### ISSUE TITLE
Quarkus 1.5.1 Final: Failed to inject ManagedExecutor

### ISSUE THREAD

**Issue by overthetop** [quarkusio/quarkus#10013]
**Describe the bug**
That was working fine in 1.4.2. I want to inject ManagedExecutor and use that in my code. When I try that on the 1.5.1 release, I get:
```
javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.eclipse.microprofile.context.ManagedExecutor and qualifiers [@Default]
	- java member: org.acme.getting.started.GreetingResource#managedExecutor
	- declared on CLASS bean [types=[org.acme.getting.started.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.getting.started.GreetingResource]
```
That's on a clean 1.5.1 quarkus getting starting project
`mvn io.quarkus:quarkus-maven-plugin:1.5.1.Final:create -DprojectGroupId=org.acme -DprojectArtifactId=getting-started -DclassName="org.acme.getting.started.GreetingResource" -Dpath="/hello"`

**Expected behavior**
Injecting ManagedExecutor should work

**Actual behavior**
Getting a build error

```
Failed to execute goal io.quarkus:quarkus-maven-plugin:1.5.1.Final:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.eclipse.microprofile.context.ManagedExecutor and qualifiers [@Default]
[ERROR] 	- java member: org.acme.getting.started.GreetingResource#managedExecutor
[ERROR] 	- declared on CLASS bean [types=[org.acme.getting.started.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.getting.started.GreetingResource]
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:978)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:242)
[ERROR] 	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:146)
[ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:359)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.eclipse.microprofile.context.ManagedExecutor and qualifiers [@Default]
[ERROR] 	- java member: org.acme.getting.started.GreetingResource#managedExecutor
[ERROR] 	- declared on CLASS bean [types=[org.acme.getting.started.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.getting.started.GreetingResource]
[ERROR] 	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
[ERROR] 	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:234)
[ERROR] 	... 14 more
```

**Comment by overthetop** [comment]
I had to add 
      ```
  <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-context-propagation</artifactId>
        </dependency>
```
