### ISSUE TITLE
Recording error when passing instance of Lucene's `RAMDirectory`

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#10139]
**Describe the bug**
I try to pass a `RAMDirectory` (essentially a set of byte arrays) from static to runtime via a recorder. I get this exception:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.5.1.Final:build (default) on project quarkus-lucene: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#build threw an exception: java.lang.RuntimeException: Failed to record call to method public io.quarkus.arc.runtime.BeanContainerListener dev.morling.quarkus.extensions.lucene.extension.RamDirectoryRecorder.initializeDirectory(org.apache.lucene.store.RAMDirectory,io.quarkus.runtime.ShutdownContext)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:393)
[ERROR]         at io.quarkus.deployment.steps.MainClassBuildStep.writeRecordedBytecode(MainClassBuildStep.java:372)
[ERROR]         at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:142)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalAccessException: class io.quarkus.deployment.recording.PropertyUtils$Property cannot access a member of class org.apache.lucene.util.Accountables$2 with modifiers "public"
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1165)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstanceImpl(BytecodeRecorderImpl.java:893)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstance(BytecodeRecorderImpl.java:488)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:389)
[ERROR]         ... 14 more
[ERROR] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalAccessException: class io.quarkus.deployment.recording.PropertyUtils$Property cannot access a member of class org.apache.lucene.util.Accountables$2 with modifiers "public"
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1165)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstanceImpl(BytecodeRecorderImpl.java:893)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstance(BytecodeRecorderImpl.java:488)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1096)
[ERROR]         ... 17 more
[ERROR] Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: class io.quarkus.deployment.recording.PropertyUtils$Property cannot access a member of class org.apache.lucene.util.Accountables$2 with modifiers "public"
[ERROR]         at io.quarkus.deployment.recording.PropertyUtils$Property.read(PropertyUtils.java:104)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1091)
[ERROR]         ... 20 more
[ERROR] Caused by: java.lang.IllegalAccessException: class io.quarkus.deployment.recording.PropertyUtils$Property cannot access a member of class org.apache.lucene.util.Accountables$2 with modifiers "public"
[ERROR]         at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
[ERROR]         at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:558)
[ERROR]         at io.quarkus.deployment.recording.PropertyUtils$Property.read(PropertyUtils.java:102)
[ERROR]         ... 21 more
```

**Expected behavior**
Directory instance can be passed.

**Actual behavior**
Getting the exception above.

**To Reproduce**

- Clone https://github.com/gunnarmorling/search.morling.dev
- Build the extension
- Build the project -> observe the exception

**Comment by gunnarmorling** [comment]
Note I've come to realize that passing `RAMDirectory` likely doesn't work anyways, as it's supposedly "non-serializeable" in recorder terms. I'm still leaving this issue open as I think it exposes a bug where the byte code recorder cannot deal with a specific trait of the parameter types.

**Comment by Sanne** [comment]
hi @gunnarmorling !
I think this is a matter of mistaken expectations. Could you clarify what you mean by "it exposes a bug where the byte code recorder cannot deal with a specific trait" ?

You can only record beans having simple types, and all state needs to be exposed as java bean properties. To record other types, see io.quarkus.deployment.recording.RecorderContext#registerSubstitution

**Comment by mathecruz** [comment]
I got the same issue today, I think it would be great to add a better explanation to the exception.

**Comment by mathecruz** [comment]
@Sanne could you reopen this one?

**Comment by Sanne** [comment]
@mcruzdev we generally prefer to not repurpose old issues. This one has a title relating to Lucene's RAMDirectory. I assume you're suggesting the error should be more helpful? Could you please open a dedicated issue towards that purpose, with a more fitting title and request?

BTW I don't know how feasible it is to improve on it - but if you open a new one you also have better chances to get the attention of someone that might have a better idea.

**Comment by mathecruz** [comment]
Ahh... it makes sense @Sanne, thanks for this advice. Ok, I am opening a new issue soon.
