### ISSUE TITLE
ClassNotFoundException when using narayana-jta extension in the native mode

### ISSUE THREAD

**Issue by zhfeng** [quarkusio/quarkus#10180]
**Describe the bug**
There is a ClassNotFoundException when running the application with the narayana-jta extension in the native mode.

**Expected behavior**
It should not throw a ClassNotFoundException

**Actual behavior**
```
2020-06-23 13:57:13,671 WARN  [com.arj.ats.common] (executor-thread-1) ARJUNA048004: attempt to load com.arjuna.ats.internal.arjuna.utils.SocketProcessId threw ClassNotFound. Wrong classloader?: java.lang.ClassNotFoundException: com.arjuna.ats.internal.arjuna.utils.SocketProcessId
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1184)
	at com.arjuna.common.internal.util.ClassloadingUtility.loadClass(ClassloadingUtility.java:57)
	at com.arjuna.common.internal.util.ClassloadingUtility.loadClass(ClassloadingUtility.java:85)
	at com.arjuna.common.internal.util.ClassloadingUtility.loadAndInstantiateClass(ClassloadingUtility.java:117)
	at com.arjuna.ats.arjuna.common.CoreEnvironmentBean.getProcessImplementation(CoreEnvironmentBean.java:232)
	at com.arjuna.ats.arjuna.utils.Utility.initDefaultProcess(Utility.java:329)
	at com.arjuna.ats.arjuna.utils.Utility.getProcess(Utility.java:340)
	at com.arjuna.ats.arjuna.utils.Utility.getpid(Utility.java:285)
	at com.arjuna.ats.arjuna.common.Uid.<init>(Uid.java:79)
	at com.arjuna.ats.arjuna.StateManager.<init>(StateManager.java:812)
	at com.arjuna.ats.arjuna.StateManager.<init>(StateManager.java:801)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.<init>(BasicAction.java:72)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.<init>(TwoPhaseCoordinator.java:55)
	at com.arjuna.ats.arjuna.AtomicAction.<init>(AtomicAction.java:74)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.AtomicAction.<init>(AtomicAction.java:38)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.<init>(TransactionImple.java:101)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.begin(BaseTransaction.java:98)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.begin(CDIDelegatingTransactionManager.java:74)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:106)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:92)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:339)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.getting.started.GreetingResource_Subclass.hello(GreetingResource_Subclass.zig:160)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

2020-06-23 13:57:13,671 WARN  [com.arj.ats.arjuna] (executor-thread-1) ARJUNA012209: Utility.getDefaultProcess failed

```
**To Reproduce**
1. create a simple quickstart example
```
mvn io.quarkus:quarkus-maven-plugin:1.5.2.Final:create     
    -DprojectGroupId=org.acme
    -DprojectArtifactId=getting-started
    -DclassName="org.acme.getting.started.GreetingResource"
    -Dpath="/hello"
cd getting-quickstart
```
2. add the narayana-jta extension
```
mvn quarkus:add-extension -Dextensions="narayana-jta"
```
3. modify the GreetingResource.java to add the Transactional
```java
package org.acme.getting.started;

import javax.transaction.Transactional;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Transactional
    public String hello() throws Exception {
        return "hello";
    }
}
```
4. run the native test
```
mvn -Pnative clean install
```

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux 192.168.0.110 5.6.19-300.fc32.x86_64 #1 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
 - GraalVM version (if different from Java): 
```
graalvm-ce-java8-19.3.1
```
 - Quarkus version or git rev: 
```
1.5.2.Final
```
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/zhfeng/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 1.8.0_252, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-1.fc32.x86_64/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "5.6.19-300.fc32.x86_64", arch: "amd64", family: "unix"
```

**Additional context**
(Add any other context about the problem here.)

**Comment by zhfeng** [comment]
It looks like that *com.arjuna.ats.internal.arjuna.utils.SocketProcessId" should be added in the ReflectiveClass. Also the other classes which implement the *com.arjuna.ats.arjuna.utils.Process* interface should be added.

**Comment by mmusgrov** [comment]
The default [Process implementation](https://github.com/jbosstm/narayana/blob/master/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/utils/Process.java#L41) is set to [SocketProcessId](https://github.com/jbosstm/narayana/blob/master/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/utils/Utility.java#L379). The quarkus narayana-jta extension does not [expose this item in its config](https://github.com/quarkusio/quarkus/tree/master/extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime). So for now I think it is best to just add the SocketProcessId class as a ReflectiveClassBuildItem. We can add other Process implementations if it is ever made configurable.

**Comment by mmusgrov** [comment]
I tried the reproducer on the current Quarkus master (999-SNAPSHOT) and the missing class is now found. I suspect the Quarkus team have fixed it along the way.

I don't know how Quarkus performs its magic but I'd expect it is capable of finding, and allowing, implementations of an interface to be found automatically so that the extension developer does not need to tell the build step about these implementations.

Maybe @stuartwdouglas or one of the other core team members could tell us whether the runtime provides that? Stewart, the context is that Amos wrote a simple example using 1.5.2.Final and found that in native mode narayana implementations of the Process interface (see the [previous comment](https://github.com/quarkusio/quarkus/issues/10180#issuecomment-648776949)) are not being discovered by the runtime even though the jta extension includes them?

**Comment by zhfeng** [comment]
@mmusgrov I tried with the master (999-SNAPSHOT) and it was still failed. I think you might not remove the fix and rebuild the narayana-jta extension ?

**Comment by mmusgrov** [comment]
I tried it using the latest master (building quarkus from a fresh git clone). The steps I tried were:

```bash
# build quarkus master (999-SNAPSHOT)
git clone https://github.com/quarkusio/quarkus
cd quarkus
./mvnw -Dquickly

# create a reproducer
 cd ..
 mvn io.quarkus:quarkus-maven-plugin:1.5.2.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=getting-started     -DclassName="org.acme.getting.started.GreetingResource"     -Dpath="/hello"
 cd getting-started
 vi pom.xml # change version from 1.5.2.Final to 999-SNAPSHOT and quarkus-universe-bom to quarkus-bom

# use GRAALVM to build a native exe:
 export GRAALVM_HOME=/usr/local/graalvm-ce-java8-19.3.2
 export JAVA_HOME=${GRAALVM_HOME}
 export PATH=${GRAALVM_HOME}/bin:$PATHexport PATH=${GRAALVM_HOME}/bin:$PATH
 mvn -Pnative clean install

# run it
 ./target/getting-started-1.0-SNAPSHOT-runner &
 curl http://localhost:8080/hello
```

The output is "hello".

[1] shows how I updated the reproducer to use 999-SNAPSHOT. Will you describe the steps you used to demonstrate the problem with the current quarkus master branch.

[1]
15,16c15,16
<     <quarkus-plugin.version>1.5.2.Final</quarkus-plugin.version>
<     <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
---
>     <quarkus-plugin.version>999-SNAPSHOT</quarkus-plugin.version>
>     <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
18c18
<     <quarkus.platform.version>1.5.2.Final</quarkus.platform.version>
---
>     <quarkus.platform.version>999-SNAPSHOT</quarkus.platform.version>

**Comment by zhfeng** [comment]
@mmusgrov I think you missed 
* step 2 add the narayana-jta extension
* step 3 modify the GreetingResource.java to add the ```@Transactional```

yeah, ```curl http://localhost:8080/hello``` returns OK but you can find the exception in the console of ```./target/getting-started-1.0-SNAPSHOT-runner```

**Comment by zhfeng** [comment]
@mmusgrov It seems that the reproducer just prints the WARN message and will not throw the exception to fail the processing.

**Comment by zhfeng** [comment]
@mmusgrov since the PR is closed. Do you mind if I create a new one to try to fix this issue ?
