### ISSUE TITLE
URL is not defined for datasource error when using quarkus.datasource.db-kind=postgresql on a properties file

### ISSUE THREAD

**Issue by YusufIsah** [quarkusio/quarkus#10194]
**Description**
- warn that you used an incorrect property name
- in the URL not defined error, we could give you the property name to use.
I was confused because I thought I was using the correct datasource url, unknowingly that I was missing jdbc in the url. At the very least, we could have the above message as part of the error message

**Implementation ideas**
(If you have any implementation ideas, they can go here.)

**Comment by ejba** [comment]
Could a warning telling the `quarkus.datasource.jdbc.url` property is empty solve the problem?

**Comment by emmanuelbernard** [comment]
@YusufIsah can you paste your exception stack, that would help to do a quick win on this one. Trying to find where trhings are triggered to opportinustically have the right message if we can't do holistically yet

**Comment by emmanuelbernard** [comment]
```
quarkus.datasource.db-kind=postgresql

quarkus.datasource.url=jdbc:postgresql://localhost:5432/dbname

quarkus.datasource.username=username

quarkus.datasource.password=password

quarkus.datasource.jdbc.min-size=4

quarkus.datasource.jdbc.max-size=16


error log:

Jun 20, 2020 3:26:16 AM io.quarkus.application

ERROR: Failed to start application

io.quarkus.runtime.configuration.ConfigurationException: URL is not defined for datasource <default>

        at io.quarkus.agroal.runtime.DataSources.doCreateDataSource(DataSources.java:146)

        at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:123)

        at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:120)

        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)

        at io.quarkus.agroal.runtime.DataSources.getDataSource(DataSources.java:120)

        at io.quarkus.agroal.runtime.DataSources.fromName(DataSources.java:116)

        at io.quarkus.agroal.runtime.AgroalRecorder.agroalDataSourceSupplier(AgroalRecorder.java:23)

        at io.quarkus.deployment.steps.AgroalProcessor$generateDataSourceBeans-109901991.deploy_0(AgroalProcessor$generateDataSourceBeans-109901991.zig:77)

        at io.quarkus.deployment.steps.AgroalProcessor$generateDataSourceBeans-109901991.deploy(AgroalProcessor$generateDataSourceBeans-109901991.zig:36)

        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:380)

        at io.quarkus.runtime.Application.start(Application.java:90)

        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)

        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)

        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)

        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)

        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.base/java.lang.reflect.Method.invoke(Method.java:566)

        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:144)

        at java.base/java.lang.Thread.run(Thread.java:834)


Jun 20, 2020 3:26:17 AM io.quarkus.runtime.ApplicationLifecycleManager run

ERROR: Error running Quarkus application

java.lang.RuntimeException: Failed to start quarkus

        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:553)

        at io.quarkus.runtime.Application.start(Application.java:90)

        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)

        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)

        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)

        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)

        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.base/java.lang.reflect.Method.invoke(Method.java:566)

        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:144)

        at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: io.quarkus.runtime.configuration.ConfigurationException: URL is not defined for datasource <default>

        at io.quarkus.agroal.runtime.DataSources.doCreateDataSource(DataSources.java:146)

        at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:123)

        at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:120)

        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)

        at io.quarkus.agroal.runtime.DataSources.getDataSource(DataSources.java:120)

        at io.quarkus.agroal.runtime.DataSources.fromName(DataSources.java:116)

        at io.quarkus.agroal.runtime.AgroalRecorder.agroalDataSourceSupplier(AgroalRecorder.java:23)

        at io.quarkus.deployment.steps.AgroalProcessor$generateDataSourceBeans-109901991.deploy_0(AgroalProcessor$generateDataSourceBeans-109901991.zig:77)

        at io.quarkus.deployment.steps.AgroalProcessor$generateDataSourceBeans-109901991.deploy(AgroalProcessor$generateDataSourceBeans-109901991.zig:36)

        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:380)

        ... 12 more
```

**Comment by geoand** [comment]
@emmanuelbernard I assume the quick win you are referring to is to warn users to use `quarkus.datasource.jdbc.url` instead of `quarkus.datasource.url`?

**Comment by emmanuelbernard** [comment]
The absolute minimal is to catch agroal's config exception and hint that maybe they use quarkus.datasource.url vs quarkus.datasource.jdbc.url.
Next level but super easy too is to check if quarkus.datasource.url is present and not quarkus.datasource.jdbc.url and raise an explicit message (vs a hint).
Ideally we could even move that from the agroal extension to the shared datasource extension that generates the build item.

**Comment by geoand** [comment]
I'll mark this as a `good first issue` then :)

**Comment by ejba** [comment]
@geoand @emmanuelbernard  Is it okay if I peek this one?

**Comment by geoand** [comment]
> @geoand @emmanuelbernard Is it okay if I peek this one?

By all means!

**Comment by emmanuelbernard** [comment]
This is an important issue to me as I don’t like usability hurdle. So go for it. I would have done it otherwise.

**Comment by ejba** [comment]
@emmanuelbernard If you feel that's important task, please take it. I don't mind at all! :)

**Comment by ejba** [comment]
I was thinking to do something like this in `Datasources` at line 142. 
What do you think @emmanuelbernard @geoand ? 

```
            if (!dataSourceJdbcRuntimeConfig.url.isPresent() && legacyDataSourceRuntimeConfig.url.isPresent()) {
                log.errorv("quarkus.datasource.%s.url` is deprecated and will be removed in a future version - it is " +
                    "recommended to switch to `quarkus.datasource.%s.jdbc.url`", dataSourceName, dataSourceName);
            } else if (!dataSourceJdbcRuntimeConfig.url.isPresent()) {
                log.errorv("'quarkus.datasource.%s.jdbc.url' property has not been defined.", dataSourceName);
            }
```

**Comment by geoand** [comment]
I propose you open a PR and in the description of that PR list the how it behaves under circumstances like this one
