### ISSUE TITLE
ContainerRequestFilter: Exception reading input stream on HTTP/2

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#10204]
**Describe the bug**
java.lang.IllegalStateException: Request has already been read when trying to read requestContext.getEntityStream() in a ContainerRequestFilter when the client calls with HTTP/2.

**Expected behavior**
Filters should be able to read the stream as per HTTP/1.x

**Actual behavior**
Exception as follows:
````
Caused by: java.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.Http2ServerRequestImpl.checkEnded(Http2ServerRequestImpl.java:215)
	at io.vertx.core.http.impl.Http2ServerRequestImpl.fetch(Http2ServerRequestImpl.java:255)
	at io.quarkus.vertx.http.runtime.ResumingRequestWrapper.fetch(ResumingRequestWrapper.java:42)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.fetch(HttpServerRequestWrapper.java:97)
	at io.undertow.vertx.VertxHttpExchange.readBlocking(VertxHttpExchange.java:467)
	at io.undertow.server.HttpServerExchange.readBlocking(HttpServerExchange.java:937)
	at io.undertow.servlet.spec.ServletInputStreamImpl.readIntoBuffer(ServletInputStreamImpl.java:178)
	at io.undertow.servlet.spec.ServletInputStreamImpl.read(ServletInputStreamImpl.java:158)
	at java.base/java.io.InputStream.readNBytes(InputStream.java:409)
	at java.base/java.io.InputStream.readAllBytes(InputStream.java:346)
	at org.acme.quickstart.MyFilter.filter(MyFilter.java:21)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:310)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)

```


**To Reproduce**
Steps to reproduce the behavior:
1. git clone https://github.com/bcluap/http2test.git
2. cd http2test
3. mvn quarkus:dev
4. curl -v http://localhost:8080/test -d"Hello world"  (ALL WORKS FINE)
3. curl --http2-prior-knowledge -v http://localhost:8080/test -d"Hello world" (ALMOST ALWAYS FAILS. SEE SERVER LOG)

**Configuration**
```properties
Blank
```

**Environment (please complete the following information):**
 1.5.2.Final
Java 14

**Comment by bcluap** [comment]
Forgot to mention this only happens when undertow is used. Removing undertow from POM and it works fine.

**Comment by geoand** [comment]
cc @stuartwdouglas

**Comment by geoand** [comment]
Is this still an issue with the latest versions of Quarkus?

**Comment by geoand** [comment]
Closing for lack of feedback.
