### ISSUE TITLE
regression from quarkus 1.2.1 - polyglot app fails with module org.graalvm.sdk does not export org.graalvm.polyglot.impl to unnamed

### ISSUE THREAD

**Issue by ghost** [quarkusio/quarkus#10226]
**Describe the bug**
Project scaffolded at https://code.quarkus.io/ - depending on io.quarkus:quarkus-core:jar:1.5.2.Final, 
and extended with polyglot code below, fails at execution with an exception:
`com.oracle.truffle.polyglot.PolyglotImpl (in unnamed module) cannot access class org.graalvm.polyglot.impl.AbstractPolyglotImpl`
The same app, but with quarkus 1.2.1, passes the test.

```
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        String out = "From JS:";
        try (Context context = Context.create()) {
            Value function = context.eval("js", "x => x+1");
            assert function.canExecute();
            int x = function.execute(41).asInt();
            out=out+x;
            System.out.println(out);
        }
        return "hello";
    }
```
I've added the following dependencies to pom.xml in the scaffolded project to enable polyglot code:
```
<dependency>
  <groupId>org.graalvm.js</groupId>
  <artifactId>js</artifactId>
  <version>19.3.1</version>
</dependency>
<dependency>
  <groupId>org.graalvm.js</groupId>
  <artifactId>js-scriptengine</artifactId>
  <version>19.3.1</version>
</dependency>
<dependency>
  <groupId>org.graalvm.truffle</groupId>
  <artifactId>truffle-api</artifactId>
  <version>19.3.1</version>
</dependency>
```
I've selected GraalVM 19.3.1 to use, because I've noted that there is dependency on it in the clean scaffolded project: 
```
$ mvn dependency:tree
...
[INFO] |  +- io.quarkus:quarkus-core:jar:1.5.2.Final:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile
[INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:1.5.2.Final:compile
[INFO] |  |  +- io.smallrye.config:smallrye-config:jar:1.7.0:compile
[INFO] |  |  |  \- io.smallrye.config:smallrye-config-common:jar:1.7.0:compile
[INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.4:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.1.0.Final:compile
[INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.1.1.Final:compile
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logging:jar:1.2.0.Final:compile
[INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:19.3.1:compile
[INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile
```

**Expected behavior**
Test is passing, i.e. JS code is executed by GraalVM and response is returned.

**Actual behavior**
Test is failing with exception.

**To Reproduce**
```
git clone https://github.com/miloslavskacel/polyglotcode-with-quarkus.git
cd polyglotcode-with-quarkus
mvn clean package
````
Test is failing.

**Environment (please complete the following information):**
```
$ uname -a
MINGW64_NT-10.0-18363 SKMW 3.0.7-338.x86_64 2019-07-03 15:16 UTC x86_64 Msys

$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)

$ ./mvnw --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\uzimskacel\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
Java version: 11.0.6, vendor: Oracle Corporation, runtime: C:\java\graalvm-ce-java11-19.3.1
Default locale: en_US, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
 - Quarkus version or git rev:  `io.quarkus:quarkus-core:jar:1.5.2.Final`
 
**Additional context**
Reported also on:
- https://stackoverflow.com/questions/62520374/com-oracle-truffle-polyglot-polyglotimpl-in-unnamed-module-cannot-access-class
- https://github.com/oracle/graal/issues/2597

Full stacktrace
```
2020-06-24 16:42:24,579 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: d698b4a3-8894-46f7-b73d-f9e48d8a348e-1: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalAccessError: superclass access check failed: class com.oracle.truffle.polyglot.PolyglotImpl (in unnamed module @0x34575a82) cannot access class org.graalvm.polyglot.impl.AbstractPolyglotImpl (in module org.graalvm.sdk) because 
module org.graalvm.sdk does not export org.graalvm.polyglot.impl to unnamed module @0x34575a82
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:515)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.IllegalAccessError: superclass access check failed: class com.oracle.truffle.polyglot.PolyglotImpl (in unnamed module @0x34575a82) cannot access class org.graalvm.polyglot.impl.AbstractPolyglotImpl (in module org.graalvm.sdk) because module org.graalvm.sdk does not export org.graalvm.polyglot.impl to unnamed module @0x34575a82
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:372)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:330)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1209)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
        at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.searchServiceLoader(Engine.java:707)
        at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.run(Engine.java:694)
        at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.run(Engine.java:668)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.graalvm.sdk/org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:668)
        at org.graalvm.sdk/org.graalvm.polyglot.Engine.access$000(Engine.java:103)
        at org.graalvm.sdk/org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:112)
        at org.graalvm.sdk/org.graalvm.polyglot.Engine.getImpl(Engine.java:264)
        at org.graalvm.sdk/org.graalvm.polyglot.Engine$Builder.build(Engine.java:502)
        at org.graalvm.sdk/org.graalvm.polyglot.Context$Builder.build(Context.java:1444)
        at org.graalvm.sdk/org.graalvm.polyglot.Context.create(Context.java:709)
        at tst.graal.ExampleResource.hello(ExampleResource.java:18)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
        ... 17 more
```

**Regression from quarkus 1.2.1**

Test is passing for quarkus 1.2.1, which is the last release passing the test. 
Older releases are failing.
Below is a change in `pom.xml` needed to make app at https://github.com/miloslavskacel/polyglotcode-with-quarkus.git
passing tests.

![image](https://user-images.githubusercontent.com/2547672/85688060-b63b9680-b6d1-11ea-9f0f-be80bdf9aa60.png)

Full `pom.xml` with quarkus 1.2.1
```
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>tst.graal</groupId>
  <artifactId>polyglotcode-with-quarkus</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>1.2.1.Final</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>1.2.1.Final</quarkus.platform.version>
    <surefire-plugin.version>2.22.1</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.graalvm.js</groupId>
      <artifactId>js</artifactId>
      <version>19.3.1</version>
    </dependency>
    <dependency>
      <groupId>org.graalvm.js</groupId>
      <artifactId>js-scriptengine</artifactId>
      <version>19.3.1</version>
    </dependency>
    <dependency>
      <groupId>org.graalvm.truffle</groupId>
      <artifactId>truffle-api</artifactId>
      <version>19.3.1</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>${surefire-plugin.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemPropertyVariables>
                    <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                  </systemPropertyVariables>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <quarkus.package.type>native</quarkus.package.type>
      </properties>
    </profile>
  </profiles>
</project>
```

**Comment by antonliauchuk-tealium** [comment]
reproduced the same issue with 1.5.2.Final version.

**Comment by frank-dspeed** [comment]
same issue with 

```bash
mvn io.quarkus:quarkus-maven-plugin:1.8.1.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=config-quickstart \
    -DclassName="org.acme.config.GreetingResource" \
    -Dpath="/greeting"
cd config-quickstart
```

**Comment by gdhokamp** [comment]
Just being curious. Are there any plans to fix this bug in the near future?

**Comment by frank-dspeed** [comment]
@gdhokamp i do not think so it is the structure of quarkus you need to code a graal-sdk extension to use that. You can how ever fix some of the problems that quarkus has via gradle as it allows better exclusion and other deep package replacements.

overall if you want to use quarkus you can only go for a own extension.

**Comment by frank-dspeed** [comment]
we should merge this issue with this https://github.com/quarkusio/quarkus/issues/9634

**Comment by ivpal** [comment]
I have some issue with 2.4.2.Final

**Comment by ninaHerpertz** [comment]
I have too in Version 2.4.1 Final 

The exception looks a bit different but I was pointed to this thread. This is what I am getting, after including graalvm during startup:

`2021-12-16 09:28:34,351 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.NoSuchMethodError: 'org.graalvm.polyglot.Value org.graalvm.polyglot.impl.AbstractPolyglotImpl$APIAccess.newValue(java.lang.Object, org.graalvm.polyglot.impl.AbstractPolyglotImpl$AbstractValueImpl)'
	at com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:146)
	at org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:233)
	at org.graalvm.polyglot.Engine$1.loadAndValidateProviders(Engine.java:821)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:794)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:768)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:768)
	at org.graalvm.polyglot.Engine.access$000(Engine.java:109)
	at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:133)
	at org.graalvm.polyglot.Engine.getImpl(Engine.java:320)
	at org.graalvm.polyglot.HostAccess$Builder.targetTypeMapping(HostAccess.java:996)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.createNashornHostAccess(GraalJSScriptEngine.java:104)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.<clinit>(GraalJSScriptEngine.java:99)
	at com.oracle.truffle.js.scriptengine.GraalJSEngineFactory.getScriptEngine(GraalJSEngineFactory.java:180)
	at com.oracle.truffle.js.scriptengine.GraalJSEngineFactory.getScriptEngine(GraalJSEngineFactory.java:57)
	at java.scripting/javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:241)
	at emilfrey.backend.matching.control.RuleEvaluationVariablesRepo.init(RuleEvaluationVariablesRepo.java:36)
	at emilfrey.backend.matching.control.RuleEvaluationVariablesRepo_Subclass.init$$superforward1(RuleEvaluationVariablesRepo_Subclass.zig:278)
	at emilfrey.backend.matching.control.RuleEvaluationVariablesRepo_Subclass$$function$$5.apply(RuleEvaluationVariablesRepo_Subclass$$function$$5.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:516)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at emilfrey.backend.matching.control.RuleEvaluationVariablesRepo_Subclass.init(RuleEvaluationVariablesRepo_Subclass.zig:724)
	at emilfrey.backend.matching.control.RuleEvaluationVariablesRepo_Observer_init_c6e577ab5da11c32214e7d0c965f6089ddc75405.notify(RuleEvaluationVariablesRepo_Observer_init_c6e577ab5da11c32214e7d0c965f6089ddc75405.zig:147)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:322)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:304)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:80)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:1060)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by roudra** [comment]
Facing a similar problem with 2.9.2 as well.

settings.gradle
```
quarkusPluginVersion=2.9.2.Final
quarkusPlatformVersion=2.9.2.Final

quarkusPlatformArtifactId=quarkus-bom
quarkusPluginId=io.quarkus
quarkusPlatformGroupId=io.quarkus.platform

lombok=1.18.24
karateVersion=1.2.0
testContainerVersion=1.17.2
graalvmPluginVersion=22.0.0.2
```

build.gradle

    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    
    implementation 'io.quarkus:quarkus-kubernetes'

    implementation 'io.quarkus:quarkus-resteasy-reactive'
    implementation 'io.quarkus:quarkus-resteasy-reactive-jackson'
    implementation 'io.quarkus:quarkus-arc'

    implementation "io.quarkus:quarkus-smallrye-health"
    implementation 'io.quarkus:quarkus-smallrye-openapi'

    compileOnly "org.projectlombok:lombok:${lombok}"
    annotationProcessor "org.projectlombok:lombok:${lombok}"

    testCompileOnly "org.projectlombok:lombok:${lombok}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombok}"

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'io.quarkus:quarkus-jacoco'
    testImplementation "com.intuit.karate:karate-junit5:${karateVersion}"
    testImplementation 'org.testcontainers:junit-jupiter'


    //Added below lines to remove error with Karate graalvm.js
    implementation "org.graalvm.js:js:${graalvmPluginVersion}"
    implementation "org.graalvm.js:js-scriptengine:${graalvmPluginVersion}"
    implementation "org.graalvm.sdk:graal-sdk:${graalvmPluginVersion}"
`

**Comment by frank-dspeed** [comment]
@roudra i solved it via building quarkus projects as uber jar and then use that in a example application like this
https://www.graalvm.org/22.1/reference-manual/embed-languages/#build-native-images-from-polyglot-applications

polyglot with other languages i my self was not able to understand whats wrong with quarkus or how quarkus works. but the low level graalvm builds it self to work always without problems.

**Comment by roudra** [comment]
> polyglot with other languages i my self was not able to understand whats wrong with quarkus or how quarkus works. but the low level graalvm builds it self to work always without problems.

Thank you @frank-dspeed for the suggestion. I'll try it. Do I skip tests to create the UberJar though? Coz my problem is with test itself.

I was digging up more on this topic and came across a suggestion to add graalvm classes in parent first class loader. So adding the below line in application.properties seems to resolve(?)/work-around this problem 
`
quarkus.class-loading.parent-first-artifacts = org.graalvm.sdk:graal-sdk,org.graalvm.js:js,org.graalvm.truffle:truffle-api
`

Still trying to figure out the root cause though.

**Comment by geoand** [comment]
Any chance you could try https://github.com/quarkusio/quarkus/pull/26171 ?

**Comment by geoand** [comment]
We don't support Truffle in any way, what I did simply ensures that Truffle can be loaded by the JVM properly - nothing more

**Comment by frank-dspeed** [comment]
@geoand if you do not support truffle why do you got so much extension that need it? for example the Camel one which i used to get my builds working as inspiration?

In Fact if quarkus does use graalvm wording anywhere without supporting truffle that would be a bad joke as that also blocks java on java and so on everything graalvm stands for.

**Comment by geoand** [comment]
Not exactly sure what you are referring to, but in all our material we explicitly mention GraalVM native-image. We never claimed to support the entirety of the (amazing) GraalVM project.

**Comment by maxandersen** [comment]
Hi @frank-dspeed, graalvm is a big project with multiple aspects. Graalvm native-image is what Quarkus core team uses and focus on. 

Very much aware that many like the GraalVM Truffle features, and welcome anyone who is up for contributing more dedicated Truffle support but we all have to prioritize our time.

thus if you are interested in helping out and contribute fixes or separate extensions I’m happy to help you do that but please do realize Quarkus core GraalVM support is focusing on native-image parts of GraalVM.

**Comment by gsmet** [comment]
Always better to try things before we merge them :).

There is some advice here on how to do it: https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#building-main - except you have to build @geoand 's branch, not `main`.
