### ISSUE TITLE
Issue with dex: OIDC server is not available at the 'quarkus.oidc.auth-server-url' URL

### ISSUE THREAD

**Issue by wgresshoff** [quarkusio/quarkus#10227]
**Describe the bug**
The bug was already discussed here:
https://groups.google.com/forum/?oldui=1#!topic/quarkus-dev/64RNvIIu9XQ

**Expected behavior**
Quarkus service starts 

**Actual behavior**
The services doesn't start, because there is a problem with the OIDC server

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus:
  http:
    auth:
      form:
        enabled: false
      policy:
        user-policy1:
          roles-allowed: everything
      permission:
        roles1:
          paths: /index.xhtml
          policy: user-policy1
  oidc:
    auth-server-url: https://oidc.k8s.wwu.de/
    client-id: service-id
    application-type: web-app
    credentials:
      secret: ***
    tls:
      verification: none

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Kubernetes cluster
 - Output of `java -version`: 11.0.6
 - GraalVM version (if different from Java): 20.0.0
 - Quarkus version or git rev: 1.5.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Additional context**
(Add any other context about the problem here.)

**Comment by sberyozkin** [comment]
@wgresshoff Hi, can you please try `https://oidc.k8s.wwu.de`, without the trailing `/' slash ?

**Comment by wgresshoff** [comment]
Yes, I tried that. It's awkward, sorry. An error comes up now, when the readiness check runs, resulting in:
2020-06-24 16:23:44,013 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /health/ready failed, error id: 16e7ae29-0f3d-4a6b-a531-3137548e0fc5-1: java.lang.RuntimeException: Multiple mechanisms present that use the same credential transport HttpCredentialTransport{transportType=AUTHORIZATION, typeTarget='bearer'}. Mechanisms are io.quarkus.oidc.runtime.OidcAuthenticationMechanism@6d7e43db and io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMechanism@71102de1
        at io.quarkus.vertx.http.runtime.security.HttpAuthenticator.<init>(HttpAuthenticator.java:76)
        at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.create(HttpAuthenticator_Bean.zig:401)
        at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.create(HttpAuthenticator_Bean.zig:461)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:79)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.arc$delegate(HttpAuthenticator_ClientProxy.zig:92)
        at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.attemptAuthentication(HttpAuthenticator_ClientProxy.zig:182)
        at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:98)
        at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:48)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)

**Comment by sberyozkin** [comment]
@wgresshoff Is it after stripping "/" ?
It should go once you remove `quarkus-smallrye-jwt` from the pom

**Comment by wgresshoff** [comment]
Yes, after stripping the trailing "/" it worked. And removing quarkus-smallrye-jwt from the pom worked, too. Thanks a lot!
But does that mean, I can't use OpenID connect to secure webapps and services in the same project (for the actual project I don't need that, but one never knows).
Now, the next problem occured, but that's a dex configuration problem.

**Comment by sberyozkin** [comment]
@wgresshoff great, let me do a small fix which will close this issue.
You can use `quarkus-oidc` to secure both types of applications, multi-tenancy feature is one way to have a single Quarkus application to deal with both the bearer tokens and code-flows, it is very flexible :-) ping us please on the forum/zulip if you'll have any questions
