### ISSUE TITLE
smallrye context propagation not usable without smallrye fault tolerance in 1.5.x

### ISSUE THREAD

**Issue by pschyma** [quarkusio/quarkus#10248]
**Describe the bug**
Context propagation does not work as described in the guide.

**Expected behavior**
Following the context propagation guide by adding `"io.quarkus:quarkus-smallrye-context-propagation"` dependency should inject a `ManagedExecutor` into instances.

**Actual behavior**
An exception is thrown at build step:
```
2020-06-25 07:45:29,192 ERROR [io.qua.dep.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.eclipse.microprofile.context.ManagedExecutor and qualifiers [@Default]
        - java member: x.Resource#<init>()
        - declared on CLASS bean [types=[de.comline.eis.excel.ExcelResource, java.lang.Object], qualifiers=[@Default, @Any], target=x.Resource]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:978)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:242)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:146)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:359)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```
Adding `"io.quarkus:quarkus-smallrye-fault-tolerance"` to the dependencies enables Quarkus to inject the executor. 

**To Reproduce**
1. Configure a resource to use a managed executor and inject it (via constructor injection?).
2. Build the project.

**Configuration**
```properties
quarkus:
  datasource:
    db-kind: mssql
    username: ..
    password: xxx
    jdbc:
      url: jdbc:sqlserver://localhost:1433
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux voyager 5.7.5-arch1-1 #1 SMP PREEMPT Mon, 22 Jun 2020 08:10:02 +0000 x86_64 GNU/Linux` 
 - Output of `java -version`: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
 - GraalVM version (if different from Java): not used here
 - Quarkus version or git rev: 1.5.1.Final / 1.5.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
Works with 1.4.1.Final as expected.

**Comment by kenfinnigan** [comment]
@FroMage @Ladicek not sure if either of you has any thoughts on this?

**Comment by Ladicek** [comment]
:shrug:

**Comment by pschyma** [comment]
I've created a small reproducer [1]. While creating this, I noticed that it somehow depends on `quarkus-flyway`.

The reproducer can be changed to build (or start quarkusDev) by either:
- commenting the flyway dependency,
- adding the fault-tolerance depedency, or
- changing quarkus to 1.4.2.Final in gradle.properties.

[1] https://github.com/pschyma/quarkus-context-propagation-reproducer

**Comment by pschyma** [comment]
Just tried this with 1.6.0.CR1 and the project is built as expected.

**Comment by gsmet** [comment]
@pschyma so we can close this one?

**Comment by pschyma** [comment]
@gsmet I'd say: yes.

**Comment by kenfinnigan** [comment]
Thanks
