### ISSUE TITLE
ZoneOffsetTransition state changing during image generation

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#10309]
I've been experimenting with a branch that adds 3rd party library sources into the source cache (#10094), and that has triggered an issue similar to #9750.

```
Caused by: com.oracle.svm.core.util.UserError$UserException: Static field or an object referenced from a static field changed during native image generation?
  object:2014=[Ljava.time.zone.ZoneOffsetTransition;@51cbb5d  of class: java.util.concurrent.ConcurrentHashMap$Node
  reachable through:
    object: [Ljava.util.concurrent.ConcurrentHashMap$Node;@78ccb00c  of class: java.util.concurrent.ConcurrentHashMap$Node[]
    object: {2017=[Ljava.time.zone.ZoneOffsetTransition;@37d6862f, 2018=[Ljava.time.zone.ZoneOffsetTransition;@66d8e07b, 2019=[Ljava.time.zone.ZoneOffsetTransition;@17730b7e, 2020=[Ljava.time.zone.ZoneOffsetTransition;@58db713f, 2014=[Ljava.time.zone.ZoneOffsetTransition;@51cbb5d}  of class: java.util.concurrent.ConcurrentHashMap
    object: ZoneRules[currentStandardOffset=Z]  of class: java.time.zone.ZoneRules
    object: Europe/London  of class: java.time.ZoneRegion
    object: sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]  of class: sun.util.calendar.ZoneInfo
    object: 0000-12-30T16:47:04.192Z  of class: sun.util.calendar.ImmutableGregorianDate
    object: [CommonEra (C.E.) since 0000-12-30T16:47:04.192 local time]  of class: sun.util.calendar.Era
    object: [Lsun.util.calendar.Era;@225671db  of class: sun.util.calendar.Era[]
    root: sun.util.calendar.JulianCalendar$Date.setNormalizedYear(int)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.verifyTargetDidNotChange(NativeImageHeapWriter.java:130)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeReference(NativeImageHeapWriter.java:158)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.write(NativeImageHeapWriter.java:147)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeConstant(NativeImageHeapWriter.java:184)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeObject(NativeImageHeapWriter.java:377)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeHeap(NativeImageHeapWriter.java:89)
	at com.oracle.svm.hosted.image.NativeBootImage.build(NativeBootImage.java:483)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:636
```

[Longer output](https://gist.githubusercontent.com/galderz/1e841ee40a0d97f3965c92cfa7ac833d/raw/a9f56427f7ec8a27270bfab409a7bfdd0c3a6dc0/gistfile1.txt).

**Comment by galderz** [comment]
Indeed this is strictly related to the debug info integration. The issue happens because of a side effect of the code that inspects the files to add to source cache when inspecting a source root that is a `-source.jar`. When it does that, `SourceCache` invokes `Files.isRegularFile` which indirectly fills up the Java Time `ZoneRules.lastRulesCache`. When the image is written, the code discovers this change and complains. Not sure about the best fix yet.

**Comment by galderz** [comment]
FYI, the stacktrace to modifying `lastRulesCache` can be found [here](https://gist.github.com/galderz/d282e44307e2aef0ca61760aebc143f1).

**Comment by galderz** [comment]
This is a GraalVM issue, not a Quarkus one. Closing this, I'll open an issue in GraalVM shortly.
