### ISSUE TITLE
Received fatal alert: certificate_required

### ISSUE THREAD

**Issue by KMUS** [quarkusio/quarkus#10325]
This only affects the native image generation. 

As long as the project sticks with GraalVM version 19.3.x, everything works fine. After updating GraalVM to the Quarkus supported version 20.0.0, the produced native image always fails and complains a certificate is required. Nothing was changed except the GraalVM version, that includes the new keystore and truststore now.

```LogManager error of type GENERIC_FAILURE: Received fatal alert: certificate_required
java.io.IOException: Cannot send data to x.y.z:1234
        at biz.paluch.logging.gelf.intern.sender.GelfTCPSender.sendMessage(GelfTCPSender.java:126)
        at biz.paluch.logging.gelf.jul.GelfLogHandler.publish(GelfLogHandler.java:135)
        at biz.paluch.logging.gelf.jboss7.JBoss7GelfLogHandler.publish(JBoss7GelfLogHandler.java:108)
        at org.jboss.logmanager.handlers.DelayedHandler.publishToChildren(DelayedHandler.java:208)
        at org.jboss.logmanager.handlers.DelayedHandler.doPublish(DelayedHandler.java:49)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:316)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:748)
        at org.jboss.logmanager.Logger.log(Logger.java:706)
        at org.jboss.logmanager.Logger.log(Logger.java:719)
        at org.jboss.logging.JBossLogManagerLogger.doLog(JBossLogManagerLogger.java:42)
        at org.jboss.logging.Logger.info(Logger.java:955)
        at x.y.service.scheduler.vehicle.CsvDownloader.downloadVehicleRest(CsvDownloader.java:54)
        at x.y.service.scheduler.vehicle.CsvDownloader.downloadAll(CsvDownloader.java:124)
        at x.y.service.scheduler.vehicle.CsvDownloader.downloadAll(CsvDownloader.java:107)
        at x.y.service.scheduler.vehicle.Scheduler.importCsv(Scheduler.java:50)
        at x.y.service.scheduler.vehicle.Scheduler.onStart(Scheduler.java:37)
        at x.y.service.scheduler.vehicle.Scheduler_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(Scheduler_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:147)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:113)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:77)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:338)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_required
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:180)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:668)
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:623)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:441)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:420)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634)
        at biz.paluch.logging.gelf.intern.sender.GelfTCPSSLSender.read(GelfTCPSSLSender.java:121)
        at biz.paluch.logging.gelf.intern.sender.GelfTCPSSLSender.write(GelfTCPSSLSender.java:83)
        at biz.paluch.logging.gelf.intern.sender.GelfTCPSender.sendMessage(GelfTCPSender.java:114)
        ... 37 more
```
Keystore and Truststore include the required certificate to communicate with Graylog.
```
cp cacerts /opt/sdk/graalvm-ce-java11-20.0.0/lib/security
cp jssecacerts /opt/sdk/graalvm-ce-java11-20.0.0/lib/security
```

**Configuration**
```
Installed features: [agroal, cdi, hibernate-orm, hibernate-validator, jdbc-postgresql, logging-gelf, mutiny, narayana-jta, scheduler]
```
```properties
quarkus.banner.path = banner.txt

quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = xyz
quarkus.datasource.password = ${quarkus.datasource.password}
quarkus.datasource.jdbc.url = ${quarkus.datasource.jdbc.url}
quarkus.datasource.jdbc.min-size = 3
quarkus.datasource.jdbc.max-size = 20

quarkus.hibernate-orm.log.sql = ${quarkus.hibernate-orm.log.sql}
quarkus.hibernate-orm.jdbc.timezone = UTC
quarkus.hibernate-orm.jdbc.statement-batch-size = 1000

quarkus.log.category.\"org.hibernate.SQL\".level = ${quarkus.log.category.org.hibernate.sql}
quarkus.log.category.\"org.hibernate.type\".level = ${quarkus.log.category.org.hibernate.type}
quarkus.log.level = ${quarkus.log.level}
quarkus.log.handler.gelf.enabled = ${quarkus.log.handler.gelf.enabled}
quarkus.log.handler.gelf.host = ssl:x.y.z?keepAlive=true
quarkus.log.handler.gelf.port = 1234
quarkus.log.handler.gelf.include-full-mdc = true
quarkus.log.handler.gelf.additional-field.ServerName.value = ${server.name}
quarkus.log.handler.gelf.additional-field.ServerName.type = String
quarkus.log.handler.gelf.additional-field.ApplicationName.value = ${graylog.application.name}
quarkus.log.handler.gelf.additional-field.ApplicationName.type = String

quarkus.native.additional-build-args =\
-H:+JNI,\
-H:+AllowIncompleteClasspath,\
-H:IncludeResourceBundles=opencsv,\
-H:JNIConfigurationFiles=jni-config.json,\
-H:ResourceConfigurationFiles=resource-config.json,\
-H:ReflectionConfigurationFiles=reflect-config.json,\
-H:DynamicProxyConfigurationFiles=proxy-config.json,\
--no-fallback,\
--enable-all-security-services,\
--initialize-at-run-time=org.apache.commons.logging.impl.Log4JLogger

quarkus.scheduler.cron-type = unix

```

**Environment:**
 - Linux DESKTOP 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Picked up JAVA_TOOL_OPTIONS: -Djavax.net.ssl.keyStore=/opt/sdk/graalvm-ce-java11-20.0.0/lib/security/cacerts -Djavax.net.ssl.keyStorePassword=changeit
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
 - 1.5.2 Final
 - Picked up JAVA_TOOL_OPTIONS: -Djavax.net.ssl.keyStore=/opt/sdk/graalvm-ce-java11-20.0.0/lib/security/cacerts -Djavax.net.ssl.keyStorePassword=changeit
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /opt/sdk/graalvm-ce-java11-20.0.0
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.19.104-microsoft-standard", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Have perhaps tried Quarkus 1.6.0.CR1 with GraalVM 20.1?

**Comment by KMUS** [comment]
That did not solve the problem. Still the same exception.

**Comment by jaikiran** [comment]
When you launch the native application (after the native image has been built), can you launch it by passing `-Djavax.net.debug=all` and capturing those logs. Those logs might help us understand what's going on. More details on debugging issues like these can be found at https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/ReadDebug.html

**Comment by KMUS** [comment]
@jaikiran 

The [log](https://github.com/quarkusio/quarkus/files/4853486/debug.txt), after starting the native application. 
Hopefully this helps.

**Comment by KMUS** [comment]
Tested Quarkus 1.6.1 with still the same metnioned problem but it seems, that this is a GraalVM issue. The truststore works as expetected. The keystore on the other hand is not part of the native image. After turning client authentification off in Graylog, all works fine with the newest Graal version.
Can anybody confirm this issue?

**Comment by geoand** [comment]
Closing for lack of feedback
