### ISSUE TITLE
Unable to disable IPv6, blocks vert.x even loop

### ISSUE THREAD

**Issue by ctron** [quarkusio/quarkus#10407]
**Describe the bug**

If IPv6 is not available, it should not be used. And there should be a switch enforce disabling IPv6.

**Expected behavior**

**Actual behavior**

It blocks the vert.x event loop:

~~~
2020-07-01T12:39:09.570Z WARN  [BlockedThreadChecker] Thread Thread[vert.x-eventloop-thread-1,5,main]=Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 3699 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java)
        at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
        at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1505)
        at java.net.InetAddress.getAllByName(InetAddress.java:1364)
        at java.net.InetAddress.getAllByName(InetAddress.java:1298)
~~~

<details>
<summary>Full stack trace</summary>

~~~
2020-07-01T12:39:09.570Z WARN  [BlockedThreadChecker] Thread Thread[vert.x-eventloop-thread-1,5,main]=Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 3699 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java)
        at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
        at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1505)
        at java.net.InetAddress.getAllByName(InetAddress.java:1364)
        at java.net.InetAddress.getAllByName(InetAddress.java:1298)
        at java.net.InetAddress.getByName(InetAddress.java:1248)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
        at java.security.AccessController.doPrivileged(AccessController.java:119)
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:83)
        at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:810)
        at org.eclipse.hono.service.auth.delegating.DelegatingAuthenticationService.lambda$registerReadinessChecks$4(DelegatingAuthenticationService.java:133)
        at io.vertx.ext.healthchecks.impl.DefaultProcedure.check(DefaultProcedure.java:50)
        at io.vertx.ext.healthchecks.impl.DefaultCompositeProcedure.check(DefaultCompositeProcedure.java:61)
        at io.vertx.ext.healthchecks.impl.HealthChecksImpl.compute(HealthChecksImpl.java:145)
        at io.vertx.ext.healthchecks.impl.HealthChecksImpl.invoke(HealthChecksImpl.java:90)
        at io.vertx.ext.healthchecks.impl.HealthChecksImpl.invoke(HealthChecksImpl.java:97)
        at io.vertx.ext.healthchecks.impl.HealthCheckHandlerImpl.handle(HealthCheckHandlerImpl.java:107)
        at io.vertx.ext.healthchecks.impl.HealthCheckHandlerImpl.handle(HealthCheckHandlerImpl.java:28)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)
        at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)
        at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
        at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:109)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
        at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

~~~

</details>

**To Reproduce**
1. Run inside kubernetes (with no IPv6)
2. Resolve hostname with vert.x
3. 

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: $ uname -a
Linux iot-tenant-service-d67c5b865-2lnsj 4.18.0-147.20.1.el8_1.x86_64 #1 SMP Wed Jun 10 19:19:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: native mode, Java 11
 - GraalVM version (if different from Java): 19.3.1 and 20.1.0
 - Quarkus version or git rev: 1.5.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvn 3.6.2

**Additional context**

I already tried:

* Passing `-Djava.net.preferIPv4Stack=true` as an argument to the native image
* Passing `-Djava.net.preferIPv4Stack=true` to the quarkus image build
* Passing `-J-Djava.net.preferIPv4Stack=true` to the quarkus image build

None of the options seems to have any effect.

**Comment by jaikiran** [comment]
> I already tried:
>
>    Passing -Djava.net.preferIPv4Stack=true as an argument to the native image
>    Passing -Djava.net.preferIPv4Stack=true to the quarkus image build
>    Passing -J-Djava.net.preferIPv4Stack=true to the quarkus image build

Keeping aside Quarkus, I can't seem to get this working in a basic helloworld of Graal native image. It works in 19.3.0 but seems to be broken starting 19.3.1 and even the recent 20.x series. I'll take a look if this is expected/intentional or a bug, before reporting it to Graal team.

**Comment by jaikiran** [comment]
I've opened https://github.com/oracle/graal/issues/2645 to get inputs from the Graal team.

**Comment by geoand** [comment]
Doesn't look like there is any update from the GraalVM folks...

**Comment by jaikiran** [comment]
> Doesn't look like there is any update from the GraalVM folks...

The past few months the responses/interactions to PRs and issues in Graal repo has slowed down and isn't the same as what it used to be maybe back until December last year during the 19.2.x days.

I think they are just busy. I say that because, everytime as a last resort, when I have personally mentioned someone in the PR/issue, they have come back and responded to the issue at hand. But yes, IMO, it's not been the same as it used to be previously.

**Comment by geoand** [comment]
It seems like this has been fixed in GraalVM, so let's close for now.
