### ISSUE TITLE
URL reencoded cause problems when calling Prometheus

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#10403]
Quarkus 1.5.2.Final

I'm trying to call Prometheus to find my applications metrics

I have to make that call :  http://localhost:9090/api/v1/query?query={__name__=~".*lastTimestampScrapped"}

but so far, I always get this URL generated : 

```
2020-06-29 14:08:45,191 DEBUG [com.com.iep.mon.con.LoggingFilter] (executor-thread-1) RestClient request GET to IP http://localhost:9090/api/v1/query?query=%7B__name__%3D~%22.lastTimestampScrapped%22 Body
2020-06-29 14:08:45,253 DEBUG [com.com.iep.mon.con.LoggingFilter] (executor-thread-1) RestClient response GET Status code 400 to IP http://localhost:9090/api/v1/query?query=%7B__name__%3D~%22.lastTimestampScrapped%22 Body {"status":"error","errorType":"bad_data","error":"invalid parameter 'query': 1:36: parse e
rror: unexpected end of input inside braces"}
```

I should receive this:
```
http://localhost:9090/api/v1/query?query={__name__=~".*lastTimestampScrapped"}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"application_org_acme_microprofile_metrics_DummyChecker_lastTimestampScrapped","app_kubernetes_io_name":"iep-monitoring-junk","app_kubernetes_io_version":"latest","instance":"192.168.94.253:8080","job":"kubernetes-pods","kubernetes_namespace":"default","kubernetes_pod_name":"monitoring-junk-866bf78cb4-8wh5d","pod_template_hash":"866bf78cb4"},"value":[1593454775.08,"1593454764109"]},{"metric":{"__name__":"application_org_acme_microprofile_metrics_PrimeNumberChecker_lastTimestampScrapped","app_kubernetes_io_name":"monitoring-junk","app_kubernetes_io_version":"latest","instance":"192.168.94.253:8080","job":"kubernetes-pods","kubernetes_namespace":"default","kubernetes_pod_name":"iep-monitoring-junk-866bf78cb4-8wh5d","pod_template_hash":"866bf78cb4"},"value":[1593454775.08,"1593454764111"]}]}}
```

I try with the code bellow (I added @Encoded.. but didn't change anything)

```
@ApplicationScoped
@RegisterRestClient
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Path("/api")
public interface PrometheusRestConnector {

    @GET
    @Operation(summary = "findApplications", description = "findApplications")
    @Path("/v1/query")
    List<String> findApplications(@Encoded @QueryParam("query") String query);


```

and the call that I use :

```
@Inject
@RestClient
PrometheusRestConnector connector;
...

List<String> applications = connector.findApplications("{__name__=~\".lastTimestampScrapped\"");

applications.forEach(System.out::println);


if I use this code, I can obtain the response


//http://localhost:9090/api/v1/query?query={__name__=~".*lastTimestampScrapped"}

URIBuilder builder = new URIBuilder();
builder.setScheme("http").setHost("localhost").setPort(9090).setPath("/api/v1/query")
        .setParameter("query", "{__name__=~\".*lastTimestampScrapped\"}");
URI uri = builder.build();
HttpGet httpget = new HttpGet(uri);

CloseableHttpClient httpClient = HttpClients.createDefault();

try (CloseableHttpResponse response = httpClient.execute(httpget)) {

    // Get HttpResponse Status
    System.out.println(response.getStatusLine().toString());

    HttpEntity entity = response.getEntity();
    Header headers = entity.getContentType();
    System.out.println(headers);

    if (entity != null) {
        // return it as a String
        String result = EntityUtils.toString(entity);
        System.out.println(result);
    }

}

cronJobWithExpressionInConfig for pulling Prometheus
HTTP/1.1 200 OK
Content-Type: application/json
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"application_org_acme_microprofile_metrics_DummyChecker_lastTimestampScrapped","app_kubernetes_io_name":"iep-monitoring-junk","app_kubernetes_io_version":"latest","instance":"192.168.94.253:8080","job":"kubernetes-pods","kubernete
s_namespace":"default","kubernetes_pod_name":"iep-monitoring-junk-866bf78cb4-8wh5d","pod_template_hash":"866bf78cb4"},"value":[1593456405.226,"1593456384109"]},{"metric":{"__name__":"application_org_acme_microprofile_metrics_PrimeNumberChecker_lastTimestampScrapped","app_kubernetes_io_name":"iep-monitoring-junk
","app_kubernetes_io_version":"latest","instance":"192.168.94.253:8080","job":"kubernetes-pods","kubernetes_namespace":"default","kubernetes_pod_name":"iep-monitoring-junk-866bf78cb4-8wh5d","pod_template_hash":"866bf78cb4"},"value":[1593456405.226,"1593456384110"]}]}}


```
I try to return a String instead of List<String>

and I still obtain  errors

String applications = connector.findApplications("{__name__=~\".lastTimestampScrapped\"");

```
2020-06-29 14:46:45,267 DEBUG [com.com.iep.mon.con.LoggingFilter] (executor-thread-1) RestClient request GET to IP http://localhost:9090/api/v1/query?query=%7B__name__%3D~%22.lastTimestampScrapped%22 Body
2020-06-29 14:46:45,302 DEBUG [com.com.iep.mon.con.LoggingFilter] (executor-thread-1) RestClient response GET Status code 400 to IP http://localhost:9090/api/v1/query?query=%7B__name__%3D~%22.lastTimestampScrapped%22 Body {"status":"error","errorType":"bad_data","error":"invalid parameter 'query': 1:36: parse e
rror: unexpected end of input inside braces"}
2020-06-29 14:46:45,304 ERROR [io.qua.sch.run.SimpleScheduler] (executor-thread-1) Error occured while executing task for trigger CronTrigger [id=1_com.comact.iep.monitoring.MonitoringService_ScheduledInvoker_cronJobWithExpressionInConfig_60365d9f6d6ac7846d8456427f02fbf4ee1fac41, cron=*/15 * * * * ?]: javax.ws.
rs.WebApplicationException: Unknown error, status code 400
        at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:16)
        at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:38)
```
```

**Comment by kenfinnigan** [comment]
Can you provide some details on the use case that requires you to interact with a Prometheus endpoint of another service?

**Comment by kenfinnigan** [comment]
Also, is the data from http://localhost:9090/api/v1/query?query={__name__=~".*lastTimestampScrapped"} returned in JSON or plain text?

**Comment by survivant** [comment]
my usecase was that I needed to monitor data from Prometheus to detect if a pod was created, down... I couldn't use the health probes in those applications because they weren't implemented correctly, so I had to figure out another way.  I planned to use Prometheus to scrap those metrics and from the last timestamp, I was able to detect if the application was down or not.

Since a enter that defect months ago, I don't have the environment up anymore.  All I have is the code and output that I provided in the issue

**Comment by kenfinnigan** [comment]
Is this still an issue to be investigated or it can be closed?

**Comment by survivant** [comment]
no one works on that issue, so it will still need to be check.  so Yes it's still a open issue.

**Comment by kenfinnigan** [comment]
As the use case you describe appears to be more a work around because of incorrect health probe implementations in another application, it wouldn't be a high priority for the core team to resolve as it's very specific to your situation.

Without a way to reproduce the problem, with steps or GH projects, it requires a large amount of effort to set up to begin investigating the problem.
