### ISSUE TITLE
Jax-RS @Context UriInfo injection does not work with constructors

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#10496]
**Describe the bug**
I want to inject `@Context uriInfo:UriInfo` into my Jax-RS resource. This works when I use field injection but fails when constructor injection is used (see reproducer). With `@ApplicationScoped` beans, constructor injection works. 

**Expected behavior**
The injection of `@Context UriInfo` into the constructor should work as well. 

**Actual behavior**
Only field injection works. 

**To Reproduce**
1. Download and unzip reproducer project 
[2020-07-06_context-constructor-injection.zip](https://github.com/quarkusio/quarkus/files/4878886/2020-07-06_context-constructor-injection.zip)

2. Run `./mvnw quarkus:dev` in the root directory of the project. The application startup crashes with
```
Caused by: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.ws.rs.core.UriInfo and qualifiers [@Default]
	- java member: org.acme.ExampleResource#<init>()
	- declared on CLASS bean [types=[org.acme.ExampleResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.ExampleResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:978)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:242)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:146)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:359)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.ws.rs.core.UriInfo and qualifiers [@Default]
	- java member: org.acme.ExampleResource#<init>()
	- declared on CLASS bean [types=[org.acme.ExampleResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.ExampleResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:234)
	... 14 more
```
3. In class `ExampleResource`, comment out the constructor injection line (`#1`) and comment in the field injection (`#2`). 

**Environment (please complete the following information):**
 - Quarkus 1.5.2.Final
- OpenJDK 11
- Windows 10

**Comment by famod** [comment]
I have a smiliar problem with `org.jboss.resteasy.spi.HttpResponse` (but with Java).

> With `@ApplicationScoped` beans, constructor injection works.

Interesting, this does _not_ work for me with `HttpResponse`.

I even tried something like this without success: https://stackoverflow.com/questions/3047400/using-context-provider-and-contextresolver-in-jax-rs/35220203#35220203

**Comment by geoand** [comment]
Although it's not obvious from a user perspective,  `@Context` is used by JAX-RS as its own version of `@Inject` because JAX-RS does not depend on CDI.

So `@Context` doesn't mean anything to Arc (Quarkus' CDI implementation) which is why you see the failure. 
One more thing to note is that fields annotated with `@Context` get populated by RESTEasy (the JAX-RS implementation Quarkus uses) without any build time assistance and not by Quarkus / Arc.

This obviously isn't great from a user perspective, but there isn't much we can do in the current state.

The only thing we can do ATM, is add some documentation. @andreas-eberle would you like to contribute that?

**Comment by janmaterne** [comment]
I think the @Path annotation makes that pojo to an ApplicationScope CDI-bean.
Therefore you could inject other beans with the same scope via constructor.
For method invocation the object is reused. Values of fields could be updated, but the constructor is not called.
So the CDI runtime could detect that and creates an error.

**Comment by geoand** [comment]
`@Context` is a JAX-RS annotation and is not in any connected to CDI which is why you are seeing this behavior.

In RESTEasy Reactive we have anticipated this disconnect and have bridged the two worlds, so I'm going to close this issue as we don't plan to do the same work for RESTEasy Classic
