### ISSUE TITLE
Native image: Integration test: Google-cloud-functions: Classes that should be initialized at run time got initialized during image building

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#10491]
**Describe the bug**
I am unable to run Google cloud functions integration test successfully with any on these builder images: `quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.0.Alpha1-java11`, `quarkus/ubi-quarkus-native-image:20.1.0-java11`, `quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11`.

**Expected behavior**
The module passes tests. It is actually the only one failing for me.

**Actual behavior**

### quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.0.Alpha1-java11 :x: 

```
../../mvnw verify --fail-at-end -Dno-format -Ddocker -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.0.Alpha1-java11

[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (native-image) @ quarkus-integration-test-google-cloud-functions ---
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building fat jar: /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Checking image status quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.0.Alpha1-java11
20.1.0.0.Alpha1-java11: Pulling from quarkus/ubi-quarkus-mandrel
Digest: sha256:6f33d30726ed68a6ba0a887d19a2f246d67e8fefbda5d49acf511ce0c33a85bc
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.0.Alpha1-java11
quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.0.Alpha1-java11
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.1.0.0.Alpha1 95a434a458 (Mandrel Distribution) (Java Version 11.0.8-ea)
Warning: Ignoring server-mode native-image argument --server-shutdown.
Error: Please specify class containing the main entry point method. (see --help)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 0:0 --rm quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.0.Alpha1-java11 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:-IncludeAllTimeZones -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner
Warning: Ignoring server-mode native-image argument --no-server.
-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezonesby default.
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:56]    classlist:   3,237.59 ms,  0.96 GB
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:56]        (cap):   1,030.53 ms,  0.96 GB
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:56]        setup:   2,940.02 ms,  0.96 GB
09:17:35,584 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
09:17:36,268 INFO  [io.quarkus] quarkus-integration-test-google-cloud-functions 999-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 16.561s. 
09:17:36,268 INFO  [io.quarkus] Profile prod activated. 
09:17:36,269 INFO  [io.quarkus] Installed features: [cdi, google-cloud-functions]
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:56]     analysis:  21,558.70 ms,  2.31 GB
Error: Classes that should be initialized at run time got initialized during image building:
 io.quarkus.runtime.ExecutorRecorder the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.quarkus.runtime.ExecutorRecorder got initialized use -H:+TraceClassInitialization

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.quarkus.runtime.ExecutorRecorder the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.quarkus.runtime.ExecutorRecorder got initialized use -H:+TraceClassInitialization

    at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
    at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:518)
    at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:189)
    at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:720)
    at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
    at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:720)
    at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
    at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
    at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
```

### quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11

```
../../mvnw verify --fail-at-end -Dno-format -Ddocker -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11


[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (native-image) @ quarkus-integration-test-google-cloud-functions ---
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building fat jar: /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Checking image status quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11
20.1.0-java11: Pulling from quarkus/ubi-quarkus-native-image
Digest: sha256:16ccdff80322d2e95f430dc12253353c7543031cb11755102a46cbb0ea1156d1
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11
quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.1.0 (Java Version 11.0.7)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 0:0 --rm quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:-IncludeAllTimeZones -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner
-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezonesby default.
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:24]    classlist:   3,476.59 ms,  0.96 GB
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:24]        (cap):   1,081.74 ms,  0.96 GB
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:24]        setup:   3,133.40 ms,  0.96 GB
09:21:39,994 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
09:21:40,416 INFO  [io.quarkus] quarkus-integration-test-google-cloud-functions 999-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 12.627s. 
09:21:40,416 INFO  [io.quarkus] Profile prod activated. 
09:21:40,417 INFO  [io.quarkus] Installed features: [cdi, google-cloud-functions]
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:24]     analysis:  16,386.03 ms,  1.72 GB
Error: Classes that should be initialized at run time got initialized during image building:
 io.quarkus.runtime.ExecutorRecorder the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.quarkus.runtime.ExecutorRecorder got initialized use -H:+TraceClassInitialization

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.quarkus.runtime.ExecutorRecorder the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.quarkus.runtime.ExecutorRecorder got initialized use -H:+TraceClassInitialization

    at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
    at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:518)
    at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:187)
    at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:720)
    at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
    at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:720)
    at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
    at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
    at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
```

### quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11

```
../../mvnw verify --fail-at-end -Dno-format -Ddocker -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11


[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (native-image) @ quarkus-integration-test-google-cloud-functions ---
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building fat jar: /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Checking image status quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11
19.3.1-java11: Pulling from quarkus/ubi-quarkus-native-image
Digest: sha256:9e2dd59c82db091bb90fd0ee60530291a5ecc201ebc718ffcc59ab0f406e47ea
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11
quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.3.1 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /root/quarkus/integration-tests/google-cloud-functions/target/quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 0:0 --rm quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:-IncludeAllTimeZones -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:24]    classlist:   3,460.71 ms
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:24]        (cap):   1,247.35 ms
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:24]        setup:   3,150.50 ms
09:19:33,745 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
09:19:34,174 INFO  [io.quarkus] quarkus-integration-test-google-cloud-functions 999-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 13.000s. 
09:19:34,175 INFO  [io.quarkus] Profile prod activated. 
09:19:34,175 INFO  [io.quarkus] Installed features: [cdi, google-cloud-functions]
[quarkus-integration-test-google-cloud-functions-999-SNAPSHOT-runner:24]     analysis:  16,602.31 ms
Error: Classes that should be initialized at run time got initialized during image building:
 io.quarkus.runtime.ExecutorRecorder the class was requested to be initialized at build time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.quarkus.runtime.ExecutorRecorder got initialized use -H:+TraceClassInitialization

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.quarkus.runtime.ExecutorRecorder the class was requested to be initialized at build time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.quarkus.runtime.ExecutorRecorder got initialized use -H:+TraceClassInitialization

    at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
    at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:510)
    at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:187)
    at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:710)
    at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
    at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:710)
    at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
    at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
    at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
```

**To Reproduce**
Clone 1.6 branch, build with `./mvnw clean install -DskipTests` and then run the aforementioned test.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Red Hat Enterprise Linux Server release 7.8,  3.10.0-1127.el7.x86_64
 - Output of `java -version`: OpenJDK 11.0.8-ea+7
 - GraalVM version (if different from Java): Used various builder images, see above
 - Quarkus version or git rev:  1.6 branch, HEAD cdfd67cff

**Additional context**
OpenJDK 11.0.8-ea+7 used as packaged in [Mandrel](https://github.com/graalvm/mandrel/releases/tag/mandrel-20.1.0.0.Alpha1)

**Comment by geoand** [comment]
cc @loicmathieu

**Comment by loicmathieu** [comment]
@Karm Google Cloud Functions didn't support native image deployment.
There is no native runtime inside Google Cloud Functions.

If you can tu use native image inside GCP, you better use RESTEasy and deploy a native image using Cloud Build.

**Comment by galderz** [comment]
I've just seen this fail again. 

Is something being done about this? If it's not meant to work, it should be removed/ignored so that it doesn't pollute test runs.

**Comment by galderz** [comment]
Btw, same as Karm, I was just calling maven verify with `-Dnative`, no project or specific profile. I can easily skip this, but my previous comment was more directed at Quarkus itself individually excluding projects, or not calling the native image build step for projects that don't have `@QuarkusTest` inside.
