### ISSUE TITLE
Join table inheritance  Annotation  @PrimaryKeyJoinColumn raise exception

### ISSUE THREAD

**Issue by pmdeville** [quarkusio/quarkus#10500]
**Describe the bug**

Exception : ERROR [io.qua.dep.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: org.hibernate.AnnotationException: SecondaryTable JoinColumn cannot reference a non primary key

When using Join table inheritance strategy in the following context :

- the primary key column name of the base table is different from the primary key column  in the child table

-  this means you need to annotate the child entity with @PrimaryKeyJoinColumn(name= "CHILD_TABLE_ID"  referencedColumnName = "BASE_TABLE_ID")
 
it is not possible to reference the child table in another entity. you must used the base table

**Expected behavior**

No error when running the application

**Actual behavior**

Exception raised by quarkus

`
Listening for transport dt_socket at address: 5005
2020-07-06 16:40:22,145 WARN  [io.qua.dep.QuarkusAugmentor] (main) Using Java versions older than 11 to build Quarkus applications is deprecated and will be disallowed in a future release!
2020-07-06 16:40:22,825 INFO  [org.jbo.threads] (main) JBoss Threads version 3.1.1.Final
2020-07-06 16:40:23,370 INFO  [org.hib.Version] (build-12) HHH000412: Hibernate ORM core version 5.4.14.Final
2020-07-06 16:40:25,736 INFO  [org.hib.Version] (Quarkus Main Thread) HHH000412: Hibernate ORM core version 5.4.14.Final
2020-07-06 16:40:25,758 INFO  [org.hib.ann.com.Version] (Quarkus Main Thread) HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2020-07-06 16:40:25,825 INFO  [org.hib.dia.Dialect] (Quarkus Main Thread) HHH000400: Using dialect: org.hibernate.dialect.Oracle10gDialect
2020-07-06 16:40:26,919 ERROR [io.qua.dep.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: org.hibernate.AnnotationException: SecondaryTable JoinColumn cannot reference a non primary key
        at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
        at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:110)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:87)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:268)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:40)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:129)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:82)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:119)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:56)
Caused by: org.hibernate.AnnotationException: SecondaryTable JoinColumn cannot reference a non primary key
        at org.hibernate.cfg.annotations.TableBinder.bindFk(TableBinder.java:612)
        at org.hibernate.cfg.JoinedSubclassFkSecondPass.doSecondPass(JoinedSubclassFkSecondPass.java:43)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processFkSecondPassesInOrder(InFlightMetadataCollectorImpl.java:1764)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1655)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:286)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:321)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:114)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:86)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:49)
        at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$4.created(HibernateOrmRecorder.java:77)
        at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:106)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources30.deploy_0(ArcProcessor$generateResources30.zig:400)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources30.deploy(ArcProcessor$generateResources30.zig:36)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:471)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at com.goodyear.pe.processor.core.system.ProcessorSystemController.startInstance(ProcessorSystemController.java:67)
        at com.goodyear.pe.spirit.processor.app.ApplicationMain.main(ApplicationMain.java:85)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:99)
        at java.lang.Thread.run(Thread.java:748)

2020-07-06 16:40:26,919 INFO  [io.qua.dep.dev.DevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
2020-07-06 16:40:26,920 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:99)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at com.goodyear.pe.processor.core.system.ProcessorSystemController.startInstance(ProcessorSystemController.java:67)
        at com.goodyear.pe.spirit.processor.app.ApplicationMain.main(ApplicationMain.java:85)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:512)
        ... 16 more
Caused by: org.hibernate.AnnotationException: SecondaryTable JoinColumn cannot reference a non primary key
        at org.hibernate.cfg.annotations.TableBinder.bindFk(TableBinder.java:612)
        at org.hibernate.cfg.JoinedSubclassFkSecondPass.doSecondPass(JoinedSubclassFkSecondPass.java:43)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processFkSecondPassesInOrder(InFlightMetadataCollectorImpl.java:1764)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1655)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:286)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:321)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:114)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:86)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:49)
        at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$4.created(HibernateOrmRecorder.java:77)
        at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:106)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources30.deploy_0(ArcProcessor$generateResources30.zig:400)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources30.deploy(ArcProcessor$generateResources30.zig:36)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:471)
        ... 16 more

**To Reproduce**

1. Creeate 2 entities with join table inheritance as follow 

` 
/*
** base table
 */
@Entity(name = "TB_BASE_OBJECT")
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(name = "OBJECT_TYPE", discriminatorType = DiscriminatorType.INTEGER)
public class TbBaseObject implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "BASE_OBJECT_ID", nullable = false)
    private Long id;

    @Column(name = "OBJECT_TYPE, nullable = false)
    private Integer objectType;

  // getter and setter
  // ...

}

/**
 * Child table where the primary key  column name is not the same name as the one in the base table
 */
@Entity
@Table(name = "TB_CHILD_OBJECT")
@DiscriminatorValue(value = "8")
@PrimaryKeyJoinColumn(name = "CHILD_OBJECT_ID", referencedColumnName = "BASE_OBJECT_ID")
public class TBChildObject extends TbBaseObject {
// specific column of this table
}

@Entity
@Table(name = "TB_TABLE_WITH_REF")
public class TbTableWithRef {
// primarykey and column definitions
// ...

// reference to the child table
    @JoinColumn(name = "CHILD_OBJECT_ID", referencedColumnName = "CHILD_OBJECT_ID")
    @ManyToOne
    private TBChildObject referenceToChildObject;

// specific column of this table
}

`

2.  mvn quarkus:dev

**Configuration**
```properties

# The broker url of the jms connection factory available in quarkus container.
quarkus.qpid-jms.url=amqp://localhost:60618
quarkus.qpid-jms.username=karaf
quarkus.qpid-jms.password=*****

# database connection
quarkus.datasource.db-kind=other
quarkus.datasource.jdbc.driver=oracle.jdbc.driver.OracleDriver
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@localhost1521:DEV
quarkus.datasource.username=devuser
quarkus.datasource.password=****

```

**Comment by pmdeville** [comment]
with 1.7.0 no problem anymore
