### ISSUE TITLE
OutOfMemoryError in Parameterized test

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#10540]
I have a fairly straight forward set of tests using parameters: (basic at the moment, but will of course make more meaningful params)

```
@QuarkusTest
@QuarkusTestResource(TestResourceLifecycleManager.class)
class TimemanagerSanitizerTest extends RunningServerTest {
	
	TimemanagerSanitizer sanitizer;
	
	public TimemanagerSanitizerTest(TimemanagerSanitizer sanitizer){
		this.sanitizer = sanitizer;
	}
	
	private static TimeManager emptyTimeManager =  new TimeManager();
	
	private static Object[][] args() {
		return new Object[][] {
			new Object[]{null, null},
			new Object[]{emptyTimeManager.clone(), emptyTimeManager.clone()},
		};
	}
	
	@ParameterizedTest
	@MethodSource("args")
	public void testTimeManagerSanitizer(TimeManager given, TimeManager expectedSanitized){
		TimeManager sanitized = sanitizer.sanitize(given);
		
		assertEquals(expectedSanitized, sanitized);
		
		TimeManager deSanitized = sanitizer.deSanitize(sanitized);
		
		assertEquals(given, deSanitized);
	}
}
```
The first set of parameters (null, null) runs fine, but when the newly created objects are used, I get the following exception:

```
Jul 07, 2020 4:59:17 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-jupiter' failed to execute tests
org.junit.platform.commons.JUnitException: Error executing tests for engine junit-jupiter
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	... 34 more
Caused by: java.lang.OutOfMemoryError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	... 35 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
	at java.lang.StringBuffer.append(StringBuffer.java:367)
	at java.io.StringWriter.write(StringWriter.java:94)
	at com.thoughtworks.xstream.core.util.QuickWriter.flush(QuickWriter.java:73)
	at com.thoughtworks.xstream.io.xml.PrettyPrintWriter.flush(PrettyPrintWriter.java:346)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1284)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1269)
	at io.quarkus.test.junit.internal.XStreamDeepClone.doClone(XStreamDeepClone.java:48)
	at io.quarkus.test.junit.internal.XStreamDeepClone.clone(XStreamDeepClone.java:34)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:615)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestTemplateMethod(QuarkusTestExtension.java:537)
	at org.junit.jupiter.engine.descriptor.TestTemplateInvocationTestDescriptor$$Lambda$359/984568990.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall$$Lambda$123/1730252446.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$$Lambda$272/1936416907.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:92)
	at org.junit.jupiter.engine.descriptor.TestTemplateInvocationTestDescriptor$$Lambda$359/984568990.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall$$Lambda$123/1730252446.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$$Lambda$272/1936416907.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
```

This happens after instantiation but before the test code is run. Any ideas?

**Comment by geoand** [comment]
Passing parameters into Quarkus tests is generally problematic due to fact that the actual test runs on a different ClassLoader, which means we need to deep clone the parameters into that ClassLoader.

**Comment by geoand** [comment]
What does `TimemanagerSanitizer` look like?

**Comment by GregJohnStewart** [comment]
Through debugging I have seen that it gets wired in fine, but doesn't get to the actual test code before the exception.

TimeManagerSanitizer (Now Anitizer, for being both a de/sanitizer) looks like this: https://github.com/GregJohnStewart/task-timekeeper/blob/webserver-work/WebServer/Server/src/main/java/com/gjs/taskTimekeeper/webServer/server/validation/sanitize/TimemanagerAnitizer.java

```
@ApplicationScoped
public class TimemanagerAnitizer extends Anitizer<TimeManager> {
	@Inject
	HTMLAnitizer htmlAnitizer;
	
	private Map<String, String> anitizeAtts(Map<String, String> atts, AnitizeOp op) {
		if(atts == null) {
			return null;
		}
		return atts.entrySet().stream().collect(Collectors.toMap(
			entry->htmlAnitizer.anitize(entry.getKey(), op),
			entry->htmlAnitizer.anitize(entry.getValue(), op)
		));
	}
	
	@Override
	public TimeManager anitize(
		TimeManager manager,
		AnitizeOp op
	) {
		if(manager == null) {
			return null;
		}
		
		for(Task task : manager.getTasks()) {
			task.setName(new Name(this.htmlAnitizer.anitize(task.getName().getName(), op)));
			task.setAttributes(this.anitizeAtts(task.getAttributes(), op));
		}
		
		for(WorkPeriod period : manager.getWorkPeriods()) {
			period.setAttributes(
				this.anitizeAtts(period.getAttributes(), op)
			);
		}
		
		return manager;
	}
	
	@Override
	public TimeManager deSanitize(TimeManager object) {
		return this.anitize(object, AnitizeOp.DESANITIZE);
	}
	
	@Override
	public TimeManager sanitize(TimeManager object) {
		return this.anitize(object, AnitizeOp.SANITIZE);
	}
}
```

**Comment by geoand** [comment]
I don't see anything obviously wrong here...

**Comment by GregJohnStewart** [comment]
Looks like it's an issue when it is.... serializing the data into xml? I don't know the workings of how this works, but seems an odd choice to me

**Comment by GregJohnStewart** [comment]
Ah I gotcha. This object happens to do a deep clone with `clone()`, but that of course isn't always the case. Is there a way to use the same serialization methods that the rest endpoints use, potentially?

**Comment by geoand** [comment]
Is this still an issue with the latest Quarkus version?

**Comment by geoand** [comment]
Closing for lack of feedback
