### ISSUE TITLE
Agroal health check blocks endpoint

### ISSUE THREAD

**Issue by seseso** [quarkusio/quarkus#10625]
**Describe the bug**
Trying to access /health endpoint but it returns nothing and server logs a bunch of warnings:

2020-07-10 00:17:02,682 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-worker-thread-1,5,main]=Thread[vert.x-worker-thread-1,5,main] has been blocked for 173021 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.6/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:447)
	at java.base@11.0.6/java.util.concurrent.FutureTask.get(FutureTask.java:190)
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:262)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:200)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:81)
	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck.call(DataSourceHealthCheck.java:47)
	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy.call(DataSourceHealthCheck_ClientProxy.zig:154)
	at io.smallrye.health.SmallRyeHealthReporter.jsonObject(SmallRyeHealthReporter.java:187)
	at io.smallrye.health.SmallRyeHealthReporter.fillCheck(SmallRyeHealthReporter.java:174)
	at io.smallrye.health.SmallRyeHealthReporter.processChecks(SmallRyeHealthReporter.java:162)
	at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:140)
	at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:99)
	at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getHealth(SmallRyeHealthReporter_ClientProxy.zig:339)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.getHealth(SmallRyeHealthHandler.java:11)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.doHandle(SmallRyeHealthHandlerBase.java:38)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:29)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.handle(SmallRyeHealthHandler.java:7)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:17)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$932/0x00000008406c8040.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.ContextImpl$$Lambda$921/0x0000000840693840.run(Unknown Source)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)

**Expected behavior**
Accessing /health should return a JSON

**Actual behavior**
Returns nothing and hangs up

**To Reproduce**
1.Access to /health 

**Configuration**
Extensions used:
[agroal, cache, cdi, mutiny, narayana-jta, rest-client, resteasy, resteasy-jackson, security, smallrye-context-propagation, smallrye-health, smallrye-jwt, smallrye-metrics, smallrye-openapi, smallrye-reactive-messaging, smallrye-reactive-messaging-amqp, swagger-ui, vertx, vertx-web]

Database: Oracle (yes, the Agroal datasource works and return valid connections)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 10 Pro 
 - Output of `java -version`: 11
 - GraalVM version (if different from Java): N/A (jvm mode)
 - Quarkus version or git rev: 1.6.0.Final (also happened with 1.5.1.Final)
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3

**Comment by gsmet** [comment]
Looks very weird and certainly not something expected. @barreiro @Sanne any idea?

**Comment by seseso** [comment]
I've figured it out:
I had a second datasource configured in application.properties (but not used), to a second oracle database. This database was down and it was taking a (very very) long time to return a response to a connect request (not sure why, but also happens with SQLDeveloper).

For this reason, I'll close this issue. 
Thanks!

**Comment by aggarwalchirag** [comment]
I am also getting the same issue. Quarkus version: 1.13.0-Final. This comes when I call up the health check api at an interval of 10 sec. Everything is running fine, and then randomly I start getting this error.

2023-02-15 01:15:13 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) {} Thread Thread[vert.x-worker-thread-16,5,main]=Thread[vert.x-worker-thread-16,5,main] has been blocked for 60533 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked
at java.base@13-ea/jdk.internal.misc.Unsafe.park(Native Method)
at java.base@13-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
at java.base@13-ea/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:447)
at java.base@13-ea/java.util.concurrent.FutureTask.get(FutureTask.java:190)
at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:258)
at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:219)
at io.agroal.pool.DataSource.getConnection(DataSource.java:81)
at io.quarkus.agroal.runtime.health.DataSourceHealthCheck.call(DataSourceHealthCheck.java:47)
at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy.call(DataSourceHealthCheck_ClientProxy.zig:126)
at io.smallrye.health.AsyncHealthCheckFactory$$Lambda$395/0x0000000800fe0840.get(Unknown Source)
at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
at io.smallrye.mutiny.operators.uni.UniAndCombination$UniHandler.subscribe(UniAndCombination.java:203)
at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor$$Lambda$402/0x0000000800fe2440.accept(Unknown Source)
at java.base@13-ea/java.util.ArrayList.forEach(ArrayList.java:1507)
at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.run(UniAndCombination.java:71)
at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.access$000(UniAndCombination.java:53)
at io.smallrye.mutiny.operators.uni.UniAndCombination.subscribe(UniAndCombination.java:50)
at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:54)
at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:256)
at io.smallrye.health.SmallRyeHealthReporter.getReadiness(SmallRyeHealthReporter.java:185)
at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getReadiness(SmallRyeHealthReporter_ClientProxy.zig:396)
at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.getHealth(SmallRyeReadinessHandler.java:11)
at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.doHandle(SmallRyeHealthHandlerBase.java:38)
at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:29)
at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.handle(SmallRyeReadinessHandler.java:7)
at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:17)
at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
at io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$392/0x0000000800f71440.handle(Unknown Source)
at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
at io.vertx.core.impl.ContextImpl$$Lambda$394/0x0000000800fe0040.run(Unknown Source)
at java.base@13-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@13-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base@13-ea/java.lang.Thread.run(Thread.java:830)

**Comment by Sanne** [comment]
> I am also getting the same issue. Quarkus version: 1.13.0-Final.

This versions is very old. Could you please check if it's still happening on the most recent builds please?

**Comment by aggarwalchirag** [comment]
I will try to do that but meanwhile I noticed that some one had reported the same issue on version 2.0 as well. Please refer https://github.com/quarkusio/quarkus/issues/16390
