### ISSUE TITLE
Crashing at start when version updated from 1.5.2 to 1.6.0

### ISSUE THREAD

**Issue by itboy87** [quarkusio/quarkus#10765]
**Describe the bug**
Crashing at start After upgrading from 1.5.2 to 1.6.0. It works fine when running as quarkusDev but when I deploy it by pushing registry with jib and run on Kubernetes. I'm getting this crash on start of container.
```
Exception in thread "main" java.lang.NoSuchFieldError: tlsClientAuth
        at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$vertx$http$runtime$HttpBuildTimeConfig(Config.zig:44085)
        at io.quarkus.runtime.generated.Config.<clinit>(Config.zig:1036)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:55)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)

```

**Expected behavior**
(Describe the expected behavior clearly and concisely.)

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
I would bet on either a partially updated Quarkus (i.e. you still have some dependencies using the old version) or that a good old `clean` is required.

**Comment by geoand** [comment]
I assume you are mixing Quarkus versions - please make you have **only** Quarkus 1.6 and no traces of 1.5

**Comment by itboy87** [comment]
@gsmet `clean` worked for me thanks.
