### ISSUE TITLE
In native mode, creating eclipse paho mqttclient instance gives IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI

### ISSUE THREAD

**Issue by Mahaswami** [quarkusio/quarkus#10775]
**Describe the bug**
Native build runtime exception **Failed to start application: java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://192.168.0.125:1883"** while creating Eclipse Paho MqttClient object.

```error
2020-07-14 14:32:21,659 ERROR [io.qua.application] (main) Failed to start application: java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://192.168.0.125:1883"
        at org.eclipse.paho.client.mqttv3.internal.NetworkModuleService.validateURI(NetworkModuleService.java:72)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:454)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:320)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:315)
        at org.eclipse.paho.client.mqttv3.MqttClient.<init>(MqttClient.java:227)
        at MqttManager.connectToBroker(MqttManager.java:102)
        at MqttManager.init(MqttManager.java:97)
        at org.acme.getting.started.service.MqttManager_ClientProxy.init(MqttManager_ClientProxy.zig:321)
        at AppLifecycleBean.onStart(AppLifecycleBean.java:23)
        at org.acme.getting.started.AppLifecycleBean_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(AppLifecycleBean_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:147)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:113)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:77)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:354)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)

2020-07-14 14:32:21,663 ERROR [io.qua.run.Application] (main) Error running Quarkus application: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:423)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://192.168.0.125:1883"
        at org.eclipse.paho.client.mqttv3.internal.NetworkModuleService.validateURI(NetworkModuleService.java:72)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:454)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:320)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:315)
        at org.eclipse.paho.client.mqttv3.MqttClient.<init>(MqttClient.java:227)
        at MqttManager.connectToBroker(MqttManager.java:102)
        at MqttManager.init(MqttManager.java:97)
        at org.acme.getting.started.service.MqttManager_ClientProxy.init(MqttManager_ClientProxy.zig:321)
        at AppLifecycleBean.onStart(AppLifecycleBean.java:23)
        at org.acme.getting.started.AppLifecycleBean_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(AppLifecycleBean_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:147)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:113)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:77)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:354)
        ... 6 more
```

The problem seems to be related to the class loader in the eclipse paho mqtt client library
```
public class NetworkModuleService {
    private static Logger LOG = LoggerFactory.getLogger("org.eclipse.paho.client.mqttv3.internal.nls.logcat", NetworkModuleService.class.getSimpleName());
    private static final ServiceLoader<NetworkModuleFactory> FACTORY_SERVICE_LOADER = ServiceLoader.load(NetworkModuleFactory.class, NetworkModuleService.class.getClassLoader()); 


while(var4.hasNext()) {
                    NetworkModuleFactory factory = (NetworkModuleFactory)var4.next();
                    if (factory.getSupportedUriSchemes().contains(scheme)) {
                        factory.validateURI(uri);
                        return;
                    }
                }

                throw new IllegalArgumentException("no NetworkModule installed for scheme \"" + scheme + "\" of URI \"" + brokerUri + "\"");
```
Tried registerting the NetworkModuleService class for reflection but to no avail.

**Expected behavior**
Should be able to use eclipse paho mqtt client library in native mode.

**Actual behavior**
Native image runtime  exception while creating MqttClient object.
Runs in **JVM mode** successfully and able to create a mqttClient object and connect to a broker(in our case mosquitto).

**To Reproduce**
Reproducer project can be found at: [quarkus-mqtt-project](https://github.com/MahaswamiSoftware/quarkus-mqtt-starter.git)

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.native.additional-build-args=-H:IncludeResourceBundles=org.eclipse.paho.client.mqttv3.internal.nls.logcat\\,org.eclipse.paho.client.mqttv3.internal.nls.messages,\
  -H:ReflectionConfigurationFiles=reflection-config.json
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux msuser1 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.4" 2019-07-16
 - GraalVM version (if different from Java): graalvm-ce-java11-20.1.0
 - Quarkus version or git rev: 1.5.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.2

**Additional context**
(Add any other context about the problem here.)

**Comment by jaikiran** [comment]
For registering the service provider, in addition to marking the provider classes for reflection, you will have to add the `META-INF/services/<that-service-provider-interface>` as a "resource" in the native image. See the section on `-H:ResourceConfigurationFiles` in this document https://github.com/oracle/graal/blob/master/substratevm/RESOURCES.md

Having said that, it looks like Quarkus has a MQTT extension(?) and perhaps this should be automatically added via that extension?

**Comment by Mahaswami** [comment]
Thank you for pointing to the extension. Used the Camel Paho - Quarkus extension for mqtt and that works successfully in native mode.
