### ISSUE TITLE
RestEasy throws a NPE on a bad uri

### ISSUE THREAD

**Issue by pilhuhn** [quarkusio/quarkus#10801]
**Describe the bug**

I have some JAX-RS code that listens on `GET /api/policies/v1.0/policies/{id}`

    public Response getPolicy(@PathParam("id") UUID policyId)

Now when I pass a bad `id` of  `"123"`, RestEasy throws a NPE (which is logged) and Quarkus returns a 500 error (see below) code with the usual http stack trace, which is annoying to clients that expect Json encoded bodies.

I am trying to add some Vert.x failure handler here, to deal with this, but this could be of any source, where throwing the 500 would be ok.

In fact there is a URISyntaxException logged in the system log, which should be the one my handler sees and not the NPE

```
2020-07-17 10:28:07,400 SEVERE [io.ver.cor.htt.imp.HttpServerRequestImpl] (executor-thread-20) Failed to create abs uri: java.net.URISyntaxException: Illegal character in path at index 28: /api/policies/v1.0/policies/"123"
        at java.base/java.net.URI$Parser.fail(URI.java:2913)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
        at java.base/java.net.URI$Parser.parse(URI.java:3125)
        at java.base/java.net.URI.<init>(URI.java:600)
        at io.vertx.core.http.impl.HttpUtils.absoluteURI(HttpUtils.java:366)
        at io.vertx.core.http.impl.HttpServerRequestImpl.absoluteURI(HttpServerRequestImpl.java:370)
        at io.quarkus.vertx.http.runtime.AbstractRequestWrapper.absoluteURI(AbstractRequestWrapper.java:156)
        at io.vertx.ext.web.impl.HttpServerRequestWrapper.absoluteURI(HttpServerRequestWrapper.java:210)
        at io.quarkus.vertx.http.runtime.AbstractRequestWrapper.absoluteURI(AbstractRequestWrapper.java:156)
        at io.vertx.ext.web.impl.HttpServerRequestWrapper.absoluteURI(HttpServerRequestWrapper.java:210)
        at io.quarkus.resteasy.runtime.standalone.VertxUtil.extractUriInfo(VertxUtil.java:31)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:116)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
        at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

```
2020-07-17 10:28:07,405 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-20) HTTP Request to /api/policies/v1.0/policies/"123" failed, error id: a9b0b1d6-5953-48c8-b17b-a6fd49d43d95-2: java.lang.NullPointerException
        at io.quarkus.resteasy.runtime.standalone.VertxUtil.extractUriInfo(VertxUtil.java:37)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:116)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
        at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

```

**Expected behavior**
(Describe the expected behavior clearly and concisely.)

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
@jaikiran isn't it something you fixed in Vert.x? I recall some discussions about something similar.

**Comment by jaikiran** [comment]
@gsmet, It's still open in vertx https://github.com/vert-x3/vertx-web/issues/1654 (I just noticed that comment from pmlopes in that issue, I will respond to it later today)

**Comment by antonwiens** [comment]
I create a similar issue some time ago: #5584

**Comment by gorshkov-leonid** [comment]
Hello, what is the result of this discussion?
My case is the usage of a valid URL. According to JAX-RS  URL "https://bla-bla/my-api/project%2Ffolder%2F42.txt" is enough valid and should be decoded on the server. But decoding is done prematurely before authorization, is not it? 
The expected result seems to be encoded again or it should not be decoded before authorization.
