### ISSUE TITLE
Remote Development AccessDeniedException

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#10822]
**Describe the bug**
Trying out remote development on 999-SNAPSHOT but I am getting AccessDeniedException(s). Looks like the userid of the process does not have sufficient permissions in the container.

Reproducer:
[Here](https://github.com/jclingan/quarkus-remote-dev). Requires minikube, and I am using the default project. Follow instructions section. Should take 60 seconds to duplicate once minikube is running. As soon as `mvn quarkus:remote-dev` is invoked, an error in the remote (Kubernetes) container pops up:
```
2020-07-18 03:58:01,582 ERROR [io.qua.ver.htt.run.dev.RemoteSyncHandler] (vert.x-eventloop-thread-0) Failed to update file: java.lang.RuntimeException: java.nio.file.AccessDeniedException: /deployments/lib/deployment/appmodel.dat
```

Other permission errors occur as well, such as:
```
Caused by: java.nio.file.AccessDeniedException: /deployments/lib/deployment/build-system.properties
```

**Comment by geoand** [comment]
Thanks for reporting @jclingan.

Is there any chance you can a larger part of the stacktrace here?

**Comment by geoand** [comment]
I tried the attached project and wasn't able to reproduce the problem.

**Comment by jclingan** [comment]
Entire stack trace below. Note, it may not have been clear that this occurs on the server side. To view, before running "curl" on the client side, follow remote logs:

```
PODNAME=`kubectl get pods -l app.kubernetes.io/name=devmode -o jsonpath='{range .items[*]}{@.metadata.name}'`

kubectl logs $PODNAME --follow
```

---


2020-07-20 14:37:32,118 INFO  [io.quarkus] (Quarkus Main Thread) devmode 1.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 2.458s. Listening on: http://0.0.0.0:8080
2020-07-20 14:37:32,139 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-07-20 14:37:32,139 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, kubernetes, resteasy]
2020-07-20 14:38:32,806 ERROR [io.qua.ver.htt.run.dev.RemoteSyncHandler] (vert.x-eventloop-thread-1) Failed to update file: java.lang.RuntimeException: java.nio.file.AccessDeniedException: /deployments/lib/deployment/appmodel.dat
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.updateFile(RuntimeUpdatesProcessor.java:141)
        at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$8.handle(RemoteSyncHandler.java:208)
        at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$8.handle(RemoteSyncHandler.java:204)
        at io.vertx.core.http.HttpServerRequest.lambda$bodyHandler$0(HttpServerRequest.java:216)
        at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:521)
        at io.vertx.core.http.impl.HttpServerRequestImpl.lambda$pendingQueue$1(HttpServerRequestImpl.java:115)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
        at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:224)
        at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:277)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.AccessDeniedException: /deployments/lib/deployment/appmodel.dat
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
        at java.base/java.nio.file.Files.write(Files.java:3424)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.updateFile(RuntimeUpdatesProcessor.java:139)
        ... 17 more

2020-07-20 14:38:32,813 ERROR [io.qua.ver.htt.run.dev.RemoteSyncHandler] (vert.x-eventloop-thread-1) Failed to update file: java.lang.RuntimeException: java.nio.file.AccessDeniedException: /deployments/quarkus-run.jar
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.updateFile(RuntimeUpdatesProcessor.java:141)
        at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$8.handle(RemoteSyncHandler.java:208)
        at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$8.handle(RemoteSyncHandler.java:204)
        at io.vertx.core.http.HttpServerRequest.lambda$bodyHandler$0(HttpServerRequest.java:216)
        at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:521)
        at io.vertx.core.http.impl.HttpServerRequestImpl.lambda$pendingQueue$1(HttpServerRequestImpl.java:115)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
        at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:224)
        at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:277)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.AccessDeniedException: /deployments/quarkus-run.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
        at java.base/java.nio.file.Files.write(Files.java:3424)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.updateFile(RuntimeUpdatesProcessor.java:139)
        ... 17 more

2020-07-20 14:38:32,819 ERROR [io.qua.ver.htt.run.dev.RemoteSyncHandler] (vert.x-eventloop-thread-1) Failed to update file: java.lang.RuntimeException: java.nio.file.AccessDeniedException: /deployments/app/devmode-1.0-SNAPSHOT.jar
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.updateFile(RuntimeUpdatesProcessor.java:141)
        at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$8.handle(RemoteSyncHandler.java:208)
        at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$8.handle(RemoteSyncHandler.java:204)
        at io.vertx.core.http.HttpServerRequest.lambda$bodyHandler$0(HttpServerRequest.java:216)
        at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:521)
        at io.vertx.core.http.impl.HttpServerRequestImpl.lambda$pendingQueue$1(HttpServerRequestImpl.java:115)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
        at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:224)
        at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:277)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.AccessDeniedException: /deployments/app/devmode-1.0-SNAPSHOT.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
        at java.base/java.nio.file.Files.write(Files.java:3424)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.updateFile(RuntimeUpdatesProcessor.java:139)
        ... 17 more

2020-07-20 14:38:32,827 ERROR [io.qua.ver.htt.run.dev.RemoteSyncHandler] (vert.x-eventloop-thread-1) Failed to update file: java.lang.RuntimeException: java.nio.file.AccessDeniedException: /deployments/lib/deployment/build-system.properties
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.updateFile(RuntimeUpdatesProcessor.java:141)
        at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$8.handle(RemoteSyncHandler.java:208)
        at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$8.handle(RemoteSyncHandler.java:204)
        at io.vertx.core.http.HttpServerRequest.lambda$bodyHandler$0(HttpServerRequest.java:216)
        at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:521)
        at io.vertx.core.http.impl.HttpServerRequestImpl.lambda$pendingQueue$1(HttpServerRequestImpl.java:115)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
        at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:224)
        at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:277)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.AccessDeniedException: /deployments/lib/deployment/build-system.properties
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
        at java.base/java.nio.file.Files.write(Files.java:3424)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.updateFile(RuntimeUpdatesProcessor.java:139)
        ... 17 more

**Comment by geoand** [comment]
Thanks @jclingan.

I did try your project a couple times and couldn't reproduce the problem at all.
The dockerfile does seem to use the proper permissions for the `/deployments` directory, so I'm not really sure what's going on.

@stuartwdouglas have you by any chance encountered this?

**Comment by jclingan** [comment]
I  am going to blow away minikube,  update it (new version available), and try it with a clean image.

**Comment by jclingan** [comment]
OK,  same problem after I blew away the image to start fresh. More data so we can compare:

- minikube 1.11.0, default-storageclass  and storage-provisioner addons  installed
- Kubernetes 1.18.3
- docker 19.03.8 (Kube docker version)
- /deployments/lib/deployments directory (and structure) uid and gid set to root.
- Java process user id is 1001 (app return value is now  'whoami' output). No user id 1001 exists in /etc/password.

**Comment by geoand** [comment]
I tried the project again following the instructions to the letter and could not reproduce the problem.

I used 

```
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
```

without any additional addones on Ubuntu.

**Comment by stuartwdouglas** [comment]
I also followed the instructions and it worked for me.

**Comment by stuartwdouglas** [comment]
Actually I am not sure why this worked for me, it should fail. Your dockerfile is different to the current one that should be generated with 1.6.1, it needs to copy with the --chown=1001 . 

I am not sure why this sometimes works and sometimes doesn't, but the chown will fix it.

**Comment by jclingan** [comment]
@stuartwdouglas The Dockerfile was generated off of  999-SNAPSHOT based on a  separate comment about 1.6.1 fixing some remote dev issues. Now that 1.6.1 is available, I'll try it out.

**Comment by jclingan** [comment]
I'm closing this issue.  1.6.1 fixed the issue with the --chown=1001.

Thanks for the help.
