### ISSUE TITLE
403 instead of 401 in case of an expired access token

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#11171]
We use an access token and a refresh token. When the access token expires, we use the refresh token to create a new token - therefore, the frontend needs to know if / when the access token expired. Right now, an expired acess token results in 403 exception - forbidden - same as when the user is just generally forbidden to access the resource. So I think that is a bug, not a feature. 

Related to this:
https://github.com/quarkusio/quarkus/issues/5019

**Comment by MarcusBiel** [comment]
Some extra information:  io.vertx.core.impl.NoStackTraceThrowable: Expired Token is wrapped into an AuthenticationFailedException - but I can't even handle this exception with an ExceptionMapper like so:

@Provider
public class MyExceptionMapper implements ExceptionMapper<AuthenticationFailedException> {
    @Override
    public Response toResponse(AuthenticationFailedException exception) {

**Comment by MarcusBiel** [comment]
@stuartwdouglas  asked for a stacktrace - this is not so easy, as basically from outside, there is no exception - it is eaten up and converted to a 403 (which probably explains why I can't catch the AuthenticattionFailedException).
But I paused the threat and this is what I got:
	at java.base@14.0.2/java.lang.Throwable.<init>(Throwable.java:375)
	at io.vertx.core.impl.NoStackTraceThrowable.<init>(NoStackTraceThrowable.java:20)
	at io.vertx.core.impl.FailedFuture.<init>(FailedFuture.java:39)
	at io.vertx.core.impl.FutureFactoryImpl.failureFuture(FutureFactoryImpl.java:54)
	at io.vertx.core.Future.failedFuture(Future.java:106)
	at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.authenticate(OAuth2AuthProviderImpl.java:305)
	at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.decodeToken(OAuth2AuthProviderImpl.java:338)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$2.accept(OidcIdentityProvider.java:82)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$2.accept(OidcIdentityProvider.java:79)
	at io.smallrye.mutiny.operators.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)

**Comment by sberyozkin** [comment]
@MarcusBiel it has been fixed with 1.7.0.Final. Please reopen if proves otherwise in your case. I'll CC you from the other issue related to dealing with the security exceptions, thanks
