### ISSUE TITLE
IllegalArgumentException during hot replace

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#11226]
**Describe the bug**
In dev mode, during a hot code replace I can see some requests failing and error in the console.

**Actual behavior**
```
2020-08-05 13:27:52,284 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-11) HTTP Request to /api/test/2 failed, error id: 3bfef13a-8f91-4293-8ba6-ead3eb71dc68-6: java.lang.IllegalArgumentException
	at io.quarkus.arc.impl.ArcContainerImpl.unwrap(ArcContainerImpl.java:663)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:668)
	at io.quarkus.arc.impl.InstanceImpl.resolve(InstanceImpl.java:188)
	at io.quarkus.arc.impl.InstanceImpl.<init>(InstanceImpl.java:68)
	at io.quarkus.arc.impl.InstanceImpl.<init>(InstanceImpl.java:50)
	at io.quarkus.arc.impl.InstanceProvider.get(InstanceProvider.java:39)
	at io.quarkus.arc.impl.InstanceProvider.get(InstanceProvider.java:16)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.create(HttpAuthenticator_Bean.zig:328)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.create(HttpAuthenticator_Bean.zig:416)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:79)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.arc$delegate(HttpAuthenticator_ClientProxy.zig:88)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.attemptAuthentication(HttpAuthenticator_ClientProxy.zig:38)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:93)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:45)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:80)
	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:17)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup.handleHotReplacementRequest(VertxHotReplacementSetup.java:39)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$7.handle(VertxHttpRecorder.java:334)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$7.handle(VertxHttpRecorder.java:331)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:112)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:103)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux rvansa 5.2.17-200.fc30.x86_64 #1 SMP Mon Sep 23 13:42:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode, sharing)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: Quarkus 1.4.2.Final

**Comment by famod** [comment]
Have you checked a more recent version of Quarkus? 1.6.1.Final, for instance?

**Comment by famod** [comment]
@mkouba It fails because the `ArcContainer` parameter is not an instance of `ArcContainerImpl`:
https://github.com/quarkusio/quarkus/blob/1.4.2.Final/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ArcContainerImpl.java#L663

**Comment by mkouba** [comment]
> It fails because the ArcContainer parameter is not an instance of ArcContainerImp

That's very likely a class loading issue. There's only one implementation of `ArcContainer` and it's the `ArcContainerImpl`.

**Comment by mkouba** [comment]
CC @stuartwdouglas

**Comment by gsmet** [comment]
As mentioned by @famod , the first step is to try with a more recent version, we fixed quite a few class loader issues since we introduced the new class loader infrastructure.

If reproducible with 1.7.0.CR2, then we need to dig more.

**Comment by pschyma** [comment]
I'm seeing this with 1.8.0.Final. I don't see any console output but a 500 response with body
```
{"details":"Error handling 79b76861-30aa-4bd1-8ef5-64ea4c1159cd-1, java.lang.IllegalArgumentException: ","stack":"java.lang.IllegalArgumentException\n	at io.quarkus.arc.impl.ArcContainerImpl.unwrap(ArcContainerImpl.java:696)\n	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:718)\n	at io.quarkus.arc.impl.InstanceImpl.resolve(InstanceImpl.java:222)\n	at io.quarkus.arc.impl.InstanceImpl.&lt;init&gt;(InstanceImpl.java:77)\n	at io.quarkus.arc.impl.InstanceImpl.&lt;init&gt;(InstanceImpl.java:59)\n	at io.quarkus.arc.impl.InstanceProvider.get(InstanceProvider.java:39)\n	at io.quarkus.arc.impl.InstanceProvider.get(InstanceProvider.java:16)\n	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.create(HttpAuthenticator_Bean.zig:373)\n	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_Bean.create(HttpAuthenticator_Bean.zig:461)\n	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)\n	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)\n	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)\n	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)\n	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)\n	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)\n	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)\n	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.arc$delegate(HttpAuthenticator_ClientProxy.zig:92)\n	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.attemptAuthentication(HttpAuthenticator_ClientProxy.zig:182)\n	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:97)\n	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:49)\n	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)\n	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)\n	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)\n	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:120)\n	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:17)\n	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)\n	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)\n	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)\n	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup.handleHotReplacementRequest(VertxHttpHotReplacementSetup.java:46)\n	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:316)\n	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:312)\n	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)\n	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)\n	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)\n	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)\n	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)\n	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:392)\n	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:389)\n	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:133)\n	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:122)\n	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)\n	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)\n	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)\n	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)\n	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)\n	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)\n	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)\n	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)\n	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)\n	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)\n	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n	at java.base/java.lang.Thread.run(Thread.java:834)"}
```

It's not happening on every hot replace. Sometimes it recovers and only the first request after hot replace fails, but there are also situtations in which it does not recover and I have to restart the dev server manually. This can happen on editing the same (kotlin) source file, so it does not seem to depend on the class.

I'm using Gradle and Java 11.

**Comment by gsmet** [comment]
Any chance one of you could put together a reproducer?

**Comment by stuartwdouglas** [comment]
This actually looks like a weird ClassLoading issue. The code in question is:

    static ArcContainerImpl unwrap(ArcContainer container) {
        if (container instanceof ArcContainerImpl) {
            return (ArcContainerImpl) container;
        } else {
            throw new IllegalArgumentException();
        }
    }

however every ArcContainer should be a ArcContainerImpl unless there is some ClassLoader weirdness going on that should never happen. We will probably need a reproducer to get to the bottom of it.

**Comment by glefloch** [comment]
I just ran some tests on a sample quarkus-kotlin-gradle project but I'm not
able to reproduce this exception.

**Comment by stuartwdouglas** [comment]
ArcContainer and ArcContainerImpl are part of the same module, they will always be loaded by the same CL. If we had a ArcContainerImpl from a different CL then you would not actually be able to call the unwrap() method, as there would be some form of ClassCastException (or LinkageError more likely). 

Therefore this is not a ClassLoading issue, container is null instead. This must be some kind of race where there are still active requests being processed while hot replacement happens, and these are seeing the container in an inconsistent state.

**Comment by stuartwdouglas** [comment]
@rvansa is the request that failed the one that actually triggers the hot reload? Or a subsequent one?

**Comment by mkouba** [comment]
In any case, we should improve the unwrap method and throw a NPE instead...

**Comment by rvansa** [comment]
@stuartwdouglas My apologies, I don't remember and I am even not sure if any requests fails when this is written to the console.The application often executes multiple requests in parallel and it would be hard to tell which one caused the hot reload.

**Comment by pschyma** [comment]
@gsmet it tried to create a reproducer, but failed because it's not deterministic when it fails in our app.

@stuartwdouglas we are doing one request per navigation, but it could be due to CORS and async endpoints? In previous versions I often got a not authorized answer to the preflight on hot reload.

We are handling async REST requests with RESTeasy and MP executor.

**Comment by stuartwdouglas** [comment]
Is it possible a request was still in flight when the hot replace happened? i.e. the endpoint is actually under load, so the moment the file is saved hot replace is triggered, but there could have been a request ms before that just missed the file being saved, that will still be running while the app is updating itself?

**Comment by pschyma** [comment]
No, I don't think so. The workflow is pretty simple: Code, navigate in the SPA (triggers hot replace via a single fetch), wait for view update [, navigate back in the SPA].
