### ISSUE TITLE
Native compile with quarkus 1.6.1 and BlazeBit on MacOs Catalina and  GraalVM 20.1 fails

### ISSUE THREAD

**Issue by hrstoyanov** [quarkusio/quarkus#11242]
**Describe the bug**
Producing native image with:

` gradle build -Dquarkus.package.type=native -x test`

fails with:

Caused by **: java.lang.UnsupportedClassVersionError: com/blazebit/persistence/DefaultPackageOpener has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes** class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.blazebit.persistence.Criteria.getDefault(Criteria.java:59)
	at com.blazebit.persistence.integration.quarkus.runtime.EntityViewRecorder.lambda$setCriteriaBuilderConfiguration$0(EntityViewRecorder.java:50)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources-1120260799.deploy_0(ArcProcessor$generateResources-1120260799.zig:713)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources-1120260799.deploy(ArcProcessor$generateResources-1120260799.zig:36)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:202)
	... 51 more

**Comment by AlexKovynev** [comment]
someone upgrade Blaze from Alpha4 to Alpha5

https://github.com/Blazebit/blaze-persistence/releases/tag/1.5.0-Alpha5

We recently switched from using JDK 9 to JDK 14 for our releases and accidentally compiled MR-JAR contents with the Java 14 classfile version. This release fixes that.

**Comment by hartimcwildfly** [comment]
The error message is very expressive. You try to use a Java14 class with a Java11 compiler. That cannot work. BlazeBit is not part of quarkus. "This extension is developed by a third party and is part of the Quarkus Platform." So I guess here is not the right place to raise the issue.

**Comment by AlexKovynev** [comment]
So as i see it's already fixed(updated) in platform some weeks ago. Need to wait 1.7 now.

**Comment by beikov** [comment]
The Blaze-Persistence version in the latest Quarkus version was updated to 1.5.1. By the way, you can update versions manually by specifying the dependencies explicitly in your pom e.g.

```
<dependency>
<groupId>com.blazebit</groupId>
<artifactId>blaze-persistence-entity-view-processor</artifactId>
<version>1.6.0-Alpha1</version>
</dependency>
<dependency>
<groupId>com.blazebit</groupId>
<artifactId>blaze-persistence-integration-hibernate-5.4</artifactId>
<version>1.6.0-Alpha1</version>
</dependency>
<dependency>
<groupId>com.blazebit</groupId>
<artifactId>blaze-persistence-integration-quarkus-deployment</artifactId>
<version>1.6.0-Alpha1</version>
</dependency>
<dependency>
<groupId>com.blazebit</groupId>
<artifactId>blaze-persistence-integration-quarkus</artifactId>
<version>1.6.0-Alpha1</version>
</dependency>
```
