### ISSUE TITLE
Bazel Standalone Build

### ISSUE THREAD

**Issue by bmstbroadcom** [quarkusio/quarkus#11305]
**Description**
This was already proposed in #3741.

**Implementation ideas**
I tried creating a standalone program using two approaches, but from what I can tell they do the same. The main code is this:

```
        List<String> deployDependencies = readList(parameters, "--dependencies");
        List<String> augumentDependencies = readList(parameters, "--build-dependencies");

        AppArtifact appArtifact = new AppArtifact("com.broadcom", "quarkus", "mock");
        appArtifact.setPath(inputFile);

        QuarkusBootstrap.Builder builder = QuarkusBootstrap.builder()
                .setProjectRoot(inputFile.getParent())
                .setAppArtifact(appArtifact)
//                .setAppModelResolver(new QuarkusMakerModelResolver(deployDependencies, augumentDependencies))
                .setAppModelResolver(new QuarkusMakerModelResolver(Collections.emptyList(), Collections.emptyList()))
                .setBaseName(baseName)
                .setBaseClassLoader(QuarkusMaker.class.getClassLoader())
                .setMode(QuarkusBootstrap.Mode.PROD)
                .setIsolateDeployment(false)
                .setTargetDirectory(outputFile.getParent());

        deployDependencies.stream()
                .map(QuarkusMaker::toApplicationDependency)
                .forEachOrdered(builder::addAdditionalApplicationArchive);

        augumentDependencies.stream()
                .map(Paths::get)
                .forEachOrdered(builder::addAdditionalDeploymentArchive);

        try (CuratedApplication curatedApplication = builder.build().bootstrap()) {
            AugmentAction action = curatedApplication.createAugmentor();
            AugmentResult result = action.createProductionApplication();

            JarResult x = result.getJar();
        } catch (BootstrapException e) {
            throw new IllegalStateException("Unable to bootstrap", e);
        }
```

or, the second approach, switching the `QuarkusMakerModelResolver` to actually have the dependencies, removing the `builder::addAdditionalApplicationArchive` and `builder::addAdditionalDeploymentArchive` calls, and then in the `resolveManagedModel`:

```
    @Override
    public AppModel resolveManagedModel(AppArtifact appArtifact,
                                        List<AppDependency> directDeps,
                                        AppArtifact managingProject) {
        AppModel.Builder builder = new AppModel.Builder()
                .setAppArtifact(appArtifact);

        for (String dependency: this.deployDependencies) {
            AppDependency appDependency = createDependency(dependency);
            builder.addRuntimeDep(appDependency);
        }

        for (String buildDependency: this.augumentDependencies) {
            AppDependency appBuildDependency = createDependency(buildDependency);
            builder.addFullDeploymentDep(appBuildDependency);
        }

        return builder.build();
    }
```

In both cases, I can get up to the JAR being generated, but when executing the JAR I get:

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-08-10 17:13:30,873 INFO  [io.quarkus] (main) Quarkus 1.5.0.Final on JVM started in 0.373s. 
2020-08-10 17:13:30,888 INFO  [io.quarkus] (main) Profile prod activated. 
2020-08-10 17:13:30,889 INFO  [io.quarkus] (main) Installed features: []
2020-08-10 17:13:30,896 ERROR [io.qua.run.Application] (main) Error running Quarkus application: java.lang.IllegalStateException: Unable to locate CDIProvider
        at javax.enterprise.inject.spi.CDI.findAllProviders(CDI.java:121)
        at javax.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:82)
        at javax.enterprise.inject.spi.CDI.current(CDI.java:64)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:93)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at com.broadcom.aa.operator.Main.main(Main.java:9)

2020-08-10 17:13:30,898 INFO  [io.quarkus] (main) Quarkus stopped in 0.001s
```

In here the `deployDependencies` are paths to jars that make the actual application, while the `augumentDependencies` are the `io.quarkus:quarkus-core-deployment` deps.

Any tips on how to approach this would be greatly appreciated.

**Comment by carolosf** [comment]
I created rules_gradle in order to build quarkus apps using gradle. 

It is not ideal because it doesn't compile directly with bazel java rules and so we lose some caching but at least whatever changes are made to quarkus it is still likely to work. 

https://github.com/carolosf/rules_gradle

Example with Quarkus: https://github.com/carolosf/quarkus-bazel-gradle

Hopefully in future we will see direct support.

**Comment by kinhluan** [comment]
Hi everyone 👋

I've been working on solving this exact problem and have published an open-source Bazel ruleset that successfully runs Quarkus build-time augmentation: [rules_quarkus](https://github.com/kinhluan/rules_quarkus)

The key insight that resolved the CDIProvider / ClassLoader issues mentioned in this thread was proper isolation of the augmentation classloader from the system classloader. Specifically:

The implementation uses `QuarkusBootstrap.builder().setExistingModel(appModel)` with a manually constructed `ApplicationModel` from Bazel's dependency graph, bypassing Maven resolution entirely.

**What works today** (Quarkus 3.20.1, Bazel 7.x, Java 21):

```starlark
load("@rules_quarkus//quarkus:defs.bzl", "quarkus_application")

quarkus_application(
    name = "my-app",
    srcs = glob(["src/main/java/**/*.java"]),
    runtime_extensions = ["@maven//:io_quarkus_quarkus_arc", ...],
    deployment_extensions = ["@maven//:io_quarkus_quarkus_arc_deployment", ...],
)
```

I'd appreciate feedback from the Quarkus team on this approach.

Repo: https://github.com/kinhluan/rules_quarkus

**Comment by kinhluan** [comment]
Hey 👋 We've been building production Quarkus apps (3.20.1) with Bazel and wanted to share some hard-won lessons using `QuarkusBootstrap` API directly.

**Our setup:** ~20 Quarkus services built via custom Bazel rules that invoke `QuarkusBootstrap.builder()` programmatically for augmentation.

### Key finding: `setBuildSystemProperties()` is essential

The biggest gotcha we hit: **`System.setProperty()` does NOT propagate to Quarkus augmentation** due to classloader isolation. You must use `setBuildSystemProperties()`:

```java
Properties buildProps = new Properties();
buildProps.setProperty("quarkus.package.main-class", "com.example.MyServiceMain");

QuarkusBootstrap bootstrap = QuarkusBootstrap.builder()
    .setBuildSystemProperties(buildProps)   // ← NOT System.setProperty()!
    .setLocalProjectDiscovery(false)        // ← important for non-Maven builds
    .setOffline(true)                       // ← skip remote resolution
    .setApplicationRoot(appRoot)
    .setExistingModel(appModel)
    .setTargetDirectory(outputDir)
    .setMode(QuarkusBootstrap.Mode.PROD)
    .setIsolateDeployment(true)
    .build();
```

### Why `quarkus.package.main-class` matters

Without it, `MainClassBuildStep` falls back to `@QuarkusMain` annotation scanning. If your `@QuarkusMain` is on an abstract base class (common pattern for shared launcher libraries), Quarkus generates `GeneratedMain` that tries to instantiate it → `InstantiationException` at `ApplicationLifecycleManager.run:136`.

Maven/Gradle plugins set this automatically from `pom.xml`/`build.gradle` properties. In Bazel (or any custom build tool), you need to set it explicitly.

### Other settings we found important

- `setLocalProjectDiscovery(false)` — prevents Quarkus from scanning for Maven/Gradle project structure
- `setOffline(true)` — Bazel already resolved all deps, no need for remote resolution
- `quarkus.application.name` / `quarkus.application.version` — Maven plugin sets these too, worth adding

### Duplicate classes in lib/main/ are harmless

We initially worried that original classes co-existing with transformed versions (`transformed-bytecode.jar` vs `lib/main/*.jar`) would cause conflicts. After research: **`RunnerClassLoader` handles this correctly** via positive filtering from `quarkus-application.dat` entry sets. Same behavior as Maven builds.

Related: filed #52915 for a `@QuarkusMain` on abstract class guard.

Hope this helps anyone else attempting Quarkus + Bazel!

**Comment by maxandersen** [comment]
Awesome info. Thanks. 

Any chance you would be up for a blog post or guide on how to build quarkus apps with Bazel ?

**Comment by kinhluan** [comment]
Thanks @maxandersen! Would love to do that. We're still actively iterating on the rules (fixing edge cases as we onboard more services), but once things stabilize I'd be happy to write up a guide. Will follow up here when ready 👍

**Comment by maxandersen** [comment]
Sounds good. Looking forward to it!

**Comment by kinhluan** [comment]
> Sounds good. Looking forward to it!

Hi @maxandersen 

Just wanted to share that we've finally achieved native Bazel support by leveraging the official QuarkusBootstrap API directly.

Instead of the usual "Maven-wrapper" approach, we've implemented a clean 3-layer architecture (Compile -> Augment -> Runtime) that fits perfectly into Bazel's hermetic sandbox. We've even got Tier 5 extensions like LangChain4j running smoothly!

Detailed the whole journey here: [https://github.com/kinhluan/rules_quarkus/blob/main/docs/blogs/2026-03-11-bazel-support-for-quarkus.md](https://github.com/kinhluan/rules_quarkus/blob/main/docs/blogs/2026-03-11-bazel-support-for-quarkus.md)

Would love for the Quarkus team to take a look!
