### ISSUE TITLE
"Resource bundle not found sun.util.resources.TimeZoneNames" error during native execution

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#11304]
The [debug info](https://github.com/galderz/debug-info) sample app fails with Quarkus master and Mandrel 20.1 branch with:

```
Caused by: java.util.MissingResourceException: Resource bundle not found sun.util.resources.TimeZoneNames. Register the resource bundle using the option -H:IncludeResourceBundles=sun.util.resources.TimeZoneNames.
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:66)
	at sun.util.resources.Bundles.loadBundleOf(Bundles.java:52)
	at sun.util.resources.Bundles.of(Bundles.java:106)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
	at java.security.AccessController.doPrivileged(AccessController.java:83)
	at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
	at sun.util.resources.LocaleData.getTimeZoneNames(LocaleData.java:114)
	at sun.util.locale.provider.LocaleResources.getTimeZoneNames(LocaleResources.java:270)
	at sun.util.cldr.CLDRTimeZoneNameProviderImpl.deriveFallbackName(CLDRTimeZoneNameProviderImpl.java:170)
	at sun.util.cldr.CLDRTimeZoneNameProviderImpl.getDisplayNameArray(CLDRTimeZoneNameProviderImpl.java:93)
	at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayName(TimeZoneNameProviderImpl.java:99)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getName(TimeZoneNameUtility.java:271)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:229)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:215)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleSubstitutions.java:150)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleSubstitutions.java:242)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayNamesImpl(TimeZoneNameUtility.java:197)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayName(TimeZoneNameUtility.java:150)
	at java.util.TimeZone.getDisplayName(TimeZone.java:401)
```

[Longer stacktrace](https://gist.github.com/galderz/00b9567c85049f8f737dd0c105d4b078).

It's unclear yet what's the cause of this, whether removal of include all timezones (see https://github.com/quarkusio/quarkus/commit/7666f6c022 and related), or whether some other issue that Mandrel 20.1 introduces. I've not yet verified with GraalVM distribution.

**Comment by jaikiran** [comment]
Slightly related - (given that stacktrace) I still think that this should be added as a resource bundle by Graal VM itself, for reasons noted here in a similar issue https://github.com/oracle/graal/issues/2005

**Comment by galderz** [comment]
@jaikiran Thx for the pointer. I'm debugging this as we speak and not yet sure the cause. but I'll keep that in mind.

I've narrowed down [this simple native image example](https://github.com/galderz/mendrugo/tree/master/timezones) to fail with a Mandrel snapshot from 6th August (see [here](https://gist.github.com/galderz/c82c6c480e0185488d44bc6d53dfdcc0)). Works fine with GraalVM 20.1.0 and Mandrel Mandrel 20.1.0.1.Alpha2 (yet to try final published yesterday).

**Comment by galderz** [comment]
It's clear though this is not an issue with Quarkus, so I'll be closing this shortly and opening a bug elsewhere.

**Comment by galderz** [comment]
Seems to work fine with Mandrel 20.1.0.1.Final though. So, either some fix in between 6th August and Final fixed it, or I'm building snapshots wrong, or this is a random occurrence. Closing for now.

**Comment by galderz** [comment]
This is now being tracked in https://github.com/graalvm/mandrel/issues/106.
