### ISSUE TITLE
Class not in jandex index warning seen new after update to Quarkus 1.7.0

### ISSUE THREAD

**Issue by bobbyphilip** [quarkusio/quarkus#11440]
**Describe the bug**
After updating to quarkus 1.7.0, I have started seeing the following message in the logs.
WARN [io.qu.de.st.ReflectiveHierarchyStep] null Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
- javax.persistence.EntityManager (source:mypackage.OneOfMyClasses)

 - Output of `java -version`: openjdk version "11.0.8" 2020-07-14
 - Quarkus version or git rev:  1.7.0

**Additional context**
I have not been able to create a standalone reproducer.  built quarkus from the master branch today, and reverted commits https://github.com/quarkusio/quarkus/commit/fb78482cdd1f27bd87b394500c01add0818e213d & https://github.com/quarkusio/quarkus/commit/c4127048865dad5b72c2c281bbdda60a50fcfb8c (The entity manager changes hinted in zulipchat). With these changes, the warning log message no longer appears

**Comment by bobbyphilip** [comment]
This patch didnt work for my code.
I did some debugging in core/deployment/src/main/java/io/quarkus/deployment/steps/ReflectiveHierarchyStep.java
When the execution reaches removeIgnored(), the Map of unindexedClasses has 2 elements. "java.math.BigDecimal" and "javax.persistence.EntityManager".  The BigDecimal gets removed from the Map at the end of this function.
Would adding the EntityManager to  the set WHITELISTED_FROM_IGNORED_PACKAGES be an acceptable solution?

**Comment by gsmet** [comment]
@bobbyphilip can you explain what is `OneOfMyClasses`? Is it a JAX-RS resource, something else?

**Comment by bobbyphilip** [comment]
import java.sql.Timestamp;
import com.example.Business;
import io.quarkus.runtime.annotations.RegisterForReflection;

@RegisterForReflection
public class BusinessView {

    private Long id;
    private Boolean active = Boolean.TRUE;
    private String city;  
    private Timestamp updatedTime;
//Some more fields 
    public BusinessView() {

    }

    public BusinessView(Business business) {
      //setting fields of the BusinessView from Business
    }

//settters and getters
}


 The Business class is the entity

@Entity
@RegisterForReflection
@Table(name = "business")
public class Business extends PanacheEntityBase implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private Boolean active;
//More fields
//no-arg constructor
//getters and setters

}


I have a BusinessResource, withGET/POST APIs, creating and consuming BusinessViews.
I dont directly use the EntityManager in any of these classes

**Comment by gsmet** [comment]
What I don't understand is what created the `ReflectiveHierarchyBuildItem` for `BusinessView`. Any chance you could add a breakpoint in the various constructors of `ReflectiveHierarchyBuildItem` and tell me which BuildStep/Processor is creating it?

**Comment by bobbyphilip** [comment]
As a quick response, I hope the stacktrace below helps.  I print this stacktrace when ReflectiveHierarchyBuildItem constructor is called and the type in it, is com.example.BusinessView.

```
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1388)
	at io.quarkus.deployment.builditem.nativeimage.ReflectiveHierarchyBuildItem.<init>(ReflectiveHierarchyBuildItem.java:119)
	at io.quarkus.deployment.builditem.nativeimage.ReflectiveHierarchyBuildItem.<init>(ReflectiveHierarchyBuildItem.java:108)
	at io.quarkus.deployment.builditem.nativeimage.ReflectiveHierarchyBuildItem$Builder.build(ReflectiveHierarchyBuildItem.java:191)
	at io.quarkus.resteasy.server.common.deployment.ResteasyServerCommonProcessor.scanMethods(ResteasyServerCommonProcessor.java:791)
	at io.quarkus.resteasy.server.common.deployment.ResteasyServerCommonProcessor.registerReflectionForSerialization(ResteasyServerCommonProcessor.java:748)
	at io.quarkus.resteasy.server.common.deployment.ResteasyServerCommonProcessor.build(ResteasyServerCommonProcessor.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  

If you need something else, I can try this tomorrow. Is there any guide to setting up the quarkus code to debug in an IDE?
```

**Comment by gsmet** [comment]
I have the info I need. Now I need to find a way to reproduce it and understand what's going on.

**Comment by bobbyphilip** [comment]
I am sharing a [git repo ](https://github.com/bobbyphilip/quarkus-test-1), which is equivalent to the code I have.
This does **NOT** reproduce the issue, so it is not particularly useful.
The class which shows up in the error is rather simplistic and I cant see anything particularly unique in it. It is very similar to around 5/6 other classes in my project.

Is there some sort of parallelism involved, which can trigger a race-condition. I see n

I use hibernate-search  resteasy, swagger-ui, resteasy-jsonb,quarkus-hibernate-orm-panache, quarkus-smallrye-jwt in case that is relevant.

**Comment by gsmet** [comment]
I wasn't able to reproduce it either.

I added some additional information to the warning hoping it could help to narrow down the issue. Could you try with the latest version of my PR? https://github.com/quarkusio/quarkus/pull/11462

**Comment by bobbyphilip** [comment]
After building your changes, I didnt see any difference in the log warning.   I think this means that the source of the ReflectiveHierarchyBuildItem is null, and we replace it with the type in the build method of ReflectiveHeirarchyStep(line 65)
I then added some debugs in
  ```
private ReflectiveHierarchyBuildItem(Type type, IndexView index, Predicate<DotName> ignoreTypePredicate,
            Predicate<FieldInfo> ignoreFieldPredicate, Predicate<MethodInfo> ignoreMethodPredicate, String source) {
```

The source is null in the following sequence

```
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1388)
	at io.quarkus.deployment.builditem.nativeimage.ReflectiveHierarchyBuildItem.<init>(ReflectiveHierarchyBuildItem.java:120)
	at io.quarkus.deployment.builditem.nativeimage.ReflectiveHierarchyBuildItem.<init>(ReflectiveHierarchyBuildItem.java:105)
	at io.quarkus.deployment.builditem.nativeimage.ReflectiveHierarchyBuildItem.<init>(ReflectiveHierarchyBuildItem.java:97)
	at io.quarkus.deployment.builditem.nativeimage.ReflectiveHierarchyBuildItem.<init>(ReflectiveHierarchyBuildItem.java:65)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.registerReflectionForApiResponseSchemaSerialization(SmallRyeOpenApiProcessor.java:225)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.registerOpenApiSchemaClassesForReflection(SmallRyeOpenApiProcessor.java:201)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```  

SmallRyeOpenApiProcessor has some function calls to the deprecated constructors.

**Comment by gsmet** [comment]
@bobbyphilip can you give my branch another try? Be careful, I rebased it and rewrote a few commits so make sure you're using the right commit `66ea18f`.

Thanks!

**Comment by gsmet** [comment]
I pushed a small additional change so it should be aed696e .

**Comment by bobbyphilip** [comment]
Latest code looks good! Problem solved
