### ISSUE TITLE
Got different property evaluated on docker run and docker-compose up but with the same image

### ISSUE THREAD

**Issue by manodupont** [quarkusio/quarkus#11469]
**Describe the bug**
When i launch a docker-compose with my image freshly created and pushed, `quarkus.oidc.auth-server-url` is not recognized correctly from my `application.yaml` file.

When i start locally with docker run, i can see the right variable being set but when i run from docker-compose, its not complete.
Here is the exact logs that showed something is wrong:

**Locally**
1. docker run myimage:mytag my-container-name
2. ....logs ....
```
2020-08-19 13:17:31,441 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-2) -Dio.netty.recycler.ratio: 8
2020-08-19 13:17:32,221 FINE  [io.ver.ext.aut.oau.imp.OAuth2ResponseImpl] (vert.x-eventloop-thread-2) New response: statusCode: 200
2020-08-19 13:17:32,297 FINE  [io.ver.ext.aut.oau.imp.OAuth2API] (vert.x-eventloop-thread-2) Fetching URL: http://35.209.56.198:8082/auth/realms/cjl/protocol/openid-connect/certs
2020-08-19 13:17:32,797 FINE  [io.ver.ext.aut.oau.imp.OAuth2ResponseImpl] (vert.x-eventloop-thread-2) New response: statusCode: 200

```

But when i start from **docker-compose up**

```
2020-08-19 13:18:28,617 ERROR [io.qua.run.Application] (main) Error running Quarkus application: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:571)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: io.quarkus.oidc.OIDCException: OIDC server is not available at the 'quarkus.oidc.auth-server-url' URL. Please make sure it is correct. Note it has to end with a realm value if you work with Keycloak, for example: 'https://localhost:8180/auth/realms/quarkus'
	at io.quarkus.oidc.runtime.OidcRecorder.toOidcException(OidcRecorder.java:238)
	at io.quarkus.oidc.runtime.OidcRecorder$2.handle(OidcRecorder.java:165)
	at io.quarkus.oidc.runtime.OidcRecorder$2.handle(OidcRecorder.java:161)
	at io.vertx.ext.auth.oauth2.providers.KeycloakAuth.lambda$discover$0(KeycloakAuth.java:125)
	at io.vertx.ext.auth.oauth2.providers.OpenIDConnectAuth.lambda$discover$2(OpenIDConnectAuth.java:104)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:141)
	at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:369)
	at io.vertx.core.http.impl.HttpClientRequestImpl.lambda$null$6(HttpClientRequestImpl.java:471)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:224)
	at io.vertx.core.http.impl.HttpClientRequestImpl.lambda$connect$7(HttpClientRequestImpl.java:470)
	at io.vertx.core.http.impl.HttpClientImpl.lambda$getConnectionForRequest$4(HttpClientImpl.java:1043)
	at io.vertx.core.http.impl.ConnectionManager.lambda$getConnection$7(ConnectionManager.java:154)
	at io.vertx.core.http.impl.pool.Pool.connectFailed(Pool.java:383)
	at io.vertx.core.http.impl.pool.Pool.access$600(Pool.java:88)
	at io.vertx.core.http.impl.pool.Pool$Holder.lambda$connect$0(Pool.java:130)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at io.vertx.core.http.impl.HttpChannelConnector.connectFailed(HttpChannelConnector.java:252)
	at io.vertx.core.http.impl.HttpChannelConnector.lambda$doConnect$0(HttpChannelConnector.java:161)
	at io.vertx.core.net.impl.ChannelProvider.lambda$connect$1(ChannelProvider.java:78)
	at io.vertx.core.net.impl.ChannelProvider.lambda$handleConnect$2(ChannelProvider.java:145)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /35.209.56.198:8082
```

**Expected behavior**
It should be the same as in docker run, as I am launching the exact same image.

**Actual behavior**
Its not getting the same values from the props !!!

**To Reproduce**
1. docker run  myimage:mytag my-container-name
2. Check the logs
3. Run docker-compose up
4. Check the logs

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus:
  datasource:
    db-kind: mariadb
    jdbc:
      max-size: 3
      min-size: 1
      url: <myDbUrl>
    password: ''
    username: root
  http:
    port: 8888
  log:
    category:
      "io.quarkus.smallrye.jwt":
        level: TRACE
      "io.smallrye.jwt":
        level: TRACE
      "io.undertow.request.security":
        level: TRACE
      "org.hibernate":
        level: DEBUG
    level: DEBUG
  oidc:
    auth-server-url: "http://localhost:8080/auth/realms/<myrealm>"
"%latest":
  quarkus:
    oidc:
      auth-server-url: "http://35.209.56.198:8082/auth/realms/<myrealm>"
```

**Environment (please complete the following information):**
Java
```
  ~/   master !2 ❯ java -version                                                                                                                          system  11.0  15:25:56
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit GraalVM CE 19.3.1 (build 25.242-b06-jvmci-19.3-b07, mixed mode)
  ~/   master !2 ❯               
```

Maven
```
  ~/   master !2 ❯ mvn -v                                                                                                                                 system  11.0  15:26:38
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3/libexec
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.1/Contents/Home/jre
Default locale: en_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
  ~/   master !2 ❯                                         
```
docker-compose
```
 api:
    image: myimage:mytag
    ports:
      - "8888:8888"
    depends_on:
      - mariadb
      - keycloak
```
**Additional context**
Whats weird is that i do have properties like datasource one with some URLs in it and its working fine no matter how i start quarkus.

Whats the difference between docker run and docker-compose up :)

**Comment by manodupont** [comment]
Im just numb!

Thanks!

Closing.
