### ISSUE TITLE
Quarkus 1.7.0.Final - SRMSG18217: Unable to read a record from Kafka topics '[someTopic]': java.lang.IllegalStateException: This processor allows only a single Subscriber

### ISSUE THREAD

**Issue by marc-christian-schulze** [quarkusio/quarkus#11476]
**Describe the bug**
I've a QuarkusTest which subscribes to a channel before each test using
```
@Inject
@Channel("in-channel")
lateinit var eventPublisher: Publisher<MyEvent>
var events = TestSubscriber<MyEvent>()

@BeforeEach
fun beforeEach() {
    events = TestSubscriber<MyEvent>()
    eventPublisher.subscribe(events)
}
```
and unsubscribes afterwards using
```
@AfterEach
fun afterEach() {
    events.dispose()
}
```
and uses a real Kafka messaging backend for testing
```
mp.messaging.outgoing.out-channel.connector=smallrye-kafka
mp.messaging.outgoing.out-channel.topic=someTopic
mp.messaging.outgoing.out-channel.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.incoming.in-channel.connector=smallrye-kafka
mp.messaging.incoming.in-channel.topic=someTopic
mp.messaging.incoming.in-channel.value.deserializer=MyEventDeserializer
```
the events are emitted to the out-channel
```
@Inject
@Channel("out-channel")
lateinit var emitter: Emitter<MyEvent>
...
emitter.send(...)
```
In Quarkus 1.6.0.CR1 the test was working properly. The QuarkusApp emitted the event into the Kafka topic and received it back from there. However, in Quarkus 1.7.0.Final the very same test fails with:
```
SRMSG18217: Unable to read a record from Kafka topics '[someTopic]': java.lang.IllegalStateException: This processor allows only a single Subscriber
	at io.smallrye.mutiny.vertx.MultiReadStream.subscribe(MultiReadStream.java:62)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:23)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:68)
	at io.smallrye.mutiny.operators.multi.MultiSignalConsumerOp.subscribe(MultiSignalConsumerOp.java:50)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:33)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:48)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.lambda$subscribe$0(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.subscribe(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:23)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:68)
	at io.smallrye.mutiny.operators.multi.MultiOnSubscribeInvokeUniOp.subscribe(MultiOnSubscribeInvokeUniOp.java:36)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:33)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:48)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.lambda$subscribe$0(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.subscribe(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:23)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:68)
	at io.smallrye.mutiny.operators.multi.MultiMapOp.subscribe(MultiMapOp.java:24)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:33)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:48)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.lambda$subscribe$0(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.subscribe(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:23)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:68)
	at io.smallrye.mutiny.operators.multi.MultiSignalConsumerOp.subscribe(MultiSignalConsumerOp.java:50)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:33)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:48)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.lambda$subscribe$0(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.subscribe(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:159)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:48)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.lambda$subscribe$0(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.subscribe(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:159)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:48)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.lambda$subscribe$0(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.subscribe(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:23)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:68)
	at io.smallrye.mutiny.operators.multi.MultiMapOp.subscribe(MultiMapOp.java:24)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:33)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:48)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.lambda$subscribe$0(ContextPropagationMultiInterceptor.java:58)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.subscribe(ContextPropagationMultiInterceptor.java:58)
	at MyTestCase.beforeEach(MyTestCase.kt:56)
```

**Expected behavior**
Subscribing to a Publisher backed by a real Kafka instance works.

**Actual behavior**
Subscribing to a Publisher backed by a real Kafka instance throws the above-mentioned exception.

Obviously, the `MultiReadStream` violates the `Publisher` interface it's implementing which is a ticket for the smallrye project. However, since the workflow was working previously in 1.6.0.CR1 and now (in 1.7.0.Final) fails I guess it should be tracked here as well.

**Comment by gsmet** [comment]
@marc-christian-schulze any chance you could prepare a small Maven project reproducing the issue? If it can be in Java, it's even better.

**Comment by evanshortiss** [comment]
Seeing a similar issue on my end Building using source-to-image via *quarkus-openshift* plugin with *registry.access.redhat.com/ubi8/openjdk-11*. The error is:

```
2020-10-01 17:56:58,009 ERROR [io.sma.rea.mes.kafka] (executor-thread-1) SRMSG18217: Unable to read a record from Kafka topics '[hydrated-meter-events]': java.lang.IllegalStateException: This processor allows only a single Subscriber
	at io.smallrye.mutiny.vertx.MultiReadStream.subscribe(MultiReadStream.java:62)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:23)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:68)
	at io.smallrye.mutiny.operators.multi.MultiSignalConsumerOp.subscribe(MultiSignalConsumerOp.java:50)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:33)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:48)
	at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$2.lambda$subscribe$0(ContextPropagationMultiInterceptor.java:58)

...etc

2020-10-01 17:56:58,267 INFO  [org.apa.kaf.cli.con.KafkaConsumer] (vert.x-kafka-consumer-thread-0) [Consumer clientId=consumer-6669a9c2-d844-4103-b3d3-223eae0e8fd2-2, groupId=6669a9c2-d844-4103-b3d3-223eae0e8fd2] Subscribed to topic(s): hydrated-meter-events
```

Here's my configuration and Resource:

```properties
mp.messaging.incoming.meter-events.connector=smallrye-kafka
mp.messaging.incoming.meter-events.topic=hydrated-meter-events
mp.messaging.incoming.meter-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
```

```java
@Path("/meters")
public class MeterEventResource {

    @Inject
    @Broadcast
    @Channel("meter-events")
    Publisher<MeterEvent> meterEvents;

    @GET
    @Path("/stream")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    @SseElementType("text/json")
    public Publisher<MeterEvent> stream() {
        return meterEvents;
    }
}
```

**Comment by cescoffier** [comment]
Add:


mp.messaging.incoming.meter-events.broadcast=true

**Comment by evanshortiss** [comment]
@cescoffier thank you! That did the trick. Is the `@Broadcast` annotation intended for a different purpose.

**Comment by cescoffier** [comment]
@evanshortiss it's doing the same thing, but one is used on emitters (annotation) and one on connector (configuration attribute).
