### ISSUE TITLE
Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]

### ISSUE THREAD

**Issue by ArokLair** [quarkusio/quarkus#11483]
Hi team.

We have a bug to compile maven project:

Failed to execute goal io.quarkus:quarkus-maven-plugin:1.7.0.Final:build (default) on project security: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]
	- java member: com.lafabril.ec.repository.AuthorityRepository#em
	- declared on CLASS bean [types=[com.lafabril.ec.repository.AuthorityRepository, com.lafabril.ec.repository.AbstractRepository<com.lafabril.ec.domain.Authority, java.lang.String>, java.lang.Object], qualifiers=[@Default, @Any], target=com.lafabril.ec.repository.AuthorityRepository]
[2] Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]
	- java member: com.lafabril.ec.repository.UserRepository#em
	- declared on CLASS bean [types=[com.lafabril.ec.repository.UserRepository, com.lafabril.ec.repository.AbstractRepository<com.lafabril.ec.domain.User, java.lang.Long>, java.lang.Object], qualifiers=[@Default, @Any], target=com.lafabril.ec.repository.UserRepository]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:998)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:234)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:122)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:391)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]
	- java member: com.lafabril.ec.repository.AuthorityRepository#em
	- declared on CLASS bean [types=[com.lafabril.ec.repository.AuthorityRepository, com.lafabril.ec.repository.AbstractRepository<com.lafabril.ec.domain.Authority, java.lang.String>, java.lang.Object], qualifiers=[@Default, @Any], target=com.lafabril.ec.repository.AuthorityRepository]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:494)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:226)
		... 14 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]
	- java member: com.lafabril.ec.repository.UserRepository#em
	- declared on CLASS bean [types=[com.lafabril.ec.repository.UserRepository, com.lafabril.ec.repository.AbstractRepository<com.lafabril.ec.domain.User, java.lang.Long>, java.lang.Object], qualifiers=[@Default, @Any], target=com.lafabril.ec.repository.UserRepository]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:494)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:226)
		... 14 more
-> [Help 1]

**Comment by stuartwdouglas** [comment]
You are likely either missing the JPA extension or don't have any entities in your project.

**Comment by ArokLair** [comment]
Yes, we solved add JPA conection in the application.propierties.

Thanks for response please close the issue.
