### ISSUE TITLE
ClassCastException and swallowed original cause

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#11529]
**Describe the bug**
My code is probably throwing an exception, or maybe there's a problem inside Quarkus itself. However, all I can see in logs is
```
2020-08-21 14:43:42,513 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-worker-thread-0) Unhandled exception: java.lang.ClassCastException: class io.vertx.core.impl.FutureImpl cannot be cast to class java.lang.Throwable (io.vertx.core.impl.FutureImpl is in unnamed module of loader 'app'; java.lang.Throwable is in module java.base of loader 'bootstrap')
	at io.hyperfoil.tools.horreum.api.NotificationService_VertxInvoker_onNewChange_a9f47974e2839427df5a82b571e8a38214a4cbad$$function$$1.handle(NotificationService_VertxInvoker_onNewChange_a9f47974e2839427df5a82b571e8a38214a4cbad$$function$$1.zig:63)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
and the actual exception that is probably the exception result of the `FutureImpl` is swallowed while the problem above fires.

**Expected behavior**
The original exception is logged.

**To Reproduce**
It's rather hard to isolate what triggered it. Just fix the bytecode in .zig and we'll see.

**Environment (please complete the following information):**
 - Output of `java -version`: openjdk version "11.0.5" 2019-10-15 (FROM fabric8/java-alpine-openjdk11-jre)
 - Quarkus version or git rev: 1.7.0 but I was seeing this since ever
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  maven-3.6.2

**Comment by jaikiran** [comment]
Hello @rvansa, is that the complete stacktrace? If not, can you post the rest of it?

**Comment by rvansa** [comment]
@jaikiran This is really all. Do you know where could I find the piece of code that gets this `.zig` generated?

**Comment by jaikiran** [comment]
> Do you know where could I find the piece of code that gets this .zig generated?

Going by this, in your stacktrace:

```
...VertxInvoker_onNewChange...
```
I think it's in this class https://github.com/quarkusio/quarkus/blob/master/extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java

**Comment by rvansa** [comment]
This is the failing bytecode:
```
      71: pop
      72: aload_1
      73: checkcast     #52                 // class io/vertx/core/Future
      76: aload_1
      77: checkcast     #57                 // class java/lang/Throwable
      80: invokeinterface #61,  2           // InterfaceMethod io/vertx/core/Future.fail:(Ljava/lang/Throwable;)V
      85: goto          88
      88: return
```
Obviously the local var 1 cannot be both a Future and Throwable, so I think that the offending line is `catchBlock.getMethodParam(0)` in https://github.com/quarkusio/quarkus/blob/master/extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java#L134 - it should really call `catchBlock.getCaughtException()`.

I'll try to compile quarkus and run it locally...

**Comment by rvansa** [comment]
Okay, I confirm that this revealed the actual exception. I'll do a PR...

**Comment by rvansa** [comment]
I cannot link PR directly: https://github.com/quarkusio/quarkus/pull/11596

**Comment by jaikiran** [comment]
Fixed in https://github.com/quarkusio/quarkus/pull/11596
