### ISSUE TITLE
Error: No instances of sun.nio.ch.FileChannelImpl are allowed in the image heap as this class should be initialized at image runtime

### ISSUE THREAD

**Issue by acx70** [quarkusio/quarkus#11702]
**Describe the bug**
`mvnw clean package -Pnative`    failed with the following error:

```
...
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:33 min
[INFO] Finished at: 2020-08-28T14:10:54+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.7.1.Final:build (default) on project as400-proxy-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:389)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.nio.file.NoSuchFileException: C:\Users\tony\Source\repos-Java\as400-proxy-quarkus\target\as400-proxy-quarkus-1.0.0-SNAPSHOT-native-image-source-jar\as400-proxy-quarkus-1.0.0-SNAPSHOT-runner.exe
[ERROR]         at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[ERROR]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[ERROR]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[ERROR]         at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
[ERROR]         at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
[ERROR]         at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:198)
[ERROR]         at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
[ERROR]         at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
[ERROR]         at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
[ERROR]         at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
[ERROR]         at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
[ERROR]         at io.quarkus.bootstrap.util.IoUtils.copy(IoUtils.java:98)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:375)
[ERROR]         ... 12 more
...
```

**Expected behavior**
native image is generated and package succeeds

**Actual behavior**
Got compile error message.

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties

# Configuration file
# key = value
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/as400proxy-quarkus/swagger-ui

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**

 - Output of `uname -a` or `ver`: 

   Microsoft Windows [Version 10.0.18363.1016]

 - Output of `java -version`: 

   java version "11.0.8" 2020-07-14 LTS
   Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
   Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

 - GraalVM version (if different from Java): 

   graalvm-ce-java-11-20.2.0

 - Quarkus version or git rev: 
    
   1.7.0.Final

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

   1.7.0.Final

**Additional context**

Please see below the log files and the POM file.

[native_building_log.txt](https://github.com/quarkusio/quarkus/files/5142230/native_building_log.txt)

[native_building_log_COMPLETE.txt](https://github.com/quarkusio/quarkus/files/5142253/native_building_log_COMPLETE.txt)

[pom.txt](https://github.com/quarkusio/quarkus/files/5141126/pom.txt)

**Comment by chandanpuggal** [comment]
Any update on this?

**Comment by gsmet** [comment]
I would try upgrading to 2.6.0.Final and add the `quarkus-awt` extension. It covers several use cases of AWT in native.

**Comment by gsmet** [comment]
No activity for a while, closing. Please reopen with a reproducer if still an issue.
