### ISSUE TITLE
Elytron JDBC forbidden native test hangs

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#11768]
Elytron JDBC `forbidden` native test hangs with Mandrel 20.2 and assertions enabled:

```
[ERROR] Tests run: 5, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 1,803.652 s <<< FAILURE! - in io.quarkus.elytron.security.jdbc.it.ElytronSecurityJdbcIT
[ERROR] io.quarkus.elytron.security.jdbc.it.ElytronSecurityJdbcIT.forbidden  Time elapsed: 1,800.136 s  <<< ERROR!
org.apache.http.NoHttpResponseException: localhost:8081 failed to respond
```

See [longer output](https://gist.github.com/galderz/d5b6ff8aeb7ff7c61ff1398fe5bb37ce).

When you run the executable and you enable TRACE, there's no sign of any error, nor is there any thread busy (see [here](https://gist.github.com/galderz/c311f5799ca0f7b4a19e75d82f2bb399)). So, this points to some exception that was uncaught and swallowed.

**Comment by galderz** [comment]
Assigning to moi, as I dig into what's the swallowed exception.

**Comment by galderz** [comment]
After a bit of experimentation (see [here](https://gist.github.com/galderz/2dd134128dba04e113913fe5eb176c4e) and [here](https://gist.github.com/galderz/2dd134128dba04e113913fe5eb176c4e)), it turns out the root cause of the test failing is https://github.com/graalvm/mandrel/issues/106:

```
2020-09-02 07:51:47,754 ERROR [io.qua.ver.htt.run.sec.PersistentLoginManager] (executor-thread-1) Tracking exception, step 1: java.util.MissingResourceException: Resource bundle not found sun.util.resources.TimeZoneNames. Register the resource bundle using the option -H:IncludeResourceBundles=sun.util.resources.TimeZoneNames.
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:66)
	at sun.util.resources.Bundles.loadBundleOf(Bundles.java:52)
	at sun.util.resources.Bundles.of(Bundles.java:106)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
	at java.security.AccessController.doPrivileged(AccessController.java:83)
	at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
	at sun.util.resources.LocaleData.getTimeZoneNames(LocaleData.java:114)
	at sun.util.locale.provider.LocaleResources.getTimeZoneNames(LocaleResources.java:270)
	at sun.util.cldr.CLDRTimeZoneNameProviderImpl.deriveFallbackName(CLDRTimeZoneNameProviderImpl.java:170)
	at sun.util.cldr.CLDRTimeZoneNameProviderImpl.getDisplayNameArray(CLDRTimeZoneNameProviderImpl.java:93)
	at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayName(TimeZoneNameProviderImpl.java:99)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getName(TimeZoneNameUtility.java:271)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:229)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:215)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleSubstitutions.java:150)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleSubstitutions.java:242)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayNamesImpl(TimeZoneNameUtility.java:197)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayName(TimeZoneNameUtility.java:150)
	at java.util.TimeZone.getDisplayName(TimeZone.java:401)
	at java.util.Date.toString(Date.java:1046)
	at io.quarkus.vertx.http.runtime.security.PersistentLoginManager.save(PersistentLoginManager.java:116)
```

The reason the test hangs is because if an exception occurs in the `.subscribe().with()` callback, the `uniEmitter` is not failed and hence it hangs. I'll open a separate issue to handle this.

**Comment by sberyozkin** [comment]
Hi @galderz do you think this issue can now be resolved now that we've merged #11807 ? thanks

**Comment by sberyozkin** [comment]
Sorry, may be I've misread your last comment above...

**Comment by galderz** [comment]
Yup, can be closed.
