### ISSUE TITLE
Allow Command Mode to Run Without HTTP or Socket Input

### ISSUE THREAD

**Issue by cpmoore** [quarkusio/quarkus#11786]
**Description**
For command mode there are certain cli utilities that do not need any http or socket input.  However a developer could still desire to use quarkus for the ease of use of some of the plugins and configuration options. 
Therefore, I believe quarkus should be allowed to be used even with `quarkus.http.insecure-requests=disabled` 
Currently with this value set quarkus throws an IllegalStateException saying that ssl must be enabled in order to disable http.

**Comment by gsmet** [comment]
Have you tried removing the quarkus-resteasy dependency?

**Comment by cpmoore** [comment]
Without any dependencies in my pom.xml, this exception is thrown
```
2020-09-01 14:28:22,506 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: java.lang.IllegalStateException: No root definition found for class io.quarkus.runtime.BannerRuntimeConfig
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:253)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:134)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:54)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:75)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:349)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:51)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:132)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:85)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:144)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: java.lang.IllegalStateException: No root definition found for class io.quarkus.runtime.BannerRuntimeConfig
        at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadResult.requireRootDefinitionForClass(BuildTimeConfigurationReader.java:798)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:219)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:98)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:251)
        ... 9 more
```

This is on 1.7.1.Final using oracle jdk 11.0.2

**Comment by gsmet** [comment]
I would add quarkus-core and quarkus-arc.

**Comment by cpmoore** [comment]
Okay, yeah that worked!  I remember seeing that in the docs before now that you mention it.  Apologies, i'll close this.

**Comment by gsmet** [comment]
No worries :).
