### ISSUE TITLE
ReadTimeoutTest#testReadTimesOut fails once in a while

### ISSUE THREAD

**Issue by jaikiran** [quarkusio/quarkus#11841]
A recent CI job has shown the following failure:

```
2020-09-02T19:55:12.1887838Z [INFO] Running io.quarkus.resteasy.test.ReadTimeoutTestCase
2020-09-02T19:55:13.5299506Z 2020-09-02 19:55:13,523 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT on JVM started in 0.820s. Listening on: http://0.0.0.0:8081
2020-09-02T19:55:13.5300833Z 2020-09-02 19:55:13,523 INFO  [io.quarkus] (main) Profile test activated. 
2020-09-02T19:55:13.5301947Z 2020-09-02 19:55:13,523 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, security]
2020-09-02T19:55:15.4370546Z 2020-09-02 19:55:15,431 INFO  [io.quarkus] (main) Quarkus stopped in 0.031s
2020-09-02T19:55:15.4404878Z [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.255 s <<< FAILURE! - in io.quarkus.resteasy.test.ReadTimeoutTestCase
2020-09-02T19:55:15.4451962Z [ERROR] io.quarkus.resteasy.test.ReadTimeoutTestCase.testReadTimesOut  Time elapsed: 1.241 s  <<< FAILURE!
2020-09-02T19:55:15.4461213Z org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
2020-09-02T19:55:15.4496734Z 	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
2020-09-02T19:55:15.4504974Z 	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:40)
2020-09-02T19:55:15.4514844Z 	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:35)
2020-09-02T19:55:15.4520567Z 	at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:210)
2020-09-02T19:55:15.4528066Z 	at io.quarkus.resteasy.test.ReadTimeoutTestCase.testReadTimesOut(ReadTimeoutTestCase.java:47)
2020-09-02T19:55:15.4534483Z 	at 
```
Looking at this testcase (and some related ones) they all check the same `static` field `invoked`. So if multiple test methods (within the same test case) get executed in different threads (I don't know if JUnit 5 does that) then this can cause issues. It's either that or there's some genuine issue in the code (and not the test), because I don't see how else this test can fail at that line.

[1] https://github.com/quarkusio/quarkus/pull/11832/checks?check_run_id=1063416562

**Comment by jaikiran** [comment]
Outdated
