### ISSUE TITLE
Quarkus cli test failing 

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#11853]
**Describe the bug**

The `io.quarkus.cli.CliTest.testAddListRemove` is failing unrelated to the changes I was working on https://github.com/quarkusio/quarkus/pull/11852

https://github.com/quarkusio/quarkus/runs/1066539001

**Expected behavior**

The test to pass. 

**Actual behavior**

```log
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 169.318 s <<< FAILURE! - in io.quarkus.cli.CliTest
[ERROR] io.quarkus.cli.CliTest.testAddListRemove  Time elapsed: 1.703 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <quarkus-resteasy> but was: <>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at io.quarkus.cli.CliTest.testAddListRemove(CliTest.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
```

**Comment by gsmet** [comment]
Yeah, @ia3andy is working on it.
