### ISSUE TITLE
quarkus-integration-test-vault needs to be fixed

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#11879]
This module contains tests that make use of `io.quarkus.test.QuarkusUnitTest` from `io.quarkus:quarkus-junit5-internal` (such tests should reside in the `quarkus-vault-deployment` module). As a result a weird class loading behavior is observed.

NOTE: The problem was identified while investigating a failure in https://github.com/quarkusio/quarkus/pull/11848. For some reason the `VaultHealthCheck` class was considered an application class and included in the bean archive but `org.eclipse.microprofile.health.HealthCheck` that is referenced by this class was not visible when running the test (`io.quarkus:quarkus-smallrye-health` is an optional dependency of `io.quarkus:quarkus-vault`).

**Comment by sberyozkin** [comment]
Not sure iif #11753 related, @vsevel, hi Vincent, looks like Quarkus Vault (tests only :-)) need some expert attention :-)

**Comment by mkouba** [comment]
Hm, and it seems that the same applies to `quarkus-integration-test-vault-agroal`.

**Comment by vsevel** [comment]
hi @mkouba indeed those tests do use `QuarkusUnitTest` to be able to use different vault configurations. I have located those tests into the `integration-tests` module because they start a vault in a docker container. as such they really are integration tests.
I have seen other modules with the same pattern, such as `quarkus-integration-test-smallrye-context-propagation` for instance.
should `QuarkusUnitTest` usage be restricted to the deployment module?
on a side note, I have tried recompiling from the `1.7` branch and executing the vault native tests. I get a warning at startup `WARN: Setting the 'javax.net.ssl.trustStore' system property will not have any effect at runtime. Make sure to set this property at build time (for example by setting 'quarkus.native.additional-build-args=-J-Djavax.net.ssl.trustStore=someValue').` followed by an ssl initialization error. 
TLS configuration is supposed to be done by the `VaultTestLifecycleManager` referenced by the `@QuarkusTestResource` on each test. Another thing that has changed and is breaking the vault tests? so I guess I should be moving those system properties into all the vault `application.properties`?
And how could we release 1.7 with that error?

**Comment by vsevel** [comment]
I went back to the last commit I did 6 weeks ago `6993e3dd25 - Merge pull request #10887 from vsevel/create_policy (6 weeks ago) <George Gastaldi>` https://github.com/quarkusio/quarkus/pull/10887 from the 23rd of july, which targetted  1.7.0.CR1.
I did a full rebuild, and could not pass the native vault test because of the system property / tls error.

what could have possibly changed these last few days or weeks that we are no longer able to pass old code?

note however that the IT Vault and Vault Agroal do pass:
```
[INFO] Quarkus - Integration Tests - Vault ................ SUCCESS [ 53.685 s]
[INFO] Quarkus - Integration Tests - Vault Agroal ......... SUCCESS [ 33.302 s]
[INFO] Quarkus - Integration Tests - Vault App ............ FAILURE [07:20 min]
```

**Comment by vsevel** [comment]
I went further to `8e88110559 - add jbang labelling (2 days ago) <Max Rydahl Andersen>` just before your commit `bf1042c29f - Disable tests in quarkus-integration-test-vault... (2 days ago) <Martin Kouba>`.
and I was able to pass the vault IT tests (except the native one because of the ssl init error as usual):
```
[INFO] Quarkus - Integration Tests - Vault ................ SUCCESS [ 48.040 s]
[INFO] Quarkus - Integration Tests - Vault Agroal ......... SUCCESS [ 36.855 s]
```
I did a full rebuild without the tests, then I executed:
`./mvnw clean install -Dnative-image.docker-build -Dnative-image.xmx=6g -Dnative -Dno-format -Dvault-test-extension.use-tls=true -Dtest-vault -pl test-framework/vault -pl extensions/credentials -pl extensions/credentials/deployment -pl extensions/credentials/runtime -pl extensions/vault -pl extensions/vault/deployment -pl extensions/vault/runtime -pl extensions/agroal -pl extensions/agroal/deployment -pl extensions/agroal/runtime -pl integration-tests/vault -pl integration-tests/vault-agroal`
the only thing I can imagine is that the mvn command used to launch the tests in the github ci, or the maven config has changed somehow.

**Comment by vsevel** [comment]
I got confused by the git history. ignore the previous comment.
the commit before yours is actually `77383b555e Merge pull request #11884 from gsmet/update-guava (2 days ago) <Jaikiran>`. I was able to pass the tests (except the native one which has the system property init issue as discussed before).
so the tests stopped working in your commit `b97fc16a27 - Merge pull request #11848 from mkouba/arc-removed-beans-warning (2 days ago) <Martin Kouba>` (but you knew that already).

it sounds like the `VaultHealthCheck` class should not be loaded, since `quarkus.vault.health.enabled` is not defined (and is `false` by default). what do you think?

**Comment by mkouba** [comment]
> should QuarkusUnitTest usage be restricted to the deployment module?

Yes, I always thought so. If not then we have a class loading problem... CC @stuartwdouglas @gsmet @geoand @aloubyansky 

> it sounds like the VaultHealthCheck class should not be loaded, since quarkus.vault.health.enabled is not defined (and is false by default). what do you think?

And that's exactly the problem. Before my change in https://github.com/quarkusio/quarkus/pull/11848 all "unused" beans were just removed and ingnored at runtime during programmatic lookup. After my change we hold the bean types of the removed beans (unless `quarkus.arc.detect-unused-false-positives=false`) so that we're able to detect problems during programmatic lookup, i.e. if a removed bean matches the required type and qualifiers. But it seems that for the vault test the `VaultHealthCheck` is considered an application class even though it shoudn't be. Previously it was just removed because it's unused. In other words, I do think that the test passed previously by accidence.

**Comment by geoand** [comment]
> > should QuarkusUnitTest usage be restricted to the deployment module?
> 
> Yes, I always thought so. If not then we have a class loading problem... CC @stuartwdouglas @gsmet @geoand @aloubyansky
> 

This sounds reasonable to me

**Comment by stuartwdouglas** [comment]
They should work fine even in other modules. It is a bit confusing to have them in the integration-tests directory but there is no reason this should not work.

**Comment by mkouba** [comment]
> They should work fine even in other modules. It is a bit confusing to have them in the integration-tests directory but there is no reason this should not work.

Hm, then we have a bug in classloading or a specific pom config is needed.

Anyway, for integration tests we should probably use [test profiles](https://quarkus.io/blog/quarkus-test-profiles/) for similar use cases, or?

**Comment by vsevel** [comment]
I gave it a try in https://github.com/quarkusio/quarkus/commit/5506a49ac2dc4d59d262b298b0ca57b6d8d9a0f8
the test failed again on the vault health check `Caused by: java.lang.ClassNotFoundException: org.eclipse.microprofile.health.HealthCheck`.

```
VAULT >> ==> Vault server configuration:
VAULT >> 
VAULT >>                      Cgo: disabled
VAULT >>               Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "enabled")
VAULT >>                Log Level: debug
VAULT >>                    Mlock: supported: true, enabled: false
VAULT >>                  Storage: file
VAULT >>                  Version: Vault v1.2.2
VAULT >> 
VAULT >> ==> Vault server started! Log data will stream in below:
VAULT >> 
VAULT >> 2020-09-14T18:37:13.565Z [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
VAULT >> 2020-09-14T18:37:13.566Z [DEBUG] storage.cache: creating LRU cache: size=0
VAULT >> 2020-09-14T18:37:13.566Z [DEBUG] cluster listener addresses synthesized: cluster_addresses=[0.0.0.0:8201]
VAULT >> 2020-09-14T18:37:13.818Z [INFO]  http: TLS handshake error from 172.18.0.1:56984: EOF
VAULT >> 2020-09-14T18:37:14.413Z [INFO]  core: security barrier not initialized
VAULT >> 2020-09-14T18:37:14.415Z [INFO]  core: security barrier initialized: shares=1 threshold=1
VAULT >> 2020-09-14T18:37:14.415Z [DEBUG] core: cluster name not found/set, generating new
VAULT >> 2020-09-14T18:37:14.415Z [DEBUG] core: cluster name set: name=vault-cluster-e3d555d8
VAULT >> 2020-09-14T18:37:14.415Z [DEBUG] core: cluster ID not found, generating new
VAULT >> 2020-09-14T18:37:14.415Z [DEBUG] core: cluster ID set: id=ce6c46af-5a75-3f7f-ab69-8effde0fd984
VAULT >> 2020-09-14T18:37:14.416Z [INFO]  core: post-unseal setup starting
VAULT >> 2020-09-14T18:37:14.416Z [DEBUG] core: clearing forwarding clients
VAULT >> 2020-09-14T18:37:14.416Z [DEBUG] core: done clearing forwarding clients
VAULT >> 2020-09-14T18:37:14.459Z [INFO]  core: loaded wrapping token key
VAULT >> 2020-09-14T18:37:14.461Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
VAULT >> 2020-09-14T18:37:14.464Z [INFO]  core: no mounts; adding default mount table
VAULT >> 2020-09-14T18:37:14.483Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
VAULT >> 2020-09-14T18:37:14.485Z [INFO]  core: successfully mounted backend: type=system path=sys/
VAULT >> 2020-09-14T18:37:14.487Z [INFO]  core: successfully mounted backend: type=identity path=identity/
VAULT >> 2020-09-14T18:37:14.501Z [INFO]  core: successfully enabled credential backend: type=token path=token/
VAULT >> 2020-09-14T18:37:14.501Z [INFO]  core: restoring leases
VAULT >> 2020-09-14T18:37:14.503Z [INFO]  rollback: starting rollback manager
VAULT >> 2020-09-14T18:37:14.503Z [DEBUG] expiration: collecting leases
VAULT >> 2020-09-14T18:37:14.503Z [DEBUG] identity: loading entities
VAULT >> 2020-09-14T18:37:14.506Z [DEBUG] identity: entities collected: num_existing=0
VAULT >> 2020-09-14T18:37:14.506Z [INFO]  identity: entities restored
VAULT >> 2020-09-14T18:37:14.506Z [DEBUG] identity: identity loading groups
VAULT >> 2020-09-14T18:37:14.507Z [DEBUG] identity: groups collected: num_existing=0
VAULT >> 2020-09-14T18:37:14.507Z [INFO]  identity: groups restored
VAULT >> 2020-09-14T18:37:14.507Z [INFO]  core: post-unseal setup complete
VAULT >> 2020-09-14T18:37:14.513Z [DEBUG] expiration: leases collected: num_existing=0
VAULT >> 2020-09-14T18:37:14.513Z [INFO]  expiration: lease restore complete
VAULT >> 2020-09-14T18:37:14.514Z [INFO]  core: root token generated
VAULT >> 2020-09-14T18:37:14.514Z [INFO]  core: pre-seal teardown starting
VAULT >> 2020-09-14T18:37:14.514Z [DEBUG] expiration: stop triggered
VAULT >> 2020-09-14T18:37:14.514Z [DEBUG] expiration: finished stopping
VAULT >> 2020-09-14T18:37:14.514Z [INFO]  rollback: stopping rollback manager
VAULT >> 2020-09-14T18:37:14.515Z [INFO]  core: pre-seal teardown complete
VAULT >> 2020-09-14T18:37:15.332Z [DEBUG] core: unseal key supplied
VAULT >> 2020-09-14T18:37:15.332Z [DEBUG] core: starting cluster listeners
VAULT >> 2020-09-14T18:37:15.332Z [INFO]  core.cluster-listener: starting listener: listener_address=0.0.0.0:8201
VAULT >> 2020-09-14T18:37:15.333Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:8201
VAULT >> 2020-09-14T18:37:15.333Z [INFO]  core: post-unseal setup starting
VAULT >> 2020-09-14T18:37:15.333Z [DEBUG] core: clearing forwarding clients
VAULT >> 2020-09-14T18:37:15.334Z [DEBUG] core: done clearing forwarding clients
VAULT >> 2020-09-14T18:37:15.334Z [INFO]  core: loaded wrapping token key
VAULT >> 2020-09-14T18:37:15.334Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
VAULT >> 2020-09-14T18:37:15.341Z [INFO]  core: successfully mounted backend: type=system path=sys/
VAULT >> 2020-09-14T18:37:15.343Z [INFO]  core: successfully mounted backend: type=identity path=identity/
VAULT >> 2020-09-14T18:37:15.343Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
VAULT >> 2020-09-14T18:37:15.355Z [INFO]  core: successfully enabled credential backend: type=token path=token/
VAULT >> 2020-09-14T18:37:15.355Z [INFO]  core: restoring leases
VAULT >> 2020-09-14T18:37:15.357Z [INFO]  rollback: starting rollback manager
VAULT >> 2020-09-14T18:37:15.357Z [DEBUG] expiration: collecting leases
VAULT >> 2020-09-14T18:37:15.358Z [DEBUG] expiration: leases collected: num_existing=0
VAULT >> 2020-09-14T18:37:15.361Z [INFO]  expiration: lease restore complete
VAULT >> 2020-09-14T18:37:15.363Z [DEBUG] identity: loading entities
VAULT >> 2020-09-14T18:37:15.363Z [DEBUG] identity: entities collected: num_existing=0
VAULT >> 2020-09-14T18:37:15.363Z [INFO]  identity: entities restored
VAULT >> 2020-09-14T18:37:15.363Z [DEBUG] identity: identity loading groups
VAULT >> 2020-09-14T18:37:15.363Z [DEBUG] identity: groups collected: num_existing=0
VAULT >> 2020-09-14T18:37:15.363Z [INFO]  identity: groups restored
VAULT >> 2020-09-14T18:37:15.365Z [DEBUG] core: request forwarding setup function
VAULT >> 2020-09-14T18:37:15.365Z [DEBUG] core: clearing forwarding clients
VAULT >> 2020-09-14T18:37:15.365Z [DEBUG] core: done clearing forwarding clients
VAULT >> 2020-09-14T18:37:15.365Z [DEBUG] core: request forwarding not setup
VAULT >> 2020-09-14T18:37:15.365Z [DEBUG] core: leaving request forwarding setup function
VAULT >> 2020-09-14T18:37:15.365Z [INFO]  core: post-unseal setup complete
VAULT >> 2020-09-14T18:37:15.366Z [INFO]  core: vault is unsealed
VAULT >> 2020-09-14T18:37:15.944Z [INFO]  core: enabled credential backend: path=userpass/ type=userpass
VAULT >> 2020-09-14T18:37:17.010Z [INFO]  core: enabled credential backend: path=kubernetes/ type=kubernetes
VAULT >> 2020-09-14T18:37:17.459Z [INFO]  core: enabled credential backend: path=approle/ type=approle
VAULT >> 2020-09-14T18:37:18.664Z [INFO]  core: successful mount: namespace= path=secret-v1/ type=kv
VAULT >> 2020-09-14T18:37:20.150Z [INFO]  core: successful mount: namespace= path=secret/ type=kv
VAULT >> 2020-09-14T18:37:20.160Z [INFO]  secrets.kv.kv_272cba4d: collecting keys to upgrade
VAULT >> 2020-09-14T18:37:20.161Z [INFO]  secrets.kv.kv_272cba4d: done collecting keys: num_keys=1
VAULT >> 2020-09-14T18:37:20.162Z [DEBUG] secrets.kv.kv_272cba4d: upgrading keys: progress=0/1
VAULT >> 2020-09-14T18:37:20.162Z [INFO]  secrets.kv.kv_272cba4d: upgrading keys finished
VAULT >> 2020-09-14T18:37:27.523Z [INFO]  core: successful mount: namespace= path=database/ type=database
VAULT >> 2020-09-14T18:37:27.526Z [INFO]  secrets.database.database_d2229306: initializing database rotation queue
VAULT >> 2020-09-14T18:37:27.531Z [INFO]  secrets.database.database_d2229306: populating role rotation queue
VAULT >> 2020-09-14T18:37:27.541Z [INFO]  secrets.database.database_d2229306: starting periodic ticker
VAULT >> 2020-09-14T18:37:28.901Z [INFO]  core: successful mount: namespace= path=transit/ type=transit
VAULT >> 2020-09-14T18:37:32.424Z [INFO]  core: successful mount: namespace= path=totp/ type=totp
VAULT >> [ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 10, Time elapsed: 155.677 s <<< FAILURE! - in io.quarkus.vault.VaultAppRoleITCase
[ERROR] io.quarkus.vault.VaultAppRoleITCase.secretV2  Time elapsed: 0.023 s  <<< ERROR!
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:534)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeEach(QuarkusTestExtension.java:384)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:161)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:197)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:197)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:160)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:196)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:234)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:512)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:545)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
        ... 32 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:146)
        ... 44 more
Caused by: java.lang.RuntimeException: Failed to initialize Arc
        at io.quarkus.arc.Arc.initialize(Arc.java:26)
        at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:24)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy_0(ArcProcessor$generateResources-1025303321.zig:76)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy(ArcProcessor$generateResources-1025303321.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:126)
        ... 44 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/microprofile/health/HealthCheck
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:400)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:363)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at io.quarkus.arc.setup.Default_ComponentsProvider.addRemovedBeans1(Default_ComponentsProvider.zig:2104)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:68)
        at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:113)
        at io.quarkus.arc.Arc.initialize(Arc.java:20)
        ... 48 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.microprofile.health.HealthCheck
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:406)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:363)
        ... 58 more

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   VaultAppRoleITCase.secretV2 » Runtime java.lang.ExceptionInInitializerError
[INFO] 
[ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 10
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ quarkus-integration-test-vault ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by mkouba** [comment]
@vsevel Maybe try to remove the `quarkus-vault-deployment` from the pom?

**Comment by vsevel** [comment]
@mkouba same issue https://github.com/vsevel/quarkus/commit/a534fbd7351274f95be35d9146b52a795d5db9bb
