### ISSUE TITLE
Micrometer extension didn't work with the security-oauth2 extension

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#12029]
**Describe the bug**
When using micrometer extension and security-oauth2 I have the following exception:

```
 java.lang.NullPointerException
	at io.quarkus.micrometer.runtime.binder.vertx.MetricsContext.addRoutingContext(MetricsContext.java:44)
	at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterFilter.handle(VertxMeterFilter.java:18)
	at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterFilter.handle(VertxMeterFilter.java:10)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:116)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.checkPermission(HttpAuthorizer.java:99)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:214)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:206)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:139)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:100)
```

The exception didn't occurs if I remove the security extensions.
The exception didn' occurs with smallrye-metrics.

This is the complete list of extensions I use: agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, hibernate-validator, jaeger, jdbc-postgresql, micrometer, mutiny, narayana-jta, rest-client, resteasy, resteasy-jsonb, security, security-oauth2, security-properties-file, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-openapi, smallrye-opentracing, swagger-ui

The same issue occurs with security-properties-file so it should occurs on all security extensions.

Adding DEBUG logging on Quarkus shows where the errors comes from:
```
DEBUG [io.qua.mic.run.bin.ver.VertxMeterFilter] (executor-thread-1) Handling event io.vertx.ext.web.impl.RoutingContextImpl@40da89c3 with context null
```
The Vert.x Context is null on this line this the NPE: https://github.com/quarkusio/quarkus/blob/master/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/VertxMeterFilter.java#L15

**Comment by gsmet** [comment]
@ebullient any chance you could have a look soon? I think it's something I would want for 1.8.1 and, considering a few issues I saw, it might be closer than expected (I might release something on Friday).

**Comment by ebullient** [comment]
Yes. sorry. distracted w/ kids' school starting.
