### ISSUE TITLE
Extend AWS DynamoDB extension for usage with Enhanced DynamoDb Client

### ISSUE THREAD

**Issue by dasniko** [quarkusio/quarkus#12168]
**Description**
Extend AWS DynamoDB extension for usage with Enhanced DynamoDb Client

There is a new enhanced DynamoDb client available since April this year: https://aws.amazon.com/de/blogs/developer/introducing-enhanced-dynamodb-client-in-the-aws-sdk-for-java-v2/
This enhanced client makes it a lot easier to work with DynamoDb and mapping items (see examples here: https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/examples-dynamodb-enhanced.html

Currently, when used with Quarkus, a `java.lang.NoClassDefFoundError: dasniko/quarkus/Book` is thrown if this code is being executed in my service class (it's thrown in the line with `getItem(...)`):

```
@Inject
DynamoDbClient ddb;
...
DynamoDbEnhancedClient enhancedClient = DynamoDbEnhancedClient.builder().dynamoDbClient(ddb).build();
DynamoDbTable<Book> booksTable = enhancedClient.table("quarkus-books", TableSchema.fromBean(Book.class));
Book book = booksTable.getItem(Key.builder().partitionValue("foo").build());
...
```
with `Book.java` being:
```
@DynamoDbBean
public class Book {
  private String id;

  @DynamoDbPartitionKey
  public String getId() { return id; }

  public void setId(String id) { this.id = id; }
  ...
}
```

I would expect to work without `NoClassDefFoundError` or other ClassLoading issues.

**Comment by Temdegon** [comment]
I've checked that with similar code and it looks like the problem exists only in dev-mode. If I start the app in the normal mode it works fine. Could you pls recheck and probably adjust the bug description?

**Comment by abouzar** [comment]
Run into the same issue. @Temdegon Yes it does work in normal mode, but it does not work in dev mode. Not sure what in the description can be changed.
- quarkus version: 1.9.2
- dynamodb-enhanced: 2.15.33

**Comment by Thul95** [comment]
Hi, we're also looking in to the quarkus Dynamodb extension with the DynamoDbEnhancedClient. With quarkus version 1.10.3.FINAL building the native image works but at runtime it fails. @Temdegon @abouzar @dasniko did you guys get it working in native mode?

`
java.lang.IllegalArgumentException: Failed to generate method handle.
software.amazon.awssdk.enhanced.dynamodb.internal.mapper.LambdaToMethodBridgeBuilder.build(LambdaToMethodBridgeBuilder.java:92)
software.amazon.awssdk.enhanced.dynamodb.internal.mapper.ObjectConstructor.create(ObjectConstructor.java:37)
software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.newObjectSupplierForClass(BeanTableSchema.java:330)
software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.createStaticTableSchema(BeanTableSchema.java:167)
software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.create(BeanTableSchema.java:124)
software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.create(BeanTableSchema.java:116)
software.amazon.awssdk.enhanced.dynamodb.TableSchema.fromBean(TableSchema.java:80)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported constructor java.lang.invoke.MemberName.<init>(Constructor) is reachable: All methods from java.lang.invoke should have been replaced during image building.
at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
at java.lang.invoke.MemberName.<init>(MemberName.java:665)
java.lang.invoke.MethodHandles$Lookup.unreflectConstructor(MethodHandles.java:1826)
software.amazon.awssdk.enhanced.dynamodb.internal.mapper.LambdaToMethodBridgeBuilder.lambda$null$2(LambdaToMethodBridgeBuilder.java:80)
software.amazon.awssdk.utils.FunctionalUtils.lambda$safeSupplier$4(FunctionalUtils.java:108)
software.amazon.awssdk.utils.FunctionalUtils.invokeSafely(FunctionalUtils.java:136)
software.amazon.awssdk.enhanced.dynamodb.internal.mapper.LambdaToMethodBridgeBuilder.lambda$build$3(LambdaToMethodBridgeBuilder.java:80)
at java.util.Optional.map(Optional.java:265)
at software.amazon.awssdk.utils.Either.lambda$map$0(Either.java:51)
at java.util.Optional.orElseGet(Optional.java:369)
at software.amazon.awssdk.utils.Either.map(Either.java:51)
at software.amazon.awssdk.enhanced.dynamodb.internal.mapper.LambdaToMethodBridgeBuilder.build(LambdaToMethodBridgeBuilder.java:78)
`

**Comment by thuringia** [comment]
I second this wholeheartedly. In my case, it doesn't even work in JVM-mode (further Mutiny-related part of the stacktrace omitted):
```
2021-01-20 15:53:27,632 FATAL [DeltaFeedImporter] (executor-thread-1) Failed processing: java.lang.NoClassDefFoundError: de/Product
        at software.amazon.awssdk.enhanced.dynamodb.internal.mapper.ResolvedImmutableAttribute.lambda$create$0(ResolvedImmutableAttribute.java:48)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.lambda$itemToMap$5(StaticImmutableTableSchema.java:491)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.itemToMap(StaticImmutableTableSchema.java:489)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.WrappedTableSchema.itemToMap(WrappedTableSchema.java:59)
        at de.Product.toDynamoMap(Product.java:402)
        at de.DeltaFeedImporter$run$2$1.accept(DeltaFeedImporter.kt:134)
        at de.DeltaFeedImporter$run$2$1.accept(DeltaFeedImporter.kt:26)
        at software.amazon.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:61)
        at software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient.putItem(DynamoDbAsyncClient.java:4611)
        at io.quarkus.amazon.dynamodb.runtime.DynamodbClientProducer_ProducerMethod_asyncClient_99195d6ecfcee8054031feec789826b26310b4ae_ClientProxy.putItem(DynamodbClientProducer_ProducerMethod_asyncClient_99195d6ecfcee8054031feec789826b26310b4ae_ClientProxy.zig:267)
        at de.DeltaFeedImporter$run$2.apply(DeltaFeedImporter.kt:133)
        at de.DeltaFeedImporter$run$2.apply(DeltaFeedImporter.kt:26)
        at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:42)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$ContextPropagationSubscriber.lambda$onNext$1(ContextPropagationMultiInterceptor.java:89)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
        at io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$ContextPropagationSubscriber.onNext(ContextPropagationMultiInterceptor.java:89)
        at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
```
Based on issues like aws/aws-sdk-java-v2#2198 this seems to be an issue with Quarkus' use of reflection and/or code generation.

This is on top of the, rather abysmal, support for mapping of the V2 DynamoDB SDK to begin with, making this quite frustrating to use if I'm honest.

Personally, I would have preferred that Quarkus does not ship an extension if it cannot wrap the SDK completely but rather document how to make the SDK usable from Quarkus, or the Extension shipping appropriate utilities. 

So it looks like we have to map bean oursel

**Comment by drissamri** [comment]
I guess the AWS/DynamoDB extension has to be extended (https://github.com/quarkusio/quarkus/pull/4968) to support the Enhanced Mapper. It would be great that the AWS CRT HTTP Client would also be supported since it's a lot faster: https://aws.amazon.com/about-aws/whats-new/2020/09/aws-crt-http-client-in-aws-sdk-for-java-2x/

**Comment by dinesh-monickaraj** [comment]
Is the java.lang.NoClassDefFoundError while using @DynamoDbBean on quarkusDev mode  has any workaround ? Anybody have any suggestions ?

**Comment by Max161** [comment]
I'm not really sure if it can help you, but with my original issue [here](https://github.com/aws/aws-sdk-java-v2/issues/2198) I solved the issue by creating a separate module (jar) only for dynamoDB mode with annotations ectl, and then imported ituse it within the original

**Comment by rohit-gandhe** [comment]
Yeah, this takes away a lot from the advantage of hot reloading!!

**Comment by rohit-gandhe** [comment]
> I'm not really sure if it can help you, but with my original issue [here](https://github.com/aws/aws-sdk-java-v2/issues/2198) I solved the issue by creating a separate module (jar) only for dynamoDB mode with annotations etc and then imported it within the original project.

@Max161  Did you move just the @DynamoDBBean classes to another module or DAO classes as well?

**Comment by Max161** [comment]
> > I'm not really sure if it can help you, but with my original issue [here](https://github.com/aws/aws-sdk-java-v2/issues/2198) I solved the issue by creating a separate module (jar) only for dynamoDB mode with annotations etc and then imported it within the original project.
> 
> @Max161 Did you move just the @DynamoDBBean classes to another module or DAO classes as well?

I tried out different solutions. In the beginning, I moved the whole domain model (POJOs) to the jar including the dynamoDB beans with the annotations too (persistence module). But I didn't like it. The whole domain and persistence modules were so tightly coupled that it became a nightmare. 
The dynamo enhanced library is using `Class.forName` at some point... The frameworks like Quarkus and play framework, that uses the hot reloading feature should **NOT** be "watching" the libraries that use `Class.forName`. As it's reported also [here](https://github.com/playframework/playframework/issues/2847#issuecomment-44243893) and [here](https://www.scala-sbt.org/1.x/docs/In-Process-Classloaders.html) the use of `Class.forName` is not a good idea. 

I really think that the issue needs to be solved on the AWS side.

One of the other solutions was to remove the use of the enhanced features and to create a manual Mapper that created the entities on the fly after retrieving them, decoupling so the domain and the persistence modules.

Hope it helps, 
Max

**Comment by vaibhav170** [comment]
%dev.quarkus.class-loading.reloadable-artifacts=software.amazon.awssdk:dynamodb-enhanced
this is working for dev mode issue at least with latest dependency

**Comment by Temdegon** [comment]
It looks like this issue could be closed since the release of quarkus-amazon-dynamodb-enhanced

 https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/amazon-dynamodb.html#_dynamodb_enhanced_client
