### ISSUE TITLE
Hibernate-validator: @Valid annotation on the Object type attribute.

### ISSUE THREAD

**Issue by andrejpetras** [quarkusio/quarkus#12214]
**Describe the bug**
If `@Valid` annotation is added to the `Object` type attribute the `HibernateValidatorProcessor` will add all sub-classes of the Object to the list `classesToBeValidated` for the `HibernateValidatorRecorder`
https://github.com/quarkusio/quarkus/blob/ebfeffcebfdbbf5ab7fc8c873eeecde90f8bdee2/extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java#L251

https://github.com/quarkusio/quarkus/blob/ebfeffcebfdbbf5ab7fc8c873eeecde90f8bdee2/extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java#L310

For example if we use the flyway for the database migration the HibernateValidatorProcessor will add all the flyway optional runtime classes. For example: 'org.flywaydb.core.internal.scanner.classpath.jboss.JBossVFSv3ClassPathLocationScanner'

**To Reproduce**
Example rest controller
```
@Path("/test")
public class TestRestController {

    @GET
    public DataDTO post() {
        return new DataDTO();
    }

    @Data
    public static class DataDTO {
        private @Valid Object name;
    }
}
```
Result:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:293)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: org/jboss/vfs/VirtualFileFilter
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at io.quarkus.deployment.steps.HibernateValidatorProcessor$build-642046765.deploy_1(HibernateValidatorProcessor$build-642046765.zig:8788)
        at io.quarkus.deployment.steps.HibernateValidatorProcessor$build-642046765.deploy(HibernateValidatorProcessor$build-642046765.zig:45)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:218)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: org.jboss.vfs.VirtualFileFilter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 14 more
```

Class: io/quarkus/deployment/steps/HibernateValidatorProcessor$build-642046765
```
INVOKEVIRTUAL java/lang/Thread#getContextClassLoader
    ASTORE 218
    LDC (String) "org.flywaydb.core.internal.scanner.classpath.jboss.JBossVFSv3ClassPathLocationScanner$1"
    LDC (Boolean) true
    ALOAD 218
    // Method descriptor: (Ljava/lang/String;ZLjava/lang/ClassLoader;)Ljava/lang/Class;
    INVOKESTATIC java/lang/Class#forName
```

**Comment by Postremus** [comment]
Hi @andrejpetras 

I had reported the same problem in #12443. `@Valid Object` does not iterate over all subclasses anymore.

**Comment by gsmet** [comment]
Thanks @Postremus
