### ISSUE TITLE
Combining persist() and a (typed) query in a nested transaction will timeout when using MSSQL

### ISSUE THREAD

**Issue by krpors** [quarkusio/quarkus#12229]
**Describe the bug**
When using MSSQL, code involving a `persist()` and a query in two different transaction scopes, it results in an exception as follows, after ~60 seconds:

    Caused by: javax.transaction.RollbackException: ARJUNA016102: The transaction is not active! Uid is 0:ffffc0a8b239:a3e3:5f68787b:0
        at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1277)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:126)
        (...)

In short, something like this can reproduce it:

```java
@ApplicationScoped
public class A {

	@Inject
	EntityManager entityManager;

	@Transactional
	public void persistSomething() {
		// persist here
		entityManager.persist(...);

		querySomething();
	}

	@Transactional(Transactional.TxType.NOT_SUPPORTED)
	private void querySomething() {
		// query something here, exception happens
	}
}
```

I've attached a Maven project (including a README with detailed instructions) which can reproduce it.

**Expected behavior**
No exception occurs.

**Actual behavior**
An exception occurs saying the transaction is not active.

**To Reproduce**

See attachment [txtest.zip](https://github.com/quarkusio/quarkus/files/5254938/txtest.zip). The project has a `README.md` with reproduction steps. For completion sake I add them here as well:

1. Start a Docker instance of MSSQL: `docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 21433:1433 -d mcr.microsoft.com/mssql/server:2017-CU8-ubuntu`.
2. Run the Quarkus instance: `mvn clean install quarkus:dev`
3. Call the endpoint: `curl http://localhost:8080/hello`
4. The command should hang for ~60 seconds before returning, and displaying an exception stacktrace.

**Configuration**

See project in the attachment.

**Environment:**

```bash
$ uname -a
Linux qlt743 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

```bash
$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/krpors/Apps/maven
Java version: 11.0.4, vendor: AdoptOpenJDK, runtime: /home/krpors/Apps/jdk-11.0.4+11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-23-generic", arch: "amd64", family: "unix"

```

**Additional notes**

Other notes:

- I've tried it with H2 and with PostgreSQL, and I cannot reproduce the issue on those two databases.
- I also tried to exclude the default JDBC driver for MSSQL and providing version 8.4.1.jre11, but same behavior.
- Tried Quarkus 1.8.0 and 1.8.1

**Comment by suchwerk** [comment]
Same here with Quarkus 1.9.2.Final

**Comment by knutwannheden** [comment]
Also with Quarkus 2.15.0.Final this problem can be observed. Example:
```java
    @Transactional(Transactional.TxType.REQUIRED)
    public void persist() {
        MyEntity entity = new MyEntity();
        entity.setId(1L);
        em.merge(entity);
        em.flush(); // NOTE: works if this line is commented out
        persistInNewTx(em.find(MyEntity.class, 1L));
    }

    @Transactional(Transactional.TxType.REQUIRES_NEW)
    public void persistInNewTx(MyEntity entity) {
        em.merge(entity);
    }
```

What is interesting is that in this example (attached [here](https://github.com/quarkusio/quarkus/files/10269646/nested-transaction.zip)) the test works if the `EntityManager#flush()` call in the outer transaction is commented out.

**Comment by geoand** [comment]
I have no idea, I've never seen this issue

**Comment by lucamolteni** [comment]
> Hi I'm wondering if there's an update to this issue? I am also using mssql and using a nested persist() followed by typed query. I think the issue still exist in quarkus build 2.16
> 
> My stack trace is: `2023-04-12 12:03:54 2023-04-12 19:03:54,987 WARN [com.arj.ats.common] (executor-thread-0) ARJUNA048006: cannot create new instance of com.arjuna.ats.internal.arjuna.objectstore.ShadowNoFileLockStore: java.lang.reflect.InvocationTargetException 2023-04-12 12:03:54 at java.base@17.0.6/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) 2023-04-12 12:03:54 at java.base@17.0.6/java.lang.reflect.Constructor.newInstance(Constructor.java:480) 2023-04-12 12:03:54 at com.arjuna.common.internal.util.ClassloadingUtility.loadAndInstantiateClass(ClassloadingUtility.java:129) 2023-04-12 12:03:54 at com.arjuna.ats.arjuna.objectstore.StoreManager.initStore(StoreManager.java:152) 2023-04-12 12:03:54 at 

Have you tried by any chance to check whether this problem still holds in Quarkus 3?

**Comment by suchwerk** [comment]
Still the same with the example from @knutwannheden 
```
2026-05-11 09:42:06,469 INFO  [io.quarkus] (main) nested-transaction 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.35.2) started in 10.267s. 
2026-05-11 09:42:06,469 INFO  [io.quarkus] (main) Profile test activated. 
2026-05-11 09:42:06,470 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, compose, hibernate-orm, jdbc-mssql, narayana-jta, smallrye-context-propagation]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.925 s <<< FAILURE! - in org.acme.MyRepoTest
[ERROR] org.acme.MyRepoTest.test  Time elapsed: 0.092 s  <<< ERROR!
jakarta.persistence.OptimisticLockException: Row was already updated or deleted by another transaction for entity [org.acme.MyEntity with id '1']
	at org.hibernate.internal.ExceptionConverterImpl.wrapStaleStateException(ExceptionConverterImpl.java:220)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:83)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:173)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:179)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:815)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:788)
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.merge(TransactionScopedSession.java:181)
	at org.hibernate.engine.spi.SessionLazyDelegator.merge(SessionLazyDelegator.java:207)
	at org.hibernate.Session_x03UFp930IxQOyJJLmtWw2baujI_Synthetic_ClientProxy.merge(Unknown Source)
	at org.acme.MyRepo.persist(MyRepo.java:17)
	at org.acme.MyRepo_Subclass.persist$$superforward(Unknown Source)
	at org.acme.MyRepo_Subclass$0.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInCallerTx(TransactionalInterceptorBase.java:365)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:39)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:81)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:31)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at org.acme.MyRepo_Subclass.persist(Unknown Source)
	at org.acme.MyRepo_ClientProxy.persist(Unknown Source)
	at org.acme.MyRepoTest.test(MyRepoTest.java:21)
Caused by: org.hibernate.StaleObjectStateException: Row was already updated or deleted by another transaction for entity [org.acme.MyEntity with id '1']
	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:432)
	at org.hibernate.event.internal.DefaultMergeEventListener.merge(DefaultMergeEventListener.java:193)
	at org.hibernate.event.internal.DefaultMergeEventListener.doMerge(DefaultMergeEventListener.java:137)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:117)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:78)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:138)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:803)
	... 20 more
```
