### ISSUE TITLE
Sentry Connection Timeout

### ISSUE THREAD

**Issue by aguilardias** [quarkusio/quarkus#12307]
**Description**
Using quarkus-logging-sentry, im receiving the follow exception
```
2020-09-23 13:02:19,227 ERROR [io.sen.con.AsyncConnection] (sentry-pool-1-thread-1) An exception occurred while sending the event to Sentry.: io.sentry.connection.ConnectionException: An exception occurred while submitting the event to the Sentry server.
	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:216)
	at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:88)
	at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
	at io.sentry.connection.HttpConnection.doSend(HttpConnection.java:168)
	... 5 more
```

I saw that in class
DefaultSentryClientFactory, the default connection timeout is just 1 second, so in my environment this time is not enough to get the connection
public static final int CONNECTION_TIMEOUT_DEFAULT = (int) TimeUnit.SECONDS.toMillis(1);

Quarkus doesnt have a config for this, so is there any other way to change this default value? or is possible to put this config in quarkus options?
https://quarkus.io/guides/logging-sentry#configuration-reference

**Comment by aguilardias** [comment]
we can configure timeout and other properties, adding a parameter on DSN url, example:
quarkus.log.sentry.dsn=[url]?timeout=10000
So now the connection timeout is 10 seconds

For a complete configurations options list:
https://docs.sentry.io/platforms/java/configuration/options/#options
