### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: Class CustomSerializer has no default (no arg) constructor

### ISSUE THREAD

**Issue by banifou** [quarkusio/quarkus#12345]
**Describe the bug**
I'm using a custom serialiser extending `com.fasterxml.jackson.databind.ser.std.StdSerializer` to serve a REST Api. It works fine in OpenJDK 11. When I run it in native mode, I get a _no default (no arg) constructor_ error.

**Expected behavior**
Get my java object serialized serving/producing an `application/json` endpoint.

**Actual behavior**
When i try to get the serialized entity object retrieved from Postgresql with the native image (in GET) it does throw error

```
com.fasterxml.jackson.databind.JsonMappingException: Class com.example.utils.BookSerializer has no default (no arg) constructor (through reference chain: java.util.ArrayList[1]->com.example.model.entities.OfferBasket["bookBaskets"]->org.hibernate.collection.internal.PersistentSet[0]->com.example.model.entities.BookBasket["bookList"]->org.hibernate.collection.internal.PersistentSet[0])
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:610)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:520)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:131)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Class com.example.utils.BookSerializer has no default (no arg) constructor (through reference chain: java.util.ArrayList[1]->com.example.model.entities.OfferBasket["bookBaskets"]->org.hibernate.collection.internal.PersistentSet[0]->com.example.model.entities.BookBasket["bookList"]->org.hibernate.collection.internal.PersistentSet[0])
	at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1309)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1427)
	at com.fasterxml.jackson.databind.SerializerProvider.findContentValueSerializer(SerializerProvider.java:754)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSecondarySerializer(PropertySerializerMap.java:90)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase._findAndAddDynamic(AsArraySerializerBase.java:304)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:140)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase._serializeWithObjectId(BeanSerializerBase.java:667)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:171)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1516)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1006)
	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.writeTo(ResteasyJackson2Provider.java:329)
	at org.jboss.resteasy.core.messagebody.AsyncBufferedMessageBodyWriter.asyncWriteTo(AsyncBufferedMessageBodyWriter.java:24)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:87)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.asyncProceed(AbstractWriterInterceptorContext.java:203)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:166)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:93)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:163)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:590)
	... 20 more
```

Note that the class actually does have a no-arg constructor:

```
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.example.model.entities.Book;
import java.io.IOException;

public class BookSerializer extends StdSerializer<Book> {

    public BookSerializer(Class<Book> t) {
        super(t);
    }
    
    public BookSerializer() {
       super(Book.class);
   }

    @Override
    public void serialize(Book book, JsonGenerator jsonGenerator, SerializerProvider sp) throws IOException {
        .
        .
        .
    }
}
```

**Environment (please complete the following information):**

Ubuntu 20.04.1 LTS. Graalvm-ce-java11-linux-amd64-20.2.0. Quarkus 1.8.1

**Comment by geoand** [comment]
Hi,

How do you register your serializer with Jackson?

**Comment by banifou** [comment]
Hi, in the entity bean like this `@JsonSerialize(using = BookSerializer.class)`

**Comment by gsmet** [comment]
We have some code to deal with that but apparently we're missing something.

Could you prepare a small reproducer so that we can have a look?

Thanks!

**Comment by banifou** [comment]
Here is my reproducer project, can checkout it? https://github.com/banifou/jdbc-jackson-serialiser

**Comment by zipper01** [comment]
Hi, I still got this problem. Code:

    package com.mysys.myclient.sub;
    
    import com.fasterxml.jackson.core.JsonParser;
    import com.fasterxml.jackson.core.JsonProcessingException;
    import com.fasterxml.jackson.core.type.TypeReference;
    import com.fasterxml.jackson.databind.DeserializationContext;
    import com.fasterxml.jackson.databind.JsonNode;
    import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
    import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
    import static com.mysys.myclient.CfgMgr.jsonObjectMapper;
    import java.io.IOException;
    import java.util.concurrent.ConcurrentHashMap;
    
    @JsonDeserialize(using = Subscriber.Deserializer.class)
    
    public class Subscriber {
    
        public int statusId;
        public String name;
        public String password;
        public final ConcurrentHashMap<Integer, Account> accounts;
    
        public Subscriber(int statusId, String name, String password, ConcurrentHashMap<Integer, Account> accounts) {
            this.statusId = statusId;
            this.name = name;
            this.password = password;
            this.accounts = accounts;
        }
    
        public static class Deserializer extends StdDeserializer<Subscriber> {
    
            public Deserializer() {
                super(Subscriber.class);
            }
    
            public Deserializer(Class<?> vc) {
                super(vc);
            }
    
            @Override
            public Subscriber deserialize(JsonParser jp, DeserializationContext ctx)
                    throws IOException, JsonProcessingException {
                JsonNode node = jp.getCodec().readTree(jp);
                if (node.isEmpty()) {
                    return null;
                }
                JsonNode v = node.get("statusId");
                int id = v == null ? -1 : v.asInt(-1);
                v = node.get("name");
                String name = v == null ? null : v.asText(null);
                v = node.get("password");
                String password = v == null ? null : v.asText(null);
                ConcurrentHashMap<Integer, Account> accounts = null;
                v = node.get("accounts");
                if (v != null) {
                    accounts = jsonObjectMapper.convertValue(v,
                            new TypeReference<ConcurrentHashMap<Integer, Account>>() {
                    });
                }
                return new Subscriber(id, name, password, accounts);
            }
        }
    
    }

    Version info: 'GraalVM 22.3.0 Java 17 CE'
    Java version info: '17.0.5+8-jvmci-22.3-b08'
    C compiler: gcc (redhat, x86_64, 8.5.0)
    Garbage collector: Serial GC

**Comment by geoand** [comment]
@zipper01 any chance you can attach a sample application we can try?

**Comment by zipper01** [comment]
@geoand please see here:
https://github.com/zipper01/reprocedure-for-quarkusio-quarkus-issue-12345/tree/main/mavenproject6

native image:
https://github.com/zipper01/reprocedure-for-quarkusio-quarkus-issue-12345/blob/main/mavenproject6/target/mavenproject6-1.0-jar-with-dependencies

running output with exception info:
https://github.com/zipper01/reprocedure-for-quarkusio-quarkus-issue-12345/blob/main/mavenproject6/target/error.txt

**Comment by geoand** [comment]
What you added does not appear to be a Quarkus project

**Comment by geoand** [comment]
Quarkus does extra work to make things like that happen - if you don't use Quarkus, you need to configure GraalVM yourself.

**Comment by zipper01** [comment]
Ok, thank you.

**Comment by geoand** [comment]
🙏🏼
