### ISSUE TITLE
Unable to Mock RestClient during tests

### ISSUE THREAD

**Issue by henrikengelbrink** [quarkusio/quarkus#12347]
**Describe the bug**
I've implemented an interface for the MP RestClient which communicates with an external API:

```kotlin
package io.goldmund.conversation.ws

import io.goldmund.conversation.ws.dto.WSGoogleBusinessAuthRequestDTO
import io.goldmund.conversation.ws.dto.WSGoogleBusinessAuthResponseDTO
import io.goldmund.conversation.ws.dto.WSGoogleBusinessRefreshRequestDTO
import io.goldmund.conversation.ws.dto.WSGoogleBusinessRefreshResponseDTO
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient
import javax.ws.rs.Consumes
import javax.ws.rs.POST
import javax.ws.rs.Path
import javax.ws.rs.Produces

@Path("/oauth2/v4")
@RegisterRestClient
@Produces("application/json")
@Consumes("application/json")
interface GoogleAuthService {

    @POST
    @Path("/token")
    fun requestAccessAndRefreshToken(
        payload: WSGoogleBusinessAuthRequestDTO
    ): WSGoogleBusinessAuthResponseDTO

    @POST
    @Path("/token")
    fun refreshToken(
        payload: WSGoogleBusinessRefreshRequestDTO
    ): WSGoogleBusinessRefreshResponseDTO
}
```
This interface is in the default `src/main/kotlin` folder.

For the tests, I wanted to have an mocked class for this which returns mocked DTO's:

```kotlin
package integration.controller.restclients

import io.goldmund.conversation.ws.GoogleAuthService
import io.goldmund.conversation.ws.dto.WSGoogleBusinessAuthRequestDTO
import io.goldmund.conversation.ws.dto.WSGoogleBusinessAuthResponseDTO
import io.goldmund.conversation.ws.dto.WSGoogleBusinessRefreshRequestDTO
import io.goldmund.conversation.ws.dto.WSGoogleBusinessRefreshResponseDTO
import io.quarkus.test.Mock
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient
import java.util.*
import javax.enterprise.context.ApplicationScoped


@Mock
@ApplicationScoped
@RegisterRestClient
class GoogleAuthServiceMock : GoogleAuthService {

    override fun requestAccessAndRefreshToken(payload: WSGoogleBusinessAuthRequestDTO): WSGoogleBusinessAuthResponseDTO {
        return WSGoogleBusinessAuthResponseDTO(
                accessToken = UUID.randomUUID().toString(),
                expiresIn = 86400,
                refreshToken = UUID.randomUUID().toString(),
                tokenType = UUID.randomUUID().toString(),
                idToken = UUID.randomUUID().toString(),
                scope = UUID.randomUUID().toString()
        )
    }

    override fun refreshToken(payload: WSGoogleBusinessRefreshRequestDTO): WSGoogleBusinessRefreshResponseDTO {
        return WSGoogleBusinessRefreshResponseDTO(
                accessToken = UUID.randomUUID().toString(),
                expiresIn = 86400,
                tokenType = UUID.randomUUID().toString(),
                idToken = UUID.randomUUID().toString(),
                scope = UUID.randomUUID().toString()
        )
    }
}
```

In the production code, I'm injecting the RestClient in one of my services (`GoogleService`) as following:
```kotlin
    @Inject
    @field: RestClient
    lateinit var googleAuthService: GoogleAuthService
```

I'm executing some integrations tests which are sending requests to the endpoints of my API where the `GoogleService` is actually calling the two functions of my RestClient (`interface GoogleAuthService`).

**Expected behavior**
I'm expecting that the injected interface for `GoogleAuthService` in `GoogleService` is not the real client but my mocked `GoogleAuthServiceMock` class so that I'm able to run tests without communicating to external services.

**Actual behavior**
The tests are failing with the following error message:
```sh
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.goldmund.conversation.ws.GoogleAuthService and qualifiers [@RestClient]
	- java member: io.goldmund.conversation.ws.GoogleService#googleAuthService
	- declared on CLASS bean [types=[io.goldmund.conversation.ws.GoogleService, java.lang.Object], qualifiers=[@Default, @Any], target=io.goldmund.conversation.ws.GoogleService]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:989)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:234)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:120)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:396)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.goldmund.conversation.ws.GoogleAuthService and qualifiers [@RestClient]
	- java member: io.goldmund.conversation.ws.GoogleService#googleAuthService
	- declared on CLASS bean [types=[io.goldmund.conversation.ws.GoogleService, java.lang.Object], qualifiers=[@Default, @Any], target=io.goldmund.conversation.ws.GoogleService]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:487)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:362)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:226)
	... 14 more

```

**Configuration**
```properties
io.hengel2810.cons.ws.GoogleAuthService/mp-rest/url=https://www.googleapis.com
io.hengel2810.cons.ws.GoogleAuthService/mp-rest/scope=javax.inject.Singleton
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Henriks-MBP-3 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
 - Output of `java -version`: 11
 - GraalVM version (if different from Java): -
 - Quarkus version or git rev: 1.6.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.1.1

**Comment by geoand** [comment]
Thanks for reporting.

Does it work if you change to:

```

@Mock
@ApplicationScoped
@RestClient
class GoogleAuthServiceMock : GoogleAuthService {

}
```

?

**Comment by henrikengelbrink** [comment]
@geoand Thank you for your answer, this is working. Changed `@RegisterRestClient` to `@RestClient`

**Comment by geoand** [comment]
Great 👌
