### ISSUE TITLE
ClassNotFoundException on primitive arguments with quarkus-test-security

### ISSUE THREAD

**Issue by antoniomacri** [quarkusio/quarkus#12413]
**Describe the bug**
If I include quarkus-test-security, a ClassNotFoundException is raised if there are test methods with arguments of primitive data types (for instance on a `@ParametrizedTest`). No need to actually use the `@TestSecurity` annotation.

**Expected behavior**
No exception is raised.

**Actual behavior**
```
java.lang.reflect.InvocationTargetException
	...
	at io.quarkus.test.junit.QuarkusTestExtension.beforeEach(QuarkusTestExtension.java:363)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:161)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:197)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	...
Caused by: java.lang.RuntimeException: Unable to setup @TestSecurity
	at io.quarkus.test.security.QuarkusSecurityTestExtension.beforeEach(QuarkusSecurityTestExtension.java:60)
	... 103 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: int
	at io.quarkus.test.security.QuarkusSecurityTestExtension.lambda$beforeEach$0(QuarkusSecurityTestExtension.java:34)
        ...
	at io.quarkus.test.security.QuarkusSecurityTestExtension.beforeEach(QuarkusSecurityTestExtension.java:36)
	... 103 more
Caused by: java.lang.ClassNotFoundException: int
        ...
	at io.quarkus.test.security.QuarkusSecurityTestExtension.lambda$beforeEach$0(QuarkusSecurityTestExtension.java:32)
	... 111 more
```

**To Reproduce**
1. Add quarkus-test-security dependency
    ```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-test-security</artifactId>
      <scope>test</scope>
    </dependency>
    ```
2. Create a ParametrizedTest with arguments of primitive data types:
    ```
    @QuarkusTest
    class QuarkusSecurityBugTest {
    
        @ParameterizedTest
        @ValueSource(ints = 1)
        public void replayTest(int number) {
        }
    }
    ```

**Environment (please complete the following information):**
 - Quarkus version: 1.8.1.Final

**Comment by sberyozkin** [comment]
CC @stuartwdouglas
