### ISSUE TITLE
Impossible to build a quarkus project since 1.7.0-Final

### ISSUE THREAD

**Issue by geniusit** [quarkusio/quarkus#12430]
Hello everyone,

using 
```xml
<dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-reactive-messaging-camel</artifactId>
    </dependency>
```
this maven dependency, it's no longer possible to build a project

**Expected behavior**
BUILD SUCCESSFULL

**Actual behavior**
```java
[INFO] [io.quarkus.arc.processor.IndexClassLookupUtils] Class for name: org.eclipse.microprofile.reactive.streams.operators.PublisherBuilder was not found in Jandex index. Please ensure the class is part of the index.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.190 s
[INFO] Finished at: 2020-09-30T20:14:46+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.7.0.Final:build (default) on project gpsng: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.IllegalArgumentException: Producer method return type not found in index: org.eclipse.microprofile.reactive.streams.operators.PublisherBuilder
[ERROR]         at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:176)
[ERROR]         at io.quarkus.arc.processor.Beans.createProducerMethod(Beans.java:186)
[ERROR]         at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:827)
[ERROR]         at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:208)
[ERROR]         at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:110)
[ERROR]         at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:361)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.lang.Thread.run(Thread.java:748)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

1. Follow the getting started guide
2. Add the BOM camel as explained [here](https://camel.apache.org/camel-quarkus/latest/user-guide/first-steps.html)
3. Add the smallrye-reactive-messaging-camel dependency
4. run mvn clean install

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Environment (please complete the following information):**
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\dev\apache-maven-3.6.3\bin\..
Java version: 1.8.0_251, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_251\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by mkouba** [comment]
I cannot reproduce the problem with `quarkus-universe-bom:1.8.1.Final` (i.e. go to https://code.quarkus.io/ and generate a project with `org.apache.camel.quarkus:camel-quarkus-smallrye-reactive-messaging`) . Could you try to upgrade your app?

CC @ppalaga

**Comment by ppalaga** [comment]
@jamesnetherton haven't we solved some reactive-messaging issues recently?

**Comment by jamesnetherton** [comment]
As @mkouba says, you should use the extension provided by the camel-quarkus project.

Although, there's a [bug](https://github.com/apache/camel-quarkus/issues/1851) that means you may want to wait until Quarkus 1.9.0 is released.

**Comment by geniusit** [comment]
Indeed, with https://code.quarkus.io I don't have any problem.
The reason is because I used this maven dependency :
```xml
<dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-reactive-messaging-camel</artifactId>
    </dependency>
```
As described : https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/camel/camel.html

Instead of the one used by [ttps://code.quarkus.io](https://code.quarkus.io)

I mean : 

```xml
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-smallrye-reactive-messaging</artifactId>
    </dependency>
```

As described here : https://camel.apache.org/camel-quarkus/latest/reference/extensions/smallrye-reactive-messaging.html
