### ISSUE TITLE
Gelf plugin improvement- Elastic server failure management

### ISSUE THREAD

**Issue by geniusit** [quarkusio/quarkus#12439]
Hello everyone,

I use the gelf plugin as described [here](https://quarkus.io/guides/centralized-log-management)

It works well! :) 

However sometimes I have network interruption and my ElasticSearch server become unavailable for a while.

I got this stack trace :

```java
LogManager error of type GENERIC_FAILURE: Port myserver.com:8135 not reachable
java.net.PortUnreachableException
        at sun.nio.ch.DatagramDispatcher.read0(Native Method)
        at sun.nio.ch.DatagramDispatcher.read(DatagramDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.DatagramChannelImpl.read(DatagramChannelImpl.java:556)
        at biz.paluch.logging.gelf.intern.sender.AbstractNioSender.isConnected(AbstractNioSender.java:78)
        at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendDatagrams(GelfUDPSender.java:54)
        at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendMessage(GelfUDPSender.java:47)
        at biz.paluch.logging.gelf.jul.GelfLogHandler.publish(GelfLogHandler.java:135)
        at biz.paluch.logging.gelf.jboss7.JBoss7GelfLogHandler.publish(JBoss7GelfLogHandler.java:108)
        at org.jboss.logmanager.handlers.DelayedHandler.publishToChildren(DelayedHandler.java:208)
        at org.jboss.logmanager.handlers.DelayedHandler.doPublish(DelayedHandler.java:49)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:316)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:748)
        at org.jboss.logmanager.Logger.log(Logger.java:706)
        at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
        at org.jboss.logging.Logger.logf(Logger.java:2445)
        at io.smallrye.reactive.messaging.i18n.ProviderLogging_$logger.initializingMediators(ProviderLogging_$logger.java:103)
        at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:160)
        at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:277)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:111)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:113)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:77)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:526)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:91)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29

LogManager error of type GENERIC_FAILURE: Port myserver.com:8135 not reachable
java.net.PortUnreachableException
        at sun.nio.ch.DatagramDispatcher.read0(Native Method)
        at sun.nio.ch.DatagramDispatcher.read(DatagramDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.DatagramChannelImpl.read(DatagramChannelImpl.java:556)
        at biz.paluch.logging.gelf.intern.sender.AbstractNioSender.isConnected(AbstractNioSender.java:78)
        at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendDatagrams(GelfUDPSender.java:54)
        at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendMessage(GelfUDPSender.java:47)
        at biz.paluch.logging.gelf.jul.GelfLogHandler.publish(GelfLogHandler.java:135)
        at biz.paluch.logging.gelf.jboss7.JBoss7GelfLogHandler.publish(JBoss7GelfLogHandler.java:108)
        at org.jboss.logmanager.handlers.DelayedHandler.publishToChildren(DelayedHandler.java:208)
        at org.jboss.logmanager.handlers.DelayedHandler.doPublish(DelayedHandler.java:49)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:316)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:748)
        at org.jboss.logmanager.Logger.log(Logger.java:706)
        at org.jboss.logmanager.Logger.log(Logger.java:719)
        at org.jboss.logging.JBossLogManagerLogger.doLog(JBossLogManagerLogger.java:42)
        at org.jboss.logging.Logger.warn(Logger.java:1247)
        at org.jboss.slf4j.JBossLoggerAdapter.log(JBossLoggerAdapter.java:72)
        at org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger.writeLog(LogContext.java:434)
        at org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger.warn(LogContext.java:282)
        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.handleServerDisconnect(NetworkClient.java:1030)
        at org.apache.kafka.clients.NetworkClient.processDisconnection(NetworkClient.java:769)
        at org.apache.kafka.clients.NetworkClient.handleDisconnections(NetworkClient.java:898)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:559)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:246)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:463)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1275)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1173)
        at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$pollRecords$6(KafkaReadStreamImpl.java:146)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
LogManager error of type GENERIC_FAILURE: Port myserver.com:8135 not reachable
java.net.PortUnreachableException
        at sun.nio.ch.DatagramDispatcher.read0(Native Method)
        at sun.nio.ch.DatagramDispatcher.read(DatagramDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.DatagramChannelImpl.read(DatagramChannelImpl.java:556)
        at biz.paluch.logging.gelf.intern.sender.AbstractNioSender.isConnected(AbstractNioSender.java:78)
        at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendDatagrams(GelfUDPSender.java:54)
        at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendMessage(GelfUDPSender.java:47)
        at biz.paluch.logging.gelf.jul.GelfLogHandler.publish(GelfLogHandler.java:135)
        at biz.paluch.logging.gelf.jboss7.JBoss7GelfLogHandler.publish(JBoss7GelfLogHandler.java:108)
        at org.jboss.logmanager.handlers.DelayedHandler.publishToChildren(DelayedHandler.java:208)
        at org.jboss.logmanager.handlers.DelayedHandler.doPublish(DelayedHandler.java:49)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:316)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:748)
        at org.jboss.logmanager.Logger.log(Logger.java:706)
        at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
        at org.jboss.logging.Logger.logf(Logger.java:2398)
        at io.smallrye.reactive.messaging.kafka.i18n.KafkaLogging_$logger.noGroupId(KafkaLogging_$logger.java:148)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector.lambda$getPublisherBuilder$0(KafkaConnector.java:115)
        at java.util.Optional.orElseGet(Optional.java:267)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector.getPublisherBuilder(KafkaConnector.java:113)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getPublisherBuilder(KafkaConnector_ClientProxy.zig:276)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createPublisherBuilder(ConfiguredChannelFactory.java:171)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$register$5(ConfiguredChannelFactory.java:149)
        at java.util.HashMap.forEach(HashMap.java:1289)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:149)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:125)
        at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory_ClientProxy.initialize(ConfiguredChannelFactory_ClientProxy.zig:217)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:158)
        at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:277)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:111)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:113)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:77)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:518)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:91)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
LogManager error of type GENERIC_FAILURE: Port myserver.com:8135 not reachable
java.net.PortUnreachableException
        at sun.nio.ch.DatagramDispatcher.read0(Native Method)
        at sun.nio.ch.DatagramDispatcher.read(DatagramDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.DatagramChannelImpl.read(DatagramChannelImpl.java:556)
        at biz.paluch.logging.gelf.intern.sender.AbstractNioSender.isConnected(AbstractNioSender.java:78)
        at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendDatagrams(GelfUDPSender.java:54)
        at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendMessage(GelfUDPSender.java:47)
        at biz.paluch.logging.gelf.jul.GelfLogHandler.publish(GelfLogHandler.java:135)
        at biz.paluch.logging.gelf.jboss7.JBoss7GelfLogHandler.publish(JBoss7GelfLogHandler.java:108)
        at org.jboss.logmanager.handlers.DelayedHandler.publishToChildren(DelayedHandler.java:208)
        at org.jboss.logmanager.handlers.DelayedHandler.doPublish(DelayedHandler.java:49)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:316)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:748)
        at org.jboss.logmanager.Logger.log(Logger.java:706)
        at org.jboss.logmanager.Logger.log(Logger.java:719)
        at org.jboss.logging.JBossLogManagerLogger.doLog(JBossLogManagerLogger.java:42)
        at org.jboss.logging.Logger.warn(Logger.java:1247)
        at org.jboss.slf4j.JBossLoggerAdapter.log(JBossLoggerAdapter.java:72)
        at org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger.writeLog(LogContext.java:434)
        at org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger.warn(LogContext.java:287)
        at org.apache.kafka.clients.NetworkClient.processDisconnection(NetworkClient.java:762)
        at org.apache.kafka.clients.NetworkClient.handleDisconnections(NetworkClient.java:898)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:559)
        at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:324)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239)
        at java.lang.Thread.run(Thread.java:748)
LogManager error of type GENERIC_FAILURE: Port myserver.com:8135 not reachable
java.net.PortUnreachableException
        at sun.nio.ch.DatagramDispatcher.read0(Native Method)
        at sun.nio.ch.DatagramDispatcher.read(DatagramDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.DatagramChannelImpl.read(DatagramChannelImpl.java:556)
        at biz.paluch.logging.gelf.intern.sender.AbstractNioSender.isConnected(AbstractNioSender.java:78)
        at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendDatagrams(GelfUDPSender.java:54)
        at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendMessage(GelfUDPSender.java:47)
        at biz.paluch.logging.gelf.jul.GelfLogHandler.publish(GelfLogHandler.java:135)
        at biz.paluch.logging.gelf.jboss7.JBoss7GelfLogHandler.publish(JBoss7GelfLogHandler.java:108)
        at org.jboss.logmanager.handlers.DelayedHandler.publishToChildren(DelayedHandler.java:208)
        at org.jboss.logmanager.handlers.DelayedHandler.doPublish(DelayedHandler.java:49)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:316)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:748)
        at org.jboss.logmanager.Logger.log(Logger.java:706)
        at org.jboss.logmanager.Logger.log(Logger.java:719)
        at org.jboss.logging.JBossLogManagerLogger.doLog(JBossLogManagerLogger.java:42)
        at org.jboss.logging.Logger.warn(Logger.java:1247)
        at org.jboss.slf4j.JBossLoggerAdapter.log(JBossLoggerAdapter.java:72)
        at org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger.writeLog(LogContext.java:434)
        at org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger.warn(LogContext.java:282)
        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.handleServerDisconnect(NetworkClient.java:1030)
        at org.apache.kafka.clients.NetworkClient.processDisconnection(NetworkClient.java:769)
        at org.apache.kafka.clients.NetworkClient.handleDisconnections(NetworkClient.java:898)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:559)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:246)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:463)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1275)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1243)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1173)
        at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$pollRecords$6(KafkaReadStreamImpl.java:146)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Even if the elasticsearch sever is back up, I need to manually restart my application because it has been crashed...

Is it possible to allow the quarkus application to auto restart or not to crash when I have this kind of network interruption ?

Thank you !

**Comment by loicmathieu** [comment]
@geniusit this is not the Elasticsearch server but the Graylog one that causes the issue (or Fluentd or Logstash depending which log aggregator you are using).

I'm suprised a transient issue on a log handler is not recoverable. What is the issue when the logging aggregator is back again ?

**Comment by geniusit** [comment]
@loicmathieu I use logstash. To me the problem is I need to kill the microservice and relaunch it... 
I don't exactly know what happens on my server that causes the stacktrace....
It happens sometimes (+- 1 time a week)

**Comment by loicmathieu** [comment]
OK, but as I ask, do you have the same stacktrace when logstash is back again or is it a different one ? I understand it occurs not very often so maybe wait for the next occurence and provides feedback when it happens.

A thread dump can also be of some help to understand what's going on. But be sure that Logstash is back when you take it.

**Comment by geniusit** [comment]
I don't have any stacktrace when logstash i back again because the microservice has already crashed.
I just need to restart it.

**Comment by loicmathieu** [comment]
So you mean that when Logstash is not available, your application crash and never recover from it ?

@dmlloyd can an error on the logmanager crash the application ? Should it be resilient to a log handler failure ?

**Comment by geniusit** [comment]
yes that's it!

**Comment by dmlloyd** [comment]
> So you mean that when Logstash is not available, your application crash and never recover from it ?
> 
> @dmlloyd can an error on the logmanager crash the application ? Should it be resilient to a log handler failure ?

Not that I know of, but there's always a chance that there is a bug that we don't know about.  `ExtHandler` is supposed to trap all exceptions - but perhaps `DelayedHandler` doesn't have the same level of protections for some reason.  I can have a look at it.

**Comment by loicmathieu** [comment]
@dmlloyd if you can have a look this could be great, thanks!

@geniusit I may have found why it broke your application, it appears that the stacktrace comes from Kafka, maybe they didn't catch the case where the logger throw an error. This seems to be Vert.x kafka streams so maybe something could also be done at this level.

```
        at org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger.writeLog(LogContext.java:434)
        at org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger.warn(LogContext.java:282)
        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.handleServerDisconnect(NetworkClient.java:1030)
        at org.apache.kafka.clients.NetworkClient.processDisconnection(NetworkClient.java:769)
        at org.apache.kafka.clients.NetworkClient.handleDisconnections(NetworkClient.java:898)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:559)
[...]
        at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$pollRecords$6(KafkaReadStreamImpl.java:146)
```
@cescoffier a failure to log inside the Kafka client seems to crash the application, maybe something could be done at Vert.x side to recover from it ?

**Comment by dmlloyd** [comment]
It appears that there are several things that should be fixed.  The Gelf handler should be trapping exceptions and using the error manager, and the delayed handler should also be doing the same.  Really the `ExtHandler` implementation should have stronger protections in several places.  I'll make the requisite upstream project changes to `ExtHandler` and friends but the Gelf side is someplace else (the `logstash-gelf` artifact).

**Comment by loicmathieu** [comment]
OK, I can send a PR to the upstream `logstash-gelf` library if you want, I already contributed to it. Ping me when you change the `ExHandler` so I can see the kind of changes that needs to be done.

**Comment by dmlloyd** [comment]
OK will do.  It's going to amount to `try/catch` and calling `reportError` in case of a problem.  The patch is almost ready though...

**Comment by dmlloyd** [comment]
OK commit https://github.com/dmlloyd/jboss-logmanager-embedded/commit/977034710784a46ef88dae8e9a2cd07003a86161 should fix the issue.

**Comment by loicmathieu** [comment]
I check the `loggin-glef` code and it seems to have `try/catch` in a lot of places so it should be safe.

**Comment by dmlloyd** [comment]
It apparently doesn't have one at `biz.paluch.logging.gelf.jul.GelfLogHandler.publish(GelfLogHandler.java:135)`. 🙂

**Comment by loicmathieu** [comment]
@dmlloyd yes, it have a try/catch exception around this line: https://github.com/mp911de/logstash-gelf/blob/b4f6617ff30d59d8180c151ed3ce68b6524a2e02/src/main/java/biz/paluch/logging/gelf/jul/GelfLogHandler.java#L128

So maybe your fix will be enought

**Comment by dmlloyd** [comment]
Hmm I see.  Then unfortunately I think I must conclude that the application isn't crashing because of these errors - and, adding the additional checks on the LogManager side will not improve matters as the exception never propagated to Kafka.  Maybe next time I will read the output a bit more carefully. :-)

Something else must be failing that is not being reported.  It might be helpful to enable console logging if it isn't already enabled.

**Comment by geniusit** [comment]
I no longer had this error since I switch to docker
