### ISSUE TITLE
Native builds with JNI failing with java.lang.UnsatisfiedLinkError:

### ISSUE THREAD

**Issue by OmriShiv** [quarkusio/quarkus#12469]
**Describe the bug**
When trying to build a project with Quarkus (whether using the gradle quarkusBuild or using graal directly), the build works; however, when trying to run the project a `java.lang.UnsatisfiedLinkError` occurs. Using a minimal test with just Onnx in a single Class, the native build works. 

**Expected behavior**
I expect the application not to fail when this line of code is called. 

**Actual behavior**
`java.lang.UnsatisfiedLinkError` occurs

**To Reproduce**
Steps to reproduce and a sample are available: https://github.com/OmriShiv/onnx-quarkus-native-repro

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.native.additional-build-args=-H:ConfigurationFileDirectories=.
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk 11.0.8 2020-07-14 LTS
OpenJDK Runtime Environment Zulu11.41+23-CA (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.41+23-CA (build 11.0.8+10-LTS, mixed mode)
 - GraalVM version (if different from Java): Using both the `quay.io/quarkus/ubi-quarkus-native-image:20.2.0-java11` image with Quarkus and `graalvm-ce-java11-20.2.0`
 - Quarkus version or git rev: 1.8.1.Final (But also found in 1.8.0 and 1.7.3)
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
------------------------------------------------------------
Gradle 6.4.1
------------------------------------------------------------

Build time:   2020-05-15 19:43:40 UTC
Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.8 (Azul Systems, Inc. 11.0.8+10-LTS)
OS:           Mac OS X 10.15.6 x86_64

**Comment by OmriShiv** [comment]
Maybe related to #12472 ?

**Comment by diggernet** [comment]
I've just run into this UnsatisfiedLinkError with a JNI library.  While searching for a solution, I found this page:
https://quarkus.io/guides/class-loading-reference
In particular, this part:

"When running a production application everything is loaded in the system ClassLoader, so it is a completely flat class path. [...] For all other use cases (e.g. tests, dev mode, and building the application) Quarkus uses the class loading architecture outlined here."

I found that running my application from the jar file avoids the error.  It appears that in dev mode, the JNI lib is getting loaded by a different classloader than the one the calling code is in.

**Comment by geoand** [comment]
Is this still an issue with the Quarkus 3.22+?

**Comment by col-panic** [comment]
I'm currently trying to get jserialcomm up and running with quarkus 3.31.3 https://github.com/Fazecast/jSerialComm/issues/438 - all the research brought me here ;)

**Comment by col-panic** [comment]
Now that is funny, the stacktrace says `java.lang.NoClassDefFoundError: com/fazecast/jSerialComm/SerialPort` while its coming from there :) 

<img width="993" height="518" alt="Image" src="https://github.com/user-attachments/assets/332cafef-6202-4fd6-8495-9e9d30eb6d57" />

`application.properties => quarkus.native.additional-build-args=--initialize-at-run-time=com.fazecast.jSerialComm.SerialPort`

Build is
`./mvnw clean compile package -P native -Dquarkus.native.container-build=false`

Adding `@RegisterForReflection(targets = { SerialPort.class })` does not change the stacktrace

**Comment by zakkak** [comment]
> Now that is funny, the stacktrace says `java.lang.NoClassDefFoundError: com/fazecast/jSerialComm/SerialPort` while its coming from there :)

That's indeed confusing, looking at the stacktrace though we see that while loading `SerialPort` the class initializer tries to load some native library (that needs to be explicitly registered when compiling to native, see https://github.com/quarkusio/quarkus/blob/d886f739ece95895478c74eaa1e270d05405a1d7/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/graal/Brotli4jFeature.java#L34-L37 for an example).

When doing so, [GraalVM looks up the class in its `JNIReflectionDictionary` and since the class is not present it throws a `NoClassDefFoundError`](https://github.com/oracle/graal/blob/eab069f7fc53f281944a15702e578c0b7556ee19/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jni/functions/JNIFunctions.java#L364-L367). 

Properly registering the native library and any potential JNI methods used by the application should resolve the issue.

**Comment by col-panic** [comment]
Thanks @zakkak for your info!

I checked your code, but I don't see where the respective Feature becomes connected to the native building process (no annotation, or reference in pom.xml), if i simply implement it (adding dependency `org.graalvm.sdk:nativeimage` it seems not to be considered during build)

Is the `RuntimeResourceAccess.addResource` different to the `@RegisterResources` [annotation](https://quarkus.io/guides/writing-native-applications-tips#registering-resource-bundles-and-resource-files)?

I tried another approach, maybe you Could you enlighten me, on why it doesn't work:

I copied the required native library to the external filesystem, and started the native image appending 
`-DjSerialComm.library.path=/my/liblocation/` as I assumed, that due to 
`quarkus.native.additional-build-args=--initialize-at-run-time=com.fazecast.jSerialComm.SerialPort`
the library might be loaded from the OS. I can even see OS X asking me if I want to grant access to the local jnilib file - and yet the console log stays the same 🤷

**Comment by col-panic** [comment]
When modifying to
`quarkus.native.additional-build-args=--initialize-at-run-time=com.fazecast.jSerialComm.SerialPort -H:IncludeResources=".*jnilib$"`

I receive

```
2026-02-16 15:18:10,544 ERROR [io.quarkus.runtime.Application] (main) Failed to start application: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:116)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:79)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:50)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:143)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: com.fazecast.jSerialComm.SerialPort.getCommPortsNative()[Lcom/fazecast/jSerialComm/SerialPort; [symbol: Java_com_fazecast_jSerialComm_SerialPort_getCommPortsNative or Java_com_fazecast_jSerialComm_SerialPort_getCommPortsNative__]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:41)
        at com.fazecast.jSerialComm.SerialPort.getCommPortsNative(Native Method)
        at com.fazecast.jSerialComm.SerialPort.getCommPorts(SerialPort.java:429)
```

so at least the class construct of SerialPort seems to have worked - yet calling the `getCommPorts()` method fails.

**Comment by zakkak** [comment]
Note that you can alternatively register the resource using

```java
NativeImageResourcePatternsBuildItem.builder().includeGlob("**/*jnilib").build()
```

Now that the library is available you also need to register all potential JNI accesses using `JniRuntimeAccessBuildItem`, `JniRuntimeAccessFieldBuildItem`, and `JniRuntimeAccessMethodBuildItem`.

> I checked your code, but I don't see where the respective Feature becomes connected to the native building process (no annotation, or reference in pom.xml), if i simply implement it (adding dependency org.graalvm.sdk:nativeimage it seems not to be considered during build)

You need to create a `NativeImageFeatureBuildItem` as well for Quarkus to enable the feature.

To do all the above you will need to [create a Quarkus extension](https://quarkus.io/guides/writing-extensions). See https://quarkus.io/guides/all-builditems for all the available build items.

> Is the `RuntimeResourceAccess.addResource` different to the `@RegisterResources` [annotation](https://quarkus.io/guides/writing-native-applications-tips#registering-resource-bundles-and-resource-files)?

No, the latter is just an abstraction so that people don't have to right their own Feature or configuration files to register resources.

HTH

**Comment by col-panic** [comment]
@zakkak thanks a lot again - to subsume/check my understanding:

The library as file can be added alternatively via the following means:
* `@RegisterResources(globs = { "**/*jnilib" })` **or**
* `application.properties` -> `quarkus.native.additional-build-args=-H:IncludeResources=".*jnilib$"` **or**
* `NativeImageResourcePatternsBuildItem.builder().includeGlob("**/*jnilib").build()` (this solution requires to write a Quarkus Extension)

Registering all potential JNI accesses, however, can only be included by writing a Quarkus extension, as for the `JniRuntimeAccessBuildItem`, `JniRuntimeAccessFieldBuildItem` and `JniRuntimeAccessMethodBuildItem` exist no abstraction that enable me to go without. (If this is true, this might be a case to introduce such an extension?)

**Comment by zakkak** [comment]
> [@zakkak](https://github.com/zakkak) thanks a lot again - to subsume/check my understanding:
> 
> The library as file can be added alternatively via the following means:
> 
>     * `@RegisterResources(globs = { "**/*jnilib" })` **or**
> 
>     * `application.properties` -> `quarkus.native.additional-build-args=-H:IncludeResources=".*jnilib$"` **or**
> still
>     * `NativeImageResourcePatternsBuildItem.builder().includeGlob("**/*jnilib").build()` (this solution requires to write a Quarkus Extension)
> 

Correct

> Registering all potential JNI accesses, however, can only be included by writing a Quarkus extension, as for the `JniRuntimeAccessBuildItem`, `JniRuntimeAccessFieldBuildItem` and `JniRuntimeAccessMethodBuildItem` exist no abstraction that enable me to go without. 

There is also the option to manually craft a [`jni-config.json`](https://www.graalvm.org/jdk21/reference-manual/native-image/metadata/#jni-metadata-in-json) or [`reachability-metadata.json`](https://www.graalvm.org/latest/reference-manual/native-image/metadata/#specifying-metadata-with-json) file. Note that you can register resources this way as well.

> (If this is true, this might be a case to introduce such an extension?)

By extension do you mean something like `@RegisterJNI`?

IMHO your use case (adding support for https://github.com/Fazecast/jSerialComm to Quarkus) is better handled by a Quarkus extension. Nevertheless, if you still think there is value in making JNI registrations easier, feel free to open a feature request for the GraalVM team to review.

**Comment by zakkak** [comment]
I am closing this due to lack of feedback from the reporter.
