### ISSUE TITLE
Quarkus does not start/respond when running inside an Azure Function on Java 11

### ISSUE THREAD

**Issue by cx-lmp** [quarkusio/quarkus#12551]
I've generated a Quarkus Azure Functions project using the provided Maven archetype (following this guide: https://quarkus.io/guides/azure-functions-http). Everything is stock in the generated project, except I've updated the Azure Functions Maven plugin to 1.9.0 and set the following properties:
```
<java.version>11</java.version>
<maven.compiler.parameters>true</maven.compiler.parameters>
<maven.compiler.source>${java.version}</maven.compiler.source>
<maven.compiler.target>${java.version}</maven.compiler.target>
```
In addition, I've added a `runtime` block to the configuration of Azure Functions Maven plugin:
```
<runtime>
  <os>linux</os>
  <javaVersion>11</javaVersion>
</runtime>
```
As recommended by Microsoft, I've installed a Zulu build of OpenJDK, specifically "Zulu: 11.41.23" (I think that's based on OpenJDK 11.0.8+10), and set `JAVA_HOME` to the location of this JDK.

When executing `mvn install azure-functions:run`, Azure Functions starts OK and locates the function. I can access `locahost:7071` just fine and observe that the Azure Functions runtime environment is up and running. However, when trying to access `localhost:7071/api/hello` (which is an endpoint that Quarkus should respond to), I never get a response. The same behaviour can be observed if Azure Functions is started using the `func` tool. Adding the `--verbose` flag shows the request coming in, but never returning.

**Expected behavior**
I would expect to Quarkus to return immediatly with "hello jaxrs" or at least with an error message if something gone awry during startup or a 404 if the endpoint does not exist.

**To Reproduce**
Checkout https://github.com/cx-lmp/azure-functins-quarkus-java-11 for configuration and source code. As mentioned, it's basically generated by the Maven archetype with a minimal set of changes. 
Build the project and run Azure Functions with:
```
mvn install azure-functions:run
```
Visit `localhost:7071/api/hello` and observe that a response is never returned.

**Environment (please complete the following information):**
 - OS: Windows 10 version 2004
 - Terminal: Powershell Core 7.0.3
 - Quarkus version: 1.8.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3
 - Azure Functions Core Tools (3.0.2912 Commit hash: bfcbbe48ed6fdacdf9b309261ecc8093df3b83f2)
 - Function Runtime Version: 3.0.14287.0

Hope I've provided you with enough information. Thanks!

**Comment by geoand** [comment]
cc @patriot1burke

**Comment by cx-lmp** [comment]
FWIW, I see the same behavior if the compiler is set to build for Java 1.8 and Azure Functions runtime is set to Java 1.8, but `JAVA_HOME` is set to an installation of JDK 11. 

I'm aware that Java 11 is in preview for Azure Functions, but I was able to create a working function based on Azure Functions' own Maven archetype. I was also able to modify that "vanilla" function to use the Micronaut framework (using https://micronaut-projects.github.io/micronaut-azure/2.0.1/guide/index.html as a guide). That led me to believe there might be some issue with Quarkus.

**Comment by szirbucz** [comment]
I dived a bit deeper and found that there is an error at the initialization of the ApplicationImpl
```
[2020-11-08T08:18:40.648Z] java.lang.ExceptionInInitializerError
[2020-11-08T08:18:40.648Z] 	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:57)
[2020-11-08T08:18:40.648Z] 	at java.base/java.lang.Class.forName0(Native Method)
[2020-11-08T08:18:40.648Z] 	at java.base/java.lang.Class.forName(Class.java:315)
[2020-11-08T08:18:40.648Z] 	at eu.wecan.quarkus.MyFunction.<clinit>(MyFunction.java:31)
[2020-11-08T08:18:40.648Z] 	at java.base/java.lang.Class.forName0(Native Method)
For detailed output, run func with --verbose flag.
[2020-11-08T08:18:40.648Z] 	at java.base/java.lang.Class.forName(Class.java:398)
[2020-11-08T08:18:40.648Z] 	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.getContainingClass(EnhancedJavaMethodExecutorImpl.java:63)
[2020-11-08T08:18:40.648Z] 	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.<init>(EnhancedJavaMethodExecutorImpl.java:22)
[2020-11-08T08:18:40.648Z] 	at com.microsoft.azure.functions.worker.broker.FactoryJavaMethodExecutor.getJavaMethodExecutor(FactoryJavaMethodExecutor.java:20)
[2020-11-08T08:18:40.648Z] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.loadMethod(JavaFunctionBroker.java:38)
[2020-11-08T08:18:40.648Z] 	at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:27)
[2020-11-08T08:18:40.648Z] 	at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:9)
[2020-11-08T08:18:40.649Z] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2020-11-08T08:18:40.649Z] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2020-11-08T08:18:40.649Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2020-11-08T08:18:40.649Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2020-11-08T08:18:40.649Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2020-11-08T08:18:40.649Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2020-11-08T08:18:40.649Z] 	at java.base/java.lang.Thread.run(Thread.java:834)
[2020-11-08T08:18:40.649Z] Caused by: java.lang.IllegalArgumentException: SRCFG00013: No Converter registered for class io.quarkus.runtime.configuration.MemorySize
[2020-11-08T08:18:40.649Z] 	at io.smallrye.config.SmallRyeConfig.lambda$getConverter$2(SmallRyeConfig.java:289)
[2020-11-08T08:18:40.649Z] 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
[2020-11-08T08:18:40.649Z] 	at io.smallrye.config.SmallRyeConfig.getConverter(SmallRyeConfig.java:286)
[2020-11-08T08:18:40.649Z] 	at io.quarkus.runtime.generated.Config.<clinit>(Config.zig:415)
[2020-11-08T08:18:40.649Z] 	... 19 more
```
It is called from the static initializer of `io.quarkus.azure.functions.resteasy.runtime.BaseFunction`
https://github.com/quarkusio/quarkus/blob/02e0ed5772f471ae901996f27e705b203e2d4d94/extensions/azure-functions-http/runtime/src/main/java/io/quarkus/azure/functions/resteasy/runtime/BaseFunction.java#L47

I'm a bit stuck with the debugging, since I'm just learning quarkus since yesterday and have no idea how to access these .zig generated sources.

**Comment by geoand** [comment]
Does the same issue occur if you use the same application without the Azure Functions functionality?

**Comment by cx-lmp** [comment]
At least in my case, this doesn't happen when the application is started outside of Azure Functions. I think that's pretty natural, though, because I don't think the Azure Functions specific code is accessed in that case.

**Comment by gsmet** [comment]
> Caused by: java.lang.IllegalArgumentException: SRCFG00013: No Converter registered for class io.quarkus.runtime.configuration.MemorySize

Are you sure all your artifacts are consistent and you don't have old artifacts around?

It looks a lot like a problem you would have with mixed versions.

**Comment by TsuyoshiUshio** [comment]
I also debug with Java Language Worker on the Azure Functions, however, it also happens inside of the ApplicationImpl startup.  The same observation as @szirbucz . Also I can't find the source ApplicationImpl. Is it auto-generated class?

**Comment by patriot1burke** [comment]
Quarkus is initialized by a static block and Azure Functions java worker no longer wraps the classloader of the function class with TCL.  At least that's what I think it is.  I should have a PR early next week to support the new azure functions runtimes.
