### ISSUE TITLE
Error when trying to Test RestClient

### ISSUE THREAD

**Issue by FcoJavierSainz** [quarkusio/quarkus#12585]
**Describe the bug**
When the annotated rest client is tried to be injected throws an exception `java.lang.IllegalArgumentException: RESTEASY003720: path param org has not been provided by the parameter map`, it happens with `@InjectMock` or without Mock using MockServer for the stubs for example

**Expected behavior**
Create the RestClienmt without trying to map the path parameter since the begining

**Actual behavior**
The test can not be executed

**To Reproduce**

```java
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.Path;
import javax.ws.rs.QueryParam;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;
import org.jboss.resteasy.annotations.jaxrs.PathParam;

@Path("/orgs")
@RegisterRestClient(configKey = "github-organization-api")
public interface GithubRepositoryRestClient {

  @GET
  @Path("/{org}/repos")
  OrganizationRepositoriesResponse getByOrg(@PathParam String org, @HeaderParam("Authorization") String token,
                                            @HeaderParam("Accept") String preview,
                                            @QueryParam("per_page") int pageSize, @QueryParam("page") int page);
}
```
```java
@ResponseObject
public interface OrganizationRepositoriesResponse {
  @Body
  List<Repository> body();

  @LinkHeaderParam(rel = "next")
  String next();
}
```

```java

@ApplicationScoped
public class RestGithubRepository implements GithubRepository {

  public static final String PREVIEW = "application/vnd.github.mercy-preview+json";
  @RestClient
  @Inject
  private GithubRepositoryRestClient restClient;
  private final CommandCenterProperties properties;

  public RestGithubRepository(CommandCenterProperties properties) {
    this.properties = properties;
  }

  @Override
  public List<Repository> getOrgRepositories() {
    int page = 1;
    var response = getRepositoriesPage(page);
    var repositories = response.body();

    while (response.next() != null) {
      page++;
      response = getRepositoriesPage(page);
      repositories.addAll(response.body());
    }

    return repositories;

  }

  private OrganizationRepositoriesResponse getRepositoriesPage(int page) {
    return restClient
        .getByOrg(properties.getGithub().getOrganization(), "token " + properties.getGithub().getToken(),
            PREVIEW, 100, page);
  }
}
```

```java
@QuarkusTest
public class RestGithubRepositoryTest {

  @InjectMock
  @RestClient
  GithubRepositoryRestClient ghClient;

  @Inject
  RestGithubRepository restGithubRepository;

  private void setHttpResponseSetup() {
    //mock response
  }

  @Test
  public void testGetOrgRepositories() {
    List<Repository> repositories = restGithubRepository.getOrgRepositories();
    assertThat(repositories.size()).isEqualTo(2);
  }

}
```
1. 
2. 
3. 

**Configuration**
```properties
command-center.github.token=${GH_TOKEN}
# Add your application.properties here, if applicable.
github-organization-api/mp-rest/url=https://api.github.mydomain.com
github-organization-api/mp-rest/scope=javax.inject.Singleton

#Test
%test.command-center.github.token=dummy
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
Stacktrace
```
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance

	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:641)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:618)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:72)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:77)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:333)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:280)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:77)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:262)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:256)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:255)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:29)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:107)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.instance(RunningQuarkusApplicationImpl.java:80)
	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:630)
	... 59 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.instance(RunningQuarkusApplicationImpl.java:78)
	... 60 more
Caused by: java.lang.RuntimeException: Error injecting com.ibm.sets.command.center.port.adapter.github.GithubRepositoryRestClient com.ibm.sets.command.center.port.adapter.github.RestGithubRepositoryTest.ghClient
	at com.ibm.sets.command.center.port.adapter.github.RestGithubRepositoryTest_Bean.create(RestGithubRepositoryTest_Bean.zig:156)
	at com.ibm.sets.command.center.port.adapter.github.RestGithubRepositoryTest_Bean.get(RestGithubRepositoryTest_Bean.zig:237)
	at com.ibm.sets.command.center.port.adapter.github.RestGithubRepositoryTest_Bean.get(RestGithubRepositoryTest_Bean.zig:272)
	at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:210)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
	... 65 more
Caused by: org.eclipse.microprofile.rest.client.RestClientDefinitionException: Parameter names don't match variable names on interface com.ibm.sets.command.center.port.adapter.github.GithubRepositoryRestClient::getByOrg
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.verifyInterface(RestClientBuilderImpl.java:428)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.build(RestClientBuilderImpl.java:173)
	at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:65)
	at com.ibm.sets.command.center.port.adapter.github.GithubRepositoryRestClient_4077d94122c737ecbeec9d87c5fbe720670d0370_Synthetic_Bean.create(GithubRepositoryRestClient_4077d94122c737ecbeec9d87c5fbe720670d0370_Synthetic_Bean.zig:188)
	at com.ibm.sets.command.center.port.adapter.github.GithubRepositoryRestClient_4077d94122c737ecbeec9d87c5fbe720670d0370_Synthetic_Bean.create(GithubRepositoryRestClient_4077d94122c737ecbeec9d87c5fbe720670d0370_Synthetic_Bean.zig:204)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at com.ibm.sets.command.center.port.adapter.github.GithubRepositoryRestClient_4077d94122c737ecbeec9d87c5fbe720670d0370_Synthetic_Bean.get(GithubRepositoryRestClient_4077d94122c737ecbeec9d87c5fbe720670d0370_Synthetic_Bean.zig:236)
	at com.ibm.sets.command.center.port.adapter.github.GithubRepositoryRestClient_4077d94122c737ecbeec9d87c5fbe720670d0370_Synthetic_Bean.get(GithubRepositoryRestClient_4077d94122c737ecbeec9d87c5fbe720670d0370_Synthetic_Bean.zig:252)
	at com.ibm.sets.command.center.port.adapter.github.RestGithubRepositoryTest_Bean.create(RestGithubRepositoryTest_Bean.zig:139)
	... 70 more
Caused by: java.lang.IllegalArgumentException: RESTEASY003720: path param org has not been provided by the parameter map
	at org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.replaceParameter(ResteasyUriBuilderImpl.java:637)
	at org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.buildCharSequence(ResteasyUriBuilderImpl.java:560)
	at org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.buildString(ResteasyUriBuilderImpl.java:529)
	at org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.buildFromValues(ResteasyUriBuilderImpl.java:759)
	at org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.build(ResteasyUriBuilderImpl.java:751)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.verifyInterface(RestClientBuilderImpl.java:426)
	... 84 more
```

**Comment by jclingan** [comment]
See issue #12347. Annotate the Rest Client with @ApplicationScoped:
```
@Path("/orgs")
@RegisterRestClient(configKey = "github-organization-api")
@ApplicationScoped
public interface GithubRepositoryRestClient {
```

[This](https://youtu.be/OCPFdpvL1Q0?t=2134) explains why.

Hope this helps!

**Comment by FcoJavierSainz** [comment]
Hi @jclingan thanks for responding, I am still seeing the same error

```
Caused by: java.lang.IllegalArgumentException: RESTEASY003720: path param repo has not been provided by the parameter map
	at org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.replaceParameter(ResteasyUriBuilderImpl.java:637)
	at org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.buildCharSequence(ResteasyUriBuilderImpl.java:560)
	at org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.buildString(ResteasyUriBuilderImpl.java:529)
	at org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.buildFromValues(ResteasyUriBuilderImpl.java:759)
	at org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.build(ResteasyUriBuilderImpl.java:751)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.verifyInterface(RestClientBuilderImpl.java:426)
	... 84 more
```
Rest Client

```java
@Path("/orgs")
@RegisterRestClient(configKey = "github-organization-api")
@ApplicationScoped
public interface GithubRepositoryRestClient {

  @GET
  @Path("/{org}/repos")
  OrganizationRepositoriesResponse getByOrg(@PathParam String org, @HeaderParam("Authorization") String token,
      @HeaderParam("Accept") String preview,
      @QueryParam("per_page") int pageSize, @QueryParam("page") int page);

  @GET
  @Path("/repos/{repo}/contents/{path}")
  GhFileContent getFileContent(@PathParam String repo, @PathParam String path, @HeaderParam("Authorization") String token);
}
```

Test class
```java
@QuarkusTest
public class RestGithubRepositoryTest {

  @InjectMock
  @RestClient
  GithubRepositoryRestClient ghClient;

  @Inject
  RestGithubRepository restGithubRepository;

  @Test
  public void testGetOrgRepositories() {
    List<Repository> repositories = restGithubRepository.getOrgRepositories();
    assertThat(repositories.size()).isEqualTo(2);
  }

}

```

**Comment by gsmet** [comment]
Maybe it's a dumb question but are you compiling with `-parameters`?

**Comment by FcoJavierSainz** [comment]
Hi, That error was thrown when using IntelliJ, When I added `@ApplicationScoped` the same problem from this issue https://github.com/quarkusio/quarkus/issues/9630 happened. Not sure if we can keep this issue to try to fix it.

**Comment by gastaldi** [comment]
Closing for now as it seems to have been resolved

**Comment by FcoJavierSainz** [comment]
I am still confused if this is expected or is a workaround of a bug

**Comment by Stalyn-1994** [comment]
Hi FcoJavierSainz,you try to change dependency 
import org.jboss.resteasy.annotations.jaxrs.PathParam;    by
import javax.ws.rs.PathParam;
in my case ,this worked for me
