### ISSUE TITLE
Documentation does not mention `quarkus.package.type=mutable-jar`

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#12601]
**Describe the bug**
https://quarkus.io/guides/all-config#quarkus-core_quarkus.package.type does not list `mutable-jar` as an option. I thought it's effectively the same as `fast-jar` but I found that live-reload wasn't working with `fast-jar` since I missed a file:

```
Exception in thread "main" java.nio.file.NoSuchFileException: /work/lib/deployment/deployment-class-path.dat
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
	at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:39)
	at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:34)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:24)
```

**Expected behavior**
Please list `mutable-jar` as a valid option.

**Comment by geoand** [comment]
Actually, this isn't something we expect end users to use under normal circumstances.

It is documented at https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/maven-tooling.adoc#remote-development-mode

**Comment by rvansa** [comment]
Yes, that's where I found about the option :) However not listing a 'supported' option in reference is confusing - it appears as if the option is deprecated and the documentation you've linked is out-of-date.

**Comment by geoand** [comment]
I'll @stuartwdouglas decide what he wants to do here as he is the author of mutable-jar

**Comment by machi1990** [comment]
If we turn [the configuration](https://github.com/quarkusio/quarkus/blob/63ff7236c4e760206c62432d985be1868ee2685a/core/deployment/src/main/java/io/quarkus/deployment/pkg/PackageConfig.java#L30) into an enum, possible values will be automatically generated in the documentation much like https://quarkus.io/guides/all-config#quarkus-scheduler_quarkus.scheduler.cron-type

**Comment by geoand** [comment]
Yeah, we could probably do that

**Comment by stuartwdouglas** [comment]
The original intention was for it to me extensible, which is why it is not an enum, but I don't know how well that would work in practice.
