### ISSUE TITLE
EntityManager is no more injected when migrated from Quarkus 1.7.* to Quarkus 1.8.1

### ISSUE THREAD

**Issue by dinabogdan** [quarkusio/quarkus#12626]
I've migrated the application from Quarkus version 1.7.1.Final to Quarkus version 1.8.1.Final, without changing anything into code.

With the old version, I run the application by using `mvn compile quarkus:dev -DSKIP_PARSE_PERSISTENCE_XML` and everything worked fine. Now, running the same command I'm receiving an error regarding the initialization of EntityManager.

**Expected behavior**
Just to work as before.

**Actual behavior**
I'm receiving the following stack trace:

```
2020-10-09 12:44:04,506 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:304)
        ... 15 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error injecting com.ing.diba.jeeop.cert_proxy.acme.database.NonceRepository com.ing.diba.jeeop.cert_proxy.acme.AcmeProtocolFeature.nonceRepository
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:519)
        at io.quarkus.deployment.steps.UndertowBuildStep$build-649634386.deploy_0(UndertowBuildStep$build-649634386.zig:361)
        at io.quarkus.deployment.steps.UndertowBuildStep$build-649634386.deploy(UndertowBuildStep$build-649634386.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:284)
        ... 15 more
Caused by: java.lang.RuntimeException: Error injecting com.ing.diba.jeeop.cert_proxy.acme.database.NonceRepository com.ing.diba.jeeop.cert_proxy.acme.AcmeProtocolFeature.nonceRepository
        at com.ing.diba.jeeop.cert_proxy.acme.AcmeProtocolFeature_Bean.create(AcmeProtocolFeature_Bean.zig:260)
        at com.ing.diba.jeeop.cert_proxy.acme.AcmeProtocolFeature_Bean.create(AcmeProtocolFeature_Bean.zig:327)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at com.ing.diba.jeeop.cert_proxy.acme.AcmeProtocolFeature_Bean.get(AcmeProtocolFeature_Bean.zig:359)
        at com.ing.diba.jeeop.cert_proxy.acme.AcmeProtocolFeature_Bean.get(AcmeProtocolFeature_Bean.zig:375)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:408)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:421)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:249)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:246)
        at io.quarkus.arc.runtime.ArcRecorder$2$1.create(ArcRecorder.java:84)
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:39)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.injectedInstance(ResteasyProviderFactoryImpl.java:1398)
        at org.jboss.resteasy.core.providerfactory.CommonProviders.addDynamicFeature(CommonProviders.java:313)
        at org.jboss.resteasy.core.providerfactory.CommonProviders.processProviderContracts(CommonProviders.java:125)
        at org.jboss.resteasy.core.providerfactory.ClientHelper.processProviderContracts(ClientHelper.java:104)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.processProviderContracts(ResteasyProviderFactoryImpl.java:840)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerProvider(ResteasyProviderFactoryImpl.java:828)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerProvider(ResteasyProviderFactoryImpl.java:815)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerProvider(ResteasyProviderFactoryImpl.java:740)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.registerProvider(ResteasyDeploymentImpl.java:738)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.registration(ResteasyDeploymentImpl.java:456)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:162)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:118)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:144)
        at org.jboss.resteasy.plugins.server.servlet.FilterDispatcher.init(FilterDispatcher.java:47)
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:112)
        at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:80)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:593)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:558)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$10$1.call(UndertowDeploymentRecorder.java:554)
        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:600)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:509)
        ... 18 more
Caused by: java.lang.RuntimeException: Error injecting javax.persistence.EntityManager com.ing.diba.jeeop.cert_proxy.acme.database.NonceRepository.em
        at com.ing.diba.jeeop.cert_proxy.acme.database.NonceRepository_Bean.create(NonceRepository_Bean.zig:167)
        at com.ing.diba.jeeop.cert_proxy.acme.database.NonceRepository_Bean.get(NonceRepository_Bean.zig:205)
        at com.ing.diba.jeeop.cert_proxy.acme.database.NonceRepository_Bean.get(NonceRepository_Bean.zig:240)
        at com.ing.diba.jeeop.cert_proxy.acme.AcmeProtocolFeature_Bean.create(AcmeProtocolFeature_Bean.zig:242)
        ... 57 more
Caused by: javax.enterprise.inject.CreationException: Synthetic bean instance for javax.persistence.EntityManager not initialized yet: javax_persistence_EntityManager_3cb728d15a0a04006cc75d03f784feb2bba9a5fb
        - a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
        - RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
        at javax.persistence.EntityManager_9b922d59b548563a5d960515e5e44f2bd846ceab_Synthetic_Bean.create(EntityManager_9b922d59b548563a5d960515e5e44f2bd846ceab_Synthetic_Bean.zig:117)
        at javax.persistence.EntityManager_9b922d59b548563a5d960515e5e44f2bd846ceab_Synthetic_Bean.create(EntityManager_9b922d59b548563a5d960515e5e44f2bd846ceab_Synthetic_Bean.zig:140)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at javax.persistence.EntityManager_9b922d59b548563a5d960515e5e44f2bd846ceab_Synthetic_Bean.get(EntityManager_9b922d59b548563a5d960515e5e44f2bd846ceab_Synthetic_Bean.zig:172)
        at javax.persistence.EntityManager_9b922d59b548563a5d960515e5e44f2bd846ceab_Synthetic_Bean.get(EntityManager_9b922d59b548563a5d960515e5e44f2bd846ceab_Synthetic_Bean.zig:188)
        at com.ing.diba.jeeop.cert_proxy.acme.database.NonceRepository_Bean.create(NonceRepository_Bean.zig:149)
        ... 60 more
```

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

**Configuration**
`quarkus.datasource.db-kind=mssql`
`quarkus.datasource.username=SA`
`quarkus.datasource.password=sqlserver2019!`
`quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=ACME;applicationName=CertProxy;encrypt=false;`
`quarkus.datasource.jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver`

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18363.1082]
 - Output of `java -version`: 
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.8.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Maven home: C:\Users\HR11MD\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Users\HR11MD\java\jdk1.8.0_201-ing\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
Could you make `AcmeProtocolFeature` `@ApplicationScoped` instead of `@Singleton`?

**Comment by dinabogdan** [comment]
`AcmeProtocolFeature` is a `@Provider`, not a `@Singleton`.

**Comment by dinabogdan** [comment]
You're right. I'm having two `@Provider` classes where are injected different repositories. It seems that if I'm removing the `@Provider` and put `@ApplicationScoped` it is working fine. Still, I need those `@Provider`s. Do you know what is the root of this issue?

**Comment by gsmet** [comment]
What if you keep `@Provider` and just add `@ApplicationScoped`?

**Comment by gsmet** [comment]
The root of the issue is that the providers are initialized very early and the EntityManager far later in recent versions. So if you have a singleton `@Provider`, it will require the EM to be initialized early while it's not.

**Comment by dinabogdan** [comment]
It's not working if I keep both `@Provider` and `@ApplicationScoped`.

**Comment by gsmet** [comment]
'Not working' meaning...

**Comment by dinabogdan** [comment]
Meaning, the same error as before. Sorry for the confusion.

**Comment by gsmet** [comment]
@dinabogdan could you make `NonceRepository` `@ApplicationScoped` too?

**Comment by dinabogdan** [comment]
It seems to be working by making the `NonceRepository` `@ApplicationScoped`.

**Comment by gsmet** [comment]
Yeah, so basically, you need the whole chain `@Provider` -> ... -> `EntityManager` to be `@ApplicationScoped` as the `@Provider` bean is initialized very early.

**Comment by gsmet** [comment]
And it broke because we used to initialize the EntityManager bean early too but this has changed.

**Comment by dinabogdan** [comment]
Hi! I'm facing the same issue when I'm trying to run a `@QuarkusTest`, even with the above changes added into the code. Any idea about this?

**Comment by dinabogdan** [comment]
The received error is:

```
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error injecting com.ing.diba.jeeop.cert_proxy.acme.database.NonceRepository com.ing.diba.jeeop.cert_proxy.acme.AcmeProtocolFeature.nonceRepository
Caused by: java.lang.RuntimeException: Error injecting com.ing.diba.jeeop.cert_proxy.acme.database.NonceRepository com.ing.diba.jeeop.cert_proxy.acme.AcmeProtocolFeature.nonceRepository
Caused by: java.lang.RuntimeException: Error injecting javax.persistence.EntityManager com.ing.diba.jeeop.cert_proxy.acme.database.NonceRepository.em
Caused by: javax.enterprise.inject.CreationException:
Synthetic bean instance for javax.persistence.EntityManager not initialized yet: javax_persistence_EntityManager_3cb728d15a0a04006cc75d03f784feb2bba9a5fb
        - a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
        - RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem

```

**Comment by gsmet** [comment]
@dinabogdan any chance you could prepare a simple Maven reproducer so that we can have a look?

**Comment by dinabogdan** [comment]
I will try to create a sample project on Github. I should let you know that the issue goes away when I'm downgrading to version `1.7.1.Final`.

**Comment by gsmet** [comment]
Yeah it's not surprising. As mentioned, we changed how the EM beans are initialized in 1.8.

**Comment by dinabogdan** [comment]
Hi! You can find the reproducere here: https://github.com/dinabogdan/quarkus-sample-project-issue-12626.
