### ISSUE TITLE
SecurityIdentityAugmentor Blocking Calls

### ISSUE THREAD

**Issue by crivera** [quarkusio/quarkus#12640]
**Describe the bug**
Implemented the example from https://quarkus.io/guides/security-customization for a SecurityIdentityAugmentor.

I am using: ` return context.runBlocking(build(identity))`

and the build function

```
 private fun build(identity: SecurityIdentity): Supplier<SecurityIdentity> {
    return if (identity.isAnonymous) {
      Supplier { identity }
    } else {
      // create a new builder and copy principal, attributes, credentials and roles from the original identity
      val builder = QuarkusSecurityIdentity.builder(identity)

      // add custom role source here
      val user = userRepository.findByExternalId(identity.principal.name)
      user?.permissions?.forEach { builder.addRole(it.name) }

      builder.addAttribute("id", user?.id)

      Supplier { builder.build() }
    }

  }
}
```

**Expected behavior**
user gets loaded 

**Actual behavior**
 java.lang.IllegalStateException: You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.checkBlocking(TransactionScopedEntityManager.java:83)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.createQuery(TransactionScopedEntityManager.java:314)
        at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.createQuery(ForwardingEntityManager.java:142)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createBaseQuery(CommonPanacheQueryImpl.java:362)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createQuery(CommonPanacheQueryImpl.java:338)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.firstResult(CommonPanacheQueryImpl.java:283)
        at io.quarkus.hibernate.orm.panache.kotlin.runtime.PanacheQueryImpl.firstResult(PanacheQueryImpl.java:165)
        at org.iam.repository.UserRepository.findByExternalId(UserRepository.kt:25)
        at org.iam.repository.UserRepository_ClientProxy.findByExternalId(UserRepository_ClientProxy.zig:1999)
        at org.iam.repository.UserRepository.findByExternalId$default(UserRepository.kt:20)
        at org.iam.util.RolesAugmenter.build(RolesAugmenter.kt:38)
        at org.iam.util.RolesAugmenter.augment(RolesAugmenter.kt:27)

**To Reproduce**
Do JPA call inside SecurityIdentityAugmentor

**Comment by sberyozkin** [comment]
Interesting, this must be a thread from a thread pool. CC @stuartwdouglas, @gsmet

**Comment by stuartwdouglas** [comment]
Can you paste the full stack trace?

**Comment by stuartwdouglas** [comment]
Actually I can see the problem. You are doing the blocking operation before returning the Supplier, you need to do the blocking operation inside the supplier.

**Comment by crivera** [comment]
ah makes sense !!! thank you!

**Comment by crivera** [comment]
this here provided the solution in case anyone else needs it: https://nderwin.wordpress.com/2020/01/20/augment-your-quarkus-identity/
