### ISSUE TITLE
Native application faild to start when liquibase enabled

### ISSUE THREAD

**Issue by inngvar** [quarkusio/quarkus#12643]
**Describe the bug**
Native application failt to start when liquibase enabled

**Expected behavior**
Native application started

**Actual behavior**
Faild to start with error
`2020-10-10 11:27:37,751 ERROR [io.qua.application] (main) Failed to start application (with profile prod): java.lang.IllegalStateException: liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: liquibase.exception.UnexpectedLiquibaseException: java.lang.NoSuchMethodException: liquibase.change.core.LoadDataColumnConfig.<init>()
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:57)
	at io.quarkus.deployment.steps.LiquibaseProcessor$createBeansAndStartActions2123523327.deploy_0(LiquibaseProcessor$createBeansAndStartActions2123523327.zig:80)
	at io.quarkus.deployment.steps.LiquibaseProcessor$createBeansAndStartActions2123523327.deploy(LiquibaseProcessor$createBeansAndStartActions2123523327.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:565)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:91)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
Caused by: liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: liquibase.exception.UnexpectedLiquibaseException: java.lang.NoSuchMethodException: liquibase.change.core.LoadDataColumnConfig.<init>()
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:223)
	at liquibase.Liquibase.validate(Liquibase.java:1666)
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:48)
	... 8 more
Caused by: liquibase.exception.SetupException: liquibase.exception.UnexpectedLiquibaseException: java.lang.NoSuchMethodException: liquibase.change.core.LoadDataColumnConfig.<init>()
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:363)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:310)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
	... 11 more
Caused by: liquibase.exception.ChangeLogParseException: liquibase.exception.UnexpectedLiquibaseException: java.lang.NoSuchMethodException: liquibase.change.core.LoadDataColumnConfig.<init>()
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:576)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:355)
	... 13 more
Caused by: liquibase.exception.UnexpectedLiquibaseException: java.lang.NoSuchMethodException: liquibase.change.core.LoadDataColumnConfig.<init>()
	at liquibase.change.AbstractChange.load(AbstractChange.java:716)
	at liquibase.changelog.ChangeSet.toChange(ChangeSet.java:491)
	at liquibase.changelog.ChangeSet.handleChildNode(ChangeSet.java:424)
	at liquibase.changelog.ChangeSet.load(ChangeSet.java:348)
	at liquibase.changelog.DatabaseChangeLog.createChangeSet(DatabaseChangeLog.java:617)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:342)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:310)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
	... 15 more
Caused by: java.lang.NoSuchMethodException: liquibase.change.core.LoadDataColumnConfig.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3349)
	at java.lang.Class.getConstructor(DynamicHub.java:2151)
	at liquibase.change.AbstractChange.createEmptyColumnConfig(AbstractChange.java:728)
	at liquibase.change.AbstractChange.load(AbstractChange.java:635)
	... 22 more`

**To Reproduce**

https://github.com/inngvar/quarkus-liquibase-failed.git

1.  Start databe with `docker-compose up -d`
2.  build native application `./mvnw package -Pnative -Dquarkus.native.container-build=true`
3. run native application `/target/code-with-quarkus-1.0.0-SNAPSHOT-runner `

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.url=jdbc:postgresql://localhost:5432/testdb
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=testdb
quarkus.datasource.password=
quarkus.datasource.max-size=8
quarkus.datasource.min-size=2
quarkus.liquibase.change-log=config/liquibase/master.xml
quarkus.liquibase.migrate-at-start=true

**Environment (please complete the following information):**
 - Output of `uname -a`: `Linux igorch-GF63-Thin-9RCX 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` 
 - Output of `java -version`: `openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
`
 - Quarkus version or git rev: 1.8.2.FINAL 
 - Build tool `Maven home: /home/igorch/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: /home/igorch/.sdkman/candidates/java/11.0.8.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-48-generic", arch: "amd64", family: "unix"
`

**Comment by gsmet** [comment]
Thanks for the detailed test case. Fix is here: https://github.com/quarkusio/quarkus/pull/12677 .
