### ISSUE TITLE
Logging issues with log4j2-jboss-logmanager

### ISSUE THREAD

**Issue by aldettinger** [quarkusio/quarkus#12659]
**Describe the bug**
When using the **log4j2-jboss-logmanager**, logs are not printed when running tests.
Furthermore, when using a log4j logger next to a jboss logger, a stack trace is reported "Maximum number of attachments exceeded".

**Expected behavior**
I would expect logs to be printed during tests.
I would also expect the runner jar to start when using log4j + jboss loggers.

**To Reproduce**

A reproducer could be found at https://github.com/aldettinger/quarkus-log4j-issue-reproducer.
1. mvn clean package
2. => NO logs are issued to console during tests (while they are when using the runner jar)
3. Uncomment the two jboss logger related lines in HelloResource.java
4. mvn clean package
5. Still no logs are issued during tests
6. Moreover the stack trace below is issued:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:189)
        ... 9 more
Caused by: java.lang.RuntimeException: Failed to initialize Arc
        at io.quarkus.arc.Arc.initialize(Arc.java:26)
        at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:24)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy_0(ArcProcessor$generateResources-1025303321.zig:76)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy(ArcProcessor$generateResources-1025303321.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:147)
        ... 9 more
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at io.quarkus.reproducer.HelloResource_Bean.<init>(HelloResource_Bean.zig:40)
        at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans1(Default_ComponentsProvider.zig:134)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:38)
        at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:113)
        at io.quarkus.arc.Arc.initialize(Arc.java:20)
        ... 13 more
Caused by: java.lang.IllegalStateException: Maximum number of attachments exceeded
        at org.jboss.logmanager.LoggerNode.attachIfAbsent(LoggerNode.java:428)
        at org.jboss.logmanager.Logger.attachIfAbsent(Logger.java:194)
        at org.jboss.logging.JBossLogManagerProvider.doGetLogger(JBossLogManagerProvider.java:93)
        at org.jboss.logging.JBossLogManagerProvider.getLogger(JBossLogManagerProvider.java:53)
        at org.jboss.logging.Logger.getLogger(Logger.java:2465)
        at org.jboss.logging.Logger.getLogger(Logger.java:2490)
        at io.quarkus.reproducer.HelloResource.<clinit>(HelloResource.java:24)
```
**Environment (please complete the following information):**
 - Output of `uname -a` ~=
```
   Linux ag.remote.csb 3.10.0-957.27.2.el7.x86_64 #1 SMP Tue Jul 9 16:53:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
   openjdk version "11.0.8" 2020-07-14
   OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
   OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```
 - Quarkus version or git rev:
```
   1.9.0.CR1
```
 - Build tool mvn -version: 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/ag/dev/maven/apache-maven-3.6.3
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: /home/ag/.sdkman/candidates/java/11.0.8.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.27.2.el7.x86_64", arch: "amd64", family: "unix"
```
**Additional context**
The global context is that I'm experimenting around an extension that would involve 3rd party libraries making use of distinct kind of loggers. I tried to shrink the reproducer as far as possible.

**Comment by dmlloyd** [comment]
I've created a possible fix in https://github.com/quarkusio/quarkus/pull/12662 though it will take about 24 hours for the update to propagate to Maven.

**Comment by galderz** [comment]
I saw this just yesterday while trying to help Infinispan lot with their log4j integration issues. To be precise, I was trying https://github.com/GluuFederation/oxauth-config/issues/165#issuecomment-691041339 to fix https://github.com/quarkusio/quarkus/issues/11644.

So @dmlloyd, what do people that want to use log4j do? Exclude any log4j dependencies and depend on `log4j2-jboss-logmanager`? @ryanemerson, I'm unsure if this dependency is enough for the REST logging customization that Infinispan does...

**Comment by ryanemerson** [comment]
Infinispan exposes the current log4j configuration via a [REST endpoint](https://github.com/infinispan/infinispan/blob/aad7cba441e8bf4e2acdf8c870f9775df7b089bf/server/rest/src/main/java/org/infinispan/rest/resources/LoggingResource.java#L29), allowing the currently configured loggers and appenders to be listed, as well allowing loggers to be set/removed. 

For this to occur we need to be able to access the following classes at runtime:

```
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.core.Appender;
import org.apache.logging.log4j.core.LoggerContext;
import org.apache.logging.log4j.core.config.LoggerConfig;
```

Is this possible with `jboss-logmanager-embedded`?

**Comment by aldettinger** [comment]
I don't know about infinispan, in the context of an extension including 3rd party libraries with distinct kind of loggers, it worked by:
1. Cutting 3rd party log4j dependencies
2. Depending upon log4j2-jboss-logmanager
3. Bumping jboss-logmanager-embedded to 1.0.5 (should not be needed as of quarkus > 1.9.0.RC1)

@dmlloyd So well done, the fix with jboss-logmanager-embedded 1.0.5 looks fine when using runners directly.
However, logs are still missing when using surefire tests. At least in my context.

**Comment by gsmet** [comment]
@aldettinger do you have this defined: https://github.com/quarkusio/quarkus-quickstarts/blob/master/validation-quickstart/pom.xml#L59 ?

**Comment by aldettinger** [comment]
@gsmet I think so. From the effective-pom abstract below:
```
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M5</version>
        <executions>
          <execution>
            <id>default-test</id>
            <phase>test</phase>
            <goals>
              <goal>test</goal>
            </goals>
            <configuration>
              <systemPropertyVariables>
                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                <maven.home>/home/ag/dev/maven/apache-maven-3.6.3</maven.home>
              </systemPropertyVariables>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>/home/ag/dev/maven/apache-maven-3.6.3</maven.home>
          </systemPropertyVariables>
        </configuration>
      </plugin>
```

**Comment by dmlloyd** [comment]
I think that the lack of logs for surefire is a long standing problem. The configurator classes are installed into Quarkus apps but none of that infrastructure is guaranteed to be available to surefire tests.

**Comment by pujavs** [comment]
Still getting issues with Quarkus 1.9.2.Final . Please advice
