### ISSUE TITLE
Native build problem with sqlite

### ISSUE THREAD

**Issue by miluxhd** [quarkusio/quarkus#12777]
I have a simple application that inserts a row to the SQLite database and selects data from it.
I can run the fat jar without any problem. But after creating a native executable realized that it could not load the native library.
here is my stack-trace:

`Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:367)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:67)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235)
        ... 39 more
`
It works well without Quarkus.

sqlite version : 3.32.3.2
jdk : 11
graalvm : graalvm-ce-java11-20.2.0
kotlin : 1.3.72

**Comment by geoand** [comment]
This should be addressed by https://github.com/quarkiverse/quarkus-jdbc-sqlite
