### ISSUE TITLE
ResteasyScanningProcessor should look at @Path as a METHOD_ANNOTATIONS for reflection registration

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#1292]
The using-jwt-rbac quick start has a sub-resource locator pattern where the 

```java
@Path("/secured")
public class TokenSecuredResource {
...
    /**
     * Illustrate the same functionality as the winners endpoint using a sub-resource that has injected JsonWebToken and
     * @Claim values using the {@linkplain CDI#current()} API.
     *
     * @return LottoNumbersResource
     */
    @Path("/lotto")
    public LottoNumbersResource lotto() {
        return CDI.current().select(LottoNumbersResource.class).get();
    }
}
```
and LottoNumbersResource is:
```java
//@RegisterForReflection
@Dependent
public class LottoNumbersResource {
    @Inject
    JsonWebToken jwt;
    @Inject
    @Claim(standard = Claims.birthdate)
    Optional<JsonString> birthdate;

    @GET
    @Path("winners")
    @Produces(MediaType.APPLICATION_JSON)
    @RolesAllowed("Subscriber")
    public LottoNumbers winners() {
        int remaining = 6;
        ArrayList<Integer> numbers = new ArrayList<>();

        if (birthdate.isPresent()) {
            JsonString bdayString = birthdate.get();
            LocalDate bday = LocalDate.parse(bdayString.getString());
            numbers.add(bday.getDayOfMonth());
            remaining --;
        }
        while(remaining > 0) {
            int pick = (int) Math.rint(64 * Math.random());
            numbers.add(pick);
            remaining --;
        }
        LottoNumbers winners = new LottoNumbers();
        winners.setNumbers(numbers);
        return winners;
    }
}
```

This works fine in JVM mode, but when run under native mode it fails with:
```java
2019-03-06 18:28:48,087 ERROR [org.jbo.res.res.i18n] (XNIO-1 task-1) RESTEASY002005: Failed executing GET /secured/lotto/winners: org.jboss.resteasy.spi.InternalServerErrorException: RESTEASY003815: Subresource for target class has no jax-rs annotations.: org.acme.jwt.LottoNumbersResource
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:123)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.lambda$invoke$3(ResourceLocatorInvoker.java:100)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:100)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:476)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:229)
	at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.sendError(ResteasyFilter.java:72)
	at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:173)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
```

If I uncomment the @RegisterForReflection on LottoNumbersResource, this runs fine under native mode as well. 

Currently the set of annotations that qualify a method for reflection introspection does not include the javax.ws.rs.Path. This should be added to support the sub-resource locator pattern.

**Comment by gsmet** [comment]
This has been fixed.
