### ISSUE TITLE
Quarkus 1.9 native image generation Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by ineednousername** [quarkusio/quarkus#12997]
Not sure if this a bug or not but I noticed the following when upgrading from quarkus 1.8.x to 1.9.0
**Describe the bug**
After upgrading to quarkus 1.9 my ci pipeline suddenly failed with the following error:

```
18:32:29,617 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
[xxxx-1.0.0-runner:24]     (clinit):   1,173.99 ms,  1.87 GB
[xxxx-1.0.0-runner:24]   (typeflow):  44,356.63 ms,  1.87 GB
[xxxx-1.0.0-runner:24]    (objects):  57,539.10 ms,  1.87 GB
[xxxx-1.0.0-runner:24]   (features):   2,115.63 ms,  1.87 GB
[xxxx-1.0.0-runner:24]     analysis: 109,274.47 ms,  1.87 GB
[xxxx-1.0.0-runner:24]     universe:   3,722.10 ms,  1.84 GB
Exception in thread "native-image pid watcher" java.lang.OutOfMemoryError: GC overhead limit exceeded
[xxxx-1.0.0-runner:24]      (parse): 342,429.92 ms,  1.78 GB
[xxxx-1.0.0-runner:24]      compile: 345,879.49 ms,  1.78 GB
Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at method: void io.vertx.core.impl.DeploymentManager.deployVerticle(Supplier, DeploymentOptions, Handler)
	at com.oracle.svm.hosted.code.CompileQueue.defaultParseFunction(CompileQueue.java:759)
	at com.oracle.svm.hosted.code.CompileQueue.doParse(CompileQueue.java:691)
	at com.oracle.svm.hosted.code.CompileQueue$ParseTask.run(CompileQueue.java:307)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
Error: Image build request failed with exit status 1

```

the odd thing is that I did not have this issue before.

My quarkus maven plugin is configured like this

```
 <groupId>io.quarkus</groupId>
                    <artifactId>quarkus-maven-plugin</artifactId>
                    <version>${quarkus.version}</version>
                    <configuration>
                        <nativeImageXmx>4096m</nativeImageXmx>
                    </configuration>
```

**To Reproduce**

I will try to add a reproducer later.

**Comment by machi1990** [comment]
@ineednousername thanks for reporting the issue. What happens if you increase the heap size to say 6GB?

**Comment by ineednousername** [comment]
@machi1990 I already tried this and increased to 5GB this works in a stable manner again. But I wonder why it worked stable with quarkus 1.8.x and before with 4GB.

**Comment by machi1990** [comment]
Thanks for confirming. 

The native image generation phase is known to consume a lot of memory. In my setups (depending on the size of the project) I usually allocate it more than 4GB just to avoid any kind of memory limit errors. It will be interesting to understand what changed though (in your application or on Quarkus side) and for that a reproducer might be a good start.

**Comment by ineednousername** [comment]
@machi1990 I could not reproduce the issue locally, but I noticed on the CI system that the graalvm was still 20.1.0 after upgrading to 20.2.0 on the CI system (same version that is also locally is used) this issue is gone and it works again with 4GB as before.

**Comment by machi1990** [comment]
Thanks for checking @ineednousername
