### ISSUE TITLE
OIDC Extension compile error when discovery disabled

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#13039]
**Describe the bug**
I have disabled the auto discovery with below configuration and manually configured jwks path. This setting is not being honored by OIDC extension
 
`quarkus.oidc.discovery-enabled=false`

And I have following settings
```properties
quarkus.oidc.auth-server-url=http://redacted/auth/realms/quarkus
quarkus.oidc.discovery-enabled=false
quarkus.oidc.client-id=backend
quarkus.oidc.credentials.secret=7redactedb
quarkus.oidc.roles.role-claim-path=scope
quarkus.oidc.jwks-path=http://redacted/auth/realms/quarkus/protocol/openid-connect/certs

```

I have getting below compile time error

```java
2020-10-31 18:06:15,484 DEBUG [io.qua.arc.impl] (Quarkus Main Thread) ArC DI container shut down
2020-10-31 18:06:15,485 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.quarkus.oidc.OIDCException: Either 'jwks-path' or 'introspection-path' properties must be set when the discovery is disabled.
	at io.quarkus.oidc.runtime.OidcRecorder.createTenantContext(OidcRecorder.java:144)
	at io.quarkus.oidc.runtime.OidcRecorder.setup(OidcRecorder.java:57)
	at io.quarkus.deployment.steps.OidcBuildStep$setup-1552895091.deploy_0(OidcBuildStep$setup-1552895091.zig:87)
	at io.quarkus.deployment.steps.OidcBuildStep$setup-1552895091.deploy(OidcBuildStep$setup-1552895091.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:664)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:95)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
```
**Expected behavior**
Manual *jwks* configuration should be detected by OIDC extension when discovery is disabled.

**Actual behavior**
See the stacktrace above

**To Reproduce**

Setup the project in user guide and configure the application properties as shown above

https://quarkus.io/guides/security-openid-connect

**Configuration**
```properties
quarkus.oidc.auth-server-url=http://redacted/auth/realms/quarkus
quarkus.oidc.discovery-enabled=false
quarkus.oidc.client-id=backend
quarkus.oidc.credentials.secret=7redactedb
quarkus.oidc.roles.role-claim-path=scope
quarkus.oidc.jwks-path=http://redacted/auth/realms/quarkus/protocol/openid-connect/certs
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux x64
 - Output of `java -version`:  Java 11
 - GraalVM version (if different from Java): NA
 - Quarkus version or git rev: 1.9.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvnw

**Comment by sberyozkin** [comment]
@missourian55 This is an invalid issue, it is documented to be a relative property
