### ISSUE TITLE
1.9.1 throws Response has already been written from RouteFilter

### ISSUE THREAD

**Issue by burmanm** [quarkusio/quarkus#13035]
**Describe the bug**
After updating from 1.8.3.Final to 1.9.1.Final our tests have started to throw this to the logs:

```
2020-10-30 17:33:39,400 ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-9) Mutiny had to drop the following exception: java.lang.IllegalStateException: Response has already been written
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:376)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:365)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:421)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$1$1.accept(HttpSecurityRecorder.java:75)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$1$1.accept(HttpSecurityRecorder.java:72)
```

This happens in a ``@RouteFilter(401)`` when it calls ``rc.next()``. This does not happen with earlier versions.

**Expected behavior**
No such error should be output.

**Actual behavior**

**To Reproduce**
```java
    @RouteFilter(401)
    void oasAcceptHeaderMangler(RoutingContext rc) {
        if (rc.normalisedPath().endsWith("openapi.json")) {
            rc.request().headers().remove("Accept");
            rc.request().headers().add("Accept", "application/json");
        }
        rc.next();
    }
```

We use HttpAuthenticationMechanism and these tests are triggering the failure path:

```java
public Uni<SecurityIdentity> authenticate(RoutingContext routingContext, IdentityProviderManager identityProviderManager) {
...
.onFailure().transform(AuthenticationFailedException::new)
...
```

**Comment by cescoffier** [comment]
The exception means that Mutiny received a _failure_, but cannot do anything with it (it would violate the Reactive Streams protocol). Before these exceptions were swallowed. Now, they are logged. 

From what I can see, it's a bug in the `HttpSecurityRecorder`, which tries to `end` a response which is already ended (leading to the exception).

**Comment by cescoffier** [comment]
By any chance, do you know what could `end` that request?

**Comment by cescoffier** [comment]
I wonder if it justs needs a simple:

```java
if (! event.response().ended()) {
   event.response().end();
}
```

**Comment by stuartwdouglas** [comment]
I think a simple check is all that is needed. sendChallenge can send data and end the response, so this is expected, when I wrote this I guess I did not realise that calling .end() on a response that has already ended would throw.
