### ISSUE TITLE
AgroalDataSource causes tests to fail with UnsatisfiedResolutionException

### ISSUE THREAD

**Issue by miquelsi** [quarkusio/quarkus#13180]
**Describe the bug**
Injecting an `AgroalDataSource` causes `@QuarkusTest` tests to fail.

**Expected behavior**
Tests are executed with no failures.

**Actual behavior**
Running the tests produces the following error
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.agroal.api.AgroalDataSource and qualifiers [@Default]
	- java member: org.acme.datasource.GreetingResource#agroalDataSource
	- declared on CLASS bean [types=[org.acme.datasource.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.datasource.GreetingResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1021)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:241)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:127)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.agroal.api.AgroalDataSource and qualifiers [@Default]
	- java member: org.acme.datasource.GreetingResource#agroalDataSource
	- declared on CLASS bean [types=[org.acme.datasource.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.datasource.GreetingResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:504)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:363)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:233)
	... 14 more

Caused by: java.lang.RuntimeException: 
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.agroal.api.AgroalDataSource and qualifiers [@Default]
	- java member: org.acme.datasource.GreetingResource#agroalDataSource
	- declared on CLASS bean [types=[org.acme.datasource.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.datasource.GreetingResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1021)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:241)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:127)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.agroal.api.AgroalDataSource and qualifiers [@Default]
	- java member: org.acme.datasource.GreetingResource#agroalDataSource
	- declared on CLASS bean [types=[org.acme.datasource.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.datasource.GreetingResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:504)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:363)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:233)
	... 14 more

Caused by: io.quarkus.builder.BuildException: 
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.agroal.api.AgroalDataSource and qualifiers [@Default]
	- java member: org.acme.datasource.GreetingResource#agroalDataSource
	- declared on CLASS bean [types=[org.acme.datasource.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.datasource.GreetingResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1021)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:241)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:127)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.agroal.api.AgroalDataSource and qualifiers [@Default]
	- java member: org.acme.datasource.GreetingResource#agroalDataSource
	- declared on CLASS bean [types=[org.acme.datasource.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.datasource.GreetingResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:504)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:363)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:233)
	... 14 more

Caused by: javax.enterprise.inject.spi.DeploymentException: 
javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.agroal.api.AgroalDataSource and qualifiers [@Default]
	- java member: org.acme.datasource.GreetingResource#agroalDataSource
	- declared on CLASS bean [types=[org.acme.datasource.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.datasource.GreetingResource]
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: 
Unsatisfied dependency for type io.agroal.api.AgroalDataSource and qualifiers [@Default]
	- java member: org.acme.datasource.GreetingResource#agroalDataSource
	- declared on CLASS bean [types=[org.acme.datasource.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.datasource.GreetingResource]
```

**To Reproduce**

Clone and execute project in https://github.com/miquelsi/agroal-datasources or follow the steps below.

1. Create project with `mvn io.quarkus:quarkus-maven-plugin:1.9.2.Final:create -DprojectGroupId=org.acme -DprojectArtifactId=agroal-datasources -DclassName="org.acme.datasource.GreetingResource" -Dpath="/hello" -Dextentions="agroal,jdbc-h2,narayana-jta"`
2. Add `quarkus-agroal` and `h2` dependencies to POM file.
3. `@Inject` an `AgroalDataSource` in `GreetingResource`
4. Configure a data source in `src/test/resources/application.properties` with properties below
5. Run `GreetingResourceTest`

**Configuration**
```properties
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:default
quarkus.datasource.jdbc.driver=org.h2.Driver
quarkus.datasource.username=username-default
```

**Environment**
 - Output of `uname -a` or `ver`: Linux fedora 5.8.17-200.fc32.x86_64 #1 SMP Thu Oct 29 18:14:53 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
```
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (build 25.272-b10, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.9.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional information**
This issue may be related to https://github.com/quarkusio/quarkus/issues/2831

**Comment by gsmet** [comment]
You need to also define:
```
quarkus.datasource.db-kind=h2
```

**Comment by miquelsi** [comment]
> You need to also define:
> 
> ```
> quarkus.datasource.db-kind=h2
> ```

Thanks, updated.

**Comment by gsmet** [comment]
So now your tests are passing, it's the main build that fails because the datasource is not defined.

You need to also define the datasource in the main `application.properties`.

`cat src/test/resources/application.properties > src/main/resources/application.properties` fixes your build.

**Comment by miquelsi** [comment]
Right, thanks for the answer, now it works :+1:
