### ISSUE TITLE
Error while building native image 

### ISSUE THREAD

**Issue by pradeepkusingh** [quarkusio/quarkus#13248]
**Describe the bug**
Trying to use the latest GraalVM and getting error while bulding native image. Generated project from Quarkus site.

Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.UnsupportedClassVersionError: org/acme/lambda/GreetingLambda has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Expected behavior**
Expecting to run flawless

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**

1.  Generate a gradle project from Quarkus site with aws lambda extension
2.  Try to build native image with OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 25.262-b10-jvmci-20.2-b03, mixed mode)
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java):  OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 25.262-b10-jvmci-20.2-b03, mixed mode)
 - Quarkus version or git rev:  latest from Quarkus site
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by pradeepkusingh** [comment]
Here is full stack trace:

2020-11-11T17:24:34.311-0700 [ERROR] [system.err] Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.quarkus.deployment.steps.AmazonLambdaProcessor$recordHandlerClass-1619263778.deploy_0(io.quarkus.runtime.StartupContext, java.lang.Object[])
2020-11-11T17:24:34.311-0700 [ERROR] [system.err] Parsing context:
2020-11-11T17:24:34.312-0700 [ERROR] [system.err]       parsing io.quarkus.deployment.steps.AmazonLambdaProcessor$recordHandlerClass-1619263778.deploy(AmazonLambdaProcessor$recordHandlerClass-1619263778.zig:40)
2020-11-11T17:24:34.312-0700 [ERROR] [system.err]       parsing io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:443)
2020-11-11T17:24:34.312-0700 [ERROR] [system.err]       parsing io.quarkus.runtime.Application.start(Application.java:90)
2020-11-11T17:24:34.312-0700 [ERROR] [system.err]       parsing io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:95)
2020-11-11T17:24:34.312-0700 [ERROR] [system.err]       parsing io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
2020-11-11T17:24:34.312-0700 [ERROR] [system.err]       parsing io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
2020-11-11T17:24:34.312-0700 [ERROR] [system.err]       parsing io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
2020-11-11T17:24:34.313-0700 [ERROR] [system.err]       parsing io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
2020-11-11T17:24:34.313-0700 [ERROR] [system.err]       parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:149)
2020-11-11T17:24:34.313-0700 [ERROR] [system.err]       parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
2020-11-11T17:24:34.313-0700 [ERROR] [system.err]       parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
2020-11-11T17:24:34.313-0700 [ERROR] [system.err]
2020-11-11T17:24:34.314-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
2020-11-11T17:24:34.314-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
2020-11-11T17:24:34.314-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
2020-11-11T17:24:34.314-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
2020-11-11T17:24:34.314-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:227)
2020-11-11T17:24:34.314-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
2020-11-11T17:24:34.315-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
2020-11-11T17:24:34.315-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:552)
2020-11-11T17:24:34.315-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
2020-11-11T17:24:34.315-0700 [ERROR] [system.err]       at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
2020-11-11T17:24:34.315-0700 [ERROR] [system.err]       at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
2020-11-11T17:24:34.315-0700 [ERROR] [system.err]       at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
2020-11-11T17:24:34.316-0700 [ERROR] [system.err]       at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
2020-11-11T17:24:34.316-0700 [ERROR] [system.err]       at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
2020-11-11T17:24:34.316-0700 [ERROR] [system.err] Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.UnsupportedClassVersionError: org/acme/lambda/GreetingLambda has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2020-11-11T17:24:34.316-0700 [ERROR] [system.err]       at parsing io.quarkus.deployment.steps.AmazonLambdaProcessor$recordHandlerClass-1619263778.deploy_0(AmazonLambdaProcessor$recordHandlerClass-1619263778.zig:75)
2020-11-11T17:24:34.316-0700 [ERROR] [system.err]       at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2580)
2020-11-11T17:24:34.316-0700 [ERROR] [system.err]       at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:100)
2020-11-11T17:24:34.317-0700 [ERROR] [system.err]       at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3418)
2020-11-11T17:24:34.317-0700 [ERROR] [system.err]       at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3220)
2020-11-11T17:24:34.317-0700 [ERROR] [system.err]       at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1090)
2020-11-11T17:24:34.317-0700 [ERROR] [system.err]       at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:984)
2020-11-11T17:24:34.317-0700 [ERROR] [system.err]       at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
2020-11-11T17:24:34.317-0700 [ERROR] [system.err]       at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:74)
2020-11-11T17:24:34.317-0700 [ERROR] [system.err]       at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
2020-11-11T17:24:34.318-0700 [ERROR] [system.err]       at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
2020-11-11T17:24:34.318-0700 [ERROR] [system.err]       at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
2020-11-11T17:24:34.318-0700 [ERROR] [system.err]       at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
2020-11-11T17:24:34.318-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
2020-11-11T17:24:34.318-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
2020-11-11T17:24:34.318-0700 [ERROR] [system.err]       at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
2020-11-11T17:24:34.318-0700 [ERROR] [system.err]       ... 12 more
2020-11-11T17:24:34.319-0700 [ERROR] [system.err] Caused by: java.lang.UnsupportedClassVersionError: org/acme/lambda/GreetingLambda has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2020-11-11T17:24:34.319-0700 [ERROR] [system.err]

**Comment by geoand** [comment]
Can you try performing:

```
mvn -version
``` 

and report the result please?

I suspend you are using Java 8...
