### ISSUE TITLE
Error with RoutingContext Inject with Reactive routing

### ISSUE THREAD

**Issue by lucaspouzac** [quarkusio/quarkus#13262]
**Describe the bug**
If I inject RoutingContext in a RequestScoped bean, an error are throwed when I try to get him. The problem is identified with reactive route (normal ou blocking handler). With Jax RS service, it's OK.

**Expected behavior**
Access RoutingContext bean inject in RequestScoped bean.

**Actual behavior**
```
Reported exception:
SLF4J: Failed toString() invocation on an object of type [io.quarkus.RequestScopedService_ClientProxy]
Reported exception:
javax.enterprise.inject.IllegalProductException: Normal scoped producer method may not return null: io.quarkus.vertx.http.runtime.CurrentVertxRequest.getCurrent()
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.create(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.zig:178)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.create(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.zig:197)
	at io.quarkus.arc.impl.RequestContext.get(RequestContext.java:67)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.arc$delegate(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.zig:100)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.toString(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.zig:942)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at io.quarkus.RequestScopedService.toString(RequestScopedService.java:20)
	at io.quarkus.RequestScopedService_ClientProxy.toString(RequestScopedService_ClientProxy.zig:161)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
	at org.slf4j.helpers.MessageFormatter.format(MessageFormatter.java:124)
	at org.jboss.slf4j.JBossLoggerAdapter.info(JBossLoggerAdapter.java:183)
	at io.quarkus.TestRoute.test(TestRoute.java:21)
	at io.quarkus.TestRoute_RouteHandler_test_996e1735fd0007ce67bd96d669ec34af05f4f2db.invoke(TestRoute_RouteHandler_test_996e1735fd0007ce67bd96d669ec34af05f4f2db.zig:109)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:53)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:17)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1036)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:95)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$16.handle(VertxHttpRecorder.java:1080)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$16.handle(VertxHttpRecorder.java:1051)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1036)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$4.handle(VertxHttpRecorder.java:306)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$4.handle(VertxHttpRecorder.java:284)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1036)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$3.handle(VertxHttpHotReplacementSetup.java:85)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$3.handle(VertxHttpHotReplacementSetup.java:74)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**

With the attach project

```
$ curl localhost:8080/reactive/ 
javax.enterprise.inject.IllegalProductException: Normal scoped producer method may not return null: io.quarkus.vertx.http.runtime.CurrentVertxRequest.getCurrent()
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.create(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.zig:178)
	...
[bug-inject-routing-context.tar.gz](https://github.com/quarkusio/quarkus/files/5532303/bug-inject-routing-context.tar.gz)
[bug-inject-routing-context.tar.gz](https://github.com/quarkusio/quarkus/files/5532306/bug-inject-routing-context.tar.gz)


2020-11-12 18:45:46,881 INFO  [io.qua.TestRoute] (vert.x-eventloop-thread-16) RequestScopedService: [FAILED toString()]

$ curl localhost:8080/jaxrs/ 
2020-11-12 18:46:31,058 INFO  [io.qua.TestResource] (executor-thread-1) RequestScopedService: RequestScopedService{routingContext=io.vertx.ext.web.impl.RoutingContextImpl@4c88e5f5}

```
[bug-inject-routing-context.tar.gz](https://github.com/quarkusio/quarkus/files/5532316/bug-inject-routing-context.tar.gz)

**Comment by manovotn** [comment]
Looks like 'RoutingContext' isn't always set in here - https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/CurrentVertxRequest.java#L11

If that field is null and the cdi producer (that is normal scoped) attempts to return it, it is an error according to cdi specification.

**Comment by lucaspouzac** [comment]
Yes, I had seen this, but is it normal that it is not set in the case of reactive routes?

**Comment by lucaspouzac** [comment]
If I add a **RouteFilter** as this

```
package io.quarkus;

import io.quarkus.vertx.http.runtime.CurrentVertxRequest;
import io.quarkus.vertx.web.RouteFilter;
import io.vertx.ext.web.RoutingContext;

import javax.inject.Inject;

public class TestFilter {

    @Inject
    private CurrentVertxRequest currentVertxRequest;

    @RouteFilter(100)
    void myFilter(RoutingContext rc) {
        currentVertxRequest.setCurrent(rc);
        rc.next();
    }
}
```

it works but only for GET type calls for reactive routes. I think that we come then to the case described here #13073

```
$ curl localhost:8080/jaxrs/
2020-11-13 08:08:02,111 INFO  [io.qua.TestResource] (executor-thread-1) RequestScopedService: RequestScopedService{routingContext=io.vertx.ext.web.impl.RoutingContextImpl@5b22cc9d}

$ curl localhost:8080/reactive/
2020-11-13 08:08:10,164 INFO  [io.qua.TestRoute] (vert.x-eventloop-thread-14) RequestScopedService: RequestScopedService{routingContext=io.vertx.ext.web.impl.RoutingContextImpl@319feccd}

$ curl -X POST localhost:8080/reactive/
javax.enterprise.inject.IllegalProductException: Normal scoped producer method may not return null: io.quarkus.vertx.http.runtime.CurrentVertxRequest.getCurrent()
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.create(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.zig:178)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.create(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.zig:197)
	at io.quarkus.arc.impl.RequestContext.get(RequestContext.java:67)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.arc$delegate(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.zig:100)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.toString(CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.zig:942)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at io.quarkus.RequestScopedService.toString(RequestScopedService.java:20)
2020-11-13 08:08:22,317 INFO  [io.qua.TestRoute] (vert.x-eventloop-thread-23) RequestScopedService: [FAILED toString()]
```

**Comment by mkouba** [comment]
From what I know the `CurrentVertxRequest` is never set for reactive routes. The main reason being that you can inject it directly in a route method (as a param) and pass to any dependency directly. In other words, the `CurrentVertxRequest` should be normally useless for reactive routes and we'd like to avoid unnecessary allocations...

**Comment by manovotn** [comment]
> Yes, I had seen this, but is it normal that it is not set in the case of reactive routes?

Probably yes, I don't know much about reactive, I was just summing up the CDI part of it :-)

**Comment by mkouba** [comment]
> Probably yes, I don't know much about reactive, I was just summing up the CDI part of it :-)

Sure, no problem :-)
