### ISSUE TITLE
Invalid LogManager error of type FORMAT_FAILURE seen only in native image

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#1337]
The using-jwt-rbac quickstart running under native mode is showing this error on the console when a request is made:

```java
LogManager error of type FORMAT_FAILURE: Formatting error
java.util.IllegalFormatConversionException: d != java.lang.String
	at org.wildfly.common.format.Printf.checkType(Printf.java:1021)
	at org.wildfly.common.format.Printf.formatDirect(Printf.java:503)
	at org.jboss.logmanager.formatters.ColorPrintf.formatDirect(ColorPrintf.java:42)
	at org.wildfly.common.format.Printf.format(Printf.java:98)
	at org.jboss.logmanager.formatters.ColorPatternFormatter.formatMessage(ColorPatternFormatter.java:130)
	at org.jboss.logmanager.formatters.Formatters$16.renderRaw(Formatters.java:781)
	at org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:221)
	at org.jboss.logmanager.formatters.ColorPatternFormatter$ColorStep.render(ColorPatternFormatter.java:149)
	at org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:86)
	at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:32)
	at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:43)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:82)
	at org.jboss.logmanager.handlers.ConsoleHandler$1.error(ConsoleHandler.java:78)
	at java.util.logging.Handler.reportError(Handler.java:241)
	at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:45)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.handlers.DelayedHandler.publishToChildren(DelayedHandler.java:208)
	at org.jboss.logmanager.handlers.DelayedHandler.doPublish(DelayedHandler.java:49)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:316)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.Logger.logRaw(Logger.java:748)
	at org.jboss.logmanager.Logger.log(Logger.java:706)
	at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
	at org.jboss.logging.Logger.debugf(Logger.java:725)
	at io.quarkus.smallrye.jwt.runtime.auth.JwtIdentityManager.verify(JwtIdentityManager.java:40)
	at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMechanism.authenticate(JWTAuthMechanism.java:67)
	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:245)
	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:268)
	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.access$100(SecurityContextImpl.java:231)
	at io.undertow.security.impl.SecurityContextImpl.attemptAuthentication(SecurityContextImpl.java:125)
	at io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:99)
	at io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:92)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentTemplate$7$1$1.call(UndertowDeploymentTemplate.java:415)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1382)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```
The JwtIdentityManager.verify(JwtIdentityManager.java:40) line in question here is:
https://github.com/quarkusio/quarkus/blob/dc387ea3a4cf4fd4973291002778018e4ef614ec/extensions/smallrye-jwt/runtime/src/main/java/io/quarkus/smallrye/jwt/runtime/auth/JwtIdentityManager.java#L40

If I run this under jvm mode, the logging output happens as expected:

```log
...
19:30:09 DEBUG [io.qu.sm.jw.ru.au.JwtIdentityManager]] (XNIO-1 task-1) authenticate, id=jdoe@quarkus.io, result=SecurityIdentity{principal=DefaultJWTCallerPrincipal{id='a-123', name='jdoe@quarkus.io', expiration=1552019176, notBefore=0, issuedAt=1552015576, issuer='https://quarkus.io/using-jwt-rbac', audience=[using-jwt-rbac], subject='jdoe-using-jwt-rbac', issuedFor='null', authTime=1552015576, givenName='null', familyName='null', middleName='null', nickName='null', preferredUsername='jdoe', email='null', emailVerified=null, allowedOrigins=null, updatedAt=0, acr='null', groups=[Echoer,Group2MappedRole,Tester,Subscriber,group2]}, securityDomain=org.wildfly.security.auth.server.SecurityDomain@169ed0e5, authorizationIdentity=org.wildfly.security.auth.realm.token.TokenSecurityRealm$TokenRealmIdentity$1@407c02be, realmInfo=RealmInfo{name='Quarkus-JWT', securityRealm=org.wildfly.security.auth.realm.token.TokenSecurityRealm@5e37541}, creationTime=2019-03-08T03:30:09.008Z}
```

This is based on my current fork where I have the native image build for the smallrye-jwt extension working.

**Comment by dmlloyd** [comment]
You may want to do a clean rebuild of the extension and then the test (or maybe just do a full `mvn clean && git clean -d -f && mvn install -Dno-native -DskipTests` to get a nice clean slate).  That code path should only be possible if there was a `%d` sequence in the log format string, which there is not.

**Comment by starksm64** [comment]
I did the completely clean rebuild, and now the error is:

```java
LogManager error of type FORMAT_FAILURE: Formatting error
java.lang.ClassCastException
	at org.jose4j.jwt.JwtClaims.getClaimValue(JwtClaims.java:248)
	at org.jose4j.jwt.JwtClaims.getStringListClaimValue(JwtClaims.java:293)
	at io.quarkus.smallrye.jwt.runtime.auth.ElytronJwtCallerPrincipal.getAudience(ElytronJwtCallerPrincipal.java:63)
	at io.quarkus.smallrye.jwt.runtime.auth.ElytronJwtCallerPrincipal.toString(ElytronJwtCallerPrincipal.java:164)
	at io.quarkus.smallrye.jwt.runtime.auth.ElytronJwtCallerPrincipal.toString(ElytronJwtCallerPrincipal.java:145)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.wildfly.security.auth.server.SecurityIdentity.toString(SecurityIdentity.java:931)
	at java.lang.String.valueOf(String.java:2994)
	at org.wildfly.common.format.Printf.formatPlainString(Printf.java:681)
	at org.jboss.logmanager.formatters.ColorPrintf.formatPlainString(ColorPrintf.java:88)
	at org.wildfly.common.format.Printf.formatDirect(Printf.java:554)
	at org.jboss.logmanager.formatters.ColorPrintf.formatDirect(ColorPrintf.java:42)
	at org.wildfly.common.format.Printf.format(Printf.java:98)
	at org.jboss.logmanager.formatters.ColorPatternFormatter.formatMessage(ColorPatternFormatter.java:130)
	at org.jboss.logmanager.formatters.Formatters$16.renderRaw(Formatters.java:781)
	at org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:221)
	at org.jboss.logmanager.formatters.ColorPatternFormatter$ColorStep.render(ColorPatternFormatter.java:149)
	at org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:86)
	at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:32)
	at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:43)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.handlers.DelayedHandler.publishToChildren(DelayedHandler.java:208)
	at org.jboss.logmanager.handlers.DelayedHandler.doPublish(DelayedHandler.java:49)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:316)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
	at org.jboss.logmanager.Logger.logRaw(Logger.java:748)
	at org.jboss.logmanager.Logger.log(Logger.java:706)
	at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
	at org.jboss.logging.Logger.debugf(Logger.java:725)
	at io.quarkus.smallrye.jwt.runtime.auth.JwtIdentityManager.verify(JwtIdentityManager.java:40)
	at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMechanism.authenticate(JWTAuthMechanism.java:67)
	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:245)
	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:268)
	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.access$100(SecurityContextImpl.java:231)
	at io.undertow.security.impl.SecurityContextImpl.attemptAuthentication(SecurityContextImpl.java:125)
	at io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:99)
	at io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:92)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentTemplate$7$1$1.call(UndertowDeploymentTemplate.java:415)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1382)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

and this happens on the first request only, but every-time in the native image, but never in the jvm image. The real issue is some class cast exception in the native image during the to string call on the `org.wildfly.security.auth.server.SecurityIdentity` object. I guess this is in reality some missing class reflection issue?

**Comment by dmlloyd** [comment]
I don't see how it could be reflection; also that line (assuming I'm looking at the correct version) doesn't correspond to any cast.  What version of jose4j are you looking at?

**Comment by starksm64** [comment]
The version is 0.6.0, and line 248 cannot generate a CCE, so it must be the type.cast call, but then the exception seen should have been a  MalformedClaimException:

```java
    public <T> T getClaimValue(String claimName, Class<T> type) throws MalformedClaimException
    {
        Object o = claimsMap.get(claimName); // Line 248
        try
        {
            return type.cast(o);
        }
        catch (ClassCastException e)
        {
            throw new MalformedClaimException("The value of the '" + claimName + "' claim is not the expected type " + classCastMsg(e, o), e);
        }
    }
````

**Comment by starksm64** [comment]
I went into the ElytronJwtCallerPrincipal#getAudience code making the call to JwtClaims#getClaimValue and updated the exception it is catching from MalformedClaimException  to Exception to avoid the leak out of toString(), and it is definitely seeing a CCE coming from line 248. There has to be some merging of the lookup and the type.cast calls in the native image that is not correctly mapping the exception handling. This must be some graal bug, so I'll close this issue.
