### ISSUE TITLE
Logging gelf CI error

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#13386]
**Describe the bug**
This error popped in my PR CI on JDK 11 only (I guess it failed randomly): 

```
2020-11-19T14:36:38.3344940Z 14:36:38.332 Elasticsearch:[2020-11-19T14:36:38,332][INFO ][o.e.c.m.MetaDataMappingService] [WrTBv6K] [graylog_0/KnNZYaLcRNOvAQpgNk6tMg] update_mapping [message]
2020-11-19T14:36:47.6449872Z 2020-11-19 14:36:37,364 INFO  [io.qua.log.gel.it.GelfLogHandlerResource] (executor-thread-1) Some useful log message
2020-11-19T14:36:47.6459855Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 18.871 s <<< FAILURE! - in io.quarkus.logging.gelf.it.GelfLogHandlerTest
2020-11-19T14:36:47.6462060Z [ERROR] io.quarkus.logging.gelf.it.GelfLogHandlerTest.test  Time elapsed: 12.019 s  <<< ERROR!
2020-11-19T14:36:47.6463737Z org.awaitility.core.ConditionTimeoutException: 
2020-11-19T14:36:47.6465425Z Assertion condition defined as a io.quarkus.logging.gelf.it.GelfLogHandlerTest 1 expectation failed.
2020-11-19T14:36:47.6466626Z Expected status code <200> but was <400>.
2020-11-19T14:36:47.6467131Z  within 10 seconds.
2020-11-19T14:36:47.6468169Z 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
2020-11-19T14:36:47.6470986Z 	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
2020-11-19T14:36:47.6472835Z 	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
2020-11-19T14:36:47.6474793Z 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
2020-11-19T14:36:47.6476679Z 	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
2020-11-19T14:36:47.6478743Z 	at io.quarkus.logging.gelf.it.GelfLogHandlerTest.test(GelfLogHandlerTest.java:59)
2020-11-19T14:36:47.6480834Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-11-19T14:36:47.6483131Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-11-19T14:36:47.6485827Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-19T14:36:47.6487836Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-19T14:36:47.6489787Z 	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:805)
2020-11-19T14:36:47.6492799Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:712)
2020-11-19T14:36:47.6495749Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-11-19T14:36:47.6498545Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-11-19T14:36:47.6501633Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-11-19T14:36:47.6504734Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2020-11-19T14:36:47.6507971Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
2020-11-19T14:36:47.6511414Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
2020-11-19T14:36:47.6535575Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-11-19T14:36:47.6538452Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-11-19T14:36:47.6541567Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-11-19T14:36:47.6545072Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2020-11-19T14:36:47.6548802Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2020-11-19T14:36:47.6552504Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2020-11-19T14:36:47.6555660Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2020-11-19T14:36:47.6558248Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2020-11-19T14:36:47.6561289Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
2020-11-19T14:36:47.6564785Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-11-19T14:36:47.6568534Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
2020-11-19T14:36:47.6572236Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
2020-11-19T14:36:47.6575882Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
2020-11-19T14:36:47.6579139Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-11-19T14:36:47.6582400Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-11-19T14:36:47.6585684Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-11-19T14:36:47.6588307Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-11-19T14:36:47.6590952Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-11-19T14:36:47.6594407Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-11-19T14:36:47.6598000Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-11-19T14:36:47.6601270Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-11-19T14:36:47.6603229Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2020-11-19T14:36:47.6607134Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-11-19T14:36:47.6620001Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2020-11-19T14:36:47.6623286Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-11-19T14:36:47.6626878Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-11-19T14:36:47.6629536Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-11-19T14:36:47.6644707Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-11-19T14:36:47.6648220Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-11-19T14:36:47.6651846Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-11-19T14:36:47.6655505Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-11-19T14:36:47.6657528Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2020-11-19T14:36:47.6661309Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-11-19T14:36:47.6666102Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2020-11-19T14:36:47.6669406Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-11-19T14:36:47.6672687Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-11-19T14:36:47.6675487Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-11-19T14:36:47.6678160Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-11-19T14:36:47.6682856Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-11-19T14:36:47.6686506Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-11-19T14:36:47.6689787Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-11-19T14:36:47.6694415Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-11-19T14:36:47.6699577Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-11-19T14:36:47.6703642Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-11-19T14:36:47.6707300Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
2020-11-19T14:36:47.6710739Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
2020-11-19T14:36:47.6714313Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
2020-11-19T14:36:47.6718324Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
2020-11-19T14:36:47.6722296Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
2020-11-19T14:36:47.6725181Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
2020-11-19T14:36:47.6727507Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
2020-11-19T14:36:47.6757834Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
2020-11-19T14:36:47.6761619Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
2020-11-19T14:36:47.6765166Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
2020-11-19T14:36:47.6768186Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2020-11-19T14:36:47.6770609Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2020-11-19T14:36:47.6772611Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2020-11-19T14:36:47.6774510Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
2020-11-19T14:36:47.6775966Z Caused by: java.lang.AssertionError: 1 expectation failed.
2020-11-19T14:36:47.6776777Z Expected status code <200> but was <400>.
2020-11-19T14:36:47.6777116Z 
2020-11-19T14:36:47.6778597Z 	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor69.newInstance(Unknown Source)
2020-11-19T14:36:47.6782886Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2020-11-19T14:36:47.6788741Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2020-11-19T14:36:47.6792467Z 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
2020-11-19T14:36:47.6796772Z 	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
2020-11-19T14:36:47.6801283Z 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
2020-11-19T14:36:47.6805352Z 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
2020-11-19T14:36:47.6809962Z 	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:493)
2020-11-19T14:36:47.6812695Z 	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
2020-11-19T14:36:47.6815954Z 	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:674)
2020-11-19T14:36:47.6820049Z 	at jdk.internal.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
2020-11-19T14:36:47.6823701Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-19T14:36:47.6825724Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-19T14:36:47.6828618Z 	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
2020-11-19T14:36:47.6853600Z 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
2020-11-19T14:36:47.6857112Z 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
2020-11-19T14:36:47.6860517Z 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
2020-11-19T14:36:47.6863517Z 	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:126)
2020-11-19T14:36:47.6931186Z 	at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
2020-11-19T14:36:47.6960947Z 	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:134)
2020-11-19T14:36:47.6964270Z 	at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
2020-11-19T14:36:47.6967329Z 	at io.restassured.internal.ValidatableResponseImpl.super$2$statusCode(ValidatableResponseImpl.groovy)
2020-11-19T14:36:47.6969691Z 	at jdk.internal.reflect.GeneratedMethodAccessor141.invoke(Unknown Source)
2020-11-19T14:36:47.6972188Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-19T14:36:47.6974183Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-19T14:36:47.6975914Z 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
2020-11-19T14:36:47.6977601Z 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
2020-11-19T14:36:47.6979007Z 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1267)
2020-11-19T14:36:47.6981490Z 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
2020-11-19T14:36:47.6984681Z 	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy:142)
2020-11-19T14:36:47.6987477Z 	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
2020-11-19T14:36:47.6995354Z 	at io.quarkus.logging.gelf.it.GelfLogHandlerTest.lambda$test$0(GelfLogHandlerTest.java:65)
2020-11-19T14:36:47.6997646Z 	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
2020-11-19T14:36:47.6999452Z 	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
2020-11-19T14:36:47.7001210Z 	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
2020-11-19T14:36:47.7002733Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-11-19T14:36:47.7004475Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-11-19T14:36:47.7006450Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-19T14:36:47.7007747Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

https://pipelines.actions.githubusercontent.com/5Na9LjmLgXLiLuzJ0Z1qHRbIDVUXUHNrKe6jPcqGdw5t1S8TiW/_apis/pipelines/1/runs/84937/signedlogcontent/43?urlExpires=2020-11-19T16%3A07%3A14.5570782Z&urlSigningMethod=HMACV1&urlSignature=cYczWTWJ0ycVcEKHFuPUg1hup4gD6ZnMSQjLRt9qrnA%3D

**Comment by loicmathieu** [comment]
Duplicated with #13364

I'll increase the timeout and see if it solved the issue.
If not I'll disable the test for now waiting for a better solution.
