### ISSUE TITLE
Builds failing in vertx-http tests

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#13428]
I saw several builds failing in the ShutdownTest of Vert.x HTTP, all JDK 8 but it might be a coincidence:

```
 Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.089 s <<< FAILURE! - in io.quarkus.vertx.http.shutdown.ShutdownTest
Error:  io.quarkus.vertx.http.shutdown.ShutdownTest  Time elapsed: 15.089 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:162)
	at io.quarkus.vertx.http.shutdown.ShutdownTest$1.run(ShutdownTest.java:56)
	at io.quarkus.test.QuarkusUnitTest.afterAll(QuarkusUnitTest.java:518)
```

/cc @stuartwdouglas @cescoffier could if be related to the issue you have in Quarkus HTTP too?

**Comment by cescoffier** [comment]
That was fixed.
