### ISSUE TITLE
easyui js bug

### ISSUE THREAD

**Issue by weir2010** [quarkusio/quarkus#13446]
EasyUI for jQuery 1.9.10   
easyui/easyloader.js:

Caused by: java.lang.IllegalArgumentException: Not a virtual method: _1,locales:_2,base:".",theme:"default",css:true,locale:null,timeout:2000,load:function(_1f,_20){
if(/\.css$/i.test(_1f)){
if(/^http/i.test(_1f)){
_c(_1f,_20);
	at io.quarkus.qute.Expressions.parseVirtualMethodParams(Expressions.java:39)
	at io.quarkus.qute.Parser.createPart(Parser.java:718)
	at io.quarkus.qute.Parser.parseExpression(Parser.java:697)
	at io.quarkus.qute.Parser.apply(Parser.java:763)
	at io.quarkus.qute.Parser.flushTag(Parser.java:467)
	at io.quarkus.qute.Parser.tag(Parser.java:263)
	at io.quarkus.qute.Parser.processCharacter(Parser.java:176)

**Comment by geoand** [comment]
@weir2010 can you please provide more information? What does your template look like? Have you tried what is described [here](https://quarkus.io/guides/qute-reference#unparsed-character-data)?

**Comment by weir2010** [comment]
The program just added the JS of easyUI, and did not write the template, and then the startup program reported an error

**Comment by mkouba** [comment]
@weir2010 In that case, the `.js` file is very likely located in `src/main/resources/templates` but this directory is not intended to contain static files.

**Comment by weir2010** [comment]
@mkouba  https://github.com/weir2010/quarkus-demo.git        compile quarkus:dev     this is  error

**Comment by mkouba** [comment]
> @mkouba https://github.com/weir2010/quarkus-demo.git compile quarkus:dev this is error

Yes, that's exactly what I said. You should not place static resource files in the `src/main/resources/templates` directory. This directory should only contain templates. For static files use `META-INF/resources` instead (see https://quarkus.io/guides/http-reference#serving-static-resources).

We could eventually ignore hte files that do not match [quarkus.qute.suffixes](https://quarkus.io/guides/qute-reference#quarkus-qute_quarkus.qute.suffixes) but even then we would have to serve these static files somehow.

**Comment by weir2010** [comment]
@mkouba thanks
