### ISSUE TITLE
RestAssured tests need ObjectMapperType for JSON-B not for Jackson

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#13459]
**Description**

When doing a RESTAssured test on a POST, we need to set the `ObjectMapperType` when using JSON-B. It would be nice to have it optional like for Jackson.

Let's say you have a `Foo` class:

```
public class Foo {
    public String bar;
}
```

And a REST endpoint that consumes a `Foo` in a JSON format:

```
@Path("/resteasy/hello")
public class ExampleResource {

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    public void hello(Foo foo) {
        System.out.println(foo);
    }
}
```

**Jackson**

With Jackson (`quarkus-resteasy-jackson` dependency), we can test the endpoint either specifying the `ObjectMapperType` or not. So both tests below work:

```
@Test
public void postHelloEndpoint() {
    Foo foo = new Foo();
    foo.bar = "baz";

    given()
        .body(foo)
        .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON).
    when()
        .post("/resteasy/hello").
    then()
        .statusCode(204);
}
```

```
@Test
public void postHelloEndpoint() {
    Foo foo = new Foo();
    foo.bar = "baz";

    given()
        .body(foo, ObjectMapperType.JACKSON_2)
        .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON).
    when()
        .post("/resteasy/hello").
    then()
        .statusCode(204);
}
```

**JSON-B**

With JSON-B (`quarkus-resteasy-jsonb` dependency) you need to specify the `ObjectMapperType.JSONB`, if not, the serialization uses XML instead of JSON and you get the following exception:

```
javax.xml.bind.MarshalException
        at org.acme.ExampleResourceTest.postHelloEndpoint(ExampleResourceTest.java:20)
Caused by: com.sun.istack.SAXException2: unable to marshal type "org.acme.Foo" as an element because it is missing an @XmlRootElement annotation
        at org.acme.ExampleResourceTest.postHelloEndpoint(ExampleResourceTest.java:20)

```

It would be good to not have to specify `ObjectMapperType.JSONB` when using JSON-B

**Comment by gsmet** [comment]
Isn't it more an issue in REST Assured? I don't see how it could be a Quarkus problem?

**Comment by geoand** [comment]
We can probably set that under the covers if necessary

**Comment by agoncal** [comment]
In the [RESTAssured documentation](https://github.com/rest-assured/rest-assured/wiki/Usage#content-type-based-serialization), it's written:

> REST Assured will serialize the object to JSON since the request content-type is set to "application/json". It will first try to use Jackson if found in classpath and if not Gson will be used. If you change the content-type to "application/xml" REST Assured will serialize to XML using JAXB. If no content-type is defined REST Assured will try to serialize in the following order:
. JSON using Jackson 2 (Faster Jackson (databind))
. JSON using Jackson (databind)
. JSON using Gson
. JSON using Johnzon
. JSON-B using Eclipse Yasson
. XML using JAXB

As for the use of `ObjectMapperType` the [RESTAssured documentation ](https://github.com/rest-assured/rest-assured/wiki/Usage#using-an-explicit-deserializer) says:

> If you have multiple object mappers in the classpath at the same time or don't care about the response content-type you can specify a deserializer explicitly.

And the [ObjectMapperResolver](https://github.com/rest-assured/rest-assured/blob/master/rest-assured-common/src/main/java/io/restassured/common/mapper/resolver/ObjectMapperResolver.java#L27) in RESTAssured looks for Yasson in the classpath, which is the case, and creates a [JSONB mapper](https://github.com/rest-assured/rest-assured/blob/master/json-path/src/main/groovy/io/restassured/internal/path/json/mapping/JsonObjectDeserializer.groovy#L92).

In the [RESTAssured Changelog](https://github.com/rest-assured/rest-assured/blob/master/changelog.txt#L75) it's written:

> To use Yasson simply in your classpath and then configure REST Assured to use it as its default ObjectMapperType:

```
RestAssured.config = RestAssured.config.objectMapperConfig(ObjectMapperConfig.objectMapperConfig().defaultObjectMapperType(ObjectMapperType.JSONB));
```

So I wonder if Quarkus shouldn't configure it. Are you doing something specific with Jackson ?

**Comment by geoand** [comment]
AFAIR, we don't configure any of RestAssured's json settings. We only configure http related settings

**Comment by agoncal** [comment]
I was having a look at the RESTAssured samples, and I don't see any differences between Jackson and JSon-B configuration (expect that Jackson is the number one choice). Weird, it should work the same.

Well, either Quarkus can configure it.... or you can close this issue but maybe add something on the documentation. In the [testing guide](https://quarkus.io/guides/getting-started-testing) there is no `.post` examples, only `.get`. And this exception happens with POST and PUT. So what about adding an example in the test documentation ?

**Comment by geoand** [comment]
More documentation is always welcome :).

Would you like to contribute that (you had to see that one coming :laughing:)?

**Comment by agoncal** [comment]
@geoand Yes, I saw that one coming ;o)

You can assign this issue to me if you want (and maybe change the tag to documentation or something like that ?)

**Comment by geoand** [comment]
Done :)

**Comment by RuiPinhoErate** [comment]
Hi, Is this issue fixed? I'm experiencing it too with a POST using ObjectMapperType.JACKSON_2

**Comment by erik-wramner** [comment]
If the code uses custom Jsonb adapters, the adapters work in Quarkus but not in RESTAssured in the unit tests (oddly enough). I solved that with:

```
    @BeforeAll
    static void configureRestAssured() {
        RestAssured.config = RestAssured.config().objectMapperConfig(
                ObjectMapperConfig.objectMapperConfig().jsonbObjectMapperFactory(new JsonbObjectMapperFactory() {
                    @Override
                    public Jsonb create(Type cls, String charset) {
                        return JsonbBuilder.create(JsonbAdapters.registerAdapters(new JsonbConfig()));
                    }
                }));
    }

```
where JsonbAdapters is one of my classes, which simply calls withAdapters on the config. Perhaps this can save time for someone else.
