### ISSUE TITLE
java.lang.NoClassDefFoundError: org/springframework/expression/spel/SpelEvaluationException

### ISSUE THREAD

**Issue by tassadar81** [quarkusio/quarkus#13495]
Hello guys, i'm meeting an error during startup of my quarkus app launching it with **java -jar command** but di doesn't happens through **maven quarkus:dev**. Someone can help me?

Exception in thread "main" java.lang.ExceptionInInitializerError
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at java.base/java.lang.Class.newInstance(Class.java:584)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.lang.RuntimeException: Failed to start quarkus
at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:282)
... 9 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/expression/spel/SpelEvaluationException
at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3192)
at java.base/java.lang.Class.getMethods(Class.java:1905)
at org.jboss.resteasy.spi.metadata.ResourceBuilder.fromAnnotations(ResourceBuilder.java:908)
at org.jboss.resteasy.spi.metadata.ResourceBuilder.getRootResourceFromAnnotations(ResourceBuilder.java:878)
at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.<init>(POJOResourceFactory.java:41)
at org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:87)
at org.jboss.resteasy.core.ResteasyDeploymentImpl.registerResources(ResteasyDeploymentImpl.java:515)
at org.jboss.resteasy.core.ResteasyDeploymentImpl.registration(ResteasyDeploymentImpl.java:472)
at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:162)
at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:118)
at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.staticInit(ResteasyStandaloneRecorder.java:71)
at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit-210558872.deploy_0(ResteasyStandaloneBuildStep$staticInit-210558872.zig:918)
at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit-210558872.deploy(ResteasyStandaloneBuildStep$staticInit-210558872.zig:40)
at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:262)
... 9 more
Caused by: java.lang.ClassNotFoundException: org.springframework.expression.spel.SpelEvaluationException
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
... 25 more

i'm using quarkus 1.9.2 and this is my java version:

openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

**Comment by geoand** [comment]
What does your `pom.xml` look like?

**Comment by tassadar81** [comment]
@geoand do you need the whole pom? It doesn't include any spring library explicity. I just wonder why launching with quarkus:dev it works

**Comment by geoand** [comment]
Does it however include any libraries that bring in spring transitively?

An `mvn dependency:tree` would show that.

**Comment by tassadar81** [comment]
i tried adding this:

<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-expression</artifactId>
    <version>5.3.1</version>
</dependency>

and the problem disappeared, so i guess that i've a library that need this one. I close this issue as it's my problem. Still wonder why quarkus:dev doesn't report this

**Comment by gsmet** [comment]
@tassadar81 are you using our Spring compatibility layer? If so, I think it would be interesting for us to have a reproducer.

**Comment by tassadar81** [comment]
> 
> 
> @tassadar81 are you using our Spring compatibility layer? If so, I think it would be interesting for us to have a reproducer.

@gsmet no, simply i'm working on a project and a collegue added a library with a transitive dependency to spring-expression. Sorry for the invalid report.
