### ISSUE TITLE
Kafka Streams with avro serde not working in native mode

### ISSUE THREAD

**Issue by KMUS** [quarkusio/quarkus#13533]
Building a Kafka streams application with avro serializer not working in native mode. In JVM mode everything works fine.

Quarkus version 1.10.1

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jsonb</artifactId>
        </dependency>               
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kafka-streams</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-avro</artifactId>
        </dependency> 
        <dependency>
            <groupId>org.apache.avro</groupId>
            <artifactId>avro</artifactId>
        </dependency>   
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>kafka-streams-avro-serde</artifactId>
            <version>6.0.0</version>
        </dependency>                  
        <dependency>
            <groupId>jakarta.security.jacc</groupId>
            <artifactId>jakarta.security.jacc-api</artifactId>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
        </dependency>

    @Produces
    public Topology buildTopology(Bar transformer) {
        var builder = new StreamsBuilder();
        var branches = builder
            .stream(INPUT_TOPIC, Consumed.with(Serdes.String(), new JsonbSerde<>(RawProtocol.class)))
            ...
            .branch((k, v) -> true);

        Serde<Foo> foo = new SpecificAvroSerde<>();

        Map<String, String> serdeConfig = new HashMap<>();
        serdeConfig.put(SCHEMA_REGISTRY_URL_CONFIG, "http://localhost:18081");
        foo.configure(serdeConfig, false);

        branches[0].to(OUTPUT_TOPIC, Produced.with(Serdes.String(), foo()));
    }

```
2020-11-28 13:54:47,731 ERROR [org.apa.kaf.str.pro.int.AssignedStreamsTasks] (service-parser-test-native-ec7d169e-1b34-4965-ae4e-0cbbd234382b-StreamThread-1) stream-thread [service-parser-test-native-ec7d169e-1b34-4965-ae4e-0cbbd234382b-StreamThread-1] Failed to process stream task 0_0 due to the following error:: org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000000, topic=raw, partition=0, offset=241766643, stacktrace=org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:129)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:96)
	at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:72)
	at javax.ws.rs.core.UriBuilder.fromPath(UriBuilder.java:125)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:492)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:486)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:459)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:206)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:268)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:244)
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:75)
	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:59)
	at io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer.serialize(SpecificAvroSerializer.java:65)
	at io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer.serialize(SpecificAvroSerializer.java:38)
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:176)
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:111)
	at org.apache.kafka.streams.processor.internals.SinkNode.process(SinkNode.java:89)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.PassThrough$PassThroughProcessor.process(PassThrough.java:33)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:188)
	at org.apache.kafka.streams.kstream.internals.KStreamBranch$KStreamBranchProcessor.process(KStreamBranch.java:48)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamFlatTransform$KStreamFlatTransformProcessor.process(KStreamFlatTransform.java:59)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:101)
	at org.apache.kafka.streams.processor.internals.StreamTask.lambda$process$3(StreamTask.java:383)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:383)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:475)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:550)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:802)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1214)
	at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:87)
	at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:185)
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:111)
	... 51 more
```

**Comment by ntnhan94** [comment]
I have the same issue. Can not find out a workaround...

**Comment by gsmet** [comment]
@cescoffier have you tested Kafka Streams with Avro?

**Comment by ngtampl94** [comment]
Workaround: Let try to add a REST Resource using quarkus-resteasy (jax-rs). The resource look like this:

        package com.testing.controller;
        
        import javax.ws.rs.GET;
        import javax.ws.rs.Path;
        import javax.ws.rs.Produces;
        import javax.ws.rs.core.MediaType;
        
        @Path("/hello")
        public class GreetingResource {
        
            @GET
            @Produces(MediaType.TEXT_PLAIN)
            public String hello() {
                return "Hello RESTEasy";
            }
        }

Not sure what happened but looks like the "org.glassfish.jersey.internal.RuntimeDelegateImpl" has been loaded by this REST Resource and so it solves the issue.

It works for me. So let try and see.

**Comment by gunnarmorling** [comment]
Instead of using `SpecificAvroSerde`, could you please try the Apicurio serializer as described [here](https://quarkus.io/blog/kafka-avro/). This should be supported in native mode, too.

**Comment by ntnhan94** [comment]
Hi @gunnarmorling 

Because of some reasons, we have to use io.confluent . Will Confluent Avro Serializer be officially supported in native mode in the near future?
I think the workaround mentioned by @ngtampl94 is a clue to have some quick fixes..

**Comment by cescoffier** [comment]
@gsmet no I didn't tested with Kafka streams, but we tested with the underlying client, so should not be an issue. 

We have worked with the apicurio team to work in native. You can use this serde with the confluent schéma registry. 

The confluent serde in native mode is more tricky.

**Comment by gunnarmorling** [comment]
As I just learned from @EricWittmann, the Apicurio SerDe *cannot* be used with the Confluent registry (the other way around though works: using Confluent's SerDe with the Apicurio registry). Seems atm. the only way that works in native is Apicurio SerDe with Apicurio registry then. Or someone would have to figure out the right substitutions etc. for the Confluent Serde.

**Comment by cescoffier** [comment]
@gunnarmorling Oh! My bad. I was thinking it was possible.

**Comment by cescoffier** [comment]
Just saw @ngtampl94's comment. So basically, you need RESTEasy, because it registers the RestClient (which Confluent Serde is using). That's a bit better than trying to substitute part of the serde itself.

**Comment by cescoffier** [comment]
We may be able to track the right bean and if the Confluent Serde is used, make it unremovable. However, having the Avro extension depending on RESTEasy is not great.

**Comment by cescoffier** [comment]
@KMUS @ntnhan94 Can you try adding the quarkus-rest-client extension and remove the resteasy extension and "fake" JAX-RS resource? 

If that fixes it, we can easily detect that at build time and ask the user to add the extension explicitly.

**Comment by gunnarmorling** [comment]
Clement, can one have the non-Reactive REST client and Reactive RestEasy in
one app?

>

**Comment by ngtampl94** [comment]
Hi @cescoffier,

The issue was fixed when I **added quarkus-rest-client** extension and **removed the resteasy** extension and "fake" JAX-RS resource.
Many thanks for your help.

**Comment by cescoffier** [comment]
@gunnarmorling it should work, do you see an issue? Soon we will have the reactive client for RestEasy reactive

**Comment by gunnarmorling** [comment]
> do you see an issue?

No, none specifically. Just was wondering whether it'd be a problem, as you cannot mix RestEasy and RestEasy Reactive (Serving components).

**Comment by cescoffier** [comment]
Closed, the `quarkus-rest-client` extension was missing.
