### ISSUE TITLE
default package breaks @Scheduled

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#13540]
**Describe the bug**
when having code class with out a package used with `@Scheduled` errors.

```java
//usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.quarkus:quarkus-scheduler:1.9.2.Final
//JAVA_OPTIONS -Dquarkus.http.port=8082
//JAVA_OPTIONS -Djava.util.logging.manager=org.jboss.logmanager.LogManager

//package com.att.sapmp.services.events;

import java.util.logging.Logger;

import javax.enterprise.context.ApplicationScoped;

import io.quarkus.scheduler.Scheduled;

import io.quarkus.runtime.Quarkus;

/**
 * A bean producing random prices every 5 seconds. The prices are written to a
 * Kafka topic (prices). The Kafka configuration is specified in the application
 * configuration.
 */
@ApplicationScoped
public class Jbang_Quarkus_Scheduler {
    static final Logger LOGGER = Logger.getLogger("Jbang_Quarkus_Scheduler");

 @Scheduled(every="10s")     
    void scheduledLog() {
        LOGGER.info("10s Tick");
    }

}
```

gives errors like: 

```
Caused by: java.nio.file.FileSystemException: /Jbang_Quarkus_Scheduler_ScheduledInvoker_scheduledLog_4592414c73f13a2e41bdf89dccc9abe064eef0d7.class: Read-only file system
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
at dev.jbang.IntegrationManager.runIntegration(IntegrationManager.java:118)
... 14 more
```

notice how it is trying to write to root filesystem indicating bad assumption about there always being a package.

**Expected behavior**
should not fail due to default package.

**Comment by maxandersen** [comment]
repoted originally in jbang at https://github.com/jbangdev/jbang/issues/561

**Comment by mkouba** [comment]
Although it's legal to use the default package in any Java app I don't believe there is any _legal_ use case other than jbang ;-).

**Comment by maxandersen** [comment]
> Although it's legal to use the default package in any Java app I don't believe there is any _valid_ use case other than jbang ;-).

**Comment by gsmet** [comment]
Why is it closed? I see the PR here is still open: https://github.com/quarkusio/quarkus/pull/13541 ?

**Comment by maxandersen** [comment]
Good question. For some reason I thought this was merged :/

**Comment by mkouba** [comment]
This should be fixed by https://github.com/quarkusio/quarkus/pull/14839.
