### ISSUE TITLE
Quarkus quarkusBuild failing when gradle buildSrc dependency 

### ISSUE THREAD

**Issue by JuanCamiloRada** [quarkusio/quarkus#13579]
**Describe the bug**
quarkusBuild fail with error  

```
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingStaticInit threw an exception: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:150)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:203)
        at io.quarkus.deployment.proxy.ProxyFactory.doDefineClass(ProxyFactory.java:189)
        at io.quarkus.deployment.proxy.ProxyFactory.defineClass(ProxyFactory.java:120)
        at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:204)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:301)
        at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFrom$85(ExtensionLoader.java:763)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  
        [error]: Build step io.quarkus.vertx.core.deployment.VertxCoreProcessor#ioThreadDetector threw an exception: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:150)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:203)
        at io.quarkus.deployment.proxy.ProxyFactory.doDefineClass(ProxyFactory.java:189)
        at io.quarkus.deployment.proxy.ProxyFactory.defineClass(ProxyFactory.java:120)
        at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:204)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:301)
        at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFrom$85(ExtensionLoader.java:763)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  
        [error]: Build step io.quarkus.vertx.http.deployment.HttpSecurityProcessor#initBasicAuth threw an exception: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:150)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:203)
        at io.quarkus.deployment.proxy.ProxyFactory.doDefineClass(ProxyFactory.java:189)
        at io.quarkus.deployment.proxy.ProxyFactory.defineClass(ProxyFactory.java:120)
        at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:204)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:301)
        at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFrom$85(ExtensionLoader.java:763)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  
        [error]: Build step io.quarkus.deployment.steps.ConfigBuildSteps#generateConfigSources threw an exception: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:150)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:203)
        at io.quarkus.deployment.steps.ConfigBuildSteps.generateConfigSources(ConfigBuildSteps.java:71)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  
        [error]: Build step io.quarkus.jsonb.deployment.JsonbProcessor#generateCustomizer threw an exception: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:150)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:203)
        at io.quarkus.jsonb.deployment.JsonbProcessor.generateCustomizer(JsonbProcessor.java:190)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  
        [error]: Build step io.quarkus.deployment.logging.LoggingResourceProcessor#registerMetrics threw an exception: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:150)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:203)
        at io.quarkus.deployment.proxy.ProxyFactory.doDefineClass(ProxyFactory.java:189)
        at io.quarkus.deployment.proxy.ProxyFactory.defineClass(ProxyFactory.java:120)
        at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:204)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:301)
        at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFrom$85(ExtensionLoader.java:763)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  
        [error]: Build step io.quarkus.vertx.http.deployment.HttpSecurityProcessor#initMtlsClientAuth threw an exception: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:150)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:203)
        at io.quarkus.deployment.proxy.ProxyFactory.doDefineClass(ProxyFactory.java:189)
        at io.quarkus.deployment.proxy.ProxyFactory.defineClass(ProxyFactory.java:120)
        at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:204)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:301)
        at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFrom$85(ExtensionLoader.java:763)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  
        [error]: Build step io.quarkus.netty.deployment.NettyProcessor#eagerlyInitClass threw an exception: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:150)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:203)
        at io.quarkus.deployment.proxy.ProxyFactory.doDefineClass(ProxyFactory.java:189)
        at io.quarkus.deployment.proxy.ProxyFactory.defineClass(ProxyFactory.java:120)
        at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:204)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:301)
        at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFrom$85(ExtensionLoader.java:763)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  
        [error]: Build step io.quarkus.deployment.steps.BootstrapConfigSetupBuildStep#setupBootstrapConfig threw an exception: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:150)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:203)
        at io.quarkus.deployment.steps.BootstrapConfigSetupBuildStep.setupBootstrapConfig(BootstrapConfigSetupBuildStep.java:44)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
  
        [error]: Build step io.quarkus.vertx.http.deployment.HttpSecurityProcessor#setupAuthenticationMechanisms threw an exception: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:150)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:203)
        at io.quarkus.deployment.proxy.ProxyFactory.doDefineClass(ProxyFactory.java:189)
        at io.quarkus.deployment.proxy.ProxyFactory.defineClass(ProxyFactory.java:120)
        at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:204)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:301)
        at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFrom$85(ExtensionLoader.java:763)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

```

**Expected behavior**
quarkusBuild to success

**Actual behavior**
quarkusBuild always fail with the same error

**To Reproduce**
1. Extract sample project [my-artifactId.zip](https://github.com/quarkusio/quarkus/files/5621570/my-artifactId.zip)
2. Execute `./gradlew app:quarkusBuild`

**Notice that**
If dependency "com.jayway.jsonpath:json-path:2.4.0" is removed in `buildSrc/build.gradle` build success but buildSrc dependencies should not affect quarkus project.

**Comment by glefloch** [comment]
This is really weird, I can reproduce the error but when inspecting dependencies, I can't any difference in what we build

**Comment by glefloch** [comment]
Ok, it seems to only happen on `quarkusBuild`, it seems that the `classLoader()` is polluted by `buildSrc` dependencies
