### ISSUE TITLE
javax.ws.rs.ProcessingException: RESTEASY008200 when using Json-B and sending an invalid UUID

### ISSUE THREAD

**Issue by languitar** [quarkusio/quarkus#13588]
**Describe the bug**

I have a REST service that expects a UUID in a post payload. That service is using resteasy-jsonb. When sending an invalid UUID string representation, the current exception is not a `ValidationException` and results in a 500.

**Expected behavior**

An instance of `ValidationException` is thrown.

**Actual behavior**

```
javax.ws.rs.ProcessingException: RESTEASY008200: JSON Binding deserialization error: javax.json.bind.JsonbException: Internal error: UUID string too large
	at org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider.readFrom(JsonBindingProvider.java:81)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:101)
	at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:63)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:80)
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:213)
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:95)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:128)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:131)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.json.bind.JsonbException: Internal error: UUID string too large
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:68)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:51)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:59)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:99)
	at org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider.readFrom(JsonBindingProvider.java:73)
	... 35 more
Caused by: java.lang.IllegalArgumentException: UUID string too large
	at java.base/java.util.UUID.fromString(UUID.java:200)
	at org.eclipse.yasson.internal.serializer.UUIDTypeDeserializer.deserialize(UUIDTypeDeserializer.java:37)
	at org.eclipse.yasson.internal.serializer.UUIDTypeDeserializer.deserialize(UUIDTypeDeserializer.java:24)
	at org.eclipse.yasson.internal.serializer.AbstractValueTypeDeserializer.deserialize(AbstractValueTypeDeserializer.java:64)
	at org.eclipse.yasson.internal.serializer.ObjectDeserializer.deserializeNext(ObjectDeserializer.java:180)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserializeInternal(AbstractContainerDeserializer.java:94)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:64)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:62)
	... 39 more
```

**To Reproduce**

This is a the stripped down data type that I use:
```java
@io.quarkus.runtime.annotations.RegisterForReflection
public class MinimalComment {

  public @Valid UUID uuid = null;

  /** Primary ID of the comment */
  public MinimalComment uuid(UUID uuid) {
    this.uuid = uuid;
    return this;
  }

  @JsonbProperty("uuid")
  public UUID getUuid() {
    return uuid;
  }

  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }

}
```

The resource interface for one of the affected methods is:

```java
@Path("/comments")
@javax.enterprise.context.ApplicationScoped
public interface CommentsRestResource {

  @POST
  @Consumes({"application/json"})
  @Produces({"application/json", "application/problem+json"})
  ValidComment createComment(@Valid MinimalComment body);

}
```

The exception appears when POSTing:

```json
{
  "product": "3fa85f64-5717-4562-b3fc-2c963f66afa6asdftoolong"
}
```
The resulting status code is 500 and not as expected 400

**Configuration**

None regarding data mapping and JSON.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux pres 5.9.10-arch1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 14:16:59 +0000 x86_64 GNU/Linux`
 - Output of `java -version`:
      ```
      Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true    -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
      openjdk version "14.0.2" 2020-07-14
      OpenJDK Runtime Environment (build 14.0.2+12)
      OpenJDK 64-Bit Server VM (build 14.0.2+12, mixed mode)
      ```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.9.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):
      ```
      Apache Maven 3.6.3 (NON-CANONICAL_2019-11-27T20:26:29Z_root)
      Maven home: /opt/maven
      Java version: 14.0.2, vendor: N/A, runtime: /usr/lib/jvm/java-14-openjdk
      Default locale: en_US, platform encoding: UTF-8
      OS name: "linux", version: "5.9.10-arch1-1", arch: "amd64", family: "unix"
      ```

**Additional context**
(Add any other context about the problem here.)

**Comment by languitar** [comment]
Maybe related: this also happens with Jackson. I have opened an issue for the resteasy implementation: https://issues.redhat.com/browse/RESTEASY-2784

**Comment by geoand** [comment]
Is this still an issue?

**Comment by languitar** [comment]
I can't tell. I am out of that project since a longer time.

**Comment by geoand** [comment]
Thanks for the update. 

I'll close for now and we can reconsider if new information becomes available

**Comment by jheyd** [comment]
Still seeing this on Quarkus 3.35.3 using `quarkus-rest-jsonb`.

<details>

<summary>Logs</summary>

```
java.lang.IllegalArgumentException: Invalid UUID string: 
    at java.util.UUID.fromString1(UUID.java:280)
    at java.util.UUID.fromString(UUID.java:258)
    at org.eclipse.yasson.internal.deserializer.types.UuidDeserializer.deserializeStringValue(UuidDeserializer.java:31)
    at org.eclipse.yasson.internal.deserializer.types.TypeDeserializer.deserialize(TypeDeserializer.java:37)
    at org.eclipse.yasson.internal.deserializer.ValueExtractor.deserialize(ValueExtractor.java:47)
    at org.eclipse.yasson.internal.deserializer.ValueExtractor.deserialize(ValueExtractor.java:24)
    at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:85)
    at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:34)
    at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:46)
    at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:26)
    at org.eclipse.yasson.internal.deserializer.JsonbCreatorDeserializer.deserialize(JsonbCreatorDeserializer.java:86)
    at org.eclipse.yasson.internal.deserializer.JsonbCreatorDeserializer.deserialize(JsonbCreatorDeserializer.java:38)
    at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:85)
    at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:34)
    at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:46)
    at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:26)
    at org.eclipse.yasson.internal.DeserializationContextImpl.deserializeItem(DeserializationContextImpl.java:138)
    at org.eclipse.yasson.internal.DeserializationContextImpl.deserialize(DeserializationContextImpl.java:127)
    at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:55)
    at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:102)
    at org.jboss.resteasy.reactive.server.jsonb.JsonbMessageBodyReader.doReadFrom(JsonbMessageBodyReader.java:57)
    at org.jboss.resteasy.reactive.server.jsonb.JsonbMessageBodyReader.readFrom(JsonbMessageBodyReader.java:39)
    at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:126)
    at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:84)
    at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:184)
    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
    at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
    at java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:291)
    at java.lang.VirtualThread.run(VirtualThread.java:456)

jakarta.json.bind.JsonbException: Internal error: Invalid UUID string: 
    at org.eclipse.yasson.internal.DeserializationContextImpl.deserializeItem(DeserializationContextImpl.java:142)
    at org.eclipse.yasson.internal.DeserializationContextImpl.deserialize(DeserializationContextImpl.java:127)
    at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:55)
    at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:102)
    at org.jboss.resteasy.reactive.server.jsonb.JsonbMessageBodyReader.doReadFrom(JsonbMessageBodyReader.java:57)
    at org.jboss.resteasy.reactive.server.jsonb.JsonbMessageBodyReader.readFrom(JsonbMessageBodyReader.java:39)
    at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:126)
    at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:84)
    at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:184)
    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
    at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
    at java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:291)
    at java.lang.VirtualThread.run(VirtualThread.java:456)
```

</details>
