### ISSUE TITLE
AWS Lambda Funqy @Transaction Exception

### ISSUE THREAD

**Issue by EzxD** [quarkusio/quarkus#13606]
**Describe the bug**
I deploy following [app](https://github.com/EzxD/Quarkus-Funqy-Native-Example) to aws lambda with the createUser function.
Running in jvm no issues
Running native I get following stacktrace:

```
START RequestId: 37b5af50-face-40b4-bf64-95f8fbc9730f Version: $LATEST
__  ____  __  _____   ___  __ ____  ______ 
--/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
-/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-12-01 21:06:42,504 INFO  [io.quarkus] (main) serverless 1.0-SNAPSHOT native (powered by Quarkus 1.10.1.Final) started in 0.185s. Listening on: http://0.0.0.0:8080
2020-12-01 21:06:42,504 INFO  [io.quarkus] (main) Profile prod activated. 
2020-12-01 21:06:42,504 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, funqy-amazon-lambda, funqy-http, hibernate-orm, hibernate-orm-panache, hibernate-validator, jdbc-h2, mutiny, narayana-jta, smallrye-context-propagation]
UserDTO(id=null, username=value1)
2020-12-01 21:06:42,666 WARN  [com.arj.ats.common] (Lambda Thread) ARJUNA048004: attempt to load com.arjuna.ats.internal.arjuna.utils.SocketProcessId threw ClassNotFound. Wrong classloader?: java.lang.ClassNotFoundException: com.arjuna.ats.internal.arjuna.utils.SocketProcessId
at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
at java.lang.Class.forName(DynamicHub.java:1214)
at com.arjuna.common.internal.util.ClassloadingUtility.loadClass(ClassloadingUtility.java:57)
at com.arjuna.common.internal.util.ClassloadingUtility.loadClass(ClassloadingUtility.java:85)
at com.arjuna.common.internal.util.ClassloadingUtility.loadAndInstantiateClass(ClassloadingUtility.java:117)
at com.arjuna.ats.arjuna.common.CoreEnvironmentBean.getProcessImplementation(CoreEnvironmentBean.java:232)
at com.arjuna.ats.arjuna.utils.Utility.initDefaultProcess(Utility.java:329)
at com.arjuna.ats.arjuna.utils.Utility.getProcess(Utility.java:340)
at com.arjuna.ats.arjuna.utils.Utility.getpid(Utility.java:285)
at com.arjuna.ats.arjuna.common.Uid.<init>(Uid.java:79)
at com.arjuna.ats.arjuna.StateManager.<init>(StateManager.java:813)
at com.arjuna.ats.arjuna.StateManager.<init>(StateManager.java:802)
at com.arjuna.ats.arjuna.coordinator.BasicAction.<init>(BasicAction.java:72)
at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.<init>(TwoPhaseCoordinator.java:55)
at com.arjuna.ats.arjuna.AtomicAction.<init>(AtomicAction.java:74)
at com.arjuna.ats.internal.jta.transaction.arjunacore.AtomicAction.<init>(AtomicAction.java:38)
at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.<init>(TransactionImple.java:101)
at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.begin(BaseTransaction.java:98)
at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.begin(CDIDelegatingTransactionManager.java:74)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:114)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
at de.stvehb.example.serverless.service.UserService_Subclass.createUser(UserService_Subclass.zig:168)
at de.stvehb.example.serverless.service.UserService_ClientProxy.createUser(UserService_ClientProxy.zig:157)
at de.stvehb.example.serverless.function.UserFunction.createUser(UserFunction.java:18)
at de.stvehb.example.serverless.function.UserFunction_Subclass.createUser$$superaccessor1(UserFunction_Subclass.zig:199)
at de.stvehb.example.serverless.function.UserFunction_Subclass$$function$$1.apply(UserFunction_Subclass$$function$$1.zig:33)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:69)
at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation(MethodValidationInterceptor.java:17)
at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept(MethodValidationInterceptor_Bean.zig:341)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
at de.stvehb.example.serverless.function.UserFunction_Subclass.createUser(UserFunction_Subclass.zig:156)
at java.lang.reflect.Method.invoke(Method.java:566)
at io.quarkus.funqy.runtime.FunctionInvoker.invoke(FunctionInvoker.java:126)
at io.quarkus.funqy.lambda.FunqyLambdaBindingRecorder.dispatch(FunqyLambdaBindingRecorder.java:144)
at io.quarkus.funqy.lambda.FunqyLambdaBindingRecorder.access$000(FunqyLambdaBindingRecorder.java:32)
at io.quarkus.funqy.lambda.FunqyLambdaBindingRecorder$1.processRequest(FunqyLambdaBindingRecorder.java:109)
at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:79)
at java.lang.Thread.run(Thread.java:834)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
2020-12-01 21:06:42,686 WARN  [com.arj.ats.arjuna] (Lambda Thread) ARJUNA012209: Utility.getDefaultProcess failed
END RequestId: 37b5af50-face-40b4-bf64-95f8fbc9730f
REPORT RequestId: 37b5af50-face-40b4-bf64-95f8fbc9730f	Duration: 198.76 ms	Billed Duration: 499 ms	Memory Size: 256 MB	Max Memory Used: 73 MB	Init Duration: 299.75 ms	```

**Expected behavior**
works without error?

**Actual behavior**
Throws a class not found exception


**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

Steps to reproduce the behavior:
1. mvn package -Pnative -Dquarkus.native.container-build=true
2. ./target/manage.sh native create
3. send test from AWS get a nice stacktrace

**Configuration**
```properties
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.funqy.export=createUser
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux Pauls-PC 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
 - GraalVM version (if different from Java): openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
 - Quarkus version or git rev: https://github.com/EzxD/Quarkus-Funqy-Native-Example (quarkus verion 1.10.1.Final)
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /mnt/c/apache-maven-3.6.3
Java version: 11.0.9.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.19.128-microsoft-standard", arch: "amd64", family: "unix"

**Comment by EzxD** [comment]
Seems like an error according to ``	@Transactional`` because the dto get`s printed

**Comment by gsmet** [comment]
I wonder if it's related to https://github.com/quarkusio/quarkus/pull/13088 .

Could you try with latest master?

You can follow the instructions here: https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#checking-an-issue-is-fixed-in-master .

**Comment by EzxD** [comment]
Its working without an error
