### ISSUE TITLE
Constraints on Optional value throw java.lang.IllegalArgumentException: Not a parameterized type!

### ISSUE THREAD

**Issue by stevefavez** [quarkusio/quarkus#13623]
**Describe the bug**
I'm trying to add a constraint on an Optional attribute in a Bean. My understanding is that if the attribute is empty it's ok, otherwise, validation is performed on the value. According to spec, I'm supposed to add it like this : 

```java
@Default
Optional<@Size(max = 10) String> optionalMessage = Optional.empty() ;
```
please see the following attachement for all the code sample : [mytest.zip](https://github.com/quarkusio/quarkus/files/5629380/mytest.zip)

But when performing mvn clean packge, I got the following errors : 
```java
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.53 s <<< FAILURE! - in ch.vs.tst.MySampleTest
[ERROR] testHelloEndpoint  Time elapsed: 0 s  <<< ERROR!
java.lang.RuntimeException:
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.steps.ApplicationIndexBuildStep#build threw an exception: java.lang.IllegalArgumentException: Not a parameterized type!
        at org.jboss.jandex.Type.asParameterizedType(Type.java:228)
        at org.jboss.jandex.Indexer.resolveTypePath(Indexer.java:768)
        at org.jboss.jandex.Indexer.resolveTypeAnnotation(Indexer.java:728)
        at org.jboss.jandex.Indexer.resolveTypeAnnotations(Indexer.java:613)
        at org.jboss.jandex.Indexer.index(Indexer.java:1606)
        at io.quarkus.deployment.steps.ApplicationIndexBuildStep$1.visitFile(ApplicationIndexBuildStep.java:38)
        at io.quarkus.deployment.steps.ApplicationIndexBuildStep$1.visitFile(ApplicationIndexBuildStep.java:27)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at io.quarkus.deployment.steps.ApplicationIndexBuildStep.build(ApplicationIndexBuildStep.java:27)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Expected behavior**
According to some documentation, (https://www.baeldung.com/bean-validation-container-elements#optional-values), it's supposed to work like that

**To Reproduce**

[mytest.zip](https://github.com/quarkusio/quarkus/files/5629380/mytest.zip)
```bash
mvn clean package 
```

Even if you skip test, I'got exactly the same stack trace but when packaging.

Thanks for your hep.

**Comment by gsmet** [comment]
Sure looks like a bug. I'll have a look.

**Comment by gsmet** [comment]
This is due to the `setOptionalMessage()` method created by Lombok not playing well with Jandex.

We end up with a `@Size` annotation instance which is referenced as being attached to a parameterized type attached to a `EmptyTypeTarget` in Jandex. My decompiler doesn't show me the annotations so I don't really know where they are but I wonder if somehow Lombok incorrectly attaches the `@Size` annotation to the void return type when generating the setter.

Another option would be a Jandex bug.

@n1hility rings any bell?

**Comment by kkcmadhu** [comment]
i too have same issue while docker building keycloak on quarkus https://github.com/keycloak/keycloak/issues/25291

**Comment by marko-bekhta** [comment]
hey @gsmet
I've tried to reproduce this one using the reproducer from the original bug report:
- 1.10.2.Final (the version of the reproducer) - it is failing
- 1.13.7.Final - still failing
- 2.7.7.Final - still failing
- 2.13.9.Final - still failing
- 2.16.12.Final - not failing  anymore (switch to Jandex 3.0)
- 3.2.12.Final - not failing
- 3.8.5 - not failing (+need to update lombok version)
- 3.13.2 - not failing

so maybe we can close this one now? 
As for the comment about keycloack: that issue got close as it became stale, and no reproducer was provided there.

**Comment by gsmet** [comment]
Let's close then, thanks for having a look.
