### ISSUE TITLE
jwks path can not be read from property mp.jwt.verify.publickey.location, local and https

### ISSUE THREAD

**Issue by bobocu** [quarkusio/quarkus#13648]
**Describe the bug**
When setting in application properties:
mp.jwt.verify.publickey.location=META-INF/resources/key.jwks
or
mp.jwt.verify.publickey.location=https://www.googleapis.com/oauth2/v3/certs

the pem from googleapis can not be loaded.

**Expected behavior**
Expecting jwks to be loaded

**Actual behavior**
2020-12-03 00:33:50,297 DEBUG [org.jos.htt.Get] (vert.x-eventloop-thread-1) HTTP GET of https://www.googleapis.com/oauth2/v3/certs returned SimpleResponse{statusCode=200, statusMessage='OK', headers={null=[HTTP/1.1 200 OK], date=[Wed, 02 Dec 2020 23:33:14 GMT], server=[ESF], expires=[Thu, 03 Dec 2020 05:14:39 GMT], transfer-encoding=[chunked], vary=[Origin,Accept-Encoding, Referer, X-Origin], x-frame-options=[SAMEORIGIN], x-content-type-options=[nosniff], x-xss-protection=[0], content-type=[application/json; charset=UTF-8], alt-svc=[h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"], accept-ranges=[none], cache-control=[public, max-age=20485, must-revalidate, no-transform], age=[35]}, body='{
  "keys": [
    {
      "e": "AQAB",
      "alg": "RS256",
      "use": "sig",
      "kty": "RSA",
      "n": "syWuIlYmoWSl5rBQGOtYGwO5OCCZnhoWBCyl-x5gby5ofc4HNhBoVVMUggk-f_MH-pyMI5yRYsS_aPQ2bmSox2s4i9cPhxqtSAYMhTPwSwQ2BROC7xxi_N0ovp5Ivut5q8TwAn5kQZa_jR9d7JO20BUB7UqbMkBsqg2J8QTtMJ9YtA5BmUn4Y6vhIjTFtvrA6iM4i1cKoUD5Rirt5CYpcKwsLxBZbVk4E4rqgv7G0UlWt6NAs-z7XDkchlNBVpMUuiUBzxHl4LChc7dsWXRaO5vhu3j_2WnxuWCQZPlGoB51jD_ynZ027hhIcoa_tXg28_qb5Al78ZttiRCQDKueAQ",
      "kid": "2e3025f26b595f96eac907cc2b9471422bcaeb93"
    },
    {
      "kty": "RSA",
      "e": "AQAB",
      "alg": "RS256",
      "use": "sig",
      "n": "s44bQ6JmMh-9YBCyCdpbfslwFQ9mloCTgBiX3mwzrBUkliwBRBt5-jJKTXNz_IKERRf43grdSBb3mUiNwq-I6H6EHU0ueyiliGS38rTOrZSK9LM0qy-I8mSNc7p-5MA4Yu-gkBBfvicQ9GZfwlFZpoXt6UIVXywtvNuQNtRsx5oJ8PtbmMPCcA5aFkFl-8YS-4lM6ZNTc9Q6UgWFap3sM9kfCiuISmJs0_SNOzlbLu4FJEA2ZIEqM-aV7kciE4jTeR0W3ks3SotiwitHTvQF89mADa8qEzh5xA0HagKDWnoT0TdF80hdT2lsvggL2r5tllw3gyCVL0LT_pjb12841w",
      "kid": "d4cba25e563660a9009d820a1c02022070574e82"
    }
  ]
}
'}
2020-12-03 00:33:50,309 DEBUG [org.jos.jwk.HttpsJwks] (vert.x-eventloop-thread-1) Updated JWKS content from https://www.googleapis.com/oauth2/v3/certs will be cached for 20485 seconds until about Thu Dec 03 06:15:15 CET 2020 -> [org.jose4j.jwk.RsaJsonWebKey{kty=RSA, kid=2e3025f26b595f96eac907cc2b9471422bcaeb93, use=sig, alg=RS256, n=syWuIlYmoWSl5rBQGOtYGwO5OCCZnhoWBCyl-x5gby5ofc4HNhBoVVMUggk-f_MH-pyMI5yRYsS_aPQ2bmSox2s4i9cPhxqtSAYMhTPwSwQ2BROC7xxi_N0ovp5Ivut5q8TwAn5kQZa_jR9d7JO20BUB7UqbMkBsqg2J8QTtMJ9YtA5BmUn4Y6vhIjTFtvrA6iM4i1cKoUD5Rirt5CYpcKwsLxBZbVk4E4rqgv7G0UlWt6NAs-z7XDkchlNBVpMUuiUBzxHl4LChc7dsWXRaO5vhu3j_2WnxuWCQZPlGoB51jD_ynZ027hhIcoa_tXg28_qb5Al78ZttiRCQDKueAQ, e=AQAB}, org.jose4j.jwk.RsaJsonWebKey{kty=RSA, kid=d4cba25e563660a9009d820a1c02022070574e82, use=sig, alg=RS256, n=s44bQ6JmMh-9YBCyCdpbfslwFQ9mloCTgBiX3mwzrBUkliwBRBt5-jJKTXNz_IKERRf43grdSBb3mUiNwq-I6H6EHU0ueyiliGS38rTOrZSK9LM0qy-I8mSNc7p-5MA4Yu-gkBBfvicQ9GZfwlFZpoXt6UIVXywtvNuQNtRsx5oJ8PtbmMPCcA5aFkFl-8YS-4lM6ZNTc9Q6UgWFap3sM9kfCiuISmJs0_SNOzlbLu4FJEA2ZIEqM-aV7kciE4jTeR0W3ks3SotiwitHTvQF89mADa8qEzh5xA0HagKDWnoT0TdF80hdT2lsvggL2r5tllw3gyCVL0LT_pjb12841w, e=AQAB}]
2020-12-03 00:33:50,313 DEBUG [io.sma.jwt.aut.principal] (vert.x-eventloop-thread-1) SRJWT08043: Trying to create a key from the HTTPS JWK(S)
2020-12-03 00:33:50,313 DEBUG [io.sma.jwt.aut.principal] (vert.x-eventloop-thread-1) SRJWT08026: Trying to create a key from the JWK(S)
2020-12-03 00:33:50,313 DEBUG [io.sma.jwt.aut.principal] (vert.x-eventloop-thread-1) SRJWT08021: JWK with a matching 'kid' is not available, refreshing HTTPS JWK Set

... and afterwards at trying to validate a token:
Caused by: org.jose4j.jwt.consumer.InvalidJwtException: JWT processing failed. Additional details: [[17] Unable to process JOSE object (cause: org.jose4j.lang.UnresolvableKeyException: SRJWT07005: Failed to load a key from https://www.googleapis.com/oauth2/v3/certs property while resolving): JsonWebSignature{"alg":"RS256","kid":"tB0M2A"}->eyJhbGciOiJSUzI1NiIsImtpZCI6InRCME0yQSJ9.eyJpc3MiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGUuY29tLyIsImF1ZCI6InJlbnRhai1tZSIsImlhdCI6MTYwNjkzNTAyNywiZXhwIjoxNjA4MTQ0NjI3LCJ1c2VyX2lkIjoiSXZVTGxERUE3Qmc3TFd3ZGp1bm9kYThCTmZqMiIsImVtYWlsIjoiY3VsdW0uYm9yaXNsYXZAZ21haWwuY29tIiwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIiwidmVyaWZpZWQiOmZhbHNlfQ.GRrsO6Ta-A4s-YGQmB2tzwHIcvDTUsOODElIOH0wiSIZ2EYcBg9Ors39fZggNCBkjoHpZICHI3gneknztPPlBOsJEP2hGzrzpoxEfJcLdwslXk8Q4ILnBemCOqeBvNKD3j28D9WK6MDSVoD56A3an5QoZcjEALrEQMjjVIHNwYK9z7jzHbcnMYO_2m-nDhx7gKxZ1cTr3PYf-SqyXzuUgpua4RWspseeonHL5jzqUyWusTGfFdcdeKkf5BxntuZhiiTb0YPJjMrJtgyINEcK4-5Go3KA1fdVx4bOZeozsduVMcOE9SDNnXA3gvBJU4u0x4Jl4_j32Rakv8p3E-VneQ]
	at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:271)
	at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:433)
	at io.smallrye.jwt.auth.principal.DefaultJWTTokenParser.parseClaims(DefaultJWTTokenParser.java:151)
	... 44 more
Caused by: org.jose4j.lang.UnresolvableKeyException: SRJWT07005: Failed to load a key from https://www.googleapis.com/oauth2/v3/certs property while resolving
	at io.smallrye.jwt.auth.principal.AbstractKeyLocationResolver.reportUnresolvableKeyException(AbstractKeyLocationResolver.java:188)
	at io.smallrye.jwt.auth.principal.KeyLocationResolver.resolveKey(KeyLocationResolver.java:65)
	at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:213)
	... 46 more

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

java version 14
gradle 6

**Configuration**
```properties
# Add your application.properties here, if applicable.

mp.jwt.verify.issuer=https://securetoken.google.com/<project-id>
#mp.jwt.verify.publickey.location=META-INF/resources/key.jwks
mp.jwt.verify.publickey.location=https://www.googleapis.com/oauth2/v3/certs
quarkus.smallrye-jwt.enabled=true

**Comment by sberyozkin** [comment]
@bobocu I think this issue is invalid. As you can see from the logs the keys are downloaded, but since none of those keys has a matching `kid` which is what your token has, `tB0M2A` no match is possible. Make sure the token has a matching kid like 
```
"kid": "2e3025f26b595f96eac907cc2b9471422bcaeb93"
``

etc
