### ISSUE TITLE
Can not verify jwt from firebase authentication

### ISSUE THREAD

**Issue by bobocu** [quarkusio/quarkus#13649]
**Describe the bug**
When trying to authenticate jwt from firebase, I get an InvalidJwtException

I obtain a token from:
https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=
And payload:
{ "username" : "user", "password" : "password" }

Use one of the public keys from here:
https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com

and try jwt authentication according to: https://medium.com/@pratikpc/user-auth-using-quarkus-firebase-fdab11d5a845

**Expected behavior**
JWT to be validated

**Actual behavior**
I get an exception on processing the token.

Caused by: org.jose4j.jwt.consumer.InvalidJwtSignatureException: JWT rejected due to invalid signature. Additional details: [[9] Invalid JWS Signature: JsonWebSignature{"alg":"RS256","kid":"b9826d093777ce005e43a327ff202652145e9604","typ":"JWT"}->eyJhbGciOiJSUzI1NiIsImtpZCI6ImI5ODI2ZDA5Mzc3N2NlMDA1ZTQzYTMyN2ZmMjAyNjUyMTQ1ZTk2MDQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVudGFqLW1lIiwiYXVkIjoicmVudGFqLW1lIiwiYXV0aF90aW1lIjoxNjA2OTQ2MzIyLCJ1c2VyX2lkIjoiSXZVTGxERUE3Qmc3TFd3ZGp1bm9kYThCTmZqMiIsInN1YiI6Ikl2VUxsREVBN0JnN0xXd2RqdW5vZGE4Qk5majIiLCJpYXQiOjE2MDY5NDc3MDQsImV4cCI6MTYwNjk1MTMwNCwiZW1haWwiOiJjdWx1bS5ib3Jpc2xhdkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiY3VsdW0uYm9yaXNsYXZAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.1SdncXmtqRjNsDV0UcZwahzIM6u-lNhovTlliORcVBTxpOzrhjiz-g6HMhKt5zyynY2puHKOtCIqSU9n4ThFG4pd58wFLGETOKtS-75-xnc4jhZKJhT4_MFBt06wnkQuwcq-Cn-v16PP-02zM5Sn9om78g7y3I4gZgcd8j_EQL433vPtmbfinGYWFIFeCj7Iq9acGEueV_5k6mrkg55hiDo2RLssysW4K26Bng5Zhyi4TOPMkvsfIqhS_f2kXEz_9FDc1x3aVBw4lsqt3Ro_Nu4sGNksJIl8CuV61FMV4-GwYqj-iGiUgx1VvGq1rgOhptQy3XQoUhKInEG0pZ3-KQ]
	at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:224)
	at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:433)

**Configuration**
```properties
# Add your application.properties here, if applicable.
mp.jwt.verify.issuer=https://securetoken.google.com/<project-id>
mp.jwt.verify.publickey.location=META-INF/resources/key.pem
quarkus.smallrye-jwt.enabled=true
```

**Screenshots**
![image](https://user-images.githubusercontent.com/26071511/100945104-de40e880-3500-11eb-93b4-af122e2fabb4.png)
^^ It fails in this block, using openjdk 14

**Environment (please complete the following information):**
openjdk 14
gradle 6
quarkus 1.9.2.Final

**Additional context**
(Add any other context about the problem here.)

**Comment by sberyozkin** [comment]
@bobocu I don't know why is it a Quarkus bug; Jose4J believes that the verification key you have provided can not verify the signature.

Maybe it is due to you signing with the public certificate according to your description, instead of the private key

**Comment by sberyozkin** [comment]
@bobocu Hi - I have to close this issue because there is no problem with smallrye-jwt loading a verification key - and if the signature verification fails then there must be a problem with creating this signature. Please do not hesitate to reopen it - but I'd like to have a reproducer and more clarifications to the earlier questions. Thanks

**Comment by cleitonsodimac** [comment]
Is there any solution?, I have the same problem

**Comment by maxiplux** [comment]
Hi guys, below you can find my approach to address this error. Update your app.properties following the approach below.

mp.jwt.verify.publickey.location=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
mp.jwt.verify.issuer=https://securetoken.google.com/YOUR_PROJECT_ID_HERE
quarkus.smallrye-jwt.enabled=true
quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE
