### ISSUE TITLE
Using @Embedded with Kotlin results in PropertyNotFoundException exception

### ISSUE THREAD

**Issue by languitar** [quarkusio/quarkus#13678]
**Describe the bug**

When using Quarkus with Kotlin, Embedding one Entity into another using the `@Embedded` annotation, the application fails to start with a `org.hibernate.PropertyNotFoundException` exception. Here is a code fragment that triggers the issue:

```kotlin
enum class CommentEventType {
    CREATED, MODIFIED, HIDDEN
}

@Entity
class Test {
    @Id
    var id: Long? = 1L
}

@Entity
class CommentEvent(
    val type: CommentEventType,
    @Embedded var test: Test? = Test(),
    private val instant: Instant = Instant.now()
) {

    @Id
    @GeneratedValue
    lateinit var eventUuid: UUID

}
```

**Expected behavior**

Things work as documented

**Actual behavior**

The application fails to start with the following exception stack trace:

```
2020-12-03 17:23:04,806 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): org.hibernate.PropertyNotFoundException: Could not locate field name [id] on class [org.acme.CommentEvent]
	at org.hibernate.internal.util.ReflectHelper.findField(ReflectHelper.java:399)
	at org.hibernate.property.access.internal.PropertyAccessFieldImpl.<init>(PropertyAccessFieldImpl.java:34)
	at org.hibernate.property.access.internal.PropertyAccessStrategyFieldImpl.buildPropertyAccess(PropertyAccessStrategyFieldImpl.java:26)
	at org.hibernate.tuple.PropertyFactory.getGetter(PropertyFactory.java:333)
	at org.hibernate.tuple.PropertyFactory.buildIdentifierAttribute(PropertyFactory.java:65)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:140)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:609)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:128)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:96)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:77)
	at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:181)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:301)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:73)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:60)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:117)
	at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:41)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:86)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits-2026547058.deploy_0(HibernateOrmProcessor$startPersistenceUnits-2026547058.zig:74)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits-2026547058.deploy(HibernateOrmProcessor$startPersistenceUnits-2026547058.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:696)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:96)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**To Reproduce**

I have created [a repository stating with a template from https://code.quarkus.io/](https://github.com/languitar/quarkus-jpa-bug-example) that demonstrates the issue. Simply start the application with `./mvnw clean compile quarkus:dev` to trigger the issue.

This is the commit that (single) introduces the issue: https://github.com/languitar/quarkus-jpa-bug-example/commit/69a97fbf12ed4cf3502c27b359b7884544d7c7b6. Sorry for reformatting the `pom.xml`.

The important parts here:
* kotlin jpa compiler plugin added
* Entity added to all-open compiler plugin
* some datasource added to trigger the creation of the entity manager

**Configuration**
Included in the repo.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux pres 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux
 - Output of `java -version`: 
      ```
      Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
      openjdk version "14.0.2" 2020-07-14
      OpenJDK Runtime Environment (build 14.0.2+12)
      OpenJDK 64-Bit Server VM (build 14.0.2+12, mixed mode)
      ```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: contained in linked repo
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): contained in linked repo

**Comment by languitar** [comment]
Seems this is a general bug in Hibernate. I ended up with the exact same situation when porting the code to spring boot. Thus, I opened an issue in the Hibernate bug tracker: https://hibernate.atlassian.net/browse/HHH-14359

**Comment by evanchooly** [comment]
I don't know Hibernate (internals) well enough to know if it's a bug there or not but it's at least partially how kotlin annotations work.  Here's how you can modify your entity to get it working:

```kotlin
@Entity
class CommentEvent(
    val type: CommentEventType,
    @Embedded var test: Test? = Test(),
    private val instant: Instant = Instant.now()
) {

    internal constructor(): this(CREATED) 

    @get:Id
    @GeneratedValue
    var eventUuid: UUID? = null
}
```

Hopefully the implications are clear to you as a kotlin use (wrt the `@get:Id` change) but if not, I'd be happy to expound on that change.

**Comment by languitar** [comment]
Thanks, that at least gives us way to make this work. However, as specifically placing the `Id` annotation on the getter is not required when using the Entity without the embedded field something is still strange here in general. I don't know if this bug should be kept open here or if the upstream hibernate issue is sufficient?

**Comment by evanchooly** [comment]
I'll have to defer to the hibernate team on that one.

**Comment by geoand** [comment]
Is this still an issue with the latest versions of Quarkus?

**Comment by languitar** [comment]
Can't tell. I'm not working on the affected project anymore.

**Comment by geoand** [comment]
Thanks for letting us know.

I'll close for now, and if it's still a problem, we can reopen
