### ISSUE TITLE
Unsafe concurrent ClassLoader use 

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#13687]
**Describe the bug**
I've noticed the following exception stack being ignored but logged in a CI test run:

```
2020-12-03T20:03:03.4075698Z [INFO] Running io.quarkus.resteasy.test.ClasspathResourceTestCase
2020-12-03T20:03:04.3307728Z 2020-12-03 20:03:03,388 ERROR [org.jbo.exe.uncaught] (executor-thread-4) Thread Thread[executor-thread-4,5,] threw an uncaught exception: java.lang.RuntimeException: Unable to read org/jboss/threads/ThreadLocalResettingRunnable$Resetter.class
2020-12-03T20:03:04.3311111Z 	at io.quarkus.bootstrap.classloading.JarClassPathElement$1$1$1.apply(JarClassPathElement.java:121)
2020-12-03T20:03:04.3313722Z 	at io.quarkus.bootstrap.classloading.JarClassPathElement$1$1$1.apply(JarClassPathElement.java:108)
2020-12-03T20:03:04.3316967Z 	at io.quarkus.bootstrap.classloading.JarClassPathElement.withJarFile(JarClassPathElement.java:149)
2020-12-03T20:03:04.3320155Z 	at io.quarkus.bootstrap.classloading.JarClassPathElement.access$100(JarClassPathElement.java:33)
2020-12-03T20:03:04.3323321Z 	at io.quarkus.bootstrap.classloading.JarClassPathElement$1$1.getData(JarClassPathElement.java:108)
2020-12-03T20:03:04.3326627Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:400)
2020-12-03T20:03:04.3332639Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:365)
2020-12-03T20:03:04.3335164Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:31)
2020-12-03T20:03:04.3337123Z 	at java.base/java.lang.Thread.run(Thread.java:832)
2020-12-03T20:03:04.3338066Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
2020-12-03T20:03:04.3339091Z Caused by: java.util.zip.ZipException: ZipFile closed
2020-12-03T20:03:04.3340369Z 	at java.base/java.util.zip.ZipFile.ensureOpenOrZipException(ZipFile.java:832)
2020-12-03T20:03:04.3342034Z 	at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:922)
2020-12-03T20:03:04.3343569Z 	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:445)
2020-12-03T20:03:04.3345719Z 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
2020-12-03T20:03:04.3347235Z 	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
2020-12-03T20:03:04.3349996Z 	at io.quarkus.bootstrap.classloading.JarClassPathElement.readStreamContents(JarClassPathElement.java:231)
2020-12-03T20:03:04.3352995Z 	at io.quarkus.bootstrap.classloading.JarClassPathElement$1$1$1.apply(JarClassPathElement.java:113)
2020-12-03T20:03:04.3354368Z 	... 9 more
2020-12-03T20:03:04.3354597Z 
```

It would seem that there is no protection in `io.quarkus.bootstrap.classloading.JarClassPathElement` against a concurrent `close()` while an ongoing classloading event being performed.

**Comment by geoand** [comment]
Thanks @Sanne.

Are you planning on sending a PR for this?

**Comment by Sanne** [comment]
I can try for the fun of it :)
but I'll need to cap my time on this, don't expect extensive stress testing

**Comment by geoand** [comment]
Yeah, I don't, as this CL is used for dev-mode, so I don't think stress-testing makes much sense :)
