### ISSUE TITLE
Hibernate Reactive Panache test failure

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#13685]
Just got this in a CI run:
```
2020-12-03 21:07:39,185 ERROR [io.qua.mut.run.MutinyInfrastructure] (executor-thread-2) Mutiny had to drop the following exception: java.lang.StackOverflowError
69024
	at io.quarkus.arc.impl.RequestContext.activate(RequestContext.java:124)
69025
	at io.quarkus.arc.runtime.context.ArcContextProvider$ContextSnapshot.begin(ArcContextProvider.java:153)
69026
	at io.smallrye.context.impl.ActiveContextState.<init>(ActiveContextState.java:20)
69027
	at io.smallrye.context.impl.CapturedContextState.begin(CapturedContextState.java:35)
69028
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:529)
69029
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onSubscribe(ContextPropagationUniInterceptor.java:27)
69030
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onSubscribe(UniSerializedSubscriber.java:64)
69031
	at io.smallrye.mutiny.operators.UniCreateFromCompletionStage.forwardFromCompletionStage(UniCreateFromCompletionStage.java:21)
69032
	at io.smallrye.mutiny.operators.UniCreateFromCompletionStage.subscribing(UniCreateFromCompletionStage.java:50)
```

Doesn't look normal to me. I think that's what caused the test failure we see in the CI run.

Details in this run: https://github.com/quarkusio/quarkus/pull/13682/checks?check_run_id=1494907762 .

/cc @gavinking @FroMage @DavideD

**Comment by gsmet** [comment]
More details:

```
2020-12-03 21:07:39,132 ERROR [io.qua.mut.run.MutinyInfrastructure] (executor-thread-2) Mutiny had to drop the following exception: java.lang.StackOverflowError
65945
	at io.quarkus.arc.impl.RequestContext.activate(RequestContext.java:124)
65946
Got back val: null and exception io.quarkus.panache.common.exception.PanacheQueryException: The named query 'Person.namedQueryNotFound' must be defined on your JPA entity or one of its super classes
65947
	at io.quarkus.arc.runtime.context.ArcContextProvider$ContextSnapshot.begin(ArcContextProvider.java:153)
65948
	at io.smallrye.context.impl.ActiveContextState.<init>(ActiveContextState.java:20)
65949
	at io.smallrye.context.impl.CapturedContextState.begin(CapturedContextState.java:35)
65950
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:529)
65951
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onSubscribe(ContextPropagationUniInterceptor.java:27)
65952
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onSubscribe(UniSerializedSubscriber.java:64)
65953
	at io.smallrye.mutiny.operators.UniCreateFromCompletionStage.forwardFromCompletionStage(UniCreateFromCompletionStage.java:21)
65954
	at io.smallrye.mutiny.operators.UniCreateFromCompletionStage.subscribing(UniCreateFromCompletionStage.java:50)
65955
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
65956
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
65957
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
65958
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:48)
65959
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
65960
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:48)
65961
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
65962
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
65963
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
65964
	at io.smallrye.mutiny.operators.UniOnItemTransform.subscribing(UniOnItemTransform.java:19)
65965
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
65966
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
65967
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
65968
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:48)
65969
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
65970
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:48)
65971
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
65972
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
65973
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
65974
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni.subscribing(UniOnItemTransformToUni.java:65)
65975
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
65976
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
65977
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
65978
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:48)
65979
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
65980
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:48)
65981
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
65982
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
65983
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
65984
	at io.smallrye.mutiny.operators.UniOnItemTransform.subscribing(UniOnItemTransform.java:19)
65985
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
65986
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
65987
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
65988
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:48)
65989
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
65990
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:48)
65991
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
65992
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
65993
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
65994
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni.handleInnerSubscription(UniOnItemTransformToUni.java:57)
65995
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni.invokeAndSubstitute(UniOnItemTransformToUni.java:43)
65996
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni$2.onItem(UniOnItemTransformToUni.java:74)
65997
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
65998
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
65999
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
66000
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
66901
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:48)
66902
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
66903
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
66904
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
66905
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni.handleInnerSubscription(UniOnItemTransformToUni.java:57)
66906
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni.invokeAndSubstitute(UniOnItemTransformToUni.java:43)
66907
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni$2.onItem(UniOnItemTransformToUni.java:74)
66908
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
66909
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
66910
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
66911
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
66912
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
66913
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
66914
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
66915
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
66916
	at io.smallrye.mutiny.operators.UniDelegatingSubscriber.onItem(UniDelegatingSubscriber.java:24)
66917
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
66918
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
66919
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
66920
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
66921
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
66922
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
66923
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
66924
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
66925
	at io.smallrye.mutiny.operators.UniOnItemTransform$1.onItem(UniOnItemTransform.java:33)
66926
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
66927
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
66928
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
66929
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
66930
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
66931
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
66932
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
66933
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
66934
	at io.smallrye.mutiny.operators.UniCreateFromCompletionStage.lambda$forwardFromCompletionStage$1(UniCreateFromCompletionStage.java:30)
66935
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
66936
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
66937
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315)
66938
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
66939
	at io.smallrye.mutiny.operators.UniCreateFromCompletionStage.forwardFromCompletionStage(UniCreateFromCompletionStage.java:22)
66940
	at io.smallrye.mutiny.operators.UniCreateFromCompletionStage.subscribing(UniCreateFromCompletionStage.java:50)
66941
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
66942
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
66943
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
66944
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:48)
66945
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
66946
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:48)
66947
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
66948
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
66949
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
66950
	at io.smallrye.mutiny.operators.UniOnItemTransform.subscribing(UniOnItemTransform.java:19)
66951
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
66952
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
66953
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
66954
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:48)
66955
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
66956
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:48)
66957
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
66958
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
66959
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
66960
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni.handleInnerSubscription(UniOnItemTransformToUni.java:57)
66961
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni.invokeAndSubstitute(UniOnItemTransformToUni.java:43)
66962
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni$2.onItem(UniOnItemTransformToUni.java:74)
66963
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
66964
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
66965
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
66966
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
66967
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
66968
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
66969
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
```

**Comment by gavinking** [comment]
I think @Sanne and @FroMage already know about this.

**Comment by gsmet** [comment]
Ah OK, it might be related to the PR I just merged then. I'll let @FroMage close this one if it's the same issue.

**Comment by Sanne** [comment]
well no this is not one of the two issues we solved today. Might be similar though.

**Comment by Sanne** [comment]
OT, but this log also contains a ton of other exceptions of this style:

```
2020-12-03T19:58:55.6730961Z [-- Mutiny had to drop the following exception --]
2020-12-03T19:58:55.6733533Z Exception received by: io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:71)
2020-12-03T19:58:55.6735794Z java.lang.IllegalStateException: Response has already been written
2020-12-03T19:58:55.6737476Z 	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:376)
2020-12-03T19:58:55.6739897Z 	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:365)
2020-12-03T19:58:55.6742046Z 	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:421)
2020-12-03T19:58:55.6744154Z 	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$4$1.onItem(HttpAuthorizer.java:164)
2020-12-03T19:58:55.6746227Z 	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$4$1.onItem(HttpAuthorizer.java:156)
2020-12-03T19:58:55.6748797Z 	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
```

I can't think these are expected? Looks dodgy.

**Comment by Sanne** [comment]
Should I not be concerned about the "OUCH" or the "boom" errors?

```
2020-12-03T20:06:54.1279726Z 2020-12-03 20:06:54,105 ERROR [org.jbo.res.rea.ser.cor.ExceptionMapping] (vert.x-eventloop-thread-3) Request failed : java.lang.RuntimeException: OUCH
2020-12-03T20:06:54.1284125Z 	at io.quarkus.resteasy.reactive.server.test.simple.SimpleQuarkusRestResource.unknownException(SimpleQuarkusRestResource.java:191)
2020-12-03T20:06:54.1289944Z 	at io.quarkus.resteasy.reactive.server.test.simple.SimpleQuarkusRestResource$quarkusrestinvoker$unknownException_6887151b9d372c914c0b3650262a476dea2800c6.invoke(SimpleQuarkusRestResource$quarkusrestinvoker$unknownException_6887151b9d372c914c0b3650262a476dea2800c6.zig:33)
2020-12-03T20:06:54.1294591Z 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2020-12-03T20:06:54.1298195Z 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
2020-12-03T20:06:54.1304925Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:108)
2020-12-03T20:06:54.1308959Z 	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:47)
2020-12-03T20:06:54.1312666Z 	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$5.handle(ResteasyReactiveRecorder.java:121)
2020-12-03T20:06:54.1316104Z 	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$5.handle(ResteasyReactiveRecorder.java:118)
2020-12-03T20:06:54.1318797Z 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1036)
2020-12-03T20:06:54.1321203Z 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
2020-12-03T20:06:54.1323367Z 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
```

boom:

```
2020-12-03T20:09:12.1473435Z [INFO] Running io.quarkus.mutiny.deployment.test.MutinyTest
2020-12-03T20:09:15.4639588Z 2020-12-03 20:09:15,445 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT on JVM started in 0.224s. 
2020-12-03T20:09:15.4641234Z 2020-12-03 20:09:15,446 INFO  [io.quarkus] (main) Profile test activated. 
2020-12-03T20:09:15.4642905Z 2020-12-03 20:09:15,446 INFO  [io.quarkus] (main) Installed features: [cdi, mutiny, smallrye-context-propagation]
2020-12-03T20:09:15.4998042Z 2020-12-03 20:09:15,481 ERROR [io.qua.mut.run.MutinyInfrastructure] (main) Mutiny had to drop the following exception: java.io.IOException: boom
2020-12-03T20:09:15.5000545Z 	at io.quarkus.mutiny.deployment.test.MutinyTest$BeanUsingMutiny.lambda$droppedException$2(MutinyTest.java:124)
2020-12-03T20:09:15.5003215Z 	at io.smallrye.mutiny.operators.UniOnCancellationCall$1$1.execute(UniOnCancellationCall.java:40)
2020-12-03T20:09:15.5006204Z 	at io.smallrye.mutiny.operators.UniOnCancellationCall$1$1.cancel(UniOnCancellationCall.java:30)
2020-12-03T20:09:15.5009461Z 	at io.smallrye.mutiny.operators.UniSerializedSubscriber.cancel(UniSerializedSubscriber.java:117)
2020-12-03T20:09:15.5012814Z 	at io.smallrye.mutiny.operators.UniSerializedSubscriber.cancel(UniSerializedSubscriber.java:117)
2020-12-03T20:09:15.5015709Z 	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.cancel(UniCallbackSubscriber.java:79)
2020-12-03T20:09:15.5018516Z 	at io.quarkus.mutiny.deployment.test.MutinyTest.testDroppedException(MutinyTest.java:62)
2020-12-03T20:09:15.5021073Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-03T20:09:15.5023605Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
2020-12-03T20:09:15.5026545Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-03T20:09:15.5028687Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-12-03T20:09:15.5030371Z 	at io.quarkus.test.QuarkusUnitTest.runExtensionMethod(QuarkusUnitTest.java:334)
```

Also, I logged #13687 -  that's definitely an issue.

**Comment by Sanne** [comment]
So there's several instances of:

```
2020-12-03 21:07:39,185 ERROR [io.qua.mut.run.MutinyInfrastructure] (executor-thread-2) Mutiny had to drop the following exception: java.lang.StackOverflowError
```
followed by stacktraces which are _pages_ long involving Mutiny, but I couldn't reproduce it locally - not even after reverting @FroMage 's patch.

I hope someone more familiar with Mutiny could have a look and suggest if it's at all reasonable for i to swallow a `StackOverflowError` !? and what could be going on?

**Comment by FroMage** [comment]
No, I don't know about this. How can I reproduce? Given the stack trace it looks like either an infinite recursion in Mutiny (@cescoffier @jponge ) or perhaps one area where either HR or the Panache layer forgot to trampoline, no @gavinking ?

**Comment by jponge** [comment]
A narrow reproducer would help 👍

**Comment by geoand** [comment]
Is this error still showing up in CI?
