### ISSUE TITLE
IDE Launcher fails for gradle project containing a submodule without resources

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#13711]
**Describe the bug**
We have a gradle project with some submodules. Some submodules have an empty resource folder.
When starting the main method directly from the Intellij, we receive a null pointer exception.

```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:57)
	at io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:92)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:79)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
	at org.qumea.Main.main(Main.java:11)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:54)
	... 5 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:60)
	... 10 more
Caused by: java.lang.NullPointerException
	at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:50)
	... 10 more
```

**Expected behavior**
Empty resource directories should probably be ignored.

**To Reproduce**
[submodule-no-resources.zip](https://github.com/quarkusio/quarkus/files/5643966/submodule-no-resources.zip)

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.10.2.Final

**Comment by glefloch** [comment]
thanks for reporting this @joggeli34, I think we handle this case in the gradle plugin, I can remember of an issue on this.

**Comment by joggeli34** [comment]
The issue is still there in 1.11.0.Final when running the main method directly from intellij. So the fix probably didn't work or I just missed something?

Regards
