### ISSUE TITLE
Websocket logs an error when forcably closed by remote, but does not call @OnError

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#13747]
**Describe the bug**

When a connection is forcibly closed by the remote host, an exception is logged, but the method annotated with @OnError is not called.

@OnClose is then called with the code '1001' (CLOSE_GOING_AWAY)

```
2020-12-08 09:37:43,842 WARN  [io.net.cha.DefaultChannelPipeline] (vert.x-eventloop-thread-8) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected behavior**

I'm not sure which one would be the correct way:

- Call @OnError and @OnClose with code 1006
- Only call @OnClose with code 1006
- Only log the exception if no @OnError annotated method is found

**To Reproduce**

[websocket-close.zip](https://github.com/quarkusio/quarkus/files/5658326/websocket-close.zip)

1. Run the reproducer with quarkusDev
2. When running, start the WebSocketClient.main()

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.10.2.FINAL

**Comment by Kybox** [comment]
I was hoping that since last December this issue would be solved with the new version [...]

**Comment by mkouba** [comment]
@joggeli34 Could you try your reproducer with [WebSockets Next](https://quarkus.io/guides/websockets-next-reference) and the latest Quarkus version?

The development of the original `quarkus-websocket` extension has been discontinued and the `quarkus-websockets-next` extension is the preferred solution.

**Comment by geoand** [comment]
Closing for lack of feedback
