### ISSUE TITLE
Native build failed due to UnresolvedElementException: Discovered unresolved method during parsing: com.google.common.util.concurrent.Futures.addCallback(com.google.common.util.concurrent.ListenableFuture, com.google.common.util.concurrent.FutureCallback)

### ISSUE THREAD

**Issue by vishalgoel1988** [quarkusio/quarkus#13755]
**Describe the bug**
Hi,
I am trying to build quarkus native build using GraalVM (Quarkus 1.10.2.Final) .  During build, I see below exception.
Please note that I am using HDFS dependencies in my pom.

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.google.common.util.concurrent.Futures.addCallback(com.google.common.util.concurrent.ListenableFuture, com.google.common.util.concurrent.FutureCallback). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
        at parsing org.apache.hadoop.security.Groups$GroupCacheLoader.reload(Groups.java:367)
Call path from entry point to org.apache.hadoop.security.Groups$GroupCacheLoader.reload(String, List):
        at org.apache.hadoop.security.Groups$GroupCacheLoader.reload(Groups.java:351)
        at org.apache.hadoop.security.Groups$GroupCacheLoader.reload(Groups.java:270)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3532)
        at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2287)
        at com.google.common.cache.LocalCache$Segment.refresh(LocalCache.java:2360)
        at com.google.common.cache.LocalCache$Segment.scheduleRefresh(LocalCache.java:2338)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2072)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3946)
        at java.util.concurrent.ConcurrentSkipListMap.equals(ConcurrentSkipListMap.java:1760)
        at java.util.HashMap.getNode(HashMap.java:574)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:129)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:323)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.google.common.util.concurrent.Futures.addCallback(com.google.common.util.concurrent.ListenableFuture, com.google.common.util.concurrent.FutureCallback). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
        at parsing org.apache.hadoop.security.Groups$GroupCacheLoader.reload(Groups.java:367)
Call path from entry point to org.apache.hadoop.security.Groups$GroupCacheLoader.reload(String, List):
        at org.apache.hadoop.security.Groups$GroupCacheLoader.reload(Groups.java:351)
        at org.apache.hadoop.security.Groups$GroupCacheLoader.reload(Groups.java:270)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3532)
        at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2287)
        at com.google.common.cache.LocalCache$Segment.refresh(LocalCache.java:2360)
        at com.google.common.cache.LocalCache$Segment.scheduleRefresh(LocalCache.java:2338)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2072)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3946)
        at java.util.concurrent.ConcurrentSkipListMap.equals(ConcurrentSkipListMap.java:1760)
        at java.util.HashMap.getNode(HashMap.java:574)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:129)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:323)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:768)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:558)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.google.common.util.concurrent.Futures.addCallback(com.google.common.util.concurrent.ListenableFuture, com.google.common.util.concurrent.FutureCallback). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
        at parsing org.apache.hadoop.security.Groups$GroupCacheLoader.reload(Groups.java:367)
Call path from entry point to org.apache.hadoop.security.Groups$GroupCacheLoader.reload(String, List):
        at org.apache.hadoop.security.Groups$GroupCacheLoader.reload(Groups.java:351)
        at org.apache.hadoop.security.Groups$GroupCacheLoader.reload(Groups.java:270)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3532)
        at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2287)
        at com.google.common.cache.LocalCache$Segment.refresh(LocalCache.java:2360)
        at com.google.common.cache.LocalCache$Segment.scheduleRefresh(LocalCache.java:2338)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2072)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3946)
        at java.util.concurrent.ConcurrentSkipListMap.equals(ConcurrentSkipListMap.java:1760)
        at java.util.HashMap.getNode(HashMap.java:574)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:129)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:323)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
        ... 8 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.google.common.util.concurrent.Futures.addCallback(com.google.common.util.concurrent.ListenableFuture, com.google.common.util.concurrent.FutureCallback). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:261)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:251)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:205)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1642)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1617)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5360)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3399)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3206)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1092)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:986)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:70)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:227)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:547)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        ... 5 more
Error: Image build request failed with exit status 1
```

pom.xml contains:
```
<dependency>
	    <groupId>org.apache.hadoop</groupId>
	    <artifactId>hadoop-hdfs-client</artifactId>
	    <version>3.1.1</version>
	    <scope>provided</scope>
    </dependency>
    <dependency>
    <groupId>org.apache.hadoop</groupId>
	    <artifactId>hadoop-client</artifactId>
	    <version>3.1.1</version>
	 </dependency>
	<dependency>
	    <groupId>org.apache.hadoop</groupId>
	    <artifactId>hadoop-common</artifactId>
	    <version>3.1.1</version>
</dependency>
```
Seems the complaint is about below line. It is static method, is that an issue?
https://github.com/hopshadoop/hops/blob/master/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/Groups.java#L378

Please suggest how can I fix this issue.

**Comment by vishalgoel1988** [comment]
Even if I remove HDFS dependencies, and use any guava functions explicitly (with guava added in pom), it also gives error.
Any idea/help?

**Comment by geoand** [comment]
This would need a dedicated extension in order to work in native
