### ISSUE TITLE
SSL error running native-image in alpine container

### ISSUE THREAD

**Issue by affanshahid** [quarkusio/quarkus#13765]
Trying to build a native-image while using the MySQL extension.

My dockerfile:
```Dockerfile
FROM quay.io/quarkus/centos-quarkus-maven:20.2.0-java11 AS build
COPY pom.xml /usr/src/app/
RUN mvn -f /usr/src/app/pom.xml -B de.qaware.maven:go-offline-maven-plugin:1.2.5:resolve-dependencies
COPY src /usr/src/app/src
USER root
RUN chown -R quarkus /usr/src/app
USER quarkus
RUN mvn -f /usr/src/app/pom.xml -Pnative -Dquarkus.native.additional-build-args=--static clean package
RUN chmod 777 /usr/src/app/target/*-runner

## Stage 2 : create the docker final image
FROM alpine
WORKDIR /work/
COPY --from=build /usr/src/app/target/*-runner /work/application
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

Error Exception:
```java
org.jboss.resteasy.spi.UnhandledException: java.sql.SQLNonTransientConnectionException: Default algorithm definitions for TrustManager and/or KeyManager are invalid.  Check java security properties file.
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:136)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:40)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:97)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.sql.SQLNonTransientConnectionException: Default algorithm definitions for TrustManager and/or KeyManager are invalid.  Check java security properties file.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:70)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql.DriverManager.getConnection(DriverManager.java:251)
	at com.affanshahid.quarkustest.GreetingService.<init>(GreetingService.java:14)
	at com.affanshahid.quarkustest.GreetingService_ClientProxy.<init>(GreetingService_ClientProxy.zig:24)
	at com.affanshahid.quarkustest.GreetingService_Bean.proxy(GreetingService_Bean.zig:37)
	at com.affanshahid.quarkustest.GreetingService_Bean.get(GreetingService_Bean.zig:169)
	at com.affanshahid.quarkustest.GreetingService_Bean.get(GreetingService_Bean.zig:185)
	at com.affanshahid.quarkustest.GreetingResource_Bean.create(GreetingResource_Bean.zig:154)
	at com.affanshahid.quarkustest.GreetingResource_Bean.create(GreetingResource_Bean.zig:195)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at com.affanshahid.quarkustest.GreetingResource_Bean.get(GreetingResource_Bean.zig:227)
	at com.affanshahid.quarkustest.GreetingResource_Bean.get(GreetingResource_Bean.zig:243)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:435)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:448)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:271)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:268)
	at io.quarkus.arc.runtime.BeanContainerImpl$1.create(BeanContainerImpl.java:35)
	at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:54)
	at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:71)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:386)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 19 more
Caused by: com.mysql.cj.exceptions.SSLParamsException: Default algorithm definitions for TrustManager and/or KeyManager are invalid.  Check java security properties file.
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.protocol.ExportControlled.getSSLContext(ExportControlled.java:517)
	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:303)
	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)
	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:97)
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:331)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
	... 50 more
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: PKIX, provider: SunJSSE, class: sun.security.ssl.TrustManagerFactoryImpl$PKIXFactory)
	at java.security.Provider$Service.newInstance(Provider.java:1902)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.TrustManagerFactory.getInstance(TrustManagerFactory.java:162)
	at com.mysql.cj.protocol.ExportControlled.getSSLContext(ExportControlled.java:514)
	... 59 more
Caused by: java.lang.NoSuchMethodException: sun.security.ssl.TrustManagerFactoryImpl$PKIXFactory.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3349)
	at java.lang.Class.getConstructor(DynamicHub.java:2151)
	at java.security.Provider.newInstanceUtil(Provider.java:153)
	at java.security.Provider$Service.newInstance(Provider.java:1891)
	... 63 more
```

I have seen solutions working with graalvm:19 which involve copying `libsunec.so` as suggested [here](https://github.com/quarkusio/quarkus/issues/2125#issuecomment-528846339) but I cannot seem to find this file in graalvm 20 images.

**Comment by gsmet** [comment]
This is a very old issue and SSL support significantly improved in GraalVM. Let's close it. If you encounter a similar issue, please open a new issue with a reproducer.
