### ISSUE TITLE
Reactive Resteasy build error

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#13778]
Trying out the new reactive resteasy with 999-SNAPSHOT. Hit an issue early on when trying to build an existing project which works with normal Quarkus/Resteasy:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project jg-ukheshe-deployable: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Failed to process method guru.jini.services.wallet.rest.WalletsResource#java.util.List<guru.jini.services.wallet.model.WalletHistory> bulkTransfer(java.util.List<guru.jini.services.wallet.model.Transfer> transfers)
[ERROR] 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:230)
[ERROR] 	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:353)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:832)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.RuntimeException: Failed to process method guru.jini.services.wallet.rest.WalletsResource#java.util.List<guru.jini.services.wallet.model.WalletHistory> bulkTransfer(java.util.List<guru.jini.services.wallet.model.Transfer> transfers)
[ERROR] 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:482)
[ERROR] 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:270)
[ERROR] 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:201)
[ERROR] 	... 13 more
[ERROR] Caused by: java.lang.RuntimeException: Failed to find converter for guru.jini.services.wallet.model.Transfer
[ERROR] 	at io.quarkus.resteasy.reactive.server.deployment.ServerEndpointIndexer.extractConverter(ServerEndpointIndexer.java:259)
[ERROR] 	at io.quarkus.resteasy.reactive.server.deployment.ServerEndpointIndexer.handleListParam(ServerEndpointIndexer.java:166)
[ERROR] 	at io.quarkus.resteasy.reactive.server.deployment.ServerEndpointIndexer.handleListParam(ServerEndpointIndexer.java:72)
[ERROR] 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.extractParameterInfo(EndpointIndexer.java:799)
[ERROR] 	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:368)
[ERROR] 	... 15 more
```

This is the source:
```
@POST
    @Path("/bulk-transfers")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public List<WalletHistory> bulkTransfer(List<Transfer> transfers) {
        return walletManager.transfer(transfers);
    } 
```

Transfer.class is in a jar which the project being built has a dependency on.
This works through. So seems like a bug when dealing with an incoming list:

```
@POST
    @Path("/transfers")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public List<WalletHistory> doTransfer(Transfer transfer) {
        return walletManager.transfer(transfer, false, false);
    }
```

**Comment by stuartwdouglas** [comment]
I think this was fixed by https://github.com/quarkusio/quarkus/commit/96aaa4f2906dd7ebe3c05d30fde8fb9a7578574a
