### ISSUE TITLE
Liquibase failing dbms-type pre-condition in native build

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#13839]
**Describe the bug**

I have a liquibase script with a precondition on the dbms type:

```
<preConditions>
   <dbms type="postgresql,h2"/>
</preConditions>
```

When runing on a JVM it works correctly. When running as native build, following error is thrown:

```
Dec 11, 2020 1:29:31 PM liquibase.changelog
INFO: Reading from qumearecording.databasechangelog
Dec 11, 2020 1:29:31 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
liquibase.exception.ValidationFailedException: Validation Failed:
     1 preconditions failed
     db/changeLog.xml : DBMS Precondition failed: expected null, got postgresql

        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:298)
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:274)
        at liquibase.Liquibase.validate(Liquibase.java:2154)
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:48)
        at io.quarkus.deployment.steps.LiquibaseProcessor$createBeansAndStartActions-960013254.deploy_0(LiquibaseProcessor$createBeansAndStartActions-960013254.zig:80)
        at io.quarkus.deployment.steps.LiquibaseProcessor$createBeansAndStartActions-960013254.deploy(LiquibaseProcessor$createBeansAndStartActions-960013254.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:455)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:96)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

I also tested that the dbms attribute on the changeSet is working correctly. 

**To Reproduce**

Run a project with contains a liquibase <preCondition> native.

**Environment:**
 - Quarkus version: 1.10.3.Final

**Comment by machi1990** [comment]
I'll have a look.
