### ISSUE TITLE
Using @Timed with quarkus-smallrye-metrics fails

### ISSUE THREAD

**Issue by enbohm** [quarkusio/quarkus#1384]
I'm using the simple getting started application at https://quarkus.io/guides/getting-started-guide and added a dependency on **quarkus-smallrye-metrics** and added two annoations, ```@Counted``` and ```@Timed```on the greering-method.

```
  @GET
  @Produces(MediaType.TEXT_PLAIN)
  @Path("/greeting/{name}")
  @Timed
  @Counted
  public String greeting(@PathParam("name") String name) {
    return service.greeting(name);
  }
```

The following annotation ```@Timed``` does seem to crash the applicationand when I try to access ```/hello/greeting/johndoe``` the requst fails with a HTTP status 500  (just using ```@Counted``` seems to work fine). The following stack trace is generated
```
Caused by: java.lang.IllegalStateException: No timer with name [se.tcxn.quarkus.GreetingFacade.greeting] found in registry [io.smallrye.metrics.MetricRegistries_ProducerMethod_getApplicationRegistry_3084f885749d4d534e6c1a0434dc45444ee9cbec_ClientProxy@13d071c7]
	at io.smallrye.metrics.interceptors.TimedInterceptor.timedCallable(TimedInterceptor.java:75)
	at io.smallrye.metrics.interceptors.TimedInterceptor.timedMethod(TimedInterceptor.java:63)
	... 83 more
```
I'm using quarkus version 0.11.0, tried with both JDK1.8 and JDK 11 on macOS Mojave and maven 3.5.3

**Comment by mkouba** [comment]
This issue duplicates https://github.com/quarkusio/quarkus/issues/1009
