### ISSUE TITLE
Hibernate Proxy classes generated with incorrect java release version

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#13871]
**Describe the bug**
We can set the java release version to be used throug maven property `maven.compiler.release` (e.g. `<maven.compiler.release>11</maven.compiler.release>`)

When the project is then compiled with a `javac` version >= 11 and run with java 11, an `java.lang.UnsupportedClassVersionError` is thrown on application startup.

**Expected behavior**
All sources should be compiled to target the specified java release, and the application should start up.

**Actual behavior**
On application startup, the following exception is thrown:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:249)
	... 9 more
Caused by: java.lang.UnsupportedClassVersionError: de/turing85/HelloEntity$HibernateProxy$0mzonqkm has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.proxies.ProxyDefinitions.generateProxyClass(ProxyDefinitions.java:127)
	at io.quarkus.hibernate.orm.runtime.proxies.ProxyDefinitions.createFromMetadata(ProxyDefinitions.java:61)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:318)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:101)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:73)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:40)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$1.created(HibernateOrmRecorder.java:58)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:53)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy_0(ArcProcessor$generateResources-1025303321.zig:127)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy(ArcProcessor$generateResources-1025303321.zig:40)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:207)
	... 9 more
```
**To Reproduce**

- Checkout `https://github.com/turing85/quarkus-hibernate-javaversion-bug`
- verify `javac` version is `>11`: 

      > javac -version
      javac 14.0.2
- Compile, project, start docker-container:

      ./mvnw clean install -Dquarkus.container-image.build=true && docker run quarkus-bug/hello-app:my-1.0.0

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Linux XXX 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 

       openjdk 14.0.2 2020-07-14
       OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
       OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

 - GraalVM version (if different from Java): N/A 
 - Quarkus version or git rev: `1.10.3.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

       Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
       Maven home: /home/marco/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
       Java version: 14.0.2, vendor: AdoptOpenJDK, runtime: /opt/adoptOpenJDK/14.0.2+12
       Default locale: en_US, platform encoding: UTF-8
       OS name: "linux", version: "5.4.0-58-generic", arch: "amd64", family: "unix"

**Comment by stuartwdouglas** [comment]
@Sanne looks like hibernate generates proxies with the version of the VM that runs augment, with no way to change it (it would need to be an additional ctor param to BytecodeProviderImpl which would need to pass it into ByteBuddyState).

**Comment by Sanne** [comment]
thanks for the analysis @stuartwdouglas and @turing85 !

But general question first. Should we really support the case of people running an older JDK at runtime than the one used during our augmentation phase?

We can certainly improve things, but I wonder what kind of rabbit hole this brings us into. Perhaps a global upfront check at framework level would be a better direction?

**Comment by turing85** [comment]
@Sanne scenario, in which I ran into the problem:
- locally installed java was Java 14
- I compile a `mitable-jar` on my machine, build a docker image, deploy it thorough `docker-compose` (I specifically avoid building from within a pod through, e.g., a multistage-docker file since we cannot mount anything at image buildtime and thus caching dependencies is a struggle)
- for further development, I open a `remote-dev` session to the docker deployment

I certainly agree that - when built through a pipeline, the java-version building the artifact should match the java-version running the artifact. But for local development, it should be possible to use a more recent java-release. Furthermore, we have a dedicated compiler-flag (`--release`) to fixate the java-version we target, so why not use it?

**Comment by Sanne** [comment]
@turing85 yes I agree, all good points and we can certainly improve things in the Hibernate extensions.

I'm just concerned that this won't be the last of such issues even if we solve it - we might need a more comprehensive approach.

@stuartwdouglas what about MR jars (for example?): will we need to ensure the classloaders load the right class for the target deployment version (which is apparently not the version used at augmentation)

**Comment by stuartwdouglas** [comment]
@Sanne while there are issues around this, IMHO I think this one is easy to fix. As I understand it the proxies in question won't be using any class file features introduced after JDK8, so it is easiest just to hard code the generated class format to JDK8.

We have seen other similar errors, and we recommend that you build and deploy with the same JDK, but as much as possible we have been fixing these on a 'best effort' basis when they crop up.

**Comment by Sanne** [comment]
pushed this to Hibernate ORM:
- https://github.com/hibernate/hibernate-orm/commit/21ec1a19d1c6db518fe6fe6026848cf68b5a06f2

Will be included in upcoming `5.4.27.Final` release - then we need to follow up with some Quarkus patch which sets the expected build version.
