### ISSUE TITLE
Cannot start a mutable-jar built under Windows 10 in docker-container with QUARKUS_LAUNCH_DEVMODE=true

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#13878]
**Describe the bug**
When a mutable-jar, that was build on windows 10, is copied to a docker-container and started with  `QUARKUS_LAUNCH_DEVMODE=true`, the container terminates by throwing a `java.lang.ClassNotFoundException`.

**Expected behavior**
Container starts and can be used in conjunction with `quarkus:remote-dev`.

**Actual behavior**
Container terminates on startup with the following stack trace:

```
Exception in thread "main" java.lang.ClassNotFoundException: io.quarkus.deployment.mutability.DevModeTask
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:49)
        at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:34)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:24)
```
**To Reproduce**
- Checkout `https://github.com/turing85/quarkus-mutablejar-win10-bug`
- Compile project, start docker-container:

      mvnw clean install -Dquarkus.container-image.build=true && docker run quarkus-bug/hello-app:1.0.0

**Configuration**

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Microsoft Windows [Version 10.0.19041.685]`
 - Output of `java -version`: 

       openjdk 11.0.4 2019-07-16
       OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
       OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev:  `1.10.3.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

       Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
       Maven home: C:\Users\Marco\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
       Java version: 11.0.4, vendor: AdoptOpenJDK, runtime: D:\Java\AdoptOpenJDK\jdk-11.0.4.11-hotspot
       Default locale: en_GB, platform encoding: Cp1252
       OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by stuartwdouglas** [comment]
Any chance you could test out https://github.com/quarkusio/quarkus/compare/master...stuartwdouglas:13878 

I don't have a windows environment setup for Java Development at the moment.

**Comment by hammer-83** [comment]
Still does not work for me. Original error is gone but there seem to be other places where backslash is used:
```
Caused by: java.nio.file.NoSuchFileException: /work/app\quarkus-test-1.0-SNAPSHOT.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:155)
        at io.quarkus.deployment.mutability.DevModeTask.extractDevModeClasses(DevModeTask.java:162)
        at io.quarkus.deployment.mutability.DevModeTask.createDevModeContext(DevModeTask.java:78)
        at io.quarkus.deployment.mutability.DevModeTask.main(DevModeTask.java:53)
        ... 8 more
```

**Comment by turing85** [comment]
Can confirm @hammer-83 's observation. The last `\` before the `jar`'-file is not replaced by a `/`.

**Comment by stuartwdouglas** [comment]
I have force pushed to the branch, can you re-test?

**Comment by turing85** [comment]
@stuartwdouglas I get (almost) the initial error again:
```
Exception in thread "main" java.lang.ClassNotFoundException: io.quarkus.deployment.mutability.DevModeTask
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:49)
        at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:35)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
```


`git log` also shows the last commit is `5ef182c058c1457c878e9dc2f5f1956c43b41682` from  `Wed Dec 16 15:22:46 2020 +1100`.
