### ISSUE TITLE
Resteasy Reactive: Custom ParamConveter is not recognized 

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#13915]
I was using the latest Resteasy Reactive:

* Quarkus version: 999-SNAPSHOT
* Java 11
* Windows 10

I have added a custom ParamConverter to convert the request param to UUID, see [here](https://github.com/hantsy/quarkus-sample/blob/master/resteasy-reactive/src/main/java/org/example/UuidParamConverterProvider.java).

When running the application via `quarkus:dev`, and got the exception at the application start stage.

```bash

Caused by: java.lang.ClassNotFoundException: java.util.UUID$quarkusrestparamConverter$
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:371)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:365)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:371)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:365)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.jboss.resteasy.reactive.server.core.parameters.converters.GeneratedParameterConverter.get(GeneratedParameterConverter.java:10)

```

**Comment by geoand** [comment]
Hi,

I just tried your reproducer (well, a modified version of it without Hibernate Reactive) and the UUID handling worked just fine.
Can you please update the reproducer to not contain anything but RESTEasy Reactive and also mention the HTTP request you used to surface the problem?

Thanks

**Comment by hantsy** [comment]
Verified it toady, it seems no problem now. Thanks @geoand .
