### ISSUE TITLE
Currently not supporting composite id

### ISSUE THREAD

**Issue by afganhalbana** [quarkusio/quarkus#13921]
**Describe the bug**
```
Caused by: java.lang.IllegalArgumentException: Currently only Entities with the @Id annotation are supported. Offending class is id.entity.ServiceClinic
	at io.quarkus.spring.data.deployment.generate.StockMethodsAdder.getIdAnnotationTargetRec(StockMethodsAdder.java:997)
	at io.quarkus.spring.data.deployment.generate.StockMethodsAdder.getIdAnnotationTargetRec(StockMethodsAdder.java:1000)
	at io.quarkus.spring.data.deployment.generate.StockMethodsAdder.getIdAnnotationTarget(StockMethodsAdder.java:986)
	at io.quarkus.spring.data.deployment.generate.StockMethodsAdder.generateSave(StockMethodsAdder.java:138)
	at io.quarkus.spring.data.deployment.generate.StockMethodsAdder.add(StockMethodsAdder.java:80)
	at io.quarkus.spring.data.deployment.generate.SpringDataRepositoryCreator.implementCrudRepository(SpringDataRepositoryCreator.java:110)
	at io.quarkus.spring.data.deployment.SpringDataJPAProcessor.implementCrudRepositories(SpringDataJPAProcessor.java:239)
	at io.quarkus.spring.data.deployment.SpringDataJPAProcessor.build(SpringDataJPAProcessor.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
```

**Expected behavior**
We should be able to use composite key with quarkus

**Actual behavior**
https://stackoverflow.com/questions/61211391/are-composite-primary-keys-in-jpa-with-quarkus-possible#_=_
as @geoand comment on the stackoverflow, this is a missing feature. when will quarkus support this kind of functionality since i believe most of the systems out there can't migrate to quarkus caused by this, thanks in advance.

**Comment by famod** [comment]
Duplicates #10870.

Anyway, thanks for reporting!

**Comment by RPG-2021** [comment]
What would be the timeline for support of composite key for quarkus spring data JPA? Wonder if there is any latest effort on it or if it is coming up in near future. I see some integrations tests with @EmbeddedId but unable to locate the actual code. We are trying to convert our big Spring project into Quarkus. We are really waiting on this one thing. Appreciate any feedback. Thanks!
