### ISSUE TITLE
Simple class name of @ConfigRoot annotated classes must be unique

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#13966]
**Describe the bug**
Due to the logic in `RootDefinition(RootDefinition.Builder)` (see below) the simple class name of `@ConfigRoot` annotated classes appear like they need to be unique.

https://github.com/quarkusio/quarkus/blob/1561bdea9639ae7a7acca1cbe8a083052371862d/core/deployment/src/main/java/io/quarkus/deployment/configuration/definition/RootDefinition.java#L31)

We indeed have a custom extension with a config root class with the simple name `SecurityBuildTimeConfig` which conflicts with the corresponding class in `quarkus-security`. When launching the application in quarkus-dev mode we run into a `ClassCastException`. I suspect these lines are also involved in the problem: https://github.com/quarkusio/quarkus/blob/1561bdea9639ae7a7acca1cbe8a083052371862d/core/deployment/src/main/java/io/quarkus/deployment/configuration/RunTimeConfigurationGenerator.java#L628-L643

Interestingly enough I have so far only encountered this error in quarkus-dev mode.

**Expected behavior**
I think either the simple class name should not have to be unique or Quarkus should fail with an error at build time indicating that there is a conflict.

**Actual behavior**
As described quarkus-dev mode may end up failing to start the application with a `ClassCastException` like the following:

```
ERROR: Failed to start application (with profile dev)
java.lang.ClassCastException: class ch.mobi.gluon.security.runtime.SecurityBuildTimeConfig cannot be cast to class io.quarkus.security.runtime.SecurityBuildTimeConfig (ch.mobi.gluon.security.runtime.SecurityBuildTimeConfig and io.quarkus.security.runtime.SecurityBuildTimeConfig are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @1dac5ef)
        at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$security$runtime$SecurityBuildTimeConfig(Config.zig:41129)
        at io.quarkus.runtime.generated.Config.readConfig(Config.zig:1912)
        at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:42)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:532)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:96)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
This is a bit more involved, but if requested, I could try to put together a reproducer.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: openjdk version "11.0.9" 2020-10-20 LTS
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.4.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Comment by radcortez** [comment]
Just to add that the fix allows to use the same simple class name.
