### ISSUE TITLE
Resteasy Reactive : issue with RestClient

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#13999]
**Describe the bug**
I have a rest endpoint that uses a MP RestClient (via a service), when I update this rest endpoint from Resteasy to the new Resteasy reactive extension, the service that uses a RestClient fails with  the following error:

```
Caused by: java.lang.ClassCastException: class org.jboss.resteasy.reactive.common.jaxrs.UriBuilderImpl cannot be cast to class org.jboss.resteasy.spi.ResteasyUriBuilder (org.jboss.resteasy.reactive.common.jaxrs.UriBuilderImpl and org.jboss.resteasy.spi.ResteasyUriBuilder are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @932bc4a)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.verifyInterface(RestClientBuilderImpl.java:396)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.build(RestClientBuilderImpl.java:175)
	at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:72)
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 11
 - Quarkus version or git rev: 1.11.0.Beta1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):

**Comment by geoand** [comment]
This has already been fixed by https://github.com/resteasy/Resteasy/pull/2575, but we'll need a RESTEasy release (cc @asoldano)

**Comment by geoand** [comment]
This was fixed by https://github.com/quarkusio/quarkus/pull/14184
