### ISSUE TITLE
Thread blocked warning VertxException

### ISSUE THREAD

**Issue by geniusit** [quarkusio/quarkus#14029]
I notice that I got this stacktrace in my server

```java
2020-12-22 18:03:23,875 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-0,5,executor]=Thread[vert.x-eventloop-thread-0,5,executor] has been blocked for 3795 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at java.net.InetAddress.getByName(InetAddress.java:1077)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
        at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:140)
        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:93)
        at io.vertx.core.net.impl.NetClientImpl.doConnect(NetClientImpl.java:211)
        at io.vertx.core.net.impl.NetClientImpl.doConnect(NetClientImpl.java:168)
        at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:157)
        at io.vertx.pgclient.impl.PgConnectionFactory.doConnect(PgConnectionFactory.java:192)
        at io.vertx.pgclient.impl.PgConnectionFactory.connect(PgConnectionFactory.java:119)
        at io.vertx.pgclient.impl.PgConnectionFactory.connectAndInit(PgConnectionFactory.java:105)
        at io.vertx.pgclient.impl.PgPoolImpl.connect(PgPoolImpl.java:47)
        at io.vertx.sqlclient.impl.PoolBase$$Lambda$107/348055829.accept(Unknown Source)
        at io.vertx.sqlclient.impl.ConnectionPool.check(ConnectionPool.java:207)
        at io.vertx.sqlclient.impl.ConnectionPool.acquire(ConnectionPool.java:76)
        at io.vertx.sqlclient.impl.PoolBase.schedule(PoolBase.java:82)
        at io.vertx.sqlclient.impl.PoolBase.lambda$schedule$2(PoolBase.java:98)
        at io.vertx.sqlclient.impl.PoolBase$$Lambda$465/1468725312.handle(Unknown Source)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$468/1029299646.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

```

Is it related to the database healthcheck or somethink related to database connection ?? I never got it since today.

I use Quarkus 1.10.3.Final

**Comment by cescoffier** [comment]
It is doing a DNS lookup on the IO Thread. It should be ok, however, in some cases, the DNS server takes a bit of time to reply (records not cached yet). That's what is happening here. If the DNS lookup takes more than 2000 ms, you get this stack trace.

Does it only happen during startup? In this case, it can be safely ignored.

**Comment by geniusit** [comment]
Yes, only during startup!

**Comment by geoand** [comment]
Like Clement said, this is related to DNS and is not a Quarkus issue, so I'll go ahead and close
