### ISSUE TITLE
Sentry integration causing Quarkus to fail at start in dev mode

### ISSUE THREAD

**Issue by DaHoC** [quarkusio/quarkus#14057]
**Describe the bug**
When following the steps of the [Quarkus Sentry logging guide](https://quarkus.io/guides/logging-sentry), the application fails to start.

**Expected behavior**
Quarkus starts up normally and Sentry integration works as described in the guide and as was behavior before about Quarkus version 1.9.1.Final

**Actual behavior**
An exception is thrown, Quarkus fails to startup:

```
./mvnw compile quarkus:dev
[...]
Listening for transport dt_socket at address: 5005
Dez. 27, 2020 12:58:32 PM org.jboss.threads
INFO: JBoss Threads version %s
Dez. 27, 2020 12:58:33 PM org.jboss.threads
INFO: JBoss Threads version %s
Dez. 27, 2020 12:58:33 PM io.quarkus.logging.sentry.SentryConfigProvider
WARN: No 'quarkus.sentry.in-app-packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See https://quarkus.io/guides/logging-sentry#in-app-packages
Dez. 27, 2020 12:58:33 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile dev)
java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonGenerator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at io.sentry.DefaultSentryClientFactory.createJsonMarshaller(DefaultSentryClientFactory.java:526)
        at io.sentry.DefaultSentryClientFactory.createMarshaller(DefaultSentryClientFactory.java:494)
        at io.sentry.DefaultSentryClientFactory.createHttpConnection(DefaultSentryClientFactory.java:456)
        at io.sentry.DefaultSentryClientFactory.createConnection(DefaultSentryClientFactory.java:356)
        at io.sentry.DefaultSentryClientFactory.createSentryClient(DefaultSentryClientFactory.java:265)
        at io.sentry.SentryClientFactory.createClient(SentryClientFactory.java:178)
        at io.sentry.Sentry.init(Sentry.java:138)
        at io.quarkus.logging.sentry.SentryHandlerValueFactory.create(SentryHandlerValueFactory.java:40)
        at io.quarkus.deployment.steps.SentryProcessor$addSentryLogHandler-1613402751.deploy_0(SentryProcessor$addSentryLogHandler-1613402751.zig:80)
        at io.quarkus.deployment.steps.SentryProcessor$addSentryLogHandler-1613402751.deploy(SentryProcessor$addSentryLogHandler-1613402751.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:477)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:832)

Dez. 27, 2020 12:58:33 PM io.quarkus.deployment.dev.IsolatedDevModeMain firstStart
INFO: Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
Quarkus application exited with code 1
Press Enter to restart or Ctrl + C to quit
```

**To Reproduce**

Reproducer project attached:
[getting-started.zip](https://github.com/quarkusio/quarkus/files/5744529/getting-started.zip)

1. `mvn io.quarkus:quarkus-maven-plugin:1.10.5.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=getting-started     -DclassName="org.acme.getting.started.GreetingResource"     -Dpath="/hello"`
2. `cd getting-started/`
3. `./mvnw quarkus:add-extension -Dextensions="logging-sentry"`
4. `echo "quarkus.log.sentry=true" >> src/main/resources/application.properties`
5. `echo "quarkus.log.sentry.dsn=https://c8ddd5f8988545ab95d1d9a815fc508c@o367630.ingest.sentry.io/5571835" >> src/main/resources/application.properties`
6. `./mvnw compile quarkus:dev`

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.log.sentry=true
quarkus.log.sentry.dsn=https://c8ddd5f8988545ab95d1d9a815fc508c@o367630.ingest.sentry.io/5571835
```

**Screenshots**
(None)

**Environment:**
 - Output of `uname -a` or `ver`: `Linux GrumpyWorkerBee 5.8.0-33-generic #36-Ubuntu SMP Wed Dec 9 09:14:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: `openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-1, mixed mode, sharing)`
 - GraalVM version (if different from Java): Not used
 - Quarkus version or git rev: `1.10.5.Final`
 - Build tool (ie. output of `./mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/janhendriks/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 14.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-14-openjdk-amd64
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-33-generic", arch: "amd64", family: "unix"`

**Additional context**

This error was introduced somewhere around 1.9.1.Final or later if I'm not mistaken.
Feel free to use the provided Sentry dsn in this ticket for testing

**Comment by gsmet** [comment]
@ia3andy could you have a look?

**Comment by gsmet** [comment]
@ia3andy I see the Sentry extension does not depend on Jackson? Given the default client factory uses Jackson, it looks like we should add a Jackson dependency?

And if not, I don't see Jackson mentioned in the guide so it should be added there.

@DaHoC can you try to add the `quarkus-jackson` dependency to your `pom.xml` and see how it goes?

**Comment by ia3andy** [comment]
I will have a look today

**Comment by DaHoC** [comment]
Adding the dependency
```    
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jackson</artifactId>
</dependency>
```
to the reproducer project's pom.xml interestingly did not improve anything and results in the same error message

**Comment by ia3andy** [comment]
I think it might be a classloading issue as jackson is already a `sentry` dependency:

![image](https://user-images.githubusercontent.com/2223984/103632411-8b65b100-4f44-11eb-985c-e0a63b38b1d8.png)

**Comment by ia3andy** [comment]
@geoand any thought?

**Comment by geoand** [comment]
I don't have any idea just by looking at it, I'll have to a have a closer look sometime this week

**Comment by ia3andy** [comment]
code.quarkus.io app is using Sentry and works with `1.10.5.Final` (in production), I've tested, devmode is also failing, but built apps are working.

**Comment by gsmet** [comment]
@ia3andy in any case, if it depends on Jackson, we need to add a dependency to the `quarkus-jackson` extension so that needs a fix.

But looks like even with that, we end up with a CL issue in dev mode. @geoand could it be that the logging layer is loaded parent first?

**Comment by geoand** [comment]
I am pretty sure we did have some parent first stuff because of sentry, but I don't remember exactly what

**Comment by ia3andy** [comment]
@geoand https://github.com/quarkusio/quarkus/blob/master/extensions/logging-sentry/runtime/pom.xml#L35

**Comment by geoand** [comment]
I don't have time to look at this today. It will probably be end of the week, at best

**Comment by ia3andy** [comment]
I guess this is closely related: https://github.com/quarkusio/quarkus/issues/12252#issuecomment-708282472

**Comment by ia3andy** [comment]
There is a new version of Sentry `3.2.0` with major changes, I will have a look to update it as it may solve the problem..

**Comment by ia3andy** [comment]
Most recent version of Sentry seems way cleaner and without hacky init methods.

It uses "gson" instead of Jackson, I am not sure if it's good or bad.. 

Anyway, if misses a jul handler to let us update for now: https://github.com/getsentry/sentry-java/issues/1037

**Comment by geoand** [comment]
It indeed looks like the only way to make this work is to make jackson parent first - otherwise sentry (which is loaded parent-first and therefore is loaded from the system classloader) tries to load jackson and fails because Jackson is only available in the Quarkus Base Runtime Classloader.

Can you remind me why sentry was made parent first in the first place? Was it because of something with logging?
