### ISSUE TITLE
Unable to set connection pool max wait queue size

### ISSUE THREAD

**Issue by omarkad2** [quarkusio/quarkus#14059]
**Describe the bug**
I get this stack, when I have a client program opening multiple websocket connections with my quarkus application in a short amount of time:
```
2020-12-27 21:49:29,881 ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-2) Mutiny had to drop the following exception: io.vertx.core.http.ConnectionPoolTooBusyException: 
Connection pool reached max wait queue size of 6
        at io.vertx.core.http.impl.pool.Pool.lambda$nextTask$1(Pool.java:293)
        at io.vertx.core.http.impl.pool.Pool.checkPendingTasks(Pool.java:250)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected behavior**
Max wait queue size can be made unbounded via configuration.

**Actual behavior**
It seems that there is no configuration aiming to set the max queue size https://quarkus.io/guides/all-config

**To Reproduce**
Have a backend in quarkus exposing a Websocket server endpoint, and a client program openning a websocket session every 1s until it reaches 1000 connection.

**Environment (please complete the following information):**
 - Output of `uname -a`: 
 ```
Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
 ```openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)
```
 - Quarkus version or git rev:  `1.10.2.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
 ```
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: /opt/apache-maven-3.6.2
Java version: 11.0.9.1, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-58-generic", arch: "amd64", family: "unix"
```

**Comment by omarkad2** [comment]
Sorry to bother you I thought it was vertx pool of connection linked to my undertow websocket endpoint that had the problem, but I came to understand that it was vertx pool of connections of my redis clients. Closing the issue
