### ISSUE TITLE
Got java.util.zip.ZipException on running mvnw quarkus:dev

### ISSUE THREAD

**Issue by ppatierno** [quarkusio/quarkus#14108]
I tried to create a really simple application using code.quarkus.io including only the REST extension just for getting started.
After unzipping the file I run `./mvnw quarkus:dev` but got the following error:

```shell
./mvnw quarkus:dev
--2021-01-05 10:33:05--  https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.jar
Resolving repo.maven.apache.org (repo.maven.apache.org)... 151.101.240.215
Connecting to repo.maven.apache.org (repo.maven.apache.org)|151.101.240.215|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 50710 (50K) [application/java-archive]
Saving to: ‘/home/ppatiern/Downloads/test-quarkus-operator/.mvn/wrapper/maven-wrapper.jar’

/home/ppatiern/Down 100%[===================>]  49.52K  --.-KB/s    in 0.02s   

2021-01-05 10:33:05 (1.94 MB/s) - ‘/home/ppatiern/Downloads/test-quarkus-operator/.mvn/wrapper/maven-wrapper.jar’ saved [50710/50710]

Exception in thread "main" java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1567)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1375)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:169)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:86)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
```

The same happens if I create a Quarkus application using the VSCode plugin.
In order to have it working I had to delete the wrapper and takari library from Maven repo by running `rm -fR ~/.m2/repository/io/takari/ ~/.m2/wrapper/`.
It would be great having a more understandable error if possible.

**Comment by emmanuelbernard** [comment]
To be clear it's not Quarkus fault but the User experience is affected. If homehow we could detect and give good error reports, we would be semi-gods (or something like that).
In Paolo's case, `rm -fR ~/.m2/repository/io/takari/ ~/.m2/wrapper/` did the trick

**Comment by FroMage** [comment]
We can test if Maven wrapper has correct checksum by adding the `-C` option after manually truncating the jar I guess.

**Comment by FroMage** [comment]
Actually it's all in the `.mvn/wrapper/MavenWrapperDownloader.java` file we distribute. This doesn't even hit `~/.m2`. We can add the checksum checking there.

@ia3andy do you know where that file originally came from?

**Comment by FroMage** [comment]
Well, no, the stack trace indicates that the wrapper was downloaded properly, since it's called. So it's _something_ else that the wrapper downloaded that didn't work.

**Comment by ia3andy** [comment]
> Actually it's all in the `.mvn/wrapper/MavenWrapperDownloader.java` file we distribute. This doesn't even hit `~/.m2`. We can add the checksum checking there.
> 
> @ia3andy do you know where that file originally came from?

@FroMage does that help? 

https://github.com/quarkusio/quarkus/blob/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/tooling/maven-wrapper/base/.mvn/wrapper/maven-wrapper.tpl.qute.properties

and https://github.com/quarkusio/quarkus/tree/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/tooling/maven-wrapper/base

**Comment by ia3andy** [comment]
ah and the java downloader is there (but I think it's only used in last resort, no wget and no curl): https://github.com/quarkusio/quarkus/blob/master/devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/tooling/maven-wrapper/base/.mvn/wrapper/MavenWrapperDownloader.tpl.qute.java
