### ISSUE TITLE
Regression: using inherit in quarkus.log.category fails with an exception

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#14154]
**Describe the bug**
Detected on code.quarkus.io app, I get an exception using current master:
```
java.util.NoSuchElementException
        at io.quarkus.runtime.logging.InheritableLevel$Inherited.getLevel(InheritableLevel.java:77)
        at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLogging(LoggingSetupRecorder.java:140)
        at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit1765975849.deploy_0(LoggingResourceProcessor$setupLoggingRuntimeInit1765975849.zig:180)
        at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit1765975849.deploy(LoggingResourceProcessor$setupLoggingRuntimeInit1765975849.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:631)
        at io.quarkus.runtime.Application.start(Application.java:90)
```

it seems to be due to that config: 
```
quarkus.log.category."io.quarkus.code".level=${IO_QUARKUS_CODE_LOG_LEVEL:inherit}
```

@dmlloyd pointed to this commit "does not check to see whether the level is inherited": https://github.com/quarkusio/quarkus/commit/f5c4cadbc539ac5d5998988a7b639288866e3ce0

cc @galderz @gsmet

**Comment by gsmet** [comment]
@galderz I let you have a look at it? This needs to be fixed before Final so before January 12th.

**Comment by galderz** [comment]
Sure, I'll assign it to myself
