### ISSUE TITLE
MongoDB Panache Reactive with Kotlin count query on a nested field crashes

### ISSUE THREAD

**Issue by imrabti** [quarkusio/quarkus#14159]
**Describe the bug**
I execute a simple count query on a nested field in a MongoDB collection with MongoDB Panache Reactive using Kotlin code looks like this `repository.count("{'configuration.priority':  :1}", priority)`. 

**Expected behavior**
I should get the count result because when I use `repository.count(Document.parse("{\"configuration.priority\": ${configuration.priority}}")) ` without any issue.

**Actual behavior**
The code crashes with the following exception : 

```
2021-01-05 17:03:53,293 ERROR [org.jbo.res.res.i18n] (Thread-44) RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.lang.NoSuchMethodError: 'io.smallrye.mutiny.Uni io.quarkus.mongodb.panache.kotlin.reactive.runtime.KotlinReactiveMongoOperations.count(java.lang.Class, java.lang.Object, java.lang.Object[])'
    at org.myproto.config.ConfigurationRepository.count(ConfigurationRepository.kt)
    at org.myproto.config.ConfigurationRepository_ClientProxy.count(ConfigurationRepository_ClientProxy.zig:598)
    at org.myproto.config.ConfigurationService.validatePriority(ConfigurationService.kt:27)
    at org.myproto.config.ConfigurationService.access$validatePriority(ConfigurationService.kt:12)
    at org.myproto.config.ConfigurationService$addConfiguration$3.apply(ConfigurationService.kt:20)
    at org.myproto.config.ConfigurationService$addConfiguration$3.apply(ConfigurationService.kt:12)
    at io.smallrye.mutiny.groups.UniOnItem.lambda$call$2(UniOnItem.java:94)
    at io.smallrye.mutiny.operators.UniOnItemTransformToUni.invokeAndSubstitute(UniOnItemTransformToUni.java:31)
    at io.smallrye.mutiny.operators.UniOnItemTransformToUni$2.onItem(UniOnItemTransformToUni.java:74)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
    at io.smallrye.mutiny.operators.UniOnItemTransform$1.onItem(UniOnItemTransform.java:33)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
    at io.smallrye.mutiny.operators.UniDelegatingSubscriber.onItem(UniDelegatingSubscriber.java:24)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
    at io.smallrye.mutiny.operators.UniOnItemTransform$1.onItem(UniOnItemTransform.java:33)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
    at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:32)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
```

**Additional context**
The MongoDB entity looks as below :

```
@MongoEntity(collection = "configuration")
data class ConfigurationDocument(
    @field:BsonId var id: String,
    var configuration: Configuration,
    var created: LocalDateTime,
    var updated: LocalDateTime? = null
)

data class Configuration(
    var description: String,
    var id: String,
    var priority: Int,
)
```

**Comment by loicmathieu** [comment]
@imrabti you mix indexed with named parameters on your example.

Indexed parameter starts with `?` and named parameter with `:` .

It seems you want to use indexed parameters, so the correct usage would be:

```
repository.count("{'configuration.priority': ?1}", priority)
```

**Comment by loicmathieu** [comment]
@imrabti did you try with the provided code correction ?

**Comment by loicmathieu** [comment]
No news from the reporter since more than two months, I'm closing it.
@imrabti if you find the time to try the proposed corrected code and the issue still occurs, please re-open it.
