### ISSUE TITLE
Reactive graphql Nullpointer exception

### ISSUE THREAD

**Issue by mutasemhidmi** [quarkusio/quarkus#14193]
i have the below graphql api, note that when i'm not using reactive entity and not returning uni it works 

```
    @Query("allPeople")
    public Uni<List<ReactivePeopleEntity>> getPeoples(@DefaultValue("0") int page, @DefaultValue("10") int pageSize) {
        Uni<List<ReactivePeopleEntity>> data = ReactivePeopleEntity.findAll().page(0, 10).list();
        return data;
    }
```

and every time i run the application i get this error 

```
 java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor#buildExecutionService threw an exception: java.lang.NullPointerException
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:273)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.collectParametrizedTypes(ReferenceCreator.java:358)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:310)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:243)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForOperationField(ReferenceCreator.java:95)
        at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:76)
        at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:43)
        at io.smallrye.graphql.schema.SchemaBuilder.addOperations(SchemaBuilder.java:229)
        at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:107)
        at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:80)
        at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:160)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:146)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:54)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:180)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:184)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:61)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:51)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor#buildExecutionService threw an exception: java.lang.NullPointerException
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:273)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.collectParametrizedTypes(ReferenceCreator.java:358)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:310)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:243)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForOperationField(ReferenceCreator.java:95)
        at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:76)
        at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:43)
        at io.smallrye.graphql.schema.SchemaBuilder.addOperations(SchemaBuilder.java:229)
        at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:107)
        at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:80)
        at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:160)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

        at io.quarkus.builder.Execution.run(Execution.java:116)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:149)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:250)
        ... 11 more
Caused by: java.lang.NullPointerException
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:273)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.collectParametrizedTypes(ReferenceCreator.java:358)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:310)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:243)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForOperationField(ReferenceCreator.java:95)
        at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:76)
        at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:43)
        at io.smallrye.graphql.schema.SchemaBuilder.addOperations(SchemaBuilder.java:229)
        at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:107)
        at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:80)
        at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:160)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Comment by geoand** [comment]
cc @phillip-kruger

**Comment by phillip-kruger** [comment]
Hi @mutasemhidmi - What version of Quarkus are you using ?

**Comment by mutasemhidmi** [comment]
@phillip-kruger 1.9.2.Final should i upgrade ? note that when i used completionstage it worked

**Comment by phillip-kruger** [comment]
Yes, Uni support is only added in 1.10.x, please give that a try and let me know

**Comment by mutasemhidmi** [comment]
it worked thanks
