### ISSUE TITLE
SmallRye GraphQL - NPE when accessing schema if no methods declared

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#14257]
If I add the GraphQL extension and have no GraphQL service, I end up with the following error when accessing the schema:

```
2021-01-12 18:26:30,719 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-10) HTTP Request to /graphql/schema.graphql failed, error id: f92243fa-2f65-466b-9213-be52f858a862-3: java.lang.NullPointerException
at graphql.schema.idl.SchemaPrinter.print(SchemaPrinter.java:323)
at io.smallrye.graphql.execution.SchemaPrinter.print(SchemaPrinter.java:20)
at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLSchemaHandler.handle(SmallRyeGraphQLSchemaHandler.java:30)
at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLSchemaHandler.handle(SmallRyeGraphQLSchemaHandler.java:18)
at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gsmet** [comment]
I also got:
```
2021-01-12 20:40:50,193 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-7) HTTP Request to /graphql failed, error id: 778abaf3-25c5-4993-9252-c26f98536cb3-2: java.lang.NullPointerException
	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:52)
	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:56)
	at io.vertx.core.buffer.impl.BufferFactoryImpl.buffer(BufferFactoryImpl.java:39)
	at io.vertx.core.buffer.Buffer.buffer(Buffer.java:72)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:113)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:93)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:64)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:37)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
when going to the GraphQL UI.

Looks slightly related but it's not the same error.
