### ISSUE TITLE
DEV Console - Internal Server Error when deploying to OpenShift and not logged in

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#14253]
In the UI, we end up with `Internal Server Error` whereas we should have a nice error page explaining what's going wrong.

Also, this action takes time so we should probably have something to monitor progress.

Error is:
```
2021-01-12 15:45:23,650 ERROR [io.qua.ver.htt.dep.dev.con.DevConsoleProcessor] (DEV Console action) Dev console request failed : java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.container.image.openshift.deployment.OpenshiftProcessor#openshiftBuildFromJar threw an exception: io.dekorate.deps.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://api.pro-us-east-1.openshift.com/apis/image.openshift.io/v1/namespaces/quarkusio/imagestreams/openjdk-11. Message: Forbidden! User gsmet@redhat.com/api-pro-us-east-1-openshift-com:443 doesn't have permission. imagestreams.image.openshift.io "openjdk-11" is forbidden: User "system:anonymous" cannot get imagestreams.image.openshift.io in the namespace "quarkusio": no RBAC policy matched.
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:505)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:395)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:376)
	at io.dekorate.deps.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:845)
	at io.dekorate.deps.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:214)
	at io.dekorate.deps.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:168)
	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.applyOpenshiftResources(OpenshiftProcessor.java:356)
	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.createContainerImage(OpenshiftProcessor.java:329)
	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuildFromJar(OpenshiftProcessor.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:274)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:109)
	at io.quarkus.container.image.deployment.devconsole.RebuildHandler.handlePostAsync(RebuildHandler.java:40)
	at io.quarkus.devconsole.runtime.spi.DevConsolePostHandler$2.run(DevConsolePostHandler.java:40)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.container.image.openshift.deployment.OpenshiftProcessor#openshiftBuildFromJar threw an exception: io.dekorate.deps.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://api.pro-us-east-1.openshift.com/apis/image.openshift.io/v1/namespaces/quarkusio/imagestreams/openjdk-11. Message: Forbidden! User gsmet@redhat.com/api-pro-us-east-1-openshift-com:443 doesn't have permission. imagestreams.image.openshift.io "openjdk-11" is forbidden: User "system:anonymous" cannot get imagestreams.image.openshift.io in the namespace "quarkusio": no RBAC policy matched.
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:505)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:395)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:376)
	at io.dekorate.deps.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:845)
	at io.dekorate.deps.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:214)
	at io.dekorate.deps.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:168)
	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.applyOpenshiftResources(OpenshiftProcessor.java:356)
	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.createContainerImage(OpenshiftProcessor.java:329)
	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuildFromJar(OpenshiftProcessor.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:116)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:148)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:272)
	... 4 more
Caused by: io.dekorate.deps.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://api.pro-us-east-1.openshift.com/apis/image.openshift.io/v1/namespaces/quarkusio/imagestreams/openjdk-11. Message: Forbidden! User gsmet@redhat.com/api-pro-us-east-1-openshift-com:443 doesn't have permission. imagestreams.image.openshift.io "openjdk-11" is forbidden: User "system:anonymous" cannot get imagestreams.image.openshift.io in the namespace "quarkusio": no RBAC policy matched.
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:505)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:395)
	at io.dekorate.deps.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:376)
	at io.dekorate.deps.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:845)
	at io.dekorate.deps.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:214)
	at io.dekorate.deps.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:168)
	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.applyOpenshiftResources(OpenshiftProcessor.java:356)
	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.createContainerImage(OpenshiftProcessor.java:329)
	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuildFromJar(OpenshiftProcessor.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by geoand** [comment]
We definitely need some better error handling.

I'll add a basic error message. As discussed with @stuartwdouglas and @FroMage when the console was being developed, we'll also want to support streaming logs back to the dev console at some point

**Comment by geoand** [comment]
Actually, are you sure you hadn't logged in?

**Comment by brunobaiano** [comment]
I'm testing deploy and I was  logged out....
I have this message:
User "system:anonymous" cannot delete services in the namespace "my-namespace": no RBAC policy matched.

I'm using 
quarkus.kubernetes-client.master-url=${OKD_HOST}
quarkus.kubernetes-client.username=${OKD_USERNAME}
quarkus.kubernetes-client.password=${OKD_PASSWORD}

He builds on the server but show this message. Because image change... i can see that a new deploy occurs ok on the server.

**Comment by geoand** [comment]
Is this still an issue?
