### ISSUE TITLE
Hibernate Reactive Schema Validation Fails

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#14264]
If you set `quarkus.hibernate-orm.database.generation=validate` then the app fails to start:

```
2021-01-13 09:56:18,206 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): org.hibernate.HibernateException: DdlTransactionIsolatorJtaImpl could not locate TransactionManager to suspend any current transaction; base JtaPlatform impl (org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform@2978458)?

	at org.hibernate.resource.transaction.backend.jta.internal.DdlTransactionIsolatorJtaImpl.<init>(DdlTransactionIsolatorJtaImpl.java:46)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorBuilderImpl.buildDdlTransactionIsolator(JtaTransactionCoordinatorBuilderImpl.java:46)
	at org.hibernate.tool.schema.internal.HibernateSchemaManagementTool.getDdlTransactionIsolator(HibernateSchemaManagementTool.java:188)
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:59)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:192)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:316)
	at org.hibernate.reactive.session.impl.ReactiveSessionFactoryImpl.<init>(ReactiveSessionFactoryImpl.java:33)
	at io.quarkus.hibernate.reactive.runtime.boot.FastBootReactiveEntityManagerFactoryBuilder.build(FastBootReactiveEntityManagerFactoryBuilder.java:31)
	at io.quarkus.hibernate.reactive.runtime.FastBootHibernateReactivePersistenceProvider.createEntityManagerFactory(FastBootHibernateReactivePersistenceProvider.java:83)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:117)
	at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:41)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:88)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits951856026.deploy_0(HibernateOrmProcessor$startPersistenceUnits951856026.zig:74)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits951856026.deploy(HibernateOrmProcessor$startPersistenceUnits951856026.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:674)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Sanne** [comment]
Thanks Stuart. We're having an unexpected mix of JTA and non-JTA components, I suspect this is a bug with the Quarkus extension with Hibernate Reactive - probably related to what I mentioned during the team meeting yesterday: that some JTA related components are being initialized.

We'll look, it shouldn't bind to JTA.

**Comment by yrodiere** [comment]
@Sanne I had a look. We're indeed configuring Hibernate Reactive in JTA mode and we shouldn't. However, the problem is deeper: I think Hibernate Reactive only support DDL "write" operations, through a custom `GenerationTarget` (which successfully abstracts from JDBC). The code that performs DDL "reads" (e.g. for validation) is entirely in Hibernate ORM, and it uses JDBC all the way down. So dropping or creating the schema works, but validating or migrating doesn't.

I'll submit a PR to move away from JTA, but I believe schema validation will require more work in Hibernate Reactive and ORM.

**Comment by Sanne** [comment]
thanks @yrodiere ! Yes let's focus on the non-JTA aspect first.

For the update/validate schema features, could you open an issue on hibernate reactive? I didn't know about this, maybe it's not too hard to implement.

**Comment by gavinking** [comment]
I'm pretty sure it's quite hard. Though certainly not impossible.

**Comment by yrodiere** [comment]
A comment by @gavinking on the Hibernate Reactive ticket:

> OTOH if you do have a JDBC driver, it should happily just use it.

Currently I don't think we inject a JDBC driver in Hibernate Reactive persistence units, ever. From what I understand the datasource is injected by `io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider#injectDataSource` for Hibernate ORM, but that method is simply absent for the Hibernate Reactive extension.

Maybe it would make sense to inject a JDBC driver in some specific cases, so as to "degrade gracefully" for features that are still implemented using JDBC in Hibernate Reactive? Not sure how easy it would be to detect when we can (or should) do this, though.

**Comment by gavinking** [comment]
I'm not sure. And TBOH i'm not 100% sure it even still works because I know we don't have tests for it anymore.
