### ISSUE TITLE
Fabric8 Kubernetes client Quarkus extensio: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by ppatierno** [quarkusio/quarkus#14299]
I am using the Java operator SDK Quarkus extension to develop and operator and I am injecting the Fabric8 Kubernetes client.
If I start the operator locally when a local minikube instance is running, everything is fine.
When I oc login into an OpenShift 4.6 cluster, I got the following error when the operator starts:

```shell
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:135)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.fabric8.kubernetes.client.utils.OIDCTokenRefreshInterceptor.intercept(OIDCTokenRefreshInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:151)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:490)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:451)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:416)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:397)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:933)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:220)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:186)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:84)
        at io.javaoperatorsdk.operator.Operator.getCustomResourceDefinitionForController(Operator.java:145)
        at io.javaoperatorsdk.operator.Operator.registerController(Operator.java:79)
        at io.javaoperatorsdk.operator.Operator.register(Operator.java:46)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at io.javaoperatorsdk.quarkus.extension.OperatorProducer.operator(OperatorProducer.java:24)
        at io.javaoperatorsdk.quarkus.extension.OperatorProducer_ProducerMethod_operator_fbb974dfbf959b9d8a2fb82741b74256904c7c58_Bean.create(OperatorProducer_ProducerMethod_operator_fbb974dfbf959b9d8a2fb82741b74256904c7c58_Bean.zig:187)
        at io.javaoperatorsdk.quarkus.extension.OperatorProducer_ProducerMethod_operator_fbb974dfbf959b9d8a2fb82741b74256904c7c58_Bean.create(OperatorProducer_ProducerMethod_operator_fbb974dfbf959b9d8a2fb82741b74256904c7c58_Bean.zig:202)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at io.javaoperatorsdk.quarkus.extension.OperatorProducer_ProducerMethod_operator_fbb974dfbf959b9d8a2fb82741b74256904c7c58_Bean.get(OperatorProducer_ProducerMethod_operator_fbb974dfbf959b9d8a2fb82741b74256904c7c58_Bean.zig:234)
        at io.javaoperatorsdk.quarkus.extension.OperatorProducer_ProducerMethod_operator_fbb974dfbf959b9d8a2fb82741b74256904c7c58_Bean.get(OperatorProducer_ProducerMethod_operator_fbb974dfbf959b9d8a2fb82741b74256904c7c58_Bean.zig:250)
        at org.bf2.operator.AgentOperator_Bean.create(AgentOperator_Bean.zig:306)
        at org.bf2.operator.AgentOperator_Bean.create(AgentOperator_Bean.zig:347)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
        at org.bf2.operator.AgentOperator_ClientProxy.arc$delegate(AgentOperator_ClientProxy.zig:67)
        at org.bf2.operator.AgentOperator_ClientProxy.run(AgentOperator_ClientProxy.zig:126)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

The workaround I have got is to add `quarkus.kubernetes-client.trust-certs=true` in the application.properties but as I said it's not needed with minikube (I haven't tried with a remote vanilla Kubernetes cluster anyway).
What I tried is using the "pure" Java Fabric8 k8s client in a simple apple and it just works.
Is there any kind of issue with the Fabric8 k8s client Quarkus extension? Because I guess Quarkus is using the `DefaultKubernetesClient` under the hood, it seems to ignore `insecure-skip-tls-verify: true` which is in the cluster description of my kubeconfig.

**Comment by geoand** [comment]
cc @metacosm

**Comment by ppatierno** [comment]
I also see these three lines before the exception with `DEBUG` level. It's trying to use the kubeconfig (3 times?), maybe something goes wrong?

```shell
2021-01-14 13:35:54,448 DEBUG [io.fab.kub.cli.Config] (Quarkus Main Thread) Trying to configure client from Kubernetes config...
2021-01-14 13:35:54,449 DEBUG [io.fab.kub.cli.Config] (Quarkus Main Thread) Found for Kubernetes config at: [/home/ppatiern/.kube/config].
2021-01-14 13:35:54,546 DEBUG [io.fab.kub.cli.Config] (Quarkus Main Thread) Trying to configure client from Kubernetes config...
2021-01-14 13:35:54,546 DEBUG [io.fab.kub.cli.Config] (Quarkus Main Thread) Found for Kubernetes config at: [/home/ppatiern/.kube/config].
2021-01-14 13:35:54,551 DEBUG [io.fab.kub.cli.Config] (Quarkus Main Thread) Trying to configure client from Kubernetes config...
2021-01-14 13:35:54,552 DEBUG [io.fab.kub.cli.Config] (Quarkus Main Thread) Found for Kubernetes config at: [/home/ppatiern/.kube/config].
```

**Comment by maxandersen** [comment]
can you show what you have in the kube config ? (sans secrets)

**Comment by maxandersen** [comment]
I have a vague memory of us turning on stricter use of TLS/ssh verifications somewhere - and i'm wondering if that is what we are seeing here and that overrides the config in kubeconfig.

**Comment by maxandersen** [comment]
@ppatierno I say your workaround `quarkus.kubernetes-client.trust-certs=true` is the correct one. 
I predict this is simply a bug at the moment where quarkus more secure defaults ends up overriding kubernetes client settings.

@iocanel wdyt?

**Comment by ppatierno** [comment]
so the kubeconfig has the following:

```yaml
- cluster:
    insecure-skip-tls-verify: true
    server: https://<address>:6443
  name: <address>:6443
```

and 

```yaml
- context:
    cluster: <address>:6443
    namespace: default
    user: <user>
  name: default/<address>:6443/<user>
```

We guess that it's ignoring the `insecure-skip-tls-verify: true` flag.

**Comment by iocanel** [comment]
Needs to be addressed on the client-side. Will fix it there!

**Comment by iocanel** [comment]
@ppatierno: I am failing to reproduce the issue. I have created and committed a unit test, that verifies that the `insecure-skip-tls-verify` is properly respected. Here's a link to the test config: https://github.com/quarkusio/quarkus/blob/master/extensions/kubernetes-client/runtime/src/test/resources/test-kubeconfig

I am wondering if in your case, the `current-context` is not the `default/<address>:6443/<user>`.

If you still have issues, please provide a full `kubeconfig`, so that we can reproduce.

**Comment by iocanel** [comment]
@ppatierno: As this can be reproduced and a test that validates correct behavior has been added, I feel that we should close this.
If I missed something, feel free to re-open I'll gladly have a second look.
