### ISSUE TITLE
Run ./gradlew quarkusBuild failed when setting 'quarkus.docker.dockerfile-jvm-path' in multi module of gradle project

### ISSUE THREAD

**Issue by River-java** [quarkusio/quarkus#14312]
**Describe the bug**
(Describe the problem clearly and concisely.)
Run quarkusBuild would be failed when specifying the docker file path to the sub-module.  

**Expected behavior**
The application project and image would build successfully. 

**Actual behavior**
```
Execution failed for task ':application:quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromJar threw an exception: java.lang.IllegalArgumentException: Specified Dockerfile path /Users/bob/work/personal projects/quakusio/my-artifactId/application/src/main/docker/Dockerfile.local does not exist
        at io.quarkus.container.image.docker.deployment.DockerProcessor$ProvidedDockerfile.get(DockerProcessor.java:342)
        at io.quarkus.container.image.docker.deployment.DockerProcessor.getDockerfilePaths(DockerProcessor.java:227)
        at io.quarkus.container.image.docker.deployment.DockerProcessor.createContainerImage(DockerProcessor.java:134)
        at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerBuildFromJar(DockerProcessor.java:86)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

But the docker file does exist in the specified path. I tried to update the path to 
`quarkus.docker.dockerfile-jvm-path=application/src/main/docker/Dockerfile.local`
still get error:
```
Execution failed for task ':application:quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromJar threw an exception: java.lang.RuntimeException: Execution of 'docker build -f /Users/bob/work/personal projects/quakusio/my-artifactId/application/application/src/main/docker/Dockerfile.local -t bob/application:unspecified /Users/bob/work/personal projects/quakusio/my-artifactId/application' failed. See docker output for more details
        at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerException(DockerProcessor.java:184)
        at io.quarkus.container.image.docker.deployment.DockerProcessor.createContainerImage(DockerProcessor.java:130)
        at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerBuildFromJar(DockerProcessor.java:79)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```
Because the path **/application** is duplicated.
`docker build -f /Users/bob/work/personal projects/quakusio/my-artifactId/application/application/src/main/docker/Dockerfile.local -t bob/application:unspecified /Users/bob/work/personal projects/quakusio/my-artifactId/application`

**To Reproduce**
1. add quarkus-container-image-docker dependency. 
2. add config to the application.properties
```
   quarkus.container-image.build=true
   quarkus.docker.dockerfile-jvm-path=src/main/docker/Dockerfile.local
```
3. Execute
`./gradlew application:quarkusBuild`

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
![image](https://user-images.githubusercontent.com/77440548/104675245-16eaf900-5720-11eb-9d53-6d2f4e13f500.png)

The screenshot is the multi-module gradle project structure

**Environment (please complete the following information):**
Quarkus version: 1.5.2.Final
JDK version: 11.0.9

**Comment by geoand** [comment]
@River-java do you have perhaps have a reproducer project to share?

Furthermore, can you try with more recent versions of Quarkus? `1.5.2` is quite old :)

**Comment by glefloch** [comment]
I just reproduced the error with the latests master branch. I'm having a look at the error.

**Comment by River-java** [comment]
@glefloch @geoand Thank you.
