### ISSUE TITLE
Liquibase hot reload - This pool is closed and does not handle any more connections!

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#14341]
**Describe the bug**
I am starting a new quarkus project which uses the quarkus-liquibase extension.

On normal quarkus start (mvn quarkus;dev), the liquibase changesets are run fine.

On hot reload, I get the exception from below.

**Expected behavior**
Liquibase migrations are executed succefully on hot reload.

**Actual behavior**
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
        at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:145)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:190)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:174)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:237)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:62)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:52)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:907)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        ... 1 more
Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: java.sql.SQLException: This pool is closed and does not handle any more connections!
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:54)
        at io.quarkus.deployment.steps.LiquibaseProcessor$createBeansAndStartActions-960013254.deploy_0(LiquibaseProcessor$createBeansAndStartActions-960013254.zig:80)
        at io.quarkus.deployment.steps.LiquibaseProcessor$createBeansAndStartActions-960013254.deploy(LiquibaseProcessor$createBeansAndStartActions-960013254.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:698)
        ... 12 more
Caused by: java.lang.IllegalStateException: java.sql.SQLException: This pool is closed and does not handle any more connections!
        at io.quarkus.liquibase.LiquibaseFactory.createLiquibase(LiquibaseFactory.java:78)
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:44)
        ... 15 more
Caused by: java.sql.SQLException: This pool is closed and does not handle any more connections!
        at io.agroal.pool.ConnectionPool.beforeAcquire(ConnectionPool.java:199)
        at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:206)
        at io.agroal.pool.DataSource.getConnection(DataSource.java:81)
        at io.quarkus.liquibase.LiquibaseFactory.createLiquibase(LiquibaseFactory.java:53)
        ... 16 more
```

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Download the reproducer: [settingsservice.zip](https://github.com/quarkusio/quarkus/files/5825212/settingsservice.zip)

2. Start the database: docker compose up -d
3. Start quarkus: mvn clean compile quarkus:dev. Notice that it just starts.
4. Now, add a new Method into SettingService for example, to force a hot reload without instrumentation. Visit localhost:8080 to trigger the hot reload itself.
5. Exception from above happens, no database changes are executed.

**Configuration**
```properties
quarkus.datasource.db-kind=mariadb
quarkus.liquibase.migrate-at-start=true

%dev.quarkus.datasource.username=root
%dev.quarkus.datasource.password=root
%dev.quarkus.datasource.jdbc.url=jdbc:mariadb://localhost:3400/settings
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux martin 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
 - Quarkus version or git rev: 
 - 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):
 Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/martin/.sdkman/candidates/maven/current
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: /home/martin/.sdkman/candidates/java/11.0.7-zulu
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-38-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Hm...

I don't remember ever seeing anything like this before... @gsmet have you?

**Comment by gsmet** [comment]
Nope, never saw this error.

But I reproduced it, will see if I can get a fix.

**Comment by gsmet** [comment]
Ah ah this is a funny one. I spotted it by reading the code. Will work on a fix.
