### ISSUE TITLE
Upgrade from 1.11.0.Beta1 to 1.11.0.CR1 - Native image Build failure

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#14414]
**Describe the bug**
I upgraded my existing project from 1.11.0.Beta1 to 1.11.0.CR1 and getting build failure during native image build.

**Expected behavior**
Native image build should succeed 

**Actual behavior**
Stack trace
```java
Error: Unsupported features in 3 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved field during parsing: io.quarkus.runtime.logging.LogConfig.minLevel. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing field is then reported at run time when it is accessed the first time.
Trace:
	at parsing io.quarkus.runtime.generated.Config.initGroup$io$quarkus$runtime$logging$LogConfig(Config.zig:51190)
Call path from entry point to io.quarkus.runtime.generated.Config.initGroup$io$quarkus$runtime$logging$LogConfig(SmallRyeConfig, StringBuilder, Object):
	at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$runtime$logging$LogConfig(Config.zig:51100)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:1876)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:42)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:443)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLogging(io.quarkus.runtime.logging.LogConfig, java.util.List, java.util.List, java.util.List, io.quarkus.runtime.RuntimeValue). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
	at parsing io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2028700189.deploy_0(LoggingResourceProcessor$setupLoggingRuntimeInit2028700189.zig:167)
Call path from entry point to io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2028700189.deploy_0(StartupContext, Object[]):
	at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2028700189.deploy_0(LoggingResourceProcessor$setupLoggingRuntimeInit2028700189.zig:54)
	at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2028700189.deploy(LoggingResourceProcessor$setupLoggingRuntimeInit2028700189.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:531)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.quarkus.runtime.ConfigChangeRecorder. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace:
	at parsing io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange-1100481704.deploy_0(ConfigGenerationBuildStep$checkForBuildTimeConfigChange-1100481704.zig:2149)
Call path from entry point to io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange-1100481704.deploy_0(StartupContext, Object[]):
	at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange-1100481704.deploy_0(ConfigGenerationBuildStep$checkForBuildTimeConfigChange-1100481704.zig:53)
	at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange-1100481704.deploy(ConfigGenerationBuildStep$checkForBuildTimeConfigChange-1100481704.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:597)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
```

**Configuration**
```properties
## Logging CONSOLE & GELF
quarkus.log.level=${LOG_LEVEL:INFO}
quarkus.log.category."org.apache.http".level=${quarkus.log.level}
quarkus.log.category."io.quarkus".level=${quarkus.log.level}
quarkus.log.category."software.amazon.awssdk.auth.credentials".level=${quarkus.log.level}

quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=tcp:${GELF_HOST:localhost}
quarkus.log.handler.gelf.port=12201
quarkus.log.handler.gelf.timestamp-pattern=yyyy-MM-dd'T'HH:mm:ss.SSSZ
quarkus.log.handler.gelf.facility=${quarkus.application.name}
quarkus.log.handler.gelf.include-log-message-parameters=false
quarkus.log.handler.gelf.include-location=false

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: mac & Linux x64
 - Output of `java -version`: Java 11
 - GraalVM version (if different from Java): 20.3.0.r11-grl
 - Quarkus version or git rev: 1.11.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvnw

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
@galderz I believe this is one for you :)

**Comment by galderz** [comment]
`io.quarkus.runtime.logging.LogConfig.minLevel` has been migrated to be a build time configuration option, see [here](https://github.com/quarkusio/quarkus/commit/f5c4cadbc539ac5d5998988a7b639288866e3ce0#diff-5a15a9bc4b329e3f789746a269f641ce8034f1830839d8b9f830f93576a943edL43). It'd appear that you have not updated your compile dependencies to Quarkus `1.11.0.CR1`? I can only explain your issue if you're compile dependencies are still `1.11.0.Beta1` or before.

**Comment by missourian55** [comment]
Thank you! Once I upgraded the quarkus plugin version the error went away.
