### ISSUE TITLE
Multiple Blaze-Persistence instances error when using simple bootstrapped application

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#14445]
Multiple Blaze-Persistence instances error when using simple bootstrapped application from code.quarkus without anything else. Tested with Quarkus 1.11.

This is bad out of the box experience for users.
Quarkus should boot without so many error messages, tbh not sure where multiple instances could appear from as indicated in the log message.

Reproducer:
```
wget -q -O xx.zip https://code.quarkus.io/api/download?s=weW
unzip -q xx.zip
cd code-with-quarkus
mvn quarkus:dev
```

Error message:
```
2021-01-20 18:22:24,085 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step com.blazebit.persistence.integration.quarkus.deployment.BlazePersistenceProcessor#buildBlazePersistenceInstanceDescriptors threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Multiple Blaze-Persistence instances are defined but the entity views are not mapped to them. You should either use the .packages Quarkus configuration property or package-level @BlazePersistenceInstance annotations.
	at com.blazebit.persistence.integration.quarkus.deployment.BlazePersistenceProcessor.mapBlazePersistenceInstancesToPackages(BlazePersistenceProcessor.java:465)
	at com.blazebit.persistence.integration.quarkus.deployment.BlazePersistenceProcessor.buildBlazePersistenceInstanceDescriptors(BlazePersistenceProcessor.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:274)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:150)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:57)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:78)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:372)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:128)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:81)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:144)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step com.blazebit.persistence.integration.quarkus.deployment.BlazePersistenceProcessor#buildBlazePersistenceInstanceDescriptors threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Multiple Blaze-Persistence instances are defined but the entity views are not mapped to them. You should either use the .packages Quarkus configuration property or package-level @BlazePersistenceInstance annotations.
	at com.blazebit.persistence.integration.quarkus.deployment.BlazePersistenceProcessor.mapBlazePersistenceInstancesToPackages(BlazePersistenceProcessor.java:465)
	at com.blazebit.persistence.integration.quarkus.deployment.BlazePersistenceProcessor.buildBlazePersistenceInstanceDescriptors(BlazePersistenceProcessor.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:116)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:148)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:272)
	... 9 more
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Multiple Blaze-Persistence instances are defined but the entity views are not mapped to them. You should either use the .packages Quarkus configuration property or package-level @BlazePersistenceInstance annotations.
	at com.blazebit.persistence.integration.quarkus.deployment.BlazePersistenceProcessor.mapBlazePersistenceInstancesToPackages(BlazePersistenceProcessor.java:465)
	at com.blazebit.persistence.integration.quarkus.deployment.BlazePersistenceProcessor.buildBlazePersistenceInstanceDescriptors(BlazePersistenceProcessor.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by Mobe91** [comment]
This log message is misleading.
I have created https://github.com/Blazebit/blaze-persistence/pull/1251 which will log a warning message similar to Agroal without JDBC datasources in case no persistence unit is defined and will allow the application to start.

**Comment by gsmet** [comment]
Thanks @Mobe91 . Let's close the issue here.
