### ISSUE TITLE
Funqy Knative events quickstart failing with NPE

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#14448]
Building the development branch of the quickstarts with current master, I end up with:

```
2021-01-20 18:26:22,342 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to / failed, error id: e283732b-23a6-42a3-be41-21de8aae01b6-1: java.lang.NullPointerException
	at io.quarkus.funqy.runtime.bindings.knative.events.VertxRequestHandler.isSupportedSpecVersion(VertxRequestHandler.java:369)
	at io.quarkus.funqy.runtime.bindings.knative.events.VertxRequestHandler.lambda$processCloudEvent$4(VertxRequestHandler.java:142)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by matejvasek** [comment]
I am on it.

**Comment by matejvasek** [comment]
I think I know what's wrong.

**Comment by matejvasek** [comment]
@gsmet Where should I create PR devel or master?

**Comment by matejvasek** [comment]
I see devel it is.

**Comment by geoand** [comment]
Yes, PRs go against the development branch

**Comment by gsmet** [comment]
@matejvasek I see you fixed it in the quickstart but shouldn't the Quarkus code be made a bit more safe?

**Comment by matejvasek** [comment]
Absolutely, I am adding nullcheck. It should return 400 not 500.

**Comment by patriot1burke** [comment]
I wish you would just remove the check entirely.  Spec should remain backward compatible and if there is a version bump you don't want to have to deploy hundreds or thousands of functions

**Comment by geoand** [comment]
Is this still an issue?

**Comment by patriot1burke** [comment]
I'll check.  Remind me tomorrow morning if I don't get back to you.

**Comment by geoand** [comment]
@patriot1burke ping 🙂

**Comment by matejvasek** [comment]
@patriot1burke has this been fixed?

**Comment by matejvasek** [comment]
@patriot1burke this could be closed, right?
