### ISSUE TITLE
Uber jar packaging fails when deploying to OpenShift

### ISSUE THREAD

**Issue by fhavel** [quarkusio/quarkus#14476]
**Describe the bug**
When deploying to OpenShift during Maven build, it fails. Package is set to uber jar: `quarkus.package.type=uber-jar`. Until Quarkus version 1.10.3.Final it works fine.

**Expected behavior**
Maven build would success and deployment is done

**Actual behavior**
Maven build fails with exception:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.11.0.Final:build (default) on project test-app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.container.image.openshift.deployment.OpenshiftProcessor#openshiftBuildFromJar threw an exception: java.lang.RuntimeException: Error creating the openshift binary build archive.
[ERROR]         at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.createContainerImage(OpenshiftProcessor.java:332)
[ERROR]         at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuildFromJar(OpenshiftProcessor.java:271)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.NullPointerException
[ERROR]         at io.dekorate.utils.Packaging.lambda$packageFile$0(Packaging.java:91)
[ERROR]         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[ERROR]         at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[ERROR]         at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR]         at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[ERROR]         at io.dekorate.utils.Packaging.packageFile(Packaging.java:92)
[ERROR]         at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.createContainerImage(OpenshiftProcessor.java:327)
[ERROR]         ... 11 more
```

**To Reproduce**
1. create Quarkus project with RESTEasy and OpenShift extensions
2. put `quarkus.package.type=uber-jar` into application.properties
3. run `mvn clean package -Dquarkus.kubernetes.deploy=true`

**Configuration**
```properties
quarkus.package.type=uber-jar
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: openjdk version "11.0.8" 2020-07-14 LTS
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
@iocanel this looks like a dekorate issue. Can you please take a look?

**Comment by iocanel** [comment]
Sorry for the delay. I was a bit snowed! 
Looking at it right now!
