### ISSUE TITLE
OidcClientFilter usage throws NoSuchFieldException

### ISSUE THREAD

**Issue by bwand** [quarkusio/quarkus#14474]
**Describe the bug**
I am very happy about the new feature but when trying to use the Annotation @OidcClientFilter i always get a no such field exception.

**Expected behavior**
No exception should be thrown and Annotation shuld care about getting token

**Actual behavior**
Just adding the @OidcClientFilter Annotation and try sending a request gives an Exception.
```
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: tokenRequestState
	at java.base/java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:349)
	at java.base/java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:116)
	at io.quarkus.oidc.client.runtime.TokensHelper.<clinit>(TokensHelper.java:13)
```

**To Reproduce**

1. Added dependencies (quarkus-oidc-client and quarkus-oidc-client-filer) to pom. 
2. Added Config stuff to application.properties
3. Used Annotation in a RestClient
4. Start Application works
5. Sending a request which should use the annoated Rest Client gives a NoSuchField Exception

```
2021-01-21 11:32:58,050 ERROR [io.und.req.io] (executor-thread-199) Exception handling request a1d0e101-4307-413d-86e1-c607b4fbe9b8-1 to /admin/api/users: org.jboss.resteasy.spi.UnhandledException: java.lang.ExceptionInInitializerError
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
	at io.quarkus.resteasy.runtime.ResteasyServlet.service(ResteasyServlet.java:19)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.quarkus.undertow.runtime.RewriteCorrectingHandlerWrappers$PostWrapper$1.handleRequest(RewriteCorrectingHandlerWrappers.java:51)
	at io.undertow.predicate.PredicatesHandler.handleRequest(PredicatesHandler.java:110)
	at io.quarkus.undertow.runtime.RewriteCorrectingHandlerWrappers$PreWrapper$1.handleRequest(RewriteCorrectingHandlerWrappers.java:31)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:572)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:91)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:117)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
	at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:398)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.ExceptionInInitializerError
	at io.quarkus.oidc.client.runtime.AbstractTokensProducer.<init>(AbstractTokensProducer.java:21)
	at io.quarkus.oidc.client.filter.OidcClientRequestFilter.<init>(OidcClientRequestFilter.java:22)
	at io.quarkus.oidc.client.filter.OidcClientRequestFilter_Bean.create(OidcClientRequestFilter_Bean.zig:220)
	at io.quarkus.oidc.client.filter.OidcClientRequestFilter_Bean.create(OidcClientRequestFilter_Bean.zig:329)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.oidc.client.filter.OidcClientRequestFilter_Bean.get(OidcClientRequestFilter_Bean.zig:361)
	at io.quarkus.oidc.client.filter.OidcClientRequestFilter_Bean.get(OidcClientRequestFilter_Bean.zig:377)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:435)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:448)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:271)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:268)
	at io.quarkus.arc.runtime.BeanContainerImpl$1.create(BeanContainerImpl.java:35)
	at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:39)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.injectedInstance(ResteasyProviderFactoryImpl.java:1398)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.newInstanceOf(RestClientBuilderImpl.java:475)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.register(RestClientBuilderImpl.java:487)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.register(RestClientBuilderImpl.java:62)
	at io.quarkus.restclient.runtime.RestClientBase.configureProviders(RestClientBase.java:206)
	at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:66)
	at com.im.flows.admin.client.UsersClient_641b798c6653bbbac57b253fe06c2fac36a1394f_Synthetic_Bean.create(UsersClient_641b798c6653bbbac57b253fe06c2fac36a1394f_Synthetic_Bean.zig:225)
	at com.im.flows.admin.client.UsersClient_641b798c6653bbbac57b253fe06c2fac36a1394f_Synthetic_Bean.create(UsersClient_641b798c6653bbbac57b253fe06c2fac36a1394f_Synthetic_Bean.zig:241)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
	at com.im.flows.admin.client.UsersClient_641b798c6653bbbac57b253fe06c2fac36a1394f_Synthetic_ClientProxy.arc$delegate(UsersClient_641b798c6653bbbac57b253fe06c2fac36a1394f_Synthetic_ClientProxy.zig:68)
	at com.im.flows.admin.client.UsersClient_641b798c6653bbbac57b253fe06c2fac36a1394f_Synthetic_ClientProxy.getUsers(UsersClient_641b798c6653bbbac57b253fe06c2fac36a1394f_Synthetic_ClientProxy.zig:131)
	at com.im.flows.admin.boundary.UsersResource.getUsers(UsersResource.java:46)
	at com.im.flows.admin.boundary.UsersResource_ClientProxy.getUsers(UsersResource_ClientProxy.zig:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 52 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: tokenRequestState
	at java.base/java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:349)
	at java.base/java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:116)
	at io.quarkus.oidc.client.runtime.TokensHelper.<clinit>(TokensHelper.java:13)
	... 106 more
Caused by: java.lang.NoSuchFieldException: tokenRequestState
	at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
	at java.base/java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl$1.run(AtomicReferenceFieldUpdater.java:335)
	at java.base/java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl$1.run(AtomicReferenceFieldUpdater.java:333)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:332)
	... 108 more
```

**Configuration**
```properties
quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/flows
quarkus.oidc.client-id=admin
quarkus.oidc.credentials.secret=XXXXXXXXXXXXXXXXXXXXX
quarkus.oidc.connection-delay=90S
quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin bwand-mac.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.2" 2019-01-15
 - GraalVM version (if different from Java): No Native Build
 - Quarkus version or git rev: powered by Quarkus 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Comment by sberyozkin** [comment]
@bwand Yeah, sorry, #14371 has restored the correct code.
Would you like to try the snapshots and confirm it ?

**Comment by sberyozkin** [comment]
@gsmet Guillaume, please backport that fix to 1.11.1.Final :-)

**Comment by bwand** [comment]
> @bwand Yeah, sorry, #14371 has restored the correct code.
> Would you like to try the snapshots and confirm it ?

@sberyozkin yes sure, can you tell me where I can get the snapshots for verification?

**Comment by sberyozkin** [comment]
@bwand please check https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#checking-an-issue-is-fixed-in-master

(thanks to @gsmet for reminding)

**Comment by bwand** [comment]
> @bwand please check https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#checking-an-issue-is-fixed-in-master
> 
> (thanks to @gsmet for reminding)

Ah ok thank you. This is my first bug opened here in quarkus. I will check the snapshots.

**Comment by bwand** [comment]
Hi @sberyozkin I tried with the latest snapshots and works like a charm.

**Comment by sberyozkin** [comment]
@bwand thanks for testing
