### ISSUE TITLE
NPE thrown in X-Forwarded-For header parsing

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#14536]
**Describe the bug**
I got the following error and stack trace reported when a request was sent with the following header `X-Forwarded-For: 10.17.13.17`. I don't know for sure if this is the header which caused the problem, that is just my assumption. I am however quite sure this problem didn't exist before Quarkus 1.11.0.Final.

```
21:05:51.537 ERROR [io.qu.ve.ht.ru.QuarkusErrorHandler] (executor-thread-8) HTTP Request to null failed, error id: 45a1b57a-7a5f-46d2-9dd6-c00d237c5c5a-1: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.ForwardedParser.parseHostAndPort(ForwardedParser.java:199)
	at io.quarkus.vertx.http.runtime.ForwardedParser.setHostAndPort(ForwardedParser.java:181)
	at io.quarkus.vertx.http.runtime.ForwardedParser.calculate(ForwardedParser.java:108)
	at io.quarkus.vertx.http.runtime.ForwardedParser.absoluteURI(ForwardedParser.java:85)
	at io.quarkus.vertx.http.runtime.ForwardedServerRequestWrapper.absoluteURI(ForwardedServerRequestWrapper.java:214)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.absoluteURI(HttpServerRequestWrapper.java:234)
	at io.quarkus.resteasy.runtime.standalone.VertxUtil.extractUriInfo(VertxUtil.java:31)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:120)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Unknown Source)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Expected behavior**
Probably the header should be ignored and a message be logged.

**Actual behavior**
NPE logged and 500 status error result.

**To Reproduce**

**Configuration**
```properties
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.enable-forwarded-host=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: Quarkus 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):

**Comment by geoand** [comment]
Hi,

I could not reproduce this with a simple hello world application and using a cURL request:

`curl -H "X-Forwarded-For: 10.17.13.17" http://localhost:8080/hello`

Is there anything more you can tell us what you are doing?

**Comment by knutwannheden** [comment]
I will take another look. But it looks like an NPE can be provoked somehow. I will try to reproduce and otherwise analyze the code.

**Comment by geoand** [comment]
The only way I saw that would cause a NPE is if the host is somehow null (I don't know how that can happen)

**Comment by knutwannheden** [comment]
When I call an endpoint using `curl` like this I can provoke this NPE: curl http://localhost:8080/foo -H "Host:". I can't really tell you how this happened now, but an NPE seems wrong in any case.

**Comment by geoand** [comment]
That is good enough. I'll provide a fix, because certainly we don't want a NPE.
