### ISSUE TITLE
Quarkus tests only run on maven projects

### ISSUE THREAD

**Issue by RupprechJo** [quarkusio/quarkus#1458]
I use gradle 5.2. I played with the getting-started project. I added a build.gradle to the project:
```
apply plugin: 'java'
apply plugin: 'io.quarkus.gradle.plugin'

buildscript { 
  repositories {
    mavenCentral()
    maven {
      //this is temporary, all dependencies should be in central soon
      url 'http://repository.jboss.org/nexus/content/groups/public'
    }
  }
  dependencies {
    classpath 'io.quarkus:quarkus-gradle-plugin:0.11.0'
  }
}

repositories { 
  mavenCentral()
  maven {
    url 'http://repository.jboss.org/nexus/content/groups/public'
  }
}

dependencies { 
  compileOnly group: 'io.quarkus', name: 'quarkus-resteasy', version:'0.11.0'
  testCompile group: 'io.quarkus', name: 'quarkus-junit5', version:'0.11.0'
  testCompile group: 'io.rest-assured', name: 'rest-assured', version: '3.3.0'
}

test {
  useJUnitPlatform()
}
```

Wenn I start the tests with `gradle test`, the tests fail with that exception
```
java.lang.RuntimeException: The test class class org.acme.quickstart.GreetingResourceTest is not located in the /test-classes directory.
	at io.quarkus.test.common.PathTestHelper.getTestClassesLocation(PathTestHelper.java:40)
	at io.quarkus.test.common.TestResourceManager.indexTestClasses(TestResourceManager.java:104)
	at io.quarkus.test.common.TestResourceManager.getTestResources(TestResourceManager.java:69)
	at io.quarkus.test.common.TestResourceManager.<init>(TestResourceManager.java:44)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:68)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassTestDescriptor.java:358)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllCallbacks(ClassTestDescriptor.java:358)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:74)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:102)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:82)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:78)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)

```
Seems, that quarkus only can use the maven output layout (which is `target/test-classes`). Gradle has a different output layout, e.g. the test classes are found in `build/classes/java/test`

Getting the same excaption, when I import the gradle project into my IDE (I used IntelliJ), and trying to start the `GreetingResourceTest`

**Comment by gsmet** [comment]
We should probably improve `PathTestHelper` to also support this layout.

@RupprechJo interested in giving it a shot?

**Comment by RupprechJo** [comment]
I mean the documentation found here: https://quarkus.io/guides/gradle-tooling.html

**Comment by RupprechJo** [comment]
@gsmet Could you describe what you mean by "giving it a shot"?

**Comment by geoand** [comment]
> @gsmet Could you describe what you mean by "giving it a shot"?

@gsmet means if you would like to attempt to contribute a fix for the issue. How does that sound?

**Comment by stalep** [comment]
With this PR: #1546 Gradle tests are going further, but they do not work yet. 
From the log I notice that the test runner do not have any extensions installed: `INFO: Installed features: []`. - somehow Quarkus do not pick up the extensions.
To replicate, use the `getting-started` project with this build.gradle file:
```java
apply plugin: 'java'
apply plugin: 'io.quarkus.gradle.plugin'

buildscript { 
  repositories {
    mavenCentral()
    mavenLocal()
    maven {
      //this is temporary, all dependencies should be in central soon
      url 'http://repository.jboss.org/nexus/content/groups/public'
    }
  }
  dependencies {
    classpath 'io.quarkus:quarkus-gradle-plugin:999-SNAPSHOT'
  }
}

repositories { 
  mavenCentral()
    mavenLocal()
  maven {
    url 'http://repository.jboss.org/nexus/content/groups/public'
  }
}

dependencies { 
  compileOnly group: 'io.quarkus', name: 'quarkus-resteasy', version:'999-SNAPSHOT'
  testCompile group: 'io.quarkus', name: 'quarkus-junit5', version:'999-SNAPSHOT'
  testCompile group: 'io.rest-assured', name: 'rest-assured', version: '3.3.0'
}

test {
  useJUnitPlatform()
}
```
Use a fresh built of Quarkus (with the PR referenced applied).

**Comment by RupprechJo** [comment]
Had the same idea as stalep. But not only gradle itself is a problem. When importing a gradle project into IntelliJ or Eclipse, the output paths of gradle and the IDE are NOT shared (because gradle wants no shared paths, because that destroys correct up-to-date recognition). So, if you want to start the test from your IDE, it still will not work. Eclipse and IntelliJ, have default output paths, but can be reconfigured to other paths. So I would suggest:

On the one hand the ability to recognize the default IntelliJ (`projectRoot/out/production/classes` and `projectRoot/out/test/classes`) and Eclipse (only one output path `projectRoot/bin`) output paths should be added, and on the other hand some kind of additional output path configuration for non default output paths may be useful

**Comment by stalep** [comment]
With the latest changes in master the next version (scheduled to be released today) I tested running the getting-started tests in Intellij which worked fine.
There are however a lot of hard-coded locations/assumptions inside Quarkus which we'll try to fix/improve in the upcoming versions. I'll close this issue now since the original issue here is resolved.
