### ISSUE TITLE
Quarkus app build fails with Java 16

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#14611]
Building one of my demos failed with Java 16. It's probably not supported at this time, but may be a good idea to look into it early on:

```
java --version

openjdk 16-ea 2021-03-16
OpenJDK Runtime Environment (build 16-ea+32-2190)
OpenJDK 64-Bit Server VM (build 16-ea+32-2190, mixed mode, sharing)
```

```
git clone https://github.com/debezium/debezium-examples.git
cd debezium-examples/saga
mvn clean verify
```

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.11.0.CR1:build (default) on project saga-order-service: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.steps.ClassTransformingBuildStep#handleClassTransformation threw an exception: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "io.quarkus.bootstrap.classloading.ClassPathResource.getData()" because the return value of "io.quarkus.bootstrap.classloading.ClassPathElement.getResource(String)" is null
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:981)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:831)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "io.quarkus.bootstrap.classloading.ClassPathResource.getData()" because the return value of "io.quarkus.bootstrap.classloading.ClassPathElement.getResource(String)" is null
[ERROR] 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[ERROR] 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[ERROR] 	at io.quarkus.deployment.steps.ClassTransformingBuildStep.handleClassTransformation(ClassTransformingBuildStep.java:174)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
[ERROR] 	... 5 more
[ERROR] Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.bootstrap.classloading.ClassPathResource.getData()" because the return value of "io.quarkus.bootstrap.classloading.ClassPathElement.getResource(String)" is null
[ERROR] 	at io.quarkus.deployment.steps.ClassTransformingBuildStep$1.call(ClassTransformingBuildStep.java:121)
[ERROR] 	at io.quarkus.deployment.steps.ClassTransformingBuildStep$1.call(ClassTransformingBuildStep.java:115)
[ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by jaikiran** [comment]
Hello @gunnarmorling,

I haven't been able to reproduce this with Java 16 (latest EA). I followed the steps you mentioned but the build passed fine:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Debezium Saga Demo - Build Aggregator 1.0.0-SNAPSHOT:
[INFO] 
[INFO] Debezium Saga Demo - Build Aggregator .............. SUCCESS [  0.092 s]
[INFO] Debezium Saga Demo - Order Service ................. SUCCESS [  7.585 s]
[INFO] Debezium Saga Demo - Payment Service ............... SUCCESS [  3.987 s]
[INFO] Debezium Saga Demo - Customer Service .............. SUCCESS [  3.615 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

java -version
```
openjdk version "16-ea" 2021-03-16
OpenJDK Runtime Environment (build 16-ea+33-2205)
OpenJDK 64-Bit Server VM (build 16-ea+33-2205, mixed mode, sharing)
```

**Comment by famod** [comment]
Just to throw in another sample: Cannot reproduce it either (with same build 2205 as @jaikiran).

**Comment by geoand** [comment]
I also tried this with the following JDK:

```
openjdk version "16-ea" 2021-03-16
OpenJDK Runtime Environment (build 16-ea+33-2205)
OpenJDK 64-Bit Server VM (build 16-ea+33-2205, mixed mode, sharing)
```

everything worked

**Comment by gunnarmorling** [comment]
Just retried, it even works with ea32 now (i.e. I haven't changed anything, really). A bit concerning, but it's not reproduceable for the time being. Thus going to close it for now. Thanks all for testing!

**Comment by jcjolley** [comment]
This happens for me with remoteDev, but not when building locally

```
accounts_1    | Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.bootstrap.classloading.ClassPathResource.getData()" because the return value of "io.quarkus.bootstrap.classloading.ClassPathElement.getResource(String)" is null
accounts_1    |         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.getResourceAsStream(QuarkusClassLoader.java:359)
accounts_1    |         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.getResourceAsStream(QuarkusClassLoader.java:380)
accounts_1    |         at io.quarkus.arc.processor.BeanArchives.index(BeanArchives.java:268)
accounts_1    |         at io.quarkus.arc.processor.BeanArchives$IndexWrapper.computeAdditional(BeanArchives.java:246)
accounts_1    |         at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
accounts_1    |         at io.quarkus.arc.processor.BeanArchives$IndexWrapper.getClassByName(BeanArchives.java:102)
accounts_1    |         at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:199)
accounts_1    |         at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:166)
accounts_1    |         at io.quarkus.deployment.steps.ReflectiveHierarchyStep.build(ReflectiveHierarchyStep.java:75)
accounts_1    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
accounts_1    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
accounts_1    |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
accounts_1    |         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
accounts_1    |         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
accounts_1    |         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
accounts_1    |         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
accounts_1    |         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
<============-> 98% EXECUTING [5m 29s]
accounts_1    |         at java.base/java.lang.Thread.run(Unknown Source)
accounts_1    |         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
accounts_1    | 
accounts_1    | 2021-10-15 09:47:26,261 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-1) Live reload total time: 0.757s 
```
