### ISSUE TITLE
qute - quarkus error when add dependency to pom

### ISSUE THREAD

**Issue by DavidNoN** [quarkusio/quarkus#14660]
I've been 1 day trying to fix this issue, when I add this to my pom

<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy-qute</artifactId>
</dependency>

suddenly, I got this issue.

PD: I've tried downgrade version, anything, and can't solve it, any help is appreciated.

.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#analyzeTemplates threw an exception: java.lang.IllegalArgumentException: Not a virtual method: ?3M2???1??z uf? (?? (?? (??'F8??1?????E??j?~e??s?EPEPE??? ?i7?z?J Z(?F? (?gU\? ?OJC"?,???=h?Ro?u??W?y: u?2??2??9?JX???)?2??Y[9?
	at io.quarkus.qute.Expressions.parseVirtualMethodParams(Expressions.java:39)
	at io.quarkus.qute.Parser.createPart(Parser.java:718)
	at io.quarkus.qute.Parser.parseExpression(Parser.java:697)
	at io.quarkus.qute.Parser.apply(Parser.java:763)
	at io.quarkus.qute.Parser.flushTag(Parser.java:467)
	at io.quarkus.qute.Parser.tag(Parser.java:263)
	at io.quarkus.qute.Parser.processCharacter(Parser.java:176)
	at io.quarkus.qute.Parser.parse(Parser.java:112)
	at io.quarkus.qute.EngineImpl.load(EngineImpl.java:124)
	at io.quarkus.qute.EngineImpl$$Lambda$363/000000000000000000.apply(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.quarkus.qute.EngineImpl.getTemplate(EngineImpl.java:102)
	at io.quarkus.qute.deployment.QuteProcessor.analyzeTemplates(QuteProcessor.java:375)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at io.quarkus.builder.BuildContext$$Lambda$231/000000000000000000.run(Unknown Source)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:836)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:134)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:54)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:75)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:360)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:52)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:129)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:82)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:144)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)

**Comment by mkouba** [comment]
Hello @DavidNoN, do you have some "non-template" files in `src/main/resources/templates`? It seems that Qute attempts to parse a file which is obviously not a template... In any case, a simple reproducer app would be really helpful.

**Comment by DavidNoN** [comment]
Hi @mkouba, thank you! I had a non-template file there, I had also to delete target folder and everything works now.
