### ISSUE TITLE
Cannot start 1.11 with blaze persistence 1.5.1

### ISSUE THREAD

**Issue by DylanSale** [quarkusio/quarkus#14694]
**Describe the bug**

I am upgrading my application from quarkus 1.10.5 to 1.11.1 which uses blaze persistence jaxrs 1.5.1, and upon starting the dev server (using `./gradlew quarkusDev`) I get an error "failed to start quarkus" (see below for details). The application works fine on quarkus 1.10.5.

**Expected behavior**

The development server should start correctly.

**Actual behavior**

The development server crashes on boot with the following stack trace:

```
Caused by: java.lang.RuntimeException: Failed to start quarkus

	... 15 more
Caused by: java.lang.RuntimeException: RESTEASY003940: Unable to instantiate MessageBodyReader
	at org.jboss.resteasy.core.providerfactory.CommonProviders.processProviderContracts(CommonProviders.java:93)
Caused by: java.lang.RuntimeException: RESTEASY003940: Unable to instantiate MessageBodyReader

	at org.jboss.resteasy.core.providerfactory.ClientHelper.processProviderContracts(ClientHelper.java:104)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.processProviderContracts(ResteasyProviderFactoryImpl.java:840)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerProvider(ResteasyProviderFactoryImpl.java:828)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerProvider(ResteasyProviderFactoryImpl.java:815)
	at io.quarkus.restclient.runtime.RestClientRecorder.registerProviders(RestClientRecorder.java:86)
	at io.quarkus.restclient.runtime.RestClientRecorder.registerProviders(RestClientRecorder.java:78)
	at io.quarkus.restclient.runtime.RestClientRecorder.initializeResteasyProviderFactory(RestClientRecorder.java:63)
	at io.quarkus.deployment.steps.RestClientProcessor$registerProviders350329842.deploy_0(RestClientProcessor$registerProviders350329842.zig:512)
	at io.quarkus.deployment.steps.RestClientProcessor$registerProviders350329842.deploy(RestClientProcessor$registerProviders350329842.zig:40)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:476)
	... 15 more
Caused by: javax.enterprise.inject.CreationException: Synthetic bean instance for com.blazebit.persistence.view.EntityViewManager not initialized yet: com_blazebit_persistence_view_EntityViewManager_3cb728d15a0a04006cc75d03f784feb2bba9a5fb
	- a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
Caused by: javax.enterprise.inject.CreationException: Synthetic bean instance for com.blazebit.persistence.view.EntityViewManager not initialized yet: com_blazebit_persistence_view_EntityViewManager_3cb728d15a0a04006cc75d03f784feb2bba9a5fb
```

**To Reproduce**

1. Have a gradle project with quarkus 1.11.1 and the following dependencies
```
    implementation 'com.blazebit:blaze-persistence-integration-hibernate-5.4'
    implementation 'com.blazebit:blaze-persistence-integration-quarkus'
    implementation "com.blazebit:blaze-persistence-integration-jaxrs:1.5.1"
```
2. start `./gradlew quarkusDev`

**Environment (please complete the following information):**
MacOS Big Sur

 ```
Initialized native services in: ~/.gradle/native

------------------------------------------------------------
Gradle 6.4.1
------------------------------------------------------------

Build time:   2020-05-15 19:43:40 UTC
Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.7 (Amazon.com Inc. 11.0.7+10-LTS)
OS:           Mac OS X 10.16 x86_64
```
```
java --version
openjdk 11.0.7 2020-04-14 LTS
OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)
```

**Additional context**
(Add any other context about the problem here.)

**Comment by famod** [comment]
@beikov @Mobe91 is this a known problem?

**Comment by beikov** [comment]
That's new to me. Are you using the fast-jar packaging? @DylanSale

**Comment by DylanSale** [comment]
Yes it is using fast jar for deployment, but this error is occuring with the dev server.

**Comment by beikov** [comment]
Could you give version 1.6.0-Alpha2 a shot please? We fixed a few things in the Quarkus compatibility area since 1.5.1 but not sure if this is related. If the problem still persists, could you please attach a simple reproducer for this?

**Comment by DylanSale** [comment]
1.6.0-Alpha2 seems to resolve this issue.

The error was being cased by:
```
    implementation "com.blazebit:blaze-persistence-integration-jaxrs:1.5.1"
```

I've attached the repro in any case for 1.5.1, but I guess the answer is to wait until 1.6.0 is out before upgrading Quarkus.

[repro.zip](https://github.com/quarkusio/quarkus/files/6034032/repro.zip)
