### ISSUE TITLE
Intermitent failure (NPE) in metrics endpoint test

### ISSUE THREAD

**Issue by miquelsi** [quarkusio/quarkus#14705]
**Describe the bug**
We are experiencing intermitent failures in a test that checks the metrics endpoint.

**Expected behavior**
The test is successful.

**Actual behavior**
The test fails with the following error:

```
2020-11-18 15:28:03,089 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /metrics failed, error id: d8b6415c-3a39-424b-a974-9667983941d6-1: java.lang.NullPointerException
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.commit(CDIDelegatingTransactionManager.java:93)
	at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:92)
	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
	at org.keycloak.services.filters.AbstractRequestFilter.close(AbstractRequestFilter.java:60)
	at org.keycloak.provider.quarkus.QuarkusRequestFilter.lambda$null$1(QuarkusRequestFilter.java:53)
	at io.vertx.ext.web.impl.RoutingContextImpl.lambda$null$1(RoutingContextImpl.java:489)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.vertx.ext.web.impl.RoutingContextImpl.lambda$getHeadersEndHandlers$2(RoutingContextImpl.java:489)
	at io.vertx.core.http.impl.HttpServerResponseImpl.prepareHeaders(HttpServerResponseImpl.java:661)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:384)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:365)
	at io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsHandler$1.respondWith(SmallRyeMetricsHandler.java:44)
	at io.smallrye.metrics.MetricsRequestHandler.handleRequest(MetricsRequestHandler.java:161)
	at io.smallrye.metrics.MetricsRequestHandler_ClientProxy.handleRequest(MetricsRequestHandler_ClientProxy.zig:259)
	at io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsHandler.handle(SmallRyeMetricsHandler.java:36)
	at io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsHandler.handle(SmallRyeMetricsHandler.java:18)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Here are some GA runs that show the described failure:
https://github.com/keycloak/keycloak/pull/7738/checks?check_run_id=1786843902
https://github.com/keycloak/keycloak/pull/7722/checks?check_run_id=1787827776

The test is this: https://github.com/keycloak/keycloak/blob/c0beca7744a5eea3858ba9881a222fcfd8a64802/quarkus/deployment/src/test/java/test/org/keycloak/quarkus/services/health/KeycloakReadyHealthCheckTest.java#L58

**Comment by jmartisk** [comment]
I don't have much insight into Keycloak, but from the stack trace, it looks like Keycloak is wrapping the call to the `/metrics` endpoint into a transaction, and the failure seems to be related to committing the transaction (or maybe there's a `commit` call when actually no transaction was started, hence the NullPointerException?). 
Is that transaction handling needed? (Obtaining metrics generally doesn't require it).

**Comment by pedroigor** [comment]
@jmartisk Yes, I suspect this is something on our side. Transactions should only be managed within a blocking thread and not in an event loop thread.

I'll check why this is happening.

**Comment by stuartwdouglas** [comment]
I have opened https://github.com/quarkusio/quarkus/pull/15797 to improve the error message, but I think the root cause is something in the Keycloak TX filter.
