### ISSUE TITLE
Generated gradle project with Kogito extension can't be build

### ISSUE THREAD

**Issue by aramashkan** [quarkusio/quarkus#14756]
**Describe the bug**
Simple gradle project with kogito extension generated from code.quarkus.io can't be build

**Expected behavior**
Like maven project it should be buildable

**Actual behavior**
```
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step org.kie.kogito.quarkus.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.IllegalArgumentException: Expected directory or archive, file given: /Users/antram/quarkus-kogito-example/build/classes/java/main/src/main/resources
        at org.kie.kogito.codegen.io.CollectedResource.fromPaths(CollectedResource.java:62)
        at org.kie.kogito.quarkus.deployment.KogitoAssetsProcessor.generateModel(KogitoAssetsProcessor.java:194)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**To Reproduce**

```
git clone https://github.com/aramashkan/quarkus-kogito-example.git
cd quarkus-kogito-example
./gradlew assemble
```
Or just create gradle kotlin project from code.quarkus.io with kogito extension 

**Environment**
```
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
```

**Comment by geoand** [comment]
cc @evacchi

**Comment by gsmet** [comment]
@evacchi any chance you could have a look? The path `build/classes/java/main/src/main/resources` looks very wrong so I wonder if it's not an issue specific to Gradle. /cc @glefloch

**Comment by evacchi** [comment]
I'll try to spare some time; we're in the middle of a big refactoring, so this could be a good time to revisit this /cc @danielezonca

**Comment by vladimirfx** [comment]
Quarkus 2.0.0.Final:

```
quarkus-kogito-gradle ./gradlew assemble
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :quarkusGenerateCode
preparing quarkus application
Loading failed because There already exists an implementation for service org.kie.internal.ruleunit.RuleUnitComponentFactory with same priority 0

> Task :quarkusBuild FAILED
building quarkus jar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.ExceptionInInitializerError
        at org.drools.dynamic.DynamicServiceRegistrySupplier.get(DynamicServiceRegistrySupplier.java:32)
        at org.drools.dynamic.DynamicServiceRegistrySupplier.get(DynamicServiceRegistrySupplier.java:23)
        at org.kie.api.internal.utils.ServiceRegistry$Impl.getServiceRegistry(ServiceRegistry.java:90)
        at org.kie.api.internal.utils.ServiceRegistry$ServiceRegistryHolder.<clinit>(ServiceRegistry.java:49)
        at org.kie.api.internal.utils.ServiceRegistry.getInstance(ServiceRegistry.java:41)
        at org.kie.api.internal.utils.ServiceRegistry.getService(ServiceRegistry.java:37)
        at org.drools.compiler.compiler.DecisionTableFactory.<clinit>(DecisionTableFactory.java:28)
        at org.kie.kogito.codegen.rules.IncrementalRuleCodegen.<init>(IncrementalRuleCodegen.java:131)
        at org.kie.kogito.codegen.rules.IncrementalRuleCodegen.ofResources(IncrementalRuleCodegen.java:113)
        at org.kie.kogito.codegen.rules.IncrementalRuleCodegen.ofCollectedResources(IncrementalRuleCodegen.java:98)
        at org.kie.kogito.codegen.rules.IncrementalRuleCodegenFactory.create(IncrementalRuleCodegenFactory.java:29)
        at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.lambda$loadGenerators$0(ApplicationGeneratorDiscovery.java:60)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.loadGenerators(ApplicationGeneratorDiscovery.java:62)
        at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.discover(ApplicationGeneratorDiscovery.java:48)
        at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateFiles(KogitoAssetsProcessor.java:114)
        at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateModel(KogitoAssetsProcessor.java:85)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.lang.RuntimeException: Unable to build kie service url = jar:file:/Users/vladimirfx/.gradle/caches/modules-2/files-2.1/org.drools/drools-ruleunit/7.55.0.Final/6deabe72d8c663995694627ade411a33fe6b2e0c/drools-ruleunit-7.55.0.Final.jar!/META-INF/kie.conf
        at org.kie.api.internal.utils.ServiceDiscoveryImpl.registerConfs(ServiceDiscoveryImpl.java:105)
        at org.kie.api.internal.utils.ServiceDiscoveryImpl.lambda$getServices$1(ServiceDiscoveryImpl.java:83)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at org.kie.api.internal.utils.ServiceDiscoveryImpl.getServices(ServiceDiscoveryImpl.java:81)
        at org.kie.api.internal.utils.ServiceRegistry$Impl.<init>(ServiceRegistry.java:62)
        at org.drools.dynamic.DynamicServiceRegistrySupplier$LazyHolder.<clinit>(DynamicServiceRegistrySupplier.java:27)
        ... 35 more
  Caused by: java.lang.RuntimeException: There already exists an implementation for service org.kie.internal.ruleunit.RuleUnitComponentFactory with same priority 0
        at org.kie.api.internal.utils.ServiceDiscoveryImpl$PriorityMap.put(ServiceDiscoveryImpl.java:222)
        at org.kie.api.internal.utils.ServiceDiscoveryImpl.processKieService(ServiceDiscoveryImpl.java:124)
        at org.kie.api.internal.utils.ServiceDiscoveryImpl.registerConfs(ServiceDiscoveryImpl.java:101)
        ... 40 more


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 58s
6 actionable tasks: 6 executed
```

**Comment by evacchi** [comment]
I created a KOGITO JIRA since I could not find one https://issues.redhat.com/browse/KOGITO-5456 I'll try to raise the priority for this

**Comment by evacchi** [comment]
I think this should be resolved by now (there are some kinks to iron out, but the bulk of the feature should work)

**Comment by glefloch** [comment]
Nice thanks ! Should we close this ?

**Comment by aramashkan** [comment]
Just test assemble fresh project from code.quarkus.io receive:
```* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.IllegalStateException: src/main/java/org/kie/kogito/app/GlobalObjectMapper.java (24:914) : Only a type can be imported. io.quarkus.jackson.ObjectMapperCustomizer resolves to a package
  src/main/java/org/kie/kogito/app/GlobalObjectMapper.java (27:1012) : ObjectMapperCustomizer cannot be resolved to a type
  src/main/java/org/kie/kogito/app/GlobalObjectMapper.java (24:914) : Only a type can be imported. io.quarkus.jackson.ObjectMapperCustomizer resolves to a packagesrc/main/java/org/kie/kogito/app/GlobalObjectMapper.java (27:1012) : ObjectMapperCustomizer cannot be resolved to a type
        at org.kie.kogito.quarkus.common.deployment.InMemoryCompiler.compile(InMemoryCompiler.java:104)
        at org.kie.kogito.quarkus.common.deployment.KogitoQuarkusResourceUtils.compileGeneratedSources(KogitoQuarkusResourceUtils.java:168)
        at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.compileAndIndexJavaSources(KogitoAssetsProcessor.java:130)
        at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateModel(KogitoAssetsProcessor.java:100)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)```

**Comment by evacchi** [comment]
that is most likely a separate issue. Make sure you include resteasy and resteasy-jackson. Kogito 1.14 will ship with 2.5.1 which should solve that issue

**Comment by JayakrishnaM7** [comment]
how to fix  [error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.NoSuchMethodError ?

any suggesstions.
