### ISSUE TITLE
Issues with modelgen in native image

### ISSUE THREAD

**Issue by thomas-mc-work** [quarkusio/quarkus#14758]
**Describe the bug**

I'm using the `hibernate-modelgen` feature [as described here](https://quarkus.io/guides/hibernate-orm-panache#defining-entities-in-external-projects-or-jars). This works fine as long the project is executed by `mvn quarkus:dev`. When it's compiled into a native runner then I get an exception in the code line containing a reference to the generated model.

**Expected behavior**

I've expected it to be functional in each target.

**Actual behavior**

An Exception is thrown once reaching the affected code line:

    2021-02-01 20:33:37,719 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /users/gerlingen failed, error id: 6319c75d-9f8d-4e0a-b793-04885978121a-1: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Uncompilable source code - Erroneous tree type: <any>
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
    Caused by: java.lang.RuntimeException: Uncompilable source code - Erroneous tree type: <any>
        at org.ecg.asvcq.roundcube.RoundcubeFacade.deleteUser(RoundcubeFacade.java:65)
        at org.ecg.asvcq.roundcube.RoundcubeFacade_ClientProxy.deleteUser(RoundcubeFacade_ClientProxy.zig:225)
        at org.ecg.asvcq.roundcube.RoundcubeService.deleteUser(RoundcubeService.java:24)
        at org.ecg.asvcq.roundcube.RoundcubeService_ClientProxy.deleteUser(RoundcubeService_ClientProxy.zig:197)
        at org.ecg.asvcq.migrate.EmailAccountService.delete(EmailAccountService.java:54)
        at org.ecg.asvcq.migrate.EmailAccountService_ClientProxy.delete(EmailAccountService_ClientProxy.zig:104)
        at org.ecg.asvcq.UsersApi.remove(UsersApi.java:119)
        at org.ecg.asvcq.UsersApi_Subclass.remove$$superaccessor1(UsersApi_Subclass.zig:344)
        at org.ecg.asvcq.UsersApi_Subclass$$function$$1.apply(UsersApi_Subclass$$function$$1.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:127)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at org.ecg.asvcq.UsersApi_Subclass.remove(UsersApi_Subclass.zig:283)
        at org.ecg.asvcq.UsersApi_ClientProxy.remove(UsersApi_ClientProxy.zig:104)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 17 more

**To Reproduce**

1. Create a JPA entity
2. Let `hibernate-modelgen` build the meta model
3. Create a simple lookup based on this meta model:

        public Users getByUsername(final String username) {
            final CriteriaBuilder cb = em.getCriteriaBuilder();
            
            final CriteriaQuery<Users> cq = cb.createQuery(Users.class);
            final Root<Users> ot = cq.from(Users.class);
            
            # This line is corresponding to the this mentioned stack trace line:
            # org.ecg.asvcq.roundcube.RoundcubeFacade.deleteUser(RoundcubeFacade.java:65)
            cq.where(cb.equal(ot.get(Users_.username), username));
            
            final TypedQuery<Users> query = em.createQuery(cq);
            query.setMaxResults(1);
            
            return query.getResultList().iterator().next();
       }

**Configuration**

Nothing related here.

**Environment (please complete the following information):**
 - `uname -a`: `Linux desktop 5.8.0-40-generic #45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - `java -version`: 

        openjdk version "11.0.9.1" 2020-11-04
        OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
        OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
 - GraalVM version (if different from Java): not used
 - Quarkus version or git rev: `1.11.0-FINAL`
 - `mvn --version`:
 
        Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
        Maven home: /home/thomas/.local/opt/apache-maven-3
        Java version: 11.0.9.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
        Default locale: en_US, platform encoding: UTF-8
        OS name: "linux", version: "5.8.0-40-generic", arch: "amd64", family: "unix"
      
**Additional context**

Native image build command:

    mvn package -Pnative -Dquarkus.native.container-runtime=docker -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.3-java11

**Comment by galderz** [comment]
Thx @thomas-mc-work. What's the `org.ecg.asvcq.roundcube.RoundcubeFacade.deleteUser(RoundcubeFacade.java:65)` code doing? Is that your code? I'm not aware of Quarkus having such code. Do you have a reproducer?


@gsmet @Sanne Is there a native test in Quarkus for a similar situation to what @thomas-mc-work is trying to do with `hibernate-modelgen`?

**Comment by galderz** [comment]
Ups, didn't mean to close. Pressed wrong button.

**Comment by thomas-mc-work** [comment]
> What's the org.ecg.asvcq.roundcube.RoundcubeFacade.deleteUser(RoundcubeFacade.java:65) code doing?

That's contained in the snippet of step three in the ticket.

**Comment by gsmet** [comment]
@thomas-mc-work could you create a small reproducer? That would make things a tad easier for us.

**Comment by gsmet** [comment]
Ping @thomas-mc-work for a reproducer. Thanks!

**Comment by thomas-mc-work** [comment]
Yes, sorry, I saw your request. It's not that easy. I'll reopen when I was successful.

**Comment by gsmet** [comment]
Thanks! Let's keep it open for now.

**Comment by geoand** [comment]
Any update on this?

**Comment by geoand** [comment]
Closing as we never got feedback
