### ISSUE TITLE
mvn package run error!!!

### ISSUE THREAD

**Issue by guanchao-yang** [quarkusio/quarkus#1481]
FROM this article but `mvn package`  run error!   https://quarkus.io/guides/getting-started-guide  

```
1) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger
  while locating org.apache.maven.repository.internal.DefaultVersionRangeResolver
  while locating java.lang.Object annotated with *
  at org.eclipse.sisu.wire.LocatorWiring
  while locating org.eclipse.aether.impl.VersionRangeResolver
    for parameter 1 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
  while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
  while locating java.lang.Object annotated with *
  while locating io.quarkus.maven.BuildMojo
Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.eclipse.sisu.bean.BeanPropertyField.set(BeanPropertyField.java:72)
	at org.eclipse.sisu.plexus.ProvidedPropertyBinding.injectProperty(ProvidedPropertyBinding.java:48)
	at org.eclipse.sisu.bean.BeanInjector.injectMembers(BeanInjector.java:52)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:140)
```

**Comment by gsmet** [comment]
@guanchao-yang which version of Maven do you use? We support Maven 3.5.3+.

**Comment by geoand** [comment]
> @guanchao-yang which version of Maven do you use? We support Maven 3.5.3+.

@gsmet Should we configure the enforcer plugin for the generated projects as well?

**Comment by guanchao-yang** [comment]
@gsmet Thank you very much ,I will upgrade maven to  3.5.3+ and try again.

**Comment by guanchao-yang** [comment]
> @gsmet Should we configure the enforcer plugin for the generated projects as well? If you think so, then I will create an issue and file a PR later on tonight

I think this is a good idea, when my environment have problem ,we can use enforcer plugin and give some tips such as  JDK8+ and Maven 3.5.3+

**Comment by gsmet** [comment]
It has already been done in master so it shouldn't be an issue with the next version.

@guanchao-yang Is your issue solved?

**Comment by guanchao-yang** [comment]
@gsmet  Thanks very much  , the problem has been solved.
