### ISSUE TITLE
Scalar.ID.class for graphql is giving an error

### ISSUE THREAD

**Issue by mutasemhidmi** [quarkusio/quarkus#14840]
Caused by: java.lang.NullPointerException: Cannot invoke "io.smallrye.graphql.schema.model.Reference.getType()" because "reference" is null

I'm getting the above error when I add Scalar.id to one of the properties 

public class OrderDTO {

    @ToScalar(Scalar.ID.class)
    private String id;

    @NotEmpty
    @NotBlank
    private String title;

}

**Comment by mutasemhidmi** [comment]
this is the error 

java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:368)
        ... 17 more
Caused by: java.lang.NullPointerException: Cannot invoke "io.smallrye.graphql.schema.model.Reference.getType()" because "reference" is null
        at io.smallrye.graphql.bootstrap.Bootstrap.referenceGraphQLOutputType(Bootstrap.java:544)
        at io.smallrye.graphql.bootstrap.Bootstrap.createGraphQLOutputType(Bootstrap.java:513)
        at io.smallrye.graphql.bootstrap.Bootstrap.createGraphQLFieldDefinitionFromField(Bootstrap.java:447)
        at io.smallrye.graphql.bootstrap.Bootstrap.createGraphQLFieldDefinitionsFromFields(Bootstrap.java:436)
        at io.smallrye.graphql.bootstrap.Bootstrap.createGraphQLObjectType(Bootstrap.java:336)
        at io.smallrye.graphql.bootstrap.Bootstrap.createGraphQLObjectTypes(Bootstrap.java:323)
        at io.smallrye.graphql.bootstrap.Bootstrap.generateGraphQLSchema(Bootstrap.java:118)
        at io.smallrye.graphql.bootstrap.Bootstrap.bootstrap(Bootstrap.java:97)
        at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:44)
        at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:40)
        at io.smallrye.graphql.cdi.producer.GraphQLProducer_ClientProxy.initialize(GraphQLProducer_ClientProxy.zig:160)
        at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLRecorder.createExecutionService(SmallRyeGraphQLRecorder.java:30)
        at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService-167583418.deploy_7(SmallRyeGraphQLProcessor$buildExecutionService-167583418.zig:18090)
        at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService-167583418.deploy(SmallRyeGraphQLProcessor$buildExecutionService-167583418.zig:75)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:337)
        ... 17 more

**Comment by phillip-kruger** [comment]
You can just use the `@Id` annotation. Do remove the `@ToScalar(Scalar.ID.class)` and add the `@Id`.

See https://github.com/eclipse/microprofile-graphql/blob/1.0.x-service/api/src/main/java/org/eclipse/microprofile/graphql/Id.java

**Comment by mutasemhidmi** [comment]
@phillip-kruger thanks appreciated
