### ISSUE TITLE
Native Compilation Fails for 1.11.2.Final at Opentracing/RestEasy

### ISSUE THREAD

**Issue by fxnn** [quarkusio/quarkus#14966]
**Describe the bug**
Since 1.11.2.Final, the native build fails having both OpenTracing and RestEasy extensions active. It worked for 1.11.1.Final.

**Expected behavior**
The build succeeds.

**Actual behavior**
We receive the following output:

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.1.0 (Java Version 11.0.7)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=de -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar reproducer-nativebuild-opentracing-1.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace reproducer-nativebuild-opentracing-1.0-SNAPSHOT-runner
[reproducer-nativebuild-opentracing-1.0-SNAPSHOT-runner:26695]    classlist:   4.486,68 ms,  0,96 GB
[reproducer-nativebuild-opentracing-1.0-SNAPSHOT-runner:26695]        setup:     560,83 ms,  0,94 GB
Error: One of @Delete, @Alias, or @Inject must be used: static final java.lang.String io.quarkus.smallrye.opentracing.runtime.graal.Target_org_jboss_resteasy_microprofile_config_FilterConfigSource.FILTER_CONFIG_SOURCE_NAME
com.oracle.svm.core.util.UserError$UserException: One of @Delete, @Alias, or @Inject must be used: static final java.lang.String io.quarkus.smallrye.opentracing.runtime.graal.Target_org_jboss_resteasy_microprofile_config_FilterConfigSource.FILTER_CONFIG_SOURCE_NAME
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:92)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:360)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:308)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:908)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:838)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:536)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
```

**To Reproduce**

Reproducer: https://github.com/fxnn/reproducer-nativebuild-opentracing

It's nothing more than what code.quarkus.io gives for OpenTracing and RestEasy JAX-RS.

1. Run `mvn verify -Pnative`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin carry.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 
 ```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```
 - GraalVM version (if different from Java): see above
 - Quarkus version or git rev: 1.11.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
 ```
 Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 14.0.1, vendor: N/A, runtime: /usr/local/Cellar/openjdk/14.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
This was fixed by https://github.com/quarkusio/quarkus/pull/14958
