### ISSUE TITLE
Create a FAQ on how to solve issues with native images

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#1497]
We had a few discussions about that lately on Zulip, we need to centralize everything with the solutions.

Not sure using SO for that is a good idea as it would be nice to have all of them centralize on a single page.

@geoand would you be interesting in taking the lead on this? I can point to the Zulip discussions

**Comment by geoand** [comment]
@gsmet certainly. If you point me to an initial list of questions, that would be great :)

**Comment by gsmet** [comment]
* delay class initialization: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/--delay-class-initialization-to-runtime/near/160658801
* some reflection (probably) missing: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/--delay-class-initialization-to-runtime/near/160662948 and https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/yasson.20reflection.20error/near/160726910 (this one has been fixed in master but the generic error message is interesting)
* how to include resources: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/yasson.20reflection.20error/near/160799818

**Comment by geoand** [comment]
Thanks @gsmet. Hopefully I will get to this over the weekend or early next week.

**Comment by gsmet** [comment]
One more interesting one, how to solve:
```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Resource bundle not found yasson-messages. Register the resource bundle using the option -H:IncludeResourceBundles=yasson-messages.
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:109)
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:103)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:64)
```
the Quarkus way.

**Comment by Sanne** [comment]
Would be great to detect messages like "Register the resource bundle using the option -H:IncludeResourceBundles=" and replace the text with "Quarkus way" instructions instead.

AFAIR Stuart already has put in place something which filters the error logs and does some replacing of the wording.

**Comment by gsmet** [comment]
This one also would be nice to consider:
```
2019-03-15 18:25:44,047 ERROR [io.und.request] (XNIO-1 task-1) UT005023: Exception handling request to /binding: org.jboss.resteasy.spi.UnhandledException: javax.json.bind.JsonbException: Can't create instance of a class: class org.acme.jsonb.Person, No default constructor found.
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:103)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:323)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
```

You need to mark the element with `@RegisterForReflection`.

**Comment by geoand** [comment]
Definitely, that seems to be coming up a lot!

**Comment by geoand** [comment]
Are we thinking of having a separate `FAQ` page in docs?

**Comment by gsmet** [comment]
My idea was a general guide on writing native applications. Maybe something like "Tips for writing native applications"?

**Comment by geoand** [comment]
Hm, in that case I'm probably not the most appropriate person to lead such an effort since I don't have much experience in writing such native apps - I only basically know answers to of the FAQ :P

**Comment by gsmet** [comment]
As you wish. For now, I really envisioned it as: issue -> solution. We could add more content later.

**Comment by geoand** [comment]
OK, in that case, I can start writing it :P

**Comment by geoand** [comment]
One thing I am not clear on is, do we intend this guide to be aimed at extension authors, regular application authors or perhaps both?
