### ISSUE TITLE
hibernate-reactive combined with plain jdbc connectionfor quarkus security jdbc

### ISSUE THREAD

**Issue by heyplusyou** [quarkusio/quarkus#14986]
**Describe the bug**
Defining a reactive datasource and a non-reactive jdbc datasource causes issues during startup. This happens if reactive and non-reactive data source share "default" and as well if the datasources are defined separately.

**Expected behavior**
hibernate-reactive orm uses reactive datasource, quarkus-security-jdbc uses non-reactive jdbc datasource

**Actual behavior**
Issues during startup e.g. with desperately defined data sources:
```
Caused by: io.quarkus.runtime.configuration.ConfigurationException: The datasource 'vcereactive' is not configured but the persistence unit 'vcereactive' uses it.
        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.lambda$producePersistenceUnitDescriptorFromConfig$4(HibernateOrmProcessor.java:740)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.producePersistenceUnitDescriptorFromConfig(HibernateOrmProcessor.java:739)
        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.handleHibernateORMWithNoPersistenceXml(HibernateOrmProcessor.java:703)
        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.configurationDescriptorBuilding(HibernateOrmProcessor.java:310)
```

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).
[https://github.com/heyplusyou/code-with-quarkus](https://github.com/heyplusyou/code-with-quarkus)

1. add hibernate-reactive
2. add quarkus-security
3. configure datasources

**Configuration**
```properties
quarkus.datasource.jdbc=true
quarkus.datasource.reactive=false
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_test

quarkus.datasource.vcereactive.jdbc=false
quarkus.datasource.vcereactive.reactive=true
quarkus.datasource.vcereactive.db-kind=postgresql
quarkus.datasource.vcereactive.username=postgres
quarkus.datasource.vcereactive.password=postgres
quarkus.datasource.vcereactive.reactive.url=vertx-reactive:postgresql://localhost/quarkus_test

quarkus.hibernate-orm.vcereactive.datasource=vcereactive
quarkus.hibernate-orm.vcereactive.database.generation=drop-and-create
quarkus.hibernate-orm.vcereactive.packages=org.acme
# quarkus.hibernate-orm.vcereactive.log.sql=true

# AUTHENTIFICATION
quarkus.security.jdbc.enabled=true
quarkus.security.jdbc.principal-query.sql=SELECT u.password FROM person u WHERE u.name=?
quarkus.security.jdbc.principal-query.clear-password-mapper.enabled=true
quarkus.security.jdbc.principal-query.clear-password-mapper.password-index=1
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux pop-os 5.8.0-7642-generic #47~1612288990~20.10~b8113e7-Ubuntu SMP Wed Feb 3 02:27:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.5.1

**Comment by sberyozkin** [comment]
CC @stuartwdouglas @FroMage

**Comment by gsmet** [comment]
Hibernate Reactive does not support named datasources at the moment.

Unfortunately, I don't think you can make your setup work at the moment.

That being said, if you're using JDBC and thus a blocking implementation for security, I really don't see the point in trying Hibernate Reactive. I would stay on plain Hibernate ORM.

**Comment by LoweloDev** [comment]
> Hibernate Reactive does not support named datasources at the moment.
> 
> Unfortunately, I don't think you can make your setup work at the moment.
> 
> That being said, if you're using JDBC and thus a blocking implementation for security, I really don't see the point in trying Hibernate Reactive. I would stay on plain Hibernate ORM.

I came here because I had the same issue but now have a little off-topic design question as a student:
Would you generally suggest to rather use a seperate database and small application for security stuff (seperate from reactive stuff)? Cause It would make sense to me. You don't really need reactive behaviour in terms of user management I think. Also I could just fetch necessary account information to my reactive part of the backend and put it into another table there. And I could make sure with another authentication layer that only my app connects to that security app and nobody else.
