### ISSUE TITLE
SRCFG00013: No Converter registered for class java.time.Period

### ISSUE THREAD

**Issue by jmdsc** [quarkusio/quarkus#15033]
**Describe the bug**
With the upgrade from 1.11.0.Final to 1.11.1.Final or 1.11.2.Final or 1.11.3.Final, native images no longer run when a configuration property of type **java.time.Period** is defined.

**Expected behavior**
Expected native image to startup.

**Actual behavior**
Native image does not start, reporting the following exception:
```
ERROR [io.qu.ru.Application] (main) Failed to start application (with profile prod): java.lang.IllegalArgumentException: SRCFG00013: No Converter registered for class java.time.Period
        at io.smallrye.config.SmallRyeConfig.lambda$getConverter$2(SmallRyeConfig.java:292)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
        at io.smallrye.config.SmallRyeConfig.getConverter(SmallRyeConfig.java:289)
        at io.smallrye.config.SmallRyeConfig.lambda$getOptionalConverter$1(SmallRyeConfig.java:274)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at io.smallrye.config.SmallRyeConfig.getOptionalConverter(SmallRyeConfig.java:273)
        at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:209)
        at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:37)
        at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties1249763973.deploy_0(ConfigBuildStep$validateConfigProperties1249763973.zig:396)
        at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties1249763973.deploy(ConfigBuildStep$validateConfigProperties1249763973.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:653)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

**Configuration**
```properties
prefix.some.period=P1D
```
```java
@ConfigProperties(prefix = "prefix.some")
public interface Configuration {
    java.time.Period period();
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/554622/107763802-12b5f980-6d27-11eb-96e1-5f46c5e53434.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
     openjdk version "11.0.10" 2021-01-19 LTS
     OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
     OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)
 - Quarkus version or git rev: 1.11.1.Final, 1.11.2.Final, 1.11.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
     Apache Maven 3.6.3
    Java version: 11.0.10, vendor: Azul Systems, Inc.
    Default locale: en_US, platform encoding: UTF-8
    OS name: "linux", version: "5.8.0-43-generic", arch: "amd64", family: "unix"

**Comment by radcortez** [comment]
@jmdsc Did this work in 1.11.0 or before?

**Comment by jmdsc** [comment]
@radcortez 
I could swear it worked on 1.10.5 and 1.11.0
Now I can't even get it to work on 1.10.5 with our current dependencies. The only other difference I can see is that we swapped out `quarkus-resteasy-jackson` for `quarkus-resteasy-jsonb` as well when upgrading to 1.11.1

**Comment by jmdsc** [comment]
@radcortez
A small note if helpful... we also have properties of type `java.time.Duration` defined and that works fine.

**Comment by radcortez** [comment]
Thanks for the feedback. It is indeed weird if it seems to work before and not working now. I don't remember any change that may have affected that. I'll have a look.

**Comment by radcortez** [comment]
@jmdsc where you using direct injection of the property with `@ConfigProperty` instead of `@ConfigProperties`?

It seems that we are failing to register `Period` for reflection when it is used in a `@ConfigProperties`.  For `Period` and other time types, an implicit Converter is used that fallbacks to the `parse`,`of`, etc.

For now, you can register it manually in `src/main/resources/reflection-config.json`:

```json
[
  {
    "name" : "java.time.Period",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  }
]
```

And the following property in the Maven build:

`<quarkus.native.additional-build-args>-H:ReflectionConfigurationFiles=reflection-config.json</quarkus.native.additional-build-args>`

Or just add a dummy injection point for the `Period` configuration to force the registration. In the meanwhile, I'll check what is missing.

**Comment by jmdsc** [comment]
@radcortez 
You're spot on, the `@ConfigProperty` was being used at one stage to inject a single property of type `java.time.Period
` in the constructor. When the target class grew in required properties, these were moved to an interface using `@ConfigProperties`.

Will properties defined using the `@ConfigProperties`  strategy also be automatically picked-up/registered in a future release?

Thanks!
