### ISSUE TITLE
Emitter fails with quarkus 1.11.x

### ISSUE THREAD

**Issue by geniusit** [quarkusio/quarkus#15058]
**Describe the bug**
Since I ve upgraded my microservices to quarkus 1.11 I notice that I can't use the `org.eclipse.microprofile.reactive.messaging.Emitter` anymore
The application fails on startup

**Expected behavior**
No stack and success startup. Like with Quarkus 1.10.x. I have 100 % startup success

**Actual behavior**
When I run the `java -jar` or `mvn compile quarkus:dev` command the application _randomly_ fails.

Here is the stacktrace
```java
2021-02-13 15:37:38,425 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalStateException: SRMSG00019: Unable to find a emitter with the name signalements-ws, available emitters are: []
        at io.smallrye.reactive.messaging.extension.ChannelProducer.getEmitter(ChannelProducer.java:192)
        at io.smallrye.reactive.messaging.extension.ChannelProducer.produceEmitter(ChannelProducer.java:141)
        at io.smallrye.reactive.messaging.extension.ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.create(ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.zig:247)
        at io.smallrye.reactive.messaging.extension.ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.get(ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.zig:277)
        at io.smallrye.reactive.messaging.extension.ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.get(ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.zig:312)
        at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
        at org.acme.getting.started.IssueService_Bean.create(IssueService_Bean.zig:300)
        at org.acme.getting.started.IssueService_Bean.create(IssueService_Bean.zig:340)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
        at org.acme.getting.started.IssueService_ClientProxy.arc$delegate(IssueService_ClientProxy.zig:67)
        at org.acme.getting.started.IssueService_ClientProxy.getAGCSignalements(IssueService_ClientProxy.zig:155)
        at org.acme.getting.started.IssueService_SmallRyeMessagingInvoker_getAGCSignalements_9dc35bb0db20f1a777038430b680cc8a806fb550.invoke(IssueService_SmallRyeMessagingInvoker_getAGCSignalements_9dc35bb0db20f1a777038430b680cc8a806fb550.zig:42)
        at io.smallrye.reactive.messaging.AbstractMediator.invoke(AbstractMediator.java:94)
        at io.smallrye.reactive.messaging.PublisherMediator.produceAPublisherOfPayloads(PublisherMediator.java:123)
        at io.smallrye.reactive.messaging.PublisherMediator.initialize(PublisherMediator.java:75)
        at io.smallrye.reactive.messaging.extension.MediatorManager.createMediator(MediatorManager.java:152)
        at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.createMediator(MediatorManager_ClientProxy.zig:188)
        at io.smallrye.reactive.messaging.wiring.Wiring$PublisherMediatorComponent.materialize(Wiring.java:512)
        at io.smallrye.reactive.messaging.wiring.Graph.materialize(Graph.java:89)
        at io.smallrye.reactive.messaging.extension.MediatorManager.start(MediatorManager.java:175)
        at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.start(MediatorManager_ClientProxy.zig:282)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:111)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:60)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:81)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:686)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**

[getting-startedissue.zip](https://github.com/quarkusio/quarkus/files/5975856/getting-startedissue.zip)

Unzip the archive
mvn compile quarkus:dev

The application fails +/- 1 time by five. Why ?

**Configuration**
```properties
# Add your application.properties here, if applicable.
mp.messaging.outgoing.signalements.connector=smallrye-kafka
mp.messaging.outgoing.signalements.bootstrap.servers=localhost:9092
mp.messaging.outgoing.signalements.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.signalements-ws.connector=smallrye-kafka
mp.messaging.outgoing.signalements-ws.topic=signalements
mp.messaging.outgoing.signalements-ws.bootstrap.servers=localhost:9092
mp.messaging.outgoing.signalements-ws.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
        
quarkus.package.type=uber-jar
```

Here is the service : 
```java
@Inject
    @Channel("signalements-ws")
    Emitter<Record<String, AlertEntity>> signalementsEmitter;

    public void test(AlertEntity alertEntity){

        signalementsEmitter
                .send(
                        Record.of(
                                "test",
                                alertEntity)
                )
        ;
    }

    @Outgoing("signalements-out")
    @OnOverflow(value = OnOverflow.Strategy.DROP)
    @Broadcast
    public Multi<AlertEntity> getAGCSignalements() {
        return Multi.createFrom().empty();
    }

    @Incoming("signalements-out")
    @Merge
    @Outgoing("signalements")
    public Message<AlertEntity> sendKafka(final Message<AlertEntity> alertEntityMessage) {

        return Message
                .of(
                        AlertEntity.builder().build()
                )
                .addMetadata(
                        null
                );
    }
```

And 
```java
@Path("/hello")
@Slf4j
public class GreetingResource {

    @Inject
    IssueService issueService;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {

        issueService.test(AlertEntity.builder().stf("test").build());
        return "Hello RESTEasy";
    }
}
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: both 8 and 11
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: success with 1.10.x - fails with 1.11.x
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvn 3.6.3

**Additional context**
(Add any other context about the problem here.)

**Comment by cescoffier** [comment]
Thanks for the reproducer.
The bean is created too early, as the graph is unable to detect the relation between the emitter and the methods (as there is none). So, it materializes the `@Outgoing` (and so create the instance of the bean) before materializing the emitter, leading to the issue.

The workaround for now is to move the emitter outside of this class.

**Comment by cescoffier** [comment]
Fixed by https://github.com/smallrye/smallrye-reactive-messaging/pull/1001.

**Comment by gsmet** [comment]
Let's close it when we upgrade SmallRye Reactive Messaging in Quarkus!

**Comment by cescoffier** [comment]
@gsmet Damned, we will need to be very careful, as it's got closed automatically.

**Comment by jendib** [comment]
I'm getting the same issue with Quarkus 1.13.3. I cannot find if it's supposed to be merged in this version. Can someone confirm this? Thanks.

**Comment by kenfinnigan** [comment]
It should be as 2.9.0 of SmallRye Reactive Messaging is present in 1.13.3
