### ISSUE TITLE
Option --trace-class-initialization is broken and has no effect

### ISSUE THREAD

**Issue by StefanOltmann** [quarkusio/quarkus#15061]
**Describe the bug**

My native build fails because of the Inet4Address problem described in https://github.com/quarkusio/quarkus/issues/11923.

Is states `Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.` and I try to resolve the problem by using the suggested `--trace-object-instantiation` option to trace where this happens so I can include it with `--initialize-at-run-time`.

**Expected behavior**

This option should show me an output like this:
```
Trace: Object was reached by 
	reading field li.pitschmann.knx.core.net.HPAI.address of
		constant li.pitschmann.knx.core.net.HPAI@1b106bcc reached by 
	scanning method li.pitschmann.knx.core.net.HPAI.useDefault(HPAI.java:105)
```

This however is only displayed if I don't have this option.

**Actual behavior**

It does not give me the traces I need to resolve the problem, but suggests to use `--trace-class-initialization` despite the fact that it's already provided.

```
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 java.net.Inet4Address the class was requested to be initialized at run time (from the command line). To see why java.net.Inet4Address got initialized use --trace-class-initialization=java.net.Inet4Address
li.pitschmann.knx.core.utils.Networker the class was requested to be initialized at run time (from the command line). To see why li.pitschmann.knx.core.utils.Networker got initialized use --trace-class-initialization=li.pitschmann.knx.core.utils.Networker
li.pitschmann.knx.core.net.HPAI the class was requested to be initialized at run time (from the command line). To see why li.pitschmann.knx.core.net.HPAI got initialized use --trace-class-initialization=li.pitschmann.knx.core.net.HPAI
```

**To Reproduce**

Try to build https://github.com/StefanOltmann/smart-home-server with `./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true`

Alternative you can include the library https://github.com/pitschr/knx-link to your project. This is the one that uses the problematic `Inet4Address`.

**Configuration**
```
quarkus.native.enable-jni=true 
quarkus.ssl.native=true
quarkus.native.enable-http-url-handler=true
quarkus.native.enable-https-url-handler=true
#quarkus.native.additional-build-args=--initialize-at-run-time=li.pitschmann.knx.core.utils.Networker\\,li.pitschmann.knx.core.net.HPAI\\,li.pitschmann.knx.core.config.CoreConfigs --trace-class-initialization=li.pitschmann.knx.core.utils.Networker\\,li.pitschmann.knx.core.net.HPAI
quarkus.native.additional-build-args=--initialize-at-run-time=java.net.Inet4Address\\,li.pitschmann.knx.core.utils.Networker\\,li.pitschmann.knx.core.net.HPAI\\,li.pitschmann.knx.core.config.CoreConfigs --trace-class-initialization=java.net.Inet4Address\\,li.pitschmann.knx.core.utils.Networker\\,li.pitschmann.knx.core.net.HPAI\\,li.pitschmann.knx.core.config.CoreConfigs
```

**Environment (please complete the following information):**

I build using a GitHub Action.

Here is the full log of a failed run: https://github.com/StefanOltmann/smart-home-server/runs/1897708770?check_suite_focus=true

 - Output of `uname -a` or `ver`: ( I build with the GitHub Action )
 - Output of `java -version`: GraalVM Version 20.3.1 (Java Version 11.0.10+8-jvmci-20.3-b09)
 - GraalVM version (if different from Java): 20.3.1
 - Quarkus version or git rev: 1.11.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.8.2

**Additional context**

Stack trace with option provided:
```
Running Quarkus native-image plugin on GraalVM Version 20.3.1 (Java Version 11.0.10+8-jvmci-20.3-b09)
docker run -v /home/runner/work/smart-home-server/smart-home-server/build/smart-home-server-0.1-native-image-source-jar:/project:z --env LANG=C --user 1001:116 --rm quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-run-time=java.net.Inet4Address,li.pitschmann.knx.core.utils.Networker,li.pitschmann.knx.core.net.HPAI,li.pitschmann.knx.core.config.CoreConfigs --trace-class-initialization=java.net.Inet4Address,li.pitschmann.knx.core.utils.Networker,li.pitschmann.knx.core.net.HPAI,li.pitschmann.knx.core.config.CoreConfigs --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar smart-home-server-0.1-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace smart-home-server-0.1-runner
[smart-home-server-0.1-runner:26]    classlist:   6,004.84 ms,  0.96 GB
[smart-home-server-0.1-runner:26]        (cap):     661.23 ms,  0.96 GB
[smart-home-server-0.1-runner:26]        setup:   2,473.73 ms,  1.18 GB
Error: Classes that should be initialized at run time got initialized during image building:
To see how the classes got initialized, use --trace-class-initialization=java.net.Inet4Address,li.pitschmann.knx.core.utils.Networker,li.pitschmann.knx.core.net.HPAI
 java.net.Inet4Address the class was requested to be initialized at run time (from the command line). To see why java.net.Inet4Address got initialized use --trace-class-initialization=java.net.Inet4Address
[smart-home-server-0.1-runner:26]     analysis:  20,717.02 ms,  1.70 GB
li.pitschmann.knx.core.utils.Networker the class was requested to be initialized at run time (from the command line). To see why li.pitschmann.knx.core.utils.Networker got initialized use --trace-class-initialization=li.pitschmann.knx.core.utils.Networker
li.pitschmann.knx.core.net.HPAI the class was requested to be initialized at run time (from the command line). To see why li.pitschmann.knx.core.net.HPAI got initialized use --trace-class-initialization=li.pitschmann.knx.core.net.HPAI

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 java.net.Inet4Address the class was requested to be initialized at run time (from the command line). To see why java.net.Inet4Address got initialized use --trace-class-initialization=java.net.Inet4Address
li.pitschmann.knx.core.utils.Networker the class was requested to be initialized at run time (from the command line). To see why li.pitschmann.knx.core.utils.Networker got initialized use --trace-class-initialization=li.pitschmann.knx.core.utils.Networker
li.pitschmann.knx.core.net.HPAI the class was requested to be initialized at run time (from the command line). To see why li.pitschmann.knx.core.net.HPAI got initialized use --trace-class-initialization=li.pitschmann.knx.core.net.HPAI

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:539)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:226)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:733)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:733)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:556)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:469)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

Original stack trace:

```
Running Quarkus native-image plugin on GraalVM Version 20.3.1 (Java Version 11.0.10+8-jvmci-20.3-b09)
docker run -v /home/runner/work/smart-home-server/smart-home-server/build/smart-home-server-0.1-native-image-source-jar:/project:z --env LANG=C --user 1001:116 --rm quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar smart-home-server-0.1-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace smart-home-server-0.1-runner
[smart-home-server-0.1-runner:25]    classlist:   7,321.59 ms,  1.19 GB
[smart-home-server-0.1-runner:25]        (cap):     846.80 ms,  1.19 GB
[smart-home-server-0.1-runner:25]        setup:   2,984.54 ms,  1.19 GB
13:02:00,455 INFO  [org.jbo.threads] JBoss Threads version 3.2.0.Final
[smart-home-server-0.1-runner:25]     (clinit):     952.42 ms,  2.86 GB
[smart-home-server-0.1-runner:25]   (typeflow):  42,149.64 ms,  2.86 GB
[smart-home-server-0.1-runner:25]    (objects):  39,273.17 ms,  2.86 GB
[smart-home-server-0.1-runner:25]   (features):   1,049.91 ms,  2.86 GB
Error: Unsupported features in 3 methods
[smart-home-server-0.1-runner:25]     analysis:  85,193.28 ms,  2.86 GB
Detailed message:
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
Trace: Object was reached by 
	reading field li.pitschmann.knx.core.net.HPAI.address of
		constant li.pitschmann.knx.core.net.HPAI@1b106bcc reached by 
	scanning method li.pitschmann.knx.core.net.HPAI.useDefault(HPAI.java:105)
Call path from entry point to li.pitschmann.knx.core.net.HPAI.useDefault(): 
	at li.pitschmann.knx.core.net.HPAI.useDefault(HPAI.java:105)
	at li.pitschmann.knx.core.communication.InternalKnxClient.getControlHPAI(InternalKnxClient.java:375)
	at li.pitschmann.knx.core.communication.communicator.ConnectionStateCommunicator.sendConnectionStateRequest(ConnectionStateCommunicator.java:149)
	at li.pitschmann.knx.core.communication.communicator.ConnectionStateCommunicator.run(ConnectionStateCommunicator.java:69)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
Trace: 
	at parsing li.pitschmann.knx.core.config.CoreConfigs$Multicast.lambda$static$0(CoreConfigs.java:361)
Call path from entry point to li.pitschmann.knx.core.config.CoreConfigs$Multicast.lambda$static$0(): 
	at li.pitschmann.knx.core.config.CoreConfigs$Multicast.lambda$static$0(CoreConfigs.java:361)
	at li.pitschmann.knx.core.config.CoreConfigs$Multicast$$Lambda$740/0x00000007c15f6040.get(Unknown Source)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:338)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
Trace: 
	at parsing li.pitschmann.knx.core.utils.Networker.getLocalHost(Networker.java:72)
Call path from entry point to li.pitschmann.knx.core.utils.Networker.getLocalHost(): 
	at li.pitschmann.knx.core.utils.Networker.getLocalHost(Networker.java:72)
	at li.pitschmann.knx.core.utils.Networker.getByAddress(Networker.java:95)
	at li.pitschmann.knx.core.config.CoreConfigs$Multicast$$Lambda$739/0x00000007c15f5c40.apply(Unknown Source)
	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:338)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 3 methods
Detailed message:
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
Trace: Object was reached by 
	reading field li.pitschmann.knx.core.net.HPAI.address of
		constant li.pitschmann.knx.core.net.HPAI@1b106bcc reached by 
	scanning method li.pitschmann.knx.core.net.HPAI.useDefault(HPAI.java:105)
Call path from entry point to li.pitschmann.knx.core.net.HPAI.useDefault(): 
	at li.pitschmann.knx.core.net.HPAI.useDefault(HPAI.java:105)
	at li.pitschmann.knx.core.communication.InternalKnxClient.getControlHPAI(InternalKnxClient.java:375)
	at li.pitschmann.knx.core.communication.communicator.ConnectionStateCommunicator.sendConnectionStateRequest(ConnectionStateCommunicator.java:149)
	at li.pitschmann.knx.core.communication.communicator.ConnectionStateCommunicator.run(ConnectionStateCommunicator.java:69)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
Trace: 
	at parsing li.pitschmann.knx.core.config.CoreConfigs$Multicast.lambda$static$0(CoreConfigs.java:361)
Call path from entry point to li.pitschmann.knx.core.config.CoreConfigs$Multicast.lambda$static$0(): 
	at li.pitschmann.knx.core.config.CoreConfigs$Multicast.lambda$static$0(CoreConfigs.java:361)
	at li.pitschmann.knx.core.config.CoreConfigs$Multicast$$Lambda$740/0x00000007c15f6040.get(Unknown Source)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:338)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
Trace: 
	at parsing li.pitschmann.knx.core.utils.Networker.getLocalHost(Networker.java:72)
Call path from entry point to li.pitschmann.knx.core.utils.Networker.getLocalHost(): 
	at li.pitschmann.knx.core.utils.Networker.getLocalHost(Networker.java:72)
	at li.pitschmann.knx.core.utils.Networker.getByAddress(Networker.java:95)
	at li.pitschmann.knx.core.config.CoreConfigs$Multicast$$Lambda$739/0x00000007c15f5c40.apply(Unknown Source)
	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:338)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:766)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:556)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:469)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 3 methods
Detailed message:
Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
Trace: Object was reached by 
	reading field li.pitschmann.knx.core.net.HPAI.address of
		constant li.pitschmann.knx.core.net.HPAI@1b106bcc reached by 
	scanning method li.pitschmann.knx.core.net.HPAI.useDefault(HPAI.java:105)
Call path from entry point to li.pitschmann.knx.core.net.HPAI.useDefault(): 
	at li.pitschmann.knx.core.net.HPAI.useDefault(HPAI.java:105)
	at li.pitschmann.knx.core.communication.InternalKnxClient.getControlHPAI(InternalKnxClient.java:375)
	at li.pitschmann.knx.core.communication.communicator.ConnectionStateCommunicator.sendConnectionStateRequest(ConnectionStateCommunicator.java:149)
	at li.pitschmann.knx.core.communication.communicator.ConnectionStateCommunicator.run(ConnectionStateCommunicator.java:69)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
Trace: 
	at parsing li.pitschmann.knx.core.config.CoreConfigs$Multicast.lambda$static$0(CoreConfigs.java:361)
Call path from entry point to li.pitschmann.knx.core.config.CoreConfigs$Multicast.lambda$static$0(): 
	at li.pitschmann.knx.core.config.CoreConfigs$Multicast.lambda$static$0(CoreConfigs.java:361)
	at li.pitschmann.knx.core.config.CoreConfigs$Multicast$$Lambda$740/0x00000007c15f6040.get(Unknown Source)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:338)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
Trace: 
	at parsing li.pitschmann.knx.core.utils.Networker.getLocalHost(Networker.java:72)
Call path from entry point to li.pitschmann.knx.core.utils.Networker.getLocalHost(): 
	at li.pitschmann.knx.core.utils.Networker.getLocalHost(Networker.java:72)
	at li.pitschmann.knx.core.utils.Networker.getByAddress(Networker.java:95)
	at li.pitschmann.knx.core.config.CoreConfigs$Multicast$$Lambda$739/0x00000007c15f5c40.apply(Unknown Source)
	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:338)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:763)
	... 8 more
Error: Image build request failed with exit status 1
```

**Comment by geoand** [comment]
Looking at the code you linked,

```
quarkus.native.additional-build-args=--initialize-at-run-time=java.net.Inet4Address\\,li.pitschmann.knx.core.utils.Networker\\,li.pitschmann.knx.core.net.HPAI\\,li.pitschmann.knx.core.config.CoreConfigs --trace-class-initialization=java.net.Inet4Address\\,li.pitschmann.knx.core.utils.Networker\\,li.pitschmann.knx.core.net.HPAI\\,li.pitschmann.knx.core.config.CoreConfigs
```

is not correct. You should use `,` as the delimiter for the various `native-image` configuration settings instead of a whitespace (` ` in this case)

**Comment by StefanOltmann** [comment]
@geoand Thank you. The option works, no bug.

**Comment by geoand** [comment]
Great 👌
