### ISSUE TITLE
Updating class when no bytecode transformation whatsoever takes place results in NPE in the logs

### ISSUE THREAD

**Issue by SaumyaSingh1** [quarkusio/quarkus#15105]
While running the quarkus app in dev mode, I got this  :

![image](https://user-images.githubusercontent.com/46818757/108050788-17a0e300-7070-11eb-9d16-99736bc5939b.png)

```
2021-02-16 14:43:45,387 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-2) Hot replace total time: 0.529s
2021-02-16 14:45:29,008 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-5) Changed source files detected, recompiling [/home/sausingh/Desktop/demoapp/src/main/java/org/acme/Welcome.java]
2021-02-16 14:45:29,070 ERROR [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-5) Failed to replace classes via instrumentation: java.lang.NullPointerException
    at java.instrument/java.lang.instrument.ClassDefinition.<init>(ClassDefinition.java:63)
    at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:220)
    at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:62)
    at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:52)
```

**Comment by SaumyaSingh1** [comment]
CC @stuartwdouglas @FroMage

**Comment by SaumyaSingh1** [comment]
Let me know if I need to put in some extra information as well :)

**Comment by geoand** [comment]
I can reproduce this consistently
