### ISSUE TITLE
Health checks fails due to NPE in quarkus-smallrye-health

### ISSUE THREAD

**Issue by sommermi** [quarkusio/quarkus#15149]
**Describe the bug**

I'm currently migrating a microservice from thorntail to quarkus. In thorntail the dependency 
```
<dependency>
            <groupId>io.thorntail</groupId>
            <artifactId>microprofile-health</artifactId>
</dependency>
```

This was migrated to

```
<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
      <version>1.10.5.Final</version>
</dependency>
```
After the migration a call to `/health` caused the exception:

```
java.lang.NullPointerException
	at io.smallrye.health.AsyncHealthCheckFactory.callSync(AsyncHealthCheckFactory.java:32)
	at io.smallrye.health.AsyncHealthCheckFactory_ClientProxy.callSync(AsyncHealthCheckFactory_ClientProxy.zig:188)
	at io.smallrye.health.SmallRyeHealthReporter.initUnis(SmallRyeHealthReporter.java:151)
	at io.smallrye.health.SmallRyeHealthReporter.initChecks(SmallRyeHealthReporter.java:138)
	at io.smallrye.health.SmallRyeHealthReporter_Bean.create(SmallRyeHealthReporter_Bean.zig:2185)
	at io.smallrye.health.SmallRyeHealthReporter_Bean.create(SmallRyeHealthReporter_Bean.zig:2201)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
	at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.arc$delegate(SmallRyeHealthReporter_ClientProxy.zig:67)
	at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getHealth(SmallRyeHealthReporter_ClientProxy.zig:276)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.getHealth(SmallRyeHealthHandler.java:11)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.doHandle(SmallRyeHealthHandlerBase.java:38)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:29)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.handle(SmallRyeHealthHandler.java:7)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:17)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
The beans that are implementing the health checks are from a company internal source. Therefore i cannot post the original source code.

I investigated what could cause the problem. In my opinion the problem is caused because the health checks are optional. The can be activated and deactivated via a config property. And as soon as the health check is deactivated the NPE occurs.

The implentation of this toggleable health check looks the following:
```
@Produces
@Liveness
    CustomHealthCheck getHealthCheck() {
        return enabled ? retrieveHealthCheck() : null;
    }

```
So as soon as the check is disabled null is returned. And it seems like the health check gets cosumed and although it is null it is tried to be called => NPE.

We need these toggleable health check in our project. So is the current behavior a bug or is there another way to achive this.

I have created a small sample project for you to be able to recreate the problem (just a quarkus get started project with a health check that is similar to the ones that are provided by us via external dependency). The project can be found here https://github.com/sommermi/getting-started

Just toggle the 

`health.enabled`

inside application.properties and visit http://localhost:8080/health. If health.enabled is true, everything works, but as soon as you change it to false the described exception occurs.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux N337 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: OpenJDK Runtime Environment Corretto-8.265.01.1 (build 1.8.0_265-b01)
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

Best regards and thank you for your great work

**Comment by Ladicek** [comment]
What scope is your "optional" health check? I think producer methods are only allowed to return `null` if the bean scope is `@Dependent`, but I'm no expert, so please don't take my word for it :-)

**Comment by sommermi** [comment]
The "optional" health check has ApplicationScope. Unfortunatley the actual code that implements this health check is a external dependency that i cannot publish. But i have recreated the exact same setup in my linked test project.

**Comment by Ladicek** [comment]
Quoting the `@Produces` javadoc:

```
If a producer method sometimes returns a null value, or if a producer field sometimes contains a null value when accessed,
then the producer method or field must have scope @Dependent.
```

I'm not exactly sure how that works, if you should add `@Dependent` on the producer method or something like that, but I'm pretty sure this is what causes the issue.

**Comment by Ladicek** [comment]
I'm looking more into it and found that I was sorely mistaken. Your producer method, by not declaring any scope (or stereotype) annotation, is already `@Dependent`. So that's not where the problem comes from. Please ignore all my comments above :-)

Indeed SmallRye Health doesn't expect `null` health checks. Whether that's a bug, I'm not sure. CC @xstefank.

In the meantime, you can workaround this limitation relatively easily: in case your health check is "disabled", you can just return an "always up" health check, like this:

```java
    @Produces
    @Liveness
    HealthCheck getHealthCheck() { // note the changed the return type
        LOG.info("producer");
        return enabled ? retrieveHealthCheck() : HealthStatus.up("my-name");
    }
```

**Comment by xstefank** [comment]
The spec doesn't specify what happens if the health check producer returns null so we defaulted to NPE. If you think that this is a useful use case can you open an issue in the specification repo - https://github.com/eclipse/microprofile-health? In every case, if it worked in Thorntail, I will fix this now in SR so we ignore the `null` HealthChecks - https://github.com/smallrye/smallrye-health/issues/239.

**Comment by sommermi** [comment]
Thanks for your fast help and the fix of the problem. I will open an issue in  https://github.com/eclipse/microprofile-health. I will close this issue here at this point.
