### ISSUE TITLE
OpenCV does not work in native mode (UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by ntrp** [quarkusio/quarkus#15147]
**Describe the bug**
OpenCV does not work when the application is compiled to native.

**Expected behavior**
The call completes correctly

**Actual behavior**
While using OpenCV classes in native mode the application crashes with:
```
2021-02-17 14:33:29,348 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: 39d6a967-b519-443a-80ce-1f7550c9ca52-1: org.jboss.resteasy.spi.UnhandledException
: java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_zeros(III)J [symbol: Java_org_opencv_core_Mat_n_1zeros or Java_org_opencv_core_Mat_n_1zeros__III]
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_zeros(III)J [symbol: Java_org_opencv_core_Mat_n_1zeros or Java_org_opencv_core_Mat_n_1zeros__III]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
```

**To Reproduce**

https://github.com/ntrp/quarkus-jni-opencv-issue

1. compile to native with `mvn package -Pnative -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:21.0-java11` (tried also with standard 20.3)
2. run application
3. call `curl localhost:8080/hello`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux mimacom-ivor-xps13 5.10.14-arch1-1 #1 SMP PREEMPT Sun, 07 Feb 2021 22:42:17 +0000 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
 - GraalVM version (if different from Java): can be seen in the package flag
 - Quarkus version or git rev: 1.11.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (NON-CANONICAL_2019-11-27T20:26:29Z_root)

**Additional context**
I tried without the JNIRegistrationFeature and without, no difference. I have seen already other similar bug reports but nothing really that matches this specific case and error

**Comment by geoand** [comment]
Quarkus makes no claim to work with OpenCV in native mode.
That would require a dedicated Quarkus extension that as of this point no one has written

**Comment by ntrp** [comment]
Didn't say it does, just trying to understand why it does not

**Comment by geoand** [comment]
This would probably be a good starting point in doing so: https://www.graalvm.org/reference-manual/native-image/JNI/

**Comment by ntrp** [comment]
To rephrase what I wrote and I guess the bug story too, is there any hit anybody can give me to make it work? Already checked the GraalVM JNI documentation but it's definitely not clear on the necessary steps to make it work. I already tried adding JNI configs

**Comment by gsmet** [comment]
You will probably need some `quarkus.jni.library-paths` set.

But there's also a good chance OpenCV will need some substitutions.

There is another issue open there: https://github.com/quarkusio/quarkus/issues/10448 .

**Comment by ntrp** [comment]
I have seen that issue already but it is not affecting me, I am using the openpnp distro of OpenCV which hosts the compiled library in the jar this is why I am perplexed it does not work. I tried adding the so file to the resource inclusion file. I will try to learn better the tools available for native images.

**Comment by gsmet** [comment]
@ntrp I think `KafkaStreamsProcessor` might be of interest to you. Kafka Streams depends on Rocksdb so files included in the jar.

Things like: https://github.com/quarkusio/quarkus/blob/master/extensions/kafka-streams/deployment/src/main/java/io/quarkus/kafka/streams/deployment/KafkaStreamsProcessor.java#L112-L130

And: https://github.com/quarkusio/quarkus/blob/master/extensions/kafka-streams/deployment/src/main/java/io/quarkus/kafka/streams/deployment/KafkaStreamsProcessor.java#L162-L168

In the end, you will need an extension and if you start working on that, it looks like something we could host in the Quarkiverse.

I'll have a look this afternoon and see if I can come with something in a limited time. I'll let you know how it goes.

**Comment by ntrp** [comment]
Ok interesting, I actually have seen that rocks db library file in the resource.json file generated by the agent, initially we tried compiling to native a streaming application which uses OpenCV.

**Comment by gsmet** [comment]
OK, I got something. At least your simple example passes.

I will clean things up and share it and we can iterate from that.

**Comment by gsmet** [comment]
@ntrp you can try this extension: https://github.com/quarkiverse/quarkus-opencv

Build it locally for now and I'll release on Maven Central once I got some feedback from you.

**Comment by ntrp** [comment]
Man, amazing! So simple and so fast :D. Looks like it works great, I tried it also on this example https://github.com/sshaaf/quarkus-opencv-examples so I guess it should work on our code too. It's weird because I guess the extension you created does two things, add the library to the native binary and load it on start. I tried to add the library by using the `-H:IncludeResources` switch and pointing to the `so` file but I guess the static block I was using does not work once built to native. I will try to integrate this into our more complex application but what you have right now is already worth releasing to maven central imho!

**Comment by gsmet** [comment]
Yeah for the record, the important part is this one: https://github.com/quarkiverse/quarkus-opencv/blob/master/deployment/src/main/java/io/quarkiverse/opencv/deployment/OpenCVProcessor.java#L40-L43 .

Otherwise the library gets initialized at build time and things go wrong.

**Comment by gsmet** [comment]
@ntrp I pushed the extension to Maven Central. Have fun!

**Comment by ntrp** [comment]
> Yeah for the record, the important part is this one: https://github.com/quarkiverse/quarkus-opencv/blob/master/deployment/src/main/java/io/quarkiverse/opencv/deployment/OpenCVProcessor.java#L40-L43 .
> 
> Otherwise the library gets initialized at build time and things go wrong.

Ah ok but that too would be fixable with the build flags `--initialize-at-run-time` I guess. Anyway thanks again for the quick release!

**Comment by gsmet** [comment]
Yeah, you could fix things with a ton of flags but having an extension makes it easy for everyone and it's not really much more work.
