### ISSUE TITLE
injecting Instance<S3Client> results in NPE at io.quarkus.amazon.s3.runtime.S3ClientProducer.client()

### ISSUE THREAD

**Issue by vladykin** [quarkusio/quarkus#15213]
**Describe the bug**
Attempt to call any S3Client method on instance injected as
```
  @Inject
  Instance<S3Client> s3ClientInstance;
```
results in NPE:
```
java.lang.NullPointerException
	at io.quarkus.amazon.s3.runtime.S3ClientProducer.client(S3ClientProducer.java:23)
	at io.quarkus.amazon.s3.runtime.S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_Bean.create(S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_Bean.zig:202)
	at io.quarkus.amazon.s3.runtime.S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_Bean.create(S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_Bean.zig:233)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
	at io.quarkus.amazon.s3.runtime.S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_ClientProxy.arc$delegate(S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_ClientProxy.zig:86)
	at io.quarkus.amazon.s3.runtime.S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_ClientProxy.createBucket(S3ClientProducer_ProducerMethod_client_c3e44358d8bba829ee2f6ae63d6f9ef0b4609f3a_ClientProxy.zig:2153)
	at S3ClientHolder.doSomethingIndirectly(S3ClientHolder.java:21)
```

S3Client injected directly as
```
@Inject
S3Client s3Client;
```
works without such NPE.

**Expected behavior**
Instance injected as
```
@Inject
Instance<S3Client> s3ClientInstance;
```
should work.

**Actual behavior**
Currently it throws NPE.

**To Reproduce**

Application bean:
```
import software.amazon.awssdk.services.s3.S3Client;

import javax.enterprise.inject.Instance;
import javax.inject.Inject;
import javax.inject.Singleton;

@Singleton
public class S3ClientHolder {

  @Inject
  Instance<S3Client> s3ClientInstance;

  public void doSomethingIndirectly() {
    s3ClientInstance.get().createBucket(b -> b.bucket("foobar"));
  }
}
```

Test:
```
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import javax.inject.Inject;

@QuarkusTest
public class ReproducerTest {

  @Inject
  S3ClientHolder bean;

  @Test
  void indirect_test() {
    bean.doSomethingIndirectly();
  }
}
```

pom.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>reproducer</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <quarkus.version>1.11.3.Final</quarkus.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-bom</artifactId>
                <version>${quarkus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-amazon-s3</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>url-connection-client</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>netty-nio-client</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
```

1. Create project containing files shown above
2. mvn clean verify

**Configuration**
```properties
quarkus.s3.aws.region=us-west-2
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=test
quarkus.s3.aws.credentials.static-provider.secret-access-key=test
```

**Environment (please complete the following information):**
 - Output of `uname -a`: `Linux 5.4.48-gentoo #2 SMP Wed Oct 7 20:15:36 MSK 2020 x86_64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz GenuineIntel GNU/Linux`
 - Output of `java -version`: `openjdk version "11.0.9.1" 2020-11-04 LTS`
 - Quarkus version or git rev: `1.11.3.Final`
 - Build tool (output of `mvnw --version`): `Apache Maven 3.6.3`

**Comment by gsmet** [comment]
Yeah, I confirm we can have this type of issues with the current setup. Probably worth some cleanup.

Thanks for the report!

**Comment by arvid-villen-adtoox** [comment]
Any updates on this?

**Comment by gsmet** [comment]
No I didn't have time to look at it. Things need to be rearchitected to use synthetic build items.

**Comment by gsmet** [comment]
Fix is coming in https://github.com/quarkusio/quarkus/pull/17836 . Sorry about the delay.
