### ISSUE TITLE
H2 upgrade from 1.4.197 to 1.4.199 makes Agroal DefaultDataSourceConfigTest test fail

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1522]
H2 upgrade from 1.4.197 to 1.4.199 makes Agroal DefaultDataSourceConfigTest test fail

The main trouble seems to be `Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database "mem:default" not found, and IFEXISTS=true, so we cant auto-create it [90146-199]`

```
[INFO] Running io.quarkus.agroal.test.DefaultDataSourceConfigTest
[INFO] H2 database started in TCP server mode
2019-03-15 19:02:37,948 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-03-15 19:02:39,306 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1358ms
2019-03-15 19:02:39,510 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.206s.
2019-03-15 19:02:39,510 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, narayana-jta]
2019-03-15 19:02:39,619 INFO  [io.quarkus] (main) Quarkus stopped in 0.003s
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.244 s <<< FAILURE! - in io.quarkus.agroal.test.DefaultDataSourceConfigTest
[ERROR] testDefaultDataSourceInjection  Time elapsed: 0.047 s  <<< ERROR!
java.sql.SQLException: Exception while creating new connection
        at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:225)
        at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:146)
        at io.agroal.pool.DataSource.getConnection(DataSource.java:61)
        at io.quarkus.agroal.test.DefaultDataSourceConfigTest.testDataSource(DefaultDataSourceConfigTest.java:52)
        at io.quarkus.agroal.test.DefaultDataSourceConfigTest.testDefaultDataSourceInjection(DefaultDataSourceConfigTest.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.test.QuarkusUnitTest$1.invoke(QuarkusUnitTest.java:123)
        at io.quarkus.agroal.test.DefaultDataSourceConfigTest$$QuarkusUnitTestProxy.testDefaultDataSourceInjection(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Exception while creating new connection
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:193)
        ... 49 more
Caused by: java.lang.RuntimeException: Exception while creating new connection
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:357)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:337)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:63)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database "mem:default" not found, and IFEXISTS=true, so we cant auto-create it [90146-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:205)
        at org.h2.message.DbException.get(DbException.java:181)
        at org.h2.engine.Engine.openSession(Engine.java:67)
        at org.h2.engine.Engine.openSession(Engine.java:201)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
        at org.h2.engine.Engine.createSession(Engine.java:161)
        at org.h2.server.TcpServerThread.run(TcpServerThread.java:160)
        at java.lang.Thread.run(Thread.java:748)

        at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
        at org.h2.engine.SessionRemote.done(SessionRemote.java:607)
        at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:143)
        at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:431)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:317)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
        at org.h2.Driver.connect(Driver.java:69)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:178)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:348)
        ... 6 more


```

**Comment by rsvoboda** [comment]
http://www.h2database.com/html/features.html#database_only_if_exists - Opening a Database Only if it Already Exists

**Comment by Sanne** [comment]
hi @rsvoboda, it's really not the intention of extensions to allow people to override the platform versions.

It's a bit sad but that's how it is.  I'm not planning to upgrade to 1.4.199 as it has some severe regressions...

So what is this issue about?

**Comment by rsvoboda** [comment]
1.4.198 has some issues too, we have to stay with 1.4.197

@Sanne, so in end the issue is not on our side as you pointed out, H2 is the trouble. I think I will close the issue.

Should we add a comment to bom so people don't waste their time trying to update H2 version ?
Or comments in this issues is sufficient note for users ?

**Comment by Sanne** [comment]
Adding a comment to the BOM is probably a good start :+1: 

I'm thinking we should also make it very clear in other docs / guides that version overrides aren't allowed; let's check what others think at the next design meeting?

**Comment by Sanne** [comment]
should we close this?
