### ISSUE TITLE
Jdbc-h2 throws com.oracle.svm.hosted.substitute.DeletedElementException during native image building

### ISSUE THREAD

**Issue by zhfeng** [quarkusio/quarkus#15267]
**Describe the bug**
This issue come across https://github.com/apache/camel-quarkus/pull/2272 when using the jdbc-h2 as an test datasource resource. The native image building throws the analyist errors

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor): 
	at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1531)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:84)
	at sun.security.pkcs11.SunPKCS11.initToken(SunPKCS11.java:1028)
	at sun.security.pkcs11.SunPKCS11$TokenPoller.run(SunPKCS11.java:852)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

**Expected behavior**
native image builds should successfully.

**Actual behavior**
native image building is failed with analyist erros.

**To Reproduce**

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 ```
    Linux 192.168.0.110 5.10.13-100.fc32.x86_64 #1 SMP Thu Feb 4 14:55:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
 ```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
```
1.12.0.Final
```
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**

I found the root cause is ```org.h2.jdbcx.JdbcDataSource.readObject()``` which is de-serializing the object by using ObjectStreamClass eventually. I add a subsition such as the following to get rid of the native image building errors.
```
@TargetClass(className = "org.h2.jdbcx.JdbcDataSource")
final class Target_org_h2_jdbcx_JdbcDataSource {
    @Delete
    private void readObject(ObjectInputStream in) {
    }
}
```
I've checked the method in h2 sources and this method seems a dead code. So does it make sense to delete this method as a fix ?

**Comment by zhfeng** [comment]
This should works by GraalVM 21 serialization support.
