### ISSUE TITLE
com.cronutils.model.time.generator.NoSuchValueException

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#15326]
**Describe the bug**

```java
@Scheduled(cron = "0 0 14,15,16 * * ?")
public void refresh() {

}
```
An error was reported when Quarkus started. `0 0 14,15,16 * * ?` The expression cannot be parsed. Replace it with `0 0 14 * * ?` is ok.

**Actual behavior**
```java
2021-02-25 17:56:28,679 DEBUG [com.cro.mod.tim.gen.AndFieldValueGenerator] (Quarkus Main Thread) Catched expected exception while generating candidates: com.cronutils.model.time.generator.NoSuchValueException
	at com.cronutils.model.time.generator.AndFieldValueGenerator.generateNextValue(AndFieldValueGenerator.java:46)
	at com.cronutils.model.time.generator.AndFieldValueGenerator.generateCandidatesNotIncludingIntervalExtremes(AndFieldValueGenerator.java:78)
	at com.cronutils.model.time.generator.FieldValueGenerator.generateCandidates(FieldValueGenerator.java:61)
	at com.cronutils.model.time.ExecutionTimeBuilder.forHoursMatching(ExecutionTimeBuilder.java:63)
	at com.cronutils.model.time.ExecutionTime.forCron(ExecutionTime.java:53)
	at io.quarkus.scheduler.runtime.SimpleScheduler$CronTrigger.<init>(SimpleScheduler.java:323)
	at io.quarkus.scheduler.runtime.SimpleScheduler.createTrigger(SimpleScheduler.java:183)
	at io.quarkus.scheduler.runtime.SimpleScheduler.<init>(SimpleScheduler.java:86)
	at io.quarkus.scheduler.runtime.SimpleScheduler_Bean.create(SimpleScheduler_Bean.zig:505)
	at io.quarkus.scheduler.runtime.SimpleScheduler_Bean.create(SimpleScheduler_Bean.zig:520)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.scheduler.runtime.SimpleScheduler_Observer_start_09e6c17011ef77dec3e1dd9987380b3d946e3db6.notify(SimpleScheduler_Observer_start_09e6c17011ef77dec3e1dd9987380b3d946e3db6.zig:135)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:60)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:81)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:642)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:   windows 10 64bit
 - Output of `java -version`:  11
 - GraalVM version (if different from Java):  21.0.0
 - Quarkus version or git rev:  1.12.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  mvnw --version

**Comment by gsmet** [comment]
From what I can see in the README, cron-utils uses `|` instead of `,`.

I wonder if we should replace `,` automatically (but I don't know if it could be used in other situations)

**Comment by mkouba** [comment]
Well, the scheduler is using the Quartz cron syntax by default, and the comma `,` should be supported as a special character there. We need to check the `cron-utils`  functionality.

In any case, you can try to configure a different syntax via the [`quarkus.scheduler.cron-type`](https://quarkus.io/guides/scheduler-reference#quarkus-scheduler_quarkus.scheduler.cron-type) property.

**Comment by aomsweet** [comment]
@gsmet  

Thank you, use `|` instead of `, ` is ok.

**Comment by mkouba** [comment]
@aomsweet Can you reproduce the problem consistently? I wasn't able to reproduce the issue. I've tried to modify the [scheduler-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/master/scheduler-quickstart) but no `NoSuchValueException` thrown.

**Comment by mkouba** [comment]
I'm going to close this issue. It seems that @aomsweet found a viable workaround and we have no reproducer.
