### ISSUE TITLE
ConfigValidationException by using passwords in config containing special characters

### ISSUE THREAD

**Issue by TuskRaider1988** [quarkusio/quarkus#15335]
**Describe the bug**
I'm using Quarkus and RabbitMQ in one maven-project for sending messages on a queue out of a java-service-class and retrieve them in another one. Therefore i'm using YAML-files in a configuration-module to define e.g. the connection-string for RabbitMQ. This connection-string contains amongst other things the used password for the RabbitMQ-user. For higher security, i created a password, which contains special characters like =, ! and +. This leads at startup to a ConfigValidationException.

**Expected behavior**
The connection-string leads to a connetion with the RabbitMQ-instance and enables my application to exchange messages using queueing.

**Actual behavior**
At startup appears a ConfigValidationException concerning the connection-string.

**To Reproduce**
Usage of special characters like =, / and + in a created password in a connection-string with RabbitMQ.
Startup of application

**Configuration**
(example)
connection-string: "amqps://username:9Rbj+9Rb5b/la!sFY/KX@rabbitmq.mydomain.com:5671/myvhost"

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
      Microsoft Windows [Version 10.0.18362.1256]

 - Output of `java -version`: 
      java version "1.8.0_231"
      Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
      Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

 - Quarkus version or git rev: 
    1.11.3.Final 

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
    Apache Maven 3.6.3

**Comment by gsmet** [comment]
Please provide the full stacktrace of the error.

**Comment by Postremus** [comment]
@gsmet 
I am a coworker of @TuskRaider1988, and also know about this problem.

Reproducer:
[config-validation-exception-password.zip](https://github.com/quarkusio/quarkus/files/6090674/config-validation-exception-password.zip)

Simply start it with mvn quarkus:dev, the exception from below is then printed.


This is the full stacktrace:
```
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-03-05 14:16:30,160 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
2021-03-05 14:16:30,160 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.config.ConfigValidationException: Configuration validation failed:
        awt.toolkit does not map to any root
        java.specification.version does not map to any root
        sun.cpu.isalist does not map to any root
        sun.jnu.encoding does not map to any root
        SESSIONNAME does not map to any root
        ALLUSERSPROFILE does not map to any root
        sun.arch.data.model does not map to any root
        quarkus.log.filter."io.netty.resolver.HostsFileParser".if-starts-with does not map to any root
        __INTELLIJ_COMMAND_HISTFILE__ does not map to any root
        SystemDrive does not map to any root
        java.vendor.url does not map to any root
        USERNAME does not map to any root
        quarkus.log.filter."io.vertx.core.impl.VertxImpl".if-starts-with does not map to any root
        ProgramFiles(x86) does not map to any root
        sun.boot.library.path does not map to any root
        FPS_BROWSER_USER_PROFILE_STRING does not map to any root
        sun.java.command does not map to any root
        PATHEXT does not map to any root
        jdk.debug does not map to any root
        maven.home does not map to any root
        DriverData does not map to any root
        sun.stderr.encoding does not map to any root
        java.specification.vendor does not map to any root
        java.version.date does not map to any root
        java.home does not map to any root
        file.separator does not map to any root
        java.vm.compressedOopsMode does not map to any root
        line.separator does not map to any root
        sun.stdout.encoding does not map to any root
        HOMEPATH does not map to any root
        java.specification.name does not map to any root
        java.vm.specification.vendor does not map to any root
        jdk.vendor.version does not map to any root
        PROCESSOR_IDENTIFIER does not map to any root
        quarkus.log.filter."io.netty.util.internal.PlatformDependent0".if-starts-with does not map to any root
        ProgramFiles does not map to any root
        PUBLIC does not map to any root
        windir does not map to any root
        quarkus.log.filter."org.jboss.threads".if-starts-with does not map to any root
        =:: does not map to any root
        user.script does not map to any root
        sun.management.compiler does not map to any root
        FPS_BROWSER_APP_PROFILE_STRING does not map to any root
        JAVA_HOME does not map to any root
        PROMPT does not map to any root
        java.runtime.version does not map to any root
        user.name does not map to any root
        quarkus.log.filter."org.jboss.resteasy.resteasy_jaxrs.i18n".if-starts-with does not map to any root
        quarkus.application.name does not map to any root
        OneDrive does not map to any root
        =C: does not map to any root
        APPDATA does not map to any root
        file.encoding does not map to any root
        guice.disable.misplaced.annotation.check does not map to any root
        java.vendor.version does not map to any root
        io.netty.noJdkZlibDecoder does not map to any root
        Path does not map to any root
        java.io.tmpdir does not map to any root
        java.version does not map to any root
        COMPUTERNAME does not map to any root
        MAVEN_PROJECTBASEDIR does not map to any root
        java.vm.specification.name does not map to any root
        java.awt.printerjob does not map to any root
        quarkus.profile does not map to any root
        ComSpec does not map to any root
        sun.os.patch.level does not map to any root
        CLASSWORLDS_LAUNCHER does not map to any root
        TERMINAL_EMULATOR does not map to any root
        java.library.path does not map to any root
        java.vendor does not map to any root
        HOMEDRIVE does not map to any root
        classworlds.conf does not map to any root
        sun.io.unicode.encoding does not map to any root
        NUMBER_OF_PROCESSORS does not map to any root
        library.jansi.path does not map to any root
        quarkus.application.version does not map to any root
        io.netty.machineId does not map to any root
        USERDOMAIN_ROAMINGPROFILE does not map to any root
        sun.desktop does not map to any root
        PROCESSOR_LEVEL does not map to any root
        quarkus.log.console.darken does not map to any root
        M2 does not map to any root
        java.class.path does not map to any root
        PROCESSOR_ARCHITECTURE does not map to any root
        java.vm.vendor does not map to any root
        jvmConfig does not map to any root
        PSModulePath does not map to any root
        user.variant does not map to any root
        quarkus.log.category."io.vertx.core.http.impl.HttpServerRequestImpl".level does not map to any root
        MAVEN_HOME does not map to any root
        user.timezone does not map to any root
        maven.conf does not map to any root
        os.name does not map to any root
        java.vm.specification.version does not map to any root
        USERDNSDOMAIN does not map to any root
        WDIR does not map to any root
        sun.java.launcher does not map to any root
        user.country does not map to any root
        sun.cpu.endian does not map to any root
        user.home does not map to any root
        user.language does not map to any root
        CLASSWORLDS_JAR does not map to any root
        io.netty.allocator.maxOrder does not map to any root
        ProgramData does not map to any root
        ProgramW6432 does not map to any root
        M2_HOME does not map to any root
        java.awt.graphicsenv does not map to any root
        LOCALAPPDATA does not map to any root
        USERDOMAIN does not map to any root
        LOGONSERVER does not map to any root
        path.separator does not map to any root
        ERROR_CODE does not map to any root
        EXEC_DIR does not map to any root
        os.version does not map to any root
        java.runtime.name does not map to any root
        sun.nio.ch.bugLevel does not map to any root
        java.vm.name does not map to any root
        quarkus.http.host does not map to any root
        MAVEN_CMD_LINE_ARGS does not map to any root
        CommonProgramFiles does not map to any root
        java.vendor.url.bug does not map to any root
        OS does not map to any root
        user.dir does not map to any root
        os.arch does not map to any root
        maven.multiModuleProjectDirectory does not map to any root
        JAVACMD does not map to any root
        PROCESSOR_REVISION does not map to any root
        CommonProgramW6432 does not map to any root
        quarkus.log.filter."io.netty.util.internal.PlatformDependent0".target-level does not map to any root
        java.util.logging.manager does not map to any root
        TEMP does not map to any root
        SystemRoot does not map to any root
        java.vm.info does not map to any root
        USERPROFILE does not map to any root
        java.vm.version does not map to any root
        TMP does not map to any root
        AZURE_AUTH_LOCATION does not map to any root
        CommonProgramFiles(x86) does not map to any root
        java.class.version does not map to any root
        IDEA_INITIAL_DIRECTORY does not map to any root
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:640)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:602)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:43)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:31)
        at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:52)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigMappings510524965.deploy_0(ConfigBuildStep$registerConfigMappings510524965.zig:130)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigMappings510524965.deploy(ConfigBuildStep$registerConfigMappings510524965.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:554)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by radcortez** [comment]
Thanks for the reproducer, I'll have a look.

**Comment by radcortez** [comment]
@TuskRaider1988 @Postremus the issue is not about the config content, but how the config is mapped. A `@ConfigMapping` maps all properties in a root and reports missing properties mappings.

So what happens here is that the validation is complaining that the reported properties are not mapped in the `@ConfigMapping` class. Because there is no prefix set up, it just assume an empty root and validates all properties. My recommendation is to set a namespace and set any configuration there and set the namespace prefix in the `@ConfigMapping` annotation.

Let me know if that help.

**Comment by Postremus** [comment]
@radcortez I think I figured out the problem. The connection String is of the URI class. The connection string defined by @TuskRaider1988 is an invalid URI.
In `ImplicitConverter#convert(String value)`, the URI(String) constructor is called with the connection string. This throws an `InvoationTargetException`, with the target containing a usefull message:
![image](https://user-images.githubusercontent.com/1223135/110284692-74921800-7fe2-11eb-9cd1-f31a212eaab2.png)

The URISyntaxException is never printed though as exception:
```
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-03-08 07:42:05,142 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
2021-03-08 07:42:05,141 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.config.ConfigValidationException: Configuration validation failed:
        java.lang.IllegalArgumentException: SRCFG00019: Failed to create new instance from Converter constructor
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:640)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:602)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:43)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:31)
        at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:52)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigMappings510524965.deploy_0(ConfigBuildStep$registerConfigMappings510524965.zig:130)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigMappings510524965.deploy(ConfigBuildStep$registerConfigMappings510524965.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:543)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

From the stacktrace above, I would have no Idea whats going on.

New reproducer (quarkus 1.12.1): 
[config-validation-exception-password.zip](https://github.com/quarkusio/quarkus/files/6099385/config-validation-exception-password.zip)

Again, simply start it with mvn quarkus:dev.

**Comment by radcortez** [comment]
Thanks. Let me have a look.

**Comment by radcortez** [comment]
Ah, the issue in this case is that you need to encode the special characters for the `URI` constructor. Try calling `new URI` directly to see the result. We cannot really encode the entire `String` that converts to an `URI` because it may encode other characters required for the `URI` parsing and provide an unexpected `URI`.

I see a couple of alternatives:

1. Can't you pass the login / password into separate properties? I'm guessing that the RabbitMQ API should provide a way to set the login and password
2. Set the login and password separately (or just the password) and provide a `Converter` to do the encoding, and use property replacement to set the password in the original connection string.

Let me know if this helps.

**Comment by Postremus** [comment]
We will go with option number 1, since it is propably the easier of the two. The RabbitMQ ConnectionFactory already provides seperate methods to set the username, password, and vhost. Thank you for your advice!

**Comment by radcortez** [comment]
Ok, great. I'll close this issue. If you still think there is something for us to do here, please reopen :)
