### ISSUE TITLE
qute templates  native run error but quarkus:dev is ok

### ISSUE THREAD

**Issue by weir2010** [quarkusio/quarkus#15348]
native  weirblog-quarkus-1.0-runner    run error:

`2021-02-26 14:11:13,908 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to / failed, error id: e4a4f0ee-6c92-4f06-86a6-b45d8d5c7ff1-1: org.jboss.resteasy.spi.UnhandledException: java.util.concurrent.CompletionException: io.quarkus.qute.TemplateException: Loop section error in template index.html on line 108: [indexVo.pageView.records] resolved to [io.quarkus.qute.Results$Result] which is not iterable
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:614)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)`

**but：quarkus：dev is  ok**

html ：
{#for posts in indexVo.pageView.records}.
...........{/for}
java:
`IndexVo indexVo = new IndexVo();
		indexVo.setPageView(pageView);
		indexVo.setRightNews(queryResult.getResultList());
		indexVo.setRightReads(rightReads);
		return index.data("indexVo", indexVo);`

public class IndexVo {

	private PageView<Posts> pageView;
	private String index;
	private List<Posts> rightNews;
	private List<Posts> rightReads;

public class PageView<T> {
	/** 分页数据 **/
	private List<T> records;
	/** 页码开始索引和结束索引 **/
	private PageIndex pageIndex;

@Entity
public class Posts extends BaseVo {

	@Id
	public Integer id;
	public String postTitle;
	@JsonbDateFormat("yyyy-MM-dd HH:mm:ss")
	public Date createDate = new Date();
	@JsonbDateFormat("yyyy-MM-dd HH:mm:ss")
	public Date updateDate;
	public Integer userId;
	public String types;
	public String description;

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`:  11
 - GraalVM version (if different from Java): 21.0.0.2
 - Quarkus version or git rev: 1.12.0
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):

**Comment by mkouba** [comment]
@weir2010 It looks like in the dev mode the reflection fallback resolver is used, i.e. properties are accessed via `java.lang.reflect` constructs. However, this fallback does not work in the native image, unless the `@io.quarkus.runtime.annotations.RegisterForReflection` is used on the target class. There are several Qute-specific ways how to fix this problem:
1. Use [Type-safe Templates](https://quarkus.io/guides/qute-reference#typesafe_templates) or [Type-safe Expressions](https://quarkus.io/guides/qute-reference#typesafe_expressions) - in this case, a special resolver is generated automatically
2. Use [@TemplateData](https://quarkus.io/guides/qute-reference#template_data) - again, a special resolver is generated

NOTE: A special resolver is also generated for a [CDI bean injected in the template](https://quarkus.io/guides/qute-reference#injecting-beans-directly-in-templates).

**Comment by weir2010** [comment]
@mkouba  It's settled. Thank you

**Comment by raychenon** [comment]
Thanks, it works by applying @CheckedTemplate and @TemplateData

**Comment by mkouba** [comment]
For the record, it's documented here: https://quarkus.io/guides/qute-reference#native_executables
