### ISSUE TITLE
MalformedURLException with Quarkus 1.12 (or master) when the app in `,;~!@#$%^&()` directory

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#15358]
Getting MalformedURLException with Quarkus 1.12 (or master) when the app in `,;~!@#$%^&()` directory. Works well with Quarkus 1.11.
Quarkus 1.12 - tests are working, dev mode is working, but running `java -jar ...` fails. Using JDK 11.
Seems `#` character is problematic for SRYE Config, `Caused by: java.net.MalformedURLException: no !/ found in url spec:file:/Users/rsvoboda/tmp/,;~!@` mentioned just part of `,;~!@#$%^&()` directory

Reproducer:
```
mkdir ',;~!@#$%^&()'
cd ',;~!@#$%^&()'
mvn io.quarkus:quarkus-maven-plugin:1.12.0.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.getting.started.GreetingResource" \
    -Dpath="/hello"
cd getting-started
mvn package
java -jar target/quarkus-app/quarkus-run.jar
```

Stacktrace:
```
$ java -jar target/quarkus-app/quarkus-run.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
Caused by: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: Error accessing configuration file
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1172)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1205)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:90)
	at io.smallrye.config.SmallRyeConfig.buildConfigSources(SmallRyeConfig.java:83)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:66)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:358)
	at io.quarkus.runtime.generated.Config.<clinit>(Config.zig:326)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:57)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	... 6 more
Caused by: java.net.MalformedURLException: no !/ found in url spec:file:/Users/rsvoboda/tmp/,;~!@
	at java.base/java.net.JarURLConnection.parseSpecs(JarURLConnection.java:172)
	at java.base/java.net.JarURLConnection.<init>(JarURLConnection.java:158)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.<init>(JarURLConnection.java:81)
	at java.base/sun.net.www.protocol.jar.Handler.openConnection(Handler.java:41)
	at java.base/java.net.URL.openConnection(URL.java:1074)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1162)
	... 26 more
```

**Comment by jaikiran** [comment]
Hello @rsvoboda, I have opened https://github.com/quarkusio/quarkus/pull/15360 with a potential fix.
