### ISSUE TITLE
REST client / RESTEasy / Apache HTTP Client does not regard TCP RST?

### ISSUE THREAD

**Issue by skasten** [quarkusio/quarkus#15383]
Hello together,

as far as I have analysed it, it is not possible to set any keep-alive options etc. in the Quarkus configuration for the REST Client, correct? As far as I see it is only possible for the Dynamo-DB extension etc. The normal RESTEasy client seems not to have specific properties/configuration to set options for the underlying Apache HTTP Client Connection pool.

**What is the problem?**
We use Quarkus - I think like many other - within a Docker Container in a Docker Swarm environment. The Docker Swarm uses Linux IPVS for the connections between services (see https://forums.docker.com/t/tcp-timeout-that-occurs-only-in-docker-swarm-not-simple-docker-run/58179). Thus, the inter-service communication between two Quarkus-base services is done over this IPVS link. Now Quarkus (or Resteasy / Apache HTTP Client) seems to leave HTTP-connections open and pools them (I think this is done by the underlying Apache HTTP Client?). 

IPVS has a timeout per default of 15 minutes. So on 15 minutes inactivity on an open TCP connection, it seems to send a TCP RST. The Quarkus rest client does not recognise this RST, unless the next request is done - then it seems that the read of the response is getting a "Connection reset" exception from Java (which should come from the RST packet). 
Even if you use resilience mechanisms (like retry) it does not help, as there may be some more connections in the pool, all getting the RST when reading the response.

**Workaround**
We have worked around the problem by using DNSrr (round robin) endpoint setting within the Docker Swarm deployment configuration. But as DNSrr has other downsides, it would be nice if Quarkus can come up with a solution to set keep-alive properties for the pooled REST client HTTP connections.

**Stacktrace**
As the problem is now a few days older, I have only a part of a stack trace, sorry:
> stackTrace:
>	org.jboss.resteasy.spi.UnhandledException: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: java.net.SocketException: Connection reset at  org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106) at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372) at

**Affected versions**
We tested it with Quarkus 1.11, which was the latest available version, as we tested it. We have not tested it with Quarkus 1.12 (due to time, as it is time consuming to reproduce the timeout behaviour)

**Ticket duplicates**
This ticket may be an duplicate of https://github.com/quarkusio/quarkus/issues/15056 - but I think that ticket does describe a more special case and only references to connection timeouts (instead of TCP keep-alive, which would be better?).

I hope I got everything right :-)

**Comment by skasten** [comment]
Hey togther, 

do you have any updates for this topic? Is it planned to integrate connection pool checks for the HTTP connections of the RESTEasy client?

Best regards

**Comment by asoldano** [comment]
@liweinan do you have time to help on this?

**Comment by ambition-consulting** [comment]
We are still facing it - basically stopping us from deploy to production.

**Comment by ambition-consulting** [comment]
@asoldano @ronsigal @liweinan We intend to bring our first Quarkus microservice application to production next week, and still face connection resets presumably due to this error resulting from using the standard quarkus rest client. Clearly using HTTP/REST is a basic requirement, so I am astonished how such a bug can still exist - Docker Swarm, Kubernetes, and most other microservice orchestrations on Linux use the Linux IPVS, thus resulting in this error.

Cleary you want the world to use your application without failing on basic connections all the time - please help or at least provide an outlook on when this will get fixed!

**Comment by skasten** [comment]
Hi together,
maybe someone can write down some information, how this could be solved.
As far as I have understand this, configuration properties have to be collected on Quarkus application side, delegated to RESTEasy and from RESTEasy to the Apache HTTP Client, right?
What I don't know: 
* does RESTEasy already have a possibility to retrieve and delegate those parameters?
* how to I collect config parameter and pass them to RESTEasy?
If someone could provide some information, how these things can be done, I will try to look into the source and write a fix, if possible.
Best regards

**Comment by TomasHofman** [comment]
Hello,

I think it should be possible to configure the rest client by registering a RestClientBuilderListener in the application (things like connection TTL or pool parameters).

```
public class CustomRestClientBuilderListener implements RestClientBuilderListener {

    @Override
    public void onNewBuilder(RestClientBuilder builder) {
        builder.property("resteasy.connectionTTL", Arrays.asList(2345L, TimeUnit.MILLISECONDS));
        builder.property("resteasy.maxPooledPerRoute", 1);
    }
}
```
and create META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderListener file with the class name of the custom listener in it.

Basically all parameters available in [ResteasyClientBuilder](https://github.com/resteasy/Resteasy/blob/main/resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java) should be configurable this way.

See a modified rest-client-quickstart: https://github.com/TomasHofman/quarkus-quickstarts/commit/abfffca591f55aa1b82d3ed67c40df70830e6d5c

There may be some additional work needed if you want this to work in native, see this StackOverflow answer: https://stackoverflow.com/a/63850492


So which parameters would be most helpful here, if they were to be exposed via the Quarkus' `application.properties` file?

**Comment by TomasHofman** [comment]
@skasten @ambition-consulting would something like https://github.com/quarkusio/quarkus/pull/17220 help?

**Comment by ambition-consulting** [comment]
I will implement and test today.
*--*
John-Paul Cunliffe, ambition.consulting <http://www.ambition.consulting>
*Simplicity is the soul of efficiency. (Austin Freeman)*

Dorothea-Schlegel-Straße 20
61130 Nidderau
Germany

Java+Kotlin/Spring, Actionscript/Flex, Dart+Typescript/Angular, Scala/Play
- Software Developer, Requirements Analyst, Architect and DevOops

+ 49 (0) 151 61510016
<+49%201516%201510016>

**Comment by ambition-consulting** [comment]
No luck, still getting the error - but maybe less frequent:

`com.fiserv.apm.error.ProcessingException: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: java.net.SocketException: Connection reset
	at com.fiserv.apm.error.ProcessingException$Builder.build(ProcessingException.java:73)
	at com.fiserv.apm.error.ProcessingException$Builder.buildUnknownCommunication(ProcessingException.java:58)
	at com.fiserv.apm.core.app.service.local.CoreExceptionBuilder_ClientProxy.buildUnknownCommunication(CoreExceptionBuilder_ClientProxy.zig:316)
	at com.fiserv.apm.tech.operation.Operation.transformUncaughtUniFailures(Operation.java:26)
	at com.fiserv.apm.core.app.controller.operation.mission.DelegateMissionSale_Subclass.transformUncaughtUniFailures$$superaccessor6(DelegateMissionSale_Subclass.zig:977)
	at com.fiserv.apm.core.app.controller.operation.mission.DelegateMissionSale_Subclass$$function$$6.apply(DelegateMissionSale_Subclass$$function$$6.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	...
	at com.fiserv.apm.core.app.controller.operation.mission.DelegateMissionSale_Subclass.transformUncaughtUniFailures(DelegateMissionSale_Subclass.zig:934)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	...
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: java.net.SocketException: Connection reset
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:297)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:491)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.lambda$executorSubmit$11(ClientInvocation.java:773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 8 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:84)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:278) `

Have used and checked, that it gets used (via successful breakpoints before rest client building), that this gets used:
`public class CustomRestClientBuilderListener implements RestClientBuilderListener {

	@Override
	public void onNewBuilder(final RestClientBuilder builder) {
		builder.property("resteasy.connectionTTL", Arrays.asList(1L, TimeUnit.NANOSECONDS));
		builder.property("resteasy.maxPooledPerRoute", 1);
		builder.property("resteasy.connectionPoolSize", 100);
	}
}
`

Any suggestions on alternative configurations? connectionPoolSize 1 is no option for us in production.

**Comment by liweinan** [comment]
It's hard to say whether it's configuration problem or TCP layer issue. If the situation happen less frequently, it needs more detail analysis.  I'll reproduce it in my local env and analysis it with Wireshark. It needs some time.

**Comment by TomasHofman** [comment]
Can you share something about your Docker Swarm setup, docker version, etc? A simple reproducer apps & instructions on how to configure the swarm would be perfect, so that we can reproduce the situation locally.

I was trying to setup a simple swarm with a rest service and a rest client, but I don't think that my setup uses IPVS. My steps were:

```
docker network create --subnet 100.0.0.0/24 -d overlay net1
docker service create --name rest-endpoint --network net1 -p 8081:8080 quarkus/rest-json-jvm
docker service create --name rest-client --network net1 -p 8080:8080 quarkus/rest-client-jvm
```

(My rest-client app uses http://rest-endpoint:8080/ as an endpoint URL.)

When I run `iptables -t nat -nvL`, I would expect to see some rules with "ipvs" listed, but there are none.

**Comment by liweinan** [comment]
I put the reproducer here: https://github.com/liweinan/quarkus-pr-15383

And I can confirm that the configuration mentioned by @TomasHofman is working:

![Uploading 989F73A2-12F3-4F36-8D7E-D4301B8B43ED.png…]

![C0524221-1995-4705-B6A6-A35B23141BEE](https://user-images.githubusercontent.com/201907/118646518-dfe23c80-b812-11eb-9240-da42bf0302a9.png)

**Comment by TomasHofman** [comment]
I did another experiment without docker swarm, instead I'm setting up IPVS loadbalancer manually.

Steps:

```
# run two instances of a rest service:
docker run -d --name server1 -p 8081:8080 quarkus/rest-json-jvm
docker run -d --name server2 -p 8082:8080 quarkus/rest-json-jvm

# figure out IP addresses on the bridge network via docker inspect -> 172.17.0.2 and 172.17.0.3

# create virtual service at 1.2.3.4:
sudo ipvsadm -A -t 1.2.3.4:80 -s rr

# add two server addresses for load balancing:
sudo ipvsadm -a -t 1.2.3.4:80 -r 172.17.0.2:8080 -m
sudo ipvsadm -a -t 1.2.3.4:80 -r 172.17.0.3:8080 -m

# set connection timeouts to 10 secs, so that we don't have to wait for 15 minutes
sudo ipvsadm --set 10 10 10
```

With above setup, run a Quarkus rest client app, target URL set to "http://1.2.3.4/". (I use modified Quarkus rest client quickstart: https://github.com/TomasHofman/quarkus-quickstarts/commit/5e5a2dee5bd071e1c6571a1a269e38372db7e9bd)

Results bellow.

### Case 1 - Without setting the "resteasy.connectionTTL"

* Make the first request -> success.
* Wait for 10 secs so that the connection is discarded by IPVS, but still present in the resteasy connection pool.
* Make a second request -> no response, the rest client seems to wait indefinitely (or at least for the couple of minutes I was waiting).

### Case 2 - Setting "resteasy.connectionTTL" = 2000 ms

* The first request successful.
* Wait for 10 secs so that the connection is discarded by IPVS. By this time however it should have been discarded by the resteasy connection pool too.
* Second request is successful too - fresh connection was created.


This seems to me to be working as expected. Aren't you guys running into a different issue?

**Comment by skasten** [comment]
@TomasHofman thank you for the work. If it works like described in the PR, then this should be the configuration possibilities needed to avoid our initial problem. We will test the solution here and give feedback. 
@ambition-consulting You configuration with a TTL of 1ns may be a little bit hard? ;-) Maybe test it with a TTL of some seconds, like Tomas.

**Comment by ambition-consulting** [comment]
@skasten happy to - am redeploying now with 2 seconds and will retest.

**Comment by TomasHofman** [comment]
@ambition-consulting @skasten it didn't occur to me before, but I looked into the code and the TTL value is internally converted to milliseconds. With the value of 2 ns that gives 0 ms, which means no expiry.

Please do retest with e.g. seconds and let us know :). IMO the only important thing is that the TTL should be shorter or equal to connection timeout in IPVS, which is 15 minutes by default.

**Comment by liweinan** [comment]
+1 to the experiment :D Yes I feel that simplify the test situation will be helpful.

In my local env, even I set the `ttl` to `1 nanosecond` seems has no difference. Let me do more detail tests and analysis the TCP level packets with Wireshark and report my test result here.

**Comment by liweinan** [comment]
I dug the implementation a little bit and here are my findings:

![3E3DF40A-FECB-4DE3-BC45-788FB55D213C](https://user-images.githubusercontent.com/201907/118793709-707c5380-b8cb-11eb-8900-2ceeeffee1da.png)

![FB8E6DF8-A70B-4478-B583-347C98B7BFFB](https://user-images.githubusercontent.com/201907/118793724-73774400-b8cb-11eb-849c-de775673f194.png)

So from above screenshot the `connectionTTL` is calculated and passed into `org.apache.http.conn.HttpClientConnectionManager`. 

I need to understand more detail on how does this `HttpClientConnectionManager` use the parameter. For now it seems no effect in my local env.

**Comment by TomasHofman** [comment]
@liweinan to clarify, do you mean setting sub-millisecond TTL has no effect, meaning it's equivalent to setting TTL = 0 (which means no TTL is set)?

The expectation is that:

* not configuring TTL (or configuring sub-millisecond TTL as we now noticed) leaves the REST client vulnerable to broken connections (because the connection is discarded by IPVS load balancer after 15 minutes, but is still considered as usable by the Resteasy connection pool).
* Configuring TTL (ideally to the same value as the timeout configured to IPVS, but can be shorter), should prevent above problem from happening, because the connection would be discarded by both the IPVS and the Resteasy connection pool (after the timeout) and a fresh connection would be opened.

**Comment by liweinan** [comment]
> @liweinan to clarify, do you mean setting sub-millisecond TTL has no effect, meaning it's equivalent to setting TTL = 0 (which means no TTL is set)?

From screenshot I can see that the `TTL=1` value is passed into `PoolingHttpClientConnectionManager`, but I'm. not sure how does it use this parameter. I need to analysis deeper and give back my findings.
> 
> The expectation is that:
> 
> * not configuring TTL (or configuring sub-millisecond TTL as we now noticed) leaves the REST client vulnerable to broken connections (because the connection is discarded by IPVS load balancer after 15 minutes, but is still considered as usable by the Resteasy connection pool).

The default value I see is `0`.

> * Configuring TTL (ideally to the same value as the timeout configured to IPVS, but can be shorter), should prevent above problem from happening, because the connection would be discarded by both the IPVS and the Resteasy connection pool (after the timeout) and a fresh connection would be opened.

That's what I expected. But even I set `TTL=1` currently, my test still work: https://github.com/liweinan/quarkus-pr-15383/blob/main/src/test/java/org/acme/rest/client/CountriesResourceTest.java#L17

Which means the request was succeed and didn't timtout (because the ttl value is set to just 1 millisecond). This result seems confusing to me. Maybe I didn't understand the underlying working scheme correctly.

I'll do more investigation on it and give back my findings.

**Comment by ambition-consulting** [comment]
We have not experienced connections reset after increasing the connectionTTL to 2 minutes. The window between the minimum value of 1 millisecond and the IPVS timeout seems to work.
![image](https://user-images.githubusercontent.com/4218334/118941451-08248500-b952-11eb-8226-fbd4df452777.png)
Will let you know if this situation changes.

**Comment by TomasHofman** [comment]
That's great news, thanks for reporting @ambition-consulting.

**Comment by liweinan** [comment]
@TomasHofman so in the screenshot you can see I set it to 1 miilisecond:

![image](https://user-images.githubusercontent.com/201907/118967515-6460c680-b99d-11eb-944e-cf057742982e.png)

(resteasy will convert it to miilisecond and pass into apache client)

**Comment by liweinan** [comment]
@ambition-consulting cool! :D

**Comment by TomasHofman** [comment]
BTW can this be marked as resolved?

**Comment by ambition-consulting** [comment]
I would wish for other developers not having to go through this riddle themselves and instead set a reasonable default in quarkus.
