### ISSUE TITLE
javax.xml.parsers.FactoryConfigurationError when using apache xmlrpc-client to make request to bugzilla.

### ISSUE THREAD

**Issue by soul2zimate** [quarkusio/quarkus#15398]
**Describe the bug**
Unable to make request to bugzilla with apache xmlrpc-client due to `Caused by: javax.xml.parsers.FactoryConfigurationError: Provider for javax.xml.parsers.SAXParserFactory cannot be found`

**Expected behavior**
successfully make a request to bugzilla with apache xmlrpc-client and get data back.

**Actual behavior**
exception happens as below example.

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

https://github.com/soul2zimate/quarkus-quickstarts/tree/getting-started-xmlrpc-client

1. check out the reproducer source code and run `mvn clean install`

2. run `java -Dusername=your_bugzilla-usrename -Dpassword=your_bugzilla_password -jar target/quarkus-app/quarkus-run.jar`

3. open `http://127.0.0.1:8080/hello/request/1161448` make a request for an example bug https://bugzilla.redhat.com/show_bug.cgi?id=1161448

4 you will see exception like:

```
2021-03-02 11:38:10,600 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: 0c825430-5faf-4332-8164-65fbc53b79ba-1: org.jboss.resteasy.spi.UnhandledException: javax.xml.parsers.FactoryConfigurationError: Provider for javax.xml.parsers.SAXParserFactory cannot be found
at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at java.base/java.lang.Thread.run(Thread.java:834)
at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider for javax.xml.parsers.SAXParserFactory cannot be found
at javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source)
at org.apache.xmlrpc.util.SAXParsers.<clinit>(SAXParsers.java:34)
at org.apache.xmlrpc.client.XmlRpcStreamTransport.newXMLReader(XmlRpcStreamTransport.java:176)
at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:181)
at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)
at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)
at org.acme.getting.started.BugzillaService.executeRequest(BugzillaService.java:42)
at org.acme.getting.started.BugzillaService.getIssue(BugzillaService.java:33)
at org.acme.getting.started.BugzillaService_ClientProxy.getIssue(BugzillaService_ClientProxy.zig:188)
at org.acme.getting.started.GreetingResource.hello(GreetingResource.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
... 15 more
```

**Environment (please complete the following information):**
 - Quarkus version 1.12.0.Final

**Comment by gsmet** [comment]
Have you tried excluding `xml-apis:xml-apis`? It looks a lot like a conflict between the JDK classes and the ones from this jar.

**Comment by soul2zimate** [comment]
```
            <exclusions>
                <exclusion>
                    <artifactId>xml-apis</artifactId>
                    <groupId>xml-apis</groupId>
                </exclusion>
            </exclusions>
```
@gsmet Thank you, the exclusion above works. but I saw another strange exception from a different reproducer in development mode with `mvn compile quarkus:dev`, does below exceptions ring a bell to you ? I don't see any application code in the stacktrace.

```
2021-03-03 15:08:03,397 INFO  [org.jbo.threads] (main) JBoss Threads version 3.2.0.Final
2021-03-03 15:08:04,080 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:244)
	... 15 more
Caused by: java.lang.NoSuchMethodError: javax.ws.rs.core.Variant.<init>(Ljavax/ws/rs/core/MediaType;Ljava/lang/String;Ljava/lang/String;)V
	at io.quarkus.resteasy.runtime.NotFoundExceptionMapper.<clinit>(NotFoundExceptionMapper.java:60)
	at io.quarkus.resteasy.runtime.ExceptionMapperRecorder.setReactiveRoutes(ExceptionMapperRecorder.java:23)
	at io.quarkus.deployment.steps.ResteasyBuiltinsProcessor$addReactiveRoutesExceptionMapper-838102434.deploy_0(ResteasyBuiltinsProcessor$addReactiveRoutesExceptionMapper-838102434.zig:90)
	at io.quarkus.deployment.steps.ResteasyBuiltinsProcessor$addReactiveRoutesExceptionMapper-838102434.deploy(ResteasyBuiltinsProcessor$addReactiveRoutesExceptionMapper-838102434.zig:40)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:81)
	... 15 more

2021-03-03 15:08:04,081 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
```

**Comment by gastaldi** [comment]
Tested with 2.14.2.Final. The error no longer occurs but Bugzilla requires logging with an API key, which xmlrpc-client doesn't seem to support (easily). 

Closing as this is no longer a Quarkus issue
