### ISSUE TITLE
Validation is not working on Spring REST Data on Native

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15409]
**Describe the bug**
Spring REST Data extension stopped working when using validations in Native. 

This is a regression issue caused by this commit: https://github.com/quarkusio/quarkus/commit/8c76e39060f6b288eaaeeb28bc477b33a972a40f.

This is how my Spring endpoint looks like:

```java
@RepositoryRestResource(exported=false, path = "books", collectionResourceRel = "books")
public interface BookRepository extends PagingAndSortingRepository<Book, Long> {

    @Override
    @RestResource(exported = true)
    Page<Book> findAll(Pageable pageable);

    @RestResource(exported = true)
    List<Book> findByOrderByNameDesc();

    @Override
    @RestResource(path = "id")
    Optional<Book> findById(Long id);

    @Override
    @RestResource
    Book save(Book book);
}
```

And my entity:

```java
@Entity
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Length(min = 2, max = 50, message = "length must be between {min} and {max}")
    @NotBlank(message = "Name may not be blank")
    private String name;

    @Length(min = 2, max = 50, message = "length must be between {min} and {max}")
    @NotBlank(message = "Author may not be blank")
    private String author;

    @JsonBackReference
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "library_id")
    private Library library;
// ...
```

When calling a POST/PUT endpoint and the validation fails, the endpoint fails with Internal Server Error:

```
Internal Server Error - Error id 7839b916-3415-4673-8059-572770e26c35-1
```

Expectation is that it should return the constraint violations. 
Note that the same is working fine in JVM.
I've reverted the above commit and everything works in JVM and Native.

**To Reproduce**

1- git clone https://github.com/Sgitario/beefy-scenarios
2- git checkout reproducer_15409
3- cd beefy-scenarios/602-spring-data-rest
4- mvn clean verify -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:21.0.0-java11 -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=4g (it needs to have built quarkus master locally)

**Environment (please complete the following information):**
Quarkus version or git rev: 999-SNAPSHOT (1.12.1.Final)

**Comment by Sgitario** [comment]
cc @gytis

**Comment by gytis** [comment]
Thanks @Sgitario I'll look into it.

**Comment by gsmet** [comment]
Could you please include the full stack trace in the issue description? I would bet you have it in the logs.

**Comment by Sgitario** [comment]
> Could you please include the full stack trace in the issue description? I would bet you have it in the logs.

This is the full exception:

```
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /books failed, error id: 7839b916-3415-4673-8059-572770e26c35-2: org.jboss.resteasy.spi.UnhandledException: io.quarkus.rest.data.panache.RestDataPanacheException: Failed to add an entity
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: io.quarkus.rest.data.panache.RestDataPanacheException: Failed to add an entity
	at org.acme.spring.data.rest.BookRepositoryJaxRs_adea41968873302399c279efce2c46dbd56e4f48.addHal(BookRepositoryJaxRs_adea41968873302399c279efce2c46dbd56e4f48.zig:1398)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 17 more
Caused by: javax.validation.ConstraintViolationException: Validation failed for classes [org.acme.spring.data.rest.Book] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='length must be between 2 and 50', propertyPath=name, rootBeanClass=class org.acme.spring.data.rest.Book, messageTemplate='length must be between {min} and {max}'}
]
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:140)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:80)
	at org.hibernate.action.internal.EntityIdentityInsertAction.preInsert(EntityIdentityInsertAction.java:188)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:78)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:645)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:282)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:263)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:317)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:330)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:287)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:193)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:123)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:185)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:128)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:55)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:93)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:720)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:706)
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.persist(TransactionScopedSession.java:139)
	at io.quarkus.hibernate.orm.runtime.session.ForwardingSession.persist(ForwardingSession.java:53)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:99)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:94)
	at org.acme.spring.data.rest.BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl.save(BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl.zig:57)
	at org.acme.spring.data.rest.BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl_Subclass.save$$superaccessor2(BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl_Subclass.zig:460)
	at org.acme.spring.data.rest.BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl_Subclass$$function$$2.apply(BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl_Subclass$$function$$2.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:127)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.spring.data.rest.BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl_Subclass.save(BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl_Subclass.zig:417)
	at org.acme.spring.data.rest.BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl.save(BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl.zig:77)
	at org.acme.spring.data.rest.BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl_ClientProxy.save(BookRepository_adea41968873302399c279efce2c46dbd56e4f48Impl_ClientProxy.zig:645)
	at org.acme.spring.data.rest.BookRepositoryResourceImpl_adea41968873302399c279efce2c46dbd56e4f48.add(BookRepositoryResourceImpl_adea41968873302399c279efce2c46dbd56e4f48.zig:306)
	at org.acme.spring.data.rest.BookRepositoryResourceImpl_adea41968873302399c279efce2c46dbd56e4f48_ClientProxy.add(BookRepositoryResourceImpl_adea41968873302399c279efce2c46dbd56e4f48_ClientProxy.zig:188)
	at org.acme.spring.data.rest.BookRepositoryJaxRs_adea41968873302399c279efce2c46dbd56e4f48.addHal(BookRepositoryJaxRs_adea41968873302399c279efce2c46dbd56e4f48.zig:1337)
	... 29 more
```

**Comment by gsmet** [comment]
Btw @Sgitario and @rsvoboda , could we run the beefy-scenarios tests as part of the ecosystem CI? Are the tests run automatically or you need manual intervention?

**Comment by geoand** [comment]
> Are the tests run automatically or you need manual intervention?

We would definitely benefit from this

**Comment by rsvoboda** [comment]
We have daily runs against Quarkus master.
Defined in https://github.com/quarkus-qe/beefy-scenarios/blob/master/.github/workflows/daily.yaml

**Comment by geoand** [comment]
Can you add this to ecosystem-ci? See the README from https://github.com/quarkusio/quarkus-ecosystem-ci for instructions

**Comment by rsvoboda** [comment]
We can prepare https://github.com/quarkusio/quarkus-ecosystem-ci integration.
This way you will get GH notifications directly?

**Comment by geoand** [comment]
Exactly!

**Comment by rsvoboda** [comment]
@Sgitario will be looking into the integration

**Comment by geoand** [comment]
Great, thanks

**Comment by gytis** [comment]
I get HTTP 500 error both in JVM and native executions. The difference I see is the response body being returned, where native mode doesn't include the stack.
In any case I'm going to raise a PR for https://github.com/quarkusio/quarkus/issues/13307 which will map all the validation errors to an HTTP 400 error. So that should take care of this issue too.

**Comment by Sgitario** [comment]
Now, Spring REST Data works similarly as in Panache REST. Now, services return 400 when there are violations. Fixed as part of https://github.com/quarkusio/quarkus/pull/15447.

However, when there is a violation, no message is returned. Reported in https://github.com/quarkusio/quarkus/issues/15492.
