### ISSUE TITLE
Deploying on OpenShift leads to a Quay error for the first deployment

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#15415]
Nearly every time I deploy my Quarkus application to an OpenShift cluster using the OpenShift extension, I get the following error on the OpenShift side for my first attempt:
```
Receiving source from STDIN as archive ...
Pulling image "quay.io/quarkus/ubi-quarkus-native-binary-s2i@sha256:d9a59f5d84de0d01a10aa77a0f3ef03533e2651a496854bfbaf86797d7694577" ...
pulling image error : manifest for quay.io/quarkus/ubi-quarkus-native-binary-s2i@sha256:d9a59f5d84de0d01a10aa77a0f3ef03533e2651a496854bfbaf86797d7694577 not found
error: build error: unable to get quay.io/quarkus/ubi-quarkus-native-binary-s2i@sha256:d9a59f5d84de0d01a10aa77a0f3ef03533e2651a496854bfbaf86797d7694577
```

The second attempt succeeds with:
```
Receiving source from STDIN as archive ...
Pulling image "quay.io/quarkus/ubi-quarkus-native-binary-s2i@sha256:2d00427fc97d217a279e54d610c2e35da5a2c1ec9c410dce41e5203f35a05281" ...
Using quay.io/quarkus/ubi-quarkus-native-binary-s2i@sha256:2d00427fc97d217a279e54d610c2e35da5a2c1ec9c410dce41e5203f35a05281 as the s2i builder image
```

As you can see, the hash is not the same. As the Quarkus images are rebuilt often, and I don't deploy that often, maybe that could explain things.

I deploy my application with:
```
mvn clean package -Dquarkus.kubernetes.deploy=true -Dquarkus.native.container-build=true -Dnative
```
and I use the `quarkus-openshift` extension.

@iocanel this is the issue we discussed on Zulip the other day. You wanted a GH issue, here we go :).

**Comment by iocanel** [comment]
> @iocanel this is the issue we discussed on Zulip the other day. You wanted a GH issue, here we go :).
Mercy Monsieur!

**Comment by maxandersen** [comment]
@gsmet what version of OpenShift are you doing this on ?

**Comment by gsmet** [comment]
So this was the old error with OpenShift 3. The problem with 4 is slightly different: it complains about manifest.

Unfortunately, for my last deployment, I didn't get the error in the console (dunno why) and the build pod in OpenShift is gone. I'll take note of the error next Sunday.

**Comment by maxandersen** [comment]
gotcha - just to check you are using quarkus mvn command to do the deploy,right ?

i have a hunch what could be causing it. let me check.

**Comment by maxandersen** [comment]
okey so just for my own sanity to keep track of what happens:

```
git clone https://github.com/quarkusio/status.quarkus.io
mvn clean package -Dquarkus.native.container-build=true -Dnative
```

will generate a `target/kubernets/openshift.yml` that refer to https://quay.io/repository/quarkus/ubi-quarkus-native-binary-s2i?tab=tags using 

```
strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi-quarkus-native-binary-s2i:1.0
```

which definitely gets bumped every week.


i'm a bit confused why that gives an error since the image stream policy should be be `IfNotPresent` by default meaning it should just stay on the old unless one explicitly updates.

**Comment by maxandersen** [comment]
its as if openshift does actually use the cached sha but then remotely fetches the manifest which of course wont exist anymore ...kinda beating the whole purpose of imagestreams. 

I must be missing something here.

**Comment by gsmet** [comment]
Yes I use the OpenShift extension and a simple `mvn clean package -Dquarkus.kubernetes.deploy=true -Dquarkus.native.container-build=true -Dnative`.

You might be on the right path as IIRC the message complains about the manifest not being found.

In this very case, I think we would want to upgrade to the latest version as we are using floating tags to push security fixes.

**Comment by maxandersen** [comment]
I wonder if a "fix" is to do as documented in https://docs.openshift.com/container-platform/4.7/openshift_images/image-streams-manage.html#images-imagestreams-update-tag_image-streams-managing


```
oc tag quay.io/quarkus/ubi-quarkus-native-binary-s2i:1.0 ubi-quarkus-native-binary-s2i
```

to force an update or even have it scheduled:

```
oc tag quay.io/quarkus/ubi-quarkus-native-binary-s2i:1.0 ubi-quarkus-native-binary-s2i --scheduled
```

note: these are workarounds to the problem and I don't grok why there is a pull of images that the cluster already knows...that should not happen.

**Comment by maxandersen** [comment]
> You might be on the right path as IIRC the message complains about the manifest not being found.

yes, but if you used the same cluster to push previously why is it fetching manifest to check...it will quite often fail on a floating tag...so there is either some bug in how openshift does this or we configured it wrong :)

**Comment by maxandersen** [comment]
long shot: could there be a policy on the cluster pruning the images somehow ? causing the cache to be partially fullfilled -i.e. sha1 is there but image gone, so it tries pulling the manifest using the sha rather than the tag?

**Comment by gsmet** [comment]
@maxandersen so I can confirm I get the error every time the image is refreshed.

Here is the error I get:
```
Caching blobs under "/var/cache/blobs".
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
error: build error: After retrying 2 times, Pull image still failed due to error: while pulling "docker://quay.io/quarkus/ubi-quarkus-native-binary-s2i@sha256:f89fdf909b7378c1a69802a8b15539ee71da517b79918b21cac71085754a0c63" as "quay.io/quarkus/ubi-quarkus-native-binary-s2i@sha256:f89fdf909b7378c1a69802a8b15539ee71da517b79918b21cac71085754a0c63": Error initializing source docker://quay.io/quarkus/ubi-quarkus-native-binary-s2i@sha256:f89fdf909b7378c1a69802a8b15539ee71da517b79918b21cac71085754a0c63: Error reading manifest sha256:f89fdf909b7378c1a69802a8b15539ee71da517b79918b21cac71085754a0c63 in quay.io/quarkus/ubi-quarkus-native-binary-s2i: manifest unknown: manifest unknown
```

BTW @iocanel , I used to have the error in the terminal and now I have to go to the OpenShift console to get the error.

I get this in the terminal:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.2.Final:build (default) on project quarkus-bot: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.openshift.deployment.OpenshiftProcessor#openshiftBuildFromNative threw an exception: java.lang.IllegalStateException: Build:quarkus-bot-1 failed! Generic Build failure - check logs for details.
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuild(OpenshiftProcessor.java:465)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.lambda$openshiftBuild$10(OpenshiftProcessor.java:410)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[ERROR] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuild(OpenshiftProcessor.java:410)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.createContainerImage(OpenshiftProcessor.java:352)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuildFromNative(OpenshiftProcessor.java:317)
```

**Comment by geoand** [comment]
Is this still an issue or can we close it?

**Comment by maxandersen** [comment]
i haven't verified it is gone - last i checked it still happened but been a while ;/

**Comment by geoand** [comment]
@iocanel one of your latest fixes should take care of this, right?

**Comment by iocanel** [comment]
> @iocanel one of your latest fixes should take care of this, right?

Not intentionally no!

**Comment by geoand** [comment]
Okay then, let's leave it open

**Comment by geoand** [comment]
Is this still an issue with Quarkus 3.8?
