### ISSUE TITLE
Mongo: Class Not Found jnr.unixsocket.UnixSocket when running in Native

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15434]
**Describe the bug**
We have a project that uses a lot of Quarkus extensions at the same time. One of these extensions is Mongo Panache and seems to be an incompatibility because when compiling the project in JVM, it works, but not in Native with the following error:

```
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:24]    classlist:  45.993,33 ms,  1,96 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:24]        setup:   3.249,06 ms,  1,96 GB
Fatal error:java.lang.NoClassDefFoundError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)
Caused by: java.lang.NoClassDefFoundError: jnr/unixsocket/UnixSocket
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleDeletedClass(AnnotationSubstitutionProcessor.java:512)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:305)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:265)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:929)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:863)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: jnr.unixsocket.UnixSocket
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 16 more

```

Note that when using only Mongo Panache, it works fine. I could not identify what other extension is causing Mongo to fail with this missing class.

**Expected behavior**
The project should work fine regardless the number of Quarkus extensions we're using.

**Actual behavior**
It fails to compile, see exception above.

**To Reproduce**
1- git clone https://github.com/Sgitario/beefy-scenarios
2- git checkout reproducer_15434
3- cd beefy-scenarios/002-quarkus-all-extensions
4- mvn clean verify -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:21.0.0-java11 -Dnative -Dquarkus.native.container-build=true (it needs to have built quarkus master locally)

Environment (please complete the following information):
- Quarkus version or git rev: 999-SNAPSHOT (1.12.1.Final)

**Comment by loicmathieu** [comment]
It's very difficult to try to understand what's going on as the provided stacktrace didn'g give any stack inside Quarkus nor MongoDB.

Can you try to locate which extension have the `com.github:jnr-unixsocket` dependency ?

Can you also try to remove the `quarkus-mongodb-panache` extension and only include `quarkus-mongodb-client` ? I suspect the issue is from the MongoDB client extension as it is the one that provides native image support.

Lastly, you can try to add the missing class and see if it fixes the issue, if yes, we can add it from the MongoDB client extension.

You can use an empty class annotated with  `@RegisterForReflection(targets={jnr.unixsocket.UnixSocket.class}) this would do the trick.

**Comment by Sgitario** [comment]
> It's very difficult to try to understand what's going on as the provided stacktrace didn'g give any stack inside Quarkus nor MongoDB.
> 
> Can you try to locate which extension have the `com.github:jnr-unixsocket` dependency ?
> 
> Can you also try to remove the `quarkus-mongodb-panache` extension and only include `quarkus-mongodb-client` ? I suspect the issue is from the MongoDB client extension as it is the one that provides native image support.
> 
> Lastly, you can try to add the missing class and see if it fixes the issue, if yes, we can add it from the MongoDB client extension.
> 
> You can use an empty class annotated with `@RegisterForReflection(targets={jnr.unixsocket.UnixSocket.class}) this would do the trick.

- No extensions bring the `com.github:jnr-unixsocket` dependency
- I confirm it happens even when only including `quarkus-mongodb-client `
- Adding the dependency `com.github:jnr-unixsocket` helped.

I didn't try your last suggestions, but if I understood correctly, are you going then add this dependency as part of the MongoDB client extension as a fix?

**Comment by loicmathieu** [comment]
This library is used only in the `io.quarkus:quarkus-extension-processor` dependency as a transitive dependency on the asccidoctorj test dependency.

I have no idea why it causes a native build issue, but this has something to do with the Quarkus extension processor.

**Comment by loicmathieu** [comment]
@aloubyansky the Quarkus extension processor have a transitive test dependency on `com.github:jnr-unixsocket` and under some circumstances it causes issue on native build.
Do you have any idea how it is possible that this extension ends somewhere on the classpath during a native build?

**Comment by aloubyansky** [comment]
It appears it's not a new issue. See https://github.com/oracle/graal/issues/1239
The dependency comes from the monodb itself. If you look into https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-core/4.0.1/mongodb-driver-core-4.0.1.pom you'll see

````
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jnr-unixsocket</artifactId>
      <version>0.18</version>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>
````

And if you look into `com.mongodb.internal.connection.UnixSocketChannelStream` which is referenced from `io.quarkus.mongodb.runtime.graal.MongoClientSubstitutions`, you'll see

````
import jnr.unixsocket.UnixSocketAddress;
import jnr.unixsocket.UnixSocketChannel;
````

**Comment by aloubyansky** [comment]
It looks like `--allow-incomplete-class-path` should help as well.

**Comment by Sgitario** [comment]
> --allow-incomplete-class-path

So, are you suggesting that we should use `--allow-incomplete-class-path` as a workaround or that the jnr dependency should be part of Mongo Client?

**Comment by loicmathieu** [comment]
@Sgitario as a workaround you can include the jnr library or add the `--allow-incomplete-class-path` flag to native.

I will work on a substitution to fix the issue, I don't want to always include this dependency.

**Comment by loicmathieu** [comment]
Trying to build the native application locally I have the following stacktrace:
```
Fatal error:java.lang.NoClassDefFoundError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)
Caused by: java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/WinNT$HANDLE
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleDeletedClass(AnnotationSubstitutionProcessor.java:512)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:305)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:265)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:929)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:863)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.WinNT$HANDLE
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 16 more
```

**Comment by Sgitario** [comment]
> Trying to build the native application locally I have the following stacktrace:
> 
> ```
> Fatal error:java.lang.NoClassDefFoundError
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
> 	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
> 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
> 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
> 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
> 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
> 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)
> Caused by: java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/WinNT$HANDLE
> 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
> 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
> 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
> 	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleDeletedClass(AnnotationSubstitutionProcessor.java:512)
> 	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:305)
> 	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:265)
> 	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:929)
> 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:863)
> 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
> 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
> 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.WinNT$HANDLE
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 16 more
> ```

I also faced the same exception and realised that there is an existing issue for this:  https://github.com/quarkusio/quarkus/issues/6327

**Comment by loicmathieu** [comment]
@aloubyansky the class `com.mongodb.internal.connection.UnixSocketChannelStream`is deleted from the MongoDB extension so we should not have any occurence of JNR classes detected by native image.

```
@TargetClass(UnixSocketChannelStream.class)
@Delete
final class UnixSocketChannelStreamSubstitution {

}
```

Something else happens ...
Maybe it's an extension dependency issue, we should check with the PR that fix some extension dependency issue, maybe it's resolved there. WDYT @aloubyansky ?
If this PR is merged, we can test with the snapshot version.

**Comment by aloubyansky** [comment]
Which PR are you talking about @loicmathieu ?

**Comment by loicmathieu** [comment]
This one: https://github.com/quarkusio/quarkus/pull/14609
If it could help, I can try to build it locally and use it. The issue reproducer uses the snapshot version of Quarkus so it's easy to setup.

**Comment by aloubyansky** [comment]
It doesn't look like it's affecting the mongodb client extension though.

**Comment by loicmathieu** [comment]
No but the issue is not with the mongodb client extension alone but when it is integrated with other extensions

**Comment by aloubyansky** [comment]
Are you saying not every Quarkus application with the mongodb client extension will fail in this way?

**Comment by loicmathieu** [comment]
No, in fact it's the only one I'm aware of, and this particular one is using almost all exiting Quarkus applicaiton. So the issue may only occurs when some other extension is used with Quarkus.

**Comment by aloubyansky** [comment]
Oh, it's that tricky...

**Comment by aloubyansky** [comment]
> I confirm it happens even when only including quarkus-mongodb-client

I read it as the mongodb-client was the only extension included

**Comment by loicmathieu** [comment]
> I read it as the mongodb-client was the only extension included

Oh no, the context was that both mongodb-client and mongodb-panache was included so I ask to test with only the client to see if it only occurs with it.

**Comment by aloubyansky** [comment]
I was trying to build it with my locally installed GraalVM and got a different error
````
Error: Classes that should be initialized at run time got initialized during image building:
 com.arjuna.ats.internal.arjuna.utils.SocketProcessId the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). com.arjuna.ats.internal.arjuna.utils.SocketProcessId has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of com.arjuna.ats.internal.arjuna.utils.SocketProcessId
````
Is that a known one?

**Comment by aloubyansky** [comment]
Could you please try adding `--trace-class-initialization=jnr.unixsocket.UnixSocket` and see whether there is more info, because I keep getting a different error.

**Comment by loicmathieu** [comment]
@aloubyansky try it, no more info.

**Comment by zakkak** [comment]
This looks like the same issue with https://github.com/quarkusio/quarkus/issues/16139
Please see https://github.com/quarkusio/quarkus/issues/16139#issuecomment-812252577 for the culprit.

**Comment by loicmathieu** [comment]
@Sgitario can you check if removing the AWS extensions resolves the issue ?
If yes, it's the same one as #16139, the issue is upstream on the AWS SDK

**Comment by Sgitario** [comment]
> @Sgitario can you check if removing the AWS extensions resolves the issue ?
> If yes, it's the same one as #16139, the issue is upstream on the AWS SDK

Yep, removing all the AWS extensions fixes this issue. However, I think this issue should remain opened and once the another issue related to AWS is solved, I can try again with Mongo.

**Comment by loicmathieu** [comment]
@Sgitario apparently the fix on AWS SDK has been integrated in Quarkus 1.13.5.Final.
Can you try again and close the issue if it fixes it ?

**Comment by Sgitario** [comment]
I've confirmed that this is indeed fixed. Thanks a lot!
