### ISSUE TITLE
OIDC Client stopped working and fails with 500 Internal Server

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15440]
**Describe the bug**
Having this configuration:

```
# Security
quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/test-realm
quarkus.oidc.client-id=test-application-client
quarkus.oidc.credentials.secret=test-application-client-secret
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
org.eclipse.microprofile.rest.client.propagateHeaders=Authorization

# OIDC Client Configuration
quarkus.oidc-client.auth-server-url=http://localhost:8180/auth/realms/test-realm
quarkus.oidc-client.client-id=test-application-client
quarkus.oidc-client.credentials.secret=test-application-client-secret
```

And this REALM configuration for Keycloak:

```
"clients": [
    {
      "clientId": "test-application-client",
      "enabled": true,
      "protocol": "openid-connect",
      "standardFlowEnabled": true,
      "implicitFlowEnabled": false,
      "directAccessGrantsEnabled": true,
      "serviceAccountsEnabled": true,
      "clientAuthenticatorType": "client-secret",
      "secret": "test-application-client-secret",
      "redirectUris": [
        "*"
      ]
    }
```

When running our application, it fails with the next exception:

```
2021-03-03 15:34:06,728 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-14) HTTP Request to /rest-pong failed, error id: b24d56d4-cfff-46e3-95e2-b9739e981896-5: io.vertx.core.VertxException: Invalid url: null
	at io.vertx.ext.web.client.impl.WebClientBase.requestAbs(WebClientBase.java:256)
	at io.vertx.ext.web.client.impl.WebClientBase.requestAbs(WebClientBase.java:246)
	at io.vertx.ext.web.client.impl.WebClientBase.postAbs(WebClientBase.java:176)
	at io.vertx.mutiny.ext.web.client.WebClient.postAbs(WebClient.java:334)
	at io.quarkus.oidc.runtime.OidcProviderClient.getHttpResponse(OidcProviderClient.java:95)
	at io.quarkus.oidc.runtime.OidcProviderClient.introspectToken(OidcProviderClient.java:63)
	at io.quarkus.oidc.runtime.OidcProvider.introspectToken(OidcProvider.java:115)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.introspectTokenUni(OidcIdentityProvider.java:275)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.verifyTokenUni(OidcIdentityProvider.java:251)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.createSecurityIdentityWithOidcServer(OidcIdentityProvider.java:122)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.access$200(OidcIdentityProvider.java:34)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$3.apply(OidcIdentityProvider.java:115)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$3.apply(OidcIdentityProvider.java:109)
```

Our project was working fine before these changes were merged: https://github.com/quarkusio/quarkus/pull/14953. So, this is a regression issue.

**To Reproduce**
1- git clone https://github.com/quarkus-qe/beefy-scenarios
2- cd beefy-scenarios/013-quarkus-oidc-restclient
4- mvn clean install (it needs to have built quarkus master locally)

**Environment (please complete the following information):**
 - Quarkus version or git rev: 999-SNAPSHOT

**Comment by sberyozkin** [comment]
@Sgitario thanks Jose, glad you've spotted a single test failing only :-), going to have a look asap

**Comment by sberyozkin** [comment]
@Sgitario I have a fix, so `integration-tests/oidc-wiremock` uses a legacy `token_introspection_endpoint` discovery property - but `introspection_endpoint` is the one used by latest KCs...

**Comment by sberyozkin** [comment]
We have invalid `JWT` tokens tests but in your test it is an opaque token :-), so it does try an introspection endpoint - we also have the introspection tests - but since KC only uses JWT I used a non-discovery option to set the introspection path :-).
I'll add one more invalid token test which would stress a live KC intropspection endpoint with an opaque token
