### ISSUE TITLE
Narayana STM failing to build in Native

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15442]
**Describe the bug**
When building a Quarkus application with the Narayana STM and also using any other extension that also brings the narayana JTA extension (hibernate orm, agroal, etc), the build fails in Native with:

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /home/jcarvaja/Downloads/tmp/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 1000:1000 --rm quay.io/quarkus/ubi-quarkus-native-image:21.0.0-java11 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Duser.language=es -J-Duser.country=ES -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar code-with-quarkus-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -J-Xmx4g -H:-AddAllCharsets -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace code-with-quarkus-1.0.0-SNAPSHOT-runner
[code-with-quarkus-1.0.0-SNAPSHOT-runner:24]    classlist:   4.198,77 ms,  1,19 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:24]        (cap):     815,95 ms,  1,19 GB
[code-with-quarkus-1.0.0-SNAPSHOT-runner:24]        setup:   2.879,19 ms,  1,19 GB
15:13:59,636 INFO  [org.jbo.threads] JBoss Threads version 3.2.0.Final
To see how the classes got initialized, use --trace-class-initialization=com.arjuna.ats.internal.arjuna.utils.SocketProcessId
[code-with-quarkus-1.0.0-SNAPSHOT-runner:24]     analysis:  37.311,65 ms,  1,87 GB
Error: Classes that should be initialized at run time got initialized during image building:
 com.arjuna.ats.internal.arjuna.utils.SocketProcessId the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why com.arjuna.ats.internal.arjuna.utils.SocketProcessId got initialized use --trace-class-initialization=com.arjuna.ats.internal.arjuna.utils.SocketProcessId

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 com.arjuna.ats.internal.arjuna.utils.SocketProcessId the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why com.arjuna.ats.internal.arjuna.utils.SocketProcessId got initialized use --trace-class-initialization=com.arjuna.ats.internal.arjuna.utils.SocketProcessId

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:539)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:226)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:740)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:740)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

**Expected behavior**
It should work as in JVM.

**Actual behavior**
It fails when building, see exception above.

**To Reproduce**
1. Go to code.quarkus.io
2. Select Narayana STM extension and Agroal (or directly Narayana JTA)
3. Download the ZIP and try to build the application using:

```
 mvn clean install -Dnative -Dquarkus.native.container-build=true 
```

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.12.0.Final and 999-SNAPSHOT

**Comment by famod** [comment]
@Sgitario Have you tried getting more info via `--trace-class-initialization=com.arjuna.ats.internal.arjuna.utils.SocketProcessId`?

**Comment by gsmet** [comment]
I can't reproduce this. By any chance did you also select the narayana-jta extension (or something that brings it)?

**Comment by Sgitario** [comment]
@famod running with `--trace-class-initialization` was not very helpful:

```
Error: Classes that should be initialized at run time got initialized during image building:
 com.arjuna.ats.internal.arjuna.utils.SocketProcessId the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). com.arjuna.ats.internal.arjuna.utils.SocketProcessId has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of com.arjuna.ats.internal.arjuna.utils.SocketProcessId

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 com.arjuna.ats.internal.arjuna.utils.SocketProcessId the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). com.arjuna.ats.internal.arjuna.utils.SocketProcessId has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of com.arjuna.ats.internal.arjuna.utils.SocketProcessId
 ```

**Comment by Sgitario** [comment]
@gsmet you are right, the problem is that we're using another extension that also brings Narayana JTA. When having narayana JTA in the classpath, Narayana STM fails to build in Native. I've already updated the issue description. Thanks!

**Comment by mmusgrov** [comment]
@famod FYI Mayank Kunwar is working on this issue (and I don't have permissions to make him the assignee).

**Comment by famod** [comment]
@mmusgrov alright, if you tell me his GH name I can assign this issue to him.

**Comment by mayankkunwar** [comment]
Hi @famod I have raised a PR as fix for this issue.
