### ISSUE TITLE
RESTEasy Reactive: ReaderInterceptor results in java.lang.IllegalStateException: Should never be called

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#15453]
Describe the bug
Using a reader interceptor for a JSON content type results in java.lang.IllegalStateException: Should never be called

Expected behavior
No error should occur

Actual behavior
a 500 is returned:
java.lang.IllegalStateException: Should never be called
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.JacksonMessageBodyReader.readFrom(JacksonMessageBodyReader.java:34)
	at org.jboss.resteasy.reactive.server.jaxrs.ReaderInterceptorContextImpl.proceed(ReaderInterceptorContextImpl.java:50)
	at reactive.scenarios.MyFilter.aroundReadFrom(MyFilter.java:26)
	at org.jboss.resteasy.reactive.server.jaxrs.ReaderInterceptorContextImpl.proceed(ReaderInterceptorContextImpl.java:52)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:74)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:25)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:117)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)

To Reproduce
git clone https://github.com/bcluap/quarkus-examples.git
cd quarkus-examples/resteasy-reactive
mvn clean test

Configuration
Nothing abnormal

Screenshots
Run the reproducer to see failures. Change the pom to non-reactive mode or 1.11.3.Final and all tests pass

Environment (please complete the following information):
This used to work on 1.11.X but fails from 1.12.X

**Comment by geoand** [comment]
Ah darn... This is a dump mistake that should be easy to fix.

Sorry for the inconvinience :(

**Comment by bcluap** [comment]
Yea, I saw the change ;-)

I get really unlucky. Each new release that comes out and I run our
platform tests and pick something new up. I sense we getting to the end and
soon will be able to go reactive :-)

**Comment by geoand** [comment]
You should just give us the application 😆

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/15455 takes care of the issue properly
