### ISSUE TITLE
JDBC Form based auth: changing user email while logged in causes a java.lang.NullPointerException   at io.quarkus.vertx.http.runtime.security.PersistentLoginManager.save(PersistentLoginManager.java:118)

### ISSUE THREAD

**Issue by obbyK** [quarkusio/quarkus#15465]
When a user is already logged in and updates their email which is used as the `username` for the form based auth, there is a redirect to sign in page. But when using the new email to log in, it cause the above error. After which accessing any page causes the same error. This is using `quarkus-elytron-security-jdbc`.

stacktrace 
```
 (executor-thread-2) HTTP Request to /signin.html failed, error id: e8a8c247-7d82-4676-b57e-a70107507f5f-3: java.lang.RuntimeException: java.lang.NullPointerException
        at io.quarkus.vertx.http.runtime.security.PersistentLoginManager.save(PersistentLoginManager.java:127)
        at io.quarkus.vertx.http.runtime.security.FormAuthenticationMechanism$2.accept(FormAuthenticationMechanism.java:166)
        at io.quarkus.vertx.http.runtime.security.FormAuthenticationMechanism$2.accept(FormAuthenticationMechanism.java:163)
        at io.smallrye.mutiny.operators.UniOnItemConsume.invokeEventHandler(UniOnItemConsume.java:62)
        at io.smallrye.mutiny.operators.UniOnItemConsume.access$100(UniOnItemConsume.java:10)
        at io.smallrye.mutiny.operators.UniOnItemConsume$1.onItem(UniOnItemConsume.java:30)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:31)
        at io.smallrye.context.impl.wrappers.SlowContextualExecutor.execute(SlowContextualExecutor.java:19)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:31)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:85)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:31)
        at io.smallrye.context.impl.wrappers.SlowContextualExecutor.execute(SlowContextualExecutor.java:19)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:31)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:31)
        at io.smallrye.context.impl.wrappers.SlowContextualExecutor.execute(SlowContextualExecutor.java:19)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:31)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:85)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:31)
        at io.smallrye.context.impl.wrappers.SlowContextualExecutor.execute(SlowContextualExecutor.java:19)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:31)
        at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
        at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl$1$1$1$1.run(QuarkusIdentityProviderManagerImpl.java:58)
        at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.NullPointerException
        at io.quarkus.vertx.http.runtime.security.PersistentLoginManager.save(PersistentLoginManager.java:118)
        ... 30 more
```

**Comment by obbyK** [comment]
It seems that if there is any change to the auth table in db like changing email or deleting a user, this error will occur

**Comment by obbyK** [comment]
If the table with credentials is empty, it also throws this exception.

**Comment by obbyK** [comment]
Maybe this is the expected behaviour? I would assume that a web application whose authentication/authorization module is not present should return a 500 http error to the browser. But perhaps a better way would be to allow for a custom error page for such a case and also provide the cause of the problem to the developer in logs. Null Pointer exception is vague

**Comment by michalvavrik** [comment]
Hey @obbyK ,

I'm happy to look at it, but please provide reproducer.

Thanks,

Michal

**Comment by michalvavrik** [comment]
Closing as we never got reproducer.
