### ISSUE TITLE
Camel Quarkus DSL - Azure Storage Blob Service doesn't work in native runtime.

### ISSUE THREAD

**Issue by tidemyr** [quarkusio/quarkus#15466]
**Describe the bug**
We intend to use Quarkus Camel for some integration patterns. One of these needs is to be able to upload files to Azure
from different types of incoming endpoints. In this specific microservice by moving files from an SFTP-server to Azure. 
The code is limited to include only Quarkus supported methods for native builds and of course, runs perfectly when using normal Java. But as native build there is a runtime error during the Azure upload, the SFPT and the mail-relay sending are working in both native and normal Java. 

**Expected behavior**
This limited code working exactly the same way running as a native build as when running normal Java.
Code can be limited to just the Azure upload part to recreate the problem.

**Actual behavior**
Got runtime error (see additional context below)

**To Reproduce**
Code can be limited to just upload a local file to Azure using the Camel DSL documentation example for uploads to recreate the problem.

**Configuration**
Mainly properties for servers, users and passwords secrets for connections.
Quarkus specific properties (yaml):
```properties
quarkus:

  swagger-ui:
    always-include: true
    theme: original

  jaeger:
    service-name: someApplication
    sampler-type: const
    sampler-param: 1
    endpoint: http://localhost:14268/api/traces

  ssl:
    native: true
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 11.0.8.j9-adpt
 - GraalVM version (if different from Java): 20.2.0
 - Quarkus version or git rev: 1.11.1.Final Camel Quarkus: 1.6.0
 - Maven: 3.6.3

**Additional context**
Camel DSL code:
    @Override
    public void configure() throws Exception {

        StorageSharedKeyCredential credential = new StorageSharedKeyCredential(azureAccountName, azureAccessKey);
        String uri = String.format("https://%s.blob.core.windows.net", azureAccountName);
        BlobServiceClient client = new BlobServiceClientBuilder()
                .endpoint(uri)
                .credential(credential)
                .buildClient();

        getContext().getRegistry().bind("client", client);

        from(String.format("sftp:%s/%s?binary=true&username=%s&password=%s&connectTimeout=3000&readLock=changed&readLockMinAge=300s&delete=true&timeout=3000",
                sftpServer,
                sftpPath,
                sftpUsername,
                sftpPassword
             ))
            .routeId("sftpToAzure")
            .errorHandler(deadLetterChannel("seda:error"))
            .convertBodyTo(byte[].class)
            .log(LoggingLevel.INFO, "File ${file:name} (${file:size} bytes) is fetched from SFTP.")
            .process(setHeaders) // sets the azure filename header
            .to(String.format("azure-storage-blob://%s/%s?blobName=blob&operation=uploadBlockBlob&serviceClient=#client",
                azureAccountName,
                azureContainer
             ))
            .log(LoggingLevel.INFO, "Uploaded to Azure.");

        from("seda:error")
            .routeId("error")
            .log(LoggingLevel.ERROR, exceptionMessage().toString())
            .doTry()
            .setHeader("from", simple(mailFrom))
            .setHeader("to", simple(mailTo))
            .setHeader("subject", simple("ERROR - " + appName + " in " + appProfile.toUpperCase()))
            .setBody(exceptionMessage())
            .to(String.format("smtp://%s:%s?username=%s&password=%s",
                mailServer,
                mailPort,
                mailUsername,
                mailPassword
             ));
    }

pom.xml extract:
    <properties>
        <compiler-plugin.version>3.8.1</compiler-plugin.version>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus-plugin.version>1.11.1.Final</quarkus-plugin.version>
        <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
        <quarkus.platform.version>1.11.1.Final</quarkus.platform.version>
        <camel-quarkus.version>1.6.0</camel-quarkus.version>
        <surefire-plugin.version>2.22.1</surefire-plugin.version>
        <docker-maven-plugin.version>0.33.0</docker-maven-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.camel.quarkus</groupId>
                <artifactId>camel-quarkus-bom</artifactId>
                <version>${camel-quarkus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-azure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-azure-storage-blob</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-seda</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-file</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-ftp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-log</artifactId>
        </dependency>
        ...

Runtime error as native build:
2021-03-03 15:50:13,283 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.7.0 (camel-1) started in 304ms
2021-03-03 15:50:13,285 INFO  [io.quarkus] (main) srv0210-someApplication 1.0.1-SNAPSHOT native (powered by Quarkus 1.11.0.Final) started in 4.075s. Listening on: http:/
/0.0.0.0:8080
2021-03-03 15:50:13,286 INFO  [io.quarkus] (main) Profile test activated.
2021-03-03 15:50:13,287 INFO  [io.quarkus] (main) Installed features: [camel-azure, camel-azure-storage-blob, camel-core, camel-file, camel-ftp, camel-log, camel-mail, camel-s
eda, camel-support-common, camel-support-mail, cdi, config-yaml, jaeger, micrometer, smallrye-health, smallrye-openapi, smallrye-opentracing, swagger-ui]
2021-03-03 15:56:01,244 INFO  [sftpToAzure] (Camel (camel-1) thread #0 - sftp://someServer/../../Integrations/someDirectory) F
ile 20210111150626x.csv (5380 bytes) is fetched from SFTP.
2021-03-03 15:56:01,247 ERROR [rea.cor.sch.Schedulers] (parallel-1) Scheduler worker in group main failed with an uncaught exception: java.lang.UnsatisfiedLinkError: io.netty.
internal.tcnative.NativeStaticallyReferencedJniMethods.sslOpCipherServerPreference()I [symbol: Java_io_netty_internal_tcnative_NativeStaticallyReferencedJniMethods_sslOpCipher
ServerPreference or Java_io_netty_internal_tcnative_NativeStaticallyReferencedJniMethods_sslOpCipherServerPreference__]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at io.netty.internal.tcnative.NativeStaticallyReferencedJniMethods.sslOpCipherServerPreference(NativeStaticallyReferencedJniMethods.java)
        at io.netty.internal.tcnative.SSL.<clinit>(SSL.java:67)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:121)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
        at reactor.netty.tcp.SslProvider.updateDefaultConfiguration(SslProvider.java:388)
        at reactor.netty.tcp.SslProvider.<init>(SslProvider.java:309)
        at reactor.netty.tcp.SslProvider$Build.build(SslProvider.java:569)
        at reactor.netty.tcp.TcpClientSecure.<clinit>(TcpClientSecure.java:71)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
        at reactor.netty.tcp.SslProvider.defaultClientProvider(SslProvider.java:100)
        at reactor.netty.http.client.HttpClientSecure.<clinit>(HttpClientSecure.java:72)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:305)
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:79)
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:330)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:52)
        at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:33)
        at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:123)
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

**Comment by jamesnetherton** [comment]
There are some known issues with the Azure components in Camel Quarkus 1.7.0, but I see you're using 1.6.0.

Is it intentional to include both `camel-quarkus-azure` & `camel-quarkus-azure-storage-blob`?  `camel-quarkus-azure` is deprecated (and will be removed in Camel 3.9.0) and is aimed at the old Azure APIs.

**Comment by tidemyr** [comment]
Have also tested with Camel 1.7.0 and Quarkus 1.12.0.Final, got runtime error also there, however another one complained about the date format in the header. Tried to set x-ms-date but does not seem to solve the problem. camel-quarkus-azure is not necessary, it's only included as a dependent test. Wasn't included in the beginning.

**Comment by tidemyr** [comment]
**Runtime error using Quarkus 1.12.0.Final and Camel 1.7.0**

`__ ____ __ _____ ___ __ ____ ______
--/ __ \/ / / / _ | / _ \/ //_/ / / / __/
-/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/

2021-03-04 13:56:42,014 INFO [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.core.CamelContextRuntime

2021-03-04 13:56:42,015 INFO [org.apa.cam.com.azu.sto.blo.BlobComponent] (main) BlobServiceClient instance is already set at endpoint level: skipping the check in the registry

2021-03-04 13:56:42,016 INFO [org.apa.cam.com.sed.SedaEndpoint] (main) Endpoint seda://error is using shared queue: seda://error with size: 1000

2021-03-04 13:56:42,018 INFO [org.apa.cam.com.fil.rem.SftpOperations] (main) Known host file not configured, using user known host file: ?/.ssh/known_hosts

2021-03-04 13:56:42,199 WARN [org.apa.cam.com.fil.rem.SftpOperations] (main) JSCH -> Permanently added 'someSftpHost' (RSA) to the list of known hosts.

2021-03-04 13:56:42,199 WARN [org.apa.cam.com.fil.rem.SftpOperations] (main) Server asks for confirmation (yes|no): ?/.ssh/known_hosts does not exist.

Are you sure you want to create it?. Camel will answer no.

2021-03-04 13:56:42,730 INFO [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:2 started:2)

2021-03-04 13:56:42,730 INFO [org.apa.cam.imp.eng.AbstractCamelContext] (main) Started sftpToAzure (sftp://someSftpHost/../../Integrations/someDirectory)

2021-03-04 13:56:42,730 INFO [org.apa.cam.imp.eng.AbstractCamelContext] (main) Started error (seda://error)

2021-03-04 13:56:42,730 INFO [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.8.0 (camel-1) started in 716ms (build:0ms init:2ms start:714ms)

2021-03-04 13:56:42,740 INFO [io.quarkus] (main) srv0210-someApplication 1.0.1-SNAPSHOT native (powered by Quarkus 1.12.0.Final) started in 0.753s. Listening on: http://0.0.0.0:8080

2021-03-04 13:56:42,740 INFO [io.quarkus] (main) Profile prod activated.

2021-03-04 13:56:42,740 INFO [io.quarkus] (main) Installed features: [camel-azure, camel-azure-storage-blob, camel-core, camel-file, camel-ftp, camel-log, camel-mail, camel-seda, camel-support-common, camel-support-jackson-dataformat-xml, camel-support-mail, camel-support-reactor-netty, cdi, config-yaml, jaeger, micrometer, smallrye-health, smallrye-openapi, smallrye-opentracing, swagger-ui]

2021-03-04 14:01:01,849 INFO [sftpToAzure] (Camel (camel-1) thread #0 - sftp://someSftpHost/../../Integrations/someDirectory) File 20210111150626x.csv (5380 bytes) is fetched from SFTP.

2021-03-04 14:01:02,191 ERROR [error] (Camel (camel-1) thread #1 - seda://error) simple{If you are using a StorageSharedKeyCredential, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate method call.

If you are using a SAS token, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate generateSas method call.

Please remember to disable 'Azure-Storage-Log-String-To-Sign' before going to production as this string can potentially contain PII.

Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

RequestId:3bc8c75d-601e-0025-0ef6-10b9bc000000

Time:2021-03-04T13:01:02.1677378Z</Message><AuthenticationErrorDetail>The Date header in the request is incorrect.</AuthenticationErrorDetail></Error>"}`

**Comment by tidemyr** [comment]
Move this issue to camel-quarkus
