### ISSUE TITLE
Remote dev mode fails to start

### ISSUE THREAD

**Issue by mswiderski** [quarkusio/quarkus#15494]
**Describe the bug**
When trying to run application in remove dev mode it fails to start with following exception

````
2021-03-05 14:50:49,723 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to create compiler, runtime compilation will be unavailable: java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:276)
	at io.quarkus.deployment.dev.ClassLoaderCompiler.lambda$new$0(ClassLoaderCompiler.java:149)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1083)
	at io.quarkus.deployment.dev.ClassLoaderCompiler.<init>(ClassLoaderCompiler.java:144)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.setupRuntimeCompilation(IsolatedDevModeMain.java:222)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:372)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:56)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:127)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
	at io.quarkus.deployment.mutability.DevModeTask.main(DevModeTask.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:50)
	at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:35)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
````

Extensions used `cdi, kubernetes, kubernetes-client, operator-sdk, resteasy, resteasy-jackson, security, smallrye-health, smallrye-openapi, swagger-ui`

**Expected behavior**
Application should start with remote dev mode

**Actual behavior**
Fails to start

**To Reproduce**

1. Create application with above listed extensions
2. Run the application build with container image jib extension (requires [PR](https://github.com/quarkusio/quarkus/pull/15480)
3. run docker `docker run -p 8080:8080 -e QUARKUS_LAUNCH_DEVMODE=true IMAGE`

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.package.type=mutable-jar
quarkus.live-reload.password=1234
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Maciejs-MacBook-Pro.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: from  [PR](https://github.com/quarkusio/quarkus/pull/15480)
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by jaikiran** [comment]
Closing this since https://github.com/quarkusio/quarkus/pull/15500 PR has now been merged.
