### ISSUE TITLE
Quarkus Dev-Mode does not work, when M2_Repo path contains a Space

### ISSUE THREAD

**Issue by JapuDCret** [quarkusio/quarkus#15496]
**Describe the bug**
When trying to run Quarkus Dev-Mode from the Maven plugin it fails, because a JAR could not be found (see log below).

*I managed to **fix** it by moving my "localRepository" in Mavens setting.xml to a location that does not contain a space.*

**Expected behavior**
 / 

**Actual behavior**
 / 

**To Reproduce**

I used this repo and immediately got an error: [https://github.com/stephan-mueller/quarkus-showcase](https://github.com/stephan-mueller/quarkus-showcase)

1. Have Windows (not known, if this is necessary)
2. Have the path to the M2_REPO contain a space
(e.g. when your username contains a space and the M2_REPO is contained in your user-dir)
3. Execute `mvn quarkus:dev`
4. Get Error (see log below)

**Configuration**
 / 

**Screenshots**
 /

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `MINGW64_NT-10.0-18363 DESKTOP-12345 3.1.7-340.x86_64 2020-09-22 19:03 UTC x86_64 Msys`
 - Output of `java -version`: `OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)`
 - GraalVM version (if different from Java): /
 - Quarkus version or git rev: `1.11.0.Final` (used in pom.xml)
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

**Additional context**
```bash
Marvin Kienitz@DESKTOP-12345 MINGW64 /c/git/quarkus-showcase (master)
$ mvn quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] --------< de.openknowledge.projects.showcase:quarkus-showcase >---------
[INFO] Building quarkus-showcase 0
[INFO] --------------------------------[ jar ]---------------------------------
 [INFO]
[INFO] --- quarkus-maven-plugin:1.11.0.Final:dev (default-cli) @ quarkus-showcase ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to C:\git\quarkus-showcase\target\classes
Listening for transport dt_socket at address: 5005
2021-03-05 15:38:52,200 INFO  [org.jbo.threads] (main) JBoss Threads version 3.2.0.Final
2021-03-05 15:38:52,697 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.flyway.devconsole.DevConsoleProcessor#collectBeanInfo threw an exception: java.lang.RuntimeException: Unable to determine groupId and artifactId of the jar that contains io.quarkus.flyway.devconsole.DevConsoleProcessor
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:76)
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:32)
        at io.quarkus.devconsole.spi.DevConsoleRuntimeTemplateInfoBuildItem.<init>(DevConsoleRuntimeTemplateInfoBuildItem.java:39)
        at io.quarkus.flyway.devconsole.DevConsoleProcessor.collectBeanInfo(DevConsoleProcessor.java:17)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.NoSuchFileException: C:\Users\Marvin%20Kienitz\.m2\repository\io\quarkus\quarkus-flyway-deployment\1.11.0.Final\quarkus-flyway-deployment-1.11.0.Final.jar
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:160)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:527)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:399)
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:47)
        ... 13 more

        [error]: Build step io.quarkus.arc.deployment.devconsole.DevConsoleProcessor#collectBeanInfo threw an exception: java.lang.RuntimeException: Unable to determine groupId and artifactId of the jar that contains io.quarkus.arc.deployment.devconsole.DevConsoleProcessor
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:76)
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:32)
        at io.quarkus.devconsole.spi.DevConsoleRuntimeTemplateInfoBuildItem.<init>(DevConsoleRuntimeTemplateInfoBuildItem.java:39)
        at io.quarkus.arc.deployment.devconsole.DevConsoleProcessor.collectBeanInfo(DevConsoleProcessor.java:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.NoSuchFileException: C:\Users\Marvin%20Kienitz\.m2\repository\io\quarkus\quarkus-arc-deployment\1.11.0.Final\quarkus-arc-deployment-1.11.0.Final.jar
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:160)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:527)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:399)
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:47)
        ... 13 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:274)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:150)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:57)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:78)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:372)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:128)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:81)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:144)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.flyway.devconsole.DevConsoleProcessor#collectBeanInfo threw an exception: java.lang.RuntimeException: Unable to determine groupId and artifactId of the jar that contains io.quarkus.flyway.devconsole.DevConsoleProcessor
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:76)
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:32)
        at io.quarkus.devconsole.spi.DevConsoleRuntimeTemplateInfoBuildItem.<init>(DevConsoleRuntimeTemplateInfoBuildItem.java:39)
        at io.quarkus.flyway.devconsole.DevConsoleProcessor.collectBeanInfo(DevConsoleProcessor.java:17)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.NoSuchFileException: C:\Users\Marvin%20Kienitz\.m2\repository\io\quarkus\quarkus-flyway-deployment\1.11.0.Final\quarkus-flyway-deployment-1.11.0.Final.jar
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:160)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:527)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:399)
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:47)
        ... 13 more

        [error]: Build step io.quarkus.arc.deployment.devconsole.DevConsoleProcessor#collectBeanInfo threw an exception: java.lang.RuntimeException: Unable to determine groupId and artifactId of the jar that contains io.quarkus.arc.deployment.devconsole.DevConsoleProcessor
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:76)
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:32)
        at io.quarkus.devconsole.spi.DevConsoleRuntimeTemplateInfoBuildItem.<init>(DevConsoleRuntimeTemplateInfoBuildItem.java:39)
        at io.quarkus.arc.deployment.devconsole.DevConsoleProcessor.collectBeanInfo(DevConsoleProcessor.java:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.NoSuchFileException: C:\Users\Marvin%20Kienitz\.m2\repository\io\quarkus\quarkus-arc-deployment\1.11.0.Final\quarkus-arc-deployment-1.11.0.Final.jar
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:160)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:527)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:399)
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:47)
        ... 13 more

        at io.quarkus.builder.Execution.run(Execution.java:116)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:148)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:272)
        ... 9 more
        Suppressed: java.lang.RuntimeException: Unable to determine groupId and artifactId of the jar that contains io.quarkus.arc.deployment.devconsole.DevConsoleProcessor
                at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:76)
                at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:32)
                at io.quarkus.devconsole.spi.DevConsoleRuntimeTemplateInfoBuildItem.<init>(DevConsoleRuntimeTemplateInfoBuildItem.java:39)
                at io.quarkus.arc.deployment.devconsole.DevConsoleProcessor.collectBeanInfo(DevConsoleProcessor.java:33)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:564)
                at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
                at java.base/java.lang.Thread.run(Thread.java:832)
                at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Caused by: java.nio.file.NoSuchFileException: C:\Users\Marvin%20Kienitz\.m2\repository\io\quarkus\quarkus-arc-deployment\1.11.0.Final\quarkus-arc-deployment-1.11.0.Final.jar
                at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:160)
                at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
                at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
                at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:527)
                at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:399)
                at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:47)
                ... 13 more
Caused by: java.lang.RuntimeException: Unable to determine groupId and artifactId of the jar that contains io.quarkus.flyway.devconsole.DevConsoleProcessor
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:76)
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:32)
        at io.quarkus.devconsole.spi.DevConsoleRuntimeTemplateInfoBuildItem.<init>(DevConsoleRuntimeTemplateInfoBuildItem.java:39)
        at io.quarkus.flyway.devconsole.DevConsoleProcessor.collectBeanInfo(DevConsoleProcessor.java:17)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.NoSuchFileException: C:\Users\Marvin%20Kienitz\.m2\repository\io\quarkus\quarkus-flyway-deployment\1.11.0.Final\quarkus-flyway-deployment-1.11.0.Final.jar
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:160)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:527)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:399)
        at io.quarkus.deployment.util.ArtifactInfoUtil.groupIdAndArtifactId(ArtifactInfoUtil.java:47)
        ... 13 more

2021-03-05 15:38:52,697 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
```

**Comment by geoand** [comment]
Is this still a problem with `1.11.5.Final` or `1.12.1.Final`?

**Comment by JapuDCret** [comment]
@geoand thanks for suggesting that, both of these versions are working as expected. I would therefore say that **this is already fixed**.

Version `1.11.5.Final`
```bash
Marvin Kienitz@DESKTOP-55VO1DT MINGW64 /c/git/quarkus-showcase (master)
$ mvn quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] --------< de.openknowledge.projects.showcase:quarkus-showcase >---------
[INFO] Building quarkus-showcase 0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.11.5.Final:dev (default-cli) @ quarkus-showcase ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Nothing to compile - all classes are up to date
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-03-09 16:09:56,424 INFO  [io.qua.fly.FlywayProcessor] (build-25) Adding application migrations in path '/C:/git/quarkus-showcase/target/classes/db/migration/' using protocol 'file'
2021-03-09 16:09:56,851 WARN  [io.qua.arc.dep.ObserverValidationProcessor] (build-25) The method de.openknowledge.projects.greet.application.GreetReadinessCheck#onStartUp is an observer for @Initialized(ApplicationScoped.class). Observer notification for this event may vary between JVM and native modes! We strongly recommend to observe StartupEvent instead as that one is consistently delivered in both modes once the container is running.
2021-03-09 16:09:56,851 WARN  [io.qua.arc.dep.ObserverValidationProcessor] (build-25) The method de.openknowledge.projects.greet.application.GreetApplicationMetrics#onStartUp is an observer for @Initialized(ApplicationScoped.class). Observer notification for this event may vary between JVM and native modes! We strongly recommend to observe StartupEvent instead as that one is consistently delivered in both modes once the container is running.
2021-03-09 16:09:57,046 INFO  [io.qua.arc.pro.BeanProcessor] (build-25) Found unrecommended usage of private members (use package-private instead) in application beans:
        - @Inject field de.openknowledge.projects.greet.infrastructure.DatasourceHealthCheck#datasource,
        - @Inject field de.openknowledge.projects.greet.application.GreetResourceHealthCheck#config,
        - @Inject field de.openknowledge.projects.greet.application.GreetResource#service
2021-03-09 16:09:59,016 INFO  [org.fly.cor.int.lic.VersionPrinter] (Quarkus Main Thread) Flyway Community Edition 7.4.0 by Redgate
2021-03-09 16:09:59,189 INFO  [org.fly.cor.int.dat.bas.DatabaseType] (Quarkus Main Thread) Database: jdbc:postgresql://localhost:5432/greeting (PostgreSQL 12.6)
2021-03-09 16:09:59,249 INFO  [org.fly.cor.int.com.DbMigrate] (Quarkus Main Thread) Current version of schema "public": 1.0.0
2021-03-09 16:09:59,252 INFO  [org.fly.cor.int.com.DbMigrate] (Quarkus Main Thread) Schema "public" is up to date. No migration necessary.
2021-03-09 16:10:00,160 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-showcase 0 on JVM (powered by Quarkus 1.11.5.Final) started in 7.721s. Listening on: http://localhost:8080
2021-03-09 16:10:00,161 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-03-09 16:10:00,161 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, hibernate-validator, jdbc-postgresql, mutiny, narayana-jta, rest-client, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-health, smallrye-metrics, smallrye-openapi, swagger-ui]
Hello World!
```
Version `1.12.1.Final`
```bash
Marvin Kienitz@DESKTOP-55VO1DT MINGW64 /c/git/quarkus-showcase (master)
$ mvn quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] --------< de.openknowledge.projects.showcase:quarkus-showcase >---------
[INFO] Building quarkus-showcase 0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.12.1.Final:dev (default-cli) @ quarkus-showcase ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to C:\git\quarkus-showcase\target\classes
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-03-09 16:13:50,476 INFO  [io.qua.fly.FlywayProcessor] (build-6) Adding application migrations in path '/C:/git/quarkus-showcase/target/classes/db/migration/' using protocol 'file'
2021-03-09 16:13:50,861 WARN  [io.qua.arc.dep.ObserverValidationProcessor] (build-23) The method de.openknowledge.projects.greet.application.GreetReadinessCheck#onStartUp is an observer for @Initialized(ApplicationScoped.class). Observer notification for this event may vary between JVM and native modes! We strongly recommend to observe StartupEvent instead as that one is consistently delivered in both modes once the container is running.
2021-03-09 16:13:50,861 WARN  [io.qua.arc.dep.ObserverValidationProcessor] (build-23) The method de.openknowledge.projects.greet.application.GreetApplicationMetrics#onStartUp is an observer for @Initialized(ApplicationScoped.class). Observer notification for this event may vary between JVM and native modes! We strongly recommend to observe StartupEvent instead as that one is consistently delivered in both modes once the container is running.
2021-03-09 16:13:51,075 INFO  [io.qua.arc.pro.BeanProcessor] (build-2) Found unrecommended usage of private members (use package-private instead) in application beans:
        - @Inject field de.openknowledge.projects.greet.application.GreetResource#service,
        - @Inject field de.openknowledge.projects.greet.application.GreetResourceHealthCheck#config,
        - @Inject field de.openknowledge.projects.greet.infrastructure.DatasourceHealthCheck#datasource
2021-03-09 16:13:52,715 INFO  [org.fly.cor.int.lic.VersionPrinter] (Quarkus Main Thread) Flyway Community Edition 7.5.2 by Redgate
2021-03-09 16:13:52,875 INFO  [org.fly.cor.int.dat.bas.DatabaseType] (Quarkus Main Thread) Database: jdbc:postgresql://localhost:5432/greeting (PostgreSQL 12.6)
2021-03-09 16:13:52,934 INFO  [org.fly.cor.int.com.DbMigrate] (Quarkus Main Thread) Current version of schema "public": 1.0.0
2021-03-09 16:13:52,936 INFO  [org.fly.cor.int.com.DbMigrate] (Quarkus Main Thread) Schema "public" is up to date. No migration necessary.
2021-03-09 16:13:53,803 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-showcase 0 on JVM (powered by Quarkus 1.12.1.Final) started in 7.459s. Listening on: http://localhost:8080
2021-03-09 16:13:53,803 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-03-09 16:13:53,803 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, hibernate-validator, jdbc-postgresql, mutiny, narayana-jta, rest-client, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-health, smallrye-metrics, smallrye-openapi, swagger-ui]
Hello World!
```
