### ISSUE TITLE
AWS APIGateway V2 JWT Authorizer failure

### ISSUE THREAD

**Issue by Ralamboniaina** [quarkusio/quarkus#15517]
**Describe the bug**
Controlling access to HTTP APIs with JWT Authorizers is not working.

**Expected behavior**
return status code: 200 when access token is valid.

**Actual behavior**
return status code: 500.

```
Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (ByteArrayInputStream); line: 1, column: 1569] (through reference chain: io.quarkus.amazon.lambda.http.model.AwsProxyRequest["requestContext"]->io.quarkus.amazon.lambda.http.model.AwsProxyRequestContext["authorizer"]->io.quarkus.amazon.lambda.http.model.ApiGatewayAuthorizerContext["jwt"]): com.fasterxml.jackson.databind.exc.MismatchedInputException
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (ByteArrayInputStream); line: 1, column: 1569] (through reference chain: io.quarkus.amazon.lambda.http.model.AwsProxyRequest["requestContext"]->io.quarkus.amazon.lambda.http.model.AwsProxyRequestContext["authorizer"]->io.quarkus.amazon.lambda.http.model.ApiGatewayAuthorizerContext["jwt"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1468)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1242)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1148)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:63)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.SettableAnyProperty.deserialize(SettableAnyProperty.java:153)
	at com.fasterxml.jackson.databind.deser.SettableAnyProperty.deserializeAndSet(SettableAnyProperty.java:134)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1576)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2079)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1453)
	at io.quarkus.amazon.lambda.runtime.JacksonInputReader.readValue(JacksonInputReader.java:17)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.handle(AmazonLambdaRecorder.java:69)
	at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.handleRequest(QuarkusStreamHandler.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

**To Reproduce**

https://github.com/Ralamboniaina/hello-lambda.git

1. In terminal: go to the project directory
2. execute `sam deploy -g`
3. Once deployed, send a `GET` request to `/Prod/hello` endpoint with an authorization of type `OAuth 2.0`
4. An internal server error occurs

**Screenshots**
![Postman](https://raw.githubusercontent.com/Ralamboniaina/hello-lambda/master/screenshot.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.9" 2020-10-20
 - GraalVM version (if different from Java): OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
 - Quarkus version or git rev: 1.11.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by sberyozkin** [comment]
@Ralamboniaina How is JWT token produced, do you use `smallrye-jwt-build` to generate it ? And how is it verified by Quarkus in your case ?

**Comment by Ralamboniaina** [comment]
@sberyozkin I'm using Amazon Cognito User Pool to generate and validate JWT. In my case, it is not verified by Quarkus. Verification is performed before lambda invocation as explained here: https://serverless-idm.awssecworkshops.com/02-backend-auth/

**Comment by sberyozkin** [comment]
@Ralamboniaina I see, thanks, so it looks like this issue is about Quarkus Amazon Lambda implementation thinking this token is part of the application payload. CC @patriot1burke - hi Bill, are you looking after this code ? Have a look please when you get a chance if yes, thanks

**Comment by Ralamboniaina** [comment]
Quarkus 1.13 release solved this issue. Thank you @sberyozkin @patriot1burke.

**Comment by sberyozkin** [comment]
@Ralamboniaina thanks, I did not look into further but may be Bill did :-), cheers
