### ISSUE TITLE
OIDC is not redirected to login page when token is no longer valid (regression issue)

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15527]
**Describe the bug**
We have configured a Quarkus app and Keycloak instance to only provide token with a very shorten life (5 seconds):

application.properties:
```
quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/test-realm
quarkus.oidc.client-id=test-application-client
quarkus.oidc.credentials.secret=test-application-client-secret
# tolerate 5 seconds of clock skew between the Keycloak server and the application
quarkus.oidc.token.lifespan-grace=5
quarkus.oidc.application-type=web-app
quarkus.oidc.roles.source=accesstoken

# logout
quarkus.oidc.logout.path=/logout

quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
```

And keycloak realm:

```
{
  "realm": "test-realm",
  "enabled": true,
  "sslRequired": "none",
  "ssoSessionMaxLifespan": 5,
  // ...
  ],
  "clients": [
    {
      "clientId": "test-application-client",
      "enabled": true,
      "protocol": "openid-connect",
      "standardFlowEnabled": true,
      "implicitFlowEnabled": false,
      "directAccessGrantsEnabled": true,
      "clientAuthenticatorType": "client-secret",
      "secret": "test-application-client-secret",
      "redirectUris": [
        "*"
      ]
    }
  ]
}
```

The problem is that when the token is no longer valid, it returns an exception instead of redirecting to the Login Keycloak page (or the right resource):

```
2021-03-08 06:57:08,421 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /user failed, error id: ead7f609-e328-4e80-b091-3c8bc99af880-1: org.jose4j.jwt.consumer.InvalidJwtException: JWT (claims->{"exp":1615186623,"iat":1615186619,"auth_time":1615186618,"jti":"b002a09e-6353-40ef-a7b9-bf30cbc354c2","iss":"http://keycloak-plain-ts-mggowahjma.apps.ocp46.dynamic.quarkus/auth/realms/test-realm","sub":"59b5d078-3b23-4729-ad24-ff326b5fbf52","typ":"Bearer","azp":"test-application-client","session_state":"b18f609e-fd82-42a8-bb0a-368c81ec88a9","acr":"1","realm_access":{"roles":["test-user-role"]},"scope":"openid profile email","email_verified":false,"preferred_username":"test-user"}) rejected due to invalid claims or other invalid content. Additional details: [[1] The JWT is no longer valid - the evaluation time NumericDate{1615186628 -> Mar 8, 2021, 6:57:08 AM GMT} is on or after the Expiration Time (exp=NumericDate{1615186623 -> Mar 8, 2021, 6:57:03 AM GMT}) claim value (even when providing 5 seconds of leeway to account for clock skew).]
	at org.jose4j.jwt.consumer.JwtConsumer.validate(JwtConsumer.java:466)
	at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:311)
	at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:433)
	at org.jose4j.jwt.consumer.JwtConsumer.processToClaims(JwtConsumer.java:171)
	at io.quarkus.oidc.runtime.OidcProvider.verifyJwtToken(OidcProvider.java:86)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.verifyTokenUni(OidcIdentityProvider.java:254)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.verifyCodeFlowAccessTokenUni(OidcIdentityProvider.java:243)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.validateAllTokensWithOidcServer(OidcIdentityProvider.java:88)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.authenticate(OidcIdentityProvider.java:80)
	at io.quarkus.oidc.runtime.OidcIdentityProvider.access$000(OidcIdentityProvider.java:34)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$1$1.get(OidcIdentityProvider.java:67)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$1$1.get(OidcIdentityProvider.java:64)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.subscribe(UniMemoizeOp.java:76)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:50)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:104)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:51)
```

And in the browser, we see:

```
....
<header>
    <h1 class="container">Internal Server Error</h1>
    <div class="exception-message">
        <h2 class="container">Error id ead7f609-e328-4e80-b091-3c8bc99af880-1</h2>
    </div>
</header>
<div class="container content">
</div></body>
</html>
...
```

**Expected behavior**
We should have been redirected to Login keycloak to let users to enter the user credentials.

**Actual behavior**
We got a 500 HTTP status.

**To Reproduce**
1. git clone https://github.com/Sgitario/quarkus-openshift-test-suite
2. cd quarkus-openshift-test-suite
3. git checkout reproducer_15527
4. mvn -B -V clean install -pl .,app-metadata/deployment,app-metadata/runtime,common -Pquarkus-core-only
5. mvn -B -V clean install -pl security/keycloak-webapp -fae -Dts.use-ephemeral-namespaces=true -Pserverless,datagrid -Dts.authenticated-registry -Pquarkus-core-only -DskipITs=true

We have tests to cover this integration using testcontainers and as far I could see, this is only randomly failing. However, the same test can also be tested in OpenShift (you will need also a OCP instance to play with) and remove the `-DskipITs=true ` argument. Let me know if you need more insights to test this.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 999-SNAPSHOT

**Comment by sberyozkin** [comment]
@Sgitario Thanks Jose, looks like the exception is not wrapped correctly in some code branch, will have a look

**Comment by sberyozkin** [comment]
@Sgitario By the way, I'm not sure if this is a regression. The problem I'm seeing is that `500` is returned instead of `401`. 

I'm assuming the problem is around `quarkus.oidc.roles.source=accesstoken`.

With the code flow we have 2 tokens, ID token and access token. If the access token is invalid - it is 401 (500 at the moment) because it is the ID token which is a primary token in the code flow and which is used to determine what to do with respect to the user interactions.

`quarkus.oidc.roles.source=accesstoken` says - instead of getting the roles out of the ID token by default - get them out of the access token - this is generally not the best approach as the AT is meant to be propagated only, i,e, it should not, ideally be used to control the access to the endpoint which will propagate it - but sometimes users do it so we have this option.
So if it is invalid - it is 401.

Can you please give me a favour and remove `quarkus.oidc.roles.source=accesstoken` and check what happens when the ID token has expired - we have a refresh token tests which depend on this check and I believe it should redirect correctly. (you may need to use `@PermitAll` or set Keycloak to use MP JWT groups - which makes sure ID token has the roles info - `@PermitAll` is simpler - just to ensure you can verify the expired ID token leads to a redirect).

In meantime I'll look at testing the case with `quarkus.oidc.roles.source=accesstoken` - and making sure the expired AT leads to 401

thanks

**Comment by Sgitario** [comment]
Link to our failure test case: https://github.com/quarkus-qe/quarkus-openshift-test-suite/runs/2054266268?check_suite_focus=true

**Comment by Sgitario** [comment]
Removing `quarkus.oidc.roles.source=accesstoken` and adjusting the scenario worked.

**Comment by sberyozkin** [comment]
Hi @Sgitario thanks.

OK, let me finish please my test - but please note that the test involving `quarkus.oidc.roles.source=accesstoken` will need to be adjusted as well to expect 401 in case of the expired AT - if it were redirecting before it was in fact a bug - as it can cause a redirection loop - if the lifespan of the ID token is bigger than that of the AT - in which case, the provider will still see the user session being active and Keycloak/etc would redirect the user back - AT verification fails again - redirect - etc...

**Comment by sberyozkin** [comment]
@Sgitario Hi Jose - please see #15547, can you please give me a favour and check if, with that PR, you will see `401` ?
I've spent the whole day today trying to write a local test reproducing `500` when the code flow access token verification fails and it is always `401`.

As I said earlier - returning a redirect on the AT failure in case of the code flow is problematic - it may cause a redirect loop - I know now why it was redirecting before - both ID and AT have been always verified at the authentication time which was a performance cost (and was producing scary traces with Auth0 etc which return binary tokens) - but now we verify AT only if it is required.

Please also link me to the test with `test-containers` -as I can actually debug it

Cheers, Sergey

**Comment by Sgitario** [comment]
I could not reproduce this issue any longer after building your latest changes. Before, I was able to reproduce it almost 100% of the times when running in OpenShift.
Great job and thanks so much!
