### ISSUE TITLE
Error using Mandrel following getting started guide.

### ISSUE THREAD

**Issue by joshuawilson** [quarkusio/quarkus#15646]
**Describe the bug**
New to Quarkus. Followed the getting started guide on quarkus.io. Then started on the deploy native side. 
When I ran `mvnw package -Pnative` I got an error `Invalid version string '21.0.0.0.Final'`

**Expected behavior**
packaging completes

**Actual behavior**
Error
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 21.0.0.0.Final (Mandrel Distribution) (Java Version 11.0.10+9)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar getting-started-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace getting-started-1.0.0-SNAPSHOT-runner
[getting-started-1.0.0-SNAPSHOT-runner:222852]    classlist:   3,708.30 ms,  0.96 GB
[getting-started-1.0.0-SNAPSHOT-runner:222852]        setup:   1,192.86 ms,  0.96 GB
Fatal error:java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Invalid version string '21.0.0.0.Final'.
```

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Follow the getting started guide
2. Install Mandrel on Fedora with sdkman `Mandrel       | >>> | 21.0.0.0     | mandrel | installed  | 21.0.0.0-mandrel `
3. Package with Mandrel

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux localhost.localdomain 5.9.16-100.fc32.x86_64 #1 SMP Mon Dec 21 14:10:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
   - ```
   openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode)
```
 - GraalVM version (if different from Java): 21.0.0.0-mandrel
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Maven home: /home/josh/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.10, vendor: Oracle Corporation, runtime: /home/josh/.sdkman/candidates/java/21.0.0.0-mandrel
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.9.16-100.fc32.x86_64", arch: "amd64", family: "unix"
```

**Additional context**
(Add any other context about the problem here.)

**Comment by gastaldi** [comment]
I have a PR that fixes this

**Comment by gastaldi** [comment]
Here is the full stacktrace:

```
Fatal error:java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Invalid version string '21.0.0.0.Final'.
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
    at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
    at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)
Caused by: java.lang.IllegalArgumentException: Invalid version string '21.0.0.0.Final'.
    at org.graalvm.sdk/org.graalvm.home.Version.invalid(Version.java:143)
    at org.graalvm.sdk/org.graalvm.home.Version.<init>(Version.java:113)
    at org.graalvm.sdk/org.graalvm.home.Version.parse(Version.java:261)
    at org.graalvm.sdk/org.graalvm.home.Version.getCurrent(Version.java:293)
    at io.quarkus.runtime.graal.Target_java_io_ObjectStreamClass$GraalVM20OrEarlier.getAsBoolean(JavaIOSubstitutions.java:34)
    at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:893)
    at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:287)
    at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:265)
    at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:929)
    at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:863)
    at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
    at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
    at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Comment by zakkak** [comment]
Hello,

This is a [known issue](https://github.com/graalvm/mandrel/issues/218) that has been fixed in the builder images (so using `-Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-image:21.0-java11` should get you going) and [a fix for sdkman](https://github.com/sdkman/sdkman-db-migrations/pull/481) is pending approval.

Thanks for the report :)

**Comment by zakkak** [comment]
sdk man is now up to date:

```
$ sdk i java 21.0.0.0-mandrel
$ native-image --version
GraalVM Version 21.0.0.0-Final (Mandrel Distribution) (Java Version 11.0.10+9)
```

@joshuawilson could you please test it (you might need to `sdk rm java 21.0.0.0-mandrel` and `sdk ug`, I am not sure how sdk handles such cases) and close this issue if everything is OK?

**Comment by gastaldi** [comment]
Also you need to `sdk flush archives` first to remove binaries that were already downloaded

**Comment by joshuawilson** [comment]
The updated version in sdkman did indeed fix it. Thanks for the help.
Closing this.
