### ISSUE TITLE
RESTEasy Reactive: Lock contention between callback processing and resume()

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#15732]
## Description
I was running some performance tests on Resteasy reactive and picked up some lock contention (about 11% of all contention during my load test) which I think may not be needed:

![image](https://user-images.githubusercontent.com/26746221/111180272-8ad93e80-85b5-11eb-857c-bde4144a98b5.png)
![image](https://user-images.githubusercontent.com/26746221/111180300-9462a680-85b5-11eb-8cc2-36a594cafdcf.png)

Its this code here on org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext:
```
 synchronized void onComplete(Throwable throwable) {
        if (completionCallbacks != null) {
            for (CompletionCallback callback : completionCallbacks) {
                callback.onComplete(throwable);
            }
        }
 }
@Override
    public synchronized void registerCompletionCallback(CompletionCallback callback) {
        if (completionCallbacks == null) {
            completionCallbacks = new ArrayList<>();
        }
        completionCallbacks.add(callback);
    }
```
I am assuming the onComplete is contending with the resume() calls which also synchronize on the object.

## Implementation ideas

In order to resolve this, and as a by-product avoid state issues of callbacks being added after they may have been processed, I suggest using an explicit lock and state flag as opposed to locking on (this):

```
private final Lock stateManagementLock = new ReentrantLock(); // Prevent race conditions on callbacks without needing to lock on (this)
private boolean completionCallbacksInvoked = false;

void onComplete(Throwable throwable) {
        try {
            stateManagementLock.lock();
            if (completionCallbacks != null) {
                for (CompletionCallback callback : completionCallbacks) {
                    callback.onComplete(throwable);
                }
                completionCallbacks = null;
            }
            completionCallbacksInvoked = true;
        } finally {
            stateManagementLock.unlock();
        }
    }

    @Override
    public void registerCompletionCallback(CompletionCallback callback) {
        try {
            stateManagementLock.lock();
            if (completionCallbacksInvoked) {
                throw new IllegalStateException("Completion callbacks cannot be registered after the context has been closed");
            }
            if (completionCallbacks == null) {
                completionCallbacks = new ArrayList<>();
            }
            completionCallbacks.add(callback);
        } finally {
            stateManagementLock.unlock();
        }
 }
```

**Comment by geoand** [comment]
Using the lock would be the simplest solution. Did you run your benchmark against a patched version of Quarkus using this strategy to see how it performs?

**Comment by bcluap** [comment]
Yea I did. TBH there is no discernable difference. I guess it would only really be visible if there were callbacks that took some time. Removing the lock contention just helps keep thread pools smaller I guess.

**Comment by FroMage** [comment]
I would only update this method:

```java
 void onComplete(Throwable throwable) {
if(completionCallbacks == null)
  return;
synchronized(completionCallbacks){
        if (completionCallbacks != null) {
            for (CompletionCallback callback : completionCallbacks) {
                callback.onComplete(throwable);
            }
        }
}
 }
```

And make `completionCallbacks` volatile, I guess.

That should take care of the common case, no?

**Comment by bcluap** [comment]
Yes it would. Just not sure if you want to prevent the possibility of code registering callbacks after the onComplete is called

**Comment by stuartwdouglas** [comment]
Why is this actually contenting though? It seems inherently racey to have one thread calling onComplete at the same another thread is calling resume?

**Comment by bcluap** [comment]
I'll catch a thread dump during the contention and see exactly what the
scenario is.

**Comment by bcluap** [comment]
```
"netty-eventloop-3-10" #119 prio=5 os_prio=0 cpu=4293.04ms elapsed=44.43s tid=0x00007fae20014b10 nid=0x111d7e runnable  [0x00007fadf09db000]
   java.lang.Thread.State: RUNNABLE
        at jdk.internal.misc.Unsafe.unpark(java.base@16/Native Method)
        at java.util.concurrent.locks.LockSupport.unpark(java.base@16/LockSupport.java:177)
        at org.jboss.threads.EnhancedQueueExecutor$PoolThreadNode.unpark(EnhancedQueueExecutor.java:2238)
        at org.jboss.threads.EnhancedQueueExecutor.tryExecute(EnhancedQueueExecutor.java:1785)
        at org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:751)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:70)
        - locked <0x00000000fa2efea0> (a io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:46)
        at org.jboss.resteasy.reactive.server.jaxrs.ContainerRequestContextImpl.abortWith(ContainerRequestContextImpl.java:188)
        at guru.jini.arch.impl.rest.JaxRsUtils.replyImmediately(JaxRsUtils.java:81)
        at guru.jini.arch.conductor.ConductorProxyingFilter.lambda$doBackToBackCall$0(ConductorProxyingFilter.java:79)
        at guru.jini.arch.conductor.ConductorProxyingFilter$$Lambda$776/0x0000000801503aa8.accept(Unknown Source)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@16/CompletableFuture.java:714)
        at java.util.concurrent.CompletableFuture.postComplete(java.base@16/CompletableFuture.java:506)
        at java.util.concurrent.CompletableFuture.complete(java.base@16/CompletableFuture.java:2143)
        at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222)
        at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257)
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241)
        at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:113)
        at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:142)
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@16/Thread.java:831)
```



And...
```
"executor-thread-8" #24 daemon prio=5 os_prio=0 cpu=714.98ms elapsed=47.41s tid=0x00007faef5d43530 nid=0x111d18 waiting for monitor entry  [0x00007fae7d6fc000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.onComplete(AbstractResteasyReactiveContext.java:315)
        - waiting to lock <0x00000000fa2efea0> (a io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.close(AbstractResteasyReactiveContext.java:92)
        at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.close(ResteasyReactiveRequestContext.java:358)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:167)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(java.base@16/Thread.java:831)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by bcluap** [comment]
Just to explain our scenario...

Its basically a reverse proxy. Request comes in and hits our filter. We analyse it and see it must be proxied, suspend the request context, and use AHC (Netty based) async HTTP client to do the call to a downstream endpoint. 

When the response comes back, using the netty eventloop thread, we do an abortWith on the request context with the response we received.

```
JaxRsUtils.suspend(requestContext);

JG.Http.doHttpMethodForProxying(method, proxyTo,
        method.equals("GET") ? null : requestContext.getEntityStream(),
        asMap(requestContext.getUriInfo().getQueryParameters()),
        proxyHeaders,
        Duration.ofMillis(socketTo),
        requestContext.getLength())
        .thenAccept((Response response) -> {
            requestContext.abortWith(response);
         });
```

The top thread is the response coming back on the HTTP client eventloop thread.
The bottom thread is the executor pool closing the context.

Our environment has @Blocking set at the application level. Maybe there could be an optimisation that if one does an abortWith then it should use that thread to close the context as opposed to an executor thread?

**Comment by geoand** [comment]
Thanks for the explanation @bcluap.

I have a question though: As your application is `@Blocking` be default (which means that the filters run on the worker thread as well), how come you suspend processing?
Why not just do a blocking HTTP call and not deal with the suspend / resume dance that doesn't earn you any advantage for a worker thread anyway?

**Comment by bcluap** [comment]
Unfortunately, the worker pool does not solve the C10k problem. Our system is like an API gateway and needs to be able to handle 10's of thousands of concurrent calls without needing a worker thread per concurrent call. The suspend, non-blocking downstream call and abortWith pattern means we are not blocking a worker thread while waiting for the downstream HTTP call to respond.

In playing around I've now managed to use a prematching filter which sees that a request will be proxied and changes the request URI to point to a fake JAX-RS resource (which is never actually called) annotated with @NonBlocking. This forces RESTEasy reactive to stay on the eventloop and performance is even better. But, I still see the lock contention sometimes between the incoming eventloop and the AHC replying eventloop:

```
"vert.x-eventloop-thread-7" #57 prio=5 os_prio=0 cpu=16418.33ms elapsed=159.29s tid=0x00007f76e9f10060 nid=0x1227a0 waiting for monitor entry  [0x00007f75fee73000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.onComplete(AbstractResteasyReactiveContext.java:315)
        - waiting to lock <0x00000000fe0798c0> (a io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.close(AbstractResteasyReactiveContext.java:92)
        at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.close(ResteasyReactiveRequestContext.java:358)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:167)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@16/Thread.java:831)



"netty-eventloop-3-8" #82 prio=5 os_prio=0 cpu=18536.67ms elapsed=158.96s tid=0x00007f761003ba10 nid=0x1227ba runnable  [0x00007f75fdba8000]
   java.lang.Thread.State: RUNNABLE
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.wakeup(SelectedSelectionKeySetSelector.java:73)
        at io.netty.channel.nio.NioEventLoop.wakeup(NioEventLoop.java:777)
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:849)
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:66)
        - locked <0x00000000fe0798c0> (a io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:46)
        at org.jboss.resteasy.reactive.server.jaxrs.ContainerRequestContextImpl.abortWith(ContainerRequestContextImpl.java:188)
        at guru.jini.arch.impl.rest.JaxRsUtils.replyImmediately(JaxRsUtils.java:81)
        at guru.jini.arch.conductor.ConductorProxyingFilter.lambda$doBackToBackCall$0(ConductorProxyingFilter.java:79)
        at guru.jini.arch.conductor.ConductorProxyingFilter$$Lambda$771/0x00000008014de458.accept(Unknown Source)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@16/CompletableFuture.java:714)
        at java.util.concurrent.CompletableFuture.postComplete(java.base@16/CompletableFuture.java:506)
        at java.util.concurrent.CompletableFuture.complete(java.base@16/CompletableFuture.java:2143)
        at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222)
        at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257)
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241)
        at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:113)
        at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:142)
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@16/Thread.java:831)

```

So this scenario can play out in any situation where there is a suspend on one thread and an abortWith on another.

**Comment by geoand** [comment]
OK, that `abortWith` is indeed a interesting use case.

I'd be in favor getting your suggestion or the one from @FroMage in to help reduce contention

**Comment by FroMage** [comment]
Also sounds like your filter should be able to run on the event loop even if the application is blocking by default. Shouldn't we add support for that @geoand ?

I mean, the workaround is pretty ugly.

**Comment by geoand** [comment]
> Also sounds like your filter should be able to run on the event loop even if the application is blocking by default. Shouldn't we add support for that @geoand ?
> 

It is being on the worker thread because the application is using `@Blocking` as the default. We certainly could support adding `@NonBlocking` on the filter, but that could trigger a ping pong between event-loop and worker thread dispatch if there are multiple filters.
WDYT?

**Comment by FroMage** [comment]
Well, it depends.

If this filter is the first one, it doesn't cost to run it on the event loop, right? If all it does is suspend then it's totally worth it.

If it does not suspend and passes execution to further filters or endpoints that do require a worker thread, then it didn't cost anything special.

It would only incur costs of ping-pong if indeed we have non-blocking -> blocking -> non-blocking but I'm sure we can add a score entry for that ;)

**Comment by geoand** [comment]
Yeah, that makes sense.

**Comment by bcluap** [comment]
@NonBlocking annotation on a filter would be marvellous

**Comment by geoand** [comment]
As I am certain that the `@NonBlocking` -> `@Blocking` -> `@NonBlocking` dance will cause problems, here is what I propose:

We do support `@NonBlocking` on filters, but all the `@NonBlocking` filters **must** be the first ones to execute - otherwise fail.

**Comment by bcluap** [comment]
Very reasonable. Cannot see why one would ever go from worker back to
eventloop on purpose

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/15882 should take care of it
