### ISSUE TITLE
StreamTestCase is flaky

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#15756]
https://github.com/quarkusio/quarkus/runs/2119138457?check_suite_focus=true
```
[INFO] Running io.quarkus.resteasy.reactive.server.test.stream.StreamTestCase
2021-03-16 06:46:30,304 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT on JVM started in 0.377s. Listening on: http://localhost:8081
2021-03-16 06:46:30,304 INFO  [io.quarkus] (main) Profile test activated. 
2021-03-16 06:46:30,304 INFO  [io.quarkus] (main) Installed features: [cdi, hibernate-validator, mutiny, resteasy-reactive, resteasy-reactive-jaxrs-client, security, smallrye-context-propagation]
Received Called at Tue Mar 16 06:46:30 UTC 2021
Received Called at Tue Mar 16 06:46:31 UTC 2021
Received Called at Tue Mar 16 06:46:34 UTC 2021
2021-03-16 06:46:36,058 INFO  [io.quarkus] (main) Quarkus stopped in 0.012s
Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.547 s <<< FAILURE! - in io.quarkus.resteasy.reactive.server.test.stream.StreamTestCase
Error:  io.quarkus.resteasy.reactive.server.test.stream.StreamTestCase.testClientStreaming  Time elapsed: 0.007 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2> but was: <0>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
	at io.quarkus.resteasy.reactive.server.test.stream.StreamTestCase.testClientStreaming(StreamTestCase.java:96)
```
Came uo here: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/New.20catalog.20API/near/230467384

/cc @geoand

**Comment by geoand** [comment]
cc @FroMage

**Comment by FroMage** [comment]
The problem, as always, is that I can't seem to be able to reproduce this.

**Comment by geoand** [comment]
Closing in favor of https://github.com/quarkusio/quarkus/issues/16227
