### ISSUE TITLE
The URL protocol https is supported but not enabled by default --enable-url-protocols=https

### ISSUE THREAD

**Issue by akram** [quarkusio/quarkus#1591]
Hi Quarkers,

I built my application using quarks and I created a native binary using:
```
mvn package -Pnative -Dnative-image.docker-build=true
```

Then I embedded the binary into a Docker image and ran it using:
```
docker build -f src/main/docker/Dockerfile -t quarkus/quarkus-webcrawler .
docker run -p 8080:8080 quarkus/quarkus-webcrawler
```

When I try to access my application I got:
```
2019-03-20 14:10:56,727 ERROR [io.und.request] (XNIO-1 task-1) UT005023: Exception handling request to /: org.jboss.resteasy.spi.UnhandledException: com.oracle.svm.core.jdk.UnsupportedFeatureError: Accessing an URL protocol that was not enabled. The URL protocol https is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=https option to the native-image command.
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:103)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:323)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:495)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
```

The documentation is not very clear about it. The graalVM says that the flag must be enabled while building the native binary. But I can't find where to enable it.
Should this be done in the maven `mvn package -Pnative -Dnative-image.docker-build=true
` command ?

**Comment by gsmet** [comment]
The SSL support in GraalVM is a bit rough right now.

I invite you to take a look at this part of our SSL guide: https://quarkus.io/guides/native-and-ssl-guide#the-sunec-library-and-friends .

**Comment by akram** [comment]
Hi @gsmet 

thank you for this pointer. It explains why.
However, my docker image is but with `mvn package -Pnative -Dnative-image.docker-build=true`
Shouldn't the GraalVM image build process take care of pointing java.library.path and javax.net.ssl.trustStore to the new GraalVM home ?

**Comment by gsmet** [comment]
Not really, you need to include them inside your Docker build and tune things yourself unfortunately.
