### ISSUE TITLE
Resteasy Rest Client: New exception behavior logs a stacktrace

### ISSUE THREAD

**Issue by Faboli7** [quarkusio/quarkus#15967]
## Describe the bug
Hi,
I have a project using `quarkus-resteasy-jsonb` and `quarkus-rest-client-jsonb` and since I migrated to quarkus 1.12 and its [new way of handling rest client exceptions](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.12#rest-client-exceptions), when a rest client returns a response with status >= 300, an error with stacktrace is logged when resteasy wraps the original exception in a `ResteasyWebApplicationException`.

However, everything seems to work as expected, as this error is non blocking, the code execution continues, the original exception is wrapped in a `ResteasyWebApplicationException` and the response is sanitized as expected.

### Expected behavior
Everything seems to work as expected so no error should be logged. If this is a real error, it should be fixed.

### Actual behavior
The wrapping of the original exception logs an error even though it seems to work as expected.

## To Reproduce
Simply create following components and call GET /client-resource.

```
@Path("service")
@RegisterRestClient(configKey = "service")
public interface Service {

    @GET
    Response get();
    
}
```
```
@Path("client-resource")
public final class ClientResource {

    @Inject
    @RestClient
    Service service;
    
    @GET
    public Response get() {
        return service.get();
    }
}
```
```
@Path("service")
public final class ServiceResource {

    @GET
    public Response get() {
        return Response.status(400).build();
    }
    
}
```
### Screenshots
Example 1:
```
2021-03-23 15:55:11,292 ERROR [org.jbo.res.res.i18n] (executor-thread-12) RESTEASY002010: Failed to execute: org.jboss.resteasy.client.exception.ResteasyWebApplicationException: Unknown error, status code 401
	at org.jboss.resteasy.client.exception.WebApplicationExceptionWrapper.wrap(WebApplicationExceptionWrapper.java:107)
	at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:21)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:39)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:154)
	at com.sun.proxy.$Proxy60.getAll(Unknown Source)
```
Example 2:
```
2021-03-23 17:25:32,617 ERROR [org.jbo.res.res.i18n] (executor-thread-12)  RESTEASY002010: Failed to execute: org.jboss.resteasy.client.exception.ResteasyWebApplicationException: Unknown error, status code 400
	at org.jboss.resteasy.client.exception.WebApplicationExceptionWrapper.wrap(WebApplicationExceptionWrapper.java:107)
	at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:21)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:39)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:154)
	at com.sun.proxy.$Proxy74.resetPassword(Unknown Source)
```
### Output of `uname -a` or `ver`
Happens on Windows and Linux
### Output of `java -version`
openjdk 11.0.7 2020-04-14 LTS
OpenJDK Runtime Environment 20.4-(Zulu-11.39+15-win_x64)-Microsoft-Azure-restricted (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM 20.4-(Zulu-11.39+15-win_x64)-Microsoft-Azure-restricted (build 11.0.7+10-LTS, mixed mode)

### Quarkus version or git rev
1.12.2
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
maven 3.6.3

**Comment by geoand** [comment]
Is this still an issue in the latest versions of Quarkus?

**Comment by geoand** [comment]
Closing for lack of feedback
