### ISSUE TITLE
document existing jbang install option

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#16032]

**Comment by maxandersen** [comment]
started in #16046

**Comment by Sgitario** [comment]
@maxandersen the command `curl -Ls https://sh.jbang.dev | bash -s - app install --force qs@quarkusio` is not working for me:

```
[jbang] jbang version 0.71.1
[jbang] Reading catalog from /home/jcarvaja/.jbang/implicit-catalog.json
[jbang] Retrieved file from cache https://raw.githubusercontent.com/quarkusio/jbang-catalog/HEAD/jbang-catalog.json = /home/jcarvaja/.jbang/cache/urls/18f27301d3b8b1c3bf70b027e02294385c940f21a743bc722c8f8f5bf569840c/jbang-catalog.json
[jbang] Reading catalog from /home/jcarvaja/.jbang/cache/urls/18f27301d3b8b1c3bf70b027e02294385c940f21a743bc722c8f8f5bf569840c/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json
[jbang] [ERROR] No alias found with name 'qs'
dev.jbang.cli.ExitException: No alias found with name 'qs'
	at dev.jbang.catalog.Alias.fromCatalog(Alias.java:124)
	at dev.jbang.catalog.Alias.merge(Alias.java:80)
	at dev.jbang.catalog.Alias.get(Alias.java:61)
	at dev.jbang.source.Source.forResource(Source.java:147)
	at dev.jbang.cli.AppInstall.install(App.java:101)
	at dev.jbang.cli.AppInstall.doCall(App.java:81)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:135)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:130)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues
```

I see the alias is in `https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json`, but perhaps the catalog is missing (I could not find it in here https://www.jbang.dev/appstore/.

Any ideas?

**Comment by maxandersen** [comment]
it is on jbang.dev/appstore:

<img width="803" alt="2021-05-26_23-35-22" src="https://user-images.githubusercontent.com/54129/119734289-10615080-be7b-11eb-817b-9068f4b790ae.png">

any chance you used some script from @quarkusio before ? 

then try `curl -Ls https://sh.jbang.dev | bash -s - app install --force qs@quarkusio` or simply `jbang --fresh app install --force qs@quarkusio`

then the issue is that jbang doesn't fetch the new cache more agressively.

**Comment by ebullient** [comment]
https://github.com/quarkusio/quarkus/pull/17502 -- resolved by that (+ adding cli to the docs index via https://github.com/quarkusio/quarkusio.github.io/pull/988 ?

**Comment by ebullient** [comment]
Done!
