### ISSUE TITLE
OpenAPI annotation @APIResponse without content makes Quarkus crash

### ISSUE THREAD

**Issue by enbohm** [quarkusio/quarkus#1611]
The following code prevents Quarkus to start and generates an java.lang.NullPointerException exception (see stacktrace below). 
 
This code was tested on macOS Mojave and OpenJDK Runtime Environment 18.9 (build 11+28) with Quarkus 0.12.0. <b>NOTE!</b> This did work with Quarkus 0.11.0. 
```java
@Path("/")
public class GreetingEndpoint {
  @GET
  @APIResponses(value = {@APIResponse(responseCode = "204", //
      description = "A response with no content")})
  @Operation(summary = "Say Hello World")
  @Path("/no-content")
  public Response greeting() {
    return Response.noContent().build();
  }
}
```
```
Failed to start quarkus: java.lang.RuntimeException: org.jboss.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#registerOpenApiSchemaClassesForReflection threw an exception: java.lang.NullPointerException
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:134)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:105)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: org.jboss.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#registerOpenApiSchemaClassesForReflection threw an exception: java.lang.NullPointerException
	at org.jboss.builder.Execution.run(Execution.java:123)
	at org.jboss.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:136)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:110)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:99)
	... 2 more
Caused by: java.lang.NullPointerException
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.registerReflectionForApiResponseSchemaSerialization(SmallRyeOpenApiProcessor.java:163)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.registerOpenApiSchemaClassesForReflection(SmallRyeOpenApiProcessor.java:154)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:506)
	at org.jboss.builder.BuildContext.run(BuildContext.java:413)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1416)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

Adding a content value to the annotation such as this:
```java
@APIResponses(value = {@APIResponse(responseCode = "204", //
      description = "A response with no content", content = @Content(mediaType = "application/json",
          schema = @Schema(implementation = String.class)))})
```
makes the code work but shouldn't be mandatory AFAIK.

The issue seems to be in smallrye-openapi-module:
```
SmallRyeOpenApiProcessor#registerReflectionForApiResponseSchemaSerialization 
``` 
which expects that a content attribute exist 
```AnnotationInstance[] contents = apiResponseAnnotationInstance.value(OPENAPI_RESPONSE_CONTENT).asNestedArray(); //<- this causes the NPE```

**Comment by gsmet** [comment]
@machi1990 could you take a look (and add more tests)? Thanks!

**Comment by machi1990** [comment]
@gmet, I see the issue. I’ll take a look at it this evining.
