### ISSUE TITLE
Reactive ContainerResponseFilter throws NPE

### ISSUE THREAD

**Issue by sirf** [quarkusio/quarkus#16122]
## Describe the bug
When a ContainerResponseFilter is active in a reactive rest application,
and we try to use `getResourceMethod()` on the `ResourceInfo` object,
NullPointerException is observed. Also, the filter doesn't seem to be invoked at all on some endpoints.

### Expected behavior
Should not throw NPE

### Actual behavior
NPE is thrown.

```
java.lang.NullPointerException
	at org.jboss.resteasy.reactive.server.injection.ContextProducers.resourceInfo(ContextProducers.java:89)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.create(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.zig:163)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.create(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_Bean.zig:194)
	at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:68)
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:33)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.arc$delegate(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.zig:43)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.getResourceMethod(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.zig:103)
	at org.acme.getting.started.Filter.filter(Filter.java:22)
	at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:24)
	at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:9)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:117)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:47)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:137)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder.lambda$start$1(StaticResourcesRecorder.java:62)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:101)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:206)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

## To Reproduce

I've attached a reproducer. It's just the `getting-started-reactive` project with the following file added to it:

```
package org.acme.getting.started;

import javax.annotation.Priority;
import javax.ws.rs.Priorities;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerResponseContext;
import javax.ws.rs.container.ContainerResponseFilter;
import javax.ws.rs.container.ResourceInfo;
import javax.ws.rs.core.Context;
import javax.ws.rs.ext.Provider;

@Priority(Priorities.HEADER_DECORATOR)
@Provider
public class Filter implements ContainerResponseFilter {

	@Context
	ResourceInfo resourceInfo;

	@Override
	public void filter(final ContainerRequestContext requestContext, final ContainerResponseContext responseContext) {

		System.out.println(resourceInfo.getResourceMethod());
	}
}
```

1. Start the app, `./mvnw quarkus:dev`
2. GET localhost:8080/hello/greeting/Johan
    Confirm that no NPE is thrown and that the correct method signature is printed on stdout
3. GET localhost:8080/hello/greet
    NPE is thrown. Correct behavior would be to see the string null on stdout
4. GET localhost:8080/hello/greeting/3/Johan
    Note that the filter is not invoked at all this time. Nothing is printed on stdout

### Output of `java -version`
```
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-1, mixed mode, sharing)
```

### Quarkus version or git rev
1.12.2.Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/.../.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 14.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-14-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-45-generic", arch: "amd64", family: "unix"
```

**Comment by sirf** [comment]
Reproducer
[getting-started-reactive.tar.gz](https://github.com/quarkusio/quarkus/files/6230269/getting-started-reactive.tar.gz)

**Comment by maidanhcongtu** [comment]
I have the same issue do we have any workaround solution?

**Comment by TomasHofman** [comment]
I'm going to check this out.

**Comment by TomasHofman** [comment]
For the record, requesting `localhost:8080/hello/greet` throws NPE because there is no endpoint mapped at that URL in the reproducer, ergo no ResourceInfo can be produced.

Question is if this situation can be resolved better. Injection producer is not allowed to return `null` (which would allow us to hand the responsibility to check null over onto the ContainerResponseFilter implementation). Maybe return an "empty" ResourceInfo, or throw an IllegalStateException instead of NPE... In any case it's not supposed to be execution as usual.

I didn't check the other cases where the filter is not called yet.

**Comment by TomasHofman** [comment]
Regarding `ContainerResponseFilter` not being triggered for certain methods - it depends on the return type and it is purposeful. If the method returns Multi, the response filters are not triggered because by the time a filter would be triggered, data may already be streamed to the client, so e.g. trying to set response headers at that stage won't work. (A response filter triggers after a method invocation.)

If you need a filter to be triggered also for methods returning a `Multi`, use a `ContainerRequestFilter` or a `ResteasyReactiveContainerRequestFilter`, which are triggered before a REST method invocation and are triggered for all methods regardless of return type.

I you have a use case that is not accomodated by above, please share.

**Comment by sirf** [comment]
Thanks for looking into this.

I kind of expected that the response filter would always be executed before serializing the Multi in a response, but if the current behavior is deemed correct then your suggested workarounds will most likely do the trick. 

I guess it makes sense that ResourceInfo is null when there is no endpoint.

**Comment by sirf** [comment]
Thanks for looking into this.

I kind of expected that the response filter would always be executed before serializing the response. It's supposed to be a filter after all and not just a simple callback, but if the current behavior is deemed correct then your suggested workarounds will probably do the trick.

I guess it makes sense that ResourceInfo is null when there is no endpoint.

**Comment by TomasHofman** [comment]
I wouldn't say it's a callback. The order actions in current implementation is:

* request arrives,
* invoke *request* filters,
* invoke the REST method,
* for non-streaming methods - invoke *response* filters; for streaming methods, data can already go through.

Allowing developers to modify response via a ResponseFilter for streaming methods would create a false impression that a developer can manipulate the response in certain ways which he cannot. E.g. modify headers (which he cannot because headers may have already been sent), or work with payload (which he cannot because it may still be being produced, or no data may have been produced yet).

Different semantics / implementations can be contemplated of course, but use cases should first be presented and analyzed to figure out what would be the best approach to solve them.

Is there something that a request filter doesn't allow you to do?

**Comment by sirf** [comment]
The use-case is primarily to set custom headers in responses, streaming and non-streaming.
This can indeed be achieved through `ResteasyReactiveContainerRequestFilter.getServerRequestContext().serverResponse().addResponseHeader` and it's is by no means a blocking issue for me, but since it's not very intuitive to use a request filter to add something to the response I figured the response filter probably wasn't working as intended.

**Comment by geoand** [comment]
@TomasHofman 's analysis is spot on.

However RESTEasy Reactive should certainly not be throwing a NPE. https://github.com/quarkusio/quarkus/pull/19062 takes care of that
