### ISSUE TITLE
@ConfigProperty cannot be used twice

### ISSUE THREAD

**Issue by Edubits** [quarkusio/quarkus#1613]
When injecting a @ConfigProperty multiple times (in different classes) ConfigBuildStep#validateConfigProperties throws an exception:
```
11:50:26,863 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.RuntimeException: org.jboss.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ConfigBuildStep#validateConfigProperties threw an exception: java.lang.IllegalStateException: Duplicate key com.project.property (attempted merging values class java.lang.String and class java.lang.String)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:134)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:105)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: org.jboss.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ConfigBuildStep#validateConfigProperties threw an exception: java.lang.IllegalStateException: Duplicate key com.project.property (attempted merging values class java.lang.String and class java.lang.String)
	at org.jboss.builder.Execution.run(Execution.java:123)
	at org.jboss.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:136)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:110)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:99)
	... 2 more
Caused by: java.lang.IllegalStateException: Duplicate key com.project.property (attempted merging values class java.lang.String and class java.lang.String)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.quarkus.arc.deployment.ConfigBuildStep.validateConfigProperties(ConfigBuildStep.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:506)
	at org.jboss.builder.BuildContext.run(BuildContext.java:413)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1416)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

This worked in 0.11.0, but is broken in 0.12.0.

**Comment by geoand** [comment]
@Edubits is this a problem only in the dev mode?

**Comment by Edubits** [comment]
Sorry for not mentioning, it happens both in dev and in a `mvn clean package` build. In the latter case the following is logged:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.12.0:build (default) on project foo_project: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.arc.deployment.ConfigBuildStep#validateConfigProperties threw an exception: java.lang.IllegalStateException: Duplicate key com.project.property (attempted merging values class java.lang.String and class java.lang.String)
```

**Comment by geoand** [comment]
Thank you for the update @Edubits

**Comment by geoand** [comment]
@starksm64 I just opened PR for this :)

**Comment by Edubits** [comment]
Thanks, tested with the master and can confirm it works now.

**Comment by geoand** [comment]
Great to hear :)
