### ISSUE TITLE
AWS Lambda Java Events 3.8.0 adoption and failures

### ISSUE THREAD

**Issue by missourian55** [quarkusio/quarkus#16199]
## Description

AWS released a new Java events version a week ago. Quarkus 1.13.0.Final use version *3.7.0* of below library. When I manually added below version the native image compilation failed with some JODA errors. I just want to give a heads up to Quarkus team about this issue

**New version**
```xml

    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-events</artifactId>
      <version>3.8.0</version>
    </dependency>
```
**Native Image compilation failure**
```java
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.joda.time.Interval.parseWithOffset(java.lang.String). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing com.fasterxml.jackson.datatype.joda.deser.IntervalDeserializer._fromString(IntervalDeserializer.java:76)
Call path from entry point to com.fasterxml.jackson.datatype.joda.deser.IntervalDeserializer._fromString(JsonParser, DeserializationContext, String):
	at com.fasterxml.jackson.datatype.joda.deser.IntervalDeserializer._fromString(IntervalDeserializer.java:54)
	at com.fasterxml.jackson.datatype.joda.deser.IntervalDeserializer.deserialize(IntervalDeserializer.java:38)
	at com.fasterxml.jackson.datatype.joda.deser.IntervalDeserializer.deserialize(IntervalDeserializer.java:15)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1426)
	at io.quarkus.amazon.lambda.runtime.JacksonInputReader.readValue(JacksonInputReader.java:17)
	at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:76)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

**Comment by patriot1burke** [comment]
Which event are you using in your Lambda?  I think this issue has popped up before and the solution is to exclude joda.

**Comment by missourian55** [comment]
I am using below events. *IamPolicyResponse* is the new event added by AWS to support Lambda Authorizer, it doesn't have any JODA references.

```java

// Lambda Authorizer
public class AuthorizerHandler implements RequestHandler<APIGatewayCustomAuthorizerEvent, IamPolicyResponse>


//Business Lambda
public class BusinessHandler implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent>
```

**Comment by missourian55** [comment]
I think I find the problem, transitive dependency issues

aws-lambda-java-events depends on **joda 2.6**

quarkus-amazon-lambda-common depends on jackson-datatype-joda depends on **joda 2.10.8**

So your recommendation of adding exclusion to joda when explicitly declaring **aws-lambda-java-events** works or we can declare an explicit joda dependency. Thank You!
