### ISSUE TITLE
Quarkus 1.13.0.Final Gradle plugin does not run annotation processors

### ISSUE THREAD

**Issue by tanadeau** [quarkusio/quarkus#16196]
## Describe the bug
Using Quarkus 1.13.0.Final and the Gradle plugin of the same version, annotation processors are no longer run. If I keep the library versions of Quarkus at 1.13.0.Final and just change the Gradle plugin to 1.12.2.Final, everything works as expected.

### Expected behavior
Annotation processors are run, code is generated by them, and build completes successfully.

### Actual behavior
Annotation processors are not run and no code is generated causing build errors like `UnsatisfiedResolutionException`.

## To Reproduce
Gradle project: 
[reproducer.zip](https://github.com/quarkusio/quarkus/files/6246756/reproducer.zip)

1. Run `./gradlew build` and see the error below:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.FooMapper and qualifiers [@Default]
        - java member: org.acme.GreetingResource#mapper
        - declared on CLASS bean [types=[org.acme.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.GreetingResource]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1081)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:255)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:419)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.FooMapper and qualifiers [@Default]
        - java member: org.acme.GreetingResource#mapper
        - declared on CLASS bean [types=[org.acme.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.GreetingResource]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:378)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:247)
        ... 12 more
```

When changing the Gradle plugin to 1.12.2.Final, the `FooMapperImpl` gets created (via the MapStruct annotation processor) that satisfies that dependency.

### Output of `uname -a` or `ver`
```
Darwin C02YK01PLVCG-ML 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
```

### Output of `java -version`
```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

### Quarkus version or git rev
1.13.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (AdoptOpenJDK 11.0.10+9)
OS:           Mac OS X 10.15.7 x86_64
```

## Additional context
(Add any other context about the problem here.)

**Comment by tanadeau** [comment]
My guess is that it has something to do with https://github.com/quarkusio/quarkus/commit/de6b5b5760b06edc0f0061ebff14985ee09dad11#diff-9ce4124e67bfff3d68b092c4fb5a0e168cf8c722357f89ad19766a34700987dc

**Comment by tanadeau** [comment]
If I change `annotationProcessor` to `compileOnly`, then it works. However, doing so breaks a lot of Gradle code examples for libraries that use annotation processors.
