### ISSUE TITLE
Quarkus Kotlin using @ApplicationPath triggering javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path on production only.

### ISSUE THREAD

**Issue by daibertdiego** [quarkusio/quarkus#16217]
## Describe the bug
I am using `@ApplicationPath(value = "/api")
class RestApplicationConfig : Application()` to modify my base URL for my REST endpoints and when I run the module using the quarkus:dev everything is fine, but when I run the module in production on kubernets, the module keep logging this error forever.

`2021-04-02 21:10:00 ERROR [or.un.ex.ExceptionHandlers] (executor-thread-1) Uncaught exception: javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://myURL/api
        at org.jboss.resteasy.core.registry.ClassNode.match(ClassNode.java:70)
        at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:47)
        at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:481)
        at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:332)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:253)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)`

### Expected behavior
Work in the same way that the dev build works.

### Actual behavior
(Describe the actual behavior clearly and concisely.)

## To Reproduce

1. Use a class `@ApplicationPath(value = "/api")
class RestApplicationConfig : Application()` to modify your baseURL
2. Run the module without the :dev mode.
3. Observe the logs.

### Output of `java -version`
Java version: 13.0.1

### GraalVM version (if different from Java)
graalvm-ce-java11-20.2.0

### Quarkus version or git rev
1.12.2.Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3

## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Is this still a problem with the latest versions of Quarkus?

**Comment by geoand** [comment]
Closing as we never got feedback
