### ISSUE TITLE
Maven 3.8.1 update causes warning

### ISSUE THREAD

**Issue by fwgreen** [quarkusio/quarkus#16233]
Maven was recently updated from 3.6.3 to 3.8.1 to address [a security vulnerability](https://maven.apache.org/docs/3.8.1/release-notes.html).  As a result, this warning now comes up on startup...
```
2021-04-04 19:02:43,763 WARN  [io.qua.boo.res.mav.BootstrapMavenContext] (main) Settings problem encountered at /Users/francois/Libraries/Java/apache-maven/conf/settings.xml, line 164, column 16: org.apache.maven.settings.io.SettingsParseException: Unrecognised tag: 'blocked' (position: START_TAG seen ...</url>\r\n      <blocked>... @164:16) 
        at org.apache.maven.settings.io.DefaultSettingsReader.read(DefaultSettingsReader.java:87)
        at org.apache.maven.settings.building.DefaultSettingsBuilder.readSettings(DefaultSettingsBuilder.java:182)
        at org.apache.maven.settings.building.DefaultSettingsBuilder.build(DefaultSettingsBuilder.java:104)
        at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getEffectiveSettings(BootstrapMavenContext.java:252)
        at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.isOffline(BootstrapMavenContext.java:218)
        at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.newRepositorySystem(BootstrapMavenContext.java:648)
        at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getRepositorySystem(BootstrapMavenContext.java:223)
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:125)
        at io.quarkus.bootstrap.BootstrapAppModelFactory.getAppModelResolver(BootstrapAppModelFactory.java:192)
        at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:305)
        at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:163)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:143)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unrecognised tag: 'blocked' (position: START_TAG seen ...</url>\r\n      <blocked>... @164:16) 
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.checkUnknownElement(SettingsXpp3Reader.java:149)
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.parseMirror(SettingsXpp3Reader.java:920)
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.parseSettings(SettingsXpp3Reader.java:1416)
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:1544)
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:566)
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:595)
        at org.apache.maven.settings.io.DefaultSettingsReader.read(DefaultSettingsReader.java:83)
        ... 12 more
```

Quarkus 1.12.1
Java 16

**Comment by srisatya1197** [comment]
@fwgreen Sir I want work on this issue .

**Comment by famod** [comment]
@srisatya1197 Thanks for your offer (really appreciated!) but I have already started to work on this in general, including an update of the Quarkus CI.
See also this discussion I have just started: https://groups.google.com/g/quarkus-dev/c/A-cm9pvviiE

/cc @aloubyansky

**Comment by cescoffier** [comment]
The issue is about a change in mavne blocking insecure repositories by default. Check that all your repositories are in `https` (<--- s) and not `http`

**Comment by geoand** [comment]
I ran into this locally as well and all I had to do was comment out the 

```xml
    <mirror>
      <id>maven-default-http-blocker</id>
      <mirrorOf>external:http:*</mirrorOf>
      <name>Pseudo repository to mirror external repositories initially using HTTP.</name>
      <url>http://0.0.0.0/</url>
      <blocked>true</blocked>
    </mirror>
```

block in my `conf/settings.xml` file
