### ISSUE TITLE
Possible Connection leak, very specific environment.

### ISSUE THREAD

**Issue by apat59** [quarkusio/quarkus#16279]
## Describe the bug
Quite quick and linear connection leak, see metrics. 

![Capture d’écran du 2021-04-01 08-33-32](https://user-images.githubusercontent.com/5196977/113718813-4e4cbe80-96ed-11eb-8e08-e92c954020f7.png)

### Expected behavior
Available count and max used count should stick to 10, the db load is pretty low and must not increase that way.

### Actual behavior
Check grafana screenshot.

## To Reproduce
Almost impossible to reproduce in a classic system with a local db.

This behavior only appears in (paas (openshift) and/or specific db server version (local is 10, the failing environment is 11) and only with specific configuration
One or a combination of the following is triggering the problem, if we don't use the following, the problem disappears.
#quarkus.datasource.jdbc.leak-detection-interval=100
#quarkus.datasource.jdbc.idle-removal-interval=120
#quarkus.datasource.jdbc.max-lifetime=150
#quarkus.datasource.jdbc.detect-statement-leaks=true
#quarkus.datasource.jdbc.new-connection-sql=select 1;

1. Just start the app and observe metrics

### Configuration
The focus should be on these props
```properties
#quarkus.datasource.jdbc.leak-detection-interval=100
#quarkus.datasource.jdbc.idle-removal-interval=120
#quarkus.datasource.jdbc.max-lifetime=150
#quarkus.datasource.jdbc.detect-statement-leaks=true
#quarkus.datasource.jdbc.new-connection-sql=select 1;
```

### Screenshots
![Capture d’écran du 2021-04-01 08-33-32](https://user-images.githubusercontent.com/5196977/113718813-4e4cbe80-96ed-11eb-8e08-e92c954020f7.png)

## Environment (please complete the following information):
Openshift 

### Output of `uname -a` or `ver`
db server : PostgreSQL 11.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit
(1 row)

pod running the quarkus app
Linux  3.10.0-1160.2.2.el7.x86_64 #1 SMP Sat Oct 17 05:06:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
sh-4.2$ java -version
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9-LTS, mixed mode, sharing

### Quarkus version or git rev
Tried with 1.12.1 and 1.13.0
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

## Additional context
Unfortunately we thought the leak was coming from our code, we spent a lot of time figuring out it was coming from the config.
Agroal is logging nothing and didn't help much providing more info.
We tried the interceptor, but wasn't helpful to greb more info.
Our app uses many job and @ActivateRequestContext might be involved here but we have no clue and no more time to debug this.

We wanted to let you know in case other users report the same kind of problem.
Since we removed the listed properties above, the problem fully disappeared.

### PROD running 2.2.2.Final, working around the "issue" (pods up for 22 days)
This is PROD env, similar to QA, except it has a real DB workload.
```
<quarkus.platform.version>2.2.2.Final</quarkus.platform.version>
# DATASOURCE
quarkus.datasource.db-kind=postgresql
quarkus.datasource.health.enabled=false
quarkus.datasource.metrics.enabled=true
quarkus.transaction-manager.default-transaction-timeout=60
#trying to tune the db pool
quarkus.datasource.jdbc.min-size=6
quarkus.datasource.jdbc.initial-size=6
quarkus.datasource.jdbc.max-size=70
quarkus.datasource.jdbc.background-validation-interval=15S
quarkus.datasource.jdbc.foreground-validation-interval=15S
quarkus.datasource.jdbc.validation-query-sql=select 1;
quarkus.datasource.jdbc.acquisition-timeout=5
quarkus.datasource.jdbc.idle-removal-interval=5M
quarkus.datasource.jdbc.detect-statement-leaks=true
quarkus.datasource.jdbc.new-connection-sql=select 1;
#quarkus.datasource.jdbc.pooling-enabled=false
# NOTE, we may have to change that in the future
quarkus.datasource.jdbc.driver=org.postgresql.ds.PGSimpleDataSource
#quarkus.datasource.jdbc.driver=software.aws.rds.jdbc.postgresql.Driver
```
And here are the metrics, quite stable
![2 2 2 workaround](https://user-images.githubusercontent.com/5196977/155489838-57ae54c0-4cab-4a22-b696-063639c0eced.png)

### QA running 2.7.2.Final, specific pool config
This is QA, the app has almost zero db workload.

In order to trigger the issue, here are the params I’ve set
```
# uncomment to trigger the pool issue
%qa.quarkus.datasource.health.enabled=true
%qa.quarkus.datasource.jdbc.max-size=15
%qa.quarkus.datasource.jdbc.max-lifetime=1M
%qa.quarkus.datasource.jdbc.background-validation-interval=15S
%qa.quarkus.datasource.jdbc.foreground-validation-interval=15S
```
Which are params you want to set (with higher values) in PROD in order to make your pool more reliable.

And here are the metrics, seems max_used is broken and since it's bound to max-size, that used to cause big troubles (JDBC exceptions (org.postgresql.util.PSQLException: This connection has been clo
sed.), the healthcheck used to return DOWN, .... However 2.7.2 is not triggering these fatal problems, at least not after 1h run. Still, this is very confusing. It's hard to predict what can happen if a connection breaks, is closed at the db server level after the pool acts as if its max size was reached.

![2 7 2 Final issue](https://user-images.githubusercontent.com/5196977/155489841-fc5ad8e3-1e2c-485d-98c5-cf0e8347dad5.png)

Unlike the initial post, this behavior can now be observed in a local environment with a classic postgres server.
And finally trigger
```
Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.prepareQueryStatement(AbstractLoadPlanBasedLoader.java:198)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeQueryStatement(AbstractLoadPlanBasedLoader.java:162)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:104)
        at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:285)
        at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:267)
        at org.hibernate.loader.entity.plan.PaddedBatchingEntityLoader.load(PaddedBatchingEntityLoader.java:86)
        at org.hibernate.persister.entity.AbstractEntityPersister.doLoad(AbstractEntityPersister.java:4521)
        at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4511)
        at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:571)
        at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:539)
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:208)
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:327)
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:108)
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:74)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventLisoupImpl.java:118)
        at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1226)
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1215)
        at org.hibernate.internal.SessionImpl.access$2100(SessionImpl.java:201)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2830)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2807)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2763)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2807)
        at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3395)
        ... 49 more
Caused by: java.sql.SQLException: Sorry, acquisition timeout!
        at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:294)
        at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:242)
        at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
        at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
        at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108)
        ... 77 more
```

**Comment by geoand** [comment]
cc @Sanne

**Comment by Sanne** [comment]
cc @barreiro - does it ring any bell?

**Comment by barreiro** [comment]
@apat59 Agroal `1.10` introduced on Quarkus `1.13.1` comes with improved leak detection. Unfortunately there is still some more work to be done on the Quarkus side to enable that feature, so stay tuned for that.

One possible cause for the leak could be [AG-154](https://issues.redhat.com/browse/AG-154) that is fixed in the same version.

**Comment by apat59** [comment]
check updated "Describe the bug section"
Reproducer being  quartz-quickstart
with the following params
quarkus.datasource.metrics.enabled=true
%dev.quarkus.datasource.health.enabled=true
%dev.quarkus.datasource.jdbc.max-size=15
%dev.quarkus.datasource.jdbc.max-lifetime=10S
%dev.quarkus.datasource.jdbc.background-validation-interval=2S
%dev.quarkus.datasource.jdbc.foreground-validation-interval=2S

**Comment by apat59** [comment]
bad news, the reproducer is not reliable.
The source of the problem for the reproducer is foreground-validation-interval, if you remove it, the problem on a local machine disappear. However it continues in the other environment openshift + aurora..

No idea what I can do. There seems to be a gap as soon as I move to openshift + aurora cluster

**Comment by geoand** [comment]
Is this still an issue with the Quarkus 3.2.z?

**Comment by geoand** [comment]
Closing for lack of feedback

**Comment by apat59** [comment]
sorry for the late answer mates I was on holidays and totally forgot to comment.
We haven't upgraded to 3.x yet.
If we observe a potential leak in the future, I'll reopen an issue.
Thanks.

**Comment by geoand** [comment]
Thanks
