### ISSUE TITLE
Qute deployment errors with template parameter declaration of concrete classes and usage of default methods

### ISSUE THREAD

**Issue by Maldivia** [quarkusio/quarkus#16337]
## Describe the bug
Given the following example classes:
```
package org.acme;
public class Name implements Something {
    public String name() {
        return "Name";
    }
}
```

```
package org.acme;
public interface Something {
    String name();
    default String fullName() {
        return name() + " Surname";
    }
}
```

And the following template:
```
{@org.acme.Name name}
Hello {name.fullName}
```

Running `mvn quarkus:dev` fails with the following error:
```
[error]: Build step io.quarkus.qute.deployment.QuteProcessor#processTemplateErrors threw an exception: io.quarkus.qute.TemplateException: Found template problems (1):
[1] Incorrect expression found: {name.fullName}
        - property/method [fullName] not found on class [org.acme.Name] nor handled by an extension method
        - at main.html:2
        at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:195)
(...)
        Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {name.fullName}
        - property/method [fullName] not found on class [org.acme.Name] nor handled by an extension method
        - at main.html:2
                at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:175)
                ... 10 more
```

If I change the templated to use the interface instead, it works as expected:
```
{@org.acme.Something name}
Hello {name.fullName}
```

mvn version: Apache Maven 3.8.1 
java version: build 11.0.10+9
quarkus-plugin.version: 1.13.1.Final
quarkus.platform.version: 1.13.1.Final

**Comment by mkouba** [comment]
It's the default method that was not handled correctly.
