### ISSUE TITLE
graphql schema creator throws java.lang.NullPointerException when Query return type has a List<T> or an array.

### ISSUE THREAD

**Issue by okothhc** [quarkusio/quarkus#16364]
When graphql query has a return type that has a list or an array object in it, a null pointer exception is raised in io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:275)

Sample code:
@GraphQLApi
class CoreResource {

@Query("listxyz")
    @Description("Lists the xyz")
    fun listXyz(@Name("code") code: String) :
        CompletionStage<ServerResponse<**List<XyzPayload>**>>
            = xyzService.list()
}

A look at the source code https://github.com/smallrye/smallrye-graphql/blob/a3b2143c5671ccd5ad01b8dc1046f27af2d8b7ed/common/schema-builder/src/main/java/io/smallrye/graphql/schema/creator/ReferenceCreator.java#L355 which invokes getReference(direction, pat, null, null, parentObjectReference) passes null for _Type methodType_ parameter.

The null that is passed in line 355 thus leads to null pointer exception being raised at line 275 https://github.com/smallrye/smallrye-graphql/blob/a3b2143c5671ccd5ad01b8dc1046f27af2d8b7ed/common/schema-builder/src/main/java/io/smallrye/graphql/schema/creator/ReferenceCreator.java#L275 when it is invoked.

_Type typeInMethodCollection = methodType.asParameterizedType().arguments().get(0);_ (line 275 consumes methodType that was passed as null in line 355, thus null pointer is an obvious result)

### Expected behavior
Line 355 should not pass null for methodType or it should invoke the right method that will not lead to NPE

### Actual behavior
Null pointer Exception is raised.

### Quarkus version or git rev
<properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <kotlin.version>1.4.31</kotlin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <quarkus-plugin.version>1.13.1.Final</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>1.13.1.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: C:\Program Files\apache-maven-3.6.3\bin\..
Java version: 11.0.9, vendor: GraalVM Community, runtime: C:\Program Files\graalvm-ce-java11-20.3.0
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

## Additional context
Is there e version that has the fix?

**Comment by phillip-kruger** [comment]
I think the issue is actually Generics (ServerResponse). Maybe @velias can comment ?

**Comment by okothhc** [comment]
Not sure if this is helpful, but, others that return ServerResponse<class instance> works just fine. @phillip-kruger is there a workaround you would recommend?

**Comment by velias** [comment]
Have you tried to add type for that List? Without type graphql schema can't be finished as it requires types everywhere.

**Comment by okothhc** [comment]
Yes, I believe I did. 

This fails. The variants for Array and Collections also fails.
`@Query("listSubscriber")
    @Description("Lists the subscribers")
    fun listSubscriber(@Name("code") code: String) :
        CompletionStage<ServerResponse<List<SubscriberPayload>>>
            = subsciberService.list()`

This works fine.
`@Query("getSubscriberByCode")
    @Description("Gets the subscriber by assigned code")
    fun getSubscriberByCode(@Name("code") code: String) :
        ServerResponse<SubscriberPayload> =
            subsciberService.findByCode(code)`

**Comment by okothhc** [comment]
Caused by: java.lang.NullPointerException
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:275)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.collectParametrizedTypes(ReferenceCreator.java:356)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:310)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:276)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:245)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForOperationField(ReferenceCreator.java:95)
        at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:70)
        at io.smallrye.graphql.schema.SchemaBuilder.addOperations(SchemaBuilder.java:229)
        at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:107)
        at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:80)
        at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:170)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

**Comment by okothhc** [comment]
Created issue https://github.com/smallrye/smallrye-graphql/issues/740 Closing this issue. Thanks!
