### ISSUE TITLE
Multi-Module Project with SOAP clients fail with circular reference error

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#16394]
Describe the bug
As of 1.13.X , multi-module projects with soap clients fail when initiating the client:

javax.xml.catalog.CatalogException: JAXP09010001: Circular reference is not allowed: 'jax-ws-catalog.xml'.
	at java.xml/javax.xml.catalog.CatalogMessages.reportRunTimeError(CatalogMessages.java:84)
	at java.xml/javax.xml.catalog.GroupEntry.verifyCatalogFile(GroupEntry.java:528)
	at java.xml/javax.xml.catalog.CatalogImpl.getCatalog(CatalogImpl.java:444)
	at java.xml/javax.xml.catalog.CatalogImpl$1.nextCatalog(CatalogImpl.java:380)
	at java.xml/javax.xml.catalog.CatalogImpl$1.hasNext(CatalogImpl.java:345)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at java.xml/javax.xml.catalog.Util.resolve(Util.java:103)
	at java.xml/javax.xml.catalog.CatalogResolverImpl.resolveEntity(CatalogResolverImpl.java:88)
	at com.sun.xml.ws.wsdl.parser.EntityResolverWrapper.resolveEntity(EntityResolverWrapper.java:43)
	at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.resolveWSDL(RuntimeWSDLParser.java:348)
	at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:201)
	at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:179)
	at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:148)
	at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:334)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:292)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:201)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:182)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:178)
	at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:89)
	at javax.xml.ws.Service.<init>(Service.java:82)

Expected behavior
Soap client should init and work fine as it does with 1.12.2.Final and before

Actual behavior
As above

To Reproduce
git clone https://github.com/bcluap/quarkus-examples.git
cd quarkus-examples/soap
mvn clean install -DskipTests
java -jar ./runnable/target/quarkus-app/quarkus-run.jar

Note the error when the soap client in the second module fails.

Configuration
Nothing abnormal. This error does not happen when running in dev mode so seems to be related to the fast jar packaging.

Screenshots
Run the reproducer

Environment (please complete the following information):
1.13.X +

**Comment by bcluap** [comment]
FYI I've worked around the issue by making the jax-ws-catalog.xml file names unique in each sub module. E.g. jax-ws-catalog-1.xml and jax-ws-catalog-2.xml

So must be related to finding resources on the classpath and getting conflicts if the same file name sits in the same relative path in 2 different jars. Its fine for me now that I have a workaround but this could cause issues for other use cases

**Comment by mkouba** [comment]
CC @aloubyansky

**Comment by aloubyansky** [comment]
I don't see this error with 2.14.2.Final. @bcluap please let us know in case there is still an issue. Thanks.
