### ISSUE TITLE
Endless "VertxException: Thread blocked"

### ISSUE THREAD

**Issue by antoniomacri** [quarkusio/quarkus#16390]
## Describe the bug

On one node in our Production environment the application started logging "Thread blocked" continuously.

### Expected behavior

A possibly temporary condition that caused the block is recovered from.

### Actual behavior

This warning is logged continuously on one node:

```
06/04/2021 04:00:59,158 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-worker-thread-5,5,main]=Thread[vert.x-worker-thread-5,5,main] has been blocked for 181444 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:447)
	at java.base@11.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
	at app//io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:262)
	at app//io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:200)
	at app//io.agroal.pool.DataSource.getConnection(DataSource.java:81)
	at app//io.quarkus.agroal.runtime.health.DataSourceHealthCheck.call(DataSourceHealthCheck.java:47)
	at app//io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy.call(DataSourceHealthCheck_ClientProxy.zig:154)
	at app//io.smallrye.health.AsyncHealthCheckFactory$$Lambda$868/0x0000000100b03440.get(Unknown Source)
	at app//io.smallrye.mutiny.groups.UniCreate.lambda$item$2(UniCreate.java:201)
	at app//io.smallrye.mutiny.groups.UniCreate$$Lambda$859/0x0000000100b05040.accept(Unknown Source)
	at app//io.smallrye.mutiny.operators.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:22)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at app//io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$239/0x0000000100518440.run(Unknown Source)
	at app//io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at app//io.smallrye.context.SmallRyeThreadContext$$Lambda$216/0x0000000100481c40.execute(Unknown Source)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at app//io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at app//io.smallrye.mutiny.operators.UniOnFailureFlatMap.subscribing(UniOnFailureFlatMap.java:29)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at app//io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$239/0x0000000100518440.run(Unknown Source)
	at app//io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at app//io.smallrye.context.SmallRyeThreadContext$$Lambda$216/0x0000000100481c40.execute(Unknown Source)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at app//io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at app//io.smallrye.mutiny.operators.UniOnItemTransform.subscribing(UniOnItemTransform.java:19)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at app//io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$239/0x0000000100518440.run(Unknown Source)
	at app//io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at app//io.smallrye.context.SmallRyeThreadContext$$Lambda$216/0x0000000100481c40.execute(Unknown Source)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at app//io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$239/0x0000000100518440.run(Unknown Source)
	at app//io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at app//io.smallrye.context.SmallRyeThreadContext$$Lambda$216/0x0000000100481c40.execute(Unknown Source)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at app//io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at app//io.smallrye.mutiny.operators.UniAndCombination$UniHandler.subscribe(UniAndCombination.java:199)
	at app//io.smallrye.mutiny.operators.UniAndCombination$AndSupervisor$$Lambda$875/0x0000000100b28040.accept(Unknown Source)
	at java.base@11.0.1/java.util.ArrayList.forEach(ArrayList.java:1540)
	at app//io.smallrye.mutiny.operators.UniAndCombination$AndSupervisor.run(UniAndCombination.java:68)
	at app//io.smallrye.mutiny.operators.UniAndCombination$AndSupervisor.access$000(UniAndCombination.java:50)
	at app//io.smallrye.mutiny.operators.UniAndCombination.subscribing(UniAndCombination.java:47)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at app//io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$239/0x0000000100518440.run(Unknown Source)
	at app//io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at app//io.smallrye.context.SmallRyeThreadContext$$Lambda$216/0x0000000100481c40.execute(Unknown Source)
	at app//io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at app//io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at app//io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at app//io.smallrye.mutiny.operators.UniBlockingAwait.await(UniBlockingAwait.java:48)
	at app//io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
	at app//io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:262)
	at app//io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:183)
	at app//io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getHealth(SmallRyeHealthReporter_ClientProxy.zig:306)
	at app//io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.getHealth(SmallRyeHealthHandler.java:11)
	at app//io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.doHandle(SmallRyeHealthHandlerBase.java:38)
	at app//io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:29)
	at app//io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.handle(SmallRyeHealthHandler.java:7)
	at app//io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:17)
	at app//io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at app//io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$865/0x0000000100b03840.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$867/0x0000000100b03040.run(Unknown Source)
	at java.base@11.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.1/java.lang.Thread.run(Thread.java:834)
```

The other 4 nodes are fine. Vert.x is not even listening:

```
curl: (7) Failed to connect to <host> port 8084: Connection refused
```

## To Reproduce

Sorry, I don't have a reproducer.

### Configuration

I have different datasources configured: Oracle, Postgres, Other (Netezza)

### Output of `java -version`

Java 11

### Quarkus version or git rev

Quarkus 1.8.3

**Comment by geoand** [comment]
Does this happen with newer Quarkus versions? Quarkus `1.8.x` is rather old at this point...

**Comment by antoniomacri** [comment]
Hi @geoand, I don't know, unfortunately I'm still on that version, but I never detected this problem before.

Do you think something changed in newer versions that could avoid such a problem?

**Comment by geoand** [comment]
A lot of things have changed in the meantime that could affect this

**Comment by cescoffier** [comment]
Health checks are executed on the worker thread, so should be fine in recent versions.

**Comment by cescoffier** [comment]
Closing - please reopen if it still happens on more recent versions.

**Comment by antoniomacri** [comment]
Hi @cescoffier, it also happens in 1.13.7.Final.

The stacktrace seems the same:
```
05/08/2021 09:10:57,723 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-worker-thread-12,5,executor]=Thread[vert.x-worker-thread-12,5,executor] has been blocked for 597066 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:447)
	at java.base@11.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
	at app//io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:280)
	at app//io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:241)
	at app//io.agroal.pool.DataSource.getConnection(DataSource.java:81)
	at app//io.quarkus.agroal.runtime.health.DataSourceHealthCheck.call(DataSourceHealthCheck.java:47)
	at app//io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy.call(DataSourceHealthCheck_ClientProxy.zig:126)
	at app//io.smallrye.health.AsyncHealthCheckFactory$$Lambda$1420/0x0000000100b83440.get(Unknown Source)

```

But in this case, while the health check is not responding, application endpoints are working fine.

**Comment by cescoffier** [comment]
It looks like you are accessing the database from an I/O thread.

**Comment by antoniomacri** [comment]
I was doing:

    @Incoming("mychannel")
    @Acknowledgment(Acknowledgment.Strategy.PRE_PROCESSING)
    public CompletionStage<Void> incomingData(KafkaRecord<GiornataNegozio, CountValue> counter) {
        return managedExecutor.runAsync(threadContext.contextualRunnable(() -> {
            blockingRepo.save(counter);
        }));
    }

Now it is:

    @Blocking
    @Incoming("mychannel")
    @Acknowledgment(Acknowledgment.Strategy.PRE_PROCESSING)
    public CompletionStage<Void> incomingData(KafkaRecord<GiornataNegozio, CountValue> counter) {
        blockingRepo.save(counter);
        return CompletableFuture.completedFuture(null);
    }

Do you see any problem?

I'm getting threads blocked with both forms.

Also with Quarkus 2.0:

```
23/08/2021 03:10:50,832 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-worker-thread-15,5,main]=Thread[vert.x-worker-thread-15,5,main] has been blocked for 132268966 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:447)
	at java.base@11.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
	at app//io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:280)
	at app//io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:241)
	at app//io.agroal.pool.DataSource.getConnection(DataSource.java:81)
	at app//io.quarkus.agroal.runtime.health.DataSourceHealthCheck.call(DataSourceHealthCheck.java:47)
	at app//io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy.call(DataSourceHealthCheck_ClientProxy.zig:126)
```

**Comment by cescoffier** [comment]
The error you are seing means that while because by on a worker thread, the operation is taken a LOT of time and so report this abnormal operation. For very long operation, I would recommend using a dedicated thread pool.

**Comment by antoniomacri** [comment]
Hi Clement, but the error I see is on Agroal datasource health check, all the blocked threads are stuck there.

**Comment by cescoffier** [comment]
Yes, I can't help around Agroal, but from what I can see, if can't get a connection, meaning that all connections are used.

**Comment by aggarwalchirag** [comment]
I am also getting the same issue. Quarkus version: 1.13.0-Final. This comes when I call up the health check api at an interval of 10 sec. Everything is running fine, and then randomly I start getting this error.

2023-02-15 01:15:13 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) {} Thread Thread[vert.x-worker-thread-16,5,main]=Thread[vert.x-worker-thread-16,5,main] has been blocked for 60533 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@13-ea/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@13-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@13-ea/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:447)
	at java.base@13-ea/java.util.concurrent.FutureTask.get(FutureTask.java:190)
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:258)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:219)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:81)
	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck.call(DataSourceHealthCheck.java:47)
	at io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy.call(DataSourceHealthCheck_ClientProxy.zig:126)
	at io.smallrye.health.AsyncHealthCheckFactory$$Lambda$395/0x0000000800fe0840.get(Unknown Source)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniAndCombination$UniHandler.subscribe(UniAndCombination.java:203)
	at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor$$Lambda$402/0x0000000800fe2440.accept(Unknown Source)
	at java.base@13-ea/java.util.ArrayList.forEach(ArrayList.java:1507)
	at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.run(UniAndCombination.java:71)
	at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.access$000(UniAndCombination.java:53)
	at io.smallrye.mutiny.operators.uni.UniAndCombination.subscribe(UniAndCombination.java:50)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:54)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
	at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:256)
	at io.smallrye.health.SmallRyeHealthReporter.getReadiness(SmallRyeHealthReporter.java:185)
	at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getReadiness(SmallRyeHealthReporter_ClientProxy.zig:396)
	at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.getHealth(SmallRyeReadinessHandler.java:11)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.doHandle(SmallRyeHealthHandlerBase.java:38)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:29)
	at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.handle(SmallRyeReadinessHandler.java:7)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:17)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$392/0x0000000800f71440.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.ContextImpl$$Lambda$394/0x0000000800fe0040.run(Unknown Source)
	at java.base@13-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@13-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@13-ea/java.lang.Thread.run(Thread.java:830)
