### ISSUE TITLE
Regression issue: Reactive and Vertx JWT stopped working

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#16392]
## Describe the bug
When using Reactive routes and authenticating the app using the Vertx jwt dependency, the app fails when calling to the service:

```
2021-04-09 14:12:36,281 ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-1) Mutiny had to drop the following exception: java.lang.AssertionError
	at io.netty.buffer.PoolChunk.calculateRunSize(PoolChunk.java:366)
	at io.netty.buffer.PoolChunk.allocateSubpage(PoolChunk.java:424)
	at io.netty.buffer.PoolChunk.allocate(PoolChunk.java:299)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:205)
	at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:174)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:136)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:128)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:378)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	at io.vertx.core.net.impl.PartialPooledByteBufAllocator.directBuffer(PartialPooledByteBufAllocator.java:92)
	at io.netty.channel.nio.AbstractNioChannel.newDirectBuffer(AbstractNioChannel.java:442)
	at io.netty.channel.nio.AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:278)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:878)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:180)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:230)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:215)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:211)
	at io.vertx.core.net.impl.NetSocketImpl.writeMessage(NetSocketImpl.java:135)
	at io.vertx.core.net.impl.NetSocketImpl.write(NetSocketImpl.java:191)
	at io.vertx.core.net.impl.NetSocketImpl.write(NetSocketImpl.java:186)
	at io.vertx.redis.client.impl.RedisStandaloneConnection.lambda$send$1(RedisStandaloneConnection.java:155)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:73)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:287)
	at io.vertx.core.impl.AbstractContext.execute(AbstractContext.java:54)
	at io.vertx.redis.client.impl.RedisStandaloneConnection.send(RedisStandaloneConnection.java:143)
	at io.vertx.redis.client.impl.PooledRedisConnection.send(PooledRedisConnection.java:68)
	at io.vertx.redis.client.impl.BaseRedisClient.lambda$send$1(BaseRedisClient.java:43)
	at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:90)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:230)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
	at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:83)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:199)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
	at io.vertx.core.net.impl.clientconnection.Endpoint.lambda$getConnection$0(Endpoint.java:52)
	at io.vertx.redis.client.impl.RedisConnectionManager$RedisEndpoint.lambda$requestConnection$1(RedisConnectionManager.java:345)
	at io.vertx.core.net.impl.clientconnection.Pool.connectSucceeded(Pool.java:387)
	at io.vertx.core.net.impl.clientconnection.Pool.access$500(Pool.java:89)
	at io.vertx.core.net.impl.clientconnection.Pool$Holder.lambda$connect$0(Pool.java:143)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:73)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:287)
	at io.vertx.redis.client.impl.RedisConnectionManager$RedisConnectionProvider.lambda$null$2(RedisConnectionManager.java:183)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:73)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:287)
	at io.vertx.redis.client.impl.RedisConnectionManager$RedisConnectionProvider.setup(RedisConnectionManager.java:263)
	at io.vertx.redis.client.impl.RedisConnectionManager$RedisConnectionProvider.lambda$null$3(RedisConnectionManager.java:177)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:73)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:287)
	at io.vertx.redis.client.impl.RedisConnectionManager$RedisConnectionProvider.select(RedisConnectionManager.java:248)
	at io.vertx.redis.client.impl.RedisConnectionManager$RedisConnectionProvider.lambda$init$4(RedisConnectionManager.java:170)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:73)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:287)
	at io.vertx.redis.client.impl.RedisConnectionManager$RedisConnectionProvider.lambda$hello$5(RedisConnectionManager.java:211)
// ...
```

I could not find out what is the root cause of the problem as we're also using the Quarkus Redis extension, but I've provided a reproducer for better understading.

This must be a regression issue with the upgrade of Vertx 4.

## To Reproduce

1. git clone https://github.com/Sgitario/beefy-scenarios
2. cd beefy-scenarios
3. git checkout reproducer_vertx_jwt
4. cd 302-quarkus-vertx-jwt
5. mvn clean verify -Dtest=BladeRunnerHandlerTest#retrieveBladeRunnerById -> it will fail

### Quarkus version or git rev
999-SNAPSHOT

**Comment by Sgitario** [comment]
I've found out the cause of this issue. Closing...

**Comment by gsmet** [comment]
@Sgitario what is the cause?

**Comment by Sgitario** [comment]
> @Sgitario what is the cause?

Vertx JWT has changed the API to generate tokens and I was not using the right `buffer` value.

**Comment by gsmet** [comment]
Shouldn't we use SmallRye JWT Build to generate tokens?

**Comment by Sgitario** [comment]
> Shouldn't we use SmallRye JWT Build to generate tokens?

We have other test cases that cover the usage of the SmallRye JWT and also the OIDC Token extensions.
