### ISSUE TITLE
Job "Native Tests - Windows - hibernate-validator" fails very often with: unable to load mspdbcore.dll

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#16416]
E.g. here: https://github.com/quarkusio/quarkus/runs/2309028360
```
LINK : fatal error LNK1171: unable to load mspdbcore.dll (error code: 1455)
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.handleLinkerFailure(NativeBootImageViaCC.java:474)
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:441)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:685)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

**Comment by famod** [comment]
Let's assume #16423 fixed it for good. If not then we can always reopen this issue.
/cc @gsmet

**Comment by famod** [comment]
Still happens: https://github.com/quarkusio/quarkus/pull/16533#issuecomment-820324489

**Comment by famod** [comment]
Haven't seen this fail for a while, closing. /cc @gsmet
