### ISSUE TITLE
PgPool is closed in test

### ISSUE THREAD

**Issue by geniusit** [quarkusio/quarkus#16479]
## Describe the bug
Hello, 
During my JUnit test, the PgPool switch to closed after the first request.

### Expected behavior
The PgPool should keep opened.

### Actual behavior
the PgPool is closed after the first request.

## To Reproduce
Here is the function I try to test : 
```java
public static Uni<BaselineDevice> get(final PgPool client, final String equipmentLabel, final String series){
        return BaselineDevice.findByEquipment( client, equipmentLabel, series )
                .onItem()
                .ifNull()
                .switchTo(
                        () ->
                                BaselineDevice.create(
                                        client,
                                        equipmentLabel,
                                        equipmentLabel.contains(CrossingConstants.GSMR_EQUIPMENT)
                                                ?
                                                CrossingConstants.GSMR_EQUIPMENT
                                                :
                                                equipmentLabel.contains(CrossingConstants.KVB_EQUIPMENT)
                                                        ?
                                                        CrossingConstants.KVB_EQUIPMENT
                                                        :
                                                        CrossingConstants.MID_EQUIPMENT
                                )
                )
                .onItem()
                .transformToUni(
                        created ->
                                BaselineDevice.findByEquipment(
                                        client,
                                        equipmentLabel,
                                        series
                                )
                );
    }
```

Here is my test : 
```java
@QuarkusTest
@Slf4j
class BaselineDeviceTest {

    @Inject
    PgPool client;

    @Test
    void test(){

        final Uni<BaselineDevice> baselineDeviceUni =
                BaselineDevice
                        .get(
                                client,
                                "test",
                                "test"
                        )
                ;

        baselineDeviceUni
                .subscribe()
                .with(
                        s -> log.info("success : {}", s),
                        e -> log.info("b : {}", e)
                );
    }
}
```

I try to test the 

```java
.ifNull()
                .switchTo(
                        () ->
                                BaselineDevice.create(....
```

part of the function. However I got this error even if the first request (BaselineDevice.findByEquipment(...)) has been successfully done.

```java
2021-04-13 15:23:13,642 INFO  [snc.mob.gro.myt.dom.BaselineDeviceTest] (vert.x-eventloop-thread-1) b : {}: java.lang.IllegalStateException: This Pool has been closed
	at io.quarkus.reactive.datasource.runtime.ThreadLocalPool.checkPoolIsOpen(ThreadLocalPool.java:92)
	at io.quarkus.reactive.datasource.runtime.ThreadLocalPool.pool(ThreadLocalPool.java:60)
	at io.quarkus.reactive.datasource.runtime.ThreadLocalPool.preparedQuery(ThreadLocalPool.java:114)
	at io.vertx.mutiny.sqlclient.Pool.preparedQuery(Pool.java:149)
	at io.vertx.mutiny.pgclient.PgPool_2d3061477c44a6b700dc3f9c4fe453a846636193_Synthetic_ClientProxy.preparedQuery(PgPool_2d3061477c44a6b700dc3f9c4fe453a846636193_Synthetic_ClientProxy.zig:323)
	at sncf.mobilite.groupehv.mytraindata.domain.BaselineDevice.create(BaselineDevice.java:93)
	at sncf.mobilite.groupehv.mytraindata.domain.BaselineDevice.lambda$get$0(BaselineDevice.java:26)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.groups.UniOnNull.lambda$switchTo$3(UniOnNull.java:98)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
	at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:34)
	at io.vertx.mutiny.sqlclient.PreparedQuery$2.handle(PreparedQuery.java:119)
	at io.vertx.mutiny.sqlclient.PreparedQuery$2.handle(PreparedQuery.java:116)
	at io.vertx.sqlclient.impl.SqlResultHandler.complete(SqlResultHandler.java:98)
	at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:87)
	at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:33)
	at io.vertx.sqlclient.impl.PoolBase$1.lambda$onSuccess$0(PoolBase.java:90)
	at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:241)
	at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:88)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:97)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:356)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:164)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:78)
	at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:138)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:235)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:95)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

2021-04-13 15:23:16,472 INFO  [io.quarkus] (main) Quarkus stopped in 3.161s
Generated Jacoco reports in C:\dev\workspace\mytraindata\crossing-series\target\jacoco-report

Process finished with exit code 0

```

Why the PgPool switch to closed ?

### Configuration
```properties
quarkus.http.test-port=8016
quarkus.datasource.db-kind=postgresql

%test.quarkus.datasource.username=xxxx
%test.quarkus.datasource.password=yyyy
%test.quarkus.datasource.reactive.url=postgresql://myserer.com/testdb

```
## Environment (please complete the following information):
only with %test

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
maven 3

Thanx!

**Comment by gsmet** [comment]
Any chance you could prepare a small Maven reproducer? That would help a lot!

**Comment by geniusit** [comment]
[getting-started.zip](https://github.com/quarkusio/quarkus/files/6305417/getting-started.zip)

Here is, but you can't reproduce the error until you have a relevant connection to my database...
It can't be reproduced with the "automatic dockerized database"

On my laptop, when I type the mvn clean install command, I get the following error : 

```java
2021-04-13 19:03:59,625 INFO  [snc.mob.gro.myt.dom.BaselineDevice] (vert.x-eventloop-thread-1) Equipment : test not found for equipment type test - Start creation ...
2021-04-13 19:03:59,627 INFO  [snc.mob.gro.myt.dom.BaselineDeviceTest] (vert.x-eventloop-thread-1) b : {}: java.lang.IllegalStateException: This Pool has been closed
        at io.quarkus.reactive.datasource.runtime.ThreadLocalPool.checkPoolIsOpen(ThreadLocalPool.java:92)
        at io.quarkus.reactive.datasource.runtime.ThreadLocalPool.pool(ThreadLocalPool.java:60)
        at io.quarkus.reactive.datasource.runtime.ThreadLocalPool.preparedQuery(ThreadLocalPool.java:114)
        at io.vertx.mutiny.sqlclient.Pool.preparedQuery(Pool.java:149)
        at io.vertx.mutiny.pgclient.PgPool_2d3061477c44a6b700dc3f9c4fe453a846636193_Synthetic_ClientProxy.preparedQuery(PgPool_2d3061477c44a6b700dc3f9c4fe453a846636193_Synthetic_ClientProxy.zig:323)
        at sncf.mobilite.groupehv.mytraindata.domain.BaselineDevice.create(BaselineDevice.java:78)
        at sncf.mobilite.groupehv.mytraindata.domain.BaselineDevice.lambda$get$0(BaselineDevice.java:26)
        at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
        at io.smallrye.mutiny.groups.UniOnNull.lambda$switchTo$3(UniOnNull.java:98)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:34)
        at io.vertx.mutiny.sqlclient.PreparedQuery$2.handle(PreparedQuery.java:119)
        at io.vertx.mutiny.sqlclient.PreparedQuery$2.handle(PreparedQuery.java:116)
        at io.vertx.sqlclient.impl.SqlResultHandler.complete(SqlResultHandler.java:98)
        at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:87)
        at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:33)
        at io.vertx.sqlclient.impl.PoolBase$1.lambda$onSuccess$0(PoolBase.java:90)
        at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:241)
        at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:88)
        at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:97)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
        at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
        at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:356)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:164)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:78)
        at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:138)
        at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:235)
        at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:95)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by cescoffier** [comment]
@tsegismont does that ring a bell?

**Comment by tsegismont** [comment]
No it doesn't.

@geniusit as discussed off-list, it's hard to say what's wrong if we can't reproduce.
Alternatively, I suggest to run the test in debug mode with a break point on the `ThreadLocalPool.close` methods to understand why the pool is closed at some point.

**Comment by geniusit** [comment]
@tsegismont is that what you need ?

![image](https://user-images.githubusercontent.com/3659037/114682874-cc255100-9d0f-11eb-82c0-1549855dfd78.png)

**Comment by geniusit** [comment]
@tsegismont Doing it solve the problem :)

```java
@Test
    void test(){

        final Uni<BaselineDevice> baselineDeviceUni =
                BaselineDevice
                        .get(
                                client,
                                "test",
                                "test"
                        )
                ;

        baselineDeviceUni
                .subscribe()
                .with(
                        s -> log.info("success : {}", s),
                        e -> log.info("b : {}", e)
                );

        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        log.info("end...");
    }
```

But why ?

**Comment by geniusit** [comment]
The PgPool is closed because on a JUnit perspective, the test is considered as a success even if the .subscribe() has no yet finished.
I see that I got the junit green mark (success) and THEN I have the stacktrace PgPool is closed. So I simply add a Thread.sleep() of 10s to let the code of the .subscribe time to execute...

The JUnit test should know that the test isn't yet finished until all the code of the .subscribe isn't completely run.

**Comment by tsegismont** [comment]
The stacktrace on the screenshot makes sense.

Subscribing is an asynchronous operation. So the test completes successfully before the asynchronous operation completes. Therefore, the Quarkus test extension closes the app which closes the pool.

Instead of subscribing, you can [wait on the `Uni`'s item](https://smallrye.io/smallrye-mutiny/guides/reactive-to-imperative#awaiting-on-unis-item) with: `.await().indefinitely();`
