### ISSUE TITLE
MP Config compilation fails if config is injected in multiple points

### ISSUE THREAD

**Issue by cristhiank** [quarkusio/quarkus#1650]
Quarkus is not compiling when I try to inject a config value in different classes  It come up after I upgraded my project to 0.12.0.

I pushed some code to reproduce it in https://github.com/cristhiank/quarkus-bugs 
Just clone it and try to run it.

Error is:

`Caused by: java.lang.IllegalStateException: Duplicate key custom.config (attempted merging values class java.lang.String and class java.lang.String)`

Full stack trace is:

> 20:10:54,841 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.RuntimeException: org.jboss.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ConfigBuildStep#validateConfigProperties threw an exception: java.lang.IllegalStateException: Duplicate key custom.config (attempted merging values class java.lang.String and class java.lang.String)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:134)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:105)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: org.jboss.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ConfigBuildStep#validateConfigProperties threw an exception: java.lang.IllegalStateException: Duplicate key custom.config (attempted merging values class java.lang.String and class java.lang.String)
        at org.jboss.builder.Execution.run(Execution.java:123)
        at org.jboss.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:136)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:110)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:99)
        ... 2 more
Caused by: java.lang.IllegalStateException: Duplicate key custom.config (attempted merging values class java.lang.String and class java.lang.String)
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.quarkus.arc.deployment.ConfigBuildStep.validateConfigProperties(ConfigBuildStep.java:146)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:506)
        at org.jboss.builder.BuildContext.run(BuildContext.java:413)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1416)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

**Comment by cristhiank** [comment]
I made a proposal to fix it here:

https://github.com/cristhiank/quarkus/commit/735d000defedc94f47f878ffcf7f71f26c80ec2e?diff=unified

**Comment by starksm64** [comment]
Thanks @cristhiank , this was already reported and has been fixed via https://github.com/quarkusio/quarkus/pull/1629. It will be in the next release and has already been merged to master if you want to build it yourself.
