### ISSUE TITLE
Config issue with live reload and .env file

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#16512]
I provide my configuration with a `.env` file, I don't know if it's relevant. But during a live reload today, I had the following error:
```
2021-04-14 15:21:06,079 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-12) Changed source files detected, recompiling [/data/home/gsmet/git/quarkus-bot/src/main/java/io/quarkus/bot/workflow/WorkflowRunAnalyzer.java, /data/home/gsmet/git/quarkus-bot/src/main/java/io/quarkus/bot/workflow/report/WorkflowReport.java]
2021-04-14 15:21:06,561 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-12) File change detected: /data/home/gsmet/git/quarkus-bot/src/main/resources/templates/WorkflowReportFormatter/commentReport.md
2021-04-14 15:21:06,561 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-12) File change detected: /data/home/gsmet/git/quarkus-bot/src/main/resources/templates/WorkflowReportFormatter/checkRunReportSummary.md
2021-04-14 15:21:06,607 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-bot stopped in 0.045s
One or more configuration errors have prevented the application from starting. The errors are:
  - SRCFG00014: Property quarkus.github-app.app-id is required but the value was not found or is empty
  - SRCFG00014: Property quarkus.github-app.private-key is required but the value was not found or is empty

Apr 14, 2021 3:21:06 PM io.quarkus.deployment.dev.IsolatedDevModeMain restartApp
ERROR: Failed to start quarkus
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:145)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:191)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:175)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:254)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:62)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:52)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:798)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	... 1 more
Caused by: io.quarkus.runtime.configuration.ConfigurationException: One or more configuration errors have prevented the application from starting. The errors are:
  - SRCFG00014: Property quarkus.github-app.app-id is required but the value was not found or is empty
  - SRCFG00014: Property quarkus.github-app.private-key is required but the value was not found or is empty
```

I stopped `quarkus:dev`, relaunched it without changing anything in my app and the application started again.

I know the information is scarce but it's not really reproducible, I just had it once.

**Comment by radcortez** [comment]
I've tried to reproduce this without any luck. Closing for now.

**Comment by labkeeper** [comment]
I'm  observing same behavior in 3.20.2.1. Not every time, but sometime application looses properties defined in .env after live reload caused by code change in @ApplicationScoped beans.
