### ISSUE TITLE
Flaky scheduler tests

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#16532]
We are seeing quite a few scheduler test failures lately with the following issue:
```
org.opentest4j.AssertionFailedError: Scheduler was not triggered ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:193)
	at io.quarkus.scheduler.test.PropertyDefaultValueSchedulerTest.testDefaultIdentity(PropertyDefaultValueSchedulerTest.java:33)
```

Could someone have a look?

**Comment by mkouba** [comment]
I'll take a look. These tests were added recently...
