### ISSUE TITLE
 Could not find a valid Docker environment

### ISSUE THREAD

**Issue by dreab8** [quarkusio/quarkus#16541]
## Describe the bug

I'm trying to run a bug reproducer (see https://github.com/quarkusio/quarkus/issues/16450#issuecomment-819466666) and the build fails because it is not able to find a valid Docker environment.

Podman is installed on my machine

### Expected behavior
The build detect and use Podman

### Actual behavior
Failure with the error message 
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor#launchDatabases threw an exception: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:215)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:207)
        at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:136)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:178)
        at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
        at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
        at io.quarkus.devservices.postgresql.deployment.PostgresqlDevServicesProcessor$1.startDatabase(PostgresqlDevServicesProcessor.java:33)
        at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:217)
        at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.launchDatabases(DevServicesDatasourceProcessor.java:103)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by vanuatoo** [comment]
Tried with 2.2.0.CR1, same issue

**Comment by xstefank** [comment]
I think this is a limitation of test containers, not quarkus.

**Comment by vanuatoo** [comment]
I got it running with the following approach.
1. Start podman with the command
2.

**Comment by r00ta** [comment]
@geoand 
I have the same issue with quarkus v2.2.2 (and previous) and with testcontainer v1.16.0 (and docker installed on my system). 

But testcontainer v1.15.3 works without any issue.

**Comment by geoand** [comment]
Given all the changes that have gone into Quarkus 3 around Docker detection, I am going to close this.
If this is still an issue, feel free to create a new issue

**Comment by ewoks** [comment]
@geoand is there some special configuration we need to do or [comment from above](https://github.com/quarkusio/quarkus/issues/16541#issuecomment-911011017) is the final "solution-around"?
I just got the same error with:
```
Quarkus: 3.0.3
Java: 17.0.7-tem
Podman 4.2.0
CSB RHEL: 4.18.0-425.19.2.el8_7.x86_64 
```

**Comment by geoand** [comment]
If you are seeing the issue with Quarkus `3.1.0.CR1`, then please open a new issue

**Comment by RapTho** [comment]
I'm still facing that issue on a MacOS though. Both Docker and podman is installed. DOCKER_HOST is also set but quarkus dev still complains about a missing docker environment?

```
➜  ~ which podman
/opt/homebrew/bin/podman
➜  ~ which docker
/Users/raphael/.rd/bin/docker
➜  ~ echo $DOCKER_HOST
unix:///run/user/501/podman/podman.sock
➜  ~ podman --version
podman version 5.1.2
➜  ~ docker --version
Docker version 25.0.4-rd, build c4cd0a9
```

Anyone got dev services to run on a MacOS?

**Comment by starksm64** [comment]
I see this problem every now and then and for me the problem generally is that podman corrupts itself when updating from the podman desktop. I had to clean up the last machine by running:

```bash
    podman machine stop
    podman machine rm podman-machine-default
    podman machine init
    podman machine start
```

after than quarkus:dev started correctly.
