### ISSUE TITLE
Undertow request failed HttpServerExchange (...) Servlet path match failed

### ISSUE THREAD

**Issue by Paul6552** [quarkusio/quarkus#16568]
## Describe the bug
I'm sorry if it's inappropriate, I wasn't sure if it was Quarkus, a library which is quarkus using, or maybe a badly secured endpoint.
I have the following error messages in the Quarkus log (pls see below)
The problem is not only the error message but also the Russian or Chinese websites. (e.g.` http://check.best-proxies.ru/azenv.php`)

```
2021-04-15 18:56:30,536 ERROR [io.und.request] (executor-thread-4) UT005071: Undertow request failed HttpServerExchange{ POST http://check.best-proxies.ru/azenv.php delegate io.undertow.vertx.VertxHttpExchange@5a06dbd6}: java.lang.IllegalArgumentException: UT000068: Servlet path match failed
	at io.undertow.servlet.handlers.ServletPathMatchesData.getServletHandlerByPath(ServletPathMatchesData.java:83)
	at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:89)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:124)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:117)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
	at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:400)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

2021-04-15 19:44:05,662 ERROR [io.und.request] (executor-thread-4) UT005071: Undertow request failed HttpServerExchange{ POST http://check.best-proxies.ru/azenv.php delegate io.undertow.vertx.VertxHttpExchange@44b229ad}: java.lang.IllegalArgumentException: UT000068: Servlet path match failed
	at io.undertow.servlet.handlers.ServletPathMatchesData.getServletHandlerByPath(ServletPathMatchesData.java:83)
	at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:89)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:124)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:117)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
	at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:400)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior
No error message

### Actual behavior
See log above

## To Reproduce
Thats the problem. I dont know which Endpoint or part of quarkus is leading to this error.

### Configuration
```properties
# datasource settings
quarkus.http.port=8080
quarkus.hibernate-orm.multitenant=SCHEMA
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pea
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=myusername
quarkus.datasource.password=mypassword
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=8
quarkus.log.category."io.agroal.pool".level=SEVERE
quarkus.transaction-manager.default-transaction-timeout=300S
quarkus.flyway.migrate-at-start=false
quarkus.flyway.schemas=public
quarkus.package.type=uber-jar

# Rest-api settings
portal-api/mp-rest/url=http://localhost:8180/
portal-api/mp-rest/scope=javax.inject.Singleton

# nimmt jeden request der rein kommt (zu pea) und schleust den Authorization header durch (nach portal)
org.eclipse.microprofile.rest.client.propagateHeaders=Authorization


# Rest-api settings
# OIDC Configuration
quarkus.oidc.auth-server-url=http://localhost:8280/auth/realms/program
quarkus.oidc.token.issuer=https://pea.turnierauswertung.at/auth/realms/program
quarkus.oidc.client-id=quarkus-pea
quarkus.oidc.credentials.secret=**credentials**
# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=false
# Dev variables
%dev.pea.reports.basedir=C:\\tmp\\program\\
#quarkus.log.level=INFO
#quarkus.log.min-level=DEBUG
#quarkus.log.category."io.undertow".level=DEBUG

```

**//EDIT**
I tried to restrict the request with cors. But I think there is another bug in CORS, because quarkus has not set any cors parameter:
#quarkus.http.cors=true
#quarkus.http.cors.origins=http://mydomain.com
#quarkus.http.cors.methods=GET,POST,DELETE,PUT
#quarkus.http.cors.headers=X-Requested-With,Content-Type,X-Codingpedia,Accept,Authorization
#quarkus.http.cors.access-control-max-age=24H
#quarkus.http.cors.access-control-allow-credentials=true

I could successfully set CORS settings in the program itself:

```
    @Override
    public void filter(ContainerRequestContext requestContext,
                       ContainerResponseContext responseContext) throws IOException {
        MultivaluedMap<String, Object> headers = responseContext.getHeaders();

        headers.add("Access-Control-Allow-Origin", "*");
        headers.add("Access-Control-Allow-Methods", "GET, POST, DELETE, PUT");
        headers.add("Access-Control-Allow-Credentials", "true");
        headers.add("Access-Control-Allow-Headers", "X-Requested-With, Content-Type, X-Codingpedia, Accept,X-Schema");

    }
```

### Output of `uname -a` or `ver`
Linux G9 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
### Output of `java -version`
jdk-15.0.2

### GraalVM version (if different from Java)
? (sry I dont know where to find)
### Quarkus version or git rev
Quarkus version 1.12.2.Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
mvn

**Comment by gsmet** [comment]
My understanding is that people are directing requests with this URL to your endpoint (probably by pointing to your IP address or proxying to your domain) and it doesn't match your resources.

I don't think we can do anything about it.

I recommend you install a webserver or reverse proxy in front of your Quarkus app and filter things there. They have a lot of tools for efficient filtering and it's better done before it hits the Java backend.

(Sorry for the very late answer, it fell through the cracks and we have a new process to bring attention to old issues)
