### ISSUE TITLE
JsonB with ssl and http/2 almost always receive null payload

### ISSUE THREAD

**Issue by mattiaforc** [quarkusio/quarkus#16605]
## Describe the bug
When quarkus is running with ssl enabled and requests are made using HTTP/2, almost all the times the JsonB deserializer fails due to a I/O exception when reading the payload. The exception is generated by the underlying input stream from which the request is read, which is empty after the initial handshake. 
I believe this happens only with the combination of JsonB, HTTP/2 and SSL because disabling one of them actually solves the problem (I tried switching JsonB to Jackson and it worked).
Native executables also suffer the same problem.
I noticed that this does not happen always, there is a very small percentage of requests that are handled correctly (i.e. the payload Is read as it should be), something like 0.01% of requests (more details in the bug reproduction section).

Stacktrace:
```java
2021-04-17 20:24:25,842 DEBUG [org.jbo.res.res.i18n] (executor-thread-205) RESTEASY002305: Failed executing POST /payload: org.jboss.resteasy.spi.ReaderException: javax.ws.rs.ProcessingException: RESTEASY008200: JSON Binding deserialization error: javax.json.bind.JsonbException: Internal error: I/O error while parsing JSON
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:250)
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:95)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:128)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.ws.rs.ProcessingException: RESTEASY008200: JSON Binding deserialization error: javax.json.bind.JsonbException: Internal error: I/O error while parsing JSON
	at org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider.readFrom(JsonBindingProvider.java:81)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:101)
	at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:63)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:80)
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:213)
	... 29 more
Caused by: javax.json.bind.JsonbException: Internal error: I/O error while parsing JSON
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:68)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:51)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:59)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:99)
	at org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider.readFrom(JsonBindingProvider.java:73)
	... 33 more
Caused by: javax.json.JsonException: I/O error while parsing JSON
	at org.glassfish.json.JsonTokenizer.read(JsonTokenizer.java:466)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:333)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:402)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:352)
	at org.eclipse.yasson.internal.JsonbRiParser.next(JsonbRiParser.java:141)
	at org.eclipse.yasson.internal.Unmarshaller.getRootEvent(Unmarshaller.java:80)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:58)
	... 37 more
Caused by: java.io.IOException: Underlying input stream returned zero bytes
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at org.glassfish.json.JsonTokenizer.fillBuf(JsonTokenizer.java:495)
	at org.glassfish.json.JsonTokenizer.read(JsonTokenizer.java:456)
	... 43 more
```

### Expected behavior
Payload should be read all the times when using JsonB combined with SSL and HTTP/2.

### Actual behavior
Payload is almost always not read due to a I/O exception when deserializing the json payload (the underlying input stream appears to be empty).

## To Reproduce

[Reproducer github repo](https://github.com/mattiaforc/quarkus-http2-ssl-test-case)

1. Run the application (using ./mvnw compile quarkus:dev or with your preferred IDE)
2. Do a series of https with HTTP/2 (this is fundamental!) requests against the url `https://localhost:8443/payload`. I prefer to do this with [hey](https://github.com/rakyll/hey) because it is easy and quick, but you can do it anyway you prefer. Hey way:
```shell
hey -h2 -n 5000 -c 100 -T "application/json" -m POST -d "{\"field\": \"string field\", \"anotherField\": \"another string field\"}" https://localhost:8443/payload
```
Be sure to run enough requests because the correct responses are just a few, something like 2/3 out of 5000.
3. (Optional) Run the same requests without HTTP/2 or enable http insecure requests in application.properties and see that the outcome is very different, all requests should succeed.

### Output of `uname -a` or `ver`
Darwin Air-di-Mattia.lan 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
### Output of `java -version`
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
### Quarkus version or git rev
1.13.1.Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 11.0.10, vendor: GraalVM Community, runtime: /Users/malattia/.sdkman/candidates/java/21.0.0.2.r11-grl
Default locale: it_IT, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "Mac"

**Comment by gsmet** [comment]
My advice would be to use Jackson.
