### ISSUE TITLE
Code reload: static attributes not reset in dependencies classes

### ISSUE THREAD

**Issue by iriikoad** [quarkusio/quarkus#16633]
## Description

I notice that the reload of the application done by quarkus:dev ( 1.13.0.Final) does not reset static attributes in dependencies.
- Issue exist on v1.11 and 1.12 too.
- instrumentation hot reload is disabled

Example of class that is not reset in dependency:

```
public class SingletonObject {
    private static SingletonObject instance;
    private SingletonObject() {}
   
    public static synchronized SingletonObject getInstance() {
        if(instance == null) {
            instance = new SingletonObject();
            System.out.println("SingletonObject created : " + instance);
        }
        return instance;
    }
    
    public void doSomething() {
        System.out.println("SingletonObject doSomething . Instance=" + instance);
    }
}
```

If this class "SingletonObject" is inside the project Quarkus, static attribute "instance" is reset to NULL when Quarkus restarts the app. So it's good.

But if you put it this class in a dependency of your pom, "instance" attributes stays set, and this result to unexpected behaviour on other dependencies that may use it.

I reproduced the issue on the "getting started" app:
- I created a library  org.acme.test.libx and put the class SingletonObject
- I created and put SingletonObjecInternal next to GreetingResource.jav, with the same code.
- Call the instance on the GET:
```
@Path("/hello")
public class GreetingResource {
    @Inject
    Logger logger;
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        SingletonObject.getInstance().doSomething();                  //-> in a dependency lib
        SingletonObjecInternal.getInstance().doSomething();        //-> next to GreetingResource, in same package
        return "Hello RESTEasy";
    }
}
```
On first call to "/hello", I see the correct output:
```
SingletonObject created: org.acme.test.libx.SingletonObject@3f0cf00
SingletonObject doSomething. Instance=org.acme.test.libx.SingletonObject@3f0cf00
SingletonObjecInternal created: org.acme.getting.started. SingletonObjecInternal@2dd5b5f7
SingletonObjecInternal doSomething. Instance=org.acme.getting.started SingletonObjecInternal@2dd5b5f7
```
I modified the class to make sure Quarkus restarts the application, then re-call "/hello", and I see:
```
SingletonObject doSomething. Instance=org.acme.test.libx.SingletonObject@3f0cf00
SingletonObjecInternal created: org.acme.getting.started. SingletonObjecInternal@a32c824
SingletonObjecInternal doSomething. Instance=org.acme.getting.started SingletonObjecInternal@a32c824
```
==> The static instance of SingletonObject  (external dependency) is not reset, we don't see "SingletonObject  created".

### Expected behavior
the "instance" should be NULL after reload on both SingletonObject (in the project and in the dependency library)

### Actual behavior
the "instance" is NULL after reload on SingletonObjecInternal in the project package : OK
the "instance" is not NULL after reload on SingletonObject in the dependency library : KO

## To Reproduce

1-generate the getting-started
2-add the class SingletonObjectInternal (copy class SingletonObject  above) in same package as  GreetingResource.
3-generate a simple jar maven project, and add SingletonObject into it
4-modify the GreetingResource to call the function (see below)
5-launch mvn quarkus:dev, then go to http://localhost:8080/hello
6-change "return "Hello RESTEasy"; to   "return "Hello RESTEasy again";
7- go to http://localhost:8080/hello
8- see the console

### Configuration
```properties

quarkus.live-reload.instrumentation=false

```

### Screenshots
I also re-used the same app to test JPA security+form: I can see that the initialization is not the same neither:

```
[INFO] Compiling 9 source files to C:\Dev\TESTS\quarkus1.13\getting-started\target\classes
Listening for transport dt_socket at address: 5005
Users created
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-04-19 14:27:33,764 INFO  [io.quarkus] (Quarkus Main Thread) getting-started 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.13.2.Final) started in 12.751s. Listening on: http://localhost:8080
2021-04-19 14:27:33,769 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-04-19 14:27:33,770 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-h2, mutiny, narayana-jta, resteasy, security, security-jdbc, security-jpa, smallrye-context-propagation]
2021-04-19 14:27:34,076 WARN  [io.qua.ver.htt.run.sec.HttpSecurityRecorder] (vert.x-eventloop-thread-0) Encryption key was not specified for persistent FORM auth, using temporary key r1W2t/qvw90uACkFkyHoe0tdSRr6vr1J+JJFhQkKKFM=
SingletonObject created ==>: org.acme.test.libx.SingletonObject@4431d8ee
SingletonObject doSomething >>. Instance=org.acme.test.libx.SingletonObject@4431d8ee
SingletonObject2 created: org.acme.getting.started.SingletonObject2@4a504115
SingletonObject2 doSomething. Instance=org.acme.getting.started.SingletonObject2@4a504115
2021-04-19 14:28:04,374 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-1) Changed source files detected, recompiling [C:\Dev\TESTS\quarkus1.13\getting-started\src\main\java\org\acme\getting\started\GreetingResource.java]
2021-04-19 14:28:06,801 INFO  [io.quarkus] (Quarkus Main Thread) getting-started stopped in 0.138s
Users created
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-04-19 14:28:10,000 INFO  [io.quarkus] (Quarkus Main Thread) getting-started 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.13.2.Final) started in 3.190s. Listening on: http://localhost:8080
2021-04-19 14:28:10,006 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-04-19 14:28:10,011 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-h2, mutiny, narayana-jta, resteasy, security, security-jdbc, security-jpa, smallrye-context-propagation]
2021-04-19 14:28:10,015 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-1) Hot replace total time: 5.646s
SingletonObject doSomething >>. Instance=org.acme.test.libx.SingletonObject@4431d8ee
SingletonObject2 created: org.acme.getting.started.SingletonObject2@408ec94f
SingletonObject2 doSomething. Instance=org.acme.getting.started.SingletonObject2@408ec94f
```
You can see this:
"SingletonObject2" is inside org.acme.getting.started, and it's reseted because you can see "created"
"SingletonObject" is in the dependency: **SingletonObject created ==> ...**  is missing after reload and has kept the hashcode @4431d8ee

Plus, HttpSecurityRecorder is showing a warning at 1st time, not after reload. 

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Logiciels\apache-maven-3.6.3\bin\..
Java version: 11.0.4, vendor: Oracle Corporation, runtime: C:\Logiciels\jdk-11.0.4
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

## Additional context
I also noticed this issue because in an other more complex project, a DLL used in a lib was not unload-reload.

**Comment by stuartwdouglas** [comment]
We don't reload dependencies outside the project by default, if you really want to do this you need to use add:

quarkus.class-loading.reloadable-artifacts=groupId:artifactId 

into application.properties.

**Comment by iriikoad** [comment]
Your solution resolves the issue.

`quarkus.class-loading.reloadable-artifacts=groupId:artifactId`

Thanks a lot.

**Comment by iriikoad** [comment]
Update:
This property creates a ClassNotFoundException in arc when we wants to inject instances of CDI beans of this library.

Example: I want to inject all classes that implements a "NewServiceInterface" defined in the "libx" in my REST class of the app:

@Path("/hello")
public class GreetingResource {

    @Inject
    Instance<NewServiceInterface> services;
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        SingletonObject.getInstance().doSomething();
        SingletonObject2.getInstance().doSomething();
        System.out.println("services size: " +  services.stream().count());
        return "Hello RESTEasy again or nothing..";
    }

in the depedency "libx", I have this class NewServiceImpl, and the interface NewServiceInterface. 

@ApplicationScoped
public class NewServiceImpl implements NewServiceInterface {
}

Without quarkus.class-loading.reloadable-artifacts=org.acme.test:libx
=> No issue: I see "services size: 1"

With quarkus.class-loading.reloadable-artifacts=org.acme.test:libx
=> Class not found exception at first call of http://localhost:8080/hello (no reload at all)

2021-04-20 11:52:44,277 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: 69d2e706-5b85-49e5-b5c4-84c611c0f658-1: org.jboss.resteasy.spi.UnhandledException: java.lang.NoClassDefFoundError: org/acme/test/libx/NewServiceImpl
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
...
Caused by: java.lang.NoClassDefFoundError: org/acme/test/libx/NewServiceImpl
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:411)
...
Caused by: java.lang.ClassNotFoundException: org.acme.test.libx.NewServiceImpl                              
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)          
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)       
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)                                  
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:421)      
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:371)     

I tried adding
quarkus.class-loading.parent-first-artifacts=org.acme.test:libx
quarkus.arc.unremovable-types=org.acme.test.libx.**
Not working neither.

**Comment by stuartwdouglas** [comment]
Can you open a new issue with these details? ArC is likely defining its classes in the wrong ClassLoader.
