### ISSUE TITLE
Flyway quarkus extension get “java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus” when executing test

### ISSUE THREAD

**Issue by falcantaracano** [quarkusio/quarkus#16632]
## Describe the bug
When execute mvnw test in my project using Flyway quarkus extension with version 1.13.2_Final, it produces the following error:
```
[INFO] Running example.credentials.flyway.entities.Test1Flyway
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.983 s <<< FAILURE! - in example.credentials.flyway.entities.Test1Flyway
[ERROR] example.credentials.flyway.entities.Test1Flyway.testAddNewExampleDescriptionToFlywayCreatedTable  Time elapsed: 0.014 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException:

Unable to obtain connection from database: Error General : "java.lang.NullPointerException"
General error: "java.lang.NullPointerException" [50000-197]
-------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : HY000
Error Code : 50000
Message    : Error General : "java.lang.NullPointerException"
General error: "java.lang.NullPointerException" [50000-197]

Caused by: org.h2.jdbc.JdbcSQLException:
Error General : "java.lang.NullPointerException"
General error: "java.lang.NullPointerException" [50000-197]
Caused by: java.lang.NullPointerException
```
The used configuration is:
```
    datasource:
      db-kind: h2
      jdbc:
        driver: org.h2.Driver
#        url: jdbc:h2:tcp://localhost/mem:example;MODE=Oracle
        url: jdbc:h2:./target/db/example;MODE=Oracle,AUTO_SERVER=TRUE
        max-size: 13
    flyway:
      locations: db/migration-test
      clean-at-start: true
      migrate-at-start: true
      schemas: PUBLIC
```
### Expected behavior
After H2 is started, flyway must create the t_examples table and insert two rows. The Test1Flyway must insert one additional row into the same table.

### Actual behavior
This Test1Flyway doesn't work, while Test22AgroalDataSource always works correctly.

## To Reproduce

[flyway-credentials-quarkus.zip](https://github.com/quarkusio/quarkus/files/6337796/flyway-credentials-quarkus.zip)

1. Execute  ***mvnw test***

### Configuration
```properties
# Add your application.properties here, if applicable.
    datasource:
      db-kind: h2
      jdbc:
        driver: org.h2.Driver
#        url: jdbc:h2:tcp://localhost/mem:example;MODE=Oracle
        url: jdbc:h2:./target/db/example;MODE=Oracle,AUTO_SERVER=TRUE
        max-size: 13
    flyway:
      locations: db/migration-test
      clean-at-start: true
      migrate-at-start: true
      schemas: PUBLIC
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
```
Microsoft Windows [Versión 10.0.19042.928]
```
### Output of `java -version`
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)`
```
### Quarkus version or git rev
1.13.2_Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: D:\desa\apache-maven-3.6.3\bin\..
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: D:\AdoptOpenJDK\jdk-11.0.8.10-hotspot
Default locale: es_ES, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
The NPE is caused by:

```
[INFO] Running example.credentials.flyway.entities.Test1Flyway
java.lang.NullPointerException
        at org.h2.index.BaseIndex.mayHaveNullDuplicates(BaseIndex.java:318)
        at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:198)
        at org.h2.mvstore.db.MVTable.addRowsToIndex(MVTable.java:684)
        at org.h2.mvstore.db.MVTable.rebuildIndexBlockMerge(MVTable.java:622)
        at org.h2.mvstore.db.MVTable.rebuildIndex(MVTable.java:559)
        at org.h2.mvstore.db.MVTable.addIndex(MVTable.java:536)
        at org.h2.engine.Database.open(Database.java:760)
        at org.h2.engine.Database.openDatabase(Database.java:286)
        at org.h2.engine.Database.<init>(Database.java:280)
        at org.h2.engine.Engine.openSession(Engine.java:66)
        at org.h2.engine.Engine.openSession(Engine.java:179)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
        at org.h2.engine.Engine.createSession(Engine.java:140)
        at org.h2.engine.Engine.createSession(Engine.java:28)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
        at org.h2.Driver.connect(Driver.java:69)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:204)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:490)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:472)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

That sounds like an H2 bug to be honest

**Comment by falcantaracano** [comment]
Probably.

I find the following issues in H2 with [50000-197] code for the version 1.4.197. 
[https://github.com/h2database/h2database/issues/1430]
[https://github.com/h2database/h2database/issues/1297]

Actually, H2 database project has two higest version (1.4.199 and 1.4.200). The h2 team made a commit to master just before releasing version 1.4.199 from this code error [50000-197]

Is it possible to upgrade h2 version outside quarkus 1.13.2_final?

**Comment by gastaldi** [comment]
@falcantaracano of course, just declare the dependency on the updated h2 driver in your application

**Comment by falcantaracano** [comment]
NPE exception is related with ***mode=Oracle*** in the jdbc parameter. I remove it, and Flyway creates the   "PUBLIC"."flyway_schema_history" table.

Now, the new exception is related not to find my t_example table.  Flyway considers that this new created database is update for public schema, not loading my creation script.
```
[INFO] Running example.credentials.flyway.entities.Test1Flyway
21:03:29:361 (main) DEBUG [i.q.f.r.QuarkusPathLocationScanner] Locations: [classpath:db/migration-test]
21:03:29:365 (main) DEBUG [i.q.f.r.QuarkusPathLocationScanner] Loading db/migration-test/V2.0.0__INITIAL_STRUCTURE_OF_TABLES_WITH_SOME_DATA
21:03:29:372 (main) DEBUG [o.f.c.i.s.c.ClassPathScanner] Scanning for classpath resources at 'classpath:db/callback' ...
21:03:29:372 (main) DEBUG [o.f.c.i.s.c.ClassPathScanner] Determining location urls for classpath:db/callback using ClassLoader QuarkusClassLoader:Quarkus Base Runtime ClassLoader ...
21:03:29:373 (main) DEBUG [o.f.c.i.s.c.ClassPathScanner] Unable to resolve location classpath:db/callback.
21:03:29:377 (main) INFO  [o.f.c.i.l.VersionPrinter] Flyway Community Edition 7.7.0 by Redgate
21:03:29:486 (agroal-11) DEBUG [e.c.f.s.c.CipherManager] Shared key File: shared.key
21:03:29:487 (agroal-11) DEBUG [e.c.f.s.c.CipherManager] Shared key Type File: resource
21:03:29:488 (agroal-11) DEBUG [e.c.f.s.c.CipherManager] LaunchMode (current): TEST
21:03:29:518 (agroal-11) DEBUG [e.c.f.s.MyBbddCredentialsProvider] my-bbdd-credentials-provider/username:tools
21:03:29:518 (agroal-11) DEBUG [e.c.f.s.MyBbddCredentialsProvider] my-bbdd-credentials-provider/password:********
21:03:29:902 (main) INFO  [o.f.c.i.d.b.DatabaseType] Database: jdbc:h2:./target/db/example (H2 1.4)
21:03:29:902 (main) DEBUG [o.f.c.i.d.b.DatabaseType] Driver  : H2 JDBC Driver 1.4.197 (2018-03-18)
21:03:29:972 (main) DEBUG [o.f.c.Flyway] DDL Transactions Supported: false
21:03:29:972 (main) DEBUG [o.f.c.Flyway] Schemas: PUBLIC
21:03:29:972 (main) DEBUG [o.f.c.Flyway] Default schema: null
21:03:29:980 (main) DEBUG [o.f.c.i.c.SqlScriptCallbackFactory] Scanning for SQL callbacks ...
21:03:29:980 (main) DEBUG [i.q.f.r.FlywayRecorder] Filtering out resource: db/migration-test/V2.0.0__INITIAL_STRUCTURE_OF_TABLES_WITH_SOME_DATA (filename: V2.0.0__INITIAL_STRUCTURE_OF_TABLES_WITH_SOME_DATA)
21:03:30:013 (main) DEBUG [o.f.c.i.c.DbClean] Dropping pre-schema database level objects...
21:03:30:015 (main) INFO  [o.f.c.i.c.DbClean] Successfully dropped pre-schema database level objects (execution time 00:00.001s)
21:03:30:017 (main) DEBUG [o.f.c.i.c.DbClean] Cleaning schema "PUBLIC" ...
21:03:30:021 (main) INFO  [o.f.c.i.c.DbClean] Successfully cleaned schema "PUBLIC" (execution time 00:00.002s)
21:03:30:021 (main) DEBUG [o.f.c.i.c.DbClean] Dropping post-schema database level objects...
21:03:30:022 (main) INFO  [o.f.c.i.c.DbClean] Successfully dropped post-schema database level objects (execution time 00:00.000s)
21:03:30:022 (agroal-11) DEBUG [e.c.f.s.c.CipherManager] Shared key File: shared.key
21:03:30:022 (agroal-11) DEBUG [e.c.f.s.c.CipherManager] Shared key Type File: resource
21:03:30:022 (agroal-11) DEBUG [e.c.f.s.c.CipherManager] LaunchMode (current): TEST
21:03:30:024 (agroal-11) DEBUG [e.c.f.s.MyBbddCredentialsProvider] my-bbdd-credentials-provider/username:tools
21:03:30:025 (agroal-11) DEBUG [e.c.f.s.MyBbddCredentialsProvider] my-bbdd-credentials-provider/password:********
21:03:30:028 (main) DEBUG [o.f.c.Flyway] Memory usage: 107 of 305M
21:03:30:028 (main) INFO  [o.f.c.i.l.VersionPrinter] Flyway Community Edition 7.7.0 by Redgate
21:03:30:031 (main) DEBUG [o.f.c.Flyway] DDL Transactions Supported: false
21:03:30:031 (main) DEBUG [o.f.c.Flyway] Schemas: PUBLIC
21:03:30:031 (main) DEBUG [o.f.c.Flyway] Default schema: null
21:03:30:032 (main) DEBUG [o.f.c.i.c.SqlScriptCallbackFactory] Scanning for SQL callbacks ...
21:03:30:032 (main) DEBUG [i.q.f.r.FlywayRecorder] Filtering out resource: db/migration-test/V2.0.0__INITIAL_STRUCTURE_OF_TABLES_WITH_SOME_DATA (filename: V2.0.0__INITIAL_STRUCTURE_OF_TABLES_WITH_SOME_DATA)
21:03:30:045 (main) DEBUG [o.f.c.i.c.DbSchemas] Skipping creation of existing schema: "PUBLIC"
21:03:30:060 (main) INFO  [o.f.c.i.s.JdbcTableSchemaHistory] Creating Schema History table "PUBLIC"."flyway_schema_history" ...
21:03:30:087 (main) DEBUG [o.f.c.i.p.Parser] Parsing  ...
21:03:30:105 (main) DEBUG [o.f.c.i.s.ParserSqlScript] Found statement at line 1: CREATE TABLE IF NOT EXISTS "PUBLIC"."flyway_schema_history" (
    "installed_rank" INT NOT NULL,
    "version" VARCHAR(50),
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INT,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "execution_time" INT NOT NULL,
    "success" BOOLEAN NOT NULL,
    CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank")
) AS SELECT -1, NULL, '<< Flyway Schema History table created >>', 'TABLE', '', NULL, 'TOOLS', CURRENT_TIMESTAMP, 0, TRUE
21:03:30:105 (main) DEBUG [o.f.c.i.s.ParserSqlScript] Found statement at line 14: CREATE INDEX "PUBLIC"."flyway_schema_history_s_idx" ON "PUBLIC"."flyway_schema_history" ("success")
21:03:30:106 (main) DEBUG [o.f.c.i.s.DefaultSqlScriptExecutor] Executing SQL: CREATE TABLE IF NOT EXISTS "PUBLIC"."flyway_schema_history" (
    "installed_rank" INT NOT NULL,
    "version" VARCHAR(50),
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INT,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "execution_time" INT NOT NULL,
    "success" BOOLEAN NOT NULL,
    CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank")
) AS SELECT -1, NULL, '<< Flyway Schema History table created >>', 'TABLE', '', NULL, 'TOOLS', CURRENT_TIMESTAMP, 0, TRUE
21:03:30:113 (main) DEBUG [o.f.c.i.s.DefaultSqlScriptExecutor] Update Count: 0
21:03:30:113 (main) DEBUG [o.f.c.i.s.DefaultSqlScriptExecutor] Executing SQL: CREATE INDEX "PUBLIC"."flyway_schema_history_s_idx" ON "PUBLIC"."flyway_schema_history" ("success")
21:03:30:119 (main) DEBUG [o.f.c.i.s.DefaultSqlScriptExecutor] Update Count: 0
21:03:30:119 (main) DEBUG [o.f.c.i.s.JdbcTableSchemaHistory] Created Schema History table "PUBLIC"."flyway_schema_history"
21:03:30:148 (main) DEBUG [i.q.f.r.FlywayRecorder] Filtering out resource: db/migration-test/V2.0.0__INITIAL_STRUCTURE_OF_TABLES_WITH_SOME_DATA (filename: V2.0.0__INITIAL_STRUCTURE_OF_TABLES_WITH_SOME_DATA)
21:03:30:148 (main) DEBUG [i.q.f.r.FlywayRecorder] Filtering out resource: db/migration-test/V2.0.0__INITIAL_STRUCTURE_OF_TABLES_WITH_SOME_DATA (filename: V2.0.0__INITIAL_STRUCTURE_OF_TABLES_WITH_SOME_DATA)
21:03:30:157 (main) INFO  [o.f.c.i.c.DbMigrate] Current version of schema "PUBLIC": << Empty Schema >>
21:03:30:165 (main) INFO  [o.f.c.i.c.DbMigrate] Schema "PUBLIC" is up to date. No migration necessary.
21:03:30:166 (main) DEBUG [o.f.c.Flyway] Memory usage: 113 of 305M
21:03:31:764 (main) INFO  [e.c.f.e.Test1Flyway] Starting flyway test
21:03:31:771 (main) ERROR [e.c.f.e.ExampleE] SQL Error: : org.h2.jdbc.JdbcSQLException: Tabla "T_EXAMPLES" no encontrada
Table "T_EXAMPLES" not found; SQL statement:
INSERT INTO PUBLIC.T_EXAMPLES (example_id, description) VALUES (?,?) [42102-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
```
I would appreciate any help with this new exception.

Thanks ...

**Comment by geoand** [comment]
It's probably best if you ask the Flyway folks as it seems to be an issue a Flyway (after the change you made)
