### ISSUE TITLE
Create a parameter to start H2 in Server Mode

### ISSUE THREAD

**Issue by felipewind** [quarkusio/quarkus#16645]
## Description

I'd like **Quarkus to start H2 in server mode**, so I would be able to run my application in development mode and access the data base with a client as DBeaver.

Nowadays, when I want to do this, I use H2 in Mixed Mode (local and remote connections at the same time) like this:
```properties
quarkus.datasource.jdbc.url=jdbc:h2:~/h2/oracle_test;MODE=Oracle;AUTO_SERVER=TRUE
```

The downside about using H2 with Mixed Mode is:
- The URL is more complex and it must be adapted to the file system of the operating system (in Linux can be `~/h2/oracle_test`, but in Windows it must be different);
- Sometimes the files get corrupted and I must clean them.

As explained in [this topic](https://stackoverflow.com/questions/57802845/quarkus-jpa-with-h2-database), I know that I could also achieve this starting a TCP Server in my application. But, for me the H2 mixed mode looks more easy to do.

## Implementation ideas

Perhaps could be a new parameter to ask Quarkus to start H2 in server mode.

I've noticed that Quarkus is already doing this when I don't inform the `quarkus.datasource.jdbc.url` property:
```
quarkus.datasource.db-kind=h2
quarkus.datasource.username=test
quarkus.datasource.password=test
```

```
[INFO] H2 database started in TCP server mode; server status: TCP server running at tcp://127.0.1.1:40003 (only local connections)
```
In this scenario, I was able to connect to H2 Server at localhost:40003 with DBeaver.

The problem is that Quarkus change the H2 Server port on every start it does and if I want to run two simultaneous application, I need to control the port number.

I've used the @ConfigProperty to discover what Quarkus is passing to this parameter:
```java
@ConfigProperty(name = "quarkus.datasource.jdbc.url")
```

In my test, it was `jdbc:h2:tcp://localhost:40003/mem:default;DB_CLOSE_DELAY=-1`

I've tried to pass this in my properties:
```property
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.driver=org.h2.Driver
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost:40003/mem:default;DB_CLOSE_DELAY=-1
```

But, when I start Quarkus I receive this error:
```
2021-04-09 17:14:57,549 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection is broken: "java.net.ConnectException: Connection refused (Connection refused): localhost:40003" [90067-197]
2021-04-09 17:14:57,551 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (Quarkus Main Thread) HHH000342: Could not obtain connection to query metadata: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused (Connection refused): localhost:40003" [90067-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:451)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:332)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:200)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:452)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:434)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:103)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:83)
	at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:114)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:447)
	... 12 more

```

I've already openned this question in [StackOverflow](https://stackoverflow.com/questions/67027970/how-can-i-start-h2-in-server-mode-using-quarkus).

Perhaps it is already possible to do this and I'm passing some wrong parameters. If it is the case, sorry!

Thanks a lot!

**Comment by geoand** [comment]
You should be able to do this by passing the appropriate properties in `quarkus.datasource.devservices.properties`

**Comment by kawoolutions** [comment]
Hi. Could you be a little more concise about how to configure an H2 in-mem DB connectable from other processes using `quarkus.datasource.devservices.properties`?

I am new to Quarkus and was guessing (in `application.properties`):

%dev.quarkus.datasource.devservices.properties."port" = 9092

But it doesn't work:

```
Caused by: java.net.ConnectException: Connection refused: getsockopt
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:135)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:99)
```

Thanks
