### ISSUE TITLE
Custom yaml properties don't work in native mode

### ISSUE THREAD

**Issue by max-grigoriev** [quarkusio/quarkus#16652]
## Describe the bug
Entities annotated by `ConfigProperties` don't work in native mode.

### Expected behavior
The native mode should work the same way as java mode.

### Actual behavior
Error is thrown when there's access to the property:
```
2021-04-20 11:45:00,157 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello-resteasy failed, error id: fe02fce4-adc1-4961-9b7f-c7f79c11964f-1: org.jboss.resteasy.spi.UnhandledException: java.util.NoSuchElementException: SRCFG00014: Property segments.items is required but the value was not found or is empty
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.util.NoSuchElementException: SRCFG00014: Property segments.items is required but the value was not found or is empty
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:234)
	at io.quarkus.arc.runtime.config.ConfigPropertiesProducer.produceSegmentsConfiguration(ConfigPropertiesProducer.zig:69)
	at io.quarkus.arc.runtime.config.ConfigPropertiesProducer_ProducerMethod_produceSegmentsConfiguration_004ce2013420739b954a774ad0e6cda8ff31bb4d_Bean.create(ConfigPropertiesProducer_ProducerMethod_produceSegmentsConfiguration_004ce2013420739b954a774ad0e6cda8ff31bb4d_Bean.zig:243)
	at io.quarkus.arc.runtime.config.ConfigPropertiesProducer_ProducerMethod_produceSegmentsConfiguration_004ce2013420739b954a774ad0e6cda8ff31bb4d_Bean.get(ConfigPropertiesProducer_ProducerMethod_produceSegmentsConfiguration_004ce2013420739b954a774ad0e6cda8ff31bb4d_Bean.zig:273)
	at io.quarkus.arc.runtime.config.ConfigPropertiesProducer_ProducerMethod_produceSegmentsConfiguration_004ce2013420739b954a774ad0e6cda8ff31bb4d_Bean.get(ConfigPropertiesProducer_ProducerMethod_produceSegmentsConfiguration_004ce2013420739b954a774ad0e6cda8ff31bb4d_Bean.zig:308)
	at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:148)
	at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:170)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:202)
	at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:218)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:430)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:443)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:266)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:263)
	at io.quarkus.arc.runtime.BeanContainerImpl$1.create(BeanContainerImpl.java:35)
	at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:54)
	at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:71)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:386)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 17 more
```

## To Reproduce

https://github.com/max-grigoriev/code-with-quarkus

1. Build: `./gradlew clean build -Dquarkus.package.type=native`
2. Start `./build/code-with-quarkus-1.0.0-SNAPSHOT-runner`
3. Open `http://localhost:8080/hello-resteasy`

### Output of `uname -a` or `ver`
Darwin Maksyms-MBP 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

### GraalVM version (if different from Java)
21.0.0.2.r11

### Quarkus version or git rev
1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.5.1

## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
@max-grigoriev please use `@ConfigMapping` instead, which works (I've tested it with your reproducer). The only difference is that it only supports interfaces. For more information check here: https://smallrye.io/docs/smallrye-config/main/mapping/mapping.html

In the meanwhile I'll look into the `@ConfigProperties` issue, but at some point we are going to deprecate it in favour of `@ConfigMapping`.

**Comment by max-grigoriev** [comment]
@radcortez your solution works, thanks a lot. 
P.S. it would be nice to have updated docs on the Quarkus website.

**Comment by radcortez** [comment]
Great! Yes, we are preparing an update for the Config Guide: https://github.com/quarkusio/quarkus/pull/16496
