### ISSUE TITLE
Nullpointer create Schema if entity based on interface

### ISSUE THREAD

**Issue by eichstaedtk** [quarkusio/quarkus#16676]
If the graphql entity is based on an interface you wil get an Nullpointer during quarkus startup. 

Caused by: java.lang.NullPointerException
	at io.smallrye.graphql.schema.creator.ReferenceCreator.createReference(ReferenceCreator.java:201)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:314)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForPojoField(ReferenceCreator.java:149)
	at io.smallrye.graphql.schema.creator.FieldCreator.createFieldForPojo(FieldCreator.java:114)
	at io.smallrye.graphql.schema.creator.type.TypeCreator.addFields(TypeCreator.java:104)
	at io.smallrye.graphql.schema.creator.type.TypeCreator.create(TypeCreator.java:72)
	at io.smallrye.graphql.schema.creator.type.TypeCreator.create(TypeCreator.java:41)
	at io.smallrye.graphql.schema.SchemaBuilder.createAndAddToSchema(SchemaBuilder.java:197)
	at io.smallrye.graphql.schema.SchemaBuilder.addTypesToSchema(SchemaBuilder.java:130)
	at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:111)
	at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:80)
	at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:170)

If you remove the interface declaration on the class the start is possible. 

Qurakus Version:  1.13.2.Final

**Comment by geoand** [comment]
cc @phillip-kruger

**Comment by phillip-kruger** [comment]
Hi @eichstaedtk - Do you have a small reproducer I can look at ?

**Comment by eichstaedtk** [comment]
@phillip-kruger Unfortunately not because it is an internal project. But what I examined is that as soon as the GraphQL Entity contains a method like this you can reproduce the issue. The only way you get thsi up and running if you use @Ignore for the method. 

public Map<String, String> getContextMap() {
    return contextMap;
  }

Can you fix this issue because I saw that the check for interfaces is still  missing the handling for the microprofile-graphql annotation @Type. Maybe this will solve also the problem.

**Comment by phillip-kruger** [comment]
Ok, so the issue here is then Map (rather than interface). We support interfaces, however Map is not supported in GraphQL.
See https://github.com/graphql/graphql-spec/issues/101
See https://graphql.org/learn/schema/

You can create an Object (Let's call is KeyValuePair) that has two fields (String key and String value) and have a list of those. 

Closing here as this is not supported in GraphQL (in general)
