### ISSUE TITLE
Arc regression on 2.0: It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#16713]
With a CDI producer method like the following

```
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;
import javax.inject.Named;
import io.minio.MinioClient;
public class MinioClientProducer {

    @Produces
    @ApplicationScoped
    @Named("minioClient")
    public MinioClient produceMinioClient() {
        return MinioClient.builder()
                .endpoint("http://" + System.getProperty(MinioResource.PARAM_SERVER_HOST),
                        Integer.parseInt(System.getProperty(MinioResource.PARAM_SERVER_PORT)), false)
                .credentials(MinioResource.SERVER_ACCESS_KEY, MinioResource.SERVER_SECRET_KEY)
                .build();
    }
}
```
I am getting the following exception after we have upgraded to Quarkus 2.0.0.Alpha1:

```
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=io.quarkiverse.minio.client.MinioProducer]
[2] It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Named(value = "minioClient"), @Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=org.apache.camel.quarkus.component.minio.it.MinioClientProducer]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1106)
        at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:142)
        at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:448)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Suppressed: javax.enterprise.inject.spi.DeploymentException: It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=io.quarkiverse.minio.client.MinioProducer]
                at io.quarkus.arc.processor.Beans.validateBean(Beans.java:764)
                at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:442)
                at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:1184)
                at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:357)
                at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:138)
                at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:421)
                ... 10 more
        Suppressed: javax.enterprise.inject.spi.DeploymentException: It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Named(value = "minioClient"), @Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=org.apache.camel.quarkus.component.minio.it.MinioClientProducer]
                at io.quarkus.arc.processor.Beans.validateBean(Beans.java:764)
                at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:442)
                at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:1184)
                at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:357)
                at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:138)
                at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:421)
                ... 10 more

        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:690)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:763)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:72)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:77)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:342)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:289)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:267)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:259)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:258)
        at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:101)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:100)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:65)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:111)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:111)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:79)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=io.quarkiverse.minio.client.MinioProducer]
[2] It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Named(value = "minioClient"), @Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=org.apache.camel.quarkus.component.minio.it.MinioClientProducer]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1106)
        at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:142)
        at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:448)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Suppressed: javax.enterprise.inject.spi.DeploymentException: It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=io.quarkiverse.minio.client.MinioProducer]
                at io.quarkus.arc.processor.Beans.validateBean(Beans.java:764)
                at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:442)
                at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:1184)
                at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:357)
                at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:138)
                at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:421)
                ... 10 more
        Suppressed: javax.enterprise.inject.spi.DeploymentException: It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Named(value = "minioClient"), @Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=org.apache.camel.quarkus.component.minio.it.MinioClientProducer]
                at io.quarkus.arc.processor.Beans.validateBean(Beans.java:764)
                at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:442)
                at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:1184)
                at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:357)
                at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:138)
                at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:421)
                ... 10 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:398)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:269)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:66)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:325)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:658)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:705)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
        ... 33 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=io.quarkiverse.minio.client.MinioProducer]
[2] It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Named(value = "minioClient"), @Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=org.apache.camel.quarkus.component.minio.it.MinioClientProducer]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1106)
        at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:142)
        at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:448)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Suppressed: javax.enterprise.inject.spi.DeploymentException: It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=io.quarkiverse.minio.client.MinioProducer]
                at io.quarkus.arc.processor.Beans.validateBean(Beans.java:764)
                at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:442)
                at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:1184)
                at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:357)
                at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:138)
                at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:421)
                ... 10 more
        Suppressed: javax.enterprise.inject.spi.DeploymentException: It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Named(value = "minioClient"), @Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=org.apache.camel.quarkus.component.minio.it.MinioClientProducer]
                at io.quarkus.arc.processor.Beans.validateBean(Beans.java:764)
                at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:442)
                at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:1184)
                at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:357)
                at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:138)
                at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:421)
                ... 10 more

        at io.quarkus.builder.Execution.run(Execution.java:116)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:154)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:396)
        ... 44 more
Caused by: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=io.quarkiverse.minio.client.MinioProducer]
[2] It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Named(value = "minioClient"), @Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=org.apache.camel.quarkus.component.minio.it.MinioClientProducer]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1106)
        at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:142)
        at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:448)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Suppressed: javax.enterprise.inject.spi.DeploymentException: It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=io.quarkiverse.minio.client.MinioProducer]
                at io.quarkus.arc.processor.Beans.validateBean(Beans.java:764)
                at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:442)
                at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:1184)
                at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:357)
                at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:138)
                at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:421)
                ... 10 more
        Suppressed: javax.enterprise.inject.spi.DeploymentException: It's not possible to add a synthetic constructor with no parameters to the unproxyable return type of PRODUCER METHOD bean [types=[io.minio.S3Base, java.lang.Object, io.minio.MinioClient], qualifiers=[@Named(value = "minioClient"), @Default, @Any], target=io.minio.MinioClient produceMinioClient(), declaringBean=org.apache.camel.quarkus.component.minio.it.MinioClientProducer]
                at io.quarkus.arc.processor.Beans.validateBean(Beans.java:764)
                at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:442)
                at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:1184)
                at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:357)
                at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:138)
                at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:421)
                ... 10 more
```

It used to work with Quarkus 1.x.

## Steps to reproduce:

It happens in Camel Quarkus Minio test https://github.com/apache/camel-quarkus/tree/camel-main/integration-tests/minio
in `camel-main` branch where we upgraded to Quarkus 2.0. The branch depends on Camel SNAPSHOT, so it might be harder to run for non-Camel people. I can try to provide a simple reproducer, if needed.

**Comment by manovotn** [comment]
I did a quick scan of what the producer looks like and what are the types of the bean and it looks exactly like a test we have in Quarkus that is supposed to fail.
See this - https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/test/java/io/quarkus/arc/test/unproxyable/ProducerFailedToAddMissingNoargsConstructorTest.java

And in your commit upgrading Quarkus, you also changed the producer method annotation, so I don't think this worked before - it didn't even have CDI annotation on it.
See https://github.com/apache/camel-quarkus/commit/156055a6a608a48bca07ebe0fdb03eb7a608fc2c#diff-6b8392f27cfda693fc939f3d5d3c1be9e297c2cb4251ff1c016f860495450390L21

**Comment by mkouba** [comment]
Matej is right, we don't generate the no-args constructor automatically if the produced class extends a class that does not have a no-args constructor. It's documented here: https://quarkus.io/guides/cdi-reference#simplified-constructor-injection. You should consider using the `@Singleton` scope.

**Comment by ppalaga** [comment]
Thanks for the explanation, @manovotn and @mkouba. As @Ladicek pointed out in the chat, this is caused by a change in Minio, not in Arc. Originally `MinioClient` extended `Object`, now it extends `S3Base` which has no default constructor. 

> in your commit upgrading Quarkus, you also changed the producer method annotation, so I don't think this worked before - it didn't even have CDI annotation on it.

I am sure it worked, but you are still right that our producer was broken. There is another producer class in Quarkiverse Minio https://github.com/quarkiverse/quarkus-minio/blob/master/runtime/src/main/java/io/quarkiverse/minio/client/MinioProducer.java that might make our test work.

It looks like fixing this is up to us (Camel Quarkus) and Quarkiverse Minio.

Thanks again for your assistance, gentlemen!

**Comment by ppalaga** [comment]
I have submitted a fix to Quarkiverse Minio https://github.com/quarkusio/quarkus/issues/16713
