### ISSUE TITLE
JAX-RS client builder fails in continuous 2.0 tests

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#16755]
When running Quarkus `2.0.0.Alpha1` in dev mode, I can't run a test which programmatically creates a JAX-RS client.
## To Reproduce
Following code used in test:

```java
// ...
client = ClientBuilder.newBuilder().build();
baseTarget = client.target(buildUri());
```

Results in:

```
java.util.ServiceConfigurationError: org.jboss.resteasy.spi.config.ConfigurationFactory: org.jboss.resteasy.core.config.DefaultConfigurationFactory not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:591)
	...
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.<init>(ManualClosingApacheHttpClient43Engine.java:120)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient43Engine.<init>(ApacheHttpClient43Engine.java:29)
	at org.jboss.resteasy.client.jaxrs.engines.ClientHttpEngineBuilder43.createEngine(ClientHttpEngineBuilder43.java:265)
	at org.jboss.resteasy.client.jaxrs.engines.ClientHttpEngineBuilder43.build(ClientHttpEngineBuilder43.java:210)
	at org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.build(ResteasyClientBuilderImpl.java:415)
	at org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.build(ResteasyClientBuilderImpl.java:47)
	at com.sebastian_daschner.coffee.CoffeeSystem.<init>(CoffeeSystem.java:16)
	at com.sebastian_daschner.coffee.CoffeeIT.<init>(CoffeeIT.java:9)
```

This would be very helpful in the interactive tests, since the way how I like to write plain JUnit tests (which programmatic stuff only) runs very fast.

Reproducer: https://github.com/sdaschner/quarkus-playground/tree/f9c23fa6fcfa0a83ae9f8f14c19ffca577d9b51d (test `CoffeeIT`)

**Comment by sdaschner** [comment]
I remember I've had a similar issue before when using the JAX-RS client before, but I didn't find an issue to it...

**Comment by cescoffier** [comment]
\CC  @FroMage @michalszynkiewicz @stuartwdouglas (adding Stuart as it may be a classloading issue)
