### ISSUE TITLE
InvocationTargetException in Quarkus 2.0.0.Alpha1

### ISSUE THREAD

**Issue by serrodcal** [quarkusio/quarkus#16781]
## Describe the bug
```
java -jar target/quarkus-app/quarkus-run.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/microprofile/config/ConfigValue
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:372)
        at io.quarkus.runtime.generated.Config.<clinit>(Config.zig:326)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:59)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.microprofile.config.ConfigValue
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:104)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:60)
        ... 18 more
```

### Expected behavior
The application should start fine.

### Actual behavior

Testing Quarkus 2.0, with Reactive Routes, I got InvocationTargetException when I start the application after `./mvnw clean package`. The application starts fine using `./mvnw quarkus:dev`.

## To Reproduce

`pom.xml` file:
```xml
<dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mutiny</artifactId>
      <version>2.0.0.Alpha1</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-vertx-web</artifactId>
      <version>2.0.0.Alpha1</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
      <version>2.0.0.Alpha1</version>
    </dependency>
  </dependencies>
```

### Configuration
```properties
quarkus.native.builder-image = abcd
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`

```
Darwin MacBook-Pro-de-Sergio-2.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```

### Output of `java -version`

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
```

### Quarkus version or git rev

2.0.0.Alpha1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/serrodcal/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.10, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home
Default locale: es_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

## Additional context
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
Could you please provide a reproducer?

**Comment by serrodcal** [comment]
> Could you please provide a reproducer?

Yes, [here](https://github.com/serrodcal-tmp/quarkus-2-alpha1) you have ;)

**Comment by geoand** [comment]
@serrodcal it seems that the project is not public

**Comment by serrodcal** [comment]
> @serrodcal it seems that the project is not public

Sorry, now it's public.

**Comment by geoand** [comment]
The problem is that you are not using the BOM (you need to use `quarkus-bom` as is mentioned in the release announcement)
