### ISSUE TITLE
SmallRyeHealthProcessor#registerUiExtension throws NPE in a multi-module CI-friendly maven project

### ISSUE THREAD

**Issue by vladykin** [quarkusio/quarkus#16827]
## Describe the bug
I have a multi-module CI-friendly (https://maven.apache.org/maven-ci-friendly.html) Maven project.
The project consists of parent pom and multiple submodules, some of which are Quarkus-based applications.

Version in every pom.xml is declared as
```xml
<version>${revision}${sha1}</version>
```
the same version format is used to refer to parent pom in all sub-modules.

Default values for revision and sha1 are defined in parent pom:
```xml
    <properties>
        <revision>1.0</revision>
        <sha1>-SNAPSHOT</sha1>
    </properties>
```

When I build this multi-module project, the tests located in submodules and annotated with QuarkusTest fail with the following exception:
```
Caused by: io.quarkus.builder.BuildException: 
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.health.deployment.SmallRyeHealthProcessor#registerUiExtension threw an exception: java.lang.NullPointerException
	at java.base/java.lang.String.replace(String.java:2143)
	at io.quarkus.deployment.util.WebJarUtil.insertVariables(WebJarUtil.java:348)
	at io.quarkus.deployment.util.WebJarUtil.copyResourcesForDevOrTest(WebJarUtil.java:150)
	at io.quarkus.deployment.util.WebJarUtil.copyResourcesForDevOrTest(WebJarUtil.java:109)
	at io.quarkus.smallrye.health.deployment.SmallRyeHealthProcessor.registerUiExtension(SmallRyeHealthProcessor.java:413)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

It's trying to access artifact version, but gets null, and subsequent String.replace fails with NPE.

### Expected behavior
Tests should run successfully, taking default values of revision and sha1 from parent pom.
If implementing resolution of the parent pom and getting default values from there is too complicated, it's OK to use some dummy value for the version. But it's not OK to fail with NPE.

### Actual behavior
Build failure as described above.

## To Reproduce

The key to reproduce this is to have multi-module maven project with parent pom and Quarkus app as one of the submodules.
And CI-friendly version must be used in all poms.

The bug does not reproduce in a single-module maven project using CI-friendly version.

## Environment (please complete the following information):

Output of `uname -a` or `ver`: `Linux 5.10.27-gentoo #3 SMP Mon Apr 26 17:36:34 MSK 2021 x86_64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz GenuineIntel GNU/Linux`

Output of `java -version`: `OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)`

Quarkus version: 1.13.1.Final

Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by vladykin** [comment]
Seems related to https://github.com/quarkusio/quarkus/issues/9727

**Comment by gsmet** [comment]
@aloubyansky I think we will need your guidance on this one.

@vladykin any chance you could prepare a small reproducer? That would help be a big help.

**Comment by aloubyansky** [comment]
@vladykin have you also tried 1.13.2.Final?

**Comment by aloubyansky** [comment]
https://github.com/quarkusio/quarkus/pull/16400 may have fixed it

**Comment by aloubyansky** [comment]
Also see https://groups.google.com/g/quarkus-dev/c/hT8j5eFPPLA/m/VCZoGG6rAQAJ

**Comment by vladykin** [comment]
Indeed with 1.13.2 and with 1.13.3 I can no longer reproduce the original problem.
Thanks! This issue can be closed.
