### ISSUE TITLE
Qute NullPointerException in build when combining MessageBundle with TemplateExtension method

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#16868]
When a MessageBundle is used in combination with a TemplateExtension method, a NullPointerException happens during the build.

I have created a small reproducer project.  https://github.com/andlinger/quarkus-qute-npe

The template line which triggers the error can be found here:
https://github.com/andlinger/quarkus-qute-npe/blob/ad06b9adce8f9e38abb0d8bfb1a3d47bc77209b6/quarkus/src/main/resources/templates/QuteResource/number.txt#L1

```
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
    [error]: Build step io.quarkus.qute.deployment.MessageBundleProcessor#validateMessageBundleMethodsInTemplates threw an exception: java.lang.NullPointerException
    at io.quarkus.qute.deployment.Types.isAssignableFrom(Types.java:116)
    at io.quarkus.qute.deployment.MessageBundleProcessor.validateMessageBundleMethodsInTemplates(MessageBundleProcessor.java:410)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
    at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
    at java.base/java.lang.Thread.run(Thread.java:834)
    at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by mkouba** [comment]
I believe that this should be fixed in https://github.com/quarkusio/quarkus/pull/16618 (fixes https://github.com/quarkusio/quarkus/issues/16590).

@andlinger What version of quarkus do you use? The fix should be backported in 1.13.3.Final...

**Comment by andlinger** [comment]
We use 1.13.2.Final. When will 1.13.3.Final be released?

**Comment by mkouba** [comment]
A tag already exists so I'd say the release is in the works. CC @gsmet

**Comment by andlinger** [comment]
Updated to Quarkus 1.13.3.Final and bug is fixed.
