### ISSUE TITLE
Disable reactive datasource explicitly fail

### ISSUE THREAD

**Issue by hernael** [quarkusio/quarkus#16919]
## Describe the bug
I have jdbc and reactive datasources simultaneously to the same DB, and depending of an initial condition i could use a reactive approach or i could use a jdbc approach (one or another).

The code contains a simple Entity (is the same table in both datasource because it is the same DB) and two repositories: one hibernate reactive paneche, and one hibernate orm panache (both in repository pattern)

In reactive approach would be something like:
```
quarkus.datasource.jdbc=false
quarkus.datasource.reactive=true
```
And in jdbc approach:
```
quarkus.datasource.jdbc=true
quarkus.datasource.reactive=false
```

Everything is fine with reactive approach!
But with jdbc approach it fails.

## The Error is:
```
2021-04-30 00:03:29,891 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.hibernate.orm.panache.deployment.PanacheHibernateResourceProcessor#build threw an exception: java.lang.IllegalStateException: Panache entities do not support being attached to several persistence units:
	- com.demo.entity.CurrencyEntity is attached to: default-reactive,<default>
	at io.quarkus.hibernate.orm.panache.deployment.PanacheHibernateResourceProcessor.recordPanacheEntityPersistenceUnits(PanacheHibernateResourceProcessor.java:200)
	at io.quarkus.hibernate.orm.panache.deployment.PanacheHibernateResourceProcessor.build(PanacheHibernateResourceProcessor.java:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:396)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:269)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:66)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:79)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:378)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:56)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:127)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:144)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.hibernate.orm.panache.deployment.PanacheHibernateResourceProcessor#build threw an exception: java.lang.IllegalStateException: Panache entities do not support being attached to several persistence units:
	- com.demo.entity.CurrencyEntity is attached to: default-reactive,<default>
	at io.quarkus.hibernate.orm.panache.deployment.PanacheHibernateResourceProcessor.recordPanacheEntityPersistenceUnits(PanacheHibernateResourceProcessor.java:200)
	at io.quarkus.hibernate.orm.panache.deployment.PanacheHibernateResourceProcessor.build(PanacheHibernateResourceProcessor.java:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:116)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:153)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:394)
	... 9 more
Caused by: java.lang.IllegalStateException: Panache entities do not support being attached to several persistence units:
	- com.demo.entity.CurrencyEntity is attached to: default-reactive,<default>
	at io.quarkus.hibernate.orm.panache.deployment.PanacheHibernateResourceProcessor.recordPanacheEntityPersistenceUnits(PanacheHibernateResourceProcessor.java:200)
	at io.quarkus.hibernate.orm.panache.deployment.PanacheHibernateResourceProcessor.build(PanacheHibernateResourceProcessor.java:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

2021-04-30 00:03:29,891 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure

```

### Configuration
```properties
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${database.username}
quarkus.datasource.password=${database.password}

quarkus.datasource.reactive.url=${database.url}
quarkus.datasource.reactive.max-size=20
quarkus.datasource.reactive=false

quarkus.datasource.jdbc.url=${database.url}
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc=true

```

### Output of `java -version`
corretto-11.0.11

### Quarkus version or git rev
1.13.3.Final

## In my Pom:

```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-reactive-panache</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-reactive-pg-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm-panache</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-postgresql</artifactId>
        </dependency>
```

**Comment by gsmet** [comment]
Hibernate ORM and Hibernate Reactive are not working well together right now. This is something that will be fixed in a later release.
