### ISSUE TITLE
Components located in a separate maven structure are not being loaded by CDI in quarkus:dev mode

### ISSUE THREAD

**Issue by wmedvede** [quarkusio/quarkus#17065]
## Describe the bug
While doing some test I've run into the scenario bellow that I believe could be a bug.

A reproducer can be found here:    https://github.com/wmedvede/quarkus-bean-loading-issue

It looks like the quarkus:dev mode can only load CDI components of classes located under the same maven project structure.

We have that:

**multi-module**: (is a maven project with the two modules below)

	generic-api:
       		A simple api module with the only purpose of defining the integration interfaces
		UserAttributesProcessor and TaskAttributesProcessor processor.

		It could be third party implementations of this processors not neccesary
		implemented in this project.

	main-service:
		A hello world service that loads by CDI all the available implementations of
		the UserAttributesProcessor and TaskAttributesProcessor clases.

                In particular in this module we have two implementations:
			DefaultUserAttributesProcessor and DefaultTaskAttributesProcessor.

		The class AttributesProcessorRegistry loads all the implementations
		at start-up.

		This service has also a dependency on "second-implementation" with the intention
		of making available the UserAttributesProcessor and TaskAttributesProcessor
		implementations provided in this module.

		Note that there are no transitive dependencies, since we have that:

		main-service          --depends on-> (generic-api and second-implementation)
		second-implementation --depends on-> (generic-api) 

		
**second-implementation**: (totally independent maven project)

	has a dependency only the "generic-api" and two implementations:
	SecondTaskAttributesProcessor and SecondUserAttributesProcessor

### Expected behavior

The different UserAttributesProcessor and TaskAttributesProcessor implementations should be loaded in all execution modes, 
quarkus dev, native image and the quarkus-run.jar.

### Actual behavior

1) when we execute the main-service application with java -jar target/quarkus-app/quarkus-run.jar 

	All the implementations are loaded as expected:
		DefaultUserAttributesProcessor
		DefaultTaskAttributesProcessor
		SecondUserAttributesProcessor
		SecondTaskAttributesProcessor

2) when we generate the native image and execute the corresponding main-service application
	./target/main-service-1.0.0-SNAPSHOT-runner all the implementations are loaded as expected

		DefaultUserAttributesProcessor
		DefaultTaskAttributesProcessor
		SecondUserAttributesProcessor
		SecondTaskAttributesProcessor

3) when we execute the main-service application in dev mode we get the following exception:

2021-05-07 15:23:07,897 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:288)
        ... 15 more
Caused by: java.lang.RuntimeException: Failed to initialize Arc
        at io.quarkus.arc.Arc.initialize(Arc.java:26)
        at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:40)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy_0(ArcProcessor$generateResources-1025303321.zig:76)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy(ArcProcessor$generateResources-1025303321.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:224)
        ... 15 more
Caused by: java.lang.NoClassDefFoundError: org/acme/api/UserAttributesProcessor
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:411)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:371)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:421)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:371)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.acme.processors.SecondUserAttributesProcessor_Bean.<init>(SecondUserAttributesProcessor_Bean.zig:80)
        at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans1(Default_ComponentsProvider.zig:252)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:38)
        at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:112)

## To Reproduce

use the following reproducer:   https://github.com/wmedvede/quarkus-bean-loading-issue

1) build the module: multi-module/generic-api
2) build the module: second-implementation
3) build the module: main-service and try to execute it in dev mode.

**Comment by stuartwdouglas** [comment]
There are no plans to fix this. It's because you have external dependencies that depend on modules in the project itself, which is not really something we recommend or support. You can work around it by specifying: `quarkus.class-loading.reloadable-artifacts=org.acme:second-implementation` in application.properties.
