### ISSUE TITLE
ArC fails to construct bean with self-referencing generic constraint

### ISSUE THREAD

**Issue by Felk** [quarkusio/quarkus#17147]
ArC appears to be unable to generate beans if they have a generic parameter and a constraint referencing the generic parameter, as is common for e.g. `T extends Comparable<T>`. The issue can be reproduced as follows:

```java
public class CdiProducers {
    @Produces
    public <T extends Comparable<T>> List<T> getSpecificList() {
        return new ArrayList<>();
    }
}
```

which results in the following error at build time:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.3.Final:build (default) on project my-project: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.IllegalStateException: Unable to construct the type handle for PRODUCER METHOD bean [types=[java.util.List<T extends java.util.List>, java.util.Collection<T extends java.util.List>, java.lang.Object, java.lang.Iterable<T extends java.util.List>], qualifiers=[@Default, @Any], target=java.util.List<T extends java.util.List> getSpecificList(), declaringBean=me.demo.CdiProducers]: Unsupported bean type: UNRESOLVED_TYPE_VARIABLE, T
[ERROR]         at io.quarkus.arc.processor.BeanGenerator.initConstructor(BeanGenerator.java:671)
[ERROR]         at io.quarkus.arc.processor.BeanGenerator.createConstructor(BeanGenerator.java:566)
[ERROR]         at io.quarkus.arc.processor.BeanGenerator.generateProducerMethodBean(BeanGenerator.java:398)
[ERROR]         at io.quarkus.arc.processor.BeanGenerator.generate(BeanGenerator.java:115)
[ERROR]         at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:181)
[ERROR]         at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:458)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

with a prettyfied error message:
```
Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception:
java.lang.IllegalStateException: Unable to construct the type handle for PRODUCER METHOD bean [
    types=[
        java.util.List<T extends java.util.List>,
        java.util.Collection<T extends java.util.List>,
        java.lang.Object,
        java.lang.Iterable<T extends java.util.List>
    ],
    qualifiers=[@Default, @Any],
    target=java.util.List<T extends java.util.List> getSpecificList(),
    declaringBean=me.demo.CdiProducers
]: Unsupported bean type: UNRESOLVED_TYPE_VARIABLE, T
```

A few more examples:
- does _not_ work: `<T extends List<T>>`
- _does_ work: `<T extends Serializable>`
- _does_ work: `<T>`

I have attached a sample project to reproduce the problem: [arc-selfreferencing-generic-constraint.zip](https://github.com/quarkusio/quarkus/files/6460654/arc-selfreferencing-generic-constraint.zip)

**Comment by mkouba** [comment]
Hi @Felk, thanks for reporting this problem. It's a known issue - see also https://github.com/wildfly/jandex/issues/88 and we can't do much until this jandex issue is resolved.

**Comment by Felk** [comment]
Thanks for letting me know, I'll watch that issue

**Comment by mkouba** [comment]
@Ladicek would you care to take a look at the ArC part? You fixed the Jandex issue, hence a perfect candidate :wink: .

**Comment by Ladicek** [comment]
Sure thing!

**Comment by Ladicek** [comment]
So the reproducer actually builds and runs just fine (I believe due to #27631), but I can't inject the produced bean anywhere, nor can I look it up programmatically -- and I don't even have an idea how to express such injection or programmatic lookup. I'm trying this:

```java
@Dependent
static class Producer {
    @Produces
    @Dependent
    public <T extends Comparable<T>> List<T> produce() {
        return new ArrayList<>();
    }
}

// inject
@Dependent
static class Target<T extends Comparable<T>> {
    @Inject
    List<T> list;

    public List<T> getList() {
        return list;
    }
}

// lookup
public <T extends Comparable<T>> void test() {
    ArcContainer arc = Arc.container();
    InstanceHandle<List<T>> handle = arc.instance(new TypeLiteral<List<T>>() {});
}
```

But I'm not exactly sure if that's supposed to work or not. Any opinions? :-)

**Comment by Felk** [comment]
In my original case I injected a concrete type, e.g.

```java
@Inject
List<String> stringList;
```

**Comment by Ladicek** [comment]
Yeah, I originally thought about that, but I'm not sure that's supposed to work as well. If I'm reading _Assignability of raw and parameterized types_, it probably should. It currently doesn't, because our `AssignabilityCheck.findAssignables` relies on presence of the types in Jandex -- I'll try to figure something out there, but `getAllKnownSubclasses` or `getAllKnownImplementors` can't really work well with on-demand indexing.

My attempts in the previous comment are most likely wrong, because those `T`s are different type variables, even if they have the same name.
