### ISSUE TITLE
Quarkus-hibernate-orm extension doesn't deal well with concurrency

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#17141]
## Describe the bug

Quarkus Version: Upstream

I am using Mutiny in order to emulate concurrency over the following extension:
`io.quarkus:quarkus-jdbc-mysql`

Scenario:

```

    @Inject
    UserRepository users;

  @RepeatedTest(10)
    public void agroalCheckBorderConditionBetweenIdleAndGetConnection() throws InterruptedException {
        final int concurrentRequestAmount = 2;
        CountDownLatch completed = new CountDownLatch(concurrentRequestAmount);
        LOG.info("######################");
        Multi.createFrom().range(0, concurrentRequestAmount).subscribe()
                .with(n -> Multi.createFrom().ticks().every(Duration.ofSeconds(getIdle() + 3))
                        .onOverflow().drop()
                        .onFailure().invoke(e -> Assertions.fail("Unexpected exception " + e.getMessage()))
                        .subscribe().with(i -> {
                            LOG.info("Result : " + users.count());
                            completed.countDown();
                        }));

        completed.await(TIMEOUT_SEC, TimeUnit.SECONDS);
        long missingEvents = concurrentRequestAmount - completed.getCount();
        assertEquals(0, completed.getCount(), String.format("Missing %d events.", missingEvents));
    }

```

As you can see in the above scenario, we are going to run two concurrent queries, that are going to be executed "at the same time" in the future:

```
Multi.createFrom().ticks().every(Duration.ofSeconds(getIdle() + 3))
```

After some iteration, an exception rises:

 ````
 2021-05-11 13:50:15,198 ERROR [io.qua.mut.run.MutinyInfrastructure] (executor-thread-1) Mutiny had to drop the following exception: java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.forEach(HashMap.java:1339)
        at org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl.releaseResources(ResourceRegistryStandardImpl.java:323)
        at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.afterTransaction(AbstractLogicalConnectionImplementor.java:60)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.afterTransaction(LogicalConnectionManagedImpl.java:167)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.afterTransaction(JdbcCoordinatorImpl.java:275)
        at org.hibernate.internal.SessionImpl.afterOperation(SessionImpl.java:543)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1448)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
        at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1665)
        at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.count(AbstractJpaOperations.java:307)
        at io.quarkus.qe.rest.data.UserRepository.count(UserRepository.java)
        at io.quarkus.qe.rest.data.UserRepository_ClientProxy.count(UserRepository_ClientProxy.zig:174)
        at io.quarkus.qe.dbpool.AgroalPoolTest.lambda$agroalCheckBorderConditionBetweenIdleAndGetConnection$2(AgroalPoolTest.java:95)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at io.smallrye.mutiny.subscription.Subscribers$CallbackBasedSubscriber.onItem(Subscribers.java:67)
        at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:66)
        at io.smallrye.mutiny.operators.multi.overflow.MultiOnOverflowDropItemsOp$MultiOnOverflowDropItemsProcessor.onItem(MultiOnOverflowDropItemsOp.java:68)
        at io.smallrye.mutiny.operators.multi.builders.IntervalMulti$IntervalRunnable.run(IntervalMulti.java:90)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
 ```

Looks that some Maps are not threadsafe like `io.quarkus.hibernate.orm.runtime.RequestScopedSessionHolder`. I tried to swap this HashMap to a `ConcurrentHashMap` but then a new `ConcurrentModificationException` is thrown by other Maps. 

Reproducer:
Project: https://github.com/quarkus-qe/beefy-scenarios/pull/203
Command: `mvn clean test -pl 014-quarkus-panache-with-transactions-xa -Dtest=AgroalPoolTest#agroalCheckBorderConditionBetweenIdleAndGetConnection`

**Comment by Sanne** [comment]
hi @pjgg 

For what it's worth, the Hibernate `Session` is indeed not threadsafe (by design, a single Session represents a single threaded "unit of work" and is often bound to a transaction).

With this test you're not really creating " emulate concurrency over the following extension: io.quarkus:quarkus-jdbc-mysql" as you're including Mutiny, Panache and Hibernate ORM as well as intermediate layers - and this doesn't seem a correct way to do so, as the Panache layer will lookup the Hibernate ORM `Session` from the current CDI context, so I don't think this can work well in multi-threaded ( @FroMage might correct me? )

If you want to test the `quarkus-jdbc-mysql` you should inject the Datasource in isolation, and use the JDBC connections - which also are not multi-threaded, but you should be able to open/use/close one in each separate thread, so testing the pool implementation for correctness under concurrency.

**Comment by pjgg** [comment]
Thank you @Sanne 

I agree, I have refactored the scenario using directly the DB connections given by agroal datasource, and works as expected. 
Also, If each request (in the previous scenario) has his own hibernate session in an isolated thread, works as expected. 

So, is true that hibernate [is not threadsafe](https://developer.atlassian.com/server/confluence/hibernate-sessions-and-transaction-management-guidelines/#:~:text=Hibernate%20sessions%20are%20not%20thread,Hibernate%2Dmanaged%20objects%20between%20threads) but we can manage some complex scenarios as well. 

To sum up is not an issue!.
