### ISSUE TITLE
Keycloak Authorization 'policy-enforcer.lazy-load-paths=true' regression

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#17179]
## Describe the bug
Guillaume @gsmet has noticed a `quickstarts/security-keycloak-authorization` has started failing with:

```
2021-05-12 16:33:31,910 ERROR [org.key.ada.aut.PolicyEnforcer] (executor-thread-1) Could not lazy load resource with path [/api/admin] from server: java.lang.NullPointerException
	at org.keycloak.adapters.authorization.PolicyEnforcer$PathConfigMatcher.matches(PolicyEnforcer.java:290)
	at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.getPathConfig(AbstractPolicyEnforcer.java:351)
	at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.authorize(AbstractPolicyEnforcer.java:72)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:72)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:36)
``` 
Adding `quarkus.keycloak.policy-enforcer.lazy-load-paths=false`, see https://github.com/quarkusio/quarkus-quickstarts/pull/858

**Comment by Vinche59** [comment]
@sberyozkin 
@pedroigor 
Just also hit that NPE when trying to upgrade to Quarkus 1.13.4.Final (and Keycloak 13.0.0).

As far as I understand the problem, in Keycloak 13.0.0, *PathConfigMatcher* (see below) try to test the Id of the resource but *quarkus-keycloak-authorization* extension do not seems to set it.

[PolicyEnforcer.java](https://github.com/keycloak/keycloak/blob/13.0.0/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/authorization/PolicyEnforcer.java)

```java
289 for (PathConfig existingPath : paths.values()) {
290   if (existingPath.getId().equals(targetResource.getId()) 
291             && existingPath.isStatic()
292             && !PolicyEnforcerConfig.EnforcementMode.DISABLED.equals(existingPath.getEnforcementMode())) {
293       return null;
294       }
295 }
```

Is it a misconfiguration of my application (but I don't find any means to setup this Id in application.properties) or really a bug ?

**Comment by pedroigor** [comment]
@Vinche59 Not sure if a bug. The id should be set based on the resource in the server that matches the path being accessed. Could you share your `application.properties` ? And perhaps export the authorization settings via Keycloak admin console?

But yeah, we should handle that better.

**Comment by pedroigor** [comment]
Created https://issues.redhat.com/browse/KEYCLOAK-18111.

**Comment by Vinche59** [comment]
@pedroigor 
Actually I just try to exclude some path from enforcement directly in application.properties:

```
# Configuration file
quarkus.oidc.auth-server-url=https://localhost:8543/auth/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret
quarkus.oidc.tls.verification=none
quarkus.http.cors=true

# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=true

# Disables policy enforcement for a path
quarkus.keycloak.policy-enforcer.paths.1.path=/api/public
quarkus.keycloak.policy-enforcer.paths.1.enforcement-mode=DISABLED
```
and thus I don't have any authorization settings for that specific path in Keycloak.

I created a reproducer here : https://github.com/Vinche59/quarkus-keycloak-npe.git

* mvn -P1.13.3 clean verify -> will run with Quarkus 1.13.3.Final and Keycloak 12.0.4 and the tests will succeed

* mvn -P1.13.4 clean verify -> will run with Quarkus 1.13.4.Final and Keycloak 13.0.0 and the tests will fail with 
```java
ERROR [org.key.ada.aut.PolicyEnforcer] (executor-thread-1) Could not lazy load resource with path [/api/admin] from server: java.lang.NullPointerException
        at org.keycloak.adapters.authorization.PolicyEnforcer$PathConfigMatcher.matches(PolicyEnforcer.java:290)
        at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.getPathConfig(AbstractPolicyEnforcer.java:351)
        at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.authorize(AbstractPolicyEnforcer.java:72)
        at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:55)
        at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:33)
        at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$1$1$1.run(HttpAuthorizer.java:72)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
```
as **quarkus-keycloak-authorization** extension will create a Path for /api/public with an **Id == null**

**Comment by Vinche59** [comment]
> Created https://issues.redhat.com/browse/KEYCLOAK-18111.

@pedroigor 
Hum... disregard my last comment... I didn't see you already have implemented a fix for that ... :-)

**Comment by pedroigor** [comment]
@Vinche59 Thanks. There is a workaround in that issue.
