### ISSUE TITLE
Clear separation between constinuous test runs in the console

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#17178]
A clear separation between runs in logs would make it easier to see results from a same run. 
```
Running Tests for the first timeWARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/Users/ia3andy/.m2/repository/org/codehaus/groovy/groovy/3.0.7/groovy-3.0.7.jar) to constructor java.lang.AssertionError(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplug
2021-05-12 17:37:56,834 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#myFavoriteBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.myFavoriteBand(RockBandResourceTest.java:59)
2021-05-12 17:37:56,835 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#mayWeHaveANewBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <405>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.mayWeHaveANewBand(RockBandResourceTest.java:87)

2021-05-12 17:37:56,836 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#is404ABand() failed
: java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "no band found with id: 2"
  Actual: RESTEASY003210: Could not find resource for full path: http://localhost:8081/rock/10

	at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.is404ABand(RockBandResourceTest.java:
2021-05-12 17:38:02,637 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#myFavoriteBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.myFavoriteBand(RockBandResourceTest.java:59)
2021-05-12 17:38:02,637 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#mayWeHaveANewBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <405>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.mayWeHaveANewBand(RockBandResourceTest.java:87)

2021-05-12 17:38:02,638 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#is404ABand() failed
: java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "no band found with id: 2"
  Actual: RESTEASY003210: Could not find resource for full path: http://localhost:8081/rock/10

	at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.is404ABand(RockBandResourceTest.java:
2021-05-12 17:38:29,630 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#myFavoriteBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.myFavoriteBand(RockBandResourceTest.java:59)
2021-05-12 17:38:29,630 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#mayWeHaveANewBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <405>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.mayWeHaveANewBand(RockBandResourceTest.java:87)

2021-05-12 17:38:29,631 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#is404ABand() failed
: java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "no band found with id: 2"
  Actual: RESTEASY003210: Could not find resource for full path: http://localhost:8081/rock/10

	at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.is404ABand(RockBandResourceTest.java:


--
Test run failed, 5 tests were run, 1 failed, 0 were skipped. Tests took 482ms
Press [r] to re-run, [v] to view full results, [p] to pause, [h] for more options>
```

```
Running Tests for the first timeWARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/Users/ia3andy/.m2/repository/org/codehaus/groovy/groovy/3.0.7/groovy-3.0.7.jar) to constructor java.lang.AssertionError(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplug
2021-05-12 17:37:56,834 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#myFavoriteBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.myFavoriteBand(RockBandResourceTest.java:59)
2021-05-12 17:37:56,835 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#mayWeHaveANewBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <405>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.mayWeHaveANewBand(RockBandResourceTest.java:87)

2021-05-12 17:37:56,836 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#is404ABand() failed
: java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "no band found with id: 2"
  Actual: RESTEASY003210: Could not find resource for full path: http://localhost:8081/rock/10

	at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.is404ABand(RockBandResourceTest.java:
2021-05-12 17:38:02,637 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#myFavoriteBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.myFavoriteBand(RockBandResourceTest.java:59)
2021-05-12 17:38:02,637 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#mayWeHaveANewBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <405>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.mayWeHaveANewBand(RockBandResourceTest.java:87)

2021-05-12 17:38:02,638 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#is404ABand() failed
: java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "no band found with id: 2"
  Actual: RESTEASY003210: Could not find resource for full path: http://localhost:8081/rock/10

	at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.is404ABand(RockBandResourceTest.java:
2021-05-12 17:38:29,630 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#myFavoriteBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.myFavoriteBand(RockBandResourceTest.java:59)
2021-05-12 17:38:29,630 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#mayWeHaveANewBand() failed
: java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <405>.

	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.mayWeHaveANewBand(RockBandResourceTest.java:87)

2021-05-12 17:38:29,631 ERROR [io.qua.test] (Test runner thread) Test RockBandResourceTest#is404ABand() failed
: java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "no band found with id: 2"
  Actual: RESTEASY003210: Could not find resource for full path: http://localhost:8081/rock/10

	at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
	at quarkus.world.tour.RockBandResourceTest.is404ABand(RockBandResourceTest.java:


--
Test run failed, 5 tests were run, 1 failed, 0 were skipped. Tests took 482ms
Press [r] to re-run, [v] to view full results, [p] to pause, [h] for more options>
```

Quarkus 2.0.0.Alpha2

**Comment by stuartwdouglas** [comment]
Fixed upstream
