### ISSUE TITLE
Regression Issue in 1.13.4.Final: Keycloak + Authz fails to start with Null Pointer Exception

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#17226]
## Describe the bug
Having a module that worked fine when using `1.13.3.Final`, now using `1.13.4.Final` fails when invoking a resource.

Quarkus Extension:

```xml
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-keycloak-authorization</artifactId>
</dependency>
```

Resource:

```
@Path("/user")
public class UserResource {
    // ...
}
```

Properties:

```
quarkus.oidc.auth-server-url=${KEYCLOAK_HTTP_URL:http://localhost:8180}/auth/realms/test-realm
quarkus.oidc.client-id=test-application-client
quarkus.oidc.credentials.secret=test-application-client-secret
# tolerate 1 minute of clock skew between the Keycloak server and the application
quarkus.oidc.token.lifespan-grace=60

quarkus.keycloak.policy-enforcer.enable=true
quarkus.keycloak.policy-enforcer.paths.health.path=/q/*
quarkus.keycloak.policy-enforcer.paths.health.enforcement-mode=DISABLED
```

When running the application and invoking the `/user` resource, it fails with a null pointer exception:

```
ERROR: Could not lazy load resource with path [/user] from server
java.lang.NullPointerException
	at org.keycloak.adapters.authorization.PolicyEnforcer$PathConfigMatcher.matches(PolicyEnforcer.java:290)
	at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.getPathConfig(AbstractPolicyEnforcer.java:351)
	at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.authorize(AbstractPolicyEnforcer.java:72)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:55)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:33)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$1$1$1.run(HttpAuthorizer.java:72)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

Previously, the undeclared endpoints were considered secured and we didn't need to explicitly marked them as secured. There is a related issue affecting 2.x: https://github.com/quarkusio/quarkus/issues/17164

In order to workaround this issue, we need to register the endpoints to enforcing:

```
quarkus.keycloak.policy-enforcer.paths.user.path=/*
quarkus.keycloak.policy-enforcer.paths.user.enforcement-mode=ENFORCING
```

I also tried to mark the resources with the `@Authenticated` but made no differences.

### Quarkus version or git rev
1.13.4.Final

**Comment by Sgitario** [comment]
cc @sberyozkin I see the behaviour of the Keycloak Authz is different in 1.13.4.Final and 2.x (see related issue https://github.com/quarkusio/quarkus/issues/17164).

**Comment by sberyozkin** [comment]
@Sgitario Hi, it is a duplicate, but it is good it has been independently reproduced

**Comment by Sgitario** [comment]
> @Sgitario Hi, it is a duplicate, but it is good it has been independently reproduced

@sberyozkin Which is the duplicated issue?

**Comment by sberyozkin** [comment]
@Sgitario Please see #17226

**Comment by Sgitario** [comment]
> @Sgitario Please see #17179

Thanks, closing this one then.

**Comment by sberyozkin** [comment]
@Sgitario thanks, see the workaround therein the description
