### ISSUE TITLE
Logging Request Entity Body with Quarkus Resteasy Reactive

### ISSUE THREAD

**Issue by KyriacosP** [quarkusio/quarkus#17280]
## Describe the bug
I'm trying to implement a logging filter to log the request and response to the API endpoints of my Quarkus application. I'm using Quarkus 1.13.3.Final and quarkus-resteasy-reactive. I have a problem trying to log the request body when calling a non blocking endpoint. This is the code I'm using to log the request:

````
    @ServerRequestFilter(priority = 0)
    public void getFilter(UriInfo info,HttpServerRequest request,ContainerRequestContext ctx) {
        String uuid = UUID.randomUUID().toString();
        ctx.setProperty("log_id", uuid);
        String body = new BufferedReader(new InputStreamReader(ctx.getEntityStream())).lines().collect(Collectors.joining("\n"));
        ctx.setEntityStream(new ByteArrayInputStream(body.getBytes()));
        logger.info("Request: " + uuid + " Method: "+ ctx.getMethod() + " Path: " + info.getPath() + " Remote Address: " +  request.remoteAddress().toString() + " Body: " + body);
    }

````

### Expected behavior
Log the request body for both blocking and non blocking endpoints

### Actual behavior
This works fine when I'm calling an API endpoint that has the @Blocking annotations but when I call a non blocking API I get the following error:

````

2021-05-17 10:15:29,159 ERROR [org.jbo.res.rea.ser.cor.ExceptionMapping] (vert.x-eventloop-thread-10) Request failed : java.io.UncheckedIOException: java.io.IOException: Attempting a blocking read on io thread
        at java.base/java.io.BufferedReader$1.hasNext(BufferedReader.java:577)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.filters.LogginFilter.getFilter(LogginFilter.java:45)
        at com.filters.LogginFilter$GeneratedServerRequestFilter$getFilter.filter(LogginFilter$GeneratedServerRequestFilter$getFilter.zig:73)
        at com.filters.LogginFilter$GeneratedServerRequestFilter$getFilter_Subclass.filter$$superaccessor1(LogginFilter$GeneratedServerRequestFilter$getFilter_Subclass.zig:201)
        at com.filters.LogginFilter$GeneratedServerRequestFilter$getFilter_Subclass$$function$$3.apply(LogginFilter$GeneratedServerRequestFilter$getFilter_Subclass$$function$$3.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)

````
Is this the expected behavior or is this a bug? If this is the expected behavior for non blocking endpoints is there a way to log the incoming request body (without going into every individual endpoint and logging the body) ?

### Output of `java -version`
Java version: 11.0.9, vendor: Oracle Corporation,

### Quarkus version or git rev
Quarkus 1.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3

**Comment by geoand** [comment]
I am changing this to a feature request as the JAX-RS way of reading the entire body is definitely blocking, but it does make sense to provide an alternative that will allow users to read the body in request filters

**Comment by KyriacosP** [comment]
Thank you!

**Comment by geoand** [comment]
👍🏼

**Comment by geoand** [comment]
I was thinking about this and I actually would like to know more about the use case.
How come you need to log the request body in a request filter? What's the end result you are trying to achieve)

**Comment by KyriacosP** [comment]
Our main use case is business related, having logs for the request and response of API calls enables the support team to help customers and integrators identify issues more easily and also makes the integration between different services implemented by different teams easier.

**Comment by geoand** [comment]
So what kind of information do these logs contain? Just generic HTTP related info?

**Comment by KyriacosP** [comment]
They contain the endpoint, info about the caller, path and query parameters, the request body and an identifier for each request. For the response the contain the response body and the identifier.

**Comment by geoand** [comment]
I can't shake the feeling that this is something that we could do ourselves and not expose.

@FroMage @stuartwdouglas WDYT?

**Comment by FroMage** [comment]
I'm not sure, I guess it depends on how filters and reader interceptors interact. I don't think we want to invoke reader interceptors while in the middie of the first filter.

**Comment by AmsterdamFilho** [comment]
+1

**Comment by tsfullman** [comment]
+1

**Comment by mihaipoenaru** [comment]
For the use case of "logging inbound requests for debugging/support purposes", couldn't we just achieve this by putting that entire body inside a Uni and then doing something like `subscribe().with(log::debug)` ? It would make this filter non blocking.

**Comment by PvlPech** [comment]
+1

**Comment by stuartwdouglas** [comment]
I think the current solution would be to inject the `org.jboss.resteasy.reactive.server.spi.ServerHttpRequest` and call `setReadListener` to do a non-blocking read.

**Comment by PvlPech** [comment]
Can't we just use io.vertx.core.Future processing to resolve the initial issue? So, in @KyriacosP's example it's possible to add something like
`Future<Buffer> body = request.body();
        body.onComplete(ar -> {
            if (ar.failed()) {
                /*...*/
            } else {
                logger.info("Request body: " + ar.result());
            }
        });`

**Comment by krakzk** [comment]
+1

**Comment by GavinRay97** [comment]
+1

**Comment by silviu-negoita** [comment]
Also needed. Trying to inject `org.jboss.resteasy.reactive.server.spi.ServerHttpRequest` but I got `javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.jboss.resteasy.reactive.server.spi.ServerHttpRequest and qualifiers [@Default]`

**Comment by GavinRay97** [comment]
PvlPech's answer works perfectly, this is what we have in our repo.
(We use `resteasy-reactive`, if it makes a difference)

Might be worth making a FAQ/documentation entry on.
Or creating a StackOverflow question and self-answering so others can find:

```kt
import io.vertx.core.http.HttpServerRequest
import org.jboss.logging.Logger
import org.jboss.resteasy.reactive.server.ServerRequestFilter
import javax.inject.Inject
import javax.ws.rs.container.ContainerRequestContext
import javax.ws.rs.core.UriInfo

class Filters {
    @Inject
    private lateinit var logger: Logger

    @ServerRequestFilter(priority = 0)
    fun logBodyFilter(info: UriInfo, request: HttpServerRequest, ctx: ContainerRequestContext) {
        request.body { buffer ->
            logger.debug("Request body: ${buffer.result()}")
        }
    }
}
```

**Comment by silviu-negoita** [comment]
@GavinRay97  I tried this solution but my body handler is never called (your logger in the example)

**Comment by silviu-negoita** [comment]
Update: I found the issue. Apparently if you are not consuming the body in your rest controller, handler is never invoked. Not sure this is a bug or a feature. But nice to know.

**Comment by ngannt1710** [comment]
I use Future<Buffer> bufferFuture = request.body();
                bufferFuture.onComplete(bufferAsyncResult -> {} to read request body. But when I modify and set again to request body with context.setEntityStream(new ByteArrayInputStream(data.getBytes())); It is not working in async function

**Comment by csotiriou** [comment]
@stuartwdouglas can you please mention how we can inject ServerHttpRequest? 

 I get ` Parameter 'request' of method 'filter of class 'com.example.ModuleFilters' is not allowed` when I'm trying to inject it to my resteasy reactive filter method.

**Comment by RamonaBarbieru** [comment]
Confirming that this feature is needed on our project.

**Comment by miladjafary** [comment]
We also need this feature 👍

**Comment by miladjafary** [comment]
the @GavinRay97 and @PvlPech workaround has also worked form me. Thanks guys.

**Comment by DudekJakub** [comment]
Hello guys. 

I have very similar case but when it comes to my code: I need to obtain request body right after any exception is thrown so in result I'll have logged out only request bodies from failures. 

What I've tried so far is using ContainerRequestContext like this:

 ```
@ServerExceptionMapper
    fun mapException(exception: Throwable, requestContext: ContainerRequestContext): Uni<Response> {
        filter(requestContext)
        return Uni.createFrom().nullItem() // ignore it
    }

    private fun filter(requestContext: ContainerRequestContext) {
        Vertx.vertx().executeBlocking { promise ->
            try {
                val text = requestContext.entityStream.bufferedReader().use { it.readText() }
                logger.info { "Size of entity stream: ${text.length}" }
                promise.complete(text)
            } catch (e: Exception) {
                promise.fail(e)
            }
        }.onComplete { println(it.result().toString()) }
    } 

```
but the problem is that at this point request body is already consumed by JAX-RS so in result log always shows " Size of entity stream: 0"

Then I tried some workaround and even tho it works as expected, it has some vulnerabilities:

   ```
 companion object {
        val map: MutableMap<String, AsyncResult<Buffer>> = mutableMapOf()
    }

@ServerRequestFilter(priority = 0)
    fun populateMap(request: HttpServerRequest) {
        val id = request.headers()[ID] // all of my requests have ID header but even with it, due to some business cases it is not best to correlate it with particular requestBody
        request.body().onComplete { map[id] = it }
    }

    @Scheduled(every = "1m") // ignore time, it is just for testing
    fun cleanMap() {
        logger.info { "Cleaning the map [$map] right now..." }
        map.clear()
        logger.info { "Map has been cleaned up [$map]" }
    }
    
```

then I can easily read requestBody from the map wherever I want but still, it doesn't look like the most optimal solution. Imagine somebody sends 2 requests with identical ID in header but different requestBody -> there is non-0 chance that in my map key-value will be replaced and in result logged requestBody won't match for given request. Also it requires alocating some memories for my map...

Do you have any tips/solutions I can try to log request body only when response is failure (any exception thrown)? I'd be glad for any help. Thanks in advance.

**Comment by FroMage** [comment]
@geoand didn't you work on logging http requests in RR in the past? I can't find mention of it in https://quarkus.io/guides/resteasy-reactive

**Comment by geoand** [comment]
I don't think we ever came to a good solution

**Comment by hungchu0912** [comment]
+1

**Comment by nitinty** [comment]
Hello Guys,

I’ve implemented the following to log the request body. Could you guys please check it, if it meets the requirements or helps ?


`import io.quarkus.arc.properties.IfBuildProperty;
import io.smallrye.mutiny.Uni;
import io.smallrye.mutiny.infrastructure.Infrastructure;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.core.MediaType;
import lombok.extern.slf4j.Slf4j;
import org.dt.core.platform.exception.ServiceRuntimeException;
import org.dt.core.platform.rest.quarkus.filter.requestcopy.RequestCopyFilterConfig;
import org.jboss.resteasy.reactive.server.ServerRequestFilter;
import org.jboss.resteasy.reactive.server.spi.ResteasyReactiveContainerRequestContext;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;


@IfBuildProperty(name = "config.filter.request.copy.props.enabled", stringValue = "true")
@Slf4j
@ApplicationScoped
public class RequestCopyFilter {
    @Inject
    private RequestCopyFilterConfig requestCopyFilterConfig;

    @ServerRequestFilter
    public Uni<Void> filter(ResteasyReactiveContainerRequestContext requestContext) {

        return readRequestBody(requestContext)
                .onItem().invoke(body -> log.debug("Request body - {} received in filter for uri - {}", body, requestContext.getUriInfo().getRequestUri()))
                .replaceWithVoid();

    }

    private Uni<String> readRequestBody(ResteasyReactiveContainerRequestContext context) {
        if (isMultiPartRequest(context)) {
            return Uni.createFrom().item(""); // Return empty string for multipart requests
        }
        return Uni.createFrom().item(() -> {
                    // Blocking code to read the request body
                    try {
                        byte[] body = context.getEntityStream().readAllBytes();
                        context.setEntityStream(new ByteArrayInputStream(body)); // Reset stream
                        return new String(body, StandardCharsets.UTF_8);
                    } catch (Exception e) {
                        throw new ServiceRuntimeException(e);
                    }
                })
                .runSubscriptionOn(Infrastructure.getDefaultWorkerPool()); // Offload to worker thread
    }

    private boolean isMultiPartRequest(ResteasyReactiveContainerRequestContext context) {
        MediaType mediaType = context.getMediaType();
        return mediaType != null && mediaType.isCompatible(MediaType.MULTIPART_FORM_DATA_TYPE);
    }
    
}`

**Comment by FroMage** [comment]
That's not the same at all as https://github.com/quarkusio/quarkus/issues/22213 but if it works for you that's great :)

**Comment by csotiriou** [comment]
I believe that we have found a "definitive" solution for this, which works under all circumstances. The solution for us seemed to be the usage of `ReaderInterceptor` and `WriterInterceptor`. 

The following is a snipped / pseudocode. The concept is to catch the body before it is being read by / sent to the client, read the streams, and replace them with a new one.

```java
public class BodyLoggerInterceprot implements ReaderInterceptor, WriterInterceptor {
    private final MyLogger logger;
    
    @Override
    public void aroundWriteTo(WriterInterceptorContext context) throws IOException, WebApplicationException {
        //retrieve the logging body
        var originalStream = context.getOutputStream();
        try (var baos = new LoggingBufferOutputStream(originalStream)) {
            context.setOutputStream(baos);
            context.proceed();
            var output = baos.toByteArray();
            logTransaction.setPayload(new String(output, StandardCharsets.UTF_8)); // <-- this is the body!
        } catch (Exception e) {
            //not sure about that, we need to check
            context.setOutputStream(originalStream);
        }
    }

    @Override
    public Object aroundReadFrom(ReaderInterceptorContext context) throws IOException, WebApplicationException {
        InputStream originalInputStream = context.getInputStream();
        // Convert InputStream to String
        String body = Streams.toString(originalInputStream); // <-- This is the line that reads the body!
        // Reset the stream so it can be read again in the actual processing
        context.setInputStream(new ByteArrayInputStream(body.getBytes()));
        // Proceed with the rest of the interceptor chain
    }
}

```

## Two notes:
### Usage of `LoggingBufferOutputStream` 
this is required because of this issue: https://github.com/quarkusio/quarkus/issues/41051 . So instead of something else, we are using a filtered stream to ensure that the original is not tampered with inside Quarkus. 

Here is the code for your convenience:
```java
/**
 * A {@link FilterOutputStream} that buffers all the data written to it.
 *
 *     The data can be retrieved using {@link #toByteArray()}.
 *     The buffer is closed when this stream is closed.
 * This is used to log the payload of a request or response, while at the
 * same time allowing the request or response to be processed as usual.
 */
public class LoggingBufferOutputStream extends FilterOutputStream {
    private final ByteArrayOutputStream buffer;

    public LoggingBufferOutputStream(OutputStream out) {
        super(out);
        this.buffer = new ByteArrayOutputStream();
    }

    @Override
    public void write(byte b[]) throws IOException {
        buffer.write(b);
        super.write(b);
    }

    public byte[] toByteArray() {
        return buffer.toByteArray();
    }

    @Override
    public void close() throws IOException {
        buffer.close();
        super.close();
    }

    @Override
    public void flush() throws IOException {
        buffer.flush();
        super.flush();
    }
}
```

### Retrieving information from the `ContainerRequestContext` inside the Interceptors

A very nice feature that we have is that whatever you pass to the `ContainerRequestContext` with `setProperty()` you will still have it in the `ReaderInterceptorContext` and `WriterInterceptorContext`. 

Which means that you can prepare all things to be logged in the ContainerRequestFilter, pass it to the context with `setProperty()` and finalize the logging (obtain the body, the properties, and log the entire thing) in the `ReaderInterceptor`s and `WriterInterceptor`s.

The above interceptors work for both the Incoming server requests, and the outbound client requests (microprofile rest client).

**Comment by geoand** [comment]
Thanks for sharing @csotiriou!

**Comment by jnbdz** [comment]
This has been open four years with 35 comments and no PR, and reading back through it the blocker looks like an unmade decision rather than missing effort. Summarising the state of play, since three different directions were proposed and none was ever chosen:

1. **Quarkus REST does it itself, not exposed as API** — @geoand, 2021: *"I can't shake the feeling that this is something that we could do ourselves and not expose."*
2. **An SPI for user filters** — @stuartwdouglas, 2022: *"inject the `org.jboss.resteasy.reactive.server.spi.ServerHttpRequest` and call `setReadListener` to do a non-blocking read"*. @FroMage's concern was ordering: *"I don't think we want to invoke reader interceptors while in the middle of the first filter."*
3. **Traffic dumping** — #22213, which @FroMage pointed people to in 2024, then clarified it is *"not the same at all"* as this.

And in 2024 @geoand summed it up: *"I don't think we ever came to a good solution."*

One thing worth flagging that post-dates most of this thread: **#50205** asks for request/response body logging in the HTTP access log, and there is already a PR against it (#55285). That is a different layer — Vert.x access log rather than a JAX-RS filter — but it covers a large share of what the +1s here are asking for (debugging, auditing, compliance). Anyone implementing this issue should check they are not duplicating that, and it may be that #50205 is simply the better home for the common case.

That leaves the part #50205 does *not* cover: people who want the body inside a `@ServerRequestFilter`, alongside their own correlation ids, tracing spans and business context. Every workaround in this thread is user-space and fragile — several people here hit the same trap where the read only happens if the resource method also consumes the body, and the `setEntityStream` round trip does not behave the same on non-blocking endpoints, which is the original report.

@geoand @FroMage @stuartwdouglas — is any of the three directions above still acceptable to you? Concretely:

- if (1), a config-driven built-in (something like `quarkus.rest.log-request-body=true` bounded by a max size) with no public API at all;
- if (2), a documented, supported way to get the already-buffered body inside a request filter without breaking interceptor ordering;
- or close this in favour of #50205 and #22213 if you consider it covered.

I am happy to implement whichever you pick. What I do not want to do is send a PR that invents public API here when the thread already shows three incompatible ideas about what it should look like.

**Comment by geoand** [comment]
@xstefank had an open PR IIRC

**Comment by FroMage** [comment]
Where?

This issue was about being able to read the body from a filter, specifically in order to do logging.

Perhaps because we didn't have anything that achieved this logging, or perhaps because they had to do something special with logging.

In the first case, what I proposed in #22213 seems like something we should definitely do. In fact, we should do it regardless, I still believe it's a very good feature.

In the second case, then #22213 won't help because they want something _custom_, and so we should still allow people to make sure the body is read in filters. Similar to `withFormRead` I guess, perhaps?

But otherwise, using the regular logs to dump request bodies seems like entirely the wrong way to log requests: it opens the door to log injection in a BIG WAY. My proposal in #22213 to dump each request in its own file seems more reasonable.

But let's face it: if users want to store the request body in a DB (for example), then our #22213 solution won't help and we should still allow custom filters.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/54481 is what I had in mind. You'll see from the review that doing logging of the request body correctly is (almost?) impossible to do properly

**Comment by FroMage** [comment]
OK I see. I guess I would have done it at the Vert.x level as a body handler wrapper/filter. Intuitively it should work in all cases, but this may be overly optimistic :)

**Comment by geoand** [comment]
> Vert.x level as a body handler wrapper/filter

It wasn't attempted like that, but the same problems mentioned in the lengthy review should still apply

**Comment by FroMage** [comment]
I do confess I did not read the many comments, so it's entirely possible 😅
