### ISSUE TITLE
AeshConsole exception happening randomly when killing continuous testing

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#17324]
## Describe the bug

Exception happening randomly when killing continuous testing (using main):
```
Exception in thread "Aesh InputStream Reader"
java.lang.RuntimeException: Unable to read io/quarkus/deployment/dev/console/AeshConsole$4.class
	at io.quarkus.bootstrap.classloading.JarClassPathElement$1$1$1.apply(JarClassPathElement.java:131)
	at io.quarkus.bootstrap.classloading.JarClassPathElement$1$1$1.apply(JarClassPathElement.java:118)
	at io.quarkus.bootstrap.classloading.JarClassPathElement.withJarFile(JarClassPathElement.java:161)
	at io.quarkus.bootstrap.classloading.JarClassPathElement$1$1.getData(JarClassPathElement.java:118)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:435)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:397)
	at io.quarkus.deployment.dev.console.AeshConsole.lambda$setup$0(AeshConsole.java:160)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:105)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:31)
	at org.aesh.terminal.io.Decoder.write(Decoder.java:133)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:216)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:1008)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1018)
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:468)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at io.quarkus.bootstrap.classloading.JarClassPathElement.readStreamContents(JarClassPathElement.java:250)
	at io.quarkus.bootstrap.classloading.JarClassPathElement$1$1$1.apply(JarClassPathElement.java:123)
	... 14 more
```

project: https://github.com/ia3andy/rock-rock-rock

**Comment by ia3andy** [comment]
I have to kill jave when it happens

**Comment by stuartwdouglas** [comment]
Have you recompiled Quarkus while Quarkus was running in dev mode?

**Comment by ia3andy** [comment]
Arggg does this really have an effect 😱 I was suspecting it..

**Comment by ia3andy** [comment]
Good catch thanks!

**Comment by stuartwdouglas** [comment]
This has happened to me enough times that I think it is worth fixing (on a 'best effort basis', depending on the changes made shutdown may still hang)
