### ISSUE TITLE
Cannot inject io.vertx.mutiny.ext.web.RoutingContext in @Route annotated method

### ISSUE THREAD

**Issue by symphony-youri** [quarkusio/quarkus#17412]
## Describe the bug
In the documentation (https://quarkus.io/guides/reactive-routes#reactive-route-methods), it is written that a `RoutingContext` (Mutiny Smallrye one) can be injected in a @Route annotated method. However trying to do that raises an exception.

### Expected behavior

`io.vertx.mutiny.ext.web.RoutingContext` can be injected in a @Route method.

### Actual behavior

Exception is raised at startup with the message:

```
2021-05-21 15:31:34,176 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.vertx.web.deployment.VertxWebProcessor#validateBeanDeployment threw an exception: java.lang.IllegalStateException: No parameter injector found for parameter 0 of route method io.smallrye.mutiny.Uni<java.lang.String> proxyPost(io.vertx.mutiny.ext.web.RoutingContext context) declared on CLASS bean [types=[com.symphony.scrypto.proxy.CryptoProxyController, java.lang.Object], qualifiers=[@Default, @Any], target=com.symphony.scrypto.proxy.CryptoProxyController]
	at io.quarkus.vertx.web.deployment.VertxWebProcessor.validateRouteMethod(VertxWebProcessor.java:494)
	at io.quarkus.vertx.web.deployment.VertxWebProcessor.validateBeanDeployment(VertxWebProcessor.java:171)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)```


## To Reproduce

Create a route like:
```
@Route(path = "/*", produces = "application/json")
public Uni<String> route(io.vertx.ext.web.RoutingContext rc) {

}
```

### Quarkus version or git rev

1.13.3

**Comment by cescoffier** [comment]
//CC @mkouba

**Comment by cescoffier** [comment]
The problem seems to be the injection of the routing context, while you are returning a `Uni`. Do you need the full routing context? Did you try with just the HTTP request?

**Comment by mkouba** [comment]
@symphony-youri Hm, the docs is wrong we don't support the `io.vertx.mutiny.ext.web.RoutingContext`. However, you can use `io.vertx.ext.web.RoutingContext` or the mutiny versions of the request/response, i.e. `io.vertx.mutiny.core.http.HttpServerRequest` and `io.vertx.mutiny.core.http.HttpServerResponse`.

**Comment by mkouba** [comment]
@cescoffier I think that we should just remove the mutiny version of RC from the docs. WDYT?

**Comment by symphony-youri** [comment]
(waouh super fast feedback)

Indeed it was working with the Http Request (mutiny or vertx ones) and with the vertx RoutingContext too.
Right now I'm working around that with:
`io.vertx.mutiny.ext.web.RoutingContext context = new io.vertx.mutiny.ext.web.RoutingContext(rc);`

Maybe the documentation should be updated then to avoid the confusion?
I opened https://github.com/quarkusio/quarkus/pull/17414 for that.
