### ISSUE TITLE
Register Hibernate @GenericGenerator strategy implementations for reflective access

### ISSUE THREAD

**Issue by kabir** [quarkusio/quarkus#1743]
@Sanne (as discussed on Zulip):
I have an entity using org.hibernate.id.UUIDGenerator:
```
public class AuthenticationRequest {

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator"
    )
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;
```
This works fine in Java but when running in native mode I get:
```
Caused by: org.hibernate.MappingException: Could not interpret id generator strategy [org.hibernate.id.UUIDGenerator]
    at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.getIdentifierGeneratorClass(DefaultIdentifierGeneratorFactory.java:144)
    at org.hibernate.mapping.SimpleValue.isIdentityColumn(SimpleValue.java:378)
    at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:60)
    at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:30)
    at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createFromMetadata(SchemaCreatorImpl.java:316)
    at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:166)
    at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:135)
    at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:121)
    at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:155)
```
Kabir Khan: Is there some trick I need to perform, or is it a bug?
Kabir Khan: BTW I am planning on ripping out this entity so it isn't a huge deal
Sanne Grinovero: @Kabir Khan ah! thanks that's a useful bugreport :) Yes we probably need to register those strategy implementations for reflective access, didn't think of that.
Kabir Khan: Cool

**Comment by gsmet** [comment]
Ah ah, was answering exactly what Sanne said and then I saw your discussion at the bottom.

**Comment by Sanne** [comment]
We can explore solving this in two different ways:
- look for the `@GenericGenerator` annotations and see if they mention classes which need to be registered for reflection
- make sure tha all identifier generators are constructed during augmentation

I suspect doing the first is easier and maybe the best way to ship a solution already; the second approach could be more efficient but we need to check if it's feasible, e.g. some generators might need to perform initialization steps which are not suitable to run at this stage.
