### ISSUE TITLE
Injecting ConfigMapping in same class as requestscoped observer causes NoSuchElementException

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#17466]
## Describe the bug
My app consists of a configmapping like this:
```
@ConfigMapping(prefix = "some")
public interface SomeConfigMapping {
    @WithName("value")
    String value();
}
```

And an observer like this:

```
public class SomeObserver {
    @Inject
    SomeConfigMapping config;

    public void initializeMDC(@Observes @Initialized(RequestScoped.class) Object o) {
        System.out.println(o.getClass().getName());
        System.out.println(o);
        System.out.println(config.value());
    }
}
```

The app does not start with the exception from below.

If I now remove all references to the config, I get the following output:
```
java.lang.String
io.quarkus.arc.impl.RequestContext@28368e19
java.lang.String
io.quarkus.arc.impl.RequestContext@28368e19
java.lang.String
io.quarkus.arc.impl.RequestContext@28368e19
java.lang.String
io.quarkus.arc.impl.RequestContext@28368e19
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-05-26 08:54:48,102 INFO  [io.quarkus] (Quarkus Main Thread) requestscoped-test 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.13.4.Final) started in 2.868s. Listening on: http://localhost:8080
2021-05-26 08:54:48,114 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-05-26 08:54:48,115 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi]
```

I believe this to be the root cause. The observer is called multiple times before quarkus is started - and most likely also before the configmapping is fully initialized.

### Expected behavior
Quarkus should start without problems.

### Actual behavior
```
Listening for transport dt_socket at address: 5005
2021-05-26 08:44:04,440 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:277)
        ... 15 more
Caused by: java.lang.RuntimeException: Failed to initialize Arc
        at io.quarkus.arc.Arc.initialize(Arc.java:26)
        at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:40)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy_0(ArcProcessor$generateResources-1025303321.zig:76)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources-1025303321.deploy(ArcProcessor$generateResources-1025303321.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:213)
        ... 15 more
Caused by: java.lang.RuntimeException: Error injecting org.acme.SomeConfigMapping org.acme.GreetingResource.config
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:240)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:263)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at org.acme.GreetingResource_Observer_initializeMDC_d697d0f74ac443caeb8121212f7b9ce9c0229d97.notify(GreetingResource_Observer_initializeMDC_d697d0f74ac443caeb8121212f7b9ce9c0229d97.zig:178)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:264)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:218)
        at io.quarkus.arc.impl.RequestContext.fireIfNotEmpty(RequestContext.java:193)
        at io.quarkus.arc.impl.RequestContext.activate(RequestContext.java:121)
        at io.quarkus.arc.ManagedContext.activate(ManagedContext.java:15)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:218)
        at io.quarkus.arc.impl.ArcContainerImpl.init(ArcContainerImpl.java:177)
        at io.quarkus.arc.Arc.initialize(Arc.java:22)
        ... 19 more
Caused by: java.util.NoSuchElementException: SRCFG00027: Could not find a mapping for org.acme.SomeConfigMapping
        at io.smallrye.config.ConfigMappings.getConfigMapping(ConfigMappings.java:60)
        at io.smallrye.config.ConfigMappings.getConfigMapping(ConfigMappings.java:50)
        at io.smallrye.config.SmallRyeConfig.getConfigMapping(SmallRyeConfig.java:355)
        at io.quarkus.arc.runtime.ConfigMappingCreator.create(ConfigMappingCreator.java:17)
        at org.acme.SomeConfigMapping_2d5671bb9f49e16a6bde817d1dc2ee2e8da3440b_Synthetic_Bean.create(SomeConfigMapping_2d5671bb9f49e16a6bde817d1dc2ee2e8da3440b_Synthetic_Bean.zig:121)
        at org.acme.SomeConfigMapping_2d5671bb9f49e16a6bde817d1dc2ee2e8da3440b_Synthetic_Bean.get(SomeConfigMapping_2d5671bb9f49e16a6bde817d1dc2ee2e8da3440b_Synthetic_Bean.zig:152)
        at org.acme.SomeConfigMapping_2d5671bb9f49e16a6bde817d1dc2ee2e8da3440b_Synthetic_Bean.get(SomeConfigMapping_2d5671bb9f49e16a6bde817d1dc2ee2e8da3440b_Synthetic_Bean.zig:175)
        at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:223)
        ... 38 more

```

1. Download the reproducer: [requestscoped-test.zip](https://github.com/quarkusio/quarkus/files/6544429/requestscoped-test.zip)
2. mvn quarkus:dev
3. The exception from above happens
4. Remove all references to the config
5. mvn quarkus:dev
6. The app starts

### Output of `uname -a` or `ver`
MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys
### Output of `java -version`
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

### Quarkus version or git rev
1.13.4.Final, 2.0.0.Alpha3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\eclipse\tools\apache-maven\bin\..
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\java\11
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by radcortez** [comment]
I'll have a look.

**Comment by radcortez** [comment]
This happens because we only register the mappings in runtime init and observers are executed at static init, so there are not mappings available at this point. Registering the mappings at static init could fix the issue, but this raises a few other questions.

We do have two Config instances, one for static init and another one for runtime init. The static init Config, does not register user config sources and any other customisations. It is mostly used to supply default configuration from build time to each extension. Also, some discovered sources at this stage cause unexpected behaviour so we removed that.

In the Observer case, using `@ConfigProperty` injection works, but the injected values may differ from the ones you will get from the same property in runtime, so I think we should discuss this a bit before moving on with any code.

@mkouba any thoughts?

**Comment by mkouba** [comment]
Hm, we do activate the _request context_ for any observer notification, incl. `@Initialized(ApplicationScoped.class)` (STATIC_INIT) and the events fired in the `VertxHttpRecorder.finalizeRouter()` (RUNTIME_INIT). And that's the reason why `SomeObserver#initializeMDC()` is called during application startup. This behavior is not defined by the spec but we thought it might be useful. When I think about it, it was probably a mistake, at least it does not make much sense for the `@Initialized(ApplicationScoped.class)`. That said, even if we don't activate the request context for `@Initialized(ApplicationScoped.class)` any other event may trigger your observer and cause the same problem.

@manovotn @Ladicek WDYT?

**Comment by manovotn** [comment]
I agree that req. context shouldn't be auto-activated for all observer method notifications.
OTOH I am not sure how many things we'll break by reverting this. A lot of it can be easily fixed by users activating the context themselves should they actually need it but it might still be somewhat disruptive.

**Comment by mkouba** [comment]
> OTOH I am not sure how many things we'll break by reverting this. A lot of it can be easily fixed by users activating the context themselves should they actually need it but it might still be somewhat disruptive.

I'm not sure either but the impact should be rather minimal because users are encouraged to observe `StartupEvent` anyway. We'll keep it for `StartupEvent` but not for `@Initialized(ApplicationScoped.class)` and `@Initialized(RequestScoped.class)` (it should be a noop in this case). Plus we'll add a note to the migration guide.

**Comment by mkouba** [comment]
FTR https://github.com/quarkusio/quarkus/pull/17544

**Comment by Postremus** [comment]
FTR. This case now works since 2.0.0.Final - the app starts. I'll leave it to @radcortez to close this issue.

**Comment by radcortez** [comment]
Great. Thanks!
