### ISSUE TITLE
User provided Rest client @RegisterProvider does not work

### ISSUE THREAD

**Issue by kabir** [quarkusio/quarkus#1748]
I am running into a problem for the following in native
```
@Path("/")
@RegisterRestClient
@RegisterProvider(GitHubApiExceptionMapper.class)
public interface GitHubApiService {

```
which gives
```
Caused by: java.lang.InstantiationException: Type `org.overbaard.review.tool.rest.client.github.GitHubApiExceptionMapper` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:678)
	at io.quarkus.smallrye.restclient.runtime.RestClientBuilderImpl.newInstanceOf(RestClientBuilderImpl.java:342)
	... 69 more
```
Kabir Khan: I tried adding a default constructor but get the same error. How do I add the constructor to the native image? I think I know how to do it in an extension (https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/UUIDGenerator.20(native)/near/161981147) but don't see how to do it for user-provided code

**Ken Finnigan: please raise an issue, it likely means we need to register constructors of classes in that annotation for native image**

**Comment by kenfinnigan** [comment]
Thanks, will take a look before next weeks release
