### ISSUE TITLE
IllegalAccessError invoking non-public @Scheduled method 

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#17492]
## Describe the bug
An IllegalAccessError is thrown when invoking a non-public @Scheduled method, e.g:

@Scheduled(every = "PT10S", concurrentExecution = ConcurrentExecution.SKIP)
void myMethod() {...}

All is fine if the method is public.

Call stack looks like so:

2021-05-27 15:58:27,006 ERROR (executor-thread-2) [SimpleScheduler] Error occured while executing task for trigger IntervalTrigger [id=1_my.redacted.Service_ScheduledInvoker_myMethod_8d0ea617bdcf7cab33987d918fbaeabfd51940d4, interval=10000]
java.lang.IllegalAccessError: class my.redacted.Service_ScheduledInvoker_myMethod_8d0ea617bdcf7cab33987d918fbaeabfd51940d4 tried to access method my.redacted.Service.myMethod()V (my.redacted.Service_ScheduledInvoker_myMethod_8d0ea617bdcf7cab33987d918fbaeabfd51940d4 is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @451b1c01; my.redacted.Service is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6f45da6b)
	at my.redacted.Service_ScheduledInvoker_myMethod_8d0ea617bdcf7cab33987d918fbaeabfd51940d4.invokeBean(Service_ScheduledInvoker_myMethod_8d0ea617bdcf7cab33987d918fbaeabfd51940d4.zig:46)
	at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
	at io.quarkus.scheduler.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
	at io.quarkus.scheduler.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:19)
	at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.run(SimpleScheduler.java:251)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:486)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1450)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

### Expected behavior

Expect it to work ok with default access per other Quarkus/CDI methods.

### Actual behavior

Fails with IllegalAccessError.

### Quarkus version or git rev

2.0.0.CR1

**Comment by mkouba** [comment]
Hello @jimbogithub, could you describe your application structure in more detail? We use the package-private `@Scheduled` methods in the tests and in the quickstart without any problem. Private methods are not supported.

It seems that the invoker class and the service class are loaded by a different class loader. Isn't the `my.redacted.Service` class located in a shared library, i.e. outside the application `src/main/java`?

**Comment by jimbogithub** [comment]
> Hello @jimbogithub, could you describe your application structure in more detail? We use the package-private `@Scheduled` methods in the tests and in the quickstart without any problem. Private methods are not supported.
> 
> It seems that the invoker class and the service class are loaded by a different class loader. Isn't the `my.redacted.Service` class located in a shared library, i.e. outside the application `src/main/java`?

Yes, you're correct, the `my.redacted.Service` class is located in a shared library (actually just a test dependency in this case as part of a semi-integration test of two interrelated modules).

Looks like you have the fix, thanks.

**Comment by jimbogithub** [comment]
Confirmed fixed for me in 2.0.0.CR2.
