### ISSUE TITLE
2.0.0.CR2 liquibase finds duplicated changelog files

### ISSUE THREAD

**Issue by Shohou** [quarkusio/quarkus#17523]
## Describe the bug
I have an app which uses gradle for building and I tried to run it with quarkus 2.0.0.CR2. Unfortunately running `./gradlew clean build` failed because liquibase finds two files for changelog.xml
```
                    Caused by:
                    java.io.IOException: Found 2 files that match db/changeLog.xml: file:/C:/Users/d.shohovs/projects/abcmobile/accounting/jpa/src/main/resources/db/changeLog.xml, file:/C:/Users/d.shohovs/projects/abcmobile/accounting/jpa/build/resources/main/db/changeLog.xml
                        at liquibase.resource.AbstractResourceAccessor.openStream(AbstractResourceAccessor.java:25)
                        at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:48)
                        ... 78 more
```
Running quarkusDev works fine though. 

### Expected behavior
liquibase runs applies changelog.xml successfully

### Actual behavior
See exception

## To Reproduce

I believe adding liquibase changelog to the standard location in /src/main/resources/db/changelog.xml and making tests execute it by adding properties to /src/test/resources/application.properties
```
quarkus.liquibase.change-log=db/changeLog.xml
quarkus.liquibase.migrate-at-start=true
```
should reproduce the issue

### Output of `java -version`
openjdk 11.0.9.1 2020-11-04

### Quarkus version or git rev
2.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.8.3

**Comment by geoand** [comment]
I was not able to reproduce this in a Liquibase example we have.

Can you add a reproducer please?

**Comment by Shohou** [comment]
@geoand 
Here it is
https://github.com/Shohou/quarkus-liquibase-bug

This issue can be reproduced in multimodule gradle project. In simple one module project build passes

To reproduce checkout master and run `./gradlew build`
Branch 1.13.6 has version 1.13.6.Final and `./gradlew build` passes successfully

**Comment by glefloch** [comment]
It looks like it tries to import the file from both the source and the build directories. I will have a look.

**Comment by glefloch** [comment]
Running the sample project with `999-SNAPSHOT`, I have the following error: 

```
 org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
        at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:855)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:819)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
```

with that cause: 
```
        Caused by:
        java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
            at io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.instance(RunningQuarkusApplicationImpl.java:85)
            at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:838)
            ... 86 more

            Caused by:
            java.lang.reflect.InvocationTargetException
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.instance(RunningQuarkusApplicationImpl.java:80)
                ... 87 more

                Caused by:
                java.lang.IllegalStateException: Unable to locate CDIProvider
                    at javax.enterprise.inject.spi.CDI.findAllProviders(CDI.java:121)
                    at javax.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:82)
                    at javax.enterprise.inject.spi.CDI.current(CDI.java:64)
```

@geoand do you have any pointers on this error ?

**Comment by geoand** [comment]
That seems to indicate that Arc was not started... 
That is super weird... @mkouba any idea how that can happen?

**Comment by mkouba** [comment]
> any idea how that can happen?

I have no idea. But the fact that no `CDIProvider` is found does not necessarily imply that ArC was not started. It could be a class loading problem, i.e. the `javax.enterprise.inject.spi.CDI` from the stack is a different class than the one used by ArC when setting the provider via `CDI.setCDIProvider(CDIProvider)`.

**Comment by Sabartius** [comment]
We upgraded serveral of our Multi-Maven-Module Projects from 1.13.x to 2.0.2 and face similar errors in our QuarkusTests

```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.IllegalStateException: Error starting Liquibase
Caused by: liquibase.exception.ChangeLogParseException: Error Reading Changelog File: Found 2 files that match liquibase/changelog.xml: file:/workspace/myProject/moduleB/target/classes/liquibase/changelog.xml, jar:file:///workspace/myProject/moduleB/target/myProject-moduleB-1.0-SNAPSHOT.jar!/liquibase/changelog.xml
```

the classpath seems to contain the changelog from the jar and target-directory 🤔

**Comment by laemm-line** [comment]
I'm having the same problem in a multi-module Gradle project.
Gradle: 7.1.1
Quarkus: 2.1.0.Final

**Comment by Shohou** [comment]
This issue is not reproducible since version 2.4.0.Final, so closing it.
