### ISSUE TITLE
ConfigProvider doesn't work during runtime with fast-jar

### ISSUE THREAD

**Issue by luneo7** [quarkusio/quarkus#17559]
## Describe the bug
During runtime if using ConfigProvider programmatically to get some config property it fails with null pointer exception trying to fetch stuff from the class loader with fast-jar

### Expected behavior
We are able to fetch config without issues

### Actual behavior
Null pointer exception

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

- https://github.com/luneo7/fast-jar-config-provider

Steps to reproduce using the repository above:

1. ./mvnw package
2. docker build -f src/main/docker/Dockerfile.jvm -t quarkus/code-with-quarkus-jvm .
3. docker run -i --rm -p 8080:8080 quarkus/code-with-quarkus-jvm
4. Hit http://localhost:8080/hello-resteasy

Or attach an archive containing the reproducer to the issue.

1. Use a custom meter registry (Graphite for instance)
2. Create a singleton producer and pass to the config property something like this:
```
    private String graphiteConfig(String property) {
        return ConfigProvider.getConfig()
                             .getOptionalValue(property, String.class)
                             .orElseGet(() -> GraphiteConfig.DEFAULT.get(property));
    }
```
3. Build and run with fast-jar, hit one endpoint to generate metrics and you will get this:
```
java.lang.NullPointerException
        at io.smallrye.common.classloader.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:83)
        at io.smallrye.config.AbstractLocationConfigSourceLoader.tryClassPath(AbstractLocationConfigSourceLoader.java:128)
        at io.smallrye.config.AbstractLocationConfigSourceLoader.loadConfigSources(AbstractLocationConfigSourceLoader.java:93)
        at io.smallrye.config.AbstractLocationConfigSourceLoader.loadConfigSources(AbstractLocationConfigSourceLoader.java:76)
        at io.smallrye.config.PropertiesConfigSourceProvider.<init>(PropertiesConfigSourceProvider.java:37)
        at io.smallrye.config.PropertiesConfigSourceProvider.classPathResource(PropertiesConfigSourceProvider.java:77)
        at io.smallrye.config.PropertiesConfigSourceProvider.classPathSources(PropertiesConfigSourceProvider.java:85)
        at io.smallrye.config.SmallRyeConfigBuilder.getDefaultSources(SmallRyeConfigBuilder.java:162)
        at io.smallrye.config.SmallRyeConfig.buildConfigSources(SmallRyeConfig.java:79)
        at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:68)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:402)
        at io.smallrye.config.SmallRyeConfigFactory$Default.getConfigFor(SmallRyeConfigFactory.java:59)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:64)
        at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
        at org.acme.MetricsConfig.graphiteConfig(MetricsConfig.java:84)
        at io.micrometer.core.instrument.config.validate.PropertyValidator.getDuration(PropertyValidator.java:42)
        at io.micrometer.core.instrument.dropwizard.DropwizardConfig.step(DropwizardConfig.java:37)
        at io.micrometer.core.instrument.dropwizard.DropwizardMeterRegistry.defaultHistogramConfig(DropwizardMeterRegistry.java:159)
        at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:310)
        at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:614)
        at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:568)
        at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:308)
        at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:400)
        at io.micrometer.core.instrument.composite.CompositeTimer.registerNewMeter(CompositeTimer.java:140)
        at io.micrometer.core.instrument.composite.CompositeTimer.registerNewMeter(CompositeTimer.java:31)
        at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:66)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5581)
        at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$0(CompositeMeterRegistry.java:65)
        at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:184)
        at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$1(CompositeMeterRegistry.java:65)
        at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:624)
        at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:568)
        at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:308)
        at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:400)
        at io.micrometer.core.instrument.binder.jvm.JvmGcMetrics.lambda$bindTo$4(JvmGcMetrics.java:152)
        at java.management/sun.management.NotificationEmitterSupport.sendNotification(NotificationEmitterSupport.java:155)
        at jdk.management/com.sun.management.internal.GarbageCollectorExtImpl.createGCNotification(GarbageCollectorExtImpl.java:115)
```

### Configuration
```properties
quarkus.application.name=test-app
quarkus.http.port=8080
current.env=test

graphite.rateUnits=SECONDS
graphite.durationUnits=MILLISECONDS
graphite.graphiteTagsEnabled=false
graphite.protocol=PLAINTEXT
graphite.step=1m
graphite.host=localhost
graphite.port=2004

%test.graphite.enabled=false

```

**Comment by luneo7** [comment]
I know that the way that it is fetching the property from the config provider is sub optimal, and now we have the Graphite extension at https://github.com/quarkiverse/quarkus-micrometer-registry but I found that getting a config value during runtime using fas-jar was a bug either way... and the Graphite thing was just to illustrate it

**Comment by radcortez** [comment]
I'll have a look.

**Comment by radcortez** [comment]
I was not able to reproduce this on my own box (OS X), but only with the Docker container.

I observed that one of Micrometer registrations happens only when you call the REST endpoint in the Docker image, while in my local box it happens at startup time. I suspect that this is related to `JvmGcMetrics` registration, which may be related to different JVMs.

Now, the reason for the NPE is because each `Config` instance is registered with its own classloader and `ConfigProvider` retrieves the correct instance based on the context classloader. For some reason, we don't have a context classloader in the thread that is trying to use the `Config` so we try to create a new `Config` instance and it fails when a lookup is required to search for the configuration files.

Even if the lookup was ok, it would still be a different `Config` instance, which may yield different results. My recommendation is to just inject the `Config` instance and use the object directly instead of `ConfigProvider.getConfig()`. This will make sure that the same instance is used for all the calls, and remove any additional lookups.

For now, I'll leave this. If this is not good enough, let me know and I'll do more digging to figure out the exact issue. If it is related to the JVM, we may not be able to do much. We already found some significant differences in how env variables are stored for instance.

**Comment by luneo7** [comment]
Yup, dunno if it related to JVM since I am able to reproduce it in OpenJ9, OpenJDK, Corretto, Graal...

But we changed the way of getting the config already and it is working, just opened up the bug report because it only happened when using fast jar, and to keep my conscience clean 😄 

But I am OK on closing it, as we also already have the Graphite extension and fetching every time using the config provider isn't a really good approach.

**Comment by radcortez** [comment]
Thanks!
