### ISSUE TITLE
not able to change log level on a logger 

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#17569]
I want to change the logger level when I'm running my tests.   I want to change the log level of one particular logger, not all the loggers under a package name

In application.properties, I added this line

I try all those separately
quarkus.log.category."com.comact.iep.codec.service.ScannerCodec".level=OFF
quarkus.log.category."com.comact.iep.codec.service.ScannerCodec".level=FATAL
quarkus.log.category."com.comact.iep.codec.service.ScannerCodec".level=SEVERE

but I still see the log in the console

````
15:19:11.629 [executor-thread-1] ERROR c.c.iep.codec.service.ScannerCodec - Unable to retrieve scanners for Node [Node parent machineCodec_1]
org.jboss.resteasy.client.exception.ResteasyWebApplicationException: Unknown error, status code 500
	at org.jboss.resteasy.client.exception.WebApplicationExceptionWrapper.wrap(WebApplicationExceptionWrapper.java:107)
	at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:21)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:39)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:154)
	at com.sun.proxy.$Proxy109.execute(Unknown Source)
````

the logger look like this

````
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

....
public class ScannerCodec extends AbstractCodec {
    private static final Logger LOGGER = LoggerFactory.getLogger(ScannerCodec.class);
````

the other settings are
````
quarkus.log.category."com.comact".level=DEBUG
quarkus.log.level=INFO
quarkus.log.file.enable=true
quarkus.log.file.level=INFO
quarkus.log.file.rotation.max-file-size=20M
quarkus.log.file.rotation.max-backup-index=2
````

**Comment by famod** [comment]
Have you double-checked that `com.comact.iep.codec.service.ScannerCodec` ist correct?

**Comment by survivant** [comment]
we can see that in the log too 
````
15:19:11.629 [executor-thread-1] ERROR c.c.iep.codec.service.ScannerCodec
````

yes, I double checked

**Comment by geoand** [comment]
Is this still an issue?

**Comment by survivant** [comment]
I will check if I still have the issue with the latest release

**Comment by gsmet** [comment]
Closing as stale.
