### ISSUE TITLE
Native build fails after building with Java 9 or later

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#1759]
Native build of sample quarkus-maven-plugin based app fails.

Using current master (56518ac4f), the main error is:
`com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: java.nio.ByteBuffer.limit(int).`

```
mkdir foo
cd foo/
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=quarkus.io -DprojectArtifactId=spfoouickstart -DprojectVersion=1.0-SNAPSHOT -DclassName="io.quarkus.FooResource"
mvn clean package -Pnative
```

```
java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) GraalVM EE 1.0.0-rc14 (build 25.202-b08-jvmci-0.56, mixed mode)
```
Note: the same on GraalVM CE 1.0.0-rc14

```
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /Users/rsvoboda/Downloads/graalvm-ee-1.0.0-rc14/Contents/Home/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar spfoouickstart-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[spfoouickstart-1.0-SNAPSHOT-runner:21184]    classlist:   3,535.03 ms
[spfoouickstart-1.0-SNAPSHOT-runner:21184]        (cap):   1,626.85 ms
[spfoouickstart-1.0-SNAPSHOT-runner:21184]        setup:   2,991.48 ms
11:45:08,531 INFO  [org.xnio] XNIO version 3.7.0.Final
11:45:09,005 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.0.Final
11:45:11,298 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Alpha4
[spfoouickstart-1.0-SNAPSHOT-runner:21184]     analysis:  16,850.79 ms
Printing call tree to /Users/rsvoboda/tmp/foo/target/reports/call_tree_spfoouickstart-1.0-SNAPSHOT-runner_20190329_114524.txt
Printing list of used classes to /Users/rsvoboda/tmp/foo/target/reports/used_classes_spfoouickstart-1.0-SNAPSHOT-runner_20190329_114525.txt
Printing list of used packages to /Users/rsvoboda/tmp/foo/target/reports/used_packages_spfoouickstart-1.0-SNAPSHOT-runner_20190329_114525.txt
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: java.nio.ByteBuffer.limit(int). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: java.nio.ByteBuffer.limit(int). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
	at parsing io.quarkus.undertow.runtime.graal.ChannelsSubstitution.drain(ChannelsSubstitution.java:53)
Call path from entry point to org.xnio.channels.Channels.drain(StreamSourceChannel, long):
	at io.quarkus.undertow.runtime.graal.ChannelsSubstitution.drain(ChannelsSubstitution.java:46)
	at io.undertow.server.HttpServerExchange.endExchange(HttpServerExchange.java:1646)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:385)
	at io.undertow.servlet.spec.AsyncContextImpl$TimeoutTask$1$1.run(AsyncContextImpl.java:525)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to org.xnio.channels.Channels.drain(org.xnio.channels.StreamSourceChannel, long):l
	org.xnio.channels.Channels.drain(org.xnio.channels.StreamSourceChannel, long):l
	io.undertow.server.protocol.http2.Http2ReceiveListener.handleRequests(io.undertow.protocols.http2.Http2Channel, io.undertow.protocols.http2.Http2StreamSourceChannel):v
	io.undertow.server.protocol.http2.Http2ReceiveListener.handleEvent(io.undertow.protocols.http2.Http2Channel):v
	io.undertow.server.protocol.http2.Http2ReceiveListener.handleEvent(io.undertow.protocols.http2.Http2Channel):v
	io.undertow.server.protocol.http2.Http2ReceiveListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.http2.Http2ReceiveListener


Possible path to org.xnio.channels.Channels.drain(org.xnio.channels.StreamSourceChannel, long):l
	org.xnio.channels.Channels.drain(org.xnio.channels.StreamSourceChannel, long):l
	org.xnio.ChannelListeners$DrainListener.handleEvent(org.xnio.channels.StreamSourceChannel):v
	org.xnio.ChannelListeners$DrainListener.handleEvent(org.xnio.channels.StreamSourceChannel):v
	org.xnio.ChannelListeners$DrainListener.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of org.xnio.ChannelListeners$DrainListener


Possible path to org.xnio.channels.Channels.drain(org.xnio.channels.StreamSourceChannel, long):l
	org.xnio.channels.Channels.drain(org.xnio.channels.StreamSourceChannel, long):l
	io.undertow.server.HttpServerExchange.endExchange():i
	io.undertow.server.Connectors.executeRootHandler(io.undertow.server.HttpHandler, io.undertow.server.HttpServerExchange):v
	io.undertow.server.HttpServerExchange$1.run():v
This is an implementation of java.lang.Runnable printing path to constructors of io.undertow.server.HttpServerExchange$1


Possible path to io.undertow.server.protocol.http2.Http2ReceiveListener.<init>(io.undertow.server.HttpHandler, org.xnio.OptionMap, int, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.http2.Http2ReceiveListener.<init>(io.undertow.server.HttpHandler, org.xnio.OptionMap, int, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.http2.Http2OpenListener.handleEvent(org.xnio.StreamConnection, io.undertow.connector.PooledByteBuffer):v
This is an implementation of io.undertow.server.DelegateOpenListener printing path to constructors of io.undertow.server.protocol.http2.Http2OpenListener


Possible path to io.undertow.server.protocol.http2.Http2ReceiveListener.<init>(io.undertow.server.HttpHandler, org.xnio.OptionMap, int, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.http2.Http2ReceiveListener.<init>(io.undertow.server.HttpHandler, org.xnio.OptionMap, int, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.http2.Http2UpgradeHandler$4.handleUpgrade(org.xnio.StreamConnection, io.undertow.server.HttpServerExchange):v
	io.undertow.server.HttpUpgradeListener.handleUpgrade(org.xnio.StreamConnection, io.undertow.server.HttpServerExchange):v
	io.undertow.server.protocol.http.HttpReadListener$2.handleEvent(org.xnio.conduits.ConduitStreamSinkChannel):v
	io.undertow.server.protocol.http.HttpReadListener$2.handleEvent(org.xnio.conduits.ConduitStreamSinkChannel):v
	io.undertow.server.protocol.http.HttpReadListener$2.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.http.HttpReadListener$2


Possible path to io.undertow.server.protocol.http2.Http2ReceiveListener.<init>(io.undertow.server.HttpHandler, org.xnio.OptionMap, int, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.http2.Http2ReceiveListener.<init>(io.undertow.server.HttpHandler, org.xnio.OptionMap, int, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.http.HttpReadListener.doHttp2PriRead(org.xnio.StreamConnection, java.nio.ByteBuffer, io.undertow.server.protocol.http.HttpServerConnection, io.undertow.connector.PooledByteBuffer):b
	io.undertow.server.protocol.http.HttpReadListener.access$000(io.undertow.server.protocol.http.HttpReadListener, org.xnio.StreamConnection, java.nio.ByteBuffer, io.undertow.server.protocol.http.HttpServerConnection, io.undertow.connector.PooledByteBuffer):b
	io.undertow.server.protocol.http.HttpReadListener$3.handleEvent(org.xnio.channels.StreamSourceChannel):v
	io.undertow.server.protocol.http.HttpReadListener$3.handleEvent(org.xnio.channels.StreamSourceChannel):v
	io.undertow.server.protocol.http.HttpReadListener$3.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.http.HttpReadListener$3


Possible path to io.undertow.server.HttpServerExchange$1.<init>(io.undertow.server.HttpServerExchange, io.undertow.server.HttpHandler):v
	io.undertow.server.HttpServerExchange$1.<init>(io.undertow.server.HttpServerExchange, io.undertow.server.HttpHandler):v
	io.undertow.server.HttpServerExchange.dispatch(java.util.concurrent.Executor, io.undertow.server.HttpHandler):i
	io.undertow.server.handlers.form.FormEncodedDataDefinition$FormEncodedDataParser.handleEvent(org.xnio.channels.StreamSourceChannel):v
	io.undertow.server.handlers.form.FormEncodedDataDefinition$FormEncodedDataParser.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.handlers.form.FormEncodedDataDefinition$FormEncodedDataParser


Possible path to io.undertow.server.protocol.http2.Http2OpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.server.protocol.http2.Http2OpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.Undertow.start():v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.doServerStart(io.quarkus.undertow.runtime.HttpConfig, io.quarkus.runtime.LaunchMode, javax.net.ssl.SSLContext):v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.startUndertow(io.quarkus.runtime.ShutdownContext, io.undertow.servlet.api.DeploymentManager, io.quarkus.undertow.runtime.HttpConfig, java.util.List, io.quarkus.runtime.LaunchMode):i
	io.quarkus.deployment.steps.UndertowBuildStep$boot9.deploy(io.quarkus.runtime.StartupContext):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
Possible path to io.undertow.server.protocol.http2.Http2OpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap, java.lang.String):v
	io.undertow.server.protocol.http2.Http2OpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap, java.lang.String):v
	io.undertow.server.protocol.http2.Http2OpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.Undertow.start():v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.doServerStart(io.quarkus.undertow.runtime.HttpConfig, io.quarkus.runtime.LaunchMode, javax.net.ssl.SSLContext):v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.startUndertow(io.quarkus.runtime.ShutdownContext, io.undertow.servlet.api.DeploymentManager, io.quarkus.undertow.runtime.HttpConfig, java.util.List, io.quarkus.runtime.LaunchMode):i
	io.quarkus.deployment.steps.UndertowBuildStep$boot9.deploy(io.quarkus.runtime.StartupContext):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
Possible path to io.undertow.server.protocol.http.HttpReadListener$2.<init>(io.undertow.server.protocol.http.HttpReadListener, io.undertow.server.protocol.http.HttpServerConnection, io.undertow.server.HttpServerExchange):v
	io.undertow.server.protocol.http.HttpReadListener$2.<init>(io.undertow.server.protocol.http.HttpReadListener, io.undertow.server.protocol.http.HttpServerConnection, io.undertow.server.HttpServerExchange):v
	io.undertow.server.protocol.http.HttpReadListener.exchangeComplete(io.undertow.server.HttpServerExchange):v
	io.undertow.server.protocol.http.PipeliningBufferingStreamSinkConduit$1.handleEvent(java.nio.channels.Channel):v
This is an implementation of org.xnio.ChannelListener printing path to constructors of io.undertow.server.protocol.http.PipeliningBufferingStreamSinkConduit$1


Possible path to io.undertow.server.protocol.http.HttpReadListener$3.<init>(io.undertow.server.protocol.http.HttpReadListener, org.xnio.StreamConnection, java.nio.ByteBuffer, io.undertow.server.protocol.http.HttpServerConnection, io.undertow.connector.PooledByteBuffer):v
	io.undertow.server.protocol.http.HttpReadListener$3.<init>(io.undertow.server.protocol.http.HttpReadListener, org.xnio.StreamConnection, java.nio.ByteBuffer, io.undertow.server.protocol.http.HttpServerConnection, io.undertow.connector.PooledByteBuffer):v
	io.undertow.server.protocol.http.HttpReadListener.handleHttp2PriorKnowledge(org.xnio.StreamConnection, io.undertow.server.protocol.http.HttpServerConnection, io.undertow.connector.PooledByteBuffer):v
	io.undertow.server.protocol.http.HttpReadListener.handleHttp2PriorKnowledge(io.undertow.connector.PooledByteBuffer, io.undertow.server.HttpServerExchange):b
	io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(org.xnio.conduits.ConduitStreamSourceChannel):v
	io.undertow.server.protocol.http.HttpReadListener.handleEvent(org.xnio.conduits.ConduitStreamSourceChannel):v
	io.undertow.server.protocol.http.HttpReadListener.run():v
This is an implementation of java.lang.Runnable printing path to constructors of io.undertow.server.protocol.http.HttpReadListener


Possible path to io.undertow.server.handlers.form.FormEncodedDataDefinition$FormEncodedDataParser.<init>(java.lang.String, io.undertow.server.HttpServerExchange, io.undertow.server.handlers.form.FormEncodedDataDefinition$1):v
	io.undertow.server.handlers.form.FormEncodedDataDefinition$FormEncodedDataParser.<init>(java.lang.String, io.undertow.server.HttpServerExchange, io.undertow.server.handlers.form.FormEncodedDataDefinition$1):v
	io.undertow.server.handlers.form.FormEncodedDataDefinition.create(io.undertow.server.HttpServerExchange):i
This is an implementation of io.undertow.server.handlers.form.FormParserFactory$ParserDefinition printing path to constructors of io.undertow.server.handlers.form.FormEncodedDataDefinition


Possible path to io.undertow.server.protocol.http.PipeliningBufferingStreamSinkConduit$1.<init>(io.undertow.server.protocol.http.PipeliningBufferingStreamSinkConduit, org.xnio.StreamConnection, io.undertow.server.protocol.http.HttpServerConnection, io.undertow.server.AbstractServerConnection$ConduitState, io.undertow.server.HttpServerExchange):v
	io.undertow.server.protocol.http.PipeliningBufferingStreamSinkConduit$1.<init>(io.undertow.server.protocol.http.PipeliningBufferingStreamSinkConduit, org.xnio.StreamConnection, io.undertow.server.protocol.http.HttpServerConnection, io.undertow.server.AbstractServerConnection$ConduitState, io.undertow.server.HttpServerExchange):v
	io.undertow.server.protocol.http.PipeliningBufferingStreamSinkConduit.performFlush(io.undertow.server.HttpServerExchange, io.undertow.server.protocol.http.HttpServerConnection):v
	io.undertow.server.protocol.http.PipeliningBufferingStreamSinkConduit.performFlush(io.undertow.server.HttpServerExchange, io.undertow.server.protocol.http.HttpServerConnection):v
	io.undertow.server.protocol.http.PipeliningBufferingStreamSinkConduit.exchangeComplete(io.undertow.server.HttpServerExchange):v
	io.undertow.server.protocol.http.PipeliningBufferingStreamSinkConduit.exchangeComplete(io.undertow.server.HttpServerExchange):v
	io.undertow.server.protocol.http.HttpServerConnection.exchangeComplete(io.undertow.server.HttpServerExchange):v
This is an implementation of io.undertow.server.ServerConnection printing path to constructors of io.undertow.server.protocol.http.HttpServerConnection


Possible path to io.undertow.server.protocol.http.HttpReadListener.<init>(io.undertow.server.protocol.http.HttpServerConnection, io.undertow.server.protocol.http.HttpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.http.HttpReadListener.<init>(io.undertow.server.protocol.http.HttpServerConnection, io.undertow.server.protocol.http.HttpRequestParser, io.undertow.server.ConnectorStatisticsImpl):v
	io.undertow.server.protocol.http.HttpOpenListener.handleEvent(org.xnio.StreamConnection, io.undertow.connector.PooledByteBuffer):v
This is an implementation of io.undertow.server.DelegateOpenListener printing path to constructors of io.undertow.server.protocol.http.HttpOpenListener


Possible path to io.undertow.server.handlers.form.FormEncodedDataDefinition.<init>():v
	io.undertow.server.handlers.form.FormEncodedDataDefinition.<init>():v
	io.undertow.servlet.core.ManagedServlet.setupMultipart(io.undertow.servlet.spec.ServletContextImpl):v
	io.undertow.servlet.core.ManagedServlet.setupMultipart(io.undertow.servlet.spec.ServletContextImpl):v
	io.undertow.servlet.core.ManagedServlet.<init>(io.undertow.servlet.api.ServletInfo, io.undertow.servlet.spec.ServletContextImpl):v
	io.undertow.servlet.core.ManagedServlets.addServlet(io.undertow.servlet.api.ServletInfo):i
	io.undertow.servlet.core.ManagedServlets.addServlet(io.undertow.servlet.api.ServletInfo):i
	io.undertow.servlet.handlers.ServletPathMatches.setupServletChains():i
	io.undertow.servlet.handlers.ServletPathMatches.getData():i
	io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(java.lang.String):i
	io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(java.lang.String):i
	io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(io.undertow.server.HttpServerExchange):v
	io.undertow.server.HttpHandler.handleRequest(io.undertow.server.HttpServerExchange):v
	io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(io.undertow.server.HttpServerExchange):v
This is an implementation of io.undertow.server.HttpHandler printing path to constructors of io.undertow.server.handlers.HttpContinueReadHandler


Possible path to io.undertow.server.protocol.http.HttpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.server.protocol.http.HttpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.Undertow.start():v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.doServerStart(io.quarkus.undertow.runtime.HttpConfig, io.quarkus.runtime.LaunchMode, javax.net.ssl.SSLContext):v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.startUndertow(io.quarkus.runtime.ShutdownContext, io.undertow.servlet.api.DeploymentManager, io.quarkus.undertow.runtime.HttpConfig, java.util.List, io.quarkus.runtime.LaunchMode):i
	io.quarkus.deployment.steps.UndertowBuildStep$boot9.deploy(io.quarkus.runtime.StartupContext):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
Possible path to io.undertow.server.protocol.http.HttpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.server.protocol.http.HttpOpenListener.<init>(io.undertow.connector.ByteBufferPool, org.xnio.OptionMap):v
	io.undertow.Undertow.start():v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.doServerStart(io.quarkus.undertow.runtime.HttpConfig, io.quarkus.runtime.LaunchMode, javax.net.ssl.SSLContext):v
	io.quarkus.undertow.runtime.UndertowDeploymentTemplate.startUndertow(io.quarkus.runtime.ShutdownContext, io.undertow.servlet.api.DeploymentManager, io.quarkus.undertow.runtime.HttpConfig, java.util.List, io.quarkus.runtime.LaunchMode):i
	io.quarkus.deployment.steps.UndertowBuildStep$boot9.deploy(io.quarkus.runtime.StartupContext):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i


Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image building with exit status 1
```

**Comment by rsvoboda** [comment]
I tried the same steps on different machine (RHEL) and native build worked.

**Comment by rsvoboda** [comment]
`mvn package -Pnative -Dnative-image.docker-build=true` fails for me too

macOS 10.14.4 (18E226)

Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: /Users/rsvoboda/Downloads/graalvm-ee-1.0.0-rc14/Contents/Home/jre
Default locale: en_CZ, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.4", arch: "x86_64", family: "mac"

**Comment by rsvoboda** [comment]
After adding `<additionalBuildArgs>-H:+ReportExceptionStackTraces</additionalBuildArgs>` I see longer stacktrace but can't get my head around it.

See https://paste.fedoraproject.org/paste/X36D-p-HJA4MU-OewJIGyw

**Comment by rsvoboda** [comment]
So the issue is that I built Quarkus master using Java 11.

GraalVM is still based on Java 8

**Comment by rsvoboda** [comment]
Reopening 
```
David Lloyd: nah it's a valid issue
David Lloyd: you should be able to build with 11 and not get this error
David Lloyd: I've nearly got a fix
```
