### ISSUE TITLE
javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl

### ISSUE THREAD

**Issue by brenol** [quarkusio/quarkus#1762]
Hello!

I am having a few issues while trying to use SAXParserFactoryImpl and have tried a few things:
- Creating a SAXParserProcessor and registering it with a @BuildStep, however, I'm not sure on how to configure a new extension (is this necessary?);
- Registering it with System.property;
- Tried using the underlying graalVM Class.forName as mentioned in Graal's reflection docs, but no luck;

Even tried a few other things and I'm a little out of ideas now. Can someone help me, please?
I even tried downloading quarkus-jaxb but no luck.

Thanks!

**Comment by brenol** [comment]
Using Class.forName directly:
```
java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParserImpl. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with a constant class name argument.
```

**Comment by danilocgomes** [comment]
I'm facing same error here, do you have any update?

**Comment by dmlloyd** [comment]
I have a patch that should be (mostly) working to solve this but I've hit a Substrate internal error.

**Comment by tjwatson** [comment]
I've hit this issue, but adding `com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl` and `com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl` to the reflect configuration for the native image build seem to work around it.  Is that unexpected?  Or I assume it must have some downsides.

**Comment by dmlloyd** [comment]
The downside to registering things for reflection is that they (and all of their dependents) effectively become ineligible for dead code elimination.  In this case it's probably fine though as the class is clearly used.  But we want to come up with a general solution to cases like this one, which doesn't involve reflection registration.

**Comment by stuartwdouglas** [comment]
Is this still an issue? There have been a lot of fixes in Graal since this was opened.

**Comment by heike2718** [comment]
Hi,

I was just facing an error with a similar message when running my application inside docker. (stacktrace below). In development mode the application was running fine.

I am using quarkus-apache-tika and apache-poi and apache-poi-ooxml

The error occured, when I changed the apache-poi / poi-ooxml dependencies from 4.1.2 to 5.0.0. Maybe this is helpful in some way? 

Probably this is not a quarkus issue.

Regards, Heike.

**Stacktrace**

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:323)
	... 15 more
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not found
	at javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source)
	at org.apache.tika.utils.XMLReaderUtils.getSAXParserFactory(XMLReaderUtils.java:255)
	at org.apache.tika.utils.XMLReaderUtils.setPoolSize(XMLReaderUtils.java:687)
	at org.apache.tika.utils.XMLReaderUtils.<clinit>(XMLReaderUtils.java:151)
	at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:166)
	at io.quarkus.tika.runtime.TikaRecorder.initializeParser(TikaRecorder.java:30)
	at io.quarkus.tika.runtime.TikaRecorder.initTikaParser(TikaRecorder.java:21)
	at io.quarkus.deployment.steps.TikaProcessor$initializeTikaParser1762155120.deploy_0(TikaProcessor$initializeTikaParser1762155120.zig:88)
	at io.quarkus.deployment.steps.TikaProcessor$initializeTikaParser1762155120.deploy(TikaProcessor$initializeTikaParser1762155120.zig:40)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:303)
	... 15 more

**Comment by Clemzd** [comment]
Has anyone found a solution? I am currently experiencing the problem

**Comment by jdussouillez** [comment]
Any updates ?

**Comment by zaro** [comment]
I have the same issue, `quarkus:dev` works fine but the image generated by `quarkus:image-build` fails with :

```
2024-11-18 14:14:16,447 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello/pdf failed, error id: 3b2cdf56-139a-4f86-925d-dbbceac137f1-1: javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not found
        at javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source)
        at org.apache.avalon.framework.configuration.DefaultConfigurationBuilder.<init>(DefaultConfigurationBuilder.java:100)
        at org.apache.avalon.framework.configuration.DefaultConfigurationBuilder.<init>(DefaultConfigurationBuilder.java:83)
        at org.apache.fop.apps.FopConfParser.<init>(FopConfParser.java:147)
        at org.apache.fop.apps.FopConfParser.<init>(FopConfParser.java:89)
        at org.apache.fop.apps.FopConfParser.<init>(FopConfParser.java:104)
        at org.apache.fop.apps.FopFactory.newInstance(FopFactory.java:158)
        at org.acme.GreetingResource.getPdf(GreetingResource.java:39)
        at org.acme.GreetingResource$quarkusrestinvoker$getPdf_543eb02c37e872c79aaa1d9bfe6f04e5f3d14068.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:627)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)


```

The only other dependency I have besides Quarkus is Apache FOP.

**Comment by dmlloyd** [comment]
I do believe that the best fix is for these classes to replace calls to `newInstance` (which performs a sort of service lookup) with `newDefaultInstance` (which just instantiates the implementation directly). Failing that, I think the best _workaround_ would be to manually register each implementation class for reflection. I'm not sure why these service providers are not being found at run time but I would expect this solution to work.

**Comment by zaro** [comment]
@dmlloyd Since the failure is actually in a dependency ( Apache FOP and Tika for the original poster) , do you mean that this needs to be fixed in the dependency library ?

**Comment by dmlloyd** [comment]
Yes (well, a qualified yes: in many cases, maintainers of libraries such as this one can't or won't use newer APIs for various reasons). All libraries should (nearly) always use the JDK implementations of these classes at this point, and that method has been in the JDK since JDK 9.

But I think it is also possible to work around the problem using a little extra GraalVM configuration. You should be able to do so by adding an extra class to your application like this:

```java
@RegisterForReflection(classNames = {"org.apache.xerces.jaxp.SAXParserFactoryImpl"})
public class JaxpReflectionHolder {}
```

Add any additional JAXP class names that are being used but not found by the native image runtime.

**Comment by zaro** [comment]
@dmlloyd  Thank you for the suggestion. I tried adding the reflections helper  like this:
```
@RegisterForReflection(classNames = {
        "com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl"
})
public class ReflectionConfig {
}
```

And also this configuration:
```
%prod.quarkus.jib.jvm-additional-arguments=--add-opens java.xml/com.sun.org.apache.xerces.internal.jaxp=ALL-UNNAMED -Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl -Djaxp.debug=true
```

This find the SAXParserFactoryImpl  class, but fails with the following error :

```
JAXP: created new instance of class com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl using ClassLoader: io.quarkus.bootstrap.runner.RunnerClassLoader@1
java.lang.ClassCastException: class com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl cannot be cast to class javax.xml.parsers.SAXParserFactory (com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl is in module java.xml of loader 'bootstrap'; javax.xml.parsers.SAXParserFactory is in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @37f8bb67)
        at javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source)
        at org.apache.xml.utils.XMLReaderManager.getXMLReader(XMLReaderManager.java:111)
        at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:437)
        at org.acme.routes.GreetingResource.getPdf(GreetingResource.java:69)
        at org.acme.routes.GreetingResource$quarkusrestinvoker$getPdf_543eb02c37e872c79aaa1d9bfe6f04e5f3d14068.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:627)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

```

I don't understand how, but it seems  to me that the Registered class is in the 'bootstrap' class loader, while the rest is in the runner class loader. 

Maybe that's what is causing the problem in the first place, the two class loaders.
Because really, the class is there, but it cannot be cast  and the `newInstance()` method is actually written in such way that it only shows the error for instantiating fallback and not for  instantiating the system configured class. The configuration I added actually , just repeats the default system configuration, but because the loading is force trough system property the error why it failed to load it is also printed.

**Comment by dmlloyd** [comment]
I think the most likely explanation is that there is a second `javax.xml.parsers.SAXParserFactory` API class coming from some class path dependency JAR. One big hint that this might be the case is that this line `at javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source)` indicates a class path JAR whose debug info has been stripped out. If it were the JDK, it would have `java.xml/` prepended (because it's in a core module) and it would have the file name and line number.

You should locate the artifact of the JAR which is providing this class and exclude it in your build system configuration. If you are using Maven, you could use `mvn dependency:tree` to gather this information.

**Comment by zaro** [comment]
@dmlloyd  Thank you for your support. When I started looking in more detail in the direction you suggested it turned out that Apache FOP is pulling `xml-apis:*` which are obsolete and are part of the runtime for quite some time. 

So in the end  all it was needed to exclude them from the project, and all the other workarounds are not needed at all .

Here is the relevant config if anybody else is having the similar problem.
```xml
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>fop</artifactId>
            <version>2.3</version>
            <exclusions>
                <exclusion>
                    <groupId>xml-apis</groupId>
                    <artifactId>xml-apis</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>xml-apis</groupId>
                    <artifactId>xml-apis-ext</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
