### ISSUE TITLE
ALB HTTP Events cause NullPointerException on QuarkusStreamHandler.java

### ISSUE THREAD

**Issue by faermanj** [quarkusio/quarkus#17638]
## Describe the bug
HTTP(S) Events from Application Load Balancers causes NPE, likely because only API Gateway fields are mapped.

### Expected behavior
Expected to work just like API Gateway, but taking requests from load balancers instead.
There are many cases to which direct HTTP is preferred to API Gateway, but shouldn't be hard to support both.

### Actual behavior
ERROR [qua.ama.lam.http] (main) Request Failure: java.lang.NullPointerException
at java.base/java.lang.StringBuilder.<init>(Unknown Source)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.nettyDispatch(LambdaHttpHandler.java:165)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:62)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:42)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.handle(AmazonLambdaRecorder.java:71)
at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.handleRequest(QuarkusStreamHandler.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
att.DelegatingMethodAccessorImpl.invoke(Unknown Source)
att.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:375)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:899)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:258)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:192)
at lambdainternal.AWSLambda.main(AWSLambda.java:187)

## To Reproduce

Associate an ALB with the lambda function and send an HTTP request.
1. Create an AWS Application Load Balancer
2. Point its target group to the generated lambda function
3. Send any HTTP request

**Comment by faermanj** [comment]
Just forked and learning about contrib, hope i can submit a PR on this soon...

**Comment by gsmet** [comment]
@faermanj https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md has some nice tips!

**Comment by patriot1burke** [comment]
What version of quarkus?

quarkus-amazon-lambda-http is AWS HTTP gateway   quarkus-amazon-lambda-rest is AWS REST gateway.  Looks like APplication Load Balancer uses REST payload 1.0?

https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html

So use quarkus-amazon-lambda-rest

**Comment by AdamBien** [comment]
For Application Load Balancer integration , you need the `quarkus-amazon-lambda-rest` extension. 

See a working deployment with VPC / ALB / Quarkus / MicroProfile and Java CDK:
https://adambien.blog/roller/abien/entry/deploying_a_microprofile_quarkus_application

**Comment by lszita** [comment]
Hi @AdamBien, Ive just tried that tutorial, and its working with some cases, but not all, because ALB event layout has "headers" property only and no "multiValueHeaders". When  it gets parsed to io.quarkus.amazon.lambda.http.model.AwsProxyRequest (according to documentation), headers are never set, and now for example you cannot parse a json body because there is no way to tell quarkus the Content-Type. 

To reproduce, try your example with a json body request. It works in dev mode with swagger UI, but not behind ALB.

Endpoint: http://localhost:8080/_lambda_

Bad request (415 unsopported media type):
`{
  "requestContext": {
    "elb": {
      "targetGroupArn": "x"
    }
  },
  "httpMethod": "POST",
  "path": "/hello",
  "headers": {
    "Content-type": "application/json"
  },
  "body": "{}",
  "isBase64Encoded": false
}`

OK request (notice the added multiValueHeaders)
`{
  "requestContext": {
    "elb": {
      "targetGroupArn": "x"
    }
  },
  "httpMethod": "POST",
  "path": "/hello",
  "headers": {
    "Content-type": "application/json"
  },
  "multiValueHeaders" : {"Content-type" : ["application/json"]},
  "body": "{}",
  "isBase64Encoded": false
}`
