### ISSUE TITLE
IT jpa-oracle not compiling with latest GraalVM

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#17672]
## Describe the bug
The integration test jpa-oracle is failing to compile with the latest GraalVM.

### Expected behavior
Test should build and pass.

### Actual behavior
Test fails to build with:
```
...
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]     (clinit):   1,803.67 ms,  3.35 GB
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]   (typeflow):  70,167.39 ms,  3.35 GB
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]    (objects):  60,688.97 ms,  3.35 GB
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]   (features):   1,984.52 ms,  3.35 GB
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]     analysis: 136,776.43 ms,  3.35 GB
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]     universe:   8,685.76 ms,  3.36 GB
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]      (parse):  26,657.85 ms,  4.05 GB
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]     (inline):  38,814.45 ms,  4.44 GB
07:07:30.744 Oracle Database:Tue Jun 01 07:07:29 2021
07:07:30.746 Oracle Database:Starting background process SMCO
07:07:30.746 Oracle Database:Tue Jun 01 07:07:30 2021
07:07:30.746 Oracle Database:SMCO started with pid=22, OS id=122
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]    (compile): 177,866.83 ms,  4.46 GB
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]      compile: 253,092.16 ms,  4.46 GB
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]        image:   9,730.15 ms,  4.47 GB
To see how the classes got initialized, use --trace-class-initialization=oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource,oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser
[quarkus-integration-test-jpa-oracle-999-SNAPSHOT-runner:27286]        write:   2,210.37 ms,  4.49 GB
Error: Classes that should be initialized at run time got initialized during image building:
 oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource got initialized use --trace-class-initialization=oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource
oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser got initialized use --trace-class-initialization=oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource got initialized use --trace-class-initialization=oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource
oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser got initialized use --trace-class-initialization=oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:542)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.afterImageWrite(ClassInitializationFeature.java:298)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$12(NativeImageGenerator.java:715)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:715)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:494)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```
see https://github.com/graalvm/mandrel/runs/2715558859?check_suite_focus=true#step:9:3511

## To Reproduce

```
wget https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/21.2.0-dev-20210601_2247/graalvm-ce-java11-linux-amd64-dev.tar.gz
tar xf graalvm-ce-java11-linux-amd64-dev.tar.gz
./graalvm-ce-java11-21.2.0-dev/bin/gu install native-image
export GRAALVM_HOME=$(pwd)/graalvm-ce-java11-21.2.0-dev
./mvnw /mvnw -Dtest-containers -Dstart-containers -Dnative -Dnative.surefire.skip -Dquarkus.container-image.build=false -f integration-tests -pl jpa-oracle install    
```

## Additional context

Reverting https://github.com/quarkusio/quarkus/pull/17472 makes the test build and pass.
On the other hand, 3ea43c1869b1e2f1069960f2e2d746b6e7412a8b which includes https://github.com/quarkusio/quarkus/pull/17472 [passed](https://github.com/graalvm/mandrel/runs/2707653564?check_suite_focus=true#step:9:3051) so it's probably a combination of https://github.com/quarkusio/quarkus/pull/17472 and a change in GraalVM.

cc @geoand

**Comment by geoand** [comment]
Did you figure this one out @zakkak ?

**Comment by zakkak** [comment]
> Did you figure this one out @zakkak ?

No, but I noticed that with https://github.com/quarkusio/quarkus/pull/17711 in place the issue doesn't manifest, so it looks like a combination of https://github.com/quarkusio/quarkus/pull/17472 and https://github.com/oracle/graal/commit/e92dab09590586baf2096569351cb987415eace6 is what's causing the issue.

**Comment by geoand** [comment]
I just tried the `jpa-oracle` with GraalVM 21.2 and everything worked fine. Can we close this or is there something more to check?

**Comment by zakkak** [comment]
@geoand did you try it without https://github.com/quarkusio/quarkus/pull/17711? 

That's when that issue appears and given that the performance issues that https://github.com/quarkusio/quarkus/pull/17711 works around will at some point get fixed I would like to keep the issue open.

**Comment by geoand** [comment]
Sure thing

**Comment by zakkak** [comment]
I [removed the `-H:-ParseOnce` option](https://github.com/zakkak/quarkus/tree/enable-parseonce) and did some tests with [GraalVM CE](https://github.com/zakkak/quarkus/runs/3371447400?check_suite_focus=true) and [Mandrel](https://github.com/graalvm/mandrel/actions/runs/1146954848) 21.2, as well as with [Mandrel 21.3-dev](https://github.com/graalvm/mandrel/actions/runs/1147027008). 

The issue seems to no longer manifest.
