### ISSUE TITLE
Internal Server Error when Content-Type header value is invalid

### ISSUE THREAD

**Issue by kekbur** [quarkusio/quarkus#17735]
## Describe the bug
Quarkus responds with the HTTP status code `500 - Internal Server Error` when `invalid` is passed as a value for the `Content-Type` header. In fact, any value that does not conform to MIME type syntax `type/subtype` yields the same response.

### Expected behavior
Quarkus should respond with one of the client error status codes, possibly `415 - Unsupported Media Type` or `400 - Bad Request`.

### Actual behavior
See above. The following exception stack trace is produced:

```
org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: RESTEASY003340: Failure parsing MediaType st
ring: invalid
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:258)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:481)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalArgumentException: RESTEASY003340: Failure parsing MediaType string: invalid
        at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.internalParse(MediaTypeHeaderDelegate.java:96)
        at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.parse(MediaTypeHeaderDelegate.java:69)
        at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:33)
        at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:19)
        at javax.ws.rs.core.MediaType.valueOf(MediaType.java:172)
        at org.jboss.resteasy.specimpl.ResteasyHttpHeaders.getMediaType(ResteasyHttpHeaders.java:151)
        at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:65)
        at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:47)
        at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:481)
        at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:332)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:253)
        ... 14 more
```

## To Reproduce

The following minimal project contains the resource class TestResource and test class ResourceTest which reproduce the issue: [invalid-content-type-internal-server-error.zip](https://github.com/quarkusio/quarkus/files/6610452/invalid-content-type-internal-server-error.zip)

### Configuration
See the attached file.

### Output of `uname -a` or `ver`
Microsoft Windows [Version 10.0.19041.985]

### Quarkus version or git rev
2.0.0.CR3. The issue is also present on at least 1.11.0.Final.

**Comment by gsmet** [comment]
@asoldano @ronsigal looks like something that should be handled at the RESTEasy level (if valid).

**Comment by ronsigal** [comment]
@gsmet, I'll take a look.

**Comment by ronsigal** [comment]
I've created https://issues.redhat.com/browse/RESTEASY-2965 "Improve handling of invalid media types" for this problem.

**Comment by rsearls** [comment]
The solution is for the ExceptionMapper below be added to quarkus-resteasy
or the user to provide it in their app.  

    package XXXXX;

    import javax.ws.rs.core.Response;
    import javax.ws.rs.ext.ExceptionMapper;
    import javax.ws.rs.ext.Provider;

    @Provider
    public class IllegalStateExceptionMapper implements ExceptionMapper<IllegalStateException>  {
        @Override
        public Response toResponse(IllegalStateException exception)
        {
            return Response.status(400).build();

        }
    }

Quarkus module quarkus-resteasy already provides the following custom ExceptionMappers.
  extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/AuthenticationRedirectExceptionMapper.java
  extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/CompositeExceptionMapper.java
  extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/NotFoundExceptionMapper.java
  extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/UnauthorizedExceptionMapper.java
  extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/AuthenticationCompletionExceptionMapper.java
  extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/ForbiddenExceptionMapper.java
  extensions/resteasy-classic/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/AuthenticationFailedExceptionMapper.java

**Comment by thomasdarimont** [comment]
I sent a PR with a fix for this to resteasy-classic: https://github.com/resteasy/resteasy/pull/3803

Shall I "forward-port" this to resteasy-reactive?
