### ISSUE TITLE
Build failure of native executable with Google Vision sdk inside jax-rs endpoint

### ISSUE THREAD

**Issue by poldinik** [quarkusio/quarkus#1779]
I'm trying **to build a native executable deployed in docker container**. This is the code inside my unique jax-rs endpoint method, it contains google vision apis sdk.

```
    @GET
    @Path("detect")
    @Produces(MediaType.TEXT_PLAIN)
    public String detectTest(@QueryParam("url") String path) throws IOException {


        List<AnnotateImageRequest> requests = new ArrayList<>();

        //ImageSource imgSource = ImageSource.newBuilder().setGcsImageUri(gcsPath).build();

        ImageSource imgSource = ImageSource.newBuilder().setImageUri(path).build();
        Image img = Image.newBuilder().setSource(imgSource).build();
        Feature feat = Feature.newBuilder().setType(Feature.Type.TEXT_DETECTION).build();
        AnnotateImageRequest request =
                AnnotateImageRequest.newBuilder().addFeatures(feat).setImage(img).build();
        requests.add(request);

        try (ImageAnnotatorClient client = ImageAnnotatorClient.create()) {
            BatchAnnotateImagesResponse response = client.batchAnnotateImages(requests);
            List<AnnotateImageResponse> responses = response.getResponsesList();

            for (AnnotateImageResponse res : responses) {
                if (res.hasError()) {
                    System.out.printf("Error: %s\n", res.getError().getMessage());
                    return "Error";
                }

                // For full list of available annotations, see http://g.co/cloud/vision/docs
                for (EntityAnnotation annotation : res.getTextAnnotationsList()) {
                    System.out.printf("Text: %s\n", annotation.getDescription());
                    System.out.printf("Position : %s\n", annotation.getBoundingPoly());
                }
            }

            return "Text: " + responses.get(0).getTextAnnotationsList().get(0).getDescription();
        }

    }
```

I run `./mvnw package -Pnative` and this is the error (if I comment the code above, it builds successfully; my code works in dev mode, too) 

```
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.google.protobuf.UnsafeUtil. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.google.protobuf.UnsafeUtil. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0. Detailed failure reason(s): The field java.lang.Long.value, where the value produced by the array index scale computation is stored, is not static.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0. Add a RecomputeFieldValue.FieldOffset manual substitution for io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.ADDRESS_FIELD_OFFSET. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.grpc.netty.shaded.io.netty.util.internal.CleanerJava6. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of io.grpc.netty.shaded.io.netty.util.internal.shaded.org.jctools.util.UnsafeRefArrayAccess. Detailed failure reason(s): Could not determine the field where the value produced by the call to sun.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[ocra-server-1.0-runner:9632]     analysis:  23,142.92 ms
Printing call tree to /Users/loretto/IdeaProjects/ocra-server/target/reports/call_tree_ocra-server-1.0-runner_20190331_014427.txt
Printing list of used classes to /Users/loretto/IdeaProjects/ocra-server/target/reports/used_classes_ocra-server-1.0-runner_20190331_014428.txt
Printing list of used packages to /Users/loretto/IdeaProjects/ocra-server/target/reports/used_packages_ocra-server-1.0-runner_20190331_014428.txt
Error: unsupported features in 2 methods
Detailed message:
Error: Class initialization failed: io.grpc.netty.shaded.io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator
Original exception that caused the problem: java.lang.NoClassDefFoundError: org/eclipse/jetty/npn/NextProtoNego$Provider
        at io.grpc.netty.shaded.io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator$1.<init>(JdkNpnApplicationProtocolNegotiator.java:29)
        at io.grpc.netty.shaded.io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator.<clinit>(JdkNpnApplicationProtocolNegotiator.java:27)
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at com.oracle.svm.hosted.ClassInitializationSupportImpl.ensureClassInitialized(ClassInitializationSupportImpl.java:199)
        at com.oracle.svm.hosted.ClassInitializationSupportImpl.computeInitKindAndMaybeInitializeClass(ClassInitializationSupportImpl.java:162)
        at com.oracle.svm.hosted.ClassInitializationSupportImpl.computeInitKindAndMaybeInitializeClass(ClassInitializationSupportImpl.java:138)
        at com.oracle.svm.hosted.ClassInitializationSupportImpl.maybeInitializeHosted(ClassInitializationSupportImpl.java:103)
        at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:179)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:263)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:204)
        at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:154)
        at org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:3992)
        at org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4235)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5023)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3184)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2993)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:891)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:785)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:213)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:332)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:169)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.npn.NextProtoNego$Provider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 36 more
Error: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace:  object io.grpc.netty.shaded.io.netty.buffer.PoolChunk
        object io.grpc.netty.shaded.io.netty.buffer.PoolChunkList
        object io.grpc.netty.shaded.io.netty.buffer.PoolArena$DirectArena
        object io.grpc.netty.shaded.io.netty.buffer.PoolArena[]
        object io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator
        method io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext.setKeyMaterial(long, X509Certificate[], PrivateKey, String)
Call path from entry point to io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext.setKeyMaterial(long, X509Certificate[], PrivateKey, String): 
        at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext.setKeyMaterial(ReferenceCountedOpenSslContext.java:733)
        at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslClientContext.newSessionContext(ReferenceCountedOpenSslClientContext.java:105)
        at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:192)
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:776)
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:452)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:385)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:435)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:223)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:164)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:156)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:157)
        at com.google.cloud.vision.v1.stub.GrpcImageAnnotatorStub.create(GrpcImageAnnotatorStub.java:84)
        at com.google.cloud.vision.v1.stub.ImageAnnotatorStubSettings.createStub(ImageAnnotatorStubSettings.java:120)
        at com.google.cloud.vision.v1.ImageAnnotatorClient.<init>(ImageAnnotatorClient.java:136)
        at com.google.cloud.vision.v1.ImageAnnotatorClient.create(ImageAnnotatorClient.java:117)
        at com.google.cloud.vision.v1.ImageAnnotatorClient.create(ImageAnnotatorClient.java:108)
        at studio.volare.endpoint.ImageResource.detectTest(ImageResource.java:79)
        at com.oracle.svm.reflect.ImageResource_detectTest_d50424aa856d0ff1b66bd3392c255cf9911418cf_34.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.api.client.util.FieldInfo.setValue(FieldInfo.java:233)
        at com.google.api.client.util.DataMap$EntrySet.clear(DataMap.java:101)
        at sun.nio.ch.Util$3.clear(Util.java:327)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:572)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext.setKeyMaterial(long, java.security.cert.X509Certificate[], java.security.PrivateKey, java.lang.String):v
        io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext.setKeyMaterial(long, java.security.cert.X509Certificate[], java.security.PrivateKey, java.lang.String):v
        io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslClientContext.newSessionContext(io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext, long, io.grpc.netty.shaded.io.netty.handler.ssl.OpenSslEngineMap, java.security.cert.X509Certificate[], javax.net.ssl.TrustManagerFactory, java.security.cert.X509Certificate[], java.security.PrivateKey, java.lang.String, javax.net.ssl.KeyManagerFactory):i
        io.grpc.netty.shaded.io.netty.handler.ssl.OpenSslClientContext.<init>(java.security.cert.X509Certificate[], javax.net.ssl.TrustManagerFactory, java.security.cert.X509Certificate[], java.security.PrivateKey, java.lang.String, javax.net.ssl.KeyManagerFactory, java.lang.Iterable, io.grpc.netty.shaded.io.netty.handler.ssl.CipherSuiteFilter, io.grpc.netty.shaded.io.netty.handler.ssl.ApplicationProtocolConfig, java.lang.String[], long, long, boolean):v
        io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.newClientContextInternal(io.grpc.netty.shaded.io.netty.handler.ssl.SslProvider, java.security.Provider, java.security.cert.X509Certificate[], javax.net.ssl.TrustManagerFactory, java.security.cert.X509Certificate[], java.security.PrivateKey, java.lang.String, javax.net.ssl.KeyManagerFactory, java.lang.Iterable, io.grpc.netty.shaded.io.netty.handler.ssl.CipherSuiteFilter, io.grpc.netty.shaded.io.netty.handler.ssl.ApplicationProtocolConfig, java.lang.String[], long, long, boolean):i
        io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.build():i
        io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory():i
        io.grpc.internal.AbstractManagedChannelImplBuilder.buildTransportFactory():i
        io.grpc.internal.AbstractManagedChannelImplBuilder.build():i
        io.grpc.ManagedChannelBuilder.build():i
        com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel():i
        com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel():c
        com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel():c
This is an implementation of com.google.api.gax.rpc.TransportChannelProvider printing path to constructors of com.google.api.gax.grpc.InstantiatingGrpcChannelProvider




Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image building with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  44.264 s
[INFO] Finished at: 2019-03-31T01:44:31+01:00
```

**Comment by gsmet** [comment]
I wonder if this extension could help you: https://github.com/hpehl/quarkus-grpc-extension .

@hpehl ?

**Comment by hpehl** [comment]
I'm not familiar with the  Google Vision APIs SDK, but I'm facing similar issues in my gRPC extensions:

I got native working for the [gRPC](https://github.com/hpehl/quarkus-grpc-extension) extension by adding Netty related gRPC [substitutions](https://github.com/hpehl/quarkus-grpc-extension/blob/master/runtime/src/main/java/io/quarkus/grpc/runtime/graal/GrpcNettySubstitutions.java).

However for the [gRPC client](https://github.com/hpehl/quarkus-grpc-client-extension) extension I get the same error when adding the `grpc-netty-shaded` dependency and `ByteBuffer` related errors when adding the `netty-tcnative-boringssl-static` dependency. 

According to @dmlloyd it's related to code built with Java 9 or newer: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Native.20code.20and.20java.2Enio.2EByteBuffer. So far I haven't found a solution for it.
