### ISSUE TITLE
quarkus:dev displays exception (warning) for @Disabled tests

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#17824]
## Describe the bug
The current version `2.0.0.CR3` of `quarkus:dev` displays warnings with exception stacktraces for tests classes that are annotated with `@Disabled`.

## To reproduce

- Have the following test:

```java
@Disabled
public class CoffeeIT {

    @Test
    void testHello() {
        // ...
    }

}
```

- run `quarkus:dev` with version `2.0.0.CR3`

- activate output [`o`] and re-run tests [`r`]

Results in:

```
2021-06-10 10:21:55,230 INFO  [io.qua.dep.dev.tes.TestSupport] (Aesh InputStream Reader) Test output enabled
2021-06-10 10:22:04,036 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Quarkus Test Watcher - 0) Changed source files detected, recompiling CoffeeIT.java
2021-06-10 10:22:06,112 WARNING [org.jun.pla.lau.cor.TestExecutionListenerRegistry] (Test runner thread) TestExecutionListener [io.quarkus.deployment.dev.testing.JunitTestRunner$3] threw exception for method: executionFinished(TestIdentifier [uniqueId = '[engine:junit-jupiter]', parentId = null, displayName = 'JUnit Jupiter', legacyReportingName = 'JUnit Jupiter', source = null, tags = [], type = CONTAINER], TestExecutionResult [status = SUCCESSFUL, throwable = null]): java.util.NoSuchElementException
	at java.base/java.util.concurrent.LinkedBlockingDeque.removeFirst(LinkedBlockingDeque.java:446)
	at java.base/java.util.concurrent.LinkedBlockingDeque.pop(LinkedBlockingDeque.java:769)
	at io.quarkus.deployment.dev.testing.JunitTestRunner$3.executionFinished(JunitTestRunner.java:282)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$executionFinished$10(TestExecutionListenerRegistry.java:109)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener$$Lambda$1098/0x0000000014cf1908.accept(Unknown Source)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.lambda$notifyEach$1(TestExecutionListenerRegistry.java:67)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$$Lambda$878/0x00000000149e3d30.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyEach(TestExecutionListenerRegistry.java:65)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$200(TestExecutionListenerRegistry.java:32)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.executionFinished(TestExecutionListenerRegistry.java:108)
	at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionFinished(ExecutionListenerAdapter.java:56)
	at org.junit.platform.launcher.core.DelegatingEngineExecutionListener.executionFinished(DelegatingEngineExecutionListener.java:46)
	at org.junit.platform.launcher.core.OutcomeDelayingEngineExecutionListener.reportEngineOutcome(OutcomeDelayingEngineExecutionListener.java:69)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:109)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator$$Lambda$872/0x00000000149df878.accept(Unknown Source)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at io.quarkus.deployment.dev.testing.JunitTestRunner.runTests(JunitTestRunner.java:214)
	at io.quarkus.deployment.dev.testing.TestRunner.runInternal(TestRunner.java:248)
	at io.quarkus.deployment.dev.testing.TestRunner$1.run(TestRunner.java:127)
	at java.base/java.lang.Thread.run(Thread.java:853)
```

This is only a warning and has no effect, however we might want to fix it :)

**Comment by geoand** [comment]
I was not able to reproduce the original issue consistently, but #17853 should fix it nonetheless
