### ISSUE TITLE
Startup error "SRMSG00019: Unable to connect an emitter with the channel"

### ISSUE THREAD

**Issue by jendib** [quarkusio/quarkus#17841]
## Describe the bug
I'm having the same issue as #15058 which is the "SRMSG00019: Unable to connect an emitter with the channel" error on startup randomly.

### Expected behavior
No error and no stacktrace.

### Actual behavior
On Quarkus startup:
```
2021-06-10 16:22:41,101 INFO  [org.qua.cor.JobRunShell] (QuarkusQuartzScheduler_Worker-1) Job io.quarkus.scheduler.Scheduler.stats-job threw a JobExecutionException: : org.quartz.JobExecutionException: java.lang.RuntimeException: Error injecting org.eclipse.microprofile.reactive.messaging.Emitter<com.example.dto.StatsMessage> com.example.service.StatsService.emitter [See nested exception: java.lang.RuntimeException: Error injecting org.eclipse.microprofile.reactive.messaging.Emitter<com.example.dto.StatsMessage> com.example.service.StatsService.emitter]
	at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:384)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.RuntimeException: Error injecting org.eclipse.microprofile.reactive.messaging.Emitter<com.example.dto.StatsMessage> com.example.service.StatsService.emitter
	at com.example.service.StatsService_Bean.create(StatsService_Bean.zig:310)
	at com.example.service.StatsService_Bean.create(StatsService_Bean.zig:376)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
	at com.example.service.StatsService_ClientProxy.arc$delegate(StatsService_ClientProxy.zig:67)
	at com.example.service.StatsService_ClientProxy.computeStats(StatsService_ClientProxy.zig:124)
	at com.example.service.StatsService_ScheduledInvoker_computeStats_f8dccc2d37c7825d22dfa702247d39d08afc55f5.invokeBean(StatsService_ScheduledInvoker_computeStats_f8dccc2d37c7825d22dfa702247d39d08afc55f5.zig:46)
	at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
	at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:382)
	... 2 more
Caused by: javax.enterprise.inject.spi.DefinitionException: SRMSG00019: Unable to connect an emitter with the channel `stats-out`
	at io.smallrye.reactive.messaging.extension.ChannelProducer.getEmitter(ChannelProducer.java:192)
	at io.smallrye.reactive.messaging.extension.ChannelProducer.produceEmitter(ChannelProducer.java:137)
	at io.smallrye.reactive.messaging.extension.ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.create(ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.zig:247)
	at io.smallrye.reactive.messaging.extension.ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.get(ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.zig:277)
	at io.smallrye.reactive.messaging.extension.ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.get(ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.zig:312)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
	at com.example.service.StatsService_Bean.create(StatsService_Bean.zig:293)
	... 16 more
```

## To Reproduce

Reproduction project: 
[reproduce-17841.zip](https://github.com/quarkusio/quarkus/files/6632505/reproduce-17841.zip)

My emitter is described like this:
```java
@ApplicationScoped
public class StatsService {
    @Inject
    @Channel("stats-out")
    Emitter<StatsMessage> emitter;

    @Transactional
    @Scheduled(cron = "0/5 * * ? * *", identity = "stats-job")
    public void computeStats() {
        StatsMessage message = new StatsMessage();
        message.date = LocalDateTime.now();
        emitter.send(message);
    }
}
```

### Configuration
```properties
mp.messaging.outgoing.stats-out.connector=smallrye-kafka
mp.messaging.outgoing.stats-out.topic=stats
mp.messaging.outgoing.stats-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
```

**Comment by gsmet** [comment]
I think a reproducer would be useful.

**Comment by jendib** [comment]
I attached a reproduction project. Just need to `mvnw compile quarkus:dev`

**Comment by cescoffier** [comment]
The reproducer fails with:
```
 java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.acme.getting.started.AlertEntity and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
 ```
 
That does not seem to be related to the mentioned issue.

In the description of the issue, who's consuming `stats-out`? If there is no consumer, the exception is expected. No one is there to consume the data.

**Comment by cescoffier** [comment]
I've updated the reproducer (just made sure that the json is not empty) and everything works fine.

**Comment by jendib** [comment]
@cescoffier I don't have the `InvalidDefinitionException` you experience.
I just redownloaded my reproducer and executed `mvnw compile quarkus:dev` immediately with no modification and I got this:

```
mvnw compile quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< org.acme:getting-startedissue >--------------------
[INFO] Building getting-startedissue 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.13.7.Final:generate-code (default) @ getting-startedissue ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ getting-startedissue ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ getting-startedissue ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Users\Benjamin\Downloads\reproduce-17841\target\classes
[INFO]
[INFO] --- quarkus-maven-plugin:1.13.7.Final:dev (default-cli) @ getting-startedissue ---
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-06-13 21:22:47,771 INFO  [org.qua.cor.JobRunShell] (QuarkusQuartzScheduler_Worker-1) Job io.quarkus.scheduler.Scheduler.task-job threw a JobExecutionException: : org.quartz.JobExecutionException: java.lang.RuntimeException: Error injecting org.eclipse.microprofile.reactive.messaging.Emitter<io.smallrye.reactive.messaging.kafka.Record<java.lang.String
, org.acme.getting.started.AlertEntity>> org.acme.getting.started.IssueService.signalementsEmitter [See nested exception: java.lang.RuntimeException: Error injecting org.eclipse.microprofile.reactive.messaging.Emitter<io.smallrye.reactive.messaging.kafka.Record<java.lang.String, org.acme.getting.started.AlertEntity>> org.acme.getting.started.IssueService.
signalementsEmitter]
        at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:384)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.RuntimeException: Error injecting org.eclipse.microprofile.reactive.messaging.Emitter<io.smallrye.reactive.messaging.kafka.Record<java.lang.String, org.acme.getting.started.AlertEntity>> org.acme.getting.started.IssueService.signalementsEmitter
        at org.acme.getting.started.IssueService_Bean.create(IssueService_Bean.zig:335)
        at org.acme.getting.started.IssueService_Bean.create(IssueService_Bean.zig:358)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
        at org.acme.getting.started.IssueService_ClientProxy.arc$delegate(IssueService_ClientProxy.zig:67)
        at org.acme.getting.started.IssueService_ClientProxy.schedule(IssueService_ClientProxy.zig:155)
        at org.acme.getting.started.IssueService_ScheduledInvoker_schedule_dce0524c3f1de653f83719900424446459b7c471.invokeBean(IssueService_ScheduledInvoker_schedule_dce0524c3f1de653f83719900424446459b7c471.zig:46)
        at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
        at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:382)
        ... 2 more
Caused by: javax.enterprise.inject.spi.DefinitionException: SRMSG00019: Unable to connect an emitter with the channel `signalements-ws`
        at io.smallrye.reactive.messaging.extension.ChannelProducer.getEmitter(ChannelProducer.java:192)
        at io.smallrye.reactive.messaging.extension.ChannelProducer.produceEmitter(ChannelProducer.java:137)
        at io.smallrye.reactive.messaging.extension.ChannelProducer_Subclass.produceEmitter$$superaccessor1(ChannelProducer_Subclass.zig:563)
        at io.smallrye.reactive.messaging.extension.ChannelProducer_Subclass$$function$$1.apply(ChannelProducer_Subclass$$function$$1.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.smallrye.reactive.messaging.extension.ChannelProducer_Subclass.produceEmitter(ChannelProducer_Subclass.zig:520)
        at io.smallrye.reactive.messaging.extension.ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.create(ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.zig:247)
        at io.smallrye.reactive.messaging.extension.ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.get(ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.zig:277)
        at io.smallrye.reactive.messaging.extension.ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.get(ChannelProducer_ProducerMethod_produceEmitter_86c8bb1e4975aaf33dff96bec0d2fc8fa44920ab_Bean.zig:312)
        at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
        at org.acme.getting.started.IssueService_Bean.create(IssueService_Bean.zig:318)
        ... 16 more

2021-06-13 21:22:47,784 INFO  [io.sma.rea.mes.kafka] (Quarkus Main Thread) SRMSG18214: Key deserializer omitted, using String as default
2021-06-13 21:22:47,784 INFO  [io.sma.rea.mes.kafka] (Quarkus Main Thread) SRMSG18237: Setting client.id for Kafka producer to kafka-producer-signalements
2021-06-13 21:22:47,794 INFO  [org.apa.kaf.cli.pro.ProducerConfig] (Quarkus Main Thread) ProducerConfig values:
        acks = 1
        batch.size = 16384
        bootstrap.servers = [localhost:9092]
        buffer.memory = 33554432
        client.dns.lookup = use_all_dns_ips
        client.id = kafka-producer-signalements
        compression.type = none
        connections.max.idle.ms = 540000
        delivery.timeout.ms = 120000
        enable.idempotence = false
        interceptor.classes = []
        internal.auto.downgrade.txn.commit = false
        key.serializer = class org.apache.kafka.common.serialization.StringSerializer
        linger.ms = 0
        max.block.ms = 60000
        max.in.flight.requests.per.connection = 5
        max.request.size = 1048576
        metadata.max.age.ms = 300000
        metadata.max.idle.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.max.ms = 10000
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 2147483647
        retry.backoff.ms = 100
        sasl.client.callback.handler.class = null
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.login.callback.handler.class = null
        sasl.login.class = null
        sasl.login.refresh.buffer.seconds = 300
        sasl.login.refresh.min.period.seconds = 60
        sasl.login.refresh.window.factor = 0.8
        sasl.login.refresh.window.jitter = 0.05
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        security.providers = null
        send.buffer.bytes = 131072
        socket.connection.setup.timeout.max.ms = 127000
        socket.connection.setup.timeout.ms = 10000
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
        ssl.endpoint.identification.algorithm = https
        ssl.engine.factory.class = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.certificate.chain = null
        ssl.keystore.key = null
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLSv1.3
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.certificates = null
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        transaction.timeout.ms = 60000
        transactional.id = null
        value.serializer = class io.quarkus.kafka.client.serialization.ObjectMapperSerializer

2021-06-13 21:22:47,912 INFO  [org.apa.kaf.com.uti.AppInfoParser] (Quarkus Main Thread) Kafka version: 2.7.0
2021-06-13 21:22:47,912 INFO  [org.apa.kaf.com.uti.AppInfoParser] (Quarkus Main Thread) Kafka commitId: 448719dc99a19793
2021-06-13 21:22:47,912 INFO  [org.apa.kaf.com.uti.AppInfoParser] (Quarkus Main Thread) Kafka startTimeMs: 1623612167911
2021-06-13 21:22:47,922 INFO  [io.sma.rea.mes.kafka] (Quarkus Main Thread) SRMSG18214: Key deserializer omitted, using String as default
2021-06-13 21:22:47,922 INFO  [io.sma.rea.mes.kafka] (Quarkus Main Thread) SRMSG18237: Setting client.id for Kafka producer to kafka-producer-signalements-ws
2021-06-13 21:22:47,923 INFO  [org.apa.kaf.cli.pro.ProducerConfig] (Quarkus Main Thread) ProducerConfig values:
        acks = 1
        batch.size = 16384
        bootstrap.servers = [localhost:9092]
        buffer.memory = 33554432
        client.dns.lookup = use_all_dns_ips
        client.id = kafka-producer-signalements-ws
        compression.type = none
        connections.max.idle.ms = 540000
        delivery.timeout.ms = 120000
        enable.idempotence = false
        interceptor.classes = []
        internal.auto.downgrade.txn.commit = false
        key.serializer = class org.apache.kafka.common.serialization.StringSerializer
        linger.ms = 0
        max.block.ms = 60000
        max.in.flight.requests.per.connection = 5
        max.request.size = 1048576
        metadata.max.age.ms = 300000
        metadata.max.idle.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.max.ms = 10000
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 2147483647
        retry.backoff.ms = 100
        sasl.client.callback.handler.class = null
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.login.callback.handler.class = null
        sasl.login.class = null
        sasl.login.refresh.buffer.seconds = 300
        sasl.login.refresh.min.period.seconds = 60
        sasl.login.refresh.window.factor = 0.8
        sasl.login.refresh.window.jitter = 0.05
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        security.providers = null
        send.buffer.bytes = 131072
        socket.connection.setup.timeout.max.ms = 127000
        socket.connection.setup.timeout.ms = 10000
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
        ssl.endpoint.identification.algorithm = https
        ssl.engine.factory.class = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.certificate.chain = null
        ssl.keystore.key = null
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLSv1.3
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.certificates = null
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        transaction.timeout.ms = 60000
        transactional.id = null
        value.serializer = class io.quarkus.kafka.client.serialization.ObjectMapperSerializer

2021-06-13 21:22:47,928 INFO  [org.apa.kaf.com.uti.AppInfoParser] (Quarkus Main Thread) Kafka version: 2.7.0
2021-06-13 21:22:47,928 INFO  [org.apa.kaf.com.uti.AppInfoParser] (Quarkus Main Thread) Kafka commitId: 448719dc99a19793
2021-06-13 21:22:47,928 INFO  [org.apa.kaf.com.uti.AppInfoParser] (Quarkus Main Thread) Kafka startTimeMs: 1623612167927
2021-06-13 21:22:48,080 INFO  [io.quarkus] (Quarkus Main Thread) getting-startedissue 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.13.7.Final) started in 2.228s. Listening on: http://localhost:8080
2021-06-13 21:22:48,081 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-06-13 21:22:48,081 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, mutiny, quartz, resteasy, scheduler, smallrye-context-propagation, smallrye-reactive-messaging, smallrye-reactive-messaging-kafka, vertx]

```

**Comment by cescoffier** [comment]
Weird, I will retry tomorrow. Make sure you clean your target directory. 

Which java version are you using?

**Comment by cescoffier** [comment]
Can you also answer my question? Who's consuming the channel? If no one consume it, the failure is expected.

**Comment by cescoffier** [comment]
Ok, I finally understand the issue. The job starts before the connector. 

@mkouba any idea to make sure reactive messaging is started before the job?

**Comment by jendib** [comment]
I deleted the `target` directory and had the same issue.

I'm using this JDK : `Java version: 11.0.5, vendor: AdoptOpenJDK`

> Ok, I finally understand the issue. The job starts before the connector.

That was also my guess!

**Comment by mkouba** [comment]
> @mkouba any idea to make sure reactive messaging is started before the job?

So the scheduler is started in `@Observes @Priority(Interceptor.Priority.PLATFORM_BEFORE) StartupEvent` observer method, i.e. with priority `0`. Whereas the reactive messaging is started in `@Observes @Priority(Interceptor.Priority.LIBRARY_BEFORE) StartupEvent`, i.e. priority `1000`. And according to the spec _"Observers with smaller priority values are called first"_.

I think that reactive messaging could be started before the `StartupEvent` is fired. Alternatively, we can just change the priority to something like ` @Priority(Interceptor.Priority.PLATFORM_BEFORE - 1)`...

**Comment by cescoffier** [comment]
Actually, I believe we changed that to allows observers to run code before reactive messaging. 
Can the user decide the priority for each method?

**Comment by mkouba** [comment]
> Can the user decide the priority for each method?

Do you mean a `@Scheduled` method? No, that's not possible. But a user can specify the `delay`: https://quarkus.io/guides/scheduler-reference#delayed-execution

**Comment by cescoffier** [comment]
@jendib not great, but did you try to add a delay?

**Comment by jendib** [comment]
@cescoffier adding a few seconds of delay seems to work indeed.

**Comment by cescoffier** [comment]
@mkouba anything else we could do? If not let's close it.

**Comment by mkouba** [comment]
> anything else we could do? If not let's close it.

Nothing comes to my mind. In theory, we could add something like `Class<? extends BooleanSupplier> executeOnlyIf()` to the `@Scheduled`... I'll think about that and will create a separate issue if needed.

**Comment by mkouba** [comment]
FTR I've created https://github.com/quarkusio/quarkus/pull/18060 which makes it possible to declare a "skip predicate" but it's just a declarative way of adding an `if()` around the scheduled business method logic. @cescoffier Is there a way to find out whether the reactive messaging is started and ready? E.g. inject some bean and invoke some `isReady()` method?
