### ISSUE TITLE
NullPointerException in build when denying unannotated endpoints

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#17854]
In a project without endpoints, a NullPointerException is thrown during build if the property `quarkus.security.jaxrs.deny-unannotated-endpoints` is set to `true`. 

Of course, without endpoints the property makes no sense, but probably no NullPointerException should be thrown either.

``` 
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
  	[error]: Build step io.quarkus.resteasy.deployment.ResteasyBuiltinsProcessor#setUpDenyAllJaxRs threw an exception: java.lang.NullPointerException
  	at io.quarkus.resteasy.deployment.ResteasyBuiltinsProcessor.setUpDenyAllJaxRs(ResteasyBuiltinsProcessor.java:57)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
  	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
  	at java.base/java.lang.Thread.run(Thread.java:829)
  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by geoand** [comment]
Thanks for reporting!

A framework should indeed never throw a NPE!
