### ISSUE TITLE
NPE from BeanManagerImpl when injecting beans in unit test

### ISSUE THREAD

**Issue by sarxos** [quarkusio/quarkus#1786]
Hello @mkouba,

This is in regards to the issue we discussed today on Zulip.

I have a 3rd party class which cannot be annotated with bean definintg annotation and I create factory for it.

```java
public class SomeRef { }
```

A factory such as:

```java
import javax.enterprise.context.Dependent;
import javax.enterprise.inject.Produces;
import javax.enterprise.inject.spi.InjectionPoint;
import javax.inject.Singleton;

@Singleton
public class SomeRefFactory {

	@Produces
	@Dependent
	public SomeRef create(final InjectionPoint injection) {
		return new SomeRef();
	}
}
```

Everything works fine when I have it in `@Path` annotated resource, but when I inject it in unit test which does not have a bean defining annotation, I'm getting NPE from `BeanManagerImpl`.

```java
import static org.assertj.core.api.Assertions.assertThat;

import javax.inject.Inject;
import org.junit.jupiter.api.Test;
import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
public class SomeTest {

	@Inject
	SomeRef ref;

	@Test
	void test_injectActorRefByClass() {
		assertThat(ref).isNotNull();
	}
}
```

A stack trace:

```plain
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [SomeTest]: Failed to inject field SomeRef SomeTest.ref
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeTestInstanceFactory(ClassTestDescriptor.java:314)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:289)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:281)
	...
Caused by: java.lang.RuntimeException: Failed to inject field SomeRef SomeTest.ref
	at io.quarkus.arc.deployment.ArcTestResourceProvider.inject(ArcTestResourceProvider.java:46)
	at io.quarkus.test.common.TestInjectionManager.inject(TestInjectionManager.java:21)
	at io.quarkus.test.junit.QuarkusTestExtension.createTestInstance(QuarkusTestExtension.java:238)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeTestInstanceFactory(ClassTestDescriptor.java:299)
	... 49 more
Caused by: java.lang.NullPointerException: Managed Bean [class SomeRef] is null
	at io.quarkus.arc.BeanManagerImpl.getReference(BeanManagerImpl.java:64)
	at io.quarkus.arc.deployment.ArcTestResourceProvider.inject(ArcTestResourceProvider.java:38)
	... 52 more
```

To W/A is to annotate test with a bean defining annotation, e.g. a test like this will pass:

```java
import static org.assertj.core.api.Assertions.assertThat;

import javax.inject.Inject;
import javax.inject.Singleton;
import org.junit.jupiter.api.Test;
import io.quarkus.test.junit.QuarkusTest;

@Singleton
@QuarkusTest
public class SomeTest {

	@Inject
	SomeRef ref;

	@Test
	void test_injectActorRefByClass() {
		assertThat(ref).isNotNull();
	}
}
```

**Comment by mkouba** [comment]
This issue is related to https://github.com/quarkusio/quarkus/issues/1749

`SomeRef` is probably not used in the app code.

**Comment by sarxos** [comment]
@mkouba Yes, this is correct. It is used in unit test only.

Just a side note. In practice I will have many such beans and related factories because project I'm working on will be used as a dependency. My goal is to have CDI compliant Akka integration layer which can be then used in any Quarkus-based applications. This integration layer, however, will not define any resources or REST/WS endpoints on its own.

**Comment by sarxos** [comment]
@mkouba I'm closing this one. After changes you and @geoand did in the master this is not a problem any more and described example testpass all the time. Thank you!
