### ISSUE TITLE
Unable to inject @RestClient into a thread class

### ISSUE THREAD

**Issue by jeanabraham** [quarkusio/quarkus#17872]
## Describe the bug
Unable to inject @RestClient into a class implementing `Runnable`. 

### Expected behavior
Successfully inject @RestClient object without an exception on startup.

### Actual behavior
```
Caused by: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.acme.HelloWorldClient and qualifiers [@Default]
	- java member: com.acme.MyThreadListener#<init>()
	- declared on CLASS bean [types=[java.lang.Runnable, com.acme.MyThreadListener, java.lang.Object], qualifiers=[@Default, @Any], target=com.acme.MyThreadListener]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=com.acme.HelloWorldClient, qualifiers=[@org.eclipse.microprofile.rest.client.inject.RestClient, @Any]]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1081)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:255)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:419)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at io.quarkus.builder.BuildContext$$Lambda$203/0x0000000000000000.run(Unknown Source)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:836)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.acme.HelloWorldClient and qualifiers [@Default]
	- java member: com.acme.MyThreadListener#<init>()
	- declared on CLASS bean [types=[java.lang.Runnable, com.acme.MyThreadListener, java.lang.Object], qualifiers=[@Default, @Any], target=com.acme.MyThreadListener]
	The following beans match by type, but none have matching qualifiers:
		- Bean [class=com.acme.HelloWorldClient, qualifiers=[@org.eclipse.microprofile.rest.client.inject.RestClient, @Any]]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:484)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:385)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:247)
	... 13 more
```

## To Reproduce

Reproducer project: https://github.com/jeanabraham/sample-restclient-inject

1. mvn quarkus:dev
2. Exception occurs

### Configuration
```properties
quarkus.log.level=INFO
com.acme.HelloWorldClient/mp-rest/url=${HELLO_WORLD_CLIENT_URL}
```

### Output of `uname -a` or `ver`
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.11+9 (build openj9-0.26.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210421_957 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 7796c80419 based on jdk-11.0.11+9)

**Comment by geoand** [comment]
This is a problem with your code.

Change https://github.com/jeanabraham/sample-restclient-inject/blob/master/src/main/java/com/acme/MyThreadListener.java#L22 to:

```java
    public MyThreadListener(@RestClient HelloWorldClient client )  {
        this.client = client;
    }   
```

and things work as expected

**Comment by glefloch** [comment]
Also, I think you bean needs to be injected and not created with a `new` in

https://github.com/jeanabraham/sample-restclient-inject/blob/a328952487c99017b508f2f16863525c088dbaa8/src/main/java/com/acme/StartupService.java#L25

**Comment by jeanabraham** [comment]
Thanks, @geoand & @glefloch.
