### ISSUE TITLE
Config property not found from an async CompletableFuture execution when StartupEvent is fired

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#17905]
@radcortez This is what we talked about today.

## Describe the bug
When the following code is executed, Quarkus will throw a `NoSuchElementException` during startup when the config value is accessed even if it is available in `application.properties`.

```
void startup(@Observes StartupEvent event) {
    CompletableFuture.runAsync(() -> {
        ConfigProvider.getConfig().getValue("my.property", String.class);
    }).join();
}
```
Here's the console output:
```
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-06-15 00:11:41,870 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.util.NoSuchElementException: SRCFG00014: The config property my.property is required but it could not be found in any config source
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:260)
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:205)
        at org.acme.MyApp.lambda$startup$0(MyApp.java:15)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## To Reproduce

https://github.com/gwenneg/quarkus-config-not-found

1. `./mvnw clean install`
2. `cd target/quarkus-app`
3. `java -jar quarkus-run.jar`

### Configuration
```properties
my.property=hello
```

### Output of `java -version`
$ java -version
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
```

### Quarkus version or git rev
`1.13.7.Final`

**Comment by radcortez** [comment]
Great. Thank you. I'll have a look.

**Comment by radcortez** [comment]
Each Config instance is registered with its own classloader and ConfigProvider retrieves the correct instance based on the context classloader. In this case, you have one context classloader for the main code and a different one for the async code. This means you have two different Config instances, which may yield different results. 

My recommendation is to just extract one single Config instance and pass it to the async code. This will make sure that the same instance is used for all the calls.

**Comment by gwenneg** [comment]
Thanks for having a look at this!

I fixed my issue by removing `CompletableFuture` from my code, but this problem could happen for other Quarkus users. I think your recommendation is worth a config documentation update.
