### ISSUE TITLE
Graphql, type BitSet not found in schema

### ISSUE THREAD

**Issue by Neisuz** [quarkusio/quarkus#17908]
## Describe the bug
There is a project (with graphql) with simple DTO where i'm using BitSet type, something like this - > private BitSet timeline;

version 1.12.0.Final 
Everything works fine, but when i run a project -> : 
WARN  [io.sma.gra.sch.cre.ReferenceCreator] (build-24) Class [java.util.BitSet] in not indexed in Jandex. Can not scan Object Type, defaulting to String Scalar;

version 1.13.7
The same project, but when i run a project, i get ->
```
ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:489)
	... 15 more
Caused by: graphql.AssertException: type BitSet not found in schema
	at graphql.Assert.assertNotNull(Assert.java:17)
	at graphql.schema.GraphQLTypeResolvingVisitor.handleTypeReference(GraphQLTypeResolvingVisitor.java:49)
	at graphql.schema.GraphQLTypeResolvingVisitor.visitGraphQLTypeReference(GraphQLTypeResolvingVisitor.java:44)
	at graphql.schema.GraphQLTypeReference.accept(GraphQLTypeReference.java:55)
	at graphql.schema.SchemaTraverser$TraverserDelegateVisitor.enter(SchemaTraverser.java:72)
	at graphql.util.Traverser.traverse(Traverser.java:144)
	at graphql.schema.SchemaTraverser.doTraverse(SchemaTraverser.java:59)
	at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:51)
	at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:38)
	at graphql.schema.SchemaUtil.replaceTypeReferences(SchemaUtil.java:116)
	at graphql.schema.GraphQLSchema$Builder.buildImpl(GraphQLSchema.java:644)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:622)
	at io.smallrye.graphql.bootstrap.Bootstrap.generateGraphQLSchema(Bootstrap.java:139)
	at io.smallrye.graphql.bootstrap.Bootstrap.bootstrap(Bootstrap.java:98)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:41)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass.initialize$$superaccessor1(GraphQLProducer_Subclass.zig:277)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass$$function$$1.apply(GraphQLProducer_Subclass$$function$$1.zig:29)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass.initialize(GraphQLProducer_Subclass.zig:235)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:37)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass.initialize$$superaccessor3(GraphQLProducer_Subclass.zig:511)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass$$function$$3.apply(GraphQLProducer_Subclass$$function$$3.zig:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass.initialize(GraphQLProducer_Subclass.zig:466)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer_ClientProxy.initialize(GraphQLProducer_ClientProxy.zig:131)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLRecorder.createExecutionService(SmallRyeGraphQLRecorder.java:29)
	at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService-167583418.deploy_52(SmallRyeGraphQLProcessor$buildExecutionService-167583418.zig:60287)
	at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService-167583418.deploy(SmallRyeGraphQLProcessor$buildExecutionService-167583418.zig:300)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:458)
	... 15 more
```
### Configuration
maven
quarkus versions 1.12.0.Final and 1.13.7
./mvnw clean compile quarkus:dev

**Comment by phillip-kruger** [comment]
BitSet is not a known type, so we can add support for it in SmallRye GraphQL, but this also relates to https://github.com/smallrye/smallrye-graphql/issues/844 where we need a generic way for users to map to and from string.

Can you create a small recreator ? And have you tried annotating the BitSet field with JsonBAdaptor:

`@JsonbTypeAdapter(MyBitSetAdaptor.class)`

And then create a MyBitSetAdaptor.

Not sure if this will work, but you can give it a go. You can also try the `@ToScalar` annotation if there is a way to create a BitSet from a String.

If you share a reproducer I can help with that.

**Comment by phillip-kruger** [comment]
Ok I have tested `@ToScalar(Scalar.String.class)` annotation on the BitSet field, and that takes away the exception on startup, however, I still need to test is during runtime. I am investigating, but in case you have a change, please also look at that

**Comment by phillip-kruger** [comment]
Add above solves for `TYPE` (output):

```
{
  person(id:1){
    names
    timeline
  }
}
```

return

```
{
  "data": {
    "person": {
      "names": [
        "Christine",
        "Fabian"
      ],
      "timeline": "{12, 40, 53, 78}"
    }
  }
}
```

So to use it as an input type too, might be an issue, I am still looking to see if/how that can work

**Comment by phillip-kruger** [comment]
Ok, Adding a `JSonBTypeAdaptor` solves the case for `INPUT`. So a full solution would be to use a combination of `ToScalar` and `JsonBTypeAdaptor`. It's not great, and as mentioned above, we will enhance SmallRye to work with JsonBTypeAdaptor for both input and output.

So the full example:

Example on `Person`
```
    @ToScalar(Scalar.String.class)
    @JsonbTypeAdapter(MyBitSetAdaptor.class)
    private BitSet timeline;
``` 

Then create an Adaptor (just an example, you can serialize/deserialize as you want):

```
public class MyBitSetAdaptor implements JsonbAdapter<BitSet, String> {

    @Override
    public String adaptToJson(BitSet bitSet) throws Exception {
        return bitSet.toString();
    }

    @Override
    public BitSet adaptFromJson(String s) throws Exception {
        String[] items = s.split(",");
        BitSet bs = new BitSet();
        for(String i:items){
            i = i.replace("{", "");
            i = i.replace("}", "");
            i = i.trim();
            int b = Integer.valueOf(i);
            bs.set(b);
        }
        return bs;
    }
}
```

Then do a mutation for example to test input and output:

```
mutation CreatePerson{
  updatePerson(person : 
    {
      names: "Phillip"
      timeline: "{12, 40, 53, 78}"
    }
  ){
    id
    names
    timeline
  }
}
```

Response

```
{
  "data": {
    "updatePerson": {
      "id": 11,
      "names": [
        "Phillip"
      ],
      "timeline": "{12, 40, 53, 78}"
    }
  }
}
```

I am closing here, as this workaround should work, and we already have a issue in SmallRye to add full support for `JSonBTypeAdaptor`. Please re-open if this is not sufficient.

**Comment by phillip-kruger** [comment]
@Ignore from GraphQL should do the trick
