### ISSUE TITLE
Quarkus dev mode triggers ignoration of different maven local repository location

### ISSUE THREAD

**Issue by mettwm** [quarkusio/quarkus#17947]
I have discovered that when I added an external library (previously built and installed in local maven repo) as a dependency to a Quarkus application it was not able to locate it if starting with the qarkus:dev goal. This happened only when running with `different` location of maven repo. e.g.:

`~/apache-maven-3.8.1/bin/mvn compile quarkus:dev -s ~/.m2sb/settings.xml` 

The external library was previously built and installed in .m2sb location, so it should have been able to see it. I got following error:

```
[INFO] --- quarkus-maven-plugin:1.13.7.Final:dev (default-cli) @ getting-started ---
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.acme:getting-started::jar:1.0.0-SNAPSHOT
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:150)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.acme:getting-started::jar:1.0.0-SNAPSHOT
        at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:320)
        at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:163)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:143)
        ... 1 more
Caused by: io.quarkus.bootstrap.resolver.maven.BootstrapMavenException: Failed to resolve dependencies for org.acme:getting-started:jar:1.0.0-SNAPSHOT
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolveManagedDependencies(MavenArtifactResolver.java:273)
        at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.doResolveModel(BootstrapAppModelResolver.java:186)
        at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveManagedModel(BootstrapAppModelResolver.java:152)
        at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:306)
        ... 3 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact com.examples:test-library:jar:0.0.1-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:357)
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolveManagedDependencies(MavenArtifactResolver.java:269)
        ... 6 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.examples:test-library:jar:0.0.1-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:340)
        ... 7 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.examples:test-library:jar:0.0.1-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:414)
        ... 9 more
```
So, on a suggestion I built and installed the external library in the default .m2 location and then I was able to run

`~/apache-maven-3.8.1/bin/mvn compile quarkus:dev`

without any issues.

By the way, when I had clean / fresh .m2 with simple settings.xml ready when running

`~/apache-maven-3.8.1/bin/mvn compile quarkus:dev -s ~/.m2sb/settings.xml`

started downloading into .m2 location rather than to .m2sb location, so that confirmed that -s option is ignored with quarkus:dev.

Mode details can be seen at: [stackoverflow](https://stackoverflow.com/questions/67999561/quarkus-running-in-dev-mode-does-not-see-pom-dependecy?noredirect=1#comment120188979_67999561)

Cheers,

mat

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by aloubyansky** [comment]
`-s ~/.m2sb/settings.xml` by itself does not specify the local maven repo location. The `localRepository` element it contains does. So what's its value? If it's missing the default local repo location will still be `~/.m2/repository`.
I couldn't reproduce this issue. I'm pretty sure the issue is in your environment.

**Comment by mettwm** [comment]
Thanks very much for looking into this. I have looked at  my original ~/.m2sb/settings.xml and there was <localRepository>${user.home}/.m2sb/repository</localRepository>, so that was not definitely pointing to ./m2 . However, I am going to try to simulate it again with completely a new maven repo placed at different location than the default to see if I had a problem within my environment setup. I will let you know. (probably in late evening). Cheers.

**Comment by aloubyansky** [comment]
Also try testing with the absolute paths in `<localRepository>`. I am not sure it supports expressions. E.g. I can tell for sure `~` won't be recognized by Maven, it'll end up creating `~` directory in your current directory.

**Comment by mettwm** [comment]
Ok, I will try.

**Comment by famod** [comment]
> Also try testing with the absolute paths in `<localRepository>`. I am not sure it supports expressions. E.g. I can tell for sure `~` won't be recognized by Maven, it'll end up creating `~` directory in your current directory.

Yeah, this sounds _very_ familiar: #11449

**Comment by aloubyansky** [comment]
@mettwm did adjusting your local repo config as suggested above help?

**Comment by aloubyansky** [comment]
@mettwm please re-open if you still see the issue in your environment. Thanks.
