### ISSUE TITLE
Quarkus compilation failure due to java.base does not "opens java.util" to unnamed module in quarkus-resteasy-reactive-kotlin

### ISSUE THREAD

**Issue by sarxos** [quarkusio/quarkus#17957]
## Describe the bug

Hello there! I would like to play with the cutting edge features of the Quarkus but I'm unable to build the 999-SNAPSHOT because compilation fails on the `quarkus-resteasy-reactive-kotlin` module. I tried to work this out simply by removing it from the parent POM and commenting out the dependency in `runtime` module, but this did not help because other Kotlin-related modules are failing as well (i.e. `quarkus-smallrye-reactive-messaging-kotlin`).

### Expected behavior

Compilation does not fail.

### Actual behavior

Compilation of the `quarkus-resteasy-reactive-kotlin` module fails.

## To Reproduce

Go to the project root directory:

```plain
$ cd quarkus
```

Checkout the latest commit (the ed5b08a538cfb3aa085ea9bc1104dd20a553d2f4 at the time when I am creating this bug report):

```plain
$ git checkout main
$ git reset --hard ed5b08a538cfb3aa085ea9bc1104dd20a553d2f4
```

Compile the project:

```plain
$ ./mvnw clean install -DskipTests=true
```

Observe:

```plain
[INFO] ------------< io.quarkus:quarkus-resteasy-reactive-kotlin >-------------
[INFO] Building Quarkus - RESTEasy Reactive - Kotlin 999-SNAPSHOT     [147/927]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ quarkus-resteasy-reactive-kotlin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce) @ quarkus-resteasy-reactive-kotlin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-test-deps-scope) @ quarkus-resteasy-reactive-kotlin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-test-deps-junit-scope) @ quarkus-resteasy-reactive-kotlin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-java-version) @ quarkus-resteasy-reactive-kotlin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven-version) @ quarkus-resteasy-reactive-kotlin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-no-runtime-deps) @ quarkus-resteasy-reactive-kotlin ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ quarkus-resteasy-reactive-kotlin ---
[INFO] 
[INFO] --- formatter-maven-plugin:2.15.0:format (default) @ quarkus-resteasy-reactive-kotlin ---
[INFO] Using 'UTF-8' encoding to format source files.
[INFO] Number of files to be formatted: 0
[INFO] 
[INFO] --- impsort-maven-plugin:1.6.2:sort (sort-imports) @ quarkus-resteasy-reactive-kotlin ---
[INFO] Processed 0 files in 00:00.000 (Already Sorted: 0, Needed Sorting: 0)
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ quarkus-resteasy-reactive-kotlin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/sarxos/workspace-2019/quarkus/extensions/resteasy-reactive/quarkus-resteasy-reactive/kotlin/src/main/resources
[INFO] 
[INFO] --- kotlin-maven-plugin:1.4.32:compile (compile) @ quarkus-resteasy-reactive-kotlin ---
[ERROR] java.lang.ExceptionInInitializerError
	at com.intellij.pom.java.LanguageLevel.<clinit>(LanguageLevel.java:25)
	at com.intellij.core.CoreLanguageLevelProjectExtension.<init>(CoreLanguageLevelProjectExtension.java:26)
	at com.intellij.core.JavaCoreProjectEnvironment.<init>(JavaCoreProjectEnvironment.java:42)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreProjectEnvironment.<init>(KotlinCoreProjectEnvironment.kt:26)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.<init>(KotlinCoreEnvironment.kt:121)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:425)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:226)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:152)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.execCompiler(KotlinCompileMojoBase.java:228)
	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execCompiler(K2JVMCompileMojo.java:237)
	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execCompiler(K2JVMCompileMojo.java:55)
	at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.execute(KotlinCompileMojoBase.java:209)
	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execute(K2JVMCompileMojo.java:222)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.util.ResourceBundle.setParent(java.util.ResourceBundle) accessible: module java.base does not "opens java.util" to unnamed module @49ebe3ab
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.intellij.util.ReflectionUtil.makeAccessible(ReflectionUtil.java:252)
	at com.intellij.util.ReflectionUtil.getDeclaredMethod(ReflectionUtil.java:269)
	at com.intellij.DynamicBundle.<clinit>(DynamicBundle.java:22)
	... 46 more
```

### Configuration

N/A

### Screenshots

N/A

### Output of `uname -a` or `ver`

```plain
$ uname -a
Linux sarxos-comp-4 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Output of `java -version`

```plain
$ java -version
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

### GraalVM version (if different from Java)

GraalVM is not installed.

### Quarkus version or git rev

```plain
ed5b08a538cfb3aa085ea9bc1104dd20a553d2f4
```

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```plain
$ ./mvnw --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /home/sarxos/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1
Java version: 16.0.1, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-16-oracle
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-55-generic", arch: "amd64", family: "unix"
```

## Additional context

N/A

**Comment by geoand** [comment]
I just tried it and it works for fine for me.
Can you try building with JDK 11?

**Comment by sarxos** [comment]
Hi @geoand,

Welp, I did try to build it with JDK 11 yesterday and only switched to 16 when I was unable to. After you mentioned it, I did a bit bit of investigation.

```plain
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

When I tried to compile it with:

```plain
$ ./mvnw clean install -DskipTests=true
```

I got the very same error as for the JDK 16:

```plain
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.4.32:compile (compile) on project quarkus-resteasy-reactive-kotlin: Compilation failure
[ERROR] java.lang.ExceptionInInitializerError
[ERROR] 	at com.intellij.pom.java.LanguageLevel.<clinit>(LanguageLevel.java:25)
[ERROR] 	at com.intellij.core.CoreLanguageLevelProjectExtension.<init>(CoreLanguageLevelProjectExtension.java:26)
[ERROR] 	at com.intellij.core.JavaCoreProjectEnvironment.<init>(JavaCoreProjectEnvironment.java:42)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreProjectEnvironment.<init>(KotlinCoreProjectEnvironment.kt:26)
...
[ERROR] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.util.ResourceBundle.setParent(java.util.ResourceBundle) accessible: module java.base does not "opens java.util" to unnamed module @4ade3c14
[ERROR] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[ERROR] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[ERROR] 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[ERROR] 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
...
```

I did change the JDK version by doing:

```plain
$ sudo update-java-alternatives --set java-1.11.0-openjdk-amd64
```

And the result from `java -version` was as expected.

But it seems like the Jetbrains compiler (or probably Maven) **does not** use the `java` from the `$PATH` but rather the one from the `$JAVA_HOME`. When I checked it I found out that:

```plain
$ echo $JAVA_HOME
```

Got me:

```plain
/usr/lib/jvm/java-16-oracle
```

Then, after doing:

```plain
$ export JAVA_HOME=""
```

The compilation finally succedded.

Lesson learned: **make sure to verify that `$JAVA_HOME` is set to the same version as the `java -version` gives**.

But the bottom line is the fact that Quarkus support for Kotlin will not compile on JDK 16. I created a JetBrains bug ticket to document this problem.

https://youtrack.jetbrains.com/issue/KT-47308

Thank you for your time!

**Comment by geoand** [comment]
👍🏼

**Comment by sarxos** [comment]
Hi @geoand,

Just to follow up. Kotlin maintainers suggested in my bug report [KT-47308](https://youtrack.jetbrains.com/issue/KT-47308) to upgrade Kotlin from 1.4.32 to 1.5.10. I saw a PR https://github.com/quarkusio/quarkus/pull/17443 for this, which is still work in progress.

**Comment by geoand** [comment]
Right. @evanchooly had taken over that work

**Comment by famod** [comment]
FTR, #16806 ist the main ticket for the update to 1.5.

**Comment by GavinRay97** [comment]
Also hitting this

**Comment by GavinRay97** [comment]
Based on suggestions found here:
- https://github.com/ebean-orm/ebean/issues/2202#issuecomment-846531453
- https://github.com/gradle/gradle/issues/16383#issuecomment-857198947
- https://github.com/gradle/gradle/issues/16383#issuecomment-863130106

I have tried setting the recommended options.
In `gradle.properties`:
```properties
org.gradle.jvmargs=-Dkotlin.daemon.jvm.options=--illegal-access=permit
```
In `gradlew`:
```bash
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m" --add-opens java.base/java.util=ALL-UNNAMED'
```
In `build.grade.kts`, changes made:
```kts
plugins {
    application
}

application {
    applicationDefaultJvmArgs = listOf("--add-opens", "java.base/java.util=ALL-UNNAMED")
}

allOpen {
    annotation("java.util")
}
```

But, no luck =(

I assume none of this works because the compilation is happening programmatically and these args need to be set during the compilation, or the Kotlin dev module would need to somehow be able to inherit the parent processes default args?

Honestly I have no idea what exactly these were meant to do, so it was a shot in the dark, but just to save anyone else the time.

**Comment by JJBRT** [comment]
Please take a look at my new article that explain [how to export all modules to all modules at runtime in Java 16 and later](https://dev.to/jjbrt/how-to-avoid-resorting-to-add-exports-and-add-opens-in-jdk-16-and-later-j3m) without using any JVM parameter

**Comment by efecanahmetoglu** [comment]
**POM:**
```
   <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <argLine>
                                --add-opens java.base/java.lang=ALL-UNNAMED
                                --add-opens java.base/java.io=ALL-UNNAMED
                                --add-opens java.base/java.util=ALL-UNNAMED
                                --add-opens java.base/java.base=ALL-UNNAMED
                            </argLine>
                            <skipTests>${skip.unit.tests}</skipTests>
                        </configuration>
 </plugin>
```
