### ISSUE TITLE
Building quarkus main fails due to java.net.BindException: Address already in use in KafkaStreamsStartupFailureTest

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#17988]
## Describe the bug
Building the current quarkus main branch is failing in the io.quarkus.it.kafka.streams.KafkaStreamsStartupFailureTest due to an address in use exception.

After checking the test code for the ports in question, both the 2182, 19092 ports were not seen to be in use by any process according to lsof -i.

### Expected behavior
The maven build installs without error

### Actual behavior
```bash
[ERROR] io.quarkus.it.kafka.streams.KafkaStreamsStartupFailureTest.testShutdownBeforeKStreamsStarted  Time elapsed: 0 s  <<< ERROR!
...
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource io.quarkus.it.kafka.streams.KafkaTestResource@4e37f121
	at io.quarkus.test.common.TestResourceManager.start(TestResourceManager.java:57)
	... 47 more
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.quarkus.it.kafka.streams.KafkaTestResource.start(KafkaTestResource.java:86)
	at io.quarkus.test.common.TestResourceManager.start(TestResourceManager.java:52)
	... 47 more
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:73)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.configure(NIOServerCnxnFactory.java:687)
	at org.apache.zookeeper.server.ServerCnxnFactory.configure(ServerCnxnFactory.java:76)
	at org.apache.zookeeper.server.ServerCnxnFactory.createFactory(ServerCnxnFactory.java:155)
	at io.debezium.kafka.ZookeeperServer.startup(ZookeeperServer.java:67)
	at io.debezium.kafka.KafkaCluster.startup(KafkaCluster.java:248)
	at io.quarkus.it.kafka.streams.KafkaTestResource.start(KafkaTestResource.java:84)
	... 48 more
```

## To Reproduce

1. mvn -T C8 clean install 

This does not happen every time, so seems to be some race condition between tests.

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Darwin Scotts-iMacPro 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

### Output of `java -version`
└> $JAVA_HOME/bin/java -version
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

### GraalVM version (if different from Java)
N/A

### Quarkus version or git rev
commit 96470389f88894f87a2591f47e396725fff3fbe6 (HEAD -> master, origin/master, origin/HEAD)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
└> mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "Mac"

## Additional context
This is an 18 core Xeon W machine

**Comment by famod** [comment]
Parallel execution of tests (`-T x` and/or via surefire forkCount etc.) is not supported. Many tests use fixed ports and so collisions are very likely. 
But you can build main in parallel _without_ tests via `mvn -Dquickly T x` (see CONTRIBUTING.md).

@geoand @gsmet I could have a look but I suppose it's going to be a can of worms. But since I like fast and efficient build processes, I kind of intrigued. 😉 
I have to say though that probably CI won't benefit, given it has only 2 cores.

**Comment by geoand** [comment]
Yeah exactly.

If you want to play around, knock yourself out 😜
