### ISSUE TITLE
JIB can not build without Docker daemon running

### ISSUE THREAD

**Issue by liuzqt** [quarkusio/quarkus#17992]
## Describe the bug
JIB can not build without Docker daemon running,
got this error:

```
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
        at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:193)
        at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:138)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.util.concurrent.ExecutionException: java.io.IOException: 'docker load' command failed with error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
        at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
        at com.google.cloud.tools.jib.builder.steps.StepsRunner.run(StepsRunner.java:219)
        at com.google.cloud.tools.jib.api.Containerizer.run(Containerizer.java:366)
        at com.google.cloud.tools.jib.api.JibContainerBuilder.containerize(JibContainerBuilder.java:598)
        at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:186)
        ... 11 more
  Caused by: java.io.IOException: 'docker load' command failed with error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  
        at com.google.cloud.tools.jib.docker.DockerClient.load(DockerClient.java:211)
        at com.google.cloud.tools.jib.builder.steps.LoadDockerStep.call(LoadDockerStep.java:74)
        at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$loadDocker$18(StepsRunner.java:618)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
  Caused by: java.io.IOException: Broken pipe
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
        at com.google.cloud.tools.jib.http.NotifyingOutputStream.write(NotifyingOutputStream.java:61)
        at org.apache.commons.compress.utils.CountingOutputStream.write(CountingOutputStream.java:48)
        at org.apache.commons.compress.utils.FixedLengthBlockOutputStream$BufferAtATimeOutputChannel.write(FixedLengthBlockOutputStream.java:244)
        at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.writeBlock(FixedLengthBlockOutputStream.java:92)
        at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.maybeFlush(FixedLengthBlockOutputStream.java:86)
        at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.write(FixedLengthBlockOutputStream.java:122)
        at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.write(TarArchiveOutputStream.java:454)
        at java.base/java.security.DigestOutputStream.write(DigestOutputStream.java:146)
        at com.google.cloud.tools.jib.hash.CountingDigestOutputStream.write(CountingDigestOutputStream.java:80)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:113)
        at com.google.cloud.tools.jib.hash.Digests.lambda$computeDigest$2(Digests.java:85)
        at com.google.cloud.tools.jib.hash.Digests.computeDigest(Digests.java:102)
        at com.google.cloud.tools.jib.hash.Digests.computeDigest(Digests.java:86)
        at com.google.cloud.tools.jib.blob.FileBlob.writeTo(FileBlob.java:39)
        at com.google.cloud.tools.jib.tar.TarStreamBuilder.writeAsTarArchiveTo(TarStreamBuilder.java:52)
        at com.google.cloud.tools.jib.image.ImageTarball.dockerWriteTo(ImageTarball.java:149)
        at com.google.cloud.tools.jib.image.ImageTarball.writeTo(ImageTarball.java:78)
        at com.google.cloud.tools.jib.docker.DockerClient.load(DockerClient.java:197)
        ... 8 more
        Suppressed: java.io.IOException: This archive contains unclosed entries.
                at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:289)
                at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:307)
                at com.google.cloud.tools.jib.tar.TarStreamBuilder.writeAsTarArchiveTo(TarStreamBuilder.java:55)
                ... 11 more
```

With docker daemon running, everything works fine.

It's not a big deal since I do have installed docker, but this is not consistent with https://quarkus.io/guides/container-image#container-image-extensions

### Expected behavior
(Describe the expected behavior clearly and concisely.)

### Actual behavior
(Describe the actual behavior clearly and concisely.)

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
`Darwin 157-48-161-10-in-addr.tusimple.ai 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`

### Output of `java -version`
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)
```
### Quarkus version or git rev
```
1.13 FINAL
```
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Initialized native services in: /Users/ziqi.liu/.gradle/native

------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (GraalVM Community 11.0.11+8-jvmci-21.1-b05)
OS:           Mac OS X 10.15.6 x86_64
```

## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment]
The documentation mentions that a docker daemon is not needed if all you do is push the image.
If you build it and not push it, you need docker

**Comment by kevinross** [comment]
@geoand I'm not sure if this was the case back in 2021, but it definitely isn't the case today: with [this](https://github.com/GoogleContainerTools/jib/blob/934814cc5a2f8d22af8644aabe0d2a2e803818cd/jib-core/src/main/java/com/google/cloud/tools/jib/api/Containerizer.java#L110), we can build an image entirely offline, with no daemon of any kind, so long as we don't intend to push. While it's not obvious from that method, I've tested that if you build to a tar file, it doesn't require a daemon; I'm not sure whether it's because it tests for one and would use it if available and falls back to a built-in java-impl docker client, or if it doesn't actually use the daemon _at all_ when building to a tar, but my environment lacks a docker daemon and I'm able to build to a tar with no issue.

**Comment by geoand** [comment]
Sure yeah, building a tar is possible without a daemon, but that's not terribly useful

**Comment by kevinross** [comment]
I disagree on usefulness: in one of my ("my"->"workplace") environments,
we're not permitted to deploy to the target registry directly and have to
go through what amounts to the equivalent of a bastion host (the
environment: govcloud, the bastion host equivalent: S3 bucket) by first
exporting to a tar. We could skip configuring docker-in-docker and all that
if we could avoid the need for a daemon entirely (which I've done, with
some help from gradle, jib-core, and jib-cli's sources: in buildSrc, I
clone jib, then add it to the classpath for a custom plugin task, which
calls the jib-cli entrypoint; I have jib.yaml in my project root, where I
recreate the layers quarkus defines). It _works_, but it's a lot of extra
code that only translates to a couple of extra lines in JibProcessor and
that loses out on any changes to how the image is optimized and built (I'm
thinking of CDS, SnapStart when I say that: my DIY impl doesn't take those
into consideration, and I don't know if it actually needs to or not. Having
build-to-tar be a quarkus thing and not a DIY one means it's not a
consideration at all): "} else if (imageInfoBuildItem.tarPath.isPresent())
{ containerizer =
Containerizer.of(TarImage.from(imageInfoBuildItem.tarPath.get())); } else
{".

IMO, having a daemon-less container image builder is a selling point for
quarkus. It removes yet another requirement on the build environment, which
makes deciding on and using quarkus that much easier.

Question: are you open to accepting a patch to implement this, or is it
(build to tar) explicitly something quarkus won't do (ie the question has
come up before and you've decided against, for some set of reasonable
arguments that held true at the time and that may still hold true today)?

**Comment by geoand** [comment]
@kevinross fair enough. 

We could certainly add this capablity, I'm not against it. My only reservation is around finding the proper user experience / configuration flag for this.
