### ISSUE TITLE
@InjectMock doesn't work with @LoggerName

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#18001]
## Describe the bug
In a `@QuarkusTest` annotated test I would expect to be able to use `@InjectMock` (or `@InjectSpy`) together with `@LoggerName` assuming there is a production class which also has a field annotated with the same `@LoggerName` annotation:

```java
@QuarkusTest
public class LoggerTest {

    @InjectMock
    @LoggerName("foo")
    Logger logger;

    @Test
    void test() { ... }
}
```

When I try this I get an exception thrown:

```
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance

	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:848)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:812)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:72)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:77)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:342)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:289)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:267)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:259)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:258)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:101)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:100)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:111)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:111)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:79)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:840)
	... 61 more
Caused by: java.lang.IllegalStateException: Unable to derive the logger name at io.quarkus.arc.impl.CurrentInjectionPointProvider$InjectionPointImpl@56826a75
	at io.quarkus.arc.runtime.LoggerProducer.getLoggerWithCustomName(LoggerProducer.java:39)
	at io.quarkus.arc.runtime.LoggerProducer_ProducerMethod_getLoggerWithCustomName_66e0090f9ca11e7ac11138dde99fef2171e15248_Bean.create(LoggerProducer_ProducerMethod_getLoggerWithCustomName_66e0090f9ca11e7ac11138dde99fef2171e15248_Bean.zig:231)
	at io.quarkus.arc.runtime.LoggerProducer_ProducerMethod_getLoggerWithCustomName_66e0090f9ca11e7ac11138dde99fef2171e15248_Bean.get(LoggerProducer_ProducerMethod_getLoggerWithCustomName_66e0090f9ca11e7ac11138dde99fef2171e15248_Bean.zig:261)
	at io.quarkus.arc.runtime.LoggerProducer_ProducerMethod_getLoggerWithCustomName_66e0090f9ca11e7ac11138dde99fef2171e15248_Bean.get(LoggerProducer_ProducerMethod_getLoggerWithCustomName_66e0090f9ca11e7ac11138dde99fef2171e15248_Bean.zig:296)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:430)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:443)
	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:413)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:222)
	at io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.getBeanInstance(CreateMockitoMocksCallback.java:72)
	at io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.afterConstruct(CreateMockitoMocksCallback.java:28)
	... 66 more
```

### Expected behavior
`@LoggerName` should work together with `@InjectSpy` and `@InjectMock` so that a Quarkus test can verify that the expected log messages are being logged.

### Actual behavior
Test cannot be instantiated (see above).

## To Reproduce

See description.

### Quarkus version or git rev
Quarkus 2.0.0.CR3

**Comment by geoand** [comment]
I think we should disalllow this. WDYT @Ladicek ?

**Comment by Ladicek** [comment]
Injected loggers are dependent-scoped anyway, so this has zero chance of working. `@InjectMock` only works for normal-scoped beans.

CC @mkouba

**Comment by Ladicek** [comment]
I wonder if there's a way to discover if `@InjectMock` is used with a bean that isn't normal-scoped. Then we could produce a good error message. WDYT @mkouba?

**Comment by mkouba** [comment]
> I wonder if there's a way to discover if `@InjectMock` is used with a bean that isn't normal-scoped. Then we could produce a good error message. WDYT @mkouba?

That's a very good idea! Actually, it seems that we do some checks in `MockSupport.installMock()`. But it's too late for a dependent bean that attempts to inspect the `InjectionPoint` metadata.

**Comment by geoand** [comment]
So what do you propose @mkouba ?

**Comment by geoand** [comment]
Now that I think of it, it might be cool to figure out a way to get this work, because it would allow users to extremely easily perform assertions on logs (whether or not that is a good practice is certainly debatable)

**Comment by mkouba** [comment]
> Now that I think of it, it might be cool to figure out a way to get this work,

I don't think it's possible because you need `@Dependent` bean to inspect the `InjectionPoint` metadata. Other scopes just don't work (for obvious reasons).

**Comment by geoand** [comment]
Yeah... It's too bad

**Comment by knutwannheden** [comment]
> Now that I think of it, it might be cool to figure out a way to get this work, because it would allow users to extremely easily perform assertions on logs (whether or not that is a good practice is certainly debatable)

I was thinking it would be cool if I could use `@LoggerName`, but I didn't know or think much about the implementation details, so I didn't realize this wouldn't be possible. But in the end what I want is some easy way of testing the logging aspect. So far I am using something similar to Quarkus' `InMemoryLogHandler`, but somewhat "tweaked" so I can use it in a try-with-resources to temporarily intercept the logging:

```java
        try (InMemoryLogHandler handler = InMemoryLogHandler.intercept(
                Logger.getLogger(ForbiddenExceptionMapper.class.getName()))) {
            RestAssured.given().when().get("/jap-devops").thenReturn();
            assertThat(handler.lastRecord().getMessage(),
                    equalTo("URI = %s; Method = %s; Admissible roles = %s; User = %s; User roles = %s"));
            assertThat(handler.lastRecord().getParameters(),
                    equalTo(new Object[]{"http://localhost:8081/tst/test/security-test-jap-devops/jap-devops", "GET",
                            "[JAP-DEVOPS]", "U123456", "[Admin]"}));
        }
```

I could open a separate feature request for an improved log testing feature, if you think that would be helpful.

**Comment by geoand** [comment]
> > I wonder if there's a way to discover if `@InjectMock` is used with a bean that isn't normal-scoped. Then we could produce a good error message. WDYT @mkouba?
> 
> That's a very good idea! Actually, it seems that we do some checks in `MockSupport.installMock()`. But it's too late for a dependent bean that attempts to inspect the `InjectionPoint` metadata.

So what can we do?

**Comment by mkouba** [comment]
> So what can we do?

Well, we could check the bean scope via `io.quarkus.arc.InstanceHandle.getBean()` in `io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.getBeanInstance()` and throw an exception unless the scope is normal.

**Comment by geoand** [comment]
Care to open a PR with that check?

**Comment by knutwannheden** [comment]
Just for my understanding, since I am no CDI expert: Is it really necessary to use the `@Dependent` scope for the `@LoggerName` qualifier? It seems a little bit odd given that the singleton `LoggerProducer` caches all instances in a map and at the same time `Dependent` states that the injected bean is bound to the lifecycle of the created (owning) object.

**Comment by mkouba** [comment]
>  Is it really necessary to use the `@Dependent` scope for the `@LoggerName` qualifier?

It is necessary beacuse for other scopes the bean instance may be (and usually is) shared accross multiple injection points and each one can define a different logger name. 

> It seems a little bit odd given that the singleton `LoggerProducer` caches all instances in a map...

I agree that it may feel odd but we effectively just cache the logger for the given name to conserve resources.

**Comment by Ladicek** [comment]
> > Is it really necessary to use the `@Dependent` scope for the `@LoggerName` qualifier?
> 
> It is necessary beacuse for other scopes the bean instance may be (and usually is) shared accross multiple injection points and each one can define a different logger name.

Just out of curiosity -- that's only because `LoggerName.value` is `@Nonbinding`, right? Would it be possible to make the attribute binding?

**Comment by mkouba** [comment]
> Would it be possible to make the attribute binding?

Yeas, but in that case, it wouldn't be possible to use a producer method for all the injection points. We would have to collect all `@LoggerName` injection points and create a synthetic bean per each unique name found. It's doable via an extension but it's suboptimal, esp. for an application with a large number of `@LoggerName` injection points.

**Comment by Ladicek** [comment]
Gotcha, understood! Thanks.

**Comment by mkouba** [comment]
I'm closing this one because it works as expected, plus a proper error message was added in https://github.com/quarkusio/quarkus/pull/18030.

**Comment by knutwannheden** [comment]
Thanks. If you can think of any way Quarkus could improve the situation for tests which want to verify the logging, I can open a separate feature request for that.

Possibly the test could mock / override the `LoggerProducer`?

**Comment by mkouba** [comment]
> Possibly the test could mock / override the `LoggerProducer`?

Yes, something like this should work:
```java
@Singleton
public class MyLoggerProducer {

    @AlternativePriority(1)
    @Dependent
    @Produces
    Logger getSimpleLogger(InjectionPoint injectionPoint) {
        // e.g. wrap the logger...
        return myLoggerInstance;
    }
 }
```

**Comment by geoand** [comment]
@mkouba would the `@Mock` not work instead of `@AlternativePriority(1)`?

**Comment by mkouba** [comment]
> @mkouba would the `@Mock` not work instead of `@AlternativePriority(1)`?

Yes, that should work too..
