### ISSUE TITLE
Kafka-client SASL in Native mode throw  a `ClassNotFoundException`

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#18000]
## Describe the bug

When I am trying to produce Kafka events from a Quarkus app in native mode, I got the following exception

```
Caused by: java.lang.ClassNotFoundException: org.wildfly.security.sasl.plain.PlainSaslClientFactory
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:290)
	at java.security.Provider$Service.getImplClass(Provider.java:1920)
	... 34 more
```

Kafka is secured by SASL protocol. 

Environment in order to reproduce the issue: 

Quarkus: Upstream (2.x)
Native base image: `ubi-quarkus-native-image:21.1-java11`
Reproducer: `https://github.com/pjgg/beefy-scenarios/tree/feat/kafka_client_authn`
cmd: 
```
mvn -fae -V -B -s .github/mvn-settings.xml -fae clean verify -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=4g -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:21.1-java11 -pl 009-quarkus-infinispan-grpc-kafka
```

Note: the same scenario works as expected pointing to `quay.io/quarkus/ubi-quarkus-native-image:20.3-java11`

**Comment by cescoffier** [comment]
From where comes org.wildfly.security.sasl.plain.PlainSaslClientFactory? This class is most probably not present in native. You would need to register it.

**Comment by pjgg** [comment]
Ok after some "deep" search I found the root of the issue:

Basically `org.wildfly.security.sasl.plain.PlainSaslClientFactory` comes with a transitive dependency from this extension: `io.quarkus:quarkus-elytron-security-common`

That comes with another extension: `io.quarkus:quarkus-infinispan-client`

As you can see in the dependency tree: 

```
 +- io.quarkus:quarkus-infinispan-client:jar:999-SNAPSHOT:compile
 |  +- io.quarkus:quarkus-caffeine:jar:999-SNAPSHOT:compile
 |  |  \- com.github.ben-manes.caffeine:caffeine:jar:2.9.1:compile
 |  +- io.quarkus:quarkus-netty:jar:999-SNAPSHOT:compile
 |  |  +- io.netty:netty-codec:jar:4.1.65.Final:compile
 |  |  +- io.netty:netty-codec-http2:jar:4.1.65.Final:compile
 |  |  \- io.netty:netty-handler:jar:4.1.65.Final:compile
 |  +- io.quarkus:quarkus-elytron-security-common:jar:999-SNAPSHOT:compile
 |  |  \- org.wildfly.security:wildfly-elytron-credential:jar:1.15.4.Final:compile
 |  |     +- org.wildfly.security:wildfly-elytron-asn1:jar:1.15.4.Final:compile
 |  |     +- org.wildfly.security:wildfly-elytron-keystore:jar:1.15.4.Final:compile
 |  |     \- org.wildfly.security:wildfly-elytron-provider-util:jar:1.15.4.Final:compile
 |  +- org.wildfly.security:wildfly-elytron-sasl-plain:jar:1.15.4.Final:compile
 |  |  +- org.wildfly.security:wildfly-elytron-sasl:jar:1.15.4.Final:compile
 |  |  |  \- org.wildfly.security:wildfly-elytron-ssl:jar:1.15.4.Final:compile
 |  |  \- org.wildfly.security:wildfly-elytron-mechanism:jar:1.15.4.Final:compile
 |  |     \- org.wildfly.security:wildfly-elytron-http:jar:1.15.4.Final:compile
 |  +- org.wildfly.security:wildfly-elytron-sasl-digest:jar:1.15.4.Final:compile
 |  |  +- org.wildfly.security:wildfly-elytron-mechanism-digest:jar:1.15.4.Final:compile
 |  |  \- org.wildfly.security:wildfly-elytron-util:jar:1.15.4.Final:compile
 |  +- org.wildfly.security:wildfly-elytron-sasl-external:jar:1.15.4.Final:compile
 |  +- org.wildfly.security:wildfly-elytron-sasl-oauth2:jar:1.15.4.Final:compile
 |  |  \- org.wildfly.security:wildfly-elytron-mechanism-oauth2:jar:1.15.4.Final:compile
 |  +- org.wildfly.security:wildfly-elytron-sasl-scram:jar:1.15.4.Final:compile
 |  |  \- org.wildfly.security:wildfly-elytron-mechanism-scram:jar:1.15.4.Final:compile
 |  +- org.infinispan:infinispan-client-hotrod:jar:12.1.1.Final:compile
 |  |  +- org.infinispan:infinispan-commons:jar:12.1.1.Final:compile
 |  |  +- org.wildfly.security:wildfly-elytron-sasl-gs2:jar:1.15.4.Final:compile
```

So basically here we have a conflict between extensions in native mode + SASL.

**Comment by gsmet** [comment]
I'm not sure it's really related to Infinispan or if the class should be registered in the Security extensions? Do we know what consumes this class?

**Comment by Karm** [comment]
Hello @pjgg, can you still reproduce this with the contemporary Mandrel & Quarkus?

**Comment by pjgg** [comment]
This scenario now is covered on: https://github.com/pjgg/quarkus-test-suite/blob/main/messaging/infinispan-grpc-kafka/src/test/java/io/quarkus/ts/messaging/infinispan/grpc/kafka/InfinispanKafkaSaslIT.java

is working as expected with: `quay.io/quarkus/ubi-quarkus-native-image:22.3-java17`
