### ISSUE TITLE
quarkus-amazon-lambda-rest: call functions without a REST path

### ISSUE THREAD

**Issue by jmaister** [quarkusio/quarkus#18045]
## Describe the bug
Using `quarkus-amazon-lambda-rest`, the functions defined with `@Path` work correctly but there is a NullPointerException, if the function is not a rest function.
Basically, we have multiple functions in the code base, and some of them are triggered by principals other than API gateway(like for example, secret manager in order to rotate the secret).
For the function that is not a rest function, we have used `@Named` annotation but it seems we can not have two types of functions in the same code base.
1- one triggered by API gateway
2- by a principal other than API Gateway. (by another lambda, secret manager, or another AWS service)
Can you provide recommendations for this use case?
### Expected behavior
The lambda function is executed.
### Actual behavior
NullPointerException because the request does not include an HTTP method. (see log below)
## To Reproduce
1. Create a project with quarkus-amazon-lambda-rest, with 2 functions, one annotated with @Path and one with @Named
2. Deploy to AWS Lambda with AWS Gateway
3. Call function annotated with @Named through lambda AWS console
### Configuration
```properties
No specific configuration
```
### Screenshots
(If applicable, add screenshots to help explain your problem.)
```
START RequestId: ed571daf-0b79-4735-9888-f1a6faa88074 Version: $LATEST
__  ____  __  _____   ___  __ ____  ______
--/ __ \/ / / / _ | / _ \/ //_/ / / / __/
-/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-06-21 12:23:55,806 INFO  [ListenerBean] (main) The application is starting...
2021-06-21 12:23:56,388 INFO  [io.quarkus] (main) function-company-sso 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.13.6.Final) started in 5.095s.
2021-06-21 12:23:56,390 INFO  [io.quarkus] (main) Profile prod activated.
2021-06-21 12:23:56,390 INFO  [io.quarkus] (main) Installed features: [amazon-dynamodb, amazon-lambda, cdi, config-yaml, resteasy, resteasy-jackson]
2021-06-21 12:23:56,447 ERROR [qua.ama.lam.http] (main) Request Failure: java.lang.NullPointerException
at io.netty.handler.codec.http.HttpMethod$EnumNameMap.hashCode(HttpMethod.java:211)
at io.netty.handler.codec.http.HttpMethod$EnumNameMap.get(HttpMethod.java:201)
at io.netty.handler.codec.http.HttpMethod.valueOf(HttpMethod.java:109)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.nettyDispatch(LambdaHttpHandler.java:182)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:61)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:41)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.handle(AmazonLambdaRecorder.java:71)
at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.handleRequest(QuarkusStreamHandler.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:375)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:899)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:257)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:192)
at lambdainternal.AWSLambda.main(AWSLambda.java:187)
END RequestId: ed571daf-0b79-4735-9888-f1a6faa88074
REPORT RequestId: ed571daf-0b79-4735-9888-f1a6faa88074	Duration: 91.02 ms	Billed Duration: 92 ms	Memory Size: 512 MB	Max Memory Used: 161 MB	Init Duration: 5388.68 ms	
No newer events at this moment. Auto retry paused.
Resume
```
### Output of `uname -a` or `ver`
AWS lamda
### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
### Quarkus version or git rev
        <quarkus-plugin.version>1.13.6.Final</quarkus-plugin.version>
        <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
        <quarkus.platform.version>1.13.6.Final</quarkus.platform.version>
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
## Additional context
(Add any other context about the problem here.)

**Comment by patriot1burke** [comment]
We don't support this.  You should not use quarkus-amazon-lambda-rest with regular AWS Lambdas.
