### ISSUE TITLE
Unable to run two CLI processes in parallel

### ISSUE THREAD

**Issue by goldmann** [quarkusio/quarkus#18111]
## Describe the bug
When using Quarkus with PicoCLI combo and having one process running in development mode - I'm unable to run another process of the same application from a native binary. It just exits with return code `1`. Nothing else is printed, I cannot even get output from `--help`.

### Expected behavior
I should be able to run the second instance without problems.

### Actual behavior
Parallel run exists without any output with return code `1`.

## To Reproduce

I can probably work on a reproducer, opening this ticket so that I do not forget to do so.

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`

❯ uname -a
Linux mistress 5.12.11-200.fc33.x86_64 #1 SMP Wed Jun 16 16:10:53 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

```
❯ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode, sharing)
```
### GraalVM version (if different from Java)

```
-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:21.1-java11
```

### Quarkus version or git rev

`-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:21.1-java11`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
❯ ./mvnw --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/goldmann/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.11, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-4.fc33.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.12.11-200.fc33.x86_64", arch: "amd64", family: "unix
```

## Additional context
(Add any other context about the problem here.)

**Comment by ebullient** [comment]
so you have the app running in dev mode via the cli, and you're trying to run the native binary of the same project.

Does this work if you use `mvn quarkus:dev` directly? (e.g. is this something specific to the CLI invocation, or is this related to something quarkus itself is doing)

**Comment by goldmann** [comment]
@ebullient When I run the CLI twice in dev mode I get on the second instance:

```
Port 8080 seems to be in use by another process. Quarkus may already be running or the port is used by another application.
Use 'netstat -anop | grep 8080' to identify the process occupying the port.
You can try to kill it with 'kill -9 <pid>'.
Quarkus application exited with code 1
Press Enter to restart or Ctrl + C to quit
```

I use following features:

```
Installed features: [cdi, config-yaml, hibernate-validator, kubernetes, kubernetes-client, picocli, quarkiverse-tekton-client, resteasy-jackson, security]
```

**Comment by goldmann** [comment]
This is correct.

Generally speaking - I'm not interested in opening any ports, at all. This is a CLI application not a server.

**Comment by goldmann** [comment]
FTR, I tried to use `quarkus.http.insecure-requests=disabled`, but as the docs say (https://quarkus.io/guides/http-reference#disable-the-http-port) - it won't even start without setting up SSL, which in my case is not what I want to do at all :)

**Comment by ebullient** [comment]
ok. I think you have the shoe on the wrong foot. ;) 
The multiple process thing has nothing to do with the CLI (so we should change the title), because the issue with running two processes is the port conflict.

`quarkus-resteasy-jackson` is what is causing the port to open.

Try  switching to `quarkus-rest-client-jackson` and see if that sorts things out.

**Comment by goldmann** [comment]
OMG, indeed, this could be it! Thanks for the pointer, I'll report back once I test it.

**Comment by goldmann** [comment]
I think the main fault is this guide here: https://quarkus.io/guides/rest-client It talks about REST client, but it adds both - client and server. I probably started with this as a skeleton and just left this. It would be much better to remove the server part entirely from the guide and use a sample payloads with `curl`.

**Comment by goldmann** [comment]
No luck really. I tried it with a dev mode process + dev mode process and dev mode process + native CLI. I'm a bit unsure what tries to open port 8080 now.

When I try to open that port 8080 in browser I get following message:

```
java.lang.IllegalStateException: No CDI container is available
	at io.quarkus.arc.impl.ArcCDIProvider.getCDI(ArcCDIProvider.java:27)
	at javax.enterprise.inject.spi.CDI.current(CDI.java:64)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:58)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:51)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:137)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup.handleHotReplacementRequest(VertxHttpHotReplacementSetup.java:49)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:349)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:345)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1038)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:137)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:132)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:426)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:423)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:149)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:131)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:164)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

FTR, here are the current features:

```
Installed features: [cdi, config-yaml, hibernate-validator, kubernetes, kubernetes-client, picocli, quarkiverse-tekton-client, rest-client, rest-client-jackson, security]
```

**Comment by ebullient** [comment]
ok. two dev mode processes at the same time will not work, as dev mode does open ports for the dev console.

I would expect a dev mode process and a native cli run (without resteasy referenced at all) to work, however. 

Do you know what processes are listening?

**Comment by goldmann** [comment]
I tried to run two native CLI processes - one which is running longer, and one shorter. When the longer one is running - I couldn't execute the other one.

**Comment by goldmann** [comment]
This is the `netstat` output when I run the native CLI process:

```
❯ netstat -anop | grep 8080
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::8080                 :::*                    LISTEN      174317/agogosctl     off (0.00/0/0)
```

`agogosctl` is the binary I run.

**Comment by ebullient** [comment]
quarkus dev will (I believe) open a port, so you should tell it to use a different one, e.g. 
```
%dev.quarkus.http.port=8888
```

**Comment by gastaldi** [comment]
You can use `%dev.quarkus.http.port=0` if you want a random port to be assigned everytime `mvn quarkus:dev` is run

**Comment by ebullient** [comment]
Should we change the topic of this issue to "Mysterious port opened in native mode" ? =)

**Comment by stuartwdouglas** [comment]
quarkus:dev will not open any ports, port 8080 is opened by vertx-http.

Can you run mvn depdencny:tree so we can figure out what is pulling in vertx-http?

**Comment by goldmann** [comment]
@stuartwdouglas You're on spot! It was `quarkus-resteasy`. Probably another leftover of the https://quarkus.io/guides/rest-client guide. After removing it from my pom's, it does not start the port and it makes me a happy man.

What would I do without you all?!

:heart:

**Comment by geoand** [comment]
Closing this as it's not a Quarkus issue
