### ISSUE TITLE
Smallrye OpenTracing trying to send traces in no-op mode

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#18131]
## Describe the bug
While `quarkus.jaeger.service-name` is not specified, then no-op tracer should be configured as stated in the https://quarkus.io/guides/opentracing#create-the-configuration
However when accessing any REST Resource the following error is printed (indicating trace data tried to be pushed to backend jaeger):

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

ERROR [io.jae.int.rep.RemoteReporter] (Thread-4) Remote reporter error: io.jaegertracing.internal.exceptions.SenderException: Failed to flush spans.
	at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:115)
	at io.jaegertracing.thrift.internal.senders.ThriftSender.close(ThriftSender.java:125)
	at io.jaegertracing.thrift.internal.senders.UdpSender.close(UdpSender.java:92)
	at io.jaegertracing.internal.reporters.RemoteReporter.close(RemoteReporter.java:105)
	at io.jaegertracing.internal.JaegerTracer.close(JaegerTracer.java:237)
	at io.jaegertracing.internal.JaegerTracer$1.run(JaegerTracer.java:146)
Caused by: io.jaegertracing.internal.exceptions.SenderException: Could not send 5 spans
	at io.jaegertracing.thrift.internal.senders.UdpSender.send(UdpSender.java:85)
	at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:113)
	... 5 more
Caused by: org.apache.thrift.transport.TTransportException: Cannot flush closed transport
	at io.jaegertracing.thrift.internal.reporters.protocols.ThriftUdpTransport.flush(ThriftUdpTransport.java:148)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73)
	at org.apache.thrift.TServiceClient.sendBaseOneway(TServiceClient.java:66)
	at io.jaegertracing.agent.thrift.Agent$Client.send_emitBatch(Agent.java:70)
	at io.jaegertracing.agent.thrift.Agent$Client.emitBatch(Agent.java:63)
	at io.jaegertracing.thrift.internal.senders.UdpSender.send(UdpSender.java:83)
	... 6 more
Caused by: java.net.PortUnreachableException: ICMP Port Unreachable
	at java.base/java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
	at io.jaegertracing.thrift.internal.reporters.protocols.ThriftUdpTransport.flush(ThriftUdpTransport.java:146)
	... 11 more

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
### Expected behavior
Tracing data should not be sent to the jaeger backend

### Actual behavior
Tracing data tried to be sent to the jaeger backend

## To Reproduce
[reproducer.zip](https://github.com/quarkusio/quarkus/files/6709306/reproducer.zip)

1. run mvn quarkus:dev
2. Access localhost:8080/hello
3. See error in logs

### Configuration
```properties

#quarkus.jaeger.service-name=Demo-Service-A
quarkus.jaeger.sampler-type=const
quarkus.jaeger.sampler-param=1

```

### Quarkus version
2.0.0.Final

## Additional context
There is a different behaviour against 1.13.7.Final. Even though `quarkus.jaeger.service-name=Demo-Service-A` is enabled in 1.13.7.Final, there was no such error message and it was silent (probably not the desired state as well according to docs)

**Comment by rymurr** [comment]
@kenfinnigan I believe this is related to #17634

We have a lot of noise in our logs now as the jaeger endpoint being set doesn't exist.

**Comment by kenfinnigan** [comment]
@rymurr it's not related as the change in the PR you referenced deals with Jaeger exporter for OpenTelemetry.

It did not impact OpenTracing integration with Jaeger in any way

**Comment by rymurr** [comment]
Ah, doh. Now I see it. Thanks @kenfinnigan for the fast response! Will continue looking for the commit that caused this.

**Comment by kshpak** [comment]
Tested with 2.6.1.Final

- Traces are still collected on Jaeger backend when ` quarkus.jaeger.service-name` is not set (the trace name defaults to projectName)

- Error message is no longer appears

**Comment by radcortez** [comment]
Closing this because we are no longer supporting OpenTracing.
