### ISSUE TITLE
rest-client with sub interface and ClientHeadersFactory throws Exception

### ISSUE THREAD

**Issue by naxmefy** [quarkusio/quarkus#18223]
## Describe the bug
(Describe the problem clearly and concisely.)
Define a rest client (e.g. API)
```java
@RegisterRestClient
@RegisterClientHeaders(CustomClientHeadersFactory.class)
@Path("/anyapi")
@Produces(MediaType.APPLICATION_JSON)
public interface API {
    @GET
    @Path("foo")
    FooDTO foo();

    @Path("/v1")
    APIV1 v1();
}
```

The Foo Endpoint works as expected. The factory is like described [here](https://quarkus.io/guides/rest-client#custom-headers-support). 

Next, let's checkout APIV1 Sub-Interface.

```java
@Produces(MediaType.APPLICATION_JSON)
public interface APIV1 {
    @GET
    @Path("bar")
    BarDTO bar();
}
```

When I call "api.v1().bar()" I get an Exception. The following:

```log
2021-06-29 09:43:43,164 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /test failed, error id: 2f3620fb-a9e9-487e-9763-4c5c74796483-1: org.jboss.resteasy.spi.UnhandledException: org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException: Handled Internally
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException: Handled Internally
	at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:72)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:718)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:492)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy69.get(Unknown Source)
	at de.sgd.oc.service.turnitin.TurnitinWebhooksResource.get(TurnitinWebhooksResource.java:40)
	at de.sgd.oc.service.turnitin.TurnitinWebhooksResource_Subclass.get$$superaccessor2(TurnitinWebhooksResource_Subclass.zig:418)
	at de.sgd.oc.service.turnitin.TurnitinWebhooksResource_Subclass$$function$$2.apply(TurnitinWebhooksResource_Subclass$$function$$2.zig:29)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at de.sgd.oc.service.turnitin.TurnitinWebhooksResource_Subclass.get(TurnitinWebhooksResource_Subclass.zig:376)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 18 more
```

When I do this with a ClientRequestFilter instead of a ClientHeadersFactory, everything works.

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

> not created yet

Or attach an archive containing the reproducer to the issue.

- see above

### Configuration
```properties
# Add your application.properties here, if applicable.
# none
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver` 

Microsoft Windows [Version 10.0.19041.1052]

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

### GraalVM version (if different from Java)

see java version

### Quarkus version or git rev

<quarkus.platform.version>1.13.6.Final</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

## Additional context
(Add any other context about the problem here.)

**Comment by naxmefy** [comment]
I think I found the problem. The problem is that sub-interfaces don't use the ClientHeadersFactory. But they use the ClientRequestFilter.

An example can be found here: https://github.com/naxmefy/quarkus_example_18223_rest_client. Check the tests

**Comment by geoand** [comment]
Is this still a problem with the latest versions of Quarkus?

**Comment by geoand** [comment]
Closing for lack of feedback
