### ISSUE TITLE
Transitive dependencies not loaded

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#18271]
## Describe the bug
The application depends on lib, with in turn depends on lib2 with dependency on org.apache.httpcomponents.httpclient.
mvn quarkus:dev works and localhost:8080/app/hello returns response as expected. Running the app with java -jar target/quarkus-app/quarkus-run.jar however throws 
```
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:61)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:44)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:46)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:116)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:123)
	at com.lib2.HttpProxyParent.<init>(HttpProxyParent.java:18)
...
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:104)
	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:60)
	... 46 more

```

### Expected behavior
The jar version should load all dependencies or fail while building the application and not at runtime

## To Reproduce
1. Unpack archive: tar xzf issue.tar.gz
[issue.tar.gz](https://github.com/quarkusio/quarkus/files/6741804/issue.tar.gz)

2. mvn clean install -f lib2 && mvn clean install -f lib
3. cd app && mvn clean package
4. java -jar target/quarkus-app/quarkus-run.jar
5. curl localhost:8080/app/hello and observe log

**Comment by stuartwdouglas** [comment]
This seems to have been fixed by https://github.com/quarkusio/quarkus/commit/77224e4a15742fa9f2a4001f39f1b4bd0f1693eb

Basically we had a dependency that included the httpclient, excluded commons-logging, but did not include jboss-logging-commons-logging.
