### ISSUE TITLE
Kafka message payload types are not registered for reflection

### ISSUE THREAD

**Issue by ozangunalp** [quarkusio/quarkus#18276]
## Describe the bug
Serde message payloads need to be registered for reflection in native builds.
If these classes were not registered by another means (i.e resteasy extension) message serde does not work in native mode.

### Expected behavior

Message serde (jackson/jsonb) works in native mode.

### Actual behavior

For example with Jackson serialization fails with a similar stacktrace:

```
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.acme.kafka.model.Quote and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at io.quarkus.kafka.client.serialization.ObjectMapperSerializer.serialize(ObjectMapperSerializer.java:37)
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:925)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:885)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.lambda$send$3(ReactiveKafkaProducer.java:96)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
	... 7 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.acme.kafka.model.Quote and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1276)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3701)
	at io.quarkus.kafka.client.serialization.ObjectMapperSerializer.serialize(ObjectMapperSerializer.java:34)
	... 13 more
``` 

## To Reproduce

1. Setup app with `smallrye-reactive-kafka` extension
2. Send/receive serde'd object to/from Kafka
3. Make sure the object is not already registered for reflection by another extension, (i.e REST endpoint payload)
4. Run the app in native mode

**Comment by cescoffier** [comment]
It depends on the serializer. For JSON yes, for Avro, I'm not so sure, for a custom serializer, probably not.

**Comment by ozangunalp** [comment]
True. It'll only be needed for Jsonb/Jackson serde.
