### ISSUE TITLE
CNFE when using (MP) ConfigProperties

### ISSUE THREAD

**Issue by tobiasstadler** [quarkusio/quarkus#18303]
## Describe the bug
I tried to use ConfigProperties in my application, e.g.
```
package org.acme;

import org.eclipse.microprofile.config.inject.ConfigProperties;

import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/hello")
public class GreetingResource {

    @ConfigProperties(prefix = "foo")
    public static class Foo {
        public String bar;
    }

    private final Foo foo;

    @Inject
    GreetingResource(@ConfigProperties Foo foo) {
        this.foo = foo;
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello RESTEasy";
    }
}
```

This works fine using `mvn compile quarkus:dev -Dfoo.bar=foobar`, but crashes with `java -Dfoo.bar=foobar -jar target/quarkus-app/quarkus-run.jar`.

### Expected behavior
The application starts fine.

### Actual behavior
```
java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:104)
	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:60)
	at io.smallrye.config.ConfigMappingClass.<init>(ConfigMappingClass.java:35)
	at io.smallrye.config.ConfigMappingClass.createConfigurationClass(ConfigMappingClass.java:27)
	at io.smallrye.config.ConfigMappingClass.access$000(ConfigMappingClass.java:7)
	at io.smallrye.config.ConfigMappingClass$1.computeValue(ConfigMappingClass.java:11)
	at io.smallrye.config.ConfigMappingClass$1.computeValue(ConfigMappingClass.java:8)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
	at io.smallrye.config.ConfigMappingClass.getConfigurationClass(ConfigMappingClass.java:17)
	at io.smallrye.config.ConfigMappingLoader.getConfigMappingClass(ConfigMappingLoader.java:42)
	at io.smallrye.config.ConfigMappingProvider$Builder.addRoot(ConfigMappingProvider.java:888)
	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:52)
	at io.smallrye.config.ConfigMappings.registerConfigProperties(ConfigMappings.java:43)
	at io.quarkus.arc.runtime.ConfigRecorder.registerConfigProperties(ConfigRecorder.java:59)
	at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy_0(ConfigBuildStep$registerConfigClasses-2116437784.zig:159)
	at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy(ConfigBuildStep$registerConfigClasses-2116437784.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:524)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
```

## To Reproduce

[Project.zip](https://github.com/quarkusio/quarkus/files/6747769/Project.zip)

1. Build the project
2. Run the project via `java -jar target/quarkus-app/quarkus-run.jar`

### Output of `uname -a` or `ver`
Darwin MacBook-Pro-von-Tobias.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment Corretto-11.0.11.9.1 (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.11.9.1 (build 11.0.11+9-LTS, mixed mode)

### Quarkus version or git rev
2.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Maven home: /Users/tobiasstadler/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1
Java version: 11.0.11, vendor: Amazon.com Inc., runtime: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "11.4", arch: "x86_64", family: "Mac"

**Comment by radcortez** [comment]
@tobiasstadler 

Sorry. This was already fixed in the latest SR Config coming in Quarkus 2.1.0. As a workaround, please update to the latest SR Config versions directly:

```xml
    <dependency>
      <groupId>io.smallrye.config</groupId>
      <artifactId>smallrye-config-common</artifactId>
      <version>2.4.1</version>
    </dependency>
    <dependency>
      <groupId>io.smallrye.config</groupId>
      <artifactId>smallrye-config</artifactId>
      <version>2.4.1</version>
    </dependency>
```

**Comment by tobiasstadler** [comment]
@radcortez Thank You for the info!
