### ISSUE TITLE
Hibernate Reactive withSession() breaks named queries & context after hot reload

### ISSUE THREAD

**Issue by markusdlugi** [quarkusio/quarkus#18301]
## Describe the bug
When using HR's `sessionFactory.withSession()` or `withTransaction()`, a hot reload of the application will lead to various problems. For example, named queries will stop working (similar to #15164) or accessing an injected SecurityContext will trigger NullPointerExceptions.

### Expected behavior
Using HR `withSession()` behaves nicely and does not break the application after any changes and subsequent hot reload.

### Actual behavior
Using HR `withSession()` will break various things in the application once a hot reload is triggered. For example, executing a NamedQuery will throw:

```
java.lang.IllegalArgumentException: Type specified for TypedQuery [com.example.Fruit] is incompatible with query return type [class com.example.Fruit]
	at org.hibernate.internal.AbstractSharedSessionContract.resultClassChecking(AbstractSharedSessionContract.java:878)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.createReactiveQuery(ReactiveSessionImpl.java:510)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.buildReactiveQueryFromName(ReactiveSessionImpl.java:487)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.createReactiveNamedQuery(ReactiveSessionImpl.java:472)
	at org.hibernate.reactive.mutiny.impl.MutinySessionImpl.createNamedQuery(MutinySessionImpl.java:251)
	at com.example.FruitResource.lambda$getFruits$0(FruitResource.java:33)
	...
```

Similarly, an injected SecurityContext will stop working:

```
java.lang.NullPointerException: null
at org.jboss.resteasy.reactive.server.injection.ContextProducers.securityContext(ContextProducers.java:119) ~[resteasy-reactive-2.0.0.Final.jar:2.0.0.Final]
at org.jboss.resteasy.reactive.server.injection.ContextProducers_Subclass.securityContext$$superforward1(ContextProducers_Subclass.zig:461) ~[quarkus:/:2.0.0.Final]
at org.jboss.resteasy.reactive.server.injection.ContextProducers_Subclass$$function$$7.apply(ContextProducers_Subclass$$function$$7.zig:24) ~[quarkus:/:2.0.0.Final]
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54) ~[arc-2.0.0.Final.jar:2.0.0.Final]
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62) ~[quarkus-arc-2.0.0.Final.jar:?]
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49) ~[quarkus-arc-2.0.0.Final.jar:?]
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521) ~[quarkus:/:?]
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41) ~[arc-2.0.0.Final.jar:2.0.0.Final]
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41) ~[arc-2.0.0.Final.jar:2.0.0.Final]
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32) ~[arc-2.0.0.Final.jar:2.0.0.Final]
at org.jboss.resteasy.reactive.server.injection.ContextProducers_Subclass.securityContext(ContextProducers_Subclass.zig:1105) ~[quarkus:/:2.0.0.Final]
at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_Bean.create(ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_Bean.zig:163) ~[quarkus:/:2.0.0.Final]
at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_Bean.create(ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_Bean.zig:194) ~[quarkus:/:2.0.0.Final]
at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:68) ~[arc-2.0.0.Final.jar:2.0.0.Final]
at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:33) ~[arc-2.0.0.Final.jar:2.0.0.Final]
at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_ClientProxy.arc$delegate(ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_ClientProxy.zig:43) ~[quarkus:/:2.0.0.Final]
at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_ClientProxy.getUserPrincipal(ContextProducers_ProducerMethod_securityContext_98b62935d2bee9dfacfb8c4a8c435c1e5da4bc13_ClientProxy.zig:120) ~[quarkus:/:2.0.0.Final]
```

## To Reproduce

Link to a small reproducer: https://github.com/markusdlugi/hibernate-reactive-hot-reload

1. Start application
2. Execute some query, e.g. `POST http://localhost:8080/fruit` or `GET http://localhost:8080/fruit`. Everything should still be working.
3. Change something in the application, e.g. remove line 33 in `FruitResource`.
4. Issue another request `GET http://localhost:8080/fruit`. The application will start hot reloading and then throw an exception when executing the NamedQuery.

### Configuration
See reproducer, no special config is required to trigger this behavior.

### Output of `uname -a` or `ver`
Microsoft Windows [Version 10.0.18363.1556]

### Output of `java -version`
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)

### GraalVM version (if different from Java)
N/A

### Quarkus version or git rev
2.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3

## Additional context
The problems do _not_ appear when injecting `Mutiny.Session` (i.e. using the `ReactiveSessionProducer`) instead of using `withSession()`. But that will in turn trigger other problems (see #18268).

**Comment by markusdlugi** [comment]
@Sanne Oh no, you beat me by 13 minutes! :laughing:
See #18299.

**Comment by Sanne** [comment]
thanks @markusdlugi ! I'll close this, but link it as you have added more interesting details.
