### ISSUE TITLE
SmallRye GraphQL Client not working in native

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#18349]
`microprofile-graphql-client-quickstart`  is failing in native with the following error.

Apart from the fact that it needs fixing, I'm very surprised we use Jersey? Shouldn't we use one of our REST Clients?

```
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:102)
	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:113)
	at io.smallrye.graphql.client.typesafe.jaxrs.JaxRsTypesafeGraphQLClientBuilder.client(JaxRsTypesafeGraphQLClientBuilder.java:36)
	at io.smallrye.graphql.client.typesafe.jaxrs.JaxRsTypesafeGraphQLClientBuilder.build(JaxRsTypesafeGraphQLClientBuilder.java:60)
	at io.quarkus.smallrye.graphql.client.runtime.SmallRyeGraphQLClientRecorder.lambda$typesafeClientSupplier$0(SmallRyeGraphQLClientRecorder.java:15)
	at 
```

**Comment by gsmet** [comment]
Example of build failing: https://github.com/quarkusio/quarkus-quickstarts/runs/2968474065?check_suite_focus=true

**Comment by phillip-kruger** [comment]
We are in the process to remove all REST dependencies.(Pure vert.x) @jmartisk ^^^

**Comment by gsmet** [comment]
We need a fix for 2.0 anyway.

**Comment by phillip-kruger** [comment]
Agree :)

**Comment by jmartisk** [comment]
I don't have access to my dev machine and I will be offline till Wednesday, so I guess I'll leave this one to you guys (if it needs a quick fix, which I suppose it does), but this is clearly related to https://github.com/quarkusio/quarkus/commit/d4f1a1430c312f5eca220d4bb0799cfb7e10b4f2 - a rest client dependency now needs to be added explicitly. I can see though that the quickstart has a dependency on `quarkus-rest-client-reactive` so it's weird that a  call (at runtime) to `javax.ws.rs.client.ClientBuilder.newBuilder` does not work, I would expect that to work.

`org.glassfish.jersey.client.JerseyClientBuilder`, AFAIK, is the default implementation `javax.ws.rs.client.ClientBuilder` tries to find if there is no other implementation registered. So it sounds a bit like a problem where `quarkus-rest-client-reactive` lets the JAX-RS client implementation slip away if its usage is not detected during build?!

Maybe switching from reactive to classic rest client would help. But that's all I can guess without access to my work machine.

**Comment by phillip-kruger** [comment]
Maybe @michalszynkiewicz can comment ? I would also assume if the non-reactive client works, the reactive one should too.
