### ISSUE TITLE
opentelemetry-quickstart native build failing

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#18350]
```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:164)
Call path from entry point to io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(): 
	at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:127)
	at io.quarkus.opentelemetry.exporter.otlp.runtime.OtlpRecorder.installBatchSpanProcessorForOtlp(OtlpRecorder.java:28)
	at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp-727556406.deploy_0(OtlpExporterProcessor$installBatchSpanProcessorForOtlp-727556406.zig:85)
	at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp-727556406.deploy(OtlpExporterProcessor$installBatchSpanProcessorForOtlp-727556406.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:447)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
```

https://github.com/quarkusio/quarkus-quickstarts/runs/2968474065?check_suite_focus=true

**Comment by kenfinnigan** [comment]
Thanks @gsmet.

An issue on Quarkus was raised yesterday: https://github.com/quarkusio/quarkus/issues/18314

**Comment by gsmet** [comment]
Ah OK, we can close this one then.
