### ISSUE TITLE
Broken Pipe log error in Dev Console in the latest snapshot 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#18447]
## Describe the bug
I'm seeing
```
2021-07-06 12:50:25,243 INFO  [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-11) RoutingContext failure (500): java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileChannelImpl.transferTo0(Native Method)
	at java.base/sun.nio.ch.FileChannelImpl.transferToDirectlyInternal(FileChannelImpl.java:501)
	at java.base/sun.nio.ch.FileChannelImpl.transferToDirectly(FileChannelImpl.java:566)
	at java.base/sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:678)
	at io.netty.channel.DefaultFileRegion.transferTo(DefaultFileRegion.java:130)
	at io.netty.channel.socket.nio.NioSocketChannel.doWriteFileRegion(NioSocketChannel.java:362)
	at io.netty.channel.nio.AbstractNioByteChannel.doWriteInternal(AbstractNioByteChannel.java:238)
	at io.netty.channel.nio.AbstractNioByteChannel.doWrite0(AbstractNioByteChannel.java:212)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:400)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:953)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:917)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:180)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:232)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:217)
	at io.vertx.core.net.impl.ConnectionBase.sendFileRegion(ConnectionBase.java:479)
	at io.vertx.core.net.impl.ConnectionBase.sendFile(ConnectionBase.java:506)
	at io.vertx.core.http.impl.Http1xServerResponse.doSendFile(Http1xServerResponse.java:537)
	at io.vertx.core.http.impl.Http1xServerResponse.sendFile(Http1xServerResponse.java:456)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:431)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:417)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.sendFile(StaticHandlerImpl.java:436)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$null$0(StaticHandlerImpl.java:231)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.getFileProps(StaticHandlerImpl.java:284)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:208)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

in quickstarts, immediately in the `security-openid-connect-quickstart` and after a few clicks in the `getting-started`.

**Comment by sberyozkin** [comment]
Note, I've applied locally Phillip's fix, #18416 just so that I could continue testing my code

**Comment by sberyozkin** [comment]
@stuartwdouglas Can you check please if you can reproduce ? I'm getting it all the time in Dev UI for Keycloak

**Comment by belu** [comment]
Seeing this exception also for 2.1.4.Final. And also this one here:
```
2021-08-30 11:50:41,657 INFO  [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-6) RoutingContext failure (500): io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
```

**Comment by geoand** [comment]
Is this still an issue? FWIW, I have never seen it

**Comment by geoand** [comment]
Closing as out of date
