### ISSUE TITLE
 Annotation class not available: @Any

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#18498]
## Describe the bug
When migrating from Quarkus `1.13.7` to `2.0.0` I began getting the below exception (referencing the `javax.enterprise.inject.Any`). Unfortunately I have not been able to isolate the problematic code from my baseline to create a reproducer. I am open to any suggestions on how to fix this.

### Expected behavior
Successful build

### Actual behavior
```
Caused by: java.lang.NullPointerException: Annotation class not available: @Any
        at io.quarkus.arc.processor.AnnotationLiteralProcessor.process(AnnotationLiteralProcessor.java:61)
        at io.quarkus.arc.processor.DecoratorGenerator.createConstructor(DecoratorGenerator.java:282)
        at io.quarkus.arc.processor.DecoratorGenerator.generate(DecoratorGenerator.java:103)
        at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:183)
        at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:457)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

## To Reproduce

I haven't been able to isolate a reproducer from our baseline.

### Output of `uname -a` or `ver`
MINGW64_NT-10.0-18363

### Output of `java -version`
OpenJDK 11.0.11

### Quarkus version or git rev
2.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.9

**Comment by stuartwdouglas** [comment]
@mkouba this line looks a bit suspect: https://github.com/quarkusio/quarkus/blob/d4dd21bd0135285aea825ca8444f28ce89688b6c/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/DecoratorGenerator.java#L280

Why is it looking for interceptor bindings for a decorator?

**Comment by mkouba** [comment]
> Why is it looking for interceptor bindings for a decorator?

Indeed, this is not correct. It should be `decorator.getDeployment().getQualifier(delegateQualifier.name())`. I'll send a PR shortly...

**Comment by mkouba** [comment]
FTR this bug occurs if a there is a decorator that declares a delegate injection point with non-defaulted qualifiers.

**Comment by mkouba** [comment]
@mweber03 Note that decorators were NOT supported before 2.0, so you might expect different behavior in your application if it contains a decorator that was ignored in 1.13.7 and earlier versions.
