### ISSUE TITLE
ConfigMapping causes ConfigBuildStep#generateConfigMappings threw an exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#18499]
## Describe the bug
I'm trying to use `@ConfigMapping` in `1.13.7` but it causes an exception during the build (see below). It looks like it is able to build fine in `2.0.0`, but I'm having other issues with that migration (https://github.com/quarkusio/quarkus/issues/18498). I'm hoping for a workaround to get `@ConfigMapping` working in `1.13`.

### Expected behavior
Successful build

### Actual behavior
```
Caused by: java.lang.NullPointerException
        at io.smallrye.config.ConfigMappingLoader.getConfigMappingsMetadata(ConfigMappingLoader.java:26)
        at io.quarkus.arc.deployment.ConfigBuildStep.generateConfigMappings(ConfigBuildStep.java:205)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

## To Reproduce

Reproducer: `service1` in https://github.com/mweber03/quarkus-test

1. `./gradlew service1:quarkusBuild`

### Output of `uname -a` or `ver`
Ubuntu 20.04

### Output of `java -version`
OpenJDK 11.0.11

### Quarkus version or git rev
1.13.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.9

**Comment by stuartwdouglas** [comment]
cc @radcortez

**Comment by radcortez** [comment]
I'll have a look.

**Comment by gsmet** [comment]
FYI, if all goes well, I plan to include the fix for #18498 in 2.0.2 released today or tomorrow. There's little chance I will release another 1.13.

**Comment by radcortez** [comment]
@mweber03 I had a look in the reproducer and the issue is that you are using the `@ConfigMapping` annotation in a class, but the annotation can only be used in interfaces. Can you please try with an interface?

**Comment by radcortez** [comment]
Implemented a validation in smallrye/smallrye-config#619
