### ISSUE TITLE
Error injecting rest client caused by PatternSyntaxException when http.nonProxyHosts is set

### ISSUE THREAD

**Issue by maykoone** [quarkusio/quarkus#18548]
## Describe the bug

when setting `http.nonProxyHosts` containing a pattern starting with `*` Quarkus fails to inject an instance of a rest client.

Despite a pattern like `*.foo.com` is not a valid regexp, it's a valid value for `nonProxyHosts` according to [Oracle Docs](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html).

### Expected behavior

Create and inject an instance of a rest client without error

### Actual behavior
When Quarkus needs to inject some rest client it fails if `http.nonProxyHost` is set with a value like `*.foo.com|localhost`
```
org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error injecting org.acme.rest.client.FooRestClient org.acme.rest.client.CountriesResource.fooApi
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:481)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error injecting org.acme.rest.client.FooRestClient org.acme.rest.client.CountriesResource.fooApi
        at org.acme.rest.client.CountriesResource_Bean.create(CountriesResource_Bean.zig:189)
        at org.acme.rest.client.CountriesResource_Bean.create(CountriesResource_Bean.zig:212)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at org.acme.rest.client.CountriesResource_Bean.get(CountriesResource_Bean.zig:244)
        at org.acme.rest.client.CountriesResource_Bean.get(CountriesResource_Bean.zig:260)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:430)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:443)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:266)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:263)
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:52)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:71)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:401)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 15 more
Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.foo.com
^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2202)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
        at io.quarkus.restclient.runtime.QuarkusRestClientBuilder.build(QuarkusRestClientBuilder.java:265)
        at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:79)
```

## To Reproduce

1.  clone the [rest-client-quickstart](https://github.com/maykoone/rest-client-quickstart)
2. `./mvnw quarkus:dev -Dhttp.proxyHost=foo-proxy.com -Dhttp.nonProxyHosts="*.foo.com|localhost|127.*|[::1]"`
3.  `curl http://localhost:8080/country`

### Configuration
Included in the project

### Output of `uname -a` or `ver`
`Linux desktop 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

### Quarkus version or git rev
`2.0.1.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /opt/maven
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/java-11-openjdk
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.72-microsoft-standard-wsl2", arch: "amd64", family: "unix"
```

**Comment by famod** [comment]
It seems your reproducer is missing the base URI config for that client.
```
IllegalArgumentException: Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding 'org.acme.rest.client.FooRestClient/mp-rest/url' or 'org.acme.rest.client.FooRestClient/mp-rest/uri' to your Quarkus configuration
```
After adding `@RegisterRestClient(baseUri="http://localhost:12345")` (or adding config in properties file) the problem is reproducible,

**Comment by maykoone** [comment]
Hi @famod 

I added the properties. Thanks for letting me know

**Comment by michalszynkiewicz** [comment]
@radcortez you have wrote the code that handles it, WDYT? 
Looking at the linked Oracle doc, I'm not sure if they mean regex patterns there or just things like `*foo.com` and `bar*`. If we wanted to keep supporting regex, it seems not doable to differentiate between the regex and non-regex usage of trailing `*`...

Maybe we could replace leading `*` with `.*` and don't care about trailing ones?

**Comment by radcortez** [comment]
Actually the code is copy of `org.jboss.resteasy.microprofile.client.RestClientBuilderImpl`. I had to do it to remove some CDI references, so we didn't have to depend on RESTEasy CDI. The same code can be found in RESTEasy.

I was having a look into the JDK code and maybe we can just do the same thing. Check `sun.net.spi.DefaultProxySelector#toPattern` and `sun.net.spi.DefaultProxySelector#disjunctToRegex`.
