### ISSUE TITLE
Kafka devservices always started despite disabling them explicitly in test mode

### ISSUE THREAD

**Issue by JeffreyThijs** [quarkusio/quarkus#18566]
## Describe the bug

When running tests, kafka devservices are started (redpanda) despite explicitly disabling them with the config parameter (`quarkus.kafka.devservices.enabled=false`). However, when i run in dev mode with this option the devservices are not started.

### Expected behavior

Don't start the kafka devservices in test mode when the are explicitly disabled.

### Actual behavior
The kafka devservices are started dispite the value of ``quarkus.kafka.devservices.enabled`.

## To Reproduce

Run a test when using kafka (quarkus-smallrye-reactive-messaging-kafka) with `quarkus.kafka.devservices.enabled=false`,

### Configuration
```properties
# Add your application.properties here, if applicable.
quarkus.kafka.devservices.enabled=false
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
`Linux saturn 5.10.0-1029-oem #30-Ubuntu SMP Fri May 28 23:53:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

### Quarkus version or git rev

2.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

## Additional context
Log:

```console
2021-07-09 14:51:22,939 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-3) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2021-07-09 14:51:24,254 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-3) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2021-07-09 14:51:24,256 INFO  [org.tes.DockerClientFactory] (build-3) Docker host IP address is localhost
2021-07-09 14:51:24,300 INFO  [org.tes.DockerClientFactory] (build-3) Connected to docker:
  Server Version: 20.10.6
  API Version: 1.41
  Operating System: Ubuntu 20.04.2 LTS
2021-07-09 14:51:24,304 INFO  [org.tes.uti.ImageNameSubstitutor] (build-3) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2021-07-09 14:51:25,625 INFO  [org.tes.DockerClientFactory] (build-3) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2021-07-09 14:51:25,626 INFO  [org.tes.DockerClientFactory] (build-3) Checking the system...
2021-07-09 14:51:25,627 INFO  [org.tes.DockerClientFactory] (build-3) ✔︎ Docker server version should be at least 1.6.0
2021-07-09 14:51:25,774 INFO  [org.tes.DockerClientFactory] (build-3) ✔︎ Docker environment should have more than 2GB free disk space
2021-07-09 14:51:25,789 INFO  [🐳 .5.5]] (build-3) Creating container for image: vectorized/redpanda:v21.5.5
2021-07-09 14:51:25,930 INFO  [🐳 .5.5]] (build-3) Starting container with ID: a3ddac4dd2e8db1174115da93296b187dde0404f3ace18595ee9fc230c4dd1a6
2021-07-09 14:51:26,524 INFO  [🐳 .5.5]] (build-3) Container vectorized/redpanda:v21.5.5 is starting: a3ddac4dd2e8db1174115da93296b187dde0404f3ace18595ee9fc230c4dd1a6
2021-07-09 14:52:26,759 ERROR [🐳 .5.5]] (build-3) Could not start container: java.lang.IllegalStateException: Container exited with code 1
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:469)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
        at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafka(DevServicesKafkaProcessor.java:156)
        at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafkaDevService(DevServicesKafkaProcessor.java:67)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

2021-07-09 14:52:26,784 ERROR [🐳 .5.5]] (build-3) Log output from the failed container:
We'd love to hear about your experience with redpanda:
https://vectorized.io/feedback
Starting redpanda...
Running:
HOSTNAME=a3ddac4dd2e8 PWD=/ HOME=/var/lib/redpanda SHLVL=1 PATH=/opt/redpanda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DEBIAN_FRONTEND=noninteractive /opt/redpanda/bin/redpanda redpanda --redpanda-cfg /etc/redpanda/redpanda.yaml --lock-memory=false


Welcome to the Redpanda community!

Slack: https://vectorized.io/slack - is the main way the community interacts with one another in real time :)
Twitter: https://twitter.com/vectorizedio - come say hi!
Github Discussion: https://github.com/vectorizedio/redpanda/discussions - is preferred for longer, async, thoughtful discussions
GitHub Issues: https://github.com/vectorizedio/redpanda/issues - is reserved only for actual issues. Please use the GitHub for discussions.
Documentation: https://vectorized.io/docs/ - official docs site
Support: https://support.vectorized.io/ - to share private information with the production support vectorized team
Product Feedback: https://vectorized.io/feedback/ - let us know how we can improve your experience


INFO   redpanda::main - application.cc:120 - Redpanda 4d2c42c - 4d2c42c15a6aca758292cb92975a9b0c322c6426
INFO   redpanda::main - application.cc:128 - kernel=5.10.0-1029-oem, nodename=a3ddac4dd2e8, machine=x86_64
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
ERROR 2021-07-09 12:51:27,407 [shard 8] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 70.76 s <<< FAILURE! - in io.my.kafka.KafkaTest
[ERROR] io.my.kafka.KafkaTest.someKafkaTest  Time elapsed: 0.007 s  <<< ERROR!
java.lang.RuntimeException:
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor#startKafkaDevService threw an exception: org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
        at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafka(DevServicesKafkaProcessor.java:156)
        at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafkaDevService(DevServicesKafkaProcessor.java:67)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
        ... 14 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:497)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        ... 15 more
Caused by: java.lang.IllegalStateException: Container exited with code 1
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:469)
        ... 17 more

Caused by: java.lang.RuntimeException:
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor#startKafkaDevService threw an exception: org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
        at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafka(DevServicesKafkaProcessor.java:156)
        at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafkaDevService(DevServicesKafkaProcessor.java:67)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
        ... 14 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:497)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        ... 15 more
Caused by: java.lang.IllegalStateException: Container exited with code 1
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:469)
        ... 17 more

Caused by: io.quarkus.builder.BuildException:
Build failure: Build failed due to errors
        [error]: Build step io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor#startKafkaDevService threw an exception: org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
        at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafka(DevServicesKafkaProcessor.java:156)
        at io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor.startKafkaDevService(DevServicesKafkaProcessor.java:67)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
        ... 14 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:497)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        ... 15 more
Caused by: java.lang.IllegalStateException: Container exited with code 1
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:469)
        ... 17 more

Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: java.lang.IllegalStateException: Container exited with code 1
```

**Comment by cescoffier** [comment]
I just tried using the kafka quickstart and it does not start the container when having `quarkus.kafka.devservices.enabled=false` in the properties file (in both dev mode and test mode). 

Do you have a simple reproducer?

**Comment by JeffreyThijs** [comment]
Issue can be closed, the config property was overwritten by a different test profile. Updating this resolved it, my bad. Thanks for the help, anyways!

**Comment by cescoffier** [comment]
Thanks for the feedback @JeffreyThijs
