### ISSUE TITLE
Register Picocli completion candidates for reflection

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#18590]
## Describe the bug

```
@Command(name = "mycommand")
public class DescribeConnectorCommand implements Runnable {

    @Parameters(paramLabel = "SOME PARAM", completionCandidates = ConnectorCompletions.class)
    String name;

    @Override
    public void run() { ... }

    private static class ConnectorCompletions implements Iterable<String> { ... }
}
```

When building a native Picocli app that uses completion candidates, the constructor of the completions `Iterable` isn't registered for reflection, resulting in this exception:

```
java.lang.NoSuchMethodException: dev.morling.kccli.command.DescribeConnectorCommand$ConnectorCompletions.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3349)
	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5489)
	at io.quarkus.picocli.runtime.PicocliBeansFactory.create(PicocliBeansFactory.java:16)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5512)
	at picocli.CommandLine$DefaultFactory.createCompletionCandidates(CommandLine.java:5506)
	at picocli.CommandLine$Model$ArgSpec$Builder.<init>(CommandLine.java:9280)
	at picocli.CommandLine$Model$PositionalParamSpec$Builder.<init>(CommandLine.java:9985)
	at picocli.CommandLine$Model$PositionalParamSpec$Builder.<init>(CommandLine.java:9975)
	at picocli.CommandLine$Model$PositionalParamSpec.builder(CommandLine.java:9934)
	at picocli.CommandLine$Model$CommandReflection.buildArgForMember(CommandLine.java:11617)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:11520)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedFields(CommandLine.java:11466)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11399)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6202)
	at picocli.CommandLine.<init>(CommandLine.java:227)
	at picocli.CommandLine.toCommandLine(CommandLine.java:3517)
	at picocli.CommandLine.access$15600(CommandLine.java:145)
	at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:11431)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11397)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6202)
	at picocli.CommandLine.<init>(CommandLine.java:227)
	at picocli.CommandLine.toCommandLine(CommandLine.java:3517)
	at picocli.CommandLine.access$15600(CommandLine.java:145)
	at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:11431)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11397)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6202)
	at picocli.CommandLine.<init>(CommandLine.java:227)
	at picocli.CommandLine.<init>(CommandLine.java:221)
	at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory.create(DefaultPicocliCommandLineFactory.java:43)
	at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory_ClientProxy.create(DefaultPicocliCommandLineFactory_ClientProxy.zig:155)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer.picocliCommandLine(PicocliCommandLineProducer.java:23)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.create(PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.zig:161)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.zig:191)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.zig:226)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.create(PicocliRunner_Bean.zig:212)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(PicocliRunner_Bean.zig:270)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(PicocliRunner_Bean.zig:305)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:430)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:443)
	at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:59)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
```

### Expected behavior
Can use completions in native Picocli binary.

### Actual behavior
Exception above.

## To Reproduce
Declare a command like above, then build with -Pnative.

### Configuration
n.a.

### Screenshots
n.a.

### Output of `uname -a` or `ver`
Darwin Kernel Version 19.6.0

### Output of `java -version`
build 17-ea+23-2064

### GraalVM version (if different from Java)
21.1.0

### Quarkus version or git rev
2.0.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Maven 3.8.1

## Additional context
n.a.

**Comment by ebullient** [comment]
raise this against picocli itself?

**Comment by gunnarmorling** [comment]
So is this to say that Picocli comes with its own GraalVM reflection
config? If so, yes, definitely makes sense to address it over there.

>

**Comment by maxandersen** [comment]
Picocli does it's graalvm via annotation processor which we can't reuse so we need the fix on our side afaik.

**Comment by gsmet** [comment]
This PR should fix it: https://github.com/quarkusio/quarkus/pull/18626 .

**Comment by gunnarmorling** [comment]
Excellent, thanks a lot for the quick fix, Guillaume!

>
