### ISSUE TITLE
Improve error reporting when user fails to attach `@MultipartForm` annotation - similar to #6738

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#18595]
## Description

If a user forgets to attach `@MultipartForm` annotation to RESTeasy controller parameter, the error returned is non-descript and not very helpful.

Maybe this could be better, similar to the solution in #6738

```kt
import org.jboss.resteasy.reactive.RestForm
import org.jboss.resteasy.reactive.multipart.FileUpload

class SourceArchiveUploadForm {
    @RestForm
    lateinit var file: FileUpload
}

@Path("/upload")
class UploadsController {

    @POST
    @Path("/script")
    @Produces(MediaType.TEXT_PLAIN)
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    fun uploadScript(upload: SourceArchiveUploadForm): String {
        return UploadsControllerService.handleFileUpload(upload)
    }
}
```

This will fail with:
```
HTTP/1.1 415 Unsupported Media Type
content-length: 0
```

**Full output of test run log:**
<details>

		    Jul 11, 2021 5:09:50 PM org.jboss.threads.Version <clinit>
		    INFO: JBoss Threads version 3.4.0.Final
		    Jul 11, 2021 5:09:52 PM org.jboss.threads.Version <clinit>
		    INFO: JBoss Threads version 3.4.0.Final
		    Jul 11, 2021 5:09:52 PM io.quarkus.bootstrap.runner.Timing printStartupTime
		    INFO: Quarkus 2.0.1.Final on JVM started in 2.630s. Listening on: http://localhost:8081
		    Jul 11, 2021 5:09:52 PM io.quarkus.bootstrap.runner.Timing printStartupTime
		    INFO: Profile test activated. 
		    Jul 11, 2021 5:09:52 PM io.quarkus.bootstrap.runner.Timing printStartupTime
		    INFO: Installed features: [cdi, config-yaml, jaxrs-client-reactive, kotlin, qute, rest-client, rest-client-mutiny, rest-client-reactive, rest-client-reactive-jackson, resteasy-reactive, resteasy-reactive-qute, smallrye-context-propagation, smallrye-health, vertx]
		    HTTP/1.1 415 Unsupported Media Type
		    content-length: 0
		    
		    2 expectations failed.
		    Expected status code <200> but was <415>.
		    
		    Response body doesn't match expectation.
		    Expected: is "ok"
		      Actual: 
		    
		    java.lang.AssertionError: 2 expectations failed.
		    Expected status code <200> but was <415>.
		    
		    Response body doesn't match expectation.
		    Expected: is "ok"
		      Actual: 
		    
			    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
			    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
			    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
			    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
			    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
			    at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
			    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
			    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
			    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
			    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
			    at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:493)
			    at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
			    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
			    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
			    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
			    at io.restassured.internal.ResponseSpecificationImpl.forceValidateResponse(ResponseSpecificationImpl.groovy:660)
			    at io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt$Then$2.invoke(RestAssuredKotlinExtensions.kt:61)
			    at io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt$Then$2.invoke(RestAssuredKotlinExtensions.kt:60)
			    at io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt$doIfValidatableResponseImpl$1.invoke(RestAssuredKotlinExtensions.kt:80)
			    at io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt$doIfValidatableResponseImpl$1.invoke(RestAssuredKotlinExtensions.kt:78)
			    at io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt.Then(RestAssuredKotlinExtensions.kt:60)
			    at org.hasura.controllers.UploadsControllerTest.uploadScript(UploadsControllerTest.kt:29)
			    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
			    at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:989)
			    at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:875)
			    at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
			    at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
			    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
			    at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
			    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
			    at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
			    at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
			    at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
			    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
			    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
			    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
			    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
			    at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
			    at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
			    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
			    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
			    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
			    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
			    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
			    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
			    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
			    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
			    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
			    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
			    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
			    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
			    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
			    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
			    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
			    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
			    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
			    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
			    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
			    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
			    at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
			    at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
			    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
			    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
			    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
			    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
			    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
			    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
			    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
			    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
			    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
			    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
			    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
			    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
			    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
			    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
			    at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
			    at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
			    at com.sun.proxy.$Proxy2.stop(Unknown Source)
			    at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
			    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
			    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
			    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
			    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
			    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
			    at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
			    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
			    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
			    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
			    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
			    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
			    at java.base/java.lang.Thread.run(Thread.java:829)
		    
		    
		    WARNING: An illegal reflective access operation has occurred
		    WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/C:/Users/rayga/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/3.0.8/43a7ecf3b8a9d7dd9fc8d468ae96b97cff4616df/groovy-3.0.8.jar) to constructor java.lang.AssertionError(java.lang.String)
		    WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
		    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
		    WARNING: All illegal access operations will be denied in a future release
		    UploadsControllerTest > uploadScript() FAILED
		        java.lang.AssertionError at UploadsControllerTest.kt:29
		    Jul 11, 2021 5:09:55 PM io.quarkus.bootstrap.runner.Timing printStopTime
		    INFO: Quarkus stopped in 1.371s
		    1 test completed, 1 failed
		    > Task :test FAILED
		    FAILURE: Build failed with an exception.
		    * What went wrong:
		    Execution failed for task ':test'.
		    > There were failing tests. See the report at: file:///C:/Users/rayga/Projects/tmp/polyglot-actions-service/quarkus-kotlin-gradle/build/reports/tests/test/index.html
		    * Try:
		    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
		    * Get more help at https://help.gradle.org
		    BUILD FAILED in 11s
		    11 actionable tasks: 7 executed, 4 up-to-date

</details>

**Comment by geoand** [comment]
Thanks for reporting!

https://github.com/quarkusio/quarkus/pull/18599 will actually make the annotation optional, so the code you attached would just work

**Comment by geoand** [comment]
👍🏼

**Comment by yuyujiejie** [comment]
Why does this not work with data classes?
