### ISSUE TITLE
StackOverflowException for Throwable ExceptionMapper

### ISSUE THREAD

**Issue by antonwiens** [quarkusio/quarkus#18603]
### Describe the bug

An ServerExceptionMapper for Throwables always throws a StackOverflowException.

Reproducer:

[reproducer-cleaned.zip](https://github.com/quarkusio/quarkus/files/6800178/reproducer-cleaned.zip)

Just Call the "/hello" Endpoint to trigger the exception.

Version: 2.0.1

### Stacktrace:
```
java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541)
	at java.base/java.lang.ClassLoader.getClassLoadingLock(ClassLoader.java:668)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:591)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:406)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:397)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:406)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:397)
	at acme.ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass.toResponse(ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass.zig:307)
	at acme.ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map.toResponse(ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map.zig:68)
	at acme.ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass.toResponse$$superforward1(ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass.zig:145)
	at acme.ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass$$function$$2.apply(ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass$$function$$2.zig:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at acme.ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass.toResponse(ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass.zig:307)
	at acme.ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map.toResponse(ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map.zig:68)
	at acme.ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass.toResponse$$superforward1(ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass.zig:145)
	at acme.ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass$$function$$2.apply(ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map_Subclass$$function$$2.zig:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
...
```

EDIT: 
I cleaned up the reproducer, because i tested a lot of stuff and left unused extensions in the gradle build file.
Also i changed the target version for kotlin to 11, because i forgot to change it.

**Comment by gsmet** [comment]
@antonwiens could you include part of the stacktrace in the description? It's helpful for other users to find similar issues.

**Comment by antonwiens** [comment]
> @antonwiens could you include part of the stacktrace in the description? It's helpful for other users to find similar issues.

I added one, sry.

**Comment by antonwiens** [comment]
@gsmet any chance this will make it for 2.1? this is blocking me from using quarkus 2 unfortunately

**Comment by gsmet** [comment]
@antonwiens so it was working in 1.13 and doesn't work anymore?

@mkouba could you have a look? I'm seeing recursive interceptor calls so I wonder if it could be related to some of the recent work on the subject.

**Comment by antonwiens** [comment]
> @antonwiens so it was working in 1.13 and doesn't work anymore?

I can say that it was working in 1.10 and in 1.12 for normal resteasy. I don't know about 1.13 and resteasy-reactive, as its the first time i am using it.

**Comment by mkouba** [comment]
> could you have a look? I'm seeing recursive interceptor calls so I wonder if it could be related to some of the recent work on the subject.

Hm, it looks like the interceptor is associated with a class  generated by resteasy reactive: 
```java
@Singleton
@Unremovable
public class ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map implements ResteasyReactiveExceptionMapper {
   private final ThrowableExceptionMapper delegate;

   @Inject
   public ThrowableExceptionMapper$GeneratedExceptionHandlerFor$Throwable$OfMethod$map(ThrowableExceptionMapper var1) {
      this.delegate = var1;
   }

   public Response toResponse(Throwable var1) {
      throw (Throwable)(new IllegalStateException("This should never be called"));
   }

   public Response toResponse(Throwable var1, ServerRequestContext var2) {
      return this.toResponse(var1, var2); // <-- This causes an infinite loop!?
   }
}
```
CC @geoand @FroMage

**Comment by geoand** [comment]
I'll take a look

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/18613 takes care of the issue
