### ISSUE TITLE
mp.jwt.verify.publickey.location is build time property in 2.0.1.Final

### ISSUE THREAD

**Issue by Andro999b** [quarkusio/quarkus#18641]
### Describe the bug

In 2.0.1.Final `mp.jwt.verify.publickey.location` become build time property

### Expected behavior

`mp.jwt.verify.publickey.location` stay runtime comfig property as it was in 2.0.0

### Actual behavior

`mp.jwt.verify.publickey.location`  is required to be evaluated in build time and cant be used with env variables

### Additional information

We are use `mp.jwt.verify.publickey.location` with remote jwks keys that passed to pod in env var. It was work fine until 2.0.1 where we cant no more use this behavior.

**Comment by sberyozkin** [comment]
@Andro999b How to you set as an ENV var ? Roberto, @radcortez can you check it please - I don't think anything has changed at the `quarkus-smallrye-jwt` or `smallrye-jwt` level in this regard

**Comment by Andro999b** [comment]
@sberyozkin like this:

```
mp:
  jwt:
    verify:
      publickey:
        location: http://${NAMESPACE}-accounts.${NAMESPACE}.svc.cluster.local/jwks
```

on 2.0.0.Final its build without any problem. But on 2.0.1.Final i gets an error:

```
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.jwt.deployment.SmallRyeJwtProcessor#registerNativeImageResources threw an exception: java.util.NoSuchElementException: SRCFG00011: Could not expand value NAMESPACE in property mp.jwt.verify.publickey.location
        at io.smallrye.config.ExpressionConfigSourceInterceptor.lambda$getValue$0(ExpressionConfigSourceInterceptor.java:63)
        at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
        at io.smallrye.common.expression.CompositeNode.emit(CompositeNode.java:22)
        at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
        at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
        at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:56)
        at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:36)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:282)
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:200)
        at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:299)
        at io.quarkus.smallrye.jwt.deployment.SmallRyeJwtProcessor.registerNativeImageResources(SmallRyeJwtProcessor.java:121)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

**Comment by sberyozkin** [comment]
@Andro999b Thanks, I believe it is not the problem of this property itself becoming a build time property only, @radcortez, that exception message rings a bell as I've seen something similar reported. @Andro999b - can you please provide a bit more info about how is `NAMESPACE` provided ? From the command line or as Kubernetes config var, etc

**Comment by Andro999b** [comment]
@sberyozkin its passed as env variable to container in kubernates
```
Containers:
  service:
    Container ID:   docker://2293f81bae2988f1cbdaee9a0cd3d217a7bc1abe7ab34478e7463da4a543013a
    Image:          registry.digitalocean.com/letsgo/cargo:dev
    Image ID:       docker-pullable://registry.digitalocean.com/letsgo/cargo@sha256:a79c9eb5efacd43bd60247b137f02a15556130945380e93d467fc4627e9ce606
    Ports:          9000/TCP, 8080/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Mon, 12 Jul 2021 12:31:02 +0300
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:http/q/health/live delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:http/q/health/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      NAMESPACE:        dev

```

**Comment by radcortez** [comment]
I did try this locally and it worked fine for me. Can you confirm that the environment variable is really present in the pod?

**Comment by Andro999b** [comment]
@radcortez its build time error(`./gradlew build`). During build we do not set NAMESPACE env var.

**Comment by Andro999b** [comment]
@radcortez Here is reproducer https://drive.google.com/file/d/16bKFclddsRlaauWkmjYE3IVdlPIB4vOj/view?usp=sharing
just try to build it. It will fail on quarkus >= 2.0.1.Final

**Comment by radcortez** [comment]
This seems to be caused by https://github.com/quarkusio/quarkus/commit/3cc026779ccd0a1ef88d3142fc49cb8bd22c743f, where `NativeImageResourceBuildItem` became a dependency of `GeneratedResourceBuildItem`.

The configuration is used in a `NativeImageResourceBuildItem` to register the keys for native image:
https://github.com/quarkusio/quarkus/blob/a099805f42b8f8c95d6e544d485260bec008aa09/extensions/smallrye-jwt/deployment/src/main/java/io/quarkus/smallrye/jwt/deployment/SmallRyeJwtProcessor.java#L118-L130

@Andro999b, to work around the issue, I recommend setting the expression to `${NAMESPACE:}` (notice the `:` in the end - this represents an empty value).

In the meanwhile, I'll propose a fix to only execute that build step when building the native image.

**Comment by radcortez** [comment]
@stuartwdouglas any thoughts?

**Comment by Andro999b** [comment]
@radcortez thanks
