### ISSUE TITLE
Mutiny Uni context propagation leaks transaction context to eventloop threads

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#18689]
### Describe the bug

We have an intermittent error "ARJUNA016053: Could not commit transaction" caused by "Caused by: java.sql.SQLException: Enlisted connection used without active transaction"  The details are as follows:

Using ReSTEasy Reactive with endpoint marked as @Transactional and @Blocking
1) Request hits endpoint
2) Endpoint does some DB work using hibernate with a worker thread
3) Endpoint uses Vertx Mutiny Http Client to a call to another service. The call returns a Uni, translated to a completionstage which the thread from (2) does a .get() on blocking for the result
4) The transaction started on (1) cannot commit with the error : ARJUNA016053: Could not commit transaction" "Caused by: java.sql.SQLException: Enlisted connection used without active transaction"

### Expected behavior

Transaction should commit without issues

### Actual behavior

```
Caused by: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1307)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.commit(CDIDelegatingTransactionManager.java:97)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:313)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:160)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at reactive.scenarios.TestRootResource_Subclass.getFails(TestRootResource_Subclass.zig:233)
	... 12 more
	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: Enlisted connection used without active transaction
		at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:140)
		at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:134)
		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:72)
		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:702)
		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2400)
		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1502)
		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:96)
		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
		... 25 more
	Caused by: java.sql.SQLException: Enlisted connection used without active transaction
		at io.agroal.pool.ConnectionHandler.verifyEnlistment(ConnectionHandler.java:352)
		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:321)
		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:69)
		... 31 more
```

### How to Reproduce?

This reproducer hits an endpoint with multiple concurrent requests and shows the issue. It is not apparent when concurrency is low.
git clone https://github.com/bcluap/quarkus-examples.git
cd quarkus-examples
git checkout mutiny
cd resteasy-reactive
mvn clean quarkus:test

Test 2 works without issues
Test 3 gives intermittent errors

### Quarkus version or git rev

2.0.1.Final

### Additional information

This appears to be an issue in Mutiny converting from a Uni to a CompletionStage and blocking for the result. The test works when using uni.await().indefinitely() but not uni.subscribeAsCompletionStage().get()

**Comment by bcluap** [comment]
Applying this change on the http client to manually suspend the transaction resolves the issue:
```
-    public Uni<String> doHttpMethod(String httpMethod, String url, String body) {
+    @Transactional(Transactional.TxType.NOT_SUPPORTED)
+    public CompletionStage<String> doHttpMethod(String httpMethod, String url, String body) {
 
-        return bufferedResult;
+        return bufferedResult.subscribeAsCompletionStage();
```

I don't think this should be needed though?

**Comment by geoand** [comment]
cc @FroMage

**Comment by cescoffier** [comment]
I need to check, but maybe we don't decorate the CompletableFuture (created by `subscribeAsCompletionStage()`) using context propagation. We have the feature, but I'm not sure we use it in this case. 

Note that for Uni, it's built-in.

**Comment by FroMage** [comment]
This is a bit weird to me, because if anything, the `Uni` version should fail more than the `CompletionStage` one.

What I assume is going wrong is that the TX is captured by the client via `Uni` and since the result at some point gets processed by another thread, the TX is resumed on the other thread, probably before it's suspended on the main worker thread. But then, this should fail in both methods.

We do have support for overriding the captured contexts in SR-CP for a while now, but I don't think Munity ever started using this, which would let you do:

```java
@WithThreadContext(cleared = ThreadContext.TRANSACTION)
public Uni<String> doHttpMethod(String httpMethod, String url, String body) {
...
}
```

@cescoffier @jponge do we have an issue for supporting the `@WithThreadContext` annotation in Mutiny?

**Comment by FroMage** [comment]
I didn't find one, so I created https://github.com/smallrye/smallrye-mutiny/issues/626

**Comment by bcluap** [comment]
> This is a bit weird to me, because if anything, the `Uni` version should fail more than the `CompletionStage` one.
> 
> What I assume is going wrong is that the TX is captured by the client via `Uni` and since the result at some point gets processed by another thread, the TX is resumed on the other thread, probably before it's suspended on the main worker thread. But then, this should fail in both methods.
> 
> We do have support for overriding the captured contexts in SR-CP for a while now, but I don't think Munity ever started using this, which would let you do:
> 
> ```java
> @WithThreadContext(cleared = ThreadContext.TRANSACTION)
> public Uni<String> doHttpMethod(String httpMethod, String url, String body) {
> ...
> }
> ```
> 
> @cescoffier @jponge do we have an issue for supporting the `@WithThreadContext` annotation in Mutiny?

Nice hypothesis... and a correct one at that.

So I added this to the test:
![image](https://user-images.githubusercontent.com/26746221/125940085-d21ac558-fe63-4336-b685-2d798a083a3f.png)

And it now passes. So its a race condition between emitting the item and passing the transaction back to the worker. I assume that on the Uni version, it passes the transaction and then emmitts the item, while on the completionstage it maybe does the order differently creating a race where if the calling code very quickly commits after getting the item, then the transaction has not been passed back off the eventloop in time.

**Comment by FroMage** [comment]
It's fixed upstream, so we should be able to close this when it's released.

**Comment by geoand** [comment]
Mutiny `1.0` is now included in Quarkus, so let's close this
