### ISSUE TITLE
Running a CLI app in quarkus dev mode (maven), does not re-run the app after a code change. (macOS

### ISSUE THREAD

**Issue by rivasdiaz** [quarkusio/quarkus#18719]
### Describe the bug

I run quarkus dev mode for a sample CLI application, and after updating the source code I press [Enter] on the terminal as suggested by the command line reference guide, and the cli app is not re-run.

OS: macOS Big Sur, version 11.3.1
Terminal: Default macOS Terminal, Version 2.11 (440)
Shell: zsh 5.8 (x86_64-apple-darwin20.0)
Quarkus: 2.0.1.Final

In addition to using `quarkus dev`, I tried directly running `./mvnw quarkus:dev`, running `bash` instead of `zsh`, generating the example with `gradle` instead of `maven`, and manually updating the generated `pom.xml` (on the maven version) to quarkus `2.0.2.Final`. All scenarios I tested worked the same way on my system.

### Expected behavior

Quarkus Dev Mode should have re-run my sample CLI app after pressing [Enter]

### Actual behavior

Only a blank line is printed on the terminal after pressing [Enter]

### How to Reproduce?

Steps to reproduce:

1. Make sure Quarkus CLI is fully updated: `jbang app install --fresh --force quarkus@quarkusio`
2. On a terminal, create a CLI app and run it in dev mode: `quarkus create cli -a mycli; cd mycli; quarkus dev`
3. On a separate terminal, update the sample code: `sed -i '' 's/, go go commando//g' mycli/src/main/java/org/acme/GreetingCommand.java`
4. Back on the first terminal, press [Enter]. This only shows an empty line. Quarkus Dev Tool never re-runs the app.

### Output of `uname -a` or `ver`

Darwin rrivas-mac 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

In one of the multiple times I tested, I got the following exception after stopping the dev mode with Ctl+C (many other times before and after I did not get such error, so it may or may not be related):

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
Caused by: java.io.IOError: java.io.IOException: Error executing 'stty icrnl echo icanon pendin dsusp ^Y lnext ^V': stty: tcsetattr: Input/output error

**Comment by rivasdiaz** [comment]
For reference, original Slack Overflow question:
https://stackoverflow.com/questions/68328956/quarkus-dev-mode-for-cli-how-to-restart-app/68343437
