### ISSUE TITLE
Mailer Template Error:  the return value of  TemplateProducer.template() is null

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#18736]
### Describe the bug

I use the following checked templates with quarkus mailer:
```
@CheckedTemplate
public class Templates {
  public static native MailTemplate.MailTemplateInstance success(String name);

  public static native MailTemplate.MailTemplateInstance error(String name);
}
```
I'm able to use those template in dev mode and in test. but when the jar is built, It's throwing an NPE.

### Expected behavior

The mail is templated correctly

### Actual behavior

```
java.lang.NullPointerException: Cannot invoke "io.quarkus.qute.Template.instance()" because the return value of "io.quarkus.qute.runtime.TemplateProducer$InjectableTemplateInstanceImpl.template()" is null
        at io.quarkus.qute.runtime.TemplateProducer$InjectableTemplateInstanceImpl.templateInstance(TemplateProducer.java:174)
        at io.quarkus.qute.runtime.TemplateProducer$InjectableTemplateInstanceImpl.renderAsync(TemplateProducer.java:155)
        at io.quarkus.mailer.runtime.MailTemplateInstanceImpl$1.get(MailTemplateInstanceImpl.java:122)
        at io.quarkus.mailer.runtime.MailTemplateInstanceImpl$1.get(MailTemplateInstanceImpl.java:117)
        at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$UniHandler.subscribe(UniAndCombination.java:203)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.run(UniAndCombination.java:71)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.access$000(UniAndCombination.java:53)
        at io.smallrye.mutiny.operators.uni.UniAndCombination.subscribe(UniAndCombination.java:50)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:54)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
        at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:42)
        at org.acme.services.MailerService.send(MailerService.java:26)
        at org.acme.services.MailerService_ClientProxy.send(MailerService_ClientProxy.zig:157)
        at org.acme.GreetingResource.hello(GreetingResource.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:481)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

### How to Reproduce?

Reproducer: https://github.com/rmanibus/quarkus_18736

1) mvn install
2) mvn quarkus:dev 
3) curl localhost:8080/hello -> template is working
4) mvn install && java -jar target/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
5) curl localhost:8080/hello -> an exception is thrown

### Output of `uname -a` or `ver`

windows

### Output of `java -version`

15.0.1

### Quarkus version or git rev

2.0.2.Final

**Comment by rmanibus** [comment]
It seems to work when I set the template as an inner class, but what is disturbing is the different behaviour in dev and in prod

**Comment by mkouba** [comment]
I've tried the attached reproducer and the build fails correctly on Linux because your project declares the templates in the `src/main/resources/Templates` directory, but it should be `src/main/resources/templates`; as a result no templates are found. When I fix the directory name to `templates` everything seems to work fine. The question is why the build did not fail on Windows...

**Comment by mkouba** [comment]
> I expect the build to fail if the folder name is not good !

Yes, it should fail and it fails on Linux...

**Comment by rmanibus** [comment]
is File::exist case insensitive on windows ?

**Comment by mkouba** [comment]
I don't think that we use `File#exists()` in the build steps. Anyway, could you pls try to enable the debug logging for qute so that we have a little bit more info? Just add the `quarkus.log.category."io.quarkus.qute.deployment".level=DEBUG` to your `application.properties`.

**Comment by mkouba** [comment]
So my guess is that `ApplicationArchive.getChildPath(String)` returns the path `src/main/resources/Templates` for the parameter `templates`, i.e. is case-insensitive on Windows. Then we collect all templates and build the relevant metadata. However, at runtime the [EngineProducer](https://github.com/quarkusio/quarkus/blob/main/extensions/qute/runtime/src/main/java/io/quarkus/qute/runtime/EngineProducer.java#L195) expects a template to be located in the `templates` directory and `java.lang.ClassLoader.getResource(String)` is case-sensitive.

**Comment by rmanibus** [comment]
I think you are right:
```
2021-07-18 09:20:40,648 DEBUG [io.qua.qut.run.EngineProducer] (main) Added generated value resolver: io.quarkus.qute.runtime.extensions.MapTemplateExtensions_Extension_ValueResolver_get_bc0571c57a00283edd7750dce31b35b7894dab35
2021-07-18 09:20:40,651 DEBUG [io.qua.qut.run.EngineProducer] (main) Locate template for templates/error.html
2021-07-18 09:20:40,667 DEBUG [io.qua.qut.run.EngineProducer] (main) Locate template for templates/error.txt
2021-07-18 09:20:40,668 DEBUG [io.qua.qut.run.EngineProducer] (main) Locate template for templates/success.html
2021-07-18 09:20:40,669 DEBUG [io.qua.qut.run.EngineProducer] (main) Locate template for templates/success.txt
2021-07-18 09:20:40,798 INFO  [io.quarkus] (main) Quarkus 2.0.2.Final on JVM started in 3.105s. Listening on: http://localhost:8081
```

**Comment by rmanibus** [comment]
Thanks a lot !
