### ISSUE TITLE
java.lang.ClassCastException: class io.smallrye.reactive.messaging.wiring.Wiring$SubscriberMediatorComponent

### ISSUE THREAD

**Issue by mgonzaga1990** [quarkusio/quarkus#18745]
### Describe the bug

Error : 

```
java.lang.ClassCastException: class io.smallrye.reactive.messaging.wiring.Wiring$SubscriberMediatorComponent cannot be cast to class io.smallrye.reactive.messaging.wiring.Wiring$PublishingComponent (io.smallrye.reactive.messaging.wiring.Wiring$SubscriberMediatorComponent and io.smallrye.reactive.messaging.wiring.Wiring$PublishingComponent are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @62146671)
at io.smallrye.reactive.messaging.wiring.Graph.lambda$new$7(Graph.java:56)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.smallrye.reactive.messaging.wiring.Graph.<init>(Graph.java:57)
	at io.smallrye.reactive.messaging.wiring.Wiring.resolve(Wiring.java:154)
	at io.smallrye.reactive.messaging.wiring.Wiring_Subclass.resolve$$superforward1(Wiring_Subclass.zig:302)
	at io.smallrye.reactive.messaging.wiring.Wiring_Subclass$$function$$2.apply(Wiring_Subclass$$function$$2.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.smallrye.reactive.messaging.wiring.Wiring_Subclass.resolve(Wiring_Subclass.zig:533)
	at io.smallrye.reactive.messaging.wiring.Wiring_ClientProxy.resolve(Wiring_ClientProxy.zig:184)
	at io.smallrye.reactive.messaging.extension.MediatorManager.start(MediatorManager.java:192)
	at io.smallrye.reactive.messaging.extension.MediatorManager_Subclass.start$$superforward1(MediatorManager_Subclass.zig:690)
	at io.smallrye.reactive.messaging.extension.MediatorManager_Subclass$$function$$14.apply(MediatorManager_Subclass$$function$$14.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.smallrye.reactive.messaging.extension.MediatorManager_Subclass.start(MediatorManager_Subclass.zig:1987)
	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.start(MediatorManager_ClientProxy.zig:220)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:41)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass.onApplicationStart$$superforward1(SmallRyeReactiveMessagingLifecycle_Subclass.zig:130)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass$$function$$1.apply(SmallRyeReactiveMessagingLifecycle_Subclass$$function$$1.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass.onApplicationStart(SmallRyeReactiveMessagingLifecycle_Subclass.zig:213)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:111)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:300)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:282)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:799)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:98)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
I tried version 2.0.0, 2.0.1 and 2.0.2

The same error happens in amqp and http connector aswell.
I Attached the reproducer.

[reproducer.zip](https://github.com/quarkusio/quarkus/files/6830889/reproducer.zip)

**Comment by cescoffier** [comment]
Kogito is registering "channels" dynamically which is something not really expected (at least with Reactive Messaging 3.x as we verify the graph at startup time). But it should still work. 
However, the registration does not seem to provide all the metadata reactive messaging needs. 

I guess the problem comes from either:

* https://github.com/kiegroup/kogito-runtimes/blob/07bd4c9f75c5f3ef32e8e5772737204caaf90999/addons/quarkus/cloudevents/multi/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/QuarkusMultiCloudEventPublisher.java#L118-L123 - which instead of registering the channels push new "configuration"
* https://github.com/kiegroup/kogito-runtimes/blob/07bd4c9f75c5f3ef32e8e5772737204caaf90999/addons/quarkus/cloudevents/multi/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/QuarkusMultiCloudEventEmitter.java#L91

Both places uses reactive messaging internals which would corrupt the graph. Registration must be done though the ChannelRegistry and not in the internal classes.

**Comment by mgonzaga1990** [comment]
Thanks for your reply Clement. May this is something I need to raise to the
kogito team.

**Comment by cescoffier** [comment]
Yes, this is something that would need to be updated in kogito. I can be more defensive in reactive messaging, but it will just reject the component (which is not what we want here)

**Comment by geoand** [comment]
cc @evacchi

**Comment by evacchi** [comment]
have we addressed this already on `main`+2.1 ? @ricardozanini also @radtriste @cristianonicolai  -- pinging you since you did the update this time, have you noticed some related failure?

**Comment by radtriste** [comment]
@Edoardo Vacchi ***@***.***> PRs for 2.1 are still ongoing:
- https://github.com/kiegroup/kogito-runtimes/pull/1465
- https://github.com/kiegroup/optaplanner/pull/1451

@Cristiano Nicolai ***@***.***>  is going to solve the apps part
AFAIK

Tristan Radisson

Principal Software Quality Engineer

Business Automation Cloud

Red Hat France <https://www.redhat.com/>

***@***.***
+33 (1) 41912322
<https://www.redhat.com/>

**Comment by fjtirado** [comment]
Hi, This should be already fixed in main branch. 
https://issues.redhat.com/browse/KOGITO-5459
In any case, multi approach was substantially changed with 
https://issues.redhat.com/browse/KOGITO-5252

**Comment by ricardozanini** [comment]
Thanks @fjtirado

**Comment by cescoffier** [comment]
@fjtirado should we close this issue as both tickets have been marked as resolved?

**Comment by cescoffier** [comment]
Ok - closing as it's kogito related.
Please re-open if the issue remains.

**Comment by evacchi** [comment]
@cescoffier : @fjtirado is confirming this can be closed. Thanks for the ping
