### ISSUE TITLE
ClassCastException for AVRO generated sources when running in dev mode

### ISSUE THREAD

**Issue by maxhov** [quarkusio/quarkus#18776]
### Describe the bug

I am trying out Quarkus and following the guide [Quarkus - Using Apache Kafka with Schema Registry and Avro ](https://quarkus.io/guides/kafka-schema-registry-avro). 

When the application is first started in dev mode everything works as expected. The created Movie resources are sent to Kafka and consequently available via the consumer. However, when a change is made and the livereload kicks in, the class are no longer available in the QuarkusClassLoader and the following stack trace is observed:

```
java.lang.ClassCastException: class org.acme.kafka.quarkus.Movie cannot be cast to class org.acme.kafka.quarkus.Movie (org.acme.kafka.quarkus.Movie is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @77e80a5e; org.acme.kafka.quarkus.Movie is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6d36a933)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:42)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.operators.multi.multicast.MultiPublishOp$PublishSubscriber.drain(MultiPublishOp.java:475)
        at io.smallrye.mutiny.operators.multi.multicast.MultiPublishOp$PublishSubscriber.onItem(MultiPublishOp.java:182)
        at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.tryEmit(MultiFlatMapOp.java:228)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onItem(MultiFlatMapOp.java:595)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onItem(UniToMultiPublisher.java:77)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:56)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:99)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:54)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2321)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forward(UniCreateFromCompletionStage.java:51)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:35)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.request(UniToMultiPublisher.java:61)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onSubscribe(MultiFlatMapOp.java:589)
        at io.smallrye.mutiny.converters.uni.UniToMultiPublisher.subscribe(UniToMultiPublisher.java:26)
        at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:156)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:191)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:98)
        at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
        at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:83)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:98)
        at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
        at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:83)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.tryEmit(MultiFlatMapOp.java:228)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onItem(MultiFlatMapOp.java:595)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onItem(UniToMultiPublisher.java:77)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
        at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
        at io.smallrye.mutiny.groups.UniOnNull.lambda$failWith$1(UniOnNull.java:43)
        at io.smallrye.context.impl.wrappers.SlowContextualBiConsumer.accept(SlowContextualBiConsumer.java:21)
        at io.smallrye.mutiny.groups.UniOnItem.lambda$transformToUni$4(UniOnItem.java:169)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143)
        at io.quarkus.smallrye.reactivemessaging.runtime.devmode.DevModeSupportConnectorFactoryInterceptor.lambda$intercept$0(DevModeSupportConnectorFactoryInterceptor.java:42)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143)
        at io.quarkus.smallrye.reactivemessaging.runtime.devmode.ReactiveMessagingHotReplacementSetup$OnMessage$1.run(ReactiveMessagingHotReplacementSetup.java:44)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

Observing the issue when runnning from the command line with `mvn quarkus:dev` as well as running from IntelliJ 2021.1.3.

### Expected behavior

AVRO generated classes are available after livereload.

### Actual behavior

Not sure, but my initial thoughts are that AVRO generated classes are no longer available on the classpath due to ClassLoader switching?

### How to Reproduce?

Reproduce:
1. Follow the guide [Quarkus - Using Apache Kafka with Schema Registry and Avro ](https://quarkus.io/guides/kafka-schema-registry-avro)
2. Start the application in dev mode
3. Observe that the application works as expected
3. Make a change in the source code with the consumer curl request still open `curl -N http://localhost:8080/consumed-movies`
4. Create a new resouce and observe that there are no new events being sent from the consumer
5. Restart the consumer curl and observe the stack trace

### Output of `uname -a` or `ver`

Darwin Macbook 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`

Tried Java 11, 15 and 16

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by gsmet** [comment]
@michalszynkiewicz @ozangunalp @cescoffier could one of you investigate this one? There's a good chance we might need Stuart here but let's at least investigate a bit what's going on and if it's still an issue with current main.

**Comment by ozangunalp** [comment]
I can reproduce this with the current main on Java 11.

**Comment by michalszynkiewicz** [comment]
I'm a bit surprised the SSE endpoint stays alive (and stuck) on reload...

**Comment by michalszynkiewicz** [comment]
I see the SSE endpoint, after restart, still uses the old classloader. 
The endpoint to feed movies uses the new classloader.

I think that's the issue. I will try to dig into it a bit further.

**Comment by michalszynkiewicz** [comment]
I see this behavior (keeping the old/pre-reload classloaders on SSE endpoints if the call is in progress when the app is reloaded) also without kafka. I don't know enough about the server part of RestEasy Reactive to fix it quickly, I think.

**Comment by cescoffier** [comment]
A workaround could be to turn off the hot reload using instrumentation. 

But during the hot reload, it should cut the SSE connection. It's up to the client side to reconnect.

**Comment by ozangunalp** [comment]
I think it is off by default, and when I activate it using `quarkus.live-reload.instrumentation=true` I don't have the issue anymore.

**Comment by michalszynkiewicz** [comment]
> A workaround could be to turn off the hot reload using instrumentation.
> 
> But during the hot reload, it should cut the SSE connection. It's up to the client side to reconnect.

Yes, that's what we do with gRPC streams.

@geoand @FroMage @stuartwdouglas can one of you give some pointers on implementing this or take a look at it himself?

**Comment by geoand** [comment]
Pointers for which part exactly?

**Comment by michalszynkiewicz** [comment]
good question :D It seems we miss closing an SSE connection on the app reload.
I don't know how it's implemented but we may need some way to gather such connections when in dev mode

**Comment by geoand** [comment]
That's one for @FroMage

**Comment by FroMage** [comment]
So we have to keep track of all the open connections when in DEV mode? This sort of thing doesn't appear to be limited to SSE though: it can happen with any REST call that is streaming.

What is the producer of the SSE feed? Is it Reactive Messaging? Shouldn't it be responsible for cutting the emission? Or is it the case that it can keep the `Multi` open when hot-reloading and it's only the SSE consumer that's having issues?

@michalszynkiewicz can you point me to where you keep track of gRPC streams in DEV mode for that, please?

**Comment by stuartwdouglas** [comment]
The linked PR should fix both issues
