### ISSUE TITLE
Native Image - Windows 10 - InvalidPathException: Illegal char <:> at index 13: -Xmx2048m -XX:MaxPermSize=512m\cl.exe

### ISSUE THREAD

**Issue by postullat** [quarkusio/quarkus#18787]
### Describe the bug

I've got `InvalidPathException: Illegal char <:> at index 13: -Xmx2048m -XX:MaxPermSize=512m\cl.exe` when tried to run a simple hello world example with native-image command on Windows 10

Environment:
1. Windows 10 Pro, x64
2. java version "11.0.11" 2021-04-20 LTS
3. graalvm-ce-java11-21.1.0
4. JAVA_HOME is in a Path
5. GRAALVM_HOME is in a Path

### Expected behavior

native image should be created

### Actual behavior

`C:\Users\Dell>native-image hello
[hello:7300]    classlist:  49,579.32 ms,  0.91 GB
[hello:7300]        setup:   3,504.13 ms,  0.91 GB
Fatal error:java.nio.file.InvalidPathException: Illegal char <:> at index 13: -Xmx2048m -XX:MaxPermSize=512m\cl.exe
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.lambda$lookupSearchPath$1(CCompilerInvoker.java:485)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.lookupSearchPath(CCompilerInvoker.java:487)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.getCCompilerPath(CCompilerInvoker.java:497)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.getCCompilerInfo(CCompilerInvoker.java:345)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.<init>(CCompilerInvoker.java:68)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker$WindowsCCompilerInvoker.<init>(CCompilerInvoker.java:108)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.create(CCompilerInvoker.java:82)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:902)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:580)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1`

### How to Reproduce?

Code wich I try to run with native-image
public class hello {
	public static void main(String[] args) {
		
		System.out.println("Hello world");
	}
}

Steps:
1. javac hello.java
2. java hello -> output "Hello world"
3. native-image hello

### Output of `java -version`

java version "11.0.11" 2021-04-20 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)

### GraalVM version (if different from Java)

graalvm-ce-java11-21.1.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

native-image

### Additional information

I get the same error when trying to run quarkus project with maven using this command `mvn package -Pnative`
Maven version is 3.8.1

**Comment by gsmet** [comment]
I'm pretty sure it's an issue with your environment. I don't know from where `-Xmx2048m -XX:MaxPermSize=512m` is coming but it should be a path. Didn't you mix JAVA_OPTS and JAVA_HOME or something similar?

**Comment by geoand** [comment]
Closing because we have not received necessary user input.
Feel free to reopen or comment if you have more information for us
