### ISSUE TITLE
Quarkus hot reload fails on absent test folder and/or test class in Continuous Testing mode 

### ISSUE THREAD

**Issue by tbvl** [quarkusio/quarkus#18796]
### Describe the bug

In a multi Maven module project where a dependee project lacks the test/java folder and/or at least one test class the hot code reload stops working in the Test Runner Thread after throwing an exception, when running in Continuous Testing mode:

![quarkus_NoSuchElementException](https://user-images.githubusercontent.com/1332978/126122662-a2a16491-6589-4ad7-9d19-cf5aac1b601b.jpg)

Tests are executing fine when just running using e.g.: `mvn test`. 

### Expected behavior

If a test folder and at least one test class are in fact required in all dependee projects / modules for Continuous Testing to work (I could not find this requirement documented anywhere) I would expect a warning and possible that the module is ignored for hot code reload.

### Actual behavior

When running the tests the first time (hitting r after Quakus dev mode started up) two exceptions are thrown after a little time:

```
2021-07-19 09:30:52,299 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, resteasy-jackson, smallrye-context-propagation]
Exception in thread "Test Compile Timer"
                                        java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:141)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.lambda$periodicTestCompile$1(RuntimeUpdatesProcessor.java:250)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.checkForFileChange(RuntimeUpdatesProcessor.java:763)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.periodicTestCompile(RuntimeUpdatesProcessor.java:250)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor$3.run(RuntimeUpdatesProcessor.java:236)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
2021-07-19 09:31:06,420 ERROR [io.qua.test] (Test runner thread) Internal error running tests: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:141)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.lambda$setWatchedFilePaths$12(RuntimeUpdatesProcessor.java:948)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.setWatchedFilePathsInternal(RuntimeUpdatesProcessor.java:961)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.setWatchedFilePaths(RuntimeUpdatesProcessor.java:948)
        at io.quarkus.deployment.dev.testing.TestRunner.runInternal(TestRunner.java:252)
        at io.quarkus.deployment.dev.testing.TestRunner$1.run(TestRunner.java:126)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

Tests are still run, but hot code replacement no longer works ie. changes to application and test code is not discovered by the Quarkus runtime. 

### How to Reproduce?

Using the attached reproducer project. 
[quarkus_ct_issue_clean.zip](https://github.com/quarkusio/quarkus/files/6839326/quarkus_ct_issue_clean.zip)

Maven structure:
- quarkus_ct_issue (root pom)
  - with_test_folder (vanilla java)
  - without_test_folder (vanilla java)
  - service (Quarkus RestEasy Service project)

_service_ depends on _with_test_folder_ and _without_test_folder_

Service project was created using the example in https://quarkus.io/guides/rest-json.

Reproduce:
1. Run `./mvnw install` in root folder
2. Cd to service folder
3. Run `./mvnw compile quarkus:dev`
4. Hit r when runtime is ready.
5. Exception will be thrown.

### Output of `uname -a` or `ver`

OS Name: Microsoft Windows 10 Enterprise OS Version: 10.0.18363 N/A Build 18363

### Output of `java -version`

openjdk version "15.0.2" 2021-01-19

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by tbvl** [comment]
@stuartwdouglas Thanks for the quick turnaround and fix! I will get it tested one of days.
