### ISSUE TITLE
Include OIDC provider in health

### ISSUE THREAD

**Issue by albert0815** [quarkusio/quarkus#18802]
### Description

I think it would be useful if the OIDC provider (e.g. keycloak) could be integrated in the health status out of the box (similar to e.g. mongo or kafka).

**Comment by albert0815** [comment]
Hi @jmartisk, @pedroigor, @sberyozkin, @xstefank,

Can you please let me know whether this is something which you would consider in future? We need Keycloak being checked as part of the healthiness of the services. It seems after a restart of Keycloak Quarkus is not able to retrieve any resources any more, most probably because some tokens are cached but not valid any more after a Keycloak restart. This can be solved by restarting the Quarkus service. This should be done automatically based on a health check.

Related stack trace:

```
2021-09-24T12:02:32+0000   ERROR [or.ke.ad.au.PolicyEnforcer] (executor-thread-1928) Could not lazy load resource with path [/data-service/q/metrics] from server: java.lang.RuntimeException: Could not find resource
        at org.keycloak.authorization.client.util.Throwables.retryAndWrapExceptionIfNecessary(Throwables.java:91)
        at org.keycloak.authorization.client.resource.ProtectedResource.find(ProtectedResource.java:232)
        at org.keycloak.authorization.client.resource.ProtectedResource.findByMatchingUri(ProtectedResource.java:291)
        at org.keycloak.adapters.authorization.PolicyEnforcer$PathConfigMatcher.matches(PolicyEnforcer.java:272)
        at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:47)
        at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:28)
        at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$1$1$1.run(HttpAuthorizer.java:72)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 400 / Bad Request / Response from server: {"error":"invalid_grant","error_description":"Session not active"}
        at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:95)
        at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
        at org.keycloak.authorization.client.util.TokenCallable.refreshToken(TokenCallable.java:149)
        at org.keycloak.authorization.client.util.TokenCallable.tryRefreshToken(TokenCallable.java:105)
        at org.keycloak.authorization.client.util.TokenCallable.call(TokenCallable.java:81)
        at org.keycloak.authorization.client.resource.ProtectedResource.createFindRequest(ProtectedResource.java:296)
        at org.keycloak.authorization.client.resource.ProtectedResource.access$300(ProtectedResource.java:38)
        at org.keycloak.authorization.client.resource.ProtectedResource$5.call(ProtectedResource.java:225)
        at org.keycloak.authorization.client.resource.ProtectedResource$5.call(ProtectedResource.java:222)
        at org.keycloak.authorization.client.resource.ProtectedResource.find(ProtectedResource.java:230)
        ... 12 more
```

Thanks
Dirk

**Comment by xstefank** [comment]
@albert0815 you're probably looking for https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-health/spi/src/main/java/io/quarkus/smallrye/health/deployment/spi/HealthBuildItem.java which you can use in your extension to produce extension health checks.

**Comment by albert0815** [comment]
Yes true, but the extension is provided by Quarkus, so my question is whether you would integrate that in e.g. quarkus-keycloak-authorization.

**Comment by xstefank** [comment]
@albert0815 ah sorry, I thought that you want to implement it yourself. Well, you only need `HealthCheck` implementation then I can help you with integration. But I'm not familiar with keycloak enough to implement this health check myself. Do you know who could provide this health check implementation?

**Comment by sberyozkin** [comment]
It was fixed in latest Quarkus
