### ISSUE TITLE
Package private Quarkus class could not be used in tests

### ISSUE THREAD

**Issue by 01epa** [quarkusio/quarkus#18817]
### Describe the bug

We have a large application based on quarkus. We wrote a new Quarkus extension (added quarkus oidc extension as dependency). We extended a lot of security Quarkus classes. everything was fine. Now we decided to upgrade quaruks to 2.0.2 version. And we see that some tests started failing. 
The special thing of these tests that they are testing extended protected Quarkus security classes like io.quarkus.oidc.runtime.TenantConfigContext.

I prepared a small test to show an error. Please find it in https://github.com/01epa/quarkus-packeges-test-failing

### Expected behavior

All tests are passed and no IllegalAccessError happened

### Actual behavior

There is an exception in logs:
`2021-07-19 17:09:59,389 WARN  [io.qua.arc.pro.BeanArchives] (build-61) Failed to index [Ljava.lang.Object;: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: TEST
2021-07-19 17:10:00,451 INFO  [io.quarkus] (main) Quarkus 2.0.2.Final on JVM started in 0.711s. Listening on: http://localhost:9315
2021-07-19 17:10:00,452 INFO  [io.quarkus] (main) Profile test activated. 
2021-07-19 17:10:00,452 INFO  [io.quarkus] (main) Installed features: [authentication, cdi, oidc, security, smallrye-context-propagation]

java.lang.IllegalAccessError: failed to access class io.quarkus.oidc.runtime.TenantConfigContext from class io.quarkus.oidc.runtime.ExtendedOidcTest (io.quarkus.oidc.runtime.TenantConfigContext is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @5632f29c; io.quarkus.oidc.runtime.ExtendedOidcTest is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @91ed0ed)

	at io.quarkus.oidc.runtime.ExtendedOidcTest.setUp(ExtendedOidcTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.QuarkusUnitTest.runExtensionMethod(QuarkusUnitTest.java:357)
	at io.quarkus.test.QuarkusUnitTest.interceptBeforeEachMethod(QuarkusUnitTest.java:297)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:490)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$19(ClassBasedTestDescriptor.java:475)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$2(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:195)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:195)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:164)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

2021-07-19 17:10:00,736 INFO  [io.quarkus] (main) Quarkus stopped in 0.054s`

### How to Reproduce?

Download the project https://github.com/01epa/quarkus-packeges-test-failing
type `mvn clean install` or run io.quarkus.oidc.runtime.ExtendedOidcTest test from IDE.

### Output of `uname -a` or `ver`

MSYS_NT-10.0 wsmnn-385 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys

### Output of `java -version`

java version "11.0.5" 2019-10-15 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)

### Quarkus version or git rev

2.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\Maven\bin\.. Java version: 11.0.5, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.5 Default locale: en_US, platform encoding: Cp1251 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

Btw, If i removed 
`    @RegisterExtension
    static QuarkusUnitTest runner = new QuarkusUnitTest()
            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
                    .addAsResource("application.properties"));`

the test is still can be executed by maven or Idea and the error disappeared. I guess it is due to that quarkus loader is not working in this case

**Comment by stuartwdouglas** [comment]
You can work around this for now with `quarkus.test.flat-class-path=true`, but in general split packages are not really supported, and won't work in devmode.

**Comment by 01epa** [comment]
Thanks. It helps. Can ypou poiny me to a documentation what does this flag do?

Also it would be great if you explain why this happened. Is it a bug or expected behaviour?

Also if I moved everything to one package it does not help. I don't understand how multiple packages relates to the issue...

Thanks in advance.

**Comment by stuartwdouglas** [comment]
The downside is that you loose support for continuous testing (same way this won't work in devmode).

Split packages are when you have two classes in the same package but in different jars. This will compile but if they are loaded by different ClassLoaders then you will get an IllegalAccessError on package private members. It's generally a bad idea and causes all kinds of problems. This is expected behavior and not a bug.

Why do you need access to these package private classes anyway?

**Comment by 01epa** [comment]
Ok, I understand split packages behaviour. Thanks for explanation.
I split packages since I implemented my own io.quarkus.security.identity.IdentityProvider but io.quarkus.oidc.runtime.TenantConfigContext (which is needed for its implementation) is package private. I don't know why. Probably it should be changed to public. I saw at least one additional class which has such access as well. it is io.quarkus.oidc.runtime.AbstractOidcAuthenticationMechanism.

Can we ask some one to check if that correct or not?

**Comment by gsmet** [comment]
I think you should prepare a small project showing what you're doing with these classes exactly.

This way, we could decide if the APIs need to evolve with a proper use case.

**Comment by 01epa** [comment]
I can't share my code since it is a proprietary. I will try to explain. We have several quarkus microservices which may be used with different security configurations. The most major one is to use/accept tokens from Keycloak identity-provider. On keycloak there are a lot of users/clients on different realms. Thus we have a dynamic tenant resolver for that.
The second configuration is vault. There is a case when vault jwt token comes to microservice. 

Both configurations are working in runtime simultaneously. Services must validate tokens using public keys (jwks). 

So io.quarkus.oidc.runtime.TenantConfigContext (package private class) is used everywhere in our code. For example it is used to verify token
`            return Uni.createFrom().item(tenantConfigContext .provider.verifyJwtToken(tokenString));
`
or to get oidc config 
`                                    tenantConfigContext.oidcConfig
`

**Comment by 01epa** [comment]
Actually what I want is to have access to these classes and remove the workaround `quarkus.test.flat-class-path=true` and have a support of continius testing.

**Comment by stuartwdouglas** [comment]
So you want to be able to verify a JWT token from the currently selected tenant? 
We could probably supply an API just for that. The problem with just marking this class public is that we don't consider what you are doing supported, so we may break it in future with no warning. 

If we can nail down the use cases that you need this class for we can possibly provide a documented API for it. 

cc @sberyozkin

**Comment by geoand** [comment]
Is there still something we want to do with this one?
