### ISSUE TITLE
Regression: Native fails with `java.lang.ClassNotFoundException: java.lang.Integer`

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#18814]
### Describe the bug

I have a pretty basic scenario that uses the `quarkus-config-yaml` Quarkus extension and it fails after build the Native image with:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.qe.configmapping.NativeConfigMappingResourceIT
Executing [/home/jcarvaja/sources/beefy-scenarios/022-quarkus-properties-config-all/target/022-quarkus-properties-config-all-1.0.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dquarkus.http.ssl-port=8444, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=/home/jcarvaja/sources/beefy-scenarios/022-quarkus-properties-config-all/target/quarkus.log, -Dquarkus.log.file.enable=true]
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-07-19 15:38:46,717 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.ClassNotFoundException: java.lang.Integer
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:64)
	at java.lang.Class.forName(DynamicHub.java:1308)
	at io.quarkus.arc.runtime.ConfigRecorder.load(ConfigRecorder.java:102)
	at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:48)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties1249763973.deploy_0(ConfigBuildStep$validateConfigProperties1249763973.zig:282)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties1249763973.deploy(ConfigBuildStep$validateConfigProperties1249763973.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:535)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)

Application was not started: 2021-07-19 15:38:46,717 localhost NativeImageGeneratorRunner$JDK9Plus[24] ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.ClassNotFoundException: java.lang.Integer
```

I don't think this issue is related to the `quarkus-config-yaml` extension as I saw the same error using the reactive Kafka extension. 

Doing exactly the same using 2.0.2.Final works fine, but not with 2.1.0.CR1 or 999-SNAPSHOT.

### How to Reproduce?

1. git clone https://github.com/quarkus-qe/beefy-scenarios
2. cd beefy-scenarios/022-quarkus-properties-config-all
3. mvn clean verify -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=4g

All the tests should pass, but the Native tests are failing.

**Comment by gsmet** [comment]
Good catch @Sgitario , just in time for the Final!
