### ISSUE TITLE
Qute: access the context of nested tag

### ISSUE THREAD

**Issue by thienldd** [quarkusio/quarkus#18886]
### Description

Let's say we have a user-defined tag:

itemDetail.html
`{#set item=itemMap.get(itemId)}
{/set}`

Is it possible to access the "item" variable in itemDetail.html from another template?
So we can have a dynamic way to render the item detail

itemList.html
`{#itemDetail itemId='1'}
{item.quantity} {item.unit}
{/itemDetail}`

itemList2.html
`{#itemDetail itemId='2'}
{item.quantity} ({item.unit})
{/itemDetail}`

**Comment by mkouba** [comment]
No, this is currently not possible because the `nested-content` is actually a parameter that is evaluated _before_ the user-defined tag is executed. In fact, `{#itemDetail itemId='1'}foo{/itemDetail}` could be rewritten as `{#itemDetail itemId='1' nested-content='foo'}`.

In theory, you can pass the nested content as a string and use the [eval section](https://quarkus.io/guides/qute-reference#eval-section), i.e. `itemDetail.html`:
```
{#set item=itemMap.get(itemId)} 
  {#eval myNestedContent item=item /}
{/set}
```
and `itemList.html`:
```
{#itemDetail itemId='1' myNestedContent="{item.quantity} {item.unit}" /}
```
It's not ideal but it should work ;-).

**Comment by thienldd** [comment]
Thanks @mkouba. I'll give it a try.

**Comment by mkouba** [comment]
@thienldd Have you tried the `{#eval}` section? Should we close this one?

**Comment by thienldd** [comment]
@mkouba Unfortunately it showed me the error:
`Caused by: io.quarkus.qute.TemplateException: Parser error in template [itemDetail.html] on line 2: no section helper found for {#eval myNestedContent item=item /}
	at io.quarkus.qute.Parser.parserError(Parser.java:525)
	at io.quarkus.qute.Parser.flushTag(Parser.java:434)
	at io.quarkus.qute.Parser.tag(Parser.java:301)
	at io.quarkus.qute.Parser.processCharacter(Parser.java:208)
	at io.quarkus.qute.Parser.parse(Parser.java:135)
	at io.quarkus.qute.EngineImpl.load(EngineImpl.java:125)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.quarkus.qute.EngineImpl.getTemplate(EngineImpl.java:103)
	at io.quarkus.qute.runtime.EngineProducer.<init>(EngineProducer.java:141)
	at io.quarkus.qute.runtime.EngineProducer_Bean.create(EngineProducer_Bean.zig:618)
	at io.quarkus.qute.runtime.EngineProducer_Bean.create(EngineProducer_Bean.zig:633)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.qute.runtime.EngineProducer_Bean.get(EngineProducer_Bean.zig:665)
	at io.quarkus.qute.runtime.EngineProducer_Bean.get(EngineProducer_Bean.zig:681)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:430)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:443)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:275)
	at io.quarkus.qute.runtime.EngineProducer_Observer_Synthetic_5ca7449e3ab1631e7e8ed910338051c00d29a79b.notify(EngineProducer_Observer_Synthetic_5ca7449e3ab1631e7e8ed910338051c00d29a79b.zig:107)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:268)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:939)
	... 46 more

`
What I did:
1. Put itemDetail.html in src/main/java/resources/templates
2. Register a UserTagSectionHelper for itemDetail (using @Observes EngineBuilder)
3. Render itemList content with data is the itemMap (Map<String, Object>)

**Comment by mkouba** [comment]
@thienldd Can you share a reproducer? I've tried to create a test and it worked: https://github.com/quarkusio/quarkus/pull/19295/files

**Comment by thienldd** [comment]
@mkouba Please take a look at my repo
https://github.com/thienldd/quarkus-qute-samples/blob/master/src/test/java/com/github/thienldd/EvalTest.java

Note: I'm using Quarkus version 1.13.3. I tried with new project generated with code.quarkus.io and your sample worked fine.

**Comment by mkouba** [comment]
@thienldd Ah, well the `{#eval}` section was introduced in 2.0.0.Alpha3.

**Comment by thienldd** [comment]
Thanks @mkouba for your help. I close this issue 'cos your sample works for Quarkus 2.x and my project will be upgraded to 2.x in the short time.

**Comment by mkouba** [comment]
> Thanks @mkouba for your help. I close this issue 'cos your sample works for Quarkus 2.x and my project will be upgraded to 2.x in the short time.

+1. I will merge the PR with the test once the CI is green.
