### ISSUE TITLE
Quarkus Jib is unable to create container image: 'docker load' command failed with error (Windows)

### ISSUE THREAD

**Issue by JapuDCret** [quarkusio/quarkus#18986]
### Describe the bug

After starting my Windows laptop I was unable to build a jib image.

The output was:
```bash
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ my-service ---
[INFO] Building jar: C:\git\my-service\my-service\target\my-service-0.1.0-SNAPSHOT.jar
[INFO]
[INFO] --- quarkus-maven-plugin:1.12.2.Final:build (default) @ my-service ---
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
[WARNING] [io.quarkus.kubernetes.deployment.KubernetesDeployer] A Kubernetes deployment was requested, but the container image to be built will not be pushed to any registry because "quarkus.container-image.registry" has not been set. The Kubernetes deployment will only work properly if the cluster is using the local Docker daemon. For that reason 'ImagePullPolicy' is being force-set to 'IfNotPresent'.
[INFO] [io.quarkus.flyway.FlywayProcessor] Adding application migrations in path '/C:/git/my-service/my-service/target/classes/db/migration/' using protocol 'file'
[INFO] [org.hibernate.Version] HHH000412: Hibernate ORM core version 5.4.28.Final
[INFO] Checking for existing resources in: C:\git\my-service\my-service\src\main\kubernetes.
[WARNING] [io.quarkus.micrometer.deployment.binder.mpmetrics.MicroprofileMetricsProcessor] This application uses the MP Metrics API. The micrometer extension currently provides a compatibility layer that supports the MP Metrics API, but metric names and recorded values will be different. Note that the MP Metrics compatibility layer will move to a different extension in the future.
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: C:\git\my-service\my-service\target\my-service-0.1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Starting container image build
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] Base image 'fabric8/java-alpine-openjdk11-jre' does not use a specific image digest - build may not be reproducible
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] The base image requires auth. Trying again for fabric8/java-alpine-openjdk11-jre...
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=INFO, message=trying docker-credential-desktop for registry-1.docker.io]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=WARN, message=The credential helper (docker-credential-desktop) has nothing for server URL: registry-1.docker.io

Got output:

credentials not found in native keychain
]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=INFO, message=trying docker-credential-desktop for registry.hub.docker.com]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=WARN, message=The credential helper (docker-credential-desktop) has nothing for server URL: registry.hub.docker.com

Got output:

credentials not found in native keychain
]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=INFO, message=trying docker-credential-desktop for index.docker.io]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] LogEvent [level=LIFECYCLE, message=Using credentials from Docker config (C:\Users\<username>\.docker\config.json) for fabric8/java-alpine-openjdk11-jre]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Using base image with digest: sha256:b459cc59d6c7ddc9fd52f981fc4c187f44a401f2433a1b4110810d2dd9e98a07
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Container entrypoint set to [java, -Djava.util.logging.manager=org.jboss.logmanager.LogManager, -cp, /app/resources:/app/classes:/app/libs/*, io.quarkus.runner.GeneratedMain]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Parent - MyService 0.1.0-SNAPSHOT:
[INFO]
[INFO] MyService Service .................. FAILURE [01:46 min]
[INFO] MyService Documentation ............ SKIPPED
[INFO] Parent - MyService .. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:46 min
[INFO] Finished at: 2021-07-26T10:38:54+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.12.2.Final:build (default) on project my-service: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
[ERROR]         at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:191)
[ERROR]         at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:137)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:832)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.util.concurrent.ExecutionException: java.io.IOException: 'docker load' command failed with error: Error processing tar file(exit status 1): unexpected EOF
[ERROR]
[ERROR]         at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
[ERROR]         at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
[ERROR]         at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
[ERROR]         at com.google.cloud.tools.jib.builder.steps.StepsRunner.run(StepsRunner.java:219)
[ERROR]         at com.google.cloud.tools.jib.api.Containerizer.run(Containerizer.java:366)
[ERROR]         at com.google.cloud.tools.jib.api.JibContainerBuilder.containerize(JibContainerBuilder.java:598)
[ERROR]         at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:184)
[ERROR]         ... 11 more
[ERROR] Caused by: java.io.IOException: 'docker load' command failed with error: Error processing tar file(exit status 1): unexpected EOF
[ERROR]
[ERROR]         at com.google.cloud.tools.jib.docker.DockerClient.load(DockerClient.java:211)
[ERROR]         at com.google.cloud.tools.jib.builder.steps.LoadDockerStep.call(LoadDockerStep.java:74)
[ERROR]         at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$loadDocker$18(StepsRunner.java:618)
[ERROR]         at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
[ERROR]         at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
[ERROR]         at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:832)
[ERROR] Caused by: java.nio.file.NoSuchFileException: C:\Users\<username>\AppData\Local\Temp\jib-core-application-layers-cache\layers\29836c6746e0ba5a1b7898beac1323d2f1e5c129bc642470df48f3bdf3677db9\00c152acfa069f803b5b78ef79922017d9c666674935294cef3383a1847354ee
[ERROR]         at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[ERROR]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[ERROR]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[ERROR]         at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
[ERROR]         at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
[ERROR]         at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
[ERROR]         at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
[ERROR]         at java.base/java.nio.file.Files.newInputStream(Files.java:160)
[ERROR]         at com.google.cloud.tools.jib.blob.FileBlob.writeTo(FileBlob.java:38)
[ERROR]         at com.google.cloud.tools.jib.tar.TarStreamBuilder.writeAsTarArchiveTo(TarStreamBuilder.java:52)
[ERROR]         at com.google.cloud.tools.jib.image.ImageTarball.dockerWriteTo(ImageTarball.java:149)
[ERROR]         at com.google.cloud.tools.jib.image.ImageTarball.writeTo(ImageTarball.java:78)
[ERROR]         at com.google.cloud.tools.jib.docker.DockerClient.load(DockerClient.java:197)
[ERROR]         ... 8 more
[ERROR]         Suppressed: java.io.IOException: This archive contains unclosed entries.
[ERROR]                 at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:289)
[ERROR]                 at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:307)
[ERROR]                 at com.google.cloud.tools.jib.tar.TarStreamBuilder.writeAsTarArchiveTo(TarStreamBuilder.java:55)
[ERROR]                 ... 11 more
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

A restart of the Docker engine did not help. A restart of windows did not either.

### Expected behavior

Jib container is successfully built.

### Actual behavior

Jib container is not being built.

### How to Reproduce?

Currently I have no way of reproducing this issue.

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19042 DESKTOP-55VO1DT 3.1.7-340.x86_64 2020-09-22 19:03 UTC x86_64 Msys

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19

### Quarkus version or git rev

1.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

### Additional information

**I've managed to fix this issue for me** by manually deleting `C:\Users\<username>\AppData\Local\Temp\jib-core-application-layers-cache\`.

**Comment by geoand** [comment]
I would suggest pruning the images on your local system and trying again. 
If the problem persists, then please report the issue to the Jib repository, as there isn't anything Quarkus can do about it.
