### ISSUE TITLE
local sam execution in jvm mode failing with resteasy error

### ISSUE THREAD

**Issue by deodorel** [quarkusio/quarkus#19056]
### Describe the bug

I am trying to run my project locally with 2.0.1.Final and 2.0.3.Final versions, and when executing 

sam local invoke --template svc/target/sam.jvm.yaml --event some_json

i am getting the exception 

Caused by: java.lang.NoSuchFieldError: SERVER_SENT_EVENTS_TYPE
        at org.jboss.resteasy.core.ResourceMethodInvoker.isSseResourceMethod(ResourceMethodInvoker.java:224)
        at org.jboss.resteasy.core.ResourceMethodInvoker.<init>(ResourceMethodInvoker.java:203)
        at org.jboss.resteasy.core.ResourceMethodRegistry.processMethod(ResourceMethodRegistry.java:381)
        at org.jboss.resteasy.core.ResourceMethodRegistry.register(ResourceMethodRegistry.java:308)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:259)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:227)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:208)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:192)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:175)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:87)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.registerResources(ResteasyDeploymentImpl.java:518)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.registration(ResteasyDeploymentImpl.java:475)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:164)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:121)
        at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.staticInit(ResteasyStandaloneRecorder.java:37)
        at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit-210558872.deploy_0(ResteasyStandaloneBuildStep$staticInit-210558872.zig:1070)
        at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit-210558872.deploy(ResteasyStandaloneBuildStep$staticInit-210558872.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:226)
        ... 5 more

time="2021-07-28T09:52:34.202" level=panic msg="ReplyStream not available"
2021/07/28 09:52:34 http: panic serving 127.0.0.1:45214: &{0xc000148000 map[] 2021-07-28 09:52:34.2022776 +0000 UTC m=+14.498034901 panic <nil> ReplyStream not available <nil> <nil> }
goroutine 54 [running]:
net/http.(*conn).serve.func1(0xc0002261e0)
        /usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x866640, 0xc00025a150)

I am aware of the javax.ws.rs-api issue and i made sure i don't even have it in my dependencies. 

[dep.txt](https://github.com/quarkusio/quarkus/files/6892093/dep.txt)

However when deploying the code as a native image to aws, it works. 

### Expected behavior

The code executes

### Actual behavior

The exception above occurs

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19042.1110]

### Output of `java -version`

openjdk version "11.0.5" 2019-10-15 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

### Quarkus version or git rev

2.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by deodorel** [comment]
Hello, this got solved by upgrading to 2.1.4.Final
