### ISSUE TITLE
Support `native-image` dev versions built locally

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#19052]
### Describe the bug

Error when trying to build Quarkus 2.1.0.Final binaries with locally built `native-image`, e.g.

```
[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /ext/.qollider/cache/2707.graalvm-21.3-dev/graal/sdk/mxbuild/linux-amd64/GRAALVM_CE0C781D19_JAVA11/graalvm-ce0c781d19-java11-21.3.0-dev/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=GB -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar code-with-quarkus-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace code-with-quarkus-1.0.0-SNAPSHOT-runner
[code-with-quarkus-1.0.0-SNAPSHOT-runner:27558]    classlist:   1,166.82 ms,  1.19 GB
--initialize-at-build-time without arguments has been deprecated when not using --diagnostics-mode. With GraalVM 22.0.0. --initialize-at-build-time will only work with --diagnostics-mode for debugging purposes.
The reason for deprecation is that --initalize-at-build-time does not compose, i.e., a single library can make assumptions that the whole classpath can be safely initialized at build time; that assumption is often incorrect.
[code-with-quarkus-1.0.0-SNAPSHOT-runner:27558]        setup:     320.27 ms,  1.19 GB
Fatal error:java.lang.IllegalArgumentException: Invalid version string 'dev'.
	at org.graalvm.sdk/org.graalvm.home.Version.invalid(Version.java:143)
	at org.graalvm.sdk/org.graalvm.home.Version.<init>(Version.java:113)
	at org.graalvm.sdk/org.graalvm.home.Version.parse(Version.java:261)
	at org.graalvm.sdk/org.graalvm.home.Version.getCurrent(Version.java:293)
	at io.quarkus.runtime.graal.Target_java_io_ObjectStreamClass$GraalVM20OrEarlier.getAsBoolean(JavaIOSubstitutions.java:34)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:920)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:288)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:934)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:866)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:489)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:399)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:562)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:121)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:592)
[code-with-quarkus-1.0.0-SNAPSHOT-runner:27558]      [total]:   1,530.14 ms,  1.19 GB
# Printing build artifacts to: /home/g/shared/mendrugo/profile-buildtime/quarkus/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/code-with-quarkus-1.0.0-SNAPSHOT-runner.build_artifacts.txt
Error: Image build request failed with exit status 1
```

```
❯ /opt/graalvm-21.3-dev/bin/native-image --version
native-image dev CE (Java Version 11.0.12+5-jvmci-21.3-b02-dev)
```

**Comment by galderz** [comment]
Not a Quarkus issue, the snapshot built does not contain version information.
