### ISSUE TITLE
NPE in LambdaHttpHandler (amazon-lambda-http extension)

### ISSUE THREAD

**Issue by deki** [quarkusio/quarkus#19063]
### Describe the bug

While testing a Quarkus Lambda function, I hit the following NPE:

ERROR [qua.ama.lam.http] (main) Request Failure: java.lang.NullPointerException
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.nettyDispatch(LambdaHttpHandler.java:171)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:63)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:43)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.handle(AmazonLambdaRecorder.java:71)
at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.handleRequest(QuarkusStreamHandler.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:375)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:899)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:257)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:192)
at lambdainternal.AWSLambda.main(AWSLambda.java:187)

Would be nicer to get a proper error message. I'm willing to open a PR, just wondering what would be the best way to fix/ validate this?

@patriot1burke @richiethom @HardNorth 

### Expected behavior

A proper error message

### Actual behavior

NullPointerException

### How to Reproduce?

1. Open a deployed Quarkus Lambda function in AWS console
2. Hit Test button
3. NPE is shown in Log output section

### Output of `java -version`

Java 11 (Corretto)

### Quarkus version or git rev

2.1.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by HardNorth** [comment]
@deki Interesting, the only option I see is that `request.getRequestContext().getHttp()` returned null. Because `request.getRequestContext()` was already called few lines above. How did you got such state? Because it's not really clear what to do in that case. There is no "default" method in HTTP protocol.

**Comment by patriot1burke** [comment]
Maybe you are using the wrong extension?  Are you doing a normal lambda or are you using vertxweb, servlet, or jax-rs with lambda?

A regular lambda is quarkus-amazon-lambda
If you are using one of our HTTP apis its quarkus-amazon-lambda-http (or -rest depending on which AWS http api you are using)

**Comment by deki** [comment]
Yes if you trigger the Lambda function directly without involving API-Gateway (e.g. using the Test button in the AWS Lambda console) there is obviously no HTTP involved. So not much we can do apart from providing a proper error message.
