### ISSUE TITLE
Error "java.lang.SecurityException: setParent() disallowed" thrown using some 3rd party library with Quarkus

### ISSUE THREAD

**Issue by tadayosi** [quarkusio/quarkus#19073]
### Describe the bug

I understand the issue is that the 3rd party library invokes `Logger#setParent()` internally, but not always we control libraries which we want to use in our Quarkus app (in my case it is `io.github.spencerpark:jupyter-jvm-basekernel`).

### Expected behavior

Quarkus (or JBoss Logging) should allow to use 3rd party libaries despite they use `Logger#setParent()` internally. Or at least it should provide some way to rescue the situation.

My proposal is that JBoss Logging `Logger#setParent()` log a warning instead of throwing `SecurityException`.

### Actual behavior

Error thrown:
```
2021-07-29 00:11:11,329 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.SecurityException: setParent() disallowed
	at org.jboss.logmanager.Logger.setParent(Logger.java:348)
	at io.github.spencerpark.jupyter.channels.JupyterSocket.<init>(JupyterSocket.java:62)
	at io.github.spencerpark.jupyter.channels.HeartbeatChannel.<init>(HeartbeatChannel.java:21)
	at io.github.spencerpark.jupyter.channels.HeartbeatChannel.<init>(HeartbeatChannel.java:26)
	at io.github.spencerpark.jupyter.channels.JupyterConnection.<init>(JupyterConnection.java:37)
	at io.github.tadayosi.icamel.ICamel.run(ICamel.java:51)
	at io.github.tadayosi.icamel.ICamel_ClientProxy.run(ICamel_ClientProxy.zig:129)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:123)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
```

### How to Reproduce?

Create a library that has the following code internally:
```java
import java.util.logging.Logger;

Logger logger1 = Logger.getLogger("Logger1");
Logger logger2 = Logger.getLogger("Logger2");
logger2.setParent(logger1);
```
and try to run the piece of code from another Quarkus app.

### Output of `uname -a` or `ver`
```
$ uname -a
Linux mypc 4.20.10-1.el7.elrepo.x86_64 #1 SMP Fri Feb 15 08:52:17 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```
### Output of `java -version`

```
$ java -version
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode, sharing)
```

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

2.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
$ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/tasato/.sdkman/candidates/maven/current
Java version: 11.0.12, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.12.0.7-0.el7_9.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.20.10-1.el7.elrepo.x86_64", arch: "amd64", family: "unix"
```

### Additional information

I tried to workaround the issue by substituting the JBoss LogManager used in Quarkus to my custom one so that I could hook the invocation of `Logger.setParent()` for a specific logger. But even I used `java.util.logging.manager` system property or service locator `META-INF/services/java.util.logging.LogManager` it doesn't seem to be possible other than for testing.

**Comment by gastaldi** [comment]
That's not a Quarkus issue, please open this ticket in https://issues.redhat.com/browse/LOGMGR
