### ISSUE TITLE
infinispan-client requires authentication to be defined right after adding the extension, didn't need that in 2.0.0.Final

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#19081]
### Describe the bug

infinispan-client requires authentication to be defined right after adding the extension, didn't need that in 2.0.0.Final

```
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-07-29 11:19:27,191 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2021-07-29 11:19:27,190 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): org.infinispan.commons.CacheConfigurationException: ISPN004030: Cannot enable authentication without specifying either a username, a token, a client Subject or a CallbackHandler
	at org.infinispan.client.hotrod.configuration.AuthenticationConfigurationBuilder.validate(AuthenticationConfigurationBuilder.java:227)
	at org.infinispan.client.hotrod.configuration.SecurityConfigurationBuilder.validate(SecurityConfigurationBuilder.java:43)
	at org.infinispan.client.hotrod.configuration.ConfigurationBuilder.validate(ConfigurationBuilder.java:529)
	at org.infinispan.client.hotrod.configuration.ConfigurationBuilder.build(ConfigurationBuilder.java:596)
	at org.infinispan.client.hotrod.configuration.ConfigurationBuilder.build(ConfigurationBuilder.java:591)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.initialize(InfinispanClientProducer.java:64)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.remoteCacheManager(InfinispanClientProducer.java:303)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_Subclass.remoteCacheManager$$superforward1(InfinispanClientProducer_Subclass.zig:309)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_Subclass$$function$$3.apply(InfinispanClientProducer_Subclass$$function$$3.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_Subclass.remoteCacheManager(InfinispanClientProducer_Subclass.zig:627)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.create(InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.zig:202)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.get(InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.zig:232)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.get(InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.zig:267)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:433)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:446)
	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:416)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:225)
	at io.quarkus.infinispan.client.runtime.InfinispanClientSupplier.cacheManager(InfinispanClientSupplier.java:18)
	at io.quarkus.infinispan.client.runtime.InfinispanClientSupplier.get(InfinispanClientSupplier.java:13)
	at io.quarkus.infinispan.client.runtime.InfinispanClientSupplier.get(InfinispanClientSupplier.java:9)
	at io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder.addInfo(DevConsoleRecorder.java:37)
	at io.quarkus.deployment.steps.DevConsoleProcessor$runtimeTemplates-308161071.deploy_0(DevConsoleProcessor$runtimeTemplates-308161071.zig:130)
	at io.quarkus.deployment.steps.DevConsoleProcessor$runtimeTemplates-308161071.deploy(DevConsoleProcessor$runtimeTemplates-308161071.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:765)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:98)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Expected behavior

Application starts without error

### Actual behavior

Error + stacktrace are thrown

### How to Reproduce?

**Generate the 2.0.0.Final based project:**
rm -rf app-generated-skeleton && mvn io.quarkus:quarkus-maven-plugin:2.0.0.Final:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-generated-skeleton -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DplatformVersion=2.0.0.Final -Dextensions=quarkus-infinispan-client

**Run in dev mode**
mvn -f app-generated-skeleton/pom.xml clean quarkus:dev

**Run with 2.1.0.Final in dev mode**
mvn -f app-generated-skeleton/pom.xml clean quarkus:dev -Dquarkus.platform.version=2.1.0.Final

### Output of `uname -a` or `ver`

macOS BigSur

### Output of `java -version`

Java 11

### Quarkus version or git rev

Quarkus 2.1.0.Final

**Comment by karesti** [comment]
@rsvoboda hi! are you using infinispan without authentication ?

**Comment by rsvoboda** [comment]
Hi Katia. My flow is just to generate the project and run the dev mode to ensure good OOTB experience, no ISPN is running.

**Comment by karesti** [comment]
Ok, we changed the default behaviour since infinispan is authenticated by default and authorization enabled by default.
https://quarkus.io/version/main/guides/infinispan-client

I added the DIGEST by default as well since SCRAM is not yet supported with quarkus and it's the default.

So the 


quarkus.infinispan-client.use-authEnables is set to true








quarkus.infinispan-client.use-authEnables or disables authentication. Set it to false when connecting to a Infinispan Server without authentication. deployments. Default is 'true'.Show less | boolean | true
-- | -- | --





quarkus.infinispan-client.use-authEnables or disables authentication. Set it to false when connecting to a Infinispan Server without authentication. deployments. Default is 'true'.Show less | boolean | true
-- | -- | --

**Comment by karesti** [comment]
@rsvoboda the documentation changes are in snapshot version

**Comment by rsvoboda** [comment]
I think something should be added into https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.1.

**Comment by karesti** [comment]
probably @rsvoboda 
I did not test this use case at all, I just made sure to simplify the use of infinispan since the container images are authenticated by default and to use a non authenticated you need to do it explicitly, so it makes more sense to me to also specifically disable it from the extension, which is also the case if you specify a user and password today.
Anyway, how do you think we can make this experience better from the extension? or anywhere else

**Comment by rsvoboda** [comment]
Using `quarkus.infinispan-client.use-auth=false` I get further. But there are attempts to contact ISPN server eagerly, I have no work for ISPN, I have just added the extension ... 

I see this in the logs:
```
2021-07-29 11:46:03,975 ERROR [org.inf.HOTROD] (HotRod-client-async-pool-1-12) ISPN004007: Exception encountered. 
  Retry 10 out of 10: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:11222
  Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by karesti** [comment]
yes, I see, tries to connect to infinispan even if there is nothing configured about infinispan, which is weird since I don't create any client in the extension (is null) if the application.properties is empty

**Comment by rsvoboda** [comment]
My use case is that developer generates new project, knows he/she will use ISPN too, so he/she adds the extension.
Starts the dev mode and wants to switch to the IDE to start coding some rest endpoint etc. but the browser gives just Error restarting Quarkus with `Connection refused: /127.0.0.1:11222` in the stacktrace

**Comment by karesti** [comment]
ok I know why, is because I added the Console Dev mode.

**Comment by karesti** [comment]
@rsvoboda I'll fix this

**Comment by karesti** [comment]
@rsvoboda I think this should be fixed already in 2.2
https://github.com/quarkusio/quarkus/pull/18618

**Comment by karesti** [comment]
but maybe there are still other issues related to the lack of any property specified in dev mode.
I will check this use case with the latest snapshot version and fix whatever needs to be fixed if it fails

**Comment by rsvoboda** [comment]
Cool, tried Quarkus main and this issue is already fixed.
`mvn -f app-generated-skeleton/pom.xml clean quarkus:dev -Dquarkus.platform.version=999-SNAPSHOT -Dquarkus.platform.group-id=io.quarkus`

**Comment by karesti** [comment]
@rsvoboda as I suspected the dev ui tries to use a null remote cache manager so it breaks. fixing that in a PR

**Comment by karesti** [comment]
I made some changes to the dev UI https://github.com/quarkusio/quarkus/pull/19099
