### ISSUE TITLE
Native build fails with LC_ALL=cs_CZ

### ISSUE THREAD

**Issue by pokusak** [quarkusio/quarkus#19082]
### Describe the bug

Building native image with environment variable LC_ALL set to cs_CZ fails on tests (or if tests skipped binary is created but fails to start with same error)

### Expected behavior

Working executable should be created for EN settings same as for CZ settings

### Actual behavior

Running final binary fails on:
`
java.lang.NoSuchMethodError: java.lang.String.<init>([B)V
        at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1113)
        at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1098)
        at com.oracle.svm.jni.functions.JNIFunctions.GetMethodID(JNIFunctions.java:411)
        at java.io.UnixFileSystem.canonicalize0(UnixFileSystem.java)
        at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:178)
        at java.io.File.getCanonicalPath(File.java:626)
        at java.io.File.getCanonicalFile(File.java:651)
        at sun.security.provider.FileInputStreamPool.getInputStream(FileInputStreamPool.java:84)
        at sun.security.provider.NativePRNG$RandomIO.<init>(NativePRNG.java:388)
        at sun.security.provider.NativePRNG$1.run(NativePRNG.java:190)
        at sun.security.provider.NativePRNG$1.run(NativePRNG.java:130)
        at java.security.AccessController.doPrivileged(AccessController.java:82)
        at sun.security.provider.NativePRNG.initIO(NativePRNG.java:129)
        at sun.security.provider.NativePRNG.<clinit>(NativePRNG.java:93)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.security.Provider.newInstanceUtil(Provider.java:176)
        at java.security.Provider$Service.newInstance(Provider.java:1894)
        at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:290)
        at java.security.SecureRandom.<init>(SecureRandom.java:219)
        at java.util.UUID$Holder.<clinit>(UUID.java:101)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at java.util.UUID.randomUUID(UUID.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder.getRandomDirectory(VertxCoreRecorder.java:313)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder.convertToVertxOptions(VertxCoreRecorder.java:268)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:195)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:515)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:497)
        at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.vertxRequestHandler(ResteasyStandaloneRecorder.java:58)
        at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$boot1173861480.deploy_0(ResteasyStandaloneBuildStep$boot1173861480.zig:138)
        at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$boot1173861480.deploy(ResteasyStandaloneBuildStep$boot1173861480.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:568)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)`

### How to Reproduce?

1. clone https://github.com/quarkusio/quarkus-quickstarts
2. run export LC_ALL=cs_CZ
3. build subproject getting-started with: mvn clean install -Pnative (among others following paramters are used: -J-Duser.language=cs -J-Duser.country=CZ)
4. Tests fails to run app to test it. If you run point 3) with -DskipTests, binary is created but also fails to start

### Output of `uname -a` or `ver`

Linux <PC-ID> 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux == WSL with Ubuntu 20.04

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05) OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

### Quarkus version or git rev

3d5865045e72f261d3e98c19707b1da0f9361801

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /mnt/c/work/linux/apache-maven-3.8.1 Java version: 11.0.11, vendor: GraalVM Community, runtime: /mnt/c/work/linux/graalvm-ce-java11-21.1.0 Default locale: en_US, platform encoding: ANSI_X3.4-1968 OS name: "linux", version: "4.4.0-18362-microsoft", arch: "amd64", family: "unix"

### Additional information

1. Exporting empty LC_ALL or using -J-Duser.language=en -J-Duser.country=US works OK
2. There is same problem with GraalVM 21.2.0
3. Locale cs_CZ should be installed correctly:
```
locale -a
C
C.UTF-8
POSIX
cs_CZ
cs_CZ.iso88592
czech
en_US.utf8
```

**Comment by jaikiran** [comment]
This exact error was previously once raised in https://github.com/quarkusio/quarkus/issues/10682#issuecomment-729064863. With the useful additional details you added in this new issue, it helped understand what might be going on. This looks like an issue in GraalVM itself. So I've opened https://github.com/oracle/graal/pull/3680 with a potential fix.

**Comment by Karm** [comment]
This is no longer an issue as per tests done in #23518
