### ISSUE TITLE
Regression: Null pointer exception when enabling continuous testing

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#19090]
### Describe the bug

This issue is caused by this commit: https://github.com/quarkusio/quarkus/commit/8d49f1e0af15608bb91588e9b05521048ca1a5bf

Basically, doing `mvn quarkus:dev` and pressing the key `r` (resuming testing), we will get the exception:

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-07-29 13:51:26,833 INFO  [io.quarkus] (Quarkus Main Thread) examples-greetings 0.0.4-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 1.565s. Listening on: http://localhost:8080
2021-07-29 13:51:26,837 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-07-29 13:51:26,838 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, smallrye-context-propagation]
2021-07-29 13:51:31,041 ERROR [io.qua.dep.dev.tes.TestSupport] (Aesh InputStream Reader) Failed to create compiler, runtime compilation will be unavailable: java.lang.NullPointerException
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.startTestScanningTimer(RuntimeUpdatesProcessor.java:268)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.checkForChangedTestClasses(RuntimeUpdatesProcessor.java:605)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor$1.testsEnabled(RuntimeUpdatesProcessor.java:147)
	at io.quarkus.deployment.dev.testing.TestSupport.start(TestSupport.java:106)
	at io.quarkus.deployment.dev.testing.TestConsoleHandler$2.run(TestConsoleHandler.java:94)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:73)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:46)
	at io.quarkus.deployment.console.AeshConsole.lambda$setup$1(AeshConsole.java:199)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:118)
	at org.aesh.terminal.EventDecoder.accept(EventDecoder.java:31)
	at org.aesh.terminal.io.Decoder.write(Decoder.java:133)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:216)
	at org.aesh.readline.tty.terminal.TerminalConnection.openBlocking(TerminalConnection.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Other consequences (not sure if related to the null pointer or not) are that when adding a new test, this test is indeed detected and executed, but it never ends:

```
Running 1/1. Running: io.quarkus.qe.GreetingResourceTest#shouldSayVictor()
```

**Comment by geoand** [comment]
I **assume** it's as simple as https://github.com/quarkusio/quarkus/pull/19093
