### ISSUE TITLE
java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#19106]
### Describe the bug

I have this code .  PS That code works fine before, now I saw this error after adding kafka support.

````
    @ConfigProperty(name = "com.comact.iep.connector.CmsClientRestConnector/mp-rest/url")
    Instance<String> cmsClientRestConnectorURL;
	
	private void logResponseIfNeeded(String method, int status, String address, String content) {
        // don't log cms-client POST response body

        if (address.startsWith(cmsClientRestConnectorURL.get()) && Objects.equals(method, "POST") && status == 200) {
            LOGGER.debug("RestClient response [{}] Status code [{}] to IP [{}] Body [not logged]", method, status, address);
            return;
        }
		...
````

that return this error 
````
15:35:25.422 [ForkJoinPool.commonPool-worker-1] ERROR com.comact.iep.codec.AbstractCodec - null
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy98.updateHealth(Unknown Source)
	at com.comact.iep.connector.TwinRestConnector_27306872b9b9d6a5cde2e5a56fad18628bb23077_Synthetic_ClientProxy.updateHealth(TwinRestConnector_27306872b9b9d6a5cde2e5a56fad18628bb23077_Synthetic_ClientProxy.zig:353)
	at com.comact.iep.codec.AbstractCodec.uninstallApplication(AbstractCodec.java:809)
	at com.comact.iep.codec.AbstractCodec.asyncUninstall(AbstractCodec.java:1172)
	at com.comact.iep.codec.AbstractCodec.lambda$restartApplication$21(AbstractCodec.java:1149)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
	... 12 common frames omitted
Caused by: javax.ws.rs.client.ResponseProcessingException: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:727)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:493)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy94.updateHealth(Unknown Source)
	... 17 common frames omitted
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:100)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:101)
	at io.smallrye.config.inject.ConfigProducer.getConfig(ConfigProducer.java:45)
	at io.smallrye.config.inject.ConfigProducer.produceStringConfigProperty(ConfigProducer.java:52)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.create(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:269)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.get(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:299)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.get(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:334)
	at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:210)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
	at com.comact.iep.codec.util.LoggingFilter.logResponseIfNeeded(LoggingFilter.java:147)
	at com.comact.iep.codec.util.LoggingFilter.filter(LoggingFilter.java:185)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:719)
	... 22 common frames omitted
````

![image](https://user-images.githubusercontent.com/191879/127558423-9b879121-439e-4c03-8474-bed04ec302ea.png)

Same problem with Quarkus 2.0.3.Final and Quarkus 2.1.0.Final

**Comment by survivant** [comment]
I updated Quarkus to 2.1.0.Final and the problem is still there.

````
07:55:01.004 [executor-thread-0] DEBUG c.c.iep.codec.util.LoggingFilter - Request [POST] [/api/codec/operation] from IP [127.0.0.1:52878] Body [{  "id" : "93adfc3f-d556-4b75-82e3-7723f4957a36",  "name" : "Node parent machineCodec_1",  "templateId" : "889f991a-4cb4-47f8-8a53-ce041b427f43",  "templateName" : "machineCodec",  "templateVersion" : "1.0.0",  "params" : [ {    "id" : "320cdab1-7b2d-4247-9ae0-f20de2a19016",    "paramKey" : "iepCodecHost",    "value" : "localhost",    "order" : 0  }, {    "id" : "f1d4096c-7938-4342-b1f1-ae8cb2ffab61",    "paramKey" : "iepCodecPort",    "value" : "8282",    "order" : 0  }, {    "id" : "7bfb1d08-5784-43bc-be8c-b12a5e2da2bf",    "paramKey" : "probesEnabled",    "value" : "false",    "order" : 0  }, {    "id" : "b5b1d38d-eaee-4261-85df-6570c9c89fd8",    "paramKey" : "service.http.nodePort",    "value" : "",    "order" : 0  }, {    "id" : "ee5eaae1-cabd-4787-ba52-bafaca1f3cde",    "paramKey" : "nginx.host",    "value" : "localhost",    "order" : 0  }, {    "id" : "80cfbe12-ae8d-49e1-8d8a-3aa3dacb53b5",    "paramKey" : "persistence.enabled",    "value" : "false",    "order" : 0  }, {    "id" : "27cfbc9d-a111-4e81-bbb8-f56057e68c61",    "paramKey" : "mariadb.master.persistence.enabled",    "value" : "false",    "order" : 0  } ],  "singletonNodesId" : [ "5cc1c63a-59ae-48a5-b7f6-73b5c5bada6d", "2c3bcd4d-bd9a-492a-9460-dbe7a5c65987", "2b4fb0d3-068d-4e82-9172-47b39c9b7126", "10f772be-d2f5-4e5d-bb62-7cf53857b27e", "4b3d7971-bc11-487b-86fe-51827c0d885b" ],  "nodeState" : "SYNC",  "nodeHealth" : "ONLINE",  "supportedOperations" : [ "START", "STOP", "RESTART" ],  "pendingOperation" : "RESTART",  "codecGroupId" : "93adfc3f-d556-4b75-82e3-7723f4957a36",  "errors" : [ ],  "properties" : [ {    "id" : "b8faa27a-0e6a-4cf1-adb1-3fd369c0fece",    "name" : "optimizer.number",    "type" : "TEXT",    "mandatory" : true,    "readOnly" : false,    "order" : 1,    "defaultValue" : "0",    "choices" : [ ],    "value" : "0"  }, {    "id" : "975bc3c1-4c86-4e05-9346-e572edf3cf64",    "name" : "simulator.number",    "type" : "TEXT",    "mandatory" : true,    "readOnly" : false,    "order" : 5,    "defaultValue" : "0s",    "choices" : [ ],    "value" : "0"  }, {    "id" : "f4d5cff7-0597-40df-b032-12c497c92faf",    "name" : "spring.profiles.active",    "type" : "TEXT",    "mandatory" : false,    "readOnly" : true,    "order" : 9,    "choices" : [ ],    "value" : "kubernetes\\,production\\,oli"  }, {    "id" : "af4e45d7-0cc1-4f2e-abfa-eedca0579ddd",    "name" : "simulator.host",    "type" : "TEXT",    "mandatory" : true,    "readOnly" : false,    "order" : 6,    "choices" : [ ],    "value" : "SIMULATOR_HOST"  }, {    "id" : "d771e4a2-b123-466f-908d-6ef88bc43df9",    "name" : "optimizer.host",    "type" : "TEXT",    "mandatory" : true,    "readOnly" : false,    "order" : 2,    "choices" : [ ],    "value" : "OPTIMIZER_HOST"  }, {    "id" : "3f47f084-a6a0-4192-9a7b-32cd88901902",    "name" : "simulator.cmsPort",    "type" : "TEXT",    "mandatory" : true,    "readOnly" : false,    "order" : 7,    "choices" : [ ],    "value" : "8080"  }, {    "id" : "af032142-f2d8-433c-a7d6-9e6143135441",    "name" : "service.loadBalancerIP",    "type" : "TEXT",    "mandatory" : true,    "readOnly" : false,    "order" : 10,    "choices" : [ ],    "value" : "SIMULATOR_HOST"  }, {    "id" : "97662b21-0539-4168-9557-a11b3ebe3baf",    "name" : "machine.type",    "type" : "CHOICE",    "mandatory" : true,    "readOnly" : false,    "order" : 0,    "choices" : [ ],    "value" : "oli"  }, {    "id" : "34fba749-d204-48f7-9ced-cdd7081bbc1f",    "name" : "optimizer.cmsPort",    "type" : "TEXT",    "mandatory" : true,    "readOnly" : false,    "order" : 3,    "choices" : [ ],    "value" : "8080"  }, {    "id" : "bdced763-2574-4e90-a28b-e52d15286de0",    "name" : "simulator.acquisition.enabled",    "type" : "BOOLEAN",    "mandatory" : true,    "readOnly" : false,    "order" : 8,    "defaultValue" : "false",    "choices" : [ ],    "value" : "false"  }, {    "id" : "7095b972-ec39-4049-868d-582d99cdeb74",    "name" : "optimizer.acquisition.enabled",    "type" : "BOOLEAN",    "mandatory" : true,    "readOnly" : false,    "order" : 4,    "defaultValue" : "true",    "choices" : [ ],    "value" : "true"  } ],  "syncDate" : 1627646035379,  "creationDate" : 1627646021927,  "modificationDate" : 1627646100062,  "deleted" : false}]
07:55:06.346 [ForkJoinPool.commonPool-worker-3] ERROR com.comact.iep.codec.AbstractCodec - null
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy101.updateHealth(Unknown Source)
	at com.comact.iep.connector.TwinRestConnector_27306872b9b9d6a5cde2e5a56fad18628bb23077_Synthetic_ClientProxy.updateHealth(TwinRestConnector_27306872b9b9d6a5cde2e5a56fad18628bb23077_Synthetic_ClientProxy.zig:353)
	at com.comact.iep.codec.AbstractCodec.uninstallApplication(AbstractCodec.java:809)
	at com.comact.iep.codec.AbstractCodec.asyncUninstall(AbstractCodec.java:1172)
	at com.comact.iep.codec.AbstractCodec.lambda$restartApplication$21(AbstractCodec.java:1149)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
	... 12 common frames omitted
Caused by: javax.ws.rs.client.ResponseProcessingException: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:807)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy97.updateHealth(Unknown Source)
	... 17 common frames omitted
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:100)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:101)
	at io.smallrye.config.inject.ConfigProducer.getConfig(ConfigProducer.java:45)
	at io.smallrye.config.inject.ConfigProducer.produceStringConfigProperty(ConfigProducer.java:52)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.create(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:269)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.get(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:299)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.get(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:334)
	at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:210)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
	at com.comact.iep.codec.util.LoggingFilter.logResponseIfNeeded(LoggingFilter.java:147)
	at com.comact.iep.codec.util.LoggingFilter.filter(LoggingFilter.java:185)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
	... 22 common frames omitted
07:55:06.350 [ForkJoinPool.commonPool-worker-3] DEBUG c.c.iep.codec.util.LoggingFilter - RestClient request [POST] to IP [http://localhost:8003/label/PODS/namespace/default/state/ACTIVE_STATE] Body [{  "nodeUUID" : "c73915a7-0c80-4cfb-9ec0-0ee1eda98ae5"}]
07:55:06.704 [ForkJoinPool.commonPool-worker-3] ERROR com.comact.iep.codec.AbstractCodec - null
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy113.findMetadataResourceByLabelsAndState(Unknown Source)
	at com.comact.iep.connector.KubernetesApiRestConnector_f22da27362baf853b2c5fd216af58a517f31ec01_Synthetic_ClientProxy.findMetadataResourceByLabelsAndState(KubernetesApiRestConnector_f22da27362baf853b2c5fd216af58a517f31ec01_Synthetic_ClientProxy.zig:169)
	at com.comact.iep.codec.util.ChartHelper.getReleasesNotTerminatedWithLabel(ChartHelper.java:600)
	at com.comact.iep.codec.util.ChartHelper.isApplicationInstalled(ChartHelper.java:736)
	at com.comact.iep.codec.util.ChartHelper_ClientProxy.isApplicationInstalled(ChartHelper_ClientProxy.zig:250)
	at com.comact.iep.codec.AbstractCodec.isApplicationInstalled(AbstractCodec.java:968)
	at com.comact.iep.codec.AbstractCodec.installApplication(AbstractCodec.java:705)
	at com.comact.iep.codec.AbstractCodec.asyncInstall(AbstractCodec.java:1161)
	at com.comact.iep.codec.AbstractCodec.lambda$restartApplication$22(AbstractCodec.java:1151)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
	... 16 common frames omitted
Caused by: javax.ws.rs.client.ResponseProcessingException: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:807)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy112.findMetadataResourceByLabelsAndState(Unknown Source)
	... 21 common frames omitted
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:100)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:101)
	at io.smallrye.config.inject.ConfigProducer.getConfig(ConfigProducer.java:45)
	at io.smallrye.config.inject.ConfigProducer.produceStringConfigProperty(ConfigProducer.java:52)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.create(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:269)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.get(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:299)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.get(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:334)
	at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:210)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
	at com.comact.iep.codec.util.LoggingFilter.logResponseIfNeeded(LoggingFilter.java:147)
	at com.comact.iep.codec.util.LoggingFilter.filter(LoggingFilter.java:185)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
	... 26 common frames omitted
07:55:06.705 [ForkJoinPool.commonPool-worker-3] INFO  com.comact.iep.codec.AbstractCodec - Application [application-server] is restarted
07:55:07.191 [ForkJoinPool.commonPool-worker-5] ERROR com.comact.iep.codec.AbstractCodec - null
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy101.updateHealth(Unknown Source)
	at com.comact.iep.connector.TwinRestConnector_27306872b9b9d6a5cde2e5a56fad18628bb23077_Synthetic_ClientProxy.updateHealth(TwinRestConnector_27306872b9b9d6a5cde2e5a56fad18628bb23077_Synthetic_ClientProxy.zig:353)
	at com.comact.iep.codec.AbstractCodec.uninstallApplication(AbstractCodec.java:809)
	at com.comact.iep.codec.AbstractCodec.asyncUninstall(AbstractCodec.java:1172)
	at com.comact.iep.codec.AbstractCodec.lambda$restartApplication$21(AbstractCodec.java:1149)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
	... 12 common frames omitted
Caused by: javax.ws.rs.client.ResponseProcessingException: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:807)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy97.updateHealth(Unknown Source)
	... 17 common frames omitted
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:100)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:101)
	at io.smallrye.config.inject.ConfigProducer.getConfig(ConfigProducer.java:45)
	at io.smallrye.config.inject.ConfigProducer.produceStringConfigProperty(ConfigProducer.java:52)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.create(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:269)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.get(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:299)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.get(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:334)
	at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:210)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
	at com.comact.iep.codec.util.LoggingFilter.logResponseIfNeeded(LoggingFilter.java:147)
	at com.comact.iep.codec.util.LoggingFilter.filter(LoggingFilter.java:185)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
	... 22 common frames omitted
````

**Comment by survivant** [comment]
I'm going in vacation for 3 weeks, I'll try to answer if you have questions.

**Comment by survivant** [comment]
Maybe I got something.  Look like the application crash when I use a RestClient within a ComputeFuture

````
// uninstall the application
            // when we receive a cleanupjob completed
            // we install the application
            CompletableFuture.supplyAsync(() -> asyncUninstall(nodeApplication, updateNodeStateMap))
                    .thenComposeAsync((releaseName) ->
                            CompletableFuture.supplyAsync(() -> asyncInstall(parentNode, nodeApplication, template, updateNodeStateMap)))
                    .thenAcceptAsync(release -> LOGGER.info("Application [{}] is restarted", nodeApplication.getName()));
````

In the async methods I'll call a RestClient
````
@Inject
    @RestClient
    protected TwinRestConnector twinRestConnector;
````

**Comment by survivant** [comment]
Look like I found a solution.  I had to pass a ManagedExecutor

````
CompletableFuture.supplyAsync(() -> asyncUninstall(nodeApplication, updateNodeStateMap), managedExecutor)
                    .thenComposeAsync((releaseName) ->
                            CompletableFuture.supplyAsync(() -> asyncInstall(parentNode, nodeApplication, template, updateNodeStateMap), managedExecutor), managedExecutor)
                    .thenAcceptAsync(release -> LOGGER.info("Application [{}] is restarted", nodeApplication.getName()), managedExecutor);
````
