### ISSUE TITLE
Enhance `@TestTransaction` to recognize `@ReactiveTransactional`

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#19102]
### Description

Quarkus 2.1 introduces `@ReactiveTransactional`, but if I'm writing tests that want to roll back the transaction at the end of each test I can't use [`@TestTransaction`](https://quarkus.io/guides/getting-started-testing#tests-and-transactions). Instead I have to do something like this:

```java
public class TestTransaction {
	public static <T> Uni<T> withRollback(Supplier<Uni<T>> uni) {
		return Panache.getSession()
			.flatMap(session -> session.withTransaction(tx -> {
				tx.markForRollback();
				return uni.get();
			}));
	}
}
```

and then use it like this
```java
@QuarkusTest
class FruitRepositoryTests {
	@Inject
	FruitRepository fruitRepository;

	@Test
	public void findByName() {
		Fruit fruit = TestTransaction.withRollback(() ->
			this.fruitRepository
				.persist(new Fruit(null, "Grapefruit", "Summer fruit"))
				.replaceWith(this.fruitRepository.findByName("Grapefruit"))
		)
			.await()
			.atMost(Duration.ofSeconds(10));

		assertThat(fruit)
			.isNotNull()
			.extracting(Fruit::getName, Fruit::getDescription)
			.containsExactly("Grapefruit", "Summer fruit");

		assertThat(fruit.getId())
			.isNotNull()
			.isGreaterThan(2L);
	}
}
```

Instead, it would be much nicer to do this
```java
@QuarkusTest
@TestTransaction
class FruitRepositoryTests {
	@Inject
	FruitRepository fruitRepository;

	@Test
	public void findByName() {
		Fruit fruit = this.fruitRepository
			.persist(new Fruit(null, "Grapefruit", "Summer fruit"))
			.replaceWith(this.fruitRepository.findByName("Grapefruit"))
			.await()
			.atMost(Duration.ofSeconds(10));

		assertThat(fruit)
			.isNotNull()
			.extracting(Fruit::getName, Fruit::getDescription)
			.containsExactly("Grapefruit", "Summer fruit");

		assertThat(fruit.getId())
			.isNotNull()
			.isGreaterThan(2L);
	}
}
```

All the test methods would run in transactions automatically.

**Comment by geoand** [comment]
Does `@TestReactiveTransaction` fit the bill?

**Comment by edeandrea** [comment]
> Does `@TestReactiveTransaction` fit the bill?

Does that already exist?

**Comment by geoand** [comment]
It does: https://github.com/quarkusio/quarkus/blob/2.1.0.Final/test-framework/common/src/main/java/io/quarkus/test/TestReactiveTransaction.java

Wanna give it a try and if it does do what the issue explains, we can close it

**Comment by edeandrea** [comment]
When I use it I get
```shell
java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-23

	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
	at org.acme.repository.FruitRepositoryTests.checkSize(FruitRepositoryTests.java:56)
	at org.acme.repository.FruitRepositoryTests.beforeTest(FruitRepositoryTests.java:47)
	at org.acme.repository.FruitRepositoryTests_Subclass.beforeTest$$superforward1(FruitRepositoryTests_Subclass.zig:179)
	at org.acme.repository.FruitRepositoryTests_Subclass$$function$$2.apply(FruitRepositoryTests_Subclass$$function$$2.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.hibernate.reactive.panache.common.runtime.ReactiveTransactionalInterceptorBase.lambda$intercept$2(ReactiveTransactionalInterceptorBase.java:47)
	at org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.lambda$execute$0(MutinySessionImpl.java:434)
	at io.smallrye.mutiny.Uni.lambda$chain$0(Uni.java:494)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.vertx.core.Future.lambda$toCompletionStage$2(Future.java:360)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
	at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
	at io.vertx.pgclient.impl.PgSocketConnection.lambda$doSchedule$2(PgSocketConnection.java:160)
	at io.vertx.sqlclient.impl.command.CommandResponse.fire(CommandResponse.java:46)
	at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:279)
	at io.vertx.pgclient.impl.PgSocketConnection.handleMessage(PgSocketConnection.java:96)
	at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:98)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:97)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$handleMessage$9(NetSocketImpl.java:390)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:49)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:275)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:389)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:87)
	at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:139)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:237)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:96)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-23
		at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
		at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
		at org.acme.repository.FruitRepositoryTests.checkSize(FruitRepositoryTests.java:56)
		at org.acme.repository.FruitRepositoryTests.afterTest(FruitRepositoryTests.java:52)
		at org.acme.repository.FruitRepositoryTests_Subclass.afterTest$$superforward1(FruitRepositoryTests_Subclass.zig:165)
		at org.acme.repository.FruitRepositoryTests_Subclass$$function$$1.apply(FruitRepositoryTests_Subclass$$function$$1.zig:24)
		... 67 more
```

Here's the test class
```java
@QuarkusTest
@TestReactiveTransaction
class FruitRepositoryTests {
	@Inject
	FruitRepository fruitRepository;

	@Test
	public void findByName() {
		Fruit fruit = this.fruitRepository
			.persist(new Fruit(null, "Grapefruit", "Summer fruit"))
			.replaceWith(this.fruitRepository.findByName("Grapefruit"))
			.await()
			.atMost(Duration.ofSeconds(10));

		assertThat(fruit)
			.isNotNull()
			.extracting(Fruit::getName, Fruit::getDescription)
			.containsExactly("Grapefruit", "Summer fruit");

		assertThat(fruit.getId())
			.isNotNull()
			.isGreaterThan(2L);
	}

	@BeforeEach
	public void beforeTest() {
		checkSize("Before");
	}

	@AfterEach
	public void afterTest() {
		checkSize("After");
	}

	private void checkSize(String msg) {
		var size = this.fruitRepository.count().await().atMost(Duration.ofSeconds(5));

		System.out.println(String.format("checkSize (%s): %d", msg, size));

		assertThat(size)
			.isEqualTo(2);
	}
```

**Comment by geoand** [comment]
Yes, that stuff is required - it's the price of using a reactive approach in the tests themselves.

I'm going to close this as the annotation covers the original issue's intent.

For bugs regarding the test lifecycle or API improvements, please open new focused issues

**Comment by edeandrea** [comment]
I'd say the custom class I built is far more intuitive than having to bring in extra vertx dependencies just so I can test :) Yeah I lose the test annotation but its far easier to read and I can continue using my favorite libraries.
