### ISSUE TITLE
Can't seem to use `UniAssertSubscriber` nor JUnit's `@BeforeEach` or `@AfterEach` with `@TestReactiveTransaction`

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#19109]
### Describe the bug

This is a spawn-off from #19102 - there's a lengthy comment at the bottom which I'll try to summarize here.

If I have an application using Panache reactive and I try to use the new `@TestReactiveTransaction` annotation rather than what I'm doing now:
```java
Panache.getSession().flatMap(session -> session.withTransaction(tx -> {
  tx.markForRollback();
  return some Uni;
}));
```

It seems I'm no longer able to use things like `UniAssertSubscriber` or run any kinds of tests that use any kind of `await` mechanism.

Some examples of things I can no longer do:
```java
@Test
@TestReactiveTransaction
public void findByName() {
	Fruit fruit = fruitRepository
			.persist(new Fruit(null, "Grapefruit", "Summer fruit"))
			.replaceWith(this.fruitRepository.findByName("Grapefruit"))
	)
		.await()
		.atMost(Duration.ofSeconds(10));

	assertThat(fruit)
		.isNotNull()
		.extracting(Fruit::getName, Fruit::getDescription)
		.containsExactly("Grapefruit", "Summer fruit");

	assertThat(fruit.getId())
		.isNotNull()
		.isGreaterThan(2L);
}
```

```java
@Test
@TestReactiveTransaction
public void findByName() {
	Fruit fruit = this.fruitRepository
			.persist(new Fruit(null, "Grapefruit", "Summer fruit"))
			.replaceWith(this.fruitRepository.findByName("Grapefruit"))
			.subscribe().withSubscriber(UniAssertSubscriber.create())
			.awaitSubscription(Duration.ofSeconds(5))
			.awaitItem(Duration.ofSeconds(10))
			.getItem();

	assertThat(fruit)
		.isNotNull()
		.extracting(Fruit::getName, Fruit::getDescription)
		.containsExactly("Grapefruit", "Summer fruit");

	assertThat(fruit.getId())
		.isNotNull()
		.isGreaterThan(2L);
}
```

What seems to work is
```java
@Test
@TestReactiveTransaction
public void findByName(UniAsserter asserter) {
	asserter.assertThat(() -> this.fruitRepository
		.persist(new Fruit(null, "Grapefruit", "Summer fruit"))
		.replaceWith(this.fruitRepository.findByName("Grapefruit")),
		fruit -> {
			assertThat(fruit)
				.isNotNull()
				.extracting(Fruit::getName, Fruit::getDescription)
				.containsExactly("Grapefruit", "Summer fruit");

			assertThat(fruit.getId())
				.isNotNull()
				.isGreaterThan(2L);
		}
	);
}
```

But then this means I have to bring in a new `quarkus-junit5-vertx` dependency and now use some assertion framework (`UniAsserter`?) in all of my tests? This just doesn't seem like a good trade-off to me where I have to completely re-write all my tests just because I want to take advantage of an annotation? The `UniAsserter` thing doesn't work in `@BeforeEach` or `@AfterEach` methods either.

What if I could tag my test class/methods with `@Blocking`? That doesn't seem to do anything now, but could it?

**Comment by geoand** [comment]
> The `UniAsserter` thing doesn't work in `@BeforeEach` or `@AfterEach` methods either.

What exactly would you be asserting in n `@BeforeEach` or `@AfterEach`? 
Asking because I want to understand the use case

> What if I could tag my test class/methods with `@Blocking`? That doesn't seem to do anything now, but could it?

Nope, that can't be done

**Comment by edeandrea** [comment]
> What exactly would you be asserting in `@BeforeEach` or `@AfterEach`?
> Asking because I want to understand the use case.
> We can likely add support for this, but I want to figure out if it's worth it

This is a dumbed down example, but if I have something like this:
```java
@QuarkusTest
class FruitRepositoryTests {
	@Inject
	FruitRepository fruitRepository;

	@BeforeEach
	public void beforeEach() {
				this.fruitRepository.count()
					.subscribe().withSubscriber(UniAssertSubscriber.create())
					.awaitSubscription(Duration.ofSeconds(5))
					.assertSubscribed()
					.awaitItem(Duration.ofSeconds(5))
					.assertItem(2L)
					.assertCompleted();
	}

	@Test
	public void doTest() {
		assertThat(true).isTrue();
	}
}
```

This works fine, as well as if I have a test which uses `@TestReactiveTransaction` in the mix of tests:
```java
@QuarkusTest
class FruitRepositoryTests {
	@Inject
	FruitRepository fruitRepository;

	@BeforeEach
	public void beforeEach() {
				this.fruitRepository.count()
					.subscribe().withSubscriber(UniAssertSubscriber.create())
					.awaitSubscription(Duration.ofSeconds(5))
					.assertSubscribed()
					.awaitItem(Duration.ofSeconds(5))
					.assertItem(2L)
					.assertCompleted();
	}

	@Test
	@TestReactiveTransaction
	public void findByName(UniAsserter asserter) {
		asserter.assertThat(() -> this.fruitRepository
			.persist(new Fruit(null, "Grapefruit", "Summer fruit"))
			.replaceWith(this.fruitRepository.findByName("Grapefruit")),
			fruit -> {
				assertThat(fruit)
					.isNotNull()
					.extracting(Fruit::getName, Fruit::getDescription)
					.containsExactly("Grapefruit", "Summer fruit");

				assertThat(fruit.getId())
					.isNotNull()
					.isGreaterThan(2L);
			}
		);
	}
}
```

The `beforeEach` does work. If I move the `@TestReactiveTransaction` to the class instead of on the individual method though, then it doesn't work, and I'm also not able to inject the `UniAsserter` into the `beforeEach` method.
```java
@QuarkusTest
@TestReactiveTransaction
class FruitRepositoryTests {
	@Inject
	FruitRepository fruitRepository;

        @BeforeEach
	public void beforeEachFails(UniAsserter asserter) {
		asserter.assertEquals(this.fruitRepository::count, 2L);
	}

        @BeforeEach
	public void beforeEach2AlsoFails() {
				this.fruitRepository.count()
					.subscribe().withSubscriber(UniAssertSubscriber.create())
					.awaitSubscription(Duration.ofSeconds(5))
					.assertSubscribed()
					.awaitItem(Duration.ofSeconds(5))
					.assertItem(2L)
					.assertCompleted();
	}

        @BeforeEach
        public void beforeEach3AlsoFails() {
                var count = this.fruitRepository.count()
			.await().atMost(Duration.ofSeconds(5));
		
		assertThat(count)
			.isEqualTo(2L);
        }

	@Test
	public void findByName(UniAsserter asserter) {
		asserter.assertThat(() -> this.fruitRepository
			.persist(new Fruit(null, "Grapefruit", "Summer fruit"))
			.replaceWith(this.fruitRepository.findByName("Grapefruit")),
			fruit -> {
				assertThat(fruit)
					.isNotNull()
					.extracting(Fruit::getName, Fruit::getDescription)
					.containsExactly("Grapefruit", "Summer fruit");

				assertThat(fruit.getId())
					.isNotNull()
					.isGreaterThan(2L);
			}
		);
	}
}
```

fails with
```shell

java.lang.RuntimeException: Unsupported return type void in method public void org.acme.repository.FruitRepositoryTests.beforeEach(io.quarkus.test.junit.vertx.UniAsserter): only Uni is supported when using @ReactiveTransaction if you are running on a VertxThread

	at io.quarkus.hibernate.reactive.panache.common.runtime.ReactiveTransactionalInterceptorBase.intercept(ReactiveTransactionalInterceptorBase.java:39)
	at io.quarkus.hibernate.reactive.panache.common.runtime.TestReactiveTransactionalInterceptorGenerated_Bean.intercept(TestReactiveTransactionalInterceptorGenerated_Bean.zig:275)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.repository.FruitRepositoryTests_Subclass.beforeEach(FruitRepositoryTests_Subclass.zig:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.vertx.RunOnVertxContextTestMethodInvoker$RunTestMethodOnContextHandler.doRun(RunOnVertxContextTestMethodInvoker.java:129)
	at io.quarkus.test.junit.vertx.RunOnVertxContextTestMethodInvoker$RunTestMethodOnContextHandler.handle(RunOnVertxContextTestMethodInvoker.java:118)
	at io.quarkus.test.junit.vertx.RunOnVertxContextTestMethodInvoker$RunTestMethodOnContextHandler.handle(RunOnVertxContextTestMethodInvoker.java:89)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:37)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I think I've discovered that the actual problem here is with having the `@TestReactiveTransaction` at the class level. If I keep it to every method I think its fine, unless my `@BeforeEach` or `@AfterEach` method does something that requires a transaction, which I could think of use cases that it might want to (i.e. set up the database in some way before each test runs).

**Comment by geoand** [comment]
Thanks for the detailed description. It will be a while before I look into this however, with PTO coming soon

**Comment by edeandrea** [comment]
You know me - I write novels

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/19159 will allow the use of  the `UniAsserter` in `@BeforeEach` and `@AfterEach`

**Comment by edeandrea** [comment]
That surely was a while before you looked into it...A whole weekend! :)

**Comment by geoand** [comment]
I turned out to be much easier than I thought :)

**Comment by edeandrea** [comment]
FWIW I still think asking uses to learn "yet another" testing framework, after they've just learned how to use `AssertSubscriber`/`UniAssertSubscriber` is a bit much. Now they have to learn this new `UniAsserter` thing.

What if I need to assert on a `Multi` in a reactive transaction?

**Comment by geoand** [comment]
> FWIW I still think asking uses to learn "yet another" testing framework, after they've just learned how to use `AssertSubscriber`/`UniAssertSubscriber`, is a bit much. Now they have to learn this new `UniAsserter` thing.
> 

I know, but as I said before, that's the price you have to pay to use HR in tests themselves.

> What if I need to assert on a `Multi` in a reactive transaction?

If you have some specific (non theoretical) use case in mind, please open an enhancement issue

**Comment by edeandrea** [comment]
I opened #19173
