### ISSUE TITLE
Quarkus Consul Config :: Enable .yaml support

### ISSUE THREAD

**Issue by gozus19p** [quarkusio/quarkus#19127]
### Description

Hi all,

I am opening this issue in order to ask for an improvement. So, let's introduce the topic.

I am migrating from Spring Boot to Quarkus. My Spring application makes use of Spring Cloud Consul, in order to handle configuration. The entire configuration deployed on Consul is made in .yaml format.

I am not able to load properties written in .yaml extension from Consul to Quarkus.

If I try to import that key as `quarkus.consul-config.properties-value-keys` I get the following error:

```
java.lang.RuntimeException: Key 'my/consul/path/application.yaml' not found in Consul
    at io.quarkus.consul.config.runtime.ConsulConfigSourceProvider$1.accept(ConsulConfigSourceProvider.java:66)
    at io.quarkus.consul.config.runtime.ConsulConfigSourceProvider$1.accept(ConsulConfigSourceProvider.java:56)
    at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
    at io.smallrye.mutiny.operators.uni.UniOnItemConsume$UniOnItemComsumeProcessor.invokeEventHandler(UniOnItemConsume.java:77)
    at io.smallrye.mutiny.operators.uni.UniOnItemConsume$UniOnItemComsumeProcessor.onItem(UniOnItemConsume.java:42)
    at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
    at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
    (...)
```

If I try to import it as `quarkus.consul-config.raw-properties-value-keys`, all goes fine until I try to access the single property by `@ConfigProperty(name = "consultest")`:

```
java.util.NoSuchElementException: SRCFG00014: The config property consultest is required but it could not be found in any config source
```

I noticed that there is no support for .yaml extension. Could you, please, add it?

More details about the use case can be found [here](https://stackoverflow.com/questions/68576894/quarkus-consul-config-how-to-inject-application-yaml-file-from-consul-agent?noredirect=1#comment121214089_68576894).

Feel free to ask me for further details! Looking forward to hear from you.

### Implementation ideas

It could be added a `ConsulYamlConfigSource` that extends `MapBackedConfigSource` inside `io.quarkus.consul.config.runtime.ResponseConfigSourceUtil`.

It could be used "Snake Yaml" in `CosulYamlConfigSource`.

Also, another entry could be added to `io.quarkus.consul.config.runtime.ValueType` (maybe `YAML`), in order to enhance `if-else` logic wrote on `io.quarkus.consul.config.runtime.ResponseConfigSourceUtil:37`.

**Comment by geoand** [comment]
Thanks for reporting!

**Comment by radcortez** [comment]
Closing in favor of https://github.com/quarkiverse/quarkus-consul-config/issues/7.
