### ISSUE TITLE
Does not start with JDK12

### ISSUE THREAD

**Issue by crivera** [quarkusio/quarkus#1917]
Hi

i tried to run a project today with JDK 12 and got the following error:

`
09:48:42,438 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.RuntimeException: org.jboss.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingStaticInit threw an exception: java.lang.Error: java.lang.NoSuchFieldException: override
        [error]: Build step io.quarkus.arc.deployment.RuntimeBeanProcessor#build threw an exception: java.lang.NoClassDefFoundError: Could not initialize class org.jboss.classfilewriter.DefaultClassFactory
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:134)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:108)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: org.jboss.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingStaticInit threw an exception: java.lang.Error: java.lang.NoSuchFieldException: override
        [error]: Build step io.quarkus.arc.deployment.RuntimeBeanProcessor#build threw an exception: java.lang.NoClassDefFoundError: Could not initialize class org.jboss.classfilewriter.DefaultClassFactory
        at org.jboss.builder.Execution.run(Execution.java:123)
        at org.jboss.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:136)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:110)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:99)
        ... 2 more
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class org.jboss.classfilewriter.DefaultClassFactory
                at org.jboss.classfilewriter.ClassFile.defineInternal(ClassFile.java:298)
                at org.jboss.classfilewriter.ClassFile.define(ClassFile.java:277)
                at org.jboss.invocation.proxy.AbstractClassFactory.defineClass(AbstractClassFactory.java:200)
                at org.jboss.invocation.proxy.AbstractClassFactory.newInstance(AbstractClassFactory.java:263)
                at org.jboss.invocation.proxy.ProxyFactory.newInstance(ProxyFactory.java:270)
                at io.quarkus.deployment.recording.BytecodeRecorderImpl$MethodRecorder.getRecordingProxy(BytecodeRecorderImpl.java:190)
                at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:150)
                at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFrom$64(ExtensionLoader.java:411)
                at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:502)
                at org.jboss.builder.BuildContext.run(BuildContext.java:413)
                at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
                at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1382)
                at java.base/java.lang.Thread.run(Thread.java:835)
                at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.Error: java.lang.NoSuchFieldException: override
        at org.jboss.classfilewriter.DefaultClassFactory$1.run(DefaultClassFactory.java:55)
        at org.jboss.classfilewriter.DefaultClassFactory$1.run(DefaultClassFactory.java:44)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:551)
        at org.jboss.classfilewriter.DefaultClassFactory.<init>(DefaultClassFactory.java:44)
        at org.jboss.classfilewriter.DefaultClassFactory.<clinit>(DefaultClassFactory.java:38)
        at org.jboss.classfilewriter.ClassFile.defineInternal(ClassFile.java:298)
        at org.jboss.classfilewriter.ClassFile.define(ClassFile.java:277)
        at org.jboss.invocation.proxy.AbstractClassFactory.defineClass(AbstractClassFactory.java:200)
        at org.jboss.invocation.proxy.AbstractClassFactory.newInstance(AbstractClassFactory.java:263)
        at org.jboss.invocation.proxy.ProxyFactory.newInstance(ProxyFactory.java:270)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl$MethodRecorder.getRecordingProxy(BytecodeRecorderImpl.java:190)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:150)
        at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFrom$64(ExtensionLoader.java:411)
        at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:502)
        at org.jboss.builder.BuildContext.run(BuildContext.java:413)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1382)
        at java.base/java.lang.Thread.run(Thread.java:835)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.NoSuchFieldException: override
        at java.base/java.lang.Class.getDeclaredField(Class.java:2417)
        at org.jboss.classfilewriter.DefaultClassFactory$1.run(DefaultClassFactory.java:53)
        ... 20 more
`

**Comment by gsmet** [comment]
Yes, we do not support JDK 12 for now. See https://github.com/quarkusio/quarkus/issues/1534 for a previous issue about it.

For now, we recommend to use LTS versions (11 or 8).

Closing this one as a duplicate.
