### ISSUE TITLE
quarkus-keycloak-admin-client throws ClassCastException on startup

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#19241]
### Describe the bug

When adding the keycloak-admin-client to a project, it can't be started anymore as it throws a ClassCastException:

```
2021-08-05 08:52:49,867 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:98)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:182)
	... 14 more
Caused by: java.lang.ExceptionInInitializerError
	at org.jboss.resteasy.core.ConstructorInjectorImpl.constructOutsideRequest(ConstructorInjectorImpl.java:250)
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:209)
	at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:37)
	at org.jboss.resteasy.core.providerfactory.Utils.createProviderInstance(Utils.java:102)
	at org.jboss.resteasy.core.providerfactory.CommonProviders.processProviderContracts(CommonProviders.java:87)
	at org.jboss.resteasy.core.providerfactory.ClientHelper.processProviderContracts(ClientHelper.java:104)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.processProviderContracts(ResteasyProviderFactoryImpl.java:841)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerProvider(ResteasyProviderFactoryImpl.java:829)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerProvider(ResteasyProviderFactoryImpl.java:816)
	at io.quarkus.restclient.runtime.RestClientRecorder.registerProviders(RestClientRecorder.java:66)
	at io.quarkus.restclient.runtime.RestClientRecorder.registerProviders(RestClientRecorder.java:56)
	at io.quarkus.restclient.runtime.RestClientRecorder.initializeResteasyProviderFactory(RestClientRecorder.java:43)
	at io.quarkus.deployment.steps.RestClientProcessor$registerProviders1597664724.deploy_0(RestClientProcessor$registerProviders1597664724.zig:416)
	at io.quarkus.deployment.steps.RestClientProcessor$registerProviders1597664724.deploy(RestClientProcessor$registerProviders1597664724.zig:40)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:162)
	... 14 more
Caused by: java.lang.ClassCastException: class org.jboss.resteasy.resteasy_jaxrs.i18n.Messages_$bundle_en_US
	at java.base/java.lang.Class.asSubclass(Class.java:3640)
	at org.jboss.logging.Messages.doGetBundle(Messages.java:80)
	at org.jboss.logging.Messages.getBundle(Messages.java:59)
	at org.jboss.logging.Messages.getBundle(Messages.java:46)
	at org.jboss.resteasy.resteasy_jaxrs.i18n.Messages.<clinit>(Messages.java:30)
	... 29 more

2021-08-05 08:52:49,904 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
```

This occures already in a small application with not many dependencies. I have following dependencies in the gradle file:

```
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-container-image-jib'
    implementation 'io.quarkus:quarkus-rest-client'
    implementation 'io.quarkus:quarkus-rest-client-jackson'
    implementation 'io.quarkus:quarkus-keycloak-admin-client'
    implementation 'io.quarkus:quarkus-config-yaml'

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
```

### Expected behavior

It should start and the keycloak-admin-client should be usable.

### Actual behavior

An exeption is thrown when trying to start the application in dev-mode.

### How to Reproduce?

Just add `io.quarkus:quarkus-keycloak-admin-client` to any project

### Output of `java -version`

11.0.11

### Quarkus version or git rev

2.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.1.1

**Comment by geoand** [comment]
cc @sberyozkin

**Comment by gsmet** [comment]
Please provide a reproducer (small project reproducing the issue) so that we can have a look. Thanks!

**Comment by joggeli34** [comment]
I created a project from code.quarkus.io with only adding the keycloak-admin-client. It seams that the maven-version is starting, but the one with gradle throws the exception.

[keycloak-admin-client-gradle.zip](https://github.com/quarkusio/quarkus/files/6943947/keycloak-admin-client-gradle.zip)
[keycloak-admin-client-maven.zip](https://github.com/quarkusio/quarkus/files/6943948/keycloak-admin-client-maven.zip)

**Comment by joggeli34** [comment]
With version 2.1.2.Final it seams to be fixed

**Comment by gsmet** [comment]
Thanks for the followup!
