### ISSUE TITLE
Rest Client java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0 when setting http.nonProxyHosts

### ISSUE THREAD

**Issue by andrzejszywala** [quarkusio/quarkus#19240]
### Describe the bug

I have REST Client injected to my resource class. 
```
@Path("/hello")
public class GreetingResource {
	
    @Inject
    @RestClient
    HelloResourceClient helloResourceClient;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello RESTEasy";
    }
}
```

When I run appliaction without proxy settings i works fine but when I set proxy parameters `-Dhttps.proxyHost=proxy.acme.com -Dhttps.proxyPort=3128 -Dhttp.proxyHost=proxy.acme.com -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts="*.acme.com|*.acme.app"` it throws an exception:
```
RoutingContext failure (500): org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:247)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:270)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:302)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:318)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:433)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:446)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:269)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:266)
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:52)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:71)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:401)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 15 more
Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.acme.com
```

This same appliaction with proxy parameters on quarkus 1.13.7.Final works fine.

### Expected behavior

Tests should pass

### Actual behavior

Exception 

[io.ver.ext.web.RoutingContext] (executor-thread-0) RoutingContext failure (500): org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:247)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:270)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:302)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:318)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:433)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:446)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:269)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:266)
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:52)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:71)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:401)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 15 more
Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.acme.com
^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2202)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
        at io.quarkus.restclient.runtime.QuarkusRestClientBuilder.build(QuarkusRestClientBuilder.java:276)
        at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:69)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.create(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:189)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.get(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:220)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.get(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:243)
        at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:230)
        ... 33 more

2021-08-05 07:37:29,577 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello failed, error id: 8bb16a4e-90f9-4381-a186-098a07ae0ba2-1: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error injecting org.acme.HelloResourceClient org.acme.GreetingResource.helloResourceClient
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:247)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:270)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:302)
        at org.acme.GreetingResource_Bean.get(GreetingResource_Bean.zig:318)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:433)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:446)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:269)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:266)
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:52)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:71)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:401)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 15 more
Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.acme.com
^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2202)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
        at io.quarkus.restclient.runtime.QuarkusRestClientBuilder.build(QuarkusRestClientBuilder.java:276)
        at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:69)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.create(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:189)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.get(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:220)
        at org.acme.HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.get(HelloResourceClient_07d854618b12320d307fde8d12ba24df9c1db29b_Synthetic_Bean.zig:243)
        at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
        at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:230)
        ... 33 more

### How to Reproduce?

1. Extract sample appliaction 
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/6936189/code-with-quarkus.zip)
2. Run mvnw test -Dhttps.proxyHost=proxy.acme.com -Dhttps.proxyPort=3128 -Dhttp.proxyHost=proxy.acme.com -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts="*.acme.com|*.acme.app"

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18363.1556]

### Output of `java -version`

openjdk version "11.0.9.1" 2020-11-04 LTS OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)

### Quarkus version or git rev

2.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\Users\aszywala\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1 Java version: 11.0.9.1, vendor: Amazon.com Inc., runtime: c:\jdk\jdk11.0.9_12 Default locale: pl_PL, platform encoding: Cp1250 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
cc @jamezp

**Comment by gsmet** [comment]
The upstream is incorrect but we can at least fix our local copy.

I created a PR but I slightly changed the semantic so I would like for @michalszynkiewicz to check the PR.

**Comment by jamezp** [comment]
@gsmet As I'm still learning the RESTEasy code base where in the upstream is this incorrect? The stack trace doesn't look like it's coming from RESTEasy at all.

**Comment by gsmet** [comment]
@jamezp the Quarkus class is more or less a copy of the original RESTEasy one. You have the same error here: https://github.com/resteasy/Resteasy/blob/main/resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java#L256 .

`http.nonProxyHosts` is not a regexp pattern, it uses `*` as a wildcard so it can't be treated as such.

See my proposal for a fix here: https://github.com/quarkusio/quarkus/pull/19261/files .

But I'm not familiar at all with this code so better wait for @michalszynkiewicz to vouch for it.

**Comment by jamezp** [comment]
Right yeah. I'm not sure why a pattern was used there. I've filed a JIRA to get this fixed in RESTEasy https://issues.redhat.com/browse/RESTEASY-2984.
