### ISSUE TITLE
rest-client-reactive cannot have truststores containing keys

### ISSUE THREAD

**Issue by antonwiens** [quarkusio/quarkus#19268]
### Describe the bug

When using a rest-client-reactive and configuring keystores and truststores, the truststore cannot contain keys. It will result in an error:

```
io.vertx.core.VertxException: java.security.UnrecoverableKeyException: Get Key failed: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
2021-08-05T08:57:56.413134207Z 	at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:467)
2021-08-05T08:57:56.413138961Z 	at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:456)
2021-08-05T08:57:56.413142387Z 	at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:494)
2021-08-05T08:57:56.413145608Z 	at io.vertx.core.net.impl.NetClientImpl.<init>(NetClientImpl.java:83)
2021-08-05T08:57:56.413149154Z 	at io.vertx.core.http.impl.HttpClientImpl.<init>(HttpClientImpl.java:170)
2021-08-05T08:57:56.413154869Z 	at io.vertx.core.impl.VertxImpl.createHttpClient(VertxImpl.java:340)
2021-08-05T08:57:56.413158225Z 	at io.vertx.core.impl.VertxImpl.createHttpClient(VertxImpl.java:347)
2021-08-05T08:57:56.413161361Z 	at org.jboss.resteasy.reactive.client.impl.ClientImpl.<init>(ClientImpl.java:116)
2021-08-05T08:57:56.413164756Z 	at org.jboss.resteasy.reactive.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:163)
2021-08-05T08:57:56.413169079Z 	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:265)
2021-08-05T08:57:56.413172851Z 	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.build(RestClientCDIDelegateBuilder.java:76)
2021-08-05T08:57:56.413176712Z 	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.createDelegate(RestClientCDIDelegateBuilder.java:57)
2021-08-05T08:57:56.413192979Z 	at io.quarkus.rest.client.reactive.runtime.RestClientReactiveCDIWrapperBase.<init>(RestClientReactiveCDIWrapperBase.java:16)
...
```

I created a reproducer project with 3 different clients and configurations where only the one with client keys in the truststore fails:

[reproducer.zip](https://github.com/quarkusio/quarkus/files/6945363/reproducer.zip)

Just execute the tests.

I got to this problem because i updated a project from quarkus 1.12.0 to 2.0.3 and changed from normal rest-client to rest-client-reactive.

The problem still exists in 2.1.1. (see reproducer)

Can someone please look into this?

### Quarkus version or git rev

2.1.1

**Comment by famod** [comment]
Just to make sure: What do you mean exactly when you say client keys? Private keys? Key pairs?
A trust store should generally only contain public keys/certs, as far as I'm concerned.

**Comment by antonwiens** [comment]
Sorry, i was away the last two weeks. I meant keypairs / private keys.
It should not contain keys, but it used to work with keys, now its no longer working.

**Comment by michalszynkiewicz** [comment]
Rest Client Reactive uses Vert.x HTTP client underneath and is handling the certificate entirely differently than the classic Rest Client. 
This sounds like it worked by accident for the classic variant, I don't think we should add support for it in the reactive one.

**Comment by famod** [comment]
I'll close this as per the above statement.

@antonwiens you are of course free to request an enhancement upstream over at https://github.com/eclipse-vertx/vert.x
If it get's adjusted there, it should end up working automatically in Quarkus once vertx is updated.
