### ISSUE TITLE
RESTEasy reactive Multipart NoClassDefFoundError

### ISSUE THREAD

**Issue by victor-costa-avancee** [quarkusio/quarkus#19275]
### Describe the bug

I am currently migrating an application to RESTEasy reactive and I stumbled a NoClassDefFoundError on a Multipart endpoint. I think the issue is that I am importing the DTO from an external module. I can reproduce this using the classes on the RESTEasy reactive documentation.

### Expected behavior

The multipart request is handled normally.

### Actual behavior

```
17:30:34 INFO  traceId=, parentId=, spanId=, sampled= [io.ve.ex.we.RoutingContext] (vert.x-eventloop-thread-10) RoutingContext failure (500): java.lang.NoClassDefFoundError: com/avancee/business/common/exception/model/FormData_generated_populator
	at com.avancee.business.common.exception.model.FormData.__quarkus_rest_inject(FormData.java)
	at org.jboss.resteasy.reactive.server.core.parameters.InjectParamExtractor.extractParameter(InjectParamExtractor.java:25)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:38)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:14)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:133)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:80)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:261)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:22)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1.execute(VertxResteasyReactiveRequestContext.java:64)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:79)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:47)
	at org.jboss.resteasy.reactive.server.core.multipart.MultiPartParserDefinition$MultiPartUploadHandler$NonBlockingParseTask.done(MultiPartParserDefinition.java:387)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$5.handle(VertxResteasyReactiveRequestContext.java:245)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$5.handle(VertxResteasyReactiveRequestContext.java:239)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
	at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:557)
	at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:125)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:227)
	at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:280)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:37)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

17:30:34 ERROR traceId=, parentId=, spanId=, sampled= [io.qu.ve.ht.ru.QuarkusErrorHandler] (vert.x-eventloop-thread-10) HTTP Request to /multipart/form failed, error id: 0d30a16d-a658-4967-a54b-b76b94e58af6-5: java.lang.NoClassDefFoundError: com/avancee/business/common/exception/model/FormData_generated_populator
	at com.avancee.business.common.exception.model.FormData.__quarkus_rest_inject(FormData.java)
	at org.jboss.resteasy.reactive.server.core.parameters.InjectParamExtractor.extractParameter(InjectParamExtractor.java:25)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:38)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:14)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:133)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:80)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:261)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:22)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1.execute(VertxResteasyReactiveRequestContext.java:64)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:79)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:47)
	at org.jboss.resteasy.reactive.server.core.multipart.MultiPartParserDefinition$MultiPartUploadHandler$NonBlockingParseTask.done(MultiPartParserDefinition.java:387)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$5.handle(VertxResteasyReactiveRequestContext.java:245)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$5.handle(VertxResteasyReactiveRequestContext.java:239)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
	at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:557)
	at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:125)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:227)
	at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:280)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:37)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

17:30:34 ERROR traceId=, parentId=, spanId=, sampled= [or.jb.re.re.co.co.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-10) Request failed: java.lang.NoClassDefFoundError: com/avancee/business/common/exception/model/FormData_generated_populator
	at com.avancee.business.common.exception.model.FormData.__quarkus_rest_inject(FormData.java)
	at org.jboss.resteasy.reactive.server.core.parameters.InjectParamExtractor.extractParameter(InjectParamExtractor.java:25)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:38)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:14)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:133)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:80)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:261)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:22)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1.execute(VertxResteasyReactiveRequestContext.java:64)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:79)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:47)
	at org.jboss.resteasy.reactive.server.core.multipart.MultiPartParserDefinition$MultiPartUploadHandler$NonBlockingParseTask.done(MultiPartParserDefinition.java:387)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$5.handle(VertxResteasyReactiveRequestContext.java:245)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$5.handle(VertxResteasyReactiveRequestContext.java:239)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
	at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:557)
	at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:125)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:227)
	at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:280)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:37)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

Endpoint:
```
@Path("multipart")
public class Endpoint {

    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Path("form")
    public Uni<String> form(@MultipartForm FormData formData) {
        return Uni.createFrom().item("ok");
    }
}
```

DTO (in the common-dtos dependency):
```
@NoArgsConstructor
public class FormData {

    @RestForm
    @PartType(MediaType.TEXT_PLAIN)
    public String description;

    @RestForm("image")
    public FileUpload file;
}
```

application.properties
```
...
quarkus.index-dependency.dto-commons.group-id=omitted
quarkus.index-dependency.dto-commons.artifact-id=common-dtos
```

pom.xml
```
       ...
        <dependency>
            <groupId>omitted</groupId>
            <artifactId>common-dtos</artifactId>
            <version>2.1.0.10</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jsonb</artifactId>
        </dependency>
```

### Quarkus version or git rev

2.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f) Maven home: /Users/victorcosta/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3 Java version: 11.0.12, vendor: Amazon.com Inc., runtime: /Users/victorcosta/Library/Java/JavaVirtualMachines/corretto-11.0.12/Contents/Home Default locale: en_PT, platform encoding: UTF-8 OS name: "mac os x", version: "11.2.3", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
Can you please give 2.1.1.Final a try? We had fixed an issue which seems to be the same as the one you are reporting

**Comment by victor-costa-avancee** [comment]
Thanks! Updating solved the problem.

**Comment by geoand** [comment]
Great!
