### ISSUE TITLE
picocli does not register defaultValueProvider references thus breaks in native

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#19289]
### Describe the bug

Have something like:

```
@CommandLine.Command(name = "starfix", mixinStandardHelpOptions = true, defaultValueProvider = YAMLDefaultProvider.class)
```

then if you do not add `@RegisterForReflection` you get an error like:

```
 ./target/starfix-1.0.0-SNAPSHOT-runner
2021-08-08 09:46:46,031 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NoSuchMethodException: dev.starfix.YAMLDefaultProvider.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3517)
	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2691)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5489)
	at io.quarkus.picocli.runtime.PicocliBeansFactory.create(PicocliBeansFactory.java:16)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5512)
	at picocli.CommandLine$DefaultFactory.createDefaultValueProvider(CommandLine.java:5503)
	at picocli.CommandLine$Model$CommandSpec.initDefaultValueProvider(CommandLine.java:7229)
	at picocli.CommandLine$Model$CommandSpec.updateCommandAttributes(CommandLine.java:7218)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11392)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6202)
	at picocli.CommandLine.<init>(CommandLine.java:227)
	at picocli.CommandLine.<init>(CommandLine.java:221)
	at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory.create(DefaultPicocliCommandLineFactory.java:43)
	at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory_ClientProxy.create(DefaultPicocliCommandLineFactory_ClientProxy.zig:155)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer.picocliCommandLine(PicocliCommandLineProducer.java:23)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.create(PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.zig:161)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.zig:191)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.zig:226)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.create(PicocliRunner_Bean.zig:212)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(PicocliRunner_Bean.zig:270)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(PicocliRunner_Bean.zig:305)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:433)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:446)
	at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:59)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
```

### Expected behavior

using the default provider should just work.

**Comment by gsmet** [comment]
I already fixed something similar. I'll fix this one and also have a look at other potential issues.
