### ISSUE TITLE
If Quarkus cannot be started, the TestResourceManager tries to start the resources several times

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#1928]
In the integration main tests, I currently have a failure causing Quarkus to not start.

The `TestResourceManager` has already started the Kafka resource.

But if Quarkus has failed to start, the `ExtensionState` is not saved so we try to start the `TestResourceManager` several times leading to:
```
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.quarkus.example.test.KafkaTestResource.start(KafkaTestResource.java:30)
	at io.quarkus.test.common.TestResourceManager.start(TestResourceManager.java:50)
	... 49 more
```

**Comment by pantaoran** [comment]
I think I have this problem with Quarkus 0.15.0 when running the quickstarts (with slight modifications from playing with the code). Are you sure this is fixed?
