### ISSUE TITLE
RESTEasy reactive endpoint 404

### ISSUE THREAD

**Issue by victor-costa-avancee** [quarkusio/quarkus#19299]
### Describe the bug

When two endpoint with similar URI's are created, one of them returns 404. Ex:
/device-features/{featureId}/permissions
/device-features/{featureId}/actions

### Expected behavior

Both Endpoints return 200

### How to Reproduce?

https://github.com/victor-costa-avancee/resteasy_path_reproducer

### Output of `uname -a` or `ver`

Darwin MBP-de-Vic.localdomain 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

### Quarkus version or git rev

2.1.1.Final

**Comment by victor-costa-avancee** [comment]
I have also noticed that when sending an empty body to a POST Method a JsonbException is thrown.
```2021-08-09 12:36:24,412 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: javax.json.bind.JsonbException: Internal error: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN, STRING, NUMBER, TRUE, FALSE, NULL]
        at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:68)
        at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:51)
        at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:59)
        at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:99)
        at io.quarkus.resteasy.reactive.jsonb.runtime.serialisers.JsonbMessageBodyReader.doReadFrom(JsonbMessageBodyReader.java:55)
        at io.quarkus.resteasy.reactive.jsonb.runtime.serialisers.JsonbMessageBodyReader.readFrom(JsonbMessageBodyReader.java:38)
        at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:108)
        at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:68)
        at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:25)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:133)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:536)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.json.stream.JsonParsingException: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN, STRING, NUMBER, TRUE, FALSE, NULL]
        at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:426)
        at org.glassfish.json.JsonParserImpl.access$1100(JsonParserImpl.java:55)
        at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:414)
        at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:352)
        at org.eclipse.yasson.internal.JsonbRiParser.next(JsonbRiParser.java:141)
        at org.eclipse.yasson.internal.Unmarshaller.getRootEvent(Unmarshaller.java:80)
        at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:58)
        ... 16 more
```

**Comment by stuartwdouglas** [comment]
This is because one is defined at class level, and the other at method level.

If you look at the JAX-RS spec `3.7.2 Request Matching` you can see that the algorithm matches against the class first, then matches on the individual methods. Paths can be 'shared' across classes, but only if the path is considered equal by the sorting algorithm (`Sort E using the number of literal characters5 in each member as the primary key (descending
order), the number of capturing groups as a secondary key (descending order) and the number
of capturing groups with non-default regular expressions (i.e. not ‘([ˆ/]+?)’) as the tertiary key
(descending order).`).

I think RESTEasy classic does not actually follow the spec here, while RR is stricter. 

If you just put `@Path("/device-features")` and the rest of the path on the methods this should work.

**Comment by victor-costa-avancee** [comment]
Ok thanks, had no ideia RESTEasy classic was doing extra stuff. Should I open an issue with the empty body 500?

**Comment by victor-costa-avancee** [comment]
Still In no way the request "/device-features/123/action" should match the class level `@Path("/device-features/{featureId}/permissions")`

**Comment by victor-costa-avancee** [comment]
According to `3.7.2 Request Matching` `1 (c)` `Filter E by matching each member against U as follows:
• Remove members that do not match U .`. According to this, the sorting algorithm you mentioned shouldn't be applied as only one root resource class matches the request

**Comment by stuartwdouglas** [comment]
I see a 404 for /device-features/123/actions with your reproducer.

**Comment by victor-costa-avancee** [comment]
Yes, why is that? Maybe I am not understanding something about your explanation but of the two root resource class that are present in the reproducer, only `@Path("/device-features")` should match that request, and then RR should find the     `@Path("/{featureId}/actions")` method. If you open swagger ui http://localhost:8080/q/swagger-ui/#/Device%20Features/post_device_features__featureId__actions will always return 404

**Comment by stuartwdouglas** [comment]
So according to the spec, when it is looking at class level matches both `/device-features` and `/device-features/{featureId}/permissions` would be in the possible match set, however under the sorting in step e) the longer URL would be considered more specific. In step f) it only considers the first element of the set, which is the longer URL, so the shorter one is no longer considered.

I do agree that this is not ideal, but it is what the spec says (the spec is also wrong, e.g. where it says `By definition, all root resource classes in C′ must be annotated with the same URI path template
modulo variable names.` is incorrect, as it could also be different regular expressions).

**Comment by victor-costa-avancee** [comment]
But shouldn't `R(/device-features/{featureId}/permissions)` be filtered out in step c) when matching against the request? `/device-features/{featureId}/permissions` would then no longer be in the match set. This is what I understood after looking at the JAX-RS 2.1 spec for the first stage of request matching: 

Input U = "/device-features/123/actions"

1.a  E = {}

1.b  Add regular expressions
       R("/device-features/{featureId}/permissions") = "\/device-features\/([^\/]+?)\/permissions(\/.*)?"
       R("/device-features") = "\/device-features"
  so E = { "\/device-features\/([^\/]+?)\/permissions(\/.*)?",  "\/device-features" } 

1.c  Filter E by matching elements against U
  so E = { "\/device-features" }

1.d  Ignore this step since E isn't empty

1.e  No need to sort since E only has one element

1.f  Rmatch = E[0] = "\/device-features"

**Comment by stuartwdouglas** [comment]
Actually you are completely right, I was thinking about how our implementation was working rather than properly reading the spec (unfortunately the algorithm as described in the spec is super slow, so you can't just implement it directly). 

https://github.com/quarkusio/quarkus/pull/19355 will actually take care of this one as well.
