### ISSUE TITLE
Add migration note about using `@ConfigMapping` only for Interfaces

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#19298]
### Description

In https://github.com/quarkusio/quarkus/commit/483c4ff2ab23a1a7e2e2ad0b0c3d1de4d17a1148, we upgraded SmallRye Config to 2.4.3 and it seems that there is no longer possible to use the annotation `@ConfigMapping` on classes, only in interfaces.

Therefore, users that were using:

```
@ConfigMapping(prefix = "person")
public class Person {
    String name;
    int age;
}
```

Before, it worked fine, but now it throws at startup:

```
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (build) on project properties: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: r]: Build step io.quarkus.arc.deployment.ConfigBuildStep#generateConfigClasses threw an exception: java.lang.IllegalStateException: SRCFG00043: The @ConfigMapping annotation can only be placed in interfaces, class io.quarkus.qe.properties.configmapping.Person is a class
Error:  	at io.smallrye.config.ConfigMappingLoader.validateAnnotations(ConfigMappingLoader.java:95)
Error:  	at io.smallrye.config.ConfigMappingLoader.getConfigMappingClass(ConfigMappingLoader.java:44)
Error:  	at io.smallrye.config.ConfigMappingLoader.getConfigMappingInterface(ConfigMappingLoader.java:40)
Error:  	at io.smallrye.config.ConfigMappingLoader.getConfigMappingsMetadata(ConfigMappingLoader.java:34)
Error:  	at io.quarkus.arc.deployment.ConfigBuildStep.generateConfigClasses(ConfigBuildStep.java:289)
```

I think this should be noted in the migration guide for 2.2.

**Comment by rsvoboda** [comment]
CC @radcortez
