### ISSUE TITLE
CDI, Transaction rollback and Hibernate State

### ISSUE THREAD

**Issue by viniciusfcf** [quarkusio/quarkus#19309]
### Describe the bug

I'm trying to migrate an EJB code.
Simple reproducer:
1. `GreetingResource.addAndList()` call `GreetingService.doSomething()` method (with `@Transactional(value = TxType.REQUIRED)`)
2. `GreetingService.doSomething` insert an entity, ant throw a `RuntimeException`
3. GreetingResource catches the exception and `entityManager.createQuery("select u from CustomUser u").getResultList();` returns an empty list

The second method.
1. `GreetingResource.addAndListTransactional()` method (with `@Transactional`) call `GreetingService.doSomething()` method (with `@Transactional(value = TxType.REQUIRED)`)
2. `GreetingService.doSomething` insert an entity, ant throw a RuntimeException
3. GreetingResource catches the exception and `entityManager.createQuery("select u from CustomUser u").getResultList();` returns a list with one element.
4. The entity is not commit in database, it's OK to me.
5. Is this correct? With EJB, an exception would be thrown because the transaction was rolled back. If correct, any suggestions to work around this situation?

### Expected behavior

`GreetingResource.addAndListTransactional()`  should return an emptyList or throw an Exception

### Actual behavior

`GreetingResource.addAndListTransactional()` return a list with one entity.

### How to Reproduce?

1. Clone https://github.com/viniciusfcf/quarkus-issues
2. cd jta-required-hibernate
3. mvn quarkus:dev
4. access: http://localhost:8080/hello/add-and-list-transactional

### Output of `uname -a` or `ver`

Darwin vflorent-mac 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /Users/vflorent/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Users/vflorent/.sdkman/candidates/java/11.0.11.hs-adpt Default locale: pt_BR, platform encoding: UTF-8 OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"

**Comment by mkouba** [comment]
AFAIK the `TxType.REQUIRED` is used by default, so if you annotate your resource method with `@Transactional` then the interceptor begins a new transaction when the resource method is executed and the `doSomething()` invocation continues inside this transaction context. If `doSomething()` throws a `RuntimeException` then the transaction is marked for rollback (i.e. `javax.transaction.Transaction.setRollbackOnly()`) but the actual rollback is perfomed when the resource method completes (i.e. when  `tx.getStatus() == Status.STATUS_MARKED_ROLLBACK)`).

I'm not sure whether it's legal to query the hibernate session after the transaction was marked for rollback though. Also I have no idea how EJB should behave in similar use cases. The difference here is that both the JAX-RS resource and the service are regular CDI beans.

**Comment by viniciusfcf** [comment]
@mkouba EJB throws:

```
Caused by: java.sql.SQLException: IJ031070: Transaction cannot proceed: STATUS_MARKED_ROLLBACK
	at org.jboss.ironjacamar.jdbcadapters@1.4.35.Final//org.jboss.jca.adapters.jdbc.WrapperDataSource.checkTransactionActive(WrapperDataSource.java:272)
	at org.jboss.ironjacamar.jdbcadapters@1.4.35.Final//org.jboss.jca.adapters.jdbc.WrappedConnection.checkTransactionActive(WrappedConnection.java:2005)
	at org.jboss.ironjacamar.jdbcadapters@1.4.35.Final//org.jboss.jca.adapters.jdbc.WrappedConnection.checkStatus(WrappedConnection.java:2020)
	at org.jboss.ironjacamar.jdbcadapters@1.4.35.Final//org.jboss.jca.adapters.jdbc.WrappedConnection.checkTransaction(WrappedConnection.java:1994)
	at org.jboss.ironjacamar.jdbcadapters@1.4.35.Final//org.jboss.jca.adapters.jdbc.WrappedConnection.prepareStatement(WrappedConnection.java:472)
	at org.hibernate@5.3.20.Final//org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
	at org.hibernate@5.3.20.Final//org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	... 165 more
```

**Comment by mkouba** [comment]
@Sanne :point_up_2: ?

**Comment by yrodiere** [comment]
See also #23909. My opinion is the transaction should not be rolled back, because that's not practical. Regardless of what the standard says (we've ignored standards we disagreed with before, we can do it again).

Now, the fact is the transcation *is* marked for rollback. Within that context, frankly I could see the point of either behavior (rejecting any SQL execution or accepting it while keeping in mind it will be rolled back anyway). As far as I know Hibernate ORM doesn't have any problem with either behavior. You can see from the EJB stacktrace that Hibernate ORM did not throw the exception, `org.jboss.ironjacamar.jdbcadapters` did.

So... I would say this behavior is the responsibility of... Agroal, maybe?

Hey @barreiro, WDYT: should Agroal prevent executing statements once a transaction is marked for rollback?
