### ISSUE TITLE
BlockingOperationNotAllowedException in gRPC tests after updating Quarkus from 2.0.1 to 2.1.1

### ISSUE THREAD

**Issue by Shpota** [quarkusio/quarkus#19321]
### Describe the bug

After updating Quarkus from Quarkus 2.0.1 to 2.1.1, all  gRPC tests that have methods annotated with `@Transactional` started failing with `BlockingOperationNotAllowedException`:
```
io.quarkus.runtime.BlockingOperationNotAllowedException: Cannot start a JTA transaction from the IO thread.
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:30)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.testpk.GreeterGrpcService_Subclass.sayHello(GreeterGrpcService_Subclass.zig:172)
	at io.quarkus.grpc.runtime.ServerCalls.oneToOne(ServerCalls.java:29)
	at com.example.bugreport.MutinyGreeterGrpc$MethodHandlers.invoke(MutinyGreeterGrpc.java:100)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.quarkus.grpc.runtime.supports.context.GrpcRequestContextGrpcInterceptor$1.onHalfClose(GrpcRequestContextGrpcInterceptor.java:81)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at io.vertx.grpc.VertxServer$ActualServer.lambda$null$0(VertxServer.java:89)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.grpc.VertxServer$ActualServer.lambda$new$1(VertxServer.java:89)
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:93)
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:86)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.halfClosed(ServerImpl.java:825)
	at io.grpc.internal.AbstractServerStream$TransportState.deframerClosed(AbstractServerStream.java:231)
	at io.grpc.netty.NettyServerStream$TransportState.deframerClosed(NettyServerStream.java:168)
	at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:233)
	at io.grpc.internal.MessageDeframer.closeWhenComplete(MessageDeframer.java:191)
	at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:203)
	at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:258)
	at io.grpc.netty.NettyServerStream$TransportState.inboundDataReceived(NettyServerStream.java:226)
	at io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:494)
	at io.grpc.netty.NettyServerHandler.access$800(NettyServerHandler.java:101)
	at io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:808)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:416)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

1. Create a Quarkus 2.1.1 project with Gradle, Kotlin, gRPC, and Hibernate/Panasche.
2. Add a service definition in protobuf:
```protobuf
syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.example.bugreport";
option java_outer_classname = "HelloWorldProto";

package helloworld;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}
```
3. Add an implementation annotating the method with `@Transactional`
```kotlin
@GrpcService
class GreeterGrpcService(private val managedExecutor: ManagedExecutor) : MutinyGreeterGrpc.GreeterImplBase() {
    @Transactional
    override fun sayHello(request: HelloRequest): Uni<HelloReply> {
        return Uni.createFrom().item(request).emitOn(managedExecutor).map {
            HelloReply.getDefaultInstance()
        }
    }
}
```
4. Add a test
```kotlin
@QuarkusTest
internal class GreeterGrpcServiceTest {

    @Inject
    @field:GrpcClient
    lateinit var service: MutinyGreeterGrpc.MutinyGreeterStub

    @Test
    fun sayHello() {
        service.sayHello(HelloRequest.getDefaultInstance()).await().indefinitely()
    }
}
```
5. Run the test and see the `BlockingOperationNotAllowedException` error

### Output of `java -version`
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

### Quarkus version or git rev

2.1.1.Final

### Additional information

This functionality was working up until Quarkus 2.1.0. Downgrading to 2.0.1 makes the test pass.

**Comment by Shpota** [comment]
The error is also reproducible on the latest 2.1.2.Final.

**Comment by michalszynkiewicz** [comment]
With `@Transactional`, I'm guessing the transaction is started prior to `GreeterGrpcService#sayHello`.
Therefore, the fact that you do `emitOn` in the method doesn't matter.
What you need here is to add `@Blocking` on your method.

**Comment by Shpota** [comment]
Thank you @michalszynkiewicz. This code used to work before Quarkus 2.1.0 without `@Blocking`, do you know why it stopped working? Is it an expected behavior?

**Comment by michalszynkiewicz** [comment]
I'm not sure, it seems like some additional checks for running blocking code on the event loop have been added.

**Comment by gsmet** [comment]
@stuartwdouglas didn't you make things automatically blocking when using @Transactional for RESTEasy Reactive? I remember you talked about it, I don't remember if it was done. If so, would it make sense to do the same for gRPC?

**Comment by stuartwdouglas** [comment]
I did, IMHO it does, @Transactional is inherently blocking as it uses the blocking JTA API's.
