### ISSUE TITLE
Could not start gRPC server 

### ISSUE THREAD

**Issue by hieunc278** [quarkusio/quarkus#19337]
### Describe the bug

1. Open quarkus-quickstarts-main project.
2. Add new class QuickStartApp as implementation of QuarkusApplication.
3. Override run method to start gRPC server
4. Run mvn package -Pnative

This is QuickStartApp file content : 

package io.quarkus.grpc.examples.hello;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.quarkus.runtime.QuarkusApplication;
import io.quarkus.runtime.annotations.QuarkusMain;

import java.io.IOException;

@QuarkusMain
public class QuickStartApp implements QuarkusApplication {

    @Override
    public int run(String... args) throws Exception {
        System.out.println("[Server] Starting QuickStartApp");
        Server server = ServerBuilder.forPort(50053)
                .build();
        try {
            server.start();

            Runtime.getRuntime().addShutdownHook(new Thread( () -> {
                System.out.println("[Server] Receive shutdown request");
                server.shutdown();
                System.out.println("[Server] Shutdown server successful");
            } ));

            server.awaitTermination();
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
        return 0;
    }
}

I tried to add grpc-netty as dependency to pom.xml file but still not run successful.

    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty</artifactId>
      <scope>runtime</scope>
    </dependency>

### Expected behavior

Start built runner successful.

### Actual behavior

Failed to start with this backtrace 

APPLEs-MacBook-Pro:grpc-plain-text-quickstart apple$ ./target/grpc-plain-text-quickstart-1.0.0-SNAPSHOT-runner 
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-08-11 16:08:27,540 INFO  [io.qua.grp.run.GrpcServerRecorder] (vert.x-eventloop-thread-0) Registering gRPC reflection service
2021-08-11 16:08:27,767 INFO  [io.qua.grp.run.GrpcServerRecorder] (vert.x-eventloop-thread-1) gRPC Server started on 0.0.0.0:9000 [SSL enabled: false]
2021-08-11 16:08:27,769 INFO  [io.quarkus] (main) grpc-plain-text-quickstart 1.0.0-SNAPSHOT native (powered by Quarkus 2.1.1.Final) started in 0.255s. Listening on: http://0.0.0.0:8080
2021-08-11 16:08:27,769 INFO  [io.quarkus] (main) Profile prod activated. 
2021-08-11 16:08:27,769 INFO  [io.quarkus] (main) Installed features: [cdi, grpc-client, grpc-server, resteasy, resteasy-mutiny, smallrye-context-propagation, vertx]
[Server] Starting QuickStartApp
2021-08-11 16:08:27,769 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional server found. Try adding a dependency on the grpc-netty or grpc-netty-shaded artifact
	at io.grpc.ServerProvider.provider(ServerProvider.java:44)
	at io.grpc.ServerBuilder.forPort(ServerBuilder.java:41)
	at io.quarkus.grpc.examples.hello.QuickStartApp.run(QuickStartApp.java:16)
	at io.quarkus.grpc.examples.hello.QuickStartApp_ClientProxy.run(QuickStartApp_ClientProxy.zig:129)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:123)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)

2021-08-11 16:08:27,772 INFO  [io.quarkus] (main) grpc-plain-text-quickstart stopped in 0.002s

### Output of `uname -a` or `ver`

Darwin APPLEs-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 11.0.12 2021-07-20 OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08) OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)

### Quarkus version or git rev

2.1.1-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /Users/apple/Documents/setup/apache-maven-3.8.1 Java version: 11.0.12, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0/Contents/Home

**Comment by hieunc278** [comment]
Dear Mr. @cescoffier  and Mr. @michalszynkiewicz,

Could you please review this issue also ?

**Comment by hieunc278** [comment]
Fixed it already
