### ISSUE TITLE
@ConfigMApping SRCFG00013: No Converter registered for class <Clazz>

### ISSUE THREAD

**Issue by silviu-negoita** [quarkusio/quarkus#19371]
### Describe the bug

I have following nested configuration
```
@Data
@ConfigMapping(prefix = "environment")
@Accessors(chain = true)
public class EnvironmentProperties {
    private MysApiProperties mys;
}

@Data
@ConfigMapping(prefix = "environment.mys")
@Accessors(chain = true)
public class MysApiProperties {
    private String baseUrl;
}

```
and yml configuration

```
environment:
  mys:
    base-url: ${MYS_BASE_URL}
```

### Expected behavior

Before upgrading to quarkus 2.x.x, I used `@ConfigProperties`, which worked just fine. Since it is deprecated with current quarkus version, i used `@ConfigMapping`. I expect to work the same.

### Actual behavior

```
Caused by: java.lang.IllegalArgumentException: SRCFG00013: No Converter registered for class com.connectis.mms.domain.model.properties.environment.MysApiProperties
	at io.smallrye.config.SmallRyeConfig.requireConverter(SmallRyeConfig.java:491)
	at io.smallrye.config.ConfigMappingContext.getConverter(ConfigMappingContext.java:113)
	at io.smallrye.config.ConfigMappingContext.lambda$getValueConverter$4(ConfigMappingContext.java:92)
	at io.smallrye.config.ConfigMappingContext$$Lambda$881/0x000000000cf73d60.apply(Unknown Source)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.smallrye.config.ConfigMappingContext.getValueConverter(ConfigMappingContext.java:89)
	at com.connectis.mms.domain.properties.EnvironmentProperties809751763I767990490Impl.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.smallrye.config.ConfigMappingLoader.configMappingObject(ConfigMappingLoader.java:55)
	at io.smallrye.config.ConfigMappingContext.constructGroup(ConfigMappingContext.java:80)
	at io.smallrye.config.ConfigMappingContext.constructRoot(ConfigMappingContext.java:76)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:802)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:785)
	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:54)
	at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:36)
	at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:65)
	at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy_0(ConfigBuildStep$registerConfigClasses-2116437784.zig:172)
	at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy(ConfigBuildStep$registerConfigClasses-2116437784.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:974)
	... 12 more

```

**Comment by radcortez** [comment]
> `@ConfigMapping` can actually only be used on interfaces.

Exactly. In the meanwhile, we added a guard to explicitly state that the annotation only works for interfaces, so the error should clear now.
