### ISSUE TITLE
Gradle error finding subproject dependency version

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#19386]
### Describe the bug

I have a top-level `build.gradle` that specifies the version of all dependencies for the subprojects. When upgrading to 2.1, the version for a dependency in a subproject can no longer be found when a classifier is specified. See the reproducer section for details.

### Expected behavior

Successful build

### Actual behavior

```
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':service3:quarkusDependency'.
        at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.getFailure(DefaultLenientConfiguration.java:148)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFailure(DefaultLenientConfiguration.java:162)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.rethrowFailure(DefaultResolvedConfiguration.java:45)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.getResolvedArtifacts(DefaultResolvedConfiguration.java:83)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolvedConfiguration.getResolvedArtifacts(ErrorHandlingConfigurationResolver.java:337)
        at io.quarkus.gradle.dependency.ConditionalDependenciesEnabler.declareConditionalDependencies(ConditionalDependenciesEnabler.java:44)
        at io.quarkus.gradle.QuarkusPlugin.afterEvaluate(QuarkusPlugin.java:282)
...
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.google.inject:guice:.
Required by:
    project :service3
```

### How to Reproduce?

top level `build.gradle`:
```
dependencies {
  implementation 'com.google.inject:guice:3.0'
}
```

subproject `build.gradle`:
```
dependencies {
  implementation 'com.google.inject:guice' // works

  testImplementation 'com.google.inject:guice::no_aop' // previously worked
  testImplementation group: 'com.google.inject', name: 'guice', classifier: 'no_aop' // previously worked
}
```

### Output of `uname -a` or `ver`

Ubuntu 20.04

### Output of `java -version`

OpenJDK 11.0.11

### Quarkus version or git rev

2.1.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1.1

**Comment by glefloch** [comment]
Thanks for reporting this @mweber03. I will work on that ASAP.

**Comment by glefloch** [comment]
@mweber03, in your top level gradle file, did you set the `dependencies` block in the `allproject{}` or `subprojects{}` block ?

**Comment by mweber03** [comment]
@glefloch It's in the `subprojects` block. Which is where we've always had it.
