### ISSUE TITLE
Document Undertow SSL support

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#1947]
See this question on SO: https://stackoverflow.com/questions/55588382/quarkus-https-restful-service/55591988 .

**Comment by leomrlima** [comment]
Would documentation on how to enable SSL support for native images be suitable here or in a new issue? Currently, the SO link works for me on JVM mode, but for Native mode it throws an error.

I don't know if I'm missing some configuration, or if this is unsupported currently by the tools.

Thanks!

`Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: JKS, provider: SUN, class: sun.security.provider.JavaKeyStore$DualFormatJKS)
	at java.security.Provider$Service.newInstance(Provider.java:1621)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.KeyStore.getInstance(KeyStore.java:848)
	... 23 more
Caused by: java.lang.NoSuchMethodException: sun.security.provider.JavaKeyStore$DualFormatJKS.<init>
	at java.lang.Class.getConstructor0(DynamicHub.java:3082)
	at java.lang.Class.getConstructor(DynamicHub.java:1825)
	at java.security.Provider$Service.newInstance(Provider.java:1594)
`

**Comment by gsmet** [comment]
This has been documented here: https://quarkus.io/guides/http-reference#supporting-secure-connections-with-ssl .
