### ISSUE TITLE
Flaky Keycloak tests potentially related to CL issue

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#19494]
Some of the Keycloak tests (typically `io.quarkus.it.keycloak.BearerOpaqueTokenAuthorizationTest.testSecureAccessSuccessPreferredUsername`) sometimes fail with:

```
2021-08-18 18:45:54,253 ERROR [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router: java.util.ServiceConfigurationError: org.eclipse.microprofile.context.spi.ThreadContextProvider: io.quarkus.arc.runtime.context.ArcContextProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at io.smallrye.context.SmallRyeContextManager$Builder.discoverThreadContextProviders(SmallRyeContextManager.java:276)
	at io.smallrye.context.SmallRyeContextManager$Builder.build(SmallRyeContextManager.java:316)
	at io.smallrye.context.SmallRyeContextManagerProvider.getContextManager(SmallRyeContextManagerProvider.java:48)
	at io.smallrye.context.SmallRyeContextManagerProvider.getContextManager(SmallRyeContextManagerProvider.java:37)
	at io.smallrye.context.SmallRyeContextManagerProvider.getManager(SmallRyeContextManagerProvider.java:97)
	at io.smallrye.context.SmallRyeThreadContext.getCurrentThreadContextOrPropagatedContexts(SmallRyeThreadContext.java:137)
	at io.smallrye.mutiny.context.DefaultContextPropagationInterceptor.getThreadContext(DefaultContextPropagationInterceptor.java:12)
	at io.smallrye.mutiny.context.BaseContextPropagationInterceptor.decorate(BaseContextPropagationInterceptor.java:349)
	at io.smallrye.mutiny.infrastructure.Infrastructure.decorate(Infrastructure.java:346)
	at io.smallrye.mutiny.groups.UniMemoize.until(UniMemoize.java:37)
	at io.smallrye.mutiny.groups.UniMemoize.indefinitely(UniMemoize.java:80)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:101)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:51)
```

Example of failing run: https://github.com/quarkusio/quarkus/pull/19472#issuecomment-901380138 .

/cc @stuartwdouglas

**Comment by stuartwdouglas** [comment]
This might be the same as the issue @famod  had. Can we close this and reopen if it persists after my pr is merged?

**Comment by sberyozkin** [comment]
@gsmet Looks like PR builds are stable now after @stuartwdouglas 's fix went in, so let me indeed close it, please reopen if you spot another failure
