### ISSUE TITLE
run error for qute templating and quarkus 2.2.0.CR1

### ISSUE THREAD

**Issue by weir2010** [quarkusio/quarkus#19525]
### Describe the bug

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Applications/SpringToolSuite4.app/Contents/Eclipse/plugins/org.eclipse.m2e.maven.runtime.slf4j.simple_1.18.0.20210618-2246/jars/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [file:/Applications/SpringToolSuite4.app/Contents/Eclipse/configuration/org.eclipse.osgi/5/0/.cp/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Applications/SpringToolSuite4.app/Contents/Eclipse/plugins/org.eclipse.m2e.maven.runtime.slf4j.simple_1.18.0.20210618-2246/jars/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [file:/Applications/SpringToolSuite4.app/Contents/Eclipse/configuration/org.eclipse.osgi/5/0/.cp/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[INFO] Scanning for projects...
[INFO] 
[INFO] [1m-------------------< [0;36mcom.weir.blog:weirblog-quarkus[0;1m >-------------------[m
[INFO] [1mBuilding weirblog-quarkus 2.0[m
[INFO] [1m--------------------------------[ jar ]---------------------------------[m
[INFO] 
[INFO] [1m--- [0;32mquarkus-maven-plugin:2.2.0.CR1:generate-code[m [1m(default)[m @ [36mweirblog-quarkus[0;1m ---[m
[INFO] 
[INFO] [1m--- [0;32mmaven-resources-plugin:2.6:resources[m [1m(default-resources)[m @ [36mweirblog-quarkus[0;1m ---[m
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2475 resources
[INFO] 
[INFO] [1m--- [0;32mmaven-compiler-plugin:3.8.1:compile[m [1m(default-compile)[m @ [36mweirblog-quarkus[0;1m ---[m
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 41 source files to /Users/weir/git/weirblog-quarkus/weirblog-quarkus/target/classes
[INFO] /Users/weir/git/weirblog-quarkus/weirblog-quarkus/src/main/java/com/weirblog/util/ImageUtils.java: /Users/weir/git/weirblog-quarkus/weirblog-quarkus/src/main/java/com/weirblog/util/ImageUtils.java使用或覆盖了已过时的 API。
[INFO] /Users/weir/git/weirblog-quarkus/weirblog-quarkus/src/main/java/com/weirblog/util/ImageUtils.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[INFO] 
[INFO] [1m--- [0;32mquarkus-maven-plugin:2.2.0.CR1:dev[m [1m(default-cli)[m @ [36mweirblog-quarkus[0;1m ---[m
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ weirblog-quarkus
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/weir/git/weirblog-quarkus/weirblog-quarkus/src/test/resources
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile @ weirblog-quarkus
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/weir/git/weirblog-quarkus/weirblog-quarkus/target/test-classes
Listening for transport dt_socket at address: 5005
Press [h] for more options>
Tests paused
Press [r] to resume testing, [h] for more options>
Press [r] to resume testing, [o] Toggle test output, [h] for more options>
[[34;1mINFO[m] Checking for existing resources in: /Users/weir/git/weirblog-quarkus/weirblog-quarkus/src/main/kubernetes.
2021-08-20 12:36:59,859 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#analyzeTemplates threw an exception: io.quarkus.qute.TemplateException: Parser error in template [photoViewPhone.html] on line 15: empty expression found {content:}
	at io.quarkus.qute.Parser.parserError(Parser.java:503)
	at io.quarkus.qute.Parser.parseExpression(Parser.java:727)
	at io.quarkus.qute.Parser.createPart(Parser.java:764)
	at io.quarkus.qute.Parser.parseExpression(Parser.java:743)
	at io.quarkus.qute.Parser.apply(Parser.java:817)
	at io.quarkus.qute.Parser.flushTag(Parser.java:486)
	at io.quarkus.qute.Parser.tag(Parser.java:293)
	at io.quarkus.qute.Parser.processCharacter(Parser.java:200)
	at io.quarkus.qute.Parser.parse(Parser.java:132)
	at io.quarkus.qute.EngineImpl.load(EngineImpl.java:138)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.quarkus.qute.EngineImpl.getTemplate(EngineImpl.java:116)
	at io.quarkus.qute.deployment.QuteProcessor.analyzeTemplates(QuteProcessor.java:459)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:415)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:275)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:66)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:92)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:441)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:65)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:137)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#analyzeTemplates threw an exception: io.quarkus.qute.TemplateException: Parser error in template [photoViewPhone.html] on line 15: empty expression found {content:}
	at io.quarkus.qute.Parser.parserError(Parser.java:503)
	at io.quarkus.qute.Parser.parseExpression(Parser.java:727)
	at io.quarkus.qute.Parser.createPart(Parser.java:764)
	at io.quarkus.qute.Parser.parseExpression(Parser.java:743)
	at io.quarkus.qute.Parser.apply(Parser.java:817)
	at io.quarkus.qute.Parser.flushTag(Parser.java:486)
	at io.quarkus.qute.Parser.tag(Parser.java:293)
	at io.quarkus.qute.Parser.processCharacter(Parser.java:200)
	at io.quarkus.qute.Parser.parse(Parser.java:132)
	at io.quarkus.qute.EngineImpl.load(EngineImpl.java:138)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.quarkus.qute.EngineImpl.getTemplate(EngineImpl.java:116)
	at io.quarkus.qute.deployment.QuteProcessor.analyzeTemplates(QuteProcessor.java:459)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:116)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:151)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:413)
	... 9 more
Caused by: io.quarkus.qute.TemplateException: Parser error in template [photoViewPhone.html] on line 15: empty expression found {content:}
	at io.quarkus.qute.Parser.parserError(Parser.java:503)
	at io.quarkus.qute.Parser.parseExpression(Parser.java:727)
	at io.quarkus.qute.Parser.createPart(Parser.java:764)
	at io.quarkus.qute.Parser.parseExpression(Parser.java:743)
	at io.quarkus.qute.Parser.apply(Parser.java:817)
	at io.quarkus.qute.Parser.flushTag(Parser.java:486)
	at io.quarkus.qute.Parser.tag(Parser.java:293)
	at io.quarkus.qute.Parser.processCharacter(Parser.java:200)
	at io.quarkus.qute.Parser.parse(Parser.java:132)
	at io.quarkus.qute.EngineImpl.load(EngineImpl.java:138)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.quarkus.qute.EngineImpl.getTemplate(EngineImpl.java:116)
	at io.quarkus.qute.deployment.QuteProcessor.analyzeTemplates(QuteProcessor.java:459)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

2021-08-20 12:36:59,859 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2021-08-20 12:36:59,931 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final

code :
`{@java.util.List<com.weirblog.entity.PhotoImg> photoImgs}
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap beign</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="/css/animate.css" rel="stylesheet" type="text/css">
	<style>
	   blockquote, body, button, dd, dl, dt, fieldset, form, h1, h2, h3, h4, h5, h6, hr, input, legend, li, ol, p, pre, td, textarea, th, ul,img{
		margin: 0;
		padding: 0;
		}
	   body{background:black;overflow:hidden}
	   ul{list-style:none}
	   .clearfix:after{display: block; content: "\20"; height: 0; clear: both; overflow: hidden; visibility: hidden;}
     
	   .img-container li img{}
	   .img-container li {overflow:hidden;float:left;}
	   .large{width:100%;height:100%;position:absolute;top:0px;left:0px;background-color:black}
	</style>
	</head>
  <body>
	<ul class="img-container clearfix" id="container">

	</ul>
	<div class="large animated fadeInDown" id="large_container" style="display:none">
		<img id="large_img">
	</div>
	{#for photoImg in photoImgs}
	<input type="hidden" name="phone_imgs" value="/photo/imgView/{photoImg.imgPath}"/>
	<input type="hidden" name="phone_thumbnails" value="/photo/imgThumbnailView/{photoImg.thumbnail}"/>
	{/for}
	<script src="/js/zepto.min.js"></script>
	<script type="text/javascript" src="/js/blog/photoViewPhone.js"></script>
  </body>
</html>`

### Output of `java -version`

11

### Quarkus version or git rev

2.2.0.CR1

**Comment by weir2010** [comment]
There is a problem with CSS code in HTML    I tried to extract the CSS code  
`blockquote, body, button, dd, dl, dt, fieldset, form, h1, h2, h3, h4, h5, h6, hr, input, legend, li, ol, p, pre, td, textarea, th, ul,img{
		margin: 0;
		padding: 0;
		}
	   body{background:black;overflow:hidden}
	   ul{list-style:none}
	   .clearfix:after{display: block; content: "\20"; height: 0; clear: both; overflow: hidden; visibility: hidden;}
     
	   .img-container li img{}
	   .img-container li {overflow:hidden;float:left;}
	   .large{width:100%;height:100%;position:absolute;top:0px;left:0px;background-color:black}`
use  <link href="/css/photoViewPhone.css" rel="stylesheet" type="text/css">
code run is ok。
