### ISSUE TITLE
better/more informative error than "Not a REST client interface: interface update$PlaylistService" 

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#19556]
### Description

Given:

```
@RegisterRestClient(baseUri = "https://www.googleapis.com/youtube/v3/playlistItems")
    public static interface PlaylistService {

        @GET
        List<String> playlist(@QueryParam("part") String part,
                          @QueryParam("maxResults") int maxResults,
                          @QueryParam("playlistId") String playListId,
                          @QueryParam("key") String key);
    }
```

in a class I get:

```
021-08-21 02:26:44,151 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.IllegalArgumentException: Not a REST client interface: interface update$PlaylistService
	at org.jboss.resteasy.reactive.client.impl.ClientProxies.get(ClientProxies.java:26)
	at org.jboss.resteasy.reactive.client.impl.WebTargetImpl.proxy(WebTargetImpl.java:382)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:273)
	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.build(RestClientCDIDelegateBuilder.java:76)
	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.createDelegate(RestClientCDIDelegateBuilder.java:57)
	at io.quarkus.rest.client.reactive.runtime.RestClientReactiveCDIWrapperBase.<init>(RestClientReactiveCDIWrapperBase.java:16)
	at update$PlaylistService$$CDIWrapper.<init>(update$PlaylistService$$CDIWrapper.zig:21)
	at update$PlaylistService$$CDIWrapper_ClientProxy.<init>(update$PlaylistService$$CDIWrapper_ClientProxy.zig:24)
	at update$PlaylistService$$CDIWrapper_Bean.proxy(update$PlaylistService$$CDIWrapper_Bean.zig:40)
	at update$PlaylistService$$CDIWrapper_Bean.get(update$PlaylistService$$CDIWrapper_Bean.zig:243)
	at update$PlaylistService$$CDIWrapper_Bean.get(update$PlaylistService$$CDIWrapper_Bean.zig:259)
	at update_Bean.create(update_Bean.zig:210)
	at update_Bean.create(update_Bean.zig:293)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
	at update_ClientProxy.arc$delegate(update_ClientProxy.zig:67)
	at update_ClientProxy.run(update_ClientProxy.zig:126)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:123)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
```

despite all the types and annotations matches what is in resteasy reactive client docs.

Could this error message  be a bit more explicit on what makes this not a REST client interface?

**Comment by maxandersen** [comment]
in this case it seem to be that `@javax.ws.rs.Path("/youtube/v3/playlistItems") was missing.
`

**Comment by gastaldi** [comment]
Yeah the error message could be more descriptive, like ` interface update$PlaylistService is not a valid REST Client interface. The @javax.ws.rs.Path annotation is missing`

**Comment by stuartwdouglas** [comment]
Should we really required the path? If it is missing but `@RegisterRestClient` is present we should just default it to '/' IMHO.

**Comment by michalszynkiewicz** [comment]
The interface @maxandersen posted should work.
This should pick it up: https://github.com/quarkusio/quarkus/blob/45d7dbb238d89a3d565828e0915a23f2e6b01917/independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/scanning/ResteasyReactiveScanner.java#L208-L221

What we currently do is we find all the interfaces that have `@Path` either on the class level or on the method level, or have any annotation like `@POST`, etc, on any of the methods.

I'll try to reproduce the problem.

**Comment by maxandersen** [comment]
Could it be one of the dreaded "code assumes every class is in a package" kinda thing ?

**Comment by stuartwdouglas** [comment]
It happens when you have no @Path, but you do have an @RegisterRestClient .

**Comment by michalszynkiewicz** [comment]
https://github.com/quarkusio/quarkus/pull/19572 should fix this
