### ISSUE TITLE
Qute can't find all fields defined on parent interfaces with strict rendering enabled

### ISSUE THREAD

**Issue by wjglerum** [quarkusio/quarkus#19564]
### Describe the bug

Looks like Qute can't find certain fields when you use a nested class hierarchy. 

For example, in our project we extensively use [Immutables](https://immutables.github.io/) for our domain objects. And we use wrappers around primitives, see https://immutables.github.io/immutable.html#wrapper-types

When we use this in combination with checked templates and strict rendering it does not work and Qute complains about incorrect expressions. See the example below:

```java
public interface Wrapper<T> {
    T value();
}

public interface Count extends Wrapper<Integer> {
}

public interface Metrics {

    Count requests();

    Count responses();
}

```
[1] Incorrect expression found: {metrics.responses.value.?:(0)}
	- property/method [value] not found on class [nl.wjglerum.Count] nor handled by an extension method
	- at MetricResource/strict.qute.html:4
	at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {metrics.responses.value.?:(0)}
	- property/method [value] not found on class [nl.wjglerum.Count] nor handled by an extension method
	- at MetricResource/strict.qute.html:4
		at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:176)
		... 11 more
```

However when we don't use checked templating or disable the strict rendering it does work as expected.

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Provided a reproducer here https://github.com/wjglerum/quarkus-qute-strict

### Output of `uname -a` or `ver`

`Darwin Willems-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64`

### Output of `java -version`

```openjdk 11.0.11 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)```

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

`2.1.2.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```

**Comment by wjglerum** [comment]
I noticed this especially after trying the `2.2.0.CR1` release, where expressions in includes and user tags are also checked, see https://github.com/quarkusio/quarkus/pull/18930
