### ISSUE TITLE
#19534 broke backwards compatibility with GraalVM/Mandrel 20.3

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#19645]
### Describe the bug

https://github.com/quarkusio/quarkus/pull/19534 results in the following exception when using GraalVM/Mandrel 20.3

```
java.lang.ClassNotFoundException: com.oracle.svm.core.jdk.JDK16OrEarlier
```

### Expected behavior

Tests and applications should build with GraalVM/Mandrel 20.3.

### Actual behavior

Tests and applications fail to build with GraalVM/Mandrel 20.3.

### How to Reproduce?

Build any integration test/quarkus app using `-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.3-java11`

### Output of `java -version`

11.0.12

### GraalVM version (if different from Java)

20.3

### Quarkus version or git rev

cc16df8dd324cecfedba06aec04c1bf2d17e62f3

### Additional information

Full stack trace:

```
Fatal error:java.lang.TypeNotPresentException: Type com.oracle.svm.core.jdk.JDK16OrEarlier not present
	at java.base/sun.reflect.annotation.TypeNotPresentExceptionProxy.generateException(TypeNotPresentExceptionProxy.java:46)
	at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:86)
	at com.sun.proxy.$Proxy62.onlyWith(Unknown Source)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:883)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:287)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:265)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:919)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:853)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:554)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:469)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: com.oracle.svm.core.jdk.JDK16OrEarlier
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:440)
	at java.base/sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:421)
	at java.base/sun.reflect.annotation.AnnotationParser.lambda$parseClassArray$0(AnnotationParser.java:719)
	at java.base/sun.reflect.annotation.AnnotationParser.parseArrayElements(AnnotationParser.java:747)
	at java.base/sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:718)
	at java.base/sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:532)
	at java.base/sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:356)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:287)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
	at java.base/java.lang.Class.createAnnotationData(Class.java:3757)
	at java.base/java.lang.Class.annotationData(Class.java:3746)
	at java.base/java.lang.Class.getAnnotations(Class.java:3682)
	at com.oracle.svm.hosted.ImageClassLoader.canLoadAnnotations(ImageClassLoader.java:133)
	at com.oracle.svm.hosted.ImageClassLoader.handleClass(ImageClassLoader.java:170)
	at com.oracle.svm.hosted.AbstractNativeImageClassLoaderSupport$ClassInit.handleClassFileName(AbstractNativeImageClassLoaderSupport.java:288)
	at com.oracle.svm.hosted.AbstractNativeImageClassLoaderSupport$ClassInit$1.lambda$visitFile$0(AbstractNativeImageClassLoaderSupport.java:225)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	... 5 more
```

**Comment by gsmet** [comment]
I think we should probably introduce these classes in Mandrel if it's possible for you.

**Comment by zakkak** [comment]
Yes, I have the patch ready, currently testing it with 20.3 and 21.3-dev JDK17.
