### ISSUE TITLE
quarkus-smallrye-opentracing no longer works after a bump to Quarkus 2.1.3.Final

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#19653]
### Describe the bug

I recently bumped Quarkus from `1.13.7.Final` to `2.1.3.Final` in an app that depends on:

```
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-smallrye-opentracing</artifactId>
</dependency>
<dependency>
   <groupId>io.opentracing.contrib</groupId>
   <artifactId>opentracing-jdbc</artifactId>
</dependency>
```

Everything seemed to be running fine locally, but when I deployed the app on OpenShift, this started to show up in the pod logs:

```
2021-08-24 13:14:17,827 WARN  [io.jae.int.rep.RemoteReporter] (jaeger.RemoteReporter-QueueProcessor) FlushCommand execution failed! Repeated errors of this command will not be logged.: io.jaegertracing.internal.exceptions.SenderException: Failed to flush spans.
    at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:115)
    at io.jaegertracing.internal.reporters.RemoteReporter$FlushCommand.execute(RemoteReporter.java:160)
    at io.jaegertracing.internal.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:182)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.jaegertracing.internal.exceptions.SenderException: Could not send 7 spans
    at io.jaegertracing.thrift.internal.senders.UdpSender.send(UdpSender.java:85)
    at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:113)
    ... 3 more
Caused by: org.apache.thrift.transport.TTransportException: Cannot flush closed transport
    at io.jaegertracing.thrift.internal.reporters.protocols.ThriftUdpTransport.flush(ThriftUdpTransport.java:148)
    at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73)
    at org.apache.thrift.TServiceClient.sendBaseOneway(TServiceClient.java:66)
    at io.jaegertracing.agent.thrift.Agent$Client.send_emitBatch(Agent.java:70)
    at io.jaegertracing.agent.thrift.Agent$Client.emitBatch(Agent.java:63)
    at io.jaegertracing.thrift.internal.senders.UdpSender.send(UdpSender.java:83)
    ... 4 more
Caused by: java.net.PortUnreachableException: ICMP Port Unreachable
    at java.base/java.net.PlainDatagramSocketImpl.send(Native Method)
    at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
    at io.jaegertracing.thrift.internal.reporters.protocols.ThriftUdpTransport.flush(ThriftUdpTransport.java:146)
    ... 9 more
```

With `1.13.7.Final`, that warning isn't printed in the log. The only differences between the deployment that works and the one that fails are the Quarkus version and a few mandatory code changes in the opentracing area because of deprecated methods.

I've been unable to reproduce the issue locally so far so I'm not sure I'll be able to provide a minimal reproducer. I'm trying anyway. In the meantime, if someone has an idea about what's causing this, I'm all ears 😃 

### How to Reproduce?

Working on it...

### Output of `java -version`

openjdk 11.0.11 2021-04-20 LTS

### Quarkus version or git rev

2.1.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by pilhuhn** [comment]
I believe that could be closed.
It may be that in the failing code base an extra exporter has been missing like 

```
   <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-opentelemetry-exporter-otlp</artifactId>
      </dependency>
```

**Comment by gsmet** [comment]
Thanks for the followup.
