### ISSUE TITLE
Reactive Messaging WebSockets connector - exception thrown on close

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#19662]
### Describe the bug

The following exception is thrown on application shutdown when using the quarkus websocket connector for reactive messaging:
```
2021-08-25 21:40:56,651 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-40) Uncaught exception received by Vert.x: java.lang.IllegalStateException
        at io.vertx.core.impl.CloseFuture.add(CloseFuture.java:51)
        at io.vertx.core.impl.ContextInternal.addCloseHook(ContextInternal.java:294)
        at io.vertx.core.impl.VertxImpl.scheduleTimeout(VertxImpl.java:524)
        at io.vertx.core.impl.VertxImpl.setTimer(VertxImpl.java:372)
        at io.vertx.core.http.impl.WebSocketImplBase.initiateConnectionCloseTimeout(WebSocketImplBase.java:567)
        at io.vertx.core.http.impl.ServerWebSocketImpl.lambda$close$0(ServerWebSocketImpl.java:149)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:80)
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:172)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:164)
        at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
        at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:132)
        at io.vertx.core.impl.future.PromiseImpl.onComplete(PromiseImpl.java:23)
        at io.vertx.core.http.impl.ServerWebSocketImpl.close(ServerWebSocketImpl.java:145)
        at io.vertx.core.http.impl.WebSocketImplBase.close(WebSocketImplBase.java:143)
        at io.vertx.core.http.impl.Http1xConnectionBase.close(Http1xConnectionBase.java:95)
        at io.vertx.core.http.impl.Http1xServerConnection.close(Http1xServerConnection.java:75)
        at io.vertx.core.net.impl.ConnectionBase.close(ConnectionBase.java:130)
        at io.vertx.core.net.impl.VertxHandler.close(VertxHandler.java:159)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
        at io.netty.channel.AbstractChannelHandlerContext.access$1200(AbstractChannelHandlerContext.java:61)
        at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:611)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

2021-08-25 21:40:56,651 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-36) Uncaught exception received by Vert.x: java.lang.IllegalStateException
        at io.vertx.core.impl.CloseFuture.add(CloseFuture.java:51)
        at io.vertx.core.impl.ContextInternal.addCloseHook(ContextInternal.java:294)
        at io.vertx.core.impl.VertxImpl.scheduleTimeout(VertxImpl.java:524)
        at io.vertx.core.impl.VertxImpl.setTimer(VertxImpl.java:372)
        at io.vertx.core.http.impl.WebSocketImplBase.initiateConnectionCloseTimeout(WebSocketImplBase.java:567)
        at io.vertx.core.http.impl.ServerWebSocketImpl.lambda$close$0(ServerWebSocketImpl.java:149)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:80)
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:172)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:164)
        at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
        at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:132)
        at io.vertx.core.impl.future.PromiseImpl.onComplete(PromiseImpl.java:23)
        at io.vertx.core.http.impl.ServerWebSocketImpl.close(ServerWebSocketImpl.java:145)
        at io.vertx.core.http.impl.WebSocketImplBase.close(WebSocketImplBase.java:143)
        at io.vertx.core.http.impl.Http1xConnectionBase.close(Http1xConnectionBase.java:95)
        at io.vertx.core.http.impl.Http1xServerConnection.close(Http1xServerConnection.java:75)
        at io.vertx.core.net.impl.ConnectionBase.close(ConnectionBase.java:130)
        at io.vertx.core.net.impl.VertxHandler.close(VertxHandler.java:159)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
        at io.netty.channel.AbstractChannelHandlerContext.access$1200(AbstractChannelHandlerContext.java:61)
        at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:611)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by michalszynkiewicz** [comment]
moved to quarkiverse
