### ISSUE TITLE
CacheResult not working in extension

### ISSUE THREAD

**Issue by Crunchy-Muesli** [quarkusio/quarkus#19676]
### Describe the bug

I'm writing an extension and I needed data caching for a method, so I tried using **@CacheResult** from quarkus-cache.
When the method gets called, this exception occurs:

```
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:148)
        at io.quarkus.cache.runtime.CacheResultInterceptor.intercept(CacheResultInterceptor.java:39)
        at io.quarkus.cache.runtime.CacheResultInterceptor_Bean.intercept(CacheResultInterceptor_Bean.zig:330)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
```

And the method body is never reached.
I followed the cache tutorial [here](https://quarkus.io/version/main/guides/cache) and I'm using the same exact code.

I'm kinda new to quarkus so this could very well be a configuration error on my part, apologies in advance.

### Expected behavior

When executing the **intercept** method in **CacheResultInterceptor**, the cache manager contains a list of all the caches declared by the **CacheResult** annotations present in the application.

### Actual behavior

In the interceptor, the cache manager's list of caches is empty, so when it tries to retrieve one by name, the **NoSuchElementException** occurs.

### Output of `uname -a` or `ver`

Linux 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08) OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)

### Quarkus version or git rev

2.1.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by dcdh** [comment]
Hello,

Is it possible to reopen ? Indexing using jandex is working but the usage of AdditionBeanBuildItem is useless because all beans will Indexed even the one we do not want.
I can reproduce it today with a 3.8.1 version.

**Comment by dcdh** [comment]
> Turns out my hunch was correct. The `CacheProcessor` is called, but the runtime part of the code is not indexed.
> 
> To fix this you can simply add something like this in your `ConfigProcessor`:
> 
> ```java
>     @BuildStep
>     IndexDependencyBuildItem index() {
>         return new IndexDependencyBuildItem("example.com", "quarkus-security-example");
>     }
> ```
> 
> If you don't want to hard code the groupId and artifactId, you can get creative and use:
> 
> ```java
>     @BuildStep
>     IndexDependencyBuildItem index(CurateOutcomeBuildItem curateOutcome) {
>         // ArtifactInfoUtil is used in Quarkus Core, but is considered internal and could change
>         Map.Entry<String, String> entry = ArtifactInfoUtil.groupIdAndArtifactId(CustomAuthMechanism.class, curateOutcome);
>         return new IndexDependencyBuildItem(entry.getKey(), entry.getValue());
>     }
> ```

We should only index what we want using AdditionalBeanBuildItem regarding the runtime.

**Comment by dcdh** [comment]
In validateCacheAnnotationsAndProduceCacheNames I would not used a CombinedIndexBuildItem but an ApplicationIndexBuildItem instead (I may be wrong)

**Comment by mkouba** [comment]
> In validateCacheAnnotationsAndProduceCacheNames I would not used a CombinedIndexBuildItem but an ApplicationIndexBuildItem instead (I may be wrong)

Well, the bean classes registered through `AdditionalBeanBuildItem`s are only part of the `BeanArchiveIndexBuildItem`. The `CombinedIndexBuildItem` only contains the classes from the application archives + `IndexDependencyBuildItem`s.

We could try to modify the `CacheProcessor#validateCacheAnnotationsAndProduceCacheNames()` to consume the `BeanArchiveIndexBuildItem#getImmutableIndex()` instead but I'm not sure if there will be no build cycles.

CC @gwenneg

**Comment by dcdh** [comment]
I continue having this issue.

```
ava.util.NoSuchElementException: No value present

	at java.base/java.util.Optional.get(Optional.java:143)
	at io.quarkus.cache.runtime.CacheResultInterceptor.intercept(CacheResultInterceptor.java:48)
	at io.quarkus.cache.runtime.CacheResultInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.damdamdeo.pulse.extension.runtime.encryption.DefaultPassphraseProvider_Subclass.provide(Unknown Source)
	at com.damdamdeo.pulse.extension.runtime.encryption.DefaultPassphraseProvider_ClientProxy.provide(Unknown Source)
```

Good news, got a workaround :)

In my test I have redefine the cache this way and it is working

```java
class CommandHandlerTest {

    @RegisterExtension
    static QuarkusUnitTest runner = new QuarkusUnitTest()
            .withApplicationRoot(jar -> jar.addAsResource("init.sql"))
            .withConfigurationResource("application.properties");

    @Inject
    @CacheName("passphrase")
    Cache cache;
```

https://github.com/dcdh/pulse-extension/blob/master/deployment/src/test/java/com/damdamdeo/pulse/extension/test/CommandHandlerTest.java#L29

But I had to do it the same in integration-tests module https://github.com/dcdh/pulse-extension/blob/master/integration-tests/src/main/java/com/damdamdeo/pulse/extension/it/PulseExtensionResource.java#L39

I am a bit confused regarding integration-tests module

Maybe it should be nice to add it inside the documentation ?

**Comment by dcdh** [comment]
To fix it from an extension side indexing the class using AdditionalIndexedClassesBuildItem is working so I guess we can close it.
If my extension have a WeatherForecastService (taken from guide) in the runtime module it needs to be registered using AdditionalIndexedClassesBuildItem to be indexed and so handled by the cache processor.

A working reproducer for the one who need help https://github.com/dcdh/quarkus-cache-extension-reproducer-19676 done inside `MyExtensionUsingCacheExtensionProcessor`

**Comment by geoand** [comment]
Closing as per the above comment
