### ISSUE TITLE
OpenAPI OASFilter not working in dev mode

### ISSUE THREAD

**Issue by Edubits** [quarkusio/quarkus#1974]
When using a OASFilter this works when normally running, but when ran in dev mode it throws a ClassNotFoundException.

I've made a sample based on the using-openapi-swaggerui quickstart: https://github.com/Edubits/quarkus-quickstarts/tree/openapi-filter

Exception when running `mvn clean compile quarkus:dev`:
```
09:42:11,874 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:118)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:108)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.<clinit>(Unknown Source)
	... 8 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.acme.openapi.OpenApiFilter
	at io.smallrye.openapi.runtime.OpenApiProcessor.getFilter(OpenApiProcessor.java:110)
	at io.quarkus.smallrye.openapi.runtime.SmallRyeOpenApiTemplate.filter(SmallRyeOpenApiTemplate.java:67)
	at io.quarkus.smallrye.openapi.runtime.SmallRyeOpenApiTemplate.access$100(SmallRyeOpenApiTemplate.java:37)
	at io.quarkus.smallrye.openapi.runtime.SmallRyeOpenApiTemplate$1.created(SmallRyeOpenApiTemplate.java:52)
	at io.quarkus.arc.runtime.ArcDeploymentTemplate.initBeanContainer(ArcDeploymentTemplate.java:108)
	at io.quarkus.deployment.steps.ArcAnnotationProcessor$build5.deploy(Unknown Source)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.acme.openapi.OpenApiFilter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at io.smallrye.openapi.runtime.OpenApiProcessor.getFilter(OpenApiProcessor.java:107)
	... 14 more
```

**Comment by gsmet** [comment]
It's a classloader issue in https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-openapi/runtime/src/main/java/io/quarkus/smallrye/openapi/runtime/SmallRyeOpenApiTemplate.java#L67.

@dmlloyd should we use the TCCL, pending any better options?

**Comment by dmlloyd** [comment]
Yes, for now use the TCCL.
