### ISSUE TITLE
Cannot Run Tests With testcontainers 1.16.0

### ISSUE THREAD

**Issue by vu-bui** [quarkusio/quarkus#19775]
### Describe the bug

I cannot execute tests depending on testcontainers version `1.16.0` after upgrading to quarkus `2.1.4.Final`. It seems that testcontainers require `com.github.docker-java` version `3.2.11` in order to run while `quarkus-universe-bom` is referencing to `3.2.8`

I'm not sure if this is the correct place to fix, but I think we can just simply upgrade the dependency version.

I have the workaround for this issue by adding this to my `build.gradle.kts` file
```kotlin
configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "com.github.docker-java") {
            useVersion("3.2.11")
        }
    }
}
```

### Actual behavior

I got this error message as there is no such class `com.github.dockerjava.api.model.DockerObject` in version `3.2.8`
```
Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
    UnixSocketClientProviderStrategy: failed with exception RuntimeException (java.lang.NoClassDefFoundError: com/github/dockerjava/api/model/DockerObject). Root cause ClassNotFoundException (com.github.dockerjava.api.model.DockerObject)
    UnixSocketClientProviderStrategy: failed with exception RuntimeException (java.lang.NoClassDefFoundError: com/github/dockerjava/api/model/DockerObject). Root cause NoClassDefFoundError (com/github/dockerjava/api/model/DockerObject)
As no valid configuration was found, execution cannot continue
HHH000342: Could not obtain connection to query metadata
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:215)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:207)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:135)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:177)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:314)
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:118)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:204)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:470)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:452)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
HHH000342: Could not obtain connection to query metadata
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:109)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:135)
	at org.testcontainers.DockerClientFactory.dockerHostIpAddress(DockerClientFactory.java:350)
	at org.testcontainers.containers.ContainerState.getHost(ContainerState.java:59)
	at org.testcontainers.containers.ContainerState.getContainerIpAddress(ContainerState.java:50)
	at org.testcontainers.containers.PostgreSQLContainer.getJdbcUrl(PostgreSQLContainer.java:86)
	at org.testcontainers.containers.JdbcDatabaseContainer.constructUrlForConnection(JdbcDatabaseContainer.java:241)
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:207)
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:124)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:204)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:470)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:452)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
HHH000342: Could not obtain connection to query metadata
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:109)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:135)
	at org.testcontainers.DockerClientFactory.dockerHostIpAddress(DockerClientFactory.java:350)
	at org.testcontainers.containers.ContainerState.getHost(ContainerState.java:59)
	at org.testcontainers.containers.ContainerState.getContainerIpAddress(ContainerState.java:50)
	at org.testcontainers.containers.PostgreSQLContainer.getJdbcUrl(PostgreSQLContainer.java:86)
	at org.testcontainers.containers.JdbcDatabaseContainer.constructUrlForConnection(JdbcDatabaseContainer.java:241)
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:207)
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:124)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:204)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:470)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:452)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

My project's gradle bom file
```kotlin
dependencies {
    api(enforcedPlatform("io.quarkus:quarkus-universe-bom:2.1.4.Final"))
    api(enforcedPlatform("org.testcontainers:testcontainers-bom:1.16.0"))
}
```

My project's gradle test file
```kotlin
dependencies {
    testImplementation("io.quarkus:quarkus-jacoco")
    testImplementation("io.quarkus:quarkus-junit5")
    testImplementation("io.quarkus:quarkus-junit5-mockito")
    testImplementation("io.rest-assured:kotlin-extensions")
    testImplementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    testImplementation("org.testcontainers:postgresql") // this is where it failed
    testImplementation("com.nhaarman.mockitokotlin2:mockito-kotlin")
}
```

### Output of `uname -a` or `ver`

Darwin local 21.0.0 Darwin Kernel Version 21.0.0: Mon Aug  2 00:18:11 PDT 2021; root:xnu-8019.30.9~9/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### Quarkus version or git rev

2.1.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by gsmet** [comment]
You need to use the Testcontainers version mandated in the Quarkus BOM.

Quarkus 2.2, released tomorrow will use Testcontainers 1.16.

**Comment by vu-bui** [comment]
Thanks for that. There is indeed testcontainers defined in quarkus that I didn't know. Removing the dependencies to testcontainers did work.

**Comment by dicolasi** [comment]
2.2.3.Final  still uses v1.15.3 @gsmet
