### ISSUE TITLE
ClassCastException while using MessageLogger

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#19790]
### Describe the bug

Using the `MessageLogger` feature from JBoss Logging throws a ClassCastException in Quarkus.

```java
Caused by: java.lang.ClassCastException: class org.acme.Messages_$logger
	at java.base/java.lang.Class.asSubclass(Class.java:3640)
	at org.jboss.logging.Logger.doGetMessageLogger(Logger.java:2562)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2530)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2516)
	at org.acme.Messages.<clinit>(Messages.java:13)
```	

### Expected behavior

No exceptions

### Actual behavior

Throws ClassCastException. 

**This is the weird part**: It works when the application hot-reloads (perform any hot-reloadable change and hit http://localhost:8080/hello again). 

### How to Reproduce?

In a clean project, have an interface defined as:

```java
package org.acme;

import org.jboss.logging.BasicLogger;
import org.jboss.logging.Logger;
import org.jboss.logging.Logger.Level;
import org.jboss.logging.annotations.LogMessage;
import org.jboss.logging.annotations.Message;
import org.jboss.logging.annotations.MessageLogger;

@MessageLogger(projectCode = "MYAPP", length = 3)
public interface Messages extends BasicLogger {

    Messages INSTANCE = Logger.getMessageLogger(Messages.class, Messages.class.getPackageName());

    @LogMessage(level = Level.INFO)
    @Message(id = 1, value = "Hello %s !")
    void greet(String name);

    @LogMessage(level = Level.INFO)
    @Message(id = 2, value = "Goodbye %s !")
    void goodbye(String name);

}
```

And then call it in the existing `GreetingResource` with:

```java
package org.acme;

import javax.ws.rs.GET;
import javax.ws.rs.Path;

@Path("/hello")
public class GreetingResource {
    @GET
    public String hello() {
        Messages.INSTANCE.greet("George");
        Messages.INSTANCE.goodbye("Bye");
        return "Hello";
    }
}
```

Then add the following dependency to your pom.xml:

```xml
    <dependency>
      <groupId>org.jboss.logging</groupId>
      <artifactId>jboss-logging-processor</artifactId>
    </dependency>
```

Run `mvn clean compile quarkus:dev` and open http://localhost:8080/hello

You'll see the stacktrace

### Output of `uname -a` or `ver`

Fedora 34

### Output of `java -version`

11

### GraalVM version (if different from Java)

21

### Quarkus version or git rev

2.1.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by gastaldi** [comment]
After looking at a decompiled `Messages_$logger` (internal class created by `jboss-logging-processor`), it's clear that something has gone wrong (the Messages interface isn't even implemented in it)

```java
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package org.acme;

import java.io.Serializable;
import java.util.Locale;
import org.jboss.logging.BasicLogger;
import org.jboss.logging.DelegatingBasicLogger;
import org.jboss.logging.Logger;

public class Messages_$logger extends DelegatingBasicLogger implements BasicLogger, Serializable {
    private static final long serialVersionUID = 1L;
    private static final String FQCN;
    private static final Locale LOCALE;

    public Messages_$logger(final Logger log) {
        throw new Error("Unresolved compilation problems: \n\tMessages cannot be resolved to a type\n\tThe method greet(String) of type Messages_$logger must override or implement a supertype method\n\tThe method goodbye(String) of type Messages_$logger must override or implement a supertype method\n");
    }

    protected Locale getLoggingLocale() {
        throw new Error("Unresolved compilation problem: \n");
    }

    public final void greet(final String name) {
        throw new Error("Unresolved compilation problem: \n\tThe method greet(String) of type Messages_$logger must override or implement a supertype method\n");
    }

    protected String greet$str() {
        throw new Error("Unresolved compilation problem: \n");
    }

    public final void goodbye(final String name) {
        throw new Error("Unresolved compilation problem: \n\tThe method goodbye(String) of type Messages_$logger must override or implement a supertype method\n");
    }

    protected String goodbye$str() {
        throw new Error("Unresolved compilation problem: \n");
    }
}
```

**Comment by gastaldi** [comment]
This was caused by having 2 IDEs opened and compiling the same project. Closing one of them fixed the problem
