### ISSUE TITLE
JUnit: Exception in BeforeAll/AfterAll with TestInfo parameter

### ISSUE THREAD

**Issue by antoniomacri** [quarkusio/quarkus#19800]
### Describe the bug

An exception is thrown on JUnit Before/AfterAll methods:

```
@QuarkusTest
public class AnnotatedTest {

    @BeforeAll
    public static void beforeAll(TestInfo testInfo) {
        Assertions.assertEquals(AnnotatedTest.class, testInfo.getTestClass().get());
        Assertions.assertFalse(testInfo.getTestMethod().isPresent());
    }

    @Test
    public void testInfoTestCase() {
    }

    @AfterAll
    public static void afterAll(TestInfo testInfo) {
        Assertions.assertEquals(AnnotatedTest.class, testInfo.getTestClass().get());
        Assertions.assertFalse(testInfo.getTestMethod().isPresent());
    }
}
```

### Expected behavior

Above test passes.

### Actual behavior

```
java.util.NoSuchElementException: No value present

	at java.base/java.util.Optional.get(Optional.java:148)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1041)
        ...
```

### How to Reproduce?

Run the above test.

### Quarkus version or git rev

2.2.1.Final

### Additional information

Relates to #19751

**Comment by geoand** [comment]
@famod are you planning on tackling this one?

**Comment by famod** [comment]
@geoand I will: https://github.com/quarkusio/quarkus/issues/19482#issuecomment-909310900 😉
