### ISSUE TITLE
Quarkus is misunderstanding the reality of the datasource when running test cases

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#19815]
### Describe the bug

I started a project that uses JDBI. I've put together something that works, but somehow, when running the test cases, Quarkus is unable to find (or inject) the datasource where required.

```shell
ActorRepositoryTest > findById_WhenActorExist() FAILED
    java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.sql.DataSource and qualifiers [@Default]
        - java member: org.acme.config.PersistenceConfig#dataSource
        - declared on CLASS bean [types=[java.lang.Object, org.acme.config.PersistenceConfig], qualifiers=[@Default, @Any], target=org.acme.config.PersistenceConfig]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1100)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:265)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:418)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
    Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.sql.DataSource and qualifiers [@Default]
        - java member: org.acme.config.PersistenceConfig#dataSource
        - declared on CLASS bean [types=[java.lang.Object, org.acme.config.PersistenceConfig], qualifiers=[@Default, @Any], target=org.acme.config.PersistenceConfig]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:492)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:471)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:253)
        ... 13 more
```

### Expected behavior

Quarkus should be able to inject the datasource, in the same way it's injected when the application runs.

### Actual behavior

Quarkus is unable to inject the datasource while running test cases, contrary to what happens when the application runs.

### How to Reproduce?

1. Clone this repo: https://github.com/x80486/quarkus-arc-issue/
2. Run `./gradlew clean test` (it will fail)
3. Run `./gradlew quarkusDev`, it will be all right 😉

### Output of `uname -a` or `ver`

Linux uplink 5.10.61-1-lts #1 SMP Fri, 27 Aug 2021 21:20:32 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk 11.0.10 2021-01-19 LTS OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.0.2 ------------------------------------------------------------  Build time:   2021-05-14 12:02:31 UTC Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e  Kotlin:       1.4.31 Groovy:       3.0.7 Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM:          11.0.10 (Amazon.com Inc. 11.0.10+9-LTS) OS:           Linux 5.10.61-1-lts amd64

### Additional information

StackOverflow question: https://stackoverflow.com/questions/68952783/quarkus-and-jdbi-integration-unsatisfied-dependency-for-type-javax-sql-datasour

**Comment by stuartwdouglas** [comment]
Why are you using `runtimeOnly` to declare the deps? I think this means they won't be present in tests.

**Comment by x80486** [comment]
Because I don't need those dependencies at compile time, but just at runtime. My understanding is that `runtimeOnly` applies to all scopes, and `testRuntimeOnly` effectively restrict the dependencies for running tests.

**Comment by stuartwdouglas** [comment]
cc @glefloch

**Comment by x80486** [comment]
This is finally working on `2.16.2.Final` and all `3.x` versions.
