### ISSUE TITLE
JUnit multiple levels of Nested fail with QuarkusTest

### ISSUE THREAD

**Issue by vonatzigenc** [quarkusio/quarkus#19845]
### Describe the bug

If there is more than one level of `@NestedTests` in a JUnit test with `@QuarkusTest`, each one throws an `org.junit.jupiter.api.extension.TestInstantiationException` due to a `javax.enterprise.inject.UnsatisfiedResolutionException`.

However, the same setup without QuarkusTest works.

*Example:*
```
@QuarkusTest
public class MultipleNestedQuarkusTest {

    @Nested
    class FirstNested {

        @Nested
        class SecondNested {

            @Test
            void check() {
                Assertions.assertTrue(true);
            }
        }
    }
}
```

### Expected behavior

Above test passes.

### Actual behavior

Stacktrace when executing test above.

```
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance

	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:848)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:812)

...

Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.instance(RunningQuarkusApplicationImpl.java:83)
	... 97 more
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [class org.acme.MultipleNestedQuarkusTest$FirstNested] and qualifiers [[]]
	at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:175)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
	... 102 more
```

### How to Reproduce?

Run the test above.

Reproducer: https://github.com/vonatzigenc/reproducer-nested-quarkustest/blob/main/src/test/java/org/acme/MultipleNestedQuarkusTest.java

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 LTS

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by famod** [comment]
FWIW, this also happens 2.2.0.Final so it's not caused by my evil doings (that's a first...).

**Comment by famod** [comment]
@geoand @stuartwdouglas in case one of you is taking on this task: For #19843, I'll probably introduce a specific test for `@Nested`, which could then be extended here.

**Comment by Sgitario** [comment]
Added proposed solution here: https://github.com/quarkusio/quarkus/pull/24199
