### ISSUE TITLE
Build/Run error with multiple modules with gradle

### ISSUE THREAD

**Issue by hanzhenliang** [quarkusio/quarkus#19885]
### Describe the bug

I have a gradle project with multiple modules, `core` module has global configs and independencies which is shared with other modules. For example, `AwsEnvVariables` is a config interface and it's injected into other modules like:
```
@Inject private lateinit var awsEnvVariables: AwsEnvVariables
```
But I got the following errors when built the project:
```
building quarkus jar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tenant-provision:quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 3 deployment problems: 
  [1] Unsatisfied dependency for type ai.bidwise.services.core.config.aws.AwsEnvVariables and qualifiers [@Default]
        - java member: ai.bidwise.services.tenantprovision.mapper.CreateIdentityPoolRequestImpl#awsEnvVariables
        - declared on CLASS bean [types=[ai.bidwise.services.tenantprovision.mapper.CreateIdentityPoolRequestMapper, java.lang.Object, ai.bidwise.services.tenantprovision.mapper.CreateIdentityPoolRequestImpl], qualifiers=[@Default, @Any], target=ai.bidwise.services.tenantprovision.mapper.CreateIdentityPoolRequestImpl]
  [2] Unsatisfied dependency for type ai.bidwise.services.core.config.aws.AwsEnvVariables and qualifiers [@Default]
        - java member: ai.bidwise.services.tenantprovision.cognito.CognitoIdentityClientProducer#awsEnvVariables
        - declared on CLASS bean [types=[ai.bidwise.services.tenantprovision.cognito.CognitoIdentityClientProducer, java.lang.Object], qualifiers=[@Default, @Any], target=ai.bidwise.services.tenantprovision.cognito.CognitoIdentityClientProducer]
  [3] Unsatisfied dependency for type ai.bidwise.services.core.config.aws.AwsEnvVariables and qualifiers [@Default]
        - java member: ai.bidwise.services.tenantprovision.cognito.CognitoIdentityProviderClientProducer#awsEnvVariables
        - declared on CLASS bean [types=[ai.bidwise.services.tenantprovision.cognito.CognitoIdentityProviderClientProducer, java.lang.Object], qualifiers=[@Default, @Any], target=ai.bidwise.services.tenantprovision.cognito.CognitoIdentityProviderClientProducer]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1108)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:265)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:418)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
```

In order to fix the build error, I used another way to inject which worked great:
```
@Inject private lateinit var awsEnvVariables: Instance<AwsEnvVariables>
```

While I ran the application, I still can not find the bean to be injected, here is the error:
```
2021-09-02 20:24:46,341 ERROR [ai.bid.ser.use.use.UserPoolProvisionUseCaseImpl] (executor-thread-0) Can not create user pool: CreateUserPoolRequest(userPoolName=test): javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [interface ai.bidwise.services.core.config.aws.AwsEnvVariables] and qualifiers [[@javax.enterprise.inject.Default()]]
        at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:175)
        at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
        at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
        at ai.bidwise.services.usermanager.cognito.CognitoIdentityProviderClientProducer.produceCognitoIdentityProviderClient(CognitoIdentityProviderClientProducer.kt:17)
        at ai.bidwise.services.usermanager.cognito.CognitoIdentityProviderClientProducer_ProducerMethod_produceCognitoIdentityProviderClient_b7f4e9f6c49ed951bdc665c8d6ccc0a8a6063659_Bean.create(CognitoIdentityProviderClientProducer_ProducerMethod_produceCognitoIdentityProviderClient_b7f4e9f6c49ed951bdc665c8d6ccc0a8a6063659_Bean.zig:203)
        at ai.bidwise.services.usermanager.cognito.CognitoIdentityProviderClientProducer_ProducerMethod_produceCognitoIdentityProviderClient_b7f4e9f6c49ed951bdc665c8d6ccc0a8a6063659_Bean.create(CognitoIdentityProviderClientProducer_ProducerMethod_produceCognitoIdentityProviderClient_b7f4e9f6c49ed951bdc665c8d6ccc0a8a6063659_Bean.zig:241)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
        at ai.bidwise.services.usermanager.cognito.CognitoIdentityProviderClientProducer_ProducerMethod_produceCognitoIdentityProviderClient_b7f4e9f6c49ed951bdc665c8d6ccc0a8a6063659_ClientProxy.arc$delegate(CognitoIdentityProviderClientProducer_ProducerMethod_produceCognitoIdentityProviderClient_b7f4e9f6c49ed951bdc665c8d6ccc0a8a6063659_ClientProxy.zig:68)
        at ai.bidwise.services.usermanager.cognito.CognitoIdentityProviderClientProducer_ProducerMethod_produceCognitoIdentityProviderClient_b7f4e9f6c49ed951bdc665c8d6ccc0a8a6063659_ClientProxy.createUserPool(CognitoIdentityProviderClientProducer_ProducerMethod_produceCognitoIdentityProviderClient_b7f4e9f6c49ed951bdc665c8d6ccc0a8a6063659_ClientProxy.zig:2882)
        at ai.bidwise.services.usermanager.repository.CognitoUserPoolRepository.createUserPool(UserPoolRepository.kt:27)
        at ai.bidwise.services.usermanager.repository.CognitoUserPoolRepository_ClientProxy.createUserPool(CognitoUserPoolRepository_ClientProxy.zig:157)
        at ai.bidwise.services.usermanager.usecase.UserPoolProvisionUseCaseImpl.createUserPool(UserPoolProvisionUseCase.kt:37)
        at ai.bidwise.services.usermanager.usecase.UserPoolProvisionUseCaseImpl_ClientProxy.createUserPool(UserPoolProvisionUseCaseImpl_ClientProxy.zig:188)
        at ai.bidwise.services.usermanager.UserPoolProvisionResource.createUserPool(UserPoolProvisionResource.kt:34)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### Expected behavior

The beans in other modules can be injected correctly.

### Actual behavior

Can not be injected and the beans can not be found.

### Quarkus version or git rev

2.2.1.Final

**Comment by hanzhenliang** [comment]
I have another bean in `core` module which has the same issue:
```
interface ResourceResultMapper {

    fun <T> from(modelResult: ModelResult<T>): ResourceResult<T>

}

@ApplicationScoped
class ResourceResultMapperImpl : ResourceResultMapper {

    override fun <T> from(modelResult: ModelResult<T>): ResourceResult<T> =
        when (modelResult) {
            is ModelResult.Success -> ResourceResult.success(modelResult.result)
            is ModelResult.Error -> ResourceResult.error(modelResult.throwable.localizedMessage)
        }

}
```

Stacktrace:
```
2021-09-03 09:22:26,425 INFO  [io.ver.ext.web.RoutingContext] (executor-thread-0) RoutingContext failure (500): org.jboss.resteasy.spi.UnhandledException: javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [interface ai.bidwise.services.core.ResourceResultMapper] and qualifiers [[@javax.enterprise.inject.Default()]]
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by hanzhenliang** [comment]
The issue is resolved by moving the beans to the module injected.

**Comment by hanzhenliang** [comment]
Fix by Jandex cache.
