### ISSUE TITLE
[native-image] integration-tests/amazon-lambda-rest, UserException: Annotated class must be final

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#19886]
### Describe the bug

Both `Quarkus 2.2.0.Final` and a contemporary main (head 94ae125) fail `integration-tests/amazon-lambda-rest` regardless of the native-image distribution, being it `21.3.0-devd63e6aab07 Mandrel Distribution (Java Version 11.0.13-ea+3)`, or `GraalVM Version 20.3.2 (Java Version 11.0.11+8-jvmci-20.3-b15)` or `GraalVM 21.2.0 Java 11 CE (Java Version 11.0.12+6-jvmci-21.2-b08)` with this at build time:

```bash
native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace -H:-ParseOnce quarkus-integration-test-amazon-lambda-rest-999-SNAPSHOT-runner -jar quarkus-integration-test-amazon-lambda-rest-999-SNAPSHOT-runner.jar
[quarkus-integration-test-amazon-lambda-rest-999-SNAPSHOT-runner:101012]    classlist:   1,981.69 ms,  1.19 GB
[quarkus-integration-test-amazon-lambda-rest-999-SNAPSHOT-runner:101012]        setup:     462.45 ms,  1.19 GB
Error: Annotated class must be final: class io.quarkus.amazon.lambda.http.graal.LambdaContainerHandlerSubstitution
com.oracle.svm.core.util.UserError$UserException: Annotated class must be final: class io.quarkus.amazon.lambda.http.graal.LambdaContainerHandlerSubstitution
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:280)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:936)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:868)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
[quarkus-integration-test-amazon-lambda-rest-999-SNAPSHOT-runner:101012]      [total]:   2,489.69 ms,  1.19 GB
# Printing build artifacts to: /home/karm/workspaceRH/quarkus/integration-tests/amazon-lambda-rest/target/quarkus-integration-test-amazon-lambda-rest-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-amazon-lambda-rest-999-SNAPSHOT-runner.build_artifacts.txt
Error: Image build request failed with exit status 1
```

**Comment by Karm** [comment]
Ouch, I wish @quarkus-bot hadn't spammed so many people with this 🙈

> /cc @ galderz, @ matejvasek, @ patriot1burke, @ zakkak
