### ISSUE TITLE
Binding in-memory channel to SSE Events issue

### ISSUE THREAD

**Issue by fbricon** [quarkusio/quarkus#19940]
### Describe the bug

I'm trying to emit data to an in-memory channel, every couple seconds, with:

```java
public class DataEmitter {
    
    @Channel("my-data")
    @OnOverflow(value = Strategy.DROP)
    Emitter<Integer> emitter;

    @Scheduled(every = "2s")
    public void pulse() {
        int payload = (int) (Math.random()*1000);
        System.out.println("Emitted "+payload);
        emitter.send(payload);
    }
}
```

The data is exposed via SSE with:
```java
@Path("/stream")
public class Streamer {

    @Channel("my-data")
    Multi<Integer> dataStream;

    @GET
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public Multi<Integer> stream() {
        return dataStream;
    }

}
```

Upon startup, the application will log errors every 2s because `No subscriber found for the channel my-data`:

```
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-09-06 18:33:43,442 INFO  [io.quarkus] (Quarkus Main Thread) channel-streamer 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.2.1.Final) started in 1.666s. Listening on: http://localhost:8080
2021-09-06 18:33:43,448 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-09-06 18:33:43,448 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy-reactive, scheduler, smallrye-context-propagation, smallrye-reactive-messaging, vertx]
Emitted 922
2021-09-06 18:33:44,008 ERROR [io.qua.sch.run.SimpleScheduler] (executor-thread-0) Error occured while executing task for trigger IntervalTrigger [id=1_foo.bar.DataEmitter_ScheduledInvoker_pulse_4b7d09f41d6bdfd0c06c3aaf27138ccc2843f647, interval=2000]: java.lang.IllegalStateException: SRMSG00027: No subscriber found for the channel my-data
	at io.smallrye.reactive.messaging.extension.AbstractEmitter.verify(AbstractEmitter.java:157)
	at io.smallrye.reactive.messaging.extension.AbstractEmitter.emit(AbstractEmitter.java:139)
	at io.smallrye.reactive.messaging.extension.EmitterImpl.send(EmitterImpl.java:29)
	at foo.bar.DataEmitter.pulse(DataEmitter.java:20)
	at foo.bar.DataEmitter_ScheduledInvoker_pulse_4b7d09f41d6bdfd0c06c3aaf27138ccc2843f647.invokeBean(DataEmitter_ScheduledInvoker_pulse_4b7d09f41d6bdfd0c06c3aaf27138ccc2843f647.zig:48)
	at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
	at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.run(SimpleScheduler.java:274)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:548)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)

```

Access http://localhost:8080/stream in chrome or in a terminal via :
```
curl -N http://localhost:8080/stream
```
 And the server will stop complaining about the missing subscriber. Kill the browser or curl process, the event will still be emitted on the server but no more complaints about the missing subscriber.

I created https://github.com/fbricon/channel-streamer as a reproducer.

### Expected behavior

Upon startup, since the emitter is annotated with `@OnOverflow(value = Strategy.DROP)` I'd expect it to not complain about the missing subscriber

### Actual behavior

An error is logged every time a message is emitted to the channel, until a subscriber is registered. The weird thing is it doesn't complain if you kill the client connection to the stream.

### How to Reproduce?

- clone https://github.com/fbricon/channel-streamer 
- run ./mvnw quarkus:dev
- see logs
- access http://localhost:8080/stream for the server to stop complaining

### Output of `uname -a` or `ver`

Darwin fbricon-mac 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

16.0.1

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

### Additional information

Discussed with @cescoffier on https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Binding.20in-memory.20channel.20to.20SSE.20Events

**Comment by cescoffier** [comment]
Thanks @fbricon for the detailed report and reproducer. 

So, definitely a bug we need to fix in reactive messaging (I will create the issue there).
As a workaround, use:

```
 if (emitter.hasRequests()) {
     emitter.send(payload);
}
```

**Comment by fbricon** [comment]
@cescoffier thx, the workaround works as expected

**Comment by cescoffier** [comment]
@fbricon https://github.com/smallrye/smallrye-reactive-messaging/pull/1398 will fix this issue. It improves the error, documents the `hasRequests`, and prevents exceptions to be thrown when using `@OnOverflow(DROP)`

**Comment by cescoffier** [comment]
Fixed as we bumped the reactive messaging version in quarkus.
