### ISSUE TITLE
Support kotlin coroutines in GraphQL 

### ISSUE THREAD

**Issue by nenros** [quarkusio/quarkus#19975]
### Description

Hi all!
Is there any chance that you can support coroutines in `io.quarkus:quarkus-smallrye-graphql`? When I try to write something like that: 
```kotlin
@GraphQLApi
@RequestScoped
class SomethingResource(
    private val somethingService: SomethingService,
) {

    @Query("getSomething")
    suspend fun getSomething(): SomethingResponse {
        val something = calendarService.getUserCalendar().awaitSuspending()

        return something?.toSomthingResponse()
    }
}
```

I get this error: 
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor#buildExecutionService threw an exception: java.lang.IllegalArgumentException: Invalid parameter type [kotlin.coroutines.Continuation]
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getNonIndexedReference(ReferenceCreator.java:462)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:331)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:259)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForOperationArgument(ReferenceCreator.java:107)
	at io.smallrye.graphql.schema.creator.ArgumentCreator.createArgument(ArgumentCreator.java:68)
	at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:80)
	at io.smallrye.graphql.schema.SchemaBuilder.addOperations(SchemaBuilder.java:252)
	at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:117)
	at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:86)
	at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:175)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:831)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

So I would be really grateful if there is chance to allow GraphQL queries to be coroutines.

**Comment by nenros** [comment]
Ok, probably it cannot be done here I created issue in smallrye-graphql https://github.com/smallrye/smallrye-graphql/issues/1024

**Comment by phillip-kruger** [comment]
Closing here, we will do the work in smallrye
