### ISSUE TITLE
2.2.2: Fails to find config-mappings (regression from 2.2.1)

### ISSUE THREAD

**Issue by snazy** [quarkusio/quarkus#19990]
### Describe the bug

`@ConfigMapping` stops to work for us in 2.2.2 (2.2.1 works fine). (Test) boot fails with the following exception. 

Little analysis (incomplete though):
* `io.smallrye.config.ConfigMappings#getConfigMapping(java.lang.Class<T>, java.lang.String)` gets called with the right `type` + `prefix`, but `ConfigMappings.mappings` is empty.
* `io.smallrye.config.ConfigMappingProvider#ConfigMappingProvider` gets called with a an empty map in `builder.roots`.

Abbreviated stack trace:
```
Caused by: java.util.NoSuchElementException: SRCFG00027: Could not find a mapping for org.projectnessie.server.config.QuarkusServerConfig
	at io.smallrye.config.ConfigMappings.getConfigMapping(ConfigMappings.java:73)
	at io.smallrye.config.SmallRyeConfig.getConfigMapping(SmallRyeConfig.java:398)
	at io.quarkus.arc.runtime.ConfigMappingCreator.create(ConfigMappingCreator.java:28)
	at org.projectnessie.server.config.QuarkusServerConfig_d817d6674f6dd6b5a719cc3112dd8ea486a5ea96_Synthetic_Bean.create(QuarkusServerConfig_d817d6674f6dd6b5a719cc3112dd8ea486a5ea96_Synthetic_Bean.zig:140)
	at org.projectnessie.server.config.QuarkusServerConfig_d817d6674f6dd6b5a719cc3112dd8ea486a5ea96_Synthetic_Bean.get(QuarkusServerConfig_d817d6674f6dd6b5a719cc3112dd8ea486a5ea96_Synthetic_Bean.zig:171)
	at org.projectnessie.server.config.QuarkusServerConfig_d817d6674f6dd6b5a719cc3112dd8ea486a5ea96_Synthetic_Bean.get(QuarkusServerConfig_d817d6674f6dd6b5a719cc3112dd8ea486a5ea96_Synthetic_Bean.zig:194)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
	at org.projectnessie.services.rest.NessieExceptionMapper_Bean.create(NessieExceptionMapper_Bean.zig:174)
```

### How to Reproduce?

1. `git clone https://github.com/projectnessie/nessie.git`
2. update `quarkus.version` in top-level `pom.xml` to 2.2.2
3. `./mvnw clean install -DskipTests`
4. Run `org.projectnessie.server.TestRest` in IntelliJ (or `./mvnw verify -pl servers/quarkus-server`)

### Quarkus version or git rev

2.2.2

**Comment by famod** [comment]
/cc @radcortez

Maybe it's related to the interface extending another one: https://github.com/projectnessie/nessie/blob/main/servers/quarkus-server/src/main/java/org/projectnessie/server/config/QuarkusServerConfig.java

**Comment by radcortez** [comment]
> Maybe it's related to the interface extending another one: https://github.com/projectnessie/nessie/blob/main/servers/quarkus-server/src/main/java/org/projectnessie/server/config/QuarkusServerConfig.java

No.

Unfortunately, we have to revert the support of `@ConfigMapping` for Static Init, which is the phase where JAX-RS Providers are initialized. 

As you can see in https://github.com/quarkusio/quarkus/pull/19937, this caused some nasty issues, so we had to take the hard decision to revert it and rethink how to do this.

@snazy sorry for the inconvenience, I'll be looking at how we can support this in the future. Right now, the only option is to inject the configs keys individually with `@ConfigProperty` (or with a programmatic lookup).
