### ISSUE TITLE
@ConfigMapping does not load Map if there are >=3 dot(.) separators in properties

### ISSUE THREAD

**Issue by JithendraKatkam** [quarkusio/quarkus#20102]
### Describe the bug

If property name contains more than 2 dot separators, its  not loading the values in the Map<String, String> and getting the error as below.
 
- xyz.z.abcd.efgh does not map to any root

### Expected behavior

All property names with multiple dot separators should be allowed to be loaded in the Map object if there are matching the prefix and the java attribute name or withName.

### Actual behavior

Only Map<String, String > props is loading with 2 dot separator properties

- xyz.z.abcd=efgh
- xyz.z.ijkl=mnop

### How to Reproduce?

1. Define two properties as below in application.properties
```
xyz.z.abcd.efgh=efgh
xyz.z.ijkl=mnop
```
2. Define @ConfigMapping bean as below
```
@ConfigMapping(prefix = "xyz")
public interface MyProperties {
     Map<String, String> z();
}
```
3. Start the application  - see error as below
```
.
2021-09-13 10:59:53,390 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.config.ConfigValidationException: Configuration validation failed:
        xyz.z.abcd.efgh does not map to any root
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:838)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:794)
        at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:54)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:36)
        at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:81)
.
.
.
```

### Output of `uname -a` or `ver`

Darwin C02C98D4LVDLMBP 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM Corretto-11.0.12.7.2 (build 11.0.12+7-LTS, mixed mode)

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.9

**Comment by radcortez** [comment]
In this case, you need to quote the dotted key like:

```properties
xyz.z.\"abcd.efgh\"=efgh
xyz.z.ijkl=mnop
```

Added a test to SR Config: https://github.com/smallrye/smallrye-config/commit/2b7b1f120397f1a5e633c21596bc1bfc6652db41

**Comment by JithendraKatkam** [comment]
Thank you...!
