### ISSUE TITLE
quarkus-maven-plugin (0.13.1) does not work with the (weird!) Apache Maven "3.5.0" (Red Hat 3.5.0-4.3) in registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#2014]
Investigating https://github.com/quarkusio/quarkus-images/issues/13 shows that quarkus-maven-plugin does not work with Maven 3.5.0 (Red Hat 3.5.0-4.3) in `registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift`...

Interestingly, I seem to be able to build and run at least `quarkus-quickstarts/getting-started` just fine with an _Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)_ which I downloaded from https://maven.apache.org/docs/history.html though! 

Therefore IMHO the "fault" here is more with that Maven package than with Quarkus, and I'm opening this issue to document this finding and allow others to comment; I'm not saying that this should be "fixed" in Quarkus.

This is with the currently released version 0.13.1, apparently it worked with 0.12.0.

**Comment by vorburger** [comment]
$ cat /etc/centos-release   
CentOS Linux release 7.6.1810 (Core) 

$ sudo yum install maven

$ /usr/bin/mvn -version     
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_201, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64/jre
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.10.1.el7.x86_64", arch: "amd64", family: "unix"

$ git clone https://github.com/quarkusio/quarkus-quickstarts.git
$ cd quarkus-quickstarts/getting-started
$ /usr/bin/mvn clean package
(...)
[INFO] --- quarkus-maven-plugin:0.13.1:build (default) @ quarkus-quickstart ---
Apr 11, 2019 6:36:27 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: io.quarkus.maven.BuildMojo
com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.eclipse.aether.RepositorySystem was bound.
  while locating io.quarkus.maven.BuildMojo

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1006)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1032)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:997)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1047)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:993)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.098s
[INFO] Finished at: Thu Apr 11 18:36:27 UTC 2019
[INFO] Final Memory: 37M/319M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.13.1:build (default) on project quarkus-quickstart: Execution default of goal io.quarkus:quarkus-maven-plugin:0.13.1:build failed: Unable to load the mojo 'build' (or one of its required components) from the plugin 'io.quarkus:quarkus-maven-plugin:0.13.1': com.google.inject.ProvisionException: Guice provision errors:
[ERROR] 
[ERROR] 1) No implementation for org.eclipse.aether.RepositorySystem was bound.
[ERROR] while locating io.quarkus.maven.BuildMojo
[ERROR] at ClassRealm[plugin>io.quarkus:quarkus-maven-plugin:0.13.1, parent: sun.misc.Launcher$AppClassLoader@7852e922]
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=io.quarkus:quarkus-maven-plugin:0.13.1:build)
[ERROR] 
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: io.quarkus:quarkus-maven-plugin:0.13.1:build
[ERROR] -> [Help 1]

**Comment by cescoffier** [comment]
Are we really talking about Maven 3.0.5? It's been released in February **2013**!

**Comment by vorburger** [comment]
> Are we really talking about Maven 3.0.5? It's been released in February 2013!

hang on, I got confused with 3.0.5 VS 3.5.0 ... :smiley_cat:  Let's just forget about the 3.0.5 you get from `yum install maven` on CentOS 7.6, and instead focus on the 3.5.0 used in `registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift`.

I don't think Quarkus should be expected to support this, and think this is another better solution for https://github.com/quarkusio/quarkus-images/issues/13 (I'll update there), and filed this more for the record and for discussion - I would take absolutely no offence if this issue was just closed later!

I'll do some more tests and update this issue with findings.

**Comment by gsmet** [comment]
Aren't we supposed to have something enforcing Maven 3.5.3+?

Because that's the version we require.

**Comment by vorburger** [comment]
> Aren't we supposed to have something enforcing Maven 3.5.3+?

We use the maven-enforcer-plugin for this in Quarkus' own build-parent/pom.xml, but not in the Quick Start. We could add to to (each...) quickstart, but it would not help in this particular case - this describes a problem where with a Maven 3.5.0 from Apache.org it works, but with with Maven 3.5.0 (Red Hat 3.5.0-4.3) in registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift it does not... :crying_cat_face:

**Comment by gsmet** [comment]
No, our own plugin is supposed to enforce it. But maybe it fails too early now.

**Comment by gastaldi** [comment]
@gsmet right now the plugin fails with the error in https://github.com/quarkusio/quarkus-images/issues/13#issuecomment-482225327, but it would be nice if it could check the maven version before executing to prevent nasty errors like this
