### ISSUE TITLE
AsyncHealthCheck does not work with Hibernate Reactive

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#20166]
### Describe the bug

The following health check based on the `AsyncHealthCheck` example from the [smallrye-health doc](https://quarkus.io/guides/smallrye-health#reactive-health-checks) works perfectly fine with Quarkus `1.13.7` when Hibernate Reactive is used:

```
@ApplicationScoped
@Liveness
public class MyHealthCheck implements AsyncHealthCheck {

    @Inject
    Mutiny.Session session;

    @Override
    public Uni<HealthCheckResponse> call() {
        return session.createNativeQuery("SELECT 1")
                .getSingleResult()
                .replaceWith(TRUE)
                .onFailure().recoverWithItem(FALSE)
                .onItem().transform(dbState ->
                        HealthCheckResponse.named("Health check").status(dbState).build()
                );
    }
}
```

With Quarkus `2.2.2.Final`, the same code no longer works because the `call` method isn't run on the Vert.x event loop thread.

### Expected behavior

The check should be run on the Vert.x event loop thread.

### Actual behavior

```
2021-09-15 11:09:45,142 ERROR [io.sma.health] (executor-thread-0) SRHCK01000: Error processing Health Checks: java.lang.IllegalStateException: HR000068: This method should exclusively be invoked from a Vert.x EventLoop thread; currently running on thread 'executor-thread-0'
        at org.hibernate.reactive.common.InternalStateAssertions.assertUseOnEventLoop(InternalStateAssertions.java:40)
        at org.hibernate.reactive.mutiny.impl.MutinySessionFactoryImpl.proxyConnection(MutinySessionFactoryImpl.java:150)
        at org.hibernate.reactive.mutiny.impl.MutinySessionFactoryImpl.openSession(MutinySessionFactoryImpl.java:69)
        at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer.createMutinySession(ReactiveSessionProducer.java:23)
        at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.create(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.zig:247)
        at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.create(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.zig:285)
        at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:68)
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:33)
        at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.arc$delegate(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.zig:60)
        at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.createNativeQuery(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.zig:294)
        at org.acme.FailingHealthCheck.call(FailingHealthCheck.java:24)
        at org.acme.FailingHealthCheck_ClientProxy.call(FailingHealthCheck_ClientProxy.zig:203)
        at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$UniHandler.subscribe(UniAndCombination.java:203)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.run(UniAndCombination.java:71)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.access$000(UniAndCombination.java:53)
        at io.smallrye.mutiny.operators.uni.UniAndCombination.subscribe(UniAndCombination.java:50)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:54)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
        at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:192)
        at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getHealth(SmallRyeHealthReporter_ClientProxy.zig:802)
        at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.getHealth(SmallRyeHealthHandler.java:11)
        at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.doHandle(SmallRyeHealthHandlerBase.java:44)
        at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:31)
        at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.handle(SmallRyeHealthHandler.java:7)
        at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:19)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

Steps to reproduce:

1. Clone https://github.com/gwenneg/quarkus-async-health-check
2. Run `./mvnw clean install`

### Quarkus version or git rev

2.2.2.Final

**Comment by Sanne** [comment]
thanks @gwenneg !

I suppose it would work if you injected the `Mutiny.SessionFactory` type instead, to then use either `withSession` or `withTransaction` or possibly best in this case - `withStatelessSession` / `withStatelessTransaction` ?

@stuartwdouglas | @mkouba  | @FroMage this is more likely in your area of expertise? The producer for `Mutiny.Session` isn't running on the vertx context, but it should in this case. This relates to what I previously mentioned as the CDI injection points needing to form a reactive chain - which I believe is a larger requirement, not specific to HR.

**Comment by gwenneg** [comment]
Sorry I forgot to mention that I tested `SessionFactory` as well and it didn't work.

Thanks for suggesting the stateless session for this check, that's a better choice indeed. 😃

**Comment by DavideD** [comment]
I will check the example to see if I can reproduce it

**Comment by gwenneg** [comment]
@DavideD I added a reproducer in the issue: https://github.com/gwenneg/quarkus-async-health-check

**Comment by mkouba** [comment]
Just to be clear - CDI does not care about the thread context a bean is created on, i.e. on which thread the `ReactiveSessionProducer.createMutinySession()` producer method is invoked. Also note that beans are created lazily and so the the context of the first bean in the request that declares the dependency on `Mutiny.Session` "wins".

**Comment by DavideD** [comment]
> @DavideD I added a reproducer in the issue: https://github.com/gwenneg/quarkus-async-health-check

Yep, the reproducer shows the error. Hibernate Reactive is working as expected, it throws the exception because the thread if not the Vert.x Loop thread. I think you have the error now because in previous versions of Quarkus the check was disabled. @Sanne, is that true?

**Comment by gwenneg** [comment]
That's correct, the check was added with Quarkus 2.1.

**Comment by stuartwdouglas** [comment]
@Sanne is this 'only use on IO thread' requirement really necessary? Shouldn't it just be 'all work is done on the IO thread', so you just dispatch to the IO thread transparently if a call is made from the wrong thread?

The current model does not actually enforce 'only one thread', as you can make invocations from different IO threads, so I don't really understand why it is necessary.

**Comment by Sanne** [comment]
well yes I'm trying to enforce "all work" on the IO thread, but opening a
session implies potentially needing to establish a connection

**Comment by stuartwdouglas** [comment]
How? Won't anything that requires a connection return a Uni<>, so you can just delegate that to an IO thread?

**Comment by Sanne** [comment]
The big difficulty is that mutators can operate on any managed entity; we can't constrain "all work" to be routed and potentially dispatched by the Session instance.

> How? Won't anything that requires a connection return a Uni<>, so you can just delegate that to an IO thread?

yes right, there's an open discussion on HR in which I've tried to persuade others to change the open-session operation to return an Uni of Session, but we've been back on forth on that and there's reasons this should be unnecessary. Primarily the point is that in most cases we can actually defer opening the connection, and andqueue any actual subsequent work as a downstream operation to happen after the connection is opened. This implies no transactions though - and the different integration options in Quarkus might need to veto the lazy chain approach.

**But all such considerations are tangential**: the bigger elefant in the room is that any "work" on the session implies state-change operations on the Session, which is not threadsafe so we really prefer to ensure isolation of the Session instance - and all its managed entities - to be confined within the scope of a single thread: the IO thread processing the responses from the DB.

Quoting you again:

> Shouldn't it just be 'all work is done on the IO thread',

so that's what we hope to achieve, but including the lifespan of the Session (Transaction): it should be opened and closed within that same thread. I totally get it it's not easy, but alternatives don't seem "easy" to me either.

**Comment by Sanne** [comment]
BTW a "KISS" approach I've attempted in the recent past is to simply remove the ability to inject a Session - forcing people to inject a SessionFactory. That approach hit a wall with the Panache integrations though.

**Comment by stuartwdouglas** [comment]
What I mean is that you basically have a Session proxy, and then every call to a method will check if the current thread is the IO thread, and if not delegate to it. 

e.g.

```
<T> Uni<T> find(Class<T> entityClass, Object id) {
if (isOnCorrectThread(entityClass, id)) {
return delegate.find();
} else {
  return dispatchToThread(() -> delegate.find(entityClass, id));
}
}
```

The complexity here lies in that with the current API's we don't know what the correct IO thread is until the connection is allocated, so this would need to be done inside hibernate itself.

**Comment by Sanne** [comment]
If we did that, then you'd have the entity loaded by a Session in a different thread, and then possibly mutated by the current thread. You see the problem? we can't allow that.

Example of user's code:
    

    Person p = new Person();
    Uni<Void> persisted = session.persist( p );
    p.setAge( 18 );
    return persisted;


And this is oversimplified; imagine re-attaching some complex entity graph via a `merge` operation, which needs to mark some attributes as dirty directly on the entity state.

Such entity states are not synchronized, and even if they did, we need the operations to be ordered.

**Comment by Sanne** [comment]
BTW CDI already provides a "Session proxy" - so I don't disagree in principle with your idea, but we need the whole function operating on the Session proxy to be dispatched; which is what I suggested above.

**Comment by Sanne** [comment]
@stuartwdouglas , @geoand looks like we went on a tangent, shouldn't we discuss first why this Uni returning method is run by the blocking executor?

I thought the deal was that any method with such a signature would run on the reactive threads.

**Comment by geoand** [comment]
Indeed, but that didn't cover health endpoints, probably because we didn't think about this case.
It does sound reasonable to me that these should be run on the event loop.

**Comment by Sanne** [comment]
@geoand awesome, if that could be done then this should be solved; I guess some other similar components might need to be identified and get the same treatment, but I suspect that would be far better than trying to work around it in HR's code base.

**Comment by geoand** [comment]
If @stuartwdouglas also agrees with this approach, I can certainly take it on.

**Comment by geoand** [comment]
I took a super quick look at this, and it seems like it would require more than just Quarkus work.

Essentially what is going on now is that Quarkus creates a `Route`  (which is always blocking) and when that route is called the various health checks are called as part of that request - there is no separation between sync and async health checks.
So this likely needs some smallrye work.
cc @radcortez @kenfinnigan

**Comment by gwenneg** [comment]
For anyone who might be affected by this issue, here's a workaround you can use until it's been properly fixed:

```
@ApplicationScoped
@Liveness
public class MyHealthCheck implements AsyncHealthCheck {

    @Inject
    Mutiny.SessionFactory sessionFactory;

    @Inject
    Vertx vertx;

    @Override
    public Uni<HealthCheckResponse> call() {
        return sessionFactory.withStatelessSession(statelessSession -> statelessSession.createNativeQuery("SELECT 1")
                .getSingleResult()
                .replaceWith(Boolean.TRUE)
                .onFailure().recoverWithItem(Boolean.FALSE)
                .onItem().transform(dbState ->
                        HealthCheckResponse.named("Health check").status(dbState).build()
                )
        ).runSubscriptionOn(MutinyHelper.executor(vertx.getOrCreateContext()));
    }
}
```

**Comment by stuartwdouglas** [comment]
@Sanne you already have that problem though, as the IO thread that HTTP happens to be on may not be the same IO thread that has been allocated to the database.

**Comment by radcortez** [comment]
> I took a super quick look at this, and it seems like it would require more than just Quarkus work.
> 
> Essentially what is going on now is that Quarkus creates a `Route` (which is always blocking) and when that route is called the various health checks are called as part of that request - there is no separation between sync and async health checks.
> So this likely needs some smallrye work.
> cc @radcortez @kenfinnigan

cc @xstefank
