### ISSUE TITLE
cannot deserialize from Object value (no delegate- or property-based Creator)

### ISSUE THREAD

**Issue by davecramer** [quarkusio/quarkus#20200]
### Describe the bug

This only happens in the native version..

Stacktrace:

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.crunchydata.model.Clusters` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (ByteArrayInputStream); line: 1, column: 2]
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1764)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1209)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1426)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.JacksonBasicMessageBodyReader.doReadFrom(JacksonBasicMessageBodyReader.java:45)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.JacksonBasicMessageBodyReader.readFrom(JacksonBasicMessageBodyReader.java:34)
	at org.jboss.resteasy.reactive.client.impl.ClientReaderInterceptorContextImpl.proceed(ClientReaderInterceptorContextImpl.java:54)
```

Here is the definition of Clusters

```java
package com.crunchydata.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

public class Clusters {
    @JsonProperty("clusters")
    List<Cluster> clusterList;

    public Clusters() {}

    public Clusters(List<Cluster> clusterList) {
        this.clusterList = clusterList;
    }

    public List<Cluster> getClusterList() {
        return clusterList;
    }

    public void setClusterList(List<Cluster> clusterList) {
        this.clusterList = clusterList;
    }
}
```

### Output of `uname -a` or `ver`

Darwin Daves-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 16.0.2+7-jvmci-21.2-b08, mixed mode, sharing)

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.0

### Additional information

This only happens with the native-image

**Comment by geoand** [comment]
What does the JAX-RS resource look like?

**Comment by davecramer** [comment]
> What does the JAX-RS resource look like?

Assume I have no clue (pretty much true). I'm going to presume this JAX-RS is the server part. I didn't write that part this is just the client so there is no JAX-RS
https://github.com/davecramer/crunchybridge-cli is the code.

**Comment by geoand** [comment]
Thanks for information.

Given that code, how would I reproduce the problem you are seeing?

**Comment by geoand** [comment]
In any case, https://github.com/quarkusio/quarkus/pull/20225 should fix  the issue

**Comment by gsmet** [comment]
In the meantime, you can use @RegisterForReflection to register your model classes for reflection manually.

**Comment by davecramer** [comment]
Thx for the quick response!

**Comment by matthyx** [comment]
Hi, I have the same issue when trying to create a `io.fabric8.certmanager.api.model.v1.CertificateList` (also in native only):
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.fabric8.certmanager.api.model.v1.CertificateList` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
at [Source: (BufferedInputStream); line: 1, column: 2]
at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1764)
at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1209)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3593)
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:261)
```

Do you think #20225 also fixes it? How can I test that?
cc @vsevel

**Comment by geoand** [comment]
> Do you think #20225 also fixes it? How can I test that?

It depends, how is this used?

**Comment by matthyx** [comment]
I try to populate a list of objects found in the namespace:
```
List<HasMetadata> resources = new ArrayList<>();
resources.addAll(client.certManagerClient.v1().certificates().inNamespace(namespace).withLabels(pruningSelector).list().getItems());
```

**Comment by geoand** [comment]
I doubt it's the same problem. Please open a new Github issue, preferably with a small reproducer project
