### ISSUE TITLE
quarkus.keycloak.devservices.port is not exposed

### ISSUE THREAD

**Issue by 9too** [quarkusio/quarkus#20219]
### Describe the bug

Using `quarkus.keycloak.devservices.port` in `application.properties` yields the following exception :
```
2021-09-16 16:27:01,580 WARN  [org.tes.con.wai.str.HttpWaitStrategy] (build-21) Unexpected error occurred - will proceed to try to wait anyway: java.lang.IllegalStateException: Target port 1337 is not exposed
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$waitUntilReady$2(HttpWaitStrategy.java:197)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:197)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:892)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:440)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:236)
	at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:128)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

No stacktrace displayed.

### Actual behavior

The container starts properly, configurations are also applied (i.e. `quarkus.keycloak.devservices.realm-path`).
It looks like a false positive AFAIK.

The error probably stems from [KeycloakDevServicesProcessor.java:369](https://github.com/quarkusio/quarkus/blob/08721da7c5dccdf3cc71d83be91f0a135bc47084/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L369), which eventually triggers the exception here [HttpWaitStrategy.java:194](https://github.com/testcontainers/testcontainers-java/blob/5e6dbc791b6184f0de6d1f9d184a78324c1ec945/core/src/main/java/org/testcontainers/containers/wait/strategy/HttpWaitStrategy.java#L194).

So I'm unsure wether the responsability falls upon `testcontainers` or something is missing on this side.

### How to Reproduce?

https://github.com/9too/quarkus-keycloak-issue

### Output of `uname -a` or `ver`

Linux 5.10.27-gentoo x86_64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz;

### Output of `java -version`

OpenJDK Runtime Environment 11.0.11_p9-r1 (build 11.0.11+9)

**Comment by 9too** [comment]
Someone double posted...
see https://github.com/quarkusio/quarkus/issues/20220
