### ISSUE TITLE
RestEasy reactive with smallrye metrics throws NoSuchMethodException

### ISSUE THREAD

**Issue by mswiderski** [quarkusio/quarkus#20229]
### Describe the bug

Running quarkus app in native mode with rest easy reactive and smallrye metrics.  Endpoint when invoked fails with following error

````
2021-09-17 09:38:08,156 ERROR [io.aut.eng.ser.exc.UnknownExceptionMapper] (executor-thread-0) Unexpected error processing request: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.acme.ScriptsResource.create_scripts(javax.ws.rs.core.HttpHeaders, java.lang.String, java.lang.String, java.util.List, org.acme.ScriptsModelInput)
	at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getMethod(ResteasyReactiveResourceInfo.java:70)
	at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getResourceMethod(ResteasyReactiveResourceInfo.java:101)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.getResourceMethod(ContextProducers_ProducerMethod_resourceInfo_be7f5503a87442251cde9fbc1d406fb350a529f0_ClientProxy.zig:89)
	at io.smallrye.metrics.jaxrs.JaxRsMetricsFilter.filter(JaxRsMetricsFilter.java:57)
	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:40)
	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:8)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.NoSuchMethodException: org.acme.ScriptsResource.create_scripts(javax.ws.rs.core.HttpHeaders, java.lang.String, java.lang.String, java.util.List, org.acme.ScriptsModelInput)
	at java.lang.Class.getMethod(DynamicHub.java:1120)
	at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getMethod(ResteasyReactiveResourceInfo.java:65)
	... 15 more
````

### Expected behavior

No errors are thrown and metrics for JAX-RS are collected

### Actual behavior

Error is thrown and service returns 500

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20

### GraalVM version (if different from Java)

GraalVM 21.2.0 Java 11 CE (Java Version 11.0.12+6-jvmci-21.2-b08)

### Quarkus version or git rev

2.2.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.6.3

### Additional information

https://groups.google.com/d/msgid/quarkus-dev/A1E3BF4D-ED44-499A-80C3-816577C3464C%40gmail.com

**Comment by geoand** [comment]
Thanks for reporting.

Are you registering the `JaxRsMetricsFilter` filter manually by any chance?

**Comment by mswiderski** [comment]
nope, was not even aware of that class until I saw it in the stack trace

**Comment by geoand** [comment]
I can get that class to be activated, so I am wondering what is going on...

**Comment by mswiderski** [comment]
I just noticed that it does fail like that also for resources from a dependency. Meaning I have another maven project that has REST resource class, that maven project contains `META-INF/beans.xml` but ends up with the same error. I will try to use this as reproducer and see if that fails on simple case. Will try to do it by the end of the day.

just wanted to add this as note...

**Comment by geoand** [comment]
Thanks!

**Comment by mswiderski** [comment]
@geoand no luck with simple reproducer :( could you maybe give me some hints to debug the process of collecting resources that should be registered for reflection? Maybe that way I could try to figure out why some classes are not there...

**Comment by geoand** [comment]
I would start with debugging `org.jboss.resteasy.reactive.common.processor.scanning.ResteasyReactiveInterceptorScanner#scanForInterceptors` and seeing if the filter in question is being picked up.

**Comment by ebullient** [comment]
Curious if you see this if you flip to the micrometer extension?

**Comment by mswiderski** [comment]
@ebullient there reason is I have to move to the micrometer as currently I still use these

````
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.eclipse.microprofile.metrics.Counter;
import org.eclipse.microprofile.metrics.Metadata;
import org.eclipse.microprofile.metrics.MetricRegistry;
import org.eclipse.microprofile.metrics.MetricType;
import org.eclipse.microprofile.metrics.Tag;
````

so it is not just to change the pom dependency :(

**Comment by ebullient** [comment]
The micrometer extension has a compat layer for the MP API. Just try it .;)

**Comment by mswiderski** [comment]
is that like another dependency?

**Comment by mswiderski** [comment]
In meantime this change made it to work https://github.com/mswiderski/quarkus/commit/f3661c767695807648767b7540127303b6fb381d

not sure though it is what it should be but looking at what `org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getMethod` does (looking up methods via reflection) I guess having these classes registered for it makes sense.

**Comment by ebullient** [comment]
> is that like another dependency?

nope. baked in. It is enabled if any MP Metrics usage is detected.

**Comment by geoand** [comment]
Yeah, but that is what we want to avoid :). We don't want to register things for reflection unless necessary. In your case, if we can find out why the filter is getting included, we can also register all the JAX-RS Resource classes for reflection.

**Comment by ebullient** [comment]
> In meantime this change made it to work [mswiderski@f3661c7](https://github.com/mswiderski/quarkus/commit/f3661c767695807648767b7540127303b6fb381d)
> 
> not sure though it is what it should be but looking at what `org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getMethod` does (looking up methods via reflection) I guess having these classes registered for it makes sense.

This is why I'm curious to see if Micrometer hits the issue, too. The smallrye metrics extension uses more reflection than micrometer does.. but this may be a case where resources need to be handled differently..

**Comment by mswiderski** [comment]
alright, let me try to move to micrometer then - stay tuned!

**Comment by geoand** [comment]
In general we detect when reflection is needed, but there might be cases we have missed. But if micrometer solves the problem, then all is good :)

**Comment by mswiderski** [comment]
so it does work indeed with micrometer extension instead! thanks a lot for the hint @ebullient 

I relied on the MP compatibility mode but need to look more into the micrometer api instead to do the same as I see on build following warning

````
[WARNING] [io.quarkus.micrometer.deployment.binder.mpmetrics.MicroprofileMetricsProcessor] This application uses the MP Metrics API. The micrometer extension currently provides a compatibility layer that supports the MP Metrics API, but metric names and recorded values will be different. Note that the MP Metrics compatibility layer will move to a different extension in the future.
````

**Comment by ebullient** [comment]
yep. 

There is a cost to using the wrapper (some extra objects are used), but we'll be supporting the MP Metrics API for a long while yet.  Please do look into it, but don't panic. ;)

**Comment by mswiderski** [comment]
Not afraid of support but more since the name of the metrics change anyway so better to move completely to micrometer and be done in one go

**Comment by mswiderski** [comment]
Just moved all my stuff to micrometer and it was easier than expected 

from my point of view this issue can be closed as the solution is to use micrometer extension instead of smallrye-metrics

thanks for really good support @ebullient @geoand

**Comment by geoand** [comment]
Thanks @mswiderski !
