### ISSUE TITLE
Quick starts example 'Using HTTP with Reactive Messaging' is not working 

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#20265]
### Describe the bug

Following ['Using HTTP with Reactive Messaging'](https://quarkus.io/guides/reactive-messaging-http.html) 
I cloned the repo and started the app. However, after clicking add price on [the HTML page](http://localhost:8080/index.html)
I get an error in log 

```java
2021-09-20 10:25:03,473 ERROR [io.qua.rea.htt.run.ReactiveHttpHandlerBean] (vert.x-eventloop-thread-13) Failed to process message.: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8081
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Expected behavior

the app should work as described in the guide

### How to Reproduce?

Follow [the guide](https://quarkus.io/guides/reactive-messaging-http.html)  by cloning the repo, checkout 2.2.3.Final tag and watch the console

**Comment by ozangunalp** [comment]
Seems like `quarkus.http.test-port` is provided even though you are not running the tests. @ennishol can you remove that from the `outgoing-costs.url` property in the `application.properties` and retry?

**Comment by ennishol** [comment]
@ozangunalp changed to `mp.messaging.outgoing.outgoing-costs.url=http://localhost:8080/cost-collector` still same error

**Comment by michalszynkiewicz** [comment]
I have just followed the quickstart and I cannot reproduce the problem.
@ennishol I think you'd have to share your project to get more help on this

**Comment by ennishol** [comment]
@ozangunalp actually removing `quarkus.http.test-port` did help. somehow the file was not saved by IDE.

**Comment by ozangunalp** [comment]
Cool! Then the question is why do the quarkus app launched in dev mode has the `quarkus.http.test-port` property defined? Or shall we use the property with profiles such as `%test.quarkus.http.test-port` ?
