### ISSUE TITLE
fabric8.certmanager extension: CertificateList cannot deserialize from Object value (no delegate- or property-based Creator)

### ISSUE THREAD

**Issue by matthyx** [quarkusio/quarkus#20267]
### Describe the bug

This only happens in the native version... I try to get a list of all `Certificates` in a namespace.

Stacktrace:
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.fabric8.certmanager.api.model.v1.CertificateList` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
at [Source: (BufferedInputStream); line: 1, column: 2]
at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1764)
at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1209)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3593)
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:261)
```

### How to Reproduce?

I have tried to make a reproducer here:
https://github.com/matthyx/quarkus-certmanager/blob/main/src/test/java/org/acme/GreetingResourceTest.java

However, the test resources are not initializing properly in native mode, so the error is different (but at least you can see the code).

Adding an entry in `reflection-config.json` for CertificateList is enough to make the real code working.

### Quarkus version or git rev

2.2.1.Final

### Additional information

Was first discussed in https://github.com/quarkusio/quarkus/issues/20200

**Comment by geoand** [comment]
Thanks for reporting.

In the real code, where is `CertificateList` used?
The reason I am asking is because if it is used only the body of some method, Quarkus doesn't know about it and therefore does not register it for reflection.
Furthermore, we don't register all the classes of the Kubernetes model for reflection, as that would result in a huge native binary.

Another workaround aside for the `reflection-config.json` file is to use `@RegisterForReflection#classNames`

**Comment by vsevel** [comment]
> Furthermore, we don't register all the classes of the Kubernetes model for reflection, as that would result in a huge native binary.

But that should not be the responsability of the developer to know what classes to register. Right?

Should there be a dedicated extension for the cert manager? That way we would register whatever is necessary for the app. WDYT?

**Comment by geoand** [comment]
> > Furthermore, we don't register all the classes of the Kubernetes model for reflection, as that would result in a huge native binary.
> 
> But that should not be the responsability of the developer to know what classes to register. Right?
> 

Yes, that does make sense. However due to what I mentioned above, it's not practical for the Kubernetes extension.
We only register for the model's classes for reflection when we they they are going to be used.


> Should there be a dedicated extension for the cert manager? That way we would register whatever is necessary for the app. WDYT?

What would this extension register? And under what circumstances?

**Comment by matthyx** [comment]
@geoand thanks for the suggestion, as planned if I add the annotation to the Java file where I use the certmanager client it works:
```
@RegisterForReflection(targets = {CertificateList.class, Map.class})
public class OpenShiftManager {
...
```

**Comment by vsevel** [comment]
> What would this extension register? And under what circumstances?

`CertificateList`, whenever the hypothetic `kubernetes-cert-manager` extension would be added as a dependency.
Registering ourselves in our app this class solves the issue for us, but others will have to do the same thing.
I understand we do not want to register by default all k8s model classes. but how do we make easy for people to use the cert manager feature, without knowing that they have to register `CertificateList` (and may be some other classes) if they want to work in native?

or should we leave the registration in the existing `kubernetes-client` extension, and add a build time property `quarkus.kubernetes.register-classes-for-cert-manager`?

what is the proper way to solve this?

**Comment by geoand** [comment]
I was going to suggest the property.  A new extension just for this is overkill
