### ISSUE TITLE
ConfigMapping throws crazy bytecode exception

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#20283]
### Describe the bug

Given the `@ConfigMapping` example in the Reproducer section, a massive exception is thrown on service startup.

### Expected behavior

Successful startup

### Actual behavior

```
2021-09-20 16:36:20,006 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    my/project/service3/Service3Handler$JmsConfig-1771651071Impl.<init>(Lio/smallrye/config/ConfigMappingContext;)V @523: aload_2
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @523
    flags: { }
    locals: { 'my/project/service3/Service3Handler$JmsConfig-1771651071Impl', 'io/smallrye/config/ConfigMappingContext', 'java/lang/StringBuilder', integer, 'java/util/List', 'java/lang/Object', integer, integer }
    stack: { }
  Stackmap Frame:
    bci: @523
    flags: { }
    locals: { 'my/project/service3/Service3Handler$JmsConfig-1771651071Impl', 'io/smallrye/config/ConfigMappingContext', 'java/lang/StringBuilder', integer, 'java/util/List', 'java/lang/Object', integer, integer }
    stack: { 'my/project/service3/Service3Handler$JmsConfig-1771651071Impl', 'my/project/service3/Service3Handler$JmsConfig-1771651071Impl' }
  Bytecode:
    0000000: 2ab7 000e 2bb6 0014 594d b600 1a3e 2a2c
    0000010: b600 1a99 000b 2c12 1e92 b600 2257 2c2b
    0000020: 1223 b600 27b6 002a 572b b600 2e2c b600
    0000030: 32b6 0038 3a04 123a b800 3e19 04b9 0041
    0000040: 0100 b900 4702 003a 0503 3606 1904 b900
    0000050: 4101 0036 0715 0615 07a2 0077 1904 1506
    0000060: b900 4a02 00c0 004c 3a08 2cb6 001a 3609
    0000070: bb00 1659 b700 4d12 4fb6 002a 1908 b600
    0000080: 5212 54b6 002a b600 323a 0a2c 190a b600
    0000090: 2a57 2b12 56b6 005a 3a0b 1905 c000 5c19
    00000a0: 0bb9 0060 0200 572b 1208 bb00 1659 b700
    00000b0: 4d12 23b6 002a 190a b600 2ab6 0032 2a19
    00000c0: 0bb6 0064 2c15 09b6 0068 8406 01a7 ff88
    00000d0: 1507 9a00 0d2a b800 6eb5 0070 a700 0c2a
    00000e0: 1905 b800 74b5 0070 2c1d b600 682a 2cb6
    00000f0: 001a 9900 0b2c 121e 92b6 0022 572c 2b12
    0000100: 76b6 0027 b600 2a57 2bb6 002e 2cb6 0032
    0000110: b600 383a 0412 3ab8 003e 1904 b900 4101
    0000120: 00b9 0047 0200 3a05 0336 0619 04b9 0041
    0000130: 0100 3607 1506 1507 a200 7719 0415 06b9
    0000140: 004a 0200 c000 4c3a 082c b600 1a36 09bb
    0000150: 0016 59b7 004d 124f b600 2a19 08b6 0052
    0000160: 1254 b600 2ab6 0032 3a0a 2c19 0ab6 002a
    0000170: 572b 1278 b600 5a3a 0b19 05c0 005c 190b
    0000180: b900 6002 0057 2b12 08bb 0016 59b7 004d
    0000190: 1276 b600 2a19 0ab6 002a b600 322a 190b
    00001a0: b600 642c 1509 b600 6884 0601 a7ff 8815
    00001b0: 079a 000d 2ab8 006e b500 7aa7 000c 2a19
    00001c0: 05b8 0074 b500 7a2c 1db6 0068 2a2c b600
    00001d0: 1a99 000b 2c12 1e92 b600 2257 2c2b 127d
    00001e0: b600 27b6 002a 572b b600 2e2c b600 322b
    00001f0: 1208 127d b600 81b6 0085 c000 87b6 008b
    0000200: b500 8da7 0008 2b5f b600 912c 1db6 0068
    0000210: b1                                     
  Exception Handler Table:
    bci [503, 518] => handler: 518
  Stackmap Table:
    full_frame(@30,{Object[#2],Object[#16],Object[#22],Integer},{Object[#2]})
    full_frame(@85,{Object[#2],Object[#16],Object[#22],Integer,Object[#58],Object[#4],Integer,Integer},{Object[#2]})
    same_locals_1_stack_item_extended(@208,Object[#2])
    same_locals_1_stack_item_frame(@223,Object[#2])
    same_locals_1_stack_item_frame(@232,Object[#2])
    full_frame(@253,{Object[#2],Object[#16],Object[#22],Integer,Object[#58],Object[#4],Integer,Integer},{Object[#2],Object[#2]})
    full_frame(@308,{Object[#2],Object[#16],Object[#22],Integer,Object[#58],Object[#4],Integer,Integer},{Object[#2],Object[#2]})
    full_frame(@431,{Object[#2],Object[#16],Object[#22],Integer,Object[#58],Object[#4],Integer,Integer},{Object[#2],Object[#2]})
    full_frame(@446,{Object[#2],Object[#16],Object[#22],Integer,Object[#58],Object[#4],Integer,Integer},{Object[#2],Object[#2]})
    full_frame(@455,{Object[#2],Object[#16],Object[#22],Integer,Object[#58],Object[#4],Integer,Integer},{Object[#2],Object[#2]})
    full_frame(@476,{Object[#2],Object[#16],Object[#22],Integer,Object[#58],Object[#4],Integer,Integer},{Object[#2],Object[#2],Object[#2]})
    same_locals_1_stack_item_frame(@518,Object[#147])
    full_frame(@523,{Object[#2],Object[#16],Object[#22],Integer,Object[#58],Object[#4],Integer,Integer},{Object[#2],Object[#2]})

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.base/java.lang.Class.getConstructor0(Unknown Source)
	at java.base/java.lang.Class.getDeclaredConstructor(Unknown Source)
	at io.smallrye.config.ConfigMappingLoader.configMappingObject(ConfigMappingLoader.java:58)
	at io.smallrye.config.ConfigMappingContext.constructGroup(ConfigMappingContext.java:80)
	at io.smallrye.config.ConfigMappingContext.constructRoot(ConfigMappingContext.java:76)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:811)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:794)
	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:54)
	at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:36)
	at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:81)
	at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy_0(ConfigBuildStep$registerConfigClasses-2116437784.zig:132)
	at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy(ConfigBuildStep$registerConfigClasses-2116437784.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:414)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
```

### How to Reproduce?

Reproducer: `service3` in https://github.com/mweber03/quarkus-test

1. `./gradlew service3:quarkusBuild`
2. `docker build -t service3 -f modules/service3/Dockerfile .`
3. `docker run -it -p 8080:8080 service3`

Code:

```java
    @ConfigMapping(prefix = "app.jms")
    interface JmsConfig {

        @WithDefault("true")
        boolean ignoreAnnotatedListeners();

        Optional<List<JmsSessionConfig>> sessions();
        Optional<List<JmsListenerConfig>> listeners();
    }

    interface JmsSessionConfig {
        Optional<String> name();
        Optional<String> uri();
        Optional<String> username();
        Optional<String> password();
        Optional<Integer> ackOption();
        Optional<String> connectionFactory();
    }

    interface JmsListenerConfig {

        @WithDefault("false")
        boolean disabled();

        @WithDefault("true")
        boolean ignoreAnnotated();

        String listenerClass();
        String session();
        Optional<Integer> poolSize();
        Optional<Boolean> async();
        Optional<List<String>> queues();
        Optional<List<String>> topics();
    }
```

### Output of `uname -a` or `ver`

Ubuntu 20.04

### Output of `java -version`

OpenJDK 11.0.11

### Quarkus version or git rev

2.2.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by radcortez** [comment]
This is an SR Config issue. This will fix it: https://github.com/smallrye/smallrye-config/pull/643.

**Comment by radcortez** [comment]
> @radcortez will we have SR Config `2.5.1` by next week so we can include it in `2.3.0.Final` (it's too late for `2.3.0.CR1`)?

Yes, I'll do one in the meanwhile. Just looking into other issue to see if it require any additional changes.

**Comment by geoand** [comment]
Great, thanks
