### ISSUE TITLE
ConfigMapping Optional in constructor injection error

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#20281]
### Describe the bug

When using `@ConfigMapping` on an `Optional` in constructor injection, there is a build error.

### Expected behavior

Successful build.

### Actual behavior

```
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ConfigBuildStep#generateConfigClasses threw an exception: java.lang.IllegalArgumentException: Not a class type!
        at org.jboss.jandex.Type.asClassType(Type.java:215)
        at io.quarkus.arc.deployment.ConfigBuildStep.generateConfigClasses(ConfigBuildStep.java:275)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### How to Reproduce?

Reproducer: `service5` in https://github.com/mweber03/quarkus-test

1. `./gradlew service5:quarkusBuild`

Code:
```java
    @Inject
    public Service5Handler(@ConfigMapping(prefix = "app.config") final Optional<Config> config) {
        if (config.isPresent()) {
            ...
        }
        else {
            ...
        }
    }

    /**
     * Configuration for JMS
     */
    interface Config {
        boolean enabled();
        String name();
        int num();
    }
```

The build NPEs when using:
```java
    @ConfigMapping(prefix = "app.config")
    private Optional<Config> config;
```

### Output of `uname -a` or `ver`

Ubuntu 20.04

### Output of `java -version`

OpenJDK 11.0.11

### Quarkus version or git rev

2.2.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by radcortez** [comment]
Hi @mweber03,

A `@ConfigMapping` or (Quarkus old `@ConfigProperties` and MP `@ConfigProperties`) are not meant to be used wrapped in an Optional. They are already a "container" type so any `Optional` configuration can be mapped inside the mapping / properties classes.

Can you please elaborate on why do you need to wrap the mapping in an `Optional`?

**Comment by mweber03** [comment]
@radcortez Basically my configuration may or may not contain `app.config`, which is why I was trying to wrap it in an `Optional`.

**Comment by radcortez** [comment]
Yes, you can do something like:

```
interface App {
```
