### ISSUE TITLE
ConfigMapping build error for List of Maps

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#20305]
### Describe the bug

I'm trying to get a `Map` of each set of configurations in a list, but there is an error on build. See the example in the reproducer section.

If there is a better way to do this let me know.

### Expected behavior

Successful build.

### Actual behavior

```
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ConfigBuildStep#generateConfigClasses threw an exception: java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl and java.lang.Class are in module java.base of loade
r 'bootstrap')
        at io.smallrye.config.ConfigMappingInterface.getPropertyDef(ConfigMappingInterface.java:643)
        at io.smallrye.config.ConfigMappingInterface.getProperties(ConfigMappingInterface.java:602)
        at io.smallrye.config.ConfigMappingInterface.createConfigurationInterface(ConfigMappingInterface.java:559)
        at io.smallrye.config.ConfigMappingInterface.access$000(ConfigMappingInterface.java:27)
        at io.smallrye.config.ConfigMappingInterface$1.computeValue(ConfigMappingInterface.java:32)
        at io.smallrye.config.ConfigMappingInterface$1.computeValue(ConfigMappingInterface.java:30)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at io.smallrye.config.ConfigMappingInterface.getConfigurationInterface(ConfigMappingInterface.java:61)
        at io.smallrye.config.ConfigMappingLoader.getConfigMappingsMetadata(ConfigMappingLoader.java:26)
        at io.quarkus.arc.deployment.ConfigBuildStep.generateConfigClasses(ConfigBuildStep.java:289)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### How to Reproduce?

Config:

```yaml
app:
  config:
    - name: Bob
      foo: thing
      bar: false
    - name: Tim
      baz: stuff
      qux: 3
```

Code:
```java
    @ConfigMapping(prefix = "app.config")
    interface MapConfig {
        List<Map<String, String>> mapConfigs();
    }
```

### Output of `uname -a` or `ver`

Ubuntu 20.04

### Output of `java -version`

OpenJDK 11.0.11

### Quarkus version or git rev

2.2.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by radcortez** [comment]
Yes, we don't support a combination of `List<Map<?, ?>`. I can probably add it, but I don't see much need, because it means you have an indexed followed by a name. If that is the case, why don't flatten this in all indexes or all key names? I guess is because you have dynamic properties and you don't know the key names?

**Comment by mweber03** [comment]
@radcortez yeah our properties are dynamic. Do you have any ideas of another way to solve this with the existing functionality?

**Comment by radcortez** [comment]
Are you able to flatten the collection and the map to be just a map? Is there any property that can be used as a unique key? Or it is really required a combination of index plus key?

**Comment by mweber03** [comment]
It's really a combination of index plus key. There's 1-to-N items that each have their own set of data.

**Comment by radcortez** [comment]
In that case, unless you can find a way to layer your configuration in a different way, we don't have a way to map that. I need to implement it.

**Comment by mweber03** [comment]
@radcortez It worked!
