### ISSUE TITLE
Null Pointer Exception when using Bean Validation and no @Produces

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#2031]
When using Bean Validation in a JAX-RS endpoint, if the endpoint is not annotated with `@Produces` then next exception is thrown:

```
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4323)
	at java.base/java.util.Arrays.asList(Arrays.java:4310)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor.getAccept(JaxrsEndPointValidationInterceptor.java:41)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor.validateMethodInvocation(JaxrsEndPointValidationInterceptor.java:30)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:270)
	at io.quarkus.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:149)
	at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:173)
	at org.acme.quickstart.GreetingResource_Subclass.createBeer(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
```

I think we should either send an exception explaining the reason or gently assume `application/json` if not specified.

Happy to provide a PR.

**Comment by gsmet** [comment]
Already fixed: https://github.com/quarkusio/quarkus/pull/2002 .

Not defining a `@Produces` should be supported even if it's *heavily* recommended to define it when building native applications (it allows to reduce the size of the image).

**Comment by gsmet** [comment]
Thanks for reporting it. I plan to release a 0.13.2 early next week.
