### ISSUE TITLE
Native image start error:  Hibernate Search application startup failure

### ISSUE THREAD

**Issue by fastluca** [quarkusio/quarkus#20310]
### Describe the bug

I'm building a native image which depends on Hibernate Search quarkus extension. At the image startup, it fails with the following error. I'm using quarkus version 2.2.3.Final.
`
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-09-21 15:55:31,631 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
2021-09-21 15:55:31,737 WARN  [io.qua.run.log.LoggingSetupRecorder] (main) Log level TRACE for category 'org.hibernate.search' set below minimum logging level DEBUG, promoting it to DEBUG
2021-09-21 15:55:31,739 WARN  [io.qua.run.log.LoggingSetupRecorder] (main) Log level TRACE for category 'org.zalando.logbook' set below minimum logging level DEBUG, promoting it to DEBUG
2021-09-21 15:55:32,288 DEBUG [org.hib.sea.map.orm.boo.imp.HibernateSearchIntegrator] (JPA Startup Thread: <default>) HSEARCH000034: Hibernate Search version 0.0.3
2021-09-21 15:55:32,293 DEBUG [org.hib.sea.map.orm.boo.imp.HibernateSearchIntegrator] (JPA Startup Thread: <default>) Hibernate Search event listeners activated
2021-09-21 15:55:33,447 DEBUG [org.hib.sea.map.orm.map.imp.HibernateOrmMapping] (JPA Startup Thread: <default>) HSEARCH000235: Default automatic indexing synchronization strategy set to 'AutomaticIndexingSynchronizationStrategy.sync()'.
2021-09-21 15:55:33,467 ERROR [org.hib.sea.eng.rep.spi.RootFailureCollector] (JPA Startup Thread: <default>) HSEARCH000521: Hibernate Search encountered a failure during bootstrap; continuing for now to list all problems, but the process will ultimately be aborted.
Context: default backend
Failure:: org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl (Caused by java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl)
        at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1158)
        at org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960)
        at java.security.AccessController.doPrivileged(AccessController.java:87)
        at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957)
        at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:624)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
        at org.apache.http.impl.client.AuthenticationStrategyImpl.<init>(AuthenticationStrategyImpl.java:69)
        at org.apache.http.impl.client.TargetAuthenticationStrategy.<init>(TargetAuthenticationStrategy.java:50)
        at org.elasticsearch.client.PersistentCredentialsAuthenticationStrategy.<init>(PersistentCredentialsAuthenticationStrategy.java:46)
        at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:212)
        at java.security.AccessController.doPrivileged(AccessController.java:87)
        at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:191)
        at org.hibernate.search.backend.elasticsearch.client.impl.ElasticsearchClientFactoryImpl.createClient(ElasticsearchClientFactoryImpl.java:185)
        at org.hibernate.search.backend.elasticsearch.client.impl.ElasticsearchClientFactoryImpl.create(ElasticsearchClientFactoryImpl.java:155)
        at org.hibernate.search.backend.elasticsearch.impl.ElasticsearchLinkImpl.onStart(ElasticsearchLinkImpl.java:136)
        at org.hibernate.search.backend.elasticsearch.impl.ElasticsearchBackendImpl.start(ElasticsearchBackendImpl.java:128)
        at org.hibernate.search.engine.common.impl.BackendNonStartedState.start(BackendNonStartedState.java:48)
        at org.hibernate.search.engine.common.impl.SearchIntegrationPartialBuildStateImpl$SearchIntegrationFinalizerImpl.finalizeIntegration(SearchIntegrationPartialBuildStateImpl.java:156)
        at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateOrmIntegrationBooterImpl.doBootSecondPhase(HibernateOrmIntegrationBooterImpl.java:284)
        at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateOrmIntegrationBooterImpl.bootNow(HibernateOrmIntegrationBooterImpl.java:221)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateSearchSessionFactoryObserver.sessionFactoryCreated(HibernateSearchSessionFactoryObserver.java:41)
        at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:394)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:71)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:67)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:149)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:58)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:71)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:212)
        at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1020)
        ... 34 more

`

### Expected behavior

It should run normally.

### Actual behavior

The applications doesn't start.

### How to Reproduce?

This is my pom dependencies:

`
<dependencies>

		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-crypto</artifactId>
			<version>5.5.2</version>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-hibernate-validator</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-openapi</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-hibernate-search-orm-elasticsearch</artifactId>
		</dependency>
		
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-jwt</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-jwt-build</artifactId>
		</dependency>

		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-oauth2</artifactId>
			<version>v2-rev157-1.25.0</version>
		</dependency>

		<dependency>
			<groupId>com.google.http-client</groupId>
			<artifactId>google-http-client-gson</artifactId>
			<version>1.39.2</version>
		</dependency>

		<dependency>
			<groupId>org.passay</groupId>
			<artifactId>passay</artifactId>
			<version>1.6.0</version>
		</dependency>

		<dependency>
			<groupId>com.google.http-client</groupId>
			<artifactId>google-http-client-apache-v2</artifactId>
			<version>1.39.2</version>
		</dependency>

		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>${org.mapstruct.version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy-jackson</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-client</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-client-jackson</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-amazon-lambda-rest</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-security-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-junit5</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-test-h2</artifactId>
			<scope>test</scope>
		</dependency>
`

### Output of `java -version`

OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode)

### Quarkus version or git rev

2.2.3-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

### Additional information

Running with quarkus:dev mode, it works fine.

**Comment by fastluca** [comment]
Solved applying the dependency management suggested in this link: https://quarkus.io/guides/logging#logging-adapters
