### ISSUE TITLE
Flaky MultiModuleIncludedBuildTest

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#20315]
### Description

This test is failing a lot recently, e.g.:
- https://github.com/quarkusio/quarkus/pull/20309#issuecomment-924371761
- https://github.com/quarkusio/quarkus/pull/20291#issuecomment-923685759

Usually you can then find something like the following in the log:
```
2021-09-21T04:39:20.1310473Z BUILD FAILED in 11s
2021-09-21T04:39:20.1311847Z [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 16.156 s <<< FAILURE! - in io.quarkus.gradle.devmode.MultiModuleIncludedBuildTest
2021-09-21T04:39:20.1314168Z [ERROR] io.quarkus.gradle.devmode.MultiModuleIncludedBuildTest.main  Time elapsed: 16.146 s  <<< FAILURE!
2021-09-21T04:39:20.1315640Z java.lang.AssertionError: 
2021-09-21T04:39:20.1316039Z 
2021-09-21T04:39:20.1316408Z Expecting actual:
2021-09-21T04:39:20.1316928Z   "BROKEN: quarkusDev mode has terminated"
2021-09-21T04:39:20.1317421Z to contain:
2021-09-21T04:39:20.1317762Z   "foo bar" 
2021-09-21T04:39:20.1319639Z 	at io.quarkus.gradle.devmode.MultiModuleIncludedBuildTest.testDevMode(MultiModuleIncludedBuildTest.java:24)
```
and before that many errors liek the following:
```
Cause 22: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve io.quarkus:quarkus-vertx:999-SNAPSHOT.
Required by:
    project : > io.quarkus:quarkus-bom:999-SNAPSHOT
Caused by: org.gradle.internal.component.AmbiguousConfigurationSelectionException: Cannot choose between the following variants of io.quarkus:quarkus-vertx:999-SNAPSHOT:
  - io.quarkus:quarkus-vertx-deployment:999-SNAPSHOT
All of them match the consumer attributes:
  - Variant 'io.quarkus:quarkus-vertx-deployment:999-SNAPSHOT' capabilities io.quarkus:quarkus-vertx-deployment-capability:999-SNAPSHOT and io.quarkus:quarkus-vertx-deployment-capability:999-SNAPSHOT:
      - Unmatched attribute:
          - Provides org.gradle.status 'integration' but the consumer didn't ask for it
	at org.gradle.internal.component.model.AttributeConfigurationSelector.selectConfigurationUsingAttributeMatching(AttributeConfigurationSelector.java:105)
```

**Comment by glefloch** [comment]
Thanks for creating the issue @famod I will have a look at this test.

**Comment by aloubyansky** [comment]
@glefloch i've seen it failing this way locally quite a few times recently but i wasn't sure whether it was due to my local changes or not. It's just FYI, it occasionally can be reproduced locally.
