### ISSUE TITLE
Resteasy Reactive: `ServerExceptionMapper` does not process a thrown `Exception` (Kotlin only)

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#20357]
### Describe the bug

If a (Kotlin-)Rest-Endpoint throws an `java.lang.Exception` then the `Exception` does not get processed by a custom `ServerExceptionMapper`. `RuntimeException` works as excepted.

```kotlin
org.acme.MyException
	at org.acme.ExceptionTestResource.throwException1Method(ExceptionTestResource.kt:33)
	at org.acme.ExceptionTestResource_Subclass.throwException1Method$$superforward1(ExceptionTestResource_Subclass.zig:113)
	at org.acme.ExceptionTestResource_Subclass$$function$$1.apply(ExceptionTestResource_Subclass$$function$$1.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.ExceptionTestResource_Subclass.throwException1Method(ExceptionTestResource_Subclass.zig:183)
	at org.acme.ExceptionTestResource_ClientProxy.throwException1Method(ExceptionTestResource_ClientProxy.zig:185)
	at org.acme.ExceptionTestResource$quarkusrestinvoker$throwException1Method_4a04d16e4f5785de322606c51c7fc425b79facd0.invoke(ExceptionTestResource$quarkusrestinvoker$throwException1Method_4a04d16e4f5785de322606c51c7fc425b79facd0.zig:33)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Resulted in: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
	at org.acme.ExceptionTestResource_Subclass.throwException1Method(ExceptionTestResource_Subclass.zig:205)
	... 12 more
```

### How to Reproduce?

1. https://code.quarkus.io/?e=resteasy-reactive-jackson&e=kotlin&extension-search=kotlin
2. Add the following code

```kotlin
package org.acme

import org.jboss.resteasy.reactive.server.ServerExceptionMapper
import javax.enterprise.context.ApplicationScoped
import javax.ws.rs.GET
import javax.ws.rs.Path
import javax.ws.rs.core.Response

open class SuperException : Exception() // Works if SuperException extends RuntimeException instead of Exception
class MyException : SuperException()

class ExceptionMappers {

    @ServerExceptionMapper
    fun superExceptionHandler(ex: SuperException): Response {
        println("SuperException processed")
        return Response.serverError().build()
    }
}

@ApplicationScoped
@Path("/ex")
class ExceptionTestResource {

    /**
     * Exception is not processed by the ServerExceptionMapper.
     */
    @GET
    @Path("/throw1")
    fun throwException1Method(): String {
        throw MyException()
    }

    /**
     * Exception is processed by the ServerExceptionMapper.
     */
    @GET
    @Path("/throw2")
    @Throws(MyException::class) // see here
    fun throwExceptionMethod(): String {
        throw MyException()
    }
}
```

### Output of `java -version`

Java 11

### Quarkus version or git rev

Quarkus 2.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by geoand** [comment]
I can't reproduce this problem with the snippets included in the description.

Please attach a project that exhibits this behavior (ideally with failing tests).

**Comment by mschorsch** [comment]
I've made a reproducer (see attached), including some tests.

Please note that unfortunately __the tests do not fail__. The problem can only be reproduced in __dev mode__.

Run `./mvnw quarkus:dev` call `http://localhost:8080/ex/throw1` then you get the following exception (console log):

```java
2021-09-23 16:01:39,381 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /ex/throw1 failed, error id: 4c3eb23b-e454-43fb-9c2c-96d44e308b1f-1: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
	at org.acme.ExceptionTestResource_Subclass.throwException1Method(ExceptionTestResource_Subclass.zig:205)
	at org.acme.ExceptionTestResource_ClientProxy.throwException1Method(ExceptionTestResource_ClientProxy.zig:185)
	at org.acme.ExceptionTestResource$quarkusrestinvoker$throwException1Method_4a04d16e4f5785de322606c51c7fc425b79facd0.invoke(ExceptionTestResource$quarkusrestinvoker$throwException1Method_4a04d16e4f5785de322606c51c7fc425b79facd0.zig:33)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.acme.MyException
	at org.acme.ExceptionTestResource.throwException1Method(ExceptionTestResource.kt:30)
	at org.acme.ExceptionTestResource_Subclass.throwException1Method$$superforward1(ExceptionTestResource_Subclass.zig:113)
	at org.acme.ExceptionTestResource_Subclass$$function$$1.apply(ExceptionTestResource_Subclass$$function$$1.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.ExceptionTestResource_Subclass.throwException1Method(ExceptionTestResource_Subclass.zig:183)
	... 12 more

2021-09-23 16:01:39,390 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
	at org.acme.ExceptionTestResource_Subclass.throwException1Method(ExceptionTestResource_Subclass.zig:205)
	at org.acme.ExceptionTestResource_ClientProxy.throwException1Method(ExceptionTestResource_ClientProxy.zig:185)
	at org.acme.ExceptionTestResource$quarkusrestinvoker$throwException1Method_4a04d16e4f5785de322606c51c7fc425b79facd0.invoke(ExceptionTestResource$quarkusrestinvoker$throwException1Method_4a04d16e4f5785de322606c51c7fc425b79facd0.zig:33)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.acme.MyException
	at org.acme.ExceptionTestResource.throwException1Method(ExceptionTestResource.kt:30)
	at org.acme.ExceptionTestResource_Subclass.throwException1Method$$superforward1(ExceptionTestResource_Subclass.zig:113)
	at org.acme.ExceptionTestResource_Subclass$$function$$1.apply(ExceptionTestResource_Subclass$$function$$1.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.ExceptionTestResource_Subclass.throwException1Method(ExceptionTestResource_Subclass.zig:183)
	... 12 more
```

[reproducer20357.zip](https://github.com/quarkusio/quarkus/files/7218182/reproducer20357.zip)

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/20364 takes care of the issue
