### ISSUE TITLE
"Hibernate Reactive with PANACHE" No annotation @ProjectedFieldName 

### ISSUE THREAD

**Issue by liuzhaozhao** [quarkusio/quarkus#20372]
### Describe the bug

When I only use Hibernate Reactive, there is no @ProjectedFieldName in the imported jar, resulting in a compilation error; when I import the jar package "quarkus-hibernate-orm-panache-common" that contains @ProjectedFieldName, another error occurs:

```
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'mysql' for the default datasource. Either provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource.jdbc=false' to your configuration if you don't need it.
	at io.quarkus.agroal.deployment.AgroalProcessor.resolveDriver(AgroalProcessor.java:334)
	at io.quarkus.agroal.deployment.AgroalProcessor.getAggregatedConfigBuildItems(AgroalProcessor.java:280)
	at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

Is it necessary to put @ProjectedFieldName in "quarkus-hibernate-reactive-panache-common"？

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22000.168]

### Output of `java -version`

java version "11.0.10" 2021-01-19

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by loicmathieu** [comment]
`quarkus-hibernate-orm-panache-common` is for Hibernate ORM, it's an inner dependency so it must never be imported directly.

It appears the functionality behing `@ProjectedFieldName` is missing in Hibernate reactive. I change the type of issue to enhancement request as it's not a bug per se.
