### ISSUE TITLE
jbang app install quarkus,but  catalog 'quarkusio' not found

### ISSUE THREAD

**Issue by liononon** [quarkusio/quarkus#20403]
### Describe the bug

jbang app install --fresh --force --verbose quarkus@quarkusio
[jbang] jbang version 0.80.2
[jbang] Duplicating classpath resource jbang-catalog.json
[jbang] Reading catalog from ~/.jbang/cache/urls/2c97f3a787487bf73b7f4d02e109487e0e43be594ef95072827efd1500cd99ae
[jbang] Local catalog 'quarkusio' not found, trying implicit catalogs...
[jbang] No catalog found at https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json
dev.jbang.cli.ExitException: Could not download https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json
	at dev.jbang.source.ResourceRef.fetchFromURL(ResourceRef.java:329)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:237)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:153)
	at dev.jbang.catalog.Catalog.getByRef(Catalog.java:191)
	at dev.jbang.catalog.ImplicitCatalogRef.tryDownload(ImplicitCatalogRef.java:80)
	at dev.jbang.catalog.ImplicitCatalogRef.lambda$getImplicitCatalogUrl$0(ImplicitCatalogRef.java:68)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at dev.jbang.catalog.ImplicitCatalogRef.getImplicitCatalogUrl(ImplicitCatalogRef.java:74)
	at dev.jbang.catalog.CatalogRef.get(CatalogRef.java:57)
	at dev.jbang.catalog.Catalog.getByName(Catalog.java:144)
	at dev.jbang.catalog.Alias.fromCatalog(Alias.java:169)
	at dev.jbang.catalog.Alias.merge(Alias.java:124)
	at dev.jbang.catalog.Alias.get(Alias.java:82)
	at dev.jbang.source.Source.forResource(Source.java:149)
	at dev.jbang.cli.AppInstall.install(App.java:101)
	at dev.jbang.cli.AppInstall.doCall(App.java:81)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.JBang$3.handle(JBang.java:135)
	at dev.jbang.cli.JBang$3.handle(JBang.java:130)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at dev.jbang.util.Util.downloadFile(Util.java:567)
	at dev.jbang.util.Util.downloadFile(Util.java:529)
	at dev.jbang.util.Util.downloadFileAndCache(Util.java:704)
	at dev.jbang.util.Util.downloadAndCacheFile(Util.java:676)
	at dev.jbang.source.ResourceRef.fetchFromURL(ResourceRef.java:326)
	... 34 more
[jbang] Redirected to: https://github.com/jbangdev/jbang/releases/latest/download/version.txt
[jbang] Redirected to: https://gitlab.com/users/sign_in
[jbang] No catalog found at https://gitlab.com/quarkusio/jbang-catalog/-/blob/HEAD/jbang-catalog.json
dev.jbang.cli.ExitException: Could not download https://gitlab.com/quarkusio/jbang-catalog/-/blob/HEAD/jbang-catalog.json
	at dev.jbang.source.ResourceRef.fetchFromURL(ResourceRef.java:329)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:237)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:153)
	at dev.jbang.catalog.Catalog.getByRef(Catalog.java:191)
	at dev.jbang.catalog.ImplicitCatalogRef.tryDownload(ImplicitCatalogRef.java:80)
	at dev.jbang.catalog.ImplicitCatalogRef.lambda$getImplicitCatalogUrl$2(ImplicitCatalogRef.java:70)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at dev.jbang.catalog.ImplicitCatalogRef.getImplicitCatalogUrl(ImplicitCatalogRef.java:74)
	at dev.jbang.catalog.CatalogRef.get(CatalogRef.java:57)
	at dev.jbang.catalog.Catalog.getByName(Catalog.java:144)
	at dev.jbang.catalog.Alias.fromCatalog(Alias.java:169)
	at dev.jbang.catalog.Alias.merge(Alias.java:124)
	at dev.jbang.catalog.Alias.get(Alias.java:82)
	at dev.jbang.source.Source.forResource(Source.java:149)
	at dev.jbang.cli.AppInstall.install(App.java:101)
	at dev.jbang.cli.AppInstall.doCall(App.java:81)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.JBang$3.handle(JBang.java:135)
	at dev.jbang.cli.JBang$3.handle(JBang.java:130)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: java.io.FileNotFoundException: No file to download at https://gitlab.com/users/sign_in. Server replied HTTP code: 503
	at dev.jbang.util.Util.downloadFile(Util.java:609)
	at dev.jbang.util.Util.downloadFile(Util.java:529)
	at dev.jbang.util.Util.downloadFileAndCache(Util.java:704)
	at dev.jbang.util.Util.downloadAndCacheFile(Util.java:676)
	at dev.jbang.source.ResourceRef.fetchFromURL(ResourceRef.java:326)
	... 34 more
[jbang] No catalog found at https://bitbucket.org/quarkusio/jbang-catalog/src/HEAD/jbang-catalog.json
dev.jbang.cli.ExitException: Could not download https://bitbucket.org/quarkusio/jbang-catalog/src/HEAD/jbang-catalog.json
	at dev.jbang.source.ResourceRef.fetchFromURL(ResourceRef.java:329)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:237)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:153)
	at dev.jbang.catalog.Catalog.getByRef(Catalog.java:191)
	at dev.jbang.catalog.ImplicitCatalogRef.tryDownload(ImplicitCatalogRef.java:80)
	at dev.jbang.catalog.ImplicitCatalogRef.lambda$getImplicitCatalogUrl$4(ImplicitCatalogRef.java:72)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at dev.jbang.catalog.ImplicitCatalogRef.getImplicitCatalogUrl(ImplicitCatalogRef.java:74)
	at dev.jbang.catalog.CatalogRef.get(CatalogRef.java:57)
	at dev.jbang.catalog.Catalog.getByName(Catalog.java:144)
	at dev.jbang.catalog.Alias.fromCatalog(Alias.java:169)
	at dev.jbang.catalog.Alias.merge(Alias.java:124)
	at dev.jbang.catalog.Alias.get(Alias.java:82)
	at dev.jbang.source.Source.forResource(Source.java:149)
	at dev.jbang.cli.AppInstall.install(App.java:101)
	at dev.jbang.cli.AppInstall.doCall(App.java:81)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.JBang$3.handle(JBang.java:135)
	at dev.jbang.cli.JBang$3.handle(JBang.java:130)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: java.io.FileNotFoundException: No file to download at https://bitbucket.org/quarkusio/jbang-catalog/raw/HEAD/jbang-catalog.json. Server replied HTTP code: 404
	at dev.jbang.util.Util.downloadFile(Util.java:609)
	at dev.jbang.util.Util.downloadFile(Util.java:529)
	at dev.jbang.util.Util.downloadFileAndCache(Util.java:704)
	at dev.jbang.util.Util.downloadAndCacheFile(Util.java:676)
	at dev.jbang.source.ResourceRef.fetchFromURL(ResourceRef.java:326)
	... 34 more
[jbang] [ERROR] Unknown catalog 'quarkusio'
dev.jbang.cli.ExitException: Unknown catalog 'quarkusio'
	at dev.jbang.catalog.Catalog.getByName(Catalog.java:148)
	at dev.jbang.catalog.Alias.fromCatalog(Alias.java:169)
	at dev.jbang.catalog.Alias.merge(Alias.java:124)
	at dev.jbang.catalog.Alias.get(Alias.java:82)
	at dev.jbang.source.Source.forResource(Source.java:149)
	at dev.jbang.cli.AppInstall.install(App.java:101)
	at dev.jbang.cli.AppInstall.doCall(App.java:81)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.JBang$3.handle(JBang.java:135)
	at dev.jbang.cli.JBang$3.handle(JBang.java:130)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues

**Comment by maxandersen** [comment]
Are you behind a proxy or something? 

It's complaining about not being able to download a url that most definitely exist ?

**Comment by maxandersen** [comment]
Just tested locally and I cannot reproduce.

Looking at the logs I see:

```
[jbang] Redirected to: jbangdev/jbang/releases/latest/download/version.txt
[jbang] Redirected to: gitlab.com/users/sign_in
[jbang] No catalog found at gitlab.com/quarkusio/jbang-catalog/-/blob/HEAD/jbang-catalog.json
dev.jbang.cli.ExitException: Could not download gitlab.com/quarkusio/jbang-catalog/-/blob/HEAD/jbang-catalog.json
```

which makes no sense unless github.com was down or you are behind a proxy of some sort.

Can you try again and/or outline what kind of proxy/firewall you are running this behind ?

**Comment by gsmet** [comment]
I believe this has been fixed.
