### ISSUE TITLE
Not able to debug/run tests in all IDEs

### ISSUE THREAD

**Issue by ppatierno** [quarkusio/quarkus#20415]
I am using Quarkus 2.2.2.Final for a project and having issues to run unit tests marked as `QuarkusTest` from IDEs (IntelliJ, Eclipse and VSCode). Everything works just fine from command line using maven.

With IntelliJ, when I run the class hosting the unit tests, I got a generic

```shell
java: Compilation failed: internal java compiler error
```

The only way to workaround this, as suggested by @metacosm is enabling `Delegate IDE build/run actions to Maven` in Build, Execution, Deployment > Build Tools > Maven > Runner settings. It was long time that I run these unit test and I remember that I didn't need that workaround before updating to 2.x version.

In VSCode so even in Eclipse (some colleagues of mine), we got a more explicit:

```shell
java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors

 [error]: Build step io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor#createConfigurationServiceAndOperator threw an exception: java.lang.IllegalArgumentException: io.quarkus.deployment.util.JandexUtil$ClassNotIndexedException

 at io.quarkus.deployment.util.JandexUtil.resolveTypeParameters(JandexUtil.java:74)

 at io.quarkiverse.operatorsdk.deployment.OperatorSDKProcessor.createControllerConfiguration(OperatorSDKProcessor.java:270)
```

Are there any settings for having Quarkus run/debug unit tests back working in IDEs?

**Comment by geoand** [comment]
I use IntelliJ and it works just fine out of the box.

What are the steps you follow to reproduce this?

**Comment by metacosm** [comment]
@geoand do you delegate run/build actions to Maven?

**Comment by geoand** [comment]
Nope.

**Comment by stuartwdouglas** [comment]
This looks like something specific to `OperatorSDKProcessor` when running from the IDE, do you have a reproducer?

**Comment by metacosm** [comment]
> This looks like something specific to `OperatorSDKProcessor` when running from the IDE, do you have a reproducer?

Yes, for some reason there seems to be some weird interaction between running the `OperatorSDKProcessor` in the IDE and Jandex… Not sure why it works in a "straight" maven setup though and not in the IDE.

**Comment by geoand** [comment]
If we get access to a repo that reproduces the problem, we'll likely be able to tell you exactly what is going on.

**Comment by geoand** [comment]
After looking into this, this turns out to be an issue with the generated Jandex index for one of the modules of the multi-module project.

Essentially for the build step to work (whether the build is initiated from Maven or the IDE), the Jandex index of the dependent Maven module needs to be present in `target/META-INF/jandex.idx` of that module.
So when launching tests for the top-level module, you need to make sure the aforementioned index has been previously created (it normally happens on the `process-classes` Maven phase)

**Comment by geoand** [comment]
For posterity, it should also be mentioned that using the `META-INF/beans.xml` file (as mentioned [here](https://quarkus.io/guides/cdi-reference#bean_discovery)) instead of the Jandex Maven plugin approach, will eliminate all the timing related issues.
