### ISSUE TITLE
quarkus:dev command input hangs when there is an Exception on application startup

### ISSUE THREAD

**Issue by murphye** [quarkusio/quarkus#20423]
### Describe the bug

OK, this is a bad bug that majorly impacts usability.

I have a Quarkus app that throws an exception on startup. After that happens, I cannot use any of the commands such as

```
Press [r] to resume testing, [o] Toggle test output, [h] for more options>
```

Nothing works, not even CTRL+C to try to escape out of it. Only option is to use the `kill` command for `java` processes for Maven and the app to get my terminal back.

### Expected behavior

Can continue to use `quarkus:dev` after an Exception is thrown. Command line inputs would still be recognized.

### Actual behavior

Terminal commands no longer work for quarkus:dev`. Terminal is hung completely forcing me to use `kill`.

### How to Reproduce?

I am using Mac OS and VS Code integrated terminal. Using `OpenJDK Runtime Environment (build 16.0.1+9-24)` 

Using Quarkus `2.3.0.CR1`.

Checkout this branch:
https://github.com/murphye/vertx-web-openapi-quarkus-petstore/tree/quarkus-dev-hang

`./mvnw quarks:dev`

Exception is thrown on startup, to be expected: `java.lang.IllegalArgumentException`

Now, here is the problem.. **terminal is hung**. No commands are able to be inputted on the terminal. Only way out of it is to `kill` the Java processes running Maven.

### Output of `uname -a` or `ver`

Darwin erics-mbp-2.lan 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment (build 16.0.1+9-24) OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

### Quarkus version or git rev

2.3.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by murphye** [comment]
Here is the stack trace for the Exception that happens on startup, for what it's worth.

The fact that there is an Exception is NOT the problem. The problem is loss of control of the command line after this Exception happens.

Could the fact that this error stems from Vert.x and Netty be a clue on why the Exception is causing hanging on the terminal as described? 

```
2021-09-27 21:53:29,481 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.opentelemetry.propagators" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-09-27 21:53:30,272 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-0) Uncaught exception received by Vert.x: java.lang.RuntimeException: Failed to resolve path from https://raw.githubusercontent.com/murphye/vertx-web-openapi-quarkus-petstore/main/src/main/resources/META-INF/openapi.yaml
        at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.uriToPath(OpenAPIHolderImpl.java:387)
        at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.resolveContainingDirPath(OpenAPIHolderImpl.java:392)
        at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.lambda$loadOpenAPI$0(OpenAPIHolderImpl.java:75)
        at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
        at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.Promise.complete(Promise.java:66)
        at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.lambda$null$7(OpenAPIHolderImpl.java:317)
        at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:81)
        at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:260)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:22)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:79)
        at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:250)
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:373)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
        at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:588)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71)
        at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:267)
        at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:822)
        at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:694)
        at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:658)
        at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalArgumentException: unsupported scheme type for 'https://raw.githubusercontent.com/murphye/vertx-web-openapi-quarkus-petstore/main/src/main/resources/META-INF/openapi.yaml'
        at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.uriToPath(OpenAPIHolderImpl.java:384)
        ... 62 more
```

**Comment by stuartwdouglas** [comment]
@cescoffier it looks like `io.vertx.mutiny.ext.web.openapi.RouterBuilder#createAndAwait(io.vertx.mutiny.core.Vertx, java.lang.String)` is not unblocking on exception, which causes the main thread to hang indefinitely.

**Comment by cescoffier** [comment]
That would be weird as all andAwait methods are generated the same way. I fear the exception is not reported the right way (which would be a bug in vertx). I will investigate.

**Comment by cescoffier** [comment]
So the issue is in Vert.x:

```
2021-10-04 07:46:44,150 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-0) Uncaught exception received by Vert.x
```

The error is not propagated to the handler. 

I've opened https://github.com/vert-x3/vertx-web/issues/2060.

**Comment by cescoffier** [comment]
Fixed in Vert.x 3.4.5, so will be fixed once we update to that version.
