### ISSUE TITLE
RESTEASY003340: Failure parsing MediaType string

### ISSUE THREAD

**Issue by flucciarini** [quarkusio/quarkus#20456]
### Describe the bug

I'm using quarkus rest client (quarkus platform1.13.3Final).
If I call a rest api that haven't Content/type I have the error in description

Below Rest-client declaration and error log

```
@PUT
 @Path("/device/name/{thingName}/command/{propertyName}")
@Consumes("application/json")
@Produces("*/*")
 Object setCommandValue(@PathParam String thingName, @PathParam String propertyName, String body);
```

```
_2021-09-29 14:21:14,980 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 >> PUT /api/v1/device/name/S-MAUROTORIN-L0B_CDZ-CRAC_1/command/S-MAUROTORIN-L0B_CDZ-CRAC_1__CMP_SET HTTP/1.1
2021-09-29 14:21:14,981 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 >> Accept: text/plain
2021-09-29 14:21:14,981 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 >> Content-Type: application/json
2021-09-29 14:21:14,982 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 >> Content-Length: 45
2021-09-29 14:21:14,982 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 >> Host: edgex-core-command:48082
2021-09-29 14:21:14,982 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 >> Connection: Keep-Alive
2021-09-29 14:21:14,983 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 >> User-Agent: Apache-HttpClient/4.5.13 (Java/11.0.11)
2021-09-29 14:21:14,983 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 >> "PUT /api/v1/device/name/S-MAUROTORIN-L0B_CDZ-CRAC_1/command/S-MAUROTORIN-L0B_CDZ-CRAC_1__CMP_SET HTTP/1.1[\r][\n]"
2021-09-29 14:21:14,984 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 >> "Accept: text/plain[\r][\n]"
2021-09-29 14:21:14,984 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 >> "Content-Type: application/json[\r][\n]"
2021-09-29 14:21:14,985 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 >> "Content-Length: 45[\r][\n]"
2021-09-29 14:21:14,985 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 >> "Host: edgex-core-command:48082[\r][\n]"
2021-09-29 14:21:14,985 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
2021-09-29 14:21:14,986 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 >> "User-Agent: Apache-HttpClient/4.5.13 (Java/11.0.11)[\r][\n]"
2021-09-29 14:21:14,986 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 >> "[\r][\n]"
2021-09-29 14:21:14,986 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 >> "{"S-MAUROTORIN-L0B_CDZ-CRAC_1__CMP_SET":"29"}"
2021-09-29 14:21:15,035 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 << "HTTP/1.1 200 OK[\r][\n]"
**2021-09-29 14:21:15,035 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 << "Content-Type: [\r][\n]"**
2021-09-29 14:21:15,036 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 << "Date: Wed, 29 Sep 2021 14:21:15 GMT[\r][\n]"
**2021-09-29 14:21:15,036 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 << "Content-Length: 0[\r][\n]"
2021-09-29 14:21:15,037 DEBUG [org.apa.htt.wire] (executor-thread-1) http-outgoing-1 << "[\r][\n]"**
2021-09-29 14:21:15,037 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 << HTTP/1.1 200 OK
2021-09-29 14:21:15,037 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 << Content-Type:
2021-09-29 14:21:15,038 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 << Date: Wed, 29 Sep 2021 14:21:15 GMT
2021-09-29 14:21:15,038 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 << Content-Length: 0
2021-09-29 14:21:15,038 DEBUG [org.apa.htt.imp.exe.MainClientExec] (executor-thread-1) Connection can be kept alive indefinitely
2021-09-29 14:21:15,039 DEBUG [org.apa.htt.imp.con.PoolingHttpClientConnectionManager] (executor-thread-1) Connection [id: 1][route: {}->http://edgex-core-command:48082] can be kept alive indefinitely
2021-09-29 14:21:15,039 DEBUG [org.apa.htt.imp.con.DefaultManagedHttpClientConnection] (executor-thread-1) http-outgoing-1: set socket timeout to 0
2021-09-29 14:21:15,040 DEBUG [org.apa.htt.imp.con.PoolingHttpClientConnectionManager] (executor-thread-1) Connection released: [id: 1][route: {}->http://edgex-core-command:48082][total available: 1; route allocated: 1 of 50; total allocated: 1 of 50]
2021-09-29 14:21:15,058 DEBUG [io.net.han.ssl.SslHandler] (NettyClient-NIO-1) [id: 0x0a5f80fd, L:/172.20.0.15:34342 - R:/10.153.4.140:8180] HANDSHAKEN: protocol:TLSv1.2 cipher suite:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
**2021-09-29 14:21:15,061 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /api/v1/edge/setValue/S-MAUROTORIN-L0B_CDZ-CRAC_1/command/CMP_SET failed, error id: c3cb37e0-04da-4fa3-9939-45dce6ff2276-1: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: RESTEASY003340: Failure parsing MediaType string:**
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.IllegalArgumentException: RESTEASY003340: Failure parsing MediaType string:
        at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.internalParse(MediaTypeHeaderDelegate.java:96)
        at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.parse(MediaTypeHeaderDelegate.java:69)
        at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:33)
        at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:19)
        at javax.ws.rs.core.MediaType.valueOf(MediaType.java:172)
        at org.jboss.resteasy.specimpl.AbstractBuiltResponse.getMediaType(AbstractBuiltResponse.java:342)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:204)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:62)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:151)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy26.setCommandValue(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:147)
        at com.sun.proxy.$Proxy29.setCommandValue(Unknown Source)
        at it.sirti.iot.ptcupdatepropertyvalues.client.CommandClient.setCommandValue(CommandClient.java:29)
        at it.sirti.iot.ptcupdatepropertyvalues.service.EdgeEventService.setValue(EdgeEventService.java:324)
        at it.sirti.iot.ptcupdatepropertyvalues.controller.EdgeController.setValue(EdgeController.java:91)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)_
```

### Output of `uname -a` or `ver`

Linux TO554-GW-1 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "1.8.0_172" Java(TM) SE Runtime Environment (build 1.8.0_172-b11) Java HotSpot(TM) Server VM (build 25.172-b11, mixed mode)

### Quarkus version or git rev

1.13.3Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

I deploy like fast-jar

**Comment by geoand** [comment]
Does the same thing happen with newer versions of Quarkus?

**Comment by gsmet** [comment]
My guess is that the server is providing an empty content type, given the error message.

Any way, no answer to our question and no reproducer to check ourselves so let's close.

**Comment by raycola** [comment]
Well, the empty content type is the cause of the problem
2021-09-29 14:21:15,037 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 << HTTP/1.1 200 OK
2021-09-29 14:21:15,037 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 << Content-Type:
2021-09-29 14:21:15,038 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 << Date: Wed, 29 Sep 2021 14:21:15 GMT
2021-09-29 14:21:15,038 DEBUG [org.apa.htt.headers] (executor-thread-1) http-outgoing-1 << Content-Length: 0

but the solution needs to be found and @gsmet what do you think about?

Therefore this is the exception:
java.lang.IllegalArgumentException: RESTEASY003340: Failure parsing MediaType string

@flucciarini, you can change Object response type for setCommandValue(...)  with void!

You can rewrite it in this way:
```
@PUT
@Path("/device/name/{thingName}/command/{propertyName}")
@Consumes("application/json")
void setCommandValue(@PathParam String thingName, @PathParam String propertyName, String body);
```
Have a nice day!
Ray
