### ISSUE TITLE
Gradle plugin resp. `quarkusBuild` task does not honor toolchain definitions

### ISSUE THREAD

**Issue by twwwt** [quarkusio/quarkus#20452]
### Describe the bug

Given a Gradle project that specifies a [`toolchain`](https://docs.gradle.org/current/userguide/toolchains.html), the `quarkusBuild` task fails if the Java version used to *run* Gradle differs from the version used to *compile* sources. In particular this bug has been observed when
```gradle
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}
```
was specified in a `build.gradle` file (i.e., use Java 17 to compile (and test) sources) while Gradle itself ran with Java 11; i.e.,
```
$ gradle --version
------------------------------------------------------------
Gradle 6.9.1
------------------------------------------------------------

Build time:   2021-08-20 11:15:18 UTC
Revision:     f0ddb54aaae0e44f0a7209c3c0274d506ea742a0

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.12 (Oracle Corporation 11.0.12+8-LTS-237)
OS:           Mac OS X 11.5 x86_64
```

In such a situation the `quarkusBuild` task fails with the following message:
```
> Task :foo:quarkusBuild FAILED
building quarkus jar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':foo:quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.cxf.deployment.QuarkusCxfProcessor#build threw an exception: java.lang.UnsupportedClassVersionError: ch**TaxService has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:445)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:405)
        at io.quarkiverse.cxf.deployment.QuarkusCxfProcessor.createQuarkusJaxWsServiceFactoryBean(QuarkusCxfProcessor.java:379)
        at io.quarkiverse.cxf.deployment.QuarkusCxfProcessor.build(QuarkusCxfProcessor.java:271)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

The Quarkus Gradle plugin/tasks should execute using the Java version specified by the toolchain, rather than the version that Gradle runs with.

### Actual behavior

The Quarkus Gradle plugin/tasks execute using the Java version that Gradle runs with (which is not necessarily the same as that of a Gradle toolchain).

### How to Reproduce?

See bug description.

### Output of `uname -a` or `ver`

see bug description

### Output of `java -version`

see bug description

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.9.1, see bug description

**Comment by glefloch** [comment]
@twwwt I'm not able to reproduce the issue. I tried with both gradle 6.9 and 7.2. Do you have a reproducer?

**Comment by twwwt** [comment]
@glefloch I'm sorry this issue was observed in a large build and right now I don't have the time to set up a minimal project that demonstrates it.

I'm not sure but the issue might in fact be related to the [Quarkus CXF extension](https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/dev/index.html), version 0.9. As can be seen from the stack trace, the exception seems to be caused by `io.quarkiverse.cxf.deployment.QuarkusCxfProcessor`, which is a class belonging to the extension. Do you agree that the issue is likely caused by that class? I would then open an issue at that project.

**Comment by glefloch** [comment]
I will try to reproduce the issue with that extension. Thanks for your answer

**Comment by marcelhanser** [comment]
Have the same issue with gradle: 7.3 and quarkus 2.5.1.Final - ill also try to create a reproducer

**Comment by marcelhanser** [comment]
Please checkout attached Project. Im not 100% sure that its working out of the box - i needed to remove proxy settings and repositories etc.
BUT: It looks like the custom ConfigSource makes the difference. Remove it and it will compile again.
[myproject.zip](https://github.com/quarkusio/quarkus/files/7733535/myproject.zip)
Best & Thx
Marcel

**Comment by krishna-kunderu** [comment]
Any fix available on this. I still see quarkusBuild error as in this ticket if use Java toolchain to use Java17

**Comment by glefloch** [comment]
Not yet, I haven't had time to go deeper on this.

**Comment by marcantoine-beauvais-bruker** [comment]
I have the same kind of issue when using quarkus-smallrye-openapi...

**Comment by MarcAntoine-Beauvais** [comment]
I have the same kind of issue when using quarkus-smallrye-openapi...

**Comment by jskillin-idt** [comment]
@glefloch I just stumbled into this myself. I believe I can make a reproducer if you need another one.

**Comment by lenalebt** [comment]
I also run into those issues, using kapt (kotlin annotation processing). Any known workarounds? `quarkusDev` works, but I cannot `assemble` or `build`.

```
> Task :quarkusBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.steps.RegisterForReflectionBuildStep#build threw an exception: java.lang.UnsupportedClassVersionError: com/maxxeed/externalservices/services/Token has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:506)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
        at io.quarkus.deployment.steps.RegisterForReflectionBuildStep.registerClass(RegisterForReflectionBuildStep.java:127)
        at io.quarkus.deployment.steps.RegisterForReflectionBuildStep.build(RegisterForReflectionBuildStep.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

...just happened after trying to upgrade to java 17, from java11. Both are installed on the system.

**Comment by jskillin-idt** [comment]
It appears based on Gradle's use of their toolchain system, it's hypothetically possible to detect the appropriate JDK:
https://github.com/gradle/gradle/blob/v8.1.1/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L104
and then because Quarkus has recently moved to using Gradle's worker system, it might be possible to extract the appropriate executable:
https://github.com/gradle/gradle/blob/v8.1.1/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaToolchainService.java#L53
and use that to configure the fork:
https://github.com/quarkusio/quarkus/blob/3.1.2.Final/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusTask.java#L64

**Comment by frehov** [comment]
We just hit this in a brand new repository as well.
Targeting Quarkus 3.1 on Java 17 with Gradle 8.1.1 toolchains, so relying on toolchain support for configuring java version.
We are "forced" to downgrade to Java 11 due to the missing support on this new repo for now.

@jskillin-idt I'm assuming you've probably read the docs here https://docs.gradle.org/current/userguide/toolchains.html#sec:plugins as it doesn't look to hard to get the launcher/executable from the toolchain service.

**Comment by jskillin-idt** [comment]
> @jskillin-idt I'm assuming you've probably read the docs here https://docs.gradle.org/current/userguide/toolchains.html#sec:plugins as it doesn't look to hard to get the launcher/executable from the toolchain service.

Yes, but since Quarkus is unique in the Gradle world in that it wants to extend the existing JavaCompile with its own compilation handiwork, I thought it'd be more accurate to track what JDK the JavaCompile task would use, especially since it appears it can have its own configuration:
https://docs.gradle.org/8.1.1/javadoc/org/gradle/api/tasks/compile/JavaCompile.html#getOptions--

**Comment by amarktl** [comment]
We are facing the same issue - we use the toolchain Plugin to set the Java Version to **21**. gradle is started e.g with java **17**. This leads to the situation that all class files will be compiled with java 21 and then the **quarkusBuild** step uses the java version which gradle is started with. 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cli:quarkusBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.deployment.steps.ClassTransformingBuildStep#handleClassTransformation threw an exception: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.UnsupportedClassVersionError: <CLASSNAME> has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by jskillin-idt** [comment]
An immediate fix Quarkus could implement is to simply add a check that the JDK running the Gradle process matches the JDK being used to compile.

A better long-term fix is for Quarkus to detect the JDK that Gradle is using to compile and use that instead.

**Comment by alexm77** [comment]
It's disheartening to see this ignored for two and a half years.
Toolchains is a great feature of gradle. It makes setting up a new project much easier, it eases defining specific Java versions for CI pipelines (where developers usually have limited access/control). But if you use Quarkus, you have to kiss all that good bye.

Fwiw, the error seems to have moved from quarkusBuild to the quarkusAppPartsBuild task, when testing with newer versions (Gradle 8.5 and Quarkus 3.6).

**Comment by alexm77** [comment]
On a more constructive note, you have this in the gradle/build-logic:
```
    // Need to limit the Java version for Kotlin to 17, because 20 doesn't work.
    // Also prefer the current version to prevent JDK downloads.
    languageVersion.set(JavaLanguageVersion.of(javaMajor.coerceAtMost(17)))
```
That hasn't been true like half a year now, it may be what forces my builds to crap out crying they can't handle Java 21.

**Comment by alexm77** [comment]
> An immediate fix Quarkus could implement is to simply add a check that the JDK running the Gradle process matches the JDK being used to compile.
> 
> A better long-term fix is for Quarkus to detect the JDK that Gradle is using to compile and use that instead.

Not sure what the "immediate fix" would address. This plugin is tapping into the gradle setup, it should respect whatever the gradle setup has decided to use for compilation. That is the _only_ fix, imho.

**Comment by jskillin-idt** [comment]
> Not sure what the "immediate fix" would address. This plugin is tapping into the gradle setup, it should respect whatever the gradle setup has decided to use for compilation. That is the _only_ fix, imho.

It would add a safety check to prevent users of Quarkus from accidentally mixing .class files built by different compilers. It would give a more immediate and clearer error message. All of this would give some time for the long-term fix to get implemented, which is likely not trivial.

**Comment by alexm77** [comment]
> An immediate fix Quarkus could implement is to simply add a check that the JDK running the Gradle process matches the JDK being used to compile.
> 
> A better long-term fix is for Quarkus to detect the JDK that Gradle is using to compile and use that instead.

Not sure what the "immediate fix" would address. This plugin is tapping into the gradle setup, it should respect whatever the gradle setup has decided to use for compilation. That is the _only_ fix, imho.

> > Not sure what the "immediate fix" would address. This plugin is tapping into the gradle setup, it should respect whatever the gradle setup has decided to use for compilation. That is the _only_ fix, imho.
> 
> The short term fix would add a safety check to prevent users of Quarkus from accidentally mixing .class files built by different compilers. It would give a more immediate and clearer error message. All of this would give some time for the long-term fix to get implemented, which is likely not trivial.

Well, the current message that the class version is not supported pretty much says the same thing. So big improvement there.

Querying the gradle infra for the configured compiler shouldn't be too hard (see: [JavaCompiler](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.JavaCompile.html#org.gradle.api.tasks.compile.JavaCompile:javaCompiler), not sure if that's aware of whatever the toolchain sets). I'm trying to look into it, but there's no javadoc to point me in the right direction, so I have to comb through the code. Sadly, I don't have a lot of time to spare :(

**Comment by joschi** [comment]
For the time being, this seems to work as intended (although a bit verbose):
```kotlin
quarkus {
	val executablePath = javaToolchains
		.launcherFor(java.toolchain)
		.map { launcher -> launcher.executablePath.asFile.absolutePath }

	buildForkOptions {
		executablePath.map { path -> executable = path }.get()
	}
	codeGenForkOptions {
		executablePath.map { path -> executable = path }.get()
	}
}
```

Tested with Java toolchain set to Amazon Corretto 23.x for the application and Azul Zulu 21.x used for Gradle.

**Comment by alexm77** [comment]
Any plans to get the above contribution into a release?
