### ISSUE TITLE
@ConfigMapping doesn't work in Kotlin projects

### ISSUE THREAD

**Issue by Shpota** [quarkusio/quarkus#20483]
While migrating from using `@ConfigProperties` to `@ConfigMapping` I found out that `ConfigMapping`s are not working in Kotlin. I tried to reproduce the issue on a fresh Quarkus 2.2.3 project and it seems like [the simples configuration](https://quarkus.io/guides/config-mappings#config-mappings) from the get started guide would not work in Kotlin.

### Actual behavior

```
2021-09-30 18:40:56,927 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.config.ConfigValidationException: Configuration validation failed:
        java.util.NoSuchElementException: SRCFG00014: The config property server.host is required but it could not be found in any config source
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:838)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:794)
        at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:54)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:36)
        at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:81)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy_0(ConfigBuildStep$registerConfigClasses-2116437784.zig:132)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy(ConfigBuildStep$registerConfigClasses-2116437784.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:612)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:98)
```

### How to Reproduce?

1. Generate a Quarkus project [with Kotlin and Gradle](https://code.quarkus.io/?g=com.bugreport&a=quarkus-props&b=GRADLE&e=kotlin).
2. Replace `application.properties` with `application.yml` with the following content:
```
server:
  host: "localhost"
```
3. Create a `ServerConfig` interface with the following class:
```
@ConfigMapping(prefix = "server")
interface ServerConfig {
    fun host(): String
}
```
4. Run: `./gradlew quarkusDev` and observer the error.

### Quarkus version

2.2.3.Final

### Additional information

The similar config would work fine with, by now deprecated,`@ConfigProperties`.

**Comment by glefloch** [comment]
Can you try to add the following dependency in your project: `implementation 'io.quarkus:quarkus-config-yaml'` ? By default, only `application.properties` file is loaded.

**Comment by geoand** [comment]
@glefloch is correct - without explicit YAML support via the extension you will run into this problem
