### ISSUE TITLE
@ConfigMapping fails to start when there is a REST cleint mapped to the same configuration root

### ISSUE THREAD

**Issue by Shpota** [quarkusio/quarkus#20497]
When there is a REST client mapped to the configuration root that has `@ConfigMapping` configured, the application would fail to start.

### Actual behavior

```
2021-10-01 13:13:59,408 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.config.ConfigValidationException: Configuration validation failed:
        greeting-integration.api-url/mp-rest/url does not map to any root
        greeting-integration.api-url/mp-rest/scope does not map to any root
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:838)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:794)
        at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:54)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:36)
        at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:81)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy_0(ConfigBuildStep$registerConfigClasses-2116437784.zig:132)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy(ConfigBuildStep$registerConfigClasses-2116437784.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:645)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:98)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

### How to Reproduce?

1. Generate a Quarkus project with Kotlin, Gradle, Resteasy, Resteasy client, and yaml.
2. Add the following into `application.yml`:
```
greeting-integration:
  enabled: false
  api-url/mp-rest/scope: javax.enterprise.context.ApplicationScoped
  api-url/mp-rest/url: https://greeting-api
```
3. Create a `GreetingConfig` interface with the following contant:
```
@ConfigMapping(prefix = "greeting-integration")
interface GreetingConfig {
    fun enabled(): Boolean
}
```
4. Create a REST client:
```
@Path("/")
@RegisterRestClient(configKey = "greeting-integration.api-url")
interface GreetingClient {
    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    fun greet(message: String): String
}
```
4. Run: `./gradlew quarkusDev` and observer the error.

### Quarkus version or git rev

2.2.3.Final

**Comment by radcortez** [comment]
There is no issue here. By default, the `@ConfigMapping` validates that all configurations keys under the defined prefix have a mapping in the class. In this case, there is no mapping for the `api-url` keys.

If you wish to disable this behavior, you can use `smallrye.config.mapping.validate-unknown=false`.

**Comment by Shpota** [comment]
Thank you, it helped. I think it would make sence to have `validate-unknown=false` as a default. We are migrating from `@ConfigProperties` to `@ConfigMapping`. This would meke migration easier considering it was a default with `@ConfigMapping`. Or maybe exclude `mp-rest` properties from validations as they are used for a different purpose and it can be verified by presence of the corresponding `@RegisterRestClient`.

**Comment by radcortez** [comment]
Sorry for the inconvenience :(

We added that as a convenience so you can be sure that all your configurations are mapped. Indeed you could set them off as a default, but we know that its harder to turn things on than off :)

We may be able to provide exceptions for the mp-rest properties.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by radcortez** [comment]
I don't think so.

**Comment by geoand** [comment]
Okay thanks. Let's close then.
Please reopen if it's still an issue
