### ISSUE TITLE
OptaPlanner AWT DataFlavor build time init error

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#20491]
Optaplanner native integration tests are failing to build native binary due to https://github.com/quarkusio/quarkus/pull/20239

One of the issues is:

```
 javax.activation.ActivationDataFlavor the class was requested to be initialized at run time (). org.drools.compiler.kproject.models.KieModuleMarshaller caused initialization of this class with the following trace:
	at javax.activation.ActivationDataFlavor.<clinit>(ActivationDataFlavor.java)
	at java.lang.Class.forName0(Unknown Source)
	at java.lang.Class.forName(Class.java:398)
	at com.thoughtworks.xstream.core.JVM.loadClassForName(JVM.java:328)
	at com.thoughtworks.xstream.core.JVM.loadClassForName(JVM.java:307)
	at com.thoughtworks.xstream.XStream.setupAliases(XStream.java:801)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:540)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:470)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:444)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:397)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:371)
	at org.kie.soup.xstream.XStreamUtils.createNonTrustingXStream(XStreamUtils.java:198)
	at org.drools.compiler.kproject.models.KieModuleMarshaller.<init>(KieModuleMarshaller.java:47)
	at org.drools.compiler.kproject.models.KieModuleMarshaller.<clinit>(KieModuleMarshaller.java:45)

java.awt.datatransfer.DataFlavor the class was requested to be initialized at run time (Quarkus run time init for AWT). org.drools.compiler.kproject.models.KieModuleMarshaller caused initialization of this class with the following trace:
	at java.awt.datatransfer.DataFlavor.<clinit>(DataFlavor.java:115)
	at java.lang.Class.forName0(Unknown Source)
	at java.lang.Class.forName(Class.java:398)
	at com.thoughtworks.xstream.core.JVM.loadClassForName(JVM.java:328)
	at com.thoughtworks.xstream.core.JVM.loadClassForName(JVM.java:307)
	at com.thoughtworks.xstream.XStream.setupAliases(XStream.java:801)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:540)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:470)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:444)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:397)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:371)
	at org.kie.soup.xstream.XStreamUtils.createNonTrustingXStream(XStreamUtils.java:198)
	at org.drools.compiler.kproject.models.KieModuleMarshaller.<init>(KieModuleMarshaller.java:47)
	at org.drools.compiler.kproject.models.KieModuleMarshaller.<clinit>(KieModuleMarshaller.java:45)
```

The AWT extension pushes any `java.awt` classes to be run time initialized. In this case, some static initalization in `org.drools.compiler.kproject.models.KieModuleMarshaller`, which currently happens at build time, leads, through xstream dependency to trying to initialize `java.awt.datatransfer.DataFlavor` at build time, to clashes with the AWT extension.

~Since the new AWT extension was introduced the Optaplanner quickstart has been failing (see https://github.com/quarkusio/quarkus/issues/11563#issuecomment-926462878).
https://github.com/graalvm/mandrel/issues/292 might also be related~

**Comment by galderz** [comment]
FYI https://github.com/graalvm/mandrel/issues/292 will be fixed in upcoming Mandrel 21.2.0.2 version. See https://github.com/graalvm/mandrel/issues/292#issuecomment-932185409 for details.

I'll look into the Optaplanner issue next.

**Comment by galderz** [comment]
PR sent: https://github.com/kiegroup/optaplanner/pull/1594

**Comment by ge0ffrey** [comment]
cc @mariofusco Can we fix this upstream in Drools 8 such that this workaround can be removed? https://github.com/kiegroup/optaplanner/pull/1594

**Comment by ge0ffrey** [comment]
Thank you Galder! The fix is merged (@triceo is following up) I suspect this issue can be closed?

**Comment by galderz** [comment]
No worries Geoffrey :). Closing.
