### ISSUE TITLE
NPE when requesting OpenApi spec file from Swagger

### ISSUE THREAD

**Issue by sarxos** [quarkusio/quarkus#20527]
### Describe the bug

I happened to hit NPE when accessing Swagger. I'm unable to reproduce it, however I did found a log from my production env where NPE stack trace can be found.

```plain
ERROR [io.qu.ve.ht.ru.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /api/spec failed, error id: c270c580-14fc-48df-9933-fb794aa894c0-1: java.lang.NullPointerException
       at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService.getJsonDocument(OpenApiDocumentService.java:45)
       at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentHolder.getDocument(OpenApiDocumentHolder.java:16)
       at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.getDocument(OpenApiDocumentService_ClientProxy.zig:157)
       at io.quarkus.smallrye.openapi.runtime.OpenApiHandler.handle(OpenApiHandler.java:76)
       at io.quarkus.smallrye.openapi.runtime.OpenApiHandler.handle(OpenApiHandler.java:21)
       at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
       at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
       at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
       at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
       at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
       at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
       at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
       at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
       at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
       at java.base/java.lang.Thread.run(Thread.java:829)
```

The stack trace points to this line:

https://github.com/quarkusio/quarkus/blob/fe6b68e2b46534aae971405d19969615ad78bdf2/extensions/smallrye-openapi/runtime/src/main/java/io/quarkus/smallrye/openapi/runtime/OpenApiDocumentService.java#L45

It seems like the `documentHolder` is not initialized, which tells me that https://github.com/quarkusio/quarkus/blob/fe6b68e2b46534aae971405d19969615ad78bdf2/extensions/smallrye-openapi/runtime/src/main/java/io/quarkus/smallrye/openapi/runtime/OpenApiDocumentService.java#L32 was either not invoked at all, or was invoked from a different thread resulting in a race condition.

Every subsequent request gives the expected (correct) result.

I tried different approaches to reproduce this bug, but with no luck. It happened only once.

### Expected behavior

The OpenApi spec is successfully returned.

### Actual behavior

The OpenApi spec request fails with NPE.

### How to Reproduce?

N/A. Described problem happened only once, randomly.

### Output of `uname -a` or `ver`

```
$ uname -a
Linux ip-*-*-*-* 5.4.0-1057-aws #60~18.04.1-Ubuntu SMP Thu Sep 9 20:38:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Output of `java -version`

```
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```

### Quarkus version or git rev

2.3.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
$ mvn --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /home/sarxos/bin/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-37-generic", arch: "amd64", family: "unix"
```

**Comment by geoand** [comment]
There is indeed a race condition here, I'll take care of it for `2.3.0.Final`.

**Comment by sarxos** [comment]
Thank you @geoand :) I looked at the fix you did in the code and it looks great!
