### ISSUE TITLE
Problem wiring up a SSE endpoint with an internal channel with the reactive messaging HTTP connector

### ISSUE THREAD

**Issue by MintakaB** [quarkusio/quarkus#20543]
### Describe the bug

I am using Quarkus 2.2.3 and OpenJDK 11.

The SSE endpoint and incoming channel looks like:
```
@Path("/hello")
public class ExampleResource {
    @Inject
    @Channel("sse-output")
    Multi<String> data;


    @GET
    @Produces(MediaType.SERVER_SENT_EVENTS)
    @RestSseElementType(MediaType.TEXT_PLAIN)
    public Multi<String> streamData() {
        return this.data;
    }
}

```

The producer is described below:

```
@ApplicationScoped
public class Producer {
    @Incoming("event")
    @Outgoing("sse-output")
    public String broadcast(final String time) {
        System.out.println("received event");

        return time.toUpperCase();
    }
}

```

The incoming "event" channel is defined in the application.resource file as:

mp.messaging.incoming.event.connector=quarkus-http
mp.messaging.incoming.event.path=/event
mp.messaging.incoming.event.method=POST
Dependencies in pom.xml
```
<dependencies>
<dependency>
<groupId>io.quarkus</groupId>
<artifactId>quarkus-arc</artifactId>
</dependency>
<dependency>
<groupId>io.quarkus</groupId>
<artifactId>quarkus-resteasy-reactive</artifactId>
</dependency>
<dependency>
<groupId>io.quarkus</groupId>
<artifactId>quarkus-junit5</artifactId>
<scope>test</scope>
</dependency>
<dependency>
<groupId>io.rest-assured</groupId>
<artifactId>rest-assured</artifactId>
<scope>test</scope>
</dependency>
<dependency>
<groupId>io.quarkus</groupId>
<artifactId>quarkus-reactive-messaging-http</artifactId>
</dependency>
</dependencies>
```

When I try to send a message using a HTTP POST, it throughs the following error:
```
2021-10-05 12:00:37,885 ERROR [io.qua.rea.htt.run.ReactiveHttpHandlerBean] (vert.x-eventloop-thread-2) Emitting message failed: java.lang.NullPointerException
at io.quarkus.reactivemessaging.http.runtime.ReactiveHttpHandlerBean.handleRequest(ReactiveHttpHandlerBean.java:61)
at io.quarkus.reactivemessaging.http.runtime.ReactiveHttpHandlerBean_Subclass.handleRequest$$superforward1(ReactiveHttpHandlerBean_Subclass.zig:549)
at io.quarkus.reactivemessaging.http.runtime.ReactiveHttpHandlerBean_Subclass$$function$$9.apply(ReactiveHttpHandlerBean_Subclass$$function$$9.zig:47)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
at io.quarkus.reactivemessaging.http.runtime.ReactiveHttpHandlerBean_Subclass.handleRequest(ReactiveHttpHandlerBean_Subclass.zig:1413)
at io.quarkus.reactivemessaging.http.runtime.ReactiveHandlerBeanBase.handle(ReactiveHandlerBeanBase.java:29)
at io.quarkus.reactivemessaging.http.runtime.ReactiveHttpHandlerBean_Subclass.handle$$superforward1(ReactiveHttpHandlerBean_Subclass.zig:530)
at io.quarkus.reactivemessaging.http.runtime.ReactiveHttpHandlerBean_Subclass$$function$$8.apply(ReactiveHttpHandlerBean_Subclass$$function$$8.zig:33)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
at io.quarkus.reactivemessaging.http.runtime.ReactiveHttpHandlerBean_Subclass.handle(ReactiveHttpHandlerBean_Subclass.zig:1310)
at io.quarkus.reactivemessaging.http.runtime.ReactiveHttpHandler.handle(ReactiveHttpHandler.java:16)
at io.quarkus.reactivemessaging.http.runtime.ReactiveHttpHandler.handle(ReactiveHttpHandler.java:6)
at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127)
at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151)
at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313)
at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:290)
at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:86)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:557)
at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:125)
at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:227)
at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:280)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)
```

The HTTP POST channel "event" works alone perfectly, however when I try to pass the event to the "see-out" channel I got the error above.

thank you if you can have a look at it.

**Comment by michalszynkiewicz** [comment]
The problem is that until someone subscribes to the channel, that is, there is some client connected to the SSE endpoint, the consumer is not set for the messages.

**Comment by michalszynkiewicz** [comment]
@MintakaB you can make it work e.g. with:
```java
    BroadcastProcessor<String> data = BroadcastProcessor.create();

    @GET
    @Produces(MediaType.SERVER_SENT_EVENTS)
    @RestSseElementType(MediaType.TEXT_PLAIN)
    public Multi<String> streamData() {
        return this.data;
    }

    @Incoming("sse-output")
    public CompletionStage<Void> broadcast(final String time) {
        data.onNext(time);
        return CompletableFuture.completedStage(null);
    }
```
