### ISSUE TITLE
Qute: error reporting needs to be more concise

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#20583]
### Describe the bug

I'm getting Qute type-safe template errors displayed like this:

```
	Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {user}
	- Only type-safe expressions are allowed in the checked template defined via: fr.epardaud.rest.PersonOrGroups$Templates.view(); an expression must be based on a checked template parameter [autoAccept, artist], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
	- at PersonOrGroups/view.html:11
		at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:170)
		... 11 more
	Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {user}
	- Only type-safe expressions are allowed in the checked template defined via: fr.epardaud.rest.PersonOrGroups$Templates.view(); an expression must be based on a checked template parameter [autoAccept, artist], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
	- at PersonOrGroups/view.html:12
		at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:170)
		... 11 more
	Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {models.ContentStatus.REJECTED}
	- Only type-safe expressions are allowed in the checked template defined via: fr.epardaud.rest.PersonOrGroups$Templates.view(); an expression must be based on a checked template parameter [autoAccept, artist], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
	- at PersonOrGroups/view.html:13
		at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:170)
		... 11 more
	Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {models.ContentStatus.REJECTED}
	- Only type-safe expressions are allowed in the checked template defined via: fr.epardaud.rest.PersonOrGroups$Templates.view(); an expression must be based on a checked template parameter [autoAccept, artist], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
	- at PersonOrGroups/view.html:17
		at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:170)
		... 11 more
	Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {models.ContentStatus.NEW}
	- Only type-safe expressions are allowed in the checked template defined via: fr.epardaud.rest.PersonOrGroups$Templates.view(); an expression must be based on a checked template parameter [autoAccept, artist], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
	- at PersonOrGroups/view.html:18
		at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:170)
		... 11 more
```

Given that I have hundreds of these, it would be more convenient to have a more concise way to list errors, such as:

```
	PersonOrGroups/view.html:11: Incorrect expression found: {user}
	- Only type-safe expressions are allowed in the checked template defined via: fr.epardaud.rest.PersonOrGroups$Templates.view(); an expression must be based on a checked template parameter [autoAccept, artist], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
	PersonOrGroups/view.html:12: Incorrect expression found: {user}
	- Only type-safe expressions are allowed in the checked template defined via: fr.epardaud.rest.PersonOrGroups$Templates.view(); an expression must be based on a checked template parameter [autoAccept, artist], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
etc…
```

**Comment by stefanorg** [comment]
Hi all, after updating to quarkus 2.4.0.CR1, i see a lot of those message too.

Something like

```
[5] Incorrect expression found: {inject:loginUtils.basePath}
        - @Named bean not found for [loginUtils]
        - at SpidController/form.html:47
....
....

 Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {inject:loginUtils.basePath}
        - @Named bean not found for [loginUtils]
        - at SpidController/form.html:47
                at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:169)
                ... 11 more
```

But i've the named bean the only thing to notice is that the named bean, use `lombok`

```
@Data
@Named("loginUtils")
public class LoginUtils {

    public static final String ERRORE_IMPREVISTO_RIPROVARE_PIU_TARDI = "Si è verificato un errore imprevisto. Ti preghiamo di riprovare più tardi.";

    static final String LOGIN_PATH = "/sso/login";
    static final String SSO_PASS_RESET_PATH = "/sso/passwordreset";
    static final String FIRST_ACCESS_PATH = "/sso/firstaccess";
    static final String SELECT_ACCOUNT_PATH = "/sso/select";
    static final String OTP_PATH = "/sso/otp";
    static final String SPID_PATH = "/spid/sso";
    static final String DIDUP_FAMIGLIA_CLIENT_ID = "72fd6dea-d0ab-4bb9-8eaa-3ac24c84886c";

    String loginPath;
    String loginUrl;
    String passwordResetUrl;
    String firstAccessUrl;
    String selectAccountUrl;
    String otpUrl;
    String otpPath;
    String spidPath;

    @ConfigProperty(name = "quarkus.http.root-path")
    String basePath;
    ....
```

**Comment by mkouba** [comment]
Resolved by https://github.com/quarkusio/quarkus/pull/25810.
