### ISSUE TITLE
Cannot read body as String from RestResponse

### ISSUE THREAD

**Issue by andreas-repp** [quarkusio/quarkus#20629]
### Describe the bug

I'm trying to use the RestResponse<T> with the rest client with Quarkus 2.3.0.

If you do `Response.readEntity(String.class)`, you can read the whole body as a `String`. This is interesting in the case of an error, where the API just prints some message and I want to log that. However, when I use `RestResponse<SomeDto>.readEntity(String.class)`, I get a `ProcessingException` telling me that the body cannot be parsed to the type `String`. 

The stacktrace looks like this:

```
equest failed: javax.ws.rs.ProcessingException: Request could not be mapped to type class java.lang.String
	at org.jboss.resteasy.reactive.common.jaxrs.RestResponseImpl.readEntity(RestResponseImpl.java:140)
	at org.jboss.resteasy.reactive.common.jaxrs.RestResponseImpl.readEntity(RestResponseImpl.java:145)
	at org.acme.Resource.testQueryWithError(Resource.kt:25)
	at org.acme.Resource_Subclass.testQueryWithError$$superforward1(Resource_Subclass.zig:129)
	at org.acme.Resource_Subclass$$function$$4.apply(Resource_Subclass$$function$$4.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.Resource_Subclass.testQueryWithError(Resource_Subclass.zig:269)
	at org.acme.Resource$quarkusrestinvoker$testQueryWithError_33fbb61aa71b731d6e473902fc222e75c9b2d63f.invoke(Resource$quarkusrestinvoker$testQueryWithError_33fbb61aa71b731d6e473902fc222e75c9b2d63f.zig:33)
```

### Expected behavior

It should be possible to read the response body of a `RestResponse` as a String like it is with the normal `Response` object.

### Actual behavior

It crashes.

### How to Reproduce?

1. Download the reproducer and unzip it. Run it with `./gradlew quarkusDev`: [2021-10-08-reactive-restclient-restresponse-string-entity.zip](https://github.com/quarkusio/quarkus/files/7312016/2021-10-08-reactive-restclient-restresponse-string-entity.zip)
2. Open your browser and go to http://localhost:8080/test-not-found
3. You should get the exception in the log and in the browser.

### Quarkus version or git rev

Quarkus 2.3.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.8.3

**Comment by gsmet** [comment]
@geoand AFAICS, it's related to common RESTEasy Reactive code, would you mind having a look? The OP provided a reproducer.

**Comment by geoand** [comment]
Unfortunately there is no good solution for this... 

@FroMage I am wondering whether we should remove `RestResponse#readEntity(Class)` completely...

**Comment by FroMage** [comment]
I don't know, it looks like the code is exactly the same in both classes, what's the reason why they behave differently?

**Comment by geoand** [comment]
Is this still a problem in the latest Quarkus versions?

**Comment by geoand** [comment]
Closing for lack of feedback
