### ISSUE TITLE
Qute: add `?.` operator

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#20704]
### Description

Groovy and other languages have a null-safe object dereference operator `?.` which allows users to safely access potentially-null expression members. For example `a?.b` is equivalent to `let lhs = a; return lhs != null ? lhs.b : null` so the member is only accessed if the left-hand-side expression is not `null`. If it's `null` then the expression evaluates to `null`. Note that normally the left-hand-side expression is only evaluated once.

Could we add the same operator to Qute?

**Comment by mkouba** [comment]
I'm going to close this one. Feel free to reopen if default values and safe expressions do not solve the problem.

**Comment by FroMage** [comment]
I'm having trouble understanding exactly what `??` applies to.

You example troubles me, because IMO if `{a.b??}` expands to `{a.b.or(null)}` then if `a` is `null` we still should have an NPE.

The definition of `.` and `?.` are clearly defined in my opinion, but apparently `??` applies to every member access of the left-hand-side expression? I'm sure it's useful, but I don't understand its semantics.

Meanwhile, it doesn't appear I can use it everywhere I'd use `?.`, for example in the following expression I get an error when trying to use it:

```
            <input name="releaseDate" class="form-control" value="{inject:flash.get('releaseDate') ?: album.releaseDate.internetDateFormat()??}" type="date"/>
```

The error is cryptic too:

```
#1 Incorrect expression found: {null}
- Only type-safe expressions are allowed in the checked template defined via: fr.epardaud.rest.Albums$Templates.addForm(); an expression must be based on a checked template parameter [artist, edit, album], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
- at Albums/addForm.html:27
...
20                <input name="title" class="form-control" value="{inject:flash.get('title') ?: album.title}" maxlength="{global:VARCHAR_SIZE}"/>
21                <span class="help-block">​{#error 'title'/}</span>
22            </div>
23        </div>
24        <div class="form-group {#errorClassBootstrap 'relaseDate'/}">
25            <label class="control-label col-lg-2" for="releaseDate">Release date</label>
26            <div class="col-lg-10">
27                <input name="releaseDate" class="form-control" value="{inject:flash.get('releaseDate') ?: album.releaseDate.internetDateFormat()??}" type="date"/>
     ===================================================================^
28                <span class="help-block">​{#error 'releaseDate'/}</span>
29            </div>
30        </div>
31        {#addPhoto container=album url=uri:Albums.viewThumbnailPhoto(album.id)/}
32        <div class="form-group">
33            <div class="col-lg-offset-2 col-lg-10">
34                {#if edit}
...
```

Now, the original expression was `{inject:flash.get('releaseDate') ?: album.releaseDate?.internetDateFormat()}` which made sense to me, but is not supported. And if I try `{inject:flash.get('releaseDate') ?: album.releaseDate.internetDateFormat()` I'm getting an NPE:

```
Internal Server Error
Error id 211f46ed-22f3-4013-9c2d-966e02f5bfbf-250, io.quarkus.qute.TemplateException: Property "internetDateFormat" not found on the base object "null" in expression {album.releaseDate.internetDateFormat()} in template Albums/addForm.html on line 27
The stacktrace below has been reversed to show the root cause first. Click Here to see the original stacktrace

io.quarkus.qute.TemplateException: Property "internetDateFormat" not found on the base object "null" in expression {album.releaseDate.internetDateFormat()} in template Albums/addForm.html on line 27
	at io.quarkus.qute.EvaluatorImpl.propertyNotFound(EvaluatorImpl.java:207)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:168)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:112)
```
