### ISSUE TITLE
CustomDirective for smallrye-graphql  does not work

### ISSUE THREAD

**Issue by johgoe** [quarkusio/quarkus#20802]
### Describe the bug

It seems that types of custom directive annotations are not added to the deployment, which causes an error on startup, if the directive is used in a entity.

```
import io.smallrye.graphql.api.Directive;
import io.smallrye.graphql.api.DirectiveLocation;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import org.eclipse.microprofile.graphql.NonNull;

@Directive(
    on = {DirectiveLocation.OBJECT, DirectiveLocation.INTERFACE}
)
@Retention(RetentionPolicy.RUNTIME)
public @interface CustomDirective{
    @NonNull
    String[] fields();
}
```
I'm not familar with quarkus extensions but it seems that in SmallRyeGraphQLProcessor getSchemaJavaClasses() all Types which are used in Schema are added except the Types of the Directive. I guess a single line like 

```
classes.addAll(getTypeClassNames(schema.getDirectiveTypes()));
```

will fix my problem.

### Expected behavior

Quarkus is starting even if I use custom directives within my GraphQL API

### Actual behavior

~~~
2021-10-15 19:14:36,357 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2021-10-15 19:14:36,358 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:98)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:470)
	... 15 more
Caused by: java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractCollection.add(AbstractCollection.java:267)
	at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService-167583418.deploy_2(SmallRyeGraphQLProcessor$buildExecutionService-167583418.zig:5725)
	at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService-167583418.deploy(SmallRyeGraphQLProcessor$buildExecutionService-167583418.zig:50)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:439)
	... 15 more

~~~

### Quarkus version or git rev

2.2.3

**Comment by johgoe** [comment]
I attached a sample project to reproduce the issue

[quarkus-sample-20802-main.zip](https://github.com/quarkusio/quarkus/files/7388625/quarkus-sample-20802-main.zip)



(or you look into my sample repo https://github.com/johgoe/quarkus-sample-20802/blob/main/src/main/java/org/acme/ )

**Comment by gsmet** [comment]
@phillip-kruger was it implemented somehow or it's still pending?

**Comment by phillip-kruger** [comment]
Not yet. On my todo list...

**Comment by uetal** [comment]
hi @phillip-kruger it's still pending?

**Comment by phillip-kruger** [comment]
still pending. PRs welcomed
