### ISSUE TITLE
NPE in ClassLoaderCompiler with multi-module project

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2084]
Well, sort of: I'm building one of the quickstarts with master, without the patch fixing the parent pom detection applied. So all the quickstarts are in the workspace and some of them have a null `getClassesPath()` here: https://github.com/quarkusio/quarkus/blob/master/core/devmode/src/main/java/io/quarkus/dev/ClassLoaderCompiler.java#L124 .

While this specific issue will be fixed by Alexey's patch, it can still happen in the case of a multi-module project where not all the modules have been built.

Either an exception or a warning (if we think it could work anyway) is in order, but definitely not a NPE.

Stacktrace:
```
2019-04-15 17:38:49,484 SEVERE [io.qua.dev.RuntimeCompilationSetup] (main) Failed to create compiler, runtime compilation will be unavailable: java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at io.quarkus.dev.ClassLoaderCompiler.<init>(ClassLoaderCompiler.java:124)
	at io.quarkus.dev.RuntimeCompilationSetup.setup(RuntimeCompilationSetup.java:38)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:78)
```

**Comment by rsvoboda** [comment]
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/NPE.20with.20dev.20mode/near/163390566

I saw that at 17:35 :-D
