### ISSUE TITLE
NoSuchElementException with Apicurio SerDes in native mode

### ISSUE THREAD

**Issue by rmarting** [quarkusio/quarkus#20890]
### Describe the bug

I upgraded my application to the latest versions of Quarkus and I found an issue when mi application is compiled in native form. The same version compiled in jvm mode is working successfully.

The full stacktrace is:

```text
2021-10-20 05:21:57,788 ERROR [io.sma.rea.mes.provider] (main) SRMSG00230: Unable to create the publisher or subscriber during initialization: org.apache.kafka.common.KafkaException: java.lang.IllegalStateException: java.util.NoSuchElementException
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.configureSerializer(ReactiveKafkaProducer.java:81)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.<init>(ReactiveKafkaProducer.java:63)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.<init>(ReactiveKafkaProducer.java:43)
	at io.smallrye.reactive.messaging.kafka.impl.KafkaSink.<init>(KafkaSink.java:77)
	at io.smallrye.reactive.messaging.kafka.KafkaConnector.getSubscriberBuilder(KafkaConnector.java:245)
	at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getSubscriberBuilder(KafkaConnector_ClientProxy.zig:397)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createSubscriberBuilder(ConfiguredChannelFactory.java:207)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:164)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:125)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory_ClientProxy.initialize(ConfiguredChannelFactory_ClientProxy.zig:189)
	at java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at io.smallrye.reactive.messaging.extension.MediatorManager.start(MediatorManager.java:189)
	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.start(MediatorManager_ClientProxy.zig:220)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:41)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:111)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:322)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:304)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:667)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.lang.IllegalStateException: java.util.NoSuchElementException
	at io.apicurio.registry.serde.AbstractSchemaResolver.configure(AbstractSchemaResolver.java:89)
	at io.apicurio.registry.serde.DefaultSchemaResolver.configure(DefaultSchemaResolver.java:59)
	at io.apicurio.registry.serde.SchemaResolverConfigurer.configure(SchemaResolverConfigurer.java:75)
	at io.apicurio.registry.serde.AbstractKafkaSerDe.configure(AbstractKafkaSerDe.java:68)
	at io.apicurio.registry.serde.avro.AvroKafkaSerializer.configure(AvroKafkaSerializer.java:81)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.configureSerializer(ReactiveKafkaProducer.java:79)
	... 30 more
Caused by: java.util.NoSuchElementException
	at java.util.ServiceLoader$2.next(ServiceLoader.java:1309)
	at java.util.ServiceLoader$2.next(ServiceLoader.java:1297)
	at java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at io.apicurio.registry.rest.client.RegistryClientFactory.resolveProviderInstance(RegistryClientFactory.java:105)
	at io.apicurio.registry.rest.client.RegistryClientFactory.create(RegistryClientFactory.java:77)
	at io.apicurio.registry.rest.client.RegistryClientFactory.create(RegistryClientFactory.java:71)
	at io.apicurio.registry.serde.AbstractSchemaResolver.configure(AbstractSchemaResolver.java:85)
	... 35 more
```

### Actual behavior

Fails in startup.

### How to Reproduce?

Upgrade my application from:

* Quarkus:2.1.3.Final
* apicurio-registry-serdes-avro-serde:2.0.2.Final

to:

* Quarkus:2.3.0.Final
* apicurio-registry-serdes-avro-serde:2.1.1.Final

The same application using the previous version of Apicurio Serdes extension (2.0.2.Final) works successfully. It seems that the new branch 2.1.X is not ready to be used in native mode.

### Output of `uname -a` or `ver`

Linux redhat 5.14.11-200.fc34.x86_64 #1 SMP Sun Oct 10 14:39:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05) OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)

### Quarkus version or git rev

2.3.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by rmarting** [comment]
I can confirm that this issue is already present with the latest versions of:

* Quarkus 2.4.2.Final
* Apicurio 2.1.2.Final (apicurio-registry-serdes-avro-serde, quarkus-apicurio-registry-avro)

The latest stacktrace with these versions is:

```text
2021-11-18 09:17:51,963 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.util.NoSuchElementException
	at java.util.ServiceLoader$2.next(ServiceLoader.java:1309)
	at java.util.ServiceLoader$2.next(ServiceLoader.java:1297)
	at java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at io.apicurio.registry.rest.client.RegistryClientFactory.resolveProviderInstance(RegistryClientFactory.java:105)
	at io.apicurio.registry.rest.client.RegistryClientFactory.create(RegistryClientFactory.java:77)
	at io.apicurio.registry.rest.client.RegistryClientFactory.create(RegistryClientFactory.java:71)
	at io.apicurio.registry.serde.AbstractSchemaResolver.configure(AbstractSchemaResolver.java:86)
	at io.apicurio.registry.serde.DefaultSchemaResolver.configure(DefaultSchemaResolver.java:59)
	at io.apicurio.registry.serde.SchemaResolverConfigurer.configure(SchemaResolverConfigurer.java:75)
	at io.apicurio.registry.serde.AbstractKafkaSerDe.configure(AbstractKafkaSerDe.java:68)
	at io.apicurio.registry.serde.avro.AvroKafkaSerializer.configure(AvroKafkaSerializer.java:81)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.configureSerializer(ReactiveKafkaProducer.java:87)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.<init>(ReactiveKafkaProducer.java:71)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.<init>(ReactiveKafkaProducer.java:46)
	at io.smallrye.reactive.messaging.kafka.impl.KafkaSink.<init>(KafkaSink.java:77)
	at io.smallrye.reactive.messaging.kafka.KafkaConnector.getSubscriberBuilder(KafkaConnector.java:226)
	at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getSubscriberBuilder(KafkaConnector_ClientProxy.zig:426)
	at io.smallrye.reactive.messaging.impl.ConnectorFactories.lambda$wrap$5(ConnectorFactories.java:84)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createSubscriber(ConfiguredChannelFactory.java:192)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:147)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:108)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory_ClientProxy.initialize(ConfiguredChannelFactory_ClientProxy.zig:189)
	at java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at io.smallrye.reactive.messaging.extension.MediatorManager.start(MediatorManager.java:189)
	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.start(MediatorManager_ClientProxy.zig:220)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:41)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:111)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:322)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:304)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:80)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:666)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

So, definitely it is blocking to use it for native mode. Ideas?

@EricWittmann Do you think that this issue should be tracked also in Apicurio project?

**Comment by rmarting** [comment]
I created a sample application where you could check and verify this issue: https://github.com/rmarting/kafka-clients-quarkus-sample/tree/feat-quarkus-2.4

If you compile in native mode, you will get the issue. Tested and verified in CRC.

**Comment by rmarting** [comment]
Tested using the latest versions of Quarkus 2.5.1.Final and Apicurio Serdes 2.1.4.Final successfully. It seems this issue could be closed. :bug: Fixed!
