### ISSUE TITLE
SRMSG18207 backpressure  Cannot emit item due to lack of requests

### ISSUE THREAD

**Issue by msillence** [quarkusio/quarkus#20951]
### Describe the bug

SRMSG18207: Unable to dispatch message to Kafka: io.smallrye.mutiny.subscription.BackPressureFailure: Cannot emit item due to lack of requests

I have two batch streams consumbers and producers signature `Multi<Message<X>> process(Multi<Message<Y>> y)`
they both have some database work and there will be contention on the tables they both use
There is a massive backlog of messages for both topics when they start

Running either is normally fine but I was seeing occasional errors so I've added to the config:

`mp.messaging.incoming.<stream>.max.poll.records=100`

I occassionally see vertx blocked threads this doesn't appear to be fatal:

```
WARN  [io.ve.co.im.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-13,5,main] has been blocked for 8242 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
```
   
but eventually the whole thing stops and this does seem to be fatal:

```

14:50:16 ERROR [io.sm.re.me.kafka] (executor-thread-8) SRMSG18207: Unable to dispatch message to Kafka: io.smallrye.mutiny.subscription.BackPressureFailure: Cannot emit item due to lack of requests
        at io.smallrye.mutiny.operators.multi.MultiBufferWithTimeoutOp$MultiBufferWithTimeoutProcessor.flushCallback(MultiBufferWithTimeoutOp.java:162)
        at io.smallrye.mutiny.operators.multi.MultiBufferWithTimeoutOp$MultiBufferWithTimeoutProcessor.lambda$new$0(MultiBufferWithTimeoutOp.java:104)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:548)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

```	
14:50:16 ERROR [io.qu.mu.ru.MutinyInfrastructure] (vert.x-eventloop-thread-13) Mutiny had to drop the following exception: io.vertx.core.impl.NoStackTraceThrowable: Transaction already complete

14:50:59 WARN  [io.sm.re.me.kafka] (vert.x-eventloop-thread-14) SRMSG18231: The amount of received messages without acking is too high for topic partition 'mytopic', amount 2. The last committed offset was 775. It means that the Kafka connector received Kafka Records that have neither be acked nor nacked in a timely fashion. The connector accumulates records in memory, but that buffer reached its maximum capacity or the deadline for ack/nack expired. The connector cannot commit as a record processing has not completed.
```

This seems to coincide with a subscriber leaving the kafka server:
`
2021-10-22 10:51:00,213 - INFO  [data-plane-kafka-request-handler-3:Logging@66] - [GroupCoordinator 1]: Member[group.instance.id None, member.id kafka-consumer-<mytopic>-6e020433-73d7-46ab-b6b8-19ff68174717] in group 33dd1b61-caa8-439f-8631-81148dd1787f has left, removing it from the group`

it never recovers

I've tried adding the annotation below but it doesn't appear to make any difference:

@Retry(delay=100, delayUnit=ChronoUnit.MILLIS, maxRetries=10)

The thread blocked messages look like this and there are several before it fails:

```
3,5,main] has been blocked for 2020 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at java.base@11.0.9/java.util.Arrays.copyOf(Arrays.java:3689)
        at java.base@11.0.9/java.util.concurrent.CopyOnWriteArrayList.add(CopyOnWriteArrayList.java:432)
        at io.quarkus.arc.runtime.devconsole.Invocation$Builder.addChild(Invocation.java:165)
        at io.quarkus.arc.runtime.devconsole.Invocation$Builder.newChild(Invocation.java:120)
        at io.quarkus.arc.runtime.devconsole.InvocationTree.invocationStarted(InvocationTree.java:23)
        at io.quarkus.arc.runtime.devconsole.InvocationTree_ClientProxy.invocationStarted(InvocationTree_ClientProxy.zig:138)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager_Subclass.getTransaction(CDIDelegatingTransactionManager_Subclass.zig:693)
        at io.smallrye.context.jta.context.propagation.JtaContextProvider.currentTransaction(JtaContextProvider.java:102)
        at io.smallrye.context.jta.context.propagation.JtaContextProvider.currentContext(JtaContextProvider.java:39)
        at io.smallrye.context.impl.ThreadContextProviderPlan.takeThreadContextSnapshots(ThreadContextProviderPlan.java:72)
        at io.smallrye.context.impl.SlowCapturedContextState.<init>(SlowCapturedContextState.java:25)
        at io.smallrye.context.SmallRyeThreadContext.captureContext(SmallRyeThreadContext.java:729)
        at io.smallrye.context.SmallRyeThreadContext.contextualConsumer(SmallRyeThreadContext.java:539)
        at io.smallrye.mutiny.context.BaseContextPropagationInterceptor.decorate(BaseContextPropagationInterceptor.java:77)
        at io.smallrye.mutiny.infrastructure.Infrastructure.decorate(Infrastructure.java:153)
        at io.smallrye.mutiny.groups.UniOnItem.transformToUni(UniOnItem.java:168)
        at io.smallrye.mutiny.groups.UniOnNull.failWith(UniOnNull.java:41)
        at io.smallrye.mutiny.streams.stages.FlatMapCompletionStageFactory$FlatMapCompletionStage.lambda$apply$0(FlatMapCompletionStageFactory.java:52)
        at io.smallrye.mutiny.streams.stages.FlatMapCompletionStageFactory$FlatMapCompletionStage$$Lambda$1006/0x0000000800afe040.apply(Unknown Source)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.groups.MultiOnItem.lambda$transformToUni$6(MultiOnItem.java:256)
        at io.smallrye.mutiny.groups.MultiOnItem$$Lambda$1007/0x0000000800afe440.apply(Unknown Source)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:176)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:98)
        at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
        at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:83)
        at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:67)
        at io.smallrye.mutiny.operators.multi.MultiOnItemInvoke$MultiOnItemInvokeProcessor.onItem(MultiOnItemInvoke.java:41)
        at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
        at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:67)
        at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:67)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToMulti$FlatMapPublisherSubscriber.onNext(UniOnItemTransformToMulti.java:59)
        at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
        at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:83)
        at io.smallrye.reactive.messaging.kafka.impl.KafkaRecordStream$KafkaRecordStreamSubscription.run(KafkaRecordStream.java:200)
        at io.smallrye.reactive.messaging.kafka.impl.KafkaRecordStream$KafkaRecordStreamSubscription.lambda$dispatch$4(KafkaRecordStream.java:180)
        at io.smallrye.reactive.messaging.kafka.impl.KafkaRecordStream$KafkaRecordStreamSubscription$$Lambda$1379/0x0000000800c3cc40.handle(Unknown Source)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$1077/0x0000000800b61440.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.9/java.lang.Thread.run(Thread.java:834)

```

I've looked at https://quarkus.io/blog/mutiny-back-pressure/ and it I'm confused if this is a consumer or sender  problem, from the page it sounds like it's a sender problem but the timeouts indicate it's struggling to process the messages it's receiving, it doesn't sound like it's sending faster than kafka can receive them.

I've no consumer for the output topic in quarkus I expect another processes to consume the messages.

from the page I understand back pressure should be handled for me: 

> Mutiny implements the Reactive Streams protocol for you. In other words, when using Multi, you are using a Publisher following the Reactive Streams protocol. All the subscription handshakes and requests negotiations are done for you.

The fact this can fail after the one consumer has caught up is also very confusing as there would then be no database contention. Reducing the number of messages in the block processing seems to make it worse rather than better:

`Multi<List<Message<SecurityAdditionalDetailValue>>> multiMessages = incoming.group().intoLists().of(100, Duration.ofSeconds(1));`

Dropping messages is not an option.

### Expected behavior

All messages to be consumed and all new messages sent

### Actual behavior

message consumption ends abruptly with no recovery

Really I'm hoping the error messages/stack traces lead some insight but I can look at creating a test case.

### How to Reproduce?

Large backlog

Two slow consumers of messages

### Output of `uname -a` or `ver`

Linux JHC8700TP 5.10.16.3-microsoft-standard-WSL2 

### Output of `java -version`

17

### Quarkus version or git rev

2.3.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.1

**Comment by msillence** [comment]
Should I maybe close this and raise an enhancement request to limit the number of inflight messages

We will have times we want to process a large backlog of messages and also the broker will be able to deliver messages faster than we can finish consuing them

**Comment by ozangunalp** [comment]
Actually, there is a limit of buffered inbound messages waiting to be processed, it applies depending on the `max.poll.records` configuration. 
However, the grouping function should have its own buffer. Maybe it is somehow messing up with the number of requests sent to the upstream.
I am sure @cescoffier has more to say on this.

**Comment by cescoffier** [comment]
This grouping operator changes the upstream requests to list-size * n. So here we have list-size set to 100, which means we request 100 * n, where n is the downstream request. 

The logic is simple. The downstream asks for n items, and in this case the items are list of, at most, 100 things. So we ask for 100 * n.

**Comment by cescoffier** [comment]
Closing in favor of an enhancement request as proposed in https://github.com/quarkusio/quarkus/issues/20951#issuecomment-957756675
