### ISSUE TITLE
redis client error when using client type sentinel

### ISSUE THREAD

**Issue by itboy87** [quarkusio/quarkus#20962]
### Describe the bug

I have deployed sentinel Redis on Kubernetes with 3 pods with helm following this:
`https://github.com/bitnami/charts/tree/master/bitnami/redis`

with this command:
`helm install redis-sentinel bitnami/redis --create-namespace -n redis -f redis-sentinel-values.yaml`

where `redis-sentinel-values.yaml` is:
```
sentinel:
  enabled: true

global:
  redis:
    password: "redis@pass"

pdb:
  create: true
  minAvailable: 2


master:
  persistence:
    size: 1Gi
replica:
  persistence:
    size: 1Gi

commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
  maxmemory 600mb
  maxmemory-policy allkeys-lru
  maxclients 40000

sysctl:
  enabled: true
  mountHostSys: true
  command:
    - /bin/sh
    - -c
    - |-
      install_packages procps
      sysctl -w net.core.somaxconn=10000
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled

```

Pods working fine and I'm connecting with following configuration using yaml env:
```
            - name: QUARKUS_REDIS_PASSWORD
              value: redis@pass
            - name: QUARKUS_REDIS_HOSTS
              value: redis://redis-sentinel-headless.redis.svc.cluster.local:26379
            - name: QUARKUS_REDIS_CLIENT_TYPE
              value: sentinel
```

But I'm getting following crashes in logs:
```
2021-10-24 08:30:19,031 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-0) Uncaught exception received by Vert.x: java.lang.IllegalStateException: Attempt to recycle more than permitted
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.recycle(SimpleConnectionPool.java:652)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.access$2500(SimpleConnectionPool.java:79)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool$LeaseImpl.recycle(SimpleConnectionPool.java:620)
        at io.vertx.redis.client.impl.PooledRedisConnection.close(PooledRedisConnection.java:83)
        at io.vertx.redis.client.impl.RedisSentinelConnection.close(RedisSentinelConnection.java:70)
        at io.vertx.redis.client.impl.BaseRedisClient.lambda$null$0(BaseRedisClient.java:54)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

Am I doing something wrong?

### How to Reproduce?

Please following above to to reproduce.

### Output of `uname -a` or `ver`

Linux app-5b8c6b9577-4nptz 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 Linux

### Output of `java -version`

Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:MaxRAMPercentage=76 -Duser.timezone=UTC openjdk version "11.0.5" 2019-10-15 OpenJDK Runtime Environment (build 11.0.5+10-alpine-r0) OpenJDK 64-Bit Server VM (build 11.0.5+10-alpine-r0, mixed mode)

### Quarkus version or git rev

2.3.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.1 ------------------------------------------------------------  Build time:   2021-06-14 14:47:26 UTC Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e  Kotlin:       1.4.31 Groovy:       3.0.7 Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM:          11.0.12 (GraalVM Community 11.0.12+6-jvmci-21.2-b08) OS:           Mac OS X 11.5 x86_64

**Comment by itboy87** [comment]
any update?

**Comment by geoand** [comment]
cc @pmlopes

**Comment by itboy87** [comment]
@pmlopes any update on this issue?

**Comment by pyranja** [comment]
We are also seeing these errors when using native vertx 4.2.5 redis client in cluster mode.
@pmlopes is there an update on this? Any hints to investigate?

**Comment by cescoffier** [comment]
I was unable to reproduce it. In the meantime, the Vert.x Redis client has been improved greatly, and Quarkus provides a new integration with Redis. Please re-open with an up-to-date and standalone reproducer if you still see the issue.
