### ISSUE TITLE
EntityManager doesn't work for quarkus scheduler

### ISSUE THREAD

**Issue by fandiluo** [quarkusio/quarkus#2102]
```
@ApplicationScoped
public class Scheduler {

  @Inject
  EntityManager entityManager;

  @Scheduled(every = "10s")
  void run() {
    Company company = entityManager.find(Company.class, 1);
    System.out.println(company);
  }
}
```

 ```
ERROR [org.qua.cor.JobRunShell] (DefaultQuartzScheduler_Worker-1) Job io.quarkus.scheduler.Scheduler.1_com.gateweb.transsexual.Scheduler_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de threw an unhandled Exception: : javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
        at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.delegate(Unknown Source)
        at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.getOrCreateEntityManager(Unknown Source)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:91)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.find(TransactionScopedEntityManager.java:135)
        at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.find(ForwardingEntityManager.java:58)
        at com.gateweb.transsexual.Scheduler.run(Scheduler.java:18)
        at com.gateweb.transsexual.Scheduler_ClientProxy.run(Unknown Source)
        at com.gateweb.transsexual.Scheduler_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de.invoke(Unknown Source)
        at io.quarkus.scheduler.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:264)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

```
 ERROR [org.qua.cor.ErrorLogger] (DefaultQuartzScheduler_Worker-1) Job (io.quarkus.scheduler.Scheduler.1_com.gateweb.transsexual.Scheduler_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de threw an exception.: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
        at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.delegate(Unknown Source)
        at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.getOrCreateEntityManager(Unknown Source)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:91)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.find(TransactionScopedEntityManager.java:135)
        at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.find(ForwardingEntityManager.java:58)
        at com.gateweb.transsexual.Scheduler.run(Scheduler.java:18)
        at com.gateweb.transsexual.Scheduler_ClientProxy.run(Unknown Source)
        at com.gateweb.transsexual.Scheduler_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de.invoke(Unknown Source)
        at io.quarkus.scheduler.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:264)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more
```

**Comment by gsmet** [comment]
@mkouba I think you already fixed a similar issue for the tests? Or was it @FroMage ?

**Comment by FroMage** [comment]
Well, I think it was @stuartwdouglas in a232c70d13c17f335f0fb313e58ef3522443f8cf

**Comment by FroMage** [comment]
It was about adding request scopes to tests. But for jobs, I'm not sure request scopes make a lot of sense. 

Well, actually you could totally argue that each job has its own request. I think it would actually make sense.

**Comment by mkouba** [comment]
Hm, currently we don't activate the request context for a scheduled method invocation. I think we should. I'll send a PR.

@fandiluo  The easiest workaround is to annotate the method with `@ActivateRequestContext` .

**Comment by mkouba** [comment]
> Well, actually you could totally argue that each job has its own request. I think it would actually make sense.

Exactly.

**Comment by fandiluo** [comment]
@mkouba Thanks, it works .

**Comment by renandeandradevaz** [comment]
I'm facing the same issue in my Kotlin project.

When I do with @Singleton:

```
@Singleton
@ActivateRequestContext
open class Scheduler {

	@Inject
	lateinit var em: EntityManager

	@Transactional
	@Scheduled(every = "10s")
	@ActivateRequestContext
	fun createGift() {
		val gift = Gift()
		gift.name = "test"
		em.persist(gift)
	}
}
```

I get this error:

`Caused by: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped`



When I use @ApplicationScoped:

```
@ApplicationScoped
@ActivateRequestContext
open class Scheduler {

	@Inject
	lateinit var em: EntityManager

	@Transactional
	@Scheduled(every = "10s")
	@ActivateRequestContext
	fun createGift() {
		val gift = Gift()
		gift.name = "test"
		em.persist(gift)
	}
}
```

I get this error:

`Caused by: javax.enterprise.inject.spi.DefinitionException: Normal scoped beans must declare a non-private constructor with no parameters: CLASS bean [types=[org.acme.scheduling.Scheduler, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.scheduling.Scheduler]`



I'm using quarkus 0.13.3 version.

Can someone help me?

Thanks!

**Comment by renandeandradevaz** [comment]
@mkouba

**Comment by renandeandradevaz** [comment]
I created the issue https://github.com/quarkusio/quarkus/issues/2175 to treat this problem separately

**Comment by stuartwdouglas** [comment]
Annotating with @Transactional will also work, as the entity manager will only need the request scope if no transaction is active.

**Comment by stuartwdouglas** [comment]
But the proper fix is to have the request scope active all the time, IMHO we should not have any entry points that don't active it.

**Comment by mkouba** [comment]
Neither `@Transactional` works - see also https://github.com/quarkusio/quarkus/issues/2175#issuecomment-485730853

**Comment by DSVDiniz** [comment]
I'm having the same issue,  but I'm using Quartz instead of the quarkus Scheduler. I've tried adding @Transactional and @ActivateRequestContext, but both didn't work.
`@ApplicationScoped
public class SchedulerComprot {
	@Inject
	Scheduler quartz;

	void onStart(@Observes StartupEvent event) throws SchedulerException {
		JobDetail jobNovos = JobBuilder.newJob(AdicionaNovoProcessoJob.class)
				.withIdentity("NovosProcessos", "Comprot")
				.build();
		Trigger triggerNovos = TriggerBuilder.newTrigger()
				.withIdentity("TriggerNovosProcessos", "Comprot")
				.startNow()
				.withSchedule(
						SimpleScheduleBuilder
						.simpleSchedule()
						.withIntervalInSeconds(1)
						.repeatForever()
				)
				.build();
		quartz.scheduleJob(jobNovos, triggerNovos);
	}
}`

`@DisallowConcurrentExecution
public class AdicionaNovoProcessoJob implements Job {
	@ActivateRequestContext
	public void execute(JobExecutionContext context) throws JobExecutionException {
		PanacheQuery<Filial> filiaisClienteCasa = Filial.findById(1);
        }
}`
`2020-09-28 16:02:09,734 ERROR [org.qua.cor.JobRunShell] (QuarkusQuartzScheduler_Worker-3) Job Comprot.NovosProcessos threw an unhandled Exception: : javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
	at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.arc$delegate(RequestScopedEntityManagerHolder_ClientProxy.zig:68)
	at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.getOrCreateEntityManager(RequestScopedEntityManagerHolder_ClientProxy.zig:220)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:77)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.find(TransactionScopedEntityManager.java:141)
	at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.find(ForwardingEntityManager.java:42)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.findById(AbstractJpaOperations.java:255)
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.findById(JpaOperations.java:167)
	at br.com.martinelliadvogados.entity.Filial.findById(Filial.java)
	at br.com.martinelliadvogados.job.AdicionaNovoProcessoJob.execute(AdicionaNovoProcessoJob.java:35)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)`

**Comment by stuartwdouglas** [comment]
AdicionaNovoProcessoJob is created by Quartz, not be CDI, interceptors won't work.

**Comment by mkouba** [comment]
In fact, this should work because we override the default `org.quartz.spi.JobFactory` here:
https://github.com/quarkusio/quarkus/blob/master/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L429-L439

@DSVDiniz What version of quarkus do you use?

**Comment by DSVDiniz** [comment]
1.8.1.Final

**Comment by mkouba** [comment]
@DSVDiniz Ok, where is the `AdicionaNovoProcessoJob` class located? Is it a part of the application (`src/main/java`) or a dependency?

**Comment by DSVDiniz** [comment]
Part of the application

**Comment by DSVDiniz** [comment]
Also, as a side note, the problem only occurs with panache queries such as list(), when I'm updating/persisting entities with panache (just using the simplest way, by setting attributes and doing .persist()) everything works as normal.

**Comment by mkouba** [comment]
@DSVDiniz Is there a chance that you could try to forge a minimal reproducer project?

**Comment by DSVDiniz** [comment]
Sure, as soon as I'm done I'll post it here.

**Comment by DSVDiniz** [comment]
I found out the problem, the job class needed to be @ApplicationScoped:
```
@DisallowConcurrentExecution
@ApplicationScoped
public class MyJob implements Job {
	@Transactional
	public void execute(JobExecutionContext context) throws JobExecutionException {
		PanacheQuery<MyEntity> stuff = MyEntity.find("from MyEntity");
	}
}
```
If you still want the minimal reproducer project, here it is https://github.com/DSVDiniz/code-with-quarkus

**Comment by mkouba** [comment]
The scope shouldn't be necessary. I'll take a look at your reproducer. Thanks!

**Comment by mkouba** [comment]
Ah, I can see the problem now - we only add the scope annotation automatically if the job "requires container services" - which is currently interpreted as "has `@Inject`, `@PostConstruct` or `@PreDestroy`". I think that we could easily improve this to also contain all interceptor bindings (and possibly qualifiers).

In any case, a scope annotation does never hurt ;-).
