### ISSUE TITLE
Gradle quarkusDev causes NoClassDefFoundError

### ISSUE THREAD

**Issue by jskov** [quarkusio/quarkus#2103]
I could run the quarkusDev task with the 0.13.1 release.

But the current state of the gradle plugin (def029f) causes this failure:

````
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.NoClassDefFoundError: io/quarkus/deployment/devmode/HotReplacementContext
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at io.quarkus.dev.RuntimeCompilationSetup.setup(RuntimeCompilationSetup.java:53)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:60)
Caused by: java.lang.ClassNotFoundException: io.quarkus.deployment.devmode.HotReplacementContext
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 11 more

> Task :quarkusDev
````

This is probably due to refactoring in the proper quarkus projects, which is not properly reflected into the Gradle plugin, which assumes all necessary classes available from the single jar containing DevModeMain.
(or maybe it is because using mavenLocal() for artifacts does not work, for some reason - but the assumption in the plugin task suggests the above explanation).

**Comment by gsmet** [comment]
@jskov I see you committed something to your fork, do you plan to open a PR?

**Comment by gsmet** [comment]
@jskov btw, I seem to remember @stalep saying that `quarkusDev` had problems and that you should use `build` instead. But if we have a fix for that, that's all better!

**Comment by jskov** [comment]
Yes, I have made the PR.
