### ISSUE TITLE
Qute: Property "getTime" not found on the base object "java.util.Date"

### ISSUE THREAD

**Issue by Mai-Lapyst** [quarkusio/quarkus#21107]
### Describe the bug

When using `getTime` on a `java.util.Date` in an qute-template, qute throws an exception, where the java version works correctly.

### Expected behavior

That it is possible to use `getTime` on a `java.util.Date` in an qute-template.

### Actual behavior

Qute throws following error:
<details>

```
2021-10-31 02:21:15,981 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /time failed, error id: e16ac237-ee82-4b73-bc19-68393a8afeb1-1: org.jboss.resteasy.spi.UnhandledException: java.util.concurrent.CompletionException: io.quarkus.qute.TemplateException
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:614)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:135)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:90)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.util.concurrent.CompletionException: io.quarkus.qute.TemplateException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:670)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsync(TemplateImpl.java:90)
	at io.quarkus.qute.runtime.TemplateProducer$InjectableTemplateInstanceImpl.renderAsync(TemplateProducer.java:154)
	at io.quarkus.resteasy.qute.runtime.TemplateResponseFilter.filter(TemplateResponseFilter.java:62)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:361)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
	... 18 more
Caused by: io.quarkus.qute.TemplateException
	at io.quarkus.qute.CompletedStage.get(CompletedStage.java:44)
	at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.lambda$renderData$3(TemplateImpl.java:110)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderData(TemplateImpl.java:104)
	... 26 more
Caused by: io.quarkus.qute.TemplateException: Property "getTime" not found on the base object "java.util.Date" in expression {now.getTime} in template time.html on line 6
	at io.quarkus.qute.EvaluatorImpl.propertyNotFound(EvaluatorImpl.java:208)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:169)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:113)
	at io.quarkus.qute.EvaluatorImpl.lambda$resolveReference$2(EvaluatorImpl.java:117)
	at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:228)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:117)
	at io.quarkus.qute.EvaluatorImpl.evaluate(EvaluatorImpl.java:81)
	at io.quarkus.qute.ResolutionContextImpl.evaluate(ResolutionContextImpl.java:28)
	at io.quarkus.qute.ExpressionNode.resolve(ExpressionNode.java:25)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:153)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:37)
	at io.quarkus.qute.Parser$1.resolve(Parser.java:1013)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:34)
	... 27 more
```
</details>

### How to Reproduce?

Reproducing archive: [date_gettime_bug.zip](https://github.com/quarkusio/quarkus/files/7447900/date_gettime_bug.zip)

Steps to reproduce (with archive):
- build the native image with `./mvnw package -Pnative`
- run the native image with `./target/date_gettime_bug-1.0.0-SNAPSHOT-runner`
- visit `localhost:8080/time` in your browser

### Output of `uname -a` or `ver`

Linux lagann 5.14.10-arch1-1 #1 SMP PREEMPT Thu, 07 Oct 2021 20:00:23 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19

### Quarkus version or git rev

2.4.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

native-image version: 21.3.0

**Comment by mkouba** [comment]
In order to make this work in a native image you'll need to use:
* type-safe templates or type-safe expressions, or
* `@TemplateData`, or
* `@RegisterForReflection`

See also the [Native Executables](https://quarkus.io/guides/qute-reference#native_executables) section in the docs.
