### ISSUE TITLE
Gradle MulitModule Project: quarkusGenerateCodeTests: java.lang.NullPointerException

### ISSUE THREAD

**Issue by iamcyw** [quarkusio/quarkus#21106]
### Describe the bug

on my [project](https://github.com/tower-projects/tower-web-template)
use quarkus 2.2.1.Final,can be start success
but,when upgrade to 2.4.0.Final to build has exception

```
Caused by: java.lang.NullPointerException
        at io.quarkus.gradle.builder.GradleApplicationModelBuilder.initProjectModule(GradleApplicationModelBuilder.java:487)
        at io.quarkus.gradle.builder.GradleApplicationModelBuilder.initProjectModuleAndBuildPaths(GradleApplicationModelBuilder.java:443)
        at io.quarkus.gradle.builder.GradleApplicationModelBuilder.collectDependencies(GradleApplicationModelBuilder.java:393)
        at io.quarkus.gradle.builder.GradleApplicationModelBuilder.lambda$collectDependencies$5(GradleApplicationModelBuilder.java:320)
        at io.quarkus.gradle.builder.GradleApplicationModelBuilder.collectDependencies(GradleApplicationModelBuilder.java:320)
        at io.quarkus.gradle.builder.GradleApplicationModelBuilder.buildAll(GradleApplicationModelBuilder.java:160)
        at io.quarkus.gradle.extension.QuarkusPluginExtension.create(QuarkusPluginExtension.java:217)
        at io.quarkus.gradle.extension.QuarkusPluginExtension.getApplicationModel(QuarkusPluginExtension.java:211)
        at io.quarkus.gradle.tasks.QuarkusGenerateCode.prepareQuarkus(QuarkusGenerateCode.java:91)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

### How to Reproduce?

1.clone my project
git@github.com:tower-projects/tower-web-template.git
2. exec:
./gradlew clean quarkusDev -p server --stacktrace -x test

**Comment by glefloch** [comment]
Thanks @iamcyw, I will have a look.

**Comment by antonwiens** [comment]
Same problem for me, some multi module projects failing with this error.

**Comment by antonwiens** [comment]
> Same problem for me, some multi module projects failing with this error.
Seems like the cause for me is a kotlin multiplatform module with jvm output.

I found a workaround for me:
``` kotlin
kotlin {
    jvm() {
       withJava()
    }
}
```

Setting withJava() seems to fix the error in the quarkus plugin.
I don't know why, tho.

**Comment by iamcyw** [comment]
> > Same problem for me, some multi module projects failing with this error.
> 
> Seems like the cause for me is a kotlin multiplatform module with jvm output.
> 
> I found a workaround for me:
> 
> ```kotlin
> kotlin {
>     jvm() {
>        withJava()
>     }
> }
> ```
> 
> Setting withJava() seems to fix the error in the quarkus plugin. I don't know why, tho.

Thanks @antonwiens ,I seem to be too.
I remember it was not added for some reasons, but I don’t remember clearly
