### ISSUE TITLE
Quarkus ignores dev profile property for hibernate ORM configurations

### ISSUE THREAD

**Issue by bardsoleim** [quarkusio/quarkus#21122]
### Describe the bug

After updating to Quarkus 2.4.0 from 2.2.1 we can no longer run quarkus dev mode as hibernate will always try to run a drop & create schema. 
We can not run drop & create with hibernate since we use custom data types with flyway.

It ignores this property scientifically:
%qa.quarkus.hibernate-orm.database.generation=none

### Expected behavior

Database schema should not be created

### Actual behavior

```
Failed to start application (with profile qa): org.hibernate.MappingException: No Dialect mapping for JDBC type: 2003
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:71)
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:103)
	at org.hibernate.dialect.Dialect.getTypeName(Dialect.java:404)
	at org.hibernate.mapping.Column.getSqlType(Column.java:238)
	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:96)
	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:30)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createFromMetadata(SchemaCreatorImpl.java:316)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:167)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:136)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:122)
	at org.hibernate.tool.hbm2ddl.SchemaExport.doExecution(SchemaExport.java:314)
	at io.quarkus.hibernate.orm.runtime.devconsole.HibernateOrmDevConsoleInfoSupplier.generateDDL(HibernateOrmDevConsoleInfoSupplier.java:77)
	at io.quarkus.hibernate.orm.runtime.devconsole.HibernateOrmDevConsoleInfoSupplier.pushPersistenceUnit(HibernateOrmDevConsoleInfoSupplier.java:35)
	at io.quarkus.hibernate.orm.runtime.devconsole.HibernateOrmDevConsoleIntegrator.integrate(HibernateOrmDevConsoleIntegrator.java:15)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:292)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:74)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:67)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:149)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:58)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.1.0

### Output of `java -version`

17

### Quarkus version or git rev

2.4.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.3

**Comment by yrodiere** [comment]
This specific code does not drop and create the schema, it just generates the SQL so that we can display it on the console. The SQL doesn't get executed.

That being said, it's not normal that an error in this generation would stop your application from starting up. I'll submit a PR to ignore the failure.

**Comment by kny78** [comment]
@yrodiere Thanks for the fix.

But does it really need to do the script-generation? Is it not better to skip it all together?

**Comment by yrodiere** [comment]
@kny78 This script generation is only there to display the scripts in the Dev UI. It has nothing to do with running the application, and will only happen in Dev mode.

If you use Flyway, you might still need this information, be it only to initialize your first Flyway script with the DDL scripts generated by Hibernate ORM. Yes I know, not everyone wants that, but some do.

If you don't need these generated scripts, all you have to do is not look at that webpage in the Dev UI.
