### ISSUE TITLE
Redis sentinel crashes

### ISSUE THREAD

**Issue by itboy87** [quarkusio/quarkus#21178]
### Describe the bug

Installed redis sentinel from here `https://github.com/bitnami/charts/tree/master/bitnami/redis`
Connecting Redis sentinel with following env values
```
            - name: QUARKUS_REDIS_HOSTS
              value: redis://redis-sentinel.redis.svc.cluster.local:26379
            - name: QUARKUS_REDIS_CLIENT_TYPE
              value: sentinel
```

Getting following crashes
```
2021-11-03 19:52:51,556 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-0) Uncaught exception received by Vert.x: java.lang.IllegalStateException: Attempt to recycle more than permitted
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.recycle(SimpleConnectionPool.java:741)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.access$3300(SimpleConnectionPool.java:82)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool$LeaseImpl.recycle(SimpleConnectionPool.java:704)
        at io.vertx.redis.client.impl.PooledRedisConnection.close(PooledRedisConnection.java:83)
        at io.vertx.redis.client.impl.RedisSentinelConnection.close(RedisSentinelConnection.java:70)
        at io.vertx.redis.client.impl.BaseRedisClient.lambda$null$0(BaseRedisClient.java:54)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:81)
        at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:260)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:22)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.Promise.complete(Promise.java:66)
        at io.vertx.redis.client.impl.RedisStandaloneConnection.lambda$handle$5(RedisStandaloneConnection.java:309)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71)
        at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:267)
        at io.vertx.core.impl.AbstractContext.execute(AbstractContext.java:58)
        at io.vertx.redis.client.impl.RedisStandaloneConnection.handle(RedisStandaloneConnection.java:283)
        at io.vertx.redis.client.impl.RESPParser.handleResponse(RESPParser.java:319)
        at io.vertx.redis.client.impl.RESPParser.handleSimpleString(RESPParser.java:235)
        at io.vertx.redis.client.impl.RESPParser.handle(RESPParser.java:81)
        at io.vertx.redis.client.impl.RESPParser.handle(RESPParser.java:24)
        at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:409)
        at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:97)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
        at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
        at io.vertx.core.net.impl.NetSocketImpl.lambda$handleMessage$9(NetSocketImpl.java:390)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
        at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
        at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:389)
        at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

### Output of `uname -a` or `ver`

Linux app-5b8c6b9577-4nptz 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 Linux

### Output of `java -version`

Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:MaxRAMPercentage=76 -Duser.timezone=UTC openjdk version "11.0.5" 2019-10-15 OpenJDK Runtime Environment (build 11.0.5+10-alpine-r0) OpenJDK 64-Bit Server VM (build 11.0.5+10-alpine-r0, mixed mode)

### Quarkus version or git rev

2.4.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.1 ------------------------------------------------------------ Build time: 2021-06-14 14:47:26 UTC Revision: 989ccc9952b140ee6ab88870e8a12f1b2998369e Kotlin: 1.4.31 Groovy: 3.0.7 Ant: Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM: 11.0.12 (GraalVM Community 11.0.12+6-jvmci-21.2-b08) OS: Mac OS X 11.5 x86_64

**Comment by itboy87** [comment]
duplicate of https://github.com/quarkusio/quarkus/issues/20962
