### ISSUE TITLE
Multiple cache invalidation not working with a native build

### ISSUE THREAD

**Issue by PVergneau** [quarkusio/quarkus#21174]
### Describe the bug

Hello, 
I have a REST endpoint to invalidate all my caches like so:

```
    @DELETE
    @CacheInvalidateAll(cacheName = Caches.MY_CACHE_A)
    @CacheInvalidateAll(cacheName = Caches.MY_CACHE_B)
    @CacheInvalidateAll(cacheName = Caches.MY_CACHE_C)
    public void invalidateCaches() {
        logger.info("Invalidating declared caches");
    }
```

When running in dev mode, everything is fine. The DEBUG logs shows that all caches are properly invalidated :

```
2021-11-03 15:06:12,757 DEBUG [io.qua.cac.run.CacheInvalidateAllInterceptor] (executor-thread-0) Invalidating all entries from cache ["cacheA"]
2021-11-03 15:06:12,759 DEBUG [io.qua.cac.run.CacheInvalidateAllInterceptor] (executor-thread-0) Invalidating all entries from cache ["cacheB"]
2021-11-03 15:06:12,759 DEBUG [io.qua.cac.run.CacheInvalidateAllInterceptor] (executor-thread-0) Invalidating all entries from cache ["cacheC"]
```

When running in native mode, a bug investigation revealed that only one cache is invalidated. This was reproduced on locahost. Calls to other resources use data from the cache instead of calling the backends.
`2021-11-03 15:06:12,759 DEBUG [io.qua.cac.run.CacheInvalidateAllInterceptor] (executor-thread-0) Invalidating all entries from cache ["cacheB"]`

(i have changed the cache names above but even after changing the order of the 3 annotations, it was always the same cache that was invalidated)

A temporary workaround is to have my multi-annotated method to delegate the invalidation to as many sub methods as necessary, each one with its own invalidation. Obviously that is the opposite of the interest to have multiple annotations. 

(And as a side note, i know this is somewhere on the roadmap: being able to programmatically invalidate all caches from my enum instead of adding/forgetting to add an annotation would even be better)

Thanks for your help !
Pascal.

### Expected behavior

All caches mentionned in each annotation are flushed.

### Output of `uname -a` or `ver`

Linux Sunnyvale 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)

### Quarkus version or git rev

2.1.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.8.3

**Comment by gwenneg** [comment]
Thanks for reporting this @PVergneau, I'll have a look at it.

**Comment by gwenneg** [comment]
@mkouba I made a quick test and I'm surprised to see that `InterceptorBindings#getInterceptorBindings` returns a `null` value in native mode while it does return the caching interceptor bindings in JVM mode. Is that expected?

This is probably not related with the current issue but I'm curious about that difference. 😃

**Comment by mkouba** [comment]
> This is probably not related with the current issue but I'm curious about that difference. smiley

Hm, that's not expected. Do you have a reproducer I can look at?

**Comment by gwenneg** [comment]
Not yet, I'll create one.

**Comment by gwenneg** [comment]
Here's a reproducer: https://github.com/gwenneg/quarkus-cache-native

The JVM tests are OK but the native version is failing:
```
Executing "/home/glepage/git/quarkus-cache-native/target/code-with-quarkus-1.0.0-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/home/glepage/git/quarkus-cache-native/target/quarkus.log -Dquarkus.log.file.enable=true"
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-11-05 10:34:12,915 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT native (powered by Quarkus 2.4.1.Final) started in 0.011s. Listening on: http://0.0.0.0:8081
2021-11-05 10:34:12,915 INFO  [io.quarkus] (main) Profile prod activated. 
2021-11-05 10:34:12,915 INFO  [io.quarkus] (main) Installed features: [cache, cdi, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/home/glepage/.m2/repository/org/codehaus/groovy/groovy/3.0.8/groovy-3.0.8.jar) to constructor java.lang.AssertionError(java.lang.String)
[ERROR] WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release
2021-11-05 10:34:13,898 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /test-cache/method1 failed, error id: 628fa176-d87a-4c4e-91df-22fcd94cb402-1: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: duplicate element: @io.quarkus.cache.CacheInvalidateAll()
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:135)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:90)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.IllegalArgumentException: duplicate element: @io.quarkus.cache.CacheInvalidateAll()
	at java.util.ImmutableCollections$Set12.<init>(ImmutableCollections.java:510)
	at java.util.Set.of(Set.java:699)
	at org.acme.GreetingResource_Subclass.<init>(GreetingResource_Subclass.zig:163)
	at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:183)
	at org.acme.GreetingResource_Bean.create(GreetingResource_Bean.zig:199)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
	at org.acme.GreetingResource_ClientProxy.arc$delegate(GreetingResource_ClientProxy.zig:67)
	at org.acme.GreetingResource_ClientProxy.arc_contextualInstance(GreetingResource_ClientProxy.zig:82)
	at io.quarkus.arc.runtime.ClientProxyUnwrapper.apply(ClientProxyUnwrapper.java:11)
	at io.quarkus.resteasy.common.runtime.QuarkusInjectorFactory$UnwrappingPropertyInjector.inject(QuarkusInjectorFactory.java:74)
	at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:80)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:401)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 17 more

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.716 s <<< FAILURE! - in org.acme.NativeGreetingResourceIT
[ERROR] org.acme.NativeGreetingResourceIT.testCache  Time elapsed: 0.931 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.
```

I had the same issue with my initial quick test. That's when I decided to add log entries in quarkus-cache and check what was happening. These entries showed me that `InterceptorBindings#getInterceptorBindings` returns null in native mode.

**Comment by gwenneg** [comment]
My previous comment was based on Quarkus `2.4.1.Final`.

Testing with `2.1.4.Final` produces a different outcome: the test won't throw an ERROR but it will fail because of the caches wasn't cleared as described by @PVergneau.

**Comment by gwenneg** [comment]
It looks like there are two different issues here.

**Comment by PVergneau** [comment]
Yes we just saw that when trying to upgrade our Quarkus version. At least the first problem is blocked by the 2nd, preventing a bug in prod :)

**Comment by gwenneg** [comment]
The `IllegalArgumentException: duplicate element: @io.quarkus.cache.CacheInvalidateAll()` is a regression from `2.4.0.Final`.

`2.3.1.Final` produces the same outcome as `2.1.4.Final`.

**Comment by mkouba** [comment]
> The `IllegalArgumentException: duplicate element: @io.quarkus.cache.CacheInvalidateAll()` is a regression from `2.4.0.Final`. I don't know yet if the issue comes from Quarkus or a new GraalVM/Mandrel version.

It's a Quarkus/ArC regression - we somehow we overlooked the fact that `java.util.Set.of(E...)` throws an IAE if there are duplicate elements. I'll prepare a fix.

**Comment by mkouba** [comment]
And BTW it works in the JVM because `javax.enterprise.util.AnnotationLiteral.equals(Object)` compares the members via reflection and we don't register the interceptor binding annotations for reflection.

**Comment by PVergneau** [comment]
Great, thanks for the reactivity !
