### ISSUE TITLE
Enforce Maven version at bootstrap?

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2124]
We had a few reports of build failing with older Maven versions (apparently a 3.5.0):

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.13.2:build (default) on project my-app: Failed to resolve application model org.openshift.appgen:my-app::jar:1.0.0 dependencies: Failed to inject extension deployment dependencies for org.openshift.appgen:my-app:jar:1.0.0: org.eclipse.aether.transfer.TransferResource.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/io/File;Lorg/eclipse/aether/RequestTrace;)V -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:0.13.2:build (default) on project my-app: Failed to resolve application model org.openshift.appgen:my-app::jar:1.0.0 dependencies
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to resolve application model org.openshift.appgen:my-app::jar:1.0.0 dependencies
at io.quarkus.maven.BuildMojo.execute(BuildMojo.java:149)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
... 20 more
Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to inject extension deployment dependencies for org.openshift.appgen:my-app:jar:1.0.0
at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.injectDeploymentDependencies(BootstrapAppModelResolver.java:184)
at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveModel(BootstrapAppModelResolver.java:90)
at io.quarkus.maven.BuildMojo.execute(BuildMojo.java:147)
... 22 more
Caused by: java.lang.NoSuchMethodError: org.eclipse.aether.transfer.TransferResource.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/io/File;Lorg/eclipse/aether/RequestTrace;)V
at org.eclipse.aether.connector.basic.BasicRepositoryConnector.newTransferResource(BasicRepositoryConnector.java:309)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:239)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:529)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:430)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:232)
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:268)
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:199)
at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:211)
at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:325)
at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.collectDependencies(MavenArtifactResolver.java:192)
at io.quarkus.bootstrap.resolver.maven.DeploymentInjectingDependencyVisitor.collectDependencies(DeploymentInjectingDependencyVisitor.java:128)
at io.quarkus.bootstrap.resolver.maven.DeploymentInjectingDependencyVisitor.processPlatformArtifact(DeploymentInjectingDependencyVisitor.java:110)
at io.quarkus.bootstrap.resolver.maven.DeploymentInjectingDependencyVisitor.processMetaInfDir(DeploymentInjectingDependencyVisitor.java:97)
at io.quarkus.bootstrap.resolver.maven.DeploymentInjectingDependencyVisitor.visitEnter(DeploymentInjectingDependencyVisitor.java:80)
at org.eclipse.aether.util.graph.visitor.TreeDependencyVisitor.visitEnter(TreeDependencyVisitor.java:67)
at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:343)
at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.injectDeploymentDependencies(BootstrapAppModelResolver.java:182)
... 24 more
```

@cescoffier added a version enforcement here: https://github.com/quarkusio/quarkus/pull/1379 . I wonder if we should do the same for the bootstrap.

**Comment by gsmet** [comment]
@aloubyansky WDYT? It's more a question than a task. If it's an easy fix, it might be worth it. If it requires a massive amount of work, probably not.

**Comment by aloubyansky** [comment]
Well, it doesn't look good to me. So, something has to be done about it, IMO. I'll have a look. Thanks.

**Comment by aloubyansky** [comment]
I looked into this a bit. One of the ways to check for the version at runtime would be to locate `META-INF/maven/<groupId>/<artifactId>/pom.properties` (as a resource on the CP) and read property `version`. I guess that would work in most cases (when the classpath includes the original JARs of the dependencies). If the classpath however includes shaded/merged JARs that info may or may not be available. Which could be ok, I guess.

**Comment by aloubyansky** [comment]
It'd be something like this https://github.com/aloubyansky/quarkus/commit/07a3a89c5340ae086eda56f00a5d6ae6cf275efb
Except instead of logging the result it would throw an exception if the version was too old.

**Comment by bkrahmer** [comment]
BTW, it looks like I hit this issue trying to follow the "Deploying the application as Java application in OpenShift" example from the website at https://quarkus.io/guides/openshift-s2i-guide ....

**Comment by gsmet** [comment]
@aloubyansky has it been done? I think it would be necessary if we want to update our internal Maven dependencies to 3.6 (which is required by another issue)

**Comment by aloubyansky** [comment]
There was no PR. I referenced the change it could be based upon, as an idea.

**Comment by gorshkov-leonid** [comment]
Hello, I am newby at  quarkus. What I did is just `mvn io.quarkus:quarkus-maven-plugin:1.3.2.Final:create -DprojectGroupId=com.corp -DprojectArtifactId=quarkus-test -DclassName="mapackage.TestResource" -Dpath="/hello"`. As result I do not know how to run my first example. I don't understand the root cause of this problem. Could you hint me how to runt it. Will the downgrade help me? Or maybe I should do something else?

**Comment by gorshkov-leonid** [comment]
ouch, Apache Maven 3.6.2. Sorry fo bother
