### ISSUE TITLE
AnnotationRegisteredProvidersImplementation are in unnamed module of loader 'app'

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#21250]
### Describe the bug

Running this with `jbang TodosAdd.java inbox`

```
///usr/bin/env jbang "$0" "$@" ; exit $?
// Update the Quarkus version to what you want here or run jbang with
// `-Dquarkus.version=<version>` to override it.
//DEPS io.quarkus:quarkus-bom:${quarkus.version:2.6.0.Final}@pom
//DEPS io.quarkus:quarkus-picocli
//DEPS io.quarkus:quarkus-rest-client-reactive-jackson

//Q:CONFIG quarkus.banner.enabled=false
//Q:CONFIG quarkus.log.level=ALL

//Q:CONFIG quarkus.rest-client.DayCaptain.url=https://daycaptain.com/
//JAVAC_OPTIONS -parameters

import static java.lang.String.format;
import static java.lang.System.out;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.TYPE;

import java.io.IOException;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.Date;

import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.NameBinding;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerRequestFilter;
import javax.ws.rs.ext.Provider;

import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;
import org.eclipse.microprofile.rest.client.inject.RestClient;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

@CommandLine.Command(name = "todos-add", mixinStandardHelpOptions = true)
public class TodosAdd {

    @RestClient
    DayCaptain captain;

    @Command(description = "Add the task to the backlog inbox")
    int inbox(@Parameters() String task) {

        out.println(format("Adding '%s' to DayCaptain inbox: ", task));

        captain.addToBacklog("Bearer token", task);

        return 0;
    };

}

@RegisterRestClient
@RegisterProvider(LoggingFilter.class)
interface DayCaptain {

    @POST
    @Path("/backlog-items")
    void addToBacklog(@HeaderParam("Authorization") String auth,String string);
}

class LoggingFilter implements ContainerRequestFilter {

    @Override
    public void filter(ContainerRequestContext requestContext) throws IOException {
        // TODO Auto-generated method stub
        
    }

}
```

fails to find and register the LoggingFilter and the output mesage/error isn't helping...

### Expected behavior

log the filter or have error message that gives hint on what possible solution are.

### Actual behavior

```
Exception in thread "main" java.lang.IllegalAccessError: failed to access class LoggingFilter from class io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation (LoggingFilter and io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation are in unnamed module of loader 'app')
	at io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation.<init>(AnnotationRegisteredProvidersImplementation.zig:24)
	at io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation_Bean.create(AnnotationRegisteredProvidersImplementation_Bean.zig:107)
	at io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation_Bean.create(AnnotationRegisteredProvidersImplementation_Bean.zig:122)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation_Bean.get(AnnotationRegisteredProvidersImplementation_Bean.zig:154)
	at io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation_Bean.get(AnnotationRegisteredProvidersImplementation_Bean.zig:170)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:440)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:453)
	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:423)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:232)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:253)
	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.build(RestClientCDIDelegateBuilder.java:71)
	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.build(RestClientCDIDelegateBuilder.java:59)
	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.createDelegate(RestClientCDIDelegateBuilder.java:42)
	at io.quarkus.rest.client.reactive.runtime.RestClientReactiveCDIWrapperBase.<init>(RestClientReactiveCDIWrapperBase.java:16)
	at DayCaptain$$CDIWrapper.<init>(DayCaptain$$CDIWrapper.zig:21)
	at DayCaptain$$CDIWrapper_ClientProxy.<init>(DayCaptain$$CDIWrapper_ClientProxy.zig:24)
	at DayCaptain$$CDIWrapper_Bean.proxy(DayCaptain$$CDIWrapper_Bean.zig:40)
	at DayCaptain$$CDIWrapper_Bean.get(DayCaptain$$CDIWrapper_Bean.zig:229)
	at DayCaptain$$CDIWrapper_Bean.get(DayCaptain$$CDIWrapper_Bean.zig:245)
	at TodosAdd_Bean.create(TodosAdd_Bean.zig:154)
	at TodosAdd_Bean.get(TodosAdd_Bean.zig:209)
	at TodosAdd_Bean.get(TodosAdd_Bean.zig:244)
	at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:210)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
	at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory.create(DefaultPicocliCommandLineFactory.java:43)
	at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory_ClientProxy.create(DefaultPicocliCommandLineFactory_ClientProxy.zig:155)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer.picocliCommandLine(PicocliCommandLineProducer.java:23)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.create(PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.zig:154)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.zig:184)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.zig:219)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.create(PicocliRunner_Bean.zig:203)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(PicocliRunner_Bean.zig:261)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(PicocliRunner_Bean.zig:296)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:440)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:453)
	at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:59)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:123)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
```

**Comment by maxandersen** [comment]
related to #21249

**Comment by maxandersen** [comment]
I can get it to stop complaining if LoggingFilter is a top level public class in a package.

But then having it as a static class should work too but it gives similar error.

```
///usr/bin/env jbang "$0" "$@" ; exit $?
// Update the Quarkus version to what you want here or run jbang with
// `-Dquarkus.version=<version>` to override it.
//DEPS io.quarkus:quarkus-bom:${quarkus.version:2.4.0.Final}@pom
//DEPS io.quarkus:quarkus-picocli
//DEPS io.quarkus:quarkus-rest-client-reactive-jackson

//Q:CONFIG quarkus.banner.enabled=false
//:CONFIG quarkus.log.level=ALL

//Q:CONFIG quarkus.rest-client.DayCaptain.url=https://daycaptain.com/
//JAVAC_OPTIONS -parameters
//SOURCES LoggingFilter.java

package daycaptain;

import static java.lang.String.format;
import static java.lang.System.out;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.TYPE;

import java.io.IOException;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.Date;

import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.NameBinding;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerRequestFilter;
import javax.ws.rs.ext.Provider;

import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;
import org.eclipse.microprofile.rest.client.inject.RestClient;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

@CommandLine.Command(name = "todos-add", mixinStandardHelpOptions = true)
public class TodosAdd {

    @RestClient
    DayCaptain captain;

    @Option(names="--token", defaultValue = "${DC_API_TOKEN}", required = true)
    String token;

    @Command(description = "Add the task to today's tasks")
    int today() {
        return 0;
    }

    @Command(description = "Add the task to tomorrow's tasks")
    int tomorrow() {
        return 0;
    }

    @Command(description = "Add the task to the DATE (formatted by ISO-8601, e.g. 2021-01-31")
    int date(@Parameters Date date) {
        return 0;
    }

    @Command(description = "Add the task to this week")
    int week() {
        return 0;
    }

    @Command(description = "Add the task to the backlog inbox")
    int inbox(@Parameters() String task) {

        out.println(format("Adding '%s' to DayCaptain inbox: ", task));

        captain.addToBacklog("Bearer " + token, task);

        return 0;
    };

    static class LoggingFilter implements ContainerRequestFilter {

        @Override
        public void filter(ContainerRequestContext requestContext) throws IOException {
         System.out.println("BLAH!");        
        }
    
    }
}

@RegisterRestClient
@RegisterProvider(TodosAdd.LoggingFilter.class)
interface DayCaptain {

    @POST
    @Path("/backlog-items")
    void addToBacklog(@HeaderParam("Authorization") String auth,String string);
}


```

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/gizmo/pull/92 should fix this.

**Comment by gsmet** [comment]
Given what Stuart said, this should be fixed in 2.6 by the Gizmo upgrade.

If not, please reopen.

**Comment by maxandersen** [comment]
no, this still fails.

```
2022-01-02 07:46:14,170 INFO  [io.quarkus] (main) Quarkus 2.6.0.Final on JVM started in 0.467s.
2022-01-02 07:46:14,170 INFO  [io.quarkus] (main) Profile prod activated.
2022-01-02 07:46:14,170 INFO  [io.quarkus] (main) Installed features: [cdi, jaxrs-client-reactive, picocli, rest-client-reactive, rest-client-reactive-jackson, smallrye-context-propagation, vertx]
Exception in thread "main" java.lang.IllegalAccessError: failed to access class LoggingFilter from class io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation (LoggingFilter and io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation are in unnamed module of loader 'app')
	at io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation.<init>(Unknown Source)
	at io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation_Bean.create(Unknown Source)
	at io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation_Bean.get(Unknown Source)
	at io.quarkus.rest.client.reactive.runtime.AnnotationRegisteredProvidersImplementation_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:440)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:453)
	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:424)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:233)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:256)
	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.build(RestClientCDIDelegateBuilder.java:71)
	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.build(RestClientCDIDelegateBuilder.java:59)
	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.createDelegate(RestClientCDIDelegateBuilder.java:42)
	at io.quarkus.rest.client.reactive.runtime.RestClientReactiveCDIWrapperBase.<init>(RestClientReactiveCDIWrapperBase.java:16)
	at DayCaptain$$CDIWrapper.<init>(Unknown Source)
	at DayCaptain$$CDIWrapper_ClientProxy.<init>(Unknown Source)
	at DayCaptain$$CDIWrapper_Bean.proxy(Unknown Source)
	at DayCaptain$$CDIWrapper_Bean.get(Unknown Source)
	at DayCaptain$$CDIWrapper_Bean.get(Unknown Source)
	at TodosAdd_Bean.create(Unknown Source)
	at TodosAdd_Bean.get(Unknown Source)
	at TodosAdd_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:223)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:209)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:95)
	at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory.create(DefaultPicocliCommandLineFactory.java:43)
	at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory_ClientProxy.create(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer.picocliCommandLine(PicocliCommandLineProducer.java:23)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.create(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.create(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:440)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:453)
	at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:59)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:121)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

**Comment by maxandersen** [comment]
updated sample to use 2.6 and fix missing variable syntax error.
