### ISSUE TITLE
Datasource / Dev Service

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#21253]
### Describe the bug

build.gradle is:
```gradle
dependencies {
    implementation "io.quarkus:quarkus-config-yaml"
    implementation "io.quarkus:quarkus-smallrye-graphql"
    implementation "io.quarkus:quarkus-resteasy-mutiny"
    implementation "io.quarkus:quarkus-hibernate-orm-panache"
    implementation "io.quarkus:quarkus-agroal"
    implementation "io.quarkus.security:quarkus-security"
    implementation "io.quarkus:quarkus-jdbc-postgresql"
}
```

config is:
```yaml
quarkus:
  banner:
    path: banner.txt
    enabled: true
  application:
    name: CRP-API-Service
  default-locale: zh-CN
  locales: zh-CN
  http:
    root-path: /
    non-application-root-path: q
    auth:
      proactive: true
      basic: true
      cors: true
  devservices:
    enabled: false
datasource:
  devservices:
    enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
  db-kind: postgresql
  username: postgres
  password:
  reactive: false
  jdbc:
    url: jdbc:postgresql://localhost:5432/crp_dev
    pooling-enabled: true
    transaction-isolation-level: read-committed
    initial-size: 16
    min-size: 16
    max-size: 128
```

### Expected behavior

./gradlew services:api-service:quarkusDev    running success

### Actual behavior

```log
> Task :services:api-service:quarkusDev
Listening for transport dt_socket at address: 5005
Press [h] for more options>
Tests paused
Press [r] to resume testing, [h] for more options>
Press [r] to resume testing, [o] Toggle test output, [h] for more options>
2021-11-07 22:48:25,012 WARN  [io.qua.dep.ste.BannerProcessor] (build-35) Could not locate banner file
> :se2021-11-07 22:48:26,377 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.http.auth.cors" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-11-07 22:48:27,116 WARN  [io.qua.run.con.ConfigRecorder] (Quarkus Main Thread) Build time property cannot be changed at runtime:
 - quarkus.smallrye-graphql.print-data-fetcher-exception was 'null' at build time and is now 'true'
Model classes are defined for the default persistence unit <default> but configured datasource <default> not found: the default EntityManagerFactory will not be created. To solve this, configure the default datasource. Refer to https://quarkus.io/guides/datasource for guidance.
Press [space] to restart, [e] to edit command line args (currently ''), [r] to resume testing, [o] Toggle test output, [h] for more options>
2021-11-07 22:48:27,141 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2021-11-07 22:48:27,141 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
     2021-11-07 22:48:27,260 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
        at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:122)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:143)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:444)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:65)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:105)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:1039)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: io.quarkus.runtime.configuration.ConfigurationException: Model classes are defined for the default persistence unit <default> but configured datasource <default> not found: the default EntityManagerFactory will not be created. To solve this, configure the default datasource. Refer to https://quarkus.io/guides/datasource for guidance.
        at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:72)
        at io.quarkus.hibernate.orm.runtime.JPAConfig_Subclass.startAll$$superforward1(JPAConfig_Subclass.zig:258)
        at io.quarkus.hibernate.orm.runtime.JPAConfig_Subclass$$function$$5.apply(JPAConfig_Subclass$$function$$5.zig:24)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:516)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.quarkus.hibernate.orm.runtime.JPAConfig_Subclass.startAll(JPAConfig_Subclass.zig:673)
        at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:96)
        at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy_0(HibernateOrmProcessor$startPersistenceUnits1868654632.zig:74)
        at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy(HibernateOrmProcessor$startPersistenceUnits1868654632.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:902)
        ... 12 more
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Model classes are defined for the default persistence unit <default> but configured datasource <default> not found: the default EntityManagerFactory will not be created. To solve this, configure the default datasource. Refer to https://quarkus.io/guides/datasource for guidance.
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.injectDataSource(FastBootHibernatePersistenceProvider.java:317)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(FastBootHibernatePersistenceProvider.java:178)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:61)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:149)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:58)
        ... 1 more
```

### Output of `uname -a` or `ver`

20.6.0 Darwin

### Output of `java -version`

openjdk version "11.0.2" 2019-01-15

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by pipinet** [comment]
i enable dev service work well.

**Comment by yrodiere** [comment]
Your config is incorrect; the `datasource` block should be indented so that's it's part of the `quarkus` block.

As it is, you set the `datasource.jdbc.url` property, not `quarkus.datasource.jdbc.url` as you should have. So it looks to Quarkus as if you didn't configure your datasource at all. Which explains why it works with devservices: in that case, Quarkus fills in the gaps in your configuration automatically.

Either switch to the properties format, where such intendating problems are not possible, or indent your file correctly:

```yaml
quarkus:
  banner:
    path: banner.txt
    enabled: true
  application:
    name: CRP-API-Service
  default-locale: zh-CN
  locales: zh-CN
  http:
    root-path: /
    non-application-root-path: q
    auth:
      proactive: true
      basic: true
      cors: true
  devservices:
    enabled: false
  datasource:
    devservices:
      enabled: false
    health:
      enabled: true
    metrics:
      enabled: true
    db-kind: postgresql
    username: postgres
    password:
    reactive: false
    jdbc:
      url: jdbc:postgresql://localhost:5432/crp_dev
      pooling-enabled: true
      transaction-isolation-level: read-committed
      initial-size: 16
      min-size: 16
      max-size: 128
```

**Comment by pipinet** [comment]
@yrodiere no, config is right.
