### ISSUE TITLE
No instance of TenantResolver was found for persistence unit <default>

### ISSUE THREAD

**Issue by Paul6552** [quarkusio/quarkus#21265]
### Describe the bug

After updating from quarkus 2.2.0 to version 2.3.1.Final (I tried also with version 2.4.1.Final) I added the annotation @PersistenceUnitExtension as mentioned in the migration guide here:
[Migration Guide 2.3 Quarkus](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.3)

I am dynamically retrieving the schema. No named persistence Unit.

Quarkus is working with the new annotation and also the schema is correctly retrieved after quarkus has booted up, but **at startup** I get the following error message:

`HHH000342: Could not obtain connection to query metadata: java.lang.IllegalStateException: No instance of TenantResolver was found for persistence unit <default>. You need to create an implementation for this interface to allow resolving the current tenant identifier.`

But I get this error message only at startup. To me it looks like it's a startup order issue.

Can somebody approve this?

My Code:

```
import io.quarkus.hibernate.orm.PersistenceUnitExtension;
import io.quarkus.hibernate.orm.runtime.tenant.TenantResolver;
import lombok.extern.slf4j.Slf4j;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;

@RequestScoped
@PersistenceUnitExtension
@Slf4j
public class CustomTenantResolver implements TenantResolver {

    @PostConstruct
    private void postConstruct() {
        log.info( "CustomTenantResolver constructed!" );
    }

    @Override
    public String getDefaultTenantId() {
        log.info( "getDefaultTenantId" );
        return "public";
    }

    @Override
    public String resolveTenantId() {
        log.info( "resolveTenantId" );
        String schema = TenantContext.getCurrentTenant();

        if ( schema == null ) {
            return "public";
        }
        log.info( "current schema {}", schema );
        return schema;
    }
}

```

Only if needed my application.properties
```
# datasource settings
quarkus.http.port=8080
quarkus.hibernate-orm.multitenant=SCHEMA
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/db
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=useraa
quarkus.datasource.password=myPassword
quarkus.datasource.jdbc.initial-size=2
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=8
quarkus.transaction-manager.default-transaction-timeout=300S
quarkus.flyway.migrate-at-start=false
quarkus.flyway.schemas=public
quarkus.package.type=uber-jar

# Logging
quarkus.log.level=INFO
quarkus.log.min-level=INFO
#%dev.quarkus.log.level=DEBUG
#%dev.quarkus.log.min-level=DEBUG

# Rest-api settings
portal-api/mp-rest/url=http://localhost:8180/
portal-api/mp-rest/scope=javax.inject.Singleton

org.eclipse.microprofile.rest.client.propagateHeaders=Authorization


# Rest-api settings
# OIDC Configuration
quarkus.oidc.auth-server-url=http://localhost:8280/auth/realms/software
quarkus.oidc.token.issuer=https://mywebsite.at/auth/realms/turniersoftware
quarkus.oidc.client-id=quarkus-pea
quarkus.oidc.credentials.secret=mySecretCode
# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=false
# Dev variables
#quarkus.log.level=INFO
#quarkus.log.min-level=DEBUG
#quarkus.log.category."io.undertow".level=DEBUG
```

**//SOLUTION found by nmvr2600:**

Add `@default` annotation to your class from the package: `import javax.enterprise.inject.Default;`
```
import javax.enterprise.context.RequestScoped;
import javax.enterprise.inject.Default;

@Default
@RequestScoped
@PersistenceUnitExtension
@Slf4j
public class CustomTenantResolver implements TenantResolver {
...
```

### Expected behavior

No error message on startup.

### Actual behavior

I get the no instance of tenantResolver was found exception.

### Output of `java -version`

11

### Quarkus version or git rev

2.4.1.Final

**Comment by yrodiere** [comment]
Thanks for reporting.

Could you please provide the full stacktrace, and ideally a small reproducer project?

**Comment by Paul6552** [comment]
Following the stacktrace. Tomorrow I will try to build an reproducer.

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-11-08 14:45:43,200 INFO  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002200: Adding class resource at.tanzauswertung.meisterschaft.endpoint.LoginEndpoint from Application class at.tanzauswertung.shared.App_Subclass
2021-11-08 14:45:43,200 INFO  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002200: Adding class resource at.tanzauswertung.dance.endpoint.DanceEndpoint from Application class at.tanzauswertung.shared.App_Subclass
2021-11-08 14:45:43,200 INFO  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002200: Adding class resource at.tanzauswertung.client.endpoint.ClientEndpoint from Application class at.tanzauswertung.shared.App_Subclass
2021-11-08 14:45:43,200 INFO  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002200: Adding class resource at.tanzauswertung.portal.endpoint.PortalDanceEndpoint from Application class at.tanzauswertung.shared.App_Subclass
2021-11-08 14:45:43,200 INFO  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002200: Adding class resource at.tanzauswertung.report.endpoint.ReportEndpoint from Application class at.tanzauswertung.shared.App_Subclass
2021-11-08 14:45:43,200 INFO  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002200: Adding class resource at.tanzauswertung.beamerpresenter.endpoint.BeamerPresenterEndpoint from Application class at.tanzauswertung.shared.App_Subclass
2021-11-08 14:45:43,200 INFO  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002200: Adding class resource at.tanzauswertung.portal.endpoint.PortalEndpoint from Application class at.tanzauswertung.shared.App_Subclass
2021-11-08 14:45:43,200 INFO  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002200: Adding class resource at.tanzauswertung.portal.endpoint.PortalMeisterschaftEndpoint from Application class at.tanzauswertung.shared.App_Subclass
2021-11-08 14:45:43,200 INFO  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002205: Adding provider class at.tanzauswertung.shared.provider.JacksonJavaTimeMappingProvider from Application class at.tanzauswertung.shared.App_Subclass
2021-11-08 14:45:43,200 INFO  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002205: Adding provider class at.tanzauswertung.shared.filter.RestRequestFilter from Application class at.tanzauswertung.shared.App_Subclass
2021-11-08 14:45:43,200 INFO  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002205: Adding provider class at.tanzauswertung.shared.filter.RestResponseFilter from Application class at.tanzauswertung.shared.App_Subclass
2021-11-08 14:45:43,202 WARN  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002155: Provider class at.tanzauswertung.shared.provider.JacksonJavaTimeMappingProvider is already registered.  2nd registration is being ignored.
2021-11-08 14:45:43,202 WARN  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002155: Provider class at.tanzauswertung.shared.filter.RestRequestFilter is already registered.  2nd registration is being ignored.
2021-11-08 14:45:43,202 WARN  [org.jbo.res.res.i18n] (Quarkus Main Thread) RESTEASY002155: Provider class at.tanzauswertung.shared.filter.RestResponseFilter is already registered.  2nd registration is being ignored.
2021-11-08 14:45:43,239 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread: <default>) HHH000342: Could not obtain connection to query metadata: java.lang.IllegalStateException: No instance of TenantResolver was found for persistence unit <default>. You need to create an implementation for this interface to allow resolving the current tenant identifier.
	at io.quarkus.hibernate.orm.runtime.tenant.HibernateMultiTenantConnectionProvider.tenantResolver(HibernateMultiTenantConnectionProvider.java:118)
	at io.quarkus.hibernate.orm.runtime.tenant.HibernateMultiTenantConnectionProvider.getAnyConnectionProvider(HibernateMultiTenantConnectionProvider.java:41)
	at org.hibernate.engine.jdbc.connections.spi.AbstractMultiTenantConnectionProvider.getAnyConnection(AbstractMultiTenantConnectionProvider.java:26)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$MultiTenantConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:208)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:265)
	at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:69)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:72)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:67)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:149)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:58)
	at java.base/java.lang.Thread.run(Thread.java:832)

2021-11-08 14:45:43,296 INFO  [io.quarkus] (Quarkus Main Thread) pea-backend 2.0.0-SNAPSHOT on JVM (powered by Quarkus 2.4.1.Final) started in 0.943s. Listening on: http://localhost:8080
2021-11-08 14:45:43,296 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-11-08 14:45:43,296 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, keycloak-authorization, narayana-jta, oidc, rest-client, resteasy, resteasy-jackson, security, servlet, smallrye-context-propagation, vertx]
2021-11-08 14:45:43,297 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-2) Live reload total time: 1.213s 
```

**Comment by Paul6552** [comment]
Sry, in the last days i tried to make a reproducer, but have many troubles to get it working with an schema database online. I hope the stacktrace can help or another person has also the same error. 

In the meantime i am running quarkus 2.4.1 succesfully in production. This error is only at startup, everything else is working correctly

**Comment by yrodiere** [comment]
I see in your stacktrace that you have several classes in package `at.tanzauswertung.shared`.

Is your tenant resolver in a shared JAR? If so, are you sure beans from that JAR are correctly discovered (see how beans are discovered in dependencies [here](https://quarkus.io/guides/cdi-reference#bean_discovery))? If not, you might simply be missing a Jandex index for this JAR: https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index.

It's strange that bean resolution would work at runtime, though...

**Comment by Paul6552** [comment]
Sadly my tenant resolver is not in the shared JAR.

**Comment by nvrs** [comment]
For what it's worth, we are seeing the same issue and -- as far as I can tell by looking at the posted configuration -- one thing we have in common with @Paul6552 is that we are using Flyway and we have set too
`quarkus.flyway.migrate-at-start=false
`

In our case the error gets printed in our case just before flyway migration kicks in.

**Comment by stefanorg** [comment]
Hi, same problem here.
After changing `@PersistenceUnit` with `@PersistenceUnitExtension` in the resolver class i get the same error.
I think because the `io/quarkus/hibernate/orm/runtime/tenant/HibernateMultiTenantConnectionProvider.java` try to resolve the `PersistenceUnitLiteral` on row number `109`

```
 private static InstanceHandle<TenantResolver> tenantResolver(String persistenceUnitName) {
        InstanceHandle<TenantResolver> resolverInstance;
        if (PersistenceUnitUtil.isDefaultPersistenceUnit(persistenceUnitName)) {
            resolverInstance = Arc.container().instance(TenantResolver.class, Default.Literal.INSTANCE);
        } else {
            resolverInstance = Arc.container().instance(TenantResolver.class,
                    new PersistenceUnitLiteral(persistenceUnitName));
        }
        if (!resolverInstance.isAvailable()) {
            throw new IllegalStateException(String.format(Locale.ROOT,
                    "No instance of %1$s was found for persistence unit %2$s. "
                            + "You need to create an implementation for this interface to allow resolving the current tenant identifier.",
                    TenantResolver.class.getSimpleName(), persistenceUnitName));
        }
        return resolverInstance;
    }
```

and there is no annotation `@PersistenceUnit` but is `@PersistenceUnitExtension`

**Comment by stefanorg** [comment]
this is my trace

```
2021-11-19 09:34:28,976 WARN  [org.hiber.engin.jdbc.env.inter.JdbcEnvironmentInitiator:133] (JPA Startup Thread: argologdb) [{}] HHH000342: Could not obtain connection to query metadata: java.lang.IllegalStateException: No instance of TenantResolver was found for persistence unit argologdb. You need to create an implementation for this interface to allow resolving the current tenant identifier.
        at io.quarkus.hibernate.orm.runtime.tenant.HibernateMultiTenantConnectionProvider.tenantResolver(HibernateMultiTenantConnectionProvider.java:118)
        at io.quarkus.hibernate.orm.runtime.tenant.HibernateMultiTenantConnectionProvider.getAnyConnectionProvider(HibernateMultiTenantConnectionProvider.java:41)
        at org.hibernate.engine.jdbc.connections.spi.AbstractMultiTenantConnectionProvider.getAnyConnection(AbstractMultiTenantConnectionProvider.java:26)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$MultiTenantConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:208)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
        at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:265)
        at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:69)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:72)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:67)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:149)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:58)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by nmvr2600** [comment]
+1 I have the same issus. When I removed @PersistenceUnitExtension, it can works. I found the hibernate-orm-multi-tenancy-quickstart code without this annotation.

**Comment by yrodiere** [comment]
@nmvr2600 Can you provide a reproducer, please?

**Comment by nmvr2600** [comment]
> 

I found another solution, just  add @Default annotation. Because the code report this error get instance like below.
`        InstanceHandle<TenantResolver> resolverInstance;
        if (PersistenceUnitUtil.isDefaultPersistenceUnit(persistenceUnitName)) {
            resolverInstance = Arc.container().instance(TenantResolver.class, Default.Literal.INSTANCE);
        } else {
            resolverInstance = Arc.container().instance(TenantResolver.class,
                    new PersistenceUnitLiteral(persistenceUnitName));
        }`

**Comment by Paul6552** [comment]
@nmvr2600 sadly I do not find the correct place to write **@default** 

I already set the function **getDefaultTenantId()**

```
@Override
public String getDefaultTenantId() {
    log.info( "getDefaultTenantId" );
    return "public";
}
```

Where do I have to write **@default**?

**Comment by nmvr2600** [comment]
@Paul6552  put it on the class
![image](https://user-images.githubusercontent.com/28606/147187272-7b94e39d-bccc-46a7-a2f0-ac1ab9657d85.png)

**Comment by Paul6552** [comment]
@nmvr2600 thanks, it is working

@yrodiere Maybe interesting for you too

:-)

**Comment by gsmet** [comment]
Can one of you try to add ˋ@Unremovable` instead of ˋ@Default`? I wonder if the bean is removed by ArC.

**Comment by gsmet** [comment]
Scrap that. There is either a doc issue or a code issue but there is a mismatch between the two.

**Comment by gsmet** [comment]
Fix is coming here: https://github.com/quarkusio/quarkus/pull/22502 .

Thanks for all the pointers you all, it put me on the right track!
