### ISSUE TITLE
Resteasy JavaTimeModule not working properly

### ISSUE THREAD

**Issue by mzellho** [quarkusio/quarkus#21397]
### Describe the bug

When adding e.g. java.time.OffsetDateTime as a @QueryParam to an endpoint, Quarkus fails to startup (RESTEASY003875), despite stating "To improve user experience, Quarkus registers the three Jackson Java 8 modules so you don’t need to do it manually." in the [docs](https://quarkus.io/guides/rest-json).

I created a [plain project for reproduction](https://github.com/mzellho/quarkus-java8time-issue) and added 

```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy-jackson</artifactId>
</dependency>


```

and edited the generated `hello` endoint to `public String hello(@QueryParam("date") OffsetDateTime date)`

In my other project, I was able to verify that `JacksonProcessor` got invoked and raised no error when registering `MODULES_NAMES_TO_AUTO_REGISTER`.

I also tried to implement a `ObjectMapperCustomizer` registering `JavaTimeModule` myself, but with no luck.

### Expected behavior

JavaTimeModule enables to use java.time.* in @QueryParam

### Actual behavior

When running `mvn quarkus:dev`, Quarkus fails to boot:

```
2021-11-12 10:31:47,215 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
        at java.base/java.lang.Class.newInstance(Class.java:642)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:318)
        ... 17 more
Caused by: java.lang.RuntimeException: RESTEASY003875: Unable to find a constructor that takes a String param or a valueOf() or fromString() method for javax.ws.rs.QueryParam("date") on public java.lang.String foo.bar.GreetingResource.hello(java.time.OffsetDateTime) for basetype: java.time.OffsetDateTime
        at org.jboss.resteasy.core.StringParameterInjector.initialize(StringParameterInjector.java:458)
        at org.jboss.resteasy.core.StringParameterInjector.<init>(StringParameterInjector.java:401)
        at org.jboss.resteasy.core.QueryParamInjector.<init>(QueryParamInjector.java:31)
        at org.jboss.resteasy.core.InjectorFactoryImpl.createParameterExtractor0(InjectorFactoryImpl.java:100)
        at org.jboss.resteasy.core.InjectorFactoryImpl.lambda$createParameterExtractor$0(InjectorFactoryImpl.java:91)
        at org.jboss.resteasy.core.InjectorFactoryImpl$OptionalInjections.lambda$wrap$8(InjectorFactoryImpl.java:309)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at org.jboss.resteasy.core.InjectorFactoryImpl$OptionalInjections.wrap(InjectorFactoryImpl.java:309)
        at org.jboss.resteasy.core.InjectorFactoryImpl.createParameterExtractor(InjectorFactoryImpl.java:91)
        at org.jboss.resteasy.core.MethodInjectorImpl.<init>(MethodInjectorImpl.java:45)
        at org.jboss.resteasy.core.InjectorFactoryImpl.createMethodInjector(InjectorFactoryImpl.java:85)
        at org.jboss.resteasy.core.ResourceMethodInvoker.<init>(ResourceMethodInvoker.java:136)
        at org.jboss.resteasy.core.ResourceMethodRegistry.processMethod(ResourceMethodRegistry.java:381)
        at org.jboss.resteasy.core.ResourceMethodRegistry.register(ResourceMethodRegistry.java:308)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:259)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:227)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:208)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:192)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:175)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:87)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.registerResources(ResteasyDeploymentImpl.java:518)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.registration(ResteasyDeploymentImpl.java:475)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:164)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:121)
        at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.staticInit(ResteasyStandaloneRecorder.java:36)
        at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit345281060.deploy_0(ResteasyStandaloneBuildStep$staticInit345281060.zig:884)
        at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit345281060.deploy(ResteasyStandaloneBuildStep$staticInit345281060.zig:40)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:287)
        ... 17 more
```

### How to Reproduce?

Clone the sample repo

### Output of `uname -a` or `ver`

Linux DSAPA210210 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "16" 2021-03-16 OpenJDK Runtime Environment AdoptOpenJDK (build 16+36) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)

### Quarkus version or git rev

2.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by geoand** [comment]
A JAX-RS `@QueryParam` is not handled by Jackson (or any JSON serialization framework).

If you want this feature, I suggest opening an issue on the RESTEasy issue tracker.

**Comment by mzellho** [comment]
Hi and thanks for your reply, @geoand. I don't think we need a feature request at Resteasy since the feature is there already (JavaTimeModule). Also, this module gets registered in Quarkus via L69, L76, L226 of https://github.com/quarkusio/quarkus/blob/main/extensions/jackson/deployment/src/main/java/io/quarkus/jackson/deployment/JacksonProcessor.java and is also documented in [Quarkus docs](https://quarkus.io/guides/rest-json#creating-the-maven-project) (next to the (i) icon it states "To improve user experience, Quarkus registers the three Jackson Java 8 modules so you don’t need to do it manually.").

Is something out of date here? Or do I simply misread the docs / code?

Thanks!!

**Comment by geoand** [comment]
Hi,

As I mentioned above, the deserialization of the value of a `@QueryParam` has **nothing** to do with Jackson or any other JSON serialization / deserialization framework (although I understand why one would think it does).

**Comment by mzellho** [comment]
@geoand, ah, I think I understand, no JSON here...my bad.
I'll have a look at `ParamConverter` instead.
Thank you and sorry for the bug request.

**Comment by geoand** [comment]
You are welcome!
