### ISSUE TITLE
Error with ConfigMapping using Maps, Nested Groups and Optional 

### ISSUE THREAD

**Issue by rudiger3d** [quarkusio/quarkus#21407]
### Describe the bug

I'm seeing an error when mapping configuration to objects using a combination of nested groups (https://quarkus.io/guides/config-mappings#nested-groups) and maps (https://quarkus.io/guides/config-mappings#maps) that I think is a bug.

Specifically I'm specifying that a nested group should be Optional **while** specifying ConfigMapping.NamingStrategy.VERBATIM in my ConfigMapping declaration.

Having:

```java
package org.acme.config;

import io.smallrye.config.ConfigMapping;
import io.smallrye.config.WithParentName;

import java.util.Map;
import java.util.Optional;

@ConfigMapping(prefix = "bugs", namingStrategy = ConfigMapping.NamingStrategy.VERBATIM)
public interface BugConfigMappingConfiguration {

    @WithParentName
    Map<String, ClientConfiguration> bugs();

    interface ClientConfiguration {
        boolean hereVerbatimWorks();
        Optional<CiscoProperties> cisco();
    }

    interface CiscoProperties {
        String feed();
        String customerId();
        String scriptSelector();
    }
}
```

and application.properties:

```
bugs.KEY1.hereVerbatimWorks=true
bugs.KEY1.cisco.feed=100103
bugs.KEY1.cisco.customerId=36936471
bugs.KEY1.cisco.scriptSelector=RoadRunner_Task1_AAR01
```

The app fails to start because

```
2021-11-12 13:36:35,641 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.util.NoSuchElementException: SRCFG00014: The config property bugs.KEY1.cisco.customer-id is required but it could not be found in any config source
	java.util.NoSuchElementException: SRCFG00014: The config property bugs.KEY1.cisco.script-selector is required but it could not be found in any config source
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:860)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:816)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:419)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:1389)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:42)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:436)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

That ConfigMapping.NamingStrategy.VERBATIM also works with Optional nested groups. 

### Actual behavior

When using Optional with nested groups the VERBATIM naming strategy is not honoured.

### How to Reproduce?

git clone https://github.com/quarkusio/quarkus-quickstarts/tree/main/config-quickstart
cd config-quickstart
Add BugConfigMappingConfiguration.java and the properties from the "Describe the error" section to application.properties
Start the application

### Output of `uname -a` or `ver`

Darwin everythingsruined 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17" 2021-09-14 OpenJDK Runtime Environment Temurin-17+35 (build 17+35) OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

### Additional information

I use the following additional decency:

```
    <dependency>
      <groupId>io.smallrye.config</groupId>
      <artifactId>smallrye-config-core</artifactId>
      <version>2.6.0</version>
    </dependency>
```

because it fixes an issue that I previously reported in (https://github.com/quarkusio/quarkus/issues/20728) and which is fixed in 2.6.0

**Comment by radcortez** [comment]
I'll have a look.

**Comment by radcortez** [comment]
For a workaround, you can place a `@ConfigMapping(namingStrategy = ConfigMapping.NamingStrategy.VERBATIM)` in the 
`ClientConfiguration`.

**Comment by radcortez** [comment]
Fixed in SR Config. Will require SR Config 2.6.1.
