### ISSUE TITLE
Quarkus application cannot find codec for MongoDB Clients

### ISSUE THREAD

**Issue by dgarcia-saaskun** [quarkusio/quarkus#21414]
### Describe the bug

Running a quarkus application with MongoDB (Panache) shows warnings on the startup,

It is a rest service application that loads data from MongoDB database hosted on Atlas MongoDB.

The Warnings logged are similar:

```
WARN  [io.qua.mon.run.MongoClients] (main) Unable to load the property codec provider class org.bson.codecs.pojo.EnumPropertyCodecProvider: java.lang.NoSuchMethodException: org.bson.codecs.pojo.EnumPropertyCodecProvider.<init>()
    at java.base/java.lang.Class.getConstructor0(Class.java:3349)
    at java.base/java.lang.Class.getConstructor(Class.java:2151)
    at io.quarkus.mongodb.runtime.MongoClients.getPropertyCodecProviders(MongoClients.java:440)
    at io.quarkus.mongodb.runtime.MongoClients.configureCodecRegistry(MongoClients.java:332)
    at io.quarkus.mongodb.runtime.MongoClients.createMongoConfiguration(MongoClients.java:255)
    at io.quarkus.mongodb.runtime.MongoClients.createReactiveMongoClient(MongoClients.java:115)
    at io.quarkus.mongodb.runtime.MongoClientRecorder.reactiveMongoClientSupplier(MongoClientRecorder.java:57)
    at io.quarkus.deployment.steps.MongoClientProcessor$generateClientBeans-1756432087.deploy_0(MongoClientProcessor$generateClientBeans-1756432087.zig:96)
    at io.quarkus.deployment.steps.MongoClientProcessor$generateClientBeans-1756432087.deploy(MongoClientProcessor$generateClientBeans-1756432087.zig:40)
    at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:666)
    at io.quarkus.runtime.Application.start(Application.java:101)
    at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
    at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```
Then in any operation to get data from the database, an StackOverflowError is generated showing cyclically this stacktrace:
```
...
    at org.bson.internal.LazyCodec.encode(LazyCodec.java:38)
    at org.bson.BsonDocumentWrapper.getUnwrapped(BsonDocumentWrapper.java:195)
    at org.bson.BsonDocumentWrapper.entrySet(BsonDocumentWrapper.java:165)
    at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:112)
    at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:42)
    at org.bson.codecs.BsonCodec.encode(BsonCodec.java:55)
    at org.bson.codecs.BsonCodec.encode(BsonCodec.java:33)
    at org.bson.internal.LazyCodec.encode(LazyCodec.java:38)
    at org.bson.BsonDocumentWrapper.getUnwrapped(BsonDocumentWrapper.java:195)
    at org.bson.BsonDocumentWrapper.entrySet(BsonDocumentWrapper.java:165)
    at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:112)
    at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:42)
 ...
```
Dependencies configured on the POM:

```
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-mongodb-panache</artifactId>
    </dependency>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-rest-client</artifactId>
    </dependency>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
    </dependency>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-resteasy-jackson</artifactId>
    </dependency>
```

Relevant notes:

- uber-jar artifact
- JavaBeans defined on a third project with the proper Jandex Index
- Running on JVM
- Same behaviour on Linux (Detected on our Azure App Servervices)

### Expected behavior

- No warnings should be shown
- Calls to service return the data

### Actual behavior

- Always the warnings are showed on the 

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22000.318]

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by dgarcia-saaskun** [comment]
Trying to generate a project to reproduce the issue. I see my mates added the org.mongodb to the jandex index.

```
quarkus.index-dependency.bson.group-id=org.mongodb
quarkus.index-dependency.bson.artifact-id=bson
```

I removed the configuration from the application.properties, the issue has gone. But the compilation warning appears.

The compilation process shows a warning that the class is not on the index:
```
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - org.bson.types.ObjectId
```

**Comment by loicmathieu** [comment]
Thanks  for the information. Indexing the Bson library was the cause then.
Can you answer your question on stackoverflow to help people how might have the same issue ?

The remaining warning log is normal, I should try to do something about it some day ...
