### ISSUE TITLE
Vertx thread blocked at startup

### ISSUE THREAD

**Issue by Xendar** [quarkusio/quarkus#21447]
### Describe the bug

When starting the dev mode on my machine on a fresh Quarkus project (for instance, just downloading a new app with no extensions from _code with quarkus_), I am getting some thread blocked at dev mode startup time. It does the same when starting the Jar file.
It does not prevent the app to start properly, but it delays the startup time of dozens of seconds.

### Expected behavior

The application should start (almost) straight away without any thread blocked.being 

### Actual behavior

Here is the full stack trace:

```
$ ./mvnw compile quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:2.4.2.Final:generate-code (default) @ code-with-quarkus ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ code-with-quarkus ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\Users\vleon\Downloads\code-with-quarkus\target\classes
[INFO]
[INFO] --- quarkus-maven-plugin:2.4.2.Final:dev (default-cli) @ code-with-quarkus ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources) @ code-with-quarkus
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\vleon\Downloads\code-with-quarkus\src\test\resources
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile) @ code-with-quarkus
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to C:\Users\vleon\Downloads\code-with-quarkus\target\test-classes
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-11-14 13:51:17,501 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-23,5,main] has been blocked for 3690 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:58)
        at io.vertx.core.net.SocketAddress.inetSocketAddress(SocketAddress.java:45)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:150)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:155)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:998)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:940)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.DeploymentManager$$Lambda$687/0x0000000800511440.handle(Unknown Source)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$688/0x0000000800540040.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)


2021-11-14 13:51:17,525 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-18,5,main] has been blocked for 3691 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at java.base@11.0.10/java.net.NetworkInterface.getAll(Native Method)
        at java.base@11.0.10/java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:359)
        at io.netty.util.NetUtilInitializations.determineLoopback(NetUtilInitializations.java:73)
        at io.netty.util.NetUtil.<clinit>(NetUtil.java:144)
        at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:58)
        at io.vertx.core.net.SocketAddress.inetSocketAddress(SocketAddress.java:45)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:150)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:155)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:998)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:940)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.DeploymentManager$$Lambda$687/0x0000000800511440.handle(Unknown Source)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$688/0x0000000800540040.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)


2021-11-14 13:51:17,542 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 3696 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:58)
        at io.vertx.core.net.SocketAddress.inetSocketAddress(SocketAddress.java:45)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:150)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:155)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:998)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:940)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.DeploymentManager$$Lambda$687/0x0000000800511440.handle(Unknown Source)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$688/0x0000000800540040.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)


2021-11-14 13:51:19,505 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-18,5,main] has been blocked for 5692 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at java.base@11.0.10/java.net.NetworkInterface.getAll(Native Method)
        at java.base@11.0.10/java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:359)
        at io.netty.util.NetUtilInitializations.determineLoopback(NetUtilInitializations.java:73)
        at io.netty.util.NetUtil.<clinit>(NetUtil.java:144)
        at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:58)
        at io.vertx.core.net.SocketAddress.inetSocketAddress(SocketAddress.java:45)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:150)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:155)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:998)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:940)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.DeploymentManager$$Lambda$687/0x0000000800511440.handle(Unknown Source)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$688/0x0000000800540040.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)


2021-11-14 13:51:19,517 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 5696 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:58)
        at io.vertx.core.net.SocketAddress.inetSocketAddress(SocketAddress.java:45)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:150)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:155)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:998)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:940)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.DeploymentManager$$Lambda$687/0x0000000800511440.handle(Unknown Source)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$688/0x0000000800540040.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)


2021-11-14 13:51:21,506 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-18,5,main] has been blocked for 7692 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at java.base@11.0.10/java.net.NetworkInterface.getAll(Native Method)
        at java.base@11.0.10/java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:359)
        at io.netty.util.NetUtilInitializations.determineLoopback(NetUtilInitializations.java:73)
        at io.netty.util.NetUtil.<clinit>(NetUtil.java:144)
        at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:58)
        at io.vertx.core.net.SocketAddress.inetSocketAddress(SocketAddress.java:45)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:150)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:155)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:998)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:940)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.DeploymentManager$$Lambda$687/0x0000000800511440.handle(Unknown Source)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$688/0x0000000800540040.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)


2021-11-14 13:51:21,519 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 7696 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:58)
        at io.vertx.core.net.SocketAddress.inetSocketAddress(SocketAddress.java:45)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:150)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:155)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:998)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:940)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.DeploymentManager$$Lambda$687/0x0000000800511440.handle(Unknown Source)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$688/0x0000000800540040.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)


2021-11-14 13:51:23,506 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-18,5,main] has been blocked for 9692 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at java.base@11.0.10/java.net.NetworkInterface.getAll(Native Method)
        at java.base@11.0.10/java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:359)
        at io.netty.util.NetUtilInitializations.determineLoopback(NetUtilInitializations.java:73)
        at io.netty.util.NetUtil.<clinit>(NetUtil.java:144)
        at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:58)
        at io.vertx.core.net.SocketAddress.inetSocketAddress(SocketAddress.java:45)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:150)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:155)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:998)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:940)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.DeploymentManager$$Lambda$687/0x0000000800511440.handle(Unknown Source)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$688/0x0000000800540040.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)


2021-11-14 13:51:23,519 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 9696 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:58)
        at io.vertx.core.net.SocketAddress.inetSocketAddress(SocketAddress.java:45)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:150)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:155)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:998)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:940)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.DeploymentManager$$Lambda$687/0x0000000800511440.handle(Unknown Source)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$688/0x0000000800540040.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.10/java.lang.Thread.run(Thread.java:834)


2021-11-14 13:51:24,434 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.4.2.Final) started in 47.365s. Listening on: http://localhost:8080
2021-11-14 13:51:24,439 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-11-14 13:51:24,442 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, smallrye-context-propagation, vertx]
```

### How to Reproduce?

I just downloaded the zip from code with Quarkus, unzipped, and launched the Maven command (n.b., same issue with Gradle).
![image](https://user-images.githubusercontent.com/24693144/141681999-8de10b89-460e-4c31-a212-f238646932f9.png)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18363.1854]

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 LTS OpenJDK Runtime Environment 18.9 (build 11.0.10+9-LTS) OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9-LTS, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

### Additional information

I would tend to think that the issue is somehow linked to my machine, as my googling of this issue has been unsuccessful, but I have no idea on how to investigate this...

**Comment by stuartwdouglas** [comment]
This looks like it is something network (DNS?) related on your machine, it looks like this bit is slow:

```
        at java.base@11.0.10/java.net.NetworkInterface.getAll(Native Method)
        at java.base@11.0.10/java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:359)
        at io.netty.util.NetUtilInitializations.determineLoopback(NetUtilInitializations.java:73)
```

Unfortunately this is probably something Windows specific rather than something Quarkus related, so I am not really sure what the solution is here.

**Comment by Xendar** [comment]
> This looks like it is something network (DNS?) related on your machine, it looks like this bit is slow:
> 
> ```
>         at java.base@11.0.10/java.net.NetworkInterface.getAll(Native Method)
>         at java.base@11.0.10/java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:359)
>         at io.netty.util.NetUtilInitializations.determineLoopback(NetUtilInitializations.java:73)
> ```
> 
> Unfortunately this is probably something Windows specific rather than something Quarkus related, so I am not really sure what the solution is here.

You got me digging into my network setup, and I noticed that I had ~20 network adapters created by VirtualBox for some reason I can't explain.
After doing some cleanup in there, the app starts more quickly (still taking ~10 seconds) but the exceptions are gone! The startup time is probably linked to something on my machine, so I guess I can close the ticket.
Thanks @stuartwdouglas for having a look!

**Comment by sebastienmoreno** [comment]
@sortadorky did you manage to solve your problem? I experience the same behavior in a Kubernetes environment.

**Comment by raweber42** [comment]
Is this fixed with a new Quarkus version? Bumping from 2.6 to 2.16.7 seems to have fixed it for me.

**Comment by brunoborges** [comment]
Also facing this issue.

**Comment by brunoborges** [comment]
I noticed the same Quarkus app, when running in a container with 0.3 CPU limit on a MacBook M1, I do **not** face this issue. But when I run on my MacBook Intel, I do get the error.

The container image on M1 is a linux/arm64 image, while the image used on MacBook intel is a regular x64 image.

**Comment by Hassaballah101** [comment]
Same here.
