### ISSUE TITLE
Allow injecting default value of quarkus.http.port

### ISSUE THREAD

**Issue by pavolloffay** [quarkusio/quarkus#2146]
When `quarkus.http.port` is not defined in `application.properties` and the value is injected the  deployment fails. It would be more friendly if quarkus injected default values of http port (and probably other core configuration properties).

```java
  @ConfigProperty(name = "quarkus.http.port")
  private int port;
```

```
javax.enterprise.inject.spi.DeploymentException: No config value of type [int] exists for: quarkus.http.port
	at io.quarkus.arc.runtime.ConfigDeploymentTemplate.validateConfigProperties(ConfigDeploymentTemplate.java:48)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties7.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:99)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:119)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:236)
	at io.quarkus.test.junit.QuarkusTestExtension.createTestInstance(QuarkusTestExtension.java:301)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeTestInstanceFactory(ClassTestDescriptor.java:299)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:289)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:281)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateAndPostProcessTestInstance(ClassTestDescriptor.java:269)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstancesProvider$2(ClassTestDescriptor.java:259)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstancesProvider$3(ClassTestDescriptor.java:263)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstancesProvider$4(ClassTestDescriptor.java:262)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:98)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:97)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
```

**Comment by mkouba** [comment]
I like the idea and TBH I thought that we already had an issue for this but I could not find any ;-).

**Comment by geoand** [comment]
This may be a misguided question @dmlloyd , but is there any reason we can't (or shouldn't) add Runtime config items to `META-INF/quarkus-default-config.properties`? That would allow for injection of properties like this issue proposes.

**Comment by dmlloyd** [comment]
There is a configuration source which provides default values for build and run time Quarkus config values.  It doesn't use a properties file, because sometimes the default values apply to e.g. any key matching `quarkus.foo.*.bar.*`, so obviously it would be impossible to make an exhaustive list.

I'm not sure why the value is appearing to not be found by Arc though.  These properties should be found if their corresponding Quarkus run time module was present during build.

**Comment by geoand** [comment]
@dmlloyd Ah yes, I see generated `RunTimeDefaultConfigSource`. I'll take a quick look and see if I can spot why it doesn't provide the value as expected.

**Comment by mkouba** [comment]
@dmlloyd It's not a problem of ArC. Just do `ConfigProvider.getConfig().getPropertyNames()` in the app code.

**Comment by dmlloyd** [comment]
As I said the properties will not show up under `getPropertyNames()`.  But `io.quarkus.arc.runtime.ConfigDeploymentTemplate#validateConfigProperties` does not seem to use that?

**Comment by mkouba** [comment]
It is using `ConfigProvider.getConfig().getOptionalValue()`.

**Comment by geoand** [comment]
I think I found the solution:

in `ConfigDeploymentTemplate` we need to replace `ConfigProvider.getConfig();`   with `Config config = ConfigProviderResolver.instance().getConfig()`.

Does that make sense @mkouba, @dmlloyd ? If so, I can open a PR

**Comment by dmlloyd** [comment]
Interesting, so it looks like our problems with class loaders and config registration are not completely over yet.  Go head with the PR and I'll make a note to review this.

**Comment by geoand** [comment]
@dmlloyd Let me make sure all the tests pass locally before opening the PR.

**Comment by mkouba** [comment]
Hm, now I rember that I send a PR with a hack to be able to validate `@ConfigProperty` injection points at runtime : https://github.com/quarkusio/quarkus/pull/1568

**Comment by mkouba** [comment]
Anyway, `ConfigDeploymentTemplate` is just a part of the puzzle - [SmallRye ConfigProducer](https://github.com/smallrye/smallrye-config/blob/master/implementation/src/main/java/io/smallrye/config/inject/ConfigProducer.java#L43) is using `ConfigProvider.getConfig()` too.
