### ISSUE TITLE
ConstraintViolation - Reactive endpoint in RESTEasy reactive doesn't behave the same as a blocking endpoint

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#21492]
### Describe the bug

When using RESTEasy reactive, code which throws `ConstraintViolationException` behaves differently whether or not the jax-rs endpoint is a reactive endpoint or not.

### Expected behavior

I would expect that any downstream code which throws `ConstraintViolationException` to be interpreted by RESTEasy reactive and handled appropriately, returning an http `400` status.

### Actual behavior

When using reactive endpoints which throw `ConstraintViolationException` somewhere in the reactive pipeline, RESTEasy reactive instead errors out with a `500` and a stack trace:

```shell
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-11) HTTP Request to /api/fruits/reactiveNotWorking failed, error id: 098981a0-af22-4772-9914-911b8910a7b1-1: javax.validation.ConstraintViolationException: name: must not be empty
	at org.acme.ExampleService.validateFruit(ExampleService.java:19)
	at org.acme.ExampleService_ClientProxy.validateFruit(ExampleService_ClientProxy.zig:205)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:50)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:90)
	at org.jboss.resteasy.reactive.server.handlers.UniResponseHandler.handle(UniResponseHandler.java:17)
	at org.jboss.resteasy.reactive.server.handlers.UniResponseHandler.handle(UniResponseHandler.java:8)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:72)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:69)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-11) Request failed: javax.validation.ConstraintViolationException: name: must not be empty
	at org.acme.ExampleService.validateFruit(ExampleService.java:19)
	at org.acme.ExampleService_ClientProxy.validateFruit(ExampleService_ClientProxy.zig:205)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:50)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:90)
	at org.jboss.resteasy.reactive.server.handlers.UniResponseHandler.handle(UniResponseHandler.java:17)
	at org.jboss.resteasy.reactive.server.handlers.UniResponseHandler.handle(UniResponseHandler.java:8)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:72)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:69)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

See the attached sample project which has unit tests that showcase this behavior.
[resteasy-reactive-behavior.zip](https://github.com/quarkusio/quarkus/files/7548814/resteasy-reactive-behavior.zip)

You can see from the `ExampleResource` class

```java
@POST
@Path("/blocking")
@Consumes(APPLICATION_JSON)
public Fruit addFruitBlocking(@NotNull Fruit fruit) {
    return this.exampleService.validateFruit(fruit);
}

@POST
@Path("/reactiveNotWorking")
@Consumes(APPLICATION_JSON)
public Uni<Fruit> addFruitReactiveNotWorkingCorrectly(@NotNull Fruit fruit) {
    return Uni.createFrom().item(fruit)
      .map(this.exampleService::validateFruit);
}

@POST
@Path("/reactiveWorking")
@Consumes(APPLICATION_JSON)
public Uni<Fruit> addFruitReactive(@NotNull Fruit fruit) {
    return Uni.createFrom().item(fruit)
      .map(this.exampleService::validateFruit)
      .onFailure(ConstraintViolationException.class)
      .transform(cve -> new ResteasyReactiveViolationException(((ConstraintViolationException) cve).getConstraintViolations()));
}
```

If on the reactive pipeline I add

```java
.onFailure(ConstraintViolationException.class)
.transform(cve -> new ResteasyReactiveViolationException(((ConstraintViolationException) cve).getConstraintViolations()));
```

which maps the `ConstraintViolationException` to a `ResteasyReactiveViolationException`, then everything works as expected.

See the `ExampleResourceTest` class for the unit tests

### Output of `uname -a` or `ver`

`Darwin edeandre-mac 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64`

### Output of `java -version`

```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

### GraalVM version (if different from Java)

```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)
OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)
```

### Quarkus version or git rev

`2.4.2.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by geoand** [comment]
I looked into this and to be honest, this is expected.

The reason you got HTTP 400 from your `addFruitBlocking` is because you used `@NotNull`. If you remove it, then you will get HTTP 500.

The difference comes down to the fact that with the blocking call the [Validator](https://github.com/quarkusio/quarkus/blob/2.5.0.Final/extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/jaxrs/ResteasyReactiveEndPointValidationInterceptor.java) CDI interceptor catches the exception and turns it into a `ResteasyReactiveViolationException`.
When using a mutiny pipeline, that obviously can't happen.

**Comment by edeandrea** [comment]
But I'm not passing in a null object in my rest call. What does the `@NotNull` annotation have to do with anything? If I were to remove it from all the endpoints and then throw the `ConstraintViolationException` shouldn't the endpoint still return a `400`?

**Comment by geoand** [comment]
> But I'm not passing in a null object in my rest call. What does the `@NotNull` annotation have to do with anything? If I were to remove it from all the endpoints and then throw the `ConstraintViolationException` shouldn't the endpoint still return a `400`?
> 

The fact that you annotate with `@NotNull` means that the CDI interceptor I mentioned earlier is engaged.

> Shouldn't there be something in the mutiny pipeline that catches the `ConstraintViolationException` and transforms it to a `ResteasyReactiveViolationException`?

Nope. When you use reactive programming, there are some things you give up - such as the use of interceptors

**Comment by edeandrea** [comment]
So if I were to remove the `@NotNull` annotations, how would I transform the `500` to a `400` (essentially simulate the same behavior)? Is there some class somewhere I can reuse if I create a `@ServerExceptionMapper(ConstraintViolationException.class)`?

**Comment by geoand** [comment]
Using `@ServerExceptionMapper(ConstraintViolationException.class)` is the way to go.

**Comment by edeandrea** [comment]
But what do I return to get it to work just like it does if `@NotNull` is there?

```java
@ServerExceptionMapper(ConstraintViolationException.class)
public Response handleConstraintViolationException(ConstraintViolationException ex) {
    throw new ResteasyReactiveViolationException(ex.getConstraintViolations());
}
```

nor

```java
@ServerExceptionMapper(ConstraintViolationException.class)
public Response handleConstraintViolationException(ConstraintViolationException ex) {
    return Response.status(Status.BAD_REQUEST)
      .entity(new ResteasyReactiveViolationException(ex.getConstraintViolations()))
      .build();
}
```

works

**Comment by edeandrea** [comment]
This seems to work

```java
@ServerExceptionMapper(ConstraintViolationException.class)
public Response handleConstraintViolationException(ConstraintViolationException ex) {
    return new ResteasyReactiveViolationExceptionMapper().toResponse(new ResteasyReactiveViolationException(ex.getConstraintViolations()));
    }
```
