### ISSUE TITLE
Kotlin: ArcUndeclaredThrowableException since 1.13.x

### ISSUE THREAD

**Issue by Itoriem** [quarkusio/quarkus#21519]
### Describe the bug

Hello,
since Quarkus 1.13.x an ArcUndeclaredThrowableException is thrown when the method has no annotation @Throws(Exception::class) and an exception is thrown by called method.

My code is written in Kotlin and it works in Quarkus 1.12.x but not in 1.13.x.

Exception thrown :
```
2021-11-19 09:41:38,139 | ERROR | executor-thread-0 | [org.acme.quarkus.arcexception.config.exception.RestThrowableMapper:30] - Throwable unhandled (ArcUndeclaredThrowableException): Error invoking subclass method: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
        at ...
Caused by: org.acme.quarkus.arcexception.partner.exception.PartnerException: Error when retrieving partner status: : RESTEASY004655: Unable to invoke request: java.net.UnknownHostException: Hôte inconnu (unknownhost)
        at org.acme.quarkus.arcexception.partner.PartnerApiService.fetchAppStatus(PartnerApiService.kt:19)
        at ...
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: java.net.UnknownHostException: Hôte inconnu (unknownhost)
        at ...
Caused by: java.net.UnknownHostException: Hôte inconnu (unknownhost)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.in.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
        at ...
```

Thanks 

### How to Reproduce?

You can find a reproducer at https://github.com/Itoriem/quarkus-kotlin-ArcUndeclaredThrowableException

### Output of `java -version`

"11.0.8" 2020-07-14 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

### Quarkus version or git rev

1.13

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3

### Additional information

Discussed here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Kotlin.3A.20ArcUndeclaredThrowableException.20since.201.2E13.2Ex

**Comment by Ladicek** [comment]
CC @mkouba

**Comment by mschorsch** [comment]
I also saw the issue in 2.4.2, but only in dev mode.

**Comment by mschorsch** [comment]
Similar issue: #20357

**Comment by Itoriem** [comment]
Right, the problem is not present when the server is started with the 'prof' profile
