### ISSUE TITLE
java.lang.IllegalStateException: Response head already sent

### ISSUE THREAD

**Issue by micheljung** [quarkusio/quarkus#21548]
### Describe the bug

Similar issue as #19621

Doing a call to my `/graphql` with an existing (but not sure if expired) JWT token results in:

```
2021-11-18 19:38:38,409 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /graphql failed, error id: 2da873a8-9cd9-411e-9002-c6acce34c9c3-2: java.lang.IllegalStateException: Response head already sent
   at io.vertx.core.http.impl.Http1xServerResponse.checkHeadWritten(Http1xServerResponse.java:675)
   at io.vertx.core.http.impl.Http1xServerResponse.setStatusCode(Http1xServerResponse.java:144)
   at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:113)
   at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:71)
   at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handleWithIdentity(SmallRyeGraphQLAbstractHandler.java:66)
   at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:48)
   at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:23)
   at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
   at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
   at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
   at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
   at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
   at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
   at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
   at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   at java.lang.Thread.run(Thread.java:829)
   at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
   at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

### Expected behavior

Don't throw an exception

### Actual behavior

Throws an exception

### How to Reproduce?

I don't exactly know

### Quarkus version or git rev

2.4.0.Final

**Comment by geoand** [comment]
Any chance you can attach a reproducer?

**Comment by gsmet** [comment]
No reproducer, closing.
