### ISSUE TITLE
@ConsumeEvent can return `Uni<R>` if parameter is `T` but throws error for `Message<T>`

### ISSUE THREAD

**Issue by rgmz** [quarkusio/quarkus#21621]
### Describe the bug

The ["Using the event bus" documentation](https://quarkus.io/guides/reactive-event-bus#replying) has examples of methods annotated with `@ConsumesEvent` returning `void`, `R`, and  `Uni<R>`:

```java
@ConsumeEvent("greeting")
public String consume(String name) {
    return name.toUpperCase();
}

@ConsumeEvent("greeting")
public Uni<String> consume2(String name) {
    return Uni.createFrom().item(() -> name.toUpperCase()).emitOn(executor);
}
````

Based on the examples I'd expect the same to work for `Message<T>`, but attempting to consume an event from `EventBus.send` or `EventBus.request` results in a `NoSuchMethodError`. 

This occurs with both Kotlin and Java.

### Expected behavior

A method annotated with `@ConsumesEvent` can return either `void` or `Uni<R>` regardless of whether the parameter is `T` or `Message<T>`.

### Actual behavior

If the method parameter is `Message<T>`, the Vertx event bus only works if the return type is `void`.

```
2021-11-22 11:16:11,566 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-2) Uncaught exception received by Vert.x: java.lang.NoSuchMethodError: 'void org.acme.Example.onMessageUni(io.vertx.core.eventbus.Message)'
        at org.acme.Example_VertxInvoker_onMessage_a71f19d99a55f26778e6ec15e5768a5d955c7f96.invokeBean(WebhookImportService_VertxInvoker_onMessageUni_a71f19d99a55f26778e6ec15e5768a5d955c7f96.zig:68)
        at io.quarkus.vertx.runtime.EventConsumerInvoker.invoke(EventConsumerInvoker.java:28)
        at io.quarkus.vertx.runtime.VertxRecorder$3$1.handle(VertxRecorder.java:118)
        at io.quarkus.vertx.runtime.VertxRecorder$3$1.handle(VertxRecorder.java:95)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
        at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177)
        at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:169)
        at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:134)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:111)
        at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:105)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168)
        at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:56)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

**Code**

```kotlin
@ConsumeEvent("json")
fun onJsonObject(json: JsonObject) {
    println("[Void] Received JsonObject: ${json.encode()}")
}

@ConsumeEvent("jsonUni")
fun onJsonObjectUni(json: JsonObject): Uni<String> {
    println("[Uni] Received JsonObject: ${json.encode()}")
    return Uni.createFrom().item("JsonObject")
}

@ConsumeEvent("message")
fun onMessage(message: Message<JsonObject>) {
    println("[Void] Received message: [headers=${message.headers()}, body=${message.body().encode()}]")
}

@ConsumeEvent("messageUni")
fun onMessageUni(message: Message<JsonObject>): Uni<String> {
    println("[Uni] Received message: [headers=${message.headers()}, body=${message.body().encode()}]")
    return Uni.createFrom().item("Message")
}

// Elsewhere in the code
val json = JsonObject().put("name", "quarkus")
val options = DeliveryOptions().addHeader("version", "2.5.0.CR1")
bus.send("json", json)
bus.request<String>("jsonUni", json).awaitSuspending()
bus.send("message", json, options)
bus.request<String>("messageUni", json, options).awaitSuspending()
```

**Output**

```
2021-11-22 11:54:28,308 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-6) Uncaught exception received by Vert.x: java.lang.NoSuchMethodError: 'void org.acme.Example.onMessageUni(io.vertx.core.eventbus.Message)'
        at org.acme.Example_VertxInvoker_onMessageUni_17549bde5566bd9bd4470ce93824889fee55004c.invokeBean(WebhookImportService_VertxInvoker_onMessageUni_17549bde5566bd9bd4470ce93824889fee55004c.zig:68)
... (rest of the stacktrace)
[Uni] Received JsonObject: {"name":"quarkus"}
[Void] Received message: [headers=version=2.5.0.CR1, body={"name":"quarkus"}]
[Void] Received JsonObject: {"name":"quarkus"}
````

### Quarkus version or git rev

2.5.0.CR1

**Comment by rgmz** [comment]
+ @cescoffier, as I believe this falls under `area/vertx`.

**Comment by rgmz** [comment]
Looking at `EventBusConsumer#implementInvoke`, it appears that `T` checks for multiple return types:
https://github.com/quarkusio/quarkus/blob/2cbd177416f92b9f45abb34b6f01acb8cb0f4eb5/extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java#L176-L187

However `Message<T>` only checks for a void return type:
https://github.com/quarkusio/quarkus/blob/2cbd177416f92b9f45abb34b6f01acb8cb0f4eb5/extensions/vertx/deployment/src/main/java/io/quarkus/vertx/deployment/EventBusConsumer.java#L161-L165

Is `Message<T>` only work with void return types deliberate?

**Comment by mkouba** [comment]
Well, the javadoc of `@ConsumeEvent` is pretty clear that _"If it accepts `io.vertx.core.eventbus.Message` then the return type must be void"_, i.e. you should call the `Message.reply()` method directly. However, I'm not sure why the return type is not validated during build.

**Comment by rgmz** [comment]
> Well, the javadoc of [@ConsumeEvent](https://github.com/quarkusio/quarkus/blob/75536aeaf79fad44452f19b6077958eb047c06b4/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/ConsumeEvent.java) is pretty clear that "If it accepts io.vertx.core.eventbus.Message then the return type must be void", i.e. you should call the Message.reply() method directly. 

_Ahh_ — IntelliJ's been having issues displaying sources, so I must have missed this.

So I guess the questions are:
1. Can Quarkus validate the return type on build (which I see you've already opened a PR for)
2. If `Message` cannot return `Uni<T>` for logical reasons, is it possible to inject both the [ `Message#headers`](https://vertx.io/docs/apidocs/io/vertx/core/eventbus/Message.html#headers--) and the body? I'm happy to open a PR for this, provided it's possible for `@ConsumeEvent` to work with 2 parameter types.

**Comment by cescoffier** [comment]
About 1 - well, @mkouba is fast!
About 2 - yes, we could inject the message header as parameter.

**Comment by rgmz** [comment]
I've created PR #21653 to do 2. It likely needs some polishing, but let me know your thoughts on the general approach.
