### ISSUE TITLE
Possible bug in gRPC client regarding MaxInboundMessageSize

### ISSUE THREAD

**Issue by dhoffer** [quarkusio/quarkus#21649]
### Describe the bug

I have found I get the following error in the gRPC client when the server sends a large message.

I have a very large value set for quarkus.grpc.clients.std.max-inbound-message-size property.

However if I in code set withMaxInboundMessageSize on the Grpc stub to a large value everything works as expected.  It seems the property value is being ignored.

                                                  Powered by Quarkus 2.4.2.Final
2021-11-23 08:43:20,610 INFO  [io.quarkus] (main) app-grpc-client 1.0-SNAPSHOT on JVM (powered by Quarkus 2.4.2.Final) started in 0.914s.
2021-11-23 08:43:20,611 INFO  [io.quarkus] (main) Profile prod activated.
2021-11-23 08:43:20,612 INFO  [io.quarkus] (main) Installed features: [cdi, config-yaml, smallrye-context-propagation, vertx]
2021-11-23 08:43:20,615 INFO  [com.bs.grp.cli.GrpcMain] (main) Running main method
2021-11-23 08:43:29,004 INFO  [io.grp.int.AbstractClientStream] (grpc-nio-worker-ELG-2-2) Received data on closed stream
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 139524662021-11-23 08:43:29,005 INFO  [io.grp.int.AbstractClientStream] (grpc-nio-worker-ELG-2-2) Received data on closed stream

        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
2021-11-23 08:43:29,007 INFO  [io.grp.int.AbstractClientStream] (grpc-nio-worker-ELG-2-2) Received data on closed stream
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at com.bs.app.proto.services.test.TestServiceGrpc$TestServiceBlockingStub.current(TestServiceGrpc.java:993)
        at com.bs.grpc.client.ProtobufClient.run(ProtobufClient.java:126)
2021-11-23 08:43:29,008 INFO  [io.grp.int.AbstractClientStream] (grpc-nio-worker-ELG-2-2) Received data on closed stream
        at com.bs.grpc.client.GrpcMain.run(GrpcMain.java:79)
        at com.bs.grpc.client.GrpcMain_ClientProxy.run(GrpcMain_ClientProxy.zig:129)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:125)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
2021-11-23 08:43:29,009 INFO  [io.grp.int.AbstractClientStream] (grpc-nio-worker-ELG-2-2) Received data on closed stream
2021-11-23 08:43:29,009 INFO  [io.grp.int.AbstractClientStream] (grpc-nio-worker-ELG-2-2) Received data on closed stream
2021-11-23 08:43:29,009 INFO  [io.grp.int.AbstractClientStream] (grpc-nio-worker-ELG-2-2) Received data on closed stream
2021-11-23 08:43:29,009 INFO  [io.grp.int.AbstractClientStream] (grpc-nio-worker-ELG-2-2) Received data on closed stream

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\Programs\apache-maven-3.8.1\bin\.. Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: C:\Programs\Java\jdk-11.0.11.9-hotspot Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by dhoffer** [comment]
Please delete this issue.  It turns out in my case I didn't have the client configured correctly for Quarkus to read the properties.  Since the online Quarkus docs for gRPC were too brief I had to use other sources as well and they didn't do it the Quarkus way so that part did not work.
