### ISSUE TITLE
MessageBundle(qute/jboss logging) not work with gradle multi module

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#21672]
### Describe the bug

Can not start service with gradle multi module

### Expected behavior

MessageBundle work well

### Actual behavior

1、when use io.quarkus.qute.i18n.MessageBundle not work
2、when use org.jboss.logging.annotations.MessageBundle not work

### How to Reproduce?

demo project in 
https://github.com/qwlabs/quarkus-graphql/tree/jboss-logging
and 
https://github.com/qwlabs/quarkus-graphql/tree/qute

step in README.md
   

### Output of `uname -a` or `ver`

Darwin Kernel Version 20.6.0

### Output of `java -version`

11.0.2

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by pipinet** [comment]
@dmlloyd qute error message in here https://github.com/qwlabs/quarkus-graphql/blob/qute/README.md

**Comment by mkouba** [comment]
> hi qute error message in here https://github.com/qwlabs/quarkus-graphql/blob/qute/README.md

@pipinet it seems that the `shared` module is not a bean archive as described in the [bean discovery documentation](https://quarkus.io/guides/cdi-reference#bean_discovery). You can try to place an empty `beans.xml` file in the `META-INF` of your shared module.

**Comment by pipinet** [comment]
@mkouba tks, got it! fixed.
what about  jboss logging ? https://github.com/qwlabs/quarkus-graphql/blob/jboss-logging/README.md

**Comment by pipinet** [comment]
@mkouba hi,

in jboos logging case,  i add class path to annotationProcessor fixed class not found error.
```gradle
annotationProcessor("org.jboss.logging:jboss-logging:3.4.2.Final")
```

but quarkus gradle plugin not include annotationProcessor output folder  build/generated/sources/annotationProcessor to class path

error message is :
```log
$ ./gradlew quarkusDev

> Task :services:api-service:quarkusDev
Listening for transport dt_socket at address: 5005
Press [h] for more options>NG [3s]
Tests paused
Press [r] to resume testing, [h] for more options>
Press [r] to resume testing, [o] Toggle test output, [h] for more options>
2021-11-25 10:47:18,492 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-53) Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives:
- "com.qwlabs.quarkus" found in [qwlabs.crp:security::jar, qwlabs.crp:shared::jar]
     2021-11-25 10:47:18,682 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure3s]
2021-11-25 10:47:18,793 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
     2021-11-25 10:47:19,017 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.qwlabs.quarkus.SecurityMessages and qualifiers [@Default]
        - java member: com.qwlabs.quarkus.IdentityService#<init>()
        - declared on CLASS bean [types=[com.qwlabs.quarkus.IdentityService, java.lang.Object], qualifiers=[@Default, @Any], target=com.qwlabs.quarkus.IdentityService]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1190)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:268)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:418)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:821)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.qwlabs.quarkus.SecurityMessages and qualifiers [@Default]
        - java member: com.qwlabs.quarkus.IdentityService#<init>()
        - declared on CLASS bean [types=[com.qwlabs.quarkus.IdentityService, java.lang.Object], qualifiers=[@Default, @Any], target=com.qwlabs.quarkus.IdentityService]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:567)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:470)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:256)
        ... 13 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:418)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:276)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:67)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:91)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:446)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:65)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:105)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.qwlabs.quarkus.SecurityMessages and qualifiers [@Default]
        - java member: com.qwlabs.quarkus.IdentityService#<init>()
        - declared on CLASS bean [types=[com.qwlabs.quarkus.IdentityService, java.lang.Object], qualifiers=[@Default, @Any], target=com.qwlabs.quarkus.IdentityService]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1190)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:268)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:418)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:821)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.qwlabs.quarkus.SecurityMessages and qualifiers [@Default]
        - java member: com.qwlabs.quarkus.IdentityService#<init>()
        - declared on CLASS bean [types=[com.qwlabs.quarkus.IdentityService, java.lang.Object], qualifiers=[@Default, @Any], target=com.qwlabs.quarkus.IdentityService]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:567)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:470)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:256)
        ... 13 more

        at io.quarkus.builder.Execution.run(Execution.java:116)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:161)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:416)
        ... 9 more
Caused by: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.qwlabs.quarkus.SecurityMessages and qualifiers [@Default]
        - java member: com.qwlabs.quarkus.IdentityService#<init>()
        - declared on CLASS bean [types=[com.qwlabs.quarkus.IdentityService, java.lang.Object], qualifiers=[@Default, @Any], target=com.qwlabs.quarkus.IdentityService]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1190)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:268)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:418)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:821)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.qwlabs.quarkus.SecurityMessages and qualifiers [@Default]
        - java member: com.qwlabs.quarkus.IdentityService#<init>()
        - declared on CLASS bean [types=[com.qwlabs.quarkus.IdentityService, java.lang.Object], qualifiers=[@Default, @Any], target=com.qwlabs.quarkus.IdentityService]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:567)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:470)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:256)
        ... 13 more


<============-> 94% EXECUTING [4m 5s]
> :services:api-service:quarkusDev
```

**Comment by mkouba** [comment]
@pipinet By default, `jboss-logging` message bundles cannot be injected via CDI. You can obtain the message bundle via `org.jboss.logging.Messages.getBundle(Class<T>)` instead. Typically, you'll initialize a static field like this:
```java
@MessageBundle(projectCode = "QWSEC")
public interface SecurityMessages {

    SecurityMessages log =  org.jboss.logging.Messages.getBundle(SecurityMessages.class);

    @Message(value = "User name not found")
    RuntimeException usernameNotFound();
}
```
And then just use `SecurityMessages.LOG.usernameNotFound()` in your code.

**Comment by pipinet** [comment]
@mkouba oh, i forgot it, I used this way in single module project.

**Comment by mkouba** [comment]
Ok, I think we can close this issue now ;-)

**Comment by pipinet** [comment]
@mkouba sure！thanks for your help!
