### ISSUE TITLE
Startup fails if OIDC provider is not available

### ISSUE THREAD

**Issue by sandronm** [quarkusio/quarkus#21706]
### Describe the bug

I'm using the quarkus-oidc extension (multi-tenants) to securize my rest endpoints.
I defined the default oidc server as follow:

```
%prod.quarkus.oidc.auth-server-url=https://www.myoidcserver.com
%prod.quarkus.oidc.token.issuer=my-issuer
%prod.quarkus.oidc.token.audience=my-audience
%prod.quarkus.oidc.credentials.jwt.token-key-id=my-jwt-token-id
%prod.quarkus.oidc.jwks-path=/jwt/jwk-set.json
%prod.quarkus.oidc.token.header=My-Authorization
%prod.quarkus.oidc.discovery-enabled=false
%prod.quarkus.oidc.token.allow-jwt-introspection=false
%prod.quarkus.oidc.token.allow-opaque-token-introspection=false
```

### Expected behavior

I should be able to run my docker container even if https://www.myoidcserver.com is not reachable.
Just like mentionned here: https://github.com/quarkusio/quarkus/issues/16725

### Actual behavior

I got the following exception:

```
io.quarkus.oidc.common.runtime.OidcEndpointAccessException
        at io.quarkus.oidc.runtime.OidcProviderClient.getJsonWebKeySet(OidcProviderClient.java:77)
        at io.quarkus.oidc.runtime.OidcProviderClient.lambda$getJsonWebKeySet$0(OidcProviderClient.java:56)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
        at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
        at io.vertx.mutiny.ext.web.client.HttpRequest$10.handle(HttpRequest.java:717)
        at io.vertx.mutiny.ext.web.client.HttpRequest$10.handle(HttpRequest.java:714)
        at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:370)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:357)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:335)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:302)
        at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:264)
        at io.vertx.ext.web.client.impl.HttpContext.lambda$null$8(HttpContext.java:519)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

1. Install the extension quarkus-oidc
2. Define the oidc params (copy/paste my params listed above)
3. mvnv package
4. docker build
5. docker run

### Quarkus version or git rev

2.4.2.Final

**Comment by sberyozkin** [comment]
@sandronm Thanks, it definitely works (and is tested) with the discovery enabled but indeed there could be some issues if it is disabled

**Comment by sandronm** [comment]
I didn't tried with the discovery enabled I have to admit @sberyozkin :-)
But unfortunately for my usecase I cannot rely on this feature.

**Comment by sberyozkin** [comment]
Np, we'll have a look
