### ISSUE TITLE
NoSuchFileException: .../target/classes when executing a codegen task

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#21718]
### Describe the bug

I have seen this happening only with a warmed up daemon in Camel Quarkus. Here is a stack trace:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.5.0.Final:generate-code (quarkus-generate-code) on project camel-quarkus-integration-test-protobuf: Quarkus code generation phase has failed: Error while reading file as JAR: /home/ppalaga/orgs/cq/camel-quarkus/integration-tests/protobuf/target/classes -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:2.5.0.Final:generate-code (quarkus-generate-code) on project camel-quarkus-integration-test-protobuf: Quarkus code generation phase has failed
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.maven.plugin.MojoExecutionException: Quarkus code generation phase has failed
        at io.quarkus.maven.GenerateCodeMojo.generateCode(GenerateCodeMojo.java:87)
        at io.quarkus.maven.GenerateCodeMojo.doExecute(GenerateCodeMojo.java:54)
        at io.quarkus.maven.QuarkusBootstrapMojo.execute(QuarkusBootstrapMojo.java:123)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        ... 10 common frames omitted
Caused by: java.io.UncheckedIOException: Error while reading file as JAR: /home/ppalaga/orgs/cq/camel-quarkus/integration-tests/protobuf/target/classes
        at io.quarkus.bootstrap.classloading.JarClassPathElement.<init>(JarClassPathElement.java:80)
        at io.quarkus.bootstrap.classloading.ClassPathElement.fromPath(ClassPathElement.java:50)
        at io.quarkus.bootstrap.app.CuratedApplication.createDeploymentClassLoader(CuratedApplication.java:331)
        at io.quarkus.maven.GenerateCodeMojo.generateCode(GenerateCodeMojo.java:71)
        ... 14 common frames omitted
Caused by: java.nio.file.NoSuchFileException: /home/ppalaga/orgs/cq/camel-quarkus/integration-tests/protobuf/target/classes
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
        at io.smallrye.common.io.jar.JarFiles.create(JarFiles.java:33)
        at io.quarkus.bootstrap.classloading.JarClassPathElement.<init>(JarClassPathElement.java:75)
        ... 17 common frames omitted
```

A fix follows

**Comment by aloubyansky** [comment]
By daemon you mean `mvnd`?

**Comment by ppalaga** [comment]
Declaring quarkus-maven-plugin with `<extensions>true</extensions>` works for me.
