### ISSUE TITLE
JAVA AZURE Module client creation fails using Quarkus native binary (Graavlvm) 

### ISSUE THREAD

**Issue by prashantg077** [quarkusio/quarkus#21741]
### Describe the bug

Creation of module client using JAVA Microsoft Azure sdk with Quarkus native binary fails . Below is the code snippet

```
 ModuleClient moduleSenderClient = ModuleClient.createFromEnvironment(IotHubClientProtocol.AMQPS);
 moduleSenderClient.open();
```

NOTE the same code works when using a JVM based binary.

Below is the exception trace:

```
2021-10-06T23:05:27.304627ZCaused by: java.lang.RuntimeException: Could not load platform constants for ProtocolFamily
2021-10-06T23:05:27.304636Z at jnr.constants.platform.ConstantResolver.getConstants(ConstantResolver.java:227)
2021-10-06T23:05:27.304644Z at jnr.constants.platform.ConstantResolver.lookupAndCacheConstant(ConstantResolver.java:128)
2021-10-06T23:05:27.304651Z at jnr.constants.platform.ConstantResolver.getConstant(ConstantResolver.java:116)
2021-10-06T23:05:27.304676Z at jnr.constants.platform.ConstantResolver.longValue(ConstantResolver.java:179)
2021-10-06T23:05:27.304684Z at jnr.constants.platform.ProtocolFamily.intValue(ProtocolFamily.java:48)
2021-10-06T23:05:27.304691Z at jnr.unixsocket.SockAddrUnix.setFamily(SockAddrUnix.java:55)
2021-10-06T23:05:27.304699Z at jnr.unixsocket.UnixSocketAddress.<init>(UnixSocketAddress.java:48)
2021-10-06T23:05:27.304733Z at com.microsoft.azure.sdk.iot.device.hsm.HttpsHsmClient.sendHttpRequestUsingUnixSocket.connect(HttpsHsmClient.java:238)
```

### Expected behavior

Module client should be created and opened successfully.

### Actual behavior

Module client creation fails with below error;

```
2021-10-06T23:05:27.304627ZCaused by: java.lang.RuntimeException: Could not load platform constants for ProtocolFamily
2021-10-06T23:05:27.304636Z at jnr.constants.platform.ConstantResolver.getConstants(ConstantResolver.java:227)
2021-10-06T23:05:27.304644Z at jnr.constants.platform.ConstantResolver.lookupAndCacheConstant(ConstantResolver.java:128)
2021-10-06T23:05:27.304651Z at jnr.constants.platform.ConstantResolver.getConstant(ConstantResolver.java:116)
2021-10-06T23:05:27.304676Z at jnr.constants.platform.ConstantResolver.longValue(ConstantResolver.java:179)
2021-10-06T23:05:27.304684Z at jnr.constants.platform.ProtocolFamily.intValue(ProtocolFamily.java:48)
2021-10-06T23:05:27.304691Z at jnr.unixsocket.SockAddrUnix.setFamily(SockAddrUnix.java:55)
2021-10-06T23:05:27.304699Z at jnr.unixsocket.UnixSocketAddress.<init>(UnixSocketAddress.java:48)
2021-10-06T23:05:27.304733Z at com.microsoft.azure.sdk.iot.device.hsm.HttpsHsmClient.sendHttpRequestUsingUnixSocket.connect(HttpsHsmClient.java:238)
```

### How to Reproduce?

https://github.com/prashantg077/quarkusBugsReproducersPras

Download & unzip the project . 
Import maven project.

Also , there will be a Dockerfile.jvm for JVM binary and Dockerfile.native for native binary.

Build the image using Dockerfile.native file.

Start the project.

### Output of `java -version`

11

**Comment by geoand** [comment]
For this to work, there would need to be a dedicated extension. 

To help getting that off the ground, I looked at the code that is causing the initial problem (which is [this](https://github.com/jnr/jnr-constants/blob/jnr-constants-0.9.12/src/main/java/jnr/constants/ConstantSet.java) class) and it seems from [here](https://github.com/jnr/jnr-constants/blob/jnr-constants-0.9.12/src/main/java/jnr/constants/ConstantSet.java#L58) that an extension would need to provide `new NativeImageResourceBuildItem("jnr/constants/ConstantSet.class")`
