### ISSUE TITLE
Qute unable to find template extension methods with @TemplateAttribute annotation

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#21779]
### Describe the bug

I have updated my Quarkus app from 2.3.1.Final to 2.5.0.Final. Since then, Qute Template Extension no longer recognizes methods marked with an @TemplateAttribute annotation and throws the following error when launching from the app. I can confirm that the error happens from version 2.4.0.Final.

I have built a small project with which the error can be reproduced: https://github.com/andlinger/quarkus-qute-namespace

In the [Extensions](https://github.com/andlinger/quarkus-qute-namespace/blob/main/quarkus/src/main/java/io/i15s/quarkus/namespace/Extensions.java) class you can find two methods. `formatCountryEnglish` works perfectly. As soon as `formatCountry` is used, Quarkus produces the exception attached below.

```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#processTemplateErrors threw an exception: io.quarkus.qute.TemplateException: Found template problems (1):
[1] Incorrect expression found: {base:formatCountry("SE")}
	- no matching namespace [base] extension method found
	- at HtmlResource/test.html:5
	at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {base:formatCountry("SE")}
	- no matching namespace [base] extension method found
	- at HtmlResource/test.html:5
		at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:168)
		... 11 more

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:93)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:450)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:105)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#processTemplateErrors threw an exception: io.quarkus.qute.TemplateException: Found template problems (1):
[1] Incorrect expression found: {base:formatCountry("SE")}
	- no matching namespace [base] extension method found
	- at HtmlResource/test.html:5
	at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {base:formatCountry("SE")}
	- no matching namespace [base] extension method found
	- at HtmlResource/test.html:5
		at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:168)
		... 11 more

	at io.quarkus.builder.Execution.run(Execution.java:116)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:161)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
	... 9 more
Caused by: io.quarkus.qute.TemplateException: Found template problems (1):
[1] Incorrect expression found: {base:formatCountry("SE")}
	- no matching namespace [base] extension method found
	- at HtmlResource/test.html:5
	at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {base:formatCountry("SE")}
	- no matching namespace [base] extension method found
	- at HtmlResource/test.html:5
		at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:168)
		... 11 more
```

**Comment by mkouba** [comment]
We validate expressions connected to namespace extension methods since 2.4.0 so it's definitely related. I think that we don't skip the parameters annotated with `@TemplateAttribute` when matching extension methods. I'll try to send a PR shortly.
