### ISSUE TITLE
Allow for testing with junit ConsoleLauncher

### ISSUE THREAD

**Issue by sparnord1337** [quarkusio/quarkus#21784]
### Description

JUnit5 includes a jar file for running tests directly from the commandline. Unfortunately Quarkus crashes with the following error. It would be really nice to be able to run Quarkus tests with the JUnit harness.

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodException: io.quarkus.runner.bootstrap.AugmentActionImpl.<init>(io.quarkus.bootstrap.app.CuratedApplication,java.util.List)
                at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:584)
                at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeAllMethod(QuarkusTestExtension.java:641)
                at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
                at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
                at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
                at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
                at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
                at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:68)
                at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
                at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
                at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
                at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
                at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
                at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
                at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
                at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
                at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$11(ClassBasedTestDescriptor.java:397)
                at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
                at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:395)
                at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:209)
                at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
                at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
                at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
                at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
                at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
                at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
                at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
                at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
                at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
                at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
                at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
                at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
                at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
                at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
                at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
                at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
                at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
                at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
                at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
                at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
                at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
                at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
                at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
                at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
                at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
                at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
                at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
                at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
                at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
                at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
                at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
                at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:66)
                at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:58)
                at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.replaceThreadContextClassLoaderAndInvoke(CustomContextClassLoaderExecutor.java:41)
                at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:31)
                at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:58)
                at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:95)
                at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:73)
                at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:50)
                at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:43)
                at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:37)
             Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: io.quarkus.runner.bootstrap.AugmentActionImpl.<init>(io.quarkus.bootstrap.app.CuratedApplication,java.util.List)
                at io.quarkus.bootstrap.app.CuratedApplication.createAugmentor(CuratedApplication.java:137)
                at io.quarkus.test.junit.AbstractJvmQuarkusTestExtension.createAugmentor(AbstractJvmQuarkusTestExtension.java:184)
                at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:213)
                at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:561)
                at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:599)
                at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381)
                at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
                at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381)
                at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205)
                ... 41 more
             Caused by: java.lang.NoSuchMethodException: io.quarkus.runner.bootstrap.AugmentActionImpl.<init>(io.quarkus.bootstrap.app.CuratedApplication,java.util.List)
                at java.base/java.lang.Class.getConstructor0(Class.java:3517)
                at java.base/java.lang.Class.getConstructor(Class.java:2238)
                at io.quarkus.bootstrap.app.CuratedApplication.createAugmentor(CuratedApplication.java:135)
                ... 49 more

```

### Implementation ideas

It looks like Quarkus assumes that its QuarkusTestExtension class will be loaded by something that falls below the SystemClassLoader, which is not the case when using JUnit Console Launcher (as that sets the classloader to a URIClassLoader).

The specific dependency seems to go like this:
https://github.com/quarkusio/quarkus/blob/11f39400da701bc49da3635436307a8d6f6ea7a0/test-framework/junit5/src/main/java/io/quarkus/test/junit/AbstractJvmQuarkusTestExtension.java#L154-L164

The Quarkus application is started with the default classloader which is retrieved with `ClassLoader.getSystemClassLoader` (Inside of `QuarkusBootstrap.Builder`. you'll have to trust me). This classloader is then used to create the internal/custom Quarkus ClassLoaders. One of those internal ClassLoaders (the Augmentation ClassLoader specifically) is used to load some more classes

https://github.com/quarkusio/quarkus/blob/657ae2965955ba1bd015d2049e4830dc223c1b36/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java#L130-L135

This is where the exception is thrown. The Quarkus ClassLoader that loads `AugmentActionImpl` doesn't have our URLClassLoader in the parent chain (since it was created from the system ClassLoader). So when we get the constructor on line 135 we are mixing the two distinct class spaces. That's no good.

Empirically i have found that explicitly setting the runnerBuilder BaseClassLoader in `AbstractJvmQuarkusTestExtension.java:157` to `this.getClass().getClassLoader()` solves this issue, since Quarkus will then be loaded as a child of the URLClassLoader.

**Comment by famod** [comment]
Never used `ConsoleLauncher` so I'm probably missing something, but are you aware of continuous testing in Quarkus?

**Comment by geoand** [comment]
How exactly does one use `ConsoleLauncher`? And what would be the benefit of making it work for Quarkus?

**Comment by sparnord1337** [comment]
@famod I am. I suppose I prefer request response type command execution. It's also already part of my workflow.

@geoand The`ConsoleLauncher` is just a standalone jar file that lets you run JUnit tests from a ClassPath. It'll scan for all the JUnit tests, execute the whole JUnit engine rigamarole, and write out the results to stdout. Optionally it can produce the well known JUnit reports as well. Detailed instructions are available [in the JUnit5 manual](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher). I think that explains it better than I could hope to.

From my vantage point it's a case of wanting to use the tools I'm use to. I use the `ConsoleLauncher` for non-Quarkus project, why not Quarkus projects as well? is my rhetorical question. Especially when I could get it working with single added line. In fact I now see that you do basically the same thing in the IDELauncher as I'm asking to do in the test launcher

https://github.com/quarkusio/quarkus/blob/b8a815495b5e22c702361d5bc8e45ce999d8df9a/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/IDELauncherImpl.java#L37

**Comment by geoand** [comment]
Thanks for the information.

If you already have a fix in mind, feel free to open a Pull Request :)

**Comment by robertgates55** [comment]
@sparnord1337 did you ever find a way to get this working?

**Comment by javaduke** [comment]
Is there any workaround for this? I just ran into this issue, the command line fails with exact same error:
`mvn clean test`

fails with:

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodException: io.quarkus.runner.bootstrap.AugmentActionImpl.<init>(io.quarkus.bootstrap.app.CuratedApplication,java.util.List)
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:639)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:723)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: io.quarkus.runner.bootstrap.AugmentActionImpl.<init>(io.quarkus.bootstrap.app.CuratedApplication,java.util.List)
	at io.quarkus.bootstrap.app.CuratedApplication.createAugmentor(CuratedApplication.java:126)
	at io.quarkus.test.junit.AbstractJvmQuarkusTestExtension.createAugmentor(AbstractJvmQuarkusTestExtension.java:207)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:218)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:606)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:656)
	... 1 more
Caused by: java.lang.NoSuchMethodException: io.quarkus.runner.bootstrap.AugmentActionImpl.<init>(io.quarkus.bootstrap.app.CuratedApplication,java.util.List)
	at java.base/java.lang.Class.getConstructor0(Class.java:3761)
	at java.base/java.lang.Class.getConstructor(Class.java:2442)
	at io.quarkus.bootstrap.app.CuratedApplication.createAugmentor(CuratedApplication.java:124)
	... 5 more
```

**Comment by blz777** [comment]
I also have the same issue - the use case if when running unit tests from neovim using the neotest-java plugin. Has somebody found a workaround?

**Comment by maxandersen** [comment]
Probably the console launcher doesn't wire up the junit extensions the same way as when run from mvn and Gradle. 

I don't have a solution off hand but maybe there is some options for the launcher or a custom launcher is needed.

**Comment by maxandersen** [comment]
If you can provide a reproducer project with steps used to run the launcher that would be good.
