### ISSUE TITLE
@BeanParam without at least one field annotated with @QueryParam produces ClassCastException with reasteasy-reactive

### ISSUE THREAD

**Issue by luca-bassoricci** [quarkusio/quarkus#21789]
### Describe the bug

Injecting a bean like this one:
```
public class BeanParam
{
	private String stringValue;
	private long longValue;	
	@QueryParam("string-value")
	public void setStringValue(String stringValue)
	{
		this.stringValue = stringValue;
	}
	@QueryParam("long-value")
	public void setLongValue(long longValue)
	{
		this.longValue = longValue;
	}
}
```
as endpoint parameter with `@BeanParam` causes an HTTP error 404 due to a `ClassCastException`.

The bean slightly modified
```
public class BeanParam
{
	@QueryParam("_unused")
	private String _unused;
	private String stringValue;
	private long longValue;
	
	@QueryParam("string-value")
	public void setStringValue(String stringValue)
	{
		this.stringValue = stringValue;
	}
...
``` 
doesn't produce the `ClassCastException`, but `@QueryParam` annotations are not honored.

### Expected behavior

Bean injected with extracted values from query string

### Actual behavior

```
javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:58)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:14)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.ClassCastException: class org.acme.TestBeanParam cannot be cast to class org.jboss.resteasy.reactive.server.injection.ResteasyReactiveInjectionTarget (org.acme.TestBeanParam is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @759d81f3; org.jboss.resteasy.reactive.server.injection.ResteasyReactiveInjectionTarget is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @5e0e82ae)
	at org.jboss.resteasy.reactive.server.core.parameters.InjectParamExtractor.extractParameter(InjectParamExtractor.java:25)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:38)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:14)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### How to Reproduce?

The attached archive contains a maven project to reproduce the error
[error-bean-param.zip](https://github.com/quarkusio/quarkus/files/7619137/error-bean-param.zip)

### Output of `uname -a` or `ver`

Microsoft Windows [Versione 10.0.19042.1288]

### Output of `java -version`

openjdk version "11.0.6" 2020-01-14 LTS

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

All tests works without errors in quarkus-resteasy (not reactive version).

**Comment by Sgitario** [comment]
`@QueryParam` annotations only work in fields. I've provided a PR https://github.com/quarkusio/quarkus/pull/21817 to enhance the exceptions we throw. Therefore, instead of a 400 caused by a cast class exception, you will get an exception at build time saying that either there are no fields annotated or that there are methods annotated with wrong JAX-RS annotations.
cc @geoand
