### ISSUE TITLE
[Resteasy Reactive] Can't upload files from cURL

### ISSUE THREAD

**Issue by indalaterre** [quarkusio/quarkus#21923]
### Describe the bug

I'm uploading some files from a cURL request and everything went fine using the v.1.12.x without resteasy reactive
After the upload to Quarkus 2.5.1.Final I got this error

```

2021-12-03 17:49:11 ERROR AbstractResteasyReactiveContext                    Request failed: java.io.IOException: Connection terminated parsing multipart request
        at org.jboss.resteasy.reactive.server.core.multipart.MultiPartParserDefinition$MultiPartUploadHandler.parseBlocking(MultiPartParserDefinition.java:221)
        at org.jboss.resteasy.reactive.server.handlers.FormBodyHandler.handle(FormBodyHandler.java:88)
        at org.jboss.resteasy.reactive.server.handlers.FormBodyHandler.handle(FormBodyHandler.java:25)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

This is the cURL ​command

```
  curl -vvv --insecure --noproxy "*" \
       --header "Content-Type: multipart/form-data; boundary=---------------BOUNDARY" \
       --request PUT \
       --form "filename=$filename" \
       --form "isRestricted=false" \
       --form "file=@$filePath" \
       "$STORAGE_ADDRESS/v1/public/$PRINT_TEMPLATES_BUCKET_NAME"
```

### Expected behavior

No regressions are found updating to Resteasy reactive

### Output of `uname -a` or `ver`

Darwin NMOL539819.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.5.1.Final

### Additional information

This is the sign of the API. Its code is never reached. We currently don't use native mode. Only JVM. 
The upload from Postman or from a custom Java multipart request works well.

```java
import org.jboss.resteasy.reactive.MultipartForm;

public Response save(String bucket, @MultipartForm UploadRequest body)

@Data
@RegisterForReflection
public class UploadRequest {

	/**
	 * The file data
	 */
	@RestForm
	@PartType(MediaType.APPLICATION_OCTET_STREAM)
	private FileUpload file;

	/**
	 * The file name
	 */
	@RestForm
	@PartType(MediaType.TEXT_PLAIN)
	private String filename;

	/**
	 * The file metadata
	 */
	@RestForm
	@PartType(MediaType.APPLICATION_JSON)
	private Map<String, String> metadata;

	/**
	 * TRUE if the file must be temporary (Deleted at first access)
	 */
	@RestForm
	@PartType(MediaType.TEXT_PLAIN)
	private boolean isTemporary;

	/**
	 * The input stream of the uploaded file
	 */
	private InputStream uploadedFileStream;

	/**
	 * Converts the uploaded file to an InputStream
	 * @throws IOException in case of read errors
	 */
	public void setUploadedFileStream() throws IOException {
		this.uploadedFileStream = Files.newInputStream(this.file.uploadedFile());
	}

}
```

**Comment by gsmet** [comment]
I think it would help if you could upload a zip with a small Maven reproducer.

**Comment by indalaterre** [comment]
Hello and happy new year!

This is the reproducer. I created a script "upload.sh" to fire the request.
[demo.zip](https://github.com/quarkusio/quarkus/files/7801113/demo.zip)

**Comment by geoand** [comment]
This is a not a Quarkus problem, but a problem with how you are using cURL. If you capture the traffic for the request your upload script is sending you will see:

```
Content-Type: multipart/form-data; boundary=---------------BOUNDARY; boundary=------------------------d81b7fc1ac7dc2b1\r\n
```

which is clearly wrong. A valid multipart request would contain somethingh like:

```
Content-Type: multipart/form-data; boundary=------------------------cbd1439637c70b18\r\n
```
