### ISSUE TITLE
New Fs Util broke Quartz and multitenancy quickstarts

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#22079]
`hibernate-orm-multi-tenancy-quickstart` and `quartz-quickstart` are failing with the following error:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project hibernate-orm-multi-tenancy-quickstart: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.flyway.FlywayProcessor#build threw an exception: java.nio.file.FileSystemNotFoundException
[ERROR] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169)
[ERROR] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155)
[ERROR] 	at java.base/java.nio.file.Path.of(Path.java:208)
[ERROR] 	at io.quarkus.flyway.FlywayProcessor.initFileSystem(FlywayProcessor.java:285)
[ERROR] 	at io.quarkus.flyway.FlywayProcessor.discoverApplicationMigrations(FlywayProcessor.java:231)
[ERROR] 	at io.quarkus.flyway.FlywayProcessor.build(FlywayProcessor.java:99)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

Failing path is `jar:file:/data/home/gsmet/git/quarkus-quickstarts/quartz-quickstart/target/quartz-quickstart-1.0.0-SNAPSHOT.jar!/db/migration/` for Quartz.

I have no idea if it's correct and should contain the `!/db/migration/` part. Also, I don't know if the `env.put("create", "true");` is of interest.

We need a fix for 2.6.0.Final so before Tuesday evening.

/cc @Postremus @aloubyansky

**Comment by Postremus** [comment]
@gsmet I am looking into it.

**Comment by gsmet** [comment]
@Postremus don't bother about the other quickstarts' failure, I worked on them already so build these ones specifically.

**Comment by gsmet** [comment]
Precision: I'm using JDK 11.
