### ISSUE TITLE
NPE while live updating quarkus from 2.5.0 to 2.5.1 in RuntimeUpdatesProcessor

### ISSUE THREAD

**Issue by dashorst** [quarkusio/quarkus#22105]
### Describe the bug

I modified the version property from 2.5.0 to 2.5.1 in my POM while quarkus:dev was running, and to my amazement it started updating the server, only to fail at the end with a NPE:

```
[ERROR] Port 5005 in use, not starting in debug mode
Debugger failed to attach: handshake failed - connection prematurally closed

Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.close()" because "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.INSTANCE" is null
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:151)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.close()" because "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.INSTANCE" is null
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:152)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:105)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
	... 1 more
Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.close()" because "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.INSTANCE" is null
	at io.quarkus.deployment.dev.IsolatedDevModeMain.close(IsolatedDevModeMain.java:340)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:477)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	... 3 more
```

### Expected behavior

Obviously no NullPointerException and a working upgraded quarkus 2.5.1 :-) 

### Actual behavior

```
[ERROR] Port 5005 in use, not starting in debug mode
Debugger failed to attach: handshake failed - connection prematurally closed

Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.close()" because "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.INSTANCE" is null
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:151)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.close()" because "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.INSTANCE" is null
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:152)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:105)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
	... 1 more
Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.close()" because "io.quarkus.deployment.dev.RuntimeUpdatesProcessor.INSTANCE" is null
	at io.quarkus.deployment.dev.IsolatedDevModeMain.close(IsolatedDevModeMain.java:340)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:477)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	... 3 more
```

### How to Reproduce?

1. Start a 2.5.0 quick start project with mvn quarkus:dev
2. Modify the POM to upgrade to 2.5.1
3. Wait for it...
4. :boom: 

### Output of `uname -a` or `ver`

Linux fedora 5.15.6-100.fc34.x86_64 #1 SMP Wed Dec 1 13:41:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12) OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

### Quarkus version or git rev

2.5.0 and 2.5.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12) OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

**Comment by geoand** [comment]
I assume this does not happen if you perform a `clean`  first?

**Comment by dashorst** [comment]
Not sure what you mean with `clean` first, but if I don't let quarkus:dev run while updating the POM it just works. It only fails while quarkus:dev is running when I modify the pom.

**Comment by geoand** [comment]
I mean doing an `mvn clean` between version updates

**Comment by dashorst** [comment]
Is not necessary:

```
$ mvn quarkus:dev
... (powered by Quarkus 2.5.0.Final)
^C
```
update pom

```
$ mvn quarkus:dev
... (powered by Quarkus 2.5.1.Final)
```

**Comment by geoand** [comment]
That's my point... If you do clean between pom updates, do you get the problem?

**Comment by dashorst** [comment]
No, I don't get the problem when I do a clean between upgrades.

**Comment by geoand** [comment]
@aloubyansky is this something that is expected to work without a recompile? I would assume not..

**Comment by aloubyansky** [comment]
No, we don't guarantee it working across versions. Basically, if you upgrade, you should rebuild the app. I actually saw this NPE in a branch I am working on, so I'll fix the NPE, at least.

**Comment by dashorst** [comment]
Sounds fair. Would be awesome if it works though, but I can imagine you won't guarantee it working.

**Comment by gsmet** [comment]
If it's not supposed to work, is there a way to detect it's happening and display a proper error message?

IIRC, @stuartwdouglas made it possible to add dependencies to the pom while in dev mode so I suppose it's only broken if you update Quarkus itself?

**Comment by geoand** [comment]
> so I suppose it's only broken if you update Quarkus itself?

that is my understanding of the issue

**Comment by dashorst** [comment]
> so I suppose it's only broken if you update Quarkus itself?

AFAIK yes. I did not upgrade any dependencies other than updating the quarkus version property, which of course causes the quarkus BOM and plugins to be upgraded.

**Comment by stuartwdouglas** [comment]
We definitely can't guarantee this will work. Some versions it might, others it won't, but it's not something we want to spend time on.

**Comment by geoand** [comment]
Maybe we can at least throw an ISE with a good error message instead of a NPE. I assume that's what @aloubyansky meant in his comment above
