### ISSUE TITLE
reactive-mssql-client: java.lang.UnsupportedOperationException: Unsupported token

### ISSUE THREAD

**Issue by git4rputuval** [quarkusio/quarkus#22141]
### Describe the bug

MS SQL tables contains NVARCHAR2 columns. Firing a query on this table results in unsupported token exception.

### Expected behavior

Query should return the data consistently. Code works for some tables, but fails with above error code in other cases.

If the cause of this issue is not known, we will be forced to dump Quarkus for Spring Boot due to time constraints. Please provide a quick answer. Thanks.

### Actual behavior

**Error**:
```
$2could not execute query: java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: Unsupported token: 0
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at io.vertx.core.Future.lambda$toCompletionStage$2(Future.java:362)
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
        at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
        at io.vertx.sqlclient.impl.QueryResultBuilder.tryFail(QueryResultBuilder.java:118)
        at io.vertx.core.Promise.fail(Promise.java:89)
        at io.vertx.core.Promise.handle(Promise.java:53)
        at io.vertx.core.Promise.handle(Promise.java:29)
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:81)
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:173)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:66)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
        at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:43)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
        at io.vertx.sqlclient.impl.command.CommandResponse.fire(CommandResponse.java:46)
        at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:287)
        at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:99)
        at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:97)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
        at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
        at io.vertx.core.net.impl.NetSocketImpl.lambda$handleMessage$9(NetSocketImpl.java:390)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
        at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
        at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:389)
        at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.vertx.mssqlclient.impl.codec.TdsMessageCodec.fail(TdsMessageCodec.java:58)
        at io.vertx.mssqlclient.impl.codec.TdsMessageCodec.exceptionCaught(TdsMessageCodec.java:48)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsupportedOperationException: Unsupported token: 0
        at io.vertx.mssqlclient.impl.codec.MSSQLCommandCodec.decode(MSSQLCommandCodec.java:80)
        at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.decodeMessage(TdsMessageDecoder.java:65)
        at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.channelRead(TdsMessageDecoder.java:43)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        ... 20 more
```

### How to Reproduce?

**Backend Database**: MS SQL Server

**Table**: contains NVARCHAR2 columns

**Query**: 
```
select
        report_.COLUMN_1 as rep_col1_0_,
        report_.COLUMN_2 as rep_col2_0_,
        report_.COLUMN_3 as rep_col3_0_,
        report_.COLUMN_4 as rep_col4_0_,
        report_.COLUMN_5 as rep_col5_0_
    from
        schema_name.MY_REPORT report_
```

**Table Design**:
```
CREATE TABLE [schema_name].[MY_REPORT] (
[COLUMN_1] int NULL,
[COLUMN_2] int IDENTITY(1, 1) NOT NULL,
[COLUMN_3] nvarchar(MAX) NULL,
[COLUMN_4] nvarchar(MAX) NULL,
[COLUMN_5] nvarchar(MAX) NULL)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
```

**Connection Properties**:
```
quarkus.datasource.db-kind=mssql
quarkus.datasource.reactive.url=vertx-reactive:sqlserver://${db_host}/${db_name}
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.http.port=9380
```
Username and password is passed, but not added in above code.

**POM**
```
<properties>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>2.3.0.Final</quarkus.platform.version>
</properties>
<dependencyManagement>
  <dependencies>
	  <dependency>
		  <groupId>${quarkus.platform.group-id}</groupId>
		  <artifactId>${quarkus.platform.artifact-id}</artifactId>
		  <version>${quarkus.platform.version}</version>
		  <type>pom</type>
		  <scope>import</scope>
	  </dependency>
  </dependencies>
</dependencyManagement>
<dependencies>
  <dependency>
	  <groupId>io.quarkus</groupId>
	  <artifactId>quarkus-hibernate-reactive-panache</artifactId>
  </dependency>
  <dependency>
	  <groupId>io.quarkus</groupId>
	  <artifactId>quarkus-reactive-mssql-client</artifactId>
  </dependency>
</dependencies>
```

### Output of `uname -a` or `ver`

Windows Environment

### Output of `java -version`

java version "11.0.11" 2021-04-20 LTS

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by gsmet** [comment]
Please provide a simple Maven reproducer for the issue. Thanks!

**Comment by git4rputuval** [comment]
Thanks. Will test this out on 2.5.0.Final and give an update.

**Comment by git4rputuval** [comment]
I have used the latest quarkus version, 2.5.0. I am getting a different error than above. But I do get this same error for some components in Quarkus 2.3.0.
[error.txt](https://github.com/quarkusio/quarkus/files/7708155/error.txt)

PFA the program for your reference
[demo-test.zip](https://github.com/quarkusio/quarkus/files/7708147/demo-test.zip)

PFA the SQL script
[demo-sql.txt](https://github.com/quarkusio/quarkus/files/7708145/demo-sql.txt)

Please use the following system properties
```
- db_host=<host:port>
- db_name=<db-name>
- demo.uname=<db-username>
- demo.pwd=<db-pwd>
```
Awaiting your quick response. Thanks.

**Comment by tsegismont** [comment]
Thank you @git4rputuval . The new error that you see is certainly due to lack of support of `VARCHAR(MAX)/NVARCHAR(MAX)` (see https://github.com/eclipse-vertx/vertx-sql-client/issues/608 for a list of types not yet supported).

As a workaround, can you try with a `VARCHAR/NVARCHAR` column?

**Comment by git4rputuval** [comment]
Thanks @tsegismont. That was very fast.

**Steps**:
Changed NVARCHAR(MAX) to NVARCHAR(4000)

**Result**:
Failed initially with the following error:
[nationalized-error.txt](https://github.com/quarkusio/quarkus/files/7714939/nationalized-error.txt)

This is because we had coded "org.hibernate.annotations.Nationalized" as an annotation in the attribute definition alongside the "Column" annotation. This was again a test to get the code working. In other words, "@Nationalized" was never used in our codebase till we faced this issue.

Removed "@Nationalized" and things works!

**Rationale**:
We provided this info to let you know that "@Nationalized" is not working with Vertx clients" because it failed while identifying NVARCHAR columns, though the purpose of this annotation is to help the Java drivers to identify NVARCHAR columns and provide the appropriate JAVA SQL type.

Hope this helps.

**Request**:

We would love to retain the COLUMN definition as NVARCHAR(MAX). So following queries in this regard,

1. Can you provide us a latest date by which this issue may get fixed? We have a production GO-LIVE in the month of April-May 2022. Will it be ready by then?
2. This issue is found only in Vertx clients. Will this work fine in quarkus projects with imperative sql clients? If a tug of war appears in our decision to retain NVARCHAR(MAX), I would like to change our quarkus projects to use imperative sql clients instead of reactive-sql-clients. If this fails, I believe, Spring Boot is the last option.




We are proactively working on developing microservice components for a set of functional tables (tables belonging to a set of functions). If everything sails through smoothly, we can close this issue. Request you to keep this issue open for a month. In case, I am assured that there are no further issues, I will close the issue at the earliest.

**Comment by tsegismont** [comment]
@git4rputuval we need to enhance the MS SQL client upstream first and then include the fix in a subsequent Quarkus release

**Comment by git4rputuval** [comment]
Thanks. We have done some basic testing, and it is working fine. Closing this issue.
