### ISSUE TITLE
LocalVariablesSorter only accepts expanded frames error when using Quarkus Log in Panache entities

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#22157]
### Describe the bug

Having a Panache Entity defined as the following: 

```java
package org.acme;

import javax.persistence.Entity;

import io.quarkus.hibernate.orm.panache.PanacheEntity;
import io.quarkus.logging.Log;

@Entity
public class MyEntity extends PanacheEntity {
    
    public void something() {
        Log.info("Hi!");
    }
}
```

The following error happens when building the project:

```java
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.5.2.Final:build (default) on project fancyproject: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]     [error]: Build step io.quarkus.deployment.steps.ClassTransformingBuildStep#handleClassTransformation threw an exception: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: LocalVariablesSorter only accepts expanded frames (see ClassReader.EXPAND_FRAMES)
[ERROR]     at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:896)
[ERROR]     at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]     at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]     at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]     at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: LocalVariablesSorter only accepts expanded frames (see ClassReader.EXPAND_FRAMES)
[ERROR]     at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[ERROR]     at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[ERROR]     at io.quarkus.deployment.steps.ClassTransformingBuildStep.handleClassTransformation(ClassTransformingBuildStep.java:231)
[ERROR]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]     at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
[ERROR]     ... 6 more
[ERROR] Caused by: java.lang.IllegalArgumentException: LocalVariablesSorter only accepts expanded frames (see ClassReader.EXPAND_FRAMES)
[ERROR]     at org.objectweb.asm.commons.LocalVariablesSorter.visitFrame(LocalVariablesSorter.java:189)
[ERROR]     at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2075)
[ERROR]     at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514)
[ERROR]     at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
[ERROR]     at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
[ERROR]     at io.quarkus.hibernate.orm.deployment.HibernateEntityEnhancer$HibernateEnhancingClassVisitor.visitEnd(HibernateEntityEnhancer.java:81)
[ERROR]     at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:377)
[ERROR]     at io.quarkus.panache.common.deployment.visitors.PanacheEntityClassAccessorGenerationVisitor.visitEnd(PanacheEntityClassAccessorGenerationVisitor.java:111)
[ERROR]     at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:377)
[ERROR]     at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:377)
[ERROR]     at io.quarkus.panache.common.deployment.visitors.PanacheEntityClassOperationGenerationVisitor.visitEnd(PanacheEntityClassOperationGenerationVisitor.java:121)
[ERROR]     at org.objectweb.asm.ClassReader.accept(ClassReader.java:748)
[ERROR]     at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
[ERROR]     at io.quarkus.deployment.steps.ClassTransformingBuildStep.transformClass(ClassTransformingBuildStep.java:317)
[ERROR]     at io.quarkus.deployment.steps.ClassTransformingBuildStep$2.call(ClassTransformingBuildStep.java:204)
[ERROR]     at io.quarkus.deployment.steps.ClassTransformingBuildStep$2.call(ClassTransformingBuildStep.java:191)
[ERROR]     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[ERROR]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[ERROR]     at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### Expected behavior

No build errors

### Actual behavior

Build error

### How to Reproduce?

1. Create a project using hibernate-orm-panache (and any jdbc extension): https://code.quarkus.io/d?e=hibernate-orm-panache&e=jdbc-postgresql&cn=code.quarkus.io
2. Create an entity as in this issue description
3. Run `mvn clean package`

### Output of `uname -a` or `ver`

Fedora 35

### Output of `java -version`

JDK 17

### Quarkus version or git rev

2.5.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

**Comment by gsmet** [comment]
/cc @Ladicek 
My guess is that all the bytecode transformers will require `.setClassReaderOptions(ClassReader.EXPAND_FRAMES)` given they potentially can work on a class that contains a logger.

**Comment by FroMage** [comment]
Looks like it, yeah.

**Comment by Ladicek** [comment]
I'd expect that https://github.com/quarkusio/quarkus/pull/20664 fixed that, so this might be a regression somewhere. I'll check.

**Comment by Ladicek** [comment]
OK so the issue is that `HibernateEntityEnhancer` needs to break the chain of class visitors to be able to call into the Hibernate API. To be able to pretend that it's still a regular `ClassVisitor`, it serializes the intermediate state to a `byte[]`, runs the Hibernate transformer, and then builds a whole new `ClassReader` to continue in the original chain. The new `ClassReader` is missing the options set on the original `ClassReader`.

I need to figure out a way how to propagate those options, because setting `EXPAND_FRAMES` for everything is a waste of resources.

**Comment by Ladicek** [comment]
Thinking out loud: a `ThreadLocal` would work, but something better would be, well, better :-)

**Comment by Ladicek** [comment]
Found a decent way to pass around those data. #22734 should fix this.

**Comment by paradoxrevolver** [comment]
i've just encountered this exact same error (in Quarkus 2.6.2 Final) but for Panache Repositories. the conditions that cause the error are identical to what's described here, so i'm unsure if i should write a new issue. let me know if one is wanted for proper record keeping.

for a similar rough example of what causes the error:

```java
package org.acme;

import io.quarkus.hibernate.orm.panache.PanacheEntity;
import io.quarkus.hibernate.orm.panache.PanacheRepository;
import io.quarkus.logging.Log;

public class MyRepository extends PanacheRepository<PanacheEntity> {
    public void something() {
        Log.info("Hi!");
    }
}
```

**Comment by Ladicek** [comment]
@paradoxrevolver I'm afraid I can't reproduce that. If you have a standalone (ideally minimal) reproducer somewhere, I'd love to take a look.

**Comment by paradoxrevolver** [comment]
@Ladicek thank you for such a quick response! you're right, i was also unable to reproduce it starting with https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-orm-panache-quickstart. i suspect i'll encounter this error again as i work on this project. when i do, i'll create a new issue with more information and make a reproducer for it (if there's any formal process to making a reproducer, let me know).

**Comment by Ladicek** [comment]
@paradoxrevolver Nothing formal, any repo on GitHub (or a .zip attachment in this issue) will do. Thanks!
