### ISSUE TITLE
NPE in SmallRyeGraphQLProcessor#buildExecutionService when using quarkus-smallrye-graphql and quarkus-jdbc-oracle

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#22158]
### Describe the bug

NPE in SmallRyeGraphQLProcessor#buildExecutionService when using `quarkus-smallrye-graphql` and `quarkus-jdbc-oracle`

Regression in Quarkus 2.5.2.Final.

```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor#buildExecutionService threw an exception: java.lang.NullPointerException: Cannot read the array length because "buf" is null
	at java.base/java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:108)
	at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:200)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

Application compiles

### Actual behavior

Build fails

### How to Reproduce?

Create application with quarkus-smallrye-graphql and quarkus-jdbc-oracle
e.g. https://code.quarkus.io/api/download?s=jjB.H95
or have this defined in your project:
```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-graphql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-oracle</artifactId>
    </dependency>
```

Run `mvn quarkus:dev` or `mvn clean verify` to see the error

Running `mvn clean verify -Dquarkus.platform.version=2.5.1.Final` works fine

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.5.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by rsvoboda** [comment]
Also cc @Sanne for Oracle part

**Comment by jmartisk** [comment]
The problem seems to be that the Oracle processor produces a `RemovedResourceBuildItem`: https://github.com/quarkusio/quarkus/blob/2.5.2.Final/extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleMetadataOverrides.java#L111 which leads to producing a `TransformedClassesBuildItem` that has a transformed class with null classname (see https://github.com/quarkusio/quarkus/blob/2.5.2.Final/core/deployment/src/main/java/io/quarkus/deployment/steps/ClassTransformingBuildStep.java#L273).

I believe the fix is to add a null-check in the SmallRye processor and ignore empty transformed classes, don't attempt to index them. I'll get a PR up

**Comment by geoand** [comment]
Hm... I wonder whether this will come up again in other places. But let's get the initial fix in for now

**Comment by jmartisk** [comment]
> Hm... I wonder whether this will come up again in other places. But let's get the initial fix in for now

I didn't find any other extension injecting a `TransformedClassesBuildItem` right now, so it seems unlikely. In the future, if an extension starts using that, it needs to be able to deal with null classes in it.

**Comment by Sanne** [comment]
Thanks! I was wondering why Oracle specifically :)

+1 for the approach
