### ISSUE TITLE
Native mode - ClassCastException: org.jboss.threads.JBossThread cannot be cast to java.lang.Thread

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2218]
java.lang.ClassCastException on app shutdown with websocket

Quarkus: 0.14.0
GraalVM: 1.0.0-rc-15
Application: https://github.com/burrsutter/quarkusfingerpaint ++ Quarkus version update

Error is not thrown each time, best way for me was to open 2 tabs with http://127.0.0.1:8080/ URL, do some drawing and shutdown the app. 

```
target/quarkusfingerpaint-1.0.0-runner
2019-04-25 13:49:37,655 INFO  [io.quarkus] (main) Quarkus 0.14.0 started in 0.007s. Listening on: http://[::]:8080
2019-04-25 13:49:37,658 INFO  [io.quarkus] (main) Installed features: [cdi, smallrye-health, undertow-websockets]
2019-04-25 13:49:41,349 INFO  [org.acm.web.WebSocket] (executor-thread-1) onOpen: 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:42,220 INFO  [org.acm.web.WebSocket] (executor-thread-1) onOpen: 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:43,652 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:45,539 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:47,636 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:50,749 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-9) message FROM 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:52,635 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-9) message FROM 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:53,196 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-9) message FROM 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:56,252 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-16) message FROM 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
^C2019-04-25 13:49:59,359 INFO  [org.acm.web.WebSocket] (main) onClose: 5d869dcb-eb1c-480e-bc41-ed9f155f7d76
2019-04-25 13:49:59,359 INFO  [org.acm.web.WebSocket] (main) onClose: 6eb814e0-ef34-4eee-afad-70dab302e4e1
2019-04-25 13:49:59,360 INFO  [io.quarkus] (main) Quarkus stopped in 0.001s
2019-04-25 13:49:59,360 ERROR [org.jbo.exe.uncaught] (executor-thread-1) Thread Thread[executor-thread-1,5,executor] threw an uncaught exception: java.lang.ClassCastException: org.jboss.threads.JBossThread cannot be cast to java.lang.Thread
	at org.jboss.threads.ThreadLocalResettingRunnable$Resetter.run(Substitutions.java:47)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:34)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by rsvoboda** [comment]
I noticed `java.lang.ClassCastException: org.jboss.threads.JBossThread cannot be cast to java.lang.Thread` also with https://github.com/burrsutter/quarkus-todo-app running in native mode.

I saw the error in console when I did page reload or opened new tab with http://localhost:8080/todo.html#/all URL. Of cause not 100% reproducible ...

Running on macOS (target/todo-backend-1.0-SNAPSHOT-runner: Mach-O 64-bit executable x86_64)

**Comment by dmlloyd** [comment]
This has to be an issue in Substrate. There are no class loaders and `JBossThread` definitely extends `Thread` so there must be some type-comparison bug.

**Comment by dmlloyd** [comment]
It probably is related to substitutions somehow...

**Comment by sberyozkin** [comment]
Got the same problem (ClassCastException after terminating the native exec) with the latest Quarkus build

**Comment by rsvoboda** [comment]
Problem is present with 1.0.0-rc-16 too.

**Comment by rsvoboda** [comment]
Comments are focused on native part so I split this issue, XNIO issue lives in #2225

**Comment by rsvoboda** [comment]
I tried quarkus-todo-app ++ Quarkus 0.13.3 ++ GraalVM 1.0.0-rc-16 and I DON'T see the issue.

**Comment by gsmet** [comment]
To reproduce this issue:
- get latest Quarkus `master` branch
- `mvn clean install -DskipTests -DskipITs`
- get latest quickstarts `development` branch
- `cd using-opentracing`
- `mvn clean install -Pnative`
- `./target/using-opentracing-1.0-SNAPSHOT-runner`
- in another shell `curl http://localhost:8080/chain`
- go back to previous shell, you should see:
```
2019-05-01 13:16:44,636 ERROR [org.jbo.exe.uncaught] (executor-thread-1) Thread Thread[executor-thread-1,5,executor] threw an uncaught exception: java.lang.ClassCastException
	at org.jboss.threads.ThreadLocalResettingRunnable$Resetter.run(Substitutions.java:60)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:34)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```
`JBossThread` inherits from a `java.lang.Thread` class that is different from the one we try to cast it to.

**Comment by dmlloyd** [comment]
Minimal reproducer: https://github.com/oracle/graal/issues/1200#issuecomment-492315564
