### ISSUE TITLE
RESTEasy Reactive: server exception mapper in endpoint makes CDI scopes clash

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22211]
### Describe the bug

I tried to add a `@ServerExceptionMapper` method in an endpoint, and was rewarded with this exception:

```
javax.enterprise.inject.spi.DefinitionException: Bean class rest.Login declares multiple scope type annotations: javax.inject.Singleton, javax.enterprise.context.RequestScoped
```

I'm guessing that RR adds those two scopes in different places, and they clash.

**Comment by geoand** [comment]
Can you add a code sample that causes this?

**Comment by FroMage** [comment]
That would be nice, wouldn't it ;)

**Comment by FroMage** [comment]
This is enough to exhibit the problem:

```java
public class Application extends Controller {

    @ServerExceptionMapper
    public Response mapIt(RuntimeException x) {
        return null;
    }
}
```

This is probably due to a conflict in `RenardeProcessor` which adds `@RequestScoped` to any endpoint extending `Controller`:

```java
        arcTransformers.produce(new io.quarkus.arc.deployment.AnnotationsTransformerBuildItem(
                new io.quarkus.arc.processor.AnnotationsTransformer() {
                    @Override
                    public void transform(TransformationContext transformationContext) {
                        if (transformationContext.isClass()
                                && controllers.contains(transformationContext.getTarget().asClass().name())) {
                            // FIXME: probably don't add a scope annotation if it has one already?
                            transformationContext.transform().add(ResteasyReactiveDotNames.REQUEST_SCOPED)
                                    .done();
                        }
```

I do like the fact that there's a `FIXME` there ;)

But even then, why are we adding a `@ApplicationScoped` annotation on the endpoint if we have a `@ServerExceptionMapper` method? And how are we doing this? Also via an `AnnotationsTransformer`? I wonder if they will clash.

**Comment by mkouba** [comment]
> But even then, why are we adding a @ApplicationScoped annotation on the endpoint if we have a @ServerExceptionMapper method? And how are we doing this? Also via an AnnotationsTransformer? I wonder if they will clash.

If scope is the only thing you need to add then I'd recommend you to use the [`io.quarkus.arc.deployment.AutoAddScopeBuildItem`](https://quarkus.io/guides/cdi-integration#reason-2-class-is-discovered-but-has-no-bean-defining-annotation) instead. However, it does not solve conflicts and thus you bean may end with random scope used (depends on which build step is called first), so you might need to specify the priority `AnnotationsTransformer#getPriority()` and consume the `io.quarkus.arc.deployment.CustomScopeAnnotationsBuildItem` to test the presence of a scope annotation like here: https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/AutoAddScopeProcessor.java#L51

We could add the priority to the `AutoAddScopeBuildItem` though...

**Comment by geoand** [comment]
I like your idea @mkouba

**Comment by mkouba** [comment]
> I like your idea @mkouba

PR sent: https://github.com/quarkusio/quarkus/pull/22253

**Comment by geoand** [comment]
So can we close this?

**Comment by mkouba** [comment]
> So can we close this?

I'm not sure - the https://github.com/quarkusio/quarkus/pull/22253 does not touch the RESTEasy Reactive/Renarde part...

**Comment by geoand** [comment]
Is this still an issue?

**Comment by mkouba** [comment]
> Is this still an issue?

It does not seem to be fixed in Renarde: https://github.com/quarkiverse/quarkus-renarde/blob/1.0.4/deployment/src/main/java/io/quarkiverse/renarde/deployment/RenardeProcessor.java#L387-L411

CC @FroMage

**Comment by FroMage** [comment]
Hum, so I guess I have to fix this on my side now…

**Comment by FroMage** [comment]
It appears RESTEasy Reactive adds this scope in `ResteasyReactiveScanningProcessor`:

```java
        for (AnnotationInstance instance : index
                .getAnnotations(ResteasyReactiveDotNames.SERVER_EXCEPTION_MAPPER)) {
            if (instance.target().kind() != AnnotationTarget.Kind.METHOD) {
                continue;
            }
            MethodInfo methodInfo = instance.target().asMethod();
            if (classLevelExceptionMappers.contains(methodInfo)) { // methods annotated with @ServerExceptionMapper that exist inside a Resource Class are handled differently
                continue;
            }
            // the user class itself is made to be a bean as we want the user to be able to declare dependencies
            additionalBeans.addBeanClass(methodInfo.declaringClass().name().toString());
            Map<String, String> generatedClassNames = ServerExceptionMapperGenerator.generateGlobalMapper(methodInfo,
                    new GeneratedBeanGizmoAdaptor(generatedBean),
                    Set.of(HTTP_SERVER_REQUEST, HTTP_SERVER_RESPONSE, ROUTING_CONTEXT), Set.of(Unremovable.class.getName()));
            for (Map.Entry<String, String> entry : generatedClassNames.entrySet()) {
                ExceptionMapperBuildItem.Builder builder = new ExceptionMapperBuildItem.Builder(entry.getValue(),
                        entry.getKey()).setRegisterAsBean(false);// it has already been made a bean
                AnnotationValue priorityValue = instance.value("priority");
                if (priorityValue != null) {
                    builder.setPriority(priorityValue.asInt());
                }
                additionalExceptionMappers.produce(builder.build());
            }
        }

        additionalBean.produce(additionalBeans.setUnremovable().setDefaultScope(DotNames.SINGLETON).build());
```

**Comment by FroMage** [comment]
The exception is actually this:

```
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: javax.enterprise.inject.spi.DefinitionException: Bean class rest.Application declares multiple scope type annotations: javax.enterprise.context.RequestScoped, javax.inject.Singleton
```

So, turns out I still can't fix this in Renarde. Perhaps it's RESTEasy Reactive that needs to do something? Or is this an Arc problem?

**Comment by manovotn** [comment]
> AnnotationsTransformer that added the annotation, I assumed it's not needed anymore, but not so sure anymore now.

You shouldn't need annotation transformer with current approach. The idea of `AutoAddScopeBuildItem` is that it sets a default which is only used when there is no other scope defined.
You *could* use annotation transformation instead, but then you'd need to check of other annotation is already present.

> So, turns out I still can't fix this in Renarde. Perhaps it's RESTEasy Reactive that needs to do something? Or is this an Arc problem?

The way [Arc processes default scopes](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcProcessor.java#L215-L228) doesn't seem to allow for a clash - you'd just override one default with another. My guess is there are other places that try to add the scope via annotation transformation and those are causing the clash.

**Comment by mkouba** [comment]
Matej is right that the default scope should be just ignored if you produce an `AutoAddScopeBuildItem`, it's because it is added by an annotation transformer with default priority and `AutoAddScopeBuildItem`s are implemented by an annotation processor with priority `DEFAULT_PRIORITY + 1000`. Both transformers skip classes annotated with a scope.

@FroMage do you have a branch I could try?

**Comment by FroMage** [comment]
Yes: https://github.com/quarkiverse/quarkus-renarde/tree/22211

`mvn clean install` will produce this issue:

```
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ quarkus-renarde-integration-tests ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkiverse.renarde.it.RenardeBackofficeTest
2022-11-22 11:19:58,378 INFO  [io.qua.dev.h2.dep.H2DevServicesProcessor] (build-2) Dev Services for H2 started.
2022-11-22 11:19:58,384 INFO  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-2) Dev Services for the default datasource (h2) started.
2022-11-22 11:19:58,385 INFO  [io.qua.hib.orm.dep.HibernateOrmProcessor] (build-4) Setting quarkus.hibernate-orm.database.generation=drop-and-create to initialize Dev Services managed database
2022-11-22 11:19:58,617 INFO  [io.qua.ren.dep.RenardeProcessor] (build-18) Generating private/public keys for DEV/TEST in /home/stephane/src/java-eclipse/quarkus-renarde/integration-tests/target/classes/dev.privateKey.pem and /home/stephane/src/java-eclipse/quarkus-renarde/integration-tests/target/classes/dev.publicKey.pem
[ERROR] Tests run: 7, Failures: 0, Errors: 1, Skipped: 6, Time elapsed: 3.669 s <<< FAILURE! - in io.quarkiverse.renarde.it.RenardeBackofficeTest
[ERROR] testBackofficeExampleEntityIndex  Time elapsed: 0.01 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: javax.enterprise.inject.spi.DefinitionException: Bean class rest.Application declares multiple scope type annotations: javax.enterprise.context.RequestScoped, javax.inject.Singleton
	at io.quarkus.arc.processor.Beans.multipleScopesFound(Beans.java:315)
	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1072)
	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:48)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1024)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:252)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:129)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:434)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:714)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:785)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: javax.enterprise.inject.spi.DefinitionException: Bean class rest.Application declares multiple scope type annotations: javax.enterprise.context.RequestScoped, javax.inject.Singleton
	at io.quarkus.arc.processor.Beans.multipleScopesFound(Beans.java:315)
	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1072)
	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:48)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1024)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:252)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:129)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:434)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:237)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:681)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:729)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	... 36 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: javax.enterprise.inject.spi.DefinitionException: Bean class rest.Application declares multiple scope type annotations: javax.enterprise.context.RequestScoped, javax.inject.Singleton
	at io.quarkus.arc.processor.Beans.multipleScopesFound(Beans.java:315)
	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1072)
	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:48)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1024)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:252)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:129)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:434)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	... 47 more
Caused by: javax.enterprise.inject.spi.DefinitionException: Bean class rest.Application declares multiple scope type annotations: javax.enterprise.context.RequestScoped, javax.inject.Singleton
	at io.quarkus.arc.processor.Beans.multipleScopesFound(Beans.java:315)
	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1072)
	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:48)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1024)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:252)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:129)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:434)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

[INFO] Running io.quarkiverse.renarde.it.RenardeResourceTest
[WARNING] Tests run: 7, Failures: 0, Errors: 0, Skipped: 7, Time elapsed: 0.002 s - in io.quarkiverse.renarde.it.RenardeResourceTest

```

**Comment by manovotn** [comment]
From the current code, it looks like `@RequestScoped` is coming from `RenardeProcessor` via `AutoAddScopeBuildItem`.
The `@Singleton` is indeed a default scope coming from RR processor (`ResteasyReactiveScanningProcessor`) via `AdditionalBeanBuildItem`.

When Arc processes the default scope addition (here), it doesn't check if there is a non-custom scope already present.

**Comment by manovotn** [comment]
@FroMage please take a look at https://github.com/quarkusio/quarkus/pull/29407 and if possible test with that.

**Comment by manovotn** [comment]
@FroMage closing this issue as my PR fixes the scope clash problem. Feel free to reopen if there is anything else
