### ISSUE TITLE
NPE while starting an application with @Incoming method

### ISSUE THREAD

**Issue by jpechane** [quarkusio/quarkus#2221]
When an application contains method annotated with `@Incoming` method to read Kafka topic the application fails to start with stacktrace
```
2019-04-25 06:32:07,760 ERROR [io.sma.rea.mes.imp.LegacyConfiguredStreamFactory] (main) Unable to create the publisher or subscriber during initialization: java.lang.NullPointerException
	at io.vertx.reactivex.kafka.client.consumer.KafkaConsumer.create(KafkaConsumer.java:131)
	at io.smallrye.reactive.messaging.kafka.KafkaSource.<init>(KafkaSource.java:37)
	at io.smallrye.reactive.messaging.kafka.KafkaMessagingProvider.getPublisherBuilder(KafkaMessagingProvider.java:40)
	at io.smallrye.reactive.messaging.kafka.KafkaMessagingProvider_ClientProxy.getPublisherBuilder(Unknown Source)
	at io.smallrye.reactive.messaging.impl.LegacyConfiguredStreamFactory.createPublisherBuilder(LegacyConfiguredStreamFactory.java:119)
	at io.smallrye.reactive.messaging.impl.LegacyConfiguredStreamFactory.lambda$initialize$2(LegacyConfiguredStreamFactory.java:100)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.smallrye.reactive.messaging.impl.LegacyConfiguredStreamFactory.initialize(LegacyConfiguredStreamFactory.java:100)
	at io.smallrye.reactive.messaging.impl.LegacyConfiguredStreamFactory_ClientProxy.initialize(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:103)
	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:18)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(Unknown Source)
	at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:244)
	at io.quarkus.arc.EventImpl.fire(EventImpl.java:85)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:39)
	at io.quarkus.arc.runtime.ArcDeploymentTemplate.handleLifecycleEvents(ArcDeploymentTemplate.java:115)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent7.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:99)
	at io.quarkus.runtime.Application.run(Application.java:206)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```
If the dependency
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
```
is added even if RESTeasy is not used then the NPE disappears and app starts correctly.

Looking at the code it seems that vert.x instance is not `@Inject`ed at time when Kafka consumer is initialized.

**Comment by gsmet** [comment]
@jpechane any chance you could put together a simple test case?

**Comment by jpechane** [comment]
Just remove resteasy dependency from https://github.com/jpechane/strimzi-lab/tree/ticket-msa-quarkus/ticket-msa-rhs2019/invoice
Please ignore readme content, it is not updated yet.

**Comment by cescoffier** [comment]
Odd, but if the resteasy dependency is not there, then there is no injected vertx instance. Need to look into this with @mkouba.

**Comment by mkouba** [comment]
It seems that `SmallRyeReactiveMessagingLifecycle#onApplicationStart(StartupEvent)` is notified before Vertx is initialized. We need to produce a Vertx `ServiceStartBuildItem` to delay the notification. I'll send a PR shortly.

**Comment by gsmet** [comment]
Closed via https://github.com/quarkusio/quarkus/pull/2418 .
