### ISSUE TITLE
Native compiling failing when smallrye-jwt dep is present

### ISSUE THREAD

**Issue by sebastienblanc** [quarkusio/quarkus#2222]
Hi ! 
I just found out that I can not compile to native when using `smallrye-jwt` , I think the team is aware of it since the native profile has been disabled for the jwt quickstart : https://github.com/quarkusio/quarkus-quickstarts/commit/6e4d30909b6e78c12ddb9c01e917f6af5f60ec9e#diff-ccc624a5f8d12aebdcfbe1d5a9e7a763

But I can not find the related issue or will it be fixed with https://github.com/quarkusio/quarkus/issues/1844 ?

**Comment by starksm64** [comment]
It is working in 13.2 as I'm testing a demo against it. I'm not sure why an issue was not raised before commenting out the quickstarts. The PR for #1844 has already been merged and is in master. What is the error you are seeing?

**Comment by sebastienblanc** [comment]
Oh I forgot to say I tested with 0.14 not against master , will try against
master when I got back in front of the computer

Le jeu. 25 avr. 2019 à 16:19, Scott M Stark <notifications@github.com> a
écrit :

**Comment by starksm64** [comment]
Note that I did update my quarkus branch to the current master and built it, updated my demo to use it and I am able to build and run. This is using all of the smallrye-* extensions:

```java
Scotts-iMacPro:Qproj4MP starksm$ ./target/demo-runner -Dinjected.value="Runtime Value" -Dhealth.freeSpaceThreshold=1073741824 -Dhealth.pathToMonitor=/Users/starksm
onStart, event=io.quarkus.runtime.StartupEvent@107b8ea08
07:34:43 INFO  [io.quarkus]] (main) Quarkus 999-SNAPSHOT started in 0.007s. Listening on: http://[::]:8080
07:34:43 INFO  [io.quarkus]] (main) Installed features: [cdi, resteasy, resteasy-jsonb, security, smallrye-fault-tolerance, smallrye-health, smallrye-jwt, smallrye-metrics, smallrye-openapi, smallrye-rest-client]
```

**Comment by starksm64** [comment]
It does not look like 0.14 is fully synced to the mirrors and it is blowing up very early with bad poms:

```bash
Scotts-iMacPro:Qproj4MP starksm$ mvn clean package -Pnative
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-bom/0.14/quarkus-bom-0.14.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.rest-assured:rest-assured:jar -> duplicate declaration of version (?) @ line 69, column 17
[ERROR] Non-resolvable import POM: Could not find artifact io.quarkus:quarkus-bom:pom:0.14 in central (https://repo.maven.apache.org/maven2) @ line 17, column 19
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-resteasy:jar is missing. @ line 27, column 17
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-junit5:jar is missing. @ line 31, column 17
[ERROR] 'dependencies.dependency.version' for io.rest-assured:rest-assured:jar is missing. @ line 69, column 17
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-fault-tolerance:jar is missing. @ line 41, column 17
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-health:jar is missing. @ line 45, column 17
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-jwt:jar is missing. @ line 49, column 17
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-resteasy-jsonb:jar is missing. @ line 53, column 17
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-metrics:jar is missing. @ line 57, column 17
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-openapi:jar is missing. @ line 61, column 17
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-rest-client:jar is missing. @ line 65, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.example:demo:1.0-SNAPSHOT (/Users/starksm/Documents/RedHat/Quarkus/GOTO_2019/Qproj4MP/pom.xml) has 11 errors
[ERROR]     Non-resolvable import POM: Could not find artifact io.quarkus:quarkus-bom:pom:0.14 in central (https://repo.maven.apache.org/maven2) @ line 17, column 19 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-resteasy:jar is missing. @ line 27, column 17
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-junit5:jar is missing. @ line 31, column 17
[ERROR]     'dependencies.dependency.version' for io.rest-assured:rest-assured:jar is missing. @ line 69, column 17
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-fault-tolerance:jar is missing. @ line 41, column 17
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-health:jar is missing. @ line 45, column 17
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-jwt:jar is missing. @ line 49, column 17
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-resteasy-jsonb:jar is missing. @ line 53, column 17
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-metrics:jar is missing. @ line 57, column 17
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-openapi:jar is missing. @ line 61, column 17
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-rest-client:jar is missing. @ line 65, column 17
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by gsmet** [comment]
It's 0.14.0, not 0.14. Please ping me if it doesn't solve your issue as I would have to dig what's going on quickly.

**Comment by gsmet** [comment]
@starksm64 ^

**Comment by starksm64** [comment]
@gsmet , ok, that is also building and running fine:

```bash
[demo-runner:57576]   (typeflow):   9,742.13 ms
[demo-runner:57576]    (objects):  19,281.56 ms
[demo-runner:57576]   (features):     733.98 ms
[demo-runner:57576]     analysis:  31,088.56 ms
Printing call tree to /Users/starksm/Documents/RedHat/Quarkus/GOTO_2019/Qproj4MP/target/reports/call_tree_demo-runner_20190425_074752.txt
Printing list of used classes to /Users/starksm/Documents/RedHat/Quarkus/GOTO_2019/Qproj4MP/target/reports/used_classes_demo-runner_20190425_074754.txt
Printing list of used packages to /Users/starksm/Documents/RedHat/Quarkus/GOTO_2019/Qproj4MP/target/reports/used_packages_demo-runner_20190425_074754.txt
[demo-runner:57576]     universe:     841.22 ms
[demo-runner:57576]      (parse):   1,131.68 ms
[demo-runner:57576]     (inline):   3,092.73 ms
[demo-runner:57576]    (compile):  10,077.76 ms
[demo-runner:57576]      compile:  16,208.26 ms
[demo-runner:57576]        image:   4,430.68 ms
[demo-runner:57576]        write:   1,810.56 ms
[demo-runner:57576]      [total]:  72,052.04 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:35 min
[INFO] Finished at: 2019-04-25T07:48:18-07:00
[INFO] ------------------------------------------------------------------------
Scotts-iMacPro:Qproj4MP starksm$ ./target/demo-runner -Dinjected.value="Runtime Value" -Dhealth.freeSpaceThreshold=1073741824 -Dhealth.pathToMonitor=/Users/starksm
onStart, event=io.quarkus.runtime.StartupEvent@10bb8ea18
07:48:28 INFO  [io.quarkus]] (main) Quarkus 0.14.0 started in 0.008s. Listening on: http://[::]:8080
07:48:28 INFO  [io.quarkus]] (main) Installed features: [cdi, resteasy, resteasy-jsonb, security, smallrye-fault-tolerance, smallrye-health, smallrye-jwt, smallrye-metrics, smallrye-openapi, smallrye-rest-client]
```

**Comment by sebastienblanc** [comment]
Hum indeed , it's working for the official quickstart, it's something in my project then ... But it still fails only if I add `smallrye-jwt` : 
```
Error: Class initialization failed: io.quarkus.runner.ApplicationImpl1
Detailed message:

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```
https://github.com/sebastienblanc/quarkus-quickstart/tree/master/quarkus-rest-caps

**Comment by starksm64** [comment]
Ok, I see the same on your project. Add the -H:+ReportExceptionStackTraces flag to get more info:

```diff
Scotts-iMacPro:quarkus-rest-caps starksm$ git diff
diff --git a/quarkus-rest-caps/pom.xml b/quarkus-rest-caps/pom.xml
index 6426041..005a34c 100644
--- a/quarkus-rest-caps/pom.xml
+++ b/quarkus-rest-caps/pom.xml
@@ -78,6 +78,7 @@
                 </goals>
                 <configuration>
                   <enableHttpUrlHandler>true</enableHttpUrlHandler>
+                  <additionalBuildArgs>-H:+ReportExceptionStackTraces</additionalBuildArgs>
                 </configuration>
               </execution>
             </executions>
@@ -103,4 +104,4 @@
       </build>
     </profile>
   </profiles>
-</project> 
```

and then it shows it is due to a missing class:

```bash
Caused by: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.registerProvider(ResteasyDeploymentImpl.java:630)
	... 50 more
```

**Comment by sebastienblanc** [comment]
I see, I need to add `quarkus-resteasy-jsonb` but it's only needed for native , so is this an expected behavior or a bug ;) ?

**Comment by starksm64** [comment]
I can't see how it would be an expected behavior. I guess the question is why it would happen. I certainly would call it a bug at this point. Some extension is not declaring the dependency adequately to the native layer. Is this a possible dead code elimination issue that requires SVM specific call?

**Comment by sebastienblanc** [comment]
Should I open a separate issue for this ?

**Comment by emmanuelbernard** [comment]
@starksm64 do you want to investigate the DCE hypothesis? Otherwise @kenfinnigan can you take that one?

**Comment by kenfinnigan** [comment]
Is it just that `quarkus-smallrye-jwt` needs to have a dependency on `quarkus-jsonb`, or `quarkus-resteasy-jsonb`?

**Comment by sebastienblanc** [comment]
`quarkus-resteasy-jsonb`

**Comment by kenfinnigan** [comment]
`quarkus-jsonb` doesn't work?

**Comment by sebastienblanc** [comment]
No, I just tried to compile natively with just adding `quarkus-jsonb` but it fails.

**Comment by kenfinnigan** [comment]
That's really weird, as the reflective access for `JsonBindingProvider` is added in `quarkus-jsonb`, which `quarkus-resteasy-jsonb` depends on

**Comment by kenfinnigan** [comment]
Can you verify if this is still a problem?

I think JWT in Native issues are all fixed

**Comment by saurabh256** [comment]
Is this issue fixed? I am still facing native build issues with the quarkus security-jwt-quickstart during native build. Irrespective of whether I use jwt feature or not but even if it is available in pom i get error which building in native mode. 

Quarkus version as below (from pom) 
```
  <properties>
    <surefire-plugin.version>2.22.1</surefire-plugin.version>
    <quarkus-plugin.version>1.4.2.Final</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>1.4.2.Final</quarkus.platform.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
```

GRAALVM - graalvm-ce-java11-20.0.0
OS - Mac OS -Mojave 10.14.6

Even if i try building it under docker container then i get same error as below

```
Caused by: java.lang.RuntimeException: Error checking value of member method since on interface java.lang.Deprecated
	at javax.enterprise.util.AnnotationLiteral.invoke(AnnotationLiteral.java:291)
	at javax.enterprise.util.AnnotationLiteral.getMemberValue(AnnotationLiteral.java:276)
	at javax.enterprise.util.AnnotationLiteral.hashCode(AnnotationLiteral.java:246)
	at java.base/java.util.HashMap.hash(HashMap.java:339)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at java.base/java.util.HashSet.add(HashSet.java:220)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_Bean.<init>(JWTAuthContextInfoProvider_Bean.zig:3345)
	at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans1(Default_ComponentsProvider.zig:1212)
	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:38)
	at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:106)
	at io.quarkus.arc.Arc.initialize(Arc.java:20)
```
