### ISSUE TITLE
XNIO007007: Thread is terminating on app shutdown with websocket

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2225]
XNIO007007: Thread is terminating / java.lang.ClassCastException on shutdown with websocket

Quarkus: 0.14.0, 0.13.3
GraalVM: 1.0.0-rc-15
Application: https://github.com/burrsutter/quarkusfingerpaint ++ Quarkus version update

Error is visible when shutting down, in both jvm and native mode.
Quarkus 0.13.3 native shows XNIO007007 error.
Quarkus 0.14.0 native shows ClassCastException (probably hides XNIO007007) - see https://github.com/quarkusio/quarkus/issues/2218.
JVM mode for both Quarkus versions throws XNIO007007.

Error is not thrown each time, more often in native mode, ~50% chance for JVM mode.
Best way for me was to open 2 tabs with http://127.0.0.1:8080/ URL, do some drawing and shutdown the app.

```
java -jar target/quarkusfingerpaint-1.0.0-runner.jar
2019-04-25 13:50:45,711 WARN  [io.und.web.jsr] (main) UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2019-04-25 13:50:45,723 INFO  [io.und.web.jsr] (main) UT026003: Adding annotated server endpoint class org.acme.websocket.WebSocket for path /paint/{id}
2019-04-25 13:50:46,163 INFO  [io.quarkus] (main) Quarkus 0.14.0 started in 0.828s. Listening on: http://[::]:8080
2019-04-25 13:50:46,163 INFO  [io.quarkus] (main) Installed features: [cdi, smallrye-health, undertow-websockets]
2019-04-25 13:50:47,933 INFO  [org.acm.web.WebSocket] (executor-thread-1) onOpen: 4e5f3bd6-d3c6-44d0-b6f3-debdf6313e75
2019-04-25 13:50:48,815 INFO  [org.acm.web.WebSocket] (executor-thread-1) onOpen: ea927f1b-11ca-4493-99c4-4c4c6e2bf13d
2019-04-25 13:50:51,608 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-3) message FROM 4e5f3bd6-d3c6-44d0-b6f3-debdf6313e75
2019-04-25 13:50:53,258 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-3) message FROM 4e5f3bd6-d3c6-44d0-b6f3-debdf6313e75
2019-04-25 13:50:55,017 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-10) message FROM ea927f1b-11ca-4493-99c4-4c4c6e2bf13d
2019-04-25 13:50:56,500 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-10) message FROM ea927f1b-11ca-4493-99c4-4c4c6e2bf13d
2019-04-25 13:51:00,836 INFO  [org.acm.web.WebSocket] (XNIO-1 I/O-10) message FROM ea927f1b-11ca-4493-99c4-4c4c6e2bf13d
^C2019-04-25 13:51:02,445 INFO  [org.acm.web.WebSocket] (main) onClose: ea927f1b-11ca-4493-99c4-4c4c6e2bf13d
2019-04-25 13:51:02,445 INFO  [org.acm.web.WebSocket] (main) onClose: 4e5f3bd6-d3c6-44d0-b6f3-debdf6313e75
2019-04-25 13:51:02,451 ERROR [org.xni.listener] (XNIO-1 I/O-3) XNIO001007: A channel event listener threw an exception: java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating
	at org.xnio.nio.WorkerThread.execute(WorkerThread.java:620)
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:396)
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:388)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:1061)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:975)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.terminated(ReadReadyHandler.java:71)
	at org.xnio.nio.NioSocketConduit.readTerminated(NioSocketConduit.java:332)
	at org.xnio.nio.NioSocketConduit.terminateReads(NioSocketConduit.java:325)
	at io.undertow.conduits.IdleTimeoutConduit.terminateReads(IdleTimeoutConduit.java:236)
	at org.xnio.conduits.ConduitStreamSourceChannel.close(ConduitStreamSourceChannel.java:168)
	at org.xnio.IoUtils.safeClose(IoUtils.java:152)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.forceTermination(ReadReadyHandler.java:58)
	at org.xnio.nio.NioSocketConduit.forceTermination(NioSocketConduit.java:106)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:507)

2019-04-25 13:51:02,451 ERROR [org.xni.listener] (XNIO-1 I/O-10) XNIO001007: A channel event listener threw an exception: java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating
	at org.xnio.nio.WorkerThread.execute(WorkerThread.java:620)
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:396)
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:388)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:1061)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:975)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.terminated(ReadReadyHandler.java:71)
	at org.xnio.nio.NioSocketConduit.readTerminated(NioSocketConduit.java:332)
	at org.xnio.nio.NioSocketConduit.terminateReads(NioSocketConduit.java:325)
	at io.undertow.conduits.IdleTimeoutConduit.terminateReads(IdleTimeoutConduit.java:236)
	at org.xnio.conduits.ConduitStreamSourceChannel.close(ConduitStreamSourceChannel.java:168)
	at org.xnio.IoUtils.safeClose(IoUtils.java:152)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.forceTermination(ReadReadyHandler.java:58)
	at org.xnio.nio.NioSocketConduit.forceTermination(NioSocketConduit.java:106)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:507)

2019-04-25 13:51:02,454 INFO  [io.quarkus] (main) Quarkus stopped in 0.018s
```

**Comment by dmlloyd** [comment]
To resolve this issue it seems like we'd have to ensure that all open websockets are completely torn down before the web container exits.

**Comment by rsvoboda** [comment]
@emmanuelbernard I don't think `component:resteasy` is valid label here, websockets are handled by undertow.

**Comment by emmanuelbernard** [comment]
There is no undertow labelso I did my best. But I want to discuss a bit labels soon

**Comment by gsmet** [comment]
I think this has probably been solved by now. If not, please reopen.
