### ISSUE TITLE
Move quarkus.smallrye-openapi.* to a runtime config.

### ISSUE THREAD

**Issue by edufolly** [quarkusio/quarkus#22378]
### Discussed in https://github.com/quarkusio/quarkus/discussions/22280

<div type='discussions-op-text'>

<sup>Originally posted by **edufolly** December 16, 2021</sup>
The `quarkus.oidc.auth-server-url` is configured by an environment variable of the container, but `quarkus.smallrye-openapi.oauth2-implicit-token-url` is a configuration property fixed at build time.

Is it possible to change the Keycloak realm in swagger-ui at native mode?</div>

**Comment by phillip-kruger** [comment]
@edufolly - I had I look at this. It will be a big change to move this config to runtime. So what you can do is to configure it like this:
```
quarkus.smallrye-openapi.oauth2-implicit-token-url: ${MY_RUNTIME_REPLACEMENT:http://foobar.com/some/url}
```

Then, by default when you start the app, the url will be `http://foobar.com/some/url`

You can then also start like this: `mvn clean install quarkus:dev -DMY_RUNTIME_REPLACEMENT=http://bla.com`

Then the url will change in runtime.

Closing this for now, as this is the why to do this. Please reopen if this does not work for you

**Comment by phillip-kruger** [comment]
Ok hold on, above might still interpret the config at build time. For now you might need your own OASFilter. I'll reopen and look at this again.

**Comment by edufolly** [comment]
OK @phillip-kruger I'll try to create the OASFilter for now. Thanks!!

**Comment by edufolly** [comment]
Running on JVM works perfectly, but in native mode doesn't work.

```The exception```
```
2021-12-26 13:01:09,138 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-8) HTTP Request to /api/v1/swagger failed, error id: 079e49c4-2f1d-41c9-82c1-273302c9c884-2: io.smallrye.openapi.runtime.OpenApiRuntimeException: java.lang.ClassNotFoundException: io.anlix.utils.SwaggerFilter
	at io.smallrye.openapi.runtime.OpenApiProcessor.getFilter(OpenApiProcessor.java:180)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService$StaticDocument.<init>(OpenApiDocumentService.java:69)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService.<init>(OpenApiDocumentService.java:33)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.create(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:18)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.getDocument(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiHandler.handle(OpenApiHandler.java:72)
	at io.quarkus.smallrye.openapi.runtime.OpenApiHandler.handle(OpenApiHandler.java:19)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.ClassNotFoundException: io.anlix.utils.SwaggerFilter
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:53)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:139)
	at io.smallrye.openapi.runtime.OpenApiProcessor.getFilter(OpenApiProcessor.java:176)
	... 28 more
```

```application.properties```
```
# aix.realm is an environment variable. 
mp.openapi.filter=io.anlix.utils.SwaggerFilter
aix.authorization-url=https://my.keycloak/auth/realms/${aix.realm}/protocol/openid-connect/auth
aix.token-url=https://my.keycloak/auth/realms/${aix.realm}/protocol/openid-connect/token
aix.refresh-url=https://my.keycloak/auth/realms/${aix.realm}/protocol/openid-connect/refresh
```

```SwaggerFilter.java```
```java
@Unremovable
public class SwaggerFilter implements OASFilter {

    @Override
    public SecurityScheme filterSecurityScheme(SecurityScheme securityScheme) {

        OAuthFlow flow = securityScheme.getFlows().getImplicit();

        Config config = ConfigProvider.getConfig();

        Optional<String> authUrl = config
                .getOptionalValue("aix.authorization-url", String.class);

        authUrl.ifPresent(flow::setAuthorizationUrl);

        Optional<String> tokenUrl = config
                .getOptionalValue("aix.token-url", String.class);

        tokenUrl.ifPresent(flow::setTokenUrl);

        Optional<String> refreshUrl = config
                .getOptionalValue("aix.refresh-url", String.class);

        refreshUrl.ifPresent(flow::setRefreshUrl);

        return securityScheme;
    }

}
```

Am I doing something wrong?  The class `SwaggerFilter` is annotated with `@Unremovable` but cannot be found.

**Comment by edufolly** [comment]
I also have been tried to use the `quarkus.arc.unremovable-types=io.anlix.utils.SwaggerFilter` property without success.

**Comment by Postremus** [comment]
@phillip-kruger Did you get started on this topic? Otherwise; I need this feature, and would therefore implement this myself.

**Comment by phillip-kruger** [comment]
Nope. Not sure if we want to do this. But if you do a PR we can see what the code changes are

**Comment by Postremus** [comment]
Ok sounds like a plan!
