### ISSUE TITLE
 NoMessageBodyWriterFoundFailure when following KAFKA guide, part with channeling topic messages to SSE

### ISSUE THREAD

**Issue by marinvila** [quarkusio/quarkus#22424]
### Describe the bug

I attempted to write a topic output to SSE like described in https://quarkus.io/guides/kafka#receiving-messages-from-kafka

### Expected behavior

Expected to receive a stream of numbers to SSE.

### Actual behavior

500 (Internal Server Error) when opening SSE connection.

```
org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find MessageBodyWriter for response object of type: io.smallrye.mutiny.operators.multi.multicast.MultiConnectAfter of media type: text/event-stream;charset=UTF-8
	at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:125)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:135)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:90)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

Following the guide. 
wrote a small [index.html](http:localhost:8080/index.html) to establish sse connection and add received messages to the page.

[github.com:marinvila/kafka-to-sse](https://github.com/marinvila/kafka-to-sse)

### Output of `uname -a` or `ver`

Linux myplace 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12-Ubuntu-120.04) OpenJDK 64-Bit Server VM (build 17.0.1+12-Ubuntu-120.04, mixed mode, sharing)

### Quarkus version or git rev

2.5.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by cescoffier** [comment]
You need RestEasy reactive, instead of classic reactive. If you want to stay with classic, you need the RestEasy Mutiny extension.

**Comment by marinvila** [comment]
Thanks for your response.

Also `org.jboss.resteasy.reactive.RestSseElementType` needs to be used instead of `org.jboss.resteasy.annotations.SseElementType`.
And one of the `@Path("price")` is excess for intended purposes. 

Change to `quarkus-reactive` would necessitate adding `org.jboss.resteasy:resteasy-core-spi` as quarkus-resteasy brings `4.7.3.Final` to the scope for the code in this state to work. 

Other option is to add `quarkus-resteasy-mutiny`.

Great guide just needs a some love.

Regards.
