### ISSUE TITLE
Dev mode recompilation broken with kotlin 1.6 and the no-arg compiler plugin

### ISSUE THREAD

**Issue by languitar** [quarkusio/quarkus#22467]
### Describe the bug

Live recompilation of a kotlin project in dev mode is broken with kotlin >= 1.6 when using the no-arg compiler plugin for entities.

### Expected behavior

Entity changes are correctly recompiled and dev mode live testing continues to run after changes.

### Actual behavior

```
Unable to invoke Kotlin compiler. java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.ir.IrBuiltIns org.jetbrains.kotlin.backend.common.extensions.IrPluginContext.getIrBuiltIns()'
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.getOrGenerateNoArgConstructor(NoArgIrGenerationExtension.kt:79)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitClass(NoArgIrGenerationExtension.kt:54)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:44)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitClass(NoArgIrGenerationExtension.kt:39)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitClass(NoArgIrGenerationExtension.kt:39)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:55)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.acceptChildren(IrFileImpl.kt:84)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitElement(NoArgIrGenerationExtension.kt:47)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:30)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitPackageFragment(NoArgIrGenerationExtension.kt:39)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:37)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitFile(NoArgIrGenerationExtension.kt:39)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:38)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitFile(NoArgIrGenerationExtension.kt:39)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitFile(NoArgIrGenerationExtension.kt:39)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:81)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.acceptChildren(IrModuleFragmentImpl.kt:40)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitElement(NoArgIrGenerationExtension.kt:47)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:27)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitModuleFragment(NoArgIrGenerationExtension.kt:39)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:28)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitModuleFragment(NoArgIrGenerationExtension.kt:39)
	at org.jetbrains.kotlin.noarg.NoArgIrTransformer.visitModuleFragment(NoArgIrGenerationExtension.kt:39)
	at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:37)
	at org.jetbrains.kotlin.noarg.NoArgIrGenerationExtension.generate(NoArgIrGenerationExtension.kt:35)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda-1(JvmIrCodegenFactory.kt:126)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:89)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:146)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$default(JvmIrCodegenFactory.kt:64)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModule(JvmIrCodegenFactory.kt:59)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:321)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:56)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at io.quarkus.kotlin.deployment.KotlinCompilationProvider.compile(KotlinCompilationProvider.java:82)
	at io.quarkus.deployment.dev.QuarkusCompiler.compile(QuarkusCompiler.java:192)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:688)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.periodicTestCompile(RuntimeUpdatesProcessor.java:300)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor$2.handleChanges(RuntimeUpdatesProcessor.java:219)
	at io.quarkus.deployment.dev.filewatch.WatchServiceFileSystemWatcher.invokeCallback(WatchServiceFileSystemWatcher.java:230)
	at io.quarkus.deployment.dev.filewatch.WatchServiceFileSystemWatcher.run(WatchServiceFileSystemWatcher.java:138)
```

### How to Reproduce?

https://github.com/languitar/quarkus-kotlin-16-error contains a reproduction case.

1. Clone the repo
2. `mvn quarkus:dev`
3. Start continuous testing by pressing `r`
4. Uncomment [line 27 in `GreetingResource.kt`](https://github.com/languitar/quarkus-kotlin-16-error/blob/main/src/main/kotlin/org/acme/getting/started/GreetingResource.kt#L27) and save the file

### Output of `uname -a` or `ver`

Linux pres 5.10.87-1-lts #1 SMP Fri, 17 Dec 2021 10:43:27 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19

### Quarkus version or git rev

2.5.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by geoand** [comment]
Kotlin 1.6 will be supported in Quarkus `2.6` as can be seen from https://github.com/quarkusio/quarkus/pull/22223

**Comment by languitar** [comment]
Ah, I have searched the "Using Kotlin" documentation page on whether there is a range of supported Kotlin version but couldn't find anything in that regard. Maybe a disclaimer should be added there that the Kotlin version cannot be bumped freely? Another thing that I see is that with the separate maven property created in projects, how am I supposed to updated a project from an older version of Quarkus to a newer one? I would have to know which Kotlin version is compatible to update the maven project correctly.

**Comment by geoand** [comment]
Good points. I'll let @evanchooly and @gsmet sort that out

**Comment by languitar** [comment]
Maybe it would also be possible to dictate the Kotlin version using the bom?

**Comment by geoand** [comment]
The version is dictaed in the BOM, but the problem with BOMs is that you can't set Maven plugin versions unfortunately.

Also adding @gastaldi here because maybe the client side tooling can help here
