### ISSUE TITLE
Quarkus fails generating Avro sources when there are references between Avro documents

### ISSUE THREAD

**Issue by codependent** [quarkusio/quarkus#22464]
### Describe the bug

Avro supports referencing types from another documents, e.g.:

id.avsc
```
{
  "namespace": "com.codependent.avro",
  "type": "record",
  "name": "Id",
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "projectId",
      "type": "string"
    }
  ]
}
```

event-received.avsc
```
{
  "namespace": "com.codependent.avro",
  "type": "record",
  "name": "EventReceived",
  "fields": [
    {
      "name": "id",
      "type": "com.codependent.avro.Id"
    },
    {
      "name": "name",
      "type": "string"
    }
  ]
}

```

When building the Quarkus application I'm finding this error:

```
Caused by: org.apache.avro.SchemaParseException: "com.codependent.avro.Id" is not a defined name. The type of the "id" field must be a defined name or a {"type": ...} expression.
        at org.apache.avro.Schema.parse(Schema.java:1676)
        at org.apache.avro.Schema$Parser.parse(Schema.java:1433)
        at org.apache.avro.Schema$Parser.parse(Schema.java:1396)
        at io.quarkus.avro.deployment.AvroSchemaCodeGenProvider.compileSingleFile(AvroSchemaCodeGenProvider.java:50)
        at io.quarkus.avro.deployment.AvroCodeGenProviderBase.trigger(AvroCodeGenProviderBase.java:65)
        at io.quarkus.deployment.CodeGenerator.lambda$trigger$1(CodeGenerator.java:102)
        at io.quarkus.deployment.CodeGenerator.callWithClassloader(CodeGenerator.java:70)
        at io.quarkus.deployment.CodeGenerator.trigger(CodeGenerator.java:91)
        at io.quarkus.deployment.CodeGenerator.initAndRun(CodeGenerator.java:34)
        ... 122 more

```

### Expected behavior

The Quarkus build shoud correctly generate two Avro types Id.java and EventReceived.java

### Actual behavior

The build fails with: 

```
Caused by: org.apache.avro.SchemaParseException: "com.codependent.avro.Id" is not a defined name. The type of the "id" field must be a defined name or a {"type": ...} expression.
        at org.apache.avro.Schema.parse(Schema.java:1676)
        at org.apache.avro.Schema$Parser.parse(Schema.java:1433)
        at org.apache.avro.Schema$Parser.parse(Schema.java:1396)
        at io.quarkus.avro.deployment.AvroSchemaCodeGenProvider.compileSingleFile(AvroSchemaCodeGenProvider.java:50)
        at io.quarkus.avro.deployment.AvroCodeGenProviderBase.trigger(AvroCodeGenProviderBase.java:65)
        at io.quarkus.deployment.CodeGenerator.lambda$trigger$1(CodeGenerator.java:102)
        at io.quarkus.deployment.CodeGenerator.callWithClassloader(CodeGenerator.java:70)
        at io.quarkus.deployment.CodeGenerator.trigger(CodeGenerator.java:91)
        at io.quarkus.deployment.CodeGenerator.initAndRun(CodeGenerator.java:34)
        ... 122 more
```

### How to Reproduce?

I'm attaching a sample project. To reproduce the issue just run `./gradlew build --stacktrace
[quark-avro.zip](https://github.com/quarkusio/quarkus/files/7761169/quark-avro.zip)
`

### Output of `uname -a` or `ver`

Darwin MacBook-Pro-de-Adminprfl-2.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### Quarkus version or git rev

2.5.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

**Comment by gsmet** [comment]
@cescoffier @alesj any idea if this has been addressed?

**Comment by cescoffier** [comment]
We have a partial fix in place, but it causes other issues. @ozangunalp looked at it recently, and we may need to change how Avro imports are referenced.

**Comment by ozangunalp** [comment]
Even before the fix I am working on, avro imports already work. You can add `avro.codegen.avsc.imports=id.avsc` (comma separated directory or file name, relative to src/main/avro) and those files will be parsed before other files in `src/main/avro`, so that they can be referenced.
I don't know how the config key `avro.codegen.avsc.imports` translates to yaml though, I couldn't make it work inside the `application.yml` file.

**Comment by cescoffier** [comment]
I think there is an issue open about yaml. I think we need some quote in yaml, but not totally sure.
