### ISSUE TITLE
`io.quarkus:quarkus-bom:2.6.0.Final` brings some Apicurio dependencies that generate an annoying log

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#22478]
### Describe the bug

Reproducer
-----------------

Repository: https://github.com/quarkus-qe/quarkus-test-framework.git
cmd: `mvn clean verify -Pexamples -pl examples/kafka-registry`
 annoying log:
```
16:44:16,558 INFO  [app] 16:44:15,746 SRMSG18260: Unable to recover from the serialization failure (topic: end-stock-price), configure a SerializationFailureHandler to recover from errors.: io.apicurio.registry.rest.client.exception.ArtifactNotFoundException: No artifact with ID 'end-stock-price-value' in group 'null' was found.
16:44:16,558 INFO  [app]        at io.apicurio.registry.rest.client.exception.ExceptionMapper.map(ExceptionMapper.java:33)
16:44:16,559 INFO  [app]        at io.apicurio.registry.rest.client.impl.ErrorHandler.handleErrorResponse(ErrorHandler.java:63)
16:44:16,559 INFO  [app]        at io.apicurio.rest.client.response.ResponseHandler.handle(ResponseHandler.java:37)
16:44:16,560 INFO  [app]        at io.apicurio.rest.client.response.ResponseHandler.handle(ResponseHandler.java:18)
16:44:16,560 INFO  [app]        at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:400)
16:44:16,560 INFO  [app]        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:387)
16:44:16,561 INFO  [app]        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:365)
16:44:16,561 INFO  [app]        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:332)
16:44:16,562 INFO  [app]        at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:294)
16:44:16,562 INFO  [app]        at io.vertx.ext.web.client.impl.HttpContext.lambda$null$8(HttpContext.java:549)
16:44:16,563 INFO  [app]        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
16:44:16,563 INFO  [app]        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
16:44:16,564 INFO  [app]        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
16:44:16,564 INFO  [app]        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
16:44:16,565 INFO  [app]        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
16:44:16,565 INFO  [app]        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
16:44:16,566 INFO  [app]        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
16:44:16,566 INFO  [app]        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
16:44:16,569 INFO  [app]        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
16:44:16,570 INFO  [app]        at java.base/java.lang.Thread.run(Thread.java:833)
```

Is working as expected in Quarkus 2.3.0.Final
cmd: `mvn clean verify -Dquarkus.platform.version=2.3.0.Final -Pexamples -pl examples/kafka-registry`

## 2.6.0.Final dependency tree

```
mvn dependency:tree -Dquarkus.platform.version=2.6.0.Final -Pexamples -pl examples/kafka-registry | grep "apicurio"

[INFO] +- io.quarkus:quarkus-apicurio-registry-avro:jar:2.6.0.Final:compile
[INFO] |  +- io.apicurio:apicurio-registry-serdes-avro-serde:jar:2.1.3.Final:compile
[INFO] |  |  \- io.apicurio:apicurio-registry-serde-common:jar:2.1.3.Final:compile
[INFO] |  |     \- io.apicurio:apicurio-registry-client:jar:2.1.3.Final:compile
[INFO] |  |        \- io.apicurio:apicurio-registry-common:jar:2.1.3.Final:compile
[INFO] |  +- io.apicurio:apicurio-common-rest-client-vertx:jar:0.1.0.Final:compile
[INFO] |  |  +- io.apicurio:apicurio-common-rest-client-common:jar:0.1.0.Final:compile

```

## 2.3.0.Final dependency tree

```
mvn dependency:tree -Dquarkus.platform.version=2.3.0.Final -Pexamples -pl examples/kafka-registry | grep "apicurio"

[INFO] +- io.quarkus:quarkus-apicurio-registry-avro:jar:2.3.0.Final:compile
[INFO] |  +- io.apicurio:apicurio-registry-serdes-avro-serde:jar:2.0.1.Final:compile
[INFO] |  |  \- io.apicurio:apicurio-registry-serde-common:jar:2.0.1.Final:compile
[INFO] |  |     \- io.apicurio:apicurio-registry-client:jar:2.0.1.Final:compile
[INFO] |  |        \- io.apicurio:apicurio-registry-common:jar:2.0.1.Final:compile

```

In my opinion, the issue is located on Kafka producer, because is talking about "serialization" error. Kafka itself doesn't know "anything" about AVRO schemas. The Schema validation is done in the producer and consumer. 

Note that I have Schema registry auto register enabled:

strimzi-application.properties

```
mp.messaging.outgoing.source-stock-price.apicurio.registry.auto-register=true
```

**Comment by ozangunalp** [comment]
@pjgg 
The config `apicurio.registry.auto-register` is present for the outgoing channel named `source-stock-price` but is not there for the channel `sink-stock-price`, with the topic name `end-stock-price`. 
Apicurio is complaining that it could not find a schema for the record value with the default id `end-stock-price-value` for this topic.
So by adding `mp.messaging.outgoing.sink-stock-price.apicurio.registry.auto-register=true` the logs go away.

**Comment by cescoffier** [comment]
@ozangunalp should we document that (if not done already)?

**Comment by ozangunalp** [comment]
I think it is well documented here: https://quarkus.io/guides/kafka-schema-registry-avro#the-movie-producer

**Comment by carlesarnal** [comment]
Sorry for the delay, I was on PTO. @ozangunalp is exactly right about the missing configuration. I've checked the documentation and I also think it's well documented.

**Comment by pjgg** [comment]
thank you!. And what about swapping the current default behavior of `mp.messaging.outgoing.<Your_channel>.apicurio.registry.auto-register` as confluent, I mean by default set the auto-register to true.

@ozangunalp @cescoffier
