### ISSUE TITLE
Exception in thread "WindowsStreamPump"

### ISSUE THREAD

**Issue by moacirbishopcamata** [quarkusio/quarkus#22545]
### Describe the bug

Hi Quarkus team,

I had problems running an app in Kotlin on the platform;
Exception in thread "WindowsStreamPump" java.lang.UnsatisfiedLinkError: 'void org.fusesource.jansi.internal.Kernel32$MOUSE_EVEN
T_RECORD.init()'
        at org.fusesource.jansi.internal.Kernel32$MOUSE_EVENT_RECORD.init(Native Method)
        at org.fusesource.jansi.internal.Kernel32$MOUSE_EVENT_RECORD.<clinit>(Kernel32.java:583)
        at org.fusesource.jansi.internal.Kernel32$INPUT_RECORD.<init>(Kernel32.java:735)
        at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:823)
        at org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:106)
        at org.aesh.readline.terminal.impl.WinSysTerminal.readConsoleInput(WinSysTerminal.java:73)
        at org.aesh.readline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:310)
        at java.base/java.lang.Thread.run(Thread.java:833)

This in OS Windows 10 Pro v21H2.

To solve this, I added the dependency 
    <dependency>
      <groupId>org.fusesource.jansi</groupId>
      <artifactId>jansi</artifactId>
      <version>1.18</version>
    </dependency>

This problem does not allow the selection of reload, test, etc. options.

Grateful for the attention.

### Output of `uname -a` or `ver`

Microsoft Windows [versão 10.0.19044.1415]

### Output of `java -version`

openjdk 17.0.1 2021-10-19 LTS OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)

None

### Quarkus version or git rev

 2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.4

**Comment by geoand** [comment]
Closing for lack of feedback.
