### ISSUE TITLE
Continuous testing doesn't support `provided` dependencies

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#22552]
### Describe the bug

Using a class from a `provided` scoped dependency in a test (in whichever way) results in a `ClassNotFoundException` when the test is run in continuous testing mode.

### Expected behavior

Class is found, just like when surefire is running the test.

### Actual behavior

`ClassNotFoundException`

### How to Reproduce?

[q_ct-provided.zip](https://github.com/quarkusio/quarkus/files/7790968/q_ct-provided.zip)

- `mvn clean verify` does not fail (`ProvidedTest` passes)
- `mvn quarkus:dev`
- resume tests
- fails with: 
  ```
  ERROR [io.qua.test] (Test runner thread) Test ProvidedTest#load() failed: java.lang.NoClassDefFoundError: lombok/experimental/SuperBuilder
          at org.acme.ProvidedTest.load(ProvidedTest.java:11)
  Caused by: java.lang.ClassNotFoundException: lombok.experimental.SuperBuilder
          at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
          at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
          at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
          at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
          at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:405)
          at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
          at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:405)
          ... 1 more
  ```

lombok might be a strange example, but in my real project I have a test based on `javaparser` that verifies the expected usage of lombok annotations (which have source retention, so ArchUnit is not usable here).

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

### Additional information

Probably related: https://github.com/quarkusio/quarkus/blob/723663953f2c54fed473021a04d169047c693572/core/deployment/src/main/java/io/quarkus/deployment/dev/testing/TestSupport.java#L196-L201

**Comment by stuartwdouglas** [comment]
@aloubyansky it looks like the 'provided' scoped dep is not ending up in the model, but for the 'mvn verify' use case it is on the class path so can be loaded from the system CL.

**Comment by aloubyansky** [comment]
Yes, it makes sense actually. I'll add `provided` dependencies in the test mode.
