### ISSUE TITLE
java.lang.ClassCastException: class io.quarkus.resteasy.server.common.runtime.QuarkusResteasyDeployment cannot be cast to class org.jboss.resteasy.spi.ResteasyDeployment 

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#22566]
I'm running into an issue after migrating to RestEasy Reactive I cannot make sense of.

```
2021-12-30 21:28:31,732 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) [] Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 17 more
Caused by: java.lang.ClassCastException: class io.quarkus.resteasy.server.common.runtime.QuarkusResteasyDeployment cannot be cast to class org.jboss.resteasy.spi.ResteasyDeployment (io.quarkus.resteasy.server.common.runtime.QuarkusResteasyDeployment is in unnamed module of loader 'app'; org.jboss.resteasy.spi.ResteasyDeployment is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @13df2a8c)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit345281060.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit345281060.deploy(Unknown Source)
	... 18 more

2021-12-30 21:28:31,824 INFO  [org.jbo.threads] (main) [] JBoss Threads version 3.4.2.Final
2021-12-30 21:28:31,967 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) [] Failed to start quarkus: java.lang.RuntimeException: java.lang.ClassCastException: class io.quarkus.resteasy.server.common.runtime.QuarkusResteasyDeployment cannot be cast to class org.jboss.resteasy.spi.ResteasyDeployment (io.quarkus.resteasy.server.common.runtime.QuarkusResteasyDeployment is in unnamed module of loader 'app'; org.jboss.resteasy.spi.ResteasyDeployment is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @13df2a8c)
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:122)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:145)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:456)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:105)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: java.lang.ClassCastException: class io.quarkus.resteasy.server.common.runtime.QuarkusResteasyDeployment cannot be cast to class org.jboss.resteasy.spi.ResteasyDeployment (io.quarkus.resteasy.server.common.runtime.QuarkusResteasyDeployment is in unnamed module of loader 'app'; org.jboss.resteasy.spi.ResteasyDeployment is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @13df2a8c)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit345281060.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit345281060.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

What I did was changing all the method signatures of my rest endpoints from

```
   myEndpoint(@Context HttpServletRequest request, @Context  HttpServletResponse response)
```

to

```
   myEndpoint(HttpServerRequest request,  HttpServerResponse response)
```

Could anyone tell me where this error might originate from?

**Comment by famod** [comment]
How does your pom.xml.look like?

**Comment by gsmet** [comment]
My guess is that you have a mix of traditional RESTEasy and RESTEasy Reactive dependencies. But having the pom would be nice as we should improve on detecting this if it's indeed the issue.

**Comment by mklueh** [comment]
I'm using Gradle in a multi-module project. Doesn't make sense to provide you all the build.gradle files, but those are the dependencies that should be relevant. I've tried around multiple variants:

```
        // 1. working
        //implementation 'io.quarkus:quarkus-mutiny'

        // 2. causes please make sure there is only one provider
        //implementation 'io.quarkus:quarkus-resteasy-mutiny'

        /**
         * 3. causes java.lang.ClassCastException: class io.quarkus.resteasy.server.common.runtime.QuarkusResteasyDeployment 
         *  cannot be cast to class org.jboss.resteasy.spi.ResteasyDeployment 
         */
        implementation('io.quarkus:quarkus-resteasy-mutiny') {
            exclude group: 'io.quarkus', module: 'quarkus-resteasy'
        }
        
        
        implementation 'io.quarkus:quarkus-arc'
        implementation 'io.quarkus:quarkus-resteasy-reactive'
        implementation 'io.quarkus:quarkus-resteasy-reactive-jsonb'
        implementation 'io.quarkus:quarkus-resteasy-reactive-jackson'
```

I think I messed things up by including the quarkus-resteasy-mutiny dependency. Using the quarkus-mutiny works on the other hand.

This is also related to your comment @gsmet on my other issue https://github.com/quarkusio/quarkus/issues/22537#issuecomment-1003187519

**Comment by geoand** [comment]
Using dependency exclusions  for Quarkus dependencies will **not** work.
