### ISSUE TITLE
java.lang.IllegalArgumentException: Wrong syntax of connection URI

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#22635]
### Describe the bug

```log

Tests paused
Press [r] to resume testing, [h] for more options>
Press [r] to resume testing, [o] Toggle test output, [h] for more options>
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-01-05 10:51:01,657 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2022-01-05 10:51:01,656 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalArgumentException: Wrong syntax of connection URI
	at io.vertx.mysqlclient.impl.MySQLConnectionUriParser.doParse(MySQLConnectionUriParser.java:89)
	at io.vertx.mysqlclient.impl.MySQLConnectionUriParser.parse(MySQLConnectionUriParser.java:58)
	at io.vertx.mysqlclient.impl.MySQLConnectionUriParser.parse(MySQLConnectionUriParser.java:50)
	at io.vertx.mysqlclient.MySQLConnectOptions.fromUri(MySQLConnectOptions.java:54)
	at io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder.toMySQLConnectOptions(MySQLPoolRecorder.java:100)
	at io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder.initialize(MySQLPoolRecorder.java:63)
	at io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder.configureMySQLPool(MySQLPoolRecorder.java:45)
	at io.quarkus.deployment.steps.ReactiveMySQLClientProcessor$build360423335.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ReactiveMySQLClientProcessor$build360423335.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)

Press [space] to restart, [e] to edit command line args (currently ''), [r] to resume testing, [o] Toggle test output, [h] for more options>
2022-01-05 10:51:01,750 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:122)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:145)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:456)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:105)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Cannot parse invalid connection URI: jdbc:mysql://localhost:3306/test
	at io.vertx.mysqlclient.impl.MySQLConnectionUriParser.parse(MySQLConnectionUriParser.java:64)
	at io.vertx.mysqlclient.impl.MySQLConnectionUriParser.parse(MySQLConnectionUriParser.java:50)
	at io.vertx.mysqlclient.MySQLConnectOptions.fromUri(MySQLConnectOptions.java:54)
	at io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder.toMySQLConnectOptions(MySQLPoolRecorder.java:100)
	at io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder.initialize(MySQLPoolRecorder.java:63)
	at io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder.configureMySQLPool(MySQLPoolRecorder.java:45)
	at io.quarkus.deployment.steps.ReactiveMySQLClientProcessor$build360423335.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ReactiveMySQLClientProcessor$build360423335.deploy(Unknown Source)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Wrong syntax of connection URI
	at io.vertx.mysqlclient.impl.MySQLConnectionUriParser.doParse(MySQLConnectionUriParser.java:89)
	at io.vertx.mysqlclient.impl.MySQLConnectionUriParser.parse(MySQLConnectionUriParser.java:58)
	... 20 more

2022-01-05 10:51:01,750 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:122)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:145)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:456)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:105)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Cannot parse invalid connection URI: jdbc:mysql://localhost:3306/test
	at io.vertx.mysqlclient.impl.MySQLConnectionUriParser.parse(MySQLConnectionUriParser.java:64)
	at io.vertx.mysqlclient.impl.MySQLConnectionUriParser.parse(MySQLConnectionUriParser.java:50)
	at io.vertx.mysqlclient.MySQLConnectOptions.fromUri(MySQLConnectOptions.java:54)
	at io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder.toMySQLConnectOptions(MySQLPoolRecorder.java:100)
	at io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder.initialize(MySQLPoolRecorder.java:63)
	at io.quarkus.reactive.mysql.client.runtime.MySQLPoolRecorder.configureMySQLPool(MySQLPoolRecorder.java:45)
	at io.quarkus.deployment.steps.ReactiveMySQLClientProcessor$build360423335.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ReactiveMySQLClientProcessor$build360423335.deploy(Unknown Source)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Wrong syntax of connection URI
	at io.vertx.mysqlclient.impl.MySQLConnectionUriParser.doParse(MySQLConnectionUriParser.java:89)
	at io.vertx.mysqlclient.impl.MySQLConnectionUriParser.parse(MySQLConnectionUriParser.java:58)
	... 20 more

```

### Output of `uname -a` or `ver`

Windows 10 20H1

### Output of `java -version`

17

### GraalVM version (if different from Java)

21.3.0

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.3

### Additional information

application.properties

```properties

quarkus.console.color=true
#
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=flight
quarkus.datasource.password=test
quarkus.datasource.reactive=true
quarkus.datasource.reactive.mysql.ssl-mode=disabled
quarkus.datasource.reactive.mysql.charset=utf-8
quarkus.datasource.reactive.url=jdbc:mysql://localhost:3306/test

```

**Comment by geoand** [comment]
Reactive datasources do **not** use `jdbc`. See [this](https://github.com/quarkusio/quarkus/blob/2.6.1.Final/integration-tests/reactive-mysql-client/pom.xml#L34) for an example of the proper syntax.

**Comment by aomsweet** [comment]
@geoand  it's ok, Thanks. ☕
