### ISSUE TITLE
uber-jar with bcprov can't run

### ISSUE THREAD

**Issue by cjdxhjj** [quarkusio/quarkus#22677]
### Describe the bug

my project need to encrypt some data. so i add the bcprov dependencies, i build the uber-jar with 
gradle clean build -D"quarkus.package.type=uber-jar" -x test, 
when i run that uber-jar, it failed with an security check.how to solve the problem, when i works on spring boot, that fine, even thought i have an dependencie to bcprov.
the error is follow

i have config the quarkus.security.security-providers=BC, but that not working

### Expected behavior

the uber-jar can run success

### Actual behavior

PS C:\Users\petzold\IdeaProjects\hr-recruit> java -jar .\build\hr-recruit-1.0-SNAPSHOT-runner.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 11 more
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.hibernate.resource.beans.internal.FallbackBeanInstanceProducer.produceBeanInstance(FallbackBeanInstanceProducer.java:42)
        at org.hibernate.resource.beans.container.internal.ContainerManagedLifecycleStrategy$BeanImpl.produceFallbackInstance(ContainerManagedLifecycleStrategy.java:173)
        at org.hibernate.resource.beans.container.internal.ContainerManagedLifecycleStrategy$AbstractBeanImpl.initialize(ContainerManagedLifecycleStrategy.java:100)
        at io.quarkus.hibernate.orm.runtime.cdi.QuarkusArcBeanContainer.createBean(QuarkusArcBeanContainer.java:34)
        at org.hibernate.resource.beans.container.spi.AbstractCdiBeanContainer.createBean(AbstractCdiBeanContainer.java:64)
        at org.hibernate.resource.beans.container.spi.AbstractCdiBeanContainer.getBean(AbstractCdiBeanContainer.java:38)
        at io.quarkus.hibernate.orm.runtime.cdi.QuarkusManagedBeanRegistry.getBean(QuarkusManagedBeanRegistry.java:34)
        at org.hibernate.boot.model.convert.internal.ClassBasedConverterDescriptor.createManagedBean(ClassBasedConverterDescriptor.java:38)
        at org.hibernate.boot.model.convert.internal.AbstractConverterDescriptor.createJpaAttributeConverter(AbstractConverterDescriptor.java:107)
        at org.hibernate.mapping.SimpleValue.buildAttributeConverterTypeAdapter(SimpleValue.java:594)
        at org.hibernate.mapping.SimpleValue.setTypeUsingReflection(SimpleValue.java:555)
        at org.hibernate.cfg.annotations.SimpleValueBinder.fillSimpleValue(SimpleValueBinder.java:510)
        at org.hibernate.cfg.SetSimpleValueTypeSecondPass.doSecondPass(SetSimpleValueTypeSecondPass.java:25)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1678)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1636)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:295)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:354)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:101)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:73)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:40)
        at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:70)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources1025303321.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources1025303321.deploy(Unknown Source)
        ... 12 more
Caused by: cn.hutool.crypto.CryptoException: SecurityException: JCE cannot authenticate the provider BC
        at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:1018)
        at cn.hutool.crypto.CipherWrapper.<init>(CipherWrapper.java:39)
        at cn.hutool.crypto.symmetric.SymmetricCrypto.init(SymmetricCrypto.java:150)
        at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:127)
        at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:171)
        at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:146)
        at cn.hutool.crypto.symmetric.SM4.<init>(SM4.java:78)
        at com.nxin.recruit.infrastructure.shared.jpa.EncryptConverter.<clinit>(EncryptConverter.kt:10)
        ... 41 more
Caused by: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at java.base/javax.crypto.Cipher.getInstance(Cipher.java:722)
        at cn.hutool.crypto.SecureUtil.createCipher(SecureUtil.java:1016)
        ... 48 more
Caused by: java.util.jar.JarException: The JCE Provider file:/C:/Users/petzold/IdeaProjects/hr-recruit/build/hr-recruit-1.0-SNAPSHOT-runner.jar is not signed.
        at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)
        at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:317)
        at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:260)
        at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130)
        at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:190)
        at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:218)
        at java.base/javax.crypto.Cipher.getInstance(Cipher.java:718)
        ... 49 more

### How to Reproduce?

1.build the uber-jar gradle clean build -D"quarkus.package.type=uber-jar" -x test
2.run the uber-jar java -jar .\build\hr-recruit-1.0-SNAPSHOT-runner.jar

### Output of `uname -a` or `ver`

Microsoft Windows [版本 10.0.19044.1415]

### Output of `java -version`

java version "17" 2021-09-14 LTS Java(TM) SE Runtime Environment (build 17+35-LTS-2724) Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)

### Quarkus version or git rev

2.6.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle clean build -D"quarkus.package.type=uber-jar" -x test

**Comment by cjdxhjj** [comment]
implementation("org.bouncycastle", "bcprov-jdk15on")

**Comment by gsmet** [comment]
Yeah, I'm pretty sure you won't be able to make it work with an uberjar except maybe if you sign it (see https://docs.oracle.com/javase/tutorial/deployment/jar/signindex.html). I would stick to the fast jar approach.

I don't think that's something we can fix in Quarkus, it's really related to the requirements of these security jars.
