### ISSUE TITLE
java.lang.StackOverflowError during build when using hibernate-orm with CompositeAttribute within hbm.xml

### ISSUE THREAD

**Issue by digsb** [quarkusio/quarkus#22685]
### Describe the bug

As part of migration our legacy Java Hibernate project to Quarkus, we faced this issue.

During compilation we got this error:
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.6.1.Final:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#defineJpaEntities threw an exception: java.lang.StackOverflowError
[ERROR] 	at java.base/java.util.HashMap.hash(HashMap.java:340)
[ERROR] 	at java.base/java.util.HashMap.get(HashMap.java:553)
[ERROR] 	at java.base/java.util.Collections$UnmodifiableMap.get(Collections.java:1454)
[ERROR] 	at org.jboss.jandex.Index.getClassByName(Index.java:301)
[ERROR] 	at org.jboss.jandex.CompositeIndex.getClassByName(CompositeIndex.java:201)
[ERROR] 	at org.jboss.jandex.CompositeIndex.getClassByName(CompositeIndex.java:201)
[ERROR] 	at io.quarkus.deployment.index.IndexWrapper.getClassByName(IndexWrapper.java:62)
[ERROR] 	at org.jboss.jandex.CompositeIndex.getClassByName(CompositeIndex.java:201)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.addClassHierarchyToReflectiveList(JpaJandexScavenger.java:429)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.enlistExplicitClass(JpaJandexScavenger.java:312)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:300)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.JpaJandexScavenger.collectHbmXmlEmbeddedTypes(JpaJandexScavenger.java:304)
```

I tried to check in the source as pointed in stack trace and found this method. Last line of the method call caught my eye, as we are passing the same attributes again in recursive call.
```
private void collectHbmXmlEmbeddedTypes(Collector collector, String packagePrefix, List<?> attributes) {
        for (Object attribute : attributes) {
            if (attribute instanceof JaxbHbmCompositeAttributeType) {
                JaxbHbmCompositeAttributeType compositeAttribute = (JaxbHbmCompositeAttributeType) attribute;
                String name = packagePrefix + compositeAttribute.getClazz();
                enlistExplicitClass(collector, name);
                // The call to 'enlistExplicitClass' above may not
                // detect that this class is an entity if it is not annotated
                collector.entityTypes.add(name);
                collectHbmXmlEmbeddedTypes(collector, packagePrefix, attributes);
            }
        }
    }
```
I made some modification to the code and this solved my StackOverflowError issue. But not sure if this is the correct way to fix it.
```
private void collectHbmXmlEmbeddedTypes(Collector collector, String packagePrefix, List<?> attributes) {
        for (Object attribute : attributes) {
            if (attribute instanceof JaxbHbmCompositeAttributeType) {
                JaxbHbmCompositeAttributeType compositeAttribute = (JaxbHbmCompositeAttributeType) attribute;
                String name = packagePrefix + compositeAttribute.getClazz();
                enlistExplicitClass(collector, name);
                // The call to 'enlistExplicitClass' above may not
                // detect that this class is an entity if it is not annotated
                collector.entityTypes.add(name);
                collectHbmXmlEmbeddedTypes(collector, packagePrefix,
                        ((JaxbHbmCompositeAttributeType) attribute).getAttributes());
            }
        }
    }
```

### Expected behavior

Build should complete successfully.

### Actual behavior

Getting java.lang.StackOverflowError

### Output of `uname -a` or `ver`

Linux ubuntu 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04) OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by yrodiere** [comment]
Thanks. Your patch looks right, though you could simplify the line to:

```
                collectHbmXmlEmbeddedTypes(collector, packagePrefix, compositeAttribute.getAttributes());
```

Do you think you could submit a pull request?

**Comment by digsb** [comment]
@yrodiere, sure I can do that
