### ISSUE TITLE
NPE when adding new registry in Quarkus CLI

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#22731]
### Describe the bug

When new registry is added into freshly installed Quarkus CLI, the operation fails with NullPointerException.

### Expected behavior

New registry is added successfully.

### Actual behavior

Exception in console:
```
java.lang.NullPointerException
	at io.quarkus.registry.config.RegistriesConfigMapperHelper.serialize(RegistriesConfigMapperHelper.java:45)
	at io.quarkus.registry.config.RegistriesConfig$Mutable.persist(RegistriesConfig.java:111)
	at io.quarkus.cli.RegistryAddCommand.call(RegistryAddCommand.java:54)
	at io.quarkus.cli.RegistryAddCommand.call(RegistryAddCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.quarkus.cli.QuarkusCli.run(QuarkusCli.java:50)
	at io.quarkus.cli.QuarkusCli_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:125)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.cli.Main.main(Main.java:9)
```

### How to Reproduce?

Steps to reproduce:

1. `jbang app uninstall quarkus`
2. `rm -r ~/.quarkus/`
3. `jbang app install --fresh --force quarkus@quarkusio`
4. 
```
$ quarkus version
2.6.1.Final # 2.5.2.Final worked as expected
```
5. `quarkus registry add registry.quarkus.redhat.com`

### Output of `uname -a` or `ver`

OS name: "linux", version: "5.15.6-100.fc34.x86_64"

### Output of `java -version`

11.0.13, vendor: Eclipse Adoptium

**Comment by glefloch** [comment]
The `configYaml` can be null https://github.com/quarkusio/quarkus/blob/8d501fc14bf108b0a7a5b84de3f2b7ae619f20e6/devtools/cli/src/main/java/io/quarkus/cli/RegistryAddCommand.java#L54
Is there a default value somewhere @ebullient ?

**Comment by ebullient** [comment]
Yeow! how did this get by? Yikes.

**Comment by gsmet** [comment]
@ebullient I release 2.6.2.Final on Monday morning early Paris time so if it's an easy fix and you can get it by then, we can include it.

**Comment by glefloch** [comment]
With some advice, I can give it a try @ebullient.

**Comment by ebullient** [comment]
It's building now.

**Comment by glefloch** [comment]
I pushed a pr but feel free to close it if you have something else. ;)

**Comment by ebullient** [comment]
I did close it. I am trying to remove direct access to those Locators outside of the registry client package. Next thing on my list is making them package private. I can't do it just yet because we still have the flying spaghetti monster in there running amok
