### ISSUE TITLE
Gradle Jacoco Plugin and Quarkus Jacoco - Cannot process instrumented class. Please supply original non-instrumented classes.

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#22793]
### Describe the bug

I have a project with a mix of plain JUnit tests and `@QuarkusTest`s. I am using both Gradle Jacoco plugin and Quarkus Jacoco dependency to measure the combined coverage.

After upgrading to Quarkus 2.6.1.Final from 2.5.8.Final I see a lot of output in stderr about "Cannot process instrumented class <class>. Please supply original non-instrumented classes.", e.g.:

```
Caused by: java.lang.IllegalStateException: Cannot process instrumented class io/quarkus/test/common/PathTestHelper. Please supply original non-instrumented classes.
	at org.jacoco.agent.rt.internal_3570298.core.internal.instr.InstrSupport.assertNotInstrumented(InstrSupport.java:238)
	at org.jacoco.agent.rt.internal_3570298.core.internal.instr.ClassInstrumenter.visitMethod(ClassInstrumenter.java:65)
	at org.jacoco.agent.rt.internal_3570298.core.internal.flow.ClassProbesAdapter.visitMethod(ClassProbesAdapter.java:66)
	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.readMethod(ClassReader.java:1330)
	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.accept(ClassReader.java:721)
	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.accept(ClassReader.java:401)
	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:90)
	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:108)
	... 76 more
```

### Expected behavior

No warnings, Gradle Jacoco plugin and Quarkus Jacoco work together

### Actual behavior

Warnings about Cannot process instrumented class. Please supply original non-instrumented classes.

### How to Reproduce?

Add 

```
plugins {
  id 'jacoco'
}
```

and

```
dependencies {
  testImplementation 'io.quarkus:quarkus-jacoco'
}
```

### Output of `uname -a` or `ver`

Darwin Josephs-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.8" 2020-07-14 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

### Quarkus version or git rev

2.6.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3

**Comment by kdubb** [comment]
@josephearl Look at https://quarkus.io/guides/tests-with-coverage#coverage-for-tests-not-using-quarkustest

Specifically the section that instructs you to exclude Quarkus class loaders...
```
jacoco {
  excludeClassLoaders = ["*QuarkusClassLoader"] 
}
```

This will solve your problem.

**Comment by josephearl** [comment]
Thank, guess that documentation has been updated since I last read it 😄 
Can confirm that solved my problem.
