### ISSUE TITLE
Quarkus fails to connect to Infinispan server running on FIPS

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#22839]
### Describe the bug

Infinispan server running on FIPS enabled machines logs following error at startup and continues to run.
Command:
`docker run -p 11222:11222 -e USER=admin -e PASS=password infinispan/server`
Logs:
`PKCS11Exception: CKR_ATTRIBUTE_VALUE_INVALID`

Because of this Quarkus fails to connect to the Infinispan server and throws:
```
ISPN005003: Exception reported java.lang.SecurityException: ISPN028027: Invalid credentials
	at org.infinispan.server.hotrod.Authentication.lambda$auth$0(Authentication.java:82)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.security.sasl.SaslException: ELY05051: Callback handler does not support credential acquisition [Caused by org.wildfly.security.auth.callback.FastUnsupportedCallbackException: javax.security.auth.callback.PasswordCallback@4034e07e]
	at org.wildfly.security.mechanism.digest.PasswordDigestObtainer.getSaltedPasswordFromPasswordCallback(PasswordDigestObtainer.java:295)
	at org.wildfly.security.mechanism.digest.PasswordDigestObtainer.handleUserRealmPasswordCallbacks(PasswordDigestObtainer.java:112)
	at org.wildfly.security.sasl.digest.AbstractDigestMechanism.handleUserRealmPasswordCallbacks(AbstractDigestMechanism.java:194)
	at org.wildfly.security.sasl.digest.DigestSaslServer.validateDigestResponse(DigestSaslServer.java:264)
	at org.wildfly.security.sasl.digest.DigestSaslServer.evaluateMessage(DigestSaslServer.java:377)
	at org.wildfly.security.sasl.util.AbstractSaslParticipant.evaluateMessage(AbstractSaslParticipant.java:206)
	at org.wildfly.security.sasl.digest.DigestSaslServer.evaluateResponse(DigestSaslServer.java:350)
	at org.wildfly.security.sasl.util.AuthenticationCompleteCallbackSaslServerFactory$1.evaluateResponse(AuthenticationCompleteCallbackSaslServerFactory.java:58)
	at org.wildfly.security.sasl.util.AuthenticationTimeoutSaslServerFactory$DelegatingTimeoutSaslServer.evaluateResponse(AuthenticationTimeoutSaslServerFactory.java:110)
	at org.wildfly.security.sasl.util.SecurityIdentitySaslServerFactory$1.evaluateResponse(SecurityIdentitySaslServerFactory.java:59)
	at org.infinispan.server.core.security.SubjectSaslServer.evaluateResponse(SubjectSaslServer.java:39)
	at org.infinispan.server.hotrod.Authentication.authInternal(Authentication.java:98)
	at org.infinispan.server.hotrod.Authentication.lambda$auth$0(Authentication.java:77)
	... 5 more
Caused by: org.wildfly.security.auth.callback.FastUnsupportedCallbackException: javax.security.auth.callback.PasswordCallback@4034e07e
```

This is related to https://github.com/quarkusio/quarkus-quickstarts/issues/1032

### How to Reproduce?

RHEL 8.5 with FIPS enabled

### Output of `uname -a` or `ver`

Linux rhel8-medium-5 4.18.0-305.el8.x86_64 #1 SMP Thu Apr 29 08:54:30 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "11.0.13" 2021-10-19 LTS

### Quarkus version or git rev

2.6.2.Final

**Comment by tristantarrant** [comment]
This is not even an Infinispan issue, but it's about configuring the JDK security provider to enable FIPS
