### ISSUE TITLE
IllegalStateException if cache hit using @CacheResult happens within HttpAuthenticationMechanism.authenticate()

### ISSUE THREAD

**Issue by j-be** [quarkusio/quarkus#22874]
### Describe the bug

Consider the following (not relevant stuff removed for brevity)

```java
@ApplicationScoped
public class CachingService {
    @CacheResult(cacheName = "counterCache")
    public int get() {
        return -1;
    }
}
```
```java
@ApplicationScoped
public class SomethingHttpAuthenticationMechanism implements HttpAuthenticationMechanism {

    @Inject
    CachingService cachingService;

    @Override
    public Uni<SecurityIdentity> authenticate(RoutingContext context, IdentityProviderManager identityProviderManager) {

        // This is the offending line
        cachingService.get();

        // This is just here to avoid a NullPointer downstream
        return Uni.createFrom().item(QuarkusSecurityIdentity.builder()
                .setAnonymous(true)
                .build());
    }
   ...
```

The above works fine in Quarks up to including `2.5.4.Final`, but it throws an `IllegalStateException` if `cachingService.get()` is a cache hit in Quarkus `2.6.0.Final` and above (checked up to `2.6.2.Final`, which is current stable at the time of writing.

### Expected behavior

Functions decorated with `@CacheResult` can be used in `HttpAuthenticationMechanism.authenticate()`.

### Actual behavior

Using functions decorated with `@CacheResult` in `HttpAuthenticationMechanism.authenticate()` cause the following exception when there is a cache hit:

```
2022-01-13 19:28:30,234 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-5) HTTP Request to / failed, error id: 03f61980-f9ff-4d10-8ce4-c4bb61654a61-1: java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-5
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:62)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:43)
	at io.quarkus.cache.runtime.CacheResultInterceptor.intercept(CacheResultInterceptor.java:96)
	at io.quarkus.cache.runtime.CacheResultInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.owly.duckdns.quarkus.test.cache.CachingService_Subclass.get(Unknown Source)
	at org.owly.duckdns.quarkus.test.cache.CachingService_ClientProxy.get(Unknown Source)
	at org.owly.duckdns.quarkus.test.cache.SomethingHttpAuthenticationMechanism.authenticate(SomethingHttpAuthenticationMechanism.java:28)
	at org.owly.duckdns.quarkus.test.cache.SomethingHttpAuthenticationMechanism_ClientProxy.authenticate(Unknown Source)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator.attemptAuthentication(HttpAuthenticator.java:122)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.attemptAuthentication(Unknown Source)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:110)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:60)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1193)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:67)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$12.handle(VertxHttpRecorder.java:486)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$12.handle(VertxHttpRecorder.java:483)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:152)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:134)
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:67)
	at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:30)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:145)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:156)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

~I'll push a small reproducer project shortly and update this sections with a link to it when I did.~

A small reproducer project can be found at https://github.com/j-be/quarkus-22874.

The line triggering the bug is [here](https://github.com/j-be/quarkus-22874/blob/692370ca787da1c5c24455dc05f6b1da6700ac06/src/main/java/org/owly/duckdns/quarkus/test/cache/SomethingHttpAuthenticationMechanism.java#L27-L28), but the bug only manifests if there is a cache hit, hence the cache needs to be preloaded, like I did [here](https://github.com/j-be/quarkus-22874/blob/692370ca787da1c5c24455dc05f6b1da6700ac06/src/test/java/org/owly/duckdns/quarkus/test/cache/test/CachingServiceTest.java#L19-L20).

### Output of `uname -a` or `ver`

Linux jbe-desktop 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### GraalVM version (if different from Java)

not relevant

### Quarkus version or git rev

2.6.0.Final and above

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: *redacted* Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /home/juri/.sdkman/candidates/java/11.0.11.hs-adpt Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.4.0-94-generic", arch: "amd64", family: "unix"

EDIT: Fix link to cache preload in `CachingServiceTest.java`

**Comment by gwenneg** [comment]
Can I see the real `HttpAuthenticationMechanism.authenticate()` implementation or is it private?

**Comment by j-be** [comment]
Yes, I can share the content with you. We are planning to open-source it anyway in the near furture - but we are still working on the final preparations, so I need to copy it in here for now.

Btw: I have to say I am fairly new to `Uni` and stuff, so it might be, that there is an extremly easy was to fix this I am simply not aware off.

In any case: it is not the `HttpAuthenticationMechanism`, but rather the `IdentityProvider<HttpSigAuthenticationRequest>` which is affected. I chose the `HttpAuthenticationMechanism` to show the issue, as the result is the same, and it seemed to need less code to reproduce.

Here is the code - I trimmed it down for brevity, so please excuse if there is a syntax error. Please note, that `host` is used in a lot of `log` statements:

```java
@ApplicationScoped
public class HttpSigIdentityProvider implements IdentityProvider<HttpSigAuthenticationRequest> {

    @Inject HttpSigService httpSigService;
    @Inject CatalogueService catalogueService;

    @Override
    public Uni<SecurityIdentity> authenticate(HttpSigAuthenticationRequest request, AuthenticationRequestContext context) {
        RequestContent requestContent = request.getContent();
        Authorization authorization = request.getAuthorization();

        /* Step 1: Check authorization header is there and valid */
        if(authorization == null) {
            log.error("authorization header is invalid");
            return Uni.createFrom().failure(new EwpApiException("authorization header is invalid", 401));
        }
        // getCatalogue() is the @CacheResult call, hasKey is a pure function ommitted for brevity
        final Host host = catalogueService.getCatalogue().getHosts().stream()
                .filter(host -> hasKey(host, authorization.getKeyId()))
                .findAny()
                .orElse(null);
        if(host == null) {
            return Uni.createFrom().failure(new EwpApiException("unknown client key", 403));
        }
        if(!httpSigService.verifyClient(requestContent, authorization)) {
            log.error("[authenticate] not verified. key ID: " + authorization.getKeyId() + ", EMail: " + host.getAdminEmail());
            return Uni.createFrom().failure(new EwpApiException("not verified", 401));
        }

        /* Step 2: Check the other required headers are there */
        final List<String> signedHeaders = authorization.getHeaders();
        if(CollectionUtils.isEmpty(signedHeaders)) {
            log.error("[authenticate] no header is signed. key ID: " + authorization.getKeyId() + ", EMail: " + host.getAdminEmail());
            return Uni.createFrom().failure(new EwpApiException("no header is signed", 401));
        }
        if(signedHeaders.stream().noneMatch(HttpHeaders.DATE::equalsIgnoreCase) && signedHeaders.stream().noneMatch(HttpHeaders.ORIGINAL_DATE::equalsIgnoreCase)) {
            log.error("[authenticate] date and original-date header is not signed. key ID: " + authorization.getKeyId() + ", EMail: " + host.getAdminEmail());
            return Uni.createFrom().failure(new EwpApiException("neither date nor original-date header is signed", 401));
        }
        for (String requiredHeader : List.of(
                HttpHeaders.TARGET,
                HttpHeaders.HOST,
                HttpHeaders.DIGEST,
                HttpHeaders.X_REQUEST_ID
        )) {
            if (signedHeaders.stream().noneMatch(requiredHeader::equalsIgnoreCase)) {
                log.error("[authenticate] " + requiredHeader + " header is not signed. key ID: " + authorization.getKeyId() + ", EMail: " + host.getAdminEmail());
                return Uni.createFrom().failure(new EwpApiException(requiredHeader + " header is not signed", 401));
            }
        }

        /* Step 3: Check the x-request-id header */
        final List<String> xRequestIdList = requestContent.getHeaderValues(HttpHeaders.X_REQUEST_ID);
        if (CollectionUtils.isEmpty(xRequestIdList)) {
            log.error("[authenticate] x-request-id missing. key ID: " + authorization.getKeyId() + ", EMail: " + host.getAdminEmail());
            return Uni.createFrom().failure(new EwpApiException("x-request-id missing", 400));
        }
        try {
            UUID.fromString(xRequestIdList.get(0));
        } catch (IllegalArgumentException e) {
            log.error("[authenticate] x-request-id invalid format. key ID: " + authorization.getKeyId() + ", EMail: " + host.getAdminEmail());
            return Uni.createFrom().failure(new EwpApiException("x-request-id invalid format", 400));
        }

        /* Step 4: Check the date or original-date header. original-date takes precedence */
        List<String> dateList = requestContent.getHeaderValues(HttpHeaders.ORIGINAL_DATE);
        if(CollectionUtils.isEmpty(dateList))
            dateList = requestContent.getHeaderValues(HttpHeaders.DATE);

        if (CollectionUtils.isEmpty(dateList)) {
            log.error("[authenticate] date is missing. key ID: " + authorization.getKeyId() + " and EMail: " + host.getAdminEmail());
            return Uni.createFrom().failure(new EwpApiException("date is missing", 400));
        }

        try {
            Instant sent = LocalDateTime.from(DateTimeFormatter.RFC_1123_DATE_TIME.parse(dateList.get(0)))
                    .atZone(ZoneId.of("UTC")).toInstant();
            Instant now = ZonedDateTime.now(ZoneId.of("UTC")).toInstant();
            long minutes = ChronoUnit.MINUTES.between(sent, now);
            if (minutes > 5) {
                throw new IllegalArgumentException(minutes + " minutes have passed");
            }
        } catch (RuntimeException e) {
            log.error("[authenticate] date is invalid: " + e.getMessage() + ". key ID: " + authorization.getKeyId() + " and EMail: " + host.getAdminEmail());
            return Uni.createFrom().failure(new EwpApiException("date is invalid", 400));
        }

        /* If this is reached, everything looks good. */
        return Uni.createFrom().item(new QuarkusSecurityIdentity.Builder()
                .setPrincipal(new EwpPrincipal(host))
                .addRole(Role.HTTPSIG)
                .addCredential(new HttpSigCredential(authorization.getKeyId()))
                .build());
    }
}
```

**Comment by gwenneg** [comment]
Thank you! Which data is cached exactly in that code?

**Comment by gwenneg** [comment]
Oh sorry it's written in the comments, just saw it 😃

**Comment by gwenneg** [comment]
Can you try something like this?

```
    @ApplicationScoped
    public class HttpSigIdentityProvider implements IdentityProvider<HttpSigAuthenticationRequest> {

        @Inject HttpSigService httpSigService;
        @Inject CatalogueService catalogueService;

        @Override
        public Uni<SecurityIdentity> authenticate(HttpSigAuthenticationRequest request, AuthenticationRequestContext context) {
            RequestContent requestContent = request.getContent();
            Authorization authorization = request.getAuthorization();

            /* Step 1: Check authorization header is there and valid */
            if(authorization == null) {
                log.error("authorization header is invalid");
                return Uni.createFrom().failure(new EwpApiException("authorization header is invalid", 401));
            }

            return catalogueService.getCatalogue().onItem().transformToUni(catalogue -> {
                final Host host = catalogue.getHosts().stream()
                        .filter(host -> hasKey(host, authorization.getKeyId()))
                        .findAny()
                        .orElse(null);

                // Put the rest of the existing code here.

            });
        }
    }
```

**Comment by j-be** [comment]
It works fine in my reproducer, but not in my actual code - I still get

```
Caused by: java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-7
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:62)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:43)
	at io.quarkus.cache.runtime.CacheResultInterceptor.intercept(CacheResultInterceptor.java:65)
	at io.quarkus.cache.runtime.CacheResultInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at at.ac.tuwien.ewp.services.MockCatalogueService_Subclass.fetchCatalogue(Unknown Source)
	at at.ac.tuwien.ewp.services.network.CatalogueService.getCatalogueUni(CatalogueService.java:58)
	at at.ac.tuwien.ewp.services.MockCatalogueService_ClientProxy.getCatalogueUni(Unknown Source)
	at at.ac.tuwien.ewp.security.HttpSigIdentityProvider.authenticate(HttpSigIdentityProvider.java:56)
	at at.ac.tuwien.ewp.security.HttpSigIdentityProvider.authenticate(HttpSigIdentityProvider.java:29)
```

Line 29 is `@ApplicationScoped`.

Line 56 is `return catalogueService.getCatalogueUni().onItem().transformToUni(catalogue -> {` (see below).

For completeness: I can't change `getCatalouge()` as it is used in a variety of places, and the `@CacheResult` call is actually in there - not sure if that makes a difference.

So I now have:

```java
    public Uni<SecurityIdentity> authenticate(HttpSigAuthenticationRequest request, AuthenticationRequestContext context) {
        RequestContent requestContent = request.getContent();
        Authorization authorization = request.getAuthorization();

        /* Step 1: Check authorization header is there and valid */
        if(authorization == null) {
            log.error("authorization header is invalid");
            return Uni.createFrom().failure(new EwpApiException("authorization header is invalid", 401));
        }

        return catalogueService.getCatalogueUni().onItem().transformToUni(catalogue -> {
            final Host host = catalogue.getHosts().stream()
                    .filter(h -> hasKey(h, authorization.getKeyId()))
                    .findAny()
                    .orElse(null);

            // And so on
```

```java
@ApplicationScoped
public class CatalogueService {
    public Uni<Catalogue> getCatalogueUni() {
        return fetchCatalogue()
                .onFailure().recoverWithItem((e) -> {
                    log.error("[GetCatalogue] Failed to fetch catalogue, falling back to MongoDB one: " + e.getMessage());
                    return catalogueRepo.get();
                })
                .onItem().ifNull().failWith(() -> new RuntimeException("[GetCatalogue] Cannot fetch Catalogue " +
                "from neither Registry, nor Cache, nor MongoDB. Nothing left to try..."));
    }

    @CacheResult(cacheName = CATALOGUE_CACHE_NAME)
    public Uni<Catalogue> fetchCatalogue() {
        log.info("[FetchCatalogue] Trying to fetch");
        final Catalogue fetchedCatalogue = CatalogueMapper.toCatalogue(registryRemoteService.getCatalogue());
        if (fetchedCatalogue != null) {
            log.info("[FetchCatalogue] Got Catalogue, storing to MongoDB");
            catalogueRepo.store(fetchedCatalogue);
        }
        return Uni.createFrom().item(fetchedCatalogue);
    }

    ...
```

but for tests (i.e. `@QuarkusTest` with `RestAssured` hitting the actual API) where the error originates from I also have:

```java
@Mock
@ApplicationScoped
public class MockCatalogueService extends CatalogueService {
   @Override
    public Uni<Catalogue> fetchCatalogue() {
        return Uni.createFrom().item(applyMocks(CatalogueMapper.toCatalogue(TestResourceLoader.getMockCatalogue())));
    }

    ...
}
```

`applyMocks` (add hardcoded stuff) and `CatalogueMapper.toCatalogue` (simple mapper) are pure functions and `TestResourceLoader.getMockCatalogue()` is currently patched to take thatone out of the equasion:

```java
public class TestResourceLoader {
    public static XmlCatalogue getMockCatalogue() {
        return new XmlCatalogue();
    }
}
```

**Comment by gwenneg** [comment]
Was that tested with Quarkus `2.6.2.Final`? The exception looks like something that would happen with `2.6.0.Final` but not `2.6.1.Final` or newer (we fixed something after 2.6.0).

**Comment by j-be** [comment]
Yes, my fault, still had it on `2.6.0.Final`. It works now! :partying_face:

Thank you so much for your help, I learned quite something today!

Feel free to close this issue.

**Comment by gwenneg** [comment]
You're welcome!
