### ISSUE TITLE
Pretty print of configuration errors

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2292]
Users can do (unintended) configuration errors and Quarkus should provide human (not only Java developer) readable message. Currently java stacktrace is provided.

I can imagine several cases
 - decimal instead of integer
 - typo in boolean
 - typo in name for enums/constants - e.g. log level

Quarkus is using MP Config via SmallRye Config code so there could be also an enhancement on that side.

Proposed format:
```
java -Dquarkus.log.console.darken=1.5 -jar target/validation-1.0-SNAPSHOT-runner.jar
Error: Expected an integer value for 'quarkus.log.console.darken' property.
```

Current state:
```
java -Dquarkus.log.console.darken=1.5 -jar target/validation-1.0-SNAPSHOT-runner.jar
java.lang.NumberFormatException: For input string: "1.5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at io.smallrye.config.Converters.lambda$static$18960f11$1(Converters.java:75)
	at io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:133)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:76)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console_darken(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.getRunTimeConfiguration(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.Application.run(Application.java:213)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.Application.run(Application.java:213)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.NumberFormatException: For input string: "1.5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at io.smallrye.config.Converters.lambda$static$18960f11$1(Converters.java:75)
	at io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:133)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:76)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console_darken(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey_log(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.parseKey(Unknown Source)
	at io.quarkus.runtime.generated.RunTimeConfig.getRunTimeConfiguration(Unknown Source)
	... 4 more
```

**Comment by dmlloyd** [comment]
This relates to #2490 and #2489.  But it's a distinct issue because this comes down to SmallRye's implicit converters.
