### ISSUE TITLE
Jbang build on github actions fails with an HTTP status 409

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#22964]
### Describe the bug

Quarkus version: `Quarkus-999-SNAPSHOT`

Jbang build is failing on Github actions with the following error: 

```
Error: 9,211 INFO  [jbang] [ERROR] Issue running postBuild()
22:38:09,211 INFO  dev.jbang.cli.ExitException: Issue running postBuild()
22:38:09,211 INFO   at dev.jbang.spi.IntegrationManager.runIntegration(IntegrationManager.java:153)
22:38:09,211 INFO   at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:200)
22:38:09,211 INFO   at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:131)
22:38:09,211 INFO   at dev.jbang.cli.BaseBuildCommand.buildIfNeeded(BaseBuildCommand.java:95)
22:38:09,211 INFO   at dev.jbang.cli.Build.doCall(Build.java:22)
22:38:09,211 INFO   at dev.jbang.cli.BaseCommand.call(BaseCommand.java:93)
22:38:09,211 INFO   at dev.jbang.cli.BaseCommand.call(BaseCommand.java:15)
22:38:09,211 INFO   at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
22:38:09,211 INFO   at picocli.CommandLine.access$1300(CommandLine.java:145)
22:38:09,211 INFO   at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
22:38:09,211 INFO   at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
22:38:09,211 INFO   at dev.jbang.cli.JBang$3.handle(JBang.java:145)
22:38:09,211 INFO   at dev.jbang.cli.JBang$3.handle(JBang.java:140)
22:38:09,211 INFO   at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
22:38:09,212 INFO   at picocli.CommandLine.execute(CommandLine.java:2078)
22:38:09,212 INFO   at dev.jbang.Main.main(Main.java:14)
22:38:09,212 INFO  Caused by: java.lang.reflect.InvocationTargetException
22:38:09,212 INFO   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:38:09,212 INFO   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:38:09,212 INFO   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:38:09,212 INFO   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:38:09,212 INFO   at dev.jbang.spi.IntegrationManager.runIntegration(IntegrationManager.java:117)
22:38:09,212 INFO   ... 15 more
22:38:09,212 INFO  Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
22:38:09,212 INFO   at io.quarkus.launcher.JBangIntegration.postBuild(JBangIntegration.java:128)
22:38:09,212 INFO   ... 20 more
22:38:09,212 INFO  Caused by: java.lang.reflect.InvocationTargetException
22:38:09,212 INFO   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:38:09,212 INFO   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:38:09,212 INFO   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:38:09,212 INFO   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:38:09,212 INFO   at io.quarkus.launcher.JBangIntegration.postBuild(JBangIntegration.java:120)
22:38:09,212 INFO   ... 20 more
22:38:09,212 INFO  Caused by: java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for dev.jbang.user:quarkus::jar:999-SNAPSHOT[paths: /home/runner/.jbang/cache/jars/main.java.cab84ed17a6a434b5c4ca0b044303509ad5a56439de0db71d016b667f6ba4994.jar.tmp;]
22:38:09,212 INFO   at io.quarkus.bootstrap.jbang.JBangBuilderImpl.postBuild(JBangBuilderImpl.java:89)
22:38:09,212 INFO   ... 25 more
22:38:09,212 INFO  Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for dev.jbang.user:quarkus::jar:999-SNAPSHOT[paths: /home/runner/.jbang/cache/jars/main.java.cab84ed17a6a434b5c4ca0b044303509ad5a56439de0db71d016b667f6ba4994.jar.tmp;]
22:38:09,212 INFO   at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:332)
22:38:09,212 INFO   at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:179)
22:38:09,212 INFO   at io.quarkus.bootstrap.jbang.JBangBuilderImpl.postBuild(JBangBuilderImpl.java:80)
22:38:09,212 INFO   ... 25 more
22:38:09,212 INFO  Caused by: io.quarkus.bootstrap.resolver.maven.BootstrapMavenException: Failed to read descriptor of dev.jbang.user:quarkus:jar:999-SNAPSHOT
22:38:09,212 INFO   at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolveDescriptorInternal(MavenArtifactResolver.java:200)
22:38:09,212 INFO   at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.newCollectManagedRequest(MavenArtifactResolver.java:334)
22:38:09,212 INFO   at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.newCollectManagedRequest(MavenArtifactResolver.java:327)
22:38:09,212 INFO   at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolveManagedDependencies(MavenArtifactResolver.java:276)
22:38:09,212 INFO   at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.doResolveModel(BootstrapAppModelResolver.java:209)
22:38:09,212 INFO   at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveManagedModel(BootstrapAppModelResolver.java:170)
22:38:09,212 INFO   at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:318)
22:38:09,212 INFO   ... 27 more
22:38:09,212 INFO  Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for dev.jbang.user:quarkus:jar:999-SNAPSHOT
22:38:09,212 INFO   at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:259)
22:38:09,212 INFO   at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175)
22:38:09,212 INFO   at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
22:38:09,212 INFO   at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolveDescriptorInternal(MavenArtifactResolver.java:194)
22:38:09,212 INFO   ... 33 more
22:38:09,213 INFO  Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact dev.jbang.user:quarkus:pom:999-SNAPSHOT from/to gradle-official-repository (https://repo.gradle.org/gradle/libs-releases-local/): transfer failed for https://repo.gradle.org/gradle/libs-releases-local/dev/jbang/user/quarkus/999-SNAPSHOT/quarkus-999-SNAPSHOT.pom, status: 409 Conflict
22:38:09,213 INFO   at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:425)
22:38:09,213 INFO   at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
22:38:09,213 INFO   at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
22:38:09,213 INFO   at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:244)
22:38:09,213 INFO   ... 36 more
22:38:09,213 INFO  Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact dev.jbang.user:quarkus:pom:999-SNAPSHOT from/to gradle-official-repository (https://repo.gradle.org/gradle/libs-releases-local/): transfer failed for https://repo.gradle.org/gradle/libs-releases-local/dev/jbang/user/quarkus/999-SNAPSHOT/quarkus-999-SNAPSHOT.pom, status: 409 Conflict
22:38:09,213 INFO   at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
22:38:09,213 INFO   at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
22:38:09,213 INFO   at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
22:38:09,213 INFO   at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:628)
22:38:09,213 INFO   at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
22:38:09,213 INFO   at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514)
22:38:09,213 INFO   at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402)
22:38:09,213 INFO   ... 39 more
22:38:09,213 INFO  Caused by: org.apache.maven.wagon.TransferFailedException: transfer failed for https://repo.gradle.org/gradle/libs-releases-local/dev/jbang/user/quarkus/999-SNAPSHOT/quarkus-999-SNAPSHOT.pom, status: 409 Conflict
22:38:09,213 INFO   at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1204)
22:38:09,213 INFO   at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1140)
22:38:09,213 INFO   at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:126)
22:38:09,213 INFO   at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
22:38:09,213 INFO   at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
22:38:09,213 INFO   at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:546)
22:38:09,213 INFO   at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:430)
22:38:09,213 INFO   at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:407)
22:38:09,213 INFO   at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:457)
```
 
GH actions log: https://github.com/quarkus-qe/quarkus-test-suite/runs/4846688325?check_suite_focus=true#step:9:20169

Reproducer: 
https://github.com/pjgg/quarkus-test-suite/tree/feat/Quarkus-cli-gradle-jbang
```
mvn clean verify -Dall-modules -Dinclude.quarkus-cli-tests -Dts.quarkus.cli.cmd=/home/pablojosegonzalezgranados/Documents/quarkus-cli/quar
kus-dev-cli -Dit.test=QuarkusCliCreateJvmApplicationIT#shouldCreateApplicationWithJbangOnJvm -pl quarkus-cli
```

**Note:** be sure that `QuarkusCliCreateJvmApplicationIT#shouldCreateApplicationWithJbangOnJvm` is enabled

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12) OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

**Comment by maxandersen** [comment]
What version of jbang are You running here?

**Comment by pjgg** [comment]
```
Downloading JBang...
Installing JBang...
[jbang] jbang version 0.86.0
[jbang] System Java version detected as 11
[jbang] System Java version matches requested version 11
[jbang] Resolving dependencies...
[jbang] Artifacts used for dependency management:
         io.quarkus.platform:quarkus-bom:pom:2.6.2.Final
[jbang] io.quarkus:quarkus-resteasy
Done
[jbang] Dependencies resolved
```

**Comment by geoand** [comment]
The reproducer does not use version `999-SNAPSHOT` of Quarkus (and a simple replace of the property I tried failed).

Please update the instructions if this is still a problem, or close it otherwise

**Comment by geoand** [comment]
I'll close this as we did not get feedback
