### ISSUE TITLE
@Blocking with reactive causes NoStackTraceThrowable: Timeout exception

### ISSUE THREAD

**Issue by DavideD** [quarkusio/quarkus#23047]
### Describe the bug

Given the following bean:
```
@Path("/payload")
public class ReceivedDataPayloadResource {

	@GET
	@Path("/blocking/{rd_id}")
	@Blocking
	public ReceivedDataPayload getBlockingPart(@PathParam("rd_id") Long rdId) {
		return ReceivedDataPayload.<ReceivedDataPayload>find( "rdId", rdId )
				.firstResult().await().indefinitely();
	}
}
```
After calling the api 4-5 times, the following error occurs:
```
2022-01-20 08:50:22,582 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-2) HR000057: Failed to execute statement [$1select receivedda0_.id as id1_0_, receivedda0_.source as source2_0_, receivedda0_.rd_id as rd_id3_0_ from received_data_source receivedda0_ where receivedda0_.rd_id=$1]: $2could not execute query: java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: Timeout
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.vertx.core.Future.lambda$toCompletionStage$2(Future.java:362)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:43)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
	at io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$null$0(SqlConnectionPool.java:202)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool$Cancel.run(SimpleConnectionPool.java:666)
	at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:50)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:240)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.cancel(SimpleConnectionPool.java:629)
	at io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$onEnqueue$1(SqlConnectionPool.java:199)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:893)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:860)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:883)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.vertx.core.impl.NoStackTraceThrowable: Timeout
```

### How to Reproduce?

A reproducer is available here: https://github.com/DavideD/reactive-panache-reproducer

1. `./mvnw clean test`

or

1. `./mvnw quarkus:dev`
2. `http http://localhost:8080/payload/blocking/22`

The first http requst will work, but after several attempts the exception should appear.

### Quarkus version or git rev

2.6.2.Final

### Additional information

I'm using Panache but I think it will happen with any reactive approach

**Comment by Ladicek** [comment]
This is using Hibernate Reactive (with Panache) and RESTEasy Reactive, so CC'ing @cescoffier @Sanne @geoand who hopefully know who should look at this :-)

**Comment by Ladicek** [comment]
Or maybe ignore my comment, sorry I didn't realize who actually filed this issue. Blame quarkus-bot for tagging me! :-)

**Comment by geoand** [comment]
This doesn't look like a RESTEasy Reactive issue, but I don't know much more than that :)

**Comment by DavideD** [comment]
No problem :)
To be honest I'm not sure what's causing the issue so I don't know who should look into this.
This usage is a bit weird but it seems like it's something that should work. Unless I've misunderstood how and where to use `@Blocking`.

**Comment by DavideD** [comment]
Note that `@Blocking` in this case  is not required because the method returns a non reactive object, but it doesn't make any difference.

**Comment by geoand** [comment]
Question: Can Hibernate Reactive work on non event loop threads? I vaguelly remember @Sanne mentioning it doesn't

**Comment by DavideD** [comment]
It depends what one does.

We keep track of the Vert.x instance and context underneath. So, if one uses `.withSession` in a non loop thread, Hibernate Reactive will run the operations in the context it's bound to.

**Comment by DavideD** [comment]
Or create a new context if one doesn't exist

**Comment by cescoffier** [comment]
I don't believe you can use Hibernate Reactive in a blocking endpoint. It would not be able to capture the event loop context (because there is none).

**Comment by geoand** [comment]
Does it result in the same exception?

**Comment by DavideD** [comment]
Yes

**Comment by DavideD** [comment]
Ooops... no sorry. It is slightly different:
```
022-01-20 09:32:30,641 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /payload/reactive/22 failed, error id: d12b52f4-c192-4e31-bd39-bfecc429a633-1: io.smallrye.mutiny.TimeoutException
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:58)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:62)
	at org.acme.hibernate.orm.panache.ReceivedDataPayloadResource.getReactivePart(ReceivedDataPayloadResource.java:19)
	at org.acme.hibernate.orm.panache.ReceivedDataPayloadResource$quarkusrestinvoker$getReactivePart_1039e4cbed5fb782d4cf2f740b3b4a9beed15045.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by geoand** [comment]
Your latest example however is not correct usage TBH.

Instead of 

```java
	@GET
	@Path("/reactive/{rd_id}")
	@Blocking
	public Uni<ReceivedDataPayload> getReactivePart(@PathParam("rd_id") Long rdId) {
		final ReceivedDataPayload rdId1 = ReceivedDataPayload.<ReceivedDataPayload>find( "rdId", rdId )
				.firstResult().await().atMost( Duration.ofSeconds( 2 ) );
		return Uni.createFrom().item( rdId1 );
	}
```

it should be:

```java
	@GET
	@Path("/reactive/{rd_id}")
	@Blocking
	public Uni<ReceivedDataPayload> getReactivePart(@PathParam("rd_id") Long rdId) {
		return ReceivedDataPayload.<ReceivedDataPayload>find( "rdId", rdId )
				.firstResult();
	}
```

If we need to support some kind of `atMost` waiting, we will need to do in another level

**Comment by DavideD** [comment]
Well... of course the reactive approach is the correct one :)

The problem for me is that I cannot find any documentation about `@Blocking` and every time I try to use it, it seems the wrong way. But I expect user to try the things that I've tried.

Should i update the Hibernate Reactive guide and write that `@Blocking` won't work?

**Comment by geoand** [comment]
> Should i update the Hibernate Reactive guide and write that @Blocking won't work?

That is not for me to answer, as I have no idea about how Hibernate Reactive handles things.

But in general, I don't see any reason why one would use Hibernate Reactive and `@Blocking` together, as the whole point of the end to end reactive stack is to be able to stay on the event loop (and thus avoid unnecessary dispatches) and never block it

**Comment by DavideD** [comment]
Ok. I don't think this is a bug. I'm going to close this issue.

**Comment by DavideD** [comment]
Thanks everybody and sorry for the noise

**Comment by geoand** [comment]
YW!
