### ISSUE TITLE
Websocket client not working anymore 

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#23073]
### Describe the bug

Connecting to websocket servers with Quarkus websocket client does not work since 2.4.0.Final and the update to Quarkus HTTP 4.1.3. 
Connecting also does not work in Quarkus version 2.6.3.Final.
With 2.3.1.Final and 2.3.0.Final a connection is still possible.

```
java.io.InterruptedIOException
at io.undertow.websockets.ServerWebSocketContainer.connectToServerInternal(ServerWebSocketContainer.java:457)
at io.undertow.websockets.ServerWebSocketContainer.connectToServerInternal(ServerWebSocketContainer.java:407)
at io.undertow.websockets.ServerWebSocketContainer.connectToServer(ServerWebSocketContainer.java:255)
at io.i15s.example.clients.DevToolsClient.connect(DevToolsClient.java:113)
at io.i15s.example.clients.DevToolsClient.printToPdf(DevToolsClient.java:41)
at io.i15s.example.services.PdfService.createPdf(PdfService.java:44)
at io.i15s.example.services.PdfService_Subclass.createPdf$$superforward1(PdfService_Subclass.zig:230)
at io.i15s.example.services.PdfService_Subclass$$function$$2.apply(PdfService_Subclass$$function$$2.zig:33)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:516)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
at io.i15s.example.services.PdfService_Subclass.createPdf(PdfService_Subclass.zig:436)
at io.i15s.example.services.PdfService_ClientProxy.createPdf(PdfService_ClientProxy.zig:128)
at io.i15s.example.resources.PdfResource.createPdf(PdfResource.java:23)
at io.i15s.example.resources.PdfResource_Subclass.createPdf$$superforward1(PdfResource_Subclass.zig:145)
at io.i15s.example.resources.PdfResource_Subclass$$function$$1.apply(PdfResource_Subclass$$function$$1.zig:33)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:68)
at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor.validateMethodInvocation(ResteasyReactiveEndPointValidationInterceptor.java:21)
at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor_Bean.intercept(ResteasyReactiveEndPointValidationInterceptor_Bean.zig:336)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:516)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
at io.i15s.example.resources.PdfResource_Subclass.createPdf(PdfResource_Subclass.zig:209)
at io.i15s.example.resources.PdfResource_ClientProxy.createPdf(PdfResource_ClientProxy.zig:103)
at io.i15s.example.resources.PdfResource$quarkusrestinvoker$createPdf_ed6fd574c05261b7c5605cbd24c3f7e4171f7d95.invoke(PdfResource$quarkusrestinvoker$createPdf_ed6fd574c05261b7c5605cbd24c3f7e4171f7d95.zig:39)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
Suppressed: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
at io.undertow.websockets.ServerWebSocketContainer.connectToServerInternal(ServerWebSocketContainer.java:441)
... 44 more
Caused by: java.nio.channels.ClosedChannelException
at io.undertow.websockets.WebsocketConnectionBuilder$WebSocketClientHandler.channelInactive(WebsocketConnectionBuilder.java:236)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
at io.netty.handler.codec.MessageAggregator.channelInactive(MessageAggregator.java:438)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:326)
at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
... 2 more
```

**Comment by andlinger** [comment]
Can anyone help me here?

**Comment by gastaldi** [comment]
Can you add a reproducer here?

**Comment by andlinger** [comment]
@gastaldi No problem. Here you go: https://github.com/andlinger/quarkus-reproducer/tree/quarkus-23073

Additional instructions in README.MD

This reproducer works with Quarkus 2.3.1.Final or 2.3.0.Final and returns "Success" on endpoint /websocket

**Comment by gastaldi** [comment]
@stuartwdouglas any ideas? I wonder if those might have been caused by the (not so recent) changes in the WebSockets integration in quarkus-http?

**Comment by gastaldi** [comment]
I have created an integration test that reproduces the error reported here: https://github.com/gastaldi/quarkus/commit/8dfadd8628b10dd74923bd3c174b89928a168cb5

**Comment by stuartwdouglas** [comment]
Fix is here: https://github.com/quarkusio/quarkus-http/pull/94

**Comment by gastaldi** [comment]
I can confirm that fixes the issue. I'll prepare a PR with the dependency bump + the test

**Comment by stuartwdouglas** [comment]
I don't think we want that test, we don't want to bring in random docker images into the build to test something this simple. 

Instead I have updated the Undertow behavior to also reject: https://github.com/quarkusio/quarkus-http/pull/95

This means that all the websocket tests now test this scenario.

**Comment by gastaldi** [comment]
> I don't think we want that test, we don't want to bring in random docker images into the build to test something this simple.

That's fine, it may be simple but it saved me from having to manually reproduce it locally :)
With your new PR the test still passed, so I'm good 😉
