### ISSUE TITLE
ConfigProperty not work when use gradle

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#2322]
quarkus version is after 8d447d47 commit

demo is: https://github.com/qwlabs/quarkus-issue

in src/main/resources/application.properties
```bash
quarkus.datasource.url=jdbc:mariadb://127.0.0.1:3306/fc
quarkus.datasource.driver=org.mariadb.jdbc.Driver
quarkus.datasource.username=root
quarkus.datasource.password=
```
use ConfigProperty in java
```bash
@Path("/users")
@ApplicationScoped
public class UserResource {

    @ConfigProperty(name = "quarkus.datasource.url")
    private String url;
    @ConfigProperty(name = "quarkus.datasource.username")
    private String username;
    @ConfigProperty(name = "quarkus.datasource.password")
    private String password;

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public List<User> list() {
        return User.findAll().list();
    }
}

```

error info 
```bash
2019-05-02 23:46:50,573 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-05-02 23:46:51,284 INFO  [io.qua.arc.pro.BeanProcessor] (build-14) Found unrecommended usage of private members (use package-private instead) in application beans:
        - @Inject field quarkus.modern.gradle.example.GreetingResource#password,
        - @Inject field quarkus.modern.gradle.example.GreetingResource#url,
        - @Inject field quarkus.modern.gradle.example.GreetingResource#username
2019-05-02 23:46:51,551 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 978ms
javax.enterprise.inject.spi.DeploymentException: No config value of type [class java.lang.String] exists for: quarkus.datasource.password
        at io.quarkus.arc.runtime.ConfigDeploymentTemplate.validateConfigProperties(ConfigDeploymentTemplate.java:48)
        at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties14.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:122)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:131)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:84)
2019-05-02 23:46:57,374 ERROR [io.qua.dev.DevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:122)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:131)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:84)
Caused by: javax.enterprise.inject.spi.DeploymentException: No config value of type [class java.lang.String] exists for: quarkus.datasource.password
        at io.quarkus.arc.runtime.ConfigDeploymentTemplate.validateConfigProperties(ConfigDeploymentTemplate.java:48)
        at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties14.deploy(Unknown Source)
        ... 5 more
```

**Comment by pipinet** [comment]
change ConfigProperty target to Optional . work!
```bash
@ConfigProperty(name = "quarkus.datasource.password")
    private Optional<String> mayPassword;
```
