### ISSUE TITLE
opentracing - java.net.UnknownHostException in native mode, not in JVM mode

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2333]
When Playing with https://github.com/quarkusio/quarkus/issues/2218#issuecomment-488259704 reproducer via quarkus-quickstarts/using-opentracing I noticed UnknownHostException in native mode(1.0.0-rc-16), not in JVM mode

I'm at home and my hostname is set to RS, no dns around.
Of course when I update my /etc/hosts this issues goes away even for native mode.
But sometimes users don't have rights to edit /etc/hosts or they don't know they can do it.

Anyway it's strange JVM mode and Native mode differ in hostname lookup ++ it can ruin a bit first impression from Quarkus and native mode.

```
2019-05-03 12:24:19,115 ERROR [io.jae.int.JaegerTracer] (executor-thread-1) Cannot obtain host name: java.net.UnknownHostException: RS: RS
	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
	at io.jaegertracing.internal.JaegerTracer.getHostName(JaegerTracer.java:685)
	at io.jaegertracing.internal.JaegerTracer.<init>(JaegerTracer.java:100)
...
Caused by: java.net.UnknownHostException: RS
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:3439)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
```

**Comment by rsvoboda** [comment]
GraalVM/Substrate VM simple example confirms it's native image bug.

```java
import java.net.InetAddress;
import java.net.UnknownHostException;
public class AbcMain {
    public static void main(String[] args) throws UnknownHostException {
        InetAddress inetAddress = InetAddress.getLocalHost();
        System.out.println("IP of my system is: " + inetAddress.getHostAddress());
        System.out.println("Name of my system is: " + inetAddress.getHostName());
    }
}
```

```
java -cp . AbcMain
IP of my system is: 10.20.30.101
Name of my system is: RS
```

```
native-image --no-server AbcMain
 ...
./abcmain
Exception in thread "main" java.net.UnknownHostException: RS: RS
	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
	at AbcMain.main(AbcMain.java:7)
Caused by: java.net.UnknownHostException: RS
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:3439)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
	... 1 more
```

**Comment by stuartwdouglas** [comment]
This should likely be reported in the Graal tracker

**Comment by rsvoboda** [comment]
OK, going to create one, wanted to report it here first.

**Comment by rsvoboda** [comment]
https://github.com/oracle/graal/issues/1338

**Comment by rsvoboda** [comment]
Fixed in released GraalVM

https://github.com/bobmcwhirter/graal/commit/6efe23d1038238ef0cebd4c18be8a3bca696e9ef
https://github.com/oracle/graal/commit/1976639d80685eb3de77bc5a9c6c7930e5e9df08
https://github.com/oracle/graal/blame/vm-19.1.1/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNetSubstitutions.java#L3605
