### ISSUE TITLE
"Request has already been read" using vertx + auth

### ISSUE THREAD

**Issue by rolintoucour** [quarkusio/quarkus#23360]
### Describe the bug

When I use a vertx Verticle route + jdbc authent, I got an error `java.lang.IllegalStateException: Request has already been read`.

I repeated the issue in a minimalist project that sets up a Verticle + JDBC authent. 

When I comment the line  `quarkus.http.auth.permission.roles1.paths=/*` then the error disappears.

My interpretation is that BodyHandler must be attached at first in a router, thus using jdbc-authent it reads the body before I can attach the BodyHandler. However as the router is injected into my verticle, I have no way to do it (maybe I am totally wrong).

### Expected behavior

It shouldn't throw an exception. Using jdbc-auth, I should be able to read the body of requests from my verticle router's handlers.

### Actual behavior

It throws the following exception:

```
2022-02-02 09:26:04,963 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /test failed, error id: 7f4953c3-e074-43b7-8fa5-e1d069ffc4cd-1: java.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.Http1xServerRequest.checkEnded(Http1xServerRequest.java:651)
	at io.vertx.core.http.impl.Http1xServerRequest.endHandler(Http1xServerRequest.java:338)
	at io.quarkus.vertx.http.runtime.ResumingRequestWrapper.endHandler(ResumingRequestWrapper.java:48)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.endHandler(HttpServerRequestWrapper.java:128)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:86)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:44)
	at io.vertx.reactivex.ext.web.handler.BodyHandler.handle(BodyHandler.java:94)
	at io.vertx.reactivex.ext.web.handler.BodyHandler.handle(BodyHandler.java:50)
	at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:181)
	at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:179)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1193)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:362)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:340)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1193)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:121)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:138)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:127)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:72)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.subscribe(UniMemoizeOp.java:66)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:50)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:90)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:127)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.checkPermission(HttpAuthorizer.java:104)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:227)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:219)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1193)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:152)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:113)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.drain(UniMemoizeOp.java:152)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.onItem(UniMemoizeOp.java:172)
	at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
	at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl$1$1$1$1.run(QuarkusIdentityProviderManagerImpl.java:58)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

1. Check out https://github.com/rolintoucour/quarkus_request_already_read
2. Launch test `GreetingResourceTest.testHelloEndpoint()`
3. Check the log
4. Uncomment the property `quarkus.http.auth.permission.roles1.paths=/*`
5. Test now passes fine

### Output of `uname -a` or `ver`

Linux netwave-lolo 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17 2021-09-14 OpenJDK Runtime Environment Temurin-17+35 (build 17+35) OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

### Quarkus version or git rev

2.6.3

**Comment by sberyozkin** [comment]
CC @stuartwdouglas

**Comment by geoand** [comment]
I tried this and the tests pass... 

Are you able to consistently reproduce this problem?

**Comment by rolintoucour** [comment]
Yes, I always have the issue. Maybe it is related to my system in some way.

**Comment by rolintoucour** [comment]
I can reproduce the issue consistently with a VM on GCP, if that might help:
- I create a VM of type e2-small
- in zone europe-west1-b
- usung image ubuntu 20.04 (ubuntu-2004-focal-v20220204)
- basic setup otherwise

Then on the this VM I run the following:

```bash
sudo apt update && sudo apt upgrade
sudo apt install wget
wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz
tar -xvf OpenJDK17U-jdk_x64_linux_hotspot_17.*.tar.gz
sudo mv jdk-17.0.1+12 /opt/
export JAVA_HOME=/opt/jdk-17.0.1+12
export PATH=$PATH:$JAVA_HOME/bin 

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
sudo chmod 777 /var/run/docker.sock

git clone https://github.com/rolintoucour/quarkus_request_already_read
cd quarkus_request_already_read/
./mvnw clean test
```

The error logged is:

```
2022-02-14 14:45:04,881 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /test failed, error id: 4d434897-2fee-4062-82b7-ba9fa783f5d0-1: java.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.Http1xServerRequest.checkEnded(Http1xServerRequest.java:651)
	at io.vertx.core.http.impl.Http1xServerRequest.endHandler(Http1xServerRequest.java:338)
	at io.quarkus.vertx.http.runtime.ResumingRequestWrapper.endHandler(ResumingRequestWrapper.java:48)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.endHandler(HttpServerRequestWrapper.java:128)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:86)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:44)
	at io.vertx.reactivex.ext.web.handler.BodyHandler.handle(BodyHandler.java:94)
	at io.vertx.reactivex.ext.web.handler.BodyHandler.handle(BodyHandler.java:50)
	at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:181)
	at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:179)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1193)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:362)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:340)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1193)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:121)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:138)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:127)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:72)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.subscribe(UniMemoizeOp.java:66)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:50)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:90)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:127)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.checkPermission(HttpAuthorizer.java:104)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:227)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:219)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1193)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:152)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:113)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.drain(UniMemoizeOp.java:152)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.onItem(UniMemoizeOp.java:172)
	at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
	at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl$1$1$1$1.run(QuarkusIdentityProviderManagerImpl.java:58)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 33.504 s <<< FAILURE! - in org.acme.getting.started.GreetingResourceTest
[ERROR] org.acme.getting.started.GreetingResourceTest.testHelloEndpoint  Time elapsed: 3.214 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.

	at org.acme.getting.started.GreetingResourceTest.testHelloEndpoint(GreetingResourceTest.java:20)

2022-02-14 14:45:05,165 INFO  [io.quarkus] (main) Quarkus stopped in 0.094s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   GreetingResourceTest.testHelloEndpoint:20 1 expectation failed.
Expected status code <200> but was <500>.

[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  46.189 s
[INFO] Finished at: 2022-02-14T14:45:05Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project getting-started: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/lthiebaud/quarkus_request_already_read/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by iompo** [comment]
The error does not happen if i use Uni.createFrom().emitter instead of the context.runBlocking, emitting a fail event instead of throwing the exception.

**Comment by iriikoad** [comment]
> The error does not happen if i use Uni.createFrom().emitter instead of the context.runBlocking, emitting a fail event instead of throwing the exception.

Can you describe how you do this?

ps: Still error with Quarkus 2.11

```
ava.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.Http2ServerRequest.checkEnded(Http2ServerRequest.java:263)
	at io.vertx.core.http.impl.Http2ServerRequest.pause(Http2ServerRequest.java:300)
	at io.quarkus.vertx.http.runtime.ResumingRequestWrapper.pause(ResumingRequestWrapper.java:28)
	at io.quarkus.vertx.http.runtime.AbstractRequestWrapper.pause(AbstractRequestWrapper.java:59)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.pause(HttpServerRequestWrapper.java:114)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.<init>(VertxResteasyReactiveRequestContext.java:79)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.<init>(QuarkusResteasyReactiveRequestContext.java:27)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$5.createContext(ResteasyReactiveRecorder.java:164)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:46)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
```

**Comment by iompo** [comment]
First you send a an event on the event bus:
```
public class DbUserPasswordIdentityProvider implements IdentityProvider<UsernamePasswordAuthenticationRequest> {

    @Inject EventBus eventBus;

    @Override
    public Class<UsernamePasswordAuthenticationRequest> getRequestType() {
        return UsernamePasswordAuthenticationRequest.class;
    }

    @Override
    public Uni<SecurityIdentity> authenticate(UsernamePasswordAuthenticationRequest request, AuthenticationRequestContext context) {
        return eventBus.<AppUser>request(AuthenticationEvents.AUTHENTICATE_CREDENTIALS, request).onItem().transform(this::fromAppUser);
    }

    private SecurityIdentity fromAppUser(Message<AppUser> appUserMessage) {
        return QuarkusSecurityIdentity.builder()
                .addRole("user")
                .setPrincipal(new QuarkusPrincipal(appUserMessage.body().getUsername()))
                .build();
    }
}
```

And then you handle the authentication request, sending back the required info to create a security identity, or an exception if the credentials are wrong:
```
@Dependent
public class RequestAuthenticator {

    @Inject
    EntityManagerFactory entityManagerFactory;

    @ConsumeEvent(value = AuthenticationEvents.AUTHENTICATE_CREDENTIALS, blocking = true)
    public AppUser authenticateUserPassword(UsernamePasswordAuthenticationRequest userPasswordRequest) {
        EntityManager entityManager = getReadOnlyEntityManager();
        try {
            return getUserFromUsername(entityManager, userPasswordRequest.getUsername());
        } finally {
            entityManager.close();
        }
    }

    @ConsumeEvent(value = AuthenticationEvents.AUTHENTICATE_TRUSTED, blocking = true)
    public AppUser authenticateTrusted(TrustedAuthenticationRequest trustedRequest) {
        EntityManager entityManager = getReadOnlyEntityManager();
        try {
            return getUserFromUsername(entityManager, trustedRequest.getPrincipal());
        } finally {
            entityManager.close();
        }
    }

    private AppUser getUserFromUsername(EntityManager entityManager, String username) {
        TypedQuery<AppUser> query = entityManager.createQuery("SELECT u from AppUser u where u.username = :username", AppUser.class);
        query.setParameter("username", username);
        List<AppUser> users = query.getResultList();
        if (!users.isEmpty()) {
            return users.get(0);
        } else {
            throw new AuthenticationFailedException("Invalid credentials");
        }
    }

    private EntityManager getReadOnlyEntityManager() {
        EntityManager readOnly = entityManagerFactory.createEntityManager();
        ((Session) readOnly).setHibernateFlushMode(FlushMode.MANUAL);
        ((Session) readOnly).setDefaultReadOnly(true);

        return readOnly;
    }

}
```

**Comment by iriikoad** [comment]
Sorry for the late answer.

I see what you mean, so I tried to use a custom HttpAuthenticationMechanism that calls FormAuthenticationMechanism.

If I throw an AuthenticationFailedException in the function **authenticate**, I can see the 401 response.
But I can't manage to use the **FormAuthenticationMechanism** function to throw the AuthenticationFailedException in this function as FormAuthenticationMechanism use an other thread to read the request.


```java
@Alternative
@Priority(1)
@ApplicationScoped
public class CustomFormAuthMechanism implements HttpAuthenticationMechanism {
    @Inject
    FormAuthenticationMechanism delegate;
    @Override
    public Uni<SecurityIdentity> authenticate(RoutingContext context, IdentityProviderManager identityProviderManager) {

      // throw new AuthenticationFailedException()  here will work... but how to use FormAuthenticationMechanism  ?

      Uni<SecurityIdentity> uni= delegate.authenticate(context, identityProviderManager);
       // I do I throw an exception in this function if the form authenticate throw an error???
       return uni;
   }
```

**Comment by iriikoad** [comment]
After debugging, it's in the **HttpAuthenticator**, method **sendChallenge**: 
```java
public Uni<Boolean> sendChallenge(RoutingContext routingContext) {
routingContext.request().resume(); ///-> this will throw the error
```

**Comment by geoand** [comment]
@sberyozkin ^

**Comment by michalvavrik** [comment]
Hmm, I remember I was already debugging it few months ago and abandon it for some reason. I'll look again and let you know.

**Comment by iriikoad** [comment]
ok.. to avoid this, i re-write the io.quarkus.vertx.http.runtime.security.HttpAuthenticator.DefaultAuthFailureHandler with a 'catch' and give it to the request in the method authenticate:

```java
@Alternative
@Priority(1)
@ApplicationScoped
public class CustomFormOrJwtAuthMechanism implements HttpAuthenticationMechanism {


@Override
    public Uni<SecurityIdentity> authenticate(RoutingContext context, IdentityProviderManager identityProviderManager) {
        //change the error handler
        context.put(QuarkusHttpUser.AUTH_FAILURE_HANDLER, new DefaultAuthFailureHandler(this));
    }

    public static final class DefaultAuthFailureHandler implements BiConsumer<RoutingContext, Throwable> {

        CustomFormOrJwtAuthMechanism meca;

        private DefaultAuthFailureHandler(CustomFormOrJwtAuthMechanism m) {
            this.meca = m;
        }

       @Override
        public void accept(RoutingContext event, Throwable throwable) {
            throwable = extractRootCause(throwable);
            // auth failed
            if (throwable instanceof AuthenticationFailedException) {

                // we want to consume any body content if present
                // challenges won't read the body, and if we don't consume
                // things can get stuck
                try {
                    event.request().resume();
                } catch (Exception e) {
                    // may happen in HTTP2: 'Request has already been read'
                }
...

```

**Comment by iriikoad** [comment]
I updated to 2.16.0.Final, still same issue with same exception.

I use this:
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-security</artifactId>
        </dependency>

<!-- to simplify logins (dev only) -->
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-elytron-security-properties-file</artifactId>
</dependency>

```
```
quarkus.http.auth.form.enabled=true

```

**Comment by michalvavrik** [comment]
ah, sorry @iriikoad I didn't mention you just commented here, not created issue. Can you provide full reproducer - link to github project, please? we have countless tests with configuration that you mentioned that are passing, therefore you can imagine it's not enough information!

**Comment by iriikoad** [comment]
I just created a project
https://github.com/iriikoad/quarkus-reproduce-err-timeout
Run `mvn quarkus:dev`and follow the readme.

**Comment by michalvavrik** [comment]
@iriikoad thanks for reproducer, it helped
