### ISSUE TITLE
java.lang.UnsupportedOperationException com.vladmihalcea.hibernate.type.json.internal.JsonSqlTypeDescriptor with Hibernate Reactive

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#23403]
### Describe the bug

I'm trying to use `implementation 'com.vladmihalcea:hibernate-types-52:2.14.0'` from https://github.com/vladmihalcea/hibernate-types in my application, which previously worked with the non-reactive dependencies.

```
@Getter
@Setter
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "my_entity")
@TypeDefs({
        @TypeDef(name = "json", typeClass = JsonType.class)
})
public class MyEntity extends PanacheEntity {

    @Type(type = "json")
    @Column(columnDefinition = "jsonb")
    private Map<String, Object> properties = new HashMap<>();

}


```

```
2022-02-03 08:42:19,971 ERROR [com.lau.aut.reg.RegistrationResource] (vert.x-eventloop-thread-9) Failed to register user: javax.persistence.PersistenceException: org.hibernate.HibernateException: java.lang.UnsupportedOperationException
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.reactive.session.impl.ReactiveExceptionConverter.convert(ReactiveExceptionConverter.java:31)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.lambda$doFlush$32(ReactiveSessionImpl.java:895)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:144)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.doFlush(ReactiveSessionImpl.java:890)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.reactiveAutoflush(ReactiveSessionImpl.java:875)
	at org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.flush(MutinySessionImpl.java:451)
	at org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.lambda$execute$1(MutinySessionImpl.java:437)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.groups.UniOnItem.lambda$call$3(UniOnItem.java:99)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.groups.UniOnItem.lambda$call$2(UniOnItem.java:79)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:46)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.vertx.core.Future.lambda$toCompletionStage$2(Future.java:360)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:102)
	at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:35)
	at io.vertx.core.Promise.complete(Promise.java:66)
	at io.vertx.core.Promise.handle(Promise.java:51)
	at io.vertx.core.Promise.handle(Promise.java:29)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
	at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
	at io.vertx.sqlclient.impl.command.CommandResponse.fire(CommandResponse.java:46)
	at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:287)
	at io.vertx.pgclient.impl.PgSocketConnection.handleMessage(PgSocketConnection.java:96)
	at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:99)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:394)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:156)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:87)
	at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:139)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:237)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:96)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.hibernate.HibernateException: java.lang.UnsupportedOperationException
	... 90 more
Caused by: java.lang.UnsupportedOperationException
	at org.hibernate.reactive.adaptor.impl.PreparedStatementAdaptor.getConnection(PreparedStatementAdaptor.java:508)
	at com.vladmihalcea.hibernate.type.json.internal.JsonSqlTypeDescriptor$1.doBind(JsonSqlTypeDescriptor.java:31)
	at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:73)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:276)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:271)
	at org.hibernate.type.AbstractSingleColumnStandardBasicType.nullSafeSet(AbstractSingleColumnStandardBasicType.java:39)
	at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:3073)
	at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:3048)
	at org.hibernate.reactive.persister.entity.impl.ReactiveAbstractEntityPersister.lambda$insertReactive$15(ReactiveAbstractEntityPersister.java:361)
	at org.hibernate.reactive.adaptor.impl.PreparedStatementAdaptor.bind(PreparedStatementAdaptor.java:53)
	at org.hibernate.reactive.persister.entity.impl.ReactiveAbstractEntityPersister.insertReactive(ReactiveAbstractEntityPersister.java:359)
	at org.hibernate.reactive.persister.entity.impl.ReactiveAbstractEntityPersister.lambda$null$13(ReactiveAbstractEntityPersister.java:316)
	at org.hibernate.reactive.util.impl.CompletionStages$ArrayLoop.next(CompletionStages.java:396)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline.lambda$asyncWhile$1(AsyncTrampoline.java:215)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.unroll(AsyncTrampoline.java:121)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.trampoline(AsyncTrampoline.java:102)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.access$200(AsyncTrampoline.java:85)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline.asyncWhile(AsyncTrampoline.java:197)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline.asyncWhile(AsyncTrampoline.java:215)
	at org.hibernate.reactive.util.impl.CompletionStages.loop(CompletionStages.java:356)
	at org.hibernate.reactive.util.impl.CompletionStages.loop(CompletionStages.java:340)
	at org.hibernate.reactive.persister.entity.impl.ReactiveAbstractEntityPersister.lambda$insertReactive$14(ReactiveAbstractEntityPersister.java:314)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
	at org.hibernate.reactive.persister.entity.impl.ReactiveAbstractEntityPersister.insertReactive(ReactiveAbstractEntityPersister.java:295)
	at org.hibernate.reactive.engine.impl.ReactiveEntityRegularInsertAction.lambda$reactiveExecute$4(ReactiveEntityRegularInsertAction.java:69)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
	at org.hibernate.reactive.engine.impl.ReactiveEntityRegularInsertAction.reactiveExecute(ReactiveEntityRegularInsertAction.java:54)
	at org.hibernate.reactive.engine.ReactiveActionQueue.lambda$executeActions$8(ReactiveActionQueue.java:695)
	at org.hibernate.reactive.util.impl.CompletionStages$ArrayLoop.next(CompletionStages.java:396)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline.lambda$asyncWhile$1(AsyncTrampoline.java:215)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.unroll(AsyncTrampoline.java:121)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.trampoline(AsyncTrampoline.java:102)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.access$200(AsyncTrampoline.java:85)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline.asyncWhile(AsyncTrampoline.java:197)
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline.asyncWhile(AsyncTrampoline.java:215)
	at org.hibernate.reactive.util.impl.CompletionStages.loop(CompletionStages.java:356)
	at org.hibernate.reactive.util.impl.CompletionStages.loop(CompletionStages.java:340)
	at org.hibernate.reactive.engine.ReactiveActionQueue.executeActions(ReactiveActionQueue.java:692)
	at org.hibernate.reactive.engine.ReactiveActionQueue.lambda$executeActions$6(ReactiveActionQueue.java:592)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
	at org.hibernate.reactive.engine.ReactiveActionQueue.executeActions(ReactiveActionQueue.java:592)
	at org.hibernate.reactive.event.impl.AbstractReactiveFlushingEventListener.lambda$performExecutions$0(AbstractReactiveFlushingEventListener.java:64)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
	at org.hibernate.reactive.event.impl.AbstractReactiveFlushingEventListener.performExecutions(AbstractReactiveFlushingEventListener.java:58)
	at org.hibernate.reactive.event.impl.DefaultReactiveFlushEventListener.lambda$reactiveOnFlush$0(DefaultReactiveFlushEventListener.java:42)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
	at org.hibernate.reactive.event.impl.DefaultReactiveFlushEventListener.reactiveOnFlush(DefaultReactiveFlushEventListener.java:42)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.lambda$fireEventOnEachListener$0(EventListenerGroupImpl.java:133)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:133)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.doFlush(ReactiveSessionImpl.java:886)
	... 83 more
```

Are there any plans to support those types or is it rather something that has to be done on Vlad Mihalcea's side?

**Comment by Sanne** [comment]
Sorry, you can't use this extension with Hibernate Reactive, as it's not based on JDBC.

I'll close this for now; perhaps there is something we will be able to do, but if we're to develop a new solution in this area, it should be based on Hibernate ORM 6, so it might be similar but not based on the current hibernate types project.

**Comment by mklueh** [comment]
@Sanne got it. Is there any other recommended way on how to deal with JSON types?

**Comment by DavideD** [comment]
You can map Json using `io.vertx.core.json.JsonObject`.
You can check [one of our tests](https://github.com/hibernate/hibernate-reactive/blob/a94960a0628ab6e6fdb7a76c882d493c5514df07/hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/JsonTypeTest.java#L94) for an example:
```
@Entity
class Basic {

    private JsonObject jsonObj;
...
}
```

Or you can create a `UserType`. Here's [an example taken from our tests](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/Json.java). You can then register the new type using annotations:
```
	@Type(type="org.hibernate.reactive.types.Json")
	private JsonObject jsonObj;
```

**Comment by DavideD** [comment]
On second thought, an attribute converter is an easier approach in this case: http://hibernate.org/reactive/documentation/1.1/reference/html_single/#_attribute_converters

**Comment by mklueh** [comment]
> On second thought, an attribute converter is an easier approach in this case: http://hibernate.org/reactive/documentation/1.1/reference/html_single/#_attribute_converters

Thanks alot for your help @DavideD 

So JsonObject should be the target type and String the source type of the JSON column when using the converter approach?

Can the PostgreSQL column still be of type JSON/JSONB or do they have to be of type varchar/text then?

**Comment by DavideD** [comment]
Not necessarly a String. If you want a map, something like this should work:
```
public class MapJsonConverter implements AttributeConverter<Map, JsonObject> {

    @Override
    public JsonObject convertToDatabaseColumn(Map map) {
        return new JsonObject(map);
    }

    @Override
    public Map convertToEntityAttribute(JsonObject jsonObject) {
        return jsonObject.getMap();
    }
}
```

But you can use a String if you prefer.

> Can the PostgreSQL column still be of type JSON/JSONB or do they have to be of type varchar/text then?

Hibernate Reactive maps a field of type `JsonObject` to a column of type `json` as the default for Postgres

**Comment by mklueh** [comment]
> Hibernate Reactive maps a field of type `JsonObject` to a column of type `json` as the default for Postgres

This is exactly what I wanted. Using String for the json type is wrong and escapes all quotes.

The only problem is, IntelliJ does complain because it doesn't know that the JsonObject type is mapped to json.

![image](https://user-images.githubusercontent.com/1553757/152487832-525dde3b-f2ad-47be-aa4b-6632c616a2df.png)

**Its still working and the warning can be ignored, or one can just create a fake converter that maps from JsonObject to JsonObject**

```
@Converter
public class JsonObjectAsStringTypeConverter implements AttributeConverter<JsonObject, JsonObject> {
    @Override
    public JsonObject convertToDatabaseColumn(JsonObject attribute) {
        return attribute;
    }

    @Override
    public JsonObject convertToEntityAttribute(JsonObject dbData) {
        return dbData;
    }
}
```

Thanks for your help @DavideD

**Comment by DavideD** [comment]
Not sure which plugin is causing the exception but 
I guess it's because it is a JPA plugin? It's a bit annoying but I would expect it to be possible to disable the warning in IntelliJ instead of using a converter. You might try to check with the plugin developers.

Anyway, whatever works.
