### ISSUE TITLE
quarkus 2.7 - quarkus-reactive-oracle-client - Wrong syntax of connection URI

### ISSUE THREAD

**Issue by alissonmelonascimento** [quarkusio/quarkus#23439]
### Describe the bug

```posh
2022-02-04 10:47:10,406 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalArgumentException: Wrong syntax of connection URI
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.doParse(OracleConnectionUriParser.java:76)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:48)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:40)
	at io.vertx.oracleclient.OracleConnectOptions.fromUri(OracleConnectOptions.java:54)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.toOracleConnectOptions(OraclePoolRecorder.java:93)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.initialize(OraclePoolRecorder.java:56)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.configureOraclePool(OraclePoolRecorder.java:38)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:834)

Press [space] to restart, [e] to edit command line args (currently ''), [r] to resume testing, [o] Toggle test output, [h] for more options>
2022-02-04 10:47:12,923 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:122)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:145)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:456)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:150)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:106)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Cannot parse invalid connection URI: oracle:thin:@abcdefg01-scan4.my.domain.com:1521/ora01
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:54)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:40)
	at io.vertx.oracleclient.OracleConnectOptions.fromUri(OracleConnectOptions.java:54)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.toOracleConnectOptions(OraclePoolRecorder.java:93)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.initialize(OraclePoolRecorder.java:56)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.configureOraclePool(OraclePoolRecorder.java:38)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy(Unknown Source)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Wrong syntax of connection URI
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.doParse(OracleConnectionUriParser.java:76)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:48)
	... 20 more

2022-02-04 10:47:12,923 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:122)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:145)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:456)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:150)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:106)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Cannot parse invalid connection URI: oracle:thin:@abcdefg01-scan4.my.domain.com:1521/ora01
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:54)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:40)
	at io.vertx.oracleclient.OracleConnectOptions.fromUri(OracleConnectOptions.java:54)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.toOracleConnectOptions(OraclePoolRecorder.java:93)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.initialize(OraclePoolRecorder.java:56)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.configureOraclePool(OraclePoolRecorder.java:38)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy(Unknown Source)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Wrong syntax of connection URI
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.doParse(OracleConnectionUriParser.java:76)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:48)
	... 20 more
```

### Expected behavior

Connection successfully

### Actual behavior

connection error

### How to Reproduce?

Try connecting to an oracle database using a URL with this pattern:
oracle:thin:@abcdefg01-scan4.my.domain.com:1521/ora01

#application.properties
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=user
quarkus.datasource.password=123456
quarkus.datasource.reactive.url=oracle:thin:@abcdefg01-scan4.my.domain.com:1521/ora01

### Output of `java -version`

JDK 11

### Quarkus version or git rev

2.7

**Comment by geoand** [comment]
The URL you are using is wrong, it needs to `vertx-reactive:oracle:thin:@abcdefg01-scan4.my.domain.com:1521/ora01`

**Comment by alissonmelonascimento** [comment]
> The URL you are using is wrong, it needs to `vertx-reactive:oracle:thin:@abcdefg01-scan4.my.domain.com:1521/ora01`

Thanks for the tip, but the error persists.
I believe the problem is in the **OracleConnectionUriParser** class, constant **FULL_URI_PATTERN**

```
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=user
quarkus.datasource.password=password
quarkus.datasource.reactive.url=vertx-reactive:oracle:thin:@abcdefg01-scan4.my.domain.com:1521/ora01
```

Error

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-02-07 09:52:08,842 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2022-02-07 09:52:08,843 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalArgumentException: Wrong syntax of connection URI
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.doParse(OracleConnectionUriParser.java:76)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:48)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:40)
	at io.vertx.oracleclient.OracleConnectOptions.fromUri(OracleConnectOptions.java:54)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.toOracleConnectOptions(OraclePoolRecorder.java:93)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.initialize(OraclePoolRecorder.java:56)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.configureOraclePool(OraclePoolRecorder.java:38)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:834)

Press [space] to restart, [e] to edit command line args (currently ''), [r] to resume testing, [o] Toggle test output, [h] for more options>
2022-02-07 09:52:12,560 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:122)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:145)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:456)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:150)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:106)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Cannot parse invalid connection URI: oracle:thin:@abcdefg01-scan4.my.domain.com:1521/ora01                                
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:54)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:40)
	at io.vertx.oracleclient.OracleConnectOptions.fromUri(OracleConnectOptions.java:54)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.toOracleConnectOptions(OraclePoolRecorder.java:93)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.initialize(OraclePoolRecorder.java:56)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.configureOraclePool(OraclePoolRecorder.java:38)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy(Unknown Source)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Wrong syntax of connection URI
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.doParse(OracleConnectionUriParser.java:76)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:48)
	... 20 more

2022-02-07 09:52:12,560 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:122)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:145)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:456)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:67)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:150)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:106)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Cannot parse invalid connection URI: oracle:thin:@abcdefg01-scan4.my.domain.com:1521/ora01                                
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:54)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:40)
	at io.vertx.oracleclient.OracleConnectOptions.fromUri(OracleConnectOptions.java:54)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.toOracleConnectOptions(OraclePoolRecorder.java:93)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.initialize(OraclePoolRecorder.java:56)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.configureOraclePool(OraclePoolRecorder.java:38)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy(Unknown Source)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Wrong syntax of connection URI
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.doParse(OracleConnectionUriParser.java:76)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:48)
	... 20 more
```

**Comment by tsegismont** [comment]
@alissonmelonascimento please `oracle:thin:@abcdefg01-scan4.my.domain.com:1521:ora01`

**Comment by alissonmelonascimento** [comment]
> 

Thanks @tsegismont !
