### ISSUE TITLE
NullPointerException when upgrading to 2.7.0 with Quartz in JDBC_CMT mode

### ISSUE THREAD

**Issue by jendib** [quarkusio/quarkus#23457]
### Describe the bug

I had an app running Quarkus 2.6.1 with Quartz scheduler configured like this:
```
quarkus.quartz.clustered=true
quarkus.quartz.store-type=jdbc_cmt
```
after upgrading to 2.7.0 I'm getting this error on boot:
```
2022-02-05 13:18:12,819 ERROR [io.qua.run.Application] (main) Failed to start application (with profile staging): java.lang.NullPointerException
	at io.quarkus.quartz.runtime.QuartzScheduler.<init>(QuartzScheduler.java:206)
	at io.quarkus.quartz.runtime.QuartzScheduler_Bean.create(Unknown Source)
	at io.quarkus.quartz.runtime.QuartzScheduler_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:101)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.quartz.runtime.QuartzScheduler_Observer_start_09e6c17011ef77dec3e1dd9987380b3d946e3db6.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
```

Please note that the error doesn't occur with a fresh database (and no qrtz_* tables).

### Output of `java -version`

OpenJDK 11

### Quarkus version or git rev

2.7.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by machi1990** [comment]
I am very curious how this could have happened.

Looks like a record from qrtz_triggeres table was deleted. However my attempt to reproduce it using the quartz quickstarts which has the same configuration as the one you shared was not successful and couldn't reproduce the NPE. 

> Please note that the error doesn't occur with a fresh database (and no qrtz_* tables).

Would you mind sharing a small reproducer, and I'll investigate further.  Thanks

**Comment by jendib** [comment]
@machi1990 If I clear the quartz tables it should recreate the triggers no? As a workaround so my app can start

**Comment by machi1990** [comment]
> @machi1990 If I clear the quartz tables it should recreate the triggers no? As a workaround so my app can start

Yes, starting with empty quartz tables should enable your app to work. 

Though I am very curious to see if there is something that will need fixing in the quartz extension. To be able to do that, I'll need your help with a small reproducer for your app (the qrtz tables plus the scheduled methods - they could be empty with business logic stripped out).

**Comment by gsmet** [comment]
In any case, it needs fixing. Be it by adding a proper error message.

**Comment by jendib** [comment]
The Quartz table have been created using this: <https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/resources/org/quartz/impl/jdbcjobstore/tables_postgres.sql>

and my scheduled methods look like like:
```java
@Scheduled(cron = "0 1 9 1/1 * ? *", identity = "discord-update-job")
public void discordUpdate() {
  ...
}
```
I didn't do anything fancy like editing manually Quartz tables, it's all default. I'll try to see if I can make a reproducer.

**Comment by KyriacosP** [comment]
We were facing the same issue after upgrading from 1.11.2.FINAL to 2.7.1.FINAL. After some debugging we found out that the issue was happening only with jobs that were created using annotations. When the `QuartzScheduler` constructor tries to find the triggers for existing Jobs it uses as key the name of the job. It seems that in earlier version this key was suffixed with `_trigger` to create the trigger names. So for jobs that were created in earlier versions that their triggers have the suffix `_trigger` in their name you get a `NullPointerException` in `QuartzScheduler  line 206`.

We manage to get around this by manually deleting the job and triggers entries from the db. First we delete the job details from `qrtz_job_details` and then we deleted the cron trigger from `qrtz_cron_triggers` and finally the trigger from `qrtz_triggers` and then let `Quartz` recreate them on startup.

This is not a solution though since it will be nearly impossible to do this manually for all of our schedulers

**Comment by jendib** [comment]
@KyriacosP From what I remember this `_trigger` was removed after the 2.x release. I had the same issue too (undocumented breaking change by the way). I may be wrong, but I think the issue I described in this ticket is yet another one. Thanks for the workaround 👍

**Comment by mkouba** [comment]
> @gsmet I checked my git log and it was in release 2.1.0

@jendib Yes, the `_trigger` suffix was removed in this [commit](https://github.com/quarkusio/quarkus/commit/4954679a77c4a0a77caabc70f5747d45139e7cb1) in 2.1.CR1. Another workaround would be to append the `_trigger` suffix to the `@Scheduled#identity()` value (this should result in the same trigger key in 2.7+). Also note that we don't guarantee the compatibility for quartz clustering accross major and minor versions of Quarkus.

> @mkouba @machi1990 could you make sure this is documented in the migration guide in which this change was introduced?

Yes, it should go into https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.1.

**Comment by jendib** [comment]
@machi1990 Unfortunately I didn't. I will try to reproduce by copying my tables from staging environment (content included). It might come from the fact that those tables were populated with Quarkus 1.x.

**Comment by machi1990** [comment]
> @machi1990 Unfortunately I didn't. I will try to reproduce by copying my tables from staging environment (content included). It might come from the fact that those tables were populated with Quarkus 1.x.

Perfect, thank you @jendib for doing it. Once you manage to reproduce it, do you think it might be possible share the qrtz_xx related content? Only those with the business data stripped out.

**Comment by machi1990** [comment]
Thanks @jendib indeed, the issue was due to the renaming of `_trigger`. 

> but I guess Quarkus should at least provide an explicit log message to indicate that (or even better do the migration by itself).

I'll provide the PR that will offer a migration support. I went this way to reduce the toil that the user will have to do. This is only an exception case where the extension will have to perform the migration. The temporary code will reschedule the old trigger i.e the one with the `_trigger` suffix to a new one without the suffix. This shouldn't impact in any way the application and should be transparent to the user. I'll appreciate your feedback on the PR which I'll open. I've verified that it indeed fixes the issue on the reproducer. I'll need a second eye on the verification.
