### ISSUE TITLE
Vert.x DnsResolver fails on Quarkus 2.7.0 because jndi is disabled

### ISSUE THREAD

**Issue by computerlove** [quarkusio/quarkus#23519]
### Describe the bug

Vert.x use jndi to lookup dns servers, since jndi is disabled by default `DefaultDnsServerAddressStreamProvider` falls back to Google DNS. If these are not reachable from the application it crash with
```
Feb 08, 2022 12:43:55 PM io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider
WARN: Default DNS servers: [/8.8.8.8:53, /8.8.4.4:53] (Google Public DNS as a fallback)
Feb 08, 2022 12:44:06 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
io.netty.resolver.dns.DnsNameResolverTimeoutException: [/8.8.4.4:53] query via UDP timed out after 5000 milliseconds (no stack trace available)
```

### Expected behavior

The application resolves DNS and starts normally.

### Actual behavior

The application it crash with
```
Feb 08, 2022 12:43:55 PM io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider
WARN: Default DNS servers: [/8.8.8.8:53, /8.8.4.4:53] (Google Public DNS as a fallback)
Feb 08, 2022 12:44:06 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
io.netty.resolver.dns.DnsNameResolverTimeoutException: [/8.8.4.4:53] query via UDP timed out after 5000 milliseconds (no stack trace available)
```

Connecting to the instance with debugger show that javax.naming.NamingException: JNDI has been disabled, enable it with quarkus.naming.enable-jndi=true is thrown (and ignored) here:
```
at io.netty.resolver.dns.DirContextUtils.addNameServers(DirContextUtils.java:49)
at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.<clinit>(DefaultDnsServerAddressStreamProvider.java:53)
at io.vertx.core.impl.resolver.DnsResolverProvider.<init>(DnsResolverProvider.java:77)
at io.vertx.core.spi.resolver.ResolverProvider.factory(ResolverProvider.java:39)
at io.vertx.core.impl.AddressResolver.<init>(AddressResolver.java:76)
at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:180)
at io.vertx.core.impl.VertxBuilder.vertx(VertxBuilder.java:225)
at io.vertx.core.Vertx.vertx(Vertx.java:86)
at io.vertx.core.Vertx.vertx(Vertx.java:76)
at io.vertx.mutiny.core.Vertx.vertx(Vertx.java:116)
at io.quarkus.vault.runtime.client.VertxVaultClient.<init>(VertxVaultClient.java:61)
at io.quarkus.vault.runtime.client.VertxVaultClient_Bean.create(Unknown Source)
at io.quarkus.vault.runtime.client.VertxVaultClient_Bean.create(Unknown Source)
at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:101)
at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
at io.quarkus.vault.runtime.client.VertxVaultClient_Bean.get(Unknown Source)
at io.quarkus.vault.runtime.client.VertxVaultClient_Bean.get(Unknown Source)
at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:428)
at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:441)
at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:412)
at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:229)
at io.quarkus.vault.runtime.VaultRecorder.configure(VaultRecorder.java:36)
at io.quarkus.deployment.steps.VaultProcessor$init1872323611.deploy_0(Unknown Source)
at io.quarkus.deployment.steps.VaultProcessor$init1872323611.deploy(Unknown Source)
at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
at io.quarkus.runtime.Application.start(Application.java:101)
at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
at io.quarkus.runner.GeneratedMain.main(Unknown Source)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
```

Following the path above I cannot see that it touches any path other than using DirContextUtils.addNameServers.
io.vertx.core.impl.resolver.DnsResolverProvider. has a path where Vert.x' AddressResolverOptions is used, but VertxVaultClientinitializes with Vertx.vertx(), so the relevant options is not possible to set.

### How to Reproduce?

Run application with the vault extension configured, and have 8.8.8.8:53 and 8.8.4.4:53 blocked.

### Output of `java -version`

17.0.2

### Quarkus version or git rev

2.7.0

### Additional information

Originally [discussed on Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/jndi.20disabled.20by.20default-.3E.20application.20does.20not.20start). 
A separate[ issue is created on quarkus-vault](https://github.com/quarkiverse/quarkus-vault/issues/21)

**Comment by gsmet** [comment]
I'm not sure this is enough.

We changed the default behavior and we are contacting external DNS servers by default. Really not sure it's something we should do.

**Comment by stuartwdouglas** [comment]
So this is really yuck, basically it seems like a JNDI hack is the only way to get the name servers to use: https://mail.openjdk.java.net/pipermail/net-dev/2017-March/010695.html

Annoyingly we can't really just enable some operations, just because of the way JNDI is implemented. All I can think of at this point is some kind of build item that would let you init classes before we disable JNDI. 

Another option would be to move the disabling to the end of static init, and then you can just init the `DefaultDnsServerAddressStreamProvider` resolver in a static init block.

**Comment by gsmet** [comment]
Mmmh, can you really resolve the DNS config at build time (in the case of a native executable)?

For me it's typically the type of things you will need to resolve at runtime.

**Comment by stuartwdouglas** [comment]
It appears that in native we just force the use of the blocking provider, so this is not an issue: https://github.com/quarkusio/quarkus/blob/262f5955cd35c1f36572124968723e613bacadcd/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/graal/VertxSubstitutions.java#L54

**Comment by cescoffier** [comment]
Now that you are mentioning it, don't we use the blocking DNS resolver in JVM mode too?

**Comment by cescoffier** [comment]
@computerlove Can you try to run with `-Dvertx.disableDnsResolver=true`?

**Comment by computerlove** [comment]
`-Dvertx.disableDnsResolver=true` does seem to work. My breakpoint in `DefaultDnsServerAddressStreamProvider` is never hit, and startup now fails because Vault has CIDR restrictions on the particular secrets. (running locally)

**Comment by cescoffier** [comment]
The Vert.x recorder should do that for you except if you explicitly enabled the async DNS (which I would not recommend):

```
if (!conf.useAsyncDNS) {
            System.setProperty(ResolverProvider.DISABLE_DNS_RESOLVER_PROP_NAME, "true");
}
```

**Comment by cescoffier** [comment]
However, to go back to the vaul initialization issue, maybe it happens BEFORE, and it should pass that property explicitely.

**Comment by vsevel** [comment]
> However, to go back to the vault initialization issue, maybe it happens BEFORE, and it should pass that property explicitely.

since vault is a config source, it may be executing very early on?
vault has its own recorder. may be I should force this system property as well? should I make that optional like you are doing in the Vert.x recorder?
this is a bit intrusive. could there be side effects? I am thinking that people using vault, are not necessarily thinking that this will disable the dns resolver automatically.

**Comment by cescoffier** [comment]
Ah, yes config source are called before. So we would need to set this property and restore the initial value (or unset it if none)

**Comment by cescoffier** [comment]
So, the problem is only in the Vaul extension, not in Quarkus "core".

**Comment by cescoffier** [comment]
Fixed by https://github.com/quarkiverse/quarkus-vault/pull/23.

**Comment by snazy** [comment]
@cescoffier @gsmet somewhere above you mentioned that contacting external (Google) DNS servers by default is probably not a good move. I just ran into exactly this issue - the Vertx (Netty) DNS-Client uses Google DNS as the default, which makes looking up local/internal DNS entries impossible (without `quarkus.naming.enable-jndi=true`). This is problematic, for example when you wanna lookup k8s service IPs. OTOH I don't wanna have JNDI.
