### ISSUE TITLE
CamelInfinispanITCase fails

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#2351]
After applying the fixes for #2346 and #2347, the CamelInfinispanITCase is failing. I am disabling it with a reference to this issue.

```
[INFO] Running io.quarkus.it.camel.core.CamelInfinispanITCase
May 06, 2019 9:21:49 PM org.infinispan.factories.GlobalComponentRegistry preStart
INFO: ISPN000128: Infinispan version: Infinispan 'N/A' 10.0.0.Beta2
May 06, 2019 9:21:49 PM org.infinispan.server.hotrod.test.HotRodTestingUtil startHotRodServer
INFO: Start server in port 11232
May 06, 2019 9:21:49 PM org.infinispan.manager.DefaultCacheManager getCache
WARN: ISPN000434: Direct usage of the ___defaultcache name to retrieve the default cache is deprecated
May 06, 2019 9:21:49 PM org.infinispan.manager.DefaultCacheManager wireAndStartCache
WARN: ISPN000454: Calling getCache with a cache override is no longer supported. Please invoke createCache first and then getCache. Cache name was default
Executing [/home/ppalaga/orgs/quarkus/quarkus/integration-tests/camel-core/target/quarkus-integration-test-camel-core-999-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
2019-05-06 21:21:49,822 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] (main) Apache Camel 3.0.0-M2 (CamelContext: quarkus-camel-example) is starting
2019-05-06 21:21:49,823 INFO  [org.apa.cam.imp.DefaultManagementStrategy] (main) JMX is disabled
2019-05-06 21:21:49,823 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] (main) StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2019-05-06 21:21:49,827 INFO  [org.apa.cam.com.net.htt.HttpServerBootstrapFactory] (main) BootstrapFactory on port 8999 is using bootstrap configuration: [NettyServerBootstrapConfiguration{protocol='http', host='0.0.0.0', port=8999, broadcast=false, sendBufferSize=65536, receiveBufferSize=65536, receiveBufferSizePredictor=0, workerCount=0, bossCount=1, keepAlive=true, tcpNoDelay=true, reuseAddress=true, connectTimeout=10000, backlog=0, serverInitializerFactory=org.apache.camel.component.netty4.http.HttpServerInitializerFactory@43653f0, nettyServerBootstrapFactory=null, options=null, ssl=false, sslHandler=null, sslContextParameters='null', needClientAuth=false, enabledProtocols='TLSv1,TLSv1.1,TLSv1.2, keyStoreFile=null, trustStoreFile=null, keyStoreResource='null', trustStoreResource='null', keyStoreFormat='JKS', securityProvider='SunX509', passphrase='null', bossGroup=null, workerGroup=null, networkInterface='null', reconnect='true', reconnectInterval='10000'}]
2019-05-06 21:21:49,928 INFO  [org.inf.cli.hot.RemoteCacheManager] (main) ISPN004021: Infinispan version: null
2019-05-06 21:21:49,939 INFO  [org.inf.cli.hot.RemoteCacheManager] (main) ISPN004021: Infinispan version: null
2019-05-06 21:21:49,946 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] (main) Route: timer started and consuming from: timer://keep-alive
2019-05-06 21:21:49,946 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] (main) Route: file started and consuming from: file://./target/orders
2019-05-06 21:21:49,948 INFO  [org.apa.cam.com.net.SingleTCPNettyServerBootstrapFactory] (main) ServerBootstrap binding to 0.0.0.0:8999
2019-05-06 21:21:49,949 INFO  [org.apa.cam.com.net.htt.NettyHttpConsumer] (main) Netty consumer bound to: 0.0.0.0:8999
2019-05-06 21:21:49,949 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] (main) Route: route1 started and consuming from: http://0.0.0.0:8999/foo
2019-05-06 21:21:49,949 INFO  [org.apa.cam.com.net.htt.NettyHttpConsumer] (main) Netty consumer bound to: 0.0.0.0:8999
2019-05-06 21:21:49,949 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] (main) Route: route2 started and consuming from: http://0.0.0.0:8999/put
2019-05-06 21:21:49,949 INFO  [org.apa.cam.com.net.htt.NettyHttpConsumer] (main) Netty consumer bound to: 0.0.0.0:8999
2019-05-06 21:21:49,949 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] (main) Route: route3 started and consuming from: http://0.0.0.0:8999/get
2019-05-06 21:21:49,949 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] (main) Total 5 routes, of which 5 are started
2019-05-06 21:21:49,949 INFO  [io.qua.cam.cor.run.sup.FastCamelContext] (main) Apache Camel 3.0.0-M2 (CamelContext: quarkus-camel-example) started in 0.127 seconds
2019-05-06 21:21:49,951 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.133s. Listening on: http://[::]:8081
2019-05-06 21:21:49,952 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-infinispan, camel-netty4-http, cdi, infinispan-client, resteasy]
2019-05-06 21:21:50,950 INFO  [keep-alive] (Camel (quarkus-camel-example) thread #2 - timer://keep-alive) Exchange[ExchangePattern: InOnly, BodyType: String, Body: I'm alive !]
2019-05-06 21:21:51,126 INFO  [cache] (Camel (quarkus-camel-example) thread #4 - NettyEventExecutorGroup) Exchange[Id: 7BF632C39B949C9-0000000000000001, ExchangePattern: InOut, Properties: {CamelCharsetName=ISO-8859-1, CamelCreatedTimestamp=Mon May 06 21:21:51 CEST 2019, CamelExternalRedelivered=false, CamelMessageHistory=[DefaultMessageHistory[routeId=route2, node=convertBodyTo1], DefaultMessageHistory[routeId=route2, node=to3]], CamelToEndpoint=log://cache?showAll=true}, Headers: {Accept=*/*, Accept-Encoding=gzip,deflate, CamelHttpCharacterEncoding=ISO-8859-1, CamelHttpMethod=POST, CamelHttpPath=, CamelHttpQuery=null, CamelHttpRawQuery=null, CamelHttpUri=/put, CamelHttpUrl=http://0.0.0.0:8999/put, CamelNettyChannelHandlerContext=ChannelHandlerContext(handler, [id: 0xacaf716b, L:/127.0.0.1:8999 - R:/127.0.0.1:45244]), CamelNettyLocalAddress=/127.0.0.1:8999, CamelNettyRemoteAddress=/127.0.0.1:45244, Connection=Keep-Alive, Content-Length=16, Content-Type=text/plain; charset=ISO-8859-1, Host=localhost:8999, User-Agent=Apache-HttpClient/4.5.7 (Java/1.8.0_201)}, BodyType: byte[], Body: Hello Infinispan, Out: null: ]
2019-05-06 21:21:51,126 INFO  [org.inf.cli.hot.imp.RemoteCacheImpl] (Camel (quarkus-camel-example) thread #4 - NettyEventExecutorGroup) ISPN004002: Cannot perform operations on a cache associated with an unstarted RemoteCacheManager. Use RemoteCacheManager.start before using the remote cache.
2019-05-06 21:21:51,126 ERROR [org.apa.cam.pro.DefaultErrorHandler] (Camel (quarkus-camel-example) thread #4 - NettyEventExecutorGroup) Failed delivery for (MessageId: 7BF632C39B949C9-0000000000000002 on ExchangeId: 7BF632C39B949C9-0000000000000001). Exhausted after delivery attempt: 1 caught: java.lang.reflect.InvocationTargetException

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route2            ] [route2            ] [http://0.0.0.0:8999/put                                                       ] [         1]
[route2            ] [convertBodyTo1    ] [convertBodyTo[byte[]]                                                         ] [         1]
[route2            ] [to3               ] [log:cache?showAll=true                                                        ] [         0]
[route2            ] [setHeader2        ] [setHeader[CamelInfinispanOperation]                                           ] [         0]
[route2            ] [setHeader3        ] [setHeader[CamelInfinispanKey]                                                 ] [         0]
[route2            ] [setHeader4        ] [setHeader[CamelInfinispanValue]                                               ] [         0]
[route2            ] [to4               ] [infinispan:default?hosts=localhost:11232                                      ] [         0]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.camel.support.ObjectHelper.invokeMethodSafe(ObjectHelper.java:201)
        at org.apache.camel.support.HeaderSelectorProducer.lambda$bind$22(HeaderSelectorProducer.java:183)
        at org.apache.camel.support.BaseSelectorProducer.process(BaseSelectorProducer.java:36)
        at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:130)
        at org.apache.camel.processor.RedeliveryErrorHandler$RedeliveryState.run(RedeliveryErrorHandler.java:482)
        at org.apache.camel.support.ReactiveHelper$Worker.schedule(ReactiveHelper.java:130)
        at org.apache.camel.support.ReactiveHelper.scheduleMain(ReactiveHelper.java:43)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:88)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:221)
        at org.apache.camel.component.netty4.handlers.ServerChannelHandler.processAsynchronously(ServerChannelHandler.java:141)
        at org.apache.camel.component.netty4.handlers.ServerChannelHandler.channelRead0(ServerChannelHandler.java:112)
        at org.apache.camel.component.netty4.http.handlers.HttpServerChannelHandler.channelRead0(HttpServerChannelHandler.java:194)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at org.apache.camel.component.netty4.http.handlers.HttpServerMultiplexChannelHandler.channelRead0(HttpServerMultiplexChannelHandler.java:143)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:350)
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: org.infinispan.client.hotrod.exceptions.RemoteCacheManagerNotStartedException:: Cannot perform operations on a cache associated with an unstarted RemoteCacheManager. Use RemoteCacheManager.start before using the remote cache.
        at org.infinispan.client.hotrod.impl.RemoteCacheImpl.assertRemoteCacheManagerIsStarted(RemoteCacheImpl.java:558)
        at org.infinispan.client.hotrod.impl.RemoteCacheImpl.putAsync(RemoteCacheImpl.java:360)
        at org.infinispan.client.hotrod.impl.RemoteCacheImpl.put(RemoteCacheImpl.java:334)
        at org.infinispan.client.hotrod.impl.RemoteCacheSupport.put(RemoteCacheSupport.java:79)
        at org.apache.camel.component.infinispan.InfinispanProducer.onPut(InfinispanProducer.java:80)
        ... 25 more

2019-05-06 21:21:51,223 INFO  [org.inf.cli.hot.imp.RemoteCacheImpl] (Camel (quarkus-camel-example) thread #6 - NettyEventExecutorGroup) ISPN004002: Cannot perform operations on a cache associated with an unstarted RemoteCacheManager. Use RemoteCacheManager.start before using the remote cache.
2019-05-06 21:21:51,223 ERROR [org.apa.cam.pro.DefaultErrorHandler] (Camel (quarkus-camel-example) thread #6 - NettyEventExecutorGroup) Failed delivery for (MessageId: 7BF632C39B949C9-0000000000000004 on ExchangeId: 7BF632C39B949C9-0000000000000003). Exhausted after delivery attempt: 1 caught: java.lang.reflect.InvocationTargetException

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route3            ] [route3            ] [http://0.0.0.0:8999/get                                                       ] [         0]
[route3            ] [setHeader5        ] [setHeader[CamelInfinispanOperation]                                           ] [         0]
[route3            ] [setHeader6        ] [setHeader[CamelInfinispanKey]                                                 ] [         0]
[route3            ] [to5               ] [infinispan:default?hosts=localhost:11232                                      ] [         0]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.camel.support.ObjectHelper.invokeMethodSafe(ObjectHelper.java:201)
        at org.apache.camel.support.HeaderSelectorProducer.lambda$bind$22(HeaderSelectorProducer.java:183)
        at org.apache.camel.support.BaseSelectorProducer.process(BaseSelectorProducer.java:36)
        at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:130)
        at org.apache.camel.processor.RedeliveryErrorHandler$RedeliveryState.run(RedeliveryErrorHandler.java:482)
        at org.apache.camel.support.ReactiveHelper$Worker.schedule(ReactiveHelper.java:130)
        at org.apache.camel.support.ReactiveHelper.scheduleMain(ReactiveHelper.java:43)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:88)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:221)
        at org.apache.camel.component.netty4.handlers.ServerChannelHandler.processAsynchronously(ServerChannelHandler.java:141)
        at org.apache.camel.component.netty4.handlers.ServerChannelHandler.channelRead0(ServerChannelHandler.java:112)
        at org.apache.camel.component.netty4.http.handlers.HttpServerChannelHandler.channelRead0(HttpServerChannelHandler.java:194)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at org.apache.camel.component.netty4.http.handlers.HttpServerMultiplexChannelHandler.channelRead0(HttpServerMultiplexChannelHandler.java:143)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:350)
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: org.infinispan.client.hotrod.exceptions.RemoteCacheManagerNotStartedException:: Cannot perform operations on a cache associated with an unstarted RemoteCacheManager. Use RemoteCacheManager.start before using the remote cache.
        at org.infinispan.client.hotrod.impl.RemoteCacheImpl.assertRemoteCacheManagerIsStarted(RemoteCacheImpl.java:558)
        at org.infinispan.client.hotrod.impl.RemoteCacheImpl.getAsync(RemoteCacheImpl.java:529)
        at org.infinispan.client.hotrod.impl.RemoteCacheImpl.get(RemoteCacheImpl.java:417)
        at org.apache.camel.component.infinispan.InfinispanProducer.onGet(InfinispanProducer.java:215)
        ... 25 more

```

**Comment by ppalaga** [comment]
Camel extensions moved to https://github.com/apache/camel-quarkus
