### ISSUE TITLE
Build fails on REST endpoint when `@BeanParam` has parameterized type

### ISSUE THREAD

**Issue by MikeEdgar** [quarkusio/quarkus#23592]
### Describe the bug

With Quarkus 2.7.4.Final (and earlier versions), defining a REST endpoint with RestEasy Reactive where a `@BeanParam` argument has a parameterized type, the build fails with `IndexOutOfBoundsException`.

```java
@GET
@Path("topics")
@Produces(MediaType.APPLICATION_JSON)
@Operation(operationId = Operations.GET_TOPICS_LIST)
@APIResponseSchema(Types.TopicList.class)
CompletionStage<Response> listTopics(@QueryParam("filter") String filter,
                                     @BeanParam OrderByInput<TopicOrderKey> orderParams)
```

```java
class OrderByInput<T> {
    @QueryParam("orderKey")
    T field;

    @QueryParam("order")
    String order;
}
```

```java
    @Schema(name = "TopicOrderKey",
            enumeration = { "name", "partitions", "retention.ms", "retention.bytes" })
    public enum TopicOrderKey {
        NAME("name"),
        PARTITIONS("partitions"),
        RETENTION_MS("retention.ms"),
        RETENTION_BYTES("retention.bytes");

        String value;

        private TopicOrderKey(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        public static TopicOrderKey fromString(String value) {
            return Arrays.stream(values())
                    .filter(v -> v.getValue().equals(value))
                    .findFirst()
                    .orElse(null);
        }
    }
```

### Expected behavior

Type parameter declared on method argument is applied to the bean parameter object.

### Actual behavior

Stack trace with root cause:
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.Collections$EmptyList.get(Collections.java:4586)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.resolveTypeVariable(EndpointIndexer.java:910)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.toClassName(EndpointIndexer.java:886)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.extractParameterInfo(EndpointIndexer.java:1151)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.scanInjectableBean(ServerEndpointIndexer.java:246)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleBeanParam(ServerEndpointIndexer.java:167)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:523)
	... 15 more
```

### How to Reproduce?

Define a REST endpoint method with query parameters defined within a POJO having a generic type parameter where the parameter is supplied in a method parameter annotated with `@BeanParam`.

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

It looks as though a parameterized type passed to `ServerEndpointIndexer#handleBeanParam` as `paramType` is needed to resolve type variables within `EndpointIndexer#resolveTypeVariable`

**Comment by Plawn** [comment]
@MikeEdgar still true in the last version ?

**Comment by MikeEdgar** [comment]
@Plawn, yes same issue in 2.7.4. Demo project @ https://github.com/MikeEdgar/quarkus-23592/tree/main/getting-started
