### ISSUE TITLE
gRPC service throw errors when using @Blocking and OpenTelemetry gRPC instrumentation

### ISSUE THREAD

**Issue by XSAM** [quarkusio/quarkus#23603]
### Describe the bug

Calling a gRPC method with `@Blocking` annotation produces errors when enabling [io.opentelemetry.instrumentation:opentelemetry-grpc-1.6:1.10.0-alpha](https://mvnrepository.com/artifact/io.opentelemetry.instrumentation/opentelemetry-grpc-1.6/1.10.0-alpha) and io.quarkus:quarkus-opentelemetry-exporter-otlp.

It does not affect gRPC methods without `@Blocking` annotation.

### Expected behavior

no error.

### Actual behavior

The gRPC server will produce the below error:

```
2022-02-11 16:53:58,993 SEVERE [io.ope.ins.grp.v1_.int.ContextStorageBridge] (executor-thread-0) Detaching context which was not attached.: java.lang.Throwable
	at io.opentelemetry.instrumentation.grpc.v1_6.internal.ContextStorageBridge.detach(ContextStorageBridge.java:67)
	at io.grpc.override.ContextStorageOverride.detach(ContextStorageOverride.java:26)
	at io.grpc.Context.detach(Context.java:450)
	at io.quarkus.grpc.runtime.supports.blocking.BlockingExecutionHandler.handle(BlockingExecutionHandler.java:45)
	at io.quarkus.grpc.runtime.supports.blocking.BlockingExecutionHandler.handle(BlockingExecutionHandler.java:12)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

### How to Reproduce?

1. Use example `grpc-plain-text-quickstart` from `https://github.com/quarkusio/quarkus-quickstarts.git`
2. Add dependencies

```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry-exporter-otlp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-grpc-1.6</artifactId>
            <version>1.10.0-alpha</version>
        </dependency>
```

3. Add `@Blocking` annotation to `io.quarkus.grpc.examples.hello.HelloWorldService.sayHello`
4. Run test `io.quarkus.grpc.examples.hello.HelloWorldServiceTest`

### Output of `uname -a` or `ver`

21.2.0

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Quarkus version or git rev

2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

**Comment by radcortez** [comment]
Specific OTel libraries are not officially supported at this point. The plan is to slowly support them in the future.
