### ISSUE TITLE
"BlockingNotAllowedException: Attempting a blocking read on io thread" when @RestQuery is missing

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#23622]
### Describe the bug

I was trying to use query parameters with RestEasy reactive, but was missing the `@RestQuery` annotation at first.

This led to the following exception, which is in my opinion very misleading and took me a lot of time to get to the actual reason.

```
org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException: Attempting a blocking read on io thread
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream$VertxBlockingInput.readBlocking(VertxInputStream.java:242)
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.readIntoBuffer(VertxInputStream.java:120)
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:82)
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:70)
	at org.jboss.resteasy.reactive.common.providers.serialisers.PrimitiveBodyHandler.readFrom(PrimitiveBodyHandler.java:21)
	at org.jboss.resteasy.reactive.server.providers.serialisers.ServerStringMessageBodyHandler.readFrom(ServerStringMessageBodyHandler.java:37)
	at org.jboss.resteasy.reactive.server.providers.serialisers.ServerStringMessageBodyHandler.readFrom(ServerStringMessageBodyHandler.java:14)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:108)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:68)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:25)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:49)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:126)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:274)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

A nice annotation that says something like "@RestQuery annotation missing" or as no annotation means, it assumes the argument is a path param according to here https://quarkus.io/guides/resteasy-reactive#accessing-request-parameters 

> the [@RestPath](https://javadoc.io/doc/io.quarkus.resteasy.reactive/resteasy-reactive-common/2.0.0.Final/org/jboss/resteasy/reactive/RestPath.html) annotation is optional: any parameter whose name matches an existing URI template variable will be automatically assumed to have [@RestPath](https://javadoc.io/doc/io.quarkus.resteasy.reactive/resteasy-reactive-common/2.0.0.Final/org/jboss/resteasy/reactive/RestPath.html).

Or something like `Path parameter requires placeholder in @Path as well`

**Comment by geoand** [comment]
Thanks for reporting!

Mind adding the snippet of code where you are declaring the JAX-RS method?

**Comment by geoand** [comment]
I am assuming that what's going on is that the name of the parameter is different from the name in the `@Path`

**Comment by mklueh** [comment]
@geoand sorry, I forgot to answer.

I was missing the name in the path, and had no annotation on the method parameter, because I wanted to have a query param, not a route param.

So JAX assumed it's meant to be a path parameter.

However, my point was just that the error given is misleading and does not help to find out that either a name was missing in the path, or that the query parameter was missing the correct annotation.

**Comment by geoand** [comment]
Yeah I understand, but the issue is that we can't know whether you are after a path parameter or the entire message body
