### ISSUE TITLE
Build failure when the kubernetes-client extension is configured with certificates

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#23681]
### Describe the bug

Configuring the kubernetes-client with

```
quarkus.kubernetes-client.ca-cert-file=/path/to/ca.cert
```
Causes the build to fail, if `/path/to/car.cert` is not available at compile time.

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.7.0.Final:build (default) on project my-project: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep#process threw an exception: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[ERROR] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:103)
[ERROR] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:97)
[ERROR] 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.applyCommonConfiguration(HttpClientUtils.java:214)
[ERROR] 	at io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory.createHttpClient(OkHttpClientFactory.java:89)
[ERROR] 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:164)
[ERROR] 	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:48)
[ERROR] 	at io.fabric8.kubernetes.client.BaseKubernetesClient.<init>(BaseKubernetesClient.java:159)
[ERROR] 	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:42)
[ERROR] 	at io.quarkus.kubernetes.client.runtime.KubernetesClientUtils.createClient(KubernetesClientUtils.java:50)
[ERROR] 	at io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep.process(KubernetesClientBuildStep.java:16)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.nio.file.NoSuchFileException: /path/to/ca.crt
[ERROR] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[ERROR] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[ERROR] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
[ERROR] 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
[ERROR] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
[ERROR] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
[ERROR] 	at java.base/java.nio.file.Files.readAllBytes(Files.java:3206)
[ERROR] 	at io.fabric8.kubernetes.client.internal.CertUtils.getInputStreamFromDataOrFile(CertUtils.java:67)
[ERROR] 	at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:73)
[ERROR] 	at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:140)
[ERROR] 	at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:90)
[ERROR] 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.applyCommonConfiguration(HttpClientUtils.java:203)
[ERROR] 	... 18 more
```

### Expected behavior

The extension should not fail at compile time.

**Comment by geoand** [comment]
I am not really sure what we can do about this honestly...
The problem is that we actually instantiate the client at build time based on the provided configuration.

**Comment by iocanel** [comment]
There are two thigs we can do:

1. Delegate this issue to the client and request lazy loading of certificates.
2. Split runtime and build time configuration, and only pass runtime config on runtime using `withRequestConfig`.

**Comment by geoand** [comment]
I don't really know what you mean by `2.` because currently all the client configuration is build time configuration.

**Comment by iocanel** [comment]
It doesn't really matter. 

It's seems that `WithRequestConfig` has long been removed.

**Comment by johurul000** [comment]
@iocanel  should I give it a try, I am new

**Comment by iocanel** [comment]
It won't work we need this to be fixed in the client first

**Comment by johurul000** [comment]
ok

**Comment by iocanel** [comment]
@johurul000: If you are still interested in contributing you could possibly pick up: https://github.com/fabric8io/kubernetes-client/issues/4085.

**Comment by shawkins** [comment]
Closed the upstream issue.  To support @iocanel 's usage there needs to be some differentiation in quarkus of what fabric8 client properties are intended for runtime only.

**Comment by geoand** [comment]
The idea being that we don't want that property to be set when doing `quarkus.kubernetes.deploy=true` but we do want it when the application is running?

If so, then there is nothing OOTB to make this happen. We would have to resort to manually handling the configuration
