### ISSUE TITLE
Vertx HttpClient + FIPS - QuarkusTest: java.lang.NoSuchFieldError: REACTIVE_ROUTES

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#23684]
### Describe the bug

I've added a [Quarkus test ](https://github.com/quarkus-qe/quarkus-test-suite/pull/534) into my project and suddenly I am getting the following error:

```
Caused by: java.lang.RuntimeException: 
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.vertx.web.deployment.ReactiveRoutesProcessor#feature threw an exception: java.lang.NoSuchFieldError: REACTIVE_ROUTES
	at io.quarkus.vertx.web.deployment.ReactiveRoutesProcessor.feature(ReactiveRoutesProcessor.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

Environment:
- Jenkins worker
- RHEL8.5 + FIPS (I could also reproduce the error in the same environment without FIPS)

Reproducer: 
Once the PR gets merged, you can clone this repo: git@github.com:quarkus-qe/quarkus-test-suite.git and run

`mvn clean verify -Dall-modules -pl http/vertx-web-client -Dit.test=PureVertxHttpClientTest`

Note: Be sure that the test is not disabled

**Comment by rsvoboda** [comment]
@pjgg which Quarkus version(s)?

**Comment by pjgg** [comment]
> @pjgg which Quarkus version(s)?

I could reproduce with Quarkus 2.2.5.Final

**Comment by geoand** [comment]
cc @mkouba

**Comment by pjgg** [comment]
This issue could be closed because is fixed on Quarkus 2.3+

**Comment by paulrobinson** [comment]
@pjgg you don't happen to know which PR this was fixed in?

**Comment by pjgg** [comment]
I am not 100% sure, but I think that could be related to this PR:

https://github.com/quarkusio/quarkus/pull/20138/files

@mkouba WDYT?

**Comment by gsmet** [comment]
What @mkouba was saying is that it was probably due to a mismatch of Quarkus versions in the test itself i.e. a test mixing somehow 2.2 and something newer than 2.3 included.
Nothing was fixed in Quarkus regarding this particular issue so you won't find a PR.

**Comment by mkouba** [comment]
> What @mkouba was saying is that it was probably due to a mismatch of Quarkus versions in the test itself i.e. a test mixing somehow 2.2 and something newer than 2.3 included. Nothing was fixed in Quarkus regarding this particular issue so you won't find a PR.

Exactly.

**Comment by paulrobinson** [comment]
Thanks all for explaining.
