### ISSUE TITLE
@GET method with request body throws BlockingNotAllowedException when using RestEasy Reactive

### ISSUE THREAD

**Issue by heliommsfilho** [quarkusio/quarkus#23715]
### Describe the bug

Define a `@GET` endpoint which receives a body when using RestEasy Reactive returns HTTP 500 due `BlockingNotAllowedException`. Works with RestEasy non-reactive.

It seems that even using `quarkus-resteasy-reactive-jackson` the body parsing is always a blocking operation.

### Expected behavior

Finish the operation without errors.

### Actual behavior

Define a `@GET` endpoint which receives a body when using RestEasy Reactive throws `BlockingNotAllowedException`:

```
{
"details": "Error id 84497e11-973c-4646-8eb0-6892966771dd-2, org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException: Attempting a blocking read on io thread",
    "stack": "org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException: Attempting a blocking read on io thread\n\tat org.jboss.resteasy.reactive.server.vertx...."
}
```

### How to Reproduce?

1. Add the `quarkus-resteasy-reactive-jackson` dependency in pom.xml:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/10871439/154047988-324c7ee1-743f-4bee-be96-1220dac83abe.png">

2. Define a `@GET` endpoint which receives some information in request body (I used `text/plain` but the same happens with `application/json`):

<img width="291" alt="image" src="https://user-images.githubusercontent.com/10871439/154047893-1084360b-7abb-475f-b1c2-321af29b6248.png">

3. Start the application and perform a request:

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/10871439/154048157-bef9a72e-cd7e-4cf1-b88d-0b8104f77876.png">

Note: Just changing `quarkus-resteasy-reactive-jackson` to `quarkus-resteasy-jackson` without any further change solves the problem:

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/10871439/154048328-efb6d5e2-cd49-4995-8bbf-3bdc51e66065.png">

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.3.0: root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64

### Output of `java -version`

java 17.0.2 2022-01-18 LTS Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86) Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

### GraalVM version (if different from Java)

openjdk 11.0.14 2022-01-18 OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05) OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05, mixed mode, sharing)

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) OS name: "mac os x", version: "12.2.1", arch: "aarch64", family: "mac"

### Additional information

```posh
2022-02-15 11:05:52,225 ERROR [org.jbo.res.rea.ser.cor.RuntimeExceptionMapper] (vert.x-eventloop-thread-11) A blocking operation occurred on the IO thread. This likely means you need to annotate com.example.ExampleResource#hello(class java.lang.String) with @io.smallrye.common.annotation.Blocking. Alternatively you can annotate the class com.example.ExampleResource to make every method on the class blocking, or annotate your sub class of the javax.ws.rs.core.Application class to make the whole application blocking
2022-02-15 11:05:52,232 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-11) HTTP Request to /hello failed, error id: 532a8a1e-ea8b-45c8-a353-407e497d682c-1: org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException: Attempting a blocking read on io thread
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream$VertxBlockingInput.readBlocking(VertxInputStream.java:242)
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.readIntoBuffer(VertxInputStream.java:120)
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:82)
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:70)
	at org.jboss.resteasy.reactive.common.providers.serialisers.PrimitiveBodyHandler.readFrom(PrimitiveBodyHandler.java:21)
	at org.jboss.resteasy.reactive.server.providers.serialisers.ServerStringMessageBodyHandler.readFrom(ServerStringMessageBodyHandler.java:37)
	at org.jboss.resteasy.reactive.server.providers.serialisers.ServerStringMessageBodyHandler.readFrom(ServerStringMessageBodyHandler.java:14)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:108)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:68)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:25)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:49)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:126)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:274)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-02-15 11:05:52,238 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-11) Request failed: org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException: Attempting a blocking read on io thread
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream$VertxBlockingInput.readBlocking(VertxInputStream.java:242)
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.readIntoBuffer(VertxInputStream.java:120)
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:82)
	at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:70)
	at org.jboss.resteasy.reactive.common.providers.serialisers.PrimitiveBodyHandler.readFrom(PrimitiveBodyHandler.java:21)
	at org.jboss.resteasy.reactive.server.providers.serialisers.ServerStringMessageBodyHandler.readFrom(ServerStringMessageBodyHandler.java:37)
	at org.jboss.resteasy.reactive.server.providers.serialisers.ServerStringMessageBodyHandler.readFrom(ServerStringMessageBodyHandler.java:14)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:108)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:68)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:25)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:49)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:126)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:274)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by geoand** [comment]
This is actually a weird case... 

It works perfectly for other types of HTTP requests because we actually attempt to read the body, but in the case of GET, we [don't](https://github.com/quarkusio/quarkus/blob/2.7.1.Final/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/InputHandler.java#L48).

The fix would be extremely easy, but do you think it makes sense @FroMage @stuartwdouglas ?

**Comment by heliommsfilho** [comment]
Ah ok, actually Quarkus isn't trying to read the body. Thank you for clarifying @geoand. 

In a real scenario, I need this in a `/list` endpoint with filtering capabilities. I used the body of the `@GET` to receive a JSON with filtering options. And then I found this problem.

**Comment by geoand** [comment]
Having a body in a GET method is very unusual, which is why you are seeing the current behavior

**Comment by geoand** [comment]
Closing as `Won't fix`
