### ISSUE TITLE
(Reactive Oracle Client) HR000061: Session is currently connecting to database

### ISSUE THREAD

**Issue by LazaroR94** [quarkusio/quarkus#23736]
### Describe the bug

I have currently spinned up a Quarkus project using the latest version 2.7.1. This is what I have included in my project (dependencies): Mutiny, smallrye-reactive-messaging-kafka, reactive-oracle-client & hibernate-reactive-panache.

I have been testing out the new reactive Oracle client and I seem to be having some issues when incorporated with reactive messaging. The flow is as follows: Message is received -> message is processed -> message is then sent to DB -> message ack() is called. The problem here is that whenever I try to insert a record into the database I am met with this error: 
`HR000061: Session is currently connecting to database`

I have looked at this previously reported similar issue but it doesn't justify my criteria: [14709](https://github.com/quarkusio/quarkus/issues/14709)

This is how I have my repository set up:
```
@ApplicationScoped
class SomeRepository : PanacheRepository<SomeEntity>

class SomeRepositoryAdapter(
    private val someRepository: SomeRepository
) : TransactionRepository<SomeEntity> {

    override fun save(entity: SomeEntity): Uni<Void> =
        Panache.withTransaction {
            someRepository.persist(entity)
        }.chain { -> someRepository.flush() }

    override fun saveAll(entities: List<SomeEntity>): Uni<Void> =
        Panache.withTransaction {
            someRepository.persist(entities)
        }.call { -> someRepository.flush() }
}
```

And this is how I have my KafkaEventHandler set up:
```
class KafkaEventHandler(
    private val processor: ProcessMessages,
) : TransactionEventHandler<Message<Notification>, Uni<Void>> {
    @Incoming(KAFKA_DATA)
    @Acknowledgment(Acknowledgment.Strategy.MANUAL)
    override fun consume(record: Message<Notification>): Uni<Void> {
        val metadata = record.getMetadata(IncomingKafkaRecordMetadata::class.java).orElse(null)
        if (metadata != null) {
            log.debug(
                "Received Kafka Record - " +
                    "topic: {}, " +
                    "partition: {}, " +
                    "offset: {}, " +
                    "payload: {}",
                metadata.topic, metadata.partition, metadata.offset, record.payload
            )
        }
        return Uni.createFrom().voidItem()
            .call { -> processor.processMessage(record.payload) }
            .call { -> handleSuccess(record) }
            .onFailure().recoverWithUni { failure -> handleFailure(failure, record) }
    }
}
```

### Expected behavior

For the transaction to be inserted into the database successfully.

### Actual behavior

```
ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-0) Mutiny had to drop the following exception: java.lang.IllegalStateException: HR000061: Session is currently connecting to database
--
  | at org.hibernate.reactive.pool.impl.ProxyConnection.withConnection(ProxyConnection.java:66)
  | at org.hibernate.reactive.pool.impl.ProxyConnection.rollbackTransaction(ProxyConnection.java:154)
  | at org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.rollback(MutinySessionImpl.java:459)
  | at org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.lambda$execute$4(MutinySessionImpl.java:442)
  | at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
  | at io.smallrye.mutiny.operators.uni.UniOnCancellationCall$UniOnCancellationCallProcessor.execute(UniOnCancellationCall.java:84)
  | at io.smallrye.mutiny.operators.uni.UniOnCancellationCall$UniOnCancellationCallProcessor.cancel(UniOnCancellationCall.java:67)
  | at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.cancel(UniOperatorProcessor.java:64)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.cancel(UniOnItemTransformToUni.java:89)
  | at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.cancel(UniOperatorProcessor.java:64)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.cancel(UniOnItemTransformToUni.java:89)
  | at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.cancel(UniOperatorProcessor.java:64)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.cancel(UniOnItemTransformToUni.java:87)
  | at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.cancel(UniOperatorProcessor.java:64)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.cancel(UniOnItemTransformToUni.java:89)
  | at io.smallrye.mutiny.operators.uni.builders.UniJoinAll$UniJoinAllSubscription.cancelSubscriptions(UniJoinAll.java:74)
  | at io.smallrye.mutiny.operators.uni.builders.UniJoinAll$UniJoinAllSubscription.onFailure(UniJoinAll.java:113)
  | at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
  | at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onFailure(UniCallbackSubscriber.java:65)
  | at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:54)
  | at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:54)
  | at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:54)
  | at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:54)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:58)
  | at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
  | at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
  | at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
  | at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forward(UniCreateFromCompletionStage.java:51)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:35)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
  | at org.hibernate.reactive.context.impl.VertxContext.execute(VertxContext.java:68)
  | at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.subscribe(UniRunSubscribeOn.java:25)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
  | at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:46)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
  | at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
  | at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
  | at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
  | at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forward(UniCreateFromCompletionStage.java:51)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:35)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
  | at org.hibernate.reactive.context.impl.VertxContext.execute(VertxContext.java:68)
  | at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.subscribe(UniRunSubscribeOn.java:25)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnSubscribeInvoke.subscribe(UniOnSubscribeInvoke.java:24)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:52)
  | at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:112)
  | at io.smallrye.mutiny.operators.uni.builders.UniJoinAll$UniJoinAllSubscription.triggerSubscriptions(UniJoinAll.java:60)
  | at io.smallrye.mutiny.operators.uni.builders.UniJoinAll.subscribe(UniJoinAll.java:36)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
  | at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
  | at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  | at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.request(UniToMultiPublisher.java:74)
  | at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onSubscribe(MultiFlatMapOp.java:601)
  | at io.smallrye.mutiny.converters.uni.UniToMultiPublisher.subscribe(UniToMultiPublisher.java:26)
  | at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:163)
  | at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:193)
  | at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
  | at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
  | at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99)
  | at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99)
  | at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
  | at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
  | at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
  | at io.smallrye.mutiny.operators.multi.multicast.MultiPublishOp$PublishSubscriber.drain(MultiPublishOp.java:487)
  | at io.smallrye.mutiny.operators.multi.multicast.MultiPublishOp$PublishSubscriber.onItem(MultiPublishOp.java:194)
  | at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:100)
  | at io.smallrye.mutiny.operators.multi.MultiOnItemInvoke$MultiOnItemInvokeProcessor.onItem(MultiOnItemInvoke.java:41)
  | at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
  | at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.tryEmit(MultiFlatMapOp.java:230)
  | at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onItem(MultiFlatMapOp.java:607)
  | at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
  | at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onItem(UniToMultiPublisher.java:93)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
  | at io.smallrye.mutiny.operators.uni.UniOnItemConsume$UniOnItemComsumeProcessor.onItem(UniOnItemConsume.java:43)
  | at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
  | at io.smallrye.mutiny.operators.uni.UniEmitOn$UniEmitOnProcessor.lambda$onItem$0(UniEmitOn.java:34)
  | at io.smallrye.reactive.messaging.kafka.commit.KafkaThrottledLatestProcessedCommit.lambda$received$6(KafkaThrottledLatestProcessedCommit.java:199)
  | at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
  | at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
  | at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Thread.java:829)


```

### How to Reproduce?

1. Create a Quarkus Application with version 2.7.1 and include these dependencies: Mutiny, smallrye-reactive-messaging-kafka, reactive-oracle-client & hibernate-reactive-panache.
2. Set up a basic reactive Kafka consumer/producer using Mutiny
3. Set up a basic Oracle database in a dockerized environment
4. Proceed to send a message to Kafka locally and wait for the consumer to process and send the message to the database

### Output of `uname -a` or `ver`

Darwin C02FW4DDMD6R 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "11.0.12" 2021-07-20 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

### Quarkus version or git rev

2.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.3.3 ------------------------------------------------------------  Build time:   2021-12-22 12:37:54 UTC Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          11.0.12 (Oracle Corporation 11.0.12+8-LTS-237) OS:           Mac OS X 11.4 x86_64

**Comment by LazaroR94** [comment]
Just tested this locally without the need for Kafka and it indeed still produces the same error when trying to insert directly to the database. (Tested using a simple /insert endpoint)

**Comment by RuggeroDAlo** [comment]
I have the same issue using kafka + postgresql, I've added a reproducer https://github.com/RuggeroDAlo/quarkus-23736

After sending 4 or 5 messages to the configured topic (with kafka-console-producer for example) the same error happens.
Calling the endpoint that does the same thing doesn't result in the same error, everything seems to keep working.

This only seems to happen on quarkus 2.7.1, not on 2.7.0.

**Comment by LazaroR94** [comment]
@RuggeroDAlo So the issue is not apparent in version 2.7.0?

**Comment by RuggeroDAlo** [comment]
@LazaroR94 I can consistently trigger the error on 2.7.1 with 4/5 messages, I can't do the same on 2.7.0, I have no idea about the root cause so I dont know :smile:

**Comment by LazaroR94** [comment]
I guess it's just me then because I just reproduced this with version 2.7.0 and still the same thing. I am highly certain this is due to the experimental reactive Oracle client still being in development perhaps.

**Comment by LazaroR94** [comment]
I have just removed Panache.withTransaction() from all my repository save methods and replaced them instead with the @ReactiveTransactional annotation and that seems to allow only one insert into a database table (I have multiple tables I insert to) but with the same error above coming before the insert. I assume the issue may lie then with Hibernate reactive w/ Panache?

**Comment by geoand** [comment]
cc @tsegismont

**Comment by LazaroR94** [comment]
I have had a breakthrough. It seems like you cannot return a combination of Unis from a method. The reason I had a combination of Unis was because I needed to ensure successful database insertion on three different tables and also to rollback any saves to the database in case any Uni save failed in the sequence. I guess my question is now: How can I have a Uni chain in which there's multiple database calls but rollback if one of them fails?

**Comment by LazaroR94** [comment]
It seems that I was not correctly enclosing multiple inserts within a single transaction, therefore, Hibernate complained that an active connection to the database was already established previously and was trying to establish itself again. I have fixed this with the following:

```
return Panache.withTransaction {
            val dbInsert1 = someRepo.save(entity)
            val dbInsert2 = someRepo2.save(entity)
            val dbInsert3 = someRepo3.save(remittanceMessageStatementDetailEntity)

            return@withTransaction Uni.combine().all().unis(dbInsert1, dbInsert2, dbInsert3).discardItems()
        }
```
