### ISSUE TITLE
@Message template fails to use #each or #for

### ISSUE THREAD

**Issue by nunocasteleira** [quarkusio/quarkus#23734]
### Describe the bug

I'm using Qute to enable i18n on a project.

When parsing a string using `Qute.fmt`, passing a template directly renders the message just fine.

But when I reference its template via the message bundle namespace, such as
```java
Qute.fmt("{error:errorMessage(dates)}").data("dates", dates)).attribute('locale', locale).render()
```

I get the following error

```text
2022-02-15 19:54:04,757 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (vert.x-worker-thread-0) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#processTemplateErrors threw an exception: io.quarkus.qute.TemplateException: Found template problems (1):
[1] Incorrect expression found: {it}
	- it is not a parameter of the message bundle method net.dummy.example.i18n.ErrorMessages#errorMessage()
	- at net.dummy.example.i18n.ErrorMessages#errorMessage():1
	at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:200)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	Suppressed: io.quarkus.qute.TemplateException: Incorrect expression found: {it}
	- it is not a parameter of the message bundle method net.dummy.example.i18n.ErrorMessages#errorMessage()
	- at net.dummy.example.i18n.ErrorMessages#errorMessage():1
		at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:174)
		... 11 more
```

@Message("FROM i18n A booking for user {user} in the selected period {#each period}{it}{#if it_hasNext}, {/if}{/each} already exists.")

I have an interface like this:
```java
@MessageBundle(value = "error")
public interface ErrorMessages {

    @Message("Information in the selected period {#each dates}{it}{/each} already exists.")
    String errorMessage(List<String> dates);

}
```

### Expected behavior

I want it to return
`Information in the selected period 2022-02-15, 2022-02-16 already exists.`

### Output of `java -version`

Oracle JDK 11

### Quarkus version or git rev

2.7.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by mkouba** [comment]
@nunocasteleira Thanks for reporting! You're right, we need to relax the validation for similar use cases.

**Comment by mkouba** [comment]
https://github.com/quarkusio/quarkus/pull/23751 should fix the problem.

**Comment by nunocasteleira** [comment]
Thanks for the awesome support and quick fix!

**Comment by nunocasteleira** [comment]
It is still impossible to use the full range of templating features, such as this one:
`@Message("A booking for user {user} in the selected period {#each period}{it}{#if it_hasNext}, {/if}{/each} already exists.")`.

**Comment by mkouba** [comment]
> It is still impossible to use the full range of templating features, such as this one: `@Message("A booking for user {user} in the selected period {#each period}{it}{#if it_hasNext}, {/if}{/each} already exists.")`.

@nunocasteleira what kind of error do you get?

**Comment by nunocasteleira** [comment]
@mkouba
`Caused by: io.quarkus.qute.TemplateException: Found template problems (1):
[1] Incorrect expression found: {it_hasNext}
	- it_hasNext is not a parameter of the message bundle method net.appname.i18n.ErrorMessages#bookingAlreadyExists()`

**Comment by mkouba** [comment]
Ok, so it's the iteration metadata. I'll try to prepare a fix tomorrow.

**Comment by mkouba** [comment]
@nunocasteleira here it is: https://github.com/quarkusio/quarkus/pull/24403
