### ISSUE TITLE
With logging, `java.util.MissingFormatArgumentException: Format specifier '%%'`

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#23769]
### Describe the bug

When logging a message, an exception like the following is thrown:

```java
java.util.MissingFormatArgumentException: Format specifier '%%'
Listening for transport dt_socket at address: 4004
	at org.wildfly.common.format.Printf.formatDirect(Printf.java:452)
	at org.jboss.logmanager.formatters.ColorPrintf.formatDirect(ColorPrintf.java:45)
	at org.wildfly.common.format.Printf.format(Printf.java:98)
	at org.jboss.logmanager.formatters.ColorPatternFormatter.formatMessage(ColorPatternFormatter.java:141)
	at org.jboss.logmanager.formatters.Formatters$16.renderRaw(Formatters.java:781)
	at org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:221)
	at org.jboss.logmanager.formatters.ColorPatternFormatter$ColorStep.render(ColorPatternFormatter.java:160)
	at org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:86)
	at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:32)
	at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:43)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
	at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:80)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
	at org.jboss.logmanager.Logger.log(Logger.java:708)
	at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
	at org.jboss.logging.Logger.infof(Logger.java:1125)
        ... (more stuff)
```

This happens when logging a message whose format string contains the string `%%` after all `printf` format specifiers (i.e. a `%%` is the last `%` sequence in the string).

### Workaround

To work around this issue, an extra argument can be given to the log method (for example, add `, null` to the end of the arguments to the log method).  This argument will be ignored but it will allow the check to pass.

**Comment by AkMo3** [comment]
Hey @dmlloyd, I looking to contribute to this project, and this issue seems to be an easy starting point. Can you please let me know how can I reproduce it?

**Comment by dmlloyd** [comment]
> Hey @dmlloyd, I looking to contribute to this project, and this issue seems to be an easy starting point. Can you please let me know how can I reproduce it?

I'm glad you're interested! Unfortunately I've already fixed the problem - it was indeed an easy fix. (It's in a dependent component, and due to the way our Nexus instance works, the component won't find it's way to the upstream Maven servers until tomorrow, which is why there's no PR yet). You might consider hanging out on the [Zulip chat](https://quarkusio.zulipchat.com/) though if you're interested in contributing; it's a pretty high-volume project so things come up all the time.
