### ISSUE TITLE
Knative autoscaling properties create incorrect manifest files

### ISSUE THREAD

**Issue by tlloyd-synalogik** [quarkusio/quarkus#23786]
### Describe the bug

Attempting to switch off Knative autoscaling via configuration properties does not work as expected.

This affects the following properties and values:
1. `quarkus.knative.scale-to-zero-enabled = false`
2. `quarkus.knative.min-scale = 1`

Deploying a sample application to a local Kubernetes cluster produces the following behaviour:
1. When `quarkus.knative.scale-to-zero-enabled` is set to false this property is ignored and the pod will still terminate after ~60-90s.
2. When `quarkus.knative.min-scale` is set to 1 the maven build will fail when the fabric8 K8s client attempts a deployment with the following stack trace:
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.7.1.Final:build (default) on project knative-demo: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy threw an exception: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://127.0.0.1:52678/apis/serving.knative.dev/v1/namespaces/default/services. Message: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: invalid key name "autoscaling.knative.dev/minScale": metadata.annotations
[ERROR] autoscaling annotations must be put under "spec.template.metadata.annotations" to work. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: invalid key name "autoscaling.knative.dev/minScale": metadata.annotations
[ERROR] autoscaling annotations must be put under "spec.template.metadata.annotations" to work, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
[ERROR]         at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682)
[ERROR]         at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:661)
[ERROR]         at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:612)
[ERROR]         at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:555)
[ERROR]         at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:518)
[ERROR]         at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:305)
[ERROR]         at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:644)
[ERROR]         at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:83)
[ERROR]         at io.fabric8.kubernetes.client.dsl.base.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:61)
[ERROR]         at io.fabric8.kubernetes.client.utils.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:48)
[ERROR]         at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:318)
[ERROR]         at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:83)
[ERROR]         at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:105)
[ERROR]         at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:63)
[ERROR]         at io.quarkus.kubernetes.deployment.KubernetesDeployer.lambda$deploy$4(KubernetesDeployer.java:224)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[ERROR]         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[ERROR]         at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[ERROR]         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[ERROR]         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR]         at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[ERROR]         at io.quarkus.kubernetes.deployment.KubernetesDeployer.deploy(KubernetesDeployer.java:199)
[ERROR]         at io.quarkus.kubernetes.deployment.KubernetesDeployer.deploy(KubernetesDeployer.java:110)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

The use case is having at least one pod instance running for local development in order to retain application logs (scale to zero removes the pod after a period of no activity and therefore also the logs).

### Expected behavior

The Kubernetes pod running the application code should not terminate and a single instance should be kept alive.

When `quarkus.knative.scale-to-zero-enabled` is set to false the `knative.yml` manifest should include the missing namespace as per the [Knative docs](https://knative.dev/docs/serving/autoscaling/scale-to-zero/#enable-scale-to-zero):
```diff
apiVersion: v1
kind: ConfigMap
metadata:
 name: config-autoscaler
+ namespace: knative-serving
data:
 enable-scale-to-zero: "false"
```

When `quarkus.knative.min-scale` is set to 1, the relevant Knative annotation should be present in the correct location in the `knative.yml` manifest as per the [Knative docs](https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound):
```diff
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-demo
  namespace: default
-  annotations:
-        autoscaling.knative.dev/minScale: "1"
+spec:
+  template:
+    metadata:
+      annotations:
+        autoscaling.knative.dev/min-scale: "1"
```

### Actual behavior

When `quarkus.knative.scale-to-zero-enabled` is set to false the pod running the application will terminate ~60-90s.
The `knative.yml` file will include a ConfigMap for autoscaling, however the required namespace `knative-serving` will be missing.

When `quarkus.knative.min-scale` is set to 1, the maven build will fail with a deployment error.

### How to Reproduce?

Prerequisites:
- [docker](https://www.docker.com/products/docker-desktop) installed and running
- [kind](https://kind.sigs.k8s.io/) installed
- [ctlptl](https://github.com/tilt-dev/ctlptl) installed
- [kubectl](https://kubernetes.io/docs/reference/kubectl/kubectl/) installed

```shell
# Bootstrap Quarkus K8s project
mvn io.quarkus.platform:quarkus-maven-plugin:2.7.1.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=knative-demo \
    -Dextensions="resteasy,kubernetes,jib"

cd knative-demo

# Create local KinD K8s cluster with image registry
ctlptl create registry ctlptl-registry --port=5005
ctlptl create cluster kind --registry=ctlptl-registry

# Install Knative on cluster
kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.2.0/serving-crds.yaml
kubectl wait --for=condition=Established --all crd
kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.2.0/serving-core.yaml
kubectl wait pod --timeout=-1s --for=condition=Ready -l '!job-name' -n knative-serving

kubectl patch configmap/config-deployment \
  --namespace knative-serving \
  --type merge \
  --patch '{"data":{"registriesSkippingTagResolving":"localhost:5005"}}'

# Issue 1 - Disable scale to zero
mvn clean package \
  -Dquarkus.container-image.registry=localhost:5005 \
  -Dquarkus.container-image.insecure=true \
  -Dquarkus.kubernetes.deployment-target=knative \
  -Dquarkus.kubernetes.deploy=true \
  -Dquarkus.kubernetes-client.namespace=default \
  -Dquarkus.knative.scale-to-zero-enabled=false

# Check pod autoscaling
kubectl get pod --watch

# Issue 2 - Set min scale for autoscaling
mvn clean package \
  -Dquarkus.container-image.registry=localhost:5005 \
  -Dquarkus.container-image.insecure=true \
  -Dquarkus.kubernetes.deployment-target=knative \
  -Dquarkus.kubernetes.deploy=true \
  -Dquarkus.kubernetes-client.namespace=default \
  -Dquarkus.knative.min-scale=1

# Cleanup
ctlptl delete cluster kind-kind
ctlptl delete registry ctlptl-registry

```

### Output of `uname -a` or `ver`

```
Darwin Thomass-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
```

### Output of `java -version`

```
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
```

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /Users/t.lloyd/.asdf/installs/maven/3.8.3
Java version: 11.0.10, vendor: Amazon.com Inc., runtime: /Users/t.lloyd/.asdf/installs/java/corretto-11.0.10.9.1
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

### Additional information

It would be useful if the [Kubernetes documentation](https://quarkus.io/guides/deploying-to-kubernetes) could be updated to include more information on Knative autoscaling. I only discovered these properties by consulting the [configuration properties reference](https://quarkus.io/guides/all-config).

It would also be worth explaining the difference between the 2 properties listed i.e. `quarkus.knative.scale-to-zero-enabled` will create a ConfigMap affecting autoscaling for **all** Knative functions in the cluster whereas `quarkus.knative.min-scale` will affect the target function revision only.

**Comment by geoand** [comment]
Thanks for the detailed report!

@iocanel @Sgitario can we fix this?

**Comment by Sgitario** [comment]
+1 I will take a look into this issue
