### ISSUE TITLE
IllegalStateException if method return type is CompletionStage<Xxx> using @CacheResult

### ISSUE THREAD

**Issue by leotu** [quarkusio/quarkus#23816]
### Describe the bug

Method return type is CompletionStage<Xxx> cause "The current thread cannot be blocked: vert.x-eventloop-thread-xx"

```java
  // raise exception
 @CacheResult(cacheName = "/api/m/test/stage")
 @GET
 @Path("/stage")
 @Produces(MediaType.TEXT_PLAIN)
 public CompletionStage<String> stage() {
      return CompletableFuture.completedFuture("stage:" + LocalDateTime.now());
 }
```

### Expected behavior
 
Should work when function return type CompletionStage<XXX> Annotated with  @CacheResult or  @CacheInvalidate

### Actual behavior

```java
13:12:33.165 DEBUG [vert.x-eventloop-thread-8] [null:-1,null()] RoutingContext failure (500): java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-8
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)
	at io.quarkus.cache.runtime.CacheResultInterceptor.intercept(CacheResultInterceptor.java:115)
	at io.quarkus.cache.runtime.CacheResultInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.xgosh.test.TestResource_Subclass.stage(Unknown Source)
	at com.xgosh.test.TestResource_ClientProxy.stage(Unknown Source)
	at com.xgosh.test.TestResource$quarkusrestinvoker$stage_971e8502f0474c9186922d25a243c5718389abdd.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
```

### How to Reproduce?

Test Code

```java
/**
 * <pre>
 * http://localhost:7070/api/m/test/normal
 * http://localhost:7070/api/m/test/uni
 * http://localhost:7070/api/m/test/stage
 * http://localhost:7070/api/m/test/stageBlocking
 * </pre>
 */
@RegisterForReflection
@ApplicationScoped
@Path("/api/m/test")
public class TestResource {

    /**
     * No error
     */
    @CacheResult(cacheName = "/api/m/test/normal")
    @GET
    @Path("/normal")
    @Produces(MediaType.TEXT_PLAIN)
    public String normal() {
        return "normal:" + LocalDateTime.now();
    }

    /**
     * No error
     */
    @CacheResult(cacheName = "/api/m/test/uni")
    @GET
    @Path("/uni")
    @Produces(MediaType.TEXT_PLAIN)
    public Uni<String> uni() {
        return Uni.createFrom().item("uni:" + LocalDateTime.now());
    }

    /**
     * Error
     */
    @CacheResult(cacheName = "/api/m/test/stage")
    @GET
    @Path("/stage")
    @Produces(MediaType.TEXT_PLAIN)
    public CompletionStage<String> stage() {
        return CompletableFuture.completedFuture("stage:" + LocalDateTime.now());
    }

    /**
     * No error
     */
    @CacheResult(cacheName = "/api/m/test/stageBlocking")
    @GET
    @Path("/stageBlocking")
    @Produces(MediaType.TEXT_PLAIN)
    @Blocking
    public CompletionStage<String> stageBlocking() {
        return CompletableFuture.completedFuture("stageBlocking:" + LocalDateTime.now());
    }

}
```

### Output of `java -version`

```txt
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 21.3.1 (build 17.0.2+8-jvmci-21.3-b09)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.1 (build 17.0.2+8-jvmci-21.3-b09, mixed mode, sharing)
```
### GraalVM version (if different from Java)

GraalVM CE 21.3.1 

### Quarkus version or git rev

2.7.1.Final

**Comment by leotu** [comment]
Note: 
Downgrade to version 2.6.3.Final, still failed
Downgrade to version 2.5.4.Final, works
