### ISSUE TITLE
Not able to connect to Apicurio dev service when running integration tests

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#23916]
### Describe the bug

I have an application which listens for events on Kafka and processes them. This application also uses an Apicurio schema registry. This application has integration tests which use a `QuarkusTestResourceLifecycleManager` to create a `KafkaProducer` to "drop" events onto the Kafka topic for the application to consume in the tests. The Kafka broker & Apicurio schema registry are started/provided by Dev Services.

https://github.com/quarkusio/quarkus-super-heroes/blob/main/event-statistics/src/test/java/io/quarkus/sample/superheroes/statistics/KafkaProducerResource.java is the class, and https://github.com/quarkusio/quarkus-super-heroes/tree/main/event-statistics is the application. The test resource class is reading the `mp.messaging.connector.smallrye-kafka.apicurio.registry.url` property provided by the Apicurio dev services and setting it's value as the `SerdeConfig.REGISTRY_URL` in the `KafkaProducer` config.

When running the integration tests against a containerized JVM version of the application (i.e. when running `./mvnw clean verify -Dquarkus.container-image.build=true`) the `KafkaProducer` doesn't appear to be able to communicate with the Apicurio schema registry.

### Expected behavior

I would expect that my integration test should be able to interact with the Apicurio schema registry started by dev services.

### Actual behavior

When I try to run the IT tests I can see in the logs that it is starting the container and specifying the network:

```shell
Executing "docker run --name quarkus-integration-test-hcIks --rm -p 64917:64917 -p 8444:8444 --net=66250d06c4a45a0142a4600e9df09ed472fd8692f0be2d7a319495bb8ff486d9 --env QUARKUS_HTTP_PORT=64917 --env QUARKUS_HTTP_SSL_PORT=8444 --env TEST_URL=http://0.0.0.0:0 --env KAFKA_BOOTSTRAP_SERVERS=PLAINTEXT://kafka-mYSzY:29092,OUTSIDE://localhost:49158 --env MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL=http://kafka-Wm7Ac:8080/apis/registry/v2 quay.io/quarkus-super-heroes/event-statistics:java11-latest"
```

My question is - how do I use that `containerNetworkId` in the construction of the `KafkaProducer`, specifically in the `SerdeConfig.REGISTRY_URL` pointing to the apicurio registry? It doesn't appear that the apicurio instance is exposed outside of the container network. The tests fail with:

```shell
[ERROR] io.quarkus.sample.superheroes.statistics.endpoint.WebSocketsIT.testScenarios  Time elapsed: 10.983 s  <<< ERROR!
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.net.UnknownHostException: Failed to resolve 'kafka-Wm7Ac' after 3 queries 
        at event.statistics@1.0/io.quarkus.sample.superheroes.statistics.endpoint.WebSocketsIT.testScenarios(WebSocketsIT.java:81)
Caused by: java.util.concurrent.ExecutionException: java.net.UnknownHostException: Failed to resolve 'kafka-Wm7Ac' after 3 queries 
        at event.statistics@1.0/io.quarkus.sample.superheroes.statistics.endpoint.WebSocketsIT.testScenarios(WebSocketsIT.java:81)
Caused by: java.net.UnknownHostException: Failed to resolve 'kafka-Wm7Ac' after 3 queries 
```

### Output of `uname -a` or `ver`

Darwin edeandre-mac 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### Quarkus version or git rev

2.7.2.Final (but has been nagging me for a few releases now)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /Users/edeandre/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Users/edeandre/.sdkman/candidates/java/11.0.2-open Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by edeandrea** [comment]
I think the underlying problem is that the Apicurio registry is not exposed outside of the docker network? The test class (which is not running in a container) can not access the container on the docker network.

**Comment by edeandrea** [comment]
Hi just wanted to get any information about this? Even after switching my tests to use the `KafkaCompanion`, the integration tests are still not able to work.

Clone https://github.com/quarkusio/quarkus-super-heroes, go into either the `rest-fights` or `event-statistics` directory and run `./mvnw clean verify -Dquarkus.container-image.build=true`. The integration tests fail because the `KafkaCompanion` producer/consumer in the ITs can't talk to apicurio.

**Comment by edeandrea** [comment]
Hi - any thoughts on this?

**Comment by cescoffier** [comment]
@geoand did the fix got pushed?

**Comment by edeandrea** [comment]
@cescoffier no I'm using Docker. This fails when running as a GitHub action as well.

**Comment by edeandrea** [comment]
The problem is that the test class executing the integration test uses a KafkaCompanion and is unable to reach the apicurio instance started by dev services because. My guess is that

a) the apicurio instance is not exposed outside of the container network

b) the hostname configured by dev services is specific to the container network and not reachable by the host process

I could be wrong though. I just know it doesn't work

**Comment by ozangunalp** [comment]
First of all, I am running into another issue running integration tests on a container image build. Using minikube as docker machine, the docker host is not on localhost, but on 192.168.205.4. But the test uri's injected into tests with `@TestHTTPResource` have `localhost`. I had to pass `-Dtest.url='http://192.168.205.4:${quarkus.http.port}'` to the command line for it to work. 

I think the described error is related. For Kafka dev service it is not an issue : Kafka dev service bootstrap servers config has 2 URLs, one for internal docker network, one for external. So even though docker network hostname `kafka-Wm7Ac` is not resolvable from the host, the second URL is. For Apicurio, the registry URL we are getting from the application config is for internal docker network, therefore not accessible from tests running on the host. 

I think this was an issue for DB dev services as well. In integration tests dev service DBs are not accessible.

**Comment by edeandrea** [comment]
Hi folks. Any progress on this?

**Comment by cescoffier** [comment]
I think @ozangunalp had a look but that was a few months ago.

**Comment by cescoffier** [comment]
Do we know if this is still an issue?

**Comment by edeandrea** [comment]
It was the last time I tried it.

**Comment by ozangunalp** [comment]
As I mentioned before this is a more global issue with with how dev services are run on integration tests. I haven't spend the time to look at it yet.

**Comment by edeandrea** [comment]
I just tried it again and can verify it is still an issue. I think though that the issue is more generic - trying to run `@QuarkusIntegrationTest`s where the test itself needs to communicate with a dev service. 

In this specific case the test uses the kafka companion to communicate with the kafka broker. The kafka broker is exposed both on the container network and outside so both the app running as a container and the integration test itself can communicate with it.

The apicurio registry though is not exposed outside the container network, so the integration test is not able to communicate with it.

```shell
08:09:43 INFO  [io.qu.te.co.DefaultDockerContainerLauncher] (main) Executing "docker run --name quarkus-integration-test-ypCCR -i --rm -p 65263:65263 -p 8444:8444 --net=2e06fc91e5bf75ce5161c005fb1feb5c27107c9661ddc8218d513ab8e863bb28 --env QUARKUS_LOG_CATEGORY__IO_QUARKUS__LEVEL=INFO --env QUARKUS_HTTP_PORT=65263 --env QUARKUS_HTTP_SSL_PORT=8444 --env TEST_URL=http://0.0.0.0:0 --env MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL=http://kafka-nbjgm:8080/apis/registry/v2 --env QUARKUS_HTTP_HOST=0.0.0.0 --env KAFKA_BOOTSTRAP_SERVERS=PLAINTEXT://kafka-kfz5i:29092,OUTSIDE://localhost:55011 --env QUARKUS_CONTAINER_IMAGE_BUILD=true --env MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_SCHEMA_REGISTRY_URL=http://kafka-nbjgm:8080/apis/ccompat/v6 quay.io/quarkus-super-heroes/event-statistics:1.0"
```

**Comment by cescoffier** [comment]
@ozangunalp is it something we can fix, or is it something requiring dev service orchestration (something we do not really want). In addition, would the docker-compose approach you are working on provide a work around?

**Comment by cescoffier** [comment]
@ozangunalp ping?

**Comment by geoand** [comment]
Is this still an issue?

**Comment by edeandrea** [comment]
I'll check on monday

**Comment by edeandrea** [comment]
This is still an issue with Quarkus 3.32.1

```
[INFO] --- quarkus:3.32.1:build (default) @ event-statistics ---
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Selecting target 'minikube' since it has the highest priority among the implicitly enabled deployment targets
[WARNING] [io.quarkus.arc.deployment.SplitPackageProcessor] Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "io.apicurio.registry.client" found in [io.apicurio:apicurio-registry-java-sdk:3.1.7, io.apicurio:apicurio-registry-v2-java-sdk:3.1.7]
- "io.apicurio.registry.serde.avro" found in [io.apicurio:apicurio-registry-avro-serde-kafka:3.1.7, io.apicurio:apicurio-registry-serde-common-avro:3.1.7]
[INFO] [io.quarkus.smallrye-reactive-messaging-kafka.deployment.processor] Apicurio Registry Avro serde detected. Note: Apicurio Registry 3.x uses 4-byte schema IDs by default, while 2.x used 8-byte IDs. If consuming messages produced by Apicurio Registry 2.x, configure 'apicurio.registry.id-handler=io.apicurio.registry.serde.Legacy8ByteIdHandler' on your consumer channels for compatibility.
[WARNING] [io.quarkus.arc.processor.BeanArchives] Failed to index io.apicurio.common.apps.config.Info: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for event-statistics-1.0@5ca01434
[INFO] [io.quarkus.arc.processor.IndexClassLookupUtils] Class for name: io.apicurio.common.apps.config.Info was not found in Jandex index. Please ensure the class is part of the index.
[INFO] [io.quarkus.kubernetes.deployment.PropertyUtil] Kubernetes manifests are generated with 'The container port http' having provided value '8085'. The app and manifests will get out of sync if the property 'quarkus.http.port' is changed at runtime.
Invalid AnsiLogger Stream -> Swapping to default sdt out logger.
[INFO] Adding existing ConfigMap with name: event-statistics-config.
[INFO] Adding existing Secret with name: event-statistics-config-creds.
[INFO] Adding existing Deployment with name: fights-kafka.
[INFO] Adding existing Service with name: fights-kafka.
[INFO] Adding existing Deployment with name: apicurio.
[INFO] Adding existing Service with name: apicurio.
[INFO] Adding existing Route with name: apicurio.
[INFO] Testcontainers version: 2.0.3
[INFO] Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
[INFO] Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
[INFO] Docker host IP address is localhost
[INFO] Connected to docker: 
  Server Version: 5.4.2
  API Version: 1.41
  Operating System: fedora
  Total Memory: 11091 MB
[INFO] Image pull policy will be performed by: DefaultPullPolicy()
[INFO] Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
[INFO] Checking the system...
[INFO] ✔︎ Docker server version should be at least 1.6.0
[INFO] [io.quarkus.container.image.docker.common.deployment.CommonProcessor] Starting (local) container image build for jar using docker
[WARNING] [io.quarkus.container.image.docker.deployment.DockerProcessor] Using executable podman within the quarkus-container-image-docker extension. Maybe you should use the quarkus-container-image-podman extension instead?
[INFO] [io.quarkus.container.image.docker.common.deployment.CommonProcessor] Executing the following command to build image: 'podman build -f /Users/edeandre/workspaces/quarkus/quarkus-super-heroes/event-statistics/src/main/docker/Dockerfile.jvm -t quay.io/quarkus-super-heroes/event-statistics:1.0 /Users/edeandre/workspaces/quarkus/quarkus-super-heroes/event-statistics'
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] Built container image quay.io/quarkus-super-heroes/event-statistics:1.0

[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 17019ms
[INFO] 
[INFO] --- failsafe:3.5.5:integration-test (default) @ event-statistics ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
15:34:40 INFO  [or.te.DockerClientFactory] (build-7) Testcontainers version: 2.0.3
15:34:40 INFO  [or.te.do.DockerClientProviderStrategy] (build-7) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
15:34:41 INFO  [or.te.do.DockerClientProviderStrategy] (build-7) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
15:34:41 INFO  [or.te.DockerClientFactory] (build-7) Docker host IP address is localhost
15:34:41 INFO  [or.te.DockerClientFactory] (build-7) Connected to docker: 
  Server Version: 5.4.2
  API Version: 1.41
  Operating System: fedora
  Total Memory: 11091 MB
15:34:41 INFO  [or.te.im.PullPolicy] (build-7) Image pull policy will be performed by: DefaultPullPolicy()
15:34:41 INFO  [or.te.ut.ImageNameSubstitutor] (build-7) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
15:34:41 INFO  [or.te.DockerClientFactory] (build-7) Checking the system...
15:34:41 INFO  [or.te.DockerClientFactory] (build-7) ✔︎ Docker server version should be at least 1.6.0
15:34:41 INFO  [tc.do.io.1.2] (ForkJoinPool.commonPool-worker-2) Creating container for image: docker.io/redpandadata/redpanda:v24.1.2
15:34:41 INFO  [tc.qu.io.1.7] (ForkJoinPool.commonPool-worker-1) Creating container for image: quay.io/apicurio/apicurio-registry:3.1.7
15:34:41 INFO  [or.te.ut.RegistryAuthLocator] (ForkJoinPool.commonPool-worker-2) Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: docker.io/redpandadata/redpanda:v24.1.2, configFile: /Users/edeandre/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Status 404: No config supplied. Checked in order: /Users/edeandre/.docker/config.json (file not found), DOCKER_AUTH_CONFIG (not set)
15:34:41 INFO  [or.te.ut.RegistryAuthLocator] (ForkJoinPool.commonPool-worker-1) Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: quay.io/apicurio/apicurio-registry:3.1.7, configFile: /Users/edeandre/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Status 404: No config supplied. Checked in order: /Users/edeandre/.docker/config.json (file not found), DOCKER_AUTH_CONFIG (not set)
15:34:41 INFO  [tc.te.13.0] (ForkJoinPool.commonPool-worker-1) Creating container for image: testcontainers/ryuk:0.13.0
15:34:41 INFO  [or.te.ut.RegistryAuthLocator] (ForkJoinPool.commonPool-worker-1) Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.13.0, configFile: /Users/edeandre/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Status 404: No config supplied. Checked in order: /Users/edeandre/.docker/config.json (file not found), DOCKER_AUTH_CONFIG (not set)
15:34:41 INFO  [tc.te.13.0] (ForkJoinPool.commonPool-worker-1) Container testcontainers/ryuk:0.13.0 is starting: 9f656732d8d6ab4f90f8bd8426a6605f0093bb8adc71f879f015239bad1a5ff5
15:34:41 INFO  [tc.te.13.0] (ForkJoinPool.commonPool-worker-1) Container testcontainers/ryuk:0.13.0 started in PT0.201474S
15:34:41 INFO  [tc.do.io.1.2] (ForkJoinPool.commonPool-worker-2) Container docker.io/redpandadata/redpanda:v24.1.2 is starting: 11f1c9db62593ae1fb3e361a1cd024c6db6a1c6bbee9292ca86c412761e76cf0
15:34:41 INFO  [tc.qu.io.1.7] (ForkJoinPool.commonPool-worker-1) Container quay.io/apicurio/apicurio-registry:3.1.7 is starting: 573f6c0420edb4d906c8a06d2f101c6835f82d0bb62bbebf4c486b58ca507b8b
15:34:42 INFO  [tc.qu.io.1.7] (ForkJoinPool.commonPool-worker-1) Container quay.io/apicurio/apicurio-registry:3.1.7 started in PT1.016124S
15:34:42 INFO  [io.qu.ap.re.de.DevServicesApicurioRegistryProcessor] (ForkJoinPool.commonPool-worker-1) Dev Services for Apicurio Registry started. The registry is available at http://apicurio-registry-bbudj:8080/apis/registry/v3
15:34:43 INFO  [tc.do.io.1.2] (ForkJoinPool.commonPool-worker-2) Container docker.io/redpandadata/redpanda:v24.1.2 started in PT1.806263S
15:34:43 INFO  [io.qu.ka.cl.de.DevServicesKafkaProcessor] (ForkJoinPool.commonPool-worker-2) Dev Services for Kafka started. Other Quarkus applications in dev mode will find the broker automatically. For Quarkus applications in production mode, you can connect to this by starting your application with -Dkafka.bootstrap.servers=PLAINTEXT://redpanda-fwwzc:29092,OUTSIDE://localhost:44157
15:34:44 INFO  [io.qu.te.co.DefaultDockerContainerLauncher] (main) Executing "podman run --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-exports=java.base/jdk.internal.module=ALL-UNNAMED -Dquarkus-internal-test.serialized-app-model.path="/Users/edeandre/workspaces/quarkus/quarkus-super-heroes/event-statistics/target/quarkus/bootstrap/test-app-model.dat" --name quarkus-integration-test-oxYmj -i --rm -p 52506:52506 -p 8444:8444 --net=quarkus-integration-test-nuXRz --env QUARKUS_LOG_CATEGORY__IO_QUARKUS__LEVEL=INFO --env QUARKUS_HTTP_PORT=52506 --env QUARKUS_HTTP_SSL_PORT=8444 --env TEST_URL=http://localhost:${quarkus.http.test-port:8081} --env QUARKUS_PROFILE=prod --env MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL=http://apicurio-registry-bbudj:8080/apis/registry/v3 --env KAFKA_BOOTSTRAP_SERVERS=PLAINTEXT://redpanda-fwwzc:29092,OUTSIDE://localhost:44157 --env QUARKUS_CONTAINER_IMAGE_BUILD=true --env MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_SCHEMA_REGISTRY_URL=http://apicurio-registry-bbudj:8080/apis/ccompat/v7 quay.io/quarkus-super-heroes/event-statistics:1.0"
15:34:44 INFO  [io.qu.te.co.DefaultDockerContainerLauncher] (main) Wait for server to start by capturing listening data...
Failed to launch the application. The application logs can be found at: /Users/edeandre/workspaces/quarkus/quarkus-super-heroes/event-statistics/target/quarkus.log
[INFO] ---io.quarkus.sample.superheroes.statistics.endpoint.WebSocketsIT - 4.390 s
[INFO]    '-- [XX] testScenarios - 0.004 s
[INFO] [*] testScenarios
[INFO] 
[INFO] Stack trace
[INFO] java.lang.RuntimeException: java.lang.RuntimeException: Unable to successfully launch process '16554'. Exit code is: '125'.
        at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:384)
        at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:122)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
Caused by: java.lang.RuntimeException: Unable to successfully launch process '16554'. Exit code is: '125'.
        at io.quarkus.test.common.LauncherUtil.ensureProcessIsAlive(LauncherUtil.java:131)
        at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:94)
        at io.quarkus.test.common.DefaultDockerContainerLauncher.start(DefaultDockerContainerLauncher.java:319)
        at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:160)
        at io.quarkus.test.junit.QuarkusIntegrationTestExtension.doProcessStart(QuarkusIntegrationTestExtension.java:327)
        at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:181)
        at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:141)
        ... 1 more

[INFO] 
[INFO] Standard out
15:34:40 INFO  [or.te.DockerClientFactory] (build-7) Testcontainers version: 2.0.3
15:34:40 INFO  [or.te.do.DockerClientProviderStrategy] (build-7) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
15:34:41 INFO  [or.te.do.DockerClientProviderStrategy] (build-7) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
15:34:41 INFO  [or.te.DockerClientFactory] (build-7) Docker host IP address is localhost
15:34:41 INFO  [or.te.DockerClientFactory] (build-7) Connected to docker: 
  Server Version: 5.4.2
  API Version: 1.41
  Operating System: fedora
  Total Memory: 11091 MB
15:34:41 INFO  [or.te.im.PullPolicy] (build-7) Image pull policy will be performed by: DefaultPullPolicy()
15:34:41 INFO  [or.te.ut.ImageNameSubstitutor] (build-7) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
15:34:41 INFO  [or.te.DockerClientFactory] (build-7) Checking the system...
15:34:41 INFO  [or.te.DockerClientFactory] (build-7) ✔︎ Docker server version should be at least 1.6.0
15:34:41 INFO  [tc.do.io.1.2] (ForkJoinPool.commonPool-worker-2) Creating container for image: docker.io/redpandadata/redpanda:v24.1.2
15:34:41 INFO  [tc.qu.io.1.7] (ForkJoinPool.commonPool-worker-1) Creating container for image: quay.io/apicurio/apicurio-registry:3.1.7
15:34:41 INFO  [or.te.ut.RegistryAuthLocator] (ForkJoinPool.commonPool-worker-2) Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: docker.io/redpandadata/redpanda:v24.1.2, configFile: /Users/edeandre/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Status 404: No config supplied. Checked in order: /Users/edeandre/.docker/config.json (file not found), DOCKER_AUTH_CONFIG (not set)
15:34:41 INFO  [or.te.ut.RegistryAuthLocator] (ForkJoinPool.commonPool-worker-1) Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: quay.io/apicurio/apicurio-registry:3.1.7, configFile: /Users/edeandre/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Status 404: No config supplied. Checked in order: /Users/edeandre/.docker/config.json (file not found), DOCKER_AUTH_CONFIG (not set)
15:34:41 INFO  [tc.te.13.0] (ForkJoinPool.commonPool-worker-1) Creating container for image: testcontainers/ryuk:0.13.0
15:34:41 INFO  [or.te.ut.RegistryAuthLocator] (ForkJoinPool.commonPool-worker-1) Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.13.0, configFile: /Users/edeandre/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Status 404: No config supplied. Checked in order: /Users/edeandre/.docker/config.json (file not found), DOCKER_AUTH_CONFIG (not set)
15:34:41 INFO  [tc.te.13.0] (ForkJoinPool.commonPool-worker-1) Container testcontainers/ryuk:0.13.0 is starting: 9f656732d8d6ab4f90f8bd8426a6605f0093bb8adc71f879f015239bad1a5ff5
15:34:41 INFO  [tc.te.13.0] (ForkJoinPool.commonPool-worker-1) Container testcontainers/ryuk:0.13.0 started in PT0.201474S
15:34:41 INFO  [tc.do.io.1.2] (ForkJoinPool.commonPool-worker-2) Container docker.io/redpandadata/redpanda:v24.1.2 is starting: 11f1c9db62593ae1fb3e361a1cd024c6db6a1c6bbee9292ca86c412761e76cf0
15:34:41 INFO  [tc.qu.io.1.7] (ForkJoinPool.commonPool-worker-1) Container quay.io/apicurio/apicurio-registry:3.1.7 is starting: 573f6c0420edb4d906c8a06d2f101c6835f82d0bb62bbebf4c486b58ca507b8b
15:34:42 INFO  [tc.qu.io.1.7] (ForkJoinPool.commonPool-worker-1) Container quay.io/apicurio/apicurio-registry:3.1.7 started in PT1.016124S
15:34:42 INFO  [io.qu.ap.re.de.DevServicesApicurioRegistryProcessor] (ForkJoinPool.commonPool-worker-1) Dev Services for Apicurio Registry started. The registry is available at http://apicurio-registry-bbudj:8080/apis/registry/v3
15:34:43 INFO  [tc.do.io.1.2] (ForkJoinPool.commonPool-worker-2) Container docker.io/redpandadata/redpanda:v24.1.2 started in PT1.806263S
15:34:43 INFO  [io.qu.ka.cl.de.DevServicesKafkaProcessor] (ForkJoinPool.commonPool-worker-2) Dev Services for Kafka started. Other Quarkus applications in dev mode will find the broker automatically. For Quarkus applications in production mode, you can connect to this by starting your application with -Dkafka.bootstrap.servers=PLAINTEXT://redpanda-fwwzc:29092,OUTSIDE://localhost:44157
15:34:44 INFO  [io.qu.te.co.DefaultDockerContainerLauncher] (main) Executing "podman run --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-exports=java.base/jdk.internal.module=ALL-UNNAMED -Dquarkus-internal-test.serialized-app-model.path="/Users/edeandre/workspaces/quarkus/quarkus-super-heroes/event-statistics/target/quarkus/bootstrap/test-app-model.dat" --name quarkus-integration-test-oxYmj -i --rm -p 52506:52506 -p 8444:8444 --net=quarkus-integration-test-nuXRz --env QUARKUS_LOG_CATEGORY__IO_QUARKUS__LEVEL=INFO --env QUARKUS_HTTP_PORT=52506 --env QUARKUS_HTTP_SSL_PORT=8444 --env TEST_URL=http://localhost:${quarkus.http.test-port:8081} --env QUARKUS_PROFILE=prod --env MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL=http://apicurio-registry-bbudj:8080/apis/registry/v3 --env KAFKA_BOOTSTRAP_SERVERS=PLAINTEXT://redpanda-fwwzc:29092,OUTSIDE://localhost:44157 --env QUARKUS_CONTAINER_IMAGE_BUILD=true --env MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_SCHEMA_REGISTRY_URL=http://apicurio-registry-bbudj:8080/apis/ccompat/v7 quay.io/quarkus-super-heroes/event-statistics:1.0"
15:34:44 INFO  [io.qu.te.co.DefaultDockerContainerLauncher] (main) Wait for server to start by capturing listening data...
[INFO] 
[INFO] Standard error
Failed to launch the application. The application logs can be found at: /Users/edeandre/workspaces/quarkus/quarkus-super-heroes/event-statistics/target/quarkus.log
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   WebSocketsIT.testScenarios » Runtime java.lang.RuntimeException: Unable to successfully launch process '16554'. Exit code is: '125'.
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by janscheidegger** [comment]
We currently face the same issue, I think the "problem" is that no port exposed, when a shared network is used, which is the case with IntegrationTests. 
See: https://github.com/quarkusio/quarkus/blob/main/extensions/schema-registry/devservice/deployment/src/main/java/io/quarkus/apicurio/registry/devservice/DevServicesApicurioRegistryProcessor.java#L197

I think this access is needed for the companion to be able to deserialize the Avro-Records.
