### ISSUE TITLE
quarkus.container-image.build error

### ISSUE THREAD

**Issue by kkk25641463** [quarkusio/quarkus#23934]
### Describe the bug

I build quarkus docker images for cli:
mvn clean package -Dextensions=container-image-docker -Dquarkus.container-image.build=true -DskipTests -Dquarkus.package.type=mutable-jar

### Expected behavior

the image can run with not error 

### Actual behavior

log print error : /home/jboss/dev not found
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:50)
	at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:45)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
Caused by: java.nio.file.AccessDeniedException: /home/jboss/dev
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
	at io.quarkus.deployment.mutability.DevModeTask.extractDevModeClasses(DevModeTask.java:104)
	at io.quarkus.deployment.mutability.DevModeTask.createDevModeContext(DevModeTask.java:78)
	at io.quarkus.deployment.mutability.DevModeTask.main(DevModeTask.java:53)
	... 8 more
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
2022-02-24 10:55:23,529 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:50)
	at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:45)

### Output of `uname -a` or `ver`

Linux localhost.localdomain 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

11.0.13

### Quarkus version or git rev

2.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.1

**Comment by geoand** [comment]
Are you using remote development mode?

**Comment by geoand** [comment]
Closing this as we never got feedback
