### ISSUE TITLE
QuarkusTest does not run @BeforeEach method of outer class when using @Nested test classes

### ISSUE THREAD

**Issue by Emmeral** [quarkusio/quarkus#23947]
### Describe the bug

Given the following test class:
```
import static org.junit.jupiter.api.Assertions.assertEquals;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

@QuarkusTest
public class DemonstratorTest {

    String outerValue;

    @BeforeEach
    void setUp() {
        outerValue = "outer";
    }

    @Nested
    public class NestedClass{

        String innerValue;

        @BeforeEach
        void setUp() {
            innerValue = "inner";
        }

        @Test
        void test() {
            assertEquals("inner", innerValue);
            assertEquals("outer", outerValue);
        }
    }
}
```

### Expected behavior

Both the outer and the inner `@BeforeEach` method are called before the test. Therefore the test succeeds.

### Actual behavior

The test fails because `outerValue` is actual `null`. If the `@QuarkusTest` annotation is removed from the outer class, the test succeeds as expected.

### How to Reproduce?

Run the test above.

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8) OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

### Quarkus version or git rev

2.7.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

### Additional information

If the public modifier of the outer class is removed, the test does not run at all and the following stacktrace is produced:
```
java.lang.NoSuchMethodException: my.package.DemonstratorTest.<init>()

	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:987)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeEachMethod(QuarkusTestExtension.java:796)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	...
```

**Comment by Sgitario** [comment]
Proposed solution in https://github.com/quarkusio/quarkus/pull/24172
