### ISSUE TITLE
RestEasy Reactive returns different resource class/method than RestEasy classic

### ISSUE THREAD

**Issue by chonton** [quarkusio/quarkus#23956]
### Describe the bug

I have an Api class and a Resource class:

```java
@Path("/v1/test")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@Authenticate(value = false)
public interface Api {
  String echoGet(@NotNull @QueryParam("message") String message);
}
```

```java
@Singleton
@Provider
public class Resource implements Api {

  @Override
  public String echoGet(String message) {
    return new message;
  }
}
```

And I have a ContainerRequestFilter

```java
@Singleton
@Provider
@Priority(Priorities.AUTHORIZATION)
public class AuthzContainerRequestFilter implements ContainerRequestFilter {

  private final ResourceInfo resourceInfo;

  @Inject
  public AuthzContainerRequestFilter(ResourceInfo resourceInfo) {
    this.resourceInfo = resourceInfo;
  }

  @Override
  public void filter(ContainerRequestContext reqCtx) {
    boolean requireAuthn;

    Authenticate annotation = getAuthenticateAnnotation();
    if (annotation != null) {
      requireAuthn = annotation.value();
    } else {
      // the default is authenticate if no annotation
      requireAuthn = true;
    }

   // code to implement authn
  }

  /**
   * Get authentication annotation
   *
   * @return relevant authentication
   */
  private Authenticate getAuthenticateAnnotation() {
    Method resourceMethod = resourceInfo.getResourceMethod();
    Authenticate authenticate = resourceMethod.getAnnotation(Authenticate.class);
    if (authenticate != null) {
      return authenticate;
    }
    Class<?> resourceClass = resourceInfo.getResourceClass();
    return resourceClass.getAnnotation(Authenticate.class);
  }
}

```

With RestEasy classic, ```ResourceInfo.getResourceClass()``` returns my Api class.  With RestEasy reactive, the result is my Resource class.

### Expected behavior

I expect RestEasy Reactive to be a drop-in replacement for RestEasy classic, returning the Api class

### Actual behavior

In RestEasy Reactive, resourceInfo.getResourceMethod() / resourceInfo.getResourceClass() return the Resource class.

### How to Reproduce?

Use above classes.

### Additional information

Over the years, and different jax-rs implementations have had different behaviors.  Sometimes the implementation returns the resource class, sometimes the api class.  I am not sure if the spec actually defines which should be returned.

I like the Api class/method to be returned.  This way the Api class has annotations which are part of the interface contract.

**Comment by geoand** [comment]
I don't see the spec defining what happens in this case or the TCK testing it.

@FroMage @stuartwdouglas WDYT? To me, it seems like what RESTEasy Reactive does makes more sense, but I'd like to hear your view on it as well.

**Comment by knutwannheden** [comment]
@geoand I have a very similar case where I have a registered `ExceptionMapper` provider, which has an injected `ResourceInfo` (injected via `@Context` in RestEasy Classic). In the case of RestEasy Classic this worked as expected (i.e. the `getResourceClass()` and `getResourceMethod()` methods returned the class and method of the called REST endpoint), whereas with RestEasy Reactive both return `null`. Let me know if I should report a separate issue for this use case.

**Comment by geoand** [comment]
@knutwannheden do you have a sample I can check?

**Comment by knutwannheden** [comment]
@geoand I've attached a simple reproducer example project. When you run `mvn verify` the test will fail. If you swap out `quarkus-resteasy-reactive` for `quarkus-resteasy` the test will pass.

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/9037202/code-with-quarkus.zip)

**Comment by geoand** [comment]
@knutwannheden yes, please open a new issue, as what you describe is different from this.

**Comment by knutwannheden** [comment]
> Also FWIW, your analysis of the problem is most likely correct, so you if also want to send a PR (with the proper tests), you are more than welcome to do so :)

Will do. Thanks for you feedback!

**Comment by myroch** [comment]
I would expect to get the target class in both cases, and not the API interface as per spec. The reason is quite simple, from the actual class I can get all interfaces and annotations, but from the API interface I'm not able to get target class. Can someone maybe help me, how to do that in currect quarkus version?

**Comment by geoand** [comment]
What you describe seems to be the behavior of RESTEasy Reactive currently as per the issue description

**Comment by jpraet** [comment]
When the injected ResourceInfo contains the implementation class instead of the API interface,
you cannot pass the result to UriBuilder.fromResource(), because that one expects a class annotated with @Path.

https://github.com/quarkusio/quarkus/blob/4377b307d7c8bc26f9e800ffa21279101813b3ac/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/jaxrs/UriBuilderImpl.java#L400-L411

**Comment by geoand** [comment]
That's interesting. Mind putting together a small reproducer that shows that issue?

**Comment by FroMage** [comment]
I am not surprised the TCK didn't test for this.

My intuition, before going to look for the spec or API docs, is that it's probably more useful to users to return the annotated method rather than any concrete method, because that's where the valuable annotations and signatures are going to be.

And now having checked the spec and javadocs, it does not mention anything either way, but the spec does give an example of using `ResourceInfo` to access more annotations, so my intuition is not invalid.

I guess that according to [annotation inheritance rules](https://jakarta.ee/specifications/restful-ws/4.0/jakarta-restful-ws-spec-4.0#annotationinheritance) we could return either the abstract method, or the concrete method, depending on which actually defines the annotations.

As for the class (`ResourceInfo` holds both the method and the class), given that the rules on annotation inheritance say that they are not inherited, we could infer that it should always be the concrete class?

Either way, it's rather arbitrary 🤷

**Comment by geoand** [comment]
I wonder if just updating `UriBuilderImpl#path` would do it :)

**Comment by FroMage** [comment]
Thing is that this is not just about the `@Path` annotation, but any other annotation.

On the other hand, there is a great divide over whether method annotations are inherited or not, and CDI says no. So, even though JAX-RS expects method annotations to be inherited, this won't work with all of them. Security annotations… I don't even remember.

Perhaps it's worth removing the ambiguity and providing a new subinterface with `getAnnotatedResourceMethod` and `getConcreteResourceMethod`? Users can get the containing resource class from either.

Though IIRC we had the goal of not requiring reflection so perhaps we should rather go with a class that allows access to annotations without exposing `Method`? 🤷

**Comment by jpraet** [comment]
> That's interesting. Mind putting together a small reproducer that shows that issue?

[rest-service.zip](https://github.com/user-attachments/files/27801599/rest-service.zip)

With quarkus-rest:

```
2026-05-15 14:40:35,979 INFO  [org.acme.GreetingResource] (executor-thread-1) Resource class: class org.acme.GreetingResource
2026-05-15 14:40:35,980 INFO  [org.acme.GreetingResource] (executor-thread-1) Resource method: public java.lang.String org.acme.GreetingResource.hello(java.lang.String)
2026-05-15 14:40:35,992 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello/test failed, error id: bdd9bbcb-2a80-4af1-94ba-56c81ceee97f-1: java.lang.IllegalArgumentException: class must be annotated with @Path
	at org.jboss.resteasy.reactive.common.jaxrs.UriBuilderImpl.path(UriBuilderImpl.java:408)
	at jakarta.ws.rs.core.UriBuilder.fromResource(UriBuilder.java:129)
	at org.acme.GreetingResource.hello(GreetingResource.java:32)
```

With quarkus-resteasy:

```
2026-05-15 14:39:48,875 INFO  [org.acme.GreetingResource] (executor-thread-1) Resource class: interface org.acme.GreetingResourceIntf
2026-05-15 14:39:48,876 INFO  [org.acme.GreetingResource] (executor-thread-1) Resource method: public abstract java.lang.String org.acme.GreetingResourceIntf.hello(java.lang.String)
```

**Comment by chonton** [comment]
> Though IIRC we had the goal of not requiring reflection so perhaps we should rather go with a class that allows access to annotations without exposing `Method`? 🤷

This is the most interesting solution to me.

**Comment by geoand** [comment]
> Perhaps it's worth removing the ambiguity and providing a new subinterface with getAnnotatedResourceMethod and getConcreteResourceMethod? Users can get the containing resource class from either.

Makes sense to me

> Though IIRC we had the goal of not requiring reflection so perhaps we should rather go with a class that allows access to annotations without exposing Method

We always supported various things in the spec that required such access
