### ISSUE TITLE
ForbiddenException / DenyAll Check / Happens with constructor argument in REST resource

### ISSUE THREAD

**Issue by ftrippel** [quarkusio/quarkus#24031]
### Describe the bug

I will provide two examples. Example 1 passes just fine, but Example 2 results in a ForbiddenException / DenyAll check when the field "registry" is accessed. Otherwise the setup is exactly the same.

Note: we are using Quarkus with Kotlin 1.6.10

### Expected behavior

There should not be a permission check on a constructor argument when accessed.

### Actual behavior

**Example 1 (works)**

```
@Path("/blueprint")
@RolesAllowed("authenticated")
class EchoRestResource() {

    @Inject
    private lateinit var registry: MeterRegistry // <-- This will work as there is no constructor argument involved

    companion object {
        private val logger = Logger.getLogger(EchoRestResource::class.java)
    }

    @GET
    @Path("/counter")
    fun counter(): Uni<Double> {
        val counter = registry.counter("counter1")
            counter.increment()
        return Uni.createFrom().item(
            counter.count()
        )
    }
}
```

**Example 1 (does not work)**

```
@Path("/blueprint")
@RolesAllowed("authenticated")
class EchoRestResource(
var registry: MeterRegistry // <-- Constructor argument not so good
) {

    companion object {
        private val logger = Logger.getLogger(EchoRestResource::class.java)
    }

    @GET
    @Path("/counter")
    fun counter(): Uni<Double> {
        val counter = registry.counter("counter1") // <-- This will fail, as a permission check happens here, when we try to access the registry object, but only when the registry is provided as constructor argument
            counter.increment()
        return Uni.createFrom().item(
            counter.count()
        )
    }
}
```

**Stacktrace of Exception (IntelliJ set to halt any thread on Exception)**

```
io.quarkus.security.ForbiddenException
	at io.quarkus.security.runtime.interceptor.check.DenyAllCheck.doApply(DenyAllCheck.java:32)
	at io.quarkus.security.runtime.interceptor.check.DenyAllCheck.apply(DenyAllCheck.java:20)
	at io.quarkus.security.runtime.interceptor.SecurityConstrainer.check(SecurityConstrainer.java:32)
	at io.quarkus.security.runtime.interceptor.SecurityConstrainer_Subclass.check$$superforward1(Unknown Source)
	at io.quarkus.security.runtime.interceptor.SecurityConstrainer_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.security.runtime.interceptor.SecurityConstrainer_Subclass.check(Unknown Source)
	at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:46)
	at io.quarkus.security.runtime.interceptor.SecurityHandler_Subclass.handle$$superforward1(Unknown Source)
	at io.quarkus.security.runtime.interceptor.SecurityHandler_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.security.runtime.interceptor.SecurityHandler_Subclass.handle(Unknown Source)
	at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor.intercept(RolesAllowedInterceptor.java:29)
	at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at c.m.x.EchoRestResource_Subclass.getRegistry(Unknown Source)
	at c.m.x.EchoRestResource.counter(EchoRestResource.kt:41)
	at c.m.x.EchoRestResource_Subclass.counter$$superforward1(Unknown Source)
	at c.m.x.EchoRestResource_Subclass$$function$$4.apply(Unknown Source)
```

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment 18.9 (build 11.0.11+9) OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode)

### GraalVM version (if different from Java)

We do not use GraalVM

### Quarkus version or git rev

2.7.2

Note: we are using Quarkus with Kotlin 1.6.10

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.3.3 ------------------------------------------------------------  Build time:   2021-12-22 12:37:54 UTC Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          11.0.11 (Oracle Corporation 11.0.11+9) OS:           Windows 10 10.0 amd64

**Comment by ftrippel** [comment]
Seems we have an error in our code. Sorry to report this.

**Comment by geoand** [comment]
Can you please attach a sample application that exhibits this behavior?

**Comment by geoand** [comment]
Closing as we never got a reproducer
