### ISSUE TITLE
2.7.2.Final does not start when smallrye-metrics is on classpath

### ISSUE THREAD

**Issue by laurentperez** [quarkusio/quarkus#24032]
### Describe the bug

Hello

I'm attempting to get client MP metrics per https://quarkus.io/guides/micrometer#quarkus-micrometer_quarkus.micrometer.binder.mp-metrics.enabled and https://quarkus.io/guides/smallrye-metrics

I am not using resteasy reactive but plain resteasy

When I add implementation("io.quarkus:quarkus-smallrye-metrics") as a dependency Quarkus does not start and throws below

Bug looks similar as https://github.com/apache/camel-quarkus/issues/2442 .

Is it a known bug ? I Did not find related issues 

```
2022-03-01 11:17:39,857 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.ChainBuildException: Multiple producers of item class io.quarkus.deployment.metrics.MetricsCapabilityBuildItem (io.quarkus.smallrye.metrics.deployment.SmallRyeMetricsProcessor#metricsCapabilityBuildItem)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:92)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:455)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:66)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:140)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:96)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.ChainBuildException: Multiple producers of item class io.quarkus.deployment.metrics.MetricsCapabilityBuildItem (io.quarkus.smallrye.metrics.deployment.SmallRyeMetricsProcessor#metricsCapabilityBuildItem)
	at io.quarkus.builder.BuildStepBuilder.build(BuildStepBuilder.java:198)
	at io.quarkus.builder.BuildStepBuilder.buildIf(BuildStepBuilder.java:212)
	at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$102(ExtensionLoader.java:817)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$103(ExtensionLoader.java:910)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
		at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
(snip, repeated dozens of times)
java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
	... 9 more
Caused by: java.lang.Throwable: This is the location of the conflicting producer (io.quarkus.micrometer.deployment.MicrometerProcessor#metricsCapabilityBuildItem).
	at io.quarkus.builder.BuildStepBuilder.build(BuildStepBuilder.java:198)
	at io.quarkus.builder.BuildStepBuilder.buildIf(BuildStepBuilder.java:212)
	at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$102(ExtensionLoader.java:817)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$103(ExtensionLoader.java:910)
	... 138 more




```

### Expected behavior

Quarks boots when I enable smallrye metrics

### Actual behavior

Does not boot

### How to Reproduce?

Add io.quarkus:quarkus-smallrye-metrics as a dependency

### Output of `java -version`

java 11

### Quarkus version or git rev

2.7.2.Final

### Additional information

Does not work on 2.6.3 either. Untested below.

**Comment by gsmet** [comment]
We really don't have enough information to help. Please provide a reproducer.

My guess would be that you have both Micrometer and SmallRye Metrics extensions but I could be mistaken.

**Comment by geoand** [comment]
We probably want to leverage the capabilities checks to make this illegal, see [this](https://github.com/quarkusio/quarkus/blob/2.7.2.Final/docs/src/main/asciidoc/capabilities.adoc#L16) for more information.

My guess is that all we need to do is add

```xml
                <configuration>
                    <capabilities>
                        <provides>io.quarkus.metrics</provides>
                    </capabilities>
                </configuration>
```

to https://github.com/quarkusio/quarkus/blob/2.7.2.Final/extensions/micrometer/runtime/pom.xml#L128

**Comment by gsmet** [comment]
Yeah but we need to make sure this capability is not used for other purposes (typically to make sure SmallRye Metrics is there) :).

**Comment by ebullient** [comment]
I can't find anyone directly referencing io.quarkus.metrics internally. But if it helps tools indicate there is a conflict, I'm ok with that.

**Comment by geoand** [comment]
The capabilities don't need to be referenced programmatically.

Quarkus does check that there are no duplicates before launching the build

**Comment by ebullient** [comment]
Right. The check that is preventing things from starting ALSO ensures there is only one metrics provider (that's why I wrote it that way). It was added at the same time as xml-based capability checks. I'm all for better error messages. ;)

**Comment by laurentperez** [comment]
Hi. Further info, setting https://quarkus.io/guides/micrometer#quarkus-micrometer_quarkus.micrometer.binder.mp-metrics.enabled to true works out of the box, we get metrics from our MP client. I don't need in fact to add sr-metrics

I sort of misunderstood sr-metrics, I thought it was the default implementation of MP metrics. I'm also using https://github.com/quarkiverse/quarkus-micrometer-registry/tree/main/micrometer-registry-statsd

I did not see the (red flagged) warning at https://quarkus.io/guides/smallrye-metrics "Use the SmallRye Metrics extension when it is required to retain MicroProfile specification compatibility.". The MM documentation at https://quarkus.io/guides/micrometer#quarkus-micrometer_quarkus.micrometer.binder.mp-metrics.enabled says compat layer may be removed later in the future, so it's a bit confusing

I guess this falls under the "not a bug"

**Comment by ebullient** [comment]
https://quarkus.io/blog/micrometer-metrics/ 
It doesn't say "removed" it says "moved" .. if/when we do so, we'll be super obvious about it (i.e. we might move it into its own extension someday).
