### ISSUE TITLE
Error while persisting list of entities - Hibernate reactive  Vert.x EventLoop thread

### ISSUE THREAD

**Issue by floflorentin** [quarkusio/quarkus#24030]
### Describe the bug

Hello, 
I'm using Hibernate Reactive Panache with RabbitMQ queues. 
The error occurs while trying to persist huge amount of entities.
I add several entities that contain an id and a string in a queue from a REST API. 

```
@Channel("token-out")
@OnOverflow(OnOverflow.Strategy.UNBOUNDED_BUFFER)
Emitter<RawLogEntity> emitter;

@POST
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public Uni<Response> insertLog(List<RawLogEntity> inputs) {
  return Panache.withTransaction(
                  () -> RawLogEntity.persist(inputs)
                          .onItemOrFailure().transform((success, error) -> {
                              if(error != null) {
                                  logger.severe("Error while inserting: " + error);
                                  return withServerError.get();
                              } else {
                                  logger.info("Inserted: " + inputs);
                                  inputs.forEach(emitter::send);
                                  return withCreated.apply(asLongStream.apply(inputs));
                              }
                          })
          );
```

The queue is consuming to parse the string and create a new entity "log" that contain a list of "token".
I made a batch that sends a multi of a List of LogEntity each second.

```
@Incoming(value = "token-in")
    @Outgoing(value = "batch-processor")
    public Multi<List<LogEntity>> processTokenization(Multi<JsonObject> incoming){
        return incoming.map(rawLog -> rawLog.mapTo(RawLogEntity.class))
                .map(rawLogEntity -> tokenization.tokenizeLog(rawLogEntity.id, rawLogEntity.log))
                .group()
                .intoLists()
                .every(Duration.ofMillis(1000));
    }

    @Merge
    @Incoming(value = "batch-processor")
    public Uni<Void> processBatch(List<LogEntity> logs) {
        return Panache.withTransaction(() -> LogEntity.persist(logs))
                .onFailure()
                .invoke(error -> {
                    LOGGER.log(Level.SEVERE, "Error while inserting log id in database");
                })
                .replaceWithVoid();
    }
```
This implementation is working but once I have inserted ~ 9K items, I get this error :

`ERROR [io.qua.mut.run.MutinyInfrastructure] (executor-thread-1) Mutiny had to drop the following exception: java.lang.IllegalStateException: HR000068: This method should exclusively be invoked from a Vert.x EventLoop thread; currently running on thread 'executor-thread-1'
	at org.hibernate.reactive.common.InternalStateAssertions.assertUseOnEventLoop(InternalStateAssertions.java:40)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.getReactiveConnection(ReactiveSessionImpl.java:1478)
	at org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.rollback(MutinySessionImpl.java:459)
	at org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.lambda$execute$4(MutinySessionImpl.java:442)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnCancellationCall$UniOnCancellationCallProcessor.execute(UniOnCancellationCall.java:84)
	at io.smallrye.mutiny.operators.uni.UniOnCancellationCall$UniOnCancellationCallProcessor.cancel(UniOnCancellationCall.java:67)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.cancel(UniOperatorProcessor.java:64)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.cancel(UniOnItemTransformToUni.java:89)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.cancel(UniOperatorProcessor.java:64)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.cancel(UniOnItemTransformToUni.java:89)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.cancel(UniOperatorProcessor.java:64)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.cancel(UniOnItemTransformToUni.java:87)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.cancel(UniOperatorProcessor.java:64)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.cancel(UniOperatorProcessor.java:64)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.cancel(UniOperatorProcessor.java:64)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.cancel(UniOnItemOrFailureFlatMap.java:79)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.cancel(UniToMultiPublisher.java:63)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.cancel(MultiFlatMapOp.java:643)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onFailure(MultiFlatMapOp.java:208)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onFailure(MultiOperatorProcessor.java:89)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.innerError(MultiFlatMapOp.java:530)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onFailure(MultiFlatMapOp.java:614)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onFailure(MultiOperatorProcessor.java:89)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onError(MultiSubscriber.java:73)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onError(SafeSubscriber.java:148)
	at io.smallrye.mutiny.helpers.HalfSerializer.onError(HalfSerializer.java:56)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onFailure(StrictMultiSubscriber.java:91)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onError(MultiSubscriber.java:73)
	at io.smallrye.mutiny.subscription.SerializedSubscriber.onFailure(SerializedSubscriber.java:102)
	at io.smallrye.mutiny.operators.multi.MultiBufferWithTimeoutOp$MultiBufferWithTimeoutProcessor.flushCallback(MultiBufferWithTimeoutOp.java:162)
	at io.smallrye.mutiny.operators.multi.MultiBufferWithTimeoutOp$MultiBufferWithTimeoutProcessor.lambda$new$0(MultiBufferWithTimeoutOp.java:104)`

The current batch greatly increases, messages per seconds rates.
I didn't see any implementation of batch in quarkus and I tried different implementation :
 
```
@Merge
@Incoming(value = "batch-processor")
@ReactiveTransactional
public Uni<?> processBatch(List<LogEntity> logs) {
    return Uni.createFrom().item(logs.stream().map(log -> log.persist()).toList());
}

```
This implementation does not insert anything, as well a using a Muti.SessionFactory.
Is persist a list or collection possible with hibernate reactive ?

### Expected behavior

The expected behavior is to insert a collection of entities the most efficient way.

### Output of `uname -a` or `ver`

 Linux Thinkpad 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

JAVA 17

### Quarkus version or git rev

2.7.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn quarkus:dev

**Comment by DavideD** [comment]
I don't think you are using Resteasy reactive. Make sure you have this dependency on the classpath:
```
       <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
```

**Comment by DavideD** [comment]
And not the regular resteasy

**Comment by floflorentin** [comment]
Thank you for your reply, unfortunately I already made sure to use resteasy reactive dependency... In order to be sure of it, I removed all dependencies that aren't reactive.

**Comment by DavideD** [comment]
The reason I've suggested it is beacuse the error says that the code is runnning in `executor-thread-1`. This shouldn't happen with Reasteasy reactive and that's why Hibernate Reactive is complaining. It should be an `event-loop-thread`.

Can you create a reproducer that we can run? Maybe using one of the quickstarts? https://github.com/quarkusio/quarkus-quickstarts

**Comment by DavideD** [comment]
I've just noticed this:

> This implementation is working but once I have inserted ~ 9K items, I get this error :

So, it normally works. It doesn't seem like an issue with Hibernate Reactive. It seems something else happens at some point that makes this run in the wrong thread.

**Comment by DavideD** [comment]
Interesting, it seems there was a timeout here:
```
io.smallrye.mutiny.operators.multi.MultiBufferWithTimeoutOp$MultiBufferWithTimeoutProcessor
```

that caused  a rollback of the transaction:
```
org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.rollback(MutinySessionImpl.java:459) 
```

So it could be a bug in reactive.

> I'm currently building a reproducer.

Great! Thanks a lot

**Comment by floflorentin** [comment]
The reproducer is now acccessible at :
https://github.com/floflorentin/demo-quarkus-hibernate-24030
Thank you again !

**Comment by floflorentin** [comment]
Hello, I've edited the duration between each batch to 10ms instead of 1000ms in the reproducer.
The error appears more quickly.

**Comment by DavideD** [comment]
Sorry, I haven't forgotten about this. We had some issues with our CI that I had to look into. I will get back to it soo

**Comment by geoand** [comment]
@DavideD perhaps this has since been fixed?

**Comment by DavideD** [comment]
I couldn't really replicate the error.

I've upgraded Quarkus to 3.14.4: https://github.com/DavideD/demo-quarkus-hibernate-24030/commit/a983a33771ed900045629398248dd3d8fd71e56e

@floflorentin Could you tell us if you are still having this issue, please?

**Comment by geoand** [comment]
Closing for lack of feedback
