### ISSUE TITLE
use "hibernate reactive with panache" in kafkaConsumerRebalanceListener throw javax.enterprise.context.ContextNotActiveException

### ISSUE THREAD

**Issue by liuzhaozhao** [quarkusio/quarkus#24067]
### Describe the bug

My kafka consume offset is stored in the database, every time to start, need in KafkaConsumerRebalanceListener query the database, and set up the consume offset, But each time performs a database query in KafkaConsumerRebalanceListener throw "javax.enterprise.context.ContextNotActiveException"

```java
@Slf4j
@ApplicationScoped
@Identifier("test-topic.rebalancer")
public class KafkaRebalanceListener implements KafkaConsumerRebalanceListener {
    private static final String CONSUME_GROUP = "test-topic-consume-group";
    @ConfigProperty(name = "device-status.init-rollback-seconds", defaultValue = "3600")
    Provider<Long> initRollbackSeconds;
    @Inject
    EventConsumeOffsetDao eventConsumeOffsetDao;

    @Override
    public void onPartitionsAssigned(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        log.info("Partitions assigned: {}", partitions);
        List<Integer> partitionNum = new ArrayList<>();
        for (TopicPartition partition : partitions) {
            partitionNum.add(partition.partition());
        }
        eventConsumeOffsetDao.getOffset(CONSUME_GROUP, partitionNum).map(list -> {
            Map<Integer, Long> offsets = new HashMap<>();
            list.forEach(o -> offsets.put(o.getPartitionNum(), o.getOffset()));
            return offsets;
        }).invoke(map -> {
            Map<TopicPartition, Long> requestOffset = new HashMap<>();
            long now = System.currentTimeMillis();
            long shouldStartAt = now - initRollbackSeconds.get() * 1000L;
            for (TopicPartition partition : partitions) {
                Long offset = map.get(partition.partition());
                if(offset != null) {
                    setOffset(consumer, partition, offset);
                } else {
                    requestOffset.put(partition, shouldStartAt);
                }
            }
            Map<TopicPartition, OffsetAndTimestamp> offsets = consumer.offsetsForTimes(requestOffset);
            for (Map.Entry<TopicPartition, OffsetAndTimestamp> position : offsets.entrySet()) {
                long target = position.getValue() == null ? 0L : position.getValue().offset();
                setOffset(consumer, position.getKey(), target);
            }
        }).await().indefinitely();
    }

    private void setOffset(Consumer<?, ?> consumer, TopicPartition partition, long offset) {
        log.info("Seeking position {} for partition {}", offset, partition);
        consumer.seek(partition, offset);
    }

    @Override
    public void onPartitionsRevoked(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        log.info("Partitions revoked: {}", partitions);
        recyclePersistence(consumer, partitions);
    }

    @Override
    public void onPartitionsLost(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        log.info("Partitions lost: {}", partitions);
        recyclePersistence(consumer, partitions);
    }

    private void recyclePersistence(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        // TODO
    }

}
```

```yml
mp:
  messaging:
    incoming:
      test-topic-in:
        connector: smallrye-kafka
        topic: test-topic
        group:
          id: test-topic-consume-group
        key:
          deserializer: io.vertx.kafka.client.serialization.JsonObjectDeserializer
        value:
          deserializer: xxxDeserializer
        auto:
          offset:
            reset: latest
        broadcast: false
        partitions: 3
        max.poll.records: 100
        consumer-rebalance-listener:
          name: test-topic.rebalancer
```

```log
2022-03-03 09:45:58.243[ERROR]-[vert.x-eventloop-thread-6]-[i.q.m.r.MutinyInfrastructure(49)]: Mutiny had to drop the following exception: javax.enterprise.context.ContextNotActiveException
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:46)
	at org.hibernate.reactive.mutiny.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.arc$delegate(Unknown Source)
	at org.hibernate.reactive.mutiny.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.createQuery(Unknown Source)
	at io.quarkus.hibernate.reactive.panache.common.runtime.CommonPanacheQueryImpl.createBaseQuery(CommonPanacheQueryImpl.java:316)
	at io.quarkus.hibernate.reactive.panache.common.runtime.CommonPanacheQueryImpl.createQuery(CommonPanacheQueryImpl.java:264)
	at io.quarkus.hibernate.reactive.panache.common.runtime.CommonPanacheQueryImpl.lambda$list$6(CommonPanacheQueryImpl.java:230)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:46)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:29)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.lambda$executeInVertxEventLoop$0(AbstractJpaOperations.java:43)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Expected behavior

Query the Kafka consume offset stored in the database and set the initial consumption location

### Actual behavior

throw javax.enterprise.context.ContextNotActiveException

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22000.168]

### Output of `java -version`

java version "11.0.10" 2021-01-19 

### Quarkus version or git rev

2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by cescoffier** [comment]
Because of Kafka execution model, you cannot use hibernate reactive from a rebalance listener. Rebalance listeners are not executed on an event loop but from the kafka polling thread. It's mandatory as these listeners must be blocking (to follow the rebalance protocol).

**Comment by cescoffier** [comment]
A workaround is to send a message on the event bus, do the recycling  in the event consumer (called on an event loop) and in the rebalance listener 'blocking' wait for a reply.

**Comment by liuzhaozhao** [comment]
> A workaround is to send a message on the event bus, do the recycling in the event consumer (called on an event loop) and in the rebalance listener 'blocking' wait for a reply.

Thanks for your reply, I will try it

**Comment by liuzhaozhao** [comment]
> A workaround is to send a message on the event bus, do the recycling in the event consumer (called on an event loop) and in the rebalance listener 'blocking' wait for a reply.

I found no examples of reactive access to data in kafkaRebalanceListener in the documentation:
https://quarkus.io/guides/kafka#consumer-rebalance-listener
https://smallrye.io/smallrye-reactive-messaging/3.14.1/kafka/consumer-rebalance-listener/

I have written a code that can be used according to the way you said, but it is not simple enough. Can The Quarkus team recommend the usage?

```java
@Slf4j
@ApplicationScoped
@Identifier("test-topic.rebalancer")
public class KafkaRebalanceListener implements KafkaConsumerRebalanceListener {
    @Inject
    EventBus bus;

    @Override
    public void onPartitionsAssigned(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        log.info("Partitions assigned: {}", partitions);
        List<Integer> partitionNum = new ArrayList<>();
        for (TopicPartition partition : partitions) {
            partitionNum.add(partition.partition());
        }
       List<EventConsumeOffset> offsets = bus.<List<EventConsumeOffset>>requestAndAwait("kafka-rebalance", partitionNum).body();
       // .....
    }

    // .....

}
```

```java
@ApplicationScoped
@Slf4j
public class EventBusConsumer {
    private static final String CONSUME_GROUP = "test-topic-consume-group";
    @Inject
    EventConsumeOffsetDao eventConsumeOffsetDao;

    @ConsumeEvent(value = "kafka-rebalance")
    @Blocking
    public MqInfo kafkaRebalance(List<Integer> partitionNum) {
        log.info("消费事件：{}", id);
        return eventConsumeOffsetDao.getOffset(CONSUME_GROUP, partitionNum).invoke(o -> .......).await().indefinitely();
    }
}
```

**Comment by cescoffier** [comment]
in your `onPartitionAssigned` do something like:

```java
MqInfo info = bus.<MqInfo>request("kafka-rebalance", partitions).await().indefinitely();
```

In the same bean or another one (up to you) do something like:

```java
 @ConsumeEvent(value = "kafka-rebalance")
  public Uni<MqInfo> kafkaRebalance(List<Integer> partitionNum) {
    // access your data store with hibernate reactive

  // return the resulting Uni
    return info;
}
```

**Comment by liuzhaozhao** [comment]
> in your `onPartitionAssigned` do something like:
> 
> ```java
> MqInfo info = bus.<MqInfo>request("kafka-rebalance", partitions).await().indefinitely();
> ```
> 
> In the same bean or another one (up to you) do something like:
> 
> ```java
>  @ConsumeEvent(value = "kafka-rebalance")
>   public Uni<MqInfo> kafkaRebalance(List<Integer> partitionNum) {
>     // access your data store with hibernate reactive
> 
>   // return the resulting Uni
>     return info;
> }
> ```

If EventBus needs to return a list, will be thrown java.lang.ClassNotFoundException: java.util.List<cn.xxx.MqInfo>
```java
@ConsumeEvent(value = "kafka-rebalance")
public Uni<List<MqInfo>> kafkaRebalance(List<Integer> partitionNum) {
    // access your data store with hibernate reactive

  // return the resulting Uni
    return list;
}
```

```log
2022-03-05 17:54:11.209[ERROR]-[Quarkus Main Thread]-[i.q.r.Application(188)]: Failed to start application (with profile dev): java.lang.ClassNotFoundException: java.util.List<cn.xxx.MqInfo>
	at io.quarkus.launcher.RuntimeLaunchClassLoader.findClass(RuntimeLaunchClassLoader.java:25)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:423)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:423)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.quarkus.deployment.steps.VertxProcessor$build609260703.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.VertxProcessor$build609260703.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at cn.ecpark.service.iov.analysis.Application.main(Application.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by liuzhaozhao** [comment]
Another issue I found was that EventBus could not be used in the onPartitionsRevoked event triggered when the application was shutdown, an exception was thrown: (NO_HANDLERS,-1) No handlers for address kafka-rebalance-revoked
```java
@Slf4j
@ApplicationScoped
@Identifier("test-topic.rebalancer")
public class KafkaRebalanceListener implements KafkaConsumerRebalanceListener {
    @Inject
    EventBus bus;

    @Override
    public void onPartitionsAssigned(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        // ....
    }

    @Override
    public void onPartitionsRevoked(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        log.info("Partitions revoked: {}", partitions);
        bus.<RecycleEventResponse>requestAndAwait(KafkaRebalanceEventConsumer.REVOKED_ADDRESS, new KafkaRebalanceEvent(consumer.groupMetadata().groupId(), partitions));
    }

    @Override
    public void onPartitionsLost(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        log.info("Partitions lost: {}", partitions);
    }

}
```
```java
@Slf4j
@ApplicationScoped
public class KafkaRebalanceEventConsumer {
    public static final String ASSIGNED_ADDRESS = "kafka-rebalance-assigned";
    public static final String REVOKED_ADDRESS = "kafka-rebalance-revoked";

    @Inject
    EventConsumeOffsetDao eventConsumeOffsetDao;
    @Inject
    DeviceStatusService deviceStatusService;


    @ConsumeEvent(value = REVOKED_ADDRESS, ordered= true)
    public Uni<RecycleEventResponse> kafkaRebalanceRevoked(KafkaRebalanceEvent event) {
        UniJoin.Builder<List<Integer>> builder = Uni.join().builder();
        for (org.apache.kafka.common.TopicPartition partition : event.getPartitions()) {
            builder.add(deviceStatusService.recyclePartition(partition.topic(), partition.partition()));
        }
        return builder.joinAll().andCollectFailures()
                .map(list -> list.stream().filter(l -> l != null && !l.isEmpty()).flatMap(Collection::stream).collect(Collectors.toList()))
                .map(r -> new RecycleEventResponse().setData(r));
    }

}
```

```log
2022-03-06 00:12:36.448[ERROR]-[smallrye-kafka-consumer-thread-0]-[i.s.r.m.kafka(42)]: SRMSG18222: Unable to execute consumer revoked re-balance listener for group 'iov-analysis-service': (NO_HANDLERS,-1) No handlers for address kafka-rebalance-revoked
	at io.vertx.core.eventbus.impl.EventBusImpl.deliverMessageLocally(EventBusImpl.java:359)
	at io.vertx.core.eventbus.impl.EventBusImpl.sendLocally(EventBusImpl.java:319)
	at io.vertx.core.eventbus.impl.EventBusImpl.sendOrPub(EventBusImpl.java:307)
	at io.vertx.core.eventbus.impl.OutboundDeliveryContext.next(OutboundDeliveryContext.java:131)
	at io.vertx.core.eventbus.impl.EventBusImpl.sendOrPubInternal(EventBusImpl.java:394)
	at io.vertx.core.eventbus.impl.EventBusImpl.sendOrPubInternal(EventBusImpl.java:400)
	at io.vertx.core.eventbus.impl.EventBusImpl.request(EventBusImpl.java:111)
	at io.vertx.core.eventbus.EventBus.request(EventBus.java:95)
	at io.vertx.core.eventbus.EventBus.request(EventBus.java:74)
	at io.vertx.mutiny.core.eventbus.EventBus.lambda$request$1(EventBus.java:125)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.vertx.AsyncResultUni.subscribe(AsyncResultUni.java:31)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:54)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:62)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:43)
	at io.vertx.mutiny.core.eventbus.EventBus.requestAndAwait(EventBus.java:147)
	at cn.ecpark.service.iov.analysis.event.consumer.KafkaRebalanceListener.onPartitionsRevoked(KafkaRebalanceListener.java:94)
	at cn.ecpark.service.iov.analysis.event.consumer.KafkaRebalanceListener_Subclass.onPartitionsRevoked$$superforward1(Unknown Source)
	at cn.ecpark.service.iov.analysis.event.consumer.KafkaRebalanceListener_Subclass$$function$$3.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at cn.ecpark.service.iov.analysis.event.consumer.KafkaRebalanceListener_Subclass.onPartitionsRevoked(Unknown Source)
	at cn.ecpark.service.iov.analysis.event.consumer.KafkaRebalanceListener_ClientProxy.onPartitionsRevoked(Unknown Source)
	at io.smallrye.reactive.messaging.kafka.impl.RebalanceListeners$1.onPartitionsRevoked(RebalanceListeners.java:39)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.invokePartitionsRevoked(ConsumerCoordinator.java:312)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onLeavePrepare(ConsumerCoordinator.java:750)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.close(AbstractCoordinator.java:1015)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.close(ConsumerCoordinator.java:898)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2385)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2352)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.lambda$close$24(ReactiveKafkaConsumer.java:369)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.lambda$runOnPollingThread$1(ReactiveKafkaConsumer.java:116)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by cescoffier** [comment]
That error means that no one is listening to that address. As you wait for a response and no one will ever reply, it just reject the message.

**Comment by liuzhaozhao** [comment]
> That error means that no one is listening to that address. As you wait for a response and no one will ever reply, it just reject the message.

There are listeners, I actively trigger events through HTTP and they respond eventbus. Just it can't respond  eventbus before the application is shut down, probably because EventBus listens to the service shutdown event and cancels the previously registered listeners in advance.

This is the test code:
```java
@Slf4j
@Path("/test")
public class TestResource {
    @Inject
    EventBus bus;

    @GET @Path("/revoked") @Produces(MediaType.APPLICATION_JSON)
    public List<Integer> eventbus(@QueryParam("group") String consumeGroup, @QueryParam("id") List<Integer> id) {
        return bus.<RecycleEventResponse>requestAndAwait(KafkaRebalanceEventConsumer.REVOKED_ADDRESS,
                        new KafkaRebalanceEvent("", id.stream().map(i -> new TopicPartition(consumeGroup, i)).collect(Collectors.toList())))
                .body().getData();
    }

}
```

**Comment by cescoffier** [comment]
Ah yes, on shutdown you can access the managed event bus. Everything has already been closed.

**Comment by cescoffier** [comment]
Closing - solution discussed in comments.
