### ISSUE TITLE
oidc-client configuration exception Environment 

### ISSUE THREAD

**Issue by stefanwendelmann** [quarkusio/quarkus#24078]
### Describe the bug

Environment Variable wont work properly.

```
// Works in application.properties
quarkus.oidc-client.auth-server-url=<PathtoKeycloak>
// Wont work in .env
QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=<PathtoKeycloak>
```

### Expected behavior

Same behavior in `.env` and in `application.properties`

### Actual behavior

```log
2022-03-03 14:30:33,270 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:148)
        at io.quarkus.oidc.common.runtime.OidcCommonUtils.initClientSecretBasicAuth(OidcCommonUtils.java:369)
        at io.quarkus.oidc.runtime.OidcProviderClient.<init>(OidcProviderClient.java:51)
        at io.quarkus.oidc.runtime.OidcRecorder$5.apply(OidcRecorder.java:315)
        at io.quarkus.oidc.runtime.OidcRecorder$5.apply(OidcRecorder.java:295)
        at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:54)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:46)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromPublisher$PublisherSubscriber.onNext(UniCreateFromPublisher.java:73)
        at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
        at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.subscription.SerializedSubscriber.onItem(SerializedSubscriber.java:75)
        at io.smallrye.mutiny.operators.multi.MultiRetryWhenOp$RetryWhenOperator.onItem(MultiRetryWhenOp.java:113)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onItem(UniToMultiPublisher.java:93)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
        at io.vertx.mutiny.ext.web.client.HttpRequest$10.handle(HttpRequest.java:727)
        at io.vertx.mutiny.ext.web.client.HttpRequest$10.handle(HttpRequest.java:724)
        at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:400)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:387)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:365)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:332)
        at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:294)
        at io.vertx.ext.web.client.impl.HttpContext.lambda$null$8(HttpContext.java:550)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)


2022-03-03 14:30:33,270 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (vert.x-worker-thread-0) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
        at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:122)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:232)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:213)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:535)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:436)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:152)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:139)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
        ... 1 more
Caused by: io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
        [Exception 0] java.util.NoSuchElementException: No value present
        [Exception 1] io.quarkus.oidc.OIDCException
        at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap$UniOnFailureFlatMapProcessor.performInnerSubscription(UniOnFailureFlatMap.java:94)
        at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap$UniOnFailureFlatMapProcessor.dispatch(UniOnFailureFlatMap.java:83)
        at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap$UniOnFailureFlatMapProcessor.onFailure(UniOnFailureFlatMap.java:60)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:54)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:54)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:91)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:54)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:46)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromPublisher$PublisherSubscriber.onNext(UniCreateFromPublisher.java:73)
        at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
        at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.subscription.SerializedSubscriber.onItem(SerializedSubscriber.java:75)
        at io.smallrye.mutiny.operators.multi.MultiRetryWhenOp$RetryWhenOperator.onItem(MultiRetryWhenOp.java:113)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onItem(UniToMultiPublisher.java:93)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
        at io.vertx.mutiny.ext.web.client.HttpRequest$10.handle(HttpRequest.java:727)
        at io.vertx.mutiny.ext.web.client.HttpRequest$10.handle(HttpRequest.java:724)
        at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:400)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:387)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:365)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:332)
        at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:294)
        at io.vertx.ext.web.client.impl.HttpContext.lambda$null$8(HttpContext.java:550)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
        Suppressed: io.quarkus.oidc.OIDCException
                at io.quarkus.oidc.runtime.OidcRecorder$3.apply(OidcRecorder.java:116)
                at io.quarkus.oidc.runtime.OidcRecorder$3.apply(OidcRecorder.java:98)
                at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
                at io.smallrye.mutiny.groups.UniOnFailure.lambda$recoverWithItem$8(UniOnFailure.java:190)
                at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap$UniOnFailureFlatMapProcessor.performInnerSubscription(UniOnFailureFlatMap.java:92)
                ... 36 more
        Caused by: java.util.NoSuchElementException: No value present
                at java.base/java.util.Optional.get(Optional.java:148)
                at io.quarkus.oidc.common.runtime.OidcCommonUtils.initClientSecretBasicAuth(OidcCommonUtils.java:369)
                at io.quarkus.oidc.runtime.OidcProviderClient.<init>(OidcProviderClient.java:51)
                at io.quarkus.oidc.runtime.OidcRecorder$5.apply(OidcRecorder.java:315)
                at io.quarkus.oidc.runtime.OidcRecorder$5.apply(OidcRecorder.java:295)
                at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
                at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
                ... 31 more
        [CIRCULAR REFERENCE:java.util.NoSuchElementException: No value present]
```

### How to Reproduce?

part pom.xml

```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-oidc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-oidc-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-oidc-client-reactive-filter</artifactId>
    </dependency>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-keycloak-authorization</artifactId>
    </dependency>
```

application.properties
```properties
# OIDC Configuration
quarkus.oidc.application-type=service
quarkus.oidc.tls.verification=none

quarkus.oidc.auth-server-url=http://keycloak:8080/auth/realms/quarkus
quarkus.oidc.token.issuer=https://quarkus.org/auth/realms/quarkus
quarkus.oidc.client-id=fancy-api

#OIDC Client
# Comment out the auth-server-url and activate it in the dotenv
quarkus.oidc-client.auth-server-url=http://keycloak:8080/auth/realms/quarkus
quarkus.oidc-client.client-id=fancy-api
quarkus.oidc-client.refresh-token-time-skew=5S
quarkus.oidc-client.tls.verification=none
```

.env
```dotenv
QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=http://keycloak:8080/auth/realms/quarkus
```

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 LTS OpenJDK Runtime Environment Microsoft-27990 (build 11.0.13+8-LTS) OpenJDK 64-Bit Server VM Microsoft-27990 (build 11.0.13+8-LTS, mixed mode)

### GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-native-image:21.3.0-java11

### Quarkus version or git rev

2.7.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.4

**Comment by sberyozkin** [comment]
I think @radcortez explained how to deal with it at #23963, have a look please

**Comment by stefanwendelmann** [comment]
also the problem is that i dont use `.env` in the production and staging environment, there i use the UNIX Environment Variables.

**Comment by stefanwendelmann** [comment]
so making a own Property and map it into the application.properties shold work i try it out in a while

**Comment by sberyozkin** [comment]
@stefanwendelmann 

> I think whats happening here is that the quarkus.oidc.auth-server-url and quarkus.oidc-client.auth-server-url are overlapping.

How are they overlapping ? The only common root is `quarkus`. But also, it works without the `env` properties, so may be something else is going on

**Comment by stefanwendelmann** [comment]
The first part ist overlapping, maybe this is the problem but idk.

`QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL` < oidc-client
`QUARKUS_OIDC_CLIENT_ID` < oidc

Maybe like you say something else is going on ^^

**Comment by stefanwendelmann** [comment]
Having the same OIDC Server for the `oidc` and `oidc-client` results me now in having:

```properties
#OIDC Client
quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}
quarkus.oidc-client.tls.verification=${quarkus.oidc.tls.verification}
quarkus.oidc-client.refresh-token-time-skew=5S
```

wich is working fine.

**Comment by stefanwendelmann** [comment]
No jut a thought, that it can indiffer, the `How To Reproduce` is still valid

**Comment by sberyozkin** [comment]
Thanks @radcortez, let me close it for now. @stefanwendelmann please reopen with a reproducer if it still does not work for you
