### ISSUE TITLE
Avro deserialization fails since 2.5 with Confluent serdes in smallrye-kafka reactive messaging

### ISSUE THREAD

**Issue by lw-mcno** [quarkusio/quarkus#24148]
### Describe the bug

I've a Kafka Streams service, successfully running with Quarkus 2.4. It connects to Confluent Schema Registry and uses Confluent Avro serializers / deserializers. There is a Maven `parent` module, an `avro` module containing and compiling Avro schemas and a `core` module, where the application resides. Tests additonally use smallrye-kafka Reactive messaging for sending test data and also for reading from topics written by Kafka streams (to e.g. compare with expected data).

I couldn't upgrade it to a newer version (2.5 IIRC, and 2.7.3 yesterday), because there's a problem in tests, when a smallrye-kafka channel tries to deserialize the specific messages for key / value.

The configuration for reading of records in test application.yaml looks like this:
```yaml
mp:
  messaging:
    incoming:
      my-test-data:
        connector: smallrye-kafka
        topic: ${my.outbound-topic}
        key:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema:
          registry:
            url: ${quarkus.kafka-streams.schema-registry-url}
        specific:
          avro:
            reader: true
```

and the exception that I get looks like this:
```java
mar 05, 2022 1:41:10 PM io.smallrye.reactive.messaging.kafka.impl.KafkaSource reportFailure
WARN: SRMSG18228: A failure has been reported for Kafka topics '[my.topic]'
java.lang.ClassCastException: class com.my.package.avro.schema.v1.MyKey cannot be cast to class org.apache.avro.specific.SpecificRecord (my.package.avro.schema.v1.MyKey is in unnamed module of loader 'app'; org.apache.avro.specific.SpecificRecord is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @77102b91)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.getSpecificReaderSchema(AbstractKafkaAvroDeserializer.java:286)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.getReaderSchema(AbstractKafkaAvroDeserializer.java:252)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.getDatumReader(AbstractKafkaAvroDeserializer.java:196)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer$DeserializationContext.read(AbstractKafkaAvroDeserializer.java:391)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:114)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:88)
	at io.confluent.kafka.serializers.KafkaAvroDeserializer.deserialize(KafkaAvroDeserializer.java:55)
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.lambda$deserialize$1(DeserializerWrapper.java:74)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.wrapDeserialize(DeserializerWrapper.java:106)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.deserialize(DeserializerWrapper.java:74)
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1436)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:135)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1671)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1507)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:733)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:684)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1304)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1238)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.lambda$poll$4(ReactiveKafkaConsumer.java:141)
...
```

The error happens in this line of `AbstractKafkaAvroDeserializer` (version 7.0.1):
```java
private Schema getSpecificReaderSchema(Schema writerSchema) {
...
    try {
      return readerClass.newInstance().getSchema();
    } catch (InstantiationException e) {
...
```

What's interesting, evaluating it in IntelliJ works without errors.

I guess this must be related to some changes in Quarkus class loading after 2.4, because if I move the .avsc files to the same Maven module, where the Quarkus application resides, then my tests start working again (that is, the records can be cast to SpecificRecord). The generated Java classes look the same in both cases (coming from the `avro` module and being generated in `core`). I'm using / Quarkus is using: Avro 1.11.0.

### Expected behavior

Using Java classes compiled by Avro, coming from a dependency module, still works.

### Actual behavior

The deserialization to Avro-generated Java classes in the following code still works:

```java
@Incoming("my-test-data")
public void receive(Record<MyKey, MyValue> record) {
    doSomething(record);
}
```

### How to Reproduce?

1. Service is using smallrye-kafka to ingest Avro-serialized messages form some Kafka topic
2. The Java classes generated from Avro schemas come from another maven module / jar
3. The code uses Avro deserializers from io.confluent:kafka-streams-avro-serde (e.g. 7.0.1)
4. When receiving a message, the reactive messaging code tries to deserialize it and fails 

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

17 (zulu)

### Quarkus version or git rev

2.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

**Comment by lw-mcno** [comment]
@cescoffier I've tried reproducing the problem using smallrye-kafka and confluent serdes using apicurio registry, but it works as expected in a simpler project. Unfortunately, I can't put a finger on the original cause of this in a more complex project. I wasn't able to get the route smallrye-kafka out -> kafka-streams -> smallrye-kafka-in (deserialization) up and running in a reasonable time, but maybe that (or using confluent schema registry in a container) would do it.

**Comment by cescoffier** [comment]
I've tried without luck, so a reproducer would be really great.

**Comment by cescoffier** [comment]
Closing - need a reproducer to understand what's going on.
Please re-open if the issue still happens.
