### ISSUE TITLE
Mutiny worker pool fails when used to resolve OIDC tenant config

### ISSUE THREAD

**Issue by mazenkhalil** [quarkusio/quarkus#24156]
### Describe the bug

TenantConfigResolver#resolve throws IllegalStateException if the returned Uni is run on the default worker thread from Mutiny.
e.g. Uni.createFrom().item(() -> getTenantConfig()).runSubscriptionOn(Infrastructure.getDefaultWorkerPool())

Changing the line above with the executor service from Arc solves the issue (Arc.container().getExecutorService()).

### Expected behavior

Infrastructure.getDefaultWorkerPool() should behave correctly if used in the TenantConfigResolver#resolve

### Actual behavior

The following exception is thrown:

```
2022-03-08 01:27:11,272 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /hello failed, error id: e502e653-f3c1-4ba3-8370-8a522104e306-1: java.lang.IllegalStateException: Can't set the context safety flag: the current context is not a duplicated context
	at io.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle.setContextSafe(VertxContextSafetyToggle.java:107)
	at io.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle.setCurrentContextSafe(VertxContextSafetyToggle.java:94)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.<init>(QuarkusResteasyReactiveRequestContext.java:33)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$4.createContext(ResteasyReactiveRecorder.java:111)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:46)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:126)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:274)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

1. Create TenantConfigResolver
2. Within resolve method, return
Uni.createFrom().item(() -> getTenantConfig()).runSubscriptionOn(Infrastructure.getDefaultWorkerPool())
3. Use Resteasy Reactive and expose an authenticated API
4. Run quarkus and Invoke the API
5. Observe the exception in the log upon sending a request

### Output of `uname -a` or `ver`

Darwin Mazens-MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)

### Quarkus version or git rev

2.7.3.Final

**Comment by cescoffier** [comment]
Hum, something does not come back on the right context. Definitely a bug.

**Comment by cescoffier** [comment]
I don't see how using Arc executor can make it work, as it's the same thread pool under the hood.

**Comment by cescoffier** [comment]
Could you provide a complete reproducer?

**Comment by cescoffier** [comment]
I pushed a workaround in https://github.com/quarkusio/quarkus/pull/24134.

However, I need to know why you are calling the tenant resolver on a worker thread. This breaks the assumption, would only work if you emit the result on the right context.

**Comment by mazenkhalil** [comment]
I am investigating locally, and here are my findings so far.

The actual issue happens in the SecurityIdentityAugmentor not the TenantConfigResolver as I mentioned earlier. I couldn't detect this because I am using @CacheResult in one of my internal methods.

So basically you can replicate this by returning `Uni.createFrom().item(() -> build()).runSubscriptionOn(Infrastructure.getDefaultWorkerPool())` from augment method. Without even having a tenant config resolver. Using Arc.container().getExecutorService() solves the issue.

My application biz. is quite complex, getting the tenant config involves the DB and there is one part in the code uses reflection for object initialization, then I am caching the response indefinitely. When using the cache i observe the exception above only on the first hit, the second request just pass because the response is already cached.

**Comment by cescoffier** [comment]
Fixed in https://github.com/quarkusio/quarkus/pull/24134.
