### ISSUE TITLE
Referencing Context APIGatewayV2HTTPEvent in RestEasy Method Throws Exeception

### ISSUE THREAD

**Issue by johnnorton** [quarkusio/quarkus#24181]
### Describe the bug

White using RestEasy-Reactive and Lambda HTTP.  Referencing @Context APIGatewayV2HTTPEvent throws IllegalStateException

**Method:**

```
 @GET
 @Produces(MediaType.TEXT_PLAIN)
  public String hello(@Context APIGatewayV2HTTPEvent event) 
 {
        return "Hello RESTEasy";
 }
```

**Exception Thrown:**

```
2022-03-07 23:02:59,967 DEBUG [org.jbo.res.rea.ser.han.ParameterHandler] (executor-thread-0) Error occurred during parameter extraction: java.lang.IllegalStateException: Unsupported contextual type: class com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent
	at org.jboss.resteasy.reactive.server.core.parameters.ContextParamExtractor.extractParameter(ContextParamExtractor.java:94)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:41)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:15)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This appears to only happen when using `RestEast-Reactive`

### Expected behavior

No exception is thrown and the `@Context APIGatewayV2HTTPEvent` parameter is available for reference.

### Actual behavior

Exception is Thrown

### How to Reproduce?

Maven Project Attached

### Output of `uname -a` or `ver`

Darwin LSLCmacK1NMJGH8 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 LTS OpenJDK Runtime Environment Corretto-11.0.12.7.2 (build 11.0.12+7-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.12.7.2 (build 11.0.12+7-LTS, mixed mode)

### Quarkus version or git rev

2.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /usr/local/Cellar/maven/3.8.1/libexec Java version: 11.0.12, vendor: Amazon.com Inc., runtime: /Users/jnorton9/.sdkman/candidates/java/11.0.12.7.2-amzn Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "12.2.1", arch: "x86_64", family: "mac"

**Comment by johnnorton** [comment]
Reproducer Attached

[reactive-error.zip](https://github.com/quarkusio/quarkus/files/8207415/reactive-error.zip)

**Comment by geoand** [comment]
Can you add a new reproducer in the comments here?

**Comment by johnnorton** [comment]
For some reason github would not let me upload.  Here is a link to the reproducer

https://file.io/FcNNMLpb5KJQ

**Comment by geoand** [comment]
This does work in Quarkus `2.8.0.CR1`, so perhaps the fix was not backported

**Comment by johnnorton** [comment]
I will wait for 2.8.0.  Thanks!
