### ISSUE TITLE
quarkus/jib: Native build fails if docker isn't installed

### ISSUE THREAD

**Issue by jesperpedersen** [quarkusio/quarkus#24231]
### Describe the bug

1) Download https://github.com/operator-framework/operator-sdk
2) mkdir test && cd test
3) operator-sdk init --plugins quarkus --domain halkyon.io --project-name expose
4) Change pom.xml
```
    <quarkus-sdk.version>3.0.4</quarkus-sdk.version>
    <quarkus.version>2.7.3.Final</quarkus.version>
```
5) `mvn clean package -Pnative`

Fails with

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.7.3.Final:build (default) on project expose: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromNative threw an exception: java.lang.RuntimeException: Unable to create container image
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:236)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromNative(JibProcessor.java:203)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:832)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Cannot run program "docker": error=2, No such file or directory
[ERROR] 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
[ERROR] 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
[ERROR] 	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.run(StepsRunner.java:219)
[ERROR] 	at com.google.cloud.tools.jib.api.Containerizer.run(Containerizer.java:390)
[ERROR] 	at com.google.cloud.tools.jib.api.JibContainerBuilder.containerize(JibContainerBuilder.java:598)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:229)
[ERROR] 	... 12 more
[ERROR] Caused by: java.io.IOException: Cannot run program "docker": error=2, No such file or directory
[ERROR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[ERROR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[ERROR] 	at com.google.cloud.tools.jib.docker.DockerClient.docker(DockerClient.java:277)
[ERROR] 	at com.google.cloud.tools.jib.docker.DockerClient.load(DockerClient.java:193)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.LoadDockerStep.call(LoadDockerStep.java:74)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$loadDocker$18(StepsRunner.java:618)
[ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
[ERROR] 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
[ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:832)
[ERROR] Caused by: java.io.IOException: error=2, No such file or directory
[ERROR] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[ERROR] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
[ERROR] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250)
[ERROR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[ERROR] 	... 11 more
```

since `docker` isn't installed. The build up to this point have used `podman` successfully.

### Expected behavior

To be able to use `podman` for the entire build

### Actual behavior

`docker` is required - e.g. `podman` isn't detected

### Output of `java -version`

JDK14

### Quarkus version or git rev

2.7.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

### Additional information

Workaround: Using

```
mvn clean package -Dquarkus.docker.executable-name=podman -Pnative
```

and the build is successful.

Code: extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java

**Comment by geoand** [comment]
What you are seeing is the expected behavior. 

> since docker isn't installed. The build up to this point have used podman successfully.

I assume you mean with this that building the native binary is done with podman without you having to configure anything?

**Comment by jesperpedersen** [comment]
@geoand Correct - like
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Using podman to run the native image builder
```

**Comment by jesperpedersen** [comment]
@metacosm FYI

**Comment by geoand** [comment]
Gotcha, thanks .

I'll take care of it to bring it in line with what we do for the native build

**Comment by jesperpedersen** [comment]
Thank you for your quick fix !

**Comment by gsmet** [comment]
@jesperpedersen 2.7.5.Final has been released.

**Comment by metacosm** [comment]
Already? Damn, I barely had time to release the extension with 2.7.4! 😁
