### ISSUE TITLE
Quartz extension store-type support customization

### ISSUE THREAD

**Issue by leotu** [quarkusio/quarkus#24279]
### Description

Quartz Configuration "quarkus.quartz.store-type" only support ram or jdbc, it should be allow user  to specify other type (i.e, Redis) by org.quartz.jobStore.class or provided jobStoreFactory

**Comment by machi1990** [comment]
It make sense to be able to use other job stores e.g redis, kafka etc but getting it to work in native might be trick. Do you have some implementations ideas that you can add to the issue description?

>  it should be allow user to specify other type (i.e, Redis) by org.quartz.jobStore.class or provided jobStoreFactory

I suppose you are referring to https://github.com/RedisLabs/redis-quartz, which I do not think will work out of the box in native mode without having an extension for linked external libraries: https://github.com/RedisLabs/redis-quartz#external-libraries.

**Comment by leotu** [comment]
> 
The project I am referring to is [https://github.com/jlinn/quartz-redis-jobstore](https://github.com/jlinn/quartz-redis-jobstore), native mode maybe the problem is  [redis.clients](https://github.com/jlinn/quartz-redis-jobstore/blob/master/pom.xml)  and  rewrite it using "quarkus redis client".

**Comment by machi1990** [comment]
> > 
> 
> The project I am referring to is https://github.com/jlinn/quartz-redis-jobstore, 

I see. The project is based/insipired on/by the one I linked above. 

> native mode maybe the problem is [redis.clients](https://github.com/jlinn/quartz-redis-jobstore/blob/master/pom.xml) and rewrite it using "quarkus redis client".

I do not think the team has some cycle doing this. I welcome contributions though and I'll be happy to review the work.

**Comment by leotu** [comment]
- The file [QuartzScheduler.java](https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java) method [getSchedulerConfigurationProperties](https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L418) is private access modifier, if it change to protected access and I could inherit my class from QuartzScheduler and override this method add my owned properties. (org.quartz.jobStore.class = xxx)

- I am not sure if [use CDI @Alternative + @Priority](https://quarkus.io/guides/writing-extensions#how-to-override-a-bean-defined-by-a-libraryquarkus-extension-that-doesnt-use-defaultbean) is correct way.


- My temporary workaround at the moment is to use  veto
```java
scheduler.getListenerManager().addTriggerListener(new TriggerListener() {
  ...
   @Override
    public boolean vetoJobExecution(Trigger trigger, JobExecutionContext context) {
          // connect to Redis check and return false/true
    }
...
}
```

**Comment by mkouba** [comment]
@leotu I don't think that you need to "override" the `QuartzScheduler` bean. Instead, we should allow users to specify a custom `io.quarkus.quartz.runtime.StoreType`, i.e. introduce `StoreType.CUSTOM` and `quarkus.quartz.custom-store-class` or something like that... @machi1990 WDYT?

**Comment by machi1990** [comment]
> @leotu I don't think that you need to "override" the `QuartzScheduler` bean. Instead, we should allow users to specify a custom `io.quarkus.quartz.runtime.StoreType`, i.e. introduce `StoreType.CUSTOM` and `quarkus.quartz.custom-store-class` or something like that... @machi1990 WDYT?

I was thinking something along the same line but native could get trick to get right. Do we just register the custom store class for reflection and leave the rest to the user to figure out?

**Comment by mkouba** [comment]
> Do we just register the custom store class for reflection and leave the rest to the user to figure out?

Yes, it would be the responsibility of the user. I think that we can't do much without a proper extension...

**Comment by machi1990** [comment]
> > Do we just register the custom store class for reflection and leave the rest to the user to figure out?
> 
> Yes, it would be the responsibility of the user. I think that we can't do much without a proper extension...

Make sense. @leotu is this something that could suffice your usecase? Or you still need a way to add additional properties? 
if so, those could be supplied as a `quarkus.quartz.custom-store-properties."<name>"=value` and they'll get appended to the quartz base properties in the method [getSchedulerConfigurationProperties](https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L418). 
If all make sense, would you like to give this a stab? Thanks

**Comment by leotu** [comment]
> > > Do we just register the custom store class for reflection and leave the rest to the user to figure out?
> > 
> > 
> > Yes, it would be the responsibility of the user. I think that we can't do much without a proper extension...
> 
> Make sense. @leotu is this something that could suffice your usecase? Or you still need a way to add additional properties? if so, those could be supplied as a `quarkus.quartz.custom-store-properties."<name>"=value` and they'll get appended to the quartz base properties in the method [getSchedulerConfigurationProperties](https://github.com/quarkusio/quarkus/blob/main/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java#L418). If all make sense, would you like to give this a stab? Thanks

Yes, "StoreType.CUSTOM and quarkus.quartz.custom-store-class/quarkus.quartz.custom-store-properties" it should be solve my problem, something like [Trigger/Job listeners](https://quarkus.io/guides/quartz#quarkus-quartz_quarkus.quartz.trigger-listeners-trigger-listeners)

**Comment by machi1990** [comment]
Perfect. Just a note though, and I have said it before: getting the custom store to work in native will be up to the user. 

Would you have some time to look into the issue and come up with the PR based on what is proposed? @leotu

**Comment by leotu** [comment]
> Perfect. Just a note though, and I have said it before: getting the custom store to work in native will be up to the user.
> 
> Would you have some time to look into the issue and come up with the PR based on what is proposed? @leotu

Try write some code but failed :-(
Are there any other alternatives? @machi1990 

```java
public class QuartzBuildTimeConfig {
    ...
    /**
     * Custom job store.
     */
    @ConfigItem(name = "custom-store")
    public Optional<QuartzExtensionPointConfig> customStore;
  ...
```

```yaml
quarkus:
   quartz:
       custom-store:
          class: xxx.CustomizedJobStore
          properties:
             name: ${quarkus.application.name}-store
```

```java
Caused by: java.lang.IllegalArgumentException: Can not set java.util.Map field io.quarkus.quartz.runtime.QuartzExtensionPointConfig.properties to java.util.Optional
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
	at java.base/java.lang.reflect.Field.get(Field.java:425)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getFieldAsMap(BuildTimeConfigurationReader.java:678)
```

Ref [#7862](https://github.com/quarkusio/quarkus/issues/7862)

**Comment by machi1990** [comment]
> > Perfect. Just a note though, and I have said it before: getting the custom store to work in native will be up to the user.
> > Would you have some time to look into the issue and come up with the PR based on what is proposed? @leotu
> 
> Try write some code but failed :-( Are there any other alternatives? @machi1990
> 
> ```java
> public class QuartzBuildTimeConfig {
>     ...
>     /**
>      * Custom job store.
>      */
>     @ConfigItem(name = "custom-store")
>     public Optional<QuartzExtensionPointConfig> customStore;
>   ...
> ```
> 
> ```yaml
> quarkus:
>    quartz:
>        custom-store:
>           class: xxx.CustomizedJobStore
>           properties:
>              name: ${quarkus.application.name}-store
> ```
> 
> ```java
> Caused by: java.lang.IllegalArgumentException: Can not set java.util.Map field io.quarkus.quartz.runtime.QuartzExtensionPointConfig.properties to java.util.Optional
> 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
> 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
> 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
> 	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
> 	at java.base/java.lang.reflect.Field.get(Field.java:425)
> 	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getFieldAsMap(BuildTimeConfigurationReader.java:678)
> ```
> 
> * [QuartzExtensionPointConfig.java](https://github.com/quarkusio/quarkus/blob/2cbd177416f92b9f45abb34b6f01acb8cb0f4eb5/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzExtensionPointConfig.java)
> * [#7862](https://github.com/quarkusio/quarkus/issues/7862)

Looks like a config error and I cannot see what's wrong with it from what you shared. Can you open a draft PR with what you current have and we could take the investigate from there?. 
/cc @radcortez @mkouba  does the error above ring a bell to you?

**Comment by radcortez** [comment]
Yes, if I remember correctly, we don't have support for `Optional` `ConfigGroup`. We recently added such support in Quarkus 2.8.x with SmallRye Config `@ConfigMapping`, which should not work with Extensions. My recommendation is to use that instead.

**Comment by leotu** [comment]
Draft PR #24636 @machi1990

Provide "Optional ConfigGroup" Described as below code snippet

```java

@ConfigRoot(phase = ConfigPhase.BUILD_AND_RUN_TIME_FIXED)
public class QuartzBuildTimeConfig {
...
    /**
     * Custom job store.
     */
    @ConfigItem
    @ConfigDocMapKey("custom-store")
    @ConfigDocSection
    protected QuartzExtensionPointOptionalConfig customStore;

    /**
     * Support for Optional ConfigGroup
     */
    public Optional<QuartzExtensionPointConfig> customStore() {
        return customStore.convertToOptional();
    }
...
```

```java
 @ConfigGroup
    static public class QuartzExtensionPointOptionalConfig {
        /**
         * Class name for the configuration.
         */
        @ConfigItem(name = "class")
        public Optional<String> clazz;

        /**
         * The properties passed to the class.
         */
        @ConfigItem
        @ConfigDocMapKey("property-name")
        public Map<String, String> properties;

        Optional<QuartzExtensionPointConfig> convertToOptional() {
            QuartzExtensionPointConfig config = null;
            if (clazz.isPresent()) {
                config = new QuartzExtensionPointConfig();
                config.clazz = clazz.get();
                config.properties = properties;
            }
            return Optional.ofNullable(config);
        }
    }
```

**Comment by mkouba** [comment]
Ping @leotu. What's the status of this issue? I can see that you closed the draft PR last year.
