### ISSUE TITLE
Getting io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype in dev mode really intermitently

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#24276]
### Describe the bug

This one is really hard to reproduce, it seems to happen randomly, and so far I have been able to observe it only in dev mode. I will not be able to put a reproducer in place as I am really not able to reproduce at will.

Here's the stacktrace;

```
2022-03-10 22:11:00,269 ERROR [org.qua.cor.ErrorLogger] (QuarkusQuartzScheduler_Worker-8) Job (io.quarkus.scheduler.Scheduler.scheduler-poller-job threw an exception.: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype]
at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:100)
at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:64)
at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
at io.quarkus.arc.runtime.ConfigMappingCreator.create(ConfigMappingCreator.java:27)
at org.acme.Config_89c98782817d888e3bd4372ecd7ed122bdb30c72_Synthetic_Bean.create(Unknown Source)
at org.acme.Config_89c98782817d888e3bd4372ecd7ed122bdb30c72_Synthetic_Bean.get(Unknown Source)
at org.acme.Config_89c98782817d888e3bd4372ecd7ed122bdb30c72_Synthetic_Bean.get(Unknown Source)
at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:428)
at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:441)
at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:412)
at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:229)
at org.acme.event.Event.isValid(Event.java:169)
```

Please note;
1. Event is coming as a List<Event> from a rest client reactive jackson
2. first line of the stackStrace, the isValid, contains this; `Config config = Arc.container().instance(Config.class).get();`
2.1 **Could this be an issue running that in a parallelStream?** if yes, what could be my alternative?
4. isValid is called from a list.parallelStream().forEach() Where all items are unique
5. the parallelStream() is called within a quartz `@Scheduled` method

is seems consistent with @fstarred comments https://github.com/quarkusio/quarkus/issues/9273#issuecomment-1059336625 and https://github.com/quarkusio/quarkus/issues/8210#issuecomment-1059222354 but in his case it seems to say that the dev mode is fine, which is not my case.

I wonder if this can happen with the jar or native. As it is really hard to repro, I cannot say if **only** devmode is affected, but so far it is the only place I could see it.

### Expected behavior

No Exceptions are thrown and processing goes through

### Actual behavior

Exception happens (somewhat rarely)

### How to Reproduce?

I cannot reproduce easily and consistently, even with my main app. I tried making a reproducer making the same steps in the descriptions but could not make it fail.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1526]

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)

### Quarkus version or git rev

2.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.4

**Comment by manofthepeace** [comment]
This issue worries me a bit. Would be nice to know at least if `Arc.container().instance(Config.class).get();` is thread safe or what could cause the exception. I have it in dev mode but I would like to know if the same can happen to prod, which would be really worrisome.

I have a bit more info of when it happens in the hope it can help.

Here's the threading sequence running parallelStream with a stream of 3 items;

QuarkusQuartzScheduler_Worker-16 --> runs OK
ForkJoinPool.commonPool-worker-1 -->  runs OK
QuarkusQuartzScheduler_Worker-16  --> Exception

as said in the original post, it's not that common, but it happens.

**Comment by manofthepeace** [comment]
I thought I did a mistake by using Arc to get a config mapping. So I have changed this;
`MyConfig config = Arc.container().instance(MyConfig.class).get();`
to
`MyConfig config = ConfigProvider.getConfig().unwrap(SmallRyeConfig.class).getConfigMapping(MyConfig.class);`

I still get an exception albeit a little different.

Help would be appreciated. Thanks

```
2022-03-31 20:35:13,271 ERROR [org.qua.cor.ErrorLogger] (QuarkusQuartzScheduler_Worker-23) Job (io.quarkus.scheduler.Scheduler.scheduler-poller-job threw an exception.: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype]
at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:100)
at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:64)
at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
at org.acme.event.Event.setEndTime(Event.java:122)
at org.acme.scheduler.Scheduler.updateDeactivateJobForEventInProgress(Scheduler.java:420)
at org.acme.scheduler.Scheduler.handleEventInProgress(Scheduler.java:191)
at org.acme.scheduler.Scheduler.createScheduledTask(Scheduler.java:125)
at org.acme.scheduler.Scheduler_Subclass.createScheduledTask$$superforward1(Unknown Source)
at org.acme.scheduler.Scheduler_Subclass$$function$$5.apply(Unknown Source)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
at org.acme.scheduler.Scheduler_Subclass.createScheduledTask(Unknown Source)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
