### ISSUE TITLE
Reactive REST Client NullPointerException

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#24364]
### Describe the bug

There seems to be a case where the header map in the ClientResponseContext is null. 

```
java.lang.NullPointerException
at org.jboss.resteasy.reactive.common.jaxrs.AbstractResponseBuilder.setAllHeaders(AbstractResponseBuilder.java:132)
at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.mapToResponse(ClientResponseCompleteRestHandler.java:39)
at io.quarkus.rest.client.reactive.runtime.MicroProfileRestClientResponseFilter.filter(MicroProfileRestClientResponseFilter.java:35)
at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:20)
at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:9)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:272)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:833)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```

### GraalVM version (if different from Java)

22.0

### Quarkus version or git rev

2.7.4.Final/2.7.5.Final

**Comment by geoand** [comment]
Can you please provide a sample project that exhibits this behavior?

**Comment by andlinger** [comment]
I do not know myself yet how the error comes about and therefore do not know how to build a reproducer. My hope was that we can look at the problem together here.

**Comment by andlinger** [comment]
Is there a way to log all requests and responses?

**Comment by geoand** [comment]
See https://quarkus.io/guides/rest-client-reactive#logging-traffic

**Comment by andlinger** [comment]
Thank you. Looks like the error happens before the request/response is logged because nothing is output. But with another (working) request everything is logged.

**Comment by geoand** [comment]
Understood. I think we'll still need a reproducer though... Without it, we're basically shooting in the dark

**Comment by andlinger** [comment]
Did it: https://github.com/andlinger/quarkus-reproducer/tree/quarkus-24364
Please note that `io.i15s.quarkus.HttpClient/mp-rest/url` in `application.properties` points to a port that is not open.
