### ISSUE TITLE
smallrye-config update from 1.3.5 to 1.3.6 or 1.3.7 introduces failures

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2437]
smallrye-config update from 1.3.5 to 1.3.6 or 1.3.7 introduces failures

1.3.6 reports Failures: 3, Errors: 4, details below.

Few hours old 1.3.7 resolves many of the fails, one still remains.
https://github.com/smallrye/smallrye-config/compare/1.3.6...1.3.7
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.012 s <<< FAILURE! - in io.quarkus.creator.config.test.SmallryeTestCase
[ERROR] testMain(io.quarkus.creator.config.test.SmallryeTestCase)  Time elapsed: 0.012 s  <<< ERROR!
java.util.NoSuchElementException: Property sun.cpu.isalist not found
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:98)
	at io.quarkus.creator.config.test.SmallryeTestCase.lambda$testMain$17(SmallryeTestCase.java:126)
```

@dmlloyd can you look into it as you did fixes in smallrye-config 1.3.7 ?

1.3.6 details:
```
[ERROR] Failures:
[ERROR]   ConfiguredBeanTest.validateRuntimeConfig:136 expected: <12345678911> but was: <0>
[ERROR]   ConfiguredBeanTest.validateRuntimeConfigMap:196 expected: <[value1, value2, value3]> but was: <[]>
[ERROR]   ConsoleHandlerTest.consoleOutputTest:40
Expecting:
 <INFO>
to be equal to:
 <ALL>
but was not.
[ERROR] Errors:
[ERROR]   FileHandlerTest.fileOutputTest:38 » NoSuchElement No value present
[ERROR]   PeriodicRotatingLoggingTest.periodicRotatingConfigurationTest:39 » NoSuchElement
[ERROR]   PeriodicSizeRotatingLoggingTest.periodicSizeRotatingConfigurationTest:39 » NoSuchElement
[ERROR]   SizeRotatingLoggingTest.sizeRotatingConfigurationTest:39 » NoSuchElement No va...
[INFO]
[ERROR] Tests run: 11, Failures: 3, Errors: 4, Skipped: 1
```

**Comment by dmlloyd** [comment]
Don't update it. The update has to be coordinated with other changes.

**Comment by rsvoboda** [comment]
ok, closing the issue (assuming you are handling that multi-changes effort).
