### ISSUE TITLE
Stork quickstart failing in native build

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#24397]
Yesterday's quickstarts native build failed with the error below. I think it's worth investigating.

```
2022-03-18 03:48:21,669 INFO  [io.quarkus] (main) Installed features: [cdi, rest-client-reactive, resteasy-reactive, smallrye-context-propagation, vertx]
Error:  WARNING: An illegal reflective access operation has occurred
Error:  WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/home/runner/.m2/repository/org/codehaus/groovy/groovy/3.0.9/groovy-3.0.9.jar) to constructor java.lang.AssertionError(java.lang.String)
Error:  WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
Error:  WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Error:  WARNING: All illegal access operations will be denied in a future release
2022-03-18 03:48:23,242 ERROR [org.jbo.res.rea.cli.han.ClientSendRequestHandler] (executor-thread-0) Error selecting service instance for serviceName: my-service: java.lang.IllegalArgumentException: No service defined for name my-service
	at io.smallrye.stork.Stork.getService(Stork.java:45)
	at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler.createRequest(ClientSendRequestHandler.java:303)
	at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler.handle(ClientSendRequestHandler.java:78)
	at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler.handle(ClientSendRequestHandler.java:55)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.performRequestInternal(AsyncInvokerImpl.java:262)
	at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.performRequestInternal(AsyncInvokerImpl.java:252)
	at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.method(AsyncInvokerImpl.java:192)
	at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:321)
	at org.acme.MyService$$QuarkusRestClientInterface.get(Unknown Source)
	at org.acme.MyService$$CDIWrapper.get(Unknown Source)
	at org.acme.MyService$$CDIWrapper_ClientProxy.get(Unknown Source)
	at org.acme.FrontendApi.invoke(FrontendApi.java:21)
	at org.acme.FrontendApi$quarkusrestinvoker$invoke_854181100c59fbf0dfc63335cc6a6b4ab7537d77.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 14.492 s <<< FAILURE! - in org.acme.FrontendApiTest
Error:  org.acme.FrontendApiTest.test  Time elapsed: 1.807 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.

	at org.acme.FrontendApiTest.test(FrontendApiTest.java:20)
```

See https://github.com/quarkusio/quarkus-quickstarts/runs/5594963820?check_suite_focus=true

**Comment by michalszynkiewicz** [comment]
thanks @gsmet !

**Comment by aureamunoz** [comment]
yep, I need to push the PR with changes....soon!

**Comment by michalszynkiewicz** [comment]
this should be fixed now
