### ISSUE TITLE
Picocli with @QuarkusMain fails when producer methods need CommandLine.ParseResult

### ISSUE THREAD

**Issue by bpasson** [quarkusio/quarkus#24401]
### Describe the bug

When using the `CommandLine.ParseResult` in producer methods when creating a PicoCLI command mode application with my own `@QuarkusMain` as described here https://quarkus.io/guides/picocli#providing-own-quarkusmain an exception is thrown, see actual behaviour.

### Expected behavior

The application to run and have the `CommandLine.ParseResult` injected in the producer method.

### Actual behavior

The following exception with stacktrace is generated.

```
2022-03-18 11:18:44,727 INFO  [io.quarkus] (main) cli-bug 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.7.5.Final) started in 0.284s. 
2022-03-18 11:18:44,744 INFO  [io.quarkus] (main) Profile prod activated. 
2022-03-18 11:18:44,744 INFO  [io.quarkus] (main) Installed features: [cdi, picocli]
2022-03-18 11:18:44,758 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [class java.lang.Object] and qualifiers [[@io.quarkus.picocli.runtime.annotations.TopCommand()]]
	at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:188)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:209)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:95)
	at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory.create(DefaultPicocliCommandLineFactory.java:43)
	at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory_ClientProxy.create(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer.picocliCommandLine(PicocliCommandLineProducer.java:23)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.create(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliParseResult_2edbe2da5547038011d72e6c55dbce57d0b8cd8b_Bean.create(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliParseResult_2edbe2da5547038011d72e6c55dbce57d0b8cd8b_Bean.get(Unknown Source)
	at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliParseResult_2edbe2da5547038011d72e6c55dbce57d0b8cd8b_Bean.get(Unknown Source)
	at org.example.Main_BeanProvider_ProducerMethod_values_ab0d82e89cd445fb160ca4c746543914189d8e56_Bean.create(Unknown Source)
	at org.example.Main_BeanProvider_ProducerMethod_values_ab0d82e89cd445fb160ca4c746543914189d8e56_Bean.get(Unknown Source)
	at org.example.Main_BeanProvider_ProducerMethod_values_ab0d82e89cd445fb160ca4c746543914189d8e56_Bean.get(Unknown Source)
	at org.example.Main_Bean.create(Unknown Source)
	at org.example.Main_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:18)
	at org.example.Main_ClientProxy.arc$delegate(Unknown Source)
	at org.example.Main_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
```

### How to Reproduce?

The following code will produce the issue.

```java
mport io.quarkus.runtime.QuarkusApplication;
import io.quarkus.runtime.annotations.QuarkusMain;
import picocli.CommandLine;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;
import javax.inject.Inject;
import java.util.Collections;
import java.util.Map;

@QuarkusMain
@CommandLine.Command(mixinStandardHelpOptions = true, subcommands = {Main.Sub.class})
public class Main implements QuarkusApplication {

    @Inject
    CommandLine.IFactory factory;

    @Inject
    Map<String,String> values;

    @Override
    public int run(String... args) throws Exception {
        return new CommandLine(this, factory)
                .execute(args);
    }

    @CommandLine.Command(name = "sub")
    public static class Sub implements Runnable {
        @Override
        public void run() {
        }
    }

    @ApplicationScoped
    public static class BeanProvider {

        @Produces
        public Map<String,String> values(CommandLine.ParseResult pr) {
            return Collections.emptyMap();
        }
    }
}
```

When you run the application this the exception will occur. If you run the same with the bean provider values method without the `CommandLine.ParseResult` parameter it will run fine.

### Output of `uname -a` or `ver`

Darwin beast.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05) OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)

### Quarkus version or git rev

Quarkus 2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

pache Maven 3.8.4

### Additional information

-

**Comment by doublefx** [comment]
I have the same issue in **native** without any direct reference to `CommandLine.ParseResult`

```
@QuarkusMain
public class ApplicationRunner {

	public static void main(String... args) {
		Quarkus.run(CsvInputConsole.class, args);
	}
}
```

```
@CommandLine.Command(name = "CSV Payment Service", mixinStandardHelpOptions = true)
public class CsvInputConsole implements Runnable, QuarkusApplication {
	private static final String DEFAULT_CSV        = "/sample-input.csv";
	private static final String CSV_FILE_NOT_FOUND = "CSV file not found: %s";

	@CommandLine.Option(names = {"-p", "--path"},
	                    description = "The Csv file to process, do not fill this argument to use the provided one.",
	                    defaultValue = DEFAULT_CSV)
	private String csvFilePath;

	@Inject
	CommandLine.IFactory factory;

	@Inject
	CsvProcessor csvProcessor;

	@SneakyThrows
	@Override
	public void run() {
		val csvFile = getAbsolutePath(csvFilePath);

		csvProcessor.process(csvFile);
	}

	@Override
	public int run(String... args) {
		val exit = new CommandLine(this, factory).execute(args);
		Quarkus.waitForExit();

		return exit;
	}

	private static String getAbsolutePath(String csvInputFile) throws FileNotFoundException {
		val filePath = Objects.equals(csvInputFile, DEFAULT_CSV)
		               ? Path.of("").toAbsolutePath() + DEFAULT_CSV
		               : csvInputFile;

		val decodedPath = URLDecoder.decode(filePath, UTF_8);
		val file        = new File(decodedPath);


		if (!file.exists()) {
			throw new FileNotFoundException(CSV_FILE_NOT_FOUND.formatted(decodedPath));
		}

		return file.getAbsolutePath();
	}
}
```

```
INFO  [io.quarkus] (main) payment-service 1.0-SNAPSHOT native (powered by Quarkus 2.13.3.Final) started in 0.055s. Listening on: http://0.0.0.0:8080
INFO  [io.quarkus] (main) Profile prod activated. 
INFO  [io.quarkus] (main) Installed features: [cache, cdi, config-yaml, picocli, rest-client-reactive, rest-client-reactive-jackson, resteasy-reactive, resteasy-reactive-jackson, scheduler, smallrye-context-propagation, smallrye-metrics, smallrye-openapi, vertx]
ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [class java.lang.Object] and qualifiers [[@io.quarkus.picocli.runtime.annotations.TopCommand()]]
	io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:190)
	io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:211)
	io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:97)
	io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory.create(DefaultPicocliCommandLineFactory.java:43)
	io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory_ClientProxy.create(Unknown Source)
	io.quarkus.picocli.runtime.PicocliCommandLineProducer.picocliCommandLine(PicocliCommandLineProducer.java:23)
	io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.create(Unknown Source)
	io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(Unknown Source)
	io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(Unknown Source)
	io.quarkus.picocli.runtime.PicocliRunner_Bean.create(Unknown Source)
	io.quarkus.picocli.runtime.PicocliRunner_Bean.get(Unknown Source)
	io.quarkus.picocli.runtime.PicocliRunner_Bean.get(Unknown Source)
	io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:471)
	io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:484)
	io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:61)
	io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:127)
	io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

**Comment by ebullient** [comment]
This is pretty old, and we may have fixed that a different way in the interim, but.. 

Does adding this qualifier (per the stated message) correct it? `@io.quarkus.picocli.runtime.annotations.TopCommand()` ?

**Comment by bpasson** [comment]
I will retest with te most recent quarkus version.
