### ISSUE TITLE
Failed to build native image with hibernate-orm-panache-kotlin

### ISSUE THREAD

**Issue by awelless** [quarkusio/quarkus#24423]
### Describe the bug

Error occurres during native build. 
```
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.kotlin.runtime.KotlinJpaOperations.getEntityManager(java.lang.Class, kotlin.reflect.KClass). 
```

### Expected behavior

Native image should be built without any issues

### Actual behavior

Native image build fails:
```
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.kotlin.runtime.KotlinJpaOperations.getEntityManager(java.lang.Class, kotlin.reflect.KClass). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
------------------------------------------------------------------------------------------------------------------------
Trace: 
        at parsing it.mail.repository.MailMessageRepository.getEntityManager(MailMessageRepository.kt)
                        7.0s (8.6% of total time) in 35 GCs | Peak RSS: 4.23GB | CPU load: 6.26
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/some_user/mail-it/build/mail-it-0.0.1-SNAPSHOT-native-image-source-jar/mail-it-0.0.1-SNAPSHOT-runner.build_artifacts.txt
========================================================================================================================
Failed generating 'mail-it-0.0.1-SNAPSHOT-runner' after 1m 20s.
Call path from entry point to it.mail.repository.MailMessageRepository.getEntityManager(KClass): 
        at it.mail.repository.MailMessageRepository.getEntityManager(MailMessageRepository.kt)
        at it.mail.repository.MailMessageRepository_Subclass.getEntityManager$$superforward1(Unknown Source)
        at it.mail.repository.MailMessageRepository_Subclass$$function$$36.apply(Unknown Source)
        at platform/jdk.crypto.ec@11.0.14/sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:318)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.kotlin.runtime.KotlinJpaOperations.getEntityManager(java.lang.Class, kotlin.reflect.KClass). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
        at parsing it.mail.repository.MailMessageTypeRepository.getEntityManager(MailMessageTypeRepository.kt)
Call path from entry point to it.mail.repository.MailMessageTypeRepository.getEntityManager(KClass): 
        at it.mail.repository.MailMessageTypeRepository.getEntityManager(MailMessageTypeRepository.kt)
        at it.mail.repository.MailMessageTypeRepository_Subclass.getEntityManager$$superforward1(Unknown Source)
        at it.mail.repository.MailMessageTypeRepository_Subclass$$function$$36.apply(Unknown Source)
        at platform/jdk.crypto.ec@11.0.14/sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:318)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.kotlin.runtime.KotlinJpaOperations.getEntityManager(java.lang.Class, kotlin.reflect.KClass). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
        at parsing it.mail.repository.MailMessageRepository.getEntityManager(MailMessageRepository.kt)
Call path from entry point to it.mail.repository.MailMessageRepository.getEntityManager(KClass): 
        at it.mail.repository.MailMessageRepository.getEntityManager(MailMessageRepository.kt)
        at it.mail.repository.MailMessageRepository_Subclass.getEntityManager$$superforward1(Unknown Source)
        at it.mail.repository.MailMessageRepository_Subclass$$function$$36.apply(Unknown Source)
        at platform/jdk.crypto.ec@11.0.14/sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:318)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.kotlin.runtime.KotlinJpaOperations.getEntityManager(java.lang.Class, kotlin.reflect.KClass). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
        at parsing it.mail.repository.MailMessageTypeRepository.getEntityManager(MailMessageTypeRepository.kt)
Call path from entry point to it.mail.repository.MailMessageTypeRepository.getEntityManager(KClass): 
        at it.mail.repository.MailMessageTypeRepository.getEntityManager(MailMessageTypeRepository.kt)
        at it.mail.repository.MailMessageTypeRepository_Subclass.getEntityManager$$superforward1(Unknown Source)
        at it.mail.repository.MailMessageTypeRepository_Subclass$$function$$36.apply(Unknown Source)
        at platform/jdk.crypto.ec@11.0.14/sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:318)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:87)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:731)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:537)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:494)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:426)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:587)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:126)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:617)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.kotlin.runtime.KotlinJpaOperations.getEntityManager(java.lang.Class, kotlin.reflect.KClass). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
        at parsing it.mail.repository.MailMessageRepository.getEntityManager(MailMessageRepository.kt)
Call path from entry point to it.mail.repository.MailMessageRepository.getEntityManager(KClass): 
        at it.mail.repository.MailMessageRepository.getEntityManager(MailMessageRepository.kt)
        at it.mail.repository.MailMessageRepository_Subclass.getEntityManager$$superforward1(Unknown Source)
        at it.mail.repository.MailMessageRepository_Subclass$$function$$36.apply(Unknown Source)
        at platform/jdk.crypto.ec@11.0.14/sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:318)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.kotlin.runtime.KotlinJpaOperations.getEntityManager(java.lang.Class, kotlin.reflect.KClass). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
        at parsing it.mail.repository.MailMessageTypeRepository.getEntityManager(MailMessageTypeRepository.kt)
Call path from entry point to it.mail.repository.MailMessageTypeRepository.getEntityManager(KClass): 
        at it.mail.repository.MailMessageTypeRepository.getEntityManager(MailMessageTypeRepository.kt)
        at it.mail.repository.MailMessageTypeRepository_Subclass.getEntityManager$$superforward1(Unknown Source)
        at it.mail.repository.MailMessageTypeRepository_Subclass$$function$$36.apply(Unknown Source)
        at platform/jdk.crypto.ec@11.0.14/sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:318)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:728)
        ... 6 more
Error: Image build request failed with exit status 1

```

### How to Reproduce?

```
git clone https://github.com/Awelless/mail-it.git
cd mail-it
git checkout 9123da9c1bfe15fe1cde2d17909389340600197b
./gradlew build -Dquarkus.package.type=native
``` 

### Output of `uname -a` or `ver`

Linux 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 GNU/Linux

### Output of `java -version`

openjdk 11.0.14

### GraalVM version (if different from Java)

22.0.0.2.r11-madrel

### Kotlin version

1.6.10

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

**Comment by Sanne** [comment]
This looks like Kotlin specific. Could you have a look @evanchooly ?

**Comment by evanchooly** [comment]
Can do

**Comment by Viacheslav-Petriaiev** [comment]
Hi @evanchooly 

I have the same error with 2.10.2.Final version

**Comment by ederfmatos-exacta** [comment]
Any update on this item?

**Comment by geoand** [comment]
Is this still an issue with the latest Quarkus version?

**Comment by awelless** [comment]
@geoand 
The issue doesn't emerge during a build with quarkus 2.16.2.Final. So, I'd assume it's fixed

**Comment by geoand** [comment]
Thanks for checking
