### ISSUE TITLE
SmallRyeHealthReporter java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#24523]
### Describe the bug

When booting up using 2.8.0.CR1, we get exceptions in the logs:

```posh
09:05:48,601: [vert.x-eventloop-thread-1]{}HTTP Request to /health/ready failed, error id: 31368e61-5b06-447c-8f78-76fa91c6d004-2: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at io.smallrye.health.SmallRyeHealthReporter.isEnabled(SmallRyeHealthReporter.java:550)
	at io.smallrye.health.SmallRyeHealthReporter.isHealthCheckEnabled(SmallRyeHealthReporter.java:540)
	at io.smallrye.health.SmallRyeHealthReporter.initUnis(SmallRyeHealthReporter.java:188)
	at io.smallrye.health.SmallRyeHealthReporter.initChecks(SmallRyeHealthReporter.java:177)
	at io.smallrye.health.SmallRyeHealthReporter.getHealthAsync(SmallRyeHealthReporter.java:373)
	at io.smallrye.health.SmallRyeHealthReporter.getReadinessAsync(SmallRyeHealthReporter.java:259)
	at io.smallrye.health.SmallRyeHealthReporter.getReadiness(SmallRyeHealthReporter.java:225)
	at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getReadiness(Unknown Source)
	at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.getHealth(SmallRyeReadinessHandler.java:11)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.doHandle(SmallRyeHealthHandlerBase.java:44)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:31)
	at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.handle(SmallRyeReadinessHandler.java:7)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:19)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

This does not happen in 2.7.X

### Expected behavior

Should not get exceptions

### Actual behavior

Get exceptions. Does not impact the system but logs are ugly

### How to Reproduce?

Do health checks to health/ready on a server as it is booting

### Output of `uname -a` or `ver`

Linux paul-xps 5.13.0-37-generic #42-Ubuntu SMP Tue Mar 15 14:34:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)

### Quarkus version or git rev

2.8.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by geoand** [comment]
Ouch... https://github.com/smallrye/smallrye-health/pull/393 should fix it.

@xstefank @radcortez  we will likely need that fix and a new release ASAP

**Comment by bcluap** [comment]
Yip I can confirm that smallrye health 3.2.1 fixes the issue. Thanks guys!
