### ISSUE TITLE
quarkusGenerateCode fails because of out of memory Java heap space

### ISSUE THREAD

**Issue by iompo** [quarkusio/quarkus#24537]
### Describe the bug

Code compilation fails for any 2.7.x version with a Java heap space error, while was working fine with 2.6.x. The error message is:
```
> Task :quarkusGenerateCode
preparing quarkus application

Problem in daemon expiration check
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.net.InetAddress.getByAddress(InetAddress.java:1201)
        at java.base/java.net.InetAddress.getByAddress(InetAddress.java:1575)
        at org.gradle.internal.remote.internal.inet.MultiChoiceAddressSerializer.read(MultiChoiceAddressSerializer.java:37)
        at org.gradle.launcher.daemon.registry.DaemonRegistryContent$Serializer.readAddresses(DaemonRegistryContent.java:208)
        at org.gradle.launcher.daemon.registry.DaemonRegistryContent$Serializer.read(DaemonRegistryContent.java:118)
        at org.gradle.launcher.daemon.registry.DaemonRegistryContent$Serializer.read(DaemonRegistryContent.java:113)
        at org.gradle.cache.internal.SimpleStateCache.deserialize(SimpleStateCache.java:144)
        at org.gradle.cache.internal.SimpleStateCache.access$000(SimpleStateCache.java:34)
        at org.gradle.cache.internal.SimpleStateCache$1.create(SimpleStateCache.java:52)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.readFile(DefaultFileLockManager.java:194)
        at org.gradle.cache.internal.OnDemandFileAccess.readFile(OnDemandFileAccess.java:43)
        at org.gradle.cache.internal.SimpleStateCache.get(SimpleStateCache.java:49)
        at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.get(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:34)
        at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.getAll(PersistentDaemonRegistry.java:71)
        at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.getDaemonsMatching(PersistentDaemonRegistry.java:116)
        at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.getIdle(PersistentDaemonRegistry.java:84)
        at org.gradle.launcher.daemon.server.CompatibleDaemonExpirationStrategy.checkExpiration(CompatibleDaemonExpirationStrategy.java:54)
        at org.gradle.launcher.daemon.server.expiry.AllDaemonExpirationStrategy.checkExpiration(AllDaemonExpirationStrategy.java:46)
        at org.gradle.launcher.daemon.server.expiry.AnyDaemonExpirationStrategy.checkExpiration(AnyDaemonExpirationStrategy.java:43)
        at org.gradle.launcher.daemon.server.MasterExpirationStrategy.checkExpiration(MasterExpirationStrategy.java:73)
        at org.gradle.launcher.daemon.server.Daemon$DaemonExpirationPeriodicCheck.run(Daemon.java:268)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
        at java.base/java.lang.Thread.run(Unknown Source)
Expiring Daemon because JVM heap space is exhausted
Daemon will be stopped at the end of the build after running out of JVM memory
```

There is a massive increase in memory used  at compile time. 
Quarkus 2.6.1 was:
<img width="1210" alt="quarkus-compile-2 6 x" src="https://user-images.githubusercontent.com/64641556/159945068-76a63d89-1311-4e6f-9098-2d2e943662b7.png">

While with quarkus 2.7.5 (or any other 2.7.x) is:
<img width="1222" alt="quarkus-compile-2 7 x" src="https://user-images.githubusercontent.com/64641556/159945294-6e5c9b9f-bf1a-4948-809f-a4756617f562.png">

### Expected behavior

code compilation should complete without errors

### Actual behavior

code compilation fails because of a memory error

### How to Reproduce?

I did try with an example project, but the amount of memory necessary for it is too small and the problem does not arise.

### Output of `java -version`

11.0.13 (Eclipse Adoptium 11.0.13+8)

### Quarkus version or git rev

2.7.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.1

**Comment by damonsutherland** [comment]
I am experiencing this as well.  Thanks @iompo for the work in detailing this defect.  Rolling back to 2.6.3.Final resolved my current issues.

**Comment by gsmet** [comment]
It would probably help if you could get a heap dump when memory usage is high.

**Comment by iompo** [comment]
[Here](https://drive.google.com/file/d/1vdC7WGMly0ywODf2Ocjw6wXOJynLl9Al/view?usp=sharing) a link to the dump file (made with VisualVM)

**Comment by iompo** [comment]
hi @gsmet, is there anything else I can do that might help solve the issue?

**Comment by iompo** [comment]
I think I found the problem. I had a dependency with a "./" entry in it. Since java 11.0.14 that is a [problem](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.zipfs/module-summary.html) if you need to open that compressed file. 
As mentioned I was using java 11.0.13, so it looks like quarkus is somehow affected by this issue, regardless the java version used to compile. It also looks like the compile process goes into an infinite loop that saturates the available memory instead of failing

**Comment by yrodiere** [comment]
Hey @iompo . Did you manage to work around this in the end? Can you confirm the problem goes away if you downgrade to Java 11.0.13? Thanks.

**Comment by iompo** [comment]
Hi @yrodiere, yes it works with java 11.0.13. We recompiled that jar removing the "./" entry, so we could keep our java version updated.
