### ISSUE TITLE
Native Container Build failed on symbolic linked folder

### ISSUE THREAD

**Issue by stefanwendelmann** [quarkusio/quarkus#24601]
### Describe the bug

Building a native executable with the maven flag `-Dquarkus.native.container-build=true` leads to an error when running on a symbolic linked folder.

When switching to the original path, it works.

### Expected behavior

Works with symbolic linked folder

### Actual behavior

```log
C:\Users\myUser\prj\code-with-me > .\mvnw package -Pnative "-Dquarkus.native.container-build=true"
[INFO] Scanning for projects...
[INFO]
[INFO] ------< org.test:code-with-me >------
[INFO] Building code-with-me 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ code-with-me ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- quarkus-maven-plugin:2.7.5.Final:generate-code (default) @ code-with-me ---
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ code-with-me ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- quarkus-maven-plugin:2.7.5.Final:generate-code-tests (default) @ code-with-me ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ code-with-me ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\myUser\prj\code-with-me\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ code-with-me ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ code-with-me ---
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ code-with-me ---
[WARNING] [io.quarkus.deployment.steps.NativeImageAllowIncompleteClasspathAggregateStep] The following extensions have required the '--allow-incomplete-classpath' flag to be set: {quarkus-jdbc-oracle}. This is a global flag which might have unexpected effects on other extensions as well, and is a hint of the library needing some additional refactoring to better support GraalVM native-image. In the case of 3rd party dependencies and/or proprietary code there is not much we can do - please ask for support to your library vendor. If you incur in any problem with other Quarkus extensions, please try reproducing the problem without these extensions first.
[INFO] [org.hibernate.Version] HHH000412: Hibernate ORM core version 5.6.5.Final
[INFO] [io.quarkus.arc.processor.BeanProcessor] Found unrecommended usage of private members (use package-private instead) in application beans:
        - @PostConstruct callback org.test.service.KeycloakAdminService#post()
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Uber JAR strategy is used for native image source JAR generation on Windows. This is done for the time being to work around a current GraalVM limitation on Windows concerning the maximum command length (see https://github.com/oracle/graal/issues/2387).
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building uber jar: C:\Users\myUser\prj\code-with-me\target\code-with-me-0.0.1-SNAPSHOT-native-image-source-jar\code-with-me-0.0.1-SNAPSHOT-runner.jar
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [com.sun.activation:jakarta.activation::jar:1.2.1[paths: C:\Users\myUser\.m2\repository\com\sun\activation\jakarta.activation\1.2.1\jakarta.activation-1.2.1.jar;], jakarta.activation:jakarta.activation-api::jar:1.2.1[paths: C:\Users\myUser\.m2\repository\jakarta\activation\jakarta.activation-api\1.2.1\jakarta.activation-api-1.2.1.jar;]] contain duplicate files, e.g. javax/activation/ActivationDataFlavor.class
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [jakarta.el:jakarta.el-api::jar:3.0.3[paths: C:\Users\myUser\.m2\repository\jakarta\el\jakarta.el-api\3.0.3\jakarta.el-api-3.0.3.jar;], org.glassfish:jakarta.el::jar:3.0.4[paths: C:\Users\myUser\.m2\repository\org\glassfish\jakarta.el\3.0.4\jakarta.el-3.0.4.jar;]] contain duplicate files, e.g. javax/el/BeanELResolver$BPSoftReference.class
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from C:\Users\myUser\prj\code-with-me\target\code-with-me-0.0.1-SNAPSHOT-native-image-source-jar\code-with-me-0.0.1-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Using docker to run the native image builder
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Checking image status quay.io/quarkus/ubi-quarkus-native-image:21.3-java11
21.3-java11: Pulling from quarkus/ubi-quarkus-native-image
510abfcdf6bc: Already exists
4a3604715398: Already exists
fe07ef1d5955: Pull complete
Digest: sha256:a32df896076e2748f32144afae7ab370ca19156af92329e0b4da6a1fae0540e7
Status: Downloaded newer image for quay.io/quarkus/ubi-quarkus-native-image:21.3-java11
quay.io/quarkus/ubi-quarkus-native-image:21.3-java11
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM 21.3.1 Java 11 CE (Java Version 11.0.14+9-jvmci-21.3-b09)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm -v //c/Users/myUser/prj/code-with-me/target/code-with-me-0.0.1-SNAPSHOT-native-image-source-jar:/project:z --name build-native-ukYSr quay.io/quarkus/ubi-quarkus-native-image:21.3-java11 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=de -J-Duser.country=DE -J-Dfile.encoding=UTF-8 -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 --allow-incomplete-classpath -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https -H:-UseServiceLoaderFeature -H:+StackTrace --exclude-config .*com\.oracle\.database\.jdbc.* /META-INF/native-image/(?:native-image\.properties|reflect-config\.json) code-with-me-0.0.1-SNAPSHOT-runner -jar code-with-me-0.0.1-SNAPSHOT-runner.jar
docker: Error response from daemon: error while creating mount source path '/run/desktop/mnt/host/c/Users/myUser/prj/code-with-me/target/code-with-me-0.0.1-SNAPSHOT-native-image-source-jar': mkdir /run/desktop/mnt/host/c/Users/myUser/prj: file exists.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:55 min
[INFO] Finished at: 2022-03-29T12:46:39+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.7.5.Final:build (default) on project code-with-me: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 125
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:397)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:238)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### How to Reproduce?

1. Create a Simple Project https://code.quarkus.io/
2. Download it and copy it to a directory
3. Create a symblolic link in windows on that directory https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/mklink
4. Open the Windows Terminal / Powershell
5. Navigate to the project under the created symbolic link
6. `.\mvnw package -Pnative "-Dquarkus.native.container-build=true"`

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 LTS OpenJDK Runtime Environment Microsoft-27990 (build 11.0.13+8-LTS) OpenJDK 64-Bit Server VM Microsoft-27990 (build 11.0.13+8-LTS, mixed mode)

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by geoand** [comment]
This sounds like a docker issue. Perhaps trying a newer version of Docker could improve things?

**Comment by stefanwendelmann** [comment]
@geoand 
using docker desktop 4.6.1 (2022-03-22)

Here my `docker version` output

```
Client:
 Cloud integration: v1.0.22
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:13:04 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.6.1 (76265)
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:06:05 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Karm** [comment]
@stefanwendelmann I tried with Podman, but... https://github.com/containers/podman/issues/14414 
And that was not even a symlink.

**Comment by Karm** [comment]
It works for me these days:

* Windows 10
* Podman Windows 4.1.0

```
C:\tmp
λ mklink C:\tmp\symbolik_link C:\tmp\quarkus-quickstarts\reactive-routes-quickstart   /D
symbolic link created for C:\tmp\symbolik_link <<===>> C:\tmp\quarkus-quickstarts\reactive-routes-quickstart

C:\tmp\symbolik_link
λ ls
mvnw*  mvnw.cmd  pom.xml  README.md  src/

C:\tmp\symbolik_link
λ podman machine start

C:\tmp\symbolik_link
λ mvnw clean package -DskipTests -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:22.2-java17 -Dquarkus.native.container-runtime=podman
[INFO] Scanning for projects...
[INFO]
[INFO] ---------< io.quarkus.quickstarts:reactive-routes-quickstart >----------
[INFO] Building reactive-routes-quickstart 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ reactive-routes-quickstart ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ reactive-routes-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\tmp\symbolik_link\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ reactive-routes-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\tmp\symbolik_link\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ reactive-routes-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\tmp\symbolik_link\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ reactive-routes-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to C:\tmp\symbolik_link\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M7:test (default-test) @ reactive-routes-quickstart ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ reactive-routes-quickstart ---
[INFO] Building jar: C:\tmp\symbolik_link\target\reactive-routes-quickstart-1.0.0-SNAPSHOT.jar
[INFO]
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ reactive-routes-quickstart ---
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: C:\tmp\symbolik_link\target\reactive-routes-quickstart-1.0.0-SNAPSHOT-native-image-source-jar\reactive-routes-quickstart-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from C:\tmp\symbolik_link\target\reactive-routes-quickstart-1.0.0-SNAPSHOT-native-image-source-jar\reactive-routes-quickstart-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Using podman to run the native image builder
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Checking image status quay.io/quarkus/ubi-quarkus-mandrel:22.2-java17
Trying to pull quay.io/quarkus/ubi-quarkus-mandrel:22.2-java17...
Getting image source signatures
Copying blob sha256:b00bf81cf836a490f07335ff62b510f2c844286c32d4f348742aeb0147989afe
Copying blob sha256:05aecceb56ee8981373782b442644ba83f38f0db991c05571b834b35de9877cf
Copying blob sha256:6bbe10f5b3e61996f4a3f90e36175a2432c84896a4e2c139c8c690bb8d449c50
Copying blob sha256:008dba906bf6dbfc356bf0f378f0ecac5da5d3d51868fbee86273572cf580904
Copying blob sha256:4efea725b552cc8a8fb0bd26735820ff46a6fc97b389970b4ede13f050f4b607
Copying blob sha256:bedb08bafb0c5853cdee139e60712d3c1564c2adf62c478bdf87b4100c2593c9
Copying blob sha256:28ac89d80791fd66ed8f8eecc301494863483fdc2015541afbd1dfaaed60b250
Copying blob sha256:d1e1560b47f4105420d686bf3b02d2fb03073eab98c25f0d4c6f3e16b27e0ea4
Copying blob sha256:e5ec126ad28ea7401b9d53a5329e3b95f618da94336cbc04fd3394bf82e96541
Copying blob sha256:f4be4a3cf2d8a132ba6c05f4ab99c5643e5d6e7a6c37ac5dc598dd9c8497179f
Copying blob sha256:14b24a9c22eddf829014d1437eab8dea37ee7d8471cea48ec61828e89e2d078f
Copying blob sha256:56be2a96092d0074a3cbb95e25025a3b578e9752f226d493636dec24d6ad5c4d
Copying blob sha256:07fedb96df87a19d9d8417b4e10d85b044843b0255132e09df9b2c4ad5c39425
Copying blob sha256:31c600a1e6860d0d658a9b03fa88f4927e29c5fdea0e8f15d2f451514c4a3a34
Copying blob sha256:432dd484a781699297714ca4894bc7ed80aafad90b7d9af5aedf4027e18e39cb
Copying blob sha256:239226ad6ff33dbe74a1fd44973466692e2673a362fec3f2a4aa93344e046c27
Copying blob sha256:088b83ebe4174f2fce96cd9943aa8a77ecfc959044df2f4bc4285946c64ec25f
Copying blob sha256:5f44925afc4258e7fdda0d72d088199a7bbfd5c549915d97a08f87e1a61ef837
Copying blob sha256:d5d2e87c6892195f3ed21c1306bbef99fc3464a9714540d2341b29a4f33677dd
Copying config sha256:cc853f176bf6341a5bca738b412935662fa7142496970cb0e41b541d551c9b99
Writing manifest to image destination
Storing signatures
cc853f176bf6341a5bca738b412935662fa7142496970cb0e41b541d551c9b99
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on native-image 22.2.0.0-Final Mandrel Distribution (Java Version 17.0.4+8)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] podman run --env LANG=C --rm -v /c/tmp/symbolik_link/target/reactive-routes-quickstart-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --name build-native-BbTEk quay.io/quarkus/ubi-quarkus-mandrel:22.2-java17 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.ResourcesFeature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.localization=ALL-UNNAMED reactive-routes-quickstart-1.0.0-SNAPSHOT-runner -jar reactive-routes-quickstart-1.0.0-SNAPSHOT-runner.jar
========================================================================================================================
GraalVM Native Image: Generating 'reactive-routes-quickstart-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (46.4s @ 0.27GB)
 Version info: 'GraalVM 22.2.0.0-Final Java 17 Mandrel Distribution'
 Java version info: '17.0.4+8'
 C compiler: gcc (redhat, x86_64, 8.5.0)
 Garbage collector: Serial GC
 4 user-specific feature(s)
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.jboss.threads] categories
 - io.quarkus.runtime.graal.ResourcesFeature: Register each line in META-INF/quarkus-native-resources.txt as a resource on Substrate VM
 - org.graalvm.home.HomeFinderFeature: Finds GraalVM paths and its version number
[2/7] Performing analysis...  [*********]                                                              (150.3s @ 1.26GB)
  10,657 (89.81%) of 11,866 classes reachable
  15,106 (57.58%) of 26,234 fields reachable
  53,911 (56.54%) of 95,350 methods reachable
     438 classes,   108 fields, and 1,548 methods registered for reflection
      63 classes,    68 fields, and    55 methods registered for JNI access
       4 native libraries: dl, pthread, rt, z
[3/7] Building universe...                                                                              (11.2s @ 3.15GB)
[4/7] Parsing methods...      [***]                                                                      (9.9s @ 1.31GB)
[5/7] Inlining methods...     [***]                                                                      (6.0s @ 2.90GB)
[6/7] Compiling methods...    [*********]                                                               (88.9s @ 1.20GB)
[7/7] Creating image...                                                                                 (15.8s @ 2.76GB)
  19.55MB (48.60%) for code area:    33,399 compilation units
  20.36MB (50.62%) for image heap:  260,256 objects and 8 resources
 320.80KB ( 0.78%) for other data
  40.22MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1.65MB sun.security.ssl                                     4.29MB byte[] for code metadata
 980.12KB java.util                                            2.61MB java.lang.Class
 733.03KB com.sun.crypto.provider                              2.35MB java.lang.String
 566.24KB java.lang.invoke                                     2.31MB byte[] for general heap data
 458.82KB sun.security.x509                                    1.89MB byte[] for java.lang.String
 458.56KB java.lang                                          915.84KB com.oracle.svm.core.hub.DynamicHubCompanion
 392.11KB java.util.concurrent                               521.51KB byte[] for reflection metadata
 390.49KB io.netty.buffer                                    495.80KB java.util.HashMap$Node
 386.75KB java.io                                            464.55KB java.lang.String[]
 339.73KB java.text                                          380.74KB c.o.svm.core.hub.DynamicHub$ReflectionMetadata
  13.06MB for 379 more packages                                3.95MB for 2661 more object types
------------------------------------------------------------------------------------------------------------------------
                        11.8s (3.4% of total time) in 35 GCs | Peak RSS: 4.26GB | CPU load: 3.23
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /project/reactive-routes-quickstart-1.0.0-SNAPSHOT-runner (executable)
 /project/reactive-routes-quickstart-1.0.0-SNAPSHOT-runner.build_artifacts.txt (txt)
========================================================================================================================
Finished generating 'reactive-routes-quickstart-1.0.0-SNAPSHOT-runner' in 5m 39s.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] podman run --env LANG=C --rm -v /c/tmp/symbolik_link/target/reactive-routes-quickstart-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --entrypoint /bin/bash quay.io/quarkus/ubi-quarkus-mandrel:22.2-java17 -c objcopy --strip-debug reactive-routes-quickstart-1.0.0-SNAPSHOT-runner
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 406648ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:02 min
[INFO] Finished at: 2022-10-12T06:24:11-07:00
[INFO] ------------------------------------------------------------------------

```
