### ISSUE TITLE
Decorator using generics throws `NoSuchMethodError`

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#24624]
### Describe the bug

When a CDI decorator uses generics it can result in a `NoSuchMethodError` being thrown.

```java
public interface Logger<T> {
    void log(T rec);
}
```
```java
@Decorator
@Priority(Interceptor.Priority.APPLICATION)
public class LoggerDecorator<T> implements Logger<T> {

    @Inject
    @Delegate
    @Any
    Logger<T> delegate;

    @Override
    public void log(T rec) {
        System.out.println("decorated " + rec);
        delegate.log(rec);
    }

}
```
```java
@ApplicationScoped
public class AccessLogger implements Logger<String> {

    @Override
    public void log(String rec) {
        System.err.println(rec);
    }

}
```

Please see attached zip with a reproducer for details: [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/8378245/code-with-quarkus.zip)
 

### Expected behavior

A decorator should be able to use generics AFAICT.

### Actual behavior

With the attached reproducer I get this error when running `mvn install`:
```
2022-03-30 09:45:34,220 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello failed, error id: 175510f2-db38-439c-a434-a8016a4bced2-1: org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchMethodError: 'void org.acme.LoggerDecorator.log(java.lang.String)'
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodError: 'void org.acme.LoggerDecorator.log(java.lang.String)'
        at org.acme.AccessLogger_Subclass.log(Unknown Source)
        at org.acme.AccessLogger_ClientProxy.log(Unknown Source)
        at org.acme.GreetingResource.hello(GreetingResource.java:20)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 15 more
```

### How to Reproduce?

Unzip attached ZIP and run `mvn install`.

### Quarkus version or git rev

2.8.0.CR1

**Comment by knutwannheden** [comment]
/cc @mkouba 

I have not yet been able to reproduce the problem with the `VerifyError` I have mentioned before. I am still investigating, however.

**Comment by manovotn** [comment]
Note that this kind of generic decoration (where the delegate doesn't even know the type it's dealing with) can mostly be replaced with interception - especially for logging purposes.
If nothing else, it might be a viable workaround for you @knutwannheden

**Comment by knutwannheden** [comment]
Thanks for the workarounds. The real issue I have I am still trying to distill to a reproducer. I will then file an issue for that.

**Comment by PyAntony** [comment]
any update on this? I am facing the exact same issue.

**Comment by mkouba** [comment]
We don't plan to add support for generic decorators in the near future. See the comments above for possible workarounds.

**Comment by geoand** [comment]
Closing as per the above comment
