### ISSUE TITLE
org.rocksdb:rocksdbjni:jar:6.22.1.1 used by kafka-streams:3.1.0 is not compiled for Mac Arm64

### ISSUE THREAD

**Issue by rinmalavi** [quarkusio/quarkus#24648]
### Describe the bug

One of deeper dependencies does not support Mac Arm64

 +- io.quarkus:quarkus-kafka-streams:jar:2.7.5.Final:compile
 |  \- org.apache.kafka:kafka-streams:jar:3.1.0:compile
 |     +- org.rocksdb:rocksdbjni:jar:6.22.1.1:compile

https://github.com/facebook/rocksdb/issues/7720

This issue is resolved

https://github.com/apache/kafka/commit/3904652b3e2dd2908ee30cff228041ce80508548)

and i guesss will be included in  `kafka-streams:3.1.1`

Can be mitigated by adding  `org.rocksdb:rocksdbjni:6.29.4.1` to dependencies 

### Expected behavior

have dev working 

### Actual behavior

ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:122)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:144)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:455)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:66)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:140)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:96)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/t1/2kykfqp15cs15t7vhk40_6tr0000gp/T/librocksdbjni757309457362074679.jnilib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:69)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38)
	at io.quarkus.kafka.streams.runtime.KafkaStreamsRecorder.loadRocksDb(KafkaStreamsRecorder.java:14)
	at io.quarkus.deployment.steps.KafkaStreamsProcessor$loadRocksDb1611413226.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.KafkaStreamsProcessor$loadRocksDb1611413226.deploy(Unknown Source)
	... 13 more

### How to Reproduce?

create project with 
        
    mvn io.quarkus.platform:quarkus-maven-plugin:2.7.5.Final:create \       
            -DprojectGroupId=org.acme \
            -DprojectArtifactId=kafka-streams-quickstart-aggregator \
            -Dextensions="kafka-streams,resteasy-jackson" \
            -DnoCode
    
    echo 'quarkus.kafka-streams.topics="someTopic" > src/main/resources/application.properties

run `mvn clean quarkus:dev`

### Output of `uname -a` or `ver`

Darwin myplace 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 LTS OpenJDK Runtime Environment (build 17.0.2+9-LTS) OpenJDK 64-Bit Server VM (build 17.0.2+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.7.5.Final, 2.8.0-CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5

**Comment by gsmet** [comment]
Well, that's really not something we can do anything about. It will be fixed when we upgrade Kafka.

Closing as it's really not a Quarkus issue. But thanks for providing the workaround in case someone looks for it.
