### ISSUE TITLE
"ObjectIdInput"  must define one or more fields - Quarkus GraphQL - MongoDB

### ISSUE THREAD

**Issue by debu999** [quarkusio/quarkus#24716]
### Describe the bug

Hi Team,
Can not serialize Graphql and ObjectID for Mutation . Need a fix to do conversion from ObjectId to String may be via custom Type registration. 

### Expected behavior

ObjectID should be allowed as string in graphql and implicitly converted to ObjectId in the resolver method.
@AdaptToScalar(Scalar.String.class) Should do implicit conversion for ObjectIdInput creation in smallrye graphQL.

`@MongoEntity(collection = "demo")
public class Demo extends ReactivePanacheMongoEntityBase {

    @AdaptToScalar(Scalar.String.class)
    public ObjectId id;

    @NotBlank(message = "Name must not be blank")
    public String name;
    @NotBlank(message = "Short name must not be blank")
    public String shortName;
    @NotBlank(message = "Grade must not be blank")
    public Integer grade;
}`

`
@Mutation
    public Uni<Demo> saveDemo(Demo demo){
        return demo.persistOrUpdate();
    }
`

### Actual behavior

`"ObjectIdInput" must define one or more fields.
    at graphql.schema.GraphQLSchema$Builder.validateSchema(GraphQLSchema.java:828)
    at graphql.schema.GraphQLSchema$Builder.buildImpl(GraphQLSchema.java:822)
    at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:787)
    at io.smallrye.graphql.bootstrap.Bootstrap.generateGraphQLSchema(Bootstrap.java:186)
    at io.smallrye.graphql.bootstrap.Bootstrap.bootstrap(Bootstrap.java:113)
    at io.smallrye.graphql.bootstrap.Bootstrap.bootstrap(Bootstrap.java:107)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:34)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass.initialize$$superforward1(Unknown Source)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass$$function$$2.apply(Unknown Source)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
    at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
    at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
    at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
    at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
    at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass.initialize(Unknown Source)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:29)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass.initialize$$superforward1(Unknown Source)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass$$function$$4.apply(Unknown Source)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
    at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
    at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
    at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
    at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
    at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass.initialize(Unknown Source)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:24)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass.initialize$$superforward1(Unknown Source)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass$$function$$3.apply(Unknown Source)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
    at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
    at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
    at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
    at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
    at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer_Subclass.initialize(Unknown Source)
    at io.smallrye.graphql.cdi.producer.GraphQLProducer_ClientProxy.initialize(Unknown Source)
    at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLRecorder.createExecutionService(SmallRyeGraphQLRecorder.java:31)
    at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService259019385.deploy_1(Unknown Source)
    at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService259019385.deploy(Unknown Source)
    at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
    at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
    at java.base/java.lang.Class.newInstance(Class.java:645)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
    at io.quarkus.runner.GeneratedMain.main(Unknown Source)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
    at java.base/java.lang.Thread.run(Thread.java:833)`

### How to Reproduce?

Create a simple quarkus app with mongodb support and graphql extension.
create a ObjectId for self reference in the code.
Expose as graphql api and the app will fail.

### Output of `uname -a` or `ver`

Darwin Debabratas-MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05) OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.5

### Additional information

need mongodb and graphql with ObjectId support.

**Comment by debu999** [comment]
Is there any way to make custom Scalar for any datatype to map as input and output. Scalars are good features. need the details on how to register the same for Custom objects.

**Comment by phillip-kruger** [comment]
You can map an Object to a scalar in certain cases (see https://quarkus.io/guides/smallrye-graphql#mapping-a-complex-object-to-a-scalar-type) . Note that the `@ToScalar` has changed to `@AdaptToScalar`

or you can write your own adapter, here is an example: 

Usage: https://github.com/smallrye/smallrye-graphql/blob/8cd464aa017fa40f963fb76420a809e571cf0ade/server/tck/src/test/java/io/smallrye/graphql/test/apps/adapt/with/api/AdapterResource.java#L171

Adapter: https://github.com/smallrye/smallrye-graphql/blob/main/server/tck/src/test/java/io/smallrye/graphql/test/apps/adapt/with/api/AddressAdapter.java

Let me know if this works for you

**Comment by phillip-kruger** [comment]
Also note that adapt to scalar only work in certain cases, like if a contructer exist to be able to create the object from the scalar, or a static from string method

**Comment by debu999** [comment]
Tried all three options.
`@AdaptToScalar(Scalar.String.class)`
Did not work
`@AdaptsWith(ObjectIdAdaptor.class)`
Did not work.

Is there anything for final class. ObjectId is a final class.
Both AdaptToScalar and AdaptsWith work for queries but not for mutations. Need some advise on how to make the input customizable.

**Comment by debu999** [comment]
@phillip-kruger am i missing anything in properties to register the scalar adaptor.

**Comment by phillip-kruger** [comment]
Hi @debu999 - do you have a small app that I can look at ?

**Comment by debu999** [comment]
@phillip-kruger Sample reproducer attached.
A very simple app with just object id in graphql mutation. The adaptor works fine with query i believe somewhere in input generation it needs to register the same as in query.
[mongo-graphql.zip](https://github.com/quarkusio/quarkus/files/8415383/mongo-graphql.zip)
.

**Comment by debu999** [comment]
In case i comment the mutation and do the following it works fine.
i guess Input creation do not respect the adaptor.
`@Query
    public Uni<Dummy> getDummy()
    {
         Dummy d = new Dummy();
        d.id = new ObjectId();
        return Uni.createFrom().item(d);
    }`
    
    
<img width="1344" alt="Screenshot 2022-04-05 at 11 39 35 AM" src="https://user-images.githubusercontent.com/1910577/161690065-a4c02c3a-96f6-4179-bf23-a485d0431e82.png">

**Comment by phillip-kruger** [comment]
I'll have a look today and get back to you

**Comment by debu999** [comment]
@phillip-kruger Thanks.

### Generated Graphql Schema 
`new SchemaPrinter(
                  // Tweak the options accordingly
                  SchemaPrinter.Options.defaultOptions()
                          .includeScalarTypes(true)
                          .includeIntrospectionTypes(true)
            ).print(schema);`
`

"Directs the executor to include this field or fragment only when the `if` argument is true"
directive @include(
    "Included when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Directs the executor to skip this field or fragment when the `if`'argument is true."
directive @skip(
    "Skipped when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Marks the field, argument, input field or enum value as deprecated"
directive @deprecated(
    "The reason for the deprecation"
    reason: String = "No longer supported"
  ) on FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM_VALUE | INPUT_FIELD_DEFINITION

"Exposes a URL that specifies the behaviour of this scalar."
directive @specifiedBy(
    "The URL that specifies the behaviour of this scalar."
    url: String!
  ) on SCALAR

type Dummy {
  id: String
  name: String
}

type ObjectId {
  "ISO-8601"
  date: DateTime
  timestamp: Int!
}

"Query root"
type Query {
  dummy(d1: DummyInput): Dummy
}

type __Directive {
  args: [__InputValue!]!
  description: String
  isRepeatable: Boolean!
  locations: [__DirectiveLocation!]!
  "The __Directive type represents a Directive that a server supports."
  name: String!
  onField: Boolean @deprecated
  onFragment: Boolean @deprecated
  onOperation: Boolean @deprecated
}

type __EnumValue {
  deprecationReason: String
  description: String
  isDeprecated: Boolean!
  name: String!
}

type __Field {
  args(includeDeprecated: Boolean = false): [__InputValue!]!
  deprecationReason: String
  description: String
  isDeprecated: Boolean!
  name: String!
  type: __Type!
}

type __InputValue {
  defaultValue: String
  deprecationReason: String
  description: String
  isDeprecated: Boolean
  name: String!
  type: __Type!
}

"A GraphQL Introspection defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, the entry points for query, mutation, and subscription operations."
type __Schema {
  description: String
  "'A list of all directives supported by this server."
  directives: [__Directive!]!
  "If this server supports mutation, the type that mutation operations will be rooted at."
  mutationType: __Type
  "The type that query operations will be rooted at."
  queryType: __Type!
  "'If this server support subscription, the type that subscription operations will be rooted at."
  subscriptionType: __Type
  "A list of all types supported by this server."
  types: [__Type!]!
}

type __Type {
  description: String
  enumValues(includeDeprecated: Boolean = false): [__EnumValue!]
  fields(includeDeprecated: Boolean = false): [__Field!]
  inputFields(includeDeprecated: Boolean = false): [__InputValue!]
  interfaces: [__Type!]
  kind: __TypeKind!
  name: String
  ofType: __Type
  possibleTypes: [__Type!]
  specifiedByUrl: String
}

"An enum describing valid locations where a directive can be placed"
enum __DirectiveLocation {
  "Indicates the directive is valid on a field argument SDL definition."
  ARGUMENT_DEFINITION
  "Indicates the directive is valid on an enum SDL definition."
  ENUM
  "Indicates the directive is valid on an enum value SDL definition."
  ENUM_VALUE
  "Indicates the directive is valid on fields."
  FIELD
  "Indicates the directive is valid on a field SDL definition."
  FIELD_DEFINITION
  "Indicates the directive is valid on fragment definitions."
  FRAGMENT_DEFINITION
  "Indicates the directive is valid on fragment spreads."
  FRAGMENT_SPREAD
  "Indicates the directive is valid on inline fragments."
  INLINE_FRAGMENT
  "Indicates the directive is valid on an input object field SDL definition."
  INPUT_FIELD_DEFINITION
  "Indicates the directive is valid on an input object SDL definition."
  INPUT_OBJECT
  "Indicates the directive is valid on an interface SDL definition."
  INTERFACE
  "Indicates the directive is valid on mutations."
  MUTATION
  "Indicates the directive is valid on an object SDL definition."
  OBJECT
  "Indicates the directive is valid on queries."
  QUERY
  "Indicates the directive is valid on a scalar SDL definition."
  SCALAR
  "Indicates the directive is valid on a schema SDL definition."
  SCHEMA
  "Indicates the directive is valid on subscriptions."
  SUBSCRIPTION
  "Indicates the directive is valid on an union SDL definition."
  UNION
  "Indicates the directive is valid on variable definitions."
  VARIABLE_DEFINITION
}

"An enum describing what kind of type a given __Type is"
enum __TypeKind {
  "Indicates this type is an enum. `enumValues` is a valid field."
  ENUM
  "Indicates this type is an input object. `inputFields` is a valid field."
  INPUT_OBJECT
  "Indicates this type is an interface. `fields` and `possibleTypes` are valid fields."
  INTERFACE
  "Indicates this type is a list. `ofType` is a valid field."
  LIST
  "Indicates this type is a non-null. `ofType` is a valid field."
  NON_NULL
  "Indicates this type is an object. `fields` and `interfaces` are valid fields."
  OBJECT
  "Indicates this type is a scalar. 'specifiedByUrl' is a valid field"
  SCALAR
  "Indicates this type is a union. `possibleTypes` is a valid field."
  UNION
}

"Scalar for DateTime"
scalar DateTime

input DummyInput {
  id: String
  name: String
}

input ObjectIdInput

`

**Comment by debu999** [comment]
My understanding is that DummyInput is respecting the Adaptor and getting generated as expected but still we have a generic input `ObjectIdInput ` created. Not sure why.

**Comment by debu999** [comment]
Actual Adaptor makes the type and Input generation correct
`type Dummy {
id: String
name: String
}`
`
input DummyInput {
id: String
name: String
}`

Only a additional input ObjectIdInput causes the issue.

**Comment by phillip-kruger** [comment]
Ok this is a bug, ill fix a.s.a.p. For some reason the scanner still included the adapted field.

**Comment by phillip-kruger** [comment]
(the fix will be in smallrye, so I am closing here and opening an issue in SmallRye)

**Comment by debu999** [comment]
Thanks @phillip-kruger

**Comment by debu999** [comment]
When will this be released will it be part of 1.4.5 version?

**Comment by phillip-kruger** [comment]
There is an upcoming 1.5.0 soon, it will be in that.

**Comment by debu999** [comment]
@phillip-kruger we still dont have this in quarkus platform. Will it be udpated in 2.8.3.Final of quarkus.

**Comment by phillip-kruger** [comment]
1.5.0 is released, but will only be in Quarkus 2.10
