### ISSUE TITLE
Rest Client does not automatically register a Provider for sending application/x-www-form-urlencoded Media Type

### ISSUE THREAD

**Issue by fernandobalieiro** [quarkusio/quarkus#24715]
### Describe the bug

When creating a REST Client for sending application/x-www-form-urlencoded Media Type to an upstream, no providers are automatically registered.

They are automatically registered only if an annotation `@Consumes(MediaType.APPLICATION_FORM_URLENCODED)` is also present in some endpoint, in other words, if the project also serve requests, which is not always the case.

### Expected behavior

A Form Provider for the client should be automatically registered or such information should be present in the project's documentation regarding REST Clients development.

### Actual behavior

When creating a REST Client for sending application/x-www-form-urlencoded Media Type to an upstream, the request is not sent and the following Exception is thrown:

```bash
2022-04-03 11:54:25,291 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /request/remote failed, error id: f13c05ad-ae57-4620-8290-6811529ded10-5: org.jboss.resteasy.spi.UnhandledException: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/x-www-form-urlencoded type: javax.ws.rs.core.Form
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/x-www-form-urlencoded type: javax.ws.rs.core.Form
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:321)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:494)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:69)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.post(ClientInvocationBuilder.java:226)
        at org.acme.rest.client.RequestResource.getFormResponse(RequestResource.java:47)
        at org.acme.rest.client.RequestResource.sendRemoteRequest(RequestResource.java:30)
        at org.acme.rest.client.RequestResource_Subclass.sendRemoteRequest$$superforward1(Unknown Source)
        at org.acme.rest.client.RequestResource_Subclass$$function$$26.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at org.acme.rest.client.RequestResource_Subclass.sendRemoteRequest(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 15 more
Caused by: javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/x-www-form-urlencoded type: javax.ws.rs.core.Form
        at org.jboss.resteasy.core.interception.jaxrs.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:50)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:302)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:240)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:224)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:446)
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.writeRequestBodyToOutputStream(ManualClosingApacheHttpClient43Engine.java:625)
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.buildEntity(ManualClosingApacheHttpClient43Engine.java:584)
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.loadHttpMethod(ManualClosingApacheHttpClient43Engine.java:489)
        at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:299)
        ... 45 more
```

### How to Reproduce?

Reproducer:

1. Clone the project: [https://github.com/fernandobalieiro/quarkus-rest-client-form-bug](https://github.com/fernandobalieiro/quarkus-rest-client-form-bug)
2. Run `./mvnw clean quarkus:dev -pl rest-server` to start the server in port 8081
3. Run `./mvnw clean quarkus:dev -pl rest-client` to start the client in port 8082
4. Run `curl -v http://localhost:8082/request/remote`
5. The request fails and an Exception is thrown by the REST Client.

### Output of `uname -a` or `ver`

Linux 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05) OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /home/fernandobalieiro/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 17.0.1, vendor: GraalVM Community, runtime: /home/fernandobalieiro/.asdf/installs/java/graalvm-21.3.0+java17 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.13.0-37-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Does this work if you use `quarkus-rest-client-reactive` instead of `quarkus-rest-client`?
Asking because all our efforts are focused on the former and the latter is slowly going to be phased out

**Comment by fernandobalieiro** [comment]
Hello @geoand!
After the changes no errors are thrown by the client (no Exceptions),  but no values are sent to the remote.
Same scenario, registering the provider solves the issue. You can try by yourself using the branch [https://github.com/fernandobalieiro/quarkus-rest-client-form-bug/tree/client-reactive](https://github.com/fernandobalieiro/quarkus-rest-client-form-bug/tree/client-reactive):
```
curl -v http://localhost:8082/request/remote
* Trying 127.0.0.1:8082...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET /request/remote HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< content-length: 17
< 
* Connection #0 to host localhost left intact
Hello 'null null'%
```

**Comment by michalszynkiewicz** [comment]
The linked project mixes the classic variant and the reactive variant.
Can you replace its dependencies with this?
```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
```

**Comment by fernandobalieiro** [comment]
Hello @michalszynkiewicz, I did it and the result is the same as in my previous comment, no Exception is thrown, but no value is sent:
```
curl -v http://localhost:8082/request/remote                                                                                                                                                                                 130 ↵
*   Trying 127.0.0.1:8082...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET /request/remote HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 17
< Content-Type: application/json
< 
* Connection #0 to host localhost left intact
Hello 'null null'%    
```


After the changes, a warning also showed up and it was necessary to add `quarkus-resteasy-reactive-jackson` dependency:
```
2022-04-04 17:26:43,731 WARN  [io.qua.res.rea.ser.dep.QuarkusServerEndpointIndexer] (build-6) Quarkus detected the use of JSON in JAX-RS method 'org.acme.rest.client.RequestResource#sendRemoteRequest' but no JSON extension has been added. Consider adding 'quarkus-resteasy-reactive-jackson' or 'quarkus-resteasy-reactive-jsonb'.
```

**Comment by michalszynkiewicz** [comment]
Thanks for checking, I'll take a look at the reactive case tomorrow if nothing more urgent pops up.
Since a workaround for quarkus-rest-client exists, and as Georgios pointed out we're focusing on the former, I don't think we'll fix it in the near future. Of course PRs for it are welcome if you'd like to fix it yourself

**Comment by fernandobalieiro** [comment]
Hello!
OK. Shouldn't the information regarding the provider be added to the docs at least?

I can try to fix it, I'll take a look.

**Comment by michalszynkiewicz** [comment]
PR to add it to the documentation would be great, thank you!

**Comment by michalszynkiewicz** [comment]
rest-client-reactive supports sending url encoded messages as `MultivaluedMap`. So a workaround is to change the relevant piece of the code to:
```java
        Response response = target
                .request()
                .header("cache-control", "no-cache")
                .accept(MediaType.APPLICATION_JSON_TYPE)
                .post(Entity.entity(buildForm(firstName, lastName), MediaType.APPLICATION_FORM_URLENCODED_TYPE));
        if (response.getStatus() == 200) {
            return response.readEntity(String.class);
        }
        throw new RuntimeException("Error when requesting");
    }

    private MultivaluedMap<String, String> buildForm(final String firstName, final String lastName) {
        MultivaluedMap<String, String> form = new MultivaluedHashMap<>();
        form.putSingle("firstName", firstName);
        form.putSingle("lastName", lastName);
        return form;
    }
```
