### ISSUE TITLE
Multiple `@LookupIfProperty` and a single `@DefaultBean` not able to resolve the bean

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#24745]
### Describe the bug

I have a simple configuration like this:

```
public class CassandraTokenConfiguration {

    @Produces
    @ApplicationScoped
    @LookupIfProperty(
            name = "stargate.token-resolver.type",
            stringValue = "header"
    )
    CassandraTokenResolver headerTokenResolver(StargateConfig stargateConfig) {
        String headerName = stargateConfig.tokenResolver().header().headerName();
        return new HeaderTokenResolver(headerName);
    }

    @Produces
    @ApplicationScoped
    @LookupIfProperty(
            name = "stargate.token-resolver.type",
            stringValue = "principal"
    )
    CassandraTokenResolver principalTokenResolver() {
        return new PrincipalTokenResolver();
    }

    @Produces
    @ApplicationScoped
    @DefaultBean
    CassandraTokenResolver noopCassandraTokenResolver() {
        return (context, securityContext) -> Optional.empty();
    }

}
```

However, there is no way to inject the correct bean based on the above.

Using the `@Inject CassandraTokenResolver resolver;` fails with exception like:

```
Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type io.stargate.sgv2.docsapi.api.common.auth.CassandraTokenResolver and qualifiers [@Default]
	- java member: io.stargate.sgv2.docsapi.api.common.StargateRequestInfo().tokenResolver
	- declared on CLASS bean [types=[java.lang.Object, io.stargate.sgv2.docsapi.api.common.StargateRequestInfo], qualifiers=[@Default, @Any], target=io.stargate.sgv2.docsapi.api.common.StargateRequestInfo]
	- available beans:
		- PRODUCER METHOD bean [types=[io.stargate.sgv2.docsapi.api.common.auth.CassandraTokenResolver, java.lang.Object], qualifiers=[@Default, @Any], target=io.stargate.sgv2.docsapi.api.common.auth.CassandraTokenResolver headerTokenResolver(io.stargate.sgv2.docsapi.config.StargateConfig stargateConfig), declaringBean=io.stargate.sgv2.docsapi.api.common.auth.configuration.CassandraTokenConfiguration]
		- PRODUCER METHOD bean [types=[io.stargate.sgv2.docsapi.api.common.auth.CassandraTokenResolver, java.lang.Object], qualifiers=[@Default, @Any], target=io.stargate.sgv2.docsapi.api.common.auth.CassandraTokenResolver noopCassandraTokenResolver(), declaringBean=io.stargate.sgv2.docsapi.api.common.auth.configuration.CassandraTokenConfiguration]
		- PRODUCER METHOD bean [types=[io.stargate.sgv2.docsapi.api.common.auth.CassandraTokenResolver, java.lang.Object], qualifiers=[@Default, @Any], target=io.stargate.sgv2.docsapi.api.common.auth.CassandraTokenResolver principalTokenResolver(), declaringBean=io.stargate.sgv2.docsapi.api.common.auth.configuration.CassandraTokenConfiguration]
```

Using the `@Inject Instance<CassandraTokenResolver> resolver;` does work, but completely ignores the default bean if the given property does not match any of the specified values and ends up in the exception when calling `resolver.get()`:

```
javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [interface io.stargate.sgv2.docsapi.api.common.auth.CassandraTokenResolver] and qualifiers [[@javax.enterprise.inject.Any()]]
	at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:188)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:209)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:95)

``` 

This is a pretty standard CDI functionality, so I guess this has to be some kind of a bug.

### Expected behavior

I expect that at least one, if not both of the above given injection examples do work.

### Output of `uname -a` or `ver`

Linux ise-Precision-5550 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-Ubuntu-120.04) OpenJDK 64-Bit Server VM (build 17.0.2+8-Ubuntu-120.04, mixed mode, sharing)

### Quarkus version or git rev

2.7.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /home/ise/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 17.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.13.0-37-generic", arch: "amd64", family: "unix"

**Comment by mkouba** [comment]
This works as expected. First of all, `@LookupIfProperty` can only be used for [programmatic lookup via `javax.enterprise.inject.Instance`](https://quarkus.io/guides/cdi-reference#declaratively-choose-beans-that-can-be-obtained-by-programmatic-lookup). Furthermore, a [default bean](https://quarkus.io/guides/cdi-reference#default_beans) is always ignored if any other matching bean exists.

> This is a pretty standard CDI functionality, so I guess this has to be some kind of a bug.

Well, both the `@LookupIfProperty` and `@DefaultBean` are non-standard features of quarkus and are well desribed in the docs ;-)

**Comment by ivansenic** [comment]
@mkouba You did not understand me, default bean is not getting wired if none of the other bean exists. At least when using the `Instance<>` approach. I am not lazy and will post a reproducible example.

**Comment by mkouba** [comment]
> @mkouba You did not understand me, default bean is not getting wired if none of the other bean exists. At least when using the `Instance<>` approach. I am not lazy and will post a reproducible example.

The problem is that those beans do exist, `@LookupIfProperty` merely filters them out during programmatic lookup.

Anyway, a reproducer would be helpful.

**Comment by ivansenic** [comment]
OK here is the reproducible example: https://github.com/ivansenic/quarkus-24745.

Hitting the `/hello` endpoint gives:

```
2022-04-05 10:35:45,601 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello failed, error id: 4c7613c3-e48e-4259-a90f-c24957449225-1: org.jboss.resteasy.spi.UnhandledException: javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [interface io.quarkus.DummyService] and qualifiers [[@javax.enterprise.inject.Default()]]
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [interface io.quarkus.DummyService] and qualifiers [[@javax.enterprise.inject.Default()]]
	at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:188)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:209)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:95)
	at io.quarkus.GreetingResource.hello(GreetingResource.java:19)
	at io.quarkus.GreetingResource_Subclass.hello$$superforward1(Unknown Source)
	at io.quarkus.GreetingResource_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.GreetingResource_Subclass.hello(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 15 more
```

**Comment by mkouba** [comment]
Ok, like I wrote above - the default bean is ignored during resolution because there are two other non-default beans (`fooService()` and `barService()`). However, both of the beans are filtered out because the `some.prop` is not set. For example, if you add `some.prop=foo` to your `application.properties` the return value of `fooService()` should be injected.

**Comment by ivansenic** [comment]
But how can I achieve this simple kind of conditional dependency injection? I am sure you understand what I want. I want the `some.prop` to be optional, if it's set to `foo` or `bar` match the services, otherwise fail back to the default bean? Do you at least have some advice?

**Comment by mkouba** [comment]
You can try to use `@LookupIfProperty(name = "some.prop", stringValue = "default", lookupIfMissing = true)}` instead of `@DefaultBean`. This way the bean should be looked up when the property `some.prop` is not specified at all.

**Comment by ivansenic** [comment]
Yea but with that I am not allowing anybody to extend the configuration and add it's own implementation (unless hey hook into the same property).. `@DefaultBean` is there with a reason, and that's if not other bean would be registered.

OK thanks for clarifying this for me. I have two workarounds in my mind to sort this out now.. Cheers..

**Comment by mkouba** [comment]
> `@DefaultBean` is there with a reason, and that's if not other bean would be registered.

Exactly, but the thing is that `@LookupIfProperty` does not disable/remove a bean. Note that in Quarkus the dependencies are resolved at build time, i.e. you can't change the set of available beans at runtime. But `@LookupIfProperty` is a runtime construct that only affects programmatic lookup. 

I agree that's it's not perfect, it's a trade-off implied by the nature of quarkus "groundwork".
