### ISSUE TITLE
Quarkus 2.7.5 problem

### ISSUE THREAD

**Issue by Moicen** [quarkusio/quarkus#24781]
![78451649212946_ pic](https://user-images.githubusercontent.com/3773928/161887735-429eb2e1-9c86-4624-b668-52585aa50ef4.jpg)

After I upgrade my quarkus dependency from `2.7.0.Final` to `2.7.5.Final`, my project build process threw this error in above. How to fix it?

The Java version I used:

```bash
➤ java -version                                                                                                                                                     10:59:44
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```

Maven build command I used:

```bash
$ mvn install -DskipTests
```

Full error log:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.7.5.Final:build (default) on project taskserver: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit threw an exception: java.lang.NullPointerException: Cannot invoke "io.quarkus.runtime.logging.InheritableLevel.isInherited()" because "inheritableLevel" is null
[ERROR]         at io.quarkus.runtime.logging.LoggingSetupRecorder.getLogLevel(LoggingSetupRecorder.java:300)
[ERROR]         at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeBuildTimeLogging(LoggingSetupRecorder.java:265)
[ERROR]         at io.quarkus.deployment.logging.LoggingResourceProcessor.setupLoggingRuntimeInit(LoggingResourceProcessor.java:222)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
```

**Comment by gsmet** [comment]
Do you have any specific logging configuration in your `application.properties`? If so, could you paste them?

**Comment by Moicen** [comment]
> Do you have any specific logging configuration in your `application.properties`? If so, could you paste them?


However I can run `mvn quarkus:dev` with our problems:

![3C39EA0C-0D67-411A-BC92-9AB3BB31B36D](https://user-images.githubusercontent.com/3773928/161927654-6e34122a-0326-420b-8945-aa84e29d4459.png)

The `mvn install -DskipTests` or `mvn package -DskipTests` always failed. Is that mean there’s bug in quarkus plugin of these phases?

**Comment by gsmet** [comment]
You haven't answered my question.

**Comment by Moicen** [comment]
@gsmet Here is my `application.properties`:

```properties
# https://quarkus.io/guides/flyway
# configure your datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DBUSER}
quarkus.datasource.password=${DBPASS}
#quarkus.datasource.reactive.url=vertx-reactive:postgresql://${DBURL}/htytask
quarkus.datasource.jdbc.url=jdbc:postgresql://${DBURL}/${DBNAME}
quarkus.datasource.jdbc.max-size=13

# https://quarkus.io/blog/hibernate-orm-config-profiles/
quarkus.hibernate-orm.database.generation=${DDL}
quarkus.hibernate-orm.log.sql=true


schema.create=true

quarkus.redis.hosts=redis://${REDIS_HOST}

cn.alchemystudio.taskserver.client.NgxProxy/mp-rest/url=${NGX_URL}
cn.alchemystudio.taskserver.client.NgxProxy/mp-rest/scope=javax.inject.Singleton

cn.alchemystudio.taskserver.client.UpyunProxy/mp-rest/url=${UPYUN_URL}
cn.alchemystudio.taskserver.client.UpyunProxy/mp-rest/scope=javax.inject.Singleton

cn.alchemystudio.taskserver.client.HtyucProxy/mp-rest/url=${HTYUC_URL}
cn.alchemystudio.taskserver.client.HtyucProxy/mp-rest/scope=javax.inject.Singleton

cn.alchemystudio.taskserver.client.TsProxy/mp-rest/url=${TS_URL}
cn.alchemystudio.taskserver.client.TsProxy/mp-rest/scope=javax.inject.Singleton

cn.alchemystudio.taskserver.domain=${TS_DOMAIN}

cn.alchemystudio.taskserver.pubkey=${PUB_KEY}
cn.alchemystudio.taskserver.privkey=${PRIV_KEY}

cn.alchemystudio.taskserver.exp_days=${EXP_DAYS}

quarkus.log.level=${SYS_LOG_LEVEL}
quarkus.log.category."cn.alchemystudio".level=${TS_LOG_LEVEL}
quarkus.log.category."org.eclipse.microprofile.rest.client".level=${TS_LOG_LEVEL}
# https://www.redhat.com/en/blog/troubleshooting-performance-vertx-applications-part-iii-%E2%80%94-troubleshooting-event-loop-delays
# https://stackoverflow.com/questions/28474236/how-to-disable-the-blockedthreadchecker-of-vert-x
quarkus.log.category."io.vertx.core.impl.BlockedThreadChecker".level=OFF

upyun.operator=${UPYUN_OPERATOR}
upyun.password=${UPYUN_PASSWORD}
upyun.bucket=${UPYUN_BUCKET}
upyun.directory=${UPYUN_DIR}
upyun.cdn=${UPYUN_CDN}

task_server.halt_on_error=${HALT_ON_ERROR}
task_server.wait_sec=${WAIT_SEC}
task_server.auth_checking=${AUTH_CHECKING}
task_server.zombie_min=${ZOMBIE_MIN}

quarkus.http.test-port=8083
quarkus.http.test-ssl-port=8446
```

In addition here is my `pom.xml`:

```xml
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>cn.alchemystudio</groupId>
    <artifactId>taskserver</artifactId>
    <version>STREAM</version>
    <properties>
        <compiler-plugin.version>3.8.1</compiler-plugin.version>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
        <quarkus.platform.version>2.7.5.Final</quarkus.platform.version>
        <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
        <ver.jjwt>0.11.2</ver.jjwt>
        <ver.lombok>1.18.20</ver.lombok>
        <ver.lombok.plugin>1.18.20.0</ver.lombok.plugin>
        <ver.commons-io>2.11.0</ver.commons-io>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${ver.commons-io}</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm-panache</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-redis-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jsonb</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>io.quarkus</groupId>-->
<!--            <artifactId>quarkus-cache</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jsonb</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-agroal</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${ver.lombok}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.15</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-jwt</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-jwt-build</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-context-propagation</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-maven-plugin</artifactId>
                <version>${ver.lombok.plugin}</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>delombok</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
                <configuration>
                    <forceJavacCompilerUse>true</forceJavacCompilerUse>
                    <parameters>${maven.compiler.parameters}</parameters>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        <maven.home>${maven.home}</maven.home>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.0.0</version>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${surefire-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                                <configuration>
                                    <systemPropertyVariables>
                                        <native.image.path>
                                            ${project.build.directory}/${project.build.finalName}-runner
                                        </native.image.path>
                                        <java.util.logging.manager>org.jboss.logmanager.LogManager
                                        </java.util.logging.manager>
                                        <maven.home>${maven.home}</maven.home>
                                    </systemPropertyVariables>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <properties>
                <quarkus.package.type>native</quarkus.package.type>
            </properties>
        </profile>
    </profiles>
</project>
```

**Comment by Moicen** [comment]
From CI you can see one task is passing but the other is failed:

![0B2AD5A8-78E4-4685-BFA7-C7689B1D0B5D](https://user-images.githubusercontent.com/3773928/161988793-bed4a410-be69-418c-adb5-128b90535d13.png)

The passed one running this command:

![5D13BACE-CDFF-4C71-816C-D1F412C15D2E](https://user-images.githubusercontent.com/3773928/161988835-ed2b4e20-ac1b-420c-b121-741ffd0a03c1.png)

And it works:

![43B85DA5-0F5B-4E88-967E-D672B4C0BD56](https://user-images.githubusercontent.com/3773928/161988907-a04f0930-030b-4a57-a0b8-b276c2deeca5.png)

![07C518AC-D5FD-411F-B828-2CC638956BE0](https://user-images.githubusercontent.com/3773928/161988933-a3a975dc-c228-49dc-bedc-1b228a0557c4.png)

On the other side the failed task run this command:

![52EC1D04-D05B-494D-965E-D5B2377B4067](https://user-images.githubusercontent.com/3773928/161988962-5dc323c6-282c-45aa-8b84-72a3aa4b68c0.png)

And it failed with:

![5B20A420-E054-4BF3-9D37-4DB30F582FD5](https://user-images.githubusercontent.com/3773928/161989009-2cece646-30dd-43c5-a77e-fd09a545648f.png)

![0BBF0FEC-1153-44C6-8D9C-DF594B75B180](https://user-images.githubusercontent.com/3773928/161989038-ff790a16-2cb7-4e07-8898-12e8e1b3f7ef.png)

I can confirm it has no effect with native build, because if I build locally without `native` option, it can reproduce the same problem.

**Comment by gsmet** [comment]
My guess is the problem is here:
```
quarkus.log.level=${SYS_LOG_LEVEL}
quarkus.log.category."cn.alchemystudio".level=${TS_LOG_LEVEL}
quarkus.log.category."org.eclipse.microprofile.rest.client".level=${TS_LOG_LEVEL}
```
and you are not always passing the env variables.

My advice would be to use a default value for all the levels you define: `${SYS_LOG_LEVEL:your default}`. And same for the others.

Now we should probably handle that more gracefully. I will create a PR.

**Comment by Moicen** [comment]
@gsmet  I set default logging level according to your suggestion:

![2E995700-F46B-4D8A-AEE4-1D3C8D578C6B](https://user-images.githubusercontent.com/3773928/162024281-191e8500-4a23-4aed-8aff-e353c5acbdd6.png)

And the build now works:

![CD6FCF48-585E-4479-82F3-1B64AB3C2135](https://user-images.githubusercontent.com/3773928/162024307-526f8caa-19f6-4785-a906-c0ddee855110.png)

![7DFA662E-55BB-4C50-A368-F3A8E3B40AA9](https://user-images.githubusercontent.com/3773928/162024336-f3ce1392-0caa-4ccc-aa61-7d493cdc8805.png)

I tried non-native build in my local environment and now it works too.

Thanks for help!
