### ISSUE TITLE
Kubernetes-Config breaks Kubernetes packaging using 2.8.x

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#24796]
### Describe the bug

Having the `kubernetes-config` properties, secrets being `enabled: true` it looks like, breaks packaging using 2.8.x (CR or Final) and does not generate the Kubernetes manifests but 2.7.5.Final works fine.

The exception being thrown is:

```
[ERROR] Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.IllegalStateException: Expected at least one of: Deployment,DeploymentConfig,Service,StatefulSet,Pipeline,Task to be present.
[ERROR]         at io.dekorate.kubernetes.decorator.ResourceProvidingDecorator.lambda$getMandatoryDeploymentMetadata$4(ResourceProvidingDecorator.java:78)
[ERROR]         at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[ERROR]         at io.dekorate.kubernetes.decorator.ResourceProvidingDecorator.getMandatoryDeploymentMetadata(ResourceProvidingDecorator.java:77)
[ERROR]         at io.quarkus.kubernetes.deployment.AddRoleResourceDecorator.visit(AddRoleResourceDecorator.java:22)
[ERROR]         at io.quarkus.kubernetes.deployment.AddRoleResourceDecorator.visit(AddRoleResourceDecorator.java:12)
[ERROR]         at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:96)
[ERROR]         at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:75)
[ERROR]         at io.dekorate.ResourceRegistry.lambda$generate$3(ResourceRegistry.java:179)
[ERROR]         at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[ERROR]         at io.dekorate.ResourceRegistry.generate(ResourceRegistry.java:173)
[ERROR]         at io.dekorate.Session.generate(Session.java:285)
[ERROR]         at io.dekorate.Session.close(Session.java:248)
[ERROR]         at io.quarkus.kubernetes.deployment.KubernetesProcessor.lambda$build$2(KubernetesProcessor.java:173)
[ERROR]         at java.base/java.util.Optional.ifPresent(Optional.java:178)
[ERROR]         at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:126)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

The configuration that causes the error is:

```
"%kubernetes":
  quarkus:
    container-image:
      build: false
    kubernetes:
      deployment-target: kubernetes, knative
      labels:
        app.kubernetes.io/managed-by: quarkus
    kubernetes-config:
      enabled: true
      fail-on-missing-config: false
      config-maps:
        - app-config
        - app-service
        - app-override
      secrets:
        enabled: true
        ~:
          - app-secrets
```

If I disable secrets using `enabled: false` it works:

```
      secrets:
        enabled: false
        ~:
          - app-secrets
```
      

### Expected behavior

Running a `mvn package` with these profiles should produce the Kubernetes manifests without error.

### Actual behavior

This error is thrown when `secrets` is a part of the Kubernetes Config properties and is `enabled: true`

```
Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.IllegalStateException: Expected at least one of: Deployment,DeploymentConfig,Service,StatefulSet,Pipeline,Task to be present.
[ERROR]         at io.dekorate.kubernetes.decorator.ResourceProvidingDecorator.lambda$getMandatoryDeploymentMetadata$4(ResourceProvidingDecorator.java:78)
[ERROR]         at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[ERROR]         at io.dekorate.kubernetes.decorator.ResourceProvidingDecorator.getMandatoryDeploymentMetadata(ResourceProvidingDecorator.java:77)
[ERROR]         at io.quarkus.kubernetes.deployment.AddRoleResourceDecorator.visit(AddRoleResourceDecorator.java:22)
```

### Output of `java -version`

openjdk 17.0.2

### Quarkus version or git rev

2.8.0.CR1 or 2.8.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4

**Comment by geoand** [comment]
@iocanel can you take a look? Seems like a serious breakage

**Comment by kjq** [comment]
I am not sure where the issue is yet.  I cannot reproduce in a clean project.  Something is knocking it out but i just copied over my config verbatim.

**Comment by kjq** [comment]
Reproducer - it looks like the issue is when I have a "name" that requires expanded properties.  Removing the `name` or hard-coding it works.

**Steps:**
1. Unzip
2. run `mvn clean package`

[secrets.zip](https://github.com/quarkusio/quarkus/files/8427408/secrets.zip)

FYI, it is a really cobbled together reproducer so ignore the unused junk unless that is the issue.

**Comment by iocanel** [comment]
Thanks for sharing the reproducer, I will look at it asap!

**Comment by kjq** [comment]
Sorry, in my zeal to find it i sent over everything with binaries - this is thinner..

[secrets.zip](https://github.com/quarkusio/quarkus/files/8427429/secrets.zip)

**Comment by kjq** [comment]
Is it the name in general with combination with the config?

- name: ${logicdrop.artifact}-${logicdrop.api} = fails
- name: aaa # ${logicdrop.artifact}-${logicdrop.api} = fails
- removed property = works

**Comment by kjq** [comment]
Is the intent to keep the ability to base that name off of properties set prior?

**Comment by iocanel** [comment]
Resources are meant to be named after the application unless explicitly specified.
Your adding a custom name falls to the 'explicitly specified category'. It seems that we have an inconsistency here.

**Comment by iocanel** [comment]
@kjq: I have a fix and will create a pull request shortly.
