### ISSUE TITLE
IT test fails when building native image using -Dquarkus.native.container-build=true in MacOS

### ISSUE THREAD

**Issue by faskan** [quarkusio/quarkus#24860]
### Describe the bug

IT test fails with below error when building native image using "quarkus build --native -Dquarkus.native.container-build=true". The project is a hello world project generated using quarkus-amazon-lambda-rest-archetype with no additional changes.

[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 2.084 s <<< FAILURE! - in com.techroots.GreetingIT
[ERROR] com.techroots.GreetingIT.testFunqy  Time elapsed: 0.01 s  <<< ERROR!
java.lang.RuntimeException: Unable to successfully launch process '32277'. Exit code is: '126'.

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   GreetingIT.testFunqy » Runtime Unable to successfully launch process '32277'. ...
[INFO] 
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 3
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ pdfgenerator ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:04 min
[INFO] Finished at: 2022-04-10T23:26:23+02:00

### Expected behavior

IT test should not fail

### Actual behavior

GreetingIT fails

### How to Reproduce?

1. Generate a new maven project using 
mvn archetype:generate \
       -DarchetypeGroupId=io.quarkus \
       -DarchetypeArtifactId=quarkus-amazon-lambda-rest-archetype \
       -DarchetypeVersion=2.7.5.Final
2. quarkus build --native -Dquarkus.native.container-build=true

### Output of `uname -a` or `ver`

Darwin Faisals-MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

### Quarkus version or git rev

2.7.5.Final

**Comment by matejvasek** [comment]
Does it only happen with `-Dquarkus.native.container-build=true` flag?

**Comment by faskan** [comment]
> @faskan another speculation: since you are doing build in container the resulting binary might be of different os/architecture.
> 
> The container probably produces Linux's ELF, but your mac expects Mach-O.

@matejvasek yes, it happens only with container build flag. And you are right the build produces a Linux binary. But since I'm running it with Dquarkus.native.container-build=true I'm expecting the whole build process (including tests) to run in a container. But somehow quarkus builds the binary using a container and executes the tests in host OS.

**Comment by matejvasek** [comment]
You probably will need to install GraalVM locally.

**Comment by matejvasek** [comment]
I think it just do build in container and the result binary is copied outside the container to host, and tests are run locally then.

**Comment by matejvasek** [comment]
>I'm expecting the whole build process (including tests) to run in a container.

That would be probably feature request.

**Comment by matejvasek** [comment]
cc @iocanel @geoand you since I see you in the history of `container-image` extensions.

**Comment by geoand** [comment]
Let me try and understand this.

You are building the native binary using `-Dquarkus.native.container-build=true` on a MacOS and then trying to launch that binary in the tests?
That won't work. You'll need to build a container for that native binary using one of our container image extensions

**Comment by matejvasek** [comment]
> then trying to launch that binary in the tests?

@geoand I think the issues is the the test is being run automatically.

**Comment by matejvasek** [comment]
So it is not immediately clear what is happening.

**Comment by faskan** [comment]
yes, when you do a quarkus build, the tests run automatically. So for Mac users, either they have to ignore the tests or install graalvm locally and not use the container build flag.

**Comment by matejvasek** [comment]
@geoand I know it's logical consequence that test fail, but at least could it fail with better message? For example: `Bad Exec Format`.

**Comment by geoand** [comment]
Yeah, that makes sense

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/blob/2.9.0.Final/test-framework/common/src/main/java/io/quarkus/test/common/DefaultNativeImageLauncher.java#L112 is where the change would need to go for anyone interested

**Comment by matejvasek** [comment]
@geoand what about:
```diff
diff --git a/test-framework/common/src/main/java/io/quarkus/test/common/LauncherUtil.java b/test-framework/common/src/main/java/io/quarkus/test/common/LauncherUtil.java
index b425ad8c60..94a12c7e58 100644
--- a/test-framework/common/src/main/java/io/quarkus/test/common/LauncherUtil.java
+++ b/test-framework/common/src/main/java/io/quarkus/test/common/LauncherUtil.java
@@ -10,6 +10,7 @@ import java.nio.file.Path;
 import java.time.Duration;
 import java.util.ArrayList;
 import java.util.List;
+import java.util.Locale;
 import java.util.ServiceLoader;
 import java.util.concurrent.CountDownLatch;
 import java.util.concurrent.TimeUnit;
@@ -94,8 +95,18 @@ public final class LauncherUtil {
                     "Interrupted while waiting to determine the status of process '" + quarkusProcess.pid() + "'.");
         }
         if (!quarkusProcess.isAlive()) {
-            throw new RuntimeException("Unable to successfully launch process '" + quarkusProcess.pid() + "'. Exit code is: '"
-                    + quarkusProcess.exitValue() + "'.");
+            String message = "Unable to successfully launch process '" + quarkusProcess.pid() + "'. Exit code is: '"
+                    + quarkusProcess.exitValue() + "'.";
+
+            String osName = System.getProperty("os.name", "generic").toLowerCase(Locale.ROOT);
+            boolean isUnix = osName.contains("mac") || osName.contains("darwin") || osName.contains("linux");
+            boolean isWin = osName.contains("windows");
+            int exit = quarkusProcess.exitValue();
+            if ((isUnix && exit == 126) || (isWin && exit == 9009)) {
+                message += System.lineSeparator()
+                        + "Hint: this may be caused by building the native application in a container while the host OS or architecture differs.";
+            }
+            throw new RuntimeException(message);
         }
     }
```
The output then is:
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   NativeFunctionIT.testFunctionIntegration » Runtime Unable to successfully launch process '393167'. Exit code is: '126'.
Hint: this may be caused by building the native application in a container while the host OS or architecture differs.
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.170 s
[INFO] Finished at: 2022-05-12T17:39:03+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by geoand** [comment]
That works too

**Comment by faskan** [comment]
@matejvasek the message will definitely help a user to understand the problem. But I am not sure if this would be a good user experience. 

I think the documentation https://quarkus.io/guides/building-native-image#container-runtime should also be corrected accordingly. It should simply say that "quarkus build --native -Dquarkus.native.container-build=true" works only on a Linux machine. For Mac or other OS, the native tests has to be disabled.

By default, native tests are enabled for a starter project and if any newbie (who doesn't want to install graalvm locally) is going to try out this way and the build fails even without making a single code change.

**Comment by yurake** [comment]
```
[INFO] --- maven-failsafe-plugin:3.0.0-M8:integration-test (default) @ producer-kafka-quarkus ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running webapp.tier.service.generator.MessageGeneratorIT
16:35:23 INFO  [or.te.ut.ImageNameSubstitutor] (main) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
16:35:23 INFO  [or.te.do.DockerClientProviderStrategy] (pool-3-thread-1) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
16:35:25 INFO  [or.te.do.DockerClientProviderStrategy] (pool-3-thread-1) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
16:35:25 INFO  [or.te.DockerClientFactory] (pool-3-thread-1) Docker host IP address is localhost
16:35:25 INFO  [or.te.DockerClientFactory] (pool-3-thread-1) Connected to docker:
  Server Version: 20.10.22
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 3933 MB
16:35:25 INFO  [🐳.3.4]] (pool-3-thread-1) Creating container for image: testcontainers/ryuk:0.3.4
16:35:25 INFO  [or.te.ut.RegistryAuthLocator] (pool-3-thread-1) Credential helper/store (docker-credential-desktop) does not have credentials for https://index.docker.io/v1/
16:35:25 INFO  [🐳.3.4]] (pool-3-thread-1) Container testcontainers/ryuk:0.3.4 is starting: 190de8c4b47633863df5ab0b6d68e1f036353e588e396ba24af98307605c3aa7
16:35:26 INFO  [🐳.3.4]] (pool-3-thread-1) Container testcontainers/ryuk:0.3.4 started in PT1.231423S
16:35:26 INFO  [or.te.ut.RyukResourceReaper] (pool-3-thread-1) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
16:35:26 INFO  [or.te.DockerClientFactory] (pool-3-thread-1) Checking the system...
16:35:26 INFO  [or.te.DockerClientFactory] (pool-3-thread-1) ✔︎ Docker server version should be at least 1.6.0
16:35:26 INFO  [io.st.te.co.KafkaVersionService] (pool-3-thread-1) Latest release of Kafka is:LogicalKafkaVersionEntity{version='3.1.0', image='quay.io/strimzi-test-container/test-container:0.100.0-kafka-3.1.0'}
16:35:26 INFO  [io.st.te.co.KafkaVersionService] (pool-3-thread-1) Latest release of Kafka is:LogicalKafkaVersionEntity{version='3.1.0', image='quay.io/strimzi-test-container/test-container:0.100.0-kafka-3.1.0'}
16:35:26 INFO  [io.st.te.co.KafkaVersionService] (pool-3-thread-1) No Kafka version specified. Using latest release: quay.io/strimzi-test-container/test-container:0.100.0-kafka-3.1.0
16:35:26 INFO  [🐳.io.10.0-.1.0]] (pool-3-thread-1) Creating container for image: quay.io/strimzi-test-container/test-container:0.100.0-kafka-3.1.0
16:35:26 INFO  [or.te.ut.RegistryAuthLocator] (pool-3-thread-1) Credential helper/store (docker-credential-desktop) does not have credentials for quay.io
16:35:26 INFO  [🐳.io.10.0-.1.0]] (pool-3-thread-1) Container quay.io/strimzi-test-container/test-container:0.100.0-kafka-3.1.0 is starting: 413f33ffef4c3febc2da284beffc02b7363d9c0ee0552f3a2b3d2bd93b1337f6
16:35:27 INFO  [io.st.te.co.StrimziKafkaContainer] (pool-3-thread-1) Mapped port: 58488
16:35:27 INFO  [io.st.te.co.StrimziKafkaContainer] (pool-3-thread-1) This is all advertised listeners for Kafka PLAINTEXT://localhost:58488,BROKER1://172.28.0.2:9093
16:35:27 INFO  [io.st.te.co.StrimziKafkaContainer] (pool-3-thread-1) Copying command to 'STARTER_SCRIPT' script.
16:35:31 INFO  [🐳.io.10.0-.1.0]] (pool-3-thread-1) Container quay.io/strimzi-test-container/test-container:0.100.0-kafka-3.1.0 started in PT4.724158S
Executing "/Users/yurak/git/k8s-3tier-webapp/application/producer-kafka-quarkus/target/producer-kafka-quarkus-5.0.0-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/Users/yurak/git/k8s-3tier-webapp/application/producer-kafka-quarkus/target/quarkus.log -Dquarkus.log.file.enable=true -Dkafka.bootstrap.servers=PLAINTEXT://localhost:58488"
/Users/yurak/git/k8s-3tier-webapp/application/producer-kafka-quarkus/target/producer-kafka-quarkus-5.0.0-SNAPSHOT-runner: /Users/yurak/git/k8s-3tier-webapp/application/producer-kafka-quarkus/target/producer-kafka-quarkus-5.0.0-SNAPSHOT-runner: cannot execute binary file
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.101 s <<< FAILURE! - in webapp.tier.service.generator.MessageGeneratorIT
[ERROR] webapp.tier.service.generator.MessageGeneratorIT.testGenerate  Time elapsed: 0.009 s  <<< ERROR!
java.lang.RuntimeException:
java.lang.RuntimeException: Unable to successfully launch process '22141'. Exit code is: '126'.
This may be caused by building the native binary in a Linux container while the host is macOS.
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:337)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:110)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$2(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:202)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:165)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:132)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.RuntimeException: Unable to successfully launch process '22141'. Exit code is: '126'.
This may be caused by building the native binary in a Linux container while the host is macOS.
	at io.quarkus.test.common.LauncherUtil.ensureProcessIsAlive(LauncherUtil.java:105)
	at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:68)
	at io.quarkus.test.common.DefaultNativeImageLauncher.start(DefaultNativeImageLauncher.java:108)
	at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:196)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.doProcessStart(QuarkusIntegrationTestExtension.java:267)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:156)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:123)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	... 37 more

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   MessageGeneratorIT.testGenerate » Runtime java.lang.RuntimeException: Unable to successfully launch process '22141'. Exit code is: '126'.
This may be caused by building the native binary in a Linux container while the host is macOS.
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.8:report (report) @ producer-kafka-quarkus ---
[INFO] Loading execution data file /Users/yurak/git/k8s-3tier-webapp/application/producer-kafka-quarkus/target/jacoco-quarkus.exec
[INFO] Analyzed bundle 'producer-kafka-quarkus' with 1 classes
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.8:check (jacoco-check) @ producer-kafka-quarkus ---
[INFO] Loading execution data file /Users/yurak/git/k8s-3tier-webapp/application/producer-kafka-quarkus/target/jacoco-quarkus.exec
[INFO] Analyzed bundle 'producer-kafka-quarkus' with 1 classes
[INFO] All coverage checks have been met.
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M8:verify (default) @ producer-kafka-quarkus ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:55 min
[INFO] Finished at: 2023-02-10T16:35:32+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M8:verify (default) on project producer-kafka-quarkus:
[ERROR]
[ERROR] Please refer to /Users/yurak/git/k8s-3tier-webapp/application/producer-kafka-quarkus/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
