### ISSUE TITLE
Change Content type in prematch filter does not change content type when matching (reactive!)

### ISSUE THREAD

**Issue by argenstijn** [quarkusio/quarkus#24868]
### Describe the bug

When you post message with a non existing content-type (application/example) and in the prematch you change it 
to "application/json" i expect the matching rule should use the new content-type when matching. 

Instead i get the following message: 

```posh
ERROR: Exception occured, message= The content-type header value did not match the value in @Consumes
javax.ws.rs.NotSupportedException: The content-type header value did not match the value in @Consumes
	at org.jboss.resteasy.reactive.server.handlers.ClassRoutingHandler.handle(ClassRoutingHandler.java:118)
	at org.jboss.resteasy.reactive.server.handlers.ClassRoutingHandler.handle(ClassRoutingHandler.java:27)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:49)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
```

Below the simple pre match rule

```java
 @ServerRequestFilter(preMatching = true)
  public void preMatchingFilter(ContainerRequestContext requestContext) {
  
    
    requestContext.getHeaders().put(HttpHeaders.CONTENT_TYPE, List.of(MediaType.APPLICATION_JSON));   


  }
```

I am using the following libs:
```

	<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-amazon-lambda-rest</artifactId>
		</dependency>		

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-vertx</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy-reactive</artifactId>
		</dependency>

		<dependency>
			<groupId>io.smallrye.reactive</groupId>
			<artifactId>smallrye-mutiny-vertx-auth-oauth2</artifactId>
		</dependency>

		<dependency>
			<groupId>io.smallrye.reactive</groupId>
			<artifactId>smallrye-mutiny-vertx-web-client</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-logging-json</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkiverse.amazonservices</groupId>
			<artifactId>quarkus-amazon-ssm</artifactId>
		</dependency>

		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>url-connection-client</artifactId>
		</dependency>
```

### Expected behavior

Matching will use the new content-type set in the pre match filter

### Actual behavior

Matching will use the old content-type

### How to Reproduce?

1. Implement a simple rest service:

```java
 @Path("/example")
@Consumes(MediaType.APPLICATION_JSON)
  @POST
  public Uni<Response> example(byte[] bytes)  {    

....
}
```

2. Create pre match filter which changes the content-type to application/json
3. Post a message with a content-type application/example

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.1586]

### Output of `java -version`

openjdk version "11.0.14" 2022-01-18 LTS

### GraalVM version (if different from Java)

22.0

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.4

**Comment by argenstijn** [comment]
Wow, that is a quick fix. Thanks :)
