### ISSUE TITLE
how to disable ssl hostname verify after i configure jwt.verify.publickey.location property?

### ISSUE THREAD

**Issue by dameng58** [quarkusio/quarkus#24886]
### Describe the bug

**i set jwt.verify.publickey.location property in my properties:**

mp.jwt.verify.publickey.location=https://userservice/.well-known/jwks.json
mp.jwt.verify.issuer=TelCloud

**and i'm use quarkus-smallrye-jwt, and it's version is 2.4.1.Final**

**when i call a Service Interface,  I've had such a mistake:**

```
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching userservice found.
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
at org.jose4j.http.Get.get(Get.java:80)
at org.jose4j.jwk.HttpsJwks.refresh(HttpsJwks.java:204)
at io.smallrye.jwt.auth.principal.AbstractKeyLocationResolver.isHttpsJwksInitialized(AbstractKeyLocationResolver.java:100)
at io.smallrye.jwt.auth.principal.KeyLocationResolver.initializeKeyContent(KeyLocationResolver.java:89)
at io.smallrye.jwt.auth.principal.KeyLocationResolver.(KeyLocationResolver.java:45)
... 81 more
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching userservice found.
at java.base/sun.security.util.HostnameChecker.matchDNS(Unknown Source)
at java.base/sun.security.util.HostnameChecker.match(Unknown Source)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
... 103 more
```

### Expected behavior

interface return 2xx

### Actual behavior

interface return 401

### Output of `java -version`

11

### Quarkus version or git rev

2.4.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by geoand** [comment]
Thanks for reporting.

Does the same issue occur on the latest versions of Quarkus (`2.7.5.Final` and `2.8.0.Final`)?

**Comment by sberyozkin** [comment]
@geoand I'm pretty sure that yes, this issue will be resolved once https://github.com/smallrye/smallrye-jwt/issues/571 is resolved.

@dameng58 You can also try `quarkus-oidc`: https://quarkus.io/guides/security-openid-connect with `quarkus.tls.trust-all=true`

**Comment by dameng58** [comment]
@sberyozkin i set quarkus.tls.trust-all=true, and it still need hostname verify then show the exception：No subject alternative DNS name matching userservice found.
And how do i skip the hostname verify after i set jwt.verify.publickey.location property to https？

**Comment by dameng58** [comment]
@geoand The problem persists in the latest versions of Quarkus (2.7.5.Final and 2.8.0.Final)

**Comment by sberyozkin** [comment]
Hi @dameng58, I should've commented here, sorry, it was resolved at the `smallrye-jwt-3.4.0` level since `mp.jwt.verify.publickey.location` property is dealt with in `smallrye-jwt`, not in Quarkus itself. See a list of new `smallrye-jwt` properties at https://github.com/quarkusio/quarkus/pull/25062/files, the one you need is `smallrye.jwt.client.tls.trust-all`. Please wait till Quarkus 2.8.2.Final is released.

Also, as I commented here earlier, you can indeed use `quarkus.tls.trust-all` but with [quarkus-oidc](https://quarkus.io/guides/security-openid-connect) (instead of `quarkus-smallrye-jwt`) - you can use `quarkus-oidc` to verify the tokens as well

HTH

**Comment by dameng58** [comment]
@sberyozkin thanks. And cloud you tell me when Quarkus 2.8.2 final will be released?

**Comment by sberyozkin** [comment]
@dameng58 I believe in the next few days, CC @gsmet

**Comment by dameng58** [comment]
@sberyozkin ok.
