### ISSUE TITLE
Smallrye Reactive Messaging causes java.lang.NullPointerException: Subscription not set!

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#24899]
### Describe the bug

I'm trying to convert an InputStream to a ReactiveStream and broadcast it using Smallrye Reactive Messaging

```
    @Broadcast
    @Outgoing("my-channel")
    public PublisherBuilder<String> source() {
        return ReactiveStreams.fromPublisher((Publisher<String>) s -> {
         .
         .
         .
            String line;
            while ((line = reader.readLine()) != null) {
                        s.onNext(line);
              }
       };
```

And my receiver looks like this

```
    @Incoming("my-channel")
    public void onMessage(String s) {
        log.info(s);
    }
```

But I'm getting this exception

```
2022-04-12 20:50:02,654 ERROR [io.sma.rea.mes.provider] (Quarkus Main Thread) SRMSG00201: Error caught while processing a message: java.lang.NullPointerException: Subscription not set!
	at io.smallrye.mutiny.subscription.SafeSubscriber.manageViolationProtocol(SafeSubscriber.java:180)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNextNoSubscription(SafeSubscriber.java:117)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:88)
	at com.myapp.test.MySource.lambda$source$0(MySource.java:53)
	at io.smallrye.mutiny.groups.MultiCreate$2.subscribe(MultiCreate.java:192)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:25)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:72)
	at io.smallrye.mutiny.operators.multi.MultiMapOp.subscribe(MultiMapOp.java:24)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:72)
	at io.smallrye.mutiny.operators.multi.MultiMapOp.subscribe(MultiMapOp.java:24)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:39)
	at io.smallrye.mutiny.groups.MultiCreate$2.subscribe(MultiCreate.java:192)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:25)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:72)
	at io.smallrye.reactive.messaging.providers.locals.ContextDecorator$ContextMulti.subscribe(ContextDecorator.java:36)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:39)
	at io.smallrye.mutiny.operators.multi.multicast.MultiPublishOp.connect(MultiPublishOp.java:105)
	at io.smallrye.mutiny.operators.multi.multicast.MultiConnectAfter.subscribe(MultiConnectAfter.java:35)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:39)
	at io.smallrye.mutiny.groups.MultiCreate$2.subscribe(MultiCreate.java:192)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:25)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:72)
	at io.smallrye.mutiny.operators.multi.MultiMapOp.subscribe(MultiMapOp.java:24)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:39)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp.subscribe(MultiFlatMapOp.java:56)
	at io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:72)
	at io.smallrye.mutiny.operators.multi.MultiOnFailureInvoke.subscribe(MultiOnFailureInvoke.java:30)
	at io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:39)
	at io.smallrye.reactive.messaging.providers.SubscriberMediator.run(SubscriberMediator.java:145)
	at io.smallrye.reactive.messaging.providers.wiring.Wiring$SubscriberMediatorComponent.materialize(Wiring.java:599)
	at io.smallrye.reactive.messaging.providers.wiring.Graph.lambda$materialize$10(Graph.java:100)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.smallrye.reactive.messaging.providers.wiring.Graph.materialize(Graph.java:99)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager.start(MediatorManager.java:205)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_Subclass.start$$superforward1(Unknown Source)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_Subclass$$function$$14.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_Subclass.start(Unknown Source)
	at io.smallrye.reactive.messaging.providers.extension.MediatorManager_ClientProxy.start(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:41)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass.onApplicationStart$$superforward1(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Subclass.onApplicationStart(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_7f54e4b27c1b49e5e062caa58f1e82797fa01393.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:322)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:304)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

However, the example from here using PublisherBuilder works flawlessly:

https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.1/getting-started.html

Why do I running into this issue?

### Output of `java -version`

17

### Quarkus version or git rev

2.8.0

**Comment by cescoffier** [comment]
It seems that the publisher you pass is not compliant. Are you sure it passes the reactive streams TCK? 

My guess is that it tries to emit while you do not have a subscription yet, which is illegal.

**Comment by mklueh** [comment]
> It seems that the publisher you pass is not compliant. Are you sure it passes the reactive streams TCK?

Could you please explain further what you mean?

> My guess is that it tries to emit while you do not have a subscription yet, which is illegal.

How can I influence when I have a subscription?

I thought having a method in place with the Incoming annotation was enough to have a subscriber and the initialization is handled by Smallrye

**Comment by cescoffier** [comment]
> Could you please explain further what you mean?

Implementing a Publisher is particularly complicated. A lot more than what people think when they look at the interface. You **MUST** pass the reactive streams TCK, which comes with a large set of rules. See https://www.reactive-streams.org// and https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck. This is the reason why I do not recommend anyone to implement their own Publisher and Subscriber (and Processor) as there is a very high chance to do it wrong. 

> How can I influence when I have a subscription?

Your Publisher gets a Subscriber. You must pass a Subscription to the Subscriber and wait for the first request before emitting anything. Then, you would need to track these requests to make sure you do not emit more than the pending requests. In addition, make sure you do not call the subscriber concurrently, this is not allowed. 

I don't know what you are trying to do, but I would recommend:

1. Not use PublisherBuilder
2. Not use `ReactiveStreams.fromPublisher` with a hand-made `Publisher`

While we support these (because of the reactive messaging spec), we highly recommend using Mutiny instead. At least Mutiny passes the TCK and make things a lot easier.  You probably want to do something like:

```java
@Broadcast
@Outgoing("my-channel")
public Multi<String> source() {
      return Mult.createFrom().emitter(e -> {
       // ....
       e.emit(line);
       });
 };
```

**Comment by mklueh** [comment]
> > Could you please explain further what you mean?
> 
> Implementing a Publisher is particularly complicated. A lot more than what people think when they look at the interface. You **MUST** pass the reactive streams TCK, which comes with a large set of rules. See https://www.reactive-streams.org// and https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck. This is the reason why I do not recommend anyone to implement their own Publisher and Subscriber (and Processor) as there is a very high chance to do it wrong.
> 
> > How can I influence when I have a subscription?
> 
> Your Publisher gets a Subscriber. You must pass a Subscription to the Subscriber and wait for the first request before emitting anything. Then, you would need to track these requests to make sure you do not emit more than the pending requests. In addition, make sure you do not call the subscriber concurrently, this is not allowed.
> 
> I don't know what you are trying to do, but I would recommend:
> 
> 1. Not use PublisherBuilder
> 2. Not use `ReactiveStreams.fromPublisher` with a hand-made `Publisher`
> 
> While we support these (because of the reactive messaging spec), we highly recommend using Mutiny instead. At least Mutiny passes the TCK and make things a lot easier. You probably want to do something like:
> 
> ```java
> @Broadcast
> @Outgoing("my-channel")
> public Multi<String> source() {
>       return Multi.createFrom().emitter(e -> {
>        // ....
>        e.emit(line);
>        });
>  };
> ```

Thank you, I didn't think there is such a complexity behind that simple looking API.

I'll try it with Mutiny instead

**Comment by cescoffier** [comment]
See comments.
