### ISSUE TITLE
Maven dev mode operator fails with Kind cluster

### ISSUE THREAD

**Issue by bentito** [quarkusio/quarkus#24925]
### Describe the bug

Maven dev:mode fails when trying to test operator on Kind cluster.

### Expected behavior

`mvn quarkus:dev` should work.

### Actual behavior

`mvn quarkus:dev` fails as follows:

```
trino-operator main $ mvn quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< tech.tofel:trino >--------------------------
[INFO] Building trino 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:2.7.1.Final:dev (default-cli) @ trino ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources) @ trino
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile) @ trino
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to /Users/btofel/workspace/trino-operator/target/classes
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources) @ trino
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/btofel/workspace/trino-operator/src/test/resources
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile) @ trino
[INFO] No sources to compile
Listening for transport dt_socket at address: 5005
2022-04-13 14:23:52,684 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4) Registered 'tech.tofel.TrinoOperator' for reflection
2022-04-13 14:23:52,688 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4) Registered 'tech.tofel.TrinoOperatorSpec' for reflection
2022-04-13 14:23:52,688 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4) Registered 'tech.tofel.TrinoOperatorStatus' for reflection
2022-04-13 14:23:52,830 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4) Processed 'tech.tofel.TrinoOperatorController' reconciler named 'trinooperator' for 'trino-operators.trino-group.tofel.tech' resource (version 'trino-group.tofel.tech/v1alpha1')
2022-04-13 14:23:52,833 INFO  [io.fab.crd.gen.CRDGenerator] (build-4) Generating 'trino-operators.trino-group.tofel.tech' version 'v1alpha1' with tech.tofel.TrinoOperator (spec: tech.tofel.TrinoOperatorSpec / status tech.tofel.TrinoOperatorStatus)...
2022-04-13 14:23:52,992 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4) Generated trino-operators.trino-group.tofel.tech CRD:
2022-04-13 14:23:52,993 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4)   - v1 -> /Users/btofel/workspace/trino-operator/target/kubernetes/trino-operators.trino-group.tofel.tech-v1.yml
[
  [34;1mINFO [m] Checking for existing resources in: /Users/btofel/workspace/trino-operator/src/main/kubernetes.

2022-04-13 14:23:54,490 INFO  [io.qua.ope.csv.dep.CSVProcessor] (build-41) Generating CSV for trinooperator controller -> /Users/btofel/workspace/trino-operator/target/kubernetes/trinooperator.csv.yml
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-04-13 14:23:55,691 INFO  [io.qua.ope.run.OperatorProducer] (Quarkus Main Thread) Applied v1 CRD named 'trino-operators.trino-group.tofel.tech' from /Users/btofel/workspace/trino-operator/target/kubernetes/trino-operators.trino-group.tofel.tech-v1.yml

2022-04-13 14:23:55,695 INFO  [io.jav.ope.Operator] (Quarkus Main Thread) Registered reconciler: 'trinooperator' for resource: 'class tech.tofel.TrinoOperator' for namespace(s): [null]
2022-04-13 14:23:55,696 INFO  [io.qua.ope.run.AppEventListener] (Quarkus Main Thread) Quarkus Java Operator SDK extension 3.0.3 (commit: ccc257b on branch: ccc257b4706b455e82e5541d456c5a1592316ac4) built on Mon Feb 07 09:13:36 EST 2022
2022-04-13 14:23:55,696 INFO  [io.jav.ope.Operator] (Quarkus Main Thread) Operator SDK 2.1.1 (commit: 817f8ca) built on Mon Feb 07 05:16:44 EST 2022 starting...
2022-04-13 14:23:55,697 INFO  [io.jav.ope.Operator] (Quarkus Main Thread) Client version: 5.12.1
2022-04-13 14:23:55,724 WARN  [io.jav.ope.pro.eve.EventSourceManager] (Quarkus Main Thread) Error starting io.javaoperatorsdk.operator.processing.event.source.controller.ControllerResourceEventSource@70822e0e: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ControllerResourceEventSource.createAndRunInformerFor(ControllerResourceEventSource.java:107)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ControllerResourceEventSource.lambda$start$0(ControllerResourceEventSource.java:89)
	at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4797)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ControllerResourceEventSource.start(ControllerResourceEventSource.java:88)
	at io.javaoperatorsdk.operator.processing.event.EventSourceManager.start(EventSourceManager.java:72)
	at io.javaoperatorsdk.operator.processing.Controller.start(Controller.java:196)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at io.javaoperatorsdk.operator.Operator$ControllerManager.start(Operator.java:164)
	at io.javaoperatorsdk.operator.Operator.start(Operator.java:82)
	at io.quarkiverse.operatorsdk.runtime.AppEventListener.onStartup(AppEventListener.java:31)
	at io.quarkiverse.operatorsdk.runtime.AppEventListener_Observer_onStartup_8d7b338c7415a5b0bcaaf3b82fd300311baae948.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:834)


2022-04-13 14:23:55,801 INFO  [io.quarkus] (Quarkus Main Thread) trino 0.0.1-SNAPSHOT on JVM (powered by Quarkus 2.7.1.Final) started in 4.267s. Listening on: http://localhost:8080
2022-04-13 14:23:55,803 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2022-04-13 14:23:55,803 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, kubernetes, kubernetes-client, openshift-client, operator-sdk, smallrye-context-propagation, smallrye-health, vertx]

--
Tests paused
Press [r] to resume testing, [o] Toggle test output, [:] for the terminal, [h] for more options>
```

Same code works when used with dev mode with another type of cluster, for instance, CRC.

### How to Reproduce?

`git clone git@github.com:bentito/trino-operator.git`

on MacOS:

`$ brew install kind`

as of Kind version  0.12.0

`$ mvn quarkus:dev`

See error as supplied below.

### Output of `uname -a` or `ver`

Darwin bretts-mbp.lan 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06) OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /usr/local/Cellar/maven/3.8.1/libexec Java version: 11.0.10, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

### Additional information

```
trino-operator main $ brew upgrade kind
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated Homebrew from d2b1a9d83 to cc6a91fea.
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 8 formulae.

==> Upgrading 1 outdated package:
kind 0.11.1 -> 0.12.0
==> Downloading https://ghcr.io/v2/homebrew/core/kind/manifests/0.12.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/kind/blobs/sha256:eb73ee98fae1727acc28ed0dbc86ad6c6ee1178c84f43c25402e1fc71f97d189
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:eb73ee98fae1727acc28ed0dbc86ad6c6ee1178c84f43c25402e1fc71f97d189?se=2022-04-13T17%3A30%3A00Z&sig=B4nf
######################################################################## 100.0%
==> Upgrading kind
  0.11.1 -> 0.12.0

==> Pouring kind--0.12.0.monterey.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/kind/0.12.0: 8 files, 8.4MB
==> Running `brew cleanup kind`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /usr/local/Cellar/kind/0.11.1... (8 files, 8.3MB)
trino-operator main $ kind delete clusters kind
Deleted clusters: ["kind"]
trino-operator main $ kind-with-registry
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.23.4) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋
Error response from daemon: endpoint with name kind-registry already exists in network kind
configmap/local-registry-hosting created
trino-operator main $ mvn quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< tech.tofel:trino >--------------------------
[INFO] Building trino 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:2.7.1.Final:dev (default-cli) @ trino ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources) @ trino
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile) @ trino
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to /Users/btofel/workspace/trino-operator/target/classes
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources) @ trino
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/btofel/workspace/trino-operator/src/test/resources
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile) @ trino
[INFO] No sources to compile
Listening for transport dt_socket at address: 5005
2022-04-13 14:23:52,684 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4) Registered 'tech.tofel.TrinoOperator' for reflection
2022-04-13 14:23:52,688 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4) Registered 'tech.tofel.TrinoOperatorSpec' for reflection
2022-04-13 14:23:52,688 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4) Registered 'tech.tofel.TrinoOperatorStatus' for reflection
2022-04-13 14:23:52,830 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4) Processed 'tech.tofel.TrinoOperatorController' reconciler named 'trinooperator' for 'trino-operators.trino-group.tofel.tech' resource (version 'trino-group.tofel.tech/v1alpha1')
2022-04-13 14:23:52,833 INFO  [io.fab.crd.gen.CRDGenerator] (build-4) Generating 'trino-operators.trino-group.tofel.tech' version 'v1alpha1' with tech.tofel.TrinoOperator (spec: tech.tofel.TrinoOperatorSpec / status tech.tofel.TrinoOperatorStatus)...
2022-04-13 14:23:52,992 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4) Generated trino-operators.trino-group.tofel.tech CRD:
2022-04-13 14:23:52,993 INFO  [io.qua.ope.dep.OperatorSDKProcessor] (build-4)   - v1 -> /Users/btofel/workspace/trino-operator/target/kubernetes/trino-operators.trino-group.tofel.tech-v1.yml
[
  [34;1mINFO [m] Checking for existing resources in: /Users/btofel/workspace/trino-operator/src/main/kubernetes.

2022-04-13 14:23:54,490 INFO  [io.qua.ope.csv.dep.CSVProcessor] (build-41) Generating CSV for trinooperator controller -> /Users/btofel/workspace/trino-operator/target/kubernetes/trinooperator.csv.yml
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-04-13 14:23:55,691 INFO  [io.qua.ope.run.OperatorProducer] (Quarkus Main Thread) Applied v1 CRD named 'trino-operators.trino-group.tofel.tech' from /Users/btofel/workspace/trino-operator/target/kubernetes/trino-operators.trino-group.tofel.tech-v1.yml

2022-04-13 14:23:55,695 INFO  [io.jav.ope.Operator] (Quarkus Main Thread) Registered reconciler: 'trinooperator' for resource: 'class tech.tofel.TrinoOperator' for namespace(s): [null]
2022-04-13 14:23:55,696 INFO  [io.qua.ope.run.AppEventListener] (Quarkus Main Thread) Quarkus Java Operator SDK extension 3.0.3 (commit: ccc257b on branch: ccc257b4706b455e82e5541d456c5a1592316ac4) built on Mon Feb 07 09:13:36 EST 2022
2022-04-13 14:23:55,696 INFO  [io.jav.ope.Operator] (Quarkus Main Thread) Operator SDK 2.1.1 (commit: 817f8ca) built on Mon Feb 07 05:16:44 EST 2022 starting...
2022-04-13 14:23:55,697 INFO  [io.jav.ope.Operator] (Quarkus Main Thread) Client version: 5.12.1
2022-04-13 14:23:55,724 WARN  [io.jav.ope.pro.eve.EventSourceManager] (Quarkus Main Thread) Error starting io.javaoperatorsdk.operator.processing.event.source.controller.ControllerResourceEventSource@70822e0e: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ControllerResourceEventSource.createAndRunInformerFor(ControllerResourceEventSource.java:107)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ControllerResourceEventSource.lambda$start$0(ControllerResourceEventSource.java:89)
	at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4797)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ControllerResourceEventSource.start(ControllerResourceEventSource.java:88)
	at io.javaoperatorsdk.operator.processing.event.EventSourceManager.start(EventSourceManager.java:72)
	at io.javaoperatorsdk.operator.processing.Controller.start(Controller.java:196)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at io.javaoperatorsdk.operator.Operator$ControllerManager.start(Operator.java:164)
	at io.javaoperatorsdk.operator.Operator.start(Operator.java:82)
	at io.quarkiverse.operatorsdk.runtime.AppEventListener.onStartup(AppEventListener.java:31)
	at io.quarkiverse.operatorsdk.runtime.AppEventListener_Observer_onStartup_8d7b338c7415a5b0bcaaf3b82fd300311baae948.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by geoand** [comment]
This is an operator SDK issue, not a Quarkus issue. Please open an issue in the relevant repository

**Comment by bentito** [comment]
Hmm yeah I guess a closer reading of that exception chain means it seems like JOSDK didn't deal with something handed it properly

**Comment by bentito** [comment]
filed https://github.com/java-operator-sdk/java-operator-sdk/issues/1157

**Comment by geoand** [comment]
👌
