### ISSUE TITLE
Oracle Devservice fails to launch on hosts with over 100 CPU cores

### ISSUE THREAD

**Issue by Felk** [quarkusio/quarkus#24939]
### Describe the bug

This is essentially the same issue as https://github.com/gvenzl/oci-oracle-xe/issues/64 but with _even more_ CPU cores. Since using that many cores is unreasonable anyway, and the upstream dockerfile seems to rely on an `if`-case for every CPU count, it might be better to implement a workaround along the lines of this: https://github.com/gvenzl/oci-oracle-xe/issues/64#issuecomment-1099107397

> Wouldn't docker run --cpus=2 option do the trick?
https://docs.docker.com/config/containers/resource_constraints/#configure-the-default-cfs-scheduler
Unless you really want to use more.

### Quarkus version or git rev

2.8.0

### Additional information

see https://github.com/gvenzl/oci-oracle-xe/issues/64#issuecomment-1087261618 for the error message that is currently happening on a 128 core machine.

**Comment by Sanne** [comment]
Thanks for reporting @Felk , I'll try this but don't have a larger machine :)
Could you verify my PR #24975 ?

**Comment by Felk** [comment]
Thank you! Will do, but probably not before Tuesday. I'll let you know

**Comment by Sanne** [comment]
sure, no rush :)
thanks

**Comment by Felk** [comment]
I tried it with the newest snapshot, but unfortunately the error persists:

```
Downloading from quarkus-snapshots-repository: https://s01.oss.sonatype.org/content/repositories/snapshots/io/quarkus/quarkus-jdbc-oracle-deployment/999-SNAPSHOT/maven-metadata.xml
Downloaded from quarkus-snapshots-repository: https://s01.oss.sonatype.org/content/repositories/snapshots/io/quarkus/quarkus-jdbc-oracle-deployment/999-SNAPSHOT/maven-metadata.xml (1.0 kB at 4.6 kB/s)
Downloading from quarkus-snapshots-repository: https://s01.oss.sonatype.org/content/repositories/snapshots/io/quarkus/quarkus-jdbc-oracle-deployment/999-SNAPSHOT/quarkus-jdbc-oracle-deployment-999-20220421.024033-343.pom
Downloaded from quarkus-snapshots-repository: https://s01.oss.sonatype.org/content/repositories/snapshots/io/quarkus/quarkus-jdbc-oracle-deployment/999-SNAPSHOT/quarkus-jdbc-oracle-deployment-999-20220421.024033-343.pom (3.7 kB at 17 kB/s)

...

2022-04-21 08:48:51,861 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
2022-04-21 08:48:53,054 WARN  [org.tes.uti.TestcontainersConfiguration] (build-32) Attempted to read Testcontainers configuration file at file:/root/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: /root/.testcontainers.properties (No such file or directory)
2022-04-21 08:48:54,540 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-32) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2022-04-21 08:48:54,638 INFO  [org.tes.DockerClientFactory] (build-32) Docker host IP address is 172.17.0.1
2022-04-21 08:48:54,756 INFO  [org.tes.DockerClientFactory] (build-32) Connected to docker: 
  Server Version: 20.10.13
  API Version: 1.41
  Operating System: AlmaLinux 8.5 (Arctic Sphynx)
  Total Memory: 515337 MB
2022-04-21 08:48:54,839 INFO  [org.tes.uti.ImageNameSubstitutor] (build-32) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2022-04-21 08:48:56,646 INFO  [org.tes.uti.RegistryAuthLocator] (build-32) Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.3.3, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
2022-04-21 08:48:57,551 INFO  [org.tes.uti.RyukResourceReaper] (build-32) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2022-04-21 08:48:57,551 INFO  [org.tes.DockerClientFactory] (build-32) Checking the system...
2022-04-21 08:48:57,552 INFO  [org.tes.DockerClientFactory] (build-32) ?? Docker server version should be at least 1.6.0
2022-04-21 08:48:57,638 INFO  [org.tes.DockerClientFactory] (build-32) ?? Docker environment should have more than 2GB free disk space
2022-04-21 08:48:57,656 INFO  [doc.io/gvenzl/oracle-xe:21-slim]] (build-32) Creating container for image: docker.io/gvenzl/oracle-xe:21-slim
2022-04-21 08:48:57,657 INFO  [org.tes.uti.RegistryAuthLocator] (build-32) Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: docker.io/gvenzl/oracle-xe:21-slim, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
2022-04-21 08:48:57,736 INFO  [doc.io/gvenzl/oracle-xe:21-slim]] (build-32) Container docker.io/gvenzl/oracle-xe:21-slim is starting: 876922cf381ef66a045e5c9204de2b17c3fc152dec97fbe8fa93547004ae1317
2022-04-21 08:52:58,099 ERROR [doc.io/gvenzl/oracle-xe:21-slim]] (build-32) Could not start container: java.lang.IllegalStateException: Container exited with code 54
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:509)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:340)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:338)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326)
	at io.quarkus.devservices.oracle.deployment.OracleDevServicesProcessor$1.startDatabase(OracleDevServicesProcessor.java:57)
	at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:263)
	at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.launchDatabases(DevServicesDatasourceProcessor.java:126)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
2022-04-21 08:52:58,130 ERROR [doc.io/gvenzl/oracle-xe:21-slim]] (build-32) Log output from the failed container:
CONTAINER: starting up...
CONTAINER: first database startup, initializing...
CONTAINER: uncompressing database data files, please wait...
CONTAINER: done uncompressing database data files, duration: 14 seconds.
CONTAINER: machine has high CPU count: 96
/opt/oracle/container-entrypoint.sh: line 156: ((: 96 = 32 : attempted assignment to non-variable (error token is "= 32 ")
CONTAINER: increasing SGA_TARGET to 1800MB.
File created.
File created.
CONTAINER: done increasing SGA_TARGET.
CONTAINER: starting up Oracle Database...
LSNRCTL for Linux: Version 21.0.0.0.0 - Production on 21-APR-2022 08:49:12
Copyright (c) 1991, 2021, Oracle.  All rights reserved.
Starting /opt/oracle/product/21c/dbhomeXE/bin/tnslsnr: please wait...
TNSLSNR for Linux: Version 21.0.0.0.0 - Production
System parameter file is /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/876922cf381e/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC_FOR_XE)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 21.0.0.0.0 - Production
Start Date                21-APR-2022 08:49:12
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           XE
Listener Parameter File   /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/876922cf381e/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
ORA-00821: Specified value of sga_target 1808M is too small, needs to be at least 2320M
ORA-01078: failure in processing system parameters
```
