### ISSUE TITLE
Config mapping to a Map with a List value type fails

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#24944]
### Describe the bug

Having a config mapping to a `Map<String, List<Double>>` fails with the `java.lang.ClassCastException`. 

Seems that the [ConfigMappingProvider#processLazyMap](https://github.com/smallrye/smallrye-config/blob/main/implementation/src/main/java/io/smallrye/config/ConfigMappingProvider.java#L416-L488) does not have a correct switch for the `CollectionProperty` and fails with class cast exception.

I can also confirm that the config mapping to `Map<String, Map<Double, Boolean>>` works for example. Again most likely because that `ConfigMappingProvider` does handle the case when value is a map.

### Expected behavior

* the map value resolves correctly in case of a `List` or `Set`

### Actual behavior

* class cast exception

### How to Reproduce?

Simple to reproduce:

```
@ConfigMapping(prefix = "some")
public interface Config {

  Map<String, List<Double>> prop();
  
}  
```

and config:

```
some:
  prop:
    value:    
      - 0.9
      - 0.99
```

leads to:

```
Caused by: java.lang.ClassCastException
	at io.smallrye.config.ConfigMappingInterface$Property.asGroup(ConfigMappingInterface.java:225)
	at io.smallrye.config.ConfigMappingProvider.processLazyMap(ConfigMappingProvider.java:481)
	at io.smallrye.config.ConfigMappingProvider.processLazyMapInGroup(ConfigMappingProvider.java:411)
	at io.smallrye.config.ConfigMappingProvider.processProperty(ConfigMappingProvider.java:215)
	at io.smallrye.config.ConfigMappingProvider.processEagerGroup(ConfigMappingProvider.java:151)
	at io.smallrye.config.ConfigMappingProvider.<init>(ConfigMappingProvider.java:80)
	at io.smallrye.config.ConfigMappingProvider$Builder.build(ConfigMappingProvider.java:955)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:444)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	... 13 more
```

### Output of `uname -a` or `ver`

Linux ise-Precision-5550 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Quarkus version or git rev

2.8.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /home/ise/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 17.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.13.0-39-generic", arch: "amd64", family: "unix"

**Comment by radcortez** [comment]
Yes, this is not supported.

**Comment by radcortez** [comment]
> Can i work on this as my first issue ?

Sure. You can find the code in https://github.com/smallrye/smallrye-config/
