### ISSUE TITLE
ConcurrentModificationException when use @GraphQLClientApi

### ISSUE THREAD

**Issue by lenhatuan** [quarkusio/quarkus#24996]
### Describe the bug

I'm using `@GraphQLClientApi`. Then stress test 1000 request by using jmeter.
Sometimes it thrown `ConcurrentModificationException`
But when I use `DynamicGraphQLClient`, I don't see this exception anymore.

### Expected behavior

No exception is thrown

### Actual behavior

```posh
13:45:05 ERROR [io.sm.graphql] (vert.x-worker-thread-0) SRGQL012000: Data Fetching Error: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.request(VertxTypesafeGraphQLClientProxy.java:226)
	at io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.invoke(VertxTypesafeGraphQLClientProxy.java:108)
	at io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientBuilder.invoke(VertxTypesafeGraphQLClientBuilder.java:193)
	at io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientBuilder.lambda$build$0(VertxTypesafeGraphQLClientBuilder.java:141)
	at com.sun.proxy.$Proxy85.initTransaction(Unknown Source)
	at vn.bizzi.graphql.client.TransactionClient.getTransactionInfo(TransactionClient.java:65)
	at vn.bizzi.graphql.client.TransactionClient_Subclass.getTransactionInfo$$superforward1(Unknown Source)
	at vn.bizzi.graphql.client.TransactionClient_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at vn.bizzi.graphql.client.TransactionClient_Subclass.getTransactionInfo(Unknown Source)
	at vn.bizzi.graphql.client.TransactionClient_ClientProxy.getTransactionInfo(Unknown Source)
	at vn.bizzi.service.TransactionService.getTransactionInfo(TransactionService.java:24)
	at vn.bizzi.service.TransactionService_Subclass.getTransactionInfo$$superforward1(Unknown Source)
	at vn.bizzi.service.TransactionService_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at vn.bizzi.service.TransactionService_Subclass.getTransactionInfo(Unknown Source)
	at vn.bizzi.service.TransactionService_ClientProxy.getTransactionInfo(Unknown Source)
	at vn.bizzi.graphql.TransactionResource.getTransaction(TransactionResource.java:25)
	at vn.bizzi.graphql.TransactionResource_Subclass.getTransaction$$superforward1(Unknown Source)
	at vn.bizzi.graphql.TransactionResource_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at vn.bizzi.graphql.TransactionResource_Subclass.getTransaction(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.smallrye.graphql.execution.datafetcher.helper.ReflectionInvoker.invoke(ReflectionInvoker.java:94)
	at io.smallrye.graphql.execution.datafetcher.UniDataFetcher.invokeAndTransform(UniDataFetcher.java:40)
	at io.smallrye.graphql.execution.datafetcher.AbstractDataFetcher.get(AbstractDataFetcher.java:53)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:279)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:210)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
	at graphql.execution.Execution.executeOperation(Execution.java:160)
	at graphql.execution.Execution.execute(Execution.java:106)
	at graphql.GraphQL.execute(GraphQL.java:641)
	at graphql.GraphQL.lambda$parseValidateAndExecute$11(GraphQL.java:561)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:556)
	at graphql.GraphQL.executeAsync(GraphQL.java:524)
	at graphql.GraphQL.execute(GraphQL.java:450)
	at io.smallrye.graphql.execution.ExecutionService.writeSync(ExecutionService.java:229)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:183)
	at io.smallrye.graphql.execution.ExecutionService.executeSync(ExecutionService.java:112)
	at io.smallrye.graphql.execution.ExecutionService.executeSync(ExecutionService.java:108)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:96)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:299)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:113)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:73)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handleWithIdentity(SmallRyeGraphQLAbstractHandler.java:66)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:48)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:23)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### How to Reproduce?

1. Use a @GraphQLClientApi interface
2. Send 1000 concurrent request to call GraphQLClientApi interface

### Additional information

My interface.
@GraphQLClientApi(configKey = "transaction")
public interface ITransactionClient {

    @Query
    TransactionInfo initTransaction();

}

**Comment by geoand** [comment]
https://github.com/smallrye/smallrye-graphql/pull/1358 should take care of it

**Comment by lenhatuan** [comment]
Thanks @geoand , @jmartisk , @phillip-kruger for your support :D

**Comment by lenhatuan** [comment]
I'm still facing this issue :(
2022-04-23 22:55:59,608 ERROR [io.sma.graphql] (vert.x-worker-thread-32) SRGQL012000: Data Fetching Error: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.request(VertxTypesafeGraphQLClientProxy.java:226)
	at io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.invoke(VertxTypesafeGraphQLClientProxy.java:108)
	at io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientBuilder.invoke(VertxTypesafeGraphQLClientBuilder.java:193)
	at io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientBuilder.lambda$build$0(VertxTypesafeGraphQLClientBuilder.java:141)
	at jdk.proxy4/jdk.proxy4.$Proxy43.createTransaction(Unknown Source)
	at vn.bizzi.service.TransactionService.createTransactionInfo(TransactionService.java:34)
	at vn.bizzi.service.TransactionService_Subclass.createTransactionInfo$$superforward1(Unknown Source)
	at vn.bizzi.service.TransactionService_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at vn.bizzi.service.TransactionService_Subclass.createTransactionInfo(Unknown Source)
	at vn.bizzi.service.TransactionService_ClientProxy.createTransactionInfo(Unknown Source)
	at vn.bizzi.graphql.TransactionResource.createTransaction(TransactionResource.java:26)
	at vn.bizzi.graphql.TransactionResource_Subclass.createTransaction$$superforward1(Unknown Source)
	at vn.bizzi.graphql.TransactionResource_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at vn.bizzi.graphql.TransactionResource_Subclass.createTransaction(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.smallrye.graphql.execution.datafetcher.helper.ReflectionInvoker.invoke(ReflectionInvoker.java:94)
	at io.smallrye.graphql.execution.datafetcher.DefaultDataFetcher.invokeAndTransform(DefaultDataFetcher.java:36)
	at io.smallrye.graphql.execution.datafetcher.AbstractDataFetcher.get(AbstractDataFetcher.java:53)
	at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:87)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:279)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:210)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:182)
	at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:43)
	at graphql.execution.Async.eachSequentiallyImpl(Async.java:80)
	at graphql.execution.Async.eachSequentially(Async.java:69)
	at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:38)
	at graphql.execution.Execution.executeOperation(Execution.java:160)
	at graphql.execution.Execution.execute(Execution.java:106)
	at graphql.GraphQL.execute(GraphQL.java:641)
	at graphql.GraphQL.lambda$parseValidateAndExecute$11(GraphQL.java:561)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:556)
	at graphql.GraphQL.executeAsync(GraphQL.java:524)
	at graphql.GraphQL.execute(GraphQL.java:450)
	at io.smallrye.graphql.execution.ExecutionService.writeSync(ExecutionService.java:229)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:183)
	at io.smallrye.graphql.execution.ExecutionService.executeSync(ExecutionService.java:112)
	at io.smallrye.graphql.execution.ExecutionService.executeSync(ExecutionService.java:108)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:96)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:299)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:113)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:73)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handleWithIdentity(SmallRyeGraphQLAbstractHandler.java:66)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:48)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:23)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by geoand** [comment]
The fix will be included in 2.8.2

**Comment by lenhatuan** [comment]
Yeah, thanks @geoand , I'm using 2.8.1 version :D

**Comment by gsmet** [comment]
I will release 2.8.2.Final on Tuesday.
