### ISSUE TITLE
`BufferOverflowException` via Maven/Failsafe w/ `@QuarkusIntegrationTest` + native image

### ISSUE THREAD

**Issue by snazy** [quarkusio/quarkus#25014]
### Describe the bug

Hit a weird scenario today while working on https://github.com/projectnessie/nessie/pull/3988 , which runs integration tests using 
`@QuarkusIntegrationTest` + native images. Once the `start()` method of a `QuarkusTestResourceLifecycleManager` implementation writes to `System.out` or `System.err`, the following `BufferOverflowException` is being thrown.

I'll try to setup a reproducer, but it's actually sufficient to use the code from the PR (or when it's merged to main), add a `System.err.println()` and run `./mvnw -Pdocker -Pnative clean verify` or so.

```java
public class DynamoTestResourceLifecycleManager implements QuarkusTestResourceLifecycleManager {
  @Override
  public Map<String, String> start() {
    System.err.println();
  }
}
```

```
 Caused by: java.nio.BufferOverflowException
   at java.base/java.nio.Buffer.nextPutIndex(Buffer.java:666)
   at java.base/java.nio.HeapByteBuffer.put(HeapByteBuffer.java:200)
   at org.apache.maven.surefire.api.stream.AbstractStreamEncoder.encodeString(AbstractStreamEncoder.java:127)
   at org.apache.maven.surefire.api.stream.AbstractStreamEncoder.encodeStringData(AbstractStreamEncoder.java:171)
   at org.apache.maven.surefire.api.stream.AbstractStreamEncoder.encode(AbstractStreamEncoder.java:157)
   at org.apache.maven.surefire.booter.spi.EventChannelEncoder.encodeMessage(EventChannelEncoder.java:398)
   at org.apache.maven.surefire.booter.spi.EventChannelEncoder.setOutErr(EventChannelEncoder.java:188)
   at org.apache.maven.surefire.booter.spi.EventChannelEncoder.testOutput(EventChannelEncoder.java:183)
   at org.apache.maven.surefire.api.booter.ForkingRunListener.writeTestOutput(ForkingRunListener.java:113)
   at org.apache.maven.surefire.api.booter.ForkingRunListener.writeTestOutput(ForkingRunListener.java:44)
   at org.apache.maven.surefire.junitplatform.RunListenerAdapter.writeTestOutput(RunListenerAdapter.java:379)
   at org.apache.maven.surefire.api.report.ConsoleOutputCapture$ForwardingPrintStream.println(ConsoleOutputCapture.java:144)
```

### Quarkus version or git rev

2.8.0+

**Comment by famod** [comment]
I see that nessie is using recently released 3.0.0-M6 auf surefire/failsafe, which suffers from https://issues.apache.org/jira/browse/SUREFIRE-2056

So this is not a Quarkus issue. You could consider downgrading to 3.0.0-M5.

**Comment by geoand** [comment]
Thanks for checking @famod !

**Comment by snazy** [comment]
Thanks @famod !
