### ISSUE TITLE
[Gradle] JWTAuthContextInfoProvider config not Inject

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#2503]
### application config 
```bash
### jwt
quarkus.smallrye-jwt.enabled=true
quarkus.smallrye-jwt.realm-name=Quarkus-JWT
quarkus.smallrye-jwt.auth-mechanism=MP-JWT
mp.jwt.verify.publickey.location=security/public.pem
mp.jwt.verify.issuer=https://quarkus.io/using-jwt-rbac
```

### error log
```bash
20:08:12,341 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:121)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:159)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:93)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl1.<clinit>(Unknown Source)
        ... 8 more
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at io.smallrye.jwt.config.JWTAuthContextInfoProvider.getContextInfo(JWTAuthContextInfoProvider.java:200)
        at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.create(Unknown Source)
        at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.get(Unknown Source)
        at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.get(Unknown Source)
        at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMethodExtension_Bean.create(Unknown Source)
        at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMethodExtension_Bean.get(Unknown Source)
        at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMethodExtension_Bean.get(Unknown Source)
        at io.quarkus.arc.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:310)
        at io.quarkus.arc.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:322)
        at io.quarkus.arc.ArcContainerImpl$1.get(ArcContainerImpl.java:201)
        at io.quarkus.arc.ArcContainerImpl$1.get(ArcContainerImpl.java:198)
        at io.quarkus.arc.runtime.ArcDeploymentTemplate$2$1.create(ArcDeploymentTemplate.java:86)
        at io.quarkus.arc.runtime.BeanContainer.instance(BeanContainer.java:35)
        at io.quarkus.smallrye.jwt.runtime.SmallRyeJwtTemplate.createAuthExtension(SmallRyeJwtTemplate.java:41)
        at io.quarkus.deployment.steps.SmallRyeJwtProcessor$registerJwtAuthExtension24.deploy(Unknown Source)
        ... 9 more
```

![image](https://user-images.githubusercontent.com/6096680/57969345-acad0e80-79a8-11e9-97fe-ac4c6cce9832.png)

**Comment by sberyozkin** [comment]
Hi @pipinet can you retry please with the latest Quarkus release ?
