### ISSUE TITLE
RestClientBuilderResolver not working with REST Client Reactive in plain unit tests

### ISSUE THREAD

**Issue by wjglerum** [quarkusio/quarkus#25041]
### Describe the bug

With the REST Client provided by RESTEasy Classic it's possible to manually obtain an implementation for your REST Client in a unit test without having to start Quarkus with a`@QuarkusTest` annotation. Now that we are trying to migrate our project to RESTEasy Reactive with Quarkus 2.8 we discovered that this approach no longer works for us.

Example code:
```java
package nl.wjglerum;

import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.core.WireMockConfiguration;
import io.quarkus.test.junit.QuarkusTest;
import org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.net.URI;
import java.net.URISyntaxException;

import static com.github.tomakehurst.wiremock.client.WireMock.*;

public class ExtensionServiceTest {

    static WireMockServer wireMockServer;
    static ExtensionService extensionService;

    @BeforeAll
    static void setup() throws URISyntaxException {
        WireMockConfiguration configuration = WireMockConfiguration.options().dynamicPort();
        wireMockServer = new WireMockServer(configuration);

        wireMockServer.stubFor(get(urlEqualTo("/extensions?id=io.quarkus%3Aquarkus-rest-client"))
                .willReturn(aResponse()
                        .withHeader("Content-Type", "application/json")
                        .withBody(
                                "[{" +
                                        "\"id\": \"io.quarkus:quarkus-rest-client\"," +
                                        "\"name\": \"REST Client\"" +
                                        "}]"
                        )));

        wireMockServer.start();

        extensionService = RestClientBuilderResolver.instance().newBuilder()
                .baseUri(new URI(wireMockServer.baseUrl()))
                .build(ExtensionService.class);
    }

    @Test
    void test() {
        Assertions.assertEquals("REST Client", extensionService.getById("io.quarkus:quarkus-rest-client").get(0).name);
    }
}
```

How would this approach be possible with the REST Client Reactive? We for example also use these stubs when we want to obtain an instance of a REST Client in our unit tests with Camel by extending from `CamelTestSupport` for those tests.

### Expected behavior

With REST Client Classic:

```
$ ./mvnw test -Dtest=ExtensionServiceTest
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< nl.wjglerum:quarkus-rest-client-wiremock >--------------
[INFO] Building quarkus-rest-client-wiremock 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ quarkus-rest-client-wiremock ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- quarkus-maven-plugin:2.8.1.Final:generate-code (default) @ quarkus-rest-client-wiremock ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ quarkus-rest-client-wiremock ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- quarkus-maven-plugin:2.8.1.Final:generate-code-tests (default) @ quarkus-rest-client-wiremock ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ quarkus-rest-client-wiremock ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/wjglerum/Documents/Dev/quarkus-rest-client-wiremock/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ quarkus-rest-client-wiremock ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M6:test (default-test) @ quarkus-rest-client-wiremock ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running nl.wjglerum.ExtensionServiceTest
2022-04-20 16:01:26,920 INFO  [wir.org.ecl.jet.uti.log] (main) Logging initialized @4822ms to wiremock.org.eclipse.jetty.util.log.Slf4jLog
2022-04-20 16:01:28,097 INFO  [wir.org.ecl.jet.ser.Server] (main) jetty-9.4.46.v20220331; built: 2022-03-31T16:38:08.030Z; git: bc17a0369a11ecf40bb92c839b9ef0a8ac50ea18; jvm 11.0.11+9
2022-04-20 16:01:28,150 INFO  [wir.org.ecl.jet.ser.han.ContextHandler] (main) Started w.o.e.j.s.ServletContextHandler@c4c0b41{/__admin,null,AVAILABLE}
2022-04-20 16:01:28,184 INFO  [wir.org.ecl.jet.ser.han.Con.ROOT] (main) RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
2022-04-20 16:01:28,186 INFO  [wir.org.ecl.jet.ser.han.ContextHandler] (main) Started w.o.e.j.s.ServletContextHandler@38548b19{/,null,AVAILABLE}
2022-04-20 16:01:28,272 INFO  [wir.org.ecl.jet.ser.AbstractConnector] (main) Started NetworkTrafficServerConnector@d1f74b8{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:64107}
2022-04-20 16:01:28,274 INFO  [wir.org.ecl.jet.ser.Server] (main) Started @6179ms
2022-04-20 16:01:28,330 WARN  [org.jbo.res.mic.cli.RestClientBuilderImpl] (main) CDI container is not available
2022-04-20 16:01:29,097 WARN  [org.jbo.res.mic.cli.RestClientBuilderImpl] (main) CDI container is not available
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.223 s - in nl.wjglerum.ExtensionServiceTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.332 s
[INFO] Finished at: 2022-04-20T16:01:30+02:00
[INFO] ------------------------------------------------------------------------
```

### Actual behavior

With REST Client Reactive:

```
$ ./mvnw test -Dtest=ExtensionServiceTest
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< nl.wjglerum:quarkus-rest-client-wiremock >--------------
[INFO] Building quarkus-rest-client-wiremock 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ quarkus-rest-client-wiremock ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- quarkus-maven-plugin:2.8.1.Final:generate-code (default) @ quarkus-rest-client-wiremock ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ quarkus-rest-client-wiremock ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- quarkus-maven-plugin:2.8.1.Final:generate-code-tests (default) @ quarkus-rest-client-wiremock ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ quarkus-rest-client-wiremock ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/wjglerum/Documents/Dev/quarkus-rest-client-wiremock/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ quarkus-rest-client-wiremock ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/wjglerum/Documents/Dev/quarkus-rest-client-wiremock/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ quarkus-rest-client-wiremock ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running nl.wjglerum.ExtensionServiceTest
2022-04-20 15:58:40,191 INFO  [wir.org.ecl.jet.uti.log] (main) Logging initialized @2215ms to wiremock.org.eclipse.jetty.util.log.Slf4jLog
2022-04-20 15:58:40,788 INFO  [wir.org.ecl.jet.ser.Server] (main) jetty-9.4.46.v20220331; built: 2022-03-31T16:38:08.030Z; git: bc17a0369a11ecf40bb92c839b9ef0a8ac50ea18; jvm 11.0.11+9
2022-04-20 15:58:40,812 INFO  [wir.org.ecl.jet.ser.han.ContextHandler] (main) Started w.o.e.j.s.ServletContextHandler@273842a6{/__admin,null,AVAILABLE}
2022-04-20 15:58:40,826 INFO  [wir.org.ecl.jet.ser.han.Con.ROOT] (main) RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
2022-04-20 15:58:40,827 INFO  [wir.org.ecl.jet.ser.han.ContextHandler] (main) Started w.o.e.j.s.ServletContextHandler@73877e19{/,null,AVAILABLE}
2022-04-20 15:58:40,867 INFO  [wir.org.ecl.jet.ser.AbstractConnector] (main) Started NetworkTrafficServerConnector@6d6bc158{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:64070}
2022-04-20 15:58:40,868 INFO  [wir.org.ecl.jet.ser.Server] (main) Started @2894ms
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.63 s <<< FAILURE! - in nl.wjglerum.ExtensionServiceTest
[ERROR] nl.wjglerum.ExtensionServiceTest  Time elapsed: 1.63 s  <<< ERROR!
java.lang.IllegalStateException: No RestClientBuilderResolver implementation found!
        at nl.wjglerum.ExtensionServiceTest.setup(ExtensionServiceTest.java:38)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ExtensionServiceTest.setup:38 ? IllegalState No RestClientBuilderResolver impl...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.265 s
[INFO] Finished at: 2022-04-20T15:58:41+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project quarkus-rest-client-wiremock: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/wjglerum/Documents/Dev/quarkus-rest-client-wiremock/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### How to Reproduce?

Follow the steps from the guides to define a REST Client and some tests:
- https://quarkus.io/guides/rest-client-reactive
- https://quarkus.io/guides/rest-client#using-a-mock-http-server-for-tests
[quarkus-rest-client-wiremock.zip](https://github.com/quarkusio/quarkus/files/8522171/quarkus-rest-client-wiremock.zip)

And see the example project [quarkus-rest-client-wiremock.zip](https://github.com/quarkusio/quarkus/files/8522197/quarkus-rest-client-wiremock.zip)

If you switch to the REST Client Reactive the test fails.

### Output of `uname -a` or `ver`

`Darwin Willems-MBP 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64`

### Output of `java -version`

`openjdk version "11.0.11" 2021-04-20`

### Quarkus version or git rev

`2.8.1`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

`Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)`

### Additional information

I also tried to instantiate the builder provided by the REST Client Reactive, however that resulted in a `NullPointerException` towards ArC. I guess that makes sense as we don't have an active Quarkus application.

```java
        extensionService = new RestClientBuilderImpl()
                .baseUri(new URI(wireMockServer.baseUrl()))
                .build(ExtensionService.class);
```

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.12 s <<< FAILURE! - in nl.wjglerum.ExtensionServiceTest
[ERROR] nl.wjglerum.ExtensionServiceTest  Time elapsed: 1.12 s  <<< ERROR!
java.lang.NullPointerException
        at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:285)
```

**Comment by michalszynkiewicz** [comment]
At this moment quarkus rest client reactive is not meant to be used standalone.
Are you trying to workaround some problem by using the client outside a quarkus test?

**Comment by geoand** [comment]
As Michal mentions, the Reactive REST cannot be used outside of Quarkus (and will likely never be made to do so), so I am going to close this.

**Comment by wjglerum** [comment]
Thanks for the extra info! Makes total sense.
