### ISSUE TITLE
Fail to inject multiple bean with Kotlin and 2.8.1.Final 

### ISSUE THREAD

**Issue by debop** [quarkusio/quarkus#25060]
### Describe the bug

In Quarkus 2.7.5.Final is success, but 2.8.1.Final is failed.

```kotlin
    interface ColorService {
        val color: String
    }

    @Singleton
    @Named("red")
    class RedColorService: ColorService {
        override val color: String = "red"
    }

    @Singleton
    @Named("blue")
    class BlueColorService: ColorService {
        override val color: String = "blue"
    }

    /**
     * [ColorService]의 모든 Service 를 inject 받는다
     *
     * 참고: [Injecting Multiple Bean Instances Intuituvely](https://quarkus.io/guides/cdi-reference#injecting-multiple-bean-instances-intuitively)
     *
     * FIXME: Quarkus 2.7.5에서는 동작하는데, Quarkus 2.8.1 에서 동작하지 않는다
     */
    @Inject
    @All
    internal lateinit var colorServices: List<CDITest.ColorService>
``` 

### Expected behavior

`colorServices` is injected

### Actual behavior

Error raise like this

```
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DefinitionException: Wildcard is not a legal type argument for org.acme.cdi.CDITest#colorServices
	at io.quarkus.arc.deployment.ArcProcessor.registerSyntheticObservers(ArcProcessor.java:446)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:116)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:157)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
	... 62 more
Caused by: javax.enterprise.inject.spi.DefinitionException: Wildcard is not a legal type argument for org.acme.cdi.CDITest#colorServices
	at io.quarkus.arc.deployment.ArcProcessor.registerSyntheticObservers(ArcProcessor.java:446)
	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.14/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.14/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Output of `java -version`

openjdk 11.0.14

### GraalVM version (if different from Java)

GrallVM CE 22.0.0.2

### Quarkus version or git rev

2.8.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.4.2

**Comment by geoand** [comment]
cc @mkouba @manovotn

**Comment by geoand** [comment]
>  Maybe we should backport it.

Sounds reasonable
