### ISSUE TITLE
Kafka emitter unusable within imperative code (both imperative and emitter are mandatory)

### ISSUE THREAD

**Issue by lamemind-ud** [quarkusio/quarkus#25066]
### Describe the bug

Started happily coding Quarkus, the imperative way.
I already have a multi project / multi repo architecture that works in production.
I'm using multiple named PUs, and panache repositories.

Then I need to do the following
- start in a `@Scheduled` method
- read database (imperative), with `@Transactional` of course
- emit a Kafka event with `Emitter`
- write database (imperative)

Here the pain starts

## 1. The `@Scheduled` method throws an exception
`Enlisted connection used without active transaction`
see https://github.com/quarkusio/quarkus/issues/22834

## 2. No proper way to switch back to imperative
`emitter.send(user).thenAccept(` is reactive, so there is no transaction here.
How do I switch back to imperative?

## 3. Managed to work with `EventBus` (very ugly solution), but still have an exception
From the async context I call `EventBus.send`, that way I switch back to imperative and can write into database.
See https://github.com/quarkusio/quarkus/issues/22834#issuecomment-1094308403
It's an ugly solution, and still the  `@Scheduled` method throws the exception

##  4. Tryed with `Reactive panache` - Quarkus won't start
**Are Hibernate `Reactive` and `Imperative` compatible to each other??**

I added `quarkus-hibernate-reactive-panache` extension and the following code, but quarkus won't start.
~~~
Panache.withTransaction(() -> {
    sysOutboundEventRepository.setSentToKafka(sysOutboundEvent);
    return null;
});
~~~

Quarkus fails to start with the following exception
~~~
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManagerFactory and qualifiers [@Default]
        - java member: io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer#emf
        - declared on CLASS bean [types=[io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer]
        The following beans match by type, but none have matching qualifiers:
                - Bean [class=org.hibernate.SessionFactory, qualifiers=[@io.quarkus.hibernate.orm.PersistenceUnit(value = "frontend"), @Named(value = "frontend"), @Any]]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:411)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:527)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:263)
        ... 13 more
~~~

### Expected behavior

- As of point 2, I expect there should be a proper way to switch from imperative to reactive and back.
- As of point 1, I expect there should be a way to avoid the exception.
- As of point 3, I expect hibernate `imperative` and `reactive` to coexists.

### Quarkus version or git rev

2.8.0 Final

### Additional information

Maybe there is no _real_ bug, but the fact I'm spending more than 1h to do that simple thing should be indicative that something's wrong... actually I spent much more time circling the problem...

Please folks, let's assume we are not all reactive experts, nor quarkus experts.
We need more in-deep docs, and more complex examples.

Thanks

**Comment by lamemind-ud** [comment]
Just to be clear, I'm really satisfied having choose Quarkus... and I'm thankful to to you guys for the incredible tool you made.

But this single problem got me swearing quite a bit. If from my post I seem aggressive or rude, I'm very sorry

**Comment by cescoffier** [comment]
You need to 'join' on the emitter send method:

emitter.send(...).toCompletableFuture().join();

Also, in 2.9, you will be able to return a Uni from an @Scheduled method. The. You will be able to return the Uni produced by the MutinyEmitter send method.

**Comment by cescoffier** [comment]
I need to check, but I believe (maybe wrongly) that this is documented in the kafka reference guide.

**Comment by lamemind-ud** [comment]
Hello @cescoffier ,

`emitter.send(...).toCompletableFuture().join();` is exactly what I was looking for.
I should have RTFM before posting this... like the following: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.1/emitter/emitter.html#emitter-payloads

There's a lot to know and study, actually, and I'm still new in the Enterprise Java in general... 
At the time I first posted this bug, I didn't find the right doc at the right moment and my head blown up.

My bad.

Just a last question... `4. Tryed with Reactive panache - Quarkus won't start`
Are Hibernate Reactive and Imperative compatible to each other?? Does they work in the same project?

**Comment by jpmaas** [comment]
> emitter.send(...).toCompletableFuture().join(); is exactly what I was looking for.
> I should have RTFM before posting this... like the following: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.1/emitter/emitter.html#emitter-payloads

While this works for situations where you only sent payloads, this runs into issues if you need to send messages with custom metadata due to e.g. custom topics to be sent to. According to the documentation, this should be done using this emitter.send(...).toCompletableFuture().join(); is exactly what I was looking for.
I should have RTFM before posting this... like the following: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.1/emitter/emitter.html#emitter-payloads. However, this does not actually wait for the completion of the message, just customizes the handling of ACKs and NACKs.

I think there should be stronger emphasize in the documentation at least that this should not be run in transactions - or should provide an option to handle that when sending messages as well. Maybe I am also missing something and missed a crucial part of the documentation there, so any advice would be appreciated. For now, I will circumvent that by sending the message outside of the transaction.

**Comment by marutzen** [comment]
> > emitter.send(...).toCompletableFuture().join(); is exactly what I was looking for.
> > I should have RTFM before posting this... like the following: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.1/emitter/emitter.html#emitter-payloads
> 
> While this works for situations where you only sent payloads, this runs into issues if you need to send messages with custom metadata due to e.g. custom topics to be sent to. According to the documentation, this should be done using this https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.1/emitter/emitter.html#emitter-messages. However, this does not actually wait for the completion of the message, just customizes the handling of ACKs and NACKs.
> 
> I think there should be stronger emphasize in the documentation at least that this should not be run in transactions - or should provide an option to handle that when sending messages as well. Maybe I am also missing something and missed a crucial part of the documentation there, so any advice would be appreciated. For now, I will circumvent that by sending the message outside of the transaction.

I'm having this problem right now. Any tips?
