### ISSUE TITLE
ClassCastException related to Maps on Parameterized test on 2.8.1.Final on Java 11

### ISSUE THREAD

**Issue by xtaixe** [quarkusio/quarkus#25073]
### Describe the bug

Parameterized tests dealing with objects that have maps as fields break when upgrading from `2.8.0.Final` to `2.8.1.Final` (at least on Java 11).

```java
@QuarkusTest
class ReproducerTest {

    static Stream<Arguments> arguments() {
        return Stream.of(
                Arguments.of(new TestObject1()),
                Arguments.of(new TestObject2()));
    }

    @ParameterizedTest
    @MethodSource("arguments")
    void map(Object o) {

    }

    static class TestObject1 {

        private final Map<String, String> map = Collections.emptyMap();

        Map<String, String> getMap() {
            return map;
        }

    }

    static class TestObject2 {

        private final Map<String, String> map = Map.of();

        Map<String, String> getMap() {
            return map;
        }

    }

}
```

gives the following errors:

```
java.lang.ClassCastException: class java.util.Collections$EmptyMap cannot be cast to class java.util.Collection (java.util.Collections$EmptyMap and java.util.Collection are in module java.base of loader 'bootstrap')

	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
```

```
java.lang.ClassCastException: class java.util.ImmutableCollections$Map1 cannot be cast to class java.util.Collection (java.util.ImmutableCollections$Map1 and java.util.Collection are in module java.base of loader 'bootstrap')

	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
```

### Output of `uname -a` or `ver`

Darwin xtaixe 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.14" 2022-01-18 OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05) OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05, mixed mode, sharing)

### Quarkus version or git rev

2.8.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5

**Comment by gsmet** [comment]
@geoand this is probably related to the Xstream changes.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/25084 fixes the issue
