### ISSUE TITLE
NullPointer during Rest client creation when micrometer is disabled

### ISSUE THREAD

**Issue by danielmaison** [quarkusio/quarkus#25099]
### Describe the bug

NullPointer is thrown if micrometer is included but disabled when RestClient is created.

### Expected behavior

Application to work as usual, but without metrics reported

### Actual behavior

Nullpointer during RestClient creation

```
Caused by: java.lang.NullPointerException
    at io.quarkus.micrometer.runtime.binder.RestClientMetricsListener.prepClientMetrics(RestClientMetricsListener.java:50)
    at io.quarkus.micrometer.runtime.binder.RestClientMetricsListener.onNewClient(RestClientMetricsListener.java:38)
    at io.quarkus.restclient.runtime.QuarkusRestClientBuilder.lambda$build$0(QuarkusRestClientBuilder.java:236)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
    at io.quarkus.restclient.runtime.QuarkusRestClientBuilder.build(QuarkusRestClientBuilder.java:236)
    at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:72)
```

### How to Reproduce?

Reproducing project:
https://github.com/danielmaison/quarkus-micrometer-bug

Simple Quarkus project generated with Quarkus 2.8.1.Final and extensions:

* quarkus-resteasy (classic)
* quarkus-resteasy-jsonb
* quarkus-rest-client-jsonb
* quarkus-micrometer-registry-prometheus

**Changes made to sample code**
1. application.properties - disabled micrometer
2. Added Rest client interface with empty get method
3. In Server rest resource, inject rest client

Reproduce by: Calling server resource (e.g. via test)

### Output of `uname -a` or `ver`

Linux Desktop 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 11.0.14.1 2022-02-08 OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04) OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.8.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by danielmaison** [comment]
Thank you for your quick response <3

**Comment by geoand** [comment]
Thanks for the reproducer, it was most helpful :)
