### ISSUE TITLE
Confusing test output from vertx-http deployment tests (it looks like a failure, but isn't)

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus#25105]
### Describe the bug

A number of apparent errors are present in the test logs. These aren't real problems, since the tests are testing the testing, but someone would need to understand the test suite to know that. These errors increase the cognitive load of reading the build logs and could cause confusion. 

I think we can make the logs a big clearer while still testing the right things. 

- *Option 1* (very cheap): Rename some test class names and strings. This makes the intention clearer to people reading the logs. For example,  "hello-this-is-expected-to-fail" and the class names things like "ParamETWhichShouldFail".
- *Option 2* (slightly more work): Amend `QuarkusDevModeTest` to write the dev mode logs only when an assertion fails.

I think the two options are complementary, so we could do the easy one first and then look into suppressing the output.

(I can see similar output in io.quarkus.amazon.lambda.deployment.testing.LambdaHandlerET.)

### Expected behavior

All test failures reported in the logs should represent real problems. 

### Actual behavior

A number of apparent errors are present in the test logs. These aren't real problems, since the tests are testing the testing, but someone would need to understand the test suite to know that. 

```
2022-04-22T02:58:24.3227607Z 2022-04-22 02:58:24,237 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #1 ====================
2022-04-22T02:58:24.3228349Z 2022-04-22 02:58:24,237 ERROR [io.qua.test] (Test runner thread) Test SimpleET#testHelloEndpoint() failed 
2022-04-22T02:58:24.3228834Z : java.lang.AssertionError: 1 expectation failed.
2022-04-22T02:58:24.3229226Z Expected status code <200> but was <404>.
```
```
2022-04-22T02:58:33.7610222Z 2022-04-22 02:58:32,085 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #2 ====================
2022-04-22T02:58:33.7610914Z 2022-04-22 02:58:32,086 ERROR [io.qua.test] (Test runner thread) Test DuplicateSimpleET#testHelloEndpoint() failed 
2022-04-22T02:58:33.7611480Z : java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
2022-04-22T02:58:33.7612184Z 	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:632)
```
```
2022-04-22T02:58:51.0344609Z 2022-04-22 02:58:46,825 ERROR [io.qua.test] (Test runner thread) Test UnitET#unitStyleTest() failed 
2022-04-22T02:58:51.0345132Z : org.opentest4j.AssertionFailedError: expected: <Hi> but was: <hello>
2022-04-22T02:58:51.0345674Z 	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
```
```
2022-04-22T02:58:51.0408787Z 2022-04-22 02:58:46,825 ERROR [io.qua.test] (Test runner thread) Test UnitET#unitStyleTest2() failed 
2022-04-22T02:58:51.0409317Z : org.opentest4j.AssertionFailedError: expected: <UNIT> but was: <unit>
```
```
2022-04-22T02:58:35.7188807Z 2022-04-22 02:58:35,588 INFO  [io.quarkus] (Test runner thread) quarkus-vertx-http-deployment(test application) stopped in 0.010s
2022-04-22T02:58:35.7189738Z 2022-04-22 02:58:35,591 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #4 ====================
2022-04-22T02:58:35.7190808Z 2022-04-22 02:58:35,592 ERROR [io.qua.test] (Test runner thread) Test SimpleET#testHelloEndpoint() failed 
2022-04-22T02:58:35.7191458Z : java.lang.AssertionError: 1 expectation failed.
2022-04-22T02:58:35.7192255Z Expected status code <200> but was <404>.
```

### How to Reproduce?

```
cd /Users/holly/Code/quarkus/main/quarkus/extensions/vertx-http/deployment
mvn -Dquickly -DskipTests=false
```

**Comment by cescoffier** [comment]
They aren't failures, they are testing that we recover gracefully after an issue in dev mode.

**Comment by cescoffier** [comment]
I would go for option 1.

**Comment by geoand** [comment]
+1 for option 1
