### ISSUE TITLE
`-Dquarkus.platform.version` is not honored during reload of dev mode 

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#25184]
### Describe the bug

Custom `-Dquarkus.platform.version` is not honored during reload of dev mode, version defined in pom.xml gets picked 

I have triggered the reload by removal of `quarkus-arc` dependency from pom.xml
Dev mode was started using `mvn quarkus:dev -Dquarkus.platform.version=2.7.5.Final`

Once the change of `pom.xml` was detected I had seen a lot of downloads of 2.8.2.Final bits and then the  dev mode exited saying that the version of Quarkus was changed.

```
...
                                                                                                                                                                                Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-core-deployment/2.8.2.Final/quarkus-core-deployment-2.8.2.Final.jar (1.2 MB at 959 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-vertx-http-deployment/2.8.2.Final/quarkus-vertx-http-deployment-2.8.2.Final.jar (2.2 MB at 1.4 MB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-bootstrap-gradle-resolver/2.8.2.Final/quarkus-bootstrap-gradle-resolver-2.8.2.Final.jar (2.4 MB at 1.5 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/platform/quarkus-bom-quarkus-platform-properties/2.8.2.Final/quarkus-bom-quarkus-platform-properties-2.8.2.Final.properties
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/platform/quarkus-bom-quarkus-platform-properties/2.8.2.Final/quarkus-bom-quarkus-platform-properties-2.2022-04-26 22:28:55,037 INFO  [io.quarkus] (Shutdown thread) code-with-quarkus stopped in 0.024s


--
Press [:] for the terminal, [h] for more options>
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Hot deployment of the application is not supported when updating the Quarkus version. The application needs to be stopped and dev mode started up again
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:138)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Hot deployment of the application is not supported when updating the Quarkus version. The application needs to be stopped and dev mode started up again
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:143)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:96)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
	... 1 more
Caused by: java.lang.IllegalStateException: Hot deployment of the application is not supported when updating the Quarkus version. The application needs to be stopped and dev mode started up again
	at io.quarkus.deployment.dev.IsolatedDevModeMain.close(IsolatedDevModeMain.java:367)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:512)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:68)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:140)
	... 3 more
```

As the application in the dev mode runs using the version specified using `-Dquarkus.platform.version=` property I would expect the same version to be used after reload

### Expected behavior

Custom `-Dquarkus.platform.version` is honored during reload of dev mode

### Actual behavior

Custom `-Dquarkus.platform.version` is not honored during reload of dev mode, version defined in pom.xml gets picked 

### How to Reproduce?

 - download app from https://code.quarkus.io/?e=resteasy-reactive
 - open pom.xml
 - run `mvn quarkus:dev -Dquarkus.platform.version=2.7.5.Final`
 - remove `quarkus-arc` dependency 
 - check the console

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.8.2.Final

**Comment by rsvoboda** [comment]
@aloubyansky / @stuartwdouglas any idea if this can be easily solved?

**Comment by geoand** [comment]
Let me take a quick look and see if this can be fixed easily

**Comment by aloubyansky** [comment]
I just reproduced it too.

**Comment by geoand** [comment]
Actually, this is probably not something that we want to support, as the code running the Quarkus plugin isn't "reloaded", so you could end up with different Quarkus versions

**Comment by rsvoboda** [comment]
`mvn quarkus:dev -Dquarkus.platform.version=2.7.5.Final` uses the 2.7.5.Final plugin, I see `[INFO] --- quarkus-maven-plugin:2.7.5.Final:dev (default-cli) @ code-with-quarkus ---` in log

**Comment by geoand** [comment]
Hold on, I think I was thinking of something else...

**Comment by geoand** [comment]
That's likely because the system property is not available when the application is relaunched

**Comment by aloubyansky** [comment]
The resolution happens in the DevMojo itself before we launch the app process. It should be available.

**Comment by geoand** [comment]
Ah, ok.

**Comment by aloubyansky** [comment]
It's related to RepositorySystemSession initialization. On the first boot we re-use the original Maven-provided one. On a POM change we are creating a new instance, because we need to re-initialize it to take into account POM changes and this is where we loose the system property.
