### ISSUE TITLE
ClassNotFound Quarkus BootStrap with Kogito and Marshalling error Protobuf marshaller

### ISSUE THREAD

**Issue by debu999** [quarkusio/quarkus#25198]
### Describe the bug

If we have a process variable in kogito app as java.util.List<org.doogle.kogito.Sample> it throws ClassNotFound Error when running in Dev Mode.
java.lang.ClassNotFoundException: org.doogle.kogito.Sample

@evacchi need some help to overcome this.

### Expected behavior

The system should auto discover and register the classes in QuarkusClassLoader. Need not throw error for native mode.

### Actual behavior

ERROR Full Stack Tracke

> 2022-04-27 17:53:22,185 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /pr failed, error id: cabdea56-2320-43ea-9c72-007f0905a210-1: org.kie.kogito.serialization.process.ProcessInstanceMarshallerException: Error while unmarshalling process instance
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallProcessInstance(ProcessInstanceMarshallerService.java:124)
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallReadOnlyProcessInstance(ProcessInstanceMarshallerService.java:133)
	at org.kie.kogito.mongodb.MongoDBProcessInstances.unmarshall(MongoDBProcessInstances.java:102)
	at org.kie.kogito.mongodb.MongoDBProcessInstances.values(MongoDBProcessInstances.java:94)
	at org.kie.kogito.process.ProcessInstances.values(ProcessInstances.java:30)
	at org.kie.kogito.process.impl.ProcessServiceImpl.getProcessInstanceOutput(ProcessServiceImpl.java:94)
	at com.example.PrResource.getResources_pr(PrResource.java:83)
	at com.example.PrResource_Subclass.getResources_pr$$superforward1(Unknown Source)
	at com.example.PrResource_Subclass$$function$$35.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.example.PrResource_Subclass.getResources_pr(Unknown Source)
	at com.example.PrResource_ClientProxy.getResources_pr(Unknown Source)
	at com.example.PrResource$quarkusrestinvoker$getResources_pr_756fcda70e20ec9af95114c348d21c591347d9e0.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:548)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.kie.kogito.serialization.process.ProcessInstanceMarshallerException: Unexpected error while trying to read object
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.readObject(ProtobufObjectMarshallerStrategy.java:79)
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.unmarshall(ProtobufObjectMarshallerStrategy.java:69)
	at org.kie.kogito.serialization.process.impl.ProtobufVariableReader.buildVariables(ProtobufVariableReader.java:44)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildWorkItemNodeInstance(ProtobufProcessInstanceReader.java:478)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildNodeInstance(ProtobufProcessInstanceReader.java:249)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildWorkflow(ProtobufProcessInstanceReader.java:164)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.read(ProtobufProcessInstanceReader.java:115)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceMarshaller.readProcessInstance(ProtobufProcessInstanceMarshaller.java:47)
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallProcessInstance(ProcessInstanceMarshallerService.java:122)
	... 28 more
Caused by: java.lang.ClassNotFoundException: org.doogle.kogito.Sample
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:438)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:778)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2045)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1909)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2235)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at java.base/java.util.ArrayList.readObject(ArrayList.java:899)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2434)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2268)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.readObject(ProtobufObjectMarshallerStrategy.java:77)
	... 36 more

2022-04-27 17:53:22,190 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: org.kie.kogito.serialization.process.ProcessInstanceMarshallerException: Error while unmarshalling process instance
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallProcessInstance(ProcessInstanceMarshallerService.java:124)
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallReadOnlyProcessInstance(ProcessInstanceMarshallerService.java:133)
	at org.kie.kogito.mongodb.MongoDBProcessInstances.unmarshall(MongoDBProcessInstances.java:102)
	at org.kie.kogito.mongodb.MongoDBProcessInstances.values(MongoDBProcessInstances.java:94)
	at org.kie.kogito.process.ProcessInstances.values(ProcessInstances.java:30)
	at org.kie.kogito.process.impl.ProcessServiceImpl.getProcessInstanceOutput(ProcessServiceImpl.java:94)
	at com.example.PrResource.getResources_pr(PrResource.java:83)
	at com.example.PrResource_Subclass.getResources_pr$$superforward1(Unknown Source)
	at com.example.PrResource_Subclass$$function$$35.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.example.PrResource_Subclass.getResources_pr(Unknown Source)
	at com.example.PrResource_ClientProxy.getResources_pr(Unknown Source)
	at com.example.PrResource$quarkusrestinvoker$getResources_pr_756fcda70e20ec9af95114c348d21c591347d9e0.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:548)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.kie.kogito.serialization.process.ProcessInstanceMarshallerException: Unexpected error while trying to read object
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.readObject(ProtobufObjectMarshallerStrategy.java:79)
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.unmarshall(ProtobufObjectMarshallerStrategy.java:69)
	at org.kie.kogito.serialization.process.impl.ProtobufVariableReader.buildVariables(ProtobufVariableReader.java:44)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildWorkItemNodeInstance(ProtobufProcessInstanceReader.java:478)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildNodeInstance(ProtobufProcessInstanceReader.java:249)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildWorkflow(ProtobufProcessInstanceReader.java:164)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.read(ProtobufProcessInstanceReader.java:115)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceMarshaller.readProcessInstance(ProtobufProcessInstanceMarshaller.java:47)
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallProcessInstance(ProcessInstanceMarshallerService.java:122)
	... 28 more
Caused by: java.lang.ClassNotFoundException: org.doogle.kogito.Sample
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:438)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:778)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2045)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1909)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2235)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at java.base/java.util.ArrayList.readObject(ArrayList.java:899)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2434)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2268)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.readObject(ProtobufObjectMarshallerStrategy.java:77)
	... 36 more

2022-04-27 17:54:06,226 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /pr/cb7d086a-e2dc-4863-8a24-c91faf4469a8 failed, error id: cabdea56-2320-43ea-9c72-007f0905a210-2: org.kie.kogito.serialization.process.ProcessInstanceMarshallerException: Error while unmarshalling process instance
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallProcessInstance(ProcessInstanceMarshallerService.java:124)
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallReadOnlyProcessInstance(ProcessInstanceMarshallerService.java:133)
	at org.kie.kogito.mongodb.MongoDBProcessInstances.unmarshall(MongoDBProcessInstances.java:102)
	at org.kie.kogito.mongodb.MongoDBProcessInstances.findById(MongoDBProcessInstances.java:79)
	at org.kie.kogito.process.impl.ProcessServiceImpl.findById(ProcessServiceImpl.java:103)
	at com.example.PrResource.getResource_pr(PrResource.java:99)
	at com.example.PrResource_Subclass.getResource_pr$$superforward1(Unknown Source)
	at com.example.PrResource_Subclass$$function$$28.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.example.PrResource_Subclass.getResource_pr(Unknown Source)
	at com.example.PrResource_ClientProxy.getResource_pr(Unknown Source)
	at com.example.PrResource$quarkusrestinvoker$getResource_pr_61ce85c208747caf9fed63af94a2155306cb3e0f.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:548)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.kie.kogito.serialization.process.ProcessInstanceMarshallerException: Unexpected error while trying to read object
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.readObject(ProtobufObjectMarshallerStrategy.java:79)
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.unmarshall(ProtobufObjectMarshallerStrategy.java:69)
	at org.kie.kogito.serialization.process.impl.ProtobufVariableReader.buildVariables(ProtobufVariableReader.java:44)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildWorkItemNodeInstance(ProtobufProcessInstanceReader.java:478)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildNodeInstance(ProtobufProcessInstanceReader.java:249)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildWorkflow(ProtobufProcessInstanceReader.java:164)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.read(ProtobufProcessInstanceReader.java:115)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceMarshaller.readProcessInstance(ProtobufProcessInstanceMarshaller.java:47)
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallProcessInstance(ProcessInstanceMarshallerService.java:122)
	... 27 more
Caused by: java.lang.ClassNotFoundException: org.doogle.kogito.Sample
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:438)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:778)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2045)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1909)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2235)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at java.base/java.util.ArrayList.readObject(ArrayList.java:899)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2434)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2268)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.readObject(ProtobufObjectMarshallerStrategy.java:77)
	... 35 more

2022-04-27 17:54:06,229 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: org.kie.kogito.serialization.process.ProcessInstanceMarshallerException: Error while unmarshalling process instance
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallProcessInstance(ProcessInstanceMarshallerService.java:124)
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallReadOnlyProcessInstance(ProcessInstanceMarshallerService.java:133)
	at org.kie.kogito.mongodb.MongoDBProcessInstances.unmarshall(MongoDBProcessInstances.java:102)
	at org.kie.kogito.mongodb.MongoDBProcessInstances.findById(MongoDBProcessInstances.java:79)
	at org.kie.kogito.process.impl.ProcessServiceImpl.findById(ProcessServiceImpl.java:103)
	at com.example.PrResource.getResource_pr(PrResource.java:99)
	at com.example.PrResource_Subclass.getResource_pr$$superforward1(Unknown Source)
	at com.example.PrResource_Subclass$$function$$28.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.example.PrResource_Subclass.getResource_pr(Unknown Source)
	at com.example.PrResource_ClientProxy.getResource_pr(Unknown Source)
	at com.example.PrResource$quarkusrestinvoker$getResource_pr_61ce85c208747caf9fed63af94a2155306cb3e0f.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:548)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.kie.kogito.serialization.process.ProcessInstanceMarshallerException: Unexpected error while trying to read object
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.readObject(ProtobufObjectMarshallerStrategy.java:79)
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.unmarshall(ProtobufObjectMarshallerStrategy.java:69)
	at org.kie.kogito.serialization.process.impl.ProtobufVariableReader.buildVariables(ProtobufVariableReader.java:44)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildWorkItemNodeInstance(ProtobufProcessInstanceReader.java:478)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildNodeInstance(ProtobufProcessInstanceReader.java:249)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildWorkflow(ProtobufProcessInstanceReader.java:164)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.read(ProtobufProcessInstanceReader.java:115)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceMarshaller.readProcessInstance(ProtobufProcessInstanceMarshaller.java:47)
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallProcessInstance(ProcessInstanceMarshallerService.java:122)
	... 27 more
Caused by: java.lang.ClassNotFoundException: org.doogle.kogito.Sample
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:438)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:778)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2045)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1909)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2235)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at java.base/java.util.ArrayList.readObject(ArrayList.java:899)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2434)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2268)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at org.kie.kogito.serialization.process.impl.marshallers.ProtobufObjectMarshallerStrategy.readObject(ProtobufObjectMarshallerStrategy.java:77)
	... 35 more

### How to Reproduce?

Clone the repo https://github.com/debu999/kogito-samples.git
it has a simple bpmn and just a reproducer
<img width="1343" alt="Screenshot 2022-04-27 at 6 04 33 PM" src="https://user-images.githubusercontent.com/1910577/165519132-16df4f37-b4d1-4826-acc8-07809b902ec8.png">
It only have a java.util.List<org.doogle.kogito.Sample>
The marshalling works fine and the payload is fine and rest api works fine. Post and PUT works but Get do not work.

The protofile registered in data index do not show it as array for  variable samplelist. Need some help to have list object in the process.

### Output of `uname -a` or `ver`

Darwin Debabratas-MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05) OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.5

### Additional information

Need to know how to add single file to classloader in case its not detected. The error we get is in dev mode only and not sure why it is happening only if we have a list in kogito process.

**Comment by debu999** [comment]
We are trying to get the data and i see the supported options.nList  of Java objects is supported. Need help
<img width="1034" alt="Screenshot 2022-04-27 at 6 10 29 PM" src="https://user-images.githubusercontent.com/1910577/165520069-6a008070-f49f-4379-a908-38812d5a50a5.png">

**Comment by evacchi** [comment]
I think @cristianonicolai is probably the better person to answer this :)

**Comment by debu999** [comment]
DataIndex never shows list not sure if this is a bug ....

**Comment by debu999** [comment]
@cristianonicolai @evacchi how to have data index generate array for repeated object in proto file

**Comment by debu999** [comment]
https://issues.redhat.com/browse/KOGITO-6892
It fixed the issue with list persistence but data index do not show list and only register single object

**Comment by debu999** [comment]
I feel this can be closed as kogito don't aupport list of Java objects but java object with list if java objects.

**Comment by debu999** [comment]
Closing the issue...
