### ISSUE TITLE
Reactive Routes - "Response head already sent" when I try to add response headers

### ISSUE THREAD

**Issue by lucaspouzac** [quarkusio/quarkus#25232]
### Describe the bug

When I use Reactive Routes, I randomly get an exception when adding header to my response and header are not added.

```java
package org;

import io.quarkus.vertx.web.Route;
import io.smallrye.mutiny.Uni;

import io.smallrye.mutiny.infrastructure.Infrastructure;
import io.vertx.core.http.HttpClientOptions;
import io.vertx.core.http.RequestOptions;
import io.vertx.ext.web.RoutingContext;
import io.vertx.mutiny.core.Vertx;
import io.vertx.mutiny.core.buffer.Buffer;
import io.vertx.mutiny.core.http.HttpClient;
import io.vertx.mutiny.core.http.HttpClientRequest;
import io.vertx.mutiny.core.http.HttpClientResponse;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

@ApplicationScoped
public class ProxyRoute {

    private final HttpClient client;

    @Inject
    public ProxyRoute(Vertx vertx) {
        this.client = vertx.createHttpClient(new HttpClientOptions()
                .setDefaultHost("localhost")
                .setDefaultPort(8181)
                .setTryUseCompression(true));
    }

    @Route(regex = "^.*$")
    Uni<Buffer> all(RoutingContext rc) {
        // Copy method, uri and headers of proxy request to api request
        RequestOptions requestOptions = new RequestOptions();
        requestOptions.setMethod(rc.request().method());
        requestOptions.setURI(rc.request().uri());
        requestOptions.setHeaders(rc.request().headers());

        // Send api request
        Uni<HttpClientResponse> response = client.request(requestOptions)
            .flatMap(HttpClientRequest::send);

        // Copy response header of API to proxy response
        response.subscribe().with(resp -> {
            resp.headers().forEach((key, values) -> {
                rc.response().putHeader(key, values);
            });
        });

        // Get API response
        Uni<Buffer> result = response.flatMap(HttpClientResponse::body);

        // Process after return result - async
        result.subscribe().with(buffer -> {
            Uni.createFrom()
                    .item(buffer)
                    .emitOn(Infrastructure.getDefaultWorkerPool())
                    .subscribe()
                    .with(System.out::println, Throwable::printStackTrace);
        });

        // Send response
        return result;
    }
}
```

### Expected behavior

Headers correctly added

### Actual behavior

Headers are added randomly.

```
2022-04-28 16:50:10,689 ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-1) Mutiny had to drop the following exception: java.lang.IllegalStateException: Response head already sent
	at io.vertx.core.http.impl.Http1xServerResponse.checkHeadWritten(Http1xServerResponse.java:681)
	at io.vertx.core.http.impl.Http1xServerResponse.putHeader(Http1xServerResponse.java:193)
	at io.vertx.core.http.impl.Http1xServerResponse.putHeader(Http1xServerResponse.java:68)
	at org.ProxyRoute.lambda$all$0(ProxyRoute.java:47)
	at io.vertx.core.MultiMap$1.accept(MultiMap.java:84)
	at io.vertx.core.MultiMap$1.accept(MultiMap.java:81)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.vertx.core.MultiMap.forEach(MultiMap.java:81)
	at io.vertx.mutiny.core.MultiMap.forEach(MultiMap.java:232)
```

### Output of `uname -a` or `ver`

Linux xxx 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)

### Quarkus version or git rev

2.8.1.Final

**Comment by lucaspouzac** [comment]
Same problem with 2.9.1.Final

**Comment by pipinet** [comment]
Same problem with 2.13.3.Final

**Comment by cescoffier** [comment]
Are you sure it's the same issue? Looking at your stack trace it's not. I think you should open a new issue with a standalone reproducer.
