### ISSUE TITLE
NullPointerException in RestEasy Reactive with 2.9.0.CR1

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#25246]
### Describe the bug

I just upgrade our service to Quarkus 2.9.0.CR1 and made a call to the Rest API. I now always get the following NullPointerException:

```
2022-04-29 10:43:28,929 SEVERE [com.adi.ret.err.ApplicationExceptionMapper] (vert.x-eventloop-thread-3) Error: java.lang.NullPointerException
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveCompressionHandler.handle(ResteasyReactiveCompressionHandler.java:52)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveCompressionHandler.handle(ResteasyReactiveCompressionHandler.java:14)
```

When I debug into that location, I see that `requestContext.getResponseContentType()` returns null. The reason seems to be that the `headers` field in the `response` only contains a single `Cache-Control` header. We have defined the content type of the response with the `@Produces(MediaType.APPLICATION_JSON)` annotation. Maybe the compression handler is applied before the headers are added?

Our resteasy reactive endpoint is a simple @GET as a kotlin suspend function.

**Comment by geoand** [comment]
Can you attach a reproducer please?

Thanks

**Comment by andreas-eberle** [comment]
To reproduce: 

1. download and unzip the reproducer [2022-04-29_resteasy-reactive-nullpointer.zip](https://github.com/quarkusio/quarkus/files/8590958/2022-04-29_resteasy-reactive-nullpointer.zip)
2. start the project with `./gradlew quarkusDev`
3. open your browser and open one of
  3.1. http://localhost:8080/test/1
  3.2. http://localhost:8080/test/2
  3.3. http://localhost:8080/test/3
4. all calls crash with a NullPointerException like this:
```
2022-04-29 15:03:07,380 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-1) Request failed: java.lang.NullPointerException
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveCompressionHandler.handle(ResteasyReactiveCompressionHandler.java:52)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveCompressionHandler.handle(ResteasyReactiveCompressionHandler.java:14)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:73)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:70)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by geoand** [comment]
Thanks, https://github.com/quarkusio/quarkus/pull/25281 fixes the issue
