### ISSUE TITLE
Quarkus 2.9.0.CR1: Async Scheduled methods have unsafe sub-context

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#25257]
### Describe the bug

When using an async `@Scheduled` method returning a void or using Kotlin coroutines, the provided sub-context seems to be unsafe and throws an error when e.g. using hibernate reactive with it. 

E.g. using a code like

```
class TestScheduler(private val testDao: TestDao) {

    @Scheduled(every = "5s")
    fun every5s(): Uni<Void> {
        return testDao.getEntity(UUID.randomUUID()).replaceWithVoid()
    }
}

@ApplicationScoped
class TestDao(private val sessionFactory: Mutiny.SessionFactory) {
    fun getEntity(id: UUID): Uni<TestEntity?> = sessionFactory.withTransaction { s, _ ->
        s.find(TestEntity::class.java, id)
    }
}

```

ends in a crash like

```
2022-04-29 15:32:05,016 ERROR [io.qua.sch.com.run.StatusEmitterInvoker] (vert.x-eventloop-thread-0) Error occured while executing task for trigger IntervalTrigger [id=1_org.acme.TestScheduler_ScheduledInvoker_every5s_c56c24f01b03a432de6e9b18de0f5a7dfbc05db8, interval=5000]: java.lang.IllegalStateException: The current operation requires a safe (isolated) Vert.x sub-context, but the current context hasn't been flagged as such. You can still use Hibernate Reactive, you just need to avoid using the methods which implicitly require accessing the stateful context, such as MutinySessionFactory#withTransaction and #withSession.
	at io.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle.checkIsSafe(VertxContextSafetyToggle.java:80)
	at io.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle.validateContextIfExists(VertxContextSafetyToggle.java:63)
	at io.quarkus.hibernate.reactive.runtime.customized.CheckingVertxContext.get(CheckingVertxContext.java:46)
	at org.hibernate.reactive.mutiny.impl.MutinySessionFactoryImpl.withSession(MutinySessionFactoryImpl.java:189)
	at org.hibernate.reactive.mutiny.impl.MutinySessionFactoryImpl.withTransaction(MutinySessionFactoryImpl.java:261)
	at org.acme.db.TestDao.getEntity(TestDao.kt:12)
	at org.acme.db.TestDao_Subclass.getEntity$$superforward1(Unknown Source)
	at org.acme.db.TestDao_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
```

### Expected behavior

@Scheduled should have a safe context that can be used with hibernate reactive.

### Actual behavior

It crashes

### How to Reproduce?

1. Download reproducer project and unzip:
[2022-04-29_scheduler-unsafe.zip](https://github.com/quarkusio/quarkus/files/8591125/2022-04-29_scheduler-unsafe.zip)
2. run the included `docker-compose.yml` to set up a local postgres container. 
3. run with `./gradlew quarkusDev`
4. check the log for the crash

### Quarkus version or git rev

2.9.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by mkouba** [comment]
@andreas-eberle `-Dio.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle.UNRESTRICTED_BY_DEFAULT=true` seems to fix the problem so I suppose that we really need to mark the context explicitly.

**Comment by gsmet** [comment]
@Sanne might know ^^

**Comment by mkouba** [comment]
Uf, this whole "vertx duplicated context + hibernate reactive" thing is a nightmare...

**Comment by andreas-eberle** [comment]
Just to double check: @mkouba, does your fix then also apply to the coroutines version?

**Comment by mkouba** [comment]
> Just to double check: @mkouba, does your fix then also apply to the coroutines version?

That's a good question. I didn't test a coroutine... but it seems that the `AbstractCoroutineInvoker` is using the `Vertx.currentContext()` which should be fine. CC @geoand

In any case, I will try your reproducer as well.

**Comment by Sanne** [comment]
> Uf, this whole "vertx duplicated context + hibernate reactive" thing is a nightmare...

Well, I'm glad I added mandatory assertions, or noone would have noticed a critical integration problem - and N.B. Hibernate Reactive is merely *detecting* the problem - you'd have the same issue, if not worse, with other components.

So it would be more correctly called the "vert.x context integration mistakes".

**Comment by mkouba** [comment]
> N.B. Hibernate Reactive is merely detecting the problem - you'd have the same issue, if not worse, with other components.

Not all components require the duplicated context, or?

> So it would be more correctly called the "vert.x context integration mistakes".

Yep, sorry about the wording ;-).

**Comment by Sanne** [comment]
> > N.B. Hibernate Reactive is merely detecting the problem - you'd have the same issue, if not worse, with other components.
> 
> Not all components require the duplicated context, or?

The main issue is that the context put/get methods are public API of Vert.x - any user code (application code) or 3rd party library might refer to the context and expect it to adhere to the documented spec, so if we "fork" the context transparently we're responsible to do so in some safe way. We need to get it right when creating new contexts, even if you don't directly intend to use its storage facility.

> > So it would be more correctly called the "vert.x context integration mistakes".
> 
> Yep, sorry about the wording ;-).

np, sorry for the nitpicking :)
but I'm not commenting in defense of HR, more like I believe it's important to make sure we're all on the same page about the impotance of catching and fixing these cases.
