### ISSUE TITLE
RESTEasy reactive illegally restricts JAX-RSpath parameter names

### ISSUE THREAD

**Issue by sithmein** [quarkusio/quarkus#25258]
### Describe the bug

Consider the following JAX-RS resource:
```
@Produces(MediaType.APPLICATION_JSON)
@Path("/")
public class ContextNotWorking {
    @GET
    @Path("foo/{something-with-dash:[^a]*}")
	public Response doSomething(@PathParam("something-with-dash") String param) {
	    return Response.noContent().build();
	}
}
```
Note that path parameter _something-with-dash_. According to the Javadoc of @Path the dash is an allowed character in a parameter name. However, if you try to run this with resteasy-reactive startup fails with
```
Caused by: java.lang.IllegalArgumentException: Path '/foo/{something-with-dash:[^a]*}' of method 'org.knime.xxx.ContextNotWorking#doSomething' is not a valid expression
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.validateMethodPath(ServerEndpointIndexer.java:226)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleAdditionalMethodProcessing(ServerEndpointIndexer.java:218)
	at io.quarkus.resteasy.reactive.server.deployment.QuarkusServerEndpointIndexer.handleAdditionalMethodProcessing(QuarkusServerEndpointIndexer.java:164)
	at io.quarkus.resteasy.reactive.server.deployment.QuarkusServerEndpointIndexer.handleAdditionalMethodProcessing(QuarkusServerEndpointIndexer.java:32)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:657)
	... 14 more
Caused by: java.util.regex.PatternSyntaxException: named capturing group is missing trailing '>' near index 12
(?<something-with-dash>[^a]*)$
            ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at java.base/java.util.regex.Pattern.groupname(Pattern.java:2949)
	at java.base/java.util.regex.Pattern.group0(Pattern.java:2995)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2123)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
	at org.jboss.resteasy.reactive.server.mapping.URITemplate.<init>(URITemplate.java:157)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.validateMethodPath(ServerEndpointIndexer.java:223)
	... 18 more
```
It seems he reactive extension does not comply with the JAX-RS specification.
The same class works fine with the non-reactive version of RESTEasy.
Patterns in Java indeed do *not* allow dashes in capture group names.

### Expected behavior

Code that is legal according to the JAX-RS specification should work in Quarkus.

### Actual behavior

Quarkus startup fails with the error above.

### How to Reproduce?

Try to run the provided JAX-RS resource class with _quarkus-resteasy-reactive_.

### Output of `java -version`

17

### Quarkus version or git rev

2.8.2.Final

**Comment by Postremus** [comment]
The name of a group can only contain following characters:
`A-Za-z0-9`

Additionally, it may only start with:
`A-Za-z`

(See java.util.Pattern.groupName)

Lets compare this with the restrictions outlined in the javax.ws.rs.Path#value javadoc.
* must start with {
* may have zero to infinite whitespaces (space or tab)
* name, consisting of
** one letter in the range A-Za-z0-9_
** zero to ininite letters in the range A-Za-z0-9_-\.
* after the name, zero to infinite whitespaces
* optional regex
** : to start the regex
**  zero to infinite non brace characters, or zero to infinite a non brace character which are wrapped in braces
* ending with }

The full ABNF, just for reference:
```
param = "{" *WSP name *WSP [ ":" *WSP regex *WSP ] "}"
  name = (ALPHA / DIGIT / "_")*(ALPHA / DIGIT / "." / "_" / "-" ) ; \w[\w\.-]*
  regex = *( nonbrace / "{" *nonbrace "}" ) ; where nonbrace is any char other than "{" and "}"
```

The capturing group name is created in:

https://github.com/quarkusio/quarkus/blob/77aa7d369b8e7b38b5aa0fec6a08b150fce3abf8/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/mapping/URITemplate.java#L157-L158

These few lines create a simple regex pattern, not respecting that fact that uri templates are way more complex than group names allow for.

A solution would introduce some kind of normalization when creating the capture group, for example (not a fully tested solution, just as inspiration for now):
https://github.com/Postremus/quarkus/commit/ee89563d46d8d26e7a303d387e634e882e3d028d

**Comment by geoand** [comment]
@Postremus mind opening a draft PR with that change?
