### ISSUE TITLE
Dev Services: older version of Keycloak fails to start since 2.8.0

### ISSUE THREAD

**Issue by jorgebsa** [quarkusio/quarkus#25261]
### Describe the bug

In one of the projects I work, we are stuck with Keycloak `9.0.2` in production. Dev Services allows us to properly run tests against that version, which is immense. However, since Quarkus `2.8.0`, the Keycloak container does not start successfully and all tests are skipped after the first one fails due to the container start-up error. 

This error exists in all `2.8.x` versions released up to now. The latest working version was `2.7.5` and reverting to it fixes the issue. All `2.7.x` work fine, and if I'm not mistaken, our test suite was implemented with this keycloak version and running fine with it since `2.6.3`

Used image is: `quay.io/keycloak/keycloak:9.0.2`

### Expected behavior

Keycloak `9.0.2` container is started successfully by Dev Services since no `quarkus.oidc.auth-server-url` is provided, and tests run successfully

### Actual behavior

Dev Services attempts to start the keycloak container during the first test of the suite, but start-up fails due to `WFLYSRV0073: Invalid option 'start'` and the whole suite is skipped:

```
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ my-project ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running my.project.MyTest
[INFO] [stdout] 2022-04-29 16:05:19,348 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
[INFO] [stdout] 2022-04-29 16:05:19,647 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-28) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy fro
m ~/.testcontainers.properties, will try it first
[INFO] [stdout] 2022-04-29 16:05:20,046 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-28) Found Docker environment with local Unix socket (unix:///var/run/docker.soc
k)
[INFO] [stdout] 2022-04-29 16:05:20,048 INFO  [org.tes.DockerClientFactory] (build-28) Docker host IP address is localhost
[INFO] [stdout] 2022-04-29 16:05:20,078 INFO  [org.tes.DockerClientFactory] (build-28) Connected to docker:
[INFO] [stdout]   Server Version: 20.10.12
[INFO] [stdout]   API Version: 1.41
[INFO] [stdout]   Operating System: Docker Desktop
[INFO] [stdout]   Total Memory: 25173 MB
[INFO] [stdout] 2022-04-29 16:05:20,086 INFO  [org.tes.uti.ImageNameSubstitutor] (build-28) Image name substitution will be performed by: DefaultImageNameSubstitutor (composit
e of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
[INFO] [stdout] 2022-04-29 16:05:23,352 INFO  [org.tes.uti.RegistryAuthLocator] (build-28) Credential helper/store (docker-credential-desktop.exe) does not have credentials fo
r index.docker.io
[INFO] [stdout] 2022-04-29 16:05:24,966 INFO  [org.tes.uti.RyukResourceReaper] (build-28) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit      
[INFO] [stdout] 2022-04-29 16:05:24,966 INFO  [org.tes.DockerClientFactory] (build-28) Checking the system...
[INFO] [stdout] 2022-04-29 16:05:24,966 INFO  [org.tes.DockerClientFactory] (build-28) ✔︎ Docker server version should be at least 1.6.0
[INFO] [stdout] 2022-04-29 16:05:25,086 INFO  [org.tes.DockerClientFactory] (build-28) ✔︎ Docker environment should have more than 2GB free disk space
[INFO] [stdout] 2022-04-29 16:05:25,091 INFO  [🐳 .0.5]] (build-28) Creating container for image: mongo:5.0.5
[INFO] [stdout] 2022-04-29 16:05:25,154 INFO  [🐳 .0.5]] (build-28) Container mongo:5.0.5 is starting: 8dc4c9469c607cf2c3cd5f28d64f597bedd1a6ba62a7bf2a9777921450c65dfe        
[INFO] [stdout] 2022-04-29 16:05:25,164 INFO  [io.qua.oid.dep.dev.key.KeycloakDevServicesProcessor] (build-13) Using Quarkus powered Keycloak distribution
[INFO] [stdout] 2022-04-29 16:05:25,164 INFO  [🐳 .io/.0.2]] (build-13) Creating container for image: quay.io/keycloak/keycloak:9.0.2
[INFO] [stdout] 2022-04-29 16:05:25,468 INFO  [org.tes.uti.RegistryAuthLocator] (build-13) Credential helper/store (docker-credential-desktop.exe) does not have credentials fo
r quay.io
[INFO] [stdout] 2022-04-29 16:05:25,512 INFO  [🐳 .io/.0.2]] (build-13) Container quay.io/keycloak/keycloak:9.0.2 is starting: ea9b7500798955dd17ff48cd67d8b2cb4b8d8197d6a95748
fdb48edd9b6cbfa6
[INFO] [stdout] 2022-04-29 16:05:26,057 INFO  [🐳 .0.5]] (build-28) Container mongo:5.0.5 started in PT0.965652013S
[INFO] [stdout] 2022-04-29 16:06:27,386 ERROR [🐳 .io/.0.2]] (build-13) Could not start container: java.lang.IllegalStateException: Container exited with code 1
[INFO] [stdout]         at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:509)
[INFO] [stdout]         at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:340)
[INFO] [stdout]         at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
[INFO] [stdout]         at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:338)
[INFO] [stdout]         at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326)
[INFO] [stdout]         at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:334)
[INFO] [stdout]         at java.base/java.util.Optional.orElseGet(Optional.java:364)
[INFO] [stdout]         at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:356)
[INFO] [stdout]         at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:185)
[INFO] [stdout]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] [stdout]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[INFO] [stdout]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] [stdout]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[INFO] [stdout]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
[INFO] [stdout]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[INFO] [stdout]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[INFO] [stdout]         at java.base/java.lang.Thread.run(Thread.java:833)
[INFO] [stdout]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[INFO] [stdout]
[INFO] [stdout] 2022-04-29 16:06:27,412 ERROR [🐳 .io/.0.2]] (build-13) Log output from the failed container:
[INFO] [stdout] start --http-enabled=true --hostname-strict=false --hostname-strict-https=false
[INFO] [stdout] =========================================================================
[INFO] [stdout]
[INFO] [stdout]   Using Embedded H2 database
[INFO] [stdout]
[INFO] [stdout] =========================================================================
[INFO] [stdout]
[INFO] [stdout] =========================================================================
[INFO] [stdout]
[INFO] [stdout]   JBoss Bootstrap Environment
[INFO] [stdout]
[INFO] [stdout]   JBOSS_HOME: /opt/jboss/keycloak
[INFO] [stdout]
[INFO] [stdout]   JAVA: java
[INFO] [stdout]
[INFO] [stdout]   JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.by
teman -Djava.awt.headless=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL
-UNNAMED
[INFO] [stdout]
[INFO] [stdout] =========================================================================
[INFO] [stdout]
[INFO] [stdout] 14:06:21,016 INFO  [org.jboss.modules] (main) JBoss Modules version 1.9.1.Final
[INFO] [stdout] WFLYSRV0073: Invalid option 'start'
[INFO] [stdout]
[INFO] [stdout] Usage: standalone.sh [args...]
[INFO] [stdout] where args include:
[INFO] [stdout]     --admin-only                        Set the server's running type to
[INFO] [stdout]                                         ADMIN_ONLY causing it to open
[INFO] [stdout]                                         administrative interfaces and accept
[INFO] [stdout]                                         management requests but not start other
[INFO] [stdout]                                         runtime services or accept end user
[INFO] [stdout]                                         requests. Cannot be used in conjunction
[INFO] [stdout]                                         with --start-mode. Deprecated; use
[INFO] [stdout]                                         --start-mode=admin-only instead.
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     -b <value>, -b=<value>              Set system property jboss.bind.address
[INFO] [stdout]                                         to the given value
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     -b<interface>=<value>               Set system property
[INFO] [stdout]                                         jboss.bind.address.<interface> to the
[INFO] [stdout]                                         given value
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     -c <config>, -c=<config>            Name of the server configuration file
[INFO] [stdout]                                         to use (default is "standalone.xml")
[INFO] [stdout]                                         (Same as --server-config)
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     --debug [<port>]                    Activate debug mode with an optional
[INFO] [stdout]                                         argument to specify the port. Only
[INFO] [stdout]                                         works if the launch script supports it.
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     -D<name>[=<value>]                  Set a system property
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     -h, --help                          Display this message and exit
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     --read-only-server-config=<config>  Name of the server configuration file
[INFO] [stdout]                                         to use. This differs from
[INFO] [stdout]                                         '--server-config' and '-c' in that the
[INFO] [stdout]                                         original file is never overwritten.
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     -P <url>, -P=<url>,                 Load system properties from the given
[INFO] [stdout]          --properties=<url>             url
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     -S<name>[=<value>]                  Set a security property
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     --server-config=<config>            Name of the server configuration file
[INFO] [stdout]                                         to use (default is "standalone.xml")
[INFO] [stdout]                                         (Same as -c)
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     -u <value>, -u=<value>              Set system property
[INFO] [stdout]                                         jboss.default.multicast.address to the
[INFO] [stdout]                                         given value
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     -v, -V, --version                   Print version and exit
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     -secmgr                             Runs the server with a security manager
[INFO] [stdout]                                         installed.
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     --start-mode                        Sets the start mode of the server, it
[INFO] [stdout]                                         can be either 'normal','admin-only' or
[INFO] [stdout]                                         'suspend'. If this is 'suspend' the
[INFO] [stdout]                                         server will start in suspended mode,
[INFO] [stdout]                                         and will not service requests until it 
[INFO] [stdout]                                         has been resumed. If this is started in
[INFO] [stdout]                                         admin-only mode the server will only
[INFO] [stdout]                                         open administrative interfaces and
[INFO] [stdout]                                         accept management requests but not
[INFO] [stdout]                                         start other runtime services or accept
[INFO] [stdout]                                         end user requests. Cannot be used in
[INFO] [stdout]                                         conjunction with --admin-only.
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     --git-repo <repo_url>,              The git repository to clone to get the
[INFO] [stdout]          --git-repo=<repo_url>          server configuration.
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     --git-branch <branch>,              The git branch to use to get the server
[INFO] [stdout]          --git-branch=<branch>          configuration. Default is 'master'
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout]     --git-auth <auth_config>,           The elytron configuration file for
[INFO] [stdout]          --git-auth=<auth_config>       managing git credentials. Default is
[INFO] [stdout]                                         'null'
[INFO] [stdout]
[INFO] [stdout]
[INFO] [stdout] 14:06:21,371 FATAL [org.jboss.as.server] (main) WFLYSRV0239: Aborting with exit code 1
[INFO] [stdout]
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 70.591 s <<< FAILURE! - in my.project.MyTest
[ERROR] my.project.MyTest.simpleTest  Time elapsed: 0.003 s  <<< ERROR!
java.lang.RuntimeException:
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException:
 org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:232)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:345)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326)
        at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:334)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:356)
        at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:185)
        ... 11 more
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:338)
        ... 16 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:537)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:340)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        ... 17 more
Caused by: java.lang.IllegalStateException: Container exited with code 1
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:509)
        ... 19 more

Caused by: java.lang.RuntimeException:
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException:
 org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:232)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:345)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326)
        at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:334)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:356)
        at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:185)
        ... 11 more
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:338)
        ... 16 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:537)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:340)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        ... 17 more
Caused by: java.lang.IllegalStateException: Container exited with code 1
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:509)
        ... 19 more
```

### How to Reproduce?

Reproducer:

1) Set Quarkus version to `2.8.0` - `2.8.2`
2) Set property `quarkus.keycloak.devservices.image-name` to `quay.io/keycloak/keycloak:9.0.2`
3) Do not set the property `quarkus.oidc.auth-server-url` so that dev services is invoked
4) Run any test annotated with `@QuarkusTest` and it shall fail

### Output of `uname -a` or `ver`

Linux LAPTOP 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05) OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by sberyozkin** [comment]
@jorgebsa Since 2.8.0 it depends on a Keycloak Quarkus by default but while before 2.8.0 such images had `keycloak-x` qualifiers, it now just `keycloak` - so it assumes your image is a Keycloak Quarkus image - but it is not a problem, you just need to set `quarkus.keycloak.devservices.keycloak-x-image=false`, 

see https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/KeycloakDevServicesProcessor.java#L360
and
https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/deployment/src/main/java/io/quarkus/oidc/deployment/devservices/keycloak/DevServicesConfig.java#L52

Give it a try please

**Comment by sberyozkin** [comment]
@jorgebsa good it works now

> Maybe it would be a good idea to update at least the security-openid-connect-dev-services or the migration guide to make a reference to it :)

Sure, I'll take care of it

**Comment by jorgebsa** [comment]
@sberyozkin lgtm :) would like to thank you again for the quick reply and for improving the documentation!
