### ISSUE TITLE
JAXB2 ClassCastException in Native Image (XmlSeeAlso$$ProxyImpl cannot be cast to Locatable)

### ISSUE THREAD

**Issue by dlabordus** [quarkusio/quarkus#25325]
### Describe the bug

After upgrading Quarkus from 2.8.0 to 2.8.1 our RestEasy XML Endpoint is failing on generated JAXB2 Classes.

When a request is processed and the response should be returned Quarkus throws the following exception:
```
2022-05-03 08:16:13,974 WARN  [org.lfe.com.cor.jax.exc.GenericExceptionHandler] (executor-thread-0) Unknown exception occurred.: java.lang.ClassCastException: javax.xml.bind.annotation.XmlSeeAlso$$ProxyImpl cannot be cast to com.sun.xml.bind.v2.model.annotation.Locatable
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:260)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:73)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.getClassInfo(RuntimeModelBuilder.java:54)
	at com.sun.xml.bind.v2.model.impl.ClassInfoImpl.getBaseClass(ClassInfoImpl.java:198)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.getBaseClass(RuntimeClassInfoImpl.java:125)
	at com.sun.xml.bind.v2.model.impl.RuntimeClassInfoImpl.getBaseClass(RuntimeClassInfoImpl.java:56)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.getClassInfo(ModelBuilder.java:248)
```

The native image worked with version 2.8.0. And also the non-native images still works with version 2.8.2.
The model is generated by a other maven project using JAXB2 from XSD Files.

The image is build using Maven with a Docker Container. 
Command: mvn clean verify -Pnative -Dquarkus.container-image.build=true

It look like PR #24768 may have caused this, because searching for this kind of errors, often similar changes are mentions, but these are partially removed in this PR. Also in this PR there is a discussion about the GraalVM version 22.1, but with Quarkus 2.8.1 this is still 22.0, maybe this is something causing the problem.

### Expected behavior

The response being created and returned.

### Actual behavior

ClassCastException thrown

### Output of `uname -a` or `ver`

Linux ubuntu 5.13.0-40-generic #45-Ubuntu SMP Tue Mar 29 14:48:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.21.10.1) OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.21.10.1, mixed mode, sharing)

### GraalVM version (if different from Java)

Running Quarkus native-image plugin on GraalVM 22.0.0.2 Java 11 CE (Java Version 11.0.14+9-jvmci-22.0-b05)

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /home/dlabordus/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 11.0.15, vendor: Private Build, runtime: /usr/lib/jvm/java-11-openjdk-amd64 Default locale: en_GB, platform encoding: UTF-8 OS name: "linux", version: "5.13.0-40-generic", arch: "amd64", family: "unix"

### Additional information

Part of the Maven output:

```
[INFO] --- quarkus-maven-plugin:2.8.2.Final:build (default) @ app ---
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- javax.xml.namespace.QName (source: SmallRyeOpenApiProcessor > org.lfenergy.compas.cim.mapping.rest.v1.model.MapResponse)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/dlabordus/projects/compas/compas-cim-mapping/app/target/app-local-SNAPSHOT-native-image-source-jar/app-local-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/dlabordus/projects/compas/compas-cim-mapping/app/target/app-local-SNAPSHOT-native-image-source-jar/app-local-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Using docker to run the native image builder
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Checking image status quay.io/quarkus/ubi-quarkus-native-image:22.0-java11
22.0-java11: Pulling from quarkus/ubi-quarkus-native-image
Digest: sha256:44fe2378937b3b0b6f64189f68fda629dfc090370239cec8a8f1496d3f1d96e7
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-native-image:22.0-java11
quay.io/quarkus/ubi-quarkus-native-image:22.0-java11
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM 22.0.0.2 Java 11 CE (Java Version 11.0.14+9-jvmci-22.0-b05)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 1000:1000 -v /home/dlabordus/projects/compas/compas-cim-mapping/app/target/app-local-SNAPSHOT-native-image-source-jar:/project:z --name build-native-hqVmc quay.io/quarkus/ubi-quarkus-native-image:22.0-java11 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=GB -J-Dfile.encoding=UTF-8 -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED --initialize-at-run-time=org.eclipse.rdf4j.common.iteration.TimeLimitIteration --initialize-at-run-time=org.apache.http.impl.auth.NTLMEngineImpl -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https -H:-UseServiceLoaderFeature -H:+StackTrace app-local-SNAPSHOT-runner -jar app-local-SNAPSHOT-runner.jar
========================================================================================================================
```

**Comment by antonwiens** [comment]
Can we please get a fix for this? It is affecting 2.9.1 and Quarkus CXF 1.1.0.

**Comment by shumonsharif** [comment]
@gastaldi @antonwiens Reproducer attached, using only the `quarkus-resteasy-jaxb` dependency; as the `quarkus-cxf` dependency is not quite relevant for this issue.

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/8782978/code-with-quarkus.zip)

For the passing use case, you can execute:
`mvn clean install -Dquarkus.platform.version=2.8.0.Final -Dnative`

For the failure use case:
`mvn clean install -Dnative`

I believe the issue has existed since 2.8.1.Final.

**Comment by gastaldi** [comment]
@shumonsharif I couldn't reproduce the issue using your reproducer project. Here is the output from my terminal:

```bash
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.GreetingResourceTest
2022-05-26 23:45:12,581 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
2022-05-26 23:45:15,535 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.9.2.Final) started in 3.849s. Listening on: http://localhost:8081
2022-05-26 23:45:15,538 INFO  [io.quarkus] (main) Profile test activated.
2022-05-26 23:45:15,538 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jaxb, smallrye-context-propagation, vertx]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.931 s - in org.acme.GreetingResourceTest
2022-05-26 23:45:17,813 INFO  [io.quarkus] (main) code-with-quarkus stopped in 0.089s
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ code-with-quarkus ---
[INFO] Building jar: /Users/ggastald/Downloads/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT.jar
[INFO]
[INFO] --- quarkus-maven-plugin:2.9.2.Final:build (default) @ code-with-quarkus ---
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /Users/ggastald/Downloads/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /Users/ggastald/Downloads/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM 22.1.0 Java 17 CE (Java Version 17.0.3+7-jvmci-22.1-b06)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /Users/ggastald/.sdkman/candidates/java/22.1.0.r17-grl/bin/native-image -J-Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=BR -J-Dfile.encoding=UTF-8 -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-UseServiceLoaderFeature -H:+StackTrace code-with-quarkus-1.0.0-SNAPSHOT-runner -jar code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
========================================================================================================================
GraalVM Native Image: Generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (18.1s @ 0.23GB)
 Version info: 'GraalVM 22.1.0 Java 17 CE'
 C compiler: cc (apple, x86_64, 13.1.6)
 Garbage collector: Serial GC
 3 user-provided feature(s)
  - io.quarkus.runner.AutoFeature
  - io.quarkus.runtime.graal.DisableLoggingAutoFeature
  - io.quarkus.runtime.graal.ResourcesFeature
[2/7] Performing analysis...  [**********]                                                              (42.8s @ 1.03GB)
  12,447 (89.36%) of 13,929 classes reachable
  19,442 (59.08%) of 32,909 fields reachable
  63,808 (56.63%) of 112,680 methods reachable
     531 classes,   130 fields, and 2,056 methods registered for reflection
      64 classes,    76 fields, and    55 methods registered for JNI access
[3/7] Building universe...                                                                               (3.4s @ 1.57GB)
[4/7] Parsing methods...      [***]                                                                      (7.0s @ 3.65GB)
[5/7] Inlining methods...     [*****]                                                                    (5.8s @ 3.40GB)
[6/7] Compiling methods...    [******]                                                                  (35.6s @ 4.20GB)
[7/7] Creating image...                                                                                  (5.1s @ 2.07GB)
  27.03MB (45.85%) for code area:   42,232 compilation units
  27.25MB (46.23%) for image heap:   8,500 classes and 307,543 objects
   4.67MB ( 7.92%) for other data
  58.95MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1.80MB sun.security.ssl                                     5.81MB byte[] for code metadata
   1.42MB jdk.proxy4                                           3.84MB byte[] for general heap data
   1.01MB java.util                                            2.98MB java.lang.Class
 763.24KB com.sun.crypto.provider                              2.79MB java.lang.String
 512.88KB c.s.org.apache.xerces.internal.impl.xs.traversers    2.28MB byte[] for java.lang.String
 503.34KB com.sun.org.apache.xerces.internal.impl              1.04MB com.oracle.svm.core.hub.DynamicHubCompanion
 499.37KB com.oracle.svm.core.reflect                        678.61KB java.util.HashMap$Node
 470.92KB java.lang                                          658.63KB java.lang.reflect.Method
 470.76KB sun.security.x509                                  577.26KB byte[] for reflection metadata
 438.27KB java.io                                            569.27KB java.lang.String[]
      ... 466 additional packages                                 ... 2844 additional object types
                                           (use GraalVM Dashboard to see all)
------------------------------------------------------------------------------------------------------------------------
                        5.2s (4.2% of total time) in 34 GCs | Peak RSS: 7.21GB | CPU load: 3.40
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /Users/ggastald/Downloads/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/code-with-quarkus-1.0.0-SNAPSHOT-runner (executable)
 /Users/ggastald/Downloads/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/code-with-quarkus-1.0.0-SNAPSHOT-runner.build_artifacts.txt
========================================================================================================================
Finished generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner' in 2m 2s.
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 129475ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:50 min
[INFO] Finished at: 2022-05-26T23:47:27-03:00
[INFO] ------------------------------------------------------------------------

    ~/Downloads/code-with-quarkus  target/code-with-quarkus-1.0.0-SNAPSHOT-runner                                                                                       ✔  took 4m 55s 
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-05-26 23:48:00,971 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT native (powered by Quarkus 2.9.2.Final) started in 0.214s. Listening on: http://0.0.0.0:8080
2022-05-26 23:48:00,998 INFO  [io.quarkus] (main) Profile prod activated.
2022-05-26 23:48:00,998 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jaxb, smallrye-context-propagation, vertx]
```

I am using GraalVM 22.1.0 on JDK 17

**Comment by shumonsharif** [comment]
Hey @gastaldi Your logs don't show the `org.acme.GreetingResourceIT` test (native mode) getting executed - just wanted to verify that it was?

**Comment by gastaldi** [comment]
I ran `mvn clean package -Dnative`, running `mvn integration-test -Dnative` now

**Comment by gastaldi** [comment]
Ah yes, I can see the error now. Let me see if I can fix this

**Comment by gastaldi** [comment]
[This PR](https://github.com/quarkusio/quarkus/pull/25838) should fix the issue. Thanks for the reproducer.
