### ISSUE TITLE
LRA is not usable with resteasy reactive extensions

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#25330]
### Describe the bug

Using `narayana-lra` extension with `resteasy-reactive`, `resteasy-reactive-jackson`, and probably mainly `rest-client-reactive` results into:

```
2022-05-03 13:04:36,746 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello failed, error id: c0573c9a-0652-42c4-b690-49e3c724996e-1: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:102)
	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:113)
	at io.narayana.lra.client.NarayanaLRAClient.getClient(NarayanaLRAClient.java:891)
	at io.narayana.lra.client.NarayanaLRAClient.startLRA(NarayanaLRAClient.java:312)
	at io.narayana.lra.filter.ServerLRAFilter.startLRA(ServerLRAFilter.java:709)
	at io.narayana.lra.filter.ServerLRAFilter.filter(ServerLRAFilter.java:304)
	at io.narayana.lra.filter.ServerLRAFilter_Subclass.filter$$superforward1(Unknown Source)
	at io.narayana.lra.filter.ServerLRAFilter_Subclass$$function$$10.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.narayana.lra.filter.ServerLRAFilter_Subclass.filter(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:47)
	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:8)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:548)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:464)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at javax.ws.rs.client.FactoryFinder.newInstance(FactoryFinder.java:93)
	at javax.ws.rs.client.FactoryFinder.find(FactoryFinder.java:210)
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:69)
	... 25 more


2022-05-03 13:04:36,770 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:102)
	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:113)
	at io.narayana.lra.client.NarayanaLRAClient.getClient(NarayanaLRAClient.java:891)
	at io.narayana.lra.client.NarayanaLRAClient.startLRA(NarayanaLRAClient.java:312)
	at io.narayana.lra.filter.ServerLRAFilter.startLRA(ServerLRAFilter.java:709)
	at io.narayana.lra.filter.ServerLRAFilter.filter(ServerLRAFilter.java:304)
	at io.narayana.lra.filter.ServerLRAFilter_Subclass.filter$$superforward1(Unknown Source)
	at io.narayana.lra.filter.ServerLRAFilter_Subclass$$function$$10.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.narayana.lra.filter.ServerLRAFilter_Subclass.filter(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:47)
	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:8)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:548)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:464)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at javax.ws.rs.client.FactoryFinder.newInstance(FactoryFinder.java:93)
	at javax.ws.rs.client.FactoryFinder.find(FactoryFinder.java:210)
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:69)
	... 25 more

```

### Expected behavior

This should work the same as with the resteasy classic extensions.

### Actual behavior

`NarayanaLRAClient` is looking for Jersey.

### How to Reproduce?

Quickstart app with narayana-lra and resteasy-reactive extension mentioned in the guide and above and access any LRA that will try to reach the coordinator.

**Comment by geoand** [comment]
Can you please attach a sample? Also, it would be good to pinpoint whether this is due to the client or not (it looks like it is)

**Comment by xstefank** [comment]
Reproducer - https://github.com/xstefank/reproducers/tree/master/lra-service

1. Start the coordinator - `https://github.com/xstefank/reproducers/tree/master/lra-service`
2. Start the service - `mvn quarkus:dev -Dquarkus.http.port=8180`
3. access the app at `:8180/hello`

**Comment by xstefank** [comment]
@gsmet unfortunately, this is still not fixed with the fixed linked. Can I reopen this or should I open a new issue? 

The new error is internal - `java.util.ServiceConfigurationError: javax.ws.rs.client.ClientBuilder: Provider org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl not found`

**Comment by geoand** [comment]
So basically our Service isn't being loaded because `org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl` is being picked up? If so, where is that coming from?

**Comment by xstefank** [comment]
@geoand from the narayana-lra and lra-client dependencies. So I need to create a new buildItem that will add:
```
quarkus.class-loading.removed-resources."org.jboss.narayana.rts\:narayana-lra"=META-INF/services/javax.ws.rs.client.ClientBuilder
quarkus.class-loading.removed-resources."org.jboss.narayana.rts\:lra-client"=META-INF/services/javax.ws.rs.client.ClientBuilder
```
from the extension. Adding these in the user-app workarounds the problem.

**Comment by geoand** [comment]
So yeah, we'll need a new build item which will allow extensions to define those as well

**Comment by xstefank** [comment]
This will need to wait for https://github.com/quarkusio/quarkus/issues/25655. Or I can only make a PR that will fix it only in built artifacts (JAR and native) for now without working devmode and tests. Personally, I would wait for the new feature.

**Comment by gsmet** [comment]
Reopening because of https://github.com/quarkusio/quarkus/pull/26025 .
