### ISSUE TITLE
integration-tests/reactive-oracle-client fails in native mode

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#25415]
### Describe the bug

integration-tests/reactive-oracle-client fails in native mode

Running command `mvn -f integration-tests/pom.xml clean verify -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=5g -U -V -B -fae -Denforcer.skip=true -Dtest-containers -Dstart-containers -pl reactive-oracle-client`

Getting `Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: oracle.security.pki.OraclePKIProvider. This error is reported at image build time because class oracle.jdbc.driver.OracleDriver is registered for linking at image build time by command line`

More details:
```
[2/7] Performing analysis...  [*]                                                                       (18.4s @ 1.19GB)
   9,043 (87.21%) of 10,369 classes reachable
  13,656 (60.78%) of 22,469 fields reachable
  43,642 (64.54%) of 67,624 methods reachable
     344 classes,   290 fields, and   540 methods registered for reflection

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing oracle.jdbc.driver.OracleDriver.defaultConnection()
Parsing context:
   at oracle.jdbc.driver.OracleDriver.defaultConnection(OracleDriver.java:1087)
   at oracle.jdbc.datasource.impl.OracleDataSource.getPhysicalConnection(OracleDataSource.java:679)
   at oracle.jdbc.datasource.impl.OracleDataSource.getConnection(OracleDataSource.java:375)
   at oracle.jdbc.datasource.impl.OracleDataSource.getConnectionInternal(OracleDataSource.java:2120)
   at oracle.jdbc.datasource.impl.OracleDataSource$1.build(OracleDataSource.java:1845)
   at oracle.jdbc.datasource.impl.OracleDataSource$1.build(OracleDataSource.java:1779)
   at io.vertx.oracleclient.impl.OracleConnectionFactory.lambda$connect$0(OracleConnectionFactory.java:50)
   at io.vertx.oracleclient.impl.OracleConnectionFactory$$Lambda$1505/0x00000007c1b27040.handle(Unknown Source)
   at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
   at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
   at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
   at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
   at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:164)
   at io.vertx.core.impl.future.PromiseImpl.onComplete(PromiseImpl.java:23)
   at io.vertx.core.impl.VertxImpl.initClustered(VertxImpl.java:201)
   at io.vertx.core.impl.VertxBuilder.clusteredVertx(VertxBuilder.java:257)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:221)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:582)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$10.get(VertxCoreRecorder.java:480)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$10.get(VertxCoreRecorder.java:477)
   at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
   at com.oracle.svm.core.jdk.SystemPropertiesSupport.setProperty(SystemPropertiesSupport.java:201)
   at com.oracle.svm.core.jdk.Target_java_lang_System.setProperty(JavaLangSubstitutions.java:293)
   at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
   at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
   at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
   at io.quarkus.runner.GeneratedMain.main(Unknown Source)
   at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:149)
   at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:185)
   at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:152)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:315)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:290)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:111)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:252)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:552)
	at com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:631)
	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.util.AnalysisError: parsing had failed in another thread
	at parsing oracle.jdbc.driver.OracleDriver.defaultConnection(OracleDriver.java:1088)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2505)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:105)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3366)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3318)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3163)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:79)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:236)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:586)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:166)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:301)
	... 13 more
Caused by: com.oracle.graal.pointsto.util.AnalysisError: parsing had failed in another thread
	at com.oracle.graal.pointsto.util.AnalysisError.shouldNotReachHere(AnalysisError.java:176)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:621)
	at com.oracle.svm.hosted.fieldfolding.StaticFinalFieldFoldingNodePlugin.handleLoadStaticField(StaticFinalFieldFoldingFeature.java:358)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4747)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4718)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5212)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3358)
	... 28 more
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: oracle.security.pki.OraclePKIProvider. This error is reported at image build time because class oracle.jdbc.driver.OracleDriver is registered for linking at image build time by command line
	at parsing oracle.jdbc.driver.OracleDriver.<clinit>(OracleDriver.java:323)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2505)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:105)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3366)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3318)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3163)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:79)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:236)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:586)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:166)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:301)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:290)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:111)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:104)
	at com.oracle.graal.pointsto.PointsToAnalysis.lambda$addRootMethod$0(PointsToAnalysis.java:485)
	at com.oracle.graal.pointsto.PointsToAnalysis$2.run(PointsToAnalysis.java:654)
	... 8 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: oracle.security.pki.OraclePKIProvider. This error is reported at image build time because class oracle.jdbc.driver.OracleDriver is registered for linking at image build time by command line
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:298)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedType(SharedGraphBuilderPhase.java:253)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedNewInstance(SharedGraphBuilderPhase.java:199)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4447)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4440)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5221)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3358)
	... 28 more
```

### Expected behavior

Tests pass

### Actual behavior

Failure in native mode

### How to Reproduce?

mvn -f integration-tests/pom.xml clean verify -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=5g -U -V -B -fae -Denforcer.skip=true -Dtest-containers -Dstart-containers -pl reactive-oracle-client

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19

### GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-native-image:22.1-java11

### Quarkus version or git rev

Quarkus main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by tsegismont** [comment]
@rsvoboda have you found this in CI? I'm pretty sure the tests were passing when the initial PR was merged. Do you know when the build started to fail because of this?

**Comment by rsvoboda** [comment]
@tsegismont reactive-oracle-client is not listed in `.github/native-tests.json` so it's not executed in GitHub Actions. The test failed on our internal Jenkins jobs where we run against various db versions.

@Sanne I don't think so, the reactive-oracle-client module started to fail on May 5 and it doesn't have multiple reactive clients.

**Comment by tsegismont** [comment]
Thank you for the details @rsvoboda

**Comment by Sanne** [comment]
@rsvoboda but the issue at https://github.com/quarkusio/quarkus/issues/24788 isn't about multiple drivers, it's highlighting that the reactive oracle client doesn't work in native.

Which seems kind-a known TODO since the CI jobs aren't testing it.

So both issues seem to point to the same problem: support for native compilation isn't ready.

**Comment by rsvoboda** [comment]
Running with Quarkus 2.8 branch the build and tests are passing

```
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-05-09 13:06:39,377 INFO  [io.quarkus] (main) quarkus-integration-test-reactive-oracle-client 999-SNAPSHOT native (powered by Quarkus 999-SNAPSHOT) started in 0.025s. Listening on: http://0.0.0.0:8081
2022-05-09 13:06:39,378 INFO  [io.quarkus] (main) Profile prod activated.
2022-05-09 13:06:39,378 INFO  [io.quarkus] (main) Installed features: [cdi, reactive-oracle-client, resteasy, smallrye-context-propagation, smallrye-health, vertx]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.162 s - in io.quarkus.it.reactive.oracle.client.HealthCheckIT
[INFO] Running io.quarkus.it.reactive.oracle.client.NativeFruitsEndpointIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.24 s - in io.quarkus.it.reactive.oracle.client.NativeFruitsEndpointIT
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

*   a5b67af12b - (HEAD -> 2.8, upstream/2.8) Merge pull request #25394 from gsmet/2.8.3-backports-1 (3 days ago) <Guillaume Smet> is the latest commit on 2.8 branch atm
