### ISSUE TITLE
Running a kotlin/jackson native built with mandrel (graal-22.1 java 17)  will fail on missing json fields

### ISSUE THREAD

**Issue by mihaipoenaru** [quarkusio/quarkus#25460]
### Describe the bug

Not sure if this is truly a bug with Quarkus but a bug with the documentation referring to using the mandrel image for building native apps.

My business requirement is to build a bunch of cloud native microservices, so I chose quarkus and Kotlin and followed [this guide](https://quarkus.io/guides/kotlin). Notice that it implies that mandrel is a-ok to use for Kotlin (at least, that is my interpretation).

Everything works fine until I receive a json with a missing field, even if that field is nullable on the data class. Then I get the classic com.fasterxml.jackson.databind.exc.InvalidDefinitionException: [......] cannot deserialize from Object value (no delegate- or property-based Creator)

**Important to note that** if I manually specify the field in the json like `{"theField" : null}` then it actually works, the issue only appears when the field is omitted, like when serialized with the `JsonInclude(NOT_NULL)` annotation

Funnily enough, it worked when compiling natively on windows. After hours and trial-and-error I found out why. This is the log printed by the native build on windows:

```[1/7] Initializing...                                                                                   (10.9s @ 0.14GB)
 Version info: 'GraalVM 22.1.0 Java 17 CE'
 C compiler: cl.exe (microsoft, x64, 19.16.27045)
 Garbage collector: Serial GC
 5 user-provided feature(s)
  - com.oracle.svm.polyglot.kotlin.KotlinFeature    <----------- notice this!!!
  - com.oracle.svm.thirdparty.gson.GsonFeature
  - io.quarkus.runner.AutoFeature
  - io.quarkus.runtime.graal.DisableLoggingAutoFeature
  - io.quarkus.runtime.graal.ResourcesFeature```

Then I remembered reading somewhere that polyglot is removed from mandrel. Sure enough, the pipeline build using mandrel was not printing the line above.

I don't know if something can or even should be done about this (or maybe it's even intentional), but it is a very easy trap to fall in. The documentation, at least, should not lead you to fall into this trap by casually mentioning that you can use mandrel with Kotlin

### Expected behavior

When building a native image with mandrel and kotlin + jackson, missing fields should be mapped to null if the property in the POJO is marked as nullable with Kotlin's `?`

### Actual behavior

The request crashes with 400 Bad Request. No exception is printed by default, however I managed to coax it out:

```
2022-05-09 14:40:05,685 ERROR [com.ora.vp.act.res.ActuatorResource] (vert.x-eventloop-thread-0) 2: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.orange.vp.bo.dto.stb.request.ActuatorControlDTO` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"pairing":{"pairingExists":true,"householdId":"householdId","deviceId":"deviceId"}}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:[1415](https://gitlab.tech.orange/voice-portal/vp-int/-/jobs/34661424#L1415))
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
<ommited for brevity>
```

### How to Reproduce?

1. Create a quarkus-resteasy-reactive-jackson project with kotlin ( used intellij for this) 
2. Create a simple data class with some fields, but one of them must be nullable 

    example: 
    ```kotlin
    data class ExampleClass(
        @JsonProperty("fieldOne") val fieldOne: Int,
        @JsonProperty("fieldTwo") val fieldTwo: String? = null
    )
    ```
3. Send the following json `{"fieldOne": 4}`

### Output of `uname -a` or `ver`

Linux dev-vp-stb-actuator-644fd9cc99-7z7n6 4.18.0-305.40.2.el8_4.x86_64 #1 SMP Tue Mar 8 14:29:54 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

2.8.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

whatever it is on quay.io/quarkus/ubi-quarkus-mandrel:22.0-java17

### Additional information

My dependencies:

```xml
    <dependencies>
    
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-opentracing</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-context-propagation</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>kotlin-extensions</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock-jre8-standalone</artifactId>
            <version>2.33.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.22.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.marcinziolo</groupId>
            <artifactId>kotlin-wiremock</artifactId>
            <version>1.0.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

```

**Comment by geoand** [comment]
Thanks a lot for reporting this and for the analysis!

@galderz @zakkak would it not be possible for Mandrel to include `com.oracle.svm.polyglot.kotlin.KotlinFeature` ?

**Comment by zakkak** [comment]
@mihaipoenaru @geoand I am not able to reproduce the issue. 

What I tried:
```
wget "https://code.quarkus.io/d?e=kotlin&e=resteasy-reactive-jackson&cn=code.quarkus.io"
unzip code-with-quarkus.zip
cd code-with-quarkus
```

Added `ExampleClass` to `src/main/kotlin/org/acme/ExampleClass.kt`
```
./mvnw -Dnative verify -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:22.0-java17 -Dquarkus.native.container-build=true
./target/code-with-quarkus-1.0.0-SNAPSHOT-runner
```

From another terminal 
```
$ curl http://0.0.0.0:8080/hello
Hello from RESTEasy Reactive
```

I even tried adding the same dependencies as listed in the description and it didn't trigger.

Am I missing any steps?

**Comment by mihaipoenaru** [comment]
@zakkak i'll try and make a simple reproducer.

**Comment by mihaipoenaru** [comment]
> @zakkak i'll try and make a simple reproducer.

Ok, so, I made a reproducer, but in the end I have identified that the issue is solved with mandrel 22.1. I was trying to make a reproducer with 22.1 but everything was working correctly. Only after I re-read my problem did I realize that I was using 22.0. I  then tried the reproducer with 22.0 and it crashes as expected. 

Reproducer:

1. Main resource class

```kotlin
package com.example.mandrel

import com.fasterxml.jackson.annotation.JsonProperty
import javax.ws.rs.POST
import javax.ws.rs.Path

@Path("/hello")
class ExampleResource {

    @POST
    fun hello(person: Person) = "Hello, ${person.name ?: "World"}"
}

data class Person(
    @field:JsonProperty("surname") val surname: String,
    @field:JsonProperty("name") val name: String? = null
)
```

2. application.properties (windows behaves funky when I try to provide these as args to maven):

```yaml
quarkus.native.container-build=true
quarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:22.0-java17
```

3. pom dependencies
```xml
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>mandrel-rep</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <compiler-plugin.version>3.8.1</compiler-plugin.version>
        <failsafe.useModulePath>false</failsafe.useModulePath>
        <kotlin.version>1.6.10</kotlin.version>
        <maven.compiler.release>11</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>2.8.3.Final</quarkus.platform.version>
        <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
        </dependency>
    </dependencies>
</project>

BUILD TAG OMMITED FOR BREVITY
```

4. Requests:


```json
{
  "surname": "Foo",
  "name": "Bar"
}
```

This should work and return "Hello, Bar"

```json
{
  "surname": "Foo",
  "name": null   <------- null or omit field entirely
}
```

This returns 400 for me. Funnily enough, I thought that assigning the `null` value explicitly wouldn't crash it, but apparently it does. Weird, since that wasn't my Initial experience.


Note that since I updated to ubi-quarkus-mandrel:**22.1**-java17 I don't have this problem and everything works. I probably should have done this from the start. I guess we can close this but Maybe there should still be a warning in the docs somewhere?

**Comment by galderz** [comment]
> ... but Maybe there should still be a warning in the docs somewhere?

You can open a PR and have a go at adding the warning in the docs.

**Comment by geoand** [comment]
Closing this as out of date
