### ISSUE TITLE
RESTEasy Reactive: Unable to mock ContainerResponseContext in unit tests

### ISSUE THREAD

**Issue by csotiriou** [quarkusio/quarkus#25495]
### Describe the bug

When using Quarkus 2.8.3.Final, and have this unit test:

```
package com.example;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.wildfly.common.Assert;

import javax.ws.rs.container.ContainerResponseContext;

@QuarkusTest
public class ExampleContainerTest {

    @Test
    public void testAlpha(){
        var mockedObject = Mockito.mock(ContainerResponseContext.class);
        Assert.assertTrue(true);
    }
}

```

We get an error like this:
```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: interface javax.ws.rs.container.ContainerResponseContext.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
```

### Expected behavior

The unit test should be able to proceed

### Actual behavior

Unit test fails with the message above

### How to Reproduce?

Download the below file, and run `mvn test`

[demo5.zip](https://github.com/quarkusio/quarkus/files/8668633/demo5.zip)

### Output of `uname -a` or `ver`

Darwin my-mbp 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

```
openjdk version "11.0.14.1" 2022-02-08 LTS
OpenJDK Runtime Environment Zulu11.54+25-CA (build 11.0.14.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.54+25-CA (build 11.0.14.1+1-LTS, mixed mode)
```

### Quarkus version or git rev

2.8.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Maven home: /opt/homebrew/Cellar/maven/3.8.4/libexec
Java version: 11.0.14.1, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Default locale: en_GR, platform encoding: UTF-8
OS name: "mac os x", version: "12.3.1", arch: "aarch64", family: "mac"
```

### Additional information

Running on M1, I don't know if it plays any 

I have tested it also on the following the following JVM:

```
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)
```

and it seems to be working, so maybe it has to do something with Java 11 or this specific JVM?

**Comment by geoand** [comment]
This is almost certainly a ByteBuddy issue.

When I run the tests with Java 17,  everything works. 
When I run with Java 11, it breaks with the following:

```
org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: interface javax.ws.rs.container.ContainerResponseContext.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11.0.12+7
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.12+7
JVM info           : mixed mode
OS name            : Linux
OS version         : 5.13.0-40-generic


Underlying exception : java.lang.IllegalStateException: Failed to invoke proxy for public abstract java.lang.reflect.AnnotatedElement net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Delegator$ForLoadedMethodReturnType$Dispatcher.getAnnotatedReturnType(java.lang.reflect.Method)
        at com.example.ExampleContainerTest.testAlpha(ExampleContainerTest.java:15)
Caused by: java.lang.IllegalStateException: Failed to invoke proxy for public abstract java.lang.reflect.AnnotatedElement net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Delegator$ForLoadedMethodReturnType$Dispatcher.getAnnotatedReturnType(java.lang.reflect.Method)
        at com.example.ExampleContainerTest.testAlpha(ExampleContainerTest.java:15)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/XmlAdapter
        at com.example.ExampleContainerTest.testAlpha(ExampleContainerTest.java:15)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.adapters.XmlAdapter
        at com.example.ExampleContainerTest.testAlpha(ExampleContainerTest.java:15)
```

It looks vaguely similar to https://github.com/raphw/byte-buddy/issues/983
