### ISSUE TITLE
oracle.jdbc.driver.OraclePreparedStatement.setLongInternal throws invalid column index error in Quarkus >=2.6.2

### ISSUE THREAD

**Issue by babl2** [quarkusio/quarkus#25593]
### Describe the bug

From Quarkus2.6.2/Hibernate5.6.1 to our current Quarkus2.8.2/Hibernate5.6.8 we are getting an invalid column index error when updating one of our entities.
The identical code did work without any problems up to (including) Quarkus1.13.7/Hibernate5.4.29.
We are using
```
quarkus.datasource.db-kind=oracle
quarkus.hibernate-orm.dialect = org.hibernate.dialect.Oracle9iDialect
```

My question is, whether this is a problem of:

 1. The Oracle driver?
 2. Hibernate?
 3. Quarkus?
 4. Something wrong in our code?

Here is the entity:
```
@Entity
@Table(name = "USER_PREFERENCES")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@SequenceGenerator(name = "user_preferences_id_sequence", sequenceName = "USER_PREFERENCES_SEQ", allocationSize = 1)
public class Preferences {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_preferences_id_sequence")
    @Column(name = "ID")
    private Long id;

    @Column(name = "TYP")
    private String typ;

    @Column(name = "MODEX")
    private String modex;

    @Column(name = "JSON")
    private String json;
}
```

And here is the DB-Table as created via Liquibase:
```
<createTable tableName="USER_PREFERENCES">
    <column name="ID" type="NUMBER(38,0)">
        <constraints nullable="false" primaryKey="true" />
    </column>
    <column name="MODEX" type="VARCHAR2(12)"/>
    <column name="TYP" type="VARCHAR2(100)"/>
    <column name="JSON" type="CLOB"/>
</createTable>

leading to:

ID	NUMBER(38,0)
MODEX	VARCHAR2(12 CHAR)
TYP	VARCHAR2(100 CHAR)
JSON	CLOB
```

Upon calling `em.persist(preferences)` Hibernate creates the following output in both, the working and the not-working versions:
```
2022-05-16 08:50:39,914 DEBUG [org.hib.SQL] (executor-thread-1)
    update
        USER_PREFERENCES
    set
        JSON=?,
        MODEX=?,
        TYP=?
    where
        ID=?
Hibernate:
    update
        USER_PREFERENCES
    set
        JSON=?,
        MODEX=?,
        TYP=?
    where
        ID=?
2022-05-16 08:50:39,918 TRACE [org.hib.typ.des.sql.BasicBinder] (executor-thread-1) binding parameter [1] as [VARCHAR] - [{"autoSearch":true,"filter":{"statusId":2,"userId":55,"testProp":"xxx"}}]
2022-05-16 08:50:39,919 TRACE [org.hib.typ.des.sql.BasicBinder] (executor-thread-1) binding parameter [2] as [VARCHAR] - [testB985B]
2022-05-16 08:50:39,921 TRACE [org.hib.typ.des.sql.BasicBinder] (executor-thread-1) binding parameter [3] as [VARCHAR] - [search_prefs]
2022-05-16 08:50:39,923 TRACE [org.hib.typ.des.sql.BasicBinder] (executor-thread-1) binding parameter [4] as [BIGINT] - [11]
```

In the not-working version, this leads to
```
2022-05-16 09:06:51,292 DEBUG [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-0) could not update: [de.my.app.preferences.entity.Preferences#11] [update USER_PREFERENCES set JSON=?, MODEX=?, TYP=? where ID=?]: java.sql.SQLException: Ung³ltiger Spaltenindex
        at oracle.jdbc.driver.OraclePreparedStatement.setLongInternal(OraclePreparedStatement.java:5005)
        at oracle.jdbc.driver.OraclePreparedStatement.setLong(OraclePreparedStatement.java:4996)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.setLong(OraclePreparedStatementWrapper.java:207)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.setLong(PreparedStatementWrapper.java:148)
        at org.hibernate.type.descriptor.sql.BigIntTypeDescriptor$1.doBind(BigIntTypeDescriptor.java:46)
        at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:73)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:276)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:271)
        at org.hibernate.persister.entity.AbstractEntityPersister.dehydrateId(AbstractEntityPersister.java:3121)
        at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:3093)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3527)
        ... 139 more
```

As initially stated, I'm not sure whether this is a Quarkus- or Hibernate- or Oracle problem and thus, I asked the same thing [on Stackoverflow](https://stackoverflow.com/questions/72256360/oracle-jdbc-driver-oraclepreparedstatement-setlonginternal-throws-invalid-column)

### Expected behavior

`em.persist(preferences)` should not throw an error in versions >=2.6.2 for SQL that did work in <=1.13.7

### Actual behavior

`em.persist(preferences)` throws an in invalid column index error in versions >=2.6.2

### Output of `uname -a` or `ver`

all (win / SLES / RedHat)

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS

### GraalVM version (if different from Java)

non-native build

### Quarkus version or git rev

2.8.2 (non-native)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by babl2** [comment]
As there was no response here after 2 weeks, I tried a workaround, which unfortunately failed, but might create additional insights to the underlying problem?

As the original error is thrown from OraclePreparedStatement.setLongInternal, I removed the ID-column of the entity and made typ+modex a composite key instead.
With this setup, the new error from em.persist is:
`Caused by: java.sql.SQLException: Ung³ltiger Spaltenindex
        at oracle.jdbc.driver.OraclePreparedStatement.setFormOfUseInternal(OraclePreparedStatement.java:11468)
        at oracle.jdbc.driver.OraclePreparedStatement.setFormOfUseInternal(OraclePreparedStatement.java:11449)
        at oracle.jdbc.driver.OraclePreparedStatement.setString(OraclePreparedStatement.java:5305)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.setString(OraclePreparedStatementWrapper.java:252)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.setString(PreparedStatementWrapper.java:188)
        at org.hibernate.type.descriptor.sql.VarcharTypeDescriptor$1.doBind(VarcharTypeDescriptor.java:46)
        at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:73)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:276)
        at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:271)
        at org.hibernate.type.ComponentType.nullSafeSet(ComponentType.java:340)
        at org.hibernate.persister.entity.AbstractEntityPersister.dehydrateId(AbstractEntityPersister.java:3121)
        at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:3093)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3527)`

**Comment by gastaldi** [comment]
@babl2 It helps if you could provide a small reproducer project

**Comment by DavideD** [comment]
@babl2 can you try to escape the column name `JSON`?

```
    @Column(name = "`JSON`")
    private String json;
```

**Comment by babl2** [comment]
@DavideD that solved the problem!

Thank you very much!
