### ISSUE TITLE
NPE in 2.9.1 Http2 response processing

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#25658]
### Describe the bug

After upgrading from 2.8.3 to 2.9.1 we started seeing these errors in our logs.

### Expected behavior

No errors

### Actual behavior

```posh
java.lang.NullPointerException: Cannot invoke "io.vertx.core.Handler.handle(Object)" because "handler" is null
at io.vertx.core.http.impl.Http2ServerResponse.write(Http2ServerResponse.java:474)
at io.vertx.core.http.impl.Http2ServerResponse.end(Http2ServerResponse.java:433)
at io.vertx.core.http.impl.Http2ServerResponse.end(Http2ServerResponse.java:413)
at io.quarkus.vertx.http.runtime.filters.AbstractResponseWrapper.end(AbstractResponseWrapper.java:481)
at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.end(VertxResteasyReactiveRequestContext.java:331)
at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:38)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:550)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

It is intermittent and cannot reproduce outside of our production environment

### Output of `uname -a` or `ver`

AWS Fargate

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)

### Quarkus version or git rev

2.9.1.Final

**Comment by geoand** [comment]
cc @cescoffier  @jviet @pmlopes

**Comment by vietj** [comment]
this happens because RestEasy reactive calls vertx with a null handler : 

```java
   @Override
    public ServerHttpResponse end() {
        if (!response.ended()) {
            response.end((Handler<AsyncResult<Void>>) null);
        }
        return this;
    }
```

in https://github.com/quarkusio/quarkus/blob/e7315703f408f4697149cd8d6a0ba08fcf061f26/independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxResteasyReactiveRequestContext.java#L331

**Comment by geoand** [comment]
We have always been doing that, should we not be doing it?

**Comment by vietj** [comment]
this was done recently (https://github.com/quarkusio/quarkus/pull/25577) and  calling method with null is not something we advocate to do for most users.

my point is that there is no guarantee that it works, in practice calling end(null) should throw an NPE.

this will be fixed in 4.3.1 : https://github.com/eclipse-vertx/vert.x/commit/e9846949523c14927a8ac2d048a84378f774b83e but try avoiding in rest easy reactive on hacks like this and avoid too much TFB driven development please.

**Comment by geoand** [comment]
> this was done recently (https://github.com/quarkusio/quarkus/pull/25577) and calling method with null is not something we advocate to do for most users

Indeed, I missed the change when looking at the git logs (cc @franz1981 ). 
In my view, this is a perfectly valid thing for us to do, unless we have a way to know that it's not expected to work.

**Comment by gsmet** [comment]
Can we revert https://github.com/quarkusio/quarkus/pull/25577 until this gets fixed? I would like this to be fixed for 2.9.2.

**Comment by geoand** [comment]
I don't really want to revert it. I did https://github.com/quarkusio/quarkus/pull/25684 instead

**Comment by franz1981** [comment]
@vietj 
> this was done recently (https://github.com/quarkusio/quarkus/pull/25577) and calling method with null is not something we advocate to do for most users.

I can understand why, but given that fire-and-forget seems to be missing gap in the API (or better- "explicit fire-and-forget") and `null` isn't a nice candidate for the callback-style API, wdyt about exposing a `voidHandler`-like singleton?
I know in the past (thinking about Netty) it hasn't been a great solution, making the underline stack more complex for what looks like a futile optimization, but saving a callback in the hot path means saving a whole graph of callbacks (including Netty ones) that interact with atomic/concurrent primitives too ie hurting not just the TLAB allocation machinery, but wasting CPU cycles as well.

**Comment by vietj** [comment]
for now I think it's ok to pass null but it should not be abused.

we'll see what we'll do in the future with Netty 5 that does not have anymore a void promise solution.
