### ISSUE TITLE
Randomly failing builds

### ISSUE THREAD

**Issue by rafmcpaf** [quarkusio/quarkus#25677]
Hy,
Our project has nightly build to verify that everything keeps working. Our nightly build fails randomly (not always) with following exception while doing quarkus-maven-plugin:build. I cannot reproduce this, as this never occurs on my machine.

Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.NullPointerException
[ERROR] 	at org.jboss.jandex.AnnotationTargetFilterCollection.size(AnnotationTargetFilterCollection.java:115)
[ERROR] 	at java.base/java.util.AbstractCollection.isEmpty(AbstractCollection.java:87)
[ERROR] 	at io.quarkus.arc.deployment.CustomScopeAnnotationsBuildItem.isScopeIn(CustomScopeAnnotationsBuildItem.java:86)
[ERROR] 	at io.quarkus.arc.deployment.AutoAddScopeProcessor$1.transform(AutoAddScopeProcessor.java:63)
[ERROR] 	at io.quarkus.arc.processor.AnnotationStore.transform(AnnotationStore.java:103)
[ERROR] 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
[ERROR] 	at io.quarkus.arc.processor.AnnotationStore.getAnnotations(AnnotationStore.java:56)
[ERROR] 	at io.quarkus.arc.processor.AnnotationStore.hasAnnotation(AnnotationStore.java:80)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:885)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:240)
[ERROR] 	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
[ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:411)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]

**Comment by geoand** [comment]
I'm afraid we'll need a lot more information than this to be able to debug.

**Comment by rafmcpaf** [comment]
What extra info do you need? As this is currently the only trace I can find...
I enable the '-X' flag on our build server in a hope this gives some more insights...

**Comment by geoand** [comment]
A sample of the code would be super helpful

**Comment by rafmcpaf** [comment]
Sadly enough my company does not allow exposing the full code. I can give some snippets thou. Is the pom.xml sufficient?

<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>mik-scada-websocket</artifactId>
  <parent>
		<groupId>com.ebo.mik</groupId>
		<artifactId>mik-backend-aggregator</artifactId>
		<version>1.8-SNAPSHOT</version>
		<relativePath>../mik-backend-aggregator</relativePath>
  </parent>
  <dependencies>
    
	<dependency>
		<groupId>org.jboss.logging</groupId>
		<artifactId>commons-logging-jboss-logging</artifactId>
	</dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j-impl</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-undertow-websockets</artifactId>
      
      <version>2.7.5.Final</version>
    </dependency>
    <dependency>
	  <groupId>com.ebo.raf</groupId>
	  <artifactId>raf-ipc-protocol</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-scheduler</artifactId>
    </dependency>
    <dependency>
      <groupId>com.ebo</groupId>
      <artifactId>JEF-MQ</artifactId>
    </dependency>
    <dependency>
      <groupId>org.keycloak</groupId>
      <artifactId>keycloak-authz-client</artifactId>
    </dependency>
    <dependency>
      <groupId>com.ebo.raf</groupId>
      <artifactId>raf-quarkus-logging</artifactId>
    </dependency>
    <dependency>
	<artifactId>raf-stack-quarkus</artifactId>
  	  <groupId>com.ebo.raf</groupId>
    </dependency>
    <dependency>
      <groupId>com.ebo.raf.authorization</groupId>
      <artifactId>raf-authorization-keycloak</artifactId>
    </dependency>
    <dependency>
      <groupId>com.ebo.mik</groupId>
      <artifactId>mik-backend-lib-geo</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>

**Comment by geoand** [comment]
> Sadly enough my company does not allow exposing the full code. 

Understood

> I can give some snippets thou. Is the pom.xml sufficient?

I doubt it, but I'll let @mkouba and/or @manovotn answer

**Comment by mkouba** [comment]
It seems that `AnnotationInstance.target()` is null, which can happen if `AnnotationInstance.create(DotName, AnnotationTarget, AnnotationValue[])` is used.

@Ladicek I wonder if `AnnotationInstance.create()` should throw an `IllegalArgumentException` if no target is specified?

**Comment by Ladicek** [comment]
There's a lot of legitimate cases for creating an `AnnotationInstance` without target. For example, I'd expect that most annotation transformations would create a target-less `AnnotationInstance`.

**Comment by mkouba** [comment]
> There's a lot of legitimate cases for creating an `AnnotationInstance` without target. For example, I'd expect that most annotation transformations would create a target-less `AnnotationInstance`.

In that case, we should fix the `AnnotationTargetFilterCollection.size()`.

**Comment by Ladicek** [comment]
I think that would just cover up an actual bug somewhere else. `AnnotationTargetFilterCollection` is only used in `ClassInfo.classAnnotations()`, and all annotations in the `ClassInfo.annotations` map _should_ have a target.

(FTR, I got rid of `AnnotationTargetFilterCollection` in Jandex 3.0, and replaced it by eager filtering. That would still exhibit the same problem, though -- I still need to look at the annotation target.)

This looks like someone is messing up with `ClassInfo` internals. I know SmallRye GraphQL is doing extremely nasty things to Jandex, but the POM snippet above doesn't contain a dependency on SmallRye GraphQL, so that probably isn't it.

It would be interesting to put this line

```java
System.out.println("!!! " + context.getTarget() + " -> " + context.getAnnotations());
```

right here: https://github.com/quarkusio/quarkus/blob/2.9.1.Final/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/AutoAddScopeProcessor.java#L62 (before the first line of the method body) and see where exactly the transformer fails.

**Comment by rafmcpaf** [comment]
Our nightly build failed again, but now with extra debug logging (-X flag enabled). I could find the following errors (in order of appearance. Hopefully this gives some extra insights:

```
[DEBUG] [io.quarkus.deployment.QuarkusAugmentor] Beginning Quarkus augmentation
[DEBUG] [io.quarkus.bootstrap.classloading.QuarkusClassLoader] Class javax.servlet.ServletConfig not found in parent first load from ClassRealm[extension>io.quarkus:quarkus-maven-plugin:2.8.2.Final, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902]
[DEBUG] [io.quarkus.bootstrap.classloading.QuarkusClassLoader] Class javax.servlet.ServletContext not found in parent first load from ClassRealm[extension>io.quarkus:quarkus-maven-plugin:2.8.2.Final, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902]
[DEBUG] [io.quarkus.bootstrap.classloading.QuarkusClassLoader] Class javax.servlet.FilterConfig not found in parent first load from ClassRealm[extension>io.quarkus:quarkus-maven-plugin:2.8.2.Final, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902]
[DEBUG] [io.quarkus.bootstrap.classloading.QuarkusClassLoader] Class javax.servlet.annotation.WebFilter not found in parent first load from ClassRealm[extension>io.quarkus:quarkus-maven-plugin:2.8.2.Final, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902]
[DEBUG] [io.quarkus.bootstrap.classloading.QuarkusClassLoader] Class javax.servlet.annotation.WebListener not found in parent first load from ClassRealm[extension>io.quarkus:quarkus-maven-plugin:2.8.2.Final, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902]
[DEBUG] [io.quarkus.bootstrap.classloading.QuarkusClassLoader] Class javax.servlet.annotation.WebServlet not found in parent first load from ClassRealm[extension>io.quarkus:quarkus-maven-plugin:2.8.2.Final, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902]
[DEBUG] [io.quarkus.bootstrap.classloading.QuarkusClassLoader] Class javax.servlet.annotation.MultipartConfig not found in parent first load from ClassRealm[extension>io.quarkus:quarkus-maven-plugin:2.8.2.Final, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902]
[DEBUG] [io.quarkus.bootstrap.classloading.QuarkusClassLoader] Class javax.servlet.annotation.ServletSecurity not found in parent first load from ClassRealm[extension>io.quarkus:quarkus-maven-plugin:2.8.2.Final, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902]
[DEBUG] [io.quarkus.bootstrap.classloading.QuarkusClassLoader] Class javax.servlet.annotation.HandlesTypes not found in parent first load from ClassRealm[extension>io.quarkus:quarkus-maven-plugin:2.8.2.Final, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902]
[ERROR] [io.quarkus.bootstrap.classloading.PathTreeClassPathElement] Failed to read com/ebo/raf/quarkus/logging/deployment/RafQuarkusLoggingProcessor.class attempting to re-open the zip file. It is likely a jar file changed on disk, you should shutdown your application
java.io.EOFException: Unexpected end of ZLIB input stream
    at jdk.nio.zipfs.ZipFileSystem$3.fill (ZipFileSystem.java:1588)
    at java.util.zip.InflaterInputStream.read (InflaterInputStream.java:159)
    at java.io.InputStream.readNBytes (InputStream.java:396)
    at java.io.InputStream.readAllBytes (InputStream.java:333)
    at jdk.nio.zipfs.ZipFileSystem.newByteChannel (ZipFileSystem.java:690)
    at jdk.nio.zipfs.ZipPath.newByteChannel (ZipPath.java:815)
    at jdk.nio.zipfs.ZipFileSystemProvider.newByteChannel (ZipFileSystemProvider.java:252)
    at java.nio.file.Files.newByteChannel (Files.java:370)
    at java.nio.file.Files.newByteChannel (Files.java:421)
    at java.nio.file.Files.readAllBytes (Files.java:3205)
    at io.quarkus.bootstrap.classloading.PathTreeClassPathElement$Resource.getData (PathTreeClassPathElement.java:247)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:452)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:414)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:464)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:414)
    at java.lang.Class.forName0 (Native Method)
    at java.lang.Class.forName (Class.java:398)
    at io.quarkus.deployment.util.ServiceUtil.classesNamedIn (ServiceUtil.java:29)
    at io.quarkus.deployment.ExtensionLoader.loadStepsFrom (ExtensionLoader.java:198)
    at io.quarkus.deployment.QuarkusAugmentor.run (QuarkusAugmentor.java:104)
    at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment (AugmentActionImpl.java:328)
    at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication (AugmentActionImpl.java:175)
    at io.quarkus.maven.BuildMojo.doExecute (BuildMojo.java:132)
    at io.quarkus.maven.QuarkusBootstrapMojo.execute (QuarkusBootstrapMojo.java:154)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

```
[DEBUG] [io.netty.util.internal.PlatformDependent0] java.nio.Buffer.address: available
[DEBUG] [io.netty.util.internal.PlatformDependent0] direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
    at io.netty.util.internal.ReflectionUtil.trySetAccessible (ReflectionUtil.java:31)
    at io.netty.util.internal.PlatformDependent0$4.run (PlatformDependent0.java:253)
    at java.security.AccessController.doPrivileged (Native Method)
    at io.netty.util.internal.PlatformDependent0.<clinit> (PlatformDependent0.java:247)
    at io.netty.util.internal.PlatformDependent.isAndroid (PlatformDependent.java:294)
    at io.netty.util.internal.PlatformDependent.<clinit> (PlatformDependent.java:88)
    at io.netty.util.AsciiString.<init> (AsciiString.java:223)
    at io.netty.util.AsciiString.<init> (AsciiString.java:210)
    at io.netty.util.AsciiString.cached (AsciiString.java:1401)
    at io.netty.util.AsciiString.<clinit> (AsciiString.java:48)
    at io.netty.handler.codec.http.HttpMethod.<init> (HttpMethod.java:132)
    at io.netty.handler.codec.http.HttpMethod.<clinit> (HttpMethod.java:36)
    at io.vertx.core.http.HttpMethod.<clinit> (HttpMethod.java:192)
    at io.quarkus.vertx.http.runtime.VertxHttpRecorder.<clinit> (VertxHttpRecorder.java:1324)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (Native Method)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:490)
    at io.quarkus.deployment.proxy.ProxyFactory.newInstance (ProxyFactory.java:278)
    at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy (BytecodeRecorderImpl.java:370)
    at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$78 (ExtensionLoader.java:692)
    at io.quarkus.deployment.ExtensionLoader$3.execute (ExtensionLoader.java:921)
    at io.quarkus.builder.BuildContext.run (BuildContext.java:277)
    at org.jboss.threads.ContextHandler$1.runWith (ContextHandler.java:18)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run (EnhancedQueueExecutor.java:2449)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1478)
    at java.lang.Thread.run (Thread.java:834)
    at org.jboss.threads.JBossThread.run (JBossThread.java:501)
[DEBUG] [io.netty.util.internal.PlatformDependent0] java.nio.Bits.unaligned: available, {}
[DEBUG] [io.netty.util.internal.PlatformDependent0] jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @56ae4edb
    at jdk.internal.reflect.Reflection.newIllegalAccessException (Reflection.java:361)
    at java.lang.reflect.AccessibleObject.checkAccess (AccessibleObject.java:591)
    at java.lang.reflect.Method.invoke (Method.java:558)
    at io.netty.util.internal.PlatformDependent0$6.run (PlatformDependent0.java:375)
    at java.security.AccessController.doPrivileged (Native Method)
    at io.netty.util.internal.PlatformDependent0.<clinit> (PlatformDependent0.java:366)
    at io.netty.util.internal.PlatformDependent.isAndroid (PlatformDependent.java:294)
    at io.netty.util.internal.PlatformDependent.<clinit> (PlatformDependent.java:88)
    at io.netty.util.AsciiString.<init> (AsciiString.java:223)
    at io.netty.util.AsciiString.<init> (AsciiString.java:210)
    at io.netty.util.AsciiString.cached (AsciiString.java:1401)
    at io.netty.util.AsciiString.<clinit> (AsciiString.java:48)
    at io.netty.handler.codec.http.HttpMethod.<init> (HttpMethod.java:132)
    at io.netty.handler.codec.http.HttpMethod.<clinit> (HttpMethod.java:36)
    at io.vertx.core.http.HttpMethod.<clinit> (HttpMethod.java:192)
    at io.quarkus.vertx.http.runtime.VertxHttpRecorder.<clinit> (VertxHttpRecorder.java:1324)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (Native Method)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:490)
    at io.quarkus.deployment.proxy.ProxyFactory.newInstance (ProxyFactory.java:278)
    at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy (BytecodeRecorderImpl.java:370)
    at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$78 (ExtensionLoader.java:692)
    at io.quarkus.deployment.ExtensionLoader$3.execute (ExtensionLoader.java:921)
    at io.quarkus.builder.BuildContext.run (BuildContext.java:277)
    at org.jboss.threads.ContextHandler$1.runWith (ContextHandler.java:18)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run (EnhancedQueueExecutor.java:2449)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1478)
    at java.lang.Thread.run (Thread.java:834)
    at org.jboss.threads.JBossThread.run (JBossThread.java:501)
```

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.8.2.Final:build (default) on project mik-scada-websocket: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: java.io.UncheckedIOException: java.io.EOFException: Unexpected end of ZLIB input stream
[ERROR] 	at io.quarkus.deployment.index.IndexingUtil$MetaInfJandexReader.apply(IndexingUtil.java:257)
[ERROR] 	at io.quarkus.deployment.index.IndexingUtil$MetaInfJandexReader.apply(IndexingUtil.java:230)
[ERROR] 	at io.quarkus.paths.PathTreeVisit.process(PathTreeVisit.java:40)
[ERROR] 	at io.quarkus.paths.DirectoryPathTree.apply(DirectoryPathTree.java:106)
[ERROR] 	at io.quarkus.paths.ArchivePathTree$OpenArchivePathTree.apply(ArchivePathTree.java:202)
[ERROR] 	at io.quarkus.paths.PathTreeWithManifest.apply(PathTreeWithManifest.java:73)
[ERROR] 	at io.quarkus.deployment.index.IndexingUtil.indexTree(IndexingUtil.java:61)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.lambda$addMarkerFilePaths$1(ApplicationArchiveBuildStep.java:251)
[ERROR] 	at io.quarkus.bootstrap.classloading.PathTreeClassPathElement.apply(PathTreeClassPathElement.java:111)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.addMarkerFilePaths(ApplicationArchiveBuildStep.java:238)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.scanForOtherIndexes(ApplicationArchiveBuildStep.java:144)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.build(ApplicationArchiveBuildStep.java:105)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
[ERROR] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$3.fill(ZipFileSystem.java:1588)
[ERROR] 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
[ERROR] 	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
[ERROR] 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
[ERROR] 	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:392)
[ERROR] 	at org.jboss.jandex.IndexReader.readVersion(IndexReader.java:134)
[ERROR] 	at org.jboss.jandex.IndexReader.getIndexVersion(IndexReader.java:127)
[ERROR] 	at io.quarkus.deployment.index.IndexingUtil$MetaInfJandexReader.apply(IndexingUtil.java:244)
[ERROR] 	... 22 more
[ERROR] -> [Help 1]
```

Looking at the last error, I assumed that there was a corrupt jar (or one with a corrupt jandex index), but I could not find one...

**Comment by geoand** [comment]
Can you try clearing the state of your CI?

**Comment by rafmcpaf** [comment]
Our CI is a jenkins. We clear the workspace after every build. 
The weird part is that this build only seems to fail in our nightly job (and not always...). 
I know that there is possibly an external cause for this. But these error messages give me no clue what to look for...

**Comment by geoand** [comment]
Perhaps https://github.com/quarkusio/quarkus/pull/25721 will help

**Comment by rafmcpaf** [comment]
Ok, let's wait till that one is in a next release

**Comment by geoand** [comment]
Any update on this?

**Comment by rafmcpaf** [comment]
We've upgraded to 2.10.1, and since this haven't occurred anymore. 
Maybe soon to say, but first glances say this is fixed now...

**Comment by geoand** [comment]
Thanks for the update.

Let's close for now. Feel free to reopen / comment if you see the issue again
