### ISSUE TITLE
Dev Services for Postgresql not working with Rancher

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#25682]
### Describe the bug

Last week I got a new laptop - a 2021 MacBook M1Pro. Since then whenever I try to use Dev Services for Postgresql (either in Quarkus Dev mode or when running tests) it seems to be broken with some kind of race condition between the starting of the Postgres container & the creation of the username/password). When Hibernate kicks in to create the tables its getting an authentication error, as if the user hasn’t yet been created. I’m hoping my new machine isn’t too fast!

### Expected behavior

I would expect the dev service for postgresql to work.

### Actual behavior

It does not

### How to Reproduce?

I can reproduce this pretty regularly. I put together a repo on GitHub [1] detailing what I’m seeing (it’s a pretty basic hello world). I also recorded a 2 minute video [2] showing what I’m seeing. The [README file in the repo](https://github.com/edeandrea/quarkus-devservice-postgresql/blob/main/README.md) has a very detailed explanation of the problem & what I'm seeing.

[1] https://github.com/edeandrea/quarkus-devservice-postgresql
[2] https://github.com/edeandrea/quarkus-devservice-postgresql/raw/main/Dev-Services-postgres-failing.mov

### Output of `uname -a` or `ver`

```
Darwin edeandrea-m1pro 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
```

### Output of `java -version`

```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode)
```

### Quarkus version or git rev

2.9.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /Users/edeandre/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4
Java version: 17.0.3, vendor: Eclipse Adoptium, runtime: /Users/edeandre/.sdkman/candidates/java/17.0.3-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.4", arch: "aarch64", family: "mac"
```

**Comment by gastaldi** [comment]
Thanks, @edeandrea, I tried to reproduce this in my M1 but no luck so far. I got two questions for you:
- Does it also happens if you run `mvn test` in your project? 
- Is there any visible interesting output when you add `quarkus.log.category."org.testcontainers".level=FINEST` to your `application.properties`?

**Comment by edeandrea** [comment]
Yes it happens when I run `./mvnw test`. Here's the output with `quarkus.log.category."org.testcontainers".level=FINEST`

```
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ quarkus-devservice-postgresql ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.GreetingResourceTest
2022-05-19 12:40:42,041 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
2022-05-19 12:40:42,240 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-2) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2022-05-19 12:40:52,504 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-2) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2022-05-19 12:40:52,505 INFO  [org.tes.DockerClientFactory] (build-2) Docker host IP address is localhost
2022-05-19 12:40:52,559 INFO  [org.tes.DockerClientFactory] (build-2) Connected to docker: 
  Server Version: 20.10.14
  API Version: 1.41
  Operating System: Alpine Linux v3.15
  Total Memory: 5925 MB
2022-05-19 12:40:52,561 INFO  [org.tes.DockerClientFactory] (build-2) Checking the system...
2022-05-19 12:40:52,562 INFO  [org.tes.DockerClientFactory] (build-2) ✔︎ Docker server version should be at least 1.6.0
2022-05-19 12:40:52,563 INFO  [org.tes.uti.ImageNameSubstitutor] (build-2) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2022-05-19 12:40:52,972 INFO  [org.tes.DockerClientFactory] (build-2) ✔︎ Docker environment should have more than 2GB free disk space
2022-05-19 12:40:53,222 INFO  [🐳 .io/.2]] (build-2) Creating container for image: docker.io/postgres:14.2
2022-05-19 12:40:53,244 INFO  [🐳 .io/.2]] (build-2) Container docker.io/postgres:14.2 is starting: cfc51e6a19e5422c6cbfba9475d2b7f0b6ded351affd051596d2a74bea922c21
2022-05-19 12:40:54,296 INFO  [🐳 .io/.2]] (build-2) Container docker.io/postgres:14.2 started in PT1.099595S
2022-05-19 12:40:54,296 INFO  [io.qua.dev.pos.dep.PostgresqlDevServicesProcessor] (build-2) Dev Services for PostgreSQL started.
2022-05-19 12:40:54,298 INFO  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-2) Dev Services for the default datasource (postgresql) started.
2022-05-19 12:40:54,303 INFO  [io.qua.hib.orm.dep.HibernateOrmProcessor] (build-2) Setting quarkus.hibernate-orm.database.generation=drop-and-create to initialize Dev Services managed database
2022-05-19 12:40:54,450 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.log.category.org.testcontainers.level" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2022-05-19 12:40:54,761 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to localhost:49177 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
2022-05-19 12:40:54,761 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread: <default>) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: Connection to localhost:49177 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:400)
	at org.postgresql.Driver.connect(Driver.java:259)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
	... 12 more

2022-05-19 12:40:54,845 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to localhost:49177 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
2022-05-19 12:40:54,845 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) SQL Error: 0, SQLState: 08001
2022-05-19 12:40:54,845 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) Connection to localhost:49177 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.438 s <<< FAILURE! - in org.acme.GreetingResourceTest
[ERROR] org.acme.GreetingResourceTest.testHelloEndpoint  Time elapsed: 0.001 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: javax.persistence.PersistenceException: [PersistenceUnit: <default>] Unable to build Hibernate SessionFactory
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: <default>] Unable to build Hibernate SessionFactory
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
Caused by: org.postgresql.util.PSQLException: Connection to localhost:49177 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Caused by: java.net.ConnectException: Connection refused

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   GreetingResourceTest.testHelloEndpoint » Runtime java.lang.RuntimeException: F...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.661 s
[INFO] Finished at: 2022-05-19T12:40:55-04:00
[INFO] ------------------------------------------------------------------------
```

**Comment by edeandrea** [comment]
@gastaldi could it be related to the docker daemon i'm running? I'm mostly using Rancher Desktop (I don't even have docker desktop installed on my machine).

**Comment by edeandrea** [comment]
as thats downloading in the background I switched off Rancher Desktop and started up podman. So far I can't seem to reproduce it using podman.

**Comment by gastaldi** [comment]
@edeandrea you can expense Docker Desktop if you need it, talk to Dimitri about it. 

I compared the output and the only difference I noticed is that I don't see the `listening on IPv4 address "0.0.0.0", port 5432` in the logs

**Comment by edeandrea** [comment]
ran it a bunch of times with docker desktop & podman - can't reproduce it. I blew away my rancher desktop instance & re-created it. Ran ok a few times but then started up again.

I'd say go ahead and close this for now. If it crops back up I'll come back & re-open.

**Comment by edeandrea** [comment]
Thank you @gastaldi for looking at it!

**Comment by kiview** [comment]
Does `quarkus dev` keep the containers running? If this is achieved via `reusable` mode in Testcontainers, note that this is an experimental alpha feature and it might not work with alternative container engines, since they might break certain assumptions.

From your logs I see, that your code tried to connect to `localhost:49260`, where was the container actually run, and which port was exposed?

**Comment by therealjsie** [comment]
`quarkus dev` keeps the containers running but I'm not sure how this is implemented. The problems also arise with other commands that don't keep the containers running, e.g. `gradle quarkusTest`. 

Network setup seems finde overall. The targeted URI is correct. The container was run at `localhost:42960` and I was able to connect to the URI from my cli via `psql`. I'm not sure if this is an issue where Testcontainers tries to connect to the DB before it's started and times out right away.

**Comment by kiview** [comment]
The log you shared had no errors from Testcontainers, they came from Liquibase.

**Comment by edeandrea** [comment]
In my original comment when I created this issue I was not using liquibase. Just postgresql. The problem does not exist with any of the other jdbc drivers (MySQL/etc).

I don't know if it's a testcontainers thing or a Quarkus thing. I just know that it consistently doesn't work with rancher desktop but is fine with docker desktop.

**Comment by edeandrea** [comment]
Nope no sample data. Just a REST endpoint and a JPA Entity object.

**Comment by InfoSec812** [comment]
I'm seeing this as well on both a Debian machine and a Fedora 36 machine (podman 4.1.0 and 4.1.1 respectively)... 

```
Database for the default datasource (postgresql) starting: 2022-08-03 11:00:11,185 INFO  [🐳 .io/postgres:14]] (build-22) Container docker.io/postgres:14 is starting: f2749623012b1e8249cdc4fd2abd0d34262c2b53ad66963f8e7592e87dabf402
```

It just hangs at this point.

Installing and using docker works

**Comment by InfoSec812** [comment]
I have also found that with Podman it is apparently only ever the **LAST** service which causes the hang. When inspecting the containers, the service is UP and running, but DevServices does not recognize whatever the last service to complete is. If I add Kafka or SSO or whatever, it's only the last one starting which gets stuck and not just PostgreSQL

**Comment by agoncal** [comment]
I'm giving the Super Heroes workshop to a bunch of developers. The ones Rancher Desktop on Mac M1 (eg. @ggui) can't make the workshop work because of DevServices (TestContainers) pulling the Postgres image. This is the stack trace that they have:

```
2022-09-23 15:56:27,693 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[error]: Build step io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor#launchDatabases threw an exception: java.lang.RuntimeException: java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:312)
at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.launchDatabases(DevServicesDatasourceProcessor.java:125)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
at java.base/java.lang.Thread.run(Thread.java:833)
at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:115)
at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:147)
at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:188)
at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:102)
at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:108)
at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:325)
at io.quarkus.devservices.postgresql.deployment.PostgresqlDevServicesProcessor$1.startDatabase(PostgresqlDevServicesProcessor.java:51)
at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:265)
... 12 more

at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:95)
at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:485)
at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:68)
at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:142)
at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:97)
at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[error]: Build step io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor#launchDatabases threw an exception: java.lang.RuntimeException: java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:312)
at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.launchDatabases(DevServicesDatasourceProcessor.java:125)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
at java.base/java.lang.Thread.run(Thread.java:833)
at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:115)
at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:147)
at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:188)
at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:102)
at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:108)
at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:325)
at io.quarkus.devservices.postgresql.deployment.PostgresqlDevServicesProcessor$1.startDatabase(PostgresqlDevServicesProcessor.java:51)
at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:265)
... 12 more

at io.quarkus.builder.Execution.run(Execution.java:116)
at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:157)
at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
... 9 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:312)
at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.launchDatabases(DevServicesDatasourceProcessor.java:125)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
```

**Comment by GGui** [comment]
I was able to run the container by adding the following environment variables:
export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
export DOCKER_HOST="unix://${HOME}/.rd/docker.sock"

**Comment by kiview** [comment]
@agoncal I think the Rancher Desktop part of the docs should be augmented to include the necessary config, as pointed out by @GGui.

Furthermore, I found the recommendation to set `RYUK_DISABLED=true`. This is *not recommended* for desktop usage and is normally not necessary. I would prefer if we can discuss removing the paragraph, or else highlighting, that this can have unintended consequences.

**Comment by adroste** [comment]
I can confirm the race condition when starting containers with Rancher Desktop. Seems like quarkus continues with the init process before the postgres container/docker network is ready. Docker Desktop works fine.

Env: M1 Mac, macOS 12.6

I think that is is a Rancher Desktop issue rather than a quarkus one. ( https://github.com/rancher-sandbox/rancher-desktop/issues/2609 )

```
2022-09-28 09:50:00,067 INFO  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-62) Dev Services for the default datasource (postgresql) started.
2022-09-28 09:50:00,843 INFO  [io.agr.pool] (Quarkus Main Thread) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
[... flyway output ...]
2022-09-28 09:50:05,932 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:279)
        at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:248)
        at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:147)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
        at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:76)
        at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions2063183959.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions2063183959.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
        at java.base/java.lang.Thread.run(Thread.java:833)


2022-09-28 09:50:05,959 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2022-09-28 09:50:05,959 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2022-09-28 09:50:06,054 WARN  [io.net.uti.con.DefaultPromise] (vert.x-acceptor-thread-0) An exception was thrown by io.vertx.core.net.impl.TCPServerBase$$Lambda$1454/0x0000000801736ed8.operationComplete(): java.lang.IllegalStateException: HttpBinderConfiguration was not found
        at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterBinderAdapter.createHttpServerMetrics(VertxMeterBinderAdapter.java:50)
        at io.vertx.core.http.impl.HttpServerImpl.createMetrics(HttpServerImpl.java:71)
        at io.vertx.core.net.impl.TCPServerBase.lambda$listen$2(TCPServerBase.java:186)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
        at io.vertx.core.net.impl.AsyncResolveConnectHelper.lambda$null$1(AsyncResolveConnectHelper.java:61)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:578)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:425)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:374)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

and 

```
2022-09-28 09:48:41,435 INFO  [org.tes.uti.RyukResourceReaper] (build-26) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2022-09-28 09:48:41,436 INFO  [org.tes.DockerClientFactory] (build-26) Checking the system...
2022-09-28 09:48:41,436 INFO  [org.tes.DockerClientFactory] (build-26) ✔︎ Docker server version should be at least 1.6.0
2022-09-28 09:48:41,450 INFO  [🐳 .io/.2]] (build-26) Creating container for image: docker.io/postgres:14.2
2022-09-28 09:48:41,479 INFO  [org.tes.uti.RegistryAuthLocator] (build-26) Credential helper/store (docker-credential-osxkeychain) does not have credentials for docker.io
2022-09-28 09:48:41,479 WARN  [🐳 .io/.2]] (build-26) Reuse was requested but the environment does not support the reuse of containers
To enable reuse of containers, you must set 'testcontainers.reuse.enable=true' in a file located at /Users/adroste/.testcontainers.properties
2022-09-28 09:48:41,502 INFO  [🐳 .io/.2]] (build-26) Container docker.io/postgres:14.2 is starting: 9c9df89b3c53c727dbde6d9913b84ef6515b33c2e4d16ff8b3c97ad1e49e1455
2022-09-28 09:48:42,899 INFO  [🐳 .io/.2]] (build-26) Container docker.io/postgres:14.2 started in PT1.459478S
2022-09-28 09:48:42,899 INFO  [io.qua.dev.pos.dep.PostgresqlDevServicesProcessor] (build-26) Dev Services for PostgreSQL started.
2022-09-28 09:48:42,900 INFO  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-26) Dev Services for the default datasource (postgresql) started.
2022-09-28 09:48:43,626 INFO  [io.agr.pool] (main) Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
[... flyway output ...]
2022-09-28 09:48:43,756 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to localhost:49160 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.928 s <<< FAILURE! - in org.tkit.portal.rs.internal.AdminUserApiTest
[ERROR] org.tkit.portal.rs.internal.AdminUserApiTest  Time elapsed: 8.928 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database: Connection to localhost:49160 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:49160 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Caused by: org.postgresql.util.PSQLException: Connection to localhost:49160 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Caused by: java.net.ConnectException: Connection refused
```

**Comment by kiview** [comment]
@adroste AFAIK Rancher Desktop has very different timing behavior regarding its networking and exposing ports as compared to Docker, so it breaks Testcontainers' assumptions of a Docker-compatible API.

**Comment by bpasson** [comment]
@gastaldi Any news on this one. The closed issue mentions it has something to do with ports being available on different times for docker-desktop and rancher-desktop. The suggestion is to use different waiting strategy `Wait.forListeningPort()`. Quarkus already uses a customized waiting strategy can this be added as it might help out rancher-desktop users.

**Comment by gastaldi** [comment]
> Quarkus already uses a customized waiting strategy can this be added as it might help out rancher-desktop users.

Added where exactly? In our guides?

**Comment by gastaldi** [comment]
Interesting, can you test and submit a PR? That would be awesome if it worked

**Comment by gsmet** [comment]
Yeah, I was having a look at all this and I think it makes sense.

If you can push a PR combining the existing one with the one waiting for the port to open using `WaitAllStrategy`, it's something we could merge.

**Comment by gsmet** [comment]
Ping us if you have questions but yes, it should be a fairly simple change.

**Comment by bpasson** [comment]
@gsmet @gastaldi  I hit a snag with current main, quarkus-flyway uses flyway 10.10.0, but it seems the change mentioned here https://github.com/flyway/flyway/issues/3780 where flyway is split up per database was not accounted for. This is probably a completely different issue, but I ran into it using one of my many projects to test the postgres container. Is this on the radar?

**Comment by gastaldi** [comment]
Yes, it's described here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10#flyway-10

**Comment by bpasson** [comment]
Good. The notes also tells me how to fix my snag. Thnx @gastaldi
