### ISSUE TITLE
Quarkus GraalVM AWS lambda-Open Telemetry  extension issue

### ISSUE THREAD

**Issue by fazeem84** [quarkusio/quarkus#25708]
### Describe the bug

I have used open Telemetry extension (https://quarkus.io/guides/opentelemetry) to connect Elastic APM server  from our AWS lambda function deployed as cloud Native (https://quarkus.io/guides/amazon-lambda#deploy-to-aws-lambda-custom-native-runtime) runtime 
A `NullPointerException` is raised while hitting the end point in Local
and In AWS Class not found exception (OKHttp Chanel ) is raised
Please find my Gradle file for more info

```gradle
plugins {
    id 'java'
    id 'io.quarkus' version '2.9.1.Final'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation enforcedPlatform("io.quarkus:quarkus-bom:2.9.1.Final")
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    implementation 'io.quarkus:quarkus-resteasy-reactive'
    implementation 'io.quarkus:quarkus-opentelemetry-exporter-otlp'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-rest-client'
    implementation 'io.quarkus:quarkus-amazon-lambda-rest'
}

test {
    useJUnitPlatform()
}
```
Could any one please look into this issue?

### Expected behavior

Expecting Quarkus Open Telemetry extension starts sending the performance data to the server successfully

### Actual behavior

```posh
022-05-20 14:17:56,822 WARN  [io.net.cha.AbstractChannelHandlerContext] (vert.x-eventloop-thread-1) An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:: java.lang.NullPointerException
	at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer$ServerAttributesExtractor.serverName(HttpInstrumenterVertxTracer.java:192)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer$ServerAttributesExtractor.serverName(HttpInstrumenterVertxTracer.java:153)
	at io.opentelemetry.instrumentation.api.instrumenter.http.HttpServerAttributesExtractor.onStart(HttpServerAttributesExtractor.java:79)
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.start(Instrumenter.java:175)
	at io.opentelemetry.instrumentation.api.instrumenter.ServerInstrumenter.start(ServerInstrumenter.java:30)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.InstrumenterVertxTracer.receiveRequest(InstrumenterVertxTracer.java:42)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.InstrumenterVertxTracer.receiveRequest(InstrumenterVertxTracer.java:22)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.OpenTelemetryVertxTracer.receiveRequest(OpenTelemetryVertxTracer.java:35)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.OpenTelemetryVertxTracer.receiveRequest(OpenTelemetryVertxTracer.java:16)
	at io.vertx.core.http.impl.Http1xServerRequest.reportRequestBegin(Http1xServerRequest.java:580)
	at io.vertx.core.http.impl.Http1xServerRequest.handleBegin(Http1xServerRequest.java:153)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:143)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.quarkus.netty.runtime.virtual.VirtualChannel.readInbound(VirtualChannel.java:251)
	at io.quarkus.netty.runtime.virtual.VirtualChannel.doBeginRead(VirtualChannel.java:274)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1400)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:522)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

1. Create a Gradle project using the Gradle file attached in description
2. Create Quarkus Resource class

```java
package org.acme.opentelemetry;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import org.jboss.logging.Logger;

@Path("/hello")
public class TracedResource {

    private static final Logger LOG = Logger.getLogger(TracedResource.class);

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        LOG.info("hello");
        return "hello";
    }
}
```

3. start Quarkus dev
4. hit the end point

### Output of `java -version`

17

### GraalVM version (if different from Java)

17

### Quarkus version or git rev

2.9.1 Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle

**Comment by fazeem84** [comment]
@geoand @patriot1burke 
Any update on this

**Comment by fazeem84** [comment]
@geoand @patriot1burke 
when can we expect this fix to be released ?
or is there anyway I can test the fix is been working?

**Comment by geoand** [comment]
The fix will be in 2.10.

You can of course build the code from source to check and make sure it works

**Comment by fazeem84** [comment]
@geoand 
I have tested my AWS lambda with Quarkus 2.10 pre-release version,
it's started working in my laptop now
but when I deployed it as quarkus native image I am getting following Exception 
`<html>
<body>


2022-06-10 10:14:49,944 FINE  [io.grp.ManagedChannelRegistry] (main) Unable to find OkHttpChannelProvider: java.lang.ClassNotFoundException: io.grpc.okhttp.OkHttpChannelProvider. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments. | 2022-06-10 10:14:49,944 FINE [io.grp.ManagedChannelRegistry] (main) Unable to find OkHttpChannelProvider: java.lang.ClassNotFoundException: io.grpc.okhttp.OkHttpChannelProvider. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments.
-- | --
  | 2022-06-10T11:14:50.080+01:00 | at io.grpc.ManagedChannelRegistry.getHardCodedClasses(ManagedChannelRegistry.java:134)
  | 2022-06-10T11:14:50.080+01:00 | at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:98)
  | 2022-06-10T11:14:50.080+01:00 | at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:41)
  | 2022-06-10T11:14:50.080+01:00 | at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
  | 2022-06-10T11:14:50.080+01:00 | at io.opentelemetry.exporter.internal.grpc.DefaultGrpcExporterBuilder.build(DefaultGrpcExporterBuilder.java:134)
  | 2022-06-10T11:14:50.080+01:00 | at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:152)
  | 2022-06-10T11:14:50.080+01:00 | at io.quarkus.opentelemetry.exporter.otlp.runtime.OtlpRecorder.installBatchSpanProcessorForOtlp(OtlpRecorder.java:37)
  | 2022-06-10T11:14:50.080+01:00 | at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp727556406.deploy_0(Unknown Source)
  | 2022-06-10T11:14:50.080+01:00 | at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp727556406.deploy(Unknown Source)
  | 2022-06-10T11:14:50.080+01:00 | at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
  | 2022-06-10T11:14:50.080+01:00 | at io.quarkus.runtime.Application.start(Application.java:101)
  | 2022-06-10T11:14:50.080+01:00 | at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
  | 2022-06-10T11:14:50.080+01:00 | at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
  | 2022-06-10T11:14:50.080+01:00 | at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
  | 2022-06-10T11:14:50.080+01:00 | at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
  | 2022-06-10T11:14:50.080+01:00 | at io.quarkus.runner.GeneratedMain.main(Unknown Source)
 

<br class="Apple-interchange-newline">
</body>
</html>`

Do I need to create a separate  Issue for this?

**Comment by geoand** [comment]
Can you provide the entire stacktrace?

**Comment by fazeem84** [comment]
@geoand 

PFA
it looks like a  internal error handled inside grpc module(it's visible only when debug log level is enabled)
Our lambda sit's behind API gateway and I am getting successful response from  lambda as well, but it's  seems request is not reaching  the Elastic server APM module ,In my local machine I can find some debug  logs  related Open Telemetry but the same cannot be found in lambda
so do I need to do any kind of setting change in AWS side to make this working?
`
__  ____  __  _____   ___  __ ____  ______ 
--/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
-/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-06-10 11:12:02,547 FINE  [io.grp.ManagedChannelRegistry] (main) Unable to find OkHttpChannelProvider: java.lang.ClassNotFoundException: io.grpc.okhttp.OkHttpChannelProvider. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments.
at io.grpc.ManagedChannelRegistry.getHardCodedClasses(ManagedChannelRegistry.java:134)
at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:98)
at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:41)
at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
at io.opentelemetry.exporter.internal.grpc.DefaultGrpcExporterBuilder.build(DefaultGrpcExporterBuilder.java:134)
at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:152)
at io.quarkus.opentelemetry.exporter.otlp.runtime.OtlpRecorder.installBatchSpanProcessorForOtlp(OtlpRecorder.java:37)
at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp727556406.deploy_0(Unknown Source)
at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp727556406.deploy(Unknown Source)
at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
at io.quarkus.runtime.Application.start(Application.java:101)
at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2022-06-10 11:12:02,551 FINE  [io.grp.ManagedChannelRegistry] (main) Service loader found io.grpc.netty.NettyChannelProvider@7b4c8c9e
2022-06-10 11:12:02,561 FINE  [io.grp.net.Utils] (main) Epoll is not available, using Nio.
2022-06-10 11:12:02,565 FINE  [io.grp.NameResolverRegistry] (main) Service loader found io.grpc.internal.DnsNameResolverProvider@3a65c4cd
2022-06-10 11:12:02,567 FINE  [io.grp.net.GrpcSslContexts] (main) Selecting JDK with provider SunJSSE version 17
2022-06-10 11:12:02,611 FINE  [io.grp.int.ManagedChannelImplBuilder] (main) Unable to apply census stats: java.lang.ClassNotFoundException: io.grpc.census.InternalCensusStatsAccessor. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments.
at io.grpc.internal.ManagedChannelImplBuilder.getEffectiveInterceptors(ManagedChannelImplBuilder.java:645)
at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
at io.opentelemetry.exporter.internal.grpc.DefaultGrpcExporterBuilder.build(DefaultGrpcExporterBuilder.java:162)
at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:152)
at io.quarkus.opentelemetry.exporter.otlp.runtime.OtlpRecorder.installBatchSpanProcessorForOtlp(OtlpRecorder.java:37)
at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp727556406.deploy_0(Unknown Source)
at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp727556406.deploy(Unknown Source)
at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
at io.quarkus.runtime.Application.start(Application.java:101)
at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2022-06-10 11:12:02,611 FINE  [io.grp.int.ManagedChannelImplBuilder] (main) Unable to apply census stats: java.lang.ClassNotFoundException: io.grpc.census.InternalCensusTracingAccessor. This exception was synthesized during native image building from a call to java.lang.Class.forName(String) with constant arguments.
at io.grpc.internal.ManagedChannelImplBuilder.getEffectiveInterceptors(ManagedChannelImplBuilder.java:681)
at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
at io.opentelemetry.exporter.internal.grpc.DefaultGrpcExporterBuilder.build(DefaultGrpcExporterBuilder.java:162)
at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:152)
at io.quarkus.opentelemetry.exporter.otlp.runtime.OtlpRecorder.installBatchSpanProcessorForOtlp(OtlpRecorder.java:37)
at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp727556406.deploy_0(Unknown Source)
at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp727556406.deploy(Unknown Source)
at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
at io.quarkus.runtime.Application.start(Application.java:101)
at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2022-06-10 11:12:02,612 FINE  [io.grp.LoadBalancerRegistry] (main) Service loader found Provider{policy=round_robin, priority=5, available=true}
2022-06-10 11:12:02,612 FINE  [io.grp.LoadBalancerRegistry] (main) Service loader found PickFirstLoadBalancerProvider{policy=pick_first, priority=5, available=true}
2022-06-10 11:12:02,664 DEBUG [io.qua.agr.run.DataSources] (main) Started datasource <default> connected to 
2022-06-10 11:12:02,669 FINE  [io.ope.ins.api.int.EmbeddedInstrumentationProperties] (main) Did not find embedded instrumentation properties file META-INF/io/opentelemetry/instrumentation/io.quarkus.opentelemetry.properties
2022-06-10 11:12:02,669 FINE  [io.ope.ins.api.int.EmbeddedInstrumentationProperties] (main) Did not find embedded instrumentation properties file META-INF/io/opentelemetry/instrumentation/io.quarkus.opentelemetry.properties
2022-06-10 11:12:02,669 FINE  [io.ope.ins.api.int.EmbeddedInstrumentationProperties] (main) Did not find embedded instrumentation properties file META-INF/io/opentelemetry/instrumentation/io.quarkus.opentelemetry.properties
2022-06-10 11:12:02,669 FINE  [io.ope.ins.api.int.EmbeddedInstrumentationProperties] (main) Did not find embedded instrumentation properties file META-INF/io/opentelemetry/instrumentation/io.quarkus.opentelemetry.properties
2022-06-10 11:12:02,669 FINE  [io.ope.ins.api.int.EmbeddedInstrumentationProperties] (main) Did not find embedded instrumentation properties file META-INF/io/opentelemetry/instrumentation/io.quarkus.opentelemetry.properties
2022-06-10 11:12:02,671 DEBUG [io.qua.ver.cor.run.VertxCoreRecorder] (main) Vertx has Native Transport Enabled: false`

**Comment by geoand** [comment]
Okay thanks. 

Best open a new issue for this

**Comment by patriot1burke** [comment]
@geoand I screwed up and didn't review this well enough.  The fix you instituted breaks non-native Lambda deployments as our poll loop doesn't run in JVM lambda deployments.  I don't think the connection information is available when running lambda in JVM mode.

**Comment by patriot1burke** [comment]
@geoand You are trying to discover the client IP address/host here?

**Comment by geoand** [comment]
Pretty much, yeah

**Comment by patriot1burke** [comment]
Ok, I'll have a new PR for this.  Will need to be extract from the lambda http event.  I think client IP is available, but the docs aren't clear on what "sourceIp" is.

**Comment by geoand** [comment]
Understood, thanks

**Comment by geoand** [comment]
Definitely, if we can't have an IP, we'll have to be defensive

**Comment by fazeem84** [comment]
I have raised another issue on the back of this issue [](https://github.com/quarkusio/quarkus/issues/26250)

**Comment by patriot1burke** [comment]
@geoand IMO, open telemetry should not barf if the client ip is null and a corresponding bug should be set there.  I cannot guarantee that it will be set with this lambda integration.

**Comment by geoand** [comment]
Yeah, let's be on the safe side here. I'll open a tiny PR making things more defensive.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/26474 is what I have in mind
