### ISSUE TITLE
Compiling a `quarkus-cli` application to a static binary breaks `picocli`

### ISSUE THREAD

**Issue by andreaTP** [quarkusio/quarkus#25762]
### Describe the bug

Trying to compile a Quarkus Cli application to fully static binaries "breaks" `picocli`.

cc. @remkop

### Expected behavior

The executable should run in the same way with Java and when compiled.

### Actual behavior

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-05-24 16:00:11,702 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT native (powered by Quarkus 2.9.1.Final) started in 0.012s. 
2022-05-24 16:00:11,705 INFO  [io.quarkus] (main) Profile prod activated. 
2022-05-24 16:00:11,705 INFO  [io.quarkus] (main) Installed features: [cdi, picocli]
2022-05-24 16:00:11,706 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): picocli.CommandLine$InitializationException: picocli.CommandLine$AutoHelpMixin@483680e0 is not a command: it has no @Command, @Option, @Parameters or @Unmatched annotations
        at picocli.CommandLine$Model$CommandReflection.validateCommandSpec(CommandLine.java:11680)
        at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11510)
        at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6236)
        at picocli.CommandLine$Model$CommandSpec.mixinStandardHelpOptions(CommandLine.java:7220)
        at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11505)
        at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6236)
        at picocli.CommandLine.<init>(CommandLine.java:227)
        at picocli.CommandLine.<init>(CommandLine.java:221)
        at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory.create(DefaultPicocliCommandLineFactory.java:43)
        at io.quarkus.picocli.runtime.DefaultPicocliCommandLineFactory_ClientProxy.create(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliCommandLineProducer.picocliCommandLine(PicocliCommandLineProducer.java:23)
        at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.create(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliCommandLineProducer_ProducerMethod_picocliCommandLine_9215511af8bf79a5b9761758f9829960bca3fec0_Bean.get(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliRunner_Bean.create(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(Unknown Source)
        at io.quarkus.picocli.runtime.PicocliRunner_Bean.get(Unknown Source)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:467)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:480)
        at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:59)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:120)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-05-24 16:00:11,707 INFO  [io.quarkus] (main) code-with-quarkus stopped in 0.001s
```

### How to Reproduce?

- clone this repo using the `quarkus-picocli` branch: https://github.com/andreaTP/test_graal_zig_cc/tree/quarkus-picocli
- run `docker build . -t graal_zigcc --progress=plain`
- and execute the static binary: `docker run --rm -it graal_zigcc`

**Comment by andreaTP** [comment]
More bisecting, the actual difference is in the `jar` used to build the native image.
Using `mvn clean package -Pnative` `native-image` command target this jar 
[code-with-quarkus-1.0.0-SNAPSHOT-runner_2.zip](https://github.com/quarkusio/quarkus/files/8773413/code-with-quarkus-1.0.0-SNAPSHOT-runner_2.zip)

instead using `mvn clean package -Dquarkus.package.type=native-sources` generates in the `/target/native-sources` folder this jar: 
[code-with-quarkus-1.0.0-SNAPSHOT-runner_1.zip](https://github.com/quarkusio/quarkus/files/8773414/code-with-quarkus-1.0.0-SNAPSHOT-runner_1.zip)

The file size is slightly different:
```
     93811 25 May 18:10 code-with-quarkus-1.0.0-SNAPSHOT-runner_1.zip
     94455 25 May 18:13 code-with-quarkus-1.0.0-SNAPSHOT-runner_2.zip
```
Looks like "something" is missing from the Jar generated with `native-sources`

**Comment by andreaTP** [comment]
The diff shows that there is a difference in the generated `io/quarkus/runner/AutoFeature.class`.

Decompiling it shows a bunch of missing `registerClass` in the "not working" one.

But now debugging is a little too steep for my knowledge of Quarkus 🙂  I drop the ball in your court @geoand 🙂

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/25803 is the fix.

Thanks for reporting!
