### ISSUE TITLE
Gradle `quarkusBuild` fails with `ZipFile invalid LOC header` in `SmallRyeOpenApiProcessor`

### ISSUE THREAD

**Issue by snazy** [quarkusio/quarkus#25788]
### Describe the bug

A repeated `./gradlew quarkusBuild` runs into the following exception from the `SmallRyeOpenApiProcessor`.

In this case, the openapi classes and spec files are pulled from a dependency and are not located in the Gradle project.

```
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.io.UncheckedIOException: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.addStaticModelIfExist(SmallRyeOpenApiProcessor.java:893)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.findStaticModels(SmallRyeOpenApiProcessor.java:840)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.generateStaticModel(SmallRyeOpenApiProcessor.java:774)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:671)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:1023)
        at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1033)
        at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:483)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.base/java.io.InputStream.readNBytes(InputStream.java:396)
        at java.base/java.io.InputStream.readAllBytes(InputStream.java:333)
        at io.quarkus.deployment.util.IoUtil.readBytes(IoUtil.java:18)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.addStaticModelIfExist(SmallRyeOpenApiProcessor.java:888)
        ... 14 more
```

This consistently happens in [this PR](https://github.com/projectnessie/nessie/pull/4274), which can serve as a reproducer:
```
$ ./gradlew :ser:quar-ser:quarkusBuild
$ echo "" > model/src/main/resources/META-INF/openapi.yaml
$ ./gradlew :ser:quar-ser:quarkusBuild
```

### Quarkus version or git rev

2.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by snazy** [comment]
With #25790 applied on top of `main`, the error message confirms that it's processing a file from the dependency's jar:
```
        [error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.io.UncheckedIOException: While processing jar:file:///home/snazy/devel/projectnessie/nessie/gradle/model/build/libs/nessie-model-0.30.1-SNAPSHOT.jar!/META-INF/openapi.yaml for META-INF/openapi.yaml
...
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.addStaticModelIfExist(SmallRyeOpenApiProcessor.java:889)
```

**Comment by snazy** [comment]
Applying a similar change like #4652 fixes this issue. Updated #25790 with the change.

**Comment by snazy** [comment]
Note: there seem to be similar issues in these places (subset of call sites of `java.net.URL#openStream`):
* `io.quarkus.kafka.client.runtime.KafkaRecorder#extractLibraryFile`
* `io.quarkus.liquibase.mongodb.runtime.graal.SubstituteLiquibaseUtil#getBuildInfo`
* `io.quarkus.qute.runtime.EngineProducer.ResourceTemplateLocation#read`
* `io.quarkus.runtime.util.ClassPathUtils#readStream`
* `io.quarkus.hibernate.orm.deployment.xml.QuarkusMappingFileParser#parse`
* `io.quarkus.test.QuarkusProdModeTest#withConfigurationResource`
* `io.quarkus.test.QuarkusUnitTest#withConfigurationResource`
