### ISSUE TITLE
CloudBuild (GCP) Failed to authenticate with registry when using Jib

### ISSUE THREAD

**Issue by anthonydenecheau** [quarkusio/quarkus#25793]
### Describe the bug

In CloudBuild environment, i try to deploy an image with Jib on Artifact Registry. I set authentication but i still have an issue  `403 Forbidden`.
When we use `quarkus.container-image.push=true`, I need more information on the different platforms used to publish our images and in particular in the case that interests me on GAR

### Expected behavior

Image has been published on artifact registry using Jib

### Actual behavior

`{"errors":[{"code":"DENIED","message":"Permission \"artifactregistry.repositories.downloadArtifacts\" denied on resource ... }"`

### Output of `uname -a` or `ver`

Linux 84592f6948b9 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 Linux

### Output of `java -version`

17.0.3

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.3, Docker version 20.10.12, build e91ed57

### Additional information

**1. Application.properties**

```
quarkus.native.container-build=true
quarkus.native.container-runtime=docker
quarkus.native.native-image-xmx=4G
quarkus.native.enable-https-url-handler=true
quarkus.native.report-exception-stack-traces=true

quarkus.jib.base-native-image=registry.access.redhat.com/ubi8/ubi-minimal
quarkus.container-image.build=true
quarkus.container-image.builder=jib
quarkus.container-image.push=true
quarkus.container-image.image=${GCP_IMAGE_NAME}
```

2. cloudbuild.yaml

```
steps:
- id: packageApp
  name: docker.io/anthonydenecheau/quarkus-maven-build-native-image:1.0
  entrypoint: bash
  args:
    - '-c'
    - |
      echo -e $(gcloud --quiet \
        --impersonate-service-account project-service-account@scc-build-docker.iam.gserviceaccount.com \
        auth configure-docker $_REGION-docker.pkg.dev)

      echo "************  ~/.docker/config.json ************"
      cat ~/.docker/config.json

      mvn clean package -Pnative -Dnative-image.docker-build=true \
      -Dmaven.test.skip=true -Dquarkus.profile=prod \
      -Dquarkus.native.additional-build-args=--initialize-at-run-time=jdk.internal.platform.cgroupv2.CgroupV2Subsystem
  env:
  - "SHORT_SHA=$SHORT_SHA"
  - "GCP_IMAGE_NAME=$_REGION-docker.pkg.dev/$PROJECT_ID/$_SERVICE_NAME/$_SERVICE_NAME:$SHORT_SHA"
  - "DOCKER_CONFIG=~/.docker/config.json"
```

3. trace/logs

```
Adding credentials for: europe-west3-docker.pkg.dev
Docker configuration file updated.

************  ~/.docker/config.json ************
{
  "auths": {
    "europe-west3-docker.pkg.dev": {
      "auth": "b2F1dGgyYWNjZXNzdG9rZW46eWEyOS5jLmIwQVh2MHpUTmt5OE9rYU..."
    },
   (....)
}
```

```
[ERROR] Caused by: com.google.cloud.tools.jib.http.ResponseException: 403 Forbidden
[ERROR] GET https://europe-west3-docker.pkg.dev/v2/token?service=europe-west3-docker.pkg.dev&scope=repository:scc-build-docker/show-service/show-service:pull,push
[ERROR] {"errors":[{"code":"DENIED","message":"Permission \"artifactregistry.repositories.downloadArtifacts\" denied on resource \"projects/scc-build-docker/locations/europe-west3/repositories/show-service\" (or it may not exist)"}]}
[ERROR]
```

**Comment by geoand** [comment]
Can you please paste a larger part of the stacktrace?

Also, it's not clear to me (having never used `GCP`) where you are setting the authentication

**Comment by anthonydenecheau** [comment]
Yes sure, here it is

```
# Printing build artifacts to: /project/show-service-0.0.1-SNAPSHOT-runner.build_artifacts.txt
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 0:0 -v /workspace/target/show-service-0.0.1-SNAPSHOT-native-image-source-jar:/project:z --entrypoint /bin/bash quay.io/quarkus/ubi-quarkus-native-image:21.2-java11 -c objcopy --strip-debug show-service-0.0.1-SNAPSHOT-runner
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] No container image registry was set, so 'docker.io' will be used
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Starting container image build
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] Base image 'registry.access.redhat.com/ubi8/ubi-minimal' does not use a specific image digest - build may not be reproducible
[WARNING] [org.apache.commons.logging.impl] Attribute org.apache.commons.logging.Log is not supported. Value org.apache.commons.logging.impl.NoOpLog will be ignored.
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Using base image with digest: sha256:e83a3146aa8d34dccfb99097aa79a3914327942337890aa6f73911996a80ebb8
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:08 min
[INFO] Finished at: 2022-05-25T16:36:42Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.2.1.Final:build (default) on project show-service: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromNative threw an exception: java.lang.RuntimeException: Unable to create container image
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:194)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromNative(JibProcessor.java:169)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: com.google.cloud.tools.jib.api.RegistryAuthenticationFailedException: Failed to authenticate with registry europe-west3-docker.pkg.dev/scc-build-docker/show-service/show-service because: 403 Forbidden
[ERROR] GET https://europe-west3-docker.pkg.dev/v2/token?service=europe-west3-docker.pkg.dev&scope=repository:scc-build-docker/show-service/show-service:pull,push
[ERROR] {"errors":[{"code":"DENIED","message":"Permission \"artifactregistry.repositories.downloadArtifacts\" denied on resource \"projects/scc-build-docker/locations/europe-west3/repositories/show-service\" (or it may not exist)"}]}
[ERROR] 
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticate(RegistryAuthenticator.java:306)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticate(RegistryAuthenticator.java:258)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticatePush(RegistryAuthenticator.java:191)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryClient.doBearerAuth(RegistryClient.java:338)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryClient.doBearerAuth(RegistryClient.java:328)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryClient.doPushBearerAuth(RegistryClient.java:310)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:65)
[ERROR] 	at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:35)
[ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
[ERROR] 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
[ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] Caused by: com.google.cloud.tools.jib.http.ResponseException: 403 Forbidden
[ERROR] GET https://europe-west3-docker.pkg.dev/v2/token?service=europe-west3-docker.pkg.dev&scope=repository:scc-build-docker/show-service/show-service:pull,push
[ERROR] {"errors":[{"code":"DENIED","message":"Permission \"artifactregistry.repositories.downloadArtifacts\" denied on resource \"projects/scc-build-docker/locations/europe-west3/repositories/show-service\" (or it may not exist)"}]}
[ERROR] 
[ERROR] 	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:329)
[ERROR] 	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:250)
[ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticate(RegistryAuthenticator.java:284)
[ERROR] 	... 13 more
[ERROR] Caused by: com.google.api.client.http.HttpResponseException: 403 Forbidden
[ERROR] GET https://europe-west3-docker.pkg.dev/v2/token?service=europe-west3-docker.pkg.dev&scope=repository:scc-build-docker/show-service/show-service:pull,push
[ERROR] {"errors":[{"code":"DENIED","message":"Permission \"artifactregistry.repositories.downloadArtifacts\" denied on resource \"projects/scc-build-docker/locations/europe-west3/repositories/show-service\" (or it may not exist)"}]}
[ERROR] 
[ERROR] 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1113)
[ERROR] 	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:323)
[ERROR] 	... 15 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
```

**Comment by geoand** [comment]
I just that you are using Quarkus `2.2.1.Final`. That is a pretty old version at this point, so I would suggest trying with `2.9.2.Final` and if there is still a problem, post the new stacktrace

**Comment by anthonydenecheau** [comment]
The problem is still here 

```
Step #0 - "packageApp": ========================================================================================================================
Step #0 - "packageApp": GraalVM Native Image: Generating 'show-service-0.0.1-SNAPSHOT-runner'...
Step #0 - "packageApp": ========================================================================================================================
Step #0 - "packageApp": [1/7] Initializing...                                                                                    (7.6s @ 0.62GB)
Step #0 - "packageApp":  Version info: 'GraalVM 22.0.0.2 Java 11 CE'
Step #0 - "packageApp":  16 user-provided feature(s)
Step #0 - "packageApp":   - com.google.cloud.nativeimage.features.SpannerFeature
Step #0 - "packageApp":   - com.google.cloud.nativeimage.features.cloudfunctions.CloudFunctionsFeature
Step #0 - "packageApp":   - com.google.cloud.nativeimage.features.core.GoogleJsonClientFeature
Step #0 - "packageApp":   - com.google.cloud.nativeimage.features.core.GrpcNettyFeature
Step #0 - "packageApp":   - com.google.cloud.nativeimage.features.core.OpenCensusFeature
Step #0 - "packageApp":   - com.google.cloud.nativeimage.features.gcp.CloudSqlFeature
Step #0 - "packageApp":   - com.google.cloud.nativeimage.features.spring.SpringTraceFeature
Step #0 - "packageApp":   - com.oracle.svm.thirdparty.gson.GsonFeature
Step #0 - "packageApp":   - io.quarkus.caffeine.runtime.graal.CacheConstructorsAutofeature
Step #0 - "packageApp":   - io.quarkus.hibernate.orm.runtime.graal.DisableLoggingAutoFeature
Step #0 - "packageApp":   - io.quarkus.jdbc.postgresql.runtime.graal.SQLXMLFeature
Step #0 - "packageApp":   - io.quarkus.runner.AutoFeature
Step #0 - "packageApp":   - io.quarkus.runtime.graal.DisableLoggingAutoFeature
Step #0 - "packageApp":   - io.quarkus.runtime.graal.ResourcesFeature
Step #0 - "packageApp":   - org.hibernate.graalvm.internal.GraalVMStaticAutofeature
Step #0 - "packageApp":   - org.hibernate.graalvm.internal.QueryParsingSupport
Step #0 - "packageApp": 06:31:54,590 WARNING [com.goo.clo.nat.fea.NativeImageUtils] Failed to find com.google.protobuf.DescriptorProtos on the classpath for reflection.
Step #0 - "packageApp": 06:31:54,619 WARNING [com.goo.clo.nat.fea.NativeImageUtils] Failed to find com.google.api.FieldBehavior on the classpath for reflection.
Step #0 - "packageApp": [2/7] Performing analysis...  [*********]                                                               (34.4s @ 1.48GB)
Step #0 - "packageApp": 06:31:56,312 INFO  [org.jbo.res.res.i18n] RESTEASY002225: Deploying javax.ws.rs.core.Application: class com.scc.show.ShowApplication
Step #0 - "packageApp":   17,802 (95.69%) of 18,603 classes reachable
Step #0 - "packageApp":   26,437 (66.12%) of 39,982 fields reachable
Step #0 - "packageApp":   88,683 (80.95%) of 109,558 methods reachable
Step #0 - "packageApp":      662 classes,   429 fields, and 2,323 methods registered for reflection
Step #0 - "packageApp":       68 classes,    88 fields, and    54 methods registered for JNI access
Step #0 - "packageApp": [3/7] Building universe...                                                                               (3.5s @ 2.14GB)
Step #0 - "packageApp": [4/7] Parsing methods...      [**]                                                                       (4.1s @ 1.31GB)
Step #0 - "packageApp": [5/7] Inlining methods...     [*****]                                                                    (6.1s @ 1.86GB)
Step #0 - "packageApp": [6/7] Compiling methods...    [*****]                                                                   (22.9s @ 2.27GB)
Step #0 - "packageApp": [7/7] Creating image...                                                                                  (8.4s @ 2.58GB)
Step #0 - "packageApp":   32.72MB (40.51%) for code area:   58,921 compilation units
Step #0 - "packageApp":   39.43MB (48.81%) for image heap:  12,048 classes and 508,246 objects
Step #0 - "packageApp":    8.63MB (10.68%) for other data
Step #0 - "packageApp":   80.78MB in total
Step #0 - "packageApp": ------------------------------------------------------------------------------------------------------------------------
Step #0 - "packageApp": Top 10 packages in code area:                               Top 10 object types in image heap:
Step #0 - "packageApp":    1.67MB sun.security.ssl                                    14.36MB byte[] for general heap data
Step #0 - "packageApp": 1019.55KB java.util                                            4.27MB java.lang.Class
Step #0 - "packageApp":  890.11KB com.oracle.svm.core.reflect                          3.58MB java.lang.String
Step #0 - "packageApp":  687.99KB com.sun.crypto.provider                              3.00MB byte[] for java.lang.String
Step #0 - "packageApp":  571.71KB org.hibernate.hql.internal.antlr                     1.43MB java.util.LinkedHashMap
Step #0 - "packageApp":  495.00KB io.quarkus.runtime.generated                       832.00KB java.lang.reflect.Method
Step #0 - "packageApp":  490.04KB sun.security.x509                                  695.23KB java.lang.String[]
Step #0 - "packageApp":  455.23KB org.postgresql.jdbc                                685.31KB java.util.HashMap$Node
Step #0 - "packageApp":  434.73KB java.lang                                          672.27KB com.oracle.svm.core.util.LazyFinalReference
Step #0 - "packageApp":  427.95KB java.util.concurrent                               568.91KB byte[] for method metadata
Step #0 - "packageApp":       ... 896 additional packages                                 ... 4260 additional object types
Step #0 - "packageApp":                                            (use GraalVM Dashboard to see all)
Step #0 - "packageApp": ------------------------------------------------------------------------------------------------------------------------
Step #0 - "packageApp":                       12.9s (13.7% of total time) in 113 GCs | Peak RSS: 5.15GB | CPU load: 13.45
Step #0 - "packageApp": ------------------------------------------------------------------------------------------------------------------------
Step #0 - "packageApp": Produced artifacts:
Step #0 - "packageApp":  /project/show-service-0.0.1-SNAPSHOT-runner (executable)
Step #0 - "packageApp":  /project/show-service-0.0.1-SNAPSHOT-runner.build_artifacts.txt
Step #0 - "packageApp": ========================================================================================================================
Step #0 - "packageApp": Finished generating 'show-service-0.0.1-SNAPSHOT-runner' in 1m 33s.
Step #0 - "packageApp": [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 0:0 -v /workspace/target/show-service-0.0.1-SNAPSHOT-native-image-source-jar:/project:z --entrypoint /bin/bash quay.io/quarkus/ubi-quarkus-native-image:22.0-java11 -c objcopy --strip-debug show-service-0.0.1-SNAPSHOT-runner
Step #0 - "packageApp": [INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Starting (local) container image build for native binary using jib.
Step #0 - "packageApp": [INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] No container image registry was set, so 'docker.io' will be used
Step #0 - "packageApp": [WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] Base image 'registry.access.redhat.com/ubi8/ubi-minimal' does not use a specific image digest - build may not be reproducible
Step #0 - "packageApp": [WARNING] [org.apache.commons.logging.impl] Attribute org.apache.commons.logging.Log is not supported. Value org.apache.commons.logging.impl.NoOpLog will be ignored.
Step #0 - "packageApp": [INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Using base image with digest: sha256:e83a3146aa8d34dccfb99097aa79a3914327942337890aa6f73911996a80ebb8
Step #0 - "packageApp": [INFO] ------------------------------------------------------------------------
Step #0 - "packageApp": [INFO] BUILD FAILURE
Step #0 - "packageApp": [INFO] ------------------------------------------------------------------------
Step #0 - "packageApp": [INFO] Total time:  02:31 min
Step #0 - "packageApp": [INFO] Finished at: 2022-05-27T06:33:24Z
Step #0 - "packageApp": [INFO] ------------------------------------------------------------------------
Step #0 - "packageApp": [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.9.2.Final:build (default) on project show-service: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Step #0 - "packageApp": [ERROR] 	[error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromNative threw an exception: java.lang.RuntimeException: Unable to create container image
Step #0 - "packageApp": [ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:240)
Step #0 - "packageApp": [ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromNative(JibProcessor.java:206)
Step #0 - "packageApp": [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #0 - "packageApp": [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Step #0 - "packageApp": [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #0 - "packageApp": [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Step #0 - "packageApp": [ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
Step #0 - "packageApp": [ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
Step #0 - "packageApp": [ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
Step #0 - "packageApp": [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
Step #0 - "packageApp": [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
Step #0 - "packageApp": [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
Step #0 - "packageApp": [ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Step #0 - "packageApp": [ERROR] Caused by: com.google.cloud.tools.jib.api.RegistryAuthenticationFailedException: Failed to authenticate with registry europe-west3-docker.pkg.dev/scc-build-docker/show-service/show-service because: 403 Forbidden
Step #0 - "packageApp": [ERROR] GET https://europe-west3-docker.pkg.dev/v2/token?service=europe-west3-docker.pkg.dev&scope=repository:scc-build-docker/show-service/show-service:pull,push
Step #0 - "packageApp": [ERROR] {"errors":[{"code":"DENIED","message":"Permission \"artifactregistry.repositories.downloadArtifacts\" denied on resource \"projects/scc-build-docker/locations/europe-west3/repositories/show-service\" (or it may not exist)"}]}
Step #0 - "packageApp": [ERROR] 
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticate(RegistryAuthenticator.java:305)
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticate(RegistryAuthenticator.java:257)
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticatePush(RegistryAuthenticator.java:190)
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.registry.RegistryClient.doBearerAuth(RegistryClient.java:336)
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.registry.RegistryClient.doBearerAuth(RegistryClient.java:326)
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.registry.RegistryClient.doPushBearerAuth(RegistryClient.java:308)
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:66)
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:35)
Step #0 - "packageApp": [ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
Step #0 - "packageApp": [ERROR] 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
Step #0 - "packageApp": [ERROR] 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
Step #0 - "packageApp": [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Step #0 - "packageApp": [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Step #0 - "packageApp": [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
Step #0 - "packageApp": [ERROR] Caused by: com.google.cloud.tools.jib.http.ResponseException: 403 Forbidden
Step #0 - "packageApp": [ERROR] GET https://europe-west3-docker.pkg.dev/v2/token?service=europe-west3-docker.pkg.dev&scope=repository:scc-build-docker/show-service/show-service:pull,push
Step #0 - "packageApp": [ERROR] {"errors":[{"code":"DENIED","message":"Permission \"artifactregistry.repositories.downloadArtifacts\" denied on resource \"projects/scc-build-docker/locations/europe-west3/repositories/show-service\" (or it may not exist)"}]}
Step #0 - "packageApp": [ERROR] 
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:355)
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:266)
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticate(RegistryAuthenticator.java:283)
Step #0 - "packageApp": [ERROR] 	... 13 more
Step #0 - "packageApp": [ERROR] Caused by: com.google.api.client.http.HttpResponseException: 403 Forbidden
Step #0 - "packageApp": [ERROR] GET https://europe-west3-docker.pkg.dev/v2/token?service=europe-west3-docker.pkg.dev&scope=repository:scc-build-docker/show-service/show-service:pull,push
Step #0 - "packageApp": [ERROR] {"errors":[{"code":"DENIED","message":"Permission \"artifactregistry.repositories.downloadArtifacts\" denied on resource \"projects/scc-build-docker/locations/europe-west3/repositories/show-service\" (or it may not exist)"}]}
Step #0 - "packageApp": [ERROR] 
Step #0 - "packageApp": [ERROR] 	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
Step #0 - "packageApp": [ERROR] 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
Step #0 - "packageApp": [ERROR] 	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:349)
Step #0 - "packageApp": [ERROR] 	... 15 more
Step #0 - "packageApp": [ERROR] -> [Help 1]
Step #0 - "packageApp": [ERROR] 
Step #0 - "packageApp": [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
Step #0 - "packageApp": [ERROR] Re-run Maven using the -X switch to enable full debug logging.
Step #0 - "packageApp": [ERROR] 
Step #0 - "packageApp": [ERROR] For more information about the errors and possible solutions, please read the following articles:
Step #0 - "packageApp": [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Finished Step #0 - "packageApp"
ERROR
ERROR: build step 0 "docker.io/anthonydenecheau/quarkus-maven-build-native-image:1.0" failed: step exited with non-zero status: 1
```

Maybe @loicmathieu has already faced this kind of problem. Sounds like a quarkus and gcp integration problem. Don't you think so?

**Comment by geoand** [comment]
Hard to tell, I have no used GCP...

**Comment by anthonydenecheau** [comment]
Could you make a call to @loicmathieu ? ;)

**Comment by geoand** [comment]
Seems like you have already pinged him :)

**Comment by anthonydenecheau** [comment]
I successfully built and pushed the image to the artifact registry (bare metal) by adding this
```
       gcloud --quiet --impersonate-service-account project-service-account@scc-build-docker.iam.gserviceaccount.com auth configure-docker $_REGION-docker.pkg.dev
       gcloud config set project scc-build-docker
       gcloud artifacts repositories describe $_SERVICE_NAME --location=$_REGION

```
I think I have isolated the problem and it seems to come from my declared docker image in my CloudBuild: docker.io/anthonydenecheau/quarkus-maven-build-native-image:1.0

Dockerfile

```
FROM google/cloud-sdk:alpine
MAINTAINER "Anthony Denecheau <anthony.denecheau@gmail.com>"

# Install prerequisites
RUN apk update
RUN apk add --no-cache curl tar bash procps openssl jq vim docker maven

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

# GCP configuration
WORKDIR /

# GCP extra components install
RUN gcloud components update --quiet && \
# skim down the size of the install
    gcloud components remove bq --quiet && \
    rm -Rf /google-cloud-sdk/.install
```

I must not have the same rights s/ CloudBuild

**Comment by loicmathieu** [comment]
@anthonydenecheau I never use JIB but the issue seems to be with authenticating to Google GAR from your CI.
I did it with some gcloud commands, I can give you those commands tuesday if you still needs them.

**Comment by anthonydenecheau** [comment]
OK @loicmathieu, yes it will be pretty cool to get them.
in the meantime, I will continue to analyze the problem on the docker image side

**Comment by loicmathieu** [comment]
With gcloud you can do the following to authenticate to GCP:

```
                        gcloud auth activate-service-account --key-file=${FILE}
                        gcloud --quiet config set project ${GCP_PROJECT_ID}
                        gcloud --quiet config set compute/zone europe-west4
                        gcloud --quiet container clusters get-credentials my-gke-cluster
```

Your service account must have the correct right.

**Comment by anthonydenecheau** [comment]
Hi Loic,

Is it possible to use `gcloud auth print-access-token` instead of `gcloud auth activate-service-account` ?

BTW, How can I get credentials ? In my environment, I don't have a cluster. I run a cloud build within a projet. I check that service account have the correct right.

Step in cloudbuild.yaml looks like

```
- id: packageApp
  name: docker.io/anthonydenecheau/quarkus-maven-build-native-image:1.4
  entrypoint: bash
  args:
    - '-c'
    - |

      gcloud auth print-access-token \
        --impersonate-service-account project-service-account@scc-build-docker.iam.gserviceaccount.com | docker login \
        -u oauth2accesstoken \
        --password-stdin https://$_REGION-docker.pkg.dev

      echo "************  ~/.docker/config.json (2) ************"
      cat ~/.docker/config.json
      
      mvn clean package -Pnative -Dnative-image.docker-build=true \
      -Dmaven.test.skip=true -Dquarkus.profile=prod \
      -Dquarkus.native.additional-build-args=--initialize-at-run-time=jdk.internal.platform.cgroupv2.CgroupV2Subsystem

  env:
  - "SHORT_SHA=$SHORT_SHA"
  - "GCP_IMAGE_NAME=$_REGION-docker.pkg.dev/$PROJECT_ID/$_SERVICE_NAME/$_SERVICE_NAME:$SHORT_SHA"

```

**Comment by loicmathieu** [comment]
> Is it possible to use gcloud auth print-access-token instead of gcloud auth activate-service-account ?

Didn't know, never use it.

> I run a cloud build within a projet

Sorry, miss that point. 

This is really a GCP only issue, I'm surprised you have auth issue inside Cloud Build. Reading your cloudbuild.yaml I wonder why you do a docker login, I usually don't do this with Cloud Build as it will automatically build and push your images to your project GAR.

**Comment by anthonydenecheau** [comment]
> Reading your cloudbuild.yaml I wonder why you do a docker login

I agree with you. I'm still a newbie and trying to go step by step using gcp documentation.
I'm going to ask for clarification on the gcp side

**Comment by loicmathieu** [comment]
OK, great, I'll close this issue.
Don't hesitate to ask for helm on Zulip if needed: https://quarkusio.zulipchat.com/#narrow/stream/187030-users
It's a better place for searching for help.
