### ISSUE TITLE
Unable to find a JDBC driver corresponding to the database kind 'postgresql', when camel-quarkus-quartz dependency added

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#25817]
### Describe the bug

I have a simple quarkus project using mutiny and postgres, which works with Quarkus 2.7.5.Final. Starting from Quarkus 2.8.0.Final, build  fails, when I add some camel route that needs quartz endpoint:
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.9.1.Final:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'postgresql' for the default datasource. Either provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource.jdbc=false' to your configuration if you don't need it.
[ERROR] 	at io.quarkus.agroal.deployment.AgroalProcessor.resolveDriver(AgroalProcessor.java:330)
[ERROR] 	at io.quarkus.agroal.deployment.AgroalProcessor.getAggregatedConfigBuildItems(AgroalProcessor.java:276)
[ERROR] 	at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:82)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]

```

### Expected behavior

Build should not fail

### Actual behavior

build fails

### How to Reproduce?

[code-with-quarkus.tar.gz](https://github.com/quarkusio/quarkus/files/8781295/code-with-quarkus.tar.gz)
Unpack attached project and run `./mvnw clean package`
Remove `<artifactId>camel-quarkus-quartz</artifactId>` dependency to make build work

**Comment by mkouba** [comment]
It seems that your application does not declare a dependency on the postgresql JDBC driver although the `camel-quarkus-quartz` seems to require a JDBC driver to be present. I'm not sure whtether it's intentional though. You'd better ask/file an issue in the https://github.com/apache/camel-quarkus.

CC @ppalaga

**Comment by ppalaga** [comment]
Yes, [ennishol](https://github.com/ennishol) could you please report at Camel Quarkus? https://github.com/apache/camel-quarkus/issues/new
