### ISSUE TITLE
Deleting entity with `OneToOne` relation with `CascadeType.REMOVE` not working

### ISSUE THREAD

**Issue by omar-zahid** [quarkusio/quarkus#25848]
### Describe the bug

Given 2 entities: `FruitEntity` and `FruitEntityDetail` related by `OneToOne` relation, deleting the parent `Fruit` entity is causing a foreign key error even when `CascadeType.REMOVE` is set on the related `FruitDetailEntity`.

### Expected behavior

Deleting Fruit should delete the related `FruitDetailEntity`.

### Actual behavior

Getting an error:

```java
2022-05-29 17:07:26,163 ERROR [org.acm.hib.orm.pan.ent.FruitEntityResource] (executor-thread-0) Failed to handle request: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
        at org.acme.hibernate.orm.panache.entity.FruitEntityResource_Subclass.delete(Unknown Source)
        at org.acme.hibernate.orm.panache.entity.FruitEntityResource_ClientProxy.delete(Unknown Source)
        at org.acme.hibernate.orm.panache.entity.FruitEntityResource$quarkusrestinvoker$delete_18d1eb030975eab2b5333faf64f47aa35d6f3940.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
        at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1307)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
        at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.commit(CDIDelegatingTransactionManager.java:105)
        at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager_Subclass.commit$$superforward1(Unknown Source)
        at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager_Subclass$$function$$6.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager_Subclass.commit(Unknown Source)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:374)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:166)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        ... 13 more
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:489)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3290)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2425)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:356)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
        at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:76)
        at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:360)
        at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:91)
        at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
        ... 35 more
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:109)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
        at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
        at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3698)
        at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3958)
        at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:123)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
        at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
        ... 47 more
Caused by: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FK6WTK4L3GY1GN4V4WNS6RMHMUP: PUBLIC.FRUITDETAILSENTITY FOREIGN KEY(FRUIT_ID) REFERENCES PUBLIC.FRUITENTITY(ID) (4)"; SQL statement:
delete from FruitEntity where id=? [23503-197]
        at org.h2.message.DbException.gQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:386)
        at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:403)
        at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:278)
        at org.h2.table.Table.fireConstraints(Table.java:995)
        at org.h2.table.Table.fireAfterRow(Table.java:1013)
        at org.h2.command.dml.Delete.update(Delete.java:108)
        at org.h2.command.CommandContainer.update(CommandContainer.java:102)
        at org.h2.command.Command.executeUpdate(Command.java:261)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
        ... 59 more
```

### How to Reproduce?

Reproducer: https://github.com/omar-zahid/quarkus-panache-cascade-delete

Steps to reproduce: 

1. Check out the code and run `quarkus dev`
2. Add color as the detail for the fruit:

```curl
curl --location --request POST 'http://localhost:8080/entity/fruits/details' \
--header 'Content-Type: application/json' \
--data-raw '{
    "fruit":{ "id": 4},
    "color": "Red"
}'
```
3. Delete fruit ID number 4 by:

```curl
curl --location --request DELETE 'http://localhost:8080/entity/fruits/4'
```

At this point you'll be greeted by the error - 500 Internal Server Error:

```
{
    "exceptionType": "io.quarkus.arc.ArcUndeclaredThrowableException",
    "code": 500,
    "error": "Error invoking subclass method"
}
```

### Output of `uname -a` or `ver`

Linux MASTER 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.14.1" 2022-02-08 OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04) OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

### Quarkus version or git rev

2.8.0 Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /home/omar/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 11.0.14.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64 Default locale: en, platform encoding: UTF-8 OS name: "linux", version: "4.19.84-microsoft-standard", arch: "amd64", family: "unix"

### Additional information

Sometimes, waiting for some period of time such as 10 to 15 minutes before deleting the resource works. Not sure why this is the case, so adding it as an additional information.

**Comment by omar-zahid** [comment]
Thanks @DavideD I understand the relation part. After going through your links above and debugging more, here's my findings:

1. The propagation is not the problem here. It is being propagated properly.
2. In the resource file, calling `entity.details` is `null`

That's the reason I'm opening this issue under bug.

Another thing is that, if we wait long enough. Eventually `entity.details` will be not null and everything works fine.
Also interestingly, all entities added through `import.sql` file does not suffer from this problem so there's definitely something weird going on here, hence I need the help.

**Comment by omar-zahid** [comment]
Hi @DavideD I've found the culprit.
Since it's related to time, I went ahead and started to investigate caching.
I was using the hibernate orm quickstart project as my project started and it contains `@Cacheable` annotation which causes the entity to not be updated immediately.

I would recommend removing `@Cacheable` completely from the starter project since Quarkus also recommends to not cache entities that will mutate.

Thanks again for looking into this issue. Appreciate it.

**Comment by DavideD** [comment]
Ok, It seems I've talked too soon before. Sorry about it.

The issue is that when you create the `FruitDetailsEntity` using the parameters from the POST request, the relationship is created with a detached object.
With Hibernate ORM, one can use the `EntityManager#getReference` method for these situations. Panache doesn't have anything similart. But you can make this work changing the create method this way:
```
public class FruitEntityDetailsResource {

    @Inject
    EntityManager em; // org.hibernate.Session would also work

   ...

    @POST
    @Transactional
    public RestResponse<FruitDetailsEntity> create(FruitDetailsEntity entity) {
        ...
        FruitEntity fruitReference = em.getReference(FruitEntity.class, entity.fruit.id);
        entity.fruit = fruitReference;
        entity.persist();
        
        return ResponseBuilder.ok(entity).status(Status.CREATED).build();
    }

}

```

After this the delete should work as expected

**Comment by omar-zahid** [comment]
I see. Thanks @DavideD for explaining the `getReference`. I'll check that out. Really appreciate you looking into this.
