### ISSUE TITLE
Quinoa does not find node or yarn executable

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#25904]
### Describe the bug

I'm trying to use Quinoa on windows with node and yarn in path.
Maybe it's worth saying It's a multi module project (with jigsaw modules) and webui is outside the java project dir.
I will try to produce a reproducer later this week.

### Actual behavior

Quinoa fail complaining that it cannot find node or yarn executable:

```
<====2022-05-31 22:58:28,018 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.quinoa.deployment.ForwardedDevProcessor#prepareDevService threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:170)
        at io.quarkiverse.quinoa.deployment.PackageManager.dev(PackageManager.java:102)
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:120)
        ... 11 more
Caused by: java.io.IOException: Cannot run program "yarn" (in directory "C:\Users\loich\workspace\Projets\handyman\main-partition\..\webui"): CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at io.quarkus.deployment.util.ProcessUtil.launchProcess(ProcessUtil.java:38)
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:168)
        ... 13 more
Caused by: java.io.IOException: CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 16 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:95)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:485)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:68)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:142)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:97)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.quinoa.deployment.ForwardedDevProcessor#prepareDevService threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:170)
        at io.quarkiverse.quinoa.deployment.PackageManager.dev(PackageManager.java:102)
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:120)
        ... 11 more
Caused by: java.io.IOException: Cannot run program "yarn" (in directory "C:\Users\loich\workspace\Projets\handyman\main-partition\..\webui"): CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at io.quarkus.deployment.util.ProcessUtil.launchProcess(ProcessUtil.java:38)
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:168)
        ... 13 more
Caused by: java.io.IOException: CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 16 more

        at io.quarkus.builder.Execution.run(Execution.java:116)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:157)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
        ... 9 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Input/Output error while running process.
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:170)
        at io.quarkiverse.quinoa.deployment.PackageManager.dev(PackageManager.java:102)
        at io.quarkiverse.quinoa.deployment.ForwardedDevProcessor.prepareDevService(ForwardedDevProcessor.java:120)
        ... 11 more
Caused by: java.io.IOException: Cannot run program "yarn" (in directory "C:\Users\loich\workspace\Projets\handyman\main-partition\..\webui"): CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at io.quarkus.deployment.util.ProcessUtil.launchProcess(ProcessUtil.java:38)
        at io.quarkiverse.quinoa.deployment.PackageManager.process(PackageManager.java:168)
        ... 13 more
Caused by: java.io.IOException: CreateProcess error=2, Le fichier sp?cifi? est introuvable
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
```

 maybe an encoding problem ?

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)

### Quarkus version or git rev

2.9.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.1

**Comment by geoand** [comment]
This is probably best reported at: https://github.com/quarkiverse/quarkus-quinoa

**Comment by ia3andy** [comment]
@rmanibus yeah please create the issue on the quinoa repository. Could you try to set the absolute path to yarn in your config file? Are you 100% sure yarn is in the path for Java?
