### ISSUE TITLE
Quarkus Cache (Caffeine): Allow setting refreshAfterWrite property

### ISSUE THREAD

**Issue by davefranken-ah** [quarkusio/quarkus#25921]
### Description

Currently, the Quarkus caffeine cache offers the following properties (see https://quarkus.io/guides/cache#quarkus-cache-config-group-cache-config-caffeine-config_configuration):
- initial capacity
- maximum size
- expire after write
- expire after access
- metrics enabled

Caffeine also offers setting 'refresh after write' (see https://github.com/ben-manes/caffeine/wiki/Refresh).

### Implementation ideas

I did some research and the version of Caffeine (2.9.3) does support this already in the builder which is called from `io.quarkus.cache.runtime.caffeine.CaffeineCacheImpl` so it should be fairly trivial to add this property. We need to add it to `CaffeineCacheInfo` (I think).

**Comment by geoand** [comment]
@davefranken-ah would you be willing to contribute this?

**Comment by davefranken-ah** [comment]
> @davefranken-ah would you be willing to contribute this?

Yeah no problem, I can try to make a PR, but might need some help, I'll see if I can get it to work.

**Comment by gwenneg** [comment]
Thanks @davefranken-ah! Don't hesitate to ask for help :smiley:

**Comment by gwenneg** [comment]
Did you rebuild Quarkus entirely? The build is fine on my machine and on CI so I suppose something's wrong on your machine.

**Comment by gilvansfilho** [comment]
Here build works fine too. 

I made some code to address this issue but now I am looking for more information about [CacheLoader](https://github.com/ben-manes/caffeine/wiki/Population#loading). Someone could help? Perhaps I could submit PR in WIP mode and we discuss there?

**Comment by gastaldi** [comment]
> I made some code to address this issue but now I am looking for more information about [CacheLoader](https://github.com/ben-manes/caffeine/wiki/Population#loading). Someone could help? Perhaps I could submit PR in WIP mode and we discuss there?

Sounds good

**Comment by davefranken-ah** [comment]
I can run the build with `-Dquickly` just fine, it's just that the tests keep failing, this is with both Eclipse Temurin JDK 11 and Mandrel 22.11 on Linux 64-bit. And it's not only the cache tests, when I run the entire build with `,/mvnw install` mutiny fails to build as well. I studied the contributing.md file, but nothing in there can help me sadly.

**Comment by technical-debt-collector** [comment]
This might come off as naive but what if Quarkus just exposed the builder somehow? Developers requiring any other functionality offered by Caffeine could just configure this themselves using the builder and then leave that to Quarkus?

My team is also interested in this feature, as well as being able to intercept evictions as documented here: https://github.com/ben-manes/caffeine/wiki/Compute

**Comment by geoand** [comment]
I think that's a reasonable request (and something we allow in other extensions as well).

@gwenneg WDYT?

**Comment by gwenneg** [comment]
That sounds reasonable indeed.

**Comment by geoand** [comment]
I'll see if I can come up with something for Quarkus 3.0, but I can't make any promises as there is a lot of work to be done for that release.

**Comment by technical-debt-collector** [comment]
If it's of any help I could try to have a look at it myself, although I too would probably need some pointers along the way.
Unless @davefranken-ah wants to give this another shot?

**Comment by geoand** [comment]
If I can't get to this by early next week, I'll let you know :)

**Comment by gsmet** [comment]
Even if we expose the builder, I think it would make sense to have that property.

**Comment by geoand** [comment]
So in the meantime, I'll go ahead and do another PR adding the property

**Comment by geoand** [comment]
Actually, adding the property does not work either because we get:

```
Caused by: java.lang.IllegalStateException: refreshAfterWrite requires a LoadingCache
        at com.github.benmanes.caffeine.cache.Caffeine.requireState(Caffeine.java:203)
        at com.github.benmanes.caffeine.cache.Caffeine.requireNonLoadingCache(Caffeine.java:1160)
        at com.github.benmanes.caffeine.cache.Caffeine.buildAsync(Caffeine.java:1091)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheImpl.<init>(CaffeineCacheImpl.java:77)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheManagerBuilder$1.get(CaffeineCacheManagerBuilder.java:57)

```

**Comment by gwenneg** [comment]
We discussed the property in https://github.com/quarkusio/quarkus/pull/25956. I'm not in favor of adding that because of the reason explained in that PR.

**Comment by geoand** [comment]
👌

**Comment by gastaldi** [comment]
Perhaps we should close this issue then?

**Comment by ayushman2001** [comment]
is there any development going on this featire

**Comment by chir050** [comment]
It would be nice to know when it is planned to be implemented?
