### ISSUE TITLE
MP Config `Converter` fails in native build

### ISSUE THREAD

**Issue by artkonr** [quarkusio/quarkus#25940]
### Describe the bug

Apparently, there's some compatibility issue with using MP config `Converter` and `@WithConverter` with native mode. If there is a property declared in a `@ConfigMapping`-annotated class that uses a value converter, the application compiles cleanly, but fails at bootstrap with `NoSuchMethodError`. See minimal [reproducer](https://github.com/artkonr/converter-native-failure) and stacktrace below:

```
java.lang.NoSuchMethodError: com.example.Config$BConverter.<init>()
	at io.smallrye.config.ConfigMappingContext.lambda$getConverterInstance$7(ConfigMappingContext.java:194)
	at java.util.Map.computeIfAbsent(Map.java:1054)
	at io.smallrye.config.ConfigMappingContext.getConverterInstance(ConfigMappingContext.java:178)
	at io.smallrye.config.ConfigMappingContext.getConverter(ConfigMappingContext.java:104)
	at io.smallrye.config.ConfigMappingContext.lambda$getValueConverter$4(ConfigMappingContext.java:92)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at io.smallrye.config.ConfigMappingContext.getValueConverter(ConfigMappingContext.java:89)
	at com.example.Config-888161165Impl.<init>(Unknown Source)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.smallrye.config.ConfigMappingLoader.configMappingObject(ConfigMappingLoader.java:65)
	at io.smallrye.config.ConfigMappingContext.constructGroup(ConfigMappingContext.java:80)
	at io.smallrye.config.ConfigMappingContext.constructRoot(ConfigMappingContext.java:76)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:811)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:794)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:450)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### Expected behavior

Configuration values are picked up correctly with `@WithConverter` and work nicely in a native image. 

### Actual behavior

Native image builds, but fails at bootstrap.

### How to Reproduce?

How to reproduce:

1. Generate a new app, use of any extension in particular doesn't seem to matter.
2. Create a configuration mapping class.
3. Have at least 1 field resolved using `@WithConverter`.
4. Inject the config class.
5. Compile with GraalVM and start.

### Output of `uname -a` or `ver`

21.3.0 Darwin Kernel Version 21.3.0

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### Quarkus version or git rev

2.9.2.Final or 2.8.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

any maven or gradle

### Additional information

From the looks of the trace, it seems like there's no constructor to be found, which is odd. 

In the reproducer, the resolved class is nested, but this has no significance. Also, I had a hypothesis that Graal does not like a `byte[]` in constructor argument or in type parameter of `Converter`, but this is not the case either. The error can be reproduced even with a `String` field.

**Comment by geoand** [comment]
Thanks for reporting. https://github.com/quarkusio/quarkus/pull/25949 takes care of it

**Comment by artkonr** [comment]
That was quick, thank you @geoand 👍

**Comment by geoand** [comment]
YW!
