### ISSUE TITLE
Mssql stop working in upstream because is missing license agreement

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#26042]
### Describe the bug

Quarkus mssql is failing at build time because is missing license agreement approval  ( `ACCEPT_EULA=Y`)

Quarkus version: 999-snapshot
Extension: quarkus-jdbc-mssql
Scenario: devServices

Error:

```
12:34:04,160 INFO  [app] Caused by: java.lang.IllegalStateException: The image mcr.microsoft.com/mssql/server:2019-latest requires you to accept a license agreement. Please place a file at the root of the classpath named container-license-acceptance.txt, e.g. at src/test/resources/container-license-acceptance.txt. This file should contain the line:
```

Stacktrace

```
12:34:04,128 INFO  [app] 12:34:03,189 Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
12:34:04,129 INFO  [app]        [error]: Build step io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor#launchDatabases threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
12:34:04,130 INFO  [app]        at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:317)
12:34:04,130 INFO  [app]        at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.launchDatabases(DevServicesDatasourceProcessor.java:126)
12:34:04,131 INFO  [app]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:34:04,131 INFO  [app]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:34:04,132 INFO  [app]        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:34:04,132 INFO  [app]        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:34:04,133 INFO  [app]        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
12:34:04,133 INFO  [app]        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
12:34:04,134 INFO  [app]        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
12:34:04,134 INFO  [app]        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
12:34:04,134 INFO  [app]        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
12:34:04,135 INFO  [app]        at java.base/java.lang.Thread.run(Thread.java:829)
12:34:04,135 INFO  [app]        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
12:34:04,135 INFO  [app] Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
12:34:04,136 INFO  [app]        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:345)
12:34:04,136 INFO  [app]        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326)
12:34:04,136 INFO  [app]        at io.quarkus.devservices.mssql.deployment.MSSQLDevServicesProcessor$1.startDatabase(MSSQLDevServicesProcessor.java:41)
12:34:04,137 INFO  [app]        at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:272)
12:34:04,137 INFO  [app]        ... 12 more
12:34:04,137 INFO  [app] Caused by: java.lang.IllegalStateException: The image mcr.microsoft.com/mssql/server:2019-latest requires you to accept a license agreement. Please place a file at the root of the classpath named container-license-acceptance.txt, e.g. at src/test/resources/container-license-acceptance.txt. This file should contain the line:
12:34:04,138 INFO  [app]   mcr.microsoft.com/mssql/server:2019-latest
12:34:04,138 INFO  [app]        at org.testcontainers.utility.LicenseAcceptance.assertLicenseAccepted(LicenseAcceptance.java:30)
12:34:04,138 INFO  [app]        at org.testcontainers.containers.MSSQLServerContainer.configure(MSSQLServerContainer.java:73)
12:34:04,139 INFO  [app]        at io.quarkus.devservices.mssql.deployment.MSSQLDevServicesProcessor$QuarkusMSSQLServerContainer.configure(MSSQLDevServicesProcessor.java:71)
12:34:04,139 INFO  [app]        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:331)
12:34:04,139 INFO  [app]        ... 15 more
12:34:04,140 INFO  [app]        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
12:34:04,140 INFO  [app]        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
12:34:04,140 INFO  [app]        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
12:34:04,141 INFO  [app]        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:95)
12:34:04,141 INFO  [app]        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:485)
12:34:04,141 INFO  [app]        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:68)
12:34:04,142 INFO  [app]        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:147)
12:34:04,142 INFO  [app]        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:102)
12:34:04,142 INFO  [app]        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
12:34:04,142 INFO  [app]        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
12:34:04,143 INFO  [app] Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
12:34:04,143 INFO  [app]        [error]: Build step io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor#launchDatabases threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
12:34:04,143 INFO  [app]        at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:317)
12:34:04,144 INFO  [app]        at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.launchDatabases(DevServicesDatasourceProcessor.java:126)
12:34:04,144 INFO  [app]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:34:04,145 INFO  [app]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:34:04,145 INFO  [app]        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:34:04,145 INFO  [app]        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:34:04,146 INFO  [app]        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
12:34:04,146 INFO  [app]        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
12:34:04,146 INFO  [app]        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
12:34:04,146 INFO  [app]        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
12:34:04,146 INFO  [app]        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
12:34:04,147 INFO  [app]        at java.base/java.lang.Thread.run(Thread.java:829)
12:34:04,147 INFO  [app]        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
12:34:04,147 INFO  [app] Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
12:34:04,147 INFO  [app]        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:345)
12:34:04,148 INFO  [app]        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326)
12:34:04,148 INFO  [app]        at io.quarkus.devservices.mssql.deployment.MSSQLDevServicesProcessor$1.startDatabase(MSSQLDevServicesProcessor.java:41)
12:34:04,148 INFO  [app]        at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:272)
12:34:04,148 INFO  [app]        ... 12 more
12:34:04,149 INFO  [app] Caused by: java.lang.IllegalStateException: The image mcr.microsoft.com/mssql/server:2019-latest requires you to accept a license agreement. Please place a file at the root of the classpath named container-license-acceptance.txt, e.g. at src/test/resources/container-license-acceptance.txt. This file should contain the line:
12:34:04,149 INFO  [app]   mcr.microsoft.com/mssql/server:2019-latest
12:34:04,149 INFO  [app]        at org.testcontainers.utility.LicenseAcceptance.assertLicenseAccepted(LicenseAcceptance.java:30)
12:34:04,150 INFO  [app]        at org.testcontainers.containers.MSSQLServerContainer.configure(MSSQLServerContainer.java:73)
12:34:04,150 INFO  [app]        at io.quarkus.devservices.mssql.deployment.MSSQLDevServicesProcessor$QuarkusMSSQLServerContainer.configure(MSSQLDevServicesProcessor.java:71)
12:34:04,150 INFO  [app]        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:331)
12:34:04,150 INFO  [app]        ... 15 more
12:34:04,151 INFO  [app]        at io.quarkus.builder.Execution.run(Execution.java:116)
12:34:04,151 INFO  [app]        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
12:34:04,151 INFO  [app]        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:157)
12:34:04,151 INFO  [app]        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
12:34:04,152 INFO  [app]        ... 9 more
12:34:04,152 INFO  [app] Caused by: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
12:34:04,152 INFO  [app]        at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:317)
12:34:04,153 INFO  [app]        at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.launchDatabases(DevServicesDatasourceProcessor.java:126)
12:34:04,153 INFO  [app]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:34:04,153 INFO  [app]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:34:04,153 INFO  [app]        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:34:04,154 INFO  [app]        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:34:04,155 INFO  [app]        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
12:34:04,156 INFO  [app]        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
12:34:04,156 INFO  [app]        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
12:34:04,156 INFO  [app]        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
12:34:04,156 INFO  [app]        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
12:34:04,157 INFO  [app]        at java.base/java.lang.Thread.run(Thread.java:829)
12:34:04,157 INFO  [app]        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
12:34:04,158 INFO  [app] Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
12:34:04,158 INFO  [app]        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:345)
12:34:04,158 INFO  [app]        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326)
12:34:04,159 INFO  [app]        at io.quarkus.devservices.mssql.deployment.MSSQLDevServicesProcessor$1.startDatabase(MSSQLDevServicesProcessor.java:41)
12:34:04,159 INFO  [app]        at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:272)
12:34:04,159 INFO  [app]        ... 12 more
12:34:04,160 INFO  [app] Caused by: java.lang.IllegalStateException: The image mcr.microsoft.com/mssql/server:2019-latest requires you to accept a license agreement. Please place a file at the root of the classpath named container-license-acceptance.txt, e.g. at src/test/resources/container-license-acceptance.txt. This file should contain the line:
12:34:04,160 INFO  [app]   mcr.microsoft.com/mssql/server:2019-latest
12:34:04,160 INFO  [app]        at org.testcontainers.utility.LicenseAcceptance.assertLicenseAccepted(LicenseAcceptance.java:30)
12:34:04,160 INFO  [app]        at org.testcontainers.containers.MSSQLServerContainer.configure(MSSQLServerContainer.java:73)
12:34:04,161 INFO  [app]        at io.quarkus.devservices.mssql.deployment.MSSQLDevServicesProcessor$QuarkusMSSQLServerContainer.configure(MSSQLDevServicesProcessor.java:71)
12:34:04,161 INFO  [app]        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:331)
12:34:04,161 INFO  [app]        ... 15 more
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 24.94 s <<< FAILURE! - in io.quarkus.ts.sqldb.sqlapp.DevModeMssqlIT
```
Note: Works on Quarkus 2.9.2.Final

**Comment by rsvoboda** [comment]
not a bug, see https://github.com/quarkusio/quarkus/issues/23525#issuecomment-1033062069
