### ISSUE TITLE
`java.lang.NoSuchMethodException: io.grpc.netty.UdsNettyChannelProvider.<init>()` on Quarkus main after grpc update

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#26083]
### Describe the bug

`java.lang.NoSuchMethodException: io.grpc.netty.UdsNettyChannelProvider.<init>()` on Quarkus main after grpc update

Did some bisection locally and the PR where the troubles start is https://github.com/quarkusio/quarkus/pull/26047 CC @cescoffier 

```
Jun 13, 2022 12:22:43 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile test)
java.lang.NoSuchMethodException: io.grpc.netty.UdsNettyChannelProvider.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3585)
	at java.lang.Class.getConstructor(DynamicHub.java:2271)
	at io.grpc.ServiceProviders.createForHardCoded(ServiceProviders.java:136)
	at io.grpc.ServiceProviders.getCandidatesViaHardCoded(ServiceProviders.java:125)
	at io.grpc.InternalServiceProviders.getCandidatesViaHardCoded(InternalServiceProviders.java:63)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:28)
	at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:101)
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43)
	at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
	at io.opentelemetry.exporter.internal.grpc.DefaultGrpcExporterBuilder.build(DefaultGrpcExporterBuilder.java:134)
	at io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporterBuilder.build(JaegerGrpcSpanExporterBuilder.java:111)
	at io.quarkus.opentelemetry.exporter.jaeger.runtime.JaegerRecorder.installBatchSpanProcessorForJaeger(JaegerRecorder.java:29)
	at io.quarkus.deployment.steps.JaegerExporterProcessor$installBatchSpanProcessorForJaeger1237208624.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.JaegerExporterProcessor$installBatchSpanProcessorForJaeger1237208624.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### Expected behavior

Application starts

### Actual behavior

Application start fails

### How to Reproduce?

 - build latest Quarkus main
 - clone https://github.com/quarkus-qe/beefy-scenarios
 - run `mvn clean verify -pl 300-quarkus-vertx-webClient -Dnative`

### Output of `uname -a` or `ver`

macOS Monterey

### GraalVM version (if different from Java)

GraalVM 22.0 Java17 / GraalVM 22.1 Java17 / GraalVM 21.3 Java11

### Quarkus version or git rev

Quarkus main

**Comment by cescoffier** [comment]
Do you have the netty domain socket on your classpath? If so, remove it

**Comment by rsvoboda** [comment]
These are the deps: https://github.com/quarkus-qe/beefy-scenarios/blob/main/300-quarkus-vertx-webClient/pom.xml#L11

these are the netty deps vvv, no netty domain socket between them
```
mvn dependency:tree -pl 300-quarkus-vertx-webClient | grep netty                                                  ✔  3s   12:38:56 
[INFO] |  |  |  +- io.netty:netty-common:jar:4.1.74.Final:compile
[INFO] |  |  |  +- io.netty:netty-handler-proxy:jar:4.1.74.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-codec-socks:jar:4.1.74.Final:compile
[INFO] |  |  |  +- io.netty:netty-resolver:jar:4.1.74.Final:compile
[INFO] |  |  |  \- io.netty:netty-resolver-dns:jar:4.1.74.Final:compile
[INFO] |  |  |     \- io.netty:netty-codec-dns:jar:4.1.74.Final:compile
[INFO] |  |     +- io.grpc:grpc-netty:jar:1.47.0:compile
[INFO] |  +- io.quarkus:quarkus-netty:jar:999-SNAPSHOT:compile
[INFO] |  |  +- io.netty:netty-codec:jar:4.1.74.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.74.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.74.Final:compile
[INFO] |  |  \- io.netty:netty-handler:jar:4.1.74.Final:compile
[INFO] |  |     \- io.netty:netty-tcnative-classes:jar:2.0.48.Final:compile
[INFO] |  +- io.netty:netty-codec-haproxy:jar:4.1.74.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.74.Final:compile
[INFO] |  |  \- io.netty:netty-transport:jar:4.1.74.Final:compile
```

**Comment by pjgg** [comment]
The error is related to opentelemetry: 
Extensions:

`io.quarkusquarkus-opentelemetry`
`io.quarkus:quarkus-opentelemetry-exporter-jaeger`
