### ISSUE TITLE
`io.grpc.netty.UdsNettyChannelProvider` needs to be registered for reflection in Native mode

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#26082]
### Describe the bug

Related to: 
https://github.com/quarkusio/quarkus/pull/26047/files#diff-ab718592919c4c47502d7fa6345c367ee6f6fcf4bab52c4b3b5b01fed26b0498R75

Quarkus Upstream: 999-snapshot

Some scenarios start failing because of the following error:

```
01:15:49,801 INFO  [vertx] java.lang.NoSuchMethodException: io.grpc.netty.UdsNettyChannelProvider.<init>()
01:15:49,801 INFO  [vertx] 	at java.lang.Class.getConstructor0(DynamicHub.java:3349)
01:15:49,802 INFO  [vertx] 	at java.lang.Class.getConstructor(DynamicHub.java:2151)
01:15:49,803 INFO  [vertx] 	at io.grpc.ServiceProviders.createForHardCoded(ServiceProviders.java:136)
01:15:49,803 INFO  [vertx] 	at io.grpc.ServiceProviders.getCandidatesViaHardCoded(ServiceProviders.java:125)
01:15:49,804 INFO  [vertx] 	at io.grpc.InternalServiceProviders.getCandidatesViaHardCoded(InternalServiceProviders.java:63)
01:15:49,804 INFO  [vertx] 	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:28)
01:15:49,805 INFO  [vertx] 	at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:101)
01:15:49,806 INFO  [vertx] 	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43)
01:15:49,806 INFO  [vertx] 	at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
01:15:49,807 INFO  [vertx] 	at io.opentelemetry.exporter.internal.grpc.DefaultGrpcExporterBuilder.build(DefaultGrpcExporterBuilder.java:134)
01:15:49,807 INFO  [vertx] 	at io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporterBuilder.build(JaegerGrpcSpanExporterBuilder.java:111)
01:15:49,808 INFO  [vertx] 	at io.quarkus.opentelemetry.exporter.jaeger.runtime.JaegerRecorder.installBatchSpanProcessorForJaeger(JaegerRecorder.java:29)
01:15:49,808 INFO  [vertx] 	at io.quarkus.deployment.steps.JaegerExporterProcessor$installBatchSpanProcessorForJaeger1237208624.deploy_0(Unknown Source)
01:15:49,809 INFO  [vertx] 	at io.quarkus.deployment.steps.JaegerExporterProcessor$installBatchSpanProcessorForJaeger1237208624.deploy(Unknown Source)
01:15:49,810 INFO  [vertx] 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
01:15:49,810 INFO  [vertx] 	at io.quarkus.runtime.Application.start(Application.java:101)
01:15:49,811 INFO  [vertx] 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
01:15:49,812 INFO  [vertx] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
01:15:49,812 INFO  [vertx] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
01:15:49,813 INFO  [vertx] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
01:15:49,813 INFO  [vertx] 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

The workaround was to add this missing class to the list of classes to be registered for reflection
reflection-config.json

```
[
  {
    "name": "io.grpc.netty.UdsNettyChannelProvider",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  }
]
```

application.properties:
```
quarkus.native.additional-build-args=--allow-incomplete-classpath, -H:ReflectionConfigurationFiles=reflection-config.json

```

### Expected behavior

I would expect that netty internal class `UdsNettyChannelProvider` would be added by default to the registered for reflection class without any extra configuration (because is not an end user/business class, is some internal stuff that should not be exposed)

**Comment by cescoffier** [comment]
Are you trying domain sockets in native?

**Comment by pjgg** [comment]
duplicated issue: https://github.com/quarkusio/quarkus/issues/26083

Reproducer: `git clone git@github.com:quarkus-qe/quarkus-test-suite.git`
cmd: `mvn clean verify -Dnative -Dall-modules -pl http/vertx-web-client`
