### ISSUE TITLE
Quarkus Test fails due to a ClassCastException while deserializing Avro generated object

### ISSUE THREAD

**Issue by ewelling** [quarkusio/quarkus#26085]
### Describe the bug

The issue: I have a Quarkus microservice that uses kafka for sending cloud events.
The dependencies are:

```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-apicurio-registry-avro</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-jwt-build</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-reactive-messaging-in-memory</artifactId>
      <scope>test</scope>
    </dependency>
```

After upgrading from quarkus version 2.5.0.Final to 2.8.2.Final, my Quarkus Test fails due to a ClassCastException while deserializing an Avro generated object.

### Expected behavior

Successful deserialization of Avro generated objects and successful QuarkusTests.

### Actual behavior

Quarkus Tests for consuming services fail:

```posh
2022-05-23 07:04:02,195 WARN  [io.sma.rea.mes.kafka] (smallrye-kafka-consumer-thread-6) SRMSG18228: A failure has been reported for Kafka topics '[xxxxxxxxxxxxxxxx]': java.lang.IllegalStateException: Error getting schema [com.avro.generated.Object]: com.avro.generated.Object
	at io.apicurio.registry.serde.avro.DefaultAvroDatumProvider.lambda$getReaderSchema$0(DefaultAvroDatumProvider.java:66)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.apicurio.registry.serde.avro.DefaultAvroDatumProvider.getReaderSchema(DefaultAvroDatumProvider.java:60)
	at io.apicurio.registry.serde.avro.DefaultAvroDatumProvider.createDatumReader(DefaultAvroDatumProvider.java:94)
	at io.apicurio.registry.serde.avro.AvroKafkaDeserializer.readData(AvroKafkaDeserializer.java:110)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.readData(AbstractKafkaDeserializer.java:142)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:122)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.lambda$deserialize$1(DeserializerWrapper.java:74)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.wrapDeserialize(DeserializerWrapper.java:106)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.deserialize(DeserializerWrapper.java:74)
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1439)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:135)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1671)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1507)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:733)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:684)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1304)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1238)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.lambda$poll$4(ReactiveKafkaConsumer.java:141)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.lambda$runOnPollingThread$0(ReactiveKafkaConsumer.java:108)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassCastException: class com.avro.generated.Object cannot be cast to class org.apache.avro.specific.SpecificRecord (com.avro.generated.Object is in unnamed module of loader 'app'; org.apache.avro.specific.SpecificRecord is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @336f1079)
	at io.apicurio.registry.serde.avro.DefaultAvroDatumProvider.lambda$getReaderSchema$0(DefaultAvroDatumProvider.java:64)
	... 30 more
```

(the avro generated object's path name, as well als the kafka topic name were altered for the purpose of hiding internal information)

### How to Reproduce?

1. A service based on Quarkus 2.8.2.Final which uses smallrye-kafka for sending kafka cloud events to a kafka topic
2. Another service which consume kafka events from this topic
3. A QuarkusTest using io.smallrye.reactive.messaging.connectors.public interface InMemorySink to verify that kafka events sent by the producing service are consumed by the other service

Although kafka-console shows that kafka events are pushed correctly to the topic, the QuarkusTest fails with above ClassCastException when deserializing the kafka data.

### Output of `uname -a` or `ver`

Linux 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.14.1" 2022-02-08 OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04) OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by geoand** [comment]
cc @ozangunalp

**Comment by ozangunalp** [comment]
@ewelling normally `apicurio.registry.use-specific-avro-reader` is automatically set to true in configuration and you wouldn't have that ClassCastException. What also confuses me is your usage of InMemorySink. Are you configuring an outgoing channel as in-memory and checking forwarded messages ? 

In any case it would be great if you add a reproducer.

**Comment by geoand** [comment]
Closing as we never got a reproducer

**Comment by ewelling** [comment]
Apologies for the delay. It seems that setting **quarkus.test.flat-class-path=true** resolves the issue. A similar issue is described in [#16804](https://github.com/quarkusio/quarkus/issues/16804).
