### ISSUE TITLE
Remote-dev mode not supported with container images created with Jib extension

### ISSUE THREAD

**Issue by sebastienblanc** [quarkusio/quarkus#26113]
### Describe the bug

[Remote-dev ](https://quarkus.io/guides/maven-tooling#remote-development-mode) works perfectly using the docker file generated by the a Quarkus project. But when trying the same thing with the `containers-jib` extension, once deployed inside a pod we get this error : 

```
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
2022-06-14 11:52:06,160 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:50)
	at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:45)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
Caused by: java.nio.file.AccessDeniedException: /home/jboss/dev
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
	at io.quarkus.deployment.mutability.DevModeTask.extractDevModeClasses(DevModeTask.java:104)
	at io.quarkus.deployment.mutability.DevModeTask.createDevModeContext(DevModeTask.java:78)
	at io.quarkus.deployment.mutability.DevModeTask.main(DevModeTask.java:53)
	... 8 more

```

### Expected behavior

remote-dev should work and the local project should be able to connect to the remote pod/container

### Actual behavior

Pod can not be started due to file.io exception

### How to Reproduce?

container image you can use to reproduce the bug : quay.io/sebastienblanc0/remote-dev-test:1.0.0-SNAPSHOT

Don't forget to set the env var : `QUARKUS_LAUNCH_DEVMODE=true`

**Comment by geoand** [comment]
What version of Quarkus are you using?
I recall us fixing some similar issues a little while ago

**Comment by sebastienblanc** [comment]
@geoand 2.9.2.Final but I'm pretty sure I had the issue with at least the 2 latests version as well (also on 2.8.2)

**Comment by geoand** [comment]
Thanks!

**Comment by sebastienblanc** [comment]
This is my application.properties : 
```
quarkus.package.type=mutable-jar
quarkus.live-reload.password=secret
quarkus.container-image.group=sebastienblanc0
quarkus.container-image.registry=quay.io
```

I build&push the image with : `mvn clean package -Dquarkus.container-image.push=true`

**Comment by sebastienblanc** [comment]
Sure no rush here , it will just make my demo flow smoother ;)
