### ISSUE TITLE
RxJava1ContextPropagator does not work correctly in the dev mode

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#2622]
Quarkus build: https://github.com/quarkusio/quarkus/commit/ef71554148994a2e43e619dc4f5e2b3f692be5eb

# Stack trace:
```
Caused by: java.lang.IllegalStateException: Container not running: ArcContainerImpl [id=ff6e4c3c-6b02-424a-8290-37430a072755, running=false, beans=0, observers=0, scopes=[interface javax.inject.Singleton, interface javax.enterprise.context.ApplicationScoped]]
	at io.quarkus.arc.ArcContainerImpl.requireRunning(ArcContainerImpl.java:548)
	at io.quarkus.arc.ArcContainerImpl.requestContext(ArcContainerImpl.java:239)
	at io.quarkus.arc.runtime.context.ArcContextProvider.lambda$currentContext$4(ArcContextProvider.java:42)
	at io.smallrye.context.impl.ActiveContextState.<init>(ActiveContextState.java:18)
	at io.smallrye.context.impl.CapturedContextState.begin(CapturedContextState.java:35)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:213)
	at io.smallrye.context.propagators.rxjava1.ContextPropagatorOnObservableCreateAction$ContextCapturerObservable$OnAssemblyObservableSubscriber.onNext(ContextPropagatorOnObservableCreateAction.java:62)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
```

# Steps to reproduce:
1. clone https://github.com/mkouba/pulls
2. run `mvn compile quarkus:dev`
3. hit `http://localhost:8080/pulls`
4. make some irrelevant change
5. hit `http://localhost:8080/pulls`

It seems that SM CP is using some outdated `ThreadContextSnapshot` returned from `ArcContextProvider#currentContext()` - this snapshot is referencing the stopped ArC container instance. A quick solution might be to use `Arc.container()` in the returned lambda.

**Comment by FroMage** [comment]
Errr, why do we have contexts from the previous deployment lying around?

**Comment by FroMage** [comment]
Right, we should find out why that stale context is still used after deployment
