### ISSUE TITLE
SimpleJaxbTest in quarkus-rest-client-reactive-jaxb-deploymant failing randomly on CI

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#26251]
### Description

`io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest`, a test in `quarkus-rest-client-reactive-jaxb-deploymant`, has been failing randomly on CI for a few days.

Sometimes it fails for JDK11 but not JDK17, sometimes it fails for JDK17 but not JDK11. So it doesn't look like a JDK compatibility issue, but more likely some race condition.

The logs for one of builds that failed:

```
2022-06-20T13:33:44.4256885Z [INFO] -------------------------------------------------------
2022-06-20T13:33:44.4257658Z [INFO]  T E S T S
2022-06-20T13:33:44.4258546Z [INFO] -------------------------------------------------------
2022-06-20T13:33:45.0340488Z [INFO] Running io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest
2022-06-20T13:33:49.8338650Z 2022-06-20 13:33:49,808 INFO  [io.quarkus] (main) quarkus-rest-client-reactive-jaxb-deployment 999-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.514s. Listening on: http://localhost:8081
2022-06-20T13:33:49.8339704Z 2022-06-20 13:33:49,810 INFO  [io.quarkus] (main) Profile test activated. 
2022-06-20T13:33:49.8340884Z 2022-06-20 13:33:49,810 INFO  [io.quarkus] (main) Installed features: [cdi, rest-client-reactive, rest-client-reactive-jaxb, resteasy-reactive, resteasy-reactive-jaxb, smallrye-context-propagation, vertx]
2022-06-20T13:33:50.4524480Z 2022-06-20 13:33:50,427 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /xml/plain failed, error id: 6fa2b8b6-5701-4441-bfac-61fb22a1e48c-1: java.lang.RuntimeException: javax.xml.bind.JAXBException: class io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$Dto nor any of its super class is known to this context.
2022-06-20T13:33:50.4525837Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.marshal(JaxbMessageBodyWriter.java:60)
2022-06-20T13:33:50.4526880Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.writeResponse(JaxbMessageBodyWriter.java:43)
2022-06-20T13:33:50.4527808Z 	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:214)
2022-06-20T13:33:50.4528894Z 	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:185)
2022-06-20T13:33:50.4529958Z 	at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriter.write(FixedEntityWriter.java:26)
2022-06-20T13:33:50.4530778Z 	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:33)
2022-06-20T13:33:50.4531682Z 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
2022-06-20T13:33:50.4532626Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
2022-06-20T13:33:50.4533410Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:554)
2022-06-20T13:33:50.4535154Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2022-06-20T13:33:50.4535760Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2022-06-20T13:33:50.4536346Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2022-06-20T13:33:50.4681456Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2022-06-20T13:33:50.4682197Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-06-20T13:33:50.4682620Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-20T13:33:50.4683149Z Caused by: javax.xml.bind.JAXBException: class io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$Dto nor any of its super class is known to this context.
2022-06-20T13:33:50.4683728Z 	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getBeanInfo(JAXBContextImpl.java:563)
2022-06-20T13:33:50.4684193Z 	at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:452)
2022-06-20T13:33:50.4684632Z 	at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:298)
2022-06-20T13:33:50.4685064Z 	at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:226)
2022-06-20T13:33:50.4685539Z 	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:80)
2022-06-20T13:33:50.4686160Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.marshal(JaxbMessageBodyWriter.java:57)
2022-06-20T13:33:50.4686617Z 	... 14 more
2022-06-20T13:33:50.4686988Z 
2022-06-20T13:33:50.4687926Z 2022-06-20 13:33:50,432 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: java.lang.RuntimeException: javax.xml.bind.JAXBException: class io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$Dto nor any of its super class is known to this context.
2022-06-20T13:33:50.4688839Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.marshal(JaxbMessageBodyWriter.java:60)
2022-06-20T13:33:50.4689618Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.writeResponse(JaxbMessageBodyWriter.java:43)
2022-06-20T13:33:50.4690305Z 	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:214)
2022-06-20T13:33:50.4690894Z 	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:185)
2022-06-20T13:33:50.4691503Z 	at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriter.write(FixedEntityWriter.java:26)
2022-06-20T13:33:50.4692141Z 	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:33)
2022-06-20T13:33:50.4692888Z 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
2022-06-20T13:33:50.4693665Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
2022-06-20T13:33:50.4694224Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:554)
2022-06-20T13:33:50.4694768Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2022-06-20T13:33:50.4695217Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2022-06-20T13:33:50.4695650Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2022-06-20T13:33:50.4696117Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2022-06-20T13:33:50.4696609Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-06-20T13:33:50.4696996Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-20T13:33:50.4697490Z Caused by: javax.xml.bind.JAXBException: class io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$Dto nor any of its super class is known to this context.
2022-06-20T13:33:50.4698047Z 	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getBeanInfo(JAXBContextImpl.java:563)
2022-06-20T13:33:50.4698492Z 	at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:452)
2022-06-20T13:33:50.4698944Z 	at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:298)
2022-06-20T13:33:50.4699380Z 	at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:226)
2022-06-20T13:33:50.4699835Z 	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:80)
2022-06-20T13:33:50.4700458Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.marshal(JaxbMessageBodyWriter.java:57)
2022-06-20T13:33:50.4700912Z 	... 14 more
2022-06-20T13:33:50.4701024Z 
2022-06-20T13:33:50.4755813Z 2022-06-20 13:33:50,462 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /xml/dto failed, error id: 6fa2b8b6-5701-4441-bfac-61fb22a1e48c-2: java.lang.RuntimeException: javax.xml.bind.JAXBException: class io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$Dto nor any of its super class is known to this context.
2022-06-20T13:33:50.4756878Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.marshal(JaxbMessageBodyWriter.java:60)
2022-06-20T13:33:50.4757670Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.writeResponse(JaxbMessageBodyWriter.java:43)
2022-06-20T13:33:50.4758370Z 	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:214)
2022-06-20T13:33:50.4759126Z 	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:185)
2022-06-20T13:33:50.4759726Z 	at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriter.write(FixedEntityWriter.java:26)
2022-06-20T13:33:50.4760339Z 	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:33)
2022-06-20T13:33:50.4761096Z 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
2022-06-20T13:33:50.4761881Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
2022-06-20T13:33:50.4762621Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:554)
2022-06-20T13:33:50.4763069Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2022-06-20T13:33:50.4763523Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2022-06-20T13:33:50.4763956Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2022-06-20T13:33:50.4764416Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2022-06-20T13:33:50.4764906Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-06-20T13:33:50.4765295Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-20T13:33:50.4765783Z Caused by: javax.xml.bind.JAXBException: class io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$Dto nor any of its super class is known to this context.
2022-06-20T13:33:50.4766441Z 	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getBeanInfo(JAXBContextImpl.java:563)
2022-06-20T13:33:50.4766898Z 	at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:452)
2022-06-20T13:33:50.4767334Z 	at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:298)
2022-06-20T13:33:50.4767768Z 	at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:226)
2022-06-20T13:33:50.4768225Z 	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:80)
2022-06-20T13:33:50.4768852Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.marshal(JaxbMessageBodyWriter.java:57)
2022-06-20T13:33:50.4769305Z 	... 14 more
2022-06-20T13:33:50.4769420Z 
2022-06-20T13:33:50.4770189Z 2022-06-20 13:33:50,464 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: java.lang.RuntimeException: javax.xml.bind.JAXBException: class io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$Dto nor any of its super class is known to this context.
2022-06-20T13:33:50.4771087Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.marshal(JaxbMessageBodyWriter.java:60)
2022-06-20T13:33:50.4771864Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.writeResponse(JaxbMessageBodyWriter.java:43)
2022-06-20T13:33:50.4772564Z 	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:214)
2022-06-20T13:33:50.4773139Z 	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:185)
2022-06-20T13:33:50.4773738Z 	at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriter.write(FixedEntityWriter.java:26)
2022-06-20T13:33:50.4774370Z 	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:33)
2022-06-20T13:33:50.4775127Z 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
2022-06-20T13:33:50.4775912Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
2022-06-20T13:33:50.4776476Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:554)
2022-06-20T13:33:50.4776986Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2022-06-20T13:33:50.4777440Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2022-06-20T13:33:50.4777872Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2022-06-20T13:33:50.4778324Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2022-06-20T13:33:50.4778823Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-06-20T13:33:50.4779210Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-20T13:33:50.4779689Z Caused by: javax.xml.bind.JAXBException: class io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$Dto nor any of its super class is known to this context.
2022-06-20T13:33:50.4780246Z 	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getBeanInfo(JAXBContextImpl.java:563)
2022-06-20T13:33:50.4780708Z 	at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:452)
2022-06-20T13:33:50.4781144Z 	at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:298)
2022-06-20T13:33:50.4781566Z 	at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:226)
2022-06-20T13:33:50.4782030Z 	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:80)
2022-06-20T13:33:50.4782650Z 	at io.quarkus.resteasy.reactive.jaxb.common.runtime.serialisers.JaxbMessageBodyWriter.marshal(JaxbMessageBodyWriter.java:57)
2022-06-20T13:33:50.4783101Z 	... 14 more
2022-06-20T13:33:50.4783207Z 
2022-06-20T13:33:50.5305228Z 2022-06-20 13:33:50,501 INFO  [io.quarkus] (main) quarkus-rest-client-reactive-jaxb-deployment stopped in 0.022s
2022-06-20T13:33:50.5360397Z [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 5.485 s <<< FAILURE! - in io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest
2022-06-20T13:33:50.5362821Z [ERROR] io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest.shouldConsumePlainXMLEntity  Time elapsed: 0.619 s  <<< ERROR!
2022-06-20T13:33:50.5364022Z org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Internal Server Error, status code 500' when invoking: Rest Client method: 'io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$XmlClient#plain'
2022-06-20T13:33:50.5365015Z 	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.unwrapException(RestClientRequestContext.java:170)
2022-06-20T13:33:50.5365953Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.handleException(AbstractResteasyReactiveContext.java:317)
2022-06-20T13:33:50.5366926Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:169)
2022-06-20T13:33:50.5367798Z 	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:276)
2022-06-20T13:33:50.5368518Z 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
2022-06-20T13:33:50.5369385Z 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
2022-06-20T13:33:50.5369871Z 	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
2022-06-20T13:33:50.5370382Z 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
2022-06-20T13:33:50.5370972Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
2022-06-20T13:33:50.5371447Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
2022-06-20T13:33:50.5371901Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
2022-06-20T13:33:50.5372353Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2022-06-20T13:33:50.5372811Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-06-20T13:33:50.5373203Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-20T13:33:50.5373779Z Caused by: javax.ws.rs.WebApplicationException: Internal Server Error, status code 500
2022-06-20T13:33:50.5374470Z 	at io.quarkus.rest.client.reactive.runtime.DefaultMicroprofileRestClientExceptionMapper.toThrowable(DefaultMicroprofileRestClientExceptionMapper.java:18)
2022-06-20T13:33:50.5375322Z 	at io.quarkus.rest.client.reactive.runtime.MicroProfileRestClientResponseFilter.filter(MicroProfileRestClientResponseFilter.java:36)
2022-06-20T13:33:50.5376072Z 	at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:20)
2022-06-20T13:33:50.5376793Z 	at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:9)
2022-06-20T13:33:50.5377538Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:219)
2022-06-20T13:33:50.5378257Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
2022-06-20T13:33:50.5378678Z 	... 11 more
2022-06-20T13:33:50.5378796Z 
2022-06-20T13:33:50.5379104Z [ERROR] io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest.shouldConsumeXMLEntity  Time elapsed: 0.018 s  <<< ERROR!
2022-06-20T13:33:50.5380132Z org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Internal Server Error, status code 500' when invoking: Rest Client method: 'io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$XmlClient#dto'
2022-06-20T13:33:50.5380902Z 	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.unwrapException(RestClientRequestContext.java:170)
2022-06-20T13:33:50.5381729Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.handleException(AbstractResteasyReactiveContext.java:317)
2022-06-20T13:33:50.5382450Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:169)
2022-06-20T13:33:50.5383088Z 	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:276)
2022-06-20T13:33:50.5383590Z 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
2022-06-20T13:33:50.5384000Z 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
2022-06-20T13:33:50.5384418Z 	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
2022-06-20T13:33:50.5384905Z 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
2022-06-20T13:33:50.5385454Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
2022-06-20T13:33:50.5385923Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
2022-06-20T13:33:50.5386403Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
2022-06-20T13:33:50.5386863Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2022-06-20T13:33:50.5387324Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-06-20T13:33:50.5387703Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-20T13:33:50.5388062Z Caused by: javax.ws.rs.WebApplicationException: Internal Server Error, status code 500
2022-06-20T13:33:50.5388740Z 	at io.quarkus.rest.client.reactive.runtime.DefaultMicroprofileRestClientExceptionMapper.toThrowable(DefaultMicroprofileRestClientExceptionMapper.java:18)
2022-06-20T13:33:50.5389594Z 	at io.quarkus.rest.client.reactive.runtime.MicroProfileRestClientResponseFilter.filter(MicroProfileRestClientResponseFilter.java:36)
2022-06-20T13:33:50.5390340Z 	at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:20)
2022-06-20T13:33:50.5391065Z 	at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:9)
2022-06-20T13:33:50.5391859Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:219)
2022-06-20T13:33:50.5392579Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
2022-06-20T13:33:50.5392988Z 	... 11 more
2022-06-20T13:33:50.5393101Z 
2022-06-20T13:33:50.5737361Z [INFO] 
2022-06-20T13:33:50.5739457Z [INFO] Results:
2022-06-20T13:33:50.5740212Z [INFO] 
2022-06-20T13:33:50.5740553Z [ERROR] Errors: 
2022-06-20T13:33:50.5753144Z [ERROR]   SimpleJaxbTest.shouldConsumePlainXMLEntity » ClientWebApplication Received: 'Internal Server Error, status code 500' when invoking: Rest Client method: 'io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$XmlClient#plain'
2022-06-20T13:33:50.5754385Z [ERROR]   SimpleJaxbTest.shouldConsumeXMLEntity » ClientWebApplication Received: 'Internal Server Error, status code 500' when invoking: Rest Client method: 'io.quarkus.rest.client.reactive.jaxb.test.SimpleJaxbTest$XmlClient#dto'
2022-06-20T13:33:50.5754907Z [INFO] 
2022-06-20T13:33:50.5755140Z [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
2022-06-20T13:33:50.5755518Z [INFO] 
```

It happens on the main branch: see https://github.com/quarkusio/quarkus/runs/6966186553
It happens on PRs: see https://github.com/quarkusio/quarkus/pull/26128#issuecomment-1160636647

**Comment by yrodiere** [comment]
> this test was disabled in #26173
> and enabled again in #26231.

So it was disabled on the main branch 5 days ago, and re-enabled on the main branch 1 hour ago, but the build I mentioned above (https://github.com/quarkusio/quarkus/runs/6966186553) failed on the main branch 20 hours ago... when the test was supposed to be disabled? There was something wrong here.

Anyway, let's hope #26231 fixes the problem. My PR has been merged, so there's no point rebasing it, but I guess we'll see what happens on builds of the main branch.

Glad to know someone is on it :) Closing.

**Comment by Sgitario** [comment]
> > So it was disabled on the main branch 5 days ago, and re-enabled on the main branch 1 hour ago, but the build I mentioned above (https://github.com/quarkusio/quarkus/runs/6966186553) failed on the main branch 20 hours ago... when the test was supposed to be disabled? There was something wrong here.
> 
> Looks like it was not the same test being disabled (`SimpleXmlTest` instead of `SimpleJaxbTest`). So, mystery solved :)
> 
> The good news is, as far as I understand, fix does look like it could solve the problem with `SimpleJaxbTest` too. So... crossed_fingers

Ops! Let's see how the CI goes :crossed_fingers:
