### ISSUE TITLE
javax.persistence.TransactionRequiredException thrown when trying to persist an entity

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#2628]
**Describe the bug**
No transaction is being created while trying to persist an entity in a method annotated with @Transactional

**Expected behavior**
The entity is persisted in the database

**Actual behavior**
An Exception is thrown trying to persist the entity
```
2019-05-29 07:18:50,652 WARN  [com.arj.ats.arjuna] (executor-thread-1) ARJUNA012125: TwoPhaseCoordinator.beforeCompletion - failed for SynchronizationImple< 0:ffffac126e23:c210:5cee14fe:3, io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager$1@7b1c0a13 >: javax.persistence.TransactionRequiredException: no transaction is in progress
	at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:398)
	at org.hibernate.internal.SessionImpl.checkTransactionNeededForUpdateOperation(SessionImpl.java:3619)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1474)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1470)
...
2019-05-29 07:18:50,663 ERROR [io.und.request] (executor-thread-1) UT005023: Exception handling request to /checkers/register: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error invoking subclass method
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
...
Caused by: java.lang.RuntimeException: Error invoking subclass method
	at com.dwitech.ib24.checker.boundary.Checkers_Subclass.register(Unknown Source)
	at com.dwitech.ib24.checker.boundary.Checkers_ClientProxy.register(Unknown Source)
	at com.dwitech.ib24.checker.boundary.CheckersEndpoint.register(CheckersEndpoint.java:32)
	at com.dwitech.ib24.checker.boundary.CheckersEndpoint_Subclass.register$$superaccessor1(Unknown Source)
	at com.dwitech.ib24.checker.boundary.CheckersEndpoint_Subclass$$function$$3.apply(Unknown Source)
	at io.quarkus.arc.InvocationContextImpl.interceptorChainCompleted(InvocationContextImpl.java:157)
	at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:177)
	at io.smallrye.metrics.interceptors.MeteredInterceptor.meteredCallable(MeteredInterceptor.java:79)
	at io.smallrye.metrics.interceptors.MeteredInterceptor.meteredMethod(MeteredInterceptor.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.arc.Reflections.invokeMethod(Reflections.java:111)
	at io.smallrye.metrics.interceptors.MeteredInterceptor_Bean.intercept(Unknown Source)
...
Caused by: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1300)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:126)
	at io.quarkus.narayana.jta.runtime.NarayanaJtaProducers_ProducerMethod_transactionManager_9989455b3b53ac81c17ca945c636473b7202fe4e_ClientProxy.commit(Unknown Source)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:152)
...
Caused by: javax.persistence.TransactionRequiredException: no transaction is in progress
	at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:398)
	at org.hibernate.internal.SessionImpl.checkTransactionNeededForUpdateOperation(SessionImpl.java:3619)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1474)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1470)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager$1.beforeCompletion(TransactionScopedEntityManager.java:76)
	at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:76)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:360)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:91)
	at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1288)
```

**To Reproduce**
1. Add the Hibernate with Panache extension 
2. Create an Entity extending PanacheEntity
3. Create a method to persist the entity in a @ApplicationScoped class and annotate the method with @Transactional

**Configuration**
```
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.1" xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">
    <persistence-unit name="ib24-checker" transaction-type="RESOURCE_LOCAL">
        <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
        <exclude-unlisted-classes>false</exclude-unlisted-classes>
        <properties>
            <property name="hibernate.archive.autodetection" value="class" />
            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5Dialect" />
            <property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver" />
            <property name="hibernate.connection.url" value="jdbc:mysql://localhost:3306/ib24_user?useSSL=false" />
            <property name="hibernate.connection.username" value="root" />
            <property name="hibernate.connection.password" value="<mysql_password>" />
            <property name="hibernate.connection.autocommit" value="false"/>
            <property name="org.hibernate.flushMode" value="COMMIT"/>
        </properties>
    </persistence-unit>
</persistence>
```

**Environment :**
 - Output of `uname -a` or `ver`: Darwin DWI-MBP15-1 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: JDK8 u202
 - GraalVM version (if different from Java): 1.0.0-rc14
 - Quarkus version or git rev: 0.15.0

**Comment by stuartwdouglas** [comment]
What happens if you change this to JTA transaction type rather than RESOURCE_LOCAL?

**Comment by stuartwdouglas** [comment]
We need to improve our handling of this at any rate. In general the datasource should be defined in application.properties so Agroal is used as the connection pool, and if RESOURCE_LOCAL is used it should either be ignored or an error. 

@Sanne @emmanuelbernard what do you guys think we should do when there is a persistence.xml that does not really map to what Quarkus expects?

**Comment by dwamara** [comment]
> What happens if you change this to JTA transaction type rather than RESOURCE_LOCAL?

Oh boy, you really make me feel stupid. I just did and it worked, thanks.

**Comment by dwamara** [comment]
> We need to improve our handling of this at any rate. In general the datasource should be defined in application.properties so Agroal is used as the connection pool, and if RESOURCE_LOCAL is used it should either be ignored or an error.

Do you see any problem with using persistence.xml? I first used the application.properties but I felt it easier to use the persistence.xml that I had when using Payara so that I can reduce the amount of work on migration. And for people like me coming from the world of Payara and other application servers, it's more straightforward.

**Comment by stuartwdouglas** [comment]
You should be able to use it, but if it is wrong you should not just get an error like that, either we should transparently use the correct TX type, or throw a meaningful error. 

Same with the datasource properties, I am not actually sure what happens here (it is a question for @Sanne ) I am not sure if they get mapped to agroal internally, or if it ends up using hibernates built in connection pool

**Comment by dwamara** [comment]
> Same with the datasource properties, I am not actually sure what happens here (it is a question for @Sanne ) I am not sure if they get mapped to agroal internally, or if it ends up using hibernates built in connection pool

I am at the office at the moment so I won't be able to paste the info I get when starting quarkus:dev (will do it when I'm home) but it definitely uses the Hibernate built-in connection pool, the message showing that appears in the log.

**Comment by dwamara** [comment]
But something that I realized though, when an Entity is mapped in a relationship with another (in my case, it is a @OneToMany) or when the Entity is a property of another (I have one "Checker" which has a property "Addresses", both extend PanacheEntity), only the Checker is persisted in the database, the Addresses are not, although a small toString shows that the Adresses are correctly set.

**Comment by Sanne** [comment]
Within Quarkus we recommend using Agroal, so that's the default for applications configured exclusively via the `application.properties` method.

But when booting via a `persistence.xml` you're running in "legacy mode" so to help porting existing applications: in that case we won't be overriding defaults with Quarkus defaults, so indeed you end up having to configure the connection pool yourself, or have it use the Hibernate ORM defaults.

HTH

**Comment by dwamara** [comment]
I tried to use Agroal with the application.properties instead of the persistence.xml file, but one thing though, there seems to be no way to use the Hibernate with Panache in case you have more than one datasource defined. May be I should open another thread for that.

**Comment by emmanuelbernard** [comment]
@dwamara yes open a separate conversation.

**Comment by emmanuelbernard** [comment]
@Sanne / @gsmet  maybe we should simply document how to do the `persistence.xml` equivalent of `application.properties` to guide people to complexity:

- agroal config
- preferred transaction managed with JTA

Should we support `RESOURCE_LOCAL` as well. I'm not sure of the implications and how much Quarkus glue code should know about it. Also it means lots of doc and explanation to go to so not sure we would actively document things.

**Comment by gsmet** [comment]
@dwamara yes, we do not support declaring multiple persistence units with `application.properties` right now but that's certainly something we might want to do in the future. Please open an issue.

@emmanuelbernard I would prefer spending time on ^ rather than documenting 2 different methods of doing the same thing.

**Comment by Sanne** [comment]
I agree with @gsmet . The `persistence.xml` approach should not be encouraged, and documenting such things is bound to get out of date; maybe it's not even possible to have a 1:1 match as we do setup some things depending on context / other things.

**Comment by emmanuelbernard** [comment]
@gsmet @Sanne Actually to me `persistence.xml` usage was not about multiple PUs (+1 to cover that in app.properties) It was about actual advanced settings that we decided not to cover via `quarkus.hibernate` properties.

**Comment by Sanne** [comment]
sure. So we'll still allow using `persistence.xml` for any power-user but the power-user better knows what he wants to do ;-)

My point really is more that whatever magic we do with `.properties` is highly dynamic; we could document some of the things it does but I doubt we can do this both comprehensively and keep the docs up to date & an light read.

**Comment by FroMage** [comment]
> there seems to be no way to use the Hibernate with Panache in case you have more than one datasource defined

Yes please open an issue, we need to support this in the config, and then I've ideas how to support this in Hibernate ORM with Panache.

**Comment by rsvoboda** [comment]
@Sanne / @FroMage this seems stalled, any plans ?

**Comment by FroMage** [comment]
Not sure if there's anything to do on ORM side, but for panache and multiple datasources, we already have an issue and it depends on ORM supporting multiple entity managers.

**Comment by Sanne** [comment]
It will take a while longer to support multiple PUs.
Some shorter term options which seem fine to me:

- Should we remove support for `persistence.xml` ?
- If not, should we at least validate that transaction management has been set to JTA (require it)?

**Comment by famod** [comment]
So, to me it seems this can be closed since:
- we have multiple datasources since a couple of versions
- AFAICS the decision was/is to _not_ document `persistence.xml`

Right?

**Comment by Sanne** [comment]
Right, thanks @famod
