### ISSUE TITLE
Unable to build Quarkus main - Gradle plugin - can't find plexus-utils-3.4.1.jar

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#26336]
### Describe the bug

Unable to build Quarkus main - Gradle plugin - can't find plexus-utils-3.4.1.jar

This block our daily and PR CI runs as we can't build Quarkus main - e.g. https://github.com/quarkus-qe/quarkus-test-suite/runs/7029470577?check_suite_focus=true

I was able to reproduce the same locally:
 - using custom local repo
 - also when I removed `~/.m2/repository/org/codehaus/plexus/plexus-utils`

Error:
```
[INFO] Building Quarkus - Gradle Plugin 999-SNAPSHOT                 [803/1073]
...
[INFO] --- exec-maven-plugin:3.0.0:exec (gradle) @ io.quarkus.gradle.plugin ---
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
> Task :gradle-application-plugin:clean UP-TO-DATE
> Task :gradle-model:compileJava UP-TO-DATE
> Task :gradle-application-plugin:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gradle-application-plugin:compileJava'.
> Could not resolve all files for configuration ':gradle-application-plugin:compileClasspath'.
   > Could not find plexus-utils-3.4.1.jar (org.codehaus.plexus:plexus-utils:3.4.1).
     Searched in the following locations:
         file:/Users/rsvoboda/Downloads/quarkus-main-local-repo/org/codehaus/plexus/plexus-utils/3.4.1/plexus-utils-3.4.1.jar
```

Part of stacktrace
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gradle-application-plugin:compileJava'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
...
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find plexus-utils-3.4.1.jar (org.codehaus.plexus:plexus-utils:3.4.1).
Searched in the following locations:
    file:/Users/rsvoboda/Downloads/quarkus-main-local-repo/org/codehaus/plexus/plexus-utils/3.4.1/plexus-utils-3.4.1.jar
	at org.gradle.internal.resolve.result.DefaultBuildableArtifactResolveResult.notFound(DefaultBuildableArtifactResolveResult.java:28)
	at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveArtifact(ExternalResourceResolver.java:509)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$ResolveAndCacheRepositoryAccess.resolveArtifact(CachingModuleComponentRepository.java:469)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.LocalModuleComponentRepository$LocalAccess.resolveArtifact(LocalModuleComponentRepository.java:101)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.lambda$resolveArtifact$15(ErrorHandlingModuleComponentRepository.java:181)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.tryResolveAndMaybeBlacklist(ErrorHandlingModuleComponentRepository.java:237)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.performOperationWithRetries(ErrorHandlingModuleComponentRepository.java:203)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveArtifact(ErrorHandlingModuleComponentRepository.java:179)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.resolveArtifact(RepositoryChainArtifactResolver.java:100)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSupplier.calculateValue(DefaultArtifactSet.java:284)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSupplier.calculateValue(DefaultArtifactSet.java:255)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.lambda$attachValue$0(CalculatedValueContainer.java:218)
	at org.gradle.internal.Try.ofFailable(Try.java:41)
```

### Expected behavior

Build passes

### Actual behavior

Build fails

### How to Reproduce?

git clone https://github.com/quarkusio/quarkus.git && cd quarkus && ./mvnw -B -s .github/mvn-settings.xml -Dmaven.repo.local=${HOME}/Downloads/quarkus-main-local-repo clean install -Dquickly -Prelocations

### Output of `java -version`

Java 11 / Java 17

### Quarkus version or git rev

Quarkus main

**Comment by rsvoboda** [comment]
https://status.quarkus.io/ reports components as green, but if I look into GH actions they are red because Quarkus main wasn't built
 - https://github.com/quarkusio/quarkus-super-heroes/actions/workflows/quarkus-snapshot.yaml
 - https://github.com/quarkiverse/quarkus-operator-sdk/actions/workflows/quarkus-snapshot.yaml
 - https://github.com/quarkiverse/quarkus-opencv/actions/workflows/quarkus-snapshot.yaml

Shouldn't Ecosystem CI report the status as red? @geoand / @gsmet

**Comment by glefloch** [comment]
I'm not sure we can do something on our side, right ?

**Comment by rsvoboda** [comment]
I noticed this yesterday, maven central has the artifact available, one can do `mvn org.apache.maven.plugins:maven-dependency-plugin:get -Dartifact=org.codehaus.plexus:plexus-utils:3.4.1`

I don't know what needs version 3.4.1, probably something from Gradle?
Quarkus BOM defines `<plexus-utils.version>3.3.0</plexus-utils.version>`

**Comment by zakkak** [comment]
> I noticed this yesterday, maven central has the artifact available, one can do `mvn org.apache.maven.plugins:maven-dependency-plugin:get -Dartifact=org.codehaus.plexus:plexus-utils:3.4.1`

Well in my case it fails even if the dependency is present in my local maven repository, so it doesn't look like a fetch issue.

It's interesting that the [quarkus GH pipelines seem to work fine](https://github.com/quarkusio/quarkus/runs/7037088745?check_suite_focus=true#step:10:2)m they use `-DskipTests -DskipITs -Dinvoker.skip -Dno-format -Dtcks` instead of `-Dquickly` though, but I tried that and didn't help locally...

**Comment by rsvoboda** [comment]
There is "Cache maven Repository" step before the build, that can bring the needed jar for the build

```
10s
Run actions/cache@v2
Received 12582912 of 709612057 (1.8%), 12.0 MBs/sec
Received 163577856 of 709612057 (23.1%), 77.9 MBs/sec
Received 327155712 of 709612057 (46.1%), 103.9 MBs/sec
Received 499122176 of 709612057 (70.3%), 119.0 MBs/sec
Received 654311424 of 709612057 (92.2%), 124.8 MBs/sec
Received 709612057 of 709612057 (100.0%), 113.0 MBs/sec
Cache Size: ~677 MB (709612057 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/23c5252b-0b07-48a4-ae8d-b4f65f39a69e/cache.tzst -P -C /home/runner/work/quarkus/quarkus
Cache restored successfully
```

**Comment by famod** [comment]
A build in my fork just failed because of that: https://github.com/famod/quarkus/actions/runs/2555518546

**Comment by famod** [comment]
Since when exactly do we have this problem?

**Comment by rsvoboda** [comment]
I noticed that yesterday

Quarkus ecosystem CI I linked before failed the last run on the build issue, previous runs were green


 - https://github.com/quarkusio/quarkus-super-heroes/actions/workflows/quarkus-snapshot.yaml
 - https://github.com/quarkiverse/quarkus-operator-sdk/actions/workflows/quarkus-snapshot.yaml
 - https://github.com/quarkiverse/quarkus-opencv/actions/workflows/quarkus-snapshot.yaml

**Comment by rsvoboda** [comment]
Same here, pom gets downloaded, but not the jar :/

**Comment by rsvoboda** [comment]
Tried to build a5ff943dad51d32c4637af02b87d353fa70c788e (last commit from Jun 22, 2022) and it all went well.
So the problem must be in commits from Jun 23, 2022.

**Comment by famod** [comment]
Alright, I will bisect my way through this.

**Comment by zakkak** [comment]
The breakage is introduced by https://github.com/quarkusio/quarkus/commit/5f30df60762c3ec5a80653da2cb18e9ac6d67269 it looks like formatter-maven-plugin 2.19.0 changed something in the dependencies.

Looking in the [diff between 2.18.0 and 2.19.0](https://github.com/revelc/formatter-maven-plugin/compare/formatter-maven-plugin-2.18.0...formatter-maven-plugin-2.19.0) I see that the latter now requires plexus-utils 3.4.2 insteaf of 3.4.1.

Now the question is why does Quarkus keep looking for 3.4.1 and fail?

**Comment by famod** [comment]
I'll try my luck with this, although Gradle is not my strong side.

**Comment by famod** [comment]
Hum, I guess the issue has something to with Maven downloading just the pom.xml but not the jar and Gradle then seems to expect that the jar is there, which isn't.

**Comment by famod** [comment]
> That doesn't seem right (but explains why the plugin has a dependency to plexus-utils in the first place).

So I've learned that usage of the maven-resolver is indeed required here, so excluding makes no sense.

Moving `mavenCentral()` before `mavenLocal()` fixes the issue, see https://github.com/gradle/gradle/issues/2631#issuecomment-353457127

IIRC, some while ago there was some back and forth regarding this @glefloch, but I will send a PR regardless.

**Comment by famod** [comment]
Looking at this old Gradle ticket https://issues.gradle.org/browse/GRADLE-2034

> This is fixed, but only for mavenLocal(). For all other repositories it is still considered an error for the artifact to be missing when the pom is present (unless packaging == 'pom')

But we have the following in `devtools/gradle/build.gradle`:
```
        // in case a custom local repo is configured we are going to use that instead of the default mavenLocal()
        if (System.properties.containsKey('maven.repo.local')) {
            maven {
                url System.properties.get('maven.repo.local')
            }
        } else {
            mavenLocal()
        }
        mavenCentral()
```
and in `pom.xml` (Maven is calling Gradle) we try hard to set that system property:
```
                        <configuration>
                            <executable>${gradle.executable}</executable>
                            <arguments>
                                <argument>clean</argument>
                                <argument>${gradle.task}</argument>
                                <argument>-Pdescription=${project.description}</argument>
                                <argument>-Dmaven.repo.local=${settings.localRepository}</argument>
                                <argument>-S</argument>
                                <argument>--stacktrace</argument>
                                <argument>--no-daemon</argument>
                            </arguments>
                            <environmentVariables>
                                <MAVEN_REPO_LOCAL>${settings.localRepository}</MAVEN_REPO_LOCAL>
                                <GRADLE_OPTS>${env.MAVEN_OPTS}</GRADLE_OPTS>
                            </environmentVariables>
                            <skip>${skip.gradle.build}</skip>
                        </configuration>
```

So, AFAICT we don't end up with `mavenLocal()` but with that custom `maven` repo, which that old bugfix is not meant for (given there weren't other fixes since then).

PS: `mvn help:evaluate -Dexpression=settings.localRepository -N` is giving me the default path, even though I didn't set anything in `settings.xml`.
