### ISSUE TITLE
Dev services page stacktrace ''Property "getShortId" not found on the base object "null""

### ISSUE THREAD

**Issue by JJWTimmer** [quarkusio/quarkus#26399]
### Describe the bug

When opening the dev services page I get a stacktrace, with this title:
`io.quarkus.qute.TemplateException: Rendering error in template [io.quarkus.quarkus-vertx-http/dev-services] line 16: Property "getShortId" not found on the base object "null" in expression {service.containerInfo.getShortId()}`
![image](https://user-images.githubusercontent.com/609540/176135885-72173f4d-8d0b-40d7-a685-d073186184af.png)

### Expected behavior

See/enable dev services? I don't know, first attempt.

### Actual behavior

```posh
io.quarkus.qute.TemplateException: Rendering error in template [io.quarkus.quarkus-vertx-http/dev-services] line 16: Property "getShortId" not found on the base object "null" in expression {service.containerInfo.getShortId()}
	at io.quarkus.qute.TemplateException$Builder.build(TemplateException.java:168)
	at io.quarkus.qute.EvaluatorImpl.propertyNotFound(EvaluatorImpl.java:242)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:200)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:127)
	at io.quarkus.qute.EvaluatorImpl.lambda$resolveReference$2(EvaluatorImpl.java:131)
	at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:232)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:131)
	at io.quarkus.qute.EvaluatorImpl.lambda$resolveReference$2(EvaluatorImpl.java:131)
	at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:232)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:131)
	at io.quarkus.qute.EvaluatorImpl.evaluate(EvaluatorImpl.java:88)
	at io.quarkus.qute.ResolutionContextImpl$ChildResolutionContext.evaluate(ResolutionContextImpl.java:87)
	at io.quarkus.qute.ExpressionNode.resolve(ExpressionNode.java:31)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:184)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:56)
	at io.quarkus.qute.LoopSectionHelper.nextElement(LoopSectionHelper.java:126)
	at io.quarkus.qute.LoopSectionHelper.lambda$resolve$0(LoopSectionHelper.java:55)
	at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:232)
	at io.quarkus.qute.LoopSectionHelper.resolve(LoopSectionHelper.java:44)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:49)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:184)
	at io.quarkus.qute.InsertSectionHelper.resolve(InsertSectionHelper.java:20)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:49)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:184)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:46)
	at io.quarkus.qute.Parser$1.resolve(Parser.java:1208)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:49)
	at io.quarkus.qute.IncludeSectionHelper.lambda$resolve$1(IncludeSectionHelper.java:63)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
	at io.quarkus.qute.IncludeSectionHelper.resolve(IncludeSectionHelper.java:47)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:49)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:180)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:46)
	at io.quarkus.qute.Parser$1.resolve(Parser.java:1208)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:49)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderData(TemplateImpl.java:171)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsyncNoTimeout(TemplateImpl.java:162)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsync(TemplateImpl.java:135)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.renderTemplate(DevConsole.java:173)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.handle(DevConsole.java:137)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.handle(DevConsole.java:39)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.deployment.devmode.console.FlashScopeHandler.handle(FlashScopeHandler.java:12)
	at io.quarkus.vertx.http.deployment.devmode.console.FlashScopeHandler.handle(FlashScopeHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:248)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:67)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor$2$1.handle(DevConsoleProcessor.java:192)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor$2$1.handle(DevConsoleProcessor.java:189)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.EventLoopContext.lambda$emit$1(EventLoopContext.java:57)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Resulted in: io.quarkus.qute.TemplateException
	at io.quarkus.qute.CompletedStage.get(CompletedStage.java:48)
	at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
	at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
	at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.lambda$renderData$5(TemplateImpl.java:177)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
	... 31 more
Resulted in: java.util.concurrent.CompletionException: io.quarkus.qute.TemplateException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:670)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
	... 30 more
```

### How to Reproduce?

[qdemo.zip](https://github.com/quarkusio/quarkus/files/8999443/qdemo.zip)

1. Import project in IntelliJ
2. Let NPM install the the depencies for patternfly
3. click the debug mode button on the toolbar
4. open http://localhost:8080/q/dev/io.quarkus.quarkus-vertx-http/dev-services 

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22000.778]

### Output of `java -version`

coretto 11.0.15

### Quarkus version or git rev

2.10.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

intellij debug mode quarkus profile?

### Additional information

docker is installed and up to date and working

**Comment by JJWTimmer** [comment]
I see I included 
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
    </dependency>
    
   instead of

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-postgresql</artifactId>
    </dependency>

this might have lead to other problems, because after a restart I see a datasource being created. I just tried to create an initial migration in Flyway, and got

java.lang.NullPointerException
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor$1.get(HibernateOrmProcessor.java:266)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor$1.get(HibernateOrmProcessor.java:260)
	at io.quarkus.flyway.FlywayDevConsoleProcessor$1.handlePostAsync(FlywayDevConsoleProcessor.java:72)
	at io.quarkus.devconsole.runtime.spi.DevConsolePostHandler$2.run(DevConsolePostHandler.java:60)
	at java.base/java.lang.Thread.run(Thread.java:829)


Not sure if related though.
