### ISSUE TITLE
@ConfigProperties usage results in crash with dependency injection errors

### ISSUE THREAD

**Issue by csotiriou** [quarkusio/quarkus#26434]
### Describe the bug

I have a very simple case where I'm trying to use  a configuration class with `@ConfigProperties` like this:

```
@ConfigProperties(prefix = "com.example2")
@ApplicationScoped //may not be needed, but it crashes whether this is present or not
public class MyConfig2 {
    @ConfigProperty(name = "sample2")
    Optional<String> sampleString2;

    public String getSampleString2() {
        return sampleString2.orElse(null);
    }

    public void setSampleString2(Optional<String> sampleString2) {
        this.sampleString2 = sampleString2;
    }
}
```

Quarkus then crashes upon injection (boot time):
```
    @Inject
    MyConfig2 myConfig2;
```

Note that I'm using `import org.eclipse.microprofile.config.inject.ConfigProperties;` and not the annotation from Quarkus ARC. It's that supposed to be working as well?

### Expected behavior

Dependency injection shoud work, and Quarkus should boot normally

### Actual behavior

Quarkus crashes on boot time, due to unsatisfied dependencies.

```
1,274 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2022-06-29 14:29:01,347 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
2022-06-29 14:29:01,469 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.example.config.MyConfig2 and qualifiers [@Default]
	- java member: com.example.GreetingResource#myConfig2
	- declared on CLASS bean [types=[com.example.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=com.example.GreetingResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1209)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:134)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:494)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.example.config.MyConfig2 and qualifiers [@Default]
	- java member: com.example.GreetingResource#myConfig2
	- declared on CLASS bean [types=[com.example.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=com.example.GreetingResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:411)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:532)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:263)
	... 13 more
```

### How to Reproduce?

Download the following reproducer and try to run the project.

[reproducer.zip](https://github.com/quarkusio/quarkus/files/9010084/reproducer.zip)

### Output of `uname -a` or `ver`

Darwin user.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm6

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)

### Quarkus version or git rev

2.10

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by csotiriou** [comment]
@radcortez

**Comment by radcortez** [comment]
Hi @csotiriou thank you for the reproducer.

You are missing the `@ConfigProperties` annotation at the injection point. The MP Config spec mandates it. If you add it, the app runs as expected.

**Comment by csotiriou** [comment]
You are right, it was working without the annotation at the injection point before, and I missed the part of the documentation that mandates it. Thank you.
