### ISSUE TITLE
Reactive Messaging (RabbitMQ) - connector stops when facing parse error

### ISSUE THREAD

**Issue by Dosexe** [quarkusio/quarkus#26470]
### Describe the bug

While receiving a `io.vertx.core.json.JsonObject` into a function annotated with `@Incoming` if the json is broken the consumer will throw an error, unack message and stop working, new messages just got unacked.

### Expected behavior

Bad message is nacked, rejected and consumer continue working as usual

### Actual behavior

Consumer dies and stops processing messages

### How to Reproduce?

1. Create minimal working quarkus app with 

```kotlin
dependencies {
    implementation(enforcedPlatform("$quarkusPlatformGroupId:$quarkusPlatformArtifactId:$quarkusPlatformVersion"))
    implementation("io.quarkus:quarkus-smallrye-reactive-messaging-rabbitmq")
    implementation("io.quarkus:quarkus-resteasy-reactive")
    implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
    implementation("io.quarkus:quarkus-rest-client-reactive-jackson")
    implementation("io.quarkus:quarkus-micrometer-registry-prometheus")
    implementation("io.quarkus:quarkus-kotlin")
    implementation("io.quarkus:quarkus-smallrye-health")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-smallrye-openapi")
    implementation("io.quarkus:quarkus-config-yaml")
    implementation("io.smallrye.reactive:mutiny-kotlin:$mutinyKotlinVersion")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:$jacksonVersion")
}
```
2. Create bean with @Incoming
```kotlin
@Singleton
class SettingsEventProcessor {

    @Incoming(INTEGRATION_SETTINGS_QUEUE)
    fun processSettingEvents(jsonObject: JsonObject) {
        // do something here
    }
}
``` 

3. Send a message to the queue with broken json (string for example) with json content type

![image](https://user-images.githubusercontent.com/26384615/176647529-6f163533-89b7-4967-b1e5-4ee18da484c6.png)

4. Exception is thrown and consumer stops working 
```
2022-06-30 12:49:25,793 ERROR [io.sma.rea.mes.provider] (vert.x-eventloop-thread-3) SRMSG00201: Error caught while processing a message: io.vertx.core.json.DecodeException: Failed to decode:Unrecognized token 'Unacked': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 8]
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromParser(QuarkusJacksonJsonCodec.java:128)
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromBuffer(QuarkusJacksonJsonCodec.java:100)
	at io.vertx.core.buffer.Buffer.toJson(Buffer.java:152)
	at io.smallrye.reactive.messaging.rabbitmq.IncomingRabbitMQMessage.convertPayload(IncomingRabbitMQMessage.java:132)
	at io.smallrye.reactive.messaging.rabbitmq.IncomingRabbitMQMessage.getPayload(IncomingRabbitMQMessage.java:113)
	at io.smallrye.reactive.messaging.providers.helpers.ConverterUtils$1.apply(ConverterUtils.java:37)
	at io.smallrye.reactive.messaging.providers.helpers.ConverterUtils$1.apply(ConverterUtils.java:28)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:42)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:100)
	at io.smallrye.reactive.messaging.providers.locals.ContextDecorator$ContextMulti$ContextProcessor.lambda$onItem$1(ContextDecorator.java:78)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Unacked': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:745)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Unacked': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')

	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3635)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2734)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:902)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:794)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4642)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromParser(QuarkusJacksonJsonCodec.java:125)
	... 24 more
```

### Output of `uname -a` or `ver`

21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment Homebrew (build 11.0.12+0) OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.4.2

**Comment by kdubb** [comment]
@Dosexe Please try with 2.10+

**Comment by Dosexe** [comment]
@kdubb The behaviour is the same.
Here is the stack trace
```
2022-06-30 16:38:53,205 ERROR [io.sma.rea.mes.provider] (vert.x-eventloop-thread-3) SRMSG00201: Error caught while processing a message: io.vertx.core.json.DecodeException: Failed to decode:Unexpected character ('}' (code 125)): was expecting double-quote to start field name
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 13, column: 8]
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromParser(QuarkusJacksonJsonCodec.java:128)
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromBuffer(QuarkusJacksonJsonCodec.java:100)
	at io.vertx.core.buffer.Buffer.toJson(Buffer.java:152)
	at io.smallrye.reactive.messaging.rabbitmq.IncomingRabbitMQMessage.convertPayload(IncomingRabbitMQMessage.java:139)
	at io.smallrye.reactive.messaging.rabbitmq.IncomingRabbitMQMessage.getPayload(IncomingRabbitMQMessage.java:116)
	at io.smallrye.reactive.messaging.providers.helpers.ConverterUtils$1.apply(ConverterUtils.java:37)
	at io.smallrye.reactive.messaging.providers.helpers.ConverterUtils$1.apply(ConverterUtils.java:28)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:42)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:100)
	at io.smallrye.reactive.messaging.providers.locals.ContextDecorator$ContextMulti$ContextProcessor.lambda$onItem$1(ContextDecorator.java:78)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}' (code 125)): was expecting double-quote to start field name
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 13, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleOddName(UTF8StreamJsonParser.java:2096)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1746)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1075)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:969)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:718)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:989)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:718)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:967)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:718)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:958)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:718)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:701)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromParser(QuarkusJacksonJsonCodec.java:125)
	... 24 more
```

**Comment by kdubb** [comment]
Oh I forgot.... this is the open PR https://github.com/smallrye/smallrye-reactive-messaging/pull/1772

**Comment by Dosexe** [comment]
@kdubb Seems the behavior is still the same on `2.16.4.Final`

**Comment by kdubb** [comment]
@Dosexe I had done a lot of work to fix this but the PR I opened was essentially rejected and only parts of it were accepted. Then a bunch of additional functionality was added.

I'm actually not sure where this stands at this point.

I do remember that the behavior that one might expect was not "how it worked". I'll have to resurrect and update my repro "playground" that I was using and see what the current behavior is.

**Comment by Dosexe** [comment]
@kdubb Yeh, sorry, I posted the message and then deleted it, because my first test was not clear enough, seems it is working fine on `2.16.4.Final`, it shows a warning in the console, but the consumer is not stopped and continue working as expected on new messages.
`2023-03-20 13:27:54,382 WARN  [io.sma.rea.mes.rabbitmq] (vert.x-eventloop-thread-2) SRMSG17038: No valid content_type set, failing back to byte[]. If that's wanted, set the content type to application/octet-stream with "content-type-override"
`

**Comment by kdubb** [comment]
That warning seems unrelated to the original issue... what happens if `content-type` is `application/json` and you send the invalid JSON?

**Comment by Dosexe** [comment]
This is the actual behavior, I send and invalid json with `content_type = application/json`

**Comment by cescoffier** [comment]
See comments.
