### ISSUE TITLE
Container build with JIB do not start in remote-dev mode 

### ISSUE THREAD

**Issue by sebastienblanc** [quarkusio/quarkus#26504]
### Describe the bug

This is follow-up on https://github.com/quarkusio/quarkus/issues/26113 and I'm trying this on `main` as a fix as been provided. 
But in my case, it doesn't work at all now, the container can't start because of this exception : 

```posh
Exception in thread "main" java.nio.file.NoSuchFileException: /home/jboss/lib/deployment/deployment-class-path.dat
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
at java.base/java.nio.file.Files.newInputStream(Files.java:156)
at io.quarkus.bootstrap.runner.DevModeMediator.doStart(DevModeMediator.java:39)
at io.quarkus.bootstrap.runner.DevModeMediator.doDevMode(DevModeMediator.java:29)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:45)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)

```

### Expected behavior

remote-dev should work with images built with the JIB extension

### Actual behavior

stacktrace provided above

### How to Reproduce?

Create new app using 999-SNAPSHOT (main) with `quarkus-container-image-jib` extension and using this properties : 
```
quarkus.package.type=mutable-jar
quarkus.live-reload.password=secret

```
build the image and push it to a registry, then try to deploy it on a cluster with setting env var `QUARKUS_LAUNCH_DEVMODE=true`

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by sebastienblanc** [comment]
You can also use directly this image `quay.io/sebastienblanc0/remote-demo:1.0.1-SNAPSHOT`

**Comment by geoand** [comment]
@aloubyansky this seems to be a problem with remote-dev, regardless of container-image building.

I tried the following on the `getting-started` quickstart:

Add the following to application properties:

```
quarkus.package.type=mutable-jar
quarkus.live-reload.password=secret
```

Build the application:

```
mvn package -DskipTests
```

If you look at the `target/quarkus-app/lib/deployment` directory you see 110 elements (notice I have not started the application, but even if I do, this count won't change).

Now, when I do `mvn remote-dev` on the same application, then I see that the `target/quarkus-app/lib/deployment` directory has changed and now only contains 37 elements. 

The end result of this weird behavior is that remote-dev does not seem to work at all. Do you have any idea what's going on?

**Comment by aloubyansky** [comment]
Not yet, I'll have a look

**Comment by geoand** [comment]
Thanks, let me know if you want me to check something
