### ISSUE TITLE
Error during injection of ObjectMapper

### ISSUE THREAD

**Issue by dfa1** [quarkusio/quarkus#26526]
### Describe the bug

From time to time, especially under load, I see the following exception in a (synchronous) resteasy controller:

```
HTTP Request to /graphql/report failed, error id: 4f838e60-22a2-4c28-9179-65bab6f867ad-13 - Exception: java.lang.RuntimeException: Error injecting com.fasterxml.jackson.databind.ObjectMapper 
io.quarkus.resteasy.common.runtime.jackson.QuarkusObjectMapperContextResolver.objectMapper - 
org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error injecting com.fasterxml.jackson.databind.ObjectMapper 
io.quarkus.resteasy.common.runtime.jackson.QuarkusObjectMapperContextResolver.objectMapper at 
org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:230) at 
org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519) at 
org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261) at 
org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161) at 
org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164) at 
org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247) at 
io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73) at 
io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151) at 
io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91) at 
io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545) at 
org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449) at 
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452) at 
org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29) at 
org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29) at 
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at 
java.base/java.lang.Thread.run(Thread.java:833) Caused by: java.lang.RuntimeException: Error injecting 
com.fasterxml.jackson.databind.ObjectMapper 
io.quarkus.resteasy.common.runtime.jackson.QuarkusObjectMapperContextResolver.objectMapper at 
io.quarkus.resteasy.common.runtime.jackson.QuarkusObjectMapperContextResolver_Bean.create(Unknown Source) at 
io.quarkus.resteasy.common.runtime.jackson.QuarkusObjectMapperContextResolver_Bean.create(Unknown Source) at 
io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111) at 
io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35) at 
io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32) at 
io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26) at 
io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69) at 
io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32) at 
io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:18) at 
io.quarkus.resteasy.common.runtime.jackson.QuarkusObjectMapperContextResolver_ClientProxy.arc$delegate(Unknown Source) at 
io.quarkus.resteasy.common.runtime.jackson.QuarkusObjectMapperContextResolver_ClientProxy.getContext(Unknown 
Source) at 
com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider._locateMapperViaProvider(JacksonJsonProvider.java:208) at 
com.fasterxml.jackson.jaxrs.base.ProviderBase.locateMapper(ProviderBase.java:917) at 
org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.writeTo(ResteasyJackson2Provider.java:232) at 
org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$writeTo$1(ServerWriterInterceptorContext.java:79) at 
io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext.executeBlockingIo(VertxHttpRequest.java:251) at 
org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:79) at 
org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:245) at 
org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:224) 
at com.sixgroup.flex.cdmstore.api.GzipSupport.aroundWriteTo(GzipSupport.java:43) at 
org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:254) at 
org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:170) at 
org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:73) at 
org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:93) at 
org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:73) at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:163) at 
org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404) at 
org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252) at 
org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101) at 
org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74) at 
org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:226) ... 16 more 
Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.arc.ArcContainer.getActiveContext(java.lang.Class)" because "<local2>" is null at 
io.quarkus.jackson.runtime.ObjectMapperProducer_ProducerMethod_objectMapper_7d4fe425e6f58abcbdd78addaab8a43fdb7ab3ae_Bean.get(Unknown Source) at 
io.quarkus.jackson.runtime.ObjectMapperProducer_ProducerMethod_objectMapper_7d4fe425e6f58abcbdd78addaab8a43fdb7ab3ae_Bean.get(Unknown Source) ... 47 more
```

Looks like that the error is triggered by a custom resteasy `WriterInterceptor`:

```java
package com.sixgroup.flex.cdmstore.api;

/**
 * Custom gzip support, workaround for https://github.com/quarkusio/quarkus/issues/9671
 *
 * NB: must be deleted when quarkus will have proper gzip support.
 */
@Provider
public class GzipSupport implements ReaderInterceptor, WriterInterceptor {

    private static final String COMPRESS_RESPONSE = "__COMPRESS_RESPONSE__";
    private static final String GZIP = "gzip";

    @Override
    public Object aroundReadFrom(ReaderInterceptorContext context) throws IOException {
        MultivaluedMap<String, String> headers = context.getHeaders();
        String wantedEncoding = headers.getFirst(HttpHeaders.ACCEPT_ENCODING);
        if (wantedEncoding != null && wantedEncoding.contains(GZIP)) {
            context.setProperty(COMPRESS_RESPONSE, true);
        }
        String contentEncoding = headers.getFirst(HttpHeaders.CONTENT_ENCODING);
        if (contentEncoding != null && contentEncoding.equals(GZIP)) {
            context.setInputStream(new GZIPInputStream(context.getInputStream()));
        }
        return context.proceed();
    }

    @Override
    public void aroundWriteTo(WriterInterceptorContext context) throws IOException {
        if (Boolean.TRUE.equals(context.getProperty(COMPRESS_RESPONSE))) {
            MultivaluedMap<String, Object> headers = context.getHeaders();
            headers.add(HttpHeaders.CONTENT_ENCODING, GZIP);
            OutputStream outputStream = context.getOutputStream();
            context.setOutputStream(new GZIPOutputStream(outputStream));
        }
        context.proceed();
    }
}
```

There are also some customization in the `ObjectMapper`:

```java
@Dependent
@SuppressWarnings("unused") // used by Quarkus
public class JsonConfig implements ObjectMapperCustomizer {

    @Override
    public void customize(ObjectMapper mapper) {
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        mapper.disable(SerializationFeature.INDENT_OUTPUT);
    }
}
```

### Expected behavior

No exceptions.

### Actual behavior

Some requests are failing with the above exception:

```
 Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.arc.ArcContainer.getActiveContext(java.lang.Class)" because "<local2>" is null at 
io.quarkus.jackson.runtime.ObjectMapperProducer_ProducerMethod_objectMapper_7d4fe425e6f58abcbdd78addaab8a43fdb7ab3ae_Bean.get(Unknown Source) at 
io.quarkus.jackson.runtime.ObjectMapperProducer_ProducerMethod_objectMapper_7d4fe425e6f58abcbdd78addaab8a43
```

### How to Reproduce?

N/A

### Output of `java -version`

JDK 17 (Azul)

### Quarkus version or git rev

2.7.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8

### Additional information

IIRC the error started to appear after the upgrade to quarkus 2.7.x.

**Comment by geoand** [comment]
I would suggest trying RESTEasy Reactive, as this problem almost certainly does not exist there.

**Comment by mkouba** [comment]
> @mkouba do you have a private email? I don't want to attach this JAR file here as it belongs to my company.

You don't need to attach the whole jar but the `ObjectMapperProducer_ProducerMethod_objectMapper_7d4fe425e6f58abcbdd78addaab8a43fdb7ab3ae_Bean.class` which is a framework class so it should be OK ;-)

**Comment by dfa1** [comment]
@mkouba oh yes, that will simplify a lot my life :)
[ObjectMapperProducer_ProducerMethod_objectMapper_7d4fe425e6f58abcbdd78addaab8a43fdb7ab3ae_Bean.class.zip]
(https://github.com/quarkusio/quarkus/files/9062830/ObjectMapperProducer_ProducerMethod_objectMapper_7d4fe425e6f58abcbdd78addaab8a43fdb7ab3ae_Bean.class.zip)

**Comment by mkouba** [comment]
It seems that `Arc.container()` returns `null` which should never happen in runtime in production mode unless there's some weird classloading problem...

**Comment by dfa1** [comment]
it happens under heavy load, few times in a row... then the service recovers, and continue to operate normally.

By the way, I will try to remove this `GzipSupport` and use the native gzip support of resteasy and maybe I will migrate to reactive resteasy too.

**Comment by mkouba** [comment]
Ok, it's hard to find out more without a simple reproducer app...

**Comment by dfa1** [comment]
yes, and I saw this exception 2 times so far... maybe it is linked to another issue we had (openshift was killing the POD because of random failures in liveness check).

Let's close this by now... and thank you for your feedback!

**Comment by geoand** [comment]
If the NPE happens during shutdown, there is very little we can do. See https://github.com/quarkusio/quarkus/issues/17237#issuecomment-842758679 for more information on a very similar issue.
