### ISSUE TITLE
Mutiny had to drop the following exception: (RECIPIENT_FAILURE,8191) Error : 1000, Position : 0, Sql = SET TRANSACTION ISOLATION LEVEL READ COMMITTED, OriginalSql = SET TRANSACTION ISOLATION LEVEL READ COMMITTED, Error Msg = ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by Swe77** [quarkusio/quarkus#26530]
### Describe the bug

Mutiny throws an exception after persist about 1110 Reactive Panache Entity object in the Oracle database.

The same application works fine with Reactive Postgresql, the problem occurs with Oracle only.

This is the Reactive Panache Entity:

```
@Entity
@Table(name = "AUDIT_TRACKING")
public class Audit extends PanacheEntity{

	private static final Logger LOG = Logger.getLogger(Audit.class);
	
	@Column(name = "TRANSACTION_NAME")
	private String transactionName;
	
	@Column(name = "TRANSACTION_URL")
	private String transactionUrl;

	public String getTransactionName() {
		return transactionName;
	}

	public void setTransactionName(String transactionName) {
		this.transactionName = transactionName;
	}

	public String getTransactionUrl() {
		return transactionUrl;
	}

	public void setTransactionUrl(String transactionUrl) {
		this.transactionUrl = transactionUrl;
	}
}
```

The application is a Reactive Rest Jackson endpoint, and post an object in an Event Bus.

```
@ApplicationScoped
@Path("/audit")
public class AuditResource {

	private static final Logger LOG = Logger.getLogger(AuditResource.class);

	@Inject
	EventBus bus;

	@POST
	@Path("/v1/audit-trail")
	@Produces(MediaType.APPLICATION_JSON)
	public Uni<Void> createTrail() {

		Audit audit = new Audit();
		audit.setTransactionName("ACCOUNT BALANCE");
		audit.setTransactionUrl("http://localhost:...");

		bus.requestAndForget("AUDIT_BUS", audit);

		return Uni.createFrom().nullItem();
	}
}
```

The Event Bus consumer persists the object in the Oracle database using Panache Reactive - Oracle Reactive Stack.

```
@ApplicationScoped
public class AuditService {
Logger log = Logger.getLogger(AuditService.class);
	private static AtomicLong counter = new AtomicLong();
	@ConsumeEvent("AUDIT_BUS")
	@ReactiveTransactional
	public Uni<Void> gravarTrilha(Audit audit) {
		log.info("### [TRAIL RECORDING] COUNTER: " + counter.incrementAndGet());
		return Audit.persist(audit);				
	}
}
```

After about more or less 1110 messages posted in the EventBus, the application throws this exception:

`Mutiny had to drop the following exception: (RECIPIENT_FAILURE,8191) Error : 1000, Position : 0, Sql = SET TRANSACTION ISOLATION LEVEL READ COMMITTED, OriginalSql = SET TRANSACTION ISOLATION LEVEL READ COMMITTED, Error Msg = ORA-01000: maximum open cursors exceeded`

**application.properties:**
```
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=THEDATABASE
quarkus.datasource.password=thepassword
quarkus.datasource.reactive.url=oracle:thin:@127.0.0.1:1521/orclpdb
quarkus.hibernate-orm.database.generation = update
```

- Operating System: Windows 11
- JDK version: RedHat Open JDK (java-11-openjdk-11.0.15.9-4)
- Quarkus Version: 2.10.1.Final

**pom.xml dependencies:**

```
<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-vertx</artifactId>
</dependency>

<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-arc</artifactId>
</dependency>

<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-narayana-jta</artifactId>
</dependency>

<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-resteasy-reactive-jackson</artifactId>
</dependency>

<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-rest-client-reactive-jackson</artifactId>
</dependency>

<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-hibernate-validator</artifactId>
</dependency>

<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-hibernate-reactive</artifactId>
</dependency>

<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-hibernate-reactive-panache</artifactId>
</dependency>

<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-reactive-oracle-client</artifactId>
</dependency>

<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-junit5</artifactId>
	<scope>test</scope>
</dependency>

<dependency>
	<groupId>io.rest-assured</groupId>
	<artifactId>rest-assured</artifactId>
	<scope>test</scope>
</dependency>
```

This is the error log:

```
2022-07-03 18:41:52,594 INFO  [org.acm.aud.ser.AuditService] (vert.x-eventloop-thread-0) ### [TRAIL RECORDING] COUNTER: 1115
2022-07-03 18:41:54,202 INFO  [org.acm.aud.ser.AuditService] (vert.x-eventloop-thread-0) ### [TRAIL RECORDING] COUNTER: 1116
2022-07-03 18:41:55,974 INFO  [org.acm.aud.ser.AuditService] (vert.x-eventloop-thread-0) ### [TRAIL RECORDING] COUNTER: 1117
2022-07-03 18:41:57,753 ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-4) Mutiny had to drop the following exception: (RECIPIENT_FAILURE,8191) Error : 1000, Position : 0, Sql = SET TRANSACTION ISOLATION LEVEL READ COMMITTED, OriginalSql = SET TRANSACTION ISOLATION LEVEL READ COMMITTED, Error Msg = ORA-01000: maximum open cursors exceeded

	at io.vertx.core.eventbus.Message.fail(Message.java:141)
	at io.quarkus.vertx.runtime.EventConsumerInvoker$RequestActivatedConsumer.accept(EventConsumerInvoker.java:115)
	at io.quarkus.vertx.runtime.EventConsumerInvoker$RequestActivatedConsumer.accept(EventConsumerInvoker.java:91)
	at io.smallrye.context.impl.wrappers.SlowContextualBiConsumer.accept(SlowContextualBiConsumer.java:21)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onFailure(UniCallbackSubscriber.java:65)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:54)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureConsume$UniOnItemOrFailureConsumeProcessor.onFailure(UniOnItemOrFailureConsume.java:46)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:54)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:58)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.vertx.core.Future.lambda$toCompletionStage$2(Future.java:362)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onFailure(FutureImpl.java:268)
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

### Expected behavior

The Quarkus save objects in the database in a reactive manner infinitely.

### Actual behavior

Quarkus Mutiny throws an exception after persist about 1110 Reactive Panache Entity object in the Oracle database.

### How to Reproduce?

1. Clone the project at https://github.com/Swe77/reactiveoracle.git
2. Configure the application.properties with the Oracle Database data.
4. Configure the jmeter to make about 2000 calls in one thread to the endpoint http://localhost:8080/audit/v1/audit-trail
5. The Jmeter test is in the link [https://github.com/Swe77/reactiveoracle/blob/main/REACTIVE_APP_TEST.jmx](https://github.com/Swe77/reactiveoracle/blob/main/REACTIVE_APP_TEST.jmx)
6. Watch logs and jmeter Summary Report tab.

### Output of `uname -a` or `ver`

Microsoft Windows 11

### Output of `java -version`

JDK version: RedHat Open JDK (java-11-openjdk-11.0.15.9-4) (it is configured in Eclipse)

### Quarkus version or git rev

2.10.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

eclipse embedded maven (3.8.4)

**Comment by tsegismont** [comment]
@Swe77 thanks for the report. I think this is due to https://github.com/eclipse-vertx/vertx-sql-client/issues/1187

There is not yet a released version of Vert.x with the corresponding fix. It should some soon(ish).

**Comment by tsegismont** [comment]
@cescoffier when is the next Vert.x upgrade expected in Quarkus?

**Comment by cescoffier** [comment]
@tsegismont We switched to 4.3.1 last week. I'm not waiting for 4.3.2. If it happens within the next 2 weeks, it will be integrated before the "big GC pause" (aka summer PTO).
