### ISSUE TITLE
QuarkusDev not working with Kotlin version 1.7.0

### ISSUE THREAD

**Issue by LazaroR94** [quarkusio/quarkus#26588]
### Describe the bug

After upgrading to the new kotlin version **1.7.0** quarkusDev fails to run with the following stacktrace:

```
> Task :quarkusDev
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:137)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.NullPointerException
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:90)
	... 1 more
```

### Expected behavior

QuarkusDev should run as intended

### Actual behavior

```
> Task :quarkusDev
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:137)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.NullPointerException
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:90)
	... 1 more
```

### How to Reproduce?

1. Spin up a new quarkus kotlin project (I use Gradle)
2. Ensure you target kotlin version 1.7.0 as the JVM target (i.e.: `plugins { kotlin("jvm") version "1.7.0" }`)
3. Start the application

### Output of `uname -a` or `ver`

Darwin C02FW4DDMD6R 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "11.0.12" 2021-07-20 LTS

### Quarkus version or git rev

2.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by evanchooly** [comment]
related to/duplicates #26290

**Comment by LazaroR94** [comment]
Thank you @evanchooly, I will close this issue for now to prevent any duplicate threads about this same bug.
