### ISSUE TITLE
Exception "java.sql.SQLException: Connection acquired without transaction." while starting

### ISSUE THREAD

**Issue by sjaakd** [quarkusio/quarkus#26627]
### Describe the bug

Two (related?) warning messages are printed during startup.

The exception:
```
2022-07-08 16:05:07,221 WARN  [io.agr.pool] (JPA Startup Thread: <default>) Datasource '<default>': java.sql.SQLException: Connection acquired without transaction.
	at io.agroal.pool.ConnectionPool.afterAcquire(ConnectionPool.java:355)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:249)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:272)
	at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:68)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:72)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:71)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:138)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:54)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
 seems to be related to the setting:
`quarkus.datasource.jdbc.transaction-requirement=warn`

The message `WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Closing connection in incorrect state CHECKED_OUT` seems to be related to `quarkus.datasource.jdbc.flush-on-close=true`

### Expected behavior

A clean startup.

### Actual behavior

WARNINGS in the log.

```
2022-07-08 16:05:07,221 WARN  [io.agr.pool] (JPA Startup Thread: <default>) Datasource '<default>': java.sql.SQLException: Connection acquired without transaction.
	at io.agroal.pool.ConnectionPool.afterAcquire(ConnectionPool.java:355)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:249)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:272)
	at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:68)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:72)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:71)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:138)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:54)
	at java.base/java.lang.Thread.run(Thread.java:834)

2022-07-08 16:05:07,318 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Closing connection in incorrect state CHECKED_OUT
```

### How to Reproduce?

Reproducer: https://github.com/sjaakd/reproducer_db_oracle

Just start up the service (quarkus:dev) with proper DB settings

### Output of `uname -a` or `ver`

-

### Output of `java -version`

java 11

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.7.0.final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.6

### Additional information

We have been struggling with connection-leaks that we could not explain. After marking all our services with `@Transactional` and finally by removing a code common `PersistenceException` interceptor (for generating the proper HTTP response on our REST services) that problem seemed to have disappeared. Apparently the connection was not made available again.

```java 
@Provider
public class PersistentExceptionProvider extends AbstractExceptionMapper implements ExceptionMapper<PersistenceException> {

    @Override
    public Response toResponse(PersistenceException exception) {
        return toResponseInternal(
            "ExceptionMessages",
            exception,
            Response.Status.INTERNAL_SERVER_ERROR.getStatusCode(),
            null );
    }
}
```

However, we sometimes still see a Quarkus container (on our openshift cluster) consuming a lot of CPU on our cluster without probable cause.

We do use ready / live probes. The ready probe seems to be working out of the box with the proper `application.properties`

**Comment by famod** [comment]
`quarkus.datasource.jdbc.transaction-requirement` could be very useful, but as of now it's kinda crippled by fact that some connections opened by some extensions (e.g. hibernate metadata retrieval, like in your stacktrace, or liquibase/flyway) are not using a transaction _by design_ and there is no SPI yet through which those extensions could tell Agroal to back off in these cases.
See also: https://github.com/quarkusio/quarkus/pull/18946#issuecomment-983032845

Btw, me and my team we had a discussion the other day whether we could avoid some boilerplate service code by allowing direct (spring) repo access, but we didn't do it in the end because we'd loose the certainty that there's a transaction (because we cannot activate `transaction-requirement` since we are using Hibernate and Liquibase).

/cc @barreiro @Sanne

**Comment by sjaakd** [comment]
@famod thanks for your answer. I guess that annotating my resource with `@Transaction` or the specific methods should be sufficient for me than. And hence I could consider leaving out  `quarkus.datasource.jdbc.transaction-requirement` all together.

Question 1: What about the `WARN [io.agr.pool] (agroal-11) Datasource '<default>': Closing connection in incorrect state CHECKED_OUT seems to have disappeared.` message? Has that been addressed in later releases?

And, I do have some `@Startup` annotated data providers that application scoped initializes a couple of datastructures. Like this:

Question 2: is the `@Transactional` effective during startup like this? (that's why we included this setting as well).
 
```java
@Startup
@ApplicationScoped
public class GenericDataProvider {

    @Inject
    public GenericDataProvider(EntityManager entityManager) {
        this.entityManager = entityManager;
    }

    @Transactional
    public void onStart(@Observes StartupEvent ev) {
        LOG.info( "The application is initializing..." );
         // init application structure.        
        this.entityManager.clear();
        LOG.info( "Initialization done!" );
    }

```

Question 3: Also the ready check (microservice profile) fired by the openshift platform triggers DB readyness (implemented by Quarkus). Does that functionality somehow require a transaction?

**Comment by famod** [comment]
@sjaakd 

> Question 1: What about the `WARN [io.agr.pool] (agroal-11) Datasource '<default>': Closing connection in incorrect state CHECKED_OUT seems to have disappeared.` message? Has that been addressed in later releases?

Don't know for sure, but there was some fix:  https://issues.redhat.com/browse/AG-186

> Question 2: is the `@Transactional` effective during startup like this? (that's why we included this setting as well).

Yes, this should work,

> Question 3: Also the ready check (microservice profile) fired by the openshift platform triggers DB readyness (implemented by Quarkus). Does that functionality somehow require a transaction?

I don't know. Do you @jmartisk?

**Comment by sjaakd** [comment]
@famod thanks for the explanation.

**Comment by sjaakd** [comment]
What do you want me to do with this issue? For me it's clear. What remains is what is reported in https://github.com/quarkusio/quarkus/pull/18946#issuecomment-983032845. Shall I close this one?

**Comment by yrodiere** [comment]
Hey all,

Do I understand correctly that https://issues.redhat.com/browse/AG-186 fixed this issue?

If so, yes we should close this one.

**Comment by yrodiere** [comment]
No answer for several months, so I'll assume https://issues.redhat.com/browse/AG-186 fixed this issue. Please comment or open a new issue (with a clear explanation and/or a reproducer) if that's not the case.

Thanks everyone.
