### ISSUE TITLE
Building native using the latest Mandrel doesn't work

### ISSUE THREAD

**Issue by wiradikusuma** [quarkusio/quarkus#26640]
### Describe the bug

According to https://quarkus.io/guides/building-native-image, "Mandrel’s main goal is to provide a way to build native executables specifically designed to support Quarkus" — but **building native using the latest Mandrel doesn't work**:

https://github.com/graalvm/mandrel/releases/tag/mandrel-22.1.0.0-Final

Note: I'm not sure if this is Quarkus' bug or Mandrel's. Let me know and I'll update accordingly.

```
java.lang.IllegalAccessError: class io.quarkus.runner.AutoFeature (in unnamed module @0x6d4ace6f) cannot access class org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport (in module org.graalvm.sdk) because module org.graalvm.sdk does not export org.graalvm.nativeimage.impl to unnamed module @0x6d4ace6f
	at io.quarkus.runner.AutoFeature.beforeAnalysis(Unknown Source)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:731)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:731)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:573)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:530)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Fatal error: java.lang.RuntimeException: Failed to load resource quarkus-runtime-config-defaults.properties
	at io.quarkus.runtime.ResourceHelper.registerResources(ResourceHelper.java:25)
	at io.quarkus.runtime.graal.ResourcesFeature.beforeAnalysis(ResourcesFeature.java:25)
```

### Expected behavior

Build is successful.

### Actual behavior

Build failed.

### How to Reproduce?

I've created Docker image: https://hub.docker.com/r/wiradikusuma/graalvm-maven-for-quarkus — I've tried both Java 11 and Java 17 version.

1. Go to https://code.quarkus.io/ and immediately click *Generate your application*.
2. Extract the zip file.
3. Open shell and navigate to the extracted folder.
4. Run `docker run --rm -it -v $PWD:/mnt/myproject:rw -w /mnt/myproject wiradikusuma/graalvm-maven-for-quarkus:latest-java11 mvn clean package -Pnative`

### Output of `uname -a` or `ver`

Linux 9fb21205a405 4.14.252-195.483.amzn2.x86_64 #1 SMP Mon Nov 1 20:58:46 UTC 2021 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.16" 2022-07-19

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

I run this in a CI/CD environment.

**Comment by gsmet** [comment]
@zakkak have you noticed the OP is using `2.7.5.Final` with Mandrel `22.1`. I'm not sure these two are compatible versions?

**Comment by wiradikusuma** [comment]
So, background story, I had been using https://hub.docker.com/r/vegardit/graalvm-maven for my CI/CD, and yesterday it stopped working. 

I did some googling and found out that Quarkus is not compatible with the latest GraalVM. I thought hmm let's use Mandrel. So I forked the original repo and did [seach-and-replace](https://github.com/vegardit/docker-graalvm-maven/compare/main...wiradikusuma:docker-graalvm-maven-for-quarkus:main) and published the image under my account. The new image works for *non-native*.

So, honestly, I don't know what's wrong since I use an image that was working and just replaced some text 😅 Here's the Dockerfile: https://github.com/wiradikusuma/docker-graalvm-maven-for-quarkus/blob/main/image/Dockerfile

The command I use:

```
mvn package 
  -Dmaven.test.skip=true 
  -Pnative 
  -Dquarkus.container-image.build=true 
  -Dquarkus.container-image.push=true 
  -Dquarkus.container-image.registry=registry.fly.io 
  -Dquarkus.container-image.group= 
  -Dquarkus.container-image.name=backend 
  -Dquarkus.container-image.tag=1.0 
  -Dquarkus.container-image.additional-tags=latest
```

**Comment by zakkak** [comment]
> I did some googling and found out that Quarkus is not compatible with the latest GraalVM

That's not true. Which GraalVM and Quarkus version combination are you using? Quarkus 2.10 works fine with GraalVM 22.1

> So, honestly, I don't know what's wrong since I use an image that was working and just replaced some text sweat_smile Here's the Dockerfile: https://github.com/wiradikusuma/docker-graalvm-maven-for-quarkus/blob/main/image/Dockerfile

I am afraid I can't help with that as it's not a build method supported by Quarkus.

Providing the following info might allow us to give some hints in what might be wrong:

1. Log lines starting with `[INFO] [io.quarkus.deployment.pkg.steps`
2. The output of the native-image logs printed during compilation

**Comment by zakkak** [comment]
The version info `GraalVM 22.3.0-dev Java 11 CE` indicates that you are using a nightly build of GraalVM CE. You will need to use a docker image with a released GraalVM/Mandrel version compatible with the quarkus version you are using.
