### ISSUE TITLE
QuarkusProdModeTest stopped working when adding Kubernetes extensions in Quarkus 2.11

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#26726]
### Describe the bug

I've just tried the Quarkus version 2.11.0.CR1 in a project where I'm using the Quarkus test extension "QuarkusProdModeTest" as:

```java
@RegisterExtension
    static final QuarkusProdModeTest config = new QuarkusProdModeTest()
            .setForcedDependencies(
                    Arrays.asList(
                            new AppArtifact("io.quarkus", "quarkus-resteasy-reactive", Version.getVersion()),
                            new AppArtifact("io.quarkus", "quarkus-kubernetes", Version.getVersion())))
            .withApplicationRoot((jar) -> jar.addClasses(Endpoint.class))
            .withConfigurationResource("application-k8s-minimal.properties");
```

And this stopped working. I see the following warning message:

```
2022-07-14 07:03:07,523 WARN  [io.qua.kub.dep.KubernetesProcessor] (build-6) No project was detected, skipping generation of kubernetes manifests!
```

Note that before Quarkus 2.11, this was working fine.

Digging into this issue, I modified this line https://github.com/quarkusio/quarkus/blob/0cc407b5a03d13a8a5e5d4d4ea7b34842016c9a2/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java#L107 to see the actual exception and I got:

```
Caused by: java.lang.IllegalStateException: Could not find matching project info read
        at io.dekorate.project.FileProjectFactory.lambda$createInternal$0(FileProjectFactory.java:64)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.dekorate.project.FileProjectFactory.createInternal(FileProjectFactory.java:64)
        at io.dekorate.project.FileProjectFactory.create(FileProjectFactory.java:44)
        at io.quarkus.kubernetes.deployment.KubernetesCommonHelper.createProject(KubernetesCommonHelper.java:93)
```

### How to Reproduce?

1. git clone https://github.com/quarkiverse/quarkus-helm
2. cd quarkus-helm
3. git checkout bump_quarkus
4. mvn clean install

**Comment by geoand** [comment]
Sounds like a dekorate issue, no?

**Comment by Sgitario** [comment]
> Sounds like a dekorate issue, no?

I don't think so. I'm trying to find the root cause. The weirdest thing is that the integration tests we have for Kubernetes are also using QuarkusProdModeTest and they work. 

Will keep this issue updated with my findings.

**Comment by Sgitario** [comment]
> > Sounds like a dekorate issue, no?
> 
> I don't think so. I'm trying to find the root cause. The weirdest thing is that the integration tests we have for Kubernetes are also using QuarkusProdModeTest and they work.
> 
> Will keep this issue updated with my findings.

I tried with Quarkus Main and Dekorate 2.9.3.Final (the previous version) and it's still failing. So, it's not a Dekorate issue.

**Comment by Sgitario** [comment]
Another hint... when running the test in debug mode via the IDE, it works fine. Any ideas?

**Comment by Sgitario** [comment]
I've just found out that this is neither a new issue nor caused by the latest Quarkus, but it's only happening when using JDK 17. When I switched out to JDK 11, everything started working fine. Closing.
