### ISSUE TITLE
Injecting io.quarkus.scheduler.Scheduler throws StackoverFlowError

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#26756]
### Discussed in https://github.com/quarkusio/quarkus/discussions/26746

<div type='discussions-op-text'>

<sup>Originally posted by **ramila** July 15, 2022</sup>
Hi;

I'm trying to Inject the built-in Scheduler to pause/resume a scheduled job. I followed the documentation https://quarkus.io/guides/scheduler-reference. 

import io.quarkus.logging.Log;
import io.quarkus.scheduler.Scheduled;
import io.quarkus.scheduler.Scheduler;

import javax.inject.Inject;
import java.sql.SQLException;

import static io.quarkus.scheduler.Scheduled.ConcurrentExecution.SKIP;

public class ForwarderBean extends TimerBean {
    @Inject
    Scheduler scheduler;

    @Override
    @Scheduled(
        identity = "forwarderSchedule",
        every = "5s",
        concurrentExecution = SKIP,
        skipExecutionIf = ForwarderPredicate.class)
    protected void action() throws SQLException {
        Log.infof("Fired Forwarder timer");
    }
}

when the applications starts up i get the following error:

2022-07-15 10:26:05,567 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.StackOverflowError
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at io.smallrye.config.SysPropConfigSource.getValue(SysPropConfigSource.java:53)
        at io.smallrye.config.ConfigValueConfigSourceWrapper.getConfigValue(ConfigValueConfigSourceWrapper.java:20)
        at io.smallrye.config.SmallRyeConfigSources.getValue(SmallRyeConfigSources.java:29)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.SecretKeysConfigSourceInterceptor.getValue(SecretKeysConfigSourceInterceptor.java:22)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.RelocateConfigSourceInterceptor.getValue(RelocateConfigSourceInterceptor.java:25)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.RelocateConfigSourceInterceptor.getValue(RelocateConfigSourceInterceptor.java:25)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.ProfileConfigSourceInterceptor.getProfileValue(ProfileConfigSourceInterceptor.java:62)
        at io.smallrye.config.ProfileConfigSourceInterceptor.getValue(ProfileConfigSourceInterceptor.java:43)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:46)
        at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:38)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.FallbackConfigSourceInterceptor.getValue(FallbackConfigSourceInterceptor.java:24)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.PropertyNamesConfigSourceInterceptor.getValue(PropertyNamesConfigSourceInterceptor.java:17)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:307)
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:225)
        at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:324)
        at io.quarkus.scheduler.common.runtime.util.SchedulerUtils$1.accept(SchedulerUtils.java:122)
        at io.quarkus.scheduler.common.runtime.util.SchedulerUtils$1.accept(SchedulerUtils.java:119)
        at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
        at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
        at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
        at io.quarkus.scheduler.common.runtime.util.SchedulerUtils.resolvePropertyExpression(SchedulerUtils.java:119)
        at io.quarkus.scheduler.common.runtime.util.SchedulerUtils.lookUpPropertyValue(SchedulerUtils.java:87)
        at io.quarkus.scheduler.runtime.SimpleScheduler.createTrigger(SimpleScheduler.java:234)
        at io.quarkus.scheduler.runtime.SimpleScheduler_Subclass.createTrigger$$superforward1(Unknown Source)
        at io.quarkus.scheduler.runtime.SimpleScheduler_Subclass.createTrigger(Unknown Source)
        at io.quarkus.scheduler.runtime.SimpleScheduler.<init>(SimpleScheduler.java:106)
        at io.quarkus.scheduler.runtime.SimpleScheduler_Subclass.<init>(Unknown Source)
        at io.quarkus.scheduler.runtime.SimpleScheduler_Bean.create(Unknown Source)
        at io.quarkus.scheduler.runtime.SimpleScheduler_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
        at io.quarkus.scheduler.runtime.SimpleScheduler_Bean.get(Unknown Source)
        at io.quarkus.scheduler.runtime.SimpleScheduler_Bean.get(Unknown Source)
        at com.ifs.notification.ForwarderBean_Bean.create(Unknown Source)
        at com.ifs.notification.ForwarderBean_Bean.create(Unknown Source)

It seems to be complaining about privileges/configsource. I have included following dependencies. Am I missing something?

<quarkus.platform.version>2.10.1.Final</quarkus.platform.version>
...
....
<dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-websockets</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-agroal</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-oracle</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-scheduler</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

Thanx in advance
- ramila</div>

**Comment by gsmet** [comment]
@ramila any chance you could provide a simple reproducer for this one (i.e. a simple Maven project reproducing the issue)?

**Comment by geoand** [comment]
Closing this as we never got a reproducer.

Feel free to comment / reopen if you have more information
