### ISSUE TITLE
OpenTelemetry: NPE in HttpInstrumenterVertxTracer.RouteGetter when request got cancelled

### ISSUE THREAD

**Issue by calohmn** [quarkusio/quarkus#26764]
### Describe the bug

Relates to [#26356](https://github.com/quarkusio/quarkus/pull/26356/files#diff-8dd25e6bcffd41aa6d82e224799fbf61b9708d6d8a3ead2c7ed32ad261d62cccR152):
Using a vert.x HTTP server along with `quarkus-opentelemetry`, we are seeing such exceptions in the logs:
```
java.lang.NullPointerException: Cannot invoke "io.vertx.core.spi.observability.HttpResponse.statusCode()" because "response" is null
	at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer$RouteGetter.get(HttpInstrumenterVertxTracer.java:153)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer$RouteGetter.get(HttpInstrumenterVertxTracer.java:136)
	at io.opentelemetry.instrumentation.api.instrumenter.http.HttpRouteHolder.updateHttpRoute(HttpRouteHolder.java:125)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer.sendResponse(HttpInstrumenterVertxTracer.java:94)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer.sendResponse(HttpInstrumenterVertxTracer.java:41)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.OpenTelemetryVertxTracer.sendResponse(OpenTelemetryVertxTracer.java:47)
	at io.quarkus.opentelemetry.runtime.tracing.vertx.OpenTelemetryVertxTracer.sendResponse(OpenTelemetryVertxTracer.java:16)
	at io.vertx.core.http.impl.Http1xServerRequest.reportRequestReset(Http1xServerRequest.java:645)
	at io.vertx.core.http.impl.Http1xServerRequest.handleException(Http1xServerRequest.java:623)
	at io.vertx.core.http.impl.Http1xServerConnection.lambda$handleClosed$6(Http1xServerConnection.java:455)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163)
	at io.vertx.core.impl.AbstractContext.execute(AbstractContext.java:58)
	at io.vertx.core.http.impl.Http1xServerConnection.handleClosed(Http1xServerConnection.java:454)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[...]
```

They occur when a client cancels a request before the server has sent a response.

### Quarkus version or git rev

2.10.2

**Comment by tmihalac** [comment]
Working on this
