### ISSUE TITLE
Quarkus compiler/extension use JDK-17 classes even when compiler-target/release is set to 11

### ISSUE THREAD

**Issue by lostiniceland** [quarkusio/quarkus#26859]
### Describe the bug

We are migrating our Quarkus services from JDK 11 to 17. In the first step we moved our build-pipeline to run with JDK-17, while still having set the compiler-target (bytecode level) to JDK-11 by setting `<release>11</release>` in the the **maven-compiler-plugin**.

The built image is still running with JDK-11 and now when starting the application Quarkus tries to load java.util.InstantSource which is a [new class since JDK-17](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/InstantSource.html). The Code is triggered from a Clock-Config but InstantSource is not used directly

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.base/java.lang.Class.newInstance(Unknown Source)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at ourpackage.Main.main(Main.java:10)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 15 more
Caused by: java.lang.ClassNotFoundException: java.time.InstantSource
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:66)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:57)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at ourpackage.ClockConfiguration_ProducerMethod_systemClock_a5266df8284edb30622299b8a888fe9c87d38a88_Bean.<init>(Unknown Source)
        at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans4(Unknown Source)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
        at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:118)
        at io.quarkus.arc.Arc.initialize(Arc.java:24)
        at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:40)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources686947423.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources686947423.deploy(Unknown Source)
```

Since the maven-compiler is setup correct, I assume that the Quarkus-extension do not honor this setting when they do their magic.

### Expected behavior

Compiling against a different JDK-Version doesn not use wrong classes.

### How to Reproduce?

Configure a Clock-Provider
```
@Dependent
public class ClockConfiguration {

    @DefaultBean
    @ApplicationScoped
    public Clock systemClock() {
        return Clock.systemDefaultZone();
    }
```
Compile with JDK-17 and using release 11 in maven-compiler

Run with JRE-11

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 LTS

### Quarkus version or git rev

2.7.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by Erfankam** [comment]
Could I work on this issue?

**Comment by yrodiere** [comment]
I believe you need to either:

* set the target release through the Maven property `maven.compiler.release`:
  ```
  <properties>
    <!-- ... -->
    <maven.compiler.release>11</maven.compiler.release>
    <!-- ... -->
  </properties>
  ```
* OR add a configuration section to the quarkus-maven-plugin to set the release that Quarkus should target, e.g.:
  ```
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <!-- ADD THIS -->
          <release>11</release>
        </configuration>
      </plugin>
  ```

If you just set `<release>` in the `<configuration>` section of the maven-compiler-plugin, then I'm not sure Quarkus can possibly know what it needs to target, and I think it will target the version of your JDK.

---

If the above does not solve your problem, we'll need a loook at your code; in particular I'm wondering what `ourpackage.ClockConfiguration#systemClock` does exactly?

---

> Could I work on this issue?

@Erfankam I'm not sure there really is something to fix, see above.

**Comment by lostiniceland** [comment]
Setting the release also on the quarkus-plugin seems like a good solution.
