### ISSUE TITLE
2.11.0.Final -A grpc service that is behind rest service is UNAVAILABLE during junit. I expect it to start. 

### ISSUE THREAD

**Issue by anborg** [quarkusio/quarkus#26905]
### Describe the bug

2.11.0.Final - compilation error - dependencies not in maven repo?

https://github.com/anborg/m-app-rest/blob/8b98b01f97412b188fbb32e291414b762fea0b04/pom.xml#L22

```log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] muni-api-protogen 1.0-SNAPSHOT ..................... SUCCESS [  5.524 s]
[INFO] amanda-soap-client 6.1.8.0-SNAPSHOT ................ SUCCESS [  7.956 s]
[INFO] lib-amanda 1.0-SNAPSHOT ............................ SUCCESS [  3.640 s]
[INFO] lib-hansen 1.0-SNAPSHOT ............................ SUCCESS [  0.632 s]
[INFO] lib-integ 1.0-SNAPSHOT ............................. SUCCESS [  0.801 s]
[INFO] app-rest 1.0-SNAPSHOT .............................. FAILURE [ 15.040 s]
[INFO] react-admin 1.0-SNAPSHOT ........................... SKIPPED
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.11.0.Final:build (default) on project app-rest: Execution default of goal io.quarkus:quarkus-maven
-plugin:2.11.0.Final:build failed: Plugin io.quarkus:quarkus-maven-plugin:2.11.0.Final or one of its dependencies could not be resolved: Failed to read artifact de
scriptor for io.quarkus:quarkus-maven-plugin:jar:2.11.0.Final: io.quarkus:quarkus-bom:pom:${project.version} was not found in https://repo.maven.apache.org/maven2 
during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or up
dates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :app-rest
```

### Expected behavior

Should compile as before

### Actual behavior

compile error - dependency not found in maven

### How to Reproduce?

```shell
git clone https://github.com/anborg/m-all

#Dependency error here
git clone https://github.com/anborg/m-app-rest

git clone https://github.com/anborg/muni-model
git clone https://github.com/anborg/m-lib-integ

cd m-all
mvn package
```

### Output of `uname -a` or `ver`

windows

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7) OpenJDK Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, emulated-client, sharing)

### Quarkus version or git rev

2.11.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)

### Additional information

```log
PS C:\projects\mkm\m-all> mvn -version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: c:\apps\apache-maven-3.8.5
Java version: 17.0.3, vendor: Eclipse Adoptium, runtime: C:\apps\jdk_17.0.3
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "x86", family: "windows"
```

**Comment by famod** [comment]
Try adding `-U` to `mvn`. If it works you can remove `-U` again.

**Comment by anborg** [comment]
A grpc service that is behind rest service is UNAVAILABLE during junit. I expect it to start. 

Before I moved to 2.11, the test suit was working.

```log
2022-07-25 08:25:41,875 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /mkapp/rest/v1/persons/1 failed, error id: 2135a151-cc38
-4b05-825c-7918b23acdb2-1: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
        at muni.model.PersonServiceGrpc$PersonServiceBlockingStub.get(PersonServiceGrpc.java:505)
        at app.api.rest.PersonResource.get(PersonResource.java:40)
        at app.api.rest.PersonResource$quarkusrestinvoker$get_7c2dccad942b063f8a074cc381d31d321bf5f98b.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:9000
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

2022-07-25 08:25:41,880 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: io.grpc.StatusRuntimeException: UNAVAIL
ABLE: io exception
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
        at muni.model.PersonServiceGrpc$PersonServiceBlockingStub.get(PersonServiceGrpc.java:505)
        at app.api.rest.PersonResource.get(PersonResource.java:40)
        at app.api.rest.PersonResource$quarkusrestinvoker$get_7c2dccad942b063f8a074cc381d31d321bf5f98b.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:9000
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.857 s <<< FAILURE! - in app.PersonResourceTest
[ERROR] personById  Time elapsed: 1.685 s  <<< FAILURE!
java.lang.AssertionError:
1 expectation failed.
Expected status code <200> but was <500>.

        at app.PersonResourceTest.personById(PersonResourceTest.java:61)

[INFO] Running app.grpc.PersonServiceGrpcTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in app.grpc.PersonServiceGrpcTest
[ERROR] getPersons  Time elapsed: 0.001 s  <<< ERROR!
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app.grpc.PersonServiceGrpcTest.getPersons(PersonServiceGrpcTest.java:47)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:9000
Caused by: java.net.ConnectException: Connection refused: no further information

2022-07-25 08:25:42,019 INFO  [io.qua.grp.run.sup.Channels] (main) Shutting down gRPC channel ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=4, targ
et=dns:///localhost:9000}}
2022-07-25 08:25:42,037 INFO  [io.quarkus] (main) app-rest stopped in 0.044s
[INFO] 
[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   PersonResourceTest.personById:61 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR] Errors: 
[ERROR]   PersonServiceGrpcTest.getPersons:47 » StatusRuntime UNAVAILABLE: io exception
[INFO]
[ERROR] Tests run: 2, Failures: 1, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] muni-api-protogen 1.0-SNAPSHOT ..................... SUCCESS [ 10.199 s]
[INFO] amanda-soap-client 6.1.8.0-SNAPSHOT ................ SUCCESS [  2.108 s]
[INFO] lib-amanda 1.0-SNAPSHOT ............................ SUCCESS [  1.706 s]
[INFO] lib-hansen 1.0-SNAPSHOT ............................ SUCCESS [  2.991 s]
[INFO] lib-integ 1.0-SNAPSHOT ............................. SUCCESS [  6.844 s]
[INFO] app-rest 1.0-SNAPSHOT .............................. FAILURE [ 27.566 s]
[INFO] react-admin 1.0-SNAPSHOT ........................... SKIPPED
[INFO] m-all 1.0 .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

```

**Comment by famod** [comment]
@anborg can you please create a new issue? Changing the scope like this is very confusing.
