### ISSUE TITLE
2.11.0.Final : rest->grpc unit test fails. The dependent grpc service must be instantiated during test automagically

### ISSUE THREAD

**Issue by anborg** [quarkusio/quarkus#26915]
### Describe the bug

A grpc service that is behind rest service is UNAVAILABLE during junit. I expect it to start. 

Before I moved to 2.11, the test suit was working.

How to get dependent grpc services available during quarkus unit tests?

Distraction please ignore: The reason why I have a grpc behind REST - is to support both REST and GRPC version of api -- if quarkus has a better way of having rest & grpc without code duplication that would be nice. 

Code reference for reproducing : #26905

```log
2022-07-25 08:25:41,875 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /mkapp/rest/v1/persons/1 failed, error id: 2135a151-cc38
-4b05-825c-7918b23acdb2-1: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
        at muni.model.PersonServiceGrpc$PersonServiceBlockingStub.get(PersonServiceGrpc.java:505)
        at app.api.rest.PersonResource.get(PersonResource.java:40)
        at app.api.rest.PersonResource$quarkusrestinvoker$get_7c2dccad942b063f8a074cc381d31d321bf5f98b.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:9000
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

2022-07-25 08:25:41,880 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: io.grpc.StatusRuntimeException: UNAVAIL
ABLE: io exception
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
        at muni.model.PersonServiceGrpc$PersonServiceBlockingStub.get(PersonServiceGrpc.java:505)
        at app.api.rest.PersonResource.get(PersonResource.java:40)
        at app.api.rest.PersonResource$quarkusrestinvoker$get_7c2dccad942b063f8a074cc381d31d321bf5f98b.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:9000
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.857 s <<< FAILURE! - in app.PersonResourceTest
[ERROR] personById  Time elapsed: 1.685 s  <<< FAILURE!
java.lang.AssertionError:
1 expectation failed.
Expected status code <200> but was <500>.

        at app.PersonResourceTest.personById(PersonResourceTest.java:61)

[INFO] Running app.grpc.PersonServiceGrpcTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in app.grpc.PersonServiceGrpcTest
[ERROR] getPersons  Time elapsed: 0.001 s  <<< ERROR!
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app.grpc.PersonServiceGrpcTest.getPersons(PersonServiceGrpcTest.java:47)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:9000
Caused by: java.net.ConnectException: Connection refused: no further information

2022-07-25 08:25:42,019 INFO  [io.qua.grp.run.sup.Channels] (main) Shutting down gRPC channel ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=4, targ
et=dns:///localhost:9000}}
2022-07-25 08:25:42,037 INFO  [io.quarkus] (main) app-rest stopped in 0.044s
[INFO] 
[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   PersonResourceTest.personById:61 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR] Errors: 
[ERROR]   PersonServiceGrpcTest.getPersons:47 » StatusRuntime UNAVAILABLE: io exception
[INFO]
[ERROR] Tests run: 2, Failures: 1, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] muni-api-protogen 1.0-SNAPSHOT ..................... SUCCESS [ 10.199 s]
[INFO] amanda-soap-client 6.1.8.0-SNAPSHOT ................ SUCCESS [  2.108 s]
[INFO] lib-amanda 1.0-SNAPSHOT ............................ SUCCESS [  1.706 s]
[INFO] lib-hansen 1.0-SNAPSHOT ............................ SUCCESS [  2.991 s]
[INFO] lib-integ 1.0-SNAPSHOT ............................. SUCCESS [  6.844 s]
[INFO] app-rest 1.0-SNAPSHOT .............................. FAILURE [ 27.566 s]
[INFO] react-admin 1.0-SNAPSHOT ........................... SKIPPED
[INFO] m-all 1.0 .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

```

**Comment by cescoffier** [comment]
Is tour module depending on the gRPC service implementation modules?

**Comment by geoand** [comment]
If you have a sample application showing the behavior (which you mention worked pre `2.11`), it would be great for us to have

**Comment by anborg** [comment]
> If you have a sample application showing the behavior (which you mention worked pre `2.11`), it would be great for us to have

Hi @geoand, Sample application referred here: https://github.com/quarkusio/quarkus/issues/26905

**Comment by geoand** [comment]
Your sample does seem to contain all the modules you mention.

**Comment by anborg** [comment]
run "mvn package"

```log
2022-07-27 10:14:13,159 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /mkapp/rest/v1/persons/1 failed, error id: d9f30aaf-f8b3
-466f-ac02-9d4c129479ee-1: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
        at muni.model.PersonServiceGrpc$PersonServiceBlockingStub.get(PersonServiceGrpc.java:505)
        at app.api.rest.PersonResource.get(PersonResource.java:40)
        at app.api.rest.PersonResource$quarkusrestinvoker$get_7c2dccad942b063f8a074cc381d31d321bf5f98b.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:9000
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

2022-07-27 10:14:13,164 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: io.grpc.StatusRuntimeException: UNAVAIL
ABLE: io exception
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
        at muni.model.PersonServiceGrpc$PersonServiceBlockingStub.get(PersonServiceGrpc.java:505)
        at app.api.rest.PersonResource.get(PersonResource.java:40)
        at app.api.rest.PersonResource$quarkusrestinvoker$get_7c2dccad942b063f8a074cc381d31d321bf5f98b.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:9000
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.887 s <<< FAILURE! - in app.PersonResourceTest
[ERROR] personById  Time elapsed: 1.594 s  <<< FAILURE!
java.lang.AssertionError:
1 expectation failed.
Expected status code <200> but was <500>.

        at app.PersonResourceTest.personById(PersonResourceTest.java:61)

[INFO] Running app.grpc.PersonServiceGrpcTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in app.grpc.PersonServiceGrpcTest
[ERROR] getPersons  Time elapsed: 0 s  <<< ERROR!
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app.grpc.PersonServiceGrpcTest.getPersons(PersonServiceGrpcTest.java:47)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:9000
Caused by: java.net.ConnectException: Connection refused: no further information

2022-07-27 10:14:13,290 INFO  [io.qua.grp.run.sup.Channels] (main) Shutting down gRPC channel ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=4, targ
et=dns:///localhost:9000}}
2022-07-27 10:14:13,304 INFO  [io.quarkus] (main) app-rest stopped in 0.038s
[INFO] 
[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   PersonResourceTest.personById:61 1 expectation failed.

```

**Comment by geoand** [comment]
> run "mvn package"

Just did, the result is:

```
[ERROR] Failed to execute goal on project app-rest: Could not resolve dependencies for project m:app-rest:jar:1.0-SNAPSHOT: Could not find artifact m:lib-integ:jar:1.0-SNAPSHOT -> [Hel
```

**Comment by anborg** [comment]
> 

```
git clone https://github.com/anborg/m-all
#Dependency error here
git clone https://github.com/anborg/m-app-rest

git clone https://github.com/anborg/muni-model
git clone https://github.com/anborg/m-lib-integ
git clone https://github.com/anborg/m-lib-amanda
git clone https://github.com/anborg/m-lib-hansen


cd m-all
mvn test
```
Code reference for reproducing : https://github.com/quarkusio/quarkus/issues/26905

**Comment by geoand** [comment]
Can you please provide a sample bash script that clones and installs in the proper order? I tried the order you mention and things still don't work.

**Comment by cescoffier** [comment]
I have the same problem as @geoand.
Please provides a simple standalone reproducer.

**Comment by geoand** [comment]
@anborg any luck in providing what we asked for above?

**Comment by geoand** [comment]
Closing as we did not get feedback
