### ISSUE TITLE
smallrye jwt returns Response despite exception being caught

### ISSUE THREAD

**Issue by marcvanR** [quarkusio/quarkus#26922]
### Describe the bug

I have a simple quarkus reactive resteasy server

```java
@Path("/")
@ApplicationScoped
public class Hello {

    @GET
    @Path("hello")
    @RolesAllowed({"roleYouNeed"})
    @Blocking
    public Uni<Response> hello(){
        return Uni.createFrom().item(Response.ok("hello").build());
    }
}
        
```

Following the documentation found here I create several exception mappers to return a response body which elaborates on the status code. This one for example works when you do not provide a JWT token to a request that needs it:

```java
@Provider//register as JAXRS provider
@Priority(1)//override the build-int mapper(which has 5001 prio)
@Slf4j
public class UnauthorizedExceptionMapper implements ExceptionMapper<UnauthorizedException> {
    @Override
    public Response toResponse(UnauthorizedException exception) {
        log.warn("There was an incoming request that did not have the correct Authorization");
        return Response.status(Response.Status.UNAUTHORIZED)
                .entity(new ErrorResponseObject().addErrorsItem(new ErrorResponseObjectErrorsInner()
                        .code(String.valueOf(Response.Status.UNAUTHORIZED.getStatusCode()))
                        .detail("Unauthorized")))
                .build();
    }

}
```

This works as expected on my endpoint that uses quarkus-smallrye-jwt with the annotation `@RolesAllowed({"roleYouNeed"})`

When someone sends a token that is truly worthless however a JWTParse Exception occurs and a different exception is raised, the `AuthenticationFailedException`

To catch this one I created 

```java
@Provider
@Priority(1)
@Slf4j
public class AuthenticationExceptionMapper implements ExceptionMapper<AuthenticationFailedException> {
    @Override
    public Response toResponse(AuthenticationFailedException exception) {
        log.warn("There was an incoming request that did not have the correct Authorization");
        return Response.status(Response.Status.UNAUTHORIZED)
                .entity(new ErrorResponseObject().addErrorsItem(new ErrorResponseObjectErrorsInner()
                        .code(String.valueOf(Response.Status.UNAUTHORIZED.getStatusCode()))
                        .detail("Unauthorized")))
                .build();
    }
}
```

This does catch the exception and my warning is logged: `[com.ene.odp.exc.AuthenticationExceptionMapper] (vert.x-eventloop-thread-0) There was an incoming request that did not have the correct Authorization
`. The problem here is that a response has already been returned and I see the following error occurring:

```
2022-07-25 16:22:03,812 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-1) Request failed: java.io.IOException: java.io.IOException: Failed to write
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.close(ResteasyReactiveOutputStream.java:272)
        at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.BasicServerJacksonMessageBodyWriter.writeResponse(BasicServerJacksonMessageBodyWriter.java:44)
        at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:207)
        at org.jboss.resteasy.reactive.server.core.serialization.DynamicEntityWriter.write(DynamicEntityWriter.java:104)
        at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:31)
        at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:15)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
        at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:73)
        at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:70)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Failed to write
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:109)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.writeBlocking(ResteasyReactiveOutputStream.java:224)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.close(ResteasyReactiveOutputStream.java:270)
        ... 18 more
Caused by: java.lang.IllegalStateException: Response has already been written
        at io.vertx.core.http.impl.Http1xServerResponse.checkValid(Http1xServerResponse.java:675)
        at io.vertx.core.http.impl.Http1xServerResponse.writeQueueFull(Http1xServerResponse.java:274)
        at io.quarkus.vertx.http.runtime.filters.AbstractResponseWrapper.writeQueueFull(AbstractResponseWrapper.java:486)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.awaitWriteable(ResteasyReactiveOutputStream.java:116)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:82)
```

Why is the response already being returned while I catch this exception? How can I make sure nothing is returned except what I return from the `AuthenticationExceptionMapper`?

### Expected behavior

When I catch the exception in my AuthenticationExceptionMapper no response is returned except one that I return from the mapper. 

### Actual behavior

The smallrye-jwt extension returns a 401 before I can return an adequate response from my exception mapper

### How to Reproduce?

Create a simple server with an endpoint that uses the smallrye-jwt extension. Create an extension mapper that catches the AuthenticationFailedException and then call the endpoint with some gibberish Authorization: Bearer <Token>. 

### Output of `uname -a` or `ver`

21.0.1 Darwin Kernel Version 21.0.1: Tue Sep 14 20:56:24 PDT 2021; root:xnu-8019.30.61~4/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### Quarkus version or git rev

2.9.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.4

**Comment by sberyozkin** [comment]
Hi @marcvanR 
`smallrye-jwt` is not controlling this exception mapping, it is only throwing the exception.

It looks like you need to implement it a bit differently, see a default [AuthenticationFailedExceptionMapper](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/exceptionmappers/AuthenticationFailedExceptionMapper.java), and return `Uni<Response>`.

Hope it will work.
However, it is not clear why a `RestEasy Classic` style of mapping the exceptions works for `UnauthorizedExceptionMapper`, while a similar approach does not work for `AuthenticationFailedExceptionMapper`. 
Also CC Georgios @geoand

**Comment by geoand** [comment]
Thanks for tagging me @sberyozkin. 

@marcvanR if you attach a sample that works with RESTEasy Classic and not Reactive, I can have a look

**Comment by DavideD** [comment]
Why using `@Blocking` in this case?

**Comment by marcvanR** [comment]
The @Blocking was used in the more elaborate use case that I actually have and I wanted it to mimic that situation as much as possible. 

Besides that I'm trying to implement what you are suggesting, so now I have:

```java
@Path("/")
@ApplicationScoped
public class Hello {

    @GET
    @Path("hello")
    @RolesAllowed({"roleINeed"})
    public Uni<Response> hello() {
        return Uni.createFrom().item(Response.ok("hello").build());
    }
}
```
Together with 

```java
@Slf4j
public class ExceptionMapper {

    @ServerExceptionMapper(value = AuthenticationFailedException.class, priority = Priorities.USER) 
    public Uni<Response> handle(RoutingContext routingContext) {
        log.info("we found ourselves trapped here");
        return Uni.createFrom()
                .item(Response
                        .status(401)
                        .entity("some message").build());
    }
}
```

But that still gives the `java.lang.IllegalStateException: Response has already been written` error message. 

Am I implementing it incorrectly?

Thanks!

**Comment by DavideD** [comment]
I suspect the issue is that the stream gets closed too soon because it's a Uni. Something similar to what happens here: https://github.com/quarkusio/quarkus/issues/23739#issuecomment-1172851744

(I haven't checked the code though and I might be completely off)

**Comment by sberyozkin** [comment]
@marcvanR Can you please put a breakpoint at https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java#L84 ? I wonder if that code is still executed...

**Comment by marcvanR** [comment]
@sberyozkin, the code does not reach that point.

**Comment by marcvanR** [comment]
@sberyozkin Do you have any idea what is going wrong or how I could fix it?

**Comment by DavideD** [comment]
It would speed up things if you could provide a small reproducer

**Comment by marcvanR** [comment]
I created the smallest reproducible example in a repo here:

https://github.com/marcvanR/quarkus-reproducer

Run it and call 

```bash
curl "http://localhost:8080/hello" -vvv -H "Authorization: Bearer "
```

To get the Unauthorised response, and 

```bash
curl "http://localhost:8080/hello" -vvv -H "Authorization: Bearer asdgasdg"
```

To see the error message and get a standard Unauthorised response.

**Comment by DavideD** [comment]
Thanks @marcvanR! I can see reproduce the exception now.

**Comment by DavideD** [comment]
I think the problem is that the `HttpSecurityRecorder` ends the response without considering that we might have a custom mapper that wants to add something to it.

The response gets closed in [HttpSecurityRecorder#authenticationMechanismHandler](https://github.com/quarkusio/quarkus/blob/d6ac3208dd2201bb15bda8009c2cc3303afd2aad/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpSecurityRecorder.java#L85) when the exception is caught. Then the custom mapper tries to add something to it with `Response.status(401).entity("some message").build()` and that's when the error occurs.

I hope this help.

**Comment by marcvanR** [comment]
Thanks for taking another look!

I'm not sure how to use this information to get it to work. Or is it just something that will not work? 
Maybe I'm still missing something.

**Comment by DavideD** [comment]
Sorry, my message wasn’t clear.

I think this is a bug (probably in RestEasy reactive). I don’t have a workaround. It happens even when Uni are not used.

I haven’t tested it using RestEasy non reactive

**Comment by marcvanR** [comment]
Ok thanks! 

I guess for now I'll have to create my own implementation of the JWT verification and throw the appropriate exceptions within the method itself.

**Comment by jessydeclerck** [comment]
Hello, I have the same issue.

 I've also noticed that when I put a breakpoint in :https://github.com/quarkusio/quarkus/blob/94024509974b65ca00b99d09bbb094482da8b63c/extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/exceptionmappers/SecurityExceptionMapperUtil.java#L19
The 401 response is returned before this method is fully executed.



Does someone know a workaround and if this issue is currently being fixed ? 

Thanks !

**Comment by michalvavrik** [comment]
> Does someone know a workaround and if this issue is currently being fixed ?

- I'm working on this as part of the https://github.com/quarkusio/quarkus/issues/5751, here you can also see an exception as RR tries to write to ended routing context, but exception is correct - it's illegal state we must fix.
- I used @marcvanR reproducer and you can workaround his issue in 2 steps
  - do not catch `UnauthorizedException`, or if you need to catch it as it's also thrown in other places, just accept the exception is going to be thrown. The exception doesn't affect the response, it just informs you that what you returned in your exception mapper won't be written to response as response has already been sent.
  - add custom auth mechanism
```Java
package org.acme;

import io.quarkus.arc.Priority;
import io.quarkus.security.identity.IdentityProviderManager;
import io.quarkus.security.identity.SecurityIdentity;
import io.quarkus.security.identity.request.AuthenticationRequest;
import io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMechanism;
import io.quarkus.vertx.http.runtime.security.ChallengeData;
import io.quarkus.vertx.http.runtime.security.HttpAuthenticationMechanism;
import io.quarkus.vertx.http.runtime.security.HttpCredentialTransport;
import io.smallrye.mutiny.Uni;
import io.vertx.core.buffer.Buffer;
import io.vertx.ext.web.RoutingContext;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Alternative;
import javax.inject.Inject;
import java.util.Set;

@Alternative
@Priority(1)
@ApplicationScoped
public class CustomAuthMechanism implements HttpAuthenticationMechanism {

    @Inject
    JWTAuthMechanism delegate;

    @Override
    public Uni<SecurityIdentity> authenticate(RoutingContext context, IdentityProviderManager identityProviderManager) {
        return delegate.authenticate(context, identityProviderManager);
    }

    @Override
    public Uni<ChallengeData> getChallenge(RoutingContext context) {
        return delegate.getChallenge(context);
    }

    @Override
    public Set<Class<? extends AuthenticationRequest>> getCredentialTypes() {
        return delegate.getCredentialTypes();
    }

    @Override
    public Uni<Boolean> sendChallenge(RoutingContext context) {
        // Here you can set custom body to your 401.
        // I'll leave body serialization on you as I don't know your production code.
        context.response().end(Buffer.buffer("My custom response"));
        return delegate.sendChallenge(context);
    }

    @Override
    public HttpCredentialTransport getCredentialTransport() {
        return delegate.getCredentialTransport();
    }

    @Override
    public Uni<HttpCredentialTransport> getCredentialTransport(RoutingContext context) {
        return delegate.getCredentialTransport(context);
    }

    @Override
    public int getPriority() {
        return delegate.getPriority();
    }
}
```

**Comment by marcvanR** [comment]
@michalvavrik I tried again with quarkus version 2.13.4.Final but the problem I started with is still present. I assumed your fix would resolve my issues, but maybe I'm misunderstanding the fix?

**Comment by michalvavrik** [comment]
@marcvanR there has been a lot of done in this area, to be honest I lost count, BUT:

You tested it with 2.13.4 and there are 2 PRs linked with this issue, one says 2.14, one 2.15. Could you try your application with current Quarkus main? I also suppose there have been related issues that could also positively impact this issue. I always use in my PRs tests that are more or less identical to reproducers, so it should be fixed.

To have certainty, you can test you application with current main (see https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md and set up of quickstarts https://github.com/quarkusio/quarkus-quickstarts that also uses 999-SNAPSHOT). If you can verify it's not fixed, I'll have a look. Thanks for your time

**Comment by marcvanR** [comment]
@michalvavrik I guess I should have read through the releases more carefully. It works now as expected.

Thanks a lot! It's really appreciated.
