### ISSUE TITLE
Jakarta - EE 9 - Infinispan Client IT fails because javax.annotation.Generated is not available

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#26984]
When building the Infinispan Client IT in the `jakarta-rewrite` branch, we get the following failure:

```
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
    at java.net.URLClassLoader.findClass (URLClassLoader.java:471)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:589)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:522)
    at org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor.addGeneratedClassHeader (AutoProtoSchemaBuilderAnnotationProcessor.java:578)
    at org.infinispan.protostream.annotations.impl.processor.MarshallerSourceCodeGenerator.generateMessageMarshaller (MarshallerSourceCodeGenerator.java:170)
    at org.infinispan.protostream.annotations.impl.processor.MarshallerSourceCodeGenerator.generateMarshaller (MarshallerSourceCodeGenerator.java:58)
    at org.infinispan.protostream.annotations.impl.BaseProtoSchemaGenerator.generateMarshallers (BaseProtoSchemaGenerator.java:203)
    at org.infinispan.protostream.annotations.impl.BaseProtoSchemaGenerator.generateAndRegister (BaseProtoSchemaGenerator.java:174)
    at org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor.processClass (AutoProtoSchemaBuilderAnnotationProcessor.java:333)
    at org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor.processElement (AutoProtoSchemaBuilderAnnotationProcessor.java:263)
    at org.infinispan.protostream.annotations.impl.processor.AutoProtoSchemaBuilderAnnotationProcessor.process (AutoProtoSchemaBuilderAnnotationProcessor.java:186)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor (JavacProcessingEnvironment.java:980)

```

Several options to fix that:
- test which `@Generated` annotation is available via reflection and use it, instead of blindly use the `javax` one
- switch to a custom `@Generated` annotation hosted in an Infinispan package - this is what Clément did for gRPC
- detect the JDK version and starting from 11 (or use reflection to detect the availability of the annotation), use `javax.annotation.processing.Generated` which is available in the JDK starting 11 instead of the `javax.annotation.Generated` (given only the name of the class is used, it should be an easy switch - obviously you would need to drop the import and use the class names directly)

Note that I have no idea if it's the only problem we will have with Infinispan Client :).

**Comment by karesti** [comment]
I created a PROTO Issue. Further investigation might be needed for the Infinispan https://issues.redhat.com/browse/IPROTO-239

**Comment by gsmet** [comment]
@karesti so I tried to work around it and see if it was the only issue but it's not:

```
Caused by: java.lang.NoClassDefFoundError: javax/transaction/RollbackException
	at org.infinispan.client.hotrod.RemoteCacheManager.<init>(RemoteCacheManager.java:171)
	at org.infinispan.client.hotrod.RemoteCacheManager.<init>(RemoteCacheManager.java:131)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.initialize(InfinispanClientProducer.java:68)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.remoteCacheManager(InfinispanClientProducer.java:314)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.create(Unknown Source)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.get(Unknown Source)
	at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.get(Unknown Source)
	at io.quarkus.it.infinispan.client.CacheSetup_Bean.create(Unknown Source)
	at io.quarkus.it.infinispan.client.CacheSetup_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
	at io.quarkus.it.infinispan.client.CacheSetup_Observer_onStart_a800524f28f3e6295575edd655cd3f1326e59216.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:323)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:305)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
```

I think we will need a Jakarta version of the Infinispan client. If it's only one artifact to adjust, it should be easy. It could be more painful if there is more.

I'll try to have a closer look and follow up.

**Comment by gsmet** [comment]
That being said I suppose you would need one for WildFly so I'm surprised you don't have something already.

**Comment by gsmet** [comment]
I see you have a `jakarta` jar for Infinispan 14 so that might fix the second problem. I'll make use of the 14.0.0.Dev04 version that is on Maven Central and see how it goes.
