### ISSUE TITLE
Dockerfile.multistage not working , gradlew build -Dquarkus.package.type=native throw Exception

### ISSUE THREAD

**Issue by seepine** [quarkusio/quarkus#27016]
## when use `quay.io/quarkus/ubi-quarkus-native-image:21.3-java11`
```shell
#17 89.50 2022-07-29T04:40:03.246+0000 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'com.fasterxml:oss-parent:43' in 'MavenRepo'
#17 89.50 2022-07-29T04:40:03.246+0000 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Using com.fasterxml:oss-parent:43 from Maven repository 'MavenRepo'
#17 89.50 2022-07-29T04:40:03.246+0000 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'oss-parent-43.pom (com.fasterxml:oss-parent:43)' in resolver cache: /root/.gradle/caches/modules-2/files-2.1/com.fasterxml/oss-parent/43/b07427a553422225d489ca19fd3fcdc38c02aa16/oss-parent-43.pom
#17 89.50 ----- End of the daemon log -----
#17 89.50 
#17 89.51 2022-07-29T04:40:04.348+0000 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
#17 89.51 2022-07-29T04:40:04.339+0000 [ERROR] [org.gradle.launcher.daemon.client.DaemonClient] JVM crash log found: file:///code/hs_err_pid78.log
#17 89.52 2022-07-29T04:40:04.369+0000 [LIFECYCLE] [org.gradle.launcher.cli.DebugLoggerWarningAction] 
#17 89.52 #############################################################################
#17 89.52    WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
#17 89.52 
#17 89.52    Debug level logging will leak security sensitive information!
#17 89.52 
#17 89.52    https://docs.gradle.org/7.4.2/userguide/logging.html#sec:debug_security
#17 89.52 #############################################################################
#17 89.52 
#17 89.65 2022-07-29T04:40:04.474+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 89.65 2022-07-29T04:40:04.479+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
#17 89.65 2022-07-29T04:40:04.480+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 89.65 2022-07-29T04:40:04.480+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
#17 89.65 2022-07-29T04:40:04.480+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
#17 89.65 2022-07-29T04:40:04.480+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 89.66 2022-07-29T04:40:04.481+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
#17 89.66 2022-07-29T04:40:04.481+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --scan to get full insights.
#17 89.66 2022-07-29T04:40:04.481+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 89.66 2022-07-29T04:40:04.481+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
#17 89.66 2022-07-29T04:40:04.482+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
#17 89.66 2022-07-29T04:40:04.482+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.daemon.client.DaemonClient.handleDaemonDisappearance(DaemonClient.java:269)
#17 89.66 2022-07-29T04:40:04.482+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:242)
#17 89.66 2022-07-29T04:40:04.482+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:204)
#17 89.66 2022-07-29T04:40:04.483+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:167)
#17 89.66 2022-07-29T04:40:04.483+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:99)
#17 89.66 2022-07-29T04:40:04.483+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
#17 89.66 2022-07-29T04:40:04.483+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:210)
#17 89.66 2022-07-29T04:40:04.484+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:275)
#17 89.66 2022-07-29T04:40:04.486+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:247)
#17 89.66 2022-07-29T04:40:04.486+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:82)
#17 89.66 2022-07-29T04:40:04.486+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
#17 89.66 2022-07-29T04:40:04.486+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:92)
#17 89.66 2022-07-29T04:40:04.486+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:38)
#17 89.66 2022-07-29T04:40:04.487+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
#17 89.66 2022-07-29T04:40:04.487+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
#17 89.66 2022-07-29T04:40:04.488+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
#17 89.66 2022-07-29T04:40:04.488+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
#17 89.66 2022-07-29T04:40:04.489+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
#17 89.66 2022-07-29T04:40:04.489+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.Main.doAction(Main.java:35)
#17 89.66 2022-07-29T04:40:04.489+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
#17 89.66 2022-07-29T04:40:04.489+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#17 89.66 2022-07-29T04:40:04.497+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#17 89.66 2022-07-29T04:40:04.497+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#17 89.66 2022-07-29T04:40:04.497+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#17 89.66 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
#17 89.66 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
#17 89.67 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#17 89.67 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#17 89.67 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#17 89.67 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#17 89.67 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.launcher.GradleMain.main(GradleMain.java:34)
#17 89.67 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#17 89.67 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#17 89.67 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#17 89.67 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#17 89.67 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
#17 89.67 2022-07-29T04:40:04.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
#17 89.67 2022-07-29T04:40:04.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
#17 89.67 2022-07-29T04:40:04.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 89.67 2022-07-29T04:40:04.501+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 89.67 2022-07-29T04:40:04.501+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
------
executor failed running [/bin/sh -c ./gradlew build -Dquarkus.package.type=native --stacktrace --debug]: exit code: 1
```

## when use `quay.io/quarkus/ubi-quarkus-native-image:22.0.0-java17`
```
#17 36.75 2022-07-29T04:42:44.985+0000 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Executing build 2c39175d-e442-4290-958f-95abd43552c5 in daemon client {pid=1}
#17 36.75 2022-07-29T04:42:45.008+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface eth0
#17 36.75 2022-07-29T04:42:45.008+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? false
#17 36.75 2022-07-29T04:42:45.009+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /172.17.0.2
#17 36.76 2022-07-29T04:42:45.009+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface lo
#17 36.76 2022-07-29T04:42:45.009+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? true
#17 36.76 2022-07-29T04:42:45.009+0000 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /127.0.0.1
#17 36.85 2022-07-29T04:42:45.072+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
#17 36.86 2022-07-29T04:42:45.121+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
#17 36.87 2022-07-29T04:42:45.139+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
#17 36.95 2022-07-29T04:42:45.159+0000 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Getting daemon stop events
#17 36.95 2022-07-29T04:42:45.199+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
#17 36.95 2022-07-29T04:42:45.199+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
#17 36.95 2022-07-29T04:42:45.199+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
#17 36.95 2022-07-29T04:42:45.214+0000 [INFO] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Removing 0 daemon stop events from registry
#17 36.95 2022-07-29T04:42:45.225+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
#17 36.95 2022-07-29T04:42:45.239+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
#17 36.96 2022-07-29T04:42:45.239+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
#17 36.96 2022-07-29T04:42:45.242+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
#17 36.96 2022-07-29T04:42:45.244+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
#17 37.05 2022-07-29T04:42:45.265+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
#17 37.06 2022-07-29T04:42:45.276+0000 [LIFECYCLE] [org.gradle.launcher.daemon.client.DefaultDaemonConnector] Starting a Gradle Daemon (subsequent builds will be faster)
#17 37.25 2022-07-29T04:42:45.504+0000 [DEBUG] [org.gradle.launcher.daemon.client.DefaultDaemonStarter] Using daemon args: [/opt/graalvm/bin/java, --add-opens, java.base/java.util=ALL-UNNAMED, --add-opens, java.base/java.lang=ALL-UNNAMED, --add-opens, java.base/java.lang.invoke=ALL-UNNAMED, --add-opens, java.base/java.util=ALL-UNNAMED, --add-opens, java.prefs/java.util.prefs=ALL-UNNAMED, --add-opens, java.prefs/java.util.prefs=ALL-UNNAMED, --add-opens, java.base/java.nio.charset=ALL-UNNAMED, --add-opens, java.base/java.net=ALL-UNNAMED, --add-opens, java.base/java.util.concurrent.atomic=ALL-UNNAMED, -XX:MaxMetaspaceSize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Xms256m, -Xmx512m, -Dfile.encoding=UTF-8, -Duser.country=US, -Duser.language=en, -Duser.variant, -cp, /root/.gradle/wrapper/dists/gradle-7.4.2-bin/dgcfplbio1xt3j7nlr9pdbagu/gradle-7.4.2/lib/gradle-launcher-7.4.2.jar]
#17 37.25 2022-07-29T04:42:45.530+0000 [DEBUG] [org.gradle.launcher.daemon.client.DefaultDaemonStarter] Starting daemon process: workingDir = /root/.gradle/daemon/7.4.2, daemonArgs: [/opt/graalvm/bin/java, --add-opens, java.base/java.util=ALL-UNNAMED, --add-opens, java.base/java.lang=ALL-UNNAMED, --add-opens, java.base/java.lang.invoke=ALL-UNNAMED, --add-opens, java.base/java.util=ALL-UNNAMED, --add-opens, java.prefs/java.util.prefs=ALL-UNNAMED, --add-opens, java.prefs/java.util.prefs=ALL-UNNAMED, --add-opens, java.base/java.nio.charset=ALL-UNNAMED, --add-opens, java.base/java.net=ALL-UNNAMED, --add-opens, java.base/java.util.concurrent.atomic=ALL-UNNAMED, -XX:MaxMetaspaceSize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Xms256m, -Xmx512m, -Dfile.encoding=UTF-8, -Duser.country=US, -Duser.language=en, -Duser.variant, -cp, /root/.gradle/wrapper/dists/gradle-7.4.2-bin/dgcfplbio1xt3j7nlr9pdbagu/gradle-7.4.2/lib/gradle-launcher-7.4.2.jar, org.gradle.launcher.daemon.bootstrap.GradleDaemon, 7.4.2]
#17 37.35 2022-07-29T04:42:45.618+0000 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'Gradle build daemon'. Working directory: /root/.gradle/daemon/7.4.2 Command: /opt/graalvm/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /root/.gradle/wrapper/dists/gradle-7.4.2-bin/dgcfplbio1xt3j7nlr9pdbagu/gradle-7.4.2/lib/gradle-launcher-7.4.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.4.2
#17 37.35 2022-07-29T04:42:45.618+0000 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
#17 37.35 2022-07-29T04:42:45.625+0000 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: Gradle build daemon.
#17 37.39 2022-07-29T04:42:45.674+0000 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
#17 37.39 2022-07-29T04:42:45.676+0000 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'Gradle build daemon' finished with exit value -1 (state: FAILED)
#17 37.39 2022-07-29T04:42:45.687+0000 [INFO] [org.gradle.launcher.daemon.client.DefaultDaemonStarter] An attempt to start the daemon took 0.152 secs.
#17 37.39 2022-07-29T04:42:45.692+0000 [LIFECYCLE] [org.gradle.launcher.cli.DebugLoggerWarningAction] 
#17 37.39 #############################################################################
#17 37.39    WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
#17 37.39 
#17 37.39    Debug level logging will leak security sensitive information!
#17 37.39 
#17 37.39    https://docs.gradle.org/7.4.2/userguide/logging.html#sec:debug_security
#17 37.39 #############################################################################
#17 37.40 
#17 37.44 2022-07-29T04:42:45.732+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 37.44 2022-07-29T04:42:45.733+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
#17 37.44 2022-07-29T04:42:45.733+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 37.44 2022-07-29T04:42:45.733+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
#17 37.44 2022-07-29T04:42:45.733+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred starting process 'Gradle build daemon'
#17 37.44 2022-07-29T04:42:45.733+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 37.44 2022-07-29T04:42:45.733+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
#17 37.44 2022-07-29T04:42:45.733+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --scan to get full insights.
#17 37.45 2022-07-29T04:42:45.734+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 37.45 2022-07-29T04:42:45.734+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
#17 37.45 2022-07-29T04:42:45.734+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.process.internal.ExecException: A problem occurred starting process 'Gradle build daemon'
#17 37.45 2022-07-29T04:42:45.734+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
#17 37.45 2022-07-29T04:42:45.734+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
#17 37.45 2022-07-29T04:42:45.735+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:369)
#17 37.45 2022-07-29T04:42:45.735+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
#17 37.45 2022-07-29T04:42:45.735+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:38)
#17 37.45 2022-07-29T04:42:45.735+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
#17 37.46 2022-07-29T04:42:45.736+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
#17 37.46 2022-07-29T04:42:45.736+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
#17 37.46 2022-07-29T04:42:45.736+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
#17 37.46 2022-07-29T04:42:45.736+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.lang.Thread.run(Thread.java:833)
#17 37.46 2022-07-29T04:42:45.737+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/opt/graalvm/bin/java'
#17 37.46 2022-07-29T04:42:45.737+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
#17 37.46 2022-07-29T04:42:45.737+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
#17 37.46 2022-07-29T04:42:45.737+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
#17 37.47 2022-07-29T04:42:45.738+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
#17 37.47 2022-07-29T04:42:45.738+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         ... 6 more
#17 37.47 2022-07-29T04:42:45.738+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.IOException: Cannot run program "/opt/graalvm/bin/java" (in directory "/root/.gradle/daemon/7.4.2"): error=0, Failed to exec spawn helper: pid: 82, exit value: 1
#17 37.47 2022-07-29T04:42:45.738+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
#17 37.47 2022-07-29T04:42:45.738+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
#17 37.47 2022-07-29T04:42:45.739+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
#17 37.48 2022-07-29T04:42:45.739+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         ... 9 more
#17 37.48 2022-07-29T04:42:45.739+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 82, exit value: 1
#17 37.48 2022-07-29T04:42:45.739+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
#17 37.48 2022-07-29T04:42:45.739+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
#17 37.48 2022-07-29T04:42:45.739+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
#17 37.48 2022-07-29T04:42:45.740+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
#17 37.49 2022-07-29T04:42:45.740+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         ... 11 more
#17 37.49 2022-07-29T04:42:45.740+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 37.49 2022-07-29T04:42:45.740+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
#17 37.49 2022-07-29T04:42:45.741+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
------
executor failed running [/bin/sh -c ./gradlew build -Dquarkus.package.type=native --stacktrace --debug]: exit code: 1
```

### Expected behavior

build docker image success

### Actual behavior

can not build image

### How to Reproduce?

1. create new project with example code
2. add `Dockerfile.multistage` at `src/main/docker`
3. run `docker build -f src/main/docker/Dockerfile.multistage -t quarkus-quickstart/getting-started .`

Dockerfile.multistage
```dockerfile
## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/ubi-quarkus-native-image:22.0.0-java17 AS build
USER root
RUN microdnf install findutils
COPY --chown=quarkus:quarkus gradlew /code/gradlew
COPY --chown=quarkus:quarkus gradle /code/gradle
COPY --chown=quarkus:quarkus build.gradle /code/
COPY --chown=quarkus:quarkus settings.gradle /code/
COPY --chown=quarkus:quarkus gradle.properties /code/
WORKDIR /code
COPY src /code/src
RUN ./gradlew build -Dquarkus.package.type=native --stacktrace --debug

## Stage 2 : create the docker final image
FROM quay.io/quarkus/quarkus-micro-image:1.0
WORKDIR /work/
COPY --from=build /code/build/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]

```

### Output of `uname -a` or `ver`

Darwin Mac-mini.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

### Output of `java -version`

openjdk version "17.0.4" , Zulu17.36+13-CA

### Quarkus version or git rev

2.11.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.4.2

### Additional information

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.4 (Azul Systems, Inc. 17.0.4+8-LTS)
OS:           Mac OS X 12.0.1 aarch64

**Comment by geoand** [comment]
Thanks for reporting.

I am going to close this as it does not look like a Quarkus issue.
