### ISSUE TITLE
H2 is not available in native

### ISSUE THREAD

**Issue by TheBlindM** [quarkusio/quarkus#27021]
### Describe the bug

quarkus.datasource.jdbc.url=jdbc:h2:~/TShell/ShellDB2  not in memory mode

`2022-07-29 15:51:12,715 DEBUG [io.agr.pool] (agroal-11) Cause: : org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.UnsupportedOperationException: H2 database compiled into a native-image is only functional as a client: can't create an Embedded Database Session" [50000-210]
        at org.h2.message.TraceObject.logAndConvert(TraceObject.java:365)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:135)
        at org.h2.Driver.connect(Driver.java:59)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
        at com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:143)
Caused by: java.lang.UnsupportedOperationException: H2 database compiled into a native-image is only functional as a client: can't create an Embedded Database Session
        at org.h2.engine.ConnectionInfo.isRemote(ConnectionInfo.java:20)
        at org.h2.engine.ConnectionInfo.preservePasswordForAuthentication(ConnectionInfo.java:353)
        at org.h2.engine.ConnectionInfo.removePassword(ConnectionInfo.java:360)
        at org.h2.engine.ConnectionInfo.convertPasswords(ConnectionInfo.java:375)
        at org.h2.engine.ConnectionInfo.<init>(ConnectionInfo.java:105)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:113)
        ... 11 more`

### Output of `java -version`

17

### GraalVM version (if different from Java)

21

### Quarkus version or git rev

2.10.3

**Comment by mkouba** [comment]
I think that this is not supported at the moment, i.e. you can only connect to a remote H2 instance.

CC @gsmet

**Comment by gsmet** [comment]
Exactly. And I don't think we will support it anytime soon.

**Comment by gsmet** [comment]
You can use a Dev Service https://quarkus.io/guides/databases-dev-services or a test resource to start a H2 server for tests.
