### ISSUE TITLE
Avro class cannot be deserialized in multi module setup in tests annotated with @QuarkusTest

### ISSUE THREAD

**Issue by GertjanHouwen** [quarkusio/quarkus#27057]
### Describe the bug

Setup: A parent module has two child modules: A and B. In module A an avro schema is present and quarkus generates a class for that schema in /target/generated-sources. Module B is dependent on module A. 

Problem: In module B, a test annotated with @QuarkusTest fails to deserialize that avro class and throws a class cast exception, even though the same test without the annotation does not.

### Expected behavior

@QuarkusTest should not cause the deserializer to throw a class cast exception.

### Actual behavior

Deserializing an avro class results in this class cast exception: 

java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.ClassCastException: org.acme.kafka.quarkus.Movie incompatible with org.apache.avro.generic.IndexedRecord

### How to Reproduce?

Steps to reproduce:

1. clone this repo git clone https://github.com/GertjanHouwen/quarkus-bug.git
2. Run mvn clean install in parent module.

Extra information:
(3. mvn quarkus:dev in nested-module2 shows that it is really problem with the annotation as the deserializer in Tester.class completes succesfully).

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19042.1826] (problem also tested on mac)

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

2.11.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

### Additional information

KafkaAvroDeserializer is not used in this git test project, but it has the same problem.

**Comment by GertjanHouwen** [comment]
What is the status of this bug report?

**Comment by guitcastro** [comment]
I am having the same problem

**Comment by gsmet** [comment]
This is still an issue with Quarkus 3.13.3:

```
Caused by: java.lang.ClassCastException: class org.acme.kafka.quarkus.Movie cannot be cast to class org.apache.avro.generic.IndexedRecord (org.acme.kafka.quarkus.Movie is in unnamed module of loader 'app'; org.apache.avro.generic.IndexedRecord is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @57f9b467)
	at org.apache.avro.generic.GenericData.setField(GenericData.java:851)
	at org.apache.avro.generic.GenericData.setField(GenericData.java:874)
	at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:260)
	at org.apache.avro.specific.SpecificDatumReader.readField(SpecificDatumReader.java:142)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:248)
	at org.apache.avro.specific.SpecificDatumReader.readRecord(SpecificDatumReader.java:123)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:180)
```

@aloubyansky `org.acme.kafka.quarkus.Movie` is a class generated by a `CodeGenProvider`. I'm surprised it ends up in the app class loader? I would have expected these classes to be loaded by the `QuarkusClassLoader`.

Am I missing something?

**Comment by aloubyansky** [comment]
It may depend on how Avro loads its classes. For example, there could be a call to Avro to process something that loads a service from the app classloader, and that one returns instances of types loaded by the app classloader to higher layers.

**Comment by cescoffier** [comment]
I guess it's related to a test classloader issue. @holly-cummins is doing good progress on this.

**Comment by holly-cummins** [comment]
See (disabled) reproducer added in https://github.com/quarkusio/quarkus/pull/45416

**Comment by holly-cummins** [comment]
I confirm this is still failing, even after the test classloading rewrite. The exception is the same, too:

```
Caused by: java.lang.ClassCastException: class org.acme.kafka.quarkus.Movie cannot be cast to class org.apache.avro.generic.IndexedRecord (org.acme.kafka.quarkus.Movie is in unnamed module of loader 'app'; org.apache.avro.generic.IndexedRecord is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @47f9738)
	at org.apache.avro.generic.GenericData.setField(GenericData.java:851)
	at org.apache.avro.generic.GenericData.setField(GenericData.java:874)
	at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:260)
	at org.apache.avro.specific.SpecificDatumReader.readField(SpecificDatumReader.java:142)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:248)
	at org.apache.avro.specific.SpecificDatumReader.readRecord(SpecificDatumReader.java:123)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:180)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:161)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:154)
	at org.apache.avro.file.DataFileStream.next(DataFileStream.java:263)
	at org.apache.avro.file.DataFileStream.next(DataFileStream.java:248)
	at org.acme.kafka.MovieSerializer.deserialize(MovieSerializer.java:36)
```

Looking at it more closely, the problem path is all on the 'application' side, and the application gets loaded with the runtime classloader both with and without the test changes. So I was just about to declare that this had nothing to do with the test framework, but I tried adding a rest endpoint to `MovieResource` in module2, and ... it works fine. 

<img width="1104" alt="Image" src="https://github.com/user-attachments/assets/eea24977-ddfe-43bb-8925-0d470e7b6889" />

And if I create a `HelloResourceTest` to hit the endpoint using `RestAssured`, that test fails with the same exception. 

I wonder if it could be something to do with the `test` application, rather than anything more specifically about test loading and invocation?
