### ISSUE TITLE
Jakarta - EE 9 - Native - Yasson MethodHandles issue

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#27064]
Anything that uses Yasson ends up with:
```
[INFO] Running io.quarkus.it.mongodb.NativeVehicleResourceIT
2022-08-01 16:58:32,056 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /vehicles failed, error id: 2d6330af-623e-48d7-98eb-7a0fedd7ef74-1: java.lang.InternalError: java.lang.NoSuchMethodException: no such method: jdk.internal.misc.Unsafe.putReference(Object,long,Object)void/invokeVirtual
	at java.lang.invoke.MethodHandleStatics.newInternalError(MethodHandleStatics.java:155)
	at java.lang.invoke.DirectMethodHandle.makePreparedFieldLambdaForm(DirectMethodHandle.java:778)
	at java.lang.invoke.DirectMethodHandle.preparedFieldLambdaForm(DirectMethodHandle.java:692)
	at java.lang.invoke.DirectMethodHandle.preparedFieldLambdaForm(DirectMethodHandle.java:680)
	at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:113)
	at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:129)
	at java.lang.invoke.MethodHandles$Lookup.getDirectFieldCommon(MethodHandles.java:4049)
	at java.lang.invoke.MethodHandles$Lookup.getDirectFieldNoSecurityManager(MethodHandles.java:4040)
	at java.lang.invoke.MethodHandles$Lookup.unreflectField(MethodHandles.java:3504)
	at java.lang.invoke.MethodHandles$Lookup.unreflectSetter(MethodHandles.java:3487)
	at org.eclipse.yasson.internal.model.PropertyModel.createWriteHandle(PropertyModel.java:571)
	at org.eclipse.yasson.internal.model.PropertyModel.<init>(PropertyModel.java:168)
	at org.eclipse.yasson.internal.ClassParser.lambda$parseProperties$0(ClassParser.java:70)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.eclipse.yasson.internal.ClassParser.parseProperties(ClassParser.java:71)
	at org.eclipse.yasson.internal.MappingContext.lambda$createParseClassModelFunction$1(MappingContext.java:97)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:81)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:60)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:51)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:59)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:99)
	at org.jboss.resteasy.reactive.server.jsonb.JsonbMessageBodyReader.doReadFrom(JsonbMessageBodyReader.java:55)
	at org.jboss.resteasy.reactive.server.jsonb.JsonbMessageBodyReader.readFrom(JsonbMessageBodyReader.java:37)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:108)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:67)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:102)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:557)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: java.lang.NoSuchMethodException: no such method: jdk.internal.misc.Unsafe.putReference(Object,long,Object)void/invokeVirtual
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:976)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
	at java.lang.invoke.DirectMethodHandle.makePreparedFieldLambdaForm(DirectMethodHandle.java:775)
	... 41 more
Caused by: java.lang.NoSuchMethodError: jdk.internal.misc.Unsafe.putReference(java.lang.Object, long, java.lang.Object)
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:345)
	at java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:223)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
	... 42 more
```

The new version is using MethodHandles and apparently GraalVM doesn't like it at all. This is with GraalVM 22.2 Java 17.

This breaks:
- `integration-tests/mongodb-client` - `io.quarkus.it.mongodb.NativeVehicleResourceIT.testVehicleEndpoint`
- `integration-tests/main` - `RestClientITCase>RestClientTestCase.testIssue8795`

**Comment by gsmet** [comment]
@galderz so here is how to reproduce the issue:

- build the `jakarta-rewrite` branch, see instructions here: https://github.com/quarkusio/quarkus/tree/main/jakarta#build-locally (just this small paragraph, nothing else is needed)
- `cd integration-tests/mongodb-client`
- `mvn clean install -Dnative`
- `io.quarkus.it.mongodb.NativeVehicleResourceIT.testVehicleEndpoint` should fail with an error in the MethodHandle handling code

After adding the reflection for `putReference` (it's already in the tree you will build), the error is:

```
Caused by: java.lang.NullPointerException
    at sun.invoke.util.VerifyAccess.isSamePackage(VerifyAccess.java:376)
    at sun.invoke.util.VerifyAccess.isClassAccessible(VerifyAccess.java:195)
    at sun.invoke.util.VerifyAccess.isMemberAccessible(VerifyAccess.java:104)
    ... 47 more
```

still triggered by the same `org.eclipse.yasson.internal.model.PropertyModel.createWriteHandle(PropertyModel.java:571)` call.

**Comment by galderz** [comment]
There's something to fix in oracle/graal, see https://github.com/oracle/graal/issues/4794

**Comment by galderz** [comment]
A very simple workaround is to add setters for the fields, e.g.

```java
package io.quarkus.it.mongodb.discriminator;

import org.bson.codecs.pojo.annotations.BsonDiscriminator;

@BsonDiscriminator(key = "type")
public abstract class Vehicle {
    public String type;
    public String name;

    public void setType(String type) {
        this.type = type;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```

**Comment by gsmet** [comment]
Thanks a lot for the help on this @galderz . I will implement the workaround and close this as it needs to be tracked upstream.
