### ISSUE TITLE
Building thin JAR on Windows sometimes leads to file access race

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#27061]
### Describe the bug

We use `QuarkusBootstrap.Builder` to build app artifact manually here https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdQuarkusApplicationManagedResourceBuilder.java#L149 and since `2022/06/29`, our daily CI sometimes fails with the following exception:

```posh
2022-07-29T23:51:27.0147089Z 23:51:26,971 INFO  Building native image source jar: target\GreetingResourceIT\blocking\blocking-native-image-source-jar\blocking-runner.jar
...
2022-07-29T23:51:28.5118448Z 	[error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.nio.file.FileSystemException: target\GreetingResourceIT\blocking\blocking-native-image-source-jar\lib\io.quarkus.quarkus-resteasy-999-SNAPSHOT.jar: The process cannot access the file because it is being used by another process.
2022-07-29T23:51:28.5126913Z 
2022-07-29T23:51:28.5127517Z 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:990)
2022-07-29T23:51:28.5128090Z 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
2022-07-29T23:51:28.5132612Z 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
2022-07-29T23:51:28.5133571Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2022-07-29T23:51:28.5135416Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2022-07-29T23:51:28.5135939Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-07-29T23:51:28.5136417Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
2022-07-29T23:51:28.5149949Z Caused by: java.nio.file.FileSystemException: target\GreetingResourceIT\blocking\blocking-native-image-source-jar\lib\io.quarkus.quarkus-resteasy-999-SNAPSHOT.jar: The process cannot access the file because it is being used by another process.
2022-07-29T23:51:28.5150642Z 
2022-07-29T23:51:28.5150998Z 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
2022-07-29T23:51:28.5152363Z 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
2022-07-29T23:51:28.5163358Z 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
2022-07-29T23:51:28.5165097Z 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
2022-07-29T23:51:28.5165771Z 	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
2022-07-29T23:51:28.5166252Z 	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
2022-07-29T23:51:28.5166873Z 	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
2022-07-29T23:51:28.5220898Z 	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
2022-07-29T23:51:28.5221724Z 	at java.base/java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:125)
2022-07-29T23:51:28.5222265Z 	at java.base/java.nio.file.Files.copy(Files.java:1298)
2022-07-29T23:51:28.5222877Z 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep$8.visitPath(JarResultBuildStep.java:1326)
2022-07-29T23:51:28.5229567Z 	at io.quarkus.paths.PathTreeVisit.walk(PathTreeVisit.java:26)
2022-07-29T23:51:28.5230353Z 	at io.quarkus.paths.DirectoryPathTree.walk(DirectoryPathTree.java:89)
2022-07-29T23:51:28.5231029Z 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.lambda$copyFiles$13(JarResultBuildStep.java:1299)
2022-07-29T23:51:28.5231939Z 	at io.quarkus.deployment.ApplicationArchiveImpl.accept(ApplicationArchiveImpl.java:103)
2022-07-29T23:51:28.5232707Z 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.copyFiles(JarResultBuildStep.java:1298)
2022-07-29T23:51:28.5237699Z 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:671)
2022-07-29T23:51:28.5238537Z 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:218)
2022-07-29T23:51:28.5239296Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-29T23:51:28.5247913Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-07-29T23:51:28.5248743Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-07-29T23:51:28.5249421Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-07-29T23:51:28.5249979Z 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:981)
2022-07-29T23:51:28.5254533Z 	... 6 more
...
```

The first time failed on Jun 29 in 1h 11m 30s. The issue only happens the Windows in the native mode.
The exception is thrown by the `Files.copy` here https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java#L1326. Previous changes to the file seems unrelated to me.

This issue started after Quarkus stopped to force uber-jar on OS WIndows (the PR from 22.6) https://github.com/quarkusio/quarkus/pull/26289 You can see in the logs above `Building native image source jar` that prooves we are building thin jar now. Prior to the PR, `WARN  Uber JAR strategy is used for native image source JAR generation on Windows. This is done for the time being to work around a current GraalVM limitation on Windows concerning the maximum command length (see https://github.com/oracle/graal/issues/2387).` had been logged.

### Expected behavior

No exception is thrown.

### Actual behavior

The exception is sometimes thrown.

### How to Reproduce?

Reproducer:

1.git clone https://github.com/michalvavrik/quarkus-test-framework/tree/quarkus-issue-27061-win-native-bloc-reactive-repro
2. mvn clean install -DskipITs -DskipTests
3. cd examples/blocking-reactive-model/
4. mvn clean verify -Dnative -Dquarkus.platform.version=999-SNAPSHOT

I absolutely understand that reproducer is insufficient, but maybe you could have a look at our daily CI runs were failure is logged https://github.com/quarkus-qe/quarkus-test-framework/actions/workflows/daily.yaml (see `Daily - Windows - Native build - Latest Version (11, 999-SNAPSHOT, 22.1.0.java11)`).

### Output of `uname -a` or `ver`

Microsoft Windows Server 2022

### Output of `java -version`

Java Version 11.0.13+7-jvmci-21.3-b05

### GraalVM version (if different from Java)

GraalVM 21.3.0

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by michalvavrik** [comment]
cc @Sanne @aloubyansky

**Comment by geoand** [comment]
cc @galderz @zakkak

**Comment by geoand** [comment]
I think it would be really helpful if we knew which other process is using the file - I personally have no idea how to find that information in Windows though...

**Comment by michalvavrik** [comment]
I'll try to do that, but I'm not sure about ETA - it's not trivial (considering the issue itself is not easy to reproduce).

**Comment by geoand** [comment]
Completely understood.

**Comment by aloubyansky** [comment]
@michalvavrik afaiu, it is saying the target path of `Files.copy(...)` is used by another process, although the previous line checked that the file did not exist?

**Comment by michalvavrik** [comment]
@aloubyansky right before it's checking whether `target` exists, but the way I read stack trace it says `visit.getPath()` is used by another process:
1. `Files.copy`-> `source` = `visit.getPath()` 
2.  `CopyMoveHelper.copyToForeignTarget` (source is still source)
3.  line 125 tries to open IS from source `try (InputStream in = Files.newInputStream(source)) {`

**Comment by aloubyansky** [comment]
@michalvavrik just to clarify, it doesn't fail on every run?

**Comment by michalvavrik** [comment]
No, we run test suite that includes this every day and it fails every couple days, sometimes twice in a row, sometimes not for a week. And the same tests are running win/linux native/jvm, only win in native is failling.

**Comment by zakkak** [comment]
@Karm have you ever seen this before?

**Comment by Karm** [comment]
I have not, but I tackled similar issues elsewhere in the past.

The tool for the job is Process Explorer from Systinternals: https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by geoand** [comment]
Is this still an issue?

**Comment by michalvavrik** [comment]
I completely forgot about it. I'll enable tests again and we will see. Let's keep it open for a week or so.

**Comment by geoand** [comment]
👌

**Comment by michalvavrik** [comment]
As we don't use Windows outside of CI, it's bit hard for me to use suggested GUI Process Explorer from Systinternals for debugging and supply required information.

Anyway, today we experienced the problem again in different test on Windows again, please see https://github.com/quarkus-qe/quarkus-test-framework/actions/runs/4672803913/jobs/8275578816

```
2023-04-12T00:44:33.2360399Z Failed to build Quarkus artifacts. Caused by java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2023-04-12T00:44:33.2369004Z 	[error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.nio.file.FileSystemException: target\LocalIT\unmanaged\unmanaged-native-image-source-jar\lib\io.quarkus.quarkus-vertx-http-999-SNAPSHOT.jar: The process cannot access the file because it is being used by another process
2023-04-12T00:44:33.2372252Z 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
2023-04-12T00:44:33.2372794Z 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
2023-04-12T00:44:33.2373237Z 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
2023-04-12T00:44:33.2373778Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2023-04-12T00:44:33.2378190Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2023-04-12T00:44:33.2378697Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-12T00:44:33.2379114Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
2023-04-12T00:44:33.2380094Z Caused by: java.nio.file.FileSystemException: target\LocalIT\unmanaged\unmanaged-native-image-source-jar\lib\io.quarkus.quarkus-vertx-http-999-SNAPSHOT.jar: The process cannot access the file because it is being used by another process
2023-04-12T00:44:33.2380917Z 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
2023-04-12T00:44:33.2394647Z 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
2023-04-12T00:44:33.2395251Z 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
2023-04-12T00:44:33.2395825Z 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
2023-04-12T00:44:33.2396376Z 	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
2023-04-12T00:44:33.2399068Z 	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
2023-04-12T00:44:33.2399610Z 	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
2023-04-12T00:44:33.2400121Z 	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
2023-04-12T00:44:33.2400645Z 	at java.base/java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:125)
2023-04-12T00:44:33.2401153Z 	at java.base/java.nio.file.Files.copy(Files.java:1308)
2023-04-12T00:44:33.2403874Z 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep$8.visitPath(JarResultBuildStep.java:1359)
2023-04-12T00:44:33.2404406Z 	at io.quarkus.paths.PathTreeVisit.walk(PathTreeVisit.java:25)
2023-04-12T00:44:33.2404905Z 	at io.quarkus.paths.DirectoryPathTree.walk(DirectoryPathTree.java:89)
2023-04-12T00:44:33.2405491Z 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.lambda$copyFiles$14(JarResultBuildStep.java:1332)
2023-04-12T00:44:33.2408468Z 	at io.quarkus.deployment.ApplicationArchiveImpl.accept(ApplicationArchiveImpl.java:103)
2023-04-12T00:44:33.2409113Z 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.copyFiles(JarResultBuildStep.java:1331)
2023-04-12T00:44:33.2409751Z 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:682)
2023-04-12T00:44:33.2410452Z 	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:222)
2023-04-12T00:44:33.2413396Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-04-12T00:44:33.2414020Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-04-12T00:44:33.2414668Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-04-12T00:44:33.2415234Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-04-12T00:44:33.2415728Z 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
2023-04-12T00:44:33.2418435Z 	... 6 more
```

**Comment by Karm** [comment]
@michalvavrik 

> As we don't use Windows outside of CI, it's bit hard for me to use
> suggested GUI Process Explorer from Systinternals for debugging and supply required information.

Then don't and use a cli tool of the same origin:  https://download.sysinternals.com/files/Handle.zip

I use it in Windows debugging all the time, it's just the thing for the job.

**Comment by michalvavrik** [comment]
@Karm shall to, thank you for the tip

**Comment by michalvavrik** [comment]
still an issue https://github.com/quarkus-qe/quarkus-test-framework/actions/runs/6054753310, while I completely forgot about this issue. I'll try to gather info in upcoming weeks as we discussed.

**Comment by aloubyansky** [comment]
Haven't really investigated whether that could be a problem but looking at the test creating two Quarkus apps and the fact that it fails on
```
io.quarkus.test.services.quarkus.ProdQuarkusApplicationManagedResourceBuilder.tryToReuseOrBuildArtifact
```
Is it possible that the apps are being built/used at the same time sharing common JARs in the lib?

**Comment by mocenas** [comment]
Encountered the same issue in quarkus tests: https://github.com/quarkus-qe/quarkus-test-framework/actions/runs/6139978440/job/16658707740 . Stack trace:
`
 Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.nio.file.FileSystemException: target\BuildTimeGreetingResourceIT\app\app-native-image-source-jar\lib\io.quarkus.quarkus-vertx-http-999-SNAPSHOT.jar: The process cannot access the file because it is being used by another process
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:867)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.FileSystemException: target\BuildTimeGreetingResourceIT\app\app-native-image-source-jar\lib\io.quarkus.quarkus-vertx-http-999-SNAPSHOT.jar: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at java.base/java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:125)
	at java.base/java.nio.file.Files.copy(Files.java:1308)
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep$8.visitPath(JarResultBuildStep.java:1361)
	at io.quarkus.paths.PathTreeVisit.walk(PathTreeVisit.java:25)
	at io.quarkus.paths.DirectoryPathTree.walk(DirectoryPathTree.java:89)
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.lambda$copyFiles$14(JarResultBuildStep.java:1334)
	at io.quarkus.deployment.ApplicationArchiveImpl.accept(ApplicationArchiveImpl.java:103)
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.copyFiles(JarResultBuildStep.java:1333)
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:683)
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:223)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
	... 6 more
`

**Comment by aloubyansky** [comment]
Perhaps you could try commenting out the `build` goal just to see whether it has any effect, given that you are re-building the app in the tests anyway.

**Comment by rsvoboda** [comment]
Build of the application is called using `AugmentAction#createProductionApplication` in https://github.com/quarkus-qe/quarkus-test-framework/blob/main/quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdQuarkusApplicationManagedResourceBuilder.java#L167

And it operates on top of new directory specific for the test (`target/BuildTimeGreetingResourceIT/app`)

**Comment by michalvavrik** [comment]
I've added some code that will help us to gather more information next time the build fail.

> Is it possible that the apps are being built/used at the same time sharing common JARs in the lib?

I was stepping the code today, I don't think it is. Also it failed on the very first build, which kinda excuse all possible races from our side on reusing JAR.

> Perhaps you could try commenting out the build goal just to see whether it has any effect, given that you are re-building the app in the tests anyway.

Done, but as mentioned by @rsvoboda the race happen in another service folder that Quarkus Maven plugin does not work with. It had no affect, failures continued.

**Comment by michalvavrik** [comment]
First results with open handles - https://github.com/quarkus-qe/quarkus-test-framework/actions/runs/6739211665/job/18320766989

Following process has open handle
```
'3992', is alive - 'true', command - 'C:\hostedtoolcache\windows\mandrel-java17-windows\23.0.1-2-Final\x64\mandrel-java17-23.0.1.2-Final\bin\java.exe', arguments - 'Optional.empty'
```

```
java.exe pid: 3992 fv-az270-339\runneradmin
4C: File  (RW-)   D:\a\quarkus-test-framework\quarkus-test-framework\examples\management
AC: File  (RW-)   C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.20348.1_none_88d3d41d702dedea
110: Section       \BaseNamedObjects\msys-2.0S5-1888ae32e00d56aa\S-1-5-21-178372129-2281020792-494459982-500.1
140: File  (RW-)   C:\hostedtoolcache\windows\mandrel-java17-windows\23.0.1-2-Final\x64\mandrel-java17-23.0.1.2-Final\lib\modules
16C: File  (R-D)   C:\Users\RUNNER~1\AppData\Local\Temp\hsperfdata_runneradmin\3992
170: Section       \Sessions\1\BaseNamedObjects\hsperfdata_runneradmin_3992
270: File  (R-D)   C:\Windows\System32\en-US\kernel32.dll.mui
314: File  (RWD)   D:\a\quarkus-test-framework\quarkus-test-framework
338: Section       \Sessions\1\BaseNamedObjects\windows_shell_global_counters
430: File  (RW-)   C:\Users\runneradmin\.m2\repository\org\apache\maven\surefire\surefire-booter\3.2.1\surefire-booter-3.2.1.jar
434: File  (RW-)   C:\Users\runneradmin\AppData\Local\Temp\surefire17980308602514035911\surefirebooter-20231103012216805_115.jar
438: File  (RW-)   C:\Users\runneradmin\.m2\repository\org\apache\maven\surefire\surefire-logger-api\3.2.1\surefire-logger-api-3.2.1.jar
43C: File  (RW-)   C:\Users\runneradmin\.m2\repository\org\apache\maven\surefire\surefire-api\3.2.1\surefire-api-3.2.1.jar
440: File  (RW-)   C:\Users\runneradmin\.m2\repository\org\apache\maven\surefire\surefire-shared-utils\3.2.1\surefire-shared-utils-3.2.1.jar
444: File  (RW-)   D:\a\quarkus-test-framework\quarkus-test-framework\examples\management\target\examples-management-1.3.1.Beta30-SNAPSHOT.jar
448: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\quarkus-resteasy\999-SNAPSHOT\quarkus-resteasy-999-SNAPSHOT.jar
44C: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\quarkus-security-runtime-spi\999-SNAPSHOT\quarkus-security-runtime-spi-999-SNAPSHOT.jar
450: File  (RW-)   C:\Users\runneradmin\.m2\repository\org\apache\maven\surefire\surefire-extensions-spi\3.2.1\surefire-extensions-spi-3.2.1.jar
454: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\quarkus-vertx-http\999-SNAPSHOT\quarkus-vertx-http-999-SNAPSHOT.jar
458: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\quarkus-credentials\999-SNAPSHOT\quarkus-credentials-999-SNAPSHOT.jar
45C: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\arc\arc\999-SNAPSHOT\arc-999-SNAPSHOT.jar
460: File  (RW-)   C:\Users\runneradmin\.m2\repository\jakarta\transaction\jakarta.transaction-api\2.0.1\jakarta.transaction-api-2.0.1.jar
464: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\quarkus-mutiny\999-SNAPSHOT\quarkus-mutiny-999-SNAPSHOT.jar
468: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\smallrye\reactive\mutiny\2.5.1\mutiny-2.5.1.jar
46C: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\quarkus-smallrye-context-propagation\999-SNAPSHOT\quarkus-smallrye-context-propagation-999-SNAPSHOT.jar
470: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\smallrye\smallrye-context-propagation\2.1.0\smallrye-context-propagation-2.1.0.jar
474: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\smallrye\smallrye-context-propagation-api\2.1.0\smallrye-context-propagation-api-2.1.0.jar
478: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\smallrye\smallrye-context-propagation-storage\2.1.0\smallrye-context-propagation-storage-2.1.0.jar
47C: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\smallrye\reactive\mutiny-smallrye-context-propagation\2.5.1\mutiny-smallrye-context-propagation-2.5.1.jar
480: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\smallrye\common\smallrye-common-vertx-context\2.1.2\smallrye-common-vertx-context-2.1.2.jar
484: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\smallrye\common\smallrye-common-constraint\2.1.2\smallrye-common-constraint-2.1.2.jar
488: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\security\quarkus-security\2.0.2.Final\quarkus-security-2.0.2.Final.jar
48C: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\quarkus-vertx\999-SNAPSHOT\quarkus-vertx-999-SNAPSHOT.jar
490: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\quarkus-netty\999-SNAPSHOT\quarkus-netty-999-SNAPSHOT.jar
494: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\netty\netty-codec\4.1.100.Final\netty-codec-4.1.100.Final.jar
498: File  (RW-)   C:\Users\runneradmin\.m2\repository\com\aayushatharva\brotli4j\brotli4j\1.12.0\brotli4j-1.12.0.jar
49C: File  (RW-)   C:\Users\runneradmin\.m2\repository\com\aayushatharva\brotli4j\service\1.12.0\service-1.12.0.jar
4A0: File  (RW-)   C:\Users\runneradmin\.m2\repository\com\aayushatharva\brotli4j\native-windows-x86_64\1.12.0\native-windows-x86_64-1.12.0.jar
4A4: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\netty\netty-codec-haproxy\4.1.100.Final\netty-codec-haproxy-4.1.100.Final.jar
4A8: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\smallrye\common\smallrye-common-annotation\2.1.2\smallrye-common-annotation-2.1.2.jar
4AC: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\quarkus-virtual-threads\999-SNAPSHOT\quarkus-virtual-threads-999-SNAPSHOT.jar
4B0: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\quarkus-vertx-latebound-mdc-provider\999-SNAPSHOT\quarkus-vertx-latebound-mdc-provider-999-SNAPSHOT.jar
4B4: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\smallrye\smallrye-fault-tolerance-vertx\6.2.6\smallrye-fault-tolerance-vertx-6.2.6.jar
4B8: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\smallrye\reactive\smallrye-mutiny-vertx-web\3.7.2\smallrye-mutiny-vertx-web-3.7.2.jar
4BC: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\smallrye\reactive\smallrye-mutiny-vertx-bridge-common\3.7.2\smallrye-mutiny-vertx-bridge-common-3.7.2.jar
4C0: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\vertx\vertx-web\4.4.6\vertx-web-4.4.6.jar
4C4: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\vertx\vertx-web-common\4.4.6\vertx-web-common-4.4.6.jar
4C8: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\vertx\vertx-auth-common\4.4.6\vertx-auth-common-4.4.6.jar
4CC: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\vertx\vertx-bridge-common\4.4.6\vertx-bridge-common-4.4.6.jar
4D0: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\github\crac\org-crac\0.1.3\org-crac-0.1.3.jar
4D4: File  (RW-)   C:\Users\runneradmin\.m2\repository\io\quarkus\quarkus-resteasy-server-common\999-SNAPSHOT\quarkus-resteasy-server-common-999-SNAPSHOT.jar
..
```

and 

```
'568', is alive - 'true', command - 'C:\hostedtoolcache\windows\mandrel-java17-windows\23.0.1-2-Final\x64\mandrel-java17-23.0.1.2-Final\bin\java.exe', arguments - 'Optional.empty'
```

holds lot of open handles similarly to the other one.

I no smarter from this, unless this is enough information for you @aloubyansky , I'll need to identify these processes with exact code blocks (I was thinking about applying patches on local Quarkus main before I built it and run it against it). The situation is difficult because I couldn't reproduce on spawned Windows instance in a week, you probably need extra slow instance like GH CI or I don't know because I run it hundreds and hundreds of times.

**Comment by michalvavrik** [comment]
I spent a day inspecting logs and Quarkus / Quarkus QE code and I'm absolutely sure now that:

- race only happens when bootstrap is not run by Quarkus plugin
- when `io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildNativeImageThinJar` is run, no Quarkus QE FW code is using folder that experience race
- when `io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildNativeImageThinJar` is run, no previously run Quarkus Maven plugin or Quarkus QE bootstrap holds any resources
  - How can I know? There are tests like `io.quarkus.qe.BuildTimeGreetingResourceIT` that is run as first and only test in the folder where race happens and nothing else uses parent folders etc.
- our bootstrap https://github.com/quarkus-qe/quarkus-test-framework/blob/a62d2b4feb274360bbde17b2c2938ef5df4a973c/quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdQuarkusApplicationManagedResourceBuilder.java#L168 looks almost identically to https://github.com/quarkusio/quarkus/blob/0741b563b60d26f2bc8067b886f07998420ba9ed/test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusProdModeTest.java#L430, one palpable difference is that our `targetDirectory` is same as `applicationRoot` while prod mode test has app root as `deploymentDir` and target dir a `buildDir` which I think can be different. However I read code and I can't see how does it matter.
- I can't know whether something like that never happens when `QuarkusProdModeTest` is used for native test because it depends on how often it runs and on what runners (f.e. I could never reproduce it on stronger AWS instance)

Quarkus code is quite complex and I can't tell how what is actually happening during `io.quarkus.maven.QuarkusBootstrapProvider.QuarkusMavenAppBootstrap#doBootstrap` differ to our bootstrap setup in regards to this race.

So, the question is does it affect other users or can I create standalone reproducer? Probably no, but it's so complex that I can't know with 100 % certainty.

**Comment by michalvavrik** [comment]
I don't want to be overly optimistic, but it seems like we fixed it by using Quarkus Maven plugin instead of QuarkusBootstrap directly. I'll close it, but re-open if problem occur in the future again. IMO it is fine, because users probably not supposed to build QuarkusBootstrap directly and there is a chance it was in our setup (or not.. :-)).
