### ISSUE TITLE
web-fragment.xml support introduced in 0.16.0 is broken

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2707]
`ZipPath` does not support `toFile()` so this code won't work:
https://github.com/quarkusio/quarkus/blob/master/extensions/undertow/deployment/src/main/java/io/quarkus/undertow/deployment/WebXmlParsingBuildStep.java#L109
and throw:
```
Caused by: java.lang.UnsupportedOperationException
at com.sun.nio.zipfs.ZipPath.toFile(ZipPath.java:597)
at io.quarkus.undertow.deployment.WebXmlParsingBuildStep.parseWebFragments(WebXmlParsingBuildStep.java:109)
at io.quarkus.undertow.deployment.WebXmlParsingBuildStep.createWebMetadata(WebXmlParsingBuildStep.java:88)
```

This is annoying because as long as you have a jar with a `web-fragment.xml`, you're not able to compile your application anymore.

Note: we should probably have a test for that. We already have a few tests with external jars (for JPA entities). It would be safer.

**Comment by gsmet** [comment]
@stuartwdouglas can you have a look at this one?

**Comment by gastaldi** [comment]
@gsmet I pushed a fix in https://github.com/quarkusio/quarkus/pull/2708 (still missing tests though)
