### ISSUE TITLE
Regression with upgrade 2.9.2 -> 2.11.1 in app using GraalVM Javascript interpreter

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus#27085]
### Describe the bug

My application uses `org.graalvm.js:js` to interpret Javascript. With 2.9.2 this was working fine (I had to make sure I keep my dependencies on the same version with Quarkus), but with upgrade to 2.11.1 the tests are failing with
```
2022-08-02 10:47:53,966 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-12) Uncaught exception received by Vert.x: org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: Duplicate language id regex. First language [Language class com.oracle.truffle.regex.RegexLanguage, Loaded from file:/home/rvansa/.m2/repository/org/graalvm/regex/regex/22.1.0/regex-22.1.0.jar]. Second language [Language class com.oracle.truffle.regex.RegexLanguage, Loaded from file:/home/rvansa/.m2/repository/org/graalvm/regex/regex/22.1.0/regex-22.1.0.jar].
    at com.oracle.truffle.polyglot.LanguageCache.createLanguages(LanguageCache.java:256)
    at com.oracle.truffle.polyglot.LanguageCache.loadLanguages(LanguageCache.java:222)
    at com.oracle.truffle.polyglot.LanguageCache.languages(LanguageCache.java:212)
    at com.oracle.truffle.polyglot.PolyglotEngineImpl.initializeLanguages(PolyglotEngineImpl.java:889)
    at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:254)
    at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:286)
    at org.graalvm.polyglot.Engine$Builder.build(Engine.java:620)
    at org.graalvm.polyglot.Context$Builder.build(Context.java:1822)
```
Looks like the `RegexLanguage` class is once loaded through AppClassLoader and another time through QuarkusClassLoader. 

### Expected behavior

There's no regression.

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

openjdk 11.0.15 2022-04-19

### GraalVM version (if different from Java)

22.1.0

### Quarkus version or git rev

2.11.1

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus/pull/27090 .

**Comment by squakez** [comment]
Hi folks, I can still see the same error in my application:
```
2022-08-25 08:38:27,286 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: Duplicate language id regex. First language [Language class com.oracle.truffle.regex.RegexLanguage, Loaded from file:/deployments/dependencies/lib/main/org.graalvm.regex.regex-22.1.0.jar]. Second language [Language class com.oracle.truffle.regex.RegexLanguage, Loaded from file:/deployments/dependencies/lib/main/org.graalvm.regex.regex-22.1.0.jar].
```
I have updated to quarkus `2.11.3.Final` and using still graalvm `22.1.0` (from builder image quay.io/quarkus/ubi-quarkus-native-image:22.1.0-java11). Is this configuration good or should I change something else?

**Comment by gsmet** [comment]
@squakez not sure. A small Maven reproducer would help as Radim confirmed the PR fixed the issue for him.

**Comment by squakez** [comment]
Thanks for the comment. Unfortunately it's not an easy tasks, as we're building the application via Camel K, and that is the one in charge to transparently create the maven application. Exporting it is not very easy as well. I'll check to see how else I can reproduce it and let you know.

**Comment by squakez** [comment]
I think I managed to workaround the problem by mimicking the behavior in the `runnerParentFirstArtifacts`. Please have a look at https://github.com/apache/camel-k-runtime/pull/878. I've tested locally and it seems it fix the problem. I wonder if that same workaround should be applied directly to the Quarkus code base. Please, feel free to reuse it.
