### ISSUE TITLE
GraphQL random CDI context issues when using RestClients with @Source

### ISSUE THREAD

**Issue by yuxblank** [quarkusio/quarkus#27127]
### Describe the bug

With version 2.10.x when using @Source and multiple RestClients there is a problem when accessing @RequestScoped elements like RoutingContext.

The issue is random and does not always break, so for that i have made a reproducer project with an integration test that you can check out.
https://github.com/yuxblank/quarkus-requestscope-bug

The error it's sometime different (maybe secondary cause) but mostly:

```log
uppressed: javax.ws.rs.ProcessingException: javax.enterprise.inject.IllegalProductException: Normal scoped producer method may not return null: io.quarkus.vertx.http.runtime.CurrentVertxRequest.getCurrent()
		at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:780)
		at org.jboss.resteasy.microprofile.client.impl.MpClientInvocation.filterRequest(MpClientInvocation.java:75)
		at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:491)
		at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
		at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
		at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
		at com.sun.proxy.$Proxy76.getExample(Unknown Source)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
		at com.sun.proxy.$Proxy77.getExample(Unknown Source)
		at com.rgigroup.quarkuscve.GraphQLEndpoint.exampleSource(GraphQLEndpoint.kt:24)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at io.smallrye.graphql.execution.datafetcher.helper.ReflectionInvoker.invoke(ReflectionInvoker.java:92)
		at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusDefaultDataFetcher.lambda$invokeAndTransformBlocking$0(QuarkusDefaultDataFetcher.java:62)
		at io.smallrye.context.impl.wrappers.SlowContextualCallable.call(SlowContextualCallable.java:21)
		at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.BlockingHelper.lambda$runBlocking$0(BlockingHelper.java:27)
		at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
		at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
		at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
		at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
		at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
		at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
		at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
		at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
		at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:834)
	Caused by: javax.enterprise.inject.IllegalProductException: Normal scoped producer method may not return null: io.quarkus.vertx.http.runtime.CurrentVertxRequest.getCurrent()
		at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.create(Unknown Source)
		at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_Bean.create(Unknown Source)
		at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:73)
		at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:28)
		at io.vertx.ext.web.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.arc$delegate(Unknown Source)
		at io.vertx.ext.web.CurrentVertxRequest_ProducerMethod_getCurrent_6dc23d16d53ba5c34e1e7b6f54290fd7b9aebd76_ClientProxy.request(Unknown Source)
		at com.rgigroup.quarkuscve.JWTAwareContext.parseClaims(JWTAwareContext.kt:29)
		at com.rgigroup.quarkuscve.JWTAwareContext.getTenant(JWTAwareContext.kt:21)
		at com.rgigroup.quarkuscve.JWTAwareContext_ClientProxy.getTenant(Unknown Source)
		at com.rgigroup.quarkuscve.ClientInterceptor.filter(ClientInterceptor.kt:19)
		at com.rgigroup.quarkuscve.ClientInterceptor_ClientProxy.filter(Unknown Source)
		at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:767)
		... 32 more

```

### Expected behavior

Current server request should be accessible during the context of a request.

### Actual behavior

With 2.10.x it randomly fails.
With 2.9.x works flawlessly

### How to Reproduce?

https://github.com/yuxblank/quarkus-requestscope-bug

- run mvn:test
- some run will break
- change quarkus version to 2.9.x
- run mvn:test
- test will never throw

### Output of `java -version`

adopt-openjdk-11.0.8

### Quarkus version or git rev

2.10.x

**Comment by mkouba** [comment]
I wonder if this could be related to https://github.com/quarkusio/quarkus/pull/27040?

**Comment by phillip-kruger** [comment]
I'll test it against that fix (main branch), else I'll debug to find the issue. Thanks

**Comment by mkouba** [comment]
So I tried to run the reproducer with the current quarkus main and it fails.

However, I'm wondering if it's a good idea to inject the `RoutingContext` in the `JWTAwareContext` which is used in the `ClientInterceptor`. I mean, in this particular case you call the rest client from a `@Source` method and I'm not sure that it's guaranteed that this method is called within the current request context. But my knowledge of graphql is minimal so let's @phillip-kruger dive into this ;-)

**Comment by yuxblank** [comment]
> So I tried to run the reproducer with the current quarkus main and it fails.
> 
> However, I'm wondering if it's a good idea to inject the `RoutingContext` in the `JWTAwareContext` which is used in the `ClientInterceptor`. I mean, in this particular case you call the rest client from a `@Source` method and I'm not sure that it's guaranteed that this method is called within the current request context. But my knowledge of graphql is minimal so let's @phillip-kruger dive into this ;-)

Not sure if it's the best way to do it, at least with Graphql.

What i need its to have access of the current request data for getting data from headers and other stuff (like the jwt token) that i use for routing all the clients to their correct destination.

They are all bound to a single HTTP request (server) so i expect there's something that allow me to share the data across a single one.

Since all modules that provide the graphql endpoints are actually jar imported, each of them shares the access to the current Context via implementation of that interface that depending on the Actual context provide the contextual request data.

The same logic is applied to JAXRS endpoints when dealing with the same RestClients implementation. (the implementation of Context changes on these deployments using ServletRequest wich works fine).

So the point to me is, getting shared access to the current @RequestScope from different clients / services across a single HTTP request.

If have any better recomendation tell me ;)

**Comment by deedarb** [comment]
after upgrading from 2.11.1 to 2.11.3 my app is not working.
i have a custom scalar type

        @AdaptToScalar(Scalar.String.class)
        public class I18nLabel {
            ...
            @Override
	        public String toString() {
                    Language lang = Optional.ofNullable(CDI.current()).map(cdi -> cdi.select(HttpServerRequest.class)).map(Instance::get).flatMap(WebUtils::extractLanguage).orElse(Language.EN);
		        return get(lang);
	        }
        }

and exception is raised at extract language with error log: 

    [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /api/store/graphql failed, error id: 84810bca-1f2e-4550-acc2-8bfdc7dccbab-1: javax.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=io.quarkus.vertx.http.runtime.CurrentRequestProducer, id=c786212c50efeac37ecc96f8570579f64be3bb5b]
            - you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
            at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:53)
            at io.vertx.core.http.CurrentRequestProducer_ProducerMethod_getCurrentRequest_05f950ea7ab91d121ba0bac525b89d62f3261b2d_ClientProxy.arc$delegate(Unknown Source)
            at io.vertx.core.http.CurrentRequestProducer_ProducerMethod_getCurrentRequest_05f950ea7ab91d121ba0bac525b89d62f3261b2d_ClientProxy.getHeader(Unknown Source)
            at is.happy.common.util.WebUtils.extractLanguage(WebUtils.java:34)


WebUtils.extractLanguage -> 

    public static Optional<Language> extractLanguage(HttpServerRequest request) {
		    String acceptLanguage = request.getHeader(HttpHeaders.ACCEPT_LANGUAGE);
		    List<ParsableLanguageValue> languages = HeaderParser.sort(HeaderParser.convertToParsedHeaderValues(acceptLanguage, ParsableLanguageValue::new));
		    return Lists.nonEmpty(languages)
			    .map(list -> list.get(0))
			    .map(lang -> Language.valueOf(lang.tag().toUpperCase()));
	    }
