### ISSUE TITLE
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider

### ISSUE THREAD

**Issue by paolopiccinini** [quarkusio/quarkus#27139]
### Describe the bug

Hi, when running a main in native mode calling a rest service I get a lot of exception `ClassNotFoundException`:

```posh
2022-08-04 15:45:02,181 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.http.host" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2022-08-04 15:45:02,189 INFO  [io.quarkus] (main) quarkus-ClassNotFoundException 1.0.0-SNAPSHOT native (powered by Quarkus 2.10.3.Final) started in 0.035s.
2022-08-04 15:45:02,189 INFO  [io.quarkus] (main) Profile prod activated.
2022-08-04 15:45:02,190 INFO  [io.quarkus] (main) Installed features: [cdi, rest-client, rest-client-jackson]
2022-08-04 15:45:02,190 INFO  [com.exa.MainExample] (main) Calling getById
2022-08-04 15:45:02,621 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.IIOImageProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.IIOImageProvider
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
        at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
        at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
        at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
        at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy203.getAllFruits(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
        at com.sun.proxy.$Proxy204.getAllFruits(Unknown Source)
        at com.example.rest.client.FruitResource.getAllFruits(FruitResource.java:23)
        at com.example.rest.client.FruitResource_ClientProxy.getAllFruits(Unknown Source)
        at com.example.MainExample.run(MainExample.java:21)
        at com.example.MainExample_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-08-04 15:45:02,621 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.sse.SseEventProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.sse.SseEventProvider
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
        at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
        at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
        at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
        at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy203.getAllFruits(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
        at com.sun.proxy.$Proxy204.getAllFruits(Unknown Source)
        at com.example.rest.client.FruitResource.getAllFruits(FruitResource.java:23)
        at com.example.rest.client.FruitResource_ClientProxy.getAllFruits(Unknown Source)
        at com.example.MainExample.run(MainExample.java:21)
        at com.example.MainExample_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-08-04 15:45:02,621 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DefaultTextPlain from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.DefaultTextPlain
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
        at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
        at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
        at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
        at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy203.getAllFruits(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
        at com.sun.proxy.$Proxy204.getAllFruits(Unknown Source)
        at com.example.rest.client.FruitResource.getAllFruits(FruitResource.java:23)
        at com.example.rest.client.FruitResource_ClientProxy.getAllFruits(Unknown Source)
        at com.example.MainExample.run(MainExample.java:21)
        at com.example.MainExample_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-08-04 15:45:02,622 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.FormUrlEncodedProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.FormUrlEncodedProvider
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
        at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
        at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
        at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
        at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy203.getAllFruits(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
        at com.sun.proxy.$Proxy204.getAllFruits(Unknown Source)
        at com.example.rest.client.FruitResource.getAllFruits(FruitResource.java:23)
        at com.example.rest.client.FruitResource_ClientProxy.getAllFruits(Unknown Source)
        at com.example.MainExample.run(MainExample.java:21)
        at com.example.MainExample_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-08-04 15:45:02,622 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DefaultNumberWriter from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.DefaultNumberWriter
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
        at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
        at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
        at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
        at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy203.getAllFruits(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
        at com.sun.proxy.$Proxy204.getAllFruits(Unknown Source)
        at com.example.rest.client.FruitResource.getAllFruits(FruitResource.java:23)
        at com.example.rest.client.FruitResource_ClientProxy.getAllFruits(Unknown Source)
        at com.example.MainExample.run(MainExample.java:21)
        at com.example.MainExample_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-08-04 15:45:02,622 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.SourceProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.SourceProvider
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
        at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
        at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
        at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
        at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy203.getAllFruits(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
        at com.sun.proxy.$Proxy204.getAllFruits(Unknown Source)
        at com.example.rest.client.FruitResource.getAllFruits(FruitResource.java:23)
        at com.example.rest.client.FruitResource_ClientProxy.getAllFruits(Unknown Source)
        at com.example.MainExample.run(MainExample.java:21)
        at com.example.MainExample_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-08-04 15:45:02,625 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DocumentProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.DocumentProvider
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
        at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
        at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
        at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
        at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy203.getAllFruits(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
        at com.sun.proxy.$Proxy204.getAllFruits(Unknown Source)
        at com.example.rest.client.FruitResource.getAllFruits(FruitResource.java:23)
        at com.example.rest.client.FruitResource_ClientProxy.getAllFruits(Unknown Source)
        at com.example.MainExample.run(MainExample.java:21)
        at com.example.MainExample_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-08-04 15:45:02,625 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DefaultBooleanWriter from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.DefaultBooleanWriter
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
        at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
        at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
        at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
        at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy203.getAllFruits(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
        at com.sun.proxy.$Proxy204.getAllFruits(Unknown Source)
        at com.example.rest.client.FruitResource.getAllFruits(FruitResource.java:23)
        at com.example.rest.client.FruitResource_ClientProxy.getAllFruits(Unknown Source)
        at com.example.MainExample.run(MainExample.java:21)
        at com.example.MainExample_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-08-04 15:45:02,627 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.JaxrsFormProvider from resource:/META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.JaxrsFormProvider
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:133)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
        at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
        at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.registerBuiltin(ResteasyProviderFactoryImpl.java:188)
        at org.jboss.resteasy.spi.ResteasyProviderFactory.getInstance(ResteasyProviderFactory.java:127)
        at org.jboss.resteasy.spi.ResteasyDeployment.onServer(ResteasyDeployment.java:19)
        at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.handles(DefaultResponseExceptionMapper.java:28)
        at org.jboss.resteasy.microprofile.client.ExceptionMapping.filter(ExceptionMapping.java:71)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterResponse(ClientInvocation.java:799)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:495)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy203.getAllFruits(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
        at com.sun.proxy.$Proxy204.getAllFruits(Unknown Source)
        at com.example.rest.client.FruitResource.getAllFruits(FruitResource.java:23)
        at com.example.rest.client.FruitResource_ClientProxy.getAllFruits(Unknown Source)
        at com.example.MainExample.run(MainExample.java:21)
        at com.example.MainExample_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-08-04 15:45:02,630 INFO  [com.exa.MainExample] (main) [Fruit{name='Apple', description='Winter fruit'}, Fruit{name='Pineapple', description='Tropical fruit'}]
2022-08-04 15:45:02,631 INFO  [io.quarkus] (main) quarkus-ClassNotFoundException stopped in 0.001s

```
The application works fine. Maybe am I missing some dependency?

I've mede an example project [here](https://github.com/paolopiccinini/quarkus-classnotfound)

Regards

### Expected behavior

No ClassNotFoundException thrown

### Actual behavior

ClassNotFoundException thrown

### How to Reproduce?

Step to reproduce:
1) Native compiling: docker build -t quarkus-test .
2) Start your example project rest-json-quickstart: mvn quarkus:dev
3) Start the image: docker run -p 9999:8080 quarkus-test

**Comment by geoand** [comment]
In your sample, why is `quarkus-resteasy-jackson` a `test` dependency?

**Comment by paolopiccinini** [comment]
Hi, becouse while testing I get Connection refused see [here](https://stackoverflow.com/questions/73109719/quarkus-test-rest-client-java-net-connectexception-connection-refused-connect) and in your [tutorial](https://quarkus.io/guides/rest-client) you tell to use:

```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-rest-client</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-rest-client-jackson</artifactId>
</dependency>
```

Should i remove scope test?

**Comment by geoand** [comment]
Yes please

**Comment by paolopiccinini** [comment]
Removing the scope test solved the issue. Thanks
