### ISSUE TITLE
Quartz jobs with WARN log: Datasource '<default>': Closing open connection prior to commit

### ISSUE THREAD

**Issue by szxp** [quarkusio/quarkus#27168]
### Describe the bug

I am trying to schedule Quartz jobs programmatically, similar to as suggested in https://quarkus.io/guides/quartz#scheduling-jobs-programmatically, but I see the following WARN log:

```
Datasource '<default>': Closing open connection prior to commit
```

### Expected behavior

No WARN log in the console.

### Actual behavior

WARN log can be seen in the log:
```
Datasource '<default>': Closing open connection prior to commit
```

### How to Reproduce?

Sample project
https://github.com/szxp/quartz-test/blob/main/module1/src/main/java/com/example/MyScheduler.java

Run in the module1 directory in Windows Powershell:
`mvn clean compile quarkus:dev -"Dquarkus.quartz.start-mode=forced"`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22000.795]

### Output of `java -version`

openjdk 17.0.2 2022-01-18 OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05) OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)

### Quarkus version or git rev

2.7.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: c:\Users\szp05\local\apache-maven-3.8.6 Java version: 17.0.2, vendor: GraalVM Community, runtime: c:\Users\szp05\local\graalvm-ce-java17-22.0.0.2 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

**Comment by mkouba** [comment]
CC @gsmet

**Comment by mkouba** [comment]
@szxp Does it still occur in recent versions of Quarkus (3.2+)?

**Comment by gsmet** [comment]
This is still a problem with the latest.

I got a stracktrace from the call (adding a `Thread.dumpStack()` to Agroal snapshot version from today):

```
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1389)
	at io.agroal.pool.ConnectionHandler.transactionBeforeCompletion(ConnectionHandler.java:337)
	at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:69)
	at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:678)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2451)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1516)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:71)
	at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1290)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.example.MyScheduler_MyJob_Subclass.execute(Unknown Source)
	at io.quarkus.quartz.runtime.CdiAwareJob.execute(CdiAwareJob.java:34)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

@barreiro I think we need your help here because from the Quarkus perspective it looks like standard operations and I'm surprised that you always log a warning when we call these methods.
Maybe we are not doing things right in how we handle the transactions?

Also /cc @mmusgrov .

Updated reproducer:

[quartz-test.zip](https://github.com/user-attachments/files/16706965/quartz-test.zip)

Run the following to reproduce:
```
cd module1
mvn clean compile quarkus:dev -"Dquarkus.quartz.start-mode=forced"
```

**Comment by barreiro** [comment]
I'll have a look.

Most likely, the `connection.close()` call is missing or happens after commit.
