### ISSUE TITLE
`quarkus.jib.platforms` not working out of box

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#27165]
### Describe the bug

So first, I'm not denying that my build environment might be not setup for multiplatform docker builds, but this ticket is more to ask for more documentation on what is necessary to perform a multiplatform build at https://quarkus.io/guides/container-image#jib

Is qemu or dockerx required to be installed? Any configuration to setup? 

I run `./gradlew clean build -Pquarkus.container-image.build=true -Pquarkus.jib.platforms=linux/amd64,linux/arm64/v8`, and get fairly unintuitive results (for someone new to multiplatform builds):

```
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
        at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:256)
        at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:182)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:977)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.util.concurrent.ExecutionException: com.google.common.base.VerifyException: multi-platform image building not supported when pushing to Docker engine
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
        at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
        at com.google.cloud.tools.jib.builder.steps.StepsRunner.run(StepsRunner.java:219)
        at com.google.cloud.tools.jib.api.Containerizer.run(Containerizer.java:390)
        at com.google.cloud.tools.jib.api.JibContainerBuilder.containerize(JibContainerBuilder.java:597)
        at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:249)
        ... 12 more
  Caused by: com.google.common.base.VerifyException: multi-platform image building not supported when pushing to Docker engine
        at com.google.common.base.Verify.verify(Verify.java:126)
        at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$loadDocker$18(StepsRunner.java:611)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

### Quarkus version or git rev

2.11.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by geoand** [comment]
Good point about better docs.

The feature requires docker's buildx

**Comment by GregJohnStewart** [comment]
Anything else required? Still getting the same exception after enabling buildkit

**Comment by geoand** [comment]
It seems that I remembered wrong.

**Comment by geoand** [comment]
See https://quarkus.io/guides/all-config#quarkus-container-image-jib_quarkus.jib.platforms for more information
