### ISSUE TITLE
"No RESTEasy Reactive request in progress" raised in @RequestScoped bean

### ISSUE THREAD

**Issue by userkci** [quarkusio/quarkus#27162]
### Describe the bug

When a `@RequestScoped` bean is injected with an HTTP request context bean such as `HttpHeaders`, a error occurs when accessing the HTTP request context bean if both:

- The request processing is accessing the bean on a thread other than the request thread, as may occur when returning a `Uni` from the handler.
- The HTTP request context bean has *not* been previously accessed on the request thread. If was previously accessed, then it works.

### Expected behavior

Hitting the endpoint should echo back the headers:

```shell
$ curl http://localhost:8080/test
Headers: [Accept=*/*,Host=localhost:8080,User-Agent=curl/7.54.0]
$
```

### Actual behavior

The curl request fails with an exception (from server's logging since it's more readable):

```
2022-08-05 15:01:59,085 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /test failed, error id: ca5ea351-f172-4123-aeb5-1c85e1a70a73-2: java.lang.IllegalStateException: No RESTEasy Reactive request in progress
	at org.jboss.resteasy.reactive.server.injection.ContextProducers.getContext(ContextProducers.java:138)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers.headers(ContextProducers.java:51)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_Subclass.headers$$superforward1(Unknown Source)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_Subclass$$function$$5.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_Subclass.headers(Unknown Source)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_headers_e2f74da907ba522e84abeecb299d68e340ff6250_Bean.create(Unknown Source)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_headers_e2f74da907ba522e84abeecb299d68e340ff6250_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:73)
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:28)
	at javax.ws.rs.core.ContextProducers_ProducerMethod_headers_e2f74da907ba522e84abeecb299d68e340ff6250_ClientProxy.arc$delegate(Unknown Source)
	at javax.ws.rs.core.ContextProducers_ProducerMethod_headers_e2f74da907ba522e84abeecb299d68e340ff6250_ClientProxy.getRequestHeaders(Unknown Source)
	at org.acme.TestResource$RequestDetails.dumpHeaders(TestResource.java:62)
	at org.acme.TestResource_RequestDetails_Subclass.dumpHeaders$$superforward1(Unknown Source)
	at org.acme.TestResource_RequestDetails_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.TestResource_RequestDetails_Subclass.dumpHeaders(Unknown Source)
	at org.acme.TestResource_RequestDetails_ClientProxy.dumpHeaders(Unknown Source)
	at org.acme.TestResource.lambda$echoHeaderGood$0(TestResource.java:45)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)


2022-08-05 15:01:59,097 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-0) Request failed: java.lang.IllegalStateException: No RESTEasy Reactive request in progress
	at org.jboss.resteasy.reactive.server.injection.ContextProducers.getContext(ContextProducers.java:138)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers.headers(ContextProducers.java:51)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_Subclass.headers$$superforward1(Unknown Source)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_Subclass$$function$$5.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_Subclass.headers(Unknown Source)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_headers_e2f74da907ba522e84abeecb299d68e340ff6250_Bean.create(Unknown Source)
	at org.jboss.resteasy.reactive.server.injection.ContextProducers_ProducerMethod_headers_e2f74da907ba522e84abeecb299d68e340ff6250_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:73)
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:28)
	at javax.ws.rs.core.ContextProducers_ProducerMethod_headers_e2f74da907ba522e84abeecb299d68e340ff6250_ClientProxy.arc$delegate(Unknown Source)
	at javax.ws.rs.core.ContextProducers_ProducerMethod_headers_e2f74da907ba522e84abeecb299d68e340ff6250_ClientProxy.getRequestHeaders(Unknown Source)
	at org.acme.TestResource$RequestDetails.dumpHeaders(TestResource.java:62)
	at org.acme.TestResource_RequestDetails_Subclass.dumpHeaders$$superforward1(Unknown Source)
	at org.acme.TestResource_RequestDetails_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.TestResource_RequestDetails_Subclass.dumpHeaders(Unknown Source)
	at org.acme.TestResource_RequestDetails_ClientProxy.dumpHeaders(Unknown Source)
	at org.acme.TestResource.lambda$echoHeaderGood$0(TestResource.java:45)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

```
@Path("/test")
public class TestResource {
    private RequestDetails details;

    TestResource(RequestDetails details) {
        this.details = details;
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Uni<String> echoHeaders(@QueryParam("action") String action) {
        if (action == null) {
            action = "";
        }
        switch (action) {
            case "accessHTTP":
                // Access HttpHeaders proxy through proxied bean
                details.dumpHeaders();
                break;
            case "accessBean":
                // Access proxied bean, but not HttpHeaders proxy
                details.ping();
                break;
        }
        return Uni.createFrom()
                .item(() -> details.dumpHeaders())
                .runSubscriptionOn(Infrastructure.getDefaultExecutor());
    }

    @RequestScoped
    public static class RequestDetails {
        private HttpHeaders headers;

        RequestDetails(HttpHeaders headers) {
            this.headers = headers;
        }

        public void ping() {
            System.out.println("Ping!");
        }

        public String dumpHeaders() {
            return "Headers: " + headers.getRequestHeaders() + "\n";
        }

        @PostConstruct
        void postConstruct() {
            System.out.println("Constructed");
        }

        @PreDestroy
        void preDestroy() {
            System.out.println("Destroying");
        }
    }

    @ApplicationScoped
    public static class EagerAccessor {
        private HttpHeaders headers;

        EagerAccessor(HttpHeaders headers) {
            this.headers = headers;
        }

        @ServerRequestFilter
        void eagerAccess(ContainerRequestContext ctx) {
            String action = ctx.getUriInfo().getQueryParameters().getFirst("action");
            if (action != null && action.equalsIgnoreCase("accessHTTPInFilter")) {
                // Access HttpHeaders proxy directly
                System.out.println("HttpHeaders accessed");
                headers.getLength();
            }
        }
    }
}
```

Included are some additional execution paths, selected by the `action` query parameter:
"accessHTTP" accesses the HTTP context bean in the request thread (and will succeed)
"accessBean" accesses the RequestScoped bean in the request thread (and will fail), so that the RequestScoped bean is created.
"accessHTTPInFilter" accesses the HTTP context bean in a filter (and will succeed). 

### Output of `uname -a` or `ver`

18.7.0 Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 LTS OpenJDK Runtime Environment Corretto-17.0.4.8.1 (build 17.0.4+8-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.4.8.1 (build 17.0.4+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

### Additional information

Results are the same regardless of whether quarkus-smallrye-context-propagation is included.

The cases in which it does work suggests to me that the lazy instantiation of the proxied HTTP request context bean is pushed outside the RestEASY request scope, but the CDI request scope is still active.

**Comment by geoand** [comment]
I see you are doing:

```java
        return Uni.createFrom()
                .item(details::dumpHeaders)
                .runSubscriptionOn(Infrastructure.getDefaultExecutor());
```

when returning the `Uni`.

That is something that not only is unnecessary, but in this case where we need to "setup" the thread when executing a request, it fails. 

If you simply remove the `runSubscriptionOn` part, everything works.

In general, when using RESTEasy Reactive with a `Uni`, to control the thread the request is served on you can use the `@Blocking` and `@NonBlocking` annotations (be default the use of a `Uni` as return type means that request will be served on the event loop).

**Comment by userkci** [comment]
The `runSubscriptionOn` is merely a simplification made _for this example_ to cause execution of request processing on another thread. To be clear, an important aspect of this is that some request processing _is not executing_ on the thread which called the handler. Removing `runSubscriptionOn` makes everything execute on the request thread, so does not replicate the triggering conditions. The real code which encountered this makes calls to third-party asynchronous APIs. Using `Uni.createFrom().completionStage()` or `Uni.createFrom().future()` will see any subsequent processing running on a different thread. This seems like a completely reasonable thing to do within a handler. 

So a more faithful representation of the situation might be more like below (again, simplified by using the default worker pool):
```
        return Uni.createFrom()
                .future(() -> Infrastructure.getDefaultWorkerPool().submit(() -> {})
                .map((ignore) -> details.dumpHeaders());
```

Is this a serious problem? I suspect not. It requires a number of conditions to be met which seem generally unlikely:
- References to HTTP context beans are indirect through another bean.
- The HTTP context bean is only accessed after processing has moved off the thread invoking the handler.

It is however, a rather confusing error when it does arise because it is not particularly obvious why things aren't working. Especially as it demonstrates some aspects of being "within" a request context, as `@RequestScoped` beans do resolve. 

There are a few workarounds available, but may not be palatable depending on one's constraints:
1. You can force the async execution to be synchronous (via `Future.get()`) and make sure you flag the handler properly.
2. You can remove the indirect reference the HTTP context bean, replacing them with direct references.
3. You can force an access to the HTTP context bean on the request thread. Note that this is what the `ServerRequestFilter` does in the example; running with the option to trigger it, you see the later access on another thread work, because the proxy was already set up by the earlier call in a valid context.
