### ISSUE TITLE
Postgres DevServices cannot pull image since 2.11.2.Final

### ISSUE THREAD

**Issue by syr** [quarkusio/quarkus#27186]
### Describe the bug

After updating quarkus from 2.10.3.Final -> 2.11.2.Final I cannot startup my quarkus application with dev services anymore.
Seems like image pull fails.

My Docker daemon is configured to use a socks5 proxy.

To continue to work I had to rollback to 2.10.3.Final  and everything worked again

### Expected behavior

Quarkus app would start up  and spinup postgres and ryuk via testcontainers

### Actual behavior

Quarkus app starts and fails with infinitely trying to pull image

```

2022-08-08 17:52:44,755 ERROR [com.git.doc.api.asy.ResultCallbackTemplate] (docker-java-stream--933788147) Error during callback: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://registry-1.docker.io/v2/\": EOF"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022-08-08 17:52:44,757 WARN  [doc.io/postgres:14]] (build-36) Retrying pull for image: docker.io/postgres:14 (119s remaining)
2022-08-08 17:52:44,962 ERROR [com.git.doc.api.asy.ResultCallbackTemplate] (docker-java-stream--933788147) Error during callback: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://registry-1.docker.io/v2/\": EOF"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022-08-08 17:52:44,963 WARN  [doc.io/postgres:14]] (build-36) Retrying pull for image: docker.io/postgres:14 (119s remaining)
2022-08-08 17:52:45,188 ERROR [com.git.doc.api.asy.ResultCallbackTemplate] (docker-java-stream--933788147) Error during callback: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://registry-1.docker.io/v2/\": EOF"}

...
```

### How to Reproduce?

https://github.com/syr/quarkus-resteasy-postgres/blob/devservices-fail_2.11.2.Final/src/test/java/org/acme/PersonServiceTest.java

### Output of `java -version`

jdk-17.0.2+8

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2

### Additional information

```
2022-08-08 17:52:40,945 INFO  [org.tes.DockerClientFactory] (build-36) Connected to docker: 
  Server Version: 20.10.8
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 25369 MB
2022-08-08 17:52:41,028 INFO  [org.tes.uti.ImageNameSubstitutor] (build-36) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2022-08-08 17:52:41,341 INFO  [doc.3.3]] (build-36) Creating container for image: testcontainers/ryuk:0.3.3
2022-08-08 17:52:41,736 INFO  [org.tes.uti.RegistryAuthLocator] (build-36) Credential helper/store (docker-credential-desktop) does not have credentials for https://index.docker.io/v1/
2022-08-08 17:52:42,846 INFO  [doc.3.3]] (build-36) Container testcontainers/ryuk:0.3.3 is starting: 589fe2f3f7ef10d8fce1eb45c8683214c494e2f954a1b7219776e8d6eabbb891
2022-08-08 17:52:44,308 INFO  [doc.3.3]] (build-36) Container testcontainers/ryuk:0.3.3 started in PT3.2564332S
2022-08-08 17:52:44,312 INFO  [org.tes.uti.RyukResourceReaper] (build-36) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2022-08-08 17:52:44,313 INFO  [org.tes.DockerClientFactory] (build-36) Checking the system...
2022-08-08 17:52:44,313 INFO  [org.tes.DockerClientFactory] (build-36) ?? Docker server version should be at least 1.6.0
2022-08-08 17:52:44,343 INFO  [doc.io/postgres:14]] (build-36) Pulling docker image: docker.io/postgres:14. Please be patient; this may take some time but only needs to be done once.
2022-08-08 17:52:44,545 INFO  [org.tes.uti.RegistryAuthLocator] (build-36) Credential helper/store (docker-credential-desktop) does not have credentials for docker.io
2022-08-08 17:52:44,755 ERROR [com.git.doc.api.asy.ResultCallbackTemplate] (docker-java-stream--933788147) Error during callback: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://registry-1.docker.io/v2/\": EOF"}


	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022-08-08 17:52:44,757 WARN  [doc.io/postgres:14]] (build-36) Retrying pull for image: docker.io/postgres:14 (119s remaining)
2022-08-08 17:52:44,962 ERROR [com.git.doc.api.asy.ResultCallbackTemplate] (docker-java-stream--933788147) Error during callback: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://registry-1.docker.io/v2/\": EOF"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022-08-08 17:52:44,963 WARN  [doc.io/postgres:14]] (build-36) Retrying pull for image: docker.io/postgres:14 (119s remaining)
2022-08-08 17:52:45,188 ERROR [com.git.doc.api.asy.ResultCallbackTemplate] (docker-java-stream--933788147) Error during callback: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://registry-1.docker.io/v2/\": EOF"}

...

**Comment by geoand** [comment]
The reproducer works just fine for me. I'd suggest purging your local docker contents and trying again

**Comment by syr** [comment]
Sorry, seems like the socks proxy was not working. I changed to another http proxy and it works now
