### ISSUE TITLE
ContextNotActiveException: SessionScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#27237]
### Describe the bug

I have code like the below:

```java
@ApplicationScoped
@Path("/")
public class Application {

    @Inject
    SessionScopedCalciteSchema sessionScopedCalciteSchema;

    @CheckedTemplate(requireTypeSafeExpressions = false)
    static class Templates {
        public static native TemplateInstance index(SchemaPlus rootSchema);
    }

    @GET
    public TemplateInstance index() {
        SchemaPlus rootSchema = sessionScopedCalciteSchema.getCalciteConnection().getRootSchema();
        return Templates.index(rootSchema);
    }
}
```
```java
@SessionScoped
public class SessionScopedCalciteSchema implements java.io.Serializable {

    private UUID id;
    private DataSource h2DataSource;
    private CalciteConnection calciteConnection;

    public SessionScopedCalciteSchema() {
    }

    @PostConstruct
    void init() {
        this.id = UUID.randomUUID();
        this.h2DataSource = ChinookDatabaseService.createChinookDatabase(id.toString());
        this.calciteConnection = initCalciteConnection();

        SchemaPlus rootSchema = calciteConnection.getRootSchema();
        JdbcCatalogSchema catalog = JdbcCatalogSchema.create(rootSchema, "chinook", h2DataSource, null);
        rootSchema.add("chinook", catalog);
    }

    private static CalciteConnection initCalciteConnection() {
      // ...
    }

    // getters/setters
}
```

Running it throws this error:
```java
javax.enterprise.context.ContextNotActiveException: SessionScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.github.gavinray97.service.SessionScopedCalciteSchema, id=5ceb6548b8253f07699efa8b7c65908ba6b0a510]
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:53)
	at io.github.gavinray97.service.SessionScopedCalciteSchema_ClientProxy.arc$delegate(Unknown Source)
	at io.github.gavinray97.service.SessionScopedCalciteSchema_ClientProxy.getCalciteConnection(Unknown Source)
	at io.github.gavinray97.Application.index(Application.java:30)
	at io.github.gavinray97.Application_Subclass.index$$superforward1(Unknown Source)
	at io.github.gavinray97.Application_Subclass$$function$$7.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
```

My dependencies are:
```kts
implementation("io.quarkus:quarkus-arc")
implementation("io.quarkus:quarkus-jdbc-h2")
implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
implementation("io.quarkus:quarkus-resteasy-reactive-qute")
implementation("io.quarkus:quarkus-resteasy-reactive")
implementation("io.quarkus:quarkus-undertow")
```

Using version `2.11.1.Final`

What does this error mean? 🤔

**Comment by GavinRay97** [comment]
Ah it seems that `@RequestScoped` might be incompatible with `resteasy-reactive`?

When I swap to non-reactive it appears to work

**Comment by geoand** [comment]
Interesting. Can you provide a sample project we can look at?
This should work

**Comment by geoand** [comment]
@GavinRay97 ^

**Comment by geoand** [comment]
I'm going to close this due to lack of feedback.

If you do manage to provide a reproducer, we'll gladly take a look.

**Comment by schltgn** [comment]
I'm having this issue, too. It can easily be reproduced:

```java
@Path("/hello")
public class GreetingResource {

    @Inject
    public Counter counter;

    @GET
    public String hello() {
        return "Hello from RESTEasy Reactive, Counter: " + counter.incrementAndGet();
    }
}
```

```java
@SessionScoped
public class Counter {
    private int count;

    public int incrementAndGet() {
        return ++this.count;
    }
}
``` 

Dependencies are:
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-undertow</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
```

Running the app in DEV mode, http://localhost:8080/hello show the following stack trace:
```
javax.enterprise.context.ContextNotActiveException: SessionScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=org.acme.Counter, id=73601d8733c3594434fcb9bcd4db1746aedd7c5e]
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:55)
	at org.acme.Counter_ClientProxy.arc$delegate(Unknown Source)
	at org.acme.Counter_ClientProxy.incrementAndGet(Unknown Source)
	at org.acme.GreetingResource.hello(GreetingResource.java:17)
	at org.acme.GreetingResource$quarkusrestinvoker$hello_e747664148511e1e5212d3e0f4b40d45c56ab8a1.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
``` 

Thanks for any help!

**Comment by geoand** [comment]
I just noticed that this uses `@SessionScoped` which is not supported in RESTEasy Reactive

**Comment by GavinRay97** [comment]
D'oh. Is there a list of incompatible annotations anywhere for future reference

**Comment by geoand** [comment]
I was actually thinking that we should fail the build if a `@SessionScoped` bean is injected into a JAX-RS resource (when RESTEasy Reactive is being used).

WDYT @mkouba ?

**Comment by GavinRay97** [comment]
Maybe it could be good to put a little note at the top of the RESTEasy Reactive extension saying "Hey, these are the JAX-RS annotations which you may expect to be present/work but which don't currently exist in the Reactive variant" FWIW too

**Comment by schltgn** [comment]
Are there any plans to support `@SessionScoped` in RESTEasy Reactive in the future?

**Comment by geoand** [comment]
Nope

**Comment by geoand** [comment]
Nope

**Comment by geoand** [comment]
> Maybe it could be good to put a little note at the top of the RESTEasy Reactive extension saying "Hey, these are the JAX-RS annotations which you may expect to be present/work but which don't currently exist in the Reactive variant" FWIW too

@GavinRay97 you would like to contribute that?

**Comment by geoand** [comment]
@mkouba is there any API in Arc that would allow one to retrieve all the beans that "depend" on a given bean (including multiple levels of bean injection)?

**Comment by mkouba** [comment]
> @mkouba is there any API in Arc that would allow one to retrieve all the beans that "depend" on a given bean (including multiple levels of bean injection)?

There's nothing like "transitive dependency resolution". You would need to resolve the dependencies manually (for each level). Also are you talking about build time or run time?

**Comment by geoand** [comment]
I would like to have that information at build time, the idea being to figure out if any `@SessionScoped` bean is injected into a JAX-RS Resource.

**Comment by mkouba** [comment]
You can start with `ValidationPhaseBuildItem`; at this point all injection points are resolved. Then simply analyse the injection points of the beans created for JAX-RS resources; e.g. `ValidationPhaseBuildItem.getContext().beans().filter(jaxRsResourcePredicate)` and then `BeanInfo#getAllInjectionPoints()` + test scope for `InjectionPointInfo.getResolvedBean()`.

And you would need to do this recursively for transient dependencies.

**Comment by geoand** [comment]
Right, I knew about that, I was just looking for something that already handles the recurviness :)

**Comment by GavinRay97** [comment]
@GavinRay97 Sure I can make the PR for the extensions docs 👍 

Is it only for `SessionScoped` that is not available at the moment?

**Comment by geoand** [comment]
Yup
