### ISSUE TITLE
Running tests with junit is fine, but when running with maven java.net.BindException: Address already in use: bind

### ISSUE THREAD

**Issue by paolopiccinini** [quarkusio/quarkus#27247]
### Describe the bug

Hi, I've writed an example project [here](https://github.com/paolopiccinini/quarkus-classnotfound). When I run the unit tests from the IDE one by one everything is fine. But when i try to compile with maven I got an exception:

```posh
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.MainExampleTest
2022-08-11 16:10:49,529 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
2022-08-11 16:10:52,358 INFO  [org.ecl.jet.uti.log] (pool-4-thread-1) Logging initialized @22401ms to org.eclipse.jetty.util.log.Slf4jLog
2022-08-11 16:10:52,586 INFO  [org.ecl.jet.ser.Server] (pool-4-thread-1) jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 17.0.4+11-LTS-179
2022-08-11 16:10:52,617 INFO  [org.ecl.jet.ser.han.ContextHandler] (pool-4-thread-1) Started o.e.j.s.ServletContextHandler@7b16f061{/__admin,null,AVAILABLE}
2022-08-11 16:10:52,625 INFO  [org.ecl.jet.ser.han.ContextHandler] (pool-4-thread-1) Started o.e.j.s.ServletContextHandler@17b2ba12{/,null,AVAILABLE}
2022-08-11 16:10:52,802 INFO  [org.ecl.jet.ser.AbstractConnector] (pool-4-thread-1) Started NetworkTrafficServerConnector@5f6e5636{HTTP/1.1, (http/1.1)}{0.0.0.0:7777}
2022-08-11 16:10:52,803 INFO  [org.ecl.jet.ser.Server] (pool-4-thread-1) Started @22848ms
2022-08-11 16:10:53,752 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
2022-08-11 16:10:54,400 INFO  [io.quarkus] (main) quarkus-ClassNotFoundException 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.10.3.Final) started in 6.444s. Listening on: http://localhost:8081
2022-08-11 16:10:54,401 INFO  [io.quarkus] (main) Profile test activated. 
2022-08-11 16:10:54,401 INFO  [io.quarkus] (main) Installed features: [cdi, rest-client, rest-client-jackson, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
2022-08-11 16:10:54,403 INFO  [com.exa.MainExample] (main) Calling getById
2022-08-11 16:10:54,631 INFO  [org.ecl.jet.ser.han.Con.ROOT] (qtp1724775732-78) RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
2022-08-11 16:10:54,838 INFO  [com.exa.MainExample] (main) [Fruit{name='apple', description='apple'}, Fruit{name='orange', description='orange'}]
2022-08-11 16:10:54,894 INFO  [io.quarkus] (main) quarkus-ClassNotFoundException stopped in 0.055s
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.461 s - in com.example.MainExampleTest
[INFO] Running com.example.rest.client.FruitResourceTest
2022-08-11 16:10:57,611 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
2022-08-11 16:11:01,043 INFO  [org.ecl.jet.uti.log] (pool-14-thread-1) Logging initialized @31088ms to org.eclipse.jetty.util.log.Slf4jLog
2022-08-11 16:11:01,245 INFO  [org.ecl.jet.ser.Server] (pool-14-thread-1) jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 17.0.4+11-LTS-179
2022-08-11 16:11:01,268 INFO  [org.ecl.jet.ser.han.ContextHandler] (pool-14-thread-1) Started o.e.j.s.ServletContextHandler@7d25ff58{/__admin,null,AVAILABLE}
2022-08-11 16:11:01,271 INFO  [org.ecl.jet.ser.han.ContextHandler] (pool-14-thread-1) Started o.e.j.s.ServletContextHandler@2ba020d9{/,null,AVAILABLE}
2022-08-11 16:11:01,277 INFO  [org.ecl.jet.ser.AbstractConnector] (main) Stopped NetworkTrafficServerConnector@10af8861{HTTP/1.1, (http/1.1)}{0.0.0.0:7777}
2022-08-11 16:11:01,278 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@2ba020d9{/,null,UNAVAILABLE}
2022-08-11 16:11:01,279 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@7d25ff58{/__admin,null,UNAVAILABLE}
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.444 s <<< FAILURE! - in com.example.rest.client.FruitResourceTest
[ERROR] com.example.rest.client.FruitResourceTest.testFruitsEndpoint  Time elapsed: 0 s  <<< ERROR!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:634)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:705)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:77)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:355)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:302)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:280)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:272)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:271)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:102)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:101)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:242)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:611)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:649)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	... 36 more
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource com.example.rest.client.resource.WireMockExtensions@67e436ea
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource com.example.rest.client.resource.WireMockExtensions@67e436ea
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:457)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 3 more
Caused by: com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:7777
	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:149)
	at com.example.rest.client.resource.WireMockExtensions.start(WireMockExtensions.java:26)
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:452)
	... 4 more
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:7777
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:192)
	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:147)
	... 6 more
Caused by: java.io.IOException: Failed to bind to /0.0.0.0:7777
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:190)
	... 7 more
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345)
	... 14 more

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   FruitResourceTest.testFruitsEndpoint » Runtime java.lang.reflect.InvocationTargetException
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:20 min
[INFO] Finished at: 2022-08-11T16:11:02+02:00
[INFO] ------------------------------------------------------------------------
```

Also the integration tests are broken if I launch them with the IDE:
`java.lang.IllegalStateException: Unable to locate the artifact metadata file created that must be created by Quarkus in order to run integration tests. Make sure this test is run after the Quarkus artifact is built from your build tool.`
I've added the full stack trace in the integration tests class.

And how @QuarkusMainTest works? It injects a mock of the resource? Because it seems to start the same moked server.

### Expected behavior

No Exception thrown when compiling

### Actual behavior

Exception thrown when compiling

### How to Reproduce?

mvn clean package

**Comment by geoand** [comment]
The problem is that you are mixing both `@QuarkusTest` and `@QuarkusMainTest` in the same run. These are both trying to manage Wiremock and causing problems.

https://github.com/quarkusio/quarkus/pull/27426 will make this mixing an explicit error.

**Comment by geoand** [comment]
As for the integration test failure you are seeing, that is expected. In order to be able to run these tests, the application artifact (jar, native binary, container etc.) first needs to be created.

**Comment by paolopiccinini** [comment]
So what I should test? The main or the resource? I can't test both. I will exclude one of the from the sonar scan. Witch one you suggest to test?

There is a documentation for @quarkuainTest? What is inject in in the MainExaple? I have not explicit set any mock? There is some magic behind?

**Comment by geoand** [comment]
If you have a CLI application, you use `@QuarkusMainTest`.

Otherwise if you have a server application (like a normal HTTP API or something), then you use `@QuarkusTest`

**Comment by paolopiccinini** [comment]
There is a documentation for @QurkusMainTest? What is injectected in in the MainExaple? I have not explicit set any mock? There is some magic behind?

**Comment by paolopiccinini** [comment]
Also if I have more bean in the MainExample how I can control them?

**Comment by geoand** [comment]
Documentation is [here](https://quarkus.io/guides/command-mode-reference#testing-command-mode-applications).

**Comment by paolopiccinini** [comment]
Thank you!

**Comment by ebullient** [comment]
> The problem is that you are mixing both `@QuarkusTest` and `@QuarkusMainTest` in the same run. These are both trying to manage Wiremock and causing problems.
> 
> #27426 will make this mixing an explicit error.

This doesn't make any sense to me. I should be able to write unit tests against individual tests within my CLI, as well as full CLI tests within the "same run" ... I now have a case where I never even use `@QuarkusTest` explicitly, and I can't upgrade to 2.13 because my tests are broken. I think we've busted something with the user experience for building CLI here because we've decided that you can't mix QuarkusTest and QuarkusMainTest arbitrarily.
