### ISSUE TITLE
Dev mode - argument type mismatch when invoking a RUNTIME_INIT build step

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#2724]
**Describe the bug**

```
10:01:02,799 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step com.github.mkouba.qute.quarkus.deployment.QuteProcessor#initialize threw an exception: java.lang.IllegalArgumentException: argument type mismatch
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:145)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:173)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:100)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step com.github.mkouba.qute.quarkus.deployment.QuteProcessor#initialize threw an exception: java.lang.IllegalArgumentException: argument type mismatch
	at io.quarkus.builder.Execution.run(Execution.java:124)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:137)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:113)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:110)
	... 2 more
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:508)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:414)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1429)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

It's very likely a class loading issue - I've compared the class loader of the [QuteTemplate](https://github.com/mkouba/qute/blob/master/quarkus/deployment/src/main/java/com/github/mkouba/qute/quarkus/deployment/QuteProcessor.java#L184) class coming from the corresponding `java.lang.reflect.Method` and the class loader of the class coming from the  argument and they differ: `sun.misc.Launcher$AppClassLoader`
VS `io.quarkus.runner.RuntimeClassLoader`. See https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java#L507

**To Reproduce**
1. clone https://github.com/mkouba/qute
2. `mvn clean install`
3. `mvn compile quarkus:dev` in the quarkus/example dir

**Comment by mkouba** [comment]
@stuartwdouglas do you have an idea what's going on here?

**Comment by stuartwdouglas** [comment]
This is because the template and the project are in the same project. The 'dev' mode supports multi module projects now, so it will discover the additional modules and attempt to make them hot reloadable, which does not work. You can work around this for now with mvn compile quarkus:dev -DnoDeps, but I might add a simple fix to skip extension modules

**Comment by stuartwdouglas** [comment]
Actually I can't really fix this, as it will also include the qtue core itself, which will have similar problems, the real fix it to just add noDeps to the plugin config.

**Comment by mkouba** [comment]
Ah, I'm sorry I actually knew the root cause (I created https://github.com/quarkusio/quarkus/issues/2575) and forgot to use `-DnoDeps`! Marking this as invalid.
