### ISSUE TITLE
Build failure with quarkus-smallrye-openapi when upgrading to 2.11.2.Final

### ISSUE THREAD

**Issue by thanhnguyenduy** [quarkusio/quarkus#27240]
### Describe the bug

I upgraded Quarkus from 2.9.2.Final to 2.11.2.Final and I get some failure related to quarkus-smallrye-openapi. The same problem also happened from 2.10.0.Final. I already created one ticket on  2.10.2.Final before but I have no clue to reproduce so now I reopen it. I am so sorry for my late reply.

`211526 [ERROR] com.nttdata.homologation.documentservice.common.mongomigration.sprint038.CL_002_CreateDefaultSnippetsTest.testCreateDefaultSnippets  Time elapsed: 0.082 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: **java.util.ServiceConfigurationError: org.eclipse.microprofile.openapi.spi.OASFactoryResolver: io.smallrye.openapi.spi.OASFactoryResolverImpl not a subtype**
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at org.eclipse.microprofile.openapi.spi.OASFactoryResolver.loadSpi(OASFactoryResolver.java:96)
	at org.eclipse.microprofile.openapi.spi.OASFactoryResolver.loadSpi(OASFactoryResolver.java:92)
	at org.eclipse.microprofile.openapi.spi.OASFactoryResolver.loadSpi(OASFactoryResolver.java:92)
	at org.eclipse.microprofile.openapi.spi.OASFactoryResolver.instance(OASFactoryResolver.java:74)
	at org.eclipse.microprofile.openapi.OASFactory.createObject(OASFactory.java:79)
	at org.eclipse.microprofile.openapi.OASFactory.createSecurityRequirement(OASFactory.java:313)
	at com.nttdata.homologation.common.rest.OASAddSecurityFilter.filterOperation(OASAddSecurityFilter.java:22)
	at io.smallrye.openapi.api.util.FilterUtil.filterOperation(FilterUtil.java:238)
	at io.smallrye.openapi.api.util.FilterUtil.filterPathItem(FilterUtil.java:204)
	at io.smallrye.openapi.api.util.FilterUtil.filter(FilterUtil.java:109)
	at io.smallrye.openapi.api.util.FilterUtil.applyFilter(FilterUtil.java:51)
	at io.smallrye.openapi.api.OpenApiDocument.filterModel(OpenApiDocument.java:173)
	at io.smallrye.openapi.api.OpenApiDocument.initialize(OpenApiDocument.java:133)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.storeDocument(SmallRyeOpenApiProcessor.java:1030)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.storeDocument(SmallRyeOpenApiProcessor.java:1004)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:719)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:[83](https://git.altemista.cloud/homologation/hds/document-service/-/jobs/882593#L83)4)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)`

### Expected behavior

Should be no error happened when run unit tests with quarkus-smallrye-openapi 2.11.2.Final.

### Actual behavior

I upgraded Quarkus from 2.9.2.Final to 2.11.2.Final and I get some failure related to quarkus-smallrye-openapi. Then I run my unit tests and the first case failed with above logs. 
In case I update Quarkus to 2.11.2.Final and set quarkus-smallrye-openapi back to 2.9.2.Final version, everything is fine. So I guess there is some changes related to OASFactoryResolverImpl on 2.10.0.Final versions quarkus-smallrye-openapi?

### How to Reproduce?

I tried to reproduce in a new project but unfortunately I failed. I just can provide all information I have and hope you guys can figure out something wrong with OASFactoryResolverImpl in quarkus-smallrye-openapi 2.10,0 final version and later versions.

**Comment by thanhnguyenduy** [comment]
The old ticket is here: https://github.com/quarkusio/quarkus/issues/26749

**Comment by phillip-kruger** [comment]
Hi @thanhnguyenduy . Like I mentioned in the old ticket, please provider a reproducer, as I can not recreate this locally. Create a small app that we can run locally that reproduce the error. Thanks.

**Comment by thanhnguyenduy** [comment]
Hi @phillip-kruger , I failed to reproduce this issue on a new project. So I will close this topic until I find something. Thanks.
