### ISSUE TITLE
quarkus-smallrye-jwt (without any additional changes) makes the application build and run fail

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2725]
quarkus-smallrye-jwt (without any additional changes) makes the application build and run fail

```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=io.quarkus.qe \
    -DprojectArtifactId=scenario-101-getting-started \
    -DprojectVersion=1.0.0-SNAPSHOT \
    -DclassName="io.quarkus.qe.hello.GreetingResource" \
    -Dextensions=io.quarkus:quarkus-smallrye-jwt
```

```
mvn clean package
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.qe.hello.GreetingResourceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.756 s <<< FAILURE! - in io.quarkus.qe.hello.GreetingResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 0.008 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [io.quarkus.qe.hello.GreetingResourceTest]
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.util.NoSuchElementException: No value present

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   GreetingResourceTest.testHelloEndpoint » TestInstantiation TestInstanceFactory...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

Application execution (app generated via `mvn clean package -DskipTests -DskipITs`)
```
java -jar /Users/rsvoboda/tmp/exp/target/scenario-101-getting-started-1.0.0-SNAPSHOT-runner.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.<clinit>(Unknown Source)
	... 1 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider.getContextInfo(JWTAuthContextInfoProvider.java:200)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.create(Unknown Source)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.get(Unknown Source)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.get(Unknown Source)
	at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMethodExtension_Bean.create(Unknown Source)
	at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMethodExtension_Bean.get(Unknown Source)
	at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMethodExtension_Bean.get(Unknown Source)
	at io.quarkus.arc.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:325)
	at io.quarkus.arc.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:337)
	at io.quarkus.arc.ArcContainerImpl$1.get(ArcContainerImpl.java:210)
	at io.quarkus.arc.ArcContainerImpl$1.get(ArcContainerImpl.java:207)
	at io.quarkus.arc.runtime.ArcDeploymentTemplate$2$1.create(ArcDeploymentTemplate.java:86)
	at io.quarkus.arc.runtime.BeanContainer.instance(BeanContainer.java:35)
	at io.quarkus.smallrye.jwt.runtime.SmallRyeJwtTemplate.createAuthExtension(SmallRyeJwtTemplate.java:41)
	at io.quarkus.deployment.steps.SmallRyeJwtProcessor$registerJwtAuthExtension14.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.SmallRyeJwtProcessor$registerJwtAuthExtension14.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.<clinit>(Unknown Source)
	... 1 more

```

After adding following snippet into src/main/resources/application.properties I see a bit different errors
```properties
quarkus.smallrye-jwt.auth-mechanism=MP-JWT
quarkus.smallrye-jwt.enabled=false
```

```
INFO] Running io.quarkus.qe.hello.GreetingResourceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.293 s <<< FAILURE! - in io.quarkus.qe.hello.GreetingResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 0.011 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException:
TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [io.quarkus.qe.hello.GreetingResourceTest]: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.jwt.deployment.SmallRyeJwtProcessor#configureIdentityManager threw an exception: java.lang.NullPointerException
Caused by: java.lang.RuntimeException:
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.jwt.deployment.SmallRyeJwtProcessor#configureIdentityManager threw an exception: java.lang.NullPointerException
Caused by: io.quarkus.builder.BuildException:
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.jwt.deployment.SmallRyeJwtProcessor#configureIdentityManager threw an exception: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
```

And `mvn clean package -DskipTests -DskipITs` fails to produce the jar
```
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ scenario-101-getting-started ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Beta4
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.310 s
[INFO] Finished at: 2019-06-05T10:26:43+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project scenario-101-getting-started: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.smallrye.jwt.deployment.SmallRyeJwtProcessor#configureIdentityManager threw an exception: java.lang.NullPointerException
[ERROR] -> [Help 1]
```

**Comment by sberyozkin** [comment]
[This code](https://github.com/smallrye/smallrye-jwt/blob/1.1.4/implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java#L108) requires either a public key or public key file location.
I will update smallrye-jwt to log something useful there

**Comment by sberyozkin** [comment]
This is what will be shown (as part of the longer trace):
```
2019-06-11 14:18:23,446 ERROR [io.und.req.io] (executor-thread-1) Exception handling request b2431065-f384-44bd-889d-0713277e9131-1 to /secured: java.lang.IllegalStateException: JWTAuthContextInfo has not been initialized. Please make sure that either public key or public key location properties are set
```
Note this message is not referring to the specific property names as there could be few different properties across various containers for configuring the public key. The issuer has to be set up as well unless its check has been disabled but I'm not sure it is necessary to advise configuring it in this exception message, there would be a log warning later if the verification has failed due to the issuer mismatch.

I can tweak this message if you'd like. @starksm64 FYI

**Comment by starksm64** [comment]
@sberyozkin I do think it would be good if we can reference one of the property names so that users can use that to search either the doc or google.

**Comment by sberyozkin** [comment]
@starksm64 Which two properties you'd like to use (such that they work in Quarkus/Thorntail/etc) ?

**Comment by sberyozkin** [comment]
@starksm64 Looks like I was wrong :-) as with Thorntail the smallrye-jwt provider non-optional producer will not be called if the Thorntail specific properties are used, let me check it, and then I'll tweak the message to something like:
"...Please make sure that either **mp.jwt.verify.publickey** or **mp.jwt.verify.publickey.location** properties are set"
thanks

**Comment by gsmet** [comment]
Addressed by https://github.com/smallrye/smallrye-jwt/pull/70 .

**Comment by rsvoboda** [comment]
Double checked as I got confused by https://github.com/quarkusio/quarkus/commit/3e448277f19a24448329efba23a7efc9802b7172 which is 20 days old and fix is 8 days old. Some GH black magic or re-tag and re-release of smallrye-jwt-1.1 had to happen :)

Now I see Quarkus boot in tests and reasonable error message `2019-06-19 10:50:40,837 ERROR [io.und.req.io] (executor-thread-1) Exception handling request 4e195f06-b97a-4504-9f89-22e596ec9f61-1 to /hello: java.lang.IllegalStateException: JWTAuthContextInfo has not been initialized. Please make sure that either public key or public key location properties are set.`

**Comment by sberyozkin** [comment]
FYI, the next smallrye-jwt release will have a [better message](https://github.com/smallrye/smallrye-jwt/blob/master/implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java#L257)

**Comment by sberyozkin** [comment]
NPE caused by the disabled smallrye-jwt property has been fixed directly in Quarkus

**Comment by gintsgints** [comment]
Do we consider this issue as solved?

JWT guide should be updated imho - https://quarkus.io/guides/jwt-guide to close this issue.
