### ISSUE TITLE
Build failure when using quarkus-amazon-lambda and smallrye-jwt extensions

### ISSUE THREAD

**Issue by Felipe-Visgou** [quarkusio/quarkus#27250]
### Describe the bug

I'm trying to build an AWS Lambda application that uses smallrye-jwt dependency to inject JsonWebTokens values into lambda handler. But when building the application, quarkus is unable to index smallrye-jwt dependency properly by saying:
```
Failed to index javax.json.JsonArray: Class does not exist in ClassLoader QuarkusClassLoader
Failed to index javax.json.JsonString: Class does not exist in ClassLoader QuarkusClassLoader
```

I was able to reproduce the error using the minimum of quarkus-amazon-lambda extension and smallrye-jwt dependency directly.

### Expected behavior

A successfully build with no failures when running tests

### Actual behavior

```
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< quarkus-lambda-jwt:lambda-jwt-test >-----------------
[INFO] Building lambda-jwt-test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ lambda-jwt-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ lambda-jwt-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ lambda-jwt-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ lambda-jwt-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M7:test (default-test) @ lambda-jwt-test ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running quarkus.lambda.jwt.LambdaHandlerTest
2022-08-11 11:16:28,491 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
2022-08-11 11:16:29,083 INFO  [io.qua.ama.lam.run.MockEventServer] (build-21) Mock Lambda Event Server Started
2022-08-11 11:16:29,101 WARN  [io.qua.arc.pro.BeanArchives] (build-47) Failed to index javax.json.JsonArray: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: TEST@30bcf3c1
2022-08-11 11:16:29,101 INFO  [io.qua.arc.pro.IndexClassLookupUtils] (build-47) Class for name: javax.json.JsonArray was not found in Jandex index. Please ensure the class is part of the index.
2022-08-11 11:16:29,108 WARN  [io.qua.arc.pro.BeanArchives] (build-47) Failed to index javax.json.JsonString: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: TEST@30bcf3c1
2022-08-11 11:16:29,108 INFO  [io.qua.arc.pro.IndexClassLookupUtils] (build-47) Class for name: javax.json.JsonString was not found in Jandex index. Please ensure the class is part of the index.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.762 s <<< FAILURE! - in quarkus.lambda.jwt.LambdaHandlerTest
[ERROR] quarkus.lambda.jwt.LambdaHandlerTest.testSimpleLambdaSuccess  Time elapsed: 0.011 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.IllegalArgumentException: Producer method return type not found in index: javax.json.JsonString
        at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:280)
        at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1039)
        at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:240)
        at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
        at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:411)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:977)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:698)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:769)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:77)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:355)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:302)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:280)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:272)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:271)
        at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:102)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:101)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:66)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.IllegalArgumentException: Producer method return type not found in index: javax.json.JsonString
        at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:280)
        at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1039)
        at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:240)
        at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
        at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:411)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:977)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:234)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:675)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:713)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
        ... 36 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.IllegalArgumentException: Producer method return type not found in index: javax.json.JsonString
        at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:280)
        at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1039)
        at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:240)
        at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
        at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:411)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:977)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:158)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
        ... 47 more
Caused by: java.lang.IllegalArgumentException: Producer method return type not found in index: javax.json.JsonString
        at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:280)
        at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1039)
        at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:240)
        at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
        at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:411)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:977)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   LambdaHandlerTest.testSimpleLambdaSuccess » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.IllegalArgumentException: Producer method return type not found in index: javax.json.JsonString
        at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:280)
        at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1039)
        at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:240)
        at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:120)
        at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:411)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:977)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.507 s
[INFO] Finished at: 2022-08-11T11:16:29-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project lambda-jwt-test: 
[ERROR] 
[ERROR] Please refer to /home/fcortes/Sensedia/Projects/EventsHub/work_quarkus/lambda-jwt-test/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### How to Reproduce?

To reproduce this error, you must do the following steps:

1. Create a sample [quarkus-amazon-lambda](https://quarkus.io/guides/amazon-lambda) project from Maven archetype:
```
mvn archetype:generate \
       -DarchetypeGroupId=io.quarkus \
       -DarchetypeArtifactId=quarkus-amazon-lambda-archetype \
       -DarchetypeVersion=2.11.2.Final
```
2. Add smallrye-jwt in pom dependency, following :
```
        <dependency>
            <groupId>io.smallrye</groupId>
            <artifactId>smallrye-jwt</artifactId>
        </dependency>
```
3. Index smallrye dependency by adding the property quarkus.index-dependency.smallrye-jwt to application.properties (as described in this[ security guide](https://quarkus.io/guides/security-jwt)):
```
quarkus.index-dependency.smallrye-jwt.group-id=io.smallrye
quarkus.index-dependency.smallrye-jwt.artifact-id=smallrye-jwt
```
4. Build with maven or quarkus:
```
quarkus build
```

### Output of `uname -a` or `ver`

Linux fcortes-XPS-8700 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

penjdk version "11.0.14.1" 2022-02-08 LTS OpenJDK Runtime Environment Corretto-11.0.14.10.1 (build 11.0.14.1+10-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.14.10.1 (build 11.0.14.1+10-LTS, mixed mode)

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0) Maven home: /home/fcortes/.sdkman/candidates/maven/current Java version: 11.0.14.1, vendor: Amazon.com Inc., runtime: /home/fcortes/.sdkman/candidates/java/11.0.14.10.1-amzn Default locale: pt_BR, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-43-generic", arch: "amd64", family: "unix"

### Additional information

I found an workaround by adding the javax.json-api dependency, but I'm afraid this is not the best thing to do because no information is present in the [security-jwt guide](https://quarkus.io/guides/security-jwt) about this:
```
<dependency>
    <groupId>javax.json</groupId>
    <artifactId>javax.json-api</artifactId>
    <version>1.0</version>
</dependency>
```

**Comment by fercomunello** [comment]
> I found an workaround by adding the javax.json-api dependency, but I'm afraid this is not the best thing to do because no information is present in the security-jwt guide about this:

I'm not an expert on this, but yes, I think you can keep this additional dependency in your project for now as Quarkus documentation doesn't say much about Java EE 8 and Jakarta EE 9.

I'll try to clarify this question: the runtime exception occurs because the plain smallrye-jwt dependency has `javax.*` and `jakarta.*` dependencies with a **provided scope**, this means that Smallrye implementation of [MicroProfile specification](https://microprofile.io/) is expecting a implementation for the [Jakarta EE](https://jakarta.ee/specifications/) dependencies, so it doesn't include [JSON-P](https://jakarta.ee/specifications/jsonp/) implementation. That's why your integration test passed after add the JSON-P dependency with **compile scope**, wich is the default scope on Maven.

In traditional Jakarta EE projects, you'll have a parent dependency of the EE and MicroProfile specifications that expects that all implementations are provided by a [compatible application server](https://jakarta.ee/compatibility/) (TCK certified), and then just deploy a thin war (KB size) of the application into the server deployment folder. For example:
```xml
<dependency>
  <groupId>jakarta.platform</groupId>
  <artifactId>jakarta.jakartaee-api</artifactId>
  <version>${jakarta.version}</version>
  <scope>provided</scope>
</dependency>

<dependency>
  <groupId>org.eclipse.microprofile</groupId>
  <artifactId>microprofile</artifactId>
  <version>${microprofile.version}</version>
  <type>pom</type>
  <scope>provided</scope>
</dependency>
```

In legacy Java EE projects you'll see:
```xml
<dependency>
  <groupId>javax</groupId>
  <artifactId>javaee-api</artifactId>
  <version>${ee.version}</version>
  <scope>provided</scope>
</dependency>
```

An application server like WildFly contains EE and SmallRye implementations, the difference is that in Quarkus we have built-in extensions that run Ahead of Time Compilation (AOT) to optimize the code as much as possible, so always prefer to add an extension of a dependency.

As @mkouba said in this [blog post](https://quarkus.io/blog/quarkus-dependency-injection/#compatibility): 

> Quarkus ArC is not a full CDI implementation verified by TCK - see also the list of [supported features](https://quarkus.io/guides/cdi-reference#supported_features) and the list of [limitations](https://quarkus.io/guides/cdi-reference#limitations).

If you want know more about the Quarkus approach to migrate from `javax` to `jakarta` namespace, take a look on this comment of @gsmet explaning about the migration: https://github.com/quarkusio/quarkus/issues/21574#issuecomment-1079733970. Quarkus probably will migrate all extensions to Jakarta EE 10 when it's possible, so in the future you should change `javax.json-api `dependency to:

```xml
<dependency>
  <groupId>jakarta.json</groupId>
  <artifactId>jakarta.json-api</artifactId>
</dependency>
```

A short history of Quarkus and Java EE:
https://developers.redhat.com/blog/2020/09/11/quarkus-and-jakarta-ee-together-or-not

**Comment by Felipe-Visgou** [comment]
Thank you @fercomunello for your explanation. Now I understand better Quarkus relationship between traditional Java EE projects.

I suppose we can close this issue since it's not a bug. Although it may be handy for people who bump into this scenario.
