### ISSUE TITLE
Broken access in openapi and swagger-ui extensions

### ISSUE THREAD

**Issue by clochardpagan** [quarkusio/quarkus#2726]
**Describe the bug**
Openapi and swagger-ui intergrations are broken. https://github.com/quarkusio/quarkus-quickstarts/tree/master/using-openapi-swaggerui is also broken. It starts up, but /openapi endpoint and /swagger-ui respond with errors.

**Expected behavior**
Cool openapi and swagger pages, heh

**Symptoms**
Adding config key resolves problem in production env, but dev still errors.
```
quarkus.swagger-ui.always-include=true
```
Also it's strange that when I'm not adding this line, openapi is still available in production - not sure how safe is this.

**Openapi error info**
```
Context Path:
Servlet Path: /openapi
Path Info: null
Query String: null

Stack Trace:
java.io.FileNotFoundException: /quarkus-generated-openapi-doc.YAML
	at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:173)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:81)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:274)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToServlet(ServletInitialHandler.java:219)
	at io.undertow.servlet.spec.RequestDispatcherImpl.includeImpl(RequestDispatcherImpl.java:392)
	at io.undertow.servlet.spec.RequestDispatcherImpl.setupIncludeImpl(RequestDispatcherImpl.java:327)
	at io.undertow.servlet.spec.RequestDispatcherImpl.include(RequestDispatcherImpl.java:291)
	at io.quarkus.smallrye.openapi.runtime.OpenApiServlet.doGet(OpenApiServlet.java:65)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:91)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentTemplate$7$1$1.call(UndertowDeploymentTemplate.java:469)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:197)
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:65)
	at io.quarkus.undertow.runtime.UndertowDeploymentTemplate$1.handleRequest(UndertowDeploymentTemplate.java:104)
	at io.undertow.server.handlers.CanonicalPathHandler.handleRequest(CanonicalPathHandler.java:49)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup.handleHotDeploymentRequest(UndertowHotReplacementSetup.java:77)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup$1$1.handleRequest(UndertowHotReplacementSetup.java:56)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1429)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:32)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**To Reproduce**
1. clone https://github.com/quarkusio/quarkus-quickstarts
2. cd /using-openapi-swaggerui/
3. ./mvnw compile quarkus:dev
4. http://localhost:8080/openapi - BANG
5. http://localhost:8080/swagger-ui - TWO TIME BANG :)

**Environment**
 - OpenSUSE Tumbleweed, kernel  5.1.3-1
 - JVM Version: Zulu 8.36.0.1
 - Quarkus 0.16.0: 

**Linked issue in this repo**
https://github.com/quarkusio/quarkus/issues/2597
**Linked issue in this quarkus-quickstarts repo**
https://github.com/quarkusio/quarkus-quickstarts/issues/207
**Probable cause**
https://github.com/quarkusio/quarkus/commit/4dcb8131f8018a46ddf098bd5c14beb4aa230404 - this commit added ability to enable swagger-ui in production env, and there was a lot of code, so some bug ought to be there.

**Comment by gsmet** [comment]
@clochardpagan when you say `Also it's strange that when I'm not adding this line, openapi is still available in production - not sure how safe is this.`, we agree that you're only talking about openapi, not Swagger UI?

The OpenAPI extension has always been designed to be, well, open. Only Swagger UI is limited to dev mode if you don't explicitly enable it.

**Comment by gsmet** [comment]
@stuartwdouglas so my understanding is that the `wiring-classes` directory is not part of the directories handled by the `RuntimeClassLoader` because in dev mode we explicitly target `wiring-devmode` as the wiring directory (we have a few classes generated there but most of them are in `wiring-classes`).

Not sure how to handle this: is it better to add `wiring-classes` to the `applicationClassesDirectories` or should it be handled by the parent class loader and added as an additional `frameworkClassesPath`.

FWIW, a quick and dirty:
```
diff --git a/core/deployment/src/main/java/io/quarkus/runner/RuntimeRunner.java b/core/deployment/src/main/java/io/quarkus/runner/RuntimeRunner.java
index 6aa728dc4..5ae154fbf 100644
--- a/core/deployment/src/main/java/io/quarkus/runner/RuntimeRunner.java
+++ b/core/deployment/src/main/java/io/quarkus/runner/RuntimeRunner.java
@@ -65,6 +65,7 @@ public class RuntimeRunner implements Runnable, Closeable {
         if (builder.classOutput == null) {
             List<Path> allPaths = new ArrayList<>();
             allPaths.add(target);
+            allPaths.add(target.resolveSibling("wiring-classes"));
             allPaths.addAll(builder.additionalHotDeploymentPaths);
             RuntimeClassLoader runtimeClassLoader = new RuntimeClassLoader(builder.classLoader, allPaths,
                     builder.frameworkClassesPath, builder.transformerCache);
```
fixes the issue so I think I narrowed down the problem properly.

Related commit: https://github.com/quarkusio/quarkus/commit/71c0fab3d8bf15e6916d1f66f9762ed71c1f499d#diff-18d7de733155491f3c70b1a59b849776L208

BTW, a comment explaining why we have this specific wiring directory for dev mode would help.
