### ISSUE TITLE
Gradle 7.5 fails to finish integration-tests/gradle due to jandex incompatibility

### ISSUE THREAD

**Issue by jskillin-idt** [quarkusio/quarkus#27260]
### Describe the bug

Hopefully this is an easy fix.

`io.quarkus.gradle.devmode.JandexMultiModuleProjectDevModeTest` fails with the following stack:
```
BUILD FAILED in 5s
BELOW IS THE CAPTURED LOGGING OF THE FAILED GRADLE TEST PROJECT BUILD
Exception in thread "main" java.lang.NoClassDefFoundError: org/gradle/internal/classpath/Instrumented
	at org.kordamp.gradle.plugin.jandex.tasks.JandexMain$ClassFileVisitor.indexFile(JandexMain.java:172)
	at org.kordamp.gradle.plugin.jandex.tasks.JandexMain$ClassFileVisitor.visitFile(JandexMain.java:160)
	at org.kordamp.gradle.plugin.jandex.tasks.JandexMain$ClassFileVisitor.visitFile(JandexMain.java:147)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
	at org.kordamp.gradle.plugin.jandex.tasks.JandexMain.execute(JandexMain.java:98)
	at org.kordamp.gradle.plugin.jandex.tasks.JandexMain.run(JandexMain.java:124)
	at org.kordamp.gradle.plugin.jandex.tasks.JandexMain.main(JandexMain.java:111)
Caused by: java.lang.ClassNotFoundException: org.gradle.internal.classpath.Instrumented
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 8 more
```

I believe this is because of https://github.com/kordamp/jandex-gradle-plugin/issues/18 which was fixed in a v0.13.0 release of that plugin. I bumped the version to v0.13.2 and that appeared to resolve this error.

### How to Reproduce?

1. Patch the gradle wrapper for integration tests to use 7.5.x:
```patch
--- a/integration-tests/gradle/gradle/wrapper/gradle-wrapper.properties
+++ b/integration-tests/gradle/gradle/wrapper/gradle-wrapper.properties
@@ -1,5 +1,5 @@
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-bin.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-bin.zip
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
```
2. Run `./mvnw -Dmaven.repo.local=$HOME/.m2.quarkus -Dquickly && ./mvnw -Dmaven.repo.local=$HOME/.m2.quarkus -f integration-tests/gradle/ install` (The `maven.repo.local` bit is extra but I find Maven can get squirrely when there's a lot of random builds packed into the local repo.)

### Output of `uname -a` or `ver`

Linux jacob-ubuntu-dev 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment (build 17.0.4+8-Ubuntu-122.04) OpenJDK 64-Bit Server VM (build 17.0.4+8-Ubuntu-122.04, mixed mode, sharing)

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by jskillin-idt** [comment]
This issue doesn't actually affect the consumer of Quarkus, in the sense that a release of Quarkus is not required to resolve this issue, but I thought you'd want to know since whenever you decide to bump Gradle for internal Quarkus development, you will hit this issue.

**Comment by glefloch** [comment]
I think this is already handled in master. 
I bump gradle to 7.5 when it came out and also bump for jandex 0.13.0 at that time.

**Comment by jskillin-idt** [comment]
Oh, look at that. Awesome. You're already on top of it.

**Comment by pipinet** [comment]
same issues.

**Comment by pipinet** [comment]
upgrade gradle plugin org.kordamp.gradle.jandex to 1.0.0
