### ISSUE TITLE
uuidRepresentation not passed to CodeRegistry of MongoCollection behind a Panache repo

### ISSUE THREAD

**Issue by languitar** [quarkusio/quarkus#27269]
### Describe the bug

When using Panache with MongoDB, the underlying MongoCollection behind and Entity or the repository abstractions is accessible for special needs. In my case, I am using UUIDs in MongoDB documents. To work properly, MongoDB requires the `uuidRepresentation` connection parameter to be present. For tests and the dev mode, this is realized by specifying this property:

```ini
quarkus.mongodb.devservices.properties.uuidRepresentation = STANDARD
```

That way, I can handle entities containing UUIDs without problem. However, as soon as I try to use underlying MongoCollection instance, the configured UUID representation doesn't seem to be propagated there and operations using UUIDs fail with a message indicating that the representation is not configured.

### Expected behavior

The CodecRegistry used by MongoCollections behind Panache entities is configured with a UUID representation.

### Actual behavior

No UUID representation is configured, resulting in exceptions like the following:

```
2022-08-12 12:43:49,557 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: org.bson.codecs.configuration.CodecConfigurationException: The uuidRepresentation has not been specified, so the UUID cannot be encoded.
	at org.bson.codecs.UuidCodec.encode(UuidCodec.java:72)
	at org.bson.codecs.UuidCodec.encode(UuidCodec.java:37)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:210)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:168)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:44)
	at org.bson.internal.LazyCodec.encode(LazyCodec.java:38)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:210)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:168)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:44)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:221)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:187)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:77)
	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:170)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:138)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:63)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:325)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:644)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:240)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:226)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:126)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:354)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:517)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:379)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$2(MixedBulkWriteOperation.java:300)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:575)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:600)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:574)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:600)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:573)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$3(MixedBulkWriteOperation.java:272)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:308)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:85)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:212)
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1010)
	at com.mongodb.client.internal.MongoCollectionImpl.executeUpdate(MongoCollectionImpl.java:994)
	at com.mongodb.client.internal.MongoCollectionImpl.updateMany(MongoCollectionImpl.java:625)
	at com.mongodb.client.internal.MongoCollectionImpl.updateMany(MongoCollectionImpl.java:620)
	at org.acme.mongodb.panache.repository.PersonResource.bug(PersonResource.java:28)
	at org.acme.mongodb.panache.repository.PersonResource_Subclass.bug$$superforward1(Unknown So
```

### How to Reproduce?

https://github.com/languitar/quarkus-mongodb-uuidRepresentation-reproducer

1. launch the project in dev mode
2. `curl -v http://localhost:8080/repository/persons/bug`

The endpoint behind this shows that an entity with UUID can be managed using the high-level panache concepts, but not with direct MongoDB commands: https://github.com/languitar/quarkus-mongodb-uuidRepresentation-reproducer/blob/main/src/main/java/org/acme/mongodb/panache/repository/PersonResource.java#L21

### Output of `uname -a` or `ver`

Linux pres 5.15.59-2-lts #1 SMP Sat, 06 Aug 2022 21:34:17 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.16" 2022-07-19

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by evanchooly** [comment]
i don't see anything in the code like this:  `quarkus.mongodb.devservices.properties.uuidRepresentation`.  Where did you get that property name?  AFAICT, there is nothing about UUID support in the code but would be trivial to add.

**Comment by languitar** [comment]
This option actually works perfectly fine with Panache. This is the map documented as the last property here: https://quarkus.io/guides/mongodb#quarkus-mongodb-config-group-dev-services-build-time-config_configuration

**Comment by evanchooly** [comment]
Does it work or does it just not complain about that property? Because if i'm reading the code correctly, it just takes those key/value pairs and stuffs them in to a map.  It doesn't validate them and I don't see anything that takes the UUID setting and applies it in the client settings.

**Comment by languitar** [comment]
Yes, this actually works. Without this property, persisting the initial entity in the example project already crashes with the following error:

```
2022-08-16 09:42:24,046 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: org.bson.codecs.configuration.CodecConfigurationException: An exception occurred when encoding using the AutomaticPojoCodec.
Encoding a Person: 'org.acme.mongodb.panache.repository.Person@2c5760f2' failed with the following exception:

Failed to encode 'Person'. Encoding 'uuid' errored with: The uuidRepresentation has not been specified, so the UUID cannot be encoded.

A custom Codec or PojoCodec may need to be explicitly configured and registered to handle this type.
	at org.bson.codecs.pojo.AutomaticPojoCodec.encode(AutomaticPojoCodec.java:53)
	at io.quarkus.mongodb.panache.common.runtime.MongoOperations.getBsonDocument(MongoOperations.java:315)
	at io.quarkus.mongodb.panache.common.runtime.MongoOperations.persistOrUpdate(MongoOperations.java:253)
	at io.quarkus.mongodb.panache.common.runtime.MongoOperations.persistOrUpdate(MongoOperations.java:147)
	at io.quarkus.mongodb.panache.PanacheMongoRepositoryBase.persistOrUpdate(PanacheMongoRepositoryBase.java:65)
	at org.acme.mongodb.panache.repository.PersonRepository_Subclass.persistOrUpdate$$superforward1(Unknown Source)
	at org.acme.mongodb.panache.repository.PersonRepository_Subclass$$function$$58.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.mongodb.panache.repository.PersonRepository_Subclass.persistOrUpdate(Unknown Source)
	at org.acme.mongodb.panache.repository.PersonRepository_ClientProxy.persistOrUpdate(Unknown Source)
	at org.acme.mongodb.panache.repository.PersonResource.bug(PersonResource.java:25)
	at org.acme.mongodb.panache.repository.PersonResource_Subclass.bug$$superforward1(Unknown Source)
	at org.acme.mongodb.panache.repository.PersonResource_Subclass$$function$$1.apply(Unknown Source)
```

This works, because the map from the config is added as query parameters to the MongoDB URI in the property `quarkus.mongodb.connection-string`. In my case, this results in `mongodb://localhost:49158/persons?uuidRepresentation=STANDARD`, which can be verified in the config editor in dev mode. The MongoDB driver picks this up automatically, in theory.

**Comment by evanchooly** [comment]
ok.  that makes sense.  thanks.  i'll take a look.

**Comment by languitar** [comment]
Btw, there's the possibility that this is caused by a MongoDB Java driver bug. Something sounding pretty similar should be fixed in the version pulled into this project, though: https://jira.mongodb.org/browse/JAVA-4450

**Comment by evanchooly** [comment]
OK.  I've finally tracked down the problem.  Where you're going wrong is calling `toBsonDocument()` directly.  When you do this you're using the default codec registry as defined by the driver and not the one configured by your quarkus configuration.  There is an overload where you can pass in the `CodecRegistry` to use but that's unnecessary here.  In your reproducer, if you completely remove the `toBsonDocument()` call, your test application should work just fine.

Give that a try and see what you get.

**Comment by languitar** [comment]
Thanks for the feedback. There was a reason why I couldn't go without the BSON version. But I can't remember that reason. In any case, this seems to be more a problem of the MongoDB driver design than of the Quarkus integration. Thanks for investigating this.

**Comment by evanchooly** [comment]
if you still need that `BsonDocument` approach, consider making the call like this:

`.toBsonDocument(Document.class, personRepository.mongoCollection().getCodecRegistry())`
