### ISSUE TITLE
Improper shutdown exception

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2728]
Upon quarkus:dev mode shutdown via CTRL+C, I receive the following error

```
mvn compile quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.issue_2482:reproducer >----------------------
[INFO] Building reproducer 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ reproducer ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ reproducer ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:dev (default-cli) @ reproducer ---
Listening for transport dt_socket at address: 5005
2019-06-05 11:16:10,209 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-06-05 11:16:10,982 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 773ms
2019-06-05 11:16:11,298 INFO  [io.qua.swa.run.SwaggerUiServletExtension] (main) Swagger UI available at /swagger-ui
2019-06-05 11:16:11,993 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 1.927s. Listening on: http://[::]:8080
2019-06-05 11:16:11,995 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, narayana-jta, resteasy, resteasy-jsonb, smallrye-openapi, swagger-ui]
^C2019-06-05 11:16:25,986 ERROR [io.qua.run.StartupContext] (Quarkus Shutdown Thread) Running a shutdown task failed: java.util.concurrent.RejectedExecutionException
        at org.jboss.threads.RejectingExecutor.execute(RejectingExecutor.java:38)
        at org.jboss.threads.EnhancedQueueExecutor.rejectShutdown(EnhancedQueueExecutor.java:2055)
        at org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:765)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at io.quarkus.runtime.CleanableExecutor.submit(CleanableExecutor.java:122)
        at io.quarkus.runtime.CleanableExecutor.clean(CleanableExecutor.java:67)
        at io.quarkus.runtime.ExecutorTemplate$1.run(ExecutorTemplate.java:63)
        at io.quarkus.runtime.StartupContext.close(StartupContext.java:59)
        at io.quarkus.runner.ApplicationImpl1.doStop(Unknown Source)
        at io.quarkus.runtime.Application.stop(Application.java:167)
        at io.quarkus.runner.RuntimeRunner$1.close(RuntimeRunner.java:138)
        at io.quarkus.runner.RuntimeRunner.close(RuntimeRunner.java:84)
        at io.quarkus.dev.DevModeMain$1.run(DevModeMain.java:113)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.util.concurrent.RejectedExecutionException: Executor is being shut down
                at org.jboss.threads.EnhancedQueueExecutor.rejectShutdown(EnhancedQueueExecutor.java:2057)
                ... 12 more

2019-06-05 11:16:25,991 INFO  [io.quarkus] (Quarkus Shutdown Thread) Quarkus stopped in 0.009s
```

The app uses the extensions mentioned in the log and connect to H2 server.

```
quarkus.datasource.url=jdbc:h2:tcp://localhost/~/Downloads/nobackup/test
quarkus.datasource.driver=org.h2.Driver
quarkus.datasource.username=sa
quarkus.datasource.password=

quarkus.hibernate-orm.database.generation=update
```

**Comment by gsmet** [comment]
It looks a lot like https://github.com/quarkusio/quarkus/issues/2699 but people told me it was only in the context of context propagation.

**Comment by gsmet** [comment]
@mkouba can you take a look at that one? Seems highly related to the issue I mention above.

**Comment by gsmet** [comment]
Hmmm, well, you also have the context propagation extension. It's just that the extension is not advertised in the extension list.

**Comment by mkouba** [comment]
Yes, I believe this duplicates https://github.com/quarkusio/quarkus/issues/2699. And I'd bet it's a context propagation bug.

**Comment by FroMage** [comment]
Only if you show me a stack trace involving CP. I don't see FT, don't see CP, don't see RxJava… The list of extensions does not point to that.

**Comment by geoand** [comment]
I tried this just out of curiosity on the simplest `getting-started` quickstart and saw the problem

**Comment by FroMage** [comment]
This is the code which submits the executors:

```java
        //this is a hack, basically just submit a heap of tasks to the pool in order to try and clean up all
        //threadlocal state. It does not really matter if this does not work, however if these threads are holding
        //state that is stopping things being GC'ed it can help with memory usage
        try {
            for (int i = 0; i < executor.getMaximumPoolSize(); ++i) {
                submit(empty);
            }
        } finally {
            latch.countDown();
        }
```

This is why there's no stack trace to display. I really don't see how this is related to CP.

**Comment by FroMage** [comment]
I guess this is an issue for @stuartwdouglas  then. I don't know how to fix it.
