### ISSUE TITLE
custom subclass for PanacheEntityBase and can't invoke findById

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#27303]
### Describe the bug

i implement subclass named `AbstractSnowflakeEntity` of `PanacheEntityBase`.

when i use it to be superclass and invoke `findById`,it error. `This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?`

```java
@MappedSuperclass
public abstract class AbstractSnowflakeEntity extends PanacheEntityBase implements PO<Long>, VersionPO {
    @Id
    @GenericGenerator(name = "snowflake", strategy = "com.mindflow.common.id.snowflake.data.SnowflakeIdentifierGenerator")
    @GeneratedValue(generator = "snowflake")
    public Long id;

    @Version
    @ColumnDefault("0")
    @Comment("乐观锁版本")
    public Integer version;

    @Comment("是否删除")
    @ColumnDefault("0")
    public Integer deleted;

    @CreationTimestamp
    @Comment("创建时间")
    public LocalDateTime createTime;

    @UpdateTimestamp
    @Comment("修改时间")
    public LocalDateTime updateTime;

    @Comment("创建人")
    public Long createUserId;

    @Comment("修改人")
    public Long lastUpdateUserId;

...
```

extend `AbstractSnowflakeEntity`
```java
@Entity
@Table(name = "notify_template")
public class NotifyTemplatePO extends AbstractSnowflakeEntity {

    @Column(nullable = false)
    @Comment("模板类型")
    public NotifyTemplatelType type;

    @Column(nullable = false)
    @Comment("标题模板")
    public String titleTemplate;

    @Column(nullable = false)
    @Comment("内容模板")
    public String contentTemplate;

}
```

when i use `NotifyTemplatePO.findById`,it error,the log is below

```log
2022-08-16 15:35:44,954 ERROR [com.min.com.exc.rep.htt.AbstractHttpExceptionReporter] (executor-thread-1) catch in global exception handler: java.lang.IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.implementationInjectionMissing(AbstractJpaOperations.java:426)
	at io.quarkus.hibernate.orm.panache.PanacheEntityBase.findById(PanacheEntityBase.java:115)
	at com.mindflow.notify.domain.template.service.NotifyTemplateDomainService.get(NotifyTemplateDomainService.java:29)
	at com.mindflow.notify.domain.template.service.NotifyTemplateDomainService_Subclass.get$$superforward1(Unknown Source)
	at com.mindflow.notify.domain.template.service.NotifyTemplateDomainService_Subclass$$function$$3.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:49)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:49)
	at com.mindflow.cache.redisson.core.interceptor.CacheResultInterceptor.intercept(CacheResultInterceptor.java:58)
	at com.mindflow.cache.redisson.core.interceptor.CacheResultInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.mindflow.notify.domain.template.service.NotifyTemplateDomainService_Subclass.get(Unknown Source)
	at com.mindflow.notify.domain.template.service.NotifyTemplateDomainService_ClientProxy.get(Unknown Source)
	at com.mindflow.notify.application.template.NotifyTemplateService.getOne(NotifyTemplateService.java:32)
	at com.mindflow.notify.application.template.NotifyTemplateService_Subclass.getOne$$superforward1(Unknown Source)
	at com.mindflow.notify.application.template.NotifyTemplateService_Subclass$$function$$3.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.mindflow.notify.application.template.NotifyTemplateService_Subclass.getOne(Unknown Source)
	at com.mindflow.notify.application.template.NotifyTemplateService_ClientProxy.getOne(Unknown Source)
	at com.mindflow.notify.interfaces.facade.service.NotifyTemplateRemoteServiceImpl.getOne(NotifyTemplateRemoteServiceImpl.java:26)
	at com.mindflow.notify.interfaces.facade.service.NotifyTemplateRemoteServiceImpl_Subclass.getOne$$superforward1(Unknown Source)
	at com.mindflow.notify.interfaces.facade.service.NotifyTemplateRemoteServiceImpl_Subclass$$function$$3.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.mindflow.notify.interfaces.facade.service.NotifyTemplateRemoteServiceImpl_Subclass.getOne(Unknown Source)
	at com.mindflow.notify.interfaces.facade.service.NotifyTemplateRemoteService$quarkusrestinvoker$getOne_125b4646c68ee22c9a62d11e094c018bceeb4e96.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Expected behavior

it can work.

### Actual behavior

custom class of `PanacheEntityBase` can't use `findById`.
it can't be proxyed

### Output of `uname -a` or `ver`

win11 and mac

### Output of `java -version`

java17

### GraalVM version (if different from Java)

22.1

### Quarkus version or git rev

2.10.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.4

**Comment by loicmathieu** [comment]
@naah69 can you provide a reproducer please ?
Abstract entity shoyld works with Panache.

**Comment by naah69** [comment]
> @naah69 can you provide a reproducer please ? Abstract entity shoyld works with Panache.

i had found the problem.the abstract entity was in jar.so it can't be indexed.i add `IndexDependencyBuildItem` and it worked.
