### ISSUE TITLE
[2.12.0.CR1]: `/q/dev` UI throws an error when navigating to "Configuration" -> "Config Editor", and "Devservices" is empty 

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#27345]
### Describe the bug

1) Starting here:

![image](https://user-images.githubusercontent.com/26604994/185231479-1d9e7470-59dc-491c-9e64-44a6b6770b7d.png)

2) Click `Config Editor`, see this:

<details>
<summary>CLICK TO VIEW STACKTRACE</summary>

```java
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at io.quarkus.vertx.http.runtime.devmode.ConfigDescriptionsManager.calculate(ConfigDescriptionsManager.java:100)
	at io.quarkus.vertx.http.runtime.devmode.ConfigDescriptionsManager.values(ConfigDescriptionsManager.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.qute.GetterAccessor.getValue(GetterAccessor.java:22)
	at io.quarkus.qute.ReflectionValueResolver.resolve(ReflectionValueResolver.java:59)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:207)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:127)
	at io.quarkus.qute.EvaluatorImpl.lambda$evaluate$0(EvaluatorImpl.java:74)
	at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:232)
	at io.quarkus.qute.EvaluatorImpl.evaluate(EvaluatorImpl.java:72)
	at io.quarkus.qute.ResolutionContextImpl$ChildResolutionContext.evaluate(ResolutionContextImpl.java:87)
	at io.quarkus.qute.LoopSectionHelper.resolve(LoopSectionHelper.java:44)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:182)
	at io.quarkus.qute.InsertSectionHelper.resolve(InsertSectionHelper.java:20)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:182)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:46)
	at io.quarkus.qute.Parser$1.resolve(Parser.java:1230)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.IncludeSectionHelper.lambda$resolve$1(IncludeSectionHelper.java:63)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:144)
	at io.quarkus.qute.IncludeSectionHelper.resolve(IncludeSectionHelper.java:47)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:178)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:46)
	at io.quarkus.qute.Parser$1.resolve(Parser.java:1230)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderData(TemplateImpl.java:176)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsyncNoTimeout(TemplateImpl.java:167)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsync(TemplateImpl.java:140)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.renderTemplate(DevConsole.java:173)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.handle(DevConsole.java:137)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.handle(DevConsole.java:39)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.deployment.devmode.console.FlashScopeHandler.handle(FlashScopeHandler.java:12)
	at io.quarkus.vertx.http.deployment.devmode.console.FlashScopeHandler.handle(FlashScopeHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:250)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:68)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor$2$1.handle(DevConsoleProcessor.java:193)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor$2$1.handle(DevConsoleProcessor.java:190)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.EventLoopContext.lambda$emit$1(EventLoopContext.java:62)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Resulted in: java.lang.reflect.InvocationTargetException
	... 64 more
Resulted in: java.lang.IllegalStateException: Reflection invocation error
	at io.quarkus.qute.GetterAccessor.getValue(GetterAccessor.java:29)
	... 59 more
Resulted in: io.quarkus.qute.TemplateException
	at io.quarkus.qute.CompletedStage.get(CompletedStage.java:48)
	at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
	at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.lambda$renderData$5(TemplateImpl.java:182)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:144)
	... 32 more
Resulted in: java.util.concurrent.CompletionException: io.quarkus.qute.TemplateException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:144)
	... 31 more
```

</details>

![image](https://user-images.githubusercontent.com/26604994/185231542-1792ce85-b618-4663-a4ad-037a808b6fc1.png)

3) Click `Dev Services`, receive empty page:

![image](https://user-images.githubusercontent.com/26604994/185231755-3bb5332a-0ba5-4d26-8035-cda1c0309942.png)

### How to Reproduce?

Here are the Quarkus-related deps:

```kotlin
dependencies {
    implementation(platform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
    implementation("io.quarkus:quarkus-agroal")
    implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-cache")
    implementation("io.quarkus:quarkus-container-image-docker")
    implementation("io.quarkus:quarkus-kotlin")
    implementation("io.quarkus:quarkus-reactive-routes")
    implementation("io.quarkus:quarkus-resteasy-reactive")
    implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.3")
    implementation("io.quarkus:quarkus-smallrye-fault-tolerance")
    implementation("io.quarkus:quarkus-smallrye-openapi")
    implementation("io.quarkus:quarkus-smallrye-opentracing")
    implementation("io.quarkus:quarkus-vertx")
    implementation("io.quarkus:quarkus-vertx-graphql")
    implementation("io.quarkiverse.loggingmanager:quarkus-logging-manager:2.1.4")
    implementation("io.opentracing.contrib:opentracing-jdbc")
    listOf("h2", "mariadb", "mssql", "mysql", "oracle", "postgresql").forEach {
        implementation("io.quarkus:quarkus-jdbc-${it}")
    }
}
```

### Output of `java -version`

17

### Quarkus version or git rev

2.12.0.CR1

**Comment by GavinRay97** [comment]
On the bright side -- I can't believe this is the only bug I've (so far) ran into testing the upgrade from `2.10.2.Final`!
Especially considering the Kotlin 1.6 -> 1.7 change.

I consider that pretty darn good 🙂

**Comment by gsmet** [comment]
Any chance you could put together a small reproducer?

**Comment by GavinRay97** [comment]
Yeah let me try to do this after work today 👍
Will need to rip a bunch of sensitive stuff out

**Comment by gsmet** [comment]
I wasn't able to reproduce it locally with a quickstart so there's something specific to the extensions you are using or your config.

**Comment by gsmet** [comment]
@GavinRay97 were you able to isolate this thing? We're supposed to build the Final core artifacts tomorrow so if we want this fixed, we would need a reproducer like... now... :)

**Comment by GavinRay97** [comment]
Alright, I've managed to reproduce it, please try `./gradlew quarkusDev` and then clicking `Config Editor` from the `/q/dev` UI

[reproducer.zip](https://github.com/quarkusio/quarkus/files/9404435/reproducer.zip)

**Comment by gsmet** [comment]
@phillip-kruger could you have a look now that we have a reproducer? ^

**Comment by phillip-kruger** [comment]
On it

**Comment by phillip-kruger** [comment]
The reproducer works fine for me ! @GavinRay97 any more info you can share ?

**Comment by phillip-kruger** [comment]
It's probably a property that is specific to your environment, like OS. What OS are you running ? Can you test your reproducer on another OS ?

**Comment by GavinRay97** [comment]
Man that is super strange, if nobody can reproduce this we should close it I think

**Comment by phillip-kruger** [comment]
I think it still could be an issue. Some of the "config" we display on that page is OS specific (System properties) so it could be your OS. Are you using Windows / Mac ?

**Comment by GavinRay97** [comment]
I'm using Windows 11:

![image](https://user-images.githubusercontent.com/26604994/186297678-95368fda-5b6a-4651-9c81-c266f7c00671.png)

**Comment by phillip-kruger** [comment]
Ok, so that might be why we can not recreate it. Can you share all the System.getProperties with their values on your example, then I can see if I can recreate the issue ?

**Comment by GavinRay97** [comment]
Sure, let me try to echo that out 👍

**Comment by GavinRay97** [comment]
Here you are:

```java
@GET
@Produces(MediaType.TEXT_PLAIN)
public String hello() throws JsonProcessingException {
    Properties systemProperties = System.getProperties();
    return new ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(systemProperties);
}
```

```json
{
  "java.specification.version": "17",
  "sun.cpu.isalist": "amd64",
  "sun.jnu.encoding": "Cp1252",
  "java.class.path": "C:\\Users\\rayga\\Downloads\\code-with-quarkus (13)\\code-with-quarkus\\build\\code-with-quarkus-dev.jar",
  "java.vm.vendor": "GraalVM Community",
  "quarkus-internal-test.serialized-app-model.path": "C:\\Users\\rayga\\Downloads\\code-with-quarkus (13)\\code-with-quarkus\\build\\tmp\\quarkusDev\\quarkus-app-test-model.dat",
  "sun.arch.data.model": "64",
  "user.variant": "",
  "java.vendor.url": "https://www.graalvm.org/",
  "user.timezone": "America/New_York",
  "java.vm.specification.version": "17",
  "os.name": "Windows 11",
  "sun.java.launcher": "SUN_STANDARD",
  "user.country": "US",
  "mp.openapi.extensions.smallrye.defaultProduces": "application/json",
  "sun.boot.library.path": "C:\\GraalVM\\graalvm-ce-java17-22.2.0\\bin",
  "sun.java.command": "C:\\Users\\rayga\\Downloads\\code-with-quarkus (13)\\code-with-quarkus\\build\\code-with-quarkus-dev.jar",
  "jdk.debug": "release",
  "JAEGER_SERVICE_NAME": "code-with-quarkus",
  "sun.cpu.endian": "little",
  "user.home": "C:\\Users\\rayga",
  "user.language": "en",
  "org.gradle.appname": "gradlew",
  "vertxweb.environment": "dev",
  "io.quarkus.force-color-support": "true",
  "java.specification.vendor": "Oracle Corporation",
  "io.netty.allocator.maxOrder": "3",
  "java.version.date": "2022-07-19",
  "java.home": "C:\\GraalVM\\graalvm-ce-java17-22.2.0",
  "file.separator": "\\",
  "java.vm.compressedOopsMode": "Zero based",
  "jdk.internal.vm.ci.enabled": "true",
  "line.separator": "\r\n",
  "java.vm.specification.vendor": "Oracle Corporation",
  "java.specification.name": "Java Platform API Specification",
  "java.nio.channels.DefaultThreadPool.threadFactory": "io.quarkus.dev.io.NioThreadPoolThreadFactory",
  "user.script": "",
  "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
  "java.runtime.version": "17.0.4+8-jvmci-22.2-b06",
  "user.name": "rayga",
  "com.mysql.cj.disableAbandonedConnectionCleanup": "true",
  "path.separator": ";",
  "os.version": "10.0",
  "java.runtime.name": "OpenJDK Runtime Environment",
  "file.encoding": "Cp1252",
  "java.vm.name": "OpenJDK 64-Bit Server VM",
  "java.vendor.version": "GraalVM CE 22.2.0",
  "java.vendor.url.bug": "https://github.com/oracle/graal/issues",
  "java.io.tmpdir": "C:\\Users\\rayga\\AppData\\Local\\Temp\\",
  "java.version": "17.0.4",
  "java.util.concurrent.ForkJoinPool.common.threadFactory": "io.quarkus.bootstrap.forkjoin.QuarkusForkJoinWorkerThreadFactory",
  "user.dir": "C:\\Users\\rayga\\Downloads\\code-with-quarkus (13)\\code-with-quarkus\\build\\classes\\java\\main",
  "os.arch": "amd64",
  "java.vm.specification.name": "Java Virtual Machine Specification",
  "vertx.disableDnsResolver": "true",
  "sun.os.patch.level": "",
  "native.encoding": "Cp1252",
  "java.util.logging.manager": "org.jboss.logmanager.LogManager",
  "java.library.path": "C:\\GraalVM\\graalvm-ce-java17-22.2.0\\bin;C:\\WINDOWS\\Sun\\Java\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\Users\\rayga\\AppData\\Roaming\\ActiveState\\bin;C:\\GraalVM\\graalvm-ce-java17-22.2.0\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\D\\dmd2\\windows\\bin;C:\\Gradle\\gradle-7.6-20220805221950+0000\\bin;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\kaitai-struct-compiler\\bin;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Strawberry\\c\\bin;C:\\Strawberry\\perl\\site\\bin;C:\\Strawberry\\perl\\bin;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Users\\rayga\\.cargo\\bin;C:\\Users\\rayga\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\rayga\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin;C:\\Program Files (x86)\\GitHub CLI\\;C:\\Users\\rayga\\.local\\bin;C:\\apache-maven-3.8.4\\bin;C:\\Users\\rayga\\AppData\\Roaming\\npm;C:\\Program Files\\PostgreSQL\\14\\bin;C:\\WiresharkPortable64\\App\\Wireshark;C:\\msys64\\clang64\\bin;C:\\z3\\z3-4.8.17-x64-win\\bin;C:\\Users\\rayga\\AppData\\Local\\JetBrains\\Toolbox\\scripts;C:\\Strawberry\\perl\\bin;;.",
  "java.vm.info": "mixed mode, sharing",
  "java.vendor": "GraalVM Community",
  "vertx.disableTCCL": "true",
  "java.vm.version": "17.0.4+8-jvmci-22.2-b06",
  "quarkus.test.basic-console": "true",
  "sun.io.unicode.encoding": "UnicodeLittle",
  "library.jansi.path": "C:\\Users\\rayga\\.gradle\\native\\jansi\\1.18\\windows64",
  "quarkus-internal.serialized-app-model.path": "C:\\Users\\rayga\\Downloads\\code-with-quarkus (13)\\code-with-quarkus\\build\\tmp\\quarkusDev\\quarkus-app-model.dat",
  "io.netty.machineId": "b4:cc:13:21:eb:db:28:bc",
  "java.class.version": "61.0",
  "mp.openapi.extensions.smallrye.defaultConsumes": "application/json"
}
```

**Comment by gastaldi** [comment]
I have a Windows VM and I am unable to reproduce this error too

**Comment by phillip-kruger** [comment]
The empty page in DevService is when there are no dev services. I'll do a PR to either add some info there, or remove the button)

**Comment by phillip-kruger** [comment]
Ok I think I found a case where this happens. See PR #27490 for a fix. @GavinRay97 if you can test against this PR that would be great. Basically if you have a quoted dot this error happens, example a config like `bla.bla."."=foo` will create this error.

**Comment by GavinRay97** [comment]
I updated to `2.13.0.CR1` and this appears to be fixed (may have also been cached and it was actually fixed earlier?)
