### ISSUE TITLE
Add ability to include extra protoc plugins when using Gradle

### ISSUE THREAD

**Issue by ranjanashish** [quarkusio/quarkus#27388]
### Description

Currently, Quarkus does not provide the functionality to include extra protoc plugins when using Gradle. One such plugin being https://github.com/envoyproxy/protoc-gen-validate#java.

Related discussion: https://github.com/quarkusio/quarkus/discussions/27278

**Comment by ranjanashish** [comment]
CC: @cescoffier

**Comment by hu-chia** [comment]
It could be a very useful feature, is there any progress?

**Comment by Venki028** [comment]
@cescoffier if Proto Generation is handled by Quarkus itself, is there any other way of adding validation to the input without any extra plugins

**Comment by cescoffier** [comment]
No, but contributions are more than welcome!

**Comment by gigi** [comment]
Hi!
It is interesting that `build.buf:protovalidate:0.2.1` works as expected
```
quarkus.generate-code.grpc.scan-for-imports=com.google.api.grpc:proto-google-common-protos,com.google.protobuf:protobuf-java,build.buf:protovalidate
```

While older versions throw error:

```
2024-11-01 12:10:46,829 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.grpc.deployment.devui.GrpcDevUIProcessor#collectMessagePrototypes threw an exception: java.lang.NoClassDefFoundError: com/google/protobuf/RuntimeVersion$RuntimeDomain
        at build.buf.validate.ValidateProto.<clinit>(ValidateProto.java:11)
        at org.acme.HelloGrpcProto.<clinit>(HelloGrpcProto.java:34)
        at org.acme.HelloRequest.internalGetFieldAccessorTable(HelloRequest.java:35)
        at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:116)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:735)
        at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:344)
        at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:354)
        at io.quarkus.grpc.deployment.devui.GrpcDevUIProcessor.collectMessagePrototypes(GrpcDevUIProcessor.java:119)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:499)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.RuntimeVersion$RuntimeDomain
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:569)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
        ... 18 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:354)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:272)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:62)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:89)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:428)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.grpc.deployment.devui.GrpcDevUIProcessor#collectMessagePrototypes threw an exception: java.lang.NoClassDefFoundError: com/google/protobuf/RuntimeVersion$RuntimeDomain
        at build.buf.validate.ValidateProto.<clinit>(ValidateProto.java:11)
        at org.acme.HelloGrpcProto.<clinit>(HelloGrpcProto.java:34)
        at org.acme.HelloRequest.internalGetFieldAccessorTable(HelloRequest.java:35)
        at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:116)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:735)
        at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:344)
        at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:354)
        at io.quarkus.grpc.deployment.devui.GrpcDevUIProcessor.collectMessagePrototypes(GrpcDevUIProcessor.java:119)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:499)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.RuntimeVersion$RuntimeDomain
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:569)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
        ... 18 more

        at io.quarkus.builder.Execution.run(Execution.java:124)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:161)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:350)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/RuntimeVersion$RuntimeDomain
        at build.buf.validate.ValidateProto.<clinit>(ValidateProto.java:11)
        at org.acme.HelloGrpcProto.<clinit>(HelloGrpcProto.java:34)
        at org.acme.HelloRequest.internalGetFieldAccessorTable(HelloRequest.java:35)
        at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:116)
        at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:735)
        at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:344)
        at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:354)
        at io.quarkus.grpc.deployment.devui.GrpcDevUIProcessor.collectMessagePrototypes(GrpcDevUIProcessor.java:119)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:499)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.RuntimeVersion$RuntimeDomain
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:569)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
        ... 18 more
```

Trying to investigate

**Comment by cescoffier** [comment]
Protobuf 4 breaks several things. We do not have support for it yet.

**Comment by gigi** [comment]
Thanks for your reply! 
Do you happen to have a list of known issues or things that aren’t working with Protobuf 4?

**Comment by jmini** [comment]
With the release of `3.21.3` and the integration of my change in https://github.com/quarkusio/quarkus/pull/47306,  the artifact `io.quarkus:quarkus-grpc-protoc-plugin:$quarkusPlatformVersion:shaded@jar` works well.

Updated gradle `build.gradle` file:

```gradle
plugins {
    id 'java'
    id 'com.google.protobuf' version '0.9.5'
    // --> no quarkus plugin configured in that module, not possible. See https://github.com/quarkusio/quarkus/discussions/47287
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-grpc'
    compileOnly 'javax.annotation:javax.annotation-api:1.3.2'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

test {
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
}
compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
}

compileTestJava {
    options.encoding = 'UTF-8'
}

String protobufVersion = "3.25.5"
String grpcVersion = "1.69.1"
protobuf {
  protoc {
    artifact = "com.google.protobuf:protoc:$protobufVersion"
  }
  plugins {
    grpc {
      artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion"
    }
    quarkusGrpc {
      artifact = "io.quarkus:quarkus-grpc-protoc-plugin:$quarkusPlatformVersion:shaded@jar"
    }
  }

  generateProtoTasks {
    all().configureEach { task ->
      task.plugins {
        grpc { }
        quarkusGrpc { }
      }
    }
  }
}

```

**Comment by jmini** [comment]
I had a [zulip chat](https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/Grpc.3A.20the.20mutiny.20generator.20override.20existing.20generated.20files) with @cescoffier related to the gradle setup (generating grpc/protobuf outisde of quarkus).

He reminded me why the **post-generation of grpc generated code** is important:

* `@javax.annotation.Generated` annotation is changed to `@io.quarkus.Generated`
* Visibility is changed to allow proxying (removal of `final`)

<details><summary>diff on a simple example `HelloServiceGrpc.java`</summary>
<p>

```diff
--- grpc
+++ quarkus post processing
@@ -4,7 +4,7 @@
 
 /**
  */
-@javax.annotation.Generated(value = "by gRPC proto compiler (version 1.69.1)", comments = "Source: hello.proto")
+@io.quarkus.Generated(value = "by gRPC proto compiler (version 1.69.1)", comments = "Source: hello.proto")
 @io.grpc.stub.annotations.GrpcGenerated
 public final class HelloServiceGrpc {
 
@@ -87,7 +87,7 @@
     public static abstract class HelloServiceImplBase implements io.grpc.BindableService, AsyncService {
 
         @java.lang.Override
-        public final io.grpc.ServerServiceDefinition bindService() {
+        public io.grpc.ServerServiceDefinition bindService() {
             return HelloServiceGrpc.bindService(this);
         }
     }
@@ -95,7 +95,7 @@
     /**
      * A stub to allow clients to do asynchronous rpc calls to service HelloService.
      */
-    public static final class HelloServiceStub extends io.grpc.stub.AbstractAsyncStub<HelloServiceStub> {
+    public static class HelloServiceStub extends io.grpc.stub.AbstractAsyncStub<HelloServiceStub> {
 
         private HelloServiceStub(io.grpc.Channel channel, io.grpc.CallOptions callOptions) {
             super(channel, callOptions);
@@ -116,7 +116,7 @@
     /**
      * A stub to allow clients to do synchronous rpc calls to service HelloService.
      */
-    public static final class HelloServiceBlockingStub extends io.grpc.stub.AbstractBlockingStub<HelloServiceBlockingStub> {
+    public static class HelloServiceBlockingStub extends io.grpc.stub.AbstractBlockingStub<HelloServiceBlockingStub> {
 
         private HelloServiceBlockingStub(io.grpc.Channel channel, io.grpc.CallOptions callOptions) {
             super(channel, callOptions);
@@ -137,7 +137,7 @@
     /**
      * A stub to allow clients to do ListenableFuture-style rpc calls to service HelloService.
      */
-    public static final class HelloServiceFutureStub extends io.grpc.stub.AbstractFutureStub<HelloServiceFutureStub> {
+    public static class HelloServiceFutureStub extends io.grpc.stub.AbstractFutureStub<HelloServiceFutureStub> {
 
         private HelloServiceFutureStub(io.grpc.Channel channel, io.grpc.CallOptions callOptions) {
             super(channel, callOptions);
@@ -190,7 +190,7 @@
         }
     }
 
-    public static final io.grpc.ServerServiceDefinition bindService(AsyncService service) {
+    public static io.grpc.ServerServiceDefinition bindService(AsyncService service) {
         return io.grpc.ServerServiceDefinition.builder(getServiceDescriptor()).addMethod(getSayHelloMethod(), io.grpc.stub.ServerCalls.asyncUnaryCall(new MethodHandlers<org.acme.HelloRequest, org.acme.HelloReply>(service, METHODID_SAY_HELLO))).build();
     }
 
```

</p>
</details> 

The code is located here in [GrpcPostProcessing](https://github.com/quarkusio/quarkus/blob/b808b47ac1befb75272e08265bf52123dcc9af2c/extensions/grpc/codegen/src/main/java/io/quarkus/grpc/codegen/GrpcPostProcessing.java):

```xml
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-grpc-codegen</artifactId>
    <version>3.26.1</version>
</dependency>
```

Can be executed like this (bash script using jbang):

```
#!/bin/sh
jbang --main io.quarkus.grpc.codegen.GrpcPostProcessing io.quarkus:quarkus-grpc-codegen:RELEASE $@
```

Commit to use the quarkus post-processor step in a gradle build: https://github.com/jmini/quarkus-experiments/commit/5402b6459639b7f3b1181dc98991a0b6ea8b9ab7
