### ISSUE TITLE
build rest client error from class of jar.

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#27439]
### Describe the bug

the below is error log.
```log
2022-08-23 19:06:37,857 ERROR [com.min.com.exc.rep.htt.AbstractHttpExceptionReporter] (executor-thread-1) catch in global exception handler: org.eclipse.microprofile.rest.client.RestClientDefinitionException: org.jboss.resteasy.reactive.client.api.InvalidRestClientDefinitionException: Failed to generate client for class interface com.mindflow.dataset.interfaces.service.MetadataRemoteService : Cannot invoke "org.jboss.jandex.AnnotationValue.asStringArray()" because the return value of "org.jboss.jandex.AnnotationInstance.value()" is null
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:338)
	at com.mindflow.reap.remote.client.MetadataClient.init(MetadataClient.java:34)
	at com.mindflow.reap.remote.client.MetadataClient_Bean.create(Unknown Source)
	at com.mindflow.reap.remote.client.MetadataClient_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:19)
	at com.mindflow.reap.remote.client.MetadataClient_ClientProxy.arc$delegate(Unknown Source)
	at com.mindflow.reap.remote.client.MetadataClient_ClientProxy.pageMetadata(Unknown Source)
	at com.mindflow.reap.controller.MetadataController.pageMetadata(MetadataController.java:79)
	at com.mindflow.reap.controller.MetadataController_Subclass.pageMetadata$$superforward1(Unknown Source)
	at com.mindflow.reap.controller.MetadataController_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.mindflow.reap.controller.MetadataController_Subclass.pageMetadata(Unknown Source)
	at com.mindflow.reap.controller.MetadataController$quarkusrestinvoker$pageMetadata_6bded7b6ed6b600d02c52efe568e4c19aecf838e.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.jboss.resteasy.reactive.client.api.InvalidRestClientDefinitionException: Failed to generate client for class interface com.mindflow.dataset.interfaces.service.MetadataRemoteService : Cannot invoke "org.jboss.jandex.AnnotationValue.asStringArray()" because the return value of "org.jboss.jandex.AnnotationInstance.value()" is null
	at org.jboss.resteasy.reactive.client.impl.ClientProxies.get(ClientProxies.java:27)
	at org.jboss.resteasy.reactive.client.impl.WebTargetImpl.proxy(WebTargetImpl.java:400)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:336)
	... 34 more

```

### Expected behavior

build rest client success.

### Actual behavior

build rest client error.

### How to Reproduce?

build rest client in bean:
```java
@ApplicationScoped
public class MetadataClient {

    @ConfigProperty(name = "mindflow.url.dataset")
    String datasetUrl;

    private MetadataRemoteService metadataRemoteService;

    @PostConstruct
    public void init(){
        metadataRemoteService = RestClientBuilder.newBuilder()
                .baseUri(URI.create(datasetUrl))
                .build(MetadataRemoteService.class);
    }

```

the rest client interface from jar and made it jandex(from jandex-maven-plugin).
![image](https://user-images.githubusercontent.com/25682169/186143647-06cb1b5a-7e99-45dc-97eb-9f02f539b304.png)

```java

@Path("/metadata")
public interface MetadataRemoteService {

    /**
     * 文件初始化
     */
    @POST
    @Path("/init")
    @Consumes(MediaType.APPLICATION_JSON)
    ResponseMessage initMetadata(MetadataInitCmd metadataInitCmd);

    /**
     * 文件上传
     */
    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    ResponseMessage saveMetadata(MetadataUploadCmd cmd);

    /**
     * 创建文件夹
     */
    @POST
    @Path("/folder")
    @Consumes(MediaType.APPLICATION_JSON)
    ResponseMessage createFolder(MetadataFolderCmd fileDirCmd);

    /**
     * 删除文件
     */
    @DELETE
    @Path("/{id}")
    @Consumes
    ResponseMessage delete(@QueryParam("id") Long id);
    /**
     * 删除多个文件
     */
    @POST
    @Path("/delete")
    @Consumes(MediaType.APPLICATION_JSON)
    ResponseMessage delete(MetadataDelCmd cmd);

    /**
     * 移动文件
     */
    @POST
    @Path("/move")
    @Consumes(MediaType.APPLICATION_JSON)
    ResponseMessage move(MetadataMoveCmd metadataMoveCmd);

    /**
     * 文件列表、数据集中的文件列表
     */
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    PageResponseMessage<MetadataDTO> pageMetadata(MetadataQuery metadataQuery);

    /**
     * 获取单条数据详情
     */
    @GET
    @Path("/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    ResponseMessage getOneDetail(@PathParam("id") Long id);
}

```

### Output of `uname -a` or `ver`

win11 and mac

### Output of `java -version`

java17

### GraalVM version (if different from Java)

22.1

### Quarkus version or git rev

2.10.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.4

### Additional information

jandex plugin
```xml
 <plugin>
                        <groupId>org.jboss.jandex</groupId>
                        <artifactId>jandex-maven-plugin</artifactId>
                        <version>1.2.3</version>
                        <executions>
                            <execution>
                                <id>make-index</id>
                                <goals>
                                    <goal>jandex</goal>
                                </goals>
                                <!-- phase is 'process-classes by default' -->
                                <configuration>
                                    <!-- Nothing needed here for simple cases -->
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
```

**Comment by naah69** [comment]
when i debug it,the method annotation can't get value

io.quarkus.jaxrs.client.reactive.deployment.JaxrsClientReactiveProcessor#addResponseTypeIfMultipart
```java
    private void addResponseTypeIfMultipart(Set<ClassInfo> multipartResponseTypes, MethodInfo method, IndexView index) {
        AnnotationInstance produces = method.annotation(ResteasyReactiveDotNames.PRODUCES);
        if (produces == null) {
            produces = method.annotation(ResteasyReactiveDotNames.PRODUCES);
        }
        if (produces != null) {
            String[] producesValues = produces.value().asStringArray();
            for (String producesValue : producesValues) {
                if (producesValue.toLowerCase(Locale.ROOT)
                        .startsWith(ContentType.MULTIPART_FORM_DATA.getMimeType())) {
                    multipartResponseTypes.add(returnTypeAsClass(method, index));
                }
            }
        }
    }
```

log
```log
2022-08-24 10:25:01,396 DEBUG [io.qua.jax.cli.rea.dep.JaxrsClientReactiveProcessor] (build-89) Failed to create client proxy for com.mindflow.dataset.interfaces.service.MetadataSetRemoteService this can usually be safely ignored: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.AnnotationValue.asStringArray()" because the return value of "org.jboss.jandex.AnnotationInstance.value()" is null
	at io.quarkus.jaxrs.client.reactive.deployment.JaxrsClientReactiveProcessor.addResponseTypeIfMultipart(JaxrsClientReactiveProcessor.java:1005)
	at io.quarkus.jaxrs.client.reactive.deployment.JaxrsClientReactiveProcessor.generateClientInvoker(JaxrsClientReactiveProcessor.java:793)
	at io.quarkus.jaxrs.client.reactive.deployment.JaxrsClientReactiveProcessor.setupClientProxies(JaxrsClientReactiveProcessor.java:315)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

**Comment by geoand** [comment]
Please attach a sample project we can use to debug.

**Comment by naah69** [comment]
it had resloved. ` @Produces` must had type
