### ISSUE TITLE
Lombok + MapStruct + Smallrye-OpenAPI = Error Running Quarkus

### ISSUE THREAD

**Issue by fenix-hub** [quarkusio/quarkus#27496]
### Describe the bug

I'm trying to compile a Quarkus multi-module project implementing Lombok and MapStruct to write DTOs and Mappings, plus Quarkus Smallrye OpenAPI to automatically exposes my Resources on the Dev UI Console.

If I try to run the project, I get this error
```bash
2022-08-25 10:57:05,745 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 15 more
Caused by: java.lang.NoClassDefFoundError: Lio/swagger/client/api/ProcessDefinitionApi;
        at java.base/java.lang.Class.getDeclaredFields0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3062)
        at java.base/java.lang.Class.getDeclaredField(Class.java:2410)
        at io.quarkus.arc.impl.Reflections.findFieldInternal(Reflections.java:64)
        at io.quarkus.arc.impl.Reflections$1.apply(Reflections.java:33)
        at io.quarkus.arc.impl.Reflections$1.apply(Reflections.java:30)
        at io.quarkus.arc.impl.ComputingCache$1.get(ComputingCache.java:52)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:49)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:40)
        at io.quarkus.arc.impl.Reflections.findField(Reflections.java:59)
        at com.aurigaspa.pbm.identityprovider.services.AuthenticationService_Bean.<init>(Unknown Source)
        at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans4(Unknown Source)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
        at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:124)
        at io.quarkus.arc.Arc.initialize(Arc.java:30)
        at io.quarkus.arc.runtime.ArcRecorder.initContainer(ArcRecorder.java:42)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources1325531031.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources1325531031.deploy(Unknown Source)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: io.swagger.client.api.ProcessDefinitionApi
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:490)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:440)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:490)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:440)
        ... 36 more
```

Looks like Quarkus is not able to locate a class used by the Smallrye OpenAPI extension, which should be generated by the plugin (and it is generate with no problems without MapStruct and only Lombok)

### How to Reproduce?

My current project presents this configuration

<details>
<summary><b>Parent POM</b></summary>  

```xml
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>${quarkus.platform.group-id}</groupId>
				<artifactId>${quarkus.platform.artifact-id}</artifactId>
				<version>${quarkus.platform.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
                        ....
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct</artifactId>
				<version>${mapstruct.version}</version>
			</dependency>
			<dependency>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct-processor</artifactId>
				<version>${mapstruct.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok-mapstruct-binding</artifactId>
				<version>${lombok-mapstruct.version}</version>
			</dependency>
                       ....
	</dependencyManagement>

	<dependencies>
		...
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-processor</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok-mapstruct-binding</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-openapi</artifactId>
		</dependency>
		...
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>${quarkus.platform.group-id}</groupId>
					<artifactId>quarkus-maven-plugin</artifactId>
					<version>${quarkus.platform.version}</version>
					<extensions>true</extensions>
					<executions>
						<execution>
							<goals>
								<goal>build</goal>
								<goal>generate-code</goal>
								<goal>generate-code-tests</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${surefire-plugin.version}</version>
					<configuration>
						<skipTests>${skipTests}</skipTests>
						<systemPropertyVariables>
							<java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
							<maven.home>${maven.home}</maven.home>
						</systemPropertyVariables>
					</configuration>
				</plugin>
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${compiler-plugin.version}</version>
					<configuration>
						<parameters>${maven.compiler.parameters}</parameters>
					</configuration>
				</plugin>
                               ....
			</plugins>
		</pluginManagement>
	</build>
```  

</details>

<details>
<summary><b>Child POM</b></summary>  

```xml
       ....
	<build>
		<plugins>
			<plugin>
				<groupId>${quarkus.platform.group-id}</groupId>
				<artifactId>quarkus-maven-plugin</artifactId>
				<version>${quarkus.platform.version}</version>
				<extensions>true</extensions>
				<executions>
					<execution>
					<goals>
						<goal>build</goal>
						<goal>generate-code</goal>
						<goal>generate-code-tests</goal>
					</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
        ...
```  

</details>

### Output of `java -version`

```bash
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

### Additional information

Versions  
```xml
<quarkus.platform.version>2.11.3.Final</quarkus.platform.version>
<lombok.version>1.18.22</lombok.version>
<lombok-mapstruct.version>0.2.0</lombok-mapstruct.version>
<mapstruct.version>1.5.2.Final</mapstruct.version>
```

**Comment by phillip-kruger** [comment]
Quarkus (or SmallRye OpenAPI) does not use `io.swagger`, but rather MicroProfile OpenAPI. Are you perhaps including io.swagger in your pom ? Or are you using some generator to generate classes from an OpenAPI schema ? Can you share more info, or better a reproducer ?

**Comment by fenix-hub** [comment]
@phillip-kruger you are right, looks like there was a sub-module generated as a swagger client which wasn't compiled. I'll close this one, thanks
