### ISSUE TITLE
camel dev mode fire initialization events twice

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#2750]
**Describe the bug**
I have [this](https://github.com/lburgazzoli/apache-camel-k-runtime/blob/quarkus-runtime/camel-k-runtime-quarkus/camel-k-runtime-quarkus/src/main/java/org/apache/camel/k/quarkus/ApplicationRuntime.java) that listens for camel related events to perform some task and what I see is that when running with `quarkus:dev` the initializing method is fired twice.

When running the jar directly this does not happen.

**Expected behavior**
Events are not fired twice

**Actual behavior**
Events are fired twice

**To Reproduce**
1. Build https://github.com/lburgazzoli/apache-camel-k-runtime/
2. Go to camel-k-runtime-examples/camel-k-runtime-example-quarkus
3. invoke `mvn quarkus:dev`

**Configuration**
```properties
quarkus.log.console.enable = true
quarkus.log.file.enable = false

quarkus.camel.disable-jaxb = true
quarkus.camel.disable-xml  = true
quarkus.camel.defer-init-phase = true

camel.context.name = camel-q
camel.context.streamCaching = true

camel.properties.prefixToken = {{
camel.properties.suffixToken = }}
camel.k.customizer = streamcaching
customizer.streamcaching.spoolDirectory = {{sys:java.io.tmpdir}}/camel-k
```

**Environment (please complete the following information):**
 - Linux 5.1.6-300.fc30.x86_64 
 - openjdk version "1.8.0_212"
 - graalvm-ce-1.0.0-rc16
 - 0.16.0

**Comment by lburgazzoli** [comment]
The stack trace for the two invocations:

```
java.lang.Thread.State: RUNNABLE
      at org.apache.camel.k.quarkus.ApplicationRuntime.initializing(ApplicationRuntime.java:49)
      at org.apache.camel.k.quarkus.ApplicationRuntime_Observer_initializing_efc0f046e9729a2e45b64b01b6ae7f050d5bccd4.notify(Unknown Source:141)
      at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:244)
      at io.quarkus.arc.EventImpl.fire(EventImpl.java:85)
      at io.quarkus.camel.core.runtime.support.FastCamelRuntime.fireEvent(FastCamelRuntime.java:172)
      at io.quarkus.camel.core.runtime.support.FastCamelRuntime.doInit(FastCamelRuntime.java:111)
      at io.quarkus.camel.core.runtime.support.FastCamelRuntime.start(FastCamelRuntime.java:83)
      at io.quarkus.camel.core.runtime.CamelTemplate.start(CamelTemplate.java:51)
      at io.quarkus.deployment.steps.CamelInitProcessor$createRuntimeInitTask44.deploy_0(Unknown Source:145)
      at io.quarkus.deployment.steps.CamelInitProcessor$createRuntimeInitTask44.deploy(Unknown Source:183)
      at io.quarkus.runner.ApplicationImpl4.doStart(Unknown Source:367)
      at io.quarkus.runtime.Application.start(Application.java:100)
      at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:130)
      at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:173)
      - locked <0xdaf> (a java.lang.Class)
      at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:205)
      at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:117)
      at io.quarkus.camel.core.deployment.devmode.CamelHotReplacementSetup$1.run(CamelHotReplacementSetup.java:21)
      at java.util.TimerThread.mainLoop(Timer.java:555)
      at java.util.TimerThread.run(Timer.java:505)
```

```
"Timer-0@5315" daemon prio=5 tid=0xd nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at org.apache.camel.k.quarkus.ApplicationRuntime.initializing(ApplicationRuntime.java:49)
      at org.apache.camel.k.quarkus.ApplicationRuntime_Observer_initializing_efc0f046e9729a2e45b64b01b6ae7f050d5bccd4.notify(Unknown Source:141)
      at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:244)
      at io.quarkus.arc.EventImpl.fire(EventImpl.java:85)
      at io.quarkus.camel.core.runtime.support.FastCamelRuntime.fireEvent(FastCamelRuntime.java:172)
      at io.quarkus.camel.core.runtime.support.FastCamelRuntime.doInit(FastCamelRuntime.java:111)
      at io.quarkus.camel.core.runtime.support.FastCamelRuntime.start(FastCamelRuntime.java:83)
      at io.quarkus.camel.core.runtime.CamelTemplate.start(CamelTemplate.java:51)
      at io.quarkus.deployment.steps.CamelInitProcessor$createRuntimeInitTask44.deploy_0(Unknown Source:145)
      at io.quarkus.deployment.steps.CamelInitProcessor$createRuntimeInitTask44.deploy(Unknown Source:183)
      at io.quarkus.runner.ApplicationImpl4.doStart(Unknown Source:367)
      at io.quarkus.runtime.Application.start(Application.java:100)
      at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:130)
      at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:173)
      - locked <0xdaf> (a java.lang.Class)
      at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:205)
      at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:117)
      at io.quarkus.camel.core.deployment.devmode.CamelHotReplacementSetup$1.run(CamelHotReplacementSetup.java:21)
      at java.util.TimerThread.mainLoop(Timer.java:555)
      at java.util.TimerThread.run(Timer.java:505)
```

Looks like event are fire by CamelHotReplacementSetup

**Comment by lburgazzoli** [comment]
//cc @gnodet

**Comment by gsmet** [comment]
@lburgazzoli is it still an issue?
