### ISSUE TITLE
Add names to the Mailer

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#2761]
**Description**
It should be possible to add the names of the sender and of the recipient(s) to an email.

**Comment by machi1990** [comment]
Hi @dwamara, 
MailMessage properties accepts email fields using the common formats for email with or without real name. So adding adding the sender or recipients emails (with names) following the following format should work. 
```
username@example.com (Firstname Lastname)
```
or 
``` 
Firstname Lastname <username@example.com>
```

**Comment by dwamara** [comment]
@machi1990 
These are the fields in the Mail class of Quarkus Mailer

```
    private List<String> bcc = new ArrayList();
    private List<String> cc = new ArrayList();
    private String from;
    private String replyTo;
    private String bounceAddress;
    private String subject;
    private String text;
    private String html;
    private List<String> to = new ArrayList();
    private Map<String, List<String>> headers = new HashMap();
    private List<Attachment> attachments = new ArrayList();
```
There is no way to add the name of the receiver in that case as you would suggest.

**Comment by machi1990** [comment]
> And a message would be sent for example like this:
> 
> ```
> mailer.send(io.quarkus.mailer.Mail.withText(request.getToEmailAddress(), request.getMessageSubject(), request.getMessage()));
> ```
> 
> There is no way to add the name of the receiver in that case as you would suggest.

The above example should work as long as `request.getToEmailAddress()` returns a `String` with the suggested format above.

**Comment by dwamara** [comment]
Only
```
username@example.com (Firstname Lastname)
```
works, 

```
Firstname Lastname <username@example.com>
```
returns 
```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: invalid email address
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.vertx.axle.AsyncResultCompletionStage.lambda$toCompletionStage$0(AsyncResultCompletionStage.java:20)
	at io.vertx.ext.mail.impl.MailClientImpl.lambda$returnResult$5(MailClientImpl.java:155)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)

```

**Comment by cescoffier** [comment]
Can you provide a reproducer?

This works:

```
@Test
    void testEmailWithRecipientNames() {
        Mail mail = new Mail()
                .setSubject("Test names")
                .setText("Test names")
                .addTo("username@example.com (Firstname Lastname)")
                .addTo("Firstname2 Lastname <usernamew@example.com>");
        assertThat(mail.getTo()).hasSize(2);

        mailer.send(mail)
                .toCompletableFuture().join();

        assertThat(wiser.getMessages()).hasSize(2);
    }
```

**Comment by dwamara** [comment]
Sorry for the delay, the reproducer would have been https://github.com/dwamara/quarkus-email-sender_bug2761 but I can't seem to reproduce it with 0.17.0 anymore so I'm closing the ticket
