### ISSUE TITLE
GraphQL fails to get current request using CDI.current().select(HttpServerRequest.class)

### ISSUE THREAD

**Issue by deedarb** [quarkusio/quarkus#27628]
### Describe the bug

GraphQL fails to get current request using CDI.current().select(HttpServerRequest.class)

fails with 

    javax.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=io.quarkus.vertx.http.runtime.CurrentRequestProducer, id=c786212c50efeac37ecc96f8570579f64be3bb5b]
            - you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
            at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:53)
            at io.vertx.core.http.CurrentRequestProducer_ProducerMethod_getCurrentRequest_05f950ea7ab91d121ba0bac525b89d62f3261b2d_ClientProxy.arc$delegate(Unknown Source)
            at io.vertx.core.http.CurrentRequestProducer_ProducerMethod_getCurrentRequest_05f950ea7ab91d121ba0bac525b89d62f3261b2d_ClientProxy.getHeader(Unknown Source)

### Expected behavior

work same as in 2.11.1

### Actual behavior

Exception is thrown

### How to Reproduce?

https://github.com/deedarb/graphql-error-reproducer-1

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode)

### Quarkus version or git rev

2.12.0 or 2.11.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

### Additional information

maybe related to https://github.com/quarkusio/quarkus/pull/27147

**Comment by phillip-kruger** [comment]
Ok, I'll see if I can fix this. The problem is in the `AdaptToScalar` class (I18NLabel). 

As a workaround, you can change that class to not do the lookup in the `toString` but rather in the earlier when you construct the class. Something like this:

```
@AdaptToScalar(Scalar.String.class)
public class I18nLabel {
    private String en;
    private String ru;
    private String lang; // Added new var
            
    public static I18nLabel fromString(String str) {
        return new JsonObject(str).mapTo(I18nLabel.class);
    }

    public static I18nLabel of(String en, String ru) {
        return new I18nLabel().setEn(en).setRu(ru).setLang(); // setLang here
    }
    
    @Override
    public String toString() {
        return switch (lang) {
            case "en" -> this.en;
            case "ru" -> this.ru;
            default -> this.en;
        };
    }

    public static Optional<String> extractLanguage(HttpServerRequest request) {
        String acceptLanguage = request.getHeader(HttpHeaders.ACCEPT_LANGUAGE);
        List<ParsableLanguageValue> languages = HeaderParser.sort(HeaderParser.convertToParsedHeaderValues(acceptLanguage, ParsableLanguageValue::new));
        return languages.stream()
            .map(ParsableLanguageValue::tag)
            .findFirst();
    }

    public String getEn() {
        return en;
}

    public I18nLabel setEn(String en) {
        this.en = en;
        return this;
    }

    public String getRu() {
        return ru;
    }

    public I18nLabel setRu(String ru) {
        this.ru = ru;
        return this;
    }
    
    // New method
    public I18nLabel setLang(){
        this.lang = Optional.ofNullable(CDI.current())
            .map(cdi -> cdi.select(HttpServerRequest.class))
            .map(Instance::get)
            .flatMap(I18nLabel::extractLanguage).orElse("en");
        return this;
    }
```

**Comment by deedarb** [comment]
workaround works as expected, implemented **lang** initialization in default constructor

**Comment by phillip-kruger** [comment]
Great. I am working on a fix ...

**Comment by phillip-kruger** [comment]
I am going to revert this fix, as it's causing some other problems. For now use the workaround as described, until I can find another way...

**Comment by geoand** [comment]
Is this still an issue?

**Comment by phillip-kruger** [comment]
I think so, but there is a workaround.
