### ISSUE TITLE
java.lang.VerifyError: class GcpQuarkusJsonLoggingProvider_Subclass overrides final method org.jboss.logmanager.ExtFormatter.format(Ljava/util/logging/LogRecord;)Ljava/lang/String;

### ISSUE THREAD

**Issue by samodadela** [quarkusio/quarkus#27639]
### Describe the bug

When running `mvn quarkus:dev` on the attached reproducer, Quarkus seems to override the wrong method.

`ExtFormatter` has:
```
    public final String format(final LogRecord record) {
        return format(ExtLogRecord.wrap(record));
    }

    public abstract String format(ExtLogRecord record);
```

`GcpQuarkusJsonLoggingProvider` overrides:
```
    @Override
    public String format(ExtLogRecord extLogRecord) {
        return null;
    }
```

but Quarkus complains:
```
2022-08-31 20:08:20,805 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.VerifyError: class org.acme.getting.started.logging.GcpQuarkusJsonLoggingProvider_Subclass overrides final method org.jboss.logmanager.ExtFormatter.format(Ljava/util/logging/LogRecord;)Ljava/lang/String;
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:480)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:440)
        at org.acme.getting.started.logging.GcpQuarkusJsonLoggingProvider_Bean.create(Unknown Source)
        at org.acme.getting.started.logging.GcpQuarkusJsonLoggingProvider_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
        at org.acme.getting.started.logging.GcpQuarkusJsonLoggingProvider_Bean.get(Unknown Source)
        at org.acme.getting.started.logging.GcpQuarkusJsonLoggingProvider_Bean.get(Unknown Source)
        at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:223)
        at io.quarkus.arc.impl.InstanceImpl$InstanceIterator.next(InstanceImpl.java:259)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at io.quarkiverse.loggingjson.LoggingJsonRecorder.initializeJsonLogging(LoggingJsonRecorder.java:38)
        at io.quarkus.deployment.steps.LoggingJsonProcessor$setUpFormatter614569086.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LoggingJsonProcessor$setUpFormatter614569086.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Expected behavior

Quarkus should choose `public abstract String format(ExtLogRecord record)` instead of `public final String format(final LogRecord record)`.
 

### Actual behavior

Quarkus complains as above.

### How to Reproduce?

Run `mvn quarkus:dev` on attached reproducer (modified quickstart). Check console output.

[reproducer.zip](https://github.com/quarkusio/quarkus/files/9463944/reproducer.zip)

### Output of `uname -a` or `ver`

Linux a 5.15.60-1-MANJARO #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "18.0.2" 2022-07-19 OpenJDK Runtime Environment (build 18.0.2+9) OpenJDK 64-Bit Server VM (build 18.0.2+9, mixed mode)

### Quarkus version or git rev

2.12.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

BTW: It was working with an older Quarkus version:
```
<quarkus-version>1.10.5.Final</quarkus-version>
```

**Comment by manovotn** [comment]
So, the class `GcpQuarkusJsonLoggingProvider` is subject to interception which means we iterate over its methods and try to [pinpoint any `final` methods](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java#L184-L186).
Debugging shows that we even correctly detect `public final String format(final LogRecord record)` (coming from `org.jboss.logmanager.ExtFormatter`). By default, transforming unproxyable classes is enabled, so Arc tries to do that and the [transformation code executes](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Methods.java#L497).

At this point, I am fairly lost at to why this doesn't help; I am trying to learn more about it...

**Comment by manovotn** [comment]
@samodadela, so the reason this doesn't work is because you are extending `org.jboss.logmanager.ExtFormatter`.
Logging classes are loaded by system `ClassLoader` as mentioned in [this guide](https://quarkus.io/guides/class-loading-reference#parent-first-dependencies):
> Some logging related classes, as logging must be loaded by the system ClassLoader

This is a problem because despite Arc attempting to perform the bytecode transformation on the `final` method, the class has been already loaded, so this has no effect. Logging classes need to be loaded very soon in the process so we cannot temper with them at later point in time.

Also note that this scenario wouldn't work for standard CDI either due to [proxyability rules](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#unproxyable) and here even Quarkus can't help with it's extra features.

**Comment by samodadela** [comment]
@manovotn 
Can you check why this works using an older Quarkus (e.g. 1.10.5.Final)?
Event though this fails for `mvn quarkus:dev` it works correctly when deployed on GCP. Why?
Any workrounds?

**Comment by mkouba** [comment]
> @manovotn Can you check why this works using an older Quarkus (e.g. 1.10.5.Final)? Event though this fails for `mvn quarkus:dev` it works correctly when deployed on GCP. Why? Any workrounds?

You can try to set `quarkus.arc.dev-mode.monitoring-enabled=false`, disable the dev monitoring feature that adds an interceptor to all eligible beans. It worked before because the dev monitoring feature was not present.

**Comment by samodadela** [comment]
@mkouba Setting `quarkus.arc.dev-mode.monitoring-enabled=false` works, thanks!

So this works when deployed on GCP because there is no monitoring feature in the deployed code?

**Comment by mkouba** [comment]
> @mkouba Setting `quarkus.arc.dev-mode.monitoring-enabled=false` works, thanks!
> 
> So this works when deployed on GCP because there is no monitoring feature in the deployed code?

Exactly. However, it would fail if your bean has a CDI interceptor associated, e.g. `@Transactional`.

**Comment by manovotn** [comment]
Martin is correct, the issue appears as soon as any CDI interceptor is attached to the given class because the class is not proxyable. And as mentioned, in the old Quarkus version, there just happened to be none.

Though I was wondering if we have some opt-in way for users to explicitly skip interception of non-proxyable methods? Well, just final methods would do. I imagine this could happen for dev mode in some cases and it might be beneficial to still allow the app to boot. In principal similar to how `InterceptionFactory` can ignore `final` methods. WDYT @mkouba?
