### ISSUE TITLE
KafkaStreams doesn't respect Serdes provided for Materialized method

### ISSUE THREAD

**Issue by mariuszbozek** [quarkusio/quarkus#27661]
### Describe the bug

KafkaStreams doesn't respect Serdes provided for Materialized method

I have simple code with aggregation (with StringSerde for value)
```
.aggregate(
            String::new,
            (k, v, agg) -> agg + v,
            Materialized.<String, String>as(storeSupplier)
                .withKeySerde(Serdes.String())
                .withValueSerde(Serdes.String()))
```
Quarkus Kafka Stream extension force me to setup default Serdes so I added it to the application.properties file (I added LongSerde for value to check if Serde provided in Materialized method will be respected)
```
quarkus.kafka-streams.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
quarkus.kafka-streams.default.value.serde=org.apache.kafka.common.serialization.Serdes$LongSerde
```

I received the error
```
A serializer (key: org.apache.kafka.common.serialization.StringSerializer / value: org.apache.kafka.common.serialization.LongSerializer) is not compatible to the actual key or value type (key type: java.lang.String / value type: com.orsted.mnr.monitoring.model.MonitoringEventAggregation). Change the default Serdes in StreamConfig or provide correct Serdes via method parameters (for example if using the DSL, `#to(String topic, Produced<K, V> produced)` with `Produced.keySerde(WindowedSerdes.timeWindowedSerdeFrom(String.class))`).
```

### Expected behavior

KafkaStream should respects Serde provided in Materialized method

### Output of `java -version`

11

### Quarkus version or git rev

2.12.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by ozangunalp** [comment]
I think you need to specify the Serde in the `.to()` method downstream to your aggregation, something along `Produced.with(Serdes.String(), Serdes.String())`, otherwise it takes the default serdes of your StreamConfig

**Comment by mariuszbozek** [comment]
I will check it. Thanks

**Comment by mariuszbozek** [comment]
I

> I think you need to specify the Serde in the `.to()` method downstream to your aggregation, something along `Produced.with(Serdes.String(), Serdes.String())`, otherwise it takes the default serdes of your StreamConfig

It doesn't work for me.

I had added Serde in the to() method and had removed default serdes and I received the error:
```
Caused by: org.apache.kafka.common.config.ConfigException: Please specify a key serde or set one through StreamsConfig#DEFAULT_KEY_SERDE_CLASS_CONFIG
	at org.apache.kafka.streams.StreamsConfig.defaultKeySerde(StreamsConfig.java:1587)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.keySerde(AbstractProcessorContext.java:90)
	at org.apache.kafka.streams.kstream.internals.WrappingNullableUtils.prepareSerializer(WrappingNullableUtils.java:49)
	at org.apache.kafka.streams.kstream.internals.WrappingNullableUtils.prepareKeySerializer(WrappingNullableUtils.java:82)
	at org.apache.kafka.streams.processor.internals.SinkNode.init(SinkNode.java:61)
	at org.apache.kafka.streams.processor.internals.StreamTask.initializeTopology(StreamTask.java:950)
	at org.apache.kafka.streams.processor.internals.StreamTask.completeRestoration(StreamTask.java:260)
	at org.apache.kafka.streams.processor.internals.TaskManager.tryToCompleteRestoration(TaskManager.java:479)
	at org.apache.kafka.streams.processor.internals.StreamThread.initializeAndRestorePhase(StreamThread.java:865)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:747)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:589)

```

**Comment by ozangunalp** [comment]
Quarkus Kafka Streams extension doesn't set default serdes itself or force setupping default Serdes. I don't know the exact topology you are building, but your issue must come from the topology itself.

**Comment by mariuszbozek** [comment]
Hi, I fixed the issue. The problem was with my topology. In the first step I created KStream object and then I doing some aggregation but as separate blocks of code so KStream force in second step to use right Serde
