### ISSUE TITLE
flyway baseline-version has no effect

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#27734]
### Describe the bug

After updating the config key quarkus.flyway.baseline-version: "2022.09.02.2", I was expecting newly created environments to use 2022.09.02.2 as first version (with migrate-at-start enabled). 

It turns out that migrate-at-start does not execute the baseline operation and all migrations before 2022.09.02.2 are still executed.

### Expected behavior

first migration of newly created environments is equal to baseline-version

### Quarkus version or git rev

2.12.0.Final

**Comment by gastaldi** [comment]
Do you also have `quarkus.flyway.baseline-on-migrate` set to true in your `application.properties`?

**Comment by rmanibus** [comment]
thank you @gastaldi I missed it.

However the description of this option is not very clear: 

"Enable the creation of the history table if it does not exist already". 

It does not really mention the baseline operation. so should I expect the baseline operation to be only executed if the bdd is empty ?

**Comment by rmanibus** [comment]
@gastaldi so the baseline-on-migrate simply enable baselineOnMigrate in flyway config.

the flyway doc mention that this option will trigger the baseline operation if it is executed against a non-empty schema with no metadata table.

So when you execute it against an empty schema, the baseline operation does not occurs.

**Comment by gastaldi** [comment]
So it seems to be a Flyway bug/feature? Nit sure if there is something we can do in the Quarkus side

**Comment by rmanibus** [comment]
@gastaldi yeah more a flyway feature.
Seeing what my projects looks like, I am regularly squashing old migrations into one new baseline, and old migration remains because they might still be needed by some existing environments. 
For that use case it could be interesting to be able to specify a baseline version for newly created environment by just executing something like:
```
    if (Objects.isNull(flyway.info().current())) {
      flyway.baseline();
    }
    flyway.migrate();
```

**Comment by gastaldi** [comment]
Hm, maybe this can be set here: https://github.com/quarkusio/quarkus/blob/main/extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/FlywayRecorder.java#L79 but I think it needs to be configurable, so it doesn't break any existing behavior.

WDYT @geoand ?

**Comment by rmanibus** [comment]
@gastaldi I can make the PR. 
I have a working solution using a custom flyway sequence in a StartupEvent observer, but scheduled methods are firing before the end of this custom method, which is causing a lot of stacktrace in the logs

**Comment by gastaldi** [comment]
I am a bit unsure if we should modify the extension, it seems to be really specific to your use case, but maybe I am missing something

**Comment by rmanibus** [comment]
@gastaldi

It's really just about baselining new empty environment to avoid replaying a long history of migrations. 
Over the time the growing amount of migrations in a project is causing a consequent overhead to each deployment. 
For example without doing this, migrations ads up 1 minutes to the execution of the tests in my project.

also about my previous message, 

Do you know if there is a lifecycle hook that is called before the scheduler is started ?

**Comment by gastaldi** [comment]
@rmanibus yes, you can register callbacks (https://quarkus.io/guides/flyway#quarkus-flyway_quarkus.flyway.callbacks) and listen for such events

**Comment by gastaldi** [comment]
Sorry, I misunderstood the question above, are you using the Quartz extension or simply scheduler?

**Comment by rmanibus** [comment]
@gastaldi I am using simple scheduler for now but I think using a flyway callback as you mentioned might work because migrate at start is executed before the scheduler is started. Thank you very much !

**Comment by rmanibus** [comment]
@gastaldi 
It seems that org.flywaydb.core.Flyway bean cannot be accessed inside the callback because it is called during static init 
(see the stacktrace bellow, I tried to access it with CDI.current().select(Flyway.class).get()).

So I will stick to the startup event observer for now but it is not really a proper solution.

```
Caused by: org.flywaydb.core.api.FlywayException: Error while executing beforeMigrate callback: Synthetic bean instance for org.flywaydb.core.Flyway not initialized yet: org_flywaydb_core_Flyway_3cb728d15a0a04006cc75d03f784feb2bba9a5fb
	- a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
	- RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
	at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.handleEvent(DefaultCallbackExecutor.java:136)
	at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.execute(DefaultCallbackExecutor.java:129)
	at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.lambda$execute$0(DefaultCallbackExecutor.java:116)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.execute(DefaultCallbackExecutor.java:114)
	at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.onMigrateOrUndoEvent(DefaultCallbackExecutor.java:70)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:84)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:176)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:126)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:126)
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:76)
	at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions2063183959.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions2063183959.deploy(Unknown Source)
	... 68 more
```

**Comment by rmanibus** [comment]
@gastaldi sure I will take some time to work on it tomorrow !

**Comment by geoand** [comment]
> Hm, maybe this can be set here: https://github.com/quarkusio/quarkus/blob/main/extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/FlywayRecorder.java#L79 but I think it needs to be configurable, so it doesn't break any existing behavior.
> 
> WDYT @geoand ?

Yeah, that seems reasonable

**Comment by rmanibus** [comment]
> Now that sounds like a bug, let me investigate it. Can you share a small reproducer?

@gastaldi here is the reproducer: https://github.com/rmanibus/quarkus_27734

**Comment by gastaldi** [comment]
@rmanibus I have a fix in https://github.com/quarkusio/quarkus/pull/27770 but your callback gives the following error:

```
 org.flywaydb.core.api.FlywayException: Unable to baseline schema history table "public"."flyway_schema_history" as it already exists, and is empty.
Delete the schema history table with the clean command, and run baseline again.
        at org.flywaydb.core.internal.command.DbBaseline.baseline(DbBaseline.java:119)
        at org.flywaydb.core.Flyway.doBaseline(Flyway.java:368)
        at org.flywaydb.core.Flyway.lambda$baseline$5(Flyway.java:294)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
        at org.flywaydb.core.Flyway.baseline(Flyway.java:284)
        at org.acme.FlyWayCallback.handle(FlyWayCallback.java:33)
```

**Comment by rmanibus** [comment]
@gastaldi Thank you very much. 
Since the interceptor is called inside the migrate method, my guess is that flyway create the table before calling the lifecycle hook.
