### ISSUE TITLE
In native mode a static instance cannot load resources as the resource url references a jar in the path

### ISSUE THREAD

**Issue by tarsij** [quarkusio/quarkus#27761]
Hey there,

Looks like when an object is instantiated as static then the object or any objects instantiated by it are not able to load resources. 

If I instantiate the object as non static, the resource URL looks like this:

     resource:/diagram-interchange-dish-example.dmn

If I instantiate it as static, then the resource URL looks like this:

     jar:file:/project/quarkus-bug-1.0-SNAPSHOT-runner.jar!/diagram-interchange-dish-example.dmn

This is the exception:

    Caused by: java.nio.file.NoSuchFileException: /project/quarkus-bug-1.0-SNAPSHOT-runner.jar
	    at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	    at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	    at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	    at java.nio.file.Files.readAttributes(Files.java:1764)
	    at java.util.zip.ZipFile$Source.get(ZipFile.java:1259)
	    at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	    at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	    at java.util.zip.ZipFile.<init>(ZipFile.java:248)
	    at java.util.zip.ZipFile.<init>(ZipFile.java:177)
	    at java.util.jar.JarFile.<init>(JarFile.java:350)
	    at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
	    at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
	    at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
	    at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
	    at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
	    at java.net.URL.openStream(URL.java:1165)
	    at my.quarkus.test.QuarkusBug$Loader.read(QuarkusBug.java:30)
    
Quarkus version is 2.12.0.Final

Link to a minimal project to reproduce the issue: https://drive.google.com/file/d/1ZeIZypM1rCpA0SVsUW33uwi2hV1GlntF/view?usp=sharing

It is an aws lambda.

Build it with:
  
    mvn clean install -Pnative

Regards,
tarsij

**Comment by tarsij** [comment]
I'm closing this as I reopened it as a bug
