### ISSUE TITLE
JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative test fails with GraalVM 22.3.0-dev

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#27791]
### Describe the bug

This last worked with quarkus revision 4f53bdd6f377edcc783e3a91b3ea3e24794cfc81. So some change between 4f53bdd6f377edcc783e3a91b3ea3e24794cfc81 and bc451819b26ba4a084349ebdac3532e732b618ae caused this issue to appear.

When running the `jpa-postgresql` integration test in native mode with a recent [GraalVM 22.3 dev build](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/22.3.0-dev-20220902_0358) the integration test fails with:

```
  31.11MB (51.20%) for image heap:  368,388 objects and 188 resources
 320.08KB ( 0.51%) for other data
  60.76MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1.63MB sun.security.ssl                                     6.61MB byte[] for code metadata
1018.06KB java.util                                            3.78MB java.lang.Class
 719.84KB com.sun.crypto.provider                              3.48MB java.lang.String
 573.59KB org.hibernate.hql.internal.antlr                     2.96MB byte[] for general heap data
 551.30KB java.lang.invoke                                     2.87MB byte[] for java.lang.String
 492.49KB org.postgresql.jdbc                                  1.33MB com.oracle.svm.core.hub.DynamicHubCompanion
 454.82KB java.lang                                         1004.02KB byte[] for embedded resources
 452.09KB sun.security.x509                                  755.10KB byte[] for reflection metadata
 441.80KB c.s.org.apache.xerces.internal.impl.xs.traversers  709.55KB java.util.HashMap$Node
 429.57KB java.util.concurrent                               698.82KB java.lang.String[]
  22.33MB for 688 more packages                                6.16MB for 3674 more object types
------------------------------------------------------------------------------------------------------------------------
                        8.0s (5.1% of total time) in 38 GCs | Peak RSS: 6.52GB | CPU load: 6.10
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/sgehwolf/Documents/openjdk/quarkus/quarkus-source/integration-tests/jpa-postgresql/target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner (executable)
 /home/sgehwolf/Documents/openjdk/quarkus/quarkus-source/integration-tests/jpa-postgresql/target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner-build-output-stats.json (json)
 /home/sgehwolf/Documents/openjdk/quarkus/quarkus-source/integration-tests/jpa-postgresql/target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner-timing-stats.json (raw)
 /home/sgehwolf/Documents/openjdk/quarkus/quarkus-source/integration-tests/jpa-postgresql/target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner.build_artifacts.txt (txt)
========================================================================================================================
Finished generating 'quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner' in 2m 36s.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] objcopy --strip-debug quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 161196ms
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M7:integration-test (default) @ quarkus-integration-test-jpa-postgresql ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase
2022-09-07 18:41:25,657 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
Executing "/home/sgehwolf/Documents/openjdk/quarkus/quarkus-source/integration-tests/jpa-postgresql/target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/home/sgehwolf/Documents/openjdk/quarkus/quarkus-source/integration-tests/jpa-postgresql/target/quarkus.log -Dquarkus.log.file.enable=true"
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-09-07 18:41:26,033 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) SQL Warning Code: 0, SQLState: 00000
2022-09-07 18:41:26,034 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) relation "person" does not exist, skipping
2022-09-07 18:41:26,034 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) SQL Warning Code: 0, SQLState: 00000
2022-09-07 18:41:26,034 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) schema "myschema" does not exist, skipping
2022-09-07 18:41:26,034 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) SQL Warning Code: 0, SQLState: 00000
2022-09-07 18:41:26,034 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) table "customer" does not exist, skipping
2022-09-07 18:41:26,035 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) SQL Warning Code: 0, SQLState: 00000
2022-09-07 18:41:26,035 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) table "sequencedaddress" does not exist, skipping
2022-09-07 18:41:26,035 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) SQL Warning Code: 0, SQLState: 00000
2022-09-07 18:41:26,035 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) sequence "addressseq" does not exist, skipping
2022-09-07 18:41:26,035 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) SQL Warning Code: 0, SQLState: 00000
2022-09-07 18:41:26,035 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (JPA Startup Thread: <default>) sequence "personseq" does not exist, skipping
2022-09-07 18:41:26,036 WARN  [org.hib.too.sch.int.ExceptionHandlerLoggedImpl] (JPA Startup Thread: <default>) GenerationTarget encountered exception accepting command : Error executing DDL "drop schema myschema" via JDBC Statement: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "drop schema myschema" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlString(SchemaDropperImpl.java:387)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlStrings(SchemaDropperImpl.java:371)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropFromMetadata(SchemaDropperImpl.java:288)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.performDrop(SchemaDropperImpl.java:156)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:128)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:114)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:157)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:85)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:335)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:74)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:165)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:66)
	at java.base@17.0.4/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:755)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: org.postgresql.util.PSQLException: ERROR: schema "myschema" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:235)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
	... 18 more

2022-09-07 18:41:26,134 INFO  [io.quarkus] (main) quarkus-integration-test-jpa-postgresql 999-SNAPSHOT native (powered by Quarkus 999-SNAPSHOT) started in 0.162s. Listening on: http://0.0.0.0:8081
2022-09-07 18:41:26,134 INFO  [io.quarkus] (main) Profile prod activated. 
2022-09-07 18:41:26,134 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, narayana-jta, servlet, smallrye-context-propagation, vertx]
list of stored Person names:
	Person with id=1, name='Gizmo', status='LIVING', address { Address with id=1, street='Street db0c083b-c7d7-4dc6-9ff1-233f329b5c2c' }
	Person with id=3, name='Hibernate ORM', status='LIVING', address { Address with id=3, street='Street 6ba453f2-73e1-43f9-a760-06450f8c8f16' }
	Person with id=2, name='Quarkus', status='LIVING', address { Address with id=2, street='Street ac9b621e-2ee5-4588-92a5-2841fc024160' }
	
List complete.
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.638 s <<< FAILURE! - in io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase
[ERROR] io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative  Time elapsed: 0.07 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Type 'javax.xml.transform.TransformerFactory' was found in the report in target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/reports/used_classes_quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner_20220907_184005.txt
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at io.quarkus.test.junit.nativeimage.ClassInclusionReport.assertContainsNot(ClassInclusionReport.java:67)
	at io.quarkus.test.junit.nativeimage.ClassInclusionReport.assertContainsNot(ClassInclusionReport.java:53)
	at io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative(JPAFunctionalityInGraalITCase.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:904)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[INFO] Running io.quarkus.it.jpa.postgresql.JPAReflectionInGraalITCase
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 s - in io.quarkus.it.jpa.postgresql.JPAReflectionInGraalITCase
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative:25 Type 'javax.xml.transform.TransformerFactory' was found in the report in target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/reports/used_classes_quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner_20220907_184005.txt
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
```

We've first discovered it here:
https://github.com/graalvm/mandrel/runs/8220972351?check_suite_focus=true

### Expected behavior

JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative test passes.

### Actual behavior

It fails.

### How to Reproduce?

Reproducer:

1. Build quarkus at revision bc451819b26ba4a084349ebdac3532e732b618ae
2. Download a [GraalVM 22.3 dev build](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/22.3.0-dev-20220902_0358) and set as GRAALVM_HOME
3. Run `jpa-postgresql` quarkus integration test in native mode.

### Output of `java -version`

17

### GraalVM version (if different from Java)

22.3.0-dev

### Quarkus version or git rev

bc451819b26ba4a084349ebdac3532e732b618ae

### Additional information

Last worked with 4f53bdd6f377edcc783e3a91b3ea3e24794cfc81

**Comment by Sanne** [comment]
Hi @jerboaa, thanks for the report - this is going to be interesting :)

I've created this test myself, to verify some assumptions we have on how GraalVM's dead code elimination could be "guided" and enable stronger optimisations.

This implies that such a regression isn't critical in terms of functionality: the application will behave the same semantically; but it might be a performance regression - how far I don't know yet.

Essentially with this particualr integration test I was expecting us to be able to avoid needing to include the XML parser code within the native-image; there's some tricky code in the Hibernate ORM (JPA) extension that was supposed to "help" the GraalVM compiler to come to this conclusion - either this is no longer effective (changes on the compiler side?) or some other component in Quarkus has inadvertently lead to including the XML parser on its reachability graph.

However  since this only failed in GraalVM 23.3.0-dev (and not in the current one we use for integration testing), I suspect it's more likely to be due to a change in GraalVM than a change in Quarkus - otherwise we'd have seen the test fail earlier.

Admittedly the things we did in Quarkus to avoid including the parser were rather "fragile"; that's why I added this test, so to spot such cases quickly.

Do you know the range of commits in GraalVM at which it started failing?

**Comment by Sanne** [comment]
BTW the optimisation was crafted using @galderz 's scripts to analyze the reachability graph using neo4j

**Comment by jerboaa** [comment]
@Sanne Note that I didn't reproduce with a GraalVM CE dev build (used the same one) with quarkus at revision `4f53bdd6f377edcc783e3a91b3ea3e24794cfc81`, I'm not 100% sold on it being a graal issue. Does anything between `4f53bdd6f377edcc783e3a91b3ea3e24794cfc81` and `bc451819b26ba4a084349ebdac3532e732b618ae` that could have caused this?

**Comment by jerboaa** [comment]
> Admittedly the things we did in Quarkus to avoid including the parser were rather "fragile"; that's why I added this test, so to spot such cases quickly.

Could you please point me to those changes?

**Comment by jerboaa** [comment]
> Do you know the range of commits in GraalVM at which it started failing?

I'll see if I can find out. It's definitely quarkus related as well.

**Comment by Sanne** [comment]
As reference, one needs to understand the different expectations in these two tests:
 - https://github.com/quarkusio/quarkus/blob/af8b95d75ab9c8e77cfb90b4ab9aff867eae2eec/integration-tests/jpa-postgresql-withxml/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityInGraalITCase.java
 - https://github.com/quarkusio/quarkus/blob/af8b95d75ab9c8e77cfb90b4ab9aff867eae2eec/integration-tests/jpa-postgresql/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityInGraalITCase.java

N.B. these are similar tests (with same name) but located in different modules. The first one does use XML, the second does not.

This GraalVM Feature works as a "toggle", enabling support for XML in the postgresql JDBC driver if (and only if) those types are also reachable via other means:
 - https://github.com/quarkusio/quarkus/blob/57fb6526814cd66b92a4f3d40c9f638a7133a12a/extensions/jdbc/jdbc-postgresql/runtime/src/main/java/io/quarkus/jdbc/postgresql/runtime/graal/SQLXMLFeature.java

Finally, the substitutions in `io.quarkus.jdbc.postgresql.runtime.graal.PgSQLXML` apply as well

**Comment by jerboaa** [comment]
@Sanne So it looks like it's caused by this commit: https://github.com/oracle/graal/commit/89fdc4232159852300e11d2952cd1932b77b7b9a

If I had to guess, move of `NeverInline` annotation might be the issue? If that's the case adding `-H:NeverInline=<string>*` to the native image build might fix it.

**Comment by jerboaa** [comment]
I'm looking at this usage: https://github.com/quarkusio/quarkus/blob/821f5eb64ed2444bda92d34ff603dc50193c2362/extensions/jdbc/jdbc-postgresql/runtime/src/main/java/io/quarkus/jdbc/postgresql/runtime/graal/DomHelper.java#L53..L56

**Comment by Sanne** [comment]
@jerboaa thanks for finding it!

So it might be because of package changes like these?

https://github.com/oracle/graal/commit/89fdc4232159852300e11d2952cd1932b77b7b9a#diff-947ac1347c188508d95be452d074199eb5f11565d29403f98f8fd3ca1617b67bL43-R45

I don't mind if this particular optimisation is broken temporarily (we could even disable the test for a while), but I'm concerned if such changes could break any other optimisation.

As far as I know, we have very limited testing about such needs being effectively applied (this being one of them - perhaps the only test)

Considering the current `svm` artifact is being deprecated - but not removed - I would have expected the existing annotations to still be effective, or fail/warn in some way.

**Comment by Sanne** [comment]
yes I understand these were not meant as public API - can't complain too much, but would be nice to have a way for a smooth transition.

> Could we specify our needs in some way?

Since we're facing a transition, I wonder if it could be doable to have both types of annotations taken in consideration?

> Could you please comment on https://github.com/oracle/graal/issues/4862 with those use cases?

Thanks for the reference - I'll try, I don't think I know all of our use cases. @dmlloyd might know of more important/critical uses? Mine were small optimisations only.

**Comment by dmlloyd** [comment]
I think it is specifically ensuring that certain inline sites do or do not take place, particularly in performance-critical code (logging comes to mind). One can infer that the heuristic inliner doesn't always make the decisions we would want otherwise.

Maybe an alternative would be to mark some given code as "hot" or "cold" in such a way that the inliner can take that into account?

**Comment by Sanne** [comment]
Hi @dmlloyd - right I was going to ping you about this issue to ask how much of a problem you expect this to be for Logging, assuming we'll live w/o such optimisations applied during some "transition" period.

See also https://github.com/oracle/graal/issues/4862#issuecomment-1241826003

**Comment by dmlloyd** [comment]
Well that's the whole issue - we don't know from one release to the next how much of a problem it will be, or even *if* it will be a problem. All we can do is observe that the problem did exist once. And when it comes to heuristics, we cannot reliably predict the behavior even with testing because things like program size might impact (to give just one example) the number of call sites which in turn might impact the overall scoring methodology used by the inliner. So, it could be fine, or it could be quite bad.

For foundational things like logging, we can be reasonably assured that our static inline/don't inline decisions are correct. So if we have the ability to express this, then we can therefore be assured that we won't have a problem. Without that ability, we may or may not have a problem, and even if *we* don't see a problem, users might see issues depending on environmental factors that we do not replicate.

I think your comment suggests the correct approach, and easier than drastic measures like bytecode rewriting or just hoping things work out OK.

**Comment by jerboaa** [comment]
In terms of image size this means: `62.90MB` with the bug vs. `54.84MB` without on GraalVM 22.3-dev. That's `~8MB`. The workaround is to pass `-H:NeverInline='io.quarkus.jdbc.postgresql.runtime.graal.DomHelper.obfuscatedMethodName'`. I'll see if I can come up with a patch to fix it.

**Comment by jerboaa** [comment]
@Sanne Please have a look at https://github.com/quarkusio/quarkus/pull/27960. It should achieve the same thing as the old `@NeverInline` trick. Tested with Mandrel `22.3-dev` and `22.2.0-Final`.

**Comment by Sanne** [comment]
@jerboaa thanks! Well check it out more in detail next week.

Let's not forget about the general effectiveness of these annotations?

**Comment by jerboaa** [comment]
> @jerboaa thanks! Well check it out more in detail next week.

Thanks!
 
> Let's not forget about the general effectiveness of these annotations?

Was it effective in this case, though? This particular use-case seemed very strange to me. It used reflection and `@NeverInline` in order to not pull in some code in some circumstances (reachability). Given it's fragility, I went with the proposed solution which - to me - conveys the intent more clearly. The side effect is that another instance of relying on non-API annotations is gone.
