### ISSUE TITLE
Deadlock on exit in Dev Mode

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#27912]
### Describe the bug

I have a few times observed that the dev-mode can deadlock when trying to quit (e.g. by pressing `q` or `ctrl-c`). This time I connected with the debugger and got the thread dumps.

### Actual behavior

```
"Quarkus Main Thread@20220" prio=5 tid=0x110 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks vert.x-eventloop-thread-1@20223
	 blocks executor-thread-35@20229
	 waiting for executor-thread-35@20229 to release lock on <0x4f19> (a io.quarkus.vertx.http.runtime.logstream.WebSocketLogHandler)
	  at io.quarkus.vertx.http.runtime.logstream.WebSocketLogHandler.recordHistory(WebSocketLogHandler.java:63)
	  at io.quarkus.vertx.http.runtime.logstream.WebSocketLogHandler.doPublish(WebSocketLogHandler.java:39)
	  at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	  at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
	  at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:80)
	  at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
	  at org.jboss.logmanager.Logger.log(Logger.java:549)
	  at org.aesh.readline.terminal.impl.AbstractWindowsTerminal$ConsoleOutput.accept(AbstractWindowsTerminal.java:67)
	  at org.aesh.readline.terminal.impl.AbstractWindowsTerminal$ConsoleOutput.accept(AbstractWindowsTerminal.java:56)
	  at org.aesh.terminal.Connection.write(Connection.java:147)
	  at io.quarkus.deployment.console.AeshConsole.write(AeshConsole.java:395)
	  at io.quarkus.deployment.console.AeshConsole.write(AeshConsole.java:483)
	  at io.quarkus.dev.console.RedirectPrintStream.write(RedirectPrintStream.java:20)
	  at org.jboss.logmanager.handlers.UncloseableOutputStream.write(UncloseableOutputStream.java:41)
	  at org.jboss.logmanager.handlers.UncloseableOutputStream.write(UncloseableOutputStream.java:41)
	  at org.jboss.logmanager.handlers.UninterruptibleOutputStream.write(UninterruptibleOutputStream.java:81)
	  at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
	  at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
	  at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:318)
	  at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:160)
	  - locked <0x4f17> (a java.io.OutputStreamWriter)
	  at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248)
	  at java.io.BufferedWriter.flush(BufferedWriter.java:257)
	  at org.jboss.logmanager.handlers.WriterHandler.safeFlush(WriterHandler.java:165)
	  at org.jboss.logmanager.handlers.WriterHandler.flush(WriterHandler.java:135)
	  - locked <0x4f18> (a java.lang.Object)
	  at org.jboss.logmanager.ExtHandler.doPublish(ExtHandler.java:113)
	  at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:64)
	  at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	  at io.quarkus.runtime.logging.LoggingSetupRecorder$6$$Lambda$1897/0x00000008017a6b48.accept(Unknown Source:-1)
	  at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:293)
	  at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:269)
	  at io.quarkus.runtime.logging.LoggingSetupRecorder$6.publish(LoggingSetupRecorder.java:522)
	  at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
	  at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:80)
	  at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
	  at org.jboss.logmanager.Logger.log(Logger.java:708)
	  at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
	  at org.jboss.logging.Logger.infof(Logger.java:1163)
	  at io.quarkus.bootstrap.runner.Timing.printStopTime(Timing.java:116)
	  at io.quarkus.runtime.Application.stop(Application.java:225)
	  at io.quarkus.runtime.Application.stop(Application.java:155)
	  at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:222)
	  at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	  at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	  at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	  at io.quarkus.runner.GeneratedMain.main(Unknown Source:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:568)
	  at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	  at java.lang.Thread.run(Thread.java:833)
```

```
"executor-thread-35@20229" daemon prio=5 tid=0x144 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks Quarkus Main Thread@20220
	 waiting for Quarkus Main Thread@20220 to release lock on <0x4f18> (a java.lang.Object)
	  at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:53)
	  at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	  at io.quarkus.runtime.logging.LoggingSetupRecorder$6$$Lambda$1897/0x00000008017a6b48.accept(Unknown Source:-1)
	  at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:293)
	  at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:269)
	  at io.quarkus.runtime.logging.LoggingSetupRecorder$6.publish(LoggingSetupRecorder.java:522)
	  at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
	  at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:80)
	  at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
	  at org.jboss.logmanager.Logger.log(Logger.java:549)
	  at org.aesh.readline.terminal.impl.AbstractWindowsTerminal$ConsoleOutput.accept(AbstractWindowsTerminal.java:67)
	  at org.aesh.readline.terminal.impl.AbstractWindowsTerminal$ConsoleOutput.accept(AbstractWindowsTerminal.java:56)
	  at org.aesh.terminal.Connection.write(Connection.java:147)
	  at io.quarkus.deployment.console.AeshConsole.write(AeshConsole.java:395)
	  at io.quarkus.dev.console.RedirectPrintStream.write(RedirectPrintStream.java:24)
	  at io.quarkus.dev.console.RedirectPrintStream.println(RedirectPrintStream.java:134)
	  at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:763)
	  at java.lang.Throwable.printStackTrace(Throwable.java:670)
	  - locked <0x4f20> (a io.quarkus.dev.console.RedirectPrintStream)
	  at java.lang.Throwable.printStackTrace(Throwable.java:659)
	  at java.lang.Throwable.printStackTrace(Throwable.java:650)
	  at io.quarkus.vertx.http.runtime.logstream.WebSocketLogHandler.recordHistory(WebSocketLogHandler.java:70)
	  - locked <0x4f19> (a io.quarkus.vertx.http.runtime.logstream.WebSocketLogHandler)
	  at io.quarkus.vertx.http.runtime.logstream.WebSocketLogHandler.doPublish(WebSocketLogHandler.java:39)
	  at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	  at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
	  at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:80)
	  at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
	  at org.jboss.logmanager.Logger.log(Logger.java:708)
	  at org.jboss.logmanager.Logger.log(Logger.java:721)
	  at org.jboss.logging.JBossLogManagerLogger.doLog(JBossLogManagerLogger.java:42)
	  at org.jboss.logging.Logger.error(Logger.java:1507)
	  at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.handleUnrecoverableError(ResteasyReactiveRequestContext.java:629)
	  at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.handleUnrecoverableError(QuarkusResteasyReactiveRequestContext.java:55)
	  at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.handleException(AbstractResteasyReactiveContext.java:317)
	  at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:168)
	  at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:557)
	  at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1462)
	  at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	  at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:833)
```

```
"vert.x-eventloop-thread-1@20223" prio=5 tid=0x11e nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for Quarkus Main Thread@20220 to release lock on <0x4f18> (a java.lang.Object)
	  at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:53)
	  at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	  at io.quarkus.runtime.logging.LoggingSetupRecorder$6$$Lambda$1897/0x00000008017a6b48.accept(Unknown Source:-1)
	  at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:293)
	  at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:269)
	  at io.quarkus.runtime.logging.LoggingSetupRecorder$6.publish(LoggingSetupRecorder.java:522)
	  at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
	  at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:80)
	  at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
	  at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
	  at org.jboss.logmanager.Logger.log(Logger.java:708)
	  at org.jboss.logmanager.Logger.log(Logger.java:721)
	  at org.jboss.logging.JBossLogManagerLogger.doLog(JBossLogManagerLogger.java:42)
	  at org.jboss.logging.Logger.warn(Logger.java:1226)
	  at io.quarkus.opentelemetry.runtime.QuarkusContextStorage.lambda$attach$0(QuarkusContextStorage.java:72)
	  at io.quarkus.opentelemetry.runtime.QuarkusContextStorage$$Lambda$2198/0x000000080199b980.close(Unknown Source:-1)
	  at io.quarkus.opentelemetry.runtime.tracing.vertx.InstrumenterVertxTracer.sendResponse(InstrumenterVertxTracer.java:72)
	  at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer.sendResponse(HttpInstrumenterVertxTracer.java:98)
	  at io.quarkus.opentelemetry.runtime.tracing.vertx.HttpInstrumenterVertxTracer.sendResponse(HttpInstrumenterVertxTracer.java:43)
	  at io.quarkus.opentelemetry.runtime.tracing.vertx.OpenTelemetryVertxTracer.sendResponse(OpenTelemetryVertxTracer.java:47)
	  at io.quarkus.opentelemetry.runtime.tracing.vertx.OpenTelemetryVertxTracer.sendResponse(OpenTelemetryVertxTracer.java:16)
	  at io.vertx.core.http.impl.Http1xServerConnection.reportResponseComplete(Http1xServerConnection.java:259)
	  at io.vertx.core.http.impl.Http1xServerConnection.responseComplete(Http1xServerConnection.java:198)
	  at io.vertx.core.http.impl.Http1xServerConnection$$Lambda$2688/0x0000000801ae8640.run(Unknown Source:-1)
	  at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

I cannot reproduce this reliably, but I hope the thread dumps will help analyze and resolve the problem.

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19044 C70C3264 3.3.3-341.x86_64 2022-01-17 11:45 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 LTS

### Quarkus version or git rev

2.12.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by knutwannheden** [comment]
I haven't seen it again. I can otherwise reopen or create a new issue.

**Comment by gsmet** [comment]
Closing then.
