### ISSUE TITLE
[Windows Native] UnsatisfiedLinkError using Quarkus Picocli with Jansi 

### ISSUE THREAD

**Issue by lppedd** [quarkusio/quarkus#27923]
### Describe the bug

Starting from a fresh Quarkus CLI application, add the `picocli-jansi-graalvm` dependency

```
<dependency>
    <groupId>info.picocli</groupId>
    <artifactId>picocli-jansi-graalvm</artifactId>
    <version>1.2.0</version>
</dependency>
```

Initialize Jansi in your main class

```kotlin
@QuarkusMain
@Command(
    name = "cli",
    mixinStandardHelpOptions = true,
    ...
)
class MyCommand : Runnable, QuarkusApplication {
    @Inject
    lateinit var factory: CommandLine.IFactory

    override fun run() {
        ...
    }

    override fun run(vararg args: String?): Int {
        AnsiConsole.windowsInstall().use {
            return CommandLine(this, factory).execute(*args)
        }
    }
}
```

Package with 
```
mvn package -Pnative
```

Run, and you'll see the result: 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.fusesource.jansi.internal.Kernel32.SetConsoleTextAttribute(JS)I [symbol: Java_org_fusesource_jansi_internal_Kernel32_SetConsoleTextAttribute or Java_org_fusesource_jansi_internal_Kernel32_SetConsoleTextAttribute__JS]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:154)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:52)
        at org.fusesource.jansi.internal.Kernel32.SetConsoleTextAttribute(Kernel32.java)
        at org.fusesource.jansi.WindowsAnsiPrintStream.applyAttribute(WindowsAnsiPrintStream.java:131)
        at org.fusesource.jansi.WindowsAnsiPrintStream.processSetAttribute(WindowsAnsiPrintStream.java:299)
        at org.fusesource.jansi.AnsiPrintStream.processEscapeCommand(AnsiPrintStream.java:363)
        at org.fusesource.jansi.AnsiPrintStream.filter(AnsiPrintStream.java:134)
        at org.fusesource.jansi.FilterPrintStream.write(FilterPrintStream.java:98)
        at org.fusesource.jansi.FilterPrintStream.write(FilterPrintStream.java:108)
        at org.fusesource.jansi.FilterPrintStream.print(FilterPrintStream.java:157)
        at org.fusesource.jansi.FilterPrintStream.println(FilterPrintStream.java:241)
        at com.lppedd.cli.ScanCopyrightsCommand.run(ScanCopyrightsCommand.kt:45)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.lppedd.cli.MyCommand.run(ClientEclipseCommand.kt:29)
        at com.lppedd.cli.MyCommand_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:131)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### Output of `java -version`

11.0.15, vendor: Amazon.com Inc.

### GraalVM version (if different from Java)

22.2.0

### Quarkus version or git rev

2.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven (standalone) 3.8.6

**Comment by geoand** [comment]
Is this still an issue with the latest versions of Quarkus?

**Comment by lppedd** [comment]
@geoand I wouldn't be able to tell you honestly, as it's been a long time since I last worked with Quarkus.  
imo we can close the issue as it's way too old anyways.

**Comment by geoand** [comment]
Thanks for the update
