### ISSUE TITLE
Some MicroProfile Rest Client TCKs throw NoClassDefFoundError

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#2796]
**Describe the bug**
If one tries to run for example `org.eclipse.microprofile.rest.client.tck.InvokeWithJsonBProviderTest` they would be faced with a stacktrace looking something like:

```
java.lang.NoClassDefFoundError: org/jboss/resteasy/specimpl/ResteasyUriBuilder
	at io.smallrye.restclient.RestClientBuilderImpl.verifyInterface(RestClientBuilderImpl.java:263)
	at io.smallrye.restclient.RestClientBuilderImpl.build(RestClientBuilderImpl.java:138)
	at org.eclipse.microprofile.rest.client.tck.InvokeWithJsonBProviderTest.setupClient(InvokeWithJsonBProviderTest.java:78)
Caused by: java.lang.ClassNotFoundException: org.jboss.resteasy.specimpl.ResteasyUriBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

It looks the smallrye-rest-client dependency tries to use an older version of RESTEasy

Currently these tests are being [skipped](https://github.com/quarkusio/quarkus/blob/88fb38b914ff027a562cb90f78ca060456204da8/tcks/microprofile-rest-client/tck-suite.xml#L12)

**Comment by kenfinnigan** [comment]
Resolved as part of #4520
