### ISSUE TITLE
Scenarion with authorization using @ClientHeaderParam doesn't bild into native after move to reactive

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#27995]
### Describe the bug

I'm trying to migrate testing scenarios we have for quarkus-oidc-client-filter / quarkus-oidc-token-propagation / quarkus-rest-client into their reactive variants.

Changes for the move are here: https://github.com/rsvoboda/quarkus-test-suite/commit/818b36371a7f511062377b869fe34407221537f7

This is followup work after https://github.com/quarkusio/quarkus/issues/27959 fix. I tried to check the app in native mode.
And it fails to build the native app with `Detected an instance of Random/SplittableRandom class in the image heap` message, cc @geoand / @sberyozkin

```
========================================================================================================================
GraalVM Native Image: Generating 'security-keycloak-oidc-client-extended-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (10.9s @ 0.27GB)
 Version info: 'GraalVM 22.2.0 Java 17 CE'
 Java version info: '17.0.4+8-jvmci-22.2-b06'
 C compiler: cc (apple, x86_64, 14.0.0)
 Garbage collector: Serial GC
 4 user-specific feature(s)
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.jboss.threads] categories
 - io.quarkus.runtime.graal.ResourcesFeature: Register each line in META-INF/quarkus-native-resources.txt as a resource on Substrate VM
 - org.graalvm.home.HomeFinderFeature: Finds GraalVM paths and its version number
[2/7] Performing analysis...  [*]                                                                       (29.4s @ 1.59GB)
  13,750 (91.47%) of 15,033 classes reachable
  20,134 (61.09%) of 32,960 fields reachable
  68,521 (64.85%) of 105,662 methods reachable
     511 classes,   157 fields, and 1,477 methods registered for reflection
       1 native library: -framework CoreServices

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.apache.http.impl.auth.NTLMEngineImpl.getType3Message(java.lang.String, java.lang.String, java.lang.String, java.lang.String, byte[], int, java.lang.String, byte[])
Parsing context:
   at org.apache.http.impl.auth.NTLMEngineImpl.getType3Message(NTLMEngineImpl.java:181)
   at org.apache.http.impl.auth.NTLMEngineImpl.generateType3Msg(NTLMEngineImpl.java:2097)
   at org.apache.http.impl.auth.NTLMScheme.authenticate(NTLMScheme.java:142)
   at org.apache.http.impl.auth.AuthSchemeBase.authenticate(AuthSchemeBase.java:136)
   at org.apache.http.impl.auth.HttpAuthenticator.doAuth(HttpAuthenticator.java:233)
   at org.apache.http.impl.auth.HttpAuthenticator.generateAuthResponse(HttpAuthenticator.java:213)
   at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:262)
   at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
   at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
   at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:84)
   at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
   at org.keycloak.authorization.client.AuthzClient.<init>(AuthzClient.java:264)
   at org.keycloak.authorization.client.AuthzClient.create(AuthzClient.java:94)
   at io.quarkus.ts.security.keycloak.oidcclient.extended.restclient.ping.clients.LookupAuthorizationPongClient.lookupAuth(LookupAuthorizationPongClient.java:64)
   at io.quarkus.ts.security.keycloak.oidcclient.extended.restclient.ping.clients.LookupAuthorizationPongClient$$deletePongById$$5.addHeaders(Unknown Source)
   at io.quarkus.rest.client.reactive.runtime.MicroProfileRestClientRequestFilter.filter(MicroProfileRestClientRequestFilter.java:47)
   at org.jboss.resteasy.reactive.client.spi.ResteasyReactiveClientRequestFilter.filter(ResteasyReactiveClientRequestFilter.java:11)
   at org.jboss.resteasy.reactive.client.handlers.ClientRequestFilterRestHandler.handle(ClientRequestFilterRestHandler.java:24)
   at org.jboss.resteasy.reactive.client.handlers.ClientRequestFilterRestHandler.handle(ClientRequestFilterRestHandler.java:9)
   at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:224)
   at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
   at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:49)
   at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
   at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
   at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
   at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
   at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
   at io.vertx.core.impl.future.FutureBase$$Lambda$1392/0x00000007c1794000.run(Unknown Source)
   at java.lang.Shutdown.runHooks(Shutdown.java:130)
   at java.lang.Shutdown.shutdown(Shutdown.java:185)
   at com.oracle.svm.core.jdk.RuntimeSupport.shutdown(RuntimeSupport.java:158)

	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:152)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultStaticInvokeTypeFlow.update(DefaultStaticInvokeTypeFlow.java:64)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:635)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  To see how this object got instantiated use --trace-object-instantiation=java.security.SecureRandom. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
	at parsing org.apache.http.impl.auth.NTLMEngineImpl.access$000(NTLMEngineImpl.java:51)
```

The same app using non-reactive extensions works fine in native.

### Expected behavior

Application builds into native

### Actual behavior

Application fails to build into native

### How to Reproduce?

 - clone https://github.com/rsvoboda/quarkus-test-suite
 - checkout `oidc-client-reactive-filter` branch
 - run `mvn clean verify -pl security/keycloak-oidc-client-extended -Dnative -Dall-modules -Dquarkus.native.container-build=false`

You can drop `-Dquarkus.native.container-build=false` if you are on Linux or don't mind using container based build of native image.

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### GraalVM version (if different from Java)

GraalVM 22.2 Java17

### Quarkus version or git rev

Quarkus main

**Comment by rsvoboda** [comment]
I thought the fail was related `NTLMEngineImpl` and to the fact, that `resteasy-classic/rest-client` and `resteasy-classic/resteasy-mutiny-common` has dependency on `quarkus-apache-httpclient` which sets `NTLMEngineImpl` for runtime initialization. But I was wrong, adding `quarkus-apache-httpclient` didn't help.

Looking closer to the deps I realized that there is direct usage of `org.keycloak:keycloak-authz-client`.
Somehow that's not a problem for non-reactive deps, but is causing troubles for reactive deps.

I have replaced that with `io.quarkus:quarkus-keycloak-admin-client` whic also uses `org.keycloak:keycloak-authz-client` plus many other deps. I was able to build the native image. But there are test failures too :/

So there is a workaround, but would be good to understand what causes troubles in reactive stack

**Comment by sberyozkin** [comment]
@rsvoboda You have
```
<dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-authz-client</artifactId>
        </dependency>
```
and it is used here: https://github.com/quarkus-qe/quarkus-test-suite/blob/main/security/keycloak-oidc-client-extended/src/main/java/io/quarkus/ts/security/keycloak/oidcclient/extended/restclient/ping/clients/LookupAuthorizationPongClient.java#L64

This dependency and code need to be replaced.
Use `keycload-admin-client-reactve`, see the guide added by @michalvavrik.
Or you can use `quarkus-oidc-client` to get this token instead

**Comment by sberyozkin** [comment]
Sorry, forgot add a link to the guide :-)

https://quarkus.io/version/main/guides/security-keycloak-admin-client

**Comment by geoand** [comment]
So are we okay as is with this one?

**Comment by sberyozkin** [comment]
Yeah, I think it is not a Quarkus bug, Rostislav, do you agree ?

**Comment by rsvoboda** [comment]
We have possible workaround with admin client that I have to try.

Still, would be good to understand why the native image build fails after move to reactive when in non-reactive things work well (even when using `org.keycloak:keycloak-authz-client`)

**Comment by sberyozkin** [comment]
Interesting question, it might be related to the build-time/static-init of Resteasy Reactive, but not really sure

**Comment by geoand** [comment]
Yeah, it's likely a manifestation of #27752

**Comment by rsvoboda** [comment]
Thanks for the pointer to 27752.

Migration to `Keycloak` class is not easy :/

I want to move from
```java
        AuthzClient authzClient = AuthzClient.create(new Configuration(
                authUrl,
                realm,
                clientId,
                Collections.singletonMap("secret", clientSecret),
                HttpClients.createDefault()));

        String authzClientToken = authzClient.obtainAccessToken("test-user", "test-user").getToken();
```

But ...
when using 
```java
        Keycloak keycloak = KeycloakBuilder.builder()
                .serverUrl(authUrl)
                .realm(realm)
                .clientId(clientId)
                .clientSecret(clientSecret)
                .build();
```
I receive `java.lang.IllegalStateException: username required`

When using 
```java
        Keycloak keycloak = KeycloakBuilder.builder()
                .serverUrl(authUrl)
                .realm(realm)
                .clientId(clientId)
                .username("test-user")
                .password("test-user")
                .build();
```
I receive `Caused by: java.lang.RuntimeException: RestEasy 3 or 4 not found on classpath`
And I have added
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-keycloak-admin-client-reactive</artifactId>
        </dependency>
```

**Comment by michalvavrik** [comment]
> ```java
>         Keycloak keycloak = KeycloakBuilder.builder()
>                 .serverUrl(authUrl)
>                 .realm(realm)
>                 .clientId(clientId)
>                 .clientSecret(clientSecret)
>                 .build();
> ```
that's because you don't have grantType("client_credentials")

**Comment by rsvoboda** [comment]
with `.grantType("client_credentials")` I end up with `Caused by: java.lang.RuntimeException: RestEasy 3 or 4 not found on classpath`

**Comment by rsvoboda** [comment]
```
[ERROR] testLookupAuthorization  Time elapsed: 1.423 s  <<< ERROR!
java.lang.ExceptionInInitializerError
    at org.keycloak.admin.client.spi.ResteasyClientClassicProvider.newRestEasyClient(ResteasyClientClassicProvider.java:35)
    at org.keycloak.admin.client.Keycloak.newRestEasyClient(Keycloak.java:98)
    at org.keycloak.admin.client.Keycloak.<init>(Keycloak.java:89)
    at org.keycloak.admin.client.KeycloakBuilder.build(KeycloakBuilder.java:152)
```

Why is `ResteasyClientClassicProvider` used ?

**Comment by michalvavrik** [comment]
IMHO `io.quarkus.keycloak.admin.client.reactive.runtime.ResteasyReactiveKeycloakAdminClientRecorder#setClientProvider` is never called as strictly speaking the application that is running the test (where you are creating the Keycloak builder) does not use the extension. It's the app you are testing that is using the extension. Do same inside tested app and you should avoid the ex.

**Comment by rsvoboda** [comment]
I need to use `ResteasyReactiveClientProvider` :/

```java
        ResteasyReactiveClientProvider rrcProvider = new ResteasyReactiveClientProvider();
        Keycloak keycloak = KeycloakBuilder.builder()
                .serverUrl(authUrl)
                .realm(realm)
                .resteasyClient(rrcProvider.newRestEasyClient(null, null, false))
                .clientId(clientId)
                .grantType("client_credentials")
                .clientSecret(clientSecret)
                .build();
```

**Comment by sberyozkin** [comment]
The easiest option would definitely be using `OidcClient` - why the injection is not possible in the test endpoint ?

@michalvavrik Should `keycloak-admin-client-reactive` also have `ResteasyReactiveClientProvider` used to create a client when preparing `Keycloak` injection ?

**Comment by sberyozkin** [comment]
We have the test involving the injected `Keycloak` and `keycloak-admin-client-reactive` (in `integration-tests/keycloak-authorization`)  but that works without it - not sure what is different in this case

**Comment by rsvoboda** [comment]
I moved back to LookupAuthorizationPongClient#lookupAuth() and I have working solution. I used test based approach just to see the stacktrace.
In LookupAuthorizationPongClient#lookupAuth() I do not need ResteasyReactiveClientProvider, Quarkus makes it work for me :)

**Comment by sberyozkin** [comment]
Sounds good

**Comment by rsvoboda** [comment]
The native part trouble seems to be #27752, for `Keycloak` part I think there is no functional issue.
Just some usability concerns, I may create small docs update once I sort out my ideas.

**Comment by rsvoboda** [comment]
(I have updated https://github.com/rsvoboda/quarkus-test-suite/tree/oidc-client-reactive-filter with commit to unblock native build)
