### ISSUE TITLE
Undertow: servletContext.getResourcePaths("/") not listed in PROD mode

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#28028]
### Describe the bug

I have a simple ApplicationInitializer to print out all the available servlet resource paths...

```java
public class ApplicationInitializer implements ServletContainerInitializer {

	private static final Logger logger = Logger.getLogger(ApplicationInitializer.class.getName());

	@Override
	public void onStartup(Set<Class<?>> c, ServletContext servletContext) throws ServletException {
		logger.info("Checking servlet resource paths...");

		Set<String> resourcePaths = servletContext.getResourcePaths("/");
		for (String resourcePath : resourcePaths) {
			logger.info("Resource: " + resourcePath);
		}
		
		if (resourcePaths.isEmpty()) {
			logger.warning("NO servlet resource paths found!");
		}
	}
}
```

When running in **DEV** mode `mvn quarkus:dev` the following is printed out it finds the mapped `/index.html`:
```
2022-09-17 07:51:08,575 INFO  [org.acm.ApplicationInitializer] (Quarkus Main Thread) Checking servlet resource paths...
2022-09-17 07:51:08,577 INFO  [org.acm.ApplicationInitializer] (Quarkus Main Thread) Resource: /index.html
```

When running in **PRD** mode `mvn clean package -DskipTests && java -jar target/quarkus-app/quarkus-run.jar` it doesn't find anything:
```
2022-09-17 07:49:05,376 INFO  [org.acm.ApplicationInitializer] (main) Checking servlet resource paths...
2022-09-17 07:49:05,376 WARNING [org.acm.ApplicationInitializer] (main) NO servlet resource paths found!
```

### Expected behavior

All servlet resource paths should be available in both DEV and PRD mode.

### Actual behavior

Resource Paths are only available in DEV mode.

### How to Reproduce?

[quarkus-servlet.zip](https://github.com/quarkusio/quarkus/files/9591559/quarkus-servlet.zip)

1. Unzip the reproducer attached
2. Run `mvn clean quarkus:dev` and see the servlet paths printed out `2022-12-27 13:00:20,489 INFO  [org.acm.ApplicationInitializer] (Quarkus Main Thread) Resource: /index.html`
3. Run `mvn clean package -DskipTests && java -jar target/quarkus-app/quarkus-run.jar` and see the WARNING that no paths found `2022-12-27 13:01:06,297 WARNING [org.acm.ApplicationInitializer] (main) NO servlet resource paths found!`

### Output of `uname -a` or `ver`

OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Output of `java -version`

OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### Quarkus version or git rev

2.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0) Maven home: C:\Tools\apache-maven-3.8.5 Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: C:\Tools\jdk-11.0.10 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by melloware** [comment]
cc @sberyozkin @stuartwdouglas 

I have a feeling the bug is right here especially since there is a `TODO` still there about in PRD mode its not scanning the JARs properly for files but it is in DEV mode because its looking at the File Paths.

https://github.com/quarkusio/quarkus/blob/9ed77a64d671b65db866ea6759a7cb06c94bd7d5/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/UndertowDeploymentRecorder.java#L184-L196

**Comment by melloware** [comment]
@manovotn was hoping you could look at this one?

**Comment by manovotn** [comment]
@melloware not sure how you arrived at my name as I haven't done much in Undertow, but I could take a look once I am back from X-mass break. I am unlikely to know though as I am unfamiliar with UT codebase :⁠-⁠)

**Comment by melloware** [comment]
Sorry @manovotn you answered on the other Undertow ticket but it should have been @mkouba !

**Comment by manovotn** [comment]
No problem. Like I said, I can take a look once I am operational again.
I think Martin will be in very much the same situation :⁠-⁠)

**Comment by mkouba** [comment]
I believe that the problem lies in the [DirectoryResource#list()](https://github.com/quarkusio/quarkus/blob/main/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/KnownPathResourceManager.java#L119-L134) method. It returns an empty list because the `KnownPathResourceManager#files` looks like `["index.html"]`. I don't think that `NavigableSet.headSet(String)` could be used here but maybe I've overlooked something. 

@stuartwdouglas could you pls take a look sometime next year ;-)

**Comment by melloware** [comment]
@stuartwdouglas bump ?

**Comment by melloware** [comment]
This bug is still happening in 999-SNAPSHOT.

**Comment by melloware** [comment]
@stuartwdouglas just found another bug with all your latest changes that was working:

https://github.com/melloware/quarkus-faces/issues/282

Basically I have resources in `\META-INF\resources\java\org\primefaces\showcase\convert\CountryConverter.java` as I copy the Java files there so they can be displayed.  In Windows it can find the resource but in Linux with the exact same JAR file it fails in Linux.

**Windows** Works:
```shell
java -jar target/quarkus-app/quarkus-run.jar
```

**Linux** with same JAR fails:
```shell
java -jar target/quarkus-app/quarkus-run.jar
```

**Error:**

```
An error occured while initializing MyFaces: Unable to get listed resource java\org\primefaces\showcase\convert\CountryConverter.java from directory  for path  from underlying manager io.undertow.server.handlers.resource.ClassPathResourceManager@5c059a68: java.lang.RuntimeException: Unable to get listed resource java\org\primefaces\showcase\convert\CountryConverter.java from directory  for path  from underlying manager io.undertow.server.handlers.resource.ClassPathResourceManager@5c059a68
2023-06-07 14:24:34     at io.quarkus.undertow.runtime.KnownPathResourceManager$DirectoryResource.list(KnownPathResourceManager.java:151)
2023-06-07 14:24:34     at io.undertow.server.handlers.resource.CachedResource.list(CachedResource.java:110)
```

Reported: https://github.com/melloware/quarkus-faces/issues/282

**Comment by melloware** [comment]
I just submitted another fix: https://github.com/quarkusio/quarkus/pull/34611

**Comment by tonyherstell** [comment]
Fails fopr me on Windows.
Sent the code to mate with a mac to build and deploy and it worked.

**Comment by melloware** [comment]
I think @gsmet fix here: https://github.com/quarkusio/quarkus/pull/43694 will fix this issue but I will test for real when its released with a real JSF app that has the issue

**Comment by melloware** [comment]
circling back to this i don't think @gsmet fix fixes this particular issue. I think this code needs to be modified to look in JAR or File Path like FlyWay does like this using `ClassPathUtils.consumeAsPaths`

```java
ClassPathUtils.consumeAsPaths(Thread.currentThread().getContextClassLoader(), location, path -> {
                Set<String> applicationMigrations = null;
                try {
                    applicationMigrations = FlywayProcessor.this.getApplicationMigrationsFromPath(finalLocation, path);
                } catch (IOException e) {
                    LOGGER.warnv(e,
                            "Can't process files in path %s", path);
                }
                if (applicationMigrations != null) {
                    applicationMigrationResources.addAll(applicationMigrations);
                }
            });
```

**Comment by tandraschko** [comment]
Found the same issue, which breaks Faces AUTOMATIC_EXTENSIONLESS_MAPPING

See https://issues.apache.org/jira/browse/MYFACES-4707
