### ISSUE TITLE
Redis GET with byte[] as type leads to unmarshaling exception

### ISSUE THREAD

**Issue by jendib** [quarkusio/quarkus#28029]
### Describe the bug

I'm using this example <https://quarkus.io/guides/redis-reference#storing-binary-data> to get a value storing byte data and I'm getting this exception:
```
io.vertx.core.json.DecodeException: Failed to decode:Illegal character ((CTRL-CHAR, code 5)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 2]
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromParser(QuarkusJacksonJsonCodec.java:128)
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromBuffer(QuarkusJacksonJsonCodec.java:100)
	at io.vertx.core.json.Json.decodeValue(Json.java:119)
	at io.quarkus.redis.datasource.codecs.Codecs$JsonCodec.decode(Codecs.java:44)
	at io.quarkus.redis.runtime.datasource.Marshaller.decode(Marshaller.java:92)
	at io.quarkus.redis.runtime.datasource.Marshaller.decode(Marshaller.java:83)
	at io.quarkus.redis.runtime.datasource.AbstractStringCommands.decodeV(AbstractStringCommands.java:59)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
	at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
```

It seems that even if I'm using a byte[] type it tries to unmarshall the value as JSON.

In `io.quarkus.redis.datasource.codecs.Codecs.getDefaultCodecFor` it defaults to `JsonCodec`, maybe we need a new codec doing nothing for byte[]?

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.12.2

**Comment by cescoffier** [comment]
You are right. Can you try the PR I just opened? (https://github.com/quarkusio/quarkus/pull/28036)

**Comment by jendib** [comment]
@cescoffier Is there an easy way to try it?

**Comment by cescoffier** [comment]
You would need to check out the `main` branch and build it. See https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#checking-an-issue-is-fixed-in-main.

Alternatively, you can try the snapshots, but it's not very reliable.
