### ISSUE TITLE
Jakarta - EE 10 - RESTEasy 6.2 - Issue with config converter not being registered in native

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#28052]
`MultipartResourceIT.testMultipartDataIsSent` is failing in native mode because of the following issue:

```
Caused by: java.lang.IllegalArgumentException: SRCFG00013: No Converter registered for class org.jboss.resteasy.spi.config.Threshold
	at io.smallrye.config.SmallRyeConfig.requireConverter(SmallRyeConfig.java:484)
	at io.smallrye.config.SmallRyeConfig.lambda$getOptionalConverter$1(SmallRyeConfig.java:468)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.smallrye.config.SmallRyeConfig.getOptionalConverter(SmallRyeConfig.java:467)
	at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:337)
	at org.jboss.resteasy.microprofile.config.ConfigConfiguration.getOptionalValue(ConfigConfiguration.java:41)
	at org.jboss.resteasy.spi.config.Options.getProperty(Options.java:122)
	at org.jboss.resteasy.spi.config.Options.getProperty(Options.java:116)
	at org.jboss.resteasy.spi.config.Options.getValue(Options.java:72)
	at org.jboss.resteasy.spi.EntityOutputStream.<init>(EntityOutputStream.java:125)
	at org.jboss.resteasy.client.jaxrs.engines.ClientEntityOutputStream.<init>(ClientEntityOutputStream.java:50)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.writeRequestBodyToOutputStream(ManualClosingApacheHttpClient43Engine.java:664)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.buildEntity(ManualClosingApacheHttpClient43Engine.java:635)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.loadHttpMethod(ManualClosingApacheHttpClient43Engine.java:561)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:371)
```

**Comment by gsmet** [comment]
@radcortez how should the converter be registered in native? I would expect the SmallRye Config extension to detect and register them? Or do we need to do something in the RESTEasy extension?

**Comment by radcortez** [comment]
They are using the implicit converter mechanics of `valueOf` in `org.jboss.resteasy.spi.config.Threshold`. There is no specific converter for `org.jboss.resteasy.spi.config.Threshold` and because this is a programmatic call, there is no way for us to know that we need to register `org.jboss.resteasy.spi.config.Threshold#valueOf` for reflection.

We either register it manually or provide an actual `Converter` for that class.

**Comment by gsmet** [comment]
@radcortez so my understanding is that just creating a converter in RESTEasy and adding a `META-INF/services/org.eclipse.microprofile.config.spi.Converter` file registering it would be enough to make it work in native?

**Comment by radcortez** [comment]
Yes.

Or manually registering `org.jboss.resteasy.spi.config.Threshold#valueOf` for reflection in a `@BuildStep`.

**Comment by gsmet** [comment]
Yeah, I'm trying to avoid that but I will do it if it's not an option to fix it on the RESTEasy side.

**Comment by radcortez** [comment]
Or we can also add the converter on our side.

**Comment by gsmet** [comment]
Yeah, I'll discuss with James and decide from there.

**Comment by gsmet** [comment]
Fixed in https://github.com/quarkusio/quarkus/commit/55b72299586bdb379a5a257d2f3011a681db376b .
