### ISSUE TITLE
java.lang.ExceptionInInitializerError for throw new WebApplicationException("Person with id of " + id + " does not exist.", 404);

### ISSUE THREAD

**Issue by poldinik** [quarkusio/quarkus#2813]
I'm trying to implement a simple PUT method with WebApplicationException (in case entityManager doesn't find anything in db). This is my method

```
    @PUT
    @Path("{id}")
    @Transactional
    public Person update(@PathParam Integer id, Person person) {

        Person entity = entityManager.find(Person.class, id);

        if (entity == null) {
            throw new WebApplicationException("Person with id of " + id + " does not exist.", 404);
        }

        entity.setFirstName(person.getFirstName());

        return entity;
    }

```
When I run in quarkus dev mode, I get

> java.lang.ExceptionInInitializerError
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at java.base/java.lang.Class.newInstance(Class.java:584)
> 	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:118)
> 	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:105)
> 	at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:132)
> 	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:87)
> 	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup.handleHotDeploymentRequest(UndertowHotReplacementSetup.java:56)
> 	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup$1$1.handleRequest(UndertowHotReplacementSetup.java:37)
> 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
> 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
> 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
> 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1416)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.lang.RuntimeException: Failed to start quarkus
> 	at io.quarkus.runner.ApplicationImpl2.<clinit>(Unknown Source)
> 	... 18 more
> Caused by: java.lang.UnsupportedOperationException
> 	at org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
> 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
> 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
> 	at io.quarkus.runner.RuntimeClassLoader.handleTransform(RuntimeClassLoader.java:237)
> 	at io.quarkus.runner.RuntimeClassLoader.loadClass(RuntimeClassLoader.java:191)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 	at studio.volare.resource.PeopleResource_Bean.<init>(Unknown Source)
> 	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
> 	at io.quarkus.arc.ArcContainerImpl.<init>(ArcContainerImpl.java:95)
> 	at io.quarkus.arc.Arc.initialize(Arc.java:34)
> 	at io.quarkus.arc.runtime.ArcDeploymentTemplate.getContainer(ArcDeploymentTemplate.java:43)
> 	at io.quarkus.deployment.steps.ArcAnnotationProcessor$build25.deploy(Unknown Source)
> 	... 19 more

It works if I remove `throw new WebApplicationException("Person with id of " + id + " does not exist.", 404);`

**Comment by poldinik** [comment]
import arc ext
