### ISSUE TITLE
@MultipartForm not support record

### ISSUE THREAD

**Issue by TheBlindM** [quarkusio/quarkus#28143]
### Describe the bug

```
2022-09-22 14:38:35,887 ERROR [com.exa.con.ErrHandle] (executor-thread-0) 失败 to handle request: java.lang.NoSuchMethodException: com.example.module.dto.fileManager.UploadDTO.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3641)
	at java.base/java.lang.Class.newInstance(Class.java:665)
	at org.jboss.resteasy.plugins.providers.multipart.MultipartFormAnnotationReader.readFrom(MultipartFormAnnotationReader.java:63)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:101)
	at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:63)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:80)
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:213)
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:95)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:128)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Output of `uname -a` or `ver`

windows 10

### Output of `java -version`

java17

### Quarkus version or git rev

2.11.2.Final

**Comment by geoand** [comment]
cc @jamesnetherton

**Comment by geoand** [comment]
@FroMage we should probably also add this to RESTEasy Reactive don't you think?

**Comment by FroMage** [comment]
Well, sure. But this is related to `@BeanParam` now ;)

**Comment by geoand** [comment]
@FroMage this is the exact same problem as we were discussing in #19686

**Comment by FroMage** [comment]
OK, so let's merge those issues ;)

**Comment by FroMage** [comment]
The other one has more docs/discussion.

**Comment by FroMage** [comment]
Wait wait, this is a RESTEAsy classic issue, not Reactive.

**Comment by FroMage** [comment]
Or not, let's be honest.

**Comment by geoand** [comment]
😂

**Comment by geoand** [comment]
@jamezp has RESTEasy by any chance added record support for multipart?

**Comment by jamezp** [comment]
@geoand Depends on media type for the multipart part. Is there some kind of code snippet or reproducer for this? I just want to understand where/how the record is being used.

**Comment by geoand** [comment]
Not that I know of, but you can likely take the code in https://docs.jboss.org/resteasy/docs/6.2.10.Final/userguide/#_multipartform_annotation and use records instead of classes

**Comment by jnbdz** [comment]
@jamezp you asked for a reproducer back in September 2024 — here is one, and it still fails on current main (6ce0ccbb857).

```java
public record UploadRecord(@FormParam @PartType(MediaType.TEXT_PLAIN) String name) {
}

@Path("/rec")
public static class Res {
    @POST
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.TEXT_PLAIN)
    public String post(@MultipartForm UploadRecord form) {
        return "got=" + form.name();
    }
}
```

POSTing a single `name` part gives:

```
status=400
java.lang.NoSuchMethodException: ...UploadRecord.<init>()
```

which matches the original report exactly.

**Why it cannot work today.** In `resteasy-multipart-provider` 7.0.4.Final, `MultipartFormAnnotationReader.readFrom` does:

1. `clazz.newInstance()` — requires a public no-arg constructor
2. `setFields(clazz, input, obj)` — reflectively assigns the fields afterwards

That construct-then-mutate shape is fundamentally incompatible with records: they have no no-arg constructor, and their fields are final. So this is not a matter of the reader happening to miss a case — the whole instantiation strategy would need a record branch that reads the parts first and passes them to the canonical constructor.

I also checked every class in `resteasy-multipart-provider` 7.0.4.Final for `Class.isRecord` / `getRecordComponents` and found none, so there is no record handling anywhere in the provider yet.

For reference, Quarkus REST (Reactive) supports records as parameter containers — `BeanParamRecordTest` and friends in `rest/deployment` cover it — which is presumably why this only bites RESTEasy Classic users.

Since the instantiation happens entirely inside RESTEasy, Quarkus cannot fix this on its own, so I have opened the fix upstream: resteasy/resteasy#5021. When the container class is a record, `MultipartFormAnnotationReader` now resolves each record component against the form data and invokes the canonical constructor instead of `newInstance()` + `setFields`. The reproducer above is the test in that PR, and it fails without the change with exactly the `<init>()` error. Once that lands in a RESTEasy release Quarkus picks up, I will add the Quarkus-side test here.

---

*Edited: replaced the "would you take this?" question that used to end this comment with a link to the upstream fix, resteasy/resteasy#5021. Everything else is unchanged.*
