### ISSUE TITLE
Keycloak policy enforcer does not find newly created resource... even if it appears in RTP token

### ISSUE THREAD

**Issue by cthiebault** [quarkusio/quarkus#28258]
### Describe the bug

I'm using Keycloak policy enforcer to protect my entities.
For each entity I have a resource, a user policy for readers and a read permission. 

On entity creation, all these authorization resources are created in Keycloak but the policy enforcer cannot find the newly created resource.

When I evaluate this with Keycloak UI, access is granted.

To show this, I've created a simple app:
[https://github.com/cthiebault/quarkus-keyclaok-authz](https://github.com/cthiebault/quarkus-keyclaok-authz)

The application is a simple REST API that allows to manage albums.

- POST `/api/albums`
- GET `/api/albums/{id}`
- PUT `/api/albums/{id}`

Any authenticated user with `user` role can create album using `POST` or `PUT`.  
They can then access their own albums using `GET`.

Users with `admin` role can access all albums.

For each created album, the application creates in Keycloak:

- a resource `album:{id}` with uri `/api/albums/{id}` and `GET` scope
- a user policy `album:{id}:readers` with current user as member
- a scope permission `album:{id}:read` for
  - `album:{id}` resource
  - `album:{id}:readers` policy
  - `GET` scope

During `AlbumApiTest`, the album is well created, same for keycloak authz resource, policy & permission.   
But when I try to access the album using `GET`, I get a 403:

```text
DEBUG [org.key.ada.aut.AbstractPolicyEnforcer] Checking permissions for path [http://localhost:8081/api/albums/1] with config [PathConfig{name='album:1', type='album', path='/api/albums/1', scopes=[GET], id='1', enforcerMode='ENFORCING'}].
DEBUG [org.key.ada.aut.KeycloakAdapterPolicyEnforcer] Obtaining authorization for authenticated user.
DEBUG [org.key.ada.aut.KeycloakAdapterPolicyEnforcer] Authorization failed: java.lang.RuntimeException: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 400 / Bad Request / Response from server: {"error":"invalid_resource","error_description":"Resource with id [1] does not exist."}
	at org.keycloak.authorization.client.util.Throwables.handleAndWrapHttpResponseException(Throwables.java:99)
	at org.keycloak.authorization.client.util.Throwables.handleWrapException(Throwables.java:42)
	at org.keycloak.authorization.client.util.Throwables.retryAndWrapExceptionIfNecessary(Throwables.java:65)
	at org.keycloak.authorization.client.resource.AuthorizationResource.authorize(AuthorizationResource.java:98)
	at org.keycloak.adapters.authorization.KeycloakAdapterPolicyEnforcer.requestAuthorizationToken(KeycloakAdapterPolicyEnforcer.java:167)
	at org.keycloak.adapters.authorization.KeycloakAdapterPolicyEnforcer.isAuthorized(KeycloakAdapterPolicyEnforcer.java:66)
	at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.authorize(AbstractPolicyEnforcer.java:121)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:64)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:28)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$1$1$1.run(HttpAuthorizer.java:74)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:557)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 400 / Bad Request / Response from server: {"error":"invalid_resource","error_description":"Resource with id [1] does not exist."}
	at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:95)
	at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
	at org.keycloak.authorization.client.resource.AuthorizationResource$1.call(AuthorizationResource.java:92)
	at org.keycloak.authorization.client.resource.AuthorizationResource$1.call(AuthorizationResource.java:74)
	at org.keycloak.authorization.client.resource.AuthorizationResource.authorize(AuthorizationResource.java:96)
```

But when introspecting the RTP token, I see that `authorization` seems correct:

```json
{
  "authorization": {
    "permissions": [
      {
        "scopes": [ "GET" ],
        "rsid": "1",
        "rsname": "album:1"
      },
      {
        "scopes": [ "POST" ],
        "rsid": "a7603402-05ec-43ab-bc47-e8e7808769fd",
        "rsname": "Albums resource"
      },
      {
        "scopes": [ "PUT" ],
        "rsid": "561a2d9d-8654-40c6-89df-7868599db78f",
        "rsname": "Create albums resource"
      }
    ]
  }
}
```

It seems the policy enforcer cannot find the newly created resource :-(

When I evaluate this with Keycloak UI, access is granted.

## Keycloak authorization config

Here is the default Keycloak authorization config in `quarkus-realm.json`:

**Resources:**

 ```json
[
  {
    "name": "Albums resource",
    "uris": [ "/api/albums" ],
    "scopes": [
      { "name": "GET" },
      { "name": "POST" }
    ]
  },
  {
    "name": "Create albums resource",
    "uris": [ "/api/albums/{id}" ],
    "scopes": [
      { "name": "PUT" }
    ]
  }
]
```

**Policies & permissions:**

```json
[
  {
    "name": "Any User Policy",
    "description": "Any user granted with the user role can access something",
    "type": "role",
    "logic": "POSITIVE",
    "decisionStrategy": "UNANIMOUS",
    "config": {
      "roles": "[{\"id\":\"user\",\"required\":false}]"
    }
  },
  {
    "name": "Any Admin Policy",
    "description": "Any user granted with the admin role can access something",
    "type": "role",
    "logic": "POSITIVE",
    "decisionStrategy": "UNANIMOUS",
    "config": {
      "roles": "[{\"id\":\"admin\",\"required\":false}]"
    }
  },
  {
    "name": "Post new album permission",
    "type": "scope",
    "logic": "POSITIVE",
    "decisionStrategy": "UNANIMOUS",
    "config": {
      "resources": "[\"Albums resource\"]",
      "scopes": "[\"POST\"]",
      "applyPolicies": "[\"Any User Policy\"]"
    }
  },
  {
    "name": "Put new album permission",
    "type": "scope",
    "logic": "POSITIVE",
    "decisionStrategy": "UNANIMOUS",
    "config": {
      "resources": "[\"Create albums resource\"]",
      "scopes": "[\"PUT\"]",
      "applyPolicies": "[\"Any User Policy\"]"
    }
  }
]
```

### Expected behavior

Policy enforcer should find the album resource.

The RTP token finds it, but the policy enforcer does not.

### Actual behavior

As the album resource is not found, we get a 403 error.

### How to Reproduce?

I've created a simple repo to reproduce error:
https://github.com/cthiebault/quarkus-keyclaok-authz

### Quarkus version or git rev

2.12.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by sberyozkin** [comment]
Hey @pedroigor Can you please review this issue ?
@cthiebault Thanks for a detailed analysis, it sounds like it is a Keycloak issue as `quarkus-keycloak-authorization` does not do any direct resolution of these resources, only via the authorization client API

**Comment by pritesh90** [comment]
Hi @cthiebault,
Did you find any alternate solution for this?

Thanks.
