### ISSUE TITLE
Resteasy-Reactive: Reactive REST-Endpoints throw in conjunction with `@Produces`

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#28277]
### Describe the bug

All REST endpoints with reactive datatypes throw an exception when using a reactive database driver in a `@Produces` method.

### Expected behavior

All REST endpoints can be called without exception.

### Actual behavior

All reactive REST endpoints throw the following exception:

```
java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-1
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)
	at org.acme.Producers.produceFruitsProvider(Producers.kt:31)
	at org.acme.Producers_Subclass.produceFruitsProvider$$superforward1(Unknown Source)
	at org.acme.Producers_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.Producers_Subclass.produceFruitsProvider(Unknown Source)
	at org.acme.Producers_ProducerMethod_produceFruitsProvider_0d1962ada685f43eed212984b66482627192929c_Bean.create(Unknown Source)
	at org.acme.Producers_ProducerMethod_produceFruitsProvider_0d1962ada685f43eed212984b66482627192929c_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
	at org.acme.Producers_ProducerMethod_produceFruitsProvider_0d1962ada685f43eed212984b66482627192929c_Bean.get(Unknown Source)
	at org.acme.Producers_ProducerMethod_produceFruitsProvider_0d1962ada685f43eed212984b66482627192929c_Bean.get(Unknown Source)
	at org.acme.FruitsService_Bean.create(Unknown Source)
	at org.acme.FruitsService_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:19)
	at org.acme.FruitsService_ClientProxy.arc$delegate(Unknown Source)
	at org.acme.FruitsService_ClientProxy.getFruits(Unknown Source)
	at org.acme.FruitsResource.getFruitsUni(FruitsResource.kt:27)
	at org.acme.FruitsResource_Subclass.getFruitsUni$$superforward1(Unknown Source)
	at org.acme.FruitsResource_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.FruitsResource_Subclass.getFruitsUni(Unknown Source)
	at org.acme.FruitsResource_ClientProxy.getFruitsUni(Unknown Source)
	at org.acme.FruitsResource$quarkusrestinvoker$getFruitsUni_cfe06f702303e237270c2970126507ce10869d96.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:115)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:49)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.handle(VertxHttpHotReplacementSetup.java:196)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.handle(VertxHttpHotReplacementSetup.java:185)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

[reproducer.zip](https://github.com/quarkusio/quarkus/files/9672379/reproducer.zip)

1. `docker run -it --rm=true --name quarkus_test -e POSTGRES_USER=quarkus_test -e POSTGRES_PASSWORD=quarkus_test -e POSTGRES_DB=quarkus_test -p 5432:5432 postgres:14.1`
2. Start Server
3. Browse to `http://localhost:8080/fruitsUni` or `http://localhost:8080/fruitsSuspend` or `http://localhost:8080/fruitsNonBlocking`

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.13.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

### Additional information

The bug is also included in Quarkus 2.12.3.Final.

**Comment by geoand** [comment]
In case the error in not sufficiently explanatory: In

```kotlin
    @Produces
    @Singleton
    fun produceFruitsProvider(): FruitsProvider {
        val query = client.query("SELECT name FROM fruits")
        val fruits = query.execute().await().indefinitely().map { Fruit(it.getString("name")) }
        return FruitsProvider(fruits)
    }
```

you are trying to obtain an instance of `FruitsProvider` by awaiting indefinitely for a result, which is not allowed.

You'll need to refactor your code to avoid such kind of blocking.

**Comment by mschorsch** [comment]
@geoand I wasn't sure so i opened this bug report. Thanks for your feedback.

**Comment by geoand** [comment]
No problem
