### ISSUE TITLE
Creating a Linux executable without GraalVM installed in macos

### ISSUE THREAD

**Issue by paomian** [quarkusio/quarkus#28311]
### Describe the bug

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.12.3.Final:build (default) on project xxx: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to pull builder image quay.io/quarkus/ubi-quarkus-native-image:22.2-java17
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner.setup(NativeImageBuildContainerRunner.java:57)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:214)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.io.IOException: Cannot run program "docker": error=2, No such file or directory
[ERROR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
[ERROR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
[ERROR] 	at io.quarkus.deployment.util.ProcessUtil.launchProcess(ProcessUtil.java:34)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner.setup(NativeImageBuildContainerRunner.java:54)
[ERROR] 	... 12 more
[ERROR] Caused by: java.io.IOException: error=2, No such file or directory
[ERROR] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[ERROR] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
[ERROR] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
[ERROR] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
[ERROR] 	... 15 more
```

### Expected behavior

I think it can find docker program.
I installed docker command-line.
but my docker context is in a lima instances.
```
docker context ls
NAME                    DESCRIPTION                               DOCKER ENDPOINT                                               KUBERNETES ENDPOINT   ORCHESTRATOR
default                 Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                                                         swarm
lima-docker-rootful *                                             unix:///Users/username/.lima/docker-rootful/sock/docker.sock
```

### How to Reproduce?

1. install lima
2. crete lima docker-rootful instance
3. create quarkus project
4. set `quarkus.native.remote-container-build=true quarkus.native.container-runtime=docker` in `application.properties`
5. add `Dockerfile.multistage`
6. run docker build -f src/main/docker/Dockerfile.multistage -t test/test .

Dockerfile.multistage
```
## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/ubi-quarkus-native-image:21.3.2-java17 AS build
COPY --chown=quarkus:quarkus mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/
USER quarkus
WORKDIR /code
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
COPY src /code/src
RUN ./mvnw package -Pnative

## Stage 2 : create the docker final image
FROM quay.io/quarkus/quarkus-micro-image:1.0
WORKDIR /work/
COPY --from=build /code/target/*-runner /work/application

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

.dockerignore
```
*
!mvnw
!.mvn
!pom.xml
!src
!target/*-runner
!target/*-runner.jar
!target/lib/*
!target/quarkus-app/*
```

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk 17.0.4.1 2022-08-12 OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1) OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

### Quarkus version or git rev

2.12.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by paomian** [comment]
It is ok. I make a mistake.
I add `quarkus.native.container-build` config in `application.properties` so it will be require docker when  build in  already build in docker.
