### ISSUE TITLE
[2.13.0.Final]: /q/dev UI throws an error when navigating to "Configuration" -> "Config Editor"

### ISSUE THREAD

**Issue by htl-leonding** [quarkusio/quarkus#28334]
### Describe the bug

/q/dev UI throws an StringIndexOutOfBoundsException-error when navigating to "Configuration" -> "Config Editor"
Same behaviour like described in https://github.com/quarkusio/quarkus/issues/27345

The "Configuration" -> "Dev Services" work as expected

### Expected behavior

html page w/ config options 

### Actual behavior

error message:

java.lang.StringIndexOutOfBoundsException: Range [1, 0) out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4602)
	at java.base/java.lang.String.substring(String.java:2715)
	at io.quarkus.vertx.http.runtime.devmode.ConfigDescriptionsManager.calculate(ConfigDescriptionsManager.java:110)
	at io.quarkus.vertx.http.runtime.devmode.ConfigDescriptionsManager.values(ConfigDescriptionsManager.java:62)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.qute.GetterAccessor.getValue(GetterAccessor.java:22)
	at io.quarkus.qute.ReflectionValueResolver.resolve(ReflectionValueResolver.java:59)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:207)
	at io.quarkus.qute.EvaluatorImpl.resolveReference(EvaluatorImpl.java:127)
	at io.quarkus.qute.EvaluatorImpl.lambda$evaluate$0(EvaluatorImpl.java:74)
	at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:232)
	at io.quarkus.qute.EvaluatorImpl.evaluate(EvaluatorImpl.java:72)
	at io.quarkus.qute.ResolutionContextImpl$ChildResolutionContext.evaluate(ResolutionContextImpl.java:87)
	at io.quarkus.qute.LoopSectionHelper.resolve(LoopSectionHelper.java:44)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:182)
	at io.quarkus.qute.InsertSectionHelper.resolve(InsertSectionHelper.java:20)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:182)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:46)
	at io.quarkus.qute.Parser$1.resolve(Parser.java:1231)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.IncludeSectionHelper.lambda$resolve$1(IncludeSectionHelper.java:63)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:144)
	at io.quarkus.qute.IncludeSectionHelper.resolve(IncludeSectionHelper.java:47)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:178)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:46)
	at io.quarkus.qute.Parser$1.resolve(Parser.java:1231)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderData(TemplateImpl.java:176)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsyncNoTimeout(TemplateImpl.java:167)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsync(TemplateImpl.java:140)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.renderTemplate(DevConsole.java:173)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.handle(DevConsole.java:137)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsole.handle(DevConsole.java:39)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.deployment.devmode.console.FlashScopeHandler.handle(FlashScopeHandler.java:12)
	at io.quarkus.vertx.http.deployment.devmode.console.FlashScopeHandler.handle(FlashScopeHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:250)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:68)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor$2$1.handle(DevConsoleProcessor.java:194)
	at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor$2$1.handle(DevConsoleProcessor.java:191)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.EventLoopContext.lambda$emit$1(EventLoopContext.java:62)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Resulted in: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	... 61 more
Resulted in: java.lang.IllegalStateException: Reflection invocation error
	at io.quarkus.qute.GetterAccessor.getValue(GetterAccessor.java:29)
	... 59 more
Resulted in: io.quarkus.qute.TemplateException
	at io.quarkus.qute.CompletedStage.get(CompletedStage.java:48)
	at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
	at io.quarkus.qute.MultiResultNode.process(MultiResultNode.java:20)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.lambda$renderData$5(TemplateImpl.java:182)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:144)
	... 32 more
Resulted in: java.util.concurrent.CompletionException: io.quarkus.qute.TemplateException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:144)
	... 31 more

### How to Reproduce?

Steps to reproduce the behaviour

1. Go to code.quarkus.io
2. add extensions: quarkus-resteasy-reactive, quarkus-hibernate-orm-panache, quarkus-jdbc-postgresql, quarkus-smallrye-openapi, quarkus-flyway
3. download zip
4. extract and open in IDE
5. quarkus dev --clean
6. open "Dev UI" -> "Config Editor"

### Output of `uname -a` or `ver`

Darwin Toms-MBP-2022.fritz.box 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "19" 2022-09-20 OpenJDK Runtime Environment Temurin-19+36 (build 19+36) OpenJDK 64-Bit Server VM Temurin-19+36 (build 19+36, mixed mode)

### Quarkus version or git rev

2.13.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /Users/xxx/.m2/wrapper/dists/apache-maven-3.8.6-bin/67568434/apache-maven-3.8.6 Java version: 19, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home Default locale: en_AT, platform encoding: UTF-8 OS name: "mac os x", version: "12.6", arch: "aarch64", family: "mac"

**Comment by gsmet** [comment]
@radcortez @phillip-kruger could one of you have a look to this one?

**Comment by phillip-kruger** [comment]
I'll have a look

**Comment by phillip-kruger** [comment]
I can not recreate this on Linux. Same as with #27490. @htl-leonding can you do some more debugging to find out what value gives you the index out of bounce ?
