### ISSUE TITLE
Native awt build fails on Windows also when running with native-build-container

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#28335]
### Describe the bug

Running the native build with `-Dquarkus.native.container-build=true` also fails on windows even though the native-build would be executed inside a linux docker container.

### Expected behavior

The build should work inside a linux docker container

### Actual behavior

Following error is thrown:

```
* What went wrong:
Execution failed for task ':devtools:machine-learning:labeling-server:quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
  	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
  	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:281)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
  	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.lang.UnsupportedOperationException: Windows AWT integration is not ready in native-image and would result in java.lang.UnsatisfiedLinkError: no awt in java.library.path.
  	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep$NativeImageInvokerInfo$Builder.build(NativeImageBuildStep.java:883)
  	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:249)
  	... 11 more
```

### How to Reproduce?

* add `io.quarkus:quarkus-awt`
* run
```sh
gradlew quarkusBuild -Dquarkus.native.container-build=true -Dquarkus.package.type=native -Dquarkus.container-image.build=true
```

### Output of `java -version`

17

### GraalVM version (if different from Java)

17

### Quarkus version or git rev

2.13.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradlew 7.5.1

**Comment by geoand** [comment]
@Karm any idea what's going on here?

**Comment by gsmet** [comment]
The OS test is based on the local OS and doesn't take into account the fact that the actual OS could be a container. It needs to be adjusted.

**Comment by Karm** [comment]
I will change ```io.quarkus.dev.console.QuarkusConsole.IS_WINDOWS``` usage to something else to as it takes into account ```nativeConfig.isContainerBuild()``` and test on Windows Podman and Windows Docker Desktop.
