### ISSUE TITLE
Native, Podman, Windows:  crun: open executable: Permission denied: OCI permission denied

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#28414]
### Describe the bug

Using Dockerfile such as:

```
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4
RUN microdnf install freetype fontconfig \
    && microdnf clean all
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

Causes `crun: open executable: Permission denied: OCI permission denied` when you try to run the image.
The reason is that the resulting Linux binary is not made executable.

A simple workaround in the Dockerfile fixes that:
```
RUN chmod ugo+x /work/application
```

I wonder whether this shouldn't be done by Quarkus itself, setting AccessMode EXECUTE on that file.... I'm gonna try on Windows.

### Expected behavior

Linux binary made by Linux builder image is marked as executable file on Windows...?

### Actual behavior

One has to explicitly make the binary executable with chmod +x.

### Output of `uname -a` or `ver`

Windows

### Output of `java -version`

Temurin-17.0.5+5-202209152336

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by pinei** [comment]
Same problem when building the image using Github Actions

```
docker build . --file ./src/main/docker/Dockerfile.native --tag $REGISTRY/$REPOSITORY:$IMAGE_TAG
```

I got the error when starting the image as an app ... after pulling the image, did a run to see the content

```
docker run -it $REGISTRY/$REPOSITORY:$IMAGE_TAG bash

bash-4.4$ pwd
/work

bash-4.4$ ls -la
total 45564
drwxrwxr-x 1 1001 root     4096 Aug 18 19:21 .
drwxr-xr-x 1 root root     4096 Aug 18 20:06 ..
-rw-r--r-- 1 1001 root 46645840 Aug 18 19:20 application
```


At my local ubuntu 23.04 (dev environment) I don´t have the problem

```
docker build . --file ./src/main/docker/Dockerfile.native --tag $IMAGE_NAME:$IMAGE_TAG
docker run -it $IMAGE_NAME:$IMAGE_TAG bash
bash-4.4$ pwd
/work
bash-4.4$ ls -la
total 45512
drwxrwxr-x 1 1001 root     4096 Aug 18 20:11 .
drwxr-xr-x 1 root root     4096 Aug 18 20:12 ..
-rwxr-xr-x 1 1001 root 46592520 Aug 18 19:46 application
```

**Comment by mklueh** [comment]
Same here with Podman

**Comment by Karm** [comment]
Hello @mklueh, this is quite an old issue and I have been using native-image and linux containers on Windows successfully for some time now.  Can you share your Quarkus version, please?   I'll take a look...

**Comment by mklueh** [comment]
@Karm I'm using the latest Quarkus 3.15


The provided Dockerfile.native
```
####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./gradlew build -Dquarkus.native.enabled=true
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/backend .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/backend
#
###
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root build/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

```
quarkus.container-image.additional-tags=latest
quarkus.container-image.name=${quarkus.application.name:unset}
quarkus.container-image.tag=${quarkus.application.version:latest}

quarkus.native.enabled=true
#or otherwise error
quarkus.package.jar.enabled=false 
quarkus.native.native-image-xmx=6g
quarkus.container-image.build=true

# Otherwise Error: Invalid Path entry when using quarkus.native.container-runtime=docker on podman
#quarkus.native.remote-container-build=true 
quarkus.native.container-build=true

#quarkus.native.compression.level=10
#quarkus.native.container-runtime=docker 
quarkus.native.container-runtime=podman
```

This is what I'm seeing in Podman
![Image](https://github.com/user-attachments/assets/d3e3f704-f165-4b11-a470-6d19b1a229be)



By the way, if I set remote-container-build to true and use the docker runtime, I get this error instead


```
[5/8] Inlining methods...     [****]                                                                    (10,5s @ 1,54GB)
[6/8] Compiling methods...    [************]                                                           (159,4s @ 1,24GB)
[7/8] Layouting methods...    [****]                                                                    (19,2s @ 1,62GB)

[8/8] Creating image...       [*****]                                                                    (0,0s @ 1,12GB)
Fatal error: jdk.vm.ci.common.JVMCIError: java.nio.file.AccessDeniedException: /project/svm_err_b_20241031T165728.577_pid49.md
	at jdk.internal.vm.ci/jdk.vm.ci.common.JVMCIError.shouldNotReachHere(JVMCIError.java:52)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.reportImpl(ReportUtils.java:174)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:155)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.printEpilog(ProgressReporter.java:652)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.reportEpilog(NativeImageGeneratorRunner.java:605)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:597)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
Caused by: java.nio.file.AccessDeniedException: /project/svm_err_b_20241031T165728.577_pid49.md
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
	at java.base/java.nio.file.Files.createFile(Files.java:657)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.reportImpl(ReportUtils.java:164)
	... 7 more
Failed to copy native image from container volume back to the host. Output: Error: No such container:path: 9f0876c626179949de48ccdf0088ee17c9105541f38ed08478f6d2c79f013d24:/project/backend-0.0.1-beta.0-runner

> Task :apps:myapp:backend:quarkusAppPartsBuild FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
18 actionable tasks: 3 executed, 3 from cache, 12 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:myapp:backend:quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
        	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:489)
        	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:278)
        	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        	at java.base/java.lang.Thread.run(Thread.java:1583)
        	at org.jboss.threads.JBossThread.run(JBossThread.java:483)


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6m 46s
17:57:32: Execution finished 'build'.
```

**Comment by gsmet** [comment]
@mklueh and you are on Windows too?

**Comment by mklueh** [comment]
> @mklueh and you are on Windows too?

Yes I am

**Comment by Karm** [comment]
This seems to be something very different though. The original issue was a mere fact that the Linux executable produced on Windows via Maven driven build was not marked as executable. So when it was  copied to the runtime container, it could not have been started.

The log above suggests that the build running in the builder image container cannot write an error report here: 
```
Fatal error: jdk.vm.ci.common.JVMCIError: java.nio.file.AccessDeniedException: /project/svm_err_b_20241031T165728.577_pid49.md
```
@mklueh I haven't been testing gradle native builds on Windows, and it seems broken or I am just doing it the wrong way:  https://github.com/quarkusio/quarkus/issues/45073

So when I stick to Maven, it works:

```
powershell -Command "Invoke-WebRequest -Uri 'https://code.quarkus.io/d?e=rest&b=MAVEN&cn=code.quarkus.io' -OutFile 'code-with-quarkus.zip'"

powershell -c "Expand-Archive -Path code-with-quarkus.zip -DestinationPath . -Force"

cd code-with-quarkus

mvnw package -Pnative -Dquarkus.native.container-build=true

C:\tmp\code-with-quarkus
λ podman build -f src\main\docker\Dockerfile.native . -t my-app
STEP 1/8: FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10
STEP 2/8: WORKDIR /work/
--> Using cache 5805a26453fdd13a2198139d1867bb14103dfd85d9f32464251ae7f1dec782d8
--> 5805a26453f
STEP 3/8: RUN chown 1001 /work     && chmod "g+rwX" /work     && chown 1001:root /work
--> Using cache 64bcf2422fffe5227bf85bf702db59a4a455f7f8b6dc2a23d1e148cbe7f57f42
--> 64bcf2422ff
STEP 4/8: COPY --chown=1001:root target/*-runner /work/application
--> Using cache b1f72db3c6bb4d74d4373d1a3cfe2cf489abf4245aad5358f99f0ce15c5d442d
--> b1f72db3c6b
STEP 5/8: RUN chmod ugo+x /work/application
--> c56c3a4f4e6
STEP 6/8: EXPOSE 8080
--> 4945541570b
STEP 7/8: USER 1001
--> b52534b2e90
STEP 8/8: ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
COMMIT my-app
--> 03bc839fd7e
Successfully tagged localhost/my-app:latest
03bc839fd7ece8b94ec56a37e58492d99fb4c7d4c960f9e44b669d3d94450b0b

C:\tmp\code-with-quarkus
λ podman run localhost/my-app:latest
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-12-11 15:46:36,528 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT native (powered by Quarkus 3.17.4) started in 0.075s. Listening on: http://0.0.0.0:8080
2024-12-11 15:46:36,529 INFO  [io.quarkus] (main) Profile prod activated.
2024-12-11 15:46:36,529 INFO  [io.quarkus] (main) Installed features: [cdi, rest, smallrye-context-propagation, vertx]
```

...except that you still have to adjust the Dockerfile as this 2022 issue suggests:

```
RUN chmod ugo+x /work/application
```

I am using Podman Desktop on Windows 10 Enterprise, pretty much vanilla, just Visual Studio installed (not needed for container builds though).

**Comment by geoand** [comment]
Is this still an issue with the latest versions of Quarkus?

**Comment by geoand** [comment]
Closing for lack of feedback
