### ISSUE TITLE
Reactive Messaging (RabbitMQ) - Problems restarting quarkus:dev

### ISSUE THREAD

**Issue by samodadela** [quarkusio/quarkus#28428]
### Describe the bug

While working with SMMR (RabbitMQ) I noticed various problems when restarting quarkus:dev with 's' (Force restart). 
The restart results is various stack traces, this is just one of them. It causes problems when developing since you need to start quarkus:dev from scratch.

### Expected behavior

Restarting quarkus should not cause problems.

### Actual behavior

Restarting quarkus results in an error which goes away if `mvn quarkus:dev` is started again.

### How to Reproduce?

Use reproducer (just a some code using SMMR, I suspect emitter is the problem).

[conc.zip](https://github.com/quarkusio/quarkus/files/9733329/conc.zip)

1. Run mvn quarkus:dev
2. Execute request `GET http://localhost:8080/x/generate`
3. Wait for request to complete
4. Type 's' in the console 
5. Execute same request again: `GET http://localhost:8080/x/generate`
6. You get the following exception:
```
2022-10-06 15:05:04,514 ERROR [io.sma.rea.mes.provider] (vert.x-eventloop-thread-2) SRMSG00201: Error caught while processing a message: java.lang.IllegalArgumentException: @Blocking referred to invalid worker name.
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry.getWorker(QuarkusWorkerPoolRegistry.java:104)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry_Subclass.getWorker$$superforward1(Unknown Source)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry_Subclass$$function$$2.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry_Subclass.getWorker(Unknown Source)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry.executeWork(QuarkusWorkerPoolRegistry.java:60)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry_Subclass.executeWork$$superforward1(Unknown Source)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry_Subclass.executeWork(Unknown Source)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry_ClientProxy.executeWork(Unknown Source)
        at io.smallrye.reactive.messaging.providers.AbstractMediator.invokeBlocking(AbstractMediator.java:113)
        at io.smallrye.reactive.messaging.providers.SubscriberMediator.lambda$processMethodReturningVoid$0(SubscriberMediator.java:158)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.groups.MultiOnItem.lambda$transformToUni$6(MultiOnItem.java:268)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:178)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.tryEmit(MultiFlatMapOp.java:230)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onItem(MultiFlatMapOp.java:607)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onItem(UniToMultiPublisher.java:93)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at io.smallrye.reactive.messaging.rabbitmq.ConnectionHolder.lambda$runOnContext$5(ConnectionHolder.java:71)
        at io.vertx.mutiny.core.Context.lambda$runOnContext$1(Context.java:134)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

As said this is just one of the possible exception. 
Other issues happen when code is modified and a request triggers recompile (live reload). That fails with an error that the emitter can not be reconnected.

### Output of `uname -a` or `ver`

Linux a 5.15.65-1-MANJARO #1 SMP PREEMPT Mon Sep 5 10:15:47 UTC 2022 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.14.1" 2022-02-08 OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1) OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)

### Quarkus version or git rev

2.13.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/apache-maven-3.8.6
Java version: 11.0.14.1, vendor: Eclipse Adoptium, runtime: /opt/jdk-11.0.14.1+1
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.65-1-manjaro", arch: "amd64", family: "unix"

**Comment by samodadela** [comment]
This seems to be connected with the Blocking annotation...

**Comment by cescoffier** [comment]
I was not able to reproduce it with `main`. Please re-open with an updated reproducer if you still have the issue.
