### ISSUE TITLE
Mongodb tracing not working properly with native build

### ISSUE THREAD

**Issue by bosofelipe** [quarkusio/quarkus#28427]
### Describe the bug

We are working in a quarkus project with mongo db and native build, but when enabled mongo db tracking the native compile not working, the following log error occurred.

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.opentracing.contrib.mongo.common.TracingCommandListener$Builder. This error is reported at image build time because class io.quarkus.mongodb.tracing.MongoTracingCommandListener is registered for linking at image build time by command line
Trace: 
        at parsing io.quarkus.mongodb.tracing.MongoTracingCommandListener.<init>(MongoTracingCommandListener.java:24)
Call path from entry point to io.quarkus.mongodb.tracing.MongoTracingCommandListener.<init>(): 
        at io.quarkus.mongodb.tracing.MongoTracingCommandListener.<init>(MongoTracingCommandListener.java:23)
        at io.quarkus.mongodb.tracing.MongoTracingCommandListener_Bean.create(Unknown Source)
        at io.quarkus.mongodb.tracing.MongoTracingCommandListener_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:299)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)
```

### Expected behavior

Compile native build without errors

### Actual behavior

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.opentracing.contrib.mongo.common.TracingCommandListener$Builder. This error is reported at image build time because class io.quarkus.mongodb.tracing.MongoTracingCommandListener is registered for linking at image build time by command line
Trace: 
        at parsing io.quarkus.mongodb.tracing.MongoTracingCommandListener.<init>(MongoTracingCommandListener.java:24)
Call path from entry point to io.quarkus.mongodb.tracing.MongoTracingCommandListener.<init>(): 
        at io.quarkus.mongodb.tracing.MongoTracingCommandListener.<init>(MongoTracingCommandListener.java:23)
        at io.quarkus.mongodb.tracing.MongoTracingCommandListener_Bean.create(Unknown Source)
        at io.quarkus.mongodb.tracing.MongoTracingCommandListener_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:299)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)
```

### How to Reproduce?

Reproducer:

1. Enable mongo db tracing in application.properties
2. Build quarkus with native way mvn install -Pnative

### Output of `uname -a` or `ver`

x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

17

### GraalVM version (if different from Java)

GraalVM 22.1.0 Java 17 CE

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn clean install -Pnative

### Additional information

application.properties

`# Connection DB
quarkus.mongodb.tracing.enabled=true`

mongo db dependencies
`

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mongodb-panache</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mongodb-client</artifactId>
    </dependency>
`

**Comment by geoand** [comment]
Any chance you can attach a sample project?

**Comment by radcortez** [comment]
Not related, but we need to move the Mongo Tracing integration to OpenTelemetry.

**Comment by geoand** [comment]
You are almost certainly missing:

```xml
    <dependency>
      <groupId>io.opentracing.contrib</groupId>
      <artifactId>opentracing-mongo-common</artifactId>
    </dependency>
```

that is mentioned [here](https://quarkus.io/guides/mongodb#tracing).
The situation is not ideal as users should not be forced to add that dependency on their own, but given that OpenTracing is deprecated, we won't be putting any effort into improving this situation.
