### ISSUE TITLE
Maven Multi-Module and Dev-Mode: Dependent class is not properly loaded

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#28447]
### Describe the bug

__Disclaimer__: I'm not sure if this is a bug or a limitation of Quarkus Live Reload Mode, so I'm opening this bug report.

If a change is made in a submodule of a Maven multi-module project that does not directly affect the main module, an exception is thrown. This is because only the changed class is recompiled and reloaded and not the classes that use that class.

Explanation and reproducer see below.

### How to Reproduce?

[reproducer.zip](https://github.com/quarkusio/quarkus/files/9732988/reproducer.zip)

1. `./mvnw -f core/pom.xml quarkus:dev`
2. http://localhost:8080/persons
3. Change the property `age` in class `Person` from type `int` to `long`
4. http://localhost:8080/persons

```java
java.lang.NoSuchMethodError: 'void org.acme.model.Person.<init>(java.lang.String, int)'
	at org.acme.PersonResource.getPersons(PersonResource.java:17)
	at org.acme.PersonResource_Subclass.getPersons$$superforward1(Unknown Source)
	at org.acme.PersonResource_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.acme.PersonResource_Subclass.getPersons(Unknown Source)
	at org.acme.PersonResource$quarkusrestinvoker$getPersons_b1ceee8c46147a6db196b42da6e33b1773010f00.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:115)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:142)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
````

The problem here is that the `Person` class is compiled and loaded, but the `PersonResource` class is not.

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.13.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by geoand** [comment]
@aloubyansky can certainly answer this :)

**Comment by aloubyansky** [comment]
Yes, the `PersonResource` has to be touched to be recompiled currently. FYI @stuartwdouglas
