### ISSUE TITLE
Build fails with Kotlin coroutine/suspend methods

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#28440]
### Describe the bug

With latest release the build fails with this error message:
```
Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Failed to process method 'io.outfoxx.cloud.api.admin.server.AdminAPI#createAccount'
```

and the final cause error message is:
```
Resource method java.lang.Object createAccount(java.lang.String tenantId, io.outfoxx.cloud.api.CreateAccountParams body, javax.ws.rs.core.UriInfo uriInfo, kotlin.coroutines.Continuation<? super javax.ws.rs.core.Response> $completion) can only have a single body parameter: $completion
```

Notice the complaint about the `$completion` parameter in the method.
 

The suspend method is defined in an interface with the following signature:
```kotlin
@Path(value = "/admin/api/v1.0")
@Produces(value = ["application/json","application/cbor"])
@Consumes(value = ["application/json"])
interface AdminAPI
  
  //...

  @POST
  @Path(value = "/tenants/{tenantId}/accounts")
  public suspend fun createAccount(
    @PathParam(value = "tenantId") tenantId: String,
    @Valid body: CreateAccountParams,
    @Context uriInfo: UriInfo
  ): Response

  //...

}
```

An implementation class then derives from the interface and implements the methods. It builds fine in `2.13.0.Final`

### Expected behavior

Kotlin suspend methods work as they did in previous releases.

### Actual behavior

Kotlin suspend methods in interfaces fails the 

### Output of `uname -a` or `ver`

macOS 12.6

### Output of `java -version`

OpenJDK 17.0.1

### Quarkus version or git rev

2.13.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5

**Comment by kdubb** [comment]
Here is the entire stack trace, it references `EndpointIndexer.createEndpoints`.

<details>

```
java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Failed to process method 'io.outfoxx.cloud.api.admin.server.AdminAPI#createAccount'
        at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:315)
        at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:593)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.lang.RuntimeException: Failed to process method 'io.outfoxx.cloud.api.admin.server.AdminAPI#createAccount'
        at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:703)
        at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:405)
        at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:452)
        at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:286)
        ... 12 more
  Caused by: java.lang.RuntimeException: Resource method java.lang.Object createAccount(java.lang.String tenantId, io.outfoxx.cloud.api.CreateAccountParams body, javax.ws.rs.core.UriInfo uriInfo, kotlin.coroutines.Continuation<? super javax.ws.rs.core.Response> $completion) can only have a single body parameter: $completion
        at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:551)
        ... 15 more
```

</details>

**Comment by geoand** [comment]
Very interesting... I wonder if the bump to the latest Kotlin caused a regression...

Any chance you can attach a minimal sample that exhibits this problem?

**Comment by kdubb** [comment]
Yep. Just needed to record it while I finished up other things.

**Comment by geoand** [comment]
Great, thanks!

**Comment by u6f6o** [comment]
I had kind of a similar issue in my project. @geoand asked me to share my reproducer here. 

In order to get the exception, you'd have to execute `./gradlew clean quarkusDev`. Funnily, if you execute only `./gradlew quarkusDev` afterwards, it successfully starts up.

Here is the reproducer: https://github.com/u6f6o/suspenderino

**Comment by geoand** [comment]
Thanks a lot for this!

I'll have a look next week.

**Comment by kdubb** [comment]
Ahhh. I'm trying to make a reproducer with no luck. I'll try the clean thing.

**Comment by kdubb** [comment]
To note, that is exactly what I was doing when I encountered the issue.

**Comment by kdubb** [comment]
Yep it was the clean that was needed. For posterity here is my reproducer that generates the same error.

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/9734918/code-with-quarkus.zip)

**Comment by kdubb** [comment]
Adding the `quarkus-resteasy-reactive-kotlin` explicitly appears to solve the issue.

**Comment by geoand** [comment]
Yes, it does. This seems to indicate a problem with the conditional adding of extensions in `2.13.1.Final` (I also think the problem is limited to Gradle)

**Comment by aloubyansky** [comment]
It appears https://github.com/quarkusio/quarkus/commit/827f778c9ab71478b19ce230ac5a5265bfdba592 has introduced a regression and that we don't have a sufficient test coverage for this use-case.
@AdlerFleurant or @glefloch would one of you like to dig into this? Thanks!

**Comment by kdubb** [comment]
@glefloch Anything I can do to speed this up? Holding up our update.

**Comment by glefloch** [comment]
@kdubb not really, I found the commit that introduced the issue but not the line of code yet

**Comment by gsmet** [comment]
@glefloch any news on this one?

**Comment by gsmet** [comment]
I will review https://github.com/quarkusio/quarkus/commit/827f778c9ab71478b19ce230ac5a5265bfdba592#diff-f039c32dd9e6b278cc24a035089a6c1c686f3e56365b794ac7559f2f49ae116aR73 and revert everything that is not directly related to the bugfix.

This PR got extremely out of hands with a ton of unrelated changes that IMO don't make the code easier to read.

**Comment by glefloch** [comment]
Yes, reverting this commit fix the issue but I wasn't able to identify which part of the code introduced the regression.

**Comment by kdubb** [comment]
A reproducer that passes with `2.12.1.Final` and fails with `EndpointIndexer` with `2.13.1.Final`
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/9821260/code-with-quarkus.zip)
