### ISSUE TITLE
LambdaCapturingClasses not supported in GraalVM 21.3

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#28530]
### Describe the bug

https://github.com/quarkusio/quarkus/commit/b772ad2dec4c8734f2bde3dd607fa7490b5e29cf introduced `LambdaCapturingTypeBuildItem` which depends on `org.graalvm.nativeimage.impl.RuntimeSerializationSupport#registerLambdaCapturingClass` which was introduced in GraalVM 22.1.0 (https://github.com/oracle/graal/commit/b455f23b624a1af149c7d5769443a4775bedd087).

### Expected behavior

Integration test `main` should pass when using GraalVM 21.3.

### Actual behavior

Integration test `main` fails when using GraalVM 21.3 with:

```
[quarkus-integration-test-main-999-SNAPSHOT-runner:57]    classlist:   7,120.24 ms,  1.69 GB
[quarkus-integration-test-main-999-SNAPSHOT-runner:57]        (cap):     780.38 ms,  1.69 GB
java.lang.NoSuchMethodError: 'void org.graalvm.nativeimage.impl.RuntimeSerializationSupport.registerLambdaCapturingClass(org.graalvm.nativeimage.impl.ConfigurationCondition, java.lang.String)'
	at io.quarkus.runner.Feature.duringSetup(Unknown Source)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$17(NativeImageGenerator.java:872)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:872)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:527)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:410)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:594)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:124)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:624)
[quarkus-integration-test-main-999-SNAPSHOT-runner:57]        setup:   3,385.40 ms,  1.69 GB
[quarkus-integration-test-main-999-SNAPSHOT-runner:57]     (clinit):   2,016.50 ms,  6.25 GB
[quarkus-integration-test-main-999-SNAPSHOT-runner:57]   (typeflow):   5,881.15 ms,  6.25 GB
[quarkus-integration-test-main-999-SNAPSHOT-runner:57]    (objects): 110,256.71 ms,  6.25 GB
[quarkus-integration-test-main-999-SNAPSHOT-runner:57]   (features):   7,968.34 ms,  6.25 GB
[quarkus-integration-test-main-999-SNAPSHOT-runner:57]     analysis: 131,110.11 ms,  6.25 GB
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService.<init>(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.<init>(Unknown Source)
Call path from entry point to io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.<init>(String): 
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.<init>(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.proxy(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.get(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.Instances$3.get(Instances.java:131)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
	at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:287)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService.<init>(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.<init>(Unknown Source)
Call path from entry point to io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.<init>(String): 
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.<init>(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.proxy(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.get(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.Instances$3.get(Instances.java:131)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
	at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:287)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:87)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:759)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:410)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:594)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:124)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:624)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService.<init>(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.<init>(Unknown Source)
Call path from entry point to io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.<init>(String): 
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_ClientProxy.<init>(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.proxy(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.get(Unknown Source)
	at io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.Instances$3.get(Instances.java:131)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
	at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:287)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:756)
	... 6 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.smallrye.openapi.runtime.OpenApiDocumentService.<init>(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:307)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:298)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:252)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1805)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1795)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5418)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3477)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3437)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3282)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1145)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:81)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:616)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:163)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:322)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:293)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:282)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:363)
	at com.oracle.graal.pointsto.flow.TypeFlow$1.run(TypeFlow.java:449)
	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[quarkus-integration-test-main-999-SNAPSHOT-runner:57]      [total]: 142,373.74 ms,  6.25 GB
```

### How to Reproduce?

```
./mvnw clean -Dnative -pl integration-tests/main -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11 -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests package -Dquarkus.native.container-build=true
```

### Output of `java -version`

11.0.16+8

### GraalVM version (if different from Java)

21.3.3.0-Final

### Quarkus version or git rev

https://github.com/quarkusio/quarkus/pull/28529

**Comment by geoand** [comment]
What do you propose we do here @zakkak?

Ignore the configured values when using GraalVM 21.3 and just log a warning?

**Comment by zakkak** [comment]
> Ignore the configured values when using GraalVM 21.3 and just log a warning?

That was my first thought as well. But I think we should better fail with an error stating that the user needs to either use a newer version of GraalVM or remove the LambdaCapturingTypeBuildItem. After all, GraalVM CE 21.3 is reaching its end of life as soon as 22.3 comes out in a few days.

**Comment by geoand** [comment]
> But I think we should better fail with an error stating that the user needs to either use a newer version of GraalVM or remove the LambdaCapturingTypeBuildItem

Users don't really know anything about build items, so we would have to warn them about the improper annotation usage. We should also enhance the javadoc to explain that the method of the annotation is only available since GraalVM _whatever_

**Comment by geoand** [comment]
@zakkak have we addressed this one?

**Comment by zakkak** [comment]
This is addressed in https://github.com/quarkusio/quarkus/pull/28596 if we end up needing it. The plan is to drop support for 21.3 in Quarkus 2.13 and mark this as a won't fix. But we are still waiting for all the tests to show that this is OK to do.

**Comment by zakkak** [comment]
Closing as not planned. GraalVM 21.3 is no longer supported.
