### ISSUE TITLE
java.lang.IncompatibleClassChangeError: AmazonServicesClientsProcessor does not implement the requested interface java.util.function.Predicate

### ISSUE THREAD

**Issue by Chexpir** [quarkusio/quarkus#28587]
### Describe the bug

Running it on Jenkins CI, which uses a ubuntu builder image, it says:
```
[2022-10-14T07:08:52.296Z] Execution failed for task ':quarkusBuild'.
[2022-10-14T07:08:52.296Z] > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[2022-10-14T07:08:52.296Z]   	[error]: Build step io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor#setup threw an exception: java.lang.IncompatibleClassChangeError: Class io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor$$Lambda$2622/0x00000008019cb8e0 does not implement the requested interface java.util.function.Predicate
[2022-10-14T07:08:52.296Z]   	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[2022-10-14T07:08:52.296Z]   	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
[2022-10-14T07:08:52.296Z]   	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[2022-10-14T07:08:52.296Z]   	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[2022-10-14T07:08:52.296Z]   	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[2022-10-14T07:08:52.296Z]   	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[2022-10-14T07:08:52.296Z]   	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[2022-10-14T07:08:52.296Z]   	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[2022-10-14T07:08:52.296Z]   	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
[2022-10-14T07:08:52.296Z]   	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.setup(AmazonServicesClientsProcessor.java:111)
[2022-10-14T07:08:52.296Z]   	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-10-14T07:08:52.296Z]   	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-10-14T07:08:52.296Z]   	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-10-14T07:08:52.296Z]   	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-10-14T07:08:52.296Z]   	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[2022-10-14T07:08:52.296Z]   	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[2022-10-14T07:08:52.296Z]   	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[2022-10-14T07:08:52.296Z]   	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[2022-10-14T07:08:52.296Z]   	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[2022-10-14T07:08:52.296Z]   	at java.base/java.lang.Thread.run(Thread.java:833)
[2022-10-14T07:08:52.296Z]   	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

Locally, it throws a different error:

```2022-10-14 09:06:53,114 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor#setup threw an exception: java.lang.NoClassDefFoundError: com/google/common/base/Predicate
	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.setup(AmazonServicesClientsProcessor.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Predicate
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:491)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:441)
	... 12 more
```

### Expected behavior

Application to build correctly without adding guava.

### Actual behavior

It does not build.

### How to Reproduce?

During upgrade from Quarkus 2.9.2 to Quarkus 2.13.2 with the following dependencies:

```
dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'io.quarkus:quarkus-resteasy-jackson'
    implementation 'io.quarkus:quarkus-rest-client'
    implementation 'io.quarkus:quarkus-jdbc-postgresql'
    implementation 'io.quarkus:quarkus-hibernate-orm-panache'
    implementation 'io.quarkus:quarkus-hibernate-orm-deployment'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-amazon-sqs'
    implementation 'io.quarkus:quarkus-hibernate-validator'
    implementation 'io.quarkus:quarkus-amazon-sns'
    implementation 'io.quarkus:quarkus-smallrye-fault-tolerance'
    implementation 'io.quarkus:quarkus-liquibase'
    implementation 'io.quarkus:quarkus-rest-client-mutiny'
    implementation 'io.quarkus:quarkus-qute'
    implementation 'io.quarkus:quarkus-quartz'

    implementation 'org.apache.camel.quarkus:camel-quarkus-aws2-sqs:2.13.0'
    implementation 'org.apache.camel.quarkus:camel-quarkus-bean:2.13.0'
    implementation 'org.apache.camel.quarkus:camel-quarkus-jackson:2.13.0'

    implementation 'io.quarkiverse.loggingjson:quarkus-logging-json:1.1.1'

    implementation 'javax.json.bind:javax.json.bind-api:1.0'
    implementation 'com.squareup.okhttp:okhttp:2.7.5'
    implementation 'com.squareup.okhttp:logging-interceptor:2.7.5'
    implementation 'org.threeten:threetenbp:1.6.2'
    implementation 'io.gsonfire:gson-fire:1.8.5'
    implementation 'io.swagger:swagger-annotations:1.6.7'
    implementation 'com.vladmihalcea:hibernate-types-52:2.19.2'
    implementation 'com.nurkiewicz.asyncretry:asyncretry:0.0.7'
    implementation 'software.amazon.awssdk:url-connection-client:2.17.285'
    implementation 'software.amazon.awssdk:netty-nio-client:2.17.285'
    implementation 'org.apache.commons:commons-lang3:3.12.0'

    compileOnly 'org.projectlombok:lombok:1.18.24'
    annotationProcessor 'org.projectlombok:lombok:1.18.24'

    implementation 'org.mapstruct:mapstruct:1.5.2.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.2.Final'

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'io.quarkus:quarkus-junit5-mockito'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.0'
    testImplementation 'org.awaitility:awaitility:4.2.0'
    testImplementation 'com.github.tomakehurst:wiremock-jre8:2.34.0'
    testImplementation('com.github.database-rider:rider-cdi:1.34.0') {
        exclude group: 'stax', module: 'stax-api'
    }
    testImplementation 'org.mockito:mockito-junit-jupiter:4.8.0'

}
```

### Output of `java -version`

17

### GraalVM version (if different from Java)

Not used

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.5.1

### Additional information

If we add
`implementation 'com.google.guava:guava:31.1-jre'` it works in both cases (Local and Jenkins).

**Comment by gsmet** [comment]
So first, this should be reported here: https://github.com/quarkiverse/quarkus-amazon-services

Secondly, it rings a bell but I think it's an issue that is quite old. Which version of Quarkus Amazon Services is resolved? It would be better if in addition to the Quarkus BOM, you also enforced the Amazon Services Platform BOM (in the exact same version as the Quarkus Platform BOM): `io.quarkus.platform:quarkus-amazon-services-bom`.

In any case, I will close this issue but if you can reproduce it with the latest versions, please open an issue with a simple reproducer here: https://github.com/quarkiverse/quarkus-amazon-services .
