### ISSUE TITLE
Reactive mongo client not working with native build

### ISSUE THREAD

**Issue by sahak1an** [quarkusio/quarkus#28663]
### Describe the bug

```java
    @Produces
    public ReactiveMongoClient reactiveMongoClient(){
        MongoClient mongoClient = MongoClients.create("mongodb://localhost:27017");
        return new ReactiveMongoClientImpl(mongoClient);
    }
```

### Actual behavior

```posh
ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NullPointerException
        at java.lang.String.valueOf(String.java:4218)
        at com.mongodb.WriteConcern.toString(WriteConcern.java:335)
        at java.lang.String.valueOf(String.java:4218)
        at com.mongodb.MongoClientSettings.toString(MongoClientSettings.java:881)
        at java.lang.String.valueOf(String.java:4218)
        at java.lang.StringBuilder.append(StringBuilder.java:173)
        at com.oracle.svm.enterprise.core.stringformat.a.a(stripped:153)
        at com.oracle.svm.enterprise.core.stringformat.a.format(stripped:104)
        at com.mongodb.reactivestreams.client.internal.MongoClientImpl.<init>(MongoClientImpl.java:108)
        at com.mongodb.reactivestreams.client.internal.MongoClientImpl.<init>(MongoClientImpl.java:76)
        at com.mongodb.reactivestreams.client.MongoClients.createMongoClient(MongoClients.java:138)
        at com.mongodb.reactivestreams.client.MongoClients.createWithAsynchronousSocketChannel(MongoClients.java:174)
        at com.mongodb.reactivestreams.client.MongoClients.create(MongoClients.java:115)
        at com.mongodb.reactivestreams.client.MongoClients.create(MongoClients.java:97)
        at io.quarkus.mongodb.runtime.MongoClients.createReactiveMongoClient(MongoClients.java:128)
        at io.quarkus.mongodb.runtime.MongoClientRecorder.lambda$reactiveMongoClientSupplier$1(MongoClientRecorder.java:71)
        at io.quarkus.mongodb.runtime.MongoClientRecorder$MongoClientSupplier.get(MongoClientRecorder.java:60)
        at io.quarkus.mongodb.reactive.ReactiveMongoClient_afcbcf6dad636d255df730977b21f823ec3c9f2e_Synthetic_Bean.create(Unknown Source)
        at io.quarkus.mongodb.reactive.ReactiveMongoClient_afcbcf6dad636d255df730977b21f823ec3c9f2e_Synthetic_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
        at io.quarkus.mongodb.reactive.ReactiveMongoClient_afcbcf6dad636d255df730977b21f823ec3c9f2e_Synthetic_ClientProxy.arc$delegate(Unknown Source)
        at io.quarkus.mongodb.reactive.ReactiveMongoClient_afcbcf6dad636d255df730977b21f823ec3c9f2e_Synthetic_ClientProxy.getDatabase(Unknown Source)
        at io.quarkus.mongodb.panache.common.reactive.runtime.ReactiveMongoOperations.mongoDatabase(ReactiveMongoOperations.java:315)
        at io.quarkus.mongodb.panache.common.reactive.runtime.ReactiveMongoOperations.mongoCollection(ReactiveMongoOperations.java:218)
        at io.quarkus.mongodb.panache.common.reactive.runtime.ReactiveMongoOperations.findAll(ReactiveMongoOperations.java:551)
        at org.plx.extraction.Edge.findAll(Edge.java)
        at org.plx.extraction.DbCounter.onStart(DbCounter.java:14)
        at org.plx.extraction.DbCounter_Observer_onStart_df12bcb88765d91b0284c500dcd33d63d39f4dc6.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:122)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### How to Reproduce?

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mongodb-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
```
`quarkus build --native`

### Output of `uname -a` or `ver`

6.0.2-2-MANJARO

### Output of `java -version`

Java(TM) SE Runtime Environment GraalVM EE 22.2.0 (build 17.0.4+11-LTS-jvmci-22.2-b05)

### Quarkus version or git rev

2.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.6

**Comment by loicmathieu** [comment]
@sahak1an you should not be using directly `io.quarkus.mongodb.runtime.MongoClient` this is an internal API. You should configure MongoDB inside your application.properties and inject the client where you need it as it is described in the guide: https://quarkus.io/guides/mongodb

**Comment by geoand** [comment]
Closing as explained by @loicmathieu
