### ISSUE TITLE
Deserialization fails in native mode with kotlin.serialization

### ISSUE THREAD

**Issue by u6f6o** [quarkusio/quarkus#28693]
### Describe the bug

I wrote a lambda with the `quarkus-amazon-lambda` library. This lambda can be triggered by an aws api gateway call. It basically serves as webhook for mailgun. The lambda code so far is quite simple: 

```kotlin
@Named("MailgunWebhookProcessor")
class WebhookProcessor(val json: kotlinx.serialization.json.Json): RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent>
{

    override fun handleRequest(
        input: APIGatewayProxyRequestEvent,
        context: Context): APIGatewayProxyResponseEvent
    {
        try {
            val callback = json.decodeFromString<EmailDeliveryUpdate>(input.body)

            val signature = callback.signature
            val candidate = "$signature.timestamp$signature.token"

            val hexDigest = HMAC_UTILS.hmacHex(candidate)

            if (hexDigest != signature.signature) {
                Log.error("Signature not valid: $hexDigest vs ${signature.signature}")
            } else {
                Log.info("Body $callback")
            }
        } catch (e: Exception) {
            Log.error("Webhook error", e)
        }
        return APIGatewayProxyResponseEvent().withStatusCode(200)
    }
}
```
When this lambda is triggered by a callback from mailgun it fails with the following exception: 

```
kotlinx.serialization.SerializationException: Serializer for class 'EmailDeliveryUpdate' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
	at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(Platform.kt:29)
	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:60)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
	at mylambda.WebhookProcessor.handleRequest(WebhookProcessor.kt:46)
	at mylambda.WebhookProcessor.handleRequest(WebhookProcessor.kt:17)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:170)
	at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:137)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)

```
The data class I am using looks like the following: 
```kotlin
@RegisterForReflection
@Serializable
data class EmailDeliveryUpdate(
    val signature: Signature,
    @SerialName("event-data")
    val eventData: EventData
)
```
Here is the build.gradle file: 

```groovy
plugins {
    id 'io.quarkus'
    id 'org.jetbrains.kotlin.jvm' version "1.7.20"
    id 'org.jetbrains.kotlin.plugin.allopen' version "1.7.20"
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.7.20'
}

repositories {
    mavenCentral()
    mavenLocal()
}

apply from: "tasks/artifactory.gradle"
apply from: "tasks/test_coverage.gradle"

dependencies {
    implementation enforcedPlatform("io.quarkus:quarkus-bom:${quarkusVersion}")
    implementation enforcedPlatform("io.quarkus.platform:quarkus-amazon-services-bom:${quarkusVersion}")

    implementation 'io.quarkus:quarkus-amazon-lambda'
    implementation 'io.quarkus:quarkus-config-yaml'
    implementation 'io.quarkus:quarkus-kotlin'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-resteasy-reactive-kotlin-serialization-common'

    implementation 'io.quarkiverse.loggingjson:quarkus-logging-json:2.0.0'

    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json'

    implementation 'commons-codec:commons-codec'

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.kotest:kotest-runner-junit5-jvm:5.5.1'
    testImplementation 'io.kotest:kotest-assertions-json:5.5.1'
}

group 'mylambda'
version '1.0.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

allOpen {
    annotation("javax.ws.rs.Path")
    annotation("javax.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
}

compileKotlin {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11
    kotlinOptions.javaParameters = true
}

compileTestKotlin {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11
}

```

I already had issues like that with Jackson back in the days and we decided to give up on quarkus native for our regular k8s services. Half a year later, I wanted to give it another try; this time with kotlin.serialization as I thought it could fit better for a native approach because most of the heavy lifting is done during build time. 

### Expected behavior

Kotlin.serialization and/or jackson json serialization/deserialization should work reliably in native mode without having to compromise on core kotlin language features (e.g. enforcing nullable props and giving up on immutability in data classes)

### GraalVM version (if different from Java)

22.2

### Quarkus version or git rev

2.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle-7.5.1

**Comment by geoand** [comment]
Hi,

If you provide a sample application I can have a look at why the serializer is not being picked up

**Comment by u6f6o** [comment]
I'll try, it's a bit hard though in this case as the local sam deployment does not work for me (also tried in in other sample projects): 
```
sam local start-api --template build/sam.native.yaml
Error: Template does not have any APIs connected to Lambda functions
```

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/28734 takes care of your issue

**Comment by u6f6o** [comment]
Nice! Thank you for investigating!

**Comment by geoand** [comment]
All is possible when we a good reproducer, so thanks for that :)
