### ISSUE TITLE
[CI] - <participant> - Quarkus <branch>

### ISSUE THREAD

**Issue by syh194194** [quarkusio/quarkus#28707]
I customized an extension,this extension provides an annotation and can be added to the interface of the sdk to provide external services. when i start service,prompt the following error

2022-10-20 15:05:09,004 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkiverse.dapr.AppApplication.main(AppApplication.java:9)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 17 more
Caused by: java.lang.IllegalAccessError: class io.quarkus.deployment.steps.DaprClientProcessor$staticInit870765674 tried to access method 'void org.jboss.jandex.MethodInfo.<init>()' (io.quarkus.deployment.steps.DaprClientProcessor$staticInit870765674 is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @4c531172; org.jboss.jandex.MethodInfo is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @7123be6c)
	at io.quarkus.deployment.steps.DaprClientProcessor$staticInit870765674.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.DaprClientProcessor$staticInit870765674.deploy(Unknown Source)
	... 18 more

**Comment by geoand** [comment]
Hi,

Can you please fix the title and add more contextual information in the description about what you are talking about?
It's really hard to understand at the moment what this issue is referring to.

**Comment by syh194194** [comment]
Thank you very much, this problem has been solved.it caused by SyntheticBeanBuildItem, my supplier has some problem
