### ISSUE TITLE
Automatic build of Docker image fails when running with podman

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#28721]
### Describe the bug

I have an application with `quarkus-resteasy-jackson` and `quarkus-container-image-docker` dependecies and with property `quarkus.container-image.build` set to true. When I run `mvn clean package` while using docker as a contanier runtime, everything works as expected. When I run the same command, while using podman socket I get an error.

### Expected behavior

Result of build command should not depend on used container runtime.

### Actual behavior

```
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] Starting (local) container image build for jar using docker.
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] Executing the following command to build docker image: 'docker build -f /home/fedinskiy/code/quarkus/refresh/reproducer/src/main/docker/Dockerfile.jvm -t qe/hello-world-app:1.0.0 /home/fedinskiy/code/quarkus/refresh/reproducer'
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] Sending build context to Docker daemon  16.45MB
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] 
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] request returned Bad Request for API route and version http://%2Frun%2Fuser%2F1000%2Fpodman%2Fpodman.sock/v1.41/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=src%2Fmain%2Fdocker%2FDockerfile.jvm&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=qe%2Fhello-world-app%3A1.0.0&target=&ulimits=null&version=1, check if the server supports the requested API version
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.880 s
[INFO] Finished at: 2022-10-20T16:03:18+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.13.3.Final:build (default) on project reproducer: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromJar threw an exception: java.lang.RuntimeException: Execution of 'docker build -f /home/fedinskiy/code/quarkus/refresh/reproducer/src/main/docker/Dockerfile.jvm -t qe/hello-world-app:1.0.0 /home/fedinskiy/code/quarkus/refresh/reproducer' failed. See docker output for more details
[ERROR] 	at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerException(DockerProcessor.java:330)
[ERROR] 	at io.quarkus.container.image.docker.deployment.DockerProcessor.createContainerImage(DockerProcessor.java:199)
[ERROR] 	at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerBuildFromJar(DockerProcessor.java:106)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### How to Reproduce?

1. Clone the reproducer: `git@github.com:fedinskiy/reproducer.git -b  reproducer/build-podman`
2. Set up podman and podman socket:
 a. `sudo dnf install podman podman-docker`
 b .`systemctl --user enable podman.socket --now`
 c. `export DOCKER_HOST=unix:///run/user/${UID}/podman/podman.sock && export TESTCONTAINERS_RYUK_DISABLED=true`
3. run `mvn clean package`
If step 2 is ommited, everything works as expected.
For comparison, manual build works flawlessly:
3. `mvn clean package -Dquarkus.container-image.build=false`
4. `podman build -f src/main/docker/Dockerfile.jvm -t quarkus/getting-started-jvm .`

### Output of `uname -a` or `ver`

5.19.11-200.fc36.x86_64

### Output of `java -version`

11.0.16 temurin

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

podman version 4.2.1
Docker version 20.10.19, build d85ef84

**Comment by geoand** [comment]
@gastaldi any chance you can take a look at this one?

**Comment by gastaldi** [comment]
@geoand I using a mac and don't have Fedora in my machine 😞

Let me see if I can reproduce that in a VM

**Comment by geoand** [comment]
Oh, I thought you were on Fedora

**Comment by gastaldi** [comment]
I have to pass, I tried but had no luck without requiring payment 😞

**Comment by holly-cummins** [comment]
It makes me think we should be running some of the native tests on M1. That's a different OS, but it's also podman so will flush out some of these issues. 

Or, alternatively, we could have a matrix job which ran on the normal hardware but forced podman as the container runtime.

**Comment by wodadehencou** [comment]
I have the same error on Mac (Intel chip)

docker build fail, podman build pass

**request returned Bad Request for API route and version http://%2FUsers%2Fjiamu%2F.local%2Fshare%2Fcontainers%2Fpodman%2Fmachine%2Fpodman-machine-default%2Fpodman.sock/v1.41/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=jd-mpc-cn-north-1-inner.jcr.service.jdcloud.com%2Fmpcimage%2F9ntrain%3Abaseimage_v1.0.0&target=&ulimits=null&version=1, check if the server supports the requested API version**

docker version
```
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.19.2
 Git commit:        baeda1f82a
 Built:             Tue Oct 25 17:53:02 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: linux/amd64/fedora-36
 Podman Engine:
  Version:          4.3.0
  APIVersion:       4.3.0
  Arch:             amd64
  BuildTime:        2022-10-21T16:16:35+08:00
  Experimental:     false
  GitCommit:
  GoVersion:        go1.18.7
  KernelVersion:    6.0.5-200.fc36.x86_64
  MinAPIVersion:    4.0.0
  Os:               linux
 Conmon:
  Version:          conmon version 2.1.4, commit:
  Package:          conmon-2.1.4-3.fc36.x86_64
 OCI Runtime (crun):
  Version:          crun version 1.6
commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  Package:          crun-1.6-2.fc36.x86_64
 Engine:
  Version:          4.3.0
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.18.7
  Git commit:
  Built:            Fri Oct 21 16:16:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
```

podman info
```
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-3.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.72
    systemPercent: 0.2
    userPercent: 0.08
  cpus: 6
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 502
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.0.5-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 7940694016
  memTotal: 8328671232
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-2.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/502/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 12m 6.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 8332595200
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 48
  runRoot: /run/user/502/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.0
  Built: 1666340195
  BuiltTime: Fri Oct 21 16:16:35 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.0
```

**Comment by fedinskiy** [comment]
fixed by https://github.com/quarkusio/quarkus/pull/41100

**Comment by geoand** [comment]
Thanks for checking!
