### ISSUE TITLE
Weird problem when using interface + class for JAX-RS Resources + Auth

### ISSUE THREAD

**Issue by davidfrickert** [quarkusio/quarkus#28732]
### Describe the bug

When using interfaces with JAX-RS annotations plus classes without those annotations + `@RolesRequired`, there seems to be a weird problem.

Logs:
```
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build

Stack frame: io.quarkus.resteasy.reactive.server.runtime.security.EagerSecurityHandler.handle(EagerSecurityHandler.java:62)
Required type: interface io.quarkus.security.spi.runtime.SecurityCheckStorage
Required qualifiers: [@javax.enterprise.inject.Default()]
Removed beans:
	- SYNTHETIC bean  [types=[interface io.quarkus.security.spi.runtime.SecurityCheckStorage], qualifiers=null]
Solutions:
	- Application developers can eliminate false positives via the @Unremovable annotation
	- Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
	- See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
	- Enable the DEBUG log level to see the full stack trace
================================================================================

2022-10-21 00:55:21,948 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-2) HTTP Request to /hello failed, error id: 04032c56-8cb1-4a3b-a007-a0cd2c01db5c-1: java.lang.NullPointerException: Cannot invoke "io.quarkus.security.spi.runtime.SecurityCheckStorage.getSecurityCheck(io.quarkus.security.spi.runtime.MethodDescription)" because the return value of "io.quarkus.arc.InstanceHandle.get()" is null
	at io.quarkus.resteasy.reactive.server.runtime.security.EagerSecurityHandler.handle(EagerSecurityHandler.java:62)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:124)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:142)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:51)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:18)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:8)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:117)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.checkPermission(HttpAuthorizer.java:100)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:233)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:225)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2$1.onItem(HttpSecurityRecorder.java:137)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2$1.onItem(HttpSecurityRecorder.java:127)
```
This problem can be kinda solved by adding this bean to the unremovable beans list by config. 
But, by doing so, any JAX-RS custom exception mappers for Forbidden and Unauthorized seem to stop working.

### Expected behavior

Requests with correct Auth return 200.
Requests with invalid Auth return 401, using custom JAX-RS exception mapper.
Requests without necessary roles return 403, using custom JAX-RS exception mapper.

### Actual behavior

All requests return 500.

After adding the bean to the unremovable list,

Requests with correct Auth return 200.
Requests with invalid Auth return 401, using default response.
Requests without necessary roles return 403, using default response.

### How to Reproduce?

https://github.com/davidfrickert/quarkus-resteasy-reactive-resource-interfaces-auth
Run `GreetingResourceImplTest` (only contains the http status 500 case described)

### Output of `uname -a` or `ver`

Linux dfrickert 6.0.2-3-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Oct 15 18:49:52 UTC 2022 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment (build 17.0.5+1) OpenJDK 64-Bit Server VM (build 17.0.5+1, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /opt/maven Java version: 17.0.5, vendor: N/A, runtime: /usr/lib/jvm/java-17-openjdk Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.0.2-3-manjaro", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Thanks for reporting.

https://github.com/quarkusio/quarkus/pull/28736 should fix the problem
