### ISSUE TITLE
Using Caffeine cach with RequestScoped bean can lead to error

### ISSUE THREAD

**Issue by jtama** [quarkusio/quarkus#28755]
### Describe the bug

In a application using @Cache annotation on a a method with `Principal` parameter, exception occures with the following message : 

```
2022-10-21 16:13:31,935 SEVERE [com.git.ben.caf.cac.BoundedLocalCache] (ForkJoinPool.commonPool-worker-13) Exception thrown when performing the maintenance task: javax.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=io.quarkus.oidc.runtime.OidcJsonWebTokenProducer, id=08f8ad3807046c8f7a5d15c697e2f86e06a9bf82]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:55)
	at org.eclipse.microprofile.jwt.OidcJsonWebTokenProducer_ProducerMethod_currentAccessToken_6cc9acf87bb9cb50add3593d880ba325b4a9f587_ClientProxy.arc$delegate(Unknown Source)
	at org.eclipse.microprofile.jwt.OidcJsonWebTokenProducer_ProducerMethod_currentAccessToken_6cc9acf87bb9cb50add3593d880ba325b4a9f587_ClientProxy.hashCode(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfPresent(ConcurrentHashMap.java:1806)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.evictEntry(BoundedLocalCache.java:912)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.expireAfterWriteEntries(BoundedLocalCache.java:836)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.expireEntries(BoundedLocalCache.java:785)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1491)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1460)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:3359)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.exec(BoundedLocalCache.java:3346)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### Expected behavior

Application should run with no exceptions

### Output of `uname -a` or `ver`

Darwin XXXXX.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "18.0.1" 2022-04-19

### Quarkus version or git rev

2.13.2.Final

### Additional information

As a workaround, the `accessToken` can be used as method parameter.

**Comment by sberyozkin** [comment]
Hmm, hi @mkouba @Ladicek, what do you think of this exception ?

**Comment by sberyozkin** [comment]
Actually, @jtama, where is ` org.eclipse.microprofile.jwt.OidcJsonWebTokenProducer` is coming from ?

**Comment by jtama** [comment]
It's from `@RegisterProvider(AccessTokenRequestFilter.class)` i guess.

I have to add that a cache we can't use intensively, is not very usefull ;)

**Comment by sberyozkin** [comment]
Hmm, `at org.eclipse.microprofile.jwt.OidcJsonWebTokenProducer_ProducerMethod_currentAccessToken` confuses me, given the actual package, https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcJsonWebTokenProducer.java :-), I guess this is the proxying in action...

But in any case, the injection point [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcJsonWebTokenProducer.java#L31) looks fine, so somehow having `@Cache` interferes, lets see what Martin, Ladislav say

**Comment by geoand** [comment]
This sounds like a context propagation issue...

**Comment by jtama** [comment]
Seems it has nothing to do with intensive usage, the exception occures on cache eviction due to expiration. And indeed there is no RequestContext at eviction time. I just a bit puzzled to be the first to fall into this case...

**Comment by Ladicek** [comment]
Sounds like the token is part of the cache key? Which is probably a bad idea?

**Comment by geoand** [comment]
@jtama could you provide us with a sample application that exhibits this behavior so we don't have to resort to guesswork about what's going on?

**Comment by jtama** [comment]
In debugging session, the key is indeed `org.eclipse.microprofile.jwt.OidcJsonWebTokenProducer_ProducerMethod_currentAccessToken_6cc9acf87bb9cb50add3593d880ba325b4a9f587_ClientProxy`...

Trying to check how the key gets injected, and to code a reproducer.

**Comment by jtama** [comment]
The idea is that we have a method that doesn't take any parameter but whose result depend on the connected user. so we have to pass _something_ so that different users don't get the same result, event though the parameter isn't used at all.

We have a workaround, we will use the `SecurityIdentity#getCredential(AccessTokenCredential.class).getToken()` result as method param. It should be unique enough ;).

**Comment by sberyozkin** [comment]
@jtama 

>The idea is that we have a method that doesn't take any parameter but whose result depend on the connected user. so we have to pass something so that different users don't get the same result, event though the parameter isn't used at all.

Does it have to be `Principal` or can it be `Authorization` HTTP header, for example ?

**Comment by jtama** [comment]
Yes that's the workaround. The issue isn't linked with token propagation, i will rename the issue.
It could be worth noting this limit somewhere.

**Comment by jtama** [comment]
Issue updated. I let you decide wether this method should be closed or not.

**Comment by geoand** [comment]
So essentially a cached method parameter is a request scoped bean, we get this issue?

If so, then I think it's something we can detect at build time and warn or even fail. @Ladicek @mkouba @gwenneg WDYT?

**Comment by jtama** [comment]
That's a very good point !

**Comment by mkouba** [comment]
> If so, then I think it's something we can detect at build time and warn or even fail.

Well, I'm not quite sure there's an easy and realiable way to detect this at build time. I.e. the fact that a method parameter is a bean type of a `@RequestScoped` bean does not necessarily mean that a contextual reference/client proxy will be used as an argument, or? In this particular case, the `java.security.Principal` could be anything.

We could easily detect this at runtime though.

**Comment by geoand** [comment]
> the fact that a method parameter is a bean type of a @RequestScoped bean does not necessarily mean that a contextual reference/client proxy will be used as an argument

In what case would it not be?

**Comment by geoand** [comment]
> We could easily detect this at runtime though.

I don't think runtime makes a lot of sense, because at runtime you'll run into the problem anyway :)

**Comment by mkouba** [comment]
> > the fact that a method parameter is a bean type of a @RequestScoped bean does not necessarily mean that a contextual reference/client proxy will be used as an argument
> 
> In what case would it not be?

In the case that you use the bean type "outside" of CDI. Imagine you have a `@RequestScoped` producer for `java.util.List` and then use the `List` as a param type of a method and `List.of("foo")` as an argument.

**Comment by geoand** [comment]
Sure, that could happen, but it's probable unlikely.

**Comment by Ladicek** [comment]
Martin has a good point actually, if the static parameter type is not a bean class but some generic interface, then failing the build would be a terrible idea. I know for a fact that we have a bean with `java.util.Map` as one of its bean types in Quarkus, for example :-)

**Comment by mkouba** [comment]
> Sure, that could happen, but it's probable unlikely.

It depends. Many producer methods work with "regular" JDK types (take a look at MP Config and JBeret for example). And in general, if you use CDI for integration you often create beans from SPI types that can be used separately.

**Comment by geoand** [comment]
Okay, you folks know more about it then I do, so I'll rest my case and leave any potential follow ups on this to you :)

**Comment by jtama** [comment]
In that case, maybe just a simple warning in the [dedicated guide](https://quarkus.io/guides/cache#cacheresult) ?

**Comment by jtama** [comment]
Wow, that required some digging ;)
