### ISSUE TITLE
docker push failed... See docker output for more details

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#28770]
### Description

I'm currently trying to push my image with

> ./gradlew my-application:build -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true --stacktrace

However, I'm running into an issue and there is insufficient detail about the reason:

```
Caused by: java.lang.RuntimeException: Execution of 'docker push my-registry/my-image:0.1.0-my-tag-SNAPSHOT' failed. See docker output for more details
        at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerException(DockerProcessor.java:330)
        at io.quarkus.container.image.docker.deployment.DockerProcessor.pushImage(DockerProcessor.java:323)
        at io.quarkus.container.image.docker.deployment.DockerProcessor.lambda$createContainerImage$3(DockerProcessor.java:220)
        at io.quarkus.container.image.docker.deployment.DockerProcessor.createContainerImage(DockerProcessor.java:220)
        at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerBuildFromJar(DockerProcessor.java:106)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

1. Why can't Quarkus capture and provide those logs and one has to look elsewhere?
2. Where would I have to look to see those logs according to the hint "See docker output for more details"?

**Comment by geoand** [comment]
Doesn't the output that shows up before the stacktrace provide the necessary information?

If it does not show up, does adding `--console=plain` to the gradle invocation make a difference?
