### ISSUE TITLE
Discovered unresolved method during parsing: io.prometheus.client.exporter.HTTPServer.<init>(int)

### ISSUE THREAD

**Issue by neoDaice** [quarkusio/quarkus#28775]
### Describe the bug

I am using prometheus java client in my program like this to start a httpserver:
```java
    void startUp(@Observes StartupEvent event) throws IOException {
        new HTTPServer(appConfig.prometheus().httpServerPort());
        deviceCollector.register();
    }
```

a quarkus-run.jar run successfully，but when i use native to build the binary: **mvn clean package -U -DskipTests -Dnative -Dquarkus.native.container-build=true**
maven outputs the following log：
```posh
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.prometheus.client.exporter.HTTPServer.<init>(int). This error is reported at image build time because class com.sensetime.jupiter.app.prometheus.CollectorRegister is registered for linking at image build time by command line
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:298)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:288)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:244)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1766)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1756)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5223)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3359)
```

my jdk version is 17.0.5 and  maven version is 3.8.6, quarqus version is 2.13.1.Final

**Comment by geoand** [comment]
Quarkus does not provide any explicit support for Prometheu's Client Java module
