### ISSUE TITLE
SSE with comment only fails when using resteasy reactive 

### ISSUE THREAD

**Issue by segersb** [quarkusio/quarkus#28801]
### Describe the bug

An error is thrown when trying to send a comment-only SSE event.
This was not the case when using the non-reactive version.

Comment-only events should be possible according to the MDN docs
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events
_The comment line can be used to prevent connections from timing out; a server can send a comment periodically to keep the connection alive._

As a workaround I was able to fix the issue by overriding a resteasy class.
https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/SseUtil.java

Wrapping the data serialization in a null check solved the issue for me
```
if (event.getData() != null) {
  String data = serialiseDataToString(context, event, eventMediaType);
  serialiseField(context, sb, "data", data, true);
}
```

Stack trace of the error
```
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getInterfaces()" because "currentClass" is null
  at org.jboss.resteasy.reactive.common.core.Serialisers.findResourceWriters(Serialisers.java:180)
  at org.jboss.resteasy.reactive.common.core.Serialisers.findWriters(Serialisers.java:256)
  at org.jboss.resteasy.reactive.common.core.Serialisers.findWriters(Serialisers.java:234)
  at org.jboss.resteasy.reactive.server.core.SseUtil.serialiseDataToString(SseUtil.java:127)
  at org.jboss.resteasy.reactive.server.core.SseUtil.serialiseEvent(SseUtil.java:70)
  at org.jboss.resteasy.reactive.server.core.SseUtil.send(SseUtil.java:36)
  at org.jboss.resteasy.reactive.server.jaxrs.SseEventSinkImpl.send(SseEventSinkImpl.java:33)
```

### Expected behavior

A comment-only SSE event can be sent.

### Actual behavior

Sending a comment-only SSE event throws an error.

### How to Reproduce?

Send a comment-only SSE

```
OutboundSseEvent sseEvent = sse.newEventBuilder().comment("keepalive").build();
sseEventSink.send(sseEvent);
```

### Quarkus version or git rev

2.12.3

**Comment by geoand** [comment]
Thanks for reporting.

Is there any chance you can provide a sample application that exhibits this behavior?

**Comment by geoand** [comment]
Closing this as we never got a reproducer.

Feel free to reopen if you do come up with one.
