### ISSUE TITLE
use redis HashCommands.hgetall and report java.lang.UnsupportedOperationException: This type doesn't hold a Map type

### ISSUE THREAD

**Issue by neoDaice** [quarkusio/quarkus#28837]
### Describe the bug

the hash object that I store in redis is:
```
{"a":1,"b":2,"c":3}
```

my code:
```
    private final HashCommands<String, String, Integer> commands;
    
    private static final String REDIS_KEY = "my_key";

    public Demo(RedisDataSource ds) {
        commands = ds.hash(Integer.class);
    }

    public Map<String, Integer> getall(){
        return commands.hgetall(REDIS_KEY);
    }
```
when i use getall function, log follows:
```
Caused by: java.lang.UnsupportedOperationException: This type doesn't hold a Map type
	at io.vertx.redis.client.Response.getKeys(Response.java:248)
	at io.vertx.mutiny.redis.client.Response.getKeys(Response.java:215)
	at io.quarkus.redis.runtime.datasource.Marshaller.decodeAsMap(Marshaller.java:101)
	at io.quarkus.redis.runtime.datasource.AbstractHashCommands.decodeMap(AbstractHashCommands.java:177)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
	at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
	at io.smallrye.mutiny.vertx.DelegatingHandler.handle(DelegatingHandler.java:25)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Eventually$1.onSuccess(Eventually.java:44)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
	at io.vertx.core.impl.future.Eventually.onSuccess(Eventually.java:41)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.redis.client.impl.RedisStandaloneConnection.handle(RedisStandaloneConnection.java:409)
	at io.vertx.redis.client.impl.RESPParser.handleResponse(RESPParser.java:296)
	at io.vertx.redis.client.impl.RESPParser.handle(RESPParser.java:128)
	at io.vertx.redis.client.impl.RESPParser.handle(RESPParser.java:24)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:100)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:239)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:129)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:414)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:390)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:157)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
May I ask where I used it incorrectly.

Thanks

### Output of `java -version`

17

### Quarkus version or git rev

2.13.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

**Comment by cescoffier** [comment]
Which version of redis do you use?

**Comment by neoDaice** [comment]
redis version is :5.0.14

**Comment by neoDaice** [comment]
here is my debug info:
![image](https://user-images.githubusercontent.com/43130355/197944196-ede908c9-36b8-41bd-bab3-662b931bc752.png)
you can see redis hgetall return a list

**Comment by cescoffier** [comment]
With Redis 7 the format is `{a: 1, b: 2, c: 3}`.

**Comment by cescoffier** [comment]
I just tried with Redis 5, and yes, they change the format. 
The API is designed for Redis 7.

**Comment by neoDaice** [comment]
👍 i konw,thanks

**Comment by neoDaice** [comment]
If I use redis5, is there a version available about quarkus-redis-client

**Comment by cescoffier** [comment]
No, however, I was able to implement a fix. I cannot give you an ETA as I need to rework the test system to test on Redis 5, 6 and 7 instead of only 7.

**Comment by neoDaice** [comment]
> No, however, I was able to implement a fix. I cannot give you an ETA as I need to rework the test system to test on Redis 5, 6 and 7 instead of only 7.

i got it,thanks

**Comment by cescoffier** [comment]
See my PR (#28854) - not very happy with how to test on multiple Redis, but happy to get almost everything working on redis 5 (except of course, unsupported commands).
