### ISSUE TITLE
Camel EndpointRouteBuilder throws org.objectweb.asm.MethodTooLargeException

### ISSUE THREAD

**Issue by miguel-figueiredo** [quarkusio/quarkus#28864]
### Describe the bug

A class that implements a Camel EndpointRouteBuilder with six methods additional methods (besides configure) throws an exception when starting quarkus.
Note that if the builder has less than six additional methods there is no error.

### Expected behavior

Quarkus starts without error.

### Actual behavior

An exception is thrown:

```
$ mvn clean quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.acme:camel-reproducer >----------------------
[INFO] Building camel-reproducer 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ camel-reproducer ---
[INFO] Deleting /Users/miguel.pedro/workspace/quarkus-examples/camel-reproducer/target
[INFO]
[INFO] --- quarkus-maven-plugin:2.13.3.Final:dev (default-cli) @ camel-reproducer ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources @ camel-reproducer
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.13.3.Final:generate-code @ camel-reproducer
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile @ camel-reproducer
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/miguel.pedro/workspace/quarkus-examples/camel-reproducer/target/classes
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ camel-reproducer
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/miguel.pedro/workspace/quarkus-examples/camel-reproducer/src/test/resources
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.13.3.Final:generate-code-tests @ camel-reproducer
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile @ camel-reproducer
[INFO] No sources to compile
Listening for transport dt_socket at address: 5005
2022-10-26 17:11:53,758 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2022-10-26 17:11:53,787 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:322)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:565)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	... 6 more
Caused by: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:511)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:214)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:225)
	at io.quarkus.arc.processor.SubclassGenerator.generate(SubclassGenerator.java:127)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:289)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:286)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 5 more

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:322)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:565)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	... 6 more
Caused by: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:511)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:214)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:225)
	at io.quarkus.arc.processor.SubclassGenerator.generate(SubclassGenerator.java:127)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:289)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:286)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 5 more

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	... 9 more
Caused by: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.util.concurrent.ExecutionException: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:322)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:565)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	... 6 more
Caused by: org.objectweb.asm.MethodTooLargeException: Method too large: org/acme/MyBuilder_Subclass.<init> (Ljavax/enterprise/context/spi/CreationalContext;Lio/quarkus/arc/InjectableInterceptor;)V
	at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:511)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:214)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:225)
	at io.quarkus.arc.processor.SubclassGenerator.generate(SubclassGenerator.java:127)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:289)
	at io.quarkus.arc.processor.BeanProcessor$4$2.call(BeanProcessor.java:286)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 5 more
```

### How to Reproduce?

Reproducer: https://github.com/miguel-figueiredo/quarkus-examples/tree/master/camel-reproducer

Steps to reproduce:

1. Run `./mvnw compile quarkus:dev` 

### Output of `uname -a` or `ver`

Darwin PT-340360-MBP32M1P.lan 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 11.0.16 2022-07-19 LTS OpenJDK Runtime Environment Corretto-11.0.16.8.1 (build 11.0.16+8-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.16.8.1 (build 11.0.16+8-LTS, mixed mode)

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /opt/homebrew/Cellar/maven/3.8.6/libexec Java version: 11.0.16, vendor: Amazon.com Inc., runtime: /Users/miguel.pedro/.sdkman/candidates/java/11.0.16-amzn Default locale: en_PT, platform encoding: UTF-8 OS name: "mac os x", version: "12.6", arch: "aarch64", family: "mac"

**Comment by mkouba** [comment]
Hmm, I will take a look. The `RouteBuilder` and `BuilderSupport` have ~ 100 methods which should not be a problem.

**Comment by mkouba** [comment]
FTR `MyBuilder` has no associated interceptors so you can set `quarkus.arc.dev-mode.monitoring-enabled=false` to avoid this particular problem in the dev mode. Of course, this would not help once you add any other interceptor binding to the bean.

**Comment by mkouba** [comment]
Ah, in fact `MyBuilder` also `implements EndpointBuilderFactory` that extends over 300 interfaces with default methods which are also intercepted. So in the end, we need to initialize intercepted metadata for more than 1000 methods in the constructor of the `MyBuilder_Subclass` and that seems to be the current limit. We'll need to split the logic in the constructor, i.e. something similar to what we do for the generated `ComponentsProvider`.

CC @Ladicek @manovotn

**Comment by manovotn** [comment]
Will take a look next week, prob on Mon.

**Comment by geoand** [comment]
I've mentioned this before but I'll bring it up again: should we flip the default for `quarkus.arc.dev-mode.monitoring-enabled`?

**Comment by mkouba** [comment]
> I've mentioned this before but I'll bring it up again: should we flip the default for `quarkus.arc.dev-mode.monitoring-enabled`?

That's a way how to mitigate the problem, not a way to fix the problem. Any interceptor binding (`@Transactional`, `@ActivateRequestContext`, `@CacheResult`, `@Retry`...) added to the bean would break it anyway.

That said, I've been thinking about `quarkus.arc.dev-mode.monitoring-enabled=false` as well and I think that it's probably a reasonable idea. @Ladicek @manovotn WDYT?

**Comment by geoand** [comment]
I know it's not a real fix, but the feature does seem to exacerbate issues which is why I am proposing to have it off be default

**Comment by mkouba** [comment]
OTOH it helped us to spot some annoying bugs earlier. Anyway, here we go: https://github.com/quarkusio/quarkus/pull/28940

**Comment by manovotn** [comment]
I spent some time today trying this out. I think I know what do to with it, I just need to translate that into Gizmo code which is where I am stuck now. Will get back on it tomorrow.

**Comment by mkouba** [comment]
> I spent some time today trying this out. I think I know what do to with it, I just need to translate that into Gizmo code which is where I am stuck now. Will get back on it tomorrow.

I can try to reach out and help ;-). Feel free to ping me tomorrow...
