### ISSUE TITLE
fetch A field relate other class with `@OneToOne(fetch = FetchType.LAZY)` by Mutiny.fetch not work

### ISSUE THREAD

**Issue by paomian** [quarkusio/quarkus#28975]
### Describe the bug

fetch A field relate other class with `@OneToOne(fetch = FetchType.LAZY)` by Mutiny.fetch not work
code in https://github.com/paomian/code-with-quarkus can reproduce this error.

### Expected behavior

it will get field data.

### Actual behavior

throw exception

### How to Reproduce?

1. clone https://github.com/paomian/code-with-quarkus
2. config your postgresql db or use devservices(I'm not try).
3. run `quarkus dev`
4. run `curl localhost:8080/hello`
5. run `curl localhost:8080/hello/world/1` maybe should replace [1] to other which return by step 4

### Output of `uname -a` or `ver`

Darwin paomians-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /Users/paomian/.m2/wrapper/dists/apache-maven-3.8.6-bin/67568434/apache-maven-3.8.6 Java version: 17.0.5, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home Default locale: en_CN, platform encoding: UTF-8 OS name: "mac os x", version: "12.6", arch: "x86_64", family: "mac"

### Additional information

I found this https://github.com/quarkusio/quarkus/issues/16638 which similar this issue

**Comment by DavideD** [comment]
Checking ...
I remember we used to have an issue with lazy *-to-one, but it should be fixed.

**Comment by DavideD** [comment]
Looks like a bug in Hibernate Reactive, I will write a test for it and get back to you.

(By the way, Master/Slave [are quite problematic terms](https://www.selfdefined.app/definitions/master-slave/). It might be a good idea to pick different names in the future)

**Comment by DavideD** [comment]
Mmmh... it seems to work when I only use Hibernate Reactive (without Quarkus).
But, it doesn't work if I use Hibernate Reactive in Quarkus (without Panache).

**Comment by DavideD** [comment]
Nevermind, something is also not working in Hibernate Reactive. I will continue to check and get back when I've figured it out

**Comment by DavideD** [comment]
I've created the issue for Hibernate Reactive: https://github.com/hibernate/hibernate-reactive/issues/1417

**Comment by DavideD** [comment]
@gavinking Given that this is a one to one association (with bytecode enhancement enabled), what's the right approach to use?

Entity:
```
@Entity
class Leader {

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "leader", cascade = CascadeType.ALL)
    Follower follower

}
```

1. ```
    Mutiny.fetch(leader.getFollower())
    ``` 
2. ```
     Attribute<? extends Leader, ?> followerAttribute = ...
     session.fetch(master, followerAttribute)
     ```

Should both work?

**Comment by gavinking** [comment]
You might have to use the overload of `fetch()` where you pass in the field name. (Remember there's a section of the docs which deals with field-level lazy fetching.) But I didn't have time to look at it, so I'm not sure.

**Comment by DavideD** [comment]
The problem is that I'm not sure what we mean with `field-level` fetching. Does it include anything?  I guess it means anything that's not a collection.

It seems there are also some differences when BE is enabled and it's not.

**Comment by DavideD** [comment]
By the way, @paomian, if you need a workaround, this will work:
```
 @ApplicationScoped
  public class SlaveRepo implements PanacheRepository<Slave> {
  }
```
```
  @Inject
  SlaveRepo slaveRepo;

  @GET
  @Path("/world/{masterId}")
  public Uni<String> world(@PathParam("masterId") Long masterId) {
      return slaveRepo
              .find( "master.id = :id", Parameters.with( "id", masterId ) )
              .singleResult()
              .map( Slave::getId )
              .map( String::valueOf );
    }
```

**Comment by paomian** [comment]
@DavideD thanks. The code write by you just get id.This project just reproduce this exception.Maybe class `Slave` have other field to get.
I'm change the `FetchType.LAZY` to `FetchType.EAGER` now. 
It's solve my problem temporary. but I still want use `LAZY` in this place .

**Comment by DavideD** [comment]
You should be able to change the query to load all the info you need without changing the field to EAGER.

**Comment by DavideD** [comment]
It's should be more efficient than running a separate query to load the lazy fields

**Comment by FroMage** [comment]
Keep in mind that with Panache we rewrite all field accesses to use the corresponding generated getter that dispatches to the Hibernate-generated lazy-loader getter. At least that's the case for the ORM version.

**Comment by DavideD** [comment]
Hibernate Reactive is different than ORM in this area. One needs to call `.fetch` explicitely or it's not going to work.

**Comment by gavinking** [comment]
@DavideD I think you figured it out, but I mean things like `@Basic(fetch=LAZY)`, the stuff I talk about here:

https://hibernate.org/reactive/documentation/1.1/reference/html_single/#_field_level_lazy_fetching

Lazy fetching for `@ManyToOne` isn't field-level lazy because we use a proxy. Lazy fetching for `@OneToOne` is, because we can't use a proxy.

**Comment by DavideD** [comment]
I know that we have a paragraph in the docs about it. But I think we need more examples. Also, the problem here was a lazy bi one-to-one, not a basic fetch lazy. It seems that depending on which side one wants to fetch, it will need a different approach. I think some HQL won't work if you select on side of the associaiton.

But I need to have a better look on how we've implemented the fetch methods.

**Comment by JFeoks** [comment]
Hi! 
@DavideD , I also have a problem with Lazy loading, but I would like to make sure that this happens under similar circumstances so as not to open a new issue. Can you take a brief look at my case too, please? Is this the same thing, or do I need to start a new issue?

For simplicity, I trimmed the model:
```
@Entity
@Cacheable
@DynamicUpdate
@Data
public class Item extends BaseEntity {

    @Column(name = "BRAND_ID")
    private Long brandId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "BRAND_ID",
            referencedColumnName = "wbBrandId",
            updatable = false,
            insertable = false
    )
    private Brand brand;

    @OneToOne(mappedBy = "item", fetch = FetchType.LAZY)
    @JoinColumn(insertable = false, updatable = false)
    @EqualsAndHashCode.Exclude
    private Statistic statistic;
}
```

Join fetch query:
```
@Override
    public Uni<Item> findById(UUID id) {
        return find( "from Item i " +
                        "left join fetch i.statistic " +
                        "left join fetch i.brand " +
                        "where i.id = ?1",  id)
                .firstResult();
    }
```

This leads in my mapper to::
```
2022-11-18 18:17:02,345 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-3) Request failed: java.lang.ClassCastException: class java.util.concurrent.CompletableFuture cannot be cast to class ru.jfeoks.shopping.assistant.wildberries.model.entity.Brand (java.util.concurrent.CompletableFuture is in module java.base of loader 'bootstrap'; ru.jfeoks.shopping.assistant.wildberries.model.entity.Brand is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @1abebef3)
	at ru.jfeoks.shopping.assistant.wildberries.model.entity.Item.$$_hibernate_read_brand(Item.java)
	at ru.jfeoks.shopping.assistant.wildberries.model.entity.Item.getBrand(Item.java:37)
	at ru.jfeoks.shopping.assistant.wildberries.service.mapping.ItemMapperImpl.entityToDto(ItemMapperImpl.java:39)
```

From the interesting: 
1) everything works with eager 
2) getStatistic() works fine, but for getBrand() there is always such an error, even if you use Mutiny.fetch()

Quarkus version: 2.14.0.Final
+ quarkus-hibernate-reactive
+ quarkus-hibernate-reactive-panache

**Comment by DavideD** [comment]
I think it's the same issue. [I've already sent a fix in Hibernate Reactive](https://github.com/hibernate/hibernate-reactive/commit/13fb7c31abcbe158ad0caae9c614610d1d05a2ee?diff=unified).

This should work in the next release (maybe you can test the snapshot on `main` and let use know).

**Comment by JFeoks** [comment]
@DavideD, thanks! I'll try to experiment with it. So far, my WA is to use the parameter not as a foreign key, but as an id.

**Comment by lucamolteni** [comment]
> I think it's the same issue. [I've already sent a fix in Hibernate Reactive](https://github.com/hibernate/hibernate-reactive/commit/13fb7c31abcbe158ad0caae9c614610d1d05a2ee?diff=unified).
> 
> This should work in the next release (maybe you can test the snapshot on `main` and let us know).

This should be released by now right? @DavideD can you double check so that we can close this?

**Comment by DavideD** [comment]
This is an old issue and nobody gave us any additional feedback. I think we can close it.

I tested it quickly with the latest Hibernate Reactive and it seems to work fine.
The fix was included in Hibernate Reactive 2.0.0.Alpha1 (The latest quarkus is using Hibernate Reactive 3.0)
