### ISSUE TITLE
IsolatedDevModeMain fails to start with module-info present

### ISSUE THREAD

**Issue by faermanj** [quarkusio/quarkus#29012]
### Describe the bug

Starting a @QuarkusMain class within an IDE when using modules throws the following exception:
```
Nov 02, 2022 4:52:44 PM io.quarkus.deployment.dev.IsolatedDevModeMain firstStart
INFO: Attempting to start live reload endpoint to recover from previous Quarkus startup failure
Nov 02, 2022 4:52:44 PM io.quarkus.deployment.dev.IsolatedDevModeMain firstStart
ERROR: Failed to start quarkus
java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigProviderResolver: io.smallrye.config.SmallRyeConfigProviderResolver not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:900)
	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1084)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.eclipse.microprofile.config.spi.ConfigProviderResolver.loadSpi(ConfigProviderResolver.java:135)
	at org.eclipse.microprofile.config.spi.ConfigProviderResolver.instance(ConfigProviderResolver.java:124)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:180)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
	at io.quarkus.deployment.dev.IDEDevModeMain.accept(IDEDevModeMain.java:71)
	at io.quarkus.deployment.dev.IDEDevModeMain.accept(IDEDevModeMain.java:28)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
	at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:56)
	at quarkus.core@2.13.3.Final/io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:99)
	at quarkus.core@2.13.3.Final/io.quarkus.runtime.Quarkus.run(Quarkus.java:86)
	at quarkus.core@2.13.3.Final/io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at cj/cj.Main.main(Main.java:12)

Nov 02, 2022 4:52:44 PM io.quarkus.deployment.dev.IsolatedDevModeMain firstStart
ERROR: Failed to recover after failed start
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:173)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
	at io.quarkus.deployment.dev.IDEDevModeMain.accept(IDEDevModeMain.java:71)
	at io.quarkus.deployment.dev.IDEDevModeMain.accept(IDEDevModeMain.java:28)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
	at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:56)
	at quarkus.core@2.13.3.Final/io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:99)
	at quarkus.core@2.13.3.Final/io.quarkus.runtime.Quarkus.run(Quarkus.java:86)
	at quarkus.core@2.13.3.Final/io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at cj/cj.Main.main(Main.java:12)
Caused by: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigProviderResolver: io.smallrye.config.SmallRyeConfigProviderResolver not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:900)
	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1084)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.eclipse.microprofile.config.spi.ConfigProviderResolver.loadSpi(ConfigProviderResolver.java:135)
	at org.eclipse.microprofile.config.spi.ConfigProviderResolver.instance(ConfigProviderResolver.java:124)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
	at io.quarkus.runtime.configuration.ConfigInstantiator.handleObject(ConfigInstantiator.java:56)
	at io.quarkus.runtime.logging.LoggingSetupRecorder.handleFailedStart(LoggingSetupRecorder.java:73)
	at io.quarkus.runtime.logging.LoggingSetupRecorder.handleFailedStart(LoggingSetupRecorder.java:68)
	... 20 more

```

Running the same code works fine if it is without module-info or outside IDE (quarkus, mvn, java -jar ...)
Both IntelliJ and VSCode presenting the same issue.

source repo: https://github.com/CaravanaCloud/cloud-janitor 

### Expected behavior

Starts the quarkus app whithin the IDE

### Actual behavior

Quarkus fails to start

### How to Reproduce?

1. add a module-info.java to an app
2. try running it from an IDE

### Quarkus version or git rev

2.13.3

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
