### ISSUE TITLE
Unable to invoke own Serializer/Deserializer within Kafka in native compiled program

### ISSUE THREAD

**Issue by wglanzer** [quarkusio/quarkus#2903]
**Describe the bug**
If I specify my own serializer/deserializers in application.properties, kafka does not find them in native compiled program. On the other hand all works just fine in "normal" mode, without native compilation.

The following error appears on the console:

``` java
org.apache.kafka.common.config.ConfigException: Invalid value io.retailplanet.backend.common.api.EventDeserializer for configuration value.deserializer: Class io.retailplanet.backend.common.api.EventDeserializer could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:718)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:471)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:464)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
	at org.apache.kafka.clients.consumer.ConsumerConfig.<init>(ConsumerConfig.java:511)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:624)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:605)
	at io.vertx.kafka.client.consumer.KafkaReadStream.create(KafkaReadStream.java:98)
	at io.vertx.kafka.client.consumer.KafkaConsumer.create(KafkaConsumer.java:74)
	at io.vertx.reactivex.kafka.client.consumer.KafkaConsumer.create(KafkaConsumer.java:180)
	at io.smallrye.reactive.messaging.kafka.KafkaSource.<init>(KafkaSource.java:49)
	at io.smallrye.reactive.messaging.kafka.KafkaConnector.getPublisherBuilder(KafkaConnector.java:65)
	at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getPublisherBuilder(Unknown Source)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createPublisherBuilder(ConfiguredChannelFactory.java:147)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$register$5(ConfiguredChannelFactory.java:125)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:125)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:120)
	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory_ClientProxy.initialize(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:104)
	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:18)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(Unknown Source)
	at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:228)
	at io.quarkus.arc.EventImpl.fire(EventImpl.java:69)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcDeploymentTemplate.handleLifecycleEvents(ArcDeploymentTemplate.java:99)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent20.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent20.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:84)
	at io.quarkus.runtime.Application.run(Application.java:196)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

**To Reproduce**
I think you just have to put your own serializer/deserializer in sample kafka projects.

**Configuration**
```properties
# Add your application.properties here, if applicable.
mp.messaging.incoming.BusinessToken_CREATE_IN.value.deserializer=io.retailplanet.backend.common.api.EventDeserializer
mp.messaging.incoming.BusinessToken_CREATE_IN.group.id=userauth
mp.messaging.incoming.BusinessToken_CREATE_IN.auto.offset.reset=latest
mp.messaging.incoming.BusinessToken_CREATE_IN.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.BusinessToken_CREATE_IN.topic=BusinessToken_CREATE
mp.messaging.incoming.BusinessToken_CREATE_IN.connector=smallrye-kafka
mp.messaging.incoming.BusinessToken_CREATE_IN.bootstrap.servers=${KAFKA_SERVERS}
mp.messaging.outgoing.BusinessToken_CREATE_AUTH_OUT.bootstrap.servers=${KAFKA_SERVERS}
mp.messaging.outgoing.BusinessToken_CREATE_AUTH_OUT.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.BusinessToken_CREATE_AUTH_OUT.topic=BusinessToken_CREATE_AUTH
mp.messaging.outgoing.BusinessToken_CREATE_AUTH_OUT.acks=1
mp.messaging.outgoing.BusinessToken_CREATE_AUTH_OUT.connector=smallrye-kafka
mp.messaging.outgoing.BusinessToken_CREATE_AUTH_OUT.value.serializer=io.retailplanet.backend.common.api.EventSerializer
```

**Environment (please complete the following information):**
 - Quarkus version or git rev: 0.17.0
 - Dockerfile, where quarkus runs in:
``` Dockerfile
FROM registry.access.redhat.com/ubi8/ubi-minimal
MAINTAINER w.glanzer@conceptive.io
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD [ "./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.http.port=8080", "-Djava.util.logging.manager=org.jboss.logmanager.LogManager" ]
```

**Comment by cescoffier** [comment]
Can you try to add the `RegisterForReflection` annotation on your serializer and deserializer?

**Comment by gsmet** [comment]
@cescoffier Hmmm, if it fixes the issue, is there a way to look for them and register them automatically? That would sound like a useful addition.

**Comment by wglanzer** [comment]
@cescoffier this did not fix it, same issue appears again.

I read something, that is has something to do with the classloader and the way kafka loads its services. ( `org.apache.kafka.common.utils.Utils#getContextOrKafkaClassLoader`, https://stackoverflow.com/questions/37363119/kafka-producer-org-apache-kafka-common-serialization-stringserializer-could-no )

I missed out some information for you: Maybe it is important to know, that my Serializers/Deserializers are in a separate maven module, which is referenced by the main module.
I already tried using the default "JsonObjectSerializer.class", but that didn't work either.
My simplified serializer looks like this:
```Java
@RegisterForReflection
public class EventSerializer implements Serializer<JsonObject>
{

  @Override
  public void configure(Map<String, ?> configs, boolean isKey)
  {
    // nothing
  }

  @Override
  public byte[] serialize(String topic, JsonObject data)
  {
    if (data == null)
      return null;

    return data.encode().getBytes();
  }

  @Override
  public void close()
  {
    // nothing
  }

}
```

**Comment by emmanuelbernard** [comment]
Yes I suppose that your other maven module does not have a `beans.xml` descriptor or a generated Jandex index (`META-INF/jandex.idx`), see https://quarkus.io/guides/cdi-reference#bean_discovery

If you try that and it works, I think the Kafka extension should look at the configuration and enlist the serializer / deserializers and enlist them e.g. read `mp.messaging.incoming.BusinessToken_CREATE_IN.value.deserializer` ad friends

**Comment by wglanzer** [comment]
@emmanuelbernard is it enough to just annotate my serializers/deserializers with "@ApplicationScoped" ? Tried this, nothing changed. 
In JVM mode my serializers/deserializers work great.

Sorry for this dumb question at all, but I am new to CDI with quarkus - I always used Google Guice for dependency injection in my projects before.

**Comment by emmanuelbernard** [comment]
no, since your serializers are in a different maven module, you need to flag the module itself with the beans.xml file or get a jandex index generated. It's a matter of the classes be in the Jandex index so we can see them during extensions augmentation time. Right know I suspect they are not seen at all.

**Comment by cescoffier** [comment]
@gsmet Codecs are already detected and registered by the extension if there are in the index.

**Comment by wglanzer** [comment]
@emmanuelbernard I created a small repository, if you need it ( https://github.com/wglanzer/quarkus-kafka-exception , with docker-compose to bring up kafka ), because I do not know what I'm doing wrong..
- annoted them with "@RegisterForReflection"
- I created a beans.xml, containing my Serializers as beans.
- I "marked" them as used, with a System.out.println() in my rest resource.

**Comment by emmanuelbernard** [comment]
You did put the `beans.xml` in the wrong directory and in the wrong project :)
Here is the fix https://github.com/wglanzer/quarkus-kafka-exception/pull/1

And a comprehensive answer to add another module's beans to a Quarkus project https://stackoverflow.com/questions/55513502/how-to-create-a-jandex-index-in-quarkus-for-classes-in-a-external-module/55513723#55513723

**Comment by wglanzer** [comment]
Thank you for your patience, it works now :) 👍

**Comment by emmanuelbernard** [comment]
No worries, it's good feedback and we found areas to improve the doc on.
