### ISSUE TITLE
Sporadic «The current thread cannot be blocked» in graphql

### ISSUE THREAD

**Issue by computerlove** [quarkusio/quarkus#29040]
### Describe the bug

We are experiencing sporadic instances of 
```
java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-0
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)
	at io.quarkus.security.runtime.SecurityIdentityAssociation.getIdentity(SecurityIdentityAssociation.java:77)
	at io.quarkus.security.runtime.SecurityIdentityAssociation_ClientProxy.getIdentity(Unknown Source)
        ...
```
in our graphql-application. 

The first code path getting this is 

```java
public class LoggingEventingService implements EventingService {
    @Override
    public void afterExecute(Context context) {
       var user = getUser();
       // logging and something here...
    }
    private User getUser() {
        return Optional.ofNullable(CDI.current().select(SecurityIdentity.class))
                .map(Provider::get)
                .map(SecurityIdentity::getPrincipal) // Here IllegalStateException is thrown
                .map(User::from)
                .orElseGet(() -> new UnknownUser());
    }
}
```

In another application I moved `getUser` to `beforeExecute`, I think in relation to [issue 1455](https://github.com/smallrye/smallrye-graphql/issues/1455) but cannot find an explicit reference to it.

The other instance looks like 
```java
public class Service {
    SecurityIdentity securityIdentity;
    @Query
    public OurUser innloggetBruker() {
        return new OurUser(securityIdentity.getPrincipal());
    }

    public Uni<Something> something(@Source OurUser ou) {
        return somerepo.getTokenForUser(ou.id())
            .flatMap(token -> checkToken(token, innloggetBruker.id()));
    }

   private Uni<Something> checkToken(Token t, String userId) {
     return securityIdentity.hasRole("admin") ? something(...) : somethingElse(...); // Here IllegalStateException is thrown
  }
}
```

Most calls involving these paths execute successfully, only a few invocations fail.

[Complete stacktraces](https://github.com/quarkusio/quarkus/files/9930142/stacktrace.txt)

### Expected behavior

No instances of  java.lang.IllegalStateException: The current thread cannot be blocked.

### Actual behavior

Sporadic  java.lang.IllegalStateException: The current thread cannot be blocked

### How to Reproduce?

Sorry, have not managed to create a reproducer.

### Output of `java -version`

18

### Quarkus version or git rev

2.13.3

**Comment by phillip-kruger** [comment]
@sberyozkin ? Any tips here ?

**Comment by cescoffier** [comment]
Do you have a reproducer? 

The issue is that the security provider seems to be blocking the I/O thread.

**Comment by computerlove** [comment]
No, havent been able to create a reproducer.

**Comment by michalvavrik** [comment]
It's difficult to be 100 % without reproducer, but here are my thoughts:

- the exception is expected as you call `io.quarkus.security.runtime.SecurityIdentityAssociation#getIdentity` and I guess have disabled proactive security so that authentication didn't happen yet in certain cases. Identity can't be access in non blocking manner as `io.quarkus.security.runtime.SecurityIdentityAssociation#identity:77` returns SecurityIdentity in a synchronous manner and blocks.

@computerlove you have 2 scenarios mentioned in the issue description:

-  `LoggingEventingService` returns User in a synchronous matter - then make sure it never are get called on IO thread
- `Service` returns Uni, therefore you should call `io.quarkus.security.runtime.SecurityIdentityAssociation#getDeferredIdentity` which will prevent the issue
- you could probably work around both scenarios by enabling proactive auth (`quarkus.http.auth.proactive=true`), but I'm not that familiar with GraphQL to tell

IMHO it's not a bug.

**Comment by computerlove** [comment]
The problem is not that authentication has not happened. 
In the case with `LoggingEventingService` `SecurityIdentity` has already been used in methods executed before `afterExecute`. (I worked around the problem by resolving `SecurityIdentity` in `beforeExecute` and storing the values I needed in a static Map.

In the `Service` case 
```java
        return new OurUser(securityIdentity.getPrincipal());
```
is run first, then the other method is called with the object returned. 

In the `Service` case the first method is blocking, and the @Source-method async. Will rewrite so that both are async and report back when I know if the frequency of this error changed :)

**Comment by michalvavrik** [comment]
Thanks for response @computerlove , I appreciate it, see my comments below.

> The problem is not that authentication has not happened. In the case with `LoggingEventingService` `SecurityIdentity` has already been used in methods executed before `afterExecute`. (I worked around the problem by resolving `SecurityIdentity` in `beforeExecute` and storing the values I needed in a static Map.
> 

I wrote that as if authentication happened in synchronous way, the result is stored in `io.quarkus.security.runtime.SecurityIdentityAssociation#identity`, therefore next line that blocks the thread shouldn't be null as long as authentication has been successful. Glad you got workaround.

> In the `Service` case
> 
> ```java
>         return new OurUser(securityIdentity.getPrincipal());
> ```
> 
> is run first, then the other method is called with the object returned.
> 
> In the `Service` case the first method is blocking, and the @Source-method async. Will rewrite so that both are async and report back when I know if the frequency of this error changed :)

Great! That's what I meant, rewriting this to async seems like a good solution. Personally I still can't see where is "the bug" and how could we fix this. As long as you are retrieving `deferredIdentity`, thread could only be blocked if there an expensive action performed as processing big files etc. Please try to gather more information on the bug, thank you.

**Comment by computerlove** [comment]
The rewrite to using `SecurityIdentityAssociation.getDeferredIdentity()` does seem to have helped. 

But a new variant of this occured now. 

We inject claims from the jwt into the Gql resource (constructor injection) with
```java
@Claim("nationalId") String nationalId,
@Claim("sub") String subject,
```

and just got an instance of
```
The current thread cannot be blocked: vert.x-eventloop-thread-0
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)
	at io.quarkus.security.runtime.SecurityIdentityAssociation.getIdentity(SecurityIdentityAssociation.java:77)
	at io.quarkus.security.runtime.SecurityIdentityAssociation_ClientProxy.getIdentity(Unknown Source)
	at io.quarkus.security.runtime.SecurityIdentityProxy.isAnonymous(SecurityIdentityProxy.java:28)
	at io.quarkus.security.runtime.SecurityIdentityProxy_ClientProxy.isAnonymous(Unknown Source)
	at io.quarkus.oidc.runtime.OidcJsonWebTokenProducer.getTokenCredential(OidcJsonWebTokenProducer.java:57)
	at io.quarkus.oidc.runtime.OidcJsonWebTokenProducer.currentAccessToken(OidcJsonWebTokenProducer.java:41)
	at io.quarkus.oidc.runtime.OidcJsonWebTokenProducer_ProducerMethod_currentAccessToken_6cc9acf87bb9cb50add3593d880ba325b4a9f587_Bean.create(Unknown Source)
	at io.quarkus.oidc.runtime.OidcJsonWebTokenProducer_ProducerMethod_currentAccessToken_6cc9acf87bb9cb50add3593d880ba325b4a9f587_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:74)
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:30)
	at org.eclipse.microprofile.jwt.OidcJsonWebTokenProducer_ProducerMethod_currentAccessToken_6cc9acf87bb9cb50add3593d880ba325b4a9f587_ClientProxy.arc$delegate(Unknown Source)
	at org.eclipse.microprofile.jwt.OidcJsonWebTokenProducer_ProducerMethod_currentAccessToken_6cc9acf87bb9cb50add3593d880ba325b4a9f587_ClientProxy.claim(Unknown Source)
	at io.smallrye.jwt.auth.cdi.RawClaimTypeProducer.getClaimAsString(RawClaimTypeProducer.java:62)
	at io.smallrye.jwt.auth.cdi.RawClaimTypeProducer_ProducerMethod_getClaimAsString_62631722e3b7b3815f8275b8be1219e2630e227f_Bean.create(Unknown Source)
	at io.smallrye.jwt.auth.cdi.RawClaimTypeProducer_ProducerMethod_getClaimAsString_62631722e3b7b3815f8275b8be1219e2630e227f_Bean.get(Unknown Source)
	at io.smallrye.jwt.auth.cdi.RawClaimTypeProducer_ProducerMethod_getClaimAsString_62631722e3b7b3815f8275b8be1219e2630e227f_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:62)
	at no.gql.ResourceGql_Bean.create(Unknown Source)
	at no.gql.ResourceGql_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:74)
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:30)
	at no.gql.ResourceGql_ClientProxy.arc$delegate(Unknown Source)
	at no.gql.ResourceGql_ClientProxy.tilganger(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at io.smallrye.graphql.execution.datafetcher.helper.ReflectionInvoker.invoke(ReflectionInvoker.java:92)
	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusUniDataFetcher.handleUserMethodCallNonBlocking(QuarkusUniDataFetcher.java:44)
	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusUniDataFetcher.handleUserMethodCall(QuarkusUniDataFetcher.java:26)
	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.AbstractAsyncDataFetcher.invokeAndTransform(AbstractAsyncDataFetcher.java:38)
	at io.smallrye.graphql.execution.datafetcher.AbstractDataFetcher.get(AbstractDataFetcher.java:63)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:282)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:211)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59)
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:670)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:457)
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:407)
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:213)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:73)
	at io.smallrye.mutiny.operators.uni.UniOnTermination$UniOnTerminationProcessor.onItem(UniOnTermination.java:39)
	at io.smallrye.mutiny.operators.uni.UniOnCancellation$UniOnCancellationProcessor.onItem(UniOnCancellation.java:49)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:56)
	at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:37)
	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.AbstractAsyncDataFetcher.lambda$invokeAndTransform$1(AbstractAsyncDataFetcher.java:66)
	at io.smallrye.mutiny.context.BaseContextPropagationInterceptor$ContextualizedTriConsumer.lambda$accept$0(BaseContextPropagationInterceptor.java:353)
	at io.smallrye.context.impl.wrappers.SlowContextualExecutor.execute(SlowContextualExecutor.java:19)
	at io.smallrye.mutiny.context.BaseContextPropagationInterceptor$ContextualizedTriConsumer.accept(BaseContextPropagationInterceptor.java:353)
	at io.smallrye.mutiny.groups.UniOnItemOrFailure.lambda$transformToUni$4(UniOnItemOrFailure.java:167)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:99)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:54)
	at io.smallrye.mutiny.operators.uni.UniOnTermination$UniOnTerminationProcessor.onItem(UniOnTermination.java:39)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.access$100(UniCreateFromKnownItem.java:26)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromPublisher$PublisherSubscriber.onNext(UniCreateFromPublisher.java:73)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
	at io.smallrye.mutiny.operators.multi.MultiSelectFirstOp$MultiSelectFirstProcessor.onItem(MultiSelectFirstOp.java:80)
	at io.smallrye.mutiny.operators.multi.MultiEmitOnOp$MultiEmitOnProcessor.run(MultiEmitOnOp.java:199)
	at io.quarkus.mongodb.impl.Wrappers.lambda$toMulti$2(Wrappers.java:30)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by michalvavrik** [comment]
That's for getting back with results.

The error above comes from injection point, I'm not right man here to answer though. I guess trying field injection wont' fix the issue, right? I think you've got 2 options:

- open an issue (please do it anyway with a `reproducer`)
- you can also inject `SecurityIdentityAssociation`, get deferred identity and then manually do what is done by `io.smallrye.jwt.auth.cdi.RawClaimTypeProducer#getClaimAsString` and `io.quarkus.oidc.runtime.OidcJsonWebTokenProducer#getTokenCredential` respectively. I can see why you would not do it :-)

**Comment by michalvavrik** [comment]
@computerlove I think we should close this issue as I don't see one. If you disagree, please provide reproducer and updated description. Thank you

**Comment by michalvavrik** [comment]
I'm going to close the issue as barring `@Claim` injection, there is no bug and issue was opened for another problem. IMO the injection can't be fixed without heavy refactoring and I'd suggest to access it in non-blocking manner, but please feel free to open dedicated issue for it. Thanks
