### ISSUE TITLE
2.13.3.Final -> ServiceConfigurationError: SmallRyeConfigFactory: QuarkusConfigFactory not a subtype

### ISSUE THREAD

**Issue by nagin** [quarkusio/quarkus#29088]
### Describe the bug

When sending message to Kafka broker , in dev mode error message is thrown after idling for some time. Error message is as
follows
Unable to dispatch message to Kafka: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype 

### Expected behavior

Message should be sent to kafka broker

### Actual behavior

exception is thrown while sending message with below stack trace.

```
ERROR [io.sma.rea.mes.kafka] (ForkJoinPool.commonPool-worker-1) SRMSG18207: Unable to dispatch message to Kafka: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:100)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:64)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
	at io.smallrye.context.impl.DefaultValues.<init>(DefaultValues.java:41)
	at io.smallrye.context.SmallRyeContextManager.<init>(SmallRyeContextManager.java:63)
	at io.smallrye.context.SmallRyeContextManager$Builder.build(SmallRyeContextManager.java:337)
	at io.smallrye.context.SmallRyeContextManagerProvider.getContextManager(SmallRyeContextManagerProvider.java:48)
	at io.smallrye.context.SmallRyeContextManagerProvider.getContextManager(SmallRyeContextManagerProvider.java:37)
	at io.smallrye.context.SmallRyeContextManagerProvider.getManager(SmallRyeContextManagerProvider.java:97)
	at io.smallrye.context.SmallRyeThreadContext.getCurrentThreadContextOrDefaultContexts(SmallRyeThreadContext.java:160)
	at io.smallrye.mutiny.context.DefaultContextPropagationInterceptor.getThreadContext(DefaultContextPropagationInterceptor.java:12)
	at io.smallrye.mutiny.context.BaseContextPropagationInterceptor.decorate(BaseContextPropagationInterceptor.java:33)
	at io.smallrye.mutiny.infrastructure.Infrastructure.decorate(Infrastructure.java:135)
	at io.smallrye.mutiny.groups.UniCreate.emitter(UniCreate.java:422)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.send(ReactiveKafkaProducer.java:127)
	at io.smallrye.reactive.messaging.kafka.impl.KafkaSink.lambda$writeMessageToKafka$3(KafkaSink.java:192)
	at io.smallrye.reactive.messaging.kafka.impl.KafkaSenderProcessor.onNext(KafkaSenderProcessor.java:61)
	at io.smallrye.reactive.messaging.kafka.impl.KafkaSenderProcessor.onNext(KafkaSenderProcessor.java:16)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.streams.utils.ConnectableProcessor.onNext(ConnectableProcessor.java:122)
	at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onNext(CompletionSubscriber.java:85)
	at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onNext(CompletionSubscriber.java:85)
	at io.quarkus.smallrye.reactivemessaging.runtime.devmode.DevModeSupportConnectorFactoryInterceptor$1.onNext(DevModeSupportConnectorFactoryInterceptor.java:62)
	at io.quarkus.smallrye.reactivemessaging.runtime.devmode.DevModeSupportConnectorFactoryInterceptor$1.onNext(DevModeSupportConnectorFactoryInterceptor.java:51)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.streams.utils.WrappedSubscriber.onNext(WrappedSubscriber.java:46)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.streams.utils.ConnectableProcessor.onNext(ConnectableProcessor.java:122)
	at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onNext(CompletionSubscriber.java:85)
	at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onNext(CompletionSubscriber.java:85)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:100)
	at io.smallrye.mutiny.operators.multi.builders.BufferItemMultiEmitter.drain(BufferItemMultiEmitter.java:118)
	at io.smallrye.mutiny.operators.multi.builders.BufferItemMultiEmitter.emit(BufferItemMultiEmitter.java:34)
	at io.smallrye.mutiny.operators.multi.builders.SerializedMultiEmitter.onItem(SerializedMultiEmitter.java:51)
	at io.smallrye.mutiny.operators.multi.builders.SerializedMultiEmitter.emit(SerializedMultiEmitter.java:141)
	at io.smallrye.reactive.messaging.providers.extension.ThrowingEmitter.emit(ThrowingEmitter.java:63)
	at io.smallrye.reactive.messaging.providers.extension.AbstractEmitter.emit(AbstractEmitter.java:164)
	at io.smallrye.reactive.messaging.providers.extension.EmitterImpl.send(EmitterImpl.java:31)
```

**Comment by nagin** [comment]
Java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

uname -a 
Linux rmd1 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by geoand** [comment]
Any chance you can provide a sample application that exhibits the behavior you mention?

Thanks

**Comment by ozangunalp** [comment]
I can imagine that it may happen on a dev mode hot reload, but is it systematic?

**Comment by nagin** [comment]
This happens in dev mode only and not in Production.

**Comment by bhdrk** [comment]
I have same issue. it still exists in latest version of Quarkus (3.3.1). I solved with "-Dmutiny.disableCallBackDecorators=true". This system parameter disables the callback decoration.
