### ISSUE TITLE
Panache project() is not working if used with distinct + case-sensitive HQL query

### ISSUE THREAD

**Issue by jasminsuljic** [quarkusio/quarkus#29089]
### Describe the bug

For an entity that has getter defined with camelCase attribute name ie: `myId` executing query:
```java
Data.find("SELECT DISTINCT d.myId FROM Data d", Sort.by("myId"))
        .project(Long.class)
        .list();
```
will result in:
```
Caused by: java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: myid of: de.turing85.panache.projection.entity.Data [select distinct new java.lang.Long(d.myid) FROM de.turing85.panache.projection.entity.Data d ORDER BY myId]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:138)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:757)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:114)
        at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.createQuery(TransactionScopedSession.java:349)
        at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:547)
```
The issue is probably here: https://github.com/quarkusio/quarkus/blob/8e4ee686b538e8cb7cbb402ef084ef0925fb83cf/extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java#L104

### Expected behavior

Distinct query should work with HQL compliant query.

### Actual behavior

It does not work, an exception is raised.

```
Caused by: java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: myid of: de.turing85.panache.projection.entity.Data [select distinct new java.lang.Long(d.myid) FROM de.turing85.panache.projection.entity.Data d ORDER BY myId]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:138)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:757)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:114)
        at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.createQuery(TransactionScopedSession.java:349)
        at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:547)
```

### How to Reproduce?

https://github.com/turing85/quarkus-panache-projection/tree/reanme-id-to-myId

Check this line: https://github.com/turing85/quarkus-panache-projection/blob/reanme-id-to-myId/src/main/java/de/turing85/panache/projection/DataResource.java#L36

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000

### Output of `java -version`

openjdk version "19" 2022-09-20 OpenJDK Runtime Environment Homebrew (build 19) OpenJDK 64-Bit Server VM Homebrew (build 19, mixed mode, sharing)

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /Users/jasminsuljic/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 19, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/19/libexec/openjdk.jdk/Contents/Home Default locale: en_GB, platform encoding: UTF-8 OS name: "mac os x", version: "12.6", arch: "x86_64", family: "mac"

**Comment by DavideD** [comment]
I will have a look.
