### ISSUE TITLE
Provider io.fabric8.knative.client.KnativeExtensionAdapter not found

### ISSUE THREAD

**Issue by spolti** [quarkusio/quarkus#29096]
### Describe the bug

Native binary fails to start when using the `quarkus-kubernetes-client` with `knative-client`.

### Expected behavior

start without issues.

### Actual behavior

```
ERROR: Failed to start application (with profile prod)
java.util.ServiceConfigurationError: io.fabric8.kubernetes.client.extension.ExtensionAdapter: Provider io.fabric8.knative.client.KnativeExtensionAdapter not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:114)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.fabric8.kubernetes.client.impl.Adapters.discoverServices(Adapters.java:106)
	at io.fabric8.kubernetes.client.impl.Adapters.<init>(Adapters.java:51)
	at io.fabric8.kubernetes.client.impl.BaseClient.<init>(BaseClient.java:102)
	at io.fabric8.kubernetes.client.impl.KubernetesClientImpl.<init>(KubernetesClientImpl.java:191)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:79)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:98)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:60)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:56)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:48)
	at org.kie.kogito.addons.quarkus.k8s.KubeDiscoveryConfigSourceInterceptor.<init>(KubeDiscoveryConfigSourceInterceptor.java:42)
	at org.kie.kogito.addons.quarkus.k8s.config.ServiceDiscoveryConfigBuilder.configBuilder(ServiceDiscoveryConfigBuilder.java:27)
	at io.quarkus.runtime.configuration.ConfigUtils.configBuilder(ConfigUtils.java:197)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:122)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### How to Reproduce?

Reproducer:

Steps:

1. create a new Quarkus app.
2. make sure that the `quarkus.platform.version` is 2.14.0.CR1
3. add the following dependencies: 
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-kubernetes-client</artifactId>
    </dependency>
        <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>knative-client</artifactId>
    </dependency>
```
4. update the `GreetingResource` class with some usage of the knative client, e.g.:
```
        knativeClient = new DefaultKnativeClient();
        knativeClient.adapt(KnativeClient.class);
```
5. access the hello endpoint.

### Output of `uname -a` or `ver`

OS name: "linux", version: "5.19.12-200.fc36.x86_64", arch: "amd64", family: "unix"

### Quarkus version or git rev

2.14.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.6

**Comment by geoand** [comment]
Thanks for reporting!

https://github.com/quarkusio/quarkus/pull/29100 should take care of it

**Comment by spolti** [comment]
Thanks for the quick fix @geoand.

**Comment by geoand** [comment]
YW!
