### ISSUE TITLE
Quarkus upgrade from 2.11.3 to 2.14.0 fails due to resteasy reactive (kotlin)

### ISSUE THREAD

**Issue by AhmetTurner** [quarkusio/quarkus#29221]
### Describe the bug

Im using Kotlin + Quarkus 2.11.3 and wanted to migrate to the platform version 2.14.0.
Before the migration everything worked except for the **"`hot reload`"** _dev feature_ of Quarkus.
I hoped to fix it magically with the upgrade :smile: 

Dependencies that I changed are:

Updated: 
* **quarkus-resteasy-reactive-kotlin** to **quarkus-resteasy-reactive** (Looked like the extensions have been added to the main package)

Added:
* quarkus-resteasy-reactive-kotlin-serialization
* quarkus-rest-client-reactive-kotlin-serialization
 

### Expected behavior

The upgrade works and hopefully the **_hot reload_** starts working again.

### Actual behavior

I'm getting an infinitly repeated error log:

```
DEBUG [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-1) Restarting handler chain for exception exception: javax.ws.rs.NotFoundException: Unable to find matching target resource method
	at org.jboss.resteasy.reactive.server.handlers.ClassRoutingHandler.throwNotFound(ClassRoutingHandler.java:223)
	at org.jboss.resteasy.reactive.server.handlers.ClassRoutingHandler.handle(ClassRoutingHandler.java:101)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:96)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:204)
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:250)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$12.handle(ResteasyReactiveRecorder.java:328)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$12.handle(ResteasyReactiveRecorder.java:321)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.handle(VertxHttpHotReplacementSetup.java:196)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.handle(VertxHttpHotReplacementSetup.java:185)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

### How to Reproduce?

See comment below

### Additional information

**_VertxHttpHotReplacementSetup_** could be a lead to the already broken `hot reload` dev feature but I don't know how it's connected

**Comment by geoand** [comment]
This is interesting...

Do you have a sample application that I could look at that exhibits the aforementioned behavior?

**Comment by AhmetTurner** [comment]
I can't explain my frustration but I think I found the problem...

After downloading a newly created project and copying my code peu à peu it looked like everything worked.
Until I copied the resources directory. It seems like the problem was the **_port_** specification in the **application.yml**.
When setting it to 9000 (my initial used port number) the exception started to occur. 
When switching to 9001 everything works fine.

Is there any explanation for this behaviour?

[reproducer-project.zip](https://github.com/quarkusio/quarkus/files/9995164/reproducer-project.zip)

**Comment by AhmetTurner** [comment]
Update: It still happens once when requesting a GET endpoint with invalidating cache (CTRL + SHIFT + R on Chromium) through the browser. It maybe is related to the missing **favicon.ico** which is requested initially

**Comment by geoand** [comment]
I tried your sample and everything works fine. Perhaps you have some other process running on port `9000` on your machine

**Comment by AhmetTurner** [comment]
> I tried your sample and everything works fine. Perhaps you have some other process running on port `9000` on your machine

Yep, I thought so as well. But the weird thing is that the **lsof** command didn't return anything. Furthermore, downgrading quarkus and trying it again worked fine.

Well I don't know what happened there, I'm just happy that it works on another port now. Anyway, thx for your time!

**Comment by geoand** [comment]
🙏🏼
