### ISSUE TITLE
Native Image build fails with Jackson >2.14.0

### ISSUE THREAD

**Issue by vincejv** [quarkusio/quarkus#29222]
### Describe the bug

Quarkus fails to build native image if jackson is upgraded to `2.14.0`, affects both Quarkus `2.13.x` and `2.14.x` (as per my testing), not sure if GraalVM related or Quarkus issue, but see the logs and reproducer below

Sample quarkus github project, it should only contain files/modifications from code.quarkus.io + Jackson 2.14.0 + CI stuff https://github.com/vincejv/playground

No issues with JVM build, only native image

Last known Jackson version to work without issues:  `2.13.4.2`

### Expected behavior

No errors should occur during building native image and should generate a native binary

### Actual behavior

Native Image build fails with the following error and does not finish compilation
```java
[2/7] Performing analysis...  []                                                                        (23.8s @ 1.39GB)
   3,866 (84.08%) of  4,598 classes reachable
   4,628 (52.93%) of  8,743 fields reachable
  15,543 (76.36%) of 20,355 methods reachable
     273 classes,     0 fields, and     0 methods registered for reflection

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findSubtypes(com.fasterxml.jackson.databind.introspect.Annotated) 
Parsing context:
   at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findSubtypes(JacksonAnnotationIntrospector.java:621)
   at com.fasterxml.jackson.databind.jsontype.impl.StdSubtypeResolver._collectAndResolveByTypeId(StdSubtypeResolver.java:296)
   at com.fasterxml.jackson.databind.jsontype.impl.StdSubtypeResolver.collectAndResolveSubtypesByTypeId(StdSubtypeResolver.java:212)
   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findTypeDeserializer(BasicDeserializerFactory.java:1793)
   at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:654)
   at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:2430)
   at com.fasterxml.jackson.databind.ObjectReader.<init>(ObjectReader.java:194)
   at com.fasterxml.jackson.databind.ObjectReader.<init>(ObjectReader.java:173)

	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:109)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:562)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:488)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
```

### How to Reproduce?

Steps to reproduce

1. Generate a vanilla Quarkus project from [code.quarkus.io](https://code.quarkus.io/)
2. Add the following jackson dependencies
```xml
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
</dependency>
<dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-databind</artifactId>
  <version>2.14.0</version>
</dependency>
<dependency>
  <groupId>com.fasterxml.jackson.datatype</groupId>
  <artifactId>jackson-datatype-jsr310</artifactId>
  <version>2.14.0</version>
</dependency>
```
3. Build with `mvn -B package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:22.3-java17`
4. Build failure

### Output of `uname -a` or `ver`

Github actions linux

### Output of `java -version`

17.0.5+8

### GraalVM version (if different from Java)

22.3. also reproducible with 22.2

### Quarkus version or git rev

2.14.0, but also affects 2.13 and earlier versions

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

### Additional information

See full Github actions run log here: https://github.com/vincejv/playground/actions/runs/3448179031/jobs/5754948784

**Comment by vincejv** [comment]
Closing the issue, turns out the correct way of upgrading jackson involves modifying the version defined by `jackson-bom.version` in `properties` by adding this in in pom file like so

```xml
<properties>
  <jackson-bom.version>2.14.0</jackson-bom.version>
</properties>
```
