### ISSUE TITLE
AWS APIGatewayManagementAPI - Native image build failure Random/SplittableRandom GraalVM

### ISSUE THREAD

**Issue by villain-bryan** [quarkusio/quarkus#29243]
### Describe the bug

I'm trying to bridge a couple of AWS services together and having some trouble. I'm using API Gateway WebSockets and would like to "use" or "access" my WebSocket [connections](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-how-to-call-websocket-api-connections.html) in my Quarkus Funky Lambda using [APIGatewayManagementAPI](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/apigatewaymanagementapi/AmazonApiGatewayManagementApiClient.html). I don't know if there is support for this AWS functionality or if I'm missing something .. API Gateway is pretty commonly used. 

I'd like to be able to [send data](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/apigatewaymanagementapi/model/PostToConnectionRequest.html) to any WebSocket connection (or [DeleteConnectionRequest](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/apigatewaymanagementapi/model/DeleteConnectionRequest.html)), using the aws-lambda-java APIGatewayV2WebSocketEvent [connectionId](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2WebSocketEvent.java#L229). To achieve this in Java I was able to locate the aws-java-sdk-apigatewaymanagementapi dependency .. and unfortunately I've run into build-native.

**Code I'd like to use**
```
@Funq
public APIGatewayProxyResponseEvent handle(APIGatewayV2WebSocketEvent input) {
	// Grab the connectionId from the WebSocket event
	System.out.println("ConnectionID: " + input.getRequestContext().getConnectionId()); // Working

	// Try accessing the WebSocket Connection via AmazonAPIGatewayAPI 
	// and try to post data to this particular Connection
	// in the future, there may be other Connections that need to be "managed" here 
	// with connectionIds maintained in  DynamoDB 
	AmazonApiGatewayManagementApi api = AmazonApiGatewayManagementApiClientBuilder.standard().withEndpointConfiguration( new EndpointConfiguration("{api-id}.execute-api.{region}.amazonaws.com/{stage}", "{region}") ).build();
	PostToConnectionRequest post = new PostToConnectionRequest(); 
	post.setConnectionId(input.getRequestContext().getConnectionId()); 
	post.setData(ByteBuffer.wrap("the message".getBytes())); 
	api.postToConnection(post); // Calling this method crashes causes build-natives fails
}
```

**The AWS dependency I'd like to use**
```
<dependency>
    	<groupId>com.amazonaws</groupId>
    	<artifactId>aws-java-sdk-apigatewaymanagementapi</artifactId>
    	<version>1.12.341</version>
</dependency>
```

**Nasty errors!**
```
Error: Unsupported features in 3 methods
Detailed message:
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.amazonaws.ClientConfiguration class initializer with a trace:
        at java.util.Random.<init>(Random.java:109)
        at com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy.<init>(PredefinedBackoffStrategies.java:101)
        at com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.<init>(PredefinedBackoffStrategies.java:150)
        at com.amazonaws.retry.PredefinedRetryPolicies.<clinit>(PredefinedRetryPolicies.java:82)
        at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:89)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy.random of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy@154a1d7a: com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy@154a1...
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.equalJitterBackoffStrategy of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71...
  scanning root com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71... embedded in
    com.amazonaws.retry.PredefinedRetryPolicies.getDefaultBackoffStrategy(PredefinedRetryPolicies.java:110)
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.amazonaws.ClientConfiguration class initializer with a trace:
        at java.util.Random.<init>(Random.java:109)
        at com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.<init>(PredefinedBackoffStrategies.java:75)
        at com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.<init>(PredefinedBackoffStrategies.java:148)
        at com.amazonaws.retry.PredefinedRetryPolicies.<clinit>(PredefinedRetryPolicies.java:82)
        at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:89)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.random of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@2cb3cd33: com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@2cb3cd...
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.fullJitterBackoffStrategy of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71...
  scanning root com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71... embedded in
    com.amazonaws.retry.PredefinedRetryPolicies.getDefaultBackoffStrategy(PredefinedRetryPolicies.java:110)
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.amazonaws.retry.PredefinedBackoffStrategies class initializer with a trace:
        at java.util.Random.<init>(Random.java:109)
        at com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.<init>(PredefinedBackoffStrategies.java:75)
        at com.amazonaws.retry.PredefinedBackoffStrategies.<clinit>(PredefinedBackoffStrategies.java:64)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.random of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f68: com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f...
  scanning root com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f68: com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f... embedded in
    com.amazonaws.retry.PredefinedRetryPolicies.getDefaultBackoffStrategy(PredefinedRetryPolicies.java:113)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 3 methods
Detailed message:
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.amazonaws.ClientConfiguration class initializer with a trace:
        at java.util.Random.<init>(Random.java:109)
        at com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy.<init>(PredefinedBackoffStrategies.java:101)
        at com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.<init>(PredefinedBackoffStrategies.java:150)
        at com.amazonaws.retry.PredefinedRetryPolicies.<clinit>(PredefinedRetryPolicies.java:82)
        at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:89)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy.random of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy@154a1d7a: com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy@154a1...
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.equalJitterBackoffStrategy of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71...
  scanning root com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71... embedded in
    com.amazonaws.retry.PredefinedRetryPolicies.getDefaultBackoffStrategy(PredefinedRetryPolicies.java:110)
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.amazonaws.ClientConfiguration class initializer with a trace:
        at java.util.Random.<init>(Random.java:109)
        at com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.<init>(PredefinedBackoffStrategies.java:75)
        at com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.<init>(PredefinedBackoffStrategies.java:148)
        at com.amazonaws.retry.PredefinedRetryPolicies.<clinit>(PredefinedRetryPolicies.java:82)
        at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:89)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.random of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@2cb3cd33: com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@2cb3cd...
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.fullJitterBackoffStrategy of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71...
  scanning root com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71... embedded in
    com.amazonaws.retry.PredefinedRetryPolicies.getDefaultBackoffStrategy(PredefinedRetryPolicies.java:110)
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.amazonaws.retry.PredefinedBackoffStrategies class initializer with a trace:
        at java.util.Random.<init>(Random.java:109)
        at com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.<init>(PredefinedBackoffStrategies.java:75)
        at com.amazonaws.retry.PredefinedBackoffStrategies.<clinit>(PredefinedBackoffStrategies.java:64)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.random of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f68: com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f...
  scanning root com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f68: com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f... embedded in
    com.amazonaws.retry.PredefinedRetryPolicies.getDefaultBackoffStrategy(PredefinedRetryPolicies.java:113)

        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:776)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 3 methods
Detailed message:
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.amazonaws.ClientConfiguration class initializer with a trace:
        at java.util.Random.<init>(Random.java:109)
        at com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy.<init>(PredefinedBackoffStrategies.java:101)
        at com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.<init>(PredefinedBackoffStrategies.java:150)
        at com.amazonaws.retry.PredefinedRetryPolicies.<clinit>(PredefinedRetryPolicies.java:82)
        at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:89)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy.random of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy@154a1d7a: com.amazonaws.retry.PredefinedBackoffStrategies$EqualJitterBackoffStrategy@154a1...
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.equalJitterBackoffStrategy of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71...
  scanning root com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71... embedded in
    com.amazonaws.retry.PredefinedRetryPolicies.getDefaultBackoffStrategy(PredefinedRetryPolicies.java:110)
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.amazonaws.ClientConfiguration class initializer with a trace:
        at java.util.Random.<init>(Random.java:109)
        at com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.<init>(PredefinedBackoffStrategies.java:75)
        at com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.<init>(PredefinedBackoffStrategies.java:148)
        at com.amazonaws.retry.PredefinedRetryPolicies.<clinit>(PredefinedRetryPolicies.java:82)
        at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:89)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.random of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@2cb3cd33: com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@2cb3cd...
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy.fullJitterBackoffStrategy of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71...
  scanning root com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c719c: com.amazonaws.retry.PredefinedBackoffStrategies$SDKDefaultBackoffStrategy@328c71... embedded in
    com.amazonaws.retry.PredefinedRetryPolicies.getDefaultBackoffStrategy(PredefinedRetryPolicies.java:110)
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.amazonaws.retry.PredefinedBackoffStrategies class initializer with a trace:
        at java.util.Random.<init>(Random.java:109)
        at com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.<init>(PredefinedBackoffStrategies.java:75)
        at com.amazonaws.retry.PredefinedBackoffStrategies.<clinit>(PredefinedBackoffStrategies.java:64)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy.random of constant
    com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f68: com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f...
  scanning root com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f68: com.amazonaws.retry.PredefinedBackoffStrategies$FullJitterBackoffStrategy@3abb2f... embedded in
    com.amazonaws.retry.PredefinedRetryPolicies.getDefaultBackoffStrategy(PredefinedRetryPolicies.java:113)

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:771)
        ... 5 more
```

I've been trying to debug this and have messed around with some additional args: 
`quarkus.native.additional-build-args=--initialize-at-run-time=org.apache.http.impl.auth.NTLMEngineImpl, --trace-object-instantiation=java.util.Random
`

I also inspected the `aws-java-sdk-apigatewaymanagementapi` artifact and detected potential problems with the `joda-time` artifact, and have excluded it from my pom.xml in an attempt to get this compiled.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.2251]

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### Quarkus version or git rev

<quarkus.platform.version>2.14.0.Final</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: C:\Users\Bry\.m2\wrapper\dists\apache-maven-3.8.6-bin\67568434\apache-maven-3.8.6 Java version: 17.0.5, vendor: GraalVM Community, runtime: C:\Program Files (x86)\Java\jdks\graalvm-ce-java17-22.3.0 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by zakkak** [comment]
Closing as it looks like something that should be resolved in https://github.com/quarkiverse/quarkus-amazon-services and is already being tracked there in https://github.com/quarkiverse/quarkus-amazon-services/issues/374
