### ISSUE TITLE
Do not require a default datasource definition if TenantConnectionResolver is implemented

### ISSUE THREAD

**Issue by alexkolson** [quarkusio/quarkus#29269]
### Description

Hi there,

Would it be possible / an okay idea to not require a default datasource definition if multi-tenancy / programmatic datasource configuration is used? I'm not sure how at all this would be implemented, but from a developer experience point-of-view, this would be nice. No having to define extra non-used properties in application.properties hanging around just to avoid errors when the application tries to start.

### Implementation ideas

Perhaps a sort of escape hatch, where if an implementation of TenantConnectionResolver is detected in the CDI container, a message is logged letting the developer know that they are now on their own for validating their configuration and that quarkus will not check to make sure a datasource is configured before starting.

**Comment by gsmet** [comment]
Which errors do you get exactly? Could you share a small Maven project showing the problem you have?

Thanks!

**Comment by sberyozkin** [comment]
Not sure it is relevant, in `quarkus-oidc` we have a `tenant-enabled` property to disable the default properties (tenant), or other tenant if needed, so in a multi-tenant setup the users only do `quarkus.oidc.tenant-enabled=false` for OIDC to avoid dealing with the main/default properties. I'm thinking of making sure to have `quarkus.oidc.tenant-enabled=false` not be even necessary as OIDC will retry to reconnect at the first request time if the connection failed at the start up - which would fail again for the default tenant, but the tenant resolvers will be there to provide the right tenant config...

**Comment by alexkolson** [comment]
Hi @gsmet! Thank you for responding! [Here is a reproducer](https://github.com/alexkolson/quarkus-no-default-datasource-reproducer) for you, as requested.

@sberyozkin This definitely sounds related! Perhaps the multi-tenancy feature for hibernate could do something similar?

**Comment by svanschooten** [comment]
Any updates here? I am running into the same issue of needing a default datasource even when I specify I want to use multi-tenant mode. Also implemented the `TenantConnectionResolver` and `TenantResolver` so those should supply a proper datasource right?

**Comment by yrodiere** [comment]
> Any updates here? I am running into the same issue of needing a default datasource even when I specify I want to use multi-tenant mode. Also implemented the `TenantConnectionResolver` and `TenantResolver` so those should supply a proper connection right?

Sorry, I've been meaning to reply for a while, but still didn't find the time to look more closely into this...

Out of the top of my head, if there's no datasource, you need to specify the dialect explicitly, so maybe check you're doing that?

Otherwise yes, there's probably a bug somewhere, and we need to dig more.

**Comment by yrodiere** [comment]
Checking with Quarkus 3.24, we still have a problem, but it shows up differently:

```
2025-06-30 14:03:22,011 ERROR [io.qua.run.Application] (main) Failed to start application: java.lang.RuntimeException: Failed to start quarkus                                                                                                                          
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)                                                                
        at io.quarkus.runtime.Application.start(Application.java:101)                                                               
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)                                 
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:80)                                                                          
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:51)                                                                          
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:144)                                                                         
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)                                                                     
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:68)                                           
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:36)                                            
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Unable to find datasource '<default>' for persistence unit '<default>': Bean is not active: SYNTHETIC bean [class=io.agroal.api.AgroalDataSource, id=sqqLi56D50iCdXmOjyjPSAxbLu0]                   
Reason: Datasource '<default>' was deactivated automatically because its URL is not set. To activate the datasource, set configuration property 'quarkus.datasource.jdbc.url'. Refer to https://quarkus.io/guides/datasource for guidance.                              
To avoid this exception while keeping the bean inactive:                                                                            
        - Configure all extensions consuming this bean as inactive as well, if they allow it, e.g. 'quarkus.someextension.active=false'                                                                                                                                 
        - Make sure that custom code only accesses this bean if it is active                                                        
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitUtil.unableToFindDataSource(PersistenceUnitUtil.java:115)                
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.injectDataSource(FastBootHibernatePersistenceProvider.java:412)                                                                                                                        
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.buildRuntimeSettings(FastBootHibernatePersistenceProvider.java:224)                                                                                                                    
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(FastBootHibernatePersistenceProvider.java:194)                                                                                                    
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:67)                                                                                                               
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:90)                                          
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:66)                                          
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:163)                                   
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:63)                                                      
        at java.base/java.lang.Thread.run(Thread.java:840)                                                                          
Caused by: io.quarkus.arc.InactiveBeanException: Bean is not active: SYNTHETIC bean [class=io.agroal.api.AgroalDataSource, id=sqqLi56D50iCdXmOjyjPSAxbLu0]                                                                                                              
Reason: Datasource '<default>' was deactivated automatically because its URL is not set. To activate the datasource, set configuration property 'quarkus.datasource.jdbc.url'. Refer to https://quarkus.io/guides/datasource for guidance.                              
To avoid this exception while keeping the bean inactive:                                                                            
        - Configure all extensions consuming this bean as inactive as well, if they allow it, e.g. 'quarkus.someextension.active=false'                                                                                                                                 
        - Make sure that custom code only accesses this bean if it is active                                                        
        at io.agroal.api.AgroalDataSource_sqqLi56D50iCdXmOjyjPSAxbLu0_Synthetic_Bean.doCreate(Unknown Source)                       
        at io.agroal.api.AgroalDataSource_sqqLi56D50iCdXmOjyjPSAxbLu0_Synthetic_Bean.create(Unknown Source)                         
        at io.agroal.api.AgroalDataSource_sqqLi56D50iCdXmOjyjPSAxbLu0_Synthetic_Bean.create(Unknown Source)                         
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)                           
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)                                           
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)                                           
        at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c10(Unknown Source)       
        at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)                                                                                                                               
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)                                             
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:23)                                    
        at io.agroal.api.AgroalDataSource_sqqLi56D50iCdXmOjyjPSAxbLu0_Synthetic_ClientProxy.arc$delegate(Unknown Source)            
        at io.agroal.api.AgroalDataSource_sqqLi56D50iCdXmOjyjPSAxbLu0_Synthetic_ClientProxy.arc_contextualInstance(Unknown Source)  
        at io.quarkus.arc.ClientProxy.unwrap(ClientProxy.java:52)                                                                   
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.injectDataSource(FastBootHibernatePersistenceProvider.java:410)                                                                                                                        
        ... 8 more                                                                                                                  
```

**Comment by GeorgeDanicico** [comment]
Hi guys, when will this fix be released? We still see this issue when using the latest quarkus version, 3.24.5.

**Comment by yrodiere** [comment]
Hi.

This tells you the fix is in 3.25:

<img width="726" height="78" alt="Image" src="https://github.com/user-attachments/assets/bfdbe05b-20ff-4560-8926-a27ae4d46d58" />

The [release planning](https://github.com/quarkusio/quarkus/wiki/Release-Planning#325-proposal) tells you when 3.25 will be released:

> ## 3.25 (Proposal)
> Core CR1 on July 16th
> Core Final on July 23th
> Full Platform release (and official announcement) on July 30th
