### ISSUE TITLE
io.vertx.core.eventbus.EventBus cannot decode List<Long> payload (???)

### ISSUE THREAD

**Issue by syr** [quarkusio/quarkus#29436]
### Describe the bug

I do something like

`eventBus.send("myBusAddress", List.of(1L,2L));`

and having a consumer method like 
```
@ConsumeEvent(BUS_ADDRESS_RETRY)
    public void doAsync(List<Long> longList) {
    ...
    }
```

### Expected behavior

Was hoping this would just work, meaning that in doAsync the longList = [1L,2L]

### Actual behavior

Instead I get
```
2022-11-23 10:00:25,967 ERROR job=[] traceId=[] spanId=[] [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile local): java.lang.ClassNotFoundException: java.util.List<java.lang.Long>
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:459)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:450)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:459)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:450)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at io.quarkus.deployment.steps.VertxProcessor$build609260703.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.VertxProcessor$build609260703.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:122)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Quarkus version or git rev

2.13.3.Final

### Additional information

When trying to use latest quarkus version 2.14.1.Final breaks my project build with

cannot find symbol
  symbol:   class OkHttpClient
package okhttp3 does not exist

Think that's another issue I have to create when I dont get this fixed on my own-

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
I believe that this problem is fixed with https://github.com/quarkusio/quarkus/pull/29446. And I wasn't able to reproduce the issue in the main branch.

The fix targets 2.14.2.Final and should be backported in 2.13 as well. 

Unfortunately, I'm not aware of any workaround; maybe just try use a raw type instead of `List<Integer>` in the consuming method?

**Comment by mkouba** [comment]
However, I'm not quite sure how does the Vert.x event bus handle generic types in the sense that the type is not considered during delivery of the event and e.g. if you send `List<Integer>` and the consumer receives `List<String>` then you may get a `ClassCastException`...

**Comment by cescoffier** [comment]
Yes, the types must match.

**Comment by Ladicek** [comment]
> I believe that this problem is fixed with #29446.

Agree, given the error message says `java.lang.ClassNotFoundException: java.util.List<java.lang.Long>`, which just points to `Type.toString()` again.

**Comment by syr** [comment]
sd

> I believe that this problem is fixed with #29446. And I wasn't able to reproduce the issue in the main branch.
> 
> The fix targets 2.14.2.Final and should be backported in 2.13 as well.
> 
> Unfortunately, I'm not aware of any workaround; maybe just try use a raw type instead of `List<Integer>` in the consuming method?

Can confirm that the issue is fixed with 2.14.2.Final. :)

**Comment by geoand** [comment]
> which just points to Type.toString() again

How about we ban it? This can come to bite us again and again, so I think we should ban it in a some of the core modules, WDYT?

**Comment by Ladicek** [comment]
That makes sense to me -- `Type.toString()` has always been usable only for human-readable string representation.

**Comment by mkouba** [comment]
> How about we ban it? 

How do we do that?

**Comment by geoand** [comment]
I'll open a PR soon :)

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus/blob/main/core/deployment/pom.xml#L199-L220 .

**Comment by geoand** [comment]
You spoiled the surprise 😆

**Comment by geoand** [comment]
LOL, see https://github.com/quarkusio/quarkus/pull/29551

**Comment by mkouba** [comment]
Interesting...
