### ISSUE TITLE
SimpleSpanProcessor support in OTel

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#29448]
### Description

We need to support SimpleSpanProcessor in OTel, in order to allow lambda functions on cloud providers to report, in time their traces. 
See #26250 

### Implementation ideas

This should be trivial after the OTel SPI access is available after the #26444 work is finished.
Should be a mater of documenting the procedure.

**Comment by geoand** [comment]
Is this still relevant?

**Comment by brunobat** [comment]
Very... Especially for lambda functions.

**Comment by brunobat** [comment]
Assigning to @alesj

**Comment by brunobat** [comment]
@arik-dig has this problem on tests that use openTelemetry. The test closes before the export finishes and throws an exception.

**Comment by arik-dig** [comment]
when working with version 3.4.1 seeing the following warning:

```
19:57:32 WARNING traceId=, parentId=, spanId=, sampled= [io.op.sd.tr.ex.BatchSpanProcessor] (BatchSpanProcessor_WorkerThread-1) Exporter threw an Exception: java.lang.IllegalStateException: Client is closed
	at io.vertx.core.http.impl.HttpClientImpl.checkClosed(HttpClientImpl.java:696)
	at io.vertx.core.http.impl.HttpClientImpl.doRequest(HttpClientImpl.java:597)
	at io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:465)
	at io.vertx.grpc.client.impl.GrpcClientImpl.request(GrpcClientImpl.java:50)
	at io.quarkus.opentelemetry.runtime.exporter.otlp.VertxGrpcExporter.export(VertxGrpcExporter.java:91)
	at io.quarkus.opentelemetry.runtime.exporter.otlp.VertxGrpcExporter.export(VertxGrpcExporter.java:128)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.exportCurrentBatch(BatchSpanProcessor.java:326)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.flush(BatchSpanProcessor.java:271)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.run(BatchSpanProcessor.java:238)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

as @brunobat mentioned when using the configs:

```
quarkus.otel.bsp.max.export.batch.size=1
quarkus.otel.bsp.schedule.delay=0.001S
```

it reduces the frequency of it happening, but its inconsistent.

**Comment by brunobat** [comment]
This has been implemented here: https://github.com/quarkusio/quarkus/pull/43983
