### ISSUE TITLE
Quartz startup error before full application initialization

### ISSUE THREAD

**Issue by LazaroR94** [quarkusio/quarkus#29455]
### Describe the bug

Hello all! I've currently been testing out Quartz for Quarkus and have come to an error whenever the application starts. It seems as though Quartz starts too prematurely and does not let the application fully start before initializing its scheduled methods. I am using Kafka in my application and the emitters unfortunately do not get immediately injected and thus prompt a quick Quartz error:
`ERROR [io.qua.sch.com.run.StatusEmitterInvoker] (vert.x-worker-thread-2) Error occurred while executing task for trigger io.quarkus.quartz.runtime.QuartzSchedulerImpl$QuartzTrigger@286b1223: java.util.concurrent.CompletionException: javax.enterprise.inject.spi.DefinitionException: SRMSG00019: Unable to connect an emitter with the channel "my-kafka-channel"`

Is there a way to configure this startup behavior? I have tried a couple of configurations from the Quarkus Quartz documentation to no avail (i.e. `quartz.start-mode`, `@Scheduled(delay = X)`, etc.).

### Expected behavior

Quartz should start after full application initialization in order to let other dependencies load.

### Actual behavior

Quartz starts before any other dependencies load and therefore causes an error to output (in my case, with Kafka).

### How to Reproduce?

1. Create a new Quarkus application with Quartz + Smallrye Kafka
2. Leave default values for Quartz
3. Create a @Scheduled method for job execution
4. Create a simple consumer/producer for Kafka
5. Start the application and observe the error before Kafka channels get registered

### Output of `uname -a` or `ver`

Darwin C02FW4DDMD6R 20.6.0 Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "11.0.12" 2021-07-20 LTS

### Quarkus version or git rev

2.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

Additional stacktrace:
```
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at java.base/java.util.concurrent.CompletableFuture$MinimalStage.whenComplete(CompletableFuture.java:2820)
	at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:24)
	at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
	at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
	at io.quarkus.quartz.runtime.QuartzSchedulerImpl$InvokerJob$1.handle(QuartzSchedulerImpl.java:625)
	at io.quarkus.quartz.runtime.QuartzSchedulerImpl$InvokerJob$1.handle(QuartzSchedulerImpl.java:621)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.enterprise.inject.spi.DefinitionException: SRMSG00019: Unable to connect an emitter with the channel `my-kafka-channel`
	at io.smallrye.reactive.messaging.providers.extension.ChannelProducer.getEmitter(ChannelProducer.java:187)
	at io.smallrye.reactive.messaging.providers.extension.ChannelProducer.produceMutinyEmitter(ChannelProducer.java:150)
	at io.smallrye.reactive.messaging.providers.extension.ChannelProducer_ProducerMethod_produceMutinyEmitter_61fbcd4df05bcbbbf61e88984db5879a6c6178b1_Bean.create(Unknown Source)
	at io.smallrye.reactive.messaging.providers.extension.ChannelProducer_ProducerMethod_produceMutinyEmitter_61fbcd4df05bcbbbf61e88984db5879a6c6178b1_Bean.get(Unknown Source)
	at io.smallrye.reactive.messaging.providers.extension.ChannelProducer_ProducerMethod_produceMutinyEmitter_61fbcd4df05bcbbbf61e88984db5879a6c6178b1_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:62)
	at config.AppConfig_Bean.create(Unknown Source)
	at config.AppConfig_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at config.AppConfig_ClientProxy.arc$delegate(Unknown Source)
	at config.AppConfig_ClientProxy.arc_contextualInstance(Unknown Source)
	at config.AppConfig_ProducerMethod_caseTrackingRepository_f8a85e2d8b8b7ea2753f823c3e5b5cc0694b83e0_Bean.create(Unknown Source)
	at config.AppConfig_ProducerMethod_caseTrackingRepository_f8a85e2d8b8b7ea2753f823c3e5b5cc0694b83e0_Bean.get(Unknown Source)
	at config.AppConfig_ProducerMethod_caseTrackingRepository_f8a85e2d8b8b7ea2753f823c3e5b5cc0694b83e0_Bean.get(Unknown Source)
	at infrastructure.scheduler.BatchRetryTask_Bean.create(Unknown Source)
	at infrastructure.scheduler.BatchRetryTask_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at infrastructure.scheduler.BatchRetryTask_Bean.get(Unknown Source)
	at infrastructure.scheduler.BatchRetryTask_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:476)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:489)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:287)
	at infrastructure.scheduler.BatchRetryTask_ScheduledInvoker_retryFailedEvents_29bc7bcb738f29944cea1d7529664810d1c8f1a7.invokeBean(Unknown Source)
```

**Comment by machi1990** [comment]
Hi @LazaroR94 can you share a simple producer project with the complete setup?

**Comment by mkouba** [comment]
You can try to skip executions via [`Scheduled#skipExecutionIf()`](https://quarkus.io/guides/scheduler-reference#conditional_execution) until the Kafka channels are ready. The problem here is that _"full application initialization"_ is not well-defined. Internally, both `quarkus-scheduler` and `quarkus-quartz` start the scheduler when the `StartupEvent` is fired. But Kafka channels are probaly initialized afterwards.

CC @cescoffier

**Comment by LazaroR94** [comment]
> Hi @LazaroR94 can you share a simple producer project with the complete setup?

I will try to get a simple reproducer out when I get some time.

> You can try to skip executions via [`Scheduled#skipExecutionIf()`](https://quarkus.io/guides/scheduler-reference#conditional_execution) until the Kafka channels are ready. The problem here is that _"full application initialization"_ is not well-defined. Internally, both `quarkus-scheduler` and `quarkus-quartz` start the scheduler when the `StartupEvent` is fired. But Kafka channels are probaly initialized afterwards.
> 
> CC @cescoffier

Do you have an example of how to use `skipExecutionIf()`? From what I read, it seems that it also observes the StartupEvent but maybe even then it's not sufficient as like you said, the channels are initialized afterwards.

**Comment by mkouba** [comment]
> Do you have an example of how to use `skipExecutionIf()`? 

There's a link to the docs in my preview comment...?

> From what I read, it seems that it also observes the StartupEvent but maybe even then it's not sufficient as like you said, the channels are initialized afterwards.

You're talking about `io.quarkus.scheduler.Scheduled.ApplicationNotRunning`, right? But you can provide your own implementation, i.e. a bean that implements `SkipPredicate`, and skip the execution as needed.

**Comment by LazaroR94** [comment]
> 

Sorry, I should have rephrased my question (_Do you have an example of how to use skipExecutionIf()?_) as I already did read the link that you posted prior to creating this issue ticket. What I really want to ask is, as mentioned in the link, what actual **Emitter** _service_ should I be injecting so that I can get an instance of its state and pass that along to the SkipPredicate? I am not sure of what configuration class Smallrye Kafka uses underneath for me to grab an instance of. Maybe @cescoffier might know more on this.

**Comment by cescoffier** [comment]
You can check the health of the kafka connector.

**Comment by LazaroR94** [comment]
> You can check the health of the kafka connector.

Thank you Clement. However, when I do use the KafkaConnector, I am met with this error: `Unsatisfied dependency for type io.smallrye.reactive.messaging.kafka.KafkaConnector and qualifiers [@Default]`. Following the example provided in the Quartz documentation above, I have created this simple predicate class:
```
@Singleton
class QuartzSkipPredicate(private val kafkaConnector: KafkaConnector) : SkipPredicate {
    override fun test(execution: ScheduledExecution?): Boolean {
        return !kafkaConnector.liveness.isOk
    }
}
```

Am I missing something here?

**Comment by mkouba** [comment]
I think that you need to add the [`@Connector(KafkaConnector.CONNECTOR_NAME)`](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConnector.java#LL47-L47C42) qualifier to your `KafkaConnector` injection point.

**Comment by LazaroR94** [comment]
> I think that you need to add the [`@Connector(KafkaConnector.CONNECTOR_NAME)`](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConnector.java#LL47-L47C42) qualifier to your `KafkaConnector` injection point.

Thank you! So I was able to get it to work with the following piece of code. The reasoning for this is because on startup, I only have producer channels being invoked for each Quartz job and therefore the failure points only came from the Emitters and **_not_** the consumer channels.

```
@Singleton
class QuartzSkipPredicate(@Connector(KafkaConnector.CONNECTOR_NAME) private val kafkaConnector: KafkaConnector) : SkipPredicate {
    override fun test(execution: ScheduledExecution?): Boolean {
        return kafkaConnector.producerChannels.isNullOrEmpty()
    }
}
```
