### ISSUE TITLE
Class 'Contact' is not registered for polymorphic serialization in the scope of 'IContact'

### ISSUE THREAD

**Issue by Dutch-0** [quarkusio/quarkus#29496]
I opened an issue at the `kotlinx.serialization` repository, but after validating that the serialization works in my main-method, but not in Quarkus, and after seeing issues like #28996, I thought this would probably be a better location. 

C&P from the original ticket:

**Describe the bug**
I am unable to serialize my objects successfully using polymorphic.

```kotlin
kotlinx.serialization.SerializationException: Class 'Contact' is not registered for polymorphic serialization in the scope of 'IContact'.
Mark the base class as 'sealed' or register the serializer explicitly.
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:113)
	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:109)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:229)
	at kotlinx.serialization.encoding.Encoder$DefaultImpls.encodeNullableSerializableValue(Encoding.kt:299)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeNullableSerializableValue(AbstractEncoder.kt:18)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeNullableSerializableElement(AbstractEncoder.kt:90)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeNullableSerializableElement(StreamingJsonEncoder.kt:154)
	at de.app.model.user.User.write$Self(User.kt:21)
	at de.app.model.user.User$$serializer.serialize(User.kt:21)
	at de.app.model.user.User$$serializer.serialize(User.kt:21)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:224)
	at kotlinx.serialization.json.internal.JsonStreamsKt.encodeByWriter(JsonStreams.kt:28)
	at kotlinx.serialization.json.JvmStreamsKt.encodeToStream(JvmStreams.kt:25)
	at io.quarkus.resteasy.reactive.kotlin.serialization.runtime.KotlinSerializationMessageBodyWriter.writeResponse(KotlinSerializationMessageBodyWriter.kt:44)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:220)
	at org.jboss.resteasy.reactive.server.core.serialization.DynamicEntityWriter.write(DynamicEntityWriter.java:106)
	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:32)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:120)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:78)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:75)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**

```kotlin
@Serializable
open class User (
    override var firstname: String,
    override var lastname: String,

) : BaseModel(), IUser {
    override var contact: IContact? = null
}
```

```kotlin
@Serializable
class Contact(
    override var telephone: String,
    override var email: String,
    
) : BaseModel(), IContact { }
```

```kotlin
@Serializable
@MappedSuperclass
abstract class BaseModel(
    override var id: Long = 0
) :  PanacheEntity(), IBaseModel
```

I've tried setting op polymorphism using different combinations of the following code in my main method, which did not help:
```kotlin
val module = SerializersModule {

    polymorphic(IUser::class) {
        subclass(User::class, User.serializer())
    }

    polymorphic(IContactInfo::class) {
        subclass(ContactInfo::class, ContactInfo.serializer())
    }
}
val format = Json { serializersModule = module }
```

**More info:**
Serialization in my main method like the following does work:
```kotlin
val user: IUser = User("A", "B")
val data: IContact = Contact("9", "8")
user.contact = data
println(format.encodeToString(user))
```

Serializing a `Contact`, or an `User` with `Contact` set to `null` on my endpoint also seems to work. Only when the user has an initialized `Contact`, then I receive the error above. And only on my endpoint. The same setup in my main-method seems to work just fine.

**Environment**
 - Kotlin version: 1.7.21
 - Library version: 1.4.0
 - Kotlin platforms: JVM (Quarkus)
 - Gradle version: 7.5.1

**Comment by geoand** [comment]
What version of Quarkus are you using?

**Comment by Dutch-0** [comment]
2.14.1.Final

**Comment by Dutch-0** [comment]
Creating a custom ContactSerializer:

```kotlin
object ContactSerializer  : KSerializer<IContact> {
    override val descriptor = PrimitiveSerialDescriptor("Contact", PrimitiveKind.STRING)

    override fun deserialize(decoder: Decoder): IContact {
        return  Json.decodeFromString(decoder.decodeString())
    }

    override fun serialize(encoder: Encoder, value: IContact) {
        encoder.encodeSerializableValue(Contact.serializer(), value as IContact)
    }
}
```

and marking the `contact` property in `User` with `@Serializable(with = ContactSerializer::class)` solves this problem for now

**Comment by geoand** [comment]
Can you please attach a sample Quarkus application that exhibits this problem?

Thanks
