### ISSUE TITLE
Unable to run quarkus-run.jar as Java application, but able to run with MVN command

### ISSUE THREAD

**Issue by Sanjini88** [quarkusio/quarkus#29566]
Hi,

I am getting below error while running jar file with command:

```sh
java  -Dquarkus-profile=dev -jar target/quarkus-app/quarkus-run.jar -Dquarkus.args="args" 
```

whereas when I run mz code with clean install quarkus:dev -Dquarkus.args="args" it runs succesfully.

```posh
2022-11-30 11:51:52,103 ERROR [io.qua.run.Application] (main) Failed to start application (with profile dev): 
org.jboss.resteasy.reactive.client.api.WebClientApplicationException: Server response is: 500
        at org.jboss.resteasy.reactive.client.handlers.ClientSetResponseEntityRestHandler.handle(ClientSetResponseEntityRestHandler.java:31)
        at org.jboss.resteasy.reactive.client.handlers.ClientSetResponseEntityRestHandler.handle(ClientSetResponseEntityRestHandler.java:22)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:229)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:279)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Please help to understand what is missing here.

**Comment by geoand** [comment]
Your launch command is incorrect. It should be:

```sh
java -Dquarkus.profile=dev -jar target/quarkus-app/quarkus-run.jar args
```
