### ISSUE TITLE
Native image - java.lang.ClassNotFoundException: com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2959]
Native image build process throws java.lang.ClassNotFoundException: com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector

Native image is generated, but console is polluted with stacktrace.
Running Quarkus master and GraalVM 19.0.2 CE.

```
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /Users/rsvoboda/.sdkman/candidates/java/19.0.2-grl/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar getting-started-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[getting-started-1.0-SNAPSHOT-runner:21236]    classlist:   4,446.30 ms
[getting-started-1.0-SNAPSHOT-runner:21236]        (cap):   2,193.08 ms
[getting-started-1.0-SNAPSHOT-runner:21236]        setup:   3,750.74 ms
java.lang.ClassNotFoundException: com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.quarkus.runner.AutoFeature.registerClass9(AutoFeature.zig:1773)
	at io.quarkus.runner.AutoFeature.beforeAnalysis(AutoFeature.zig:350)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:667)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:64)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:667)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ser.std.SqlDateSerializer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.quarkus.runner.AutoFeature.registerClass10(AutoFeature.zig:2321)
	at io.quarkus.runner.AutoFeature.beforeAnalysis(AutoFeature.zig:352)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:667)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:64)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:667)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
```

Running `mvn verify -Dnative` passes but console is polluted with stacktrace

**Comment by gsmet** [comment]
This is due to this code: https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java#L491 .

We have several options:
- live with it: I don't think that's acceptable as it's going to log an exception in A LOT of cases
- remove it: not sure it's a good idea as it would break some Jackson install
- it's logged by a `printStackTrace()` that was previously commented. If allowing an incomplete classpath solves the issue; maybe we could revert this change for this version and add it again once we allow the incomplete classpath. We would need to check it fixes the issue though as I suppose we want this stacktrace in some cases.
- move that to Jackson extensions. But I don't think we have the time to do that before tomorrow and Jackson is split in a lot of modules so I don't know how many extensions we would need to do that properly. If we just take these two classes, it's already two separate extensions jaxb and databind.

@dmlloyd what do you think about commenting the stacktrace again for tomorrow's release? We would have more time to think about a proper fix for the next release.

**Comment by dmlloyd** [comment]
> @dmlloyd what do you think about commenting the stacktrace again for tomorrow's release? We would have more time to think about a proper fix for the next release.

Sure, seems fine, as long as it's tracked & fixed later.

**Comment by machi1990** [comment]
> > @dmlloyd what do you think about commenting the stacktrace again for tomorrow's release? We would have more time to think about a proper fix for the next release.
> 
> Sure, seems fine, as long as it's tracked & fixed later.

Maybe comment for tomorrow release with reference to this issue and keep this issue open for tracking?

**Comment by gsmet** [comment]
I think I will just test if the classes are in the classpath for now.

This way, the workaround is very localized and where the things are already a bit ad hoc.

We do that a few lines above for another class.

I'll try to push something this evening.
