### ISSUE TITLE
Random execution error when Lambda Handler class implements ```RequestHandler<Object, "anything">```

### ISSUE THREAD

**Issue by lfmatosm** [quarkusio/quarkus#29619]
### Describe the bug

Hi, how are you doing? I found some strange behavior writing AWS Lambdas using `quarkus-amazon-lambda` and I would like to share my findings.

When a handler class with multiple `public` methods implements Amazon Lambda's `RequestHandler` interface with input type being `Object` and output type being anything else (ex. ```RequestHandler<Object, "anything">```), the invocation behavior becomes erratic.

I reproduced failures on three distinct scenarios.

### First scenario
Here we have a handler class with a single `handleRequest` method and another public method by the name of `generateResponse`.
```java
package org.test.lambda;

import org.jboss.logging.Logger;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class GreetingLambda implements RequestHandler<Object, String> {
    private static final Logger log = Logger.getLogger(GreetingLambda.class);
    private String response = null;

    @Override
    public String handleRequest(Object input, Context context) {
        log.info("Called 'handleRequest'");
        generateResponse(input);
        return response;
    }

    public void generateResponse(Object input) {
        log.info("Called 'generateResponse'");
        response = "Hello!";
    }
}
```

When executing tests, sometimes they pass, but randomly they will fail with the following piece of log:
```plaintext
> Task :test

LambdaHandlerTest STANDARD_OUT
    2022-12-01 11:16:41,028 WARN  [io.net.res.dns.DnsServerAddressStreamProviders] (build-4) Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'
    2022-12-01 11:16:41,251 INFO  [io.qua.ama.lam.run.MockEventServer] (build-4) Mock Lambda Event Server Started
    2022-12-01 11:16:41,821 INFO  [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (TEST)) Listening on: http://localhost:8081/_lambda_/2018-06-01/runtime/invocation/next
    2022-12-01 11:16:41,836 INFO  [io.quarkus] (Test worker) amazon-lambda-random-shutdown-failure 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.14.2.Final) started in 1.692s. 
    2022-12-01 11:16:41,837 INFO  [io.quarkus] (Test worker) Profile test activated. 
    2022-12-01 11:16:41,838 INFO  [io.quarkus] (Test worker) Installed features: [amazon-lambda, cdi]

Called 'handleRequest'
Called 'generateResponse'
Failed to run lambda (TEST)
java.lang.IllegalArgumentException: Class void is not a primitive type
        at com.fasterxml.jackson.databind.util.ClassUtil.wrapperType(ClassUtil.java:908)
        at com.fasterxml.jackson.databind.SerializerProvider._reportIncompatibleRootType(SerializerProvider.java:1385)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:381)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1514)
        at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1219)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1044)
        at io.quarkus.amazon.lambda.runtime.JacksonOutputWriter.writeValue(JacksonOutputWriter.java:18)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop.postResponse(AbstractLambdaPollLoop.java:249)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:138)
        at java.base/java.lang.Thread.run(Thread.java:829)
Aborting lambda poll loop: ending dev/test mode
Lambda polling thread complete (TEST)
%s%s stopped in %ss
Stopping Mock Lambda Event Server
Gradle Test Executor 51 finished executing tests.
```

Which suggests that the correct `handleRequest` method was chosen and called (note the `Called 'handleRequest' log at the beginning`) but the Lambda response, which is a `String` was being transformed into `void`, thus the failure. `void` is not the return type of the `handleRequest` method but is the return type of the `generateResponse` method.

I was able to reproduce this scenario on a real AWS Lambda's environment.

Both the following scenarios are variations of this one.

### Second scenario
Let's change the previous code a little bit:

```diff
package org.test.lambda;

import org.jboss.logging.Logger;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class GreetingLambda implements RequestHandler<Object, String> {
    private static final Logger log = Logger.getLogger(GreetingLambda.class);
    private String response = null;

    @Override
    public String handleRequest(Object input, Context context) {
        log.info("Called 'handleRequest'");
-       generateResponse(input);
+       generateResponse("ignored");
        return response;
    }

-    public void generateResponse(Object input) {
+    public void generateResponse(String input) {
        log.info("Called 'generateResponse'"); 
        response = "Hello!";
    }
}
```

Now the tests will randomly fail with:
```plaintext
> Task :test
    2022-12-01 11:22:49,776 WARN  [io.net.res.dns.DnsServerAddressStreamProviders] (build-26) Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'
    2022-12-01 11:22:49,981 INFO  [io.qua.ama.lam.run.MockEventServer] (build-26) Mock Lambda Event Server Started
    2022-12-01 11:22:50,664 INFO  [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (TEST)) Listening on: http://localhost:8081/_lambda_/2018-06-01/runtime/invocation/next
    2022-12-01 11:22:50,670 INFO  [io.quarkus] (Test worker) amazon-lambda-random-shutdown-failure 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.14.2.Final) started in 1.822s. 
    2022-12-01 11:22:50,671 INFO  [io.quarkus] (Test worker) Profile test activated. 
    2022-12-01 11:22:50,671 INFO  [io.quarkus] (Test worker) Installed features: [amazon-lambda, cdi]

LambdaHandlerTest > testSimpleLambdaSuccess() STANDARD_OUT
    2022-12-01 11:22:52,175 ERROR [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (TEST)) Failed to run lambda (TEST): com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
     at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1420)
        at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:932)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2051)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1427)
        at io.quarkus.amazon.lambda.runtime.JacksonInputReader.readValue(JacksonInputReader.java:17)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:135)
        at java.base/java.lang.Thread.run(Thread.java:829)


Failed to run lambda (TEST)
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1420)
        at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:932)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2051)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1427)
        at io.quarkus.amazon.lambda.runtime.JacksonInputReader.readValue(JacksonInputReader.java:17)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:135)
        at java.base@11.0.17/java.lang.Thread.run(Thread.java:829)
Aborting lambda poll loop: ending dev/test mode
Lambda polling thread complete (TEST)
%s%s stopped in %ss
Stopping Mock Lambda Event Server
Gradle Test Executor 52 finished executing tests.
```

Now it seems that `public void generateResponse(String input)` was called directly and the error resulted from trying to convert the `Object` input of the handler to the `String` class argument of this method.

### Third scenario
Let's further change the `generateResponse` method by removing its arguments:
```diff
package org.test.lambda;

import org.jboss.logging.Logger;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class GreetingLambda implements RequestHandler<Object, String> {
    private static final Logger log = Logger.getLogger(GreetingLambda.class);
    private String response = null;

    @Override
    public String handleRequest(Object input, Context context) {
        log.info("Called 'handleRequest'");
-       generateResponse("ignored");
+       generateResponse();
        return response;
    }

-    public void generateResponse(String input) {
+    public void generateResponse() {
        log.info("Called 'generateResponse'");
        response = "Hello!";
    }
}
```

Now we have a bigger stacktrace:
```plaintext
> Task :test FAILED
LambdaHandlerTest STANDARD_OUT
    2022-12-01 11:40:39,480 WARN  [io.net.res.dns.DnsServerAddressStreamProviders] (build-17) Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'
    2022-12-01 11:40:39,651 INFO  [io.qua.ama.lam.run.MockEventServer] (build-17) Mock Lambda Event Server Started
    2022-12-01 11:40:40,292 INFO  [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (TEST)) Listening on: http://localhost:8081/_lambda_/2018-06-01/runtime/invocation/next

LambdaHandlerTest > testSimpleLambdaSuccess() FAILED
    java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:625)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:696)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)
        at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

        Caused by:
        java.lang.RuntimeException: Failed to start quarkus
            at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
            at io.quarkus.runtime.Application.start(Application.java:101)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
            at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:253)
            at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:250)
            at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:592)
            at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:640)
            at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
            at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
            at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
            at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
            at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
            at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
            ... 52 more

            Caused by:
            java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
                at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.setHandlerClass(AmazonLambdaRecorder.java:61)
                at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.chooseHandlerClass(AmazonLambdaRecorder.java:158)
                at io.quarkus.deployment.steps.AmazonLambdaProcessor$recordHandlerClass308924844.deploy_0(Unknown Source)
                at io.quarkus.deployment.steps.AmazonLambdaProcessor$recordHandlerClass308924844.deploy(Unknown Source)
                ... 68 more

1 test completed, 1 failed
Finished generating test XML results (0.0 secs) into: /Users/luiz.matos/Downloads/amazon-lambda-random-shutdown-failure/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.002 secs) into: /Users/luiz.matos/Downloads/amazon-lambda-random-shutdown-failure/build/reports/tests/test
:test (Thread[Execution worker Thread 11,5,main]) completed. Took 3.822 secs.
```

Which indicates that the `generateResponse` would be wrongly chosen as handler method for the class, but the resulting error prevented quarkus from initializing.

## How to prevent?
The third scenario was described previously on #11510. On this discussion, some suggested solutions were:

- keep a single `public` method on the handler class, so quarkus will never pick the wrong one to call, or
- implement a stricter version of the `RequestHandler` interface by replacing the generic `Object`-based input by some specific type

Both solutions seem to work by the tests I made, so hopefully this issue will be useful to anyone encountering a similar problem and looking for a solution :)

## What is the reason?
According to the #11510 issue, the behavior is related to quarkus non-deterministic discovery of the handler method. This process initially ignores `handleRequest` methods where the input type is `Object` and then randomly picks the first method it founds to use as handler. Looking around, I found this piece of code which I believe describes this behavior:
https://github.com/quarkusio/quarkus/blob/45dba69b9c1d93e6ae8d6b31699d8ac253b1683a/extensions/amazon-lambda/runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaRecorder.java#L90-L110

The behavior in question is quite puzzling, the exceptions thrown significantly change based on the state of code and no recommendation of the suggested prevention measures is given on the [official docs](https://quarkus.io/guides/amazon-lambda). So, after struggling with these scenarios, I decided to open this issue.

### Expected behavior

quarkus should choose the correct `handleRequest` method and not pick one method randomly. It should also be able to serialize the response to the correct return type

### Actual behavior

quarkus randomly chooses from the `public` methods declared one method to handle requests. It also exhibits inconsistency regarding the `handleRequest` method return type even when calling it, by trying to serialize the response into an unexpected type

### How to Reproduce?

Reproducer: https://github.com/lffloyd/amazon-lambda-random-shutdown-failure-repro (its a Gradle repo but that doesn't seem related at all)

The reproducer consists of the code shown on the `First scenario` section above. The other scenarios are derived from small changes to the referred code, as shown previously. The reproducer was generated with https://code.quarkus.io/, using Java 11, gradle and adding just the `quarkus-amazon-lambda` extension.

Steps to reproduce:
1. Execute `./gradlew clean test build --info --stacktrace`. Sometimes the test will fail, sometimes it will run successfully. When a failure occurs, it conforms to the described error. The behavior is non-deterministic
2. You can update the code to reflect the other scenarios. By executing tests again, the error will happen randomly again

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

### Output of `java -version`

11.0.17

### GraalVM version (if different from Java)

OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 11.0.17+8-jvmci-22.3-b08, mixed mode, sharing)

### Quarkus version or git rev

2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.5.1 (gradle)

### Additional information

#11510 is a related issue and describes the third failure scenario described above.

**Comment by patriot1burke** [comment]
Quarkus wraps and marshalls i/o to the handler.  Since it is an Object it doesn't know how to unmarshal it as you haven't given it a type.

How does regular Lambda handle Object?

**Comment by lffloyd** [comment]
@patriot1burke no special requirements are needed according to the [AWS Lambda handler in Java docs](https://docs.aws.amazon.com/lambda/latest/dg/java-handler.html). They also describe `List<Object>` as an possible example to handle JSON arrays, so it seems there's no intrinsic problem by using a generic type.

We also have deployed regular Lambda functions written in Java with input type set to `Object` that execute just fine.

**Comment by geoand** [comment]
Is this still an issue in the latest versions of Quarkus?

**Comment by geoand** [comment]
Closing for lack of feedback
