### ISSUE TITLE
Creating a native container image with quarkus-container-image-docker fails when using Podman on macOS

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#29701]
### Describe the bug

Building a native container image with `quarkus-container-image-docker` on macOS with `alias docker=podman` results in a failure

```shell
Error: preparing container e1fa001f03ebcda62e17dfd0d36b3ca9fa6a39e0c91153be99fb757f5f3bb2ad for attach: lsetxattr /Users/<snip>/build/<snip>-1.0-SNAPSHOT-native-image-source-jar/lib: operation not supported

> Task :quarkusBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 126
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:421)
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:262)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

The container builds successfully when using Docker directly.

Possibly related https://github.com/containers/podman/issues/13631

### Expected behavior

Building a native container image with podman works on macOS

### Actual behavior

Building a native container image with podman fails on macOS 

### Output of `uname -a` or `ver`

Darwin MacBook-Pro 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### Quarkus version or git rev

2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.6

**Comment by berkanaslan** [comment]
Same issue here.

**Comment by danielbjorkholm** [comment]
I've got the same Error: statfs issue. On MacOS Intel.
Tried Quarkus 2.15.3.Final and 2.9.2.Final. Issue persists regardless of using -Dquarkus.native.builder-image=mandrel or just default.

**Comment by danielbjorkholm** [comment]
Solved the "no such file" by upgrading podman (4.1.1 -> 4.3.1), deleted the machine and reinitiated it.

So now, I'm at your original issue:
`Error: preparing container dade691ac58e577a525a09d06209bf6feea4edf4a5f401595e1d9159ccd4fd42 for attach: lsetxattr /Users/[redacted]/target/[redacted]-2.14.0-SNAPSHOT-native-image-source-jar/lib: operation not supported`

**Comment by cmoulliard** [comment]
As building an image since podman 5 has been improved a lot and works now, I propose to close this issue 

Test done using Quarkus 3.24 on macos using podman 5.5
```
❯ quarkus build --native --no-tests -Dquarkus.native.container-build=true -Dquarkus.container-image.builder=podman -Dquarkus.native.container-runtime=podman
...
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] podman run --env LANG=C --rm --user 501:20 --userns=keep-id -v /Users/cmoullia/code/_temp/hello/target/hello-1.0-native-image-source-jar:/project --name build-native-oJhQC quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Duser.language=en -J-Duser.country=GB -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -H:+UnlockExperimentalVMOptions -H:IncludeLocales=en-GB -H:-UnlockExperimentalVMOptions -J-Dfile.encoding=UTF-8 -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature,io.quarkus.runtime.graal.SkipConsoleServiceProvidersFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-exports=java.security.jgss/sun.security.jgss=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+UnlockExperimentalVMOptions -H:BuildOutputJSONFile=hello-1.0-runner-build-output-stats.json -H:-UnlockExperimentalVMOptions -H:+UnlockExperimentalVMOptions -H:+GenerateBuildArtifactsFile -H:-UnlockExperimentalVMOptions --strict-image-heap -H:+UnlockExperimentalVMOptions -H:+AllowFoldMethods -H:-UnlockExperimentalVMOptions -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+UnlockExperimentalVMOptions -H:+ReportExceptionStackTraces -H:-UnlockExperimentalVMOptions -H:-AddAllCharsets --enable-url-protocols=http --enable-monitoring=heapdump -H:+UnlockExperimentalVMOptions -H:-UseServiceLoaderFeature -H:-UnlockExperimentalVMOptions -J--add-exports=org.graalvm.nativeimage/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json hello-1.0-runner -jar hello-1.0-runner.jar
========================================================================================================================
GraalVM Native Image: Generating 'hello-1.0-runner' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------
[1/8] Initializing...                                                                                    (2.7s @ 0.14GB)
 Java version: 21.0.8+9-LTS, vendor version: Mandrel-23.1.8.0-Final
 Graal compiler: optimization level: 2, target machine: armv8-a
 C compiler: gcc (redhat, aarch64, 11.5.0)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 5 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Adapts logging during the analysis phase
 - io.quarkus.runtime.graal.SkipConsoleServiceProvidersFeature: Skip unsupported console service providers when quarkus.native.auto-service-loader-registration is false
 - org.eclipse.angus.activation.nativeimage.AngusActivationFeature
------------------------------------------------------------------------------------------------------------------------
 5 experimental option(s) unlocked:
 - '-H:+AllowFoldMethods' (origin(s): command line)
 - '-H:BuildOutputJSONFile' (origin(s): command line)
 - '-H:-UseServiceLoaderFeature' (origin(s): command line)
 - '-H:+GenerateBuildArtifactsFile' (origin(s): command line)
 - '-H:AddOpens' (alternative API option(s): --add-opens java.base/java.lang=ALL-UNNAMED; origin(s): command line)
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 6.11GB of memory (75.6% of 8.09GB system memory, determined at start)
 - 8 thread(s) (100.0% of 8 available processor(s), determined at start)
[2/8] Performing analysis...  [*****]                                                                   (15.6s @ 1.07GB)
   11,517 reachable types   (86.7% of   13,288 total)
   16,587 reachable fields  (58.8% of   28,201 total)
   58,428 reachable methods (56.3% of  103,809 total)
    3,751 types,   128 fields, and 3,637 methods registered for reflection
       62 types,    67 fields, and    55 methods registered for JNI access
        4 native libraries: dl, pthread, rt, z
[3/8] Building universe...                                                                               (2.4s @ 1.22GB)
[4/8] Parsing methods...      [**]                                                                       (2.1s @ 0.73GB)
[5/8] Inlining methods...     [***]                                                                      (1.0s @ 0.83GB)
[6/8] Compiling methods...    [****]                                                                    (13.6s @ 1.01GB)
[7/8] Laying out methods...   [**]                                                                       (2.5s @ 1.21GB)
[8/8] Creating image...       [**]                                                                       (4.2s @ 1.45GB)
  22.06MB (44.86%) for code area:    37,311 compilation units
  26.70MB (54.30%) for image heap:  311,740 objects and 61 resources
 424.34kB ( 0.84%) for other data
  49.17MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 origins of code area:                                Top 10 object types in image heap:
  11.79MB java.base                                            7.43MB byte[] for code metadata
   1.29MB svm.jar (Native Image)                               4.02MB byte[] for java.lang.String
 910.09kB hello-1.0-runner.jar                                 2.83MB java.lang.Class
 902.14kB modified-io.vertx.vertx-core-4.5.16.jar              2.82MB java.lang.String
 658.02kB org.jboss.resteasy.resteasy-core-6.2.12.Final.jar    1.03MB byte[] for general heap data
 650.59kB io.netty.netty-buffer-4.1.121.Final.jar            989.74kB com.oracle.svm.core.hub.DynamicHubCompanion
 495.39kB io.netty.netty-common-4.1.121.Final.jar            685.02kB byte[] for reflection metadata
 427.55kB com.fasterxml.jackson.core.jackson-core-2.19.1.jar 543.34kB java.lang.String[]
 401.90kB io.netty.netty-codec-http-4.1.121.Final.jar        499.88kB java.util.HashMap$Node
 365.37kB io.netty.netty-transport-4.1.121.Final.jar         423.16kB java.lang.Object[]
   4.07MB for 80 more packages                                 5.49MB for 2848 more object types
------------------------------------------------------------------------------------------------------------------------
Recommendations:
 HEAP: Set max heap for improved and more predictable memory usage.
 CPU:  Enable more CPU features with '-march=native' for improved performance.
------------------------------------------------------------------------------------------------------------------------
                       4.0s (8.9% of total time) in 1022 GCs | Peak RSS: 2.16GB | CPU load: 5.82
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /project/build-artifacts.json (build_info)
 /project/hello-1.0-runner (executable)
 /project/hello-1.0-runner-build-output-stats.json (build_info)
========================================================================================================================
Finished generating 'hello-1.0-runner' in 44.7s.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] podman run --env LANG=C --rm --user 501:20 --userns=keep-id -v /Users/cmoullia/code/_temp/hello/target/hello-1.0-native-image-source-jar:/project --entrypoint /bin/bash quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21 -c objcopy --strip-debug hello-1.0-runner
[INFO] [io.quarkus.container.image.docker.common.deployment.CommonProcessor] Starting (local) container image build for jar using podman
[INFO] [io.quarkus.container.image.docker.common.deployment.CommonProcessor] Executing the following command to build image: 'podman build -f /Users/cmoullia/code/_temp/hello/src/main/docker/Dockerfile.native -t cmoullia/hello:1.0 /Users/cmoullia/code/_temp/hello'
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 1/7: FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5
[INFO] [io.quarkus.deployment.util.ExecUtil] Trying to pull registry.access.redhat.com/ubi9/ubi-minimal:9.5...
[INFO] [io.quarkus.deployment.util.ExecUtil] Getting image source signatures
[INFO] [io.quarkus.deployment.util.ExecUtil] Checking if image destination supports signatures
[INFO] [io.quarkus.deployment.util.ExecUtil] Copying blob sha256:3a51516451292e212d18ae92028ed74f1d747fc2bc7752aa8c608a2cc7d626cc
[INFO] [io.quarkus.deployment.util.ExecUtil] Copying config sha256:229e554401b25e2477343ab8c886258162f53432f72d336ad88e51fa84380514
[INFO] [io.quarkus.deployment.util.ExecUtil] Writing manifest to image destination
[INFO] [io.quarkus.deployment.util.ExecUtil] Storing signatures
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 2/7: WORKDIR /work/
[INFO] [io.quarkus.deployment.util.ExecUtil] --> 7a051d4a76bd
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 3/7: RUN chown 1001 /work     && chmod "g+rwX" /work     && chown 1001:root /work
[INFO] [io.quarkus.deployment.util.ExecUtil] --> bd7a8e3e2731
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 4/7: COPY --chown=1001:root --chmod=0755 target/*-runner /work/application
[INFO] [io.quarkus.deployment.util.ExecUtil] --> 6664b8b22e5f
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 5/7: EXPOSE 8080
[INFO] [io.quarkus.deployment.util.ExecUtil] --> b7d7aa5197ac
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 6/7: USER 1001
[INFO] [io.quarkus.deployment.util.ExecUtil] --> fed10874a554
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 7/7: ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
[INFO] [io.quarkus.deployment.util.ExecUtil] COMMIT cmoullia/hello:1.0
[INFO] [io.quarkus.deployment.util.ExecUtil] --> 054dddf767a9
[INFO] [io.quarkus.deployment.util.ExecUtil] Successfully tagged localhost/cmoullia/hello:1.0
[INFO] [io.quarkus.deployment.util.ExecUtil] 054dddf767a9cf14f095c10a56ff999b922f1822c7df3426ec61255a108037cc
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 63284ms
[INFO]
[INFO] --- failsafe:3.5.3:integration-test (default) @ hello ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- quarkus:3.24.2:native-image-agent (default) @ hello ---
[INFO]
[INFO] --- failsafe:3.5.3:verify (default) @ hello ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- install:3.1.2:install (default-install) @ hello ---
[INFO] Installing /Users/cmoullia/code/_temp/hello/pom.xml to /Users/cmoullia/.m2/repository/io/quarkus/hello/1.0/hello-1.0.pom
[INFO] Installing /Users/cmoullia/code/_temp/hello/target/hello-1.0.jar to /Users/cmoullia/.m2/repository/io/quarkus/hello/1.0/hello-1.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:05 min
[INFO] Finished at: 2025-08-07T11:02:05+02:00
[INFO] ------------------------------------------------------------------------
2025-08-07 11:02:05,388 WARN  [io.sma.com.process] (process-waiter-"mvnw"-83864) SRCOM05000: Command /Users/cmoullia/code/_temp/hello/mvnw (pid 83864) completed but logged errors:
	Trying to pull quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21...
	Getting image source signatures
	Copying blob sha256:a3a3909175b93a7c8c00ef474ad85a468c64f1fa9e19ba4f7f753352cb6b64ee
	Copying blob sha256:00a6599c1f00c80bddd388f4b49e87dcf663d07667a888c1ec255b002e253b00
	Copying blob sha256:e026928d936362cb1335b3499a816386d805c9855e1d4da7954cb5bc6ee53c45
	… (skipped 9 line(s)) …
	Copying blob sha256:a418ab9dc5ab4586fbe3dc7110e5f02c9c43c51581a7145e6d6331a81a6a49ae
	Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
	Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
	Copying config sha256:6bded33fb98638cbe31587fdbf342fe4580bbe1a697b9d34a252f48204b33b17
	Writing manifest to image destination
```

Podman version
```
❯ podman version
Client:        Podman Engine
Version:       5.5.2
API Version:   5.5.2
Go Version:    go1.24.5
Built:         Tue Jun 24 16:41:45 2025
Build Origin:  brew
OS/Arch:       darwin/arm64

Server:       Podman Engine
Version:      5.4.2
API Version:  5.4.2
Go Version:   go1.23.7
Git Commit:   be85287fcf4590961614ee37be65eeb315e5d9ff
Built:        Wed Apr  2 02:00:00 2025
OS/Arch:      linux/arm64
```

WDYT ? @josephearl

**Comment by geoand** [comment]
Closing as per ^
