### ISSUE TITLE
Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3085 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked

### ISSUE THREAD

**Issue by serrg1994** [quarkusio/quarkus#29745]
### Describe the bug

I'm using Reactive Client to make API call, usually everything was working fine and I did not see any issues but today in logs I saw this message

[io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3085 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@17.0.5/java.net.Inet4AddressImpl.lookupAllHostAddr(Inet4AddressImpl.java)
	at java.base@17.0.5/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)
	at java.base@17.0.5/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1529)
	at java.base@17.0.5/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
	at java.base@17.0.5/java.net.InetAddress.getAllByName0(InetAddress.java:1519)
	at java.base@17.0.5/java.net.InetAddress.getAllByName(InetAddress.java:1377)
	at java.base@17.0.5/java.net.InetAddress.getAllByName(InetAddress.java:1305)
	at java.base@17.0.5/java.net.InetAddress.getByName(InetAddress.java:1255)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
	at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:144)
	at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:569)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
	at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:155)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:106)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:92)
	at io.vertx.core.net.impl.NetClientImpl.connectInternal2(NetClientImpl.java:273)
	at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$1(NetClientImpl.java:241)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)

As REST Client I configured to show all logs I have the next sequesnce:

21:19:01,103 INFO - Message about making http request
21:19:04,189 WARN  -  Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3085 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
21:19:05,104 INFO  - (executor-thread-0) GOT ERROR null . **It's error from mutiny onFailure pipe** . Error is null because I put timeout 4 seconds before. And logged **e.message**. Looks like timeout exception does not have message 
21:19:06,155 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-0) Request: POST. **Only here we can see that it started sending http request**

Is I understood the issue was because of DNS resolving timeout.

**Comment by cescoffier** [comment]
Yes, it's a DNS resolution timeout, check your DNS servers. 

It's hard to say more without a proper standalone reproducer.

**Comment by serrg1994** [comment]
> Yes, it's a DNS resolution timeout, check your DNS servers.
> 
> It's hard to say more without a proper standalone reproducer.

So DNS resolution is a blocking call ? Also noticed if we use Mutiny and it has timeout, it does not cancel calling.

For example if DNS resolution takes 6 seconds but you put in Mutiny timeout 4 seconds, in 6 seconds it will make API call what I thing should not happen

**Comment by cescoffier** [comment]
Yes, DNS is a blocking call handled by the JVM.

**Comment by cescoffier** [comment]
What you describe depends on how you build your Uni, it is very likely that you use the current thread and so not doing any async call (which means that timeout cannot work as the thread is blocked).
