### ISSUE TITLE
@ApplicationScoped not recognizing dependency upon Injection (Reactive PostgreSQL Client)

### ISSUE THREAD

**Issue by tkb2022** [quarkusio/quarkus#29771]
### Describe the bug

I followed the Quarkus guide to include Fruit and FruitResource for Reactive PostgreSQL according to [this Quarkus guide](https://quarkus.io/guides/reactive-sql-clients). But instead of making methods in Fruit static to be used in FruitResource, I wanted to make all of the methods non-static and then inject Fruit in FruitResource. The Fruit class has the @ApplicationScoped annotation. It also includes an @Inject for PgPool client because I did not want to pass client as a parameter in the methods. FruitResource has @Inject for a Fruit fruit. 

### Expected behavior

After adding @ApplicationScoped to the Fruit class, a Fruit should be able to be injected into the FruitResource class successfully by using the @Inject annotation, especially since other Inject/ApplicationScoped classes exist within this project and do not have this problem.

### Actual behavior

When running mvn quarkus:dev I get errors such as:

```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.path1.Fruit and qualifiers [@Default]
        - java member: org.path2.FruitResource#fruit
        - declared on CLASS bean [types=[org.path2.FruitResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.path2.FruitResource]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1215)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:140)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:496)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

### How to Reproduce?

Reproducer project cannot be added as it is in a private project. 

### Output of `uname -a` or `ver`

Mac OS (Monterey), M1 chip

### Output of `java -version`

openjdk version "11.0.17" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 11.0.17+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 11.0.17+8-jvmci-22.3-b08, mixed mode)

### Quarkus version or git rev

2.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.6

**Comment by geoand** [comment]
Although it's almost certain that this is not a Quarkus issue, to be 100% sure, we'll need to see the code you wrote.

**Comment by manovotn** [comment]
> After adding @ApplicationScoped to the Fruit class, a Fruit should be able to be injected into the FruitResource class successfully by using the @Inject annotation, especially since other Inject/ApplicationScoped classes exist within this project and do not have this problem.

The fruit class from quickstart should be recognized as a bean once you give it a bean defining annotation (such as the scope you used).
I wonder, does injection of the `Fruit` bean work when you inject it into any other bean than the `FruitRecource`?

> Reproducer project cannot be added as it is in a private project.

You are describing a modification of a quickstart which only seems relevant to quickstart parts. Could you maybe provide that modification minus all the private parts?

**Comment by tkb2022** [comment]
Ahhh sorry I figured it out!! Kept commenting out code in Fruit backwards until it worked - issue was that I was **missing the default/dummy constructor** 🫠 thank you, appreciate the help!! (side note if anyone here is available to check out my [different question (usage/capabilities of a certain quarkus extension) on SO](https://stackoverflow.com/questions/74710353/is-it-possible-to-use-quarkiverse-azureservices-http-web-client-as-i-would-use-t) it would be greatly appreciated, thanks!)
