### ISSUE TITLE
@PreDestroy method not awaited

### ISSUE THREAD

**Issue by miguelzapaton** [quarkusio/quarkus#29783]
## Quarkus version

2.14.2 on Linux with OpenJSD 11.0.17+8

## Actual behaviour

I get the following exception on session timeout:

ERROR [io.qua.arc.imp.AbstractInstanceHandle] (executor-thread-31) Error occurred while destroying instance of bean 
[...SessionManager_Bean]: javax.enterprise.context.ContextNotActiveException: SessionScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=...MyAPIClient, id=5b2...]

## Expected behavior

Session scope and @SessionScoped beans should not be destroyed as long as all methods annotated with @PreDestroy of unremovable beans have returned.

## How to Reproduce?

```
@Named("myAPIClient")
@SessionScoped
public class MyAPIClient implements Serializable {

...

}


@Named("sessionManager")
@SessionScoped
public class SessionManager implements Serializable {

	@Inject
	private myAPIClient myAPIClient;

	@PreDestroy
	public void autoLogout() {

		myAPIClient.doSomething();		// <-- Exception thrown here
		
	}
	
	...

}
```

Any hints?

**Comment by mkouba** [comment]
First of all, you shouldn never invoke other beans in a `@PreDestroy` callback, especially beans with the same scope. The reason is that (1) ordering is not defined; so `MyAPIClient` could have been destroyed before `autoLogout()` is called and thus a new `MyAPIClient` bean instance could be created (and this may or may not cause all kind of issues),  and (2) the context of the other bean may not be active at all.

Now, you're right that in this particular case, the `ContextNotActiveException` does not make sense since both `MyAPIClient` and `SessionManager` are `@SessionScoped`. However, we'll need more info - a full stack trace and ideally a simple reproducer app.

BTW `@SessionScoped` is not supported by default, unless the `quarkus-undertow`  extension is used. Is it the case?

**Comment by miguelzapaton** [comment]
Many thanks @mkouba for your rapid feedback.

> First of all, you shouldn never invoke other beans in a `@PreDestroy` callback, especially beans with the same scope. The reason is that (1) ordering is not defined; so `MyAPIClient` could have been destroyed before `autoLogout()` is called and thus a new `MyAPIClient` bean instance could be created (and this may or may not cause all kind of issues), and (2) the context of the other bean may not be active at all.

Your recommendation refers to ARC specifically or is this best practice for CDI in general?  

In **Wildfly/Weld** this never was a problem.


> Now, you're right that in this particular case, the `ContextNotActiveException` does not make sense since both `MyAPIClient` and `SessionManager` are `@SessionScoped`. However, we'll need more info - a full stack trace and ideally a simple reproducer app.

OK. I'll try to provide a small reproducer during the next days.


> BTW `@SessionScoped` is not supported by default, unless the `quarkus-undertow` extension is used. Is it the case?

Yes, of course. I'm using myfaces-quarkus that has quarkus-undertow as a dependency. I'm trying to migrate an older JSF app from Wildfly. It went quite smooth and the mentioned issue was the only considerable obstacle until now.

I'm aware that this kind of use is not the one Quarkus was invented for and the use of @SessionScope is somewhat old-school. However there may be others trying the migration of older webapps.

**Comment by mkouba** [comment]
> Your recommendation refers to ARC specifically or is this best practice for CDI in general?

For CDI in general. CC @manovotn 

> OK. I'll try to provide a small reproducer during the next days.

+1

**Comment by miguelzapaton** [comment]
Here you can find a small reproducer app:

https://github.com/miguelzapaton/quarkus-predestroy-reproducer

It confirms the described behaviour. 

For my issue I already have a workaround in mind. 

However this could be of general interest as the code worked perfectly in Weld before.

**Comment by mkouba** [comment]
I can see the problem now. The `HttpSession` is invalidated due to a timeout, i.e. the context is destroyed in a `HttpSessionListener#sessionDestroyed()` callback. However, no `HttpServletRequest` available at this point (obviously) and the `io.quarkus.undertow.runtime.HttpSessionContext` does not support this use case and thus a client proxy invocation fails.

We'll need to modify the `HttpSessionContext` to support this use case.

**Comment by miguelzapaton** [comment]
OK. Later I'll add a manual session.invalidate() action to the reproducer to check what happens ...

**Comment by miguelzapaton** [comment]
> OK. Later I'll add a manual session.invalidate() action to the reproducer to check what happens ...

Manual session invalidation works in different scenarios - see updated reproducer.

**Comment by mkouba** [comment]
> > OK. Later I'll add a manual session.invalidate() action to the reproducer to check what happens ...
> 
> Manual session invalidation works in different scenarios - see updated reproducer.

Yes, that's expected. [This pull request](https://github.com/quarkusio/quarkus/pull/29832) should fix the problem. However, keep in mind that if a `@SessionScoped` bean is created during the destruction of the context then it might not be destroyed correctly, i.e. its `@PreDestroy` callback is not invoked.

**Comment by melloware** [comment]
Just a warning my OmniFaces extension started failing on this 2.16-SNAPSHOT with this fix.

You can see my build here: https://github.com/quarkiverse/quarkus-omnifaces/actions/runs/3779243933/jobs/6424351860

In my Integration test JSF XHTML page i am doing this `<li>Session ID: #{session.id}</li>`

It is failing with the following:
```
javax.el.PropertyNotFoundException: The class 'io.undertow.servlet.spec.HttpSessionImpl' does not have the property 'id'.
2022-12-26T06:40:39.6956895Z 	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:104)
2022-12-26T06:40:39.6957483Z 	at org.apache.myfaces.view.facelets.el.ELText$ELTextVariable.writeText(ELText.java:238)
2022-12-26T06:40:39.6957950Z 	at org.apache.myfaces.view.facelets.el.ELText$ELTextComposite.writeText(ELText.java:137)
2022-12-26T06:40:39.6958448Z 	at org.apache.myfaces.view.facelets.compiler.TextInstruction.write(TextInstruction.java:45)
2022-12-26T06:40:39.6959006Z 	at org.apache.myfaces.view.facelets.compiler.UIInstructions.encodeBegin(UIInstructions.java:46)
2022-12-26T06:40:39.6959578Z 	at org.apache.myfaces.view.facelets.compiler.UILeaf.encodeAll(UILeaf.java:362)
```

This works fine locally with 2.15.1 currently.

**Comment by manovotn** [comment]
@melloware what you describe sounds like a separate issue? Unless you are relying on creating new beans during session destruction.

**Comment by melloware** [comment]
Nope I figured it out it was the reflection issue I had to register HTTP Session which I was not expecting.  Thanks!
