### ISSUE TITLE
Regression: `InvalidPathException` when creating initial Flyway script from Dev UI

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#29845]
### Describe the bug

I am not exactly sure when this started, but it must have been with one of the latest releases. When I use the Dev UI to create the initial Flyway migration script, I get this error:
```
2022-12-13 22:06:04,295 ERROR [io.qua.ver.htt.dep.dev.con.DevConsoleProcessor] (DEV Console action) Dev console request failed: java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:db
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.resolve(Path.java:515)
        at io.quarkus.flyway.FlywayDevConsoleProcessor$1.handlePostAsync(FlywayDevConsoleProcessor.java:83)
        at io.quarkus.devconsole.runtime.spi.DevConsolePostHandler$2.run(DevConsolePostHandler.java:60)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

Creating the script should be possible as it was with earlier releases (also on Windows).

### Actual behavior

See description.

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045 C70C3264 3.3.3-341.x86_64 2022-01-17 11:45 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 LTS

### Quarkus version or git rev

2.15.0.Final

**Comment by knutwannheden** [comment]
Hmm, I actually noticed that I had the following in my `application.properties`:
```properties
quarkus.flyway.locations=classpath:db
```
I am unsure if this should work or not. I will investigate a bit further and reopen the issue if necessary.
