### ISSUE TITLE
Liquibase's `clean-at-start` fails to perform its duties

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#29938]
### Describe the bug

I have a simple `Quarkus` application. The (simplified for this issue) configuration file looks like:

```yaml
quarkus:
  liquibase:
    change-log: classpath:database/changelog.xml
    clean-at-start: false
    migrate-at-start: true
    validate-on-migrate: true
---
"%dev":
  quarkus:
    liquibase:
      clean-at-start: true
---
"%prod":
---
"%test":
```

Whenever the application is started with the `dev` profile, and exception is thrown. Removing `clean-at-start`, or just turning it to `false` won't fail the application startup.

### Expected behavior

Database migrations should run after `Liquibase` wipes out the database when using the `dev` profile.

### Actual behavior

The application throws an exception:

```shell
2022-12-18 04:59:08,739 |- ERROR in io.quarkus.runtime.Application:195 [Quarkus Main Thread] - Failed to start application (with profile dev): java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "unexpectedObject" is null
	at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixUnexpected(ChangeGeneratorFactory.java:102)
	at liquibase.lockservice.StandardLockService.destroy(StandardLockService.java:490)
	at liquibase.command.core.InternalDropAllCommandStep.run(InternalDropAllCommandStep.java:118)
	at liquibase.command.CommandScope.execute(CommandScope.java:173)
	at liquibase.Liquibase.dropAll(Liquibase.java:1840)
	at liquibase.Liquibase.dropAll(Liquibase.java:1819)
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:58)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase763757012.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase763757012.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:43)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:123)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:833)
: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "unexpectedObject" is null
	at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixUnexpected(ChangeGeneratorFactory.java:102)
	at liquibase.lockservice.StandardLockService.destroy(StandardLockService.java:490)
	at liquibase.command.core.InternalDropAllCommandStep.run(InternalDropAllCommandStep.java:118)
	at liquibase.command.CommandScope.execute(CommandScope.java:173)
	at liquibase.Liquibase.dropAll(Liquibase.java:1840)
	at liquibase.Liquibase.dropAll(Liquibase.java:1819)
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:58)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase763757012.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase763757012.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:43)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:123)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### How to Reproduce?

- Have a `Quarkus` application with `liquibase` support
- Place a (dummy if wanted) `changelog` configuration
- Configure profiles as stated initially in the question
- Start application :smirk:

### Output of `uname -a` or `ver`

Linux uplink 5.15.81-1-lts #1 SMP Fri, 02 Dec 2022 21:05:15 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.5 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### Quarkus version or git rev

2.14.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.6 ------------------------------------------------------------  Build time:   2022-11-25 13:35:10 UTC Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8  Kotlin:       1.7.10 Groovy:       3.0.13 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.5 (Eclipse Adoptium 17.0.5+8) OS:           Linux 5.15.81-1-lts amd64

### Additional information

I'm trying to replicate `Flyway`'s `clean-at-start` behavior, so I'm assuming that `Liquibase`'s `clean-at-start` is exactly the same.

I've searched for that `clean` command in the `Liquibase` documentation but I couldn't find it :thinking:

**Comment by x80486** [comment]
If used against a real `PostgreSQL` or `MariaDB` instance (and I would assume most supported databases as well) it works correctly:

```shell
All objects dropped from kong@jdbc:postgresql://localhost:5432/kong_db
Running Changeset: database/00000_schema.sql::raw::includeAll
Running Changeset: database/00005_data.sql::raw::includeAll
```

But somehow with `H2` (in-memory) it doesn't work :grimacing:

**Comment by geoand** [comment]
Thanks for reporting.

Any chance you can attach a sample application that behaves the way you describe?
It would greatly aid us in coming up with and testing a fix.

**Comment by x80486** [comment]
[Here](https://github.com/x80486/quarkus-h2/) is a small project you can use to replicate this. I think there is something going on here with `H2`, `Liquibase`, `Quarkus` — or the combination.

### First Issue — Unprofilable `clean-at-start`

1. Make use of the in-memory database JDBC URL
1. Turn `clean-at-start` to `true` for `dev` profile

You will get a `NullPointerException`. Obviously, when the in-memory database JDBC URL is used the database is gone on every (re)start, so that setting wouldn't make a difference, but regardless it shouldn't fail. What's more interesting, when turning it to `true` in the `default` profile (and removing the setting or turning to `false` in `dev`) behaves as it should.

### Second Issue — Changelog not saved correctly and `clean-at-start` (again) not doing its job

1. Make use of the embedded connection JDBC URL — the one with `file` on it

When the application is run for the first time everything is fine, but if when run again will get an error message that `Table "databasechangelog" already exists`. This is not correct, because the migration script(s) should have been applied already and it's expected to have that table with the status for the SQL scripts. Not sure if this is a problem only with `H2`. The key here is that (as I understand it) the database is kept in `quarkus_db[.mv].db`, and its content is maintained between restarts.

1. Turn `clean-at-start` to `true` (for `default` or `dev` profile) and the same error arises. My understanding is that this setting should wipe out the database before running anything else.

> I call the `default` profile the _unnamed_ settings that are common, before specifying a given profile identifier/name in the YAML file.

**Comment by geoand** [comment]
I took a quick look at this, but I don't see anything we can do on our end. This looks like a Liquibase bug, so please open an issue on that repo.

Thanks.
