### ISSUE TITLE
Detected 'Duplicate Endpoint' but this not is

### ISSUE THREAD

**Issue by Amilcar34** [quarkusio/quarkus#30038]
### Describe the bug

My Controller:

	@Path("/entity")
	public class EntityRest {

		@Inject
		EntityService entityService;

		@GET
		@Path("{id}")   // ----- Endpoint 1
		public Entity getEntityById(@PathVariable("id") Integer id) {
			return efectoService.getEntityById(id);
		}

		@GET           // ----- Endpoint 2
		public List<Entity> getEntityByIds(@QueryParam("ids") List<Integer> ids) {	
			return efectoService.getEfectoByIds(ids);
		}
	
		@GET            // ----- Endpoint 3
		public List<Entity> getEntity() {
			return efectoService.getAllEntity();
		}
  	}

### Expected behavior

Consumes endpoints:

// Endpoint 1
http://localhost:8080/entity/4

// Endpoint 2
http://localhost:8080/entity/?ids=4,3,5
or
http://localhost:8080/entity/?ids=4&ids=3&ids=5

// Endpoint 3
http://localhost:8080/entity

### Actual behavior

	Caused by: io.quarkus.deployment.configuration.ConfigurationError: GET /entity is declared by :
	com.ase.EntityRest#getEntityByIds consumes *, produces application/json
	com.ase.EntityRest#getEntity consumes *, produces application/json

	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.checkForDuplicateEndpoint(ResteasyReactiveProcessor.java:946)
	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:596)
	at jdk.internal.reflect.GeneratedMethodAccessor625.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

2022-12-22 12:09:39,207 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-0) Live reload total time: 0.315s 

### How to Reproduce?

Generate controller with two endpoint equals but one with parameter type java.util.List or primitive array

	@GET // Endpoint 2
	public List<Entity> getEntityByIds(@QueryParam("ids") List<Integer> ids) {
		return entityService.getEntityByIds(ids);
	}
 or

	@GET // Endpoint 2
	public List<Entity> getEntityByIds(@QueryParam("ids") Integer[] ids) {
		return entityService.getEntityByIds(ids);
	}

### Output of `java -version`

11

### Quarkus version or git rev

2.14.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.6.3

### Additional information

Im am using Quarkus rigth now, i want to create two methods with diferent parameter but exposing the same resource (/efecto), but i am getting this error: CheckForDuplicateEndponit
Sorry, if this not bug and i not speak native inglish :c

**Comment by sberyozkin** [comment]
Endpoint 2 and 3 are duplicates - they sit on the same Path, queries are optional therefore either endpoint 2 or 3 can be invoked. Collapse endpoint 2 and 3 methods into a single method.

**Comment by Amilcar34** [comment]
@sberyozkin something like that?

	@GET
	public List<Entity> getEntityByIds(@QueryParam("ids") List<Integer> ids) {
		
		if(ids == null || ids.isEmpty())
			return entityService.getAllEfectos();
		
		return entityService.getEfectoByIds(ids);
	}

**Comment by geoand** [comment]
@sberyozkin is absolute correct

**Comment by sberyozkin** [comment]
Thanks @geoand for verifying that assertion.
