### ISSUE TITLE
2.15.1-Final breaks AWS S3 file upload

### ISSUE THREAD

**Issue by jdussouillez** [quarkusio/quarkus#30056]
### Describe the bug

I just upgraded from 2.15.0-Final to 2.15.1-Final and I'm facing an issue with the AWS S3 connector.

When I try to upload a file on a S3 bucket, I get the following error :

```
software.amazon.awssdk.services.s3.model.NoSuchBucketException: The specified bucket does not exist (Service: S3, Status Code: 404, Request ID: 7a62c49f-347e-4fc4-9331-6e8eEXAMPLE, Extended Request ID: MzRISOwyjmnupC6EB399EB057D6167/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:266)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:89)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:132)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$DataCountingPublisher$1.onComplete(ResponseHandler.java:513)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:250)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$600(ResponseHandler.java:75)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:371)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.complete(HandlerPublisher.java:447)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.handlerRemoved(HandlerPublisher.java:435)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:1122)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:370)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:232)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:203)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 more
```

The bucket exists and the bucket variable is injected in the service correctly. If I stop my Quarkus app, set the version to 2.15.0-Final and try again it works fine.

I have no clue for now why this happens, I saw nothing in the 2.15.1 release notes that seems to cause this.
Note: on localhost we're using localstack and not "real" buckets on the cloud.

We use the asynchronous S3 client (version from bom) :

```xml
<dependency>
    <groupId>io.quarkiverse.amazonservices</groupId>
    <artifactId>quarkus-amazon-s3</artifactId>
</dependency>
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>netty-nio-client</artifactId>
</dependency>
```

Our upload code (simplified) :

```java
@ApplicationScoped
public class FileService {

    @ConfigProperty(name = "myproject.aws.bucket")
    protected String bucketName;

    @Inject
    protected S3AsyncClient s3Client;

    public Uni<Void> upload(
        final String id,
        final String filename,
        final InputStream file,
        final Map<String, String> additionnalMetadata) throws IOException {

        // FIXME: toByteArray load all bytes into memory
        byte[] bytes = IOUtils.toByteArray(file);
        byte[] md5 = DigestUtils.md5(bytes);
        var md5base64 = new String(Base64.getEncoder().encode(md5), StandardCharsets.UTF_8);

        var metadata = new HashMap<String, String>();
        metadata.put("filename", filename);
        Optional.ofNullable(additionnalMetadata).ifPresent(metadata::putAll);

        var requestBuilder = PutObjectRequest.builder()
            .bucket(bucketName)
            .key(getKey(id))
            .contentType(FileUtils.getMimeType(bytes))
            .metadata(metadata)
            .contentMD5(md5base64);

        return Uni.createFrom()
            .completionStage(s3Client.putObject(requestBuilder.build(), AsyncRequestBody.fromBytes(bytes)))
            .replaceWithVoid();
    }

    protected String getKey(final String id) {
        return "foo/bar/" + id;
    }
}
```

### Expected behavior

File is uploaded without errors

### Actual behavior

File upload fails with "The specified bucket does not exist". I'm 100% sure the bucket exists and it works perfectly with Quarkus 2.15.0-Final.

### How to Reproduce?

_Not that simple to reproduce in a small standalone project (we need localstack and stuff). I can work on it next week if necessary._

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu120.04) OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu120.04, mixed mode, sharing)

### Quarkus version or git rev

2.15.1-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /home/junior/.m2/wrapper/dists/apache-maven-3.8.6-bin/1ks0nkde5v1pk9vtc31i9d0lcd/apache-maven-3.8.6 Java version: 17.0.5, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.4.0-135-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
This sounds like an Amazon SDK bug.
The difference between `2.15.0.Final` and `2.15.1.Final` is that the later uses version `2.18.41` as opposed to `2.17.291` used by the former (see https://github.com/quarkiverse/quarkus-amazon-services/pull/423).

cc @gsmet

**Comment by jdussouillez** [comment]
@geoand Thanks!

I didn't noticed the version of `io.quarkiverse.amazonservices:quarkus-amazon-s3` changed from [1.3.1](https://github.com/quarkusio/quarkus-platform/blob/2.15.0.Final/generated-platform-project/quarkus-amazon-services/bom/pom.xml#L185) to [1.4.0](https://github.com/quarkusio/quarkus-platform/blob/2.15.1.Final/generated-platform-project/quarkus-amazon-services/bom/pom.xml#L185)

**Comment by gsmet** [comment]
I will close this issue here as my guess is that it's not related to Quarkus (but might be related to the https://github.com/quarkiverse/quarkus-amazon-services/ extension though).

We cannot move issues to the Quarkiverse org so feel free to copy your issue there: https://github.com/quarkiverse/quarkus-amazon-services/ .

If you can reproduce it with localstack, could you open a pull request with a failing test here: https://github.com/quarkiverse/quarkus-amazon-services/ ?

Thanks.

**Comment by jdussouillez** [comment]
Ok I think I get it. It's an issue when using v2.18 of the AWS SDK and localstack.

Issue reported in AWS SDK repo:  https://github.com/aws/aws-sdk-java-v2/issues/3528

From the [changelogs of v2.18.1](https://github.com/aws/aws-sdk-java-v2/blob/2.18.1/CHANGELOG.md#L35) :

> Notably, there are some changes in S3: when including and endpoint override, the SDK will use virtual bucket addressing as long as the bucket is a valid DNS label. This is different from the previous behavior where this only happens if the endpoint override begins with 's3'.

When using localstack in my dev/test profile, my application.properties file overrides the endpoint to use localstack.

```properties
%dev.quarkus.s3.endpoint-override=http://localhost:4566
%test.quarkus.s3.endpoint-override=http://localhost:4566
```

Since v2.18, DNS/virtual-hosted style is used to identify buckets instead of good old path style. The first one doesn't work great with localstack. See the difference here : https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access

To fix this, we should use force the AWS client to use "path style" instead of (now default) "DNS/virtual-hosted style" when using localstack.
To do this, use the [`path-style-access`](https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/amazon-s3.html#quarkus-amazon-s3_quarkus.s3.path-style-access) configuration.

```properties
# Mandatory when using localstack
# See https://github.com/quarkusio/quarkus/issues/30056
%dev.quarkus.s3.path-style-access=true
%test.quarkus.s3.path-style-access=true

%dev.quarkus.s3.endpoint-override=http://localhost:4566
%test.quarkus.s3.endpoint-override=http://localhost:4566
```

Now it works great.
