### ISSUE TITLE
Quarkus Native Build getting OOM error when running halfway

### ISSUE THREAD

**Issue by firdy94** [quarkusio/quarkus#30050]
I am getting OOM issue when running quarkus native build on openshift container.  We are not building the native build directly as container image due to restricted on docker from the company. instead we are building the native build normally using graalvm and putting it inside the docker image to run.

My container has a limit of  4Gi memory with 1000 CPU ram which is the cap set by the company. 

I am using Redisson client library which is creating redisson client , when my application starts the first thing is to create redisson client and after creating around 200 redis connections , I am getting below error with container CrashLoopBackOff . 

After checking, i noticed that even though my container memory is 4Gi, I am getting OOM error after 400MB memory being used

I read some article online which suggested to give more memory to application using -Xmx2g   when starting the native binary
example : ./application -Xmx2g -Dquarkus.http.host=0.0.0.0. But this does not seem to resolve it as well.

Error that was shown: 
2022-12-23 12:26:24,814 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
    at com.oracle.svm.core.thread.PlatformThreads.startThread(PlatformThreads.java:675)
    at java.lang.Thread.start0(Thread.java:343)
    at java.lang.Thread.start(Thread.java:798)
    at io.netty.util.concurrent.ThreadPerTaskExecutor.execute(ThreadPerTaskExecutor.java:32)
    at io.netty.util.internal.ThreadExecutorMap$1.execute(ThreadExecutorMap.java:57)
    at io.netty.util.concurrent.SingleThreadEventExecutor.doStartThread(SingleThreadEventExecutor.java:986)
    at io.netty.util.concurrent.SingleThreadEventExecutor.startThread(SingleThreadEventExecutor.java:955)
    at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:838)
    at io.netty.util.concurrent.SingleThreadEventExecutor.lazyExecute0(SingleThreadEventExecutor.java:831)

Would appreciate if anyone can guide me what wrong is happening?
Am i increasing the memory of the native binary wrongly? if so what is the correct way

**Comment by geoand** [comment]
This is likely due to something the application is doing. Please read [this](https://quarkus.io/guides/native-reference#native-memory-management) for information of how to configure the various memory aspects.
