### ISSUE TITLE
2.15.1.Final : java.lang.ClassNotFoundException: jakarta.inject.Singleton (jersey, 3rd party)

### ISSUE THREAD

**Issue by laurentperez** [quarkusio/quarkus#30069]
### Describe the bug

Hello

Trying to use the official Mattermost client https://mattermost.com/marketplace/api-v4-client-for-java/ , https://github.com/maruTA-bis5/mattermost4j, client creation throws at (1)

Code is https://github.com/maruTA-bis5/mattermost4j/blob/master/mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java#L200

I understand https://github.com/maruTA-bis5/mattermost4j/issues/308 exists, referring to RESTeasy at https://github.com/maruTA-bis5/mattermost4j/issues/481#issuecomment-1162415200

I attempted the following imports, to no luck

```
    implementation("jakarta.inject:jakarta.inject-api:1.0.3")
    implementation("jakarta.activation:jakarta.activation-api:2.1.0")
```
Q: how could I import the `jakarta.inject` namespace into Quarkus ?

(1)
```
2022-12-24 16:14:26,957 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /matter failed, error id: d794560c-0064-49c2-bddc-55514f160a17-1: java.lang.NoClassDefFoundError: jakarta/inject/Singleton
	at org.glassfish.jersey.model.ContractProvider$Builder.<clinit>(ContractProvider.java:67)
	at org.glassfish.jersey.model.ContractProvider.builder(ContractProvider.java:49)
	at org.glassfish.jersey.model.internal.ComponentBag.modelFor(ComponentBag.java:522)
	at org.glassfish.jersey.model.internal.ComponentBag.lambda$registerModel$10(ComponentBag.java:454)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.model.internal.ComponentBag.registerModel(ComponentBag.java:446)
	at org.glassfish.jersey.model.internal.ComponentBag.register(ComponentBag.java:357)
	at org.glassfish.jersey.model.internal.CommonConfig.register(CommonConfig.java:463)
	at org.glassfish.jersey.client.ClientConfig$State.register(ClientConfig.java:223)
	at org.glassfish.jersey.client.ClientConfig.register(ClientConfig.java:613)
	at org.glassfish.jersey.client.JerseyClientBuilder.register(JerseyClientBuilder.java:244)
	at org.glassfish.jersey.client.JerseyClientBuilder.register(JerseyClientBuilder.java:48)
	at net.bis5.mattermost.client4.MattermostClient.buildClient(MattermostClient.java:201)
	at net.bis5.mattermost.client4.MattermostClient.<init>(MattermostClient.java:272)
	at net.bis5.mattermost.client4.MattermostClient$MattermostClientBuilder.build(MattermostClient.java:245)

```

### Expected behavior

Class `jakarta.inject.Singleton` is found on the classpath

### Actual behavior

Caused by: java.lang.ClassNotFoundException: jakarta.inject.Singleton
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:502)

### How to Reproduce?

1. sdk i quarkus
2. import the lib `implementation("net.bis5.mattermost4j:mattermost4j-core:0.25.0")`
3. create a client to get the Exception
```
        var client: MattermostClient
        client = MattermostClient.builder()
            .url("http://localhost:8065")
            .logLevel(Level.INFO)
            .ignoreUnknownProperties()
            .build()
```

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### Quarkus version or git rev

powered by Quarkus 2.15.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by laurentperez** [comment]
I attempted to use the `999-jakarta-SNAPSHOT` rewrite work in progress, per https://github.com/quarkusio/quarkus/tree/main/jakarta#jakarta-migration

However it does not appear to be published on https://s01.oss.sonatype.org/content/repositories/snapshots/io/quarkus/platform/quarkus-bom/

Most of the jobs at https://github.com/quarkusio/quarkus/issues/25363 are greenlit so I'm not sure if the 999-jakarta-SNAPSHOT is expected to be published at Sonatype OSSRH

I'll attempt 3.0.0.Alpha2 and update this issue.

**Comment by laurentperez** [comment]
3.0.0.Alpha2 works for my use case :) thank you @gsmet @maxandersen & all for your work. I understand EE9 and EE10 is indeed a bumpy road.

I guess Alphas now superseed the jakarta artefact name.

merry xmas

**Comment by melloware** [comment]
@laurentperez  Yep 3.0.0.alpha2 is the Jakarta 10 version and the only way that MatterMost client would work.  I think you can close this ticket.
