### ISSUE TITLE
Blaze-Persistence issue in Dev Mode

### ISSUE THREAD

**Issue by KyriacosP** [quarkusio/quarkus#30088]
### Describe the bug

When Quarkus is trying to instantiate CriteriaBuilderFactory in dev mode the following exception is thrown ` HTTP Request to /hello failed, error id: ea2f2f5c-06e2-4865-addf-c1484d84ea97-1: org.jboss.resteasy.spi.UnhandledException: java.util.ServiceConfigurationError: com.blazebit.persistence.spi.EntityManagerFactoryIntegrator: Provider com.blazebit.persistence.integration.hibernate.Hibernate56EntityManagerFactoryIntegrator could not be instantiated` (full exception below) this does not happen when you create a fast jar with mvnw install or mvnw deploy.

I'm attaching a small reproducer. The GreetingResource injects an application scoped class (TestService) which injects the CriteriaBuilderFactory. When the `/hello` endpoint is called the `hello()` method of TestService is called causing the CriteriaBuilderFactory to be instantiated which throws the exception.

This issue started for us with the update to 2.14.3.Final, it was working fine on 2.7.1.Final.

`
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello failed, error id: ea2f2f5c-06e2-4865-addf-c1484d84ea97-1: org.jboss.resteasy.spi.UnhandledException: java.util.ServiceConfigurationError: com.blazebit.persistence.spi.EntityManagerFactoryIntegrator: Provider com.blazebit.persistence.integration.hibernate.Hibernate56EntityManagerFactoryIntegrator could not be instantiated
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.ServiceConfigurationError: com.blazebit.persistence.spi.EntityManagerFactoryIntegrator: Provider com.blazebit.persistence.integration.hibernate.Hibernate56EntityManagerFactoryIntegrator could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
        at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.loadEntityManagerIntegrator(CriteriaBuilderConfigurationImpl.java:1914)
        at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.<init>(CriteriaBuilderConfigurationImpl.java:573)
        at com.blazebit.persistence.impl.CriteriaBuilderConfigurationProviderImpl.createConfiguration(CriteriaBuilderConfigurationProviderImpl.java:47)
        at com.blazebit.persistence.Criteria.getDefault(Criteria.java:65)
        at com.blazebit.persistence.integration.quarkus.runtime.EntityViewRecorder.lambda$criteriaBuilderFactorySupplier$0(EntityViewRecorder.java:45)
        at com.blazebit.persistence.CriteriaBuilderFactory_2f29ab4902e863bcf38a5a9ab37269748362ecdd_Synthetic_Bean.create(Unknown Source)
        at com.blazebit.persistence.CriteriaBuilderFactory_2f29ab4902e863bcf38a5a9ab37269748362ecdd_Synthetic_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
        at com.blazebit.persistence.CriteriaBuilderFactory_2f29ab4902e863bcf38a5a9ab37269748362ecdd_Synthetic_Bean.get(Unknown Source)
        at com.blazebit.persistence.CriteriaBuilderFactory_2f29ab4902e863bcf38a5a9ab37269748362ecdd_Synthetic_Bean.get(Unknown Source)
        at org.acme.TestService_Bean.create(Unknown Source)
        at org.acme.TestService_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
        at org.acme.TestService_ClientProxy.arc$delegate(Unknown Source)
        at org.acme.TestService_ClientProxy.hello(Unknown Source)
        at org.acme.GreetingResource.hello(GreetingResource.java:17)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 15 more
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
        ... 59 more
Caused by: java.lang.IllegalArgumentException: Error while trying to resolve the Hibernate version. This can happen when using an uber-jar deployment. In that case, please provide a service provider implementation of com.blazebit.persistence.integration.hibernate.base.spi.HibernateVersionProvider
        at com.blazebit.persistence.integration.hibernate.base.function.AbstractHibernateEntityManagerFactoryIntegrator.<clinit>(AbstractHibernateEntityManagerFactoryIntegrator.java:96)
        ... 64 more
Caused by: java.lang.IllegalArgumentException: An error happened while trying to resolve the Hibernate version through the module version descriptor
        at com.blazebit.persistence.integration.hibernate.base.funbstractHibernateEntityManagerFactoryIntegrator.<clinit>(AbstractHibernateEntityManagerFactoryIntegrator.java:84)
        ... 64 more
Caused by: java.lang.NullPointerException
        at java.base/java.lang.reflect.Method.invoke(Method.java:559)
        at com.blazebit.persistence.integration.hibernate.base.function.AbstractHibernateEntityManagerFactoryIntegrator.<clinit>(AbstractHibernateEntityManagerFactoryIntegrator.java:79)
        ... 64 more
`

### How to Reproduce?
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/10314025/code-with-quarkus.zip)

1. mvnw quarkus:dev
2. call http://localhost:8080/hello
3. throws Exception
4. mvnw install
5. call http://localhost:8080/hello
6. works fine

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.963]

### Output of `java -version`

java version "11.0.15.1" 2022-04-22 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.15.1+2-LTS-10) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.15.1+2-LTS-10, mixed mode)

### Quarkus version or git rev

2.14.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by geoand** [comment]
This is not a Quarkus core issue, so I propose opening the issue on Blaze's issue tracker. 

cc @beikov

**Comment by KyriacosP** [comment]
Sorry I've already did and i forgot to close this one.

Here is the link for anyone that may be searching for this: [https://github.com/Blazebit/blaze-persistence/issues/1661](url)
