### ISSUE TITLE
[Native] UnresolvedElementException: Discovered unresolved method during parsing: com.fasterxml.jackson.datatype.jdk8.OptionalDoubleDeserializer._parseDoublePrimitive

### ISSUE THREAD

**Issue by wiradikusuma** [quarkusio/quarkus#30092]
### Describe the bug

I'm upgrading Quarkus from `2.13.3.Final` to `2.15.1.Final`, and as part of that, upgraded my JDK from `22.1.0.0-Final-java11` to `22.3.0.1-Final-java17`. The Docker image is `wiradikusuma/graalvm-maven-for-quarkus:22.3.0.1-Final-java17` (https://github.com/wiradikusuma/docker-graalvm-maven-for-quarkus).

After the upgrade, my native build fails with this exception:

```
com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.fasterxml.jackson.datatype.jdk8.OptionalDoubleDeserializer._parseDoublePrimitive(com.fasterxml.jackson.core.JsonParser, com.fasterxml.jackson.databind.DeserializationContext, java.lang.String)
```

Log leading to the exception:

```
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /Users/MAC_USERNAME/projects/foobar/backend/target/backend-1.0.0-SNAPSHOT-native-image-source-jar/backend-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /Users/MAC_USERNAME/projects/foobar/backend/target/backend-1.0.0-SNAPSHOT-native-image-source-jar/backend-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM 22.3.0 Java 17 CE (Java Version 17.0.5+8-jvmci-22.3-b08)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /Users/MAC_USERNAME/.sdkman/candidates/java/22.3.r17-grl/bin/native-image -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dlogging.initial-configurator.min-level=500 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=ID -J-Dfile.encoding=UTF-8 --features=io.quarkus.caffeine.runtime.graal.CacheConstructorsFeature,io.quarkus.jdbc.postgresql.runtime.graal.SQLXMLFeature,org.hibernate.graalvm.internal.QueryParsingSupport,org.hibernate.graalvm.internal.GraalVMStaticFeature,io.quarkus.runner.Feature,io.quarkus.runtime.graal.ResourcesFeature,io.quarkus.runtime.graal.DisableLoggingFeature,io.quarkus.hibernate.validator.runtime.DisableLoggingFeature,io.quarkus.hibernate.orm.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+CollectImageBuildStatistics -H:ImageBuildStatisticsFile=backend-1.0.0-SNAPSHOT-runner-timing-stats.json -H:BuildOutputJSONFile=backend-1.0.0-SNAPSHOT-runner-build-output-stats.json --allow-incomplete-classpath --initialize-at-run-time=org.apache.commons.lang3.RandomStringUtils,org.apache.commons.lang3.RandomUtils -H:ReflectionConfigurationFiles=reflection-config.json -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http,https -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json backend-1.0.0-SNAPSHOT-runner -jar backend-1.0.0-SNAPSHOT-runner.jar
Warning: Using a deprecated option --allow-incomplete-classpath from command line. Allowing an incomplete classpath is now the default. Use --link-at-build-time to report linking errors at image build time for a class or package.
Warning: Using a deprecated option --allow-incomplete-classpath from 'META-INF/native-image/com.google.api/gax/native-image.properties' in 'file:///Users/MAC_USERNAME/projects/foobar/backend/target/backend-1.0.0-SNAPSHOT-native-image-source-jar/lib/com.google.api.gax-2.19.1.jar'. Allowing an incomplete classpath is now the default. Use --link-at-build-time to report linking errors at image build time for a class or package.
========================================================================================================================
GraalVM Native Image: Generating 'backend-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (28.6s @ 0.75GB)
 Version info: 'GraalVM 22.3.0 Java 17 CE'
 Java version info: '17.0.5+8-jvmci-22.3-b08'
 C compiler: cc (apple, arm64, 14.0.0)
 Garbage collector: Serial GC
 15 user-specific feature(s)
 - com.google.api.gax.grpc.nativeimage.GrpcNettyFeature
 - com.google.api.gax.grpc.nativeimage.ProtobufMessageFeature
 - com.google.api.gax.nativeimage.GoogleJsonClientFeature
 - com.google.api.gax.nativeimage.OpenCensusFeature
 - com.oracle.svm.polyglot.scala.ScalaFeature
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.quarkus.caffeine.runtime.graal.CacheConstructorsFeature
 - io.quarkus.hibernate.orm.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.hibernate.Version, org.hibernate.annotations.common.Version, org.hibernate.dialect.Dialect] categories
 - io.quarkus.hibernate.validator.runtime.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.hibernate.validator.internal.util.Version] categories
 - io.quarkus.jdbc.postgresql.runtime.graal.SQLXMLFeature
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.jboss.threads] categories
 - io.quarkus.runtime.graal.ResourcesFeature: Register each line in META-INF/quarkus-native-resources.txt as a resource on Substrate VM
 - org.hibernate.graalvm.internal.GraalVMStaticFeature: Hibernate ORM's static reflection registrations for GraalVM
 - org.hibernate.graalvm.internal.QueryParsingSupport: Hibernate ORM's support for HQL Parser in GraalVM
[2/7] Performing analysis...  []                                                                        (39.7s @ 3.68GB)
  21,664 (93.96%) of 23,056 classes reachable
  28,419 (63.57%) of 44,702 fields reachable
  88,130 (81.08%) of 108,692 methods reachable
   1,229 classes,     0 fields, and     0 methods registered for reflection
       1 native library: -framework CoreServices

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.fasterxml.jackson.datatype.jdk8.OptionalDoubleDeserializer.deserialize(com.fasterxml.jackson.core.JsonParser, com.fasterxml.jackson.databind.DeserializationContext) 
Parsing context:
   at com.fasterxml.jackson.datatype.jdk8.OptionalDoubleDeserializer.deserialize(OptionalDoubleDeserializer.java:29)
   at com.fasterxml.jackson.datatype.jdk8.OptionalDoubleDeserializer.deserialize(OptionalDoubleDeserializer.java:13)
   at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._deserializeWithNativeTypeId(TypeDeserializerBase.java:269)
   at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:88)
   at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromAny(AsWrapperTypeDeserializer.java:67)
...
   at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromParser(QuarkusJacksonJsonCodec.java:125)
   at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.fromString(QuarkusJacksonJsonCodec.java:95)
   at io.vertx.core.json.JsonObject.fromJson(JsonObject.java:1250)
   at io.vertx.core.json.JsonObject.<init>(JsonObject.java:51)
   at io.vertx.core.impl.HAManager.checkQuorum(HAManager.java:369)
...
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.fasterxml.jackson.datatype.jdk8.OptionalDoubleDeserializer._parseDoublePrimitive(com.fasterxml.jackson.core.JsonParser, com.fasterxml.jackson.databind.DeserializationContext, java.lang.String). This error is reported at image build time because class com.fasterxml.jackson.datatype.jdk8.OptionalDoubleDeserializer is registered for linking at image build time by command line
	at parsing com.fasterxml.jackson.datatype.jdk8.OptionalDoubleDeserializer.deserialize(OptionalDoubleDeserializer.java:51)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2518)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:110)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3393)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3345)
...
```

### Expected behavior

The native build should work, just like before the upgrade.

### Actual behavior

The native build fails.

### How to Reproduce?

Upgrade Quarkus from `2.13.3.Final` to `2.15.1.Final`, and as part of that, upgrade JDK from `22.1.0.0-Final-java11` to `22.3.0.1-Final-java17`. The Docker image is `wiradikusuma/graalvm-maven-for-quarkus:22.3.0.1-Final-java17` (https://github.com/wiradikusuma/docker-graalvm-maven-for-quarkus).

### Output of `uname -a` or `ver`

Darwin SDSMac005s-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### GraalVM version (if different from Java)

GraalVM CE 22.3.0

### Quarkus version or git rev

2.15.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0

**Comment by wiradikusuma** [comment]
Fixed by upgrading Jackson to latest version (2.14.1).
