### ISSUE TITLE
I use GraalVM  version `graalvm-ce-19.0.0` to compile sub project hibernate-validator  with tag `0.18.0` get errors

### ISSUE THREAD

**Issue by guanchao-yang** [quarkusio/quarkus#3015]
I use GraalVM  version `graalvm-ce-19.0.0` to compile your sub project [hibernate-validator](https://github.com/quarkusio/quarkus/tree/master/integration-tests/hibernate-validator)  with tag `0.18.0` get errors below : 

```
[INFO] --- quarkus-maven-plugin:0.18.0:native-image (native-image) @ quarkus-integration-test-hibernate-validator ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on Java HotSpot(TM) 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /Applications/graalvm-ce-19.0.0/Contents/Home/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-integration-test-hibernate-validator-0.18.0-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[quarkus-integration-test-hibernate-validator-0.18.0-runner:65448]    classlist:   3,413.03 ms
[quarkus-integration-test-hibernate-validator-0.18.0-runner:65448]        (cap):   1,829.82 ms
[quarkus-integration-test-hibernate-validator-0.18.0-runner:65448]        setup:   2,944.98 ms
14:35:34,111 INFO  [org.hib.val.int.uti.Version] HV000001: Hibernate Validator 6.1.0.Alpha5
14:35:34,830 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta4
14:35:35,315 INFO  [org.xnio] XNIO version 3.7.2.Final
14:35:35,361 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.2.Final
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.quarkus.runtime.CleanableExecutor$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.quarkus.runtime.CleanableExecutor$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResettingRunnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResettingRunnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[quarkus-integration-test-hibernate-validator-0.18.0-runner:65448]   (typeflow):  11,009.00 ms
[quarkus-integration-test-hibernate-validator-0.18.0-runner:65448]    (objects):  13,561.23 ms
[quarkus-integration-test-hibernate-validator-0.18.0-runner:65448]   (features):     630.99 ms
[quarkus-integration-test-hibernate-validator-0.18.0-runner:65448]     analysis:  25,775.06 ms
Printing call tree to /Users/yangguanchao/Idea15Projects/k8s/quarkus/integration-tests/hibernate-validator/target/reports/call_tree_quarkus-integration-test-hibernate-validator-0.18.0-runner_20190628_143602.txt
Printing list of used classes to /Users/yangguanchao/Idea15Projects/k8s/quarkus/integration-tests/hibernate-validator/target/reports/used_classes_quarkus-integration-test-hibernate-validator-0.18.0-runner_20190628_143603.txt
Printing list of used packages to /Users/yangguanchao/Idea15Projects/k8s/quarkus/integration-tests/hibernate-validator/target/reports/used_packages_quarkus-integration-test-hibernate-validator-0.18.0-runner_20190628_143603.txt
[quarkus-integration-test-hibernate-validator-0.18.0-runner:65448]     (clinit):     280.78 ms
[quarkus-integration-test-hibernate-validator-0.18.0-runner:65448]     universe:     775.83 ms
Fatal error: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot create java.lang.reflect.Method for class initializer
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:458)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:289)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:427)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:109)
Caused by: java.lang.IllegalArgumentException: Cannot create java.lang.reflect.Method for class initializer
        at jdk.vm.ci.hotspot.CompilerToVM.asReflectionExecutable(Native Method)
        at jdk.vm.ci.hotspot.HotSpotJDKReflection.getMethod(HotSpotJDKReflection.java:446)
        at jdk.vm.ci.hotspot.HotSpotJDKReflection.getMethodAnnotation(HotSpotJDKReflection.java:175)
        at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.getAnnotation(HotSpotResolvedJavaMethodImpl.java:540)
        at org.graalvm.util.GuardedAnnotationAccess.getAnnotation(GuardedAnnotationAccess.java:52)
        at org.graalvm.util.GuardedAnnotationAccess.isAnnotationPresent(GuardedAnnotationAccess.java:47)
        at com.oracle.svm.hosted.cenum.CEnumCallWrapperSubstitutionProcessor.lookup(CEnumCallWrapperSubstitutionProcessor.java:54)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:396)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:376)
        at com.oracle.graal.pointsto.meta.AnalysisType.getClassInitializer(AnalysisType.java:962)
        at com.oracle.svm.hosted.classinitialization.TypeInitializerGraph.shouldPromoteToUnsafe(TypeInitializerGraph.java:196)
        at com.oracle.svm.hosted.classinitialization.TypeInitializerGraph.lambda$updateTypeInitializerSafety$3(TypeInitializerGraph.java:134)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.oracle.svm.hosted.classinitialization.TypeInitializerGraph.updateTypeInitializerSafety(TypeInitializerGraph.java:134)
        at com.oracle.svm.hosted.classinitialization.TypeInitializerGraph.computeInitializerSafety(TypeInitializerGraph.java:113)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.beforeCompilation(ClassInitializationFeature.java:215)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$2(NativeImageGenerator.java:572)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:64)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:572)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1

```

**Comment by machi1990** [comment]
Hey @guanchao-yang  The minimum required graalvm version is 19.0.2.
