### ISSUE TITLE
NullPointerException when sending SSE with comment only

### ISSUE THREAD

**Issue by SHSolution** [quarkusio/quarkus#30169]
Like explained here:
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#examples

It should be possible to send Server Sent Events that just contain a comment (e.g. to be used as keep-alive mechanism: :keep-alive)

But when trying to send such an event this way:

```java
broadcaster.broadcast(sse.newEventBuilder().comment("keep-alive...").build());
```

I do get a NPE:

```java
java.lang.NullPointerException
        at org.jboss.resteasy.reactive.common.core.Serialisers.findResourceWriters(Serialisers.java:186)
        at org.jboss.resteasy.reactive.common.core.Serialisers.findWriters(Serialisers.java:262)
        at org.jboss.resteasy.reactive.common.core.Serialisers.findWriters(Serialisers.java:240)
        at org.jboss.resteasy.reactive.server.core.SseUtil.serialiseDataToString(SseUtil.java:129)
        at org.jboss.resteasy.reactive.server.core.SseUtil.serialiseEvent(SseUtil.java:72)
        at org.jboss.resteasy.reactive.server.core.SseUtil.send(SseUtil.java:38)
        at org.jboss.resteasy.reactive.server.jaxrs.SseEventSinkImpl.send(SseEventSinkImpl.java:35)
        at org.jboss.resteasy.reactive.server.jaxrs.SseBroadcasterImpl.broadcast(SseBroadcasterImpl.java:53)
        at org.acme.GreetingResource.broadcastInternal(GreetingResource.java:171)
        at org.acme.GreetingResource$1.run(GreetingResource.java:121)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

https://github.com/quarkusio/quarkus/blob/f1986725a60432c539432e9242951d947af8a0dd/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/SseUtil.java#L129

IMO: it should not be tried to serialize the NULL data field so sending an keep-alive event would be possible, e.g.:

```text
:keep-alive
```

see also this check here, which respects this specification:
https://github.com/quarkusio/quarkus/blob/f1986725a60432c539432e9242951d947af8a0dd/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/jaxrs/OutboundSseEventImpl.java#L200

```java
@Override
public OutboundSseEventImpl build() {
    if (this.comment == null && this.data == null) {
        throw new IllegalArgumentException("Must set either comment or data");
    }
    return new OutboundSseEventImpl(name, id, reconnectDelay, type, genericType, mediaType, data, comment);
}
```

Would be nice if this could be fixed.

Even more I would appreciate a function (whether in SseBroadcaster or SseEventSink) which provides the feature to easily send keep-alive messages.

Tested with Quarkus version: 2.15.1.Final

Thanks and regards

Soeren

**Comment by geoand** [comment]
As you have already done an initial analysis of the code, would you be willing to contribute a fix?

Thanks

**Comment by SHSolution** [comment]
I could try but wanted to have this discussed first. I will try to provide a proposal how to solve this particular issue.

**Comment by geoand** [comment]
I will actually handle this one myself, because I see that there is a bug in the client code as well

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/30177 takes care of the issue
