### ISSUE TITLE
Native: build error when an app use DB2 (quarkus-jdbc-db2) and Oracle (quarkus-jdbc-oracle)

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#30176]
### Describe the bug

Quarkus Version: `999-SNAPSHOT`
Works as expected with Quarkus 2.15.0.Final

A native compilation with `quay.io/quarkus/ubi-quarkus-mandrel:22.3-java17` is failing, when an application has the following extensions:
- quarkus-jdbc-oracle
- quarkus-jdbc-db2

Error: 
```
[ERROR]   DB2DatabaseIT Failed to build Quarkus artifacts. Caused by java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:421)
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:262)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

There is a warning message that looks very interesting:
```
16:21:37,142 INFO  JBoss Threads version 3.4.3.Final
16:21:37,152 WARN  The following extensions have required native-image to allow run-time resolution of classes: {quarkus-jdbc-oracle}. This is a global requirement which might have unexpected effects on other extensions as well, and is a hint of the library needing some additional refactoring to better support GraalVM native-image. In the case of 3rd party dependencies and/or proprietary code there is not much we can do - please ask for support to your library vendor. If you incur in any problem with other Quarkus extensions, please try reproducing the problem without these extensions first.
```

Could be related to: https://github.com/quarkusio/quarkus/pull/28921

### How to Reproduce?

`git clone git@github.com:quarkus-qe/quarkus-test-suite.git`

`cd quarkus-test-suite/sql-db/sql-app`

`mvn clean verify -Dnative -Dit.test=DB2DatabaseIT`

Works with Quarkus 2.15.0.Final
`mvn clean verify -Dnative -Dit.test=DB2DatabaseIT -Dquarkus.platform.version=2.15.0.Final`

Note: be sure that the scenario is not disabled in native mode

### Output of `uname -a` or `ver`

Linux fedora 6.0.11-200.fc36.x86_64

### Output of `java -version`

openjdk 17.0.5 2022-10-18

**Comment by michalvavrik** [comment]
Thank you for opening the issue @pjgg .

@jerboaa kindly analysed it and provided issue here https://github.com/quarkusio/quarkus/pull/28921#issuecomment-1364131939, should be fixed by https://github.com/quarkusio/quarkus/pull/28921. We can provide the fix separately, but the issue is with required resources for the test that verifies the issue, while #28921 already verifies the issue (CI was failing without the fix).
