### ISSUE TITLE
Integration test execution fails with a NoSuchMethodException error

### ISSUE THREAD

**Issue by iompo** [quarkusio/quarkus#30191]
### Describe the bug

I have an application with a couple of Rest endpoints, a test class and two integration test classes annotated with @QuarkusIntegrationTest. The integration tests execution task quarkusIntTest always fails, even though the tests should pass.

### Expected behavior

quarkusIntTest task should complete correctly

### Actual behavior

the command line shows the following log

```
% ./gradlew quarkusIntTest
Cannot transform %s as its containing application archive could not be found.
Cannot transform %s as its containing application archive could not be found.

> Task :test

GeometryBinaryIT > shouldReturn204WhenUploadCanceled() FAILED
    java.lang.NoSuchMethodException at Class.java:2108

GeometryBinaryIT > executionError FAILED
    java.lang.NullPointerException at QuarkusIntegrationTestExtension.java:360

Cannot transform %s as its containing application archive could not be found.
Cannot transform %s as its containing application archive could not be found.
```
And inside the jacoco report:

```
java.lang.NoSuchMethodException: io.quarkus.test.junit.mockito.internal.SetMockitoMockAsBeanMockCallback.beforeEach(io.quarkus.test.junit.callback.QuarkusTestMethodContext)
	at java.base/java.lang.Class.getMethod(Class.java:2108)
	at io.quarkus.test.junit.AbstractTestWithCallbacksExtension.invokeCallbacks(AbstractTestWithCallbacksExtension.java:153)
	at io.quarkus.test.junit.AbstractTestWithCallbacksExtension.invokeBeforeEachCallbacks(AbstractTestWithCallbacksExtension.java:76)
	at io.quarkus.test.junit.AbstractTestWithCallbacksExtension.invokeBeforeEachCallbacks(AbstractTestWithCallbacksExtension.java:72)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$2(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	...
```

### How to Reproduce?

run the reproducer available at https://github.com/iompo/integration-error-quarkus

### Output of `java -version`

openjdk version "11.0.16.1"

### Quarkus version or git rev

2.15.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by geoand** [comment]
As mentioned [here](https://quarkus.io/guides/gradle-tooling#running-integration-tests), integration tests should be added to `src/integrationTest/java` (as they are part of the `integrationTest` source set)
