### ISSUE TITLE
EOFException when running tests in CI

### ISSUE THREAD

**Issue by snazy** [quarkusio/quarkus#30264]
### Describe the bug

We regularly see quarkus-jacoco fail the build ([sample CI run](https://github.com/projectnessie/nessie/actions/runs/3875049557/jobs/6607050098)) for (probably) the same reason as #18571. I'm not sure whether the fix #21296 completely helps here - especially in scenarios when Jacoco is still writing the file (i.e. when the file is not empty but not fully written).

Note: there are multiple test invocations on the same project, because we ran into OOMs, because `QuarkusClassLoader.transformedClasses` accumulates stuff, probably related to many starts of the tested CLI. The Gradle `intTest` task is configured w/ `setForkEvery(2)`.

Sample build output:
```

> Task :nessie-quarkus-cli:intTest
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Failed to generate Jacoco reports
java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
	at org.jacoco.core.internal.data.CompactDataInput.readBooleanArray(CompactDataInput.java:64)
	at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:150)
	at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116)
	at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74)
	at io.quarkus.jacoco.runtime.ReportCreator.run(ReportCreator.java:72)
	at java.base/java.lang.Thread.run(Thread.java:829)
Failed to generate Jacoco reports
java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
	at org.jacoco.core.internal.data.CompactDataInput.readBooleanArray(CompactDataInput.java:64)
	at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:150)
	at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116)
	at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74)
	at io.quarkus.jacoco.runtime.ReportCreator.run(ReportCreator.java:72)
	at java.base/java.lang.Thread.run(Thread.java:829)
Failed to generate Jacoco reports
java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
	at org.jacoco.core.internal.data.CompactDataInput.readBooleanArray(CompactDataInput.java:64)
	at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:150)
	at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116)
	at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74)
	at io.quarkus.jacoco.runtime.ReportCreator.run(ReportCreator.java:72)
	at java.base/java.lang.Thread.run(Thread.java:829)
Failed to generate Jacoco reports
java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
	at org.jacoco.core.internal.data.CompactDataInput.readBooleanArray(CompactDataInput.java:64)
	at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:150)
	at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116)
	at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74)
	at io.quarkus.jacoco.runtime.ReportCreator.run(ReportCreator.java:72)
	at java.base/java.lang.Thread.run(Thread.java:829)
Failed to generate Jacoco reports
java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
	at org.jacoco.core.internal.data.CompactDataInput.readBooleanArray(CompactDataInput.java:64)
	at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:150)
	at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116)
	at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74)
	at io.quarkus.jacoco.runtime.ReportCreator.run(ReportCreator.java:72)
	at java.base/java.lang.Thread.run(Thread.java:829)
Failed to generate Jacoco reports
java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
	at org.jacoco.core.internal.data.CompactDataInput.readBooleanArray(CompactDataInput.java:64)
	at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:150)
	at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116)
	at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74)
	at io.quarkus.jacoco.runtime.ReportCreator.run(ReportCreator.java:72)
	at java.base/java.lang.Thread.run(Thread.java:829)
Failed to generate Jacoco reports
java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
	at org.jacoco.core.internal.data.CompactDataInput.readBooleanArray(CompactDataInput.java:64)
	at org.jacoco.core.data.ExecutionDataReader.readExecutionData(ExecutionDataReader.java:150)
	at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:116)
	at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:93)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:60)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:74)
	at io.quarkus.jacoco.runtime.ReportCreator.run(ReportCreator.java:72)
	at java.base/java.lang.Thread.run(Thread.java:829)
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
Generated Jacoco reports in /home/runner/work/nessie/nessie/servers/quarkus-cli/build/jacoco-report
```

**Comment by geoand** [comment]
I wonder if you could give https://github.com/quarkusio/quarkus/pull/30300 a try

**Comment by snazy** [comment]
@geoand giving it a try

**Comment by famod** [comment]
Alternatively, we could now try the `OverlappingFileLockException`approach (see https://github.com/quarkusio/quarkus/issues/18571#issuecomment-963668662) because the file length check should ensure that jacoco has already acquired the lock and Quarkus always comes second.
This could be a more robust solution than waiting a fixed amount of time. :thinking:

**Comment by geoand** [comment]
Yeah, that sounds like a good alternative

**Comment by snazy** [comment]
Wondering, whether relying on the file output could be replaced w/ jacoco's TCP-client output mode. Haven't looked at (and neither thought about) the details, but it seems that jacoco can connect to a remote TCP server and send the execution data that way. Would be quite more code, but maybe more reliable. I.e. quarkus-jacoco opens the TCP socket, then waits for the jacoco agent to connect and send the output. WDYT?

**Comment by geoand** [comment]
I'd like to avoid that if we can

**Comment by famod** [comment]
FWIW, in #18571 @stuartwdouglas was talking about a possible JMX approach.

**Comment by geoand** [comment]
Yeah, I saw that too. Personally I am of the opinion of not going over the wire of we can avoid it.

**Comment by snazy** [comment]
Just realized that we set `JacocoConfig.reuseDataFile` to `true`, which causes a different behavior if the data file already exists, because it exits the "first wait loop" (the one waiting for the file to appear) immediately. Feels like this makes the situation even trickier :(

**Comment by snazy** [comment]
IIUC `JacocoProcessor.transformerBuildItem()` is called for every test being run (simply speaking: every `@Test` and `@ParameterizedTest` variation). It adds one `BytecodeTransformerBuildItem` for every class on the whole classpath for every test (i.e. number of`BytecodeTransformerBuildItem` instances ~= number-of-tests * classes on the test classpath). It also generates one report via one shutdown hook for every test, although there's only one Jacoco agent (in other words: concurrently generates the same report from the same data file).

**Comment by geoand** [comment]
I need to look into that as I don't remember what the execution model is

**Comment by geoand** [comment]
Is this still a problem?

**Comment by snazy** [comment]
I think it is. We've just changed our build to let Gradle generate the report, which works fine.
