### ISSUE TITLE
ResponseExceptionMapper is not invoked on `java.net.ConnectException: Connection refused`

### ISSUE THREAD

**Issue by Shinigami92** [quarkusio/quarkus#30276]
### Describe the bug

I wrote a ResponseExceptionMapper (in Kotlin) and it looks it works fine, but when the other service I want to access is not running at all, a `java.net.ConnectException: Connection refused` is thrown but doesn't pass to the `toThrowable` function.

### Expected behavior

It should be received inside the `toThrowable` function

https://github.com/Shinigami92/quarkus-fruits/blob/8a198bd6b805a7841537166e0381399d5421f18b/src/main/kotlin/com/github/shinigami92/OtherService.kt#L30-L34

### Actual behavior

Nothing happens and the default handling applies

```jsonc
{
    "details": "Error id 486e5e50-a7db-4d6b-8922-02dd4f34d89e-2, javax.ws.rs.ProcessingException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8079",
    "stack": "javax.ws.rs.ProcessingException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8079
    at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$3.accept(ClientSendRequestHandler.java:217)
    at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$3.accept(ClientSendRequestHandler.java:209)
    at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
    at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onFailure(UniCallbackSubscriber.java:62)
    at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
    at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
    at org.jboss.resteasy.reactive.client.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:37)
    at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
    at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
    at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:86)
    at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163)
    at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:66)
    at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
    at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
    at io.vertx.core.http.impl.HttpClientImpl.lambda$doRequest$6(HttpClientImpl.java:658)
    at io.vertx.core.net.impl.pool.Endpoint.lambda$getConnection$0(Endpoint.java:52)
    at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:162)
    at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:123)
    at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
    at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
    at io.vertx.core.net.impl.pool.SimpleConnectionPool$ConnectFailed$1.run(SimpleConnectionPool.java:384)
    at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:50)
    at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:245)
    at io.vertx.core.net.impl.pool.SimpleConnectionPool.lambda$connect$2(SimpleConnectionPool.java:259)
    at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint.lambda$connect$2(SharedClientHttpStreamEndpoint.java:104)
    at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
    at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
    at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
    at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66)
    at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
    at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98)
    at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55)
    at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
    at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
    at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
    at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
    at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
    at io.vertx.core.net.impl.NetClientImpl.failed(NetClientImpl.java:320)
    at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal2$5(NetClientImpl.java:288)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
    at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
    at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:110)
    at io.vertx.core.net.impl.ChannelProvider.lambda$handleConnect$0(ChannelProvider.java:160)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
    at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8079
Caused by: java.net.ConnectException: Connection refused
    at java.base/sun.nio.ch.Net.pollConnect(Native Method)
    at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
    at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
    at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:1589)"
}
```

### How to Reproduce?

https://github.com/Shinigami92/quarkus-fruits/blob/main/src/main/kotlin/com/github/shinigami92/OtherService.kt#L30-L34

```
git clone git@github.com:Shinigami92/quarkus-fruits.git
cd quarkus-fruits
quarkus dev
```

`GET http://localhost:8080/api/fruit/other`

profit $$$

### Output of `uname -a` or `ver`

Darwin Shinigami-MBP.dermalog.hh 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "19.0.1" 2022-10-18

### Quarkus version or git rev

2.15.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn via quarkus

### Additional information

https://mas.to/@Shini92/109664368712090615

**Comment by Shinigami92** [comment]
Oh, my motivation why I want to do this:
I want to throw a `ServiceUnavailableException` or something similar instead.

I have a `Camera` with a `locationId` and when I create a `camera` with a `locationId`, the `locationService` gets asked whether the `Location` does exists or not.
If the location micro-service is not running, it should throw a human understandable exception / should get catched via try-catch in the `CameraService` and then e.g. other fallbacks could get applied.

I want to route some different Response >= 400 to different exceptions
404 => Prevent Camera from creation as the Location does not exists
400 => Something different went wrong
401 => You are authed in the CameraService but not LocationService (?!)
50x => Location Service is unavailable, apply fallback strategy

**Comment by geoand** [comment]
This is a limitation of the Microprofile REST Client. 
`ResponseExceptionMapper` is explicitly meant to the case where the request to the server was made.

I am not sure there is much we do here, @radcortez WDYT?

**Comment by Shinigami92** [comment]
But why do I need to explicitly handle it on every Service function invocation manually instead of globally say: The service was not available -> do fallback X

Is there any kind of other way I could handle it?

**Comment by geoand** [comment]
I agree there should be a better to handle it that exists currently, I am just saying that `ResponseExceptionMapper` is likely not it.

**Comment by radcortez** [comment]
Unfortunately, there is no way to implement a custom handler for this case. I have the same problem because I want to handle it for Tracing.

I would likely implement such a capability to serve Tracing, which everyone could use, but I haven't started that work yet.

**Comment by geoand** [comment]
@radcortez we can certainly add something Quarkus specific that would fit both ours and user's needs

**Comment by radcortez** [comment]
If I remember correctly, the relevent code is on the RESTEasy side.

**Comment by geoand** [comment]
I am talking about the Reactive REST client which we control

**Comment by radcortez** [comment]
Yes, we can probably do it on the Reactive side, but we also need to handle the classic one :)

**Comment by geoand** [comment]
I don't see it as necessary being honestly. The new features we have added have been almost exclusively to the new client

**Comment by Shinigami92** [comment]
> I don't see it as necessary being honestly. The new features we have added have been almost exclusively to the new client

Off-Topic question to that point:
Is it correct to use the reactive client even if I don't want to use the Mutiny stuff and so on?
So I just want (for ever reason) the classic blocking behavior, or at least the reactive stuff is just not relevant to me?

**Comment by geoand** [comment]
Yes, the `quarkus-rest-client-reactive` can be used in a blocking manner in the exact same way as you used the `quarkus-rest-client`. You only use reactive features if you want to.

**Comment by geoand** [comment]
It's not exactly deprecated yet, but we probably should do that, cc @maxandersen @cescoffier @gsmet
