### ISSUE TITLE
How the end user change the jar in lib folder

### ISSUE THREAD

**Issue by ajaiswal595** [quarkusio/quarkus#30334]
### Describe the bug

These days we are getting multiple vulnerabilities, Let's suppose we have shipped our software to someone else after packaging it.

If we found some vulnerability he will go and change the jar in quarks-app/lib/main which is vulnerable-free. 
But when we start it will get an error 

For example changed netty-buffer version Now i'm getting this error 

```
Jan 12, 2023 6:22:15 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
java.nio.file.NoSuchFileException: /Users/ajaykumarjaiswal/driveE/Exploration/Quarkus-Impl/getting-started/target/quarkus-app/lib/main/io.netty.netty-buffer-4.1.86.Final.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1259)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
        at io.smallrye.common.io.jar.JarFiles.create(JarFiles.java:33)
        at io.quarkus.bootstrap.runner.JarResource.ensureJarFileIsOpen(JarResource.java:170)
        at io.quarkus.bootstrap.runner.JarResource.readLockAcquireAndGetJarReference(JarResource.java:153)
        at io.quarkus.bootstrap.runner.JarResource.getResourceData(JarResource.java:72)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:99)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
        at io.vertx.core.impl.VertxBuilder.initTransport(VertxBuilder.java:327)
        at io.vertx.core.impl.VertxBuilder.init(VertxBuilder.java:265)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:242)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:610)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:592)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.initializeRouter(VertxHttpRecorder.java:286)
        at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:109)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```
        
        
How can we handle such scenarios?

### Expected behavior

We should be able to replace with our desired jar directly in lib/main

### Actual behavior

We are getting error

### How to Reproduce?

Just change any jar version in lib/* folder

**Comment by geoand** [comment]
Which jar did you replace and what did you replace it with?

**Comment by geoand** [comment]
In any case, doing such a hotswap of jars not something we support.

**Comment by ajaiswal595** [comment]
@geoand 

We are replacing wildfly with Quarkus.

There we could do hotswap with the upgraded jar  to fix vulnerability.


But here with Quarkus I'm unable to do hotswap.

It will be very hard to rebuild everytime and ship entire package for a minor version of jar change.

**Comment by ajaiswal595** [comment]
Is there any workaround that I can achieve this?

**Comment by geoand** [comment]
FWIW, rebuilding should not be time consuming or resource intensive is most cases, it's just a Maven or Gradle build. 
There are no workarounds, you need to do it to ensure that everything works.

Even if it were possible, I would argue it's not a great practice a project's tests have not been run

**Comment by geoand** [comment]
If you use the exact same name for the jar you replace, it will probably work

**Comment by ajaiswal595** [comment]
@geoand on the same line is there any option that we can load our custom jar by setting the classpath in Quarkus?

**Comment by geoand** [comment]
Nope, that will not work

**Comment by ajaiswal595** [comment]
@geoand 

If we think of it from a product perspective, the customer may have their own set of jars that they might want to use it at runtime.

As we are only resolving class from appmodel.dat file, I feel it makes it very tightly coupled.

There should be a provision like hotdeploy where we put our jars and it load at runtime in JVM.

If you have some plan then please let me know.

**Comment by geoand** [comment]
That is by design.

We would only revisit this if there is a customer need or a lot of community requests
