### ISSUE TITLE
[Regression in 2.16.0.CR1] Continuous testing fails with `ClassNotFoundException: io.quarkus.arc.impl.ParameterizedTypeImpl`

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#30400]
### Describe the bug

Regular tests are running ok, dev mode also. But in continuous testing I'm getting a build failure that causes all QuarkusTests to be skipped.

### Expected behavior

No failure

### Actual behavior

```
2023-01-16 21:26:49,926 ERROR (,) [io.qua.test] (Test runner thread) >>>>>>>>>>>>>>>>>>>> Summary: <<<<<<<<<<<<<<<<<<<<
AccountServiceTest#handleMissingIdpId_idpIdExists() java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.TypeNotPresentException: Type io/quarkus/arc/impl/ParameterizedTypeImpl not present
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.util.concurrent.ExecutionException: java.lang.TypeNotPresentException: Type io/quarkus/arc/impl/ParameterizedTypeImpl not present
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:324)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:575)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	... 6 more
Caused by: java.lang.TypeNotPresentException: Type io/quarkus/arc/impl/ParameterizedTypeImpl not present
	at org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1051)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
	at org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm.Frame.merge(Frame.java:1197)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1611)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1547)
	at io.quarkus.gizmo.MethodCreatorImpl.write(MethodCreatorImpl.java:139)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:221)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:244)
	at io.quarkus.arc.processor.ComponentsProviderGenerator.generate(ComponentsProviderGenerator.java:169)
	at io.quarkus.arc.processor.BeanProcessor$1.call(BeanProcessor.java:230)
	at io.quarkus.arc.processor.BeanProcessor$1.call(BeanProcessor.java:226)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 5 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.arc.impl.ParameterizedTypeImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1049)
	... 17 more

2023-01-16 21:26:49,927 ERROR (,) [io.qua.test] (Test runner thread) >>>>>>>>>>>>>>>>>>>> 1 TEST FAILED <<<<<<<<<<<<<<<<<<<<
```

### How to Reproduce?

n/a for now

### Output of `uname -a` or `ver`

Linux XXX 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM Zulu17.38+21-CA (build 17.0.5+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.16.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.6

**Comment by aloubyansky** [comment]
@famod is there a previous version that doesn't have this issue?

**Comment by famod** [comment]
2.15.3.Final doesn't have this issue. I'm currently trying to bisect.

**Comment by famod** [comment]
@aloubyansky bisect says #29785 is the culprit.

**Comment by aloubyansky** [comment]
Thanks a lot @famod! Any chance for a reproducer?

**Comment by aloubyansky** [comment]
As a workaround, you could try system property `quarkus.bootstrap.converged-tree-only=true`

**Comment by famod** [comment]
> Any chance for a reproducer?

I cannot promise anything as I don't have much time for that but I'll try my best.

> As a workaround, you could try system property `quarkus.bootstrap.converged-tree-only=true`

That seems to work! I'm only seeing the well-know message about a "Unrecognized configuration key".

**Comment by aloubyansky** [comment]
I won't mind reverting. Although the change is logically doing the right thing. I think it highlighted an issue we have elsewhere. But as I said, we can revert.

**Comment by aloubyansky** [comment]
It's unlikely I'll be able to fix it in the nearest future w/o a reproducer though.

**Comment by gsmet** [comment]
Yeah exactly. I don't want to pressure Falko. Let's revert for now and give him time to provide a reproducer so that we can fix what's wrong.
I'll prepare the revert.

**Comment by famod** [comment]
Ok, I found what's triggering it (but now why/how excatly): Just add:
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jacoco</artifactId>
            <scope>test</scope>
        </dependency>
```
to the `getting-started-testing` quickstart and there you have it!

**Comment by aloubyansky** [comment]
Excellent, thanks a lot @famod

**Comment by famod** [comment]
@aloubyansky interesting, do you have a fix in mind?

**Comment by famod** [comment]
@aloubyansky do you want to keep this issue open? #30416 has "fixed" it for now.

**Comment by geoand** [comment]
Let's close this for now and we can always reopen if it's still an issue
