### ISSUE TITLE
Quarkus Undertow doesn't work with blocking SecurityIdentityAugmentor

### ISSUE THREAD

**Issue by myroch** [quarkusio/quarkus#30405]
### Describe the bug

Found in versions: 2.15.0, 2.15.3

Extension used: [cdi, resteasy, resteasy-jsonb, security, servlet, smallrye-context-propagation, vertx]

In case that I have undertow together with some blocking security identity augmentor in the project, the authorized requests end with NullPointerException:

```
2023-01-12 11:58:26,226 ERROR [io.und.req.io] (executor-thread-0) Exception handling request a2892aab-b89a-40b8-943a-ddd34d3a9b68-1 to /bug/fruits: java.lang.NullPointerException: Cannot invoke "io.vertx.ext.web.RoutingContext.request()" because "routingContext" is null
	at io.quarkus.resteasy.runtime.ContextUtil.pushContext(ContextUtil.java:19)
	at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.service(ResteasyFilter.java:69)
	at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.sendError(ResteasyFilter.java:76)
	at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:172)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
```

There is no issue without undertow or with non blocking augmentor.

### Expected behavior

no exception shall be thrown

### How to Reproduce?

I have created example [github project](https://github.com/myroch/quarkus-undertow-bug), just start it up in dev mode and try following request:
http://localhost:21380/bug/fruits
Basic Auth: admin/pass

### Quarkus version or git rev

2.15.3

**Comment by sberyozkin** [comment]
@michalvavrik Please have a look when you will be back and have some bandwidth
