### ISSUE TITLE
Reactive Messaging / Kafka - ProtoBuff support

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#3041]
* Add support for ProtoBuff records (for key and payload). 
* Make sure the classes are registered for reflection when needed

**Comment by Dufgui** [comment]
Hello @cescoffier , I create a little test in local and I see this errors:
```
2019-07-13 15:03:34,803 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-2) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - com.google.protobuf.AbstractMessage$Builder
        - com.google.protobuf.AbstractMessageLite$Builder
        - com.google.protobuf.ByteString
        - com.google.protobuf.Descriptors$Descriptor
        - com.google.protobuf.GeneratedMessageV3
        - com.google.protobuf.GeneratedMessageV3$Builder
        - com.google.protobuf.GeneratedMessageV3$FieldAccessorTable
        - com.google.protobuf.Message
        - com.google.protobuf.Message$Builder
        - com.google.protobuf.MessageLite
        - com.google.protobuf.MessageLite$Builder
        - com.google.protobuf.UnknownFieldSet
```

So i update the kafkaProcessor. I think I need a complete test on it with stream to see if it's enought and if it's work

**Comment by tobad357** [comment]
@Dufgui / @cescoffier Any update on this or anything I can help with to get this added?

**Comment by cescoffier** [comment]
The protobuf support should be in its own extension and manage the generation of the classes and registration. 
Same would be required for Avro (even if Avro is a bit more flexible as it support "generic" classes).

**Comment by gaetancollaud** [comment]
I currently have issue with kafka and Protobuf. I tried to register all the classes needed but now I'm stuck with some static field which is package protected. Any clue how I could solve this ?

The static field is:
```
io.spoud.sdm.global.domain.v1.Domain.internal_static_io_spoud_sdm_global_domain_v1_IdPathReference_fieldAccessorTable
```

The complete stacktrace
```
2021-02-16 08:24:06,196 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-2) Uncaught exception received by Vert.x: java.lang.NoSuchFieldError: io.spoud.sdm.global.domain.v1.Domain.internal_static_io_spoud_sdm_global_domain_v1_IdPathReference_fieldAccessorTable
	at io.spoud.sdm.global.domain.v1.IdPathReference.internalGetFieldAccessorTable(IdPathReference.java:92)
	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:764)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1263)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1128)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1052)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1030)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:769)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1263)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1128)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1052)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1030)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:769)
	at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:372)
	at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:382)
	at io.spoud.sdm.elasticsearch.SearchService.addRecord(SearchService.java:74)
```

The classes registered for reflexion:
```
      // ...
      
      io.spoud.sdm.global.domain.v1.Domain.class,
      io.spoud.sdm.global.domain.v1.IdPathReference.class,
      io.spoud.sdm.global.domain.v1.IdPathReference.Builder.class,
            
      com.google.protobuf.AbstractMessage.Builder.class,
      com.google.protobuf.AbstractMessageLite.Builder.class,
      com.google.protobuf.ByteString.class,
      com.google.protobuf.Descriptors.Descriptor.class,
      com.google.protobuf.GeneratedMessageV3.class,
      com.google.protobuf.GeneratedMessageV3.Builder.class,
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable.class,
      com.google.protobuf.Message.class,
      com.google.protobuf.Message.Builder.class,
      com.google.protobuf.MessageLite.class,
      com.google.protobuf.MessageLite.Builder.class,
      com.google.protobuf.UnknownFieldSet.class,
```

**Comment by cescoffier** [comment]
@gaetancollaud Look at the gRPC extension which contain some Protobuf related substitutions.

**Comment by gaetancollaud** [comment]
> @gaetancollaud Look at the gRPC extension which contain some Protobuf related substitutions.

I'm using the grpc extension already. I have some grpc services implemented that works fine.
