### ISSUE TITLE
javax.ws.rs.ProcessingException: Response could not be mapped to type class

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#30465]
### Describe the bug

We are using the Reactive Client to call a service which returns a custom Object (named "GatewayResponse") containing some data needed.
While the called service returns the object as it should, the calling service returns following exception
`19-01-2023 09:38:49,867 | [ERROR] ResteasyReactiveRequestContext.handleUnrecoverableError(621) | Request failed: javax.ws.rs.ProcessingException: Response could not be mapped to type class com.dwitech.kc.beipp.frontend.entity.response.GatewayResponse
	at org.jboss.resteasy.reactive.client.impl.ClientReaderInterceptorContextImpl.proceed(ClientReaderInterceptorContextImpl.java:75)
	at org.jboss.resteasy.reactive.client.impl.ClientSerialisers.invokeClientReader(ClientSerialisers.java:160)
	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.readEntity(RestClientRequestContext.java:185)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.mapToResponse(ClientResponseCompleteRestHandler.java:104)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:35)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:31)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:229)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:279)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

### Expected behavior

The service is correctly called and no exception is thrown

### Actual behavior

I only have the problem with the latest version (2.15.3), I reverted back to the last version I used a month ago (2.14.3) and the problem didn't occur.

### Output of `uname -a` or `ver`

Darwin Daniels-Laptop.fritz.box 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "11.0.17" 2022-10-18 LTS

### Quarkus version or git rev

2.15.3

**Comment by gsmet** [comment]
Could you provide a reproducer? Because I don't think the issue is obvious. Thanks!

**Comment by geoand** [comment]
It would definitely be very useful to have a sample project that exhibits this behavior

**Comment by dwamara** [comment]
I will try my best to produce one.

**Comment by geoand** [comment]
You need to add 

```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive-jsonb</artifactId>
        </dependency>
```

to `bei_pp_frontend` in order to enable json processing for the rest client
