### ISSUE TITLE
Build failed due to limit bean types to types outside of the transitive closure of bean types

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#30540]
### Describe the bug

Our Quarkus QE project does not compile when run against `999-SNAPSHOT`. It must be some recent change as it was fine last week.

caused by https://github.com/quarkusio/quarkus/pull/30447

### Expected behavior

Build succeeds.

### Actual behavior

Build failes with

```bash
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (build) on project http-advanced-reactive: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: javax.enterprise.inject.spi.DefinitionException: Cannot limit bean types to types outside of the transitive closure of bean types. Bean: org.jboss.resteasy.plugins.providers.multipart.MapMultipartFormDataReader illegal bean types: [javax.ws.rs.ext.MessageBodyReader]
[ERROR] 	at io.quarkus.arc.processor.Types.restrictBeanTypes(Types.java:644)
[ERROR] 	at io.quarkus.arc.processor.Types.getClassBeanTypeClosure(Types.java:403)
[ERROR] 	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1121)
[ERROR] 	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:49)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1034)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:256)
[ERROR] 	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:134)
[ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:444)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :http-advanced-reactive

```

### How to Reproduce?

Reproducer:

Steps to reproduce teh behavior:
1. `git clone https://github.com/quarkus-qe/quarkus-test-suite.git`
2. `mvn -T C1 -DskipDocs -DskipTests -DskipITs -DskipExtensionValidation -Dskip.gradle.tests -Dcheckstyle.skip clean install`

### Output of `uname -a` or `ver`

Linux fedora 6.1.5-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jan 12 15:52:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### GraalVM version (if different from Java)

22.3

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by Sgitario** [comment]
The build "Quarkus CI / MicroProfile TCKs Tests (pull_request) " started failing with the same issue. For example, in https://github.com/quarkusio/quarkus/pull/30533

**Comment by michalvavrik** [comment]
reverting https://github.com/quarkusio/quarkus/pull/30447 fixes build, cc @manovotn

**Comment by manovotn** [comment]
@michalvavrik there is a pr that should fix it again, see https://github.com/quarkusio/quarkus/pull/30544

**Comment by michalvavrik** [comment]
ok, thank you

**Comment by gsmet** [comment]
@michalvavrik could you test with https://github.com/quarkusio/quarkus/pull/30544 applied (and https://github.com/quarkusio/quarkus/pull/30447)?

**Comment by michalvavrik** [comment]
tested @gsmet , #30544 fixes our issue
