### ISSUE TITLE
java 17 only extensions fails quarkus create app on java 11

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#30541]
### Describe the bug

since neo4j latest update (https://github.com/quarkiverse/quarkus-neo4j/commit/dd0f7f152c210a73104cb4f34c6fcf29e1f39703) that targets java 17 `quarkus create app -x neo4j` (with or without `--java 11`) fails to build.

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.15.3.Final:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.neo4j.deployment.Neo4jDriverProcessor#configureDriverProducer threw an exception: java.lang.UnsupportedClassVersionError: org/neo4j/driver/Config$ConfigBuilder has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
[ERROR] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[ERROR] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:497)
[ERROR] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:457)
[ERROR] 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[ERROR] 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
[ERROR] 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
[ERROR] 	at io.quarkus.deployment.proxy.ProxyFactory.addMethodsOfClass(ProxyFactory.java:118)
[ERROR] 	at io.quarkus.deployment.proxy.ProxyFactory.addMethodsOfClass(ProxyFactory.java:114)
[ERROR] 	at io.quarkus.deployment.proxy.ProxyFactory.<init>(ProxyFactory.java:67)
[ERROR] 	at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:377)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$57(ExtensionLoader.java:663)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:905)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR]
[ERROR] 	[error]: Build step io.quarkus.neo4j.deployment.Neo4jDriverProcessor#metrics threw an exception: java.lang.UnsupportedClassVersionError: org/neo4j/driver/Config$ConfigBuilder has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
[ERROR] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
```

Question is how we deal with this since neo4j does have a quarkus-neo4j 1.x version available that works with Java 11.

Feels like we at least could warn or error on it not being possible to use java 11

**Comment by gastaldi** [comment]
It would be interesting if extensions could provide the minimum Java info in the extension metadata:

- https://github.com/quarkusio/quarkus/pull/30290

**Comment by geoand** [comment]
This is now out of date as we use Java 17 as the baseline
