### ISSUE TITLE
io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype in v3.0.0.Alpha3 dev mode

### ISSUE THREAD

**Issue by kdubois** [quarkusio/quarkus#30543]
### Describe the bug

When you define a ConfigProperty and forget to set an actual value you get a very convenient error message (when running in Dev Mode) in the UI that shows a form where you can set the value for this missing property.  In the latest v3.0.0.Alpha3 version this appears to be broken.  

The form shows up, but when I enter a value and submit, I get an Internal Server Error served at http://localhost:8080/io.quarkus.vertx-http.devmode.config.fix

The form (note, this is not the bug!)
![Screenshot from 2023-01-23 12-32-50](https://user-images.githubusercontent.com/373537/214030442-3e1c8bfa-1187-47ef-9ac8-87fb2a9eed0b.png)

### Expected behavior

The value of the property is set in your application.properties file

### Actual behavior
![image](https://user-images.githubusercontent.com/373537/214030620-b1562c1b-6361-404b-bcdf-5118b0d3b0e5.png)

2023-01-23 12:32:54,124 ERROR [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-1) Unhandled exception in router: java.lang.RuntimeException: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
        at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.updateConfig(ConfigEditorProcessor.java:258)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$3$1.handle(VertxHttpHotReplacementSetup.java:115)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$3$1.handle(VertxHttpHotReplacementSetup.java:101)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:100)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:64)
        at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
        at io.quarkus.runtime.configuration.ConfigUtils.getProfiles(ConfigUtils.java:273)
        at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.updateConfig(ConfigEditorProcessor.java:218)
        ... 13 more

### How to Reproduce?

1. Create new project: `quarkus create app com.redhat.developers:mytest -P3.0.0.Alpha3`

2. Edit the supplied GreetingResource.java and add 
```    
   @ConfigProperty(name="greeting")
    String greeting;
```
3. Start dev mode `quarkus dev`
4. In your browser, go to localhost:8080/hello
5. Notice the error with the missing property value and the form field to add a value.  Populate with any string and submit
6. You should see an "Internal Server Error"

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment (Red_Hat-17.0.5.0.8-1.fc37) (build 17.0.5+8) OpenJDK 64-Bit Server VM (Red_Hat-17.0.5.0.8-1.fc37) (build 17.0.5+8, mixed mode, sharing)

### Quarkus version or git rev

3.0.0.Alpha3

**Comment by gsmet** [comment]
I can confirm the issue is reproducible.

@radcortez does it ring any bell? I suppose it's a class loading issue somehow but I'm not sure how this could have changed from 2.x to 3.x?

**Comment by radcortez** [comment]
Yes, this is a class loading issue, but also I have no clue what may have caused this. I'll have a look.

**Comment by gsmet** [comment]
I know that I fixed a few of them which were caused by artifacts being declared as parent first which names have changed in the Jakarta charge.
But I don't think that's the case here with SmallRye Config or Eclipse MP.

**Comment by gsmet** [comment]
Not sure if it's important but the config loading is made on the event loop (but I suppose it's available on the event loop?).

**Comment by radcortez** [comment]
I was also able to reproduce this with 2.16.x and higher. The culprit is here:
https://github.com/quarkusio/quarkus/commit/5cf686e7e5da947fbf8c6b362b2ba5d29ae52ea0#diff-7b4bdcfa078d80aa501664b2d6d9f5a34a5b9b62a863e08d913f3dc1b41ae4cc

I'm provide a fix.
