### ISSUE TITLE
gRPC reports the error: io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: GET /

### ISSUE THREAD

**Issue by cmoulliard** [quarkusio/quarkus#30613]
### Describe the bug

The [gRPC quickstart ](https://github.com/quarkusio/quarkus-quickstarts/tree/main/grpc-plain-text-quickstart)generates the following error with Quarkus 2.5.13
```
2023-01-24 09:20:17,432 WARN  [io.qua.grp.run.GrpcServerRecorder] (Quarkus Main Thread) Using legacy gRPC support, with separate new HTTP server instance. Switch to single HTTP server instance usage with quarkus.grpc.server.use-separate-server=false property

2023-01-24 09:20:17,521 INFO  [io.qua.grp.run.GrpcServerRecorder] (Quarkus Main Thread) Registering gRPC reflection service
2023-01-24 09:20:17,655 INFO  [io.qua.grp.run.GrpcServerRecorder] (vert.x-eventloop-thread-0) gRPC Server started on 0.0.0.0:9000 [SSL enabled: false]
2023-01-24 09:20:17,705 INFO  [io.quarkus] (Quarkus Main Thread) grpc-plain-text-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.15.3.Final) started in 2.619s. Listening on: http://localhost:8080
2023-01-24 09:20:17,706 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-01-24 09:20:17,706 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, grpc-client, grpc-server, resteasy-reactive, smallrye-context-propagation, vertx]
2023-01-24 09:20:18,292 INFO  [io.grp.net.Net.connections] (vert.x-eventloop-thread-0) Transport failed: io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: GET /
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:109)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:317)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:247)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
when it is started post compilation step
```

```

### Expected behavior

The gRPC server should be started without any issue

### Actual behavior

gRPC serve fails to start

### How to Reproduce?

1. Git clone: https://github.com/quarkusio/quarkus-quickstarts
2. cd grpc-plain-text-quickstart
3. mvn compile
4. mvn quarkus:dev

### Output of `uname -a` or `ver`

Darwin MacBook-Pro 21.6.0 Darwin Kernel Version 21.6.0

### Output of `java -version`

openjdk version "17"

### Quarkus version or git rev

2.5.13

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.6

**Comment by alesj** [comment]
It doesn't fail for me:
* https://gist.github.com/alesj/d1012b9741a872dc820f754a6b72e20e

But as I see, this quickstart is already using Quarkus 2.16.0.Final ...

**Comment by cmoulliard** [comment]
> But as I see, this quickstart is already using Quarkus 2.16.0.Final ...

Yep. This is fixed since at least 2.16 and impacts some previous versions as: 2.5, ...

**Comment by alesj** [comment]
@cescoffier anything to do wrt older versions? ^^

**Comment by cescoffier** [comment]
No, if it works in 2.13.x, we're good.
