### ISSUE TITLE
quarkiverse jdbc extension error after upgrate to Quarkus 3

### ISSUE THREAD

**Issue by alexeysharandin** [quarkusio/quarkus#30661]
### Describe the bug

After upgrade over ```curl -Ls https://sh.jbang.dev | bash -s - --fresh upgrade-to-quarkus3@quarkusio``` test failed
Please see details below.

### Expected behavior

packaging completed w/o errors

### Actual behavior

exception raised in integration tests: 

```
Caused by: java.lang.NoSuchMethodError: 'void org.hibernate.jpa.boot.internal.PersistenceXmlParser.<init>(org.hibernate.boot.registry.classloading.spi.ClassLoaderService, jakarta.persistence.spi.PersistenceUnitTransactionType)'
        at io.quarkus.hibernate.orm.deployment.QuarkusPersistenceXmlParser.<init>(QuarkusPersistenceXmlParser.java:36)
        at io.quarkus.hibernate.orm.deployment.QuarkusPersistenceXmlParser.locatePersistenceUnits(QuarkusPersistenceXmlParser.java:28)
        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.parsePersistenceXmlDescriptors(HibernateOrmProcessor.java:344)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### How to Reproduce?

Steps to reproduce:
1. ```git clone https://github.com/quarkiverse/quarkus-jdbc-sqlite.git```
2. ```cd quarkus-jdbc-sqlite```
3. ```curl -Ls https://sh.jbang.dev | bash -s - --fresh upgrade-to-quarkus3@quarkusio```
4. ```mvn package```

### Output of `uname -a` or `ver`

Linux 5.10.102.1

### Output of `java -version`

OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by gastaldi** [comment]
@alexeysharandin your project depends on `com.github.gwenn:sqlite-dialect` which brings an older Hibernate version. 

Exclude it and it should work: 

```xml
    <dependency>
      <groupId>com.github.gwenn</groupId>
      <artifactId>sqlite-dialect</artifactId>
      <version>${sqlite-dialect.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.hibernate</groupId>
          <artifactId>hibernate-core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

**Comment by alexeysharandin** [comment]
@gastaldi Hi George! Thanks my friend for quick analysis and response!
Sanne spoke about it few month ago but I missed update to hibernate 6 in quarkus.

will check how to upgrade dialect with him.

BTW: How to upgrade quarkiverse extension for Quarkus 3.x? Have a some guide or by the same way what used for 2.x?

**Comment by gastaldi** [comment]
@alexeysharandin hey, as we suggested in https://groups.google.com/g/quarkus-dev/c/xjHIBk6Mx7k, we recommend creating a separate branch for 2.x releases and use the main branch for 3.x. 

Some extensions are already doing this, like https://github.com/quarkiverse/quarkus-openapi-generator

**Comment by alexeysharandin** [comment]
BTW: looking to bom for [2.16](https://github.com/quarkusio/quarkus/blob/2.16/bom/application/pom.xml#L94) and [3alpha](https://github.com/quarkusio/quarkus/blob/3.0.0.Alpha3/bom/application/pom.xml#L100).
Hibernate version - the same - 5.6.14.Final

As I understood in Quarkus 3.0 upgrade to hibernate 6.x planned. When it's will be done?
For 6.x yes - need to update dialect to [this one](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLiteDialect.java).

@gastaldi any ideas?

**Comment by gastaldi** [comment]
There isn't a target date for 6.2 yet but the plan is to have it in Quarkus 3 when that happens

**Comment by alexeysharandin** [comment]
@Sanne, maybe you can help here. Looks like some methods signatures changed between 3.0 and 2.16 and org.hibernate.jpa.boot.internal

**Comment by Sanne** [comment]
@alexeysharandin which versions are you referring to? We plan to upgrade to Hibernate ORM 6.2 in Quarkus 3 but this change wasn't integrated yet, so it can't possibly affect you; it's still using the same version as Quarkus 2.x

**Comment by alexeysharandin** [comment]
@Sanne, it's about 2.16.x vs 3.0.0.Alpha after using jbang.
You right Hibernate [version](https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L94) the [same](https://github.com/quarkusio/quarkus/blob/3.0.0.Alpha3/bom/application/pom.xml#L100) but error happen.
