### ISSUE TITLE
[Quarkus Native] ClassNotFoundException: com.github.benmanes.caffeine.cache.SSSW

### ISSUE THREAD

**Issue by chberger** [quarkusio/quarkus#30744]
### Describe the bug

Using the Cache API with ``caffeine`` leads to the following exception when running ``Quarkus 2.16.0.Final`` in ```native``` mode:
```
2023-01-31 13:56:54,211 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.SSSW
        at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1132)
        at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1105)
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.loadFactory(LocalCacheFactory.java:84)
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:40)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalAsyncCache.<init>(BoundedLocalCache.java:4216)
        at com.github.benmanes.caffeine.cache.Caffeine.buildAsync(Caffeine.java:1096)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheImpl.<init>(CaffeineCacheImpl.java:71)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheManagerBuilder$1.get(CaffeineCacheManagerBuilder.java:56)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheManagerBuilder$1.get(CaffeineCacheManagerBuilder.java:34)
        at io.quarkus.cache.CacheManager_7ace4235729bbc654ace276b403267860dc707de_Synthetic_Bean.createSynthetic(Unknown Source)
        at io.quarkus.cache.CacheManager_7ace4235729bbc654ace276b403267860dc707de_Synthetic_Bean.create(Unknown Source)
        at io.quarkus.cache.CacheManager_7ace4235729bbc654ace276b403267860dc707de_Synthetic_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
        at io.quarkus.cache.CacheManager_7ace4235729bbc654ace276b403267860dc707de_Synthetic_ClientProxy.arc$delegate(Unknown Source)
        at io.quarkus.cache.CacheManager_7ace4235729bbc654ace276b403267860dc707de_Synthetic_ClientProxy.getCacheNames(Unknown Source)
        at io.quarkus.cache.runtime.CacheManagerInitializer.onStartup(CacheManagerInitializer.java:14)
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.arc.impl.Reflections.invokeMethod(Reflections.java:170)
        at io.quarkus.cache.runtime.CacheManagerInitializer_Observer_onStartup_8dc69ad76cf9cc31e6928ed65580a8d3fd18a734.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:328)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:310)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:78)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### Actual behavior

This issue is related to the ``native`` mode only. The ``JVM`` mode is working just fine. 
It also looks like it's just an issue with ```2.16.0.Final```, with ```2.15.3.Final``` everything works as expected, even in the ``native`` mode.

### How to Reproduce?

1. Define a ``Quarkus 2.16.0.Final`` dependency
2. Add the ``@CacheResult`` annotation to an interceptable method
3. Run your app in ``native`` mode

### Output of `java -version`

openjdk 17.0.2 2022-01-18

### GraalVM version (if different from Java)

GraalVM 22.3.0 Java 17 CE

### Quarkus version or git rev

Quarkus 2.16.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

### Additional information

The native build is conducted with the help of ``quay.io/quarkus/ubi-quarkus-native-image:22.3-java17``

**Comment by gsmet** [comment]
@gwenneg could it be that the default configuration changed with your latest adjusments? Because depending on the defaults, Caffeine will use slightly different classes.

**Comment by gsmet** [comment]
@chberger could you get us a small Maven reproducer? Thanks!

**Comment by chberger** [comment]
Maven reproducer: https://github.com/chberger/quarkus-cache-issue

# quarkus-cache-issue

How to reproduce the issue?

```
mvn package -Pnative -Dquarkus.native.container-build=true
docker run -p 8080:8080 chberger/quarkus-cache-issue:1.0.0-SNAPSHOT
```

When compiling the code in ``JVM`` mode, everything should work:

```
mvn package
docker run -p 8080:8080 chberger/quarkus-cache-issue:1.0.0-SNAPSHOT
```

The same is true when using Quarkus ``2.15.3.Final``.

The issue is somehow related to the following cache configurations:

```
quarkus.cache.caffeine."test".expire-after-write=60M
quarkus.cache.caffeine."test".metrics-enabled=true
```

Without these configs in place, the code works again....

**Comment by gsmet** [comment]
To give you a bit more background:
- Caffeine generates a lot of classes for all the cache configurations so that it's perfectly optimized for each setup.
- We don't register all of them for reflection because the cost in image size is too high: we register only the most common ones.
- If you're using a more exotic cache configuration, you have to register the classes you want following this advice: https://quarkus.io/guides/cache#going-native

Your problem is due to `metrics-enabled` which might have not been supported (or supported differently before) and it now triggers the need for a cache class that we don't enable by default.

I think we should enable these classes by default if we have Micrometer around. I'll have a look at it next week.

In the meantime, just register the class manually as explained in the guide pointed above.

**Comment by ben-manes** [comment]
> “However, to optimize runtime speed, Caffeine embarks many cache implementation classes that are selected depending on the cache configuration.”

Can you please replace “speed” with “memory”? There would otherwise be wasted space due to unused fields, which impacts large caches.

**Comment by gwenneg** [comment]
@gsmet The global cache config hasn't been released yet so this is not related.

The config phase of `CacheConfig` changed from `BUILD_TIME` to `RUN_TIME` in `2.16.0.Final`. The caches were instantiated earlier before that change. Now, they are created by recorded bytecode executed at `RUNTIME_INIT`. I guess this is causing the issue. To be confirmed...

**Comment by gwenneg** [comment]
I missed the comment saying that this happens with `2.15.3.Final` as well.

Maybe `com.github.benmanes.caffeine.cache.SSSW` should simply be added to [CacheConstructorsFeature](https://github.com/quarkusio/quarkus/blob/main/extensions/caffeine/runtime/src/main/java/io/quarkus/caffeine/runtime/graal/CacheConstructorsFeature.java) because it can be needed with a very basic cache config?

**Comment by gsmet** [comment]
It's not only this one. I think we need to record all the metrics-capable ones and I would prefer doing it only if Micrometer is around.
I think I will just drop the feature and do things in the processor. It was a nice optimization while we didn't have conditions but it's going to be annoying now.

**Comment by gwenneg** [comment]
I suppose the classes registration will move from the `caffeine` extension to `cache`.

**Comment by gwenneg** [comment]
Or maybe the old ones will stay there and new ones will be added to `cache` depending on the cache metrics config.

**Comment by manuelwallrapp** [comment]
Having the same issue with: com.github.benmanes.caffeine.cache.PSMW

**Comment by gsmet** [comment]
@ben-manes done here: https://github.com/quarkusio/quarkus/pull/30825

@manuelwallrapp yeah the whole array of classes with metrics are missing. I'll have a closer look either tomorrow or next week.

**Comment by ivansenic** [comment]
I am seeing the same issue with the `I am still seeing the issue with `com.github.benmanes.caffeine.cache.PSAMW`, this one was not covered in linked PR. Any reason why?

**Comment by juangon** [comment]
Another missing class to the list: com.github.benmanes.caffeine.cache.SSSMSAW

**Comment by gsmet** [comment]
@ivansenic @juangon it would be interesting if you could post the cache config leading to these particular classes being needed.

Thanks!

**Comment by juangon** [comment]
Sure @gsmet !, here they are:

```
quarkus.cache.caffeine."my-cache".initial-capacity=100 
quarkus.cache.caffeine."my-cache".maximum-size=1000
quarkus.cache.caffeine."my-cache".expire-after-write=PT1H
quarkus.cache.caffeine."my-cache".expire-after-access=PT1H

quarkus.cache.caffeine."my-cache".metrics-enabled=false
```

As seen in this issue, we are disabling metrics for now. 
Thanks very much!

**Comment by juangon** [comment]
I edited the snippet as the issue was with metrics enabled

**Comment by ivansenic** [comment]
Mine are:

```
quarkus:
  cache:
    caffeine:
      keyspace-cache:
        maximum-size: 1000
        expire-after-access: PT5M
        metrics-enabled: true
```

**Comment by juangon** [comment]
BTW it seems that even after 

`quarkus.cache.caffeine."my-cache".metrics-enabled=false`

issue with `com.github.benmanes.caffeine.cache.SSSMSAW` in native mode persists

**Comment by juangon** [comment]
Another one:
`com.github.benmanes.caffeine.cache.PSAWMW`

**Comment by gsmet** [comment]
I will add the ones you both mentioned but we need to accept that we will never have all of them as otherwise everyone is paying the cost of having these classes includes even if they are not used.

PR to come.

**Comment by ben-manes** [comment]
FYI,
There is no reason to have both expireAfterAccess and expireAfterWrite enabled. At the same value then expireAfterAccess is enough. If different values it’s confusing and using an expiry is preferred. The combination is allowed for Guava compatibility where it was a mistake since it makes little sense.

**Comment by kathirsvn** [comment]
Hi, we are hitting this issue with `com.github.benmanes.caffeine.cache.SSLSMSA` ClassNotFoundException in native mode.
