### ISSUE TITLE
java.lang.IllegalStateException: Exception when closing Vert.x instance

### ISSUE THREAD

**Issue by pdaniel** [quarkusio/quarkus#30770]
### Describe the bug

On a mac os intel processor and also m1 i get an error when a try to run the native build.  I get the same error in docker and also trying to run the native image directly on macos. 

The steps that i followed to build a native image using docker image:

```
quarkus build --native --no-tests -Dquarkus.native.container-build=true

docker build -f src/main/docker/Dockerfile.native -t quarkus/code-with-quarkus .

docker run -i --rm -p 8080:8080 quarkus/code-with-quarkus
```

The error log that i get is :

```
2023-02-01 07:35:44,693 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT native (powered by Quarkus 2.16.0.Final) started in 0.017s. 
2023-02-01 07:35:44,696 INFO  [io.quarkus] (main) Profile prod activated. 
2023-02-01 07:35:44,696 INFO  [io.quarkus] (main) Installed features: [amazon-lambda, cdi, funqy-http, security, smallrye-context-propagation, vertx]
2023-02-01 07:35:44,761 WARN  [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (NORMAL)) Aborting lambda poll loop: ending dev/test mode
2023-02-01 07:35:44,762 ERROR [io.qua.run.StartupContext] (Lambda Thread (NORMAL)) Running a shutdown task failed [Error Occurred After Shutdown]: java.lang.IllegalStateException: Exception when closing Vert.x instance
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder.destroy(VertxCoreRecorder.java:424)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$1.run(VertxCoreRecorder.java:109)
	at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:84)
	at io.quarkus.runtime.StartupContext.close(StartupContext.java:75)
	at io.quarkus.runner.ApplicationImpl.doStop(Unknown Source)
	at io.quarkus.runtime.Application.stop(Application.java:208)
	at io.quarkus.runtime.Application.stop(Application.java:155)
	at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:160)
	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.lang.InterruptedException
	at java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
	at java.base@17.0.6/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder.destroy(VertxCoreRecorder.java:418)
	... 10 more

2023-02-01 07:35:44,763 INFO  [io.quarkus] (Lambda Thread (NORMAL)) code-with-quarkus stopped in 0.001s
```

What could cause this error?

### Output of `uname -a` or `ver`

Darwin Users-MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "19.0.1" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08, mixed mode, sharing)

### Quarkus version or git rev

2.16.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by pdaniel** [comment]
anyone ? The quarkus framework is marketed as a framework built for native, but it does not seems to work? Any ideas?

**Comment by cescoffier** [comment]
The exception informs you that the graceful shutdown took more time than expected, and Quarkus interrupted the threads waiting. 

Do you have a reproducer so we can check what's going on in your case?

**Comment by cescoffier** [comment]
Also, you are using GraalVM using Java 19? Did you try with 17?

**Comment by pdaniel** [comment]
Here is a link to a simple project that is causing this error 

https://github.com/pdaniel/quarkus-test

**Comment by cescoffier** [comment]
The stack trace is not right, but it is expected.

Your application cannot run like that (without being deployed on lambda). So, Quarkus terminates the AWS lambda poll thread:

```
2023-02-07 07:44:31,574 WARN  [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (NORMAL)) Aborting lambda poll loop: ending dev/test mode
```

**Comment by pdaniel** [comment]
I had a feeling that this could be the case. But when I run it on lambda, as native executable or docker lambda with native executable in docker I get another problem discussed here

https://github.com/quarkusio/quarkus/issues/30770

**Comment by JosephBineesh** [comment]
I am also facing the same issue. I just start using this framework for aws lambda and end up with this error. Any hope?

**Comment by cescoffier** [comment]
It's just noise, it should not be an issue.
