### ISSUE TITLE
Kubernetes client extension: JsonMappingException in native mode

### ISSUE THREAD

**Issue by fstab** [quarkusio/quarkus#3077]
I created a minimal project with the new Fabric8 Kubernetes Client extension. When I watch Pods, I get the following error:

```
Could not deserialize watch event: ...
com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:v1#Pod
 at [Source: (String)"{"type":"ADDED","object":{"kind":"Pod","apiVersion":"v1","metadata":{"name":"operator-example-7fb6446744-969t5","generateName":"operator-example-7fb6446744-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/operator-example-7fb6446744-969t5","uid":"2d6e35d4-9d6a-11e9-ab7b-0242e3a6ea5b","resourceVersion":"4772","creationTimestamp":"2019-07-03T08:11:36Z","labels":{"app":"operator-example","pod-template-hash":"7fb6446744"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaS"[truncated 2069 chars]; line: 1, column: 2567] (through reference chain: io.fabric8.kubernetes.api.model.WatchEvent["object"])
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1718)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:78)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:32)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
        at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager.readWatchEvent(WatchHTTPManager.java:293)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:224)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

This is reproducable with the following minimal Java code:

```java
package com.instana.operator.example;

import io.fabric8.kubernetes.api.model.Pod;
import io.fabric8.kubernetes.client.DefaultKubernetesClient;
import io.fabric8.kubernetes.client.KubernetesClient;
import io.fabric8.kubernetes.client.KubernetesClientException;
import io.fabric8.kubernetes.client.Watcher;
import io.quarkus.runtime.StartupEvent;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;

@ApplicationScoped
public class PodWatcher {

  void onStartup(@Observes StartupEvent _ev) {
    new Thread(this::watchPods).start();
  }

  private void watchPods() {
    KubernetesClient client = new DefaultKubernetesClient().inNamespace("default");
    client.pods().watch(new Watcher<Pod>() {
      @Override
      public void eventReceived(Action action, Pod pod) {
        System.out.println("Received " + action + " event for Pod " + pod.getMetadata().getName());
      }

      @Override
      public void onClose(KubernetesClientException e) {
        e.printStackTrace();
        System.exit(-1);
      }
    });
  }
}
```
The code works when I run it on the JVM instead of native mode.

**Comment by fstab** [comment]
[pod-watcher.tar.gz](https://github.com/quarkusio/quarkus/files/3353942/pod-watcher.tar.gz)
Attaching the example project to reproduce. The `deploy/` directory contains the necessary deployment yamls.

**Comment by gsmet** [comment]
@geoand this one is for you :).

**Comment by geoand** [comment]
I'll take a look!

**Comment by geoand** [comment]
It looks like a "problem" in the Kubernetes Client which tries to dynamically load classes upon deserialization. 
I'll see if we can fix it here with some kind of substitution, otherwise we'll need to take care of it upstream.

**Comment by geoand** [comment]
@fstab #3085 should take care of your issue (I tested it with your reproducer)

**Comment by fstab** [comment]
Great, thanks!

**Comment by geoand** [comment]
You are welcome!

**Comment by geoand** [comment]
I would suggest opening a new issue with a reproducer project
