### ISSUE TITLE
Cannot deploy applications into OpenShift using `quarkus.kubernetes.deploy=true`

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#30951]
### Describe the bug

In 999-SNAPSHOT,  we cannot deploy applications using the property `quarkus.kubernetes.deploy=true`. The build fails with:

```
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Selecting target 'openshift' since it has the highest priority among the implicitly enabled deployment targets
[WARNING] [io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider] Default DNS servers: [/[2001:4860:4860:0:0:0:0:8888]:53, /[2001:4860:4860:0:0:0:0:8844]:53] (Google Public DNS as a fallback)
[WARNING] There are multiple httpclient implementation in the classpath, choosing the first non-default implementation. You should exclude dependencies that aren't needed or use an explicit association of the HttpClient.Factory.
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] The decompiled output can be found at: /home/jcarvaja/sources/personal/quarkus-examples/openshift/target/decompiled
[INFO] Adding existing ConfigMap with name: app-config.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.123 s
[INFO] Finished at: 2023-02-07T14:10:09+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project openshift: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy threw an exception: java.lang.RuntimeException: Although a Kubernetes deployment was requested, it however cannot take place because there was an error during communication with the API Server at 'https://c115-e.eu-de.containers.cloud.ibm.com:31364/'
[ERROR]         at io.quarkus.kubernetes.deployment.KubernetesDeploy.doCheck(KubernetesDeploy.java:81)
[ERROR]         at io.quarkus.kubernetes.deployment.KubernetesDeploy.check(KubernetesDeploy.java:31)
[ERROR]         at io.quarkus.kubernetes.deployment.KubernetesDeployer.deploy(KubernetesDeployer.java:117)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[ERROR]         at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:129)
[ERROR]         at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:122)
[ERROR]         at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.restCall(OperationSupport.java:791)
[ERROR]         at io.fabric8.kubernetes.client.impl.BaseClient.getVersionInfo(BaseClient.java:265)
[ERROR]         at io.fabric8.kubernetes.client.impl.KubernetesClientImpl.getVersion(KubernetesClientImpl.java:591)
[ERROR]         at io.quarkus.kubernetes.deployment.KubernetesDeploy.doCheck(KubernetesDeploy.java:62)
[ERROR]         ... 13 more
[ERROR] Caused by: java.io.IOException: Failed to resolve 'c115-e.eu-de.containers.cloud.ibm.com' and search domain query for configured domains failed as well: [redhat.com]
[ERROR]         at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:535)
[ERROR]         at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:558)
[ERROR]         at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.restCall(OperationSupport.java:784)
[ERROR]         ... 16 more
[ERROR] Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'c115-e.eu-de.containers.cloud.ibm.com' and search domain query for configured domains failed as well: [redhat.com]
[ERROR]         at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1069)
[ERROR]         at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1022)
[ERROR]         at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
[ERROR]         at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:66)
[ERROR]         at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:489)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
[ERROR]         at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:256)
[ERROR]         at io.netty.resolver.dns.DnsQueryContext.onQueryWriteCompletion(DnsQueryContext.java:193)
[ERROR]         at io.netty.resolver.dns.DnsQueryContext.access$200(DnsQueryContext.java:43)
[ERROR]         at io.netty.resolver.dns.DnsQueryContext$3.operationComplete(DnsQueryContext.java:185)
[ERROR]         at io.netty.resolver.dns.DnsQueryContext$3.operationComplete(DnsQueryContext.java:182)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
[ERROR]         at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
[ERROR]         at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
[ERROR]         at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:723)
[ERROR]         at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:308)
[ERROR]         at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:288)
[ERROR]         at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:158)
[ERROR]         at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
[ERROR]         at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
[ERROR]         at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
[ERROR]         at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
[ERROR]         at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
[ERROR]         at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
[ERROR]         at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
[ERROR]         at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
[ERROR]         at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.flushQueries(DnsNameResolver.java:1249)
[ERROR]         at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:361)
[ERROR]         at io.netty.resolver.dns.DnsResolveContext.doSearchDomainQuery(DnsResolveContext.java:284)
[ERROR]         at io.netty.resolver.dns.DnsAddressResolveContext.doSearchDomainQuery(DnsAddressResolveContext.java:96)
[ERROR]         at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:249)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1150)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached(DnsNameResolver.java:1123)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.doResolveUncached(DnsNameResolver.java:1025)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:967)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:804)
[ERROR]         at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[ERROR]         at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:100)
[ERROR]         at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:66)
[ERROR]         at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:51)
[ERROR]         at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[ERROR]         at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[ERROR]         at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[ERROR]         at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[ERROR]         at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
[ERROR]         at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
[ERROR]         at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:155)
[ERROR]         at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:106)
[ERROR]         at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:92)
[ERROR]         at io.vertx.core.net.impl.NetClientImpl.connectInternal2(NetClientImpl.java:273)
[ERROR]         at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$1(NetClientImpl.java:240)
[ERROR]         at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
[ERROR]         at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
[ERROR]         at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
[ERROR]         at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
[ERROR]         at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
[ERROR]         at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
[ERROR]         at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
[ERROR]         at io.vertx.core.impl.future.FixedMapping.onSuccess(FixedMapping.java:31)
[ERROR]         at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
[ERROR]         at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
[ERROR]         at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
[ERROR]         at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
[ERROR]         at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
[ERROR]         at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
[ERROR]         at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
[ERROR]         at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
[ERROR]         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[ERROR]         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[ERROR]         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[ERROR]         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[ERROR]         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[ERROR]         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[ERROR]         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] Caused by: io.netty.resolver.dns.DnsNameResolverException: [/[2001:4860:4860:0:0:0:0:8844]:53] failed to send a query via UDP (no stack trace available)
[ERROR] Caused by: java.net.SocketException: La red es inaccesible
[ERROR]         at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
[ERROR]         at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:901)
[ERROR]         at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:863)
[ERROR]         at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:821)
[ERROR]         at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:297)
[ERROR]         at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:143)
[ERROR]         at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
[ERROR]         at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
[ERROR]         at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
[ERROR]         at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
[ERROR]         at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
[ERROR]         at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
[ERROR]         at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
[ERROR]         at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
[ERROR]         at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.flushQueries(DnsNameResolver.java:1249)
[ERROR]         at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:361)
[ERROR]         at io.netty.resolver.dns.DnsResolveContext.doSearchDomainQuery(DnsResolveContext.java:284)
[ERROR]         at io.netty.resolver.dns.DnsAddressResolveContext.doSearchDomainQuery(DnsAddressResolveContext.java:96)
[ERROR]         at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:249)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1150)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached(DnsNameResolver.java:1123)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.doResolveUncached(DnsNameResolver.java:1025)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:967)
[ERROR]         at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:804)
[ERROR]         at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[ERROR]         at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:100)
[ERROR]         at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:66)
[ERROR]         at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:51)
[ERROR]         at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[ERROR]         at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[ERROR]         at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[ERROR]         at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[ERROR]         at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
[ERROR]         at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
[ERROR]         at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:155)
[ERROR]         at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:106)
[ERROR]         at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:92)
[ERROR]         at io.vertx.core.net.impl.NetClientImpl.connectInternal2(NetClientImpl.java:273)
[ERROR]         at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$1(NetClientImpl.java:240)
[ERROR]         at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
[ERROR]         at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
[ERROR]         at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
[ERROR]         at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
[ERROR]         at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
[ERROR]         at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
[ERROR]         at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
[ERROR]         at io.vertx.core.impl.future.FixedMapping.onSuccess(FixedMapping.java:31)
[ERROR]         at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
[ERROR]         at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
[ERROR]         at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
[ERROR]         at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
[ERROR]         at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
[ERROR]         at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
[ERROR]         at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
[ERROR]         at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
[ERROR]         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[ERROR]         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[ERROR]         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[ERROR]         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[ERROR]         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[ERROR]         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[ERROR]         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833): Unknown host Failed to resolve 'c115-e.eu-de.containers.cloud.ibm.com' and search domain query for configured domains failed as well: [redhat.com]
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

```

### Expected behavior

This should work as done in 2.16.1.Final. 

### How to Reproduce?

1.- git clone `https://github.com/Sgitario/quarkus-examples`
2.- cd quarkus-examples/openshift
3.- Log into a remote OpenShift cluster
4.- Run `mvn clean install -DskipTests -Dquarkus.kubernetes.deploy=true`

**Comment by Sgitario** [comment]
@manusa I guess this is related to the changes in https://github.com/quarkusio/quarkus/pull/30480

**Comment by geoand** [comment]
Ah, this is a classic issue with Vert.x. I'll have a look

**Comment by geoand** [comment]
You are welcome!

Best keep this one in mind in case someone comes across the issue with the client outside of Quarkus

**Comment by Sgitario** [comment]
> `Classic Vert.x` sweat_smile
> 
> Glad that you figured this out so quickly I would have been really lost here. Thx @geoand !

haha I was also trying to figure out how we could fix this until I read `Class Vert.x` ... 
Awesome Georgios!

**Comment by manusa** [comment]
> Best keep this one in mind in case someone comes across the issue with the client outside of Quarkus

So shall we do this here too?

https://github.com/fabric8io/kubernetes-client/blob/55357e1692ac3e5b2c9de2807dbfe6296b15b32e/httpclient-vertx/src/main/java/io/fabric8/kubernetes/client/vertx/VertxHttpClientFactory.java#L26

**Comment by geoand** [comment]
I personally would, it's the least surprising behavior
