### ISSUE TITLE
Mongodb native apps built with JDK20 based GraalVM / Mandrel crash

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#30957]
### Describe the bug

$title

cc @Karm @jerboaa 

### Expected behavior

Application should not crash.

### Actual behavior

Application crashes with:

```
java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2707)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:111)
	at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:45)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$3.getPid(Processes.java:242)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:80)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:61)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:177)
	at de.flapdoodle.embed.process.runtime.ProcessControl.fromCommandLine(ProcessControl.java:173)
	at de.flapdoodle.embed.process.runtime.NUMA.isNUMAOnce(NUMA.java:57)
	at de.flapdoodle.embed.process.runtime.NUMA.lambda$isNUMA$0(NUMA.java:48)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
	at de.flapdoodle.embed.process.runtime.NUMA.isNUMA(NUMA.java:48)
	at de.flapdoodle.embed.mongo.commands.MongodArguments.warpWithNumaSupport(MongodArguments.java:191)
	at de.flapdoodle.embed.mongo.commands.MongodArguments.asArguments(MongodArguments.java:116)
	at de.flapdoodle.embed.mongo.transitions.MongodProcessArguments.result(MongodProcessArguments.java:97)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:62)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:50)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:165)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:69)
	at de.flapdoodle.embed.mongo.transitions.Mongod.start(Mongod.java:90)
	at io.quarkus.test.mongodb.MongoTestResource.start(MongoTestResource.java:71)
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:481)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### How to Reproduce?

1. Build GraalVM / Mandrel using JDK 20 EA
2. Set GRAALVM_HOME to point to the build
3. `./mvnw clean verify -Dtest-containers -Dstart-containers -Dformat.skip -Dno-descriptor-tests -Dnative -Dquarkus.native.container-build=false -pl integration-tests/mongodb-client`

### GraalVM version (if different from Java)

23.0-dev based on JDK 20

### Additional information

The issue is expected to be resolved once flapdoodle adds support for JDK 20

https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/6075c6018cfac63bf1f9b0c8a662f773dd2cce49/src/main/java/de/flapdoodle/embed/process/runtime/Processes.java#L58-L68

**Comment by jerboaa** [comment]
I've filed this upstream flapdoodle issue:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues/137

**Comment by michaelmosmann** [comment]
@jerboaa @zakkak .. new release ahead .. 4.4.1 should fix this.
