### ISSUE TITLE
PanacheHibernateCommonResourceProcessor: NoClassDefFoundError: javax/persistence/Transient

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#30990]
### Describe the bug

As I'm running Hibernate ORM tests, there are lots of errors being logged in the background:

```
Caused by: java.lang.NoClassDefFoundError: javax/persistence/Transient
	at io.quarkus.panache.common.deployment.PanacheHibernateCommonResourceProcessor.<clinit>(PanacheHibernateCommonResourceProcessor.java:29)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at io.quarkus.deployment.util.ServiceUtil.classesNamedIn(ServiceUtil.java:29)

```

I guess Panache is generating some code somewhere which is meant to use `@javax.persistence.Transient`, this needs to be migrated to Jakarta.

**Comment by gsmet** [comment]
`PanacheHibernateCommonResourceProcessor` uses a Jakarta class. And it wouldn't build at all if it hadn't been migrated as it's in the `<clinit>`.
I suspect you have some old javax jars around.

**Comment by Sanne** [comment]
Right, I also checked and I see the sources are pointing to the right symbol - this seems to suggest the build order is wrong.

**Comment by gsmet** [comment]
Removed the `area/jakarta` label as if there is a problem it's not related to the Jakarta migration per se.

**Comment by Sanne** [comment]
good point, thanks. I'll adapt the title too.

**Comment by yrodiere** [comment]
Honestly, looking at the dependency tree I have no idea how you could have ended up in this situation, except perhaps with weird builds (forgot a `-am` in a Maven command maybe?)

More to the point, the build seems to work right now, so it's unlikely to be worth our time to investigate this IMO. Let's close the issue, unless you intend to provide a reproducer or to spend time on it yourself?
