### ISSUE TITLE
resteasy-reactive-jaxb does not seperate RootElements by endpoint

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#31032]
### Describe the bug

In my app I have multiple endpoints.
They each return jaxb.

Some of the JAXB Types accidently got the same name over the last few years.

With resteasy classic this works, however with resteasy reactive it does not.

On each POST request I get the exception from below.

I believe this happens becase every found XMLRoot is put into the same JAXBContext.
https://github.com/quarkusio/quarkus/blob/89fcdc9331f9857606ea9cf89666c73be3c1b16a/extensions/jaxb/runtime/src/main/java/io/quarkus/jaxb/runtime/JaxbContextProducer.java#L26-L46

With resteasy classic, each endpoint got its own (cached) JAXBContext, so that problem did not happen.
Entry point is, I believe, this interface:
https://github.com/resteasy/resteasy/blob/main/providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/JAXBContextFinder.java

### Expected behavior

properly create separate JAXBContext for each endpoint and cache each of them.

### Actual behavior

```
2023-02-09 11:25:47,780 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: java.lang.RuntimeException: com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 2 counts of IllegalAnnotationExceptions
Zwei Klassen haben denselben XML-Typnamen"enum". Verwenden Sie @XmlType.name und @XmlType.namespace, um ihnen unterschiedliche Namen zuzuweisen.
        this problem is related to the following location:
                at org.acme.model2.Enum
                at public org.acme.model2.Enum org.acme.model2.Root.getEnum2()
                at org.acme.model2.Root
        this problem is related to the following location:
                at org.acme.model1.Enum
                at public org.acme.model1.Enum org.acme.model1.Root.getEnum1()
                at org.acme.model1.Root
Zwei Klassen haben denselben XML-Typnamen"root". Verwenden Sie @XmlType.name und @XmlType.namespace, um ihnen unterschiedliche Namen zuzuweisen.
        this problem is related to the following location:
                at org.acme.model2.Root
        this problem is related to the following location:
                at org.acme.model1.Root

        at io.quarkus.jaxb.runtime.JaxbContextProducer.jaxbContext(JaxbContextProducer.java:44)
        at io.quarkus.jaxb.runtime.JaxbContextProducer_ProducerMethod_jaxbContext_bd8f21cf3f403916a32bb5db1dc1007aab351487_Bean.create(Unknown Source)
        at io.quarkus.jaxb.runtime.JaxbContextProducer_ProducerMethod_jaxbContext_bd8f21cf3f403916a32bb5db1dc1007aab351487_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
        at io.quarkus.jaxb.runtime.JaxbContextProducer_ProducerMethod_jaxbContext_bd8f21cf3f403916a32bb5db1dc1007aab351487_Bean.get(Unknown Source)
        at io.quarkus.jaxb.runtime.JaxbContextProducer_ProducerMethod_jaxbContext_bd8f21cf3f403916a32bb5db1dc1007aab351487_Bean.get(Unknown Source)
        at io.quarkus.jaxb.runtime.JaxbContextProducer_ProducerMethod_unmarshaller_35a6e3c7bcfff544e73a054dc57f75665b05075c_Bean.create(Unknown Source)
        at io.quarkus.jaxb.runtime.JaxbContextProducer_ProducerMethod_unmarshaller_35a6e3c7bcfff544e73a054dc57f75665b05075c_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:74)
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:30)
        at javax.xml.bind.JaxbContextProducer_ProducerMethod_unmarshaller_35a6e3c7bcfff544e73a054dc57f75665b05075c_ClientProxy.arc$delegate(Unknown Source)
        at javax.xml.bind.JaxbContextProducer_ProducerMethod_unmarshaller_35a6e3c7bcfff544e73a054dc57f75665b05075c_ClientProxy.unmarshal(Unknown Source)
        at io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyReader.unmarshal(ServerJaxbMessageBodyReader.java:64)
        at io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyReader.doReadFrom(ServerJaxbMessageBodyReader.java:76)
        at io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyReader.readFrom(ServerJaxbMessageBodyReader.java:36)
        at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:122)
        at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:81)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 2 counts of IllegalAnnotationExceptions
Zwei Klassen haben denselben XML-Typnamen"enum". Verwenden Sie @XmlType.name und @XmlType.namespace, um ihnen unterschiedliche Namen zuzuweisen.
        this problem is related to the following location:
                at org.acme.model2.Enum
                at public org.acme.model2.Enum org.acme.model2.Root.getEnum2()
                at org.acme.model2.Root
        this problem is related to the following location:
                at org.acme.model1.Enum
                at public org.acme.model1.Enum org.acme.model1.Root.getEnum1()
                at org.acme.model1.Root
Zwei Klassen haben denselben XML-Typnamen"root". Verwenden Sie @XmlType.name und @XmlType.namespace, um ihnen unterschiedliche Namen zuzuweisen.
        this problem is related to the following location:
                at org.acme.model2.Root
        this problem is related to the following location:
                at org.acme.model1.Root

        at com.sun.xml.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:76)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:441)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:273)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1126)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:135)
        at com.sun.xml.bind.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:35)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:393)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at io.quarkus.jaxb.runtime.JaxbContextProducer.jaxbContext(JaxbContextProducer.java:42)
        ... 30 more

```

### How to Reproduce?

Reproducer: 
[rr-jaxb-multi.zip](https://github.com/quarkusio/quarkus/files/10696175/rr-jaxb-multi.zip)

1. mvn clean compile quarkus:dev 
2.` curl -X POST http://localhost:8080/hello/root2 -H "Content-Type: application/xml" -d '<root></root>'  `
3. Look in the terminal where quarkus was started, the exception happend
4. Stop quarkus. Change the dependencies from quarkus-resteasy-reactive-jaxb to quarkus-resteasy-jaxb
5. mvn clean compile quarkus:dev 
6. curl -X POST http://localhost:8080/hello/root2 -H "Content-Type: application/xml" -d '<root></root>'  
7. No exception

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19044 NANBCHL9NG3 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys

### Output of `java -version`

openjdk 17.0.4 2022-07-19 OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)

### Quarkus version or git rev

2.16.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\eclipse\tools\java\maven Java version: 17.0.4, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\17 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Sgitario** [comment]
I'm having a look into this issue

**Comment by Sgitario** [comment]
https://github.com/quarkusio/quarkus/pull/31043 should address this issue.
