### ISSUE TITLE
Unable to launch test on lambda starter code

### ISSUE THREAD

**Issue by aleboulanger** [quarkusio/quarkus#31052]
### Describe the bug

I download a starter quarks project with AWS lambda and DynamoDB selected

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/35097656/217940023-4f1b633a-59d3-4b44-a505-d84ad0e07a95.png">

When I tried to launch the unit test I have the issue below

`    ~/Downloads/code-with-quarkus-3  ./mvnw test                                                                                                                                          ✔
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 59925  100 59925    0     0   668k      0 --:--:-- --:--:-- --:--:--  713k
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/platform/quarkus-maven-plugin/2.16.2.Final/quarkus-maven-plugin-2.16.2.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/platform/quarkus-maven-plugin/2.16.2.Final/quarkus-maven-plugin-2.16.2.Final.pom (7.3 kB at 25 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-project-core-extension-codestarts/2.16.2.Final/quarkus-project-core-extension-codestarts-2.16.2.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-project-core-extension-codestarts/2.16.2.Final/quarkus-project-core-extension-codestarts-2.16.2.Final.pom (3.1 kB at 49 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-all/2.16.2.Final/quarkus-devtools-all-2.16.2.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-all/2.16.2.Final/quarkus-devtools-all-2.16.2.Final.pom (998 B at 11 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-common/2.16.2.Final/quarkus-devtools-common-2.16.2.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-common/2.16.2.Final/quarkus-devtools-common-2.16.2.Final.pom (5.8 kB at 181 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-registry-client/2.16.2.Final/quarkus-devtools-registry-client-2.16.2.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-registry-client/2.16.2.Final/quarkus-devtools-registry-client-2.16.2.Final.pom (2.2 kB at 21 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-message-writer/2.16.2.Final/quarkus-devtools-message-writer-2.16.2.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-message-writer/2.16.2.Final/quarkus-devtools-message-writer-2.16.2.Final.pom (777 B at 29 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-base-codestarts/2.16.2.Final/quarkus-devtools-base-codestarts-2.16.2.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-base-codestarts/2.16.2.Final/quarkus-devtools-base-codestarts-2.16.2.Final.pom (911 B at 25 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-codestarts/2.16.2.Final/quarkus-devtools-codestarts-2.16.2.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-codestarts/2.16.2.Final/quarkus-devtools-codestarts-2.16.2.Final.pom (2.2 kB at 68 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/qute/qute-core/2.16.2.Final/qute-core-2.16.2.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/qute/qute-core/2.16.2.Final/qute-core-2.16.2.Final.pom (1.2 kB at 39 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/qute/qute-parent/2.16.2.Final/qute-parent-2.16.2.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/qute/qute-parent/2.16.2.Final/qute-parent-2.16.2.Final.pom (19 kB at 345 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/platform/quarkus-maven-plugin/2.16.2.Final/quarkus-maven-plugin-2.16.2.Final.jar
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-project-core-extension-codestarts/2.16.2.Final/quarkus-project-core-extension-codestarts-2.16.2.Final.jar
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-common/2.16.2.Final/quarkus-devtools-common-2.16.2.Final.jar
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-registry-client/2.16.2.Final/quarkus-devtools-registry-client-2.16.2.Final.jar
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-message-writer/2.16.2.Final/quarkus-devtools-message-writer-2.16.2.Final.jar
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-message-writer/2.16.2.Final/quarkus-devtools-message-writer-2.16.2.Final.jar (6.3 kB at 44 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-base-codestarts/2.16.2.Final/quarkus-devtools-base-codestarts-2.16.2.Final.jar
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-registry-client/2.16.2.Final/quarkus-devtools-registry-client-2.16.2.Final.jar (216 kB at 654 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-codestarts/2.16.2.Final/quarkus-devtools-codestarts-2.16.2.Final.jar
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-common/2.16.2.Final/quarkus-devtools-common-2.16.2.Final.jar (273 kB at 766 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/qute/qute-core/2.16.2.Final/qute-core-2.16.2.Final.jar
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/platform/quarkus-maven-plugin/2.16.2.Final/quarkus-maven-plugin-2.16.2.Final.jar (451 kB at 1.2 MB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-project-core-extension-codestarts/2.16.2.Final/quarkus-project-core-extension-codestarts-2.16.2.Final.jar (255 kB at 670 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-codestarts/2.16.2.Final/quarkus-devtools-codestarts-2.16.2.Final.jar (84 kB at 181 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-devtools-base-codestarts/2.16.2.Final/quarkus-devtools-base-codestarts-2.16.2.Final.jar (394 kB at 784 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/qute/qute-core/2.16.2.Final/qute-core-2.16.2.Final.jar (305 kB at 572 kB/s)
[INFO]
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- quarkus-maven-plugin:2.16.2.Final:generate-code (default) @ code-with-quarkus ---
Downloading from central: https://repo1.maven.org/maven2/org/acme/code-with-quarkus/1.0.0-SNAPSHOT/maven-metadata.xml
Downloading from redshift: https://s3.amazonaws.com/redshift-maven-repository/release/org/acme/code-with-quarkus/1.0.0-SNAPSHOT/maven-metadata.xml
Downloading from snapshots: https://artifacts-zl.talend.com/nexus/content/repositories/snapshots/org/acme/code-with-quarkus/1.0.0-SNAPSHOT/maven-metadata.xml
Downloading from sonatype.snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/acme/code-with-quarkus/1.0.0-SNAPSHOT/maven-metadata.xml
Downloading from TalendOpenSourceRelease: https://artifacts-oss.talend.com/nexus/content/repositories/TalendOpenSourceRelease/org/acme/code-with-quarkus/1.0.0-SNAPSHOT/maven-metadata.xml
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ code-with-quarkus ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/aurelienleboulanger/Downloads/code-with-quarkus-3/target/classes
[INFO]
[INFO] --- quarkus-maven-plugin:2.16.2.Final:generate-code-tests (default) @ code-with-quarkus ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/aurelienleboulanger/Downloads/code-with-quarkus-3/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ code-with-quarkus ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/aurelienleboulanger/Downloads/code-with-quarkus-3/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M7:test (default-test) @ code-with-quarkus ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.lambda.LambdaHandlerTest
2023-02-09 22:07:20,328 WARN  [io.net.res.dns.DnsServerAddressStreamProviders] (build-19) Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'
2023-02-09 22:07:20,468 INFO  [io.qua.ama.lam.run.MockEventServer] (build-19) Mock Lambda Event Server Started
2023-02-09 22:07:21,080 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-15) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2023-02-09 22:07:21,405 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-15) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2023-02-09 22:07:21,407 INFO  [org.tes.DockerClientFactory] (build-15) Docker host IP address is localhost
2023-02-09 22:07:21,424 INFO  [org.tes.DockerClientFactory] (build-15) Connected to docker:
  Server Version: 20.10.22
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 7859 MB
2023-02-09 22:07:21,434 INFO  [org.tes.uti.ImageNameSubstitutor] (build-15) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2023-02-09 22:07:21,437 INFO  [org.tes.DockerClientFactory] (build-15) Checking the system...
2023-02-09 22:07:21,438 INFO  [org.tes.DockerClientFactory] (build-15) ✔︎ Docker server version should be at least 1.6.0
2023-02-09 22:07:21,488 INFO  [🐳 [localstack/localstack:latest]] (build-15) HOSTNAME_EXTERNAL environment variable set to localstack-bzzzk (to match last network alias on container with non-default network)
2023-02-09 22:07:21,490 INFO  [🐳 [localstack/localstack:latest]] (build-15) Creating container for image: localstack/localstack:latest
2023-02-09 22:07:22,119 INFO  [org.tes.uti.RegistryAuthLocator] (build-15) Credential helper/store (docker-credential-desktop) does not have credentials for https://index.docker.io/v1/
2023-02-09 22:07:22,125 INFO  [🐳 .3.4]] (build-15) Creating container for image: testcontainers/ryuk:0.3.4
2023-02-09 22:07:22,194 INFO  [🐳 .3.4]] (build-15) Container testcontainers/ryuk:0.3.4 is starting: eb54d259f98b6d55dba2c2c6738aa2786c142507798121977ff2d817749344e1
2023-02-09 22:07:22,486 INFO  [🐳 .3.4]] (build-15) Container testcontainers/ryuk:0.3.4 started in PT0.361377S
2023-02-09 22:07:22,991 INFO  [🐳 [localstack/localstack:latest]] (build-15) Container localstack/localstack:latest is starting: 327de906aebb1756aa740cfbb102427633e8278285cd78e9413e6fefc24db512
2023-02-09 22:07:27,306 INFO  [🐳 [localstack/localstack:latest]] (build-15) Container localstack/localstack:latest started in PT5.81664S
2023-02-09 22:07:27,309 INFO  [io.qua.ama.com.dep.DevServicesLocalStackProcessor] (build-15) Amazon Dev Services for localstack (dynamodb) started. Other Quarkus applications in dev mode will find the LocalStack automatically.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.299 s <<< FAILURE! - in org.acme.lambda.LambdaHandlerTest
[ERROR] org.acme.lambda.LambdaHandlerTest.testSimpleLambdaSuccess  Time elapsed: 0.004 s  <<< ERROR!
java.lang.RuntimeException:
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor#setup threw an exception: javax.enterprise.inject.spi.DeploymentException: Missing 'software.amazon.awssdk:url-connection-client' dependency on the classpath
	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.missingDependencyException(AmazonServicesClientsProcessor.java:173)
	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.setup(AmazonServicesClientsProcessor.java:122)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:625)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:696)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor#setup threw an exception: javax.enterprise.inject.spi.DeploymentException: Missing 'software.amazon.awssdk:url-connection-client' dependency on the classpath
	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.missingDependencyException(AmazonServicesClientsProcessor.java:173)
	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.setup(AmazonServicesClientsProcessor.java:122)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:222)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:592)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:640)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	... 37 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor#setup threw an exception: javax.enterprise.inject.spi.DeploymentException: Missing 'software.amazon.awssdk:url-connection-client' dependency on the classpath
	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.missingDependencyException(AmazonServicesClientsProcessor.java:173)
	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.setup(AmazonServicesClientsProcessor.java:122)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	... 48 more
Caused by: javax.enterprise.inject.spi.DeploymentException: Missing 'software.amazon.awssdk:url-connection-client' dependency on the classpath
	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.missingDependencyException(AmazonServicesClientsProcessor.java:173)
	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.setup(AmazonServicesClientsProcessor.java:122)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   LambdaHandlerTest.testSimpleLambdaSuccess » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor#setup threw an exception: javax.enterprise.inject.spi.DeploymentException: Missing 'software.amazon.awssdk:url-connection-client' dependency on the classpath
	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.missingDependencyException(AmazonServicesClientsProcessor.java:173)
	at io.quarkus.amazon.common.deployment.AmazonServicesClientsProcessor.setup(AmazonServicesClientsProcessor.java:122)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0`

### Expected behavior

mvn test result ok

### Actual behavior

error missing artifact 

### How to Reproduce?

Steps to reproduce:

1. https://code.quarkus.io/?e=io.quarkiverse.amazonservices%3Aquarkus-amazon-dynamodb-enhanced&e=io.quarkiverse.amazonservices%3Aquarkus-amazon-dynamodb&e=amazon-lambda
2. download the zip 
3. run mvn test

### Output of `uname -a` or `ver`

Darwin LT-C02DC3R5MD6R.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64

### Quarkus version or git rev

2.16

**Comment by patriot1burke** [comment]
`Missing 'software.amazon.awssdk:url-connection-client' dependency on the classpath`

Maybe add this dependency?

**Comment by aleboulanger** [comment]
> `Missing 'software.amazon.awssdk:url-connection-client' dependency on the classpath`
> 
> Maybe add this dependency?

yes of course but I'm expect to have this dependency define somewhere in the quarkus dynamodb dependency maybe ?
since I downloaded a starter code from the quarkus website it should work without any updates.

**Comment by aleboulanger** [comment]
found the answer in the [quarkiverse website](https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/amazon-dynamodb.html#_configuring_dynamodb_clients)
