### ISSUE TITLE
 org.springframework.data.domain.Example is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader

### ISSUE THREAD

**Issue by Joy1024** [quarkusio/quarkus#31056]
### Describe the bug

pom.xml include `quarkus-spring-data-jpa` flow is:

```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-spring-data-jpa</artifactId>
        </dependency>
```

My code is:
```java
// SysUserRepository
@Singleton
public interface SysUserRepository extends JpaRepository<SysUser, Long>

 // query users by example.
 @Override
    public List<SysUser> selectUserList(SysUser user) {
        Example q = Example.of(user);  <==================== throw exception
        return sysUserRepository.findAll(q);
    }

```

```log
2023-02-10 10:13:41,976 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: java.lang.IllegalAccessError: failed to access class org.springframework.data.domain.TypedExample from class org.springframework.data.domain.Example (org.springframework.data.domain.TypedExample is in unnamed module of loader 'app'; org.springframework.data.domain.Example is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @541d4d9f)
	at org.springframework.data.domain.Example.of(Example.java:39)
	at com.wwkj.platform.system.service.impl.SysUserServiceImpl.selectUserList(SysUserServiceImpl.java:55)
	at com.wwkj.platform.system.controller.SysUserController.list(SysUserController.java:100)
	at com.wwkj.platform.system.controller.SysUserController$quarkusrestinvoker$list_df44f2bfcd664145662e4bf2e0668035d39cbfd5.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Expected behavior

Find user list.

### Actual behavior

throw exception:
``` 
org.springframework.data.domain.Example is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader
```

### How to Reproduce?

# Create a quarkus maven project.
# add some dependency to pom.xml
```
   <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-spring-data-jpa</artifactId>
        </dependency>
```

# model a java file named `SysUser`, like this:
```
@Data
@Entity
@Table(name="sys_user")
public class SysUser extends BaseEntity
{
```

# Create a repository for SysUser.
```
@Singleton
public interface SysUserRepository extends JpaRepository<SysUser, Long>
```

#  Create a SysUserService that include the code like is:
```
@Override
    public List<SysUser> selectUserList(SysUser user) {
        Example q = Example.of(user);
        return sysUserRepository.findAll(q);
    }
```
# Create a `SysUserResource` that include invoke `SysUserService#selectUserList(SysUser user)` like is:
```java
 @GET
@Path("/list")
    public TableDataInfo list(@BeanParam SysUserVO vo) {
        SysUser user = new SysUser();
        BeanUtils.copyProperties(vo, user);
        List<SysUser> list = userService.selectUserList(user);
        return getDataTable(list);
    }
```

### Output of `uname -a` or `ver`

Linux gaojie-H81U 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13) OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### GraalVM version (if different from Java)

GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13)

### Quarkus version or git rev

2.16.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by geoand** [comment]
Can you please attach a sample application that behaves as you mention?

**Comment by geoand** [comment]
Closing as we never got a reproducer
