### ISSUE TITLE
bouncycastle-jsse native integration test fails with lastest JDK 17.0.7+1 ea

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#31113]
### Describe the bug

Native image generation of the `bouncycastle-jsse` integration test fails on Graal master tree and JDK `17.0.7+1` with:

```
Error: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image runtime, and the files might not even be present anymore at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.io.FileDescriptor. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  reading field java.io.FileInputStream.fd of constant 
    java.io.FileInputStream@2cc3602d: java.io.FileInputStream@2cc3602d
  reading field java.io.FilterInputStream.in of constant 
    java.io.BufferedInputStream@b20978f: java.io.BufferedInputStream@b20978f
  reading field org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider.seedStream of constant 
    org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider@2f0c286e: org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider@2f0c28...
  reading field org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider$3.this$0 of constant 
    org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider$3@296fbe7f: org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider$3@296f...
  reading field org.bouncycastle.jcajce.provider.drbg.DRBG$HybridEntropySource$SignallingEntropySource$EntropyGatherer.baseRandom of constant 
    org.bouncycastle.jcajce.provider.drbg.DRBG$HybridEntropySource$SignallingEntropySource$EntropyGatherer@d9a41e8: org.bouncycastle.jcajce.provider.drbg.DRBG$HybridEntropySource$SignallingEntropy...
  reading field java.util.concurrent.ConcurrentLinkedDeque$Node.item of constant 
    java.util.concurrent.ConcurrentLinkedDeque$Node@6be5f814: java.util.concurrent.ConcurrentLinkedDeque$Node@6be5f814
  reading field java.util.concurrent.ConcurrentLinkedDeque.tail of constant 
    java.util.concurrent.ConcurrentLinkedDeque@3a9f2580: []
  reading field org.bouncycastle.jcajce.provider.drbg.DRBG$EntropyDaemon.tasks of constant 
    org.bouncycastle.jcajce.provider.drbg.DRBG$EntropyDaemon@511da44f: org.bouncycastle.jcajce.provider.drbg.DRBG$EntropyDaemon@511da44f
  reading static field org.bouncycastle.jcajce.provider.drbg.DRBG.entropyDaemon
    at org.bouncycastle.jcajce.provider.drbg.DRBG.createBaseRandom(Unknown Source)
  parsing method org.bouncycastle.jcajce.provider.drbg.DRBG.createBaseRandom(Unknown Source) reachable via the parsing context
    at org.bouncycastle.jcajce.provider.drbg.DRBG$Default.<clinit>(Unknown Source)
    at static root method.(Unknown Source)


com.oracle.svm.core.util.UserError$UserException: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image runtime, and the files might not even be present anymore at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.io.FileDescriptor. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  reading field java.io.FileInputStream.fd of constant 
    java.io.FileInputStream@2cc3602d: java.io.FileInputStream@2cc3602d
  reading field java.io.FilterInputStream.in of constant 
    java.io.BufferedInputStream@b20978f: java.io.BufferedInputStream@b20978f
  reading field org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider.seedStream of constant 
    org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider@2f0c286e: org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider@2f0c28...
  reading field org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider$3.this$0 of constant 
    org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider$3@296fbe7f: org.bouncycastle.jcajce.provider.drbg.DRBG$URLSeededEntropySourceProvider$3@296f...
  reading field org.bouncycastle.jcajce.provider.drbg.DRBG$HybridEntropySource$SignallingEntropySource$EntropyGatherer.baseRandom of constant 
    org.bouncycastle.jcajce.provider.drbg.DRBG$HybridEntropySource$SignallingEntropySource$EntropyGatherer@d9a41e8: org.bouncycastle.jcajce.provider.drbg.DRBG$HybridEntropySource$SignallingEntropy...
  reading field java.util.concurrent.ConcurrentLinkedDeque$Node.item of constant 
    java.util.concurrent.ConcurrentLinkedDeque$Node@6be5f814: java.util.concurrent.ConcurrentLinkedDeque$Node@6be5f814
  reading field java.util.concurrent.ConcurrentLinkedDeque.tail of constant 
    java.util.concurrent.ConcurrentLinkedDeque@3a9f2580: []
  reading field org.bouncycastle.jcajce.provider.drbg.DRBG$EntropyDaemon.tasks of constant 
    org.bouncycastle.jcajce.provider.drbg.DRBG$EntropyDaemon@511da44f: org.bouncycastle.jcajce.provider.drbg.DRBG$EntropyDaemon@511da44f
  reading static field org.bouncycastle.jcajce.provider.drbg.DRBG.entropyDaemon
    at org.bouncycastle.jcajce.provider.drbg.DRBG.createBaseRandom(Unknown Source)
  parsing method org.bouncycastle.jcajce.provider.drbg.DRBG.createBaseRandom(Unknown Source) reachable via the parsing context
    at org.bouncycastle.jcajce.provider.drbg.DRBG$Default.<clinit>(Unknown Source)
    at static root method.(Unknown Source)


	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:819)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:607)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:564)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:616)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
```

It looks like with `17.0.7+1` and later a FileDescriptor is being reached which wasn't before. It seems a new failure since `17.0.7+1` (I haven't checked `17.0.6` just yet).

### Expected behavior

native image generation passes and test works.

### Actual behavior

Native image generation fails.

### How to Reproduce?

Run the native integration test `bouncycastle-jsse` with a Graal/mandrel build with JDK 17.0.7+1 ea. For example from here: https://github.com/graalvm/mandrel/suites/10925352838/artifacts/552436030

### Output of `java -version`

17.0.7+1

### GraalVM version (if different from Java)

GraalVM master

### Quarkus version or git rev

main

**Comment by jerboaa** [comment]
see https://github.com/graalvm/mandrel/actions/runs/4154165398/jobs/7186572966#step:11:473

**Comment by zakkak** [comment]
@jerboaa it looks like this is not an issue in the latest run https://github.com/graalvm/mandrel/actions/runs/4159369513

**Comment by jerboaa** [comment]
@zakkak Ah, OK. Thanks. I'll close it then and will re-open if we see it again.
