### ISSUE TITLE
Jandex indexation of spring RestTemplate/InitializingBean fails

### ISSUE THREAD

**Issue by laurentperez** [quarkusio/quarkus#31123]
### Describe the bug

Hello

I've read https://github.com/quarkusio/quarkus/issues/5971#issuecomment-562438434

I have a use case where I'd like to use a custom 3rd party jar which is internally using `RestTemplate` and `InitializingBean` (yes I understand the bean lifecycle of `afterPropertiesSet` will not be honored, it's ok)

I'm using the QK spring-di spring-boot-properties and spring-web adapters

Basically I'm using a template producer as xxxxx as in

```
@Configuration
open class Foo {
    @Bean
    open fun xxxxx(): RestTemplate = RestTemplate(
        HttpComponentsClientHttpRequestFactory(httpClient())
    )
}
```

QK 2.16.2 Final throws and fails on startup

```
023-02-13 15:44:51,963 DEBUG [io.qua.arc.pro.BeanArchives] (build-14) Index: org.springframework.beans.factory.InitializingBean
2023-02-13 15:44:51,964 WARN  [io.qua.arc.pro.BeanArchives] (build-14) Failed to index org.springframework.beans.factory.InitializingBean: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV@1356d4d4
2023-02-13 15:44:51,964 INFO  [io.qua.arc.pro.IndexClassLookupUtils] (build-14) Class for name: org.springframework.beans.factory.InitializingBean was not found in Jandex index. Please ensure the class is part of the index.
2023-02-13 15:23:19,882 WARN  [io.qua.arc.pro.BeanArchives] (build-21) Failed to index org.springframework.web.client.RestTemplate: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV@1356d4d4
2023-02-13 15:23:19,882 INFO  [io.qua.arc.pro.IndexClassLookupUtils] (build-21) Class for name: org.springframework.web.client.RestTemplate was not found in Jandex index. Please ensure the class is part of the index.

Caused by: java.lang.IllegalArgumentException: Producer method return type not found in index: org.springframework.web.client.RestTemplate
	at io.quarkus.arc.processor.Types.getProducerMethodTypeClosure(Types.java:330)

plus : 
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.InitializingBean
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
```

I understand it's maybe not in RedHat's market interest to support Vmware's Spring RestTemplate or the lifecycle of InitializingBean. I'm note sure about @PostConstruct either ?

If you do suppport that well it'd open... gates.

@geoand comment was "it's unlikely we will support" but it was from 3 years ago

Are there maybe reopened plans to support both the template and https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/InitializingBean.html too ?

Thanks

### Expected behavior

Unsure ;)

### Actual behavior

throws see above

### Quarkus version or git rev

2.16.2 final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by geoand** [comment]
I personally won't be adding support for the mentioned Spring features, but I'd be willing to accept contributions

**Comment by laurentperez** [comment]
Oki. I noticed RestTemplate is deprecated in favor of WebClient. I'll check if Jandex indexes this one.

InitializingBean is the "old" coupled way, PostConstruct is preferred nowadays. I'll check this one too.

I understand contributing these may produce weird mutants apps hard to debug using both RESTeasy and another http component of another fwk. I need to check the outcomes

Please don't close this unless there's no activity. Thanks !

disclaimer : nope I'm not an employee of vmware, ha. We're just happy Quarkus users

**Comment by geoand** [comment]
👌

**Comment by geoand** [comment]
@laurentperez is this still an issue?

**Comment by laurentperez** [comment]
it's still relevant but I had no time to PR further. closing.
