### ISSUE TITLE
Quarkus OIDC Cannot Discovery When use Programmatically Resolving Tenants Configuration

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#31140]
### Describe the bug

1、will got error when bootstrap
```yaml
quarkus:
     oidc:
        enabled: true
        tenant-id: master
        tenant-enabled: true
        auth-server-url: http://localhost:18080
```
```log
2023-02-14 15:17:47,501 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.datasource.reactive" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2023-02-14 15:17:47,502 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.smallrye-health.http.post.queryparameters.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2023-02-14 15:17:49,357 WARN  [io.qua.oid.com.run.OidcCommonUtils] (vert.x-eventloop-thread-1) OIDC Server is not available:: io.quarkus.oidc.common.runtime.OidcEndpointAccessException
        at io.quarkus.oidc.common.runtime.OidcCommonUtils.lambda$discoverMetadata$2(OidcCommonUtils.java:406)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
        at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
        at io.smallrye.mutiny.vertx.DelegatingHandler.handle(DelegatingHandler.java:25)
        at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:397)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:384)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:362)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:329)
        at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:291)
        at io.vertx.ext.web.client.impl.HttpContext.lambda$null$7(HttpContext.java:507)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

2、Dit not discovery on provide a OidcConfig
```java

@ApplicationScoped
public class OrgTenantConfigResolver implements TenantConfigResolver {
    private static final String ORG_CODE_HEADER_NAME = "X-ORG-CODE";
    private final OrgService orgService;

    @Inject
    public OrgTenantConfigResolver(OrgService orgService) {
        this.orgService = orgService;
    }

    @Override
    public Uni<OidcTenantConfig> resolve(RoutingContext routingContext,
                                         OidcRequestContext<OidcTenantConfig> requestContext) {
        return requestContext.runBlocking(() -> loadOidcTenantConfig(routingContext));
    }

    private OidcTenantConfig loadOidcTenantConfig(RoutingContext routingContext) {
        var org = loadOrg(routingContext);
        String authServerUrl = ConfigProvider.getConfig().getValue("quarkus.oidc.auth-server-url", String.class);
        OidcTenantConfig config = new OidcTenantConfig();
        config.setTenantId(org.getRealm());
        config.setTenantEnabled(true);
        config.setAuthServerUrl(String.format("%s/realms/%s", authServerUrl, org.getRealm()));
        config.setDiscoveryEnabled(true);
        return config;
    }

    private OrgEntity loadOrg(RoutingContext routingContext) {
        return orgService.searcher().findOrPrimary(loadOrgCode(routingContext))
            .orElseThrow(OrgMessages.INSTANCE::primaryNotFound);
    }

    private String loadOrgCode(RoutingContext routingContext) {
        return Optional.ofNullable(routingContext)
            .map(RoutingContext::request)
            .map(request -> request.getHeader(ORG_CODE_HEADER_NAME)).orElse(null);
    }
}
```

```log
2023-02-14 15:21:40,822 TRACE [org.hib.typ.des.sql.BasicBinder] (vert.x-worker-thread-0) binding parameter [1] as [VARCHAR] - [PRIMARY]
     2023-02-14 15:21:41,079 INFO  [io.qua.htt.access-log] (vert.x-eventloop-thread-3) 0:0:0:0:0:0:0:1 - - 14/Feb/2023:15:21:41 +0800 "POST /graphql HTTP/1.1" 401 -
2023-02-14 15:21:41,087 ERROR [io.sma.graphql] (vert.x-eventloop-thread-3) SRGQL012000: Data Fetching Error: io.quarkus.security.AuthenticationFailedException
        at io.quarkus.oidc.runtime.OidcIdentityProvider$4.apply(OidcIdentityProvider.java:161)
        at io.quarkus.oidc.runtime.OidcIdentityProvider$4.apply(OidcIdentityProvider.java:157)
        at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onFailure(UniOnItemOrFailureFlatMap.java:65)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownFailure$KnownFailureSubscription.forward(UniCreateFromKnownFailure.java:38)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownFailure.subscribe(UniCreateFromKnownFailure.java:23)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:99)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:54)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:99)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:54)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:36)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
        at io.smallrye.mutiny.vertx.DelegatingHandler.handle(DelegatingHandler.java:25)
        at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:397)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:384)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:362)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:329)
        at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:291)
        at io.vertx.ext.web.client.impl.HttpContext.lambda$null$7(HttpContext.java:507)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.jose4j.jwt.consumer.InvalidJwtException: JWT (claims->{"exp":1676357992,"iat":1676357932,"jti":"d7a44369-15fb-4653-9981-c9d0d42970ab","iss":"http://localhost:18080/realms/master","sub":"5d15d9ff-0288-4487-8103-94ae1d056ea1","typ":"Bearer","azp":"admin-cli","session_state":"e53cf100-a1e0-4ee0-b9a3-c4ae625af115","acr":"1","scope":"email profile","sid":"e53cf100-a1e0-4ee0-b9a3-c4ae625af115","email_verified":false,"preferred_username":"admin","given_name":"","family_name":"","email":"admin@handaotech.com"}) rejected due to invalid claims or other invalid content. Additional details: [[1] The JWT is no longer valid - the evaluation time NumericDate{1676359301 -> Feb 14, 2023, 3:21:41 PM CST} is on or after the Expiration Time (exp=NumericDate{1676357992 -> Feb 14, 2023, 2:59:52 PM CST}) claim value.]
        at org.jose4j.jwt.consumer.JwtConsumer.validate(JwtConsumer.java:459)
        at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:304)
        at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:426)
        at org.jose4j.jwt.consumer.JwtConsumer.processToClaims(JwtConsumer.java:171)
        at io.quarkus.oidc.runtime.OidcProvider.verifyJwtTokenInternal(OidcProvider.java:162)
        at io.quarkus.oidc.runtime.OidcProvider.verifyJwtToken(OidcProvider.java:110)
        at io.quarkus.oidc.runtime.OidcIdentityProvider.verifyTokenUni(OidcIdentityProvider.java:328)
        at io.quarkus.oidc.runtime.OidcIdentityProvider.createSecurityIdentityWithOidcServer(OidcIdentityProvider.java:153)
        at io.quarkus.oidc.runtime.OidcIdentityProvider$3.apply(OidcIdentityProvider.java:136)
        at io.quarkus.oidc.runtime.OidcIdentityProvider$3.apply(OidcIdentityProvider.java:125)
        at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
        ... 48 more

2023-02-14 15:21:41,091 INFO  [io.sma.graphql] (vert.x-eventloop-thread-3) SRGQL011006: Payload Out [ExecutionResponse->ExecutionResultImpl{errors=[ExceptionWhileDataFetching{path=[entrances], exception=io.quarkus.security.AuthenticationFailedException, locations=[SourceLocation{line=2, column=3}]}], data=null, dataPresent=true, extensions=null}]
2023-02-14 15:21:41,092 ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-3) Mutiny had to drop the following exception: java.lang.IllegalStateException: Response head already sent
        at io.vertx.core.http.impl.Http1xServerResponse.checkHeadWritten(Http1xServerResponse.java:687)
        at io.vertx.core.http.impl.Http1xServerResponse.setStatusCode(Http1xServerResponse.java:149)
        at io.quarkus.vertx.http.runtime.filters.AbstractResponseWrapper.setStatusCode(AbstractResponseWrapper.java:61)
        at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler$VertxExecutionResponseWriter.write(SmallRyeGraphQLExecutionHandler.java:338)
        at io.smallrye.graphql.execution.ExecutionService.notifyAndWrite(ExecutionService.java:237)
        at io.smallrye.graphql.execution.ExecutionService.lambda$writeAsync$1(ExecutionService.java:203)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:73)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at graphql.execution.ExecutionStrategy.handleNonNullException(ExecutionStrategy.java:798)
        at graphql.execution.AbstractAsyncExecutionStrategy.lambda$handleResults$0(AbstractAsyncExecutionStrategy.java:28)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
        at graphql.execution.AsyncExecutionStrategy.lambda$execute$1(AsyncExecutionStrategy.java:72)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at graphql.execution.Async$Single.lambda$await$1(Async.java:87)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:386)
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
        at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Output of `uname -a` or `ver`

Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### GraalVM version (if different from Java)

17.0.5+8-jvmci-22.3-b08

### Quarkus version or git rev

3.0.0.Alpha3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.6

**Comment by pipinet** [comment]
i try jwt.io Signature Verified

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/6096680/218672397-9ece1c76-e9bf-49ba-98f0-43f25669a10b.png">
<img width="1784" alt="image" src="https://user-images.githubusercontent.com/6096680/218672529-b1a76c58-6701-41b0-938a-a71b2d17e9ed.png">

**Comment by pipinet** [comment]
2、Looks like the token has expired, ignore it.

**Comment by sberyozkin** [comment]
@pipinet Right as far as the 2nd problem is concerned, the discovery is working correctly, many of Quarkus OIDC tests with the programmatic setup depend on the discovery as well. The failure happens during the token verification, the token lifetime may have to be adjusted, see also `quarkus.oidc.token.lifetime-grace` to take care of the clock skew etc

As far as 1. is concerned, knowing now it is  Keycloak you work with, the configured auth-server-url is not complete, so it can't discover anything from it.
FYI, by default, the tenant is enabled, and so it the discovery, so no need to configure these 2 properties.

Looks like this issue can be closed, right ?

**Comment by pipinet** [comment]
> 

Thanks, so i need to configure the oidc base url somewhere other than quarkus.oidc.auth-server-url, right?

**Comment by sberyozkin** [comment]
@pipinet In case of Keycloak it has to be set to the KC realm URL, in 1. you have just `http://localhost:18080`, while you do set it correctly in the tenant resolver

**Comment by pipinet** [comment]
@sberyozkin  ok, thanks,  the question is resolved, please close the issues。

**Comment by sberyozkin** [comment]
Thanks @pipinet
