### ISSUE TITLE
IndexOutOfBoundsException on gRPC request received after Quarkus shutdown initiated

### ISSUE THREAD

**Issue by vladykin** [quarkusio/quarkus#31168]
### Describe the bug

The following exception is sometimes observed, if there is incoming gRPC traffic when Quarkus app is shutting down. 

```
2023-02-10 05:59:46,459 WARNING [io.grp.net.NettyServerStream] (vert.x-eventloop-thread-4) Exception processing message: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at io.vertx.grpc.VertxServer$ActualServer.lambda$new$1(VertxServer.java:91)
        at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:102)
        at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:95)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.messagesAvailable(ServerImpl.java:845)
        at io.grpc.internal.AbstractStream$TransportState.messagesAvailable(AbstractStream.java:182)
        at io.grpc.internal.MessageDeframer.processBody(MessageDeframer.java:412)
        at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:275)
        at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:177)
        at io.grpc.internal.AbstractStream$TransportState.deframe(AbstractStream.java:210)
        at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:255)
        at io.grpc.netty.NettyServerStream$TransportState.inboundDataReceived(NettyServerStream.java:226)
        at io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:508)
        at io.grpc.netty.NettyServerHandler.access$900(NettyServerHandler.java:106)
        at io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:840)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:307)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:415)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:250)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Expected behavior

Reject new incoming calls, close existing calls. Not throw IndexOutOfBoundsException

### Actual behavior

IndexOutOfBoundsException is logged. Not clear what happens with gRPC calls after it

### How to Reproduce?

Start a Quarkus app with gRPC server. Send gRPC traffic to it. Shutdown Quarkus app while still under load

### Output of `java -version`

java 11

### Quarkus version or git rev

2.12.3.Final

**Comment by geoand** [comment]
Sounds like a Vert.x issue. cc @vietj

**Comment by cescoffier** [comment]
Yes, it's a vert.x issue. 

@vladykin do you have a reproducer?

**Comment by cescoffier** [comment]
@vladykin Are you using the legacy (separated) server or the new server?

**Comment by vladykin** [comment]
This happens with the legacy (separated) gRPC server in our production app. I don't have a minimal reproducer. I think the key to creating one is to create a long-living streaming gRPC call with active incoming traffic from client when the server starts shutting down.

**Comment by cescoffier** [comment]
@vladykin a simple reproducer would be great.

**Comment by vladykin** [comment]
Here is a reproducer.

**streams.proto**:
```proto
syntax = "proto3";

package com.example;

option java_package = "com.example.test";

service Streams {
  rpc Echo (stream Item) returns (stream Item) {}
}

message Item {
  string name = 1;
}
```

**StreamsService.java**:
```java
package com.example;

import com.example.test.StreamsGrpc;
import com.example.test.StreamsOuterClass.Item;
import io.grpc.stub.StreamObserver;
import io.quarkus.grpc.GrpcService;

@GrpcService
public class StreamsService extends StreamsGrpc.StreamsImplBase {

  @Override
  public StreamObserver<Item> echo(StreamObserver<Item> responseObserver) {
    return new StreamObserver<Item>() {
      @Override
      public void onNext(Item item) {
        responseObserver.onNext(item);
      }

      @Override
      public void onError(Throwable throwable) {
        responseObserver.onError(throwable);
      }

      @Override
      public void onCompleted() {
        responseObserver.onCompleted();
      }
    };
  }
}
```

**pom.xml**:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>ioobe-reproducer</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <quarkus.version>2.16.3.Final</quarkus.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>quarkus-build</id>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-universe-bom</artifactId>
                <version>${quarkus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-grpc</artifactId>
        </dependency>
    </dependencies>

</project>
```

Steps to reproduce:
* run the app: `mvn quarkus:dev`
* in another terminal connect a client and start sending messages: `while true; do echo '{"name":"foo"}'; done | grpcurl -import-path src/main/proto -proto streams.proto -plaintext -d @ localhost:9000 com.example.Streams/Echo`
* initiate app shutdown by hitting `q` in the quarkus:dev console

As result, client logs the following gRPC error:
```
ERROR:
  Code: Unknown
  Message: java.lang.IndexOutOfBoundsException - Index 0 out of bounds for length 0
```

**Comment by cescoffier** [comment]
I've tried with both the legacy and the new server. It's the expected behavior, in the sense that `q` closes the server and so closes the connection.

Note that with the latest release (as well as 999-SNAPSHOT), the server stack trace has been fixed (at least, I do not see it).

The new server behavior is slightly better as it returns:
```
ERROR:
  Code: Unavailable
  Message: closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR
```
