### ISSUE TITLE
Jib multiplatform build not working?

### ISSUE THREAD

**Issue by snazy** [quarkusio/quarkus#31191]
### Describe the bug

After looking into the docs and source code, I can't get the build to produce a multiplatform image.

From the stack trace it always hits `com.google.cloud.tools.jib.builder.steps.StepsRunner#dockerLoadSteps`, which it should not hit for multiplatform builds IIUC.

`io.quarkus.container.image.jib.deployment.JibProcessor#createContainerizer` calls either `com.google.cloud.tools.jib.api.Containerizer#to(com.google.cloud.tools.jib.api.RegistryImage)` or `com.google.cloud.tools.jib.api.Containerizer#to(com.google.cloud.tools.jib.api.DockerDaemonImage)` - and both call `com.google.cloud.tools.jib.api.Containerizer#to(com.google.cloud.tools.jib.api.DockerClient, com.google.cloud.tools.jib.api.DockerDaemonImage)`, which adds the `dockerLoadSteps`. It seems, there's no way around _Docker_ in that call chain, so it can't build multiplatform images? Should Quarkus use `com.google.cloud.tools.jib.api.Containerizer#to(com.google.cloud.tools.jib.api.TarImage)` instead?

The properties I'm using look correct to me:
```
  quarkus.package.type     = fast-jar
  quarkus.native.builder-image     = quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
  quarkus.native.container-build     = false
  quarkus.container-image.build     = true
  quarkus.container-image.builder     = jib
  quarkus.docker.buildx.output     = type=oci,dest=build/nessie-quarkus-0.48.3-SNAPSHOT/image
  quarkus.jib.base-jvm-image     = registry.access.redhat.com/ubi8/openjdk-17-runtime:1.14
  quarkus.jib.platforms     = linux/amd64,linux/arm64/v8
  quarkus.docker.buildx.platform     = linux/amd64,linux/arm64/v8
```
same for a "reduced options set":
```
  quarkus.package.type     = fast-jar
  quarkus.container-image.build     = true
  quarkus.container-image.builder     = jib
  quarkus.jib.platforms     = linux/amd64,linux/arm64/v8
```

Removing the multiplatform options or just specifying a single platform works fine though.

Stack trace (probably the same as in #27165):
```
Execution failed for task ':nessie-quarkus:quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
        at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:255)
        at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:181)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.util.concurrent.ExecutionException: com.google.common.base.VerifyException: multi-platform image building not supported when pushing to Docker engine
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
        at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
        at com.google.cloud.tools.jib.builder.steps.StepsRunner.run(StepsRunner.java:219)
        at com.google.cloud.tools.jib.api.Containerizer.run(Containerizer.java:406)
        at com.google.cloud.tools.jib.api.JibContainerBuilder.containerize(JibContainerBuilder.java:610)
        at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:248)
        ... 12 more
  Caused by: com.google.common.base.VerifyException: multi-platform image building not supported when pushing to Docker engine
        at com.google.common.base.Verify.verify(Verify.java:126)
        at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$loadDocker$18(StepsRunner.java:619)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Quarkus version or git rev

2.16.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.6

**Comment by snazy** [comment]
(Could not find an IT using `quarkus.jib.platforms`)

**Comment by geoand** [comment]
IIRC, that feature was contributed by someone in the community, I have never tested it myself.

**Comment by snazy** [comment]
(Moving our Docker build to `docker buildx` using an external script, so not blocked on this issue.)

**Comment by Karm** [comment]
> IIRC, that feature was contributed by someone in the community, I have never tested it myself.

So, should this be triaged and fixed or removed from Quarkus as an unmaintained thing?

**Comment by geoand** [comment]
Ideally fixed

**Comment by rquinio** [comment]
You probably need `quarkus.container-image.push=true` so Jib doesn't fallback to using "docker load" command ?

**Comment by gmuth** [comment]
rquinio is right. You need to tell jib where to put the multiplatform images to. As docker desktop does not support to keep different architectures jib rejects you request. jib can very well build multiplatform images! however you need to provide/configure a registry that supports multiplatform images, e.g. aws ecr or gitlab cr.
If you're on a Mac M1 you can still pull and run images using different architectures using the --platform option.

Switching to docker buildx via quarkus extension does not help because load and push is not supported by docker for multiplatform images either :-(
