### ISSUE TITLE
Quarkus Vertx throwing java.nio.BufferOverflowException during test when run from command line but not intellij

### ISSUE THREAD

**Issue by aaron-axisa** [quarkusio/quarkus#31208]
### Describe the bug

I have a service that is making use of the Quarkus Event bus. Quarkus version in use is 2.9.0.CR1

When I run my tests through intellij, all tests pass and i do not get issues. However, when I try to run with mvn clean install from command line, I am getting this excpetion:

```
(RECIPIENT_FAILURE,8185) java.nio.BufferOverflowException
        at io.vertx.core.eventbus.Message.fail(Message.java:141)
        at io.quarkus.vertx.runtime.VertxRecorder$3$1$1.handle(VertxRecorder.java:117)
        at io.quarkus.vertx.runtime.VertxRecorder$3$1$1.handle(VertxRecorder.java:107)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:548)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

The object I am trying to send over the event bus is this:

```
public record TransportSendMessage(MimeMessage message, String from, String to) {

}
```
(For the record, the MimeMessage in that is the jakarta one to send mail with. It also contains an image as an attachment in it, so it is posisble that there isa bit of heft to the message in terms of bytes)

The Codec for this is:

```
public class TransportSendMessageCodec implements MessageCodec<TransportSendMessage, TransportSendMessage> {
  @Override
  public void encodeToWire(Buffer buffer, TransportSendMessage scheduledPubsubMessage) {
    // NO-OP
  }

  @Override
  public TransportSendMessage decodeFromWire(int pos, Buffer buffer) {
    // NO-OP
    return null;
  }

  @Override
  public TransportSendMessage transform(TransportSendMessage transportSendMessage) {
    // we pass the object by reference over the eventbus.
    return transportSendMessage;
  }

  @Override
  public String name() {
    return getClass().getName();
  }

  @Override
  public byte systemCodecID() {
    return -1;
  }
}
```
My handler class:

```
@Slf4j
@Startup
@ApplicationScoped
public class TransportSendHandler {

  public static final String TRANSPORT_HANDLER_EVENT_BUS_ADDRESS = "emailTransportSendEventBus";

  @Inject
  EventBus eventBus;


  @PostConstruct
  public void init() {
    eventBus.registerCodec(new TransportSendMessageCodec());
  }

  /**
   * We consume a message from the event bus. The message received will then be emailed
   *
   * @param message The message to email
   */
  @ConsumeEvent(value = TRANSPORT_HANDLER_EVENT_BUS_ADDRESS)
  @Blocking
  public Uni<Void> consumeMessage(TransportSendMessage message) {
    try {
      log.debug("Attempting to send email: from {}, to {}", message.from(), message.to());
      Transport.send(message.message());
      log.debug("Email has been sent: from {}, to {} ", message.from(), message.to());
      return Uni.createFrom().voidItem();
    } catch (MessagingException e) {
      log.warn("Failed sending email: from {}, to {}", message.from(), message.to());
      return Uni.createFrom().failure(e);
    }
  }
}
```

And the code sending the message:

```
eventBus.request(TransportSendHandler.TRANSPORT_HANDLER_EVENT_BUS_ADDRESS,
            new TransportSendMessage(myMimeMessage, fromADdress, toAddress)))
```
I'm a bit lost really as to why this is happening just when run from command line.

### Expected behavior

No error when running from commandline

### Actual behavior

BufferOverflowException

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.1105]

### Output of `java -version`

openjdk version "18.0.1.1" 2022-04-22 OpenJDK Runtime Environment (build 18.0.1.1+2-6) OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

### Quarkus version or git rev

2.9.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0) Maven home: C:\Program Files\Maven\apache-maven-3.8.5 Java version: 18.0.1.1, vendor: Oracle Corporation, runtime: C:\Users\Aaron Work\.jdks\openjdk-18.0.1.1 Default locale: en_GB, platform encoding: UTF-8 OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

**Comment by cescoffier** [comment]
Do you have a reproducer I can use?

**Comment by cescoffier** [comment]
I would also recommend updating to the latest Quarkus. 2.9 is very old.

**Comment by geoand** [comment]
Closing as we never got a reproducer
