### ISSUE TITLE
Upgrade to Quarkus  3.0.0.Alpha4. Dependencies could not be resolved: org.junit.jupiter:junit-jupiter:jar:5.9.2

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#31241]
### Describe the bug

Migrated an app to 3.0.0.Alpha4  with the script `jbang --fresh --verbose upgrade-to-quarkus3@quarkusio`
Maven build fails:
```
[WARNING] The POM for org.junit.jupiter:junit-jupiter:jar:5.9.2 is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin io.quarkus.platform:quarkus-maven-plugin:3.0.0.Alpha4 or one of its dependencies could not be resolved: org.junit.jupiter:junit-jupiter:jar:5.9.2 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]

org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin io.quarkus.platform:quarkus-maven-plugin:3.0.0.Alpha4 or one of its dependencies could not be resolved: org.junit.jupiter:junit-jupiter:jar:5.9.2 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced @ 

	at org.apache.maven.project.CachingProjectBuilder.build(CachingProjectBuilder.java:378)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:414)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:405)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:82)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:542)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]   
[ERROR]   The project org.acme:quarkus-timed-producers:1.0.0-SNAPSHOT (/home/qk/Downloads/quarkus-timed-producers/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin io.quarkus.platform:quarkus-maven-plugin:3.0.0.Alpha4 or one of its dependencies could not be resolved: org.junit.jupiter:junit-jupiter:jar:5.9.2 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]

org.apache.maven.plugin.PluginManagerException: Plugin io.quarkus.platform:quarkus-maven-plugin:3.0.0.Alpha4 or one of its dependencies could not be resolved: org.junit.jupiter:junit-jupiter:jar:5.9.2 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
	at org.mvndaemon.mvnd.plugin.CliMavenPluginManager.setupExtensionsRealm(CliMavenPluginManager.java:758)
	at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm(DefaultProjectBuildingHelper.java:197)
	at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled(DefaultModelBuildingListener.java:101)
	at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire(ModelBuildingEventCatapult.java:44)
	at org.apache.maven.model.building.DefaultModelBuilder.fireEvent(DefaultModelBuilder.java:1450)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:530)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:510)
	at org.apache.maven.project.CachingProjectBuilder.build(CachingProjectBuilder.java:601)
	at org.apache.maven.project.CachingProjectBuilder.build(CachingProjectBuilder.java:364)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:414)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:405)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:82)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:542)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin io.quarkus.platform:quarkus-maven-plugin:3.0.0.Alpha4 or one of its dependencies could not be resolved: org.junit.jupiter:junit-jupiter:jar:5.9.2 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:234)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:165)
	at org.mvndaemon.mvnd.plugin.CliMavenPluginManager.resolveExtensionArtifacts(CliMavenPluginManager.java:807)
	at org.mvndaemon.mvnd.plugin.CliMavenPluginManager.setupExtensionsRealm(CliMavenPluginManager.java:753)
	... 26 common frames omitted
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: org.junit.jupiter:junit-jupiter:jar:5.9.2 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:425)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:340)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:226)
	... 29 common frames omitted
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: org.junit.jupiter:junit-jupiter:jar:5.9.2 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:217)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:189)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:574)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:484)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402)
	... 32 common frames omitted

```

**Comment by ennishol** [comment]
Reproducer app
[quarkus-timed-producers.tar.gz](https://github.com/quarkusio/quarkus/files/10764785/quarkus-timed-producers.tar.gz)

**Comment by aloubyansky** [comment]
Try removing `org/junit/jupiter/junit-jupiter/5.9.2/` in your local Maven repo and re-build the project. https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter/5.9.2/ is available.

**Comment by ennishol** [comment]
Argh... I'm very sorry. mvn -U solved it
