### ISSUE TITLE
[Regression in 2.16.3] `NullPointerException: Cannot invoke "org.jboss.resteasy.reactive.server.SimpleResourceInfo.getResourceClass()" because "this.resourceInfo" is null`

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#31245]
### Describe the bug

There seems to be a regression in 2.16.3: RestAssured tests that were running fine with 2.16.2 now fail with error code 500.

I can see the following in the logs:
```
2023-02-17 10:10:11,260 WARN  (f1cedf409aa3d4426067cc1700745ce6,86399571e387844a) [de.tsy.mms.nrw.reg.api.exc.ApiExceptionMapper] (executor-thread-0) internal exception: java.lang.NullPointerException: Cannot invoke "org.jboss.resteasy.reactive.server.SimpleResourceInfo.getResourceClass()" because "this.resourceInfo" is null
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.resteasy.OpenTelemetryReactiveServerFilter.filter(OpenTelemetryReactiveServerFilter.java:29)
	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:48)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:104)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
So it looks related to OTEL...?

### Expected behavior

No error

### Actual behavior

REST endpoints fail

### Quarkus version or git rev

2.16.3.Final

**Comment by geoand** [comment]
Which test is failing with this?

**Comment by famod** [comment]
It seems _all_ of our controller tests are failing.

**Comment by geoand** [comment]
Weird. If you have a small sample we can use to debug, that would be great

**Comment by famod** [comment]
So when I remove/disable OTEL, the problem goes away! Then again, `OpenTelemetryReactiveServerFilter` hasn't been touched since 2.16.2.
Question is: Why is `@Context SimpleResourceInfo resourceInfo;` all of a sudden?

**Comment by geoand** [comment]
Yeah, I would really like to debug it

**Comment by brunobat** [comment]
SimpleResourceInfo seems to be absent from OpenTelemetryReactiveServerFilter.
... But that comes from resteasy-reactive.
OpenTelemetryReactiveServerFilter was introduced last Dec. @arik-dig Any thoughts?

**Comment by brunobat** [comment]
@famod can you please provide a minimal reproducer?

**Comment by geoand** [comment]
I'll make a change that should fix the problem

**Comment by geoand** [comment]
Actually, before making any change, I would like to see a reproducer because I see our tests (which do exercise the filter) pass.

**Comment by famod** [comment]
Will take me some time to provide one. Hope it's not one of those "only in my app" issues...

**Comment by famod** [comment]
I wasn't able to extract a reproducer but I'll keep trying.
This does not only affect tests btw, real app is broken as well (JVM, docker image built via jib).

**Comment by arik-dig** [comment]
@brunobat I'm not sure what's causing it, since when I added it I added tests as well which covers it.
I'm not sure what is the edge case.

**Comment by famod** [comment]
@geoand I have a hard time extracting a minimal reproducer. Do you have some hints what to debug to get a better idea where this issue might be coming from?

**Comment by geoand** [comment]
I can't think of anyway that would lead to the filter being engaged in the filter chain but not be properly constructed...

**Comment by geoand** [comment]
You would be able to test a PR with your application if I make a change?

**Comment by famod** [comment]
> You would be able to test a PR with your application if I make a change?

@geoand sure!

**Comment by geoand** [comment]
@famod mind giving https://github.com/quarkusio/quarkus/pull/31331 a try please?
