### ISSUE TITLE
[ORM6] Hibernate Search - Class loading issue when loading services

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#31247]
Most of the Hibernate Search tests pass but some of them are failing when loading services.
The following is an example of the issue but there are others with the same symptoms.

:warning: **Note that this is with Hibernate Search 6.2.0.Alpha2 as I thought it would be the version to use to be compatible with ORM 6.2. In the end, we downgraded to 6.1.7.Final.**

Also see @marko-bekhta 's comments below.

How to reproduce:
- Get branch from: https://github.com/quarkusio/quarkus/pull/31235
- Update Hibernate Search version to 6.2.0.Alpha2 (we downgraded to 6.1.7.Final as the tests are all passing with this version)
- Make sure you have a fresh Hibernate ORM 6.2.0-SNAPSHOT around (that means building a fresh 6.2 branch from ORM)
- `./mvnw -Dquickly -pl :quarkus-hibernate-search-orm-elasticsearch-deployment -am`
- `./mvnw -f extensions/hibernate-search-orm-elasticsearch/deployment/ clean verify -Dtest-containers -Dstart-containers -Dtest=SinglePersistenceUnitsCdiTest`

You then get the following error (and I suspect a class loading issue):
```
Caused by: java.util.ServiceConfigurationError: org.hibernate.search.engine.environment.bean.spi.BeanConfigurer: org.hibernate.search.backend.elasticsearch.impl.ElasticsearchBeanConfigurer not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$ProviderSpliterator.tryAdvance(ServiceLoader.java:1484)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.hibernate.search.engine.environment.classpath.spi.DefaultServiceResolver$ClassPathAndModulePathServiceResolver.loadJavaServices(DefaultServiceResolver.java:157)
	at org.hibernate.search.engine.environment.classpath.spi.DefaultServiceResolver$ClassPathAndModulePathServiceResolver.loadJavaServices(DefaultServiceResolver.java:127)
	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateOrmClassLoaderServiceClassAndResourceAndServiceResolver.loadJavaServices(HibernateOrmClassLoaderServiceClassAndResourceAndServiceResolver.java:78)
	at org.hibernate.search.engine.environment.bean.impl.BeanResolverImpl.create(BeanResolverImpl.java:52)
	at org.hibernate.search.engine.common.spi.SearchIntegrationEnvironment.<init>(SearchIntegrationEnvironment.java:72)
	at org.hibernate.search.engine.common.spi.SearchIntegrationEnvironment.<init>(SearchIntegrationEnvironment.java:26)
	at org.hibernate.search.engine.common.spi.SearchIntegrationEnvironment$Builder.build(SearchIntegrationEnvironment.java:167)
	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateSearchPreIntegrationService$Initiator.createEnvironment(HibernateSearchPreIntegrationService.java:167)
	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateSearchPreIntegrationService$Initiator.lambda$initiateService$0(HibernateSearchPreIntegrationService.java:135)
	at org.hibernate.search.mapper.orm.bootstrap.spi.HibernateOrmIntegrationBooterBehavior.bootFirstPhase(HibernateOrmIntegrationBooterBehavior.java:17)
	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateSearchPreIntegrationService$Initiator.initiateService(HibernateSearchPreIntegrationService.java:133)
	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateSearchPreIntegrationService$Initiator.initiateService(HibernateSearchPreIntegrationService.java:80)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:119)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:264)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:239)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:216)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.<init>(FastBootMetadataBuilder.java:182)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:99)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:73)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:40)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$1.created(HibernateOrmRecorder.java:76)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:73)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy(Unknown Source)
```

**Comment by marko-bekhta** [comment]
This problem is  triggered by the change applied here: https://github.com/hibernate/hibernate-search/commit/9e269ee3d23c7cfc62c8774196cd026c3fc7d20b

Going back to a previous approach and just loading the services using the `aggregatedClassLoader` opens another issue:
```
Caused by: org.hibernate.search.util.common.SearchException: HSEARCH700119: Exception while retrieving the Jandex index for code source location 'quarkus:/': HSEARCH900013: Exception while accessing Jandex index for 'quarkus:/': Could not open 'META-INF/jandex.idx' within 'quarkus:/': HSEARCH900016: Cannot open filesystem for code source at 'quarkus:/': HSEARCH900017: Cannot interpret 'quarkus:/' as a local directory or JAR.
	at org.hibernate.search.mapper.pojo.mapping.definition.annotation.impl.AnnotationMappingConfigurationContextImpl.jandexIndexForCodeSourceLocation(AnnotationMappingConfigurationContextImpl.java:213)
	at org.hibernate.search.mapper.pojo.mapping.definition.annotation.impl.AnnotationMappingConfigurationContextImpl.buildJandexIndex(AnnotationMappingConfigurationContextImpl.java:180)
	at org.hibernate.search.mapper.pojo.mapping.definition.annotation.impl.AnnotationMappingConfigurationContextImpl.configure(AnnotationMappingConfigurationContextImpl.java:122)
	at org.hibernate.search.mapper.pojo.mapping.spi.AbstractPojoMappingInitiator.configure(AbstractPojoMappingInitiator.java:134)
	at org.hibernate.search.mapper.orm.mapping.impl.HibernateOrmMappingInitiator.configure(HibernateOrmMappingInitiator.java:161)
	at org.hibernate.search.engine.common.impl.SearchIntegrationBuilder$MappingBuildingState.collect(SearchIntegrationBuilder.java:269)
	at org.hibernate.search.engine.common.impl.SearchIntegrationBuilder.prepareBuild(SearchIntegrationBuilder.java:147)
	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateSearchPreIntegrationService$NotBooted.doBootFirstPhase(HibernateSearchPreIntegrationService.java:258)
	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateOrmIntegrationBooterImpl.preBoot(HibernateOrmIntegrationBooterImpl.java:93)
	at io.quarkus.hibernate.search.orm.elasticsearch.runtime.HibernateSearchElasticsearchRecorder$HibernateSearchIntegrationStaticInitListener.onMetadataInitialized(HibernateSearchElasticsearchRecorder.java:231)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:399)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:101)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:73)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:40)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$1.created(HibernateOrmRecorder.java:76)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:73)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy(Unknown Source)
	... 48 more
Caused by: org.hibernate.search.util.common.SearchException: HSEARCH900013: Exception while accessing Jandex index for 'quarkus:/': Could not open 'META-INF/jandex.idx' within 'quarkus:/': HSEARCH900016: Cannot open filesystem for code source at 'quarkus:/': HSEARCH900017: Cannot interpret 'quarkus:/' as a local directory or JAR.
	at org.hibernate.search.util.common.jar.impl.JandexUtils.readOrBuildIndex(JandexUtils.java:113)
	at org.hibernate.search.mapper.pojo.mapping.definition.annotation.impl.AnnotationMappingConfigurationContextImpl.jandexIndexForCodeSourceLocation(AnnotationMappingConfigurationContextImpl.java:206)
	... 65 more
Caused by: java.io.IOException: Could not open 'META-INF/jandex.idx' within 'quarkus:/': HSEARCH900016: Cannot open filesystem for code source at 'quarkus:/': HSEARCH900017: Cannot interpret 'quarkus:/' as a local directory or JAR.
	at org.hibernate.search.util.common.jar.impl.CodeSource.readOrNull(CodeSource.java:90)
	at org.hibernate.search.util.common.jar.impl.JandexUtils.doReadIndex(JandexUtils.java:127)
	at org.hibernate.search.util.common.jar.impl.JandexUtils.readOrBuildIndex(JandexUtils.java:101)
	... 66 more
Caused by: java.io.IOException: HSEARCH900016: Cannot open filesystem for code source at 'quarkus:/': HSEARCH900017: Cannot interpret 'quarkus:/' as a local directory or JAR.
	at org.hibernate.search.util.common.jar.impl.CodeSource.initFileSystem(CodeSource.java:130)
	at org.hibernate.search.util.common.jar.impl.CodeSource.classesPathOrFail(CodeSource.java:96)
	at org.hibernate.search.util.common.jar.impl.CodeSource.readOrNull(CodeSource.java:50)
	... 68 more
	Suppressed: java.lang.NullPointerException: Cannot read the array length because "buf" is null
		at java.base/java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:108)
		at io.quarkus.bootstrap.classloading.MemoryClassPathElement$MemoryUrlStreamHandler$1.getInputStream(MemoryClassPathElement.java:147)
		at java.base/java.net.URL.openStream(URL.java:1161)
		at org.hibernate.search.util.common.jar.impl.CodeSource.readOrNull(CodeSource.java:80)
		... 68 more
Caused by: java.io.IOException: HSEARCH900017: Cannot interpret 'quarkus:/' as a local directory or JAR.
	at org.hibernate.search.util.common.jar.impl.CodeSource.initFileSystem(CodeSource.java:126)
	... 70 more
```

**Comment by yrodiere** [comment]
@gsmet:

> Hibernate Search 6.2.0.Alpha2 as I thought it would be the version to use to be compatible with ORM 6.2

We regularly test Search 6.1 against ORM 6.2. You can use Search 6.1, that's not a problem at all and the recommended approach at this point (since Search 6.2 is in Alpha).

Though, of course, Search 6.2 is *also* tested regularly against ORM 6.2 and we didn't spot this bug... I don't know what it says about our test suite, but I sure don't like it :/

Anyway, thanks for taking the time to report this, we'll try to find a solution.

@marko-bekhta: The error you're seing about Search not being able to interpret `quarkus:/` should not happen in the first place, because once we upgrade Quarkus to Search 6.2, the Hibernate Search extension for Quarkus should disable any kind of runtime use of Jandex (with something [like this](https://github.com/hibernate/hibernate-search/blob/161a40deaf3428bf3a2c933f9522ccecdbafc560/documentation/src/test/java/org/hibernate/search/documentation/mapper/pojo/standalone/mapping/config/MappingConfigurationIT.java#L52-L54)). The extension should compensate by doing annotation discovery at build time.

So, let's focus on fixing the classloading issue here (either by reverting your change, or by finding what's wrong exactly). We'll address the Search 6.2 upgrade in Quarkus another time.

**Comment by yrodiere** [comment]
Upstream issue: https://hibernate.atlassian.net/browse/HSEARCH-4803

**Comment by gsmet** [comment]
This is an upstream issue and it is not disrupting Quarkus 3 so closing.
