### ISSUE TITLE
@QuarkusTest - java.lang.ClassNotFoundException: jakarta.interceptor.Interceptor

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#31264]
### Describe the bug

After migrating to Quarkus 3.0.0.Alpha4 there are a couple of scenarios where I'm seeing `[error]: Build step io.quarkus.arc.deployment.ArcProcessor#quarkusMain threw an exception: java.lang.NoClassDefFoundError: jakarta/interceptor/Interceptor`.

I'm seeing it for a `@QuarkusTest` in a library project (the test simulates an app proving the library) and for a very simple service when performing `mvn quarkus:dev`.  15 other services are fine.  Initial suspicion is that it's related to the limited dependencies in these projects.  Only direct Quarkus dependencies in the library project are `quarkus-resteasy-reactive-common` and `quarkus-smallrye-openapi`.  Only direct Quarkus dependency in the service is `quarkus-resteasy-reactive-jackson`.

I note that other services obtain `jakarata.interceptor-api` transitively via `quarkus-hibernate-orm`, `quarkus-security` and probably others.  I can resolve by adding `jakarata.interceptor-api` myself.

Hopefully this just means `jakarata.interceptor-api` needs to be added to `quarkus-resteasy-reactive-common`?

I can try and make a simple reproducer if the answer is not already obvious.

Sample stack trace:
```
java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#quarkusMain threw an exception: java.lang.NoClassDefFoundError: jakarta/interceptor/Interceptor
	at io.quarkus.arc.processor.DotNames.<clinit>(DotNames.java:88)
	at io.quarkus.arc.deployment.ArcProcessor.quarkusMain(ArcProcessor.java:759)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.ClassNotFoundException: jakarta.interceptor.Interceptor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
	... 13 more

	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:625)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:696)
```

### Quarkus version or git rev

Quarkus 3.0.0.Alpha4

**Comment by gastaldi** [comment]
Thanks for the issue, if you could provide a minimalistic reproducer project that would be great

**Comment by gsmet** [comment]
I'll have a look on Monday.

**Comment by gsmet** [comment]
@jimbogithub I had a quick look and jakarta.interceptor-api is a dependency of `quarkus-resteasy-reactive-common`.

```
$ pwd
/home/gsmet/git/quarkus/extensions/resteasy-reactive/quarkus-resteasy-reactive-common/runtime
$ mvn dependency:tree | grep interceptor
[INFO] |  |  +- jakarta.interceptor:jakarta.interceptor-api:jar:2.1.0:compile
```

Maybe check your dependency tree (and that the version of `jakarta.interceptor-api` is similar) and if you don't see anything obvious, please post it here. And if we can't find anything obvious, we will need a small reproducer.

**Comment by jimbogithub** [comment]
Looks like this is caused by the `jakarta.jakartaee-bom:10.0.0` excluding transitive dependencies, e.g:
```
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<version>${jakarta.enterprise.cdi-api.version}</version>
			<optional>false</optional>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
Earlier versions don't have these exclusions.

I have upstream library projects that use the bom to import versions.  I can resolve by ranking `io.quarkus.platform.quarkus-bom` higher than those libraries in the downstream projects. So not a Quarkus issue.  But while we're here, does the Quarkus team have any insight into why the `jakartaee-bom` has changed?  I prefer to use this to import versions (for non Quarkus specific projects) rather than the blanket `jakartaee-api` import everything as `provided` that seems to be a common pattern.

**Comment by Snorri1986** [comment]
Hi.
Today I have found the solution how to fix this error.
It related with local Maven repo.
Delete all files from .m2/repository and build a project once again.
Maven will download all needed with dependencies.
Let me know when I am wrong.

**Comment by gsmet** [comment]
Let's close this issue then. Thanks.
