### ISSUE TITLE
drop-and-create does not work for DB2 at the first time

### ISSUE THREAD

**Issue by mcanzerini** [quarkusio/quarkus#31371]
### Describe the bug

When I configure a new quarkus app with DB2 connection, I cannot set the property: 
`quarkus.hibernate-orm.database.generation=drop-and-create` because quarkus will try to drop some tables that do not exist yet and raises this error:

```
GenerationTarget encountered exception accepting command : Error executing DDL "drop sequence MY_SCHEMA.MY_SEQUENCE restrict" via JDBC Statement: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "drop sequence MY_SCHEMA.MY_SEQUENCE restrict" via JDBC Statement
        at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
        at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlString(SchemaDropperImpl.java:387)
        at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlStrings(SchemaDropperImpl.java:371)
        at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropFromMetadata(SchemaDropperImpl.java:256)
        at org.hibernate.tool.schema.internal.SchemaDropperImpl.performDrop(SchemaDropperImpl.java:156)
        at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:128)
        at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:114)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:157)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:85)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:335)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:74)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:167)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:68)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=MY_SCHEMA.MY_SEQUENCE, DRIVER=4.32.28
``` 

To make this works, I have to set `quarkus.hibernate-orm.database.generation=create` the first time, then set `quarkus.hibernate-orm.database.generation=drop-and-create` after that.

It is not blocking, but quite annoying. Maybe you could add a 'IF EXISTS' clause to the DROP statement ?

### Expected behavior

When starting for the first time my app with: `quarkus.hibernate-orm.database.generation=drop-and-create`, do not raise an error if the DB is empty and start the application normally after creating the structure

### Actual behavior

When starting for the first time my app with: `quarkus.hibernate-orm.database.generation=drop-and-create`, quarkus raises an error telling me that the tables do not exist (they don't actually, because it is the first time)

**Comment by GregJohnStewart** [comment]
I'm noticing similar issues, though setting to just create doesn't fix. To me it feels like there are issues with perhaps ordering of the tables being created, based on my errors being related to foreign key issues.

**Comment by yrodiere** [comment]
Sorry for the (very) late answer.

Could you clarify whether this is just a warning log which happens to include a stacktrace, or an actual failure to start?

We'd need a reproducer to investigate...

> Maybe you could add a 'IF EXISTS' clause to the DROP statement ?

As far as I know, Hibernate ORM adds `IF EXISTS` when the DB supports it. Maybe some earlier DB2 versions didn't support `IF EXISTS`, I'd have to check... in any case, [setting your DB version](https://quarkus.io/guides/hibernate-orm#hibernate-dialect-supported-databases) will ensure Hibernate ORM uses the most appropriate SQL it can. Could you tell us if that fixes your problem?

**Comment by geoand** [comment]
Closing for a lack of a reproducer
