### ISSUE TITLE
Error opening config URL is ignored

### ISSUE THREAD

**Issue by geertschuring** [quarkusio/quarkus#31402]
### Describe the bug

When using `quarkus.config.locations` quarkus swallows errors when the listed URLs cannot be opened.

### Expected behavior

Quarkus should use the Fail Early paradigm and fail to start, throwing a clear error that states which given configuration location could not be found.
Optionally another config option could be added to enable ignoring failed config lookups, but this should not be the default.

### Actual behavior

Quarkus starts as if all is well and silently ignores the error that happend when trying to read the configuration.

### How to Reproduce?

Run any quarkus application like this:

```
java -Dquarkus.config.locations=https://example.com/clearly-wrong.properties -jar target\greeting-service-1.0.0-SNAPSHOT-runner.jar
```

### Quarkus version or git rev

2.13.5.Final-redhat-00002

**Comment by radcortez** [comment]
Hum... the community version works as expected. I get an error when running the Quarkus app with an invalid URL:

```console
java -Dquarkus.config.locations=https://example.com/clearly-wrong.properties -jar target/quarkus-app/quarkus-run.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
Caused by: java.lang.ExceptionInInitializerError
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:68)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:122)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	... 6 more
Caused by: java.lang.IllegalStateException: SRCFG00035: Failed to load resource
	at io.smallrye.config.AbstractLocationConfigSourceLoader.addConfigSource(AbstractLocationConfigSourceLoader.java:230)
	at io.smallrye.config.AbstractLocationConfigSourceLoader.addConfigSource(AbstractLocationConfigSourceLoader.java:221)
	at io.smallrye.config.AbstractLocationConfigSourceLoader.tryHttpResource(AbstractLocationConfigSourceLoader.java:184)
	at io.smallrye.config.AbstractLocationConfigSourceLoader.loadConfigSources(AbstractLocationConfigSourceLoader.java:100)
	at io.smallrye.config.AbstractLocationConfigSourceLoader.loadConfigSources(AbstractLocationConfigSourceLoader.java:81)
	at io.smallrye.config.AbstractLocationConfigSourceFactory.getConfigSources(AbstractLocationConfigSourceFactory.java:30)
	at io.smallrye.config.PropertiesLocationConfigSourceFactory.getConfigSources(PropertiesLocationConfigSourceFactory.java:16)
	at io.smallrye.config.ConfigurableConfigSource.getConfigSources(ConfigurableConfigSource.java:50)
	at io.smallrye.config.SmallRyeConfig$ConfigSources.mapLateSources(SmallRyeConfig.java:664)
	at io.smallrye.config.SmallRyeConfig$ConfigSources.<init>(SmallRyeConfig.java:554)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:68)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:449)
	at io.quarkus.runtime.generated.Config.<clinit>(Unknown Source)
	... 16 more
Caused by: java.io.FileNotFoundException: https://example.com/clearly-wrong.properties
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at io.smallrye.common.classloader.ClassPathUtils.readStream(ClassPathUtils.java:200)
	at io.smallrye.common.classloader.ClassPathUtils.consumeStream(ClassPathUtils.java:169)
	at io.smallrye.config.common.utils.ConfigSourceUtil.urlToMap(ConfigSourceUtil.java:65)
	at io.smallrye.config.PropertiesConfigSource.<init>(PropertiesConfigSource.java:46)
	at io.smallrye.config.PropertiesLocationConfigSourceFactory.loadConfigSource(PropertiesLocationConfigSourceFactory.java:21)
	at io.smallrye.config.AbstractLocationConfigSourceLoader.addConfigSource(AbstractLocationConfigSourceLoader.java:226)
	... 28 more
```

@geertschuring can you please confirm?

On another hand, I did notice that starting with `2.16.x` the exception is not being properly propagated to the DevMojo:

Before `2.16.x`:

```console
mvn quarkus:dev -Dquarkus.config.locations=https://example.com/clearly-wrong.properties
2023-03-02 13:18:44,105 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-03-02 13:18:44,393 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.IllegalStateException: SRCFG00035: Failed to load resource
	at io.smallrye.config.AbstractLocationConfigSourceLoader.addConfigSource(AbstractLocationConfigSourceLoader.java:230)
	at io.smallrye.config.AbstractLocationConfigSourceLoader.addConfigSource(AbstractLocationConfigSourceLoader.java:221)
	at io.smallrye.config.AbstractLocationConfigSourceLoader.tryHttpResource(AbstractLocationConfigSourceLoader.java:184)
	at io.smallrye.config.AbstractLocationConfigSourceLoader.loadConfigSources(AbstractLocationConfigSourceLoader.java:100)
	at io.smallrye.config.AbstractLocationConfigSourceLoader.loadConfigSources(AbstractLocationConfigSourceLoader.java:81)
	at io.smallrye.config.AbstractLocationConfigSourceFactory.getConfigSources(AbstractLocationConfigSourceFactory.java:30)
	at io.smallrye.config.PropertiesLocationConfigSourceFactory.getConfigSources(PropertiesLocationConfigSourceFactory.java:16)
	at io.smallrye.config.ConfigurableConfigSource.getConfigSources(ConfigurableConfigSource.java:50)
	at io.smallrye.config.SmallRyeConfig$ConfigSources.mapLateSources(SmallRyeConfig.java:664)
	at io.smallrye.config.SmallRyeConfig$ConfigSources.<init>(SmallRyeConfig.java:554)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:68)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:449)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:184)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:105)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:328)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:87)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:448)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:60)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:148)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:103)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.io.FileNotFoundException: https://example.com/clearly-wrong.properties
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at io.smallrye.common.classloader.ClassPathUtils.readStream(ClassPathUtils.java:200)
	at io.smallrye.common.classloader.ClassPathUtils.consumeStream(ClassPathUtils.java:169)
	at io.smallrye.config.common.utils.ConfigSourceUtil.urlToMap(ConfigSourceUtil.java:65)
	at io.smallrye.config.PropertiesConfigSource.<init>(PropertiesConfigSource.java:46)
	at io.smallrye.config.PropertiesLocationConfigSourceFactory.loadConfigSource(PropertiesLocationConfigSourceFactory.java:21)
	at io.smallrye.config.AbstractLocationConfigSourceLoader.addConfigSource(AbstractLocationConfigSourceLoader.java:226)
	... 23 more
```

After  `2.16.x`:

```console
mvn quarkus:dev -Dquarkus.config.locations=https://example.com/clearly-wrong.properties
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.593 s
[INFO] Finished at: 2023-03-02T13:19:50Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.16.0.Final:dev (default-cli) on project number-api: Failed to run: Dev mode process did not complete successfully -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

@aloubyansky any thoughts?

**Comment by geertschuring** [comment]
@radcortez I can confirm that we are not on the community version but on 2.13.5.Final-redhat-00002 because my client has RedHat support contract. Perhaps I should file this issue through the proper support channels, but if this problem is already fixed upstream then we can probably expect a fix in the next redhat release of Quarkus.

**Comment by geertschuring** [comment]
I must say that the stack trace thrown by the community version is not what I would expect either. A more to-the-point error message stating which config location was not found would be better. Without stack trace.
