### ISSUE TITLE
com.github.beanio:beanio:3.0.0.M2 not working in native build

### ISSUE THREAD

**Issue by Manfred73** [quarkusio/quarkus#31443]
### Describe the bug

Maybe not a bug, but some configuration issue?

I have a service which processes a file using the com.github.beanio:beanio:3.0.0.M2 to parse some records into an object.
This works fine in a normal (non native) build, but fails with a native image.

I have a configuration class with the following piece of code which should create a beanio StreamFactory:

```
@Produces
@ApplicationScoped
public StreamFactory produceFileStreamFactory() {
	final var streamFactory = StreamFactory.newInstance();
	final var builder = new StreamBuilder("file")
			.format("fixedlength")
			.ignoreUnidentifiedRecords()
			.addRecord(FileRecord.class);
	streamFactory.define(builder);
	return streamFactory;
}
```

And in my class that processes the file, I use this factory. However, when running a native image, I get a NullPointerException on the factory.createReader, because factory is null:

```
@ApplicationScoped
@AllArgsConstructor
public class FileProcessor {

	private final StreamFactory factory;     // IN NATIVE IMAGE THIS IS NULL!
	private final RecordProcessor recordProcessor
	private final Logger logger;

	public void processFile(Long id) throws IOException {
		try {
			try (final var br = getReader(id); // reads file with id
					final var beanReader = factory.createReader("file", br)) { // NullPointerException since factory is null
				var record = (FileRecord) beanReader.read();
				while (notEndOfFile(record)) {
					processRecord(record);
					record = (FileRecord) beanReader.read();
				}
			}
		} catch (Exception e) {
			logger(e); // logs the NullPointerException
			throw e;
		}
	}
	// some more methods
}
```

The QuarkusIntegrationTest fails and shows a stacktrace (see below), which doesn't really give a clue to what was wrong until I caught and logged the exception.
My guess is that the beanio factory doesn't work out of the box and I need to configure something with regards to reflection? I have tried to add a `ReflectionsConfig` class, but that didn't help (maybe it needs more configuration?):

```
import io.quarkus.runtime.annotations.RegisterForReflection;
import org.beanio.BeanReader;
import org.beanio.StreamFactory;

@RegisterForReflection(targets = {
		BeanReader.class,
		StreamFactory.class
})
public class ReflectionsConfig {
}
```

How could I get beanio to work with a native image?

The stacktrace:
```
Expected status code <200> but was <500>.

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:499)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:684)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:127)
	at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
	at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
	at io.restassured.internal.ValidatableResponseImpl.super$2$statusCode(ValidatableResponseImpl.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy:142)
	at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
	at com.mycompany.fileprocessor.integrationtests.ProcessFileSuccessIntegrationTest.expect_status_code_200(ProcessFileSuccessIntegrationTest.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

```

### Expected behavior

Expect factory to be created and no NullPointerException.

### Actual behavior

Factory is null and NullPointerException occurs.

### Output of `uname -a` or `ver`

Linux ..... 5.15.0-60-generic #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.6

**Comment by gsmet** [comment]
The `StreamFactory` is loaded via reflection from a class name:

https://github.com/beanio/beanio/blob/main/src/org/beanio/StreamFactory.java#L314-L351

What you need is to register for reflection the implementation(s) of `StreamFactory` so probably at least [`DefaultStreamFactory`](https://github.com/beanio/beanio/blob/main/src/org/beanio/internal/DefaultStreamFactory.java), maybe others.

Not sure it's the only issue though.

This library might be a good candidate for a Quarkiverse extension if you get it to work. Please post your findings!

**Comment by Manfred73** [comment]
That gives me the error:

```
org.beanio.BeanIOException: Failed to load stream factory implementation class 'org.beanio.internal.DefaultStreamFactory'
```

So that could be because I need to add others as well?

**Comment by gsmet** [comment]
Hard to know without the full stacktrace. AFAICS from the code the stacktrace should contain the cause.

Making libraries work in native is a bit of a detective work. That's why we try to create extensions to do that once for all users.

**Comment by Manfred73** [comment]
Having an extension for this would indeed be great.

I've added also the following classes to the `ReflectionConfig`:

```
@RegisterForReflection(targets = {
		DefaultStreamFactory.class,
		StreamCompiler.class,
		XmlConfigurationLoader.class,
		XmlMappingReader.class,
		DocumentBuilderFactory.class
})
public class ReflectionsConfig {
}
```

Stacktrace:
```
org.beanio.BeanIOException: Failed to load stream factory implementation class 'org.beanio.internal.DefaultStreamFactory'
	at org.beanio.StreamFactory.newInstance(StreamFactory.java:348)
	at org.beanio.StreamFactory.newInstance(StreamFactory.java:299)
	at com.mycompany.fileprocessor.config.FileStreamFactoryProducer.produceFileStreamFactory(FileStreamFactoryProducer.java:23)
	at com.mycompany.fileprocessor.config.FileStreamFactoryProducer_ProducerMethod_produceFileStreamFactory_8304fac9f10e29732c177a5a614f950906d815ca_Bean.create(Unknown Source)
	at com.mycompany.fileprocessor.config.FileStreamFactoryProducer_ProducerMethod_produceFileStreamFactory_8304fac9f10e29732c177a5a614f950906d815ca_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at org.beanio.FileStreamFactoryProducer_ProducerMethod_produceFileStreamFactory_8304fac9f10e29732c177a5a614f950906d815ca_ClientProxy.arc$delegate(Unknown Source)
	at org.beanio.FileStreamFactoryProducer_ProducerMethod_produceFileStreamFactory_8304fac9f10e29732c177a5a614f950906d815ca_ClientProxy.createReader(Unknown Source)
	at com.mycompany.fileprocessor.FileProcessor.processFile(FileProcessor.java:32)
	at com.mycompany.fileprocessor.FileProcessor_ClientProxy.processFile(Unknown Source)
	at com.mycompany.fileprocessor.FileProcessorService.processFile(FileProcessorService.java:17)
	at com.mycompany.fileprocessor.FileProcessorService_ClientProxy.processFile(Unknown Source)
	at com.mycompany.fileprocessor.FileProcessorResource.processFile(FileProcessorResource.java:31)
	at com.mycompany.fileprocessor.FileProcessorResource_Subclass.processFile$$superforward1(Unknown Source)
	at com.mycompany.fileprocessor.FileProcessorResource_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
	at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor.validateMethodInvocation(ResteasyReactiveEndPointValidationInterceptor.java:21)
	at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at com.mycompany.fileprocessor.FileProcessorResource_Subclass.processFile(Unknown Source)
	at com.mycompany.fileprocessor.FileProcessorResource$quarkusrestinvoker$processFile_b434c40488a5b94ed5f2993155d2d3d2b99ccfae.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.lang.NullPointerException
	at org.beanio.internal.config.xml.XmlMappingReader.createDocumentBuilderFactory(XmlMappingReader.java:127)
	at org.beanio.internal.config.xml.XmlMappingReader.<init>(XmlMappingReader.java:50)
	at org.beanio.internal.config.xml.XmlConfigurationLoader.<init>(XmlConfigurationLoader.java:34)
	at org.beanio.internal.compiler.StreamCompiler.<init>(StreamCompiler.java:48)
	at org.beanio.internal.DefaultStreamFactory.init(DefaultStreamFactory.java:43)
	at org.beanio.StreamFactory.newInstance(StreamFactory.java:344)
	... 41 more
```

**Comment by gsmet** [comment]
I can help but you will have to dig a bit for yourself.

The problem here is that the XSD resource is missing here:
https://github.com/beanio/beanio/blob/main/src/org/beanio/internal/config/xml/XmlMappingReader.java#L127

Which is expected in a native executable, you need to register the resources to include.

See https://quarkus.io/guides/writing-native-applications-tips#including-resources

Once you have something working, we can easily create an extension if you post all your findings (ideally in the form of a small Maven project that could be used as a test case for the extension).

**Comment by gsmet** [comment]
Exactly. You need to register all the static resources from the jar.

**Comment by Manfred73** [comment]
Seems to get a bit further after including:

```
quarkus:
  native:
    resources:
      # See: https://quarkus.io/guides/writing-native-applications-tips:
      includes: "org/beanio/internal/**/*.properties,org/beanio/xsd/**/*.xsd"
```

On to the next: seems `FixedLengthParserFactory` is not present in the native build:
```
Caused by: java.lang.ClassNotFoundException: org.beanio.internal.compiler.fixedlength.FixedLengthParserFactory
	at java.base@17.0.6/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
	at java.base@17.0.6/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base@17.0.6/java.lang.ClassLoader.loadClass(ClassLoader.java:132)
	at org.beanio.internal.util.BeanUtil.createBean(BeanUtil.java:83)
```

**Comment by gsmet** [comment]
Yeah so that's similar to the problem you had before with the factory. Just include it for reflection.

You should be able to overcome most problems with the two tricks I showed you but there might be some more problematic ones, you will see.

**Comment by Manfred73** [comment]
Thanks for the tips, finally got it working for my service with only the following minimal `ReflectionConfig`:

```
@RegisterForReflection(targets = {
		DefaultStreamFactory.class,
		FixedLengthParserFactory.class })
public class ReflectionsConfig {
}
```

and including the properties and xsds:

```
quarkus:
  native:
    resources:
      # See: https://quarkus.io/guides/writing-native-applications-tips:
      includes: "org/beanio/internal/**/*.properties,org/beanio/xsd/**/*.xsd"
```

Since `FixedLengthParserFactory` is the only one I use, this is working for me now, but beanio has multiple parser factories like `CsvParserFactory`, `DelimitedParserFactory`, `FlatParserFactory`, `JsonParserFactory`, and `XmlParserFactory`.

If I were to use any of these, they would have to be registered for reflection as well. Maybe something to be included for an extension then?

**Comment by gsmet** [comment]
If you provide a small Maven project with an included test (no need for the native stuff that you described here, just a working test case with JUnit 5 and BeanIO), I can have a look at preparing an extension.

**Comment by Manfred73** [comment]
Great, I'll see if I can find some time for that this week.

**Comment by melloware** [comment]
@Manfred73 a nice trick you can use is look if all the factories extend any base class. If they do we can do a "registerAllImplementations" of that base class so you don't have to list them all.   This seems like it would be a pretty easy library to add an extension for.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by Manfred73** [comment]
I solved this more than a year ago by adding the required classes to the reflection config and adding static resources from the dependency.

**Comment by geoand** [comment]
Thanks for the update!
