### ISSUE TITLE
Warnings about lack of "Hibernate Validator", despite no validation annotations being used

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#31469]
### Describe the bug

I have an application, which uses `quartz`,`agroal` and `hibernate-panache` and saves data into DB on regular intervals. After update to the latest 999-SNAPSHOT(1d45952917c72a12eed6b9351f6ecdca813637a8) it now shows multiple warnings about `jakarta.validation.NoProviderFoundException` being thrown. The application doesn't use any code from `javax.validation` or `jakarta.validation` packages. Adding `quarkus-hibernate-validator` solves this problem. Nothing of sorts is mentioned in the migration guide[1].

[1] https://docs.jboss.org/hibernate/orm/6.0/migration-guide/migration-guide.html

### Expected behavior

The application should work without warnings, and should not require `quarkus-hibernate-validator`

### Actual behavior

```
(JPA Startup Thread) Error calling `jakarta.validation.Validation#buildDefaultValidatorFactory`: jakarta.validation.NoProviderFoundException: Unable to create a Configuration, because no Jakarta Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at jakarta.validation.Validation$GenericBootstrapImpl.configure(Validation.java:291)
	at jakarta.validation.Validation.buildDefaultValidatorFactory(Validation.java:103)
	at org.hibernate.boot.beanvalidation.TypeSafeActivator.getValidatorFactory(TypeSafeActivator.java:483)
	at org.hibernate.boot.beanvalidation.TypeSafeActivator.activate(TypeSafeActivator.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.hibernate.boot.beanvalidation.BeanValidationIntegrator.integrate(BeanValidationIntegrator.java:140)
	at org.hibernate.internal.SessionFactoryImpl.integrate(SessionFactoryImpl.java:451)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:247)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:200)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:78)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:73)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:167)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:68)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

1. ` git clone git@github.com:fedinskiy/beefy-scenarios.git -b reproducer/hibernate-6`
2. `beefy-scenarios/017-quartz-cluster`
3. `mvn clean verify #exceptions in logs`
4. add ```        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>```
        to pom.xml
5. Run `mvn clean verify # no exceptions in app logs `
6.  If command in step 3 uses ` -Dquarkus.platform.version=3.0.0.Alpha4`, then the app works even without `hibernate-validator`

The app doesn't use any validation: `find src/ | xargs grep 'validation'`

### Output of `uname -a` or `ver`

6.0.18-300.fc37.x86_64

### Output of `java -version`

17.0.5, vendor: GraalVM Community

### Quarkus version or git rev

1d45952917c72a12eed6b9351f6ecdca813637a8

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

Probably related to https://github.com/quarkusio/quarkus/pull/31235

**Comment by yrodiere** [comment]
That's probably related to https://github.com/quarkusio/quarkus/pull/30617, though I'll have to investigate to know what's happening exactly

**Comment by gsmet** [comment]
Yes this is known, has been reported, AFAIK fixed in Hibernate ORM and we are waiting for a new version. I will work around it for the time being.
