### ISSUE TITLE
quarkus.test.arg-line has become a built-time fixed property in 2.16.4

### ISSUE THREAD

**Issue by michael-simons** [quarkusio/quarkus#31626]
### Describe the bug

When upgrading from 2.16.3 to 2.16.4, `quarks.test.arg-line` suddenly is a built time fixed property and cannot be used anymore to pass existing configuration (like JaCoCo and co) anymore.

### Actual behavior

```
java.lang.IllegalStateException: Build time property cannot be changed at runtime:
[2140](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2141)
 - quarkus.test.arg-line is set to '-javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8-runtime.jar=destfile=/home/runner/work/neo4j-migrations/neo4j-migrations/neo4j-migrations-quarkus-parent/integration-tests/target/jacoco.exec,append=true,includes=**/*' but it is build time fixed to ''. Did you change the property quarkus.test.arg-line after building the application?
[2141](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2142)
	at io.quarkus.runtime.configuration.ConfigRecorder.handleConfigChange(ConfigRecorder.java:66)
[2142](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2143)
	at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange1532146938.deploy_5(Unknown Source)
[2143](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2144)
	at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange1532146938.deploy(Unknown Source)
[2144](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2145)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
[2145](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2146)
	at io.quarkus.runtime.Application.start(Application.java:101)
[2146](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2147)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
[2147](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2148)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
[2148](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2149)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
[2149](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2150)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
[2150](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2151)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
[2151](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2152](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2153](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2154)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2154](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2155)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2155](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2156)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
[2156](https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2157)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.16.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

### Additional information

Failing test is here https://github.com/michael-simons/neo4j-migrations/actions/runs/4342849831/jobs/7584165451#step:10:2141

Config in question https://github.com/michael-simons/neo4j-migrations/blob/main/neo4j-migrations-quarkus-parent/integration-tests/pom.xml#L141, basically taking from https://quarkus.io/guides/tests-with-coverage

**Comment by michael-simons** [comment]
Could be related to this https://github.com/quarkusio/quarkus/commit/8c3e47c9473ee03713c8be37c672744275251344

**Comment by geoand** [comment]
@radcortez any idea?

**Comment by radcortez** [comment]
I'll have a look

**Comment by michael-simons** [comment]
🎉 thanks!

**Comment by michael-simons** [comment]
I can confirm the fix works, thanks @radcortez and @gsmet
