### ISSUE TITLE
@Blocking doesn't work

### ISSUE THREAD

**Issue by mpusg** [quarkusio/quarkus#31677]
Hi guys. 

### Describe the bug

@Blocking does not seem to be taken into account when using a reactive call stack. 

"""
Annotation used to indicate that the annotated method is inherently blocking and so should not be executed on a non-blockable thread (I/O thread, event loops...)
"""

### Expected behavior

Using another thread pool than vertx when @Blocking is detected

### Actual behavior

The example of the code logs a WARN because we see a vert.x-eventloop-thread used. 

```
2023-03-08 09:32:42,616 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3688 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at java.base@17.0.6/java.lang.Thread.sleep(Native Method)
        at org.test.GreetingResource.schedule(GreetingResource.java:39)
        at org.test.GreetingResource.hello(GreetingResource.java:26)
        at org.test.GreetingResource$quarkusrestinvoker$hello_d1fd18c65b32335d71a4b7282527a960c5fc08f2.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:101)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:87)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:290)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl$$Lambda$959/0x000000080113e208.handle(Unknown Source)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.vertx.core.impl.future.FutureBase$$Lambda$936/0x0000000801135c68.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

```java
@ApplicationScoped
public class GreetingResource {
    private static final Logger log = LoggerFactory.getLogger(GreetingResource.class);
    private final Semaphore semaphore = new Semaphore(1);

    @Scheduled(every = "1s")
    Uni<Void> everySecond() throws InterruptedException {
        schedule();
        return Uni.createFrom().voidItem();
    }
    
    @Blocking
    public void schedule() throws InterruptedException {
        log.info("scheduler run new thread");
        if (semaphore.tryAcquire(10, SECONDS)) {

            log.info("thread in activity");
            try {
                Thread.sleep(50000);
            } finally {
                semaphore.release();
            }
        }
    }
}
```

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS                            
OpenJDK Runtime Environment (build 17.0.6+10-LTS)                  
OpenJDK 64-Bit Server VM (build 17.0.6+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)                                 
Maven home: E:\git\scoop\apps\maven\current                                                   
Java version: 17.0.6, vendor: BellSoft, runtime: E:\git\scoop\apps\liberica17-full-jdk\current
Default locale: en_US, platform encoding: Cp1252                                              
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"                      

### Additional information

Thanks !

**Comment by geoand** [comment]
Thanks for reporting.

Unfortunately this **not** how `@Blocking` works. 
The purpose of the annotation is to inform Quarkus on which thread to execute the call of a method that is under framework control - it has no effect on methods called directly by user code.

**Comment by vsevel** [comment]
@geoand I believe it is the same behavior, even if `@Blocking` is put on the  `everySecond()``method. @mpusg can you check?

**Comment by geoand** [comment]
Hm... I don't think `@Blocking` applies to scheduled methods in general, although maybe is should - cc @mkouba @cescoffier

**Comment by mpusg** [comment]
Yes, you're right @vsevel. Same behavior.

**Comment by vsevel** [comment]
> although maybe is should

I agree.
if not,  how can we switch back to a non vertx thread?

**Comment by geoand** [comment]
Do you mind explaining the use case a little? I understrand the code in the issue is pretty artificial and just meant to show the problem at hand, but I would like to better understand what exactly you are trying to accomplish.

**Comment by vsevel** [comment]
> By default, a scheduled method is executed on the main executor for blocking tasks

is that true @mkouba ? so when I write:
``` 
    @Scheduled(every = "1s")
    // @Blocking
    void everySecond() {
        log.info("thread = " + Thread.currentThread().getName());
    }
```

why does it print: 
```
2023-03-10 10:42:01,001 INFO  [com.lod.art.ban.qua.GreetingResource] (vert.x-worker-thread-0) thread = vert.x-worker-thread-0
```


from what you say it should already be working.
I am wondering if this related to the reactive extensions we are using in the app.
@mpusg can you check on a simple app?

**Comment by vsevel** [comment]
> That's ok. It's the Vert.x worker thread that can be used to execute blocking tasks, i.e. it's not executed on the event loop.

ah
then it should not print 
```
2023-03-10 10:59:17,703 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-worker-thread-0,5,main] has been
 blocked for 61688 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked
        at java.base@17.0.3/java.lang.Thread.sleep(Native Method)
        at com.lodh.arte.bank.quarkus.GreetingResource.everySecond(GreetingResource.java:58)
```

**Comment by mkouba** [comment]
> > That's ok. It's the Vert.x worker thread that can be used to execute blocking tasks, i.e. it's not executed on the event loop.
> 
> ah then it should not print
> 
> ```
> 2023-03-10 10:59:17,703 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-worker-thread-0,5,main] has been
>  blocked for 61688 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked
>         at java.base@17.0.3/java.lang.Thread.sleep(Native Method)
>         at com.lodh.arte.bank.quarkus.GreetingResource.everySecond(GreetingResource.java:58)
> ```

It should not. How does your actual code look like?

**Comment by mkouba** [comment]
But you're right that the warning is printed. @cescoffier is that intentional?

**Comment by vsevel** [comment]
``` 
    @Scheduled(every = "1s", concurrentExecution = Scheduled.ConcurrentExecution.SKIP)
    // @Blocking
    void everySecond() throws InterruptedException {
        Thread.sleep(65000L);
        log.info("thread = " + Thread.currentThread().getName());
    }
```

**Comment by mpusg** [comment]
@vsevel we are no difference if you use or not, a reactive dependency like quarkus-resteasy-reactive.

**Comment by vsevel** [comment]
> but I would like to better understand what exactly you are trying to accomplish.

@geoand in the absence of https://github.com/quarkusio/quarkus/issues/30943, we used the poor man approach of pulling messages regularly using a scheduler, https://github.com/quarkiverse/quarkus-pooled-jms and https://github.com/quarkiverse/quarkus-artemis. 
it is far from where I want to be, but we can't wait. hopefully we will have a better solution at some point.

so we are doing something like this (pseudo-code):
```
    @Scheduled(every = "1s")
    private void consumeMessages() throws JMSException {
        try (Connection connection = factory.createConnection();
                Session session = connection.createSession(Session.SESSION_TRANSACTED);
                MessageConsumer consumer = session.createConsumer(queue)) {
            connection.start();
            var instant = LocalTime.now();
            while (stillHasTimeToProcessMessagesAndServerIsNotShuttingDown(instant)) {
                var message = consumer.receive(MESSAGE_RECEPTION_TIMEOUT.toMillis());
                if (message != null) {
                    // do something with message and commit or rollback
                }
            }
        }
    }
```

**Comment by geoand** [comment]
Thanks for the information @vsevel.

And may I ask how reactive fits into the picture you painted above?

**Comment by vsevel** [comment]
> And may I ask how reactive fits into the picture you painted above?

it does not.
when we saw the warning, we wrongly assumed that we were executing on the event loop.
I missed that we were executing on `vert.x-worker-thread-0` and not `vert.x-eventloop-thread-0`, as spotted by @mkouba 
I saw `vertx`, and I assumed reactive. sorry for the confusion.

so in the end, I believe the issue is relevant, but it should be: _BlockedThreadChecker incrorrectly complains about vertx worker thread being blocked_. or is this wanted? I am seeing the alert in the warning that the configured timeout is 1 minute. so is this 
a specific timeout of operations on vertx worker threads. seems to be the case in https://github.com/quarkusio/quarkus/issues/16390#issuecomment-903879436 also
so if this the case, I guess I was mistaken twice. I did not know that `BlockedThreadChecker` was monitoring worker threads as well.

**Comment by geoand** [comment]
Yeah, I would say that for schedule tasks, we probably don't want to have such messages being logged.

**Comment by mkouba** [comment]
> Yeah, I would say that for schedule tasks, we probably don't want to have such messages being logged.

@vsevel @geoand There is a config property to specify the timeout to log a warning for worker threads: [quarkus.vertx.max-worker-execute-time](https://quarkus.io/guides/vertx-reference#quarkus-vertx-core_quarkus.vertx.max-worker-execute-time).

**Comment by geoand** [comment]
@mkouba sure yeah, my point is that even though the same executor is used, scheduled tasks probably should not be log the warning why other should

**Comment by mkouba** [comment]
> @mkouba sure yeah, my point is that even though the same executor is used, scheduled tasks probably should not be log the warning why other should

Hm, I don't see a difference between a scheduled task and for example a task submitted manually via `Vertx.executeBlocking()`.

In any case, e.g. `quarkus.vertx.max-worker-execute-time=2m` would solve the problem in this particular example ;-)

**Comment by vsevel** [comment]
> In any case, e.g. quarkus.vertx.max-worker-execute-time=2m would solve the problem in this particular example ;-)

ok thanks @mkouba I was looking for it ;)

another strange behavior, for the same code, I have:
```
$ mvn compile quarkus:dev
...
2023-03-10 13:49:44,001 INFO  [com.lod.art.ban.qua.gre.GreetingResource] (vert.x-worker-thread-0) Thread = vert.x-worker-thread-0
2023-03-10 13:49:45,001 INFO  [com.lod.art.ban.qua.gre.GreetingResource] (vert.x-worker-thread-0) Thread = vert.x-worker-thread-0

...
$ java -jar target/quarkus-app/quarkus-run.jar
...
2023-03-10 13:43:51,095 INFO  [com.lod.art.ban.qua.gre.GreetingResource] (executor-thread-0) Thread = executor-thread-0
2023-03-10 13:43:52,007 INFO  [com.lod.art.ban.qua.gre.GreetingResource] (executor-thread-0) Thread = executor-thread-0
```

disturbing.

**Comment by geoand** [comment]
@vsevel don't worry about that, it's expected (although unfortunate and unavoidable for dev mode)

**Comment by mkouba** [comment]
> > In any case, e.g. quarkus.vertx.max-worker-execute-time=2m would solve the problem in this particular example ;-)
> 
> ok thanks @mkouba I was looking for it ;)
> 
> another strange behavior, for the same code, I have:
> 
> ```
> $ mvn compile quarkus:dev
> ...
> 2023-03-10 13:49:44,001 INFO  [com.lod.art.ban.qua.gre.GreetingResource] (vert.x-worker-thread-0) Thread = vert.x-worker-thread-0
> 2023-03-10 13:49:45,001 INFO  [com.lod.art.ban.qua.gre.GreetingResource] (vert.x-worker-thread-0) Thread = vert.x-worker-thread-0
> 
> ...
> $ java -jar target/quarkus-app/quarkus-run.jar
> ...
> 2023-03-10 13:43:51,095 INFO  [com.lod.art.ban.qua.gre.GreetingResource] (executor-thread-0) Thread = executor-thread-0
> 2023-03-10 13:43:52,007 INFO  [com.lod.art.ban.qua.gre.GreetingResource] (executor-thread-0) Thread = executor-thread-0
> ```
> 
> disturbing.

Could you also post the `Installed features:` line? It looks like in the prod mode the Vert.x extension is not present?

**Comment by vsevel** [comment]
```

$ mvn compile quarkus:dev

Installed features: [agroal, artemis-jms, cache, cdi, config-yaml, confluent-registry-avro, hibernate-orm, hibernate-validator, kafka-client, logserver, messaginghub-pooled-jms, micrometer, narayana-jta, opentelemetry, opentelemetry-otlp-exporter, rest-client-reactive, rest-client-reactive-jackson, resteasy-reactive, resteasy-reactive-jackson, scheduler, security, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-openapi, smallrye-reactive-messaging, smallrye-reactive-messaging-kafka, stdlib, swagger-ui, vault, vertx]

$ java -jar target/quarkus-app/quarkus-run.jar

Installed features: [agroal, artemis-jms, cache, cdi, config-yaml, confluent-registry-avro, hibernate-orm, hibernate-validator, kafka-client, logserver, messaginghub-pooled-jms, micrometer, narayana-jta, opentelemetry, opentelemetry-otlp-exporter, rest-client-reactive, rest-client-reactive-jackson, resteasy-reactive, resteasy-reactive-jackson, scheduler, security, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-openapi, smallrye-reactive-messaging, smallrye-reactive-messaging-kafka, stdlib, vault, vertx]
```

`swagger-ui` in `quarkus:dev`  is the only difference.

**Comment by mkouba** [comment]
> `swagger-ui` in `quarkus:dev`  is the only difference.

An impressive list ;-). 

In any case, it seems that the thread factory used in the dev mode is different compared to the one used in the production mode. @cescoffier and @geoand probably know more :shrug:

**Comment by geoand** [comment]
It's expected, [this](https://github.com/quarkusio/quarkus/pull/17241#issuecomment-846248592) gives some explanation

**Comment by mkouba** [comment]
> It's expected, [this](https://github.com/quarkusio/quarkus/pull/17241#issuecomment-846248592) gives some explanation

Ok, so it seems that in the dev mode there are two separate thread pools: core blocking pool (represented by `ExecutorBuildItem` and potentially backed by `ThreadFactoryBuildItem`) and the worker pool used for `Vertx.executeBlocking()`. However, in the test and production mode there is a single thread pool used for both the core pool and worker pool.
