### ISSUE TITLE
RequestScoped context not active when using a ReaderInterceptor with large HTTP requests

### ISSUE THREAD

**Issue by jdussouillez** [quarkusio/quarkus#31692]
### Describe the bug

I have a [`ReaderInterceptor`](https://quarkus.io/guides/resteasy-reactive#reader-and-writer-interceptors) to intercept my RestEasy reactive API. This interceptor calls a `@RequestScoped` service to do some actions.

With small HTTP requests, it works fine. But if my request is bigger than 10KB then it fails. The source is that the request scoped context is not active, so the request scoped service can't be injected. Which is quite weird because it works with requests lighter than 10KB.

Stacktrace :

```
2023-03-08 14:40:30,265 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: javax.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=org.acme.service.LogService, id=922c737080882371f004038baf0a71f17589d79d]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:55)
	at org.acme.service.LogService_ClientProxy.arc$delegate(Unknown Source)
	at org.acme.service.LogService_ClientProxy.log(Unknown Source)
	at org.acme.interceptor.LogInterceptor.aroundReadFrom(LogInterceptor.java:23)
	at org.jboss.resteasy.reactive.server.jaxrs.ReaderInterceptorContextImpl.proceed(ReaderInterceptorContextImpl.java:54)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:88)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Repo to reproduce**: https://github.com/jdussouillez/quarkus-reader-interceptor-req-size

---

The important code :

```java
@RequestScoped // To make it work for requests bigger than 10KB, use "@ApplicationScoped" here
public class LogService {

    public void log(final String entity) {
        System.out.println("Entity size: " + entity.length());
    }
}
```

```java
@Provider
@ConstrainedTo(RuntimeType.SERVER)
public class LogInterceptor implements ReaderInterceptor {

    @Inject
    protected LogService logService;

    @Override
    public Object aroundReadFrom(final ReaderInterceptorContext context) throws IOException, WebApplicationException {
        var entity = context.proceed();
        logService.log((String) entity);
        return entity;
    }
}
```

```java
@Path("/test")
public class TestResource {

    @POST
    @Path("")
    @Consumes(MediaType.TEXT_PLAIN)
    @Produces(MediaType.APPLICATION_JSON)
    public Uni<Boolean> test(final String body) {
        return Uni.createFrom().item(true);
    }
}
```

### Expected behavior

The request scoped context is active, no matter the request size.

### Actual behavior

The request scoped context is not active for requests bigger than 10KB.

### How to Reproduce?

Repo to reproduce: https://github.com/jdussouillez/quarkus-reader-interceptor-req-size

Follow the steps in the readme.

### Output of `uname -a` or `ver`

Linux frpo245 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)

### Quarkus version or git rev

2.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /home/junior/.m2/wrapper/dists/apache-maven-3.8.6-bin/1ks0nkde5v1pk9vtc31i9d0lcd/apache-maven-3.8.6
Java version: 17.0.6, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-144-generic", arch: "amd64", family: "unix"

**Comment by jdussouillez** [comment]
May be related to https://github.com/quarkusio/quarkus/issues/28446

**Comment by geoand** [comment]
I'll have a look soon

**Comment by jdussouillez** [comment]
When using a multipart body there is no error. But it's because the `ReaderInterceptor` is not called. I don't know if this is expected or not.

To test it, use the branch [`multipart-body`](https://github.com/jdussouillez/quarkus-reader-interceptor-req-size/tree/multipart-body)

**Comment by geoand** [comment]
This is similar but not exactly the same as #31606
