### ISSUE TITLE
DevUI: Not reachable in 3.0.0.Alpha5

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#31738]
### Describe the bug

Trying to hit the new Dev UI at  `q/dev-ui` in 3.0.0.Alpha5 and the browser just spins and spins and says "not found"

### Expected behavior

New DEV UI appears.

### Actual behavior

Browser just spins

### How to Reproduce?

1. git clone https://github.com/melloware/quarkus-faces
2. run `mvn quarkus:dev`
3. hit http://localhost:8081/q/dev-ui 

See nothing happens

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.1265]

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### GraalVM version (if different from Java)

Mandrel 22.3

### Quarkus version or git rev

3.0.0.Alpha5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: C:\Tools\apache-maven-3.8.6 Java version: 17.0.5, vendor: Eclipse Adoptium, runtime: C:\Tools\jdk-17 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

**Comment by melloware** [comment]
cc @phillip-kruger

**Comment by maxandersen** [comment]
Alpha5 does not have the polyfill PR that fixes this for "older" browsers https://github.com/quarkusio/quarkus/pull/31672

in short - this is broken in alpha5 but work on main.

@melloware you can either:

1) in firefox goto about:config and set `dom.importMaps.enabled` to true
2) use a browser that has importmap support (Chrome and Edge had for a while, Firefox is recent)
3) build quarkus locally from main and should just work no matter browser age/setting.

**Comment by melloware** [comment]
Cool i will close this for now if its going to be fixed in Alpha6!

**Comment by gsmet** [comment]
@melloware for our information, which browser are you using and which version it is? I would like to make sure we don't have a problem we haven't caught.

**Comment by melloware** [comment]
I was definitely using latest Firefox and I am pretty sure I tried latest Chrome too.  Same behavior on both.

**Comment by melloware** [comment]
Confirmed I cannot reach it in Chrome 111, Firefox 110.0.1 (64-bit) the browser just sits there on the Network tab saying "in Progress".

**Comment by melloware** [comment]
OK when trying it with the Quarkus POI extension which has a bare bones integration test when I hit the site in Chrome 111 it starts infinitely stack tracing.

```java
 at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder$3.handle(ResteasyStandaloneRecorder.java:187)
        at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder$3.handle(ResteasyStandaloneRecorder.java:157)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup.handleHotReplacementRequest(VertxHttpHotReplacementSetup.java:135)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$11.handle(VertxHttpRecorder.java:517)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$11.handle(VertxHttpRecorder.java:513)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.vertx.ext.web.impl.RoutingContextImplBase.restart(RoutingContextImplBase.java:130)
        at io.vertx.ext.web.impl.RoutingContextImpl.reroute(RoutingContextImpl.java:430)
        at io.vertx.ext.web.impl.RoutingContextWrapper.reroute(RoutingContextWrapper.java:303)
        at io.vertx.ext.web.RoutingContext.reroute(RoutingContext.java:571)
        at io.quarkus.devui.runtime.VaadinRouterHandler.handle(VaadinRouterHandler.java:31)
        at io.quarkus.devui.runtime.VaadinRouterHandler.handle(VaadinRouterHandler.java:9)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:68)
        at io.quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:15)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:68)
      .quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:15)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.vertx.http.runtime.devmode.FileSystemStaticHandler.sendStatic(FileSystemStaticHandler.java:140)
        at io.quarkus.vertx.http.runtime.devmode.FileSystemStaticHandler.handle(FileSystemStaticHandler.java:86)
        at io.quarkus.vertx.http.runtime.devmode.FileSystemStaticHandler.handle(FileSystemStaticHandler.java:32)
        at io.quarkus.vertx.http.runtime.webjar.WebJarStaticHandler.handle(WebJarStaticHandler.java:94)
        at io.quarkus.vertx.http.runtime.webjar.WebJarStaticHandler.handle(WebJarStaticHandler.java:18)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:250)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:437)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:415)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder$3.handle(ResteasyStandaloneRecorder.java:187)
        at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder$3.handle(ResteasyStandaloneRecorder.java:157)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup.handleHotReplacementRequest(VertxHttpHotReplacementSetup.java:135)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$11.handle(VertxHttpRecorder.java:517)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$11.handle(VertxHttpRecorder.java:513)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.vertx.ext.web.impl.RoutingContextImplBase.restart(RoutingContextImplBase.java:130)
        at io.vertx.ext.web.impl.RoutingContextImpl.reroute(RoutingContextImpl.java:430)
        at io.vertx.ext.web.impl.RoutingContextWrapper.reroute(RoutingContextWrapper.java:303)
        at io.vertx.ext.web.RoutingContext.reroute(RoutingContext.java:571)
        at io.quarkus.devui.runtime.VaadinRouterHandler.handle(VaadinRouterHandler.java:31)
        at io.quarkus.devui.runtime.VaadinRouterHandler.handle(VaadinRouterHandler.java:9)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:68)
        at io.quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:15)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:68)
        at io.quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:15)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.vertx.http.runtime.devmode.FileSystemStaticHandler.sendStatic(FileSystemStaticHandler.java:140)
        at io.quarkus.vertx.http.runtime.devmode.FileSystemStaticHandler.handle(FileSystemStaticHandler.java:86)
        at io.quarkus.vertx.http.runtime.devmode.FileSystemStaticHandler.handle(FileSystemStaticHandler.java:32)
        at io.quarkus.vertx.http.runtime.webjar.WebJarStaticHandler.handle(WebJarStaticHandler.java:94)
        at io.quarkus.vertx.http.runtime.webjar.WebJarStaticHandler.handle(WebJarStaticHandler.java:18)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:250)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
```

**Comment by phillip-kruger** [comment]
@melloware do you have a reproducer of the above stacktrace ?

**Comment by phillip-kruger** [comment]
For reference, the issue with browsers (that we have the polyfill for) is because of importmaps: https://caniuse.com/import-maps , but your browser version is definitely fine, so it's something else. I have not managed to recreate the issue on my firefox / chrome, and I do not get the above stacktrace. Any more info would help :) Thanks
 
![working_firefox](https://user-images.githubusercontent.com/6836179/224175645-380743d6-f968-4a01-bef9-598051b2fce4.gif)

**Comment by melloware** [comment]
Yep just Git clone Quarkiverse POI which is a simple wrapper library by @gastaldi    Run Quarkus dev in the integration tests folder. It happens every time for me.

**Comment by phillip-kruger** [comment]
Ok, trying now. Is there anything in your browser developer console ?

**Comment by phillip-kruger** [comment]
@melloware Locally Poi extension works for me: 
![working_poi](https://user-images.githubusercontent.com/6836179/224182363-66f5db5e-fbe3-4ff3-a7cf-a7a3e3c8c588.gif)

Let me know if there is anything in your browser log

**Comment by melloware** [comment]
So could the difference be I am running on Windows?   I can't see how that example works for you and not for me if both are identical other than OS difference?

**Comment by phillip-kruger** [comment]
I actually have a Windows VM. Let me confirm. Hold on

**Comment by phillip-kruger** [comment]
@melloware - Got it ! Managed to recreate on Windows. Looking...

**Comment by melloware** [comment]
Ok I feel better that I am not going crazy 😃

**Comment by melloware** [comment]
You guys rock.  I want to build new Dev UIs for OmniFaces, PrimeFaces, MyFaces extensions.  Not sure what I will put in there but excited for the new UI.

**Comment by phillip-kruger** [comment]
Please reach out on zulip if you have questions w.r.r Dev UI
