### ISSUE TITLE
3.0.0.Alpha5: Simple Hibernate Application does not start because import.sql

### ISSUE THREAD

**Issue by andvasp** [quarkusio/quarkus#31749]
### Describe the bug

A simple application using the extensios RESTEasy Reactive, Hibernate ORM, JDBC Driver - H2 does not start.
The application in Alpha4 is ok. I did not have problem.
When I remove the import.sql the application just run properly.

### Expected behavior

The application is launched without errors.

### Actual behavior

__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-03-09 23:10:23,298 INFO  [org.hib.too.sch.int.SchemaCreatorImpl] (JPA Startup Thread) HHH000476: Executing import script 'file:/C:/_Temp/code-with-quarkus-simple-alpha5/target/classes/import.sql'

line 5:85 extraneous input '<EOF>' expecting {CHAR, ' ', '\t', NEWLINE, QUOTED_TEXT}
2023-03-09 23:10:24,590 INFO  [org.hib.too.sch.int.SchemaCreatorImpl] (JPA Startup Thread) HHH000476: Executing import script 'file:/C:/_Temp/code-with-quarkus-simple-alpha5/target/classes/import.sql'
line 5:85 extraneous input '<EOF>' expecting {CHAR, ' ', '\t', NEWLINE, QUOTED_TEXT}
2023-03-09 23:10:24,662 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-03-09 23:10:24,659 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "terminalNodes" is null
        at org.hibernate.tool.schema.internal.script.SqlScriptVisitor.visitScript(SqlScriptVisitor.java:46)
        at org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor.extractCommands(MultiLineSqlScriptExtractor.java:47)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.lambda$applyImportScript$2(SchemaCreatorImpl.java:715)
        at org.hibernate.tool.schema.internal.exec.AbstractScriptSourceInput.extract(AbstractScriptSourceInput.java:40)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applyImportScript(SchemaCreatorImpl.java:714)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applyImportFiles(SchemaCreatorImpl.java:695)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applyImportSources(SchemaCreatorImpl.java:614)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:185)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:143)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:119)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:254)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:143)
        at java.base/java.util.HashMap.forEach(HashMap.java:1420)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:140)
        at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
        at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:366)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:200)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:78)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)        
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)        
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:167) 
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:68)
        at java.base/java.lang.Thread.run(Thread.java:833)

### How to Reproduce?

1. Create one application using the version 3.0.0.Alpha5 with the extensios: RESTEasy Reactive, Hibernate ORM, JDBC Driver - H2 

https://code.quarkus.io/?e=resteasy-reactive&e=hibernate-orm&e=jdbc-h2&S=io.quarkus.platform%3A3.0

2. Launch the application using mvn quarkus:dev
3. Check the console to show errors.

### Output of `uname -a` or `ver`

Microsoft Windows [versão 10.0.19043.2364]

### Output of `java -version`

openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### Quarkus version or git rev

3.0.0.Alpha5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\Users\andvasp\.m2\wrapper\dists\apache-maven-3.8.6-bin\67568434\apache-maven-3.8.6
Java version: 17, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17
Default locale: pt_BR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by yrodiere** [comment]
Thanks for the report. I can reproduce this locally and am having a look.

**Comment by yrodiere** [comment]
Confirmed as a bug upstream: https://hibernate.atlassian.net/browse/HHH-16279
Will work to get that fixed.

**Comment by Sanne** [comment]
awesome, thanks!

**Comment by andvasp** [comment]
Pretty good. Thanks!

**Comment by yrodiere** [comment]
We upgraded to ORM 6.0.0.CR4 in #31953 , so this was fixed.
