### ISSUE TITLE
java.lang.ClassNotFoundException: boolean,short

### ISSUE THREAD

**Issue by punkratz312** [quarkusio/quarkus#31776]
### Describe the bug

```
Error restarting Quarkus
io.quarkus.dev.appstate.ApplicationStartException: java.lang.TypeNotPresentException: Type boolean not present
The stacktrace below has been reversed to show the root cause first. Click Here to see the original stacktrace

java.lang.ClassNotFoundException: boolean
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.repository.ConstructorRepository.computeParameterTypes(ConstructorRepository.java:111)
	at java.base/sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(ConstructorRepository.java:87)
	at java.base/java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:298)
	at java.base/java.lang.reflect.Method.getGenericParameterTypes(Method.java:333)
	at java.base/java.lang.reflect.Executable.getAllGenericParameterTypes(Executable.java:317)
	at java.base/java.lang.reflect.Executable.getAnnotatedParameterTypes(Executable.java:754)
	at org.hibernate.validator.internal.properties.javabean.JavaBeanExecutable.getParameters(JavaBeanExecutable.java:190)
	at org.hibernate.validator.internal.properties.javabean.JavaBeanExecutable.<init>(JavaBeanExecutable.java:44)
	at org.hibernate.validator.internal.properties.javabean.JavaBeanMethod.<init>(JavaBeanMethod.java:20)
	at org.hibernate.validator.internal.properties.javabean.JavaBeanHelper.executable(JavaBeanHelper.java:132)
	at org.hibernate.validator.internal.properties.javabean.JavaBeanHelper.executable(JavaBeanHelper.java:120)
	at org.hibernate.validator.internal.properties.javabean.JavaBeanHelper.executable(JavaBeanHelper.java:112)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findExecutableMetaData(AnnotationMetaDataProvider.java:307)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getMetaData(AnnotationMetaDataProvider.java:292)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getMethodMetaData(AnnotationMetaDataProvider.java:279)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.retrieveBeanConfiguration(AnnotationMetaDataProvider.java:130)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfiguration(AnnotationMetaDataProvider.java:120)
	at org.hibernate.validator.internal.metadata.PredefinedScopeBeanMetaDataManager.getBeanConfigurationForHierarchy(PredefinedScopeBeanMetaDataManager.java:183)
	at org.hibernate.validator.internal.metadata.PredefinedScopeBeanMetaDataManager.createBeanMetaData(PredefinedScopeBeanMetaDataManager.java:150)
	at org.hibernate.validator.internal.metadata.PredefinedScopeBeanMetaDataManager.<init>(PredefinedScopeBeanMetaDataManager.java:100)
	at org.hibernate.validator.internal.engine.PredefinedScopeValidatorFactoryImpl.<init>(PredefinedScopeValidatorFactoryImpl.java:183)
	at org.hibernate.validator.PredefinedScopeHibernateValidator.buildValidatorFactory(PredefinedScopeHibernateValidator.java:42)
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:433)
	at io.quarkus.hibernate.validator.runtime.HibernateValidatorRecorder$2.created(HibernateValidatorRecorder.java:163)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:73)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:833)
Resulted in: java.lang.TypeNotPresentException: Type boolean not present
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	... 45 more
Resulted in: io.quarkus.dev.appstate.ApplicationStartException: java.lang.TypeNotPresentException: Type boolean not present
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:58)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:123)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:222)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:203)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:537)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:437)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:152)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:139)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/8830888/224441165-9a65fb88-3599-465b-a7aa-88d11a8b23ef.png">

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/8830888/224441208-a5252c6c-9b24-4fb3-9c6d-659ba5fe5a04.png">

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/8830888/224441237-b8fec318-9fb1-48b5-a58a-5843a9c4b45f.png">
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/8830888/224441261-bf48b245-9efd-418e-8322-0986c35caf93.png">

**Comment by punkratz312** [comment]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/8830888/224443933-571cd721-a9d9-4d87-b453-eae623085493.png">


<img width="959" alt="image" src="https://user-images.githubusercontent.com/8830888/224443951-b7083d12-199a-4fbb-ac35-fe5f537022ba.png">


it works when we using the fix resources that mock the PanacheEntityResource with manual resource endpoints, so i dont think the class issue is the real indicator, as it works without panache.

**Comment by punkratz312** [comment]
<img width="972" alt="image" src="https://user-images.githubusercontent.com/8830888/224474221-0f3f7096-b6ec-4b7e-98fc-a482b3f83325.png">

this might be the issue...

**Comment by maxandersen** [comment]
@punkratz312 can you attach a project that lets us reproduce the issue?

your last screenshot indicates you are trying to use Java 19 with version of kotlin that does not support java 19...

**Comment by punkratz312** [comment]
@maxandersen thanks for your hint
running under 19 compiled to 17 should do be possible?
the other java versions can run with higher jdk versions to some point, if their compile lvl is set correctly to the demanding version. the gap here is only 2 major version so it can be compatible.

i will check on colleagues windows pc with java 17 if the issue is reliable.

if fundamental classes are not found its usually an java incompatibility issue yes indeed.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/8830888/224548086-5640e289-976f-4b33-ac52-7a7a1723c486.png">
we have bumped everything to 17 now.
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/8830888/224548145-1b712206-e109-46d6-898b-729a6e8de96e.png">

**Comment by punkratz312** [comment]
same with java 17 as runtime:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/8830888/224549530-2c3962a0-a8ec-40fc-8223-923fc8bf29b3.png">
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/8830888/224549537-a0cd18ad-a30c-411d-b9e9-7bd1330b693b.png">
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/8830888/224549544-6517f94e-34cd-4cbd-b1b1-c31143f8d417.png">
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/8830888/224549566-2fb24431-1304-4922-ab0b-514e523efe33.png">

**Comment by maxandersen** [comment]
Can you please make a reproducer ? The screenshots are not helping us figuring out how to reproduce your issue.

**Comment by punkratz312** [comment]
yes i will try to. for now this is all i can provide

**Comment by geoand** [comment]
Please attach a reproducer, not screenshots.

**Comment by punkratz312** [comment]
@geoand yes im working on it 🫡

**Comment by geoand** [comment]
Closing as we did not get a reproducer
