### ISSUE TITLE
Unable to create RESTEasy Reactive application with 10k endpoints

### ISSUE THREAD

**Issue by ruannawe** [quarkusio/quarkus#31914]
### Describe the bug

after creating multiple controllers to test the compilation time using the following script

```ruby
#!/usr/bin/ruby

i = 1
10000.times do |val|
  puts i

  File.open("./GreetingResource#{i}.java", 'w+') do |f|
    f.write(
      <<~HEREDOC
        package org.acme;

        import javax.ws.rs.GET;
        import javax.ws.rs.Path;
        import javax.ws.rs.Produces;
        import javax.ws.rs.core.MediaType;

        @Path("/hello#{i}")
        public class GreetingResource#{i} {

            @GET
            @Produces(MediaType.TEXT_PLAIN)
            public String hello() {
                return "Hello from RESTEasy Reactive #{i}";
            }
        }
      HEREDOC
    )
  end

  i+=1
end
```

when I tried to up the application I received the following error:
```java
Listening for transport dt_socket at address: 5005
2023-03-16 16:35:07,036 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-03-16 16:35:07,212 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#build threw an exception: org.objectweb.asm.ClassTooLargeException: Class too large: io/quarkus/deployment/steps/ResteasyReactiveProcessor$setupEndpoints1082683577
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:621)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:238)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:249)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:609)
	at io.quarkus.deployment.steps.MainClassBuildStep.writeRecordedBytecode(MainClassBuildStep.java:479)
	at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:186)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#build threw an exception: org.objectweb.asm.ClassTooLargeException: Class too large: io/quarkus/deployment/steps/ResteasyReactiveProcessor$setupEndpoints1082683577
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:621)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:238)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:249)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:609)
	at io.quarkus.deployment.steps.MainClassBuildStep.writeRecordedBytecode(MainClassBuildStep.java:479)
	at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:186)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	... 9 more
Caused by: org.objectweb.asm.ClassTooLargeException: Class too large: io/quarkus/deployment/steps/ResteasyReactiveProcessor$setupEndpoints1082683577
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:621)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:238)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:249)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:609)
	at io.quarkus.deployment.steps.MainClassBuildStep.writeRecordedBytecode(MainClassBuildStep.java:479)
	at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:186)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

Up the server without errors

### Actual behavior

Appears the following error:
```
Listening for transport dt_socket at address: 5005
2023-03-16 16:35:07,036 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-03-16 16:35:07,212 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#build threw an exception: org.objectweb.asm.ClassTooLargeException: Class too large: io/quarkus/deployment/steps/ResteasyReactiveProcessor$setupEndpoints1082683577
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:621)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:238)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:249)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:609)
	at io.quarkus.deployment.steps.MainClassBuildStep.writeRecordedBytecode(MainClassBuildStep.java:479)
	at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:186)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#build threw an exception: org.objectweb.asm.ClassTooLargeException: Class too large: io/quarkus/deployment/steps/ResteasyReactiveProcessor$setupEndpoints1082683577
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:621)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:238)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:249)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:609)
	at io.quarkus.deployment.steps.MainClassBuildStep.writeRecordedBytecode(MainClassBuildStep.java:479)
	at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:186)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	... 9 more
Caused by: org.objectweb.asm.ClassTooLargeException: Class too large: io/quarkus/deployment/steps/ResteasyReactiveProcessor$setupEndpoints1082683577
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:621)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:238)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:249)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:609)
	at io.quarkus.deployment.steps.MainClassBuildStep.writeRecordedBytecode(MainClassBuildStep.java:479)
	at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:186)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### How to Reproduce?

1. Create a new Quarkus project
2. Go to the path `/src/main/java/org/acme`
3. run the following script

```ruby
#!/usr/bin/ruby

i = 1
10000.times do |val|
  puts i

  File.open("./GreetingResource#{i}.java", 'w+') do |f|
    f.write(
      <<~HEREDOC
        package org.acme;

        import javax.ws.rs.GET;
        import javax.ws.rs.Path;
        import javax.ws.rs.Produces;
        import javax.ws.rs.core.MediaType;

        @Path("/hello#{i}")
        public class GreetingResource#{i} {

            @GET
            @Produces(MediaType.TEXT_PLAIN)
            public String hello() {
                return "Hello from RESTEasy Reactive #{i}";
            }
        }
      HEREDOC
    )
  end

  i+=1
end
```

4. run the command `quarkus dev` 

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10)
OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)

### Quarkus version or git rev

2.16.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: /usr/local/Cellar/maven/3.9.0/libexec
Java version: 11.0.18, vendor: Eclipse Adoptium, runtime: /Users/ruannawe/.sdkman/candidates/java/11.0.18-tem
Default locale: en_BR, platform encoding: UTF-8
OS name: "mac os x", version: "13.2.1", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
Do you actually run into this problem with a real world application on only when generating the resources with the script?

**Comment by geoand** [comment]
Sure, but as everything is a matter of priorities, there is no reason to put effort into fixing something if it does not actually show up in practice.

**Comment by mkouba** [comment]
> Sure, but as everything is a matter of priorities, there is no reason to put effort into fixing something if it does not actually show up in practice.

:+1: For sure, then documenting the known limits would be a reasonable choice.

**Comment by geoand** [comment]
Sure, but there is no hard limit. It really depends on the type of resource - for example how many methods it has. 
I assume that saying 1000k is known to be supported is fine.

**Comment by mkouba** [comment]
> I assume that saying 1000k is known to be supported is fine.

1000k or 1k? :wink: 

Yes, we don't need to give exact numbers but some "estimated guarantees".

**Comment by ruannawe** [comment]
> Do you actually run into this problem with a real world application on only when generating the resources with the script?

I was trying to simulate huge applications from the real world with my script, not a vast majority of applications arrive at this size point, but in big companies, is not hard for a monolithic service to arrive at this size.

**Comment by ruannawe** [comment]
> Have you actually seen such an application with 10k resources?
> 
> Because I have not

It is common on the GitHub repo to get more than 10000 files.
```
git@github.com:mysql/mysql-server.git => 35628 files
git@github.com:erlang/otp.git => 11862 files
git@github.com:apache/openoffice.git => 62627 files
```

**Comment by geoand** [comment]
That is a totally different thing.

**Comment by geoand** [comment]
I am going to close this for now.

If someone has ever righted a real application with 10k endpoints, then I'll be happy to reopen and look into how we can fix this.
