### ISSUE TITLE
Hibernate-Reactive-Panache issue

### ISSUE THREAD

**Issue by petrroda** [quarkusio/quarkus#31955]
When running 

Theme.list( "FROM Theme WHERE id = :id", Parameters.with("id", 1)).await().indefinitely();

 I get the following error

io.vertx.pgclient.PgException: ERROR: syntax error at end of input (42601)

When running

Theme.list( "FROM Theme WHERE id = 1").await().indefinitely();

all works fine.

????

**Comment by raycon300** [comment]
@petrroda  try to replace:
`Theme.list( "FROM Theme WHERE id = :id", Parameters.with("id", 1)).await().indefinitely();`
by
`Theme.list( "FROM Theme WHERE id = :id", Parameters.with("id", 1L)).await().indefinitely();`

**Comment by petrroda** [comment]
@raycon300 

Then I get an error as well, because the column is an integer

java.lang.IllegalArgumentException: Parameter value [1] did not match expected type [java.lang.Integer (n/a)]

Somehow it seems like these parameters are not passed to the queries when executed by the driver

**Comment by petrroda** [comment]
Within io.vefrtx.sqlclient.impl.SocketConnectionBase I can see
that the parameters are passed within the tuple. But these are never used.

![image](https://user-images.githubusercontent.com/12616511/226089340-e81f92a6-4b9e-45f7-a28f-3820cc0d6305.png)

**Comment by raycon300** [comment]
I can't reproduce the issue from my side. I tried to reproduce this using the following:
**Quarkus platform BOMs:**
- [x] io.quarkus.platform:quarkus-bom:pom:2.16.4.Final

**Extensions from io.quarkus.platform:quarkus-bom:**
- [x] io.quarkus:quarkus-hibernate-reactive-panache
- [x] io.quarkus:quarkus-arc
- [x] io.quarkus:quarkus-reactive-pg-client

By the way, the tuple value should be used when `prepareCmd.handler` calls the `queryCmd.prepare()`, then It will be passed to `PgPreparedStatement.prepare()` that by its time will pass the value to be extracted by `PgParamDesc.prepare()`.

**Comment by petrroda** [comment]
This is a stack trace I get:

2023-03-19 11:31:41,393 TRACE [org.hib.typ.des.sql.BasicBinder] (vert.x-eventloop-thread-3) binding parameter [1] as [OTHER] - [4395b642-9bab-4360-a687-21f0d80b68df]
Hibernate: 
    select
        companypro0_."id" as id1_0_0_,
        companypro0_."activated" as activate2_0_0_,
        companypro0_."agile" as agile3_0_0_,
        companypro0_."benefits" as benefits4_0_0_,
        companypro0_."branches" as branches5_0_0_,
        companypro0_."createdAt" as createda6_0_0_,
        companypro0_."duCulture" as ducultur7_0_0_,
        companypro0_."euCitizen" as eucitize8_0_0_,
        companypro0_."hierarchie" as hierarch9_0_0_,
        companypro0_."homeOffice" as homeoff10_0_0_,
        companypro0_."interNational" as interna11_0_0_,
        companypro0_."lastUpdatedBy" as lastupd12_0_0_,
        companypro0_."location" as locatio13_0_0_,
        companypro0_."logo" as logo14_0_0_,
        companypro0_."name" as name15_0_0_,
        companypro0_."profileType" as profile16_0_0_,
        companypro0_."size" as size17_0_0_,
        companypro0_."updatedAt" as updated18_0_0_,
        companypro0_."userId" as userid20_0_0_,
        companypro0_."workTime" as worktim19_0_0_ 
    from
        "company_profile" companypro0_ 
    where
        companypro0_."id"=?
2023-03-19 11:31:41,461 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-3) HR000057: Failed to execute statement [select companypro0_."id" as id1_0_0_, companypro0_."activated" as activate2_0_0_, companypro0_."agile" as agile3_0_0_, companypro0_."benefits" as benefits4_0_0_, companypro0_."branches" as branches5_0_0_, companypro0_."createdAt" as createda6_0_0_, companypro0_."duCulture" as ducultur7_0_0_, companypro0_."euCitizen" as eucitize8_0_0_, companypro0_."hierarchie" as hierarch9_0_0_, companypro0_."homeOffice" as homeoff10_0_0_, companypro0_."interNational" as interna11_0_0_, companypro0_."lastUpdatedBy" as lastupd12_0_0_, companypro0_."location" as locatio13_0_0_, companypro0_."logo" as logo14_0_0_, companypro0_."name" as name15_0_0_, companypro0_."profileType" as profile16_0_0_, companypro0_."size" as size17_0_0_, companypro0_."updatedAt" as updated18_0_0_, companypro0_."userId" as userid20_0_0_, companypro0_."workTime" as worktim19_0_0_ from "company_profile" companypro0_ where companypro0_."id"=?]: could not load an entity: [com.newhr.persistence.entity.CompanyProfile#4395b642-9bab-4360-a687-21f0d80b68df]: java.util.concurrent.CompletionException: io.vertx.pgclient.PgException: ERROR: syntax error at end of input (42601)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:936)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:386)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.sqlclient.impl.QueryResultBuilder.tryFail(QueryResultBuilder.java:116)
	at io.vertx.core.Promise.fail(Promise.java:89)
	at io.vertx.core.Promise.handle(Promise.java:53)
	at io.vertx.core.Promise.handle(Promise.java:29)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:43)
	at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.vertx.pgclient.PgException: ERROR: syntax error at end of input (42601)
	at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:31)
	at io.vertx.pgclient.impl.codec.PrepareStatementCommandCodec.handleErrorResponse(PrepareStatementCommandCodec.java:90)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:246)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:132)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:112)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	... 4 more

**Comment by petrroda** [comment]
When executing the query with PgAdmin there is no issue. The parameter binding is not working in Hibernate/Reactive PG Client

**Comment by petrroda** [comment]
I don't know why I had problems. I just started from again and now it works: ;-)
