### ISSUE TITLE
Kafka Streams Extension can't find Serdes.StringSerde

### ISSUE THREAD

**Issue by muirandy** [quarkusio/quarkus#3202]
**Describe the bug**
Native image generated cannot find the StringSerde. This causes the app to fail on startup.

**Expected behavior**
The app should start up and run without issues.

**Actual behavior**
I have a Java Kafka Streams app. I configure the Serdes.StringSerde as the default Serdes in the Kafka properties.
I then build a native image (either on OSX or docker).
When I run the native image, it fails with:
```
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.serialization.Serdes$StringSerde for configuration default.key.serde: Class org.apache.kafka.common.serialization.Serdes$StringSerde could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:718)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:471)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:464)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.streams.StreamsConfig.<init>(StreamsConfig.java:849)
	at org.apache.kafka.streams.StreamsConfig.<init>(StreamsConfig.java:844)
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:544)
	at com.aimyourtechnology.quarkus.kafka.streams.ConverterStream.runTopology(ConverterStream.java:52)
	at com.aimyourtechnology.quarkus.kafka.streams.StreamingApp.onStart(StreamingApp.java:54)
	at com.aimyourtechnology.quarkus.kafka.streams.StreamingApp_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(StreamingApp_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:63)
	at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:228)
	at io.quarkus.arc.EventImpl.fire(EventImpl.java:69)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcDeploymentTemplate.handleLifecycleEvents(ArcDeploymentTemplate.java:99)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent17.deploy_0(LifecycleEventsBuildStep$startupEvent17.zig:58)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent17.deploy(LifecycleEventsBuildStep$startupEvent17.zig:77)
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:90)
	... 3 more
```

**To Reproduce**
You can show it through docker:
```
1. git clone https://github.com/muirandy/quarkus-kafka-streams-xml-json-converter.git
2. cd quarkus-kafka-streams-xml-json-converter
3. mvn package -Pnative -Dnative-image.docker-build=true
4. docker build -f src/main/docker/Dockerfile.native -t quarkus/quarkus-kafka-streams-xml-json-converter .
```
You can now run acceptance.converter.ConvertToJsonShould from an IDE. This will demonstrate the failure.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Darwin andymuir-3.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```
 - Output of `java -version`: 
```
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b31)
Java HotSpot(TM) 64-Bit GraalVM EE 19.1.0 (build 25.212-b31-jvmci-20-b04, mixed mode)
```
 - GraalVM version (if different from Java): 19.1.0
 - Quarkus version or git rev: 0.18.0

**Additional context**
The quickstart example uses a StringSerde defined for the Stream:
```
builder.stream(                                                       
                        TEMPERATURE_VALUES_TOPIC,
                        Consumed.with(Serdes.Integer(), Serdes.String())
                )
```

My code defines:
```
        streamingConfig.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName());
        streamingConfig.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName());
```
as part of the Kafka Properties used when creating the KafkaStreams within com.aimyourtechnology.quarkus.kafka.streams.ConverterStream:
```
streams = new KafkaStreams(topology, streamingConfig);
```

**Comment by gsmet** [comment]
I think it's related to the fact that, right now, the Serdes needs to be defined for reflection manually.

/cc @cescoffier

**Comment by gunnarmorling** [comment]
@muirandy, thanks for opening this, I think understand now what's happening.

When relying on the default key / value serde, they must indeed be registered for reflection manually atm. That's different from the programmatic use case in the quick start example, where there's an actual reference to their type and they are also not instantiated reflectively.

It's something the extension can take care of automatically going forward, but for now you'd have to manually register those SerDes or just use them programmatically when building the topology.

**Comment by gsmet** [comment]
@gunnarmorling maybe you could point @muirandy to where the magic is done? He might be interested in contributing :).

**Comment by gunnarmorling** [comment]
The problem is this should only be really done once my other basic work for #2863 is done. It's only then that the extension will have access to the configuration used for Kafka Streams (which it then will be able to read and obtain those default Serde classes from). Right now the properties are "un-managed" and just given in the actual application code, so we don't really have handle to it.

**Comment by gunnarmorling** [comment]
I'm right now working on rebasing my PR for #2863 to the current master and sort out one issue with Dev mode. Once it's in, features like the one here can be implemented. I've added it as one item to the list in #2863.

**Comment by muirandy** [comment]
I'd be delighted to have a bash at implementing it - lets see how things look once #2863 is pushed. 

I did try accessing the Serde in the code to see if it would help (it didn't):
```
        Serdes.StringSerde stringSerde = new Serdes.StringSerde();
        System.out.println(stringSerde);
```

**Comment by gunnarmorling** [comment]
@muirandy, it should work if you don't rely on the default key/value SerDe. If you e.g. remove those configuration values, Kafka Streams should tell you where they are missing. Most likely it's enough if you pass a `Produced` with the SerDe to that last `to()` call in your pipeline.

**Comment by gunnarmorling** [comment]
Hi @muirandy, so I've updated the PR for #2863 now: https://github.com/quarkusio/quarkus/pull/2953. It should be in a state now where you could add the functionality we discussed above on top of it.

To do so, take a look at `io.quarkus.kafka.streams.deployment.KafkaStreamsProcessor#build()`. It'll have to produce further ``ReflectiveClassBuildItem``s for the default SerDes. The config values can be acccessed as seen in `processBuildTimeConfig()`.

**Comment by muirandy** [comment]
@gunnarmorling How do I go about this? Do I fork your fork? First time doing this, apologies for nb question!

**Comment by gunnarmorling** [comment]
@muirandy, yes, you could fork my fork, and create a local branch based on my branch upon which this PR is based. If you then submit a pull request with your work against the upstream repo in the Quarkus organization, that'd either include my commits here or not, depending on whether my PR has been merged at this point yet or not. Hope this helps, if not let me know.

**Comment by muirandy** [comment]
@gunnarmorling @gsmet Is there somewhere I can read more about setting up quarkus in my IDE (IntelliJ)? I've followed the simple steps in the README, but it seems I need to set all my source directories manually, and some poms aren't happy (jacoco dependency not found, ). When I open the code (`KafkaStreamsProcessor`) then I have loads of errors about not finding libraries (`org.apache.kafka.stream`, `org.rocksdb` for instance). 

Am I missing something or having a bad day?!

**Comment by muirandy** [comment]
Small update: Its taken a while to get the project open and compiled. I'll consider updating the `CONTRIBUTING.md` seperately.

**Comment by gsmet** [comment]
It's weird because I always had good reports about using Intellij to work on the Quarkus tree.

Eclipse (which I use) is a bit more challenging.

Curious to see the problems you had.

**Comment by muirandy** [comment]
@gunnarmorling I've made a small change to `io.quarkus.kafka.streams.deployment.KafkaStreamsProcessor#build()` as you suggested. It appears to have resolved the issue I was having, however, I have a new problem in its place:
```
Exception in thread "acceptance.converter.ConvertToJsonShould-368fa7ee-6eeb-4129-9b8d-1989f31fc453-StreamThread-1" org.apache.kafka.streams.errors.StreamsException: stream-thread [acceptance.converter.ConvertToJsonShould-368fa7ee-6eeb-4129-9b8d-1989f31fc453-StreamThread-1] Failed to rebalance.
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:949)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:845)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:804)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:773)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:314)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:302)
	at org.apache.kafka.streams.StreamsConfig.defaultDeserializationExceptionHandler(StreamsConfig.java:1207)
	at org.apache.kafka.streams.processor.internals.StreamTask.<init>(StreamTask.java:227)
	at org.apache.kafka.streams.processor.internals.StreamTask.<init>(StreamTask.java:172)
	at org.apache.kafka.streams.processor.internals.StreamThread$TaskCreator.createTask(StreamThread.java:447)
	at org.apache.kafka.streams.processor.internals.StreamThread$TaskCreator.createTask(StreamThread.java:398)
	at org.apache.kafka.streams.processor.internals.StreamThread$AbstractTaskCreator.createTasks(StreamThread.java:383)
	at org.apache.kafka.streams.processor.internals.TaskManager.addStreamTasks(TaskManager.java:148)
	at org.apache.kafka.streams.processor.internals.TaskManager.createTasks(TaskManager.java:107)
	at org.apache.kafka.streams.processor.internals.StreamThread$RebalanceListener.onPartitionsAssigned(StreamThread.java:280)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:292)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:410)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:344)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:342)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1226)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1191)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1176)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:940)
	... 5 more
Caused by: java.lang.NoSuchMethodException: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler.<init>
	at java.lang.Class.getConstructor0(DynamicHub.java:3082)
	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:312)
	... 23 more
```
I'm not using `LogAndContinueExceptionHandler` directly in my code, but I did notice it was one of the `ReflectiveClassBuildItems` that you have already included. Its a bit puzzling as there is a no-arg constructor. Any ideas?

To try this out, I had to build the quarkus project and then include it into my own project and run my tests. Are there any tests in quarkus that I could use to test if its working? It would certainly be quicker.

**Comment by muirandy** [comment]
@gunnarmorling Perhaps there is a change to the way I need to configure my app? Have the properties changed their keys?

**Comment by gunnarmorling** [comment]
Hey @muirandy, sorry for the long delay -- holidays and such :) Do you still encounter the issue above after rebasing your work to the current master (my work on #2863 has been merged by now)? As you say, `LogAndFailExceptionHandler` is already registered for reflection, so it's a bit puzzling.

**Comment by gunnarmorling** [comment]
@muirandy, so the issue above should be fixed by @gsmet's PR https://github.com/quarkusio/quarkus/pull/3534. I had misread -- `LogAndFailExceptionHandler` was already registered, but `LogAndContinueExceptionHandler` wasn't. Have you configured this one explicitly? If so, it'd make sense to automatically register the configured handler in the extension, similar to what you plan to do fo the default SerDe.

**Comment by muirandy** [comment]
@gunnarmorling & @gsmet I guess that some of the other classes that are being registered here could also be read from the properties. I'll look after `LogAndContinueExceptionHandler` and indeed the default SerDes. I expect that `LogAndFailExceptionHandler` and `ByteArraySerde` should also be dependant on the properties?

**Comment by gunnarmorling** [comment]
Yes, for any types whose need for registration for reflection we can derive from the config, we should do it. The ones I had hard-coded were essentially the default values I had to enable in order to make things initially.

So taking a step back, I think for each property that takes the name of class(es) reflectively instantiated by Kafka (Streams), we should register the configured classes or register the default implementation. I don't quite remember why `ByteArraySerde` is needed, perhaps it's the default SerDe if nothing else is configured?

**Comment by muirandy** [comment]
@gunnarmorling @gsmet I've created a PR for this. Looking forward to the feedback!

**Comment by muirandy** [comment]
@cescoffier Whats the process for closing this ticket? Code was merged to master 2 weeks back.

**Comment by machi1990** [comment]
What was the PR closing the issue? Just for reference. Otherwise I can close the issue.

**Comment by muirandy** [comment]
[#3547](https://github.com/quarkusio/quarkus/pull/3547)

**Comment by machi1990** [comment]
Thanks. Closing.
