### ISSUE TITLE
CredentialsProvider API should be asynchronous

### ISSUE THREAD

**Issue by tsegismont** [quarkusio/quarkus#32021]
### Description

A `CredentialsProvider` can be invoked several times over the application's lifetime, not just on startup.
Besides, it can be invoked by an event loop thread.

But it has a synchronous API:

https://github.com/quarkusio/quarkus/blob/bc4955b027800abd07c066f63120bc37b532f634/extensions/credentials/runtime/src/main/java/io/quarkus/credentials/CredentialsProvider.java#L20

Given the implementation may read data on disk or from an external system, the API should be asynchronous (and the implementation non blocking).

### Implementation ideas

See https://github.com/quarkusio/quarkus/pull/31873#issuecomment-1476534265

**Comment by tsegismont** [comment]
cc @cescoffier @geoand

**Comment by redsolo** [comment]
I tried to implement a custom Credentials provider to be used by rabbitmq, and it gets the credentials properly the first times;  but when it is trying to refresh the credentials it raises the following exception.
```
2024-11-20 17:51:21,418 ERROR [com.rec.ale.job.orc.pro.amq.MyCredentialsProvider] (vert.x-eventloop-thread-4) meeeh: java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-4
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)
	at MyCredentialsProvider.getCredentials(MyCredentialsProvider.scala:21)
	at MyCredentialsProvider_ClientProxy.getCredentials(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.rabbitmq.runtime.CredentialsProviderLink.refresh(CredentialsProviderLink.java:53)
	at io.quarkus.smallrye.reactivemessaging.rabbitmq.runtime.CredentialsProviderLink_loYwekz4j5bK6dM_JNrDYaXpzmA_Synthetic_ClientProxy.refresh(Unknown Source)
	at com.rabbitmq.client.impl.DefaultCredentialsRefreshService$CredentialsProviderState.refresh(DefaultCredentialsRefreshService.java:334)
	at com.rabbitmq.client.impl.DefaultCredentialsRefreshService.lambda$refresh$1(DefaultCredentialsRefreshService.java:156)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by tsegismont** [comment]
@redsolo as a workaround, you may refresh credentials in the background and keep a copy of the result that `getCredentials` returns.

**Comment by cescoffier** [comment]
I was wondering about changing the API to have both a method returning a Uni and the "imperative" method. The `Uni` method when not explicitly implemented, would call the blocking one:

```java
default Map<String, String> getCredentials(String credentialsProviderName) {
    return UnsupportedOperationException("Either `getCredentials` or `retrieveCredentials` need to be implemented`);
}

default Uni<Map<String, String>> retrieveCredentials(String credentialProviderName) {
    return Uni.createFrom().item(() -> getCredentials(credentialProviderName));
}
```

With this, asynchronous credential retrievers would be integrated correctly.

Of course, it means that the callers would need to be updated. If they still use the blocking one, they won't be able to integrate with the asynchronous retriever. However, it provides a smooth migration instead of a big bang "break everything" change.

**Comment by tsegismont** [comment]
That sounds good to me @cescoffier , with one caveat: in the default async implementation, the call to the sync method should happen on a worker thread (maybe using `subscribeOn` or whatever this is called in Mutiny).
