### ISSUE TITLE
Quarkus watches wrong protobuf directory

### ISSUE THREAD

**Issue by micheljung** [quarkusio/quarkus#32092]
### Describe the bug

Using `io.quarkus:quarkus-grpc`.

When DEBUG log is enabled, this gets printed to the console a zillion times:

```
2023-03-23 22:32:00,132 DEBUG [io.qua.dep.uti.FSWatchUtil] (FSWatchUtil) Failed checking for code gen source modifications: java.nio.file.NoSuchFileException: C:\Users\foo\bar\build\classes\java\proto
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:198)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3825)
	at java.base/java.nio.file.Files.walk(Files.java:3879)
	at io.quarkus.deployment.util.FSWatchUtil.doObserve(FSWatchUtil.java:55)
	at io.quarkus.deployment.util.FSWatchUtil.lambda$observe$1(FSWatchUtil.java:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I'm not sure what directory it is looking for, but the ones that exist are:
* `src/main/proto`
* `build/classes/java/quarkus-generated-sources/grpc`

### Expected behavior

No Exception. I understand it's just DEBUG but it seems like it's looking for the wrong directory. If not, I wonder why the directory doesn't exist.

### Actual behavior

Exceptions are spamming the DEBUG log.

### How to Reproduce?

I can create one if needed

### Quarkus version or git rev

3.0.0.Beta1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

**Comment by BrianSetz** [comment]
This issues appears to only happen when you use Gradle, even when you create a clean project (https://code.quarkus.io/?e=grpc&extension-search=origin:platform%20quarkus-grpc). You only have to set Quarkus log levels to debug for the issue to appear.  

It is not only an issue on Windows, but also on Linux. 

```
2023-07-21 14:23:29,685 DEBUG [io.qua.dep.uti.FSWatchUtil] (FSWatchUtil) Failed checking for code gen source modifications: java.nio.file.NoSuchFileException: /home/user/foo/bar/build/classes/java/quarkus-generated-sources/proto
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3918)
	at java.base/java.nio.file.Files.walk(Files.java:3973)
	at io.quarkus.deployment.util.FSWatchUtil.doObserve(FSWatchUtil.java:55)
	at io.quarkus.deployment.util.FSWatchUtil.lambda$observe$1(FSWatchUtil.java:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It seems to me that the `codeGen.sourceDir` is set incorrectly ( https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/dev/CodeGenWatcher.java#L42 ). But I am unsure where this sourceDir originates from.

**Comment by cescoffier** [comment]
oh lovely, Thanks @BrianSetz.

@alesj .... I'm sure you are going to become a Gradle expert one day.

**Comment by cescoffier** [comment]
It would be great if we could get a reproducer.

**Comment by BrianSetz** [comment]
In case it is useful, I have pushed an example of this issue to this repository: https://github.com/BrianSetz/quarkus-grpc-nosuchfileexception

You can also manually reproduce it using the following steps: 
- Download this template: https://code.quarkus.io/?b=GRADLE&e=grpc&extension-search=origin:platform%20quarkus-grpc
- Add the following to application.properties
```
quarkus.log.level=DEBUG
```

You can also verify that it does **not** happen when using maven, using the following steps:
- Download this template: https://code.quarkus.io/?e=grpc&extension-search=origin:platform%20quarkus-grpc
- Add the following to application.properties
```
quarkus.log.level=DEBUG
```
