### ISSUE TITLE
Native building with container: Podman not detected on Windows

### ISSUE THREAD

**Issue by cedric780** [quarkusio/quarkus#32106]
Podman 4.4.2 is not detected on my Windows 10 machine when building a quarkus project
I use Quarkus 2.16.4.Final.

I installed podman with *scoop*.

I build my project with:

    mvn package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true

The problem comes from:
https://github.com/quarkusio/quarkus/blob/09fb41167ca41c1a794799f0555d5783b8c8b6fb/core/runtime/src/main/java/io/quarkus/runtime/util/ContainerRuntimeUtil.java#L65

getVersionOutputFor(ContainerRuntime.PODMAN) returns '`podman.exe version 4.4.2\n`' on my machine (`\n` seems to be a real end of line : [..., 50, 10]) . 

Then it does not match the test:
https://github.com/quarkusio/quarkus/blob/09fb41167ca41c1a794799f0555d5783b8c8b6fb/core/runtime/src/main/java/io/quarkus/runtime/util/ContainerRuntimeUtil.java#L66

I then have this stack trace:

```
Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.16.4.Final:build (default) on project my-quarkus-project: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.IllegalStateException: No container runtime was found to. Make sure you have Docker or Podman installed in your environment.
	at io.quarkus.runtime.util.ContainerRuntimeUtil.detectContainerRuntime(ContainerRuntimeUtil.java:42)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner.<init>(NativeImageBuildContainerRunner.java:32)
	at io.quarkus.deployment.pkg.steps.NativeImageBuildLocalContainerRunner.<init>(NativeImageBuildLocalContainerRunner.java:23)
	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.getNativeImageBuildRunner(NativeImageBuildStep.java:327)
	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:216)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by gsmet** [comment]
Thanks for the report. I create https://github.com/quarkusio/quarkus/pull/32107 to fix it.
