### ISSUE TITLE
Hibernate Reactive creates Oracle database table for identity strategy without generated identity primary key

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#32102]
### Describe the bug

This is https://github.com/quarkusio/quarkus/issues/32040 follow-up, I probably should stress out there is also problem for Oracle.

### Expected behavior

I can use identity strategy with Oracle database as I did with 2.16.

### Actual behavior

Application fails to start as database is created

```
create table authors (
        id number(10,0) not null,
        name varchar2(10 char) not null,
        primary key (id)
    )
```

there is no `GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` which seems weird to me. Following exception is logged:

```
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:273)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:250)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:592)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:640)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	... 37 more
Caused by: java.lang.RuntimeException: org.hibernate.MappingException: Error creating SQL create commands for table : books
	at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:82)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:97)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy(Unknown Source)
	... 53 more
Caused by: org.hibernate.MappingException: Error creating SQL create commands for table : books
	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:104)
	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:41)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createTables(SchemaCreatorImpl.java:435)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createSequencesTablesConstraints(SchemaCreatorImpl.java:355)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createFromMetadata(SchemaCreatorImpl.java:254)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:173)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:143)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:119)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:226)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:143)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:140)
	at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:366)
	at org.hibernate.reactive.session.impl.ReactiveSessionFactoryImpl.<init>(ReactiveSessionFactoryImpl.java:32)
	at io.quarkus.hibernate.reactive.runtime.boot.FastBootReactiveEntityManagerFactoryBuilder.build(FastBootReactiveEntityManagerFactoryBuilder.java:29)
	at io.quarkus.hibernate.reactive.runtime.FastBootHibernateReactivePersistenceProvider.createEntityManagerFactory(FastBootHibernateReactivePersistenceProvider.java:92)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:167)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:68)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.hibernate.MappingException: org.hibernate.dialect.identity.IdentityColumnSupportImpl does not support identity key generation
	at org.hibernate.dialect.identity.IdentityColumnSupportImpl.getIdentityColumnString(IdentityColumnSupportImpl.java:46)
	at org.hibernate.tool.schema.internal.ColumnDefinitions.appendColumnDefinition(ColumnDefinitions.java:161)
	at org.hibernate.tool.schema.internal.ColumnDefinitions.appendColumn(ColumnDefinitions.java:88)
	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:73)
	... 22 more
```

### How to Reproduce?

Steps to reproduce:

1. `git@github.com:DavideD/quarkus-issues.git`
2. `cd quarkus-issues/quarkus-32040`
3. `sed -i 's/reactive-pg-client/reactive-oracle-client/g' pom.xml`
4. `mvn clean verify`

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

openjdk 17.0.4 2022-07-19

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 22.3

### Quarkus version or git rev

3.0.0.Beta1 and 999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by DavideD** [comment]
We are still working on the support for Oracle for this version.

**Comment by michalvavrik** [comment]
@DavideD that's fine then, I can close this.

**Comment by michalvavrik** [comment]
@DavideD I also experienced problems with MsSQL on code that worked in 2.16, that's WIP too? (that requires different code, below is just a hint)

```
10:27:57,398 INFO  [app] 10:27:56,611 HHH000099: an assertion failure occurred (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): org.hibernate.AssertionFailure: null identifier (io.quarkus.ts.hibernate.reactive.database.Book)
10:27:45,392 INFO  [app] 10:27:44,662 HHH000099: an assertion failure occurred (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): org.hibernate.AssertionFailure: null identifier (io.quarkus.ts.hibernate.reactive.database.Book)
10:27:45,392 INFO  [app] org.hibernate.HibernateException: org.hibernate.AssertionFailure: null identifier (io.quarkus.ts.hibernate.reactive.database.Book)
10:27:45,392 INFO  [app] 	at org.hibernate.reactive.session.impl.ReactiveExceptionConverter.convert(ReactiveExceptionConverter.java:28)
10:27:45,392 INFO  [app] 	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.lambda$doFlush$29(ReactiveSessionImpl.java:1110)
10:27:45,392 INFO  [app] 	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
10:27:45,392 INFO  [app] 	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
10:27:45,392 INFO  [app] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
10:27:45,392 INFO  [app] 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
10:27:45,393 INFO  [app] 	at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.lambda$unroll$0(AsyncTrampoline.java:123)
10:27:45,393 INFO  [app] 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
10:27:45,393 INFO  [app] 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
10:27:45,393 INFO  [app] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
10:27:45,393 INFO  [app] 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
10:27:45,393 INFO  [app] 	at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:384)
10:27:45,393 INFO  [app] 	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
10:27:45,393 INFO  [app] 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
10:27:45,394 INFO  [app] 	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
10:27:45,394 INFO  [app] 	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
10:27:45,394 INFO  [app] 	at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:100)
10:27:45,394 INFO  [app] 	at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:34)
10:27:45,394 INFO  [app] 	at io.vertx.core.Promise.complete(Promise.java:66)
10:27:45,394 INFO  [app] 	at io.vertx.core.Promise.handle(Promise.java:51)
10:27:45,394 INFO  [app] 	at io.vertx.core.Promise.handle(Promise.java:29)
10:27:45,394 INFO  [app] 	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
10:27:45,394 INFO  [app] 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
10:27:45,394 INFO  [app] 	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
10:27:45,394 INFO  [app] 	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
10:27:45,395 INFO  [app] 	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
10:27:45,395 INFO  [app] 	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
10:27:45,395 INFO  [app] 	at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72)
10:27:45,395 INFO  [app] 	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
10:27:45,395 INFO  [app] 	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
10:27:45,395 INFO  [app] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
10:27:45,395 INFO  [app] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
10:27:45,395 INFO  [app] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
10:27:45,395 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
10:27:45,396 INFO  [app] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
10:27:45,396 INFO  [app] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
10:27:45,396 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
10:27:45,396 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:833)
10:27:45,396 INFO  [app] Caused by: org.hibernate.AssertionFailure: null identifier (io.quarkus.ts.hibernate.reactive.database.Book)
10:27:45,396 INFO  [app] 	at org.hibernate.engine.spi.EntityKey.<init>(EntityKey.java:50)
10:27:45,396 INFO  [app] 	at org.hibernate.internal.AbstractSharedSessionContract.generateEntityKey(AbstractSharedSessionContract.java:618)
10:27:45,396 INFO  [app] 	at org.hibernate.reactive.engine.impl.ReactiveEntityIdentityInsertAction.lambda$reactiveExecute$3(ReactiveEntityIdentityInsertAction.java:77)
10:27:45,396 INFO  [app] 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
10:27:45,396 INFO  [app] 	... 29 more

```

**Comment by DavideD** [comment]
> @DavideD I also experienced problems with MsSQL on code that worked in 2.16, that's WIP too? (that requires different code, below is just a hint)

Yes, it will work in the next release

> btw @DavideD I know I'm working against main, so it's not exactly user case and I need to expect lack of docs, but it would be nice to have a hint somewhere, because I didn't find anything about this in https://github.com/quarkusio/quarkus/pull/31454 (just note that there are not Oracle tests)

I'm aware. Sorry about it.

**Comment by michalvavrik** [comment]
Thanks for info!
