### ISSUE TITLE
Updating to Quarkus 3: build breaks when io.quarkiverse.jooq.deployment tries to access javax

### ISSUE THREAD

**Issue by sandrasap** [quarkusio/quarkus#32126]
### Describe the bug

After upgrading to Quarkus 3, it seems that `io.quarkiverse.jooq.deployment` is still trying to access a javax library:

```
2023-03-24 18:17:43,216 INFO  [io.qua.cxf.dep.QuarkusCxfProcessor] (build-91) Preventing access to http://java.sun.com/dtd/properties.dtd
2023-03-24 18:17:43,388 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-03-24 18:17:43,564 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.jooq.deployment.JooqProcessor#build threw an exception: java.lang.NoClassDefFoundError: javax/enterprise/context/ApplicationScoped
at io.quarkiverse.jooq.deployment.JooqProcessor.createDslContextProducerBean(JooqProcessor.java:117)
	at io.quarkiverse.jooq.deployment.JooqProcessor.build(JooqProcessor.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	...
```

This is breaking the build. Adding the following dependency to the `pom.xml` didn't have an effect:

```
<dependency>
          <groupId>io.quarkiverse.jooq</groupId>
          <artifactId>quarkus-jooq-deployment</artifactId>
          <version>0.4.0</version>
 </dependency>
```

### Expected behavior

To match with Quarkus 3, I believe `io.quarkiverse.jooq.deployment` should use Jakarta, and the build will succeed.

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110 arm64

### Output of `java -version`

openjdk version "11.0.16" 2022-07-19 LTS OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS) OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)

### Quarkus version or git rev

3.0.0.Alpha6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by famod** [comment]
It seems the jooq extensions hasn't moved to Quarkus 3 yet: https://github.com/quarkiverse/quarkus-jooq/pull/113

**Comment by geoand** [comment]
Closing as this is not a Quarkus core issue
