### ISSUE TITLE
Quarkus 2.13 test extension tests fail with the 22.3 mandrel builder image and

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#32152]
### Describe the bug

The integration tests fail with the 22.3 mandrel builder image. Filing this for tracking purposes:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.it.extension.ClasspathInGraalITCase
Executing "/home/runner/work/mandrel/mandrel/quarkus/integration-tests/test-extension/tests/target/quarkus-integration-test-test-extension-tests-999-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/home/runner/work/mandrel/mandrel/quarkus/integration-tests/test-extension/tests/target/quarkus.log -Dquarkus.log.file.enable=true"
Mar 25, 2023 2:19:24 AM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
java.lang.ClassNotFoundException: io.quarkus.extest.runtime.config.RunTimeConfigBuilder
	at java.base@17.0.6/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
	at java.base@17.0.6/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base@17.0.6/java.lang.ClassLoader.loadClass(ClassLoader.java:132)
	at io.quarkus.runtime.configuration.ConfigUtils.configBuilder(ConfigUtils.java:189)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:43)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:123)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

### Expected behavior

Test extension tests pass with the builder image.

### Actual behavior

Test throws `ClassNotFoundException` at boot.

### How to Reproduce?

Run integration tests extension tests with the 22.3 builder image.

### Additional information

See https://github.com/graalvm/mandrel/actions/runs/4516801805/jobs/7955690955#step:11:1120

**Comment by jerboaa** [comment]
I'm not sure if this is an expected failure or not.

**Comment by radcortez** [comment]
This requires https://github.com/quarkusio/quarkus/pull/30220.

It should have been backported with https://github.com/quarkusio/quarkus/pull/29842.

**Comment by zakkak** [comment]
Hello @radcortez , are there any updates on this? Should we label the two PRs for backport?

**Comment by radcortez** [comment]
I did open a backport here: https://github.com/quarkusio/quarkus/pull/32278.

But the CI is having a few issues (not related to this particular backport). It requires additional backports to fix the CI:
https://github.com/quarkusio/quarkus/pull/32278#issuecomment-1493380778
