### ISSUE TITLE
@RestCookie/@RestHeader (and relative @*Param) applied to Temporal parameter lead to deployment failure

### ISSUE THREAD

**Issue by luca-bassoricci** [quarkusio/quarkus#32194]
### Describe the bug

```java
@Path("/hello")
public class GreetingResource {
    @Inject
    ObjectMapper mapper;

    @Path("{path}")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public String hello(@RestQuery("query") Instant query, @RestPath("path") Instant path,
            @RestHeader("header") Instant header, @RestCookie("cookie") Instant cookie) throws IOException {}
}
```

header and cookie extracted as `java.time.temporal.*` produce and invalid build

```posh
Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Failed to process method 'org.acme.GreetingResource#hello'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:323)
	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:633)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:[281](https://github.com/luca-bassoricci/code-with-quarkus/actions/runs/4544958243/jobs/8011773735#step:4:282))
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Failed to process method 'org.acme.GreetingResource#hello'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:765)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:412)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:[290](https://github.com/luca-bassoricci/code-with-quarkus/actions/runs/4544958243/jobs/8011773735#step:4:291))
	... 12 more
Caused by: java.lang.RuntimeException: Could not create converter for java.time.Instant for method java.lang.String hello(java.time.Instant query, java.time.Instant path, java.time.Instant header, java.time.Instant cookie) throws java.io.IOException on class org.acme.GreetingResource of type HEADER
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:367)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:96)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.extractParameterInfo(EndpointIndexer.java:1407)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:592)
	... 14 more
Caused by: java.lang.RuntimeException: Failed to find converter for java.time.Instant
	at org.jboss.resteasy.reactive.server.processor.generation.converters.GeneratedConverterIndexerExtension.extractConverterImpl(GeneratedConverterIndexerExtension.java:106)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.extractConverter(ServerEndpointIndexer.java:564)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:363)
	... 17 more
```

### Expected behavior

A valid build with data extracted from header/cookie as Temporal value.

### Actual behavior

Invalid build

### How to Reproduce?

Reproducer at https://github.com/luca-bassoricci/code-with-quarkus; just build to reproduce the error

### Output of `uname -a` or `ver`

Windows 11

### Output of `java -version`

temurin 17

### Quarkus version or git rev

2.16.5.Final

**Comment by geoand** [comment]
Thanks for reporting, I'll have a look

**Comment by luca-bassoricci** [comment]
I pulled a draft PR

**Comment by geoand** [comment]
Ah, okay. Let me have a look
