### ISSUE TITLE
Do not print stack-trace in LogStreamBroadcaster.recordHistory

### ISSUE THREAD

**Issue by JanWiemer** [quarkusio/quarkus#32203]
### Describe the bug

```posh
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.ReentrantLock$Sync.lockInterruptibly(ReentrantLock.java:159)
        at java.base/java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:372)
        at java.base/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:432)
        at io.quarkus.devui.runtime.logstream.LogStreamBroadcaster.recordHistory(LogStreamBroadcaster.java:33)
        at io.quarkus.devui.runtime.logstream.LogStreamBroadcaster.onNext(LogStreamBroadcaster.java:21)
        at io.quarkus.devui.runtime.logstream.LogStreamBroadcaster_ClientProxy.onNext(Unknown Source)
        at io.quarkus.devui.runtime.logstream.MutinyLogHandler.doPublish(MutinyLogHandler.java:31)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:327)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
		...
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

This is perfectly OK, but the stacktrace should not be printed to the console by default in io.quarkus.devui.runtime.logstream.LogStreamBroadcaster:

```java
   private void recordHistory(final JsonObject message) {
        synchronized (this) {
            try {
                if (history.remainingCapacity() == 0) {
                    history.take();
                }
                history.add(message);
            } catch (InterruptedException ex) {
                ex.printStackTrace(); // <------- REMOVE THIS
                Thread.currentThread().interrupt();
            }
        }
    }
```

### Expected behavior

No stacktrace in console logging

### Actual behavior

stacktrace is printed on console

**Comment by geoand** [comment]
Seems reasonable to me, WDYT @phillip-kruger ?

**Comment by phillip-kruger** [comment]
Sounds good to me

**Comment by geoand** [comment]
@JanWiemer would you be interested in contributing the fix?

**Comment by JanWiemer** [comment]
Super fast reaction! :-)

Yes I would be interested to contribute, if its not too urgent and if someone provide me a link how to start with a contribution (would be my first one.).

Anyway Thx in advance! :-)

**Comment by geoand** [comment]
💪🏼 

You can see how to build the project [here](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#build).
If you have any questions, feel free to ask

**Comment by JanWiemer** [comment]
Tried to create a pull request (via Gitpod) and hope I've done it correctly ;-)
Link: https://github.com/quarkusio/quarkus/pull/32368
