### ISSUE TITLE
org.apache.commons.lang3 library functions doesn't work in Quarkus native build

### ISSUE THREAD

**Issue by paolo-bruno** [quarkusio/quarkus#32218]
### Describe the bug

We use SerializationUtils.clone() method of org.apache.commons.lang3 library in an Apache Kafka Stream application.
There are no problems when running in jvm mode, but when we launch the application in native mode and insert a message in the input topic, the following error occurs:

```posh
2023-03-29 10:11:48,933 ERROR [org.apa.kaf.str.pro.int.TaskExecutor] (outbound-stream-9bc4e44e-3670-47f1-9a34-b98c349c9198-StreamThread-1) stream-thread [outbound-stream-9bc4e44e-3670-47f1-9a34-b98c349c9198-StreamThread-1] Failed to process stream task 1_0 due to the following error:: org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=1_0, processor=KSTREAM-SOURCE-0000000004, topic=picking-event, partition=0, offset=0, stacktrace=org.apache.commons.lang3.SerializationException: IOException while reading or closing cloned object data
        at org.apache.commons.lang3.SerializationUtils.clone(SerializationUtils.java:155)
        at eu.my.application.stream.TopologyProducer.lambda$buildTopology$35(TopologyProducer.java:521)
        at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        ...
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:551)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.io.InvalidClassException: eu.my.application.maserdata.PickingEvent; no valid constructor
        at java.base@17.0.5/java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:172)
        at java.base@17.0.5/java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:790)
        at java.base@17.0.5/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2225)
        at java.base@17.0.5/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
        at java.base@17.0.5/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
        at java.base@17.0.5/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
        at org.apache.commons.lang3.SerializationUtils.clone(SerializationUtils.java:149)
        ... 45 more

        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:737)
        at org.apache.kafka.streams.processor.internals.TaskExecutor.processTask(TaskExecutor.java:100)
        at org.apache.kafka.streams.processor.internals.TaskExecutor.process(TaskExecutor.java:81)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:1177)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:769)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:589)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:551)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: org.apache.commons.lang3.SerializationException: IOException while reading or closing cloned object data
        at org.apache.commons.lang3.SerializationUtils.clone(SerializationUtils.java:155)
        ...
        at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:809)
        at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:780)
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:711)
        ... 8 more
Caused by: java.io.InvalidClassException: eu.my.application.maserdata.PickingEvent; no valid constructor
        at java.base@17.0.5/java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:172)
        at java.base@17.0.5/java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:790)
        at java.base@17.0.5/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2225)
        at java.base@17.0.5/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
        at java.base@17.0.5/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
        at java.base@17.0.5/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
        at org.apache.commons.lang3.SerializationUtils.clone(SerializationUtils.java:149)
        ... 45 more
```

### Actual behavior

The error seems to refer to org.apache.commons.lang3.SerializationUtils.ClassLoaderAwareObjectInputStream.class, at
```
ClassLoaderAwareObjectInputStream(InputStream in, ClassLoader classLoader) throws IOException {
    super(in);
    this.classLoader = classLoader;
}
```

So I think it's due to a problem with the reflection of some library classes, or to a strategy used by the classLoader for GraalVM native images, but I don't know what to try.

### GraalVM version (if different from Java)

Quarkus native-image plugin on native-image 22.3.0.1-Final Mandrel Distribution (Java Version 17.0.5+8)

### Quarkus version or git rev

2.13.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

./mvnw clean package -Dnative -Dquarkus.native.container-build=true -DskipTest

### Additional information

 I also tried adding following to the reflection class configuration:
```
@RegisterForReflection(targets = {
    PickingEvent.class,
    SerializationUtils.class
})
public class QuarkusConfiguration {
}
```

**Comment by geoand** [comment]
Quarkus does not support commons-lang3 out of the box, so it's up to users to provide the necessary GraalVM native-image configuration in their applications to make it work in native mode.

As you mention, in this case you need to register the problematic class for reflection so GraalVM can find its constructors
