### ISSUE TITLE
Config mapping beans not available in a custom Hibernate  `ConstraintValidator`

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#32265]
### Describe the bug

Having a config mapping class:

```
@ConfigMapping(prefix = "some.props")
public interface MyConfig {
}
```

I can not inject it into a custom `ConstraintValidator` using:
```
@ApplicationScoped
public class MaxInsertManyDocumentsValidation implements ConstraintValidator<..., ...> {

    @Inject
    MyConfig config;
```

Exception being thrown:

```
Caused by: java.util.NoSuchElementException: SRCFG00027: Could not find a mapping for ....MyConfig
	at io.smallrye.config.ConfigMappings.getConfigMapping(ConfigMappings.java:111)
	at io.smallrye.config.SmallRyeConfig.getConfigMapping(SmallRyeConfig.java:411)
	at io.quarkus.arc.runtime.ConfigMappingCreator.create(ConfigMappingCreator.java:31)
```

### Expected behavior

Config mappings can be injected, as they can be injected to other `ApplicationScope` beans.

### How to Reproduce?

See above.

### Quarkus version or git rev

2.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /home/ise/.m2/wrapper/dists/apache-maven-3.8.6-bin/67568434/apache-maven-3.8.6 Java version: 17.0.6, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-69-generic", arch: "amd64", family: "unix"

### Additional information

Workaround is to use the `@ConfigProperty(name = "..")` in the validator, which works atm.

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
Duplicated by #24540.

Please use `Instance<MyConfig>` to inject the mapping.

Closing in favor of #24540.
