### ISSUE TITLE
Native Build: Illegal/unsupported escape sequence

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#32272]
### Describe the bug

This just started happening recently and was not happening before:

```
Fatal error: java.util.regex.PatternSyntaxException: 
Illegal/unsupported escape sequence near index 34
META-INF/resources/resources\demo\images\product\galaxy-earrings.jpg
```

```
Fatal error: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 34
META-INF/resources/resources\demo\images\product\galaxy-earrings.jpg
                                  ^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
        at java.base/java.util.regex.Pattern.escape(Pattern.java:2608)
        at java.base/java.util.regex.Pattern.atom(Pattern.java:2286)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2210)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.makeResourcePattern(ResourcesFeature.java:289)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.compilePatterns(ResourcesFeature.java:282)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:270)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:162)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:745)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

### Expected behavior

Native Build works properly

### Actual behavior

Native Build failing with the above issue.

### How to Reproduce?

Reproducer:

1. git clone https://github.com/melloware/quarkus-faces
2. `mvn -Pnative`

See failure.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.1413]

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)

### GraalVM version (if different from Java)

 22.3.1.0-Final Mandrel Distribution (Java Version 17.0.6+10)

### Quarkus version or git rev

3.0.0-CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

**Comment by galderz** [comment]
Can you define "before"? Is that Quarkus 3.0.0.Beta1? Quarkus 2.x?

**Comment by melloware** [comment]
Alpha4 was definitely working so something after Alpha4?  Or could it be the Mandrel image I didn't pay close attention to that version?

**Comment by zakkak** [comment]
@melloware is this related to https://github.com/quarkusio/quarkus/issues/31307?
