### ISSUE TITLE
Quarkus 3.0.0.CR1 throw NoSuchMethodException where use   @CreationTimestamp  and   @UpdateTimestamp  

### ISSUE THREAD

**Issue by yuhaibohotmail** [quarkusio/quarkus#32333]
### Describe the bug

```java
@Entity
public class MyEntity {
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Integer id;

    @Column(updatable = false)
    @CreationTimestamp
    public Timestamp createdDate;

    @Column()
    @UpdateTimestamp
    public Timestamp modifiedDate;
}
```

### Actual behavior

```log
09:11:31 ERROR [io.qu.ru.Application] (main) Failed to start application (with profile [prod]): java.lang.NoSuchMethodException: org.hibernate.generator.internal.CurrentTimestampGeneration.<init>()
        at java.base@17.0.5/java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.base@17.0.5/java.lang.Class.newInstance(DynamicHub.java:626)
        at org.hibernate.boot.model.internal.GeneratorBinder.instantiateGenerator(GeneratorBinder.java:419)
        at org.hibernate.boot.model.internal.GeneratorBinder.lambda$generatorCreator$0(GeneratorBinder.java:362)
        at org.hibernate.mapping.Property.createGenerator(Property.java:464)
        at org.hibernate.tuple.entity.EntityMetamodel.buildGenerator(EntityMetamodel.java:477)
        at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:312)
        at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:513)
        at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:145)
        at java.base@17.0.5/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base@17.0.5/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:92)
        at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:75)
        at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.processBootEntities(MappingMetamodelImpl.java:247)
        at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.finishInitialization(MappingMetamodelImpl.java:185)
        at org.hibernate.internal.SessionFactoryImpl$1.<init>(SessionFactoryImpl.java:275)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:268)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:200)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:79)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:167)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:68)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
```

### Additional information

CurrentTimestampGeneration  does not have a parameterless constructor:

https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/generator/internal/CurrentTimestampGeneration.java

**Comment by gsmet** [comment]
@yrodiere could you have a look at this one?

**Comment by yrodiere** [comment]
It's caused by some classes incorrectly not being registered for reflection in `org.hibernate.graalvm.internal.GraalVMStaticFeature`. I'll try to implement a workaround in Quarkus and also fix it upstream.

**Comment by yrodiere** [comment]
Created https://hibernate.atlassian.net/browse/HHH-16439 upstream
