### ISSUE TITLE
"java.lang.OutOfMemoryError: GC overhead limit exceeded" when building native app

### ISSUE THREAD

**Issue by ginccc** [quarkusio/quarkus#3235]
Hi,

I am trying to build a native app, but constantly get this error. I have setup memory limits to 4gb already for maven. 
Can it really be that this build needs so much memory or might there be a other problem?

```
/c/dev/git/EDDI (feature/quarkus)
$ export MAVEN_OPTS="-Xmx4096m -XX:MaxPermSize=2048m"

/c/dev/git/EDDI (feature/quarkus)
$ echo $MAVEN_OPTS
-Xmx4096m -XX:MaxPermSize=2048m

/c/dev/git/EDDI (feature/quarkus)
$ ./mvnw package -Pnative -Dnative-image.docker-build=true
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] eddi                                                               [pom]
[INFO] persistencestore-definition                                        [jar]
[INFO] basemodels                                                         [jar]
[INFO] conversationmemory-definition                                      [jar]
[INFO] conversationlifecycle-definition                                   [jar]
[INFO] runtime-definition                                                 [jar]
[INFO] sharedutilities                                                    [jar]
[INFO] expressions                                                        [jar]
[INFO] user-definition                                                    [jar]
[INFO] permissions-definition                                             [jar]
[INFO] corerest-definition                                                [jar]
[INFO] configurationrepository-definition                                 [jar]
[INFO] automatedtesting-definition                                        [jar]
[INFO] httpclient-definition                                              [jar]
[INFO] coreutilities                                                      [jar]
[INFO] persistencestore-impl                                              [jar]
[INFO] user-impl                                                          [jar]
[INFO] permissions-impl                                                   [jar]
[INFO] conversationmemory-impl                                            [jar]
[INFO] conversationlifecycle-impl                                         [jar]
[INFO] runtime-impl                                                       [jar]
[INFO] webserver                                                          [jar]
[INFO] httpclient-impl-jetty                                              [jar]
[INFO] staticresourceprovider-definition                                  [jar]
[INFO] caching-definition                                                 [jar]
[INFO] caching-impl-infinispan                                            [jar]
[INFO] configurationrepository-impl                                       [jar]
[INFO] automatedtesting-impl                                              [jar]
[INFO] staticresourceprovider-impl                                        [jar]
[INFO] outputgeneration-definition                                        [jar]
[INFO] semanticparser-definition                                          [jar]
[INFO] semanticparser-impl                                                [jar]
[INFO] conversationcallback-definition                                    [jar]
[INFO] conversationcallback-impl                                          [jar]
[INFO] coreserver                                                         [jar]
[INFO] outputgeneration-impl                                              [jar]
[INFO] facebookmessenger-definition                                       [jar]
[INFO] facebookmessenger-impl                                             [jar]
[INFO] xmpp-definition                                                    [jar]
[INFO] xmpp-impl                                                          [jar]
[INFO] behavior-impl                                                      [jar]
[INFO] templateengine-definition                                          [jar]
[INFO] templateengine-impl-thymeleaf                                      [jar]
[INFO] propertysetter-definition                                          [jar]
[INFO] propertysetter-impl                                                [jar]
[INFO] httpCallsTask-impl                                                 [jar]
[INFO] backupservice-defintion                                            [jar]
[INFO] backupservice-impl                                                 [jar]
[INFO] apiserver                                                          [jar]
[INFO]
[INFO] ----------------------------< ai.labs:eddi >----------------------------
[INFO] Building eddi 4.7                                                 [1/49]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- jandex-maven-plugin:1.0.6:jandex (make-index) @ eddi ---
[INFO]
[INFO] --- quarkus-maven-plugin:0.19.1:build (default) @ eddi ---
[INFO] Type of the artifact is POM, skipping build goal
[INFO]
[INFO] --- quarkus-maven-plugin:0.19.1:native-image (default) @ eddi ---
[INFO] Type of the artifact is POM and appArtifact parameter has not been set, skipping native-image goal
[INFO]
[INFO] ----------------< ai.labs:persistencestore-definition >-----------------
[INFO] Building persistencestore-definition 4.7                          [2/49]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ persistencestore-definition ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ persistencestore-definition ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- jandex-maven-plugin:1.0.6:jandex (make-index) @ persistencestore-definition ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ persistencestore-definition ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\dev\git\EDDI\persistencestore-definition\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ persistencestore-definition ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ persistencestore-definition ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ persistencestore-definition ---
[INFO] Building jar: C:\dev\git\EDDI\persistencestore-definition\target\persistencestore-definition-4.7.jar
[INFO]
[INFO] --- quarkus-maven-plugin:0.19.1:build (default) @ persistencestore-definition ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Beta4
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1440ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: C:\dev\git\EDDI\persistencestore-definition\target\persistencestore-definition-4.7-runner.jar
[INFO]
[INFO] --- quarkus-maven-plugin:0.19.1:native-image (default) @ persistencestore-definition ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on Java HotSpot(TM) 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] docker run -v C:\dev\git\EDDI\persistencestore-definition\target:/project:z --rm quay.io/quarkus/ubi-quarkus-native-image:19.0.2 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager --initializ
e-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar persistencestore-definition-4.7-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTra
ces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI -H:-UseServiceLoaderFeature -H:+StackTrace
Build on Server(pid: 9, port: 40985)*
[persistencestore-definition-4.7-runner:9]    classlist:  11,690.31 ms
[persistencestore-definition-4.7-runner:9]        (cap):   1,280.56 ms
[persistencestore-definition-4.7-runner:9]        setup:   2,732.26 ms
19:09:51,569 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta4
19:09:52,842 INFO  [org.xnio] XNIO version 3.7.2.Final
19:09:52,924 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.2.Final
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.quarkus.runtime.CleanableExecutor$R
esetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored.
 The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.quarkus.runtime.CleanableExecutor$R
esetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored.
 The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResetting
Runnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation
is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResetting
Runnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation
is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
[persistencestore-definition-4.7-runner:9]     analysis: 154,549.22 ms
Fatal error: java.lang.OutOfMemoryError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:458)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:292)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:430)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:390)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:327)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:408)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:324)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:268)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:228)
java.lang.OutOfMemoryError: GC overhead limit exceeded
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eddi 4.7:
[INFO]
[INFO] eddi ............................................... SUCCESS [  1.878 s]
[INFO] persistencestore-definition ........................ FAILURE [06:32 min]
[INFO] basemodels ......................................... SKIPPED
[INFO] conversationmemory-definition ...................... SKIPPED
[INFO] conversationlifecycle-definition ................... SKIPPED
[INFO] runtime-definition ................................. SKIPPED
[INFO] sharedutilities .................................... SKIPPED
[INFO] expressions ........................................ SKIPPED
[INFO] user-definition .................................... SKIPPED
[INFO] permissions-definition ............................. SKIPPED
[INFO] corerest-definition ................................ SKIPPED
[INFO] configurationrepository-definition ................. SKIPPED
[INFO] automatedtesting-definition ........................ SKIPPED
[INFO] httpclient-definition .............................. SKIPPED
[INFO] coreutilities ...................................... SKIPPED
[INFO] persistencestore-impl .............................. SKIPPED
[INFO] user-impl .......................................... SKIPPED
[INFO] permissions-impl ................................... SKIPPED
[INFO] conversationmemory-impl ............................ SKIPPED
[INFO] conversationlifecycle-impl ......................... SKIPPED
[INFO] runtime-impl ....................................... SKIPPED
[INFO] webserver .......................................... SKIPPED
[INFO] httpclient-impl-jetty .............................. SKIPPED
[INFO] staticresourceprovider-definition .................. SKIPPED
[INFO] caching-definition ................................. SKIPPED
[INFO] caching-impl-infinispan ............................ SKIPPED
[INFO] configurationrepository-impl ....................... SKIPPED
[INFO] automatedtesting-impl .............................. SKIPPED
[INFO] staticresourceprovider-impl ........................ SKIPPED
[INFO] outputgeneration-definition ........................ SKIPPED
[INFO] semanticparser-definition .......................... SKIPPED
[INFO] semanticparser-impl ................................ SKIPPED
[INFO] conversationcallback-definition .................... SKIPPED
[INFO] conversationcallback-impl .......................... SKIPPED
[INFO] coreserver ......................................... SKIPPED
[INFO] outputgeneration-impl .............................. SKIPPED
[INFO] facebookmessenger-definition ....................... SKIPPED
[INFO] facebookmessenger-impl ............................. SKIPPED
[INFO] xmpp-definition .................................... SKIPPED
[INFO] xmpp-impl .......................................... SKIPPED
[INFO] behavior-impl ...................................... SKIPPED
[INFO] templateengine-definition .......................... SKIPPED
[INFO] templateengine-impl-thymeleaf ...................... SKIPPED
[INFO] propertysetter-definition .......................... SKIPPED
[INFO] propertysetter-impl ................................ SKIPPED
[INFO] httpCallsTask-impl ................................. SKIPPED
[INFO] backupservice-defintion ............................ SKIPPED
[INFO] backupservice-impl ................................. SKIPPED
[INFO] apiserver .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:36 min
[INFO] Finished at: 2019-07-15T21:15:53+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.19.1:native-image (default) on project persistencestore-definition: Failed to generate a native image: Failed to build native image: Image generation failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :persistencestore-definition

```

**Comment by mmornati** [comment]
Hey, I add exactly the same problem at the beginning on my Mac. The amount of memory I think it can depend on the number of modules you are adding to your project.
In my case, I simply fixed it just adding memory to my Docker Machine (it seems you are building using docker too). How much? No idea... here you are what I have and it is working for me:

![image](https://user-images.githubusercontent.com/139323/61247555-9b3a7580-a751-11e9-9e8c-5cf8b2e337e0.png)

On OSx I think by default there is not much RAM which is reserved to Docker...

**Comment by ginccc** [comment]
Ha! That was it, thanks. Of course it won't have an effect if i change the memory on maven, as the build is happening inside docker not on my local machine..

Appreciate the hint, @mmornati

PS: 2GB was not enough, 4GB memory seem to do the trick.

**Comment by geoand** [comment]
I think that the suggestion by @mmornati is spot on. 
Basically building the native image is a resource intensive operation and based on your command line you are using building it via docker - which means that you need to make sure docker has plenty of memory.
The memory settings you have changed for Maven won't have any effect since the native image is not being built in Java.

**Comment by BradleySmithVaGov** [comment]
Every other answer to this question I found suggested adding memory to the jvm, but the docker runtime was the key.  Thanks!
