### ISSUE TITLE
Failed to execute goal io.quarkus:quarkus-maven-plugin:3.0.0.CR1:build

### ISSUE THREAD

**Issue by msmygit** [quarkusio/quarkus#32379]
### Describe the bug

Getting the below:
```
Failed to execute goal io.quarkus:quarkus-maven-plugin:3.0.0.CR1:build
```

when attempting to leverage `3.0.0.CR1` version which was released a couple days back.

Stacktrace:
```
[2023-04-03T16:06:32.215Z] Apache Maven 3.6.0
[2023-04-03T16:06:32.215Z] Maven home: /usr/share/maven
[2023-04-03T16:06:32.215Z] Java version: 11.0.18, vendor: GraalVM Community, runtime: /usr/lib/jabba/jdk/11.0.18-graalvm-ce-22.3.1
[2023-04-03T16:06:32.215Z] Default locale: en, platform encoding: UTF-8
[2023-04-03T16:06:32.215Z] OS name: "linux", version: "5.4.0-1094-aws", arch: "amd64", family: "unix"
...
[2023-04-03T16:06:39.250Z] [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/freemarker/freemarker/2.3.32/freemarker-2.3.32.jar (1.7 MB at 9.3 MB/s)
[2023-04-03T16:06:39.250Z] [WARNING] Error injecting: io.quarkus.maven.BuildMojo
[2023-04-03T16:06:39.250Z] com.google.inject.ProvisionException: Unable to provision, see the following errors:
[2023-04-03T16:06:39.250Z] 
[2023-04-03T16:06:39.250Z] 1) No implementation for io.quarkus.maven.QuarkusBootstrapProvider was bound.
[2023-04-03T16:06:39.250Z]   while locating io.quarkus.maven.BuildMojo
[2023-04-03T16:06:39.250Z] 
[2023-04-03T16:06:39.250Z] 1 error
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.InjectorImpl$2.get (InjectorImpl.java:1025)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.InjectorImpl.getInstance (InjectorImpl.java:1051)
[2023-04-03T16:06:39.250Z]     at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:81)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:53)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:65)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:115)
[2023-04-03T16:06:39.250Z]     at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision (BeanScheduler.ja:176)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:126)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:68)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:63)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:45)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.InjectorImpl$2$1.call (InjectorImpl.java:1016)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.InjectorImpl.callInContext (InjectorImpl.java:1092)
[2023-04-03T16:06:39.250Z]     at com.google.inject.internal.InjectorImpl$2.get (InjectorImpl.java:1012)
[2023-04-03T16:06:39.250Z]     at org.eclipse.sisu.inject.Guice4$1.get (Guice4.java:162)
[2023-04-03T16:06:39.250Z]     at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
[2023-04-03T16:06:39.250Z]     at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
[2023-04-03T16:06:39.250Z]     at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
[2023-04-03T16:06:39.250Z]     at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:520)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
[2023-04-03T16:06:39.250Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
[2023-04-03T16:06:39.250Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2023-04-03T16:06:39.250Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2023-04-03T16:06:39.250Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2023-04-03T16:06:39.250Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2023-04-03T16:06:39.250Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
[2023-04-03T16:06:39.250Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
[2023-04-03T16:06:39.250Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
[2023-04-03T16:06:39.250Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
...
[2023-04-03T16:06:39.250Z] [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.0.0.CR1:build (default) on project test-project-quarkus-integration-tests: Execution default of goal io.quarkus:quarkus-maven-plugin:3.0.0.CR1:build failed: Unable to load the mojo 'build' (or one of its required components) from the plugin 'io.quarkus:quarkus-maven-plugin:3.0.0.CR1': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[2023-04-03T16:06:39.250Z] [ERROR] 
[2023-04-03T16:06:39.250Z] [ERROR] 1) No implementation for io.quarkus.maven.QuarkusBootstrapProvider was bound.
[2023-04-03T16:06:39.250Z] [ERROR]   while locating io.quarkus.maven.BuildMojo
[2023-04-03T16:06:39.250Z] [ERROR]   at ClassRealm[plugin>io.quarkus:quarkus-maven-plugin:3.0.0.CR1, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@55f96302] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[2023-04-03T16:06:39.250Z] [ERROR]   while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=io.quarkus:quarkus-maven-plugin:3.0.0.CR1:build)
[2023-04-03T16:06:39.250Z] [ERROR] 
[2023-04-03T16:06:39.250Z] [ERROR] 1 error
[2023-04-03T16:06:39.250Z] [ERROR]       role: org.apache.maven.plugin.Mojo
[2023-04-03T16:06:39.250Z] [ERROR]   roleHint: io.quarkus:quarkus-maven-plugin:3.0.0.CR1:build
[2023-04-03T16:06:39.250Z] [ERROR] -> [Help 1]
...

### Expected behavior

Build suceeding.

### Actual behavior

Erroring out.

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

3.0.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

**Comment by aloubyansky** [comment]
Could you please try with Maven 3.6.3 or later?

**Comment by famod** [comment]
Got something similar with Maven 3.8.8 when running `quarkus update --stream=3.0` (Quarkus CLI 3.0.0.CR2):
```
Error injecting: io.quarkus.maven.UpdateMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for io.quarkus.maven.components.QuarkusWorkspaceProvider was bound.
  while locating io.quarkus.maven.UpdateMojo

1 error
```

The problem vanishes when using Maven 3.9.1.

**Comment by aloubyansky** [comment]
Which version of `quarkus` CLI was it @famod?

**Comment by aloubyansky** [comment]
Ah, sorry, you already provided that info.

**Comment by aloubyansky** [comment]
I can't reproduce it. @famod can you reliably reproduce it with Maven 3.8.8? Could you please post the complete log?

**Comment by msmygit** [comment]
Thank you team & @aloubyansky!. It worked with maven `3.6.3+`.

**Comment by aloubyansky** [comment]
Thanks for confirming it worked with more recent Maven versions @msmygit

**Comment by famod** [comment]
@aloubyansky well, strange - I cannot reproduce anymore either.

PS: I only seeing another smaller issue: The update recipe doesn't catch the separate version propery for the quarkus-maven-plugin (the way it was may months ago).

**Comment by hntan** [comment]
I got a similar error with quarkus `3.2.0.Final` and maven `3.9.1`.

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code (default) on project lqa-service: Execution default of goal io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code failed: Unable to load the mojo 'generate-code' (or one of its required components) from the plugin 'io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) [Guice/ErrorInjectingConstructor]: NullPointerException: Cannot invoke "io.quarkus.devtools.messagewriter.MessageWriter.warn(String, Object[])" because "this.log" is null
[ERROR]   at BuildAnalyticsProvider.<init>(BuildAnalyticsProvider.java:35)
[ERROR]   at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
[ERROR]       \_ installed by: WireModule -> PlexusBindingModule
[ERROR]   at BootstrapSessionListener.<init>(BootstrapSessionListener.java:26)
[ERROR]       \_ for 2nd parameter buildAnalyticsProvider
[ERROR]   at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
[ERROR]       \_ installed by: WireModule -> PlexusBindingModule
[ERROR]   while locating BootstrapSessionListener
[ERROR]   while locating Object annotated with *
[ERROR]   while locating GenerateCodeMojo
[ERROR]   at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
[ERROR]       \_ installed by: WireModule -> PlexusBindingModule
[ERROR]   while locating Mojo annotated with @Named("io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code")
[ERROR] 
[ERROR] Learn more:
[ERROR]   https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
[ERROR] 
[ERROR] 1 error
[ERROR] 
[ERROR] ======================
[ERROR] Full classname legend:
[ERROR] ======================
[ERROR] BootstrapSessionListener: "io.quarkus.maven.components.BootstrapSessionListener"
[ERROR] BuildAnalyticsProvider:   "io.quarkus.maven.BuildAnalyticsProvider"
[ERROR] Final:                    "3.2.0.Final"
[ERROR] GenerateCodeMojo:         "io.quarkus.maven.GenerateCodeMojo"
[ERROR] Mojo:                     "org.apache.maven.plugin.Mojo"
[ERROR] Named:                    "com.google.inject.name.Named"
[ERROR] PlexusBindingModule:      "org.eclipse.sisu.plexus.PlexusBindingModule"
[ERROR] URLClassLoader:           "java.net.URLClassLoader"
[ERROR] WireModule:               "org.eclipse.sisu.wire.WireModule"
```

**Comment by lukaszlenart** [comment]
Same problem using Maven 3.9.0 and Quarkus Maven plugin 3.3.0

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.3.0:build (default) on project quarkus: Execution default of goal io.quarkus:quarkus-maven-plugin:3.3.0:build failed: Unable to load the mojo 'build' (or one of its required components) from the plugin 'io.quarkus:quarkus-maven-plugin:3.3.0': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) No implementation for io.quarkus.maven.QuarkusBootstrapProvider was bound.
[ERROR]   while locating io.quarkus.maven.BuildMojo
[ERROR]   at ClassRealm[plugin>io.quarkus:quarkus-maven-plugin:3.3.0, parent: java.net.URLClassLoader@457e2f02] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR]   while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=io.quarkus:quarkus-maven-plugin:3.3.0:build)
[ERROR] 
[ERROR] 1 error
[ERROR]       role: org.apache.maven.plugin.Mojo
[ERROR]   roleHint: io.quarkus:quarkus-maven-plugin:3.3.0:build
```

**Comment by maxandersen** [comment]
@lukaszlenart sorry you are getting that error - best to open new issue with updated full stacktrace and steps to reproduce.

**Comment by lukaszlenart** [comment]
> @lukaszlenart sorry you are getting that error - best to open new issue with updated full stacktrace and steps to reproduce.

will do, thanks!

**Comment by lukaszlenart** [comment]
btw. I'm running the plugin on JDK11 - is that the problem?

**Comment by aloubyansky** [comment]
No, it's not.

**Comment by stroem2** [comment]
Quarkus 3.10.1 - it worked with Maven version 3.8.8.

**Comment by holly-cummins** [comment]
I've just hit this, trying to update a 2.9.5 project to 3+. https://quarkus.io/guides/update-quarkus says to use `./mvnw io.quarkus.platform:quarkus-maven-plugin:3.13.2:update -N`
but because the thing I'm updating is so ancient, the `./mvnw` is old and hits the workspace bind error. `mvn  io.quarkus.platform:quarkus-maven-plugin:3.13.2:update -N` does work. 

Maybe we need to update the docs to suggest trying `mvn` as a fallback? It seems likely we could have similar compatibility issues in the future, too.
