### ISSUE TITLE
Different http status code after Hibernate 6.2.0.Final merge, using spring-web and orm-panache

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#32397]
### Describe the bug

After Hibernate 6.2.0.Final merge one test in our TS started to fail - https://github.com/quarkus-qe/quarkus-test-suite/blob/main/spring/spring-web/src/test/java/io/quarkus/ts/spring/web/reactive/boostrap/AbstractSpringWebRestIT.java#L70

Setting book author to null.

Returned error code is now 500 (internal server error), before the merge the status code was 400 (bad request). Test was created ~2 years ago.

### Expected behavior

Test passes

### Actual behavior

Test fails - [ERROR]   SpringWebRestIT>AbstractSpringWebRestIT.whenInvalidBook_thenError:78 expected: <400> but was: <500>

### How to Reproduce?

 - clone https://github.com/quarkus-qe/quarkus-test-suite
 - run `mvn clean verify -pl spring/spring-web -Dit.test=SpringWebRestIT#whenInvalidBook_thenError`

`mvn clean verify -pl spring/spring-web -Dit.test=SpringWebRestIT#whenInvalidBook_thenError -Dquarkus.platform.version=3.0.0.CR1` passes

### Output of `java -version`

Java 17

### Quarkus version or git rev

Quarkus main

**Comment by rsvoboda** [comment]
The fail happens with RESTEasy Classic, not with RESTEasy Reactive (which returns 400).

Stacktrace:
```
14:25:24,976 INFO  [app] 14:25:24,690 HTTP Request to /api/books failed, error id: 20adc9f2-22f0-418d-ab4b-0a452ef52fed-1: org.jboss.resteasy.spi.UnhandledException: org.hibernate.PropertyValueException: not-null property references a null or transient value : io.quarkus.ts.spring.web.reactive.boostrap.persistence.model.Book.author
14:25:24,976 INFO  [app] 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:110)
14:25:24,976 INFO  [app] 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:370)
14:25:24,977 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
14:25:24,977 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
14:25:24,977 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
14:25:24,977 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
14:25:24,977 INFO  [app] 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
14:25:24,978 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
14:25:24,978 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
14:25:24,978 INFO  [app] 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
14:25:24,978 INFO  [app] 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
14:25:24,979 INFO  [app] 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
14:25:24,979 INFO  [app] 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
14:25:24,979 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
14:25:24,979 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
14:25:24,979 INFO  [app] 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
14:25:24,979 INFO  [app] 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
14:25:24,980 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
14:25:24,980 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:833)
14:25:24,980 INFO  [app] Caused by: org.hibernate.PropertyValueException: not-null property references a null or transient value : io.quarkus.ts.spring.web.reactive.boostrap.persistence.model.Book.author
14:25:24,980 INFO  [app] 	at org.hibernate.engine.internal.Nullability.checkNullability(Nullability.java:109)
14:25:24,980 INFO  [app] 	at org.hibernate.engine.internal.Nullability.checkNullability(Nullability.java:54)
14:25:24,980 INFO  [app] 	at org.hibernate.action.internal.AbstractEntityInsertAction.nullifyTransientReferencesIfNotAlready(AbstractEntityInsertAction.java:124)
14:25:24,981 INFO  [app] 	at org.hibernate.action.internal.AbstractEntityInsertAction.makeEntityManaged(AbstractEntityInsertAction.java:133)
14:25:24,981 INFO  [app] 	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:294)
14:25:24,981 INFO  [app] 	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:268)
14:25:24,981 INFO  [app] 	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:255)
14:25:24,981 INFO  [app] 	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:373)
14:25:24,981 INFO  [app] 	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:274)
14:25:24,982 INFO  [app] 	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:180)
14:25:24,982 INFO  [app] 	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:136)
14:25:24,982 INFO  [app] 	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:175)
14:25:24,982 INFO  [app] 	at org.hibernate.event.internal.DefaultPersistEventListener.persist(DefaultPersistEventListener.java:93)
14:25:24,982 INFO  [app] 	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:77)
14:25:24,982 INFO  [app] 	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:54)
14:25:24,982 INFO  [app] 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
14:25:24,983 INFO  [app] 	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:755)
14:25:24,983 INFO  [app] 	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:739)
14:25:24,983 INFO  [app] 	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.persist(TransactionScopedSession.java:145)
14:25:24,983 INFO  [app] 	at org.hibernate.engine.spi.SessionLazyDelegator.persist(SessionLazyDelegator.java:275)
14:25:24,983 INFO  [app] 	at org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_ClientProxy.persist(Unknown Source)
14:25:24,983 INFO  [app] 	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:101)
14:25:24,983 INFO  [app] 	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:96)
14:25:24,983 INFO  [app] 	at io.quarkus.hibernate.orm.panache.PanacheRepositoryBase.persist(PanacheRepositoryBase.java:54)
14:25:24,984 INFO  [app] 	at io.quarkus.ts.spring.web.reactive.boostrap.persistence.repo.BookRepository_ClientProxy.persist(Unknown Source)
14:25:24,984 INFO  [app] 	at io.quarkus.ts.spring.web.reactive.boostrap.web.BookController.create(BookController.java:51)
14:25:24,984 INFO  [app] 	at io.quarkus.ts.spring.web.reactive.boostrap.web.BookController_Subclass.create$$superforward(Unknown Source)
14:25:24,984 INFO  [app] 	at io.quarkus.ts.spring.web.reactive.boostrap.web.BookController_Subclass$$function$$1.apply(Unknown Source)
14:25:24,984 INFO  [app] 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:74)
14:25:24,984 INFO  [app] 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:63)
14:25:24,984 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
14:25:24,984 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
14:25:24,985 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
14:25:24,985 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
14:25:24,985 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
14:25:24,985 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
14:25:24,985 INFO  [app] 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
14:25:24,985 INFO  [app] 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:38)
14:25:24,985 INFO  [app] 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:26)
14:25:24,986 INFO  [app] 	at io.quarkus.ts.spring.web.reactive.boostrap.web.BookController_Subclass.create(Unknown Source)
14:25:24,986 INFO  [app] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:25:24,986 INFO  [app] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
14:25:24,986 INFO  [app] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:25:24,986 INFO  [app] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
14:25:24,986 INFO  [app] 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
14:25:24,986 INFO  [app] 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
14:25:24,987 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
14:25:24,987 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
14:25:24,987 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
14:25:24,987 INFO  [app] 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
14:25:24,987 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
14:25:24,987 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
14:25:24,987 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
14:25:24,988 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
14:25:24,988 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
14:25:24,988 INFO  [app] 	... 15 more
14:25:27,926 INFO  [app] Service stopped (Quarkus JVM mode)
```

**Comment by rsvoboda** [comment]
Stacktrace with 3.0.0.CR1:

```
14:47:03,763 INFO  ## Running test SpringWebRestIT.whenInvalidBook_thenError()
14:47:07,463 INFO  [app] 14:47:06,365 Error: 1048-23000: Column 'author' cannot be null
14:47:07,464 INFO  [app] 14:47:06,366 SQL Error: 1048, SQLState: 23000
14:47:07,464 INFO  [app] 14:47:06,366 (conn=3) Column 'author' cannot be null
14:47:07,464 INFO  [app] 14:47:06,371 ARJUNA012125: TwoPhaseCoordinator.beforeCompletion - failed for SynchronizationImple< 0:ffff7f000001:d4fb:642c1c4a:1, org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@240122f6 >: org.hibernate.exception.ConstraintViolationException: could not execute statement [(conn=3) Column 'author' cannot be null] [insert into Book (author,title,id) values (?,?,?)]
14:47:07,464 INFO  [app] 	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:60)
14:47:07,464 INFO  [app] 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
14:47:07,464 INFO  [app] 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
14:47:07,464 INFO  [app] 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:278)
14:47:07,465 INFO  [app] 	at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.performNonBatchedMutation(AbstractMutationExecutor.java:98)
14:47:07,465 INFO  [app] 	at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorSingleNonBatched.performNonBatchedOperations(MutationExecutorSingleNonBatched.java:40)
14:47:07,465 INFO  [app] 	at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.execute(AbstractMutationExecutor.java:43)
14:47:07,465 INFO  [app] 	at org.hibernate.persister.entity.mutation.InsertCoordinator.doStaticInserts(InsertCoordinator.java:168)
14:47:07,465 INFO  [app] 	at org.hibernate.persister.entity.mutation.InsertCoordinator.coordinateInsert(InsertCoordinator.java:110)
14:47:07,465 INFO  [app] 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2775)
14:47:07,466 INFO  [app] 	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:102)
14:47:07,466 INFO  [app] 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:616)
14:47:07,466 INFO  [app] 	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:487)
14:47:07,466 INFO  [app] 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
14:47:07,466 INFO  [app] 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:484)
14:47:07,466 INFO  [app] 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:358)
14:47:07,466 INFO  [app] 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
14:47:07,467 INFO  [app] 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
14:47:07,467 INFO  [app] 	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1412)
14:47:07,467 INFO  [app] 	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:485)
14:47:07,467 INFO  [app] 	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2296)
14:47:07,467 INFO  [app] 	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1961)
14:47:07,467 INFO  [app] 	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:426)
14:47:07,467 INFO  [app] 	at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:336)
14:47:07,468 INFO  [app] 	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
14:47:07,468 INFO  [app] 	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
14:47:07,468 INFO  [app] 	at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:76)
14:47:07,468 INFO  [app] 	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:360)
14:47:07,468 INFO  [app] 	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:91)
14:47:07,468 INFO  [app] 	at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
14:47:07,468 INFO  [app] 	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
14:47:07,469 INFO  [app] 	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
14:47:07,469 INFO  [app] 	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
14:47:07,469 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
14:47:07,469 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:171)
14:47:07,469 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
14:47:07,469 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
14:47:07,469 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
14:47:07,470 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
14:47:07,470 INFO  [app] 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
14:47:07,470 INFO  [app] 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
14:47:07,470 INFO  [app] 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:38)
14:47:07,470 INFO  [app] 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:26)
14:47:07,470 INFO  [app] 	at io.quarkus.ts.spring.web.reactive.boostrap.web.BookController_Subclass.create(Unknown Source)
14:47:07,471 INFO  [app] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:47:07,471 INFO  [app] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
14:47:07,471 INFO  [app] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:47:07,471 INFO  [app] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
14:47:07,471 INFO  [app] 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
14:47:07,471 INFO  [app] 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
14:47:07,471 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
14:47:07,472 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
14:47:07,472 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
14:47:07,472 INFO  [app] 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
14:47:07,472 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
14:47:07,472 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
14:47:07,472 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
14:47:07,473 INFO  [app] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
14:47:07,473 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
14:47:07,473 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
14:47:07,473 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
14:47:07,473 INFO  [app] 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
14:47:07,473 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
14:47:07,473 INFO  [app] 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
14:47:07,473 INFO  [app] 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
14:47:07,474 INFO  [app] 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
14:47:07,474 INFO  [app] 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
14:47:07,474 INFO  [app] 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
14:47:07,474 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
14:47:07,474 INFO  [app] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
14:47:07,474 INFO  [app] 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
14:47:07,474 INFO  [app] 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
14:47:07,475 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
14:47:07,475 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:833)
14:47:07,475 INFO  [app] Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=3) Column 'author' cannot be null
14:47:07,475 INFO  [app] 	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:290)
14:47:07,475 INFO  [app] 	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
14:47:07,475 INFO  [app] 	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:134)
14:47:07,475 INFO  [app] 	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:855)
14:47:07,476 INFO  [app] 	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:794)
14:47:07,476 INFO  [app] 	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:713)
14:47:07,476 INFO  [app] 	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:637)
14:47:07,476 INFO  [app] 	at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:95)
14:47:07,476 INFO  [app] 	at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:334)
14:47:07,476 INFO  [app] 	at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:311)
14:47:07,476 INFO  [app] 	at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
14:47:07,477 INFO  [app] 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:275)
14:47:07,477 INFO  [app] 	... 70 more
14:47:09,674 INFO  [app] Service stopped (Quarkus JVM mode)
```

**Comment by rsvoboda** [comment]
Did some digging and there is [RestExceptionHandler.java](https://github.com/quarkus-qe/quarkus-test-suite/blob/main/spring/spring-web/src/main/java/io/quarkus/ts/spring/web/reactive/boostrap/web/RestExceptionHandler.java) in the testing app which I will need to adjust.

**Comment by rsvoboda** [comment]
So the problem is on our side, there was an adjustment of the ExceptionHandler ~1 month ago to react to the changes done in Quarkus main via https://github.com/quarkus-qe/quarkus-test-suite/pull/1089. Those changes seemed to be adjusted with 6.2.0.Final, we didn't realize the behavior change ~1 month ago was more bogus than intentional.
