### ISSUE TITLE
Native Build should not build each maven module separately in a multi-module project

### ISSUE THREAD

**Issue by ginccc** [quarkusio/quarkus#3240]
I believe this native build fails, because it is missing the application.configuration file. 
It's true, this particular submodule doesn't contain this file, as I only have it once in my application, not a duplicate in each individual module. 
I noticed this, as it was complaining about this already at the first module (persistencestore-definition), then i copied the config file into this module. After that it worked, but failed at the next sub-module with the same error.

Note: It feels there is no support in quarkus for multi-module maven projects just yet. It treats the app in separate parts rather then creating a big one of all modules and build runner or native for that only. No reason to have a runner in each sub-module, it won't execute anyways.

```
/c/dev/git/EDDI (feature/quarkus)
$ ./mvnw package -Pnative -Dnative-image.docker-build=true
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] eddi                                                               [pom]
[INFO] persistencestore-definition                                        [jar]
[INFO] basemodels                                                         [jar]
[INFO] conversationmemory-definition                                      [jar]
[INFO] conversationlifecycle-definition                                   [jar]
[INFO] runtime-definition                                                 [jar]
[INFO] sharedutilities                                                    [jar]
[INFO] expressions                                                        [jar]
[INFO] user-definition                                                    [jar]
[INFO] permissions-definition                                             [jar]
[INFO] corerest-definition                                                [jar]
[INFO] configurationrepository-definition                                 [jar]
[INFO] automatedtesting-definition                                        [jar]
[INFO] httpclient-definition                                              [jar]
[INFO] coreutilities                                                      [jar]
[INFO] persistencestore-impl                                              [jar]
[INFO] user-impl                                                          [jar]
[INFO] permissions-impl                                                   [jar]
[INFO] conversationmemory-impl                                            [jar]
[INFO] conversationlifecycle-impl                                         [jar]
[INFO] runtime-impl                                                       [jar]
[INFO] webserver                                                          [jar]
[INFO] httpclient-impl-jetty                                              [jar]
[INFO] staticresourceprovider-definition                                  [jar]
[INFO] caching-definition                                                 [jar]
[INFO] caching-impl-infinispan                                            [jar]
[INFO] configurationrepository-impl                                       [jar]
[INFO] automatedtesting-impl                                              [jar]
[INFO] staticresourceprovider-impl                                        [jar]
[INFO] outputgeneration-definition                                        [jar]
[INFO] semanticparser-definition                                          [jar]
[INFO] semanticparser-impl                                                [jar]
[INFO] conversationcallback-definition                                    [jar]
[INFO] conversationcallback-impl                                          [jar]
[INFO] coreserver                                                         [jar]
[INFO] outputgeneration-impl                                              [jar]
[INFO] facebookmessenger-definition                                       [jar]
[INFO] facebookmessenger-impl                                             [jar]
[INFO] xmpp-definition                                                    [jar]
[INFO] xmpp-impl                                                          [jar]
[INFO] behavior-impl                                                      [jar]
[INFO] templateengine-definition                                          [jar]
[INFO] templateengine-impl-thymeleaf                                      [jar]
[INFO] propertysetter-definition                                          [jar]
[INFO] propertysetter-impl                                                [jar]
[INFO] httpCallsTask-impl                                                 [jar]
[INFO] backupservice-defintion                                            [jar]
[INFO] backupservice-impl                                                 [jar]
[INFO] apiserver                                                          [jar]
[INFO]
[INFO] ----------------------------< ai.labs:eddi >----------------------------
[INFO] Building eddi 4.7                                                 [1/49]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- jandex-maven-plugin:1.0.6:jandex (make-index) @ eddi ---
[INFO]
[INFO] --- quarkus-maven-plugin:0.19.1:build (default) @ eddi ---
[INFO] Type of the artifact is POM, skipping build goal
[INFO]
[INFO] --- quarkus-maven-plugin:0.19.1:native-image (default) @ eddi ---
[INFO] Type of the artifact is POM and appArtifact parameter has not been set, skipping native-image goal
[INFO]
[INFO] ----------------< ai.labs:persistencestore-definition >-----------------
[INFO] Building persistencestore-definition 4.7                          [2/49]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ persistencestore-definition ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ persistencestore-definition ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- jandex-maven-plugin:1.0.6:jandex (make-index) @ persistencestore-definition ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ persistencestore-definition ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\dev\git\EDDI\persistencestore-definition\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ persistencestore-definition ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ persistencestore-definition ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ persistencestore-definition ---
[INFO] Building jar: C:\dev\git\EDDI\persistencestore-definition\target\persistencestore-definition-4.7.jar
[INFO]
[INFO] --- quarkus-maven-plugin:0.19.1:build (default) @ persistencestore-definition ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Beta4
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 2443ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: C:\dev\git\EDDI\persistencestore-definition\target\persistencestore-definition-4.7-runner.jar
[INFO]
[INFO] --- quarkus-maven-plugin:0.19.1:native-image (default) @ persistencestore-definition ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on Java HotSpot(TM) 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] docker run -v C:\dev\git\EDDI\persistencestore-definition\target:/project:z --rm quay.io/quarkus/ubi-quarkus-native-image:19.0.2 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager --initializ
e-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar persistencestore-definition-4.7-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTra
ces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI -H:-UseServiceLoaderFeature -H:+StackTrace
Build on Server(pid: 9, port: 36705)*
[persistencestore-definition-4.7-runner:9]    classlist:  18,930.34 ms
[persistencestore-definition-4.7-runner:9]        (cap):   2,153.34 ms
[persistencestore-definition-4.7-runner:9]        setup:   4,869.63 ms
07:01:10,573 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta4
07:01:13,083 INFO  [org.xnio] XNIO version 3.7.2.Final
07:01:13,366 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.2.Final
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.quarkus.runtime.CleanableExecutor$R
esetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored.
 The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.quarkus.runtime.CleanableExecutor$R
esetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored.
 The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResetting
Runnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation
is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResetting
Runnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation
is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
[persistencestore-definition-4.7-runner:9]   (typeflow): 124,222.56 ms
[persistencestore-definition-4.7-runner:9]    (objects):  74,669.96 ms
[persistencestore-definition-4.7-runner:9]   (features):   3,028.62 ms
[persistencestore-definition-4.7-runner:9]     analysis: 204,497.17 ms
Printing call tree to /project/reports/call_tree_persistencestore-definition-4.7-runner_20190716_070740.txt
Printing list of used classes to /project/reports/used_classes_persistencestore-definition-4.7-runner_20190716_070902.txt
Printing list of used packages to /project/reports/used_packages_persistencestore-definition-4.7-runner_20190716_070903.txt
[persistencestore-definition-4.7-runner:9]     (clinit):   4,791.78 ms
[persistencestore-definition-4.7-runner:9]     universe:  11,311.64 ms
[persistencestore-definition-4.7-runner:9]      (parse):  10,072.37 ms
[persistencestore-definition-4.7-runner:9]     (inline):  14,019.50 ms
[persistencestore-definition-4.7-runner:9]    (compile):  75,451.48 ms
[persistencestore-definition-4.7-runner:9]      compile: 103,895.33 ms
[persistencestore-definition-4.7-runner:9]        image:   5,257.65 ms
[persistencestore-definition-4.7-runner:9]        write:   1,223.46 ms
[persistencestore-definition-4.7-runner:9]      [total]: 622,861.93 ms
[INFO]
[INFO] -------------------------< ai.labs:basemodels >-------------------------
[INFO] Building basemodels 4.7                                           [3/49]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ basemodels ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ basemodels ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- jandex-maven-plugin:1.0.6:jandex (make-index) @ basemodels ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ basemodels ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\dev\git\EDDI\basemodels\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ basemodels ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ basemodels ---
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ basemodels ---
[INFO] Building jar: C:\dev\git\EDDI\basemodels\target\basemodels-4.7.jar
[INFO]
[INFO] --- quarkus-maven-plugin:0.19.1:build (default) @ basemodels ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [io.quarkus.arc.processor.BeanProcessor] Found unrecommended usage of private members (use package-private instead) in application beans:
        - Producer method ai.labs.bootstrap.RuntimeModule#provideExecutor()
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 828ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: C:\dev\git\EDDI\basemodels\target\basemodels-4.7-runner.jar
[INFO]
[INFO] --- quarkus-maven-plugin:0.19.1:native-image (default) @ basemodels ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on Java HotSpot(TM) 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] docker run -v C:\dev\git\EDDI\basemodels\target:/project:z --rm quay.io/quarkus/ubi-quarkus-native-image:19.0.2 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager --initialize-at-build-time=
-H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar basemodels-4.7-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-
AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI -H:-UseServiceLoaderFeature -H:+StackTrace
Build on Server(pid: 10, port: 42083)*
[basemodels-4.7-runner:10]    classlist:  11,498.57 ms
[basemodels-4.7-runner:10]        (cap):   1,119.26 ms
[basemodels-4.7-runner:10]        setup:   2,647.60 ms
07:11:36,573 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta4
07:11:37,626 INFO  [org.xnio] XNIO version 3.7.2.Final
07:11:37,810 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.2.Final
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.quarkus.runtime.CleanableExecutor$R
esetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored.
 The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.quarkus.runtime.CleanableExecutor$R
esetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored.
 The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResetting
Runnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation
is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResetting
Runnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation
is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
[basemodels-4.7-runner:10]     analysis:  22,064.52 ms
Printing call tree to /project/reports/call_tree_basemodels-4.7-runner_20190716_071157.txt
Printing list of used classes to /project/reports/used_classes_basemodels-4.7-runner_20190716_071158.txt
Printing list of used packages to /project/reports/used_packages_basemodels-4.7-runner_20190716_071158.txt
Error: Class initialization failed: io.quarkus.runner.ApplicationImpl2
Detailed message:

com.oracle.svm.core.util.UserError$UserException: Class initialization failed: io.quarkus.runner.ApplicationImpl2
Detailed message:

        at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:219)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:733)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Class initialization failed: io.quarkus.runner.ApplicationImpl2
Detailed message:

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:564)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:684)
        ... 7 more
Caused by: java.lang.ExceptionInInitializerError
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:129)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:357)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:92)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:120)
        at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:179)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:263)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:204)
        at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:154)
        at org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4229)
        at org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4472)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5260)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:838)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:214)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:333)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:509)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        ... 4 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl2.<clinit>(ApplicationImpl2.zig:152)
        ... 34 more
Caused by: java.lang.IllegalStateException: Keycloak configuration not found, please refer to the Quarkus documentation to learn how to configure your application
        at io.quarkus.keycloak.KeycloakRecorder.createKeycloakDeploymentContext(KeycloakRecorder.java:37)
        at io.quarkus.deployment.steps.KeycloakAdapterProcessor$configureAdapter32.deploy_0(KeycloakAdapterProcessor$configureAdapter32.zig:47)
        at io.quarkus.deployment.steps.KeycloakAdapterProcessor$configureAdapter32.deploy(KeycloakAdapterProcessor$configureAdapter32.zig:106)
        at io.quarkus.runner.ApplicationImpl2.<clinit>(ApplicationImpl2.zig:66)
        ... 34 more
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eddi 4.7:
[INFO]
[INFO] eddi ............................................... SUCCESS [  4.170 s]
[INFO] persistencestore-definition ........................ SUCCESS [10:53 min]
[INFO] basemodels ......................................... FAILURE [ 53.759 s]
[INFO] conversationmemory-definition ...................... SKIPPED
[INFO] conversationlifecycle-definition ................... SKIPPED
[INFO] runtime-definition ................................. SKIPPED
[INFO] sharedutilities .................................... SKIPPED
[INFO] expressions ........................................ SKIPPED
[INFO] user-definition .................................... SKIPPED
[INFO] permissions-definition ............................. SKIPPED
[INFO] corerest-definition ................................ SKIPPED
[INFO] configurationrepository-definition ................. SKIPPED
[INFO] automatedtesting-definition ........................ SKIPPED
[INFO] httpclient-definition .............................. SKIPPED
[INFO] coreutilities ...................................... SKIPPED
[INFO] persistencestore-impl .............................. SKIPPED
[INFO] user-impl .......................................... SKIPPED
[INFO] permissions-impl ................................... SKIPPED
[INFO] conversationmemory-impl ............................ SKIPPED
[INFO] conversationlifecycle-impl ......................... SKIPPED
[INFO] runtime-impl ....................................... SKIPPED
[INFO] webserver .......................................... SKIPPED
[INFO] httpclient-impl-jetty .............................. SKIPPED
[INFO] staticresourceprovider-definition .................. SKIPPED
[INFO] caching-definition ................................. SKIPPED
[INFO] caching-impl-infinispan ............................ SKIPPED
[INFO] configurationrepository-impl ....................... SKIPPED
[INFO] automatedtesting-impl .............................. SKIPPED
[INFO] staticresourceprovider-impl ........................ SKIPPED
[INFO] outputgeneration-definition ........................ SKIPPED
[INFO] semanticparser-definition .......................... SKIPPED
[INFO] semanticparser-impl ................................ SKIPPED
[INFO] conversationcallback-definition .................... SKIPPED
[INFO] conversationcallback-impl .......................... SKIPPED
[INFO] coreserver ......................................... SKIPPED
[INFO] outputgeneration-impl .............................. SKIPPED
[INFO] facebookmessenger-definition ....................... SKIPPED
[INFO] facebookmessenger-impl ............................. SKIPPED
[INFO] xmpp-definition .................................... SKIPPED
[INFO] xmpp-impl .......................................... SKIPPED
[INFO] behavior-impl ...................................... SKIPPED
[INFO] templateengine-definition .......................... SKIPPED
[INFO] templateengine-impl-thymeleaf ...................... SKIPPED
[INFO] propertysetter-definition .......................... SKIPPED
[INFO] propertysetter-impl ................................ SKIPPED
[INFO] httpCallsTask-impl ................................. SKIPPED
[INFO] backupservice-defintion ............................ SKIPPED
[INFO] backupservice-impl ................................. SKIPPED
[INFO] apiserver .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:54 min
[INFO] Finished at: 2019-07-16T09:12:01+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.19.1:native-image (default) on project basemodels: Failed to generate a native image: Failed to build native image: Image generation failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :basemodels

```

**Comment by rquinio** [comment]
The quarkus-maven-plugin should be added **only** to the module that packages the application (and thus contains the application.properties). It will augment / do the native compilation of the whole classpath in one shot.

**Comment by gsmet** [comment]
Closing as we didn't have any answer for a while.
