### ISSUE TITLE
ERROR Being Logged In Quarkus 3.0.0.CR1 DevUIProcessor with camel-quarkus-twilio extension

### ISSUE THREAD

**Issue by spieps** [quarkusio/quarkus#32414]
### Describe the bug

In quarkus platform version 3.0.0.CR1, and when the `camel-quarkus-twilio` extension is present.. On application startup with `./mvnw compile quarkus:dev` the following error is logged. 

**The application still starts up fine**, and the relevant camel extensions appear in the list at the bottom of the Dev UI (localhost:8080/q/dev) . I'm not sure if anything is actually broken in regards to the dev UI,  or if the log just needs to stop being  printed?

```
2023-04-04 15:40:36,263 ERROR [io.qua.dev.dep.DevUIProcessor] (build-129) Failed to process extension descriptor jar:file:///Users/sethpiepergerdes/.m2/repository/org/apache/camel/quarkus/camel-quarkus-core/3.0.0-M1/camel-quarkus-core-3.0.0-M1.jar!/META-INF/quarkus-extension.yaml: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
        at io.quarkus.devui.deployment.DevUIProcessor.lambda$getAllExtensions$1(DevUIProcessor.java:403)
        at io.quarkus.runtime.util.ClassPathUtils.lambda$consumeAsPath$0(ClassPathUtils.java:121)
        at io.quarkus.runtime.util.ClassPathUtils.processAsPath(ClassPathUtils.java:154)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPath(ClassPathUtils.java:120)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:104)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:85)
        at io.quarkus.devui.deployment.DevUIProcessor.getAllExtensions(DevUIProcessor.java:366)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```
### Expected behavior

No errors from DevUIProcessor are logged when the camel-quarkus-twilio extension is present

### Actual behavior

Error is logged on application start up regarding camel and the DevUIProcessor

### How to Reproduce?

1. Generate a quarkus app with quarkus.platform.version 3.0.0.CR1 at [code.quarkus.io](https://code.quarkus.io/?g=org.potato&a=potato-artifact&e=resteasy-reactive-jackson&e=rest-client-reactive-jackson&e=org.apache.camel.quarkus%3Acamel-quarkus-twilio&S=io.quarkus.platform%3A3.0&extension-search=origin:platform%20twil)

![image](https://user-images.githubusercontent.com/103952931/229916819-107d64be-fb95-4f4d-b78f-9489d838c406.png)

And boot the application with `./mvnw compile quarkus:dev`, then the error log will come. After, you can remove the camel-quarkus-twilio extension to verify that the error is not logged when the extension is not present.

### Output of `uname -a` or `ver`

Darwin FTSRoot-100268.attlocal.net 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### Quarkus version or git rev

3.0.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /usr/local/Cellar/maven/3.8.5/libexec
Java version: 17.0.5, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.3.0/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "13.3", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
We should probably handle issues like this gracefully as to avoid having the DevUI being broken by malformed metadata in extensions.

**Comment by phillip-kruger** [comment]
Yea agreed, I don't think this breaks anything though, just print. And the extension seems ok, so I'll have to have a deeper look.

**Comment by geoand** [comment]
Thanks
