### ISSUE TITLE
Native build fails with 3.0.0.CR2

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#32465]
### Describe the bug

If you try to build a native Image with CR2 it fails

Extensions: quarkus-resteasy-reactive, quarkus-container-image-docker, quarkus-arc

### Expected behavior

Should not fail

### Actual behavior

Fails with a null pointer

<details>

<summary>Logs of the build</summary>

```
13:32:08: Executing 'build'...

> Task :processResources
> Task :quarkusGenerateCode
> Task :quarkusGenerateCodeDev
> Task :compileJava
> Task :classes
> Task :jar
> Task :quarkusGenerateCodeTests
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
22.3-java17: Pulling from quarkus/ubi-quarkus-mandrel-builder-image
Digest: sha256:ea5288a0cf83d1d2a5a341f87849ce3a6f149147f37241ddf9bf538a824edc87
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
========================================================================================================================
GraalVM Native Image: Generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (11,9s @ 0,25GB)
 Version info: 'GraalVM 22.3.1.0-Final Java 17 Mandrel Distribution'
 Java version info: '17.0.6+10'
 C compiler: gcc (redhat, x86_64, 8.5.0)
 Garbage collector: Serial GC
 2 user-specific feature(s)
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
> Task :quarkusAppPartsBuild

[2/7] Performing analysis...  [******]                                                                  (74,6s @ 2,18GB)
  10.420 (88,46%) of 11.780 classes reachable
  14.851 (57,45%) of 25.852 fields reachable
  51.260 (55,20%) of 92.865 methods reachable
     528 classes,   111 fields, and 2.417 methods registered for reflection
      63 classes,    68 fields, and    55 methods registered for JNI access
       4 native libraries: dl, pthread, rt, z
[3/7] Building universe...                                                                               (9,9s @ 4,19GB)
[4/7] Parsing methods...      [***]                                                                      (7,3s @ 3,26GB)
[5/7] Inlining methods...     [***]                                                                      (3,9s @ 4,84GB)
[6/7] Compiling methods...    [********]                                                                (61,3s @ 5,18GB)
[7/7] Creating image...                                                                                  (6,5s @ 2,71GB)
  19,36MB (46,87%) for code area:    32.727 compilation units
  21,62MB (52,35%) for image heap:  270.759 objects and 8 resources
 329,23KB ( 0,78%) for other data
  41,30MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1,62MB sun.security.ssl                                     4,29MB byte[] for code metadata
 971,63KB java.util                                            2,45MB java.lang.Class
 733,91KB java.lang.invoke                                     2,45MB java.lang.String
 717,68KB com.sun.crypto.provider                              2,32MB byte[] for general heap data
 450,53KB sun.security.x509                                    1,96MB byte[] for java.lang.String
 447,26KB java.lang                                          895,47KB com.oracle.svm.core.hub.DynamicHubCompanion
 399,23KB io.netty.buffer                                    671,25KB java.util.HashMap$Node
 386,49KB java.io                                            545,41KB byte[] for reflection metadata
 381,35KB java.util.concurrent                               474,80KB java.lang.String[]
 342,33KB io.netty.handler.codec.http2                       390,82KB byte[] for embedded resources
  12,77MB for 387 more packages                                4,29MB for 2538 more object types
------------------------------------------------------------------------------------------------------------------------
                        5,3s (2,9% of total time) in 31 GCs | Peak RSS: 6,20GB | CPU load: 5,46
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /project/code-with-quarkus-1.0.0-SNAPSHOT-runner (executable)
 /project/code-with-quarkus-1.0.0-SNAPSHOT-runner-build-output-stats.json (json)
 /project/code-with-quarkus-1.0.0-SNAPSHOT-runner-timing-stats.json (raw)
 /project/code-with-quarkus-1.0.0-SNAPSHOT-runner.build_artifacts.txt (txt)
========================================================================================================================
Finished generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner' in 3m 2s.
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  43163560 ->  13773860   31.91%   linux/amd64   code-with-quarkus-1.0.0-SNAPSHOT-runner

Packed 1 file.

> Task :quarkusAppPartsBuild FAILED
9 actionable tasks: 9 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        	[error]: Build step io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromNativeImage threw an exception: java.lang.RuntimeException: Execution of 'docker build -f /tmp/gradle/code-with-quarkus/src/main/docker/Dockerfile.native -t jonathank/code-with-quarkus:1.0.0-SNAPSHOT /tmp/gradle/code-with-quarkus' failed. See docker output for more details
        	at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerException(DockerProcessor.java:347)
        	at io.quarkus.container.image.docker.deployment.DockerProcessor.createContainerImage(DockerProcessor.java:207)
        	at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerBuildFromNativeImage(DockerProcessor.java:155)
        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        	at java.base/java.lang.Thread.run(Thread.java:833)
        	at org.jboss.threads.JBossThread.run(JBossThread.java:501)


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 33s
13:35:42: Execution finished 'build'.
```
</details>

### How to Reproduce?

[demonstrate-build-error.zip](https://github.com/quarkusio/quarkus/files/11169774/demonstrate-build-error.zip)

### Output of `uname -a` or `ver`

5.19.0-38-generic

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 ------------------------------------------------------------ Gradle 8.0.1 ------------------------------------------------------------  Build time:   2023-02-17 20:09:48 UTC Revision:     68959bf76cef4d28c678f2e2085ee84e8647b77a  Kotlin:       1.8.10 Groovy:       3.0.13 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          11.0.18 (Ubuntu 11.0.18+10-post-Ubuntu-0ubuntu122.04) OS:           Linux 5.19.0-38-generic amd64

**Comment by geoand** [comment]
Can you please attach more details to the description, like the extensions you are using and all stacktrace you are seeing.

Thanks

**Comment by bulldog98** [comment]
@geoand I added the requested information, I hope I did not forget anything

**Comment by geoand** [comment]
Thanks

**Comment by geoand** [comment]
For some reason I am not able to debug the Quarkus Gradle plugin using `./gradlew build -Dorg.gradle.debug=true --no-daemon` and remote debug.

@aloubyansky @glefloch any ideas?

**Comment by snazy** [comment]
Hm - somewhat though.
With #31166 the actual Quarkus builds are executed in a separate Gradle worker _process_, do debugging is probably difficult there.

Tip: with IntelliJ it's usually not necessary to use the remote debugging, if you can modify the Gradle project source. Then update the `settings.gradle[.kts]` and add the `devtools/gradle` of the Quarkus source tree - the Quarkus plugin can then be edited directly in the Gradle project in question itself
```
includeBuild("/home/snazy/devel/quarkusio/quarkus/master/devtools/gradle")
```

I tried the build w/ the attached zip, and it fails for me as well.

First issue I ran into is that the image build couldn't find the `slirp4netns` executable. Looks like the environment's not properly passed to the Gradle worker processes. It would also be easier for debugging, when the Quarkus build steps are not run via worker processes. I'll open a PR to address both in a bit.

With `--info`, the Docker output's available as well, saying that a `COPY` step failed:
```
Error: building at STEP "COPY --chown=1001:root build/*-runner /work/application": checking on sources under "/home/snazy/Downloads/zz/code-with-quarkus": Rel: can't make  relative to /home/snazy/Downloads/zz/code-with-quarkus; copier: stat: ["/build/*-runner"]: no such file or directory
```

This error is related to #31166, because the "intermediate" build output from the Quarkus build steps is placed in `build/quarkus-build/gen`, not in `build/, by the `quarkusAppPartsBuild` task. It's then placed into `build/` by the (later executed) `quarkusBuild` task.

I could make the build from the attached zip work by updating the occurences of `build/` with `build/quarkus-build/gen/` in `.dockerignore` and similar in the `src/main/docker/Dockerfile.*` files.

**Comment by geoand** [comment]
> With https://github.com/quarkusio/quarkus/pull/31166 the actual Quarkus builds are executed in a separate Gradle worker process, do debugging is probably difficult there.

Ah, I was not aware of this, thanks.

> I could make the build from the attached zip work by updating the occurences of build/ with build/quarkus-build/gen/ in .dockerignore and similar in the src/main/docker/Dockerfile.* files.

wanna give it a shot?

**Comment by snazy** [comment]
However, it feels like the `build/quarkus-build/gen/` vs `build/` change is quite annoying for images. I'll take a deeper look into how we can prevent that users have to update their `Dockerfile`s. Thinking about something that's code-wise a bit ugly (aka: build in the "old" `build/` location and then move to the "new" ones, so that Gradle caching still works.

**Comment by geoand** [comment]
@snazy with https://github.com/quarkusio/quarkus/pull/32508 now in, can we close this?

**Comment by snazy** [comment]
Yes, this can be closed.
