### ISSUE TITLE
Quarkus 3.0.0.CR2: Jib fails to build container on Ubuntu

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#32477]
### Describe the bug

When I try to create a JVM container image with jib on ubuntu, it fails with the following error.

```
Container entrypoint set to [java, -Djava.util.logging.manager=org.jboss.logmanager.LogManager, -jar, quarkus-run.jar]
Created container image aeberle/code-with-quarkus:1.0.0-SNAPSHOT (sha256:76895e04c1c388a769576e2d1f46606a0b1427abff211f3e13d71035f23fb973)


> Task :quarkusAppPartsBuild
Quarkus augmentation completed in 53731ms
AugmentResult.nativeResult = null

> Task :quarkusAppPartsBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > java.lang.NullPointerException (no error message)



```

I attached a simple reproducer which is just a project created from code.quarkus.io with gradle, kotlin, reaseasy reactive and jib.

### How to Reproduce?

Reproducer: 
[2023-04-06-quarkus-3-jib-broken.zip](https://github.com/quarkusio/quarkus/files/11171545/2023-04-06-quarkus-3-jib-broken.zip)

1. Download & Unzip the reproducer on an Ubuntu (tested with WSL & Github actions)
2. Run `./gradlew clean assemble -D"quarkus.container-image.build=true"`
3. see the error in the console

### Output of `uname -a` or `ver`

5.15.90.1-microsoft-standard-WSL2  and github actions ubuntu runner

### Output of `java -version`

JDK17

### Quarkus version or git rev

3.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by geoand** [comment]
Please disregard my comment above, I can reproduce the problem locally.

**Comment by geoand** [comment]
@aloubyansky I am seeing:

```posh

Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
        at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:283)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.lambda$waitForItemsAndGatherFailures$2(DefaultAsyncWorkTracker.java:130)
        at org.gradle.internal.Factories$1.create(Factories.java:31)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:321)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:304)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLock(DefaultWorkerLeaseService.java:309)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:126)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:88)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForAll(DefaultAsyncWorkTracker.java:78)
        at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForCompletion(DefaultAsyncWorkTracker.java:72)
        at org.gradle.workers.internal.DefaultWorkerExecutor.await(DefaultWorkerExecutor.java:210)
        at org.gradle.workers.internal.DefaultWorkerExecutor.access$100(DefaultWorkerExecutor.java:58)
        at org.gradle.workers.internal.DefaultWorkerExecutor$DefaultWorkQueue.await(DefaultWorkerExecutor.java:308)
        at io.quarkus.gradle.tasks.QuarkusBuildTask.generateBuild(QuarkusBuildTask.java:170)
        at io.quarkus.gradle.tasks.QuarkusBuildCacheableAppParts.fastJarBuild(QuarkusBuildCacheableAppParts.java:122)
        at io.quarkus.gradle.tasks.QuarkusBuildCacheableAppParts.performQuarkusBuild(QuarkusBuildCacheableAppParts.java:81)
```

and later down the line:

```
Caused by: java.lang.NullPointerException
        at io.quarkus.gradle.tasks.worker.BuildWorker.execute(BuildWorker.java:62)
```

Do you have any idea what is going on?

**Comment by andreas-eberle** [comment]
I wanted to add the full log, but I think its easier if you debug anyways. Thanks for your support @geoand !

**Comment by andreas-eberle** [comment]
It looks like it still worked in Beta1 but stopped with CR1. Maybe that helps to narrow it down.

**Comment by iocanel** [comment]
I have hit this myself and I think its not limited to `jib` but it affects all container image builds. The weird part is that the build does complete succesfully yet the gradle build fails.

**Comment by geoand** [comment]
I guess it has somethign to do with Gradle refactoring. We also have https://github.com/quarkusio/quarkus/issues/32465 which I guess is similar to what you have seen @iocanel

**Comment by aloubyansky** [comment]
It should be fixed by https://github.com/quarkusio/quarkus/pull/32490
