### ISSUE TITLE
Numerous NPEs in Kafka during quarkus-integration-test-kafka

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#3249]
**Describe the bug**
The following NPE was observed during a full native build for Java 11:

```
2019-07-16 10:32:46 2019-07-16 10:32:46,460 ERROR [kaf.log.TimeIndex] (main) Error unmapping index /home/david/src/java/quarkus/integration-tests/kafka/target/data/kafka-data/kafka/broker1/streams-test-pipeline-countstore-changelog-0/0000
0000000000000000.timeindex: java.lang.NullPointerException
2019-07-16 10:32:46     at org.apache.kafka.common.utils.MappedByteBuffers.unmap(MappedByteBuffers.java:73)
2019-07-16 10:32:46     at kafka.log.AbstractIndex.forceUnmap(AbstractIndex.scala:321)
2019-07-16 10:32:46     at kafka.log.AbstractIndex.safeForceUnmap(AbstractIndex.scala:311)
2019-07-16 10:32:46     at kafka.log.AbstractIndex.$anonfun$closeHandler$1(AbstractIndex.scala:260)
2019-07-16 10:32:46     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
2019-07-16 10:32:46     at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
2019-07-16 10:32:46     at kafka.log.AbstractIndex.closeHandler(AbstractIndex.scala:260)
2019-07-16 10:32:46     at kafka.log.AbstractIndex.deleteIfExists(AbstractIndex.scala:229)
2019-07-16 10:32:46     at kafka.log.LogSegment.$anonfun$deleteIfExists$8(LogSegment.scala:599)
2019-07-16 10:32:46     at kafka.log.LogSegment.delete$1(LogSegment.scala:586)
2019-07-16 10:32:46     at kafka.log.LogSegment.$anonfun$deleteIfExists$7(LogSegment.scala:599)
2019-07-16 10:32:46     at kafka.utils.CoreUtils$.$anonfun$tryAll$1(CoreUtils.scala:115)
2019-07-16 10:32:46     at kafka.utils.CoreUtils$.$anonfun$tryAll$1$adapted(CoreUtils.scala:114)
2019-07-16 10:32:46     at scala.collection.immutable.List.foreach(List.scala:389)
2019-07-16 10:32:46     at kafka.utils.CoreUtils$.tryAll(CoreUtils.scala:114)
2019-07-16 10:32:46     at kafka.log.LogSegment.deleteIfExists(LogSegment.scala:600)
2019-07-16 10:32:46     at kafka.log.Log.$anonfun$delete$3(Log.scala:1798)
2019-07-16 10:32:46     at kafka.log.Log.$anonfun$delete$3$adapted(Log.scala:1798)
2019-07-16 10:32:46     at scala.collection.Iterator.foreach(Iterator.scala:929)
2019-07-16 10:32:46     at scala.collection.Iterator.foreach$(Iterator.scala:929)
2019-07-16 10:32:46     at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
2019-07-16 10:32:46     at scala.collection.IterableLike.foreach(IterableLike.scala:71)
2019-07-16 10:32:46     at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
2019-07-16 10:32:46     at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
2019-07-16 10:32:46     at kafka.log.Log.$anonfun$delete$2(Log.scala:1798)
2019-07-16 10:32:46     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
2019-07-16 10:32:46     at kafka.log.Log.maybeHandleIOException(Log.scala:2049)
2019-07-16 10:32:46     at kafka.log.Log.delete(Log.scala:1795)
2019-07-16 10:32:46     at java.base/java.lang.Iterable.forEach(Iterable.java:75)
2019-07-16 10:32:46     at io.debezium.kafka.KafkaServer.shutdown(KafkaServer.java:241)
2019-07-16 10:32:46     at io.debezium.kafka.KafkaCluster.shutdownReliably(KafkaCluster.java:393)
2019-07-16 10:32:46     at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4772)
2019-07-16 10:32:46     at io.debezium.kafka.KafkaCluster.shutdown(KafkaCluster.java:263)
2019-07-16 10:32:46     at io.quarkus.it.kafka.KafkaTestResource.stop(KafkaTestResource.java:37)
2019-07-16 10:32:46     at io.quarkus.test.common.TestResourceManager.stop(TestResourceManager.java:74)
2019-07-16 10:32:46     at io.quarkus.test.junit.QuarkusTestExtension$ExtensionState.close(QuarkusTestExtension.java:366)
2019-07-16 10:32:46     at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2019-07-16 10:32:46     at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:61)
2019-07-16 10:32:46     at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:73)
2019-07-16 10:32:46     at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
2019-07-16 10:32:46     at org.junit.jupiter.engine.descriptor.JupiterEngineDescriptor.cleanUp(JupiterEngineDescriptor.java:67)
2019-07-16 10:32:46     at org.junit.jupiter.engine.descriptor.JupiterEngineDescriptor.cleanUp(JupiterEngineDescriptor.java:29)
2019-07-16 10:32:46     at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$9(NodeTestTask.java:151)
2019-07-16 10:32:46     at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2019-07-16 10:32:46     at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:151)
2019-07-16 10:32:46     at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:83)
2019-07-16 10:32:46     at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2019-07-16 10:32:46     at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2019-07-16 10:32:46     at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2019-07-16 10:32:46     at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
2019-07-16 10:32:46     at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
2019-07-16 10:32:46     at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
2019-07-16 10:32:46     at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
2019-07-16 10:32:46     at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
2019-07-16 10:32:46     at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
2019-07-16 10:32:46     at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
2019-07-16 10:32:46     at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
2019-07-16 10:32:46     at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
```

This occurred numerous times during execution of `quarkus-integration-test-kafka`.

**Comment by gunnarmorling** [comment]
I reckon this is a manifestation of [KAFKA-8398](https://issues.apache.org/jira/browse/KAFKA-8398). I think we can simply ignore this, as this is not in Quarkus or the Kafka client code we use, but on the Kafka server side when shutting down the Kafka cluster started for tests.

**Comment by gsmet** [comment]
Closing as per Gunnar's comment.
