### ISSUE TITLE
Kubernetes client thread block

### ISSUE THREAD

**Issue by zZHorizonZz** [quarkusio/quarkus#32499]
### Describe the bug

I'm currently experimenting with kubernetes client and grapqhl. Basically what I'm trying to do is create a namespace, pod, deployment, or whatever you want based on request. But I'm experiencing an issue when I'm using Uni as a response for Graphql response. If I try the same code without Uni it works perfectly fine but the moment I put the method as async then it starts throwing this error (Error is thrown a couple of times):

```
 [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-7,5,main] has been blocked for 2384 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.6/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.6/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1866)
	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
	at java.base@17.0.6/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1939)
	at java.base@17.0.6/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:528)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:566)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:443)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:420)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handlePatch(BaseOperation.java:717)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:219)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation$$Lambda$813/0x000000080108f860.apply(Unknown Source)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:224)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:239)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:1136)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:93)
	at io.fabric8.kubernetes.client.extension.ResourceAdapter.serverSideApply(ResourceAdapter.java:325)
	at com.company.backplane.conductor.service.DeploymentServiceImpl.deployApplication(DeploymentServiceImpl.java:72)
	at com.company.backplane.conductor.service.DeploymentServiceImpl_ClientProxy.deployApplication(Unknown Source)
	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
	at io.smallrye.graphql.execution.datafetcher.helper.ReflectionInvoker.invoke(ReflectionInvoker.java:93)
	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusUniDataFetcher.handleUserMethodCallNonBlocking(QuarkusUniDataFetcher.java:44)
	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusUniDataFetcher.handleUserMethodCall(QuarkusUniDataFetcher.java:26)
	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.AbstractAsyncDataFetcher.invokeAndTransform(AbstractAsyncDataFetcher.java:38)
	at io.smallrye.graphql.execution.datafetcher.AbstractDataFetcher.get(AbstractDataFetcher.java:63)
	at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:86)
	at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation$$Lambda$1043/0x000000080121ba88.get(Unknown Source)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:282)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:211)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:183)
	at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:47)
	at graphql.execution.AsyncSerialExecutionStrategy$$Lambda$1029/0x0000000801211c48.apply(Unknown Source)
	at graphql.execution.Async.eachSequentiallyImpl(Async.java:191)
	at graphql.execution.Async.eachSequentially(Async.java:180)
	at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:42)
	at graphql.execution.Execution.executeOperation(Execution.java:159)
	at graphql.execution.Execution.execute(Execution.java:105)
	at graphql.GraphQL.execute(GraphQL.java:645)
	at graphql.GraphQL.lambda$parseValidateAndExecute$11(GraphQL.java:564)
	at graphql.GraphQL$$Lambda$1018/0x0000000801214fd0.apply(Unknown Source)
	at java.base@17.0.6/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base@17.0.6/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:559)
	at graphql.GraphQL.executeAsync(GraphQL.java:527)
	at io.smallrye.graphql.execution.ExecutionService.lambda$writeAsync$0(ExecutionService.java:209)
	at io.smallrye.graphql.execution.ExecutionService$$Lambda$979/0x0000000801202ac8.get(Unknown Source)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
	at io.smallrye.graphql.execution.ExecutionService.writeAsync(ExecutionService.java:211)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:191)
	at io.smallrye.graphql.execution.ExecutionService.executeAsync(ExecutionService.java:119)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:305)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:121)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:82)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handleWithIdentity(SmallRyeGraphQLAbstractHandler.java:95)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:76)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:30)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:358)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:335)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$$Lambda$946/0x00000008011ed8b0.handle(Unknown Source)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
	at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:581)
	at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:130)
	at io.vertx.core.http.impl.Http1xServerRequest$$Lambda$943/0x00000008011e8f28.handle(Unknown Source)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:239)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:129)
	at io.vertx.core.http.impl.Http1xServerRequest.handleEnd(Http1xServerRequest.java:562)
	at io.vertx.core.http.impl.Http1xServerConnection$$Lambda$948/0x00000008011edf20.handle(Unknown Source)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:76)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:153)
	at io.vertx.core.http.impl.Http1xServerConnection.onEnd(Http1xServerConnection.java:191)
	at io.vertx.core.http.impl.Http1xServerConnection.onContent(Http1xServerConnection.java:181)
	at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:161)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:149)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:157)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

Reproducer:

1. Create a new project
2. Create class DeploymentService for example
3. Insert this java code:
```java
@GraphQLApi
@Startup
@ApplicationScoped
public class DeploymentServiceImpl {

    private static final String NAMESPACE = "this-is-a-test";

    private final Logger logger = LoggerFactory.getLogger(DeploymentServiceImpl.class);

    @Inject
    KubernetesClient kubernetesClient;

    @PostConstruct
    public void postConstruct() {
        Uni.createFrom().item(1).onItem().delayIt().by(Duration.ofSeconds(5)).onItem().invoke(this::init).subscribe().with(
                item -> logger.info("Kubernetes client initialized"),
                throwable -> logger.error("Error while initializing kubernetes client", throwable)
        );
    }

    public void init() {
        logger.info("Kubernetes client: {}", kubernetesClient.hashCode());
        Namespace ns = new NamespaceBuilder().withNewMetadata().withName(NAMESPACE).addToLabels("this", "rocks").endMetadata()
                .build();
        logger.info("Created namespace: {}", kubernetesClient.resource(ns).serverSideApply());
        kubernetesClient.namespaces().withName(NAMESPACE).delete();
        logger.info("Done.");
    }

    @Mutation
    public Uni<DeploymentStatusResponse> deployApplication(@Id String applicationId) throws InterruptedException {
        logger.info("Kubernetes client: {}", kubernetesClient.hashCode());
        
        logger.info("Current thread: {}", Thread.currentThread().getName());
        logger.info("All threads: {}", Thread.getAllStackTraces().keySet());

        Namespace ns = new NamespaceBuilder().withNewMetadata().withName(NAMESPACE).addToLabels("this", "rocks").endMetadata()
                .build();

        kubernetesClient.resource(ns).serverSideApply();

        System.out.println("testNamespace = " + ns);
        return Uni.createFrom().item(new DeploymentStatusResponse());
    }
}
```

### Output of `java -version`

java version "17.0.5" 2022-10-18 LTS

### Quarkus version or git rev

3.0.0.Beta1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.0.2

**Comment by geoand** [comment]
Have you tried Quarkus 3.0.0.CR2

cc @manusa

**Comment by zZHorizonZz** [comment]
> Have you tried Quarkus 3.0.0.CR2

I have tried this but I'm getting the build time error probably related to Kubernetes as well. I'm trying to figure out If there is not something wrong on my side, but I'm out of ideas so I'm thinking about creating an issue for this as well.

```
A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        	[error]: Build step io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep#process threw an exception: java.lang.IllegalStateException: Unable to create folder at path 'C:\Windows\\vertx-cache'
        	at io.vertx.core.file.impl.FileCache.setupCacheDir(FileCache.java:61)
        	at io.vertx.core.file.impl.FileCache.setupCache(FileCache.java:31)
        	at io.vertx.core.file.impl.FileResolverImpl.<init>(FileResolverImpl.java:67)
        	at io.vertx.core.impl.VertxBuilder.initFileResolver(VertxBuilder.java:334)
        	at io.vertx.core.impl.VertxBuilder.init(VertxBuilder.java:274)
        	at io.vertx.core.Vertx.vertx(Vertx.java:87)
        	at io.quarkus.kubernetes.client.runtime.QuarkusHttpClientFactory.createVertxInstance(QuarkusHttpClientFactory.java:41)
        	at io.quarkus.kubernetes.client.runtime.QuarkusHttpClientFactory.<init>(QuarkusHttpClientFactory.java:27)
        	at io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep.process(KubernetesClientBuildStep.java:18)
        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
        	at java.base/java.lang.Thread.run(Thread.java:833)
        	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Caused by: java.nio.file.AccessDeniedException: C:\Windows\vertx-cache-99e79696-c3b0-421d-9b87-145756bae656
        	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:521)
        	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
        	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
        	at io.vertx.core.file.impl.FileCache.setupCacheDir(FileCache.java:53)
        	... 19 more
        
```

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/32502 should fix the issue you are seeing with CR2.

You can get around that problem for now by passing `-Dvertx.disableFileCaching=true -Dvertx.disableFileCPResolving=true` when building the application

**Comment by zZHorizonZz** [comment]
I tried the workaround you suggested but Gradle is not able to find disableFileCaching task.

**Comment by geoand** [comment]
You are likely not issuing the correct build command.

Try something like: `gradle build -Dvertx.disableFileCaching=true -Dvertx.disableFileCPResolving=true`

**Comment by zZHorizonZz** [comment]
> Try something like: `gradle build -Dvertx.disableFileCaching=true -Dvertx.disableFileCPResolving=true`

I'm looking at it but I'm pretty sure the command I sent here:

> ```
> gradle build -Dvertx.disableFileCaching=true -Dvertx.disableFileCPResolving=true
> ```

and yours are the same.

**Comment by iocanel** [comment]
@zZHorizonZz The commands do look identical, however the fact that gradle thinks that `disableFileCaching` is a task and not a system property makes me belive that what you tried and what you pasted here are not the same. 

Are you sure that you are not running: `gradle build -Dvertx. disableFileCaching=true` (with a space between the dot and disableFileCaching)`? A command like this could possible cause the error message you got.

**Comment by zZHorizonZz** [comment]
> @zZHorizonZz The commands do look identical, however the fact that gradle thinks that `disableFileCaching` is a task and not a system property makes me belive that what you tried and what you pasted here are not the same.
> 
> Are you sure that you are not running: `gradle build -Dvertx. disableFileCaching=true` (with a space between the dot and disableFileCaching)`? A command like this could possible cause the error message you got.

So I did some experimenting and came to the conclusion that I don't really know what's happening this is not problem of quarkus but gradle itself it seems I'm using installed gradle which is acting weird and doesn't probably parse the passed arguments properly, but if I use the script version ```gradlew``` then it doesn't throw the task error but throws already mentioned build [error](https://github.com/quarkusio/quarkus/issues/32499#issuecomment-1500829471), so I'm assuming the arguments are not passed at all. I have found some issues of people on other projects not just quarkus for example [this](https://community.sonarsource.com/t/projectkey-not-found-in-root-project/68025/6). I don't want to take your time so I will just wait until #32502 is released.

**Comment by geoand** [comment]
@zZHorizonZz have you tried using `3.0.0.Final`?

**Comment by zZHorizonZz** [comment]
> @zZHorizonZz have you tried using `3.0.0.Final`?

I have been trying but I probably don't seem to understand how quarkus release versioning works since when I change

```properties
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.0.0.Beta1 to 3.0.0.Final
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.0.0.Beta1 to 3.0.0.Final
```

But when I'm trying to build I'm getting an error that quarkus-bom for 3.0.0.Final doesn't exist, which after looking at [Sonatype releases](https://s01.oss.sonatype.org/content/repositories/releases/io/quarkus/platform/quarkus-bom/) doesn't seem like it will work any time soon (At least not until 26th which is planned official release from what I can understand?) since there is no 3.0.0.Final v. Also, I have tried using 999-SNAPSHOT but I was not able to make it work either.

**Comment by geoand** [comment]
For a few more days, ytou need to use `quarkusPlatformGroupId=io.quarkus` - once the full platform is released that will no longer be necessary

**Comment by zZHorizonZz** [comment]
> For a few more days, ytou need to use `quarkusPlatformGroupId=io.quarkus` - once the full platform is released that will no longer be necessary

Thanks for the tip. I have tried it on my test project and it seems like it's working. I'm getting some build errors not related to this so I'm not able to test it on the main project. Anyways thanks for the help. Since it seems like it's fixed closing the issue.

**Comment by geoand** [comment]
Great, thanks for checking
