### ISSUE TITLE
Quarkus build failed due to very long env var value

### ISSUE THREAD

**Issue by shakhar** [quarkusio/quarkus#32507]
### Describe the bug

We tried to upgrade our Quarkus version from 2.12.3.Final to 3.0.0.CR2 (in order to test the new upcoming major version).
When running our unit tests (that uses `@QuarkusTest` annotation), we got the following error:
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.ConfigGenerationBuildStep#runtimeDefaultsConfig threw an exception: java.lang.IllegalArgumentException: Cannot load strings larger than 65535 bytes
	at io.quarkus.gizmo.BytecodeCreatorImpl.load(BytecodeCreatorImpl.java:316)
	at io.quarkus.deployment.steps.ConfigGenerationBuildStep.generateDefaultsConfigSource(ConfigGenerationBuildStep.java:508)
	at io.quarkus.deployment.steps.ConfigGenerationBuildStep.runtimeDefaultsConfig(ConfigGenerationBuildStep.java:169)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

After debugging it a bit, we found that one of our environment variable's value is very long (longer than 65535) and [this](https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java#L530) line throws the above exception from [here](https://github.com/quarkusio/gizmo/blob/main/src/main/java/io/quarkus/gizmo/BytecodeCreatorImpl.java#L316).

### How to Reproduce?

Steps to reproduce:
1. Write a unit test class with `@QuarkusTest` annotation.
2. Run `./gradlew test` with an injected long env var (longer than 65535 bytes). 

### Output of `uname -a` or `ver`

Darwin ShakharArad 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13) OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### GraalVM version (if different from Java)

22.3.1

### Quarkus version or git rev

3.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.3.3 ------------------------------------------------------------  Build time:   2021-12-22 12:37:54 UTC Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.6 (GraalVM Community 17.0.6+10-jvmci-22.3-b13) OS:           Mac OS X 13.2.1 aarch64

**Comment by geoand** [comment]
Hi,

Is there a real world use case for having such a long environment variable?

**Comment by shakhar** [comment]
We saved in some of our env vars a json string. I know it is not the best practice to do so and there are many alternative, but in general I think that your infra shouldn't limit it. What was the reason for thia limitation? Maybe you can support configuring a larger limit?

**Comment by geoand** [comment]
The issue is that we record this information in the bytecode of the application and gigantic strings like that don't work

**Comment by geoand** [comment]
https://github.com/quarkusio/gizmo/pull/151 should take care of the issue

**Comment by Sanne** [comment]
Also wondering.. do we need to store all environment variables?

**Comment by shakhar** [comment]
Hey guys, this one is still an issue because you didn't bump gizmo's version yet, can you add it to your next fixes release?
