### ISSUE TITLE
Native build fails on RandomGeneratorFactory.getDefault().create()

### ISSUE THREAD

**Issue by mailq** [quarkusio/quarkus#32515]
### Describe the bug

Using any RandomGenerator (through the RandomGeneratorFactory) in a Quarkus native build results in an exception `java.lang.IllegalStateException: Random algorithm L32X64MixRandom is missing a default constructor`. Although the RandomGenerator implementations do have a default constructor.

Stacktrace:
````
java.lang.IllegalStateException: Random algorithm L32X64MixRandom is missing a default constructor
	at java.base@17.0.6/java.util.random.RandomGeneratorFactory.getConstructors(RandomGeneratorFactory.java:314)
	at java.base@17.0.6/java.util.random.RandomGeneratorFactory.ensureConstructors(RandomGeneratorFactory.java:333)
	at java.base@17.0.6/java.util.random.RandomGeneratorFactory.create(RandomGeneratorFactory.java:564)
	at java.base@17.0.6/java.util.random.RandomGeneratorFactory.create(RandomGeneratorFactory.java:587)
	at com.example.Tester.test(Tester.java:9)
	at com.example.Tester.run(Tester.java:15)
	at com.example.Tester_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:129)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at com.example.Main.main(Main.java:9)
````

### Expected behavior

It should just work as it does when not running as native image.

### Actual behavior

`java.lang.IllegalStateException: Random algorithm XXX is missing a default constructor` is thrown whereas XXX is variable depending on the algorithm requested by the RandomGeneratorFactory. 

### How to Reproduce?

Create an empty (Gradle) Quarkus project. Add two classes:
```java
@QuarkusMain
public class Main {
  public static void main(String[] args) {
    Quarkus.run(Tester.class, args);
  }
}
```

````java
@ApplicationScoped
public class Tester implements QuarkusApplication {
  public void test() {
    var generator = RandomGeneratorFactory.getDefault().create(4);
    generator.ints().limit(100).forEach(System.out::println);
  }

  @Override
  public int run(String... args) throws Exception {
    this.test();
    return 0;
  }
}
````
Verify that the code is working with `./gradlew quarkusDebug`.

Then create the native image `./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true`

When you run the produced native program it fails (not the build process itself).

### Output of `uname -a` or `ver`

Linux desktop 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17

### GraalVM version (if different from Java)

none; in Docker container

### Quarkus version or git rev

2.16.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.0.2

**Comment by mailq** [comment]
Also applies to Quarkus 3.0.0.CR2

**Comment by melloware** [comment]
Yep looks like this class needs to be registered for reflection.

**Comment by geoand** [comment]
You can add 

```java
@RegisterForReflection(targets=RandomGeneratorFactory.class)
```

on your `Main` class and things should just work.

I am wondering however if we should always register this class for reflection... @zakkak WDYT? Any idea why GraalVM doesn't do it on its own?

**Comment by melloware** [comment]
To me if this is a JDK class shouldn't GraalVM register it by default so users don't have to?

**Comment by sberyozkin** [comment]
My understanding is that GraalVM does not register other classes it does not consider to be critical/absolutely essential as well. I'm curious though to see what Foivos finds out. Maybe this class is indeed important enough to be always available in native mode

**Comment by geoand** [comment]
@zakkak and @galderz can shine some light on this

**Comment by mailq** [comment]
> You can add
> 
> ```java
> @RegisterForReflection(targets=RandomGeneratorFactory.class)
> ```
> 
> on your `Main` class and things should just work.
> 
_Should_ is the right word. It should, but it does not help.

I suppose that it is not the problem of the RandomGeneratorFactory to be registered, but the special implementations have to be registered. But I can not add L32X64MixRandom.class as the target for reflection as the Java compiler can't find the class (probably because it is defined in the jdk package).

I got it to work by creating a `reflection-config.json` for the `L32X64MixRandom.class` and then extend the `application.properties` as described in the documentation. But that is cumbersome and not quite obvious.

**Comment by melloware** [comment]
Can you do this

```java
@RegisterForReflection(targets="xxx.xxx.L32X64MixRandom")
```

Basically use the string variant and not the class variant?

**Comment by mailq** [comment]
Yes and no. It is
````java
@RegisterForReflection(classNames = "jdk.random.L32X64MixRandom")
````
and then it works

**Comment by melloware** [comment]
Nice I knew there was some way of using the String!

**Comment by galderz** [comment]
Looking at the [`L32X64MixRandom` source](https://github.com/openjdk/jdk/blob/master/src/jdk.random/share/classes/jdk/random/L32X64MixRandom.java), it looks like it might be a new class in Java 17? That could explain why the class is not registered in GraalVM. I'll open an issue there.

**Comment by galderz** [comment]
Created https://github.com/oracle/graal/issues/6456

**Comment by zakkak** [comment]
As pointed out by @sberyozkin "GraalVM does not register other classes it does not consider to be critical/absolutely essential". The more things we register for reflection the more bloated the native executable becomes so we need to be careful with what gets in by default. In this case (as commented in https://github.com/oracle/graal/issues/6456#issuecomment-1517933074) IMO the class should only get registered on demand when `java.util.random.RandomGeneratorFactory#getDefault()` or `java.util.random.RandomGenerator#getDefault()` is reachable. Note, however, that such a change could still be rejected upstream as that access is something the native-agent can easily detect and craft the corresponding jni-config.json file.

If you think this is important enough, this kind of conditional registration should be possible through Quarkus as well.

**Comment by gsmet** [comment]
This is a GraalVM upstream issue.

Still, I will add a note in https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/writing-native-applications-tips.adoc .
