### ISSUE TITLE
Rest Client cannot run with Hibernate Reactive Panache in same method

### ISSUE THREAD

**Issue by darkpastiurs** [quarkusio/quarkus#32660]
### Describe the bug

Hello, the purpose of this report is about a problem when executing an operation that implies executing a GET request with restclient to the public API of TVMAZE and create an entity object and persist it through a panache repository but this launches the exception org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException. I tried to add the annotations Blocking and NonBlocking on the method that executes them without success.

### Expected behavior

Get the information of a TV series and persist it in my database

### Actual behavior

Cannot complete request with restclient to API

```
2023-04-14 19:58:27,910 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /tvseries/fetch?title=stranger%20things failed, error id: 8e823158-13b9-4785-9686-19a694a5122a-1: org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException                    
        at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.unwrap(InvocationBuilderImpl.java:210)                                       
        at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:324)
        at sv.com.dkps.TvMazeSerieProxy$$QuarkusRestClientInterface.get(Unknown Source)
        at sv.com.dkps.TvMazeSerieProxy$$CDIWrapper.get(Unknown Source)
        at sv.com.dkps.TvMazeSerieProxy$$CDIWrapper_ClientProxy.get(Unknown Source)
        at sv.com.dkps.TvSeriesResource.fetchTvSerie(TvSeriesResource.java:36)
        at sv.com.dkps.TvSeriesResource_Subclass.fetchTvSerie$$superforward1(Unknown Source)
        at sv.com.dkps.TvSeriesResource_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.hibernate.reactive.panache.common.runtime.ReactiveTransactionalInterceptorBase.lambda$intercept$0(ReactiveTransactionalInterceptorBase.java:30)
        at org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.executeInTransaction(MutinySessionImpl.java:444)
        at org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.lambda$execute$0(MutinySessionImpl.java:434)
        at io.smallrye.mutiny.Uni.lambda$chain$0(Uni.java:549)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:384)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
        at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)


2023-04-14 19:58:27,928 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-1) Request failed: org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException
        at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.unwrap(InvocationBuilderImpl.java:210)
        at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:324)
        at sv.com.dkps.TvMazeSerieProxy$$QuarkusRestClientInterface.get(Unknown Source)
        at sv.com.dkps.TvMazeSerieProxy$$CDIWrapper.get(Unknown Source)
        at sv.com.dkps.TvMazeSerieProxy$$CDIWrapper_ClientProxy.get(Unknown Source)
        at sv.com.dkps.TvSeriesResource.fetchTvSerie(TvSeriesResource.java:36)
        at sv.com.dkps.TvSeriesResource_Subclass.fetchTvSerie$$superforward1(Unknown Source)
        at sv.com.dkps.TvSeriesResource_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.hibernate.reactive.panache.common.runtime.ReactiveTransactionalInterceptorBase.lambda$intercept$0(ReactiveTransactionalInterceptorBase.java:30)
        at org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.executeInTransaction(MutinySessionImpl.java:444)
        at org.hibernate.reactive.mutiny.impl.MutinySessionImpl$Transaction.lambda$execute$0(MutinySessionImpl.java:434)
        at io.smallrye.mutiny.Uni.lambda$chain$0(Uni.java:549)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:384)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
        at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

GitHub repo: [https://github.com/darkpastiurs/quarkus-microprofile-health.git](url)

### Output of `uname -a` or `ver`

Windows 11 Version 10.0.22621 compilación 22621

### Output of `java -version`

``` openjdk version "11.0.18" 2023-01-17 OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 11.0.18+10-jvmci-22.3-b13) OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 11.0.18+10-jvmci-22.3-b13, mixed mode, sharing)

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

2.16.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: C:\Users\darkpastiursSennin\.m2\wrapper\dists\apache-maven-3.8.6-bin\67568434\apache-maven-3.8.6 Java version: 11.0.18, vendor: GraalVM Community, runtime: C:\Java\graalvm-ce-java11-22.3.1 Default locale: es_ES, platform encoding: Cp1252 OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

### Additional information

It should be added that I am a rookie learning about Quarkus and reactive programming, therefore, it is a mistake that I have made due to ignorance I also ask to instruct myself in what I need or that I must correct. Thanks in advance.

**Comment by loicmathieu** [comment]
Hi,
Can you give us the code of your `TvSeriesResource` and your rest client ?
A reproducer project would be great.

**Comment by darkpastiurs** [comment]
> Hi,
> Can you give us the code of your `TvSeriesResource` and your rest client ?
> A reproducer project would be great.

Sure, here is the link to the github project  [to_reproduce](https://github.com/darkpastiurs/quarkus-microprofile-health.git)

**Comment by loicmathieu** [comment]
The issue is that you have a reactive endpoint with a reactive transaction that do a blocking call via its rest client.
So you need to make your `TvMazeSerieProxy.get()  method to return a `Uni<TvSerie>>`.

**Comment by geoand** [comment]
Closing as per @loicmathieu's comment
