### ISSUE TITLE
Hit Error on JAX-RS call: java.lang.NoSuchMethodError: io.quarkus.runner.RuntimeRunner$Builder.setBuildSystemProperties(Ljava/util/Properties;)Lio/quarkus/runner/RuntimeRunner$Builder

### ISSUE THREAD

**Issue by wargun02** [quarkusio/quarkus#3266]
My app runs fine with version 0.17.0 and 0.18.0. However when switching to version 0.19.0 or 0.19.1, it **DID NOT** show console log like the below after "Listening for transport dt_socket at address: 5005":
```
2019-07-18 11:57:02,231 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-07-18 11:57:03,649 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1418ms
2019-07-18 11:57:06,948 INFO  [io.quarkus] (main) Quarkus 0.17.0 started in 4.948s. Listening on: http://[::]:8080
2019-07-18 11:57:06,950 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-validator, jdbc-mariadb, narayana-jta, resteasy, resteasy-jsonb, smallrye-rest-client, vertx]
```

and when ever a JAX-RS endpoint is invoked, the return response message is
```
Error restarting Quarkus

java.lang.NoSuchMethodError: io.quarkus.runner.RuntimeRunner$Builder.setBuildSystemProperties(Ljava/util/Properties;)Lio/quarkus/runner/RuntimeRunner$Builder;
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:167)
	at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:198)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:108)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup.handleHotDeploymentRequest(UndertowHotReplacementSetup.java:67)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup$1$1.handleRequest(UndertowHotReplacementSetup.java:56)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:32)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

If needed, please provide me some pointers as of how to diagnose and reproduce this. Thank you.

#### Quarkus was running on:
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-macosx) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-macosx) (build 25.212-b04, mixed mode)

**Comment by stuartwdouglas** [comment]
Did you update the quarkus maven plugin to the same version as the other quarkus dependencies?

**Comment by wargun02** [comment]
A portion of my pom.xml is somewhat like:

```
<properties>
  <quarkus.version>0.19.1</quarkus.version>
</properties>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-bom</artifactId>
            <version>${quarkus.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
  </dependency>
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jsonb</artifactId>
  </dependency>
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-rest-client</artifactId>
  </dependency>
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-agroal</artifactId>
  </dependency>
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-narayana-jta</artifactId>
  </dependency>
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-orm</artifactId>
  </dependency>
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-validator</artifactId>
  </dependency>
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-orm-panache</artifactId>
  </dependency>
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-mariadb</artifactId>
  </dependency>
  <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-vertx</artifactId>
  </dependency>

  <!-- And the rest of the others... -->
</dependencies>
```

**Comment by stuartwdouglas** [comment]
What about the <build> section where the quarkus-maven-plugin is defined?

**Comment by wargun02** [comment]
Here it is...

```
<build>
    <plugins>
        <plugin>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-maven-plugin</artifactId>
            <version>${quarkus.version}</version>
            <executions>
                <execution>
                    <goals>
                        <goal>build</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>${surefire-plugin.version}</version>
            <configuration>
                <systemProperties>
                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                </systemProperties>
            </configuration>
        </plugin>
    </plugins>
</build>
```

**Comment by stuartwdouglas** [comment]
What is the output of mvn dependency:tree ? It looks like the wrong version is being pulled in somehow, but I don't really see how as the bom should override it.

**Comment by wargun02** [comment]
The command I use:
```
mvn dependency:tree -Dincludes=io.quarkus
```

The output:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< my.cloudlegato:CloudLegato-REST-Service >---------------
[INFO] Building CloudLegato-REST-Service 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ CloudLegato-REST-Service ---
[INFO] my.cloudlegato:CloudLegato-REST-Service:jar:1.0-SNAPSHOT
[INFO] +- io.quarkus:quarkus-resteasy:jar:0.19.1:compile
[INFO] |  +- io.quarkus:quarkus-undertow:jar:0.19.1:compile
[INFO] |  \- io.quarkus:quarkus-resteasy-server-common:jar:0.19.1:compile
[INFO] |     \- io.quarkus:quarkus-jaxb:jar:0.19.1:compile
[INFO] +- io.quarkus:quarkus-resteasy-jsonb:jar:0.19.1:compile
[INFO] |  \- io.quarkus:quarkus-jsonb:jar:0.19.1:compile
[INFO] |     \- io.quarkus:quarkus-jsonp:jar:0.19.1:compile
[INFO] +- io.quarkus:quarkus-smallrye-rest-client:jar:0.19.1:compile
[INFO] |  +- io.quarkus:quarkus-core:jar:0.19.1:compile
[INFO] |  +- io.quarkus:quarkus-arc:jar:0.19.1:compile
[INFO] |  \- io.quarkus:quarkus-resteasy-common:jar:0.19.1:compile
[INFO] +- io.quarkus:quarkus-agroal:jar:0.19.1:compile
[INFO] +- io.quarkus:quarkus-narayana-jta:jar:0.19.1:compile
[INFO] +- io.quarkus:quarkus-hibernate-orm:jar:0.19.1:compile
[INFO] |  \- io.quarkus:quarkus-caffeine:jar:0.19.1:compile
[INFO] +- io.quarkus:quarkus-hibernate-validator:jar:0.19.1:compile
[INFO] +- io.quarkus:quarkus-hibernate-orm-panache:jar:0.19.1:compile
[INFO] |  \- io.quarkus:quarkus-panache-common:jar:0.19.1:compile
[INFO] +- io.quarkus:quarkus-jdbc-mariadb:jar:0.19.1:compile
[INFO] +- io.quarkus:quarkus-vertx:jar:0.19.1:compile
[INFO] |  \- io.quarkus:quarkus-netty:jar:0.19.1:compile
[INFO] +- io.quarkus:quarkus-junit5:jar:0.19.1:test
[INFO] |  \- io.quarkus:quarkus-bootstrap-core:jar:0.19.1:test
[INFO] \- io.quarkus:quarkus-test-common:jar:0.17.0:compile
[INFO]    +- io.quarkus:quarkus-core-deployment:jar:0.17.0:compile
[INFO]    |  \- io.quarkus:quarkus-builder:jar:0.17.0:compile
[INFO]    \- io.quarkus:quarkus-jsonp-deployment:jar:0.17.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.250 s
[INFO] Finished at: 2019-07-20T10:40:07+08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by wargun02** [comment]
My bad my bad...I realised that there is one version tag which is miss-aligned...after fixing the version number of quarkus-test-common. I'm fine now...
```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-test-common</artifactId>
    <version>${quarkus.version}</version>
    <scope>compile</scope>
</dependency>
```

Sorry to take up your time. Thanks for the effort. Closing this issue now.
