### ISSUE TITLE
'Server response is: 401' occurs during test when @RegisterProvider(AccessTokenRequestReactiveFilter.class) is used

### ISSUE THREAD

**Issue by andychoi-ibm** [quarkusio/quarkus#32782]
### Describe the bug

The issue occurs when @RegisterProvider(AccessTokenRequestReactiveFilter.class) is used but doesn't occur when @AccessToken is used.

### Expected behavior

'Server response is: 401' doesn't occur during test when OIDC is disabled.

### Actual behavior

'Server response is: 401' occurs during test when OIDC is disabled.

### How to Reproduce?

1. Clone https://github.com/quarkusio/quarkus-quickstarts/tree/main/rest-client-reactive-quickstart.

2. Add the following dependency to pom.xml

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-oidc-token-propagation-reactive</artifactId>
    </dependency>
```

3. Add the following properties to application.properties.

```
%test.quarkus.oidc.enabled=false
%test.quarkus.oidc-token-propagation-reactive.enabled=false
```

4. Add `@RegisterProvider(AccessTokenRequestReactiveFilter.class)` to ExtentionService.java.

5. run `mvn test`.

### Output of `uname -a` or `ver`

Linux li-eae487cc-21ca-11b2-a85c-b04e05111fa6.ibm.com 4.18.0-425.13.1.el8_7.x86_64 #1 SMP Thu Feb 2 13:01:45 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.5" 2022-10-18 IBM Semeru Runtime Certified Edition 17.0.5.0 (build 17.0.5+8) Eclipse OpenJ9 VM 17.0.5.0 (build openj9-0.35.0, JRE 17 Linux amd64-64-Bit Compressed References 20221018_272 (JIT enabled, AOT enabled)

### Quarkus version or git rev

2.16.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)

### Additional information

The issue doesn't occur when `@AccessToken` is used but AccessToken is not available in the latest Red Hat build of Quarkus, 2.13.

**Comment by geoand** [comment]
You need to use `@RegisterProvider(AccessTokenRequestReactiveFilter.class)` instead of `@RegisterProvider(AccessTokenRequestReactiveFilter.class)` when using the Reactive REST Client

**Comment by geoand** [comment]
I was not able to reproduce this, can you attach a sample application please that exhibits this problem?

**Comment by sberyozkin** [comment]
@andychoi-ibm , '@AccessToken' annotation is a shortcut fior registering the reactive token propagation filter directly, in both cases, this filter will expect an injected, already verified token

**Comment by sberyozkin** [comment]
See the oidc client quickstart how to test, you can depend on DevServices for Keycloak or wiremock and use jwt build api to generate test tokens

**Comment by andychoi-ibm** [comment]
> I was not able to reproduce this, can you attach a sample application please that exhibits this problem?

I'm using https://github.com/quarkusio/quarkus-quickstarts/tree/main/rest-client-reactive-quickstart. Did you follow the steps to reproduce the behavior? I just updated to the latest main branch and reproduce the issue.

```
[ERROR] org.acme.rest.client.ExtensionsResourceTest.testExtensionsIdEndpoint  Time elapsed: 0.012 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.

        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:499)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
        at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:684)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:127)
        at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
        at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
        at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
        at io.restassured.internal.ValidatableResponseImpl.super$2$statusCode(ValidatableResponseImpl.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
        at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy:142)
        at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
        at org.acme.rest.client.ExtensionsResourceTest.testExtensionsIdEndpoint(ExtensionsResourceTest.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1002)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:816)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
        Suppressed: org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Unauthorized, status code 401' when invoking: Rest Client method: 'org.acme.rest.client.ExtensionsService#getById'
                at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.unwrapException(RestClientRequestContext.java:181)
                at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.handleException(AbstractResteasyReactiveContext.java:322)
                at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:173)
                at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.performRequestInternal(AsyncInvokerImpl.java:285)
                at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.performRequestInternal(AsyncInvokerImpl.java:275)
                at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.method(AsyncInvokerImpl.java:220)
                at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:329)
                at org.acme.rest.client.ExtensionsService$$QuarkusRestClientInterface.getById(Unknown Source)
                at org.acme.rest.client.ExtensionsService$$CDIWrapper.getById(Unknown Source)
                at org.acme.rest.client.ExtensionsService$$CDIWrapper_ClientProxy.getById(Unknown Source)
                at org.acme.rest.client.ExtensionsResource.id(ExtensionsResource.java:23)
                at org.acme.rest.client.ExtensionsResource$quarkusrestinvoker$id_3fe3d84a9169f4b84577974c562e674cd1b00c46.invoke(Unknown Source)
                at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
                at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
                at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
                at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
                at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
                at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:857)
        Caused by: javax.ws.rs.WebApplicationException: Unauthorized, status code 401
                at io.quarkus.rest.client.reactive.runtime.DefaultMicroprofileRestClientExceptionMapper.toThrowable(DefaultMicroprofileRestClientExceptionMapper.java:18)
                at io.quarkus.rest.client.reactive.runtime.MicroProfileRestClientResponseFilter.filter(MicroProfileRestClientResponseFilter.java:41)
                at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:21)
                at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:10)
                at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:229)
                at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
                ... 19 more
        [CIRCULAR REFERENCE:org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Unauthorized, status code 401' when invoking: Rest Client method: 'org.acme.rest.client.ExtensionsService#getById']

2023-04-20 09:16:10,155 INFO  [io.quarkus] (main) rest-client-reactive-quickstart stopped in 0.017s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ExtensionsResourceTest.testExtensionIdAsyncEndpoint:36 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   ExtensionsResourceTest.testExtensionIdMutinyEndpoint:49 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   ExtensionsResourceTest.testExtensionsIdEndpoint:23 1 expectation failed.
Expected status code <200> but was <500>.

[INFO] 
[ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.522 s
[INFO] Finished at: 2023-04-20T09:16:10-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project rest-client-reactive-quickstart: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/andychoi/code/quarkus-quickstarts/rest-client-reactive-quickstart/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
```

**Comment by geoand** [comment]
> @geoand I'm using https://github.com/quarkusio/quarkus-quickstarts/tree/main/rest-client-reactive-quickstart. Did you follow the steps to reproduce the behavior? I just updated to the latest main branch and reproduce the issue.

Yes, that's why I am asking for a sample project and not instructions

**Comment by andychoi-ibm** [comment]
> See the oidc client quickstart how to test, you can depend on DevServices for Keycloak or wiremock and use jwt build api to generate test tokens

@sberyozkin I'm trying to disable/bypass OIDC during test so I can just verify the business logic only. I don't need to test and verify OIDC.

**Comment by andychoi-ibm** [comment]
> > @geoand I'm using https://github.com/quarkusio/quarkus-quickstarts/tree/main/rest-client-reactive-quickstart. Did you follow the steps to reproduce the behavior? I just updated to the latest main branch and reproduce the issue.
> 
> Yes, that's why I am asking for a sample project and not instructions

@geoand The issue doesn't occur when I run the application. It only occurs when I run the JUnit test.

**Comment by andychoi-ibm** [comment]
I'm not making any changes to https://github.com/quarkusio/quarkus-quickstarts/tree/main/rest-client-reactive-quickstart other than the changes I described in the steps to reproduce the behavior.

**Comment by andychoi-ibm** [comment]
@geoand @sberyozkin ExtensionsResourceTest passes if I add `@AccessToken` instead of `@RegisterProvider(AccessTokenRequestReactiveFilter.class)` to ExtensionsResource but AccessToken is not available in the latest Red Hat build of Quarkus, 2.13.

**Comment by sberyozkin** [comment]
>@sberyozkin I'm trying to disable/bypass OIDC (step 3) during test so I can just verify the business logic only. I don't need to test and verify OIDC.

But the filter is active, it expects a token. I think the issue is invalid. It is a problem of a test set up not a bug as this issue is marked. 
You have 2 options:
- do not disable OIDC, use Dev Services for Keycloak, or wiremock as shown in the docs/other demos. IMHO it is the right approach
- If you need to keep the token propagation filter - instead of registering the one shipped by Quarkus, register a custom one extending that filter instead - and there check the OIDC status and skip the propagation if needed

Note the token propagation will also work with smallrye-jwt, or probably even with the amazon lamda extension which supports JSON Web Token API, the default filter can't be checking all the statuses of all the extensions which might produce the tokens

**Comment by geoand** [comment]
@sberyozkin if the issue is invalid, please close it.

Thanks

**Comment by sberyozkin** [comment]
Hey @geoand Sure, I was just wondering about 

>ExtensionsResourceTest passes if I add @AccessToken instead of @RegisterProvider(AccessTokenRequestReactiveFilter.class)

If I read it correctly, if `@AccessToken` is used then the filter is not auto-registered, since if it were registered then it would fail the same way as with the explicit registration. 

Oh I see, in the description, the reactive feature is disabled which is why `@AccessToken` is not registered at the build step time, while with the explicit class registration it is static.

Right, so @andychoi-ibm, sorry but I have to close this issue, check 2 options proposed above, if you need help with getting your set up tested then ping us in Discussions/Zulip, thanks

**Comment by andychoi-ibm** [comment]
@sberyozkin Thanks for the explanation so it seems the issue is that AccessTokenRequestReactiveFilter doesn't honor `%test.quarkus.oidc-token-propagation-reactive.enabled=false` whereas AccessToken does. Does it sound right? Ideally, the property should be honored by the filter also and we shouldn't need to add a custom filter just so we can run JUnit tests without OIDC.

**Comment by sberyozkin** [comment]
@andychoi-ibm Np, The filter is what the extension provides, the extension specific classes like this filter (but not only in the OIDC propagation reactive filter) can't each of them check these build time properties in its constructors, runtime methods like `filter` or whatever else the given extension class does. The purpose of this build time property is to avoid doing the initialization work at the application build time, not for the extension classes do `if (enabled)` checks everywhere in their runtime code. Providing a simple custom filter for now is not totally perfect but is an easy solution, and once you upgrade you can depend on `@AccessToken`
