### ISSUE TITLE
ClassCastException when sending a object in messaging with SmallRye and RabbitMQ

### ISSUE THREAD

**Issue by julianomqs** [quarkusio/quarkus#32811]
### Describe the bug

When sending a simple object from an `Outgoing` producer to an `Incoming` consumer, a `ClassCastException` occurs:

```java
2023-04-20 19:11:52,456 WARN  [io.sma.rea.mes.rabbitmq] (vert.x-eventloop-thread-0) SRMSG17013: A message sent to channel `consume-in` has been nacked, ignoring the failure and marking the RabbitMQ message as rejected
2023-04-20 19:11:52,456 ERROR [io.sma.rea.mes.provider] (vert.x-eventloop-thread-0) SRMSG00200: The method org.example.Consumer#consume has thrown an exception: java.lang.ClassCastException: class io.vertx.core.json.JsonObject cannot be cast to class org.example.Product (io.vertx.core.json.JsonObject is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @54d9d12d; org.example.Product is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @ea9e141)
	at org.example.Consumer_SmallRyeMessagingInvoker_consume_cdc25663535141a6c287538499060aea6010d99a.invoke(Unknown Source)
	at io.smallrye.reactive.messaging.providers.AbstractMediator.invoke(AbstractMediator.java:104)
	at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeOnMessageContext$1(AbstractMediator.java:112)
	at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$0(LocalContextMetadata.java:34)
	at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$1(LocalContextMetadata.java:53)
	at io.smallrye.reactive.messaging.providers.helpers.VertxContext.runOnContext(VertxContext.java:24)
	at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$2(LocalContextMetadata.java:51)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.request(UniToMultiPublisher.java:74)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onSubscribe(MultiFlatMapOp.java:601)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher.subscribe(UniToMultiPublisher.java:26)
	at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:170)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:193)
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:100)
	at io.smallrye.reactive.messaging.providers.locals.ContextOperator$ContextMulti$ContextProcessor.lambda$onItem$1(ContextOperator.java:71)
	at io.smallrye.reactive.messaging.providers.helpers.VertxContext.lambda$runOnContext$0(VertxContext.java:26)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

Serialize the object to JSON properly.

### Actual behavior

A ClassCastException occurs when sending the message.

### How to Reproduce?

https://github.com/julianomqs/quarkus-smallrye-rabbitmq-bug

### Output of `uname -a` or `ver`

Linux juliano 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17

### Quarkus version or git rev

2.16.6.Final

**Comment by geoand** [comment]
cc @ozangunalp @cescoffier

**Comment by ozangunalp** [comment]
The rabbitmq connector doesn't handle object mapping deserialization. A bean sent to the broker is serialized to Json automatically and the `content_type` is set to `application/json`. When that message is received, looking at its `content_type` it is deserialized as `io.vertx.core.json.JsonObject`. You read how to do the object mapping in https://quarkus.io/guides/rabbitmq-reference#deserialization
