### ISSUE TITLE
Quarkus app fails to build/start in jvm mode with hadoop dependencies and resteasy dependencies

### ISSUE THREAD

**Issue by qpointz** [quarkusio/quarkus#32818]
### Describe the bug

When application has hadoop and resteasy dependencies quarkus fails to build (gradle quarkusBuild) or run (gradle quarkusDev) 

Steps to reproduce 
1. create quarkus app quarkus create app --java=17 --gradle-kotlin-dsl 
2. add hadoop dependency to build.gradle.kts , minimal runtimeOnly("org.apache.hadoop:hadoop-common:3.3.5")
3. run quarkus dev 

### Expected behavior

Application successfully builds and/or runs

### Actual behavior

build and or run fails with message 

io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupDeployment threw an exception: java.lang.IllegalStateException: java.lang.NoSuchMethodException: javax.ws.rs.core.MediaType.<init>(java.lang.String,java.lang.String,java.lang.String)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.lang.NoSuchMethodException: javax.ws.rs.core.MediaType.<init>(java.lang.String,java.lang.String,java.lang.String)
        at java.base/java.lang.Class.getConstructor0(Class.java:3585)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
        at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupDeployment(ResteasyReactiveProcessor.java:1106)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        ... 6 more

removing hadoop or reasteasy dependency solves an issue 

### Output of `uname -a` or `ver`

Linux pc-lnx 5.15.0-70-generic #77-Ubuntu SMP Tue Mar 21 14:02:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### Quarkus version or git rev

2.16.6.FInal

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.0.2 ------------------------------------------------------------  Build time:   2023-03-03 16:41:37 UTC Revision:     7d6581558e226a580d91d399f7dfb9e3095c2b1d  Kotlin:       1.8.10 Groovy:       3.0.13 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.5 (GraalVM Community 17.0.5+8-jvmci-22.3-b08) OS:           Linux 5.15.0-70-generic amd64

**Comment by geoand** [comment]
This is caused because JAX-RS 1.1 is being used. 

@aloubyansky @glefloch how come that is happening even though we are using `enforcedPlatform`?

**Comment by geoand** [comment]
I should add that the equivalent Maven project works just fine

**Comment by qpointz** [comment]
> 

Equivalent maven was failing same way for me 

Same reproduce steps + hadoop dependency in pom.xml

 <dependency>
      <groupId>org.apache.hadoop</groupId>
       <artifactId>hadoop-common</artifactId>
       <version>3.3.5</version>
    </dependency>

**Comment by aloubyansky** [comment]
@qpointz you need to configure an exclusion for `javax.ws.rs:jsr111-api` that is brought in by the hadoop dependency.

**Comment by qpointz** [comment]
> @qpointz you need to configure an exclusion for `javax.ws.rs:jsr111-api` that is brought in by the hadoop dependency.

exclusion did the trick 

@aloubyansky @geoand  thank you very much for your assistance. 
should I close the issue ?

**Comment by aloubyansky** [comment]
Yes, please. Thanks.

**Comment by qpointz** [comment]
issue close
