### ISSUE TITLE
CNFE exception when running custom configsource in jar mode

### ISSUE THREAD

**Issue by firdy94** [quarkusio/quarkus#32853]
Hi, i wrote a custom configsource that is reading from etcd server to load some application properties.

While running in dev mode, i am able to pull all the data properly without any issue. 
However when i compile it into fast-jar and execute the java -jar on the file i get the following error :

```posh
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.config
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Apr 24, 2023 5:08:29 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile [prod])
java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:115)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
        at io.smallrye.config.ConfigMappingInterface.getClassBytes(ConfigMappingInterface.java:176)
        at io.smallrye.config.ConfigMappingLoader.loadClass(ConfigMappingLoader.java:109)
        at io.smallrye.config.ConfigMappingLoader.getImplementationClass(ConfigMappingLoader.java:90)
        at io.smallrye.config.ConfigMappingLoader$1.computeValue(ConfigMappingLoader.java:22)
        at io.smallrye.config.ConfigMappingLoader$1.computeValue(ConfigMappingLoader.java:19)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at io.smallrye.config.ConfigMappingLoader.configMappingObject(ConfigMappingLoader.java:63)
        at io.smallrye.config.ConfigMappingContext.constructGroup(ConfigMappingContext.java:82)
        at io.smallrye.config.ConfigMappingContext.constructRoot(ConfigMappingContext.java:78)
        at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:955)
        at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:937)
        at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:29)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:937)
        at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:91)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:526)
        at io.smallrye.config.ConfigSourceFactory$ConfigurableConfigSourceFactory.getConfigSources(ConfigSourceFactory.java:48)
        at io.smallrye.config.ConfigurableConfigSource.getConfigSources(ConfigurableConfigSource.java:50)
        at io.smallrye.config.SmallRyeConfig$ConfigSources.mapLateSources(SmallRyeConfig.java:669)
        at io.smallrye.config.SmallRyeConfig$ConfigSources.<init>(SmallRyeConfig.java:553)
        at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:69)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:525)
        at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
        at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

Any idea how can i fix this ? i tried searching thru the code but cannot figure out why. 
i tried this following the solution in this ticket but did not work either still getting the same error : https://github.com/quarkusio/quarkus/issues/18303

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
Can you please provide us with a reproducer? Thank you!

**Comment by firdy94** [comment]
sure will try to give a reproducer for this. Thanks!

**Comment by richard-123456** [comment]
[ConfigReproducer.zip](https://github.com/quarkusio/quarkus/files/11342789/ConfigReproducer.zip)

Hi, i have attached the reproducer in this post. 
The gradle in the reproducer is set to java 11 due to some restriction i have while creating this code. In our actual code we are using jdk 17.

To test the code , do the following : 
1) Gradle Build CustomApp Project
2) Run the jar file , error will appear  (does not appear when running in quarkusDev mode)

**Comment by radcortez** [comment]
Thanks. I'll have a look.

**Comment by radcortez** [comment]
Ah, the issue is that the mapping is an external library, which we don't scan by default, so it is not added, and you get the error. I can probably improve this by providing a more accurate message.

To fix the issue, please check https://quarkus.io/guides/cdi-reference#bean_discovery

Just add:

```

**Comment by radcortez** [comment]
> Did not help. Any other suggestions how this can be fixed?

Can you provide a reproducer?

**Comment by gkozyryatskyy** [comment]
@radcortez for now I fixed it, by removed 'inner interfaces' in @ConfigMapping, adding them seems causing the problem. Mb in some time I will provide a reproducer, but it will take some time 'extract' it from my project.

Thant you for your reply!
