### ISSUE TITLE
RESTEasy Reactive streaming resource methods leads to NoSuchMethodException in native mode

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#32886]
### Describe the bug

https://github.com/quarkusio/quarkus/pull/32815 changed `Serialisers.NO_ANNOTATION` to `context.getAllAnnotations()` so now all streamed methods needs to be registered for reflection (or change impl.)

### Expected behavior

I can call RESTEasy Reactive endpoint that returns `Multi` (meaning these that are not already registered for reflection)

### Actual behavior

```
18:06:12,577 INFO  [app] 18:06:11,467 HTTP Request to /execution-model/reactive/multi failed, error id: 1b9f1864-4704-4c37-8e39-d849f3e1c17d-1: java.lang.RuntimeException: java.lang.NoSuchMethodException: io.quarkus.ts.http.jakartarest.reactive.ExecutionModelResource.reactiveMulti()
18:06:12,577 INFO  [app] 	at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getMethod(ResteasyReactiveResourceInfo.java:72)
18:06:12,577 INFO  [app] 	at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getAnnotations(ResteasyReactiveResourceInfo.java:89)
18:06:12,577 INFO  [app] 	at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.getMethodAnnotations(ResteasyReactiveRequestContext.java:553)
18:06:12,578 INFO  [app] 	at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.getAllAnnotations(ResteasyReactiveRequestContext.java:531)
18:06:12,578 INFO  [app] 	at org.jboss.resteasy.reactive.server.core.StreamingUtil.serialiseEntity(StreamingUtil.java:66)
18:06:12,579 INFO  [app] 	at org.jboss.resteasy.reactive.server.core.StreamingUtil.send(StreamingUtil.java:36)
18:06:12,579 INFO  [app] 	at org.jboss.resteasy.reactive.server.handlers.PublisherResponseHandler$StreamingMultiSubscriber.onNext(PublisherResponseHandler.java:124)
18:06:12,579 INFO  [app] 	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:30)
```

### How to Reproduce?

Reproducer:

1. `git clone git@github.com:quarkus-qe/quarkus-test-suite.git`
2. `cd quarkus-test-suite`
3. `git checkout -b repro/rr-injection`
4. `cd http/jakarta-rest-reactive`
5. `mvn clean verify -Dnative -Dit.test=ExecutionModelIT`

### Output of `uname -a` or `ver`

Fedora

### Output of `java -version`

openjdk 11.0.18 2023-01-17

### GraalVM version (if different from Java)

22.3

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

MVN 3.8.6

**Comment by michalvavrik** [comment]
btw original PR got backported to 3.0.1.Final
