### ISSUE TITLE
Two beans resolve JAX-RS @Context

### ISSUE THREAD

**Issue by jbonofre** [quarkusio/quarkus#32921]
### Describe the bug

I have a pretty simple JAX-RS resource class:

```java
@Path("/")
public class RestService {

    private static Logger logger = LoggerFactory.getLogger(RestService.class);

    @Context
    UriInfo uriInfo;

    @GET
    @Path("/hello")
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        logger.info("hello");
        return "hello";
    }

    @GET
    @Path("/chain")
    @Produces(MediaType.TEXT_PLAIN)
    public String chain() {
        RestClient restClient = RestClientBuilder.newBuilder()
                .baseUri(uriInfo.getBaseUri())
                .build(RestClient.class);
        return ("chain -> " + restClient.hello());
    }

}
```

When I try to build, arc is complaining:

```posh
[ERROR]         [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type jakarta.ws.rs.core.UriInfo and qualifiers [@Default]
[ERROR]         - java member: RestService#uriInfo
[ERROR]         - declared on CLASS bean [types=[RestService, java.lang.Object], qualifiers=[@Default, @Any], target=RestService]
[ERROR]         - available beans:
[ERROR]                 - PRODUCER METHOD bean [types=[jakarta.ws.rs.core.UriInfo, java.lang.Object], qualifiers=[@Default, @Any], target=jakarta.ws.rs.core.UriInfo uriInfo(), declaringBean=org.jboss.resteasy.reactive.server.injection.ContextProducers]
[ERROR]                 - PRODUCER METHOD bean [types=[jakarta.ws.rs.core.UriInfo, java.lang.Object], qualifiers=[@Default, @Any], target=jakarta.ws.rs.core.UriInfo uriInfo(), declaringBean=org.jboss.resteasy.cdi.ContextProducers]
[ERROR]         at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1395)
[ERROR]         at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:305)
[ERROR]         at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:156)
...
```

I will check this up.

**Comment by geoand** [comment]
You seem to be mixing RESTEasy Classic and RESTEasy Reactive in the same application.

What does your pom.xml look like?

**Comment by jbonofre** [comment]
Here's the dependencies in my `pom.xml`:

```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-grpc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kubernetes-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kubernetes-config</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-logging-json</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client</artifactId>
        </dependency>
```

I guess the problem is between resteasy-reactive and transitive from grpc/rest-client. I can try to add an exclusion.

**Comment by jbonofre** [comment]
Here's the dependencies in my `pom.xml`:

```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-grpc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kubernetes-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kubernetes-config</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-logging-json</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client</artifactId>
        </dependency>
```

I guess the problem is between resteasy-reactive and transitive from grpc/rest-client. I can try to add an exclusion.

**Comment by mschorsch** [comment]
You have to use `quarkus-rest-client-reactive`  instead of `quarkus-rest-client`.

**Comment by jbonofre** [comment]
@mschorsch it makes sense. It will align my extensions (I'm using a meta extension). Thanks !
