### ISSUE TITLE
after bumping to 3.0.1.final -> ClassNotFoundException: org.hibernate.dialect.PostgreSQL82Dialect

### ISSUE THREAD

**Issue by punkratz312** [quarkusio/quarkus#32928]
### after 3.0.1.final bump class not found occures.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/8830888/234679589-fb6c6ea1-4028-4c79-8ddb-bf4d3090d2c2.png">

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/8830888/234679720-fc9d451a-5193-4179-b438-582f36fd9ed4.png">

we had an MetadataBuilder which is deprecated and the replacement it not rdy yet.
this custom sql function mapper is used at runtime i assume so it might not directly be the cause:

<img width="989" alt="image" src="https://user-images.githubusercontent.com/8830888/234680366-2a83abb9-3abb-480f-a290-46be19d34962.png">

```
2023-04-26 21:08:48,403 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.opentelemetry.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2023-04-26 21:08:48,593 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-04-26 21:08:48,599 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: org/hibernate/dialect/PostgreSQL82Dialect
	at com.vladmihalcea.hibernate.type.HibernateTypesContributor.contribute(HibernateTypesContributor.java:39)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:636)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:171)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:404)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:101)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:73)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:40)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$1.created(HibernateOrmRecorder.java:78)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:79)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy(Unknown Source)
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.hibernate.dialect.PostgreSQL82Dialect
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
	... 27 more
```

### Output of `uname -a` or `ver`

Darwin MacBook-Pro-von-vip.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 LTS OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.0.1.Final

**Comment by yrodiere** [comment]
Hey, thanks for your report.

Regarding `MetadataBuilderContributor`, you should still be able to set one through [quarkus.hibernate-orm.metadata-builder-contributor](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.metadata-builder-contributor). It's true that it's deprecated and we should expose its replacement, though; I created #32936 to address that.

Regarding `org.hibernate.dialect.PostgreSQL82Dialect`, you should simply no longer use it. I recommend having a look at the [migrationg guide from Hibernate ORM 5 to 6 in Quarkus](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration), in particular [this section](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration#dialect), but in short, replace this:

```
quarkus.datasource.db-kind = postgresql
# Incorrect!
quarkus.hibernate-orm.dialect = org.hibernate.dialect.PostgreSQL82Dialect
```

With this:

```
quarkus.datasource.db-kind = postgresql
quarkus.datasource.db-version = 8.2
```

Though I'd recommend upgrading your version of PostgreSQL, since the minimum version supported in Hibernate ORM is 10.0; see [this section of the migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration#some-databases-and-older-database-versions-are-no-longer-supported-in-hibernate-orm):

```
quarkus.datasource.db-kind = postgresql
# Will also require an upgrade of your postgresql install
quarkus.datasource.db-version = 10.0
```

Since the behavior you encountered is not the result of a bug, I'm going to close this ticket. Feel free to ask for more help on the usual channels (Stackoverflow, GitHub discussions).

Cheers.
