### ISSUE TITLE
Kafka shutdown issues

### ISSUE THREAD

**Issue by hwellmann** [quarkusio/quarkus#3296]
**Describe the bug**
Quarkus down not properly shut down `KafkaSink` and `Vertex`.

**Expected behavior**
Quarkus shuts down without logging warnings or errors.

**Actual behavior**
The following warning is logged every time:

````
WARN: An error occured during delivery of the @BeforeDestroyed(ApplicationScoped.class) event
java.util.concurrent.RejectedExecutionException: Task io.vertx.core.impl.TaskQueue$$Lambda$470/633727380@72e789cb rejected from java.util.concurrent.ThreadPoolExecutor@7c1812b3[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at io.vertx.core.impl.TaskQueue.execute(TaskQueue.java:93)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:288)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:242)
	at io.vertx.core.impl.EventLoopContext.executeBlocking(EventLoopContext.java:23)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:247)
	at io.vertx.core.impl.EventLoopContext.executeBlocking(EventLoopContext.java:23)
	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.close(KafkaWriteStreamImpl.java:225)
	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.close(KafkaWriteStreamImpl.java:220)
	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.close(KafkaWriteStreamImpl.java:215)
	at io.smallrye.reactive.messaging.kafka.KafkaSink.close(KafkaSink.java:146)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at io.smallrye.reactive.messaging.kafka.KafkaConnector.terminate(KafkaConnector.java:45)
	at io.smallrye.reactive.messaging.kafka.KafkaConnector_Observer_terminate_01ca61423b802db2b2ec45ffe53148a5efa33e27.notify(KafkaConnector_Observer_terminate_01ca61423b802db2b2ec45ffe53148a5efa33e27.zig:125)
	at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:228)
	at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:218)
	at io.quarkus.arc.ArcContainerImpl.shutdown(ArcContainerImpl.java:263)
	at io.quarkus.arc.Arc.shutdown(Arc.java:37)
	at io.quarkus.arc.runtime.ArcRecorder$1.run(ArcRecorder.java:37)
	at io.quarkus.runtime.StartupContext.close(StartupContext.java:43)
	at io.quarkus.runner.ApplicationImpl1.doStop(ApplicationImpl1.zig:140)
	at io.quarkus.runtime.Application.stop(Application.java:151)
	at io.quarkus.runner.RuntimeRunner$1.close(RuntimeRunner.java:129)
	at io.quarkus.runner.RuntimeRunner.close(RuntimeRunner.java:75)
	at io.quarkus.test.junit.QuarkusTestExtension$5.close(QuarkusTestExtension.java:246)
	at io.quarkus.test.junit.QuarkusTestExtension$ExtensionState.close(QuarkusTestExtension.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:61)
	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:73)
	at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
	at org.junit.jupiter.engine.descriptor.JupiterEngineDescriptor.cleanUp(JupiterEngineDescriptor.java:67)
	at org.junit.jupiter.engine.descriptor.JupiterEngineDescriptor.cleanUp(JupiterEngineDescriptor.java:29)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$9(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:83)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

````

**To Reproduce**
Add the following no-op test to quarkus-quickstarts/kafka-quickstart and run it from the IDE:

````java
package org.acme.quarkus.sample;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

@QuarkusTest
public class KafkaShutdownTest {

    @Test
    public void empty() {
    }
}

````

**Environment (please complete the following information):**
 Quarkus 0.19.1 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)

**Remarks**
There seems to be a conflict between `KafkaConnector.terminate()` handling the `BeforeDestroyed(ApplicationScope.class)` event and the shutdown task installed by `VertexRecorder`

**Comment by gsmet** [comment]
@hwellmann can you confirm it is still an issue?

**Comment by gsmet** [comment]
Closing. Please reopen a new one if you can reproduce.
