### ISSUE TITLE
Quarkus-info extension could provide beans available to applications

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#32994]
### Description

In our applicaiton we use `git-commit-id-maven-plugin` to create a git.properties, which we add to the build via `quarkus.config.locations`

I think it would be good if we could remove that and use quarkus-info and inject or a composite bean or multiple bean for; JavaInfo, GitInfo, BuildInfo, OsInfo, which could then be use through an application. This way we could easily customize also the format we want and/or need via a custom endpoint, or not use an endpoint at all but have it available for logging or any other purposes.

**Comment by geoand** [comment]
So if I understand correctly you just want access to the data vis CDI which you would then use to build your own endpoint?

**Comment by manofthepeace** [comment]
Yes. In my particular case the endpoint + a startup log are using the data from `git-commit-id-maven-plugin` which could then be removed and use only `quarkus-info` provided data  and `ProcessorInfo`. example log in my case;

```
log.info("<app> version {} running on {} cpus. Git branch is {} and short sha is {}", gitConfig.version(),
    ProcessorInfo.availableProcessors(), gitConfig.branch(), gitConfig.commitId());
```

where gitConfig is a ConfigMapping created from the properties file create by `git-commit-id-maven-plugin`

**Comment by ygyg70** [comment]
I was trying to use this capability (Quarkus version 3.0.0) with the following behavior:

- Injection of BuildInfo and GitInfo works in dev, test mode
- Locally, all artifact types (jar, native) are built without errors
- IDE (Intellij) shows "Unsatisfied dependency: no bean matches the injection point" warning for the injection fields
- With Github action, build fails with the exception shown below

Any ideas?

`Error: #25 347.2 [ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkus.info.GitInfo and qualifiers [@Default]
#25 347.2 [ERROR] 	- java member: ***.AppLifecycleBean#gitInfo
#25 347.2 [ERROR] 	- declared on CLASS bean [types=[***.AppLifecycleBean, java.lang.Object], qualifiers=[@Default, @Any], target=***.AppLifecycleBean]
#25 347.2 [ERROR] 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1435)
#25 347.2 [ERROR] 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:310)
#25 347.2 [ERROR] 	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:155)
#25 347.2 [ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:469)
#25 347.2 [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#25 347.2 [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#25 347.2 [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#25 347.2 [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#25 347.2 [ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
#25 347.2 [ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
#25 347.2 [ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#25 347.2 [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
#25 347.2 [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
#25 347.2 [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
#25 347.2 [ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#25 347.2 [ERROR] Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkus.info.GitInfo and qualifiers [@Default]
#25 347.2 [ERROR] 	- java member: ***.AppLifecycleBean#gitInfo
#25 347.2 [ERROR] 	- declared on CLASS bean [types=[***.AppLifecycleBean, java.lang.Object], qualifiers=[@Default, @Any], target=***.AppLifecycleBean]
#25 347.2 [ERROR] 	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:477)
#25 347.2 [ERROR] 	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:624)
#25 347.2 [ERROR] 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:298)
`

**Comment by geoand** [comment]
I've never seen that. Do you have a sample application thta exhibits that behavior?

**Comment by ramiswailem** [comment]
I use GitInfo from the dependency Quarkus-info:

```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-info</artifactId>
</dependency>
```

```
@Inject
GitInfo gitInfo;

String commitId;
String commitTime;
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    
  void onStart(@Observes StartupEvent ev) {
        LOG.info("The application is starting...");
        var localDateTime = gitInfo.commitTime().toLocalDateTime();
        commitId = gitInfo.latestCommitId();
        commitTime = localDateTime.format(formatter);
    }
```

**Comment by geoand** [comment]
I tried it and it worked just fine for me.
