### ISSUE TITLE
Port AWT Extension to Windows

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#32993]
### Description

Quarkus AWT extension enables server side image processing, e.g. converting formats, color spaces, resizing, generating thumbnails, watermarking, rendering custom fonts as overlays on uploaded images etc.
It also empowers extensions like Apache TIKA to read, convert and manipulate PDF files and many other document formats.

The code paths related to JNI state initialization are quite different on Windows and the extension requires refactoring and testing, perhaps even updates in upstream GraalVM/Mandrel.

### Implementation ideas

The implementation idea is really the same as with Linux, except Visual Studio or WinDBG  (shout out to @stooke :-D ) will be used to track the code paths in AWT native libs.

**Comment by gian1200** [comment]
This seems to affect <https://github.com/quarkiverse/quarkus-poi>, too. I don't use/need pdf handler, but gets the same error on Windows. I handle XSLX only.

Should this be tracked on this issue or a separate one?

Quarkus 3.8.4
quarkus-poi: 2.0.5

```java
...
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GRAALVM 22.3.3 JDK 17.0.8+7-jvmci-22.3-b22
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  56.563 s
[INFO] Finished at: 2024-04-19T19:37:35-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.8.4:build (default) on project viabcp-formularios-reportes: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:301)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.UnsupportedOperationException: Windows AWT integration is not ready in native-image and would result in java.lang.UnsatisfiedLinkError: no awt in java.library.path.
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep$NativeImageInvokerInfo$Builder.build(NativeImageBuildStep.java:973)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:248)
[ERROR]         ... 11 more
...
```

**Comment by col-panic** [comment]
Trying to render a QRCode native in Windows - build fails with
```
 Windows AWT integration is not ready in Quarkus native-image and would result in java.lang.UnsatisfiedLinkError: no awt in java.library.path.
```

**Comment by Eng-Fouad** [comment]
I was able to use [AWT SystemTray API](https://docs.oracle.com/javase/tutorial/uiswing/misc/systemtray.html) on Windows with addition of these classes to `AwtProcessor.setupJava2DClasses`:

```
classes.add("java.awt.AWTEvent");
classes.add("java.awt.Event");
classes.add("java.awt.event.ActionEvent");
classes.add("java.awt.event.ComponentEvent");
classes.add("java.awt.event.InputEvent");
classes.add("java.awt.event.MouseEvent");
classes.add("java.awt.Component");
classes.add("java.awt.Font");
classes.add("java.awt.FontMetrics");
classes.add("java.awt.Insets");
classes.add("java.awt.desktop.UserSessionEvent$Reason");
classes.add("java.awt.Container");
classes.add("java.awt.Cursor");
classes.add("java.awt.Dimension");
classes.add("java.awt.Frame");
classes.add("java.awt.Menu");
classes.add("java.awt.MenuComponent");
classes.add("java.awt.MenuItem");
classes.add("java.awt.Point");
classes.add("java.awt.PopupMenu");
classes.add("java.awt.SequencedEvent");
classes.add("java.awt.Toolkit");
classes.add("java.awt.TrayIcon");
classes.add("java.awt.Window");
classes.add("java.awt.Window$Type");
classes.add("java.lang.Enum");
classes.add("java.lang.Thread");
classes.add("java.util.Locale");
classes.add("sun.awt.image.SunVolatileImage");
classes.add("sun.awt.image.VolatileSurfaceManager");
classes.add("sun.awt.im.InputMethodWindow");
classes.add("sun.awt.windows.WToolkit");
classes.add("sun.awt.windows.WComponentPeer");
classes.add("sun.awt.windows.WDesktopPeer");
classes.add("sun.awt.windows.WFontPeer");
classes.add("sun.awt.windows.WFramePeer");
classes.add("sun.awt.windows.WMenuItemPeer");
classes.add("sun.awt.windows.WObjectPeer");
classes.add("sun.awt.windows.WPanelPeer");
classes.add("sun.awt.windows.WToolkit");
classes.add("sun.awt.windows.WTrayIconPeer");
classes.add("sun.awt.windows.WWindowPeer");
classes.add("sun.awt.AWTAutoShutdown");
classes.add("sun.awt.EmbeddedFrame");
classes.add("sun.awt.ExtendedKeyCodes");
classes.add("sun.awt.FontDescriptor");
classes.add("sun.awt.LightweightFrame");
classes.add("sun.awt.PlatformFont");
classes.add("sun.awt.SunToolkit");
classes.add("sun.awt.TimedWindowEvent");
classes.add("sun.awt.Win32GraphicsConfig");
classes.add("sun.awt.Win32GraphicsDevice");
classes.add("sun.awt.Win32GraphicsEnvironment");
classes.add("sun.font.FontDesignMetrics");
classes.add("sun.font.FontUtilities");
classes.add("sun.java2d.d3d.D3DGraphicsDevice$1");
classes.add("sun.java2d.d3d.D3DRenderQueue$1");
classes.add("sun.java2d.windows.WindowsFlags");
```

On the application side I had to add the following on `native-image.properties`:

```
Args=--initialize-at-run-time=sun.print.PrintServiceLookupProvider \
  --initialize-at-run-time=sun.datatransfer.DataFlavorUtil$DefaultDesktopDatatransferService \
  --initialize-at-run-time=javax.swing.plaf.metal.OceanTheme \
  --initialize-at-run-time=javax.swing.plaf.metal.MetalTheme \
  --initialize-at-run-time=javax.swing.plaf.metal.MetalBumps \
  --initialize-at-run-time=sun.swing.SwingUtilities2
```

Also I had to remove:

```
unsupported.produce(new UnsupportedOSBuildItem(OS.WINDOWS,
                "Windows AWT integration is not ready in Quarkus native-image and would result in " +
                        "java.lang.UnsatisfiedLinkError: no awt in java.library.path."));
```


I have only one problem, the popup menu from the systemstary icon appears to be smaller and does not fit the text:

JVM mode:

<img width="92" height="70" alt="Image" src="https://github.com/user-attachments/assets/eb798087-a332-493f-aaad-bc1d3469e50b" />

Native mode:

<img width="52" height="56" alt="Image" src="https://github.com/user-attachments/assets/b7ba85bc-d2f9-4bd2-afb0-9bd05d207619" />

**Comment by Karm** [comment]
Discussion continues here: https://github.com/quarkusio/quarkus/pull/50603
