### ISSUE TITLE
ClassNotFoundException when scheduler calls static @Transactional PanacheEntity method

### ISSUE THREAD

**Issue by neon-dev** [quarkusio/quarkus#32990]
### Describe the bug

The following method cannot be called from a `@Scheduled` annotated method, if the entity class is imported from a lib and not part of the same source:
```java
@Entity
public class ExternalEntity extends PanacheEntity {
    ...
    @Transactional
    public static long doStuff() { ... }
}
```

### Expected behavior

This call should work without throwing an exception:
```java
@Scheduled(every = "1h")
public void run() {
  ExternalEntity.doStuff();
}
```

### Actual behavior

Class not found:
```
2023-04-28 15:31:41,012 ERROR [io.qua.sch.com.run.StatusEmitterInvoker] (vert.x-worker-thread-0) Error occurred while executing task for trigger IntervalTrigger [id=1_org.acme.Reproducer_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de, interval=3600000]: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/acme/entity/Entity_InterceptorInitializer
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
        at java.base/java.util.concurrent.CompletableFuture$MinimalStage.whenComplete(CompletableFuture.java:2902)
        at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:24)
        at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask.doInvoke(SimpleScheduler.java:333)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.handle(SimpleScheduler.java:314)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.handle(SimpleScheduler.java:310)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: org/acme/entity/Entity_InterceptorInitializer
        at org.acme.entity.Entity.deleteByField(Entity.java)
        at org.acme.Reproducer.run(Reproducer.java:13)
        at org.acme.Reproducer_ClientProxy.run(Unknown Source)
        at org.acme.Reproducer_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de.invokeBean(Unknown Source)
        ... 15 more
Caused by: java.lang.ClassNotFoundException: org.acme.entity.Entity_InterceptorInitializer
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
        ... 19 more
```

### How to Reproduce?

1. Download & unzip [reproducer.zip](https://github.com/quarkusio/quarkus/files/11353916/reproducer.zip)
2. `mvn -f entity/pom.xml install`
3. `mvn -f app/pom.xml quarkus:dev`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.2728]

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17

### Quarkus version or git rev

2.16.6.Final & 3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

### Additional information

Tested with:
JDBC extension: `quarkus-jdbc-h2` & `quarkus-jdbc-mysql`
Panache extension: `quarkus-hibernate-orm-panache` (reactive untested)
Scheduler extension: `quarkus-scheduler`

Possible workarounds:
Move the entity class or the `@Transactional` annotation into the main project.

**Comment by mkouba** [comment]
Hm, the generated `org.acme.entity.Entity_InterceptorInitializer` is a public class so I suspect there's something related to the fact that `org.acme.entity.Entity` is also transformed by Panache...

**Comment by mkouba** [comment]
> Hm, the generated `org.acme.entity.Entity_InterceptorInitializer` is a public class so I suspect there's something related to the fact that `org.acme.entity.Entity` is also transformed by Panache...

I've tried to extract the intercepted static method in a separate class and still can see the same NCDFE. So it's likely not related to the bytecode transformation...

**Comment by mkouba** [comment]
And it fails with quarkus 3.0.1.Final too..

**Comment by geoand** [comment]
There is a flag in the build item that allows you to make generated classes part of the application ClassLoader.

Have you tried it?

**Comment by stuartwdouglas** [comment]
That is exactly that this flag does, if it is false it is loaded by the base runtime CL, not the runtime CL.

**Comment by mkouba** [comment]
> That is exactly that this flag does, if it is false it is loaded by the base runtime CL, not the runtime CL.

Ok, thanks. I think that I found the problem: https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/staticmethods/InterceptedStaticMethodsProcessor.java#L157 and fix is on the way...

Out of curiosity, where's the place where the `GeneratedClassBuildItem.applicationClass` is used to affect the behavior of a ClassLoader?

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus/blob/6bd418575a28ed940258346727927b4277790bbf/core/deployment/src/main/java/io/quarkus/runner/bootstrap/StartupActionImpl.java#L353

**Comment by mkouba** [comment]
> https://github.com/quarkusio/quarkus/blob/6bd418575a28ed940258346727927b4277790bbf/core/deployment/src/main/java/io/quarkus/runner/bootstrap/StartupActionImpl.java#L353

:+1: thanks!

**Comment by neon-dev** [comment]
Thanks a lot! Keep up the great work.
