### ISSUE TITLE
Kubernetes Dev Services: `kind` flavour doesn't work on macOS / M1

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#33003]
### Describe the bug

Cannot start a `kind` cluster when running tests on macOS. Haven't looked at the details yet but might be related to the fact that I'm using an Apple Silicon CPU.

### Expected behavior

`kind` cluster should start via dev services or be documented not to work on macOS.

### Actual behavior

`kind` cluster fails to start with the following logs / errors finishing with (the log is very long, can attach a fuller version if needed):

```java
couldn't initialize a Kubernetes cluster
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase
	cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:108
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	cmd/kubeadm/app/cmd/init.go:153
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
	cmd/kubeadm/app/kubeadm.go:50
main.main
	cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1263
error execution phase wait-control-plane
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	cmd/kubeadm/app/cmd/init.go:153
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
	cmd/kubeadm/app/kubeadm.go:50
main.main
	cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1263
)
	at com.dajudge.kindcontainer.KindContainer.exec(KindContainer.java:307)
	at com.dajudge.kindcontainer.KindContainer.kubeadmInit(KindContainer.java:239)
	at com.dajudge.kindcontainer.KindContainer.containerIsStarting(KindContainer.java:170)
	... 19 more

2023-04-29 00:30:10,309 ERROR [🐳 .24.1]] (build-19) Log output from the failed container:
INFO: ensuring we can execute mount/umount even with userns-remapINFO: remounting /sys read-onlyINFO: making mounts sharedINFO: detected cgroup v1WARN: cgroupns not enabled! Please use cgroup v2, or cgroup v1 with cgroupns enabled.INFO: fix cgroup mounts for all subsystemsINFO: unmounting and removing /sys/fs/cgroup/openrcINFO: clearing and regenerating /etc/machine-idInitializing machine ID from random generator.INFO: faking /sys/class/dmi/id/product_name to be "kind"INFO: setting iptables to detected mode: legacyINFO: Detected IPv4 address: 172.17.0.3INFO: Detected IPv6 address: systemd 248.3-1ubuntu8.6 running in system mode. (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP -LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)Detected virtualization docker.Detected architecture arm64.Failed to create symlink /sys/fs/cgroup/cpu: File existsFailed to create symlink /sys/fs/cgroup/cpuacct: File existsFailed to create symlink /sys/fs/cgroup/net_cls: File existsFailed to create symlink /sys/fs/cgroup/net_prio: File existsWelcome to Ubuntu 21.10!Couldn't move remaining userspace processes, ignoring: Input/output errorQueued start job for default target Graphical Interface.-.slice: Failed to migrate controller cgroups from , ignoring: Input/output error[  OK  ] Created slice slice used to run Kubernetes / Kubelet.[  OK  ] Created slice system-modprobe.slice.[  OK  ] Started Dispatch Password …ts to Console Directory Watch.[  OK  ] Set up automount Arbitrary…s File System Automount Point.[  OK  ] Reached target Local Encrypted Volumes.[  OK  ] Reached target Paths.[  OK  ] Reached target Slices.[  OK  ] Reached target Swap.[  OK  ] Reached target Local Verity Integrity Protected Volumes.[  OK  ] Listening on Journal Audit Socket.[  OK  ] Listening on Journal Socket (/dev/log).[  OK  ] Listening on Journal Socket.[  OK  ] Reached target Sockets.         Mounting Huge Pages File System...         Mounting Kernel Debug File System...         Mounting Kernel Trace File System...         Starting Journal Service...         Starting Create list of st…odes for the current kernel...         Starting Load Kernel Module configfs...         Starting Load Kernel Module fuse...         Starting Remount Root and Kernel File Systems...         Starting Apply Kernel Variables...[  OK  ] Mounted Huge Pages File System.[  OK  ] Mounted Kernel Debug File System.[  OK  ] Mounted Kernel Trace File System.[  OK  ] Finished Create list of st… nodes for the current kernel.modprobe@configfs.service: Deactivated successfully.[  OK  ] Finished Load Kernel Module configfs.[  OK  ] Finished Remount Root and Kernel File Systems.         Starting Create System Users...         Starting Update UTMP about System Boot/Shutdown...modprobe@fuse.service: Deactivated successfully.[  OK  ] Finished Load Kernel Module fuse.[  OK  ] Finished Apply Kernel Variables.         Mounting FUSE Control File System...[  OK  ] Mounted FUSE Control File System.[  OK  ] Finished Update UTMP about System Boot/Shutdown.[  OK  ] Started Journal Service.         Starting Flush Journal to Persistent Storage...[  OK  ] Finished Flush Journal to Persistent Storage.[  OK  ] Finished Create System Users.         Starting Create Static Device Nodes in /dev...[  OK  ] Finished Create Static Device Nodes in /dev.[  OK  ] Reached target Local File Systems (Pre).[  OK  ] Reached target Local File Systems.[  OK  ] Reached target System Initialization.[  OK  ] Started Daily Cleanup of Temporary Directories.[  OK  ] Reached target Basic System.[  OK  ] Reached target Timers.         Starting containerd container runtime...[  OK  ] Started containerd container runtime.[  OK  ] Reached target Multi-User System.[  OK  ] Reached target Graphical Interface.         Starting Update UTMP about System Runlevel Changes...[  OK  ] Finished Update UTMP about System Runlevel Changes.


```

### Output of `uname -a` or `ver`

Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### Quarkus version or git rev

3.0.1

**Comment by maxandersen** [comment]
can you share your application.properties?

**Comment by maxandersen** [comment]
`quarkus.kubernetes-client.devservices.flavor=kind`

seem to work for me on second run.

**Comment by metacosm** [comment]
That's the app I've been using: https://github.com/quarkiverse/quarkus-operator-sdk/tree/main/samples/exposedapp

**Comment by gsmet** [comment]
If anything, I think this is an upstream issue.

It might have been already fixed upstream.
