### ISSUE TITLE
Quarkus Native on GraalVM issue with ElasticSearch Java Client jakarta.json.JsonException: Provider org.eclipse.parsson.JsonProviderImpl not found

### ISSUE THREAD

**Issue by AbhinabKanrar** [quarkusio/quarkus#33049]
### Describe the bug

I'm using Quarkus 2.16.6.Final with ElasticSearch 8.7. I've written a small piece of code to use ES's update_by_query feature:

```
try (Reader query = new StringReader(/*my json query String*/)) {
  var request = UpdateByQueryRequest.of(fn -> fn.index(index).withJson(query));

  return client.updateByQuery(request);
} catch (IOException e) {
  throw new RuntimeException(e);
}
```

And this is my ES client initialization code:
```

var credsProv = new BasicCredentialsProvider();

credsProv.setCredentials(AuthScope.ANY, new UsernamePasswordCredentials(username, password));

var restClient = RestClient.builder(HttpHost.create(host)).setHttpClientConfigCallback(
    hc -> hc.disableAuthCaching().setDefaultCredentialsProvider(credsProv)).build();

var transport = new RestClientTransport(restClient, new JacksonJsonpMapper());

var client = new ElasticsearchAsyncClient(transport);
```

This actually works fine in normal jvm mode. However whenever I'm trying to run this is Quarkus Native(GraalVM) mode I'm getting this error:

```
Caused by: jakarta.json.JsonException: Provider org.eclipse.parsson.JsonProviderImpl not found
   at jakarta.json.spi.JsonProvider.newInstance(JsonProvider.java:160)
   at jakarta.json.spi.JsonProvider.provider(JsonProvider.java:144)
   at co.elastic.clients.json.JsonpUtils.findProvider(JsonpUtils.java:65)
... 54 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.parsson.JsonProviderImpl
    at java.base@17.0.7/java.lang.Class.forName(DynamicHub.java:1132)
    at java.base@17.0.7/java.lang.Class.forName(DynamicHub.java:1105)
    at jakarta.json.spi.JsonProvider.newInstance(JsonProvider.java:157)
```

As per the [documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/installation.html), I've added required dependency in the Maven pom.

```
    <dependency>
        <groupId>co.elastic.clients</groupId>
        <artifactId>elasticsearch-java</artifactId>
        <version>8.7.0</version>
        <exclusions>
            <exclusion>
                <groupId>commons-logging</groupId>
                <artifactId>commons-logging</artifactId>
            </exclusion>
            <exclusion>
                <groupId>jakarta.json</groupId>
                <artifactId>jakarta.json-api</artifactId>
            </exclusion>
            <exclusion>
                <groupId>org.eclipse.parsson</groupId>
                <artifactId>parsson</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>jakarta.json</groupId>
        <artifactId>jakarta.json-api</artifactId>
        <version>2.1.1</version>
        <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>org.eclipse.parsson</groupId>
        <artifactId>parsson</artifactId>
        <version>1.1.1</version>
        <scope>compile</scope>
    </dependency>
```

But that didn't solve this issue and wondering how come the same thing works on normal JVM but not in native mode in GraalVM

### Expected behavior

In Quarkus native mode the ElasticSearch java client should work just like JVM mode

### Actual behavior

Getting below exception:
```
2023-05-02 08:14:52,422 ERROR [com.mab.cha.con.exc.ServerExceptionHandler] (vert.x-eventloop-thread-3) Unhandled error: jakarta.json.JsonException: Unable to get a JsonProvider. Check your classpath or thread context classloader.
	at co.elastic.clients.json.JsonpUtils.findProvider(JsonpUtils.java:85)
	at co.elastic.clients.json.JsonpUtils.provider(JsonpUtils.java:55)
	at co.elastic.clients.json.SimpleJsonpMapper.jsonProvider(SimpleJsonpMapper.java:93)
	at co.elastic.clients.json.WithJson.withJson(WithJson.java:57)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.lambda$syncFlow$3(FaultToleranceInterceptor.java:257)
	at io.smallrye.faulttolerance.core.InvocationContext.call(InvocationContext.java:20)
	at io.smallrye.faulttolerance.core.Invocation.apply(Invocation.java:29)
	at io.smallrye.faulttolerance.core.retry.Retry.doApply(Retry.java:88)
	at io.smallrye.faulttolerance.core.retry.Retry.apply(Retry.java:42)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.syncFlow(FaultToleranceInterceptor.java:259)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.intercept(FaultToleranceInterceptor.java:186)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
	at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor.validateMethodInvocation(ResteasyReactiveEndPointValidationInterceptor.java:21)
	at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:78)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:75)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: jakarta.json.JsonException: Provider org.eclipse.parsson.JsonProviderImpl not found
	at jakarta.json.spi.JsonProvider.newInstance(JsonProvider.java:160)
	at jakarta.json.spi.JsonProvider.provider(JsonProvider.java:144)
	at co.elastic.clients.json.JsonpUtils.findProvider(JsonpUtils.java:65)
	... 54 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.parsson.JsonProviderImpl
	at java.base@17.0.7/java.lang.Class.forName(DynamicHub.java:1132)
	at java.base@17.0.7/java.lang.Class.forName(DynamicHub.java:1105)
	at jakarta.json.spi.JsonProvider.newInstance(JsonProvider.java:157)
	... 56 more

```

### Output of `uname -a` or `ver`

quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17

### Output of `java -version`

openjdk 17.0.6 2023-01-17

### Quarkus version or git rev

2.16.6.Final

**Comment by gsmet** [comment]
The Elasticsearch Java Client 8.x requires the `jakarta.*` packages. So use Quarkus 3.0 and the new `quarkus-elasticsearch-java-client` extension.

See https://quarkus.io/guides/elasticsearch for more information

**Comment by yrodiere** [comment]
> Quarkus native mode the ElasticSearch java client should work just like JVM mode

Certainly not without a Quarkus extension.

As Guillaume mentioned, you need to use Quarkus 3, which includes the appropriate extension.

**Comment by yrodiere** [comment]
Closing, feel free to comment and ping me if you encounter the same problem with Quarkus 3 and the new `quarkus-elasticsearch-java-client` extension.

**Comment by AbhinabKanrar** [comment]
So used  `Quarkus 3.0`  with  `quarkus-elasticsearch-java-client` and instead of manually creating the ES client, just injected the same as mentioned in the [doc](https://quarkus.io/guides/elasticsearch#using-the-elasticsearch-java-client). 
Now the old error is gone now but getting this new one :(

```
2023-05-02 12:56:34,289 ERROR [com.mab.cha.con.exc.ServerExceptionHandler] (vert.x-eventloop-thread-1) Unhandled error: java.lang.RuntimeException: No deserializer found in 'co.elastic.clients.elasticsearch.core.UpdateByQueryRequest._DESERIALIZER'
	at co.elastic.clients.json.JsonpMapperBase.findDeserializer(JsonpMapperBase.java:92)
	at co.elastic.clients.json.JsonpMapperBase.findDeserializer(JsonpMapperBase.java:78)
	at co.elastic.clients.util.WithJsonObjectBuilderBase.withJson(WithJsonObjectBuilderBase.java:44)
	at co.elastic.clients.json.WithJson.withJson(WithJson.java:57)
	at co.elastic.clients.elasticsearch.core.UpdateByQueryRequest.of(UpdateByQueryRequest.java:212)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:74)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:63)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.lambda$syncFlow$3(FaultToleranceInterceptor.java:257)
	at io.smallrye.faulttolerance.core.InvocationContext.call(InvocationContext.java:20)
	at io.smallrye.faulttolerance.core.Invocation.apply(Invocation.java:29)
	at io.smallrye.faulttolerance.core.retry.Retry.doApply(Retry.java:88)
	at io.smallrye.faulttolerance.core.retry.Retry.apply(Retry.java:42)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.syncFlow(FaultToleranceInterceptor.java:259)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.intercept(FaultToleranceInterceptor.java:186)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:38)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:26)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:74)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:63)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
	at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor.validateMethodInvocation(ResteasyReactiveEndPointValidationInterceptor.java:21)
	at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:38)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:26)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:78)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:75)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

Use these props in the application.properties file:
```
quarkus.elasticsearch.protocol=https
quarkus.elasticsearch.hosts=<>
quarkus.elasticsearch.username=<>
quarkus.elasticsearch.password=<>
quarkus.elasticsearch.connection-timeout=5
```

**Comment by gsmet** [comment]
Did you remove all this from your POM? You need it gone.

```xml
    <dependency>
        <groupId>co.elastic.clients</groupId>
        <artifactId>elasticsearch-java</artifactId>
        <version>8.7.0</version>
        <exclusions>
            <exclusion>
                <groupId>commons-logging</groupId>
                <artifactId>commons-logging</artifactId>
            </exclusion>
            <exclusion>
                <groupId>jakarta.json</groupId>
                <artifactId>jakarta.json-api</artifactId>
            </exclusion>
            <exclusion>
                <groupId>org.eclipse.parsson</groupId>
                <artifactId>parsson</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>jakarta.json</groupId>
        <artifactId>jakarta.json-api</artifactId>
        <version>2.1.1</version>
        <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>org.eclipse.parsson</groupId>
        <artifactId>parsson</artifactId>
        <version>1.1.1</version>
        <scope>compile</scope>
    </dependency>
```

**Comment by AbhinabKanrar** [comment]
> Did you remove all this from your POM? You need it gone.
> 
> ```
>     <dependency>
>         <groupId>co.elastic.clients</groupId>
>         <artifactId>elasticsearch-java</artifactId>
>         <version>8.7.0</version>
>         <exclusions>
>             <exclusion>
>                 <groupId>commons-logging</groupId>
>                 <artifactId>commons-logging</artifactId>
>             </exclusion>
>             <exclusion>
>                 <groupId>jakarta.json</groupId>
>                 <artifactId>jakarta.json-api</artifactId>
>             </exclusion>
>             <exclusion>
>                 <groupId>org.eclipse.parsson</groupId>
>                 <artifactId>parsson</artifactId>
>             </exclusion>
>         </exclusions>
>     </dependency>
>     <dependency>
>         <groupId>jakarta.json</groupId>
>         <artifactId>jakarta.json-api</artifactId>
>         <version>2.1.1</version>
>         <scope>compile</scope>
>     </dependency>
>     <dependency>
>         <groupId>org.eclipse.parsson</groupId>
>         <artifactId>parsson</artifactId>
>         <version>1.1.1</version>
>         <scope>compile</scope>
>     </dependency>
> ```

Yup removed those. Still need those even after using quarkus-elasticsearch-java-client?

**Comment by yrodiere** [comment]
Actually this issue is quite messy already; @AbhinabKanrar can you please open another issue with a reproducer for your problem on Quarkus 3, please?
