### ISSUE TITLE
Native build fails on docs module

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#33061]
### Describe the bug

Granted this is a somewhat unusual scenario but it might happen in a multi-module project where a documentation module exists and the native profile / build is requested. Build fails with:
 
```
[1/7] Initializing...
                                                                                    (0.0s @ 0.16GB)
Error: Feature io.quarkus.runtime.graal.DisableLoggingFeature class not found on the classpath. Ensure that the name is correct and that the class is on the classpath.
com.oracle.svm.core.util.UserError$UserException: Feature io.quarkus.runtime.graal.DisableLoggingFeature class not found on the classpath. Ensure that the name is correct and that the class is on the classpath.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.registerFeatures(FeatureHandler.java:175)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:852)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:575)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
------------------------------------------------------------------------------------------------------------------------
                         0.1s (5.5% of total time) in 6 GCs | Peak RSS: 0.42GB | CPU load: 3.33
========================================================================================================================
```

### Expected behavior

Nothing should happen when trying to perform a native build of a module that doesn't contain any code.

### Actual behavior

Build fails.

**Comment by geoand** [comment]
This is not really Quarkus specific. 

The issue arises because you have configured the Quarkus plugin on a project that is not a Quarkus project.

**Comment by metacosm** [comment]
This only fails when activating the native profile, though. JVM mode is just fine with it.

**Comment by metacosm** [comment]
And actually, to be able to generate the docs, I believe you need the Quarkus plugin anyway for the config properties to be processed.

**Comment by geoand** [comment]
So the question becomes: Do you miss anything if you add:

```xml
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
```

in the docs module?

**Comment by geoand** [comment]
In any case, I stand by my initial assessment that this is not a Quarkus core issue. At best it's a Quarkiverse generated project issue

**Comment by gsmet** [comment]
I don't think you need it. The config reference doc is generated when the extension is built and it's just included in the adoc file.

**Comment by gastaldi** [comment]
IMHO including the `quarkus-maven-plugin` in the docs build is wrong: https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/quarkiverse/java/docs/pom.tpl.qute.xml#L32

I'll submit a PR removing it

**Comment by metacosm** [comment]
It would still be nice for the native build to not run on modules that do not contain Quarkus projects but since the underlying problem of this issue has been addressed, we can close this issue now.
