### ISSUE TITLE
Can't build the tree with mvnd anymore due to Gradle Enterprise build scans

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#33095]
Even with Gradle Enterprise not enabled locally, it's impossible to build Quarkus with `mvnd` anymore.

If I do `mvnd -DskipDocs -DskipTests -DskipITs -Dinvoker.skip -DskipExtensionValidation -Dskip.gradle.tests clean install`, I get:

```
[INFO] Processing build on daemon 0c05a412
[INFO] 0 goals, 0 executed
[ERROR] Internal error: java.lang.IllegalStateException: MavenPluginManager was not overridden -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalStateException: MavenPluginManager was not overridden
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:120)
	at org.apache.maven.cli.DaemonMavenCli.execute(DaemonMavenCli.java:707)
	at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:242)
	at org.apache.maven.cli.DaemonMavenCli.main(DaemonMavenCli.java:218)
	at org.mvndaemon.mvnd.daemon.Server.handle(Server.java:593)
	at org.mvndaemon.mvnd.daemon.Server.client(Server.java:269)
	at org.mvndaemon.mvnd.daemon.Server.accept(Server.java:236)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: MavenPluginManager was not overridden
	at com.gradle.enterprise.b.a.a(SourceFile:152)
	at com.gradle.enterprise.b.a.a(SourceFile:45)
	at com.gradle.maven.internal.GradleEnterpriseLifecycleManager.afterSessionStart(SourceFile:168)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:208)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	... 7 common frames omitted
```

While I can understand mvnd is not supported to produce build scans, I think we should still be able to build with mvnd if not using build scans.

/cc @maxandersen @aloubyansky @ppalaga @runningcode

**Comment by phillip-kruger** [comment]
Same for me :(

**Comment by gastaldi** [comment]
Interesting, I don't get this error. 

I ran `mvnd -DskipDocs -DskipTests -DskipITs -Dinvoker.skip -DskipExtensionValidation -Dskip.gradle.tests clean install` and it worked great.  This is my setup:

```
Apache Maven Daemon (mvnd) 1.0-m6 darwin-aarch64 native client (47d4c6b9c399079d91312bb8ae35d1d76e7fd97a)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.osx.OsXNativePty
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /Users/ggastald/.sdkman/candidates/mvnd/current/mvn
Java version: 17.0.6, vendor: GraalVM Community, runtime: /Users/ggastald/.sdkman/candidates/java/22.3.1.r17-grl
Default locale: en_BR, platform encoding: UTF-8
OS name: "mac os x", version: "13.3.1", arch: "aarch64", family: "mac"
```

**Comment by runningcode** [comment]
I will see if there's a way to do this automatically when the Maven daemon is detected. We are also working on improving how the Maven daemon interact with the Build Scan service. In the meantime, you can run the build with `-Dscan=false` to disable Build Scan functionality.

**Comment by gsmet** [comment]
> As a workaround, you can run the build with -Dscan=false to disable Build Scan functionality.

But I thought we made that the default if you didn't set up a token and an account? @maxandersen ?

**Comment by maxandersen** [comment]
What happens without key is the maven plugin starts but don't do anything. 

I assume mvnd still initialize the gradle maven plugin and it then fails. 

Sounds like it should be able to configure it to not do that.

**Comment by ppalaga** [comment]
Which version do you work with @gsmet ? There were some Gradle build scans fixes done a couple of weeks ago. Not sure though those were released already. @gnodet might know whether the current issue is solved or not.

**Comment by runningcode** [comment]
Could you also please let us know which version of the Maven daemon you are using?

**Comment by gsmet** [comment]
Ah. I might be using an older version. Let me upgrade to the latest.

**Comment by phillip-kruger** [comment]
I still get an error even with the latest main:

```
[ERROR] Failed to execute goal io.smallrye:jandex-maven-plugin:3.1.1:jandex (make-index) on project quarkus-devtools-registry-client: Execution make-index of goal io.smallrye:jandex-maven-plugin:3.1.1:jandex failed: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error in custom provider, java.lang.IllegalStateException
[ERROR]   at org.apache.maven.session.scope.internal.SessionScopeModule.configure(SessionScopeModule.java:64) (via modules: org.eclipse.sisu.wire.WireModule -> org.apache.maven.session.scope.internal.SessionScopeModule)
[ERROR]   while locating org.apache.maven.execution.MavenSession
[ERROR]     for the 3rd parameter of com.gradle.maven.cache.extension.h.a.a(Unknown Source)
[ERROR]   at com.gradle.maven.cache.extension.h.a.a(Unknown Source) (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule -> com.gradle.maven.extension.b -> com.gradle.maven.extension.b$a -> com.gradle.maven.cache.extension.h.a)
[ERROR]   while locating com.gradle.maven.common.configuration.n
[ERROR]     for the 3rd parameter of com.gradle.maven.cache.extension.g.e.<init>(Unknown Source)
[ERROR]   at ClassRealm[coreExtension>com.gradle:gradle-enterprise-maven-extension:1.17.1, parent: ClassRealm[plexus.core, parent: null]] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule -> com.gradle.maven.extension.b -> com.gradle.maven.extension.b$a -> com.gradle.maven.cache.extension.h.a -> com.gradle.maven.cache.extension.g.d)
[ERROR]   while locating com.gradle.maven.cache.extension.g.e
[ERROR]     for the 2nd parameter of com.gradle.maven.cache.extension.g.h.<init>(Unknown Source)
[ERROR]   while locating com.gradle.maven.cache.extension.g.h annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit
[ERROR]   at org.eclipse.sisu.wire.LocatorWiring
[ERROR]   while locating com.gradle.maven.cache.extension.g.h
[ERROR]     for the 1st parameter of com.gradle.maven.cache.extension.g.g.<init>(Unknown Source)
[ERROR]   while locating com.gradle.maven.cache.extension.g.g annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit
[ERROR]   at org.eclipse.sisu.wire.LocatorWiring
[ERROR]   while locating com.gradle.maven.cache.extension.g.g
[ERROR]     for the 3rd parameter of com.gradle.maven.cache.extension.d.k.<init>(Unknown Source)
[ERROR]   at ClassRealm[coreExtension>com.gradle:gradle-enterprise-maven-extension:1.17.1, parent: ClassRealm[plexus.core, parent: null]] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule -> com.gradle.maven.extension.b -> com.gradle.maven.extension.b$a -> com.gradle.maven.cache.extension.h.a)
[ERROR]   while locating com.gradle.maven.cache.extension.d.k
[ERROR] 
[ERROR] 1 error
[ERROR] -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0:test (default-test) on project quarkus-bootstrap-core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0:test failed: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error in custom provider, java.lang.IllegalStateException
[ERROR]   at org.apache.maven.session.scope.internal.SessionScopeModule.configure(SessionScopeModule.java:64) (via modules: org.eclipse.sisu.wire.WireModule -> org.apache.maven.session.scope.internal.SessionScopeModule)
[ERROR]   while locating org.apache.maven.execution.MavenSession
[ERROR]     for the 3rd parameter of com.gradle.maven.cache.extension.h.a.a(Unknown Source)
[ERROR]   at com.gradle.maven.cache.extension.h.a.a(Unknown Source) (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule -> com.gradle.maven.extension.b -> com.gradle.maven.extension.b$a -> com.gradle.maven.cache.extension.h.a)
[ERROR]   while locating com.gradle.maven.common.configuration.n
[ERROR]     for the 3rd parameter of com.gradle.maven.cache.extension.g.e.<init>(Unknown Source)
[ERROR]   at ClassRealm[coreExtension>com.gradle:gradle-enterprise-maven-extension:1.17.1, parent: ClassRealm[plexus.core, parent: null]] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule -> com.gradle.maven.extension.b -> com.gradle.maven.extension.b$a -> com.gradle.maven.cache.extension.h.a -> com.gradle.maven.cache.extension.g.d)
[ERROR]   while locating com.gradle.maven.cache.extension.g.e
[ERROR]     for the 2nd parameter of com.gradle.maven.cache.extension.g.h.<init>(Unknown Source)
[ERROR]   while locating com.gradle.maven.cache.extension.g.h annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit
[ERROR]   at org.eclipse.sisu.wire.LocatorWiring
[ERROR]   while locating com.gradle.maven.cache.extension.g.h
[ERROR]     for the 1st parameter of com.gradle.maven.cache.extension.g.g.<init>(Unknown Source)
[ERROR]   while locating com.gradle.maven.cache.extension.g.g annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit
[ERROR]   at org.eclipse.sisu.wire.LocatorWiring
[ERROR]   while locating com.gradle.maven.cache.extension.g.g
[ERROR]     for the 3rd parameter of com.gradle.maven.cache.extension.d.k.<init>(Unknown Source)
[ERROR]   at ClassRealm[coreExtension>com.gradle:gradle-enterprise-maven-extension:1.17.1, parent: ClassRealm[plexus.core, parent: null]] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule -> com.gradle.maven.extension.b -> com.gradle.maven.extension.b$a -> com.gradle.maven.cache.extension.h.a)
[ERROR]   while locating com.gradle.maven.cache.extension.d.k
[ERROR] 
[ERROR] 1 error
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :quarkus-devtools-registry-client
```

**Comment by phillip-kruger** [comment]
This was with quickbuild (so skipping tests). If I do a full build, I also get test failures in the `independent-projects/extension-maven-plugin` :

```
[ERROR] Tests run: 8, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 27.285 s <<< FAILURE! - in io.quarkus.maven.ExtensionDescriptorMojoTest
[ERROR] io.quarkus.maven.ExtensionDescriptorMojoTest.shouldFlagIncorrectRuntimeDependencyOnDeployment  Time elapsed: 9.129 s  <<< ERROR!
junit.framework.AssertionFailedError: 
Message format does not match expectations: 
Failed to resolve dependencies of io.quackiverse:quarkus-fake-extension:jar:999-SNAPSHOT
        at junit.framework.Assert.fail(Assert.java:47)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at io.quarkus.maven.ExtensionDescriptorMojoTest.shouldFlagIncorrectRuntimeDependencyOnDeployment(ExtensionDescriptorMojoTest.java:185)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:50)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

... 
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ExtensionDescriptorMojoTest.shouldFlagIncorrectRuntimeDependencyOnDeployment:185 Message format does not match expectations: 
Failed to resolve dependencies of io.quackiverse:quarkus-fake-extension:jar:999-SNAPSHOT
[ERROR]   ExtensionDescriptorMojoTest.shouldFlagMissingDependenciesInARealisticExtension:162 Message format does not match expectations: 
Failed to resolve dependencies of io.quackiverse:quarkus-fake-extension:jar:999-SNAPSHOT
[ERROR]   ExtensionDescriptorMojoTest.shouldProcessRealisticExtensionCleanly:146 » MojoExecution Failed to resolve dependencies of io.quackiverse:quarkus-fake-extension:jar:999-SNAPSHOT
[INFO] 
[ERROR] Tests run: 8, Failures: 0, Errors: 3, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

```

**Comment by phillip-kruger** [comment]
Seems like upgrading to maven 3.9.x solves the issue.

**Comment by gnodet** [comment]
The `mvn -DskipDocs -DskipTests -DskipITs -Dinvoker.skip -DskipExtensionValidation -Dskip.gradle.tests clean install` command works for me on both mvnd-1.0-m6-m39 and mvnd-1.0-m6-m40.

**Comment by gsmet** [comment]
I confirm it works with the latest `mvnd`. Thanks!
