### ISSUE TITLE
Quarkus Kubernetes extension fails to create configuration

### ISSUE THREAD

**Issue by smoell** [quarkusio/quarkus#33178]
### Describe the bug

After upgrading my project to Quarkus 3, the build fails with:

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.2.Final:build (default) on project aws-eks-quarkus-example: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep#process threw an exception: mapping values are not allowed here
[ERROR]  in reader, line 2, column 77:
[ERROR]      ... g the AssumeRole operation: User: arn:aws:sts::<id>:assu ... 
[ERROR]                                          ^
[ERROR] 
[ERROR]         at org.snakeyaml.engine.v2.scanner.ScannerImpl.fetchValue(ScannerImpl.java:839)
[ERROR]         at org.snakeyaml.engine.v2.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:362)
[ERROR]         at org.snakeyaml.engine.v2.scanner.ScannerImpl.checkToken(ScannerImpl.java:192)
[ERROR]         at org.snakeyaml.engine.v2.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:710)
[ERROR]         at org.snakeyaml.engine.v2.parser.ParserImpl.lambda$produce$1(ParserImpl.java:232)
[ERROR]         at java.base/java.util.Optional.ifPresent(Optional.java:178)
[ERROR]         at org.snakeyaml.engine.v2.parser.ParserImpl.produce(ParserImpl.java:232)
[ERROR]         at org.snakeyaml.engine.v2.parser.ParserImpl.peekEvent(ParserImpl.java:206)
[ERROR]         at org.snakeyaml.engine.v2.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
[ERROR]         at org.snakeyaml.engine.v2.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
[ERROR]         at org.snakeyaml.engine.v2.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:135)
[ERROR]         at org.snakeyaml.engine.v2.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:115)
[ERROR]         at org.snakeyaml.engine.v2.composer.Composer.composeScalarNode(Composer.java:244)
[ERROR]         at org.snakeyaml.engine.v2.composer.Composer.composeNode(Composer.java:206)
[ERROR]         at org.snakeyaml.engine.v2.composer.Composer.composeValueNode(Composer.java:364)
[ERROR]         at org.snakeyaml.engine.v2.composer.Composer.composeMappingChildren(Composer.java:343)
[ERROR]         at org.snakeyaml.engine.v2.composer.Composer.composeMappingNode(Composer.java:321)
[ERROR]         at org.snakeyaml.engine.v2.composer.Composer.composeNode(Composer.java:210)
[ERROR]         at org.snakeyaml.engine.v2.composer.Composer.next(Composer.java:162)
[ERROR]         at org.snakeyaml.engine.v2.api.Load$YamlIterator.next(Load.java:234)
[ERROR]         at io.fabric8.kubernetes.client.utils.Serialization.parseYaml(Serialization.java:252)
[ERROR]         at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:233)
[ERROR]         at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:399)
[ERROR]         at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:329)
[ERROR]         at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:311)
[ERROR]         at io.fabric8.kubernetes.client.Config.getExecCredentialFromExecConfig(Config.java:795)
[ERROR]         at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:751)
[ERROR]         at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:666)
[ERROR]         at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:286)
[ERROR]         at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:282)
[ERROR]         at io.quarkus.kubernetes.client.runtime.KubernetesClientUtils.createConfig(KubernetesClientUtils.java:18)
[ERROR]         at io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep.process(KubernetesClientBuildStep.java:20)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
```

### How to Reproduce?

Reproducer:

1. Check out https://github.com/aws-samples/aws-eks-quarkus-example 
2. Use Cloud 9 or EC2 instance to build (IAM role is necessary)
3. Migrate to Quarkus 3
4. Build the project

### Output of `uname -a` or `ver`

Linux ip-172-16-1-215.eu-west-1.compute.internal 4.14.305-227.531.amzn2.x86_64 #1 SMP Tue Feb 14 09:55:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 LTS OpenJDK Runtime Environment Corretto-17.0.4.8.1 (build 17.0.4+8-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.4.8.1 (build 17.0.4+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

Quarkus 3.0.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

My Kubernetes configuration:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://<endpoint>.gr7.eu-west-1.eks.amazonaws.com
  name: arn:aws:eks:eu-west-1:<id>:cluster/QuarkusEKSCluster
contexts:
- context:
    cluster: arn:aws:eks:eu-west-1:<id>:cluster/QuarkusEKSCluster
    user: arn:aws:eks:eu-west-1:<id>:cluster/QuarkusEKSCluster
  name: arn:aws:eks:eu-west-1:<id>:cluster/QuarkusEKSCluster
current-context: arn:aws:eks:eu-west-1:<id>:cluster/QuarkusEKSCluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-west-1:<id>:cluster/QuarkusEKSCluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - QuarkusEKSCluster
      - --role
      - arn:aws:iam::<id>:role/QuarkusEksStackStack-ClusterMastersRole9AA35625-1947DW8ZMSDGP
      command: aws
```

**Comment by geoand** [comment]
@cescoffier @maxandersen do you guys have any idea what could be causing this?

**Comment by cescoffier** [comment]
I believe we updated snake yaml (because of the cve). So, the behavior might be slightly different. 

I can't exclude a stricter yaml parsing. Typically values with : may need to be in quotes.

Also, we would need to check why the error message has User with an uppercase U while the config has a lower case u.

**Comment by smoell** [comment]
Found the problem, was not related to YAML parsing, but it was a permission problem, the IAM role wasn't able to assume another role.

**Comment by geoand** [comment]
Thanks for the update
