### ISSUE TITLE
Podman fails to build native on macOS

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#33188]
### Describe the bug

Podman 4.5.0 fails to build native on macOS ([longer output](https://gist.github.com/galderz/4ba6e81310f181d01fb2f1dc6dc3dbb5)):

```
/usr/bin/ld: cannot open output file /project/code-with-quarkus-1.0.0-SNAPSHOT-runner: Permission denied
collect2: error: ld returned 1 exit status
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:203)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.runLinkerCommand(NativeImageViaCC.java:151)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:718)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

### Output of `uname -a` or `ver`

Darwin m22 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

native-image 22.3.2.1-Final Mandrel Distribution (Java Version 17.0.7+7)

### Quarkus version or git rev

3.0.2.Final

### Additional information

Podman machine was started with:

```
$ podman machine init --rootful -m 8092 --cpus 4
```

FYI @n1hility @holly-cummins @tqvarnst

**Comment by galderz** [comment]
The issue is not specific to Mandrel. It also happens with the GraalVM CE image.

Also, the issue also happens with rootless podman.

**Comment by galderz** [comment]
Remove tests carried out to check permissions because command was wrong.

**Comment by galderz** [comment]
I think adding `--userns=keep-id -u=$(id -u):$(id -g)` as done by @zakkak in https://github.com/quarkusio/quarkus/issues/10637#issuecomment-666405112 might work.

Initially I was getting this:

```
$ podman run -it -v /Users/g/tmp/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar:/project --entrypoint /bin/bash quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
[quarkus@612e217ce0b4 project]$ ls -al
total 400
drwxr-xr-x.   4  501 games    128 May  8 07:32 .
dr-xr-xr-x.   1 root root      17 May  8 07:51 ..
-rw-r--r--.   1  501 games 408289 May  8 07:32 code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
drwxr-xr-x. 100  501 games   3200 May  8 07:32 lib
[quarkus@612e217ce0b4 project]$ touch /project/lala
touch: cannot touch '/project/lala': Permission denied
```

After adding those extra parameters:

```
$ podman run -it -v /Users/g/tmp/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar:/project --userns=keep-id -u=$(id -u):$(id -g) --entrypoint /bin/bash quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
bash-4.4$ ls -al /project/
total 400
drwxr-xr-x.   4 core games    128 May  8 07:32 .
dr-xr-xr-x.   1 root root      28 May  8 07:57 ..
-rw-r--r--.   1 core games 408289 May  8 07:32 code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
drwxr-xr-x. 100 core games   3200 May  8 07:32 lib
bash-4.4$ touch /project/lala
bash-4.4$ ls -al
total 400
drwxr-xr-x.   5 core games    160 May  8 07:57 .
dr-xr-xr-x.   1 root root      28 May  8 07:57 ..
-rw-r--r--.   1 core games 408289 May  8 07:32 code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
-rw-r--r--.   1 core games      0 May  8 07:57 lala
drwxr-xr-x. 100 core games   3200 May  8 07:32 lib
```
