### ISSUE TITLE
Using duration with hibernate and postgres interval leads to error in native mode

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#33206]
### Describe the bug

Using hibernate with duration, which now with hibernate 6.2 uses the postgres interval type leads to an error due to `PGInterval` not correctly registered for reflection:

```
Caused by: org.postgresql.util.PSQLException: Failed to create object for: interval.
	at org.postgresql.jdbc.PgConnection.getObject(PgConnection.java:760)
	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:3020)
	at io.agroal.pool.wrapper.ResultSetWrapper.getObject(ResultSetWrapper.java:472)
	at io.hypersistence.utils.hibernate.type.interval.PostgreSQLIntervalType.get(PostgreSQLIntervalType.java:40)
	at io.hypersistence.utils.hibernate.type.interval.PostgreSQLIntervalType.get(PostgreSQLIntervalType.java:24)
	at io.hypersistence.utils.hibernate.type.ImmutableType.nullSafeGet(ImmutableType.java:97)
	at org.hibernate.type.internal.UserTypeSqlTypeAdapter$ValueExtractorImpl.extract(UserTypeSqlTypeAdapter.java:110)
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.readCurrentRowValues(JdbcValuesResultSetImpl.java:262)
	... 87 more
Caused by: java.lang.NoSuchMethodException: org.postgresql.util.PGInterval.<init>()
	at java.base@17.0.7/java.lang.Class.getConstructor0(DynamicHub.java:3585)
	at java.base@17.0.7/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754)
	at org.postgresql.jdbc.PgConnection.getObject(PgConnection.java:739)
	... 94 more
```

### Expected behavior

This probably should work out of the box as it is now in the standard hibernate implementation.

### GraalVM version (if different from Java)

Mandrel 22.3.2.1

### Quarkus version or git rev

3.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradlew 8.1.1

**Comment by yrodiere** [comment]
@marko-bekhta this might be a good first issue, do you mind having a look?

I believe the fix will have to be implemented in `io.quarkus.jdbc.postgresql.deployment.PostgreSQLJDBCReflections`.

If necessary, this should provide a good introduction of the concepts at play:

* https://quarkus.io/guides/getting-started
* https://quarkus.io/guides/building-native-image
* https://quarkus.io/guides/building-my-first-extension

And this is more in-depth: https://quarkus.io/guides/writing-extensions

If you need help or advice, feel free to ping me on Zulip (probably on the Quarkus Zulipchat on the `dev` stream, so that others can chime in).

**Comment by yrodiere** [comment]
Also, thank you @joggeli34  for the reproducer :)
