### ISSUE TITLE
Vertx race condition may not initialise OpenTelemetry

### ISSUE THREAD

**Issue by Adelrisk** [quarkusio/quarkus#33285]
### Describe the bug

I am migrating a project from 2.16.6 to 3.02, and seem to encounter a race condition when running the tests, roughly every second execution. Whether using maven or intellij, the execution of the tests will pause/stop (but not terminate) when the error occurs, before any of the tests are actually executed.

### Expected behavior

I would expect the normal execution of my tests. (Side note: probably 3 in 10 tests pass :cry: )

### Actual behavior

None of the tests run. Ther runner seems to pause. The last output is the following stacktrace:

```bash
2023-05-10 22:16:31,741 DEBUG [io.net.uti.ResourceLeakDetectorFactory] (vert.x-eventloop-thread-1) Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@4a98cd5b
2023-05-10 22:16:31,769 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-1) Uncaught exception received by Vert.x: java.lang.NullPointerException: Cannot invoke "io.vertx.core.spi.tracing.VertxTracer.sendRequest(io.vertx.core.Context, io.vertx.core.spi.tracing.SpanKind, io.vertx.core.tracing.TracingPolicy, Object, String, java.util.function.BiConsumer, io.vertx.core.spi.tracing.TagExtractor)" because "this.delegate" is null
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.OpenTelemetryVertxTracingFactory$Delegator.sendRequest(OpenTelemetryVertxTracingFactory.java:71)
	at io.vertx.core.http.impl.Http1xClientConnection.beginRequest(Http1xClientConnection.java:273)
	at io.vertx.core.http.impl.Http1xClientConnection.access$600(Http1xClientConnection.java:108)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.writeHead(Http1xClientConnection.java:556)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.writeHead(Http1xClientConnection.java:549)
	at io.vertx.core.http.impl.HttpClientRequestImpl.doWrite(HttpClientRequestImpl.java:501)
	at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:471)
	at io.vertx.core.http.impl.HttpClientRequestImpl.end(HttpClientRequestImpl.java:417)
	at io.vertx.core.http.impl.HttpClientRequestImpl.end(HttpClientRequestImpl.java:411)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$handleCreateRequest$5(HttpContext.java:485)
	at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.Promise.complete(Promise.java:66)
	at io.vertx.ext.web.client.impl.HttpContext.handleSendRequest(HttpContext.java:559)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:375)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:362)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:329)
	at io.vertx.ext.web.client.impl.HttpContext.sendRequest(HttpContext.java:232)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$handleCreateRequest$6(HttpContext.java:491)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.http.impl.HttpClientImpl.lambda$null$5(HttpClientImpl.java:683)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
	at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
	at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:164)
	at io.vertx.core.impl.future.PromiseImpl.onComplete(PromiseImpl.java:23)
	at io.vertx.core.http.impl.Http1xClientConnection.createStream(Http1xClientConnection.java:1270)
	at io.vertx.core.http.impl.HttpClientImpl.lambda$doRequest$6(HttpClientImpl.java:666)
	at io.vertx.core.net.impl.pool.Endpoint.lambda$getConnection$0(Endpoint.java:52)
	at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:162)
	at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:123)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool$LeaseImpl.emit(SimpleConnectionPool.java:704)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool$ConnectSuccess$2.run(SimpleConnectionPool.java:338)
	at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:56)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:245)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.lambda$connect$2(SimpleConnectionPool.java:257)
	at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint.lambda$connect$2(SharedClientHttpStreamEndpoint.java:102)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
	at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.Promise.complete(Promise.java:66)
	at io.vertx.core.net.impl.NetClientImpl.lambda$connected$9(NetClientImpl.java:330)
	at io.vertx.core.net.impl.VertxHandler.setConnection(VertxHandler.java:82)
	at io.vertx.core.net.impl.VertxHandler.handlerAdded(VertxHandler.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:195)
	at io.vertx.core.net.impl.NetClientImpl.connected(NetClientImpl.java:332)
	at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal2$3(NetClientImpl.java:294)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.net.impl.ChannelProvider.connected(ChannelProvider.java:172)
	at io.vertx.core.net.impl.ChannelProvider.lambda$handleConnect$0(ChannelProvider.java:155)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

Run the tests in the reproducer (within IntelliJ?): https://github.com/Adelrisk/quarkus-reproducer-33285

Either the first or second execution should be sufficient.

### Output of `uname -a` or `ver`

Linux ffs 6.1.0-8-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.25-1 (2023-04-22) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "18.0.2-ea" 2022-07-19

### Quarkus version or git rev

3.0.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by brunobat** [comment]
Yes, without a reproducer it will be hard...
This is happening because vert.x is initialising before the OTel bean is built. Some hints...
Try to inject openTelemetry on your tests, to force it.
Not related but you have the wiremock dependency on compile time, not just tests.
Why are you using this?

**Comment by Adelrisk** [comment]
> Yes, without a reproducer it will be hard... 

Yeah, I know. I'll think I can put some effort into it.

> This is happening because vert.x is initialising before the OTel bean is built. Some hints... Try to inject openTelemetry on your tests, to force it.

NPE was raised for the second execution of a single test class which has `OpenTelemetry` injected.

> Not related but you have the wiremock dependency on compile time, not just tests. Where are you using this?

Not productive. Seems to have slipped in. Thank you! (I can confirm, this is unrelated.)

**Comment by Adelrisk** [comment]
I could reproduce the bug with this reproducer: https://github.com/Adelrisk/quarkus-reproducer-33285

**Comment by brunobat** [comment]
Strange... It works on my machine:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.222 s
[INFO] Finished at: 2023-05-11T11:55:56+01:00
```
Devmode works, test on devmode work as well.

My setup:
````
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /Users/bbaptist/.sdkman/candidates/maven/current
Java version: 17.0.4.1, vendor: Eclipse Adoptium, runtime: /Users/bbaptist/.sdkman/candidates/java/17.0.4.1-tem
Default locale: en_PT, platform encoding: UTF-8
OS name: "mac os x", version: "13.3.1", arch: "aarch64", family: "mac"
````
I do get an unrelated error, though: 
```
2023-05-11 11:52:36,598 WARN  [org.hib.met.int.EntityRepresentationStrategyPojoStandard] (JPA Startup Thread) HHH000305: Could not create proxy factory for:org.acme.domain.Document: org.hibernate.HibernateException: Getter methods of lazy classes cannot be final: org.acme.domain.Document#getCreatedAt
````
Do you have some particular steps that I should follow?

**Comment by Adelrisk** [comment]
I just ran `./mvnw clean test` and it failed first try (as described). My suggestion: try again. There is some sort of race condition, because it doesn't fail every time.

I just ran that command multiple times an (in order):
- fail
- success
- fail
- success
- success

When I get the error, it actually occurs before that warning is emitted (as observed in the successful runs)

```
[INFO] Running org.acme.GreetingResourceTest                                                                                                                                                                                                
2023-05-11 13:21:34,093 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-21) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first                            2023-05-11 13:21:35,070 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-21) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)                                                                           
2023-05-11 13:21:35,072 INFO  [org.tes.DockerClientFactory] (build-21) Docker host IP address is localhost                                                                                                                                  
2023-05-11 13:21:35,102 INFO  [org.tes.DockerClientFactory] (build-21) Connected to docker:                                                                                                                                                 
  Server Version: 20.10.24+dfsg1                                                                                                                                                                                                            
  API Version: 1.41                                                                                                                                                                                                                           Operating System: Debian GNU/Linux 12 (bookworm)                                                                                                                                                                                          
  Total Memory: 23886 MB                                                                                                                                                                                                                    
2023-05-11 13:21:35,141 INFO  [org.tes.uti.ImageNameSubstitutor] (build-21) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitut
or')                                                                                                                                                                                                                                        
2023-05-11 13:21:35,192 INFO  [org.tes.DockerClientFactory] (build-21) Checking the system...                                                                                                                                               
2023-05-11 13:21:35,193 INFO  [org.tes.DockerClientFactory] (build-21) ✔︎ Docker server version should be at least 1.6.0                                                                                                                     
2023-05-11 13:21:35,219 INFO  [io.qua.oid.dep.dev.key.KeycloakDevServicesProcessor] (build-7) Using Quarkus powered Keycloak distribution                                                                                                   
2023-05-11 13:21:35,305 INFO  [🐳 .io/.0.2]] (build-7) Creating container for image: quay.io/keycloak/keycloak:21.0.2                                                                                                                       
2023-05-11 13:21:35,307 INFO  [io.qua.sma.openapi] (build-16) OpenAPI JSON saved: /home/neil/_/projects/mgov4eu/code-with-quarkus/./openapi.json                                                                                            
2023-05-11 13:21:35,311 INFO  [io.qua.sma.openapi] (build-16) OpenAPI YAML saved: /home/neil/_/projects/mgov4eu/code-with-quarkus/./openapi.yaml                                                                                            
2023-05-11 13:21:35,365 INFO  [🐳 .io/postgres:14]] (build-21) Creating container for image: docker.io/postgres:14                                                                                                                          
2023-05-11 13:21:35,372 INFO  [🐳 .3.4]] (build-7) Creating container for image: testcontainers/ryuk:0.3.4                                                                                                                                  
2023-05-11 13:21:35,547 INFO  [🐳 .io/postgres:14]] (build-21) Reusing container with ID: ddbf39f91bca3da8a82d27c99e486f21085acc8ad70452ac5c87ea919938208a and hash: 7db76d3f0bbef540a4453d4d5f4157518f524d87
2023-05-11 13:21:35,548 INFO  [🐳 .io/postgres:14]] (build-21) Reusing existing container (ddbf39f91bca3da8a82d27c99e486f21085acc8ad70452ac5c87ea919938208a) and not creating a new one                                                     
2023-05-11 13:21:35,689 INFO  [🐳 .io/postgres:14]] (build-21) Container docker.io/postgres:14 started in PT0.467260912S                                                                                                                    
2023-05-11 13:21:35,690 INFO  [io.qua.dev.pos.dep.PostgresqlDevServicesProcessor] (build-21) Dev Services for PostgreSQL started.                                                                                                           
2023-05-11 13:21:35,691 INFO  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-21) Dev Services for the default datasource (postgresql) started - container ID is ddbf39f91bca                                                    
2023-05-11 13:21:36,036 INFO  [🐳 .3.4]] (build-7) Container testcontainers/ryuk:0.3.4 is starting: 9c0ef4a6254872181ef507ecca2937033e3803156a13da9fe8c6f11f02712c16                                                                        
2023-05-11 13:21:36,799 INFO  [🐳 .3.4]] (build-7) Container testcontainers/ryuk:0.3.4 started in PT1.425936691S                                                                                                                            
2023-05-11 13:21:39,133 INFO  [🐳 .io/.0.2]] (build-7) Container quay.io/keycloak/keycloak:21.0.2 is starting: 9db9f025c995c4dc8809be36531cfd92586201798ba01299bca2b8585a93e56b                                                             
2023-05-11 13:21:50,474 INFO  [🐳 .io/.0.2]] (build-7) Container quay.io/keycloak/keycloak:21.0.2 started in PT15.254307667S                                                                                                                
2023-05-11 13:21:52,463 INFO  [io.qua.oid.dep.dev.key.KeycloakDevServicesProcessor] (build-7) Dev Services for Keycloak started.                                                                                                            
2023-05-11 13:21:54,443 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-1) Uncaught exception received by Vert.x: java.lang.NullPointerException: Cannot invoke "io.vertx.core.spi.tracing.VertxTracer.sendRequest(io.
vertx.core.Context, io.vertx.core.spi.tracing.SpanKind, io.vertx.core.tracing.TracingPolicy, Object, String, java.util.function.BiConsumer, io.vertx.core.spi.tracing.TagExtractor)" because "this.delegate" is null                        
        at io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.OpenTelemetryVertxTracingFactory$Delegator.sendRequest(OpenTelemetryVertxTracingFactory.java:71)
```

**Comment by gsmet** [comment]
FWIW, we had this sort of issues a few times when we were recording (as in bytecode recording) initialization stuff relatively randomly: sometimes, the build steps were not executed in the right order and we ended up with the bytecode being executed in an order that doesn't fit us. Usually, what we do is consuming a build item produced by the recording build step we want to execute first in the build step we want to execute second.

I wouldn't be surprised if it's a similar issue but I haven't looked at the code so I might be completely mistaken.

**Comment by brunobat** [comment]
5 in 5 successes... Maybe my machine is to fast.
Will try on a slower one.

**Comment by brunobat** [comment]
I was able to reproduce the issue once, in a slower intel based machine.
The problem relates to the fact that we have set a consumer to the `VertxOptions` before OTel is built: https://github.com/quarkusio/quarkus/blob/15575ef5d7ec44973176b288c1a18341bf6a6803/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/InstrumentationRecorder.java#LL37C54-L37C54

Once OTel is available, we set the delegate with the tracers using the right OTel SDK instance: https://github.com/quarkusio/quarkus/blob/15575ef5d7ec44973176b288c1a18341bf6a6803/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/InstrumentationRecorder.java#L44

It happens that in this small meantime, someone is performing a REST client HTTP call somewhere, thus triggering the error.
Will need to think on how to solve this...

**Comment by Adelrisk** [comment]
Thanks for your efforts to isolate it so quickly. Race conditions are the embodiment of "it works on my machine"

Note to self: finally, really apply for a newer work laptop. :sweat_smile:

**Comment by martaisty** [comment]
👍  Experiencing the same issue with Quarkus 3.0.0.Final

**Comment by ikos23** [comment]
I just raised a bug, probably the same as this one:
https://github.com/quarkusio/quarkus/issues/33669 

And only after that found this one.
