### ISSUE TITLE
Kafka consumer using kotlin coroutines throws ClassCastException

### ISSUE THREAD

**Issue by scherrsasrf** [quarkusio/quarkus#33308]
### Describe the bug

We are in the process of switching from reactive programming (using Uni/Multi) to a more simple imperative design using coroutines because our use cases are easier to implement that way. 
When using coroutines with `@Incoming` in smallrye messaging a ClassCastException exception is thrown. The same method without in reactive style without coroutines/suspend works without a problem.
Broken coroutine version:
```kotlin
@Incoming("contents-incoming")
suspend fun consumeContents(record: Record<ContentMessageKey, Content?>) {
    val value = record.value()
    /* TODO */
}
```

Working reactive version:
```kotlin
@Incoming("contents-incoming")
fun consumeContents(record: Record<ContentMessageKey, Content?>): Uni<out Any> {
    val value = record.value()
    return uni { /* TODO */ }
}
```

### Expected behavior

Coroutine version of the consumer method processes the kafka message without error (like the reactive version)

### Actual behavior

Throws the following exception
```
WARN: SRMSG18228: A failure has been reported for Kafka topics '[contents]'
java.lang.ClassCastException: class org.apache.avro.generic.GenericData$Record cannot be cast to class com.redacted.domain.egest.Content (org.apache.avro.generic.GenericData$Record is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6d40a2b; com.redacted.domain.egest.Content is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @274f51ad)
	at com.redacted.api.extractor.ContentConsumer.consumeContents(ContentConsumer.kt:31)
	at com.redacted.api.extractor.ContentConsumer_ClientProxy.consumeContents(Unknown Source)
	at com.redacted.api.extractor.ContentConsumer_SmallRyeMessagingInvoker_consumeContents_494b1d69daf42c579ff2208c00abd2c78c487910.invokeBean(Unknown Source)
	at io.quarkus.smallrye.reactivemessaging.runtime.kotlin.AbstractSubscribingCoroutineInvoker$invoke$1.invokeSuspend(AbstractSubscribingCoroutineInvoker.kt:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.quarkus.smallrye.reactivemessaging.runtime.kotlin.VertxDispatcher.dispatch$lambda$0(VertxDispatcher.kt:17)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

Consumer method:
```kotlin
@Incoming("contents-incoming")
suspend fun consumeContents(record: Record<ContentMessageKey, Content?>) {
    val value = record.value()
    /* TODO */
}
```

application.properties:
```
mp.messaging.incoming.contents-incoming.enabled=true
mp.messaging.incoming.contents-incoming.topic=contents
mp.messaging.incoming.contents-incoming.connector=smallrye-kafka
mp.messaging.incoming.contents-incoming.auto.offset.reset=earliest
mp.messaging.incoming.contents-incoming.key.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
mp.messaging.incoming.contents-incoming.value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
mp.messaging.incoming.contents-incoming.max.poll.records=1
```

### Output of `uname -a` or `ver`

Darwin MBP-von-Sascha.fritz.box 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

### Additional information

Might be user error or missing/wrong configuration. It's somewhat difficult to create a minimal reproducable setup. I'll try if necessary.

**Comment by geoand** [comment]
Lovely...

**Comment by geoand** [comment]
Any chance you can add a sample of the working Mutiny version vs the non-working Kotlin version?

**Comment by scherrsasrf** [comment]
@geoand Something like this: https://github.com/scherrsasrf/quarkus-issue-33308
POSTing to http://localhost:8080/movies a JSON like this:
```
{
	"title": "test-movie",
	"year": 1990
}
```
Prints the following to the console:
`Received 'test-movie' from 1990`

There's also a commented out suspend version in this file: https://github.com/scherrsasrf/quarkus-issue-33308/blob/main/src/main/kotlin/org/acme/kafka/KotlinConsumer.kt

Trying to start with that code already prints the following message, indicating that something different is happening suddenly:
```ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.IllegalArgumentException: The attribute `value.deserializer` on connector 'smallrye-kafka' (channel: movies-from-kafka) must be set```

We use `io.confluent.kafka.serializers.KafkaAvroDeserializer` in our specific case, which then results in the reported error.
I hope this helps :)

**Comment by geoand** [comment]
I checked this real quick and it I am pretty sure we can fix it. I'll take a closer look later on todat or tomorrow.
