### ISSUE TITLE
null pointer in panache 'list' query with like clause

### ISSUE THREAD

**Issue by sjaakd** [quarkusio/quarkus#33310]
### Describe the bug

```java
@Entity
@Table(schema = "DINO_DBA", name = "GDW_LKS_CPT_RD")
@NamedQuery( name = "GdwLksCptRd.search", query = "from GdwLksCptRd p where p.broId like :criterion" )
public class GdwLksCptRd extends PanacheEntityBase implements Serializable {

    private static final long serialVersionUID = -2816021106611026573L;

    @Id
    @Column(name = "OBJECT_ID")
    private Long objectId;

    @Column( name = "BRO_ID" )
    private String broId;
}

```

```java
    List<GdwLksCptRd> rs1 = GdwLksCptRd.list( "broId like ?1", criterion + "%");
```

Leads to:

```
16:02:40 WARN  [nl.bro.mic.com.rs.pro.DefaultExceptionProvider] (executor-thread-4) null: java.lang.NullPointerException
	at java.base/java.lang.String$CaseInsensitiveComparator.compare(String.java:1224)
	at java.base/java.lang.String$CaseInsensitiveComparator.compare(String.java:1218)
	at java.base/java.util.TreeMap.getEntryUsingComparator(TreeMap.java:374)
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:343)
	at java.base/java.util.TreeMap.get(TreeMap.java:277)
	at org.hibernate.dialect.function.SQLFunctionRegistry.findSQLFunction(SQLFunctionRegistry.java:45)
	at org.hibernate.hql.internal.ast.util.SessionFactoryHelper.findSQLFunction(SessionFactoryHelper.java:386)
	at org.hibernate.hql.internal.ast.tree.IdentNode.getDataType(IdentNode.java:371)
	at org.hibernate.hql.internal.ast.HqlSqlWalker.lookupProperty(HqlSqlWalker.java:680)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.addrExpr(HqlSqlBaseWalker.java:5097)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.expr(HqlSqlBaseWalker.java:1315)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.exprOrSubquery(HqlSqlBaseWalker.java:4797)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.comparisonExpr(HqlSqlBaseWalker.java:4261)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2180)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.whereClause(HqlSqlBaseWalker.java:841)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:635)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:339)
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:287)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:276)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:192)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:144)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:112)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:73)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:162)
	at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:636)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:748)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:114)
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.createQuery(TransactionScopedSession.java:357)
	at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:547)
	at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:65)
	at org.hibernate.Session_5b93bee577ae2f8d76647de04cfab36afbf52958_Synthetic_ClientProxy.createQuery(Unknown Source)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createBaseQuery(CommonPanacheQueryImpl.java:361)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createQuery(CommonPanacheQueryImpl.java:316)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.list(CommonPanacheQueryImpl.java:267)
	at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.list(PanacheQueryImpl.java:149)

```

Same result for executing the query with `@NamedQuery` as arg:

```java
GdwLksCptRd.find( "GdwLksCptRd.search", Parameters.with( "criterion", criterion + "%" ) ).range( 0, 29 ).list()
```

However executing a normal JPA query works as expected.

```java
TypedQuery<GdwLksCptRd> query1 = em.createNamedQuery( "GdwLksCptRd.search", GdwLksCptRd.class ); query1.setParameter( "criterion", criterion + "%" );
List<GdwLksCptRd> rs1 = query1.getResultList();
```

### Output of `java -version`

openjdk 11

### Quarkus version or git rev

2.16.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by gsmet** [comment]
Wondering if this is a Hibernate ORM issue. /cc @yrodiere @Sanne

**Comment by loicmathieu** [comment]
Yes, named query in a PanacheQL query (the simplified JPQL that is accepted by all Panache methods) must start with `# ` so we can distinguished them from simplified queries like `Person.find("name", "John Doe")`.

@sjaakd can you confirm that it's working ?

**Comment by gsmet** [comment]
Hmmm, if it fixes it, we definitely need to improve to provide a proper error message and not a NPE.

**Comment by sjaakd** [comment]
Thanks guys. I'll check that one asap.. Need to rewrite quite some code to test again, so will need some time.  Could it be so simple? 

I tried querying directly: 
`  List<GdwLksCptRd> rs1 = GdwLksCptRd.list( "broId like ?1", criterion + "%");`  like is suggested [here](https://stackoverflow.com/questions/72408776/how-to-do-a-partial-search-in-hibernate-panache, although that's a repo example).  It doesn't use the named query, but a query string leading to the same result. 

Yes.. the NPE put me on a wrong track 😄 ..

**Comment by Sanne** [comment]
> Hmmm, if it fixes it, we definitely need to improve and provide a proper error message and not a NPE.

Definitely. I'll track the ORM side - however this issue only applies to ORM5, as ORM6 treats functions in an entirely different way.

On the Panache side, it would be nice to detect that the simplified query is invalid and it happens to refer to a named query - not sure if we can do better.

**Comment by sjaakd** [comment]
@Sanne thanks.. 

In my case I have a number of quite similar objects that share all the same  `MappedSuperclass`. This works quite nice for named queries. I tried to rewrite this to Panache to test this issue again . 

So I've got a number of maps handling a function that calls this named query. This is how it looked like:

```java
  private static final List<BiFunction<EntityManager, String, List<ObjectDto>>> DINO_OBJECT_QUERIES = List.of(
        (e, criterion) -> objectQuery( e, "GdwLksGboRd.search", criterion ),
        (e, criterion) -> objectQuery( e, "GdwLksAboRd.search", criterion ),
        (e, criterion) -> objectQuery( e, "GdwLksGsoRd.search", criterion )
        // etc
      );
```

and then:

```java
    private static List<ObjectDto> objectQuery(EntityManager em, String queryName, String criterion ) {
        TypedQuery<ObjectDto> query = em.createNamedQuery( queryName, ObjectDto.class );
        query.setParameter( "criterion", criterion + "%" );
        query.setMaxResults( MAX_SEARCH_RESULTS_PER_DATA_TYPE );
        return query.getResultList();
    }
```

```
@NamedQuery(
    name = "GdwLksBhrGRd.search",
    query = "select new nl.bro.microservices.dlp.model.common.ObjectDto( p.broId, p.geometry, 'SOIL', 'BRO', 'bhrg' ) "
        + "from GdwLksBhrGRd p where p.broId like :criterion order by p.broId"
)
```

Now.. I want to rewrite this using panache and panache projection

So:

```java
    private static final List<Function< String, List<ObjectDto>>> DINO_OBJECT_QUERIES = List.of(
        criterion -> objectQuery( GdwLksGboRd.find("#GdwLksGboRd.search",  Parameters.with( "criterion", criterion + "%" ) ) ),
        criterion -> objectQuery( GdwLksAboRd.find("#GdwLksAboRd.search",  Parameters.with( "criterion", criterion + "%" ) ) ),
        criterion -> objectQuery( GdwLksGsoRd.find("#GdwLksGsoRd.search",  Parameters.with( "criterion", criterion + "%" ) ) ),
   //: 
```

```java
    private static <T extends PanacheEntityBase>  List<ObjectDto> objectQuery( PanacheQuery<T> query  ) {
        return query.range( 0, MAX_SEARCH_RESULTS_PER_DATA_TYPE ).project( ObjectDto.class ).list();
    }
```` 

example query:

```java 
@NamedQuery(
    name = "GdwLksBhrGRd.search",
    query = "select  p.broId, p.geometry, 'SOIL', 'BRO', 'bhrg'  "
        + "from GdwLksBhrGRd p where p.broId like :criterion order by p.broId"
)
```

Only to find out that Panache does not support `@NamedQuery` icw projection 😢 ..  Note: cannot derive this from the documentation, but that could be me (not such a good reader).  I always assumed there would be a performance gain by using named queries. Guess I've got to rewrite stuff a bit further..

**Comment by Sanne** [comment]
@FroMage ^

**Comment by sjaakd** [comment]
Happy to be useful 😄 .  

Wrt to Oracle: we are possibly moving away from Oracle in the future. License costs / opensource vs closed source etc.

In short, it comes down what you consider to be abstraction. I think an ORM should provide database abstraction, not needing a dao, but my experience is otherwise. I try to encourage to use as much as standard SQL as possible in the teams. I just recently discovered rider-cdi and I really like it in combination with h2 and Quarkus. With a few annotations you setup your test data. 

Keep up the good work here.. Its appreciated 👍 .

BTW: If you want to close the issue that's ok for me. I leave that up to you. My issues are handled.

**Comment by FroMage** [comment]
So, this issue turns out to have many parts:

- HQL parsing issue causing an NPE: https://hibernate.atlassian.net/browse/HHH-16609
- Using a named query in `find()` without its leading `#` sign: we could detect that at runtime and produce a helpful warning before we let it pass to ORM, I guess. Or throw. Or do it at build time…
- Projection of named queries: we don't support it, but frankly I don't see why not. Probably it's just that nobody every asked for it, but I don't see technical limitations.
- The `project()` method is very badly documented in javadoc. The guide is a bit better https://quarkus.io/guides/hibernate-orm-panache#query-projection but doesn't really explain it all.
- "The next point is that Panache will not allow me to use string literals in the "new Object" in projection, like this:" what's your error? I don't see why Panache would be involved in that one.
- "I cannot use the flexibility that the @NamedQuery offers assigning different query parameters". Can you clarify? I don't understand the issue.

Thanks for your feedback, this is very helpful.

**Comment by yrodiere** [comment]
FWIW https://hibernate.atlassian.net/browse/HHH-16609 has been fixed upstream, so the originally reported problems will be fixed in Quarkus as soon as Hibernate ORM 5.6.16 gets released and we upgrade in Quarkus 2.16.

@FroMage can you confirm I can close this ticket as soon as the upstream issue in ORM gets fixed in Quarkus, or do you need to keep it open to track those other problems you listed? I'd recommend opening another issue, but it's up to you.

**Comment by FroMage** [comment]
Most of these points I summarised are taken care of by https://github.com/quarkusio/quarkus/pull/33902 if you want to review it.

**Comment by sjaakd** [comment]
Hi guys,

Although closed I see I missed some questions. Sorry. For that

"The next point is that Panache will not allow me to use string literals in the "new Object" in projection, like this:" what's your error? I don't see why Panache would be involved in that one.

-> Panache is not involved here. It's just a feature that you get with standard named queries.. Just like this

```
@Entity
@Table(schema = "DINO_DBA", name = "GDW_LKS_SFR_RD")
@NamedQuery(
    name = "GdwLksSfrRd.search",
    query = "select new nl.bro.microservices.dlp.model.common.ObjectDto( p.broId, p.geometry, 'SOIL', 'BRO', 'sfr' ) "
        + "from GdwLksSfrRd p where p.broId like :criterion order by p.broId"
)
``` 
Note that you can set the constructor arguments with a literal? I miss that kind of functionality in Panache. 

"I cannot use the flexibility that the @NamedQuery offers assigning different query parameters". Can you clarify? I don't understand the issue.

-> I'm lost here myself as well 😢

**Comment by FroMage** [comment]
Oh, OK, so you'd like to use literal values for some of the parameters of your projection constructor, that don't correspond to selected columns?

Perhaps some extra optional annotation parameter on `@ProjectedFieldName(defaultValue = 'SOIL')` or `literal` or something? I'm not sure if we want to support Java literals or DB literals (which are probably of a different set of types).

That could be useful, could you open an issue for that please? This way we can see if more people would find this useful.

Thanks.

**Comment by FroMage** [comment]
Yes, true. Though this would not use HQL projection, right?
