### ISSUE TITLE
Unable to build native image with Tika

### ISSUE THREAD

**Issue by zaretskyy** [quarkusio/quarkus#3342]
**Describe the bug**
Build fails while running multistage docker build with 

```
Error: Unsupported method sun.java2d.DefaultDisposerRecord.invokeNativeDispose(long, long) is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Call path from entry point to sun.java2d.DefaultDisposerRecord.invokeNativeDispose(long, long): 
	at sun.java2d.DefaultDisposerRecord.invokeNativeDispose(DefaultDisposerRecord.java)
	at sun.java2d.DefaultDisposerRecord.dispose(DefaultDisposerRecord.java:42)
	at sun.java2d.Disposer.run(Disposer.java:151)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:145)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------
```

**Expected behavior**
Build succeds

**Actual behavior**
Build fails

**To Reproduce**
1. Download https://zarets.egnyte.com/dl/zHkzBNRM4a
2. Extract
3. Run `docker build -f src/main/docker/Dockerfile.multistage -t quarkus-quickstart/getting-started .` in extracted dir
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Linux azar-Latitude-E5470 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
 - Quarkus version or git rev: 
Created using
```
mvn io.quarkus:quarkus-maven-plugin:0.19.1:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
```

**Comment by kenfinnigan** [comment]
Can you take a look @sberyozkin

**Comment by sberyozkin** [comment]
@zaretskyy thanks for reporting this issue. Can you please try the latest Quarkus release ? The Tika extension there adds a build item requesting a JNI capability. By the way, the java version also looks old, GraalVM 19.0.0 was rebased against 212, while the latest Quarkus uses GraalVM 19.1.1.
Let me know please how it goes

**Comment by sberyozkin** [comment]
@zaretskyy Hi, I'd like to close this issue. Have you had a chance to confirm the JNI issue has gone ?

**Comment by zaretskyy** [comment]
@sberyozkin yes sorry for late reply it works on quarkus 0.20

**Comment by sberyozkin** [comment]
@zaretskyy np, thanks for the confirmation
