### ISSUE TITLE
Error "No current injection point found" when using a ConfigMapping on an onStartup method

### ISSUE THREAD

**Issue by sauljabin** [quarkusio/quarkus#33449]
### Describe the bug

I'm using quarkus 3, and I'm receiving a java.lang.IllegalStateException on this class:

```
import io.quarkus.runtime.StartupEvent;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;

@ApplicationScoped
public class Bootstrapper {
    void onStartup(@Observes StartupEvent startupEvent, MyConfig myConfig) {
        System.out.println(myConfig);
    }
}
```

This is my config:
```

import io.smallrye.config.ConfigMapping;

@ConfigMapping(prefix = "my.config")
public interface MyConfig {

    int value1();

    String value2();
    
}
```

My properties:

```
my.config.value1=3
my.config.value2=hola
```

This is the exception:

```
2023-05-15 12:12:58,768 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.IllegalStateException: No current injection point found               
        at io.quarkus.arc.runtime.ConfigMappingCreator.create(ConfigMappingCreator.java:24)                                                                                                                    
        at io.quarkus.arc.BeanCreator.create(BeanCreator.java:24)                                                                                                                                              
        at org.acme.MyConfig_3e7170390fa36b5ce4b4b6020acce65de972ca9e_Synthetic_Bean.createSynthetic(Unknown Source)                                                                                           
        at org.acme.MyConfig_3e7170390fa36b5ce4b4b6020acce65de972ca9e_Synthetic_Bean.doCreate(Unknown Source)                                                                                                  
        at org.acme.MyConfig_3e7170390fa36b5ce4b4b6020acce65de972ca9e_Synthetic_Bean.create(Unknown Source)                                                                                                    
        at org.acme.MyConfig_3e7170390fa36b5ce4b4b6020acce65de972ca9e_Synthetic_Bean.get(Unknown Source)                                                                                                       
        at org.acme.MyConfig_3e7170390fa36b5ce4b4b6020acce65de972ca9e_Synthetic_Bean.get(Unknown Source)                                                                                                       
        at org.acme.Bootstrapper_Observer_onStartup_351d904331422896e93db19aa6f41b7621d40a12.notify(Unknown Source)                                                                                            
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)                                                                                                                          
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)                                                                                                                                   
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)                                                                                                                                               
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)                                                                                                                         
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)                                                                                                                      
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)                                                                                                
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)                                                                                                  
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)                                                                                                                                           
        at io.quarkus.runtime.Application.start(Application.java:101)                                                                                                                                          
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)                                                                                                            
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)                                                                                                                                                     
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)                                                                                                                                                     
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)                                                                                                                                                    
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)                                                                                                                                                
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                      
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)                                                                                                    
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                            
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)                                                                                                                                          
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)                                                                                                                     
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

I want to eagerly instantiate a @ConfigMapping like this:

```
void onStartup(@Observes StartupEvent startupEvent, MyConfig myConfig) {
        System.out.println(myConfig);
}
```

Instead of using @Inject or a constructor.

I expected this https://quarkus.io/guides/cdi-reference#startup_event

### Actual behavior

It is not possible to inject a @ConfigMapping into an onStartup method, quarkus says "No current injection point found"

### How to Reproduce?

1. Create a new project with the scaffold
2. Create a ConfigMap like this:
```
@ConfigMapping(prefix = "my.config")
public interface MyConfig {
    int value1();
    String value2();
}
```
3. Setup the application.properties:
```
my.config.value1=3
my.config.value2=hello
```
4. Eagerly inject it by parameters in another bean:
```
void onStartup(@Observes StartupEvent startupEvent, MyConfig myConfig) {
        System.out.println(myConfig);
}
```

### Output of `uname -a` or `ver`

6.2.9-060209-generic

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.0.2

### Additional information

If you inject the config map by constructor or using @Inject it works well, this only happens injecting by parameter at `onStartup` method

P.S. This was originally posted as a [StackOverflow question](https://stackoverflow.com/q/76256554/2504224).

**Comment by mkouba** [comment]
I think that the way the [ConfigMappingCreator](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/ConfigMappingCreator.java#L22) obtains the `InjectionPoint` metadata does not work well together with observer injection points.

It should help if the synthetic bean defines a synthetic injection point for `InjectionPoint` metadata. It also seems that we handle the current IP metadata differently for regular injection points of a `@Dependent` synthetic bean.

In any case, it's a bug.
