### ISSUE TITLE
Kotlin dev mode throw "Unable to invoke Kotlin compiler. java.lang.NoSuchMethodError : 'void org.jetbrains.kotlin.fir.extensions.FirExtensionRegistrar$Companion.registerExtension(com.intellij.openapi.project.Project, org.jetbrains.kotlin.fir.extensions.FirExtensionRegistrar)'"

### ISSUE THREAD

**Issue by miladjafary** [quarkusio/quarkus#33549]
### Describe the bug

After upgrading to **3.0.2.Final** when I'm in the dev mode and apply some changes on the code and the reload, I give this following error 
```
Unable to invoke Kotlin compiler. java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.fir.extensions.FirExtensionRegistrar$Companion.registerExtension(com.intellij.openapi.project.Project, org.jetbrains.kotlin.fir.extensions.FirExtensionRegistrar)'
        at org.jetbrains.kotlin.allopen.AllOpenComponentRegistrar.registerProjectComponents(AllOpenPlugin.kt:57)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:666)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:168)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.configureProjectEnvironment(KotlinCoreEnvironment.kt:569)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:198)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:107)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:448)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:201)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:152)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at io.quarkus.kotlin.deployment.KotlinCompilationProvider.compile(KotlinCompilationProvider.java:93)
        at io.quarkus.deployment.dev.QuarkusCompiler.compile(QuarkusCompiler.java:226)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:727)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:461)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:441)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:152)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:139)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

Not having the exception

### Actual behavior

Throw the exception

### How to Reproduce?

1. Setup a quarkus project with Kotlin setup 
2. run the app in dev mode
3. apply change, 
4. reload the endpoint 

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by geoand** [comment]
Ah, the upgrade doesn't cover that, good catch!

cc @gsmet @ia3andy

**Comment by gsmet** [comment]
Starting Quarkus 3.0.3, the Kotlin upgrade is handled but it wasn't before (see https://github.com/quarkusio/quarkus/pull/33108).

As for the Kotlin configuration, we don't have anything for it as changing the configuration of Maven plugin is not that easy with OpenRewrite: we could do it but that would override any additional configuration made by the user and that could be destructive.

**Comment by gsmet** [comment]
Maybe we could do the `all-open` change with a simple text replacement as the pattern looks easy enough to find. I'll have a look.
