### ISSUE TITLE
Failed to stop Quarkus [Error Occurred After Shutdown] error when adjusting configuration through Dev UI

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#33588]
### Describe the bug

`Failed to stop Quarkus [Error Occurred After Shutdown]` error when adjusting configuration through Dev UI

Changes in `application.properties` file are detected, but the restart is not seamless, there is `Error Occurred After Shutdown` error in the log

There is no error in the log when adjusting `application.properties` file manually and accessing the rest endpoint to trigger the app restart.

I suspect, that the error during the restart is related to the websocket connection or to the "background ping" so the user doesn't need to access the app to trigger the restart.

Console log:
```
2023-05-24 22:23:56,363 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy-reactive, smallrye-context-propagation, vertx]
2023-05-24 22:28:46,401 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (executor-thread-1) File change detected: /Users/rsvoboda/Downloads/code-with-quarkus/src/main/resources/application.properties
2023-05-24 22:28:46,405 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (executor-thread-1) Restarting quarkus due to changes in application.properties.
2023-05-24 22:28:46,432 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus-abcx stopped in 0.025s
2023-05-24 22:28:46,433 ERROR [io.qua.run.boo.StartupActionImpl] (executor-thread-1) Failed to stop Quarkus [Error Occurred After Shutdown]: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl.doClose(StartupActionImpl.java:164)
	at io.quarkus.runner.bootstrap.StartupActionImpl$2.close(StartupActionImpl.java:142)
	at io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.close(RunningQuarkusApplicationImpl.java:35)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.stop(IsolatedDevModeMain.java:298)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:212)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:203)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:541)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:441)
	at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.preventKill(ConfigEditorProcessor.java:285)
	at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.updateConfig(ConfigEditorProcessor.java:258)
	at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.lambda$registerJsonRpcService$1(ConfigEditorProcessor.java:161)
	at io.quarkus.dev.console.DevConsoleManager.invoke(DevConsoleManager.java:135)
	at io.quarkus.devui.runtime.config.ConfigJsonRPCService.updateProperty(ConfigJsonRPCService.java:17)
	at io.quarkus.devui.runtime.config.ConfigJsonRPCService_ClientProxy.updateProperty(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.devui.runtime.comms.JsonRpcRouter.lambda$invoke$0(JsonRpcRouter.java:100)
	at io.smallrye.mutiny.unchecked.UncheckedSupplier.lambda$toSupplier$0(UncheckedSupplier.java:41)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Interrupted while waiting for another thread to stop the application
	at io.quarkus.runtime.Application.interruptedOnAwaitStop(Application.java:249)
	at io.quarkus.runtime.Application.awaitShutdown(Application.java:264)
	at io.quarkus.runtime.Quarkus.blockingExit(Quarkus.java:192)
	... 35 more


2023-05-24 22:28:46,434 ERROR [io.qua.run.boo.ForkJoinClassLoading] (executor-thread-1) Failed to set fork join ClassLoader [Error Occurred After Shutdown]: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1081)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading.setForkJoinClassLoader(ForkJoinClassLoading.java:40)
	at io.quarkus.runner.bootstrap.StartupActionImpl.doClose(StartupActionImpl.java:169)
	at io.quarkus.runner.bootstrap.StartupActionImpl$2.close(StartupActionImpl.java:142)
	at io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.close(RunningQuarkusApplicationImpl.java:35)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.stop(IsolatedDevModeMain.java:298)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:212)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:203)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:541)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:441)
	at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.preventKill(ConfigEditorProcessor.java:285)
	at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.updateConfig(ConfigEditorProcessor.java:258)
	at io.quarkus.vertx.http.deployment.devmode.console.ConfigEditorProcessor.lambda$registerJsonRpcService$1(ConfigEditorProcessor.java:161)
	at io.quarkus.dev.console.DevConsoleManager.invoke(DevConsoleManager.java:135)
	at io.quarkus.devui.runtime.config.ConfigJsonRPCService.updateProperty(ConfigJsonRPCService.java:17)
	at io.quarkus.devui.runtime.config.ConfigJsonRPCService_ClientProxy.updateProperty(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.devui.runtime.comms.JsonRpcRouter.lambda$invoke$0(JsonRpcRouter.java:100)
	at io.smallrye.mutiny.unchecked.UncheckedSupplier.lambda$toSupplier$0(UncheckedSupplier.java:41)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)


__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-05-24 22:28:46,745 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus-abc 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.1.0.Final) started in 0.307s. Listening on: http://0.0.0.0:8080

2023-05-24 22:28:46,746 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-05-24 22:28:46,746 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy-reactive, smallrye-context-propagation, vertx]
2023-05-24 22:28:46,747 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (executor-thread-1) Live reload total time: 0.348s
```

### Expected behavior

No error stacktrace in the log

### Actual behavior

Error stacktrace in the log

### How to Reproduce?

 - Get app from https://code.quarkus.io/
 - Run it in dev mode
 - Access http://127.0.0.1:8080/q/dev-ui/configuration-form-editor
 - Adjust ` quarkus.application.name` to `code-with-quarkus-abc`
 - Check the terminal where dev mode was started

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.0.3.Final / Quarkus main 071a89c

**Comment by phillip-kruger** [comment]
I'll have a look today

**Comment by phillip-kruger** [comment]
@rsvoboda this has been fix, PR coming soon...
