### ISSUE TITLE
NPE When Constructor Injecting a Microprofile Metric

### ISSUE THREAD

**Issue by gilday** [quarkusio/quarkus#33585]
### Describe the bug

Quarkus throws an NPE when a bean constructor injects a microprofile metric e.g.

```java
@ApplicationScoped
public class FailsToInjectMetric {

  private final Timer timer;

  @Inject
  public FailsToInjectMetric(
      @Metric(name = "my-timer", unit = MetricUnits.MILLISECONDS) final Timer timer) {
    this.timer = timer;
  }
```

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.microprofile.metrics.annotation.Metric.name()" because "annotation" is null

	at io.quarkus.micrometer.runtime.binder.mpmetrics.MetricRegistryAdapter.injectedTimer(MetricRegistryAdapter.java:365)
	at io.quarkus.micrometer.runtime.binder.mpmetrics.InjectedMetricProducer.getTimer(InjectedMetricProducer.java:72)
	at io.quarkus.micrometer.runtime.binder.mpmetrics.InjectedMetricProducer_ProducerMethod_getTimer_40638bc6dcfae855a99f42cfc454029922b9370a_Bean.doCreate(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.mpmetrics.InjectedMetricProducer_ProducerMethod_getTimer_40638bc6dcfae855a99f42cfc454029922b9370a_Bean.create(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.mpmetrics.InjectedMetricProducer_ProducerMethod_getTimer_40638bc6dcfae855a99f42cfc454029922b9370a_Bean.get(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.mpmetrics.InjectedMetricProducer_ProducerMethod_getTimer_40638bc6dcfae855a99f42cfc454029922b9370a_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:48)
	at com.acme.FailsToInjectMetric_Bean.doCreate(Unknown Source)
```

Changing the bean to use package-private field injection instead of constructor injection works around this issue.

### Expected behavior

Quarkus constructor injection works with microprofile metrics.

### Actual behavior

Quarkus throws NPE.

### How to Reproduce?

Run the tests in the attached Maven project.

[constructor-inject-microprofile-metric-issue.zip](https://github.com/quarkusio/quarkus/files/11557001/constructor-inject-microprofile-metric-issue.zip)

### Output of `uname -a` or `ver`

Darwin pixee-mbp-gilday.localdomain 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39) Maven home: /Users/jgilday/.m2/wrapper/dists/apache-maven-3.8.8-bin/67c30f74/apache-maven-3.8.8 Java version: 17.0.7, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "13.3.1", arch: "aarch64", family: "mac"

**Comment by geoand** [comment]
Thanks for reporting.

The reproducer doesn't really show the problem in hand, but it is easy enough to extend surface the actual issue by adding:

```java
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;

@Path("hello")
public class HelloResource {

    private final FailsToInjectMetric failsToInjectMetric;

    public HelloResource(FailsToInjectMetric failsToInjectMetric) {
        this.failsToInjectMetric = failsToInjectMetric;
    }

    @GET
    public String get() {
        failsToInjectMetric.doSomething();
        return "hello";
    }
}
```

@mkouba @jmartisk this is one for you guys to look at

**Comment by geoand** [comment]
It seems like 

https://github.com/quarkusio/quarkus/blob/3.0.3.Final/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/mpmetrics/InjectedMetricProducer.java#L71

does not yield the annotation for constructor parameters

**Comment by Ladicek** [comment]
Instead of adding a JAX-RS resource, it is enough to annotate the `FailsToInjectMetric` class `@Startup`. With that, I can also reproduce the issue.

Injecting the `InjectionPoint` metadata should work. I've been in that code recently, I'll take a look.

**Comment by Ladicek** [comment]
So the problem is not in ArC, injection point metadata work exactly as they should. There's an incorrect annotation transformation in the Micrometer extension that takes an annotation whose target is a parameter and replaces it with equivalent annotation that is targetted at a method. Such annotation is obviously not present in the injection point metadata.

I guess there's more annotation transformations that work incorrectly for parameters, because of the annotation transformation API's legacy. Not sure if we can do anything about that, but I'll submit a PR to fix the one I found here :-)

**Comment by Ladicek** [comment]
#33598 should fix this.
