### ISSUE TITLE
Building Native executable using container-build fails

### ISSUE THREAD

**Issue by ewoks** [quarkusio/quarkus#33610]
### Describe the bug

Trying to build linux executable with:
`mvn install -Dnative -DskipTests -Dquarkus.native.container-build=true` as per quarkus.io/guides/building-native-image, fails with following error:
```
Writing manifest to image destination
Storing signatures
47a7e9c75dba704bd8b46c17ab25b1529b26a2eb21f2c2f894ac744afab915ec
[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
...
...
Error: error creating container storage: creating an ID-mapped copy of layer "b20471bd23f2a3de10323366a217bcd22d8a9ad77fff50d20cf71280a8a4e0da": error during chown: storage-chown-by-maps: lchown usr/lib/locale/en_AU.utf8/LC_NAME: no such file or directory: exit status 1
```

I checked if my RHEL host machine has the file at `/usr/lib/locale/en_AU.utf8/LC_NAME` and it is there (root:root), but I am not sure why **en_AU** is important and if error refers to the file on my host machine or build image.

### Expected behavior

executable is built using default build image without errors.

### Actual behavior

fails with error from above.

### How to Reproduce?

Execute:
`mvn install -Dnative -DskipTests -Dquarkus.native.container-build=true` in a getting-started quarkus project root. 

will render:
```
Trying to pull quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17...
Getting image source signatures
Copying blob 8667fe2eaa4a skipped: already exists  
Copying blob 42d71c7fcaa2 skipped: already exists  
Copying blob d7a143ab1773 skipped: already exists  
Copying blob 368759f1ce35 skipped: already exists  
Copying blob a27c365cc8f5 skipped: already exists  
Copying blob f1e5c98c74e5 skipped: already exists  
Copying blob 118a124c1483 skipped: already exists  
Copying blob 6e198094e21c skipped: already exists  
Copying blob e430a4eaf0f9 skipped: already exists  
Copying blob 7d5003439875 skipped: already exists  
Copying blob 71d351c5e765 skipped: already exists  
Copying blob 3543484e245f skipped: already exists  
Copying blob 4f4fb700ef54 skipped: already exists  
Copying blob 4f4fb700ef54 skipped: already exists  
Copying blob a49367d57626 skipped: already exists  
Copying config 47a7e9c75d done  
Writing manifest to image destination
Storing signatures
47a7e9c75dba704bd8b46c17ab25b1529b26a2eb21f2c2f894ac744afab915ec
[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.

[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] podman run --env LANG=C --rm --user 119066:119066 --userns=keep-id -v /home/someuser/Downloads/quarkus-playground/getting-start/target/getting-start-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --name build-native-cGOgX quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json getting-start-1.0.0-SNAPSHOT-runner -jar getting-start-1.0.0-SNAPSHOT-runner.jar
Error: error creating container storage: creating an ID-mapped copy of layer "b20471bd23f2a3de10323366a217bcd22d8a9ad77fff50d20cf71280a8a4e0da": error during chown: storage-chown-by-maps: lchown usr/lib/locale/en_AU.utf8/LC_NAME: no such file or directory: exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.333 s
[INFO] Finished at: 2023-05-25T14:55:13+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.4.Final:build (default) on project getting-start: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 125
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:437)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:263)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

### Output of `uname -a` or `ver`

4.18.0-425.19.2.el8_7.x86_64

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)

### GraalVM version (if different from Java)

~/.sdkman/candidates/java/22.3.0.1.r17-mandrel/

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

### Additional information

Java is set by SdkMan, `JAVA_HOME` is not set, but `java -version` returns correct version and sdkman set it correctly to be available in the Path 
GRAALVM_HOME is explicitly set to mandrel installed by sdkman and it has `~/.sdkman/candidates/java/22.3.0.1.r17-mandrel/` value. 

Hereby, I would like to emphasize that this issue is about building with image. `podman images` returns:
```
REPOSITORY                                                                          TAG                     IMAGE ID           CREATED        SIZE
quay.io/quarkus/ubi-quarkus-mandrel-builder-image  22.3-java17       47a7e9c75dba  4 days ago     1.1 GB
```

Building using `quarkus build --native` when `GRAALVM_HOME` is set to mandrel version (and `JAVA_HOME` not set) as described above, creates valid native runnable of the getting-started application (~42MB).

**Comment by Karm** [comment]
> [ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep]
> Unable to get GraalVM version from the native-image binary.

Hell @ewoks, 
The podman on your system doesn't work, so even the first `native-image --version` to determine the version fails and it all goes downhill from there.

What happens if you just type:

```
podman pull quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
podman run quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17 --version
```

Are there any issues?

What is your `$ locale`?

**Comment by ewoks** [comment]
@Karm any further suggestions? could you reproduce it at your end? tnx

**Comment by galderz** [comment]
@ewoks Have you tried upgrading Podman? Current version is 4.5.0.

**Comment by Karm** [comment]
@ewoks I did not manage to reproduce it at the first try on RHEL 8, but I haven't tried a clean room system yet. Will get back here when I manage to switch context to it.
