### ISSUE TITLE
Resteasy reactive kotlin serialization not completely configured after generating app from code.quarkus.io 

### ISSUE THREAD

**Issue by janpk** [quarkusio/quarkus#33622]
### Describe the bug

Creating an app through code.quarkus.io with 

- kotlin
- resteasy reactive kotlin serialization
- maven

do not configure the kotlin-maven-plugin to use kotlinx-serialization.

Without doing this, kotlin serialization will not work, and the following error will be given when returning an object where content type is application_json

```
kotlinx.serialization.SerializationException: Serializer for class 'Result' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.

        at kotlinx.serialization.internal.PlatformKt.serializerNotRegistered(Platform.kt:31)
```

### Expected behavior

When selecting the resteasy reactive kotlin serialization extension, the kotlin-maven-plugin should also be configured in pom.xml.

```xml
     <plugin>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-maven-plugin</artifactId>
        <version>${kotlin.version}</version>
        <executions>
          <execution>
            <id>compile</id>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>test-compile</id>
            <goals>
              <goal>test-compile</goal>
            </goals>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-allopen</artifactId>
            <version>${kotlin.version}</version>
          </dependency>
          <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-serialization</artifactId>
            <version>${kotlin.version}</version>
          </dependency>
        </dependencies>
        <configuration>
          <javaParameters>true</javaParameters>
          <jvmTarget>17</jvmTarget>
          <compilerPlugins>
            <plugin>all-open</plugin>
            <plugin>kotlinx-serialization</plugin>
          </compilerPlugins>
          <pluginOptions>
            <option>all-open:annotation=jakarta.ws.rs.Path</option>
            <option>all-open:annotation=jakarta.enterprise.context.ApplicationScoped</option>
            <option>all-open:annotation=io.quarkus.test.junit.QuarkusTest</option>
          </pluginOptions>
        </configuration>
      </plugin>
```

### Actual behavior

The generated kotlin-maven-plugin in pom.xml is without the kotlinx.serialization plugin

```xml
      <plugin>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-maven-plugin</artifactId>
        <version>${kotlin.version}</version>
        <executions>
          <execution>
            <id>compile</id>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>test-compile</id>
            <goals>
              <goal>test-compile</goal>
            </goals>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-allopen</artifactId>
            <version>${kotlin.version}</version>
          </dependency>
        </dependencies>
        <configuration>
          <javaParameters>true</javaParameters>
          <jvmTarget>17</jvmTarget>
          <compilerPlugins>
            <plugin>all-open</plugin>
          </compilerPlugins>
          <pluginOptions>
            <option>all-open:annotation=jakarta.ws.rs.Path</option>
            <option>all-open:annotation=jakarta.enterprise.context.ApplicationScoped</option>
            <option>all-open:annotation=io.quarkus.test.junit.QuarkusTest</option>
          </pluginOptions>
        </configuration>
      </plugin>
```

### How to Reproduce?

1. Use code.quarkus.io, select maven as build tool and select the kotlin and the resteasy-reactive-kotlin-serialization extension
2. Change GreetingResource.kt generated starter code to

```kotlin
@Path("/hello")
class GreetingResource {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    fun hello() = Result("Hello from RESTEasy Reactive")
}

@Serializable
data class Result(val greeting : String)
```

Running

```bash
./mvnw test
```

results in 

```
kotlinx.serialization.SerializationException: Serializer for class 'Result' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.

        at kotlinx.serialization.internal.PlatformKt.serializerNotRegistered(Platform.kt:31)
```

**Comment by geoand** [comment]
Makes perfect sense, thanks for reporting!

**Comment by bulldog98** [comment]
Had a short look and it seems this also happens with gradle, should I open a seperate ticket for that?

**Comment by geoand** [comment]
cc @ia3andy

**Comment by geoand** [comment]
@ia3andy given how many people use Kotlin in Quarkus, I think this should be done. WDYT?

**Comment by ia3andy** [comment]
@geoand @janpk would it be a problem to have this dep (even when the kotlin serialization extension is not there)?:
```xml
<dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-serialization</artifactId>
            <version>${kotlin.version}</version>
          </dependency>
```

Else we could add a "if" condition based on the selected extensions, but this is a bit fragile (same for gradle I guess)

**Comment by geoand** [comment]
As far as I can tell, the issue is about configuring the Kotlin plugin, not about adding a dependency

**Comment by ia3andy** [comment]
are those two extensions the trigger to having this config?
https://code.quarkus.io/?extension-search=origin:platform%20serialization%20kotlin

**Comment by geoand** [comment]
correct!

**Comment by im-bravo** [comment]
Hi, team
Any solution about this issue ?

**Comment by ia3andy** [comment]
I will fix it now
