### ISSUE TITLE
Vert.X bump to 4.4.2 lead to `domain socket must not be empty` exception when used with Quarkus Micrometer extension

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#33679]
### Describe the bug

https://github.com/quarkusio/quarkus/pull/33416 makes my RESTEasy Classic app with domain socket fail.

### Expected behavior

No ex.

### Actual behavior

```bash
18:54:18,652 INFO  [app] 18:54:15,418 An exception 'java.lang.IllegalArgumentException: domain socket must not be empty' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:: java.lang.IllegalArgumentException: domain socket must not be empty
18:54:18,653 INFO  [app] 	at io.vertx.core.impl.Arguments.require(Arguments.java:29)
18:54:18,653 INFO  [app] 	at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:85)
18:54:18,654 INFO  [app] 	at io.vertx.core.impl.transports.EpollTransport.convert(EpollTransport.java:85)
18:54:18,654 INFO  [app] 	at io.vertx.core.net.impl.ConnectionBase.channelRemoteAddress(ConnectionBase.java:618)
18:54:18,654 INFO  [app] 	at io.vertx.core.net.impl.ConnectionBase.remoteAddress(ConnectionBase.java:631)
18:54:18,655 INFO  [app] 	at io.vertx.core.http.impl.HttpServerWorker.configureHttp1(HttpServerWorker.java:310)
18:54:18,656 INFO  [app] 	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:123)
18:54:18,657 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
18:54:18,657 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:54:18,658 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:54:18,658 INFO  [app] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
18:54:18,659 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
18:54:18,659 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:54:18,660 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:54:18,661 INFO  [app] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
18:54:18,661 INFO  [app] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
18:54:18,662 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
18:54:18,663 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:54:18,663 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:54:18,664 INFO  [app] 	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
18:54:18,665 INFO  [app] 	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
18:54:18,665 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
18:54:18,666 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:54:18,666 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:54:18,667 INFO  [app] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
18:54:18,667 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
18:54:18,668 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:54:18,668 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:54:18,669 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
18:54:18,669 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
18:54:18,670 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:54:18,670 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
18:54:18,671 INFO  [app] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
18:54:18,671 INFO  [app] 	at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:140)
18:54:18,671 INFO  [app] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
18:54:18,672 INFO  [app] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
18:54:18,672 INFO  [app] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
18:54:18,673 INFO  [app] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
18:54:18,673 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
18:54:18,673 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

Reproducer:

1. `git clone git@github.com:michalvavrik/quarkus-test-suite.git`
2. `git checkout -b reproducer/domain-socket-vertx-bump`
3. `cd quarkus-test-suite/http/http-advanced`
4. `mvn clean test`

### Output of `uname -a` or `ver`

Fedora 38

### Output of `java -version`

17

### GraalVM version (if different from Java)

23.2

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

MVN 3.9.1

**Comment by cescoffier** [comment]
@Vietj any idea?

**Comment by cescoffier** [comment]
Hum, works with KQueue...

It seems that with epoll, the path is empty.

**Comment by vietj** [comment]
remote address does not make sense with domain sockets I think

**Comment by vietj** [comment]
can you share how it happens ? I can see an upgrade

**Comment by vietj** [comment]
as far as I can see, it's an HTTP/2 upgrade with on a domain socket server ?

**Comment by vietj** [comment]
I think it happens after a change in netty

**Comment by gsmet** [comment]
@cescoffier @michalvavrik how widespread is this configuration? I.e. do I need to revert and release a 3.1.1.Final right away and avoid releasing 3.1.0.Final?

**Comment by michalvavrik** [comment]
> very uncommon - it's when you use native transport which is still experimental (and typically do not work in native). Also, it's only happening on linux Epoll, which now for linux, we recommend io_uring.

I think we followed https://quarkus.io/guides/vertx-reference#listening-to-a-unix-domain-socket to verify https://github.com/quarkusio/quarkus/issues/24739. I can see in migration guide that Quarkus 3 supports `io_uring`, however I can't find a single note about it in the Quarkus documentation, let alone note that you recommned `io_uring`. Can you please point me to this recommendation? Thank you

**Comment by michalvavrik** [comment]
I think you meant that I can find it in Vert.X docs https://vertx.io/docs/vertx-io_uring-incubator/java/ ?

**Comment by cescoffier** [comment]
The PR adding the doc is there: https://github.com/quarkusio/quarkus/pull/33544.

**Comment by michalvavrik** [comment]
Alright, thank you.

**Comment by cescoffier** [comment]
I'm trying to write a pure vert.x reproducer.

**Comment by cescoffier** [comment]
Hum... not sure why, I cannot reproduce it...

**Comment by michalvavrik** [comment]
I'll try today.

**Comment by cescoffier** [comment]
Hum... interesting. Why would micrometer influence this...

**Comment by cescoffier** [comment]
Ah ah...

@vietj HttpServerWorker:310 .... it tries to rebuild to remote address, and ends up with something empty. 

It actually calls convert twice. The first time, for the actual HTTP processing it works, the second time for the metrics, it fails.

**Comment by cescoffier** [comment]
@vietj here is a pure vert.x reproducer:

[Archive.zip](https://github.com/quarkusio/quarkus/files/11615225/Archive.zip)

**Comment by vietj** [comment]
Thanks clément, will have a look soonish

**Comment by vietj** [comment]
that's indeed something that changed in Netty and we have to workaround it in vertx , for domain sockets we will most likely return the local address as remote address in this case

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/pull/4719
