### ISSUE TITLE
Cannot compile native with GraalVM and Azure

### ISSUE THREAD

**Issue by Lory1990** [quarkusio/quarkus#33690]
### Describe the bug

Hi!
I am trying to compile my app with `Quarkus 3.0.4.Final` in native but there is this error:

```
Error encountered while parsing com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.getHeader() 
Parsing context:
   at com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.getHeader(DigestProxyChallengeProcessorImpl.java:53)
```

The full stack is:
```
16:40:35,543 INFO  [com.azu.cor.imp.jac.JacksonVersion] Package versions: jackson-core=2.14.2, jackson-databind=2.14.2, jackson-dataformat-xml=2.14.2, jackson-datatype-jsr310=2.14.2, azure-core=1.35.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
16:40:39,247 INFO  [org.mon.dri.authenticator] Using built-in driver implementation to retrieve AWS credentials. Consider adding a dependency to AWS SDK v2's software.amazon.awssdk:auth artifact to get access to additional AWS authentication functionality.
[2/7] Performing analysis...  []                                                                        (65.7s @ 4.00GB)
  22,655 (94.98%) of 23,852 classes reachable
  32,376 (63.75%) of 50,789 fields reachable
 102,528 (83.42%) of 122,906 methods reachable
     774 classes,     0 fields, and     0 methods registered for reflection
       2 native libraries: m, stdc++
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.getHeader() 
Parsing context:
   at com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.getHeader(DigestProxyChallengeProcessorImpl.java:53)
   at com.microsoft.azure.proton.transport.proxy.impl.ProxyImpl$ProxyTransportWrapper.process(ProxyImpl.java:276)
   at org.apache.qpid.proton.engine.impl.TransportImpl.process(TransportImpl.java:[1589](https://git.tools.mia-platform.eu/clients/beconsulting/step/international/services/step-trackactions-be-int/-/jobs/1664405#L1589))
   at org.apache.qpid.proton.reactor.impl.IOHandler$1.run(IOHandler.java:242)
   at org.apache.qpid.proton.reactor.impl.SelectableImpl.readable(SelectableImpl.java:118)
   at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:61)
   at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:398)
   at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:236)
   at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
   at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
   at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:292)
   at com.azure.core.amqp.implementation.ReactorExecutor.lambda$scheduleCompletePendingTasks$1(ReactorExecutor.java:158)
   at com.azure.core.amqp.implementation.ReactorExecutor$$Lambda$3613/0x00000007c2ee74c0.run(Unknown Source)
   at com.azure.core.amqp.implementation.ReactorExecutor.scheduleCompletePendingTasks(ReactorExecutor.java:181)
   at com.azure.core.amqp.implementation.ReactorExecutor.closeAsync(ReactorExecutor.java:203)
   at com.azure.core.amqp.implementation.AmqpChannelProcessor.close(AmqpChannelProcessor.java:345)
   at com.azure.core.amqp.implementation.AmqpChannelProcessor.onNext(AmqpChannelProcessor.java:136)
   at reactor.core.publisher.Signal.accept(Signal.java:299)
   at reactor.core.publisher.Signal.accept(Signal.java:38)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxOptionsCustomizer.customize(VertxCoreRecorder.java:632)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:209)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:610)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:592)
   at io.quarkus.mongodb.runtime.MongoClientRecorder$1.get(MongoClientRecorder.java:37)
   at io.quarkus.mongodb.runtime.MongoClientRecorder$1.get(MongoClientRecorder.java:31)
   at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:219)
   at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:172)
   at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:305)
   at java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2573)
   at com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.initializeCommonPool(RecomputedFields.java:385)
   at com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.get(RecomputedFields.java:377)
   at java.util.concurrent.ForkJoinTask.fork(ForkJoinTask.java:652)
   at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:306)
   at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
   at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
   at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
   at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
   at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
   at java.lang.reflect.Executable.sharedToString(Executable.java:122)
   at java.lang.reflect.Method.toString(Method.java:412)
   at java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
   at java.lang.StringConcatHelper.simpleConcat(StringConcatHelper.java:408)
   at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializerError(ClassInitializationInfo.java:366)
   at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:359)
   at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:277)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:109)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:562)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:488)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:[1622](https://git.tools.mia-platform.eu/clients/beconsulting/step/international/services/step-trackactions-be-int/-/jobs/1664405#L1622))
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  To see how this object got instantiated use --trace-object-instantiation=java.security.SecureRandom. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
	at parsing com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.computeDigestAuthHeader(DigestProxyChallengeProcessorImpl.java:143)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2518)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:110)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3393)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3345)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3190)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:97)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:84)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:446)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysis.java:180)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1162)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:1145)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:1003)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:957)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:817)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysis.java:240)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:548)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:833)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:98)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:179)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:349)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
	... 13 more
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  To see how this object got instantiated use --trace-object-instantiation=java.security.SecureRandom. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.DisallowedImageHeapObjectFeature.error(DisallowedImageHeapObjectFeature.java:174)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.image.DisallowedImageHeapObjects.check(DisallowedImageHeapObjects.java:65)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.DisallowedImageHeapObjectFeature.replacer(DisallowedImageHeapObjectFeature.java:150)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:595)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:177)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:148)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:100)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:79)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil$1.readValue(ConstantFoldUtil.java:55)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.common.spi.JavaConstantFieldProvider.readConstantField(JavaConstantFieldProvider.java:78)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantFieldProvider.readConstantField(AnalysisConstantFieldProvider.java:72)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil.tryConstantFold(ConstantFoldUtil.java:51)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.ConstantFoldLoadFieldPlugin.tryConstantFold(ConstantFoldLoadFieldPlugin.java:53)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.ConstantFoldLoadFieldPlugin.handleLoadStaticField(ConstantFoldLoadFieldPlugin.java:49)
------------------------------------------------------------------------------------------------------------------------
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4801)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4772)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5282)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3385)
	... 38 more
                        7.2s (8.0% of total time) in 25 GCs | Peak RSS: 6.04GB | CPU load: 3.30
========================================================================================================================
Failed generating 'step-trackactions-be-int-runner' after 1m 28s.
Error: Image build request failed with exit status 1
```

I think is a problem with this dependency:
```
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-servicebus</artifactId>
</dependency>
```

the CD/CI pipeline (Gitlab) is:
```
build:
  image:
    name: softinstigate/graalvm-maven:latest
    entrypoint: [""]
  script:
    - source /root/.bashrc
    - mvn package $MAVEN_OPTS -Pnative -DskipTests -Dquarkus.native.builder-image=graalvm
```

### Output of `java -version`

maven:3.8.3-openjdk-17

### GraalVM version (if different from Java)

softinstigate/graalvm-maven:latest

### Quarkus version or git rev

3.0.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

**Comment by geoand** [comment]
`azure-messaging-servicebus` is not something we have support for out of the box, so this is really not a Quarkus issue.

That said, if what you reported is the only problem with the library, it should be a very easy fix :)

**Comment by agoncal** [comment]
@Lory1990 which version of the Azure SDK are you using? I'm not sure the entire Azure SDK compiles to native yet.

**Comment by Lory1990** [comment]
@agoncal 
azure-messaging-servicebus - 7.13.1
azure-identity - 1.7.3

**Comment by zakkak** [comment]
> `azure-messaging-servicebus` is not something we have support for out of the box, so this is really not a Quarkus issue.

Closing as not planned.
