### ISSUE TITLE
hotreload fails hard when adding extensions with vscode (any IDE?) open

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33709]
### Describe the bug

```
code .
```

in vscode terminal 1:

```
quarkus create app redhattour
cd redhattour
quarkus dev
```

in vscode terminal 2:

```
quarkus ext add jdbc-postgres
quarkus ext add hibernate-orm-panache
```

reload now will have stacktrace like this:

```
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources @ redhatontour
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile @ redhatontour
[INFO] Nothing to compile - all classes are up to date
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ redhatontour
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/manderse/code/demo/redhatontour/src/test/resources
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile @ redhatontour
2023-05-30 19:12:28,989 INFO  [io.quarkus] (Shutdown thread) redhatontour stopped in 0.013s

--
Press [:] for the terminal, [h] for more options>
Listening for transport dt_socket at address: 5005
2023-05-30 19:12:30,305 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-05-30 19:12:30,533 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.vertx.http.deployment.StaticResourcesProcessor#collectStaticResources threw an exception: java.lang.NullPointerException: Cannot invoke "io.quarkus.bootstrap.classloading.ClassPathResource.getUrl()" because "res" is null
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.getResources(QuarkusClassLoader.java:260)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.getResources(QuarkusClassLoader.java:207)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:102)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:85)
        at io.quarkus.vertx.http.deployment.StaticResourcesProcessor.getClasspathResources(StaticResourcesProcessor.java:96)
        at io.quarkus.vertx.http.deployment.StaticResourcesProcessor.collectStaticResources(StaticResourcesProcessor.java:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.vertx.http.deployment.StaticResourcesProcessor#collectStaticResources threw an exception: java.lang.NullPointerException: Cannot invoke "io.quarkus.bootstrap.classloading.ClassPathResource.getUrl()" because "res" is null
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.getResources(QuarkusClassLoader.java:260)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.getResources(QuarkusClassLoader.java:207)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:102)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:85)
        at io.quarkus.vertx.http.deployment.StaticResourcesProcessor.getClasspathResources(StaticResourcesProcessor.java:96)
        at io.quarkus.vertx.http.deployment.StaticResourcesProcessor.collectStaticResources(StaticResourcesProcessor.java:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        ... 9 more
Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.bootstrap.classloading.ClassPathResource.getUrl()" because "res" is null
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.getResources(QuarkusClassLoader.java:260)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.getResources(QuarkusClassLoader.java:207)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:102)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:85)
        at io.quarkus.vertx.http.deployment.StaticResourcesProcessor.getClasspathResources(StaticResourcesProcessor.java:96)
        at io.quarkus.vertx.http.deployment.StaticResourcesProcessor.collectStaticResources(StaticResourcesProcessor.java:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


2023-05-30 19:12:30,571 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-2) Restarting quarkus due to changes in GreetingResource.class.
2023-05-30 19:12:30,675 WARN  [io.qua.hib.orm.dep.HibernateOrmProcessor] (build-10) Hibernate ORM is disabled because no JPA entities were found
2023-05-30 19:12:31,661 INFO  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-14) Dev Services for the default datasource (postgresql) started - container ID is ddbe0083fe1e
2023-05-30 19:12:31,663 INFO  [io.qua.hib.orm.dep.dev.HibernateOrmDevServicesProcessor] (build-23) Setting quarkus.hibernate-orm.database.generation=drop-and-create to initialize Dev Services managed database
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-05-30 19:12:32,106 INFO  [io.quarkus] (Quarkus Main Thread) redhatontour 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.0.4.Final) started in 1.530s. Listening on: http://localhost:8080

2023-05-30 19:12:32,107 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-05-30 19:12:32,108 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, narayana-jta, resteasy-reactive, smallrye-context-propagation, vertx]
2023-05-30 19:12:32,108 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-2) Live reload total time: 1.541s 

--
Press [:] for the terminal, [h] for more options>
```

sometimes it recovers - but other times it stays with error and app does not work.

**Comment by gsmet** [comment]
I tried to reproduce it following the instructions and it looks OK now. We probably added the required safe guards as I see us having code to avoid adding null resources.
