### ISSUE TITLE
Hibernate entity inheritance does not work with Kotlin

### ISSUE THREAD

**Issue by cthiebault** [quarkusio/quarkus#33740]
### Describe the bug

Using Hibernate entity inheritance with Kotlin works fine with Quarkus 2 but not with Quarkus 3.

I've created a repo that reproduce the bug:
https://github.com/cthiebault/quarkus-hibernate-kotlin

Use the `quarkus2` and `quarkus3` branches to reproduce the issue.

Here are the entities

```kotlin
@Entity
@Table(name = "shape")
@Inheritance(strategy = InheritanceType.JOINED)
abstract class Shape(

  @Id
  @JdbcTypeCode(SqlTypes.VARCHAR)
  @Column(name = "id", updatable = false, nullable = false, unique = true)
  open val id: UUID,

  @Length(max = 100)
  @Column(name = "name", nullable = false, length = 100)
  open var name: String,

  @Enumerated(EnumType.STRING)
  @Column(name = "color", nullable = false, length = 50)
  open var color: Color,

  @Embedded
  var properties: Properties?,
)
```

```kotlin
@Entity
@Table(name = "rectangle")
@PrimaryKeyJoinColumn(name = "shape_id")
data class Rectangle(
  override val id: UUID,
  override var name: String,
  override var color: Color,
  override var properties: Properties?
) : Shape(id, name, color, properties) 
```

```kotlin
@ApplicationScoped
class ShapeRepository : PanacheRepositoryBase<Shape, UUID>
```

And the test I run

```kotlin
  @Test
  @Transactional
  fun test() {

    val rectangle = Rectangle(
      id = UUID.randomUUID(),
      name = "Rectangle",
      color = Color.Red,
      properties = Properties("foo", "bar")
    )

    Log.info("rectangle: $rectangle")
    repository.persist(rectangle)

    val found = repository.findById(rectangle.id)
    Log.info("found: $found")

    assertEquals(rectangle, found)
    assertEquals(1, repository.count())
  }
```

The error with Qurakus 3:
```text
INFO: rectangle: Rectangle(id=7c0863fb-a786-4dd7-b9f1-c3b3f48fc0d8, name=Rectangle, color=Red, properties=Properties(foo=foo, bar=bar))

INFO: found: Rectangle(id=7c0863fb-a786-4dd7-b9f1-c3b3f48fc0d8, name=Rectangle, color=Red, properties=Properties(foo=foo, bar=bar))
ERROR: ERROR: null value in column "name" of relation "shape" violates not-null constraint
  Detail: Failing row contains (7c0863fb-a786-4dd7-b9f1-c3b3f48fc0d8, null, null, null, null).

could not execute statement [ERROR: null value in column "name" of relation "shape" violates not-null constraint
  Detail: Failing row contains (7c0863fb-a786-4dd7-b9f1-c3b3f48fc0d8, null, null, null, null).] [insert into shape (color,name,bar,foo,id) values (?,?,?,?,?)]
org.hibernate.exception.ConstraintViolationException: could not execute statement [ERROR: null value in column "name" of relation "shape" violates not-null constraint
  Detail: Failing row contains (7c0863fb-a786-4dd7-b9f1-c3b3f48fc0d8, null, null, null, null).] [insert into shape (color,name,bar,foo,id) values (?,?,?,?,?)]
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:95)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:278)
	at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.performNonBatchedMutation(AbstractMutationExecutor.java:108)
	at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorStandard.lambda$performNonBatchedOperations$1(MutationExecutorStandard.java:217)
	at java.base@17.0.7/java.util.TreeMap.forEach(TreeMap.java:1282)
	at org.hibernate.engine.jdbc.mutation.internal.PreparedStatementGroupStandard.forEachStatement(PreparedStatementGroupStandard.java:90)
	at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorStandard.performNonBatchedOperations(MutationExecutorStandard.java:217)
	at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.execute(AbstractMutationExecutor.java:53)
	at org.hibernate.persister.entity.mutation.InsertCoordinator.doStaticInserts(InsertCoordinator.java:170)
	at org.hibernate.persister.entity.mutation.InsertCoordinator.coordinateInsert(InsertCoordinator.java:112)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2656)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:102)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:616)
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:487)
	at java.base@17.0.7/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:484)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:358)
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:55)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1375)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$0(ConcreteSqmSelectQueryPlan.java:107)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:302)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:243)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:521)
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:367)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.list(QuerySqmImpl.java:1084)
	at org.hibernate.query.spi.AbstractSelectionQuery.getSingleResult(AbstractSelectionQuery.java:461)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.getSingleResult(QuerySqmImpl.java:1110)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.count(AbstractJpaOperations.java:323)
	at org.acme.ShapeRepository.count(ShapeRepository.kt)
	at org.acme.ShapeRepository_ClientProxy.count(Unknown Source)
	at org.acme.ShapeTest.test(ShapeTest.kt:43)
```

### How to Reproduce?

https://github.com/cthiebault/quarkus-hibernate-kotlin

### Additional information

Gradle 8.1.1
Build time: 2023-04-21 12:31:26 UTC
Revision: 1cf537a851c635c364a4214885f8b9798051175b

Kotlin: 1.8.10
Groovy: 3.0.15
Ant: Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM: 17.0.7 (Eclipse Adoptium 17.0.7+7)
OS: Linux 6.1.30-1-MANJARO amd64

**Comment by marko-bekhta** [comment]
Hey, I'm not that familiar with Kotlin, but I've looked into what's causing this issue. In short, the problem is caused by such behaviour from Kotlin:

```kotlin
var shapeField = Shape::class.java.getDeclaredField("color")
shapeField.setAccessible(true)
// it's already strange that this even works and there's a declared `color` field on a rectangle O_o
var rectangleField = Rectangle::class.java.getDeclaredField("color")
rectangleField.setAccessible(true)


val rectangle = Rectangle(
        id = UUID.randomUUID(),
        name = "Rectangle",
        color = Color.Red,
        properties = Properties("foo", "bar")
)

// unable to get a color value using superclass field (the returned value is `null`)
// which is what ORM is attempting to do (if simplified)
// and that in the end leads to the exception on an insert operation in ORM
assertTrue(shapeField.get(rectangle) == null)

// getting data out of fields from concrete type gives the stored value: 
assertFalse(rectangleField.get(rectangle) == null)
assertEquals(Color.Red, rectangleField.get(rectangle))
```

The exception happens on flush when ORM attempts to write data into DB. Since it gets nulls for all the values, it tries to execute an insert with those `nulls`, and a DB rejects it. I suspect that this - https://github.com/hibernate/hibernate-orm/blob/f22d7e1328c0e063528eb8a16ccaf6a064e8f713/hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java#L4684-L4707 would be a part that would need some adjustments if we'd want to support this case in ORM. 
It worked in Quarkus 2 since it was using ORM 5.6 and it accessed entity data a bit differently...

**Comment by yrodiere** [comment]
> would be a part that would need some adjustments if we'd want to support this case in ORM.

Can you please create an issue in Hibernate ORM? Though I'm not sure this will get a high priority given Hibernate ORM mostly targets Java and not Kotlin...

I would guess this has to do with Kotlin's [property override](https://www.callicoder.com/kotlin-inheritance/#overriding-properties)? Most likely field access won't work well in such case, since, well... Kotlin probably just never uses the parent class' field.

I'd suggest trying to avoid field override and seeing where this leads.

Failing that, putting `@Access(AccessType.FIELD)` on `Shape` or `Rectangle` could be a valid workaround, assuming Kotlin goes generate getters and setters (`getId()`, etc.). Someone would have to try, though.

**Comment by marko-bekhta** [comment]
Created https://hibernate.atlassian.net/browse/HHH-16735

Also tested your suggestion about `@Access(AccessType.PROPERTY)` -- that helps:

```kotlin
@Entity
@Table(name = "shape")
@Inheritance(strategy = InheritanceType.JOINED)
abstract class Shape(

  @Id
  @JdbcTypeCode(SqlTypes.VARCHAR)
  @Column(name = "id", updatable = false, nullable = false, unique = true)
  open val id: UUID,

  @Length(max = 100)
  @Column(name = "name", nullable = false, length = 100)
  @Access(AccessType.PROPERTY)
  open var name: String,

  @Enumerated(EnumType.STRING)
  @Column(name = "color", nullable = false, length = 50)
  @Access(AccessType.PROPERTY)
  open var color: Color,

  @Embedded
  var properties: Properties?,

  )
```
makes the test pass.

**Comment by yrodiere** [comment]
> Also tested your suggestion about `@Access(AccessType.PROPERTY)` -- that helps:

Glad to hear that.

FWIW, you should be able to put the annotation the type level:

```kotlin
@Entity
@Table(name = "shape")
@Inheritance(strategy = InheritanceType.JOINED)
@Access(AccessType.PROPERTY)
abstract class Shape(

  @Id
  @JdbcTypeCode(SqlTypes.VARCHAR)
  @Column(name = "id", updatable = false, nullable = false, unique = true)
  open val id: UUID,

  @Length(max = 100)
  @Column(name = "name", nullable = false, length = 100)
  open var name: String,

  @Enumerated(EnumType.STRING)
  @Column(name = "color", nullable = false, length = 50)
  open var color: Color,

  @Embedded
  var properties: Properties?,

  )
```

**Comment by marko-bekhta** [comment]
yup, that would've worked too. There's just a `open val id: UUID,`  hiding there (which is val and not var) )which doesn't have a setter (at least ORM would complain that it doesn't 😄) so probably would need to override the access for the id on a field level if a type level access is set 🙈

**Comment by cthiebault** [comment]
Thanks for help!!

@yrodiere , I tried to add `@Access(AccessType.PROPERTY)` at type level as you suggested but I get
```
org.hibernate.AnnotationException: Entity 'org.acme.Shape' has no identifier (every '@Entity' class must declare or inherit at least one '@Id' or '@EmbeddedId' property)
	at org.hibernate.boot.model.internal.InheritanceState.getElementsToProcess(InheritanceState.java:235)
	at org.hibernate.boot.model.internal.InheritanceState.postProcess(InheritanceState.java:160)
	at org.hibernate.boot.model.internal.EntityBinder.handleIdentifier(EntityBinder.java:293)
	at org.hibernate.boot.model.internal.EntityBinder.bindEntityClass(EntityBinder.java:228)
	at org.hibernate.boot.model.internal.AnnotationBinder.bindClass(AnnotationBinder.java:417)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:255)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:275)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:318)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:406)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:101)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:73)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:40)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$1.created(HibernateOrmRecorder.java:78)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:79)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy(Unknown Source)
	... 64 more
```

For now I will annotate each parent class fields... 

Thanks again for your quick answers!!!

**Comment by cthiebault** [comment]
Hello
I'm trying to upgrade Quarkus to 3.1.1 but I get again the same error even if the fields of the parent class are annotated with `@Access(AccessType.PROPERTY)` :-(

I've pushed a new `quarkus-3.1.1` branch to my repo that shows the error:
https://github.com/cthiebault/quarkus-hibernate-kotlin/tree/quarkus-3.1.1

It was working with Quarkus 3.1.0 but not anymore with 3.1.1

```text
org.hibernate.exception.ConstraintViolationException: could not execute statement [ERROR: null value in column "name" of relation "shape" violates not-null constraint
      Detail: Failing row contains (4db7480d-5875-4c2f-bf0c-3b52704cc0d4, null, null, null, null).] [insert into shape (color,name,bar,foo,id) values (?,?,?,?,?)]
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:95)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:278)
        at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.performNonBatchedMutation(AbstractMutationExecutor.java:108)
        at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorStandard.lambda$performNonBatchedOperations$1(MutationExecutorStandard.java:217)
        at java.base@17.0.7/java.util.TreeMap.forEach(TreeMap.java:1282)
        at org.hibernate.engine.jdbc.mutation.internal.PreparedStatementGroupStandard.forEachStatement(PreparedStatementGroupStandard.java:90)
        at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorStandard.performNonBatchedOperations(MutationExecutorStandard.java:217)
        at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.execute(AbstractMutationExecutor.java:53)
        at org.hibernate.persister.entity.mutation.InsertCoordinator.doStaticInserts(InsertCoordinator.java:170)
        at org.hibernate.persister.entity.mutation.InsertCoordinator.coordinateInsert(InsertCoordinator.java:112)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2742)
        at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:102)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:606)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:358)
        at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:55)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
        at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1375)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$0(ConcreteSqmSelectQueryPlan.java:108)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:303)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:244)
        at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:518)
        at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:367)
        at org.hibernate.query.spi.AbstractSelectionQuery.getSingleResult(AbstractSelectionQuery.java:473)
        at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.count(AbstractJpaOperations.java:323)
        at org.acme.ShapeRepository.count(ShapeRepository.kt)
        at org.acme.ShapeRepository_ClientProxy.count(Unknown Source)
        at org.acme.ShapeTest.test(ShapeTest.kt:43)

        Caused by:
        org.postgresql.util.PSQLException: ERROR: null value in column "name" of relation "shape" violates not-null constraint
          Detail: Failing row contains (4db7480d-5875-4c2f-bf0c-3b52704cc0d4, null, null, null, null).
            at app//org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
            at app//org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
            at app//org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
            at app//org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
            at app//org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
            at app//org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
            at app//org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
            at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
            at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:275)
            ... 26 more
```

**Comment by yrodiere** [comment]
@cthiebault As stated above, this is a bug in Hibernate ORM.

If things still don't work, or are getting worse, I'd recommend reaching out to the Hibernate ORM team, in particular to assist in analyzing the causes on the Kotlin side of things. Christian asked for just that [here](https://hibernate.atlassian.net/browse/HHH-15874?focusedCommentId=111579).

**Comment by cthiebault** [comment]
Thanks @yrodiere!
I'll create a small repo to reproduce the issue with Hibernate only...

**Comment by cthiebault** [comment]
I've created a minimalist repo with just Hibernate & Kotlin and inheritance seems to work if we annotate fields with `@Access(AccessType.PROPERTY)`:
https://github.com/cthiebault/hibernate-inheritance-kotlin

But the same code is failing with Quarkus 3.1.1:
https://github.com/cthiebault/quarkus-hibernate-kotlin/tree/quarkus-3.1.1

**Comment by yrodiere** [comment]
@marko-bekhta could you have another look? This might not be the same problem as https://hibernate.atlassian.net/browse/HHH-15874 after all.

**Comment by marko-bekhta** [comment]
Yes, sure. Will do 👍🏻😃

**Comment by marko-bekhta** [comment]
@cthiebault, thanks again for reporting a problem. As it turned out, it is a different bug from the one about Kotlin. I've created this ticket for it: https://hibernate.atlassian.net/browse/HHH-16799
I couldn't see any workarounds for you, so it seems you'd need to stay on 3.1.0 for now.

**Comment by cthiebault** [comment]
Hello @marko-bekhta 
I see that 3.2.0 release is almost out... Do you have an idea of when this issue could be fixed? 
Thanks :)

**Comment by yrodiere** [comment]
Not in 3.2.0, since core artifacts have already been released. It'll be fixed next time we upgrade Hibernate ORM in Quarkus. Probably in 3.2.1/3.2.2.

**Comment by polymorph233** [comment]
It seems that if the entities are also connected by `@OneToOne` relationship, with the `@Access(AccessType.PROPERTY)` annotation, another bug of hibernate will be triggered and Quarkus will refuse to launch.

```
io.quarkus.dev.appstate.ApplicationStartException: java.lang.ClassCastException: class org.hibernate.mapping.BasicValue 
cannot be cast to class org.hibernate.mapping.ToOne (org.hibernate.mapping.BasicValue and org.hibernate.mapping.ToOne are 
in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @3aefe5e5)
```

The ticket could be found here: https://hibernate.atlassian.net/browse/HHH-16593 and don't know when this will be solved.

**Comment by cthiebault** [comment]
Issue https://hibernate.atlassian.net/browse/HHH-16593 seems fixed for Hibernate `6.3.0.CR1` :-)

**Comment by DepickereSven** [comment]
Can we get this functionality merged in Quarkus 3.2.8 Final?

**Comment by yrodiere** [comment]
You would need a backport of HHH-16593 to Hibernate ORM 6.2, which from what I understand is unlikely: https://hibernate.org/orm/releases/6.2/ , https://hibernate.org/community/maintenance-policy/#levels . You can always ask the Hibernate ORM team though :shrug: 

As for Quarkus, this will get fixed when we upgrade to Hibernate ORM 6.3/6.4, which I'm currently working on. So this should hopefully be in Quarkus 3.6, or Quarkus 3.7 if we don't get a Hibernate Reactive release in time.

**Comment by DepickereSven** [comment]
Thank you for the quick response, there has been a hibernate issue been created:
https://hibernate.atlassian.net/browse/HHH-17195

But indeed, let's see if it get ported back or not.

**Comment by msnijder30** [comment]
@DepickereSven I was also running into this, and I noticed they did backport this and created a new release version 6.2.16 on december 15th

**Comment by yrodiere** [comment]
This will be fixed in Quarkus 3.7 when we upgrade to Hibernate ORM 6.4.0 (#36978).
It should also eventually get fixed in Quarkus 3.2 when we upgrade to Hibernate ORM 6.2.16, but I don't when that will be.
