### ISSUE TITLE
Quarkus 3.1 still throws an error if @Produces is not defined on a stream response

### ISSUE THREAD

**Issue by blabdouze** [quarkusio/quarkus#33746]
### Describe the bug

With the new addiction of `RestMulti` we should be able to do something like this :

```java
public Multi<String>streamedResponse {
	return RestMulti.fromMultiData()
				.header("Content-Type", "application/json")
				.build();
}
```
It returns the following error when calling the endpoint :  

```posh
error id: 8a43ae6f-691a-445f-aca6-a8171f0f9332-1: java.lang.IllegalStateException: Negotiation or dynamic media type not supported yet for Multi: please use the @Produces annotation when returning a Multi
        at org.jboss.resteasy.reactive.server.handlers.PublisherResponseHandler.handle(PublisherResponseHandler.java:304)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

⚠️ ⚠️ ⚠️ Note that if you add a random `@Produces` bean like `@Produces(MediaType.APPLICATION_XML)` no error is thrown and the function behaves normally, returning the correct Content-Type defined in the `RestMulti` object.

### Expected behavior

The error should not appear if you don't specify `@Produces`, since it has no impact with the new `RestMulti` object.

### How to Reproduce?

```java
package org.acme;

import io.smallrye.mutiny.Multi;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.jboss.resteasy.reactive.RestMulti;

@Path("/")
public class GreetingResource {
    @GET
    @Path("/notworking")
    public Multi<byte[]> notWorking() {
        Multi<byte[]> multi = Multi.createFrom().item("Hello from RESTEasy Reactive".getBytes());
        return RestMulti.fromMultiData(multi).header("Content-Type", MediaType.TEXT_PLAIN).build();
    }

    @GET
    @Path("/working")
    @Produces(MediaType.APPLICATION_ATOM_XML)
    public Multi<byte[]> working() {
        Multi<byte[]> multi = Multi.createFrom().item("Hello from RESTEasy Reactive".getBytes());
        return RestMulti.fromMultiData(multi).header("Content-Type", MediaType.TEXT_PLAIN).build();
    }

    @GET
    @Path("/workingString")
    public Multi<String> workingWithString() {
        Multi<String> multi = Multi.createFrom().item("Hello from RESTEasy Reactive");
        return RestMulti.fromMultiData(multi).header("Content-Type", MediaType.TEXT_PLAIN).build();
    }
}
```

### Quarkus version or git rev

3.1

**Comment by geoand** [comment]
I am not sure I understand the title - specifically the mention of `@Content`.

In any case, mind attaching a sample Quarkus application that shows the problem you are having?

**Comment by geoand** [comment]
Thanks!

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/33763 takes care of the issue
