### ISSUE TITLE
3.1.0.Final - io.quarkus.builder.BuildException: Build failure: Build failed due to errors

### ISSUE THREAD

**Issue by spieps** [quarkusio/quarkus#33764]
### Describe the bug

The only change I made was upgrading quarkus.platform.version from 3.0.3.Final to 3.1.0.Final

When I execute `mvn install -Pnative` it fails when trying to run the tests. It produced the native image successfully in 3.0.3.Final.

```
[INFO] Running com.fanthreesixty.program.consumers.SmsMessageAddedConsumerTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.764 s <<< FAILURE! - in com.fanthreesixty.program.consumers.SmsMessageAddedConsumerTest
[ERROR] com.fanthreesixty.program.consumers.SmsMessageAddedConsumerTest.testConsumingSmsMessage  Time elapsed: 0.005 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.loggingmanager.deployment.LoggingManagerProcessor#includeUiAndWebsocket threw an exception: java.lang.NoSuchMethodError: 'io.quarkus.bootstrap.model.AppModel io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem.getEffectiveModel()'
        at io.quarkiverse.loggingmanager.deployment.LoggingManagerProcessor.includeUiAndWebsocket(LoggingManagerProcessor.java:152)
```

### Expected behavior

`mvn install -Pnative` finishes successfully

### Actual behavior

```
[ERROR] Errors: 
[ERROR]   SmsMessageAddedConsumerTest.testConsumingSmsMessage » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.loggingmanager.deployment.LoggingManagerProcessor#includeUiAndWebsocket threw an exception: java.lang.NoSuchMethodError: 'io.quarkus.bootstrap.model.AppModel io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem.getEffectiveModel()'
        at io.quarkiverse.loggingmanager.deployment.LoggingManagerProcessor.includeUiAndWebsocket(LoggingManagerProcessor.java:152)
```

### How to Reproduce?

```
<properties>
    <compiler-plugin.version>3.11.0</compiler-plugin.version>
    <failsafe.useModulePath>false</failsafe.useModulePath>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>3.1.0.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

### Output of `uname -a` or `ver`

Darwin FTSRoot-100268.attlocal.net 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08) OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39) Maven home: /Users/sethpiepergerdes/Public/apache-maven-3.8.8 Java version: 17.0.5, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.3.0/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "13.4", arch: "x86_64", family: "mac"

**Comment by geoand** [comment]
@aloubyansky did we remove `CurateOutcomeBuildItem#getEffectiveModel`?

In any case, this is not a Quarkus core issue, but an issue for https://github.com/quarkiverse/quarkus-logging-manager

**Comment by aloubyansky** [comment]
Yes, apparently, as part of a clean up of deprecated API.
