### ISSUE TITLE
Quarkus Reactive Rest Client using Jackson Deserializer which needs to call another Rest Client fails

### ISSUE THREAD

**Issue by doppelrittberger** [quarkusio/quarkus#33783]
### Describe the bug

I need to use a Rest Client to fetch data. While deserializing the data I need to call another Rest Client to validate the data. Using classic RestEasy this works well, but with reactive RestEasy it fails with 
```
2023-06-01` 22:12:30,507 ERROR [org.jbo.res.rea.ser.cor.RuntimeExceptionMapper] (executor-thread-1) A blocking operation occurred on the IO thread. This likely means you need to annotate com.test.TestResource#getMoney() with @io.smallrye.common.annotation.Blocking. Alternatively you can annotate the class com.test.TestResource to make every method on the class blocking, or annotate your sub class of the jakarta.ws.rs.core.Application class to make the whole application blocking
2023-06-01 22:12:30,515 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /test failed, error id: 094d184b-555a-4651-8513-f0d967b6f404-1: org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'HTTP 400 Bad Request' when invoking: Rest Client method: 'com.test.MoneyResource#getMoney'
	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.unwrapException(RestClientRequestContext.java:185)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.handleException(AbstractResteasyReactiveContext.java:324)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:173)
	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:295)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException) (through reference chain: com.test.Money["currency"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1830)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
	at org.jboss.resteasy.reactive.server.jackson.JacksonBasicMessageBodyReader.doReadFrom(JacksonBasicMessageBodyReader.java:44)
	at org.jboss.resteasy.reactive.server.jackson.JacksonBasicMessageBodyReader.readFrom(JacksonBasicMessageBodyReader.java:31)
	at io.quarkus.rest.client.reactive.jackson.runtime.serialisers.ClientJacksonMessageBodyReader.readFrom(ClientJacksonMessageBodyReader.java:45)
	at org.jboss.resteasy.reactive.client.impl.ClientReaderInterceptorContextImpl.proceed(ClientReaderInterceptorContextImpl.java:86)
	at org.jboss.resteasy.reactive.client.impl.ClientSerialisers.invokeClientReader(ClientSerialisers.java:160)
	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.readEntity(RestClientRequestContext.java:197)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.mapToResponse(ClientResponseCompleteRestHandler.java:104)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:35)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:31)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:229)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	... 12 more
Caused by: org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException
	at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.unwrap(InvocationBuilderImpl.java:210)
	at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:324)
	at com.test.CurrencyResource$$QuarkusRestClientInterface.getCurrency(Unknown Source)
	at com.test.RestClientProducer_ProducerMethod_createCurrencyResource_dfcd167d61eb2228b92290ac57be5abe835d9139_ClientProxy.getCurrency(Unknown Source)
	at com.test.CurrencyDeserializer.deserialize(CurrencyDeserializer.java:20)
	at com.test.CurrencyDeserializer.deserialize(CurrencyDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:568)
	... 30 more

```

### Expected behavior

It should work like it works in classic RestEasy

### Actual behavior

The Rest Client fetches data from a remote endpoint and needs to deserialize the data using a custom Jackson Deserializer. This uses another Rest Client instance to fetch additional data but this fails because of some blocking operation.

### How to Reproduce?

You find a reproducer here: https://github.com/doppelrittberger/quarkus-rest-client-test
Just run the application and call http://localhost:8080/test
This will fetch the data for the use case. In pom.xml you can toggle to classic RestEasy which works as expected.

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

17

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.2

**Comment by geoand** [comment]
What you are trying to do will not work with the Reactive REST Client because its internals are run on the Event Loop (even whern returning a blocking result).

I kind of don't think we'll fix this as it would mean a lot of work just to address this one niche use case.

**Comment by Sgitario** [comment]
> What you are trying to do will not work with the Reactive REST Client because its internals are run on the Event Loop (even whern returning a blocking result).
> 
> I kind of don't think we'll fix this as it would mean a lot of work just to address this one niche use case.

+100

**Comment by doppelrittberger** [comment]
Hi and thanks for the quick reply.
While I indeed agree that this is some edge case I want to point out a more common use case: calling a database while deserializing. I think this will also cause a lot of problems.
Anyway some more questions:
Since it is not possible to mix reactive Rest Server and non-reactive Rest Client: how long will you support the "classic" non-blocking Rest Server and Client?
Are there some workarounds that we can do? I already tried @Blocking but this is not supported by the Rest Client. Also setting executorManager() on the Rest Client is not supported. It would be really great if you could give some advice despite saying that my use case is a niche use case and you can´t do anything :)
Thanks in advance
P.S. if you point me to the code which needs to be changed I can also create a PR

**Comment by geoand** [comment]
>  calling a database while deserializing

If you don't mind me saying, this is probably not a good idea. The reason is that you have very little control over how much the database will be hit due to deserialization.

> Since it is not possible to mix reactive Rest Server and non-reactive Rest Client: how long will you support the "classic" non-blocking Rest Server and Client?

There are no plans for retiring it any time soon.

> Are there some workarounds that we can do? I already tried @Blocking but this is not supported by the Rest Client. Also setting executorManager() on the Rest Client is not supported. It would be really great if you could give some advice despite saying that my use case is a niche use case and you can´t do anything :)

I didn't say we can't do anything, I said it's unlikely we will because it requires a lot of work (and will complicate the code significantly) just to address such niche use cases.
There aren't any workarounds using your current code architecture. Personally, regardless of the framework, I would look into taking all I/O out of serialization/deserialization operations if I were you.

**Comment by doppelrittberger** [comment]
Ok, I will try to get around this in another way. Thanks anyway

**Comment by geoand** [comment]
👌
