### ISSUE TITLE
How to use hibernate with thread? Exception in thread "ForkJoinPool-2-worker-1" jakarta.enterprise.inject.CreationException: java.lang.ClassNotFoundException: io.quarkus.hibernate.orm.runtime.TransactionSessions

### ISSUE THREAD

**Issue by seepine** [quarkusio/quarkus#33788]
### Describe the bug

ExecutorConfigurer.java
```java
public class ExecutorConfigurer {
  @Produces
  public ForkJoinPool forkJoinPool() {
    return new ForkJoinPool(
        Math.max(Runtime.getRuntime().availableProcessors() - 4, 4),
        ForkJoinPool.defaultForkJoinWorkerThreadFactory,
        null,
        true);
  }
}
```

UserDao.java
```java
@Singleton
public class UserDao implements PanacheRepositoryBase<User, Long> {

  @Transactional
  public void save(User entities) {
    persist(entities);
  }
}
```

UserResource.java
```java
@Path("/user")
public class UserResource {
  @Inject ForkJoinPool forkJoinPool;
  @Inject UserDao userDao;

  @GET
  @Path("save1")
  @Produces(MediaType.TEXT_PLAIN)
  public String save1() {
    forkJoinPool.execute(() -> userDao.save(User.builder().nickName("bob").build()));
    return "save1 end";
  }
}
```

### Expected behavior

insert success

### Actual behavior

throw exception
```
Exception in thread "ForkJoinPool-2-worker-1" jakarta.enterprise.inject.CreationException: java.lang.ClassNotFoundException: io.quarkus.hibernate.orm.runtime.TransactionSessions
	at org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_Bean.create(Unknown Source)
	at org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_ClientProxy.arc$delegate(Unknown Source)
	at org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_ClientProxy.contains(Unknown Source)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:100)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:96)
	at io.quarkus.hibernate.orm.panache.PanacheRepositoryBase.persist(PanacheRepositoryBase.java:54)
	at com.example.dao.UserDao.save(UserDao.java:13)
	at com.example.dao.UserDao_Subclass.save$$superforward(Unknown Source)
	at com.example.dao.UserDao_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:66)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:34)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.example.dao.UserDao_Subclass.save(Unknown Source)
	at com.example.resource.UserResource.lambda$save1$0(UserResource.java:24)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: io.quarkus.hibernate.orm.runtime.TransactionSessions
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_Bean.doCreate(Unknown Source)
	... 36 more

```

### How to Reproduce?

https://github.com/seepine/quarkus-thread-hibernate-demo

### Output of `java -version`

17

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.1.1

**Comment by geoand** [comment]
If I may ask, what exactly are you trying to achieve?

**Comment by geoand** [comment]
That being said, it's probably pretty wasteful to offload the Hibernate ORM calls to another executor :)

**Comment by geoand** [comment]
My point is that when you are invoking Hibernate ORM from a JAX-RS Resource like that, you are already on an executor thread.

If you offload the task like that, you are tying  up two threads when one would suffice

**Comment by Sanne** [comment]
Sorry but this is a terrible idea; some reasons coming to mind in no particular order, not even an exuastive list:
 - the `ForkJoinPool` is meant for computationally intensive tasks which DO NOT perform IO, you're slowing down your entire JVM.
 - offloading a save task is unnecessary, like Georgios mentioned this whole method was already offloaded by Quarkus to a dedicated executor automatically (so you don't have to).
 - You mention "insert speed" .. this operation won't perform faster just by moving it to a different thread. In fact it's going to be slower as now there's extra work to be done.
 - All transactional boundaries are now undefined as it's unclear in which context the "save" operation is running; for example if you need to save multiple objects this will happen in undefined order and w/o being part of the same transaction.
 - If you happen to save multiple objects which have a common cascade rule and the save operation is applied transitively to any object which is shared by different threads, you're going to get runtime exceptions as it attempts to associate the same objects to different Sessions.

Having said that, I'm puzzled that this results in a `ClassNotFoundException` - we might need to look into that @geoand

**Comment by geoand** [comment]
> Having said that, I'm puzzled that this results in a ClassNotFoundException - we might need to look into that @geoand

I am not based on the Javadoc of `QuarkusForkJoinWorkerThreadFactory` :)

**Comment by Sanne** [comment]
Ah, right - thanks! All good here then :+1:

**Comment by geoand** [comment]
🙏🏼
