### ISSUE TITLE
Using a PropertyVisibilityStrategy when deserializing a json document containing a collection of enums fails since 3.0.0.Final

### ISSUE THREAD

**Issue by stephane-vallee9** [quarkusio/quarkus#33780]
### Describe the bug

When deserializing a json document that contains a collection of enums using io.quarkus:quarkus-jsonb, adding a PropertyVisibilityStrategy have the program fail with the following error:

java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.lang.Enum.name accessible: module java.base does not "opens java.lang" to unnamed module @cdf2379

This was working till version 3.0.0.CR2 and fails starting 3.0.0.Final

Also, maybe of interest: it doesn't fail when deserializing plain enums, only when deserializing a collection of enums.

### Expected behavior

It shouldn't fail AFAIK.

### Actual behavior

It fails

### How to Reproduce?

```java
import jakarta.inject.*;
import jakarta.json.bind.*;
import jakarta.json.bind.config.*;

import java.lang.reflect.*;
import java.time.*;
import java.util.*;

import org.jboss.logging.*;

import io.quarkus.runtime.*;
import io.quarkus.runtime.annotations.*;

@QuarkusMain
public class TestJsonBug implements QuarkusApplication {
	public static record MyBean(String name, Month month, List<Month> listOfMonths) {
	}

	@Inject
	private Logger logger;

	public TestJsonBug() {
		super();
	}

	public int run(String... args) {
		var text = """
				{
					"name": "John",
					"month": "JANUARY",
					"listOfMonths": [ "JANUARY", "FEBRUARY" ]
				}
				""";

		// Works
		logger.infof("Parsed: %s", binding(null).fromJson(text, MyBean.class));
		// Fails
		logger.infof("Parsed: %s", binding(strategy()).fromJson(text, MyBean.class));
		return 0;
	}

	protected Jsonb binding(PropertyVisibilityStrategy strategy) {
		return JsonbBuilder.newBuilder().withConfig(new JsonbConfig().withPropertyVisibilityStrategy(strategy)).build();
	}

	protected PropertyVisibilityStrategy strategy() {
		return new PropertyVisibilityStrategy() {
			public boolean isVisible(Field field) {
				return true;
			}

			public boolean isVisible(Method meth) {
				return false;
			}
		};
	}
}
```

### Output of `uname -a` or `ver`

Darwin potiron.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by geoand** [comment]
Does it fail with Quarkus `3.1.0.Final` as well?

**Comment by geoand** [comment]
This is not a Quarkus specific issue. I propose opening an issue on the [Yasson](https://github.com/eclipse-ee4j/yasson)  repository

**Comment by stephane-vallee9** [comment]
Yes, certainly, but the fact that this deserialization issue starts happening in 3.0.0.Final (no issue in 3.0.0.CR2) while there is no change in the included Yasson version between 3.0.0.CR2 and 3.0.0.Final wouldn't suggest that there was a change in Quarkus that might be of interest? (stacktrace refers to some missing/necessary --add-opens)

When I execute the given test in a context without Quarkus (Yasson only + plain java), there is no issue happening.

**Comment by geoand** [comment]
What's the entire stacktrace?

**Comment by stephane-vallee9** [comment]
```
2023-06-02 07:05:55,761 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.lang.Enum.name accessible: module java.base does not "opens java.lang" to unnamed module @559570f4
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.eclipse.yasson.internal.model.PropertyModel.lambda$overrideAccessible$2(PropertyModel.java:594)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.eclipse.yasson.internal.model.PropertyModel.overrideAccessible(PropertyModel.java:593)
	at org.eclipse.yasson.internal.model.PropertyModel.isFieldVisible(PropertyModel.java:568)
	at org.eclipse.yasson.internal.model.PropertyModel.createReadHandle(PropertyModel.java:516)
	at org.eclipse.yasson.internal.model.PropertyModel.<init>(PropertyModel.java:157)
	at org.eclipse.yasson.internal.ClassParser.lambda$parseProperties$0(ClassParser.java:70)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.eclipse.yasson.internal.ClassParser.parseProperties(ClassParser.java:71)
	at org.eclipse.yasson.internal.MappingContext.lambda$createParseClassModelFunction$1(MappingContext.java:105)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:77)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.createCollectionDeserializer(DeserializationModelCreator.java:272)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChainInternal(DeserializationModelCreator.java:183)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChain(DeserializationModelCreator.java:135)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.createNewChain(DeserializationModelCreator.java:488)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.typeProcessor(DeserializationModelCreator.java:477)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.typeProcessor(DeserializationModelCreator.java:430)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.createObjectDeserializer(DeserializationModelCreator.java:227)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChainInternal(DeserializationModelCreator.java:193)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChain(DeserializationModelCreator.java:135)
	at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.deserializerChain(DeserializationModelCreator.java:123)
	at org.eclipse.yasson.internal.DeserializationContextImpl.deserializeItem(DeserializationContextImpl.java:137)
	at org.eclipse.yasson.internal.DeserializationContextImpl.deserialize(DeserializationContextImpl.java:127)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:55)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:62)
	at com.test.jsonb.TestJsonBug.run(TestJsonBug.java:40)
	at com.test.jsonb.TestJsonBug_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by stephane-vallee9** [comment]
This is the small project I use. Hope it helps.

[jsonb-bug.tar.gz](https://github.com/quarkusio/quarkus/files/11634673/jsonb-bug.tar.gz)

**Comment by stephane-vallee9** [comment]
Thank you for your help. Will investigate more and open an issue with Yasson.
