### ISSUE TITLE
Generic CDI Decorator Throws java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by gilday** [quarkusio/quarkus#33803]
### Describe the bug

When using CDI decorators with generic type parameters in a Quarkus application, a `NoSuchMethodError` is thrown when invoking a decorated method. The error message indicates that it cannot find the method in the decorator class.

The following configuration fails when executing the `GreetingResource.hello()` method:

```java
interface Repository<T> {
  T get();
}

@Priority(APPLICATION)
@Decorator
class LoggingRepository<T> implements Repository<T> {

  @Inject Logger logger;

  @Inject @Any @Delegate Repository<T> delegate;

  @Override
  public T get() {
    logger.debug("Getting item");
    return delegate.get();
  }
}

@ApplicationScoped
class GreetingRepository implements Repository<String> {

  @Override
  public String get() {
    return "Hello from RESTEasy Reactive";
  }
}

@Path("/hello")
class GreetingResource {

  @Inject GreetingRepository repository;

  @GET
  @Produces(MediaType.TEXT_PLAIN)
  public String hello() {
    return repository.get();
  }
}
```

The exception is:

```
	Suppressed: java.lang.NoSuchMethodError: 'java.lang.String org.acme.LoggingRepository.get()'
		at org.acme.GreetingRepository_Subclass.get(Unknown Source)
		at org.acme.GreetingRepository_ClientProxy.get(Unknown Source)
		at org.acme.GreetingResource.hello(GreetingResource.java:53)
		at org.acme.GreetingResource$quarkusrestinvoker$hello_e747664148511e1e5212d3e0f4b40d45c56ab8a1.invoke(Unknown Source)
		at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
		at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
		at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
```

A similar configuration works as expected in Weld.

### Expected behavior

Quarkus Arc decorates all beans that implement the interface with the decorator and no exception is thrown. In this example, the `GreetingRepository` is decorated with logic in the `LoggingRepository<T>` decorator.

### Actual behavior

Decorated bean throws `NoSuchMethodException`.

### How to Reproduce?

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/11638777/code-with-quarkus.zip)

### Output of `uname -a` or `ver`

Darwin pixee-mbp-gilday.localdomain 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39) Maven home: /Users/jgilday/.m2/wrapper/dists/apache-maven-3.8.8-bin/67c30f74/apache-maven-3.8.8 Java version: 17.0.7, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "13.3.1", arch: "aarch64", family: "mac"

**Comment by manovotn** [comment]
Likely an Arc bug. I know I already saw another issue with generic decorators (https://github.com/quarkusio/quarkus/issues/30811).
Note that Quarkus/Arc doesn't have full support of decorators like Weld.
I am not sure how far we are with supporting these cases, can take a look on Mon.

**Comment by Ladicek** [comment]
`java.lang.NoSuchMethodError: 'java.lang.String org.acme.LoggingRepository.get()'`

The decorator only has a method with return type of `Object` (after erasure), so not sure where that `String` comes from. Perhaps we expect the decorators have a method with the same signature/descriptor as the decorated class? Or something like that.

**Comment by manovotn** [comment]
It seems that when we create the `invokevirtual` call to the decorator, we build the call from the method descriptor of the original method - in this case it means we expect return type `String` but the decorator only knows one with `Object`.
We're doing that in the following bit of code - https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/SubclassGenerator.java#L538-L542
