### ISSUE TITLE
Hibernate Reactive with Oracle doesn't support identity generation strategy

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#33831]
### Describe the bug

We have app (also) with Hibernate Reactive extension and Oracle. Before Quarkus 3, we used `identity` generation strategy, now it is not possible. It seems like a regression and I can't find anything about it in [Hibernate migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0) or https://docs.jboss.org/hibernate/orm/6.2/userguide/html_single/Hibernate_User_Guide.html#identifiers-generators-identity.

### Expected behavior

Previously when we had column `ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` and id defined as 
```
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;
```
it just worked.

### Actual behavior

```
18:36:22,014 INFO  [app] 18:36:21,195 Failed to start application (with profile [prod]): org.hibernate.MappingException: org.hibernate.dialect.identity.IdentityColumnSupportImpl does not support identity key generation
18:36:22,014 INFO  [app] 	at org.hibernate.dialect.identity.IdentityColumnSupportImpl.getIdentityColumnString(IdentityColumnSupportImpl.java:48)
18:36:22,014 INFO  [app] 	at org.hibernate.tool.schema.internal.ColumnDefinitions.appendColumnDefinition(ColumnDefinitions.java:161)
18:36:22,014 INFO  [app] 	at org.hibernate.tool.schema.internal.ColumnDefinitions.appendColumn(ColumnDefinitions.java:88)
18:36:22,014 INFO  [app] 	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:73)
18:36:22,015 INFO  [app] 	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:41)
18:36:22,015 INFO  [app] 	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createTables(SchemaCreatorImpl.java:420)
18:36:22,015 INFO  [app] 	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createSequencesTablesConstraints(SchemaCreatorImpl.java:340)
18:36:22,015 INFO  [app] 	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createFromMetadata(SchemaCreatorImpl.java:239)
18:36:22,015 INFO  [app] 	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:172)
18:36:22,015 INFO  [app] 	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:142)
18:36:22,015 INFO  [app] 	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:118)
18:36:22,016 INFO  [app] 	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:226)
18:36:22,016 INFO  [app] 	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:143)
18:36:22,016 INFO  [app] 	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
18:36:22,016 INFO  [app] 	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:140)
18:36:22,016 INFO  [app] 	at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
18:36:22,016 INFO  [app] 	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
18:36:22,016 INFO  [app] 	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:292)
18:36:22,016 INFO  [app] 	at org.hibernate.reactive.session.impl.ReactiveSessionFactoryImpl.<init>(ReactiveSessionFactoryImpl.java:32)
18:36:22,017 INFO  [app] 	at io.quarkus.hibernate.reactive.runtime.boot.FastBootReactiveEntityManagerFactoryBuilder.build(FastBootReactiveEntityManagerFactoryBuilder.java:31)
18:36:22,017 INFO  [app] 	at io.quarkus.hibernate.reactive.runtime.FastBootHibernateReactivePersistenceProvider.createEntityManagerFactory(FastBootHibernateReactivePersistenceProvider.java:92)
18:36:22,017 INFO  [app] 	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
18:36:22,017 INFO  [app] 	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
18:36:22,017 INFO  [app] 	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:156)
18:36:22,017 INFO  [app] 	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
18:36:22,017 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

1. `git clone git@github.com:quarkus-qe/quarkus-test-suite.git`
2. `cd quarkus-test-suite/sql-db/hibernate-reactive`
3. `sed -i '/@Disabled/d' src/test/java/io/quarkus/ts/hibernate/reactive/OracleDatabaseIT.java`
4. `mvn clean verify -Dit.test=OracleDatabaseIT`

### Quarkus version or git rev

`999-SNAPSHOT`

**Comment by michalvavrik** [comment]
We can't detect problem anymore :-)
