### ISSUE TITLE
Get runtime exception in Integration test

### ISSUE THREAD

**Issue by raizo000** [quarkusio/quarkus#33852]
### Describe the bug

I facing this runtime exception in our integration test when upgrade to version  **3.1.0.Final** of **quarkus-hibernate-orm-panache-deployment**

This is trace log 
```
Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors        [error]: Build step io.quarkus.deployment.steps.ClassTransformingBuildStep#handleClassTransformation threw an exception: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'java.lang.String org.jboss.jandex.Type.descriptor()'
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'java.lang.String org.jboss.jandex.Type.descriptor()'
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at io.quarkus.deployment.steps.ClassTransformingBuildStep.handleClassTransformation(ClassTransformingBuildStep.java:267)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        ... 6 more
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.jboss.jandex.Type.descriptor()'
        at io.quarkus.panache.common.deployment.ByteCodeType.descriptor(ByteCodeType.java:36)
        at io.quarkus.panache.common.deployment.visitors.PanacheRepositoryClassOperationGenerationVisitor.lambda$discoverTypeParameters$2(PanacheRepositoryClassOperationGenerationVisitor.java:104)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
```

### Output of `uname -a` or `ver`

Windows 10
### Output of `java -version`

Java 17

**Comment by geoand** [comment]
Thanks for reporting, however for us to be able to help, we'll need a sample project that exhibits the behavior you mention.

**Comment by gsmet** [comment]
My guess is that you have an inconsistent project such as a Jandex version overriding the BOM version or that you have updated only one extension.

Make sure you have consistent versioning i.e. use the BOM, make sure the Quarkus Maven Plugin shares the same version and don't override individual versions.

I'm going to close this. If this is not your issue and you have a reproducer, please reopen it.
