### ISSUE TITLE
Memory leak with static resource

### ISSUE THREAD

**Issue by JozefDropco** [quarkusio/quarkus#33885]
### Describe the bug

We are getting a OutOfMemory issue in one of our applications. This application doesnt have any extreme memory consumption. Serves 1 static HTML and displays data from 3rd party application (data displayed at once is chunked to size of 10 - so nearly no memory footprint). After 2 days working with the application, application is hung during JS file download. Stack trace is

```posh
[executor-thread-32] ERROR io.undertow.request.io - Exception handling request f9662cbc-faf8-4803-be49-44b07d3efcb0-25 to /monitor/lhadam_monitor/5EB8298E7263A641426C4958A9769D7D.cache.js
java.lang.OutOfMemoryError: Direct buffer memory
at java.base/java.nio.Bits.reserveMemory(Unknown Source)
at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:701)
at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:676)
at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:215)
at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:180)
at io.netty.buffer.PoolArena.allocate(PoolArena.java:137)
at io.netty.buffer.PoolArena.allocate(PoolArena.java:129)
at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:396)
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$UndertowBufferAllocator.allocateBuffer(UndertowDeploymentRecorder.java:831)
at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$UndertowBufferAllocator.allocateBuffer(UndertowDeploymentRecorder.java:825)
at io.undertow.server.HttpServerExchange.allocateBuffer(HttpServerExchange.java:1266)
at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:154)
at io.undertow.server.handlers.resource.URLResource.serveRangeBlocking(URLResource.java:366)
at io.undertow.server.handlers.resource.CachedResource.serveRangeBlocking(CachedResource.java:311)
at io.undertow.servlet.handlers.DefaultServlet.serveFileBlocking(DefaultServlet.java:358)
at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:197)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
```

### Expected behavior

Application should be working just fine without any issues

### Actual behavior

Application doesnt display as the JS file has 1,19 MB of size and download hungs at 65kB see screenshot
![image](https://github.com/quarkusio/quarkus/assets/729306/8cfc8af0-695c-450d-be4b-7c7997ef8181)

### Output of `uname -a` or `ver`

 Linux amd 5.4.0-144-generic

### Output of `java -version`

11.0.18

### Quarkus version or git rev

2.16.7.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

**Comment by geoand** [comment]
Have you tried using `-Dio.netty.leakDetection.level=advanced` as described [here](https://netty.io/wiki/reference-counted-objects.html#leak-detection-levels) to detect where the leak is coming from?

**Comment by JozefDropco** [comment]
hi @geoand , I am sorry  I didnt have time to test it. But I will give it a try and keep you posted

**Comment by Sanne** [comment]
Any news?

**Comment by JozefDropco** [comment]
Hi @Sanne , we are no Longoria using undertow with quarkus. I rewrote all legacy code to REST api instead
