### ISSUE TITLE
Quarkus Dev Mode Hangs on stop

### ISSUE THREAD

**Issue by phillip-kruger** [quarkusio/quarkus#33896]
### Describe the bug

I have this issue with the latest released (3.1.1) and main (999-SNAPSHOT) versions of Quarkus that I start an app in dev mode, then stop it (using ctl-c) but that does not stop quarkus and I have to do a kill -9 to stop the process. After killing the process, the app can not start up properly anymore and I have to restart my laptop to get it to start. 

Now, this is probably just on my laptop and something weird with my environment,  but I thought I'll log the bug and see if anyone can help me. It seems connected to the docker instance started by Testing (Keycloak in this case), but I'll investigate further. To recreate, create an app from code.quarkus.io with oidc, resteasy reactive and smallrye open api, start the app and then stop it. 

I am using podman version 4.5.1

### Expected behavior

The app stop and can be started again

### Actual behavior

The app hangs on stop and needs to be killed

### How to Reproduce?

[code-with-quarkus(12).zip](https://github.com/quarkusio/quarkus/files/11684095/code-with-quarkus.12.zip)

Use above app, start it, go to dev ui, stop it, see if it hand for you.

### Output of `uname -a` or `ver`

Linux pkruger-laptop 6.3.5-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 30 15:44:17 UTC 2023 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7) OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7, mixed mode, sharing)

### Quarkus version or git rev

3.1.1 or 999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

**Comment by gsmet** [comment]
When the process hangs, use `kill -3 <pid>` to get the stacktrace. That would help narrow down the issue.

**Comment by phillip-kruger** [comment]
Thanks @gsmet . This is the output:
```
Full thread dump OpenJDK 64-Bit Server VM (17.0.7+7 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007f308c6fa210, length=12, elements={
0x00007f3124026270, 0x00007f31241dc590, 0x00007f31241dd970, 0x00007f31241e2ea0,
0x00007f31241e42c0, 0x00007f31241e56d0, 0x00007f31241e7080, 0x00007f31241e85b0,
0x00007f31241f1a10, 0x00007f31241f9010, 0x00007f31241fd080, 0x00007f31256f1700
}

"main" #1 prio=5 os_prio=0 cpu=3848.72ms elapsed=79.13s tid=0x00007f3124026270 nid=0x125db waiting on condition  [0x00007f312951c000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(java.base@17.0.7/Native Method)
        at io.quarkus.maven.DevMojo.execute(DevMojo.java:416)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
        at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
        at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
        at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:827)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:272)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:195)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.7/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.7/NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.7/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@17.0.7/Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=1.66ms elapsed=79.12s tid=0x00007f31241dc590 nid=0x125e2 waiting on condition  [0x00007f30e52c8000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@17.0.7/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@17.0.7/Reference.java:253)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@17.0.7/Reference.java:215)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.53ms elapsed=79.12s tid=0x00007f31241dd970 nid=0x125e3 in Object.wait()  [0x00007f30e51c8000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.7/Native Method)
        - waiting on <0x0000000417001308> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.7/ReferenceQueue.java:155)
        - locked <0x0000000417001308> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.7/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@17.0.7/Finalizer.java:172)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.19ms elapsed=79.12s tid=0x00007f31241e2ea0 nid=0x125e4 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.50ms elapsed=79.12s tid=0x00007f31241e42c0 nid=0x125e5 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Deflation Thread" #6 daemon prio=9 os_prio=0 cpu=1.94ms elapsed=79.12s tid=0x00007f31241e56d0 nid=0x125e6 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=0 cpu=3787.25ms elapsed=79.12s tid=0x00007f31241e7080 nid=0x125e7 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #10 daemon prio=9 os_prio=0 cpu=1705.39ms elapsed=79.12s tid=0x00007f31241e85b0 nid=0x125e8 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #11 daemon prio=9 os_prio=0 cpu=40.73ms elapsed=79.12s tid=0x00007f31241f1a10 nid=0x125e9 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Notification Thread" #12 daemon prio=9 os_prio=0 cpu=0.09ms elapsed=79.12s tid=0x00007f31241f9010 nid=0x125ea runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #13 daemon prio=8 os_prio=0 cpu=1.34ms elapsed=79.12s tid=0x00007f31241fd080 nid=0x125ec in Object.wait()  [0x00007f30e48c6000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.7/Native Method)
        - waiting on <0x0000000417000358> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.7/ReferenceQueue.java:155)
        - locked <0x0000000417000358> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@17.0.7/CleanerImpl.java:140)
        at java.lang.Thread.run(java.base@17.0.7/Thread.java:833)
        at jdk.internal.misc.InnocuousThread.run(java.base@17.0.7/InnocuousThread.java:162)

"process reaper (pid 75290)" #16 daemon prio=10 os_prio=0 cpu=0.16ms elapsed=74.41s tid=0x00007f31256f1700 nid=0x1261f runnable  [0x00007f30e4431000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ProcessHandleImpl.waitForProcessExit0(java.base@17.0.7/Native Method)
        at java.lang.ProcessHandleImpl$1.run(java.base@17.0.7/ProcessHandleImpl.java:150)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.7/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.7/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.7/Thread.java:833)

"VM Thread" os_prio=0 cpu=13.89ms elapsed=79.12s tid=0x00007f31241d8610 nid=0x125e1 runnable  

"GC Thread#0" os_prio=0 cpu=97.51ms elapsed=79.13s tid=0x00007f3124057510 nid=0x125dc runnable  

"GC Thread#1" os_prio=0 cpu=98.95ms elapsed=78.54s tid=0x00007f30c40065d0 nid=0x125ef runnable  

"GC Thread#2" os_prio=0 cpu=95.01ms elapsed=78.54s tid=0x00007f30c4007000 nid=0x125f0 runnable  

"GC Thread#3" os_prio=0 cpu=92.94ms elapsed=78.54s tid=0x00007f30c4007a30 nid=0x125f1 runnable  

"GC Thread#4" os_prio=0 cpu=109.76ms elapsed=78.54s tid=0x00007f30c4008460 nid=0x125f2 runnable  

"GC Thread#5" os_prio=0 cpu=99.87ms elapsed=78.54s tid=0x00007f30c4008e90 nid=0x125f3 runnable  

"GC Thread#6" os_prio=0 cpu=87.95ms elapsed=78.54s tid=0x00007f30c40098c0 nid=0x125f4 runnable  

"GC Thread#7" os_prio=0 cpu=104.22ms elapsed=78.54s tid=0x00007f30c400a2f0 nid=0x125f5 runnable  

"GC Thread#8" os_prio=0 cpu=100.30ms elapsed=78.54s tid=0x00007f30c400ad60 nid=0x125f6 runnable  

"GC Thread#9" os_prio=0 cpu=109.09ms elapsed=78.54s tid=0x00007f30c400b7d0 nid=0x125f7 runnable  

"G1 Main Marker" os_prio=0 cpu=0.88ms elapsed=79.13s tid=0x00007f3124068560 nid=0x125dd runnable  

"G1 Conc#0" os_prio=0 cpu=110.75ms elapsed=79.13s tid=0x00007f31240694c0 nid=0x125de runnable  

"G1 Conc#1" os_prio=0 cpu=114.56ms elapsed=76.61s tid=0x00007f30d8000eb0 nid=0x12601 runnable  

"G1 Conc#2" os_prio=0 cpu=109.70ms elapsed=76.61s tid=0x00007f30d80018f0 nid=0x12602 runnable  

"G1 Refine#0" os_prio=0 cpu=5.16ms elapsed=79.13s tid=0x00007f31241a5ce0 nid=0x125df runnable  

"G1 Refine#1" os_prio=0 cpu=4.09ms elapsed=76.84s tid=0x00007f30d0000eb0 nid=0x125f8 runnable  

"G1 Refine#2" os_prio=0 cpu=3.58ms elapsed=76.84s tid=0x00007f3058000eb0 nid=0x125f9 runnable  

"G1 Refine#3" os_prio=0 cpu=3.30ms elapsed=76.84s tid=0x00007f305c000eb0 nid=0x125fa runnable  

"G1 Refine#4" os_prio=0 cpu=2.86ms elapsed=76.84s tid=0x00007f3050000eb0 nid=0x125fb runnable  

"G1 Refine#5" os_prio=0 cpu=2.68ms elapsed=76.84s tid=0x00007f3054000eb0 nid=0x125fc runnable  

"G1 Refine#6" os_prio=0 cpu=2.28ms elapsed=76.84s tid=0x00007f3048000eb0 nid=0x125fd runnable  

"G1 Refine#7" os_prio=0 cpu=2.14ms elapsed=76.84s tid=0x00007f304c000eb0 nid=0x125fe runnable  

"G1 Refine#8" os_prio=0 cpu=0.69ms elapsed=76.84s tid=0x00007f3040000eb0 nid=0x125ff runnable  

"G1 Refine#9" os_prio=0 cpu=0.11ms elapsed=76.84s tid=0x00007f3044000eb0 nid=0x12600 runnable  

"G1 Service" os_prio=0 cpu=30.78ms elapsed=79.13s tid=0x00007f31241a6bd0 nid=0x125e0 runnable  

"VM Periodic Task Thread" os_prio=0 cpu=48.55ms elapsed=79.12s tid=0x00007f31241fa950 nid=0x125eb waiting on condition  

JNI global refs: 18, weak refs: 0

Heap
 garbage-first heap   total 524288K, used 187696K [0x0000000417000000, 0x0000000800000000)
  region size 8192K, 11 young (90112K), 2 survivors (16384K)
 Metaspace       used 31254K, committed 31680K, reserved 1114112K
  class space    used 3511K, committed 3712K, reserved 1048576K

```

**Comment by phillip-kruger** [comment]
I can't really find anything that allows me to fix this. What I (think) I know so far:

- This is related to the test container for keycloak 
- The container does not stop (close) on ctl-c
- Even if I stop this manually with podman stop it still hangs and can not start up. 
- Even if I restart the podman service (systemctl restart podman) it still hangs and can not start up.
- It does not seem like there was a new version of podman released that could indicate a change.

Does anyone else that use podman get this ?

**Comment by stalep** [comment]
After updating to Fedora 38 we have issues with Horreum (https://github.com/Hyperfoil/Horreum) test suite (Horreum is based on Quarkus using Keycloak). The test suite hangs and after in kill it I see two docker.io/testcontainers/ryuk:0.3.4 running and on docker.io/library/postgres:13 when using 'podman ps'.
I'm thinking it's related to this issue as we did not have any issues before Fedora 38.

**Comment by cgruver** [comment]
I am seeing similar issues with Quarkus 3.3.2 in OpenShift Dev Spaces / Eclipse Che.

If I use a VS Code task to start live dev mode, it does not stop when I stop the task.  I cannot restart dev mode at this point because the required ports are still bound by the previous process.

If I start dev mode from a terminal, it requires two `CTRL+C` combinations to stop it.

**Comment by cgruver** [comment]
The above might have been self inflicted...  I can no longer reproduce it.
