### ISSUE TITLE
Quarkus-opentelemetry-exporter-otlp requires javax class

### ISSUE THREAD

**Issue by JiriOndrusek** [quarkusio/quarkus#33906]
### Describe the bug

I tried opentelemetry quickstart  (https://github.com/quarkusio/quarkus-quickstarts/tree/main/opentelemetry-quickstart). Switched to quarkus from 'main' branch by using `<quarkus.platform.version>999-SNAPSHOT</quarkus.platform.version>`.
I added 

```
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-opentelemetry-exporter-otlp</artifactId>
            </dependency>
```

(to simulate an error in example on camel-quarkus)
and I'm getting:

```
2023-06-08 13:06:18,683 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: javax/enterprise/inject/spi/CDI
	at io.quarkus.opentelemetry.exporter.otlp.runtime.OtlpRecorder.installBatchSpanProcessorForOtlp(OtlpRecorder.java:40)
	at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp727556406.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.OtlpExporterProcessor$installBatchSpanProcessorForOtlp727556406.deploy(Unknown Source)
	... 13 more
Caused by: java.lang.ClassNotFoundException: javax.enterprise.inject.spi.CDI
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
	... 16 more

````

### Expected behavior

There should be no starting failure because of classNotFoundException.

### Quarkus version or git rev

'main' branch, rev 5ed7597ea415438a66c9e3f392e15b5d5aff4951

**Comment by brunobat** [comment]
@JiriOndrusek the quarkus-opentelemetry-exporter-otlp no longer exists. On Quarkus 3 you just need quarkus-opentelemetry. 
This default exporter is already included on it.

**Comment by JiriOndrusek** [comment]
Thanks for the explanation, I'll check if  camel-quarkus problem could be solved by removing the exporter.

**Comment by brunobat** [comment]
Thanks @JiriOndrusek
