### ISSUE TITLE
Cannot push with jib to private registry and https

### ISSUE THREAD

**Issue by Jeansen** [quarkusio/quarkus#33917]
### Describe the bug

Building and pushing to a private registry (harbor), fails , but manually I can push without problems.

### Expected behavior

Build and push successful.

### Actual behavior

Build fails.
I see repeatedly: GET https://<my-reg-server>/v2/ failed and will be retried

### How to Reproduce?

Create any simple Quarkus Demo App.
Have a local registry.
Put the following in your application.properties:
```
quarkus.container-image.username=<user>
quarkus.container-image.password=<password>
quarkus.container-image.push=true
quarkus.container-image.builder=jib
quarkus.container-image.registry=<your registry>
quarkus.container-image.build=true
quarkus.container-image.insecure=false
```

### Output of `uname -a` or `ver`

Linux omph-laptop 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.7 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.1.1

### Additional information

If I do `curl -v --basic -u <user>:<password> https://<my-reg-server>/v2/_catalog` I works without any problem. I can also do a push, e.g. with `docker login` and having provided my user and password.

If I set `quarkus.container-image.insecure=true`, I see a lot of `Cannot verify server at https://<my-reg-server>/v2/... . Attempting again with no TLS verification.` But it works.

**Comment by Jeansen** [comment]
You can try it yourself, the code is now here: https://github.com/Jeansen/lp39a

**Comment by Jeansen** [comment]
For what it's worth, here's the relevant debug part:
```
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':quarkusAppPartsBuild'.
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > There was a failure while executing work items
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           [error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromNative threw an exception: java.lang.RuntimeException: Unable to create container image
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:258)
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromNative(JibProcessor.java:224)
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
2023-06-12T14:16:57.249+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at java.base/java.lang.Thread.run(Thread.java:833)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at org.jboss.threads.JBossThread.run(JBossThread.java:501)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         Caused by: com.google.cloud.tools.jib.api.RegistryUnauthorizedException: Unauthorized for registry-1.docker.io/marcel/lp39a
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:163)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:114)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:623)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.cloud.tools.jib.registry.RegistryClient.checkBlob(RegistryClient.java:474)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.cloud.tools.jib.builder.steps.PushBlobStep.call(PushBlobStep.java:74)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.cloud.tools.jib.builder.steps.PushLayerStep.call(PushLayerStep.java:92)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.cloud.tools.jib.builder.steps.PushLayerStep.call(PushLayerStep.java:33)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at java.base/java.lang.Thread.run(Thread.java:833)
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         Caused by: com.google.cloud.tools.jib.http.ResponseException: 401 Unauthorized
2023-06-12T14:16:57.250+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         HEAD https://registry-1.docker.io/v2/marcel/lp39a/blobs/sha256:17c36892760463035827d059181dd10b8248658f80b1dbe94ad6e18b32a4bc74
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:355)
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:266)
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:138)
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           ... 12 more
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         Caused by: com.google.api.client.http.HttpResponseException: 401 Unauthorized
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]         HEAD https://registry-1.docker.io/v2/marcel/lp39a/blobs/sha256:17c36892760463035827d059181dd10b8248658f80b1dbe94ad6e18b32a4bc74
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:349)
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           ... 14 more
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --stacktrace option to get the stack trace.
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --scan to get full insights.
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2023-06-12T14:16:57.251+0200 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
2023-06-12T14:16:57.251+0200 [WARN] [org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler] 
```

**Comment by Jeansen** [comment]
I don't konw, why it tries to connect to https://registry-1.docker.io/v2/, I expicitly set it in the application.yaml

**Comment by geoand** [comment]
No problem 😸
