### ISSUE TITLE
Internal Server Error when a Gradle project is generated with Azure function extension

### ISSUE THREAD

**Issue by danieloh30** [quarkusio/quarkus#33928]

**Comment by aloubyansky** [comment]
Trying it locally with the CLI I see
```
[aloubyansky@localhost playground]$ quarkus create -x azure-functions-http --gradle -e
Creating an app (default project type, see --help).
-----------
selected extensions: 
- io.quarkus:quarkus-azure-functions-http

io.quarkus.devtools.codestarts.CodestartStructureException: something is wrong, smart-pom-merge file strategy must only be used on maven projects
	at io.quarkus.devtools.codestarts.core.strategy.SmartPomMergeCodestartFileStrategyHandler.lambda$process$1(SmartPomMergeCodestartFileStrategyHandler.java:35)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.quarkus.devtools.codestarts.core.strategy.SmartPomMergeCodestartFileStrategyHandler.process(SmartPomMergeCodestartFileStrategyHandler.java:35)
	at io.quarkus.devtools.codestarts.core.CodestartProcessor.writeFiles(CodestartProcessor.java:84)
	at io.quarkus.devtools.codestarts.core.CodestartProjectGeneration.generateProject(CodestartProjectGeneration.java:53)
	at io.quarkus.devtools.codestarts.core.DefaultCodestartProjectDefinition.generate(DefaultCodestartProjectDefinition.java:56)
	at io.quarkus.devtools.commands.handlers.CreateProjectCommandHandler.execute(CreateProjectCommandHandler.java:158)
	at io.quarkus.cli.CreateApp.call(CreateApp.java:91)
	at io.quarkus.cli.CreateApp.call(CreateApp.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.quarkus.cli.Create.call(Create.java:35)
	at io.quarkus.cli.Create.call(Create.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.quarkus.cli.QuarkusCli.run(QuarkusCli.java:121)
	at io.quarkus.cli.QuarkusCli_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.cli.Main.main(Main.java:9)

[ERROR] ❗  Unable to create project: something is wrong, smart-pom-merge file strategy must only be used on maven projects
```

**Comment by aloubyansky** [comment]
@ia3andy it's not just a code.quarkus issue

**Comment by ia3andy** [comment]
@aloubyansky yeah it's a known issue, the codestart is not compatible with Gradle per design

**Comment by patriot1burke** [comment]
This no longer happens in "main" because the azure-functions-http extension and codestart supports gradle now.  The bug still exists though as the old codestart was marked "maven only".

**Comment by danieloh30** [comment]
@patriot1burke I have still the same error in 3.1.1 in code.quarkus.io. I don't see "maven only" mark on the page either
<img width="1563" alt="image" src="https://github.com/quarkusio/quarkus/assets/14066977/cbeac225-4879-4335-a9f9-eb222209629c">
