### ISSUE TITLE
Can't unmarshal XML to Java in native mode.

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#33936]
### Describe the bug

Hello,

In a Camel application, running on Quarkus 2.16.6, I have a route which, among others, is unmarshalling an XML payload into the associated Java class. This works as expected in JVM mode but, in native mode, it raises the following exception:

    2023-06-09 14:32:38,319 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): javax.xml.bind.JAXBException: "fr.simplex_software.quarkus.camel.integrations.jaxb" doesnt contain ObjectFactory.class or jaxb.index
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:254)
        at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:195)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:153)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:339)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:478)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:435)
    ...

However, the mentioned package contains the ObjectFactory class, as shown below:

      382 Thu Jun 08 16:51:16 CEST 2023 fr/simplex_software/quarkus/camel/integrations/jaxb/package-info.class
      1713 Thu Jun 08 16:51:16 CEST 2023 fr/simplex_software/quarkus/camel/integrations/jaxb/Bank.class
      2855 Thu Jun 08 16:51:16 CEST 2023 fr/simplex_software/quarkus/camel/integrations/jaxb/BankAccount.class
      1588 Thu Jun 08 16:51:16 CEST 2023 fr/simplex_software/quarkus/camel/integrations/jaxb/ObjectFactory.class
      2297 Thu Jun 08 16:51:16 CEST 2023 fr/simplex_software/quarkus/camel/integrations/jaxb/MoneyTransfer.class
      1621 Thu Jun 08 16:51:16 CEST 2023 fr/simplex_software/quarkus/camel/integrations/jaxb/BankAccountType.class
      2275 Thu Jun 08 16:51:16 CEST 2023 fr/simplex_software/quarkus/camel/integrations/jaxb/BankAddress.class
      1459 Thu Jun 08 16:51:16 CEST 2023 fr/simplex_software/quarkus/camel/integrations/jaxb/MoneyTransfers.class

Here is the code which triggers the exception:

    private JaxbDataFormat jaxbDataFormat = new JaxbDataFormat(true);
    ....

    @PostConstruct
    public void postConstruct()
    {
      jaxbDataFormat.setContextPath("fr.simplex_software.quarkus.camel.integrations.jaxb");
    }
    ....

    @Override
    public void configure() throws Exception
    {
      from(aws2Sqs(queueName).useDefaultCredentialsProvider(true).region("eu-west-3"))
        .unmarshal(jaxbDataFormat)
        .marshal().json(JsonLibrary.Jsonb)
        .setHeader(Exchange.HTTP_METHOD, constant("POST"))
        .to(http(uri));
    }
    ...

### Expected behavior

The JAXB unmarshalling process has to work the same way as it does in JVM mode.

### Actual behavior

The unmarshalling process raises the mentioned exception.

### How to Reproduce?

To reproduce:

    $ git clone https://github.com/nicolasduminil/aws-camelk
    $ cd aws-camelk
    $ git checkout native
    $ cd aws-camelk-sqs
    $ mvn -DskipTests clean install
    $ ./target/aws-camelk-sqs-runner

### Output of `uname -a` or `ver`

    $ Linux nicolas-XPS-15-9570 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
    java version "17.0.6" 2023-01-17 LTS
    Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
    Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### GraalVM version (if different from Java)

    quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17

### Quarkus version or git rev

    2.16.6.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

    Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
    Maven home: /opt/apache-maven-3.6.3
    Java version: 17.0.6, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-17
    Default locale: en_US, platform encoding: UTF-8
    OS name: "linux", version: "5.15.0-73-generic", arch: "amd64", family: "unix"

**Comment by nicolasduminil** [comment]
anyone please ?

**Comment by Sgitario** [comment]
The reproducer failed for a different reason for me:

```
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: aws2-sqs://myQueue?region=eu-west-3&useDefaultCredentialsProvider=true due to: The SqsClient is required but has not been detected/configured.
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:1008)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:919)
	at org.apache.camel.builder.endpoint.AbstractEndpointBuilder.resolve(AbstractEndpointBuilder.java:68)
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:93)
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:75)
	... 24 more
Caused by: java.lang.IllegalStateException: The SqsClient is required but has not been detected/configured.
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer.client(SqsClientProducer.java:30)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_ProducerMethod_client_24ac7b8ada82ac4b22f84052195e7c8e880e0ee7_Bean.create(Unknown Source)
	at io.quarkus.amazon.sqs.runtime.SqsClientProducer_ProducerMethod_client_24ac7b8ada82ac4b22f84052195e7c8e880e0ee7_Bean.create(Unknown Source)

```

However, your problem is that the dependency "fr.simplex-software.quarkus.camel.integrations:aws-camelk-model" is missing the Jandex index. More information about this in [here](https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index).

You can try adding the following properties:

```
quarkus.index-dependency.acme.group-id=fr.simplex-software.quarkus.camel.integrations
quarkus.index-dependency.acme.artifact-id=aws-camelk-model
```

Another tip could be trying to configure the model for reflection: https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection

**Comment by gsmet** [comment]
`jandex-maven-plugin` should work but you need to make sure you call the `make-index` goal.

**Comment by nicolasduminil** [comment]
I need to amend my comment above. 

Yes, `jandex-maven-plugin` works and, the reason it didn't in my previous attempt is that I forgot to compile the associated module after modification.

On the other hand, configuring for reflection works as well and, in my case, the reason it didn't is that I have configured a wrong module.

In conclusion, as opposed to what I was stating previously, all the three methods work and using the `jandex-maven-plugin ` is probably the most appropriate one.

Sorry, for the mistaken diagnostic and for the small-talk.
