### ISSUE TITLE
Quarkus CXF and Amazon DynamoDB Extension does not work together - throws ChainBuildException

### ISSUE THREAD

**Issue by knuspertante** [quarkusio/quarkus#33955]
### Describe the bug

Hey, 

unfortunately I doesn't know where this issue belongs to. 

The CXF and DynamoDB extension doesn't work together. As far I understand, both want to generate the same Bean in build phase. 

Error Message: 
```sh
Caused by: io.quarkus.builder.ChainBuildException: Cycle detected:
		   io.quarkiverse.cxf.deployment.CxfClientProcessor#generateClientProducers produced class io.quarkus.arc.deployment.GeneratedBeanBuildItem
		to io.quarkus.arc.deployment.BeanArchiveProcessor#build produced class io.quarkus.arc.deployment.BeanArchiveIndexBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#initialize produced class io.quarkus.arc.deployment.ContextRegistrationPhaseBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#registerBeans produced class io.quarkus.arc.deployment.BeanRegistrationPhaseBuildItem
		to io.quarkus.amazon.dynamodb.deployment.DynamodbProcessor#discover produced class io.quarkus.amazon.common.deployment.RequireAmazonClientBuildItem
		to io.quarkus.amazon.dynamodb.deployment.DynamodbProcessor#setup produced class io.quarkus.deployment.builditem.ExtensionSslNativeSupportBuildItem
		to io.quarkus.deployment.steps.NativeImageConfigBuildStep#build produced class io.quarkus.deployment.builditem.nativeimage.RuntimeInitializedClassBuildItem
		to io.quarkiverse.cxf.deployment.CxfClientProcessor#collectClients produced class io.quarkiverse.cxf.deployment.CxfClientBuildItem
		to io.quarkiverse.cxf.deployment.CxfClientProcessor#generateClientProducers
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:375)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:339)
	at io.quarkus.builder.BuildChainBuilder.build(BuildChainBuilder.java:249)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:142)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	... 47 more
```

Perhaps @ppalaga (from quarkus-cxf extension) or @scrocquesel (from amazon extension) could help?

### Expected behavior

Both extensions should work with each other

### Actual behavior

Detail Message from ChainBuildException
```sh
Cycle detected:
		   io.quarkiverse.cxf.deployment.CxfClientProcessor#generateClientProducers produced class io.quarkus.arc.deployment.GeneratedBeanBuildItem
		to io.quarkus.arc.deployment.BeanArchiveProcessor#build produced class io.quarkus.arc.deployment.BeanArchiveIndexBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#initialize produced class io.quarkus.arc.deployment.ContextRegistrationPhaseBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#registerBeans produced class io.quarkus.arc.deployment.BeanRegistrationPhaseBuildItem
		to io.quarkus.amazon.dynamodb.deployment.DynamodbProcessor#discover produced class io.quarkus.amazon.common.deployment.RequireAmazonClientBuildItem
		to io.quarkus.amazon.dynamodb.deployment.DynamodbProcessor#setup produced class io.quarkus.deployment.builditem.ExtensionSslNativeSupportBuildItem
		to io.quarkus.deployment.steps.NativeImageConfigBuildStep#build produced class io.quarkus.deployment.builditem.nativeimage.RuntimeInitializedClassBuildItem
		to io.quarkiverse.cxf.deployment.CxfClientProcessor#collectClients produced class io.quarkiverse.cxf.deployment.CxfClientBuildItem
		to io.quarkiverse.cxf.deployment.CxfClientProcessor#generateClientProducers
```

### How to Reproduce?

Reproducer: https://github.com/knuspertante/reproducer-cxf-dynamodb.git

1. git clone https://github.com/knuspertante/reproducer-cxf-dynamodb.git
2. cd reproducer-cxf-dynamodb
3. ./mvnw clean verify

### Output of `java -version`

OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08)

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08)

### Quarkus version or git rev

3.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.8

**Comment by ppalaga** [comment]
Thanks for the report @knuspertante! You win the prize for filing the first issue with a reproducer using `io.quarkus.platform:quarkus-cxf-bom` :-)

I need to check whether this is the same issue as https://github.com/quarkiverse/quarkus-cxf/issues/860

**Comment by scrocquesel** [comment]
> Thanks for the report @knuspertante! You win the prize for filing the first issue with a reproducer using `io.quarkus.platform:quarkus-cxf-bom` :-)
> 
> I need to check whether this is the same issue as [quarkiverse/quarkus-cxf#860](https://github.com/quarkiverse/quarkus-cxf/issues/860)

I guess it is.
On my side, I can split the `setupExtension` build step and move `ExtensionSslNativeSupportBuildItem` to another build step.
But, I first want to try if I can get rid of `BeanRegistrationPhaseBuildItem`.

BTW, I was thinking of generating client producer classes. Guess, I will be a lot inspired by your `generateCxfClientProducer` method.

**Comment by geoand** [comment]
@ppalaga This does not seem like a Quarkus core issue, right?

**Comment by ppalaga** [comment]
> @ppalaga This does not seem like a Quarkus core issue, right?

Yes, that's how I'd see it. However, it is not clear yet whether it should be fixed in Quarkus CXF or in quarkus-amazon-services

**Comment by geoand** [comment]
Understood, thanks.

I'll close this one in any case.

**Comment by knuspertante** [comment]
@geoand sure this is not a issue for quarkus core but how could we track this kind of issues? As I wrote or @ppalaga said, it is not clear which extension is the error origin. 

@ppalaga is it ok for you to track this issue in https://github.com/quarkiverse/quarkus-cxf/issues/860 or will you work on this issue further?

**Comment by geoand** [comment]
> but how could we track this kind of issues?

That's for people who use and develop these extensions to decide. We can't have Quarkus Core repo be a catch all (although I'll grant that it sometimes makes sense for it to be the first place an issue is reported) issue tracker for all Quarkus extensions

**Comment by scrocquesel** [comment]
> @geoand sure this is not a issue for quarkus core but how could we track this kind of issues? As I wrote or @ppalaga said, it is not clear which extension is the error origin. 
> 
> @ppalaga is it ok for you to track this issue in https://github.com/quarkiverse/quarkus-cxf/issues/860 or will you work on this issue further?

That's fine for me.
