### ISSUE TITLE
"Could not set value of type" Hibernate 6 org.hibernate.PropertyAccessException only on quarkus test rerun

### ISSUE THREAD

**Issue by sigi-tw** [quarkusio/quarkus#33953]
### Describe the bug

We upgraded from quarkus 2 to quarkus 3 (+h5 to h6) and use the PostgreSQLEnumType from https://github.com/vladmihalcea/hypersistence-utils.

The tests we have are fine, the application itself is also fine but when we re-run the test case in Quarkus, an exception is thrown for all cases where we use a Type which extends ImmutableDynamicParameterizedType from hibernate 6.

https://github.com/vladmihalcea/hypersistence-utils/blob/master/hypersistence-utils-hibernate-62/src/main/java/io/hypersistence/utils/hibernate/type/basic/PostgreSQLEnumType.java

### Expected behavior

Re-running tests should not fail.

### Actual behavior

Following exception is thrown after re-run:

```
2023-06-09 23:13:05,427 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #2 ====================
2023-06-09 23:13:05,428 ERROR [io.qua.test] (Test runner thread) Test CountryTest#Switzerland has a City attached() failed 
: org.hibernate.PropertyAccessException: Could not set value of type [foo.bar.enums.CurrencyCode] : 'foo.bar.entity.City.baseCurrency' (setter)
        at org.hibernate.property.access.spi.SetterFieldImpl.set(SetterFieldImpl.java:86)
        at org.hibernate.property.access.spi.EnhancedSetterImpl.set(EnhancedSetterImpl.java:40)
        at org.hibernate.persister.entity.AbstractEntityPersister.setPropertyValues(AbstractEntityPersister.java:4155)
        at org.hibernate.sql.results.graph.entity.AbstractEntityInitializer.initializeEntityInstance(AbstractEntityInitializer.java:844)
        at org.hibernate.sql.results.graph.entity.AbstractEntityInitializer.initializeEntity(AbstractEntityInitializer.java:804)
        at org.hibernate.sql.results.graph.entity.AbstractEntityInitializer.initializeInstance(AbstractEntityInitializer.java:790)
        at org.hibernate.sql.results.internal.InitializersList.initializeInstance(InitializersList.java:70)
        at org.hibernate.sql.results.internal.StandardRowReader.coordinateInitializers(StandardRowReader.java:111)
        at org.hibernate.sql.results.internal.StandardRowReader.readRow(StandardRowReader.java:87)
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:179)
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:361)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:168)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:93)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
        at org.hibernate.loader.ast.internal.CollectionBatchLoaderArrayParam.initializeKeys(CollectionBatchLoaderArrayParam.java:145)
        at org.hibernate.loader.ast.internal.CollectionBatchLoaderArrayParam.load(CollectionBatchLoaderArrayParam.java:107)
        at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:679)
        at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:75)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
        at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1702)
        at org.hibernate.collection.spi.AbstractPersistentCollection.lambda$initialize$3(AbstractPersistentCollection.java:617)
        at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:265)
        at org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:615)
        at org.hibernate.collection.spi.AbstractPersistentCollection.read(AbstractPersistentCollection.java:136)
        at org.hibernate.collection.spi.AbstractPersistentCollection.lambda$readSize$0(AbstractPersistentCollection.java:163)
        at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:265)
        at org.hibernate.collection.spi.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:148)
        at org.hibernate.collection.spi.PersistentBag.isEmpty(PersistentBag.java:360)
        at foo.bar.country.CountryTest.Switzerland has a City attached(CountryTest.kt:33)
Caused by: java.lang.IllegalArgumentException: Can not set foo.bar.enums.CurrencyCode field foo.bar.entity.City.baseCurrency to foo.bar.enums.CurrencyCode
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115)
        at java.base/java.lang.reflect.Field.set(Field.java:834)
        at org.hibernate.property.access.spi.SetterFieldImpl.set(SetterFieldImpl.java:55)
        ... 29 more
```

### Example project, java based without panache
https://github.com/neukunft/java-no-panache (most simplified version)

### Example project, java based
https://github.com/neukunft/pg-issue-java

### Example project, kotlin based with panache (original setup)
https://github.com/neukunft/pg-issue

### Output of `uname -a` or `ver`

happens on linux and macos

### Output of `java -version`

jdk17 and jdk20

### Quarkus version or git rev

3.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by geoand** [comment]
I kinda doubt this is a Quarkus specific issue, but I'll let the Hibernate folks comment

**Comment by yrodiere** [comment]
Thanks for the report.

> Can not set foo.bar.enums.CurrencyCode field foo.bar.entity.City.baseCurrency to foo.bar.enums.CurrencyCode

This screams "classloader issue" to me, but I'll try to debug to confirm this.

**Comment by yrodiere** [comment]
So, I'm getting a different error with your reproducer, for some reason. Probably because you switched from Kotlin to Java?

Here's the error I'm getting:

```
2023-06-12 10:02:33,824 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #2 ==================== [Error Occurred After Shutdown]
2023-06-12 10:02:33,824 ERROR [io.qua.test] (Test runner thread) Test EnumTest#testPersistingEntityAndReadingAllEntities() failed 
 [Error Occurred After Shutdown]: java.lang.AssertionError: Unexpected value type (expected : DemoEnum) : The SOME enum is mapped to ordinal: 0 (DemoEnum)
        at org.hibernate.sql.exec.internal.JdbcParameterBindingImpl.<init>(JdbcParameterBindingImpl.java:23)
        at org.hibernate.sql.exec.spi.JdbcParameterBindings.createAndAddBinding(JdbcParameterBindings.java:97)
        at org.hibernate.type.BasicType.forEachDisassembledJdbcValue(BasicType.java:134)
        at org.hibernate.metamodel.mapping.Bindable.forEachJdbcValue(Bindable.java:194)
        at org.hibernate.sql.exec.spi.JdbcParameterBindings.registerParametersForEachJdbcValue(JdbcParameterBindings.java:78)
        at org.hibernate.sql.exec.spi.JdbcParameterBindings.registerParametersForEachJdbcValue(JdbcParameterBindings.java:69)
        at org.hibernate.query.sqm.internal.SqmUtil.createValueBindings(SqmUtil.java:409)
        at org.hibernate.query.sqm.internal.SqmUtil.createJdbcParameterBindings(SqmUtil.java:338)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.buildCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:358)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:268)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:244)
        at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:518)
        at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:367)
        at org.hibernate.query.Query.getResultList(Query.java:119)
        at EnumTest.testPersistingEntityAndReadingAllEntities(EnumTest.java:60)


2023-06-12 10:02:33,826 ERROR [io.qua.test] (Test runner thread) Test EnumTest#testListingEntityWithPGEnum() failed 
 [Error Occurred After Shutdown]: java.lang.AssertionError: Unexpected value type (expected : DemoEnum) : The VALUE enum is mapped to ordinal: 2 (DemoEnum)
        at org.hibernate.sql.exec.internal.JdbcParameterBindingImpl.<init>(JdbcParameterBindingImpl.java:23)
        at org.hibernate.sql.exec.spi.JdbcParameterBindings.createAndAddBinding(JdbcParameterBindings.java:97)
        at org.hibernate.type.BasicType.forEachDisassembledJdbcValue(BasicType.java:134)
        at org.hibernate.metamodel.mapping.Bindable.forEachJdbcValue(Bindable.java:194)
        at org.hibernate.sql.exec.spi.JdbcParameterBindings.registerParametersForEachJdbcValue(JdbcParameterBindings.java:78)
        at org.hibernate.sql.exec.spi.JdbcParameterBindings.registerParametersForEachJdbcValue(JdbcParameterBindings.java:69)
        at org.hibernate.query.sqm.internal.SqmUtil.createValueBindings(SqmUtil.java:409)
        at org.hibernate.query.sqm.internal.SqmUtil.createJdbcParameterBindings(SqmUtil.java:338)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.buildCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:358)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:268)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:244)
        at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:518)
        at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:367)
        at org.hibernate.query.Query.getResultList(Query.java:119)
        at EnumTest.testListingEntityWithPGEnum(EnumTest.java:42)
```

The error message does not make sense, but that's because of some questionable `toString()` implementations. This does seem caused by a classloader issue, so this is probably a bug in Quarkus' testing support (some classloader problem).

How to witness the problem:

* Take the reproducer at https://github.com/neukunft/java-no-panache
* Remove the `volume` section in `docker-compose.yaml` (it's not portable, and it's not useful)
* Run `mvn clean quarkus:dev`
* Press `r` => Tests will pass
* Press `r` again => Tests will fail
* Connect to the running application with your debugger
* Put a breakpoint in `org.hibernate.sql.exec.internal.JdbcParameterBindingImpl`, line 22 (the `assert` in the constructor), with the following condition:
  ```
  !(bindValue == null || jdbcMapping == null || jdbcMapping.getJdbcJavaType().isInstance( bindValue ))
  ```
* When the breakpoint is reached, evaluate the following expression:
  ```
  jdbcMapping.getJdbcJavaType().getJavaTypeClass().getName()
		+ " vs. " + bindValue.getClass().getName()
		+ " / " +
		System.identityHashCode( jdbcMapping.getJdbcJavaType().getJavaTypeClass() )
		+ " vs. " + System.identityHashCode( bindValue.getClass().toString() )
  ```
* You will get something like this, proving there are two `DemoEnum` classes:
  ```
  DemoEnum vs. DemoEnum / 2024429247 vs. 1045903903
  ```

Note: `DemoEnum` in this reproducer is in the default package, and I suspected it could be related to the problem, but it isn't. Moving the classes to an actual package doesn't change the outcome.

Regardless, this is not an ORM problem. Requalifying this as a testing problem.

**Comment by yrodiere** [comment]
cc @geoand , I think testing classloaders are an area you're familiar with? :)

**Comment by geoand** [comment]
Taking a quick look, this is almost certainly **not** a Quarkus issue, but either an issue in Hibernate ORM or the hypersistence-utils library, but I need to investigate more.

**Comment by neukunft** [comment]
Hi, thanks for taking a look!

Just for reference, we initially opened a ticket here...
https://github.com/vladmihalcea/hypersistence-utils/issues/634

**Comment by geoand** [comment]
I figured out the problem and it's in _hypersistence-utils_ , specifically:

https://github.com/vladmihalcea/hypersistence-utils/blob/bee14b1b5cd03eda02b6469ef030124caa457e6c/hypersistence-utils-hibernate-62/src/main/java/io/hypersistence/utils/hibernate/util/ReflectionUtils.java#L21

is very unfriendly to ClassLoaders as it assumes that a class name always maps to the same Class 😉.

There is nothing we can do about this in Quarkus itself, but  if there is a Quarkus extension for this library, a issue should be reported there and ask for lifecycle hook that clears that cache.

**Comment by yrodiere** [comment]
Thanks @geoand , sorry I didn't look further. I wouldn't have imagined Hypersistence would cache classes like that...

**Comment by geoand** [comment]
No problem
