### ISSUE TITLE
LambdaDevServicesContinuousTestingTestCase.testLambda test failure 

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#33963]
### Describe the bug

The test io.quarkus.amazon.lambda.deployment.testing.LambdaDevServicesContinuousTestingTestCase.testLambda fails in JDK 19 as noticed in https://github.com/quarkusio/quarkus/pull/33958#issuecomment-1586481744.
The failure report is 
```
org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
```

### Expected behavior

The test should pass consistently 

### Actual behavior

The test fails as can be seen in the linked PR

### Output of `uname -a` or `ver`

CI

**Comment by gsmet** [comment]
@patriot1burke I will disable this test as it is causing a lot of CI failures and it makes it harder for us to make progress.

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus/pull/34007

**Comment by patriot1burke** [comment]
This stuff was committed a long time ago.  Was this test always failing?  If not, then, you could be masking something deeper.

**Comment by stuartwdouglas** [comment]
Further context (note the timestamps):

```
2023-06-11T23:55:20.6540806Z 2023-06-11 23:55:20,646 DEBUG [io.qua.ama.lam.run.MockEventServer] (vert.x-worker-thread-7) Starting processing 15517ecf-551c-42d4-b0fe-e4c62a12eec0, added to pending request map
2023-06-11T23:55:50.6983092Z 2023-06-11 23:55:50,679 INFO  [io.quarkus] (Test runner thread) quarkus-amazon-lambda-deployment(test application) stopped in 0.001s
```

**Comment by gsmet** [comment]
It's disabled now, it was really in our way. Please have a look ASAP so that we can enable it again.

**Comment by gsmet** [comment]
Going to close for no activity.
