### ISSUE TITLE
401 error,  ID token verification failure

### ISSUE THREAD

**Issue by comdata** [quarkusio/quarkus#34015]
### Describe the bug

Website with OIDC and keycloak delivers 401 error.

In the log I find:

[io.qua.oid.run.CodeAuthenticationMechanism] (vert.x-eventloop-thread-3) ID token verification failure: Cannot invoke "String.length()" because "str" is null 

What is wrong?

### Expected behavior

Authentication works

### Additional information

Quarkus 3.1.1.Final

**Comment by sberyozkin** [comment]
@comdata Can you provide more information please or ideally a reproducer ? Is this error message coming from Keycloak or somewhere else, I don't recall having any log message like `Cannot invoke "String.length()" because "str" is null` produced by Quarkus OIDC itself

**Comment by sberyozkin** [comment]
@comdata FYI, `quarkus-oidc` does not have a `str` String variable anywhere in its code. Is it something that you declare, for example, in the custom `SecurityIdentityAugmentor` ?

**Comment by comdata** [comment]
The error seems to be handled at: https://github.com/quarkusio/quarkus/blob/210b2a332e855aee3a73f71f7cdb7d10a3467c6f/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L315

I have no SecurityIdentityAugmentor  and the code worked fine on 2.16.x

**Comment by comdata** [comment]
The error message comes from running .\mvnw quarkus:dev and accessing it on localhost

**Comment by sberyozkin** [comment]
@comdata Sure, if you'd like me to help, I'd need something more concrete, please provide a reproducer, or copy and paste the test token if you can, etc, I can't do anything with the `str` related error with `str` not even in the quarkus OIDC code . 
Otherwise, try to put a breakpoint there, you'll see the problem immediately.

**Comment by comdata** [comment]
will need to set something up

**Comment by comdata** [comment]
What I got from the debugger was:

2023-06-13 16:47:25,620 DEBUG [io.qua.oid.run.DefaultTenantConfigResolver] (vert.x-eventloop-thread-3) Registered TenantResolver has not provided the configuration for tenant '8a025083-dce5-41ce-9404-73e72f222bcb', using the default tenant



--
2023-06-13 16:47:25,622 DEBUG [io.qua.ver.htt.run.ForwardedParser] (vert.x-eventloop-thread-3) Recalculated absoluteURI to http://localhost:8082/


--
2023-06-13 16:47:25,624 DEBUG [io.qua.oid.run.CodeAuthenticationMechanism] (vert.x-eventloop-thread-3) State parameter can not be empty or multi-valued if the state cookie is present


--
2023-06-13 16:47:25,625 DEBUG [io.qua.ver.htt.run.sec.HttpSecurityRecorder] (vert.x-eventloop-thread-3) Authentication has failed, returning HTTP status 401


--
2023-06-13 16:47:25,627 DEBUG [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-3) RoutingContext failure (500): io.quarkus.security.AuthenticationCompletionException
        at io.quarkus.oidc.runtime.CodeAuthenticationMechanism.stateCookieIsMissing(CodeAuthenticationMechanism.java:245)
        at io.quarkus.oidc.runtime.CodeAuthenticationMechanism.processRedirectFromOidc(CodeAuthenticationMechanism.java:154)
        at io.quarkus.oidc.runtime.CodeAuthenticationMechanism.authenticate(CodeAuthenticationMechanism.java:117)
        at io.quarkus.oidc.runtime.OidcAuthenticationMechanism$1.apply(OidcAuthenticationMechanism.java:50)
        at io.quarkus.oidc.runtime.OidcAuthenticationMechanism$1.apply(OidcAuthenticationMechanism.java:44)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniMemoizeOp.subscribe(UniMemoizeOp.java:84)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
        at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AbstractAuthenticationHandler.handle(HttpSecurityRecorder.java:414)
        at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AbstractAuthenticationHandler.handle(HttpSecurityRecorder.java:368)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.handle(VertxHttpHotReplacementSetup.java:196)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.handle(VertxHttpHotReplacementSetup.java:185)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
