### ISSUE TITLE
TransactionRequiredException with @Transactional PanacheEntity instance methods

### ISSUE THREAD

**Issue by neon-dev** [quarkusio/quarkus#34013]
### Describe the bug

Not sure if it's a bug or just unintuitive behavior, as I could not find any code examples for `@Transactional` annotated PanacheEntity instance methods.
Currently we can define static `@Transactional` annotated methods like so:
```java
@Entity
public class Something extends PanacheEntity {

  @Transactional
  public static void deleteTransactionalById(Long id) {
    deleteById(id);
  }
}
```
but if we define an instance method in a similar way, calling it will throw `TransactionRequiredException`:
```java
  @Transactional
  public void deleteTransactional() {
    delete();
  }
```

### Expected behavior

Class methods and instance methods of Panache entities should both support `@Transactional` annotations.

### Actual behavior

Instance methods of Panache entities don't support `@Transactional` annotations:
```
jakarta.persistence.TransactionRequiredException: Transaction is not active, consider adding @Transactional to your method to automatically activate one.

	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.remove(TransactionScopedSession.java:165)
	at org.hibernate.engine.spi.SessionLazyDelegator.remove(SessionLazyDelegator.java:345)
	at org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_ClientProxy.remove(Unknown Source)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.delete(AbstractJpaOperations.java:124)
	at io.quarkus.hibernate.orm.panache.PanacheEntityBase.delete(PanacheEntityBase.java:80)
	at org.acme.Entity.deleteTransactional(Entity.java:11)
	at org.acme.EntityTest.deleteTransactional(EntityTest.java:12)
```
The error message is also a bit misleading, as there already is an annotation present. It's just ignored.

### How to Reproduce?

1. Download and unzip [reproducer.zip](https://github.com/quarkusio/quarkus/files/11735185/reproducer.zip)
2. Run `mvnw test`

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17

### Quarkus version or git rev

3.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8

**Comment by FroMage** [comment]
Transactions are working with CDI interceptors and entities are not beans, so they can't be intercepted. Is there any reason why you can't do your transactions in the static methods?

**Comment by neon-dev** [comment]
No, but it would be weird to delete an entity via `Entity.delete(entity)` and it's also not always very elegant to define intermediate transactional methods in the calling class.
Do you have a suggestion how to refactor this sample code without creating an annotated helper method or using `QuarkusTransaction`?
```java
class SomeClass {

  void doStuf() {
    Entity entity = getEntity()
    if (tryToDoSomethingWith(entity)) {
      entity.delete();
    }
  }
}
```

**Comment by FroMage** [comment]
Yes, OK. But usually all entity modifications are done by a method annotated with `@Transactional`, so where are you calling these entity methods?

**Comment by FroMage** [comment]
Ah, I see. You can probably do it this way:

```java
@Scheduled(every = "2s", concurrentExecution = Scheduled.ConcurrentExecution.SKIP)
void maintainTriggers() {
  ExportTrigger.<ExportTrigger>listAll().forEach(trigger -> {
    PricelistConfig config = PricelistConfig.findById(trigger.customerName);
    if (config == null) {
      delete(trigger);
    } else if (config.getChannel() == Config.exporterChannel) {
      try {
        JobKey jobKey = new JobKey(trigger.customerName);
        JobDataMap jobDataMap = new JobDataMap();
        jobDataMap.put("customerName", trigger.customerName);
        jobDataMap.put("trigger", trigger);
        scheduler.addJob(JobBuilder.newJob(ExportJob.class).withIdentity(jobKey).storeDurably().usingJobData(jobDataMap).build(), true);
        scheduler.triggerJob(jobKey);
      } catch (SchedulerException e) {
        throw new RuntimeException(e);
      } finally {
        delete(trigger);
      }
    }
  });
}

@Transactional
void delete(ExportTrigger trigger){
 trigger.delete();
}
```

I guess we could add support for this too:

```java
@Scheduled(every = "2s", concurrentExecution = Scheduled.ConcurrentExecution.SKIP)
void maintainTriggers() {
  ExportTrigger.<ExportTrigger>listAll().forEach(trigger -> {
    PricelistConfig config = PricelistConfig.findById(trigger.customerName);
    if (config == null) {
        Panache.inTransaction(t -> trigger.delete());
    } else if (config.getChannel() == Config.exporterChannel) {
      try {
        JobKey jobKey = new JobKey(trigger.customerName);
        JobDataMap jobDataMap = new JobDataMap();
        jobDataMap.put("customerName", trigger.customerName);
        jobDataMap.put("trigger", trigger);
        scheduler.addJob(JobBuilder.newJob(ExportJob.class).withIdentity(jobKey).storeDurably().usingJobData(jobDataMap).build(), true);
        scheduler.triggerJob(jobKey);
      } catch (SchedulerException e) {
        throw new RuntimeException(e);
      } finally {
        Panache.inTransaction(t -> trigger.delete());
      }
    }
  });
}
```

WDYT?

**Comment by neon-dev** [comment]
Yes, this should work. I was just looking for a way to make the delete method transactional by default and ended up doing this in the ExportTrigger class, instead of annotating it with `@Transactional`:
```java
@Override
public void delete() {
  QuarkusTransaction.joiningExisting().run(super::delete);
}
```
PS: Wouldn't `Panache.inTransaction(t -> trigger.delete())` be the same as `QuarkusTransaction.requiringNew().run(() -> trigger.delete())`?

**Comment by FroMage** [comment]
Ah yeah, you're right. This is better.

If you don't mind, I'll rephrase your issue title to "Support CDI interceptor annotations on `PanacheEntity` instance methods?" and leave it open to see if other people want this or not, because so far you're the first person to ask.

**Comment by neon-dev** [comment]
Sure, thank you very much!
