### ISSUE TITLE
Track which dev services work using kubedock

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#34051]
### Description

There have been discussion about running dev services over kubedock, to support dockerless environments.
We should first check which dev services work with `kubedock` and which are not.

**Comment by iocanel** [comment]
cc @maxandersen

**Comment by iocanel** [comment]
# jdbc-postgres (hibernate-orm-quickstart)

```
│ chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted                                                                            │
│ chmod: changing permissions of '/var/run/postgresql': Operation not permitted                                                                                 │
│ The files belonging to this database system will be owned by user "1011300000".                                                                               │
│ This user must also own the server process.                                                                                                                   │
│                                                                                                                                                               │
│ The database cluster will be initialized with locale "en_US.utf8".                                                                                            │
│ The default database encoding has accordingly been set to "UTF8".                                                                                             │
│ The default text search configuration will be set to "english".                                                                                               │
│                                                                                                                                                               │
│ Data page checksums are disabled.                                                                                                                             │
│                                                                                                                                                               │
│ fixing permissions on existing directory /var/lib/postgresql/data ... initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Op │
│ Stream closed EOF for ikanello1-dev/kubedock-967355e7b5b8 (main)
```

**Comment by n1hility** [comment]
Thanks for diving into this @iocanel!

> Most of the quick starts I tried failed.
> 
> From what I understand in most cases the issue has to do with file permissions. The root cause is the that images used created their own user (e.g. mysql, mariadb etc) and use that to setup directories while in Openshift containers run as random users causing all those permission issues.

+1 Many popular images are designed around running as root, and fall apart when passed a UID. Or they expected a fixed non-root UID, which is then overridden by kube/openshift to a random one. Another common failure case is a pre-created image path with files owned by root get squashed by the storage provider to a different UID than the one running the container. Once userns support lands in Kube/Openshift (coming soon), the situation should eventually improve since fixed UIDs are fine (get remapped to a different UID).

> There are specific guidelines on how to fix those images but I am not sure if we want to get down to that road.

  IMO it is worth it to work with upstream image providers to improve their images. Aside from using our own layers to workaround we might be able to patch kubedoclet to support (if it doesnt already) init container usage to fix up file related issues.

**Comment by iocanel** [comment]
What I find interesting is that some of the failing images, work if they are used with `oc new-app`. For examples the centos and rhel flavors of postgress fall into that category. I can even manually portforward and use them in the quickstarts, but still fail when used via `kubedock`. The only differnence between `kubedock` and `oc` I observe is that `oc` automatically adds an empty dir volume to the pod when its declared in the image. It might worth implementing something like this in `kubedock` to see if it makes any difference.

**Comment by joyrex2001** [comment]
This does not apply to all issues, but nevertheless might help getting more insight.

Since volume mounts are difficult to get correctly configured in ci, and may not even possible if testcontainers is using a remote host (eg testcontainers cloud), a lot of the modules are copying config instead of using volumes.

One of the gaps when simulating the docker api on kubernetes is that in docker, you can copy files to an unstarted container, while in kubernetes you can’t since there is no unstarted state. So kubedock will “always” start a container when files are being copied to it. (“always” because there is a —pre-archive flag which works around this, using configmaps).

This approach however, can lead to race exceptions (e.g. copying the config after the container proces requires it), or to permission issues. Usually this is overcome by implemeting a script that waits until the config is present in the container. However, this script might have a destination that is not writable for non-root users, like /.

The kafka devservice has its own implementation, and implements it in a pattern that can fit both worlds. See this pr as well: https://github.com/quarkusio/quarkus/pull/19736

This is another interesting pr, tackling a similar issue: https://github.com/testcontainers/testcontainers-java/pull/7524

**Comment by tqvarnst** [comment]
Another thing that worries me about using a shared cluster like this with testcontainers is that most (if not all) containers are hosted on DockerHub, and a shared cluster is likely to run into rate limits. We need to take this into consideration as well and see if we can find a workaround by caching images in the local OpenShift cluster.

**Comment by Blarc** [comment]
I am trying to run test containers in GitLab pipeline using GitLab Kubernetes Executor (as runner). I added kubedock as GitLab [service](https://docs.gitlab.com/ee/ci/services/).

This is my current devservices configuration:
```yaml
'%test':
  quarkus:
    devservices:
      enabled: true
      timeout: 300
    datasource:
      devservices:
        image-name: mariadb:10.11
    elasticsearch:
      devservices:
        image-name: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
# Works with opensearch distribution
#        distribution: opensearch
#        image-name: docker.io/opensearchproject/opensearch:2.9.0
    kafka:
      devservices:
        image-name: docker.io/vectorized/redpanda:v22.3.4
```

This works when using **opensearch** as the distribution of elasticsearch, but fails when I use default (elastic) distribution. The other two containers (kafka and mariadb) are started up correctly.

```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.elasticsearch.restclient.common.deployment.DevServicesElasticsearchProcessor#startElasticsearchDevService threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image docker.elastic.co/elasticsearch/elasticsearch:8.11.0
	at io.quarkus.elasticsearch.restclient.common.deployment.DevServicesElasticsearchProcessor.startElasticsearchDevService(DevServicesElasticsearchProcessor.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image docker.elastic.co/elasticsearch/elasticsearch:8.11.0
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:361)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:334)
	at io.quarkus.elasticsearch.restclient.common.deployment.DevServicesElasticsearchProcessor.lambda$startElasticsearch$1(DevServicesElasticsearchProcessor.java:229)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.quarkus.elasticsearch.restclient.common.deployment.DevServicesElasticsearchProcessor.startElasticsearch(DevServicesElasticsearchProcessor.java:243)
	at io.quarkus.elasticsearch.restclient.common.deployment.DevServicesElasticsearchProcessor.startElasticsearchDevService(DevServicesElasticsearchProcessor.java:97)
	... 11 more
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:346)
	... 16 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:565)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:356)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 17 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"command terminated with exit code 2"}
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CopyArchiveFromContainerCmdExec.execute(CopyArchiveFromContainerCmdExec.java:30)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CopyArchiveFromContainerCmdExec.execute(CopyArchiveFromContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.CopyArchiveFromContainerCmdImpl.exec(CopyArchiveFromContainerCmdImpl.java:66)
	at org.testcontainers.containers.ContainerState.copyFileFromContainer(ContainerState.java:378)
	at org.testcontainers.elasticsearch.ElasticsearchContainer.containerIsStarted(ElasticsearchContainer.java:136)
	at org.testcontainers.containers.GenericContainer.containerIsStarted(GenericContainer.java:724)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:544)
	... 19 more
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:639)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:723)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

The log from the elasticsearch pod does not contain any errors. When observing the whole process, it looks to me like the pod is killed before elasticsearch finishes initializing.

[elastic-no-error-log.txt](https://github.com/quarkusio/quarkus/files/13349231/elastic-no-error-log.txt)

**Comment by xstefank** [comment]
We did the superhero workshop in Dev Spaces yesterday, so I can confirm that with Quarkus 3.9.2

jdbc-postgresql works without any additional configuration
messaging-kafka works with Redpanda, and also we fixed kafka-native

**Comment by ahussey-redhat** [comment]
Hello,
I'm not sure if this issue is still active, but Keycloak doesn't appear to be working with kubedock
```bash
Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
2024-09-02 06:28:56,117 INFO [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 10602ms
Server configuration updated and persisted. Run the following command to review the configuration:
kc.sh show-config
Next time you run the server, just run:
kc.sh start --http-enabled=true --hostname-strict=false --spi-user-profile-declarative-user-profile-config-file=/opt/keycloak/upconfig.json --optimized
ERROR: Unexpected error when starting the server in (production) mode
ERROR: Failed to start quarkus
ERROR: Failed to reaad default user profile configuration: /opt/keycloak/upconfig.json
ERROR: /opt/keycloak/upconfig.json (No such file or directory)
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```
