### ISSUE TITLE
3.1.1 Final - java.lang.IllegalArgumentException: Class java.util.UUID[] is instantiated reflectively but was never registered

### ISSUE THREAD

**Issue by amoscatelli** [quarkusio/quarkus#34071]
### Describe the bug

Upgrading from 3.1.0 Final to 3.1.1 Final leads to this is native mode only

```
2023-06-15 18:20:45.00 UTCgreetings-68cc87fc5-dvgsf[pod-event]Successfully pulled image "registry.cloud.okteto.net/amoscatelli/greetings:1.0.4" in 242.613097ms (242.629307ms including waiting)
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings__ ____ __ _____ ___ __ ____ ______ 
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \ 
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings--\___\_\____/_/ |_/_/|_/_/|_|\____/___/ 
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings18:31:02 WARN traceId=, parentId=, spanId=, sampled= [io.qu.ru.co.ConfigRecorder] (main) Build time property cannot be changed at runtime:
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings - quarkus.http.root-path is set to '/greetings' but it is build time fixed to '/'. Did you change the property quarkus.http.root-path after building the application?
2023-06-15 18:31:02.71 UTCgreetings-68cc87fc5-dvgsfgreetings18:31:02 WARN traceId=, parentId=, spanId=, sampled= [io.qu.op.ru.ex.ot.LateBoundBatchSpanProcessor] (main) No BatchSpanProcessor delegate specified, no action taken.
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings18:31:04 ERROR traceId=, parentId=, spanId=, sampled= [io.qu.ru.Application] (main) Failed to start application (with profile [prod]): java.lang.IllegalArgumentException: Class java.util.UUID[] is instantiated reflectively but was never registered.Register the class by adding "unsafeAllocated" for the class in reflect-config.json.
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.snippets.SubstrateAllocationSnippets.arrayHubErrorStub(SubstrateAllocationSnippets.java:345)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.loader.ast.internal.EntityBatchLoaderArrayParam.prepare(EntityBatchLoaderArrayParam.java:176)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.persister.entity.AbstractEntityPersister.prepareLoader(AbstractEntityPersister.java:3425)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.persister.entity.AbstractEntityPersister.postInstantiate(AbstractEntityPersister.java:3419)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.finishInitialization(MappingMetamodelImpl.java:204)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.internal.SessionFactoryImpl.initializeMappingModel(SessionFactoryImpl.java:320)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:270)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:156)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
2023-06-15 18:31:04.25 UTCgreetings-68cc87fc5-dvgsfgreetings at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

### Quarkus version or git rev

3.1.1 Final

**Comment by gsmet** [comment]
Could you give a bit more details about where you are using UUID in your model and how?

**Comment by amoscatelli** [comment]
Here is the only class where I do use UUID ( anyway notice the error is talking about an array java.util.UUID[] ) : 

```
package com.infolabtech.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import java.util.Date;
import java.util.UUID;

@Entity
public class Greeting {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column
    private String username;
    
    @Column
    private Date creation;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getUser() {
        return username;
    }

    public void setUser(String user) {
        this.username = user;
    }

    public Date getCreation() {
        return creation;
    }

    public void setCreation(Date creation) {
        this.creation = creation;
    }

    @PrePersist
    protected void prePersist() {
        this.setCreation(
                new Date()
        );
    }

}
```

Thank you in advance

**Comment by yrodiere** [comment]
I believe this is a regression caused by https://hibernate.atlassian.net/browse/HHH-16466

I'm opened a discussion this with the ORM team in https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev/topic/HHH-16466

**Comment by yrodiere** [comment]
Created https://hibernate.atlassian.net/browse/HHH-16809 / https://hibernate.atlassian.net/browse/HHH-16808 in an attempt to fix this upstream.

**Comment by amoscatelli** [comment]
@yrodiere do you have any update ?
this kinda prevents any update to quarkus 3.2 so far ... for anybody using JPA/hibernate extension (I think?)

I took a look at the hibernate discussion and that's stuck at 20 June
Can I help ? What can we do to unblock the situation ?

**Comment by yrodiere** [comment]
> for anybody using JPA/hibernate extension (I think?)

Probably only people using UUID in specific circumstances. Still, it remains an important regression.

As to progress, last I heard @sebersole had a branch with some work in progress but wasn't totally happy with the API changes.

For you, a workaround would be registering `UUID[].class` (the array type) for reflection. Putting `@RegisterForReflection(targets = {UUID[].class})` on some entity class should work. See https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection

**Comment by amoscatelli** [comment]
Thank you I'll try this workaround for the moment

**Comment by humcqc** [comment]
> > for anybody using JPA/hibernate extension (I think?)
> 
> Probably only people using UUID in specific circumstances. Still, it remains an important regression.
> 
> As to progress, last I heard @sebersole had a branch with some work in progress but wasn't totally happy with the API changes.
> 
> For you, a workaround would be registering `UUID[].class` (the array type) for reflection. Putting `@RegisterForReflection(targets = {UUID[].class})` on some entity class should work. See https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection

The workaround worked for my case, thanks! Waiting for the final fix.
