### ISSUE TITLE
BlockingOperationNotAllowedException in GRPC when using authentication

### ISSUE THREAD

**Issue by ihepda** [quarkusio/quarkus#34146]
### Describe the bug

Dear all, 
I'm implementing a solution to use a jwt bearer with GRPC.
I've created a class JWTGrpcSecurityMechanism that extends GrpcSecurityMechanism
```
@ApplicationScoped
public class JWTGrpcSecurityMechanism implements GrpcSecurityMechanism {

	@Override
	public boolean handles(Metadata metadata) {
		return true;
	}

	@Override
	public AuthenticationRequest createAuthenticationRequest(Metadata metadata) {
		String jwt = metadata.get(io.grpc.Metadata.Key.of("authorization", Metadata.ASCII_STRING_MARSHALLER));
		jwt = jwt.substring("Bearer ".length());
		TokenAuthenticationRequest token = new TokenAuthenticationRequest(new JsonWebTokenCredential(jwt));
		return token;
	}

}
```
If I execute a client call with a right bearer I receive this error.
```
io.quarkus.runtime.BlockingOperationNotAllowedException: You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.checkBlocking(TransactionScopedSession.java:116)
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.find(TransactionScopedSession.java:173)
	at org.hibernate.engine.spi.SessionLazyDelegator.find(SessionLazyDelegator.java:784)
	at org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_ClientProxy.find(Unknown Source)
```

This seems to be due to the io.quarkus.grpc.auth.GrpcSecurityInterceptor where it execute the chain, when the authentication is OK, using the context thread (I/O thread):

```
        for (GrpcSecurityMechanism securityMechanism : securityMechanisms) {
            if (securityMechanism.handles(metadata)) {
                try {
                    AuthenticationRequest authenticationRequest = securityMechanism.createAuthenticationRequest(metadata);
                    Context context = Vertx.currentContext();
                    boolean onEventLoopThread = Context.isOnEventLoopThread();
                    if (authenticationRequest != null) {
                        Uni<SecurityIdentity> auth = identityProviderManager
                                .authenticate(authenticationRequest)
                                .emitOn(new Executor() {
                                    @Override
                                    public void execute(Runnable command) {
                                        if (onEventLoopThread) {
                                            context.runOnContext(new Handler<>() {
                                                @Override
                                                public void handle(Void event) {
                                                    command.run();
                                                }
                                            });
                                        } else {
                                            command.run();
                                        }
                                    }
                                });
````

This code dones not take in consideration the @Blocking annotation in the grpc implementation

```
@Authenticated
@Blocking
@GrpcService
public class SurveyServiceImpl implements SurveyService{

	@Inject
	private be.digitech.common.survey.service.SurveyService surveyService;


	@Override
	public Uni<SurveyValidationResult> validate(SurveyResponses request) {
		return Uni.createFrom().item(()-> {
			try {
				this.surveyService.validate(request.getSurveyName(), request.getSurveyId(), request.getResponsesMap());
				return SurveyValidationResult.newBuilder().setResultCode(SurveyValidationResultCode.OK).build();
			}catch (ValidationException e) {
				return SurveyMapper.toSurveyValidationResult(e);
			}
		});
	}

```

and the system goes in error.

If I remove the @Authenticated annotation, all work fine.

Sorry if I am not very clear.
I'm at disposal for every explaination

### Expected behavior

The system must execute the GRPC service implementation in an worker thread if I use the @Blocking annotation.

### Actual behavior

The system uses the I/O thread used during the authentication process also if I set the @Blocking annotation in the implementation class.
```
                   AuthenticationRequest authenticationRequest = securityMechanism.createAuthenticationRequest(metadata);
                    Context context = Vertx.currentContext();
                    boolean onEventLoopThread = Context.isOnEventLoopThread(); // this returns true and the thread is a I/O thread
...
                                .authenticate(authenticationRequest)
                                .emitOn(new Executor() {
                                    @Override
                                    public void execute(Runnable command) {
                                        if (onEventLoopThread) { // enters in this if
                                            context.runOnContext(new Handler<>() { //executes in the context thread
                                                @Override
                                                public void handle(Void event) {
                                                    command.run();
                                                }
                                            });
                                        } else {
                                            command.run();
                                        }
                                    }
                                });

```

### How to Reproduce?

Pre-requirements:

- a quarkus project with GRPC and postgres features
- a proto with a RPC service 
- The RPC implementation must execute a findById in panache
- You have to implement a GrpcSecurityMechanism that returns an AuthenticationRequest
```
@ApplicationScoped
public class JWTGrpcSecurityMechanism implements GrpcSecurityMechanism {

	@Override
	public boolean handles(Metadata metadata) {
		return true;
	}

	@Override
	public AuthenticationRequest createAuthenticationRequest(Metadata metadata) {
		String jwt = metadata.get(io.grpc.Metadata.Key.of("authorization", Metadata.ASCII_STRING_MARSHALLER));
		jwt = jwt.substring("Bearer ".length());
		TokenAuthenticationRequest token = new TokenAuthenticationRequest(new JsonWebTokenCredential(jwt));
		return token;
	}

}
```

- you have to call the grpc request with a right bearer jwt token 

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

java version "17.0.5" 2022-10-18 LTS

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

**Comment by sberyozkin** [comment]
@ihepda This issue is probably a duplicate of or at least related to #34085

**Comment by ihepda** [comment]
> @ihepda This issue is probably a duplicate of or at least related to #34085

Hello @sberyozkin ,
may be or may be not, I'm not sure. The synthom is different, in my case the GRPC response doesn't hang but return an error (status code 2) due the exception I mentioned.
I don't know how the keycloak authorization mechanism has been implemented and I'm not sure that the flow is the same.
I'll get back to you with a sample project that reproduces the issue, it is simplier that the keycloak configuration.

Maybe I'm using the wrong API.

**Comment by ihepda** [comment]
Simple project to reproduce the issue.
https://github.com/ihepda/grpc-authorization-test
It's important tu use a jwt token valid, so I put a Readme.md in the postman folder to explain how to use postman.

If you need other info please, I'm at your disposal

BR
Claudio

**Comment by sberyozkin** [comment]
Thanks @ihepda. @alesj FYI, have a look at the reproducer please when you get a chance. I'm not sure right now how I can help, but ping me please and I can answer questions if any related to the Quarkus security part,  see also #34085

**Comment by ihepda** [comment]
FYI, as workaround tou can use 
`
vertx.executeBlocking(Uni.createFrom().item(()-> {
// code....
		}));
`

**Comment by sberyozkin** [comment]
Thanks, can it be a required solution though ? @cescoffier @alesj what do you think ?
