### ISSUE TITLE
Dev service fails with permission error during startup

### ISSUE THREAD

**Issue by chiroito** [quarkusio/quarkus#34154]
### Describe the bug

I tried to run the Infinispan Dev service on DevSpaces 3.6, but it failed to start the Dev service.

```
2023-06-20 07:42:55,673 ERROR [tc.qua.io/.4.0] (build-43) Could not start container: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"cause":"permission denied","message":"error unmounting storage for container 1ab08088b18badd70b8adfcd94a38946d838ec78c474553eb8c2a2b45f13b1fc after network create failure: error unmounting container 1ab08088b18badd70b8adfcd94a38946d838ec78c474553eb8c2a2b45f13b1fc SHM mount /home/user/.local/share/containers/storage/vfs-containers/1ab08088b18badd70b8adfcd94a38946d838ec78c474553eb8c2a2b45f13b1fc/userdata/shm: permission denied","response":500}

        at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
        at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
        at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:78)
        at org.testcontainers.utility.RyukResourceReaper.register(RyukResourceReaper.java:68)
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:423)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
        at io.quarkus.infinispan.client.deployment.devservices.InfinispanDevServiceProcessor.lambda$startContainer$2(InfinispanDevServiceProcessor.java:213)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at io.quarkus.infinispan.client.deployment.devservices.InfinispanDevServiceProcessor.startContainer(InfinispanDevServiceProcessor.java:223)
        at io.quarkus.infinispan.client.deployment.devservices.InfinispanDevServiceProcessor.runInfinispanDevService(InfinispanDevServiceProcessor.java:165)
        at io.quarkus.infinispan.client.deployment.devservices.InfinispanDevServiceProcessor.startInfinispanContainers(InfinispanDevServiceProcessor.java:117)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

Dev service starts and Quarkus connects to it

### Actual behavior

Dev service fails with permission error during startup

### How to Reproduce?

1. Access to https://developers.redhat.com/developer-sandbox/ide
2. Click "Start your sandbox for free"
3. Open terminal on Dev Spaces.
4. `git clone https://github.com/quarkusio/quarkus-quickstarts.git` on the terminal.
5. `cd infinispan-client-quickstart`
6. Do following commands

```
systemctl --user enable podman.socket --now
podman system service --time=0 &
export DOCKER_HOST=unix://`podman info | yq -r .host.remoteSocket.path`
mvn quarkus:dev
```

### Output of `uname -a` or `ver`

Linux workspacec9d41de567e748c2-57d996b74b-l4gz5 5.14.0-284.13.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 27 13:35:10 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.19" 2023-04-18 LTS OpenJDK Runtime Environment (Red_Hat-11.0.19.0.7-1.el8_7) (build 11.0.19+7-LTS) OpenJDK 64-Bit Server VM (Red_Hat-11.0.19.0.7-1.el8_7) (build 11.0.19+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /home/user/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 11.0.19, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.19.0.7-1.el8_7.x86_64 Default locale: en, platform encoding: UTF-8 OS name: "linux", version: "5.14.0-284.13.1.el9_2.x86_64", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
@maxandersen do you have any idea who could help on this `DevSpaces` related issue?

**Comment by gsmet** [comment]
I'm going to close this because it doesn't look related to Quarkus itself.
