### ISSUE TITLE
Quarkus CLI deploy kubernetes -> KubernetesClientException: namespace not specified

### ISSUE THREAD

**Issue by cmoulliard** [quarkusio/quarkus#34199]
### Describe the bug

When we issue the following quarkus CLI command:
```
quarkus deploy kubernetes
```
then we got the following error:
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.1.2.Final:deploy (default-cli) on project hello:
Failed to build quarkus application: io.quarkus.builder.BuildException: 
Build failure: Build failed due to errors
[ERROR] 	[error]: 
Build step io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy threw an exception:
io.fabric8.kubernetes.client.KubernetesClientException: namespace not specified for an operation requiring one and no default was found in the Config.
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.checkNamespace(OperationSupport.java:269)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleCreate(OperationSupport.java:341)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:707)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:93)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:42)
[ERROR] 	at io.fabric8.kubernetes.client.utils.internal.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:51)
```

### Expected behavior

According to the CLI documentation, the namespace is optional and should not be mandatory
```
quarkus deploy kubernetes -h

Perform the deploy action on kubernetes.

Usage: quarkus deploy kubernetes [-Beh] [--[no-]clean] [--dry-run]
...
Kubernetes options:
...
      --namespace=<namespace>
                        The Kubernetes namespace
                          Default: Optional.empty
```

### How to Reproduce?

```
quarkus create app hello -x=kubernetes,resteasy-reactive; cd hello
quarkus deploy kubernetes
```

### Output of `uname -a` or `ver`

Darwin MacBook-Pro 21.6.0

### Output of `java -version`

openjdk version "17" 2021-09-14

### Quarkus version or git rev

3.1.2.Final

**Comment by gsmet** [comment]
@cmoulliard is it still an issue with 3.15.1?

**Comment by cmoulliard** [comment]
Problem is fixed. I will close it

```
quarkus create app hello -x=kubernetes,resteasy; cd hello
  quarkus deploy kubernetes
-----------
selected extensions:
- io.quarkus:quarkus-kubernetes
- io.quarkus:quarkus-resteasy


applying codestarts...
📚 java
🔨 maven
📦 quarkus
📝 config-properties
🔧 tooling-dockerfiles
🔧 tooling-maven-wrapper
🚀 resteasy-codestart

-----------
[SUCCESS] ✅  quarkus project has been successfully generated in:
--> /Users/cmoullia/temp/hello
-----------
Navigate into this directory and get started: quarkus dev
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< org.acme:hello >---------------------------
[INFO] Building hello 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- resources:3.3.1:resources (default-cli) @ hello ---
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.705 s
[INFO] Finished at: 2024-10-02T18:51:13+02:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< org.acme:hello >---------------------------
[INFO] Building hello 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus:3.15.1:deploy (default-cli) @ hello ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 391ms
[INFO] [io.quarkus.kubernetes.deployment.PropertyUtil] Kubernetes manifests are generated with 'The container port http' having default value '8080'. The app and manifests will get out of sync if the property 'quarkus.http.port' is changed at runtime.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Deploying to kubernetes server: https://127.0.0.1:61561/ in namespace: default.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: Service hello.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: Deployment hello.
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1539ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.604 s
[INFO] Finished at: 2024-10-02T18:51:17+02:00
[INFO] ------------------------------------------------------------------------

~/temp/hello
❯ k get po -A
NAMESPACE                    NAME                                                READY   STATUS         RESTARTS         AGE
...
default                      hello-54946b7f65-sh878                              0/1     ErrImagePull   0                11s

~/temp/hello
❯ k get deployment/hello -n default
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
hello   0/1     1            0           35s
```
