### ISSUE TITLE
Locally built GraalVM (with local built JDK) fails to build Quarkus Native with NPE

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#34191]
### Describe the bug

Building Quarkus with a locally built GraalVM, which uses a locally built JDK fails with an NPE:

```[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /Users/g/1/mendrugo/quarkus-quick-crud/hibernate-orm-quickstart/target/hibernate-orm-quickstart-1.0.0-SNAPSHOT-native-image-source-jar/hibernate-orm-quickstart-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /Users/g/1/mendrugo/quarkus-quick-crud/hibernate-orm-quickstart/target/hibernate-orm-quickstart-1.0.0-SNAPSHOT-native-image-source-jar/hibernate-orm-quickstart-1.0.0-SNAPSHOT-runner.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.726 s
[INFO] Finished at: 2023-06-21T09:27:03+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.1.2.Final:build (default) on project hibernate-orm-quickstart: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to get GraalVM version
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildRunner.getGraalVMVersion(NativeImageBuildRunner.java:40)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:218)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.NullPointerException
[ERROR] 	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
[ERROR] 	at org.graalvm.home.Version.parse(Version.java:260)
[ERROR] 	at io.quarkus.deployment.pkg.steps.GraalVM$Version.<init>(GraalVM.java:156)
[ERROR] 	at io.quarkus.deployment.pkg.steps.GraalVM$VersionParseHelper.parse(GraalVM.java:72)
[ERROR] 	at io.quarkus.deployment.pkg.steps.GraalVM$Version.of(GraalVM.java:207)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildRunner.getGraalVMVersion(NativeImageBuildRunner.java:37)
[ERROR] 	... 12 more
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
make: *** [../make/common/QuarkusProd.gmk:2: hibernate-orm-quickstart/target/hibernate-orm-quickstart-1.0.0-SNAPSHOT-runner] Error 1
```

The `native-image` version prints:

```
❯ ~/opt/graalvm-17/bin/native-image --version
native-image 17.0.9-internal 2023-10-17
OpenJDK Runtime Environment GraalVM CE 17.0.9-dev.internal+0.1 (build 17.0.9-internal+0-adhoc.g.jdk17u-dev)
OpenJDK 64-Bit Server VM GraalVM CE 17.0.9-dev.internal+0.1 (build 17.0.9-internal+0-adhoc.g.jdk17u-dev, mixed mode, sharing)
```

**Comment by gsmet** [comment]
This resonates a lot with: https://github.com/quarkusio/quarkus/issues/34161 .

**Comment by maxandersen** [comment]
Local build jdks has no sensible version info where tools expects such version info. 

They are a pain to deal with

**Comment by jerboaa** [comment]
@galderz The `native-image` version printout has no way of knowing which GraalVM version this is. But I agree it shouldn't throw a NPE. Then again it would just fall back to UNKNOWN. That's the best it could do. The version output you've provided only has OpenJDK version info.

Just for reference, what does `grep GRAALVM_VERSION $GRAALVM_HOME/release` print? Would that be saner (just curious).

**Comment by gsmet** [comment]
If we are able to detect it's a development version, we could default to the latest version we support.

**Comment by jerboaa** [comment]
`-internal` is a hint, but why would it default to latest? I could produce such a build for any graalvm version. Maybe it's time to give the user the option to override it? -Dquarkus.native.graalvm-version=`XX`?

**Comment by gsmet** [comment]
Sure but there's a good chance you're trying to work on a recent tree. So while having the ability to override it could be useful, I would still default to the latest.

**Comment by galderz** [comment]
I've been able to workaround this by building the JDK with `--with-version-opt=jvmci-24.0-b1` or `--with-version-opt=jvmci-23.1-b1`. The former has module issues because it considers `24.0` as unknown version (see [here](https://gist.github.com/galderz/515babd567b2d45bac3d3e26dcc5326c)). Using `23.1` fails some JVMCI version checks (I think it's a labsjdk and so can do those checks), but those can be ignored (see [here](https://gist.github.com/galderz/802d89276a297be5c6c1377f1b8d9962)).

I think we should support `jvmci` and `internal` inside the build information to deal with both labsjdk and locally built JDKs. That should be enough for now to have. I'll prepare a PR for it.

**Comment by galderz** [comment]
Actually, no need for Quarkus changes here. Adding `-dev` at the end of the version removes the JVMCI check altogether. E.g. `--with-version-opt=jvmci-23.1-dev`.

**Comment by galderz** [comment]
With the above parameters, `native-image --version` prints:

```
/Users/g/1/mandrel-mandrel/sdk/latest_graalvm_home/bin/native-image --version
native-image 21.0.1-internal 2023-10-17
OpenJDK Runtime Environment GraalVM CE 21.0.1-dev.internal.1 (build 21.0.1-internal-jvmci-23.1-dev)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.1-dev.internal.1 (build 21.0.1-internal-jvmci-23.1-dev, mixed mode, sharing)
```

And that is enough for the current Quarkus version detecting logic (see [here](https://gist.github.com/galderz/f78d205291f2329483dd2d2f7d39b459), the illegal access errors are due to recent changes in master).

I'm closing this for now.
