### ISSUE TITLE
Quarkus 3.1.2 Hibernate Reactive Panache requires a safe (isolated) Vert.x sub-context

### ISSUE THREAD

**Issue by hamed-hatami** [quarkusio/quarkus#34291]
### Describe the bug

I've written a Kafka consumer in which I have to persist data into Postgres (Reactive Hibernate Panache) but when it read data from Kafka topic and it's time to write it to Postgres, there's an issue

@ApplicationScoped
public class EventConsumer {
    @Inject
    CreditCardRepository creditCardRepository;

    @Incoming("event-out")
    @Acknowledgment(Acknowledgment.Strategy.POST_PROCESSING)
    public Uni<Void> consumeEvent(final CreditCardDto creditCardDto) {
        Uni<Void> result = creditCardRepository.addCreditCard(creditCardDto);
        return result;
    }

}

### Expected behavior

The expectation would be it  to safely keep working after getting data from topic by using @WithTransaction on repository layer 

    @WithTransaction
    public Uni<Void> addCreditCard(final CreditCardDto creditCardDto) {

        var creditCardEntity = new CreditCardEntity();
        creditCardEntity.availableCredit = creditCardDto.getAvailableCredit();
        creditCardEntity.cardNumber = creditCardDto.getCardNumber();
        creditCardEntity.ownerName = creditCardDto.getOwnerName();
        creditCardEntity.expirationMonth = creditCardDto.getExpirationMonth();
        creditCardEntity.expirationYear = creditCardDto.getExpirationYear();
        creditCardEntity.securityCode = creditCardDto.getSecurityCode();

        return creditCardEntity
                .persistAndFlush()
                .replaceWith(Uni
                        .createFrom()
                        .voidItem())
                .onFailure()
                .transform(t -> new IllegalStateException("Error"));

    }

### Actual behavior

it throws some an exception at the level of calling database operation

 Suppressed: java.lang.IllegalStateException: Hibernate Reactive Panache requires a safe (isolated) Vert.x sub-context, but the current context hasn't been flagged as such.
                at io.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle.checkIsSafe(VertxContextSafetyToggle.java:89)
                at io.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle.validateContextIfExists(VertxContextSafetyToggle.java:72)
                at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.vertxContext(SessionOperations.java:183)
                at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.withSession(SessionOperations.java:112)
                at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.withTransaction(SessionOperations.java:86)
                at io.quarkus.hibernate.reactive.panache.common.runtime.WithTransactionInterceptor.intercept(WithTransactionInterceptor.java:20)
                at io.quarkus.hibernate.reactive.panache.common.runtime.WithTransactionInterceptor_Bean.intercept(Unknown Source)
                at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
                at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
                at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
                at com.postnord.kafkaManager.EventConsumer_Subclass.consumeEvent(Unknown Source)
                at com.postnord.kafkaManager.EventConsumer_ClientProxy.consumeEvent(Unknown Source)
                at com.postnord.kafkaManager.EventConsumer_SmallRyeMessagingInvoker_consumeEvent_97dd6007b4cbfe809de9511b738c6531d7aa7015.invoke(Unknown Source)
                at io.smallrye.reactive.messaging.providers.AbstractMediator.invoke(AbstractMediator.java:104)
                at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeOnMessageContext$1(AbstractMediator.java:112)
                at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$0(LocalContextMetadata.java:34)
                at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$1(LocalContextMetadata.java:53)
                at io.smallrye.reactive.messaging.providers.helpers.VertxContext.lambda$runOnContext$0(VertxContext.java:26)
                at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
                at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
                at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
                at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:833)

### How to Reproduce?

As reproducer, I can refer you to the genuine gitlab repo of that project as below :

https://gitlab.com/hamedhatami/quarkus-demo

**Comment by mkouba** [comment]
CC @cescoffier @ozangunalp

**Comment by cescoffier** [comment]
Looking at the reproducer, you found the solution.

Reactive messaging cannot mark the context safe, as ... it depends what you do with it. Thus, we require the user to do it.
That being said, I like how you did it with the stereotype. 

I'm going to document that and propose something very similar.

**Comment by cescoffier** [comment]
I've opened a PR with the interceptor: https://github.com/quarkusio/quarkus/pull/34636

**Comment by ozangunalp** [comment]
@cescoffier hold on that PR because I am pretty sure we have an interceptor that sets the context safe if we are on a duplicated context. @hamed-hatami thanks for the reproducer, I'll debug it and get back.

**Comment by cescoffier** [comment]
@ozangunalp this ins not only for RM, but for almost everything else.... like virtual threads :-D

**Comment by cescoffier** [comment]
But, yes, in the case of RM, I'm surprised, as I was pretty sure we were doing this. 

Note that we should not mark the context as safe on method annotated with @Blocking and ordered = false.

**Comment by cescoffier** [comment]
@ozangunalp we do have: io.quarkus.smallrye.reactivemessaging.runtime.DuplicatedContextConnectorFactoryInterceptor.

**Comment by ozangunalp** [comment]
Ok, the problem is the application configures both `event-in` and `event-out` channels like you are supposed to, but on the incoming channel it uses `event-out`, which links the outgoing emitter to that channel internally. Therefore the message never goes to Kafka but is emitted internally. 

It is still emitted on a duplicated context, however, we do not set it as safe. We only do set it when it is a connector channel like `event-in`.

**Comment by mklueh** [comment]
I'm running into this issue when I try to call a `@WithTransaction` annotated method from a Smallrye Messaging receiver

```
    @Incoming(value = SEND_MAIL)
    public Uni<Void> sendMail(Mail mail) {
        return send(mail);
    }

    @WithTransaction
    public Uni<Void> send(Mail mail){

    }
```

Instead I have to do this and use Panache.withTransaction:

```
       @Incoming(value = SEND_MAIL)
       public Uni<Mail> sendMail(Mail mail) {
           return send(mail);
       }

        protected Uni<Mail> send(Mail mail) {

        if (ProfileManager.getActiveProfile().equals("dev")) {
            log.info(mail.toString());
        }

        return mailer.send(...)
                .onFailure().invoke(throwable -> {
                    log.error("Failed to send Email", throwable);
                    mail.setState(MailState.FAILED);
                })

                .onItem().invoke(unused -> mail.setState(MailState.SENT))

                .onItemOrFailure()
                .transformToUni((unused, throwable) -> Panache.withTransaction(mail::persist)
                        .onItem().transformToUni(p -> Uni.createFrom().item(mail)));
    }

```


Could anyone explain if and why this is normal?

**Comment by cescoffier** [comment]
Adding `@SafeVertxContext`  on the method consuming the event will mark the duplicated context as safe. Quarkus cannot do that, as we can't be sure the context will be use safely (not concurrently) in the method.
