### ISSUE TITLE
Hibernate ORM tries to connect on start up when  quarkus.datasource.jdbc.initial-size is 0

### ISSUE THREAD

**Issue by DavideD** [quarkusio/quarkus#34309]
### Describe the bug

Hibernate ORM should not connect at start up when `quarkus.datasource.jdbc.initial-size=0` (it should be the default value).

It's possible to see this using the Hibernate ORM quickstart:
1. change the `application.properties` to:
    ```
    quarkus.datasource.db-kind=postgresql
    quarkus.datasource.username=quarkus_test
    quarkus.datasource.password=quarkus_test
    quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus_test
    quarkus.datasource.jdbc.max-size=8
    quarkus.hibernate-orm.database.generation=none
    quarkus.datasource.jdbc.initial-size=0

    quarkus.hibernate-orm.log.sql=true
    ```
2. `mvn quarkus:dev`

The goal is to see the application start without errors when the database is not present and there's no need of schema creation, update, or validation.

**Comment by yrodiere** [comment]
I ran your reproducer and got two separate errors.

First is this:

```
2023-06-26 15:24:32,578 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
        at org.postgresql.Driver.makeConnection(Driver.java:443)
        at org.postgresql.Driver.connect(Driver.java:297)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
        at org.postgresql.core.PGStream.<init>(PGStream.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
        ... 12 more


2023-06-26 15:24:33,541 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

```

... but then it's Agroal trying to connect, not ORM.

Second is this:

```
2023-06-26 15:24:33,544 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (Hibernate post-boot validation thread for <default>) Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
2023-06-26 15:24:33,547 ERROR [io.qua.hib.orm.run.sch.SchemaManagementIntegrator] (Hibernate post-boot validation thread for <default>) Failed to run post-boot validation: org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution [Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.] [n/a]
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:98)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
        at org.hibernate.resource.transaction.backend.jta.internal.DdlTransactionIsolatorJtaImpl.getIsolatedConnection(DdlTransactionIsolatorJtaImpl.java:77)
        at org.hibernate.resource.transaction.backend.jta.internal.DdlTransactionIsolatorJtaImpl.getIsolatedConnection(DdlTransactionIsolatorJtaImpl.java:67)
        at org.hibernate.tool.schema.internal.exec.ImprovedExtractionContextImpl.getJdbcConnection(ImprovedExtractionContextImpl.java:63)
        at org.hibernate.tool.schema.extract.spi.ExtractionContext.getQueryResults(ExtractionContext.java:43)
        at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.extractMetadata(SequenceInformationExtractorLegacyImpl.java:39)
        at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.initializeSequences(DatabaseInformationImpl.java:66)
        at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.<init>(DatabaseInformationImpl.java:60)
        at org.hibernate.tool.schema.internal.Helper.buildDatabaseInformation(Helper.java:187)
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:67)
        at io.quarkus.hibernate.orm.runtime.schema.SchemaManagementIntegrator.runPostBootValidation(SchemaManagementIntegrator.java:140)
        at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$6.run(HibernateOrmRecorder.java:166)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
        at org.postgresql.Driver.makeConnection(Driver.java:443)
        at org.postgresql.Driver.connect(Driver.java:297)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        ... 1 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
        at org.postgresql.core.PGStream.<init>(PGStream.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
        ... 12 more
```

... and here it's a feature specific to dev mode, supposed to validate the schema in all cases. I dare say it makes sense in dev mode since I wouldn't expect the database to be down in that case. It won't run in production environments. It can be disabled through [`quarkus.hibernate-orm.validate-in-dev-mode=false`](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.validate-in-dev-mode).

So... are we talking about the first issue only, @DavideD? Or are you also challenging the idea that `validate-in-dev-mode` defaults to `true`?

**Comment by DavideD** [comment]
My expectation is that I can start quarkus-quickstart without having a database, if I set the following properties when I use the hibernate orm extension (and testcontainers is not involved):
```
quarkus.hibernate-orm.database.generation=none
quarkus.datasource.jdbc.initial-size=0
```
I've tried this in `dev` and `prod` mode, and it fails in both scenarios (did I do something wrong?).
Why does Quarkus need to connect to the database if there's no need to generate the schema?

> Or are you also challenging the idea that validate-in-dev-mode defaults to true?

I didn't know this property existed. 
I don't understand what's the benefit of it when you can set the same thing (I think) with:
```
%dev.quarkus.hibernate-orm.database.generation=validate
```

Also, what happens if we have both:
```
quarkus.hibernate-orm.validate-in-dev-mode=false
%dev.quarkus.hibernate-orm.database.generation=validate
```

In general, I would expect the default in Quarkus to be the same as the one the extension uses without Quarkus,
when Quarkus is not creating the test environment (`none` for Hibernate ORM).

In this particular case, because we are not asking Quarkus to start a default database with testcontainer, I would have
expected those two properties to be already set to `none` and `0`.

I'm not sure  what I would expect when asking Quarkus to create the test environment. I suppose I wouldn't care too much about those details in that situation.

It seems it's starting to become harder and harder to keep track of all the possible defaults.
But, maybe it's because I don't use Quarkus on a regular basis.
Anyway, I think this is not a problem of setting defaults, and not relevant for this issue.

**Comment by DavideD** [comment]
On second thought, these are probably two separate issues;
1. Agroal is trying to connect even if it's not necessary
2. Hibernate ORM is checking the database even if `quarkus.hibernate-orm.database.generation=none`

Anyway, maybe this is the expected behaviour and I'm just not familiar enough with it.
Feel free to close the issue in that case. It's still helpful to have a record of it.

**Comment by yrodiere** [comment]
> My expectation is that I can start the hibernate-orm-quickstart without having a database, if I set the following properties (and testcontainers is not involved):
> 
> ```
> quarkus.hibernate-orm.database.generation=none
> quarkus.datasource.jdbc.initial-size=0
> ```
> 
> I've tried this in `dev` and `prod` mode, and it fails in both scenarios (did I do something wrong?). Why does Quarkus need to connect to the database if there's no need to generate the schema?

I'd rather ask: why does Agroal open a connection on startup even though `initial-size` is set to `0`. Which is even worse, since it's not just doing something unnecessary, it's actively going against your instructions.

#27999 seems somewhat related in the sense that there too, Agroal doesn't seem to comply with its configuration. Maybe there's a common cause, maybe not. One would have to debug Agroal.

---

> I don't understand what's the benefit of it when you can set the same thing (I think) with:
> 
> ```
> %dev.quarkus.hibernate-orm.database.generation=validate
> ```

I think `validate-in-dev-mode` also provides suggestions to fix the schema. That is, when you actually have a database.

As to why it's been implemented that way... we'd have to ask Stuart I guess, but he's quite busy these days.

> Also, what happens if we have both:

You'll probably validate the schema twice. I doubt that's a problem in practice though.

> On second thought, these are probably two separate issues (like you mentioned):

Agreed. Let's focus on the Agroal one here as it looks like the more pressing issue IMO. Feel free to open another issue if you want to change how `validate-in-dev-mode` works.

**Comment by DavideD** [comment]
> FWIW I tried adding quarkus.hibernate-orm.validate-in-dev-mode=false to the quickstart and we still get that error about Agroal trying to open a connection on startup.

Yes, it matches with my experiments.

> Anyway... it seems great minds think alike: I actually opened https://github.com/quarkusio/quarkus/issues/30002 some time ago because I had the exact same problem as you.

:) Nice.

> Closing as duplicate of https://github.com/quarkusio/quarkus/issues/30002, feel free to answer here if you disagree, otherwise let's continue the discussion there.

Not much to disagree here. It seems we already keep track of everything one way or another.


Thanks for looking into this.
