### ISSUE TITLE
Hibernate Reactive: Empty error message when connection is refused at start up

### ISSUE THREAD

**Issue by DavideD** [quarkusio/quarkus#34301]
### Description

An Hibernate Reactive application in production mode (`prod`) send the following response when the database is not present:
```
HTTP/1.1 500 Internal Server Error
content-length: 72
content-type: application/json; charset=utf-8

{
    "details": "Error id 3cc60e1f-e83e-4805-b517-4cf900c22c2b-1",
    "stack": ""
}
```

We should improve the error message and send back something less cryptic.

It's possible to test this using the `hibernate-reactive-quickstart`:
1. Set `quarkus.hibernate-orm.database.generation` to `none`
2. Set `quarkus.hibernate-orm.database.start-offline=true`
3. `mvn clean verify -DskipTests && java -jar target/quarkus-app/quarkus-run.jar`
4. With [HttPie](https://httpie.io/): `http localhost:8080/fruits` 
This follows [a question on StackOverflow](https://stackoverflow.com/questions/76548046/how-to-establish-database-connection-on-startup-using-panache-reactive/76554701#76554701)

**Comment by geoand** [comment]
Is this something that will need a fix in Hibernate Reactive itself or in Quarkus?

**Comment by yrodiere** [comment]
> Is this something that will need a fix in Hibernate Reactive itself or in Quarkus?

Bump @DavideD :)

**Comment by DavideD** [comment]
No idea if it's Quarkus or Hibernate Reactive

**Comment by DavideD** [comment]
This is an old issue, it's also possible that the error has been solved already with some upgrades. I will test it again and update the issue as soon as I have some time

**Comment by DavideD** [comment]
It seems that Quarkus hides internal errors (maybe others, but I haven't checked) when responding to the client. As a default,  I think it's a sensible security precaution. I don't know why nothing gets logged server side though.

In this particular scenario, when enabling offline start up, if the database is not reachable, Quarkus won't show any error server side: not at start up (because it doesn't check), and not when answering the client request.

Client side the response is going to be:
```
➜  hibernate-reactive-quickstart git:(34301) ✗ http localhost:8080/fruits    
HTTP/1.1 500 Internal Server Error
content-length: 72
content-type: application/json; charset=utf-8

{
    "details": "Error id 580ce7da-2f30-4051-b2b7-60a7ee07887c-1",
    "stack": ""
}
```
This can make it harder to figure out what's happening, especially if one expect Quarkus to start the database.

But, a user can remap exceptions and show something different.
For example, adding this to the `FruitMutinyResource` class:
```java
    @ServerExceptionMapper
    public RestResponse<String> mapException(Throwable x) {
        x.printStackTrace(); // don't print the stacktrace like this, this is just an example.

        // Just a random status error for testing
        return RestResponse.status( Response.Status.HTTP_VERSION_NOT_SUPPORTED, "A very meaningful message" );
    }
```
(**WARNING:** this is just a quick test, I'm **NOT** suggesting to catch every exception in production.)

It will show the response:
```java
➜  hibernate-reactive-quickstart git:(34301) ✗ http localhost:8080/fruits
HTTP/1.1 505 HTTP Version Not Supported
Content-Type: application/json;charset=UTF-8
content-length: 25

A very meaningful message
```

and server side:
```
2025-12-10 15:34:59,343 INFO  [io.quarkus] (main) Installed features: [cdi, hibernate-orm, hibernate-reactive, reactive-pg-client, rest, rest-jackson, smallrye-context-propagation, vertx]
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:784)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:732)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by DavideD** [comment]
I'm prone to say that we can close this issue... but maybe we can change something in the default exception mapper (whichever it is in this case).

**Comment by yrodiere** [comment]
> It seems that Quarkus hides internal errors (maybe others, but I haven't checked) when responding to the client. As a default, I think it's a sensible security precaution.

+1 it's expected.

> I don't know why nothing gets logged server side though.

_That_ is unexpected.

We had a similar issue a long time ago for validation errors, but it should be fixed by https://github.com/quarkusio/quarkus/pull/20141 and anyway, it's unlikely that you're having the same problem here.

Perhaps Netty exceptions like `io.netty.channel.AbstractChannel$AnnotatedConnectException` are handled specially because the HTTP server runs on Netty, but that doesn't work well here because the Netty exception actually comes from the DB client... ?

You'd have to find out which exception mapper is handling the exception in your specific case to find out what's going on...

**Comment by geoand** [comment]
It appears that in Quarkus REST, `"io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432"` is not logged because `io.netty.channel.AbstractChannel$AnnotatedConnectException` is an `IOException`, and we log those in `debug`, because they are quite common (client's going away for example before the connection is done)

**Comment by DavideD** [comment]
Maybe I can change the hibernate-reactive quickstarts log configuration so that it appears in the log and call it a day.

**Comment by geoand** [comment]
Sure yeah, let's do that

**Comment by yrodiere** [comment]
That... doesn't solve the problem for anyone?

Ideally Quarkus REST would distinguish between connection errors thrown by the method itself, and those thrown by the http layer, but I understand this can be complex, especially with reactive code.
Maybe we can have Hibernate Reactive wrap such exceptions with a `HibernateException`? I'd expect Hibernate ORM does that with IOExceptions thrown by the JDBC drivers, so that would be consistent...

**Comment by DavideD** [comment]
Ok, that sounds reasonable. I will have a look

**Comment by geoand** [comment]
> That... doesn't solve the problem for anyone?

It doesn't, but it doesn't seem to be something people are bumping into much... Nonetheless, if you want to tackle, that's great

**Comment by DavideD** [comment]
I created https://github.com/hibernate/hibernate-reactive/issues/3020
I will try to fix it this week.

**Comment by DavideD** [comment]
Re-opened because it has not been released yet, and Quarkus needs to upgrade Hibernate Reactive to close this issue

**Comment by DavideD** [comment]
This issue should have been fixed by the upgrade to Hibernate Reactive 3.4.1.Final: https://github.com/quarkusio/quarkus/pull/54840
