### ISSUE TITLE
CSRF: head is already written

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#34375]
### Describe the bug

Sometimes I'm getting this exception:

```
2023-06-28 12:26:51,627 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to / failed, error id: f847bb1a-b636-4561-b59b-cc522052a2c0-3: java.lang.IllegalStateException: Response head already sent
	at io.vertx.core.http.impl.Http1xServerResponse.checkHeadWritten(Http1xServerResponse.java:709)
	at io.vertx.core.http.impl.Http1xServerResponse.addCookie(Http1xServerResponse.java:847)
	at io.quarkus.csrf.reactive.runtime.CsrfRequestResponseReactiveFilter.createCookie(CsrfRequestResponseReactiveFilter.java:233)
	at io.quarkus.csrf.reactive.runtime.CsrfRequestResponseReactiveFilter.filter(CsrfRequestResponseReactiveFilter.java:198)
	at io.quarkus.csrf.reactive.runtime.CsrfRequestResponseReactiveFilter$GeneratedServerResponseFilter$filter.filter(Unknown Source)
	at io.quarkus.csrf.reactive.runtime.CsrfRequestResponseReactiveFilter$GeneratedServerResponseFilter$filter_ClientProxy.filter(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I guess this happens if it's too late to write, which is probably fine, and besides there's no point in throwing, the response is already out, we should first check if the response is written and avoid setting cookies.

**Comment by geoand** [comment]
Should be as simple as #34377

**Comment by michalvavrik** [comment]
@FroMage could you provide git project on which I can reproduce it? I can send expired token myself, there not need to be failing test, but it would help to have set up on which I know it is failing. Thank you

**Comment by michalvavrik** [comment]
I had a look today and can't reproduce it without custom auth failure handler. I'm pretty sure this is not a Quarkus issue, we remove auth failure handler when RR started processing for a reason, also default auth failure handler should allow you to catch AuthenticationFailedException and handle it yourself. Other alternative would be Vert.X failure handler -> they all should work, it is documented here https://quarkus.io/guides/security-proactive-authentication-concept#how-to-customize-authentication-exception-responses

@FroMage I believe you should remove `io.quarkiverse.renarde.util.AuthenticationFailedExceptionMapper#myFilter` and use one of ^^. Setting custom `QuarkusHttpUser.AUTH_FAILURE_HANDLER` must be done with the highest caution. If you disagree (or it didn't help), please at least provide application with which you experienced it, so that I can have a look. Thank you

**Comment by michalvavrik** [comment]
So described logged message goes down to Renarde changes. I think this issue should be closed or we would need more information on the feedback I provided. Thank you.

**Comment by michalvavrik** [comment]
Problem with fixing it is that logged message only demonstrates user did something he should not.

**Comment by michalvavrik** [comment]
https://github.com/quarkusio/quarkus/pull/34377#issuecomment-1642339000
