### ISSUE TITLE
Quarkus + Azure Functions: NPE because the return value of "io.quarkus.arc.Arc.container()" is null

### ISSUE THREAD

**Issue by franden** [quarkusio/quarkus#34428]
### Describe the bug

Hello,

if I am try to invoke any azure function locally , I get an error:
````
Core Tools Version:       4.0.4915 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.14.0.19631


Functions:

        HttpExample: [GET,POST] http://localhost:7071/api/HttpExample

For detailed output, run func with --verbose flag.
[2023-06-30T06:57:15.579Z] OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
[2023-06-30T06:57:17.737Z] Worker process started and initialized.
[2023-06-30T06:57:20.291Z] Host lock lease acquired by instance ID '000000000000000000000000F933CC4F'.
[2023-06-30T06:58:14.340Z] Executing 'Functions.HttpExample' (Reason='This function was programmatically called via the host APIs.', Id=06f16185-2e47-4da6-bd41-ac389472a627)
[2023-06-30T06:58:14.438Z] Executed 'Functions.HttpExample' (Failed, Id=06f16185-2e47-4da6-bd41-ac389472a627, Duration=115ms)
[2023-06-30T06:58:14.440Z] System.Private.CoreLib: Exception while executing function: Functions.HttpExample. System.Private.CoreLib: Result: Failure
Exception: NullPointerException: Cannot invoke "io.quarkus.arc.ArcContainer.requestContext()" because the return value of "io.quarkus.arc.Arc.container()" is null
Stack: java.lang.NullPointerException: Cannot invoke "io.quarkus.arc.ArcContainer.requestContext()" because the return value of "io.quarkus.arc.Arc.container()" is null
[2023-06-30T06:58:14.441Z]      at io.quarkus.azure.functions.runtime.QuarkusAzureFunctionsMiddleware.invoke(QuarkusAzureFunctionsMiddleware.java:13)
[2023-06-30T06:58:14.442Z]      at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
[2023-06-30T06:58:14.443Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:80)
[2023-06-30T06:58:14.445Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:37)
[2023-06-30T06:58:14.445Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:12)
[2023-06-30T06:58:14.446Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
[2023-06-30T06:58:14.447Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:93)
[2023-06-30T06:58:14.448Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2023-06-30T06:58:14.448Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2023-06-30T06:58:14.449Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2023-06-30T06:58:14.450Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2023-06-30T06:58:14.451Z]      at java.base/java.lang.Thread.run(Thread.java:833)
[2023-06-30T06:58:14.452Z] .
````

### Expected behavior

Working HTTP communication

### Actual behavior

exception

### How to Reproduce?

1. download the example code from Quarkus’s application generator at [this link](https://code.quarkus.io/d?e=azure-functions&cn=code.quarkus.io).
2. extract
3. run `mvnw clean package azure-functions:run`
4. run curl http://localhost:7071/api/HttpExample 

Result:
![image](https://github.com/quarkusio/quarkus/assets/20822716/0d590baf-563e-4bc6-909a-6fdaf76b8311)

### Output of `uname -a` or `ver`

WindowsNT ZO05N004X0 2 6 x86

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

3.1.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39) Java version: 17.0.2, vendor: Eclipse Adoptium, runtime: ..... OpenJDK17U-jdk_x64_windows_hotspot_17.0.2_8\jdk-17.0.2+8 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

Used quarkus modules:
- quarkus-azure-functions
- azure-functions-java-library
- quarkus-arc

**Comment by mkouba** [comment]
CC @patriot1burke

**Comment by patriot1burke** [comment]
I cannot reproduce this issue.  You might have to update core tools and function runtime.  MSFT may have released their SPI in stages.

Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667

**Comment by franden** [comment]
no I updated the core tools and function runtime to the newest version 
```
Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667
```
and the issue is not present anymore. @patriot1burke Thank you for your support.
