### ISSUE TITLE
Quarkus 3 native image fail to start with NoSuchMethod Exception

### ISSUE THREAD

**Issue by humcqc** [quarkusio/quarkus#34443]
### Describe the bug

I have a Quarkus application with hibernate orm and flyway.
I use Discriminator Multitenancy with `@TenandId` annotation and use:
`
    @TenantId
    @Column(name = TENANT_ID_SQL_NAME, length = 40, nullable = false)
    public String tenantId;
`

When I run the app in dev mode , all works fine.
When I build a native image and use it in a container the app does not start:

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-06-30 14:01:04,222 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.NoSuchMethodException: org.hibernate.generator.internal.TenantIdGeneration.<init>()
	at java.base@17.0.7/java.lang.Class.getConstructor0(DynamicHub.java:3585)
	at java.base@17.0.7/java.lang.Class.newInstance(DynamicHub.java:626)
	at org.hibernate.boot.model.internal.GeneratorBinder.instantiateGenerator(GeneratorBinder.java:419)
	at org.hibernate.boot.model.internal.GeneratorBinder.lambda$generatorCreator$0(GeneratorBinder.java:362)
	at org.hibernate.mapping.Property.createGenerator(Property.java:482)
	at org.hibernate.tuple.entity.EntityMetamodel.buildGenerator(EntityMetamodel.java:479)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:313)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:499)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:140)
	at java.base@17.0.7/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base@17.0.7/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:92)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:75)
	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.processBootEntities(MappingMetamodelImpl.java:247)
	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.finishInitialization(MappingMetamodelImpl.java:185)
	at org.hibernate.internal.SessionFactoryImpl.initializeMappingModel(SessionFactoryImpl.java:320)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:270)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:156)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)


```

### Expected behavior

The app should start like in dev mode.

### Actual behavior

It generates an exception at startup.

### Output of `uname -a` or `ver`

Darwin 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

17.0.7

### Quarkus version or git rev

3.1.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.0 ------------------------------------------------------------  Build time:   2023-02-13 13:15:21 UTC Revision:     62ab9b7c7f884426cf79fbedcf07658b2dbe9e97  Kotlin:       1.8.10 Groovy:       3.0.13 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.7 (Eclipse Adoptium 17.0.7+7) OS:           Mac OS X 13.4 aarch64

**Comment by geoand** [comment]
Can you attach a sample application that behaves as you describe?

**Comment by humcqc** [comment]
Seems same behavior as https://github.com/quarkusio/quarkus/issues/32725 but with new class.

**Comment by geoand** [comment]
Might be. An application that exhibits the problem is the best way for us to troubleshoot

**Comment by humcqc** [comment]
will try with https://github.com/quarkusio/quarkus/tree/main/integration-tests/hibernate-orm-tenancy/discriminator/src and come back to you

**Comment by humcqc** [comment]
Finally, I used the jpa integration test to reproduce. 
Here is a PR : https://github.com/quarkusio/quarkus/pull/34452

**Comment by geoand** [comment]
Thanks for the PR!

> could we backport it in 3.1.x 

Once `3.2` is out, there will be no more 3.1 releases
