### ISSUE TITLE
Failure to pull non-cached deps during test launch with proxy private repository

### ISSUE THREAD

**Issue by agseijas** [quarkusio/quarkus#34448]
### Describe the bug

Quarkus (3.x) fails to pull dependencies from a private repository during tests, with this error:

```
Caused by: org.apache.http.client.HttpResponseException: status code: 401, reason phrase: Unauthorized (401)
        at org.eclipse.aether.transport.http.HttpTransporter.handleStatus(HttpTransporter.java:527)
        at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:396)
        at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:343)
        at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:64)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:482)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:414)
        ... 67 more
```

This happens if during the test launch, quarkus needs some extra dependency that maven couldn't resolve and cache (typically the `*-deployment` libraries).

The problem is because it tries to pull dependencies from repository defined in the settings.xml; but somehow misses the settings-security.xml setup. If explicitly providing such setup to maven, it works (similar problem can also be replicated in the IDEs)

The error is pretty obscure, because success or failure depends on having the dependency locally cached or not by just mere chance. So upgrading to a newer Quarkus version might make it fail (because of transitive dependency changes). This tipically hits pipelines quite hard and make usage of maven args or parameters mandatory in CI/CD and cumbersome for local dev. In CI/CD this can be overcome with workarounds such as `MAVEN_ARGS = "-Dsettings.security=~/.m2/settings-security.xml"` (if using maven >= 3.9).

Using pom.xml-> surefire config -> systemPropertyVariables -> `<settings.security>${settings.security}</settings.security>` doesn't work (looks like no system property used there works but /shrug)

Link to reproducer that's just a copy of the `quarkus-quickstarts/getting-started:3.1.3.Final` [project ](https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started).

https://github.com/agseijas/maven-security-quarkus/blob/master/README.md

### Expected behavior

The `GreetingResourceTest` test passes and the build ends successfully with maven

### Actual behavior

Error pulling dependencies during test launch:

```text
Caused by: org.apache.http.client.HttpResponseException: status code: 401, reason phrase: Unauthorized (401)
        at org.eclipse.aether.transport.http.HttpTransporter.handleStatus(HttpTransporter.java:527)
        at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:396)
        at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:343)
        at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:64)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:482)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:414)
        ... 67 more
```

### How to Reproduce?

Check the README file that explains the steps and tools setup needed to reproduce the issue:

https://github.com/agseijas/maven-security-quarkus/blob/master/README.md

### Output of `java -version`

openjdk version "20.0.1" 2023-04-18

### Quarkus version or git rev

3.1.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by aloubyansky** [comment]
Thanks for the report and the reproducer @agseijas

**Comment by agseijas** [comment]
Thanks @aloubyansky for the fix!
