### ISSUE TITLE
Unable to insert to database (mariadb) after DB version upgrade.

### ISSUE THREAD

**Issue by yujietan** [quarkusio/quarkus#34464]
### Describe the bug

Hi, 
I have encoountered a bug (sql syntax error) where my quarkus application cannot insert to the database after upgrading the DB version.

'10.6.11-6-MariaDB-enterprise-log' on single server
'10.6.12-8-MariaDB-enterprise-log' on mariadb maxscale

### Expected behavior

Able to insert to mariadb even after upgrading the db version

### Actual behavior

I am using Quarkus version 2.16.6.Final with the following db driver and hibernate library
api("io.quarkus:quarkus-hibernate-reactive-panache")
api("io.quarkus:quarkus-reactive-my sql-client")

The insert is working with the mariadb version (10.6.11-6-MariaDB) but once i changed version to 10.6.12-8-MariaDB. Its failing with the following stacktrace.

```posh
io.vertx.mysqlclient.MySQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
        at io.vertx.mysqlclient.impl.codec.CommandCodec.decodeErrorPacketPayload(CommandCodec.java:134)
        at io.vertx.mysqlclient.impl.codec.CommandCodec.handleErrorPacketPayload(CommandCodec.java:123)
        at io.vertx.mysqlclient.impl.codec.SimpleQueryCommandCodec.handleInitPacket(SimpleQueryCommandCodec.java:53)
        at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:56)
        at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePackets(MySQLDecoder.java:72)
        at io.vertx.mysqlclient.impl.codec.MySQLDecoder.channelRead(MySQLDecoder.java:48)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by geoand** [comment]
Does this problem still occur with Quarkus 3.1 or 3.2?

**Comment by yujietan** [comment]
Hi @geoand 

We found out the problem , it was due to the the code trying to open up a transaction to the 10.6.12.8 max scale database 

Also due to company policy, we are unable to upgrade to quarkus 3

We tried the following 2 method both getting error 



Method 1 (original implementation)
    @ReactiveTransactional
    internal fun addDataToMariaDb(data: List<ArchivedJobDetail>): Uni<Void> {
       return archivedJobDetailRepository.persist(data)
        }


Method 2

    internal fun addDataToMariaDb(data: List<ArchivedJobDetail>): Uni<Void> {

        return sessionFactory.withStatelessSession { session ->
            session.withTransaction { tx->
                tx.markForRollback()
                session.insertAll()
            }
       }
        }

Working version we tried is  without transaction and inserted successfully.


    internal fun addDataToMariaDb(data: List<ArchivedJobDetail>): Uni<Void> {

        return sessionFactory.withStatelessSession {
            it.insertAll(*data.toTypedArray())
        }
  }

**Comment by geoand** [comment]
> We found out the problem , it was due to the the code trying to open up a transaction to mariadb 10.6.12.8 (version) max scale database

Interesting!

> Also we are on quarkus 2.

Any reason you can't move up to 3.x?

**Comment by yujietan** [comment]
Did similar tests on quarkus 3.1.2.final. Getting the same errors :(. SQL syntax errors.

@QuarkusTest
class Final_Test {
    
    @Inject
    lateinit var  sessionFactory: SessionFactory

    @Test
    fun testdata(){
        var a = ArchivedJobDetail()
        var b = ArchivedJobDetail()
        a.env = "HAPPY"
        a.uid = 1
        b.env = "HAPPY"
        b.uid = 2
        var list = mutableListOf(a,b)
        //Fail
//      sessionFactory.withStatelessTransaction{
//                session -> session.insertAll(listOf(a,b))
//        }.await().indefinitely()
//

        //Fail
//      sessionFactory.withStatelessSession { session ->
//            session.withTransaction { tx->
//                tx.markForRollback()
//                session.insertAll(listOf(a,b))
//            }
//        }.await().indefinitely()

        //Works
        sessionFactory.withStatelessSession { session ->
            session.insertAll(*list.toTypedArray())
        }.await().indefinitely()

    }
}

**Comment by geoand** [comment]
Let's see what @tsegismont has to say

**Comment by tsegismont** [comment]
@yujietan thank you for reporting this. 

Can you please [report a bug upstream](https://github.com/eclipse-vertx/vertx-sql-client/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=) ?

It would help a lot if the upstream bug report includes:

- the name of the container image we can use to reproduce
- the DB schema and data setup queries used for testing

**Comment by yujietan** [comment]
Hi closing issue. Turns out the db server config is different. The one where is not working has ANSI_QUOTES enabled.. Thus failing with syntax error when inserting

**Comment by geoand** [comment]
Thanks for the update
