### ISSUE TITLE
HTTP Compression not working with quarkus-amazon-lambda-rest dependency 

### ISSUE THREAD

**Issue by itzsuman** [quarkusio/quarkus#34472]
### Describe the bug

No http compression happening  in my rest api if I add quarkus-amazon-lambda-rest maven dependency.

### Expected behavior

Http compression should occur

### How to Reproduce?

Reproduce : 

[gzip-reactive.zip](https://github.com/quarkusio/quarkus/files/11935497/gzip-reactive.zip)
1. mvn clean compile quarkus:dev
2. open a browser
3. open devtools / network tab
4. visit http://localhost:8080/hello/2
in devtools, you can see that no compression used for the response

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10]

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.5

### Quarkus version or git rev

3.1.2.Final

### Additional information

I have followed this link https://quarkus.io/guides/resteasy-reactive#http-compression

**Comment by patriot1burke** [comment]
Did it ever work for you?  I ask this because I removed transfer encoding support as chunked was screwing things up.

**Comment by itzsuman** [comment]
yes its working if I not add quarkus-amazon-lambda-rest maven dependency. If you remove the dependency from the attached 
project then it should work.

**Comment by patriot1burke** [comment]
No, I mean did it ever work with Lambda.  We might be at the mercy of the AWS API Gateway

**Comment by itzsuman** [comment]
I have a scenario where lambda may return more than  6 mb of data . Since knowing the limit of AWS lambda, we cant give back more than 6MB. And if we we enable API gateway encoding it will not fulfill our scenario as we get lambda timeout for more than 6mb data .. hence we want compression  at the lambda level..
But  quarkus-amazon-lambda-rest blocking the gzip/compression.. I have tried in my local, compression only work if I not include quarkus-amazon-lambda-rest dependency.

**Comment by itzsuman** [comment]
@patriot1burke Did you get any chance to look into this issue.

**Comment by itzsuman** [comment]
@geoand @patriot1burke @matejvasek Please help me on this.

**Comment by Serkan80** [comment]
@mkouba 

I can confirm that this also doesnt work when you have resteasy-reactive-jackson in your pom.xml (using Quarkus 3.2.1.Final)

**Comment by mkouba** [comment]
> @mkouba
> 
> I can confirm that this also doesnt work when you have resteasy-reactive-jackson in your pom.xml (using Quarkus 3.2.1.Final)

Unfortunately, I have no idea how `quarkus-amazon-lambda-rest` maps the JAX-RS resources to AWS and vice versa.

**Comment by itzsuman** [comment]
> > @mkouba
> > I can confirm that this also doesnt work when you have resteasy-reactive-jackson in your pom.xml (using Quarkus 3.2.1.Final)
> 
> Unfortunately, I have no idea how `quarkus-amazon-lambda-rest` maps the JAX-RS resources to AWS and vice versa.

I have tried with WriterInterceptor  to add Content-Encoding gzip using the below mentioned code. But getting QuarkusErrorHandler java.lang.RuntimeException: java.lang.NoSuchMethodException in lambda. 

`@Compress
@RegisterForReflection 
https://github.com/Provider
public class GzipFilter implements WriterInterceptor {

@Override 
public void aroundWriteTo(WriterInterceptorContext context)
throws IOException, WebApplicationException {
MultivaluedMap<String, Object> headers = context.getHeaders();
headers.add(HttpHeaders.CONTENT_ENCODING, "gzip");
final OutputStream outputStream = context.getOutputStream();
context.setOutputStream(new GZIPOutputStream(outputStream));
context.proceed();
}
}`

**Comment by itzsuman** [comment]
Fixed the above issue with 

`@RegisterForReflection(targets = {Resource.class})
public class YourReflectionConfig {}`

My GZIP’d/compressed response looks like: {J?J??t??`$?@??????....

However when try to decompress this gzip'd response using GZIPInputStream getting ' Not a gzip format' error

**Comment by geoand** [comment]
@itzsuman what the entire stacktrace?

**Comment by itzsuman** [comment]
> @itzsuman what the entire stacktrace?

`

ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /test/v1/resource failed, error id: 86d95716-2ee1-4eb1-936a-098e5e657777-1: jakarta.ws.rs.ProcessingException: Not in GZIP format
        at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.unwrap(InvocationBuilderImpl.java:223)
        at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:324)
        at com.test.rest.client.Client$$QuarkusRestClientInterface.getList(Unknown Source)
        at com.test.rest.client.Client$$CDIWrapper.getList(Unknown Source)
        at com.test.rest.client.Client$$CDIWrapper_ClientProxy.getList(Unknown Source)
        at com.test.bags.resource.TestResource.getLoad(TestResource.java:73)
        at com.test.bags.resource.TestResource$quarkusrestinvoker$getLoad_6cace0981d7af1a0ee81fd1133d6095f83f1a64e.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.zip.ZipException: Not in GZIP format
        at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:166)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
        at com.test.config.GZIPReadInterceptor.aroundReadFrom(GZIPReadInterceptor.java:23)
        at org.jboss.resteasy.reactive.client.impl.ClientReaderInterceptorContextImpl.proceed(ClientReaderInterceptorContextImpl.java:133)
        at org.jboss.resteasy.reactive.client.impl.ClientSerialisers.invokeClientReader(ClientSerialisers.java:160)
        at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.readEntity(RestClientRequestContext.java:199)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.mapToResponse(ClientResponseCompleteRestHandler.java:104)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:35)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:31)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:229)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:304)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        ... 2 more

`

**Comment by geoand** [comment]
That looks very weird as it includes JAX-RS Client elements.

**Comment by itzsuman** [comment]
is there anything wrong in compression logic.

**Comment by geoand** [comment]
Is the reproducer attached in the description up to date? Can I use it to see the stacktrace you mentioned?

**Comment by itzsuman** [comment]
> Is the reproducer attached in the description up to date? Can I use it to see the stacktrace you mentioned?

No, interceptor one is not attached . Attached one was quarkus HTTP Compression  https://quarkus.io/guides/resteasy-reactive#http-compression  but with aws-lambda that was not working . Hence tried with Interceptor .

**Comment by geoand** [comment]
Do you have that experiment anywhere I can try?

**Comment by itzsuman** [comment]
yes , you can check the reproduced attached one. If you remove the lambda dependency from pom then only compression happen

**Comment by itzsuman** [comment]
@geoand Please let me know if you want any update on attached reproducer . Reproducer one based on quarkus HTTP Compression but not working with aws lambda.

**Comment by itzsuman** [comment]
> Do you have that experiment anywhere I can try?

@geoand  Please let me know if you want any update on attached reproducer . Reproducer one based on quarkus HTTP Compression but not working with aws lambda.

**Comment by geoand** [comment]
I have not had to test it unfortunately, it will likely have to wait until next week.

**Comment by Serkan80** [comment]
I just want  to remind that compression also doesn’t work when resteasy-reactive-jackson is on the classpath.

**Comment by itzsuman** [comment]
> I have not had to test it unfortunately, it will likely have to wait until next week.

@geoand  Did you get any chance to check the issue.

**Comment by geoand** [comment]
Nope, as I was out for a conference last week and as a result I have a
large backlog

**Comment by geoand** [comment]
> I just want to remind that compression also doesn’t work when resteasy-reactive-jackson is on the classpath.

Do you have a sample for this? 

cc @mkouba

**Comment by mkouba** [comment]
Like I mentioned earlier, I have no idea how `quarkus-amazon-lambda-rest` works internally but it seems that in the dev mode, Quarkus starts a mock AWS Lambda server, so if you do `HTTP GET http://localhost:8080/hello/2` then the request hits the mock server, is converted to a JSON message that is consumed by the ["Quarkus Lambda Poll loop"](https://quarkus.io/guides/aws-lambda-http#live-coding-and-simulating-aws-lambda-environment-locally); i.e. not by the regular HTTP server. So the question is how the mock server handles the requests... :shrug:

**Comment by geoand** [comment]
I think what @Serkan80 was saying that the problem manifests **without** Amazon Lambda

**Comment by mkouba** [comment]
> I think what @Serkan80 was saying that the problem manifests **without** Amazon Lambda

I see, we'll need a dedicated reproducer then...

**Comment by geoand** [comment]
That would likely require input from @patriot1burke

**Comment by geoand** [comment]
Can someone provide an up to date reproducer for this issue?

**Comment by geoand** [comment]
We have made some related changes recently that could have fixed this, so unless someone comes up with an to date reproducer for this issue, I'll close it soon
