### ISSUE TITLE
grpc injection error:  org.demo.HelloGrpc cannot be injected into org.demo.HelloGrpcServiceTest#helloGrpc

### ISSUE THREAD

**Issue by anborg** [quarkusio/quarkus#34534]
### Describe the bug

Expected: Grpc injection works.

Hello service should work
![image](https://github.com/quarkusio/quarkus/assets/56970398/ee574c64-afdb-4bad-91f0-176d85ae79ff)

Actual : 

See error stack trace below

### Expected behavior

HelloGrpc service must respond from bloomRpc

Injection in Test classes must not throw error

### Actual behavior

Stack trace:

```log
2023-07-04 20:04:32,570 WARN  [io.qua.hib.rea.dep.HibernateReactiveProcessor] (build-15) Hibernate Reactive is disabled because no JPA entities were found
2023-07-04 20:04:32,571 WARN  [io.qua.hib.orm.dep.HibernateOrmProcessor] (build-32) Hibernate ORM is disabled because no JPA entities were found
2023-07-04 20:04:32,637 WARN  [io.qua.hib.rea.dep.HibernateReactiveProcessor] (build-77) Skipping registration of ReactiveSessionFactoryProducer bean because exact
ly one persistence unit is required for their registration
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-07-04 20:04:41,770 INFO  [io.qua.grp.run.GrpcServerRecorder] (Quarkus Main Thread) Registering gRPC reflection service

2023-07-04 20:04:41,982 INFO  [io.qua.grp.run.GrpcServerRecorder] (Quarkus Main Thread) Starting new Vert.x gRPC server ...
2023-07-04 20:04:42,556 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-rest-grpc 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.1.3.Final) started in 14.654s. Liste
ning on: http://localhost:8080
2023-07-04 20:04:42,564 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-07-04 20:04:42,572 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, grpc-server, hibernate-orm, hibernate-reactive, reactive-pg-client, reac
tive-routes, rest-client-reactive, rest-client-reactive-jackson, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-openapi, swag
ger-ui, vertx]

--
2023-07-04 20:06:02,015 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #1 ====================
2023-07-04 20:06:02,018 ERROR [io.qua.test] (Test runner thread) Test GreetingResourceTest#testHelloEndpoint() failed 
: java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.grpc.deployment.GrpcClientProcessor#discoverInjectedClients threw an exception: jakarta.enterprise.inject.spi.DeploymentExce
ption: org.demo.HelloGrpc cannot be injected into org.demo.HelloGrpcServiceTest#helloGrpc - only Mutiny service interfaces, blocking stubs, reactive stubs based on
 Mutiny and io.grpc.Channel can be injected via @GrpcClient
        at io.quarkus.grpc.deployment.GrpcClientProcessor.invalidInjectionPoint(GrpcClientProcessor.java:445)
        at io.quarkus.grpc.deployment.GrpcClientProcessor.discoverInjectedClients(GrpcClientProcessor.java:198)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:640)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:711)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)
        at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)   
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)   
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)      
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
        at org.junit.platform.launcher.core.DefaultLauncherSession$Deleguncher.execute(DefaultLauncherSession.java:91)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
        at io.quarkus.deployment.dev.testing.JunitTestRunner$2.run(JunitTestRunner.java:227)
        at io.quarkus.deployment.dev.testing.ModuleTestRunner$2.run(ModuleTestRunner.java:89)
        at io.quarkus.deployment.dev.testing.TestSupport.runInternal(TestSupport.java:462)
        at io.quarkus.deployment.dev.testing.TestSupport$3.run(TestSupport.java:382)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.grpc.deployment.GrpcClientProcessor#discoverInjectedClients threw an exception: jakarta.enterprise.inject.spi.DeploymentExce
ption: org.demo.HelloGrpc cannot be injected into org.demo.HelloGrpcServiceTest#helloGrpc - only Mutiny service interfaces, blocking stubs, reactive stubs based on
 Mutiny and io.grpc.Channel can be injected via @GrpcClient
        at io.quarkus.grpc.deployment.GrpcClientProcessor.invalidInjectionPoint(GrpcClientProcessor.java:445)
        at io.quarkus.grpc.deployment.GrpcClientProcessor.discoverInjectedClients(GrpcClientProcessor.java:198)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:223)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:607)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:655)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
        ... 35 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.grpc.deployment.GrpcClientProcessor#discoverInjectedClients threw an exception: jakarta.enterprise.inject.spi.DeploymentExce
ption: org.demo.HelloGrpc cannot be injected into org.demo.HelloGrpcServiceTest#helloGrpc - only Mutiny service interfaces, blocking stubs, reactive stubs based on
 Mutiny and io.grpc.Channel can be injected via @GrpcClient
        at io.quarkus.grpc.deployment.GrpcClientProcessor.invalidInjectionPoint(GrpcClientProcessor.java:445)
        at io.quarkus.grpc.deployment.GrpcClientProcessor.discoverInjectedClients(GrpcClientProcessor.java:198)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        ... 46 more
Caused by: jakarta.enterprise.inject.spi.DeploymentException: org.demo.HelloGrpc cannot be injected into org.demo.HelloGrpcServiceTest#helloGrpc - only Mutiny serv
ice interfaces, blocking stubs, reactive stubs based on Mutiny and io.grpc.Channel can be injected via @GrpcClient
        at io.quarkus.grpc.deployment.GrpcClientProcessor.invalidInjectionPoint(GrpcClientProcessor.java:445)
        at io.quarkus.grpc.deployment.GrpcClientProcessor.discoverInjectedClients(GrpcClientProcessor.java:198)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


2023-07-04 20:06:02,279 ERROR [io.qua.test] (Test runner thread) >>>>>>>>>>>>>>>>>>>> Summary: <<<<<<<<<<<<<<<<<<<<
GreetingResourceTest#testHelloEndpoint() java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.grpc.deployment.GrpcClientProcessor#discoverInjectedClients threw an exception: jakarta.enterprise.inject.spi.DeploymentExce
ption: org.demo.HelloGrpc cannot be injected into org.demo.HelloGrpcServiceTest#helloGrpc - only Mutiny service interfaces, blocking stubs, reactive stubs based on
 Mutiny and io.grpc.Channel can be injected via @GrpcClient
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

### How to Reproduce?

To reproduce: 
```sh
git clone git@github.com:anborg/corp-users-q-rest-grpc.git

# Generate grpc java  -- protos stored externally, in future .proto will be in a different repo
0_generate_grpc_java.bat

# run 
dev.bat
#invoke tests by pressing 'r'

# To this project, in future I'll have to add resteasy-reactive with hibernate-reactive & r2dbc
```

**Comment by cescoffier** [comment]
So there are multiple issues due to the setup.

1. If you use the maven gRPC plugin - do not configure the output directory, or Quarkus cannot find the classes. This is the leading cause of the issue. So remove that line:
```
<outputDirectory>${basedir}/src/zgen/proto/java</outputDirectory> <!-- Generate in java-new, build from java -->
```

That would also remove the need for the maven build helper.

2. I recommend packaging your protos in an artifact and having a dependency on this artifact. Then use the Quarkus codegen facilities to generate the Java files correctly. That will avoid many surprises. 

3. Finally,  your code was not importing the right gRPC classes:

```java
package org.demo;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.time.Duration;

import corp.model.HelloGrpc;
import corp.model.HelloReply;
import corp.model.HelloRequest;
import io.quarkus.grpc.GrpcClient;
import io.quarkus.test.junit.QuarkusTest;

import org.junit.jupiter.api.Test;


@QuarkusTest
public class HelloGrpcServiceTest {

    @GrpcClient("hello")
    HelloGrpc helloGrpc;

    @Test
    public void testHello() {
        HelloReply reply = helloGrpc
                .sayHello(HelloRequest.newBuilder().setName("Neo").build()).await().atMost(Duration.ofSeconds(5));
        assertEquals("Hello Neo!", reply.getMessage());
    }

}
```

```java
package org.demo;

import corp.model.HelloReply;
import corp.model.HelloRequest;
import io.quarkus.grpc.GrpcService;

import io.smallrye.mutiny.Uni;
import corp.model.HelloGrpc;

@GrpcService
public class HelloGrpcService implements HelloGrpc {

    @Override
    public Uni<HelloReply> sayHello(HelloRequest request) {
        return Uni.createFrom().item("Hello " + request.getName() + "!")
                .map(msg -> HelloReply.newBuilder().setMessage(msg).build());
    }

}
```

**Comment by anborg** [comment]
Main focus: 

Thanks, I changed the right pckage: import corp.model.HelloGrpc;

I EXPECT: 

If  a class was not found. Quarkus system should complain  ClassNotFoundError type of error. Not something else. Please reopen or create appropriate bug/issue if needed/



----
Side point, minor point, not the main focus: 
<outputDirectory>${basedir}/src/zgen/proto/java</outputDirectory> <!-- Gene

I need to generate the classes once a while and check it in zgen folder. I don't want any oth

**Comment by cescoffier** [comment]
It was not an ClassNotFoundError because your generation was containing the right classes. You may have generated them with a bad package at some point and kept them around. It's one of the reason why generated classes should not be checked in.

**Comment by anborg** [comment]
I regenerated afresh [code/service has right package name corp.mode.HelloGrpc].  I expect the 'hello service' to be up and running. Hmmm ... 

![image](https://github.com/quarkusio/quarkus/assets/56970398/73fdc104-870e-4d9e-820e-e00f6a4bf4f7)

**Comment by cescoffier** [comment]
Can you provide another clean reproducer with the recommendations I made?
