### ISSUE TITLE
Quarkus 3 hibernate-orm with JDBC driver throws java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by LazaroR94** [quarkusio/quarkus#34560]
### Describe the bug

Hello Quarkus community! I have recently created a new project with hibernate-orm and a JDBC driver in Quarkus 3 but I have been experiencing a very strange Vertx error on runtime that I cannot decipher on my own as to why it's happening. If I convert the code to reactive using the reactive extensions then the error goes away??

Quarkus dependencies:

```
implementation("io.quarkus:quarkus-hibernate-validator")
    implementation("io.quarkus:quarkus-jdbc-oracle")
    implementation("io.quarkus:quarkus-smallrye-reactive-messaging-kafka")
    implementation("io.quarkus:quarkus-quartz")
    implementation("io.quarkus:quarkus-config-yaml")
    implementation("io.quarkus:quarkus-kotlin")
    implementation("io.quarkus:quarkus-hibernate-orm")
    implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
    implementation("io.quarkus:quarkus-smallrye-health")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("io.quarkus:quarkus-arc")
```

The error I get at runtime:

```
ERROR [io.qua.dep.dev.DevModeMain] (main) Quarkus dev mode failed to start: java.lang.NoClassDefFoundError: io/vertx/core/impl/transports/JDKTransport
    at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor.initializeDevConsoleVertx(DevConsoleProcessor.java:243)
    at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleProcessor.initializeVirtual(DevConsoleProcessor.java:151)
    at io.quarkus.vertx.http.deployment.devmode.console.DevConsoleFailedStartHandler.handleFailedInitialStart(DevConsoleFailedStartHandler.java:9)
```

This is with a brand new Quarkus 3 project using **Quarkus 3.2.0.Final**. I have tried to update the Vertx version throughout the project to the latest `4.4.4` but when I do so I get hit with this error at runtime:

```
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Model classes are defined for the default persistence unit, but no default datasource was found. The default EntityManagerFactory will not be created. To solve this, configure the default datasource. Refer to https://quarkus.io/guides/datasource for guidance.
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.handleHibernateORMWithNoPersistenceXml(HibernateOrmProcessor.java:872)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.configurationDescriptorBuilding(HibernateOrmProcessor.java:332)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

This is how my application.yml looks like:

```
  datasource:
    db-kind: oracle
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
    jdbc:
      url: ${ORACLE_URL}
```

### Expected behavior

Quarkus should start up without these issues as it is configured correctly (as it is a fresh project). 

### Actual behavior

Quarkus cannot start because of either of the two errors mentioned above. This seems to happen using a JDBC datasource, if I revert to a reactive datasource then the problem goes away.

### How to Reproduce?

- Spin up a new Quarkus 3 project using Hibernate ORM and a JDBC driver

I am not sure if this is relevant or not, but these are the dependencies that I have in my project:

```
implementation("io.quarkus:quarkus-hibernate-validator")
    implementation("io.quarkus:quarkus-jdbc-oracle")
    implementation("io.quarkus:quarkus-smallrye-reactive-messaging-kafka")
    implementation("io.quarkus:quarkus-quartz")
    implementation("io.quarkus:quarkus-config-yaml")
    implementation("io.quarkus:quarkus-kotlin")
    implementation("io.quarkus:quarkus-hibernate-orm")
    implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
    implementation("io.quarkus:quarkus-smallrye-health")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("io.quarkus:quarkus-arc")
```

### Output of `uname -a` or `ver`

Darwin C02G54SCMD6R 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "11.0.18" 2023-01-17 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.18+9-LTS-195, mixed mode)

### Quarkus version or git rev

Quarkus 3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by gsmet** [comment]
I think it would help if you attached a sample project showing the issue.

**Comment by LazaroR94** [comment]
@gsmet I cannot attach my project as it is en enterprise project, but still, it is pretty much a fresh new project. Are you referring to this?

```
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.2.0.Final
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.2.0.Final
```
