### ISSUE TITLE
Negotiation or dynamic media type not supported yet for Multi

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#34621]
### Describe the bug

My example stack: Mongo reactive, Kotlin/Kotlin Coroutines/ Resteasy Reactive

```bash 
Suppressed: java.lang.IllegalStateException: Negotiation or dynamic media type not supported yet for Multi: please use the @Produces annotation when returning a Multi
		at org.jboss.resteasy.reactive.server.handlers.PublisherResponseHandler.handle(PublisherResponseHandler.java:310)
		at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
		at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
		at org.jboss.resteasy.reactive.server.runtime.kotlin.FlowToPublisherHandler$handle$1.invokeSuspend$lambda$0(FlowToPublisherHandler.kt:34)
		at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:92)
		at org.jboss.resteasy.reactive.server.runtime.kotlin.FlowToPublisherHandler$handle$1.invokeSuspend(FlowToPublisherHandler.kt:34)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
		at org.jboss.resteasy.reactive.server.runtime.kotlin.VertxDispatcher.dispatch$lambda$0(ApplicationCoroutineScope.kt:45)
		at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
		at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
		at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

In My example, I use `asFlow` to convert `Multi` to `Flow` and use a endpoint to expose it.

```kotlin 
@ApplicationScoped
class PostRepository : ReactivePanacheMongoRepository<Post> {
    fun findByTitle(title: String) = find("title", title).firstResult()
}
```

In the `PostResources`:

```kotlin
@GET
suspend fun all() = postRepository.streamAll().asFlow()
```

The testing codes to raise the exception.

```kotlin
@QuarkusTest
class PostResourcesTest {

    @InjectMock
    lateinit var postRepository: PostRepository

    @Test
    fun `get all posts`() {
        `when`(postRepository.streamAll())
            .thenReturn(
                Multi.createFrom().items(
                    Post(ObjectId(), "foo", "bar", LocalDateTime.now()),
                    Post(ObjectId(), "foo2", "bar2", LocalDateTime.now())
                )
            )

        //@formatter:off
        given()
            .accept(ContentType.JSON)
        .`when`()
            .get("/posts")
        .then()
            .statusCode(200)
            .log().all()
            .body("size()", `is`(2),
                "[0].title", `is`("foo")
            )
        //@formatter:on

        verify(postRepository, times(1)).streamAll()
        verifyNoMoreInteractions(postRepository)
    }
}
```

### Actual behavior

Resteasy(reactive) can not render the `Flow` result as expected.

### How to Reproduce?

Example codes: https://github.com/hantsy/quarkus-sandbox/tree/master/mongodb-kotlin-co

1. clone 
2. Run the PostResourceTest

### Output of `java -version`

17

### GraalVM version (if different from Java)

not test

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: C:\Users\hantsy\.m2\wrapper\dists\apache-maven-3.8.8-bin\67c30f74\apache-maven-3.8.8

**Comment by geoand** [comment]
Have you tried adding `@Producer("application/json")` to the resource method?

**Comment by hantsy** [comment]
@geoand But I have a question here, I have set the `Accept: application/json` in the tests, if the server is content negotiate, it should return `application/json`  content type as expected.

The blocking version, see [here](https://github.com/hantsy/quarkus-sandbox/blob/master/mongodb-kotlin/src/main/kotlin/com/example/PostResources.kt#L22), where returns a `Stream<T>`, without explicit `@Produces()` on methods, it worked well.

**Comment by geoand** [comment]
Streaming content with `Publisher` is always an exceptional case :)
