### ISSUE TITLE
No current Vertx context found

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#34634]
I try to update [my Quarkus example](https://github.com/hantsy/quarkus-sandbox/tree/master/resteasy-reactive) to the latest 3.2.0.Final, but when running `./mvnw Quarkus:dev`, I got the following exception:

```bash 
2023-07-08 13:08:33,074 INFO  [org.exa.DataInitializer] (Quarkus Main Thread) The application is starting...
2023-07-08 13:08:33,175 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-07-08 13:08:33,173 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus      
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: No current Vertx context found
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.vertxContext(SessionOperations.java:186)
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.getSession(SessionOperations.java:143)
        at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.getSession(AbstractJpaOperations.java:364)
        at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.deleteAll(AbstractJpaOperations.java:260)
        at org.example.PostRepository.deleteAll(PostRepository.java)
        at org.example.PostRepository_ClientProxy.deleteAll(Unknown Source)
        at org.example.DataInitializer.onStart(DataInitializer.java:30)
        at org.example.DataInitializer_Observer_onStart_b1ec74dcd02168bc83cc4e1229668f13327ebce5.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        ... 13 more

```

The DataIntializer is a bean to insert some sample at startup.

```java
@ApplicationScoped
@Startup
public class DataInitializer {
    private static final Logger LOGGER = Logger.getLogger(DataInitializer.class.getName());

    @Inject
    PostRepository posts;

    // There is an issue call reactive opertions in the blocking codes.
    // see: https://github.com/quarkusio/quarkus/issues/14044
    public void onStart(@Observes StartupEvent ev) {
        LOGGER.info("The application is starting...");

        Post first = Post.of("Hello Quarkus", "My first post of Quarkus");
        Post second = Post.of("Hello Again, Quarkus", "My second post of Quarkus");

        this.posts.deleteAll()
                .onItem().invoke(l -> LOGGER.log(Level.INFO, "deleted {0} posts.", new Object[]{l}))
                .flatMap(d -> this.posts.persist(List.of(first, second)))
                .flatMap(v -> this.posts.findAll().list())
                .subscribe()
                .with(
                        rows -> rows.forEach(r -> LOGGER.log(Level.INFO, "data:{0}", r)),
                        err -> LOGGER.log(Level.SEVERE, "error:{0}", err.toString())
                );
    }

    void onStop(@Observes ShutdownEvent ev) {
        LOGGER.info("The application is stopping...");
    }
}

```

_Originally posted by @hantsy in https://github.com/quarkusio/quarkus/discussions/34616_

**Comment by hantsy** [comment]
The Vertx context is not ready at the application startup stage?

**Comment by mschorsch** [comment]
You have to use [VertxContextSupport](https://quarkus.io/guides/vertx#executing-asynchronous-code-from-a-blocking-thread).

**Comment by hantsy** [comment]
@mschorsch I did not use `Mutiny.SessionFactory` here, just used the general [Reactive Repository pattern.](https://github.com/hantsy/quarkus-sandbox/blob/master/resteasy-reactive/src/main/java/org/example/PostRepository.java)

**Comment by hantsy** [comment]
@mschorsch There is another example use Hibernate Reactive `Mutiny.SessionFactory` and Resteasy reactive, it is working well. 

see: https://github.com/hantsy/quarkus-sandbox/tree/master/hibernate-reactive

**Comment by geoand** [comment]
@hantsy you also try adding `@ActivateRequestContext` to `onStart`

**Comment by hantsy** [comment]
> You have to use [VertxContextSupport](https://quarkus.io/guides/vertx#executing-asynchronous-code-from-a-blocking-thread).
> 
> ```java
> void onStart(@Observes StartupEvent event, Mutiny.SessionFactory sf) {
>    VertxContextSupport.subscribeAndAwait(() -> {
>       sf.withTransaction(session -> session.persist(new Person()));
>    });
> }
> ```

Tried to wrap the onStart method, did not work.

**Comment by mkouba** [comment]
> > You have to use [VertxContextSupport](https://quarkus.io/guides/vertx#executing-asynchronous-code-from-a-blocking-thread).
> > ```java
> > void onStart(@Observes StartupEvent event, Mutiny.SessionFactory sf) {
> >    VertxContextSupport.subscribeAndAwait(() -> {
> >       sf.withTransaction(session -> session.persist(new Person()));
> >    });
> > }
> > ```
> 
> Tried to wrap the onStart method, did not work.

What exactly didn't work?

If using Panache then something like this should work:

```java
void onStart(@Observes StartupEvent event) {
   VertxContextSupport.subscribeAndAwait(() -> {
      Panache.withTransaction(() -> entity.persist(new Person()));
   });
}
```

**Comment by mkouba** [comment]
Ok, so this seems to work just fine:

```java
@ApplicationScoped
public class DataInitializer {

    private static final Logger LOGGER = Logger.getLogger(DataInitializer.class.getName());

    @Inject
    PostRepository posts;

    public void onStart(@Observes StartupEvent ev) throws Throwable {
        LOGGER.info("The application is starting...");
        VertxContextSupport.subscribeAndAwait(() -> {
            return Panache.withTransaction(() -> {
                Post first = Post.of("Hello Quarkus", "My first post of Quarkus");
                Post second = Post.of("Hello Again, Quarkus", "My second post of Quarkus");

                return posts.deleteAll()
                        .onItem().invoke(l -> LOGGER.infof("deleted %s posts.", l))
                        .chain(d -> posts.persist(first, second))
                        .chain(v -> posts.findAll().list())
                        .invoke(all -> LOGGER.infof("found %s posts.", all.size()));

            });
        });
    }

    void onStop(@Observes ShutdownEvent ev) {
        LOGGER.info("The application is stopping...");
    }
}
```

Of course, I had to remove the `subscribe()` part from the code because the returned supplier must return `Uni`.

Also the `@Startup` annotation is unnecessary.

**Comment by hantsy** [comment]
@mkouba Yes, it fixes the startup issue, when I hit the endpoint via `curl http://localhost:8080/posts`, the following error will be displayed in the dev console.

```bash 
2023-07-11 15:01:16,435 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /posts failed, error id: 0a927305-3c01-4af0-90fe-3edf9c132057-1: java
.lang.IllegalStateException: No current Mutiny.Session found
        - no reactive session was found in the context and the context was not marked to open a new session lazily
        - you might need to annotate the business method with @WithSession
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.getSession(SessionOperations.java:155)
        at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.getSession(AbstractJpaOperations.java:364)
        at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.findAll(AbstractJpaOperations.java:180)
        at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.listAll(AbstractJpaOperations.java:191)
        at com.example.PostRepository.listAll(PostRepository.java)
        at com.example.PostRepository_ClientProxy.listAll(Unknown Source)
        at com.example.PostResources.getAllPosts(PostResources.java:30)
        at com.example.PostResources_ClientProxy.getAllPosts(Unknown Source)
        at com.example.PostResources$quarkusrestinvoker$getAllPosts_437e80f1c407b37a2afec8f3bf3a6fc45b5a0c17.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:102)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:88)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:290)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)


```

**Comment by hantsy** [comment]
The simple RepsoitoryTest still shows

```bash 
2023-07-11 15:06:27,102 ERROR [io.qua.test] (Test runner thread) Test PostRepositoryTest#testSave() failed 
: java.lang.IllegalStateException: No current Vertx context found
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.vertxContext(SessionOperations.java:186)
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.getSession(SessionOperations.java:143)
        at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.getSession(AbstractJpaOperations.java:364)
        at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:37)
        at io.quarkus.hibernate.reactive.panache.PanacheRepositoryBase.persist(PanacheRepositoryBase.java:54)
        at com.example.PostRepository_ClientProxy.persist(Unknown Source)
        at com.example.PostRepositoryTest.testSave(PostRepositoryTest.java:20)

```

**Comment by mkouba** [comment]
> Yes, it fixes the application startup issue, when I hit the endpoint via curl http://localhost:8080/posts, the following error will be displayed in the dev console.

Yes, but that's a completely different issue. You'll need to annotate the resource method with `@WithSession`/`@WithTransaction`. We do open a new session automatically in some cases but we don't support the repository pattern yet. Currently, we only detect Panache entities used in a JAX-RS resource. In theory, we should be able to do the same for repositories as well.

> The simple RepsoitoryTest still shows...

Keep in mind, that your repository/entities tests will need some update too. Specifically, you'll need to switch to `@RunOnVertxContext` and `UniAsserter`; see https://quarkus.io/guides/hibernate-reactive-panache#testing and https://quarkus.io/guides/hibernate-reactive#testing.

NOTE: In Quarkus 3.3 there is a `TransactionalUniAsserter` available in the `quarkus-test-hibernate-reactive-panache` artifact.

**Comment by hantsy** [comment]
Check the reproducer example codes in https://github.com/quarkusio/quarkus/issues/34634#issuecomment-1629207330, I only added a simple entity, a Repository, a Resources, it throws the same exception when access http://localhost:8080/posts

**Comment by mkouba** [comment]
> Check the reproducer example codes in [#34634 (comment)](https://github.com/quarkusio/quarkus/issues/34634#issuecomment-1629207330), I only added a simple entity, a Repository, a Resources, it throws the same exception when access http://localhost:8080/posts

??? Like I said in https://github.com/quarkusio/quarkus/issues/34634#issuecomment-1630281052 one of the  `@WithSession`/`@WithTransaction` annotations fixes the problem.

**Comment by hantsy** [comment]
Added a `@WithSession` on the Repository directly, `curl http://localhost:8080` works. But I do not understand, I only use one db in the project, all session/transaction should be bound to the default database.

**Comment by mkouba** [comment]
> But I do not understand, I only use one db in the project, all session/transaction should be bound to the default database.

How is that related?

Anyway, the consequences of Hibernate Reactive Panache refactoring are explained in the [Migration Guide 3.0](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#hibernate-reactive-panache).

**Comment by hantsy** [comment]
Thanks for the migration info.

From Hibernate/JPA to Hibernate Reactive, this seems a little complex. If possible to hide the context switching for developers, to remove VertxContext... related annotaions.

I also tried the `Mutiny.Session` in my another hibernate example, https://github.com/hantsy/quarkus-sandbox/blob/master/hibernate-reactive/src/main/java/com/example/PostRepository.java, and app is running well, and Repository tests  are also passed without extra work.

**Comment by mkouba** [comment]
FYI here's the PR for the repository pattern: https://github.com/quarkusio/quarkus/pull/34671

**Comment by hantsy** [comment]
Micronaut Hibernate Reactive almost brought the same experience of Data Hibernate/JPA, just switched APIs to Reactor. 

https://github.com/hantsy/micronaut-sandbox/tree/master/data-hibernate-reactive

**Comment by mkouba** [comment]
> Micronaut Hibernate Reactive almost brought the same experience of Data Hibernate/JPA, just switched APIs to Reactor.
> 
> https://github.com/hantsy/micronaut-sandbox/tree/master/data-hibernate-reactive

I don't see a big difference here :shrug:. Esp. after the PR mentioned in the https://github.com/quarkusio/quarkus/issues/34634#issuecomment-1630399936. 

Anyway, we're open for suggestions and improvements. So feel free to contribute ;-)

WRT `CustomerRepositoryTest` - I think that the Quarkus version would not need the `CountDownLatch` and `AtomicReference` constructs at all. So the quarkus test with `UniAsserter` should be even simpler.

**Comment by hantsy** [comment]
> FYI here's the PR for the repository pattern: #34671

How about getting rid of the Vertx helpers in the `Datainitializer`(`VertxContextSupport`) and testing codes(`@RunOnVertxContext`)? For an end user, the vertx context should be provided when calling Repository api.

**Comment by lucamolteni** [comment]
Unable to reproduce

**Comment by lucamolteni** [comment]
^

**Comment by geoand** [comment]
Thanks for checking
