### ISSUE TITLE
Native image building with podman fails

### ISSUE THREAD

**Issue by maarten-vandeperre** [quarkusio/quarkus#34666]
### Describe the bug

- podman version: 4.5.1
- Quarkus version: 3.0.3.Final
- Java version: 17
- OS: same error on Mac M1 and Linux
- Project: https://github.com/maarten-vandeperre/clean-architecture-software-sample-project 
- Command to mimic: sh scripts/monolith_quarkus_code_native_build.sh 

Error: 

[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.3.Final:build (default) on project monolith-configuration-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 125
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:427)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:263)
[ERROR]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:1589)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.3.Final:build (default) on project monolith-configuration-quarkus: Failed to build quarkus application
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:210)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:195)
    at java.util.concurrent.FutureTask.run (FutureTask.java:317)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:577)
    at java.util.concurrent.FutureTask.run (FutureTask.java:317)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
    at java.lang.Thread.run (Thread.java:1589)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to build quarkus application
    at io.quarkus.maven.BuildMojo.doExecute (BuildMojo.java:170)
    at io.quarkus.maven.QuarkusBootstrapMojo.execute (QuarkusBootstrapMojo.java:154)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:210)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:195)
    at java.util.concurrent.FutureTask.run (FutureTask.java:317)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:577)
    at java.util.concurrent.FutureTask.run (FutureTask.java:317)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
    at java.lang.Thread.run (Thread.java:1589)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 125
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:427)
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:263)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

### Expected behavior

I should expect it to work (as it does with docker).
Changing "podman" to "docker" works on both Mac M1 and Linux.
Command looks like this then:

```
./mvnw clean -T 10C package -X -DskipTests \
        -Dquarkus.package.type=native \
        -Dquarkus.native.container-build=true \
        -Dquarkus.native.container-runtime=docker \
        -Dquarkus.container-image.build=true \
        -Dquarkus.container-image.image=$CONTAINER_IMAGE \
        -Dquarkus.native.native-image-xmx=5G \
        -am -Pmonolith-quarkus,quarkus-native
```

### Actual behavior

Error: see bug description

### How to Reproduce?

See bug description

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

**Comment by gastaldi** [comment]
You should have other errors in the log, can you paste the full build output?

**Comment by maarten-vandeperre** [comment]
I see indeed another error as well: 
_(The complete build log is attached as well)_


[DEBUG] [io.netty.util.internal.PlatformDependent0] direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
    at io.netty.util.internal.ReflectionUtil.trySetAccessible (ReflectionUtil.java:31)
    at io.netty.util.internal.PlatformDependent0$5.run (PlatformDependent0.java:288)
    at java.security.AccessController.doPrivileged (AccessController.java:318)
    at io.netty.util.internal.PlatformDependent0.<clinit> (PlatformDependent0.java:282)
    at io.netty.util.internal.PlatformDependent.isAndroid (PlatformDependent.java:333)
    at io.netty.util.internal.PlatformDependent.<clinit> (PlatformDependent.java:88)
    at io.netty.util.AsciiString.<init> (AsciiString.java:225)
    at io.netty.util.AsciiString.<init> (AsciiString.java:212)
    at io.netty.util.AsciiString.cached (AsciiString.java:1403)
    at io.netty.util.AsciiString.<clinit> (AsciiString.java:48)
    at io.netty.handler.codec.http.HttpMethod.<init> (HttpMethod.java:140)
    at io.netty.handler.codec.http.HttpMethod.<clinit> (HttpMethod.java:36)
    at io.vertx.core.http.HttpMethod.<clinit> (HttpMethod.java:192)
    at io.quarkus.vertx.http.runtime.VertxHttpRecorder.<clinit> (VertxHttpRecorder.java:1430)
    at jdk.internal.misc.Unsafe.ensureClassInitialized0 (Native Method)
    at jdk.internal.misc.Unsafe.ensureClassInitialized (Unsafe.java:1160)
    at jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized (MethodHandleAccessorFactory.java:300)
    at jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor (MethodHandleAccessorFactory.java:103)
    at jdk.internal.reflect.ReflectionFactory.newConstructorAccessor (ReflectionFactory.java:201)
    at java.lang.reflect.Constructor.acquireConstructorAccessor (Constructor.java:547)
    at java.lang.reflect.Constructor.newInstanceWithCaller (Constructor.java:497)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:484)
    at io.quarkus.deployment.proxy.ProxyFactory.newInstance (ProxyFactory.java:274)
    at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy (BytecodeRecorderImpl.java:378)
    at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$57 (ExtensionLoader.java:663)
    at io.quarkus.deployment.ExtensionLoader$3.execute (ExtensionLoader.java:905)
    at io.quarkus.builder.BuildContext.run (BuildContext.java:282)
    at org.jboss.threads.ContextHandler$1.runWith (ContextHandler.java:18)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run (EnhancedQueueExecutor.java:2513)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1538)
    at java.lang.Thread.run (Thread.java:1589)
    at org.jboss.threads.JBossThread.run (JBossThread.java:501)

[build_log.txt](https://github.com/quarkusio/quarkus/files/12016055/build_log.txt)

**Comment by maarten-vandeperre** [comment]
Yes,

With this part of the scripts/monolith_quarkus_code_native_build.sh script:

` ./mvnw clean -T 10C package -X -DskipTests \
        -Dquarkus.package.type=native \
        -Dquarkus.native.container-build=true \
        -Dquarkus.native.container-runtime=podman \
        -Dquarkus.container-image.build=true \
        -Dquarkus.container-image.image=$CONTAINER_IMAGE \
        -Dquarkus.native.native-image-xmx=5G \
        -am -Pmonolith-quarkus,quarkus-native`

When I change podman to docker as follows, it works (but I prefer to use podman):

` ./mvnw clean -T 10C package -X -DskipTests \
        -Dquarkus.package.type=native \
        -Dquarkus.native.container-build=true \
        -Dquarkus.native.container-runtime=docker \
        -Dquarkus.container-image.build=true \
        -Dquarkus.container-image.image=$CONTAINER_IMAGE \
        -Dquarkus.native.native-image-xmx=5G \
        -am -Pmonolith-quarkus,quarkus-native`

**Comment by holly-cummins** [comment]
I tried running 

```
 ./mvnw clean -T 10C package -X -DskipTests \
        -Dquarkus.package.type=native \
        -Dquarkus.native.container-build=true \
        -Dquarkus.native.container-runtime=podman \
        -Dquarkus.container-image.build=true

```

on simple rest application, and I got a similar, but different error to what I saw above 

```
[1/7] Initializing...                                                                                    (0.0s @ 0.04GB)
Error: Could not find JNI configuration resource "META-INF/native-image/jansi/jni-config.json".
com.oracle.svm.core.util.UserError$UserException: Could not find JNI configuration resource "META-INF/native-image/jansi/jni-config.json".
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$2(ConfigurationParserUtils.java:96)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:515)
        at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:473)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:113)
```

**Comment by maarten-vandeperre** [comment]
@gsmet or @holly-cummins , any update on this issue?

**Comment by maarten-vandeperre** [comment]
@gsmet  and @holly-cummins. This issue is solved with podman 4.8.2 and Quarkus 3.6.3

**Comment by maarten-vandeperre** [comment]
issue resolved

**Comment by gsmet** [comment]
Cool! Thanks for the follow up!
