### ISSUE TITLE
No current Vertx context found with reactive resteasy and panache

### ISSUE THREAD

**Issue by scrocquesel** [quarkusio/quarkus#34687]
### Describe the bug

A user [reported an issue](https://github.com/quarkiverse/quarkus-amazon-services/issues/837) using AWS extension and reactive panache at the same time. Trying to reproduce the issue with s3 quickstart and I'm stuck trying to make it work.

First, adding `quarkus-hibernate-reactive-panache` and calling a JAX-RS endpoint that do not use Panache entity or repository but make S3 calls fails, trying to autoclose an on demand Session.

I see two issues:
- Could it be possible to narrow the detection of panache usage per method in a resource class.
- How to run a continuation on the Vertx ThreadPool after the s3 completionstage ? This is a bit off the issue but if narrowing is not possible this could solve this issue and explain usage of both s3 and panache in the same method

### Expected behavior

Request should return a 200 response. At least, it should not try to close a session. Looking at https://github.com/quarkusio/quarkus/pull/34671, it seems that the `WithSessionOnDemand` annotation is added even if the Resource does not inject a Panache entity nor repository. The detection mechanism is a bit too wide and it detects static usage of entity/repo in others methods.

### Actual behavior

Request failed with 

```
2023-07-11 22:59:56,208 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [amazon-s3, cdi, hibernate-orm, hibernate-reactive, hibernate-reactive-panache, reactive-pg-client, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
2023-07-11 23:00:17,048 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /async-s3 failed, error id: 35acc389-f5b0-4f34-bc59-b3506f412974-1: java.lang.IllegalStateException: No current Vertx context found
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.vertxContext(SessionOperations.java:186)
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.closeSession(SessionOperations.java:191)
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.lambda$withSessionOnDemand$0(SessionOperations.java:73)
        at io.smallrye.mutiny.Uni.lambda$eventually$1(Uni.java:580)
        at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
        at io.smallrye.mutiny.groups.UniOnItemOrFailure.lambda$call$2(UniOnItemOrFailure.java:68)
        at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:54)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:56)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$2(AsyncApiCallTimeoutTrackingStage.java:69)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:177)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:105)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.completeResponseFuture(MakeAsyncHttpRequestStage.java:238)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

With this repro : https://github.com/scrocquesel/quarkus-quickstarts/tree/s3_with_panache

1. inside `amazon-s3-quickstart`
2. quarkus dev
3. curl http://localhost:8080/async-s3.html

**Comment by geoand** [comment]
cc @Sgitario as well

**Comment by mkouba** [comment]
> Could it be possible to narrow the detection of panache usage per method in a resource class.

I'm afraid that it would be too costly. Currently, we only inspect the contstant pool to detect the usage of an entity (and repository after https://github.com/quarkusio/quarkus/pull/34671 is merged).

Still, I'm trying to understand the problem. It seems that there's no current Vert.x context when the attempt to close the session... Maybe we should use the [captured context](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-reactive-panache-common/runtime/src/main/java/io/quarkus/hibernate/reactive/panache/common/runtime/SessionOperations.java#L63) instead. @cescoffier WDYT?

**Comment by cescoffier** [comment]
I think all the s3 callbacks will be invoked on random thread (random in the unmanaged sense), which mean: no context. That could be the issue.

Even with context propagation, it would not work as the CS must be decorated by context propagation. 

Is there a way to specify on which executor the completion stages from the AWS sdk are resolved?

**Comment by mkouba** [comment]
> Is there a way to specify on which executor the completion stages from the AWS sdk are resolved?

I think that we need someone from the [`io.quarkiverse.amazonservices:quarkus-amazon-services`](https://github.com/quarkiverse/quarkus-amazon-services/graphs/contributors) team...

**Comment by gsmet** [comment]
@scrocquesel who created the issue is the maintainer of the Amazon Services extensions so we should be good :)

**Comment by scrocquesel** [comment]
> I think all the s3 callbacks will be invoked on random thread (random in the unmanaged sense), which mean: no context. That could be the issue.
> 
> Even with context propagation, it would not work as the CS must be decorated by context propagation.
> 
> Is there a way to specify on which executor the completion stages from the AWS sdk are resolved?

@cescoffier  I recently changed that so that it can now terminate on the Executor provided by `io.quarkus.deployment.builditem.ExecutorBuildItem`. It is a client configuration and AFAIK you can't override this on a per request basis. The client is configured no matter the context in which it will be consumed as a singleton.

The code looks like this right now

```java
    @GET
    public Uni<List<FileObject>> listFiles() {
        ListObjectsRequest listRequest = ListObjectsRequest.builder()
                .bucket(bucketName)
                .build();
        return Uni.createFrom().completionStage(() -> s3.listObjects(listRequest))
                .onItem().transform(result -> toFileItems(result));
    }
```

I tried something like 

```java
        var e = ContextInternal.current().executor();
        return Uni.createFrom().completionStage(() -> s3.listObjects(listRequest)).emitOn(e)
                .onItem().transform(result -> toFileItems(result));
```

but it didn't work.

**Comment by cescoffier** [comment]
I need to check one think about your second approach. I believe it's retrouve the netty executor, not the duplicated context one.

**Comment by scrocquesel** [comment]
> Ok, this way it cannot go back to the context.
> 
> We need to capture it and restore it.
> 
> So, there are multiple ways to do this:
> 
> * we can decorate the executor to capture the context and restore it
> * we can use the next-to-be vertx utilities which will provide an executor doing ^ (CC @jponge)
> 
> We can do the first approach for now. If someone tell me where to look I can have a look (next week unfortunately).
[This is where the executor is set on the client](https://github.com/quarkiverse/quarkus-amazon-services/blob/154da17e790a17182aec7c546b6b3f5f979b8b48/common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientCommonRecorder.java#L56) and you can test with this [integration test](https://github.com/quarkiverse/quarkus-amazon-services/blob/154da17e790a17182aec7c546b6b3f5f979b8b48/integration-tests/src/main/java/io/quarkus/it/amazon/s3/S3Resource.java#L47).


> I need to check one think about your second approach. I believe it's retrouve the netty executor, not the duplicated context one.
> 
> So you execute on the root context, not on the duplicated context.

With
```java
@GET
    public Uni<List<FileObject>> listFiles() {
        ListObjectsRequest listRequest = ListObjectsRequest.builder()
                .bucket(bucketName)
                .build();

        System.out.println("capture isOnVertxThread:" + Context.isOnVertxThread());
        System.out.println("capture isOnVertxThread:" + Context.isOnEventLoopThread());
        System.out.println("capture isOnVertxThread:" + Context.isOnWorkerThread());
        var e = ContextInternal.current().executor();
        return Uni.createFrom().completionStage(() -> s3.listObjects(listRequest)).emitOn(e)
                .onItem().transform(result -> {
                    System.out.println("transform isOnVertxThread:" + Context.isOnVertxThread());
                    System.out.println("transform isOnVertxThread:" + Context.isOnEventLoopThread());
                    System.out.println("transform isOnVertxThread:" + Context.isOnWorkerThread());   
                    return toFileItems(result);
                });
    }
```

```
capture isOnVertxThread:true
capture isOnVertxThread:true
capture isOnVertxThread:false
transform isOnVertxThread:true
transform isOnVertxThread:true
transform isOnVertxThread:false
```

and without the `emitOn(e)`

```
capture isOnVertxThread:true
capture isOnVertxThread:true
capture isOnVertxThread:false
transform isOnVertxThread:false
transform isOnVertxThread:false
transform isOnVertxThread:false
```

I also tried with `var e = ((ContextInternal) VertxContext.getOrCreateDuplicatedContext(ContextInternal.current())).executor();`

**Comment by scrocquesel** [comment]
I edit my previous comment to provide log trace with thread names

**Comment by cescoffier** [comment]
Thread names are not enough, duplicated contexts are not threads. 

You cannot use `var e = ContextInternal.current().executor();` - this is running on the root context, not on the duplicated one.

You need to do `var e = runnable -> captured.runOnContext(runnable)`

**Comment by scrocquesel** [comment]
> Thread names are not enough, duplicated contexts are not threads.
> 
> You cannot use `var e = ContextInternal.current().executor();` - this is running on the root context, not on the duplicated one.
> 
> You need to do `var e = runnable -> captured.runOnContext(runnable)`

Thanks, to compile I had to do

```java
Context context = Vertx.currentContext();
Executor e = command -> context.runOnContext(x -> command.run());
```

I guess the sample at https://github.com/quarkusio/quarkus/blob/26cb1bd3f327606f58fe897e48d2e2c87b0198c2/docs/src/main/asciidoc/duplicated-context.adoc?plain=1#L96-L103 is also not correct or does runOnContext recently changed ?

Is there an issue tracking the "next-to-be vertx utilities which will provide an executor doing ^" ?
I'll try to hook that directly in the extension but it is not using Vert.x and I would rather not add a dependency only for that.

**Comment by scrocquesel** [comment]
Trying to wrap the Executor is not working. By the time, the completion stage is executed, aws netty client has already moved to another thread and the `Vertx.currentContext()` is null.

https://github.com/aws/aws-sdk-java-v2/blob/4639d41ee6bc835ea2e53bb27ebb0d977c292d6c/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java#L91-L97
```java
    public CompletableFuture<Void> execute() {
        Promise<Channel> channelFuture = context.eventLoopGroup().next().newPromise();
        executeFuture = createExecutionFuture(channelFuture);
        acquireChannel(channelFuture);
        channelFuture.addListener((GenericFutureListener) this::makeRequestListener);
        return executeFuture;
    }
```

where `context.eventLoopGroup()` is the EventLoopGroup supplied by [`EventLoopGroupBuildItem`](https://github.com/quarkusio/quarkus/pull/33239)`.

**Comment by cescoffier** [comment]
You cannot use the netty executor or the EventLoopGroupBuildItem - because you will always have a root context, and not a duplicated context. Thus it breaks the propagation.

You will have only one way or another to use Vert.x.

The PR adding the next-to-be executor is this one: https://github.com/smallrye/smallrye-mutiny-vertx-bindings/pull/733

**Comment by manor-parmar** [comment]
try doing as below, capture the context and than restore it while emitting the completionStage

`// capture context
Context context = Vertx.currentContext();
Uni.createFrom()
	.completionStage(
			() -> {
				FileUpload fileUpload =
						s3TransferManager.uploadFile(...);
				return fileUpload.completionFuture();
			})
	.emitOn(command -> context.runOnContext(x -> command.run())) // Restore the context
	.onItem()
	.invoke(
			i -> {
				var status = i.response();
				log.info("s3 upload response:{}", status);
			})
	.onFailure()
	.invoke(e -> log.error("error:", e))
	.eventually(...);`

**Comment by adampoplawski** [comment]
Hello
We have similar problem. After reacrive transactional method with Panache, next flatmap that sends data to SNS gives "No current Vertx context found". We are using Quarkus 3.4. Is there recommended walkaround?

**Comment by FroMage** [comment]
Losing the Vert.x context is problematic, because CP doesn't propagate it, and indeed, delegates to it. How can we fix this @cescoffier @mkouba?

**Comment by cescoffier** [comment]
Unfortunately, there is no magic solution. You need to capture the context and restore it to emit the result produced by the completion stage of AWS.

**Comment by FroMage** [comment]
Well, there _could_ be magic, because Mutiny uses CP, and _if_ CP captured the current vert.x context, it could propagate it :)

**Comment by markusdlugi** [comment]
For completeness sake: we investigated the issues described above more thoroughly and it was actually related to the context being lost by the Quarkus Cache which we were using to reduce the number of calls to `getQueueUrl`. So it was actually not related to the AWS integration. I opened #39515 for that.

**Comment by scrocquesel** [comment]
Is `ContextAwareScheduler.delegatingTo(Infrastructure.getDefaultWorkerPool()).withGetOrCreateContext(vertx)` the correct approach?

In the Quarkus AWS extension, I inject the executor provided by the `ExecutorBuildItem`. The only issue I encounter was to deal with the TCCL because it is lost when using the AWS CRT-based HTTP client, which utilizes JNI. Thus, in Dev/Test mode, I wrap it with an executor that captures the TCCL.

Still, I am seeking a solution to capture the Vert.x context and restore it. One potential solution could involve having an AWS `ExecutorInterceptor` that captures the context before the request and restores it after the request when back on the thread provided by the configured thread executor. However, as far as I know, the Vert.x context can only be restored by switching to another thread, which is not feasible in this case.

**Comment by jponge** [comment]
> Is `ContextAwareScheduler.delegatingTo(Infrastructure.getDefaultWorkerPool()).withGetOrCreateContext(vertx)` the correct approach?

I'd say so

**Comment by markusdlugi** [comment]
> > Is `ContextAwareScheduler.delegatingTo(Infrastructure.getDefaultWorkerPool()).withGetOrCreateContext(vertx)` the correct approach?
> 
> I'd say so

From my tests, I think that this unfortunately doesn't work as expected, or at least I was unable to configure it correctly. The configuration I mentioned above with the `ContextAwareScheduler` would in fact result in the context not being preserved, regardless of whether using the AWS CRT-based client or the Netty NIO client or whether I was using `Infrastructure.getDefaultWorkerPool()` or `vertx.nettyEventLoopGroup()`. We got some dedicated unit tests for ensuring the Vertx context is preserved in our application now, and while they're all green with the `emitOn` approach, I can't get it to work with the `ContextAwareScheduler`.

Maybe someone who has a working configuration with `ContextAwareScheduler` could show how it's done, because I'd actually love to get rid of the tedious `emitOn` workaround. While that one is working reliably (if you make sure to wrap all CompletionStage usages properly *cough cough*), it's certainly cumbersome and error-prone...

**Comment by jponge** [comment]
`ScheduledExecutorService` supports different strategies to specify which Vert.x context shall be used. The key for `withGetOrCreateContext` to work is to make sure it gets called from a thread that has the Vert.x context that you need, otherwise it will create a new context, but it may not have the correct context for propagation to happen.
