### ISSUE TITLE
Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code

### ISSUE THREAD

**Issue by hntan** [quarkusio/quarkus#34717]
### Describe the bug

My jenkins build failed with the error below after upgrading to `quarkus 3.2.0.Final`, the maven version is `3.9.1`

```
INFO] --- quarkus:3.2.0.Final:generate-code (default) @ lqa-service ---
[WARNING] Error injecting: io.quarkus.maven.GenerateCodeMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NullPointerException: Cannot invoke "io.quarkus.devtools.messagewriter.MessageWriter.warn(String, Object[])" because "this.log" is null
  at BuildAnalyticsProvider.<init>(BuildAnalyticsProvider.java:35)
  at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
      \_ installed by: WireModule -> PlexusBindingModule
  at BootstrapSessionListener.<init>(BootstrapSessionListener.java:26)
      \_ for 2nd parameter buildAnalyticsProvider
  at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
      \_ installed by: WireModule -> PlexusBindingModule
  while locating BootstrapSessionListener
  while locating Object annotated with *
  while locating GenerateCodeMojo

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
....

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.655 s
[INFO] Finished at: 2023-07-13T02:21:32Z
[INFO] ------------------------------------------------------------------------
[INFO] [jenkins-event-spy] Generated ...abc.log
....

[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code (default) on project xxx-service: Execution default of goal io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code failed: Unable to load the mojo 'generate-code' (or one of its required components) from the plugin 'io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) [Guice/ErrorInjectingConstructor]: NullPointerException: Cannot invoke "io.quarkus.devtools.messagewriter.MessageWriter.warn(String, Object[])" because "this.log" is null
[ERROR]   at BuildAnalyticsProvider.<init>(BuildAnalyticsProvider.java:35)
[ERROR]   at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
[ERROR]       \_ installed by: WireModule -> PlexusBindingModule
[ERROR]   at BootstrapSessionListener.<init>(BootstrapSessionListener.java:26)
[ERROR]       \_ for 2nd parameter buildAnalyticsProvider
[ERROR]   at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
[ERROR]       \_ installed by: WireModule -> PlexusBindingModule
[ERROR]   while locating BootstrapSessionListener
[ERROR]   while locating Object annotated with *
[ERROR]   while locating GenerateCodeMojo
[ERROR]   at ClassRealm[plugin>io.quarkus.platform:quarkus-maven-plugin:Final, parent: URLClassLoader@723279cf]
[ERROR]       \_ installed by: WireModule -> PlexusBindingModule
[ERROR]   while locating Mojo annotated with @Named("io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code")
[ERROR] 
[ERROR] Learn more:
[ERROR]   https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
[ERROR] 
[ERROR] 1 error
[ERROR] 
[ERROR] ======================
[ERROR] Full classname legend:
[ERROR] ======================
[ERROR] BootstrapSessionListener: "io.quarkus.maven.components.BootstrapSessionListener"
[ERROR] BuildAnalyticsProvider:   "io.quarkus.maven.BuildAnalyticsProvider"
[ERROR] Final:                    "3.2.0.Final"
[ERROR] GenerateCodeMojo:         "io.quarkus.maven.GenerateCodeMojo"
[ERROR] Mojo:                     "org.apache.maven.plugin.Mojo"
[ERROR] Named:                    "com.google.inject.name.Named"
[ERROR] PlexusBindingModule:      "org.eclipse.sisu.plexus.PlexusBindingModule"
[ERROR] URLClassLoader:           "java.net.URLClassLoader"
[ERROR] WireModule:               "org.eclipse.sisu.wire.WireModule"
[ERROR] ========================
[ERROR] End of classname legend:
[ERROR] ========================
[ERROR] 
[ERROR]       role: org.apache.maven.plugin.Mojo
[ERROR]   roleHint: io.quarkus.platform:quarkus-maven-plugin:3.2.0.Final:generate-code
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[Pipeline] }
```

### Output of `java -version`

17

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.1, 3.9.2

**Comment by hntan** [comment]
This is my `quarkus-maven-plugin` config

```
<plugin>
                    <groupId>io.quarkus.platform</groupId>
                    <artifactId>quarkus-maven-plugin</artifactId>
                    <version>${quarkus.platform.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>build</goal>
                                <goal>generate-code</goal>
                                <goal>generate-code-tests</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <properties>
                            <project.version>${project.version}</project.version>
                            <git.commit.id.describe>${git.commit.id.describe}
                            </git.commit.id.describe>
                            <git.commit.id.abbrev>${git.commit.id.abbrev}</git.commit.id.abbrev>
                            <git.branch>${git.branch}</git.branch>
                            <git.commit.time>${git.commit.time}</git.commit.time>
                            <git.build.time>${git.build.time}</git.build.time>
                        </properties>
                    </configuration>
                </plugin>
```

**Comment by aloubyansky** [comment]
@hntan can you also reproduce it in your local environment or does it happen only in Jenkins?

**Comment by hntan** [comment]
Hi @aloubyansky , on Jenkins build only, more error is below.

```
Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.devtools.messagewriter.MessageWriter.warn(String, Object[])" because "this.log" is null
    at io.quarkus.analytics.AnonymousUserId.write (AnonymousUserId.java:73)
    at io.quarkus.analytics.AnonymousUserId.loadOrCreate (AnonymousUserId.java:49)
    at io.quarkus.analytics.AnonymousUserId.<init> (AnonymousUserId.java:32)
    at io.quarkus.analytics.AnonymousUserId.getInstance (AnonymousUserId.java:21)
    at io.quarkus.analytics.AnalyticsService.<init> (AnalyticsService.java:82)
    at io.quarkus.maven.BuildAnalyticsProvider.<init> (BuildAnalyticsProvider.java:37)
```

**Comment by aloubyansky** [comment]
Ah, thank you for that @hntan! @brunobat would you look into this please? Thanks.

**Comment by brunobat** [comment]
On it.
