### ISSUE TITLE
Failed to start quarkus with quarkus:dev becauProvider org.apache.camel.k.listener.ContextConfigurer not a subtypese of 

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#3474]
**Describe the bug**

```
2019-08-11 16:06:42,240 ERROR [io.qua.dev.DevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:94)
	at io.quarkus.runtime.Application.start(Application.java:84)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:127)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:171)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:89)
Caused by: java.util.ServiceConfigurationError: org.apache.camel.k.Runtime$Listener: Provider org.apache.camel.k.listener.ContextConfigurer not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at org.apache.camel.k.quarkus.ApplicationRuntime.starting(ApplicationRuntime.java:57)
	at org.apache.camel.k.quarkus.ApplicationRuntime_Observer_starting_3a6dd292952f4837fcdfde41adae09ecd30b3382.notify(ApplicationRuntime_Observer_starting_3a6dd292952f4837fcdfde41adae09ecd30b3382.zig:83)
	at io.quarkus.arc.EventImpl$Notifier.notify(EventImpl.java:228)
	at io.quarkus.arc.EventImpl.fire(EventImpl.java:69)
	at org.apache.camel.quarkus.core.runtime.support.FastCamelRuntime.fireEvent(FastCamelRuntime.java:182)
	at org.apache.camel.quarkus.core.runtime.support.FastCamelRuntime.doStart(FastCamelRuntime.java:125)
	at org.apache.camel.quarkus.core.runtime.support.FastCamelRuntime.start(FastCamelRuntime.java:74)
	at org.apache.camel.quarkus.core.runtime.CamelRecorder.start(CamelRecorder.java:78)
	at io.quarkus.deployment.steps.CamelInitProcessor$createRuntimeInitTask8.deploy_0(CamelInitProcessor$createRuntimeInitTask8.zig:92)
	at io.quarkus.deployment.steps.CamelInitProcessor$createRuntimeInitTask8.deploy(CamelInitProcessor$createRuntimeInitTask8.zig:36)
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:58)
	... 4 more

```

**To Reproduce**
1. clone https://github.com/lburgazzoli/apache-camel-k-runtime/tree/github-57
2. build the project
3. go to `camel-k-runtime-examples/camel-k-runtime-example-quarkus-yaml`
4. run `mvn clean compile quarkus:dev`

**Comment by mkouba** [comment]
If you using `mvn compile quarkus:dev` inside a multi-module maven project that also contains an extension you need to use `mvn compile quarkus:dev -DnoDeps` to exclude the local project dependencies from the dev mode. Otherwise, quarkus attempts to monitor the extension classes and this results in various classloading issues.

See https://github.com/quarkusio/quarkus/blob/master/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L137-L142.

**Comment by lburgazzoli** [comment]
@mkouba it fixes it thx

**Comment by mkouba** [comment]
FYI I've just sent a PR to mention this property in the extension guide.
