### ISSUE TITLE
Build Error introduced by 3.2.0 not extant in 2.16.x

### ISSUE THREAD

**Issue by tbkahuna48** [quarkusio/quarkus#34763]
### Describe the bug

Have a Service which uses a homegrown extension. This compiles and runs in 2.16.x. However, when the extensions and service are converted to 3.2.0 the compile produces the following error. There is no reference to which Producer it refers. We looked at every known producer both in the service and the extension code and all are tagged @ApplicationScoped.

### Expected behavior

Expected the compile to run withut error. 

### Actual behavior

Compiler produced this error:

```posh
[INFO] Reactor Summary for quarkus-mvp-async-parent 2.0.1-SNAPSHOT:
[INFO] 
[INFO] quarkus-mvp-async-parent ........................... SUCCESS [  0.065 s]
[INFO] quarkus-mvp-async .................................. FAILURE [  7.106 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.906 s
[INFO] Finished at: 2023-07-14T09:43:30-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.2.0.Final:build (default) on project quarkus-mvp-async: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Found 4 deployment problems: 
[ERROR] [1] Ambiguous dependencies for type jakarta.ws.rs.ext.Providers and qualifiers [@Default]
[ERROR] 	- java member: io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter():providers
[ERROR] 	- declared on CLASS bean [types=[jakarta.ws.rs.ext.MessageBodyWriter<java.lang.Object>, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyWriter$AllWriteableMessageBodyWriter, org.jboss.resteasy.reactive.common.types.AllWriteableMarker, io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyWriter<java.lang.Object>, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter]
[ERROR] 	- available beans:
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=org.jboss.resteasy.cdi.ContextProducers]
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=io.quarkus.resteasy.reactive.server.runtime.QuarkusContextProducers]
[ERROR] [2] Ambiguous dependencies for type jakarta.ws.rs.ext.Providers and qualifiers [@Default]
[ERROR] 	- java member: io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyReader():providers
[ERROR] 	- declared on CLASS bean [types=[io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyReader, org.jboss.resteasy.reactive.server.jackson.JacksonBasicMessageBodyReader, org.jboss.resteasy.reactive.common.providers.serialisers.AbstractJsonMessageBodyReader, jakarta.ws.rs.ext.MessageBodyReader<java.lang.Object>, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyReader<java.lang.Object>, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyReader]
[ERROR] 	- available beans:
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=org.jboss.resteasy.cdi.ContextProducers]
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=io.quarkus.resteasy.reactive.server.runtime.QuarkusContextProducers]
[ERROR] [3] Ambiguous dependencies for type jakarta.ws.rs.ext.Providers and qualifiers [@Default]
[ERROR] 	- java member: io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyReader#providers
[ERROR] 	- declared on CLASS bean [types=[jakarta.ws.rs.ext.MessageBodyReader<java.lang.Object>, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyReader<java.lang.Object>, java.lang.Object, io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyReader], qualifiers=[@Default, @Any], target=io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyReader]
[ERROR] 	- available beans:
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=org.jboss.resteasy.cdi.ContextProducers]
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=io.quarkus.resteasy.reactive.server.runtime.QuarkusContextProducers]
[ERROR] [4] Ambiguous dependencies for type jakarta.ws.rs.ext.Providers and qualifiers [@Default]
[ERROR] 	- java member: io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyWriter#providers
[ERROR] 	- declared on CLASS bean [types=[io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyWriter, jakarta.ws.rs.ext.MessageBodyWriter<java.lang.Object>, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyWriter$AllWriteableMessageBodyWriter, org.jboss.resteasy.reactive.common.types.AllWriteableMarker, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyWriter<java.lang.Object>, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyWriter]
[ERROR] 	- available beans:
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=org.jboss.resteasy.cdi.ContextProducers]
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=io.quarkus.resteasy.reactive.server.runtime.QuarkusContextProducers]
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1443)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:310)
[ERROR] 	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:155)
[ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:469)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] 	Suppressed: jakarta.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type jakarta.ws.rs.ext.Providers and qualifiers [@Default]
[ERROR] 	- java member: io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter():providers
[ERROR] 	- declared on CLASS bean [types=[jakarta.ws.rs.ext.MessageBodyWriter<java.lang.Object>, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyWriter$AllWriteableMessageBodyWriter, org.jboss.resteasy.reactive.common.types.AllWriteableMarker, io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyWriter<java.lang.Object>, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter]
[ERROR] 	- available beans:
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=org.jboss.resteasy.cdi.ContextProducers]
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=io.quarkus.resteasy.reactive.server.runtime.QuarkusContextProducers]
[ERROR] 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
[ERROR] 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:624)
[ERROR] 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:298)
[ERROR] 		... 13 more
[ERROR] 	Suppressed: jakarta.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type jakarta.ws.rs.ext.Providers and qualifiers [@Default]
[ERROR] 	- java member: io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyReader():providers
[ERROR] 	- declared on CLASS bean [types=[io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyReader, org.jboss.resteasy.reactive.server.jackson.JacksonBasicMessageBodyReader, org.jboss.resteasy.reactive.common.providers.serialisers.AbstractJsonMessageBodyReader, jakarta.ws.rs.ext.MessageBodyReader<java.lang.Object>, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyReader<java.lang.Object>, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyReader]
[ERROR] 	- available beans:
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=org.jboss.resteasy.cdi.ContextProducers]
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=io.quarkus.resteasy.reactive.server.runtime.QuarkusContextProducers]
[ERROR] 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
[ERROR] 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:624)
[ERROR] 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:298)
[ERROR] 		... 13 more
[ERROR] 	Suppressed: jakarta.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type jakarta.ws.rs.ext.Providers and qualifiers [@Default]
[ERROR] 	- java member: io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyReader#providers
[ERROR] 	- declared on CLASS bean [types=[jakarta.ws.rs.ext.MessageBodyReader<java.lang.Object>, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyReader<java.lang.Object>, java.lang.Object, io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyReader], qualifiers=[@Default, @Any], target=io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyReader]
[ERROR] 	- available beans:
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=org.jboss.resteasy.cdi.ContextProducers]
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=io.quarkus.resteasy.reactive.server.runtime.QuarkusContextProducers]
[ERROR] 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
[ERROR] 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:624)
[ERROR] 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:298)
[ERROR] 		... 13 more
[ERROR] 	Suppressed: jakarta.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type jakarta.ws.rs.ext.Providers and qualifiers [@Default]
[ERROR] 	- java member: io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyWriter#providers
[ERROR] 	- declared on CLASS bean [types=[io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyWriter, jakarta.ws.rs.ext.MessageBodyWriter<java.lang.Object>, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyWriter$AllWriteableMessageBodyWriter, org.jboss.resteasy.reactive.common.types.AllWriteableMarker, org.jboss.resteasy.reactive.server.spi.ServerMessageBodyWriter<java.lang.Object>, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.resteasy.reactive.jaxb.runtime.serialisers.ServerJaxbMessageBodyWriter]
[ERROR] 	- available beans:
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=org.jboss.resteasy.cdi.ContextProducers]
[ERROR] 		- PRODUCER METHOD bean [types=[java.lang.Object, jakarta.ws.rs.ext.Providers], qualifiers=[@Default, @Any], target=jakarta.ws.rs.ext.Providers providers(), declaringBean=io.quarkus.resteasy.reactive.server.runtime.QuarkusContextProducers]
[ERROR] 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:486)
[ERROR] 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:624)
[ERROR] 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:298)
[ERROR] 		... 13 more
```

### How to Reproduce?

Not sure how to provide all the code needed or if I am allowed to. Would have to get permission from Kaiser. 
Code is in internal github instance.

### Output of `uname -a` or `ver`

22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

java version "17.0.7" 2023-04-18 LTS Java(TM) SE Runtime Environment Oracle GraalVM 17.0.7+8.1 (build 17.0.7+8-LTS-jvmci-23.0-b12) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.7+8.1 (build 17.0.7+8-LTS-jvmci-23.0-b12, mixed mode, sharing)

### Quarkus version or git rev

3.2.0

**Comment by geoand** [comment]
We'll need a sample that produces the error you mention in 3.2 but works properly in 2.16

**Comment by geoand** [comment]
Closing for lack of feedback
