### ISSUE TITLE
Unable to connect via SSL to Redis Cache

### ISSUE THREAD

**Issue by JoaoBrandao** [quarkusio/quarkus#34761]
### Describe the bug

Hi,
I am trying to connect to a Redis Enterprise version but I am getting the following exception:  "Pool initialized with SSL but connection requested plain socket".

Configurations:
quarkus.redis.hosts=redis://abcabc.westeurope.redisenterprise.cache.abcba.net:10000
quarkus.redis.password=abcabc
quarkus.redis.tls.enabled=true
quarkus.redis.client-type=STANDALONE
(_Port is not wrong, I am not using the default_)

According to the documentation, enabling the third command with TLS as true should enable the SSL connection.
I was able to connect via third-party tools to this Redis cache database using the same configurations above.

**Exception**

`
java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: Pool initialized with SSL but connection requested plain socket
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:79)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
        at io.quarkus.redis.runtime.client.RedisClientImpl.await(RedisClientImpl.java:1052)
        at io.quarkus.redis.runtime.client.RedisClientImpl.del(RedisClientImpl.java:143)
        at io.quarkus.redis.client.RedisClient_6993bb0318fd2d6e0fbeb2a9742968fbb76620ee_Synthetic_ClientProxy.del(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeBlocking$11(AbstractMediator.java:166)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:36)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
        at io.vertx.mutiny.core.Context$1.handle(Context.java:170)
        at io.vertx.mutiny.core.Context$1.handle(Context.java:168)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.vertx.core.impl.NoStackTraceThrowable: Pool initialized with SSL but connection requested plain socket
`

### Expected behavior

By enabling the SSL, I was expecting a healthy connection to redis

### Actual behavior

Getting the exception: Caused by: io.vertx.core.impl.NoStackTraceThrowable: Pool initialized with SSL but connection requested plain socket

### Output of `java -version`

17.0.5

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.9.2

### Additional information

related topics: 
https://github.com/quarkusio/quarkus/issues/13161

By disabling the TLS on Redis side I was able to publish a new record to Redis but keep throwing exceptions after the operations has been completed.

**Comment by JoaoBrandao** [comment]
I was doing some tests using this example: **https://github.com/Azure-Samples/azure-cache-redis-samples/blob/main/quickstart/java/redistest/src/main/java/example/demo/App.java** and  I was able to connect to Redis and add a new record without changing any configurations on Redis server.

**Comment by cescoffier** [comment]
Did you try with rediss:// ?

**Comment by cescoffier** [comment]
The example you gave to not give the redis url.

**Comment by JoaoBrandao** [comment]
Thank you for your input. with rediss:// it worked without I always get the error message: " Pool initialized with SSL but connection requested plain socket".

@cescoffier  I would suggest adding this kind of information in Quarkus Redis page https://quarkus.io/guides/redis-reference, at least for me would help from the beginning :)

**Comment by machi1990** [comment]
> I would suggest adding this kind of information in Quarkus Redis page https://quarkus.io/guides/redis-reference, at least for me would help from the beginning 

@JoaoBrandao do you want to give it a stab?
