### ISSUE TITLE
[Rest Client Reactive] Failed to Deserialize JSON Array to Multi

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#34771]
### Describe the bug

Given the following RestClient.

```java
@Path("/posts")
@RegisterRestClient()
@RegisterProvider(PostResponseExceptionMapper.class)
public interface PostResourceClient {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    Multi<Post> getAllPosts(
            @QueryParam("q") String q,
            @QueryParam("offset") @DefaultValue("0") int offset,
            @QueryParam("limit") @DefaultValue("10") int limit
    );

}

```

And in the tests, I used WireMock to serve a JSON array to it.

```java
 @Test
    void getAllPosts() throws Throwable {
        var url = "/posts?q=&offset=0&limit=10";
        stubFor(
                get(url)
                        .withHeader("Accept", equalTo("application/json"))
                        .willReturn(
                                aResponse()
                                        .withStatus(200)
                                        .withHeader("Content-Type", "application/json")
                                        .withBody(
                                                """
                                                        [
                                                            {
                                                                "id":1,
                                                                "title":"test post 1",
                                                                "content":"test content of post 1",
                                                                "createdAt":"2023-03-26T10:15:30"
                                                            },
                                                            {
                                                                "id":2,
                                                                "title":"test post 2",
                                                                "content":"test content of post 2",s
                                                                "createdAt":"2023-03-26T10:15:30"
                                                            }
                                                        ]
                                                        """.trim()
                                        )
                        )
        );

        var postList = VertxContextSupport.subscribeAndAwait(() ->
                client.getAllPosts("", 0, 10)
                        .onItem().invoke(c -> LOGGER.log(Level.INFO, "post is: {0}", c))
                        .onFailure().invoke(error -> LOGGER.log(Level.INFO, "error: {0}", error.getMessage()))
                        .collect().asList()
        );

        assertThat(postList.size()).isEqualTo(2);

        verify(
                getRequestedFor(urlEqualTo(url))
                        .withHeader("Accept", equalTo("application/json"))
        );

    }

```

### Expected behavior

It should work.

### Actual behavior

```bash

2023-07-16 00:25:22,629 INFO  [com.exa.dem.PostResourceClientTest] (vert.x-eventloop-thread-2) error: HTTP 400 Bad Request

org.jboss.resteasy.reactive.ClientWebApplicationException: HTTP 400 Bad Request

	at io.quarkus.rest.client.reactive.jackson.runtime.serialisers.ClientJacksonMessageBodyReader.readFrom(ClientJacksonMessageBodyReader.java:59)
	at org.jboss.resteasy.reactive.client.impl.ClientReaderInterceptorContextImpl.proceed(ClientReaderInterceptorContextImpl.java:86)
	at org.jboss.resteasy.reactive.client.impl.ClientSerialisers.invokeClientReader(ClientSerialisers.java:160)
	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.readEntity(RestClientRequestContext.java:197)
	at org.jboss.resteasy.reactive.client.impl.MultiInvoker$1.handle(MultiInvoker.java:231)
	at org.jboss.resteasy.reactive.client.impl.MultiInvoker$1.handle(MultiInvoker.java:190)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.http.impl.HttpEventHandler.handleChunk(HttpEventHandler.java:51)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleChunk(HttpClientResponseImpl.java:239)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:452)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255)
	at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:242)
	at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:295)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `com.example.demo.Post` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (ByteArrayInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1526)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1473)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:656)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:211)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
	at io.quarkus.rest.client.reactive.jackson.runtime.serialisers.ClientJacksonMessageBodyReader.readFrom(ClientJacksonMessageBodyReader.java:53)
	... 23 more


```

### How to Reproduce?

1. clone https://github.com/hantsy/quarkus-sandbox/tree/master/restclient-reactive
2. Run `PostResourceClientTest`

### Output of `uname -a` or `ver`

Windows 10 Pro

### Output of `java -version`

17

### GraalVM version (if different from Java)

not used

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

**Comment by cescoffier** [comment]
It is expected as using Multi, in this case, is often erroneous. 
The reason is that your response is sent in one "batch" (content type is json), so having a multi does not make sense. The proper response type is a `Uni<List<X>>`.  You can then build a Multi, but not sure you need it. 

Note that it would be different if you would be streaming the array (there are a few json stream approaches).

**Comment by hantsy** [comment]
OK, a simple question, if I want to return `Mutlti` in the rest client interface directly, how to mock it instead of JSON array in WireMock?

I have used similar Mock for Kotlin Flow in real world projects, it worked well.

**Comment by cescoffier** [comment]
You need to send streams, like SSE, or json streams...

**Comment by cescoffier** [comment]
It's incorrect and dangerous, as, for most databases, you must keep the connection open and sometimes even with a transaction attached. 

It means you can stale your system quickly if you have slow consumers. Also, because DB connections are scarce resources, keeping them too long can reduce your concurrency. 

If you need DB steaming, use cursors. It keeps the connection open, but at least it's a conscious choice.

**Comment by cescoffier** [comment]
For single-response HTTP, it would add a control flow protocol for something already in memory. So, you are paying a price for something not really useful. 

For your specific case (a JSON array), we could imagine a Multi emitting each item individually. It would make the assumption that the server has actually written the array chunk by chunk, and the client reads the chunks one by one using some advanced JSON mapping to be able to do that. That's a lot of hypotheses, which make this use case very niche.

When you want to stream, use a proper streaming format (SSE, NDJson (`application/x-ndjson)`...)
