### ISSUE TITLE
OOM error in DevConsoleOidcNoDiscoverySmokeTest

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#34790]
### Describe the bug

I've noticed the following error in

https://github.com/quarkusio/quarkus/actions/runs/5574319191/jobs/10183572640?pr=34784

```
 Error:  Errors: 
Error:    DevConsoleOidcNoDiscoverySmokeTest.testOidcProviderTemplate » Runtime io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: ]: Build step io.quarkus.arc.deployment.ArcProcessor#buildCompatibleExtensions threw an exception: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.io.InputStream.readNBytes(InputStream.java:405)
	at java.base/java.io.InputStream.readAllBytes(InputStream.java:346)
```

**Comment by gsmet** [comment]
I think we can close this one, we haven't seen any related issue since a long time.
