### ISSUE TITLE
warning on transactional method after one hour and service didn't work

### ISSUE THREAD

**Issue by alinayebi9080** [quarkusio/quarkus#34843]
### Describe the bug

i migrated quarkus from 2.7.1 to 3.1.2. all of system worked perfectly for one hour **but** i got below warning on transactional method and service didn't work after one hour. what is problem? (this method worked in quarkus 2.7.1)  

```java
**my service code:**
    @Transactional
    public GenerateOtpResponse generateOtp(GenerateOtpRequest request) {

        Optional<Otp> optional = otpRepository.findNotExpiredOtpWithPessimisticWriteLock(
                request.getMobileNumber()
        );

       Otp otp = Otp.builder()
                .mobileNumber(request.getMobileNumber())
                .otp(codeGenerator.generateOtp(6))
                .expirationTime(calculateExpiredTime(otpUsage))
                .creationTime(new Date())
                .build();

       sendOtp(request.getMobileNumber(),newOtp)

        otpRepository.persistAndFlush(otp);
}

private void sendSms(String mobileNumber, String otp) {
   smsClient.sendSms(mobileNumber,otp)
}
```

```posh
-----------------------<<<*>>>-----------------------
[WARN] *** 2023-07-19 06:56:57,378 TID:  *** 
ARJUNA012117: TransactionReaper::check processing TX 0:ffffac120005:a39c:64b751e6:540 in state  RUN
-----------------------<<<*>>>-----------------------
[WARN] *** 2023-07-19 06:56:57,379 TID:  *** 
ARJUNA012095: Abort of action id 0:ffffac120005:a39c:64b751e6:540 invoked while multiple threads active within it.
-----------------------<<<*>>>-----------------------
[WARN] *** 2023-07-19 06:56:57,380 TID:  *** 
ARJUNA012381: Action id 0:ffffac120005:a39c:64b751e6:540 completed with multiple threads - thread executor-thread-6 was in progress with java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
java.base@17.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
java.base@17.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
java.base@17.0.7/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
java.base@17.0.7/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
java.base@17.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:391)
org.apache.http.pool.AbstractConnPool.access$300(AbstractConnPool.java:70)
org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:253)
org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:198)
org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:306)
org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:282)
org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:344)
org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:427)
org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:134)
org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:61)
jdk.proxy2/jdk.proxy2.$Proxy84.sendSms(Unknown Source)
jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:168)
jdk.proxy2/jdk.proxy2.$Proxy87.sendSms(Unknown Source)
...
io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
ir.co.isc.mss.authentication.app.controllers.AuthenticationOtpController_Subclass.generateOtpForActivation(Unknown Source)
ir.co.isc.mss.authentication.app.controllers.AuthenticationOtpController_ClientProxy.generateOtpForActivation(Unknown Source)
jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
org.jboss.resteasy.core.ResourceMethodInvoker$$Lambda$858/0x00000008018141c8.get(Unknown Source)
org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$856/0x0000000801810b40.run(Unknown Source)
org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$857/0x0000000801811450.get(Unknown Source)
org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
-----------------------<<<*>>>-----------------------
[WARN] *** 2023-07-19 06:56:57,380 TID:  *** 
ARJUNA012108: CheckedAction::check - atomic action 0:ffffac120005:a39c:64b751e6:540 aborting with 1 threads active!
-----------------------<<<*>>>-----------------------
[WARN] *** 2023-07-19 06:56:57,382 TID:  *** 
HHH000451: Transaction afterCompletion called by a background thread; delaying afterCompletion processing until the original thread can handle it. [status=4]
-----------------------<<<*>>>-----------------------
[WARN] *** 2023-07-19 06:56:57,382 TID:  *** 
ARJUNA012121: TransactionReaper::doCancellations worker Thread[Transaction Reaper Worker 0,5,main] successfully canceled TX 0:ffffac120005:a39c:64b751e6:540
-----------------------<<<*>>>-----------------------


 Caused by: jakarta.transaction.RollbackException: ARJUNA016102: The transaction is not active! Uid is 0:ffffac12000e:852b:64abece2:be8
         at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1285)
         at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
         at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
         at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
         at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
         at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
         at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
         at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
         at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
         at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
 
```

### Output of `java -version`

17

### Quarkus version or git rev

3.1.2

**Comment by mmusgrov** [comment]
The message `ARJUNA012095: Abort of action id 0:ffffac120005:a39c:64b751e6:540 invoked while multiple threads active within it.` means that the the transaction was rolled back but there is still an application thread running with that transaction bound to the application thread, my guess is that the transaction timed out. The first thing to investigate is why is the application thread is stalling?
