### ISSUE TITLE
Under load Panache Reactive exception "Detected use of the reactive session from a different Thread..."

### ISSUE THREAD

**Issue by AlekseyMay** [quarkusio/quarkus#34848]
### Describe the bug

I have application that uses Panache Reactive. There are several layers of services with @WithSession\@WithTransaction on methods. All is ok, until the app sometimes switches to eventloop thread 1 under load. I don't know if it is my mistake or the expected behavior.

```
	09:30:29.173 [vert.x-eventloop-thread-1] ERROR com.example.helper.utils.interceptor.faillog.OnFailLogInterceptor - java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread [28]: 'vert.x-eventloop-thread-1' current Thread [20]: 'vert.x-eventloop-thread-0' {}
org.hibernate.HibernateException: java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread [28]: 'vert.x-eventloop-thread-1' current Thread [20]: 'vert.x-eventloop-thread-0'
	at org.hibernate.reactive.session.impl.ReactiveExceptionConverter.convert(ReactiveExceptionConverter.java:28) ~[org.hibernate.reactive.hibernate-reactive-core-2.0.1.Final.jar:2.0.1.Final]
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.lambda$doFlush$28(ReactiveSessionImpl.java:1101) ~[org.hibernate.reactive.hibernate-reactive-core-2.0.1.Final.jar:2.0.1.Final]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.unroll(AsyncTrampoline.java:131) ~[org.hibernate.reactive.hibernate-reactive-core-2.0.1.Final.jar:2.0.1.Final]
	at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.lambda$unroll$0(AsyncTrampoline.java:126) ~[org.hibernate.reactive.hibernate-reactive-core-2.0.1.Final.jar:2.0.1.Final]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at org.hibernate.reactive.persister.entity.mutation.ReactiveUpdateCoordinatorStandard.complete(ReactiveUpdateCoordinatorStandard.java:52) ~[org.hibernate.reactive.hibernate-reactive-core-2.0.1.Final.jar:2.0.1.Final]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:536) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:88) ~[io.vertx.vertx-sql-client-4.4.4.jar:4.4.4]
	at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:32) ~[io.vertx.vertx-sql-client-4.4.4.jar:4.4.4]
	at io.vertx.core.Promise.complete(Promise.java:66) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.Promise.handle(Promise.java:51) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.Promise.handle(Promise.java:29) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72) ~[io.vertx.vertx-sql-client-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Transformation$1.onSuccess(Transformation.java:63) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:44) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:86) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.sqlclient.impl.command.CommandResponse.fire(CommandResponse.java:46) ~[io.vertx.vertx-sql-client-4.4.4.jar:4.4.4]
	at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:325) ~[io.vertx.vertx-sql-client-4.4.4.jar:4.4.4]
	at io.vertx.pgclient.impl.PgSocketConnection.handleMessage(PgSocketConnection.java:118) ~[io.vertx.vertx-pg-client-4.4.4.jar:4.4.4]
	at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:138) ~[io.vertx.vertx-sql-client-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:378) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:158) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153) ~[io.vertx.vertx-core-4.4.4.jar:4.4.4]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:100) ~[io.vertx.vertx-pg-client-4.4.4.jar:4.4.4]
	at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:139) [io.vertx.vertx-pg-client-4.4.4.jar:4.4.4]
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:237) [io.vertx.vertx-pg-client-4.4.4.jar:4.4.4]
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:96) [io.vertx.vertx-pg-client-4.4.4.jar:4.4.4]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [io.netty.netty-transport-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [io.netty.netty-common-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.94.Final.jar:4.1.94.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.94.Final.jar:4.1.94.Final]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread [28]: 'vert.x-eventloop-thread-1' current Thread [20]: 'vert.x-eventloop-thread-0'
	at org.hibernate.reactive.common.InternalStateAssertions.assertCurrentThreadMatches(InternalStateAssertions.java:46) ~[org.hibernate.reactive.hibernate-reactive-core-2.0.1.Final.jar:2.0.1.Final]
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.threadCheck(ReactiveSessionImpl.java:195) ~[org.hibernate.reactive.hibernate-reactive-core-2.0.1.Final.jar:2.0.1.Final]
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.checkOpen(ReactiveSessionImpl.java:1777) ~[org.hibernate.reactive.hibernate-reactive-core-2.0.1.Final.jar:2.0.1.Final]
	at org.hibernate.internal.AbstractSharedSessionContract.checkOpenOrWaitingForAutoClose(AbstractSharedSessionContract.java:447) ~[org.hibernate.orm.hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.internal.SessionImpl.checkOpenOrWaitingForAutoClose(SessionImpl.java:616) ~[org.hibernate.orm.hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.internal.SessionImpl.getPersistenceContext(SessionImpl.java:1825) ~[org.hibernate.orm.hibernate-core-6.2.5.Final.jar:6.2.5.Final]
	at org.hibernate.reactive.event.impl.AbstractReactiveFlushingEventListener.lambda$performExecutions$0(AbstractReactiveFlushingEventListener.java:65) ~[org.hibernate.reactive.hibernate-reactive-core-2.0.1.Final.jar:2.0.1.Final]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	... 81 more

```

### Expected behavior

No exception

### Actual behavior

Exception

### Output of `java -version`

17

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.1.1

**Comment by geoand** [comment]
cc @DavideD

**Comment by FroMage** [comment]
Could you give us a reproducer project? This is going to be impossible to find without a reproducer, I'm afraid.

**Comment by DavideD** [comment]
Waiting for a reproducer, this error is too generic and without one there's not much the we can do.

**Comment by geoand** [comment]
Closing for a lack of a reproducer. If one does become available, feel free to comment or reopen
