### ISSUE TITLE
Treat incorrect Accept header as a user error

### ISSUE THREAD

**Issue by patrox** [quarkusio/quarkus#34858]
### Description

Hey,

while doing some security tests, we found out that if we sent a fake `Accept` header to a Quarkus-based service, it would respond with an internal server error, i.e.:

```
http localhost:8080/hello Accept:blah
```

```
HTTP/1.1 500 Internal Server Error
content-length: 3252
content-type: application/json; charset=utf-8

{
    "details": "Error id 2425a57c-4865-4301-bca4-e99ed554f884-1, java.lang.IllegalArgumentException: Failed to parse media type blah",
    "stack": "java.lang.IllegalArgumentException: Failed to parse media type blah
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.internalParse(MediaTypeHeaderDelegate.java:77)
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.parse(MediaTypeHeaderDelegate.java:53)
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:125)
	at org.jboss.resteasy.reactive.common.headers.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:15)
	at jakarta.ws.rs.core.MediaType.valueOf(MediaType.java:172)
	at org.jboss.resteasy.reactive.server.handlers.ClassRoutingHandler.acceptHeaderMatches(ClassRoutingHandler.java:160)
	at org.jboss.resteasy.reactive.server.handlers.ClassRoutingHandler.handle(ClassRoutingHandler.java:130)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:123)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:102)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:88)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:290)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)"
}
```

This behavior was observed on:

- Quarkus 3.2.0
- Quarkus 2.16.6

So, we ended up adding a dedicated exception mapper, which will map this exception to a 400 (`BAD_REQUEST`) status code. After having some seconds thoughts, we are considering returning a more specific status code, i.e. `406 Not Acceptable`, but the point is that we didn't want to treat it as an internal server error, as it's purely related to a user action.

I was wondering what's your opinion in this case. Do you think it's OK to add such exception mapping to quarkus itself, so in such case it will be mapped to an HTTP status code from 4xx family?

Alternatively, if the `Accept` header value cannot be parsed it could be ignored, and the content type negotiation could default to a type which is offered by server.

If you are OK with changing this behavior, I'll be happy to address it, so we don't need to add exception mappers for this specific case in our services :)

**Comment by geoand** [comment]
This makes perfect sense! #34874 fixes the issue
