### ISSUE TITLE
hibernate schema update for Oracledb is broken

### ISSUE THREAD

**Issue by Manny404** [quarkusio/quarkus#34887]
### Describe the bug

I have an entity with a String field with @Lob   which is created as a clob. On the first run this is working fine, but on the second start of quarkus, hibernate trys to update die column from clob to clob, which the oracle db doesn't like.

quarkus.hibernate-orm.database.generation=update

With quarkus.hibernate-orm.database.generation=validate   hibernate does not complain.

With the old quarkus 2.13.1 Version it works also fine. I can check the latest 2.x version if required.

2023-07-20 13:59:12,045 WARN  [org.hib.too.sch.int.ExceptionHandlerLoggedImpl] (JPA Startup Thread) GenerationTarget encountered exception accepting command : Error e
xecuting DDL "alter table MyEntity modify text clob" via JDBC [ORA-22859: Ungültige Änderung von Spalten
]: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "alter table MyEntity modify text clob" via JDBC [ORA-22859: Ungültige Änderung von S
palten
]
        at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:92)
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlString(AbstractSchemaMigrator.java:574)
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlStrings(AbstractSchemaMigrator.java:514)
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.migrateTable(AbstractSchemaMigrator.java:333)
        at org.hibernate.tool.schema.internal.GroupedSchemaMigratorImpl.performTablesMigration(GroupedSchemaMigratorImpl.java:84)
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.performMigration(AbstractSchemaMigrator.java:232)
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:117)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:284)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:143)
        at java.base/java.util.HashMap.forEach(HashMap.java:1336)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:140)
        at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)      
        at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:292)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:156)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: ORA-22859: Ungültige Änderung von Spalten

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:702)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:608)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1335)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1041)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:443)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:533)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:176)
        at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1305)
        at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1877)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1520)
        at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:2557)
        at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:2506)
        at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:334)
        at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:235)
        at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:78)
        ... 20 more
Caused by: Error : 22859, Position : 28, SQL = alter table MyEntity modify text clob, Original SQL = alter table MyEntity modify text clob, Error Message = ORA-22859:
 Ungültige Änderung von Spalten

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:710)
        ... 34 more

### Expected behavior

Start of the application with no error. 

### Actual behavior

A Exception ist thrown

### How to Reproduce?

Create a application with oracle driver and hibernate+ panache. Add a String field with @Lob + set quarkus.hibernate-orm.database.generation=update  and run the application twice.

Or use the reproducer project below. I have removed the db credentials

[reproducer.zip](https://github.com/quarkusio/quarkus/files/12106524/reproducer.zip)

### Output of `java -version`

11

### Quarkus version or git rev

3.2.1

### Additional information

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.17.0.0.0

**Comment by marko-bekhta** [comment]
Hey @Manny404 
Thanks for reporting this. It is actually an already reported Hibernate ORM issue - -https://hibernate.atlassian.net/browse/HHH-16762

**Comment by yrodiere** [comment]
Thanks for reporting. I've notified the Hibernate ORM team that Quarkus is affected.

Let's close this as this is purely a Hibernate ORM issue: it'll be fixed in Quarkus when we upgrade to a version of Hibernate ORM that fixes the issue. Please use https://hibernate.atlassian.net/browse/HHH-16762 to track progress.
