### ISSUE TITLE
Introduce new configuration to disable oidc discovery at startup

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#34890]
### Description

I am using `quarkus-oidc` with Keycloak as OIDC provider, and I am creating a new realm (`myrealm`) at application startup (for non-production environments only):

```
void onStartUp(@Observes StartupEvent event) {
    if(LaunchMode.current().isDevOrTest()) {
        // generate realm configuration at runtime then use Keycloak Admin API to create the new realm
        RealmRepresentation realm = generateNewRealm();
        realm.setRealm("myrealm");
        keycloak.realms().create(realm);
    }
}
```

Given these configs:

```
quarkus.oidc.discovery-enabled=true
quarkus.keycloak.devservices.realm-name=myrealm
quarkus.keycloak.devservices.create-realm=false
```

I got this exception:

```
2023-07-20 17:12:22,909 [] WARN  [io.qua.oid.com.run.OidcCommonUtils] (vert.x-eventloop-thread-1) OIDC Server is not available:: io.quarkus.oidc.common.runtime.OidcEndpointAccessException
	at io.quarkus.oidc.common.runtime.OidcCommonUtils.lambda$discoverMetadata$2(OidcCommonUtils.java:425)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
	at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
	at io.smallrye.mutiny.vertx.DelegatingHandler.handle(DelegatingHandler.java:25)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:397)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:384)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:362)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:329)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:291)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$7(HttpContext.java:507)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
2023-07-20 17:12:22,910 [] WARN  [io.qua.oid.run.OidcRecorder] (vert.x-eventloop-thread-1) OIDC server is not available at the 'http://localhost:9090/realms/myrealm' URL. Please make sure it is correct. Note it has to end with a realm value if you work with Keycloak, for example: 'https://localhost:8180/auth/realms/quarkus'
2023-07-20 17:12:22,910 [] WARN  [io.qua.oid.run.OidcRecorder] (vert.x-eventloop-thread-1) Tenant 'Default': 'OIDC Server is not available'. OIDC server is not available yet, an attempt to connect will be made during the first request. Access to resources protected by this tenant may fail if OIDC server will not become available
```

This happens because `myrealm` is not available yet, as `OidcRecorder` is executed before `onStartUp()`.

Although the application continues to run normally, but It's nice to not have this exception on every application startup :)

### Implementation ideas

Introduce new configuration `quarkus.oidc.discovery-at-startup` which can be `true` by default. If set to `false`, the discovery will be made during the first request anyway.

**Comment by sberyozkin** [comment]
@Eng-Fouad This is what is happening in any case, you have the discovery completed at the first request, if it did not work at the start up. I guess this exception can be reported at the debug level.

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad This is what is happening in any case, you have the discovery completed at the first request, if it did not work at the start up. I guess this exception can be reported at the debug level.

Changing the log level of this exception to debug level resolves the issue for me.

**Comment by Eng-Fouad** [comment]
As a workaround, I am using:

> %dev.quarkus.log.category."io.quarkus.oidc.common.runtime.OidcCommonUtils".level=ERROR
