### ISSUE TITLE
SRMSG18010: Unable to create an instance of `io.vertx.kafka.client.serialization.JsonObjectDeserializer`

### ISSUE THREAD

**Issue by gpaolopedrazza** [quarkusio/quarkus#34911]
### Describe the bug

Hi, I am trying to build a native image using maven and GraalVM, but I'm running into a java.lang.ClassNotFoundException for io.vertx.kafka.client.serialization.JsonObjectDeserializer.  When I try to run the jar, I have no problem. 

I tried to create a reflection-config.json file with io.vertx.kafka.client.serialization.JsonObjectDeserializer, the file was processed by native-image.cmd without any error message, but it still does not work. 

I am using following version on Windows:
C:\source\innbit\backend\services\sensor\target>java --version
java 20.0.2 2023-07-18
Java(TM) SE Runtime Environment Oracle GraalVM 20.0.2+9.1 (build 20.0.2+9-jvmci-23.0-b14)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 20.0.2+9.1 (build 20.0.2+9-jvmci-23.0-b14, mixed mode, sharing)

I also tried with compiling graalvm-jdk-20_linux-x64_bin.tar.gz on a Linux docker, but same result.
Since Quarkus and Vertx are frequently used in combination, I believe there could be a way to make this working, but in doubt I raise a bug ticket.

### Expected behavior

The quarkus native executable can be started

### Actual behavior

__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-07-21 11:59:30,853 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18229: Configured topics for channel 'imports-xml-consumer': [import.importsxml]
2023-07-21 11:59:30,855 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18213: Setting bootstrap.servers to localhost:9092
2023-07-21 11:59:30,855 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18214: Key deserializer omitted, using String as default
2023-07-21 11:59:30,856 DEBUG [io.sma.rea.mes.kafka] (main) SRMSG18234: Auto-commit disabled for channel imports-xml-consumer
2023-07-21 11:59:30,861 DEBUG [io.sma.rea.mes.kafka] (main) SRMSG18240: 'throttled' commit strategy used for channel 'imports-xml-consumer'
2023-07-21 11:59:30,862 DEBUG [io.sma.rea.mes.kafka] (main) SRMSG18232: Will commit for group 'service-sensor_imports-xml-consumer' every 5000 milliseconds.
2023-07-21 11:59:30,862 DEBUG [io.sma.rea.mes.kafka] (main) SRMSG18236: Will mark throttled commit strategy for group 'service-sensor_imports-xml-consumer' as unhealthy if records go more than 60000 milliseconds without being processed.
2023-07-21 11:59:30,863 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18229: Configured topics for channel 'sensorarea-consumer': [sensor.sensorarea]
2023-07-21 11:59:30,863 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18213: Setting bootstrap.servers to localhost:9092
2023-07-21 11:59:30,863 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18214: Key deserializer omitted, using String as default
2023-07-21 11:59:30,863 DEBUG [io.sma.rea.mes.kafka] (main) SRMSG18234: Auto-commit disabled for channel sensorarea-consumer
2023-07-21 11:59:30,863 ERROR [io.sma.rea.mes.provider] (main) SRMSG00230: Unable to create the publisher or subscriber during initialization: java.lang.IllegalArgumentException: SRMSG18010: Unable to create an instance of `io.vertx.kafka.client.serialization.JsonObjectDeserializer`
        at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.createDelegateDeserializer(DeserializerWrapper.java:64)
        at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.<init>(DeserializerWrapper.java:35)
        at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.<init>(ReactiveKafkaConsumer.java:102)
        at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.<init>(ReactiveKafkaConsumer.java:67)
        at io.smallrye.reactive.messaging.kafka.impl.KafkaSource.<init>(KafkaSource.java:110)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector.getPublisher(KafkaConnector.java:211)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector_Subclass.getPublisher$$superforward(Unknown Source)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector_Subclass$$function$$9.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.smallrye.reactivemessaging.runtime.DuplicatedContextConnectorFactoryInterceptor.intercept(DuplicatedContextConnectorFactoryInterceptor.java:32)
        at io.quarkus.smallrye.reactivemessaging.runtime.DuplicatedContextConnectorFactoryInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector_Subclass.getPublisher(Unknown Source)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getPublisher(Unknown Source)
        at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.createPublisher(ConfiguredChannelFactory.java:172)
        at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:134)
        at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:106)
        at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory_ClientProxy.initialize(Unknown Source)
        at java.base@20.0.2/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base@20.0.2/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
        at java.base@20.0.2/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at io.smallrye.reactive.messaging.providers.extension.MediatorManager.start(MediatorManager.java:212)
        at io.smallrye.reactive.messaging.providers.extension.MediatorManager_ClientProxy.start(Unknown Source)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:52)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_68e7b57eb97cb75d597c5b816682366e888d0d9b.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: io.vertx.kafka.client.serialization.JsonObjectDeserializer
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:123)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:87)
        at java.base@20.0.2/java.lang.Class.forName(DynamicHub.java:1322)
        at java.base@20.0.2/java.lang.Class.forName(DynamicHub.java:1311)
        at org.apache.kafka.common.utils.Utils.loadClass(Utils.java:422)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:411)
        at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.createDelegateDeserializer(DeserializerWrapper.java:62)
        ... 41 more

2023-07-21 11:59:30,870 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: jakarta.enterprise.inject.spi.DeploymentException: java.lang.IllegalArgumentException: SRMSG18010: Unable to create an instance of `io.vertx.kafka.client.serialization.JsonObjectDeserializer`
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:57)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_68e7b57eb97cb75d597c5b816682366e888d0d9b.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: SRMSG18010: Unable to create an instance of `io.vertx.kafka.client.serialization.JsonObjectDeserializer`
        at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.createDelegateDeserializer(DeserializerWrapper.java:64)
        at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.<init>(DeserializerWrapper.java:35)
        at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.<init>(ReactiveKafkaConsumer.java:102)
        at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.<init>(ReactiveKafkaConsumer.java:67)
        at io.smallrye.reactive.messaging.kafka.impl.KafkaSource.<init>(KafkaSource.java:110)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector.getPublisher(KafkaConnector.java:211)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector_Subclass.getPublisher$$superforward(Unknown Source)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector_Subclass$$function$$9.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.smallrye.reactivemessaging.runtime.DuplicatedContextConnectorFactoryInterceptor.intercept(DuplicatedContextConnectorFactoryInterceptor.java:32)
        at io.quarkus.smallrye.reactivemessaging.runtime.DuplicatedContextConnectorFactoryInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector_Subclass.getPublisher(Unknown Source)
        at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getPublisher(Unknown Source)
        at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.createPublisher(ConfiguredChannelFactory.java:172)
        at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:134)
        at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:106)
        at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory_ClientProxy.initialize(Unknown Source)
        at java.base@20.0.2/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base@20.0.2/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
        at java.base@20.0.2/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at io.smallrye.reactive.messaging.providers.extension.MediatorManager.start(MediatorManager.java:212)
        at io.smallrye.reactive.messaging.providers.extension.MediatorManager_ClientProxy.start(Unknown Source)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:52)
        ... 15 more
Caused by: java.lang.ClassNotFoundException: io.vertx.kafka.client.serialization.JsonObjectDeserializer
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:123)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:87)
        at java.base@20.0.2/java.lang.Class.forName(DynamicHub.java:1322)
        at java.base@20.0.2/java.lang.Class.forName(DynamicHub.java:1311)
        at org.apache.kafka.common.utils.Utils.loadClass(Utils.java:422)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:411)
        at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.createDelegateDeserializer(DeserializerWrapper.java:62)
        ... 41 more

### How to Reproduce?

Relevant part of my pom.xml

<quarkus-plugin.version>3.2.0.Final</quarkus-plugin.version>
<vertx.version>4.4.4</vertx.version>
   <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-vertx</artifactId>
    </dependency>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-kafka-client</artifactId>
      <version>${vertx.version}</version>
    </dependency>

 mvnw -Pnative clean package

### Output of `java -version`

 java 20.0.2 2023-07-18 Java(TM) SE Runtime Environment Oracle GraalVM 20.0.2+9.1 (build 20.0.2+9-jvmci-23.0-b14) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 20.0.2+9.1 (build 20.0.2+9-jvmci-23.0-b14, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 mvnw -Pnative clean package

**Comment by ozangunalp** [comment]
The `JsonObjectDeserializer` is now provided by the Quarkus kafka-client extension itself. The fully qualified name is `io.quarkus.kafka.client.serialization.JsonObjectDeserializer`.

**Comment by gpaolopedrazza** [comment]
First of all, thank you for your quick answer. Should I just replace vertx-kafka-client with quarkus-kafka-client in my pom.xml? Is there anything else I should modify or is quarkus supposed to just use io.quarkus.kafka.client instead of vertx without any configuration changes (like adding something to the properties file)?

**Comment by ozangunalp** [comment]
From the stack trace it seems like you are already using the `quarkus-smallrye-reactive-messaging-kafka` extension. It already pulls `quarkus-kafka-client`. 
If you have a config explicitly setting `io.vertx.kafka.client.serialization.JsonObjectDeserializer` deserializer, then yes you need to change that to `io.quarkus.kafka.client.serialization.JsonObjectDeserializer`

**Comment by gpaolopedrazza** [comment]
I am updating a quarkus project developed a long time ago and the reason why I originally installed io.vertx.kafka.client was a stack trace reporting that package could not be found.  If I do not need to explicitly force quarkus-smallrye-reactive-messaging-kafka to use io.quarkus.kafka.client.serialization.JsonObjectDeserializer, then there must be somewhere a config explicitly setting io.vertx.kafka.client.serialization.JsonObjectDeserializer that I am overlooking.

**Comment by ozangunalp** [comment]
If a reactive messaging channel consumes `JsonObject` and you haven't configured a deserializer for that channel, the serde auto-detection will pick `io.quarkus.kafka.client.serialization.JsonObjectDeserializer`, I believe this is the case since Quarkus 3.0.0.

**Comment by geoand** [comment]
@ozangunalp should this be closed? It doesn't seem like a bug, correct?

**Comment by geoand** [comment]
Or maybe converted to a discussion?

**Comment by ozangunalp** [comment]
Sure let's convert this to discussion
