### ISSUE TITLE
Quarkus 3.2.1.Final not working properly with DynamoEnhancedClient & @InjectMock (mockk)

### ISSUE THREAD

**Issue by DudekJakub** [quarkusio/quarkus#34924]
### Describe the bug

Hi.

After update to 3.2.1 v. I faced weird behavior related to `DynamoDbEnhancedAsyncClient` and `@InjectMock` (from mockk). 

Within this report I provided link to github project for easier issue reproduction. 

Project is split into 3 branches:
 - `3.2.0_OK`  -> here everything works as expected
 - `3.2.1_ERROR` -> here exactly the same code as in above OK branch doesn't work anymore
 - `3.2.1_ERROR_with_@DefaultBean` -> here code from above ERROR branch has been updated with `@DefaultBean` annotation what solved one problem with `DynamoDbEnhancedAsyncClient` but led to another one with `@InjectMock` for Clock bean. 
 
 More details in 'Expected behavior' & 'Actual behavior'

### Expected behavior

Check branch: `3.2.0_OK`

In nutshell: 
- Inside _GreetingResource_ class I expect 'dynamoClient' to be injected w/o any issues as it is registered in _Config_ class properly
- Inside _GreetingResourceTest_ class I expect 'clock' to be injected with @InjectMock (mockk) as it has been with 3.2.0 v. where it worked properly

### Actual behavior

Check branch: `3.2.1_ERROR`

Code is the same as in `3.2.0_OK` branch but now 'dynamoClient' cannot be injected as **"Unsatisfied dependency: no bean matches the injection point"** appears.

**stacktrace**:

> java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedAsyncClient and qualifiers [@Default]
	- java member: org.acme.GreetingResource():dynamoClient
	- declared on CLASS bean [types=[org.acme.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.GreetingResource]
	- available beans:
		- PRODUCER METHOD bean [types=[software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedAsyncClient, software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedResource, java.lang.Object], qualifiers=[@Default, @Any], target=software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedAsyncClient enhancedClient(software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient client, java.time.Clock clock), declaringBean=org.acme.Config]
		- SYNTHETIC bean [types=[software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedAsyncClient, java.lang.Object], qualifiers=[@Default, @Any], target=n/a]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1435)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:310)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:155)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:469)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
	
----------------

Check branch: `3.2.1_ERROR_with_@DefaultBean`

The only change here is `@DefaultBean` added for enhancedClient method inside _Config_ class. With it there is no more issue with **"Unsatisfied dependency: [...]"** but now clock inside _GreetingResourceTest_ class cannot be properly injected (with mockk).

**stacktrace**:

> Failed to create test instance
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:786)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:752)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.IllegalStateException: Invalid use of io.quarkiverse.test.junit.mockk.InjectMock - could not determine bean of type: class java.time.Clock. Offending field is clock of test class class org.acme.GreetingResourceTest
	

### How to Reproduce?

https://github.com/DudekJakub/Quarkus_DynamoDB_demo/tree/3.2.0_OK

3 branches listed in **"Describe the bug"** section. 
For each please run the only test inside _GreetingResourceTest_. 

### Output of `java -version`

JVM:  17.0.7 (Amazon.com Inc. 17.0.7+7-LTS)

### Quarkus version or git rev

3.2.1_FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by geoand** [comment]
cc @mkouba

**Comment by adampoplawski** [comment]
@mkouba @geoand I have check on version 3.2.2 and issue is the same.

**Comment by geoand** [comment]
Thanks for checking

**Comment by mkouba** [comment]
Shouldn't this issue be moved into https://github.com/quarkiverse/quarkus-mockk instead?

**Comment by mkouba** [comment]
In any case, the synthetic bean for `DynamoDbEnhancedAsyncClient` got introduced in this commit: https://github.com/quarkiverse/quarkus-amazon-services/commit/e973ced1038c0c95ac44e3e58e03c995127aa5bb last month (quarkus-amazon-dynamodb-enhanced 2.4.0). And this version is used since `io.quarkus.platform:quarkus-amazon-services-bom:3.2.1`.

**Comment by adampoplawski** [comment]
@mkouba so second part (mockk) can be moved. But different bean discovery after patch update for DynamoDbEnhancedAsyncClient is expected and @DefaultBean should be used to pick corrrect one?

**Comment by mkouba** [comment]
>  But different bean discovery after patch update for DynamoDbEnhancedAsyncClient is expected and @DefaultBean should be used to pick corrrect one?

The discovery itself is the same but the `quarkus-amazon-dynamodb-enhanced` extension added a new bean in 2.4.x. The question is whether the switch from 2.3.x to 2.4.x in a maintenance release (3.2.1.Final) is reasonable :shrug:. That's more of a question for the maintainers of the [quarkus-amazon-services](https://github.com/quarkiverse/quarkus-amazon-services) though.

**Comment by adampoplawski** [comment]
@geoand  @mkouba thx for your support. We will prepare 2 separate tasks, one for Mockk extension and one for quarkus-amazon-services in dedicated github repos and share a link.

**Comment by scrocquesel** [comment]
> In any case, the synthetic bean for `DynamoDbEnhancedAsyncClient` got introduced in this commit: [quarkiverse/quarkus-amazon-services@e973ced](https://github.com/quarkiverse/quarkus-amazon-services/commit/e973ced1038c0c95ac44e3e58e03c995127aa5bb) last month (quarkus-amazon-dynamodb-enhanced 2.4.0). And this version is used since `io.quarkus.platform:quarkus-amazon-services-bom:3.2.1`.
> 
> This explains the error in the `3.2.1_ERROR` branch.

@mkouba could you explain why it worked when the extension provide the bean with a `@DefaultBean` producer and it doesn't work when providing it with a synthetic bean ? Is there anything to add to the `SyntheticBeanBuildItem` to make it behave the same ?

**Comment by mkouba** [comment]
> > In any case, the synthetic bean for `DynamoDbEnhancedAsyncClient` got introduced in this commit: [quarkiverse/quarkus-amazon-services@e973ced](https://github.com/quarkiverse/quarkus-amazon-services/commit/e973ced1038c0c95ac44e3e58e03c995127aa5bb) last month (quarkus-amazon-dynamodb-enhanced 2.4.0). And this version is used since `io.quarkus.platform:quarkus-amazon-services-bom:3.2.1`.
> > This explains the error in the `3.2.1_ERROR` branch.
> 
> @mkouba could you explain why it worked when the extension provide the bean with a `@DefaultBean` producer and it doesn't work when providing it with a synthetic bean ? Is there anything to add to the `SyntheticBeanBuildItem` to make it behave the same ?

A synthetic bean is not marked as default by default. You need to use `BeanConfiguratorBase.defaultBean()`, i.e.:
```java
syntheticBean.produce(SyntheticBeanBuildItem
                        .configure(DynamoDbEnhancedAsyncClient.class)
                        .scope(ApplicationScoped.class)
                        .setRuntimeInit()
                        .createWith(recorder.createDynamoDbEnhancedAsyncClient(extensions))
                        .addInjectionPoint(ClassType.create(DynamoDbAsyncClient.class))
                        .defaultBean()
                        .done());
```

**Comment by scrocquesel** [comment]
> > > In any case, the synthetic bean for `DynamoDbEnhancedAsyncClient` got introduced in this commit: [quarkiverse/quarkus-amazon-services@e973ced](https://github.com/quarkiverse/quarkus-amazon-services/commit/e973ced1038c0c95ac44e3e58e03c995127aa5bb) last month (quarkus-amazon-dynamodb-enhanced 2.4.0). And this version is used since `io.quarkus.platform:quarkus-amazon-services-bom:3.2.1`.
> > > This explains the error in the `3.2.1_ERROR` branch.
> > 
> > 
> > @mkouba could you explain why it worked when the extension provide the bean with a `@DefaultBean` producer and it doesn't work when providing it with a synthetic bean ? Is there anything to add to the `SyntheticBeanBuildItem` to make it behave the same ?
> 
> A synthetic bean is not marked as default by default. You need to use `BeanConfiguratorBase.defaultBean()`, i.e.:
> 
> ```java
> syntheticBean.produce(SyntheticBeanBuildItem
>                         .configure(DynamoDbEnhancedAsyncClient.class)
>                         .scope(ApplicationScoped.class)
>                         .setRuntimeInit()
>                         .createWith(recorder.createDynamoDbEnhancedAsyncClient(extensions))
>                         .addInjectionPoint(ClassType.create(DynamoDbAsyncClient.class))
>                         .defaultBean()
>                         .done());
> ```

Thanks, I was confused by the default qualifier. I pushed a new release to quarkus platform for the next increment.

**Comment by adampoplawski** [comment]
@mkouba @geoand @scrocquesel all is working since quarkus 3.2.4
