### ISSUE TITLE
Hot reloading fails with "Thread has been blocked for 61797 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked"

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#34943]
### Describe the bug

I'm using Quarkus reactive in my project, and hot reloading fails all the time telling me the thread is blocked so I have to manually restart the application.

```
2023-07-24 09:00:55,873 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[#128,vert.x-worker-thread-1,5,main] has been blocked for 61797 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked
        at java.base/java.lang.Object.wait0(Native Method)
        at java.base/java.lang.Object.wait(Object.java:366)
        at java.base/java.lang.Object.wait(Object.java:339)
        at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:52)
        at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:123)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:198)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:179)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:541)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:441)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:152)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:139)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

Those vertx logs are generally very verbose and unclear, so I have no idea what could be wrong and where to look at. 

**What do I have to do to track the problem down?**

### Quarkus version or git rev

3.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2

**Comment by geoand** [comment]
We'd need a sample application that reproduces this behavior in order to be able to look into what's causing this,

**Comment by Serkan80** [comment]
Just restart the application a couple of times by pressing S in the terminal. I also saw this happening.

**Comment by geoand** [comment]
Tried and failed

**Comment by mklueh** [comment]
I found the reason. I've indexed a dataset with Lucene in the `start(@Observes Startup startup)` method, and likely the index was locked and not released during restart

**Comment by geoand** [comment]
Thanks for the update
