### ISSUE TITLE
Provider io.quarkus.runtime.configuration.TemporaryConfigSourceProvider not found

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#3498]
**Describe the bug**
I've added a custom ConfigSourceProvider and as per documentation I've created the related service file. 

When running in JVM mode everything works as expected but when compiling as native image, then the application throws the following exception:

```
java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSourceProvider: Provider io.quarkus.runtime.configuration.TemporaryConfigSourceProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:80)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:190)
	at io.quarkus.runtime.generated.RunTimeConfig.getRunTimeConfiguration(RunTimeConfig.zig:11483)
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:42)
	at io.quarkus.runtime.Application.start(Application.java:84)
	at io.quarkus.runtime.Application.run(Application.java:196)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:94)
	at io.quarkus.runtime.Application.start(Application.java:84)
	at io.quarkus.runtime.Application.run(Application.java:196)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
Caused by: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSourceProvider: Provider io.quarkus.runtime.configuration.TemporaryConfigSourceProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:80)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:190)
	at io.quarkus.runtime.generated.RunTimeConfig.getRunTimeConfiguration(RunTimeConfig.zig:11483)
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:42)
	... 3 more
```

**Comment by gwenneg** [comment]
Did you name this provider `TemporaryConfigSourceProvider`? Because the exception seems to be about a class that already exists in Quarkus: [TemporaryConfigSourceProvider.java](https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/configuration/TemporaryConfigSourceProvider.java)

**Comment by lburgazzoli** [comment]
No, the set-up is:

- https://github.com/lburgazzoli/apache-camel-k-runtime/blob/github-57/camel-k-runtime-quarkus/camel-k-runtime-quarkus/src/main/java/org/apache/camel/k/quarkus/ApplicationRuntime.java#L100
- https://github.com/lburgazzoli/apache-camel-k-runtime/blob/github-57/camel-k-runtime-quarkus/camel-k-runtime-quarkus/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSourceProvider

**Comment by gsmet** [comment]
Could you check what happens in `ConfigurationSetup#addDiscoveredSources()` ?

Because this source should be added in the `ServiceProviderBuildItem` and thus added for reflection. So there's something fishy going on.

**Comment by lburgazzoli** [comment]
I see only mine:

![image](https://user-images.githubusercontent.com/1868933/62943359-93b2ce80-bdda-11e9-9112-7ddb63ec2cda.png)

**Comment by lburgazzoli** [comment]
@gsmet I confirm:

1. if I remove the custom source provider, then the image works
2. the workaround of declaring TemporaryConfigSourceProvider for reflection make the app working

**Comment by gsmet** [comment]
So what we need to understand is what triggers the issue when adding a custom source provider.

**Comment by lburgazzoli** [comment]
Added a reproducer here: https://github.com/lburgazzoli/quarkus-config-factory
