### ISSUE TITLE
Resteasy LocaleResolver crashes Hibernate Validator in Quarkus

### ISSUE THREAD

**Issue by thst71** [quarkusio/quarkus#35007]
### Describe the bug

We use the Hibernate validator as implementation of the Validation framework. In our application, two use cases are implemented: 

* The builtin use of the validation framework in a rest controller (works)
* A direct use of the validatorfactory to produce a validator to validate messages received over NATS.io (fails)

### Expected behavior

We expect to receive a validator result.

### Actual behavior

The validator used to check JSON received over nats fails with an exception:

```
javax.validation.ValidationException: HV000149: An exception occurred during message interpolation
	at org.hibernate.validator.internal.engine.validationcontext.AbstractValidationContext.interpolate(AbstractValidationContext.java:331)
	at org.hibernate.validator.internal.engine.validationcontext.AbstractValidationContext.addConstraintFailure(AbstractValidationContext.java:231)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:79)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.doValidateConstraint(MetaConstraint.java:130)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:123)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:555)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForSingleDefaultGroupElement(ValidatorImpl.java:518)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:488)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:450)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:400)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:172)
	at de....AbstractValidationService.validate(AbstractValidationService.java:67)
	at de.....
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at de.....        
	at io.nats.client.impl.NatsDispatcher.run(NatsDispatcher.java:97)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.vertx.http.runtime.CurrentVertxRequest, id=9260aa608251c44230eeb9b234f605844a7622bf]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:55)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.getCurrent(Unknown Source)
	at io.quarkus.hibernate.validator.runtime.locale.ResteasyReactiveLocaleResolver.getHeaders(ResteasyReactiveLocaleResolver.java:26)
	at io.quarkus.hibernate.validator.runtime.locale.AbstractLocaleResolver.getAcceptableLanguages(AbstractLocaleResolver.java:31)
	at io.quarkus.hibernate.validator.runtime.locale.AbstractLocaleResolver.resolve(AbstractLocaleResolver.java:17)
	at io.quarkus.hibernate.validator.runtime.locale.ResteasyReactiveLocaleResolver.resolve(ResteasyReactiveLocaleResolver.java:18)
	at io.quarkus.hibernate.validator.runtime.locale.LocaleResolversWrapper.resolve(LocaleResolversWrapper.java:27)
	at org.hibernate.validator.messageinterpolation.AbstractMessageInterpolator.interpolate(AbstractMessageInterpolator.java:343)
	at org.hibernate.validator.internal.engine.validationcontext.AbstractValidationContext.interpolate(AbstractValidationContext.java:322)
	... 30 more
```

The reason is the registered `ResteasyReactiveLocaleResolver`, that will try to use the current request context and fails outside of a try-catch-block and breaks the whole message interpolation. The current request context is only available when the validator is called through the rest endpoint. 

### How to Reproduce?

Inject the default ValidatorFactory into some class and create a validator to use. The app must have a REST controller with validation.

Use the validator outside a REST call.

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)

### Quarkus version or git rev

2.16.8.final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

### Additional information

The default validatorfactory cannot be used outside of a http context, this is unexpected and the localeResolverWrapper should be resilient to failing locale resolvers as they cannot be removed after creation and the failing resolver could have been ignored in our case. 

This would have lead to the DefaultLocaleResolver which would have created the correct result. 

At least, this behavior should be clearly documented, that a validator created with the default validatorfactory cannot be used outside of a http context, if a rest controller/resteasy is actively used.

**Comment by geoand** [comment]
This has already been fixed in #31518 for Quarkus 3.x

**Comment by gsmet** [comment]
Maybe it’s something we should try to backport given I plan a few more 2.16. I will mark the PR for backport and see how it goes.

**Comment by gsmet** [comment]
I was able to backport it so the fix will be in the next 2.16.

**Comment by geoand** [comment]
🏆

**Comment by thst71** [comment]
awesome @gsmet, do you know, when the next 2.16 will be released?
We tried to workaround the issue by  creating a ValidatorFactory manually but this does not work in native build (missing beans)

**Comment by gsmet** [comment]
Yeah, creating your own VF is not supported in native. I created the backport PR here and will release 2.16.9.Final early next week.

**Comment by gsmet** [comment]
2.16.9.Final is available on Maven Central.
