### ISSUE TITLE
Fast jar build fails at runtime with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by jkalex-git** [quarkusio/quarkus#35068]
### Describe the bug

The issue is happening after migrating to quarkus 3. Previous working version - 2.16.5.Final

No exception is thrown in 
- quarkus dev mode
- Legacy build
- quarkus test

The issue occurs only if I use fast jar build and try to run the application. 
Build commands used which causes failure at runtime,
```
RUN ./mvnw -B -e -c package -Dquarkus.package.type=fast-jar -DskipTests=true

COPY --from=build --chown=talpa-app:talpa-app /build/target/quarkus-app/lib/ ./application/lib/
COPY --from=build --chown=talpa-app:talpa-app /build/target/quarkus-app/*.jar ./application/
COPY --from=build --chown=talpa-app:talpa-app /build/target/quarkus-app/app/ ./application/app/
COPY --from=build --chown=talpa-app:talpa-app /build/target/quarkus-app/quarkus/ ./application/quarkus/
```

Workaround

```
RUN ./mvnw -B -e -C -s ci_settings.xml package -Dquarkus.package.type=legacy-jar -DskipTests=true

COPY --from=build --chown=talpa-app:talpa-app /build/target/lib/* ./application/lib/
COPY --from=build --chown=talpa-app:talpa-app /build/target/*-runner.jar ./application/quarkus-run.jar
```

Dependencies which may be causing the problem
```
        <dependency>
            <groupId>com.github.mjakubowski84</groupId>
            <artifactId>parquet4s-core_2.13</artifactId>
            <version>1.9.2</version>
        </dependency>

        <dependency>
            <groupId>org.apache.parquet</groupId>
            <artifactId>parquet-hadoop</artifactId>
            <version>1.12.3</version>
        </dependency>

       <dependency>
            <groupId>org.apache.parquet</groupId>
            <artifactId>parquet-format</artifactId>
            <version>2.9.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.parquet</groupId>
            <artifactId>parquet-encoding</artifactId>
            <version>1.12.3</version>
        </dependency>

        <dependency>
            <groupId>org.apache.parquet</groupId>
            <artifactId>parquet-column</artifactId>
            <version>1.12.3</version>
        </dependency>

        <dependency>
            <groupId>org.apache.parquet</groupId>
            <artifactId>parquet-common</artifactId>
            <version>1.12.3</version>
        </dependency>
```

### Actual behavior
The application starts up normal and waits for request. 
Once request comes and application starts to execute and runs without issues until parquet writer method is called.

Error Logs:

```
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/application/quarkus-run.jar
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-07-27 17:31:22,879 WARN  [io.qua.ope.run.exp.otl.LateBoundBatchSpanProcessor] (main) No BatchSpanProcessor delegate specified, no action taken.
2023-07-27 17:31:35,273 INFO  [tal.cor.ser.CService] (executor-thread-1) Starting conversion tool execution
 ERROR [io.qua.sch.com.run.StatusEmitterInvoker] (executor-thread-1) Error occurred while executing task for trigger IntervalTrigger [id=1_talpa.cortexconv.App#run, interval=1000]: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void org.apache.parquet.format.Util.writePageHeader(org.apache.parquet.format.PageHeader, java.io.OutputStream, org.apache.parquet.format.BlockCipher$Encryptor, byte[])'
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$MinimalStage.whenComplete(Unknown Source)
        at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:24)
        at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
        at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask.doInvoke(SimpleScheduler.java:416)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.handle(SimpleScheduler.java:397)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.handle(SimpleScheduler.java:393)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:581)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'void org.apache.parquet.format.Util.writePageHeader(org.apache.parquet.format.PageHeader, java.io.OutputStream, org.apache.parquet.format.BlockCipher$Encryptor, byte[])'
        at org.apache.parquet.format.converter.ParquetMetadataConverter.writeDataPageV1Header(ParquetMetadataConverter.java:1880)
        at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writePage(ColumnChunkPageWriteStore.java:186)
        at org.apache.parquet.column.impl.ColumnWriterV1.writePage(ColumnWriterV1.java:59)
        at org.apache.parquet.column.impl.ColumnWriterBase.writePage(ColumnWriterBase.java:387)
        at org.apache.parquet.column.impl.ColumnWriteStoreBase.flush(ColumnWriteStoreBase.java:186)
        at org.apache.parquet.column.impl.ColumnWriteStoreV1.flush(ColumnWriteStoreV1.java:29)
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:185)
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:124)
        at org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:319)
        at com.github.mjakubowski84.parquet4s.DefaultParquetWriter.close(ParquetWriter.scala:165)
        at com.github.mjakubowski84.parquet4s.ParquetWriter$.writeAndClose(ParquetWriter.scala:116)
        at talpa.io.ParquetWriter.$anonfun$writeFile$3(ParquetWriter.scala:371)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
```

### Output of `uname -a` or `ver`

debian:bullseye-slim 

### Output of `java -version`

java 17

### Quarkus version or git rev

3.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.6

**Comment by geoand** [comment]
Thanks for reporting.

Unfortunately, the only way we can dig into this is we have a small sample application we can run that exhibits the problematic behavior.

**Comment by Sanne** [comment]
This sounds like very likely you're having a problem with alignment of dependencies of Parquet, not really a Quarkus issue other than it possibly conflicting with something that's coming from the Quarkus BOM.

so, sorry but I don't think we can help.

**Comment by jkalex-git** [comment]
I think its a draw back that it cannot be reliably tested with the Quarkus test framework, and fails in fast-jar builds. 
Even the legacy jar works and fast jar in Quarkus 2.
So i am guessing it has something to do with 'indexed information about which dependency jar contains classes and resources'.
Knowing that some libraries can have problem with Quarkus framework in newer releases is a hard thing to accept when designing enterprise applications.
I hope its just limited to the parquet libraries.

**Comment by geoand** [comment]
> I think its a draw back that it cannot be reliably tested with the Quarkus test framework, and fails in fast-jar builds

It can be, you can use `@QuarkusIntegrationTest` for this as it launches the production jar
