### ISSUE TITLE
Datasource Devservices do not respect container port

### ISSUE THREAD

**Issue by ttsatsanis** [quarkusio/quarkus#35093]
### Describe the bug

When using Devservices for creating a database with TestContainers, the connection string targets the default port (5432) which is not the one that the container (in my case, Docker) exposes.

I do not know if it has to do only with reactive connections (as I am using).

### Expected behavior

When accessing /health-ui through Dev-UI, all connections should be up.

### Actual behavior

`Reactive PostgreSQL connections health check` is down.

Error:

> Error obtaining database connection for healthcheck of datasource '<default>': io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

The port should be 60329: `Container is started (JDBC URL: jdbc:postgresql://localhost:60329/quarkus?loggerLevel=OFF)`

### How to Reproduce?

1. Set the following configuration in application.yml:

>   quarkus.datasource.db-kind="postgresql"
     quarkus.datasource.devservices.enabled=true
     quarkus.datasource.jdbc=false
     quarkus.datasource.reactive=true
2. Run the application
3. Go to `localhost:8080/q/health-ui`

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by geoand** [comment]
I could not reproduce this. 

Please attach a sample application that behaves as described in the issue.

**Comment by geoand** [comment]
Thanks for the update!
