### ISSUE TITLE
"Hibernate Reactive Panache requires a safe (isolated) Vert.x sub-context, but the current context hasn't been flagged as such." when using Smallrye Messaging

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#35106]
### Describe the bug

Scenario: EntityA get's persisted, notification with entity is sent through message channel, receiver creates EntityB and links it to EntityA

This leads to the following error:

```
erResourceTest > testCreateUser() STANDARD_ERROR
    Jul 31, 2023 7:37:55 AM io.smallrye.reactive.messaging.providers.AbstractMediator invoke
    ERROR: SRMSG00200: The method com.example.EntityAService#onUserRegistrationConfirmed has thrown an exception
    java.lang.IllegalStateException: Hibernate Reactive Panache requires a safe (isolated) Vert.x sub-context, but the current context hasn't been flagged as such.
        at io.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle.checkIsSafe(VertxContextSafetyToggle.java:89)
        at io.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle.validateContextIfExists(VertxContextSafetyToggle.java:72)
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.vertxContext(SessionOperations.java:183)
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.withSession(SessionOperations.java:112)
        at io.quarkus.hibernate.reactive.panache.common.runtime.WithSessionInterceptor.intercept(WithSessionInterceptor.java:20)
        at io.quarkus.hibernate.reactive.panache.common.runtime.WithSessionInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at com.example.EntityAService_Subclass.onUserRegistrationConfirmed(Unknown Source)
        at com.example.EntityAService_ClientProxy.onUserRegistrationConfirmed(Unknown Source)
        at com.example.EntityAService_SmallRyeMessagingInvoker_onUserRegistrationConfirmed_3712669874522feb4afaa8774dd5fa51e4e2f384.invoke(Unknown Source)
        at io.smallrye.reactive.messaging.providers.AbstractMediator.invoke(AbstractMediator.java:136)
        at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeOnMessageContext$8(AbstractMediator.java:144)
        at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$0(LocalContextMetadata.java:34)
        at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$1(LocalContextMetadata.java:53)
        at io.smallrye.reactive.messaging.providers.helpers.VertxContext.lambda$runOnContext$0(VertxContext.java:26)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

I'm not sure if it is a Quarkus / Vert.X bug or if I'm missing something in my implementation.

The message is sent from within a transaction, and as I'm not using the `@Broadcast` annotation, I guess the transaction might still be open on the receiver-side or at least the same session is getting used. Is this true?

Are there any best / bad practices for using transactions / sessions accross a message bus?

### Expected behavior

To save the second entity without issues.

### How to Reproduce?

https://github.com/mklueh/quarkus-reactive-reproducer-context-not-flagged

Run the test inside the test package

**Comment by FroMage** [comment]
Sounds ike a question for @cescoffier

**Comment by cescoffier** [comment]
It's because you use an emitter with an "in-process/in-memory" channel. The message is processed on another duplicated context, which is not marked as safe by default (on purpose, as we can't know).
Use the latest Quarkus; you can use the `io.quarkus.vertx.SafeVertxContext`  annotation:

```java
    @SafeVertxContext
    @WithSession
    @Incoming(Events.USER_REGISTRATION_CONFIRMED)
    public Uni<EntityA> onUserRegistrationConfirmed(User user) {   
        return createEntityAAndLinkToUser(user.id)
                .onItem().invoke(link -> log.info("EntityA created and linked"));
    }
```

**Comment by mklueh** [comment]
@cescoffier thanks for the explanation.

So let's say you are using Kafka as an emitter, the `@SafeVertxContext` would not be needed then? 
Would this annotation even hurt in that case or can we safely just put it on every receiver?
If so, can't you just assume every receiver is safe by default instead of requiring the then-verbose annotation?

**Comment by cescoffier** [comment]
The annotation is in Quarkus 3.3. In the previous version you have an api doing the same (Vertx Toggle something). 

If you emit to Kafka no problem. If you consume from kafka using @Incoming no problem either. But yes, you can use the annotation every time if you are sure that your method (and subsequent methods) are not going to use the context concurrently.

**Comment by uPagge** [comment]
In my case, @SafeVertxContext didn't help. I read from the cafe and save it in the database.

**Comment by geoand** [comment]
Is this still an issue with the latest versions of Quarkus?

**Comment by cescoffier** [comment]
I think it got fixed a long time ago.

**Comment by geoand** [comment]
Let's close this then and we can always reopen if it is still an issue
