### ISSUE TITLE
@Nested tests in a superclass do not work with test profiles

### ISSUE THREAD

**Issue by adutra** [quarkusio/quarkus#35104]
### Describe the bug

If `@Nested` tests are declared in a shared superclass, and if 2 or more test subclasses exist, any test class using test profiles will crash with an `AmbiguousResolutionException`.

The relevant portions of the stack trace are:

```
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:786)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:752)
    ...
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.instance(RunningQuarkusApplicationImpl.java:90)
	at io.quarkus.test.junit.QuarkusTestExtension.createActualTestInstance(QuarkusTestExtension.java:792)
	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:773)
	... 76 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.instance(RunningQuarkusApplicationImpl.java:88)
	... 78 more
Caused by: jakarta.enterprise.inject.AmbiguousResolutionException: Beans: [CLASS bean [class=org.acme.Nested2Test, id=3b65ca95454361c99a346a4310722038d56f59c8], CLASS bean [class=org.acme.Nested1Test, id=570d58f8116768968fb960c30fc6d2e6df1364a9]]
	at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:291)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:309)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:190)
	... 83 more
```

There is a workaround though, see reproducer below, so I wouldn't consider this bug as an urgent one.

### Expected behavior

All tests should run and pass.

### Actual behavior

Any test class annotated with `@TestProfile` will throw `AmbiguousResolutionException` when executed.

### How to Reproduce?

The following is a small reproducer. Running `Nested1Test` will exhibit the faulty behavior:

```java
public class AbstractNestedTest {
    @Nested
    class NestedTests {
        @Test
        public void dummyNestedTest() {
        }
    }
}

```

```java
@QuarkusTest
@TestProfile(Nested1Test.Profile.class)
public class Nested1Test extends AbstractNestedTest {

    public static class Profile implements QuarkusTestProfile {
    }

    @Test
    public void dummyTest1() {
    }

    // Uncomment the following for a workaround:
    // @Nested
    // class NestedTests extends AbstractNestedTest.NestedTests {
    // }
}
```

```java
@QuarkusTest
public class Nested2Test extends AbstractNestedTest {
    @Test
    public void dummyTest2() {
    }
}
```

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10) OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode)

### Quarkus version or git rev

3.2.2.Final

### Additional information

I think it's a class loading issue. The if expression below:

https://github.com/quarkusio/quarkus/blob/752ec72787e8c67f213bd8b4ee65f616e113da2f/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L769 

...fails, but it shouldn't, because the 2 classes were loaded by different class loaders.

**Comment by geoand** [comment]
cc @Sgitario
