### ISSUE TITLE
async-http-client 2.x not compatible with JakartaEE 10

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#35128]
### Describe the bug

`org.asynchttpclient:async-http-client` 2.12.3 has recently been added to `quarkus-bom`. Unfortunately, this version is not compatible with JakartaEE 10.

https://github.com/AsyncHttpClient/async-http-client/blob/async-http-client-project-2.12.3/client/src/main/java/org/asynchttpclient/request/body/multipart/FileLikePart.java#L15

In the Camel Quarkus Zendesk integration test native build we see:

```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.asynchttpclient.request.body.multipart.FilePart.<init>(FilePart.java:45) 
Parsing context:
   at org.zendesk.client.v2.Zendesk.createUploadArticle(Zendesk.java:754)
   at org.zendesk.client.v2.Zendesk.createUploadArticle(Zendesk.java:743)
   at root method.(Unknown Source)

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:149)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:178)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:152)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraphInfo(MethodTypeFlow.java:110)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.lambda$onObservedUpdate$0(DefaultSpecialInvokeTypeFlow.java:63)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.LightImmutableCollection.forEach(LightImmutableCollection.java:90)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultSpecialInvokeTypeFlow.java:62)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:583)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:474)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.activation.MimetypesFileTypeMap. This error is reported at image build time because class org.asynchttpclient.request.body.multipart.FileLikePart is registered for linking at image build time by command line
        at parsing org.asynchttpclient.request.body.multipart.FileLikePart.<clinit>(FileLikePart.java:31)
```

We were aligning the Camel Quarkus project to use `org.asynchttpclient:async-http-client` 3.0.0.Beta2, which is compatible with JakartaEE 10. But it's no longer effective as `quarkus-bom` takes precedence.

Can we do the same the upgrade in Quarkus?

**Comment by gsmet** [comment]
Closing here in relation to the discussion here: https://github.com/quarkusio/quarkus/pull/45105 .

We will be able to upgrade once the Pulsar Client is compatible with 3.x.
