### ISSUE TITLE
HV000151: A method overriding another method must not redefine the parameter constraint configuration

### ISSUE THREAD

**Issue by dntichy** [quarkusio/quarkus#35144]
**I use** 
- reactivity (quarkus-resteasy-reactive-jackson, quarkus-rest-client-reactive-jackson)
- Java 11
- Quarkus 3.2.2.Final

When I try to run the application, , I end up with following error:

> Caused by: jakarta.validation.ConstraintDeclarationException: **HV000151: A method overriding another method must not redefine the parameter constraint configuration, but method TestServiceInterface$$CDIWrapper#doSomething(String) redefines the configuration of TestServiceInterface#doSomething(String)**.
	at org.hibernate.validator.internal.metadata.aggregated.rule.OverridingMethodMustNotAlterParameterConstraints.apply(OverridingMethodMustNotAlterParameterConstraints.java:24)
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.assertCorrectnessOfConfiguration(ExecutableMetaData.java:462)
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.build(ExecutableMetaData.java:380)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataBuilder$BuilderDelegate.build(BeanMetaDataBuilder.java:260)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataBuilder.build(BeanMetaDataBuilder.java:133)
	at org.hibernate.validator.internal.metadata.PredefinedScopeBeanMetaDataManager.createBeanMetaData(PredefinedScopeBeanMetaDataManager.java:155)
	at org.hibernate.validator.internal.metadata.PredefinedScopeBeanMetaDataManager.<init>(PredefinedScopeBeanMetaDataManager.java:100)
	at org.hibernate.validator.internal.engine.PredefinedScopeValidatorFactoryImpl.<init>(PredefinedScopeValidatorFactoryImpl.java:206)
	at org.hibernate.validator.PredefinedScopeHibernateValidator.buildValidatorFactory(PredefinedScopeHibernateValidator.java:42)
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:435)
	at io.quarkus.hibernate.validator.runtime.HibernateValidatorRecorder$2.created(HibernateValidatorRecorder.java:178)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:79)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources844392269.deploy(Unknown Source)
	... 15 more

I have an interface, with parameter annotated `@ConvertGroup(to = Error.class)` and I have an implementation of that interface:

![image](https://github.com/quarkusio/quarkus/assets/18206019/55e62824-3fa4-4ce3-98d4-6dcdc6fe2ab3)
![image](https://github.com/quarkusio/quarkus/assets/18206019/6e014615-692b-4079-9a24-8570ba222aed)

I understand that there are $$CDIWrapper classes which are generated from the interface.
I have noticed, that when applying OverridingMethodMustNotAlterParameterConstraints, there is an issue that callable 
`TestServiceInterface$$CDIWrapper#doSomething(String)` has empty **groupConversions** while `TestServiceInterface#doSomething(String)` have exactly one... 

I think this is a bug. 
What is interesting, I tried to dump all generated classes with (`-Dquarkus.debug.generated-classes-dir=dump-classes`) and I can see, that the ConvertGroup annotation is present on that $$CDIWrapper class:

![image](https://github.com/quarkusio/quarkus/assets/18206019/cb112264-34da-40bb-84e0-be4f9316615f)

**Here is a project to reproduce the error https://github.com/dntichy/convert-group-minimal-example**

### Expected behavior

Exception should not be thrown and app should start properly

### Actual behavior

Exception is thrown upon startup

### How to Reproduce?

**Here is a project to reproduce the error https://github.com/dntichy/convert-group-minimal-example**

### Output of `java -version`

openjdk version "11.0.19" 2023-04-18 LTS
OpenJDK Runtime Environment Corretto-11.0.19.7.1 (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.19.7.1 (build 11.0.19+7-LTS, mixed mode)

### Quarkus version or git rev

3.2.2.Final

**Comment by yrodiere** [comment]
Thanks for the workaround @MarcScheib .

That being said, this definitely looks like a bug to me, and you shouldn't have to do this.

I suspect that [this code](https://github.com/quarkusio/quarkus/blob/b9969efaaf7c3369822456c80c52dc293ab1b6ea/extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizer.java#L21-L26) is supposed to avoid that error, but doesn't work (anymore?) for some reason. We'll have to investigate.

**Comment by gsmet** [comment]
The normalizer does work but this `$$CDIWrapper` thing is new and was never taken into account.

I'll check if we can do something about it.

**Comment by marko-bekhta** [comment]
I had a look at this one and opened https://hibernate.atlassian.net/browse/HV-2029

We could try excluding the `$$CDIWrapper` types... but there also seems to be an issue on the Validator side. I would keep the HV fix for the 9.0 series only so as not to change any behaviour for existing apps using 8.0.

**Comment by gsmet** [comment]
I think there are two things to get done here on the Quarkus side though:

- we should be able to unwrap this thing in a way similar to https://github.com/quarkusio/quarkus/blob/b9969efaaf7c3369822456c80c52dc293ab1b6ea/extensions/hibernate-validator/runtime/src/main/java/io/quarkus/hibernate/validator/runtime/ArcProxyBeanMetaDataClassNormalizer.java#L21-L26 . For now I think we will have to hardcode it... and get to the interface if the class name ends with `$$CDIWrapper`. Not ideal and maybe we should take a step back and discuss with the CDI team when they're back from PTO.
- also maybe in `RestClientReactiveProcessor`, we shouldn't copy the Bean Validation annotations to the class and methods. We have `BeanValidationAnnotationsBuildItem` in a SPI for exactly this kind of usage.

**Comment by marko-bekhta** [comment]
I've created this draft PR https://github.com/quarkusio/quarkus/pull/42654 which tries to address the first part about unwrapping. As for the second part about not copying the annotations -- that would've been nice. And I gave it a try, but 😕  ...
```java
java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.ChainBuildException: Cycle detected:
		   io.quarkus.rest.client.reactive.deployment.RestClientReactiveProcessor#addRestClientBeans produced class io.quarkus.arc.deployment.GeneratedBeanBuildItem
		to io.quarkus.arc.deployment.BeanArchiveProcessor#build produced class io.quarkus.arc.deployment.BeanArchiveIndexBuildItem
		to io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor#beanValidationAnnotations produced class io.quarkus.hibernate.validator.spi.BeanValidationAnnotationsBuildItem
		to io.quarkus.rest.client.reactive.deployment.RestClientReactiveProcessor#addRestClientBeans
```
that's ^ when I've updated

https://github.com/quarkusio/quarkus/blob/34ca0e002996b919b922756d730f27f1f8835b47/extensions/resteasy-reactive/rest-client/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java#L543

to do something like 

```java
Set<DotName> allAnnotationsToSkip = new HashSet<>(SKIP_COPYING_ANNOTATIONS_TO_GENERATED_CLASS);
allAnnotationsToSkip.addAll(beanValidationAnnotationsBuildItem.getAllAnnotations());

// ....
for (AnnotationInstance annotation : annotationsStore.getAnnotations(jaxrsInterface)) {
    if (allAnnotationsToSkip.contains(annotation.name())) {
        continue;
    }
    // ....
    classCreator.addAnnotation(annotation);
}
```

other thing I've noticed is that `BeanValidationAnnotationsBuildItem` doesn't contain all possible (non-constraints like convert groups or group sequence providers etc) annotations. So we'd probably had to add those missing ones to the list if we want to do the filtering...

**Comment by gsmet** [comment]
I don't think there's an easy way to fix the cycle unfortunately.
