### ISSUE TITLE
quarkus-hibernate-reactive-panache-kotlin use suspend but session lose 

### ISSUE THREAD

**Issue by OrdinarySF** [quarkusio/quarkus#35168]
### Describe the bug

```kotlin
    @GET
    @Path("/{id}")
    suspend fun getSingle(id: Long): User {
        return userRepository.findById(id).awaitSuspending()
    }
```

### Actual behavior

error:
```
2023-08-02 20:37:33,232 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /user/1 failed, error id: 9fbdb37b-e68b-4094-8b41-d37534576005-1: java.lang.IllegalStateException: No current Mutiny.Session found
	- no reactive session was found in the context and the context was not marked to open a new session lazily
	- you might need to annotate the business method with @WithSession
	at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.getSession(SessionOperations.java:155)
	at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.getSession(AbstractJpaOperations.java:364)
	at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.findById(AbstractJpaOperations.java:98)
	at cn.holmescraft.wahr.jelly.sticker.repository.ClassRepository.findById(ClassRepository.kt)
	at cn.holmescraft.wahr.jelly.sticker.repository.ClassRepository.findById(ClassRepository.kt:9)
	at cn.holmescraft.wahr.jelly.sticker.repository.ClassRepository_ClientProxy.findById(Unknown Source)
	at cn.holmescraft.wahr.jelly.sticker.service.ClassService.getById$suspendImpl(ClassService.kt:14)
	at cn.holmescraft.wahr.jelly.sticker.service.ClassService.getById(ClassService.kt)
	at cn.holmescraft.wahr.jelly.sticker.service.ClassService_ClientProxy.getById(Unknown Source)
	at cn.holmescraft.wahr.jelly.sticker.resource.ClassResource.getSingle$suspendImpl(ClassRescource.kt:28)
	at cn.holmescraft.wahr.jelly.sticker.resource.ClassResource.getSingle(ClassRescource.kt)
	at cn.holmescraft.wahr.jelly.sticker.resource.ClassResource$quarkuscoroutineinvoker$getSingle_76f031b0311b0e37099fc7d71984a7111389ff3b.invokeCoroutine(Unknown Source)
	at org.jboss.resteasy.reactive.server.runtime.kotlin.CoroutineInvocationHandler$handle$1.invokeSuspend(CoroutineInvocationHandler.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at org.jboss.resteasy.reactive.server.runtime.kotlin.VertxDispatcher.dispatch$lambda$0(ApplicationCoroutineScope.kt:45)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22621.1992]

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 LTS OpenJDK Runtime Environment GraalVM 22.3.2 (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM GraalVM 22.3.2 (build 17.0.7+7-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)

22.3.2

### Quarkus version or git rev

3.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: E:\client\apache-maven-3.9.3 Java version: 17.0.7, vendor: BellSoft, runtime: D:\Program Files\BellSoft\bellsoft-liberica-vm-full-openjdk17-22.3.2 Default locale: zh_CN, platform encoding: GBK OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

**Comment by OrdinarySF** [comment]
maven dependency: 
```xml
   <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-kotlin</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-websockets</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-config-yaml</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-redis-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mongodb-panache-kotlin</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-kotlin</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>kotlin-extensions</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-reactive-panache-kotlin</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-reactive-pg-client</artifactId>
    </dependency>

    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
      <version>${mapstruct.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct-processor</artifactId>
      <version>${mapstruct.version}</version>
      <scope>provided</scope>
    </dependency>
```

**Comment by geoand** [comment]
Can you add a sample project that behaves as you mention?

**Comment by OrdinarySF** [comment]
https://github.com/OrdinarySF/quarkus-reactive-kotlin-demo

**Comment by DavideD** [comment]
This will work if you change it to:
```
    @GET
    @Path("/{id}")
    @WithSession
    fun getSingle(id: Long): Uni<User> {
        return userRepository.getById(id)
    }
```

In Quarkus, reactive are expected to return a `Uni`.
I don't think you are supposed to use suspendable in this scenario.

But I don't know enough about Kotlin to know if there's a difference.

**Comment by geoand** [comment]
The problem is almost certainly due to the improper use of the Vert.x context when `awaitSuspending` is used. 
There is not much that can be done without a proper integration

**Comment by OrdinarySF** [comment]
@DavideD @geoand In the[ quarkus guide](https://quarkus.io/guides/kotlin#coroutines-support), there is mention of support for the Kotlin coroutine, so I would like to try fully coroutinized reactive development. Like this [issus](https://github.com/quarkusio/quarkus/issues/10162).

I tried to add `@WithSession` directly but it didn't work. So how can I integrate appropriate dependencies to support this feature.

**Comment by geoand** [comment]
Coroutines are supported on a per feature manner. We need to integrate them into with Hibernate Reactive - cc @evanchooly

**Comment by Feavy** [comment]
```kt
@GET
@Path("/{id}")
suspend fun getSingle(id: Long): User = coroutineScope {
    Panache.withSession {
        this.async {
            // Put your actual code here
            return@async userRepository.findById(id).awaitSuspending()
        }.asUni()
    }.awaitSuspending()
}
```

Something like that should work but it's quite annoying to have to wrap the code like that.

**Comment by geoand** [comment]
Yeah, that's something we don't want people to have to do - cc @evanchooly

**Comment by evanchooly** [comment]
I can see where we make that leap in to the coroutine context but I'm not familar with the vert.x context bits so I'm not sure what to do here.

**Comment by OrdinarySF** [comment]
@Feavy Great, that it can work. But maybe we have a better solution to reduce the overhead of context switching?

**Comment by FredyH** [comment]
There is also a similar issue when trying to return a `Uni<T>` (for example in `IdentityProvider`) and to make the coroutine remember the session.
I managed to get a solution as @Feavy to work which essentially does the same setup as the `AbstractCoroutineInvoker` that Quarkus uses when invoking suspending functions. The trick is to use the correct coroutine scope and dispatcher.

```kotlin
@OptIn(ExperimentalCoroutinesApi::class)
fun <R> withPanacheTransaction(block: suspend () -> R): Uni<R> = Panache.withTransaction {
    val coroutineScope = Arc.container().instance(ApplicationCoroutineScope::class.java).get()
    val dispatcher: CoroutineDispatcher =
        io.vertx.core.Vertx.currentContext()?.let(::VertxDispatcher)
            ?: throw IllegalStateException("No Vertx context found")
    coroutineScope.async(dispatcher) {
        block()
    }.asUni()
}
```

**Comment by frankcoutinho** [comment]
Sadly, both features were not designed to be composed.
"Do want a suspend function endpoint? We've got you"
"Do want to use kotlin with Panache? Don't you worry my man"
"You want both? Erh, no can do"

It's quite gruesome to work with both of these (I had to abandon panache)

**Comment by sengokudaikon** [comment]
@FredyH could you please provide a gist of your solution and a smaple implementation for withPanacheTransaction?

**Comment by FredyH** [comment]
The implementation you can find in my post above, and you can use it like the following in a controller:

```kotlin
@GET
@Path("/{id}")
suspend fun getSingle(id: Long): Uni<User> = withPanacheTransaction {
    userRepository.findById(id).awaitSuspending()
}
```

However, please note that I stopped using Panache myself because there were far too few pain points when using it with coroutines, so I am not sure that you will not run into other issues along the way.

**Comment by SimonScholz** [comment]
@FredyH So what library would you recommend when it comes to Kotlin Coroutines and reading entities from a database, e.g. Postgres?
Are you using io.quarkus:quarkus-reactive-pg-client for this purpose, because here they state that this should work out of the box with suspend functions: https://github.com/quarkusio/quarkus/issues/35359#issuecomment-1688782251
Unfortunately this is really low level api without JPA etc.

So I would be interested what others are using.

**Comment by FredyH** [comment]
@SimonScholz Personally, we switched back to using Jooq with their new coroutines support and quarkus plugin. It worked for us because we encountered the issue early on in the project. Unfortunately, it is probably not an option for most people :(

**Comment by gho1b** [comment]
i try this one, but i hope some one can make this approach simpler
```kotlin
import io.quarkus.hibernate.reactive.panache.Panache
import io.smallrye.mutiny.Uni
import io.vertx.kotlin.coroutines.vertxFuture

private fun <T> (suspend () -> T).asUni(): Uni<T> = Uni.createFrom()
    .completionStage(vertxFuture { this@asUni() }.toCompletionStage())

internal fun <T> withSession(block: suspend () -> T) = Panache.withSession { block.asUni() }

internal fun <T> transactional(block: suspend () -> T) = Panache.withTransaction { block.asUni() }
```

**Comment by thomaslhostis** [comment]
@Feavy and @FredyH's solution are working perfectly with Reactive Panache and MongoDB (as long as you're using a replica set).

Here's an updated version of their code:

```kotlin
import io.quarkus.mongodb.panache.common.reactive.Panache
import io.smallrye.mutiny.coroutines.asUni
import io.smallrye.mutiny.coroutines.awaitSuspending
import jakarta.enterprise.context.ApplicationScoped
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope

@ApplicationScoped
class MongoTransactionManager {
    @OptIn(ExperimentalCoroutinesApi::class)
    suspend fun <T> withTransaction(block: suspend () -> T): T = coroutineScope {
        Panache.withTransaction {
            this.async { block() }.asUni()
        }.awaitSuspending()
    }
}
```

Or

```kotlin
import io.quarkus.mongodb.panache.common.reactive.Panache
import io.smallrye.mutiny.coroutines.asUni
import io.smallrye.mutiny.coroutines.awaitSuspending
import io.vertx.core.Vertx
import io.vertx.kotlin.coroutines.dispatcher
import jakarta.enterprise.context.ApplicationScoped
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.async

@ApplicationScoped
class MongoTransactionManager {
    @OptIn(ExperimentalCoroutinesApi::class)
    suspend fun <T> withTransaction(block: suspend () -> T): T = Panache.withTransaction {
        val coroutineDispatcher = Vertx.currentContext().dispatcher()
        val coroutineScope = CoroutineScope(coroutineDispatcher)
        coroutineScope.async { block() }.asUni()
    }.awaitSuspending()
}
```
It's pretty straightforward and can be isolated.

To use it, it's as simple as:

```kotlin
@ApplicationScoped
class MyUseCaseClass(
    private val mongoTransactionManager: mongoTransactionManager
) {
    suspend fun myUseCaseFunction() = mongoTransactionManager.withTransaction {
        ...
    }
}

**Comment by thomaslhostis** [comment]
Also, this is how I managed to deal with a use case without a Vertx context (a JobRunr task in my case):
```kotlin
import io.quarkus.mongodb.panache.common.reactive.Panache
import io.quarkus.vertx.VertxContextSupport
import io.smallrye.mutiny.Uni
import io.smallrye.mutiny.coroutines.asUni
import io.smallrye.mutiny.coroutines.awaitSuspending
import io.vertx.core.Vertx
import io.vertx.kotlin.coroutines.dispatcher
import jakarta.enterprise.context.ApplicationScoped
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch
import sncf.traction.madoc.domain.transactions.TransactionManager
import java.util.concurrent.CompletableFuture

@ApplicationScoped
class MongoTransactionManager(
    private val vertx: Vertx,
) : TransactionManager {

    @OptIn(ExperimentalCoroutinesApi::class)
    override suspend fun <T> withTransaction(
        block: suspend () -> T,
    ): T = if (Vertx.currentContext() != null) {

        coroutineScope {
            Panache.withTransaction {
                async { block() }.asUni()
            }.awaitSuspending()
        }

    } else {
        // Unfortunately, I couldn't make it less verbose
        VertxContextSupport.subscribeAndAwait {
            Uni.createFrom().completionStage {
                val completableFuture = CompletableFuture<Unit>()
                CoroutineScope(vertx.dispatcher()).launch {

                    try {
                        Panache.withTransaction {
                            async { block() }.asUni()
                        }.awaitSuspending()
                        completableFuture.complete(Unit)

                    } catch (throwable: Throwable) {
                        completableFuture.completeExceptionally(throwable)
                    }
                }

                completableFuture
            } as Uni<T>
        } as T
    }
}
```

**Comment by lucamolteni** [comment]
> [@Feavy](https://github.com/Feavy) and [@FredyH](https://github.com/FredyH)'s solution are working perfectly with Reactive Panache and MongoDB (as long as you're using a replica set).
> 
> Here's an updated version of their code:
> 
> import io.quarkus.mongodb.panache.common.reactive.Panache
> import io.smallrye.mutiny.coroutines.asUni
> import io.smallrye.mutiny.coroutines.awaitSuspending
> import jakarta.enterprise.context.ApplicationScoped
> import kotlinx.coroutines.ExperimentalCoroutinesApi
> import kotlinx.coroutines.async
> import kotlinx.coroutines.coroutineScope
> 
> @ApplicationScoped
> class MongoTransactionManager {
>     @OptIn(ExperimentalCoroutinesApi::class)
>     suspend fun <T> withTransaction(block: suspend () -> T): T = coroutineScope {
>         Panache.withTransaction {
>             this.async { block() }.asUni()
>         }.awaitSuspending()
>     }
> }
> Or
> 
> import io.quarkus.mongodb.panache.common.reactive.Panache
> import io.smallrye.mutiny.coroutines.asUni
> import io.smallrye.mutiny.coroutines.awaitSuspending
> import io.vertx.core.Vertx
> import io.vertx.kotlin.coroutines.dispatcher
> import jakarta.enterprise.context.ApplicationScoped
> import kotlinx.coroutines.CoroutineScope
> import kotlinx.coroutines.ExperimentalCoroutinesApi
> import kotlinx.coroutines.async
> 
> @ApplicationScoped
> class MongoTransactionManager {
>     @OptIn(ExperimentalCoroutinesApi::class)
>     suspend fun <T> withTransaction(block: suspend () -> T): T = Panache.withTransaction {
>         val coroutineDispatcher = Vertx.currentContext().dispatcher()
>         val coroutineScope = CoroutineScope(coroutineDispatcher)
>         coroutineScope.async { block() }.asUni()
>     }.awaitSuspending()
> }
> It's pretty straightforward and can be isolated.
> 
> To use it, it's as simple as:
> 
> @ApplicationScoped
> class MyUseCaseClass(
>     private val mongoTransactionManager: mongoTransactionManager
> ) {
>     suspend fun myUseCaseFunction() = mongoTransactionManager.withTransaction {
>         ...
>     }
> }

So if we have workarounds can we close this?

**Comment by FroMage** [comment]
Well, it's still a bug, no?

If someone with Kotlin expertise can contribute a fix, then we can close this.
