### ISSUE TITLE
Jvm memory metrics available in native image after upgrade to Quarkus 3

### ISSUE THREAD

**Issue by stephan-strate** [quarkusio/quarkus#35196]
### Describe the bug

After upgrading Quarkus from 2.16.7 to 3.2.2, we see the following warning, when requesting the metrics from `/q/metrics`:
```
2023-08-04 01:38:01,019 WARN  [io.micrometer.core.instrument.internal.DefaultGauge] (executor-thread-2) Failed to apply the value function for the gauge 'jvm.memory.used'. Note that subsequent logs will be logged at debug level.: java.lang.IllegalArgumentException: committed = 14680064 should be < max = 12582912
	at java.management@17.0.8/java.lang.management.MemoryUsage.<init>(MemoryUsage.java:166)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.genscavenge.AbstractMemoryPoolMXBean.memoryUsage(AbstractMemoryPoolMXBean.java:75)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.genscavenge.GenScavengeMemoryPoolMXBeans$EdenMemoryPoolMXBean.getUsage(GenScavengeMemoryPoolMXBeans.java:94)
	at io.micrometer.core.instrument.binder.jvm.JvmMemory.getUsage(JvmMemory.java:76)
	at io.micrometer.core.instrument.binder.jvm.JvmMemory.getUsageValue(JvmMemory.java:66)
	at io.micrometer.core.instrument.binder.jvm.JvmMemoryMetrics.lambda$bindTo$0(JvmMemoryMetrics.java:82)
	at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:53)
	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newGauge$5(PrometheusMeterRegistry.java:331)
	at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:75)
	at io.prometheus.client.Collector.collect(Collector.java:45)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:204)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:219)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152)
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:71)
	at io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:53)
	at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:154)
	at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:149)
	at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:120)
	at io.quarkus.micrometer.runtime.export.handlers.PrometheusHandler.doHandle(PrometheusHandler.java:63)
	at io.quarkus.micrometer.runtime.export.handlers.PrometheusHandler.handle(PrometheusHandler.java:43)
	at io.quarkus.micrometer.runtime.export.handlers.PrometheusHandler.handle(PrometheusHandler.java:18)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
```

And `jvm_memory_*` metrics are available. As far as my understanding goes these metrics are not available, when building Quarkus as native image, right?

Did this change from 2.x to 3.x? I could not find anything in migration guides.

### Output of `java -version`

17

### GraalVM version (if different from Java)

Mandrel-23.0.1.2-Final (build 17.0.8+7)

### Quarkus version or git rev

3.2.2

**Comment by geoand** [comment]
I assume we should only be including `JvmMemoryMetrics` when in JVM mode (which is easy enough to do), but I am not sure why there is a difference in behavior between Quarkus 2.x and 3.x.

@ebullient any idea?

**Comment by stephan-strate** [comment]
Anything new?

**Comment by galderz** [comment]
@stephan-strate Do you have a reproducer?

**Comment by stephan-strate** [comment]
Its basically just quarkus-resteasy-reactive + quarkus-micrometer-registry-prometheus.

[reproducer-quarkus2.zip](https://github.com/quarkusio/quarkus/files/12919191/reproducer-quarkus2.zip)
[reproducer-quarkus3.zip](https://github.com/quarkusio/quarkus/files/12919192/reproducer-quarkus3.zip)

1. `mvn install -Dnative`
2. Launch the native image
3. Call localhost:8080/q/metrics
4. Compare results between quarkus 2 and quarkus 3

**Comment by galderz** [comment]
@stephan-strate I've not been able to replicate it the issue above using the Quarkus 3 reproducer you uploaded along with the latest GraalVM for JDK 21 21.0.0.0 release (download from [here](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-21.0.0)).

The changes in `jvm_info` are due to internal versioning changes that have happened ever since GraalVM adopted the "GraalVM for JDK.." naming. You can read about the changes in their [June announcement](https://medium.com/graalvm/a-new-graalvm-release-and-new-free-license-4aab483692f5).

Quarkus 2 with GraalVM 22.3 shows:
```
jvm_info_total{runtime="unknown",vendor="Oracle Corporation",version="unknown",} 1.0
```

Quarkus 3.4.3 with GraalVM for JDK 21 shows:
```
jvm_info_total{runtime="GraalVM Runtime Environment",vendor="GraalVM Community",version="21+35-jvmci-23.1-b15",} 1.0
```

Also, in spite of the differences in `jvm_info`, it looks to me that the info in the more recent versions is more meaningful than the previous one.

If using Mandrel, it's version 23.1.0.0 is equivalent to GraalVM for JDK 21 21.0.0.0. Note also that the default in-container image has not switched to Mandrel 23.1.0.0 yet. That was integrated [a few days ago](https://github.com/quarkusio/quarkus/pull/36457) and seems it'll be default in Quarkus 3.5.0, but you can still tell Quarkus to build in-container passing in the builder container image for Mandrel 23.1.0.0 (see the available tags [here](https://quay.io/repository/quarkus/ubi-quarkus-mandrel-builder-image?tab=tags), `23.1.0.0-Final-java21` should work here).
