### ISSUE TITLE
`QuarkusUnitTest` throws "No config found for class" when writing extension using Kotlin

### ISSUE THREAD

**Issue by jeffawx** [quarkusio/quarkus#35221]
### Describe the bug

When I write a Quarkus extension using Kotlin, I could't get `QuarkusUnitTest` mechanism working properly if I have a config class defined in `runtime` module and used in a build step in `deployment` module.

If I changed to Java, works fine.

Current workaround is manually creating a file `META-INF/quarkus-config-roots.list` and list the config class there, but as described in the following link this file is not supposed to be edited manually: https://quarkus.io/guides/extension-metadata#quarkus-config-roots

Apart from this issue, defining config class using Kotlin isn't nice experience, e.g. can't use data class and Kotlin native types, has to put @JvmField on each field and make sure the field is declared using `var` instead of `val`, etc.

### Expected behavior

Should not throw error

### Actual behavior

Can't find config class, throw exception:

> Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
> 	[error]: Build step demo.DemoProcessor#helloServlet threw an exception: java.lang.IllegalStateException: No config found for class demo.HelloConfig
> 	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadResult.requireObjectForClass(BuildTimeConfigurationReader.java:1274)
> 	at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$55(ExtensionLoader.java:591)
> 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:860)
> 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
> 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
> 
> 	at app//io.quarkus.builder.Execution.run(Execution.java:123)
> 	at app//io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
> 	at app//io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
> 	at app//io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:332)
> 	... 59 more
> Caused by: java.lang.IllegalStateException: No config found for class demo.HelloConfig
> 	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadResult.requireObjectForClass(BuildTimeConfigurationReader.java:1274)
> 	at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$55(ExtensionLoader.java:591)
> 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:860)
> 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
> 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
> 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

### How to Reproduce?

Example project demo this issue:

https://github.com/jeffawx/quarkus-ext-test

If this file is removed: https://github.com/jeffawx/quarkus-ext-test/blob/main/deployment/src/main/resources/META-INF/quarkus-config-roots.list

build will fail: `./gradlew clean build`

### Output of `java -version`

openjdk 17.0.7 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)

### Quarkus version or git rev

3.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.0

**Comment by geoand** [comment]
This doesn't work because an annotation processor needs to generate metadata for Config classes. 
Of course that annotation processor only works for Java source.

This is issue is very similar to #35110.

**Comment by geoand** [comment]
Just as a note, you could overcome this issue by using a `@ConfigMapping` class for your configuration instead of a `@ConfigRoot`

**Comment by geoand** [comment]
In that case, I propose using `@ConfigMapping` instead

**Comment by jeffawx** [comment]
> In that case, I propose using `@ConfigMapping` instead

I switched to use `@ConfigMapping`, now a bit more Kotlin friendly (no more val/var limitation and `@JvmField`), but I get same result as previously, i.e. extension still works properly in real application, but `QuarkusUnitTest` can't find config which can be fixed by manually put in `META-INF/quarkus-config-roots.list`

```kotlin
@ConfigRoot(phase = ConfigPhase.BUILD_TIME)
@ConfigMapping(prefix = "quarkus.my.ext")
interface HelloConfig {
    /**
     * test
     */
    @WithDefault("Hello World")
    fun text(): String
}
```

btw: My config class is root level, has to put `@ConfigRoot` or else doesn't work, I see the same pattern in Quarkus code base, e.g. https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveServerRuntimeConfig.java

**Comment by geoand** [comment]
Can you update your sample with ConfigMapping?

Thanks

**Comment by geoand** [comment]
cc @radcortez

**Comment by jeffawx** [comment]
> https://github.com/jeffawx/quarkus-ext-test

Yep pushed the changes here: https://github.com/jeffawx/quarkus-ext-test

if you run `./gradlew test` it should pass test, but if you remove `META-INF/quarkus-config-roots.list` will fail

Also confirmed this test extension works properly in real application.

**Comment by radcortez** [comment]
For what I've seen, the processor is not being executed at all. It requires:

```gradle
kapt {
    keepJavacAnnotationProcessors = true
}
```

Now the processor executes as expected, but it does not generate the files in the standard folders. These are generated in `build/tmp/kapt3/classes/`. Check https://youtrack.jetbrains.com/issue/KT-22263.

I've tried to add the sources on the runtime project, with

```gradle
sourceSets {
    main {
        resources {
            srcDir("build/tmp/kapt3/classes/main")
        }
    }
}
```

The expected config file is now in the JAR, but it seems it is not visible in the deployment project. It seems that additional source sets are not added in the module dependency. I'm not a big expert in Gradle, so maybe someone else can help here?

**Comment by jeffawx** [comment]
> source sets are not added in the module dependency.

Thanks for the feedback!

But how come the extension (without manual `META-INF/quarkus-config-roots.list`) works properly in actual application?

What I can see is annotation processor works fine, because if I removed the following line in build script the application just failed

```
kapt("io.quarkus:quarkus-extension-processor:3.2.2.Final")
```

The only part doesn't work is the unit test for the extension itself using `QuarkusUnitTest` (seems it can find metadata file for build steps, just config-root is a problem)

I got this issue because I wanted to added some proper unit test for my existing extension.

**Comment by jeffawx** [comment]
FYI: it seems to be some ClassLoader related problem for `QuarkusUnitTest`

Because I wrote a simple test method adding the lines below it can find and print my config file:

```kotlin
val file = ServiceUtil.classNamesNamedIn(
    Thread.currentThread().contextClassLoader,
    "META-INF/quarkus-config-roots.list_test"
)
println(file)
``` 

Under the covers Quarkus uses `ServiceUtil.classNamesNamedIn` to find the resources so the only difference is classloader.

**Comment by radcortez** [comment]
It works when running the `test-app` because you are referencing the resulting jars of the extension, which contains the `quarkus-config-root.list`.

The issue here is `kapt`  is generating the output in a different folder from `build/classes` or `build/resources` as you would expect. For a Gradle dependency project these are the expected directories to find each project module output. There should be a way to change the output path.

Another easier alternative is copy the generated file to the main build output. Adding this to the `runtime` module, the test passes as expected:

```gradle
tasks.register<Copy>("copyConfigRoots") {
    from(layout.buildDirectory.file("tmp/kapt3/classes/main/META-INF/quarkus-config-roots.list"))
    into(layout.buildDirectory.dir("resources/main/META-INF/"))
}

tasks.named("build") {
    finalizedBy("copyConfigRoots")
}
```

**Comment by jeffawx** [comment]
Thanks @radcortez, I tried the snippet above it works!

I also found out the test code below can find config because kotlin plugin appended the directory into classpath.

In ```System.getProperty("java.class.path")``` result I can see `tmp/kapt3/classes/main`

Question: is it possible in future to make `QuarkusUnitTest` respect `java.class.path` so that no need to do special configuration for kotlin?

```kotlin
@Test
fun test() {
    println(System.getProperty("java.class.path"))

    val names = ServiceUtil.classNamesNamedIn(
        Thread.currentThread().contextClassLoader,
        "META-INF/quarkus-config-roots.list"
     )
     println(names)
}
```

**Comment by radcortez** [comment]
@aloubyansky I think this is needs to be handled in https://github.com/quarkusio/quarkus/blob/main/devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/GradleApplicationModelBuilder.java
