### ISSUE TITLE
Migration script to Quarkus 3.0 hanging on `Parsing source files`

### ISSUE THREAD

**Issue by SandraPetkovic** [quarkusio/quarkus#35267]
### Describe the bug

When migrating a Kotlin project from Quarkus 2.13. to Quarkus 3.0 using the Quarkus cli command `quarkus update --stream=3.0`, the script hangs on

```
[INFO] [INFO] Using active recipe(s) [io.quarkus.openrewrite.Quarkus]
[INFO] [INFO] Using active styles(s) []
[INFO] [INFO] Validating active recipes...
[INFO] [INFO] Project [projectName] Resolving Poms...
[INFO] [INFO] Project [projectName] Parsing source files
```

Although the project is fairly large (~1000 source files), we've let it run for over an hour with no progress. Is it expected to take a long time?

### Expected behavior

The script should terminate, either successfully or with a failure message.

### Actual behavior

The script hangs on `[INFO] [INFO] Project [projectName] Parsing source files`:

```
[INFO] [INFO] Using active recipe(s) [io.quarkus.openrewrite.Quarkus]
[INFO] [INFO] Using active styles(s) []
[INFO] [INFO] Validating active recipes...
[INFO] [INFO] Project [projectName] Resolving Poms...
[INFO] [INFO] Project [projectName] Parsing source files
```

### Output of `uname -a` or `ver`

Darwin Sandras-MacBook-Pro-2.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110 arm64

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 LTS OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /Users/sandrapetkovic/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 11.0.20, vendor: Azul Systems, Inc., runtime: /Users/sandrapetkovic/.sdkman/candidates/java/11.0.20-zulu/zulu-11.jdk/Contents/Home Default locale: en_CA, platform encoding: UTF-8 OS name: "mac os x", version: "12.5", arch: "aarch64", family: "mac"

**Comment by evanchooly** [comment]
OpenRewrite does not support kotlin (last time I checked)

**Comment by geoand** [comment]
cc @gsmet

**Comment by SandraPetkovic** [comment]
I was able to run this script in March without it hanging. The [issue](https://github.com/quarkusio/quarkus/issues/32126) was with a Jooq dependency, but it was otherwise working fine with Kotlin (changing all the imports and dependencies)

**Comment by SandraPetkovic** [comment]
Thanks for the suggestion. The two outputs are below:

```
2023-08-09 14:20:19
Full thread dump OpenJDK 64-Bit Server VM (11.0.20+8-LTS mixed mode):

Threads class SMR info:
_java_thread_list=0x000060000265eb60, length=11, elements={
0x0000000132808800, 0x00000001320af000, 0x00000001320b1800, 0x00000001320a5000,
0x00000001320a6000, 0x00000001320c5800, 0x00000001320c6800, 0x000000012680c800,
0x000000013211a000, 0x0000000132963800, 0x0000000126bba000
}

"main" #1 prio=5 os_prio=31 cpu=630.30ms elapsed=4939.30s tid=0x0000000132808800 nid=0x1903 in Object.wait()  [0x000000016f1bd000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.20/Native Method)
        - waiting on <0x00000006cd50af00> (a java.lang.ProcessImpl)
        at java.lang.Object.wait(java.base@11.0.20/Object.java:328)
        at java.lang.ProcessImpl.waitFor(java.base@11.0.20/ProcessImpl.java:495)
        - waiting to re-lock in wait() <0x00000006cd50af00> (a java.lang.ProcessImpl)
        at io.quarkus.cli.build.ExecuteUtil.executeProcess(ExecuteUtil.java:73)
        at io.quarkus.cli.build.BuildSystemRunner.run(BuildSystemRunner.java:50)
        at io.quarkus.cli.build.MavenRunner.updateProject(MavenRunner.java:186)
        at io.quarkus.cli.Update.call(Update.java:28)
        at io.quarkus.cli.Update.call(Update.java:11)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.quarkus.cli.QuarkusCli.run(QuarkusCli.java:97)
        at io.quarkus.cli.QuarkusCli_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.cli.Main.main(Main.java:9)

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=0.22ms elapsed=4939.30s tid=0x00000001320af000 nid=0x3503 waiting on condition  [0x0000000170012000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.20/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@11.0.20/Reference.java:241)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.20/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=31 cpu=0.17ms elapsed=4939.30s tid=0x00000001320b1800 nid=0x3603 in Object.wait()  [0x000000017021e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.20/Native Method)
        - waiting on <0x00000006ce022cb8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.20/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x00000006ce022cb8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.20/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.20/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=0.47ms elapsed=4939.30s tid=0x00000001320a5000 nid=0x3d03 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=31 cpu=0.02ms elapsed=4939.30s tid=0x00000001320a6000 nid=0x5603 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=31 cpu=525.89ms elapsed=4939.30s tid=0x00000001320c5800 nid=0xa703 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #9 daemon prio=9 os_prio=31 cpu=324.58ms elapsed=4939.31s tid=0x00000001320c6800 nid=0x5803 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #10 daemon prio=9 os_prio=31 cpu=0.01ms elapsed=4939.31s tid=0x000000012680c800 nid=0x5903 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #11 daemon prio=8 os_prio=31 cpu=29.00ms elapsed=4939.28s tid=0x000000013211a000 nid=0xa103 in Object.wait()  [0x000000017118a000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.20/Native Method)
        - waiting on <0x00000006ce034a18> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.20/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x00000006ce034a18> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@11.0.20/CleanerImpl.java:148)
        at java.lang.Thread.run(java.base@11.0.20/Thread.java:829)
        at jdk.internal.misc.InnocuousThread.run(java.base@11.0.20/InnocuousThread.java:161)

"executor-thread-2" #16 daemon prio=5 os_prio=31 cpu=0.55ms elapsed=4938.87s tid=0x0000000132963800 nid=0x9e03 waiting on condition  [0x00000001715a2000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.20/Native Method)
        - parking to wait for  <0x00000006ce0232b0> (a org.jboss.threads.EnhancedQueueExecutor)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.20/LockSupport.java:194)
        at org.jboss.threads.EnhancedQueueExecutor$PoolThreadNode.park(EnhancedQueueExecutor.java:2276)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1570)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(java.base@11.0.20/Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

"process reaper (pid 32196)" #17 daemon prio=10 os_prio=31 cpu=0.07ms elapsed=4938.41s tid=0x0000000126bba000 nid=0x6603 runnable  [0x000000017201e000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ProcessHandleImpl.waitForProcessExit0(java.base@11.0.20/Native Method)
        at java.lang.ProcessHandleImpl$1.run(java.base@11.0.20/ProcessHandleImpl.java:141)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.20/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.20/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.20/Thread.java:829)

"VM Thread" os_prio=31 cpu=420.28ms elapsed=4939.34s tid=0x00000001320a7000 nid=0x4803 runnable  

"GC Thread#0" os_prio=31 cpu=70.28ms elapsed=4939.36s tid=0x0000000132014800 nid=0x2d03 runnable  

"GC Thread#1" os_prio=31 cpu=75.96ms elapsed=4938.87s tid=0x00000001321cd000 nid=0x5c07 runnable  

"GC Thread#2" os_prio=31 cpu=70.57ms elapsed=4938.87s tid=0x000000013219a800 nid=0x9f07 runnable  

"GC Thread#3" os_prio=31 cpu=78.06ms elapsed=4938.87s tid=0x00000001321c1000 nid=0x6003 runnable  

"GC Thread#4" os_prio=31 cpu=79.81ms elapsed=4938.87s tid=0x00000001321c2000 nid=0x6203 runnable  

"GC Thread#5" os_prio=31 cpu=75.91ms elapsed=4938.87s tid=0x00000001321b3800 nid=0x6303 runnable  

"G1 Main Marker" os_prio=31 cpu=0.18ms elapsed=4939.36s tid=0x0000000132060800 nid=0x2e03 runnable  

"G1 Conc#0" os_prio=31 cpu=1.54ms elapsed=4939.37s tid=0x000000013280b000 nid=0x2f03 runnable  

"G1 Conc#1" os_prio=31 cpu=1.59ms elapsed=4938.68s tid=0x0000000132260000 nid=0x6403 runnable  

"G1 Refine#0" os_prio=31 cpu=0.09ms elapsed=4939.37s tid=0x00000001328ab800 nid=0x4d03 runnable  

"G1 Young RemSet Sampling" os_prio=31 cpu=942.66ms elapsed=4939.37s tid=0x0000000132061800 nid=0x4c03 runnable  
"VM Periodic Task Thread" os_prio=31 cpu=1656.82ms elapsed=4939.31s tid=0x0000000126808800 nid=0xa303 waiting on condition  

JNI global refs: 15, weak refs: 0

Heap
 garbage-first heap   total 262144K, used 46629K [0x00000006c0000000, 0x00000007c0000000)
  region size 1024K, 43 young (44032K), 7 survivors (7168K)
 Metaspace       used 29849K, capacity 30566K, committed 30768K, reserved 1077248K
  class space    used 3322K, capacity 3606K, committed 3712K, reserved 1048576K
```

Two minutes later
```
2023-08-09 14:23:00
Full thread dump OpenJDK 64-Bit Server VM (11.0.20+8-LTS mixed mode):

Threads class SMR info:
_java_thread_list=0x000060000265eb60, length=11, elements={
0x0000000132808800, 0x00000001320af000, 0x00000001320b1800, 0x00000001320a5000,
0x00000001320a6000, 0x00000001320c5800, 0x00000001320c6800, 0x000000012680c800,
0x000000013211a000, 0x0000000132963800, 0x0000000126bba000
}

"main" #1 prio=5 os_prio=31 cpu=630.30ms elapsed=5101.01s tid=0x0000000132808800 nid=0x1903 in Object.wait()  [0x000000016f1bd000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.20/Native Method)
        - waiting on <0x00000006cd50af00> (a java.lang.ProcessImpl)
        at java.lang.Object.wait(java.base@11.0.20/Object.java:328)
        at java.lang.ProcessImpl.waitFor(java.base@11.0.20/ProcessImpl.java:495)
        - waiting to re-lock in wait() <0x00000006cd50af00> (a java.lang.ProcessImpl)
        at io.quarkus.cli.build.ExecuteUtil.executeProcess(ExecuteUtil.java:73)
        at io.quarkus.cli.build.BuildSystemRunner.run(BuildSystemRunner.java:50)
        at io.quarkus.cli.build.MavenRunner.updateProject(MavenRunner.java:186)
        at io.quarkus.cli.Update.call(Update.java:28)
        at io.quarkus.cli.Update.call(Update.java:11)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.quarkus.cli.QuarkusCli.run(QuarkusCli.java:97)
        at io.quarkus.cli.QuarkusCli_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.cli.Main.main(Main.java:9)

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=0.22ms elapsed=5100.99s tid=0x00000001320af000 nid=0x3503 waiting on condition  [0x0000000170012000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.20/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@11.0.20/Reference.java:241)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.20/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=31 cpu=0.17ms elapsed=5100.99s tid=0x00000001320b1800 nid=0x3603 in Object.wait()  [0x000000017021e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.20/Native Method)
        - waiting on <0x00000006ce022cb8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.20/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x00000006ce022cb8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.20/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.20/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=0.69ms elapsed=5100.98s tid=0x00000001320a5000 nid=0x3d03 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=31 cpu=0.02ms elapsed=5100.98s tid=0x00000001320a6000 nid=0x5603 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=31 cpu=527.01ms elapsed=5100.98s tid=0x00000001320c5800 nid=0xa703 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #9 daemon prio=9 os_prio=31 cpu=325.50ms elapsed=5100.98s tid=0x00000001320c6800 nid=0x5803 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #10 daemon prio=9 os_prio=31 cpu=0.01ms elapsed=5100.98s tid=0x000000012680c800 nid=0x5903 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #11 daemon prio=8 os_prio=31 cpu=30.40ms elapsed=5100.95s tid=0x000000013211a000 nid=0xa103 in Object.wait()  [0x000000017118a000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.20/Native Method)
        - waiting on <0x00000006ce034a18> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.20/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x00000006ce034a18> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@11.0.20/CleanerImpl.java:148)
        at java.lang.Thread.run(java.base@11.0.20/Thread.java:829)
        at jdk.internal.misc.InnocuousThread.run(java.base@11.0.20/InnocuousThread.java:161)

"executor-thread-2" #16 daemon prio=5 os_prio=31 cpu=0.55ms elapsed=5100.54s tid=0x0000000132963800 nid=0x9e03 waiting on condition  [0x00000001715a2000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.20/Native Method)
        - parking to wait for  <0x00000006ce0232b0> (a org.jboss.threads.EnhancedQueueExecutor)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.20/LockSupport.java:194)
        at org.jboss.threads.EnhancedQueueExecutor$PoolThreadNode.park(EnhancedQueueExecutor.java:2276)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1570)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(java.base@11.0.20/Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

"process reaper (pid 32196)" #17 daemon prio=10 os_prio=31 cpu=0.07ms elapsed=5100.08s tid=0x0000000126bba000 nid=0x6603 runnable  [0x000000017201e000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ProcessHandleImpl.waitForProcessExit0(java.base@11.0.20/Native Method)
        at java.lang.ProcessHandleImpl$1.run(java.base@11.0.20/ProcessHandleImpl.java:141)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.20/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.20/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.20/Thread.java:829)

"VM Thread" os_prio=31 cpu=438.16ms elapsed=5101.00s tid=0x00000001320a7000 nid=0x4803 runnable  

"GC Thread#0" os_prio=31 cpu=72.78ms elapsed=5101.02s tid=0x0000000132014800 nid=0x2d03 runnable  

"GC Thread#1" os_prio=31 cpu=78.28ms elapsed=5100.53s tid=0x00000001321cd000 nid=0x5c07 runnable  

"GC Thread#2" os_prio=31 cpu=73.11ms elapsed=5100.53s tid=0x000000013219a800 nid=0x9f07 runnable  

"GC Thread#3" os_prio=31 cpu=80.02ms elapsed=5100.53s tid=0x00000001321c1000 nid=0x6003 runnable  

"GC Thread#4" os_prio=31 cpu=82.11ms elapsed=5100.53s tid=0x00000001321c2000 nid=0x6203 runnable  

"GC Thread#5" os_prio=31 cpu=78.23ms elapsed=5100.53s tid=0x00000001321b3800 nid=0x6303 runnable  

"G1 Main Marker" os_prio=31 cpu=0.18ms elapsed=5101.02s tid=0x0000000132060800 nid=0x2e03 runnable  

"G1 Conc#0" os_prio=31 cpu=1.54ms elapsed=5101.02s tid=0x000000013280b000 nid=0x2f03 runnable  

"G1 Conc#1" os_prio=31 cpu=1.59ms elapsed=5100.33s tid=0x0000000132260000 nid=0x6403 runnable  

"G1 Refine#0" os_prio=31 cpu=0.09ms elapsed=5101.02s tid=0x00000001328ab800 nid=0x4d03 runnable  

"G1 Young RemSet Sampling" os_prio=31 cpu=979.27ms elapsed=5101.02s tid=0x0000000132061800 nid=0x4c03 runnable  
"VM Periodic Task Thread" os_prio=31 cpu=1732.99ms elapsed=5100.97s tid=0x0000000126808800 nid=0xa303 waiting on condition  

JNI global refs: 15, weak refs: 0

Heap
 garbage-first heap   total 262144K, used 46629K [0x00000006c0000000, 0x00000007c0000000)
  region size 1024K, 43 young (44032K), 7 survivors (7168K)
 Metaspace       used 29849K, capacity 30566K, committed 30768K, reserved 1077248K
  class space    used 3322K, capacity 3606K, committed 3712K, reserved 1048576K
```

To note, I changed to Java 11 from 17 to see if it would make any difference (it didn't).

```
openjdk 11.0.20 2023-07-18 LTS
OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.66+15-CA (build 11.0.20+8-LTS, mixed mode)
```

**Comment by gsmet** [comment]
Sorry for the delay, I was on PTO.

You need to do that for the nested process that is started specifically for the update.

Do a `ps faux | grep plainTextMasks` and you should get this process then `kill -3 <pid of this process>`.

Have you tried raising the Xmx in the `MAVEN_OPTS`? Something like:

```
export MAVEN_OPTS="-Xmx3000m"
quarkus update
```

I think the MAVEN_OPTS should be applied to the second process but please have a look at the command line. They should be there.

Btw, our update is actually parsing the Kotlin files as it does some text replacement in them so it might just be the process running out of memory and stalling.

**Comment by gsmet** [comment]
Closing for lack of feedback.
