### ISSUE TITLE
IllegalStateException: HttpBinderConfiguration was not found

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#35287]
### Describe the bug

Getting the following error when trying to dev run my app:

```
09:20:40 [WARN ][                |  |                |     ][io.ne.ut.co.DefaultPromise              |vert.x-acceptor-thread-0  ]():: An exception was thrown by io.vertx.core.net.impl.TCPServerBase$$Lambda$2203/0x00007f72f0c41900.operationComplete(): java.lang.IllegalStateException: HttpBinderConfiguration was not found
	at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterBinderAdapter.createHttpServerMetrics(VertxMeterBinderAdapter.java:63)
	at io.vertx.core.http.impl.HttpServerImpl.createMetrics(HttpServerImpl.java:71)
	at io.vertx.core.net.impl.TCPServerBase.lambda$null$1(TCPServerBase.java:184)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:97)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.lambda$null$1(AsyncResolveConnectHelper.java:61)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:578)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:426)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:375)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:557)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

Honestly no clue what could be happening, this happens about 50% of runs, and happens on every attempt at a REST call. 

Looks like additionally, the worker threads are being blocked:

```
2023-08-09 09:25:38,085 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-worker-thread-1,5,main] has been blocked for 233063 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
	at java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
	at java.base@17.0.8/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
	at java.base@17.0.8/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:444)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:437)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:152)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:139)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextBase$$Lambda$2210/0x00007f72f0c46f50.handle(Unknown Source)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.ContextBase$$Lambda$2207/0x00007f72f0c43d78.run(Unknown Source)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
```

Dependencies:

```
dependencies {
	implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
	implementation 'io.quarkus:quarkus-resteasy-reactive'
	implementation 'io.quarkus:quarkus-resteasy-reactive-jackson'
	implementation 'io.quarkus:quarkus-resteasy-reactive-qute'
	implementation 'io.quarkus:quarkus-smallrye-openapi'
//	implementation 'io.quarkus:quarkus-smallrye-jwt'// https://quarkus.io/guides/security-properties
	implementation 'io.quarkus:quarkus-smallrye-jwt-build'
	implementation 'io.quarkus:quarkus-smallrye-health'
	implementation 'io.quarkus:quarkus-smallrye-reactive-messaging-amqp'
	implementation 'io.quarkus:quarkus-opentelemetry'
	implementation 'io.quarkus:quarkus-config-yaml'
	implementation 'io.quarkus:quarkus-qute'
	implementation 'io.quarkus:quarkus-mongodb-panache'
	implementation 'io.quarkus:quarkus-hibernate-validator'
	implementation 'io.quarkus:quarkus-elytron-security'
	implementation 'io.quarkus:quarkus-micrometer-registry-prometheus'
	implementation 'io.quarkus:quarkus-container-image-jib'
	implementation 'io.quarkus:quarkus-rest-client-reactive'
	implementation 'io.quarkus:quarkus-rest-client-reactive-jackson'
	implementation 'io.quarkus:quarkus-mailer'
	implementation 'io.quarkus:quarkus-scheduler'
	implementation 'io.quarkus:quarkus-oidc'
//	implementation 'io.quarkus:quarkus-oidc-client-reactive-filter'
//	implementation 'io.quarkus:quarkus-oidc-token-propagation-reactive'
//	implementation 'io.quarkus:quarkus-keycloak-admin-client-reactive'

	//implementation 'io.opentelemetry.instrumentation:opentelemetry-mongo-3.1:1.24.0-alpha'
	// https://quarkus.io/guides/logging
	implementation 'org.jboss.slf4j:slf4j-jboss-logmanager'

	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
	implementation 'com.fasterxml.jackson.module:jackson-module-blackbird'


	implementation group: 'org.jsoup', name: 'jsoup', version: '1.16.1'
	implementation 'org.passay:passay:1.6.3'
	implementation 'com.itextpdf:html2pdf:5.0.0'

	//webjars
	implementation 'org.webjars:jquery:3.6.4'
	implementation 'org.webjars:bootstrap:5.3.0'
//	implementation 'org.webjars.npm:bootstrap-icons:1.10.2' //doesn't contain everything needed
//    implementation 'org.webjars:js-cookie:2.2.1' //out of date
//    implementation 'org.webjars:spin-js:2.1.0'

//	implementation 'tech.epic-breakfast-productions.openQuarterMaster.lib:open-qm-lib-core:1.0.62'
	implementation 'tech.epic-breakfast-productions.openQuarterMaster.lib:open-qm-lib-moduleDriver:1.0.2-DEV'

	// https://mvnrepository.com/artifact/tech.units/indriya
	//     https://unitsofmeasurement.gitbook.io/uom-guide/getting-started/getting-started-with-indriya
	implementation 'tech.units:indriya:2.2'
	implementation 'systems.uom:systems-common:2.1'
	// https://mvnrepository.com/artifact/tech.uom.lib/uom-lib-jackson
	implementation 'tech.uom.lib:uom-lib-jackson:2.1'

	implementation 'org.apache.commons:commons-lang3:3.12.0'
	implementation 'org.apache.commons:commons-compress:1.23.0'
	implementation 'org.apache.commons:commons-csv:1.10.0'
	implementation 'org.apache.commons:commons-io:1.3.2'
	implementation 'commons-codec:commons-codec:1.16.0'
	implementation 'org.apache.tika:tika-core:2.8.0'

	implementation 'uk.org.okapibarcode:okapibarcode:0.4.0'

	/*
	Test Dependencies
	 */
	testImplementation group: 'io.quarkus', name: 'quarkus-junit5'
	testImplementation group: 'io.quarkus', name: 'quarkus-jacoco' // https://quarkus.io/guides/tests-with-coverage
	testImplementation group: 'io.rest-assured', name: 'rest-assured'
	testImplementation 'net.datafaker:datafaker:2.0.1'
	testImplementation 'org.assertj:assertj-core:3.24.2'

//	testImplementation 'com.github.dasniko:testcontainers-keycloak:2.5.0'
	//2.1.2 seems dud, fails to start & null pointers
//	testImplementation 'org.keycloak:keycloak-admin-client:21.1.1'
	// 17.0.1 seems dud, might be related to keycloak issue
	testImplementation 'io.jaegertracing:jaeger-testcontainers:0.7.0'

	testImplementation 'org.seleniumhq.selenium:selenium-java:4.10.0'
	testImplementation 'org.testcontainers:selenium:1.18.3'
	testImplementation 'com.deque:axe-selenium:3.0'
}
```

This seems to happen more often when I pass a custom realm to keycloak, which is fairly odd to me. The keycloak container seems to start when these errors occur, but the other 50% keycloak fails to start but this error is not present (but keycloak not being present is obviously an issue). Actually, looks like when this error doesn't occur, all deservices are not present in Docker...

### Output of `java -version`

17

### Quarkus version or git rev

2.16.8 and 3.2.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by GregJohnStewart** [comment]
Just updated my codebase to `3.2.3`, same issue...

**Comment by geoand** [comment]
@GregJohnStewart would you be able to attach a sample application that behaves as you mention? I would like to have a quick look in case there is some real problem lurking here.

Thanks

**Comment by geoand** [comment]
Closing for lack of feedback
