### ISSUE TITLE
java.util.NoSuchElementException when using jakarta.validation.*

### ISSUE THREAD

**Issue by ghost81** [quarkusio/quarkus#35294]
### Describe the bug

We have a project based on GraphQLApi.  
We are also using Hibernate Validators to validate our `@Entity`s

After this commit: https://github.com/quarkusio/quarkus/commit/a66c8b45884f91e0ee814a6672554f31c22bdef9
our system is not functional anymore.  
Here is the stacktrace that we get no matter if we use default validator (@Min, @Max, @NotBlank) or any custom validator:
```
java.util.NoSuchElementException
	at java.base/java.util.ArrayList$SubList$1.next(ArrayList.java:1301)
	at io.smallrye.graphql.validation.BeanValidationUtil$RequestNodeBuilder.build(BeanValidationUtil.java:49)
	at io.smallrye.graphql.validation.BeanValidationUtil.lambda$addConstraintViolationsToDataFetcherResult$0(BeanValidationUtil.java:30)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.smallrye.graphql.validation.BeanValidationUtil.addConstraintViolationsToDataFetcherResult(BeanValidationUtil.java:31)
	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusDefaultDataFetcher.lambda$invokeAndTransformBlocking$0(QuarkusDefaultDataFetcher.java:98)
	at io.smallrye.context.impl.wrappers.SlowContextualCallable.call(SlowContextualCallable.java:21)
	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.BlockingHelper.lambda$runBlocking$0(BlockingHelper.java:30)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589) 
```
After some debugging I noticed that in io.smallrye.graphql.validation.BeanValidationUtil.RequestNodeBuilder.build method
in this peace of code:
```
return asList(
                    methodNode(violationNodes.next()),
                    requestedArgument(violationNodes.next()));
```
`violationNodes` contains just one element - the field which were validated and the second `.next()` statement throws this exception.  

We are initializing the validator in the service layer this way
```
protected Validator getValidator() {
        if (validator == null) {
            validator = Validation.buildDefaultValidatorFactory().getValidator();
        }
        return validator;
    }
```

and use a general method for `Entity`s validation
```
protected void validate(E entity) {
        var violations = getValidator().validate(entity);
        if (!violations.isEmpty()) {
            throw new ConstraintViolationException("Execution error!", violations);
        }
    }
```
This is somehow a regression since our code is fully functional with version 3.0.*

IMO, `ConstraintViolationException` could be thrown from many places, not just from GraphQL layer, so the processing of the exception should be tuned somehow

### Expected behavior

System should not throw an exception

### Actual behavior

System trows an exception

### Output of `uname -a` or `ver`

Linux 6.4.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023 16:02:01 +0000 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM Zulu19.32+13-CA (build 19.0.2+7, mixed mode, sharing)

### Quarkus version or git rev

3.1+

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2.1

**Comment by jmartisk** [comment]
Hi, I think I'll need some more info about how you application works, I don't know how to reproduce this. An executable reproducer would be best...
I'm not sure how to understand the `getValidator()` and `validate(E entity)` code that you posted - does this mean you don't rely on Hibernate Validator's interceptor to do the validation, but you have some custom logic for it? That might be related to the failure, but I'll need more details.
The smallrye-graphql code was changed a bit so that it doesn't throw any `ConstraintViolationException` by itself anymore, it only catches the one thrown by HV and appends the violation metadata into the response.

**Comment by geoand** [comment]
Closing for lack of feedback
