### ISSUE TITLE
ResteasyReactiveRuntimeRecorder throws ClassCastException when deployed on Openshift

### ISSUE THREAD

**Issue by mocenas** [quarkusio/quarkus#35344]
### Describe the bug

Related to PR #35246 
When deploying RestEasy Reactive application to Openshift, it will fail on ResteasyReactiveRuntimeRecorder's ClassCastException (see stack trace below). 
```
15:47:36,238 INFO  [app] 13:47:35,438 Failed to start application (with profile [OpenShiftCompressionHandlerIT]): java.lang.RuntimeException: Failed to start quarkus
15:47:36,238 INFO  [app] 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
15:47:36,238 INFO  [app] 	at io.quarkus.runtime.Application.start(Application.java:101)
15:47:36,238 INFO  [app] 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
15:47:36,238 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
15:47:36,238 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
15:47:36,238 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
15:47:36,239 INFO  [app] 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
15:47:36,239 INFO  [app] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:47:36,239 INFO  [app] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
15:47:36,239 INFO  [app] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:47:36,239 INFO  [app] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
15:47:36,239 INFO  [app] 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
15:47:36,239 INFO  [app] 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
15:47:36,239 INFO  [app] Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
15:47:36,239 INFO  [app] 	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRuntimeRecorder.runtimeConfiguration(ResteasyReactiveRuntimeRecorder.java:38)
15:47:36,240 INFO  [app] 	at io.quarkus.deployment.steps.ResteasyReactiveProcessor$runtimeConfiguration1462480334.deploy_0(Unknown Source)
15:47:36,240 INFO  [app] 	at io.quarkus.deployment.steps.ResteasyReactiveProcessor$runtimeConfiguration1462480334.deploy(Unknown Source)
15:47:36,240 INFO  [app] 	... 13 more
```
Seems like issue is on [this line](https://github.com/quarkusio/quarkus/blob/42cd3eac552ee5102033f7f7de7acc3ec90a75d3/extensions/resteasy-reactive/quarkus-resteasy-reactive/runtime/src/main/java/io/quarkus/resteasy/reactive/server/runtime/ResteasyReactiveRuntimeRecorder.java#L38). Somehow produces `String` ,while expected is `List<String>`.

Reverting #35246 fixes this issue.

### Expected behavior

RestEasy Reactive application will deploy

### Actual behavior

RestEasy Reactive application fails to deploy, with above-mention exception.

**Comment by mocenas** [comment]
cc @gsmet @radcortez

**Comment by michalvavrik** [comment]
Hey @geoand @Sgitario it's not just OpenShift, even baremetal JVM and native fails https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/5881025521/job/15950020046?pr=1365

**Comment by Sgitario** [comment]
Thanks for reporting! https://github.com/quarkusio/quarkus/pull/35396 should fix this.

**Comment by gsmet** [comment]
Nice catch.

**Comment by gsmet** [comment]
And nice bug report :).
