### ISSUE TITLE
Do not print stack-trace in WebSocketLogHandler.recordHistory

### ISSUE THREAD

**Issue by JanWiemer** [quarkusio/quarkus#35340]
### Describe the bug

Similar to #32203:

```
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.ReentrantLock$Sync.lockInterruptibly(ReentrantLock.java:159)
        at java.base/java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:372)
        at java.base/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:432)
        at io.quarkus.vertx.http.runtime.logstream.WebSocketLogHandler.recordHistory(WebSocketLogHandler.java:66)
        at io.quarkus.vertx.http.runtime.logstream.WebSocketLogHandler.doPublish(WebSocketLogHandler.java:39)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:327)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
```

The stacktrace should not be printed to the console by default in io.quarkus.vertx.http.runtime.logstream.WebSocketLogHandler.recordHistory:

```java
    private void recordHistory(final ExtLogRecord record) {
        synchronized (this) {
            try {
                if (history.remainingCapacity() == 0) {
                    history.take();
                }
                history.add(record);
            } catch (InterruptedException ex) {
                ex.printStackTrace(); // <------- REMOVE THIS
                Thread.currentThread().interrupt();
            }
        }
    }
```
 

### Expected behavior

No stacktrace in console logging

### Actual behavior

stacktrace is printed on console

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10) OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

### Quarkus version or git rev

3.2.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.2.1

**Comment by JanWiemer** [comment]
related to #25359

**Comment by brunobat** [comment]
@JanWiemer looks like this is not related with tracing (like in OpenTelemetry tracing) but with vert.x. Correct?

**Comment by JanWiemer** [comment]
Yes, I think so. I found the class (WebSocketLogHandler) on the Quarkus 3.2.4 branch. However on main branch it seems to be gone...

**Comment by geoand** [comment]
With #35164 this is no longer relevant. 

However, @phillip-kruger it would probably make sense to remove printing the stacktrace in the `3.2` branch

**Comment by phillip-kruger** [comment]
Yea that was part of the old Dev UI, that has now been removed.
