### ISSUE TITLE
QuarkusTestExtension does not support -ntp in Maven 3.6.1

### ISSUE THREAD

**Issue by jglick** [quarkusio/quarkus#3539]
**Describe the bug**

If I run Maven commands using `-ntp`, an option added in Maven 3.6.1, I get an error during Quarkus tests.

**Expected behavior**

Just runs.

**Actual behavior**

The test crashes with

```
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class […]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:298)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:273)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:70)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:256)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:250)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:249)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:29)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:106)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:105)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.ExceptionInInitializerError
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:118)
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:56)
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver$Builder.build(MavenArtifactResolver.java:101)
	at io.quarkus.bootstrap.BootstrapClassLoaderFactory.newDeploymentClassLoader(BootstrapClassLoaderFactory.java:314)
	at io.quarkus.test.junit.QuarkusTestExtension.createQuarkusBuildClassLoader(QuarkusTestExtension.java:291)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:78)
	at io.quarkus.test.junit.QuarkusTestExtension.createTestInstance(QuarkusTestExtension.java:343)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:283)
	... 49 more
Caused by: java.lang.IllegalStateException: Failed to parse Maven command line arguments
	at io.quarkus.bootstrap.resolver.maven.MavenRepoInitializer.<clinit>(MavenRepoInitializer.java:101)
	... 57 more
Caused by: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -ntp
	at org.apache.commons.cli.Parser.processOption(Parser.java:383)
	at org.apache.commons.cli.Parser.parse(Parser.java:210)
	at org.apache.commons.cli.Parser.parse(Parser.java:88)
	at org.apache.maven.cli.CLIManager.parse(CLIManager.java:159)
	at io.quarkus.bootstrap.resolver.maven.MavenRepoInitializer.<clinit>(MavenRepoInitializer.java:99)
	... 57 more
```

**To Reproduce**

Given a sample app,

```bash
DOCKER_BUILDKIT=1 docker build --progress plain -f src/main/docker/Dockerfile.test -t test .
```

```Dockerfile
# syntax=docker/dockerfile:1.1.1-experimental
FROM quay.io/quarkus/centos-quarkus-maven:19.1.1
COPY src /project/src
COPY pom.xml /project
USER root
RUN cp -rv ~quarkus/.m2 ~root/.m2
RUN --mount=type=cache,target=/root/.m2/repository,sharing=private mvn -f /project -ntp package
```

crashes. If `-ntp` is removed, the build works.

**Environment**

Ubuntu, Docker 19.03.1

**Additional context**

I suspect https://github.com/quarkusio/quarkus/blob/08180a306b88e010ac54c44dddbd01d8ad7569ac/independent-projects/bootstrap/pom.xml#L29 is to blame here.

**Comment by geoand** [comment]
@aloubyansky does this seem like something that should be fixed in bootstrap?

**Comment by aloubyansky** [comment]
Yes, definitely.

**Comment by rsvoboda** [comment]
@aloubyansky How is https://github.com/quarkusio/quarkus/pull/5464 connected to this ?

**Comment by aloubyansky** [comment]
#5464 isolated certain parts of Bootstrap's maven artifact resolver initialization (including command line parsing) by loading classes directly from the Maven's lib directory if `maven.home` property is set (which is set the Maven build process). Otherwise, it expects the necessary Maven API and impl to be on the classpath.
I've been working on a general approach to enable initialization of all Maven resolver parts from the Maven home dir unless they are present on the classpath before the New Year. This would solve this and other related issues. I've got it mostly working but stumbled upon a few conflicts when mixing various Maven versions. Not sure I'll continue that effort, tbh.

A simple fix for this issue would be to just update the bootstrap's deps on the latest Maven version (given that it is backward compatible). And we should probably add `maven.home` property to our project templates, as mentioned previously.

**Comment by rsvoboda** [comment]
> A simple fix for this issue would be to just update the bootstrap's deps on the latest Maven version (given that it is backward compatible). And we should probably add maven.home property to our project templates, as mentioned previously.

Is it something you will discuss with wider team or you will just create PRs for it ?

**Comment by aloubyansky** [comment]
I briefly mentioned that to @gsmet at the f2f, he thought it made sense.
