### ISSUE TITLE
SubjectSubstitution.java uses org.graalvm.home.Version

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#35507]
### Describe the bug

The `kafka-client` extension uses `org.graalvm.home.Version` class which is no longer available in GraalVM for JDK 21 (internal version 23.1). It looks like the substitution is only being applied for a GraalVM version `< 22.1` and the minimum supported version is `22.3`. So it appears that substitution can just get removed?

We see the following native image failure due to `SubjectSubstitution` with `23.1`:

```
[1/8] Initializing...                                                                                    (0.0s @ 0.16GB)
------------------------------------------------------------------------------------------------------------------------
                        1.1s (10.9% of total time) in 21 GCs | Peak RSS: 0.60GB | CPU load: 1.85
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/runner/work/mandrel/mandrel/quarkus/integration-tests/reactive-messaging-kafka/target/quarkus-integration-test-reactive-messaging-kafka-999-SNAPSHOT-native-image-source-jar/svm_err_b_20230823T015620.525_pid2999.md (build_info)
========================================================================================================================
Failed generating 'quarkus-integration-test-reactive-messaging-kafka-999-SNAPSHOT-runner' after 9.1s.

The build process encountered an unexpected error:

java.lang.NoClassDefFoundError: org/graalvm/home/Version
	at io.quarkus.kafka.client.runtime.graal.Target_javax_security_auth_Subject$Graal22_0OrEarlier.getAsBoolean(SubjectSubstitution.java:111)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1057)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:373)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:351)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:1030)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:908)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:591)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:551)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:529)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:711)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
Caused by: java.lang.ClassNotFoundException: org.graalvm.home.Version
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 12 more
```

See also:
https://github.com/graalvm/mandrel/actions/runs/5945859580/job/16126064721#step:12:931

**Comment by jerboaa** [comment]
With GraalVM `23.1`, class `org.graalvm.home.Version` is being provided by the `polyglot.jar` which we shouldn't depend on.

**Comment by jerboaa** [comment]
> But I agree we can remove this substitution. Will you do it or should I?

Please go ahead and remove it.

**Comment by gsmet** [comment]
@jerboaa I created https://github.com/quarkusio/quarkus/pull/35535
