### ISSUE TITLE
WebSocket ITs failure 

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#3558]
**Describe the bug**
`integrations-test/main` are failing with the following NPE message:
```
2019-08-18 18:05:42,116 ERROR [io.und.request] (executor-thread-2) UT005071: Undertow request failed HttpServerExchange{ GET /echo delegate io.undertow.vertx.VertxHttpExchange@72cf6608}: java.lang.NullPointerException
	at io.undertow.vertx.VertxHttpExchange.writeAsync0(VertxHttpExchange.java:454)
	at io.undertow.httpcore.HttpExchangeBase.writeAsync(HttpExchangeBase.java:222)
	at io.undertow.httpcore.HttpExchangeBase.endExchange(HttpExchangeBase.java:177)
	at io.undertow.server.HttpServerExchange.endExchange(HttpServerExchange.java:1180)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:315)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:665)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```
**Expected behavior**
build to succeed
**Actual behavior**
build failure

**To Reproduce**
1. `cd integration-tests/main`
2. `mvn clean install`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: macOs
 - Output of `java -version`: N/A
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: `master`

**Comment by machi1990** [comment]
Windows CI failures for the following PRs seem to be related:
- https://github.com/quarkusio/quarkus/pull/3557,
- https://github.com/quarkusio/quarkus/pull/3556
- https://github.com/quarkusio/quarkus/pull/3428

**Comment by geoand** [comment]
Yup, I have been seeing flakiness in CI since yesterday

**Comment by machi1990** [comment]
I have prepared PR - https://github.com/quarkusio/quarkus-http/pull/2 in attempt to fix the issue. 

/cc @stuartwdouglas @gsmet @geoand
