### ISSUE TITLE
AWS Lambda Quarkus tutorial results in java.lang.NoClassDefFoundError of org/eclipse/microprofile/config/spi/ConfigSource

### ISSUE THREAD

**Issue by typekpb** [quarkusio/quarkus#35584]
### Describe the bug

Following official docs for AWS Lambda: https://quarkus.io/guides/aws-lambda-http results in error on local run.

Running:

```
mvn archetype:generate \
       -DarchetypeGroupId=io.quarkus \
       -DarchetypeArtifactId=quarkus-amazon-lambda-http-archetype \
       -DarchetypeVersion=3.3.0
```
having sample vals:
```
Confirm properties configuration:
groupId: test
artifactId: test
version: 1.0-SNAPSHOT
package: test
```
afterwards building using:
```
mvn install
```
and running lambda locally using:
```
sam local start-api --template target/sam.jvm.yaml
```

once accessing the URL: http://127.0.0.1:3000/hello

results in error:
```
{
errorMessage: "org/eclipse/microprofile/config/spi/ConfigSource",
errorType: "java.lang.NoClassDefFoundError"
}
```

### Expected behavior

http://127.0.0.1:3000/hello

should result in:
```
hello jaxrs
```

### Actual behavior

http://127.0.0.1:3000/hello

results in error:
```
{
errorMessage: "org/eclipse/microprofile/config/spi/ConfigSource",
errorType: "java.lang.NoClassDefFoundError"
}
```

### How to Reproduce?

see above

### Output of `uname -a` or `ver`

Darwin Peters-MBP 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.8" 2023-07-18 LTS OpenJDK Runtime Environment Corretto-17.0.8.7.1 (build 17.0.8+7-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.8.7.1 (build 17.0.8+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.3.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9) Maven home: /opt/homebrew/Cellar/maven/3.9.4/libexec Java version: 17.0.8, vendor: Amazon.com Inc., runtime: /Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home Default locale: en_SK, platform encoding: UTF-8 OS name: "mac os x", version: "13.4.1", arch: "aarch64", family: "mac"

### Additional information

for local run, using SAM:
```
sam --version
SAM CLI, version 1.61.0
```
and podman:
```
podman --version
podman version 4.6.1
```

detailed error msg in console:
```
28 Aug 2023 04:00:42,553 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 1 InvokeID=
org/eclipse/microprofile/config/spi/ConfigSource: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/eclipse/microprofile/config/spi/ConfigSource
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
        at java.base/java.net.URLClassLoader$1.run(Unknown Source)
        at java.base/java.net.URLClassLoader$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.eclipse.microprofile.config.spi.ConfigSource. Current classpath: file:/var/task/:file:/var/task/lib/com.aayushatharva.brotli4j.brotli4j-1.12.0.jar:file:/var/task/lib/com.aayushatharva.brotli4j.native-osx-aarch64-1.12.0.jar:file:/var/task/lib/com.aayushatharva.brotli4j.service-1.12.0.jar:file:/var/task/lib/com.amazonaws.aws-lambda-java-core-1.2.2.jar:file:/var/task/lib/com.amazonaws.aws-lambda-java-events-3.11.2.jar:file:/var/task/lib/com.fasterxml.jackson.core.jackson-annotations-2.15.2.jar:file:/var/task/lib/com.fasterxml.jackson.core.jackson-core-2.15.2.jar:file:/var/task/lib/com.fasterxml.jackson.core.jackson-databind-2.15.2.jar:file:/var/task/lib/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.15.2.jar:file:/var/task/lib/com.fasterxml.jackson.datatype.jackson-datatype-joda-2.15.2.jar:file:/var/task/lib/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.15.2.jar:file:/var/task/lib/com.fasterxml.jackson.module.jackson-module-parameter-names-2.15.2.jar:file:/var/task/lib/com.ibm.async.asyncutil-0.1.0.jar:file:/var/task/lib/io.github.crac.org-crac-0.1.3.jar:file:/var/task/lib/io.netty.netty-buffer-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-codec-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-codec-dns-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-codec-haproxy-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-codec-http-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-codec-http2-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-codec-socks-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-common-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-handler-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-handler-proxy-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-resolver-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-resolver-dns-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-transport-4.1.94.Final.jar:file:/var/task/lib/io.netty.netty-transport-native-unix-common-4.1.94.Final.jar:file:/var/task/lib/io.quarkus.arc.arc-3.3.0.jar:file:/var/task/lib/io.quarkus.http.quarkus-http-core-5.0.2.Final.jar:file:/var/task/lib/io.quarkus.http.quarkus-http-http-core-5.0.2.Final.jar:file:/var/task/lib/io.quarkus.http.quarkus-http-servlet-5.0.2.Final.jar:file:/var/task/lib/io.quarkus.http.quarkus-http-vertx-backend-5.0.2.Final.jar:file:/var/task/lib/io.quarkus.quarkus-amazon-lambda-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-amazon-lambda-common-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-amazon-lambda-http-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-arc-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-bootstrap-runner-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-core-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-credentials-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-development-mode-spi-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-fs-util-0.0.9.jar:file:/var/task/lib/io.quarkus.quarkus-funqy-http-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-funqy-server-common-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-jackson-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-mutiny-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-netty-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-reactive-routes-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-resteasy-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-resteasy-common-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-resteasy-server-common-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-security-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-security-runtime-spi-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-smallrye-context-propagation-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-undertow-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-vertx-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-vertx-http-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-vertx-http-dev-console-runtime-spi-3.3.0.jar:file:/var/task/lib/io.quarkus.quarkus-vertx-latebound-mdc-provider-3.3.0.jar:file:/var/task/lib/io.quarkus.security.quarkus-security-2.0.2.Final.jar:file:/var/task/lib/io.smallrye.common.smallrye-common-annotation-2.1.0.jar:file:/var/task/lib/io.smallrye.common.smallrye-common-classloader-2.1.0.jar:file:/var/task/lib/io.smallrye.common.smallrye-common-constraint-2.1.0.jar:file:/var/task/lib/io.smallrye.common.smallrye-common-expression-2.1.0.jar:file:/var/task/lib/io.smallrye.common.smallrye-common-function-2.1.0.jar:file:/var/task/lib/io.smallrye.common.smallrye-common-io-2.1.0.jar:file:/var/task/lib/io.smallrye.common.smallrye-common-os-2.1.0.jar:file:/var/task/lib/io.smallrye.common.smallrye-common-vertx-context-2.1.0.jar:file:/var/task/lib/io.smallrye.config.smallrye-config-3.3.3.jar:file:/var/task/lib/io.smallrye.config.smallrye-config-common-3.3.3.jar:file:/var/task/lib/io.smallrye.config.smallrye-config-core-3.3.3.jar:file:/var/task/lib/io.smallrye.reactive.mutiny-2.3.1.jar:file:/var/task/lib/io.smallrye.reactive.mutiny-smallrye-context-propagation-2.3.1.jar:file:/var/task/lib/io.smallrye.reactive.smallrye-mutiny-vertx-auth-common-3.5.0.jar:file:/var/task/lib/io.smallrye.reactive.smallrye-mutiny-vertx-bridge-common-3.5.0.jar:file:/var/task/lib/io.smallrye.reactive.smallrye-mutiny-vertx-core-3.5.0.jar:file:/var/task/lib/io.smallrye.reactive.smallrye-mutiny-vertx-runtime-3.5.0.jar:file:/var/task/lib/io.smallrye.reactive.smallrye-mutiny-vertx-uri-template-3.5.0.jar:file:/var/task/lib/io.smallrye.reactive.smallrye-mutiny-vertx-web-3.5.0.jar:file:/var/task/lib/io.smallrye.reactive.smallrye-mutiny-vertx-web-common-3.5.0.jar:file:/var/task/lib/io.smallrye.reactive.vertx-mutiny-generator-3.5.0.jar:file:/var/task/lib/io.smallrye.smallrye-context-propagation-api-2.1.0.jar:file:/var/task/lib/io.smallrye.smallrye-context-propagation-storage-2.1.0.jar:file:/var/task/lib/io.smallrye.smallrye-fault-tolerance-vertx-6.2.6.jar:file:/var/task/lib/io.vertx.vertx-auth-common-4.4.4.jar:file:/var/task/lib/io.vertx.vertx-bridge-common-4.4.4.jar:file:/var/task/lib/io.vertx.vertx-codegen-4.4.4.jar:file:/var/task/lib/io.vertx.vertx-uri-template-4.4.4.jar:file:/var/task/lib/io.vertx.vertx-web-4.4.4.jar:file:/var/task/lib/io.vertx.vertx-web-common-4.4.4.jar:file:/var/task/lib/jakarta.activation.jakarta.activation-api-2.1.2.jar:file:/var/task/lib/jakarta.annotation.jakarta.annotation-api-2.1.1.jar:file:/var/task/lib/jakarta.el.jakarta.el-api-5.0.1.jar:file:/var/task/lib/jakarta.enterprise.jakarta.enterprise.cdi-api-4.0.1.jar:file:/var/task/lib/jakarta.enterprise.jakarta.enterprise.lang-model-4.0.1.jar:file:/var/task/lib/jakarta.inject.jakarta.inject-api-2.0.1.jar:file:/var/task/lib/jakarta.interceptor.jakarta.interceptor-api-2.1.0.jar:file:/var/task/lib/jakarta.servlet.jakarta.servlet-api-6.0.0.jar:file:/var/task/lib/jakarta.transaction.jakarta.transaction-api-2.0.1.jar:file:/var/task/lib/jakarta.validation.jakarta.validation-api-3.0.2.jar:file:/var/task/lib/jakarta.ws.rs.jakarta.ws.rs-api-3.1.0.jar:file:/var/task/lib/jakarta.xml.bind.jakarta.xml.bind-api-4.0.0.jar:file:/var/task/lib/joda-time.joda-time-2.10.14.jar:file:/var/task/lib/modified-io.smallrye.smallrye-context-propagation-2.1.0.jar:file:/var/task/lib/modified-io.vertx.vertx-core-4.4.4.jar:file:/var/task/lib/org.eclipse.angus.angus-activation-2.0.1.jar:file:/var/task/lib/org.eclipse.microprofile.config.microprofile-config-api-3.0.3.jar:file:/var/task/lib/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.3.jar:file:/var/task/lib/org.eclipse.microprofile.jwt.microprofile-jwt-auth-api-2.1.jar:file:/var/task/lib/org.jboss.logging.jboss-logging-3.5.1.Final.jar:file:/var/task/lib/org.jboss.logging.jboss-logging-annotations-2.2.1.Final.jar:file:/var/task/lib/org.jboss.logmanager.jboss-logmanager-embedded-1.1.1.jar:file:/var/task/lib/org.jboss.resteasy.microprofile.microprofile-config-2.1.1.Final.jar:file:/var/task/lib/org.jboss.resteasy.resteasy-cdi-6.2.4.Final.jar:file:/var/task/lib/org.jboss.resteasy.resteasy-core-6.2.4.Final.jar:file:/var/task/lib/org.jboss.resteasy.resteasy-core-spi-6.2.4.Final.jar:file:/var/task/lib/org.jboss.slf4j.slf4j-jboss-logmanager-2.0.0.Final.jar:file:/var/task/lib/org.jboss.threads.jboss-threads-3.5.0.Final.jar:file:/var/task/lib/org.jboss.weld.weld-api-5.0.SP2.jar:file:/var/task/lib/org.reactivestreams.reactive-streams-1.0.4.jar:file:/var/task/lib/org.slf4j.slf4j-api-2.0.6.jar:file:/var/task/lib/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar

```

**Comment by gsmet** [comment]
I went through the steps described here and all is fine with 3.17.5.
