### ISSUE TITLE
Native mode ++ websockets ++ Vert.x based http layer failure

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#3562]
I see failure for native mode ++ websockets ++ Vert.x based http layer 
Using Quarkus master  3d86ef180 - (HEAD -> master, upstream/master, origin/master, origin/HEAD) Merge pull request #3506 from stuartwdouglas/quakus-http (2 days ago) <Jason T. Greene>

Issue found via Quarkus quickstart `using-websockets`.

JVM mode test passed.

Native mode test failed with following stacktrace:
```
[INFO] Running org.acme.websocket.ChatITCase
Executing [/Users/rsvoboda/git/quarkus-quickstarts/using-websockets/target/using-websockets-1.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
2019-08-19 08:49:47,739 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.010s. Listening on: http://0.0.0.0:8081
2019-08-19 08:49:47,739 INFO  [io.quarkus] (main) Installed features: [cdi, undertow-websockets, vertx, vertx-web]
Aug 19, 2019 8:49:47 AM io.undertow.websockets.jsr.ServerWebSocketContainer addEndpointInternal
INFO: UT026004: Adding annotated client endpoint class org.acme.websocket.ChatTestCase$Client
2019-08-19 08:49:48,188 ERROR [io.und.request] (executor-thread-1) UT005071: Undertow request failed HttpServerExchange{ GET /chat/stu delegate io.undertow.vertx.VertxHttpExchange@10c055b18}: java.lang.NullPointerException
	at io.undertow.vertx.VertxHttpExchange.writeAsync0(VertxHttpExchange.java:452)
	at io.undertow.httpcore.HttpExchangeBase.writeAsync(HttpExchangeBase.java:222)
	at io.undertow.httpcore.HttpExchangeBase.endExchange(HttpExchangeBase.java:177)
	at io.undertow.server.HttpServerExchange.endExchange(HttpServerExchange.java:1180)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:315)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:665)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.671 s <<< FAILURE! - in org.acme.websocket.ChatITCase
[ERROR] testWebsocketChat  Time elapsed: 10.404 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <User stu joined> but was: <null>
```

**Comment by machi1990** [comment]
Duplicate of https://github.com/quarkusio/quarkus/issues/3558

**Comment by rsvoboda** [comment]
@machi1990 thanks, you saw that in JVM mode ? I'm seeing it only in native mode ...

**Comment by machi1990** [comment]
Yes I saw them in JVM mode too.
