### ISSUE TITLE
Support required values for parameter expansion

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#35669]
### Description

Currently, `Quarkus` supports parameter expansion for environment variables. Direct substitutions (e.g.: `${DATABASE_JDBC_URL}`) works as expected, even when default values are specified: `${DATABASE_JDBC_URL:-fail_when_not_present}`.

It will be quite convenient to have a syntax to **define required values**. For example, something similar to [what `Docker` provides](https://docs.docker.com/compose/environment-variables/env-file/#parameter-expansion): `${DATABASE_JDBC_URL:?error}` — value of `DATABASE_JDBC_URL` must be set and non-empty, otherwise exit with error.

### Implementation ideas

I think implementing this in the same way `Docker` currently behaves is a big plus because most developers are already familiar with the syntax.

**Comment by radcortez** [comment]
Expressions are already required. For instance if I try:

```java
@ConfigMapping(prefix = "foo")
public interface Foo {
    String bar();
}
```

```properties
foo.bar=${baz}
```

I get:

```console
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.util.NoSuchElementException: SRCFG00011: Could not expand value baz in property foo.bar
	at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:1001)
	at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:961)
	at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:961)
	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:91)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:647)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	... 13 more
```

**Comment by x80486** [comment]
The issue is for something different. If I have a certain property set in `application.yaml` to be set from an environment variable (no fallback), and the environment variable is not set, there is currently no way to fail the startup process — basically enforcing certain values to be set.

This behavior is currently implemented in `Docker`, so the issue was about that.

**Comment by radcortez** [comment]
> The issue is for something different. If I have a certain property set in `application.yaml` to be set from an environment variable (no fallback), and the environment variable is not set, there is currently no way to fail the startup process — basically enforcing certain values to be set.

Maybe I'm not understanding properly what you mean, but I believe we have the behavior you expect:

```java
@ConfigMapping(prefix = "foo")
public interface Foo {
    String bar();
}
```

```yaml
foo:
  bar: ${BAZ}
```

When you run you get a `Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.util.NoSuchElementException: SRCFG00011: Could not expand value BAZ in property foo.bar`:

```console
java -jar target/quarkus-app/quarkus-run.jar
Oct 02, 2023 3:12:09 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile [prod])
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.util.NoSuchElementException: SRCFG00011: Could not expand value BAZ in property foo.bar
	at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:1001)
	at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:961)
	at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:961)
	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:91)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:647)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	... 13 more
```

If you set the env var:

```console
🌀 export BAZ=x
🌀 java -jar target/quarkus-app/quarkus-run.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-10-02 15:14:00,265 INFO  [io.quarkus] (main) config-playground 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.4.1) started in 0.913s. Listening on: http://0.0.0.0:8080
2023-10-02 15:14:00,273 INFO  [io.quarkus] (main) Profile prod activated.
2023-10-02 15:14:00,273 INFO  [io.quarkus] (main) Installed features: [cdi, config-yaml, resteasy-reactive, smallrye-context-propagation, vertx]
```

So if the Env var is not set, you get the "fail to start the process"; if it is set, it starts as expected.

**Comment by radcortez** [comment]
If this is not what you expect, can you please detail with more clarity, with examples and even a reproducer if possible? Thanks!

**Comment by x80486** [comment]
To reproduce what I described, have a project with an `application.yaml` file, and for instance, a datasource configuration:

```yaml
quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
```

Have a `.env` file with `DATASOURCE_URL` and `DATASOURCE_USERNAME` declared and set. Start the application.

Remove `DATASOURCE_URL` and/or `DATASOURCE_USERNAME` from `.env`, start the application again — I would expect a failure at this point.

Same behavior occurs with `prod` profile — which doesn't use the `.env` file.

If `Quarkus` could support something like `${DATASOURCE_URL:?error}` (like `Docker`) this could be prevented.

**Comment by radcortez** [comment]
It doesn't work for these properties because they are set as Optional, so the Config system does not require a configuration to be set. Each Quarkus extension should be responsible for what they require (or not) and ideally, users should not be required to do that management manually.

While it could work if we add such feature to the expression mechanism, it looks to me to be mostly a workaround to override the configuration definitions set by Quarkus.

//cc @yrodiere

**Comment by radcortez** [comment]
> @radcortez I must admit I find this behavior strange as well. I wouldn't have expected environment variable resolution to work differently depending on the property it is resolved for. Though I suppose this must enable some nice features.

There is no difference; it works the same. The issue is that an expression expanded to an Optional property does not give you an error because it is acceptable not to have configurations for such cases. If you try to expand a regular property, you get the expected mandatory error.

> I don't know what to say, those properties _are_ optional for a number of reasons (reactive doesn't use JDBC urls, devmode doesn't require a JDBC url, ...).

If these are supposed to be Optional, I'm fine with that. I just think that adding another config construct to workaround a mandatory / optional property is not a good solution. And this will only work if you use expressions.

**Comment by yrodiere** [comment]
> > @radcortez I must admit I find this behavior strange as well. I wouldn't have expected environment variable resolution to work differently depending on the property it is resolved for. Though I suppose this must enable some nice features.
> 
> There is no difference; it works the same. The issue is that an expression expanded to an Optional property does not give you an error because it is acceptable not to have configurations for such cases. If you try to expand a regular property, you get the expected mandatory error.

But the error in your example was "Could not expand value BAZ"... Which has nothing to do with the property being required?

I feel I'm missing some critical piece of information here.
