### ISSUE TITLE
Qute extension conflict Redis-cache extension  cause Deployment build time failed

### ISSUE THREAD

**Issue by leotu** [quarkusio/quarkus#35680]
### Describe the bug

Mailer extension include Qute extension library that raise Build step failed

```txt
Unable to determine the value type for 'qute-cache' Redis cache. An appropriate configuration value for 'quarkus.cache.redis.qute-cache.value-type' needs to be set
```

pom.xml

```xml
<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-mailer</artifactId>
</dependency>

<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-redis-cache</artifactId>
</dependency>
```

- Error StackTrace

```java
2023-09-01 17:28:47,798 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.cache.redis.deployment.RedisCacheProcessor#determineValueTypes threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Unable to determine the value type for 'qute-cache' Redis cache. An appropriate configuration value for 'quarkus.cache.redis.qute-cache.value-type' needs to be set
	at io.quarkus.cache.redis.deployment.RedisCacheProcessor.determineValueTypes(RedisCacheProcessor.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:336)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:253)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:82)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:423)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.cache.redis.deployment.RedisCacheProcessor#determineValueTypes threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Unable to determine the value type for 'qute-cache' Redis cache. An appropriate configuration value for 'quarkus.cache.redis.qute-cache.value-type' needs to be set
	at io.quarkus.cache.redis.deployment.RedisCacheProcessor.determineValueTypes(RedisCacheProcessor.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:332)
	... 9 more
Caused by: jakarta.enterprise.inject.spi.DeploymentException: Unable to determine the value type for 'qute-cache' Redis cache. An appropriate configuration value for 'quarkus.cache.redis.qute-cache.value-type' needs to be set
	at io.quarkus.cache.redis.deployment.RedisCacheProcessor.determineValueTypes(RedisCacheProcessor.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

How set set the value or RedisCacheProcessor automatically skip it ?

'quarkus.cache.redis.qute-cache.value-type'

```yaml
quarkus:
  cache:
    #caffeine:
    # qute-cache:
    #    value-type: xxx

    redis:
      qute-cache:
        value-type: ???
```

### Actual behavior

https://quarkus.io/guides/qute-reference#cached-section

howt to resolve it ?

1.  specify cache Implementation ?
2. disable template cache ?
3. mailer execlude qute ?
4. or ...

### Output of `java -version`

JDK 17.0.4.1

### Quarkus version or git rev

3.2.4.Final

### Additional information

"qute-cache" from io.quarkus.qute.cache.QuteCache.java

```java
package io.quarkus.qute.cache;

public final class QuteCache {

    /**
     * The name of the cache used to cache parts of templates
     */
    public static final String NAME = "qute-cache";

}
```

**Comment by leotu** [comment]
Exclusion can't solve

```xml
<dependency>
   <groupId>io.quarkus</groupId>
   <artifactId>quarkus-mailer</artifactId>
       <exclusions>
	  <exclusion>
	    <groupId>io.quarkus</groupId>
	    <artifactId>quarkus-qute</artifactId>
	  </exclusion>
      </exclusions>
</dependency>
```

```txt
2023-09-01 18:12:23,728 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.NoClassDefFoundError: io/quarkus/qute/i18n/MessageBundle
	at io.quarkus.qute.deployment.Names.<clinit>(Names.java:31)
	at io.quarkus.qute.deployment.QuteProcessor.<clinit>(QuteProcessor.java:155)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at io.quarkus.deployment.util.ServiceUtil.classesNamedIn(ServiceUtil.java:29)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:170)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:332)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:253)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:82)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:423)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.ClassNotFoundException: io.quarkus.qute.i18n.MessageBundle
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
	... 17 more


```

**Comment by mkouba** [comment]
Just a wild guess (I have zero knowledge of the redis extension) - you can try to specify the default value type for the `qute-cache` with the `quarkus.cache.redis."qute-cache".value-type` config property as a workaround; the value should be `io.quarkus.qute.ResultNode`.

**Comment by geoand** [comment]
If that is indeed the solution, we should probably set it automatically when qute and redis-cache are used.

But we probably also want to not use the cache in Qute in this case...

**Comment by mkouba** [comment]
> If that is indeed the solution, we should probably set it automatically when qute and redis-cache are used.

Well, in general any extension can produce an `AdditionalCacheNameBuildItem` so it's IMO not a qute-specific problem.

> But we might also want to not use the cache in Qute in this case...

I'd like to know the details about this redis requirement - the cache SPI does not seem to define any... Maybe we should enhance the SPI instead?

**Comment by geoand** [comment]
It's true that it's not a Qute specific problem, and we should indeed augment the SPI. 

Essentially what this does is enable the Redis cache extension to know the type of data that is going to be exchanged with the server which in turn is used in order to marshall and unmarshall the data.

**Comment by mkouba** [comment]
> Essentially what this does is enable the Redis cache extension to know the type of data that is going to be exchanged with the server which in turn is used in order to marshall and unmarshall the data over the wire.

How does it handle serialization?

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/blob/3.3.1/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/Marshaller.java

**Comment by mkouba** [comment]
> https://github.com/quarkusio/quarkus/blob/3.3.1/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/runtime/datasource/Marshaller.java

Ah, so it wouldn't work anyway as there's probably no working codec for the `ResultNode`. In that case, we should make it possible to inspect the cache impl capabilities at build time so that we can only register the additional cache conditionally...?

**Comment by geoand** [comment]
Yeah, that's probably a good option.

**Comment by leotu** [comment]
> Just a wild guess (I have zero knowledge of the redis extension) - you can try to specify the default value type for the `qute-cache` with the `quarkus.cache.redis."qute-cache".value-type` config property as a workaround; the value should be `io.quarkus.qute.ResultNode`.


It can be successfully compiled when setting value:

```txt
quarkus.cache.redis."qute-cache".value-type = io.quarkus.qute.ResultNode
```

But i am not sure Qute is working and it shouldn't choose redis cache if both  caffeine and redis exist.

**Comment by mkouba** [comment]
> But i am not sure Qute is working...

I don't think it is.

> ...and it shouldn't choose redis cache if both caffeine and redis exist.

But only one cache implementation can be present, right? We need to enhance the SPI so that it's possible to detect the cache impl...

**Comment by geoand** [comment]
Right, only one impl is allowed

**Comment by geoand** [comment]
I'll have to think of this a little

**Comment by geoand** [comment]
For Qute specifically, is caching templates on a remote server a good thing or would it hurt performance?

**Comment by mkouba** [comment]
> For Qute specifically, is caching templates on a remote server a good thing or would it hurt performance?

I don't think it's a good idea. So the SPI should at least provide a way to detect the type of the cache (in-memory/remote).

**Comment by geoand** [comment]
That's what I thought, thanks!

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/35817 should take care of it
