### ISSUE TITLE
async REST return types will throw when used reactively

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#3578]
Due to the new HTTP-vertx merge, we're starting to see the following exception:

```
2019-08-19 17:24:18,882 ERROR [org.jbo.res.res.i18n] (vert.x-eventloop-thread-30) RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.lang.IllegalStateException: UT000126: Attempted to do blocking IO from the IO thread. This is prohibited as it may result in deadlocks
	at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:132)
	at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:115)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletResponseWrapper$DeferredOutputStream.write(HttpServletResponseWrapper.java:39)
	at org.jboss.resteasy.util.CommitHeaderOutputStream.write(CommitHeaderOutputStream.java:64)
	at org.jboss.resteasy.plugins.providers.StringTextStar.writeTo(StringTextStar.java:65)
	at org.jboss.resteasy.plugins.providers.StringTextStar.writeTo(StringTextStar.java:24)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.writeTo(AbstractWriterInterceptorContext.java:193)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:64)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:155)
	at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$2(ServerResponseWriter.java:156)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:405)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:232)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:97)
	at org.jboss.resteasy.core.AsyncResponseConsumer.sendBuiltResponse(AsyncResponseConsumer.java:148)
	at org.jboss.resteasy.core.AsyncResponseConsumer.internalResume(AsyncResponseConsumer.java:115)
	at org.jboss.resteasy.core.AsyncResponseConsumer$CompletionStageResponseConsumer.accept(AsyncResponseConsumer.java:237)
	at org.jboss.resteasy.core.AsyncResponseConsumer$CompletionStageResponseConsumer.accept(AsyncResponseConsumer.java:216)
	at io.smallrye.context.SmallRyeThreadContext$ContextualBiConsumer.accept(SmallRyeThreadContext.java:157)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.smallrye.context.CompletableFutureWrapper.lambda$new$0(CompletableFutureWrapper.java:35)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at io.vertx.axle.AsyncResultCompletionStage.lambda$toCompletionStage$0(AsyncResultCompletionStage.java:18)
	at io.vertx.axle.sqlclient.SqlConnection$3.handle(SqlConnection.java:196)
	at io.vertx.axle.sqlclient.SqlConnection$3.handle(SqlConnection.java:193)
	at io.vertx.sqlclient.impl.SqlResultBuilder.handle(SqlResultBuilder.java:65)
	at io.vertx.sqlclient.impl.SqlResultBuilder.handle(SqlResultBuilder.java:29)
	at io.vertx.sqlclient.impl.SqlConnectionImpl.lambda$schedule$0(SqlConnectionImpl.java:52)
	at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:210)
	at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:81)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:235)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:125)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:364)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:77)
	at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:124)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:229)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:87)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Which happens when you return something like:

```java
@GET
public CompletionStage<String> foo(){
 return doAsyncHttpCall().thenApply(() -> "OK");
}
```

So, what happens is that we run a client HTTP call, which notifies us of its result on the IO thread, then RESTEasy registers for this async result and proceeds to write the response to the client. 

RESTEasy ATM doesn't care which thread it's invoked on, and will happily resume the suspended HTTP request on the IO thread like any other thread. But Undertow detects this and throws an exception.

This needs fixing, because it will happen a lot. If RESTEasy cannot ever write on the IO thread, it needs to be able to determine that it is on the wrong thread when it gets the async result, and resume the request on another thread (which one??).

OTOH, if @patriot1burke rewrites the `quarkus-resteasy` integration so that it runs without servlet, directly on vert.x, it's possible it will use the `resteasy-vertx` integration which writes all IO as buffered HTTP chunk and so writing the response will likely not care that it's on the IO thread. Though flushing/sending it might still care.

This probably needs advice from @vietj @stuartwdouglas and @cescoffier.

**Comment by stuartwdouglas** [comment]
So this was always a problem, only now it is a more serious one.

Before this change Undertow was doing blocking IO on the vert.x IO thread, which could cause major performance problems. After this change Undertow now detects this and throws an exception, as the IO threads are now shared this could actually result in a deadlock if the IO thread is blocked, as unblocking is done by the IO thread. 

In terms of Resteasy + Servlet the only real fix is to dispatch before writing, although if the response is fully buffered a better solution would be to use Servlet async IO.

**Comment by FroMage** [comment]
Funny thing to note is that I can't run TechEmpower for quarkus with pg-client due to this. I can workaround it by finishing every endpoint on a worker thread, but I suppose it will kill perf.

**Comment by Sergey80** [comment]
seems still a problem for me at quarkus 1.0:
https://stackoverflow.com/questions/59229567/resteasy002020-unhandled-asynchronous-exception-with-quarkus-1-0-final-and-rest
