### ISSUE TITLE
Native executable compiled with GraalVM fails to subscribe to Google Pub/Sub topic

### ISSUE THREAD

**Issue by gpaolopedrazza** [quarkusio/quarkus#35803]
### Describe the bug

I create a new Google Pub/Sub project for Quarkus following exactly the tutorial available on https://docs.quarkiverse.io/quarkus-google-cloud-services/main/pubsub.html using 3.2.0 Final as quarkus version. The only small difference was in the subscription name, because I already had one and therefore, I just used it like
`ProjectSubscriptionName subscriptionName = ProjectSubscriptionName.of(projectId, pubSubSubscription);`
Running the project on quarkus works like a charm, the subscriber works and messages are sent/received to/from the Pub/Sub subscription.
My problem comes when I try to build a native executable. I downloaded and installed Oracle GraalVM 20.0.2+9.1 and tried to build a native image. 
`mvnw --no-transfer-progress -f pom.xml -Pnative clean package -DskipTest`
Due to following bug in GraalVM https://github.com/oracle/graal/issues/5868, I had to implement following workaround https://github.com/apache/camel-quarkus/issues/5006#issuecomment-1612648062
Probably precisely because of that GraalVM bug, Google Pub/Sub rejects the subscriber request with invalid argument error.
Is this really just a bug of GraalVM and I have to wait for the fix? Is there any different method/framework else I can use in order to make a PubSub subscriber working under Quarkus with a native build?

### Expected behavior

__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-09-07 15:56:42,364 INFO  [io.quarkus] (Quarkus Main Thread) pubsub-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.2.0.Final) started in 2.860s. Listening on: http://localhost:8080
2023-09-07 15:56:42,367 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-09-07 15:56:42,367 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, google-cloud-pubsub, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
2023-09-07 15:59:36,450 INFO  [org.acm.PubSubResource] (executor-thread-1) Created subscriber
2023-09-07 15:59:36,704 INFO  [org.acm.PubSubResource] (executor-thread-1) Subscriber running

### Actual behavior

C:\source\pubsub-quickstart\target>pubsub-quickstart-1.0.0-SNAPSHOT-runner.exe
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-09-07 15:40:38,096 INFO  [io.quarkus] (main) pubsub-quickstart 1.0.0-SNAPSHOT native (powered by Quarkus 3.2.0.Final) started in 0.086s. Listening on: http://0.0.0.0:8080
2023-09-07 15:40:38,099 INFO  [io.quarkus] (main) Installed features: [cdi, google-cloud-pubsub, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
2023-09-07 15:46:19,031 INFO  [org.acm.PubSubResource] (executor-thread-1) Created subscriber
2023-09-07 15:46:19,051 INFO  [org.acm.PubSubResource] (executor-thread-1) Subscriber running
2023-09-07 15:46:19,591 SEVERE [com.goo.clo.pub.v1.StreamingSubscriberConnection] (Subscriber-SE-1-0) terminated streaming with exception: com.google.api.gax.rpc.InvalidArgumentException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:92)
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
        at com.google.cloud.pubsub.v1.StreamingSubscriberConnection$1.onFailure(StreamingSubscriberConnection.java:340)

### How to Reproduce?

1. Follow the tutorial https://docs.quarkiverse.io/quarkus-google-cloud-services/main/pubsub.html and check the project works
2. Install Oracle GraalVM 20.0.2+9.1 and build an executable
3. Try to run the executable

### Output of `java -version`

java 20.0.1 2023-04-18

### GraalVM version (if different from Java)

20.0.2+9.1

### Quarkus version or git rev

3.2.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw --no-transfer-progress -f pom.xml -Pnative clean package -DskipTest

**Comment by gsmet** [comment]
@loicmathieu could you have a look at this one? I think it’s using your stuff and there is a reproducer. Thanks!

**Comment by gpaolopedrazza** [comment]
I tried to run Quarkus with debug as log level and to build again a native executable. I was able to capture the request which gets rejected (I replaced some data):
`2023-09-08 08:40:23,503 DEBUG [io.grp.net.NettyClientHandler] (grpc-nio-worker-ELG-2-2) [id: 0x99ea3967, L:/10.21.33.2:52092 - R:pubsub.googleapis.com/142.250.186.106:443] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: pubsub.googleapis.com:443, :path: /google.pubsub.v1.Subscriber/StreamingPull, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.56.0, x-goog-request-params: subscription=asd, x-goog-api-client: gl-java/20.0.2-graalvm gapic/1.123.12 gax/2.27.0 grpc/1.56.0, grpc-accept-encoding: gzip, authorization: Bearer ya29., x-goog-user-project: asd] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2023-08-18 08:40:23,503 DEBUG [io.grp.net.NettyClientHandler] (grpc-nio-worker-ELG-2-2) [id: 0x99ea3967, L:/10.21.33.2:52092 - R:pubsub.googleapis.com/142.250.186.106:443] OUTBOUND DATA: streamId=3 padding=0 endStream=false length=133 bytes=00000000800000000000000000000070726f6a656374732f6d6574617379732d73746f726167652d6465762f737562736372697074696f6e732f696d706f7274...`
The headers look fine and are exactly the same as with quarkus in dev mode. However, the server rejects the request without any useful debug information:
`2023-09-08 08:40:23,546 DEBUG [io.grp.net.NettyClientHandler] (grpc-nio-worker-ELG-2-2) [id: 0x99ea3967, L:/10.21.33.2:52092 - R:pubsub.googleapis.com/142.250.186.106:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, date: Fri, 18 Aug 2023 06:40:23 GMT, alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000] padding=0 endStream=false
2023-08-18 08:40:23,547 DEBUG [io.grp.net.NettyClientHandler] (grpc-nio-worker-ELG-2-2) [id: 0x99ea3967, L:/10.21.33.2:52092 - R:pubsub.googleapis.com/142.250.186.106:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 3, grpc-message: Request contains an invalid argument.] padding=0 endStream=true`

**Comment by loicmathieu** [comment]
@gpaolopedrazza could you open an issue in this repo https://github.com/quarkiverse/quarkus-google-cloud-services with a reproducer ? There is an issue with Apache Arrow which will be fixed in 1.3 (not yet released last time I checked) and an issue with GraalVM (which will be fixed soon), and an issue with Google GAX (which will be fixed soon) so it's very complex to track all these stuff right now.

So the best is to add you reproducer to the other issue and close this one so I can synchronize all the issues and check when the fix will be integrated that they cover all the use cases.

**Comment by gpaolopedrazza** [comment]
I opened https://github.com/quarkiverse/quarkus-google-cloud-services/issues/494 as requested in the message above.

**Comment by loicmathieu** [comment]
Thanks
