### ISSUE TITLE
Narayana upgrade to 5.9.6.Final causes fail in native

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#3581]
Narayana upgrade to 5.9.6.Final causes fail in native mode

Revealed in https://github.com/quarkusio/quarkus/pull/3572#pullrequestreview-276620114

```
quarkus-integration-test-main-999-SNAPSHOT-runner:20]        setup:     801.32 ms
Error: could not find target method: private static synchronized void io.quarkus.narayana.jta.runtime.graal.ConfigurationInfoSubstitution.getBuildTimeProperties()
com.oracle.svm.core.util.UserError$UserException: could not find target method: private static synchronized void io.quarkus.narayana.jta.runtime.graal.ConfigurationInfoSubstitution.getBuildTimeProperties()
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:633)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:326)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:298)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:863)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:817)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:520)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:440)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by gwenneg** [comment]
The `ConfigurationInfo.getBuildTimeProperties()` was removed from Narayana recently:
https://github.com/jbosstm/narayana/commit/6a6b9b3943e06a1726cc638688d46b17b8ecb7dd#diff-ca74e7d5775a087fc3023c7dee796eb0
