### ISSUE TITLE
Narayana transaction recovery stops work in DEV mode after hot reload

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#35839]
### Describe the bug

When I change my application in DEV mode and the app is reload, Narayana keeps using the old (previous) Datasource connection even though pool has been closed and new one was created. Details in here https://github.com/quarkusio/quarkus/pull/35242#issuecomment-1668239070

### Expected behavior

After hot reload, my app still works.

### Actual behavior

Warning is logged and periodic recovery doesn't work

```
2023-08-07 18:41:54,145 WARN  [com.arj.ats.arjuna] (Transaction Expired Entry Monitor) ARJUNA012251: allObjUids caught exception: java.sql.SQLException: This pool is closed and does not handle any more connections!
	at io.agroal.pool.ConnectionPool.beforeAcquire(ConnectionPool.java:209)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:235)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.quarkus.narayana.jta.runtime.QuarkusDataSource.getConnection(QuarkusDataSource.java:38)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.accessors.DirectDataSourceJDBCAccess.getConnection(DirectDataSourceJDBCAccess.java:27)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCImple_driver.allObjUids(JDBCImple_driver.java:348)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore.allObjUids(JDBCStore.java:169)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore.allObjUids(JDBCStore.java:125)
	at com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionStatusManagerScanner.scan(ExpiredTransactionStatusManagerScanner.java:81)
	at com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor.run(ExpiredEntryMonitor.java:171)
```

### How to Reproduce?

Reproducer:

- on this branch and inside quickstart added here https://github.com/quarkusio/quarkus-quickstarts/pull/1311
- `quarkus dev`
- wait till service is fully started
- force restart with `s`

### Output of `uname -a` or `ver`

Fedora

### Output of `java -version`

17

### GraalVM version (if different from Java)

23

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

**Comment by michalvavrik** [comment]
Is this solved or on your radar @zhfeng @mmusgrov ?

**Comment by mmusgrov** [comment]
@michalvavrik I don't recall ever investigating it. You raised the issue so could you not retest it? If not then the transaction team are quite busy:  @marcosgopen or @jmfinelli are either of you able to provide Michal with any input on this issue.

**Comment by michalvavrik** [comment]
> @michalvavrik I don't recall ever investigating it. You raised the issue so could you not retest it? If not then the transaction team are quite busy: @marcosgopen or @jmfinelli are either of you able to provide Michal with any input on this issue.

copy that, thanks; I'll re-run the test later this week

**Comment by marcosgopen** [comment]
Sure, I will have a look at it.

**Comment by michalvavrik** [comment]
sorry @marcosgopen , I had very busy week, sure, there were breaking changes in the meanwhile and I completely forgot aobut QS PR. Should probably rebase it and resolve conflicts. I'll fix the reproducer next week, thanks so far.

**Comment by gsmet** [comment]
It would be interesting to see if this is still an issue.

**Comment by michalvavrik** [comment]
Hey, I'll answer later this week.

**Comment by michalvavrik** [comment]
So, I have tried and I still can reproduce the original issue. Here is how:

```
git clone git@github.com:michalvavrik/quarkus-quickstarts.git -b feature/add-narayana-transaction-logs-qs
cd quarkus-quickstarts/narayana-transaction-logs-quickstart
docker-compose up
quarkus dev
```

Wait till Quarkus ready, then type 's', maybe wait again and try thrice. I am not quite sure how many times I have tried `s` as I had a long day. Here are logs I got:

```
[INFO] Invoking compiler:3.1:testCompile (default-testCompile) @ narayana-transaction-logs-quickstart
[INFO] Nothing to compile - all classes are up to date
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-09-22 21:57:58,602 INFO  [io.quarkus] (Quarkus Main Thread) narayana-transaction-logs-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 2.090s. Listening on: http://localhost:8080

2024-09-22 21:57:58,605 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-09-22 21:57:58,605 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, jdbc-postgresql, narayana-jta, rest, smallrye-context-propagation, vertx]
2024-09-22 21:58:01,087 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Aesh InputStream Reader) Restarting as requested by the user.
2024-09-22 21:58:01,090 INFO  [com.arj.ats.jbossatx] (Quarkus Main Thread) ARJUNA032014: Stopping transaction recovery manager
2024-09-22 21:58:01,099 INFO  [io.quarkus] (Quarkus Main Thread) narayana-transaction-logs-quickstart stopped in 0.011s
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-09-22 21:58:01,460 INFO  [io.quarkus] (Quarkus Main Thread) narayana-transaction-logs-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.359s. Listening on: http://localhost:8080

2024-09-22 21:58:01,461 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-09-22 21:58:01,461 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, jdbc-postgresql, narayana-jta, rest, smallrye-context-propagation, vertx]
2024-09-22 21:58:01,462 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Aesh InputStream Reader) Live reload total time: 0.377s 
2024-09-22 21:58:02,738 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Aesh InputStream Reader) Restarting as requested by the user.
2024-09-22 21:58:02,743 INFO  [com.arj.ats.jbossatx] (Quarkus Main Thread) ARJUNA032014: Stopping transaction recovery manager
2024-09-22 21:58:02,748 INFO  [io.quarkus] (Quarkus Main Thread) narayana-transaction-logs-quickstart stopped in 0.008s
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-09-22 21:58:03,051 WARN  [com.arj.ats.arjuna] (Transaction Expired Entry Monitor) ARJUNA012251: allObjUids caught exception: java.sql.SQLException: This pool is closed and does not handle any more connections!
	at io.agroal.pool.ConnectionPool.beforeAcquire(ConnectionPool.java:247)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:273)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.agroal.api.AgroalDataSource_4TkLOYZRnQnK5Mzj2yarinAMQzA_Synthetic_ClientProxy.getConnection(Unknown Source)
	at io.quarkus.narayana.jta.runtime.QuarkusDataSource.getConnection(QuarkusDataSource.java:38)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.accessors.DirectDataSourceJDBCAccess.getConnection(DirectDataSourceJDBCAccess.java:25)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCImple_driver.allObjUids(JDBCImple_driver.java:321)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore.allObjUids(JDBCStore.java:142)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore.allObjUids(JDBCStore.java:98)
	at com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionStatusManagerScanner.scan(ExpiredTransactionStatusManagerScanner.java:54)
	at com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor.run(ExpiredEntryMonitor.java:144)


2024-09-22 21:58:03,051 WARN  [com.arj.ats.arjuna] (Periodic Recovery) ARJUNA012251: allObjUids caught exception: java.sql.SQLException: This pool is closed and does not handle any more connections!
	at io.agroal.pool.ConnectionPool.beforeAcquire(ConnectionPool.java:247)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:273)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.agroal.api.AgroalDataSource_4TkLOYZRnQnK5Mzj2yarinAMQzA_Synthetic_ClientProxy.getConnection(Unknown Source)
	at io.quarkus.narayana.jta.runtime.QuarkusDataSource.getConnection(QuarkusDataSource.java:38)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.accessors.DirectDataSourceJDBCAccess.getConnection(DirectDataSourceJDBCAccess.java:25)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCImple_driver.allObjUids(JDBCImple_driver.java:321)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore.allObjUids(JDBCStore.java:142)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore.allObjUids(JDBCStore.java:98)
	at com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule.periodicWorkFirstPass(AtomicActionRecoveryModule.java:63)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:743)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:355)


2024-09-22 21:58:03,053 WARN  [com.arj.ats.arjuna] (Periodic Recovery) ARJUNA012251: allObjUids caught exception: java.sql.SQLException: This pool is closed and does not handle any more connections!
	at io.agroal.pool.ConnectionPool.beforeAcquire(ConnectionPool.java:247)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:273)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.agroal.api.AgroalDataSource_4TkLOYZRnQnK5Mzj2yarinAMQzA_Synthetic_ClientProxy.getConnection(Unknown Source)
	at io.quarkus.narayana.jta.runtime.QuarkusDataSource.getConnection(QuarkusDataSource.java:38)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.accessors.DirectDataSourceJDBCAccess.getConnection(DirectDataSourceJDBCAccess.java:25)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCImple_driver.allObjUids(JDBCImple_driver.java:321)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore.allObjUids(JDBCStore.java:142)
	at com.arjuna.ats.internal.arjuna.objectstore.jdbc.JDBCStore.allObjUids(JDBCStore.java:98)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:198)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:167)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:743)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:355)


2024-09-22 21:58:03,054 WARN  [com.arj.ats.jta] (Periodic Recovery) ARJUNA016001: could not get all object Uids.
2024-09-22 21:58:03,054 INFO  [io.quarkus] (Quarkus Main Thread) narayana-transaction-logs-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 0.303s. Listening on: http://localhost:8080
2024-09-22 21:58:03,054 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-09-22 21:58:03,055 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, jdbc-postgresql, narayana-jta, rest, smallrye-context-propagation, vertx]
2024-09-22 21:58:03,055 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Aesh InputStream Reader) Live reload total time: 0.321s 
```

**Comment by marcosgopen** [comment]
Thanks @michalvavrik for your reproducer, I menaged to reproduce it and I am working to understand what the problem is and solve it. I think that when the destroy method of QuarkusRecoveryService is executed we should also set to null the datasource of  QuarkusDataSource. I'll keep you updated.

**Comment by marcosgopen** [comment]
This is how Narayana XARecoveryModule works:
https://github.com/jbosstm/narayana/blob/main/ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/XARecoveryModule.java#L660-L666
It calls recover with TMSTARTRSCAN to open the connection and then calls recover with TMENDRSCAN to close it.
In agroal, the RecoveryXAResource  opens or closes the connection based on the flag passed.
https://github.com/agroal/agroal/blob/master/agroal-narayana/src/main/java/io/agroal/narayana/RecoveryXAResource.java#L53-L59
 That works until you execute a restart in quarkus dev mode.
I need to investigate more but I believe that when the quarkus dev restart is executed there is a loop call to connect which is causing:
 ```
javax.transaction.xa.XAException:` FATAL: sorry, too many clients already
	at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:21)
	at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:15)
	at io.agroal.narayana.RecoveryXAResource.recover(RecoveryXAResource.java:62)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.xaRecoveryFirstPass(XARecoveryModule.java:660)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:217)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:155)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:788)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:403)
Caused by: org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:778)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:234)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:289)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:57)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:279)
	at org.postgresql.Driver.makeConnection(Driver.java:448)
	at org.postgresql.Driver.connect(Driver.java:298)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:613)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:199)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:104)
	at org.acme.quickstart.recovery.CrashingPGXADataSource.getXAConnection(CrashingPGXADataSource.java:22)
	at org.acme.quickstart.recovery.CrashingPGXADataSource.getXAConnection(CrashingPGXADataSource.java:17)
	at io.agroal.pool.ConnectionFactory.getRecoveryConnection(ConnectionFactory.java:292)
	at io.agroal.narayana.RecoveryXAResource.connect(RecoveryXAResource.java:29)
	at io.agroal.narayana.RecoveryXAResource.recover(RecoveryXAResource.java:54)
	... 5 more
 ```
when the connection limit is reached. And then every 'PeriodicRecovery.doWorkInternal' will throw the exception.

**Comment by marcosgopen** [comment]
> Possibly related is the issue that the quarkus recovery manager service does not seem to correctly deregister recovery helpers during shutdown which means that narayana periodic recovery will continue using the connections. I will try to find the time to raise an issue for that but in the mean time it is something [@marcosgopen](https://github.com/marcosgopen) could factor into his investigations.

@mmusgrov is right, the recoveryMenager was terminated in the 'stop' phase, but the the helpers need to be removed (to free the connections) before (so not in the destroy phase). see my fix https://github.com/quarkusio/quarkus/pull/52181

**Comment by cescoffier** [comment]
🤖 Automatically associated with the **WG - Unified Saga implementation** Working Group based on AI classification.

**Comment by marcosgopen** [comment]
@michalvavrik Could you please verify the fix I proposed is correctly addressing the issue?

**Comment by michalvavrik** [comment]
> [@michalvavrik](https://github.com/michalvavrik) Could you please verify the fix I proposed is correctly addressing the issue?

hey @marcosgopen , I am not working on that project anymore. Perphaps @rsvoboda can pick someone who will have a look?

**Comment by zhfeng** [comment]
@marcosgopen I added my comment on your PR.
