### ISSUE TITLE
Quarkus exception logging limit

### ISSUE THREAD

**Issue by JChrist** [quarkusio/quarkus#35950]
### Description

I'm trying to configure quarkus to log exceptions with limited or no stacktrace, just the exception class and message, similar to logback's exception shortening (e.g. `%ex{short}`). 

I've tried changing the property:

`quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %m%n`: logs message, exception and stacktrace
`quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n`: same as previous
`quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%n`: does not log anything related to the exception.

Currently, there's no such option in JBoss LogManager, so this is not supported.

**Comment by geoand** [comment]
@jamezp @dmlloyd this sounds like a reasonable request for JBoss Logging, WDYT?

**Comment by jamezp** [comment]
This does seem like a reasonable request to me. We'd need to think what this looks like because currently we support something like `%e{0}` which would not log suppressed exceptions.

**Comment by geoand** [comment]
> currently we support something like %e{0} which would not log suppressed exceptions

@jamezp is this kind of thing documented? Asking because we definitely have not documented it in Quarkus

**Comment by geoand** [comment]
^ is probably the most polished comment I have ever seen in this repo :)

**Comment by JChrist** [comment]
The argument for `e` currently seems to only affect nested/suppressed exceptions, as @jamezp mentioned.
For example, setting `%e{0}` and attempting to log an exception similar to the following:
`logger.error("test exception", new Exception("test ex 1", new Exception("test ex 2", new Exception("test ex 3"))));`

results to output like:
```
test exception: java.lang.Exception: test ex 1
        at TestResource.test(TestResource.java:12)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       ... <many more lines reducted for brevity>
Caused by: java.lang.Exception: test ex 2
        ... 122 more
Caused by: java.lang.Exception: test ex 3
        ... 122 more
```

So, only the suppressed exceptions are affected and (kind of) skip the stacktrace.

**Comment by dmlloyd** [comment]
This problem is based on me misunderstanding the code as I was reading it. The extended parameter for `%e` is actually an indicator for how many nested or cause stack traces to log in addition to the base stack trace. Perhaps we should consider enhancing the exception formats similarly to log4j2 with more capabilities.

**Comment by jamezp** [comment]
+1, it seems like a reasonable change request to me.
