### ISSUE TITLE
Request freeze in Resteasy Reactive during writing of body

### ISSUE THREAD

**Issue by anders-ahlgren** [quarkusio/quarkus#35961]
### Describe the bug

We had a Resteasy Reactive request that hanged in production, and we investigated via thread and heap dump. 

Our analysis suggests the underlying cause to be a vert.x bug, which has been reported to vert.x too.

### Expected behavior

Request should not hang.

### Actual behavior

Request hanged, with the stack given below.

Basically, the thread entered the `request.connection().wait()`; statement in `ResteasyReactiveOutputStream.awaitWriteable()` and never was woken up. The heap dump showed that `request.response().writeQueueFull()` -- which had to return true to reach this statement -- had changed to false at the time of the heap dump. Thus, the statement should have been woken up but was not.

Stack:

```
"executor-thread-56316" #700597 daemon prio=5 os_prio=0 cpu=806.56ms elapsed=41638.06s tid=0x00007fe620237aa0 nid=0x23f3f2 in Object.wait()  [0x00007fe575829000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.7/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@17.0.7/Object.java:338)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.awaitWriteable(ResteasyReactiveOutputStream.java:140)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:89)
	- locked <0x00000005d56763d0> (a io.vertx.core.http.impl.Http2ServerConnection)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.writeBlocking(ResteasyReactiveOutputStream.java:231)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:218)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:189)
	at com.mercur.server.endpoint.support.CborBody$CborBodyWriter.writeTo(CborBody.java:203)
	at com.mercur.server.endpoint.support.CborBody$CborBodyWriter.writeTo(CborBody.java:191)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:233)
	at org.jboss.resteasy.reactive.server.core.serialization.DynamicEntityWriter.write(DynamicEntityWriter.java:106)
	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:32)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:120)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:581)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@17.0.7/Thread.java:833)

```

### How to Reproduce?

Intermittent and rather low-frequency -- once per some hundreds of millions of requests. However, theoretical analysis suggests sequence is something similar to the following.

1. Thread A: `ResteasyReactiveOutputStream.awaitWriteable()` checks if queue is full -- it is, that is `VertxHttp2Stream.writable` == false (synchronized on connection throughout, synchronized on stream during check itself)
2. Thread B: Drains the queue (or observes it has been drained, not clear on where this is done)
3. Thread B: Sets `VertxHttp2Stream.writable` to true (synchronized on stream)
4. Thread B: Checks `Http2ServerResponse.drainHandler` (it is null -- it is checked without any locks held; unclear if that is correct)
5. Thread A: Registers a `Http2ServerResponse.drainHandler` (still synchronized on connection)
6. Thread A: Goes to sleep via `request.connection().wait()` -- expecting to be woken up when writability changes, but that has already happened so it waits forever instead

### Additional information

I believe the underlying problem is in vert.x, reported as [https://github.com/eclipse-vertx/vert.x/issues/4858](url)

**Comment by geoand** [comment]
@viej this sounds like one for you

**Comment by geoand** [comment]
@anders-ahlgren any chance you could attach a sample application we can use to reproduce the problem and test potential fixes against?

Thanks

**Comment by anders-ahlgren** [comment]
@geoand The following simple application seems to hang pretty reliably, but it varies a lot how long it takes before that happens, but in most cases it hangs within a minute or two.

(There are also two two slightly different variations of the hanging behaviour with slightly different stacks and different printouts -- sometimes it prints "Very slow write" which corresponds to our production case, but usually it hangs without this printout. It probably doesn't matter, it seems to be the same bug, but the different printouts can be confusing if you don't know about this behaviour.) 

Start the server and then curl "http://localhost:8080/test/count" to start the case. 

You can also add a query parameter iterations if you want to change the number of iterations (default 2 million).

[hanging-in-await-writable.zip](https://github.com/quarkusio/quarkus/files/12872192/hanging-in-await-writable.zip)

**Comment by geoand** [comment]
Thanks

**Comment by geoand** [comment]
Is this still an issue with the latest Quarkus versions?

**Comment by anders-ahlgren** [comment]
The isolated case still hangs in Quarkus 3.5.3.

**Comment by geoand** [comment]
Thanks.

And I assume with 3.6.0 as well?

**Comment by anders-ahlgren** [comment]
Yes, just verified it hangs in 3.6.0 too.

**Comment by jasminsuljic** [comment]
Just to check if there's any update on this one, we are experiencing same issue in production environment.

Quarkus Version: `3.7.4`

```
io.vertx.core.VertxException: Thread blocked
	at java.base@17.0.6/java.lang.Object.wait(Native Method)
	at java.base@17.0.6/java.lang.Object.wait(Object.java:338)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.awaitWriteable(ResteasyReactiveOutputStream.java:145)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:94)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.writeBlocking(ResteasyReactiveOutputStream.java:207)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:195)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2208)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.close(UTF8JsonGenerator.java:1232)
	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1278)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1098)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.BasicServerJacksonMessageBodyWriter.writeResponse(BasicServerJacksonMessageBodyWriter.java:39)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:216)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:184)
	at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriter.write(FixedEntityWriter.java:28)
	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:34)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:147)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:78)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:75)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:276)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:258)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:56)
	at io.vertx.core.impl.ContextInternal$$Lambda$1084/0x0000000801964000.run(Unknown Source)
	at io.opentelemetry.javaagent.bootstrap.executors.ContextPropagatingRunnable.run(ContextPropagatingRunnable.java:37)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)

```

**Comment by FroMage** [comment]
Apparently Quarkus `3.7.4` includes Vert.x `4.5.3` which should have the fix in https://github.com/eclipse-vertx/vert.x/issues/4858 since it was fixed in early December. Perhaps this is a different issue? Or should we have done something on our side?

**Comment by jasminsuljic** [comment]
Not sure whom you are asking, maybe it would be good if reproducer created by @anders-ahlgren is tested againts `3.7.4`

@anders-ahlgren do you still experience same issue?

**Comment by anders-ahlgren** [comment]
@jasminsuljic @FroMage My isolated case seems to works fine for me with 3.7.4.  Production also seems to work fine for us so far, but the problem was always relatively infrequent, so that may not be completely conclusive.

**Comment by FroMage** [comment]
Ah, so perhaps it's another variation of this problem and not the same one, then?

Can you write a reproducer please @jasminsuljic ?
