### ISSUE TITLE
Can't read SSE content type with plain Rest client

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#35967]
### Describe the bug

When consuming an SSE source with `quarkus-rest-client-jsonb`, I get the following error: `RESTEASY003145: Unable to find a MessageBodyReader of content-type text/event-stream and type class org.jboss.resteasy.plugins.providers.sse.SseEventInputImpl`.

Funnily, this only happens in the Quarkus app in the production code; in my unit test, it works as expected (reading the SSE events). My assumption is that the build-time optimization removes some classes it finds unnecessary.

I'm not using `resteasy`, since this a cli app. This might be the isssue... I'm also not using `rest-client-reactive-*` because of #35966

### How to Reproduce?

This code:

```java
@ApplicationScoped
public class SomeClient {

    private Client client;
    private SseEventSource updateSource;

    @PostConstruct
    void init() {
        client = ClientBuilder.newClient();
    }

    // [...]

    @PreDestroy
    void close() throws IOException {
        client.close();
        if (updateSource != null)
            updateSource.close();
    }

    public void someMethod() {
        // [...]

        WebTarget target = client.target("http://localhost:8080/updates");
        updateSource = SseEventSource.target(target).build();
        updateSource.register(ev -> {
            System.out.println(ev.getName());
            System.out.println(ev.readData());
        }, thr -> {
            System.err.println("Error in SSE updates");
            thr.printStackTrace();
        });

        System.out.println("SSE opened");
        updateSource.open();
    }

}
```

Invocation of the method results in:

```
jakarta.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type text/event-stream and type class org.jboss.resteasy.plugins.providers.sse.SseEventInputImpl
	at org.jboss.resteasy.core.interception.jaxrs.ClientReaderInterceptorContext.throwReaderNotFound(ClientReaderInterceptorContext.java:46)
  at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.getReader(AbstractReaderInterceptorContext.java:129)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:76)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:192)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:75)
	at org.jboss.resteasy.specimpl.AbstractBuiltResponse.readEntity(AbstractBuiltResponse.java:232)
	at org.jboss.resteasy.plugins.providers.sse.client.SseEventSourceImpl$EventHandler.run(SseEventSourceImpl.java:292)
	at org.jboss.resteasy.plugins.providers.sse.client.SseEventSourceScheduler$1.run(SseEventSourceScheduler.java:80)
	at org.jboss.resteasy.concurrent.ContextualExecutors.lambda$runnable$2(ContextualExecutors.java:312)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Maybe this issue is connected to #30935

### Output of `java -version`

OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)

### Quarkus version or git rev

3.2.0.Final

**Comment by sdaschner** [comment]
Update: Adding `quarkus-resteasy-jsonb` as dependency *AND* adding an (unused) SSE server resource fixes this, so I'm quite confident it has to do with the tree shaking at build time...

This is my "unused" resource I've added (together with `quarkus-resteasy-jsonb`):

```java
@ApplicationScoped
@Path("updates")
@Produces(MediaType.SERVER_SENT_EVENTS)
public class ClusterUpdatesResource {

    @Context
    Sse sse;

    @GET
    public void updates(@Context SseEventSink eventSink) {
        eventSink.send(createEvent());
        eventSink.close();
    }

    private OutboundSseEvent createEvent() {
        return sse.newEventBuilder()
                .name("test")
                .data("test")
                .build();
    }
}
```

**Comment by geoand** [comment]
Can you please attach a sample that behaves as you describe?
I'd like to debug why Quarkus is disregarding the SSE provider unless the server is around.

**Comment by sdaschner** [comment]
Sure, I've added a branch here: https://github.com/sdaschner/quarkus-playground/tree/sse-issue-35967

To reproduce:

```
git clone # with branch https://github.com/sdaschner/quarkus-playground/tree/sse-issue-35967
cd .../server/
mvn quarkus:dev

# new terminal
cd .../client/
mvn clean package
# you'll notice the SseTest works
java -jar target/quarkus-app/quarkus-run.jar
```

If the class `DummyUpdatesResource` gets removed from the client project, the exeption from above appears.

Btw, it seems the `quarkus-resteasy-*` dependency is not required in the pom, the example also works just by adding the dummy class.

**Comment by geoand** [comment]
So we do indeed bail out on setting up JAX-RS when we don't find any annotation usage, so I am going to close this as it works as intended.

**Comment by sdaschner** [comment]
Wait wait wait... This does not work as intented if I have an application that only consumes (client) and said client isn't able to map the content types.

**Comment by sdaschner** [comment]
Right now I have the dummy resource class as a workaround, but this is clearly not intended, since I don't want to offer an SSE endpoint from the client side

**Comment by geoand** [comment]
Yes and no really. What you are using the programmatic JAX-RS client which we have never really supported explicitly. What we do support is the REST Client which is annotation driven.

**Comment by geoand** [comment]
> I understand, yet from a real-world project perspective, it would be beneficial for these APIs (part of JAX-RS after all) to work "standalone" as well.

Right, I get that completely. But standalone means that there is no inspection we can perform which would mean we would have to include the kitchen sink when we don't find any JAX-RS / Jakarta REST annotations.

We could potentially provide a config property that would allow you to manually enable providers, but that would be extremely user unfriendly.

**Comment by geoand** [comment]
But I am pretty sure you can register providers on your own programmatically for the client

**Comment by sdaschner** [comment]
> But I am pretty sure you can register providers on your own programmatically for the client

Yes I can, do you have a list or more information which ones these are for JSON-B and/or Jackson? That's what I thought, that if we can identify these classes (probably some of `MessageBodyWriter`, or there is a class `SseEventProvider` FWIW), then we could manually add the class names to a jandex index or something, right?

**Comment by geoand** [comment]
Simply replace 

```java
client = ClientBuilder.newClient();
``` 

with

```
client = ClientBuilder.newClient().register(SseEventProvider.class);
```

**Comment by geoand** [comment]
🙏🏼
