### ISSUE TITLE
Unable to pull wsdl for Apache CXF project in dev mode with quarkus-amazon-lambda-rest

### ISSUE THREAD

**Issue by mgm3746** [quarkusio/quarkus#35991]
### Describe the bug

Using the quarkus-amazon-lambda-rest extension:

<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-amazon-lambda-rest</artifactId>
</dependency>

Attempting to retrieve the wsdl:
http://localhost:8080/soap/MyService?wsdl

There is the following exception in the quarkus logging:

ERROR [org.apa.cxf.ser.inv.AbstractInvoker] (vert.x-worker-thread-1) Invocation without a binding operation.
2023-09-11 10:52:46,612 WARN  [org.apa.cxf.pha.PhaseInterceptorChain] (vert.x-worker-thread-1) Interceptor for {http://localhost/ws/MyGateway%7MyService has thrown exception, unwinding now: org.apache.cxf.interceptor.Fault: No binding operation info while invoking unknown method with params unknown.
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:58)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$2.run(ServiceInvokerInterceptor.java:126)
        at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:131)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:233)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:207)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:159)
        at io.quarkiverse.cxf.transport.CxfHandler.process(CxfHandler.java:305)
        at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:242)
        at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:48)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

And the following in the browser:

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
<soap:Fault>
<faultcode>soap:Server</faultcode>
<faultstring>No binding operation info while invoking unknown method with params unknown.</faultstring>
</soap:Fault>
</soap:Body>
</soap:Envelope>

If the quarkus-amazon-lambda-rest extension is commented out, the wsdl is able to be successfully retrieved.

### Expected behavior

The wsdl should be returned.

### Actual behavior

org.apache.cxf.interceptor.Fault: No binding operation info while invoking unknown method with params unknown

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-3.el8_7) (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-3.el8_7) (build 17.0.6+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.3.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39) Maven home: /home/mmillson/.m2/wrapper/dists/apache-maven-3.8.8-bin/67c30f74/apache-maven-3.8.8 Java version: 17.0.8, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.8.0.7-2.el8.x86_64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "4.18.0-477.21.1.el8_8.x86_64", arch: "amd64", family: "unix"

**Comment by gsmet** [comment]
Sorry it took so long to get back to you. I think we will need a reproducer for this kind of problem and it might be too late to ask for that.

Let us know if you can come up with a reproducer. If not, we will close the issue. Thanks!

**Comment by geoand** [comment]
Let's close this for now, If a reproducer becomes available, we can reopen
