### ISSUE TITLE
hibernate failed to alter table add index for sqlite

### ISSUE THREAD

**Issue by lost22git** [quarkusio/quarkus#36052]
### Describe the bug

error info: 

```
  [org.hib.too.sch.int.ExceptionHandlerLoggedImpl] (JPA Startup Thread) GenerationTarget encountered exception accep
ting command : Error executing DDL "alter table fighter add constraint uk_name unique (name)" via JDBC [[SQLITE_ERROR] SQL error or missing data
base (near "constraint": syntax error)]: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "alter table fighter add constraint uk_name unique (name)" via JDBC [[SQLITE_ERROR] SQL error or missing database (near "constraint": syntax error)]
        at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:92)
        at org.hibernate.tool.schema.internal.Helper.applySqlString(Helper.java:235)
        at org.hibernate.tool.schema.internal.Helper.applySqlStrings(Helper.java:219)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createTableConstraints(SchemaCreatorImpl.java:393)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createSequencesTablesConstraints(SchemaCreatorImpl.java:351)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createFromMetadata(SchemaCreatorImpl.java:239)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:172)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:142)
        at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:118)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:254)        
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:143)
        at java.base/java.util.HashMap.forEach(HashMap.java:1429)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:140)
        at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
        at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:292)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:156)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "constraint": syntax error)
        at org.sqlite.core.DB.newSQLException(DB.java:1179)
        at org.sqlite.core.DB.newSQLException(DB.java:1190)
        at org.sqlite.core.DB.throwex(DB.java:1150)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:126)
        at org.sqlite.core.DB.prepare(DB.java:264)
        at org.sqlite.jdbc3.JDBC3Statement.lambda$execute$0(JDBC3Statement.java:51)
        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:455)
        at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:40)
        at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:235)
        at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:78)
        ... 22 more

```

**Comment by geoand** [comment]
This is almost certainly not a Quarkus specific issue, but I'll let our persistence SMEs decide.

**Comment by yrodiere** [comment]
If I had to guess I'd say your application is using the wrong Hibernate Dialect and thus Hibernate ORM generates incorrect SQL. Hard to say without a reproducer or your config, though.

Anyway, thanks for reporting but SQLite is not supported in Quarkus out of the box. If you haven't already, please try again with [quarkiverse/quarkus-jdbc-sqlite](https://github.com/quarkiverse/quarkus-jdbc-sqlite), and if you still get the error, report an issue on that repository with a reproducer.

If the problem occurs even with the extension above and you're sure it uses the right Hibernate dialect, then you can consider [reporting to the Hibernate ORM project](https://hibernate.atlassian.net/browse/HHH). SQLite is only a [community dialect](https://github.com/hibernate/hibernate-orm/blob/8a0e4a9cdd2675e2ecc7bcb4e864024cdf74bbc8/dialects.adoc#community-dialects) though, so the Hibernate team is unlikely to fix it if a SQLLite user doesn't provide a patch.
