### ISSUE TITLE
Exception when specifying QUARKUS_OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc

### ISSUE THREAD

**Issue by cuichenli** [quarkusio/quarkus#36084]
### Describe the bug

When using the environment variable `QUARKUS_OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc` Quarkus will throw exception 
```
Caused by: java.lang.IllegalStateException: Only the GRPC Exporter is currently supported. Please check `otel.exporter.otlp.traces.protocol` property
	at io.quarkus.opentelemetry.runtime.exporter.otlp.OtlpRecorder.createOtlpGrpcSpanExporter(OtlpRecorder.java:110)
	at io.quarkus.opentelemetry.runtime.exporter.otlp.OtlpRecorder.installBatchSpanProcessorForOtlp(OtlpRecorder.java:61)
```

I think this issue has been resolved in https://github.com/quarkusio/quarkus/pull/35156 for 3.3.0, but for the older version, this is still causing issues. Can we implement a fix for the older versions? 

Looks like the logic at https://github.com/quarkusio/quarkus/blob/cca68dd37170d3d389fcf7117455ee798f6d055e/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java#L109 is a little bit wrong. Shouldn't the error be thrown when the protocol not equals to `grpc` instead? 

Thanks! Please feel free to correct me if I am getting any thing wrong here.  

### Expected behavior

No exception should be thrown

### Actual behavior

Exception thrown 

### Quarkus version or git rev

3.2

**Comment by brunobat** [comment]
[cuichenli](https://github.com/cuichenli) you mean: `QUARKUS_OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf`, right?

**Comment by cuichenli** [comment]
nope, the value i set is ` QUARKUS_OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc`

**Comment by brunobat** [comment]
Previously to Quarkus 3.3, with the previous exporter, there was only one protocol available. 
Due to the piping rewiring, it would be very difficult to backport.

**Comment by cuichenli** [comment]
Sorry I may miss something here, but I thought to backport a fix we just need to update 
```
 if (!exporterRuntimeConfig.traces().protocol().orElse("").equals(HTTP_PROTOBUF)) { 
```
to 
```
 if (!exporterRuntimeConfig.traces().protocol().orElse("").equals(GRPC)) { 

```

The original code basically means if the protocol is set to `grpc`, then it does not equal to `http/protobuf`, hence one exception would be thrown. 

Feel free to correct me if I am wrong.

**Comment by siewp** [comment]
I would like to work on this simple issue :)

**Comment by brunobat** [comment]
@siewp go for it!
