### ISSUE TITLE
in dev mode logs are frozen when a BuildStep is blocking

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#36086]
### Describe the bug

in dev mode, if the process gets longer (slow connection) it waits for as long as the download to show the logs:
![image](https://quarkusio.zulipchat.com/user_uploads/11321/Yd6AVaNvDbLaJ546NqqvVFo8/Kapture-2023-09-22-at-09.01.32.gif)

As a user it feels like a freeze if it gets longer.

in build, the logs are flowing making the download feels ok:
![image](https://quarkusio.zulipchat.com/user_uploads/11321/5N6oOKrmUWwE9RooNkSFaNyA/Kapture-2023-09-22-at-09.06.10.gif)

### Expected behavior

The logs should flow in both mode

### Actual behavior

it freezes

### How to Reproduce?

https://github.com/ia3andy/reproducer-slow-logs

you need to delete the .quinoa dir because it is what gets downloaded and show the logs slowness issue

```bash
rm -rf .quinoa
quarkus dev
```

**Comment by maxandersen** [comment]
@stuartwdouglas is this not kinda expected when a buildstep blocks that in/output are frozen because the main thread is not able to process stdout as its blocked?

**Comment by stuartwdouglas** [comment]
Can you try having the Quinoa code consume `LoggingSetupBuildItem`?

**Comment by ia3andy** [comment]
> Can you try having the Quinoa code consume LoggingSetupBuildItem?

@stuartwdouglas 

```
2023-09-28 08:54:59,041 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-09-28 08:54:59,477 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.ChainBuildException: Cycle detected:
		   io.quarkus.deployment.steps.CombinedIndexBuildStep#build produced class io.quarkus.deployment.builditem.CombinedIndexBuildItem
		to io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit produced class io.quarkus.deployment.logging.LoggingSetupBuildItem
		to io.quarkiverse.quinoa.deployment.QuinoaProcessor#install produced class io.quarkiverse.quinoa.deployment.items.InstalledPackageManagerBuildItem
		to io.quarkiverse.quinoa.deployment.devui.QuinoaDevUIProcessor#registerJsonRpcBackend produced class io.quarkus.devui.spi.JsonRPCProvidersBuildItem
		to io.quarkus.devui.deployment.DevUIProcessor#additionalBean produced class io.quarkus.deployment.builditem.AdditionalIndexedClassesBuildItem
		to io.quarkus.deployment.steps.CombinedIndexBuildStep#build
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:336)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:253)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:82)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:423)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.ChainBuildException: Cycle detected:
		   io.quarkus.deployment.steps.CombinedIndexBuildStep#build produced class io.quarkus.deployment.builditem.CombinedIndexBuildItem
		to io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit produced class io.quarkus.deployment.logging.LoggingSetupBuildItem
		to io.quarkiverse.quinoa.deployment.QuinoaProcessor#install produced class io.quarkiverse.quinoa.deployment.items.InstalledPackageManagerBuildItem
		to io.quarkiverse.quinoa.deployment.devui.QuinoaDevUIProcessor#registerJsonRpcBackend produced class io.quarkus.devui.spi.JsonRPCProvidersBuildItem
		to io.quarkus.devui.deployment.DevUIProcessor#additionalBean produced class io.quarkus.deployment.builditem.AdditionalIndexedClassesBuildItem
		to io.quarkus.deployment.steps.CombinedIndexBuildStep#build
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:375)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:348)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:379)
	at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:339)
	at io.quarkus.builder.BuildChainBuilder.build(BuildChainBuilder.java:249)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:142)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:332)
	... 9 more
```

FYI and this is important I think, in prod mode, it doesn't freeze, so I don't think it's the fact that it's blocking.

**Comment by ia3andy** [comment]
Also, even the logs before the blocking code don't appear, my guess it's that it's related to the dev terminal (resume test, ...) which shows at the bottom.

**Comment by ia3andy** [comment]
Ok I've fixed it by luck 🤪 (and found the guilty code 🕵️) 
```java
 @BuildStep(onlyIf = IsDevelopment.class)
    JsonRPCProvidersBuildItem registerJsonRpcBackend(InstalledPackageManagerBuildItem installedPackageManager,
            QuinoaConfig quinoaConfig) {
        DevConsoleManager.register("quinoa-install-action",
                install(installedPackageManager, quinoaConfig));
        return new JsonRPCProvidersBuildItem(QuinoaJsonRpcService.class);
    }

    private Function<Map<String, String>, String> install(InstalledPackageManagerBuildItem installedPackageManager,
            QuinoaConfig quinoaConfig) {
        return (map -> {
            try {
                final PackageManagerRunner packageManagerRunner = installedPackageManager.getPackageManager();

                // install or update packages
                packageManagerRunner.install();

                return "installed";
            } catch (Exception e) {
                return e.getMessage();
            }
        });
    }
```

Removing this block fixes the issue

**Comment by ia3andy** [comment]
@cescoffier @phillip-kruger you might have other extensions impacted by this

**Comment by cescoffier** [comment]
I don't have the context, but it might call the registered console on the event loop.

**Comment by ia3andy** [comment]
I'll re-open this issue in case there is an underlying problem which needs to be resolved.

**Comment by gsmet** [comment]
It hasn't been an issue in practice so far so let's close this one.
