### ISSUE TITLE
ConfigMapping property not found in quarkus 3.4.1 native mode and gradle

### ISSUE THREAD

**Issue by kristjanhk** [quarkusio/quarkus#36239]
### Describe the bug

Migrating from 3.3.3 to 3.4.1 mandatory config property values are not found when running in native mode. JVM mode works fine. When switching from gradle to maven then native mode also works as expected.

```
ERROR: Failed to start application (with profile [prod])
java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
        java.util.NoSuchElementException: SRCFG00014: The config property config.key is required but it could not be found in any config source
        at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:1001)
        at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:961)
        at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:961)
        at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:91)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:647)
        at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
        at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
        at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
```

### Expected behavior

Application should start up in native mode the same way as in JVM mode.

### Actual behavior

Application is not started because value was not found from application.properties file.

### How to Reproduce?

Reproducer: [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/12781321/code-with-quarkus.zip)

1. Create ConfigMapping and add value to application.properties
2. Build with `./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true`
3. Application fails to start in native mode

### Output of `java -version`

java 17.0.4 2022-07-19 LTS

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by gsmet** [comment]
@snazy any chance you could have a look at this one? It's Gradle-related and we have a reproducer.

**Comment by melloware** [comment]
I am seeing this in a Maven build as well not a Gradle build.

**Comment by kristjanhk** [comment]
Looks like Quarkus 3.4.3 fixed it for Gradle build. I wasn't able to reproduce it using Maven. 
If you still have problems then create a new issue.
