### ISSUE TITLE
Using Hibernate Panache Reactive with Virtual Threads causing "This method should exclusively be invoked from a Vert.x EventLoop thread; currently running on thread 'quarkus-virtual-thread-0'"

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#36258]
### Describe the bug

The examples regarding Virtual Threads are using the **RESTEasy Reactive** extension in combination with the **Hibernate Panache Classic** extension. However, **I'd like** to use the **Hibernate Panache Reactive** extension **instead** as **only parts of the application should be migrated to Virtual Threads for now**, while the rest should keep using the **reactive approach**.

I **haven't found any explicit mention that Quarkus Panache Reactive and Virtual Threads cannot work together at all**, so I assumed it somehow also works, although reactive code normally has to run on the event loop thread. 
Especially after finding this piece of documentation that explicitly mentions that you can use `uni.await().atMost(..)` within virtual threads:

> API returning Uni can be used directly using uni.await().atMost(…​). It blocks the virtual thread, without blocking the carrier thread, and also improves the resilience of your application with an easy (non-blocking) timeout support.

https://quarkus.io/guides/virtual-threads#use-virtual-thread-friendly-clients

It indeed works using Uni calls on the virtual thread, unless no database operations are in play.

Whenever I use Hibernate Reactive calls within a virtual thread, it complains with

> This method should exclusively be invoked from a Vert.x EventLoop thread; currently running on thread 'quarkus-virtual-thread-2'

as it **requires the event loop thread.**

**Can anything be done to shift reactive calls back onto the event-loop-thread from the virtual thread to be able to use Reactive Panache, or shouldn't this dependency (and probably other reactive dependencies) used with Virtual Threads at all?**

### Actual behavior

```
2023-10-03 10:27:21,964 ERROR [org.jbo.res.rea.ser.cor.RuntimeExceptionMapper] (quarkus-virtual-thread-2) An operation that needed be run on a Vert.x EventLoop thread was run on a worker pool thread. This likely means you need to annotate com.example.ExampleResource#reactiveVirtuals() with @io.smallrye.common.annotation.NonBlocking. Alternatively you can annotate the class com.example.ExampleResource to make every method on the class run on a Vert.x EventLoop thread, or annotate your sub class of the jakarta.ws.rs.core.Application class to affect the entire application
2023-10-03 10:27:21,964 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (quarkus-virtual-thread-2) HTTP Request to /reactive-virtual-entity failed, error id: 09344a90-a7fe-4893-94e4-d9e54fc46c9f-3: java.lang.IllegalStateException: HR000068: This method should exclusively be invoked from a Vert.x EventLoop thread; currently running on thread 'quarkus-virtual-thread-2'
	at org.hibernate.reactive.common.InternalStateAssertions.assertUseOnEventLoop(InternalStateAssertions.java:40)
	at org.hibernate.reactive.mutiny.impl.MutinySessionFactoryImpl.connection(MutinySessionFactoryImpl.java:139)
	at org.hibernate.reactive.mutiny.impl.MutinySessionFactoryImpl.lambda$openSession$0(MutinySessionFactoryImpl.java:90)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at org.hibernate.reactive.context.impl.VertxContext.execute(VertxContext.java:91)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.subscribe(UniRunSubscribeOn.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemConsume.subscribe(UniOnItemConsume.java:30)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
	at org.jboss.resteasy.reactive.server.handlers.UniResponseHandler.handle(UniResponseHandler.java:19)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.virtual.threads.ContextPreservingExecutorService$1.run(ContextPreservingExecutorService.java:36)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)


```

**Comment by cescoffier** [comment]
You cannot use hibernate reactive with virtual threads.

**Comment by cescoffier** [comment]
No, hibernate reactive is the only one. It's because it requires being called on the event loop. The other reactive APIs would switch to the event loop. 

Note that when using virtual thread, you can use any reactive API (except hibernate reactive) using .await().indefinitely()
