### ISSUE TITLE
Liquibase not playing nice with `H2` on version `3.4.1`

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#36292]
### Describe the bug

I'm trying to upgrade a small project I have that's currently using `Quarkus` version `3.3.3`. Everything works fine with that version, but as soon as I upgrade to `3.4.1`, I'm unable to run the `SQL` scripts as before because `Liquibase` states that table `databasechangelog` already exists 😑

### Expected behavior

Application should start and `Liquibase` should run successfully — because nothing changed (application-wise) between upgrades.

### Actual behavior

Application fail the `Liquibase` step(s) with:

```shell
2023-10-04 14:32:41,645 |- ERROR in io.quarkus.runtime.Application:197 [Quarkus Main Thread] - Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Error starting Liquibase
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:88)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy(Unknown Source)
	... 13 more
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Table "databasechangelog" already exists; SQL statement:
CREATE TABLE PUBLIC.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10)) [42101-220] [Failed SQL: (42101) CREATE TABLE PUBLIC.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]
	at liquibase.command.CommandScope.execute(CommandScope.java:236)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:223)
	at liquibase.Scope.lambda$child$0(Scope.java:197)
	at liquibase.Scope.child(Scope.java:206)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Liquibase.runInScope(Liquibase.java:1361)
	at liquibase.Liquibase.update(Liquibase.java:215)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:77)
	... 15 more
```

### How to Reproduce?

1. Setup a `Quarkus` application with `H2` and `Liquibase`
2. Place a `SQL` script for `Liquibase` to run at startup

This is the configuration I'm currently using:

```yaml
quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:${quarkus.application.name};DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DEFAULT_NULL_ORDERING=HIGH;MODE=PostgreSQL
    username: sa
  liquibase:
    change-log: database/migrations/changelog.xml
    clean-at-start: false
    default-schema-name: public
    migrate-at-start: true
    validate-on-migrate: true
```

### Output of `uname -a` or `ver`

Linux uplink 6.1.55-1-lts #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 16:57:15 +0000 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.3

**Comment by x80486** [comment]
Of course, I posted this before started playing with some settings :innocent:

Removing `DATABASE_TO_LOWER=TRUE;` will make this work:

```shell
No validation errors found.
Running Changeset: database/migrations/V00001__initial_schema_setup.sql::00001::liquibase

UPDATE SUMMARY
Run:                          1
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:            1

Liquibase: Update has been successful. Rows affected: 9
```

I guess this may be an issue with `Liquibase` itself and/or `H2`, because the current `H2` version [stills recommend](https://h2database.com/html/features.html) to use the parameters I'm currently using.

**Comment by gsmet** [comment]
Yeah, playing with the settings is what I was going to recommend when reading your report.

I don't think we can do anything on the Quarkus side. Might be worth discussing it with the Liquibase people first.

Thanks for taking the time to report back!
