### ISSUE TITLE
ARJUNA048006: cannot create new instance of com.arjuna.ats.internal.arjuna.objectstore.ShadowNoFileLockStore: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by parasjain27031994** [quarkusio/quarkus#36323]
### Describe the bug

I have a lambda function, deployed as a GraalVM native image on AWS. It seems, while trying to release transaction we are getting following exception :

```posh
2023-10-06 08:48:53,390 DEBUG [org.hib.eng.tra.int.TransactionImpl] (Lambda Thread (NORMAL)) On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
--
2023-10-06 08:48:53,390 DEBUG [org.hib.res.jdb.int.LogicalConnectionManagedImpl] (Lambda Thread (NORMAL)) Initiating JDBC connection release from beforeTransactionCompletion
2023-10-06 08:49:03,315 WARN  [com.arj.ats.common] (Lambda Thread (NORMAL)) ARJUNA048006: cannot create new instance of com.arjuna.ats.internal.arjuna.objectstore.ShadowNoFileLockStore: java.lang.reflect.InvocationTargetException
at java.base@17.0.8/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base@17.0.8/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at com.arjuna.common.internal.util.ClassloadingUtility.loadAndInstantiateClass(ClassloadingUtility.java:114)
at com.arjuna.ats.arjuna.objectstore.StoreManager.initStore(StoreManager.java:137)
at com.arjuna.ats.arjuna.objectstore.StoreManager.getActionStore(StoreManager.java:96)
at com.arjuna.ats.arjuna.objectstore.StoreManager.getParticipantStore(StoreManager.java:66)
at com.arjuna.ats.arjuna.coordinator.BasicAction.getStore(BasicAction.java:396)
at com.arjuna.ats.arjuna.coordinator.BasicAction.prepare(BasicAction.java:2175)
at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1526)
at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:74)
at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:138)
at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:171)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
at com.refinitiv.research.lambda.service.ItopEligibilityService_Subclass.validateEligibility(Unknown Source)
at com.refinitiv.research.lambda.service.ItopEligibilityService_ClientProxy.validateEligibility(Unknown Source)
at com.refinitiv.research.lambda.Handler.handleRequest(Handler.java:56)
at com.refinitiv.research.lambda.Handler.handleRequest(Handler.java:22)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:167)
at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:142)
at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
Caused by: com.arjuna.ats.arjuna.exceptions.ObjectStoreException: ARJUNA012225: FileSystemStore::setupStore - cannot access root of object store: ObjectStore/ShadowNoFileLockStore/defaultStore/
at com.arjuna.ats.internal.arjuna.objectstore.FileSystemStore.<init>(FileSystemStore.java:609)
at com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore.<init>(ShadowingStore.java:628)
at com.arjuna.ats.internal.arjuna.objectstore.ShadowNoFileLockStore.<init>(ShadowNoFileLockStore.java:29)
... 33 more
2023-10-06 08:49:03,315 INFO  [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (NORMAL)) Lambda polling thread complete (NORMAL)
Exception in thread "Lambda Thread (NORMAL)" com.arjuna.ats.arjuna.exceptions.FatalError: ARJUNA012391: Could not initialize object store 'null' of type 'com.arjuna.ats.internal.arjuna.objectstore.ShadowNoFileLockStore'
at com.arjuna.ats.arjuna.objectstore.StoreManager.initStore(StoreManager.java:145)
at com.arjuna.ats.arjuna.objectstore.StoreManager.getActionStore(StoreManager.java:96)
at com.arjuna.ats.arjuna.objectstore.StoreManager.getParticipantStore(StoreManager.java:66)
at com.arjuna.ats.arjuna.coordinator.BasicAction.getStore(BasicAction.java:396)
at com.arjuna.ats.arjuna.coordinator.BasicAction.prepare(BasicAction.java:2175)
at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1526)
at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:74)
at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:138)
at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:406)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:171)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
at com.refinitiv.research.lambda.service.ItopEligibilityService_Subclass.validateEligibility(Unknown Source)
at com.refinitiv.research.lambda.service.ItopEligibilityService_ClientProxy.validateEligibility(Unknown Source)
at com.refinitiv.research.lambda.Handler.handleRequest(Handler.java:56)
at com.refinitiv.research.lambda.Handler.handleRequest(Handler.java:22)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:167)
at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:142)
at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
2023-10-06 08:49:52,354 WARN  [com.arj.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffffa9fe9a11:8c2f:651fc9f4:0 in state  RUN
```

Moreover, the execution seems to be in hung state as there are no logs and lambda times out after 900 seconds.
The error des not seem to occur in JVM mode when run locally.

### Expected behavior

The function should execute w/o transaction errors.

### Actual behavior

The execution hangs with " ARJUNA048006: cannot create new instance of com.arjuna.ats.internal.arjuna.objectstore.ShadowNoFileLockStore: java.lang.reflect.InvocationTargetException" exception.

### Output of `java -version`

17.0.8+7

### GraalVM version (if different from Java)

OpenJDK Runtime Environment Mandrel-23.0.1.2-Final (build 17.0.8+7)
OpenJDK 64-Bit Server VM Mandrel-23.0.1.2-Final (build 17.0.8+7, mixed mode)

### Quarkus version or git rev

3.4.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: C:\Users\Paras_Jain\.m2\wrapper\dists\apache-maven-3.9.3-bin\54p6kc7m0ap3os8bc4ge28ia2\apache-maven-3.9.3 Java version: 17.0.8, vendor: Oracle Corporation, runtime: C:\dev\graalvm-jdk-17.0.8+9.1 Default locale: en_IN, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

Extensions used :
Installed features: [agroal, amazon-lambda, amazon-s3, amazon-secretsmanager, cdi, config-yaml, hibernate-orm, hibernate-orm-panache, hibernate-validator, jdbc-mssql, narayana-jta, smallrye-context-propagation, spring-data-jpa, spring-di]

**Comment by parasjain27031994** [comment]
I seem to have figure out the issue. It seems that for locking, the Transaction Manager seems to create files in file storage. In my local machine it is able to do so, while it fails in AWS Lambda, hence the execution hangs even with exception.

As a work around, disabling the transaction works fine.

Probably if there are configuration which can be defined to let the transaction manager know the location to create lock file might work with AWS Lambda.

**Comment by jmfinelli** [comment]
> I seem to have figure out the issue. It seems that for locking, the Transaction Manager seems to create lock file in file storage. In my local machine it is able to do so, while it fails in AWS Lambda, hence the execution hangs even with exception.
> 
> As a work around, disabling the transaction works fine.
> 
> Probably if there are configuration which can be defined to let the transaction manager know the location to create lock file might work with AWS Lambda.

I suppose you are not sharing your object store among multiple environments/processes/JVM. In that case, could you please try the `BasicLockStore` [implementation](https://www.narayana.io//docs/project/index.html#d5e712) and see if that solves the issue?

**Comment by mmusgrov** [comment]
We initialise the store using reflection and our logging of failures doesn't always capture the underlying cause. Is this something we could run in a debugger to see what the actual cause of the exception is?

**Comment by parasjain27031994** [comment]
> We initialise the store using reflection and our logging of failures doesn't always capture the underlying cause. Is this something we could run in a debugger to see what the actual cause of the InvocationTargetException is?

The error seems to only occur in the AWS Lambda function itself and not in local. Do you have any documentation that can be followed for debug in Lambda Runtime ?
My suspicion is the lambda storage ( file system) we have access to "/tmp" directory. 
The ephemeral storage is available in each function’s /tmp directory.
Perhaps  the location is the problem ?

**Comment by mmusgrov** [comment]
Would it  be possible for you to check that by changing the location of the store using the [object-store.directory](https://quarkus.io/guides/all-config#quarkus-narayana-jta_quarkus.transaction-manager.object-store.directory) property?

**Comment by mmusgrov** [comment]
Remark, the next release of narayana will include a change to report the underlying cause of store initialisation failures via the exception trace.

**Comment by parasjain27031994** [comment]
I do not see this issue in latest version of Quarkus anymore.

**Comment by mmusgrov** [comment]
> Would it be possible for you to check that by changing the location of the store using the [object-store.directory](https://quarkus.io/guides/all-config#quarkus-narayana-jta_quarkus.transaction-manager.object-store.directory) property?

 @parasjain27031994  Did you try doing this?

**Comment by mmusgrov** [comment]
> I do not see this issue in latest version of Quarkus anymore.

I'm not sure what you mean, but if you are asking "is the narayana change to provide improved error reporting available in the latest quarkus release" then no - narayana releases are independent of quarkus releases. But I will say that you need to help us by responding to my earlier request - note that the narayana change just provides an improved error message, it won't necessarily resolve you problem.
