### ISSUE TITLE
Calling redis gives "ERR unknown command 'watch'" when upgrading from quarkus 3.3.2 to 3.4.2

### ISSUE THREAD

**Issue by hugin78** [quarkusio/quarkus#36324]
### Describe the bug

From imperative code, we call a reactive method annotated with @CacheResult. This works fine with quarkus 3.3.2, but when we upgrade to 3.4.2 (not changing any thing else than the quarkus version) we get this error when accessing our sentinel redis from the application:

Caused by: ERR unknown command 'watch', with args beginning with: 'cache:get-cpr-number-cache:2120-02-02-04.24.28.23145' 

### Expected behavior

Expect the redis interaction to work with quarkus 3.4.2 as it does with quarkus 3.3.2

### Actual behavior

Throw exception with "unknown command 'watch'"

### How to Reproduce?

We have a redis installed in kubernetes in a sentinel setup with three pods, using this image:

```
_image:
   registry: docker.io
   repository: bitnami/redis
   tag: 7.2-debian-11_
```
In quarkus we configure the integration with:

```
_quarkus.cache.type=redis
quarkus.redis.max-nested-arrays=16
quarkus.redis.hosts=redis://redis:26379
quarkus.redis.client-type=sentinel
quarkus.redis.password=${REDIS_AUH_PASSWORD}
// The number of nodes in our sentinel cluster
quarkus.redis.max-pool-size=3
// Clean the redis pool queue every 2 seconds, hopefully freeing resources to 
// Our other reactive threads
quarkus.redis.pool-cleaner-interval=2S
// There is per default no timeout on the blocking redis calls
// Since, the idea with the cache is speed, 1 second timeout should be fine
quarkus.redis.timeout=1S
// We have a fairly simple redis setup, so we don't have that many
// arrays within arrays. Lowering this from 32 helps with our perfomance
quarkus.redis.max-nested-arrays=16_
```

From our application we call this reactive cache annotated method from imperative code:

```
@CacheResult(cacheName = "get-cpr-number-cache")
public Uni<String> getCprNumber(String customerId) {
    return ....
}

```
When upgrading the quarkus version we get this exception:

```
         ...
	Caused by: jakarta.ws.rs.InternalServerErrorException: Failed to fetch cpr for customerId:  2120-02-02-04.24.28.23145
	at dk.bankdata.drb.external.metadata.MetaDataFacade.lambda$getCprNumber$6(MetaDataFacade.java:112)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnFailureTransform$UniOnFailureTransformProcessor.onFailure(UniOnFailureTransform.java:54)
	at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap$UniOnFailureFlatMapProcessor.dispatch(UniOnFailureFlatMap.java:85)
	at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap$UniOnFailureFlatMapProcessor.onFailure(UniOnFailureFlatMap.java:60)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
	at io.smallrye.mutiny.operators.uni.UniOnTerminationCall$UniOnTerminationCallProcessor.lambda$onFailure$3(UniOnTerminationCall.java:79)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:73)
	at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
	at io.vertx.core.impl.future.SucceededFuture.onComplete(SucceededFuture.java:81)
	at io.vertx.redis.client.RedisConnection.close(RedisConnection.java:127)
	at io.vertx.mutiny.redis.client.RedisConnection.lambda$close$14(RedisConnection.java:266)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.vertx.AsyncResultUni.subscribe(AsyncResultUni.java:31)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
	at io.smallrye.mutiny.operators.uni.UniOnTerminationCall$UniOnTerminationCallProcessor.onFailure(UniOnTerminationCall.java:78)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
	at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:37)
	at io.smallrye.mutiny.vertx.DelegatingHandler.handle(DelegatingHandler.java:25)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onFailure(FutureImpl.java:268)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.Transformation$1.onFailure(Transformation.java:67)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:191)
	at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
	at io.vertx.core.impl.future.Transformation.onFailure(Transformation.java:56)
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 more
Caused by: ERR unknown command 'watch', with args beginning with: 'cache:get-cpr-number-cache:2120-02-02-04.24.28.23145'
```

        

### Output of `uname -a` or `ver`

Linux wealth-items-service-654c5759c8-nlrkg 4.18.0-372.69.1.el8_6.x86_64 #1 SMP Thu Aug 3 16:12:43 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.8" 2023-07-18 LTS

### Quarkus version or git rev

3.4.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by cescoffier** [comment]
Can you provide a simple standalone reproducer?

**Comment by geoand** [comment]
Closing for lack of feedback

**Comment by sebastian639559** [comment]
I have got the same issue. Unfortunately, I am unable to provide a standalone reproducer. Since I dont believe this is a bug, I am just seeking help in terms of what might cause this error and how to fix it. 

Any help as to what might be wrong is highly appreciated. 

**Here is some more information:**
When a method is called annotated with 
```
@CacheResult(...)
```
, then you get 
```
Caused by: ERR unknown command 'watch', with args beginning with: 'cache:get-cpr-number-cache:2120-02-02-04.24.28.23145'
```

When a method is called annotated with 
```
@CacheInvalidateAll(...)
```
, then you get 
```
Caused by: ERR unknown command `keys`, with args beginning with: cache:my-cache5:*
```

-----------

When starting our redis instance up in a docker image, this is the initial start prompt: 
(I censored some with *****)
(Noteworthy is that the redis version is 6.2.6)
```
09:48:15.13 WARN ==> bitnami-redis-headless.**********.svc.cluster.local does not contain the IP of this pod: *****
09:48:20.15 INFO ==> about to run the command: redis-cli -h bitnami-redis.********.svc.cluster.local -p 26379 sentinel master mymaster
09:48:20.21 INFO ==> Redis master is up now
09:48:20.21 INFO ==> about to run the command: redis-cli -h bitnami-redis.**********.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
09:48:20.24 INFO ==> printing REDIS_SENTINEL_INFO=(bitnami-redis-node-1.bitnami-redis-headless.*******.svc.cluster.local,6379)
1:C 19 Dec 2023 09:48:20.316 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 19 Dec 2023 09:48:20.316 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
```

**Comment by Ladicek** [comment]
The Vert.x Redis client has a bug in its configuration initialization, where the default values of `quarkus.redis.master-name` or `quarkus.redis.role` are not set properly. This bug should be fixed by these PRs:

- https://github.com/vert-x3/vertx-redis-client/pull/428
- https://github.com/vert-x3/vertx-redis-client/pull/429

The `quarkus.redis.master-name` setting should default to `mymaster`, and since I followed the Redis documentation, my "master set" is called `mymaster`, so that's what I used when trying to reproduce.

The `quarkus.redis.role` setting should default to `master`, which is the only sensible setting for a Redis-backed cache, because both read and write operations need to happen. (For read-only operations, a role of `replica` would also make sense.)

When I configure `quarkus.redis.role=sentinel`, I'm essentially asking the Redis client to connect directly to the sentinel servers instead of the actual Redis servers guarded by the sentinels. A sentinel server clearly doesn't understand normal Redis commands (such as `watch` or `keys`), so it's going to fail. When I do that, I observe the same behavior described in this issue.

No comment above mentions `quarkus.redis.master-name` or `quarkus.redis.role`, but it seems clear that `quarkus.redis.role` must have been set to `sentinel`, which is wrong (see previous paragraph).

Please set `quarkus.redis.role=master` for now (together with explicit setting of `quarkus.redis.master-name`). This should be fixed in the future, when the Vert.x Redis client are merged and Vert.x is updated in Quarkus.
