### ISSUE TITLE
quarkus.otel.traces.sampler.arg doesn't support String value (e.g. cannot configure "jaeger_remote" sampler)

### ISSUE THREAD

**Issue by calohmn** [quarkusio/quarkus#36335]
### Describe the bug

The [Quarkus OpenTelemetry Configuration Reference](https://quarkus.io/guides/opentelemetry#configuration-reference) mentions that the `quarkus.*` properties match the ones from the [OpenTelemetry SDK Autoconfigure](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md).

In the AutoConfigure SDK [sampler](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler) configuration section, the `otel.traces.sampler.arg` property isn't explicitly restricted to having a number/double value.
In fact, in the OpenTelemetry Specification 1.25.0, section [General SDK Configuration](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#general-sdk-configuration), the `OTEL_TRACES_SAMPLER_ARG` env var is described as possibly containing a comma separated list in case of the `jaeger_remote` and `parentbased_jaeger_remote` samplers.

But the [quarkus.otel.traces.sampler.arg](https://quarkus.io/guides/opentelemetry#quarkus-opentelemetry_quarkus.otel.traces.sampler.arg) configuration property explicitly has a `double` type.

That means that a configuration of 
```
quarkus.otel.traces.sampler: "jaeger_remote"
quarkus.otel.traces.sampler.arg: "endpoint=http://hono-jaeger:14250"
```
isn't supported and leads to this exception on startup:
```
ERROR: Failed to start application (with profile [prod])
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.lang.IllegalArgumentException: SRCFG00039: The config property quarkus.otel.traces.sampler.arg with the config value "endpoint=http://hono-jaeger:14250" threw an Exception whilst being converted SRCFG00031: Expected a double value, got "endpoint=http://hono-jaeger:14250"
	at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:1003)
	at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:959)
	at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:959)
	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:91)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:630)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	... 13 more
```

### Expected behavior

`quarkus.otel.traces.sampler.arg` not being restricted to a `double` type.

### Actual behavior

Setting `quarkus.otel.traces.sampler.arg` to a String value leads to an exception on startup.

### How to Reproduce?

Use a configuration like
```
quarkus.otel.traces.sampler: "jaeger_remote"
quarkus.otel.traces.sampler.arg: "endpoint=http://hono-jaeger:14250"
```

### Quarkus version or git rev

3.2.6

**Comment by brunobat** [comment]
@calohmn, If I understood well, you are using a custom sampler and need the `arg` to pass a string that can be used inside the custom sampler, right?

**Comment by hiteshkhatri97** [comment]
@brunobat If anyone else has not yet picked up, can I work on this issue?

**Comment by brunobat** [comment]
Hi @hiteshkhatri97, sure, you can work on it.
