### ISSUE TITLE
REST Client with generic subresource fails with InvalidRestClientDefinitionException

### ISSUE THREAD

**Issue by slinstaedt** [quarkusio/quarkus#36343]
### Describe the bug

Given the following REST client definition:

```java
@Path("api")
@RegisterRestClient
public interface TestApi {

	interface GenericFunction<R> {

		@GET
		R get();
	}

	@Path("get")
	GenericFunction<String> subresource();
}
```

fails during invocation (not deployment, yikes) with:
```posh
Caused by: org.jboss.resteasy.reactive.client.api.InvalidRestClientDefinitionException: Failed to generate client for class interface org.acme.TestApi : Sub resource type is not a class: org.acme.TestApi$GenericFunction
        at org.jboss.resteasy.reactive.client.impl.ClientProxies.get(ClientProxies.java:29)
        at org.jboss.resteasy.reactive.client.impl.WebTargetImpl.proxy(WebTargetImpl.java:449)
        at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:386)
        ... 38 more
```

Due to the fact, that the actual type argument is a very concrete class, I suspect the extension the unresolved `GenericFunction#get` method of the class itself being checked (returning a type variable of course) instead of the actual parameterized type, which is returned by `TestApi#subresource`.

If I change the REST client definition to the following, everything works of course:
```java
@Path("api")
@RegisterRestClient
public interface TestApi {

	interface SimpleFunction {

		@GET
		String get();
	}

	@Path("get")
	SimpleFunction subresource();
}
```

### Expected behavior

As the given generic subresource is a valid subresource locator with a valid subresource method when implementing this API as an API provider, I would expect this API interface being a valid defintion for a REST client too. For this generic use case, all static information are available to resolve the the subresource method's type variable at deployment time to String, not some unbound type variable. The `quarkus-resteasy-reactive` extension is able to do so, but not the `quarkus-rest-client-reactive` extension.

### Actual behavior

Fails with the beforementioned exception during invocation time :/ 

### Output of `uname -a` or `ver`

Darwin sl-macbook.fritz.box 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:39:54 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T8112 arm64

### Output of `java -version`

openjdk version "17.0.8.1" 2023-08-24 OpenJDK Runtime Environment Homebrew (build 17.0.8.1+0) OpenJDK 64-Bit Server VM Homebrew (build 17.0.8.1+0, mixed mode, sharing)

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by geoand** [comment]
I am pretty sure it will be easy to fix, but do you mind adding a sample application that we can use to test against?

Thanks

**Comment by slinstaedt** [comment]
Not at all. Give me an hour to prepare one.

**Comment by slinstaedt** [comment]
https://github.com/slinstaedt/quarkus-issue-36343

Interestingly no endpoint is showing up in the dev ui, but in the swagger ui. But I guess that's another bug.

**Comment by geoand** [comment]
Turns out this is a lot more difficult to fix that expected...

**Comment by slinstaedt** [comment]
`org.apache.commons.lang3.reflect.TypeUtils` and `com.google.common.reflect.TypeResolver` provide all the tools normally necessary for resolving type variables to their concrete usage. I am not sure, if they can be used by the rest client extension at least at deployment time, because both of them use reflection of course.

**Comment by geoand** [comment]
That's not the problem, we can easily determine the types we need at build time.
The problem is getting the information to the proper place

**Comment by geoand** [comment]
All true, but still that's not the problem
