### ISSUE TITLE
Quarkus ignores environment property "consul-config.agent.host-port" on Kubernetes

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#36359]
### Describe the bug

I have an application, which uses consul, I use property "quarkus.consul-config.agent.host-port" to provide the application with path to deployed consul instance. Starting from 6 or 7 of October, when I deploy this app on Openshift using 999-SNAPSHOT build, the app can not retrieve this property and fails to start.
The property is stored in openshift DeploymentConfig as "template.spec.containers.env.name".
If the property is put into property file, or the property variable inside the yaml is renamed into "QUARKUS_CONSUL_CONFIG_AGENT_HOST_PORT", then everything works fine.

### Expected behavior

Application starts succefully

### Actual behavior

Application fails with the following error:

```
16:07:48,407 INFO  [app] java.lang.RuntimeException: Failed to start quarkus
16:07:48,408 INFO  [app] 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
16:07:48,408 INFO  [app] 	at io.quarkus.runtime.Application.start(Application.java:101)
16:07:48,409 INFO  [app] 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
16:07:48,409 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
16:07:48,409 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
16:07:48,410 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
16:07:48,410 INFO  [app] 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
16:07:48,411 INFO  [app] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:07:48,411 INFO  [app] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
16:07:48,411 INFO  [app] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:07:48,412 INFO  [app] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
16:07:48,412 INFO  [app] 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
16:07:48,413 INFO  [app] 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
16:07:48,413 INFO  [app] Caused by: java.lang.RuntimeException: An error occurred while attempting to fetch configuration from Consul.
16:07:48,413 INFO  [app] 	at io.quarkus.consul.config.runtime.ConsulConfigSourceFactory.getConfigSources(ConsulConfigSourceFactory.java:82)
16:07:48,414 INFO  [app] 	at io.quarkus.consul.config.runtime.ConsulConfigSourceFactory.getConfigSources(ConsulConfigSourceFactory.java:28)
16:07:48,414 INFO  [app] 	at io.quarkus.consul.config.runtime.ConsulConfigSourceFactory.getConfigSources(ConsulConfigSourceFactory.java:19)
16:07:48,415 INFO  [app] 	at io.smallrye.config.ConfigSourceFactory$ConfigurableConfigSourceFactory.getConfigSources(ConfigSourceFactory.java:58)
16:07:48,415 INFO  [app] 	at io.smallrye.config.ConfigurableConfigSource.getConfigSources(ConfigurableConfigSource.java:50)
16:07:48,416 INFO  [app] 	at io.smallrye.config.SmallRyeConfig$ConfigSources.mapLateSources(SmallRyeConfig.java:687)
16:07:48,416 INFO  [app] 	at io.smallrye.config.SmallRyeConfig$ConfigSources.<init>(SmallRyeConfig.java:577)
16:07:48,416 INFO  [app] 	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:68)
16:07:48,417 INFO  [app] 	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:698)
16:07:48,417 INFO  [app] 	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
16:07:48,417 INFO  [app] 	at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
16:07:48,418 INFO  [app] 	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
16:07:48,418 INFO  [app] 	... 13 more
16:07:48,419 INFO  [app] Caused by: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8500
16:07:48,419 INFO  [app] 	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:79)
16:07:48,420 INFO  [app] 	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
16:07:48,420 INFO  [app] 	at io.quarkus.consul.config.runtime.ConsulConfigSourceFactory.getConfigSources(ConsulConfigSourceFactory.java:79)
16:07:48,420 INFO  [app] 	... 24 more
16:07:48,421 INFO  [app] Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8500
16:07:48,422 INFO  [app] Caused by: java.net.ConnectException: Connection refused
16:07:48,422 INFO  [app] 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
16:07:48,422 INFO  [app] 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
16:07:48,423 INFO  [app] 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
16:07:48,423 INFO  [app] 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
16:07:48,424 INFO  [app] 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
16:07:48,424 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
16:07:48,425 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
16:07:48,425 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
16:07:48,425 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
16:07:48,426 INFO  [app] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
16:07:48,426 INFO  [app] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
16:07:48,427 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
16:07:48,427 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

1. ` git clone git@github.com:quarkus-qe/quarkus-test-framework.git`
2. `mvn clean install -Pframework`
3. Log in into openshift
This fails: " mvn clean install -Pexamples,openshift -pl examples/consul/ -Dit.test=OpenShiftGreetingResourceIT -Dquarkus.platform.version=999-SNAPSHOT"
This works as expected: `mvn clean install -Pexamples,openshift -pl examples/consul/ -Dit.test=OpenShiftGreetingResourceIT -Dquarkus.platform.version=3.4.2`

If option `-Dts.global.delete.folder.on.exit=false` is added, then yaml file `examples/consul/target/OpenShiftGreetingResourceIT/app/openshift.yml` contains deployment config
By default, the project is cleared afterwards, add `-Dts.openshift.delete.project.after.all=false -Dts.openshift.ephemeral.namespaces.enabled=false` to use the persistent one

### Output of `uname -a` or `ver`

6.4.14-200.fc38.x86_64

### Output of `java -version`

17.0.5, vendor: GraalVM Community

### Quarkus version or git rev

6be99a4aeb0107e3104e05dd7cd50e6b8f1533a1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

**Comment by fedinskiy** [comment]
Commit 39381f9aff920d414bd5de7975df9a82c7b26260 is not affected, so I presume this is caused by https://github.com/quarkusio/quarkus/pull/35322

**Comment by radcortez** [comment]
I'll have a look.

**Comment by fedinskiy** [comment]
Addition: this affect all "quarkus.*" properties, not just "consul-config.agent.host-port"

**Comment by radcortez** [comment]
> I have an application, which uses consul, I use property "quarkus.consul-config.agent.host-port" to provide the application with path to deployed consul instance. Starting from 6 or 7 of October, when I deploy this app on Openshift using 999-SNAPSHOT build, the app can not retrieve this property and fails to start.

Are you using precisely this property name? `quarkus.consul-config.agent.host-port`, or is it the environment variable name?

> The property is stored in openshift DeploymentConfig as "template.spec.containers.env.name".

Are you setting environment variable names in dotted format?

> If the property is put into property file, or the property variable inside the yaml is renamed into "QUARKUS_CONSUL_CONFIG_AGENT_HOST_PORT", then everything works fine.

From the last comment, I'm guessing that you are using `quarkus.consul-config.agent.host-port` in a source that should only take Environment Variables as `QUARKUS_CONSUL_CONFIG_AGENT_HOST_PORT`. It may have worked in the past, but this was never intended to work...

**Comment by fedinskiy** [comment]
@radcortez yes, the app uses environment variables in dotted format and for some reason this worked (presumably for a long time).
I agree, that this is strange, but we should probably document, that it doesn't work anymore.

**Comment by radcortez** [comment]
Sure. Feel free to document it. Thanks!

**Comment by fedinskiy** [comment]
That should go to release notes I suppose. Who is handling that for Quarkus and how do I contact that person?

**Comment by radcortez** [comment]
Release notes are added here:
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.5

Are you able to edit and add the notes in the `Config` section?

**Comment by fedinskiy** [comment]
No, I can not.

I prepared a note, could you add it into the guide?

```
System properties can not be used as environmental variables anymore.

For some time, it was possible to have quarkus environment variables in dotted.lower-case (style, used for system properties) and such variables were read and accepted by Quarkus. This was accidental and against specifications[1], and was removed in this release. From now on, Quarkus accepts environment variables only in SCREAMING_SNAKE_CASE.

[1] https://quarkus.io/guides/config-reference#system-properties
```

**Comment by janderssonse** [comment]
This helped me, we have tons of config envs in the x.y.z-format to change to X_Y_Z now. While the release notes makes it quite clear, @radcortez @fedinskiy last note should really be a added to the https://quarkus.io/guides/config-reference#environment-variables documentation paragraph, as it stil gives examples of envrionment naming resolutions in x.Y.Z-formats. And so, people that didn't read every release note will contiinue trying that format. @radcortez Should I open a seperate issue regadring environment documentation?

**Comment by radcortez** [comment]
> This helped me, we have tons of config envs in the x.y.z-format to change to X_Y_Z now.

You may want to hold that change :)

I was not aware that so many users were relying on this, so I reaaded the support in https://github.com/quarkusio/quarkus/pull/36917.

**Comment by janderssonse** [comment]
Thanks @radcortez , I have now read the whole thread at https://github.com/quarkusio/quarkus/pull/36917 , and that docker handling with mixed mode was surely interesting, I can see why you want to add the dot-support back.  We already started the posix compatible  journey as we are deploying that version atm,  (and to be honest I prefer the X_Y_Z convention, posix compatible and all.

**Comment by radcortez** [comment]
Great :)
