### ISSUE TITLE
[GraalVM 24.0] Native integration tests using flyway fail to build

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#36418]
### Describe the bug

We see various flyway related build failures in native integration tests when running on GraalVM for JDK 22 (24.0). The build failure looks like this:

```
========================================================================================================================
GraalVM Native Image: Generating 'quarkus-integration-test-hibernate-orm-tenancy-datasource-999-SNAPSHOT-runner' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------
[1/8] Initializing...                                                                                   (15.0s @ 0.20GB)
 Java version: 21+35, vendor version: GraalVM CE 21-dev+35.1
 Graal compiler: optimization level: 2, target machine: x86-64-v3
 C compiler: gcc (linux, x86_64, 11.4.0)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 7 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.quarkus.caffeine.runtime.graal.CacheConstructorsFeature
 - io.quarkus.hibernate.orm.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
 - org.eclipse.angus.activation.nativeimage.AngusActivationFeature
 - org.hibernate.graalvm.internal.GraalVMStaticFeature: Hibernate ORM's static reflection registrations for GraalVM
------------------------------------------------------------------------------------------------------------------------
 4 experimental option(s) unlocked:
 - '-H:+AllowFoldMethods' (origin(s): command line)
 - '-H:BuildOutputJSONFile' (origin(s): command line)
 - '-H:-UseServiceLoaderFeature' (origin(s): command line)
 - '-H:ReflectionConfigurationResources' (origin(s): 'META-INF/native-image/io.netty/netty-transport/native-image.properties' in 'file:///home/runner/work/mandrel/mandrel/quarkus/integration-tests/hibernate-orm-tenancy/datasource/target/quarkus-integration-test-hibernate-orm-tenancy-datasource-999-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-transport-4.1.97.Final.jar')
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 4.44GB of memory (65.8% of 6.76GB system memory, set via '-Xmx5g')
 - 2 thread(s) (100.0% of 2 available processor(s), determined at start)
03:01:59,023 WARN  [org.hib.orm.deprecation] HHH90000025: MariaDBDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
03:01:59,100 WARN  [org.hib.orm.deprecation] HHH90000025: MariaDBDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
[2/8] Performing analysis...  [*****]                                                                  (154.2s @ 2.11GB)
   22,408 reachable types   (89.9% of   24,918 total)
   32,262 reachable fields  (63.0% of   51,216 total)
  110,751 reachable methods (55.1% of  201,040 total)
    6,974 types,   321 fields, and 4,436 methods registered for reflection
       61 types,    59 fields, and    55 methods registered for JNI access
        4 native libraries: dl, pthread, rt, z

Error: Unsupported features in 2 methods
Detailed message:
Error: Discovered unresolved type during parsing: org.apache.commons.logging.LogFactory. This error is reported at image build time because class org.flywaydb.core.internal.logging.apachecommons.ApacheCommonsLogCreator is registered for linking at image build time by command line and command line.
Error encountered while parsing org.flywaydb.core.internal.logging.apachecommons.ApacheCommonsLogCreator.createLogger(ApacheCommonsLogCreator.java:24) 
Parsing context:
   at static root method.(Unknown Source)

Error: Discovered unresolved type during parsing: org.apache.logging.log4j.LogManager. This error is reported at image build time because class org.flywaydb.core.internal.logging.log4j2.Log4j2LogCreator is registered for linking at image build time by command line and command line.
Error encountered while parsing org.flywaydb.core.internal.logging.log4j2.Log4j2LogCreator.createLogger(Log4j2LogCreator.java:24) 
Parsing context:
   at static root method.(Unknown Source)


com.oracle.svm.core.util.UserError$UserException: Unsupported features in 2 methods
Detailed message:
Error: Discovered unresolved type during parsing: org.apache.commons.logging.LogFactory. This error is reported at image build time because class org.flywaydb.core.internal.logging.apachecommons.ApacheCommonsLogCreator is registered for linking at image build time by command line and command line.
Error encountered while parsing org.flywaydb.core.internal.logging.apachecommons.ApacheCommonsLogCreator.createLogger(ApacheCommonsLogCreator.java:24) 
Parsing context:
   at static root method.(Unknown Source)

Error: Discovered unresolved type during parsing: org.apache.logging.log4j.LogManager. This error is reported at image build time because class org.flywaydb.core.internal.logging.log4j2.Log4j2LogCreator is registered for linking at image build time by command line and command line.
Error encountered while parsing org.flywaydb.core.internal.logging.log4j2.Log4j2LogCreator.createLogger(Log4j2LogCreator.java:24) 
Parsing context:
   at static root method.(Unknown Source)


	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:831)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:597)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:555)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:538)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
------------------------------------------------------------------------------------------------------------------------
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 2 methods
Detailed message:
Error: Discovered unresolved type during parsing: org.apache.commons.logging.LogFactory. This error is reported at image build time because class org.flywaydb.core.internal.logging.apachecommons.ApacheCommonsLogCreator is registered for linking at image build time by command line and command line.
Error encountered while parsing org.flywaydb.core.internal.logging.apachecommons.ApacheCommonsLogCreator.createLogger(ApacheCommonsLogCreator.java:24) 
Parsing context:
   at static root method.(Unknown Source)

Error: Discovered unresolved type during parsing: org.apache.logging.log4j.LogManager. This error is reported at image build time because class org.flywaydb.core.internal.logging.log4j2.Log4j2LogCreator is registered for linking at image build time by command line and command line.
Error encountered while parsing org.flywaydb.core.internal.logging.log4j2.Log4j2LogCreator.createLogger(Log4j2LogCreator.java:24) 
Parsing context:
   at static root method.(Unknown Source)


	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:826)
	... 6 more
                       43.7s (25.5% of total time) in 220 GCs | Peak RSS: 3.56GB | CPU load: 1.89
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/runner/work/mandrel/mandrel/quarkus/integration-tests/hibernate-orm-tenancy/datasource/target/quarkus-integration-test-hibernate-orm-tenancy-datasource-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-hibernate-orm-tenancy-datasource-999-SNAPSHOT-runner-build-output-stats.json (build_info)
========================================================================================================================
Finished generating 'quarkus-integration-test-hibernate-orm-tenancy-datasource-999-SNAPSHOT-runner' in 2m 49s.
```

native integration tests that are knowingly affected by this are:

- `quarkus-integration-test-hibernate-orm-tenancy-datasource`
- `quarkus-integration-test-flyway`
- `quarkus-integration-test-hibernate-orm-tenancy-schema`
- `quarkus-integration-test-hibernate-search-orm-elasticsearch-tenancy`
- `quarkus-integration-test-hibernate-reactive-mysql-agroal-flyway`
- `quarkus-integration-test-quartz`

See for example this CI failure here:
https://github.com/graalvm/mandrel/actions/runs/6476804908/job/17587135032#step:12:2404

**Comment by jerboaa** [comment]
Looks to me that a dependency that provides `org.apache.commons.logging.LogFactory` is missing?

**Comment by jerboaa** [comment]
Adding `-H:AbortOnTypeReachable=org.flywaydb.core.internal.logging.apachecommons.ApacheCommonsLogCreator,org.flywaydb.core.internal.logging.log4j2.Log4j2LogCreator` reveals this trace:

```
Type org.flywaydb.core.internal.logging.apachecommons.ApacheCommonsLogCreator is marked as allocated
    at static method com.oracle.svm.core.code.FactoryMethodHolder.ApacheCommonsLogCreator_constructor_b07955c98bcbaba7c4e5cef63881988dcdf8907b(generated:0), implementation invoked
        str: Factory method, registered in class com.oracle.svm.hosted.reflect.ReflectionFeature
Type org.flywaydb.core.internal.logging.log4j2.Log4j2LogCreator is marked as allocated
    at static method com.oracle.svm.core.code.FactoryMethodHolder.Log4j2LogCreator_constructor_a1ad1013c9167b24cb504224bc92827df259da50(generated:0), implementation invoked
        str: Factory method, registered in class com.oracle.svm.hosted.reflect.ReflectionFeature
```

Which seems strange... Looking some more.

**Comment by jerboaa** [comment]
One GraalVM version which is known to **not** have this problem was `7c17c0c6e8b3fbc43d1a955ab5bf01f4ab71471d` from around September 16, 2023.
https://github.com/graalvm/mandrel/actions/runs/6204421543/job/16846476397#step:2:516

**Comment by zakkak** [comment]
@jerboaa please see https://github.com/oracle/graal/issues/7448

My understanding is that it's a regression on the GraalVM side.

**Comment by jerboaa** [comment]
> @jerboaa please see [oracle/graal#7448](https://github.com/oracle/graal/issues/7448)
> 
> My understanding is that it's a regression on the GraalVM side.

Thanks for the heads-up! Hopefully we can get some traction on that one.

**Comment by jerboaa** [comment]
This is a duplicate of https://github.com/quarkusio/quarkus/issues/35994
