### ISSUE TITLE
oidc-client-graphql tests are failing with NPE

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#36469]
### Describe the bug

https://github.com/quarkusio/quarkus/pull/36375  introduced `oidc-client-grapghql`, some PRs are failing with:

```
2023-10-13T00:41:14.4473397Z Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object, Object)" because "dynamicHeaders" is null
2023-10-13T00:41:14.4475762Z 	at io.quarkus.oidc.client.graphql.runtime.OidcGraphQLClientIntegrationRecorder.lambda$enhanceGraphQLClientConfigurationWithOidc$0(OidcGraphQLClientIntegrationRecorder.java:25)
2023-10-13T00:41:14.4477670Z 	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
2023-10-13T00:41:14.4479641Z 	at io.quarkus.oidc.client.graphql.runtime.OidcGraphQLClientIntegrationRecorder.enhanceGraphQLClientConfigurationWithOidc(OidcGraphQLClientIntegrationRecorder.java:19)
2023-10-13T00:41:14.4482048Z 	at io.quarkus.deployment.steps.OidcGraphQLClientIntegrationProcessor$initialize1724027614.deploy_0(Unknown Source)
2023-10-13T00:41:14.4483872Z 	at io.quarkus.deployment.steps.OidcGraphQLClientIntegrationProcessor$initialize1724027614.deploy(Unknown Source)
```

**Comment by sberyozkin** [comment]
It all passes on my laptop:

```
2023-10-13 13:38:36,484 INFO  [io.qua.oid.dep.dev.OidcDevUIProcessor] (build-36) OIDC Dev Console: discovering the provider metadata at http://localhost:32773/auth/realms/quarkus/.well-known/openid-configuration
2023-10-13 13:38:38,514 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-oidc-client-graphql-deployment 999-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 2.605s. Listening on: http://localhost:8080
2023-10-13 13:38:38,515 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-10-13 13:38:38,515 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, hibernate-validator, oidc, oidc-client, oidc-client-graphql-client-integration, resteasy-reactive, security, smallrye-context-propagation, smallrye-graphql, smallrye-graphql-client, vertx]
2023-10-13 13:38:38,793 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-oidc-client-graphql-deployment stopped in 0.006s
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 35.90 s -- in io.quarkus.oidc.client.graphql.GraphQLClientUsingOidcClientTest

```

**Comment by gsmet** [comment]
As I said in the comment where I pinged @jmartisk , it's probably a race condition (that happens more regularly on CI because it's slow).

**Comment by gsmet** [comment]
A couple of comments here:
- I think `GraphQLClientsConfiguration.clients` should be a CHM, not a HM
- It would be preferable to initialize `GraphQLClientConfiguration` in a fully immutable way (typically with a builder)

**Comment by sberyozkin** [comment]
Looks like some more work is needed at the `smallrye-graphql` level, I've removed the backport label from the PR which introduced the extension, targeting 3.6.0 looks safer at this stage

**Comment by sberyozkin** [comment]
I suppose reverting the PR will hopefully not be necessary, Jan will be back tomorrow, so he'll have enough time to fix it and re-enable to tests to confirm.

**Comment by jmartisk** [comment]
With https://github.com/smallrye/smallrye-graphql/pull/1939 I have run the test 140 times and got zero failures

**Comment by jmartisk** [comment]
Let's keep it open until we upgrade to a fixed smallrye-graphql version
