### ISSUE TITLE
Using RestEasy Reactive Links producing Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is null in GetterAccessorsContainer

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#36463]
### Describe the bug

I'm trying to get a simple ReastEasy Reactive Links example running

While the "all" endpoint works fine, the other one creates a NullPointerException I cannot make sense of.

I'd appreciate any hints on what is wrong here.

### Actual behavior

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is null
	at io.quarkus.resteasy.reactive.links.runtime.GetterAccessorsContainer.get(GetterAccessorsContainer.java:14)
	at io.quarkus.resteasy.reactive.links.runtime.RestLinksProviderImpl.getPathParameterValues(RestLinksProviderImpl.java:65)
	at io.quarkus.resteasy.reactive.links.runtime.RestLinksProviderImpl.getInstanceLinks(RestLinksProviderImpl.java:57)
	at io.quarkus.resteasy.reactive.links.RestLinksProviderProducer_ProducerMethod_restLinksProvider_786cc3ba1428495d7e51b3949de5641383cecdb3_ClientProxy.getInstanceLinks(Unknown Source)
	at io.quarkus.resteasy.reactive.links.RestLinksHandler.getLinks(RestLinksHandler.java:38)
	at io.quarkus.resteasy.reactive.links.RestLinksHandler.handle(RestLinksHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

```
@Path("test")
public class TestResource {

    @Data
    public static class Test {
        private String name;

        public static Test name(String name) {
            var test = new Test();
            test.setName(name);
            return test;
        }
    }

    private static final Map<Integer, Test> db = Map.of(
            1, Test.name("a"),
            2, Test.name("b"),
            3, Test.name("c"),
            4, Test.name("d")
    );

    @GET
    @InjectRestLinks
    @RestLink(rel = "list")
    public Collection<Test> all() {
        return db.values();
    }

    @GET
    @Path("{id}")
    @RestLink(rel = "self")
    @InjectRestLinks(RestLinkType.INSTANCE)
    public Test get(@PathParam("id") int id) {
        return db.get(id);
    }

}
```

### Output of `java -version`

21

### Quarkus version or git rev

3.4.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle

**Comment by geoand** [comment]
Mind attaching a project that has test that reproduces the problem?

Thanks

**Comment by mklueh** [comment]
Hey @geoand 

It seems to happen only, when `@InjectRestLinks` is used with type `RestLinkType.INSTANCE`

https://github.com/mklueh/quarkus-reproducer-resteasy-links-documentation-not-working

**Comment by LeonorLunatech** [comment]
Hi @mklueh, I took the freedom of looking into this issue and after some debugging I figured out what the issue is.
In the endpoint `/with-type-instance/{id}` the instance that is returned (`TestRecord`) needs to have a field called `id` (the same as the parameter in your endpoint).

So with this code:
```
    @Data
    public static class TestRecord {
        private Integer id;
        private String name;

        public static TestRecord name(Integer id, String name) {
            var test = new TestRecord();
            test.setId(id);
            test.setName(name);
            return test;
        }
    }

    private static final Map<Integer, TestRecord> testRecordDb = Map.of(
            1, TestRecord.name(1, "a"),
            2, TestRecord.name(2, "b"),
            3, TestRecord.name(3, "c"),
            4, TestRecord.name(4, "d")
    );

    @GET
    @RestLink(rel = "list")
    @InjectRestLinks(RestLinkType.INSTANCE)
    public List<TestRecord> getAll() {
        return testRecordDb.values().stream().toList();
    }

    @GET
    @Path("/with-type-instance/{id}")
    @InjectRestLinks(RestLinkType.INSTANCE)
    @RestLink(entityType = TestRecord.class)
    public TestRecord injectTypeInstance(@PathParam("id") int id) {
        return testRecordDb.get(id);
    }
```

The output is:
```
 $ curl -i localhost:8080/records/with-type-instance/1
HTTP/1.1 200 OK
content-length: 19
Content-Type: application/json;charset=UTF-8
Link: <http://localhost:8080/records>; rel="list"
Link: <http://localhost:8080/records/with-type-instance/1>; rel="self"
```
 
So maybe in the end this is a documentation issue because in [web links support](https://quarkus.io/guides/resteasy-reactive#web-links-support) this is not explained.

**Comment by mklueh** [comment]
@LeonorLunatech thank you, that makes sense!

I think there should also be a more specific error message. The current one isn't telling at all

**Comment by geoand** [comment]
Nice find!

Would you like to improve the error message?

**Comment by LeonorLunatech** [comment]
I'm currently working on this. Would the error message ` HTTP Request to /records/with-type-instance/1 failed, error id: 255f9d71-294e-40e5-a73e-7786ab8b746a-1: java.lang.IllegalStateException: Cannot generate web links for com.example.RecordsResource$TestRecord because class does not contain an `id` field` make sense?

**Comment by geoand** [comment]
Looks good to me!

**Comment by LeonorLunatech** [comment]
Cool! Lets see if I can do something about the actual documentation
