### ISSUE TITLE
Gradle multimodule cannot find Kotlin classes in dev mode

### ISSUE THREAD

**Issue by dmarmelo** [quarkusio/quarkus#36506]
### Describe the bug

I am trying to build a multimodule gradle project with several quarkus aplications and a shared module to be used by all applications, all using kotlin and gradle kotlin DSL.

The problem is that the quarkus applicatioon cannot find the kotlin classes from the shared module in dev mode, but only in dev mode because it compiles and runs fine not in dev mode.

Launch quarkus in dev mode:
`java.lang.ClassNotFoundException: org.acme.SharedKotlinExample
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
	at org.acme.GreetingResource.hello(GreetingResource.kt:16)
	at org.acme.GreetingResource$quarkusrestinvoker$hello_e747664148511e1e5212d3e0f4b40d45c56ab8a1.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Resulted in: java.lang.NoClassDefFoundError: org/acme/SharedKotlinExample
	... 12 more`

Import the class and trigger a live reload:
`java.lang.RuntimeException: Compilation failed.         val sharedKotlinExample = SharedKotlinExample()
/Users/danielmarmelo/Downloads/quarkus-kotlin-shared-library-bug/quarkus-app/src/main/kotlin/org/acme/GreetingResource.kt:16:35
Reason: Unresolved reference: SharedKotlinExample
	at io.quarkus.kotlin.deployment.KotlinCompilationProvider.compile(KotlinCompilationProvider.java:101)
	at io.quarkus.deployment.dev.QuarkusCompiler.compile(QuarkusCompiler.java:226)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:725)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:461)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:441)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:152)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:139)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)`

This issue only happens with kotlin classes, with java works fine, and checkd the jar the is procuced from the module and both are there, but quarkus in dev mode can only see the java ones.

The previous errors occurr when I include the dependency as a project, like this: `implementation(project(":common"))`
If I include the jar directly it works as expected, even in dev mode, like this: `implementation(files("/Users/danielmarmelo/Downloads/quarkus-kotlin-shared-library-bug/shared/build/libs/common-1.0.0-SNAPSHOT.jar"))`

### Expected behavior

Be able to use all classes from the shared module, kotlin or java.

### Actual behavior

Can only use java classes from the shared module.

### How to Reproduce?

Reproducer: [quarkus-kotlin-shared-library-bug.zip](https://github.com/quarkusio/quarkus/files/12919187/quarkus-kotlin-shared-library-bug.zip)

Steps
- ./gradlew :quarkus-app:quarkusDev
- Invoke the '/hello' endpoint

### Output of `uname -a` or `ver`

Darwin MacBook-Pro-de-Daniel.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

java version "17.0.8" 2023-07-18 LTS Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211) Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.2 ------------------------------------------------------------  Build time:   2023-06-30 18:02:30 UTC Revision:     5f4a070a62a31a17438ac998c2b849f4f6892877  Kotlin:       1.8.20 Groovy:       3.0.17 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          17.0.8 (Oracle Corporation 17.0.8+9-LTS-211) OS:           Mac OS X 14.0 aarch64

### Additional information

It seems like the kotlin classes are not being included in the classpath when in dev mode, because when it compiles out of dev mode it works fine.

**Comment by dmarmelo** [comment]
After some research I think I've found the source of the problem.
For quarkus project the tasks filter functions as expected filtering only the kotlin tasks, but when comes the shared module, even though the tasks exist (I checks with debugger) the `withType(KotlinJvmCompile.class)` doesnt's return any task, leading to the sources paths from kotlin not being saved to be registered in the artifact.
https://github.com/quarkusio/quarkus/blob/adb9cbf7eafb66e10bac4560f8e1b359fbb550c3/devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/GradleApplicationModelBuilder.java#L538

This issue seems to be related: https://github.com/gradle/gradle/issues/19831

**Comment by lschmierer** [comment]
I ran into the same issue. Moving the Kotlin Gradle plugin to the root `build.gradle.kts` fixed it for me.

```
plugins {
    kotlin("jvm") version "1.9.20" apply false
    id("io.quarkus") apply false
}


subprojects {
    apply(plugin="kotlin")

    repositories {
        mavenCentral()
        maven { url = uri("https://repo1.maven.org/maven2/") }
    }
}
```

then in the sub projects just use
```
kotlin("jvm")
```
instead of
```
kotlin("jvm") version "1.9.20" 
```

**Comment by rodcheater** [comment]
I don’t suppose we could hear from the Quarkus team on this one. I tried @lschmierer’s workaround but it didn’t work for me.

@evanchooly @geoand  @glefloch

**Comment by evanchooly** [comment]
Fwiw, I'm no longer on the team and don't have an answer for you.  Sorry.

**Comment by geoand** [comment]
Maybe @aloubyansky has some ideas

**Comment by rodcheater** [comment]
Just to explain why the workaround doesn’t work for me, our setup involves multiple Gradle projects in separate repositories, so we don’t have a shared root Gradle build file to add the Kotlin plugin to. I’ve updated the reproducer to illustrate.

[quarkus-kotlin-shared-library-bug.zip](https://github.com/user-attachments/files/15860650/quarkus-kotlin-shared-library-bug.zip)

Use `cd quarkus-app && ./gradlew quarkusDev --include-build ../shared` to run.

**Comment by Maxi937** [comment]
Still a nasty issue that I have hit today, any update would be appreciated.
