### ISSUE TITLE
Since 3.5.0 AMQ hostname cannot be overriden with environment variable in OpenShift, previously it could be

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#36549]
### Describe the bug

I have following properties in my application.properties

```
amqp-host=fedor-rules
amqp-port=5672
```

and later I override it inside OpenShift pod like this (shortened output of oc describe pod):

```
...
Containers:
  app:
    Container ID:   cri-o://2c353ee043ebefed4451a9d8cb7ad2a24e3f0e93f725f2932a2fbe8c4c4a4dd5
    Image:          image-registry.openshift-image-registry...
    Image ID:       image-registry.openshift-image-registry....
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 18 Oct 2023 12:30:42 +0200
    Ready:          True
    Restart Count:  0
    Environment:
      KUBERNETES_NAMESPACE:        ts-dxadyvktfs (v1:metadata.namespace)
      QUARKUS_HOME:                /home/quarkus/
      QUARKUS_OPTS:                
      JAVA_APP_JAR:                /deployments/quarkus-run.jar
      amqp-port:                   5672
      amqp-host:                   amq-amqp
...
```

previously it was absolutely irrelevant what I set in app properties as long as I set env variable.

I tried to link this change in behavior to netty bump / smallrye reactive messaging bump / kubernetes client bump etc. and failed to find it.

### Expected behavior

Environment variable is source with higher priority to application properties. It worked with 3.4.3.

### Actual behavior

Application fails to start and following exception is being logged repeatedly:

```
12:31:30,321 INFO  [app] 10:31:29,252 SRMSG16212: Establishing connection with AMQP broker
12:31:30,321 INFO  [app] 10:31:29,254 SRMSG16215: Unable to connect to the broker, retry will be attempted: java.net.UnknownHostException: fedor-rules: Name or service not known
12:31:30,321 INFO  [app] 	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
12:31:30,321 INFO  [app] 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
12:31:30,321 INFO  [app] 	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
12:31:30,321 INFO  [app] 	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
12:31:30,321 INFO  [app] 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
12:31:30,322 INFO  [app] 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
12:31:30,322 INFO  [app] 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
12:31:30,322 INFO  [app] 	at java.base/java.net.InetAddress.getByName(InetAddress.java:1256)
12:31:30,322 INFO  [app] 	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
12:31:30,322 INFO  [app] 	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
12:31:30,322 INFO  [app] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
12:31:30,322 INFO  [app] 	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
12:31:30,322 INFO  [app] 	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
12:31:30,322 INFO  [app] 	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
12:31:30,323 INFO  [app] 	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
12:31:30,323 INFO  [app] 	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
12:31:30,323 INFO  [app] 	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
12:31:30,323 INFO  [app] 	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
12:31:30,323 INFO  [app] 	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220)
12:31:30,323 INFO  [app] 	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:171)
12:31:30,323 INFO  [app] 	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:148)
12:31:30,323 INFO  [app] 	at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:152)
12:31:30,323 INFO  [app] 	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:103)
12:31:30,324 INFO  [app] 	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:89)
12:31:30,324 INFO  [app] 	at io.vertx.core.net.impl.NetClientImpl.connectInternal2(NetClientImpl.java:304)
12:31:30,324 INFO  [app] 	at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$2(NetClientImpl.java:270)
12:31:30,324 INFO  [app] 	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
12:31:30,324 INFO  [app] 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
12:31:30,324 INFO  [app] 	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
12:31:30,324 INFO  [app] 	at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:164)
12:31:30,324 INFO  [app] 	at io.vertx.core.net.impl.NetClientImpl.connectInternal(NetClientImpl.java:268)
12:31:30,325 INFO  [app] 	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:230)
12:31:30,325 INFO  [app] 	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:206)
12:31:30,325 INFO  [app] 	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:139)
12:31:30,325 INFO  [app] 	at io.vertx.proton.impl.ProtonClientImpl.connectNetClient(ProtonClientImpl.java:74)
12:31:30,325 INFO  [app] 	at io.vertx.proton.impl.ProtonClientImpl.connect(ProtonClientImpl.java:65)
12:31:30,325 INFO  [app] 	at io.vertx.amqp.impl.AmqpConnectionImpl.connect(AmqpConnectionImpl.java:79)
12:31:30,325 INFO  [app] 	at io.vertx.amqp.impl.AmqpConnectionImpl.lambda$new$0(AmqpConnectionImpl.java:70)
12:31:30,325 INFO  [app] 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
12:31:30,325 INFO  [app] 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:259)
12:31:30,325 INFO  [app] 	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
12:31:30,326 INFO  [app] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
12:31:30,326 INFO  [app] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
12:31:30,326 INFO  [app] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
12:31:30,326 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
12:31:30,326 INFO  [app] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
12:31:30,326 INFO  [app] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
12:31:30,326 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
12:31:30,326 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

1. `oc login ...`
2. `git clone git@github.com:michalvavrik/quarkus-test-framework.git`
3. `cd quarkus-test-framework`
4. `git checkout reproduce/amq-ocp`
5. `mvn clean verify -Dopenshift -f examples/amq-amqp`

### Output of `uname -a` or `ver`

Fedora 38

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.7+7

### Quarkus version or git rev

3.5.0.CR1 and 999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

### Additional information

Using OpenShift 4.13.

**Comment by michalvavrik** [comment]
@ozangunalp @cescoffier @radcortez @iocanel any ideas?

**Comment by cescoffier** [comment]
My guess is a change in SR Config. It needs to be investigated, as unlike Kafka, it’s a much simpler lookup.

**Comment by fedinskiy** [comment]
@michalvavrik it looks like https://github.com/quarkusio/quarkus/issues/36359.
Basically, these properties should become something like AMQP_PORT, when they are in the "Environment" segment of Kubernetes/Openshift manifests

**Comment by michalvavrik** [comment]
Oki, I'll close it. Thanks.
