### ISSUE TITLE
3.0 - BuildException when using jakarta.ws.rs.client.ClientBuilder

### ISSUE THREAD

**Issue by mikethecalamity** [quarkusio/quarkus#36614]
### Describe the bug

I'm trying to upgrade our system from Quarkus 2 to 3. We are slowly working to migrate to the Rest Client interfaces that Quarkus recommends, but as of now we have too many to do right away, so as of now we inject `jakarta.ws.rs.client.Client` which is generated by the producer below. But there is a `BuildException`  when I `quarkusBuild` in Quarkus 3.

### Expected behavior

```
Failed to index org.jboss.resteasy.plugins.providers.AbstractPatchMethodFilter: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD@77a8b83f
> Task :my-project:quarkusAppPartsBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':my-project:quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.ClassInfo.name()" because "currentClazz" is null
                at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.createTypedAnnotationInstance(ResteasyReactiveProcessor.java:872)
                at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor$6.transform(ResteasyReactiveProcessor.java:854)
                at io.quarkus.arc.processor.AnnotationStore.transform(AnnotationStore.java:108)
                at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
                at io.quarkus.arc.processor.AnnotationStore.getAnnotations(AnnotationStore.java:61)
                at io.quarkus.arc.processor.AnnotationStore.hasAnnotation(AnnotationStore.java:85)
                at io.quarkus.arc.processor.BeanDeployment.isVetoed(BeanDeployment.java:1278)
                at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1001)
                at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:272)
                at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:144)
                at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:419)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
                at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
                at java.base/java.lang.Thread.run(Thread.java:833)
                at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

### Actual behavior

Successful build

### How to Reproduce?

```sh
gradlew my-project:quarkusBuild
```

Class using client
```java
@Inject
Client client;

public void doSoemthing(String url, long param) {
    final Response r = client.target(url).queryParam("my-param", param)
            .request(MediaType.APPLICATION_JSON).get();
    // use response
}
```

Client producer
```java
public class RestClientProducer {

    @Produces
    @ApplicationScoped
    public Client produceClient(
            @ConfigProperty(name = "quarkus.rest-client.connect-timeout", defaultValue = "30000") final int connectTimeout,
            @ConfigProperty(name = "quarkus.rest-client.read-timeout", defaultValue = "30000") final int readTimeout) {
        try {
            TrustManager[] trustManagers = { new NullX509TrustManager() };
            SSLContext context = SSLContext.getInstance("TLSv1");
            context.init(null, trustManagers, null);
            ClientBuilder clientBuilder = ClientBuilder.newBuilder();
            return clientBuilder
                    .sslContext(context) //
                    .connectTimeout(connectTimeout, TimeUnit.MILLISECONDS) //
                    .readTimeout(readTimeout, TimeUnit.MILLISECONDS) //
                    .register(JwtClientFilter.class) //
                    .register(MyCustomObjectMapperContextResolver.class).build();
        }
        catch (KeyManagementException | NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
}
```

### Output of `java -version`

Temurin JDK 17

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.3

**Comment by mikethecalamity** [comment]
I think its actually an issue with a `javax.ws.rs.ext.Provider`, going to attempt to make a reproducer and post a new issue.
