### ISSUE TITLE
@Source method parameter in GraphQLApi class + Java Bean Validation input

### ISSUE THREAD

**Issue by dpolysiou** [quarkusio/quarkus#36658]
### Describe the bug

Given a method in a `GraphQLApi` class that takes two parameters, the first annotated with `@Source` and the second annotated with `@Valid`, eg:

```
public List<Foo> page(@Source Foo foo, @Valid Pagination pagination) {
  ...
}
```
any validation errors on the input will lead to a system error:

```
ERROR [io.sma.graphql] (vert.x-eventloop-thread-0) SRGQL012000: Data Fetching Error: java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
```
The problem seems to be in the computation of the parameter index, due to the `@Source` parameter not being included in the GraphQL `FieldDefinition`. A similar problem, concerning `Context` parameters, was reported in quarkusio/quarkus/issues/24183 and has already been resolved by smallrye/smallrye-graphql#1314 .

### Expected behavior

The API response should include the relevant validation errors.

### Actual behavior

```
ERROR [io.sma.graphql] (vert.x-eventloop-thread-0) SRGQL012000: Data Fetching Error: java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
        at graphql.com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1355)
        at graphql.com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1337)
        at graphql.com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:44)
        at io.smallrye.graphql.validation.BeanValidationUtil$RequestNodeBuilder.requestedArgument(BeanValidationUtil.java:61)
        at io.smallrye.graphql.validation.BeanValidationUtil$RequestNodeBuilder.build(BeanValidationUtil.java:49)
        at io.smallrye.graphql.validation.BeanValidationUtil.lambda$addConstraintViolationsToDataFetcherResult$0(BeanValidationUtil.java:30)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at io.smallrye.graphql.validation.BeanValidationUtil.addConstraintViolationsToDataFetcherResult(BeanValidationUtil.java:31)
        at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusDefaultDataFetcher.lambda$invokeAndTransformBlocking$0(QuarkusDefaultDataFetcher.java:98)
        at io.smallrye.context.impl.wrappers.SlowContextualCallable.call(SlowContextualCallable.java:21)
        at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.BlockingHelper.lambda$runBlocking$0(BlockingHelper.java:30)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
        at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

### How to Reproduce?

A small reproducer can be found at [dpolysiou/smallrye-graphql-reproducer](https://github.com/dpolysiou/smallrye-graphql-reproducer)
The following query will result in a system error:
```
query {
  foo {
    page(pagination: {limit: 0, start: -1}) {
      name
    }
  }
}
```

### Output of `java -version`

openjdk version "17.0.8" 2023-07-18

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.1

**Comment by jmartisk** [comment]
Hi, thanks for reporting this. It should be relatively easy to fix, you just skip the increment just like in https://github.com/smallrye/smallrye-graphql/pull/1314/files#diff-aaed41990fe1560f69b1c31cb1ac6bc5b1fa3bd0b15db043c127a19f817a835eR87 when the parameter has a `@Source` annotation. If you're up for it, we welcome pull requests, otherwise, we'll look into it.
