### ISSUE TITLE
integration-tests/kafka-oauth-keycloak failing in native

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#36653]
I saw it failing in several builds with the following error:

```
Error: Unsupported features in 2 methods
Detailed message:
Error: Discovered unresolved method during parsing: io.strimzi.kafka.oauth.jsonpath.JsonPathQuery.apply(com.fasterxml.jackson.databind.JsonNode). This error is reported at image build time because class io.strimzi.kafka.oauth.common.PrincipalExtractor is registered for linking at image build time by command line and command line.
Error encountered while parsing io.strimzi.kafka.oauth.common.PrincipalExtractor.getPrincipal(PrincipalExtractor.java:81) 
Parsing context:
   at io.strimzi.kafka.oauth.common.TokenIntrospection.introspectAccessToken(TokenIntrospection.java:48)
   at io.strimzi.kafka.oauth.common.OAuthAuthenticator.post(OAuthAuthenticator.java:483)
   at io.strimzi.kafka.oauth.common.OAuthAuthenticator.loginWithClientSecret(OAuthAuthenticator.java:167)
   at io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler.handleCallback(JaasClientOauthLoginCallbackHandler.java:284)
   at root method.(Unknown Source)

Error: Discovered unresolved method during parsing: io.strimzi.kafka.oauth.jsonpath.JsonPathQuery.parse(java.lang.String). This error is reported at image build time because class io.strimzi.kafka.oauth.common.PrincipalExtractor is registered for linking at image build time by command line and command line.
Error encountered while parsing io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler.configure(JaasClientOauthLoginCallbackHandler.java:89) 
```

**Comment by ozangunalp** [comment]
I'll probably have to rewrite this IT in order to fix this. Will look at it today or tomorrow

**Comment by zakkak** [comment]
FTR the failures started after merging https://github.com/quarkusio/quarkus/pull/36462

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/36657 to revert the change.

**Comment by ozangunalp** [comment]
`kafka-oauth-common` pulls the jayway json-path but `kafka-oauth-client` excludes it. 
I think with the version 0.14.0 the usage of json-path is in the nominal path.

I agree that we need to revert this.

**Comment by ozangunalp** [comment]
Created an issue in upstream `kafka-oauth-client`. But I still need to rewrite this IT.
