### ISSUE TITLE
Quarkus native tests fail with latest GraalVM CE for JDK 22, 24.0.0-dev builds due to wildfly substitution

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#36686]
### Describe the bug

Quarkus native tests fail with latest GraalVM CE for JDK 22, 24.0.0-dev builds due to wildfly substitution.

The error is:

```
Error: Substitution target for org.wildfly.common.Substitutions$Target_GraalDirectives is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: Substitution target for org.wildfly.common.Substitutions$Target_GraalDirectives is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1098)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1047)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1043)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:375)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:353)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:1058)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:924)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:595)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:555)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:540)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:722)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
```

### Expected behavior

Tests should build and pass.

### Actual behavior

Tests fail to build.

### How to Reproduce?

1. Grab a dev build of GraalVM CE with https://github.com/oracle/graal/pull/7650 and https://github.com/oracle/graal/pull/7621 (none available yet) or build it from source:
  ```
git clone https://github.com/graalvm/mx
git clone https://github.com/oracle/graal
cd graal
../mx/mx fetch-jdk --java-distribution labsjdk-ce-latest
export JAVA_HOME=/path/to/downloaded/labsjdk
../mx/mx --primary-suite-path substratevm --components="Native Image,LibGraal,Truffle SVM Macro" --native-images=native-image,lib:jvmcicompiler build
export GRAALVM_HOME=$(pwd)/sdk/latest_graalvm_home
```

2. `export GRAALVM_HOME=/path/to/the/deb-build`
3. `./mvnw -Dnative -pl integration-tests/jpa -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean package -Dquarkus.native.container-build=false`

### Mandrel or GraalVM version (if different from Java)

24.0.0-dev

### Quarkus version or git rev

main

### Additional information

The issue is caused because wildfly tries to [substitute a GraalVM internal class](https://github.com/wildfly/wildfly-common/blob/44dc271fa0893788f51842a8b34313e1cb6c1519/src/main/java/org/wildfly/common/Substitutions.java#L62) that is no longer available due to the package renaming in https://github.com/oracle/graal/pull/7650 and https://github.com/oracle/graal/pull/7621

**Comment by zakkak** [comment]
Upstream wildfly issue https://github.com/wildfly/wildfly-common/issues/74

**Comment by zakkak** [comment]
The issue has been fixed upstream and should be part of the next release (1.6.1?)
