### ISSUE TITLE
BlockingNotAllowedException with quarkus-rest-client-reactive when using gzip compression

### ISSUE THREAD

**Issue by kekbur** [quarkusio/quarkus#36761]
### Describe the bug

RESTEasy reactive client throws `BlockingNotAllowedException` when reading a GZIP compressed response. Whether the bug is triggered seems to depend on the operating system and the length of the response. The bug seems to appear only when the REST client's return type is `InputStream`.

```
quarkus.http.enable-compression=true
```
```java
@GET
@Path("/books")
@ClientHeaderParam(name = "Accept-Encoding", value = "gzip")
public InputStream getBooksStream(@QueryParam("input") String input);
```

### Expected behavior

No BlockingNotAllowedException is thrown.

### Actual behavior

The following exception is thrown:

```
org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException: Attempting a blocking read on io thread
        at org.jboss.resteasy.reactive.client.handlers.VertxClientInputStream$VertxBlockingInput.readBlocking(VertxClientInputStream.java:199)
        at org.jboss.resteasy.reactive.client.handlers.VertxClientInputStream.readIntoBuffer(VertxClientInputStream.java:81)
        at org.jboss.resteasy.reactive.client.handlers.VertxClientInputStream.read(VertxClientInputStream.java:62)
        at org.jboss.resteasy.reactive.client.handlers.VertxClientInputStream.read(VertxClientInputStream.java:54)
        at org.jboss.resteasy.reactive.client.handlers.VertxClientInputStream.read(VertxClientInputStream.java:45)
        at java.base/java.util.zip.CheckedInputStream.read(CheckedInputStream.java:59)
        at java.base/java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:277)
        at java.base/java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:269)
        at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:175)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at org.jboss.resteasy.reactive.client.interceptors.ClientGZIPDecodingInterceptor.aroundReadFrom(ClientGZIPDecodingInterceptor.java:26)
        at org.jboss.resteasy.reactive.client.impl.ClientReaderInterceptorContextImpl.proceed(ClientReaderInterceptorContextImpl.java:133)
        at org.jboss.resteasy.reactive.client.impl.ClientSerialisers.invokeClientReader(ClientSerialisers.java:160)
        at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.readEntity(RestClientRequestContext.java:198)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.mapToResponse(ClientResponseCompleteRestHandler.java:104)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:35)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:31)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:231)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
        at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:38)
        at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:35)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:259)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

Reproducer: [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/13196747/code-with-quarkus.zip)

1. Run `mvn -Dtest="org.acme.BookApiTest#testGetBooksStream" test` to induce the error.

### Output of `uname -a` or `ver`

CYGWIN_NT-10.0-22000 DESKTOP 3.4.9-1.x86_64 2023-09-06 11:19 UTC x86_64 Cygwin

### Output of `java -version`

openjdk version "21" 2023-09-19

### Quarkus version or git rev

3.5.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4

### Additional information

Also reproducible with Java 17.0.8 on Linux and Windows.

The problem proved somewhat tricky to reproduce on Windows where the test code needs to send multiple requests with different response lengths to find one that triggers the bug. On Linux (Debian 4.19.289-2) any response length seems to trigger it.

**Comment by rysurd** [comment]
Hello ! I'll have a look.

**Comment by rysurd** [comment]
@kekbur Are you sure this is a bug and not an expected behavior? Looking at the code where the error is thrown :
```
while (input1 == null && !eof && readException == null) {
    long rem = expire - System.currentTimeMillis();
    if (rem <= 0) {
        //everything is broken, if read has timed out we can assume that the underling connection
        //is wrecked, so just close it
        request.netSocket().close();
        IOException throwable = new IOException("Read timed out");
        readException = throwable;
        throw throwable;
    }

    try {
        if (Context.isOnEventLoopThread()) {
            throw new BlockingNotAllowedException("Attempting a blocking read on io thread");
        }
        waiting = true;
        VertxClientInputStream.VertxBlockingInput.this.wait(rem);
    } catch (InterruptedException e) {
        throw new InterruptedIOException(e.getMessage());
    } finally {
        waiting = false;
    }
}
```
It looks like we are expecting such this error to be thrown on a specific case. I'm not expert on this class but I suppose the error is thrown in case we are attempting to do a blocking operation (read) on an event thread (io). Can someone with more knowledge on this confirm or infim ? @geoand or @cescoffier ?

**Comment by cescoffier** [comment]
When using input stream you must be sure the caller is using a worker thread. I didn't check the reproducer, but make sure the caller is on a worker thread.

**Comment by kekbur** [comment]
> @kekbur Are you sure this is a bug and not an expected behavior?

Thank you for investigating this. I'm leaning towards it being a bug, because the only things I'm doing is:

1. Configuring `quarkus.http.enable-compression=true`
2. Sending `Accept-Encoding: gzip`
3. Receiving `Content-Encoding: gzip` and gzipped body.

It's at least unintuitive if that's not supported when the client method's return type is `InputStream`.

> When using input stream you must be sure the caller is using a worker thread. I didn't check the reproducer, but make sure the caller is on a worker thread.

The calling thread in the reproducer is JUnit's main thread. In other words, I'm not calling the API client from a request context where the worker / IO thread distinction would come into play.

Now I tried calling the API client from a request context with a `@Blocking` annotation and without, but the result is the same: BlockingNotAllowedException is thrown. Here is a reproducer with additional test cases: [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/13199024/code-with-quarkus.zip). Run with `mvn -Dtest="org.acme.BookApiTest#testGetBooksRequestContextBlocking" test`.

**Comment by cescoffier** [comment]
Ok, so it's a bug. I suspect the compression feature to switch back to the event loop.

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
> cc @mkouba

Hm, I have no idea how does the compression work in `quarkus-rest-client-reactive`  and whas exactly is the `org.jboss.resteasy.reactive.client.interceptors.ClientGZIPDecodingInterceptor` doing...

**Comment by cescoffier** [comment]
I was unable to reproduce it with the reproducer. Do I miss something? Should I see an exception or something?

**Comment by cescoffier** [comment]
ah, it does not happen every time.

**Comment by kekbur** [comment]
> ah, it does not happen every time.

I've found that the length of the response and the operating system the code is running on affects whether the bug is hit. Maybe it has something to do with varying buffer sizes or network configuration.

**Comment by cescoffier** [comment]
(I'm pretty sure I sent that comment already.)

So, the issue is that sometimes the buffer from the network is not complete, and thus, we block the data. However, we block in that case, and this is not allowed.

We need to switch to a worker thread in that case. I’m not sure where the switch needs to happen.

**Comment by geoand** [comment]
I can take a look, but probably not this week

**Comment by cescoffier** [comment]
It looks like the interceptor cannot return a Uni. We will have to dig a bit more.

**Comment by rysurd** [comment]
@geoand you take care of this issue? Just to know if I have to check for the worker thread too or if I should move to another issue :)

**Comment by geoand** [comment]
If you have ideas on how to fix it, then go ahead. I won't be able to have a look until next week

**Comment by rysurd** [comment]
I have no idea currently but I'll give it a shot for sure

**Comment by geoand** [comment]
This is one requires a lot of surgery unfortunately...
