### ISSUE TITLE
TransactionScoped beans are destroyed after the JTA transaction is commited/rolled back

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#36880]
### Describe the bug

This functionality was added in https://github.com/quarkusio/quarkus/pull/14053. A JTA `Synchronization` is registered and the CDI context is destroyed during the `afterCompletion()` callback.

However, our docs say the opposite: https://quarkus.io/guides/transaction#transaction-scope

The JTA spec states that *"Any Synchronization.afterCompletion methods will be invoked in an undefined context."*. But it does not explicitly define when exactly `@TransactionScoped` beans are destroyed.

We should either update the docs or change the implementation.

**Comment by mkouba** [comment]
CC @yrodiere beacause of https://github.com/quarkusio/quarkus/pull/28870 ;-)

**Comment by yrodiere** [comment]
Do I understand correctly that your problem is with `@PreDestroy` being called *after* commit/rollback?

This does sound counter-intuitive... But I guess it makes sense from CDI's point of view.

It would seem that I got confused by this test:

https://github.com/quarkusio/quarkus/blob/eed0241eaf6dfdd1f148e14dd153edf7404ac2d1/integration-tests/narayana-jta/src/main/java/io/quarkus/narayana/jta/TransactionBeanWithEvents.java#L138-L144

It says we expect an "active" transaction, but doesn't check that the status of the transaction is active... and I guess it's `COMMITTED`/`ROLLEDBACK` instead :/

**Comment by Ladicek** [comment]
The only way how `@PreDestroy` callbacks could be called _before_ commit/rollback is to destroy the transaction CDI context as the first thing of the commit/rollback process, before we actually start committing or rolling back anything. However, the JTA specification [says](https://jakarta.ee/specifications/transactions/2.0/jakarta-transactions-spec-2.0#transactionscoped-annotation) that the transaction CDI context is active even when the transaction status is committing and rolling back, so my opinion is that our documentation is just incorrect.

**Comment by mkouba** [comment]
> It says we expect an "active" transaction, but doesn't check that the status of the transaction is active... and I guess it's `COMMITTED`/`ROLLEDBACK` instead :/

Also this tests context lifecycle events which is a bit different.

**Comment by yrodiere** [comment]
> > The only way how `@PreDestroy` callbacks could be called _before_ commit/rollback is to destroy the transaction CDI context as the first thing of the commit/rollback process, before we actually start committing or rolling back anything. However, the JTA specification [says](https://jakarta.ee/specifications/transactions/2.0/jakarta-transactions-spec-2.0#transactionscoped-annotation) that the transaction CDI context is active even when the transaction status is committing and rolling back, so my opinion is that our documentation is just incorrect.
> 
> And it seems that Naryana JTA does the same in a CDI Full environment: https://github.com/jbosstm/narayana/blob/main/ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionScopeCleanup.java#L45-L51

I'm afraid this makes the `@PreDestroy` callback pretty much useless for many use cases... and also pretty confusing IMO: "you can execute code **after** the transaction gets committed by annotating the transaction-scoped bean with `@**Pre**Destroy`...

Anyway, not the first time I disagree with the Transactions spec (who thought it was a good idea to have checked exceptions not cause a rollback in the interceptor by default? :x ), and I agree my opinion doesn't matter much in this case.

+1 to update the documentation to reflect what's standard and implemented, whatever that is.

**Comment by mkouba** [comment]
Well, a `@PreDestroy` should be used to clean up some "local" resources; "local" in the terms of bean internals. In general, it's not recommended to work with injected beans inside  a `@PreDestroy` callback unless they live in a wider scope (e.g. `@ApplicationScoped` in this particular case).

But I agree that it's a bit confusing.

**Comment by Ladicek** [comment]
> I'm afraid this makes the `@PreDestroy` callback pretty much useless for many use cases... and also pretty confusing IMO: "you can execute code **after** the transaction gets committed by annotating the transaction-scoped bean with `@**Pre**Destroy`"...

I'm no JTA expert, but I don't intuitively see why `@TransactionScoped` beans should be destroyed while the transaction still exists? Destroying the context after the transaction completes seems like a sensible choice to me.

It is also perfectly sensible to be able to get notified when a transaction is about to complete... which is possible using transactional observer methods: https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#transactional_observer_methods In general, I would recommend using those over lifecycle callbacks.

**Comment by yrodiere** [comment]
> > I'm afraid this makes the `@PreDestroy` callback pretty much useless for many use cases... and also pretty confusing IMO: "you can execute code **after** the transaction gets committed by annotating the transaction-scoped bean with `@**Pre**Destroy`"...
> 
> I'm no JTA expert, but I don't intuitively see why `@TransactionScoped` beans should be destroyed while the transaction still exists? Destroying the context after the transaction completes seems like a sensible choice to me.
> 
> It is also perfectly sensible to be able to get notified when a transaction is about to complete... which is possible using transactional observer methods: https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#transactional_observer_methods I would recommend using those over lifecycle callbacks, if you're interested in observing the state of the transaction (as opposed to observing the state of the bean).

Fair enough. We do need an event to be fired in order to use `@Observes(during = Transaction.BEFORE_COMPLETION)` though... If I just want to run something before every transaction gets committed, is there an event type I can use?

**Comment by mkouba** [comment]
> > > I'm afraid this makes the `@PreDestroy` callback pretty much useless for many use cases... and also pretty confusing IMO: "you can execute code **after** the transaction gets committed by annotating the transaction-scoped bean with `@**Pre**Destroy`"...
> > 
> > 
> > I'm no JTA expert, but I don't intuitively see why `@TransactionScoped` beans should be destroyed while the transaction still exists? Destroying the context after the transaction completes seems like a sensible choice to me.
> > It is also perfectly sensible to be able to get notified when a transaction is about to complete... which is possible using transactional observer methods: https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#transactional_observer_methods I would recommend using those over lifecycle callbacks, if you're interested in observing the state of the transaction (as opposed to observing the state of the bean).
> 
> Fair enough. We do need an event to be fired in order to use `@Observes(during = Transaction.BEFORE_COMPLETION)` though... If I just want to run something before every transaction gets committed, is there an event type I can use?

You can use the context lifecycle events, like in the test you mentioned above: `void beforeDestroyed(@Observes @BeforeDestroyed(TransactionScoped.class) Object event)`.

**Comment by yrodiere** [comment]
Alright, thank you. Then that's probably what I should have included in the documentation instead of the incorrect garbage I wrote :)

**Comment by yrodiere** [comment]
Uh, wait. The transaction scope is only destroyed after the transaction is committed.

So something like this just wouldn't work, would it?

```
void beforeDestroyed(@Observes(during = Transaction.BEFORE_COMPLETION) @BeforeDestroyed(TransactionScoped.class) Object event)
```

**Comment by Ladicek** [comment]
The funny thing is that in Quarkus, the lifecycle events of the transaction CDI context do not actually follow the lifecycle super-precisely :-)

If you look at the subclasses of `TransactionScopedNotifier`, we actually fire `@BeforeDestroyed(TransactionScoped.class)` _before_ we start commit/rollback, even though the context will still be active for the duration of commit/rollback, and we fire `@Destroyed(TransactionScoped.class)` _after_ commit/rollback finishes.

The transaction CDI context is destroyed in a `Synchronization.afterCompletion()`, which I guess happens as part of the commit/rollback process.

I guess it would be valid to fire the `@BeforeDestroyed(TransactionScoped.class)` and `@Destroyed(TransactionScoped.class)` events also in `Synchronization.afterCompletion()`, just before/after we destroy the context, but the existing implementation should be good too. In fact, this behavior is probably intentional (catering to the same use cases this issue is about), but I'm not the authority on that.

**Comment by mmusgrov** [comment]
Looking at the ugly stacktrace for the reproducer, the issue is that the TransactionScoped object is being [enlisted/registered when the transaction is not active](https://github.com/quarkusio/quarkus/blob/3.21/extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/context/TransactionContext.java#L207) but the JTA spec does not allow this. If the bean observes the @Initialised event then the enlist/registration will be fine since it would be done when the transaction is active. How about "fixing" it by just logging a warning, instead of a stacktrace, if the transaction is not active before trying to enlist the context:

```
if (transaction.getStatus() == Status.STATUS_ACTIVE) {
    transaction.registerSynchronization(this);
} else {
    log.warn("Cannot register synchronization with transaction because it is not active")
}
```

and updating the docs to say that the user cannot observe the destroy event for the TransactionScoped bean unless it also observes the corresponding initialise event. I think most others on this thread have also suggested we just update the documentation. Other fixes would be too invasive and would incur a performance penalty.

**Comment by mmusgrov** [comment]
Remark: the narayana-jta extension calls the [beforeDestroyed](https://github.com/quarkusio/quarkus/blob/3.21/extensions/narayana-jta/runtime/src/main/java/io/quarkus/narayana/jta/runtime/NotifyingTransactionManager.java#L89) event immediately before calling commit/rollback on the next line (line 70 or line 94), ie it sends out the events at the latest possible time - to "fix" the issue we would need to be sure to intialise the bean immediately before calling beforeDestroyed which would be a rather odd thing to do.

**Comment by yrodiere** [comment]
> How about "fixing" it by just logging a warning, instead of a stacktrace, if the transaction is not active before trying to enlist the context:
> 
> ```
> if (transaction.getStatus() == Status.STATUS_ACTIVE) {
>     transaction.registerSynchronization(this);
> } else {
>     log.warn("Cannot register synchronization with transaction because it is not active")
> }
> ```
>
> and updating the docs to say that the user cannot observe the destroy event for the TransactionScoped bean unless it also observes the corresponding initialise event

This sounds acceptable as a last resort, but I'm interested in this:

> to "fix" the issue we would need to be sure to intialise the bean immediately before calling beforeDestroyed which would be a rather odd thing to do.

I'm not sure I understand this... which bean are we talking about? If it's a `@TransactionScoped` one, why isn't it initialized after the transaction becomes active, considering the javadoc of `@TransactionScoped` says it's about "bean instances whose lifecycle is scoped to the currently active Jakarta Transactions transaction"? Isn't _that_ the problem we should be trying to solve?

**Comment by mmusgrov** [comment]
> 
> This sounds acceptable as a last resort, but I'm interested in this:
> 
> > to "fix" the issue we would need to be sure to intialise the bean immediately before calling beforeDestroyed which would be a rather odd thing to do.
> 
> I'm not sure I understand this... which bean are we talking about? If it's a `@TransactionScoped` one, why isn't it initialized after the transaction becomes active, considering the javadoc of `@TransactionScoped` says it's about "bean instances whose lifecycle is scoped to the currently active Jakarta Transactions transaction"? Isn't _that_ the problem we should be trying to solve?

I was referring to the related issue #40882 (the bean is TxEndObserver). I didn't study how/when ArC creates the beans but when debugging it I noticed that the bean is not initialised just before we rollback. I'm not familiar with how ArC creates the beans bu I can take another look to see if I can provide you with more context. The stack trace for the reproducer is:

```
2025-04-07 10:23:55,356 INFO  [org.acm.GreetingResource$TxEndObserver] (executor-thread-1) Transaction is ending
2025-04-07 10:23:55,392 ERROR [io.qua.nar.jta.run.NotifyingTransactionManager] (executor-thread-1) Failed to fire @BeforeDestroyed(TransactionScoped.class): java.lang.RuntimeException: Cannot register synchronization
	at io.quarkus.narayana.jta.runtime.context.TransactionContext$TransactionContextState.<init>(TransactionContext.java:209)
	at io.quarkus.narayana.jta.runtime.context.TransactionContext.get(TransactionContext.java:125)
	at io.quarkus.narayana.jta.runtime.context.TransactionContext.get(TransactionContext.java:160)
	at org.acme.GreetingResource_TxEndObserver_Observer_onBeforeEndTransaction_-qkHMozTFpNQ78h2RU2G2LHEEgk.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:329)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
	at io.quarkus.narayana.jta.runtime.TransactionScopedNotifier.beforeDestroyed(TransactionScopedNotifier.java:35)
	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.rollback(NotifyingTransactionManager.java:89)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:404)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at org.acme.GreetingResource_Subclass.failure(Unknown Source)
	at org.acme.GreetingResource_ClientProxy.failure(Unknown Source)
	at org.acme.GreetingResource$quarkusrestinvoker$failure_96554a4e8df099fb4eb8581c89f3f9663b0027d8.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
```
