### ISSUE TITLE
Mongodb Panache unable to connect MongoDB Atlas instance in AWS

### ISSUE THREAD

**Issue by anamak9** [quarkusio/quarkus#36932]
### Describe the bug

Deployed AWS lambda unable to connect to MongoDB Atlas instance.

**Dependencies used:**
<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-mongodb-panache</artifactId>
            <version> 3.5.0 </version>
        </dependency>
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver-sync</artifactId>
            <version>4.11.0</version>
        </dependency>
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver-reactivestreams</artifactId>
            <version>4.11.0</version>

### Expected behavior

It should successfully connect to Atlas instance and fetch data.

### Actual behavior

Received the following error when trying to test an AWS deployed lambda API, 

<html>
<body>

2023-11-07 22:01:14,502 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /api/v1/products failed, error id: ca36ca7b-04b2-4b21-8979-7dhfc0edb557-1: java.lang.NoClassDefFoundError: com/mongodb/internal/connection/StreamFactoryHelper
--
at com.mongodb.client.internal.MongoClientImpl.getStreamFactory(MongoClientImpl.java:235)
at com.mongodb.client.internal.MongoClientImpl.createCluster(MongoClientImpl.java:227)
at com.mongodb.client.internal.MongoClientImpl.<init>(MongoClientImpl.java:73)
at com.mongodb.client.MongoClients.create(MongoClients.java:108)
at com.mongodb.client.MongoClients.create(MongoClients.java:50)
at io.quarkus.mongodb.runtime.MongoClients.createMongoClient(MongoClients.java:123)
at io.quarkus.mongodb.runtime.MongoClientRecorder.lambda$mongoClientSupplier$0(MongoClientRecorder.java:66)
at io.quarkus.mongodb.runtime.MongoClientRecorder$MongoClientSupplier.get(MongoClientRecorder.java:60)
at io.quarkus.arc.runtime.ArcRecorder$4.apply(ArcRecorder.java:129)
at io.quarkus.arc.runtime.ArcRecorder$4.apply(ArcRecorder.java:126)
at com.mongodb.client.MongoClient_875fc6d3e776003a77cb64e6876f962a3525aded_Synthetic_Bean.createSynthetic(Unknown Source)
at com.mongodb.client.MongoClient_875fc6d3e776003a77cb64e6876f962a3525aded_Synthetic_Bean.doCreate(Unknown Source)
at com.mongodb.client.MongoClient_875fc6d3e776003a77cb64e6876f962a3525aded_Synthetic_Bean.create(Unknown Source)
at com.mongodb.client.MongoClient_875fc6d3e776003a77cb64e6876f962a3525aded_Synthetic_Bean.create(Unknown Source)
at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
at com.mongodb.client.MongoClient_875fc6d3e776003a77cb64e6876f962a3525aded_Synthetic_ClientProxy.arc$delegate(Unknown Source)
at com.mongodb.client.MongoClient_875fc6d3e776003a77cb64e6876f962a3525aded_Synthetic_ClientProxy.getDatabase(Unknown Source)
at io.quarkus.mongodb.panache.common.runtime.MongoOperations.mongoDatabase(MongoOperations.java:400)
at io.quarkus.mongodb.panache.common.runtime.MongoOperations.mongoCollection(MongoOperations.java:193)
at io.quarkus.mongodb.panache.common.runtime.MongoOperations.count(MongoOperations.java:690)
at com.abc.model.Product.count(Product.java)

</body>
</html>

### How to Reproduce?

1. Create a MongoDB Atlas instance
2. Create AWS lambda app using MongoDB panache as ORM layer
3. Deploy lambda and test it.

**Comment by anamak9** [comment]
And if I don't use the below transitive dependencies, 
```
org.mongodb
mongodb-driver-sync
4.11.0

org.mongodb
mongodb-driver-reactivestreams
4.11.0
```

then I get the following error (note: user creds and cluster ids either hidden or fabricated), 

Logs:
2023-11-08 02:29:31,623 INFO  [org.mon.dri.cluster] (cluster-ClusterId{value='98af28bea87ad302ae84324', description='null'}-srv-sn-mongodb-cluster-us-e.thacgab.mongodb.net) Adding discovered server ac-cr8sxq9-shard-00-01.thacgab.mongodb.net:27017 to client view of cluster
2023-11-08 02:29:31,727 INFO  [org.mon.dri.client] (executor-thread-1) MongoClient with metadata 
{
    "driver": {
        "name": "mongo-java-driver|sync",
        "version": "4.10.2"
    },
    "os": {
        "type": "Linux",
        "name": "Linux",
        "architecture": "amd64",
        "version": "5.10.196-205.748.amzn2.x86_64"
    },
    "platform": "Java/Amazon.com Inc./17.0.8.1+8-LTS"
}
 created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=true}, retryWrites=false, retryReads=true, readConcern=ReadConcern{level=null}, credential=MongoCredential{mechanism=null, userName=<hidden>, source=<hidden>, password=<hidden>, mechanismProperties=<hidden>}, streamFactoryFactory=null, commandListeners=[], codecRegistry=ProvidersCodecRegistry{codecProviders=[ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, CollectionCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.client.model.mql.ExpressionCodecProvider@4b882135, com.mongodb.Jep395RecordCodecProvider@d41772c, com.mongodb.KotlinCodecProvider@67e8ccc2]}, ProvidersCodecRegistry{codecProviders=[org.bson.codecs.pojo.PojoCodecProvider@1adb98d4]}]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[127.0.0.1:27017], srvHost=sn-mongodb-cluster-us-e.thacgab.mongodb.net, srvServiceName=mongodb, mode=MULTIPLE, requiredClusterType=REPLICA_SET, requiredReplicaSetName='atlas-meta53-shard-0', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='30000 ms', localThreshold='30000 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, sendBufferSize=0}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, sendBufferSize=0}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=true, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=UNSPECIFIED, serverApi=null, autoEncryptionSettings=null, dnsClient=null, inetAddressResolver=null, contextProvider=null}
2023-11-08 02:29:31,901 INFO  [org.mon.dri.cluster] (cluster-ClusterId{value='98af28bea87ad302ae84324', description='null'}-srv-sn-mongodb-cluster-us-e.thacgab.mongodb.net) Adding discovered server ac-cr8sxq9-shard-00-02.thacgab.mongodb.net:27017 to client view of cluster
2023-11-08 02:29:31,920 INFO  [org.mon.dri.cluster] (cluster-ClusterId{value='98af28bea87ad302ae84324', description='null'}-srv-sn-mongodb-cluster-us-e.thacgab.mongodb.net) Adding discovered server ac-cr8sxq9-shard-00-00.thacgab.mongodb.net:27017 to client view of cluster
2023-11-08 02:29:32,221 INFO  [org.mon.dri.cluster] (cluster-ClusterId{value='98af28bea87ad302ae84324', description='null'}-ac-cr8sxq9-shard-00-02.thacgab.mongodb.net:27017) Exception in monitor thread while connecting to server ac-cr8sxq9-shard-00-02.thacgab.mongodb.net:27017: com.mongodb.MongoSocketWriteException: Exception sending message
at com.mongodb.internal.connection.InternalStreamConnection.translateWriteException(InternalStreamConnection.java:708)
at com.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:585)
at com.mongodb.internal.connection.InternalStreamConnection.sendCommandMessage(InternalStreamConnection.java:416)
at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:362)
at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:102)
at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:49)
at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:129)
at com.mongodb.internal.connection.InternalStreamConnectionInitializer.startHandshake(InternalStreamConnectionInitializer.java:77)
at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:211)
at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:199)
at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:159)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(Unknown Source)
at com.mongodb.internal.connection.SocketStream.write(SocketStream.java:102)
at com.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:582)
... 10 more
2023-11-08 02:29:32,241 INFO  [org.mon.dri.cluster] (cluster-ClusterId{value='98af28bea87ad302ae84324', description='null'}-ac-cr8sxq9-shard-00-00.thacgab.mongodb.net:27017) Exception in monitor thread while connecting to server ac-cr8sxq9-shard-00-00.thacgab.mongodb.net:27017: com.mongodb.MongoSocketWriteException: Exception sending message
at com.mongodb.internal.connection.InternalStreamConnection.translateWriteException(InternalStreamConnection.java:708)
at com.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:585)
at com.mongodb.internal.connection.InternalStreamConnection.sendCommandMessage(InternalStreamConnection.java:416)
at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:362)
at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:102)
at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:49)
at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:129)
at com.mongodb.internal.connection.InternalStreamConnectionInitializer.startHandshake(InternalStreamConnectionInitializer.java:77)
at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:211)
at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:199)
at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:159)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(Unknown Source)
at com.mongodb.internal.connection.SocketStream.write(SocketStream.java:102)
at com.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:582)
... 10 more
2023-11-08 02:29:32,222 INFO  [org.mon.dri.cluster] (cluster-ClusterId{value='98af28bea87ad302ae84324', description='null'}-ac-cr8sxq9-shard-00-01.thacgab.mongodb.net:27017) Exception in monitor thread while connecting to server ac-cr8sxq9-shard-00-01.thacgab.mongodb.net:27017: com.mongodb.MongoSocketWriteException: Exception sending message
at com.mongodb.internal.connection.InternalStreamConnection.translateWriteException(InternalStreamConnection.java:708)
at com.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:585)
at com.mongodb.internal.connection.InternalStreamConnection.sendCommandMessage(InternalStreamConnection.java:416)
at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:362)
at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:102)
at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:49)
at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:129)
at com.mongodb.internal.connection.InternalStreamConnectionInitializer.startHandshake(InternalStreamConnectionInitializer.java:77)
at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:211)
at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:199)
at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:159)
at java.base/java.lang.Thread.run(Unknown Source)
**Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error**
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(Unknown Source)
at com.mongodb.internal.connection.SocketStream.write(SocketStream.java:102)
at com.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:582)
... 10 more
2023-11-08 02:29:32,283 INFO  [org.mon.dri.cluster] (executor-thread-1) No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=ac-cr8sxq9-shard-00-01.thacgab.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLException: Received fatal alert: internal_error}}, ServerDescription{address=ac-cr8sxq9-shard-00-02.thacgab.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLException: Received fatal alert: internal_error}}, ServerDescription{address=ac-cr8sxq9-shard-00-00.thacgab.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLException: Received fatal alert: internal_error}}]}. Waiting for 30000 ms before timing out
2023-11-08T02:29:45.160Z 3477e789-07f3-4b5c-a425-04439ecbe25c Task timed out after 15.03 seconds
