### ISSUE TITLE
Erroneous resteasy "Attempting a blocking read on io thread"

### ISSUE THREAD

**Issue by jtama** [quarkusio/quarkus#36943]
### Describe the bug

If resource endpoint has been wrongly mapped, we get an erroneous exception, at the very least not an easily inderstandable one.

### Expected behavior

The exception should cleary state the issue

### Actual behavior

The exception says the code is blocking, which is wrong, even though the code is indeed wrong...

### How to Reproduce?

Define an endpoint as follow :

```java
@GET
public Uni<String> acmeUniversity(String iAmNotMapped) {
    return Uni.createFrom().item("Acme looniversity");
}
```

If you trigger the endpoint you wil get a :

```java
org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException: Attempting a blocking read on io thread
        at org.jboss.resteasy.reactive.server.vertx.VertxInputStream$VertxBlockingInput.readBlocking(VertxInputStream.java:244)
        at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.readIntoBuffer(VertxInputStream.java:122)
        at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:84)
        at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:72)
        at org.jboss.resteasy.reactive.common.providers.serialisers.PrimitiveBodyHandler.readFrom(PrimitiveBodyHandler.java:22)
        at org.jboss.resteasy.reactive.server.providers.serialisers.ServerStringMessageBodyHandler.readFrom(ServerStringMessageBodyHandler.java:37)
        at org.jboss.resteasy.reactive.server.providers.serialisers.ServerStringMessageBodyHandler.readFrom(ServerStringMessageBodyHandler.java:15)
        at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:126)
        at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:84)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:135)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:102)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:88)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:290)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1589)

```

### Quarkus version or git rev

quarkus 3.5.0

**Comment by geoand** [comment]
I don't really understand how one would reproduce the problem based on the current description. Care to elaborate please?

**Comment by jtama** [comment]
You juste have to create an endpoint with resteasy-reactive, with a method parameter that is not resolvable. 

I know it's dumb and it's certainly a bug on code, but we should not yell at the developper that he is blocking a thread.

**Comment by FroMage** [comment]
It's not a parameter that can't be resolved. It's supposed to be the body of the http message. So, it should be read async before the method is called. That exception should not happen, for sure. This should just work.

**Comment by FroMage** [comment]
OK, then perhaps the class or package annotations, or config, are required to reproduce 🤷

**Comment by jtama** [comment]
Ok I'lll try to make a reproducer then.

**Comment by jtama** [comment]
Ok, so the error doesn't occure if the method simply returns a string. It as to be a Uni<String>. The error is triggered whatever the serialization (JSON/XML/PLAIN_TEXT)

**Comment by geoand** [comment]
Yes, I tried a Uni and could not reproduce the problem

**Comment by jtama** [comment]
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/13348889/code-with-quarkus.zip)

**Comment by geoand** [comment]
This is really a pathological case as a `GET` request is not meant to have a body.  The message is indeed not great, so I have opened #37219

**Comment by jtama** [comment]
Well, if we follow the norm, nothing prevents `GET` request to have a body : https://www.rfc-editor.org/rfc/rfc9112#name-message-body

But at least now developper will know where the error comes from.
