### ISSUE TITLE
Quarkus 3.5.x breaks Apache Tika

### ISSUE THREAD

**Issue by b-thiswatch** [quarkusio/quarkus#36974]
### Describe the bug

We are using Apache Tika 2.9.1 in a Quarkus project. Since 3.5.0 one of our tests is broken. We rolled back to 3.4.3. 

```shell
Test FileParserTest#Reading content from pdf file works() failed 
: java.lang.NoSuchMethodError: 'org.apache.fontbox.ttf.TrueTypeFont org.apache.fontbox.ttf.TTFParser.parse(java.io.InputStream)'
        at org.apache.pdfbox.pdmodel.font.FontMapperImpl.<init>(FontMapperImpl.java:130)
        at org.apache.pdfbox.pdmodel.font.FontMappers$DefaultFontMapper.<clinit>(FontMappers.java:36)
        at org.apache.pdfbox.pdmodel.font.FontMappers.instance(FontMappers.java:46)
        at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.<init>(PDTrueTypeFont.java:218)
        at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:89)
        at org.apache.pdfbox.pdmodel.PDResources.getFont(PDResources.java:171)
        at org.apache.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:66)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:980)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:555)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:530)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:155)
        at org.apache.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java:155)
        at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:363)
        at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:137)
        at org.apache.tika.parser.pdf.AbstractPDF2XHTML.processPages(AbstractPDF2XHTML.java:1369)
        at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:238)
        at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:108)
        at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:219)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:203)
```

### How to Reproduce?

Use Quarkus 3.5.x, add Tika

```kotlin
    implementation("org.apache.tika:tika-core:2.9.1")
    implementation("org.apache.tika:tika-langdetect-optimaize:2.9.1")
    implementation("org.apache.tika:tika-parsers-standard-package:2.9.1")
    implementation("org.apache.tika:tika-serialization:2.9.1")
```

and run something like this...

```kotlin
fun parseFile(file: File): FileParserResult {

        val config = TesseractOCRConfig()
        config.isSkipOcr = true
        val context = ParseContext()
        context.set(TesseractOCRConfig::class.java, config)

        val stream = FileInputStream(file)
        val parser = AutoDetectParser()
        val handler = BodyContentHandler(-1)
        val metadata = Metadata()

        parser.parse(stream, handler, metadata, context)
```

I can build a reproducer, if unclear...

Thanks!

**Comment by geoand** [comment]
cc @sberyozkin

**Comment by gsmet** [comment]
It doesn't look like a Quarkus problem since you are manually handling the versions. It looks like somehow you have inconsistent Tika/PDFBox dependencies.

**Comment by b-thiswatch** [comment]
thanks for looking in to this.
oh boy, i did not realise there is a tika quarkiverse extension. i don't see how it works with langdetect-optimaize, though, but i might figure this out.

**Comment by melloware** [comment]
Yes please use the Quarkus Tika extension and let us know anything over there that doesn't work @b-thiswatch

**Comment by gsmet** [comment]
I'm closing the issue here, please follow up in the Tika extension repository.
