### ISSUE TITLE
3.2.8.Final causing failure in ServerSentEventsTraceOpentracingIT in quarkus-qe/quarkus-test-suite

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#36979]
### Describe the bug

3.2.8.Final causing failure in ServerSentEventsTraceOpentracingIT in quarkus-qe/quarkus-test-suite

This test passes with 3.2.7.Final and prior versions.

```
16:09:54,515 INFO  ## Running test ServerSentEventsTraceOpentracingIT.testServerClientTrace()
16:09:56,782 INFO  [app] 16:09:55,577 Recorded trace ID: 47216c36c680e4bb
16:09:56,783 INFO  [app] 16:09:55,716 Recorded trace ID: 47216c36c680e4bb
16:09:56,783 INFO  [app] 16:09:55,742 Uncaught exception received by Vert.x: java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "this.data" is null
16:09:56,783 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.InboundSseEventImpl.readData(InboundSseEventImpl.java:121)
16:09:56,783 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.InboundSseEventImpl.readData(InboundSseEventImpl.java:111)
16:09:56,784 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.MultiInvoker.lambda$registerForSse$2(MultiInvoker.java:166)
16:09:56,784 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.SseEventSourceImpl.fireEvent(SseEventSourceImpl.java:224)
16:09:56,784 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.SseParser.dispatchEvent(SseParser.java:164)
16:09:56,784 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.SseParser.parseEvent(SseParser.java:138)
16:09:56,785 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.SseParser.handle(SseParser.java:108)
16:09:56,785 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.SseParser.handle(SseParser.java:11)
16:09:56,785 INFO  [app] 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
16:09:56,785 INFO  [app] 	at io.vertx.core.http.impl.HttpEventHandler.handleChunk(HttpEventHandler.java:51)
16:09:56,785 INFO  [app] 	at io.vertx.core.http.impl.HttpClientResponseImpl.handleChunk(HttpClientResponseImpl.java:239)
16:09:56,786 INFO  [app] 	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:454)
16:09:56,786 INFO  [app] 	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255)
16:09:56,786 INFO  [app] 	at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:242)
16:09:56,786 INFO  [app] 	at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:295)
16:09:56,786 INFO  [app] 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
16:09:56,787 INFO  [app] 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:259)
16:09:56,787 INFO  [app] 	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
16:09:56,787 INFO  [app] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
16:09:56,787 INFO  [app] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
16:09:56,787 INFO  [app] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
16:09:56,788 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
16:09:56,788 INFO  [app] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
16:09:56,788 INFO  [app] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
16:09:56,788 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
16:09:56,788 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:833)
16:09:56,789 INFO  [app] 16:09:55,743 Uncaught exception received by Vert.x: java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "this.data" is null
16:09:56,789 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.InboundSseEventImpl.readData(InboundSseEventImpl.java:121)
16:09:56,789 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.InboundSseEventImpl.readData(InboundSseEventImpl.java:111)
16:09:56,789 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.MultiInvoker.lambda$registerForSse$2(MultiInvoker.java:166)
16:09:56,789 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.SseEventSourceImpl.fireEvent(SseEventSourceImpl.java:224)
16:09:56,790 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.SseParser.dispatchEvent(SseParser.java:164)
16:09:56,790 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.SseParser.parseEvent(SseParser.java:138)
16:09:56,790 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.SseParser.handle(SseParser.java:108)
16:09:56,790 INFO  [app] 	at org.jboss.resteasy.reactive.client.impl.SseParser.handle(SseParser.java:11)
16:09:56,790 INFO  [app] 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
16:09:56,790 INFO  [app] 	at io.vertx.core.http.impl.HttpEventHandler.handleChunk(HttpEventHandler.java:51)
16:09:56,791 INFO  [app] 	at io.vertx.core.http.impl.HttpClientResponseImpl.handleChunk(HttpClientResponseImpl.java:239)
16:09:56,791 INFO  [app] 	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:454)
16:09:56,791 INFO  [app] 	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255)
16:09:56,791 INFO  [app] 	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:134)
16:09:56,791 INFO  [app] 	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleChunk(Http1xClientConnection.java:706)
16:09:56,792 INFO  [app] 	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:76)
16:09:56,792 INFO  [app] 	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:174)
16:09:56,792 INFO  [app] 	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseChunk(Http1xClientConnection.java:894)
16:09:56,792 INFO  [app] 	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:813)
16:09:56,792 INFO  [app] 	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:780)
16:09:56,793 INFO  [app] 	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
16:09:56,793 INFO  [app] 	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
16:09:56,793 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
16:09:56,793 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
16:09:56,793 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
16:09:56,793 INFO  [app] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
16:09:56,794 INFO  [app] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
16:09:56,794 INFO  [app] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
16:09:56,794 INFO  [app] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
16:09:56,794 INFO  [app] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
16:09:56,794 INFO  [app] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
16:09:56,795 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
16:09:56,795 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
16:09:56,795 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
16:09:56,795 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
16:09:56,795 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
16:09:56,795 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
16:09:56,795 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
16:09:56,796 INFO  [app] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
16:09:56,796 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
16:09:56,796 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
16:09:56,796 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
16:09:56,796 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
16:09:56,796 INFO  [app] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
16:09:56,797 INFO  [app] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
16:09:56,797 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
16:09:56,797 INFO  [app] 	at java.base/java.lang.Thread.run(Thread.java:833)
16:09:57,871 INFO  [app] Service stopped (Quarkus JVM mode)
```

### Expected behavior

ServerSentEventsTraceOpentracingIT test passes

### Actual behavior

ServerSentEventsTraceOpentracingIT test fails

### How to Reproduce?

 - Clone https://github.com/quarkus-qe/quarkus-test-suite repo 
 - Checkout `3.2` branch
 - run `mvn clean verify -f monitoring/opentracing-reactive-grpc -Dit.test=ServerSentEventsTraceOpentracingIT#testServerClientTrace -Dquarkus.platform.version=3.2.8.Final`

This test passes with 3.2.7.Final and prior versions.

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.2.8.Final

**Comment by rsvoboda** [comment]
Switch to 3.2 branch pls

**Comment by rsvoboda** [comment]
Trying to identify commit which changed the behaviour

Current window is:
e28b706025f - Fix assertions in Hibernate ORM 5.6 compatibility tests    FAIL
afb8cd8210b - Prevent recording configuration coming from Gradle     PASS

**Comment by gsmet** [comment]
I would bet on https://github.com/quarkusio/quarkus/pull/35990 .

**Comment by brunobat** [comment]
Thanks @rsvoboda I was able to reproduce it.

**Comment by aloubyansky** [comment]
Just tried with 3.4.1 where that change was introduced but for a different failure
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.4.1:build (build) on project monitoring-opentracing-reactive-grpc: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.resteasy.reactive.common.deployment.ResteasyReactiveCommonProcessor#checkMixingStacks threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Mixing RESTEasy Reactive and RESTEasy Classic client parts is not supported
[ERROR] 	at io.quarkus.resteasy.reactive.common.deployment.ResteasyReactiveCommonProcessor.checkMixingStacks(ResteasyReactiveCommonProcessor.java:105)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by rsvoboda** [comment]
@aloubyansky you need to be on 3.2 or 3.3, it has mixed resteasy classic and reactive, starting with 3.4 the build is aborted, before there was just a warning

**Comment by rsvoboda** [comment]
8449c98e2f5 - Don't ignore empty SSE events in client ... this one looks suspicious, checking now

**Comment by rsvoboda** [comment]
Yes, it's it. This commit make difference for the test

* 8449c98e2f5 - Don't ignore empty SSE events in client (9 days ago) <Georgios Andrianakis>   FAIL
* 154fe5115db - Fix windows paths (9 days ago) <Andy Damevin>       PASS

**Comment by rsvoboda** [comment]
Test module is using quarkus-rest-client-reactive and quarkus-resteasy-mutiny

**Comment by aloubyansky** [comment]
Can we run the same test against 3.4.1 though?

**Comment by brunobat** [comment]
FYI, OpenTracing is deprecated and will no longer be part of the core extensions after 3.6.

**Comment by brunobat** [comment]
I rebuilt Quarkus without https://github.com/quarkusio/quarkus/pull/35990 and the test passes. We have a winner.

**Comment by aloubyansky** [comment]
Either we find a backportable fix for for it or we revert https://github.com/quarkusio/quarkus/commit/8449c98e2f5c61156e79497c16f3b58c9b01435e

**Comment by brunobat** [comment]
cc @gsmet

**Comment by rsvoboda** [comment]
I switched `quarkus-rest-client-reactive` with `quarkus-rest-client-mutiny` and the test fails 

https://github.com/quarkusio/quarkus/commit/8449c98e2f5c61156e79497c16f3b58c9b01435e says
```
Don't ignore empty SSE events in client
RESTEasy Classic does not ignore them, so let's keep the same behavior
```

So I can confirm that in 3.2.8.Final we have consistent behaviour :) I will check what can be changed in test to make it running on 3.2.8.Final. But any hint from @geoand would be welcome.

**Comment by rsvoboda** [comment]
I don't see anything wrong with the app or anything that could be done on the app side.

changing `quarkus-resteasy-mutiny` to `quarkus-resteasy-reactive` makes the test run further, but it fails because of https://github.com/quarkusio/quarkus/issues/29539 , only the last span is available (`server-sent-events-pong` one), the first one is missing (`server-sent-events-ping`).

So I thing the scenario is now hitting some SSE limitation or issue in RESTEasy Classic.

**Comment by rsvoboda** [comment]
I remembered conversation I had with @cescoffier about SSE with `Multi<String>` on RESTEasy Classic
<img width="729" alt="Screenshot 2023-11-09 at 18 00 29" src="https://github.com/quarkusio/quarkus/assets/925259/16f9b240-071a-473d-b8f9-cdbbdbe5d4ee">

Seems the only remaining option is to disable the test and close this :)

Other suggestions?

**Comment by geoand** [comment]
Personally I am for not spending any extra time on anything SSE related in RESTEasy Classic.

**Comment by rsvoboda** [comment]
About SSE and RESTEasy Classic issues - shouldn't this be mentioned in our docs?

And also adding a note into https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.2 that if people are using SSE with quarkus-resteasy-mutiny and quarkus-rest-client-reactive they may encounter some troubles with 3.2.8.Final and the suggested mitigation is to use RESTEasy Reactive  instead of RESTEasy Classic

**Comment by geoand** [comment]
That probably makes sense

**Comment by felixng313** [comment]
It sometimes fails randomly. I don't know the pattern.

`2023-12-07T10:10:42.452640252Z 2023-12-07 18:10:42,451 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-2) Uncaught exception received by Vert.x: java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "this.data" is null
2023-12-07T10:10:42.452935566Z 	at org.jboss.resteasy.reactive.client.impl.InboundSseEventImpl.readData(InboundSseEventImpl.java:121)
2023-12-07T10:10:42.452960254Z 	at org.jboss.resteasy.reactive.client.impl.InboundSseEventImpl.readData(InboundSseEventImpl.java:111)
2023-12-07T10:10:42.452968642Z 	at org.jboss.resteasy.reactive.client.impl.MultiInvoker.lambda$registerForSse$2(MultiInvoker.java:166)
	at org.jboss.resteasy.reactive.client.impl.SseEventSourceImpl.fireEvent(SseEventSourceImpl.java:224)
2023-12-07T10:10:42.453009390Z 	at org.jboss.resteasy.reactive.client.impl.SseParser.dispatchEvent(SseParser.java:164)
2023-12-07T10:10:42.453014220Z 	at org.jboss.resteasy.reactive.client.impl.SseParser.parseEvent(SseParser.java:138)
2023-12-07T10:10:42.453020274Z 	at org.jboss.resteasy.reactive.client.impl.SseParser.handle(SseParser.java:108)
2023-12-07T10:10:42.453025390Z 	at org.jboss.resteasy.reactive.client.impl.SseParser.handle(SseParser.java:11)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
2023-12-07T10:10:42.453035199Z 	at io.vertx.core.http.impl.HttpEventHandler.handleChunk(HttpEventHandler.java:51)
2023-12-07T10:10:42.453040015Z 	at io.vertx.core.http.impl.HttpClientResponseImpl.handleChunk(HttpClientResponseImpl.java:239)
2023-12-07T10:10:42.453044768Z 	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:452)
2023-12-07T10:10:42.453049478Z 	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255)
2023-12-07T10:10:42.453054550Z 	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:134)
2023-12-07T10:10:42.453059264Z 	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleChunk(Http1xClientConnection.java:704)
2023-12-07T10:10:42.453064157Z 	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:76)
2023-12-07T10:10:42.453068870Z 	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:174)
2023-12-07T10:10:42.453073893Z 	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseChunk(Http1xClientConnection.java:918)
2023-12-07T10:10:42.453078879Z 	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:811)
2023-12-07T10:10:42.453083659Z 	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:778)
2023-12-07T10:10:42.453088589Z 	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
2023-12-07T10:10:42.453093338Z 	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
2023-12-07T10:10:42.453103082Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-07T10:10:42.453107773Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2023-12-07T10:10:42.453114002Z 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
2023-12-07T10:10:42.453119059Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
2023-12-07T10:10:42.453124028Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
2023-12-07T10:10:42.453133421Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
2023-12-07T10:10:42.453138308Z 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
2023-12-07T10:10:42.453143124Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
2023-12-07T10:10:42.453148023Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-07T10:10:42.453152744Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2023-12-07T10:10:42.453168083Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2023-12-07T10:10:42.453172815Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2023-12-07T10:10:42.453177518Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2023-12-07T10:10:42.453182301Z 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
2023-12-07T10:10:42.453187058Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
2023-12-07T10:10:42.453202875Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
2023-12-07T10:10:42.453207541Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
2023-12-07T10:10:42.453217818Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-12-07T10:10:42.453222644Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-12-07T10:10:42.453227149Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by geoand** [comment]
@rsvoboda should we close this?

**Comment by rsvoboda** [comment]
I think so, OpenTracing is deprecated
