### ISSUE TITLE
[GraalVM 24.0] quarkus-integration-test-simple-with-space fails to run with a recent JDK 22-based GraalVM master build

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#36998]
### Describe the bug

The simple-with-space native intergration test seems to fail to start:

```
 [INFO] Running io.quarkus.it.spaces.NativeGreetingResourceIT
Executing "/home/runner/work/mandrel/mandrel/quarkus/integration-tests/simple with space/target/quarkus-integration-test-simple-with-space-999-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/home/runner/work/mandrel/mandrel/quarkus/integration-tests/simple with space/target/quarkus.log -Dquarkus.log.file.enable=true -Dquarkus.log.category."io.quarkus".level=INFO -Dquarkus.native.native-image-xmx=5g"
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.347 s <<< FAILURE! -- in io.quarkus.it.spaces.NativeGreetingResourceIT
Error:  io.quarkus.it.spaces.NativeGreetingResourceIT.testHelloEndpoint -- Time elapsed: 0.015 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Unable to successfully launch process '4915'. Exit code is: '1'.
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:366)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Unable to successfully launch process '4915'. Exit code is: '1'.
	at io.quarkus.test.common.LauncherUtil.ensureProcessIsAlive(LauncherUtil.java:124)
	at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:87)
	at io.quarkus.test.common.DefaultNativeImageLauncher.start(DefaultNativeImageLauncher.java:110)
	at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:195)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.doProcessStart(QuarkusIntegrationTestExtension.java:294)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:163)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:130)
	... 1 more

[INFO] 
```

See: https://github.com/graalvm/mandrel/actions/runs/6819594271/job/18548520578#step:12:1555

### How to Reproduce?

Run the simple with space native integration test on a recent GraalVM 24.0 dev build.

**Comment by zakkak** [comment]
The root cause is:

```
java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/zakkak/code/quarkus/integration-tests/simple%20with%20space/target/quarkus-integration-test-simple-with-space-999-SNAPSHOT-native-image-source-jar/lib/io.smallrye.config.smallrye-config-core-3.4.1.jar
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.Resources.get(Resources.java:317)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.Resources.createURLs(Resources.java:434)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.Resources.createURLs(Resources.java:409)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.ResourcesHelper.nameToResourceListURLs(ResourcesHelper.java:115)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.ResourcesHelper.nameToResourceEnumerationURLs(ResourcesHelper.java:124)
	at java.base@22/java.lang.ClassLoader.getResources(ClassLoader.java:99)
	at java.base@22/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1199)
	at java.base@22/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1224)
	at java.base@22/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1269)
	at java.base@22/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1305)
	at java.base@22/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1387)
	at org.eclipse.microprofile.config.spi.ConfigProviderResolver.loadSpi(ConfigProviderResolver.java:135)
	at org.eclipse.microprofile.config.spi.ConfigProviderResolver.instance(ConfigProviderResolver.java:124)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
	at io.quarkus.runtime.configuration.ConfigUtils.getProfiles(ConfigUtils.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:199)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

**Comment by zakkak** [comment]
The issue seems related to https://github.com/oracle/graal/pull/7670 

URLs with '%20' in the path are not being properly decoded after this PR.

**Comment by zakkak** [comment]
Upstream fix for the issue: https://github.com/oracle/graal/pull/7815
