### ISSUE TITLE
Unable to invoke HTTP requests using RESTEasy Reactive Client from a Kotlin project

### ISSUE THREAD

**Issue by ioansurariu** [quarkusio/quarkus#37023]
### Describe the bug

I tried to instantiate and use the RESTEasy Reactive client as described in this guide ([https://quarkus.io/guides/rest-client](https://quarkus.io/guides/rest-client)) but from a Kotlin project instead. It works just fine for Java project, but when invoked from a Kotlin context it throws an internal server error like: jakarta.ws.rs.ProcessingException: EARLY_HINTS

### Expected behavior

HTTP requests are executed with no error

### Actual behavior

It throws an 500 Internal Server Error when it does an HTTP request.

```
java.lang.NoSuchFieldError: EARLY_HINTS
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseBegin(Http1xClientConnection.java:838)
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:805)
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:780)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Resulted in: jakarta.ws.rs.ProcessingException: EARLY_HINTS
	at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.unwrap(InvocationBuilderImpl.java:223)
	at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:324)
	at MyRestClient$$QuarkusRestClientInterface.getSomething(Unknown Source)
```

### How to Reproduce?

Create REST client:

```kotlin
@Path("/api")
@RegisterRestClient(configKey = "api")
interface MyRestClient {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    fun getSomething(): String
}
```

Inject the RestClient and use it:

```kotlin
@Inject
@field: RestClient
lateinit var myRestClient: MyRestClient

@GET
fun test(): String {
    return myRestClient.getSomething() // here it throws the error
}
```
application.properties

```text
quarkus.rest-client.api.url=<any_server_url; including localhost; http or https>
quarkus.rest-client.api.scope=jakarta.inject.Singleton
```

### Output of `uname -a` or `ver`

22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "17.0.8.1" 2023-08-24 OpenJDK Runtime Environment Homebrew (build 17.0.8.1+0) OpenJDK 64-Bit Server VM Homebrew (build 17.0.8.1+0, mixed mode, sharing)

### Quarkus version or git rev

Quarkus 3.5.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.6.3 Build time:   2023-10-04 15:59:47 UTC Revision:     1694251d59e0d4752d547e1fd5b5020b798a7e71  Kotlin:       1.7.10 Groovy:       3.0.13 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.8.1 (Homebrew 17.0.8.1+0) OS:           Mac OS X 13.2.1 aarch64

**Comment by mschorsch** [comment]
@ioansurariu Do you have a reproducer? We use the resteasy reactive rest client and kotlin in our products without problems.

Hint: The link to the guide ist https://quarkus.io/guides/rest-client-reactive

**Comment by ioansurariu** [comment]
@mschorsch thank you for the quick reply. It turned out I had a Netty dependency conflict. After solving it the issue gone.
