### ISSUE TITLE
com.jcraft.jsch.jzlib.Compression not included in native compilation

### ISSUE THREAD

**Issue by gnieser** [quarkusio/quarkus#37064]
### Describe the bug

Hello,

The class `com.jcraft.jsch.jzlib.Compression` is missing from the Quarkus JSch when compiling to native.

It is used by reflection JSch session when initializing an [inflater](https://github.com/mwiede/jsch/blob/2dd6dc2628370c21dd34349eacb5be64d7bd949b/src/main/java/com/jcraft/jsch/Session.java#L2526) or a [deflater](https://github.com/mwiede/jsch/blob/2dd6dc2628370c21dd34349eacb5be64d7bd949b/src/main/java/com/jcraft/jsch/Session.java#L2493C52).
The class corresponds to the use of zlib compression as defined in the [JSch config map](https://github.com/mwiede/jsch/blob/2dd6dc2628370c21dd34349eacb5be64d7bd949b/src/main/java/com/jcraft/jsch/JSch.java#L189-L190)

I think it should be added to the [JSchProcessor](https://github.com/quarkiverse/quarkus-jsch/blob/229dbf8074d351eeb0d4eac2ee89cb17aaebc7ee/deployment/src/main/java/io/quarkus/jsch/deployment/JSchProcessor.java#L30) of quarkus-jsch extension.

Thanks

### Expected behavior

The class to be included in the native executable.

So far I'm using as a workaround an explicit registration for reflection.
```
@RegisterForReflection(targets = {com.jcraft.jsch.jzlib.Compression.class})
public class JSchCompressionReflectionConfiguration {
}
```

### Actual behavior

The class is not included and without workaround the following exception is raised in native only.
```
Caused by: java.lang.ClassNotFoundException: com.jcraft.jsch.jzlib.Compression
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:123)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:87)
	at java.base@17.0.9/java.lang.Class.forName(DynamicHub.java:1322)
	at java.base@17.0.9/java.lang.Class.forName(DynamicHub.java:1285)
	at java.base@17.0.9/java.lang.Class.forName(DynamicHub.java:1278)
	at com.jcraft.jsch.Session.initDeflater(Session.java:2493)
	... 21 more
```

### How to Reproduce?

I'm using a Quarkus Camel route with SFTP component and compression level at 9.

I'm using Quarkus version 3.4.3, I'm sure it hits other version too. The class was renamed in Aug 2021 which is probably when the Quarkus JSch extension stopped included it.
https://github.com/mwiede/jsch/commit/4a9152cf5a7d3d0b4a1b02e3e71a9f369bf555bd#diff-a7096f419f397fd75a0bfc29ad53cb793e3245bb394b6beeb20f9eb7c485abcb
https://github.com/mwiede/jsch/commit/4a9152cf5a7d3d0b4a1b02e3e71a9f369bf555bd#diff-386872d0e566ffedfe882af926962125b51f440abeb4b7a81013511f748f17ba

### Output of `uname -a` or `ver`

Linux lh1v-devci02 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)

### Mandrel or GraalVM version (if different from Java)

OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

**Comment by gnieser** [comment]
Sorry, I've just realized that the extension repository has GitHub issues. I'll reopen this over there.
