### ISSUE TITLE
Messaging Emitter can't handle Objects

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#37110]
### Describe the bug

I've found that the emitter used for sending messages can't handle sending objects, even though the API appears to accept them.

I'll note I am using Jackson, as per the guide: https://quarkus.io/guides/amqp

### Expected behavior

```
    @Channel("calculator-results")
    Emitter<CalculationResult> quoteRequestEmitter;

    public void sendResult(CalculationResult result){
        this.quoteRequestEmitter.send(Message.of(result));
    }
```
Should be acceptable

### Actual behavior

Get the following error:

```
2023-11-15 10:26:42,184 ERROR [io.sma.rea.mes.provider] (vert.x-eventloop-thread-0) SRMSG00201: Error caught while processing a message in method org.acme.interfaces.message.CalculatorMessenger#process: java.lang.ClassCastException: class io.vertx.core.json.JsonObject cannot be cast to class com.fasterxml.jackson.databind.JsonNode (io.vertx.core.json.JsonObject and com.fasterxml.jackson.databind.JsonNode are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @27ae2fd0)
	at org.acme.interfaces.message.CalculatorMessenger_SmallRyeMessagingInvoker_process_23024026a695027853c3a36f832876685db6fcae.invoke(Unknown Source)
	at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeBlocking$10(AbstractMediator.java:171)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:36)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
	at io.vertx.mutiny.core.Context$1.handle(Context.java:172)
	at io.vertx.mutiny.core.Context$1.handle(Context.java:170)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

Reproducer: https://github.com/GregJohnStewart/calc-quarkus 

https://github.com/GregJohnStewart/calc-quarkus/blob/main/src/main/java/org/acme/interfaces/message/CalculatorMessenger.java#L27

Run in dev mode, hit the `/calculate/5/ADD/5` endpoint, optionally from Swagger in dev ui

### Quarkus version or git rev

3.5.1

**Comment by ozangunalp** [comment]
It works as expected. The issue is in your consume method which expects a Jackson JsonNode, but the AMQP connector returns a [Vert.x JsonObject](https://vertx.io/docs/apidocs/io/vertx/core/json/JsonObject.html).

**Comment by GregJohnStewart** [comment]
Somehow even though I was not exercising this code, was the issue. There is probably a conversation there about accepting pojos or actually jackson as parameters instead of a non-jackson-but-looks-like-jackson json objects, but not here. Thanks
