### ISSUE TITLE
Call to DB2 is failing for the first time and abruptly once in a while making a hibernate call from QUARKUS application

### ISSUE THREAD

**Issue by satwikburman** [quarkusio/quarkus#37134]
### Describe the bug

**Stack trace from the error :** 

```

15:11:2023 18:13:19,048 INFO  [com.delta.techops.lmo.med.dao.RoutingRestrictionDao] (main) Message:"Inside fetchMelItemRestrictions(), FetchQuery : org.hibernate.query.internal.QueryImpl@65cf4d6d", ServiceName:"searchRestrictionsForItem", LambdaRuntimeEnvironment:"development-us-east-1", TransactionId:"mytran123456789"
15:11:2023 18:13:19,168 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) SQL Error: -4499, SQLState: 08001
15:11:2023 18:13:19,183 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) [jcc][t4][2030][11211][4.32.28] A communication error occurred during operations on the connection's underlying socket, socket input stream, 
or socket output stream.  Error location: Reply.fill() - socketInputStream.read (-1).  Message: Software caused connection abort (Write failed). ERRORCODE=-4499, SQLSTATE=08001
javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: could not extract ResultSet
at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626)
at org.hibernate.query.Query.getResultList(Query.java:165)
at com.delta.techops.lmo.med.dao.RoutingRestrictionDao.fetchMelItemRestrictions(RoutingRestrictionDao.java:53)
at com.delta.techops.lmo.med.dao.RoutingRestrictionDao_Subclass.fetchMelItemRestrictions$$superforward1(Unknown Source)
at com.delta.techops.lmo.med.dao.RoutingRestrictionDao_Subclass$$function$$1.apply(Unknown Source)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:133)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
at com.delta.techops.lmo.med.dao.RoutingRestrictionDao_Subclass.fetchMelItemRestrictions(Unknown Source)
at com.delta.techops.lmo.med.dao.RoutingRestrictionDao_ClientProxy.fetchMelItemRestrictions(Unknown Source)
at com.delta.techops.lmo.med.service.RoutingRestrictionsServiceImpl.getRestrictionsForItem(RoutingRestrictionsServiceImpl.java:95)
at com.delta.techops.lmo.med.service.RoutingRestrictionsServiceImpl_ClientProxy.getRestrictionsForItem(Unknown Source)
at com.delta.techops.lmo.med.handler.SearchRestrictionsForItemHandler.handleRequest(SearchRestrictionsForItemHandler.java:94)
at com.delta.techops.lmo.med.handler.SearchRestrictionsForItemHandler.handleRequest(SearchRestrictionsForItemHandler.java:32)
at com.delta.techops.lmo.med.handler.SearchRestrictionsForItemHandler_ClientProxy.handleRequest(Unknown Source)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.handle(AmazonLambdaRecorder.java:83)
at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.handleRequest(QuarkusStreamHandler.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:383)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:925)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:207)
at lambdainternal.AWSLambda.main(AWSLambda.java:196)
Caused by: org.hibernate.exception.JDBCConnectionException: could not extract ResultSet
at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)
at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
at org.hibernate.loader.Loader.getResultSet(Loader.java:2322)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2075)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
at org.hibernate.loader.Loader.doQuery(Loader.java:956)
at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
at org.hibernate.loader.Loader.doList(Loader.java:2868)
at org.hibernate.loader.Loader.doList(Loader.java:2850)
at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
at org.hibernate.loader.Loader.list(Loader.java:2677)
at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459)
at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
... 32 more
Caused by: com.ibm.db2.jcc.am.DisconnectNonTransientConnectionException: [jcc][t4][2030][11211][4.32.28] A communication error occurred during operations on the connection's underlying socket, socket input stream, 
or socket output stream.  Error location: Reply.fill() - socketInputStream.read (-1).  Message: Software caused connection abort (Write failed). ERRORCODE=-4499, SQLSTATE=08001
at com.ibm.db2.jcc.am.b7.a(b7.java:338)
at com.ibm.db2.jcc.t4.a.a(a.java:577)
at com.ibm.db2.jcc.t4.a.a(a.java:561)
at com.ibm.db2.jcc.t4.a.a(a.java:556)
at com.ibm.db2.jcc.t4.a.b(a.java:1727)
at com.ibm.db2.jcc.t4.a.a(a.java:1752)
at com.ibm.db2.jcc.t4.a.h(a.java:495)
at com.ibm.db2.jcc.t4.a.flush_(a.java:420)
at com.ibm.db2.jcc.am.Agent.flow(Agent.java:265)
at com.ibm.db2.jcc.am.ld.a(ld.java:4723)
at com.ibm.db2.jcc.am.ld.b(ld.java:4338)
at com.ibm.db2.jcc.am.ld.bd(ld.java:787)
at com.ibm.db2.jcc.am.ld.executeQuery(ld.java:752)
at io.agroal.pool.wrapper.PreparedStatementWrapper.executeQuery(PreparedStatementWrapper.java:78)
at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
... 47 more
Caused by: java.net.SocketException: Software caused connection abort (Write failed)
at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
at java.base/java.net.SocketOutputStream.socketWrite(Unknown Source)
at java.base/java.net.SocketOutputStream.write(Unknown Source)
at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(Unknown Source)
at com.ibm.db2.jcc.t4.ae.b(ae.java:2069)
at com.ibm.db2.jcc.t4.ae.a(ae.java:2011)
at com.ibm.db2.jcc.t4.a.h(a.java:488)
... 55 more
15:11:2023 18:13:19,219 WARN  [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (main) Datasource '<default>': JDBC resources leaked: 0 ResultSet(s) and 1 Statement(s)
15:11:2023 18:13:19,235 WARN  [com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord] (main) ARJUNA016045: attempted rollback of < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffffa9fef005:b1dd:65550a3e:0, node_name=quarkus, branch_uid=0:ffffa9fef005:b1dd:65550a3e:3, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@6dd36ab6) failed with exception code XAException.XAER_RMERR: javax.transaction.xa.XAException: Error trying to transactionRollback local transaction: [jcc][t4][10335][10366][4.32.28] Invalid operation: Connection is closed. ERRORCODE=-4470, SQLSTATE=08003
at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:140)
at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:134)
at io.agroal.narayana.LocalXAResource.rollback(LocalXAResource.java:88)
at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelAbort(XAResourceRecord.java:362)
at com.arjuna.ats.arjuna.coordinator.BasicAction.doAbort(BasicAction.java:3037)
at com.arjuna.ats.arjuna.coordinator.BasicAction.doAbort(BasicAction.java:3016)
at com.arjuna.ats.arjuna.coordinator.BasicAction.Abort(BasicAction.java:1679)
at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.cancel(TwoPhaseCoordinator.java:124)
at com.arjuna.ats.arjuna.AtomicAction.abort(AtomicAction.java:186)
at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.rollbackAndDisassociate(TransactionImple.java:1377)
at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.rollback(BaseTransaction.java:145)
at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.rollback(NotifyingTransactionManager.java:94)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:372)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:170)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:104)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:58)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
at com.delta.techops.lmo.med.dao.RoutingRestrictionDao_Subclass.fetchMelItemRestrictions(Unknown Source)
at com.delta.techops.lmo.med.dao.RoutingRestrictionDao_ClientProxy.fetchMelItemRestrictions(Unknown Source)
at com.delta.techops.lmo.med.service.RoutingRestrictionsServiceImpl.getRestrictionsForItem(RoutingRestrictionsServiceImpl.java:95)
at com.delta.techops.lmo.med.service.RoutingRestrictionsServiceImpl_ClientProxy.getRestrictionsForItem(Unknown Source)
at com.delta.techops.lmo.med.handler.SearchRestrictionsForItemHandler.handleRequest(SearchRestrictionsForItemHandler.java:94)
at com.delta.techops.lmo.med.handler.SearchRestrictionsForItemHandler.handleRequest(SearchRestrictionsForItemHandler.java:32)
at com.delta.techops.lmo.med.handler.SearchRestrictionsForItemHandler_ClientProxy.handleRequest(Unknown Source)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.handle(AmazonLambdaRecorder.java:83)
at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.handleRequest(QuarkusStreamHandler.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:383)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:925)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:207)
at lambdainternal.AWSLambda.main(AWSLambda.java:196)
Caused by: com.ibm.db2.jcc.am.SqlNonTransientConnectionException: [jcc][t4][10335][10366][4.32.28] Invalid operation: Connection is closed. ERRORCODE=-4470, SQLSTATE=08003
at com.ibm.db2.jcc.am.b7.a(b7.java:800)
at com.ibm.db2.jcc.am.b7.a(b7.java:66)
at com.ibm.db2.jcc.am.b7.a(b7.java:133)
at com.ibm.db2.jcc.am.Connection.checkForClosedConnection(Connection.java:6279)
at com.ibm.db2.jcc.am.Connection.rollbackX(Connection.java:1423)
at com.ibm.db2.jcc.am.Connection.rollback(Connection.java:1412)
at io.agroal.pool.ConnectionHandler.transactionRollback(ConnectionHandler.java:366)
at io.agroal.narayana.LocalXAResource.rollback(LocalXAResource.java:85)
... 37 more
15:11:2023 18:13:19,244 WARN  [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (main) Datasource '<default>': [jcc][t4][10335][10366][4.32.28] Invalid operation: Connection is closed. ERRORCODE=-4470, SQLSTATE=08003
15:11:2023 18:13:19,250 ERROR [com.delta.techops.lmo.med.service.RoutingRestrictionsServiceImpl] (main) Message:"Exit getRestrictionsForItem() - MEDException -> getRestrictionsForItem() Failure in DB2 Processing failed (Status Code) -> getRestrictionsForItem() 500", ServiceName:"searchRestrictionsForItem", LambdaRuntimeEnvironment:"development-us-east-1", TransactionId:"mytran123456789"
15:11:2023 18:13:19,272 ERROR [com.delta.techops.lmo.med.handler.SearchRestrictionsForItemHandler] (main) Message:"Exit handleRequest() - MEDException - null Processing failed (Response) - {statusCode: 503,headers: {X-Custom-Header=application/json, Access-Control-Allow-Origin=*, Access-Control-Allow-Methods=GET, OPTIONS, Access-Control-Allow-Headers=*, Content-Type=application/json},body: {"statusCode":503,"errorDescription":"Error while executing query fetch MEL item restrictions","errors":[{"code":"ROURES006E","message":"Failure occurred in DB2"}]}}", ServiceName:"searchRestrictionsForItem", LambdaRuntimeEnvironment:"development-us-east-1", TransactionId:"mytran123456789"

```
### Expected behavior

Expected behavior is the call should be consistent and should not fail abruptly.

### Actual behavior

Call failing for the first time, after that it is passing and again if kept idle for sometime it is failing and then again passing, same pattern noticed time and time again.

### How to Reproduce?

Reproducer:

Quarkus version 2.15.1.Final
Using Quarkus hibernate ORM and Quarkus JDBC DB2

```
**Sample code :** 
```
```
 @Transactional
    @SuppressWarnings("unchecked")
    public List<String> fetchItemCodeForSingleRestrictionId(String transactionId, String restrictionId) throws MEDException {
        String logMessage = MEDUtil.generateLog(Constant.SEARCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getConstantType(), "Enter fetchItemCodeForSingleRestrictionId()", transactionId);
        LOGGER.info(logMessage);
        logMessage = MEDUtil.generateLog(Constant.SEARCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getConstantType(), "Inside fetchItemCodeForSingleRestrictionId(), The incoming restrictionId is :" +restrictionId, transactionId);
        LOGGER.info(logMessage);
        try {
            List<String> filteredItemCodeListForSingleRestrictionId = new ArrayList<>();
            Query fetchQuery = em.createQuery(QueryScript.getItemCodeSubFleetDetailsQuery).
                    setParameter(RESTRICTIONID,restrictionId);
            logMessage = MEDUtil.generateLog(Constant.SEARCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getConstantType(), "Inside fetchItemCodeForSingleRestrictionId(), FetchQuery : " +fetchQuery.toString(), transactionId);
            LOGGER.info(logMessage);
            List<Object[]> resultList = fetchQuery.getResultList();
            if(ObjectUtils.isNotEmpty(fetchQuery.getResultList())) {
                for (Object[] arr : resultList) {
                    System.out.println(Arrays.toString(arr));
                    filteredItemCodeListForSingleRestrictionId.add(Arrays.toString(arr));
                }
            }
            logMessage = MEDUtil.generateLog(Constant.SEARCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getConstantType(), "Exit fetchItemCodeForSingleRestrictionId(), size of filteredItemCodeListForSingleRestrictionId : " +filteredItemCodeListForSingleRestrictionId.size(), transactionId);
            LOGGER.info(logMessage);
            return filteredItemCodeListForSingleRestrictionId;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new MEDException(HttpStatus.SC_INTERNAL_SERVER_ERROR, ErrorDetails.ERROR_CODE_FETCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getErrorDesc(),
                    ErrorDetails.ERROR_CODE_FETCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getErrorCode(),
                    String.format(ErrorDetails.ERROR_CODE_FETCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getErrorMsg(), ex.getMessage()));
        }
    }
```
    
```
    **The HQL is :** 
```
    
        public static final String getItemCodeSubFleetDetailsQuery = "SELECT DISTINCT rest.deferralNumber, ser.configurationSubFleetNumber FROM MelItemRestrictions as rest, SerEquipmentAccount as ser WHERE ser.hpLpFleetCode = rest.ossFleetNumber AND rest.registrationId = :restrictionId";

Calling fetchItemCodeForSingleRestrictionId from service layer, PLEASE NOTE there is nothing wrong with the code and the query as it is working consistently after the first time, the issue is for the first time it is failing which should not

Call is happening from POSTMAN (9.20.3)
    

### Output of `uname -a` or `ver`

Windows 10 64 bit

### Output of `java -version`

openjdk version "11.0.1" 2018-10-16 OpenJDK Runtime Environment 18.9 (build 11.0.1+13) OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

### Quarkus version or git rev

Quarkus version 2.15.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

$ mvn -version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\Users\633647\softwares\delta_softwares\apache-maven-3.8.6
Java version: 11.0.18, vendor: Red Hat, Inc., runtime: C:\Program Files\RedHat\java-11-openjdk-11.0.18-1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by yrodiere** [comment]
@satwikburman Thanks for the report. Please format code and stack trace correctly, so that we can at least read your message.

Just add a line with three backticks before and after each snippet:

````
```
code
```
````

**Comment by satwikburman** [comment]
@yrodiere thanks for your response, Please check once. I have formatted the trace and the code for the same. Let me know if you need additional details on top of what has already been shared.

**Comment by yrodiere** [comment]
> @yrodiere thanks for your response, Please check once. I have formatted the trace and the code for the same. 

Your code does not appear to be formatted correctly.

**Comment by zhfeng** [comment]
@satwikburman can you try with the latest 2.x of Quarkus, like `2.16.12.Final`?

**Comment by satwikburman** [comment]
@Transactional
    @SuppressWarnings("unchecked")
    public List<String> fetchItemCodeForSingleRestrictionId(String transactionId, String restrictionId) throws MEDException {
        String logMessage = MEDUtil.generateLog(Constant.SEARCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getConstantType(), "Enter fetchItemCodeForSingleRestrictionId()", transactionId);
        LOGGER.info(logMessage);
        logMessage = MEDUtil.generateLog(Constant.SEARCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getConstantType(), "Inside fetchItemCodeForSingleRestrictionId(), The incoming restrictionId is :" +restrictionId, transactionId);
        LOGGER.info(logMessage);
        try {
            List<String> filteredItemCodeListForSingleRestrictionId = new ArrayList<>();
            Query fetchQuery = em.createQuery(QueryScript.getItemCodeSubFleetDetailsQuery).
                    setParameter(RESTRICTIONID,restrictionId);
            logMessage = MEDUtil.generateLog(Constant.SEARCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getConstantType(), "Inside fetchItemCodeForSingleRestrictionId(), FetchQuery : " +fetchQuery.toString(), transactionId);
            LOGGER.info(logMessage);
            List<Object[]> resultList = fetchQuery.getResultList();
            if(ObjectUtils.isNotEmpty(fetchQuery.getResultList())) {
                for (Object[] arr : resultList) {
                    System.out.println(Arrays.toString(arr));
                    filteredItemCodeListForSingleRestrictionId.add(Arrays.toString(arr));
                }
            }
            logMessage = MEDUtil.generateLog(Constant.SEARCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getConstantType(), "Exit fetchItemCodeForSingleRestrictionId(), size of filteredItemCodeListForSingleRestrictionId : " +filteredItemCodeListForSingleRestrictionId.size(), transactionId);
            LOGGER.info(logMessage);
            return filteredItemCodeListForSingleRestrictionId;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new MEDException(HttpStatus.SC_INTERNAL_SERVER_ERROR, ErrorDetails.ERROR_CODE_FETCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getErrorDesc(),
                    ErrorDetails.ERROR_CODE_FETCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getErrorCode(),
                    String.format(ErrorDetails.ERROR_CODE_FETCH_ITEM_CODE_SINGLE_RESTRICTION_ID.getErrorMsg(), ex.getMessage()));
        }
    }
    
    @yrodiere @zhfeng

**Comment by satwikburman** [comment]
@zhfeng @yrodiere 

No luck even after upgrading QUARKUS version, getting same error upon invoking for the first time with same stack trace, working fine after the first invokation.

**Comment by satwikburman** [comment]
Added snap start configuration and it is working now. Closing the issue.

**Comment by satwikburman** [comment]
Added snap start configuration and it is working now. Closing the issue.

**Comment by satwikburman** [comment]
```

@Startup
@ApplicationScoped
public class SnapstartConfiguration implements Resource {

	private static final Logger LOGGER = LoggerFactory.getLogger(SnapstartConfiguration.class);

	@Inject
	AgroalDataSource db2DataSource;

	@PostConstruct
	void init() {
		Core.getGlobalContext().register(this);
	}

	@Override
	public void beforeCheckpoint(org.crac.Context<? extends Resource> context) throws Exception {
		LOGGER.info("Before checkpoint hook");
		var db2Con = db2DataSource.getConnection();
		if (!db2Con.isClosed()) {
			LOGGER.info("Closing connection to DB2");
			db2Con.close();
		}
	}

	@Override
	public void afterRestore(org.crac.Context<? extends Resource> context) throws Exception {
		LOGGER.info("After restore hook : Attempting to establish connection to DB2 datasource");
		var db2Con = db2DataSource.getConnection();
		if( null != db2Con && !db2Con.isClosed()) {
			LOGGER.info("Successfully established connection to DB2 datasource");
		}
	}
}
```
This will work for DB2 and also for other kind of DBs like POSTGRESS as well.

**Comment by mswatosh** [comment]
@satwikburman I'm not very familiar with snapstart, so I may just be missing something here, but why bother getting a connection before the checkpoint?
```	
@Override
public void beforeCheckpoint(org.crac.Context<? extends Resource> context) throws Exception {
    LOGGER.info("Before checkpoint hook");
    var db2Con = db2DataSource.getConnection();
    if (!db2Con.isClosed()) {
	    LOGGER.info("Closing connection to DB2");
	    db2Con.close();
    }
}
```
Wouldn't this just result in a connection in the pool that is invalid by the time the restore occurs?

**Comment by satwikburman** [comment]
@mswatosh well from what I have understood QUARKUS establishes a connection and after a few minutes that established connection dies out and when the system tries to connect to the DB using that dead connection the first call fails and then in the next call it establishes a fresh connection which works. This is how the QUARKUS framework behaves.

That is the reason why if there is any open connection we close it so that the existing(probably dead) connection is not used while making a call and always a fresh connection is used while attempting to connect. So every time a fresh connection is established and the first call failing scenario does not occur.

**Comment by mswatosh** [comment]
@Sanne I'm curious what your thoughts are on this, I'm not very familiar with Hibernate, but I'm assuming when the EM is created it's creating a connection to the db (pre checkpoint), which is reused from the pool on the `em.createQuery` call when the function is run (post checkpoint), resulting in the error.

Since Agroal is a pool, my thought is that this is what's happening in the `beforeCheckpoint`:
```		
var db2Con = db2DataSource.getConnection();   <--- Get's a connection from the pool, like the one the EM created
if (!db2Con.isClosed()) {
	LOGGER.info("Closing connection to DB2");
	db2Con.close();  <---- returns the connection to the pool
}
```
The result of this would be effectively nothing. The same connection is still in the pool, and would be invalid after the Checkpoint restore. So why is this working?

Looking at the afterRestore, I think I see what's going on:
```
var db2Con = db2DataSource.getConnection(); <----- gets the invalid connection from the pool
if( null != db2Con && !db2Con.isClosed()) { <--- db2Con won't be null since we have a connection, 
                                               and importantly, the isClosed() method does not validate a 
                                               connection. It really only checks if close() has been called, 
                                               which it hasn't since we just got the connection
    LOGGER.info("Successfully established connection to DB2 datasource");
} 
```
Importantly, there is no `db2Con.close()` called in the afterRestore. So, what I think is happening here, is the `afterRestore` method is picking up the invalid connection, and leaking it, so the application can never use it.

@satwikburman I know you have this working and probably don't want to keep thinking about it, but if you wouldn't mind indulging my curiosity, does this still work if you close the connection in `afterRestore`?
```
@Override
public void afterRestore(org.crac.Context<? extends Resource> context) throws Exception {
    LOGGER.info("After restore hook : Attempting to establish connection to DB2 datasource");
    var db2Con = db2DataSource.getConnection();
    if( null != db2Con && !db2Con.isClosed()) {
	    LOGGER.info("Successfully established connection to DB2 datasource");
	    db2Con.close();
    }
}
```
