### ISSUE TITLE
Mongodb panache with multiple clients and reactive client not working

### ISSUE THREAD

**Issue by acuiuli** [quarkusio/quarkus#37168]
### Describe the bug

I'm using quarkus panache to access mongodb in my project. I need to connect to two different clusters and so I need to have different connection-string. This is what I'm doing right now

application.yaml
```
quarkus:
  mongodb:
    db1:
      connection-string: ${DB1_MONGODB_URI}
      database: ${DB1_MONGODB_DB}
    db2:
      connection-string: ${DB2_MONGODB_URI}
      database: ${DB2_MONGODB_DB}
```

First entity
```
@MongoEntity(collection = "log", clientName = "db1")
public class Log extends PanacheMongoEntityBase {
    @BsonId
    public ObjectId id;
    public LogType type;
    public String message;
    public Instant createdOn;
}
```

Second entity
```
@MongoEntity(collection = "order", clientName = "db2")
public class Order extends PanacheMongoEntityBase {
    @BsonId
    public ObjectId id;
    public BigDecimal total;
    public BigDecimal subtotal;
    ...
}
```

The problem seems to arise when I use also the reactive client with the @MongoClientName annotation. Something like this:

```
@ApplicationScoped
public class FirstRepository {

    @Inject
    @MongoClientName("db1")
    ReactiveMongoClient client;

    @ConfigProperty(name = "quarkus.mongodb.db1.database")
    String databaseName;

    public boolean existsOrder(ObjectId id) {
        return getCollection("order")
                .countDocuments(
                        Filters.eq("_id", id)

                )
                .await().atMost(Duration.ofSeconds(15)) > 0;
    }

    private ReactiveMongoCollection<Document> getCollection(String collectionName) {
        return client.getDatabase(databaseName).getCollection(collectionName);
    }
}
```

If I have also this class in the project and I try to call the persist(); method of the entity annotated with the clientName that is also used for the ReactiveMongoClient than I receive that error.

> 2023-11-15 11:31:11,268 ERROR [com.test.resource.Resource] (executor-thread-1) java.lang.IllegalStateException: Unable to find MongoClient bean for entity @io.quarkus.mongodb.panache.common.MongoEntity(readPreference="", database="", collection="log", clientName="db1")
	at io.quarkus.mongodb.panache.common.runtime.BeanUtils.clientFromArc(BeanUtils.java:58)
	at io.quarkus.mongodb.panache.common.runtime.MongoOperations.mongoDatabase(MongoOperations.java:395)
	at io.quarkus.mongodb.panache.common.runtime.MongoOperations.mongoCollection(MongoOperations.java:193)
	at io.quarkus.mongodb.panache.common.runtime.MongoOperations.mongoCollection(MongoOperations.java:391)
	at io.quarkus.mongodb.panache.common.runtime.MongoOperations.persist(MongoOperations.java:73)
	at io.quarkus.mongodb.panache.PanacheMongoEntityBase.persist(PanacheMongoEntityBase.java:36)

I cannot find anything online and I don't know what to do.
If I remove the double connections and work with entities without the clientName in the annotation everything works perfectly.

### Expected behavior

I should be able to use both the panache entities and the reactive client when there are multiple clientName in the same way it is possible to do with only one clientName.

### How to Reproduce?

Download this project and set up the two connection in the application.yaml and call the api to fire the persist method of one of the two entities.

https://file.io/Fmohi0hRqvY3

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045 DESKTOP-UC2UQJ1 3.0.7-338.x86_64 2019-07-03 15:16 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10) OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

### Quarkus version or git rev

3.5.0

**Comment by loicmathieu** [comment]
Related SO thread to answer the question when this issue has been tackled: https://stackoverflow.com/questions/77487005/quarkus-mongodb-panache-with-multiple-clients-not-working

**Comment by Steffi14** [comment]
Is there any update on this issue? We have the same problem and would need the Named MongoDb client to create indexes which can't be made otherwise.

**Comment by nconcetti** [comment]
Having investigated a bit into this (rather old) issue, i think the problem is caused by the panache extension. Specifically [in this class at line 38](https://github.com/quarkusio/quarkus/blob/a4b7f6088a2813a006df85525111e8385ac906da/extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/common/runtime/BeanUtils.java#L38).

.. which effectively prevents finding the default named client bean for entities which target another client. The rest of the code correctly resolves the named client.
