### ISSUE TITLE
RuntimeException in vertx is silently swallowed for blocking ConsumeEvents

### ISSUE THREAD

**Issue by ErrorProne** [quarkusio/quarkus#37222]
### Describe the bug

It looks like RuntimeExceptions are swallowed and don't reach the log if the ConsumeEvent is blocking, starting with quarkus 3.5.0
I've created a small reproducer: https://github.com/ErrorProne/missing-exception-for-blocking-consumer

With Quarkus < 3.5.0 both tests will output something like this
```java
2023-11-20 15:12:07,013 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-1) Uncaught exception received by Vert.x: java.lang.RuntimeException: I SHOULD BE IN THE LOG
	at org.acme.GreetingResource.nonblockingException(GreetingResource.java:41)
	at org.acme.GreetingResource_VertxInvoker_nonblockingException_2a6b7543e0b91dc3f6ae79b20bbcbac8094b81fe.invokeBean(Unknown Source)
```

and

```java
2023-11-20 15:12:06,994 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-0) Uncaught exception received by Vert.x: java.lang.RuntimeException: I SHOULD BE IN THE LOG
	at org.acme.GreetingResource.blockingException(GreetingResource.java:34)
```

In the versions 3.5.0, 3.5.1 and 3.5.1 the test with the blocking consumer won't output anything and the exception is not shown to the developer.

Possibly related to https://github.com/quarkusio/quarkus/issues/14591

### Expected behavior

Exception is shown in the log

### Actual behavior

Exception is not shown in the log

### How to Reproduce?

1. Add a blocking ConsumeEvent like `@ConsumeEvent(value = "blocking", blocking = true)`
2. In that event throw a RuntimeException
3. Send something on the bus - The exception should no appear in the log

### Output of `uname -a` or `ver`

Darwin Finns-MacBook-Pro.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21" 2023-09-19 OpenJDK Runtime Environment (build 21+35-2513) OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

**Comment by mkouba** [comment]
@cescoffier I wonder if the following change could be the cause: https://github.com/quarkusio/quarkus/commit/97c358a7001bca9cfd2244f51894fb38d5018eb5#diff-02f220fb13860e4ef7b3aef2a551a643b9152b34f603fcbd5e64a62dc1dd2030L138-L153

**Comment by cescoffier** [comment]
@mkouba yes, good catch. We need to setup an onFailure callback or log inside the existing one. Initially, the exception bubble-up to the Vert.x global exception handler.
