### ISSUE TITLE
Quarkus openshift extension fails to deploy application on OCP 4.14

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#37286]
### Describe the bug

I have an app, which is deployed to openshift 4.14 by `quarkus-openshift` extension. It can be deployed when I use Quarkus 3.5.0, but there is an exception, when I use 999-SNAPSHOT

### Expected behavior

The app should be deployed succesfully

### Actual behavior

an exception:
```
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: Service app.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: ImageStream openjdk-17.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: ImageStream app.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: BuildConfig app.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: DeploymentConfig app.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: Route app.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:38 min
[INFO] Finished at: 2023-11-23T16:31:18+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (build) on project many-extensions: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy threw an exception: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.ocp4-14.<redacted>:<redacted>/apis/monitoring.coreos.com/v1/servicemonitors. Message: Not Found.
[ERROR] 	at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:507)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleCreate(OperationSupport.java:340)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:753)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:97)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:42)
[ERROR] 	at io.fabric8.kubernetes.client.utils.internal.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:53)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:313)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:97)
[ERROR] 	at io.fabric8.kubernetes.client.extension.ResourceAdapter.createOrReplace(ResourceAdapter.java:124)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeployer.deployResource(KubernetesDeployer.java:242)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeployer.lambda$deploy$4(KubernetesDeployer.java:202)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[ERROR] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeployer.deploy(KubernetesDeployer.java:201)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesDeployer.deploy(KubernetesDeployer.java:142)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.ocp4-14.<redacted>:<redacted>/apis/monitoring.coreos.com/v1/servicemonitors. Message: Not Found.
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:640)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:589)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:549)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[ERROR] 	at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:140)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[ERROR] 	at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:52)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[ERROR] 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[ERROR] 	at io.fabric8.kubernetes.client.vertx.VertxHttpRequest.lambda$null$1(VertxHttpRequest.java:122)
[ERROR] 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
[ERROR] 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:259)
[ERROR] 	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
[ERROR] 	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:250)
[ERROR] 	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:446)
[ERROR] 	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255)
[ERROR] 	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:134)
[ERROR] 	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:710)
[ERROR] 	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:76)
[ERROR] 	at io.vertx.core.impl.ContextBase.execute(ContextBase.java:290)
[ERROR] 	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:946)
[ERROR] 	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:816)
[ERROR] 	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:780)
[ERROR] 	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
[ERROR] 	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[ERROR] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
[ERROR] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[ERROR] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[ERROR] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[ERROR] 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1471)
[ERROR] 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1334)
[ERROR] 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1383)
[ERROR] 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
[ERROR] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
[ERROR] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[ERROR] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[ERROR] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[ERROR] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[ERROR] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[ERROR] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[ERROR] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[ERROR] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[ERROR] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[ERROR] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[ERROR] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] -> [Help 1]

```

### How to Reproduce?

1.  `git clone git@github.com:quarkus-qe/quarkus-test-suite.git tests`
2. `cd tests/super-size/many-extensions`
3. Run the script:
```
mvn clean package -Dnative.encoding=UTF-8 -Pdeploy-to-openshift-using-extension -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.route.expose=true -Dquarkus.application.name=app -Dquarkus.kubernetes-client.trust-certs=true -Dquarkus.kubernetes.deployment-target=openshift -Dquarkus.s2i.base-jvm-image=registry.access.redhat.com/ubi8/openjdk-17:latest -Dquarkus.openshift.base-jvm-image=registry.access.redhat.com/ubi8/openjdk-17:latest -Dquarkus.platform.version=999-SNAPSHOT
```

This works:
```
mvn clean package -Dnative.encoding=UTF-8 -Pdeploy-to-openshift-using-extension -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.route.expose=true -Dquarkus.application.name=app -Dquarkus.kubernetes-client.trust-certs=true -Dquarkus.kubernetes.deployment-target=openshift -Dquarkus.s2i.base-jvm-image=registry.access.redhat.com/ubi8/openjdk-17:latest -Dquarkus.openshift.base-jvm-image=registry.access.redhat.com/ubi8/openjdk-17:latest -Dquarkus.platform.version=3.5.0
```

### Output of `uname -a` or `ver`

6.5.12-300.fc39.x86_64

### Output of `java -version`

17.0.8, vendor: Eclipse Adoptium

### Quarkus version or git rev

2cb598b2d3ff838e66558b6b56653370aa7816bb

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

### Additional information

```
$ oc version
Client Version: 4.13.0-202308290326.p0.g17b7acc.assembly.stream-17b7acc
Kustomize Version: v4.5.7
Kubernetes Version: v1.27.6+f67aeb3
```

**Comment by geoand** [comment]
Is this still an issue?

**Comment by fedinskiy** [comment]
Can not be reproduced for 3.10.1 or f02058038703b5f3b3bd50a4213b5f47fcb7e816

**Comment by geoand** [comment]
Thanks for checking
