### ISSUE TITLE
Using quarkus-amazon-lambda-rest and static mehtods with Annotations fails on build

### ISSUE THREAD

**Issue by dmoran-wpt** [quarkusio/quarkus#37386]
### Describe the bug

On a new generated project downloaded from code.quarkus.io (version 3.5.3), added a static method with an annotation @CacheInvalidate(cacheName = "test") or @Transactional, then builded with "mvn package" and then using "sam start api", the startup fails on the method which has the static method with the annotation.

### Expected behavior

Startup success

### Actual behavior

Fails on startup

### How to Reproduce?

1. Download a 3.5.3 quarkus from code.quarkus.io
2. add this package to pom.xml
```      
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-amazon-lambda-rest</artifactId>
    <version>${quarkus.platform.version}</version>
</dependency>
```
3. add static method with an Annotation on the GreetingResource.java. It could be CacheInvalidate, or Transactional or else. Ex:
```
@CacheInvalidateAll(cacheName = "test")
public static boolean invalidateCache(){
    return true;
}
```
4. package to generate the necessary files for aws lambda. I use the integrated mvn:
```
./mvnw clean package -Dmaven.test.skip=true
```
5. test builded code with sam:
```
sam local start-api --template target/sam.jvm.yaml
```
If it's fails for compiler version, it can be for the java runtime version in sam.jvm.waml (change it to java17)
6. call the endpoint /hello on the port assigned by sam (default 3000)
7. watch startup quarkus failing

### Output of `uname -a` or `ver`

Linux dmoran-ThinkPad 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.6" 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### Quarkus version or git rev

3.5.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /home/dmoran/.m2/wrapper/dists/apache-maven-3.9.5-bin/32db9c34/apache-maven-3.9.5 Java version: 17.0.6, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-17.0.6 Default locale: es_CL, platform encoding: UTF-8 OS name: "linux", version: "6.2.0-37-generic", arch: "amd64", family: "unix"

### Additional information

Here is the detail of the error on startup
```
java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at io.quarkus.runtime.Quarkus.manualInitialize(Quarkus.java:236)
        at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.<init>(QuarkusStreamHandler.java:21)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.arc.runtime.InterceptedStaticMethodsInitializer
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at io.quarkus.arc.runtime.InterceptedStaticMethodsRecorder.callInitializer(InterceptedStaticMethodsRecorder.java:17)
        at io.quarkus.deployment.steps.InterceptedStaticMethodsProcessor$callInitializer254957675.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.InterceptedStaticMethodsProcessor$callInitializer254957675.deploy(Unknown Source)
        ... 10 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "main"]
        at org.acme.GreetingResource_InterceptorInitializer.init_invalidateCache_a507a1b06db3a2e92c748e8345a77c6856dd2582(Unknown Source)
        at org.acme.GreetingResource_InterceptorInitializer.init_static_intercepted_methods(Unknown Source)
        at io.quarkus.arc.runtime.InterceptedStaticMethodsInitializer.<clinit>(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at io.quarkus.runtime.PreloadClassesRecorder.preloadClass(PreloadClassesRecorder.java:19)
        at io.quarkus.runtime.PreloadClassesRecorder.preloadClassesFromStream(PreloadClassesRecorder.java:56)
        at io.quarkus.runtime.PreloadClassesRecorder.preloadClasses(PreloadClassesRecorder.java:41)
        at io.quarkus.runtime.PreloadClassesRecorder.invokePreloadClasses(PreloadClassesRecorder.java:65)
        at io.quarkus.deployment.steps.PreloadClassesBuildStep$preInit93512537.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.PreloadClassesBuildStep$preInit93512537.deploy(Unknown Source)
        ... 10 more

29 Nov 2023 12:24:45,825 [ERROR] (rapid) Init failed InvokeID= error=Runtime exited with error: exit status 1
java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at io.quarkus.runtime.Quarkus.manualInitialize(Quarkus.java:236)
        at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.<init>(QuarkusStreamHandler.java:21)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.arc.runtime.InterceptedStaticMethodsInitializer
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at io.quarkus.arc.runtime.InterceptedStaticMethodsRecorder.callInitializer(InterceptedStaticMethodsRecorder.java:17)
        at io.quarkus.deployment.steps.InterceptedStaticMethodsProcessor$callInitializer254957675.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.InterceptedStaticMethodsProcessor$callInitializer254957675.deploy(Unknown Source)
        ... 10 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "main"]
        at org.acme.GreetingResource_InterceptorInitializer.init_invalidateCache_a507a1b06db3a2e92c748e8345a77c6856dd2582(Unknown Source)
        at org.acme.GreetingResource_InterceptorInitializer.init_static_intercepted_methods(Unknown Source)
        at io.quarkus.arc.runtime.InterceptedStaticMethodsInitializer.<clinit>(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at io.quarkus.runtime.PreloadClassesRecorder.preloadClass(PreloadClassesRecorder.java:19)
        at io.quarkus.runtime.PreloadClassesRecorder.preloadClassesFromStream(PreloadClassesRecorder.java:56)
        at io.quarkus.runtime.PreloadClassesRecorder.preloadClasses(PreloadClassesRecorder.java:41)
        at io.quarkus.runtime.PreloadClassesRecorder.invokePreloadClasses(PreloadClassesRecorder.java:65)
        at io.quarkus.deployment.steps.PreloadClassesBuildStep$preInit93512537.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.PreloadClassesBuildStep$preInit93512537.deploy(Unknown Source)
        ... 10 more
```

Here is the GreetingResource.java (this is the only resource that the project has)
```
package org.acme;

import io.quarkus.cache.CacheInvalidateAll;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import software.amazon.awssdk.annotations.NotNull;

@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public String hello(@NotNull Integer idClient) {
        return "Hello from RESTEasy Reactive";
    }
    
    
    @CacheInvalidateAll(cacheName = "test")
    public static boolean invalidateCache(){
        return true;
    }
}
```

**Comment by otoniel-zappyride** [comment]
Any news ?

**Comment by geoand** [comment]
Is this still a problem with the latest Quarkus versions?

**Comment by geoand** [comment]
Closing for lack of feedback
