### ISSUE TITLE
Building native during 3.5.3 -> 3.6.0 upgrade fails when using reactive messaging kafka

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#37385]
### Describe the bug

The superheroes CI is failing on upgrade from 3.5.3 -> 3.6.0 (see quarkusio/quarkus-super-heroes#451) when building native images for applications that include the reactive messaging kafka extension.

I've also posted this on Zulip: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/building.20native.20in.203.2E6.2E0.20fails

### Expected behavior

I would expect to be able to build a native image.

### Actual behavior

The native image build fails. For full CI logs, see https://github.com/quarkusio/quarkus-super-heroes/actions/runs/7031593678/job/19133547377?pr=451 and https://github.com/quarkusio/quarkus-super-heroes/actions/runs/7031593678/job/19133548028?pr=451

```
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/runner/work/quarkus-super-heroes/quarkus-super-heroes/rest-fights/target/rest-fights-1.0-native-image-source-jar/rest-fights-1.0-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/runner/work/quarkus-super-heroes/quarkus-super-heroes/rest-fights/target/rest-fights-1.0-native-image-source-jar/rest-fights-1.0-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on MANDREL 23.0.1.2 JDK 17.0.8+7
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /opt/hostedtoolcache/Java_jdkfile_jdk/17/x64/bin/native-image -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true -J-Dlogging.initial-configurator.min-level=500 -J-Dio.quarkus.caffeine.graalvm.recordStats=true -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Davro.disable.unsafe=true -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --features=io.quarkus.caffeine.runtime.graal.CacheConstructorsFeature,io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature,io.quarkus.hibernate.validator.runtime.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:BuildOutputJSONFile=rest-fights-1.0-runner-build-output-stats.json -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http,https -H:NativeLinkerOption=-no-pie --enable-monitoring=heapdump -H:-UseServiceLoaderFeature -H:+StackTrace -H:AdditionalSecurityProviders=com.sun.security.sasl.Provider,org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerSaslClientProvider,org.apache.kafka.common.security.scram.internals.ScramSaslClientProvider -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json rest-fights-1.0-runner -jar rest-fights-1.0-runner.jar
========================================================================================================================
GraalVM Native Image: Generating 'rest-fights-1.0-runner' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------

[1/8] Initializing...                                                                                    (0.0s @ 0.45GB)
Error: Substitution target for io.smallrye.reactive.kafka.graal.Target_com_jayway_jsonpath_internal_DefaultsImpl is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: Substitution target for io.smallrye.reactive.kafka.graal.Target_com_jayway_jsonpath_internal_DefaultsImpl is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
    at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
------------------------------------------------------------------------------------------------------------------------
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:1064)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:377)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:355)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:1003)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:888)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:579)
                        1.3s (11.6% of total time) in 26 GCs | Peak RSS: 1.05GB | CPU load: 3.37
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/runner/work/quarkus-super-heroes/quarkus-super-heroes/rest-fights/target/rest-fights-1.0-native-image-source-jar/rest-fights-1.0-runner-build-output-stats.json (build_info)
========================================================================================================================
Finished generating 'rest-fights-1.0-runner' in 10.3s.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:52 min
[INFO] Finished at: 2023-11-29T11:34:07Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.6.0:build (default) on project rest-fights: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: [ERROR]  [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
Error:      at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:468)
Error:      at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:258)
Error:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Error:      at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
Error:      at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
Error:      at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
Error:      at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
Error:      at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
Error:      at java.base/java.lang.Thread.run(Thread.java:833)
Error:      at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Error:  -> [Help 1]
Error:
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```

### Output of `java -version`

mandrel-23.0.1.2-Final-17

### Quarkus version or git rev

3.6.0

**Comment by edeandrea** [comment]
Seems there is an issue with the `io.strimzi:kafka-oauth-client` dependency. Additionally adding the `io.strimzi:kafka-oauth-common` dependency in the meantime fixes the issue.
