### ISSUE TITLE
Amazon Lamda IT raises exceptions

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#3743]
**Describe the bug**
Amazon integration tests raises 

**Expected behavior**
Tests to pass correctly without raising exception

**Actual behavior**
I am seeing the following errors:
```
2019-08-28 00:09:09,191 ERROR [io.qua.ama.lam.run.AmazonLambdaRecorder] (Lambda Thread) Failed to run lambda: java.lang.IllegalArgumentException: Can only greet nicknames
	at io.quarkus.it.amazon.lambda.ProcessingService.proces(ProcessingService.java:12)
	at io.quarkus.it.amazon.lambda.ProcessingService_ClientProxy.proces(ProcessingService_ClientProxy.zig:131)
	at io.quarkus.it.amazon.lambda.TestLambda.handleRequest(TestLambda.java:15)
	at io.quarkus.it.amazon.lambda.TestLambda.handleRequest(TestLambda.java:8)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$2.run(AmazonLambdaRecorder.java:68)
	at java.base/java.lang.Thread.run(Thread.java:834)

2019-08-28 00:09:09,225 WARN  [io.net.uti.con.AbstractEventExecutor] (vert.x-eventloop-thread-0) A task raised an exception. Task: io.undertow.vertx.VertxHttpExchange$7@3f69cac8: java.lang.NullPointerException
	at io.undertow.vertx.VertxHttpExchange$7.run(VertxHttpExchange.java:499)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Which is followed by this error:

```
2019-08-28 00:09:09,271 ERROR [io.qua.ama.lam.run.AmazonLambdaRecorder] (Lambda Thread) Failed to run lambda: java.net.SocketException: Connection reset
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1963)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1958)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1957)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1525)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$2.run(AmazonLambdaRecorder.java:67)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:859)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3084)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$2.run(AmazonLambdaRecorder.java:64)
```

**To Reproduce**
1. run `mvn clean install` on integration test directory and observe the console.

**Environment (please complete the following information):**
 - Quarkus version or git rev: `master`

**Comment by machi1990** [comment]
@stuartwdouglas looks like an issue similar to https://github.com/quarkusio/quarkus/issues/3558. I'll provide a PR in the quarkus-http repo.
