### ISSUE TITLE
Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: Make sure you have either Docker or Podman installed in your environment.

### ISSUE THREAD

**Issue by cmoulliard** [quarkusio/quarkus#37469]
### Describe the bug

JIB build fails when maven build of a quarkus application runs in a Tekton's pod. The code is looking about docker binary
```
Charles Moulliard: JIB don't need a docker binary but it complains

[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.3.Final:deploy (default-cli) on project quarkus-helloworld: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]     [error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.IllegalStateException: No container runtime was found. Make sure you have either Docker or Podman installed in your environment.
[ERROR]     at io.quarkus.runtime.util.ContainerRuntimeUtil.detectContainerRuntime(ContainerRuntimeUtil.java:52)
[ERROR]     at io.quarkus.runtime.util.ContainerRuntimeUtil.detectContainerRuntime(ContainerRuntimeUtil.java:38)
[ERROR]     at io.quarkus.container.image.jib.deployment.JibProcessor.createContainerizer(JibProcessor.java:290)
[ERROR]     at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:235)
[ERROR]     at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:181)
[ERROR]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Ioannis Canellos: Jib should not require a binary
```

### Expected behavior

Jib build should work without Docker binary included part of the container image

### How to Reproduce?

Steps to reproduce:

- Have access to a cluster: ocp or k8s
- Install Tekton
- Deploy a Pipeline and create a PipelineRun able to build a quarkus project using jib extension
```
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-maven-build
  namespace: default
spec:
  params:
  - description: url of the git repository to clone
    name: url
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: $(params.url)
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: project-dir
      workspace: project-dir

  - name: maven-build-image-deploy
    params:
    - name: GOALS
      value:
      - quarkus:deploy
      - -B
      - -Dquarkus.kubernetes.deploy=true
      - -Dquarkus.container-image.build=true
      - -Dquarkus.log.level=DEBUG
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: maven
    workspaces:
    - name: maven-settings
      workspace: maven-settings
    - name: project-dir
      workspace: project-dir
  workspaces:
  - name: project-dir
  - name: maven-m2-repo
  - name: maven-settings
```

### Output of `uname -a` or `ver`

Linux 5.19.6-300.fc37.x86_64

### Output of `java -version`

N/A

### Quarkus version or git rev

3.0.3.Final

**Comment by geoand** [comment]
Actually, `-Dquarkus.kubernetes.deploy=true` works with `mnv package`.  When using the CLI you should be following https://quarkus.io/blog/quarkus-cli/#deploying-using-the-quarkus-cli

**Comment by geoand** [comment]
Is this still an issue?

**Comment by cmoulliard** [comment]
Yes. I did a new test using 3.9.2 and got again same error with a project having jib extension

## Error
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.9.2:deploy (default-cli) on project my-quarkus-app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.IllegalStateException: No container runtime was found. Make sure you have either Docker or Podman installed in your environment.
[ERROR] 	at io.quarkus.deployment.util.ContainerRuntimeUtil.detectContainerRuntime(ContainerRuntimeUtil.java:58)
[ERROR] 	at io.quarkus.deployment.util.ContainerRuntimeUtil.detectContainerRuntime(ContainerRuntimeUtil.java:44)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.createContainerizer(JibProcessor.java:307)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:252)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:197)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[
```

## Maven command

```
        - 'quarkus:deploy'
        - '-B'
        - '-Dquarkus.kubernetes.deploy=false'
        - '-Dquarkus.container-image.build=true'
```

**Comment by DeMol-EE** [comment]
I had the same issue, but it turned out I had forgotten to specify `-Dquarkus.container-image.push=true`, which meant a local build was done, which does require docker (as also detailed [here](https://quarkus.io/guides/container-image#jib)).

**Comment by cmoulliard** [comment]
I know, I think, why we have this issue as quarkus `executes` [commands](https://github.com/quarkusio/quarkus/blob/7c176b698e1c86228ebd08de2c248d2c2dcf90d0/core/deployment/src/main/java/io/quarkus/deployment/util/ContainerRuntimeUtil.java#L234)

```
// https://github.com/quarkusio/quarkus/blob/7c176b698e1c86228ebd08de2c248d2c2dcf90d0/core/deployment/src/main/java/io/quarkus/deployment/util/ContainerRuntimeUtil.java#L234

    private static String getVersionOutputFor(ContainerRuntime containerRuntime) {
        Process versionProcess = null;
        try {
            final ProcessBuilder pb = new ProcessBuilder(containerRuntime.getExecutableName(), "--version")
                    .redirectErrorStream(true);
            versionProcess = pb.start();
            final int timeoutS = 10;
            if (versionProcess.waitFor(timeoutS, TimeUnit.SECONDS)) {
                return new String(versionProcess.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
            } else {
                log.debugf("Failure. It took command %s more than %d seconds to execute.", containerRuntime.getExecutableName(),
                        timeoutS);
                return "";
            }
        }
```

to determine if a `docker`, `podman` executable returns a response.

Of course, that works locally as the user has most probably installed `podman` or `docker` but when the code is executed in a pod using as image by example `maven` then no executable like docker or podman exist.

In this case, we should adopt a different strategy which is perhaps to curl the HTTP API endpoint

Example performed within a podman VM on macos where the API is exposed as service

```
curl -s --unix-socket /run/user/501/podman/podman.sock http://10.89.0.1:2375/v4.4.0/libpod/info
{"host":{"arch":"arm64","buildahVersion":"1.35.4","cgroupManager":"systemd","cgroupVersion":"v2","cgroupControllers":["cpu","io","memory","pids"],"conmon":{"package":"conmon-2.1.10-1.fc40.aarch64","path":"/usr/bin/conmon","version":"conmon version 2.1.10, commit: "},"cpus":6,"cpuUtilization":{"userPercent":3.01,"systemPercent":1.5,"idlePercent":95.49},"databaseBackend":"sqlite","distribution":{"distribution":"fedora","variant":"coreos","version":"40"},"eventLogger":"journald","freeLocks":2048,"hostname":"localhost.localdomain","idMappings":{"gidmap":[{"container_id":0,"host_id":1000,"size":1},{"container_id":1,"host_id":100000,"size":1000000}],"uidmap":[{"container_id":0,"host_id":501,"size":1},...
```
FYI: @iocanel @geoand

**Comment by geoand** [comment]
I have no knowledge of podman, so I can't comment. But if you want to provide a PR addressing the issue, that would be great

**Comment by cmoulliard** [comment]
> I have no knowledge of podman, so I can't comment.

This is completely independent of the executable detected within the code `docker` or `podman` as the `ProcessBuilder()` code will always fail when executed in a container or pod (= container) as the container, most probably, will never include such executables
I will (try) work on a PR as soon as I will masterize the logic of the plugin

**Comment by amoscatelli** [comment]
I always had this issue too ...

'''
[INFO] [INFO] --- quarkus-maven-plugin:3.18.3:build (default) @ greetings ---
[INFO] [WARNING] [io.quarkus.deployment.configuration] Configuration property 'quarkus.package.type' has been deprecated and replaced by: [quarkus.package.jar.enabled, quarkus.package.jar.type, quarkus.native.enabled, quarkus.native.sources-only]
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  02:18 min
[INFO] [INFO] Finished at: 2025-02-24T16:37:42Z
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.18.3:build (default) on project greetings: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[INFO] [ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#resolveNativeImageBuildRunner threw an exception: java.lang.IllegalStateException: No container runtime was found. Make sure you have either Docker or Podman installed in your environment.
'''

As a workaround I inject the docker binary inside the container from the dind sidecar (I am using tekton pipelines).
That's ugly for sure.

**Comment by saschpe** [comment]
This can easily be reproduced by creating a new Quarkus project and adding the Jib extension with no _Docker (Desktop)_ or _Podman (Desktop)_ installed:

```bash
quarkus create && cd code-with-quarkus
quarkus extension add container-image-jib
./mvnw -Dquarkus.container-image.build=true -Dquarkus.container-image.builder=jib package
```

That leads to:

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.22.3:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.IllegalStateException: No container runtime was found. Make sure you have either Docker or Podman installed in your environment.
[ERROR] 	at io.quarkus.deployment.util.ContainerRuntimeUtil.detectContainerRuntime(ContainerRuntimeUtil.java:71)
[ERROR] 	at io.quarkus.deployment.util.ContainerRuntimeUtil.detectContainerRuntime(ContainerRuntimeUtil.java:55)
[ERROR] 	at io.quarkus.deployment.util.ContainerRuntimeUtil.detectContainerRuntime(ContainerRuntimeUtil.java:47)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.createContainerizer(JibProcessor.java:287)
[ERROR] 	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:240)

```

**Comment by geoand** [comment]
> quarkus.container-image.build - only build OCI image layers w/o exporting to Docker or Podman

This is simply not possible.

**Comment by saschpe** [comment]
Huh? I can build OCI image layers by hand if necessary, as can do Jib. Exporting to any container engine would indeed require one installed. The "build" flag should simply build OCI images and nothing else. Exporting to Docker Desktop or publishing to a repository are entirely different things.

**Comment by geoand** [comment]
> Huh? I can build OCI image layers by hand if necessary, as can do Jib

It cannot build locally unless you mean just create a tarball

**Comment by saschpe** [comment]
Now we're getting there. Jib Maven (and Gradle similarly) has

- jib:buildTar
- jib:dockerBuild

Currently, you can't express what you want with the Quarkus Jib integration. Ideally, Quarkus would resort to "buildTar" when there's no Docker daemon around. That would be useful in CI situations where you don't have DinD (Docker in Docker) or similar and just want to archive the layers. Sometimes you want to run tools on them or put them in a Maven assembly for further redistribution. Currently, you can either build with Docker or Podman or not build at all.

**Comment by geoand** [comment]
Makes sense, however we can't do 

> quarkus.container-image.build - only build OCI image layers w/o exporting to Docker or Podman 

as it would break everyone using the extensions.
I someone can come up with a proper name and then drive the implementation (as my focus is way far away from the Docker/Jib  stuff I did 5+ years ago), then I'm perfectly happy to accept it.

**Comment by saschpe** [comment]
How about `quarkus.container-image.archive` or maybe just `quarkus.container-image.build-tar`?

**Comment by geoand** [comment]
Both sounds fine to me
