### ISSUE TITLE
Quarkus 3.5.3 RESTEasy Reactive unreliable

### ISSUE THREAD

**Issue by senzu** [quarkusio/quarkus#37480]
### Describe the bug

Hello!

I have an endpoint which receives huge amount of data from several clients, with the "old" RESTEasy there wasn't any problem, but with the transition to Reactive messed up the function. I'm always getting this error:

```posh
11:21:42 ERROR [io.un.request] (executor-thread-143) UT005071: Undertow request failed HttpServerExchange{ POST /@QuarkusError delegate io.undertow.vertx.VertxHttpExchange@27b47cf9}: java.lang.OutOfMemoryError: Cannot reserve 65536 bytes of direct buffer memory (allocated: 26157087, limit: 26214400)
        at java.base@21.0.1/java.nio.Bits.reserveMemory(Bits.java:178)
        at java.base@21.0.1/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)
        at java.base@21.0.1/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:360)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:717)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:692)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:215)
        at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:180)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:137)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:129)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$UndertowBufferAllocator.allocateBuffer(UndertowDeploymentRecorder.java:855)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$UndertowBufferAllocator.allocateBuffer(UndertowDeploymentRecorder.java:849)
        at io.undertow.server.HttpServerExchange.allocateBuffer(HttpServerExchange.java:1273)
        at io.undertow.servlet.spec.ServletOutputStreamImpl.underlyingBuffer(ServletOutputStreamImpl.java:284)
        at io.undertow.servlet.spec.ServletPrintWriter.write(ServletPrintWriter.java:263)
        at io.undertow.servlet.spec.ServletPrintWriter.write(ServletPrintWriter.java:308)
        at io.undertow.servlet.spec.ServletPrintWriterDelegate.write(ServletPrintWriterDelegate.java:111)
        at io.quarkus.undertow.runtime.QuarkusErrorServlet.service(QuarkusErrorServlet.java:56)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:229)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:164)
        at io.undertow.servlet.spec.RequestDispatcherImpl.error(RequestDispatcherImpl.java:494)
        at io.undertow.servlet.spec.RequestDispatcherImpl.error(RequestDispatcherImpl.java:427)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:281)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:626)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
        at io.undertow.server.handlers.CanonicalPathHandler.handleRequest(CanonicalPathHandler.java:49)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:125)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)
        at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$2.run(UndertowDeploymentRecorder.java:441)
        at java.base@21.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base@21.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1522)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
```

Is there any way to increase the buffer memory or switch back to "old" RESTEasy?

Best regards,
Viktor Kiss

**Comment by gsmet** [comment]
Yeah, your stacktrace is pointing Undertow as the culprit. If nothing has changed except moving from RESTEasy to RESTEasy Reactive, it might be that before the update the request was handled by RESTEasy and now it's delegated to Undertow for whatever reason.

As @geoand mentioned, we will need a small reproducer to get to the bottom of it.

**Comment by senzu** [comment]
Sorry, my bad, this is an undertow issue, I need it to get the client IP address, still using quarkus-reasteasy in this project. When I've read "Remember that RESTEasy Reactive is our default REST layer covering both reactive and blocking workloads." I thought quarkus-reasteasy became reactive

**Comment by senzu** [comment]
Could you tell me please how I could get the client IP address with RESTEasy Reactive? I would be happy to get rid of undertow...

**Comment by geoand** [comment]
Have you looked [here](https://github.com/quarkusio/quarkus/discussions/27451)?

**Comment by senzu** [comment]
I thought io.vertx.core.http.HttpServerRequest only can be used in Filter, but you can use it in the Controller as well

**Comment by geoand** [comment]
Yeah, you can inject it in any managed piece of code
