### ISSUE TITLE
Using underscore in lambda parameter name causes trouble for Quarkus

### ISSUE THREAD

**Issue by beikov** [quarkusio/quarkus#37523]
### Describe the bug

I have a CDI bean containing a lambda e.g. `(_) -> ...` using an underscore `_` as variable name (unnamed variable preview feature in Java 21 delivered by https://openjdk.org/jeps/443). Using that, fails the app startup.

### Expected behavior

It just works.

### Actual behavior

Exception on startup:

```
Caused by: java.lang.ClassFormatError: Illegal field name "" in class org/hibernate/examples/resources/StatisticsResource
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1018)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:508)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:496)
	at java.base/java.lang.Class.forName(Class.java:475)
	at org.hibernate.examples.resources.StatisticsResource_Bean.<init>(Unknown Source)
	at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans3(Unknown Source)
	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:127)
	at io.quarkus.arc.Arc.initialize(Arc.java:39)
	at io.quarkus.arc.runtime.ArcRecorder.initContainer(ArcRecorder.java:51)
	at io.quarkus.deployment.steps.ArcProcessor$initializeContainer1770303700.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$initializeContainer1770303700.deploy(Unknown Source)
	... 17 more
```

### How to Reproduce?

Enable preview language features with Java 21 and try to start an app with the following.

```java
@Path("res")
public class MyResource {
    @GET
    public Response get() {
        Function<Object, Object> f = _ -> null;
        f.apply(null);
        return Response.ok().build();
    }
}
```

### Output of `java -version`

21

### Quarkus version or git rev

3.6.0

**Comment by yrodiere** [comment]
Hey @mkouba @Ladicek , I tentatively assigned this to Arc, but I suspect this is more about Gizmo or something like that... Feel free to throw the ball to someone else :)

**Comment by Ladicek** [comment]
I tried to reproduce here https://github.com/Ladicek/quarkus-tinies/tree/main/unnamedvars and no success. There must be some more bytecode generation or transformation going on.

@beikov If the class you mention above is enough to trigger the problem, what extensions do you have?

**Comment by beikov** [comment]
Here is a snippet of part of the class.

```java
@Path("stats")
public class StatisticsResource {

    @Inject
    Session session;

    @GET
    @Path("top-products")
    @Produces(MediaType.APPLICATION_JSON)
    public List<TopTenProductResponseDto> findTopProducts() {
        return session.createQuery(
                """
                select
                    p.id as id, 
                    coalesce(sum(l.quantity) filter (where o.status <> CANCELLED),0) as amountSold
                from Order o
                join o.orderLines l
                join l.productVariant pv
                right join pv.product p
                group by id
                order by amountSold desc, id desc
                fetch first 10 rows with ties
                """,
                Object[].class
            )
            // workaround until https://github.com/quarkusio/quarkus/issues/37518 is fixed
            .setTupleTransformer((tuple, _) -> new TopTenProductResponseDto((Long) tuple[0], (BigDecimal) tuple[1]))
            .getResultList();
    }
}
```

**Comment by yrodiere** [comment]
FWIW Christian is on Windows.
I'll let him answer about the rest, but later, as he's talking at Quarkus Insights today.

**Comment by beikov** [comment]
Ughh, I still had the Java 21-ea on my Laptop. Can't reproduce the error with the 21 final release. Sorry for the noise.
