### ISSUE TITLE
Quarkus 3.6.2: NPE in quarkus-config during build time

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#37695]
### Describe the bug

Since Quarkus 3.6.2 we got the following exception during build, Quarkus 3.6.1 works fine:

```
[ERROR]       [error]: Build step io.quarkus.deployment.steps.ConfigGenerationBuildStep#unknownConfigFiles threw an exception: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "s" is null
[ERROR]       at java.base/java.lang.String.contains(String.java:2856)
[ERROR]       at io.quarkus.runtime.configuration.ConfigDiagnostic.unknownConfigFiles(ConfigDiagnostic.java:231)
[ERROR]       at io.quarkus.deployment.steps.ConfigGenerationBuildStep.unknownConfigFiles(ConfigGenerationBuildStep.java:439)
[ERROR]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]       at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR]       at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]       at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]       at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]       at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]       at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]       at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### How to Reproduce?

No reproducer yet.

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.6.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by mschorsch** [comment]
@radcortez Do you have any idea?

**Comment by famod** [comment]
Thanks for reporting.
Duplicates #37690.
3.6.3 with a fix is already on its way!
