### ISSUE TITLE
Quarkus qute with error "AccessDeniedException:" /qute-i18n-examples , when using re-build and re-arg

### ISSUE THREAD

**Issue by mrgurgel** [quarkusio/quarkus#37783]
### Describe the bug

I'm facing the following exception when using Qute extension when building with ` -Dquarkus.package.type=mutable-jar` and runing with `-Dquarkus.launch.rebuild=true -Dquarkus.datasource.db-kind=${QUARKUS_DATASOURCE_DB_KIND} `

### Expected behavior

The app should start without errors.

### Actual behavior

The following exception is being printed:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:89)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.qute.deployment.MessageBundleProcessor#generateExamplePropertiesFiles threw an exception: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /qute-i18n-examples
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.AccessDeniedException: /qute-i18n-examples
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
        at java.base/java.nio.file.Files.createDirectory(Files.java:699)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        at java.base/java.nio.file.Files.createDirectories(Files.java:793)
        at io.quarkus.qute.deployment.MessageBundleProcessor.generateExamplePropertiesFiles(MessageBundleProcessor.java:645)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        ... 6 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:334)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
        at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 4 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.qute.deployment.MessageBundleProcessor#generateExamplePropertiesFiles threw an exception: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /qute-i18n-examples
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.AccessDeniedException: /qute-i18n-examples
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
        at java.base/java.nio.file.Files.createDirectory(Files.java:699)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        at java.base/java.nio.file.Files.createDirectories(Files.java:793)
        at io.quarkus.qute.deployment.MessageBundleProcessor.generateExamplePropertiesFiles(MessageBundleProcessor.java:645)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        ... 6 more

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
        ... 7 more
Caused by: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /qute-i18n-examples
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.AccessDeniedException: /qute-i18n-examples
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
        at java.base/java.nio.file.Files.createDirectory(Files.java:699)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        at java.base/java.nio.file.Files.createDirectories(Files.java:793)
        at io.quarkus.qute.deployment.MessageBundleProcessor.generateExamplePropertiesFiles(MessageBundleProcessor.java:645)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        ... 6 more
        ```

### How to Reproduce?

1. Have a Quarkus app which uses Qute extension;
2. Compile this app as follows: mvn clean package -Dquarkus.package.type=mutable-jar
3. In the Dockerfile, start the quarkus app with the following paramters: -Dquarkus.launch.rebuild=true -Dquarkus.datasource.db-kind=${QUARKUS_DATASOURCE_DB_KIND} 

### Output of `uname -a` or `ver`

Linux (suppressed) 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 / OpenJDK Runtime Environment (build 21.0.1+12-29) / OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)

### Quarkus version or git rev

3.6.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)

### Additional information

I also had the same behaviour with 3.5.x version and also with 3.6.3 .
When removing the parameters `-Dquarkus.package.type=mutable-jar`, and `-Dquarkus.launch.rebuild=true` the app starts properly.

**Comment by mkouba** [comment]
@mrgurgel Hm, I don't think the problem is caused by the mutable-jar itself but the fact that your re-augment your app in a docker container. At least I wasn't able to reproduce the issue when running re-augmentation locally.

We could skip generation of the qute message bundle example file but I think that quarkus will need to write to the output directory anyway.

**Comment by mrgurgel** [comment]
> @mrgurgel Hm, I don't think the problem is caused by the mutable-jar itself but the fact that your re-augment your app in a docker container. At least I wasn't able to reproduce the issue when running re-augmentation locally.
> 
> We could skip generation of the qute message bundle example file but I think that quarkus will need to write to the output directory anyway.

@mkouba , I was abble to solve (work around?) it by creating the  `/qute-i18n-examples`  inside the Dockerfile.
If there's a better way to deal with it, I will be glad to hear about.

Thanks for your support!

**Comment by mkouba** [comment]
> > @mrgurgel Hm, I don't think the problem is caused by the mutable-jar itself but the fact that your re-augment your app in a docker container. At least I wasn't able to reproduce the issue when running re-augmentation locally.
> > We could skip generation of the qute message bundle example file but I think that quarkus will need to write to the output directory anyway.
> 
> @mkouba , I was abble to solve (work around?) it by creating the `/qute-i18n-examples` inside the Dockerfile. If there's a better way to deal with it, I will be glad to hear about.
> 
> Thanks for your support!

Glad to hear that you found a workaround.

I have no idea if there's a generic solution though.

In any case, I will modify qute to create the `/qute-i18n-examples` directory only if message bundles are used.

**Comment by mkouba** [comment]
For the record, since 3.7 the `/qute-i18n-examples` directory is not be created unless the qute message bundles are used.
