### ISSUE TITLE
[Quarkus main] integration test 'main' fails in native mode: QuarkusTestCallbacksITCase.testCallbackContextIsNotFailed

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#37809]
### Describe the bug

We see this failure with various Mandrel versions. 23.1, 22.3 and Graal master:

```
Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.015 s <<< FAILURE! -- in io.quarkus.it.main.QuarkusTestCallbacksITCase
Error:  io.quarkus.it.main.QuarkusTestCallbacksITCase.testCallbackContextIsNotFailed -- Time elapsed: 0.003 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:31)
	at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:231)
	at io.quarkus.it.main.QuarkusTestCallbacksITCase.testCallbackContextIsNotFailed(QuarkusTestCallbacksITCase.java:61)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

22.3 failure: https://github.com/graalvm/mandrel/actions/runs/7247202176/job/19741555739?pr=638#step:12:651
23.1 failure: https://github.com/graalvm/mandrel/actions/runs/7228893522/job/19699470818#step:12:706
Graal master failure: https://github.com/graalvm/mandrel/actions/runs/7242468774/job/19728465877#step:12:688

**Comment by zakkak** [comment]
I will have a look and try to understand why it's not happening with the published mandrel 23.1 builder image but still shows up in our CI when testing 23.1 source builds.

**Comment by zakkak** [comment]
@geoand is there a good reason Quarkus is keeping failures from previous tests in the extension context? I guess the callback test is only interested in failures caused in its test class, no?

**Comment by geoand** [comment]
> I guess the callback test is only interested in failures caused in its test class, no?

exactly
