### ISSUE TITLE
DevMode for Oracle can not be started on the latest RHEL 8 with podman

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#38003]
### Describe the bug

I have a RHEL8 machine, which uses podman as a container runtime. After the update (including updating podman from  4.4.1 to 4.6.1), dev mode for Oracle can not be started and fails with an exception.

### Expected behavior

Dev mode starts

### Actual behavior

```
(build-45) Could not start container: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"cause":"OCI runtime error","message":"runc: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: cannot set cpu limit: container could not join or create cgroup: OCI runtime error","response":500}ocessor.launchDatabases(DevServicesDatasourceProcessor.java:142)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.inat org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)	at java.base/jdk.internal.reflect.DelegatingMat org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102):566)	at io.quarkus.deployment.ExtensionLoaat org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31).threads.ContextHandler$1.runWith(Context	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)enzl/oracle-free:23-slim-faststart] (build	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:42)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:455)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:357)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:347)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:333)
	at io.quarkus.devservices.oracle.deployment.OracleDevServicesProcessor$1.startDatabase(OracleDevServicesProcessor.java:78)
	at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:282)
	at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.launchDatabases(DevServicesDatasourceProcessor.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExec
```

### How to Reproduce?

1. `wget -O quarkus.zip 'https://code.quarkus.io/d?j=11&e=jdbc-oracle&e=hibernate-orm-rest-data-panache&e=resteasy-reactive-jackson&cn=code.quarkus.io'`
2. `unzip -q quarkus.zip`
3. `cd code-with-quarkus/`
4. `mvn quarkus:dev`

### Output of `uname -a` or `ver`

4.18.0-513.9.1.el8_9.x86_64

### Output of `java -version`

11.0.21, vendor: Red Hat, Inc.

### Quarkus version or git rev

 3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

My speculations below:

For Oracle containers, Quarkus explicitly sets a limit of 2 CPUs[1]. At the same time, podman 4.6.1 can not handle limits on hosts with cgroups v1[2]. Since containerised oracledb now handles cpu parameters on its own[3], maybe Quarkus should not set them itself?

[1] https://github.com/quarkusio/quarkus/pull/25009/files
[2] https://github.com/containers/podman/issues/21139
[3] https://github.com/gvenzl/oci-oracle-xe/issues/64

**Comment by gsmet** [comment]
Maybe try to override `getEnv` in `QuarkusOracleServerContainer` and set `CPU_COUNT` to `2` and see how it goes?

**Comment by fedinskiy** [comment]
@gsmet such change[1] solves this problem, but I do not know, whether it will make https://github.com/quarkusio/quarkus/issues/24939 resurface again (I do not have a 128-core machine to verify it.)

[1] https://github.com/fedinskiy/quarkus/commit/7a8aad1d1082d9c3f8876088172e963bd34f71ab

**Comment by melloware** [comment]
I wonder if we should update from gvenzel/oraclexe image to the newer and more supported gvenzel/oraclefree image.   It also has a faststart-slim image which is much smaller than the current XE image from 1 GB down to 300MB.

**Comment by michalvavrik** [comment]
I can confirm that it works with Podman on my laptop.
