### ISSUE TITLE
Bytebuddy exception when request on a native packege

### ISSUE THREAD

**Issue by shenbinglife** [quarkusio/quarkus#38053]
### Describe the bug
Intercept methods of a Object using bytebuddy. It's ok on java -jar quarkus-run.jar , but failed on native package when HTTP request.

## ERROR log: 
```
 ERROR [org.acm.com.web.ExceptionHandler] (executor-thread-1) Handling server request exception: java.lang.IllegalStateException: size = 0
        at net.bytebuddy.matcher.FilterableList$AbstractBase.getOnly(FilterableList.java:139)                                                                    
        at net.bytebuddy.implementation.InvocationHandlerAdapter.apply(InvocationHandlerAdapter.java:255)                                                        
        at net.bytebuddy.implementation.InvocationHandlerAdapter$ForInstance$Appender.apply(InvocationHandlerAdapter.java:404)                                   
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:730)                                  
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:715)                                  
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:622)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:6043)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2224)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4055)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3739)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3991)
        at org.acme.common.orm.SqlBuilder.enforce(SqlBuilder.kt:73)
        at org.acme.common.orm.SqlBuilder.<init>(SqlBuilder.kt:41)
        at org.acme.common.orm.SqlBuilder.<init>(SqlBuilder.kt:31)
        at org.acme.service.system.MenuService.buildQuery(MenuService.kt:31)
        at org.acme.service.system.MenuService.page(MenuService.kt:19)
        at org.acme.service.system.MenuService_ClientProxy.page(Unknown Source)
        at org.acme.controller.system.MenuController.page(MenuController.kt:21)
        at org.acme.controller.system.MenuController$quarkusrestinvoker$page_437cf267b6e230f6794eba46dc3136970caca206.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:210)

```

## The reason using bytebuddy
I want to a SqlBuilder like this:

```kotlin
private fun buildQuery(menu: SysMenu): Triple<String, Sort, Parameters> {
        val builder = SqlBuilder(menu)
        builder.like(SysMenu::title)
            .like(SysMenu::path)
            .like(SysMenu::component)
            .eq(SysMenu::isHide)
        println(builder.sql())
        println(builder.params.map())

        return Triple(builder.sql(), SysMenu.SORT_NUM_DESC, builder.params)

    }
```

The SqlBuilder instance proxy the `menu` object as query condition to generate Hibernate QL,

when a SysMenu method lambda called, like `.eq(SysMenu::isHide)` , will append string ` and isHide=:isHide` to hql, and set the value of isHide field from `menu` object to Paramters.

## This is my SqlBuilder source code: 

```kotlin
package org.acme.common.orm

import io.quarkus.panache.common.Parameters
import net.bytebuddy.ByteBuddy
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy
import net.bytebuddy.implementation.InvocationHandlerAdapter
import net.bytebuddy.matcher.ElementMatchers
import org.acme.entity.system.SysMenu
import org.hibernate.boot.model.naming.Identifier
import org.hibernate.boot.model.naming.PhysicalNamingStrategy
import org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
import java.beans.BeanInfo
import java.beans.Introspector
import java.lang.reflect.InvocationHandler
import java.lang.reflect.Method

class FieldInterceptor<T>(val builder: SqlBuilder<T>) : InvocationHandler {
    override fun invoke(proxy: Any, method: Method, args: Array<out Any>?): Any? {

        val value = method.invoke(builder.origin)
        if (value != null) {
            builder.columnName = builder.methodToField[method.name]
                ?: throw Exception("Can not find column by getter method: ${method.name}")
        }

        return value
    }

}

class SqlBuilder<T>(val origin: T & Any,  val strategy: PhysicalNamingStrategy = PhysicalNamingStrategyStandardImpl()) {



    val builder = StringBuilder(" 1=1 ")

    fun sql() = builder.toString()

    val params = Parameters()

    val wrapper: T = enforce()

    var columnName: String = "bad"

    val methodToField: Map<String, String> = methodMapping()

    private fun methodMapping(): Map<String, String> {
        val map = mutableMapOf<String, String>()


        val cls = origin::class.java
        val info: BeanInfo = Introspector.getBeanInfo(cls)
        for (propertyDescriptor in info.propertyDescriptors) {
            val propertyName = propertyDescriptor.name
            propertyDescriptor.readMethod?.let {
                map[it.name] = strategy.toPhysicalColumnName(Identifier.toIdentifier(propertyName), null).text
            } ?: let {
                val trickName = "is" + propertyName.first().uppercase() + propertyName.takeLast(propertyName.length - 1)
                val methodName = cls.getDeclaredMethod(trickName).name
                map[methodName] = strategy.toPhysicalColumnName(Identifier.toIdentifier(trickName), null).text
            }

        }
        println(map)
        return map
    }

    fun enforce(): T {
        return ByteBuddy()
            .subclass(origin::class.java)
            .method(ElementMatchers.not(ElementMatchers.isDeclaredBy(Object::class.java)))
            .intercept(InvocationHandlerAdapter.of(FieldInterceptor<T>(this)))
            .make()
            .load(FieldInterceptor::class.java.classLoader, ClassLoadingStrategy.Default.WRAPPER)
            .loaded
            .declaredConstructors
            .first()
            .newInstance() as T

    }


    fun lt(call: (T) -> Any?): SqlBuilder<T> {
        val value = call(wrapper)

        if (value != null) {
            params.and(columnName, value)
            builder.append(" and $columnName < :$columnName")
        }
        return this
    }

    fun gt(call: (T) -> Any?): SqlBuilder<T> {
        val value = call(wrapper)

        if (value != null) {
            params.and(columnName, value)
            builder.append(" and $columnName > :$columnName")
        }
        return this
    }

    fun le(call: (T) -> Any?): SqlBuilder<T> {
        val value = call(wrapper)

        if (value != null) {
            params.and(columnName, value)
            builder.append(" and $columnName <= :$columnName")
        }
        return this
    }

    fun ge(call: (T) -> Any?): SqlBuilder<T> {
        val value = call(wrapper)

        if (value != null) {
            params.and(columnName, value)
            builder.append(" and $columnName >= :$columnName")
        }
        return this
    }

    fun eq(call: (T) -> Any?): SqlBuilder<T> {
        val value = call(wrapper)

        if (value != null) {
            params.and(columnName, value)
            builder.append(" and $columnName = :$columnName")
        }
        return this
    }

    fun isNull(call: (T) -> Any?): SqlBuilder<T> {
        val value = call(wrapper)
        builder.append(" and $columnName is NULL")
        return this
    }

    fun notNull(call: (T) -> Any?): SqlBuilder<T> {
        val value = call(wrapper)
        builder.append(" and $columnName is NOT NULL")
        return this
    }

    fun inList(call: (T) -> Any?, list: List<Any>): SqlBuilder<T> {
        val value = call(wrapper)

        params.and(columnName, list)
        builder.append(" and $columnName in :$columnName")
        return this
    }

    fun like(call: (T) -> Any?): SqlBuilder<T> {
        val value = call(wrapper)

        if (value != null) {
            params.and(columnName, "%${value}%")
            builder.append(" and $columnName like :$columnName")
        }
        return this
    }
}

fun main() {

    val menu = SysMenu()
    menu.isFull = true
    menu.isLink = "asdf"
    menu.isHide = false
    menu.title = "adsf"

    val builder = SqlBuilder(menu).lt(SysMenu::sortNum).lt(SysMenu::isHide).lt(SysMenu::isFull).lt(SysMenu::title)
        .lt(SysMenu::isLink)
    print(builder.params.map())
}

```

### Expected behavior

ByteBuddy success on native package.

### How to Reproduce?

Using bytebuddy intercept a object at runtime 

### Output of `java -version`

17

### Quarkus version or git rev

3.6.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

### Additional information

GraalVM 21.0.1+12.1

 ------------------------------------------------------------ Gradle 8.5 ------------------------------------------------------------ 
 Build time:   2023-11-29 14:08:57 UTC 
Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598  
Kotlin:       1.9.20 
Groovy:       3.0.17 
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 
JVM:          17.0.4.1 (Oracle Corporation 17.0.4.1+1-LTS-2) OS:          
 Windows 10 10.0 amd64

**Comment by geoand** [comment]
Bytebuddy does not work in native-mode as it has to redefine a class (or generate a new one), both of which are not possible in native-mode.
