### ISSUE TITLE
Change in behavior after SmallRye Config update to 3.5.1

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#38052]
### Describe the bug

We have noticed change in behavior after SmallRye Config update to 3.5.1 in https://github.com/quarkusio/quarkus/pull/37794.

We have testing application which is using `quarkus.stork.pong-replica.load-balancer=round-robin` property which was valid ~Quarkus 2.7, later it was replaced by `quarkus.stork.pong.load-balancer.type`.

Till now the app worked fine because roun-robin is the default load-balancer type, there was just warning about unrecognized property.

After SmallRye Config update to 3.5.1 there is error when booting the app.

On one side it's good that users are forced to update the config, but on the other hand I miss any information in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7 about the changes around config.

Also raising this issue as @radcortez's comment https://github.com/quarkusio/quarkus/pull/37794#issuecomment-1876083176 indicated he would like to know about the side-effects of this SmallRye Config change.

Stacktrace:
```
WARN: Unrecognized configuration key "quarkus.stork.pong-replica.load-balancer" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
Configuration validation failed:
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "round-robin")
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Failed to read configuration properties
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	... 13 more
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "round-robin")
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:73)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:86)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:720)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
```

### Expected behavior

Application starts just with warning about unrecognized property

### Actual behavior

After SmallRye Config update to 3.5.1 there is error when booting the app.

I think it's connected with `@WithParentName` usage in https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-stork/runtime/src/main/java/io/quarkus/stork/StorkLoadBalancerConfiguration.java#L25

### How to Reproduce?

```
quarkus create app app -P io.quarkus::999-SNAPSHOT --extensions=stork,resteasy-reactive
cd app
mvn clean package -Dquarkus.stork.pong-replica.service-discovery.type=consul -Dquarkus.stork.pong-replica.load-balancer=round-robin
```

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 17

### Quarkus version or git rev

5fcc268ce44

**Comment by gsmet** [comment]
I don't think it's a behavior we want. It looks like a bug.

**Comment by radcortez** [comment]
I'll have a look.

**Comment by radcortez** [comment]
I believe this is working as expected now.

Notice that the property that must be used is `quarkus.stork.pong-replica.load-balancer.[param-key]`, where `[param-key]` is missing in the declaration. The `@WithParentName` shortens the Map `parameters` name, but you still need to add a key to add values into the Map.

The old implementation simply ignored such declarations, so `quarkus.stork.pong-replica.load-balancer=round-robin` has no effect at all. The new implementation allows you to inline the entire `Map` content as `<key1>=<value1>;<key2>=<value2>`, hence the error message.

**Comment by radcortez** [comment]
> * [Update SmallRye Config to 3.5.1 #37794](https://github.com/quarkusio/quarkus/pull/37794) should be marked as noteworthy so it gets mentioned in the blog post for 3.7 release

I've marked the issue as noteworthy now :)

> * https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7 could have a note about SRye update and `quarkus.stork.pong-replica.load-balancer` case for users convenience

I'm unsure about `quarkus.stork.pong-replica.load-balancer`. It may have been a valid property some time ago, but currently (even without this PR), it is completely ignored. I was looking for stork properties in 2.7 and couldn't find it. In 2.13, it already uses the new property.

**Comment by rsvoboda** [comment]
https://quarkus.io/version/2.7/guides/stork#stork-configuration
