### ISSUE TITLE
java.sql.SQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"

### ISSUE THREAD

**Issue by cjbi** [quarkusio/quarkus#38090]
### Describe the bug

I used hikariCP in my project, and after running the project for a while, I received the error "Data source rejected establishment of connection, message from server: 'Too many connections'". Here is the detailed error:
```posh
Caused by: java.sql.SQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	... 1 more
```

Why is this happening?

### Output of `uname -a` or `ver`

OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

### Output of `java -version`

21

### Quarkus version or git rev

3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5

**Comment by cjbi** [comment]
I just checked and found that when quarku.datasource.jdbc.flush-on-close=true, the maximum connection config invalid. Is this a bug?

**Comment by yrodiere** [comment]
This generally indicates a connection leak, which could come from a number of reasons, either in your application or, indeed, a bug in Quarkus.

However, this is not detailed enough for us to help. Can you please provide a reproducer? A small application, perhaps a stripped-down version of yours, which, after being sent requests for a while, exhibits this error?

> I just checked and found that when quarku.datasource.jdbc.flush-on-close=true, the maximum connection config invalid.

I'm sorry, I don't understand what you mean. Could you be more specific?
