### ISSUE TITLE
Kotlin project fails to include JAXP classes provided by JDK

### ISSUE THREAD

**Issue by boonyasukd** [quarkusio/quarkus#3813]
**Describe the bug**
I'm creating [a project](https://github.com/boonyasukd/buggy-kotlin-native) in Kotlin that requires the use of `JAXP` included as part of Java 8. However, when I built an executable, ran it, and made a REST call to `http://localhost:8080/hello`, I got an error saying that it cannot find resource bundle class `com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages`:

```
ERROR [io.und.req.io] (executor-thread-1) Exception handling request 80ebdbef-17ae-4295-a7d0-1f4ef6897987-1 to /hello: org.jboss.resteasy.spi.UnhandledException: org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : Could not load any resource bundle by com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
	at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.sendError(ResteasyFilter.java:64)
	at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:175)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:28)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$8$1$1.call(UndertowDeploymentRecorder.java:489)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : Could not load any resource bundle by com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:558)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1488)
	at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:242)
	at com.acme.serverless.run.InvoicesResource.hello(InvoicesResource.kt:23)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:110)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:580)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:454)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:410)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:379)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:353)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:353)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
	... 51 more
Caused by: java.util.MissingResourceException: Could not load any resource bundle by com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages
	at com.sun.org.apache.xalan.internal.utils.SecuritySupport$8.run(SecuritySupport.java:182)
	at com.sun.org.apache.xalan.internal.utils.SecuritySupport$8.run(SecuritySupport.java:174)
	at java.security.AccessController.doPrivileged(AccessController.java:69)
	at com.sun.org.apache.xalan.internal.utils.SecuritySupport.getResourceBundle(SecuritySupport.java:174)
	at com.sun.org.apache.xalan.internal.utils.SecuritySupport.getResourceBundle(SecuritySupport.java:164)
	at com.sun.org.apache.xml.internal.serializer.utils.Messages.createMessage(Messages.java:153)
	at com.sun.org.apache.xml.internal.serializer.OutputPropertiesFactory.getDefaultMethodProperties(OutputPropertiesFactory.java:346)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.setDefaults(TransformerImpl.java:1132)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.createOutputProperties(TransformerImpl.java:1092)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.<init>(TransformerImpl.java:254)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.<init>(TransformerImpl.java:245)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:735)
	at org.apache.poi.openxml4j.opc.StreamHelper.getIdentityTransformer(StreamHelper.java:45)
	at org.apache.poi.openxml4j.opc.StreamHelper.saveXmlInStream(StreamHelper.java:61)
	at org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager.saveImpl(ZipContentTypeManager.java:69)
	at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.save(ContentTypeManager.java:452)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:524)
	... 74 more
```

**Expected behavior**
I expect JAXP classes (provided in JDK 8) to be included into the executable.

**Actual behavior**
The classes weren't properly included into an executable. An attempt to remedy this by adding `com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages` and `com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages_en` into `reflect-config.json` doesn't work. The executable still couldn't find the classes.

However, if I include a separate dependency [`jaxp-ri` in `pom.xml`](https://github.com/boonyasukd/buggy-kotlin-native/blob/master/pom.xml#L83-L87), the problem goes away. But this is undesirable since the JAXP used is a bit dated (version 1.4 vs 1.6 provided in JDK 8).

**To Reproduce**
1. Clone the [example project](https://github.com/boonyasukd/buggy-kotlin-native)
2. Run `mvn package -Pnative`
3. Run the executable, and cURL at `http://localhost:8080/hello`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Darwin boonybook.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```
 - Output of `java -version`: 
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-20190711112007.graal.jdk8u-src-tar-gz-b08)
OpenJDK 64-Bit GraalVM CE 19.2.0 (build 25.222-b08-jvmci-19.2-b02, mixed mode)
```
 - Quarkus version or git rev: `0.20.0`
 - Maven
```
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T02:00:29+07:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 1.8.0_222, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-19.2.0/Contents/Home/jre
Default locale: en_TH, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```
**Additional context**
I created another similar project in Java to replicate the issue. Surprisingly, this time around an executable actually works without crashing.

**Comment by gsmet** [comment]
There's a good chance we would need a JAXP extension.

**Comment by gsmet** [comment]
@fmhwong this one might be of interest too. It's the second time we have complaints about JAXP in native. We already have a JAXB extension but we might need a JAXP one.

**Comment by boonyasukd** [comment]
@gsmet 
Just to give you all a bit more information, there seems to be a problem with `graalvm` itself not picking up JDK resources even when `native-image` is properly configured, and there are currently multiple ongoing issues related to this in graalvm's github. This problem seems to affect people using micronaut as well.

- [my graalvm issue (stalled)](https://github.com/oracle/graal/issues/1648)
- [a (more recent and) active graalvm issue](https://github.com/oracle/graal/issues/1993)

**Comment by fmhwong** [comment]
@boonyasukd Your issue https://github.com/oracle/graal/issues/1648 has just been fixed on Jan 29, 2020.  Can you retry your test case when the fix is available in a new release of GraalVM?

**Comment by boonyasukd** [comment]
@fmhwong Sure can. Once the fix is part of the official release I'll be testing it and get back to this issue.

**Comment by boonyasukd** [comment]
@fmhwong The new version of `graalvm` is out. I've compiled my code with
- `ubi-quarkus-native-image:20.0.0-java8`
- `ubi-quarkus-native-image:20.0.0-java11`

Now my code runs just fine. I no longer need to recreate missing resource file to prevent it from crashing.

**Comment by fmhwong** [comment]
@boonyasukd Can this issue be closed?

**Comment by boonyasukd** [comment]
Yes, I'll close it now.
