### ISSUE TITLE
io.quarkus.runtime.BlockingOperationNotAllowedException: You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.

### ISSUE THREAD

**Issue by shenbinglife** [quarkusio/quarkus#38158]
### Describe the bug

Failed call orm operation in ContainerRequestFilter, what's the best practice to validate token using orm before request handled?

## source code 
```kotlin

@PreMatching
@Priority(Priorities.HEADER_DECORATOR + 50)
@Provider
class TokenFilter : ContainerRequestFilter {

    @Inject
    lateinit var tokenService: TokenService

    @Inject
    lateinit var userService: SysUserService

    val AUTHORIZATION_HEADER: String = "Authorization"
    val BEARER: String = "Bearer"

    /**
     * 允许匿名访问的路径
     */
    val anonymous_uris = arrayOf("/login")


    override fun filter(requestContext: ContainerRequestContext) {
        val path = requestContext.uriInfo.path
        if (anonymous_uris.contains(path)) {

        } else {
            val principal = requestContext.securityContext.userPrincipal as JsonWebToken
            userService.validate(principal)  // this is ORM operation to validate user status, but throw exception
        }
    }
}

```

## log
```
2024-01-12 20:32:30,566 ERROR [org.sbl.gee.con.web.ExceptionHandler] (vert.x-eventloop-thread-1) Handling server request exception: io.quarkus.runtime.BlockingOperationNotAllowedException: You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.checkBlocking(TransactionScopedSession.java:116)
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.createQuery(TransactionScopedSession.java:364)
	at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:548)
	at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:66)
	at org.hibernate.Session_OpdLahisOZ9nWRPXMsEFQmQU03A_Synthetic_ClientProxy.createQuery(Unknown Source)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createBaseQuery(CommonPanacheQueryImpl.java:366)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createQuery(CommonPanacheQueryImpl.java:344)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.firstResult(CommonPanacheQueryImpl.java:293)
	at io.quarkus.hibernate.orm.panache.kotlin.runtime.PanacheQueryImpl.firstResult(PanacheQueryImpl.kt:123)
	at org.sbl.geeker.modules.system.repository.SysUserRepository.findByUsername(SysUserRepository.kt:79)
	at org.sbl.geeker.modules.system.repository.SysUserRepository_ClientProxy.findByUsername(Unknown Source)
	at org.sbl.geeker.modules.system.service.SysUserService.validate(SysUserService.kt:109)
	at org.sbl.geeker.modules.system.service.SysUserService_ClientProxy.validate(Unknown Source)
	at org.sbl.geeker.config.security.TokenFilter.filter(TokenFilter.kt:42)
	at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:48)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:131)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:102)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:88)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:290)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Output of `java -version`

17

### Quarkus version or git rev

3.6.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

**Comment by geoand** [comment]
You can add `@Blocking` to `TokenFilter`

**Comment by shenbinglife** [comment]
> You can add `@Blocking` to `TokenFilter`

```
@Blocking
@PreMatching
@Priority(Priorities.HEADER_DECORATOR + 50)
@Provider
class TokenFilter : ContainerRequestFilter {}
```

But I Still get the error 
```
 Handling server request exception: io.quarkus.runtime.BlockingOperationNotAllowedException: You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.
```

**Comment by damgel** [comment]
Have you tried annotating @Blocking your services as well?

**Comment by geoand** [comment]
Closing for lack of feedback
