### ISSUE TITLE
Support Kotlin data classes for describing type-safe Qute templates

### ISSUE THREAD

**Issue by mthmulders** [quarkusio/quarkus#38194]
### It would be great if we could use a Kotlin data class to describe a type-safe Qute template.

Originally posted as a [question on StackOverflow](https://stackoverflow.com/questions/77816595/type-safe-qute-template-with-kotlin-data-classes), here's the full story.

I'm feeding paginated data into a Qute template. The data is of type `Paginated<out T>`, where `Paginated` adds information about total page count, current page, etc.

The [documentation](https://quarkus.io/guides/qute-reference#typesafe_templates) says you can let your controller return

> a Java record that implements io.quarkus.qute.TemplateInstance

And I was hoping that I could do the same thing with a Kotlin data class. I prefer that over invoking an `@JvmStatic external fun` method since the latter is a lot harder to write unit tests for.

I'd like to have my controller methods return instances of that data class:

```kotlin
@GET @Path("/list") @Produces(MediaType.TEXT_HTML)
fun list(@QueryParam("pageIndex") pageIndex: Int = 0): TemplateInstance {
  // work your magic
  return ExampleListTemplate(
    Paginated(
      currentPage = 0,
      pageCount = 1,
      items = listOf("example")
    )
  )
}

@CheckedTemplate(basePath = "example")
data class ExampleListTemplate(val data: Paginated<String>): TemplateInstance
```

### Implementation ideas

Current behaviour is that if you request such a page, you'll get a stacktrace:

```
Caused by: java.lang.UnsupportedOperationException
    at io.quarkus.qute.TemplateInstance.getTemplate(TemplateInstance.java:142)
    at io.quarkus.resteasy.qute.runtime.TemplateResponseFilter.filter(TemplateResponseFilter.java:45)
```

This is because the data class doesn't override the `getAttribute` (default) method from the `TemplateInstance` interface.

This is where I get a little bit lost. If I followed the Java record approach, my record wouldn't override that default method either, but it would work nevertheless. I guess that by studying how it works for Java records, it might be possible to find a solution direction for Kotlin data classes, but I didn't walk that far (yet).

**Comment by bulldog98** [comment]
As a workaround, have you tried annotating your data class with `@JvmRecord`? That should make the bytecode for the class a java record.

**Comment by mthmulders** [comment]
> As a workaround, have you tried annotating your data class with `@JvmRecord`? That should make the bytecode for the class a java record.

I didn't know about `@JvmRecord`, but now I do - and it turns out that adding it is enough for Quarkus to recognise the Kotlin data class as a valid template instance. Works like a charm!

**Comment by bulldog98** [comment]
I still think it would be nice to accept a data class as part of kotlin integration (or at least mention `@JvmRecord` in the docs.

**Comment by geoand** [comment]
Yeah, I think the request makes sense. @mkouba WDYT?

**Comment by mkouba** [comment]
I would start with a note about the `@JvmRecord` in the [docs](https://quarkus.io/guides/qute-reference#typesafe_templates).

And as usual, PRs are welcome! ;-)

**Comment by geoand** [comment]
> I would start with a note about the @JvmRecord in the [docs](https://quarkus.io/guides/qute-reference#typesafe_templates).

Yeah, definitely

**Comment by geoand** [comment]
> And as usual, PRs are welcome! ;-)

I would help would-be contributors if you pointed to the PR where the initial support for Java Records was added 😉

**Comment by mkouba** [comment]
> > And as usual, PRs are welcome! ;-)
> 
> I would help would-be contributors if you pointed to the PR where the initial support for Java Records was added 😉

For sure. So in my previous comment there's a link to the docs where the note about `@JvmRecord` should go. And for the brave ones this is the PR where records support was added: https://github.com/quarkusio/quarkus/pull/34696.

**Comment by geoand** [comment]
I should note that the best starting place for looking into that change is probably `io.quarkus.qute.deployment.TemplateRecordEnhancer`
