### ISSUE TITLE
Current request NPE with micrometer-registry-prometheus

### ISSUE THREAD

**Issue by UbiquitousBear** [quarkusio/quarkus#38205]
### Describe the bug

After installing `micrometer-registry-prometheus`, I am receiving an error after every HTTP request. The HTTP request itself is successful.

Added dependency:

```
root@2d440fb8440b:/workspace# mvn dependency:tree | grep prometheus
[INFO] +- io.quarkus:quarkus-micrometer-registry-prometheus:jar:3.6.5:compile
[INFO] |  \- io.micrometer:micrometer-registry-prometheus:jar:1.11.5:compile
[INFO] |     \- io.prometheus:simpleclient_common:jar:0.16.0:compile
[INFO] |        \- io.prometheus:simpleclient:jar:0.16.0:compile
[INFO] |           +- io.prometheus:simpleclient_tracer_otel:jar:0.16.0:compile
[INFO] |           |  \- io.prometheus:simpleclient_tracer_common:jar:0.16.0:compile
[INFO] |           \- io.prometheus:simpleclient_tracer_otel_agent:jar:0.16.0:compile
```

### Expected behavior

No errors to be produced related to fetching the current request

### Actual behavior

An error is produced after every HTTP request.

Stack Trace:

```
2024-01-15 20:57:32,871 ERROR [io.und.req.io] (executor-thread-1) Exception handling request f41345e2-38cd-4ed5-93c9-5268b2b14be4-5 to /connect/AuthenticationApi/getRegisteredProviders: jakarta.enterprise.inject.IllegalProductException: Normal scoped producer method may not return null: io.quarkus.vertx.http.runtime.CurrentVertxRequest.getCurrent()
        at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_bcI9FtU7pcNOHntvVCkP17muvXY_Bean.doCreate(Unknown Source)
        at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_bcI9FtU7pcNOHntvVCkP17muvXY_Bean.create(Unknown Source)
        at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ProducerMethod_getCurrent_bcI9FtU7pcNOHntvVCkP17muvXY_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.RequestContext$1.get(RequestContext.java:79)
        at io.quarkus.arc.impl.RequestContext$1.get(RequestContext.java:75)
        at io.quarkus.arc.generator.Default_jakarta_enterprise_context_RequestScoped_ContextInstances.c9(Unknown Source)
        at io.quarkus.arc.generator.Default_jakarta_enterprise_context_RequestScoped_ContextInstances.computeIfAbsent(Unknown Source)
        at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:75)
        at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:28)
        at io.vertx.ext.web.CurrentVertxRequest_ProducerMethod_getCurrent_bcI9FtU7pcNOHntvVCkP17muvXY_ClientProxy.arc$delegate(Unknown Source)
        at io.vertx.ext.web.CurrentVertxRequest_ProducerMethod_getCurrent_bcI9FtU7pcNOHntvVCkP17muvXY_ClientProxy.request(Unknown Source)
        at io.quarkus.micrometer.runtime.binder.vertx.HttpRequestMetric.getRequestMetric(HttpRequestMetric.java:100)
        at io.quarkus.micrometer.runtime.binder.vertx.VertxMeterBinderUndertowServletFilter.doFilter(VertxMeterBinderUndertowServletFilter.java:31)
        at jakarta.servlet.http.HttpFilter.doFilter(HttpFilter.java:97)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:626)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
        at io.undertow.server.handlers.CanonicalPathHandler.handleRequest(CanonicalPathHandler.java:49)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:125)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)
        at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$2.run(UndertowDeploymentRecorder.java:441)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Output of `uname -a` or `ver`

6.5.13-orbstack-00121-ge428743e4e98

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

3.6.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by geoand** [comment]
It would be extremely helpful if you could provide a sample application that exhibits the error described.

Thanks!

**Comment by cescoffier** [comment]
You are using the servlet API. I do not believe our metrics support has been tested in this case. Indeed, we do not have a current request set in this case.

Any reason to use servlets?

**Comment by UbiquitousBear** [comment]
> It would be extremely helpful if you could provide a sample application that exhibits the error described.
> 
> Thanks!

Trying to get one out :)

**Comment by UbiquitousBear** [comment]
> You are using the servlet API. I do not believe our metrics support has been tested in this case. Indeed, we do not have a current request set in this case.
> 
> Any reason to use servlets?

I'm using an extension which uses the Servlet API, so I guess that's where we should be fixing this? 
Servlet is configured here: https://github.com/mcollovati/quarkus-hilla/blob/0c8372e7f6f7148e95759c38a2aedd797bccc4d8/runtime-commons/src/main/java/com/github/mcollovati/quarkus/hilla/QuarkusEndpointController.java#L70

**Comment by geoand** [comment]
I'll have another look tomorrow

**Comment by geoand** [comment]
Hm... I actually can't figure out what's going solely from the stacktrace.

Please attach a sample project that reproduces the issue when you get a chance.

**Comment by geoand** [comment]
Closing for lack of feedback. 

If one becomes available, please attach it and I'll take another look
