### ISSUE TITLE
transitive @Transactional binding not supported by io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase

### ISSUE THREAD

**Issue by cghislai** [quarkusio/quarkus#38264]
### Describe the bug

With `@InterceptorBinding` annotations, like `@Transactional`, I should be able to declare others `@InterceptorBinding` that inherit the binding by transitivity. See https://jakarta.ee/specifications/interceptors/2.0/interceptors-spec-2.0#interceptor_binding_types_with_additional_interceptor_bindings.

However, if I define my own interceptor binding  like so:

```java
@Inherited
@InterceptorBinding
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Transactional
public @interface MyTransactionalBinding {
}
```

then it works for setting up the tranasction on the transaction boundary method, but if a nested call on another transactional bean that throws is annotated, this fails with an error " ARJUNA016107: Expected an @Transactional annotation at class and/or method level": 

```java
@ApplicationScoped
public class MyTransactionalBean {

    @Inject
    MyUnsafeTransactionalBean myUnsafeTransactionalBean;

    @MyTransactionalBinding
    public void test2() throws SystemException {
        Transaction transaction = tm.getTransaction();
        if (transaction == null) {
            throw new AssertionError("No tranasction");
        }

       try {
            myUnsafeTransactionalBean.test2();
            throw new AssertionError("nothing thrown");
        } catch (TransactionalSafeException e) {
        }
    }
}


@ApplicationScoped
public class MyUnsafeTransactionalBean {
    @MyTransactionalBinding
    public void test2() {
        throw new TransactionalSafeException("test");
    }
}
```

### Expected behavior

Using own interceptor bindings providing `@Tranasctional` works in all cases

### Actual behavior

Exception thrown at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase#getTransactional:

```java
    private Transactional getTransactional(InvocationContext ic) {
        Set<Annotation> bindings = InterceptorBindings.getInterceptorBindings(ic);
        for (Annotation i : bindings) {
            if (i.annotationType() == Transactional.class) {
                return (Transactional) i;
            }
        }
        throw new RuntimeException(jtaLogger.i18NLogger.get_expected_transactional_annotation());
    }
```

```
java.lang.RuntimeException: ARJUNA016107: Expected an @Transactional annotation at class and/or method level
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.getTransactional(TransactionalInterceptorBase.java:87)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.handleExceptionNoThrow(TransactionalInterceptorBase.java:359)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.handleException(TransactionalInterceptorBase.java:392)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:139)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
		at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
		at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
		at org.example.MyUnsafeTransactionalBean_Subclass.test2(Unknown Source)
		at org.example.MyUnsafeTransactionalBean_ClientProxy.test2(Unknown Source)
		at org.example.MyTransactionalBean.test4(MyTransactionalBean.java:49)
		at org.example.MyTransactionalBean_ClientProxy.test4(Unknown Source)
		at org.example.GreetingResource.hello(GreetingResource.java:36)
		at org.example.GreetingResource$quarkusrestinvoker$hello_2615aa2773bd5be3c69078450e792903e1eacee1.invoke(Unknown Source)
		at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
		at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
		at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
		at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
		at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
		at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
		at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
		at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

Running the quarkus test in the repo https://github.com/cghislai/cdi-interceptor-transitivity-test reproduces the issue

**Comment by Ladicek** [comment]
I've stumbled upon this problem recently -- we take transitive interceptor bindings into account during interceptor resolution, but we ignore them when generating `InterceptedMethodMetadata`, so they are not visible from the `InvocationContext`. I have a fix, will submit PR shortly.
