### ISSUE TITLE
Resteasy configuration defined in `application.properties` is ignored since the 3.0 version

### ISSUE THREAD

**Issue by lukasz-piekarski-smartlogic** [quarkusio/quarkus#38279]
### Describe the bug

Given a quarkus project (version 2.x) with resteasy and servlet features, defining a PATCH endpoint:
```
@PATCH
    @Consumes("application/merge-patch+json")
    @Produces(MediaType.APPLICATION_JSON)
    public String hello() {
        return "Hello from RESTEasy Reactive";
    }
```
with resteasy patchfilter disabled in `application.properties`
```
resteasy.patchfilter.disabled=true
```
invoking the endpoint yields the expected results:
```
$ curl -X PATCH http://localhost:8080/hello -H 'Content-Type: application/merge-patch+json'
Hello from RESTEasy Reactive
```
But after upgrading quarkus to 3.0
```
quarkus update --stream=3.0
```
The `resteasy.patchfilter.disabled=true` property is no longer respected and invoking the endpoint results in the following error
```
org.jboss.resteasy.spi.UnhandledException: jakarta.ws.rs.ProcessingException: GET method returns the patch/merge json object target not found    
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:357)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:205)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:452)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:222)
        at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:35)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:624)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:124)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)
        at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$2.run(UndertowDeploymentRecorder.java:439)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: jakarta.ws.rs.ProcessingException: GET method returns the patch/merge json object target not found
        at org.jboss.resteasy.plugins.providers.AbstractPatchMethodFilter.getMethodInvoker(AbstractPatchMethodFilter.java:163)
        at org.jboss.resteasy.plugins.providers.AbstractPatchMethodFilter.filter(AbstractPatchMethodFilter.java:101)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:276)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
        ... 47 more
```

### Expected behavior

`resteasy.patchfilter.disabled=true` should be respected

### Actual behavior

`resteasy.patchfilter.disabled=true` is ignored and the default patch filter from resteasy overlays the method from the project.

### How to Reproduce?

1. download the [demo.zip](https://github.com/quarkusio/quarkus/files/13977354/demo.zip) project
2. run `mvn quarkus:dev`
3. run `curl -X PATCH http://localhost:8080/hello -H 'Content-Type: application/merge-patch+json'` to see that everything works correctly for quarkus 2.16.12.Final
4. run `quarkus update --stream=3.0` to upgrade the project to quarkus 3.0
5. run `mvn quarkus:dev` and `curl -X PATCH http://localhost:8080/hello -H 'Content-Type: application/merge-patch+json'` again to see that now the exception appears

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-22621 RDLP 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys

### Output of `java -version`

openjdk version "11.0.18" 2023-01-17 LTS OpenJDK Runtime Environment Microsoft-7208460 (build 11.0.18+10-LTS) OpenJDK 64-Bit Server VM Microsoft-7208460 (build 11.0.18+10-LTS, mixed mode)

### Quarkus version or git rev

3.0.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0

**Comment by geoand** [comment]
RESTEasy Reactive does not support the feature in question

**Comment by geoand** [comment]
cc @jamezp

**Comment by jamezp** [comment]
Looks like a simple fix, see https://issues.redhat.com/browse/RESTEASY-3439.

As a workaround if you pass `-Dresteasy.patchfilter.disabled=true` as a system property it should work until the bug is fixed. For example:
```bash
mvn quarkus:dev -Djvm.args="-Dresteasy.patchfilter.disabled=true "
```

**Comment by geoand** [comment]
@jamezp any plans for 6.2.8.Final in the immediate future?

Thanks

**Comment by geoand** [comment]
No hurry, just wondering 😄

**Comment by geoand** [comment]
We now include version `6.2.8` of RESTEasy, so I am going to close this.
