### ISSUE TITLE
Not able to run quarkus-funqy-google-cloud-functions with CloudEvents and http trigger

### ISSUE THREAD

**Issue by kdubois** [quarkusio/quarkus#38302]
### Describe the bug

I am trying to deploy a Google Cloud Function using Funqy to process a Cloud Event via an http trigger, however when I try to deploy it, I get an error saying 
`Exception in thread "main" java.lang.RuntimeException: Class io.quarkus.funqy.gcp.functions.FunqyCloudEventsFunction does not implement com.google.cloud.functions.HttpFunction`

### Expected behavior

I expect the function to be deployed correctly

### Actual behavior

The deployment fails. When I look in the logs, I see 
`Exception in thread "main" java.lang.RuntimeException: Class io.quarkus.funqy.gcp.functions.FunqyCloudEventsFunction does not implement com.google.cloud.functions.HttpFunction
	at com.google.cloud.functions.invoker.HttpFunctionExecutor.forClass(HttpFunctionExecutor.java:48)
	at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:305)
	at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:244)
	at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:127)`

### How to Reproduce?

You should be able to reproduce using the example in this repository and deploying using the instructions in the README:
https://github.com/serverless-java-in-action/examples/tree/main/chapter4/quarkus-funqy-gcp-cloud-events

(Running it locally works fine, but when you deploy it should fail).

### Output of `java -version`

openjdk version "21" 2023-09-19 LTS OpenJDK Runtime Environment Temurin-21+35 (build 21+35-LTS) OpenJDK 64-Bit Server VM Temurin-21+35 (build 21+35-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.6.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8

**Comment by loicmathieu** [comment]
Hi,
In you reproducer you deploy the Cloud Event function with an HTTP target, that's why you have the error.
You need to trigger the function with a cloud event, for ex with a bucket event as documented here: https://quarkus.io/guides/funqy-gcp-functions#cloud-events-functions-cloud-storage

**Comment by loicmathieu** [comment]
As far as I know it's Google limitation.
Cloud events function are designed to be triggered by an event arc trigger: https://cloud.google.com/functions/docs/calling/eventarc

There is a way to manually trigger them via `gcloud functions call`.
