### ISSUE TITLE
Failed to redeploy verticle after quorum was re-attained

### ISSUE THREAD

**Issue by drse** [quarkusio/quarkus#38315]
### Describe the bug

Created a simple application, manually customized Vert.x instance to enable HA and quorum size 2, with a basic hazelcast TCP config. Deployed a simple HA worker verticle on startup. When launching the application, the deployed verticle is undeployed correctly because quorum is not yet attained. After launching another instance of the app, Vert.x redeploys the verticle, causing an `java.lang.NoSuchMethodException`.

### Expected behavior

Verticle is redeployed when quorum is reached.

### Actual behavior

```
Failed to redeploy verticle java:org.acme.HAVerticle_ClientProxy after quorum was re-attained: java.lang.InstantiationException: org.acme.HAVerticle_ClientProxy
        at java.base/java.lang.Class.newInstance(Class.java:719)
        at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:153)
        at io.vertx.core.impl.VerticleManager.lambda$doDeployVerticle$5(VerticleManager.java:222)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoSuchMethodException: org.acme.HAVerticle_ClientProxy.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3761)
        at java.base/java.lang.Class.newInstance(Class.java:706)
        ... 12 more
```

### How to Reproduce?

[quarkus-cluster.zip](https://github.com/quarkusio/quarkus/files/13996620/quarkus-cluster.zip)

```java
@ApplicationScoped
public class VertxCustomizer implements VertxOptionsCustomizer {
    @Override
    public void accept(VertxOptions options) {
        options.setHAEnabled(true);
        options.setHAGroup("test-group");
        options.setQuorumSize(2);
    }
}
```

```java
@ApplicationScoped
public class VerticleDeployer {
    public void init(
            @Observes StartupEvent e,
            Vertx vertx,
            HAVerticle verticle
    ) {
        Log.info("Deploying verticle: " + verticle.getClass().getName());

        DeploymentOptions options = new DeploymentOptions()
                .setWorker(true)
                .setInstances(1)
                .setWorkerPoolName("ha-verticle-pool")
                .setHa(true)
                .setWorkerPoolSize(1);

        vertx.deployVerticleAndForget(verticle, options);
    }
}
```

```java
@ApplicationScoped
public class HAVerticle extends io.vertx.core.AbstractVerticle {
    @Override
    public void start() throws Exception {
        Log.info("HAVerticle started");
    }

    @Override
    public void stop() throws Exception {
        Log.info("HAVerticle stopped");
    }
}
```

```
quarkus.vertx.cluster.clustered=true
```

```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-5.4.xsd">
    <cluster-name>dev-cluster</cluster-name>
    <network>
        <join>
            <multicast enabled="false"/>
            <tcp-ip enabled="true">
                <interface>127.0.0.1</interface>
            </tcp-ip>
        </join>
        <interfaces enabled="true">
            <interface>127.0.0.1</interface>
        </interfaces>
    </network>
</hazelcast>
```

### Output of `uname -a` or `ver`

Darwin macbook.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

java version "21" 2023-09-19 Java(TM) SE Runtime Environment Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

### Quarkus version or git rev

3.6.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.5

**Comment by geoand** [comment]
I'll leave this to @cescoffier to clarify, but AFAIK this use case has never been supported and changing the scope of the  Verticle to fit it sounds like a bad workaround to me.

**Comment by cescoffier** [comment]
Vert.x HA is not supported in Quarkus. There may not be a good workaround. 
HA is a bit tricky, and I don't believe you can use Verticle "beans" reliably (as the HA manager decides). Could you try deploying your instance using a supplier and use CDI programmatic lookup?

**Comment by drse** [comment]
The following produces same error:

```java
@ApplicationScoped
public class VerticleDeployer {
    public void init(
            @Observes StartupEvent e,
            Vertx vertx,
            Instance<HAVerticle> verticleInstance
    ) {
        Log.info("Deploying verticle: " + verticleInstance);

        DeploymentOptions options = new DeploymentOptions()
                .setWorker(true)
                .setInstances(1)
                .setWorkerPoolName("ha-verticle-pool")
                .setHa(true)
                .setWorkerPoolSize(1);

        vertx.deployVerticleAndForget(verticleInstance::get, options);
    }
}
```

```
 Failed to redeploy verticle java:org.acme.HAVerticle_ClientProxy after quorum was re-attained: java.lang.InstantiationException: org.acme.HAVerticle_ClientProxy
        at java.base/java.lang.Class.newInstance(Class.java:719)
        at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:153)
        at io.vertx.core.impl.VerticleManager.lambda$doDeployVerticle$5(VerticleManager.java:222)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoSuchMethodException: org.acme.HAVerticle_ClientProxy.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3761)
        at java.base/java.lang.Class.newInstance(Class.java:706)
        ... 12 more
```

However, both solutions work when `HAVerticle` is annotated with `@Dependent`. I will most likely give up on this workaround since it is not supported, or will roll my own HA.

**Comment by cescoffier** [comment]
Can you post `vecticleInstance`?

**Comment by drse** [comment]
```java
package org.acme;

import io.quarkus.logging.Log;
import io.smallrye.mutiny.vertx.core.AbstractVerticle;
import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class HAVerticle extends AbstractVerticle {
    @Override
    public void start() {
        Log.info("HAVerticle started");
    }

    @Override
    public void stop() {
        Log.info("HAVerticle stopped");
    }
}
```

**Comment by cescoffier** [comment]
That's the problem: your verticle cannot be a bean when used with the HA.

You can try `@Singleton` instead of `@ApplicationScoped`, it may workaround the issue.
