### ISSUE TITLE
Cross-Site Request Forgery (CSRF) prevents JSON-Bodies to be deserialized

### ISSUE THREAD

**Issue by lizzyTheLizard** [quarkusio/quarkus#38326]
### Describe the bug

I want to add CSRF-protection as described in https://quarkus.io/guides/security-csrf-prevention. But my application has some Ajax-endpoints, e.g:
```
@POST
  @Path("/csrfTokenPostBody")
  @Consumes(MediaType.APPLICATION_JSON)
  @Produces(MediaType.TEXT_PLAIN)
  public Uni<String> postJson(User user) {
    return Uni.createFrom().item(user.name);
  }
```

### Expected behavior

The token is read from the header and verified. If the token is correct, the method can access the body normally.

### Actual behavior

If I send a correct token in the header, I get this exception 
```
org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException: Attempting a blocking read on io thread
                at org.jboss.resteasy.reactive.server.vertx.VertxInputStream$VertxBlockingInput.readBlocking(VertxInputStream.java:245)
                at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.readIntoBuffer(VertxInputStream.java:123)
                at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:85)
                at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:539)
                at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:133)
                at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:256)
                at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1744)
                at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1143)
                at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1103)
                at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
                at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.doReadFrom(ServerJacksonMessageBodyReader.java:87)
                at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.readFrom(ServerJacksonMessageBodyReader.java:38)
                at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.readFrom(ServerJacksonMessageBodyReader.java:77)
                at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:126)
                at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:84)
                at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:135)
                at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
                at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
                at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
                at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
                at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
                at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
                at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
                at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:59)
                at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:37)
                at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
                at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
                at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
                at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:339)
                at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:332)
                at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
                at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
                at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
                at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:68)
                at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
                at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$2.handle(HttpServerCommonHandlers.java:83)
                at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$2.handle(HttpServerCommonHandlers.java:66)
                at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:162)
                at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:138)
                at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
                at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:179)
                at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:174)
                at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
                at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:124)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
                at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannet.java:420)tex
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:1583)

```

### How to Reproduce?

I created an example at https://github.com/lizzyTheLizard/quarkus-csrf-reactive-json-body, including a failing test that shows the behaviour

### Output of `uname -a` or `ver`

Linux XXXXX #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.9 2023-10-17

### Quarkus version or git rev

3.6.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 

### Additional information

It might be linked to https://github.com/quarkusio/quarkus/issues/22444 The WithFormRead annotation tries to read the form parameter. This will already consume the input stream preventing Jackson to read it again (just a guess). Also quarkus.csrf-reactive.require-form-url-encoded=false does not help as the body is still parsed and cannot be read any more.

**Comment by sberyozkin** [comment]
@FroMage, Steph, what do you think re a possible #22444 impact ?

**Comment by sberyozkin** [comment]
>Also quarkus.csrf-reactive.require-form-url-encoded=false does not help as the body is still parsed and cannot be read any more.

Right, the CCRF filter is not processing the body itself, ` quarkus.csrf-reactive.require-form-url-encoded=false` is only there to support cases where HTML forms are used and some methods in the class are not related to the form processing

**Comment by FroMage** [comment]
Due to the return of `Uni` the method is marked as non-blocking. Which is fine, I really don't understand why the body deserialisation should pose any blocking issue, since it's always read before the endpoint is called, and we don't support async reading of the body with things like `Uni<User>` as a parameter.

This looks like a bug in RESTEasy Reactive, don't you think, @geoand ?

**Comment by geoand** [comment]
Indeed.

I'll have to take a look

**Comment by FroMage** [comment]
Thanks

**Comment by geoand** [comment]
👌

**Comment by geoand** [comment]
I can confirm this is a bug on the RESTEasy Reactive side.

Now I need to figure out how to fix it :)

**Comment by geoand** [comment]
👍🏼
