### ISSUE TITLE
nested configurations in extension: sub-property is seen as nested entity.

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#38422]
### Describe the bug

The nightly builds for `quarkus-artemis` against the `main` of `quarkus` fail since 2023-01-04, see e.g. [here (`github.com`)](https://github.com/quarkiverse/quarkus-artemis/actions/runs/7664166199).

We have a similar configuration scheme as data sources have: we allow named connection factories, with one default connection factory. Looking at the stack trace of the build we find this stack trace:
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:643)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:727)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:285)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:252)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:610)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:660)
	... 1 more
Caused by: java.lang.IllegalStateException: Configuration devservices: url is not set and devservices is activated. This is a bug. Please report it.
	at io.quarkus.artemis.core.runtime.ArtemisUtil.validateIntegrity(ArtemisUtil.java:30)
	at io.quarkus.artemis.jms.runtime.ArtemisJmsRecorder.getConnectionFactoryProducer(ArtemisJmsRecorder.java:32)
	at io.quarkus.deployment.steps.ArtemisJmsProcessor$configure1243796012.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArtemisJmsProcessor$configure1243796012.deploy(Unknown Source)
	... 8 more
```
This means that `devservices` is recognized as named connection factory, not as property of the default configuration.

Further details can be found on [the PR that should upgrade `quarkus` to `3.7.0`  in `quarkus-artemis` (`github.com`)](https://github.com/quarkiverse/quarkus-artemis/pull/382).

**Comment by turing85** [comment]
@radcortez any news on this?

**Comment by radcortez** [comment]
Yes, https://github.com/smallrye/smallrye-config/pull/1107 fixes this.

**Comment by turing85** [comment]
! 

> Yes, [smallrye/smallrye-config#1107](https://github.com/smallrye/smallrye-config/pull/1107) fixes this.

Will test shortly! Thanks

**Comment by turing85** [comment]
I can confirm that the fix works. Thanks again @radcortez !
