### ISSUE TITLE
Unsatisfied dependency

### ISSUE THREAD

**Issue by punkratz312** [quarkusio/quarkus#38461]
### cant build jandex

hello friends,

would you please have a look at my dependency injection problem. Quarkus cant find the bean. CDI works if i take the copy from the same modul.

i have added the sub-modul to jandex 

these combinations have been tried:
quarkus.index-dependency.adapters.artifact-id=adapters
quarkus.index-dependency.adapters.artifact-id=driver.adapters
quarkus.index-dependency.adapters.artifact-id=:drivers:adapters:
```
quarkus.index-dependency.adapters.artifact-id=adapters
quarkus.index-dependency.adapters.group-id=de.db.vendo.prototype.buchung.reservation
```

```
2024-01-29 22:37:40,144 WARN  [io.qua.hib.orm.dep.HibernateOrmProcessor] (build-2) Hibernate ORM is disabled because no JPA entities were found
2024-01-29 22:37:40,144 INFO  [io.qua.hib.orm.dep.dev.HibernateOrmDevServicesProcessor] (build-20) Setting quarkus.hibernate-orm.database.generation=drop-and-create to initialize Dev Services managed database
2024-01-29 22:37:40,166 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (vert.x-worker-thread-1) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type de.db.vendo.prototype.buchung.reservation.divers.adapters.submit.boundary.SubmitReservationResourceAdapter and qualifiers [@Default]
	- java member: de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource#resourceAdapter
	- declared on CLASS bean [types=[de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource, java.lang.Object], qualifiers=[@Default, @Any], target=de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1453)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:311)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:160)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:472)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1623)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type de.db.vendo.prototype.buchung.reservation.divers.adapters.submit.boundary.SubmitReservationResourceAdapter and qualifiers [@Default]
	- java member: de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource#resourceAdapter
	- declared on CLASS bean [types=[de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource, java.lang.Object], qualifiers=[@Default, @Any], target=de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:478)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:624)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:299)
	... 11 more

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:334)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:264)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.reloadExistingApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:190)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:173)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:541)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:441)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.call(VertxHttpHotReplacementSetup.java:150)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.call(VertxHttpHotReplacementSetup.java:137)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$0(ContextBase.java:167)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type de.db.vendo.prototype.buchung.reservation.divers.adapters.submit.boundary.SubmitReservationResourceAdapter and qualifiers [@Default]
	- java member: de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource#resourceAdapter
	- declared on CLASS bean [types=[de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource, java.lang.Object], qualifiers=[@Default, @Any], target=de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1453)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:311)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:160)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:472)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1623)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type de.db.vendo.prototype.buchung.reservation.divers.adapters.submit.boundary.SubmitReservationResourceAdapter and qualifiers [@Default]
	- java member: de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource#resourceAdapter
	- declared on CLASS bean [types=[de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource, java.lang.Object], qualifiers=[@Default, @Any], target=de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:478)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:624)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:299)
	... 11 more

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	... 18 more
Caused by: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type de.db.vendo.prototype.buchung.reservation.divers.adapters.submit.boundary.SubmitReservationResourceAdapter and qualifiers [@Default]
	- java member: de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource#resourceAdapter
	- declared on CLASS bean [types=[de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource, java.lang.Object], qualifiers=[@Default, @Any], target=de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1453)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:311)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:160)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:472)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1623)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type de.db.vendo.prototype.buchung.reservation.divers.adapters.submit.boundary.SubmitReservationResourceAdapter and qualifiers [@Default]
	- java member: de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource#resourceAdapter
	- declared on CLASS bean [types=[de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource, java.lang.Object], qualifiers=[@Default, @Any], target=de.db.vendo.prototype.buchung.reservation.divers.web.submit.boundary.SubmitReservationResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:478)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:624)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:299)
	... 11 more

2024-01-29 22:37:40,168 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-1) Live reload total time: 0.112s 
```

Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type de.db.vendo.prototype.buchung.reservation.divers.adapters.submit.boundary.SubmitReservationResourceAdapter and qualifiers [@Default]

<img width="1628" alt="image" src="https://github.com/quarkusio/quarkus/assets/8830888/7fd8ad07-322c-41c8-9285-6249d6f8c059">

**Comment by mkouba** [comment]
Hello @punkratz312, what's the GA (`<groupId>` and `<artifactId>` from the `pom.xml`) of your artifact?

Also if I understand it correctly it's a Maven multi-module project, right? If so then a project structure description would be helpful (module hierarchy, from which module you run `quarkus:dev` etc.).

**Comment by Ladicek** [comment]
You can also include an empty `META-INF/beans.xml` file into the JAR, that will make the archive indexed as well (and is a standard bean archive designator).

**Comment by punkratz312** [comment]
@mkouba thanks for you approach.

its gradle multi modul with **nested** child projects:


<img width="1861" alt="image" src="https://github.com/quarkusio/quarkus/assets/8830888/148b3967-b873-4d30-811c-50aedc16600a">

Awesome @Ladicek thank you so much.

So it must be an issue with addressing the module. The empty beans.xml did the trick. Thank you so much.

quarkus.index-dependency.adapters.artifact-id=adapters

<img width="1646" alt="image" src="https://github.com/quarkusio/quarkus/assets/8830888/df59effa-1ff2-44f1-b296-4c3fe38fcf55">
<img width="602" alt="image" src="https://github.com/quarkusio/quarkus/assets/8830888/0fe07970-e9b9-46b5-8c68-15105780aa21">

**Comment by punkratz312** [comment]
Please you have any advice whats the jandex issue is? i can start the app and even the cdi works on runtime with the beans.xml fix.



<img width="1790" alt="image" src="https://github.com/quarkusio/quarkus/assets/8830888/4386d847-2b59-43b3-848b-5355c06e0113">


```
> Task :drivers:quarkusAppPartsBuild
> Task :drivers:compileTestJava NO-SOURCE
> Task :drivers:testClasses
> Task :drivers:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':drivers:test' (type 'Test').
  - Gradle detected a problem with the following location: '/Users/wip/IdeaProjects/reservierung-prototype/drivers/build/resources/main'.
    
    Reason: Task ':drivers:test' uses this output of task ':drivers:jandex' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':drivers:jandex' as an input of ':drivers:test'.
      2. Declare an explicit dependency on ':drivers:jandex' from ':drivers:test' using Task#dependsOn.
      3. Declare an explicit dependency on ':drivers:jandex' from ':drivers:test' using Task#mustRunAfter.
    
    For more information, please refer to https://docs.gradle.org/8.4/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 12s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
38 actionable tasks: 37 executed, 1 up-to-date
10:30:05: Execution finished 'build'.

```

**Comment by punkratz312** [comment]
Disabled jandex plugin worked out 🗡️ 

<img width="629" alt="image" src="https://github.com/quarkusio/quarkus/assets/8830888/faf63ea7-5429-4f27-b65f-0c9af709207a">

<img width="1697" alt="image" src="https://github.com/quarkusio/quarkus/assets/8830888/8403493a-ccbe-4643-94b9-3f1ddbe2f58a">
