### ISSUE TITLE
Dev mode: weird ZIP error on shutdown

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3846]
I sometimes have this weird this error when I shut down the dev mode:
```
^C2019-09-04 11:39:21,915 ERROR [io.qua.run.StartupContext] (Quarkus Shutdown Thread) Running a shutdown task failed: java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:583)
	at java.util.zip.ZipFile.access$900(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:539)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:514)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at java.util.jar.JarFile$JarEntryIterator.next(JarFile.java:257)
	at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:266)
	at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:247)
	at sun.misc.URLClassPath$JarLoader.validIndex(URLClassPath.java:1005)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1138)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1050)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:239)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.quarkus.runtime.CleanableExecutor.clean(CleanableExecutor.java:50)
	at io.quarkus.runtime.ExecutorRecorder$1.run(ExecutorRecorder.java:47)
	at io.quarkus.runtime.StartupContext.close(StartupContext.java:43)
	at io.quarkus.runner.ApplicationImpl1.doStop(ApplicationImpl1.zig:156)
	at io.quarkus.runtime.Application.stop(Application.java:158)
	at io.quarkus.runner.RuntimeRunner$1.close(RuntimeRunner.java:143)
	at io.quarkus.runner.RuntimeRunner.close(RuntimeRunner.java:83)
	at io.quarkus.dev.DevModeMain$1.run(DevModeMain.java:110)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stuartwdouglas** [comment]
@gsmet did you happen to re-build Quarkus while dev mode was active? Dev mode runs from artifacts in the maven repo, so if you do mvn install on quarkus then shut down you can get that error

**Comment by gsmet** [comment]
Ah maybe, I was building the Quarkus core runtime a lot to fix the error page.

Let's close it then. I'll reopen if it happens in other circumstances.
