### ISSUE TITLE
OpenShift Integration Tests CI is failing for months

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#38472]
### Description

OpenShift Integration Tests CI is failing for months

https://github.com/quarkusio/quarkus/actions/workflows/ci-kubernetes.yml

From https://github.com/quarkusio/quarkus/actions/runs/7705303378/job/20999153914 - Set up OpenShift
```
 Starting OpenShift using openshift/origin-control-plane:v3.11 ...
I0130 02:16:38.709568    2110 config.go:40] Running "create-master-config"
I0130 02:16:40.725662    2110 config.go:46] Running "create-node-config"
I0130 02:16:41.224677    2110 flags.go:30] Running "create-kubelet-flags"
I0130 02:16:41.518473    2110 run_kubelet.go:49] Running "start-kubelet"
I0130 02:16:41.580838    2110 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0130 02:16:59.588422    2110 interface.go:26] Installing "kube-proxy" ...
I0130 02:16:59.588437    2110 interface.go:26] Installing "kube-dns" ...
I0130 02:16:59.588441    2110 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0130 02:16:59.588446    2110 interface.go:26] Installing "openshift-apiserver" ...
I0130 02:16:59.588463    2110 apply_template.go:81] Installing "openshift-apiserver"
I0130 02:16:59.588628    2110 apply_template.go:81] Installing "kube-proxy"
I0130 02:16:59.588772    2110 apply_template.go:81] Installing "kube-dns"
I0130 02:16:59.588890    2110 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0130 02:17:01.369187    2110 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
Error: Command failed: oc cluster up --routing-suffix="127.0.0.1.${OC_DOMAIN:-nip.io}" 
    at checkExecSyncError (node:child_process:861:11)
    at Object.execSync (node:child_process:932:15)
Error: Command failed: oc cluster up --routing-suffix="127.0.0.1.${OC_DOMAIN:-nip.io}" 
    at logExecSync (/home/runner/work/_actions/manusa/actions-setup-openshift/v1.1.5/src/exec.js:8:17)
    at clusterUp (/home/runner/work/_actions/manusa/actions-setup-openshift/v1.1.5/src/install.js:16:3)
    at startCluster (/home/runner/work/_actions/manusa/actions-setup-openshift/v1.1.5/src/install.js:18:39)
    at install (/home/runner/work/_actions/manusa/actions-setup-openshift/v1.1.5/src/install.js:46:3)
Error: Command failed: oc cluster up --routing-suffix="127.0.0.1.${OC_DOMAIN:-nip.io}" 
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/home/runner/work/_actions/manusa/actions-setup-openshift/v1.1.5/src/index.js:16:3) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2109,
  stdout: null,
  stderr: null
}
```

CC @iocanel @maxandersen

**Comment by iocanel** [comment]
@manusa: Is this something you've seen before?

**Comment by manusa** [comment]
Yes, indeed.

https://github.com/fabric8io/kubernetes-client/issues/5545

They seem to have broken the OpenShift 3.x images a long time ago.

From time to time the OpenShift 3.10 version does work, depending on what they deploy to the image registry.

As of today, we haven't found any feasible way to deploy an ephemeral OpenShift cluster on a GitHub hosted runner.

Any suggestions are welcome ;)

**Comment by gsmet** [comment]
@rsvoboda @maxandersen  ^ Looks like we don't have many options and we might have to get rid of these tests on the GitHub Actions infra.
