### ISSUE TITLE
[resteasy classic] Invalid JSON body should result in HTTP 400, not 500

### ISSUE THREAD

**Issue by steinsag** [quarkusio/quarkus#38511]
### Describe the bug

In Quarkus <= 3.6.6, POSTing a non-JSON string to a REST endpoint set to consume only JSON resulted in HTTP 400 response. This behaviour changed with Quarkus 3.6.7 release. Now, a internal server error is thrown instead.

Stacktrace:

```
2024-01-31 23:08:43,847 ERROR [org.jbo.res.plu.pro.jackson] (executor-thread-1) RESTEASY-JACKSON000100: Not able to deserialize data provided: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2481)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:752)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:676)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2794)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:911)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:797)
	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:171)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:99)
	at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:60)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:81)
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:192)
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:87)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:116)
```

### Expected behavior

A request not possible to parse should be rejected with HTTP 400 like in the past.

### Actual behavior

Quarkus responds with HTTP 500 instead.

### How to Reproduce?

```
git clone git@github.com:steinsag/quarkus-maven-kotlin.git
git checkout dependabot/maven/quarkus.platform.version-3.7.1
mvn clean verify
```

test case: services.progressit.rest.TodoResourceTest.Create#post - invalid JSON - bad request 400
```
given()
                .contentType(APPLICATION_JSON)
                .body("<invalidJson />")
                .post("/$TODO_BASE_PATH")
                .then().statusCode(400)
```

respective REST endpoint: services.progressit.rest.TodoResource#createTodo

controller annotated with
```
@Consumes(APPLICATION_JSON)
@Produces(APPLICATION_JSON)
abstract class TodoResourceDocumentation {
```

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.9.6

**Comment by geoand** [comment]
cc @jamezp

**Comment by jamezp** [comment]
FWIW I added this to the project and the test passed. I know it's not ideal, but it's at least a workaround:
```kotlin
package services.progressit.rest

import com.fasterxml.jackson.core.JsonProcessingException
import jakarta.ws.rs.core.Response
import jakarta.ws.rs.ext.ExceptionMapper
import jakarta.ws.rs.ext.Provider

@Provider
class JsonProcessingExceptionMapper : ExceptionMapper<JsonProcessingException> {
    override fun toResponse(exception: JsonProcessingException?): Response {
        if (exception != null) {
            return Response.status(Response.Status.BAD_REQUEST).entity(exception.message).build()
        }
        return Response.status(Response.Status.BAD_REQUEST).build()
    }
}
```

**Comment by steinsag** [comment]
I think it is good that the output is cleaned to not expose any internal information, but this should not change the HTTP response code.

**Comment by geoand** [comment]
@jamezp ib Quarkus `JsonProcessingExceptionMapper` is also executed properly and HTTP 500 is always returned.

I think what @steinsag is saying that he doesnt' agree with the return code returned by that mapper, and FWIW I agree with him (in RESTEasy Reactive we return 400 in that case)

**Comment by jamezp** [comment]
I do agree 400 is better. I think the only reason I went with 500 is that is what was returned before, in most cases. There were some cases where 400 would have been returned. I was mostly concerned with breaking compatibility. I've filed https://issues.redhat.com/browse/RESTEASY-3443 to fix this.

**Comment by jamezp** [comment]
Actually, I remember now why I went with a 500. The RESTEasy tests expected a 500 and my general rule is that tests shouldn't change for a bug fix. I need to think about the compatibility issue here. While maybe not ideal, it's very easy to override the `ExceptionMapper` with a custom one, which is why I did it this way.

That said, I could use that same argument to change the response code to the correct response code :)

**Comment by geoand** [comment]
In any case, I'm going to close this here as it's an upstream issue.

**Comment by steinsag** [comment]
Any chance to include the fix in the upcoming LTS release of Quarkus?

**Comment by geoand** [comment]
We can likely backport the 6.2.8 version to Quarkus when it's available

**Comment by stephan-strate** [comment]
I just stumbled across this problem aswell, but with other symptoms. I got a MissingKotlinParameterException, which also leads to a 500, but should be 400.

Just wanted to leave this message, so when someone searches for MissingKotlinParameterException, he or she will find this issue and can resolve it with the workaround :)
