### ISSUE TITLE
Panache sorting no longer works for embedded fields in Quarkus 3.7.1

### ISSUE THREAD

**Issue by Felk** [quarkusio/quarkus#38521]
### Describe the bug

Starting with Quarkus 3.7, when sorting on a field that contains `.`, e.g. an embeddable `Sort.by("embeddedThing.name")`, an error occurrs, e.g. `org.hibernate.query.SemanticException: Could not interpret path expression 'embeddedThing.name'`.

### Expected behavior

No exception

### Actual behavior

an error occurrs:
```
java.lang.IllegalArgumentException: org.hibernate.query.SemanticException: Could not interpret path expression 'embeddedThing.name'

	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:143)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:167)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:173)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:848)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:753)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:136)
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.createQuery(TransactionScopedSession.java:367)
	at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:558)
	at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:67)
	at org.hibernate.Session_OpdLahisOZ9nWRPXMsEFQmQU03A_Synthetic_ClientProxy.createQuery(Unknown Source)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createBaseQuery(CommonPanacheQueryImpl.java:366)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createQuery(CommonPanacheQueryImpl.java:327)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.list(CommonPanacheQueryImpl.java:278)
	at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.list(PanacheQueryImpl.java:149)
	at org.acme.PanacheSortRegressionTest.embeddedSortTest(PanacheSortRegressionTest.java:13)
	at org.acme.PanacheSortRegressionTest_Subclass.embeddedSortTest$$superforward(Unknown Source)
	at org.acme.PanacheSortRegressionTest_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TestTransactionInterceptor.intercept(TestTransactionInterceptor.java:45)
	at io.quarkus.narayana.jta.runtime.interceptor.TestTransactionInterceptorGenerated_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at org.acme.PanacheSortRegressionTest_Subclass.embeddedSortTest(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.hibernate.query.SemanticException: Could not interpret path expression 'embeddedThing.name'
	at org.hibernate.query.hql.internal.BasicDotIdentifierConsumer$BaseLocalSequencePart.resolvePathPart(BasicDotIdentifierConsumer.java:255)
	at org.hibernate.query.hql.internal.BasicDotIdentifierConsumer.consumeIdentifier(BasicDotIdentifierConsumer.java:91)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.resolveOrderByOrGroupByExpression(SemanticQueryBuilder.java:1593)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitSortExpression(SemanticQueryBuilder.java:1681)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitSortSpecification(SemanticQueryBuilder.java:1641)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitOrderByClause(SemanticQueryBuilder.java:1624)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitOrderByClause(SemanticQueryBuilder.java:1613)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitQueryOrder(SemanticQueryBuilder.java:1095)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitQuerySpecExpression(SemanticQueryBuilder.java:944)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitQuerySpecExpression(SemanticQueryBuilder.java:269)
	at org.hibernate.grammars.hql.HqlParser$QuerySpecExpressionContext.accept(HqlParser.java:1869)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitSimpleQueryGroup(SemanticQueryBuilder.java:926)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitSimpleQueryGroup(SemanticQueryBuilder.java:269)
	at org.hibernate.grammars.hql.HqlParser$SimpleQueryGroupContext.accept(HqlParser.java:1740)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitSelectStatement(SemanticQueryBuilder.java:443)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitStatement(SemanticQueryBuilder.java:402)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.buildSemanticModel(SemanticQueryBuilder.java:311)
	at org.hibernate.query.hql.internal.StandardHqlTranslator.translate(StandardHqlTranslator.java:71)
	at org.hibernate.query.internal.QueryInterpretationCacheStandardImpl.createHqlInterpretation(QueryInterpretationCacheStandardImpl.java:165)
	at org.hibernate.query.internal.QueryInterpretationCacheStandardImpl.resolveHqlInterpretation(QueryInterpretationCacheStandardImpl.java:147)
	at org.hibernate.internal.AbstractSharedSessionContract.interpretHql(AbstractSharedSessionContract.java:790)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:840)
	... 26 more
```

### How to Reproduce?

`MyEntity.java`
```java
@Entity
public class MyEntity extends PanacheEntity {
    public String id;

    public EmbeddedThing embeddedThing;
}
```
`EmbeddedThing.java`
```java
@Embeddable
public class EmbeddedThing {
    public String name;
}
```
`PanacheSortRegressionTest.java`
```java
@QuarkusTest
@TestTransaction
class PanacheSortRegressionTest {
    @Test
    void embeddedSortTest() {
        MyEntity.findAll(Sort.by("embeddedThing.name")).list();
    }
}
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.3930]

### Output of `java -version`

openjdk version "21" 2023-09-19 OpenJDK Runtime Environment (build 21+35-2513) OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: C:\Program Files\maven\apache-maven-3.9.3 Java version: 21, vendor: Oracle Corporation, runtime: C:\Program Files\OpenJDK\jdk-21 Default locale: de_DE, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

Worked in Quarkus 3.6.9 (latest 3.6.x as of writing), broken in 3.7.1 (latest 3.7.x as of writing)

**Comment by Felk** [comment]
I'm seeing that with 3.6.9 the order by clause gets generated as `ORDER BY embeddedThing.name`, but with 3.7.1 it geta generated as `ORDER BY `embeddedThing.name``

**Comment by Felk** [comment]
Looks like this regression was introduced by https://github.com/quarkusio/quarkus/pull/37282, also pinging @ifeelgood in case they want to take a look at it

**Comment by yrodiere** [comment]
Yeah well I don't know what to do at this point.

Some people want this to be escaped, and others want to be able to use paths instead of attribute names.

Obviously that's incompatible, since escaping would likely escape the dots in paths.

What I can propose:

1. Revert #37282 and expose ourselves to injection (again)
2. Document that paths can't be passed to panache, only attribute names.
3. Split strings passed to panache on dots before escaping individual components of the path. This will prevent the use of dots in attribute names, but I guess that's acceptable? They are probably forbidden anyway; for Java fields/methods they are for sure, but I suspect there are ways to set an attribute name to something else than the field it's extracted from.

**Comment by yrodiere** [comment]
@gsmet only option 1 above is worth considering if you want a fix fast (and it seems you do).

I suspect 3 will lead to more trouble (like, is `+ORDER BY `embeddedThing`.`name`+` even valid HQL?).

**Comment by Felk** [comment]
I'd be fine with the auto-quoting if there was some other way to specify paths, e.g. any of these made up methods:

    Sort.by("`embeddedThing`.`name`")
    Sort.by(EntityPath.of("embeddedThing", "name"))
    Sort.by("embeddedThing.name", QuotingStrategy.DISABLE_AUTO_QUOTING)

**Comment by gsmet** [comment]
Yeah, I think we should revert it and go back to the drawing board.

I don't think we should forget about it though as it's an important subject.
