### ISSUE TITLE
LinksProcessor ID field error for native class HalCollectionWrapper

### ISSUE THREAD

**Issue by mahi-kandiar** [quarkusio/quarkus#38543]
### Describe the bug

Hello,

When I upgrade quarkus from 3.6.9 to 3.7.1 PR @bpasson https://github.com/quarkusio/quarkus/pull/38265/files is causing the following issue.

My entity is :

    import io.quarkus.resteasy.reactive.links.RestLinkId;
    
    @Getter
    @AllArgsConstructor
    @NoArgsConstructor
    public class Car
    {
    
       @RestLinkId
       private int id;
       private int year;
       private String make;
       private String model;
    }

In my controller I have : 

      Collection<Object> objectCollection = returnCars.stream().map(car -> (Object)car).collect(Collectors.toList());
      HalCollectionWrapper halCollection = resteasyReactiveHalService.toHalCollectionWrapper(objectCollection,"result_page_"+pageRequest.getPage()+"_size_"+pageRequest.getSize(),
               Car.class);

When the app starts I get:

        2024-02-01 16:46:50,992 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	        [error]: Build step io.quarkus.resteasy.reactive.links.deployment.LinksProcessor#initializeLinksProvider threw an exception: java.lang.IllegalStateException: Cannot generate web links for the class io.quarkus.hal.HalCollectionWrapper because it is either missing an `id` field, a field with an `@Id` annotation or a field with a `@RestLinkId annotation
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:268)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateClassHasFieldId(LinksProcessor.java:232)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.implementPathParameterValueGetters(LinksProcessor.java:151)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.initializeLinksProvider(LinksProcessor.java:76)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	        at java.base/java.lang.Thread.run(Thread.java:840)
	        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        
	        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:334)
	        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:251)
	        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:112)
	        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:433)
	        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
	        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
	        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
	        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
        Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	        [error]: Build step io.quarkus.resteasy.reactive.links.deployment.LinksProcessor#initializeLinksProvider threw an exception: java.lang.IllegalStateException: Cannot generate web links for the class io.quarkus.hal.HalCollectionWrapper because it is either missing an `id` field, a field with an `@Id` annotation or a field with a `@RestLinkId annotation
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:268)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateClassHasFieldId(LinksProcessor.java:232)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.implementPathParameterValueGetters(LinksProcessor.java:151)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.initializeLinksProvider(LinksProcessor.java:76)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	        at java.base/java.lang.Thread.run(Thread.java:840)
	        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        
	        at io.quarkus.builder.Execution.run(Execution.java:123)
	        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	        ... 9 more
        Caused by: java.lang.IllegalStateException: Cannot generate web links for the class io.quarkus.hal.HalCollectionWrapper because it is either missing an `id` field, a field with an `@Id` annotation or a field with a `@RestLinkId annotation
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:268)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateRec(LinksProcessor.java:277)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.validateClassHasFieldId(LinksProcessor.java:232)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.implementPathParameterValueGetters(LinksProcessor.java:151)
	        at io.quarkus.resteasy.reactive.links.deployment.LinksProcessor.initializeLinksProvider(LinksProcessor.java:76)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	        at java.base/java.lang.Thread.run(Thread.java:840)
	        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        
        

### Expected behavior

Since my entity is marked with `RestLinkId` and I am using quarkus's `io.quarkus.hal.HalCollectionWrapper` I should not have received `io.quarkus.resteasy.reactive.links.deployment.LinksProcessor` 's IllegalStateException. HalCollectionWrapper and HalEntityWrapper should be excluded from the Id check.

### Actual behavior

I end up getting 

    java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.reactive.links.deployment.LinksProcessor#initializeLinksProvider threw an exception: java.lang.IllegalStateException: Cannot generate web links for the class io.quarkus.hal.HalCollectionWrapper because it is either missing an `id` field, a field with an `@Id` annotation or a field with a `@RestLinkId annotation

### How to Reproduce?

1. Create an entity with RestLinkId annotation
2. Create a controller method like 

     `@GET`
     `@Produces({ MediaType.APPLICATION_JSON, RestMediaType.APPLICATION_HAL_JSON })`
     `@RestLink(rel = "list")`
     `@InjectRestLinks`
       public HalCollectionWrapper getCars(@BeanParam PageRequest pageRequest, @Context UriInfo uriInfo)
       {
          List<Car> returnCars = Cars.cars();
    

         Collection<Object> objectCollection = returnCars.stream().map(car -> (Object)car).collect(Collectors.toList());
      
        HalCollectionWrapper halCollection = resteasyReactiveHalService.toHalCollectionWrapper(objectCollection,"result_page_"+pageRequest.getPage()+"_size_"+pageRequest.getSize(),
         Car.class);

          halCollection.addLinks(Link.fromPath(uriInfo.getAbsolutePath().toString()+"?page="+(pageRequest.getPage()+1)+"size="+pageRequest.getSize()).rel("next_page_url").build());

          halCollection.addLinks(Link.fromPath(uriInfo.getAbsolutePath().toString()+"?page=1&size=20").rel("first_page_url").build());

         halCollection.addLinks(Link.fromPath(uriInfo.getAbsolutePath().toString()).rel("list").build());

         return halCollection;
       }
4. Run application

### Output of `java -version`

17

### Quarkus version or git rev

3.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.5

**Comment by bpasson** [comment]
I will have a look.

**Comment by bpasson** [comment]
@mahi-kandiar after the 3.6.9 release a check was included which valides the configuration for injecting rest links. The way you are using it is incorrect, but was silently ignored upto release 3.6.9. Which is why you are getting the IllegalStateException. You are using the `HalCollectionWrapper` to provide the links. The annotations should then not be used. 

Looking at the code I assume you want to have paging support. I'm not sure paging is supported in general for `resteasy-reactive`. If you are working with entities you could take a look at https://quarkus.io/guides/rest-data-panache#resource-customisation which shows how to use paging with `rest-data-panache`.

**Comment by mahi-kandiar** [comment]
Thank you @bpasson. Removing the annotations fixed it. Regarding panache, I don't have control over the data access layer yet. Would you be kind and remove the annotation at https://github.com/bpasson/quarkus/blob/be75b5d1a897dda26051f073ac61c5048173d4b4/docs/src/main/asciidoc/resteasy-reactive.adoc?plain=1#L1886 too please. If I add that annotation, the exception reappears.

**Comment by bpasson** [comment]
@mahi-kandiar Looking at that documentation mentioning the possibility to add extra links programmatically, this might still require a fix. It seems it was broken already before my PR. Could you reopen the issue? I will see if I can come up with a fix.

**Comment by mahi-kandiar** [comment]
@bpasson sure.

**Comment by bpasson** [comment]
Looking at the documentation the following should be possible

```
@Path("/records")
public class RecordsResource {

    @Inject
    RestLinksProvider linksProvider;

    @GET
    @Produces({ MediaType.APPLICATION_JSON, RestMediaType.APPLICATION_HAL_JSON })
    @RestLink(rel = "list")
    public HalCollectionWrapper getAll() {
        List<Record> list = // ...
        HalCollectionWrapper halCollection = new HalCollectionWrapper(list, "collectionName", linksProvider.getTypeLinks(Record.class));
        halCollection.addLinks(Link.fromPath("/records/1").rel("first-record").build());
        return halCollection;
    }

    @GET
    @Produces({ MediaType.APPLICATION_JSON, RestMediaType.APPLICATION_HAL_JSON })
    @Path("/{id}")
    @RestLink(rel = "self")
    @InjectRestLinks(RestLinkType.INSTANCE)
    public HalEntityWrapper get(@PathParam("id") int id) {
        Record entity = // ...
        HalEntityWrapper halEntity = new HalEntityWrapper(entity, linksProvider.getInstanceLinks(entity));
        halEntity.addLinks(Link.fromPath("/records/1/parent").rel("parent-record").build());
        return halEntity;
    }
}
```

But that wont work for three reasons:
* Since release 3.6.9 the return type is checked to actually be able to provide an `id` for the self link.
* The `HalEntityWrapper` and `HalCollectionWrapper` have not id field, the entity probably does, but we don't know which type it is during link processing.
* The constructor signature for the `HalCollectionWrapper` does not match the one being used here.

For this to work the type being wrapped needs to be know when processing the links. So either the `HalCollectionWrapper` and `HalEntityWrapper` need to become parameterized or we need to have some annotation
list the type. Personally I would opt for parameterizing the wrapper classes, but not sure what the impact would be.

It is also probably better to construct the wrapper classes using the `HalService`. It has utility methods available for this.

Anybody any suggestion?

**Comment by geoand** [comment]
@Sgitario do you have any suggestions?

**Comment by bpasson** [comment]
I did some preliminary testing with parameterizing the wrapper types and ended up with the following REST resource matching the documentation mentioned earlier as best as possible.

```
@Path("/hal")
public class HalWrapperResource {

    @Inject
    ResteasyReactiveHalService halService;

    @GET
    @Produces({ MediaType.APPLICATION_JSON, RestMediaType.APPLICATION_HAL_JSON })
    @RestLink(rel = "list")
    @InjectRestLinks
    public HalCollectionWrapper<TestRecord> getRecords(@Context UriInfo uriInfo) {
        List<TestRecord> items = List.of(
                new TestRecord(1, "slug-1", "1"),
                new TestRecord(2, "slug-2", "2"));

        HalCollectionWrapper<TestRecord> halCollection = halService.toHalCollectionWrapper(items,
                "collectionName", TestRecord.class);
        halCollection.addLinks(
                Link.fromUriBuilder(uriInfo.getBaseUriBuilder().path(String.format("/hal/%d", 1))).rel("first-record").build());

        return halCollection;
    }

    @GET
    @Path("/{id}")
    @Produces({ MediaType.APPLICATION_JSON, RestMediaType.APPLICATION_HAL_JSON })
    @RestLink(rel = "self")
    @InjectRestLinks(RestLinkType.INSTANCE)
    public HalEntityWrapper<TestRecord> getRecord(@PathParam("id") int id, @Context UriInfo uriInfo) {

        HalEntityWrapper<TestRecord> halEntity = halService.toHalWrapper(new TestRecord(id, "slug-" + id, "" + id));
        halEntity.addLinks(Link.fromUriBuilder(uriInfo.getBaseUriBuilder().path(String.format("/hal/%d/parent", id)))
                .rel("parent-record").build());

        return halEntity;
    }
}
```

Which results in the following output for `GET /hal`

```
{
    "_embedded": {
        "collectionName": [
            {
                "id": 1,
                "slug": "slug-1",
                "value": "1",
                "_links": {
                    "self": {
                        "href": "http://localhost:8081/hal/1"
                    },
                    "list": {
                        "href": "http://localhost:8081/hal"
                    }
                }
            },
            {
                "id": 2,
                "slug": "slug-2",
                "value": "2",
                "_links": {
                    "self": {
                        "href": "http://localhost:8081/hal/2"
                    },
                    "list": {
                        "href": "http://localhost:8081/hal"
                    }
                }
            }
        ]
    },
    "_links": {
        "first-record": {
            "href": "http://localhost:8081/hal/1"
        },
        "list": {
            "href": "http://localhost:8081/hal"
        }
    }
}
```
And for `GET /hal/1`
```
{
    "id": 1,
    "slug": "slug-1",
    "value": "1",
    "_links": {
        "parent-record": {
            "href": "http://localhost:8081/hal/1/parent"
        },
        "self": {
            "href": "http://localhost:8081/hal/1"
        },
        "list": {
            "href": "http://localhost:8081/hal"
        }
    }
}
```
It mostly looks ok in my opinion. I only have some doubts about the `list` relation with each entity in the collection. This happens because the links are now resolved based on the wrappers type, in this case `TestRecord`.  Should that be there?

**Comment by bpasson** [comment]
It seems you also get this when using `List<TestRecord>` and `TestRecord` as return type for the rest methods. I guess it should be fine then. What do you think?

**Comment by bpasson** [comment]
@geoand @Sgitario shall I open a PR so we can discuss my preliminary solution?

**Comment by Sgitario** [comment]
I didn't follow the latest changes here, but it looks good to me to open a new PR for further discussion. 
Btw, I would better prefer using `HalService` instead of `ResteasyReactiveHalService`

**Comment by bpasson** [comment]
It will be `HalService` in the PR. It's just a left over from my preliminary testing and debugging where this went wrong. I'll see if I can open the PR tonight. @Sgitario if you could then have a look at it that would be much appreciated.
