### ISSUE TITLE
InternalServerErrorException Testcontainer start

### ISSUE THREAD

**Issue by hakuseki** [quarkusio/quarkus#38555]
### Describe the bug

With 3.7.1 when starting Dev. services and Testcontainers, I get errors and the testcontainers are not download/started.

```
2024-02-02 10:20:24,213 ERROR [com.git.doc.api.asy.ResultCallbackTemplate] (docker-java-stream--623331358) Error during callback: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Expected behavior

DevServices and Testcontainers started normally.
As for 3.6.9

### Actual behavior

When starting quarkus dev, my two endpoints, Kafka and Artemis is not started.

```
2024-02-02 10:22:41,852 ERROR [com.git.doc.api.asy.ResultCallbackTemplate] (docker-java-stream--623331358) Error during callback: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
ActiveMQ Artemis Dev Services Starting: 2024-02-02 10:22:26,829 INFO  [tc.tes.6.0] (build-9) Pulling docker image: testcontainers/ryuk:0.6.0. Please be patient; this may take some time but only needs to be done on
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Output of `uname -a` or `ver`

Darwin C02FF7XMMD6P 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "21" 2023-09-19 Java(TM) SE Runtime Environment Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)

### Additional information

Docker version 24.0.7, build afdd53b

**Comment by geoand** [comment]
It works fine for me

**Comment by hakuseki** [comment]
Sorry for the cry wolf…
Some issues with .m2

**Comment by geoand** [comment]
👍🏼
