### ISSUE TITLE
Using DBRef raises InvalidDefinitionException

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#38573]
### Describe the bug

Using Quarkus 3.7.1. Here is an excerpt of the domain model:

    @MongoEntity(database = "mdb", collection="Customers")
    public class Customer
    {
      @BsonId
      private Long id;
      private String firstName, lastName;
      ...
    }
    ...
    @MongoEntity(database = "mdb", collection="Orders")
    public class Order
    {
      @BsonId
      private Long id;
      private DBRef customer;
      private Address shippingAddress;
      ...
    }

I'm generating the CRUD associated to this model using the `quarkus-mongodb-rest-data-panache` extension and I'm trying to test it through Swagger. Using the following payload to test the `POST /order` endpoint:

    {
      "id": 0,
      "customer": {
        "id": "0",
        "collectionName": "Customers",
        "databaseName": "mdb"
      },
      "shippingAddress": {
        "street": "string",
        "city": "string",
        "country": "string"
      },
      "billingAddress": {
        "street": "string",
        "city": "string",
        "country": "string"
      },
      "orderItemSet": [
        {
          "id": 0,
          "product": {
            "id": "string",
            "collectionName": "string",
            "databaseName": "string"
          },
          "price": 0,
          "amount": 0
        }
      ]
    }

I get the following exception:

     2024-02-03 17:48:41,996 ERROR [org.jbo.res.plu.pro.jackson] (executor-thread-1) RESTEASY-JACKSON000100: Not able to deserialize data provided: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.mongodb.DBRef` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
      at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 4, column: 5] (through reference chain: fr.simplex_software.docstore.domain.Order["customer"])
            at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
            at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1887)
            at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
            at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1375)
            at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1508)
            at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
            at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
            at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
            at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
            at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
            at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
            at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2099)
            at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1249)
            at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:184)
            at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:99)
            at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:60)
            at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:81)
            at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:192)
            at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:87)
            at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:116)
            at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
           at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
           at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
            at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
            at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
            at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
            at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
            at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
            at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
            at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
            at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
            at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
            at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
            at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
            at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
            at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
            at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
            at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
            at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
            at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
            at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
            at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
            at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base/java.lang.Thread.run(Thread.java:840)
 
What am I doing wrong here ?

**Comment by gsmet** [comment]
My guess is that you would need to register a serializer/deserializer for `DBRef`.

We already did it for ObjectId with JSON-B and Jackson `ObjectIdSerializer`/`ObjectIdDeserializer`.

I think it would be a nice first contribution if you're willing to.

**Comment by nicolasduminil** [comment]
Implementing the mentioned serializer/deserializer components fixed the issue. Many thanks.

**Comment by gsmet** [comment]
I think it would be worth contributing them (with a test) so that we support it out of the box. 

Thanks!
