### ISSUE TITLE
Sort Bug in HQL Query That Has Alias

### ISSUE THREAD

**Issue by yasarmatrac** [quarkusio/quarkus#38581]
### Describe the bug

In HQL queries, if I use 'io.quarkus.panache.common.Sort' with a query that has an alias then the application throws org.hibernate.query.SemanticException.

`Person.find("select distinct p from Person p left join p.roles r",
                Sort.by("p.name")).list()`

The code block creates this following HQL.

`select distinct p from Person p left join p.roles r ORDER BY 'p.name'  `

In 'io.quarkus.panache.hibernate.common.runtime.PanacheJpaUtil.toOrderBy' method causes this exception. In the method, fields are enquoted and HQL couldn't be interpreted.

![image](https://github.com/quarkusio/quarkus/assets/4759385/df7dc3c8-f4a0-492e-b6db-b18ee37341fc)

### Expected behavior

Hql queries that have aliases should be used with sort aliases

### Actual behavior

The application throws the following error.
`java.lang.IllegalArgumentException: org.hibernate.query.SemanticException: Could not interpret path expression 'p.name'
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:143)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:167)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:173)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:848)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:753)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:136)
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.createQuery(TransactionScopedSession.java:367)`

### How to Reproduce?

`Person.find("select distinct p from Person p left join p.roles r",
                Sort.by("p.name")).list()`

### Output of `java -version`

17

### Quarkus version or git rev

3.7.1

**Comment by geoand** [comment]
This looks like an upstream bug, but I'll let @yrodiere and @beikov decide

**Comment by yrodiere** [comment]
Thanks for reporting, but it appears this duplicates #38521 , which will be fixed in 3.7.2.

I'll close this issue, feel free to answer here if you think this is a mistake.
