### ISSUE TITLE
mvn quarkus:remote-dev does not work when quarkus.servlet.context-path specified

### ISSUE THREAD

**Issue by jglick** [quarkusio/quarkus#3862]
**Describe the bug**

I was successfully using `mvn quarkus:remote-dev` until I introduced `quarkus.servlet.context-path` from #2479.

**Expected behavior**

Same as before.

**Actual behavior**

```
…
[INFO] --- quarkus-maven-plugin:0.21.0:remote-dev (default-cli) @ … ---
…/src/main/java
javax.websocket.DeploymentException: Invalid response code 404
	at io.undertow.websockets.jsr.ServerWebSocketContainer.connectToServer(ServerWebSocketContainer.java:338)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.connectToServer(ServerWebSocketContainer.java:309)
	at io.quarkus.remotedev.AgentRunner.run(AgentRunner.java:50)
	at io.quarkus.maven.RemoteDevMojo.execute(RemoteDevMojo.java:134)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.xnio.http.UpgradeFailedException: Invalid response code 404
	at org.xnio.http.HttpUpgrade$HttpUpgradeState$UpgradeResultListener.handleEvent(HttpUpgrade.java:471)
	at org.xnio.http.HttpUpgrade$HttpUpgradeState.flushUpgradeChannel(HttpUpgrade.java:369)
	at org.xnio.http.HttpUpgrade$HttpUpgradeState.access$900(HttpUpgrade.java:165)
	at org.xnio.http.HttpUpgrade$HttpUpgradeState$ConnectionOpenListener.handleEvent(HttpUpgrade.java:340)
	at org.xnio.http.HttpUpgrade$HttpUpgradeState$ConnectionOpenListener.handleEvent(HttpUpgrade.java:320)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.WorkerThread$ConnectHandle.handleReady(WorkerThread.java:333)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
```

**To Reproduce**

Do not have a public project to demonstrate the difference on at the moment. Can try to construct one upon request.

**Configuration**
```properties
quarkus.live-reload.password=…
quarkus.live-reload.url=http://127.0.0.1.xip.io/somename
quarkus.servlet.context-path=/somename
```

where an `Ingress` has been configured in Microk8s, so that I can in fact use that URL for other purposes. (I also tried stripping off the context path from the `quarkus.live-reload.url`; same error.)

**Screenshots**

N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux … 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`:
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~19.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```
 - GraalVM version (if different from Java): N/A (not used in this mode)
 - Quarkus version or git rev: 0.21.0

**Additional context**
N/A

**Comment by fabricepipart1a** [comment]
Is there any news on this topic? I have the impression that I am facing the exact same issue (with Quarkus 1.2.1).
Is there any known workaround?

**Comment by jglick** [comment]
For my part I just ran into enough issues with custom context paths that I ceased to use this feature and began interpreting the full URI directly in my resources.

**Comment by stuartwdouglas** [comment]
The remote dev mode in 1.6 is completely new, this should not be an issue.
