### ISSUE TITLE
dev mode error with multiple application properties profiles

### ISSUE THREAD

**Issue by jeremyrdavis** [quarkusio/quarkus#3863]
**Describe the bug**
I have both "%dev" and "%test" profiles in my application properties.  Making a simple change results in errors being thrown.  I've gotten a couple of different errors, but they all reference the datasource.

**Expected behavior**
I expect quarkus:dev to work as usual and reload on code changes

**Actual behavior**
I got the following error by simply changing text returned from an endpoint.  I built a sample project: https://github.com/jeremyrdavis/datasource-configuration-bug

I simply changed the default text in HelloResource.

`java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.ConfigurationSetup#initializeConfiguration threw an exception: java.util.NoSuchElementException: Property quarkus.datasource.max-size not found
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:141)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
	at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:195)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:116)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup.handleHotDeploymentRequest(UndertowHotReplacementSetup.java:72)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup$1$1.handleRequest(UndertowHotReplacementSetup.java:61)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:224)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.ConfigurationSetup#initializeConfiguration threw an exception: java.util.NoSuchElementException: Property quarkus.datasource.max-size not found
	at io.quarkus.builder.Execution.run(Execution.java:108)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:121)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:115)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:107)
	... 18 more
Caused by: java.util.NoSuchElementException: Property quarkus.datasource.max-size not found
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:89)
	at io.quarkus.deployment.steps.ConfigurationSetup.initializeConfiguration(ConfigurationSetup.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:768)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	... 2 more`

**To Reproduce**
1. Clone https://github.com/jeremyrdavis/datasource-configuration-bug
2. mvn compile quarkus:dev
3. change the text in HelloResource and reload the browser

**Configuration**
```properties
# Add your application.properties here, if applicable.
# Configuration file
# key = value
%dev.quarkus.datasource.url=jdbc:h2:./dev-db/dev
%dev.quarkus.datasource.driver=org.h2.Driver
%dev.quarkus.datasource.username=username-default
%dev.quarkus.datasource.min-size=3
%dev.quarkus.datasource.max-size=13

# drop and create the database at startup (use `update` to only update the schema)
%dev.quarkus.hibernate-orm.database.generation = drop-and-create

%test.quarkus.datasource.url=jdbc:h2:./test-db/test
%test.quarkus.datasource.driver=org.h2.Driver
%test.quarkus.datasource.username=username-default
%test.quarkus.datasource.min-size=3
%test.quarkus.datasource.max-size=13

# drop and create the database at startup (use `update` to only update the schema)
%test.quarkus.hibernate-orm.database.generation = drop-and-create

```

**Screenshots**

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin fuzzface 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 0.21.1

**Additional context**
(Add any other context about the problem here.)

**Comment by jamesfalkner** [comment]
FWIW I get the same with mongodb.

works:

`quarkus.mongodb.connection-string=mongodb://localhost:27017`

fails:

`%dev.quarkus.mongodb.connection-string=mongodb://localhost:27017` 

with

```
2019-09-05 12:40:39,591 ERROR [io.qua.dev.DevModeMain] (executor-thread-1) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.steps.ConfigurationSetup#initializeConfiguration threw an exception: java.util.NoSuchElementException: Property quarkus.mongodb.connection-string not found
```

**Comment by machi1990** [comment]
@jeremyrdavis @jamesfalkner thanks for reporting this issue. I was able to reproduce this with `0.21.1` but not with `0.21.2` which was released a few days ago to address several bug. Can you try with that version and confirm if it the issue is fixed? Thanks.

**Comment by jamesfalkner** [comment]
Confirmed it works again with `0.21.2` !

**Comment by machi1990** [comment]
Glad it worked for you. This can be closed then.
