### ISSUE TITLE
quarkus-mongodb-rest-data-panache: DBRefCodec does not support decoding

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#38743]
### Describe the bug

Using Quarkus 3.7.1 with the `quarkus-mongodb-rest-data-panache` extension, I'm persisting data into a MongoDB database. I have the following `Document`:

    @MongoEntity(database = "mdb", collection="OrderItems")
    public class OrderItem
    {
      @BsonId
      private Long id;
      private DBRef product;
      private BigDecimal price;
      private int amount;
      ....
    }

The associated repository looks as follows:

    @ApplicationScoped
    public class OrderItemRepository implements PanacheMongoRepositoryBase<OrderItem, Long> {}

and I'm generating the REST resource using the `quarkus-mongodb-rest-data-panache` extension:

    public interface OrderItemResource extends PanacheMongoRepositoryResource<OrderItemRepository, OrderItem, Long> {}

After having inserted the `Document` shown in the attached screen copy of Mongo Express, I'm tryin to query it, in an integration test:

    ...
    given()
      .header("Content-type", "application/json")
      .when().get("/order-item")
      .then()
      .statusCode(HttpStatus.SC_OK);
    ....

Then I'm getting th exception below:

    ...
    Caused by: java.lang.UnsupportedOperationException: DBRefCodec does not support decoding
        at com.mongodb.DBRefCodec.decode(DBRefCodec.java:66)
        at com.mongodb.DBRefCodec.decode(DBRefCodec.java:33)
        at org.bson.codecs.pojo.LazyPropertyModelCodec.decode(LazyPropertyModelCodec.java:52)
        at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
        at org.bson.codecs.pojo.PojoCodecImpl.lambda$decodePropertyModel$2(PojoCodecImpl.java:212)
        at org.bson.codecs.pojo.PojoCodecImpl.setPropertyValue(PojoCodecImpl.java:234)
        at org.bson.codecs.pojo.PojoCodecImpl.decodePropertyModel(PojoCodecImpl.java:202)

Not sure whether it has anything to do with the DBRef serializers/deserializers:

    public class JacksonDBRefDeserializer extends StdDeserializer<DBRef>
    {
      public JacksonDBRefDeserializer()
      {
        this(null);
      }

      public JacksonDBRefDeserializer(Class<DBRef> dbrefClass)
      {
        super(dbrefClass);
      }

      @Override
      public DBRef deserialize(JsonParser jsonParser, DeserializationContext deserializationContext) throws IOException, JacksonException
      {
        JsonNode node = jsonParser.getCodec().readTree(jsonParser);
        return new DBRef(node.findValue("databaseName").asText(), node.findValue("collectionName").asText(), node.findValue("id").asText());
      }
    }

    public class JaksonDBRefSerializer extends StdSerializer<DBRef>
    {
      public JaksonDBRefSerializer()
      {
        this(null);
      }

      protected JaksonDBRefSerializer(Class<DBRef> dbrefClass)
      {
        super(dbrefClass);
      }

      @Override
      public void serialize(DBRef dbRef, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException
      {
        if (dbRef != null)
        {
          jsonGenerator.writeStartObject();
          jsonGenerator.writeStringField("id", (String)dbRef.getId());
          jsonGenerator.writeStringField("collectionName", dbRef.getCollectionName());
          jsonGenerator.writeStringField("databaseName", dbRef.getDatabaseName());
          jsonGenerator.writeEndObject();
        }
      }
    }

### Expected behavior

Getting the `Document`.

### Actual behavior

The mentioned exception is raised.

### How to Reproduce?

Don't have a reproducer.

### Output of `uname -a` or `ver`

Linux P15s-Gen-2i 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.8" 2023-07-18 LTS Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211) Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

pache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /usr/share/apache-maven-3.9.6 Java version: 17.0.8, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-17-oracle-x64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-94-generic", arch: "amd64", family: "unix"

### Additional information

Attaching a screen copy showing a fragment of the Mongo Express display.
![Screenshot_20240213_003429](https://github.com/quarkusio/quarkus/assets/1037978/858d79ad-c696-418e-a45e-cf4917f9c08f)

**Comment by gsmet** [comment]
Probably something to add to `MongoClients#configureCodecRegistry()`. From what I can see, producing a `DBRefCodecProvider`  as a CDI bean should be a valid workaround.

As I said in the other issue, I would recommend contributing fixes so that it's handled out of the box from now on.

**Comment by loicmathieu** [comment]
Hi,
It seems that the PojoCodec, the MongoDB codec used to serialize an object in BSON before storing it in MongoDB, didn't support decoding DBRef.

I found [this question](https://www.mongodb.com/community/forums/t/dbrefcodec-does-not-support-decoding/219783) in the MongoDB forum and [this one](https://stackoverflow.com/questions/72007813/dbref-resolution-is-not-supported) in StackOverflow.

As I understand it, DBRef is not designed to be used as is with the MongoDB driver. The idea is to be able to store a reference to another document (what is close to a foreign key in MongoDB) and when retrieving the DBRef, load the referenced document. 

We already discussed this with @evanchooly and will not provide loading referenced documents inside MongoDB with Panache, Morphia did this as it is an object document mapper, and there is a Morphia extension.

However, what we can do is, as @gsmet suggest, override the default DBRef codec to provide a codec that will decode the DBRef (without loading the associated document). And as already discussed in an other issue, we also can provide a Jackson Serializer/Deserializer.

If we do this we should clearly document that the DBRef object is supported but not automatically loading referenced documents into an associated object field.

**Comment by nicolasduminil** [comment]
@loicmathieu : thanks for these explanations but, unfortunately, they don't help in solving my issue. Waiting that you to decide what the best strategy in fixing it would be, what can I do in order to implement my use case ? Using Morphia ? Or perhaps simply getting back to Spring Data which perfectly supports DBRef via annotations ?

By the way, I'm not sure what am I supposed to do with the links you provided, since the first one isn't even answered, while the 2nd one doesn't have anything to do with any Quarkus extension, but with Spring Data.

Thank you anyway for your time.

Kind regards,
Nicolas

**Comment by nicolasduminil** [comment]
@gsmet : Looking in the mentioned class (`DBRefCodec`), I can see that:

      ...
      public DBRef decode(BsonReader reader, DecoderContext decoderContext) {
        throw new UnsupportedOperationException("DBRefCodec does not support decoding");
      }

Is that normal ? I'm not sure to understand as, either this class fully implements the `Codec<?>` interface, or it doesn't implement it at all, but implementing only the half of it is quite surprising. 

So, what would one be supposed to do here ? To contribute with the missing half implementation ? Or simply replacing the current implementation with another one ? Both alternatives are possible but this doesn't help to dispel my surprise seeing that this class, supposed to provide an implementation of the `Codec<?>` interface, throws `UnsuportedOperationException`.

At the risk to repeat myself, I would like to mention again that Spring Data fully supports `@DBRef` annotations as a way to model connections, if not relationships, between different `Document` instances, possibly located in different databases. And, in my opinion, what users are expecting from Panache, as a Spring Data heir, is to support at least the same features and functionalities.

**Comment by evanchooly** [comment]
spring-data is an object mapper.  it's a fully realized library providing a whole swath of functionality.  mongodb-panache is a decorator layer for querying via the driver.  it was never intended to be a fully featured ODM.  Simply to provide a convenience layer for nicer queries.  For ODM features, systems like spring-data and morphia exist to provide those more advanced features.  IMO, mongodb-panache isn't the place for such things.

**Comment by loicmathieu** [comment]
@nicolasduminil the DBRefCodec is from the MongoDB driver, this is the default way the driver decode the DBRef.

> To contribute with the missing half implementation ? 

It's possible but it must be contributed upstream on the MongoDB driver, and there may be legitimate reasons it is like that.

> Or simply replacing the current implementation with another one ?

You can do that by providing your own codec, it will be automatically discovered by MongoDB with Panache. We can then decide if we want to include it by default inside MongoDB with Panache (but again, just to decode a DBRef not to resolve it to the referenced document/attribute).

**Comment by nicolasduminil** [comment]
@evanchooly : 

> `mongodb-panache` is a decorator layer for querying via the driver. it was never intended to be a fully featured ODM.

However, `quarkus-hibernate-orm-panache` is an ODM and one expect the same as far as `mongodb-panache` is concerned.

> ... systems like spring-data and morphia exist ...

The `spring-data-jpa` extension doesn't support MongoDB, neither any other NoSQL databases. As for `morphia`, it doesn't support Panache like patterns as active record or repository.

Have had a look at Jakarta Data and Jakarta NoSQL but it doesn't seem to provide any annotation for aggregations. So, we don't have much choice any more other than going the hard way with the MongoDB driver, exactly like we used to do 20 years ago with SQL ! :-(

**Comment by maxandersen** [comment]
> > ... I'm terribly busy ...
> 
> Good for you. I can understand that but, I wonder whether a contributor, who doesn't have the time to contribute, is still a contributor ? :-).

@nicolsduminil I appreciate you providing feedback and input but please note that @evanchooly is very much a contributor to Quarkus. 

It's our collective contributions, whether big or small, that shape the success of this project. Every bit of effort, whenever possible, is valuable and appreciated. We all have periods where our availability varies, and that's perfectly okay. 

What matters is the spirit of collaboration and support we foster within our community. If there's ever a time when you find a moment to contribute code, know that your contributions will be just as welcomed with open arms and respect.

If you feel there are features missing do please ask, and if you feel the answers are insufficient do consider contributing fixes or maybe in this case add a separate extension to handle your usecase. 

In all cases, let us not speak to anyone in a discouraging tone - especially not to those who actually wrote and contributed the code you are already using.

Thank you!

**Comment by nicolasduminil** [comment]
@maxandersen I've tried to attach some sense to your comments but I failed 'cause I find them are completely off the mark.

**Comment by evanchooly** [comment]
`DBRef` support is orthogonal to the active record pattern. The driver treats `DBRef`s as simple values and attaches no special logic or significance to them. In fact, their use is even discouraged as that pattern isn't exactly idiomatic to how mongodb is intended to be used.  The fact that the `DBRefCodec` doesn't decode them is not a quarkus issue and should be taken up with the driver team.  `quarkus-morphia` is indeed lagging because I'm trying to get pieces in place in `morphia` itself to make proper support much more feasible. That takes time and effort apart from what I already spend on my day job which is utterly unrelated. I do such work when I can and as rapidly as I can and it's not for you or anyone to pass judgement on that.

If one is willing to contribute code, then everyone is welcome. But if your only contribution is to cast aspersions then I really don't have time for you.  It's open source.  You can contribute or not but you absolutely have no claim on anyone's time to provide anything. 

Patches are welcome.  Tantrums are not.  Choose appropriately.

**Comment by maxandersen** [comment]
> @maxandersen I've tried to attach some sense to your comments but I failed 'cause I find them completely off the mark.

Thank you for your honesty, @nicolasduminil. I understand that my response might not have aligned with your expectations, and that's perfectly okay. We all approach situations with different perspectives. It can sometimes be hard to be sure what is behind written text on an issue. Sounds like you see it as completely fine to question a contributor's earned right to be a contributor - you might even have meant it as a casual joke. If that is all you did, excellent - just be aware that more than just I found your comments quite discouraging. You can ignore that information or take that into consideration for future comments. Thank you.
