### ISSUE TITLE
 java.lang.NoSuchFieldError: Class io.netty.handler.codec.http.HttpHeaderNames does not have member field 'io.netty.util.AsciiString ACCESS_CONTROL_ALLOW_PRIVATE_NETWORK'

### ISSUE THREAD

**Issue by maxlam79** [quarkusio/quarkus#38746]
### Describe the bug

Hi,

I came across this error when migrating my codes to from previous Quarkus version to 3.7.2.

I hit this when I run:
```
./mvnw quarkus:dev
```

```
2024-02-13 10:42:31,838 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoSuchFieldError: Class io.netty.handler.codec.http.HttpHeaderNames does not have member field 'io.netty.util.AsciiString ACCESS_CONTROL_ALLOW_PRIVATE_NETWORK'
        at io.vertx.core.http.HttpHeaders.<clinit>(HttpHeaders.java:107)
        at io.vertx.ext.web.client.impl.WebClientBase.buildHeaders(WebClientBase.java:171)
        at io.vertx.ext.web.client.impl.WebClientBase.requestAbs(WebClientBase.java:139)
        at io.vertx.ext.web.client.WebClient.requestAbs(WebClient.java:250)
        at io.vertx.ext.web.client.WebClient.getAbs(WebClient.java:350)
        at io.vertx.mutiny.ext.web.client.WebClient.getAbs(WebClient.java:449)
        at io.quarkus.oidc.common.runtime.OidcCommonUtils.discoverMetadata(OidcCommonUtils.java:437)
        at io.quarkus.oidc.runtime.OidcRecorder.createOidcClientUni(OidcRecorder.java:484)
        at io.quarkus.oidc.runtime.OidcRecorder.createOidcProvider(OidcRecorder.java:375)
        at io.quarkus.oidc.runtime.OidcRecorder.createTenantContext(OidcRecorder.java:321)
        at io.quarkus.oidc.runtime.OidcRecorder.createStaticTenantContext(OidcRecorder.java:144)
        at io.quarkus.oidc.runtime.OidcRecorder.setup(OidcRecorder.java:85)
        at io.quarkus.deployment.steps.OidcBuildStep$setup635434700.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.OidcBuildStep$setup635434700.deploy(Unknown Source)
        ... 11 more
```

Seems like the OIDC component is causing some issues. I do have these dependency:
```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-oidc</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-keycloak-authorization</artifactId>
</dependency>
```

Help needed. Thank you.

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS

### Quarkus version or git rev

3.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by gsmet** [comment]
Thanks for the report. Do you enforce the Netty version? Which version of Netty do you have in your classpath?

**Comment by gsmet** [comment]
(If you just updated Quarkus, a `mvn clean` might help)

**Comment by maxlam79** [comment]
Thanks for the pointers. I did not deliberately have any io.netty stuff as one of the dependencies. But I believe you have given me some pointers to look at where some other dependencies might have trigger this conflicting.

Yes, I have used ./mvnw clean quarkus:dev but to no avail.

Anyway, here are the dependencies which I have included in my pom.xml (minus the versions as I'm using an external BOM):
```
<dependencies>

        <!-- Quarkus -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-oidc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-keycloak-authorization</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jsonb</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-reactive-panache</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-keycloak-admin-client-reactive</artifactId>
        </dependency>

        <!-- Others -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>com.cloudinary</groupId>
            <artifactId>cloudinary-http44</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ooxi</groupId>
            <artifactId>jdatauri</artifactId>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

**Comment by gsmet** [comment]
Thanks for reporting back :).
