### ISSUE TITLE
Multipart form data is interpreted as a file although it's not a file

### ISSUE THREAD

**Issue by chutzemischt** [quarkusio/quarkus#38802]
### Describe the bug

If multipart form data is not a file and specified with other MIME-Type than `text/plain`, quarkus tries to parse form data as a file, which leads to a NullPointerException.

Was introduced in quarkus 3.7.3 with this change: https://github.com/quarkusio/quarkus/pull/38714

### Expected behavior

Multipart form data is parsed with correct content type.

### Actual behavior

Multipart form data other than `text/plain` is parsed as File.

Request:

```
Hypertext Transfer Protocol
MIME Multipart Media Encapsulation, Type: multipart/form-data, Boundary: "5vI261AD6aFM_WL55jbNMpcLal_Lzt2uTnRW"
    [Type: multipart/form-data]
    First boundary: --5vI261AD6aFM_WL55jbNMpcLal_Lzt2uTnRW\r\n
    Encapsulated multipart part:  (application/json)
        Content-Disposition: form-data; name="firstParam"\r\n
        Content-Type: application/json; charset=US-ASCII\r\n
        Content-Transfer-Encoding: 8bit\r\n\r\n
        JavaScript Object Notation: application/json
    Last boundary: \r\n--5vI261AD6aFM_WL55jbNMpcLal_Lzt2uTnRW--\r\n
```

Exception:

```
2024-02-15 15:58:14,745 DEBUG [WebApplicationException] (executor-thread-1) Restarting handler chain for exception exception: jakarta.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:66)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:137)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.nio.file.Files.readString(Files.java:3343)
	at org.jboss.resteasy.reactive.server.core.multipart.MultipartSupport.getString(MultipartSupport.java:204)
	at org.jboss.resteasy.reactive.server.core.parameters.MultipartFormParamExtractor.extractParameter(MultipartFormParamExtractor.java:46)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:45)
	... 9 more
```

### How to Reproduce?

I've made a reproducer: https://github.com/chutzemischt/quarkus-multipart-reproducer

```java
@Path("/api")
public class MyTestController {

    @Path("test")
    @POST
    public Response testMultipart(@FormParam("firstParam") final String firstParam, @FormParam("secondParam") final String secondParam) {
        return Response.ok().build();
    }
}
```

```java
@QuarkusTest
class MyTestControllerTest {

    @Test
    void testMultipart() {
        given().multiPart("firstParam", "{\"id\":\"myId\",\"name\":\"myName\"}", "application/json")
                .when()
                .post("/api/test")
                .then()
                .statusCode(200);
    }
}
```

### Output of `java -version`

21.0.1

### Quarkus version or git rev

3.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

**Comment by geoand** [comment]
Thanks, 

I'll have a look tomorrow
