### ISSUE TITLE
Kafka reactive messaging extension incompatible with Micrometer Prometheus extension for Quarkus 3.7.*

### ISSUE THREAD

**Issue by jasmdk** [quarkusio/quarkus#38889]
### Describe the bug

The error occurs when an incomming channel expects an io.smallrye.reactive.messaging.kafka.IncomingKafkaRecord class, it will then fail when processing the event with a ClassCastException.
The error only occurs with Quarkus 3.7.*, but not with 3.6.9 and it only occurs if the following extension is added to the pom.xml file:
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
    </dependency>

### Expected behavior

I would expect to be able to consume messages using the IncomingKafkaRecord interface as it worked before.

### Actual behavior

2024-02-20 12:15:17,532 ERROR [io.sma.rea.mes.provider] (executor-thread-1) SRMSG00200: The method org.acme.MessagePersister#persist has thrown an exception [Error Occurred After Shutdown]: java.lang.ClassCastException: class org.eclipse.microprofile.reactive.messaging.Message$5 cannot be cast to class io.smallrye.reactive.messaging.kafka.IncomingKafkaRecord (org.eclipse.microprofile.reactive.messaging.Message$5 and io.smallrye.reactive.messaging.kafka.IncomingKafkaRecord are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @615091b8)
	at org.acme.MessagePersister_SmallRyeMessagingInvoker_persist_fe0067080e13a99e2bb405470f8a6aa5945227cc.invoke(Unknown Source)
	at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeBlocking$15(AbstractMediator.java:190)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:36)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
	at io.vertx.mutiny.core.Context$1.handle(Context.java:172)
	at io.vertx.mutiny.core.Context$1.handle(Context.java:170)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:190)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:276)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:209)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### How to Reproduce?

[getting-started.zip](https://github.com/quarkusio/quarkus/files/14345520/getting-started.zip)
Small maven project attached with an incomming channel expecting KafkaIncomingRecord and a test which writes to the same kafka topic using an outgoing channel.

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19044 pc-9274 3.1.7-340.x86_64 2021-10-12 16:29 UTC x86_64 Msys

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS OpenJDK Runtime Environment Zulu21.32+17-CA (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Zulu21.32+17-CA (build 21.0.2+13-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)

**Comment by cescoffier** [comment]
Yes, it should have been fixed. Do you have a reproducer?
