### ISSUE TITLE
java.security.cert.CertificateException when connecting to SSL-enabled MongoDB from native app

### ISSUE THREAD

**Issue by jamesfalkner** [quarkusio/quarkus#3889]
**Describe the bug**
I am using the MongoDB quickstart to connect to an ssl-enabled MongoDB server. When I do this from a JVM-based app it works. Same code, but compiled to native fails.

This is my connection string in `application.properties`:

`quarkus.mongodb.connection-string=mongodb://[redacted]@[redacted]:10255/?ssl=true&replicaSet=globaldb`

**Expected behavior**
No errors, connection successful, everything works

**Actual behavior**
When I run the JVM-based image using:
```
git clone https://github.com/quarkusio/quarkus-quickstarts
cd using-mongodb-client
# [insert my connection string in `src/main/resources/application.properties`] 
mvn clean package
java -jar target/mongo-client-1.0-SNAPSHOT-runner.jar
```
 it works fine and I can access `http://localhost:8080/fruits`. When I build a native image with `mvn clean package -Pnative` and run it, I immediately get:

```
➜  using-mongodb-client git:(master) ✗ target/mongo-client-1.0-SNAPSHOT-runner
2019-09-05 14:08:01,211 INFO  [org.mon.dri.cluster] (main) Cluster created with settings {hosts=[**REDACTED**:10255], mode=MULTIPLE, requiredClusterType=REPLICA_SET, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500, requiredReplicaSetName='globaldb'}
2019-09-05 14:08:01,211 INFO  [org.mon.dri.cluster] (main) Adding discovered server **REDACTED**:10255 to client view of cluster
2019-09-05 14:08:01,211 INFO  [org.mon.dri.cluster] (main) Cluster created with settings {hosts=[**REDACTED**:10255], mode=MULTIPLE, requiredClusterType=REPLICA_SET, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500, requiredReplicaSetName='**REDACTED**'}
2019-09-05 14:08:01,211 INFO  [org.mon.dri.cluster] (main) Adding discovered server **REDACTED**:10255 to client view of cluster
2019-09-05 14:08:01,213 INFO  [io.quarkus] (main) Quarkus 0.21.2 started in 0.008s. Listening on: http://[::]:8080
2019-09-05 14:08:01,213 INFO  [io.quarkus] (main) Installed features: [cdi, mongodb-client, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-reactive-streams-operators, vertx]
2019-09-05 14:08:01,489 INFO  [org.mon.dri.cluster] (cluster-ClusterId{value='**REDACTED**', description='null'}-**REDACTED**:10255) Exception in monitor thread while connecting to server **REDACTED**:10255: com.mongodb.MongoSocketWriteException: Exception sending message
	at com.mongodb.internal.connection.InternalStreamConnection.translateWriteException(InternalStreamConnection.java:541)
	at com.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:429)
	at com.mongodb.internal.connection.InternalStreamConnection.sendCommandMessage(InternalStreamConnection.java:269)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:253)
	at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:83)
	at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:33)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:105)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:62)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:127)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address **REDACTED** found
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:750)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at com.mongodb.internal.connection.SocketStream.write(SocketStream.java:99)
	at com.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:426)
	... 11 more
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address **REDACTED** found
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:168)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:94)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:461)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:442)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:208)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 20 more
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin jfalkner-OSX 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

and `curl http://localhost:8080/fruits` hangs.

 - Output of `java -version`: 

```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
 - GraalVM version (if different from Java): 

`GraalVM Version 19.1.1 CE`

 - Quarkus version or git rev: 

0.21.2

**Additional context**

If I add 

```
quarkus.mongodb.tls=true
quarkus.mongodb.tls-insecure=true
```

to my `application.properties`, it works in native mode (but is not a secure solution)

**Comment by jaikiran** [comment]
It looks to me, the MongoDB server is presenting a cert which doesn't match the IP address to which you are connecting to. Can you change your mongo DB connection URL (quarkus.mongodb.connection-string=mongodb://[redacted]@[redacted]:10255/?ssl=true&replicaSet=globaldb) to use a hostname instead of an IP address?

**Comment by ppatz-vendavo** [comment]
hi, I just found this issue when googling for my problem. We are not using quarkus but having same issue - with plain MongoClient and native image. We use Atlas MongoDb hosting (which uses ssl connections by default), our connection string contains host names but when trying to connect, we get the same error message talking about IP addresses - so it looks more like mongodb vs native-image issue. generic workaround for this is to enable sslSettings.invalidHostNameAllowed option (but, as mentioned, it's not secure)

**Comment by geoand** [comment]
Is this still an issue in the latest versions of Quarkus?
