### ISSUE TITLE
Postgresql bump causing detection of instance Random/SplittableRandom

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#38949]
### Describe the bug

QE testsuite start failing after the https://github.com/quarkusio/quarkus/pull/38909. The new version adding `PasswordUtil` class which have `SecureRandom` attribute, see PR https://github.com/pgjdbc/pgjdbc/pull/3082

Error log:
```
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=java.security.SecureRandom'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  trying to constant fold static field org.postgresql.util.PasswordUtil$SecureRandomHolder.INSTANCE
    at org.postgresql.util.PasswordUtil.getSecureRandom(PasswordUtil.java:34)
  parsing method org.postgresql.util.PasswordUtil.getSecureRandom(PasswordUtil.java:34) reachable via the parsing context
    at static root method.(Unknown Source)


com.oracle.svm.core.util.UserError$UserException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=java.security.SecureRandom'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  trying to constant fold static field org.postgresql.util.PasswordUtil$SecureRandomHolder.INSTANCE
    at org.postgresql.util.PasswordUtil.getSecureRandom(PasswordUtil.java:34)
  parsing method org.postgresql.util.PasswordUtil.getSecureRandom(PasswordUtil.java:34) reachable via the parsing context
    at static root method.(Unknown Source)


        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:814)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use 

    '--trace-object-instantiation=java.security.SecureRandom'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  trying to constant fold static field org.postgresql.util.PasswordUtil$SecureRandomHolder.INSTANCE
    at org.postgresql.util.PasswordUtil.getSecureRandom(PasswordUtil.java:34)
  parsing method org.postgresql.util.PasswordUtil.getSecureRandom(PasswordUtil.java:34) reachable via the parsing context
    at static root method.(Unknown Source)


        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:809)
        ... 6 more
```

### Expected behavior

Compile to native as it was possible with version 42.7.1

### Actual behavior

Fail to compile to native.

### How to Reproduce?

Need latest version of Quarkus main branch

1. `git clone https://github.com/quarkus-qe/quarkus-test-suite.git`
2. `cd quarkus-test-suite`
3. `mvn clean verify -Psql-db-modules -pl sql-db/narayana-transactions -Dreruns=0 -Dit.test="PostgresqlTransactionGeneralUsageIT*" -Dnative`

### Quarkus version or git rev

main

**Comment by Serkan80** [comment]
I also noticed this yesterday. 

After bumping postgres to 42.7.1, we got errors with setting blobs. Now, I've downgraded to 42.6.1. 

The problem is also present in 42.7.0.

**Comment by gsmet** [comment]
@jedla97 do you have any idea why the core tests didn't catch it? I checked the PR, the tests were executed and I don't see them failing with this issue.

**Comment by gsmet** [comment]
@zakkak creating a `RuntimeReinitializedClassBuildItem` for https://github.com/pgjdbc/pgjdbc/pull/3082/files#diff-4a86a9f2f0d5eef4636059fe34d7510c3ea493c87cee72d4e438916d3354d753R31-R33 should work, right?

**Comment by jedla97** [comment]
> do you have any idea why the core tests didn't catch it? I checked the PR, the tests were executed and I don't see them failing with this issue.
@gsmet sorry not at the moment I tried create simple reproducer but wasn't able. But we have this issue only in Narayana modul so I think that can be reason why it was not catched because all other sql module passing without fail.

**Comment by gsmet** [comment]
@Serkan80 are you sure it's the same error? I would be surprised if blobs were using a password util. What's your error exactly?

**Comment by zakkak** [comment]
> @zakkak creating a `RuntimeReinitializedClassBuildItem` for https://github.com/pgjdbc/pgjdbc/pull/3082/files#diff-4a86a9f2f0d5eef4636059fe34d7510c3ea493c87cee72d4e438916d3354d753R31-R33 should work, right?

Yes, that should do the trick.

**Comment by gsmet** [comment]
@jedla97 could you check if https://github.com/quarkusio/quarkus/pull/38958 fixes the issue for you?

**Comment by jedla97** [comment]
@gsmet I tested it and it's working. Thanks for quick fix!
