### ISSUE TITLE
Unable to build a container with Jib when podman is running

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#38961]
### Describe the bug

When building an image with Jib, and podman is running, I get:

```
ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.7.2:build (default) on project crud-example: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]     [error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
[ERROR]     at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:270)
[ERROR]     at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:195)
[ERROR]     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR]     at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR]     at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR]     at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]     at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]     at java.base/java.lang.Thread.run(Thread.java:1570)
[ERROR]     at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.util.concurrent.ExecutionException: java.io.IOException: 'docker load' command failed with error: Cannot connect to the Docker daemon at unix:///Users/clement/.docker/run/docker.sock. Is the docker daemon running?
```

The podman machine is running and works correctly.

The reproducer is: https://github.com/quarkusio/virtual-threads-demos/tree/main/crud-example (mvn package -DskipTests)

### How to Reproduce?

Checkout https://github.com/quarkusio/virtual-threads-demos/tree/main/crud-example

`mvn clean package`.

**Comment by geoand** [comment]
I've never tried podman, but I guess I'll have to :)

**Comment by geoand** [comment]
Okay, I can reproduce this issue by doing what is described [here](https://podman-desktop.io/docs/migrating-from-docker/using-the-docker_host-environment-variable).

**Comment by geoand** [comment]
But that actually does not look like a Jib specific issue, because even in this case, when you do `docker ps` you get:

```
Cannot connect to the Docker daemon at unix://run/user/1000/podman/podman.sock. Is the docker daemon running?
```

**Comment by cescoffier** [comment]
So, @n1hility found the issue.

I also have docker installed, and I have 2 contexts:

```
> docker context list
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                 KUBERNETES ENDPOINT   ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock
desktop-linux *     moby                Docker Desktop                            unix:///Users/clement/.docker/run/docker.sock
```

You need to switch to _default_ and then it works:

```
> docker context use default
default
Current context is now "default"
```

**Comment by geoand** [comment]
Interesting, thanks
