### ISSUE TITLE
GRPC server doesn't respond when running on the same server as HTTP and using TLS

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#38965]
### Describe the bug

I have an application, which serves both HTTP(s) and GRPC traffic and have two endpoints: "api/http/" and "api/grpc", the former responds directly and the latter returns data from GRPC server in the same application.

When I run GRPC on a separate server (using legacy option `quarkus.grpc.server.use-separate-server=true`) the app works as expected, whenever I run GRPC with or without TLS.
When I run GRPC on the same server as HTTP(s) without using TLS, it also works as expected.
But, when I run GRPC and HTTP(s) on the same server and use TLS for grpc, the server is not available to clients.

### Expected behavior

GRPC server is available

### Actual behavior

Quarkus client fails to connect with this exception:
```
2024-02-22 16:21:00,469 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /api/grpc/world failed, error id: 25a9a835-c112-4498-b0da-aa2a2d17f7ec-1: io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.quarkus.grpc.runtime.supports.IOThreadClientInterceptor$1$1.lambda$onClose$3(IOThreadClientInterceptor.java:70)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:276)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:258)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:56)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
Netty client fails to connect with this one:
```
java.util.concurrent.ExecutionException: 
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:594)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:573)
	at io.quarkus.ts.http.tls.TLSIT.grpcTLSServer(TLSIT.java:67)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 485454502f312e30203430302042616420526571756573740d0a636f6e74656e742d6c656e6774683a20300d0a0d0a
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1314)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

```

### How to Reproduce?

1. `git clone git@github.com:fedinskiy/reproducer.git -b grpc-tls-same-server`
2. `cd reproducer`
3. `mvn quarkus:dev -Dquarkus.grpc.clients.plain.port='${quarkus.http.port}' -Dquarkus.grpc.server.use-separate-server=false -Dquarkus.grpc.clients.plain.ssl.trust-store=tls/ca.pem -Dquarkus.grpc.server.ssl.certificate=tls/server.pem -Dquarkus.grpc.server.ssl.key=tls/server.key`
4.  Open https://localhost:8443/api/http/world — it works
5.  Open https://localhost:8443/api/grpc/world — there is an error on page and in quarkus logs

Endpoint https://localhost:8443/api/grpc/world  is accessible, if you use one of the following commands in p. 3 instead:
1. `mvn quarkus:dev -Dquarkus.grpc.clients.plain.port='${quarkus.grpc.server.port}' -Dquarkus.grpc.server.use-separate-server=true # separate server, no TLS`
2. `mvn quarkus:dev -Dquarkus.grpc.clients.plain.port='${quarkus.http.port}' -Dquarkus.grpc.server.use-separate-server=false # same server, no TLS`
3. `mvn quarkus:dev -Dquarkus.grpc.clients.plain.port='${quarkus.grpc.server.port}' -Dquarkus.grpc.server.use-separate-server=true -Dquarkus.grpc.clients.plain.ssl.trust-store=tls/ca.pem -Dquarkus.grpc.server.ssl.certificate=tls/server.pem -Dquarkus.grpc.server.ssl.key=tls/server.key # separate server, TLS`

The behaviour is the same if I remove both `quarkus.http.ssl.certificate.` options  from application.properties and access the endpoint over HTTP

### Output of `uname -a` or `ver`

6.7.3-200.fc39.x86_64

### Output of `java -version`

Java version: 21.0.1, vendor: Eclipse Adoptium

### Quarkus version or git rev

3,7,3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by alesj** [comment]
I think you're targeting wrong port at (3) ... `${quarkus.http.port}` ... it should be https port.
@cescoffier ^ ?

**Comment by fedinskiy** [comment]
@alesj see the last sentence in reproducer. This issue happens even when I use http instead of https.

**Comment by fedinskiy** [comment]
@alesj hmm, it looks like replacing ` -Dquarkus.grpc.clients.plain.port='${quarkus.http.port}'` with `-Dquarkus.grpc.clients.plain.port='${quarkus.http.ssl-port}'` helps against this malady, but that also means, that we cannot run encrypted grpc and unecrypted HTTP n the same server. Is that correct?

**Comment by cescoffier** [comment]
Yes, as you use the same server, it's all or nothing. If you enable HTTPS, you cannot use plain-text gRPC (and the opposite).

**Comment by fedinskiy** [comment]
According to the comments above, this works as expected.

Thank you, guys!
