### ISSUE TITLE
gradlew quarkusDev -> NullPointerException on startup

### ISSUE THREAD

**Issue by jrevault** [quarkusio/quarkus#3898]
Hi all,

I just migrated to Windows 10 pro (maybe it's not related, but it's the only difference) and my previous project is crashing at start when I launch
gradlew quarkusDev

Here is the exception I got :
```
07:50:04,034 INFO  [io.qua.dep.QuarkusAugmentor] Beginning quarkus augmentation
07:50:04,236 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta5
07:50:04,565 INFO  [io.qua.dep.QuarkusAugmentor] Quarkus augmentation completed in 531ms
07:50:05,015 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:126)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:94)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:229)
        ... 9 more
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
        at com.google.cloud.ServiceOptions$Builder.setCredentials(ServiceOptions.java:210)
        at com.google.cloud.firestore.FirestoreOptions$Builder.build(FirestoreOptions.java:223)
        at fr.quidquid.houlela.services.updaters.RTDBService.<init>(RTDBService.java:48)
        at fr.quidquid.houlela.services.updaters.RTDBService_ClientProxy.<init>(RTDBService_ClientProxy.zig:21)
        at fr.quidquid.houlela.services.updaters.RTDBService_Bean.<init>(RTDBService_Bean.zig:185)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:87)
        at io.quarkus.arc.ArcContainerImpl.<init>(ArcContainerImpl.java:86)
        at io.quarkus.arc.Arc.initialize(Arc.java:18)
        at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:33)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources10.deploy_0(ArcProcessor$generateResources10.zig:72)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources10.deploy(ArcProcessor$generateResources10.zig:36)
        at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:191)
        ... 9 more**Describe the bug**

Any idea ?
Thanks

**Comment by jrevault** [comment]
I need to check something first...
