### ISSUE TITLE
javax.actiovation dependency is not including in final package - Qurakus version - 3.6.6

### ISSUE THREAD

**Issue by Ramakrishna132** [quarkusio/quarkus#39042]
### Discussed in https://github.com/quarkusio/quarkus/discussions/39040

<div type='discussions-op-text'>

<sup>Originally posted by **Ramakrishna132** February 27, 2024</sup>
We have a requirement use below javax.actiovation dependency in my project. We have included below dependency inpom.xml but the jar is not inclusing in final package lib folder. Please suggest.

<dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
</dependency>

quarkus-plugin.version>3.6.6
quarkus.platform.version>3.6.6

Error : 
javax/activation/DataSource: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: javax/activation/DataSource
at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl.<clinit>(RuntimeBuiltinLeafInfoImpl.java:444)
at com.sun.xml.bind.v2.model.impl.RuntimeTypeInfoSetImpl.<init>(RuntimeTypeInfoSetImpl.java:33)
at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:98)
at com.sun.xml.bind.v2.model.impl.ModelBuilder.<init>(ModelBuilder.java:132)
at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:62)
at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:434)
at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:282)
at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)</div>

**Comment by fugerit79** [comment]
Hello @Ramakrishna132 actually I'm having the same issue.

I need to include a legacy library which needs javax.activation.

As I understand, quarkus extensions may define artifcats that should be always excluded from the build  : 
<https://quarkus.io/guides/class-loading-reference>

If you run mavne in debug, for instance : 

`mvn package -X`

You should see something like : 

'[DEBUG] [io.quarkus.bootstrap.model.ApplicationModelBuilder] (main) Extension io.quarkus:quarkus-resteasy-common:jar:3.9.2 is excluding javax.activation:activation`

**Reading the rationale for banning the dependency I guess there is no solution.**

I would like the quarkus team to confirm it anyway.

And it would be useful to know if there is a workaround to include javax.activation jar in quarkus 3.

At the moment, we tried to cut the only functionality needing javax* dependency, isolating them in quarkus 2 micro services.

But It would be great to be able to upgrade to quarkus 3.

Thanks in advance.

**Comment by geoand** [comment]
Closing for the lack of feedback
