### ISSUE TITLE
After upgrading Quarkus version from 3.2.7.Final to 3.8.1 io.quarkus.vertx.core.runtime.VertxCoreRecorder throws NPE on health checks

### ISSUE THREAD

**Issue by tugcesahin** [quarkusio/quarkus#39076]
### Describe the bug

After upgrading Quarkus version from 3.2.7.Final and 3.6.8 (2 separate projects) to 3.8.1, `io.quarkus.vertx.core.runtime.VertxCoreRecorder` throws NPE on  health checks. 

Project with version 3.2.7.Final used custom health check url before but now smallrye health checks are in use and problem starts with that change. Quarkus version 3.2.7.Final is working fine with the smallrye health checks.

Project with version 3.6.8 uses smallrye health checks.

Message:
`Uncaught exception received by Vert.x`
stack trace:

```posh
java.lang.NullPointerException: Cannot invoke "io.vertx.core.Handler.handle(Object)" because "this.original" is null
	at com.nr.vertx.instrumentation.AsyncHandlerWrapper.handle(AsyncHandlerWrapper.java:32)
	at com.nr.vertx.instrumentation.AsyncHandlerWrapper.handle(AsyncHandlerWrapper.java:14)
	at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16

**Comment by geoand** [comment]
Can you attach a sample application that exhibits this behavior please?

Thanks

**Comment by geoand** [comment]
I see.

Where does `com.nr.vertx.instrumentation.AsyncHandlerWrapper` come from?

**Comment by tugcesahin** [comment]
I think it comes NewRelic dependency. newrelic-agent and newrelic-api versions are upgraded from 8.6.0 to 8.9.1.

**Comment by geoand** [comment]
In that case my guess is that the agent doesn't handle the new version of Vert.x properly
