### ISSUE TITLE
ClassNotFoundException (ClassVisitor) with @ConfigMapping in production mode

### ISSUE THREAD

**Issue by liquidnya** [quarkusio/quarkus#39090]
### Describe the bug

When using inheritance in `@ConfigMapping` interfaces the resulting jar file throws a `java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor` Exception.

Config interfaces:

```java
package org.acme;

import java.util.Optional;

import io.smallrye.config.ConfigMapping;

@ConfigMapping(prefix = "my-config")
public interface MyConfig {
	GlobalConfig global();

	interface CommonConfig {
		Optional<String> commonTest();

		UserConfig user();
	}

	interface GlobalConfig extends CommonConfig {
		Optional<String> globalTest();
	}

	interface UserConfig {
		Optional<String> name();
	}
}
```

### Expected behavior

I expect being able to inject `MyConfig`.

### Actual behavior

An exception is thrown:

`java -jar target/quarkus-app/quarkus-run.jar`

```posh
Feb 29, 2024 3:00:10 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile [prod])
java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
        at io.smallrye.config.ConfigMappingInterface.getClassBytes(ConfigMappingInterface.java:147)
        at io.smallrye.config.ConfigMappingLoader.loadClass(ConfigMappingLoader.java:123)
        at io.smallrye.config.ConfigMappingLoader.getImplementationClass(ConfigMappingLoader.java:103)
        at io.smallrye.config.ConfigMappingLoader$1.computeValue(ConfigMappingLoader.java:23)
        at io.smallrye.config.ConfigMappingLoader$1.computeValue(ConfigMappingLoader.java:20)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at io.smallrye.config.ConfigMappingLoader.configMappingObject(ConfigMappingLoader.java:64)
        at io.smallrye.config.ConfigMappingContext.constructGroup(ConfigMappingContext.java:81)
        at io.smallrye.config.ConfigMappingContext$ObjectCreator$6.apply(ConfigMappingContext.java:455)
        at io.smallrye.config.ConfigMappingContext$ObjectCreator$6.apply(ConfigMappingContext.java:449)
        at io.smallrye.config.ConfigMappingContext$ObjectCreator$1.accept(ConfigMappingContext.java:259)
        at io.smallrye.config.ConfigMappingContext$ObjectCreator$1.accept(ConfigMappingContext.java:256)
        at io.smallrye.config.ConfigMappingContext$ObjectCreator.group(ConfigMappingContext.java:449)
        at org.acme.MyConfig$GlobalConfig1533326641Impl.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at io.smallrye.config.ConfigMappingLoader.configMappingObject(ConfigMappingLoader.java:66)
        at io.smallrye.config.ConfigMappingContext.constructGroup(ConfigMappingContext.java:81)
        at io.smallrye.config.ConfigMappingContext$ObjectCreator$6.apply(ConfigMappingContext.java:455)
        at io.smallrye.config.ConfigMappingContext$ObjectCreator$6.apply(ConfigMappingContext.java:449)
        at io.smallrye.config.ConfigMappingContext$ObjectCreator$1.accept(ConfigMappingContext.java:259)
        at io.smallrye.config.ConfigMappingContext$ObjectCreator$1.accept(ConfigMappingContext.java:256)
        at io.smallrye.config.ConfigMappingContext$ObjectCreator.group(ConfigMappingContext.java:449)
        at org.acme.MyConfig-1511189288Impl.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at io.smallrye.config.ConfigMappingLoader.configMappingObject(ConfigMappingLoader.java:66)
        at io.smallrye.config.ConfigMappingContext.constructGroup(ConfigMappingContext.java:81)
        at io.smallrye.config.ConfigMappingContext.constructRoot(ConfigMappingContext.java:76)
        at io.smallrye.config.ConfigMappingContext$1.apply(ConfigMappingContext.java:70)
        at io.smallrye.config.ConfigMappingContext$1.apply(ConfigMappingContext.java:65)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.smallrye.config.ConfigMappingContext.registerRoot(ConfigMappingContext.java:65)
        at io.smallrye.config.ConfigMappingContext.<init>(ConfigMappingContext.java:54)
        at io.smallrye.config.ConfigMappingProvider$1.get(ConfigMappingProvider.java:65)
        at io.smallrye.config.ConfigMappingProvider$1.get(ConfigMappingProvider.java:62)
        at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
        at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:84)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:724)
        at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
        at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
        at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
        ... 13 more
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:115)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
        ... 64 more
```

### How to Reproduce?

Reproducer:

- Create a new Quarkus project
- Add the `MyConfig` interface from above
- Add any Bean that is not removed by Quarkus and injects MyConfig at startup
- Run `mvn clean package`
- Run `java -jar target/quarkus-app/quarkus-run.jar`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.4046]

### Output of `java -version`

OpenJDK Runtime Environment Corretto-17.0.8.7.1 (build 17.0.8+7-LTS)

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

### Additional information

Note that this bug does not happen during tests and also does not happen during `mvn quarkus:dev`!

This issue is probably related to #18533.

**Comment by liquidnya** [comment]
I created this example project:
https://github.com/liquidnya/quarkus-issue-39090
Run `mvn clean package` and then `java -jar target/quarkus-app/quarkus-run.jar`

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
This will be fixed by https://github.com/smallrye/smallrye-config/pull/1123

**Comment by radcortez** [comment]
Unfortunately, I don't have a workaround for this... other than avoiding super types in nested types.

**Comment by geoand** [comment]
@radcortez is there any chance that the error message could be improved to indicate that this is an issue with the library and should be reported?

Asking because the current error message is very misleading

**Comment by geoand** [comment]
> One option is to check if classes of ASM are available, and if they aren't, then we know that the generation should have happened during build time and fail with a better message

+1

**Comment by radcortez** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/39308
