### ISSUE TITLE
Panache: count() method with query string not building correctly

### ISSUE THREAD

**Issue by tmulle** [quarkusio/quarkus#39126]
### Describe the bug

When trying to run a custom query using the count() method, it appears the query is trying to build the query incorrectly and causing another SELECT statement where it shouldn't be.

I didn't see anything in the docs saying I couldn't provide a full custom select query to the count() method.

We are doing this because we need the filtered records BEFORE we do the pagination for our UI and unfortunately there is no way for us to get this info but to run two queries. One to count the records before Pagination and then run the other one to retrieve the records themselves.

Anyway, here is my query to the count and the error it is throwing..it is adding a SELECT statement where I didn't put one.

Count Query and Error
```
java.lang.IllegalArgumentException: org.hibernate.query.SyntaxException: At 1:103 and token 'SELECT', mismatched input 'SELECT', expecting one of the following tokens: <EOF>, ',', CROSS, FULL, GROUP, INNER, JOIN, LEFT, ORDER, OUTER, RIGHT, WHERE [SELECT COUNT(*) FROM com.acme.myapp.server.services.registration.entity.RegistrationEntity WHERE SELECT r FROM RegistrationEntity r JOIN r.macAddressList m WHERE m.address LIKE :filter OR m.address LIKE :filterStripped]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:143)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:167)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:173)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:848)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:753)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:136)
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.createQuery(TransactionScopedSession.java:367)
	at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:558)
	at org.hibernate.engine.spi.SessionLazyDelegator.createQuery(SessionLazyDelegator.java:67)
	at org.hibernate.Session_OpdLahisOZ9nWRPXMsEFQmQU03A_Synthetic_ClientProxy.createQuery(Unknown Source)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.count(AbstractJpaOperations.java:351)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.count(AbstractJpaOperations.java:360)
	at com.acme.myapp.server.services.registration.repository.RegistrationRepository.count(RegistrationRepository.java)
```

Count query to perform the filtering so we know how many records were filtered before the pagination.
```
recordsFiltered = registrationRepo.count("SELECT r FROM RegistrationEntity r JOIN r.macAddressList m WHERE m.address LIKE :filter OR m.address LIKE :filterStripped",
                        Parameters.with("filter", "%" + filter + "%").and("filterStripped", "%" + filterStripped + "%"));
```

### Expected behavior

I should be able to run the query

### Actual behavior

Throws the error described above

### Additional information

Quarkus 3.8.1
JDK 17

**Comment by tmulle** [comment]
i found this similar issue which looks to have been fixed but it might be a new or regression bug?

https://github.com/quarkusio/quarkus/issues/8254

**Comment by tmulle** [comment]
Ok, so seems that if I remove the starting "SELECT r" from the query it works.

So, this appears to work:
```
registrationRepo.count("FROM RegistrationEntity r JOIN r.macAddressList m WHERE m.address LIKE :filter OR m.address LIKE :filterStripped",
                        Parameters.with("filter", "%" + filter + "%").and("filterStripped", "%" + filterStripped + "%"));
```

**Comment by melloware** [comment]
@FroMage i agree this is not a bug just a misuse of the `count` query.

**Comment by melloware** [comment]
@tmulle can this be closed now?

**Comment by tmulle** [comment]
yes, i will close it.
