### ISSUE TITLE
Websocket warning: NoSuchElementException: io.vertx.core.net.impl.VertxSniHandler

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#39134]
### Describe the bug

I got this warning in logs only once, so it is not a real issue, but I just wanted to report it anyway:

```
2024-03-02 23:55:21,570 INFO  WebsocketServer.closed() is called
2024-03-03 00:06:08,688 WARN  An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: io.netty.handler.codec.DecoderException: java.util.NoSuchElementException: io.vertx.core.net.impl.VertxSniHandler
	at io.netty.handler.ssl.SslClientHelloHandler$1.operationComplete(SslClientHelloHandler.java:237)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:503)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Caused by: java.util.NoSuchElementException: io.vertx.core.net.impl.VertxSniHandler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1082)
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:509)
	at io.netty.handler.ssl.SniHandler.replaceHandler(SniHandler.java:184)
	at io.netty.handler.ssl.SniHandler.onLookupComplete(SniHandler.java:164)
	at io.netty.handler.ssl.AbstractSniHandler.onLookupComplete(AbstractSniHandler.java:191)
	at io.netty.handler.ssl.SslClientHelloHandler$1.operationComplete(SslClientHelloHandler.java:233)
	... 15 more
```

Note that `quarkus.http.ssl.sni=true` in `application.properties`.

### Output of `java -version`

21

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.6

**Comment by vietj** [comment]
does not ring a bell, do you have a reproducer ?

**Comment by Eng-Fouad** [comment]
> does not ring a bell, do you have a reproducer ?

Unfortunately, I don't have a reproducer.
