### ISSUE TITLE
RESTEasy resource with constructor or field injection failing with RESTEASY003190

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#39137]
### Describe the bug

I have the following JAX-RS Endpoint:

```
import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.validation.Validator;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.SecurityContext;
import jakarta.ws.rs.sse.Sse;
import lombok.extern.jbosslog.JBossLog;

@Path("/")
@ApplicationScoped
@JBossLog
public class ApplicationConstructorInjectionResource {
	
	private final Sse sse;
	private final SecurityContext security;
	private final Validator validator;
	
	
	@Inject
	public ApplicationConstructorInjectionResource(@Context Sse sse, SecurityContext security, Validator validator) {
		log.info("CDI Constructor called");
		this.sse = sse;
		this.security = security;
		this.validator = validator;
		log.infov("this.sse = {0}", this.sse.getClass());
		log.infov("this.security = {0}", this.security.getClass());
		log.infov("this.validator = {0}", this.validator.getClass());
	}

	@PostConstruct
	public void postConstruct() {
		log.infov("@PostConstruct called: {0}", this.getClass().getSimpleName());
		log.infov("this.sse = {0}", this.sse.getClass());
	}
	
	
	@GET
	@Path("/hello")
	@Produces(MediaType.TEXT_PLAIN)
	public String test() {
		return "hello";
	}

}
```

I get this compile error:

```
2024-03-03 12:30:44,985 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 3 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 16 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: RESTEASY003190: Could not find constructor for class: app.rest.ApplicationConstructorInjectionResource
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:556)
	at io.quarkus.deployment.steps.UndertowBuildStep$build767851419.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.UndertowBuildStep$build767851419.deploy(Unknown Source)
	... 17 more
Caused by: java.lang.RuntimeException: RESTEASY003190: Could not find constructor for class: app.rest.ApplicationConstructorInjectionResource
	at org.jboss.resteasy.spi.metadata.ResourceBuilder.getConstructor(ResourceBuilder.java:712)
	at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.registered(POJOResourceFactory.java:54)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:218)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:201)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:184)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:171)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:156)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:81)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.registerResources(ResteasyDeploymentImpl.java:463)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.registration(ResteasyDeploymentImpl.java:431)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:159)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:124)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:134)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:39)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:118)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:295)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:140)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:585)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:556)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:604)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:598)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:546)
	... 19 more
```
### 

### Expected behavior

Constructor injection with `@ApplicationScoped` and final fields should work without the need to set a no-args-constructor:

### Actual behavior

Constructor injection with `@ApplicationScoped` and final fields does not work .

### How to Reproduce?

Reproducer:

1. Take the class above and compile
2. The error above is thrown

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 OpenJDK Runtime Environment (build 21.0.2+13-58) OpenJDK 64-Bit Server VM (build 21.0.2+13-58, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.1

### Additional information

A similiar issue (but with `@Singleton`-scope) is reported here https://github.com/quarkusio/quarkus/issues/16475.

**Comment by manovotn** [comment]
I am not in front of my work laptop but it seems the no-args ctor might not be generated [here](https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-classic/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java#L384).

RE seems to check for list of allowed annotations on class to determine if it generates the c-tor - I wonder is the `@JBossLog` could cause this?

**Comment by mkouba** [comment]
CC @geoand

**Comment by geoand** [comment]
#39146 takes care of the issue

**Comment by geoand** [comment]
It turns out that the PR above was wrong.

The use case here actually is **not** supported because of the use of `@Context` on constructor parameters.

I opened #39152 to improve logging of this kind of thing in the future

**Comment by geoand** [comment]
> Is @Context within a constructor injection generally not supported by CDI, or is this just not supported in Quarkus Arc?

Correct, although it works in RESTEasy Reactive (with most types)

**Comment by geoand** [comment]
I'll update the docs soon

**Comment by geoand** [comment]
> If this is a Quarkus Arc limitation, it should be documented here: https://quarkus.io/guides/cdi-reference#supported_features_and_limitations.

This is not really a great place to document this limitation as it's not an Arc limitation - although I understand why one would look there.
@mkouba @manovotn any ideas where to document that using `@Context`, `@PathParam` etc. is not supported by Arc and may or may not work in RETEasy Classic depending on exactly is being attempted?

**Comment by mkouba** [comment]
> > If this is a Quarkus Arc limitation, it should be documented here: https://quarkus.io/guides/cdi-reference#supported_features_and_limitations.
> 
> This is not really a great place to document this limitation as it's not an Arc limitation - although I understand why one would look there. @mkouba @manovotn any ideas where to document that using `@Context`, `@PathParam` etc. is not supported by Arc and may or may not work in RETEasy Classic depending on exactly is being attempted?

Yes, it's not an ArC limitation and it should not be documented there. I think that there should be a dedicated "CDI integratoin" chapter in the RETEasy Classic/Reactive docs and all the details (that I don't know ;-) should be explained there.

**Comment by manovotn** [comment]
> > If this is a Quarkus Arc limitation, it should be documented here: https://quarkus.io/guides/cdi-reference#supported_features_and_limitations.
> 
> This is not really a great place to document this limitation as it's not an Arc limitation - although I understand why one would look there. @mkouba @manovotn any ideas where to document that using `@Context`, `@PathParam` etc. is not supported by Arc and may or may not work in RETEasy Classic depending on exactly is being attempted?

A section in https://quarkus.io/guides/resteasy would be IMO best.
It's not Arc limitation as such, more a matter of integration between the two.

**Comment by geoand** [comment]
Yeah, you are just trying to work around the problem and that won't work :)

**Comment by geoand** [comment]
The general advice (for RESTEasy Classic at least) is that anything with `@Context` should be a method parameter
