### ISSUE TITLE
Hibernate schema validation is flaky and fails due missing tables (while the tables are present)

### ISSUE THREAD

**Issue by AnastasiiaL** [quarkusio/quarkus#39145]
### Describe the bug

When running integration tests on the project - it fails around 10% of the time locally, and more often on CI. The error shown is `java.lang.RuntimeException: Failed to start quarkus` ... `Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [Limits]`. 

I saw there was already an issue created about the same flakiness earlier ([https://github.com/quarkusio/quarkus/issues/34187](https://github.com/quarkusio/quarkus/issues/34187)) and it was closed due to the missing reproducible, so I stripped down the project to the minimal setup when the issue still happens and made it available here - [https://github.com/AnastasiiaL/flaky-cms](https://github.com/anastasiial/flaky-cms). 

### Expected behavior

No flakiness while executing integration tests

### Actual behavior

flaky around 10% of the time on my local machine, more often on CI. Perhaps can be triggered more often with restrained resources.

The stack trace:
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 18.17 s <<< FAILURE! -- in nl.cms.error.CMSExceptionMapperTest
[ERROR] nl.cms.error.CMSExceptionMapperTest.shouldReturnGeneralExceptionAPICall -- Time elapsed: 0.004 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:638)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:722)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:285)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:252)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:605)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:655)
        ... 1 more
Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: <default>] Unable to build Hibernate SessionFactory
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:129)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:89)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:157)
        at io.quarkus.hibernate.orm.runtime.JPAConfig.getEntityManagerFactory(JPAConfig.java:105)
        at io.quarkus.hibernate.orm.runtime.metrics.HibernateMetricsRecorder$1.accept(HibernateMetricsRecorder.java:31)
        at io.quarkus.hibernate.orm.runtime.metrics.HibernateMetricsRecorder$1.accept(HibernateMetricsRecorder.java:26)
        at io.quarkus.micrometer.runtime.MicrometerRecorder.registerMetrics(MicrometerRecorder.java:229)
        at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry477897979.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry477897979.deploy(Unknown Source)
        ... 8 more
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [Limits]
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:134)
        at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:46)
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:97)
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:75)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:295)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:145)
        at java.base/java.util.HashMap.forEach(HashMap.java:1429)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:142)
        at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
        at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:315)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:87)
        ... 18 more

[INFO] Running nl.cms.resource.LimitsResourceTest
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s -- in nl.cms.resource.LimitsResourceTest
[INFO] Running nl.cms.resource.TestResourceTest
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s -- in nl.cms.resource.TestResourceTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   CMSExceptionMapperTest.shouldReturnGeneralExceptionAPICall » Runtime java.lang.RuntimeException: Failed to start quarkus
```

### How to Reproduce?

[https://github.com/AnastasiiaL/flaky-cms](https://github.com/anastasiial/flaky-cms). 

Running the application:
- For the first time run: `./mvnw install -DskipTests`
- then `./mvnw verify`

### Output of `uname -a` or `ver`

 Darwin Kernel Version 23.3.0

### Output of `java -version`

21.0.2

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5

**Comment by wjglerum** [comment]
I've noticed this behaviour too, most notably going from Quarkus 2.x to Quarkus 3.x

**Comment by geoand** [comment]
I'll try and have a look soon

**Comment by marko-bekhta** [comment]
hey @geoand, I've tried reproducing this last week with no luck ... also note that the example seems to use MSSQL and if you are on the latest Fedora, you may have a problem starting the DB (https://github.com/microsoft/mssql-docker/issues/868) depending on your kernel version ...

**Comment by geoand** [comment]
Thanks for the heads up!

I'll give it a shot and see if there is anything different for my case

**Comment by gsmet** [comment]
If it's a timing issue and happening on CI, you might need to slow down
things.

**Comment by geoand** [comment]
Thanks for the input folks.

As I was not able to reproduce the problem (which is what I expected TBH), @AnastasiiaL could you update the description with the entire stacktrace of the exception you are getting?

**Comment by wjglerum** [comment]
> Thanks for the info.
> 
> As I am not really familiar with the Hibernate ORM extension (and given I can't reproduce the problem locally), I don't think I can provide much help here... 

Probably if you restrain the resources (cpu/ram) for your Docker env it should be easier to reproduce this issue.

> One thing I would ask however is to test and see if the problem still occurs when `quarkus.hibernate-orm.metrics.enabled` is set to `false`.

We will give that a try 👍

**Comment by AnastasiiaL** [comment]
Thanks for looking into it.

To trigger the problem locally I have to run it around 5-10times.

The stack trace from the shared sample app:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 18.17 s <<< FAILURE! -- in nl.cms.error.CMSExceptionMapperTest
[ERROR] nl.cms.error.CMSExceptionMapperTest.shouldReturnGeneralExceptionAPICall -- Time elapsed: 0.004 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:638)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:722)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:285)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:252)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:605)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:655)
        ... 1 more
Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: <default>] Unable to build Hibernate SessionFactory
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:129)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:89)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:157)
        at io.quarkus.hibernate.orm.runtime.JPAConfig.getEntityManagerFactory(JPAConfig.java:105)
        at io.quarkus.hibernate.orm.runtime.metrics.HibernateMetricsRecorder$1.accept(HibernateMetricsRecorder.java:31)
        at io.quarkus.hibernate.orm.runtime.metrics.HibernateMetricsRecorder$1.accept(HibernateMetricsRecorder.java:26)
        at io.quarkus.micrometer.runtime.MicrometerRecorder.registerMetrics(MicrometerRecorder.java:229)
        at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry477897979.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry477897979.deploy(Unknown Source)
        ... 8 more
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [Limits]
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:134)
        at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:46)
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:97)
        at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:75)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:295)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:145)
        at java.base/java.util.HashMap.forEach(HashMap.java:1429)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:142)
        at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
        at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:315)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:87)
        ... 18 more

[INFO] Running nl.cms.resource.LimitsResourceTest
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s -- in nl.cms.resource.LimitsResourceTest
[INFO] Running nl.cms.resource.TestResourceTest
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s -- in nl.cms.resource.TestResourceTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   CMSExceptionMapperTest.shouldReturnGeneralExceptionAPICall » Runtime java.lang.RuntimeException: Failed to start quarkus
```

**Comment by AnastasiiaL** [comment]
disabling `quarkus.hibernate-orm.metrics.enabled` seems to prevent the issue from recurring locally. I will try to push it to CI now and will let you know how that goes

**Comment by AnastasiiaL** [comment]
I ran the job on CI 6 times without failing, whereas before it would fail every second time there. So there's definitely an improvement

**Comment by geoand** [comment]
Can someone give #39352 a try?

**Comment by geoand** [comment]
I had that as well (it's likely due to build caching - cc @gsmet), but I was able to get over it by cleaning my `~/.m2/repository/io/quarkus` directory and built with `mvn -Dquickly`

**Comment by AnastasiiaL** [comment]
so I tried cleaning the directory and rebuilding quarkus locally, but that didn't solve the issue.

Basically when I only use the local version I get this error:
```
[ERROR] Failed to execute goal on project cms-webapp: Could not resolve dependencies for project nl.cms:cms-webapp:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: io.quarkus:quarkus-resteasy-reactive-qute:jar:999-SNAPSHOT (absent), io.quarkus:quarkus-resteasy-reactive-jsonb:jar:999-SNAPSHOT (absent): Could not find artifact io.quarkus:quarkus-resteasy-reactive-qute:jar:999-SNAPSHOT -> [Help 1]
```

then I also enable fetching from the quarkus snapshots repo `https://s01.oss.sonatype.org/content/repositories/snapshots` and then I get the error above.

**Comment by geoand** [comment]
How did you do the local build?

**Comment by AnastasiiaL** [comment]
> How did you do the local build?

1. `softwareupdate --install-rosetta`
2. git clone https://github.com/quarkusio/quarkus.git 
3. commited your change on top of main
3. cd quarkus
4. export MAVEN_OPTS="-Xmx4g"
5. ./mvnw -Dquickly --> results in `BUILD SUCCESS`

**Comment by gsmet** [comment]
@AnastasiiaL build Quarkus with `-Prelocations`.

Some extensions have been renamed and you are still using the old ones.

**Comment by gsmet** [comment]
(Sorry we are in the middle of a major change in Quarkus, see https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9 for more details)

The easiest way to do a quick test for you is to build with `./mvnw -Dquickly -Prelocations`

**Comment by AnastasiiaL** [comment]
aha, `-Prelocations` has solved it indeed. Thank you! I am happy to hear I was just missing something important rather than failing to follow the simplest instructions:)  

so far the tests are passing in my sample app. I will update you once more when it ran enough times to make any conclusions.

**Comment by geoand** [comment]
Thanks a lot for your help!

**Comment by AnastasiiaL** [comment]
I ran it around 30 times - the problem wasn't reproducible anymore. Then I rolled back to use v.3.8.1 - and it failed on the 5th run, so while there's no guarantee when trying to catch a flaky problem - it does look like this fix does the job 👍

**Comment by geoand** [comment]
Awesome, thanks so much!

**Comment by AnastasiiaL** [comment]
Thanks for looking into it! Amazing how you pin-pointed the source of it right away:)

**Comment by geoand** [comment]
Lucky guess :)
