### ISSUE TITLE
@MessageBundle with custom keys does not work properly

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#39176]
### Describe the bug

According to the [documentation](https://quarkus.io/guides/qute-reference#bundle-name-and-message-keys):

> Message keys are used directly in templates. The bundle name is used as a namespace in template expressions. The @MessageBundle can be used to define the default strategy used to generate message keys from method names. **However, the @Message can override this strategy and even define a custom key**.

The following should work:

AuthEmailTemplates.java:
```java
import io.quarkus.qute.i18n.Message;
import io.quarkus.qute.i18n.MessageBundle;

@MessageBundle(value = "auth_emails")
public interface AuthEmailTemplates {
    
    @Message(key = "email.login-otp")
    String loginByEmailOtp(String otp);
}
```

./resources/messages/auth_emails.properties:
```
email.login-otp=Login OTP is {otp}
```

However, I got the following error:

```
io.quarkus.qute.deployment.MessageBundleException: Message bundle method email.login-otp() not found on: io.fouad.backend.auth.templates.AuthEmailTemplates
	- file: C:\Users\fouad\IdeaProjects\fouad-backend\build\resources\main\messages\auth_emails.properties
	- line 0
	at io.quarkus.qute.deployment.MessageBundleProcessor.parseKeyToTemplateFromLocalizedFile(MessageBundleProcessor.java:781)
	at io.quarkus.qute.deployment.MessageBundleProcessor.getLocalizedFileKeyToTemplate(MessageBundleProcessor.java:730)
	at io.quarkus.qute.deployment.MessageBundleProcessor.generateImplementations(MessageBundleProcessor.java:679)
	at io.quarkus.qute.deployment.MessageBundleProcessor.processBundles(MessageBundleProcessor.java:268)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

If I delete `email.login-otp=Login OTP is {otp}` from `auth_emails.properties`, I get this error:

```
Caused by: io.quarkus.qute.deployment.MessageBundleException: Message template for key [email.login-otp] is missing for default locale [en-US]
	at io.quarkus.qute.deployment.MessageBundleProcessor.generateImplementation(MessageBundleProcessor.java:916)
	at io.quarkus.qute.deployment.MessageBundleProcessor.generateImplementations(MessageBundleProcessor.java:683)
	at io.quarkus.qute.deployment.MessageBundleProcessor.processBundles(MessageBundleProcessor.java:268)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

The workaround here is to replace `email.login-otp=Login OTP is {otp}` with `loginByEmailOtp=Login OTP is {otp}`.

### Output of `java -version`

21

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.6

**Comment by mkouba** [comment]
This works as designed. Keep in mind that `@Message#key()`  is only used in templates and not in message bundle files. The requisites of a  message bundle file are described in [the docs](https://quarkus.io/guides/qute-reference#localization): _"Keys are mapped to method names from the corresponding message bundle interface."_

The main reason is that message keys are [derived/transformed by default](https://quarkus.io/guides/qute-reference#bundle-name-and-message-keys).

There is an [issue to make it possible to use transformed message keys in localized files](https://github.com/quarkusio/quarkus/issues/35243). You can upvote the issue or even send a pull request ;-).

**Comment by geoand** [comment]
> This works as designed

In that case, we should probably close this
