### ISSUE TITLE
quarkus-elasticsearch-java-client extension raises exception on DELETE request

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#39191]
### Describe the bug

Using Quarkus 3.7.1 with `quarkus-elasticsearch-java-client` extension. Running the following request in Kibana works as expected:

    DELETE customers/_doc/69wID44Bdp9hpkBkyZ2a

Running the same request with the Java client, as follows:

        client.delete(DeleteRequest.of(dr -> dr.index(INDEX).id(id)));

where `INDEX` = `customers` and `id` = `69wID44Bdp9hpkBkyZ2a`, raises the following exception:

    Caused by: co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/delete] failed: [http_status_405] Incorrect HTTP method for uri [/customers/_doc/] and method [DELETE], allowed: [POST]
        at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345)
        at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147)
        at co.elastic.clients.elasticsearch.ElasticsearchClient.delete(ElasticsearchClient.java:554)
        at fr.simplex_software.docstore.service.impl.CustomerServiceImpl.removeCustomerById(CustomerServiceImpl.java:68)
        at fr.simplex_software.docstore.service.impl.CustomerServiceImpl_ClientProxy.removeCustomerById(Unknown Source)
        at fr.simplex_software.docstore.api.impl.CustomerResourceImpl.deleteCustomerById(CustomerResourceImpl.java:64)

### Expected behavior

I expect that the given request works when using the Java client the same way as when using the Kibana console.

### Actual behavior

While the request works as expected when ran in the Kibana console, it fails when ran with the Java client, raising the mention exception.

### How to Reproduce?

Don't have a reproducer.

### Output of `uname -a` or `ver`

Linux nicolas-XPS-15-9570 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "17.0.6" 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /opt/apache-maven-3.9.5 Java version: 17.0.6, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-17 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-97-generic", arch: "amd64", family: "unix"

### Additional information

N/A

**Comment by patrox** [comment]
Hi @nicolasduminil 

First, it doesn't look like an issue with quarkus itself, as the stacktrace is all about elasticsearch / client code.
I tried to reproduce it by setting up a simple example project from https://quarkus.io/guides/elasticsearch and adding there an endpoint for deleting documents, but the calls were successful.

One idea which I have is that maybe you didn't pass the `id` so that's why you got the message:

```
[http_status_405] Incorrect HTTP method for uri [/customers/_doc/] and method [DELETE], allowed: [POST]
```

Please note, that the uri doesn't contain the id - which might explain the error.

**Comment by nicolasduminil** [comment]
@patrox : as a matter of fact, it wasn't a bug. You were right, debugging more carefully I found out that the `id` was null. Thanks for putting me on the right track.
