### ISSUE TITLE
Quarkus-Gradle-Plugin uses deprecated methods

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#39221]
### Describe the bug

The Quarkus-Gradle-Plugin uses deprecated methods

```
...
> Configure project :server
The resolvable usage is already allowed on configuration ':server:quarkusGeneratedSourcesRuntimeClasspath'. This behavior has been deprecated. This behavior is scheduled to be removed in Gradle 9.0. Remove the call to setCanBeResolved(true), it has no effect. Consult the upgrading guide for further informat
ion: https://docs.gradle.org/8.6/userguide/upgrading_version_8.html#redundant_configuration_usage_activation
The resolvable usage is already allowed on configuration ':server:quarkusTestGeneratedSourcesRuntimeClasspath'. This behavior has been deprecated. This behavior is scheduled to be removed in Gradle 9.0. Remove the call to setCanBeResolved(true), it has no effect. Consult the upgrading guide for further info
rmation: https://docs.gradle.org/8.6/userguide/upgrading_version_8.html#redundant_configuration_usage_activation
...
> Task :server:quarkusGenerateCode
The BuildIdentifier.getName() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Use getBuildPath() to get a unique identifier for the build. Consult the upgrading guide for further information: https://docs.gradle.org/8.6/userguide/upgrading_version_8.html#build_identifier_name_and_
current_deprecation
...
```

### How to Reproduce?

[reproducer.zip](https://github.com/quarkusio/quarkus/files/14509138/reproducer.zip)

Run `./gradlew clean build --console=plain --warning-mode=all --rerun-tasks --build-cache --parallel`

### Output of `java -version`

Java 17

### Quarkus version or git rev

Quarkus 3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

**Comment by mschorsch** [comment]
@aloubyansky: You have been mentioned in other issues in connection with Gradle and the Quarkus plugin so I hope you can help here.

**Comment by aloubyansky** [comment]
I don't see `setCanBeResolved(true)` calls in our code, there must be something else triggering these.

**Comment by mschorsch** [comment]
Tested with Quarkus 3.9.4, Quarkus 99-SNAPSHOT and Gradle 8.7. The deprecation warning is still there.

**Comment by ryandens** [comment]
I'm also still seeing this deprecation warning for `BuildIdentifier.getName()` which looks like it is being used in by the quarkus class `io.quarkus.gradle.tooling.dependency.DependencyUtils` based on this stacktrace:

```bash
at org.gradle.api.internal.artifacts.DefaultBuildIdentifier.getName(DefaultBuildIdentifier.java:48)	
	at io.quarkus.gradle.tooling.dependency.DependencyUtils.getExtensionInfoOrNull(DependencyUtils.java:100)	
	at io.quarkus.gradle.dependency.ConditionalDependenciesEnabler.collectConditionalDependencies(ConditionalDependenciesEnabler.java:94)	
	at io.quarkus.gradle.dependency.ConditionalDependenciesEnabler.<init>(ConditionalDependenciesEnabler.java:51)	
	at io.quarkus.gradle.dependency.ApplicationDeploymentClasspathBuilder.lambda$setUpDeploymentConfiguration$10(ApplicationDeploymentClasspathBuilder.java:205)	
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
```


link to usage of deprecated method in source: https://github.com/quarkusio/quarkus/blob/9a768bbec0f3e9db839d7bf61f8594174999380c/devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/dependency/DependencyUtils.java#L100


The deprecated method recommends using `getBuildPath` instead and to use that for comparing builds to compare included builds. It looks like this value is comapred in `ToolingUtils.includedBuild`:

https://github.com/quarkusio/quarkus/blob/9a768bbec0f3e9db839d7bf61f8594174999380c/devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/tooling/ToolingUtils.java#L54

so just updating both locations to use `BuildIdentifier.getBuildPath` instead of `BuildIdentifier.getName` would be sufficient to help prepare quarkus builds for Gradle 9.

**Comment by mschorsch** [comment]
Thranks @ryandens 

@aloubyansky Tested with Quarkus 3.9.5 + Gradle 8.7

`./gradlew clean build --warning-mode=all --rerun-tasks --build-cache --parallel --stacktrace`

[full_stacktrace.md](https://github.com/quarkusio/quarkus/files/15145265/full_stacktrace.md)

**Comment by kronst** [comment]
Please, allow me to add some more deprecated methods used by Quarkus Gradle plugin:
```bash
Calling extendsFrom on configuration ':common:detachedConfiguration80' has been deprecated. This will fail with an error in Gradle 9.0. Detached configurations should not extend other configurations, this was extending: 'quarkusDevRuntimeClasspathConfigurationPlatform'. Consult the upgrading guide for further information: https://docs.gradle.org/8.11-rc-1/userguide/upgrading_version_8.html#detached_configurations_cannot_extend
Calling extendsFrom on configuration ':common:detachedConfiguration81' has been deprecated. This will fail with an error in Gradle 9.0. Detached configurations should not extend other configurations, this was extending: 'quarkusDevRuntimeClasspathConfigurationPlatform'. Consult the upgrading guide for further information: https://docs.gradle.org/8.11-rc-1/userguide/upgrading_version_8.html#detached_configurations_cannot_extend
Calling extendsFrom on configuration ':common:detachedConfiguration82' has been deprecated. This will fail with an error in Gradle 9.0. Detached configurations should not extend other configurations, this was extending: 'quarkusDevRuntimeClasspathConfigurationPlatform'. Consult the upgrading guide for further information: https://docs.gradle.org/8.11-rc-1/userguide/upgrading_version_8.html#detached_configurations_cannot_extend
```
This probably appears because of [ConditionalDependenciesEnabler::createConditionalDependenciesConfiguration](https://github.com/quarkusio/quarkus/blob/3.14/devtools/gradle/gradle-model/src/main/java/io/quarkus/gradle/dependency/ConditionalDependenciesEnabler.java#L177), which was reverted in https://github.com/quarkusio/quarkus/pull/42477

**Comment by amaechler** [comment]
I'm seeing the same:

```
Calling extendsFrom on configuration ':service-event-collector:detachedConfiguration14' has been deprecated. This will fail with an error in Gradle 9.0. Detached configurations should not extend other configurations, this was extending: 'quarkusProdRuntimeClasspathConfigurationPlatform'. Consult the upgrading guide for further information: https://docs.gradle.org/8.11.1/userguide/upgrading_version_8.html#detached_configurations_cannot_extend
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertNotDetachedExtensionDoingExtending(DefaultConfiguration.java:1878)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.extendsFrom(DefaultConfiguration.java:402)
        at io.quarkus.gradle.dependency.ConditionalDependenciesEnabler.createConditionalDependenciesConfiguration(ConditionalDependenciesEnabler.java:177)
        at io.quarkus.gradle.dependency.ConditionalDependenciesEnabler.resolveConditionalDependency(ConditionalDependenciesEnabler.java:111)
        at io.quarkus.gradle.dependency.ConditionalDependenciesEnabler.<init>(ConditionalDependenciesEnabler.java:61)
        at io.quarkus.gradle.dependency.ApplicationDeploymentClasspathBuilder.lambda$setUpDeploymentConfiguration$11(ApplicationDeploymentClasspathBuilder.java:233)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
        ...
```

Quarkus: 3.16.4
Gradle: 8.11.1

**Comment by ryandens** [comment]
👋 Just wanted to surface/raise awareness of this issue again. Gradle 9 is planned to be released in the next few months according to [this](https://gradle.org/whats-new/gradle-9/) page. Does the quarkus team have a plan for improving their gradle support?

**Comment by Eng-Fouad** [comment]
Fixed in #48522

**Comment by aloubyansky** [comment]
Thanks @Eng-Fouad
