### ISSUE TITLE
Quarkus can't see my Clojure classes.

### ISSUE THREAD

**Issue by tkaryadis** [quarkusio/quarkus#39277]
### Describe the bug

I use https://github.com/clojurephant/clojurephant for grandle and it works ok in Clojure, i made spring and vert.x projects in past.
I tried to use it with Quarkus and Quarkus can't see the Clojure classes. I can't find a way to use Clojure with Quarkus.

### Expected behavior

See the Clojure classes.

### Actual behavior

joy.Interop is a class made from Clojure code

Caused by: java.lang.ClassNotFoundException: joy.Interop at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518) at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468) at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518) at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468) ... 15 more

### How to Reproduce?

I made a simple project here, if you go to localhost:8080/hello => runtime error
https://github.com/tkaryadis/code-with-quarkus

In spring-webflux and in vert.x i didn't had this problem, for example this is the almost the same demo project in spring, and works ok.
https://github.com/tkaryadis/spring-demo

### Additional information

If you know a way to use Quarkus from either maven or grandle and Clojure would be helpful else Clojure developers can't use Quarkus.

**Comment by geoand** [comment]
Thanks for reporting

We have absolutely no support for Closure and as far as I know we have never even tested it, so this is not something we will be looking into.

**Comment by nha** [comment]
@tkaryadis you could try https://github.com/talios/clojure-maven-plugin
