### ISSUE TITLE
Binding error in azure app functions

### ISSUE THREAD

**Issue by jumper404** [quarkusio/quarkus#39280]
### Describe the bug

Getting binding error when azure function binding using route is used.

### Expected behavior

To retrieve the value

### Actual behavior

Throws binding error

### How to Reproduce?

Create any azure app function with route 

### Output of `java -version`

11

### Quarkus version or git rev

3.5.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

### Additional information

@FunctionName("GetLicense")
    public HttpResponseMessage getLicense(
            @HttpTrigger(
                name = "getLicense",
                methods = {HttpMethod.GET},
                authLevel = AuthorizationLevel.ANONYMOUS,
                route = "license/getLicenseDetails/{customerCode}")
            @BindingName("customerCode") String customerCode,
            HttpRequestMessage<?> request,
            final ExecutionContext context
    )

Stack Trace->
Executed 'Functions.GetLicense' (Failed, Id=92f0807b-2414-4947-8f2e-9401b37d84f8, Duration=22ms)
[2024-03-08T09:14:42.256Z] System.Private.CoreLib: Exception while executing function: Functions.GetLicense. System.Private.CoreLib: Result: Failure
Exception: ClassCastException: class com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource cannot be cast to class java.lang.String (com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
Stack: java.lang.ClassCastException: class com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource cannot be cast to class java.lang.String (com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
[2024-03-08T09:14:42.259Z]      at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:99)
[2024-03-08T09:14:42.260Z]      at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
[2024-03-08T09:14:42.261Z]      at com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource.computeByType(ExecutionContextDataSource.java:21)
[2024-03-08T09:14:42.262Z]      at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByType(BindingDataStore.java:71)
[2024-03-08T09:14:42.263Z]      at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:50)
[2024-03-08T09:14:42.264Z]      at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolveArguments(ParameterResolver.java:22)
[2024-03-08T09:14:42.265Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:20)
[2024-03-08T09:14:42.266Z]      at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
[2024-03-08T09:14:42.267Z]      at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
[2024-03-08T09:14:42.268Z]      at io.quarkus.azure.functions.runtime.QuarkusAzureFunctionsMiddleware.invoke(QuarkusAzureFunctionsMiddleware.java:19)
[2024-03-08T09:14:42.270Z]      at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
[2024-03-08T09:14:42.272Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125)
[2024-03-08T09:14:42.273Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
[2024-03-08T09:14:42.274Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2024-03-08T09:14:42.275Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
[2024-03-08T09:14:42.276Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
[2024-03-08T09:14:42.277Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-03-08T09:14:42.278Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-03-08T09:14:42.279Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-03-08T09:14:42.280Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-03-08T09:14:42.281Z]      at java.base/java.lang.Thread.run(Thread.java:834)
[2024-03-08T09:14:42.282Z] .

**Comment by jumper404** [comment]
@functionName("GetLicense")
public HttpResponseMessage getLicense(
@HttpTrigger(
name = "getLicense",
methods = {HttpMethod.GET},
authLevel = AuthorizationLevel.ANONYMOUS,
route = "license/getLicenseDetails/{customerCode}")
HttpRequestMessage<?> request,
@BindingName("customerCode") String customerCode,
final ExecutionContext context
)



It was an ordering problem
