### ISSUE TITLE
Invalid channel configuration -  the `connector` attribute must be set for channel `news$1` when setting the concurrency attribute

### ISSUE THREAD

**Issue by jesantana** [quarkusio/quarkus#39281]
### Describe the bug

I have Kafka message consumer configured like this:

```
kafka.group.id=news-api
mp.messaging.incoming.news.connector=smallrye-kafka
mp.messaging.incoming.news.topic=news-events
mp.messaging.incoming.news.value.deserializer=SomeClass
mp.messaging.incoming.news.failure-strategy=dead-letter-queue
mp.messaging.incoming.news.dead-letter-queue.topic=news-events.dead-letter
mp.messaging.incoming.news.value-deserialization-failure-handler=event-deserialization-failure-handler
mp.messaging.incoming.news.concurrency=8
```
The `mp.messaging.incoming.news.concurrency` was just added and on this moment the error started appearing

### Expected behavior

Concurrency of the consumer should be set to 8, and all new consuming threads should work correctly

### Actual behavior

The application fails when starting with error 

```
Caused by: jakarta.enterprise.inject.spi.DeploymentException: java.lang.IllegalArgumentException: SRMSG00071: Invalid channel configuration -  the `connector` attribute must be set for channel `news$1`
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:58)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_qTrMuLFyQ1IvGfeSxRVitl6CCBQ.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 13 more
```
But this shouldn't happen since my config already has `mp.messaging.incoming.news.connector=smallrye-kafka`

If I declare 

```
mp.messaging.incoming.news$1.connector=smallrye-kafka
mp.messaging.incoming.news$2.connector=smallrye-kafka
mp.messaging.incoming.news$3.connector=smallrye-kafka
mp.messaging.incoming.news$4.connector=smallrye-kafka
mp.messaging.incoming.news$5.connector=smallrye-kafka
mp.messaging.incoming.news$6.connector=smallrye-kafka
mp.messaging.incoming.news$7.connector=smallrye-kafka
mp.messaging.incoming.news$8.connector=smallrye-kafka
```

or remove the dead letter queue config the error goes away

### How to Reproduce?

Start an application with above config

### Output of `uname -a` or `ver`

Linux pc-30.home 6.3.8-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 15 01:51:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 LTS OpenJDK Runtime Environment Microsoft-6841604 (build 17.0.5+8-LTS) OpenJDK 64-Bit Server VM Microsoft-6841604 (build 17.0.5+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

**Comment by ozangunalp** [comment]
It does look like a bug with the handling of properties for dead-letter-queue when combined with the concurrency.

**Comment by kouong** [comment]
Hi all,

I am having the same issue. It is already working for you? :)

Thanks in advance for the reply ! :)

**Comment by jesantana** [comment]
@kouong You will need to upgrade to version >= 3.10.0 in order to have the fix working.
