### ISSUE TITLE
`@ConfigMapping` handling of Maps is not compatible with old config classes

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#39315]
### Describe the bug

For https://github.com/quarkusio/quarkus/issues/17664 I need to use `@ConfigMapping` as I don't want users to create deprecated config classes. Migration of the:

https://github.com/quarkusio/quarkus/blob/56ffa1223ca982c97933acdb08e6d6df4e5ca03d/extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerTenantConfig.java#L152

results in config validation error. Migrated class can be seen in here https://github.com/quarkusio/quarkus/commit/310a568eba3dfc856fd599b0fad147becdb5382e

### Expected behavior

There should be a way to do what we did in past without writing custom converted, that is:

```
@ConfigGroup
public static class ClaimInformationPointConfig {

    /**
     *
     */
    @ConfigItem(name = ConfigItem.PARENT)
    public Map<String, Map<String, Map<String, String>>> complexConfig;

    /**
     *
     */
    @ConfigItem(name = ConfigItem.PARENT)
    public Map<String, Map<String, String>> simpleConfig;
}
```

### Actual behavior

An exception is thrown and application starts to run:

```
io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "static-claim")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "{request.parameter['grant']}")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "GET")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "{request.body['/from-body']}")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "{request.relativePath}")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "static-claim")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "static-claim")
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:643)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:727)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "static-claim")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "{request.parameter['grant']}")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "GET")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "{request.body['/from-body']}")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "{request.relativePath}")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "static-claim")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "static-claim")
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:75)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:84)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:714)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.initConfiguration(BuildTimeConfigurationReader.java:409)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:137)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:251)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:224)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:610)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:660)
	... 1 more
```

### How to Reproduce?

1. `git@github.com:michalvavrik/quarkus.git`
2. `cd quarkus`
3. `git checkout feature/kc-authz-dynamic-policy-enforcer-resolver`
4. `mvn -Dquickly`
5. `mvn clean verify -f integration-tests/keycloak-authorization/ -Dtest-containers -Dstart-containers`

### Output of `uname -a` or `ver`

Fedora 38

### Output of `java -version`

21

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3

**Comment by michalvavrik** [comment]
In case there is known workaround, please let me know.

**Comment by radcortez** [comment]
It seems to be a bug when multiple Maps are used in the same level with `@WithParentName`. I don't have a workaround at the moment. Let me see what I can do.

**Comment by michalvavrik** [comment]
Thank you @radcortez .

**Comment by radcortez** [comment]
https://github.com/smallrye/smallrye-config/pull/1132 should fix it.

But `@ConfigMapping` behaves a bit differently with a `Map`. Nested map keys are also added to the outer `Map. Consider:

```java
@ConfigMapping(prefix = "maps")
interface NestedLeadfsMaps {
    @WithParentName
    Map<String, Map<String, String>> doubleMap();

    @WithParentName
    Map<String, Map<String, Map<String, String>>> tripleMap();
}
```

```properties
maps.one.two=value
maps.one.two.three=value
```

The `doubleMap` will contain a key `one` with another `Map` with two keys `two` and `two.three`. We changed the `Map` to also consider any nested keys, because other config systems like Kafka, use dynamic properties with a variable number of key segments, which made it impossible if a `Map` would only consider keys of its root level.

**Comment by michalvavrik** [comment]
np, I can work with that. thanks

**Comment by radcortez** [comment]
> Wondering if this should be configurable at the property level if we think that's not something we want to enforce everywhere?

Yes, that something we can add. Until now, I haven't found any cases where that is required.

To further clarify, this only applies when the `Map` has a leaf type as a value. In most case, we add a nested group, and in that case, it just follows the regular rules.

**Comment by michalvavrik** [comment]
Hey @radcortez , I've tried it, this time with this commit https://github.com/quarkusio/quarkus/commit/e3b58d9850bb87f0f3c59b70a197844b85d1d023 rebased on your fix (I think you can probably reproduce it with original reproducer as well, but I split original planned changes into this now).

I get:
```
[ERROR] io.quarkus.it.keycloak.AdminClientTestCase.testGetNewRealm -- Time elapsed: 0.004 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:643)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:727)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:285)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:252)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:610)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:660)
	... 1 more
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Failed to read configuration properties
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	... 8 more
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "static-claim")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "{request.parameter['grant']}")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "GET")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "{request.body['/from-body']}")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "{request.relativePath}")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "static-claim")
	java.util.NoSuchElementException: SRCFG00042: Value does not match the expected map format "<key1>=<value1>;<key2>=<value2>..." (value was "static-claim")
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:75)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:84)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:714)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
	... 9 more

```

for following properties:

```
quarkus.keycloak.policy-enforcer.paths.1.claim-information-point.claims.static-claim=static-claim
quarkus.keycloak.api-permission-webapp.policy-enforcer.paths.1.claim-information-point.claims.static-claim=static-claim
quarkus.keycloak.api-permission-tenant.policy-enforcer.paths.1.claim-information-point.claims.static-claim=static-claim
quarkus.keycloak.policy-enforcer.claim-information-point.claims.request-uri={request.relativePath}
quarkus.keycloak.policy-enforcer.paths.3.claim-information-point.http.method=GET
...
```

Yes, I can see that you have a test, but probably conditions are not same. Just run `mvn clean test -f integration-tests/keycloak-authorization/ -Dtest-containers -Dstart-containers -Dtest=AdminClientTestCase#testGetNewRealm` with my changes in the above-mentioned commit. Please have a look.

**Comment by radcortez** [comment]
Ok, I'll have a look.

**Comment by radcortez** [comment]
This one should fix it entirely: https://github.com/smallrye/smallrye-config/pull/1135.

Sorry for the inconvenience :(

**Comment by michalvavrik** [comment]
np, thanks for quick fix, it will help me
