### ISSUE TITLE
IllegalArgumentException exception is thrown when logging rest client request / response body which has GUID

### ISSUE THREAD

**Issue by vickymicky** [quarkusio/quarkus#39374]
### Describe the bug

I want to enable the rest client logging to log req / res and I have added the following configuration to achieve that, 

 ```yaml
rest-client:
    logging:
      scope: request-response
      body-limit: 10000
```
But I get an error when the response body contains GUID in it,

**Sample Response:**

```json
[
    {
        "id": {
            "guid": "2341DE42-2D89-48E1-B2BD-D48539A5E11F",
            "version": 1
        },
        "title": "sample json with guid"
    }
]
```
**Exception Stack trace:**

```posh
LogManager error of type FORMAT_FAILURE: Formatting error

java.lang.IllegalArgumentException: can't parse argument number: "id":{"guid":"2341DE42-2D89-48E1-B2BD-D48539A5E11F"
        at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1454)
        at java.base/java.text.MessageFormat.applyPattern(MessageFormat.java:492)
        at java.base/java.text.MessageFormat.<init>(MessageFormat.java:371)
        at java.base/java.text.MessageFormat.format(MessageFormat.java:860)
        at org.jboss.logmanager.ExtFormatter.formatMessageLegacy(ExtFormatter.java:107)
        at org.jboss.logmanager.ExtFormatter.formatMessage(ExtFormatter.java:70)
        at org.jboss.logmanager.formatters.Formatters$15.renderRaw(Formatters.java:736)
        at org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:221)
        at org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:86)
        at io.quarkus.runtime.logging.BannerFormatter.format(BannerFormatter.java:56)
        at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:32)
        at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:43)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:327)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
        at org.jboss.logmanager.Logger.log(Logger.java:708)
        at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:56)
        at org.jboss.logging.Logger.debugf(Logger.java:701)
        at org.jboss.resteasy.reactive.client.logging.DefaultClientLogger$1.handle(DefaultClientLogger.java:32)
        at org.jboss.resteasy.reactive.client.logging.DefaultClientLogger$1.handle(DefaultClientLogger.java:29)
        at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
        at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
        at io.vertx.core.impl.future.FutureImpl.onSuccess(FutureImpl.java:87)
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:23)
        at io.vertx.core.http.HttpClientResponse.bodyHandler(HttpClientResponse.java:132)
        at org.jboss.resteasy.reactive.client.logging.DefaultClientLogger.logResponse(DefaultClientLogger.java:29)
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$3$3.handle(ClientSendRequestHandler.java:327)
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$3$3.handle(ClientSendRequestHandler.java:323)
        at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:86)
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:79)
        at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:250)
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:444)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255)
        at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:134)
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:708)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:76)
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:153)
        at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:945)
        at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:814)
        at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:778)
        at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:158)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1383)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1246)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1295)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: ""id":{"guid":"2341DE42-2D89-48E1-B2BD-D48539A5E11F""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:654)
        at java.base/java.lang.Integer.parseInt(Integer.java:786)
        at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1452)
```

### Expected behavior

I would expect the logs print the req / res body without any error.

### Actual behavior

I suspect the error is due to the fact, DefaultClientLogger tries to format the req / res body since it considers it to be string always.

https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/logging/DefaultClientLogger.java#L32

https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/logging/DefaultClientLogger.java#L52

### Output of `java -version`

17.0.6

### Quarkus version or git rev

3.5.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

### Additional information

I propose the following solution:

Modify the printf-style substitutions to MessageFormat-style substitutions in the log statement aka, change from `%s` to `{}`.

**Sample**:

**Current statement,**

```
log.debugf("%s: %s %s, Status[%d %s], Headers[%s], Body:\n%s",
                        redirect ? "Redirect" : "Response",
                        response.request().getMethod(), response.request().absoluteURI(), response.statusCode(),
                        response.statusMessage(), asString(response.headers()), bodyToString(body));
```

**Proposed statement,**

```
log.debugf("%s: %s %s, Status[%d %s], Headers[%s], Body:\n{6}",  --> Modified statement
                        redirect ? "Redirect" : "Response",
                        response.request().getMethod(), response.request().absoluteURI(), response.statusCode(),
                        response.statusMessage(), asString(response.headers()), bodyToString(body));
```

**Reasoning**:

The {} notation is much more efficient than the` %s` String format notation in this case. The `{}` notation accepts any Object or primitive value, where the` %s %d ...` String format requires that the type of the parameter matches the format or an exception is thrown. So generally, `{}` is more convenient.

**Comment by geoand** [comment]
Closing as we never got a reproducer
