### ISSUE TITLE
Injection failure in generated code in devmode

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#39392]
### Describe the bug

I have an application, which uses mapstruct to generate code. When I run this app using `mvn clean quarkus:dev`, it fails with the follwoing exception: `@javax.inject.Inject declared on <..> use @jakarta.inject.Inject instead`. When I run the same app using  `mvn clean compile quarkus:dev` it works as expected.

### Expected behavior

Application should be started in devmode using `mvn clean quarkus:dev` command

### Actual behavior

```
2024-03-13 10:52:13,481 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatTopicMapper, use @jakarta.inject.Inject instead
[2] @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatDtoFactory, use @jakarta.inject.Inject instead
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1516)
	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:180)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:518)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	Suppressed: java.lang.IllegalStateException: @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatTopicMapper, use @jakarta.inject.Inject instead
		at io.quarkus.arc.deployment.WrongAnnotationUsageProcessor.detect(WrongAnnotationUsageProcessor.java:68)
		... 9 more
	Suppressed: java.lang.IllegalStateException: @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatDtoFactory, use @jakarta.inject.Inject instead
		at io.quarkus.arc.deployment.WrongAnnotationUsageProcessor.detect(WrongAnnotationUsageProcessor.java:68)
		... 9 more

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:334)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:251)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:112)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:433)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatTopicMapper, use @jakarta.inject.Inject instead
[2] @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatDtoFactory, use @jakarta.inject.Inject instead
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1516)
	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:180)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:518)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	Suppressed: java.lang.IllegalStateException: @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatTopicMapper, use @jakarta.inject.Inject instead
		at io.quarkus.arc.deployment.WrongAnnotationUsageProcessor.detect(WrongAnnotationUsageProcessor.java:68)
		... 9 more
	Suppressed: java.lang.IllegalStateException: @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatDtoFactory, use @jakarta.inject.Inject instead
		at io.quarkus.arc.deployment.WrongAnnotationUsageProcessor.detect(WrongAnnotationUsageProcessor.java:68)
		... 9 more

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	... 9 more
Caused by: jakarta.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatTopicMapper, use @jakarta.inject.Inject instead
[2] @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatDtoFactory, use @jakarta.inject.Inject instead
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1516)
	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:180)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:518)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	Suppressed: java.lang.IllegalStateException: @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatTopicMapper, use @jakarta.inject.Inject instead
		at io.quarkus.arc.deployment.WrongAnnotationUsageProcessor.detect(WrongAnnotationUsageProcessor.java:68)
		... 9 more
	Suppressed: java.lang.IllegalStateException: @javax.inject.Inject declared on io.quarkus.ts.javaee.gettingstarted.mapper.ChitChatMapperImpl.chitChatDtoFactory, use @jakarta.inject.Inject instead
		at io.quarkus.arc.deployment.WrongAnnotationUsageProcessor.detect(WrongAnnotationUsageProcessor.java:68)
		... 9 more

```

### How to Reproduce?

1. `git clone git@github.com:quarkus-qe/quarkus-test-suite.git -b 3.8 tests`
2. `cd tests/javaee-like-getting-started`
3.  `mvn clean quarkus:dev`

### Output of `uname -a` or `ver`

6.7.3-200.fc39.x86_64

### Output of `java -version`

Java version: 21.0.1, vendor: Eclipse Adoptium

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

Stacktrace mentions a bean, which uses `componentModel = CDI`. Mapstruct doc[1] mentions, that for this model, "the generated mapper is an application-scoped (from javax.enterprise.context or jakarta.enterprise.context, depending on which one is available with javax.inject having priority) CDI bean". Is it possible, that Quarkus provides javax context for some reason?

[1] https://mapstruct.org/documentation/stable/reference/html/#configuration-options

**Comment by Ladicek** [comment]
I didn't try, but it seems that the MapStruct annotation processor can correctly figure out which CDI version is available when javac is executed by the Maven compiler plugin, but not when javac is executed by Quarkus. There might be something Quarkus could do, or it might be MapStruct's fault entirely.

This certainly isn't an ArC bug, though.

**Comment by Ladicek** [comment]
As a workaround, using `componentModel = ComponentModel.JAKARTA_CDI` should work.
