### ISSUE TITLE
[GraalVM 24.1] Integration Tests - Locales - Some fails with: Error occurred during initialization of boot layer

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#39478]
### Describe the bug

The native integration test for `Locales Some` fails generating a native image with:

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /home/runner/work/mandrel/mandrel/graalvm-home/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Dlogging.initial-configurator.min-level=500 -J-Duser.language=cs -J-Duser.country=US -H:+UnlockExperimentalVMOptions -H:IncludeLocales=de,ja,fr-FR,uk-UA -H:-UnlockExperimentalVMOptions -J-Dfile.encoding=UTF-8 --features=io.quarkus.hibernate.validator.runtime.DisableLoggingFeature,io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+UnlockExperimentalVMOptions -H:BuildOutputJSONFile=quarkus-integration-test-locales-some-999-SNAPSHOT-runner-build-output-stats.json -H:-UnlockExperimentalVMOptions -H:+UnlockExperimentalVMOptions -H:+AllowFoldMethods -H:-UnlockExperimentalVMOptions -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+UnlockExperimentalVMOptions -H:+ReportExceptionStackTraces -H:-UnlockExperimentalVMOptions -J-Xmx13g -H:-AddAllCharsets --enable-url-protocols=http -H:NativeLinkerOption=-no-pie --enable-monitoring=heapdump -H:+UnlockExperimentalVMOptions -H:-UseServiceLoaderFeature -H:-UnlockExperimentalVMOptions -J--add-exports=org.graalvm.nativeimage/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json quarkus-integration-test-locales-some-999-SNAPSHOT-runner -jar quarkus-integration-test-locales-some-999-SNAPSHOT-runner.jar
Error occurred during initialization of boot layer
java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: symbolic reference class is not accessible: class java.lang.Class, from public Lookup
```

See:
https://github.com/graalvm/mandrel/actions/runs/8289954741/job/22688020495#step:12:2444

This is JDK 23+13.

Last worked with:
`Java version: 23-beta+12-ea, vendor version: Mandrel-24.1.0-dev418f219a`

See here for the working version: https://github.com/graalvm/mandrel/actions/runs/8211076430/job/22460157595#step:12:2463

**Comment by jerboaa** [comment]
This seems only reproducible with this particular CI build. When I enable debug logging `-Xlog:init=debug` I get:

```
Error occurred during initialization of boot layer
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1161)
	at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:382)
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:370)
	at java.base/java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:335)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:168)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:275)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:265)
	at java.base/java.lang.runtime.SwitchBootstraps$TypePairs.hashCode(SwitchBootstraps.java:685)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.put(HashMap.java:619)
	at java.base/java.lang.runtime.SwitchBootstraps$TypePairs.initialize(SwitchBootstraps.java:695)
	at java.base/java.lang.runtime.SwitchBootstraps.<clinit>(SwitchBootstraps.java:102)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1161)
	at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:382)
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:370)
	at java.base/java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:335)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:147)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:275)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:265)
	at java.base/java.util.Locale.createLocale(Locale.java:998)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1067)
	at java.base/java.util.Locale.getInstance(Locale.java:989)
	at java.base/java.util.Locale.getInstance(Locale.java:980)
	at java.base/java.util.Locale.initDefault(Locale.java:1136)
	at java.base/java.util.Locale.<clinit>(Locale.java:2391)
	at java.base/sun.security.util.SignatureFileVerifier.<clinit>(SignatureFileVerifier.java:51)
	at java.base/java.util.jar.JarFile.getBytes(JarFile.java:801)
	at java.base/java.util.jar.JarFile.checkForSpecialAttributes(JarFile.java:1027)
	at java.base/java.util.jar.JarFile.isMultiRelease(JarFile.java:387)
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:509)
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
	at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:639)
	at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:332)
	at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:238)
	at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:191)
	at java.base/jdk.internal.module.ModulePath.findAll(ModulePath.java:167)
	at java.base/java.lang.module.ModuleFinder$2.lambda$findAll$2(ModuleFinder.java:365)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:288)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at java.base/java.lang.module.ModuleFinder$2.findAll(ModuleFinder.java:366)
	at java.base/jdk.internal.module.DefaultRoots.compute(DefaultRoots.java:52)
	at java.base/jdk.internal.module.ModuleBootstrap.boot2(ModuleBootstrap.java:342)
	at java.base/jdk.internal.module.ModuleBootstrap.boot(ModuleBootstrap.java:173)
	at java.base/java.lang.System.initPhase2(System.java:2236)
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: symbolic reference class is not accessible: class java.lang.Class, from public Lookup
	at java.base/java.lang.runtime.ObjectMethods.<clinit>(ObjectMethods.java:164)
	... 54 more
Caused by: java.lang.IllegalAccessException: symbolic reference class is not accessible: class java.lang.Class, from public Lookup
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:889)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkSymbolicClass(MethodHandles.java:3799)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3759)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2752)
	at java.base/java.lang.runtime.ObjectMethods.<clinit>(ObjectMethods.java:90)
	... 54 more
```

I'm closing this for now since I cannot reproduce with a local build.

**Comment by jerboaa** [comment]
Another sighting of this with GraalVM community (24.1 - JDK 23):
https://github.com/graalvm/mandrel/actions/runs/8336110822/job/22813651251#step:12:2444

**Comment by jerboaa** [comment]
We consistently see that test failing in our nightly CI and master/JDK 23. JDK 22/24.0 is fine.

**Comment by jerboaa** [comment]
All that is needed to reproduce this seems to be `-Duser.language=cs` and a multi-release jar file on the module path. For example `lib/io.quarkus.quarkus-fs-util-0.0.9.jar` from a quarkus integration test.

```
./jdk-23+14/bin/java -Duser.language=cs -Xlog:init=debug --module-path lib/io.quarkus.quarkus-fs-util-0.0.9.jar --list-modules
Error occurred during initialization of boot layer
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1161)
	at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:382)
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:370)
	at java.base/java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:335)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:168)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:275)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:265)
	at java.base/java.lang.runtime.SwitchBootstraps$TypePairs.hashCode(SwitchBootstraps.java:685)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.put(HashMap.java:619)
	at java.base/java.lang.runtime.SwitchBootstraps$TypePairs.initialize(SwitchBootstraps.java:695)
	at java.base/java.lang.runtime.SwitchBootstraps.<clinit>(SwitchBootstraps.java:102)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1161)
	at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:382)
	at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:370)
	at java.base/java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:335)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:147)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:275)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:265)
	at java.base/java.util.Locale.createLocale(Locale.java:998)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1067)
	at java.base/java.util.Locale.getInstance(Locale.java:989)
	at java.base/java.util.Locale.getInstance(Locale.java:980)
	at java.base/java.util.Locale.initDefault(Locale.java:1136)
	at java.base/java.util.Locale.<clinit>(Locale.java:2391)
	at java.base/sun.security.util.SignatureFileVerifier.<clinit>(SignatureFileVerifier.java:51)
	at java.base/java.util.jar.JarFile.getBytes(JarFile.java:801)
	at java.base/java.util.jar.JarFile.checkForSpecialAttributes(JarFile.java:1027)
	at java.base/java.util.jar.JarFile.isMultiRelease(JarFile.java:387)
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:509)
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
	at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:639)
	at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:332)
	at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:238)
	at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:191)
	at java.base/jdk.internal.module.ModulePath.findAll(ModulePath.java:167)
	at java.base/java.lang.module.ModuleFinder$2.lambda$findAll$2(ModuleFinder.java:365)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:288)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at java.base/java.lang.module.ModuleFinder$2.findAll(ModuleFinder.java:366)
	at java.base/java.lang.module.Resolver.findAll(Resolver.java:856)
	at java.base/java.lang.module.Resolver.bind(Resolver.java:234)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:313)
	at java.base/java.lang.module.ModuleDescriptor$1.resolveAndBind(ModuleDescriptor.java:2763)
	at java.base/jdk.internal.module.Modules.newBootLayerConfiguration(Modules.java:191)
	at java.base/jdk.internal.module.ModuleBootstrap.boot2(ModuleBootstrap.java:383)
	at java.base/jdk.internal.module.ModuleBootstrap.boot(ModuleBootstrap.java:173)
	at java.base/java.lang.System.initPhase2(System.java:2236)
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: symbolic reference class is not accessible: class java.lang.Class, from public Lookup
	at java.base/java.lang.runtime.ObjectMethods.<clinit>(ObjectMethods.java:164)
	... 58 more
Caused by: java.lang.IllegalAccessException: symbolic reference class is not accessible: class java.lang.Class, from public Lookup
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:889)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkSymbolicClass(MethodHandles.java:3799)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3759)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2752)
	at java.base/java.lang.runtime.ObjectMethods.<clinit>(ObjectMethods.java:90)
	... 58 more
```

changing this to `-Duser.language=en` makes the problem go away:

```
jdk-23+14/bin/java -Duser.language=en -Xlog:init=debug --module-path lib/io.quarkus.quarkus-fs-util-0.0.9.jar --list-modules
java.base@23-beta
java.compiler@23-beta
java.datatransfer@23-beta
java.desktop@23-beta
java.instrument@23-beta
java.logging@23-beta
java.management@23-beta
java.management.rmi@23-beta
java.naming@23-beta
java.net.http@23-beta
java.prefs@23-beta
java.rmi@23-beta
java.scripting@23-beta
java.se@23-beta
java.security.jgss@23-beta
java.security.sasl@23-beta
java.smartcardio@23-beta
java.sql@23-beta
java.sql.rowset@23-beta
java.transaction.xa@23-beta
java.xml@23-beta
java.xml.crypto@23-beta
jdk.accessibility@23-beta
jdk.attach@23-beta
jdk.charsets@23-beta
jdk.compiler@23-beta
jdk.crypto.cryptoki@23-beta
jdk.crypto.ec@23-beta
jdk.dynalink@23-beta
jdk.editpad@23-beta
jdk.graal.compiler@23-beta
jdk.graal.compiler.management@23-beta
jdk.hotspot.agent@23-beta
jdk.httpserver@23-beta
jdk.incubator.vector@23-beta
jdk.internal.ed@23-beta
jdk.internal.jvmstat@23-beta
jdk.internal.le@23-beta
jdk.internal.opt@23-beta
jdk.internal.vm.ci@23-beta
jdk.jartool@23-beta
jdk.javadoc@23-beta
jdk.jcmd@23-beta
jdk.jconsole@23-beta
jdk.jdeps@23-beta
jdk.jdi@23-beta
jdk.jdwp.agent@23-beta
jdk.jfr@23-beta
jdk.jlink@23-beta
jdk.jpackage@23-beta
jdk.jshell@23-beta
jdk.jsobject@23-beta
jdk.jstatd@23-beta
jdk.localedata@23-beta
jdk.management@23-beta
jdk.management.agent@23-beta
jdk.management.jfr@23-beta
jdk.naming.dns@23-beta
jdk.naming.rmi@23-beta
jdk.net@23-beta
jdk.nio.mapmode@23-beta
jdk.random@23-beta
jdk.sctp@23-beta
jdk.security.auth@23-beta
jdk.security.jgss@23-beta
jdk.unsupported@23-beta
jdk.unsupported.desktop@23-beta
jdk.xml.dom@23-beta
jdk.zipfs@23-beta
io.quarkus.quarkus.fs.util@0.0.9 file:///home/sgehwolf/Documents/openjdk/quarkus/quarkus-source/integration-tests/locales/target/quarkus-integration-test-locales-999-SNAPSHOT-native-image-source-jar/lib/io.quarkus.quarkus-fs-util-0.0.9.jar automatic
```

I'll report this to upstream OpenJDK.

**Comment by jerboaa** [comment]
Well, that exercise wasn't too useful. Anyhow we should have this fixed with JDK 23+15. Why?

See https://bugs.openjdk.org/browse/JDK-8329100 for some details. I.e. The issue is caused by [JDK-8309622](https://bugs.openjdk.org/browse/JDK-8309622) and fixed by [JDK-8328261](https://bugs.openjdk.org/browse/JDK-8328261) which is in JDK 23+15.

That's also why we no longer see this with Mandrel JDK 23 builds which uses 23+15 already. Only on a GraalVM CE build with JDK 23+14 ([here](https://github.com/graalvm/mandrel/actions/runs/8429420113/job/23087307923#step:12:2437) for example).

**Comment by zakkak** [comment]
FTR the upstream PR updating GraalVM to JDK 23+15 is https://github.com/oracle/graal/pull/8628

**Comment by gastaldi** [comment]
Can this issue be closed?

**Comment by zakkak** [comment]
> Can this issue be closed?

Yes, the issue described here is fixed. There is a different issue related to locales though tracked here https://github.com/graalvm/mandrel/issues/778
