### ISSUE TITLE
Quarkus 3.9 build issue: String too large to record

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#39545]
### Describe the bug

I have migrated from 3.8 to 3.9.
on our main integration test application, I have the following error during the build:
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#build threw an exception: java.lang.RuntimeException: Failed to record c
all to method public void io.quarkus.runtime.ClassPathSystemPropertyRecorder.set(java.lang.String)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:480)
        at io.quarkus.deployment.steps.MainClassBuildStep.writeRecordedBytecode(MainClassBuildStep.java:501)
        at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:201)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: String too large to record: E:\projects\maven\maven-local-repo-artifactory\org\wildfly\se...
```

this is caused by 
```
                        } else if (param instanceof String) {
                            if (((String)param).length() > 65535) {
                                throw new RuntimeException("String too large to record: " + param);
                            } else {
```

in my case the string is of length 72119.
this was working in 3.8.

**Comment by gsmet** [comment]
Are you using `3.9.0.CR1`? We released `3.9.0.CR2` to fix this issue.

**Comment by vsevel** [comment]
fixed in CR2

**Comment by can-ishk** [comment]
hi @vsevel @gsmet, I hope you guys are doing well. I'm encountering this issue in `3.15.2`. Any thoughts?
