### ISSUE TITLE
SmallRyeConfig : ClassLoader_resolveClass error

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#3958]
**Describe the bug**
When adding camel into the mix, I get the following error:

```
Error: Error encountered while parsing com.oracle.svm.reflect.ClassLoader_resolveClass_1e2b9a844a6faacbb35b21800611da766acbc0f6.invoke(java.lang.Object, java.lang.Object[]) 
Parsing context:
	parsing java.lang.reflect.Method.invoke(Method.java:498)
	parsing io.smallrye.config.ImplicitConverters$StaticMethodConverter.convert(ImplicitConverters.java:97)
	parsing io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:127)
	parsing io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:98)
	parsing io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:35)
	parsing io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties9.deploy_0(ConfigBuildStep$validateConfigProperties9.zig:67)
	parsing io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties9.deploy(ConfigBuildStep$validateConfigProperties9.zig:86)
	parsing io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:74)
	parsing io.quarkus.runtime.Application.start(Application.java:91)
	parsing io.quarkus.runtime.Application.run(Application.java:204)
	parsing io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:147)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.reflect.ClassLoader_resolveClass_1e2b9a844a6faacbb35b21800611da766acbc0f6.invoke(java.lang.Object, java.lang.Object[]) 
Parsing context:
	parsing java.lang.reflect.Method.invoke(Method.java:498)
	parsing io.smallrye.config.ImplicitConverters$StaticMethodConverter.convert(ImplicitConverters.java:97)
	parsing io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:127)
	parsing io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:98)
	parsing io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:35)
	parsing io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties9.deploy_0(ConfigBuildStep$validateConfigProperties9.zig:67)
	parsing io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties9.deploy(ConfigBuildStep$validateConfigProperties9.zig:86)
	parsing io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:74)
	parsing io.quarkus.runtime.Application.start(Application.java:91)
	parsing io.quarkus.runtime.Application.run(Application.java:204)
	parsing io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:147)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:191)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:343)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:385)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:510)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.resolveClass(Class) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:183)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:395)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:375)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:74)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaMethod(UniverseMetaAccess.java:93)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:66)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:39)
	at com.oracle.svm.reflect.hosted.ReflectionSubstitutionType$ReflectiveInvokeMethod.buildGraph(ReflectionSubstitutionType.java:519)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:317)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:185)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	... 12 more

```

**To Reproduce**
1.  clone https://github.com/lburgazzoli/quarkus-camel-example
2.  built the native image

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux mars 5.2.11-200.fc30.x86_64
 - Output of `java -version`: OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
 - GraalVM version (if different from Java): building with docker
 - Quarkus version or git rev: 0.21.2

**Additional context**
The Camel Extension binds MP Config to the Camel Contex in a STATIC_INIT phase, shjould the reference to the MP Config object be recomputed ?

**Comment by dmlloyd** [comment]
I just want to note a couple of things.

@lburgazzoli, your `java -version` output is incomplete, and doesn't say what the actual version is.  But in any event I think we'd want the versions used by docker, whatever they may be...

The first method that is failing to be parsed is one that was generated by SVM itself.  So it seems odd that it is not parsing its own bytecode for some reason.  But, based on the bottom stack trace, I'm thinking that the problem is that something is trying to force class resolution by way of `ClassLoader` and invoking `resolveClass` via reflection.

**Comment by lburgazzoli** [comment]
The full java version on my host is:

    openjdk version "1.8.0_222"
    OpenJDK Runtime Environment (build 1.8.0_222-b10)
    OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

The I'm building with the docker images used by the quarkus maven plugin when it is configured to build the native image through docker:

     quay.io/quarkus/ubi-quarkus-native-image:19.1.1

Which reports:

    docker run --rm -ti --entrypoint sh quay.io/quarkus/ubi-quarkus-native-image:19.1.1 
    sh-4.4$ java -version
    openjdk version "1.8.0_222"
    OpenJDK Runtime Environment (build 1.8.0_222-20190711120915.buildslave.jdk8u-src-tar--b08)
    OpenJDK 64-Bit GraalVM CE 19.1.1 (build 25.222-b08-jvmci-19.1-b01, mixed mode)

**Comment by ppalaga** [comment]
I am getting a very similar stack trace with the code in https://github.com/apache/camel-quarkus/pull/201 also using the default docker image of Quarkus 0.21.2

```
Error: Error encountered while parsing com.oracle.svm.reflect.ClassLoader_resolveClass_1e2b9a844a6faacbb35b21800611da766acbc0f6.invoke(java.lang.Object, java.lang.Object[]) 
Parsing context:
        parsing java.lang.reflect.Method.invoke(Method.java:498)
        parsing io.smallrye.config.ImplicitConverters$StaticMethodConverter.convert(ImplicitConverters.java:97)
        parsing io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:127)
        parsing io.quarkus.runtime.configuration.ConfigUtils.convert(ConfigUtils.java:133)
        parsing io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console_async(RunTimeConfig.zig:13576)
        parsing io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console(RunTimeConfig.zig:8896)
        parsing io.quarkus.runtime.generated.RunTimeConfig.parseKey_log(RunTimeConfig.zig:25130)
        parsing io.quarkus.runtime.generated.RunTimeConfig.parseKey(RunTimeConfig.zig:12992)
        parsing io.quarkus.runtime.generated.RunTimeConfig.getRunTimeConfiguration(RunTimeConfig.zig:28243)
        parsing io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:42)
        parsing io.quarkus.runtime.Application.start(Application.java:91)
        parsing io.quarkus.runtime.Application.run(Application.java:204)
        parsing io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
        parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:147)
        parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.reflect.ClassLoader_resolveClass_1e2b9a844a6faacbb35b21800611da766acbc0f6.invoke(java.lang.Object, java.lang.Object[]) 
Parsing context:
        parsing java.lang.reflect.Method.invoke(Method.java:498)
        parsing io.smallrye.config.ImplicitConverters$StaticMethodConverter.convert(ImplicitConverters.java:97)
        parsing io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:127)
        parsing io.quarkus.runtime.configuration.ConfigUtils.convert(ConfigUtils.java:133)
        parsing io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console_async(RunTimeConfig.zig:13576)
        parsing io.quarkus.runtime.generated.RunTimeConfig.parseKey_log_console(RunTimeConfig.zig:8896)
        parsing io.quarkus.runtime.generated.RunTimeConfig.parseKey_log(RunTimeConfig.zig:25130)
        parsing io.quarkus.runtime.generated.RunTimeConfig.parseKey(RunTimeConfig.zig:12992)
        parsing io.quarkus.runtime.generated.RunTimeConfig.getRunTimeConfiguration(RunTimeConfig.zig:28243)
        parsing io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:42)
        parsing io.quarkus.runtime.Application.start(Application.java:91)
        parsing io.quarkus.runtime.Application.run(Application.java:204)
        parsing io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
        parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:147)
        parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:191)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:343)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:385)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:510)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.resolveClass(Class) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:183)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:395)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:375)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:74)
        at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaMethod(UniverseMetaAccess.java:93)
        at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:66)
        at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:39)
        at com.oracle.svm.reflect.hosted.ReflectionSubstitutionType$ReflectiveInvokeMethod.buildGraph(ReflectionSubstitutionType.java:519)
        at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:317)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:185)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        ... 12 more
```

**Comment by dmlloyd** [comment]
Yep this stack trace similarly seems to show that something is trying to call `ClassLoader#resolveClass` reflectively.  Whatever it is will need to be substituted.

**Comment by lburgazzoli** [comment]
Adding

    --report-unsupported-elements-at-runtime

make the application compile and run as expected

**Comment by lburgazzoli** [comment]
turns out that this is a problem in how camel handles xml: we can enable/disable xml/jaxb related bits with a build time configuration option but that does not influence the classpath hence, when xml processing is not disabled it is required to add quarkus-jaxb

**Comment by ppalaga** [comment]
@lburgazzoli sounds like we need a followup issue on the Camel Quarkus side?
