### ISSUE TITLE
ClassNotFoundException for beanparam class with generics in external artifact

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#39598]
### Describe the bug

In my app I want to put some of the commonly used classes in a common lib.
This however causes a ClassNotFoundException from resteasy-reactive (see below) for this constellation:

These 2 classes are in my main quarkus app.

Resource
```
@GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(@BeanParam GreetingListFilter<GreetingListSortAttribute> listFilter) {
        return listFilter.sortAttribute.name();
    }
```

```
public enum GreetingListSortAttribute implements SortAttribute{
    FORMALITY_FACTOR,
    LANGUAGE;

}
```

This one (and SortAttribute interface) is in an external lib:
```
public class GreetingListFilter<T extends SortAttribute> {
    @QueryParam("sortAttribute")
    // bogus default value so that rr calls fromString
    @DefaultValue("-")
    public T sortAttribute;
}
```

If I have the GreetingListFilter in the same module as app, everything works. It also works if the lib project is a sister module adjacent to the app.
It does not work if the lib is a fully external artifact.
I have added a META-INF/beans.xml in the lib for good measure, does not help. 

### Expected behavior

App starts

As endgoal, I want to call `http://localhost:8080/hello?sortAttribute=LANGUAGE`, and have the sortAttribute of GreetingListFilter be an instance of GreetingListSortAttribute. This works already if the lib is not external.

### Actual behavior

App does not start
```
2024-03-20 16:58:45,853 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 3 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 16 more
Caused by: java.lang.NoClassDefFoundError: org/acme/GreetingListSortAttribute$quarkusrestparamConverter$
        at org.acme.GreetingListFilter.__quarkus_init_converter__sortAttribute(GreetingListFilter.java)
        at io.quarkus.rest.runtime.__QuarkusInit.init(Unknown Source)
        at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder.createDeployment(ResteasyReactiveRecorder.java:144)
        at io.quarkus.deployment.steps.ResteasyReactiveProcessor$setupDeployment713137389.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.ResteasyReactiveProcessor$setupDeployment713137389.deploy(Unknown Source)
        ... 17 more
Caused by: java.lang.ClassNotFoundException: org.acme.GreetingListSortAttribute$quarkusrestparamConverter$
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
        ... 22 more


2024-03-20 16:58:45,871 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure

```

### How to Reproduce?

Reproducer: 
[rr-gen-type.zip](https://github.com/quarkusio/quarkus/files/14669565/rr-gen-type.zip)

1. cd lib
2. mvn clean install
3. cd ..
4. mvn clean compile quarkus:dev
5. error from above, does not start
6. ctrl+c, now in the pom.xml of the parent, include lib as a module
7. mvn clean compile quarkus:dev
8. app starts

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045 NANBCHL9NG3 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys

### Output of `java -version`

openjdk 21.0.2 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\eclipse\tools\java\maven Java version: 21.0.2, vendor: Eclipse Adoptium, runtime: C:\eclipse\tools\java\21 Default locale: de_DE, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by FroMage** [comment]
I think the important info is this:

> If I have the GreetingListFilter in the same module as app, everything works. It also works if the lib project is a sister module adjacent to the app.
> It does not work if the lib is a fully external artifact.
> I have added a META-INF/beans.xml in the lib for good measure, does not help.

For Hibernate ORM transformations, a `META-INF/beans.xm` is enough to find external classes from the index. Perhaps we're not using the proper index in RESTEasy Reactive?

**Comment by geoand** [comment]
The structure of the application looks weird in the sense that you have a parent `pom.xml` which has the Quarkus Maven plugin configured yet is not an applicaiton itself, but however contains a module that is an application.

I am pretty sure this kind of setup is not tested and AFAIK, it's not encouraged in any test or sample we have.

**Comment by Postremus** [comment]
@geoand 
Well yes the weird setup is caused by the reproducer. I just wanted to create something that fails, and that was the first thing I tested which did indeed fail :).

My real world application fails with the same exception.
In that one the lib is completly seperate from the quarkus application.

The quarkus application itself is multi module project.
Quarkus plugin is defined in pluginmanagement of parent.
And as plugin itself in the module which should be launched during quarkus:dev.
The same setup as any of my other apps.

So yes, please look deeper into this. Just cause there is a stumbling block does not mean the rest of the reproducer is invalid :)

(sorry if this comes of as harsh - I just hate situations like this. one mistake done and everything invalid? thats stupid)

**Comment by geoand** [comment]
I understand your point, no offense taken.

Let me try and explain my point of view a little better: I have to look at a bunch of issue day in and day out in addition to doing new development. 
Lots of eople such as yourself do an amazing job of making my job a lot easier by eliminating the guesswork and allowing me to spend very little time on setting up an environment where the problem manifests.
But when something like this happens, it's not an optimal use of my time to try and guess what the real world application looks like and try to recreate it. 
Additionally, it's not uncommon for people to find issues in their own setups when they try to provide a proper reproducer.

So  if you don't mind, can you please update the reproduce with a more typical Maven multi-module and dig in deeper to try and figure out what's going on.

Thanks

**Comment by Postremus** [comment]
@geoand 
[rr-gen-type (2).zip](https://github.com/quarkusio/quarkus/files/14754628/rr-gen-type.2.zip)

mvn clean install -N on the parent
mvn clean install on lib
mvn clean compile quarkus:dev on the app
-> Classnotfound exception

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/39691 should take care of it
