### ISSUE TITLE
Could not start quarkus in tests

### ISSUE THREAD

**Issue by jumper404** [quarkusio/quarkus#39612]
### Describe the bug

After cloning the quarkus repo and running a test the test fails saying quarkus failed to start.

Stacktrace ->

Mar 21, 2024 12:27:10 PM io.quarkus.runtime.StartupContext runAllInReverseOrder
ERROR: Running a shutdown task failed
java.lang.VerifyError: Method does not expect a return value
Exception Details:
  Location:
    io/vertx/core/impl/ContextInternal.removeLocal(Lio/vertx/core/spi/context/storage/ContextLocal;Lio/vertx/core/spi/context/storage/AccessMode;)V @5: ireturn
  Reason:
    Type integer (current frame, stack[0]) is not assignable to top (from method signature)
  Current Frame:
    bci: @5
    flags: { }
    locals: { 'io/vertx/core/impl/ContextInternal', 'io/vertx/core/spi/context/storage/ContextLocal', 'io/vertx/core/spi/context/storage/AccessMode' }
    stack: { integer }
  Bytecode:
    0000000: 2a2b b801 a4ac 0000 0000 0000 0000 00bf
    0000010:
  Stackmap Table:
    full_frame(@6,{},{Object[#177]})

        at io.vertx.core.Vertx.currentContext(Vertx.java:180)
        at io.quarkus.vertx.runtime.VertxCurrentContextFactory$VertxCurrentContext.get(VertxCurrentContextFactory.java:63)
        at io.quarkus.arc.impl.RequestContext.destroy(RequestContext.java:200)
        at io.quarkus.arc.ManagedContext.terminate(ManagedContext.java:50)
        at io.quarkus.arc.impl.ArcContainerImpl.shutdown(ArcContainerImpl.java:443)
        at io.quarkus.arc.Arc.shutdown(Arc.java:65)
        at io.quarkus.arc.runtime.ArcRecorder$1.run(ArcRecorder.java:53)
        at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:84)
        at io.quarkus.runtime.StartupContext.close(StartupContext.java:73)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:285)
        at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:662)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:396)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:396)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:212)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:85)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
        at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
        at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.82 s <<< FAILURE! -- in io.quarkus.funqy.test.SimpleTest
[ERROR] io.quarkus.funqy.test.SimpleTest -- Time elapsed: 10.82 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:709)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:285)
        at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:662)
        ... 1 more
Caused by: java.lang.VerifyError: Method does not expect a return value
Exception Details:
  Location:
    io/vertx/core/impl/ContextInternal.removeLocal(Lio/vertx/core/spi/context/storage/ContextLocal;Lio/vertx/core/spi/context/storage/AccessMode;)V @5: ireturn
  Reason:
    Type integer (current frame, stack[0]) is not assignable to top (from method signature)
  Current Frame:
    bci: @5
    flags: { }
    locals: { 'io/vertx/core/impl/ContextInternal', 'io/vertx/core/spi/context/storage/ContextLocal', 'io/vertx/core/spi/context/storage/AccessMode' }
    stack: { integer }
  Bytecode:
    0000000: 2a2b b801 a4ac 0000 0000 0000 0000 00bf
    0000010:
  Stackmap Table:
    full_frame(@6,{},{Object[#177]})

        at io.vertx.core.Vertx.currentContext(Vertx.java:180)
        at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:175)
        at io.vertx.core.impl.VertxBuilder.vertx(VertxBuilder.java:229)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:255)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:653)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:632)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.initializeRouter(VertxHttpRecorder.java:276)
        at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.VertxHttpProcessor$preinitializeRouter1141331088.deploy(Unknown Source)
        ... 6 more

[INFO] 
[INFO] Results:
[INFO]
[ERROR] Errors: 
[ERROR]   SimpleTest » Runtime java.lang.RuntimeException: Failed to start quarkus

### How to Reproduce?

1. Clone the repo
2. mvnw install -f extensions/funqy

### Output of `java -version`

jdk 17

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

**Comment by geoand** [comment]
Please attach a sample application that exhibits this behavior.

**Comment by jumper404** [comment]
Not from any application. This is coming when I run it the quarkus repo.

**Comment by geoand** [comment]
How do you run the tests?

**Comment by jumper404** [comment]
While running the command -> mvnw install -f extensions/funqy

**Comment by geoand** [comment]
Have you built the entire project before doing that?
