### ISSUE TITLE
Conflict between grpc and hibernate when throwing StatusRuntimeException

### ISSUE THREAD

**Issue by dcdh** [quarkusio/quarkus#39652]
### Describe the bug

I want to throw a StatusRuntimeException when an issue occured while executing a remote call.
The exception can be enriched by adding details as ErrorInfo.

When the service is Transactional (can be needed when downloading a file from a blob datasource) we can notice two issues:
1. The exception message is duplicated
2. The list containing the details is empty (and should not be)

### Expected behavior

The exception can be caught by the client. The exception contains all the detail defined by the server.

### Actual behavior

1. The exception message is duplicated (and should not be)
2. The detail is empty (and should not be)

### How to Reproduce?

1. git clone https://github.com/dcdh/quarkus-grcp-transactional-issue-reproducer
2. Run the tests

To make the test worked you should comment this dependency:
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>
```

But I need it.

### Output of `uname -a` or `ver`

Linux 2a02-8428-dff8-c601-234b-8c10-a3c4-2308.rev.sfr.net 6.6.11-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 10 19:25:59 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17

### Quarkus version or git rev

3.8.3

### Additional information

I guess using `@Transactional` trigger an interceptor. This interceptor does not handle well the StatusRuntimeException in case of grpc.

**Comment by dcdh** [comment]
It fails event if I specify that 

```java
@Transactional(dontRollbackOn = StatusRuntimeException.class)
```

**Comment by dcdh** [comment]
A quick win is to use the default Grpc api when doing transaction. https://github.com/dcdh/quarkus-grcp-transactional-issue-reproducer/blob/default_grpc_api/src/main/java/org/acme/DefaultHelloGrpcService.java

**Comment by yrodiere** [comment]
FWIW here's the exception:

```
io.grpc.StatusRuntimeException: NOT_FOUND: io.smallrye.mutiny.CompositeException - Multiple exceptions caught:
	[Exception 0] io.grpc.StatusRuntimeException: NOT_FOUND: Unknown message
	[Exception 1] io.grpc.StatusRuntimeException: NOT_FOUND: Unknown message
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.quarkus.grpc.runtime.supports.IOThreadClientInterceptor$1$1.onClose(IOThreadClientInterceptor.java:72)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closedInternal(ClientCallImpl.java:750)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:690)
	at io.grpc.internal.DelayedStream$DelayedStreamListener$4.run(DelayedStream.java:510)
	at io.grpc.internal.DelayedStream$DelayedStreamListener.delayOrExecute(DelayedStream.java:462)
	at io.grpc.internal.DelayedStream$DelayedStreamListener.closed(DelayedStream.java:507)
	at io.grpc.internal.ForwardingClientStreamListener.closed(ForwardingClientStreamListener.java:34)
	at io.grpc.internal.InternalSubchannel$CallTracingTransport$1$1.closed(InternalSubchannel.java:691)
	at io.grpc.internal.AbstractClientStream$TransportState.closeListener(AbstractClientStream.java:458)
	at io.grpc.internal.AbstractClientStream$TransportState.access$400(AbstractClientStream.java:221)
	at io.grpc.internal.AbstractClientStream$TransportState$1.run(AbstractClientStream.java:441)
	at io.grpc.internal.AbstractClientStream$TransportState.deframerClosed(AbstractClientStream.java:278)
	at io.grpc.internal.Http2ClientStreamTransportState.deframerClosed(Http2ClientStreamTransportState.java:31)
	at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:234)
	at io.grpc.internal.MessageDeframer.closeWhenComplete(MessageDeframer.java:192)
	at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:201)
	at io.grpc.internal.AbstractClientStream$TransportState.transportReportStatus(AbstractClientStream.java:444)
	at io.grpc.internal.AbstractClientStream$TransportState.transportReportStatus(AbstractClientStream.java:400)
	at io.grpc.internal.AbstractClientStream$TransportState.inboundTrailersReceived(AbstractClientStream.java:383)
	at io.grpc.internal.Http2ClientStreamTransportState.transportTrailersReceived(Http2ClientStreamTransportState.java:183)
	at io.grpc.netty.NettyClientStream$TransportState.transportHeadersReceived(NettyClientStream.java:334)
	at io.grpc.netty.NettyClientHandler.onHeadersRead(NettyClientHandler.java:379)
	at io.grpc.netty.NettyClientHandler.access$1200(NettyClientHandler.java:93)
	at io.grpc.netty.NettyClientHandler$FrameListener.onHeadersRead(NettyClientHandler.java:936)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:437)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:352)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:56)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:476)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:484)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:253)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:188)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by yrodiere** [comment]
Hey @alesj @cescoffier do you think you could have a look?

The problem does seem related to the presence of the Hibernate ORM extension, but I suspect this has more to do with transaction handling and the fact that the Hibernate ORM extension somehow enables non-reactive transaction handling which conflicts with reactive transaction handling... just a guess though.

I tried debugging, and this is where the composite exception gets created:

```
<init>:46, CompositeException (io.smallrye.mutiny)
onFailure:48, MultiOnFailureInvoke$MultiOnFailureInvokeProcessor (io.smallrye.mutiny.operators.multi)
onError:73, MultiSubscriber (io.smallrye.mutiny.subscription)
fail:68, Subscriptions (io.smallrye.mutiny.helpers)
fail:57, Subscriptions (io.smallrye.mutiny.helpers)
subscribe:36, FailedMulti (io.smallrye.mutiny.operators.multi.builders)
withSubscriber:70, MultiSubscribe (io.smallrye.mutiny.groups)
subscribe:29, MultiOnFailureInvoke (io.smallrye.mutiny.operators.multi)
withSubscriber:70, MultiSubscribe (io.smallrye.mutiny.groups)
subscribe:24, MultiOnTerminationInvoke (io.smallrye.mutiny.operators.multi)
withSubscriber:70, MultiSubscribe (io.smallrye.mutiny.groups)
with:218, MultiSubscribe (io.smallrye.mutiny.groups)
with:176, MultiSubscribe (io.smallrye.mutiny.groups)
oneToMany:61, ServerCalls (io.quarkus.grpc.stubs)
invoke:101, MutinyHelloGrpcGrpc$MethodHandlers (org.acme)
onHalfClose:182, ServerCalls$UnaryServerCallHandler$UnaryServerCallListener (io.grpc.stub)
accept:-1, BlockingServerInterceptor$ReplayListener$$Lambda/0x00007f331b795ba0 (io.quarkus.grpc.runtime.supports.blocking)
call:43, BlockingExecutionHandler (io.quarkus.grpc.runtime.supports.blocking)
call:11, BlockingExecutionHandler (io.quarkus.grpc.runtime.supports.blocking)
lambda$executeBlocking$0:177, ContextImpl (io.vertx.core.impl)
handle:-1, ContextImpl$$Lambda/0x00007f331b791578 (io.vertx.core.impl)
dispatch:276, ContextInternal (io.vertx.core.impl)
lambda$internalExecuteBlocking$2:209, ContextImpl (io.vertx.core.impl)
run:-1, ContextImpl$$Lambda/0x00007f331b6866f0 (io.vertx.core.impl)
run:76, TaskQueue (io.vertx.core.impl)
run:-1, TaskQueue$$Lambda/0x00007f331b640eb8 (io.vertx.core.impl)
runWith:582, VertxCoreRecorder$14 (io.quarkus.vertx.core.runtime)
run:2513, EnhancedQueueExecutor$Task (org.jboss.threads)
run:1538, EnhancedQueueExecutor$ThreadBody (org.jboss.threads)
run:29, DelegatingRunnable (org.jboss.threads)
run:29, ThreadLocalResettingRunnable (org.jboss.threads)
run:30, FastThreadLocalRunnable (io.netty.util.concurrent)
runWith:1583, Thread (java.lang)
run:1570, Thread (java.lang)
```

In particular, it seems applying the consumer in this code throws the original exception again (for some reason), and that's why it gets duplicated. Interestingly, the consumer seems to call the transaction interceptor again... might be related? It means that when handling a failure, we attempt to open another transaction?

FWIW the error handler comes from `io.quarkus.grpc.stubs.ServerCalls#oneToMany`.

```
    // io.smallrye.mutiny.operators.multi.MultiOnFailureInvoke.MultiOnFailureInvokeProcessor
    class MultiOnFailureInvokeProcessor extends MultiOperatorProcessor<T, T> {

        public MultiOnFailureInvokeProcessor(MultiSubscriber<? super T> downstream) {
            super(downstream);
        }

        @Override
        public void onFailure(Throwable failure) {
            Flow.Subscription up = getAndSetUpstreamSubscription(CANCELLED);
            MultiSubscriber<? super T> subscriber = downstream;
            if (up != Subscriptions.CANCELLED) {
                try {
                    if (predicate.test(failure)) {
                        callback.accept(failure);
                    }
                } catch (Throwable e) {
                    failure = new CompositeException(failure, e);
                }
                subscriber.onFailure(failure);
            }
        }
    }
```

I'll leave the rest to a reactive guru though, because I'm honestly out of my depth here.

**Comment by dcdh** [comment]
Hello all,
I've just notice that my reproducer is not working as expected.
I will have a look on this this week end to find a proper reproducer.

**Comment by alesj** [comment]
> I've just notice that my reproducer is not working as expected.

What was unexpected?
Since from what @yrodiere found out, it sure does look weird - dups, composite, etc

**Comment by dcdh** [comment]
I am closing this issue because the reproducer is not working and I have found a way inside my project to do it.
@Transactional must not be used at method level, instead I should use from this documentation https://quarkus.io/guides/context-propagation#usage-example-with-mutiny `.emitOn(Infrastructure.getDefaultExecutor())`
