### ISSUE TITLE
[JDK 23/22 EA] quarkus-integration-test-hibernate-search-orm-elasticsearch-outbox-polling native integration test fails due to NumberFormatException

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#39664]
### Describe the bug

We see native integration test failures in Mandrel CI. The `org.awaitability` code doesn't seem to cope with the `23-beta` version string. Failure looks like:

```
 2024-03-25 02:43:30,274 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /test/hibernate-search-outbox-polling/check-agents-running failed, error id: 772a0050-aca3-4693-93bd-e47597e4b754-1: org.jboss.resteasy.spi.UnhandledException: java.lang.NumberFormatException: For input string: "23-beta"
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:107)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:344)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:205)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:452)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invokePropagateNotFound$6(SynchronousDispatcher.java:275)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invokePropagateNotFound(SynchronousDispatcher.java:260)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:84)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:97)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@23-beta/java.lang.Thread.runWith(Thread.java:1588)
	at java.base@23-beta/java.lang.Thread.run(Thread.java:1575)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:836)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:812)
Caused by: java.lang.NumberFormatException: For input string: "23-beta"
	at java.base@23-beta/java.lang.Integer.parseInt(Integer.java:588)
	at java.base@23-beta/java.lang.Integer.parseInt(Integer.java:685)
	at org.awaitility.core.JavaVersionDetector.getJavaMajorVersion(JavaVersionDetector.java:21)
	at org.awaitility.core.LambdaErrorMessageGenerator.getLambdaDetectionClassName(LambdaErrorMessageGenerator.java:86)
	at org.awaitility.core.LambdaErrorMessageGenerator.isLambdaClass(LambdaErrorMessageGenerator.java:30)
	at org.awaitility.core.AssertionCondition.generateDescriptionPrefix(AssertionCondition.java:87)
	at org.awaitility.core.AssertionCondition.getMatchMessage(AssertionCondition.java:73)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:54)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base@23-beta/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base@23-beta/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@23-beta/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	... 4 more
```

See for example here:
https://github.com/graalvm/mandrel/actions/runs/8413746359/job/23037180271#step:12:1589

**Comment by jerboaa** [comment]
Upstream issue: https://github.com/awaitility/awaitility/issues/277

**Comment by marko-bekhta** [comment]
I think we can close this one now since awaitility was bumped to 4.2.2 in https://github.com/quarkusio/quarkus/pull/42385  and it includes the fix for https://github.com/awaitility/awaitility/issues/277

**Comment by jerboaa** [comment]
Agreed. Closing it now.
