### ISSUE TITLE
ChainBuildException: Cycle Detected, when Using Liquibase Extension Together with Metrics and  Hibernate-Orm

### ISSUE THREAD

**Issue by gcw-it** [quarkusio/quarkus#39660]
### Describe the bug

When deploying a project using the liquibase, smallrye-metrics and hibernate-orm  extensions  together a  ChainBuildException: Cycle Detected is thrown.

### Expected behavior

The project is deployed without throwing an exception.

### Actual behavior

The following exception is thrown:

java.lang.RuntimeException: io.quarkus.builder.ChainBuildException: Cycle detected:
		   io.quarkus.arc.deployment.ArcProcessor#signalBeanContainerReady produced class io.quarkus.arc.deployment.BeanContainerBuildItem
		to io.quarkus.liquibase.deployment.LiquibaseProcessor#startLiquibase produced class io.quarkus.agroal.spi.JdbcDataSourceSchemaReadyBuildItem
		to io.quarkus.hibernate.orm.deployment.metrics.HibernateOrmMetricsProcessor#metrics produced class io.quarkus.deployment.metrics.MetricsFactoryConsumerBuildItem
		to io.quarkus.smallrye.metrics.deployment.SmallRyeMetricsProcessor#extensionMetrics produced class io.quarkus.arc.deployment.UnremovableBeanBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#validate produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#validateAsyncObserverExceptionHandlers produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem$ValidationErrorBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#generateResources produced class io.quarkus.arc.deployment.ResourcesGeneratedPhaseBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#initializeContainer produced class io.quarkus.arc.deployment.ArcContainerBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#notifyBeanContainerListeners produced class io.quarkus.arc.deployment.PreBeanContainerBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#signalBeanContainerReady
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:334)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:251)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:112)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:433)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.ChainBuildException: Cycle detected:
		   io.quarkus.arc.deployment.ArcProcessor#signalBeanContainerReady produced class io.quarkus.arc.deployment.BeanContainerBuildItem
		to io.quarkus.liquibase.deployment.LiquibaseProcessor#startLiquibase produced class io.quarkus.agroal.spi.JdbcDataSourceSchemaReadyBuildItem
		to io.quarkus.hibernate.orm.deployment.metrics.HibernateOrmMetricsProcessor#metrics produced class io.quarkus.deployment.metrics.MetricsFactoryConsumerBuildItem
		to io.quarkus.smallrye.metrics.deployment.SmallRyeMetricsProcessor#extensionMetrics produced class io.quarkus.arc.deployment.UnremovableBeanBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#validate produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#validateAsyncObserverExceptionHandlers produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem$ValidationErrorBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#generateResources produced class io.quarkus.arc.deployment.ResourcesGeneratedPhaseBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#initializeContainer produced class io.quarkus.arc.deployment.ArcContainerBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#notifyBeanContainerListeners produced class io.quarkus.arc.deployment.PreBeanContainerBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#signalBeanContainerReady
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:327)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
	at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:300)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:331)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:291)
	at io.quarkus.builder.BuildChainBuilder.detectCycles(BuildChainBuilder.java:284)
	at io.quarkus.builder.BuildChainBuilder.build(BuildChainBuilder.java:157)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:142)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	... 9 more

### How to Reproduce?

1. Create a standard Project: quarkus create app com.test:quarkus-failuretest
2. Add Extensions: quarkus-smallrye-metrics, quarkus-hibernate-orm, quarkus-liquibase
3. Run the app: man quarks:dev

### Output of `uname -a` or `ver`

Darwin 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_X86_64 x86_64

### Output of `java -version`

java 21.0.2 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

### Quarkus version or git rev

3.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by geoand** [comment]
Thanks for reporting.

This is a duplicate (can't find the original right now) and will be fixed in 3.8.4

**Comment by yrodiere** [comment]
> can't find the original right now

#39468 , most likely.

**Comment by geoand** [comment]
🙏
