### ISSUE TITLE
getValue() errors with config property is required when config value is marked as Optional

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#39693]
### Description

I'm not sure this can be fixed but thought I would open it in case others gets  confused.

I have this code:

```java
@ConfigRoot(phase = ConfigPhase.RUN_TIME)
@ConfigMapping(prefix = "quarkus.homeassistant")
public interface HomeAssistantConfig {
    Optional<String> token();
}
```

and on startup using that extension I got this error:

```
The config property quarkus.homeassistant.token is required but it could not be found in any config source
        at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:369)
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:314)
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:293)
        at io.quarkiverse.homeassistant.deployment.HomeAssistantProcessor.userConfigured(HomeAssistantProcessor.java:131)
        at io.quarkiverse.homeassistant.deployment.HomeAssistantProcessor.starthomeassistant(HomeAssistantProcessor.java:109)
        at io.quarkiverse.homeassistant.deployment.HomeAssistantProcessor.starthomeassistantDevService(HomeAssistantProcessor.java:71)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

I spent way too long wondering why it was saying the value was required when I cleared made the type as optional.

Turned out I had code that did this:

```
 String token = config.getValue("quarkus.homeassistant.token", String.class);
```

which I assume implies it is required.

Just wondering if we can do better on that exception message because its not marked as required in the config types...but the method is asking as if it is.

**Comment by radcortez** [comment]
The config types and the config API work separately. Actually, the config mapping is populated calling the API methods from `SmallRyeConfig`.

In this case, I'm unsure how we can improve it. In the `getValue` javadocs:

_The result of this method is identical to the result of calling getOptionalValue(propertyName, propertyType).get(). In particular, If the given property name or the value element of this property does not exist, the java. util. NoSuchElementException is thrown. This method never returns null._

Also, the types don't match between the programmatic call and the config type. If the configuration is optional, what should we return when calling `String getValue`? That is why we have an `Optional<String> getOptionalValue`.

We could implement some checker, that validates if the declared type for a given property name matches when the same name is used in the programmatic API.
