### ISSUE TITLE
Bean Param init issue -  java.lang.NoClassDefFoundError: io/quarkus/generated/int$quarkusrestparamConverter$

### ISSUE THREAD

**Issue by JoaoBrandao** [quarkusio/quarkus#39777]
### Describe the bug

Application not able to start due to an error related with initialisation of Bean Param in a resource class

**Pagination Class**

```java
public class PageRequest implements Page {

  @QueryParam("page")
  @DefaultValue("1")
  int page;

  @QueryParam("pageSize")
  @DefaultValue("20")
  int pageSize;

  public PageRequest() {
  }

  PageRequest(final int page, final int pageSize) {
    this.page = page;
    this.pageSize = pageSize;
  }
...
}
```

**Usage of PageRequest class**

`Response get(@BeanParam PageRequest page, @QueryParam("type") NotificationType type);`

### Expected behavior

Able to inject bean parameter and build project

### Actual behavior

```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 18.85 s <<< FAILURE! -- in com.app.integration.AssetsResourceIntegrationTest
[ERROR] com.app.integration.AssetsResourceIntegrationTest.testIfAbleToCreateAssets -- Time elapsed: 0.004 s <<< ERROR!
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:643)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:727)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:269)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:252)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:610)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:660)
        ... 1 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 8 more
Caused by: java.lang.NoClassDefFoundError: io/quarkus/generated/int$quarkusrestparamConverter$
        at com.app.pagination.PageRequest.__quarkus_init_converter__page(PageRequest.java)
        at io.quarkus.rest.runtime.__QuarkusInit.init(Unknown Source)
        at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder.createDeployment(ResteasyReactiveRecorder.java:152)
        at io.quarkus.deployment.steps.ResteasyReactiveProcessor$setupDeployment713137389.deploy_17(Unknown Source)
        at io.quarkus.deployment.steps.ResteasyReactiveProcessor$setupDeployment713137389.deploy(Unknown Source)
```

### How to Reproduce?

**Reproduce simple way:**

1. Create Project
2. Create class type of Bean Param
3. Use that bean param in a resource  API parameters
4. Build project (mvn clean install)

**Reproduce the same way:**
Reproduce:
1. Create project
2. Create Bean Param class in a library
3. Create another project
5. Import library in that project
6. Use that bean parameter as resource parameter
7. Build project (mvn clean install)

### Output of `uname -a` or `ver`

Darwin LIS-C-000XT 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)

### Quarkus version or git rev

3.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4

### Additional information

- Related problem has been found here: https://github.com/quarkusio/quarkus/issues/39598
- With Quarkus Framework v3.8.2 the issues does not exist

**Comment by kjq** [comment]
This sounds like our issue somewhat - https://github.com/quarkusio/quarkus/issues/39773#issuecomment-2025252560

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/39691 is definitely at fault...

**Comment by geoand** [comment]
> This sounds like our issue somewhat - [#39773 (comment)](https://github.com/quarkusio/quarkus/issues/39773#issuecomment-2025252560)

Yeah...

**Comment by geoand** [comment]
It would be super helpful to have a reproducer for both cases mentioned in the description. 
The reason is that I would like to be able to test both this and what https://github.com/quarkusio/quarkus/pull/39691 was intending to fix.

**Comment by kjq** [comment]
Ill try to put one together.

**Comment by geoand** [comment]
🙏

**Comment by kjq** [comment]
Reproducer here https://github.com/quarkusio/quarkus/issues/39773#issuecomment-2030493539
