### ISSUE TITLE
Kafka fails with multiple emitters(Emitter & MultinyEmitter) on the same channel

### ISSUE THREAD

**Issue by kennylam91** [quarkusio/quarkus#39821]
### Describe the bug

Using kafka reactive messaging, when creating 2 emitters(Emitter & MultinyEmitter) for one channel, the Quarkus app fails to start and throws the following exception:
`
@Inject
    @Channel("words-out")
    Emitter<String> emitter;

    @Inject
    @Channel("words-out")
    MutinyEmitter<String> mutinyEmitter;
`
`2024-04-02 11:43:43,741 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (Aesh InputStream Reader) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.reactivemessaging.deployment.SmallRyeReactiveMessagingProcessor#build threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Emitter configuration for channel `words-out` is different than previous configuration : QuarkusEmitterConfiguration{name='words-out', emitterType=io.quarkus.smallrye.reactivemessaging.runtime.EmitterFactoryForLiteral@78573ac8, overflowBufferStrategy=BUFFER, overflowBufferSize=-1, broadcast=false, numberOfSubscriberBeforeConnecting=-1}
        at io.quarkus.smallrye.reactivemessaging.deployment.SmallRyeReactiveMessagingProcessor.build(SmallRyeReactiveMessagingProcessor.java:308)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)`

### Expected behavior

Two emitters for the same channel should not cause any problem. 

### How to Reproduce?

I've create a reproducer here: https://github.com/kennylam91/quarkus-multiple-kafka-emitters-issue-reproducer

### Output of `java -version`

openjdk 17.0.7

### Quarkus version or git rev

3.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.3

### Additional information

The multiple emitter configuration worked well with 3.2.
I encounted this issue when upgrading Quarkus from 3.2 to 3.8.

**Comment by cescoffier** [comment]
You cannot inject an emitter multiple times. You would need different channels and merge them:

```java
@Channel("c1") Emitter<X> emitter1;
@Channel("c2") Emitter<X> emitter2;

@Incoming("c1")
@Incoming("c2")
@Outgoing("my-channel")
X merge(X x) { return x; }
```

**Comment by kennylam91** [comment]
Hi @cescoffier , thanks for your comment. 
It's true that we can have multiple channels and merge them. But actually we also can have one emitter and inject it multiple times like this:
```
@Inject
@Channel("words-out")
Emitter<String> emitter1;

@Inject
@Channel("words-out")
Emitter<String> emitter2;
```
I tested and it's working fine. 
There's a similar issue which was fixed here: https://github.com/quarkusio/quarkus/issues/38054
So I think maybe this is another case.

**Comment by ozangunalp** [comment]
Indeed #38054 was a bug and you can now inject the same emitter multiple times, but it needs to be of the same type. 
There are no plans to support multiple emitter facets of the same channel.
