### ISSUE TITLE
Deserialization Errors during test classloading

### ISSUE THREAD

**Issue by AlanMasciangelo** [quarkusio/quarkus#39847]
### Describe the bug

On Quarkus 3.9.1 we are seeing an error attempting to run `@QuarkusTest` in a gradle test task. Here is our task definitions

```groovy
test {
    useJUnitPlatform {
        excludeTags 'QuarkusTest'
    }
}

task runQuarkusTests(type: Test) {
    useJUnitPlatform {
        includeTags 'QuarkusTest'
    }
}
```

This occurs when attempting to run our custom runQuarkusTests task. We first saw this on a previous version but were able to use the workaround provided in https://github.com/quarkusio/quarkus/issues/36812

### Expected behavior

Tests tagged with `@QuarkusTest` run

### Actual behavior

```
java.lang.RuntimeException: java.lang.ClassCastException: class io.quarkus.builder.BuildChainBuilder cannot be cast to class io.quarkus.builder.BuildChainBuilder (io.quarkus.builder.BuildChainBuilder is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @3d764641; io.quarkus.builder.BuildChainBuilder is in unnamed module of loader 'app')
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:643)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:727)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ClassCastException: class io.quarkus.builder.BuildChainBuilder cannot be cast to class io.quarkus.builder.BuildChainBuilder (io.quarkus.builder.BuildChainBuilder is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @3d764641; io.quarkus.builder.BuildChainBuilder is in unnamed module of loader 'app')
	at io.quarkus.test.junit.QuarkusTestExtension$TestBuildChainFunction$1.accept(QuarkusTestExtension.java:1278)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:130)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:251)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:224)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:610)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:660)
	... 1 more
```

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045

### Output of `java -version`

 17.0.5 (Eclipse Adoptium 17.0.5+8)

### Quarkus version or git rev

3.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

**Comment by AlanMasciangelo** [comment]
I believe I've resolved this by excluding the `integrationTests` group from my test task based on https://docs.gradle.org/current/userguide/java_testing.html#test_grouping

```
task runQuarkusTests(type: Test) {
    useTestNG {
        excludeGroups 'integrationTests'
    }
    useJUnitPlatform {
        includeTags 'QuarkusTest'
    }
}
```

My assumption is having `io.quarkus:quarkus-bootstrap-runner` on both the `test` and `integrationTest` classpath causes this conflict.

**Comment by geoand** [comment]
Is this still an issue with the latest versions of Quarkus?

**Comment by geoand** [comment]
Closing for lack of feedback
