### ISSUE TITLE
Apache Pulsar NoClassDefFoundError

### ISSUE THREAD

**Issue by garrettahines1** [quarkusio/quarkus#39935]
### Describe the bug

When using the Quarkus plugin for Apache Pulsar I get the following error message:

```
2024-04-07 20:08:39,489 WARN  [org.apa.pul.cli.imp.ProducerImpl] (vert.x-eventloop-thread-13) [test] [test_outgoing] error while create opSendMsg by batch message container: java.lang.NoClassDefFoundError: com/scurrilous/circe/checksum/Crc32cIntChecksum
        at org.apache.pulsar.common.protocol.Commands.serializeCommandSendWithSize(Commands.java:1650)
        at org.apache.pulsar.common.protocol.Commands.newSend(Commands.java:568)
        at org.apache.pulsar.common.protocol.Commands.newSend(Commands.java:515)
        at org.apache.pulsar.client.impl.ProducerImpl.sendMessage(ProducerImpl.java:854)
        at org.apache.pulsar.client.impl.BatchMessageContainerImpl.createOpSendMsg(BatchMessageContainerImpl.java:255)
        at org.apache.pulsar.client.impl.ProducerImpl.batchMessageAndSend(ProducerImpl.java:2166)
        at org.apache.pulsar.client.impl.ProducerImpl.batchFlushTask(ProducerImpl.java:2149)
        at org.apache.pulsar.common.util.Runnables$CatchingAndLoggingRunnable.run(Runnables.java:54)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: com.scurrilous.circe.checksum.Crc32cIntChecksum
        ... 18 more
```

I have tr

### Expected behavior

Successfully send the message to the pulsar broker.

### Actual behavior

Receive error message above.

### How to Reproduce?

1. Create app using Quarkus version 3.8.8
2. Include apache pulsar dependency
3. Send message with the following code

```
@Path("/")
public class Resource {

    @Channel("test_outgoing")
    Emitter<String> emitter;

    @GET
    public Uni<Void> sendObj() {
        System.out.println(">> Sending message");
        return Uni.createFrom().completionStage(emitter.send("HELLO WORLD"));
    }

}
```

4. configure connection with 

```
mp:
  messaging:
    outgoing:
      test_outgoing:
        serviceUrl: pulsar://pulsar:6650
        connector: smallrye-pulsar
        topic: test
```

### Output of `java -version`

eclipse-temurin:21-jdk

### Quarkus version or git rev

3.8.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

### Additional information

I see that the missing class comes from a .nar file which I assume means it won't work on windows which is why I tried building it with eclipse-temurin:21-jdk docker image and then running with registry.access.redhat.com/ubi8/openjdk-21:1.18.

**Comment by garrettahines1** [comment]
looks like compiling with maven works instead of gradle as gradle only downloads the .nar file and maven downloads the everything. Any idea why that may be? is there a way to use gradle with the pulsar plugin?

**Comment by ozangunalp** [comment]
I've investigated this issue in here with some workarounds: https://github.com/smallrye/smallrye-reactive-messaging/discussions/2567#discussioncomment-9042159

Unfortunately, I don't see any way we can fix this.

**Comment by ozangunalp** [comment]
@garrettahines1 it'd be awesome if you can come up with a way to fix it otherwise I'll close this as a won't fix.

**Comment by garrettahines1** [comment]
sounds good, not sure how I didn't see the smallrye issue when I was searching. thanks for the link.
