### ISSUE TITLE
SmallRyeGraphQLClientProcessor#buildClientModel threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.Type.name()" because the return value of "org.jboss.jandex.ClassInfo.superClassType()" is null

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#39931]
### Describe the bug

Since Quarkus 3.9 we get the following exception during the build if `io.quarkus:quarkus-smallrye-openapi` and `io.quarkus:quarkus-smallrye-graphql-client` are on the classpath:

```
> Task :quarkusAppPartsBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.smallrye.graphql.client.deployment.SmallRyeGraphQLClientProcessor#buildClientModel threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.Type.name()" because the return value of "org.jboss.jandex.ClassInfo.superClassType()" is null
                at io.smallrye.graphql.client.model.helper.TypeModel.fields(TypeModel.java:389)
                at io.smallrye.graphql.client.model.helper.TypeModel.fields(TypeModel.java:389)
                at io.smallrye.graphql.client.model.helper.TypeModel.fields(TypeModel.java:377)
                at io.smallrye.graphql.client.model.helper.OperationModel.recursionCheckedFields(OperationModel.java:103)
                at io.smallrye.graphql.client.model.helper.OperationModel.fields(OperationModel.java:75)
                at io.smallrye.graphql.client.model.helper.OperationModel.recursionCheckedFields(OperationModel.java:94)
                at io.smallrye.graphql.client.model.helper.OperationModel.fields(OperationModel.java:75)
                at io.smallrye.graphql.client.model.QueryBuilder.build(QueryBuilder.java:54)
                at io.smallrye.graphql.client.model.ClientModelBuilder.lambda$generateClientModels$0(ClientModelBuilder.java:62)
                at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
                at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
                at io.smallrye.graphql.client.model.ClientModelBuilder.lambda$generateClientModels$1(ClientModelBuilder.java:61)
                at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
                at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
                at io.smallrye.graphql.client.model.ClientModelBuilder.generateClientModels(ClientModelBuilder.java:57)
                at io.smallrye.graphql.client.model.ClientModelBuilder.build(ClientModelBuilder.java:38)
                at io.quarkus.smallrye.graphql.client.deployment.SmallRyeGraphQLClientProcessor.buildClientModel(SmallRyeGraphQLClientProcessor.java:205)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
                at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
                at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
                at java.base/java.lang.Thread.run(Thread.java:840)
                at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```

### How to Reproduce?

1. Download [reproducer.zip](https://github.com/quarkusio/quarkus/files/14898127/reproducer.zip)
2. `./gradlew clean build`

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.9.2

**Comment by jmartisk** [comment]
We already have a PR for this: https://github.com/smallrye/smallrye-graphql/pull/2077
I'll merge it in a bit and release SmallRye GraphQL 2.8.2 this week

**Comment by jmartisk** [comment]
fixed by https://github.com/quarkusio/quarkus/pull/39938, this should get into Quarkus 3.10.0 and 3.9.3
