### ISSUE TITLE
Quarkus 3.9.2 [Native image] - jcifs-ng - bouncycastle no such algorithm issue

### ISSUE THREAD

**Issue by senzu** [quarkusio/quarkus#39951]
### Describe the bug

Hi!

I'm trying to make jcifs-ng work (which uses bouncycastle) in native image, but somehow I'm always getting java.security.NoSuchAlgorithmException.

My **pom.xml** looks like this:

`<dependency>`
  `<groupId>io.quarkus</groupId>`
  `<artifactId>quarkus-security</artifactId>`
`</dependency>`

`<dependency>`
  `<groupId>org.bouncycastle</groupId>`
  `<artifactId>bcprov-jdk18on</artifactId>`
`</dependency>`

`<dependency>`
  `<groupId>eu.agno3.jcifs</groupId>`
  `<artifactId>jcifs-ng</artifactId>`
  `<version>2.1.10</version>`
`</dependency>`

In the **application.properties** file I've put the following line:

quarkus.security.security-providers=BC

When I'm trying to connect, I'm getting the following error:

`Caused by: jcifs.CIFSUnsupportedCryptoException: java.security.NoSuchAlgorithmException: no such algorithm: MD4 for provider BC`
        `at jcifs.util.Crypto.getMD4(Crypto.java:59)`
        `at jcifs.smb.NtlmUtil.getNTHash(NtlmUtil.java:135)`
        `at jcifs.ntlmssp.Type3Message.<init>(Type3Message.java:203)`
        `at jcifs.ntlmssp.Type3Message.<init>(Type3Message.java:130)`
        `at jcifs.smb.NtlmContext.createType3Message(NtlmContext.java:326)`
        `at jcifs.smb.NtlmContext.makeAuthenticate(NtlmContext.java:269)`
        `... 36 more`
`Caused by: java.security.NoSuchAlgorithmException: no such algorithm: MD4 for provider BC`
        `at java.base@21.0.2/sun.security.jca.GetInstance.getService(GetInstance.java:101)`
        `at java.base@21.0.2/sun.security.jca.GetInstance.getInstance(GetInstance.java:218)`
        `at java.base@21.0.2/java.security.Security.getImpl(Security.java:684)`
        `at java.base@21.0.2/java.security.MessageDigest.getInstance(MessageDigest.java:300)`
        `at jcifs.util.Crypto.getMD4(Crypto.java:56)`
        `... 41 more`

I've tried the following methods, with no success:

`@RegisterForReflection(targets=jcifs.util.Crypto.class)`
`public class CryptoConfiguration {`
`}`

`@RegisterForReflection(targets=org.bouncycastle.jce.provider.BouncyCastleProvider.class)`
`public class BouncyCastleProviderConfiguration {`
`}`

Could you please help me to resolve the issue?

Thank you,
Viktor

### Output of `java -version`

21.0.2+13-LTS, vendor version: Mandrel-23.1.2.0-Final

### Quarkus version or git rev

3.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

**Comment by geoand** [comment]
I was not able to reproduce the problem, so please attach a sample application that behaves as you describe.

Thanks

**Comment by senzu** [comment]
Hi!

Sorry for the late answer. I think in my case this was jcifs-ng issue, I was in a hurry, so I switched jcifs-ng to smbj with the following dependency:

`<dependency>`
  `<groupId>com.hierynomus</groupId>`
  `<artifactId>smbj</artifactId>`
  `<version>0.13.0</version>`
`</dependency>`

smbj uses bouncycastle too, so I left the quarkus-security and bouncycastle dependencies in pom.xml, and the quarkus.security.security-providers=BC line in application.properties.

I just needed to add 2 configuration classes, and it worked like a charm.

`@RegisterForReflection(targets=com.hierynomus.smbj.auth.SpnegoAuthenticator.class)`
`public class SpnegoAuthenticatorConfiguration {`
`}`

`@RegisterForReflection(targets=com.hierynomus.smbj.auth.SpnegoAuthenticator.Factory.class)`
`public class SpnegoAuthenticatorFactoryConfiguration {`
`}`

I'm sorry to have stolen your time. This issue can be closed. If you want to investigate it, I will create a sample application with jcifs-ng as soon as I have time, if you give me your contact information, I will be happy to send it when it is ready. Or should this issue keep opened until then and should I put it here?

Thank you,
Viktor

**Comment by geoand** [comment]
Thanks for the update!

I am going to close this as neither `jcifs-ng` nor `smbj` have extensions that would make them work in native mode.
