### ISSUE TITLE
Jib can't authenticate to the docker.io registry

### ISSUE THREAD

**Issue by dodalovicgran** [quarkusio/quarkus#39983]
### Describe the bug

I'm trying to build and push stuff to my private registry:

```
* What went wrong:
Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
                at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:270)
                at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:195)
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
                at java.base/java.lang.reflect.Method.invoke(Method.java:580)
                at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
                at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
                at java.base/java.lang.Thread.run(Thread.java:1583)
                at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Caused by: com.google.cloud.tools.jib.api.RegistryAuthenticationFailedException: Failed to authenticate with registry registry-1.docker.io/gransoftware/time-tracker-backend because: 401 Unauthorized
        GET https://auth.docker.io/token?service=registry.docker.io&scope=repository:gransoftware/time-tracker-backend:pull,push
        {"details":"incorrect username or password"}
        
                at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticate(RegistryAuthenticator.java:305)
                at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticate(RegistryAuthenticator.java:257)
                at com.google.cloud.tools.jib.registry.RegistryAuthenticator.authenticatePush(RegistryAuthenticator.java:190)
                at com.google.cloud.tools.jib.registry.RegistryClient.doBearerAuth(RegistryClient.java:336)
                at com.google.cloud.tools.jib.registry.RegistryClient.doBearerAuth(RegistryClient.java:326)
                at com.google.cloud.tools.jib.registry.RegistryClient.doPushBearerAuth(RegistryClient.java:308)
                at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:66)
                at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:35)
                at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
                at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
                at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
                at java.base/java.lang.Thread.run(Thread.java:1583)
        Caused by: com.google.cloud.tools.jib.http.ResponseException: 401 Unauthorized
        GET https://auth.docker.io/token?service=registry.docker.io&scope=repository:gransoftware/time-tracker-backend:pull,push
        {"details":"incorrect username or password"}
        

```

**Comment by dodalovicgran** [comment]
```yaml
  jib:
    base-jvm-image: "registry.access.redhat.com/ubi8/openjdk-21-runtime:1.18"
  container-image:
    registry: docker.io
    group: gransoftware
    name: time-tracker-backend
    additional-tags: latest
    build: true
    push: true
    username: gransoftware
```

I have `QUARKUS_CONTAINER_IMAGE_PASSWORD=xxx-yyy` as an ENV var

**Comment by geoand** [comment]
I just tried the exact scenario and it worked for me as expected

**Comment by dodalovicgran** [comment]
```
docker -v         
Docker version 25.0.4-rd, build c4cd0a9
```

I'm on Pop!_OS 22.04 LTS Linux

what's the setup there?

**Comment by geoand** [comment]
`Docker version 26.0.0, build 2ae903e` on `Ubuntu 22.04`

**Comment by dodalovicgran** [comment]
Same for me, weird. 
Is this Docker Desktop or Docker Engine? I'm using Docker Desktop

**Comment by geoand** [comment]
No Docker Desktop installed on my machine

**Comment by dodalovicgran** [comment]
@geoand 

```
java -version 
openjdk version "21.0.2" 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13-58)
OpenJDK 64-Bit Server VM (build 21.0.2+13-58, mixed mode, sharing)
```

@ your end?

**Comment by geoand** [comment]
It should not matter, but I am using:

```
java -version
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)
```

**Comment by geoand** [comment]
Where you able to get this working

**Comment by dodalovicgran** [comment]
No, @geoand, unfortunately - I have no solution to this.

**Comment by dodalovicgran** [comment]
What are the prerequisites for this to work?

**Comment by dodalovicgran** [comment]
@geoand I updated to quarkus `3.10.2`, but it didn't help. 
I'm not sure what are the prerequisites for this tech to work on linux...

**Comment by geoand** [comment]
I use Linux and it works as expected, so I am not sure what the problem is

**Comment by geoand** [comment]
Not as far as I am aware

**Comment by dodalovicgran** [comment]
Is there anything I can do to troubleshoot this issue? |
Wasn't able to deploy my changes for months now :(

**Comment by geoand** [comment]
I wish I had more info for you, but I have never experienced the issue so I am out of suggestions...

**Comment by dodalovicgran** [comment]
May I ask you to install docker on the machine you're testing with? Just to figure out the impact of docker being there.

**Comment by dodalovicgran** [comment]
May I ask you to install docker on the machine you're testing with. Just to figure out the impact of docker being there.

**Comment by geoand** [comment]
I always had docker :)

**Comment by dodalovicgran** [comment]
I managed to fix the thing. 
The problem was in front of the computer.

Thank you @geoand for all the support

**Comment by geoand** [comment]
What as the problem?

**Comment by dodalovicgran** [comment]
I had an outdated QUARKUS_CONTAINER_IMAGE_PASSWORD which took precedence over the one defined in `${PROJECT_ROOT}/.env` one. 🤔

**Comment by geoand** [comment]
ouch :)

**Comment by dodalovicgran** [comment]
is this expected behavior?

**Comment by geoand** [comment]
Environment variables have higher priority - only system properties have a higher one
