### ISSUE TITLE
Log file rotation for periods longer then day not working. Regression.

### ISSUE THREAD

**Issue by alex-pumpkin** [quarkusio/quarkus#40016]
### Describe the bug

Since 3.4.x it is not possible to use logging file rotation periods longer then a day, for example `quarkus.log.file.rotation.file-suffix=.yyyy-MM`. Application doesn't start.

### Expected behavior

Application starts successfully

### Actual behavior

```
2024-04-11 14:29:17,108 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unit is too large to be used for truncation
        at java.base/java.time.LocalTime.truncatedTo(LocalTime.java:978)
        at java.base/java.time.LocalDateTime.truncatedTo(LocalDateTime.java:1118)
        at java.base/java.time.ZonedDateTime.truncatedTo(ZonedDateTime.java:1527)
        at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.calcNextRollover(PeriodicRotatingFileHandler.java:254)
        at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.setSuffix(PeriodicRotatingFileHandler.java:197)
        at io.quarkus.runtime.logging.LoggingSetupRecorder.configureFileHandler(LoggingSetupRecorder.java:602)
        at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLogging(LoggingSetupRecorder.java:173)
        at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2024815463.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2024815463.deploy(Unknown Source)
        ... 13 more

```

### How to Reproduce?

1. Download or clone [getting-started example](https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started)
2. Modify application.properties, add
    ```
    quarkus.log.file.enable=true
    quarkus.log.file.rotation.file-suffix=.yyyy-MM
    ```
3. run ./mvnw compile quarkus:dev

### Additional information

The solution is quite simple. There is a [PR](https://github.com/jboss-logging/jboss-logmanager/pull/468) to fix it. But it should be integrated to Quarkus after releasing new version of jboss-logmanager

**Comment by jamezp** [comment]
No, that should still work and if it doesn't it's a bug. I can't look right now as I'm in the middle of something else, but I can likely look later today or tomorrow.

**Comment by geoand** [comment]
🙏🏼

**Comment by alex-pumpkin** [comment]
Actually there is a pull request to fix it https://github.com/jboss-logging/jboss-logmanager/pull/468

Please take a look when it's convenient for you @jamezp

**Comment by jamezp** [comment]
I did a 3.0.5.Final release today which includes this fix and dependabot should pick it up.

**Comment by jamezp** [comment]
Well, crap. I missed this commit when creating the branch I guess... ...3.0.6.Final incoming.
