### ISSUE TITLE
Reactive Oracle Client IT does not work anymore

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#40020]
### Describe the bug

The reactive Oracle client IT does not work anymore. Seems it cannot connect to the database.
The compilation works.

### Expected behavior

Tests should be passing

### Actual behavior

Tests do not pass:

```

Caused by: java.sql.SQLException: ORA-12541: Cannot connect. No listener at host localhost port 1521. (CONNECTION_ID=08LMZkatRPCJgMKpweaxVw==)
https://docs.oracle.com/error-help/db/ora-12541/
        at oracle.jdbc.driver.T4CConnection.handleLogonNetException(T4CConnection.java:1398)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:991)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1157)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:104)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:825)
        at oracle.jdbc.datasource.impl.OracleDataSource.getPhysicalConnection(OracleDataSource.java:707)
        at oracle.jdbc.datasource.impl.OracleDataSource.getConnection(OracleDataSource.java:381)
        at oracle.jdbc.datasource.impl.OracleDataSource.getConnectionInternal(OracleDataSource.java:2206)
        at oracle.jdbc.datasource.impl.OracleDataSource$1.build(OracleDataSource.java:1915)
        at oracle.jdbc.datasource.impl.OracleDataSource$1.build(OracleDataSource.java:1849)
        at io.vertx.oracleclient.impl.OracleConnectionFactory.lambda$connect$0(OracleConnectionFactory.java:75)
        at io.vertx.oracleclient.impl.Helper$SQLBlockingCodeHandler.handle(Helper.java:306)
        at io.vertx.oracleclient.impl.Helper$SQLBlockingCodeHandler.handle(Helper.java:298)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@22/java.lang.Thread.runWith(Thread.java:1583)
        at java.base@22/java.lang.Thread.run(Thread.java:1570)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:853)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:829)
Caused by: oracle.net.ns.NetException: ORA-12541: Cannot connect. No listener at host localhost port 1521. (CONNECTION_ID=08LMZkatRPCJgMKpweaxVw==)
https://docs.oracle.com/error-help/db/ora-12541/
        at oracle.net.nt.TcpNTAdapter.establishSocket(TcpNTAdapter.java:311)
        at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:222)
        at oracle.net.nt.ConnOption.connect(ConnOption.java:327)
        at oracle.net.nt.ConnStrategy.executeConnOption(ConnStrategy.java:1144)
        at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:718)
        at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:707)
        at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:938)
        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:327)
        at oracle.jdbc.driver.T4CConnection.connectNetworkSessionProtocol(T4CConnection.java:3185)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:926)
        ... 25 more

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.529 s <<< FAILURE! -- in io.quarkus.it.reactive.oracle.client.NativeFruitsEndpointIT
[ERROR] io.quarkus.it.reactive.oracle.client.NativeFruitsEndpointIT.testListAllFruits -- Time elapsed: 0.084 s <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.

        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
        at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
        at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
        at io.restassured.specification.ResponseSpecification$statusCode$1.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
        at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
        at io.quarkus.it.reactive.oracle.client.FruitsEndpointTest.testListAllFruits(FruitsEndpointTest.java:18)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:821)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   HealthCheckIT>HealthCheckTest.testHealthCheck:20 2 expectations failed.
JSON path status doesn't match.
Expected: is "UP"
  Actual: DOWN

JSON path checks.status doesn't match.
Expected: iterable with items ["UP"] in any order
  Actual: <[DOWN]>

[ERROR]   NativeFruitsEndpointIT>FruitsEndpointTest.testListAllFruits:18 1 expectation failed.
Expected status code <200> but was <500>.

[INFO] 
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0

```

### How to Reproduce?

```
cd /integration-tests/reactive-oracle-client
mvn clean verify -Dtest-containers -Dstart-containers -Dnative
```

**Comment by cescoffier** [comment]
it's actually working on CI....
