### ISSUE TITLE
UpdateTimestamp(source = SourceType.DB) + @SoftDelete produces an error

### ISSUE THREAD

**Issue by williammadie** [quarkusio/quarkus#40114]
### Describe the bug

Adding the @SoftDelete annotation to an entity AND declaring an attribute like the following one breaks Hibernate:

`@UpdateTimestamp(source = SourceType.DB)
    private LocalDateTime lastUpdateOn;`

Apparently, it is specifically the `SourceType.DB` that breaks. `SourceType.VM` seems okay.

### Expected behavior

When adding both annotations, we expect the app to start without error.

### Actual behavior

```bash
2024-04-17 10:05:47,014 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: <default>] Unable to build Hibernate SessionFactory
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:129)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:89)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:154)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:61)
        ... 1 more
Caused by: java.lang.IllegalStateException: PostInitCallback queue could not be processed...
        - PostInitCallbackEntry - Entity(org.acme.Shop) `staticFetchableList` generator

        at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess.executePostInitCallbacks(MappingModelCreationProcess.java:144)
        at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess.execute(MappingModelCreationProcess.java:88)
        at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess.process(MappingModelCreationProcess.java:42)
        at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.finishInitialization(MappingMetamodelImpl.java:198)
        at org.hibernate.internal.SessionFactoryImpl.initializeMappingModel(SessionFactoryImpl.java:364)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:293)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:87)
        ... 6 more
        Suppressed: java.lang.NullPointerException: Cannot load from object array because "this.tableMappings" is null
                at org.hibernate.persister.entity.AbstractEntityPersister.getTableMapping(AbstractEntityPersister.java:2889)
                at org.hibernate.persister.entity.SingleTableEntityPersister.getIdentifierTableDetails(SingleTableEntityPersister.java:470)
                at org.hibernate.persister.entity.AbstractEntityPersister.getSoftDeleteTableDetails(AbstractEntityPersister.java:5907)
                at org.hibernate.persister.entity.AbstractEntityPersister.createRootTableGroup(AbstractEntityPersister.java:3113)
                at org.hibernate.loader.ast.internal.LoaderSelectBuilder.buildRootTableGroup(LoaderSelectBuilder.java:578)
                at org.hibernate.loader.ast.internal.LoaderSelectBuilder.generateSelect(LoaderSelectBuilder.java:494)
                at org.hibernate.loader.ast.internal.LoaderSelectBuilder.createSelect(LoaderSelectBuilder.java:257)
                at org.hibernate.metamodel.mapping.internal.GeneratedValuesProcessor.<init>(GeneratedValuesProcessor.java:71)
                at org.hibernate.persister.entity.AbstractEntityPersister.createGeneratedValuesProcessor(AbstractEntityPersister.java:2012)
                at org.hibernate.persister.entity.AbstractEntityPersister.lambda$prepareMappingModel$12(AbstractEntityPersister.java:5033)
                at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess$PostInitCallbackEntry.process(MappingModelCreationProcess.java:246)
                at org.hibernate.metamodel.mapping.internal.MappingModelCreationProcess.executePostInitCallbacks(MappingModelCreationProcess.java:106)
                ... 12 more


2024-04-17 10:05:47,046 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
```

### How to Reproduce?

1. Create a new Quarkus project
2. Add `quarkus-hibernate-orm-panache` to pom.xml
3. Add `quarkus-jdbc-postgresql` to pom.xml
4. Deploy a PostgreSQL DB like this one:

```docker
version: '3.8'

services:
  ephemeria-db:
    container_name: test-db
    image: postgres:latest
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
```

5. Add the following `application.properties` file:
```bash
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=root
%dev.quarkus.datasource.password=root
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/test-db
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
%dev.quarkus.hibernate-orm.log.sql=true
```

6. Add your entity
```java
package org.acme;

import jakarta.persistence.*;

import java.time.LocalDateTime;
import java.util.UUID;
import org.hibernate.annotations.SoftDelete;
import org.hibernate.annotations.SourceType;
import org.hibernate.annotations.UpdateTimestamp;

@Entity
@SoftDelete
public class Shop {
    @Id
    @GeneratedValue
    private UUID idShop;

    @UpdateTimestamp(source = SourceType.DB)
    private LocalDateTime lastUpdateOn;
}
```
7. Run the application with `quarkus dev`

### Output of `uname -a` or `ver`

Linux zbook-wme 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.10 2024-01-16 OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1) OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)

### Quarkus version or git rev

3.9.3

**Comment by yrodiere** [comment]
Hi. Thanks for reporting but this is very likely a Hibernate ORM bug that is unrelated to Quarkus.

Can you please create a reproducer based on https://github.com/hibernate/hibernate-test-case-templates/blob/main/orm/hibernate-orm-6/src/test/java/org/hibernate/bugs/QuarkusLikeORMUnitTestCase.java , attach it to a bug report at https://hibernate.atlassian.net/browse/HHH, and paste the URL of that report here for future tracking?

**Comment by yrodiere** [comment]
Hey @williammadie, any news on this?

See my previous message:

> Hi. Thanks for reporting but this is very likely a Hibernate ORM bug that is unrelated to Quarkus.
> 
> Can you please create a reproducer based on https://github.com/hibernate/hibernate-test-case-templates/blob/main/orm/hibernate-orm-6/src/test/java/org/hibernate/bugs/QuarkusLikeORMUnitTestCase.java , attach it to a bug report at https://hibernate.atlassian.net/browse/HHH, and paste the URL of that report here for future tracking?

**Comment by geoand** [comment]
Closing for lack of feedback
