### ISSUE TITLE
Update from Quarkus 3.6.9 to 3.9.3

### ISSUE THREAD

**Issue by Froidoh** [quarkusio/quarkus#40124]
### Describe the bug

Update from Quarkus 3.6.9 to 3.9.3 (no other changes) leads to:

```
io.vertx.core.impl.NoStackTraceException
Caused by: io.quarkus.dev.appstate.ApplicationStartException: jakarta.enterprise.inject.AmbiguousResolutionException: Beans: [CLASS bean [class=io.quarkus.jackson.customizer.RegisterSerializersAndDeserializersCustomizer, id=i-4rYv1Pyh6ZpctNTYfjIIb-Myg], CLASS bean [class=io.quarkus.jackson.runtime.VertxHybridPoolObjectMapperCustomizer, id=kc3P4gbsTBL_Xz4iSuVtQ6FQP_8]]
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:58)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:132)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:192)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:173)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:542)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:442)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:161)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:148)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: jakarta.enterprise.inject.AmbiguousResolutionException: Beans: [CLASS bean [class=io.quarkus.jackson.customizer.RegisterSerializersAndDeserializersCustomizer, id=i-4rYv1Pyh6ZpctNTYfjIIb-Myg], CLASS bean [class=io.quarkus.jackson.runtime.VertxHybridPoolObjectMapperCustomizer, id=kc3P4gbsTBL_Xz4iSuVtQ6FQP_8]]
	at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:291)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:309)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:190)
	at my.project.config.ClientObjectMapper.objectMapper(ClientObjectMapper.java:28)
	at my.project.config.ClientObjectMapper_ProducerMethod_objectMapper_KgqnG0Hv0d6QYgKd-v-HRXlW39Y_Bean.doCreate(Unknown Source)
	at my.project.config.ClientObjectMapper_ProducerMethod_objectMapper_KgqnG0Hv0d6QYgKd-v-HRXlW39Y_Bean.create(Unknown Source)
	at my.project.config.ClientObjectMapper_ProducerMethod_objectMapper_KgqnG0Hv0d6QYgKd-v-HRXlW39Y_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at my.project.config.ClientObjectMapper_ProducerMethod_objectMapper_KgqnG0Hv0d6QYgKd-v-HRXlW39Y_Bean.get(Unknown Source)
	at my.project.config.ClientObjectMapper_ProducerMethod_objectMapper_KgqnG0Hv0d6QYgKd-v-HRXlW39Y_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:559)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:539)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:572)
	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:534)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:294)
	at io.quarkus.hibernate.orm.runtime.customized.FormatMapperKind$1.create(FormatMapperKind.java:21)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.mergeSettings(FastBootMetadataBuilder.java:404)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.<init>(FastBootMetadataBuilder.java:140)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:99)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:73)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:40)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$1.created(HibernateOrmRecorder.java:78)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:79)
	at io.quarkus.deployment.steps.ArcProcessor$notifyBeanContainerListeners1304312071.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$notifyBeanContainerListeners1304312071.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	... 1 more
```

```java
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.SerializationFeature;
import io.quarkus.jackson.ObjectMapperCustomizer;
import jakarta.enterprise.inject.Instance;
import jakarta.inject.Singleton;

public class ClientObjectMapper {

    // Replaces the CDI producer for ObjectMapper built into Quarkus
    @Singleton
    ObjectMapper objectMapper(Instance<ObjectMapperCustomizer> customizers) {
        ObjectMapper om = new ObjectMapper();
        om.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        // Write dates as ISO-8601 timestamps
        om.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

        om.setSerializationInclusion(JsonInclude.Include.ALWAYS);

        om.setPropertyNamingStrategy(PropertyNamingStrategies.LOWER_CAMEL_CASE);

        // Apply all ObjectMapperCustomizer beans (incl. Quarkus)
        customizers.get().customize(om);
        return om;
    }
}
```
    
Any ideas? 

Did I miss something in the migration guides? If so, terribly sorry, I double checked!

When I remove 
```
// Apply all ObjectMapperCustomizer beans (incl. Quarkus)
        //customizers.get().customize(om);
```
it works :/

**Comment by geoand** [comment]
This is very interesting. Can you please attach a project that reproduces the problem so we can dig into what is happening?

**Comment by geoand** [comment]
Can you also try replacing

```
Instance<ObjectMapperCustomizer> customizers
```

with 

```
@All List<ObjectMapperCustomizer> customizers
```

?

**Comment by geoand** [comment]
Closing for lack of feedback
