### ISSUE TITLE
quarkus-azure-functions-3.9.3 - ERROR [io.qua.dev.dep.DevUIProcessor] failed to process extension descriptor - class java.lang.String cannot be cast to class java.util.List

### ISSUE THREAD

**Issue by faustool** [quarkusio/quarkus#40139]
### Describe the bug

When running the application with `mvn quarkus:dev`, the error below is printed in the output:
```
2024-04-18 08:56:17,613 ERROR [io.qua.dev.dep.DevUIProcessor] (build-51) Failed to process extension descriptor jar:file:///<path>/.m2/repository/io/quarkus/quarkus-azure-functions/3.9.3/quarkus-azure-functions-3.9.3.jar!/META-INF/quarkus-extension.yaml: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
        at io.quarkus.devui.deployment.DevUIProcessor.lambda$getAllExtensions$1(DevUIProcessor.java:496)
        at io.quarkus.runtime.util.ClassPathUtils.lambda$consumeAsPath$0(ClassPathUtils.java:121)
        at io.quarkus.runtime.util.ClassPathUtils.processAsPath(ClassPathUtils.java:154)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPath(ClassPathUtils.java:120)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:104)
        at io.quarkus.runtime.util.ClassPathUtils.consumeAsPaths(ClassPathUtils.java:85)
        at io.quarkus.devui.deployment.DevUIProcessor.getAllExtensions(DevUIProcessor.java:443)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```

### Expected behavior

I expected to see the Azure Functions extensions in the dev-ui/extensions page.

### Actual behavior

No Azure Functions extension shows in the dev-ui/extensions page.

### How to Reproduce?

Run `mvn quarkus:dev`

### Output of `uname -a` or `ver`

Microsoft Windows 11 Enterprise - 10.0.22631

### Output of `java -version`

OpenJDK Runtime Environment Microsoft-8905927 (build 21.0.2+13-LTS

### Quarkus version or git rev

3.9.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

This bug happens in all versions released after 3.8.4:

* 3.9.0.CR1
* 3.9.0.CR2
* 3.9.1
* 3.9.2
* 3.9.3
* 3.10.0.CR1

**Comment by geoand** [comment]
cc @patriot1burke

**Comment by phillip-kruger** [comment]
This looks like a Dev UI issue. I'll have a look
