### ISSUE TITLE
Cannot mock `GitInfo` using `@MockitoConfig(convertScopes = true)`

### ISSUE THREAD

**Issue by sne11ius** [quarkusio/quarkus#40152]
### Describe the bug

I want to mock `GitInfo` (from the info extension) in my Test. But although I use `@MockitoConfig`, I get

`Invalid use of io.quarkus.test.InjectMock - the injected bean does not declare a CDI normal scope but: jakarta.inject.Singleton. Offending field is gitInfo of test class class org.acme.BuildInfoResourceTest`.

Here is my example Test class:
```kotlin
package org.acme

import io.quarkus.info.GitInfo
import io.quarkus.test.InjectMock
import io.quarkus.test.junit.QuarkusTest
import io.quarkus.test.junit.mockito.MockitoConfig
import io.restassured.RestAssured.given
import io.restassured.http.ContentType.JSON
import org.hamcrest.CoreMatchers.`is`
import org.junit.jupiter.api.Test
import org.mockito.Mockito

@QuarkusTest
class BuildInfoResourceTest {

    @InjectMock
    @MockitoConfig(convertScopes = true)
    lateinit var gitInfo: GitInfo

    @Test
    fun testBuildInfoEndpoint() {
        Mockito.`when`(gitInfo.latestCommitId()).thenReturn("f123A")
        given()
            .`when`()
            .get("/build-info")
            .then()
            .statusCode(200)
            .contentType(JSON)
            .body(`is`("{\"gitHash\":\"f123A\"}"))
    }
}
```

### Expected behavior

I expect annotation `@MockitoConfig(convertScopes = true)` to work and give me a mock.

### Actual behavior

Attempting to run the test gives the stacktrace below:

```

Failed to create test instance
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:789)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:755)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.IllegalStateException: Invalid use of io.quarkus.test.InjectMock - the injected bean does not declare a CDI normal scope but: jakarta.inject.Singleton. Offending field is gitInfo of test class class org.acme.BuildInfoResourceTest
	at io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.getBeanHandle(CreateMockitoMocksCallback.java:105)
	at io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.injectField(CreateMockitoMocksCallback.java:47)
	at io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.afterConstruct(CreateMockitoMocksCallback.java:37)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.AbstractTestWithCallbacksExtension.invokeCallbacks(AbstractTestWithCallbacksExtension.java:158)
	at io.quarkus.test.junit.AbstractTestWithCallbacksExtension.invokeAfterConstructCallbacks(AbstractTestWithCallbacksExtension.java:64)
	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:786)
	... 4 more
```

### How to Reproduce?

Run the test to reproduce. Use the uploaded minimal example project if it helps you. Contains more or less nothing but gradle project and the Test.
Testproject: [test.zip](https://github.com/quarkusio/quarkus/files/15038590/test.zip)

### Output of `uname -a` or `ver`

Linux hostname 6.5.0-10031-tuxedo

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.9.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

### Additional information

To me, this looks a lot like #35080 or #38817, but I thought these issues would be fixed by now.

**Comment by geoand** [comment]
Thanks for reporting. 

This is a more general issue, i.e. that `@MockitoConfig(convertScopes = true)` does not work with synthetic beans. 
I am not sure what we could do about that @mkouba.

In this specific case we could easily make the `GitInfo` bean an `@ApplicationScoped` bean instead of a `@Singleton`.

**Comment by mkouba** [comment]
> This is a more general issue, i.e. that `@MockitoConfig(convertScopes = true)` does not work with synthetic beans.
> I am not sure what we could do about that @mkouba.

Indeed, `@MockitoConfig(convertScopes = true)` makes use of the `AnnotationsTransformer` API which does not work for synthetic beans, i.e. beans whose metadata are created programmatically in a Quarkus extension. We would need a new API to transform the bean metadata to fix this problem :shrug:.

I'm not quite sure it's worth the effort.

CC @Ladicek @manovotn

**Comment by geoand** [comment]
> I'm not quite sure it's worth the effort.

Right, I'm not convinced either :)

**Comment by Ladicek** [comment]
If `GitInfo` could easily be turned into `@ApplicationScoped`, then I think that would be the best solution here. Certainly for this particular case, it doesn't make sense to create a bean transformation API.

**Comment by manovotn** [comment]
> I'm not quite sure it's worth the effort.

I am of the same opinion

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/40178 makes the change to `@ApplicationScoped`
