### ISSUE TITLE
[DOC]  From 3.2.9 to 3.3.0 version, redis-client extension

### ISSUE THREAD

**Issue by marcelolemes** [quarkusio/quarkus#40189]
### Describe the bug

Significant change to the extension's quarkus-redis-client (3.2.9 to 3.3.0) operating mode, resulting in the following exception.

`
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/                                                                                                                                                                                          
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-04-22 10:03:52,366 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-redis-exemplo 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.2.9.Final) started in 2.224s. Listening on: http://localhost:8080
2024-04-22 10:03:52,369 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-04-22 10:03:52,370 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, redis-client, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-openapi, swagger-ui, vertx]           
2024-04-22 10:05:21,238 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /increments failed, error id: d1b9ba0a-1b53-454c-a4e3-15919ad28754-1: java.lang.NullPointerException: Cannot invoke "io.vertx.redis.client.RedisRole.ordinal()" because "role" is null
        at io.vertx.redis.client.impl.RedisSentinelClient.createConnectionInternal(RedisSentinelClient.java:145)
        at io.vertx.redis.client.impl.RedisSentinelClient.connect(RedisSentinelClient.java:69)
        at io.vertx.redis.client.impl.BaseRedisClient.send(BaseRedisClient.java:42)
        at io.vertx.redis.client.Redis.send(Redis.java:110)
        at io.quarkus.redis.runtime.client.ObservableRedis.send(ObservableRedis.java:52)
        at io.vertx.mutiny.redis.client.Redis.lambda$send$6(Redis.java:154)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at io.smallrye.mutiny.vertx.AsyncResultUni.subscribe(AsyncResultUni.java:31)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
        at org.jboss.resteasy.reactive.server.handlers.UniResponseHandler.handle(UniResponseHandler.java:19)
        
`
Situation resolved but not reported in version 3.3.0 CHANGELOG document.

Several redis-client extension classes changed, based in this comparison https://github.com/quarkusio/quarkus/compare/3.3.0...main

### Expected behavior

None exception at all

### Quarkus version or git rev

3.2.9

**Comment by Ladicek** [comment]
Yes, I'm aware of the problem, and it should be fixed by https://github.com/vert-x3/vertx-redis-client/pull/429 (that is, in Vert.x Redis client 4.5.6).

Please update to Quarkus 3.8.4 and try again. If it still fails, please reopen the issue.

If you cannot update to latest Quarkus, then the following properties are in fact mandatory (even though they are documented as optional):

```properties
quarkus.redis.master-name=mymaster
quarkus.redis.role=master
```

**Comment by marcelolemes** [comment]
The problem has already been resolved in the version 3.3.0, the issue was opened exclusively on the documentation, which made me waste some time trying to discover this change that was not indicated in the changelog of the version 3.3.0
