### ISSUE TITLE
avro class-cast-exception in `quarkus test`

### ISSUE THREAD

**Issue by flyinfish** [quarkusio/quarkus#40190]
### Describe the bug

so simple that i hope its no duplicate. found similar issues but no solution...
https://github.com/quarkusio/quarkus/issues/18776
https://github.com/quarkusio/quarkus/issues/16804

when using builder of generated-avro-class it get 
```
2024-04-22 15:49:24,110 ERROR [io.qua.test] (Test runner thread) Test AvroTest#test() failed 
 [Error Occurred After Shutdown]: org.apache.avro.AvroRuntimeException: java.lang.ClassCastException: class org.whatever.SomeChild cannot be cast to class org.whatever.SomeChild (org.whatever.SomeChild is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @2686b936; org.whatever.SomeChild is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6593b104)
        at org.whatever.SomeObject$Builder.build(SomeObject.java:307)
        at org.acme.AvroTest.test(AvroTest.java:10)
Caused by: java.lang.ClassCastException: class org.whatever.SomeChild cannot be cast to class org.whatever.SomeChild (org.whatever.SomeChild is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @2686b936; org.whatever.SomeChild is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6593b104)
        at org.whatever.SomeObject$Builder.build(SomeObject.java:301)
        ... 1 more
```

### Expected behavior

no class-cast-exception

### Actual behavior

class-cast-exception

### How to Reproduce?

git clone https://github.com/flyinfish/avro-classloading.git
cd avro-classloading
quarkus test

### Output of `uname -a` or `ver`

Linux C70C7391 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 21.0.1.0.101 2024-01-16 LTS OpenJDK Runtime Environment Zulu21.31+16-SA (build 21.0.1.0.101+3-LTS) OpenJDK 64-Bit Server VM Zulu21.31+16-SA (build 21.0.1.0.101+3-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.9.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Warning: JAVA_HOME environment variable is not set. Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /home/u125015/.m2/wrapper/dists/apache-maven-3.9.6-bin/3311e1d4/apache-maven-3.9.6 Java version: 21.0.1.0.101, vendor: Azul Systems, Inc., runtime: /usr/lib/jvm/mobi-azuljdk21 Default locale: en, platform encoding: UTF-8 OS name: "linux", version: "5.15.146.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"

**Comment by cescoffier** [comment]
Thanks for reporting. It's a CLI issue. It works perfectly with `mvn test`.

**Comment by flyinfish** [comment]
@stuartwdouglas @geoand @maxandersen i annotate you as of `area/(continous-)testing, area/cli`

could you please have a look and check?
works with `mvn test` fails with `mvn quarkus:test` `mvn quarkus:dev`

thanks a lot

**Comment by geoand** [comment]
I took a quick look and I don't see any easy fix for this

**Comment by maxandersen** [comment]
this is not a cli issue, right? its a devmode and continuous test issue, right?

**Comment by geoand** [comment]
Continuous testing issue

**Comment by maxandersen** [comment]
I tried work around using quarkus.test.flat-class-path=true but then hit:

```
[INFO] [stdout] 2024-06-12 12:16:29,936 ERROR [io.qua.test] (main) Failed to create compiler, runtime compilation will be unavailable: java.lang.NullPointerException: Cannot read field "includeModulePattern" because "this.config" is null
[INFO] [stdout] 	at io.quarkus.deployment.dev.testing.TestSupport.init(TestSupport.java:161)
[INFO] [stdout] 	at io.quarkus.deployment.dev.testing.TestSupport.start(TestSupport.java:136)
[INFO] [stdout] 	at io.quarkus.deployment.dev.testing.TestHandler.accept(TestHandler.java:21)
[INFO] [stdout] 	at io.quarkus.deployment.dev.testing.TestHandler.accept(TestHandler.java:17)
[INFO] [stdout] 	at io.quarkus.runner.bootstrap.AugmentActionImpl.performCustomBuild(AugmentActionImpl.java:162)
[INFO] [stdout] 	at io.quarkus.deployment.dev.IsolatedTestModeMain.accept(IsolatedTestModeMain.java:132)
[INFO] [stdout] 	at io.quarkus.deployment.dev.IsolatedTestModeMain.accept(IsolatedTestModeMain.java:34)
[INFO] [stdout] 	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
[INFO] [stdout] 	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
[INFO] [stdout] 	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
[INFO] [stdout] 	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
```

**Comment by flyinfish** [comment]
> Continuous testing issue

so it gets the right label and will be fixed hopefully some day in future? we're providing a quarkus platform and try to "promote" continuous testing. 

using @QuarkusTest instead of simple unittest just to workaround the issue is somehow odd.
thanks a lot

**Comment by flyinfish** [comment]
@holly-cummins another one mentioned yesterday in bern

**Comment by holly-cummins** [comment]
See also #27057, also in the avro area. 

I have bad news and good news and bad news.

Bad news: I've checked and https://github.com/quarkusio/quarkus/pull/34681 doesn't fix this (which isn't entirely surprising, since it focusses on what's going on with `@QuarkusTest`, not vanilla JUnit. 

Good news: I can see an opportunity for improvement in the reproducer, @flyinfish. There's a [Quarkus extension for Avro](https://quarkus.io/extensions/io.quarkus/quarkus-avro/). To convert the reproducer to use the extension
- run `quarkus ext add avro` to add the Quarkus extension
- remove the apache avro dependency
- remove the apache avro plugin from the pom; the extension takes care of source generation 
- move the schema files from `.kafka/avroschemas/ to `src/main/avro`
https://github.com/quarkusio/quarkus-quickstarts/blob/main/kafka-avro-schema-quickstart is an example application which you can also look at

Bad news: Even after converting to use the extension, I can reproduce the problem. Simple schemas are ok, but the child record breaks it. 

I guess there's a final bit of good news which is that adding `@QuarkusTest` to affected tests is an easy workaround.

**Comment by flyinfish** [comment]
nevermind and thanks i'll check why we do not use quarkus avro yet
