### ISSUE TITLE
Quarkus 3.9 doesn't load RestClient class in Kotlin CoroutineScope

### ISSUE THREAD

**Issue by johan-hanson** [quarkusio/quarkus#40245]
### Describe the bug

When injecting a RestClient into an @ApplicationScoped or @Singleton class and try to use it inside a Coroutine the class is not found, throwing a ClassNotFoundException in Quarkus 3.9. The code works as expected if you downgrade Quarkus to <= 3.8.4. The code also works if the call is made outside of the Coroutine.

Simple code to reproduce the exception:
```
  fun onStart(@Observes ev: StartupEvent) {
      CoroutineScope(Dispatchers.IO).launch {
          println("RestClient result: ${restClient.getHello()}")
      }
  }
```

The exception:
```
Exception in thread "DefaultDispatcher-worker-1" jakarta.enterprise.inject.CreationException: java.lang.ClassNotFoundException: org.acme.rest.TestRestClient
	at org.acme.rest.TestRestClient$$CDIWrapper_Bean.create(Unknown Source)
	at org.acme.rest.TestRestClient$$CDIWrapper_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c6(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at org.acme.rest.TestRestClient$$CDIWrapper_ClientProxy.arc$delegate(Unknown Source)
	at org.acme.rest.TestRestClient$$CDIWrapper_ClientProxy.getHello(Unknown Source)
	at org.acme.app.LoadTest$onStart$1.invokeSuspend(LoadTest.kt:17)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6ebcc246, Dispatchers.IO]
Caused by: java.lang.ClassNotFoundException: org.acme.rest.TestRestClient
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:491)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at org.acme.rest.TestRestClient$$CDIWrapper.<init>(Unknown Source)
	at org.acme.rest.TestRestClient$$CDIWrapper_Bean.doCreate(Unknown Source)
```

### How to Reproduce?

Reproducer: [test-rest-client.zip](https://github.com/quarkusio/quarkus/files/15092506/test-rest-client.zip)
Sorry but the reproducer is created with Gradle. Its only three small classes so it should be fine to create a simple Quarkus project in Maven and copy the classes.

Unzip and run gradlew quarkusDev

**Comment by geoand** [comment]
There is a good chance that this issue is the same as [this](https://github.com/quarkusio/quarkus/discussions/40187#discussioncomment-9190388).

Can you try the workarounds mention [here](https://github.com/quarkusio/quarkus/discussions/40187#discussioncomment-9190388)?

@aloubyansky how do you feel about introducing the change mentioned [here](https://github.com/quarkusio/quarkus/discussions/40187#discussioncomment-9193869)?

**Comment by johan-hanson** [comment]
I have tried with both new artifact names `quarkus-rest* `and the old ones with no luck. I also test with adding `quarkus-rest-kotlin` or `quarkus-resteasy-reactive-kotlin` but with the same result.

**Comment by geoand** [comment]
I will try it soon

**Comment by geoand** [comment]
> I have tried with both new artifact names `quarkus-rest* `and the old ones with no luck. I also test with adding `quarkus-rest-kotlin` or `quarkus-resteasy-reactive-kotlin` but with the same result.

Is there something I need to do to get the project imported in IntelliJ? Asking because I am getting a bunch of Gradle related errors

**Comment by johan-hanson** [comment]
I have no problem running the Gradle project using the latest Intellij Community Edition. It was some time I used Maven, but I have created a Kotlin Maven project using Quarkus CLI and copied the code from the Gradle project. I get the same exception in the Maven project
[rest-kotlin-quickstart.zip](https://github.com/quarkusio/quarkus/files/15106636/rest-kotlin-quickstart.zip)

**Comment by geoand** [comment]
Thanks. 

The root cause of the problem is that the inside the coroutine scope the context ClassLoader (`Thread.currentThread().contextClassLoader`) is in incorrect. 

You can see this by changing your example to:

```kotlin
    fun onStart(@Observes ev: StartupEvent) {
        println(Thread.currentThread().contextClassLoader.name)
        CoroutineScope(Dispatchers.IO).launch {
            println(Thread.currentThread().contextClassLoader.name)
            println("RestClient result: ${restClient.getHello()}")
        }
    }
```

and viewing the output:

```
Quarkus Runtime ClassLoader: DEV for rest-kotlin-quickstart-1.0.0-SNAPSHOT restart no:0
Quarkus Base Runtime ClassLoader: DEV for rest-kotlin-quickstart-1.0.0-SNAPSHOT
```

Now, I have no idea what causes that... What I do know is that we never had any code that interacted with the context ClassLoader of threads used in Corroutines.  

There is an easy workaround however:

```kotlin
@Singleton
class LoadTest(@RestClient private val restClient: TestRestClient) {

    fun onStart(@Observes ev: StartupEvent) {
        val properTccl = Thread.currentThread().contextClassLoader
        CoroutineScope(Dispatchers.IO).launch {
            Thread.currentThread().contextClassLoader = properTccl
            println("RestClient result: ${restClient.getHello()}")
        }
    }
}
```

**Comment by nikbucher** [comment]
> I have no problem running the Gradle project using the latest Intellij Community Edition. It was some time I used Maven, but I have created a Kotlin Maven project using Quarkus CLI and copied the code from the Gradle project. I get the same exception in the Maven project [rest-kotlin-quickstart.zip](https://github.com/quarkusio/quarkus/files/15106636/rest-kotlin-quickstart.zip)

@geoand Sorry for commenting on a closed ticket, but when I take the `rest-kotlin-quickstart.zip` file from above and run `./mvnw package quarkus:run`, it works as expected:

```
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2025-03-28 15:54:18,183 INFO  [io.quarkus] (main) rest-kotlin-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.9.4) started in 0.377s. Listening on: http://0.0.0.0:8080
2025-03-28 15:54:18,186 INFO  [io.quarkus] (main) Profile prod activated.
2025-03-28 15:54:18,186 INFO  [io.quarkus] (main) Installed features: [cdi, kotlin, rest, rest-client, rest-client-jackson, smallrye-context-propagation, vertx]
RestClient result: Hello!
^C2025-03-28 15:54:31,279 INFO  [io.quarkus] (main) rest-kotlin-quickstart stopped in 0.015s
```

The error `java.lang.ClassNotFoundException: org.acme.rest.TestRestClient` only occurs when starting with `./mvnw quarkus:dev`.

**Comment by geoand** [comment]
Yeah, that's expected. The workaround is mentioned [here](https://github.com/quarkusio/quarkus/issues/40245#issuecomment-2076907560)

**Comment by nikbucher** [comment]
Thanks for the answer! I've already seen that workaround. Sorry if my question sounds silly, but is this a Quarkus bug or a Kotlin bug? And where should I file an issue to get it fixed?

**Comment by geoand** [comment]
It's probably not a bug per-se - it only is if what I describe below is meant to happen but for some unforeseen reason does not.

What happens is that Kotlin does not capture the Context ClassLoader of the Thread that creates the initiates the launch.

**Comment by nikbucher** [comment]
Thanks for the answer. I'm not sure if it's reasonable to add a Quarkus-specific launcher. After some investigation, now it looks for me more like a coroutine bug. But I also found a really elegant workaround or solution for me.

Instead of using some of the provided dispatchers:

```kotlin
val limitingDispatcher = Dispatchers.Default.limitedParallelism(7)
val result = runBlocking(limitingDispatcher) { ... }
```

I found out it works seamlessly if I create a thread pool which is easy to use as a coroutine dispatcher:

```kotlin
val limitingDispatcher: CoroutineDispatcher = Executors.newFixedThreadPool(7).asCoroutineDispatcher()
val result = runBlocking(limitingDispatcher) { ... }
```

Or even better with Java 21 (in my case) by using virtual threads:

```kotlin
val limitingDispatcher: CoroutineDispatcher = Executors.newFixedThreadPool(7, Thread.ofVirtual().factory()).asCoroutineDispatcher()
val result = runBlocking(limitingDispatcher) { ... }
```

Hope it helps someone else too.

**Comment by geoand** [comment]
That's very interesting! 

One slight improvement I can think of is to the `ManagedExecutor` provided by [Context Propagation](https://quarkus.io/guides/context-propagation)
