### ISSUE TITLE
Transaction is not closed at the end of the request after calling the begin() method in @GraphqlAPI

### ISSUE THREAD

**Issue by Tiikara** [quarkusio/quarkus#40363]
### Describe the bug

Transaction is not closed at the end of the request after calling the begin() method in @GraphqlAPI

I've written two simple classes (I plan to use GraphqlApiDomainTransactionalState in @Interceptor, but for simplicity I wrote this example)

```kotlin
@RequestScoped
class GraphqlApiDomainTransactionalState {
  private var started = false

  fun startIfNeed() {
    println(started)

    if (started) {
      return
    }

    QuarkusTransaction.begin(
      QuarkusTransaction.beginOptions().commitOnRequestScopeEnd()
    )

    started = true
  }
}

@GraphQLApi
class TestGraphqlEndpoint {
  @Inject
  lateinit var state: GraphqlApiDomainTransactionalState

  @Query("objects")
  fun tests(): List<Test> {
    state.startIfNeed()

    return listOf(Test("asd"))
  }
}
```

After that execute graphql query, it completes successfully. At the end of the logs I see the following

```
2024-04-30 19:18:40,024 FINE  [io.sma.con.jta.con.pro.JtaContextProvider] (vert.x-worker-thread-1) Suspending transaction TransactionImple < ac, BasicAction: 0:ffff0a140312:c968:6630b76f:0 status: ActionStatus.RUNNING >
2024-04-30 19:18:40,038 FINE  [io.sma.con.jta.con.pro.JtaContextProvider] (vert.x-worker-thread-1) Resuming transaction TransactionImple < ac, BasicAction: 0:ffff0a140312:c968:6630b76f:0 status: ActionStatus.RUNNING >
```

If I execute the request again, the following exception is thrown

```
2024-04-30 19:20:03,485 DEBUG [not.gra.exe.ExecutionStrategy] (vert.x-worker-thread-1) '19770343191', field '/objects' fetch threw exception: io.quarkus.narayana.jta.QuarkusTransactionException: Transaction already active
	at io.quarkus.narayana.jta.RequestScopedTransaction.begin(RequestScopedTransaction.java:57)
	at io.quarkus.narayana.jta.RequestScopedTransaction_ClientProxy.begin(Unknown Source)
	at io.quarkus.narayana.jta.QuarkusTransactionImpl.begin(QuarkusTransactionImpl.java:223)
	at io.quarkus.narayana.jta.QuarkusTransaction.begin(QuarkusTransaction.java:53)
	at ru.foura.erpii.graphql.endpoints.GraphqlApiDomainTransactionalState.startIfNeed(DepartmentGraphqlEndpoint.kt:48)
	at ru.foura.erpii.graphql.endpoints.GraphqlApiDomainTransactionalState_ClientProxy.startIfNeed(Unknown Source)
	at ru.foura.erpii.graphql.endpoints.TestGraphqlEndpoint.tests(DepartmentGraphqlEndpoint.kt:63)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.smallrye.graphql.execution.datafetcher.helper.ReflectionInvoker.invoke(ReflectionInvoker.java:97)
	at io.smallrye.graphql.execution.datafetcher.DefaultDataFetcher.invokeAndTransform(DefaultDataFetcher.java:33)
	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusDefaultDataFetcher.invokeAndTransform(QuarkusDefaultDataFetcher.java:45)
	at io.smallrye.graphql.execution.datafetcher.AbstractDataFetcher.get(AbstractDataFetcher.java:70)
	at graphql.execution.ExecutionStrategy.invokeDataFetcher(ExecutionStrategy.java:311)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:287)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:213)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55)
	at graphql.execution.Execution.executeOperation(Execution.java:161)
	at graphql.execution.Execution.execute(Execution.java:103)
	at graphql.GraphQL.execute(GraphQL.java:568)
	at graphql.GraphQL.lambda$parseValidateAndExecute$13(GraphQL.java:487)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482)
	at graphql.GraphQL.lambda$executeAsync$9(GraphQL.java:440)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
	at graphql.GraphQL.executeAsync(GraphQL.java:428)
	at io.smallrye.graphql.execution.ExecutionService.lambda$writeAsync$0(ExecutionService.java:235)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
	at io.smallrye.graphql.execution.ExecutionService.writeAsync(ExecutionService.java:237)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:196)
	at io.smallrye.graphql.execution.ExecutionService.executeAsync(ExecutionService.java:131)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:366)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:124)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:85)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handleWithIdentity(SmallRyeGraphQLAbstractHandler.java:95)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:76)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:30)
```

After debugging, I noticed that the `RequestScopedTransaction` class tries to complete the transaction but fails the check in the

```kotlin
@PreDestroy
    void destroy() {
        try {
            if (transactionManager.getTransaction() == createdTransaction) { // (!!!!!!) doesn't pass inspection here. fields of transactionManager object is empty for some reason
                if (autoCommit) {
                    QuarkusTransaction.commit();
                } else {
                    log.warn("Rolling back transaction that was not committed or explicitly rolled back.");
                    try {
                        userTransaction.rollback();
                    } catch (SystemException e) {
                        throw new QuarkusTransactionException(e);
                    }
                }
            }
        } catch (SystemException e) {
            log.warn("Failed to destroy request scoped transaction", e);
        }
    }
```

And of course, if I call the QuarkusTransaction.commit() method manually after QuarkusTransaction.begin(), everything works as intended

### Expected behavior

After calling the method

QuarkusTransaction.begin(
   QuarkusTransaction.beginOptions().commitOnRequestScopeEnd()
)

The transaction should complete at the end of the request

### How to Reproduce?

Under Describe the bug

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.3527]

### Output of `java -version`

Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)

### Quarkus version or git rev

3.9.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

### Additional information

------------------------------------------------------------
Gradle 8.6
------------------------------------------------------------

Build time:   2024-02-02 16:47:16 UTC
Revision:     d55c486870a0dc6f6278f53d21381396d0741c6e

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.2 (Oracle Corporation 21.0.2+13-LTS-jvmci-23.1-b30)
OS:           Windows 11 10.0 amd64

**Comment by jmartisk** [comment]
It would seem to me that using `commitOnRequestScopeEnd` transactions isn't possible this way, because your GraphQL operation is dispatched to a worker thread, whereas the `RequestScopedTransaction.destroy` callback runs on an event loop, that's the reason why it can't see and commit the original transaction that was started by the operation.
Using a request-scoped transaction with GraphQL generally doesn't sound like a very good idea to me, because a client might request the execution of multiple operations in a single request, and they may need their own transactions.

**Comment by Tiikara** [comment]
I see. But what if I need one request to be strictly in one transaction? For the data to be consistent. In such a case, is it intended to use a separate query root field?

**Comment by jmartisk** [comment]
Operations should be written to be consistent each individually because you never know which and how many a client will run in a single request. The engine also doesn't start any transactions automatically, so yeah, if you do need to wrap them into a single tx then I think you also need to wrap them into a single entry point (operation) and either annotate it with `@Transactional`, or manage transactions in it programmatically.
