### ISSUE TITLE
upgrade to Quarkus 3.10.0 with flyway and postgres failed, missing a dependency

### ISSUE THREAD

**Issue by humcqc** [quarkusio/quarkus#40368]
### Describe the bug

I have a quarkus app in 3.9.5  with flyway and postgres ( and others) 
When you  upgrade to 3.10.0, your quarkus app fail to start with:
```
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 16.2
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:73)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:134)
	at org.flywaydb.core.Flyway.clean(Flyway.java:248)
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:123)
	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy(Unknown Source)
	... 8 more
```

Following Flyway guys, https://github.com/flyway/flyway/issues/3774 there is a new dependencies following your db.
for postgres you need to add this new dependency: org.flywaydb:flyway-database-postgresql

It could be nice if quarkus add it automatically if possible ?

**Comment by gastaldi** [comment]
This change is explained in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10#flyway-10-gear-white_check_mark. 

I suppose we could add it during the `quarkus update` execution somehow, is that what you mean?

**Comment by humcqc** [comment]
Sorry my mistake, didn't notice that part.

But if it's possible to automatically detect that we are using flyway and postgres and automatically add this dependency it will be fantastic and avoid that in the app side we sync quarkus-flyway with flywaydb dependency.

But it's ok with the migration guide, you can close this issue if you are not interested by the automatic way.

**Comment by gastaldi** [comment]
Quarkus does not add dependencies to other libraries when building as this may introduce other issues which have been already previously discussed in other cases. 

I'm going to close this now because the solution is quite straightforward. Thanks for reporting in.
