### ISSUE TITLE
have static @Observes method work on things that aren't beans

### ISSUE THREAD

**Issue by sixcorners** [quarkusio/quarkus#40372]
### Description

I initially was going to make this a bug report but I think it makes sense how it works now.

It would be nice if I could put static `@Observes` methods on things that aren't beans. If an `@Observes` method is static then the Observer doesn't need to get a `this` instance to dispatch events to it. That probably works fine based on the code here: https://github.com/quarkusio/quarkus/blob/094d626f20cffa6cedf79330c087d5b97db3f808/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/ObserverGenerator.java#L368-L370. At build time though ArcProcessor#validate doesn't necessarily like it because I think adding an Observes method, even if it's static, turns it into a bean. When it finds out the class doesn't make sense as a bean it errors out.

Here is what can be used to see the error happen:
```
public class Test {
    Test(Void x) {} // uninjectable type
    static void test(@Observes String event) {}
}
```

Here is what some of the error looks like:
```
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.Void and qualifiers [@Default]
	- injection target: parameter 'x' of info.sixcorners.client.Test constructor
	- declared on CLASS bean [types=[info.sixcorners.client.Test, java.lang.Object], qualifiers=[@Default, @Any], target=info.sixcorners.client.Test]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:638)
```

On the other hand working around this is pretty easy. Just need to define an additional class to house the `@Observes` method.

### Implementation ideas

I don't exactly know what all of the consequences of this would be but you could make it so that static methods don't turn the class into a bean.

**Comment by sixcorners** [comment]
Actually if I make the Test class `abstract` then it doesn't error out but it also doesn't work so it might be that the code I linked above wouldn't work even if the validator didn't error out.

**Comment by mkouba** [comment]
So first of all, the CDI spec has this requirement - [Observer methods](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#observer_methods): _"An observer method is a non-abstract method of a managed bean class. An observer method may be either static or non-static."_.

In theory, we could relax this requirement (and hide this feature behind the [strict mode switch](https://quarkus.io/guides/cdi-reference#strict_mode)) but I'm not really sure of all the consequences.

> On the other hand working around this is pretty easy. Just need to define an additional class to house the `@Observes` method.

Exactly.

**Comment by manovotn** [comment]
FYI, the reason that Arc currently operates on CDI beans is because CDI specification declares it that way.
It's [this part](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#observer_methods) of the specification that states:

> An observer method is a non-abstract method of a managed bean class. An observer method may be either static or non-static

**Comment by manovotn** [comment]
> We would need to spend some time uncovering and investigating corner cases.

Just a clarification for our future selves, as we discussed this on Zulip.
These cases include, but are not limited to, CDI extensions, which allow you to process observer methods and access their declaring beans. Similar story is with CDI 4.1 invokers where you could attempt to declare them for an OM outside of a bean.
In such cases you'd be sailing through undefined territory and for example extensions processing all OMs for given type could deal with unexpected `null` values.

**Comment by sixcorners** [comment]
ya makes sense. thanks
