### ISSUE TITLE
@ExceptionHandler method does not accept the WebRequest / HttpRequest as a parameter

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#4042]
Quarkus 0.22.0

`@ExceptionHandler` only accept one parameter, but it should allow more params in the method param list.

https://github.com/hantsy/quarkus-sample/tree/master/spring-post-service

```java
@RestControllerAdvice
public class PostExceptionHandler {

    @ExceptionHandler(PostNotFoundException.class)
    public ResponseEntity notFound(PostNotFoundException ex/*, WebRequest req*/) {
        Map<String, String> errors = new HashMap<>();
        errors.put("entity", "POST");
        errors.put("id", "" + ex.getSlug());
        errors.put("code", "not_found");
        errors.put("message", ex.getMessage());

        return status(HttpStatus.NOT_FOUND).body(errors);
    }

}
```

**Comment by geoand** [comment]
OK, so basically we won't be adding support for `WebRequest` (a Spring specific type) soon, but we can probably add support for `HttpServletRequest` (the servlet type).

**Comment by geoand** [comment]
I opened #4046 to address this. Feel free to give it a try

**Comment by hantsy** [comment]
>OK, so basically we won't be adding support for WebRequest (a Spring specific type) soon, but we can probably add support for HttpServletRequest (the servlet type).

If there is no plan to add `WebRequest`, please add a usage **limitation** block in the docs, it is important for developers.

**Comment by geoand** [comment]
> > OK, so basically we won't be adding support for WebRequest (a Spring specific type) soon, but we can probably add support for HttpServletRequest (the servlet type).
> 
> If there is no plan to add `WebRequest`, please add a usage **limitation** block in the docs, it is important for developers.

Thats is a great point! Would you like to contribute a PR for the docs addressing that?

Thanks

**Comment by hantsy** [comment]
@geoand  Just verify this again in my application. 

I have NOT changed my codes. 
```java
@RestControllerAdvice
public class PostExceptionHandler {

    @ExceptionHandler(PostNotFoundException.class)
    public ResponseEntity notFound(PostNotFoundException ex/*, WebRequest req*/) {
        Map<String, String> errors = new HashMap<>();
        errors.put("entity", "POST");
        errors.put("id", "" + ex.getSlug());
        errors.put("code", "not_found");
        errors.put("message", ex.getMessage());
        return status(HttpStatus.NOT_FOUND).body(errors);
    }
}
```

Now I got an exception like this.

```bash
2019-11-11 21:06:01,612 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-worker-thread-7) HTTP Request to /posts/notapostid failed, error id: d3cc34f6-b01e-4f9e-9ba8-46a26a83fc77-1: org.jboss.resteasy.spi.UnhandledException: java.lang.ClassCastException: class java.util.HashMap cannot be cast to class org.springframework.http.ResponseEntity (java.util.HashMap is in module java.base of loader 'bootstrap'; org.springframework.http.ResponseEntity is in unnamed module of loader 'app')
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:221)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:108)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatchRequestContext(VertxRequestHandler.java:83)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:70)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class java.util.HashMap cannot be cast to class org.springframework.http.ResponseEntity (java.util.HashMap is in module java.base of loader 'bootstrap'; org.springframework.http.ResponseEntity is in unnamed module of loader 'app')
        at org.jboss.resteasy.spring.web.ResponseEntityContainerResponseFilter.filter(ResponseEntityContainerResponseFilter.java:16)
        at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:361)
        at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:232)
        at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:97)
        at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:70)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:217)
        ... 15 more
```. 

BTW, the details of exception handler can be found in the [`ExceptionHandler`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/ExceptionHandler.html) java doc, I am not sure which type of method parameters and return type are working in Quarkus.

**Comment by geoand** [comment]
@hantsy I will take a look

**Comment by hantsy** [comment]
I added a Jackson `ObjectMapper` bean in the [AppConfig](https://github.com/hantsy/quarkus-sandbox/blob/master/spring-post-service/src/main/java/com/example/AppConfig.java#L16-L21) to customize the JSON format. But I am not sure if this affected it.  Obviously it indicated it is a serialization issue.

**Comment by geoand** [comment]
@hantsy I figured out the problem, very interesting!

Thanks for spotting. I'll open a new issue.
