### ISSUE TITLE
smallrye-reactive-messaging-kafka: Emitter inject in SubscriberDecorator unable to connect emitter error

### ISSUE THREAD

**Issue by edeweerd1A** [quarkusio/quarkus#40443]
### Describe the bug

We have a piece of software relying on a SubscriberDecorator that itself sends messages to a Kafka topic. We do that with an Emitter. From Quarkus 3.10 the application does not start.

### Expected behavior

Quarkus is able to initialize

### Actual behavior

Initialization error with a stacktrace:

```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:643)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:727)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:285)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:252)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:610)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:660)
        ... 1 more
Caused by: jakarta.enterprise.inject.spi.DefinitionException: SRMSG00019: Unable to connect an emitter with the channel `channel-name`
        at io.smallrye.reactive.messaging.providers.extension.ChannelProducer.getEmitter(ChannelProducer.java:225)
        at io.smallrye.reactive.messaging.providers.extension.ChannelProducer.produceEmitter(ChannelProducer.java:173)
        at io.smallrye.reactive.messaging.providers.extension.ChannelProducer_ProducerMethod_produceEmitter_jRfYFqSs8A2Ams_fdlkwttyVQ3w_Bean.doCreate(Unknown Source)
        at io.smallrye.reactive.messaging.providers.extension.ChannelProducer_ProducerMethod_produceEmitter_jRfYFqSs8A2Ams_fdlkwttyVQ3w_Bean.create(Unknown Source)
[...]
```

### How to Reproduce?

[reproducer-channel-injection.zip](https://github.com/quarkusio/quarkus/files/15202454/reproducer-channel-injection.zip)

* Unzip the small reproducer project
* mvn clean install

### Output of `uname -a` or `ver`

Linux xxx 6.5.0-28-generic #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22)

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by edeweerd1A** [comment]
Let me know if I need reporting this upstream to smallrye-reactive-messaging repository.

**Comment by ozangunalp** [comment]
Thanks for the reproducer.

It is very easy to create cyclic bean dependencies with emitters and `SubscriberDecorator`, because decorators are called immediately after creation. I am actually surprised you didn't have the issue with the `@Outgoing` channel already.

Please use an indirection to access the `Emitter` you are calling in the `SubscriberDecorator`, for example a separate bean that'll provide the emitter to the decorator.

```
@ApplicationScoped
public class EmitterProvider {
    
  @Channel("channel-name")
  Emitter<byte[]> emitter;

  Emitter<byte[]> getEmitter() {
    return emitter;
  }

}
```

You're having the issue updating to 3.10 because now subscriber decorators are also called on _outgoing channel_ created for the dead letter queue.

Hope this explains.

**Comment by edeweerd1A** [comment]
OK now I understand! And thanks for the suggestion.
