### ISSUE TITLE
Remote development mode: RemoteSyncHandler interrupted exception

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#40503]
### Describe the bug

When starting the application in remote development mode, I see the following exception sometimes:
```
2024-05-07 18:00:17,396 ERROR [io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler] (vert.x-worker-thread-14) interrupted
java.lang.InterruptedException
	at java.base/java.lang.Object.wait0(Native Method)
	at java.base/java.lang.Object.wait(Object.java:366)
	at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler.doPreScan(RemoteSyncHandler.java:66)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$1.run(VertxHttpHotReplacementSetup.java:52)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:457)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:443)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:161)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:148)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

and:
``` 
2024-05-07 18:44:22,085 ERROR [io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler] (vert.x-eventloop-thread-0) Invalid session
```

and on the client side: 
``` 
2024-05-07 18:44:17,760 ERROR [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) {} Remote dev request failed: java.io.IOException: Server returned HTTP response code: 503 for URL: https://x/dev
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
        at io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient$Session.run(HttpRemoteDevClient.java:222)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```  

These exceptions do not seem to alter the functional behavior. in other words, I have been able to get the application patched and restarted.

### Expected behavior

The exceptions would ideally be understood, and corrected at the root cause.
If this is just noise, then this may be tuned down a bit.

### Actual behavior

Noisy behavior. It is not easy to figure out if something is wrong or not.

### How to Reproduce?

I am running a containerized application running in ocp.

### Quarkus version or git rev

89b732bdc82 (future 3.11)

**Comment by lukens** [comment]
I have started to encounter this issue when trying to update Quarkus from 2.7.1 on a project I've not worked on for a while.

I got errors as above when updating to the latest 3.17.3. Working back through versions to find when the issue emerged, it seems to be introduced when going from 3.8.x to 3.9.x.

I'm wondering if its related to the change from `quarkus-resteasy-reactive` to `quarkus-rest`, though, only because that seems maybe the most like change in the release.

With 3.9 and up I seem to always get the above errors when it tries to update a class on the remote instance.

As @vsevel says, this doesn't actually seem to be breaking the functionality of remote dev; however, I hadn't realised this until reading their comment and doing some more testing, and have spent the past few hours trying to find a "fix" for this, as I thought it had broken remote dev.

**Comment by cjmaria** [comment]
I've just set up a new project with `quarkus-rest` and I am using remote dev attaching to a local Docker container.  I also get these errors every time I make a request to Quarkus after a code change, but it does not seem to impact anything as my changes still take effect after reload. Toggling `QUARKUS_LIVE_RELOAD_INSTRUMENTATION` also had no impact.

<details>
<summary>Output from ./gradlew quarkusRemoteDev</summary>

```
2025-03-17 14:22:05,171 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Remote dev client thread) Restarting quarkus due to changes in ResponseObject.class, S3Resource.class, S3Resource$listObjects$1.class.
2025-03-17 14:22:06,026 INFO  [io.qua.dep.QuarkusAugmentor] (Remote dev client thread) Quarkus augmentation completed in 853ms
2025-03-17 14:22:06,034 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Remote dev client thread) Live reload total time: 3.436s 
2025-03-17 14:22:06,881 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending dev/app/com/nyiso/ResponseObject.class
2025-03-17 14:22:06,885 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending dev/app/com/nyiso/S3Resource.class
2025-03-17 14:22:06,887 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending app/quarkus-application.jar
2025-03-17 14:22:06,889 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending quarkus-run.jar
2025-03-17 14:22:06,890 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending dev/app/com/nyiso/S3Resource$listObjects$1.class
2025-03-17 14:22:07,197 ERROR [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Remote dev request failed: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:3000/dev
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2013)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614)
	at io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient$Session.run(HttpRemoteDevClient.java:222)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
</details>

<details>
<summary>Output from Quarkus application in Docker</summary>

```
public-api-1  | __  ____  __  _____   ___  __ ____  ______
public-api-1  |  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
public-api-1  |  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
public-api-1  | --\___\_\____/_/ |_/_/|_/_/|_|\____/___/
public-api-1  | 2025-03-17 18:26:22,974 INFO  [com.nyi.S3ClientProducer] (Quarkus Main Thread) Creating S3 client with endpoint: http://s3.localhost.localstack.cloud:4566
public-api-1  | 2025-03-17 18:26:22,989 INFO  [io.quarkus] (Quarkus Main Thread) public-api 1.0-SNAPSHOT on JVM (powered by Quarkus 3.19.3) started in 0.266s. Listening on: http://0.0.0.0:3000
public-api-1  | 2025-03-17 18:26:22,990 INFO  [io.quarkus] (Quarkus Main Thread) Profile localstack activated. Live Coding activated.
public-api-1  | 2025-03-17 18:26:22,990 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, kotlin, micrometer, rest, rest-jackson, smallrye-context-propagation, vertx]
public-api-1  | 2025-03-17 18:26:22,991 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-8) Live reload total time: 2.249s
public-api-1  | 2025-03-17 18:26:22,991 ERROR [io.qua.ver.htt.run.dev.RemoteSyncHandler] (vert.x-worker-thread-7) Connect failed: java.lang.InterruptedException
public-api-1  |         at java.base/java.lang.Object.wait0(Native Method)
public-api-1  |         at java.base/java.lang.Object.wait(Object.java:366)
public-api-1  |         at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$3$1.call(RemoteSyncHandler.java:144)
public-api-1  |         at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$3$1.call(RemoteSyncHandler.java:130)
public-api-1  |         at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$4(ContextImpl.java:192)
public-api-1  |         at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
public-api-1  |         at io.vertx.core.impl.ContextImpl$1.execute(ContextImpl.java:221)
public-api-1  |         at io.vertx.core.impl.WorkerTask.run(WorkerTask.java:56)
public-api-1  |         at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:81)
public-api-1  |         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
public-api-1  |         at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
public-api-1  |         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
public-api-1  |         at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
public-api-1  |         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
public-api-1  |         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
public-api-1  |         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
public-api-1  |         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
public-api-1  |         at java.base/java.lang.Thread.run(Thread.java:1583)
public-api-1  |
public-api-1  | 2025-03-17 18:26:22,993 INFO  [com.nyi.S3Resource] (vert.x-eventloop-thread-1) Endpoint hit!!! Maybe this will change?
public-api-1  | 2025-03-17 18:26:22,993 INFO  [com.nyi.S3Resource] (vert.x-eventloop-thread-1) Yee Haw! Anythign new here?
```
</details>

**Comment by geoand** [comment]
Is this still an issue with the latest version of Quarkus? If so, how can I reproduce it?

**Comment by vsevel** [comment]
not relevant to our teams anymore. I do not believe the feature is being used at the moment.

**Comment by geoand** [comment]
Thanks for the update!

**Comment by lukens** [comment]
@geoand - hi, it is still relevant to my team! I can try and test if it is still occurring next week.

**Comment by geoand** [comment]
Got it! I'll reopen

**Comment by lukens** [comment]
@geoand - sorry this has taken forever to get back to you on.

Issue is still there.

Error on remote side:

```
2026-01-20 19:17:33,392 ERROR [io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler] (vert.x-worker-thread-1) Connect failed: java.lang.InterruptedException
	at java.base/java.lang.Object.wait0(Native Method)
	at java.base/java.lang.Object.wait(Object.java:366)
	at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$3$1.call(RemoteSyncHandler.java:142)
	at io.quarkus.vertx.http.runtime.devmode.RemoteSyncHandler$3$1.call(RemoteSyncHandler.java:129)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$4(ContextImpl.java:192)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextImpl$1.execute(ContextImpl.java:221)
	at io.vertx.core.impl.WorkerTask.run(WorkerTask.java:56)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:81)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Error on local side:

```
2026-01-20 19:17:33,397 ERROR [io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient] (Remote dev client thread) Remote dev request failed: java.io.IOException: Server returned HTTP response code: 500 for URL: http://ako-dev/mywbs-event-streams/dev
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2028)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1629)
	at io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient$Session.run(HttpRemoteDevClient.java:222)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Despite the errors, everything does seem to actually work.

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/52110 should take care of it
