### ISSUE TITLE
Remote development mode: SmallRyeOpenApiProcessor throws AccessDeniedException: /target

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#40501]
### Describe the bug

When starting an application for remote dev, and using extension openapi, the application fails to start, and displays:
```
2024-05-07 18:13:42,570 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) {} Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /target
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.nio.file.AccessDeniedException: /target
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
	at java.base/java.nio.file.Files.createDirectory(Files.java:699)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.storeGeneratedSchema(SmallRyeOpenApiProcessor.java:950)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.storeDocument(SmallRyeOpenApiProcessor.java:1225)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.storeDocument(SmallRyeOpenApiProcessor.java:1183)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:904)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	... 7 more
```

My application is built inside a jvm container.

A workaround consists in adding this property to the application:
```
quarkus:
 smallrye-openapi:
   store-schema-directory: /tmp
```

### Expected behavior

The application should start, using a folder that makes sense in the context of a remote dev application packaged as a container and deployed into a K8s cluster.

### Actual behavior

The application fails to start. 

### How to Reproduce?

The test application has: Installed features: [cache, cdi, config-yaml, confluent-registry-avro, hibernate-validator, ironjacamar, kafka-client, messaging, messaging-kafka, micrometer, narayana-jta, opentelemetry, rest, rest-client, rest-client-jackson, rest-jackson, scheduler, security, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-openapi, swagger-ui, vault, vertx]

### Quarkus version or git rev

89b732bdc82 (future 3.11)

**Comment by MikeEdgar** [comment]
Do you have `store-schema-directory` set some other way when the error occurs? It should only attempt to store the generated schema when a directory has been configured.

**Comment by vsevel** [comment]
no

**Comment by vsevel** [comment]
my bad @MikeEdgar . we had that in one our of extensions (which seemed appropriate for a normal build or quarkus:dev, but does not in a mutable jar):
``` 
quarkus:
  smallrye-openapi:
    store-schema-directory: target/generated-api
```

so with https://github.com/quarkusio/quarkus/pull/40437 we now have a clear error message
not an issue. I am closing this. wondering if we or quarkus should do something else to improve?
