### ISSUE TITLE
Quarkus 3.10.0 doesnt support flyway with Postgresql 16

### ISSUE THREAD

**Issue by agilob** [quarkusio/quarkus#40512]
### Describe the bug

Quarkus 3.10.0 comes with flyway 10.10.0, which should support Postgresql 16 as such support was introduced in 10.1.0
https://documentation.red-gate.com/flyway/release-notes-and-older-versions/release-notes-for-flyway-engine

When running only with:
```
    <quarkus.platform.version>3.10.0</quarkus.platform.version>
...
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-flyway</artifactId>
    </dependency>
```

Quarkus crashes on start up with:
```
2024-05-07 19:20:52,512 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
     at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
     at io.quarkus.runtime.Application.start(Application.java:101)
     at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
     at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
     at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
     at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
     at io.quarkus.runner.GeneratedMain.main(Unknown Source)
     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
     at java.base/java.lang.reflect.Method.invoke(Method.java:580)
     at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
     at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 16.1
     at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105)
     at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:73)
     at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:134)
     at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
     at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:136)
     at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy_0(Unknown Source)
     at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy(Unknown Source)
     ... 11 more
```

But when I add the same version of flyway postgres library:

```
    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-database-postgresql</artifactId>
      <version>10.10.0</version>
      <scope>runtime</scope>
    </dependency>
```

so the dependency tree is:

```
❯ mvn dependency:tree | grep flyway
[INFO] +- io.quarkus:quarkus-flyway:jar:3.10.0:compile
[INFO] |  +- org.flywaydb:flyway-core:jar:10.10.0:compile
[INFO] +- org.flywaydb:flyway-database-postgresql:jar:10.10.0:runtime
```

Everything is working again.

Looks like it's linked to a poor communication from flyway side: https://github.com/flyway/flyway/issues/3819

I think quarkus should come with flyway postgres module, but maybe you decided against it for some reason?

**Comment by gastaldi** [comment]
You need to add a new dependency. See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10#flyway-10-gear-white_check_mark
