### ISSUE TITLE
Issue found with Brotli4J compression run in Openshift in native mode

### ISSUE THREAD

**Issue by jcarranzan** [quarkusio/quarkus#40533]
### Describe the bug

I've been doing a Quarkus Http Brotli4J test coverage development and the tests were passing ok in different environments but just gave me issues in Openshift and native mode execution.

- Context execution found in:

   RHEL8 / JDK 17 / Run OpenShift tests in native mode
-  native image used:
`  <quarkus.s2i.base-native-image>quay.io/quarkus/ubi-quarkus-native-binary-s2i:2.0</quarkus.s2i.base-native-image>`
- Quarkus platform version: 
  3.10.0

This is my reproducer:
https://github.com/jcarranzan/quarkus-reproducer/tree/brotli4j-native 
This is the maven command execution:
` mvn clean verify -Dnative -Popenshift -Dfailsafe.failIfNoSpecifiedTests=false -Dit.test="OpenShiftBrotli4JIT"`

Error logs:
```
  10:24:27,158 INFO  ## Running test OpenShiftBrotli4JIT.checkTextPlainWithtBrotli4J()
12:24:30  10:24:30,075 INFO  [app] 10:24:27,207 Failed to initialize a channel. Closing: [id: 0x832a69a5, L:embedded - R:embedded]: io.netty.channel.ChannelPipelineException: io.netty.handler.codec.compression.BrotliEncoder.handlerAdded() has thrown an exception; removed.
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:624)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.embedded.EmbeddedChannel$2.initChannel(EmbeddedChannel.java:222)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1130)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:480)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.embedded.EmbeddedChannel$EmbeddedUnsafe$1.register(EmbeddedChannel.java:840)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.embedded.EmbeddedEventLoop.register(EmbeddedEventLoop.java:181)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.embedded.EmbeddedEventLoop.register(EmbeddedEventLoop.java:175)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.embedded.EmbeddedChannel.setup(EmbeddedChannel.java:227)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:204)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.handler.codec.http.HttpContentCompressor.beginEncode(HttpContentCompressor.java:275)
12:24:30  10:24:30,075 INFO  [app] 	at io.vertx.core.http.impl.HttpChunkContentCompressor.beginEncode(HttpChunkContentCompressor.java:51)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.handler.codec.http.HttpContentEncoder.encode(HttpContentEncoder.java:163)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.handler.codec.http.HttpContentEncoder.encode(HttpContentEncoder.java:57)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
12:24:30  10:24:30,075 INFO  [app] 	at io.vertx.core.http.impl.HttpChunkContentCompressor.write(HttpChunkContentCompressor.java:46)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:891)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.handler.stream.ChunkedWriteHandler.write(ChunkedWriteHandler.java:140)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:891)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:305)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:891)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.onHttpResponseWrite(WebSocketServerExtensionHandler.java:212)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.write(WebSocketServerExtensionHandler.java:169)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:891)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:956)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:982)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:950)
12:24:30  10:24:30,075 INFO  [app] 	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:181)
12:24:30  10:24:30,075 INFO  [app] 	at io.vertx.core.net.impl.ConnectionBase.lambda$queueForWrite$2(ConnectionBase.java:247)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
12:24:30  10:24:30,075 INFO  [app] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
12:24:30  10:24:30,076 INFO  [app] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
12:24:30  10:24:30,076 INFO  [app] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
12:24:30  10:24:30,076 INFO  [app] 	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
12:24:30  10:24:30,076 INFO  [app] 	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
12:24:30  10:24:30,076 INFO  [app] 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
12:24:30  10:24:30,076 INFO  [app] 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
12:24:30  10:24:30,076 INFO  [app] Caused by: java.lang.UnsatisfiedLinkError: com.aayushatharva.brotli4j.encoder.EncoderJNI.nativeCreate([J)Ljava/nio/ByteBuffer; [symbol: Java_com_aayushatharva_brotli4j_encoder_EncoderJNI_nativeCreate or Java_com_aayushatharva_brotli4j_encoder_EncoderJNI_nativeCreate___3J]
12:24:30  10:24:30,076 INFO  [app] 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
12:24:30  10:24:30,076 INFO  [app] 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
12:24:30  10:24:30,076 INFO  [app] 	at com.aayushatharva.brotli4j.encoder.EncoderJNI.nativeCreate(Native Method)
12:24:30  10:24:30,076 INFO  [app] 	at com.aayushatharva.brotli4j.encoder.EncoderJNI.access$200(EncoderJNI.java:17)
12:24:30  10:24:30,076 INFO  [app] 	at com.aayushatharva.brotli4j.encoder.EncoderJNI$Wrapper.<init>(EncoderJNI.java:90)
12:24:30  10:24:30,076 INFO  [app] 	at com.aayushatharva.brotli4j.encoder.Encoder.<init>(Encoder.java:48)
12:24:30  10:24:30,076 INFO  [app] 	at com.aayushatharva.brotli4j.encoder.BrotliEncoderChannel.<init>(BrotliEncoderChannel.java:38)
12:24:30  10:24:30,076 INFO  [app] 	at com.aayushatharva.brotli4j.encoder.BrotliEncoderChannel.<init>(BrotliEncoderChannel.java:50)
12:24:30  10:24:30,076 INFO  [app] 	at io.netty.handler.codec.compression.BrotliEncoder$Writer.<init>(BrotliEncoder.java:193)
12:24:30  10:24:30,076 INFO  [app] 	at io.netty.handler.codec.compression.BrotliEncoder$Writer.<init>(BrotliEncoder.java:185)
12:24:30  10:24:30,076 INFO  [app] 	at io.netty.handler.codec.compression.BrotliEncoder.handlerAdded(BrotliEncoder.java:102)
12:24:30  10:24:30,076 INFO  [app] 	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1130)
12:24:30  10:24:30,076 INFO  [app] 	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
12:24:30  10:24:30,076 INFO  [app] 	... 61 more
```

### Expected behavior

Works properly

### Actual behavior

Tests failed because of the error mentioned above in the description.

### How to Reproduce?

1. `git clone https://github.com/jcarranzan/quarkus-reproducer/tree/brotli4j-native `
2. Login in an openshift cluster
3. Execution in Openshift with native profile:
` mvn clean verify -Dnative -Popenshift -Dfailsafe.failIfNoSpecifiedTests=false -Dit.test="OpenShiftBrotli4JIT"`
4. Check the logs

### Output of `uname -a` or `ver`

Linux Fedora 39 x86_64

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17

**Comment by jedla97** [comment]
Just a note. This is also happening on baremetal. You can check it with provided reproducer by running `mvn clean verify -Dnative`
1. `mvn install -Dnative`
2. `./target/reproducer-with-quarkus-1.0.0-SNAPSHOT-runner`
3. Go to http://127.0.0.1:8080/compression/text and see quarkus log

**Comment by Karm** [comment]
Hello @jcarranzan,

I have your reproducer working properly in native. Let me polish the how-to and share it with you.

This is neither Quarkus nor GraalVM issue per se. It's just that AOT requires some more config work to get it working. 
Quarkus extensions shield users from this complexity, but since there is none for this specific library usage (or none I know of), you need to add some manual configs.

**Comment by gsmet** [comment]
Is this usage widespread? Would it make sense to develop a small extension similar to what I did here: https://github.com/quarkiverse/quarkus-opencv/ ?

**Comment by cescoffier** [comment]
I would not say 'widespread'. It's starting to be used. Vert.x already has the support (via netty), and due to some ugly substitution business, we have it on the classpath.

@Karm Based on your exploration, I would do the same thing I did for RocksDB, Snappy... If a built-time property enables Brotli, we include the appropriate native library into the native executable and mark Broli4Loarder as runtime init.

**Comment by Karm** [comment]
@melloware @cescoffier 

> Should we re-open this ticket then?

I don't know. Not a bug... it's a missing feature :)

I will work on the seamless integration regardless of this particular issue being open or not.

**Comment by cescoffier** [comment]
I guess the next to be PR should be enough. This ticket provides the workaround (correct instructions).

**Comment by melloware** [comment]
@Karm thanks i will monitor for PR's!

**Comment by fedinskiy** [comment]
@Karm sorry for resurrecting this thread, but if I understand correctly, this feature should work iafter adding `quarkus.http.compressors=deflate,gzip,br` property, is that correct?
