### ISSUE TITLE
QuarkusConfigFactory not a subtype when using Uni

### ISSUE THREAD

**Issue by sammehdevel** [quarkusio/quarkus#40540]
### Describe the bug

When combining unis I intermittently get the following exception `java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype`

It's shown up a few times in different places in my code, so I'm not sure if I'm using Mutiny wrong or it's a bug in quarkus.

This is the code block throwing the error. postProcessor.processStats is a kotlin coroutine being turned into a Uni, but I've had this issue show up on "native" Unis
```
    fun computeStats(jobId: String): Uni<Boolean> {
        return Uni.combine().all().unis<Int>(
            computeAndStoreTrips(jobId),
            computeAndStoreHaulCycles(jobId),
            postProcessor.processStats(jobId) // throwing here
        ).with { true }
    }
```

### Expected behavior

I wouldn't expect it to fail with this specific error. If it's the way I'm using Mutiny I would expect a more specific error message. But this looks like a class loader issue?

### Actual behavior

Fails 1 in 5 times with the following error
```2024-05-09 13:35:56,991 ERROR [com.str.mes.rea.pro.MessageListener$init$1$2] (ForkJoinPool.commonPool-worker-92) Failed processing message: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:102)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:78)
        at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:101)
        at io.smallrye.config.inject.ConfigProducer.getConfig(ConfigProducer.java:45)
        at io.smallrye.config.inject.ConfigProducer.getIntegerValue(ConfigProducer.java:66)
        at io.smallrye.config.inject.ConfigProducer_Subclass.getIntegerValue$$superforward(Unknown Source)
        at io.smallrye.config.inject.ConfigProducer_Subclass$$function$$7.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.arc.runtime.ConfigStaticInitCheckInterceptor.aroundInvoke(ConfigStaticInitCheckInterceptor.java:47)
        at io.quarkus.arc.runtime.ConfigStaticInitCheckInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at io.smallrye.config.inject.ConfigProducer_Subclass.getIntegerValue(Unknown Source)
        at io.smallrye.config.inject.ConfigProducer_ProducerMethod_getIntegerValue_dhQE7qVWDdkn-iwoTirb1GnLaWs_Bean.doCreate(Unknown Source)
        at io.smallrye.config.inject.ConfigProducer_ProducerMethod_getIntegerValue_dhQE7qVWDdkn-iwoTirb1GnLaWs_Bean.create(Unknown Source)
        at io.smallrye.config.inject.ConfigProducer_ProducerMethod_getIntegerValue_dhQE7qVWDdkn-iwoTirb1GnLaWs_Bean.get(Unknown Source)
        at io.smallrye.config.inject.ConfigProducer_ProducerMethod_getIntegerValue_dhQE7qVWDdkn-iwoTirb1GnLaWs_Bean.get(Unknown Source)
        at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:48)
        at com.stream.config.ConcurrencyProperties_Bean.doCreate(Unknown Source)
        at com.stream.config.ConcurrencyProperties_Bean.create(Unknown Source)
        at com.stream.config.ConcurrencyProperties_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c72(Unknown Source)
        at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
        at com.stream.config.ConcurrencyProperties_ClientProxy.arc$delegate(Unknown Source)
        at com.stream.config.ConcurrencyProperties_ClientProxy.getThreads(Unknown Source)
        at com.stream.stat.PostProcessor.<init>(PostProcessor.kt:39)
        at com.stream.stat.PostProcessor_Bean.doCreate(Unknown Source)
        at com.stream.stat.PostProcessor_Bean.create(Unknown Source)
        at com.stream.stat.PostProcessor_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c3(Unknown Source)
        at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
        at com.stream.stat.PostProcessor_ClientProxy.arc$delegate(Unknown Source)
        at com.stream.stat.PostProcessor_ClientProxy.processStats(Unknown Source)
        at com.stream.messaging.reactive.processor.postprocess.PostProcessor.computeStats(PostProcessor.kt:144)
        at com.stream.messaging.reactive.processor.postprocess.PostProcessor$process$1.invoke(PostProcessor.kt:48)
        at com.stream.messaging.reactive.processor.postprocess.PostProcessor$process$1.invoke(PostProcessor.kt:48)
        at com.stream.messaging.reactive.processor.postprocess.PostProcessor.process$lambda$0(PostProcessor.kt:48)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:47)
        at io.smallrye.mutiny.operators.uni.UniLogger$UniLoggerProcessor.onItem(UniLogger.java:54)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.computeAndFireTheOutcome(UniAndCombination.java:151)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.check(UniAndCombination.java:130)
        at io.smallrye.mutiny.operators.uni.UniAndCombination$UniHandler.onItem(UniAndCombination.java:220)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### How to Reproduce?

I'm unable to reproduce it consistently

### Output of `uname -a` or `ver`

Linux SS00260 6.5.0-28-generic #29-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar 28 23:46:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

-> % java -version 
openjdk version "17.0.5" 2022-10-18 LTS
OpenJDK Runtime Environment GraalVM 22.3.0 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM GraalVM 22.3.0 (build 17.0.5+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/apache-maven-3.8.6
Java version: 17.0.5, vendor: BellSoft, runtime: /home/sharrison/.sdkman/candidates/java/22.3.r17-nik
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.5.0-28-generic", arch: "amd64", family: "unix"

**Comment by sammehdevel** [comment]
I think I have solved my issue...

After reading about a totally unrelated issue about running panache on arbitrary threads, I thought maybe this was the same issue so I switched the following
```
    fun processStats(jobId: String): Uni<Unit> {
        return CoroutineScope(newFixedThreadPoolContext(concurrencyProperties.threads, "PostProcessing-Executor")).async {
...
        }.asUni()
    }
```
with 
```
    fun processStats(jobId: String): Uni<Unit> {
        return CoroutineScope(Infrastructure.getDefaultWorkerPool().asCoroutineDispatcher()).async {
...
        }.asUni()
    }
```

And it seems to work!

**Comment by geoand** [comment]
This is almost certainly has the root as described in #40245.
