### ISSUE TITLE
" java.lang.ClassNotFoundException: Worker" running "quarkusDev" or "build" when quarkus.docker.dockerfile-native-path=/docker/Dockerfile.native is used

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#40544]
### Describe the bug

I've encountered a very sneaky issue:

In one branch I've added some additional config lines into the `application.properties` of the base module of my multi-module Gradle project

![image](https://github.com/quarkusio/quarkus/assets/1553757/c46b7219-da63-408c-91db-144a53ca55e9)

Neither build nor running the application was working and failed with

```
Could not write standard input to Gradle Worker Daemon 22.
java.io.IOException: Die Pipe wird gerade geschlossen
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:367)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:125)
	at java.base/java.io.BufferedOutputStream.implFlush(BufferedOutputStream.java:252)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:240)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.writeBuffer(ExecOutputHandleRunner.java:98)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:85)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:64)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Fehler: Hauptklasse Worker konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: Worker

> Task :base:quarkusGenerateCode FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':base:quarkusGenerateCode'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.CodeGenWorker
      > Failed to run Gradle Worker Daemon
         > Process 'Gradle Worker Daemon 22' finished with non-zero exit value 1
```

Turns out it is this specific line causing it

> quarkus.docker.dockerfile-native-path=/docker/Dockerfile.native"

### Expected behavior

I expect at least that quarkusDev is working, as this property should only affect the build.

### Actual behavior

Build and run failing

### Output of `java -version`

21

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.7

**Comment by dmlloyd** [comment]
This might possibly be the same issue as #40496.

**Comment by geoand** [comment]
Is this still an issue with https://github.com/quarkusio/quarkus/pull/40496 now in?

**Comment by geoand** [comment]
Closing for the lack of feedback
