### ISSUE TITLE
access-log - custom category doesn't work

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#4059]
access-log - custom category doesn't work on master. This works with 0.22.0.

`access-log(format='common', category='my.own.category')` defined in META-INF/undertow-handlers.conf, using sample getting-started application generated via quarkus maven plugin

Quarkus 0.22.0
```
[INFO] --- quarkus-maven-plugin:0.22.0:dev (default-cli) @ getting-started ---
Listening for transport dt_socket at address: 5005
2019-09-17 09:48:07,002 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-09-17 09:48:07,721 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 719ms
2019-09-17 09:48:08,027 INFO  [io.quarkus] (main) Quarkus 0.22.0 started in 1.216s. Listening on: http://[::]:8080
2019-09-17 09:48:08,029 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
2019-09-17 09:50:22,382 INFO  [my.own.category] (executor-thread-1) 0:0:0:0:0:0:0:1 - - [17/Sep/2019:09:50:22 +0200] "GET /health HTTP/1.1" 404 1999
^C2019-09-17 09:52:20,267 INFO  [io.quarkus] (Quarkus Shutdown Thread) Quarkus stopped in 0.003s
```

Quarkus master (mvn clean package quarkus:dev -DskipTests):
```
java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:134)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
	at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:195)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:116)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:52)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:44)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl2.<clinit>(ApplicationImpl2.zig:163)
	... 16 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: UT000045: Error parsing predicated handler string unknown parameter category:
access-log(format='common', category='my.own.category')
                                                     ^
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:399)
	at io.quarkus.deployment.steps.UndertowBuildStep$build45.deploy_0(UndertowBuildStep$build45.zig:351)
	at io.quarkus.deployment.steps.UndertowBuildStep$build45.deploy(UndertowBuildStep$build45.zig:376)
	at io.quarkus.runner.ApplicationImpl2.<clinit>(ApplicationImpl2.zig:149)
	... 16 more
Caused by: java.lang.IllegalArgumentException: UT000045: Error parsing predicated handler string unknown parameter category:
access-log(format='common', category='my.own.category')
                                                     ^
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.error(PredicatedHandlersParser.java:729)
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.handleHandlerNode(PredicatedHandlersParser.java:171)
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.handleNode(PredicatedHandlersParser.java:114)
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.parse(PredicatedHandlersParser.java:91)
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.parse(PredicatedHandlersParser.java:80)
	at io.quarkus.undertow.runtime.UndertowHandlersConfServletExtension.handleDeployment(UndertowHandlersConfServletExtension.java:33)
	at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:300)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:155)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:388)
	... 19 more
```

This issue blocks progress on PR https://github.com/quarkusio/quarkus/pull/3792

**Comment by geoandri** [comment]
I think the quarkus-http dependency that was introduced in 0.23.0 (https://github.com/quarkusio/quarkus/blob/0.23.0/bom/runtime/pom.xml#L27) caused the problem (https://github.com/quarkusio/quarkus-http/blob/3.0.0.Alpha5/core/src/main/java/io/undertow/server/handlers/accesslog/AccessLogHandler.java#L164). 
In 0.22.0, the undertow dependency had the appropriate `parameters()` method (https://github.com/undertow-io/undertow/blob/2.0.23.Final/core/src/main/java/io/undertow/server/handlers/accesslog/AccessLogHandler.java#L179).

**Comment by gsmet** [comment]
@anamarija can you have at @geoandri 's comment? I think it should be an easy fix but we would need to be adding the category there fixes the issue.

**Comment by gsmet** [comment]
BTW, `quarkus-http` is in another repo there: https://github.com/quarkusio/quarkus-http/

**Comment by anamarija** [comment]
ok. Just I can do it later tonight :)

**Comment by gsmet** [comment]
This will require a new Quarkus HTTP release.

**Comment by anamarija** [comment]
yes :)

**Comment by gsmet** [comment]
This one has been solved by @anamarija in quarkus-http: https://github.com/quarkusio/quarkus-http/pull/11

**Comment by rsvoboda** [comment]
I tried to use access log for getting started project but didn't see any access log entries.
I think it's because `quarkus-http` is not used in getting started project :/
Will create new issue for this.

```
[INFO] org.acme:getting-started:jar:1.0-SNAPSHOT
[INFO] +- io.quarkus:quarkus-resteasy:jar:1.0.0.CR1:compile
[INFO] |  +- io.quarkus:quarkus-vertx-http:jar:1.0.0.CR1:compile
```

**Comment by gsmet** [comment]
This issue is not solved in CR1 so that's probably why you don't see it fixed.

**Comment by rsvoboda** [comment]
Using master, the issue is that no access log is produced with getting-started sample app, issue linked now
