### ISSUE TITLE
Service not registering jandex indexed beans in multi-module project (gradle/kotlin)

### ISSUE THREAD

**Issue by adamvelo** [quarkusio/quarkus#40693]
### Describe the bug

Quarkus doesn't seem to be honouring the jandex index when operating in a multi-module gradle project.

I have a multi-module gradle build with a rest-module containing a rest resource and a ModuleService class marked with @Singleton - this module includes the gradle jandex plugin in its build file and correctly includes the /META-INF/jandex.idx file in the jar. The other module is called "service" and includes the rest-module as a dependency but when the service starts up the ExampleService bean tries to wire in the ModuleService which should be registered (I believe) with the CDI context via the jandex index file in the rest-module but it fails with:

      Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.ModuleService and qualifiers [@Default]
	  - injection target: parameter 'moduleService' of org.acme.service.ExampleService constructor
	  - declared on CLASS bean [types=[org.acme.service.ExampleService, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.service.ExampleService]
	  at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
	  at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:638)
	  at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:308)
	  ... 11 more

### Expected behavior

The service should correctly manage the CDI beans from the rest-module and wire them into the service.

### Actual behavior

The service is not seeing the beans described in the jandex index in the rest-module and is failing to start with a jakarta.enterprise.inject.UnsatisfiedResolutionException

### How to Reproduce?

There is an example repo here: https://github.com/adamvelo/example-quarkus-multi-module
(I will also attach the zip file)
[example-quarkus-multi-module-main.zip](https://github.com/quarkusio/quarkus/files/15348201/example-quarkus-multi-module-main.zip)

### Output of `uname -a` or `ver`

Darwin Adams-MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Zulu21.30+15-CA (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Zulu21.30+15-CA (build 21.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.10.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.5 ------------------------------------------------------------  Build time:   2023-11-29 14:08:57 UTC Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598  Kotlin:       1.9.20 Groovy:       3.0.17 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          21.0.1 (Azul Systems, Inc. 21.0.1+12-LTS) OS:           Mac OS X 13.3.1 aarch64

### Additional information

Am I missing something here? Or should this work as is?

This is the ModuleService class in the rest-module:

    package org.acme
    import jakarta.inject.Singleton
    @Singleton
    class ModuleService {
        fun hello() : String {
            return "Hello from the module"
        }
    }

And this is the ExampleService class in the service module:

    package org.acme.service

    import jakarta.inject.Singleton
    import org.acme.ModuleService
    
    @Singleton
    class ExampleService (val moduleService: ModuleService) {
        fun helloFromModule() : String {
            return moduleService.hello()
        }
    }

**Comment by adamvelo** [comment]
The attached example was bootstrapped with the following commands:

    mkdir example
    cd example
    gradle init --dsl kotlin
    quarkus create app org.acme:rest-module --extension='kotlin,rest-jackson' --gradle-kotlin-dsl
    quarkus create app org.acme:service --extension='kotlin' --gradle-kotlin-dsl

**Comment by adamvelo** [comment]
nevermind - it was a gradle issue...  needed to add this to the top level build file:

    plugins {
        kotlin("jvm") version "1.9.23" apply false
    }
