### ISSUE TITLE
Improve usability of `quarkus.hibernate-orm.sql-load-script`

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4072]
Steps

1. create a new project with Hibernate ORM and an entity
2. in the same step add to `application.properties`

```
quarkus.hibernate-orm.sql-load-script=import-dev.sql
```

and the `import-dev.sql` file

3. Then refresh the browser

You end up with the following error

```
2019-09-17 14:35:32,484 ERROR [io.qua.dev.DevModeMain] (executor-thread-1) Failed to start quarkus: java.lang.RuntimeException:
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build threw an exception: io.quarkus.deplo
yment.configuration.ConfigurationError: Unable to find file referenced in 'quarkus.hibernate-orm.sql-load-script=import-dev.sql'
. Remove property or add file to your path.
        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.lambda$handleHibernateORMWithNoPersistenceXml$12(HibernateO
rmProcessor.java:468)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.handleHibernateORMWithNoPersistenceXml(HibernateOrmProcesso
r.java:375)
        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.build(HibernateOrmProcessor.java:180)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:768)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:141)
```

because `import-dev.sql` is not a hot resourse as it was not part of the previous application.properties, the framework fails claiming it does not file the file.

Let's try and improve the situation CC @Sanne @gsmet

**Comment by emmanuelbernard** [comment]
Option 1. don't fail with exception when the import-dev.sql file is not found but just a warning.
And force the file to be put in the hot reload list.
Also force Quarkus Core to copy the files from the hot list
Next refresh, warning should disappear.

**Comment by emmanuelbernard** [comment]
I feel there is a chicken and egg and Quarkus Core should offer a way to check for a file presence in `src` and copy in `target` via an API to properly solve this one.

**Comment by emmanuelbernard** [comment]
@stuartwdouglas

**Comment by stuartwdouglas** [comment]
I think there are two options here:

- Just copy all changed files every request, but only trigger a hot reload if a flagged file has been modified
- Change the hot reload support to have excluded files rather than included files, so we can just exclude all web resources from causing a hot reload but auto reload if any other file is changed. 

The original goal of selectively reloading on resource change was to make sure that changes to web resources did not force a restart, but maybe we took the wrong approach and the default approach should have been to always restart unless a file has been specifically excluded.

**Comment by emmanuelbernard** [comment]
I think I like point 1 best which is what's missing and I'm not sure there is a lot of harm to it.
I don't think point 2 would be going in he right direction

**Comment by Sanne** [comment]
I would expect the Extension to be ableto "register interest" in a
specific resource after its configuration is parsed. Is that too late
in the game?
