### ISSUE TITLE
RestEasy reactive: Cannot use method with same name but different parameters

### ISSUE THREAD

**Issue by ZetalyDev** [quarkusio/quarkus#40831]
### Describe the bug

Downloading a Quarkus project with "Start Coding" with only RESTEasy Reactive (3.2.12.FINAL), I modify the GreetingResource to have two @GET endpoints. I try to execute the first one.

### Expected behavior

GET endpoint working as expected.

### Actual behavior

Getting the following error:

```java
2024-05-24 13:55:20,630 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello/z failed, error id: 510e7f82-47e1-425a-b730-1cda0e5eade2-1: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
	at org.acme.GreetingResource$quarkusrestinvoker$hello_b14314082eb006718a61dd4be4a41cda1d994f26.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

Get the quarkus project from Quarkus website --> "Start Coding". Select Quarkus 3.2 to get the 3.2.12.FINAL version.

Modify the GreetingResource.java file with the following content:

```java
package org.acme;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

import java.util.List;

@Path("/hello")
@ApplicationScoped
public class GreetingResource {

    @GET
    @Path("/{variable}")
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(@PathParam("variable") String variable) {
        return "Hello from RESTEasy Reactive";
    }

    @GET
    @Path("/{variable}/abc")
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(@PathParam("variable") List<String> variable) {
        return "Hello from RESTEasy Reactive";
    }
}
```

(I have also deleted the class test)

Add the following dependancy in pom.xml:
```
<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>
```

Using swagger, I execute the first endpoint with any value for the path param "variable".

### Output of `java -version`

openjdk version "17.0.9"

### Quarkus version or git rev

3.2.12.FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.2

**Comment by geoand** [comment]
Does tge same problem occur with Quarkus 3.8?

**Comment by ZetalyDev** [comment]
@geoand  I just tested it, it is still indeed present in 3.8.4.

**Comment by geoand** [comment]
Thanks for the info
