### ISSUE TITLE
Can't update to quarkus 3.10.1

### ISSUE THREAD

**Issue by dodalovicgran** [quarkusio/quarkus#40832]
### Describe the bug

Trying to update from quarkus 3.9.5 to 3.10.1

### Actual behavior

Getting this on startup

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-05-24 16:11:10,286 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 15.6
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:73)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:134)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:136)
	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.FlywayProcessor$startActions2099152139.deploy(Unknown Source)
	... 11 more

```

**Comment by gsmet** [comment]
it is due to the update to Flyway 10. 

See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10#flyway 

I recommend using quarkus update. It would have handled it for you.

**Comment by dodalovicgran** [comment]
![image](https://github.com/quarkusio/quarkus/assets/116893230/0fcd5a76-714a-40e5-bc5d-858c0469f547)

**Comment by gsmet** [comment]
Not sure where you found this command line?

You shouldn’t have to specify a version and 3.9.3.Final doesn’t exist. It’s 3.9.3. 

I will fix it if it’s on a site we maintain.

**Comment by gsmet** [comment]
And thinking about it, I don’t recall if this particular case is handled for Gradle as the recipes are not exactly the same. I’m off today and too lazy to open my laptop :)

**Comment by mschorsch** [comment]
@dodalovicgran Just add `implementation("org.flywaydb:flyway-database-postgresql")` to your dependency list and it should work as expected. 

BTW The quarkus update tool does not seem to work in Gradle projects, at least not in our various multi module projects.

**Comment by dodalovicgran** [comment]
Thank you @mschorsch, @gsmet I update the dependency, the thing works fine!
