### ISSUE TITLE
Synthetic bean throws NoSuchMethodError for a non existing constructor on live reload

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#40854]
### Describe the bug

When using Quarkus LangChain4j after adding a tools class, when the application reloads, a very obscure  `NoSuchMethodError` is thrown.

### Expected behavior

Live reload works as excpected

### Actual behavior

```
2024-05-27 17:10:48,468 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus [Error Occurred After Shutdown]: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 15 more
Caused by: java.lang.NoSuchMethodError: 'void io.quarkiverse.langchain4j.runtime.aiservice.QuarkusAiServiceContext_DMMaQycu1p4xSTvEyHNFMDekqwc_Synthetic_Bean.<init>(java.util.function.Supplier, java.util.function.Supplier, java.util.function.Supplier)'
        at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans3(Unknown Source)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
        at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:128)
        at io.quarkus.arc.Arc.initialize(Arc.java:38)
        at io.quarkus.arc.runtime.ArcRecorder.initContainer(ArcRecorder.java:49)
        at io.quarkus.deployment.steps.ArcProcessor$initializeContainer1770303700.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.ArcProcessor$initializeContainer1770303700.deploy(Unknown Source)
        ... 16 more


2024-05-27 17:10:48,504 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (vert.x-worker-thread-1) Failed to start quarkus [Error Occurred After Shutdown]: io.quarkus.dev.appstate.ApplicationStartException: java.lang.NoSuchMethodError: 'void io.quarkiverse.langchain4j.runtime.aiservice.QuarkusAiServiceContext_DMMaQycu1p4xSTvEyHNFMDekqwc_Synthetic_Bean.<init>(java.util.function.Supplier, java.util.function.Supplier, java.util.function.Supplier)'
        at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:58)
        at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:132)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:192)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:173)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:541)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:441)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.call(VertxHttpHotReplacementSetup.java:150)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.call(VertxHttpHotReplacementSetup.java:137)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:177)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:276)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:209)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NoSuchMethodError: 'void io.quarkiverse.langchain4j.runtime.aiservice.QuarkusAiServiceContext_DMMaQycu1p4xSTvEyHNFMDekqwc_Synthetic_Bean.<init>(java.util.function.Supplier, java.util.function.Supplier, java.util.function.Supplier)'
        at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans3(Unknown Source)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
        at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:128)
        at io.quarkus.arc.Arc.initialize(Arc.java:38)
        at io.quarkus.arc.runtime.ArcRecorder.initContainer(ArcRecorder.java:49)
        at io.quarkus.deployment.steps.ArcProcessor$initializeContainer1770303700.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.ArcProcessor$initializeContainer1770303700.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
        ... 1 more
```

### How to Reproduce?

Use the `email-me-a-poem` Quarkus LangChain4j [sample](https://github.com/quarkiverse/quarkus-langchain4j/tree/main/samples/email-a-poem).

* Before starting the application delete `EmailService.java` and also change the `@RegisterAiService` on `MyAiService` by removing the `tools` attribute.

* `mvn quarkus:dev` 

* Load http://localhost:8080 and hit the `email me a poem button`

* Execute `git revert` to revert the changes made

* Load http://localhost:8080

* The exception now appears

### Output of `java -version`

17

### Quarkus version or git rev

Tested with 3.8

**Comment by mkouba** [comment]
Keep in mind, that `QuarkusAiServiceContext_DMMaQycu1p4xSTvEyHNFMDekqwc_Synthetic_Bean.<init>(java.util.function.Supplier, java.util.function.Supplier, java.util.function.Supplier)` is not a constructor of the bean class but of the generated bean metadata class, i.e. something that implements `Bean`. Those suppliers usually represent bean dependencies, i.e. other `Bean`s.

**Comment by geoand** [comment]
Any more clues would be appreciated 😜

**Comment by mkouba** [comment]
> Any more clues would be appreciated 😜

Fore sure, except that I don't have OpenAI API key, yet...

**Comment by mkouba** [comment]
I think that you need to use `configurator.forceApplicationClass()` for the `QuarkusAiServiceContext` synthetic bean. The `QuarkusAiServiceContext` class comes from an extension and so it's not considered an app class in the dev mode by default. In other words, the definition is not reloaded during live reload.

In general, we do not expect the bean metadata provided by extensions to depend on app code, i.e. to change between live reloads...

**Comment by geoand** [comment]
Oh, I didn't know about that configuration knob at all.

I'll check it out soon and let you know.
