### ISSUE TITLE
Regression: Unexpected `DisabledOidcClientException`

### ISSUE THREAD

**Issue by neon-dev** [quarkusio/quarkus#40886]
### Describe the bug

#37361 should allow us to set `quarkus.oidc-client.client-enabled=false` and use the `@OidcClientFilter` annotated REST client without trying (and failing) to acquire a token.
This is currently not the case:
```
io.quarkus.oidc.client.runtime.DisabledOidcClientException: 'Default' client configuration is disabled
	at io.quarkus.oidc.client.runtime.OidcClientRecorder$DisabledOidcClient.getTokens(OidcClientRecorder.java:251)
	at io.quarkus.oidc.client.runtime.TokensHelper.getTokens(TokensHelper.java:43)
	at io.quarkus.oidc.client.runtime.AbstractTokensProducer.getTokens(AbstractTokensProducer.java:65)
	at io.quarkus.oidc.client.reactive.filter.runtime.AbstractOidcClientRequestReactiveFilter.filter(AbstractOidcClientRequestReactiveFilter.java:31)
```

### Expected behavior

Calling methods of the annotated REST client should not throw a `DisabledOidcClientException`.

### Actual behavior

The call aborts with a `DisabledOidcClientException`.

### How to Reproduce?

application.properties
```properties
quarkus.rest-client.test.url=http://localhost:8080/dev/null
quarkus.oidc-client.client-enabled=false
quarkus.oidc-client.auth-server-url=changeme
quarkus.oidc-client.client-id=changeme
quarkus.oidc-client.credentials.secret=changeme
quarkus.oidc-client.grant-options.client.resource=changeme
```
RestClient.java
```java
@RegisterRestClient(configKey = "test")
@OidcClientFilter
public interface RestClient {
  @GET
  Response getSomething();
}
```
Call this client's method

### Quarkus version or git rev

3.10.2

**Comment by sberyozkin** [comment]
Reproduced
