### ISSUE TITLE
CodeSource#location always null inside when running in dev mode

### ISSUE THREAD

**Issue by jordanglassman** [quarkusio/quarkus#4088]
**Describe the bug**

When running a Flyway java-based migration programatically, it failed with NPE when running:

```
            ProtectionDomain protectionDomain = aClass.getProtectionDomain();
            CodeSource codeSource = protectionDomain.getCodeSource();
            String url = codeSource.getLocation().getPath();
```

because all fields in CodeSource are null:

![image](https://user-images.githubusercontent.com/1238718/65154997-776a0900-d9fa-11e9-8e45-92552c93aee2.png)

I discovered that this is the case everywhere in the application.  Not sure if this is expected or not, but it is preventing me from using Flyway programmatically.  

Unknown if the problem recurs when using Flyway declaratively per [the guide](https://quarkus.io/guides/flyway-guide).

**Expected behavior**
CodeSource#location to be populated with the URL to the source file.

**Actual behavior**
CodeSource#location is null.

**To Reproduce**
1.  Add a breakpoint anywhere inside a running quarkus app.
2. Run `this.getClass().getProtectionDomain().getCodeSource().getLocation()`

**Configuration**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin ip-192-168-1-137.ec2.internal 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 
```
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit GraalVM EE 19.1.1 (build 25.221-b11-jvmci-19.1-b01, mixed mode)
```
 - Quarkus version or git rev: 0.22.0

**Comment by jordanglassman** [comment]
Update:  verified same error recurs with programmatic Flyway configuration:

```
2019-09-18 10:23:23,992 ERROR [io.qua.dev.DevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:142)
	at io.quarkus.runtime.Application.start(Application.java:91)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:127)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:94)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: java.lang.NullPointerException
	at org.flywaydb.core.internal.util.ClassUtils.getLocationOnDisk(ClassUtils.java:196)
	at org.flywaydb.core.internal.resolver.AbstractJavaMigrationResolver.resolveMigrations(AbstractJavaMigrationResolver.java:77)
	at org.flywaydb.core.internal.resolver.AbstractJavaMigrationResolver.resolveMigrations(AbstractJavaMigrationResolver.java:44)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:136)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:118)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:104)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:46)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:133)
	at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:138)
	at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:126)
	at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
	at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:126)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1476)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:85)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1364)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:26)
	at io.quarkus.deployment.steps.FlywayProcessor$configureRuntimeProperties23.deploy_0(FlywayProcessor$configureRuntimeProperties23.zig:81)
```

using

```
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:sql,classpath:com/my-migration-pacakge
quarkus.flyway.schemas=myschema
quarkus.flyway.baseline-on-migrate=true
```

**Comment by jordanglassman** [comment]
Not able to reproduce with in the test env:  https://github.com/jordanglassman/quarkus/commit/326c32a034f7b864492f6e350f460e25fc83238b

**Comment by jordanglassman** [comment]
Created a trivial reproducer project:  https://github.com/jordanglassman/quarkus-flyway-bug

**Comment by gastaldi** [comment]
@johnaohara I ran your project using the H2 driver and I see the following output:

```bash
➜  quarkus-flyway-bug git:(master) ✗ java -jar target/my-artifactId-my-version-runner.jar
2019-10-11 13:35:05,287 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 5.2.4 by Boxfuse
2019-10-11 13:35:05,461 INFO  [org.fly.cor.int.dat.DatabaseFactory] (main) Database: jdbc:h2:mem:coco (H2 1.4)
2019-10-11 13:35:05,514 WARN  [org.fly.cor.int.sca.cla.ClassPathScanner] (main) Unable to resolve location classpath:sql
2019-10-11 13:35:05,548 INFO  [org.fly.cor.int.com.DbSchemas] (main) Creating schema "TEST_SCHEMA" ...
2019-10-11 13:35:05,552 INFO  [org.fly.cor.int.sch.JdbcTableSchemaHistory] (main) Creating Schema History table: "TEST_SCHEMA"."flyway_schema_history"
2019-10-11 13:35:05,598 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "TEST_SCHEMA": null
2019-10-11 13:35:05,601 INFO  [org.fly.cor.int.com.DbMigrate] (main) Migrating schema "TEST_SCHEMA" to version 1 - Some migration
migrating!
2019-10-11 13:35:05,612 INFO  [org.fly.cor.int.com.DbMigrate] (main) Successfully applied 1 migration to schema "TEST_SCHEMA" (execution time 00:00.029s)
2019-10-11 13:35:05,776 INFO  [io.quarkus] (main) Quarkus 0.22.0 started in 1.010s. Listening on: http://[::]:8080
2019-10-11 13:35:05,778 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, jdbc-h2, narayana-jta, resteasy]
```

Was it supposed to show the NPE you mentioned?

This is my application.properties:

```properties
quarkus.log.console.level=DEBUG

# development environment configuration
quarkus.datasource.url=jdbc:h2:mem:coco;DB_CLOSE_DELAY=-1;DB_CLOSE_DELAY=-1;
quarkus.datasource.driver=org.h2.Driver
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# Flyway minimal config properties
quarkus.flyway.migrate-at-start=true

# Flyway optional config properties
quarkus.flyway.schemas=TEST_SCHEMA
quarkus.flyway.locations=classpath:sql,classpath:org/my/group
quarkus.flyway.baseline-on-migrate=true
```

**Comment by jordanglassman** [comment]
@gastaldi problem seems to be confined to maven!  

Confirmed that I can reproduce when running *from maven only*:

```
[my-artifactId (master)]$ java -jar target/my-artifactId-my-version-runner.jar
2019-10-16 09:50:16,011 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 5.2.4 by Boxfuse
2019-10-16 09:50:16,314 INFO  [org.fly.cor.int.dat.DatabaseFactory] (main) Database: jdbc:h2:mem:coco (H2 1.4)
2019-10-16 09:50:16,426 WARN  [org.fly.cor.int.sca.cla.ClassPathScanner] (main) Unable to resolve location classpath:sql
2019-10-16 09:50:16,478 INFO  [org.fly.cor.int.com.DbSchemas] (main) Creating schema "TEST_SCHEMA" ...
2019-10-16 09:50:16,486 INFO  [org.fly.cor.int.sch.JdbcTableSchemaHistory] (main) Creating Schema History table: "TEST_SCHEMA"."flyway_schema_history"
2019-10-16 09:50:16,582 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "TEST_SCHEMA": null
2019-10-16 09:50:16,583 INFO  [org.fly.cor.int.com.DbMigrate] (main) Migrating schema "TEST_SCHEMA" to version 1 - Some migration
migrating!
2019-10-16 09:50:16,614 INFO  [org.fly.cor.int.com.DbMigrate] (main) Successfully applied 1 migration to schema "TEST_SCHEMA" (execution time 00:00.048s)
2019-10-16 09:50:16,918 INFO  [io.quarkus] (main) Quarkus 0.22.0 started in 1.851s. Listening on: http://[::]:8080
2019-10-16 09:50:16,922 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, jdbc-h2, jdbc-postgresql, narayana-jta, resteasy]
^C2019-10-16 09:50:26,338 INFO  [io.quarkus] (main) Quarkus stopped in 0.017s
```
```
[my-artifactId (master)]$ mvn clean compile quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< my-groupId:my-artifactId >----------------------
[INFO] Building my-artifactId my-version
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ my-artifactId ---
[INFO] Deleting /Users/jglassman/iiworkspace/my-artifactId/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ my-artifactId ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ my-artifactId ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/jglassman/iiworkspace/my-artifactId/target/classes
[INFO]
[INFO] --- quarkus-maven-plugin:0.22.0:dev (default-cli) @ my-artifactId ---
Listening for transport dt_socket at address: 5005
2019-10-16 09:50:49,888 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-10-16 09:50:50,998 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1110ms
2019-10-16 09:50:51,376 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 5.2.4 by Boxfuse
2019-10-16 09:50:51,492 INFO  [org.fly.cor.int.dat.DatabaseFactory] (main) Database: jdbc:h2:mem:coco (H2 1.4)
2019-10-16 09:50:51,548 WARN  [org.fly.cor.int.sca.cla.ClassPathScanner] (main) Unable to resolve location classpath:sql
java.lang.NullPointerException
	at org.flywaydb.core.internal.util.ClassUtils.getLocationOnDisk(ClassUtils.java:196)
	at org.flywaydb.core.internal.resolver.AbstractJavaMigrationResolver.resolveMigrations(AbstractJavaMigrationResolver.java:77)
	at org.flywaydb.core.internal.resolver.AbstractJavaMigrationResolver.resolveMigrations(AbstractJavaMigrationResolver.java:44)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:136)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:118)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:104)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:46)
	at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:109)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1476)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:85)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1364)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:26)
	at io.quarkus.deployment.steps.FlywayProcessor$configureRuntimeProperties16.deploy_0(FlywayProcessor$configureRuntimeProperties16.zig:100)
	at io.quarkus.deployment.steps.FlywayProcessor$configureRuntimeProperties16.deploy(FlywayProcessor$configureRuntimeProperties16.zig:36)
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:82)
	at io.quarkus.runtime.Application.start(Application.java:91)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:127)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:94)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
2019-10-16 09:50:51,615 ERROR [io.qua.dev.DevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:126)
	at io.quarkus.runtime.Application.start(Application.java:91)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:127)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:94)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: java.lang.NullPointerException
	at org.flywaydb.core.internal.util.ClassUtils.getLocationOnDisk(ClassUtils.java:196)
	at org.flywaydb.core.internal.resolver.AbstractJavaMigrationResolver.resolveMigrations(AbstractJavaMigrationResolver.java:77)
	at org.flywaydb.core.internal.resolver.AbstractJavaMigrationResolver.resolveMigrations(AbstractJavaMigrationResolver.java:44)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:136)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:118)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:104)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:46)
	at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:109)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1476)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:85)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1364)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:26)
	at io.quarkus.deployment.steps.FlywayProcessor$configureRuntimeProperties16.deploy_0(FlywayProcessor$configureRuntimeProperties16.zig:100)
	at io.quarkus.deployment.steps.FlywayProcessor$configureRuntimeProperties16.deploy(FlywayProcessor$configureRuntimeProperties16.zig:36)
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:82)
	... 5 more

2019-10-16 09:50:51,616 ERROR [io.qua.dev.DevModeMain] (main) Failed to start Quarkus, attempting to start hot replacement endpoint to recover
```

**Comment by gsmet** [comment]
How to reproduce:
 * get https://github.com/jordanglassman/quarkus-flyway-bug
 * update to 999-SNAPSHOT to be sure you run on master
 * `mvn clean compile quarkus:dev`

There's probably an information missing in our CL or our compiled files.

@anamarija up for some detective work?

**Comment by anamarija** [comment]
ok.

**Comment by gsmet** [comment]
This has been fixed by @anamarija 's PR.
