### ISSUE TITLE
Transaction-Scoped observer on transaction end sometimes fails if the transaction is aborted

### ISSUE THREAD

**Issue by Felk** [quarkusio/quarkus#40882]
### Describe the bug

[The guide on `@TransactionScoped`](https://quarkus.io/guides/transaction#transaction-scope) states:

> ```java
> void onBeforeEndTransaction(@Observes @BeforeDestroyed(TransactionScoped.class) Object event) {
>     // This gets invoked before a transaction ends (commit or rollback).
> }
> ```

This works as expected in most cases, except under these circumstances:

- The bean containing the `onBeforeEndTransaction` is itself `@TransactionScoped`
- The bean containing the `onBeforeEndTransaction` is not interacted with before the `@Observes @BeforeDestroyed(TransactionScoped.class)` event
- The transaction gets aborted

> [!NOTE]
> For holding transaction-specific state during the transaction and executing code at the transaction end, the documentation suggests using `@TransactionScoped` in conjunction with `@PreDestroy`, but due to https://github.com/quarkusio/quarkus/issues/36880 this currently does not work. This is why I opted for a combination of `@TransactionScoped` and `@Observes @BeforeDestroyed(TransactionScoped.class)`

Under those circumstances, at the end of the transaction this error gets logged:
```
2024-05-29 16:25:08,766 ERROR [io.qua.nar.jta.run.NotifyingTransactionManager] (executor-thread-1) Failed to fire @BeforeDestroyed(TransactionScoped.class): java.lang.RuntimeException: Cannot register synchronization
	at io.quarkus.narayana.jta.runtime.context.TransactionContext$TransactionContextState.<init>(TransactionContext.java:209)
	at io.quarkus.narayana.jta.runtime.context.TransactionContext.get(TransactionContext.java:125)
	at io.quarkus.narayana.jta.runtime.context.TransactionContext.get(TransactionContext.java:160)
	at org.acme.GreetingResource_TxEndObserver_Observer_onBeforeEndTransaction_-qkHMozTFpNQ78h2RU2G2LHEEgk.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:329)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
	at io.quarkus.narayana.jta.runtime.TransactionScopedNotifier.beforeDestroyed(TransactionScopedNotifier.java:35)
	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.rollback(NotifyingTransactionManager.java:89)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:404)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:175)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at org.acme.GreetingResource_Subclass.failure(Unknown Source)
	at org.acme.GreetingResource_ClientProxy.failure(Unknown Source)
	at org.acme.GreetingResource$quarkusrestinvoker$failure_96554a4e8df099fb4eb8581c89f3f9663b0027d8.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: jakarta.transaction.RollbackException: ARJUNA016083: Cannot register synchronization because the transaction is in aborted state
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.registerSynchronizationImple(TransactionImple.java:371)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.registerSynchronization(TransactionImple.java:352)
	at io.quarkus.narayana.jta.runtime.context.TransactionContext$TransactionContextState.<init>(TransactionContext.java:207)
	... 32 more
```

The behaviour can be demonstrated with this REST-Controller:
```java
@Path("/hello")
@ApplicationScoped
@Transactional
@Produces(MediaType.TEXT_PLAIN)
public class GreetingResource {
    @Inject
    TxEndObserver txEndObserver;

    @Path("/success")
    @GET
    public String success() {
        return "that worked!";
    }

    @Path("/failure-without-error")
    @GET
    public String success2() {
        txEndObserver.interactWithMe(); // initializes bean
        throw new BadRequestException("that failed as expected!");
    }

    @Path("/failure-with-error")
    @GET
    public String failure() {
        throw new BadRequestException("this causes an ugly ERROR log message");
    }

    @TransactionScoped
    public static class TxEndObserver {
        public void interactWithMe() {}
        void onBeforeEndTransaction(@Observes @BeforeDestroyed(TransactionScoped.class) Object event) {
            Log.info("Transaction is ending");
        }
    }
}
```

The endpoints `/success` and `/failure-without-error` both log `Transaction is ending`, but the endpoint `/failure-with-error` does not, and instead logs the above error.

An easy workaround is to also add a `@Observes @Initialized(TransactionScoped.class)` observer method to the same bean, to ensure it always gets initialized at transaction start:
```java
void onInitializedTransaction(@Observes @Initialized(TransactionScoped.class) Object event) {
    // We don't do anything here, but we need the bean to be initialized before the shutdown event even if it wasn't used during the whole transaction.
    // Otherwise, the @BeforeDestroyed event would try to initialize the bean, which fails with this warning if the transaction was already aborted:
    //     Failed to fire @BeforeDestroyed(TransactionScoped.class): java.lang.RuntimeException: Cannot register synchronization
    //     Caused by: jakarta.transaction.RollbackException: ARJUNA016083: Cannot register synchronization because the transaction is in aborted state
    // The warning is harmless since it's okay that we don't execute anything for aborted transactions, but it's irritating and spams logs.
    Log.tracef("Transaction started: %s", event);
}
```

### Expected behavior

I expect one of two options:
- The above use-case to work without an error
- documentation and/or code safeguards to indicate the use-case as forbidden or to require extra care, e.g. a transaction observer that itself is transaction-scoped having some limitations.

### How to Reproduce?

With the above controller, run these tests to trigger the error:

````java
@QuarkusTest
class GreetingResourceTest {
    @Test
    void testSuccess() {
        given()
                .when().get("/hello/success")
                .then()
                .statusCode(200);
    }

    @Test
    void testFailureWithoutError() {
        given()
                .when().get("/hello/failure-without-error")
                .then()
                .statusCode(400);
    }

    @Test
    void testFailureWithError() {
        given()
                .when().get("/hello/failure-with-error")
                .then()
                .statusCode(400);
    }
}
```

I also attached a reproducer project: TODO

### Output of `uname -a` or `ver`

TODO

### Output of `java -version`

TODO

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

TODO

### Additional information

_No response_

**Comment by dhufnagel** [comment]
Any solution or workaround available for this issue? Unfortunately it spams our logs, so I would be happy if there is a workaround or similar until this is fixed. Thanks!

**Comment by Felk** [comment]
Hey @dhufnagel, have you had any luck with the `onInitializedTransaction(@Observes @Initialized(TransactionScoped.class) Object event)` workaround described above?

**Comment by dhufnagel** [comment]
I did not, as this would always create a TransactionScoped Bean on every Transaction while the use case on my side is only for specific transactions involving file creation. This seems to be an overhead, so i went for the exception way.

**Comment by mmusgrov** [comment]
I provided a proposal for progressing this issue over on the root cause issue ie #36880 - @mkouba what do you think, is a documentation and a warning sufficient for resolving this issue?

**Comment by mkouba** [comment]
> I provided a proposal for progressing this issue over on the root cause issue ie [#36880](https://github.com/quarkusio/quarkus/issues/36880) - [@mkouba](https://github.com/mkouba) what do you think, is a documentation and a warning sufficient for resolving this issue?

But #36880 was not resolved yet, or?

**Comment by mmusgrov** [comment]
> > I provided a proposal for progressing this issue over on the root cause issue ie [#36880](https://github.com/quarkusio/quarkus/issues/36880) - [@mkouba](https://github.com/mkouba) what do you think, is a documentation and a warning sufficient for resolving this issue?
> 
> But [#36880](https://github.com/quarkusio/quarkus/issues/36880) was not resolved yet, or?

The root cause of the current issue is #36880 and I presented a proposal for resolving that one. My last comment here was a question:  "... what do you think, is a documentation and a warning sufficient for resolving this [ie #40882] issue?".
