### ISSUE TITLE
CIRCULAR REFERENCE: io.quarkus.runtime.configuration.ConfigurationException: 'quarkus.oidc.client.auth-server-url' property must be configured

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#40899]
### Describe the bug

After upgrading Quarkus from 3.10.2 to 3.11.0 we get the following exception:

```
java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
        [Exception 0] io.quarkus.runtime.configuration.ConfigurationException: 'quarkus.oidc.client.auth-server-url' property must be configured
        [Exception 1] io.quarkus.oidc.OIDCException
        at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap$UniOnFailureFlatMapProcessor.performInnerSubscription(UniOnFailureFlatMap.java:94)
        at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap$UniOnFailureFlatMapProcessor.dispatch(UniOnFailureFlatMap.java:83)
        at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap$UniOnFailureFlatMapProcessor.onFailure(UniOnFailureFlatMap.java:60)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownFailure$KnownFailureSubscription.forward(UniCreateFromKnownFailure.java:38)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownFailure.subscribe(UniCreateFromKnownFailure.java:23)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:60)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
        at io.quarkus.oidc.runtime.OidcRecorder.createStaticTenantContext(OidcRecorder.java:166)
        at io.quarkus.oidc.runtime.OidcRecorder.setup(OidcRecorder.java:95)
        at io.quarkus.deployment.steps.OidcBuildStep$setup1008959783.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.OidcBuildStep$setup1008959783.deploy(Unknown Source)
        ... 11 more
        Suppressed: io.quarkus.oidc.OIDCException
                at io.quarkus.oidc.runtime.OidcRecorder$5.apply(OidcRecorder.java:163)
                at io.quarkus.oidc.runtime.OidcRecorder$5.apply(OidcRecorder.java:145)
                at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
                at io.smallrye.mutiny.groups.UniOnFailure.lambda$recoverWithItem$8(UniOnFailure.java:190)
                at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap$UniOnFailureFlatMapProcessor.performInnerSubscription(UniOnFailureFlatMap.java:92)
                ... 24 more
        Caused by: io.quarkus.runtime.configuration.ConfigurationException: 'quarkus.oidc.client.auth-server-url' property must be configured
                at io.quarkus.oidc.runtime.OidcRecorder.createTenantContext(OidcRecorder.java:219)
                at io.quarkus.oidc.runtime.OidcRecorder.createStaticTenantContext(OidcRecorder.java:143)
                ... 14 more
Caused by: [CIRCULAR REFERENCE: io.quarkus.runtime.configuration.ConfigurationException: 'quarkus.oidc.client.auth-server-url' property must be configured]

```

### How to Reproduce?

Not yet.

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus 3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.7

**Comment by gsmet** [comment]
I think we will need a bit more information about your setup :).

Ideally a reproducer would really help.

**Comment by mschorsch** [comment]
I have found it. In our CI environment we had not set the environment variable `QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL`. For some reason it worked in Quarkus 3.10.2 but not in Quarkus 3.11.0. 

@gsmet Sorry for the noise.
