### ISSUE TITLE
Why Quarkus-JsonB is using ArC?

### ISSUE THREAD

**Issue by FreifeldRoyi** [quarkusio/quarkus#4090]
As I was writing a unit test (not `@QuarkusTest`) for a class that uses `Jsonb.fromJson(String,Class)`, I got a NullPointerException on an adapted type field:

```
    @NotNull
    @JsonbProperty("instant")
    @JsonbTypeAdapter(EpochSecondsAdapter.class)
    private Instant instant;  //UTC epoch second Long
```

I'm not sure that the adapted field is actually what causing the problem but It failed on that particular field so I'm writing it down. The way I solved it is by using `Arc.initialize()` as a `BeforeAll` step in the test and `Arc.shutdown()` as a `AfterAll` step.

Why is JsonB using ArC, and is initializing ArC a good practice or I can do something else to make the test pass?

**Comment by gsmet** [comment]
On Wed, Sep 18, 2019 at 4:59 PM Royi Freifeld <notifications@github.com>
wrote:

> As I was writing a unit test (not @QuarkusTest) for a class that uses
> Jsonb.fromJson(String,Class), I got a NullPointerException on an adapted
> type field
>

Any chance we could have the stacktrace?

**Comment by FreifeldRoyi** [comment]
```
Sep 19, 2019 9:20:51 AM org.eclipse.yasson.internal.Unmarshaller deserializeItem
SEVERE: null


javax.json.bind.JsonbException: Internal error: null

	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:76)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:56)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:53)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:60)
	at <My code stack here>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at io.quarkus.jsonb.QuarkusJsonbComponentInstanceCreator.lambda$getOrCreateComponent$0(QuarkusJsonbComponentInstanceCreator.java:37)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.quarkus.jsonb.QuarkusJsonbComponentInstanceCreator.getOrCreateComponent(QuarkusJsonbComponentInstanceCreator.java:36)
	at org.eclipse.yasson.internal.ComponentMatcher.introspectAdapterBinding(ComponentMatcher.java:254)
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBindingFromAnnotation(AnnotationIntrospector.java:232)
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBinding(AnnotationIntrospector.java:211)
	at org.eclipse.yasson.internal.model.PropertyModel.getUserAdapterBinding(PropertyModel.java:151)
	at org.eclipse.yasson.internal.model.PropertyModel.introspectCustomization(PropertyModel.java:205)
	at org.eclipse.yasson.internal.model.PropertyModel.<init>(PropertyModel.java:98)
	at org.eclipse.yasson.internal.ClassParser.lambda$parseProperties$0(ClassParser.java:75)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.eclipse.yasson.internal.ClassParser.parseProperties(ClassParser.java:76)
	at org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:57)
	at org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:38)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:108)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:66)
	... 69 more
```

**Comment by geoand** [comment]
@FreifeldRoyi Interesting!

Would you be able to provide a small reproducer so I can look into it and get back to you with more information?

**Comment by FreifeldRoyi** [comment]
```
// src/main/java/test
package test;

import javax.json.bind.adapter.JsonbAdapter;
import javax.json.bind.annotation.JsonbProperty;
import javax.json.bind.annotation.JsonbTypeAdapter;
import java.time.Instant;

public class Bean {

    @JsonbProperty("time")
    @JsonbTypeAdapter(EpochSecondsAdapter.class)
    private Instant time;

    public Bean() {
    }

    public Instant getTime() {
        return time;
    }

    public void setTime(Instant time) {
        this.time = time;
    }

    public static class EpochSecondsAdapter implements JsonbAdapter<Instant, Long> {
        @Override
        public Long adaptToJson(Instant obj) {
            return obj.getEpochSecond();
        }

        @Override
        public Instant adaptFromJson(Long obj) {
            return Instant.ofEpochSecond(obj);
        }
    }
}
```

```
// src/main/java/test
package test;

import javax.json.bind.Jsonb;
import javax.json.bind.JsonbBuilder;

public class BeanProcessor {

    private final Jsonb JSONB = JsonbBuilder.create();

    public Bean process(String str) {
        return JSONB.fromJson(str, Bean.class);
    }
}
```

```
// src/test/java/test
package test;

import org.junit.jupiter.api.*;

import java.time.Instant;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class BeanProcessorTest {

    private BeanProcessor cut;

    @BeforeAll
    public void setup() {
        // Arc.initialize();
        this.cut = new BeanProcessor();
    }

    @AfterAll
    public void tearDown() {
//        Arc.shutdown();
    }

    @Test
    public void test() {
        String str = "{\"time\":1570039000}";
        Bean process = this.cut.process(str);

        Assertions.assertEquals(Instant.ofEpochSecond(1570039000), process.getTime());
    }

}
```

When the `Arc.initialize()` & `Arc.shutdown()` is not called, I get the NPE I mentioned. Once I remove the comment, everything works.

It's the `QuarkusJsonbComponentInstanceCreator.getOrCreateComponent()` that calls `Arc.container()` which is not initialized

**Comment by geoand** [comment]
@FreifeldRoyi would it possible for you to provide a minimum complete example that exhibits the behavior?
It would also be great to mention what command you are using to launch the test.

**Comment by FreifeldRoyi** [comment]
> @FreifeldRoyi would it possible for you to provide a minimum complete example that exhibits the behavior?
You mean like a zip with all the files?

**Comment by geoand** [comment]
@FreifeldRoyi either that or some project hosted on Github. Whatever you prefer

**Comment by FreifeldRoyi** [comment]
[jsonb-test-fail.zip](https://github.com/quarkusio/quarkus/files/3743456/jsonb-test-fail.zip)

Sorry for the delay

**Comment by geoand** [comment]
Thanks @FreifeldRoyi, I'll take a look

**Comment by geoand** [comment]
#4658 should take care of it

**Comment by FreifeldRoyi** [comment]
You're fast =)
Thank you

**Comment by geoand** [comment]
You are welcome :)
