### ISSUE TITLE
Getting io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype intermitently

### ISSUE THREAD

**Issue by sambhav-khare** [quarkusio/quarkus#40912]
### Describe the bug

I got the exception `io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype` randomly while testing the app in dev mode, I am not sure if the behavior is same in prod. It happens during redis read/write mostly.

```
java.util.concurrent.ExecutionException: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.app.kafka.KafkaMessageConsumer.consume(KafkaMessageConsumer.java:63)
	at com.app.kafka.KafkaMessageConsumer_ClientProxy.consume(Unknown Source)
	at com.app.kafka.KafkaMessageConsumer_SmallRyeMessagingInvoker_consume_514addf985870c678ccf9388685c24a19426e522.invoke(Unknown Source)
	at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeBlocking$15(AbstractMediator.java:190)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:36)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
	at io.vertx.mutiny.core.Context$1.handle(Context.java:171)
	at io.vertx.mutiny.core.Context$1.handle(Context.java:169)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:102)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:78)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:66)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
	at io.smallrye.context.impl.DefaultValues.<init>(DefaultValues.java:41)
	at io.smallrye.context.SmallRyeContextManager.<init>(SmallRyeContextManager.java:63)
	at io.smallrye.context.SmallRyeContextManager$Builder.build(SmallRyeContextManager.java:337)
	at io.smallrye.context.SmallRyeContextManagerProvider.getContextManager(SmallRyeContextManagerProvider.java:48)
	at io.smallrye.context.SmallRyeContextManagerProvider.getContextManager(SmallRyeContextManagerProvider.java:37)
	at io.smallrye.context.SmallRyeContextManagerProvider.getManager(SmallRyeContextManagerProvider.java:97)
	at io.smallrye.context.SmallRyeThreadContext.getCurrentThreadContextOrDefaultContexts(SmallRyeThreadContext.java:160)
	at io.smallrye.mutiny.context.DefaultContextPropagationInterceptor.getThreadContext(DefaultContextPropagationInterceptor.java:12)
	at io.smallrye.mutiny.context.BaseContextPropagationInterceptor.decorate(BaseContextPropagationInterceptor.java:33)
	at io.smallrye.mutiny.infrastructure.Infrastructure.decorate(Infrastructure.java:152)
	at io.smallrye.mutiny.vertx.AsyncResultUni.<init>(AsyncResultUni.java:21)
	at io.smallrye.mutiny.vertx.AsyncResultUni.toUni(AsyncResultUni.java:17)
	at io.vertx.mutiny.redis.client.Redis.send(Redis.java:152)
	at io.quarkus.redis.runtime.datasource.ReactiveRedisDataSourceImpl.execute(ReactiveRedisDataSourceImpl.java:77)
	at io.quarkus.redis.runtime.datasource.AbstractRedisCommands.execute(AbstractRedisCommands.java:20)
	at io.quarkus.redis.runtime.datasource.AbstractStringCommands._get(AbstractStringCommands.java:153)
	at io.quarkus.redis.runtime.datasource.ReactiveStringCommandsImpl.get(ReactiveStringCommandsImpl.java:109)
	at com.app.redis.RedisClient.getConfig(RedisClient.java:52)
	at com.app.redis.RedisClient_ClientProxy.getConfig(Unknown Source)
	at com.app.service.ConfigService.populateConfig(ConfigService.java:44)
	at com.app.service.ConfigService_ClientProxy.populateConfig(Unknown Source)
	at com.app.kafka.KafkaMessageConsumer.processMessage(KafkaMessageConsumer.java:86)
	at com.app.kafka.KafkaMessageConsumer.lambda$consume$0(KafkaMessageConsumer.java:61)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

### Expected behavior

It should not throw any exception during redis read/write.

### Actual behavior

Exception `io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype` is being thrown randomly

### How to Reproduce?

Since it is happening randomly, I don't have specific steps to reproduce it.

### Output of `uname -a` or `ver`

Darwin Kernel Version 23.5.0

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16

### Quarkus version or git rev

3.9.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

**Comment by radcortez** [comment]
Usually, this means that there is some issue with the CL. Is there any chance you can provide us with a reproducer? Or at least the code in `com.app.service.ConfigService.populateConfig(ConfigService.java)`. Thanks!

**Comment by geoand** [comment]
Closing for the lack of a reproducer. If one becomes available, please attach it and we can have another look at the issue.
