### ISSUE TITLE
Extension using Gradle and Kotlin

### ISSUE THREAD

**Issue by cthiebault** [quarkusio/quarkus#40961]
### Describe the bug

I'm trying to create a very simple Quarkus Extension using Gradle and Kotlin.

The extension is basic and just offer a CDI bean.
```kotlin
class ExtensionProcessor {
  @BuildStep
  fun feature(): FeatureBuildItem {
    return FeatureBuildItem(FEATURE)
  }

  @BuildStep
  fun registerBeans(): AdditionalBeanBuildItem {
    return AdditionalBeanBuildItem.builder()
      .addBeanClass(ExampleService::class.java)
      .build()
  }

  companion object {
    private const val FEATURE = "example-extension"
  }
}
```

Building the project, I get a 
```
jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.example.ExampleService and qualifiers [@Default]
      	- injection target: parameter 'exampleService' of com.example.application.ExampleResource constructor
      	- declared on CLASS bean [types=[com.example.application.ExampleResource, java.lang.Object], qualifiers=[@Default, @Any], target=com.example.application.ExampleResource]
```

It works when I use Gradle + Java but not with Gradle + Kotlin. 

### How to Reproduce?

I've created a sample repo to reproduce the error:
https://github.com/cthiebault/quarkus-gradle-kotlin-extension

- branch [maven-java](https://github.com/cthiebault/quarkus-gradle-kotlin-extension) (Maven + Java) builds fine
  ```shell
  git checkout maven
  ./mvnw clean package 
  ```
- branch [gradle-java](https://github.com/cthiebault/quarkus-gradle-kotlin-extension/tree/gradle-java) (Gradle + Java) builds fine
  ```shell
  git checkout gradle
  ./gradlew build 
  ```
- branch [gradle-kotlin](https://github.com/cthiebault/quarkus-gradle-kotlin-extension/tree/gradle-kotlin) 
  (Gradle + Kotlin) fails with the following error:
  ```shell
  git checkout gradle-kotlin
  ./gradlew build
  
  > There was a failure while executing work items
    > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.example.ExampleService and qualifiers [@Default]
        	- injection target: parameter 'exampleService' of com.example.application.ExampleResource constructor
        	- declared on CLASS bean [types=[com.example.application.ExampleResource, java.lang.Object], qualifiers=[@Default, @Any], target=com.example.application.ExampleResource]
        	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1529)
        	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:332)
        	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:166)
        	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:488)
        	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        	at java.base/java.lang.Thread.run(Thread.java:1583)
        	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
        Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.example.ExampleService and qualifiers [@Default]
        	- injection target: parameter 'exampleService' of com.example.application.ExampleResource constructor
        	- declared on CLASS bean [types=[com.example.application.ExampleResource, java.lang.Object], qualifiers=[@Default, @Any], target=com.example.application.ExampleResource]
        	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
        	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:642)
        	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:317)
        	... 12 more
    ```

### Output of `java -version`

21.0.2

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

**Comment by mschorsch** [comment]
@cthiebault We use Gradle + Kotlin for our applications, but we use Maven + Kotlin for our extensions. This combination has worked well for us.

You can find an example in the quarkverse: https://github.com/quarkiverse/quarkus-mockk

@geoand The Quarkus documentation explicitly mentions Gradle extensions as supported (https://quarkus.io/guides/writing-extensions#using-gradle), so this seems a valid issue.

**Comment by mschorsch** [comment]
@cthiebault If you want I can provide a template for an extension with Maven + Kotlin.

**Comment by geoand** [comment]
@mschorsch right, that combination is totally untested AFAIk

**Comment by aloubyansky** [comment]
@mschorsch i think it'd be great

**Comment by mschorsch** [comment]
Here is an example of a Quarkus extension with Maven+Kotlin based on the standard example “Greeting extensions”: 
[quarkus-extension-kotlin-maven-skeleton.zip](https://github.com/user-attachments/files/15748252/quarkus-extension-kotlin-maven-skeleton.zip)

Hope this helps.

**Comment by cthiebault** [comment]
Thanks your help :)

I'm working on an AWS Rest Lambda application using Gradle+Kotlin.
As we cannot mix `quarkus-amazon-lambda-rest` with other non-REST lambda (like SQS), I'm splitting my application into 2 differents Quarkus applications with the common code as an extension:
- `app-lambda-rest`
- `app-lambda` (for non-REST lambdas)
- `common-runtime`
- `common-deployment`

I was hoping to be able to use a single Gradle project with 4 sub-projects... 
Using Maven for the extension and Gradle for the apps will complexify things.
I may switch to Maven for this project. I'll have a look to your skeleton! Thanks again!
