### ISSUE TITLE
ClassCastException when streaming with MQTT messaging

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#41047]
### Describe the bug

I have a service which emits into a channel and streams out of this channel on the other side. I use `quarkus-messaging-mqtt` for this.

```java
@ApplicationScoped
public class ProductService {

    @Channel("products-out")
    Emitter<Product> emitter;

    @Channel("products-in")
    Multi<Product> products;

    public Multi<Product> stream() {
        return products;
    }

    public void produce() {
        emitter.send(new Product(UUID.randomUUID().toString(), "Product Test"));
    }
}
```

I have implemented a test for this.

The following test works:

```java
@Test
public void working() {
    AssertSubscriber<Product> subscriber = productService.stream()
            .subscribe()
            .withSubscriber(AssertSubscriber.create());

    productService.produce();

    subscriber.awaitNextItem();

    var products = subscriber.getItems();
    Assertions.assertEquals(1, products.size());
}
```

And this test fails with a ClassCastException:

```java
@Test
public void notWorking() {
    AssertSubscriber<Product> subscriber = productService.stream()
            .subscribe()
            .withSubscriber(AssertSubscriber.create());

    productService.produce();

    subscriber.awaitNextItem();

    var products = subscriber.getItems();
    Assertions.assertEquals(1, products.size());

    var product = products.getFirst();
    Assertions.assertEquals("Product Test", product.name());
}
```

```
class [B cannot be cast to class io.i15s.quarkus.Product ([B is in module java.base of loader 'bootstrap'; io.i15s.quarkus.Product is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @7a81065e)
java.lang.ClassCastException: class [B cannot be cast to class io.i15s.quarkus.Product ([B is in module java.base of loader 'bootstrap'; io.i15s.quarkus.Product is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @7a81065e)
	at io.i15s.quarkus.ProductServiceTest.notWorking(ProductServiceTest.java:42)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1017)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:831)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

The only difference in the test are the last two lines.

### How to Reproduce?

I created the above example as a reproducer project.
https://github.com/andlinger/quarkus-reproducer/tree/quarkus-41047

### Output of `uname -a` or `ver`
```
 Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031 arm64
```
### Output of `java -version`
```
openjdk version "22" 2024-03-19
OpenJDK Runtime Environment GraalVM CE 22+36.1 (build 22+36-jvmci-b02)
OpenJDK 64-Bit Server VM GraalVM CE 22+36.1 (build 22+36-jvmci-b02, mixed mode, sharing)
```
### Quarkus version or git rev

3.11.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
------------------------------------------------------------
Gradle 8.6
------------------------------------------------------------

Build time:   2024-02-02 16:47:16 UTC
Revision:     d55c486870a0dc6f6278f53d21381396d0741c6e

Kotlin:       1.9.20
Groovy:       3.0.17
```

**Comment by ozangunalp** [comment]
Yes, the MQTT connector only supports consuming `JsonObject` and `byte[]`.

**Comment by cescoffier** [comment]
Closing - if you need this feature. Please open a feature request on https://github.com/smallrye/smallrye-reactive-messaging.

This is documented in https://smallrye.io/smallrye-reactive-messaging/latest/mqtt/receiving-mqtt-messages/#deserialization.
