### ISSUE TITLE
Broken error message shown  when quarkus application failes to start due to occupied port

### ISSUE THREAD

**Issue by thomasdarimont** [quarkusio/quarkus#41057]
### Describe the bug

Broken error message shown  when quarkus application failes to start due to occupied port, due to invalid format string / log message parameterization.

### Expected behavior

A proper error message should be printed instead of the exception.

### Actual behavior

```
2024-06-07 15:05:10,646 ERROR [io.qua.run.Application] (Quarkus Main Thread) Port 8080 seems to be in use by another process. Quarkus may already be running or the port is used by another application.

java.util.logging.ErrorManager: 1: Nested handler publication threw an exception
java.util.MissingFormatArgumentException: Format specifier '%d'
        at java.base/java.util.Formatter.format(Formatter.java:2790)
        at java.base/java.util.Formatter.format(Formatter.java:2728)
        at java.base/java.lang.String.format(String.java:4390)
        at org.jboss.logmanager.ExtLogRecord.getFormattedMessage(ExtLogRecord.java:512)
        at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:132)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:438)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:1089)
        at org.jboss.logmanager.Logger.log(Logger.java:1052)
        at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:56)
        at org.jboss.logging.Logger.warnf(Logger.java:1407)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:186)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
        at java.base/java.lang.Thread.run(Thread.java:1583)
2024-06-07 15:05:10,656 WARN  [io.qua.run.Application] (Quarkus Main Thread) You can try to kill it with 'kill -9 <pid>'.
```

### How to Reproduce?

See: https://gist.github.com/thomasdarimont/354e9fe7dca488fd3e0888547a006caf

Run with `mvn quarkus:dev`

### Output of `uname -a` or `ver`

Linux neumann 6.8.9-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May  2 18:50:49 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.11" 2024-04-16

### Quarkus version or git rev

3.11.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.7

**Comment by thomasdarimont** [comment]
Duplicate issue that's already fixed in https://github.com/quarkusio/quarkus/pull/41036
