### ISSUE TITLE
Initialization Tasks failing

### ISSUE THREAD

**Issue by frootshoot** [quarkusio/quarkus#41113]
### Describe the bug

We have been using Liquibase with Kubernetes where in our own helm charts we are configuring a job to run with "QUARKUS_INIT_AND_EXIT" to execute the schema migration.

This was working up to version 3.8.x, and now fails with newer versions due to a NullPointerException on startup - this stops the deployment progressing.

```
2024-06-11 11:57:55,590 ERROR [io.qua.run.shu.ShutdownRecorder] (Quarkus Main Thread) Graceful shutdown failed: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "io.quarkus.runtime.shutdown.ShutdownRecorder.shutdownListeners" is null
	at io.quarkus.runtime.shutdown.ShutdownRecorder.executePreShutdown(ShutdownRecorder.java:42)
	at io.quarkus.runtime.shutdown.ShutdownRecorder.runShutdown(ShutdownRecorder.java:33)
	at io.quarkus.runtime.Application.stop(Application.java:207)
	at io.quarkus.runtime.Application.stop(Application.java:155)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:211)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
```

Following an investigation, it appears that the graceful shutdown code was refactored after 3.8.x which removed the null check for shutdown listeners - however it appears any shutdown listeners are not actually injected until after the point when "init and exit" has finished, leading to the NPE.

### Expected behavior

The Quarkus container should run the Liquibase migration and then exit cleanly.

### Actual behavior

The Liquibase migration happens as expected but the contianer does not shutdown without the error - stopping the appplication containers from starting.

### How to Reproduce?

Running any Quarkus application with environment variable "QUARKUS_INIT_AND_EXIT" set to true.

### Quarkus version or git rev

3.11.1

**Comment by geoand** [comment]
Thanks for reporting!

As you've already investigated this, would you like to contribute a fix?

**Comment by frootshoot** [comment]
I am not sure of the intention of the refactor, as it clearly removed the null check - i.e. if the shutdown listeners are supposed to be injected by this point?

**Comment by geoand** [comment]
What likely happened is that when things were refactored, this use case was not taken into account

**Comment by frootshoot** [comment]
> As you've already investigated this, would you like to contribute a fix?

I am currently not in a position to contribute code, but happy to help where I can with this.
