### ISSUE TITLE
Integration tests against AWS deployed services

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#41167]
### Describe the bug

Hello,
I'm deploying an AWS stack exposing a REST API behind an API Gateway and, in addition to `testcontainers` based unit tests, I want to perform integration tests against the real services.

The Quarkus documentation mentions:

> @QuarkusIntegrationTest supports executing tests against an already running instance of the application. This can be achieved by setting the quarkus.http.test-host system property when running the tests.

So, I'm running my integration tests as follows:

    $ mvn ... -Dquarkus.http.test-host=$API_ENDPOINT failsafe:integration-test

where `API_ENDPOINT` is something like `https://...lambda-url.eu-west-3.on.aws/`. 

### Expected behavior

I expect that the test connects to the API endpoint and runs as expected, as when running locally with `localstack` and `testcontainers`.

### Actual behavior

The following exception is raised:

    [ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 8.775 s <<< FAILURE! -- in fr.simplex_software.aws.iac.quarkus.s3.tests.S3FileManagementIT
    [ERROR] fr.simplex_software.aws.iac.quarkus.s3.tests.S3FileManagementIT.testUploadFile -- Time elapsed: 0.487 s <<< ERROR!
    java.net.MalformedURLException: Error at index 0 in: ":8081"
        at java.base/java.net.URL.<init>(URL.java:806)
        at java.base/java.net.URL.<init>(URL.java:654)
        at java.base/java.net.URL.<init>(URL.java:590)
    ...

What seems to happen is that the TCP port #8081, which is the default for tests, is appended to the `quarkus.http.test-host` value and, of course, such a host doesn't exist. In order to define the port number the property `quarkus.http.test-port` should be used but there is no such a thing like a TCP port in an AWS endpoint.

The other thing is that `testcontainers` and `localstack` seem to be still started, as shown below, even if this doesn't make sense, 'cause I want to test against the real services, not against the mocked ones. 

    [INFO] -------------------------------------------------------
    [INFO]  T E S T S
    [INFO] -------------------------------------------------------
    [INFO] Running fr.simplex_software.aws.iac.quarkus.s3.tests.S3FileManagementIT
    2024-06-12 16:31:36,353 INFO  [io.qua.ama.lam.run.MockEventServer] (build-12) Mock Lambda Event Server Started
    2024-06-12 16:31:36,888 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-12) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
    2024-06-12 16:31:37,059 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-12) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
    2024-06-12 16:31:37,060 INFO  [org.tes.DockerClientFactory] (build-12) Docker host IP address is localhost
    2024-06-12 16:31:37,072 INFO  [org.tes.DockerClientFactory] (build-12) Connected to docker: 
      Server Version: 26.1.3
      API Version: 1.45
      Operating System: Ubuntu 22.04.4 LTS
      Total Memory: 31730 MB
    2024-06-12 16:31:37,080 INFO  [org.tes.ima.PullPolicy] (build-12) Image pull policy will be performed by: DefaultPullPolicy()
    2024-06-12 16:31:37,081 INFO  [org.tes.uti.ImageNameSubstitutor] (build-12) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
    2024-06-12 16:31:37,084 INFO  [org.tes.DockerClientFactory] (build-12) Checking the system...
    2024-06-12 16:31:37,084 INFO  [org.tes.DockerClientFactory] (build-12) ✔︎ Docker server version should be at least 1.6.0
    2024-06-12 16:31:37,150 INFO  [tc.loc.0.1] (build-12) LOCALSTACK_HOST environment variable set to localstack-kjhyz (to match last network alias on container with non-default network)
    2024-06-12 16:31:37,151 INFO  [tc.tes.7.0] (build-12) Creating container for image: testcontainers/ryuk:0.7.0
    2024-06-12 16:31:37,153 INFO  [org.tes.uti.RegistryAuthLocator] (build-12) Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.7.0, configFile: /home/nicolas/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Status 404: No config supplied. Checked in order: /home/nicolas/.docker/config.json (file not found), DOCKER_AUTH_CONFIG (not set)
    2024-06-12 16:31:37,255 INFO  [tc.tes.7.0] (build-12) Container testcontainers/ryuk:0.7.0 is starting: cd41e812ba8b83b3c563fba85994382305f537de651e5555a074093979b82d54
    2024-06-12 16:31:37,602 INFO  [tc.tes.7.0] (build-12) Container testcontainers/ryuk:0.7.0 started in PT0.451637302S
    2024-06-12 16:31:37,606 INFO  [tc.loc.0.1] (build-12) Creating container for image: localstack/localstack:3.0.1
    2024-06-12 16:31:38,323 INFO  [tc.loc.0.1] (build-12) Container localstack/localstack:3.0.1 is starting: caba480d4d6a764b7a011b92fdafc28213decda4e58927ec3127fe1b6e68f95b
    2024-06-12 16:31:40,827 INFO  [tc.loc.0.1] (build-12) Container localstack/localstack:3.0.1 started in PT3.220766362S
    2024-06-12 16:31:43,028 INFO  [io.qua.ama.com.dep.DevServicesLocalStackProcessor] (build-12) Amazon Dev Services for localstack (s3) started. Other Quarkus applications in dev mode will find the LocalStack automatically.

### How to Reproduce?

Don't have a reproducer

### Output of `uname -a` or `ver`

Linux nicolas-XPS-15-9570 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "21.0.3" 2024-04-16 LTS Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152) Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /opt/apache-maven-3.9.5 Java version: 21.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-21-oracle-x64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-112-generic", arch: "amd64", family: "unix"

### Additional information

None

**Comment by nicolasduminil** [comment]
I've prepared a reproducer to illustrate the case. Finally, I decided not to use anymore `@QuarkusIntegrationTest` and to replace it by `@QuarkusTest`, base on some recommendations that I've seen somewhere in the documentation.

So, to reproduce:

    $ git clone https://github.com/nicolasduminil/quarkus-s3.git
    $ cd quarkus-s3
    $ ./deploy.sh

This will build a CDK app having a stack with a lambda function exposing a REST API. The stack will be deployed on AWS (aws account and aws cli valid instal required) and then the integration test will be run. This is a simple test whose code is shown below:

    @QuarkusTest
    public class HostResourceIT
    {
      @Inject
      @RestClient
      HostResourceClient hostResourceClient;
      @Inject
      @ConfigProperty(name = "base_uri/mp-rest/url")
      String baseURI;

      @Test
      public void testHostResource() throws IOException
      {
        assertThat(hostResourceClient.host()).contains("*** My IP address is");
      }
    }

It is run as follows:

    mvn -Dbase_uri/mp-rest/url=$API_ENDPOINT failsafe:integration-test

where `API_ENDPOINT` is the lambda function URL, something like: `https://<GENERATED>.lambda-url.eu-west-3.on.aws/`. 

Hence, I expect that the test send a GET request to this endpoint but, instead, it starts the local mock lambda server, which listens on `http://localhost:8081/_lambda_/2018-06-01/runtime/invocation/next`. here is the log file:

    [INFO] -------------------------------------------------------
    [INFO]  T E S T S
    [INFO] -------------------------------------------------------
    [INFO] Running fr.simplex_software.aws.iac.tests.HostResourceIT
    Jun 16, 2024 6:19:12 PM org.jboss.logmanager.JBossLoggerFinder getLogger
    ERROR: The LogManager accessed before the "java.util.logging.manager" system property was set to "org.jboss.logmanager.LogManager". Results may be unexpected.
    Jun 16, 2024 6:19:15 PM io.quarkus.amazon.lambda.runtime.MockEventServer start
    INFO: Mock Lambda Event Server Started
    Jun 16, 2024 6:19:16 PM io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1 run
    INFO: Listening on: http://localhost:8081/_lambda_/2018-06-01/runtime/invocation/next
    Jun 16, 2024 6:19:16 PM io.quarkus.bootstrap.runner.Timing printStartupTime
    INFO: quarkus-s3 0.1 on JVM (powered by Quarkus 3.11.0) started in 1.744s. 
    Jun 16, 2024 6:19:16 PM io.quarkus.bootstrap.runner.Timing printStartupTime
    INFO: Profile test activated. 
    Jun 16, 2024 6:19:16 PM io.quarkus.bootstrap.runner.Timing printStartupTime
    INFO: Installed features: [amazon-lambda, cdi, rest-client, security, smallrye-context-propagation, vertx]
    [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.452 s <<< FAILURE! - in fr.simplex_software.aws.iac.tests.HostResourceIT
    [ERROR] fr.simplex_software.aws.iac.tests.HostResourceIT.testHostResource  Time elapsed: 6.732 s  <<< ERROR!
    org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Not Found, status code 404' when invoking: Rest   Client method: 'fr.simplex_software.aws.iac.api.HostResourceClient#host'
        at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.unwrapException(RestClientRequestContext.java:195)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.handleException(AbstractResteasyReactiveContext.java:329)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:175)
        at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
        at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:38)
        at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:35)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:261)
        at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:59)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
    Caused by: jakarta.ws.rs.WebApplicationException: Not Found, status code 404
        at fr.simplex_software.aws.iac.tests.HostResourceIT.testHostResource(HostResourceIT.java:27)
 
So, what I want to do here is not to start any mock server to listen on localhost but simply test against the AWS deployed service. How can I do that ?

**Comment by hamburml** [comment]
Hm... interesting idea but I think the current architecture of the lambda dependencies will not allow this.

Afaik `@QuarkusTest` will always, when a lambda dependency is found, run the mock event server. There is no other way to run a lambda in a non-aws environment (its more a fake lambda...). This was added here https://github.com/quarkusio/quarkus/pull/35412 What you can do is set `quarkus.lambda.mock-event-server.enabled=false`. But now your QuarkusTest should not start anymore.

But what you really need is a Quarkus-Application which sends requests against the Lambda deployed in AWS. The response is then evaluated and if correct, the test is successful.

Maybe you could use maven profiles for that...

```
<profiles>
    <profile>
        <id>withLambdaDependency</id>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-amazon-lambda-http</artifactId>
              </dependency>
        </dependencies>
    </profile>
    <profile>
        <id>forTest</id>
    </profile>
</profiles>
```

This would also mean that you need to remove quarkus-amazon-lambda-http from your dependencies section because it will now be added by the profile. When cdk builds your app the withLambdaDependency profile must be active (for example via `mvn package -P withLambdaDependency`) so that the dependency is added.

When the tests runs locally it should activate the forTest profile (of course the profile is empty, so you could omit it). So the quarkus-applications runs normally (there is no amazon-lambda dependency and also no mock server) and should send requests against your public aws api gateway.

I hope this makes sense?

**Comment by nicolasduminil** [comment]
@hamburml : 

> Intersting idea ...

I'm pleased that you find interesting this idea but it isn't really an "idea" but the most basic functionality that one might expect: being able to test against a full-scale service, not a local mock.

> There is no other way to run a lambda in a non-aws environment (its more a fake lambda...)

I'm afraid that I didn't make myself clear. I'm not talking about a non-aws environment, neither about fake-lambda. I'm talking about testing in a genuine AWS environment, with real lambda functions.

> But now your QuarkusTest should not start anymore.

That's not good as I need it to start, otherwise I wouldn't have written it. :-)

> But what you really need is a Quarkus-Application which sends requests against the Lambda deployed in AWS.

Well, what I need is an Junit based test. Of course, a standalone application could do it as well but this is what I would have done 20 years ago, when JUnit didn't exist. Or did it exist even then ?

> Maybe you could use maven profiles for that...

I could, of course, but I couldn't have a separate profile each time I need to exclude a dependency. I tried to configure the `maven-failsafe-plugin` such that to exclude `quarkus-amazon-lambda-http` during tests but, despite that, the local mock server, together with `testcontainers` and `localstack` are still started. Which allows me to say that, even if  `quarkus-amazon-lambda-http` isn't among the dependencies, as this is the case when excluding it in the plugin config, you're still not able to test against the full scale service.

So, I'm quite surprised that it doesn't seem possible to write integration tests that connect to the full-scale services since I'm doing that, since decades, with all the other frameworks like Jakarta EE, Spring, Helidon, Micronaut, etc. But I'm left edified now and I thank you for your help and support. Closing the issue since there is no solution.

Kind regards,

Nicolas

**Comment by nicolasduminil** [comment]
@hamburml : I need to update my comments above as, having traced the HTTP traffic, I get this:

    2024-06-18 14:54:39,088 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-3) Request: POST https://w2263hc2crj5js2lxaokyeqvka0jlxdu.lambda-url.eu-west-3.on.aws/s3/upload Headers[content-length=1170 Content-Type=multipart/form-data; boundary=5ea36f5799a6d76f User-Agent=Quarkus REST Client], Body omitted
    2024-06-18 14:54:49,285 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-3) Response: POST https://w2263hc2crj5js2lxaokyeqvka0jlxdu.lambda-url.eu-west-3.on.aws/s3/upload, Status[502 Bad Gateway], Headers[Date=Tue, 18 Jun 2024 12:54:49 GMT Content-Type=application/json Content-Length=21 Connection=keep-alive x-amzn-RequestId=984bf281-efcc-4098-85ed-0a6ba9a521d4 X-Amzn-Trace-Id=root=1-6671838f-35db041e2da6324e21114ee6;parent=181ed28d231167aa;sampled=0;lineage=2f92fea8:0], Body:
    Internal Server Error

So, as opposed to what you were saying, it is possible to test against full blown AWS environment, as the `@QuarkusTest` connects to the AWS URL, here `https://w2263hc2crj5js2lxaokyeqvka0jlxdu.lambda-url.eu-west-3.on.aws`. Further, there must be an error condition while working with multipart data on AWS Gateway. I thought that the HTTP 502 was related to the Mock Lambda server, which is still started and listening, but the real connection is done to the AWS URL, not `localhost`.

To conclude, there wasn't any issue here, the `@QuarkusTest` works as expected, the only thing is that the Mock Lambda server is unnecessarily started, but not used and the connection is done to the full scale AWS service.

Now I need to figure out why my API Gateway with Lambda proxy works when deployed on `localstack` but not on AWS (probably a permission related issue), but this is a different story.

**Comment by hamburml** [comment]
I never said that you can not test against a full blown AWS environment. What I said is that the current architecture of the lambda dependencies will always start the mock server.

What I simply overlooked is that you override the URL via  `-Dbase_uri/mp-rest/url`.

Suit yourself
