### ISSUE TITLE
Quarkus CLI reports `Unmatched argument at index 2` error when running a command that doesn't exist

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#41161]
### Describe the bug

When running a command that Quarkus doesn't understand, it throws a cryptic error from Picocli:
```
$ quarkus create ext abc -e                                                                        
Command quarkus-create-ext is not available, looking for available plugins ...
[ERROR] ❗  Command quarkus-create-ext is missing and can't be installed.
Creating an app (default project type, see --help).
picocli.CommandLine$UnmatchedArgumentException: Unmatched argument at index 2: 'abc'
	at io.quarkus.cli.common.OutputOptionMixin.throwIfUnmatchedArguments(OutputOptionMixin.java:154)
	at io.quarkus.cli.CreateApp.call(CreateApp.java:64)
	at io.quarkus.cli.CreateApp.call(CreateApp.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at io.quarkus.cli.Create.call(Create.java:35)
	at io.quarkus.cli.Create.call(Create.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at io.quarkus.cli.QuarkusCli.run(QuarkusCli.java:149)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.cli.Main.main(Main.java:9)

[ERROR] ❗  Unable to create project: Unmatched argument at index 2: 'abc'
```

### Expected behavior

It would be nice to display a better error message in this case	

### Actual behavior

Picocli error is shown

### How to Reproduce?

Run `quarkus create ext abc -e`

### Output of `uname -a` or `ver`

macOS m1

### Output of `java -version`

JDK 17

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.7

**Comment by geoand** [comment]
Is this still a problem?

**Comment by gastaldi** [comment]
Yes, error still exists in 3.32.1: 

```bash
$ quarkus create ext abc -e                                                                                                                            
Unable to match command `create-ext`, looking for available plugins...
2026-02-26 13:29:37,474 WARN  [io.sma.com.process] (process-waiter-"jbang"-6596) SRCOM05000: Command /Users/ggastald/.jbang/bin/jbang (pid 6596) completed but logged errors:
	[jbang] There is a new version of jbang available!
	[jbang] You have version 0.135.1 and 0.137.0 is the latest.
	[jbang] Run 'jbang version --update' to update to the latest version.
2026-02-26 13:29:38,109 WARN  [io.sma.com.process] (process-waiter-"jbang"-6662) SRCOM05000: Command /Users/ggastald/.jbang/bin/jbang (pid 6662) completed but logged errors:
	[jbang] [0:141] jbang version 0.135.1
	[jbang] [0:147] Reading catalog from classpath:/jbang-catalog.json
	[jbang] [0:174] Using cached file /Users/ggastald/.jbang/cache/urls/9e5f036f349563e036ce916208ce6a69cea71bd388666b1793f22c8ed96ad73a/jbang-catalog.json for remote https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json
	[jbang] [0:174] Reading catalog from https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json
	[jbang] [0:176] Obtained catalog from https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json
	… (skipped 2 line(s)) …
	[jbang] [0:502] Downloaded file https://raw.githubusercontent.com/quarkusio/jbang-catalog/HEAD/jbang-catalog.json
	[jbang] [0:504] Deleting folder /Users/ggastald/.jbang/cache/urls/18f27301d3b8b1c3bf70b027e02294385c940f21a743bc722c8f8f5bf569840c.old
	[jbang] [0:506] Deleting folder /Users/ggastald/.jbang/cache/urls/18f27301d3b8b1c3bf70b027e02294385c940f21a743bc722c8f8f5bf569840c-meta.old
	[jbang] [0:507] Reading catalog from https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json
	[jbang] [0:509] Obtained catalog from https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json
[ERROR] ❗  Unable to match command `create-ext` and a corresponding plugin couldn't be installed.
Creating an app (default project type, see --help).
picocli.CommandLine$UnmatchedArgumentException: Unmatched argument at index 2: 'abc'
	at io.quarkus.cli.common.OutputOptionMixin.throwIfUnmatchedArguments(OutputOptionMixin.java:154)
	at io.quarkus.cli.CreateApp.call(CreateApp.java:64)
	at io.quarkus.cli.CreateApp.call(CreateApp.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2031)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2469)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2423)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2425)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at io.quarkus.cli.Create.call(Create.java:35)
	at io.quarkus.cli.Create.call(Create.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2031)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2469)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2423)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2425)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at io.quarkus.cli.QuarkusCli.run(QuarkusCli.java:155)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:141)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:80)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:51)
	at io.quarkus.cli.Main.main(Main.java:9)

[ERROR] ❗  Unable to create project: Unmatched argument at index 2: 'abc'
```

**Comment by geoand** [comment]
Thanks a lot

**Comment by tiwari91** [comment]
Still reproduces on 3.32.1 as @gastaldi confirmed. The root cause is that Create has @Unmatched which silently absorbs the unknown subcommand, then Create.call() blindly forwards everything to CreateApp which throws the raw picocli exception.

Opened #52969 — it adds a check in Create.call() for non-flag unmatched args before the forward. Now you get a clear message listing the available subcommands instead of the stack trace.
