### ISSUE TITLE
Multipart @FormParam on EntityPart not working according to Jakarta RESTful Web Services 3.1

### ISSUE THREAD

**Issue by ollelogdahl** [quarkusio/quarkus#41186]
### Describe the bug

According to the [Jakarta RESTful Web Services 3.1 Specification](https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1#consuming_multipart_formdata), `@FormParam` should be supported on `EntityPart` parameters in resources. More specifically stated:

> For resource methods that consume multipart/form-data media types, the @FormParam annotation may be used on jakarta.ws.rs.core.EntityPart parameters. [link](https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1#resource_method_params)

Currently, this is not supported in quarkus-rest (resteasy-reactive), and giving the error `Could not create converter for jakarta.ws.rs.core.EntityPart`. It is in-fact not possible to implement your own `ParameterConverter`, as the [`FormParamExtractor`](https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/FormParamExtractor.java) giving the string-value for the converter doesn't include the 'content-disposition' row.

The following is the jist of the reproducer (a full project is attached below):
```java
@Path("/api")
public class GreetingResource {

    static final Logger LOG = LoggerFactory.getLogger(GreetingResource.class);

    @POST
    @Path("/upload")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.APPLICATION_JSON)
    public Response upload(@FormParam("part1") EntityPart part) {
        LOG.info("part: {}", part);
        return Response.ok().build();
    }
}
```

This should run correctly and respond with 200 using the following curl command
```
curl -vvv -X POST -F "part1=hello" http://localhost:8080/api/upload
```

This was previously reported in https://github.com/quarkusio/quarkus/issues/38980, but no reproducer was provided.

### Expected behavior

The program should start up successfully and respond to the following curl with 200:
```
curl -vvv -X POST -F "part1=hello" http://localhost:8080/api/upload
```

The logs should print that the part is **not** null. Inspecting the `EntityPart` should give access to all attributes taken from the content-disposition header (e.g. filename), and the content should be "hello".

### Actual behavior

Currently quarkus fails to start and logs the following:
```
[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Failed to process method 'org.acme.GreetingResource#upload'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:332)
	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:663)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.lang.RuntimeException: Failed to process method 'org.acme.GreetingResource#upload'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:780)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:421)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:299)
	... 11 more
Caused by: java.lang.RuntimeException: Could not create converter for jakarta.ws.rs.core.EntityPart for method jakarta.ws.rs.core.Response upload(jakarta.ws.rs.core.EntityPart part) on class org.acme.GreetingResource of type FORM
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:373)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:98)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.extractParameterInfo(EndpointIndexer.java:1449)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:598)
	... 13 more
Caused by: java.lang.RuntimeException: Failed to find converter for jakarta.ws.rs.core.EntityPart
	at org.jboss.resteasy.reactive.server.processor.generation.converters.GeneratedConverterIndexerExtension.extractConverterImpl(GeneratedConverterIndexerExtension.java:106)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.extractConverter(ServerEndpointIndexer.java:579)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:369)
	... 16 more
```

### How to Reproduce?

1. extract [reproducer.zip](https://github.com/user-attachments/files/15817050/reproducer.zip).
2. run `./mvnw clean quarkus:dev`

If quarkus succeeds in starting up, you need to
3. execute the following command and check the response code
    ```
    curl -vvv -X POST -F "part1=hello" http://localhost:8080/api/upload
    ```
4. Check the application logs to see if the part was not null.

### Output of `uname -a` or `ver`
```
Linux olle 4.18.0-553.5.1.el8_10.x86_64 #1 SMP Tue May 21 03:13:04 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
```
### Output of `java -version`
```
openjdk version "22.0.1" 2024-04-16
```
### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by geoand** [comment]
@FroMage loves these :)

**Comment by FroMage** [comment]
Well, there's a long list of things to improve with multipart. Do you feel like helping contribute support for this @ollelogdahl ?

**Comment by choudharypranay** [comment]
Is there a workaround currently?

**Comment by FroMage** [comment]
Well, you can use https://javadoc.io/doc/io.quarkus.resteasy.reactive/resteasy-reactive-common/latest/org/jboss/resteasy/reactive/multipart/FileUpload.html which what we added before `EntityPart` existed. It should provide the same information, except headers (for some reason, we probably forgot that and nobody noticed).

As for the `getContent` versions, unless the content type is dynamic, we have better support for deserialising form parameters where you can declare them as the proper type and they will go through the proper `MessageBodyReader`: https://quarkus.io/guides/rest#multipart

To be more precise, you can declare them as `@RestForm @PartType(MediaType.APPLICATION_JSON) Person person` and that will be equivalent to `.getContent(Person.class)` for a JSON mime type

**Comment by jnbdz** [comment]
`@FormParam` on an `EntityPart` parameter works on main since #55768 (milestone 4.0, not in a release yet). The reproducer from the description now returns 200 and the part is injected: `curl -F "part1=hello"` gives a part named `part1` whose content is `hello`, and `getFileName()` / `getHeaders()` expose what the spec requires. `@FormParam InputStream`, the other form allowed by section 3.5.2, works too.

While checking this I found that the charset declared by a part is ignored when its content is read as a `String`: a part sent as `text/plain; charset=ISO-8859-1` comes back with a replacement character instead of the accented letter, both through `EntityPart.getContent(String.class)` and through `@FormParam String` for a part that has a filename. #56575 fixes that.

So this issue looks resolved by #55768 and can be closed, unless you want it kept open for the charset part.
