### ISSUE TITLE
Stuck Quarkus process when port 8080 is already assigned, kill -9 needs to be used, user not informed about used port

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#4124]
Stuck Quarkus process when port 8080 is already assigned, `kill -9` needs to be used, user not informed about used port.

This is regression comparing to 0.22.0 when user is informed via `Caused by: java.net.BindException: Address already in use` and user can press Ctrl+C to stop the process.

Master based app doesn't react to Ctrl+C and `kill -9` needs to be used.
Stacktrace informs just about NPE, nothing about already used port.

```
java -jar getting-started-two/target/getting-started-two-1.0-SNAPSHOT-runner.jar
2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-15) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-9) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-1) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-8) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-4) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-14) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-12) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-10) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-11) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-3) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-13) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-6) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-5) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-0) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-2) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019-09-20 09:37:26,984 SEVERE [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-7) Unhandled exception: java.lang.NullPointerException
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$start$0(VertxHttpRecorder.java:382)
	at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:277)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Killed: 9
```

Steps to reproduce:
```

mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started-one \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"


mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started-two \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"


mvn clean package -f getting-started-one/pom.xml
mvn clean package -f getting-started-two/pom.xml

java -jar getting-started-one/target/getting-started-one-1.0-SNAPSHOT-runner.jar &
java -jar getting-started-two/target/getting-started-two-1.0-SNAPSHOT-runner.jar
```

Run following command in new terminal to kill the stuck process
```
jps -l | grep started-two | cut -d" " -f1 | xargs kill -9
```

Don't forget to stop the first app
```
jps -l | grep started-one | cut -d" " -f1 | xargs kill
```

**Comment by rafialhamd** [comment]
I'm facing this issue, now.

Just started with Quarkus.
Ran command: `mvnw compile quarkus:dev:`, in Windows 10 _git bash terminal_.

localhost:8080/hello is working fine.
Changed the code, and hot deploy didn't work.

Wanted to re-start Quarkus. Attempted Ctrl+C. But, didn't work.
So, Closed the 'terminal'.
Again, running the command `mvnw compile quarkus:dev:` gives the below error:

> [INFO] --- quarkus-maven-plugin:1.2.0.Final:dev (default-cli) @ bismi-ap ---
> [ERROR] Port 5005 in use, not starting in debug mode
> 
> 2020-02-07 21:20:38,124 WARN  [io.qua.net.run.NettyRecorder] (Thread-50) Localhost lookup took more than one second, you need to add a /etc/hosts entry to improve Quarkus startup time. See https://thoeni.io/post/macos-sierra-java/ for details.
> 2020-02-07 21:20:38,251 ERROR [io.qua.application] (main) Failed to start application: java.lang.RuntimeException: Unable to start HTTP server
>         at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:330)
> 

Can someone help me fix this please... Thanks!

**Comment by rafialhamd** [comment]
I **rebooted** Windows, and started to use _Traditional Windows Command Prompt_, and no issues in using `mvnw compile quarkus:dev:`.

**Comment by fahad-israr** [comment]
# Facing similar issue 
`ERROR [io.qua.application] (main) Failed to start application: java.lang.RuntimeException: Unable to start HTTP server
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:415)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:188)
	at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket31.deploy_0(VertxHttpProcessor$openSocket31.zig:119)
	at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket31.deploy(VertxHttpProcessor$openSocket31.zig:36)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:214)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
`
