### ISSUE TITLE
Accessing a management endpoint after a live reload leads to an exception (when Hibernate Search Standalone mapper is used)

### ISSUE THREAD

**Issue by marko-bekhta** [quarkusio/quarkus#41315]
### Describe the bug

Accessing a management endpoint after a live reload leads to an exception. This issue occurs with https://github.com/quarkusio/search.quarkus.io, it was discovered while working on https://github.com/quarkusio/search.quarkus.io/pull/286.

### Expected behavior

After an app is reloaded -- management endpoints can be accessed without any issues.

### Actual behavior

An exception occurs:

```java
java.lang.IllegalStateException: Failed to create indexes: Error creating synthetic bean [A3Pwpzj6LZ1U3ryq007Z-Hp-28Q]: java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
	at io.quarkus.search.app.indexing.IndexingService.createIndexes(IndexingService.java:213)
	at io.quarkus.search.app.indexing.IndexingService.reindex(IndexingService.java:170)
	at io.quarkus.search.app.indexing.IndexingService_Subclass.reindex$$superforward(Unknown Source)
	at io.quarkus.search.app.indexing.IndexingService_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:129)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.quarkus.search.app.indexing.IndexingService_Subclass.reindex(Unknown Source)
	at io.quarkus.search.app.indexing.IndexingService.lambda$registerManagementRoutes$0(IndexingService.java:57)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [A3Pwpzj6LZ1U3ryq007Z-Hp-28Q]: java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
	at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_Bean.doCreate(Unknown Source)
	at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_Bean.create(Unknown Source)
	at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c29(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_ClientProxy.arc$delegate(Unknown Source)
	at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_ClientProxy.scope(Unknown Source)
	at io.quarkus.search.app.indexing.IndexingService.createIndexes(IndexingService.java:191)
	... 26 more
	Suppressed: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [A3Pwpzj6LZ1U3ryq007Z-Hp-28Q]: java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
		at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_Bean.doCreate(Unknown Source)
		at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_Bean.create(Unknown Source)
		at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_Bean.create(Unknown Source)
		at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
		at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
		at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
		at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c29(Unknown Source)
		at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
		at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
		at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
		at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_ClientProxy.arc$delegate(Unknown Source)
		at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_ClientProxy.backend(Unknown Source)
		at io.quarkus.search.app.indexing.Rollover.client(Rollover.java:105)
		at io.quarkus.search.app.indexing.Rollover.recoverInconsistentAliases(Rollover.java:92)
		at io.quarkus.search.app.indexing.IndexingService.createIndexes(IndexingService.java:205)
		... 26 more
	Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
		at java.base/java.util.HashMap.putMapEntries(HashMap.java:495)
		at java.base/java.util.LinkedHashMap.<init>(LinkedHashMap.java:385)
		at io.quarkus.hibernate.search.standalone.elasticsearch.runtime.HibernateSearchStandaloneRecorder$1.apply(HibernateSearchStandaloneRecorder.java:110)
		at io.quarkus.hibernate.search.standalone.elasticsearch.runtime.HibernateSearchStandaloneRecorder$1.apply(HibernateSearchStandaloneRecorder.java:103)
		at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_Bean.createSynthetic(Unknown Source)
		... 41 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:495)
	at java.base/java.util.LinkedHashMap.<init>(LinkedHashMap.java:385)
	at io.quarkus.hibernate.search.standalone.elasticsearch.runtime.HibernateSearchStandaloneRecorder$1.apply(HibernateSearchStandaloneRecorder.java:110)
	at io.quarkus.hibernate.search.standalone.elasticsearch.runtime.HibernateSearchStandaloneRecorder$1.apply(HibernateSearchStandaloneRecorder.java:103)
	at org.hibernate.search.mapper.pojo.standalone.mapping.SearchMapping_A3Pwpzj6LZ1U3ryq007Z-Hp-28Q_Synthetic_Bean.createSynthetic(Unknown Source)
	... 39 more
```

### How to Reproduce?

1. Run a Quarkus app in dev mode
2. Make some changes and save them so that the app is reloaded
3. After the app is reloaded, trying to access a management endpoint results in an exception.

### Output of `uname -a` or `ver`

Linux fedora 6.8.11-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sun May 26 20:05:41 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.10" 2024-01-16 OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7) OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)

### Quarkus version or git rev

3.11.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)

### Additional information

I'm opening the issue as is so that we don't forget to investigate it. If someone else picks it up and has questions about reproducing it or running search.quarkus.io, feel free to ping me.

**Comment by yrodiere** [comment]
Hey @marko-bekhta , is this really about any management endpoint like the title suggests? Or just a problem you got with the Hibernate Search Standalone extension?

**Comment by marko-bekhta** [comment]
> Hey @marko-bekhta , is this really about any management endpoint like the title suggests? Or just a problem you got with the Hibernate Search Standalone extension?

good point 🙈 I've updated the title a bit, but from what I've seen, I can get the an error with the ORM mapper as well... just a different one:
```
java.util.NoSuchElementException: SRCFG00027: Could not find a mapping for io.quarkus.search.app.fetching.FetchingConfig
	at io.smallrye.config.SmallRyeConfig.getConfigMapping(SmallRyeConfig.java:591)
	at io.quarkus.arc.runtime.ConfigMappingCreator.create(ConfigMappingCreator.java:30)
	at io.quarkus.search.app.fetching.FetchingConfig_FeT38EpD1hrch2luAL5GZdVFKpU_Synthetic_Bean.createSynthetic(Unknown Source)
	at io.quarkus.search.app.fetching.FetchingConfig_FeT38EpD1hrch2luAL5GZdVFKpU_Synthetic_Bean.doCreate(Unknown Source)
	at io.quarkus.search.app.fetching.FetchingConfig_FeT38EpD1hrch2luAL5GZdVFKpU_Synthetic_Bean.create(Unknown Source)
```
so live reload seems to mess something up 😕 but IDK... I'll try to have a closer look tomorrow....

**Comment by marko-bekhta** [comment]
I've looked a bit more into this.. and I think it's actually not related to Hibernate Search...

The problem seems to be that the management route handlers added in the app are not reloaded:
```java
void registerManagementRoutes(@Observes ManagementInterface mi) {
    mi.router().get(REINDEX_ENDPOINT_PATH)
            .blockingHandler(new ReindexHandler());
}
```

Even though this code is executed when the app is reloaded, when an actual request for a management endpoint comes in - it is handled by whatever the handler was on the application start. 

The same applies if you try to add a new management endpoint and then do a live reload -- the call to a new endpoint will result in a 404 😖 😕...

The error in the original bug report is thrown by Search as an original handler (pointing to the original service bean) tries to access a search mapping bean that was already destroyed and removed from the context. As a result it tries to create it, but since the standalone mapper already cleaned up boot things -- it cannot create another mapping...
