### ISSUE TITLE
gradlew quarkusRun failed with error "Failed to index: io.quarkus.test.TestReactiveTransaction"

### ISSUE THREAD

**Issue by nining** [quarkusio/quarkus#41328]
### Describe the bug

When running "gradlew quarkusRun", it failed with error "Failed to index: io.quarkus.test.TestReactiveTransaction".  I dont' know where this error come from. My code don't even has any code with TestReactiveTransaction.

When running with "gradlew quarkusDev", everything is OK.

### Expected behavior

Working

### Actual behavior

Failed with the following error:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':quarkusRun'.
> > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
>         [error]: Build step io.quarkus.arc.deployment.BeanArchiveProcessor#build threw an exception: java.lang.IllegalStateException: Failed to index: io.quarkus.test.TestReactiveTransaction
>         at io.quarkus.deployment.index.IndexingUtil.indexClass(IndexingUtil.java:168)
>         at io.quarkus.arc.deployment.BeanArchiveProcessor.build(BeanArchiveProcessor.java:94)
>         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
>         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
>         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
>         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
>         at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
>         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
>         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
>         at java.base/java.lang.Thread.run(Thread.java:1583)
>         at org.jboss.threads.JBossThread.run(JBossThread.java:483)
>   Caused by: java.lang.IllegalArgumentException: stream cannot be null
>         at org.jboss.jandex.Indexer.indexWithSummary(Indexer.java:2482)
>         at io.quarkus.deployment.index.IndexingUtil.indexClass(IndexingUtil.java:163)
>         ... 11 more
> 
> 

### Output of `uname -a` or `ver`

Darwin noname 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

java version "21.0.1" 2023-10-17 Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)

### Quarkus version or git rev

3.11.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.5 ------------------------------------------------------------  Build time:   2023-11-29 14:08:57 UTC Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598  Kotlin:       1.9.20 Groovy:       3.0.17 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          21.0.1 (Oracle Corporation 21.0.1+12-jvmci-23.1-b19) OS:           Mac OS X 14.5 aarch64

### Additional information

It will also failed on a Linux x64 machine.  I have this command to be successful in the past, but after more code added it failed.

**Comment by nining** [comment]
I found the issue was raised after upgrading to Quarkus 3.11.0, and the previous 3.10.2 was working.
