### ISSUE TITLE
OIDC private_key_jwt flow with id-token-required=false fails on generating internal IdToken

### ISSUE THREAD

**Issue by mhayen** [quarkusio/quarkus#41357]
### Describe the bug

I'm integrating with a Spring Authorization Server based OIDC provider with Authorization Code Grant.
the private key jwt is used as credentials.
Since the ID token is not return in the response we also use `quarkus.oidc.authentication.id-token-required=false`
But the it fails with a NPE when trying to generate a key to use the 'internal IdToken'
```

2024-06-21 14:20:21,846 DEBUG [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-3) RoutingContext failure (500): java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "secret" is null
        at io.smallrye.jwt.util.KeyUtils.createSecretKeyFromSecret(KeyUtils.java:220)
  at io.quarkus.oidc.runtime.CodeAuthenticationMechanism.generateInternalIdToken(CodeAuthenticationMechanism.java:978)
        at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$9.apply(CodeAuthenticationMechanism.java:812)
        at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$9.apply(CodeAuthenticationMechanism.java:797)
 
```

when I provide a secret like `quarkus.oidc.credentials.client-secret.value=geheim`
the client secret credentials flow is choosen and this fails of course.

### Expected behavior

To not fail with a NPE or to be able to provide a secret which does not trigger the wrong client credentials flow

### Actual behavior

fails with 
```
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "secret" is null
	at io.smallrye.jwt.util.KeyUtils.createSecretKeyFromSecret(KeyUtils.java:220)
	at io.quarkus.oidc.runtime.CodeAuthenticationMechanism.generateInternalIdToken(CodeAuthenticationMechanism.java:978)
	at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$9.apply(CodeAuthenticationMechanism.java:812)
	at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$9.apply(CodeAuthenticationMechanism.java:797)
	at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:54)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:47)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:47)
	at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
	at io.smallrye.mutiny.vertx.DelegatingHandler.handle(DelegatingHandler.java:25)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:397)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:384)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:362)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:329)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:291)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$7(HttpContext.java:507)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:261)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:59)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Output of `uname -a` or `ver`

Darwin MBP-DVJM7TRQXF 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031 arm64

### Output of `java -version`

java version "21.0.3" 2024-04-16 LTS Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152) Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)

### Quarkus version or git rev

3.11.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8

**Comment by sberyozkin** [comment]
I think in this case we can try to fall back to the configured session encryption key's hash to act as an internal ID token's signing key, otherwise the only other option is to generate a signing key. In this case the session encryption key must be configured as well because the client secret fallback is not available...

**Comment by mhayen** [comment]
I tried setting `quarkus.oidc.token-state-manager.encryption-secret` but that doesn't change anything.
How can I 'fall back' to the session encryption key's hash ?

**Comment by sberyozkin** [comment]
@mhayen 

Sorry, I meant that this is how we can try to fit it, without having to introduce one more property, since in this case, the session encryption key should be set to avoid the session be encrypted with a random key which is not great in devmode or after restarts or across pods.
