### ISSUE TITLE
Detected an instance of Random/SplittableRandom class in the image heap

### ISSUE THREAD

**Issue by parasjain27031994** [quarkusio/quarkus#41385]
### Describe the bug

I have a Quarkus application, that includes dependencies for both AWS and Azure EventHub. Since EventHub extension is not yet available and Azure SDK is GraalVM compatible, while building the native image I am getting following error

```
Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use 
    '--trace-object-instantiation=java.security.SecureRandom'
to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 
    '--initialize-at-run-time=<culprit>'
to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  trying to constant fold static field com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.SECURE_RANDOM
    at com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.computeDigestAuthHeader(DigestProxyChallengeProcessorImpl.java:143)
  parsing method com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.computeDigestAuthHeader(DigestProxyChallengeProcessorImpl.java:116) reachable via the parsing context
    at static root method.(Unknown Source)
com.oracle.svm.core.util.UserError$UserException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use 
    '--trace-object-instantiation=java.security.SecureRandom'
to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 
    '--initialize-at-run-time=<culprit>'
to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  trying to constant fold static field com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.SECURE_RANDOM
    at com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.computeDigestAuthHeader(DigestProxyChallengeProcessorImpl.java:143)
  parsing method com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.computeDigestAuthHeader(DigestProxyChallengeProcessorImpl.java:116) reachable via the parsing context
    at static root method.(Unknown Source)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:814)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. If these objects should not be stored in the image heap, you can use 
    '--trace-object-instantiation=java.security.SecureRandom'
to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 
    '--initialize-at-run-time=<culprit>'
to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
  trying to constant fold static field com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.SECURE_RANDOM
    at com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.computeDigestAuthHeader(DigestProxyChallengeProcessorImpl.java:143)
  parsing method com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl.computeDigestAuthHeader(DigestProxyChallengeProcessorImpl.java:116) reachable via the parsing context
    at static root method.(Unknown Source)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:809)
	... 6 more
```

The initial error was different and related to a conflict with reactor netty, so based on https://github.com/quarkusio/quarkus/issues/26879 I made following adjustments in my POM

```
 <dependency>
            <groupId>io.quarkiverse.azureservices</groupId>
            <artifactId>quarkus-azure-http-client-vertx</artifactId>
            <version>1.0.4</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.azure</groupId>
                    <artifactId>azure-core-http-netty</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
I also defined below native image args
```
quarkus:
  native:
    additional-build-args: --initialize-at-run-time=com.microsoft.azure.proton.transport.ws.impl.Utils
```
However, after making the change, it is now throwing the above error.

### Expected behavior

The native image build should succeed.

### Actual behavior

THe native build fails

### Output of `java -version`

graalvm-jdk-21+35.1

### Mandrel or GraalVM version (if different from Java)

23.1.3.1-Final

### Quarkus version or git rev

3.11.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by Karm** [comment]
@parasjain27031994 You need to use `--trace-object-instantiation` and perhaps also `--trace-class-initialization` to see the chain of what initializes what. Looking at source code also might help. You then mark the relevant classes for runtime initialization, e.g. in `application.properties` e.g. 
```
quarkus.native.additional-build-args=\
-H:+UnlockExperimentalVMOptions,\
--initialize-at-run-time=\
some.package.SomeClass1\\,\
some.package.SomeClass2\\,\
some.package.SomeClass3,\
-H:-UnlockExperimentalVMOptions
```

Give it a shot and tell us if you need any assistance.

**Comment by zakkak** [comment]
@parasjain27031994 you might want to have a look at https://foivos.zakkak.net/tutorials/working-with-randoms-native-images/ (non-Quarkus specific blog post about this issue) as well.

**Comment by karottc** [comment]
I have the same error message. I am using the okhttp component.


```
 <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <version>4.12.0</version>
  </dependency>
```

**Comment by parasjain27031994** [comment]
Hi @Karm , I did followed your advice, I manage to get away with the previous error, however, I am still seeing the below exception

```
Error: An object of type 'io.netty.handler.ssl.OpenSslClientContext' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.
You now have two options to resolve this:
1) If it is intended that objects of type 'io.netty.handler.ssl.OpenSslClientContext' are persisted in the image heap, add 
    '--initialize-at-build-time=io.netty.handler.ssl.OpenSslClientContext'
to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'io.netty.handler.ssl.OpenSslClientContext' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.
2) If these objects should not be stored in the image heap, you can use 
    '--trace-object-instantiation=io.netty.handler.ssl.OpenSslClientContext'
to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 
    '--initialize-at-run-time=<culprit>'
to prevent the instantiation of the object.
If you are seeing this message after enabling '--strict-image-heap', this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
To fix this, include '--initialize-at-build-time=io.netty.handler.ssl.OpenSslClientContext' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.
Please address this problem to be prepared for future releases of GraalVM.
The following detailed trace displays from which field in the code the object was reached.
Trace: Object was reached by
  reading field reactor.netty.tcp.SslProvider.sslContext of constant 
    reactor.netty.tcp.SslProvider@440ec20: SslProvider {type=NONE, handshakeTimeoutMillis=10000, closeNotifyFlushTimeoutMil...
  scanning root reactor.netty.tcp.SslProvider@440ec20: SslProvider {type=NONE, handshakeTimeoutMillis=10000, closeNotifyFlushTimeoutMil... embedded in 
    reactor.netty.http.client.HttpClientSecure.defaultSslProvider(HttpClientSecure.java:36)
  parsing method reactor.netty.http.client.HttpClientSecure.defaultSslProvider(HttpClientSecure.java:35) reachable via the parsing context
    at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:217)
    at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$$Lambda/0x00000007c23064f0.accept(Unknown Source)
    at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1736)
    at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
    at java.util.ServiceLoader$ModuleServicesLookupIterator.iteratorFor(ServiceLoader.java:1054)
    at java.util.ServiceLoader$ModuleServicesLookupIterator.<init>(ServiceLoader.java:1001)
    at java.util.ServiceLoader.newLookupIterator(ServiceLoader.java:1304)
    at java.util.ServiceLoader.iterator(ServiceLoader.java:1368)
    at java.util.ServiceLoader.findFirst(ServiceLoader.java:1811)
    at java.net.InetAddress.loadResolver(InetAddress.java:508)
    at java.net.InetAddress.resolver(InetAddress.java:488)
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1826)
    at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1139)
    at java.net.InetAddress.getAllByName0(InetAddress.java:1818)
    at java.net.InetAddress.getAllByName(InetAddress.java:1688)
    at java.net.InetAddress.getByName(InetAddress.java:1568)
    at java.net.URL.getHostAddress(URL.java:995)
    at java.net.URLStreamHandler.getHostAddress(URLStreamHandler.java:447)
    at java.net.URLStreamHandler.hashCode(URLStreamHandler.java:372)
    at java.net.URL.hashCode(URL.java:1159)
    at java.lang.Object.toString(Object.java:257)
    at io.quarkus.vertx.mdc.provider.LateBoundMDCProvider.remove(LateBoundMDCProvider.java:81)
    at root method.(Unknown Source)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:809)
	... 6 more
```

Even though, I have added below config in my application 

```
quarkus:
  native:
    additional-build-args: >
      --initialize-at-run-time=io.netty.handler.ssl.OpenSslClientContext,
      --initialize-at-run-time=com.microsoft.azure.proton.transport.proxy.impl.DigestProxyChallengeProcessorImpl,
      --initialize-at-run-time=com.microsoft.azure.proton.transport.ws.impl.Utils
```

**Comment by Karm** [comment]
@parasjain27031994 It is impossible to help you without having a reproducer, small project you are trying to compile.

To bring whole OKHttp to native might require *many* more config options, in fact, so many that it might be impractical to try to do it by hand. 

You might take a look at an agent that facilitates the automation of creating the config:
https://quarkus.io/guides/native-reference#native-image-agent-integration

While we are talking OKHttp specifically, used in Quarkus app, you might use Vert.x or Netty's components directly and might be better off with fewer dependencies...

**Comment by parasjain27031994** [comment]
Hi @Karm , I am not using OKHTTP, I think that is another comment from someone else, let me try to stick together a quick reproducer.

**Comment by parasjain27031994** [comment]
Hi @Karm , After debugging the native build, I managed to pinpoint that the issue occurs after adding below dependency

```
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-queue</artifactId>
        </dependency>
```

Here is a reproduce for same

https://github.com/parasjain27031994/quarkus-azure-queue-sample.git

**Comment by gsmet** [comment]
I'm still wondering if we should avoid initialize non vetted artifacts at build time.

I suggested a few times a middle ground of initializing at build time everything that was pushed by an extension and let GraalVM initialize at runtime everything else.

Not sure how easy it would be to implement but I wonder if we should revive this discussion.
It makes Quarkus harder to use when you just want to add a random dependency.

/cc @zakkak @geoand @cescoffier

**Comment by parasjain27031994** [comment]
Hi @gsmet , I may not be aware much about Qurakus internals, I was hoping that if I use any dependencies that are GraalVM compatible, should work well in Quarkus as well.

https://devblogs.microsoft.com/azure-sdk/announcing-graalvm-support-in-azure-sdk-for-java-and-spring-cloud-azure-libraries/

**Comment by cescoffier** [comment]
I'm not against, but we need to be careful as it may have an effect on performances of Quarkus applications that are running fine today. 

We could start with an option (switching to runtime for non vetted artifacts) and also a list of artifacts the user can configure to still initialize at build time (when the option is enabled)

**Comment by parasjain27031994** [comment]
Hi @Karm , thanks for investigation it. I did manage to find from some other threads that we can exclude "`azure-core-http-netty`" and include "`azure-core-http-vertx`", however, I am still running into some issues, I did tried to trace the object instantiation and class initialization and tend to mark them for runtime, however still I am unable to make it work.

```
Error: java.util.concurrent.ExecutionException: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: An object of type 'io.netty.util.concurrent.ScheduledFutureTask' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.
You now have two options to resolve this:
1) If it is intended that objects of type 'io.netty.util.concurrent.ScheduledFutureTask' are persisted in the image heap, add 
    '--initialize-at-build-time=io.netty.util.concurrent.ScheduledFutureTask'
to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'io.netty.util.concurrent.ScheduledFutureTask' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.
2) If if it is not intended that objects of type 'io.netty.util.concurrent.ScheduledFutureTask' are persisted in the image heap, examine the stack trace and use 
    '--initialize-at-run-time=<culprit>'
to prevent instantiation of this object.
The culprit object has been instantiated with the following trace:
	at io.netty.util.concurrent.ScheduledFutureTask.<init>(ScheduledFutureTask.java:40)
	at io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:208)
	at io.vertx.core.impl.VertxImpl.scheduleTimeout(VertxImpl.java:665)
	at io.vertx.core.impl.VertxImpl.scheduleTimeout(VertxImpl.java:676)
	at io.vertx.core.impl.VertxImpl.setTimer(VertxImpl.java:443)
	at io.vertx.core.http.impl.HttpClientImpl.checkExpired(HttpClientImpl.java:153)
	at io.vertx.core.http.impl.HttpClientImpl.access$100(HttpClientImpl.java:48)
	at io.vertx.core.http.impl.HttpClientImpl$PoolChecker.handle(HttpClientImpl.java:144)
	at io.vertx.core.http.impl.HttpClientImpl$PoolChecker.handle(HttpClientImpl.java:132)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1056)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1027)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:328)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:321)
	at io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:209)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:1045)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.runWith(Thread.java:1596)
	at java.lang.Thread.run(Thread.java:1583)  
```

**Comment by Karm** [comment]
Hello @parasjain27031994, 

Your remark about the possibility to exclude `azure-core-http-netty` basically solved the problem :-) Bringing the complexity way down from zillions of JNI bindings for tcnative to just a handful of things for the `okhttp` client I chose from the [pluggable implementations](https://github.com/Azure/azure-sdk-for-java/wiki/Custom-HTTP-clients). Using the vert.x one would likely make it even less complex, but I'd have to either use the beta one from Central or write my own and it seemed beside the point.

Here is a working example you can use to get your project working. Note that I heavily modified your original example and most notably, I removed the AWS Lambda stuff as that is completely irrelevant to the Azure SDK issues. When it comes to Quarkus and Native, "AWS Lambda" basically just means "pack everything into function.zip for deployment". 

## Start Azurite
```
$ podman  run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite
```

## Run the example
```
$ git clone https://github.com/Karm/dev-null.git
$ cd dev-null/quarkus-azure-queue-sample/
$ export JAVA_HOME=/home/karm/X/JDKs/mandrel-java21-23.1.3.1-Final/;export GRAALVM_HOME=${JAVA_HOME};export PATH=${JAVA_HOME}/bin:${PATH}
$ ./mvnw clean install -Dnative
```

You should see something like this in the Azurite log:
```
127.0.0.1 - - [06/Aug/2024:13:21:14 +0000] "PUT /devstoreaccount1/meh HTTP/1.1" 204 -
127.0.0.1 - - [06/Aug/2024:13:21:14 +0000] "POST /devstoreaccount1/meh/messages HTTP/1.1" 201 -
```
And the test must pass.

The solution is in the configuration files, notably:
```
src/main/resources/application.yml
src/main/resources/proxy-config.json
src/main/resources/reflect-config.json
src/main/resources/resource-config.json
```

## How?
I ran two versions of the app in HotSpot mode, one with Azure dependencies and one without them, including the runtime test. 
The one without them just returned a mock string "hahaha" , it did not call any Azure stuff.

I used native agent to monitor and record what the application accesses.

```
$ java -agentlib:native-image-agent=config-output-dir=AGENT_NO_AZURE -jar target/quarkus-app/quarkus-run.jar
...
$ java -agentlib:native-image-agent=config-output-dir=AGENT_AZURE -jar target/quarkus-app/quarkus-run.jar
```

Then I examined the diff. Furthermore, I used `--trace-class-initialization` to nail down what the agent missed. 

## UX

One could also use https://quarkus.io/version/main/guides/native-reference#integration-testing-with-the-tracing-agent to make the process smoother.

If there is a Quarkus extension for azure-storage-queue, all this would be hidden from the Quarkus user, done by the extension.

I will close this issue now as we are not talking a Quarkus bug. If you see it differently, feel free to reopen or reach out on Zulip.
