### ISSUE TITLE
Upgrade to latest quarkus version 3.12.0

### ISSUE THREAD

**Issue by khaledhnAbusair** [quarkusio/quarkus#41399]
I encountered an issue when upgrading to the latest version:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.12.0:build (default) on project ekycapi: Failed to build Quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.resteasy.reactive.common.deployment.ResteasyReactiveCommonProcessor#checkMixingStacks threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Mixing Quarkus REST and RESTEasy Classic server parts is not supported
[ERROR]         at io.quarkus.resteasy.reactive.common.deployment.ResteasyReactiveCommonProcessor.checkMixingStacks(ResteasyReactiveCommonProcessor.java:108)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:840)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:483)
[ERROR] -> [Help 1]
```

Below are my dependency files. Can anyone help me, please?

[pom.txt](https://github.com/user-attachments/files/15960416/pom.txt)

**Comment by cescoffier** [comment]
You didn't send your dependencies, just the root pom. Please send the `pom.xml` file of the module triggering this issue.

**Comment by khaledhnAbusair** [comment]
@cescoffier sorry for that 

[pom2.txt](https://github.com/user-attachments/files/15966085/pom2.txt)

**Comment by cescoffier** [comment]
Some of your dependencies are not correct. Typically the RestEasy multipart need to be changed.

See https://quarkus.io/blog/quarkus-3-9-1-released/ for details.
