### ISSUE TITLE
Qute: StackOverflowError due to nested #include and #insert directives

### ISSUE THREAD

**Issue by gbourant** [quarkusio/quarkus#41451]
### Describe the bug

I have the following templates and i get a `StackOverflowError`. This happens because the `login.html` include the `auth.html` template
and the `auth.html` template includes the `root.html` which both have a default `{#insert/}`.

In order to fix this i can use a named insert, but i'm just wondering if this is a bug worth mentioning or it is intended to be used in that way.

`root.html`

```html
<html>
<body>{#insert /}</body>
</html>
```

`auth.html`

```html
{#include root.html}
    <div>
        {#insert/}
    </div>
{/include}
```

`login.html`

```html
{#include auth.html}
    <form>Login Form</form>
{/include}
```

So in order to fix this change the `{#insert/}` of `auth.html` to `{#insert main /}` and in templates `login.html` use it `{#main}`

`auth.html`

```html
{#include root.html}
    <div>
        {#insert main/}
    </div>
{/include}
```

`login.html`

```html
{#include auth.html}
    {#main}<form>Login Form</form>{/}
{/include}
```

```
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: 11b07391-60d2-46dd-8c66-d320e7678346-3: java.lang.StackOverflowError
	at io.quarkus.runtime.logging.LogCleanupFilter.isLoggable(LogCleanupFilter.java:32)
	at java.logging/java.util.logging.Handler.isLoggable(Handler.java:443)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:87)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:438)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
	at org.jboss.logmanager.Logger.logRaw(Logger.java:1089)
	at org.jboss.logmanager.Logger.log(Logger.java:1052)
	at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:56)
	at org.jboss.logging.Logger.tracef(Logger.java:303)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:47)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:228)
	at io.quarkus.qute.InsertSectionHelper.resolve(InsertSectionHelper.java:20)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:228)
	at io.quarkus.qute.InsertSectionHelper.resolve(InsertSectionHelper.java:20)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:48)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:228)
	at io.quarkus.qute.InsertSectionHelper.resolve(InsertSectionHelper.java:20)
```

[reproducer](https://github.com/gbourant/qute-insert-bug)

**Comment by ia3andy** [comment]
[qute-inheritance-issue.zip](https://github.com/user-attachments/files/15992505/qute-inheritance-issue.zip)

Funny I found the same issue today :) reproducer 👆
