### ISSUE TITLE
Error Due to Duplicate Event Listener in Hibernate SessionFactory Initialization when start application

### ISSUE THREAD

**Issue by khaledhnAbusair** [quarkusio/quarkus#41463]
After upgrading our application to the latest version of Quarkus, we encountered an error preventing the application from starting successfully. The error stack trace indicates a problem with building the Hibernate SessionFactory due to a "Duplicate event listener found" exception.

**Error Stack Trace:**

```
at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:642)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeAllMethod(QuarkusTestExtension.java:710)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:285)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:251)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:609)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:659)
	... 1 more
Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: <default>] Unable to build Hibernate SessionFactory
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:129)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:89)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:154)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:61)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.hibernate.event.service.spi.EventListenerRegistrationException: Duplicate event listener found
	at org.hibernate.event.service.internal.EventListenerGroupImpl.handleListenerAddition(EventListenerGroupImpl.java:312)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.appendListeners(EventListenerGroupImpl.java:209)
	at org.hibernate.event.service.internal.EventListenerRegistryImpl.appendListeners(EventListenerRegistryImpl.java:184)
	at org.hibernate.envers.boot.internal.EnversIntegrator.integrate(EnversIntegrator.java:89)
	at org.hibernate.internal.SessionFactoryImpl.integrate(SessionFactoryImpl.java:517)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:276)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:87)
	... 6 more
```

**Additional Details:**

- **Application Framework:** Quarkus
- **Persistence Provider:** Hibernate
- **Envers Integration:** Enabled for auditing purposes
- **Steps to Reproduce:** Upgrade application to the latest Quarkus version and attempt to start the application.

**Expected Resolution:**

Identify the root cause of the "Duplicate event listener found" exception during Hibernate SessionFactory initialization and provide a solution to ensure proper integration of Hibernate Envers without duplication.

---

Note: Attached Below are My Dependencies

Please find attached the file containing details of the dependencies used in the project. This includes configurations and libraries that are crucial for the application's functionality and integration.

[parent_pom.txt](https://github.com/user-attachments/files/15987071/parent_pom.txt)
[child_pom.txt](https://github.com/user-attachments/files/15987070/child_pom.txt)

**Comment by yrodiere** [comment]
Thank you for reporting.

I'm afraid the stacktrace is not giving obvious clues, and our own integration tests with ORM + Envers are passing. So there must be something specific in your app.

Can you please provide a minimal project that reproduces the problem, so we can run it and look into the problem?

**Comment by khaledhnAbusair** [comment]
@yrodiere, thank you for trying to help me with the duplicate listener issue; I managed to solve that. However, I could use your assistance with another problem. Here’s a sample of my code: [GitHub Repository](https://github.com/khaledhnAbusair/demo-quarkus). 

When I try to send any request in an integration test or actual run, it always returns a 404 error. I suspect the problem lies in my `pom.xml` file, but I haven't been able to pinpoint the issue. If you could take a look, I would greatly appreciate it. 😊

Note: the integration test in the class `com.test.FilesApiTest`
