### ISSUE TITLE
If running quarkusDev using the gradle plugin ClassNotFoundException: VirtualThreadsConfig occurs

### ISSUE THREAD

**Issue by palmoliven** [quarkusio/quarkus#41510]
###  I get the follwing error if I run quarkusDev using quarkus 3.12.0
Caused by: java.lang.ClassNotFoundException: io.quarkus.virtual.threads.VirtualThreadsConfig
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)

### with the followinging quarkus extensions
 quarkus-arc, camel-quarkus-core, camel-quarkus-xml-jaxb, camel-quarkus-protobuf, camel-quarkus-grpc

### My System
JDK 17.10, on a Windows 10 22H2, PowerShell 7.3.12, Intel Core i7-12800H, 32GB Memory
Quarkus commandline tool 3.11.2

### What I've tested
- The problem does not show up with using Maven
- The Problem persists using JDK 21
- I tested the quarkus commandline tool as well as creating the project on the web-page
- I tested also Quarkus 3.8.5, 3.9.5: the problem persists
- When adding the quarkus rest extension the error is gone 

### Expected behavior

No Exception if running quarkusDev

### Actual behavior

I get a  java.lang.ClassNotFoundException: io.quarkus.virtual.threads.VirtualThreadsConfig

### How to Reproduce?

quarkus create app --gradle

cd code-with-quarkus

rm src\main\java\org\acme\GreetingResource.java  
rm src\test\java\org\acme\GreetingResourceTest.java 

quarkus ext remove quarkus-rest                                                

quarkus ext add camel-quarkus-core camel-quarkus-xml-jaxb camel-quarkus-protobuf camel-quarkus-grpc 

create file .\src\main\java\org\acme\Main.java with content
package com.acme;

import io.quarkus.runtime.annotations.QuarkusMain;
import io.quarkus.runtime.Quarkus;

@QuarkusMain  
public class Main {

    public static void main(String ... args) {
        System.out.println("Running main method");
        Quarkus.run(args); 
    }
}

./gradlew build

./gradlew quarkusDev

### Output of `uname -a` or `ver`

Windows 10 Enterprise, 22H2, build 19045.4529

### Output of `java -version`

openjdk version "17.0.10" 2024-01-16 LTS OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS) OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.11.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.7 ------------------------------------------------------------  Build time:   2024-03-22 15:52:46 UTC Revision:     650af14d7653aa949fce5e886e685efc9cf97c10  Kotlin:       1.9.22 Groovy:       3.0.17 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          17.0.10 (Azul Systems, Inc. 17.0.10+7-LTS) OS:           Windows 10 10.0 amd64

**Comment by maxandersen** [comment]
this occurs by just adding `org.apache.camel.quarkus:camel-quarkus-grpc` - thus something in that is causing it.

**Comment by jamesnetherton** [comment]
I'll look into it. The eventual fix will be tracked in https://github.com/apache/camel-quarkus/issues/6239.

**Comment by Sanne** [comment]
Thanks @jamesnetherton , I see the linked issue was resolved. Should we close this one?

**Comment by jamesnetherton** [comment]
> Should we close this one?

Yes, it was fixed last year.

**Comment by geoand** [comment]
Thanks for the update
