### ISSUE TITLE
Netty finalizers load classes from closed class loaders

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#41607]
@franz1981 @cescoffier  I decided to create a specific issue for this one. I think it would have value for us to be able to fully control the Netty lifecycle instead of relying on finalizers.
Obviously, I have no idea how easy it would be.

This is the stacktrace we obtain:

```
Class loader QuarkusClassLoader:QuarkusUnitTest ClassLoader for NonAppEndpointsDisabledTest@75b45343 has been closed and may not be accessed anymore
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1389)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.ensureOpen(QuarkusClassLoader.java:730)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:509)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:504)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:556)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:504)
	at io.netty.util.internal.shaded.org.jctools.queues.ConcurrentCircularArrayQueue.isEmpty(ConcurrentCircularArrayQueue.java:71)
	at io.netty.util.internal.shaded.org.jctools.queues.MpscArrayQueue.isEmpty(MpscArrayQueue.java:207)
	at io.netty.buffer.PoolThreadCache.checkCacheMayLeak(PoolThreadCache.java:236)
	at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:227)
	at io.netty.buffer.PoolThreadCache$FreeOnFinalize.finalize(PoolThreadCache.java:500)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2297)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:88)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
```

This is logged when trying to load `IndexedQueueSizeUtil` to check if the queue is empty.

While it might sound like something that is not that problematic because it works, we actually have a lot of problems coming from the fact that we don't enforce the closing of CLs. When a `QuarkusClassLoader` is closed, we shouldn't try to load anything from it anymore.
This is not exactly easy and this is just one of the occurrences but I thought it would be better isolated in a specific issue.

**Comment by gsmet** [comment]
Note that this isn't the only issue I have with Netty.

I also get the following for some tests:

```
Class loader QuarkusClassLoader:QuarkusUnitTest ClassLoader for InvalidAttributesConfigTest@27494e46 has been closed and may not be accessed anymore
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1389)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.ensureOpen(QuarkusClassLoader.java:727)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:501)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:514)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:503)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:95)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:262)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by franz1981** [comment]
For the finalizer part I have sent a small fix - if you can give it a shot: https://github.com/franz1981/netty/tree/4.1_classloader_leak

**Comment by franz1981** [comment]
For the other one re scheduled tasks I think they are not cancelled, because https://github.com/netty/netty/pull/9580 shows that we are currently removing them on cancel.

**Comment by franz1981** [comment]
@gsmet FYI https://github.com/netty/netty/pull/14155#issuecomment-2203111706

If is accepted - it means an additional property to us :"(

**Comment by franz1981** [comment]
ok @gsmet https://github.com/netty/netty/pull/14155 is ready to go, so before is getting merged can you provide a feedback if it is working for your case? 
you need to set an additional sys property i.e. `-Dio.netty.allocator.disableCacheFinalizersForFastThreadThreadLocalThreads=true`

which disable finalizers for both jboss blocking thread pool and event loops (which should be both `FastThreadLocalThread`s afaik, @cescoffier am I right?)

**Comment by gsmet** [comment]
@franz1981 so the issue mentioned in the description looks solved by your PR.

Still wondering if we could improve the unrelated situation I was mentioning in this comment:
https://github.com/quarkusio/quarkus/issues/41607#issuecomment-2202876679

**Comment by gsmet** [comment]
@cescoffier do you have any idea of what could schedule these tasks and what they could be?

**Comment by gsmet** [comment]
@franz1981 @cescoffier I added some breakpoints and AFAICS the tasks are from the `GlobalEventExecutor`. And I see a lot of `cancelScheduledTasks()` called for the `NioEventLoop` but I haven't seen a call to the method for `GlobalEventExecutor`.

Now it's hard to debug as things pop up everywhere but I wonder if it could be an interesting lead?

**Comment by franz1981** [comment]
It seems that https://github.com/netty/netty/blob/ef2ed4e2cda6f764c661e24caccc833f9fd0b6e5/common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java#L55 is a singleton event loop, single threaded, which schedule a periodic task every each second to check if it should stop its thread, because is not used.
It is used as fallback executor, but i don't know why it cannot be unloaded...in theory after 1 second of inactivity, it should be stopped.
If you can, try debugging at https://github.com/netty/netty/blob/ef2ed4e2cda6f764c661e24caccc833f9fd0b6e5/common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java#L262 to print if there's some task which keep on getting run and prevent it to stop.

The executor itself should stop its single thread if there is nothing to do, see https://github.com/netty/netty/blob/ef2ed4e2cda6f764c661e24caccc833f9fd0b6e5/common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java#L278 (the `break` parts) - so we just need to understand why is not happening.
When it will happen, it should be just an empty shell to unload.

**Comment by franz1981** [comment]
The executor is not really "running": it create a single Thread to handle all tasks, which will stop after 1 second of inactivity (which is using a timer to detect it). While stopped it should be an empty shell, really.

**Comment by cescoffier** [comment]
I agree with Franz, we need to see why the executor is not shutdown nicely.

I don't know if possible (didn't check the code yet) but in dev mode, we could imagine using reflection to shutdown the executor properly. 

Do you have a way to debug / trigger this @gsmet, I can try to have a look tomorrow or Monday.

**Comment by gsmet** [comment]
@franz1981

From what I can see, you have the `GlobalEventExecutor#quietPeriodTask` and then a bunch of tasks coming from: https://github.com/netty/netty/blob/ef2ed4e2cda6f764c661e24caccc833f9fd0b6e5/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java#L500-L505

As for reproducing it, I'm trying to get my PR in but the reviewing guys are fighting... :)

**Comment by gsmet** [comment]
@cescoffier @franz1981 so to reproduce it, make sure you have built a tree that contains:
https://github.com/quarkusio/quarkus/pull/41692

Then you can run:

> ./mvnw clean verify -f extensions/opentelemetry/deployment/ -Dstart-containers -Dtest-containers -Dquarkus-log-access-to-closed-class-loaders -Dtest=InvalidAttributesConfigTest,NonAppEndpointsDisabledTest

You should see several stack traces similar to the following when the second test starts (you need two tests to see the issue):

```
Class loader QuarkusClassLoader:QuarkusUnitTest ClassLoader for InvalidAttributesConfigTest@4d157787 has been closed and may not be accessed anymore
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1389)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.ensureOpen(QuarkusClassLoader.java:728)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:514)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:509)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:509)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:95)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:262)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by cescoffier** [comment]
Coming back to this one. Will have a look this week.
