### ISSUE TITLE
Inject config properties into OpenApiFilter 

### ISSUE THREAD

**Issue by ChristianNavolskyi** [quarkusio/quarkus#41627]
### Describe the bug

When injecting a property into an OASFilter class, the service startup fails, because it cannot call an empty default constructor. 

### Expected behavior

Service starts normally with the correct values shown in Swagger-UI.

### Actual behavior

Startup fails with this error.

<details>
  <summary>Error message</summary>

``` bash
2024-07-02 16:02:26,161 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: io.smallrye.openapi.runtime.OpenApiRuntimeException: java.lang.NoSuchMethodException: com.arconsis.ExampleOpenApiFilter.<init>()
        at io.smallrye.openapi.runtime.OpenApiProcessor.uncheckedCall(OpenApiProcessor.java:293)
        at io.smallrye.openapi.runtime.OpenApiProcessor.lambda$newInstance$4(OpenApiProcessor.java:282)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.smallrye.openapi.runtime.OpenApiProcessor.newInstance(OpenApiProcessor.java:282)
        at io.smallrye.openapi.runtime.OpenApiProcessor.getFilter(OpenApiProcessor.java:267)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.filter(SmallRyeOpenApiProcessor.java:1271)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.prepareOpenApiDocument(SmallRyeOpenApiProcessor.java:1257)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.loadDocument(SmallRyeOpenApiProcessor.java:1166)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:895)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.lang.NoSuchMethodException: com.arconsis.ExampleOpenApiFilter.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3761)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
        at io.smallrye.openapi.runtime.OpenApiProcessor.lambda$newInstance$3(OpenApiProcessor.java:282)
        at io.smallrye.openapi.runtime.OpenApiProcessor.uncheckedCall(OpenApiProcessor.java:291)
        ... 18 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:58)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:113)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:435)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:56)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: io.smallrye.openapi.runtime.OpenApiRuntimeException: java.lang.NoSuchMethodException: com.arconsis.ExampleOpenApiFilter.<init>()
        at io.smallrye.openapi.runtime.OpenApiProcessor.uncheckedCall(OpenApiProcessor.java:293)
        at io.smallrye.openapi.runtime.OpenApiProcessor.lambda$newInstance$4(OpenApiProcessor.java:282)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.smallrye.openapi.runtime.OpenApiProcessor.newInstance(OpenApiProcessor.java:282)
        at io.smallrye.openapi.runtime.OpenApiProcessor.getFilter(OpenApiProcessor.java:267)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.filter(SmallRyeOpenApiProcessor.java:1271)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.prepareOpenApiDocument(SmallRyeOpenApiProcessor.java:1257)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.loadDocument(SmallRyeOpenApiProcessor.java:1166)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:895)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.lang.NoSuchMethodException: com.arconsis.ExampleOpenApiFilter.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3761)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
        at io.smallrye.openapi.runtime.OpenApiProcessor.lambda$newInstance$3(OpenApiProcessor.java:282)
        at io.smallrye.openapi.runtime.OpenApiProcessor.uncheckedCall(OpenApiProcessor.java:291)
        ... 18 more

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:327)
        ... 9 more
Caused by: io.smallrye.openapi.runtime.OpenApiRuntimeException: java.lang.NoSuchMethodException: com.arconsis.ExampleOpenApiFilter.<init>()
        at io.smallrye.openapi.runtime.OpenApiProcessor.uncheckedCall(OpenApiProcessor.java:293)
        at io.smallrye.openapi.runtime.OpenApiProcessor.lambda$newInstance$4(OpenApiProcessor.java:282)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.smallrye.openapi.runtime.OpenApiProcessor.newInstance(OpenApiProcessor.java:282)
        at io.smallrye.openapi.runtime.OpenApiProcessor.getFilter(OpenApiProcessor.java:267)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.filter(SmallRyeOpenApiProcessor.java:1271)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.prepareOpenApiDocument(SmallRyeOpenApiProcessor.java:1257)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.loadDocument(SmallRyeOpenApiProcessor.java:1166)
        at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:895)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.lang.NoSuchMethodException: com.arconsis.ExampleOpenApiFilter.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3761)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
        at io.smallrye.openapi.runtime.OpenApiProcessor.lambda$newInstance$3(OpenApiProcessor.java:282)
        at io.smallrye.openapi.runtime.OpenApiProcessor.uncheckedCall(OpenApiProcessor.java:291)
        ... 18 more
```
</details>

### How to Reproduce?

Start this minimal reproducer project: https://github.com/ChristianNavolskyi/quarkus-reproducer-openapi

To make it work, you can remove the constructor value from `ExampleOpenApiFilter` (obviously no workaround for the issue).

### Output of `uname -a` or `ver`

Darwin Christians-MBP.arconsis.lan 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:x

### Output of `java -version`

openjdk 21.0.2 2024-01-16 LTS OpenJDK Runtime Environment Corretto-21.0.2.13.1 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.2.13.1 (build 21.0.2+13-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.12.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 8.8 ------------------------------------------------------------  Build time:   2024-05-31 21:46:56 UTC Revision:     4bd1b3d3fc3f31db5a26eecb416a165b8cc36082  Kotlin:       1.9.22 Groovy:       3.0.21 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          21.0.2 (Amazon.com Inc. 21.0.2+13-LTS) OS:           Mac OS X 14.5 aarch64

**Comment by MikeEdgar** [comment]
Currently, `OASFilter` implementations are not supported as CDI beans.

**Comment by MikeEdgar** [comment]
@ChristianNavolskyi even though injection does not work, you can still get a `Config` instance in your filter and obtain properties that way.

```java
Config config = ConfigProvider.getConfig();
```

**Comment by ChristianNavolskyi** [comment]
I already had the feeling, that CDI wouldn't work in the OASFilter.
Didn't know the `ConfigProvider`, that's a great solution. Thanks @MikeEdgar!
