### ISSUE TITLE
Fix Reactive Resteasy to deal with request/responses without headers

### ISSUE THREAD

**Issue by marcelolemes** [quarkusio/quarkus#41639]
### Describe the bug

When making a request, and 'response' does not have 'header' when using org.jboss.resteasy.reactive.common.headers.HeaderUtils.java, an expection is returned.
Changing this [line](https://github.com/quarkusio/quarkus/blob/3.12/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/headers/HeaderUtil.java#L197) 

> from:
> headers.get
> to:
> headers.getFirst --> a overrided method from MultivaluedMap
> 

would resolve this.

### Expected behavior

Return null value.

### Actual behavior

A NullPointerException, like this
```
ERROR: Mutiny had to drop the following exception
java.lang.NullPointerException: Cannot invoke "jakarta.ws.rs.core.MultivaluedMap.get(Object)" because "headers" is null
        at org.jboss.resteasy.reactive.common.headers.HeaderUtil.getHeaderString(HeaderUtil.java:197)
        at org.jboss.resteasy.reactive.client.impl.ClientResponseContextImpl.getHeaderString(ClientResponseContextImpl.java:74)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:21)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:10)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:229)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.performRequestInternal(AsyncInvokerImpl.java:285)
        at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.performRequestInternal(AsyncInvokerImpl.java:275)
        at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.method(AsyncInvokerImpl.java:215)
        at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:324)
```

![image](https://github.com/quarkusio/quarkus/assets/8428918/f99655b3-8761-4080-934e-a552b2e7be38)

### How to Reproduce?

In quarkus/resteasy version 3.12 or above. Try process a HTTP response whitout headers.
Try to search for a specific header

**Comment by geoand** [comment]
Can you please attach a sample I can use to understand the exact conditions under which this happens?
