### ISSUE TITLE
graceful shutdown NPE when using kafka consumer with stork

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#41658]
### Describe the bug

I have a kafka consumer calling a rest service using a stork url.
under reasonable load, the rest call fails with a NPE in the `StorkClientRequestFilter`: `"io.smallrye.stork.Stork.getInstance()" is null`
it sounds like the shutdown of the application does not wait for in flight messages to finish processing, before shutting down parts of the application.
the integrity of data is preserved, but some messages are sent to the dead letter topic, delaying our ability to quickly process them, when there is actually another replica that could have processed them.

### Expected behavior

in a ideal situation, upon shutdown, we should have: 
 - do not accept new workload
 - let in flight activity finish (schedulers, rest endpoints, messaging consumers)
 - shut down all parts of the application
 - exit

### Actual behavior

we see the following exception:
```
2024-07-03 10:37:15,144 ERROR [org.jbo.res.rea.cli.imp.StorkClientRequestFilter] (quarkus-virtual-thread-10) Error selecting service instance for serviceName: greeting-service [Error Occurred After Shutdown]: java.lang.NullPointerException: Cannot invoke "io.smallrye.stork.Stork.getService(String)" because the return value of "io.smallrye.stork.Stork.getInstance()" is null
        at org.jboss.resteasy.reactive.client.impl.StorkClientRequestFilter.filter(StorkClientRequestFilter.java:38)
        at org.jboss.resteasy.reactive.client.spi.ResteasyReactiveClientRequestFilter.filter(ResteasyReactiveClientRequestFilter.java:21)
        at org.jboss.resteasy.reactive.client.handlers.ClientRequestFilterRestHandler.handle(ClientRequestFilterRestHandler.java:25)
        at org.jboss.resteasy.reactive.client.handlers.ClientRequestFilterRestHandler.handle(ClientRequestFilterRestHandler.java:10)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:231)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.performRequestInternal(AsyncInvokerImpl.java:285)
        at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.performRequestInternal(AsyncInvokerImpl.java:275)
        at org.jboss.resteasy.reactive.client.impl.AsyncInvokerImpl.method(AsyncInvokerImpl.java:215)
        at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:313)
        at org.acme.IGreetingResource$$QuarkusRestClientInterface.hello(Unknown Source)
        at org.acme.IGreetingResource$$CDIWrapper.hello(Unknown Source)
        at org.acme.IGreetingResource$$CDIWrapper_ClientProxy.hello(Unknown Source)
        at org.acme.PriceConsumer.consume(PriceConsumer.java:29)
        at org.acme.PriceConsumer_ClientProxy.consume(Unknown Source)
        at org.acme.PriceConsumer_SmallRyeMessagingInvoker_consume_ff7ab742c6cdb0956d1e3afc1d8ed7fd43c75ad0.invoke(Unknown Source)
        at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeBlocking$15(AbstractMediator.java:190)
        at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
        at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
```
and messages may be sent to the DLT.

### How to Reproduce?

create a new application with additional deps:
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-messaging-kafka</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-stork</artifactId>
    </dependency>
    <dependency>
      <groupId>io.smallrye.stork</groupId>
      <artifactId>stork-service-discovery-static-list</artifactId>
    </dependency>
```

add properties file:
```
quarkus.http.port=18080

mp.messaging.incoming.prices.connector=smallrye-kafka
mp.messaging.outgoing.prices-out.connector=smallrye-kafka

mp.messaging.incoming.prices.topic=mytopic
mp.messaging.outgoing.prices-out.topic=mytopic

quarkus.rest-client.greeting.url=stork://greeting-service
#quarkus.rest-client.greeting.url=http://localhost:18080

quarkus.stork.greeting-service.service-discovery.type=static
quarkus.stork.greeting-service.service-discovery.address-list=localhost:18080
quarkus.stork.greeting-service.load-balancer.type=round-robin
```

a producer:
```
@ApplicationScoped
public class KafkaPriceProducer {

    private final Random random = new Random();

    @Outgoing("prices-out")
    public Multi<Double> generate() {
        // Build an infinite stream of random prices
        // It emits a price every second
        return Multi.createFrom().ticks().every(Duration.ofMillis(100))
                .map(x -> random.nextDouble());
    }
}
```

a consumer:
```
@ApplicationScoped
public class PriceConsumer {

    Logger log = LoggerFactory.getLogger(PriceConsumer.class);

    @Inject
    @RestClient
    IGreetingResource greetingResource;

    @Incoming("prices")
    @RunOnVirtualThread
    @Blocking(ordered = false)
    public void consume(double price) throws InterruptedException {
        log.info("receive " + price);
        Thread.sleep(1000);
        log.info("greeting => " + greetingResource.hello());
    }

}

```

start the application with `quarkus:dev`
after startup, press `s`
you should see multiple exceptions.

### Quarkus version or git rev

3.12

**Comment by cescoffier** [comment]
FTR, @ozangunalp is still working on it.

**Comment by vsevel** [comment]
@ozangunalp  I tried the documented reproducer with Quarkus `3.22.2`
the original documented NPE on stork is not there anymore.
I noticed however there was a bizarre stack trace with a NPE `java.lang.NullPointerException: Cannot invoke "io.smallrye.context.SmallRyeContextManager.defaultThreadContext()" because the return value of "io.smallrye.context.SmallRyeContextManagerProvider.getManager()" is null` plus a `java.lang.InterruptedException`.
I am not sure I understand the sequence of action.
in the reproducer I do have a `Thread.sleep`, which is supposed to increase the likelyhood of seeing the original issue.
it seems that the quarkus shutdown process is doing an interrupt on threads currently processing requests.
that is a surprise to me. I would expect to let the in flight requests continue as normal, and interrupt them only after some time, if they have not finished normally (e.g. 30 seconds).
since my sleep is only 1 sec in length, that means the interrupt is doing right away.

so in short, the original issue is solved, but I believe there is room for improvement in the current graceful shutdown implementation.

```
2025-05-12 16:16:00,530 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Quarkus Terminal Reader) Restarting as requested by the user.
2025-05-12 16:16:00,620 INFO  [io.sma.rea.mes.kafka] (smallrye-kafka-consumer-thread-0) SRMSG18224: Executing consumer revoked re-balance listener for group 'reproducer-graceful-kafka'
2025-05-12 16:16:01,236 INFO  [io.quarkus] (Quarkus Main Thread) reproducer-graceful-kafka stopped in 0.705s
2025-05-12 16:16:01,239 ERROR [io.sma.rea.mes.kafka] (quarkus-virtual-thread-245) SRMSG18203: A message sent to channel `prices` has been nacked, fail-stop [Error Occurred After Shutdown]
2025-05-12 16:16:01,239 ERROR [io.sma.rea.mes.kafka] (quarkus-virtual-thread-247) SRMSG18203: A message sent to channel `prices` has been nacked, fail-stop [Error Occurred After Shutdown]
2025-05-12 16:16:01,239 WARN  [io.sma.rea.mes.kafka] (quarkus-virtual-thread-245) SRMSG18228: A failure has been reported for Kafka topics '[mytopic]'

Exception in PriceConsumer.java:30
          28      public void consume(double price) throws InterruptedException {
          29          // log.info("receive " + price);
        ? 30          Thread.sleep(1000);
          31          // log.info("greeting => " + greetingResource.hello());
          32          int count = counter.incrementAndGet();: io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
        [Exception 0] java.lang.InterruptedException
        [Exception 1] java.lang.NullPointerException: Cannot invoke "io.smallrye.context.SmallRyeContextManager.defaultThreadContext()" because the return value of "io.smallrye.context.SmallRyeContextManagerProvider.getManager()" is null
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:89)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onFailure(UniOnItemOrFailureFlatMap.java:65)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:28)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)
        at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry$ContextPreservingRunnable.run(QuarkusWorkerPoolRegistry.java:150)
        at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
        Suppressed: java.lang.NullPointerException: Cannot invoke "io.smallrye.context.SmallRyeContextManager.defaultThreadContext()" because the return value of "io.smallrye.context.SmallRyeContextManagerProvider.getManager()" is null
                at io.smallrye.context.SmallRyeThreadContext.getCurrentThreadContextOrDefaultContexts(SmallRyeThreadContext.java:160)
                at io.smallrye.mutiny.context.DefaultContextPropagationInterceptor.getThreadContext(DefaultContextPropagationInterceptor.java:12)
                at io.smallrye.mutiny.context.BaseContextPropagationInterceptor.decorate(BaseContextPropagationInterceptor.java:33)
                at io.smallrye.mutiny.infrastructure.Infrastructure.decorate(Infrastructure.java:157)
                at io.smallrye.mutiny.groups.UniCreate.emitter(UniCreate.java:420)
                at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry.lambda$runOnVirtualThread$8(QuarkusWorkerPoolRegistry.java:109)
                at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
                at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
                ... 9 more
Caused by: java.lang.InterruptedException
        at java.base/java.lang.VirtualThread.sleepNanos(VirtualThread.java:809)
        at java.base/java.lang.Thread.sleep(Thread.java:507)
        at org.acme.PriceConsumer.consume(PriceConsumer.java:30)
        at org.acme.PriceConsumer_ClientProxy.consume(Unknown Source)
        at org.acme.PriceConsumer_SmallRyeMessagingInvoker_consume_ff7ab742c6cdb0956d1e3afc1d8ed7fd43c75ad0.invoke(Unknown Source)
        at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeBlocking$15(AbstractMediator.java:194)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
        ... 6 more

2025-05-12 16:16:01,239 WARN  [io.sma.rea.mes.kafka] (quarkus-virtual-thread-247) SRMSG18228: A failure has been reported for Kafka topics '[mytopic]'

Exception in PriceConsumer.java:30
          28      public void consume(double price) throws InterruptedException {
          29          // log.info("receive " + price);
        ? 30          Thread.sleep(1000);
          31          // log.info("greeting => " + greetingResource.hello());
          32          int count = counter.incrementAndGet();: io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
        [Exception 0] java.lang.InterruptedException
        [Exception 1] java.lang.NullPointerException: Cannot invoke "io.smallrye.context.SmallRyeContextManager.defaultThreadContext()" because the return value of "io.smallrye.context.SmallRyeContextManagerProvider.getManager()" is null
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:89)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onFailure(UniOnItemOrFailureFlatMap.java:65)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:28)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)
        at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry$ContextPreservingRunnable.run(QuarkusWorkerPoolRegistry.java:150)
        at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
        Suppressed: java.lang.NullPointerException: Cannot invoke "io.smallrye.context.SmallRyeContextManager.defaultThreadContext()" because the return value of "io.smallrye.context.SmallRyeContextManagerProvider.getManager()" is null
                at io.smallrye.context.SmallRyeThreadContext.getCurrentThreadContextOrDefaultContexts(SmallRyeThreadContext.java:160)
                at io.smallrye.mutiny.context.DefaultContextPropagationInterceptor.getThreadContext(DefaultContextPropagationInterceptor.java:12)
                at io.smallrye.mutiny.context.BaseContextPropagationInterceptor.decorate(BaseContextPropagationInterceptor.java:33)
                at io.smallrye.mutiny.infrastructure.Infrastructure.decorate(Infrastructure.java:157)
                at io.smallrye.mutiny.groups.UniCreate.emitter(UniCreate.java:420)
                at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry.lambda$runOnVirtualThread$8(QuarkusWorkerPoolRegistry.java:109)
                at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
                at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
                ... 9 more
Caused by: java.lang.InterruptedException
        at java.base/java.lang.VirtualThread.sleepNanos(VirtualThread.java:809)
        at java.base/java.lang.Thread.sleep(Thread.java:507)
        at org.acme.PriceConsumer.consume(PriceConsumer.java:30)
        at org.acme.PriceConsumer_ClientProxy.consume(Unknown Source)
        at org.acme.PriceConsumer_SmallRyeMessagingInvoker_consume_ff7ab742c6cdb0956d1e3afc1d8ed7fd43c75ad0.invoke(Unknown Source)
        at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeBlocking$15(AbstractMediator.java:194)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
        ... 6 more

2025-05-12 16:16:01,239 ERROR [io.sma.rea.mes.kafka] (quarkus-virtual-thread-246) SRMSG18203: A message sent to channel `prices` has been nacked, fail-stop [Error Occurred After Shutdown]
2025-05-12 16:16:01,239 WARN  [io.sma.rea.mes.kafka] (quarkus-virtual-thread-246) SRMSG18228: A failure has been reported for Kafka topics '[mytopic]'

Exception in PriceConsumer.java:30
          28      public void consume(double price) throws InterruptedException {
          29          // log.info("receive " + price);
        ? 30          Thread.sleep(1000);
          31          // log.info("greeting => " + greetingResource.hello());
          32          int count = counter.incrementAndGet();: io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
        [Exception 0] java.lang.InterruptedException
        [Exception 1] java.lang.NullPointerException: Cannot invoke "io.smallrye.context.SmallRyeContextManager.defaultThreadContext()" because the return value of "io.smallrye.context.SmallRyeContextManagerProvider.getManager()" is null
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:89)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onFailure(UniOnItemOrFailureFlatMap.java:65)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:28)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)
        at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry$ContextPreservingRunnable.run(QuarkusWorkerPoolRegistry.java:150)
        at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
        Suppressed: java.lang.NullPointerException: Cannot invoke "io.smallrye.context.SmallRyeContextManager.defaultThreadContext()" because the return value of "io.smallrye.context.SmallRyeContextManagerProvider.getManager()" is null
                at io.smallrye.context.SmallRyeThreadContext.getCurrentThreadContextOrDefaultContexts(SmallRyeThreadContext.java:160)
                at io.smallrye.mutiny.context.DefaultContextPropagationInterceptor.getThreadContext(DefaultContextPropagationInterceptor.java:12)
                at io.smallrye.mutiny.context.BaseContextPropagationInterceptor.decorate(BaseContextPropagationInterceptor.java:33)
                at io.smallrye.mutiny.infrastructure.Infrastructure.decorate(Infrastructure.java:157)
                at io.smallrye.mutiny.groups.UniCreate.emitter(UniCreate.java:420)
                at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry.lambda$runOnVirtualThread$8(QuarkusWorkerPoolRegistry.java:109)
                at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
                at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
                ... 9 more
Caused by: java.lang.InterruptedException
        at java.base/java.lang.VirtualThread.sleepNanos(VirtualThread.java:809)
        at java.base/java.lang.Thread.sleep(Thread.java:507)
        at org.acme.PriceConsumer.consume(PriceConsumer.java:30)
        at org.acme.PriceConsumer_ClientProxy.consume(Unknown Source)
        at org.acme.PriceConsumer_SmallRyeMessagingInvoker_consume_ff7ab742c6cdb0956d1e3afc1d8ed7fd43c75ad0.invoke(Unknown Source)
        at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeBlocking$15(AbstractMediator.java:194)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
        ... 6 more

2025-05-12 16:16:01,239 ERROR [io.sma.rea.mes.kafka] (quarkus-virtual-thread-248) SRMSG18203: A message sent to channel `prices` has been nacked, fail-stop [Error Occurred After Shutdown]
2025-05-12 16:16:01,239 WARN  [io.sma.rea.mes.kafka] (quarkus-virtual-thread-248) SRMSG18228: A failure has been reported for Kafka topics '[mytopic]'

Exception in PriceConsumer.java:30
          28      public void consume(double price) throws InterruptedException {
          29          // log.info("receive " + price);
        ? 30          Thread.sleep(1000);
          31          // log.info("greeting => " + greetingResource.hello());
          32          int count = counter.incrementAndGet();: io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
        [Exception 0] java.lang.InterruptedException
        [Exception 1] java.lang.NullPointerException: Cannot invoke "io.smallrye.context.SmallRyeContextManager.defaultThreadContext()" because the return value of "io.smallrye.context.SmallRyeContextManagerProvider.getManager()" is null
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:89)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onFailure(UniOnItemOrFailureFlatMap.java:65)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:28)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)
        at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
        at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry$ContextPreservingRunnable.run(QuarkusWorkerPoolRegistry.java:150)
        at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
        Suppressed: java.lang.NullPointerException: Cannot invoke "io.smallrye.context.SmallRyeContextManager.defaultThreadContext()" because the return value of "io.smallrye.context.SmallRyeContextManagerProvider.getManager()" is null
                at io.smallrye.context.SmallRyeThreadContext.getCurrentThreadContextOrDefaultContexts(SmallRyeThreadContext.java:160)
                at io.smallrye.mutiny.context.DefaultContextPropagationInterceptor.getThreadContext(DefaultContextPropagationInterceptor.java:12)
                at io.smallrye.mutiny.context.BaseContextPropagationInterceptor.decorate(BaseContextPropagationInterceptor.java:33)
                at io.smallrye.mutiny.infrastructure.Infrastructure.decorate(Infrastructure.java:157)
                at io.smallrye.mutiny.groups.UniCreate.emitter(UniCreate.java:420)
                at io.quarkus.smallrye.reactivemessaging.runtime.QuarkusWorkerPoolRegistry.lambda$runOnVirtualThread$8(QuarkusWorkerPoolRegistry.java:109)
                at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
                at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
                ... 9 more
Caused by: java.lang.InterruptedException
        at java.base/java.lang.VirtualThread.sleepNanos(VirtualThread.java:809)
        at java.base/java.lang.Thread.sleep(Thread.java:507)
        at org.acme.PriceConsumer.consume(PriceConsumer.java:30)
        at org.acme.PriceConsumer_ClientProxy.consume(Unknown Source)
        at org.acme.PriceConsumer_SmallRyeMessagingInvoker_consume_ff7ab742c6cdb0956d1e3afc1d8ed7fd43c75ad0.invoke(Unknown Source)
        at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeBlocking$15(AbstractMediator.java:194)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromDeferredSupplier.subscribe(UniCreateFromDeferredSupplier.java:25)
        ... 6 more

```

**Comment by ozangunalp** [comment]
@vsevel, thank you for reporting this. Indeed, this happens because the context manager is closed and nulled while the executors still accept work. We're working on a fix for this.
