### ISSUE TITLE
Dev mode always complaining about module-info not being supported

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#41669]
When starting a simple app in dev mode, starting continuous testing and then updating a class, we end up with this message in the logs:

> 2024-07-03 18:49:23,984 INFO  [io.qua.dep.dev.fil.StaticFileManager] (Quarkus Test Watcher - 0) Ignoring module-info.java in dev mode, set the `quarkus.live-reload.ignore-module-info` property to `false` in your project descriptor (`pom.xml` or `build.gradle`) to disable this behavior.

While I understand why we added this message, my understanding was that it would be displayed when we actually had a `module-info` around, not for every apps.
This happens every time, even when changing a simple Java file and not having a `module-info` around.

Is it really expected?

Stack trace is:

```
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:2209)
	at io.quarkus.deployment.dev.filesystem.StaticFileManager.getJavaFileForInput(StaticFileManager.java:37)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.getJavaFileForInput(ClientCodeWrapper.java:278)
	at jdk.compiler/com.sun.tools.javac.main.DelegatingJavaFileManager.getJavaFileForInput(DelegatingJavaFileManager.java:109)
	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.getModuleInfoFromLocation(ModuleFinder.java:286)
	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findSingleModule(ModuleFinder.java:201)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:459)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:268)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.initModules(Modules.java:234)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.initModules(JavaCompiler.java:1051)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:949)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at io.quarkus.deployment.dev.JavaCompilationProvider.compile(JavaCompilationProvider.java:104)
	at io.quarkus.deployment.dev.QuarkusCompiler.compile(QuarkusCompiler.java:232)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:775)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.periodicTestCompile(RuntimeUpdatesProcessor.java:330)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor$2.handleChanges(RuntimeUpdatesProcessor.java:246)
	at io.quarkus.deployment.dev.filesystem.watch.WatchServiceFileSystemWatcher.invokeCallback(WatchServiceFileSystemWatcher.java:247)
	at io.quarkus.deployment.dev.filesystem.watch.WatchServiceFileSystemWatcher.run(WatchServiceFileSystemWatcher.java:146)
```

/cc @cescoffier @dmlloyd @aloubyansky @geoand

**Comment by dmlloyd** [comment]
Maybe something like #41670?
