### ISSUE TITLE
Company Nexus ignored when running tests in Dev UI after starting Quarkus through bundled IntelliJ plugin

### ISSUE THREAD

**Issue by RiverOmega** [quarkusio/quarkus#41706]
### Describe the bug

Hello!

Running `mvn quarkus:dev` in terminal and navigating to the Dev UI to activate Continuous Testing works fine.

However, starting the same application via bundled IntelliJ Quarkus Plugin -> Activate Continuous Testing in Dev UI -> Throws exception:

```text
2024-07-05 10:35:23,799 ERROR [io.qua.test] (executor-thread-5) Failed to create compiler, runtime compilation will be unavailable: java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for REDACTED-app::jar:1.0.0-SNAPSHOTnull
	at io.quarkus.deployment.dev.testing.TestSupport.init(TestSupport.java:276)
	at io.quarkus.deployment.dev.testing.TestSupport.start(TestSupport.java:136)
	at io.quarkus.devui.deployment.menu.ContinuousTestingProcessor.lambda$registerStartMethod$0(ContinuousTestingProcessor.java:96)
	at io.quarkus.dev.console.DevConsoleManager.invoke(DevConsoleManager.java:135)
	at io.quarkus.devui.runtime.continuoustesting.ContinuousTestingJsonRPCService.invokeAction(ContinuousTestingJsonRPCService.java:103)
	at io.quarkus.devui.runtime.continuoustesting.ContinuousTestingJsonRPCService.start(ContinuousTestingJsonRPCService.java:64)
	at io.quarkus.devui.runtime.continuoustesting.ContinuousTestingJsonRPCService_ClientProxy.start(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.devui.runtime.comms.JsonRpcRouter.lambda$invoke$0(JsonRpcRouter.java:98)
	at io.smallrye.mutiny.unchecked.UncheckedSupplier.lambda$toSupplier$0(UncheckedSupplier.java:41)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for REDACTED-app::jar:1.0.0-SNAPSHOTnull
	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:297)
	at io.quarkus.deployment.dev.testing.TestSupport.init(TestSupport.java:213)
	... 21 more
Caused by: io.quarkus.bootstrap.resolver.maven.BootstrapMavenException: Failed to resolve dependencies for REDACTED-app:jar:1.0.0-SNAPSHOT
	at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyTreeResolver.resolveRuntimeDeps(ApplicationDependencyTreeResolver.java:394)
	at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyTreeResolver.resolve(ApplicationDependencyTreeResolver.java:145)
	at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.buildAppModel(BootstrapAppModelResolver.java:337)
	at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.doResolveModel(BootstrapAppModelResolver.java:288)
	at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveManagedModel(BootstrapAppModelResolver.java:168)
	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:283)
	... 22 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: REDACTED-lib:jar:1.0.0 (present, but unavailable): Could not find artifact REDACTED-lib:jar:1.0.0 in central (https://repo.maven.apache.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:365)
	at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyTreeResolver.resolveRuntimeDeps(ApplicationDependencyTreeResolver.java:389)
	... 27 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: REDACTED-lib:jar:1.0.0 (present, but unavailable): Could not find artifact REDACTED-lib:jar:1.0.0 in central (https://repo.maven.apache.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:473)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:353)
	... 28 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact REDACTED-lib:jar:1.0.0 in central (https://repo.maven.apache.org/maven2)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:42)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:417)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:260)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:537)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449)
	... 30 more
```

My MAVEN_HOME points to an installation where the company nexus mirrors are configured, but I get the feeling that these settings aren't used when starting Quarkus through IntelliJ.

### Expected behavior

Test should run similarly when starting Quarkus through IntelliJ, as they do when starting Quarkus through `mvn quarkus:dev`

### Actual behavior

Quarkus throws exceptions (see above), due to unresolved dependencies.

### How to Reproduce?

1. Add company Nexus mirror to MAVEN_HOME/conf/settings.xml
2. Start Quarkus via IntelliJ Plugin
3. Write test which depends on code in an artifact supplied by company Nexus
4. Activate Test Mode in Dev UI to run the test

### Output of `uname -a` or `ver`

OMITTED 

### Output of `java -version`

java version "21" 2023-09-19 LTS Java(TM) SE Runtime Environment (build 21+35-LTS-2513) Java HotSpot(TM) 64-Bit Server VM (build 21+35-LTS-2513, mixed mode, sharing)

### Quarkus version or git rev

3.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9) Maven home: C:\opt\apache-maven-3.9.4 Java version: 21, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-21 Default locale: en_GB, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by phillip-kruger** [comment]
@cescoffier I think this is a IDE plugin issue ? w.d.y.t ?

**Comment by cescoffier** [comment]
Yes, I also believe it's an IDE issue. 

Please report it to the Indellij plugin team.

**Comment by RiverOmega** [comment]
Alright, I'll do that. I'll close the issue for now. Thanks guys!

**Comment by gsmet** [comment]
@aloubyansky does it ring a bell? Because I'm worried the fine people at Intellij won't have a clue of what's going on. Maybe the IDE run is missing some context but maybe we should try to pinpoint what's missing here?
