### ISSUE TITLE
KogitoDevModeIT sometimes fails

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#4189]
I saw the issue [here](https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=8414&view=logs&jobId=b20e6b61-15e8-51de-c701-d87903f753af) but I also vaguely remember seeing it in the past.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.kogito.maven.it.KogitoDevModeIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 73.891 s <<< FAILURE! - in io.quarkus.kogito.maven.it.KogitoDevModeIT
[ERROR] testThatTheKogitoApplicationRuns  Time elapsed: 73.86 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with io.quarkus.kogito.maven.it.KogitoDevModeIT was not fulfilled within 1 minutes.
	at io.quarkus.kogito.maven.it.KogitoDevModeIT.testThatTheKogitoApplicationRuns(KogitoDevModeIT.java:22)
Caused by: java.util.concurrent.TimeoutException
	at io.quarkus.kogito.maven.it.KogitoDevModeIT.testThatTheKogitoApplicationRuns(KogitoDevModeIT.java:22)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   KogitoDevModeIT.testThatTheKogitoApplicationRuns:22 � ConditionTimeout Conditi...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by gsmet** [comment]
Has been fixed a while ago.
