### ISSUE TITLE
PostgresQL IT tests failing with Mandrel 24.2 (for JDK 24)

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#41917]
### Describe the bug

Integration tests:

* JPA - PostgreSQL
* JPA - PostgreSQL with XML 

fail with the latest mandrel builds (for JDK 24)

### Expected behavior

Tests should pass

### Actual behavior

```
 Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.111 s <<< FAILURE! -- in io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase
Error:  io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative -- Time elapsed: 0.083 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Type 'org.postgresql.jdbc.PgSQLXML' was not found in the report in target/quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-native-image-source-jar/reports/used_classes_quarkus-integration-test-jpa-postgresql-999-SNAPSHOT-runner_20240716_005849.txt
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at io.quarkus.test.junit.nativeimage.ClassInclusionReport.assertContains(ClassInclusionReport.java:59)
	at io.quarkus.test.junit.nativeimage.ClassInclusionReport.assertContains(ClassInclusionReport.java:49)
	at io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase.verifyJdkXmlParsersHavebeenEcludedFromNative(JPAFunctionalityInGraalITCase.java:21)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:812)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

See https://github.com/graalvm/mandrel/actions/runs/9948658053/job/27484292339

### How to Reproduce?

```
./mvnw -Dnative -pl integration-tests/jpa-postgresql-withxml,integration-tests/jpa-postgresql -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean package
```

**Comment by zakkak** [comment]
Bisecting indicated that the regression was introduced by https://github.com/oracle/graal/commit/1d769c7ffe3fec32a6738ba96d803bf06cf9f444

Looking into it...
