### ISSUE TITLE
[Hibernate Reactive Panache] Concurrent request - HR000069: Detected use of the reactive Session from a different Thread

### ISSUE THREAD

**Issue by ZetalyAlexandre** [quarkusio/quarkus#41945]
### Describe the bug

Concurrent calls to the same api performing a delete in the database sometimes cause an anomaly “HR000069: Detected use of the reactive Session from a different Thread”. All calls are on different elements.
This problem does not occur when requests are sequential.

Stacktrace example: 
```
2024-07-17 10:29:06,501 ERROR [org.acm.hib.orm.pan.FruitResource] (vert.x-eventloop-thread-2) Failed to handle request: org.hibernate.HibernateException: java.lang.IllegalStateException: HR000069: Detected use of the reactive Se
ssion from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread [163]: 'vert.x-eventloop-thread-2' current Thread [162]: 'vert.x-eventloop-thread-1' 
        at org.hibernate.reactive.session.impl.ReactiveExceptionConverter.convert(ReactiveExceptionConverter.java:28)
        at org.hibernate.reactive.session.impl.ReactiveSessionImpl.lambda$doFlush$27(ReactiveSessionImpl.java:994)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.unroll(AsyncTrampoline.java:131)
        at org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.lambda$unroll$0(AsyncTrampoline.java:126)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.hibernate.reactive.persister.entity.mutation.ReactiveDeleteCoordinator.complete(ReactiveDeleteCoordinator.java:198)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:536)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:88)
        at io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:32)
        at io.vertx.core.Promise.complete(Promise.java:66)
        at io.vertx.core.Promise.handle(Promise.java:51)
        at io.vertx.core.Promise.handle(Promise.java:29)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
        at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:86)
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:184)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
        at io.vertx.sqlclient.impl.command.CommandResponse.fire(CommandResponse.java:46)
        at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:325)
        at io.vertx.pgclient.impl.PgSocketConnection.handleMessage(PgSocketConnection.java:118)
        at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:138)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
        at io.vertx.core.impl.ContextBase.emit(ContextBase.java:297)
        at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:378)
        at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:100)
        at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:139)
        at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:237)
        at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:96)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread 
[163]: 'vert.x-eventloop-thread-2' current Thread [162]: 'vert.x-eventloop-thread-1'
        at org.hibernate.reactive.common.InternalStateAssertions.assertCurrentThreadMatches(InternalStateAssertions.java:46)
        at org.hibernate.reactive.session.impl.ReactiveSessionImpl.threadCheck(ReactiveSessionImpl.java:183)
        at org.hibernate.reactive.session.impl.ReactiveSessionImpl.checkOpen(ReactiveSessionImpl.java:1670)
        at org.hibernate.internal.AbstractSharedSessionContract.checkOpenOrWaitingForAutoClose(AbstractSharedSessionContract.java:447)
        at org.hibernate.internal.SessionImpl.checkOpenOrWaitingForAutoClose(SessionImpl.java:616)
        at org.hibernate.internal.SessigetPersistenceContext(SessionImpl.java:1825)
        at org.hibernate.reactive.event.impl.AbstractReactiveFlushingEventListener.lambda$performExecutions$0(AbstractReactiveFlushingEventListener.java:65)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        ... 74 more
```

### Expected behavior

No exceptions should be thrown, all calls should work.

### Actual behavior

An exception is sometimes raised with the following error message: “HR000069: Detected use of the reactive Session from a different Thread”.

### How to Reproduce?

Project to reproduce: : [hibernate-reactive-panache-quickstart.zip](https://github.com/user-attachments/files/16262580/hibernate-reactive-panache-quickstart.zip)

I used the hibernate-reactive-panache-quickstart example.
I've only added a “Remove all” button to the index.html file. This makes a call to the delete api, starting from the fruit list. There are no changes in the quarkus part.

JS function added:
``` javascript
$scope.removeAll = function() {
   $scope.fruits.forEach(fruit => $scope.remove(fruit));
}
```

Launch the project, access the page and use the “Remove all” option. The number of errors may vary

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17

### Quarkus version or git rev

3.2.12.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by DavideD** [comment]
Yes, this is a limitation we have at the moment. The Hibernate session does not support concurrent calls.
We mention this in the Hibernate Reactive documentation: https://staging.hibernate.org/reactive/documentation/2.3/reference/html_single/#_sessions_and_vert_x_contexts

**Comment by DavideD** [comment]
You should have a different session for each request.
Quarkus should take care of it.

What stopping you from adding a new access point in `FruitResource`?
```java
    @DELETE
    public Uni<Response> deleteAll() {
        return Panache.withTransaction( () -> Panache.executeUpdate( "delete from Fruit" )
                .map( deleted -> Response
                        .ok( "Number of fruits deleted: " + deleted )
                        .build() ) );
    }
```

PS:
You should be able to write this:
```java
   @DELETE
   public Uni<Response> deleteAll() {
       return Panache.withTransaction(Fruit::deleteAll)
               .map(deleted -> Response.ok("Number of fruits deleted: " + deleted).build());
   }
```

But I've found this bug: https://github.com/quarkusio/quarkus/issues/41967

**Comment by ZetalyAlexandre** [comment]
I've done more test and I do not have this issue when I try to mass update or mass create. So it's very much linked to delete only. Nothing prevent me to add a "mass" delete endpoint. We've already found a workaround for our particular application. Unit deletions by several users are rare in our application, so this shouldn't be a problem for the time being.

I was just afraid that this case could also arise with mass creation or modification, which doesn't seem to be the case.

**Comment by ZetalyAlexandre** [comment]
It seems that I do not have the issue if I replace:
```java
    @DELETE
    @Path("{id}")
    public Uni<Response> delete(Long id) {
        return Panache.withTransaction(() -> Fruit.deleteById(id))
                .map(deleted -> deleted
                        ? Response.ok().status(NO_CONTENT).build()
                        : Response.ok().status(NOT_FOUND).build());
    }
```
by
```java
    @DELETE
    @Path("{id}")
    public Uni<Response> delete(Long id) {
        return Panache.withTransaction(() -> Panache.executeUpdate("delete from Fruit where id=?1", id))
                .map(deleted -> deleted > 0
                        ? Response.ok().status(NO_CONTENT).build()
                        : Response.ok().status(NOT_FOUND).build());
    }
```

**Comment by DavideD** [comment]
If the session is not re-created each time, it can definitely happen in all situations, even if you don't see any error now. Simply because the Session is not designed to be used in parallel.

That said, maybe I was a bit too quick in looking at this issue. I will have a second look.

That said, I think that adding a new Rest point to `FruitResource` is a better solution because it will keep all the actual logic in one place.

**Comment by DavideD** [comment]
OK, nevermind, it doesn't seem like it's using the same session, so it's something else that's causing the error

**Comment by ZetalyAlexandre** [comment]
This is very strange, as I've done the following tests (one call per create/update/delete, all done with concurrency):
* Create 100 --> No error
* Update 100 --> No error
* Delete 5 --> Error HR000069 for 1 or 2 (may vary)
* Delete 5 (code updated with my last comment) --> No error
* Delete 100 (code updated with my last comment) --> No error

This only happens when using “Fruit.deleteById(id)” with only 5 simultaneous requests, but has never happened for the others...

I'll let you work on it.
Thanks for your responsiveness.

**Comment by MaximeGil** [comment]
Hello,

@DavideD Do you think it's related to this old Zulip discussion ? https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Reactive.20exception.20.22Detected.20use.20of.20the.20reactive.2E.2E.22/near/380321402

That's why I had to downgrade in 2.x in the past. I didn't want to take any chances, despite all our tests before going live. However, this problem is very important to me because it happened again today...

**Comment by DavideD** [comment]
I'm not sure, but thanks for reminding me. I will check for sure.

Can you give me some details about your use case?

The Hibernate ORM upgrades are taking me longer than I've anticipated, but I hope I can get back to check these bugs soon

**Comment by Dougniel** [comment]
I had a similar problem, same error but while inserting with ~20 concurrent request with about 1000k records each within 5 entities

I analyzed a heap dump with VisualVM and found that one instance of `ReactiveSessionImpl` was still open even though there was no activity at that time. Looking a bit more I found [this code](https://github.com/hibernate/hibernate-reactive/blob/4a7c515446041c6039da7761b2111e26caa4fff6/hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/ReactiveActionQueue.java#L1028-L1030) that seams a bit sneaky _(singleton with an instance variable holding a session..)_. So I disabled `hibernate.order_inserts` that I had activated it previously for 20% speed gain and I d'ont have this issue anymore

**Comment by FroMage** [comment]
@DavideD this looks like a good code suspect, no?

**Comment by DavideD** [comment]
Could be. As soon as I have finished something else I will have a better look

**Comment by DavideD** [comment]
I think I might have found the culprit: https://github.com/hibernate/hibernate-reactive/issues/2079
I haven't tested it yet, though

**Comment by DavideD** [comment]
Nevermind. It doesn't seem to solve the issue

**Comment by derkork** [comment]
We encountered the same problem in an application of ours. It only shows under high load. I can confirm that using  delete with a query (e.g.`delete("_id = ?1", someId)`) instead of `deleteById(someId)` fixes the problem, so it must be something that the `deleteById` function does, that triggers it.

**Comment by dmitrysulman** [comment]
We're facing the same issue and it also happens only under high load:

```
java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread [121]: 'vert.x-eventloop-thread-1' current Thread [126]: 'vert.x-eventloop-thread-2'
```

We use Hibernate Reactive 4.5 together with Spring Framework, so it's not related to Panache or Quarkus. In our implementation we strictly follow [the thread-safe and stream-safe requirements for the reactive Session](https://docs.hibernate.org/reactive/4.5/reference/html_single/#_sessions_and_vert_x_contexts).

**Comment by cescoffier** [comment]
🤖 Automatically associated with the **WG - Quarkus Data** Working Group based on AI classification.

**Comment by dmitrysulman** [comment]
Update on this: in our case it traces back to Hibernate Reactive's Kotlin coroutines bridge (`Uni.awaitSuspending()`, from `mutiny-kotlin`). When the coroutine's `Job` gets cancelled — e.g. the client disconnects mid-request — cancellation propagates into the `Uni` subscription and closes the Session. Every `Mutiny.Session` operation (including `close()`) goes through a shared `uni()` wrapper (`MutinySessionFactoryImpl`) that dispatches via `runSubscriptionOn(context)`, `context` being the `VertxContext` — so the close gets dispatched onto whatever event-loop thread Hibernate's internal Vert.x instance picks for that dispatch, which isn't guaranteed to be the thread the Session was originally opened on.

We worked around it by capturing the Session's owning `Vertx.currentContext()` right when it's opened, and explicitly redirecting any cancellation-triggered close back onto that captured context, instead of leaving it to Hibernate's own dispatch.

**Comment by FroMage** [comment]
Is this an issue for @DavideD or for @lucamolteni ?

**Comment by DavideD** [comment]
Is there a test case? Because it's a bit unclear how we can solve this issue otherwise.

**Comment by FroMage** [comment]
Good point.

**Comment by FroMage** [comment]
Claude had this to say about this bug @DavideD and it feels like it may have nailed it:

  Analysis of the root cause                                                                                                                                               
  
  I traced through the Quarkus code to understand why deleteById triggers HR000069 while bulk delete(query) does not.
 
  The smoking gun: two-step `getSession()` in `deleteById`

  The problem is in AbstractJpaOperations.java:251-261 (https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-reactive-panache-common/runtime/src/mai
  n/java/io/quarkus/hibernate/reactive/panache/common/runtime/AbstractJpaOperations.java#L251-L261):
 
```java
  public Uni<Boolean> deleteById(Class<?> entityClass, Object id) {
      return findById(entityClass, id)              // Step 1: getSession() + session.find()
              .chain(entity -> {
                  if (entity == null) {
                      return Uni.createFrom().item(false);
                  }   
                  return getSession(entityClass)    // Step 2: getSession() AGAIN
                      .chain(session -> delete(session, entity).map(v -> true));
              });     
  }           
```  

  Where findById (line 81-82 (https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-reactive-panache-common/runtime/src/main/java/io/quarkus/hibernat
  e/reactive/panache/common/runtime/AbstractJpaOperations.java#L81-L82)) itself calls getSession():

```java
  public Uni<?> findById(Class<?> entityClass, Object id) {
      return getSession(entityClass).chain(session -> find(session, entityClass, id));
  }
```
 
  What goes wrong, step by step
 
  1. Request arrives on `vert.x-eventloop-thread-2`. The session is lazily created and stored in the Vert.x duplicated context. Hibernate Reactive records `thread-2` as the
     session's owning thread.
  2. `session.find(entityClass, id)` sends a `SELECT` query. The Vert.x SQL client executes this over a pooled database connection. The response arrives on whatever event-loop
     thread owns that socket — e.g. `vert.x-eventloop-thread-1`.
  3. Thread switch happens at the `.chain()` boundary. Internally, Hibernate Reactive bridges from Vert.x futures to `CompletableFuture` (visible in the original stack trace:
     `CompletableFuture.postComplete` → `CompletableFuture.complete`). Mutiny's `.chain()` runs the callback synchronously on the thread that signals completion — so the 
     continuation now runs on `thread-1`.
  4. `session.remove(entity)` triggers the thread check. `getSession()` retrieves the same session from the Vert.x duplicated context (it's per-request, not per-thread). Then
     `session.remove(entity)` touches the persistence context, which hits Jump to bottom (ctrl+End) ↓ affinity check: original `thread-2` ≠ current `thread-1` → HR000069.

  Why bulk `delete(query)` doesn't trigger it
 
  The query-based path (lines 263-279 (https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-reactive-panache-common/runtime/src/main/java/io/quarkus
  /hibernate/reactive/panache/common/runtime/AbstractJpaOperations.java#L263-L279)) makes one getSession() call and does a single stateless executeUpdate() that never
  touches the persistence context:

```java 
  return getSession(entityClass).chain(session ->
      createMutationQuery(session, "DELETE FROM Fruit WHERE id = ?1")
          .executeUpdate()
          .map(Integer::longValue));
```

  No find, no entity loaded, no second session access, no .chain() boundary between two session-touching operations.
 
  Why it mainly shows on delete (not create/update)
 
  `persist()` does a single `getSession().chain(session -> session.persist(entity))` — one step. `deleteById` is the only Panache operation that chains `findById` + `remove` as two
  separate session-touching steps with a `.chain()` boundary in between. (The code comment at line 252 explains the design intent: "we load the entity then delete it because
  it's the only implementation generic enough for any model, and correct in all cases (composite key, graph of entities, ...)")

  Possible Quarkus-side fix

  The simplest improvement is to capture the session once and reuse it, plus use emitOn to dispatch back to the correct event-loop thread after the find():

```java
  public Uni<Boolean> deleteById(Class<?> entityClass, Object id) {
      return getSession(entityClass).chain(session -> {
          Context ctx = Vertx.currentContext();
          return find(session, entityClass, id)
                  .emitOn(runnable -> ctx.runOnContext(v -> runnable.run()))
                  .chain(entity -> {
                      if (entity == null) {
                          return Uni.createFrom().item(false);
                      }   
                      return delete(session, entity).map(v -> true);
                  }); 
      });         
  }   
```

  This eliminates the redundant second getSession() call and forces the continuation back onto the correct event-loop thread after the DB response.
  
  That said, the deeper issue is in Hibernate Reactive itself — session.find() completions should dispatch back to the session's owning Vert.x context, so callers don't
  need to worry about thread affinity across `.chain()` boundaries. @dmitrysulman's comment above (https://github.com/quarkusio/quarkus/issues/41945#issuecomment-5686686422)
  confirms this affects bare Hibernate Reactive (without Panache) as well.

**Comment by FroMage** [comment]
"the smoking gun" what dramatics, Claude, really 🙄

**Comment by DavideD** [comment]
I will have a look
