### ISSUE TITLE
ConfigProvider is not working properly in QuarkusTestResourceLifecycleManager

### ISSUE THREAD

**Issue by Inithron** [quarkusio/quarkus#42027]
### Describe the bug

Like described in this chapter https://quarkus.io/guides/getting-started-testing#quarkus-test-resource I used the ConfigProvider in a class which implements QuarkusTestResourceLifecycleManager. But with the ConfigProvider I can only access the properties from the application.properties file and not the properties from the application-test.properties file. @

### Expected behavior

The properties in the application-test.properties file can be accessed via the ConfigProvider.

### Actual behavior

When accessing a property from the application-test.properties file following error is thrown:
```
java.lang.RuntimeException: java.lang.RuntimeException: Unable to start Quarkus test resource class testutils.TcmsWireMockResourceLifecycleManager
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:642)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:726)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class testutils.TcmsWireMockResourceLifecycleManager
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.NoSuchElementException: SRCFG00014: The config property my-config-group.myconfig is required but it could not be found in any config source
	at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:435)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:380)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:359)
	at testutils.TcmsWireMockResourceLifecycleManager.start(TcmsWireMockResourceLifecycleManager.java:30)
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:500)
	... 4 more
```

### How to Reproduce?

1. Create a class which implements QuarkusTestResourceLifecycleManager.
2. Try to get a property which is defined in a applicatipn-test.properties file (it must be applicatipn-test.properties because the properties from applicatipn.properties file can accessed

### Output of `java -version`

17

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle version 8.9

### Additional information

I have implemented a workaround to access the properties from an application-test.properties file:
```
var config = ConfigProviderResolver.instance()
                    .getBuilder()
                    .withSources(new PropertiesConfigSource(ClassLoader.getSystemClassLoader()
                            .getResource("application-test.properties")))
                    .build();
            var myVar = config.getValue("my-config-group.myconfig", String.class);
```

**Comment by radcortez** [comment]
`ConfigProvider.getConfig` creates or retrieves a `Config` instance from the current classloader. In this particular case, because the method itself may provide configuration values, a `Config` instance does not exist, so when you call `ConfigProvider.getConfig` a new one is created.

The new instance does not contain the profile (unless it is set in one of the main config sources), because we only construct and set the profile much later in the test initialization. My recommendation is to either set the `quarkus.profile` in one of the main sources, or build a new instance with `ConfigUtils.emptyConfigBuilder().withProfile("test").build()`.
