### ISSUE TITLE
Cache manager does not see caches create at runtime in Infinispan

### ISSUE THREAD

**Issue by omasseau** [quarkusio/quarkus#42030]
### Describe the bug

Hello,

I don't really know if it is a bug or a limitation but it seems that the CacheManager is not able to see any cache that is created at runtime in Infinispan.

I'm using quarkus-infinispan-cache as the cache implementation and would like to create caches using the programmatic API if they don't exist (I cannot know in advance my caches names in my application).

So I tried to use infinispan RemoteCacheManager  to dynamically create a cache at runtime (which works as I can see the cache in the Infinispan console. But when I later call cacheManager.getCache(...) it tells me that the cache does not exist : 

> 2024-07-22 10:17:10,661 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /cache failed, error id: 881330ad-a87e-421e-8aa8-bf34ad8d7876-1: java.util.NoSuchElementException: No value present
> 	at java.base/java.util.Optional.get(Optional.java:143)
> 	at com.test.CacheTestResource.getCache(CacheTestResource.java:38)
> 	at com.test.CacheTestResource.get(CacheTestResource.java:26)
> 	at com.test.CacheTestResource$quarkusrestinvoker$get_27e4bb4bc80a4dcd94a463bacd9cb253d64feafb.invoke(Unknown Source)
> 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
> 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
> 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)

Here is a simple example to demonstrate the problem : 

```
package com.test;

import java.util.Optional;
import org.infinispan.client.hotrod.RemoteCacheManager;
import io.quarkus.cache.Cache;
import io.quarkus.cache.CacheManager;
import io.quarkus.infinispan.client.runtime.InfinispanClientProducer;
import io.quarkus.logging.Log;
import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;


@Path("/cache")
public class CacheTestResource {

    @Inject
    CacheManager cacheManager;

    @Inject
    RemoteCacheManager remoteCacheManager;

    @GET
    public void get() {
       getCache("test");
    }

    private Cache getCache(String cacheName) {
        Optional<Cache> cache = cacheManager.getCache(cacheName);

        if (cache.isPresent()) {
            return cache.get();
        } else {
            Log.info("Cache not found: " + cacheName + ". Creating it...");
            remoteCacheManager.administration().getOrCreateCache(cacheName, InfinispanClientProducer.DEFAULT_CONFIG);
            Log.info("Cache created: " + cacheName);
            return cacheManager.getCache(cacheName).get(); // Not working, cache is not available though CacheManager
        }
    }
}
```

### Expected behavior

CacheManager should correctly return the created cache

### Actual behavior

CacheManager is not returning the created cache

### Output of `java -version`

21.0.3

### Quarkus version or git rev

3.12.3

**Comment by karesti** [comment]
@omasseau io.quarkus.cache.CacheManager bean is not connecting to Infinispan, or the programmatic api, this is a limitation now. Use the RemoteCacheManager to create caches on the fly.
I'll keep this issue open to improve the extension

**Comment by omasseau** [comment]
> @omasseau io.quarkus.cache.CacheManager bean is not connecting to Infinispan, or the programmatic api, this is a limitation now. Use the RemoteCacheManager to create caches on the fly. I'll keep this issue open to improve the extension

@karesti 
As you can see I'm using the inject RemoteCacheManager to create the cache on the fly : 
`remoteCacheManager.administration().getOrCreateCache(cacheName, InfinispanClientProducer.DEFAULT_CONFIG);`

Maybe you meant to also use the remoteCacheManager to get the cache instance everywhere I need to add an entry to the cache ?

**Comment by karesti** [comment]
yes, sorry for the confusion, yes, this is what I meant

**Comment by karesti** [comment]
The benefit of using infinispan with the cache extension are the annotations like @CacheResult and so on. However, if you need to manipulate the caches in Infinispan, I would recommend using RemoteCacheManager and RemoteCache (infinispan client extension api)
