### ISSUE TITLE
Invalid `was not indexed at build time` on application reload

### ISSUE THREAD

**Issue by ylemoigne** [quarkusio/quarkus#42077]
### Describe the bug

Getting a REST client interface is working on first run, but when reloading the application (by pressing `s` in console), it fail with `REST client interface: interface toto.TotoResource was not indexed at build time`

### Expected behavior

It should work after reload.
If not, it should give an adapted error message, because this one does not match the situation.

### Actual behavior

Bogus message `REST client interface: interface toto.TotoResource was not indexed at build time`

### How to Reproduce?

[quarkus-rest-client-restart-issue.zip](https://github.com/user-attachments/files/16347924/quarkus-rest-client-restart-issue.zip)

Use the attached project, run `./gradlew :app:quarkusDev`
Then press `s` <Enter>

you should have the folowing log :
```
 ./gradlew :app:quarkusDev
Starting a Gradle Daemon, 2 stopped Daemons could not be reused, use --status for details

> Task :app:quarkusDev
io.smallrye.common:smallrye-common-net::jar classpath entry /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-net/2.2.0/261d912ae8bc78a67df97e69a589f998440f6d1c/smallrye-common-net-2.2.0.jar was overriden with /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-net/2.3.0/4858c78377802c801d2f9b24141381733b256260/smallrye-common-net-2.3.0.jar
io.smallrye.common:smallrye-common-constraint::jar classpath entry /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-constraint/2.4.0/9845f428e7ac5ff165dcd03074261f0ee6772f81/smallrye-common-constraint-2.4.0.jar was overriden with /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-constraint/2.3.0/1be18f3663dc7e8a5080039cdd10415ae679544/smallrye-common-constraint-2.3.0.jar
io.smallrye.common:smallrye-common-ref::jar classpath entry /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-ref/2.2.0/3887e9f5b9c6ab21e6f9d5f71d550ecbdafc620a/smallrye-common-ref-2.2.0.jar was overriden with /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-ref/2.3.0/8dee03ceb1c5466faaeb5554e045abfffa3df4eb/smallrye-common-ref-2.3.0.jar
io.smallrye.common:smallrye-common-expression::jar classpath entry /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-expression/2.4.0/3428461f913fd623d0b754eebca44eacd45be42c/smallrye-common-expression-2.4.0.jar was overriden with /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-expression/2.3.0/10b4807e36c082607bbd22bd263898c2043bb5f6/smallrye-common-expression-2.3.0.jar
io.smallrye.common:smallrye-common-function::jar classpath entry /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-function/2.4.0/87c17831e20be35c2b017f06f37a87ed286d5ecd/smallrye-common-function-2.4.0.jar was overriden with /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-function/2.3.0/17e2dcd9e238c99a6aaaba0162ba8547bfc8ade3/smallrye-common-function-2.3.0.jar
io.smallrye.common:smallrye-common-cpu::jar classpath entry /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-cpu/2.2.0/b70030308912ce33baafbf9775bba3a5d0c69b00/smallrye-common-cpu-2.2.0.jar was overriden with /Users/ylemoigne/.gradle/caches/modules-2/files-2.1/io.smallrye.common/smallrye-common-cpu/2.3.0/46b679da6b944d7e99fe2c32928978d916770b26/smallrye-common-cpu-2.3.0.jar
Listening for transport dt_socket at address: 5005
Press [e] to edit command line args (currently ''), [h] for more options>
Tests paused
Press [e] to edit command line args (currently ''), [r] to resume testing, [h] for more options>
Press [e] to edit command line args (currently ''), [r] to resume testing, [o] Toggle test output, [h] for more options>
2024-07-23 13:25:41,938 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-10) Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives:
- "toto" found in [org.example:api:1.0-SNAPSHOT, org.example:app:1.0-SNAPSHOT]
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-07-23 13:25:42,227 INFO  [io.quarkus] (Quarkus Main Thread) app 1.0-SNAPSHOT on JVM (powered by Quarkus 3.12.0) started in 0.599s.
2024-07-23 13:25:42,227 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-07-23 13:25:42,227 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, rest-client, rest-client-jackson, smallrye-context-propagation, vertx]
2024-07-23 13:25:42.324 java[79882:6290855] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
toto.TotoResource$$CDIWrapper@4d2eb1ae
<<============-> 93% EXECUTING [12s]
2024-07-23 13:25:51,400 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Quarkus Terminal Reader) Restarting as requested by the user.
2024-07-23 13:25:51,406 INFO  [io.quarkus] (Quarkus Main Thread) app stopped in 0.005s
2024-07-23 13:25:51,440 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-21) Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives:
- "toto" found in [org.example:api:1.0-SNAPSHOT, org.example:app:1.0-SNAPSHOT]
     __  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-07-23 13:25:51,505 INFO  [io.quarkus] (Quarkus Main Thread) app 1.0-SNAPSHOT on JVM (powered by Quarkus 3.12.0) started in 0.099s.
2024-07-23 13:25:51,506 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-07-23 13:25:51,506 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, rest-client, rest-client-jackson, smallrye-context-propagation, vertx]
2024-07-23 13:25:51,506 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Quarkus Terminal Reader) Live reload total time: 0.110s

Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: REST client interface: interface toto.TotoResource was not indexed at build time. See https://quarkus.io/guides/cdi-reference#bean_discovery for information on how to index the module that contains it.
        at org.jboss.resteasy.reactive.client.impl.ClientProxies.get(ClientProxies.java:35)
        at org.jboss.resteasy.reactive.client.impl.WebTargetImpl.proxy(WebTargetImpl.java:449)
        at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:521)
        at io.quarkus.rest.client.reactive.runtime.QuarkusRestClientBuilderImpl.build(QuarkusRestClientBuilderImpl.java:267)
        at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.build(RestClientCDIDelegateBuilder.java:67)
        at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.createDelegate(RestClientCDIDelegateBuilder.java:49)
        at io.quarkus.rest.client.reactive.runtime.RestClientReactiveCDIWrapperBase.delegate(RestClientReactiveCDIWrapperBase.java:76)
        at io.quarkus.rest.client.reactive.runtime.RestClientReactiveCDIWrapperBase.<init>(RestClientReactiveCDIWrapperBase.java:30)
        at toto.TotoResource$$CDIWrapper.<init>(Unknown Source)
        at toto.TotoResource$$CDIWrapper_ClientProxy.<init>(Unknown Source)
        at toto.TotoResource$$CDIWrapper_Bean.proxy(Unknown Source)
        at toto.TotoResource$$CDIWrapper_Bean.get(Unknown Source)
        at toto.TotoResource$$CDIWrapper_Bean.get(Unknown Source)
        at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:325)
        at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:309)
        at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:190)
        at toto.Application.lambda$run$0(Application.java:17)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
<============-> 93% EXECUTING [20s]
> :app:quarkusDev
```

### Output of `uname -a` or `ver`

Darwin MacBook-Pro-de-Yann.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode)

### Quarkus version or git rev

3.12.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 ------------------------------------------------------------ Gradle 8.8 ------------------------------------------------------------  Build time:   2024-05-31 21:46:56 UTC Revision:     4bd1b3d3fc3f31db5a26eecb416a165b8cc36082  Kotlin:       1.9.22 Groovy:       3.0.21 Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023 JVM:          21.0.3 (Eclipse Adoptium 21.0.3+9-LTS) OS:           Mac OS X 14.5 aarch64

### Additional information

This seems to be tied to calling thead and the easiest way to have a reproducer is calling from Swing UI thread. 
Internally, the `clazz` parameter of `ClientProxies` doesn't match the one in the map, but the ClientProxies is rebuild at reload, so I don't understand why ; it looks like a classloader issue but not sure.

**Comment by geoand** [comment]
Thanks for reporting.

Does this problem also happen with `3.12.3` and / or `3.13.0.CR1`?

**Comment by ylemoigne** [comment]
Yes (on both)

**Comment by geoand** [comment]
Thanks for checking

**Comment by geoand** [comment]
@aloubyansky any idea what's going on here?

**Comment by michelkaeser** [comment]
Encountering the same issue just now (but without reloading?).

For me, it happens for a REST client interface defined in a module where most code is generated by the `quarkus-openapi-generator` extension. Maybe the extension writes the Jandex index without checking if there are also classes outside of the generated one?

**Comment by aloubyansky** [comment]
Not yet, I can see the class being indexed on every app (re)start in` ApplicationArchivesBuildStep`.
FYI @mkouba

**Comment by michelkaeser** [comment]
```
@Path("assets/v1")
@Consumes(MediaType.MULTIPART_FORM_DATA)
public interface AssetsApi {

    @POST
    @Path("upload")
    void upload(@FormParam("file") File file);

}
```

works, while

```
@Path("assets/v1")
@Consumes(MediaType.MULTIPART_FORM_DATA)
public interface AssetsApi {

    @POST
    @Path("upload")
    void upload(@FormParam("file") InputStream file);

}
```

results in the error mentioned above.

Adding an additional (non `InputStream`) method to the interface works too, so it seems the interface is not correctly recognized if using non-standard parameters (that are however supported by Quarkus)?

**Comment by ylemoigne** [comment]
Hello. The issue is still present in 3.13.3

Any progress on this ?

**Comment by andreas-eberle** [comment]
I also just encountered this issue with a slightly different setup. For me, the error happens on application startup (reproducer below)

My Rest Client looks like this: 

```
@RegisterRestClient(baseUri = "google.de")
interface TestClient {

    @POST
    @ClientFormParam(name = "purpose", value = ["assistants"])
    fun uploadFile(@RestForm file: FileUpload): Response

}
```

and I use the rest client like this at startup:

```
@ApplicationScoped
class SomeService(@RestClient private val client: TestClient) {

    fun onStartup(@Observes e: StartupEvent) {
        println("empty")
    }
}
```


and this produces the follwing exception:

```
2024-09-03 15:55:59,653 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:116)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: REST client interface: interface org.acme.TestClient was not indexed at build time. See https://quarkus.io/guides/cdi-reference#bean_discovery for information on how to index the module that contains it.
	at org.jboss.resteasy.reactive.client.impl.ClientProxies.get(ClientProxies.java:35)
	at org.jboss.resteasy.reactive.client.impl.WebTargetImpl.proxy(WebTargetImpl.java:449)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:528)
	at io.quarkus.rest.client.reactive.runtime.QuarkusRestClientBuilderImpl.build(QuarkusRestClientBuilderImpl.java:267)
	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.build(RestClientCDIDelegateBuilder.java:69)
	at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.createDelegate(RestClientCDIDelegateBuilder.java:50)
	at io.quarkus.rest.client.reactive.runtime.RestClientReactiveCDIWrapperBase.delegate(RestClientReactiveCDIWrapperBase.java:76)
	at io.quarkus.rest.client.reactive.runtime.RestClientReactiveCDIWrapperBase.<init>(RestClientReactiveCDIWrapperBase.java:30)
	at org.acme.TestClient$$CDIWrapper.<init>(Unknown Source)
	at org.acme.TestClient$$CDIWrapper_ClientProxy.<init>(Unknown Source)
	at org.acme.TestClient$$CDIWrapper_Bean.proxy(Unknown Source)
	at org.acme.TestClient$$CDIWrapper_Bean.get(Unknown Source)
	at org.acme.TestClient$$CDIWrapper_Bean.get(Unknown Source)
	at org.acme.SomeService_Bean.doCreate(Unknown Source)
	at org.acme.SomeService_Bean.create(Unknown Source)
	at org.acme.SomeService_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c3(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at org.acme.SomeService_Observer_onStartup_o-CjltpfTUIuQfRAWE_2d4l5544.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:156)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:107)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 11 more
```

As soon as I remove the `@ClientFormParam(name = "purpose", value = ["assistants"])` line in the Rest Client, Quarkus can start. 


Reproducer:

* download and unzip [2024-09-03-rest-client-form-param-mix.zip](https://github.com/user-attachments/files/16849984/2024-09-03-rest-client-form-param-mix.zip)
* just start the app with `./gradlew quarkusDev`


Maybe this helps debugging it.

**Comment by akizminet** [comment]
How do I debug what's wrong with the build process? It succeeds, but I am still facing the same error on the latest Quarkus 3.19.2

**Comment by ylemoigne** [comment]
Always present in 3.21.0

**Comment by gsmet** [comment]
I'll have a look tomorrow.

**Comment by ylemoigne** [comment]
Hello @gsmet. Any news on this ?
(Still here in 3.21.2)

**Comment by gsmet** [comment]
I had a quick look the other day and didn't find anything obvious, except maybe that there could be a race condition.

I have to wrap a few things today but I will get back to it soon.
