### ISSUE TITLE
Quarkus 3.10 issue with OpenTelemetry? 

### ISSUE THREAD

**Issue by matzew** [quarkusio/quarkus#42087]
### Describe the bug

We get a unti test failure when trying to bump to Quarkus 3.10 (from 3.8).

```
java.lang.AssertionError: 
Expected size: 3 but was: 2 in:
[SpanData{spanContext=ImmutableSpanContext{traceId=b3af604008204ef273725923bf652a00, spanId=59f302b88a8e9bb0, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=b3af604008204ef273725923bf652a00, spanId=410e1d8a6485bd43, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=true, valid=true}, resource=Resource{schemaUrl=null, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.32.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=io.vertx, version=null, schemaUrl=null, attributes={}}, name=POST, kind=SERVER, startEpochNanos=1721749113517586397, endEpochNanos=1721749113534142078, attributes=AttributesMap{data={http.request.method=POST, url.path=/broker-ns/broker-name, http.status_code=202, http.scheme=http, messaging.message_source=/hello, messaging.message_type=type, http.method=POST, http.response.status_code=202, http.url=http://localhost:8083/broker-ns/broker-name, messaging.message_id=1234}, capacity=128, totalAddedValues=10}, totalAttributeCount=10, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true},
    SpanData{spanContext=ImmutableSpanContext{traceId=b3af604008204ef273725923bf652a00, spanId=410e1d8a6485bd43, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=null, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.32.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=io.vertx, version=null, schemaUrl=null, attributes={}}, name=POST, kind=CLIENT, startEpochNanos=1721749113491976322, endEpochNanos=1721749113538305773, attributes=AttributesMap{data={http.request.method=POST, http.status_code=202, http.method=POST, url.full=http://localhost:8083/broker-ns/broker-name, http.response.status_code=202, http.url=http://localhost:8083/broker-ns/broker-name}, capacity=128, totalAddedValues=6}, totalAttributeCount=6, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}]

	at dev.knative.eventing.kafka.broker.receiver.impl.ReceiverVerticleTracingTest.traceIsPropagated(ReceiverVerticleTracingTest.java:190)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
```

### Expected behavior

Like in 3.8 and its telemetry libray no issue

### Actual behavior

Test fails...

### How to Reproduce?

* check out the branch: https://github.com/matzew/eventing-kafka-broker/tree/quarkus_3.10
* open project root in `IDEA`
* go to the `data-plane` project
* run the `ReceiverVerticleTracingLoomImplTest` test in the IDEA 

### Output of `uname -a` or `ver`

Fedora

### Output of `java -version`

21 (prow) and 22 (my fedora)

### Quarkus version or git rev

3.10.2

### Additional information

The error:

```
java.lang.AssertionError: 
Expected size: 3 but was: 2 in:
[SpanData{spanContext=ImmutableSpanContext{traceId=b3af604008204ef273725923bf652a00, spanId=59f302b88a8e9bb0, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=b3af604008204ef273725923bf652a00, spanId=410e1d8a6485bd43, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=true, valid=true}, resource=Resource{schemaUrl=null, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.32.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=io.vertx, version=null, schemaUrl=null, attributes={}}, name=POST, kind=SERVER, startEpochNanos=1721749113517586397, endEpochNanos=1721749113534142078, attributes=AttributesMap{data={http.request.method=POST, url.path=/broker-ns/broker-name, http.status_code=202, http.scheme=http, messaging.message_source=/hello, messaging.message_type=type, http.method=POST, http.response.status_code=202, http.url=http://localhost:8083/broker-ns/broker-name, messaging.message_id=1234}, capacity=128, totalAddedValues=10}, totalAttributeCount=10, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true},
    SpanData{spanContext=ImmutableSpanContext{traceId=b3af604008204ef273725923bf652a00, spanId=410e1d8a6485bd43, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=null, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.32.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=io.vertx, version=null, schemaUrl=null, attributes={}}, name=POST, kind=CLIENT, startEpochNanos=1721749113491976322, endEpochNanos=1721749113538305773, attributes=AttributesMap{data={http.request.method=POST, http.status_code=202, http.method=POST, url.full=http://localhost:8083/broker-ns/broker-name, http.response.status_code=202, http.url=http://localhost:8083/broker-ns/broker-name}, capacity=128, totalAddedValues=6}, totalAttributeCount=6, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}]

	at dev.knative.eventing.kafka.broker.receiver.impl.ReceiverVerticleTracingTest.traceIsPropagated(ReceiverVerticleTracingTest.java:190)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)

**Comment by geoand** [comment]
cc @brunobat

**Comment by matzew** [comment]
there are other tracing related errors, such as -> https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/3872/reconciler-tests_eventing-kafka-broker_main/1815775631011483648

all w/ the bump to 3.10

**Comment by brunobat** [comment]
looking into it

**Comment by matzew** [comment]
I see this here too, and I think it is just when I use the vertx-opentelemetry version 4.5.x:
https://github.com/knative-extensions/eventing-kafka-broker/pull/3929#pullrequestreview-2198980757

But not yet exactly sure, on what's the diff between 4.4.7 and 4.5.7 (which is what our core is based on, via quarkus)

**Comment by brunobat** [comment]
@matzew I'm not sure about the scope of this issue anymore. 
From this issue it seems you cannot use `quarkus-opentelemetry` in version 3.10, however, in this issue: https://github.com/knative-extensions/eventing-kafka-broker/pull/3929 it looks like you are instead instrumenting with `vertx-opentelemetry` which Quarkus doesn't support.
Can you please clarify what's your plan?
Also, above, I see you never answered to this question:

> @matzew what are the 3 traces that you are expecting on that test, here:
https://github.com/matzew/eventing-kafka-broker/blob/6e1d381b21f48d893aa925729ed50e903d378e83/data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java#L190

In order to understand what's going on, we need to understand what are the contents of the span that's missing.

**Comment by matzew** [comment]
@brunobat with the update it is missing the `name=kafka_send, kind=PRODUCER` span entry. 

Here is what it looks when printing the data on the `main` unit-tests. See the `kafka_send` data below:
```
Span: SpanData{spanContext=ImmutableSpanContext{traceId=aa128452f86c0d34c94139647e1855ef, spanId=bd3ca922bd020860, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=aa128452f86c0d34c94139647e1855ef, spanId=1c8d35da82bf2f28, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, resource=Resource{schemaUrl=null, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.32.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=io.vertx, version=null, schemaUrl=null, attributes={}}, name=kafka_send, kind=PRODUCER, startEpochNanos=1736235874876406008, endEpochNanos=1736235874893161153, attributes=AttributesMap{data={message_bus.destination=topic-name-42, peer.service=kafka, peer.address=}, capacity=128, totalAddedValues=3}, totalAttributeCount=3, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}

**Comment by brunobat** [comment]
@matzew can we close this issue?

**Comment by matzew** [comment]
/close

this has been addressed. It was an issue w/ just the vert.x library 

@tsegismont fixed the issue w/ this PR: https://github.com/matzew/eventing-kafka-broker/pull/23
