### ISSUE TITLE
Unable to migrate to non-deprecated AnnotationsTransformerBuildItem

### ISSUE THREAD

**Issue by DSkoufis** [quarkusio/quarkus#42168]
### Describe the bug

We've recently updated Quarkus to 3.12.0 from 3.11 in a custom extension we use internally and we noticed that `io.quarkus.arc.deployment.AnnotationsTransformerBuildItem#AnnotationsTransformerBuildItem(io.quarkus.arc.processor.AnnotationsTransformer)` is deprecated and marked for removal. I've tried to use the other constructor but that is causing some build errors.

### Actual behavior

The build crash

```text
[ERROR] Errors: 
[ERROR]   CustomTest » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.AnnotationTarget.kind()" because the return value of "org.jboss.jandex.AnnotationInstance.target()" is null
	at io.quarkus.arc.processor.Annotations.getAnnotations(Annotations.java:105)
	at io.quarkus.arc.processor.Annotations.getAnnotations(Annotations.java:91)
	at io.quarkus.arc.deployment.AutoProducerMethodsProcessor$1.transform(AutoProducerMethodsProcessor.java:69)
	at io.quarkus.arc.processor.AnnotationsTransformer.apply(AnnotationsTransformer.java:67)
	at org.jboss.jandex.AnnotationOverlayImpl.getAnnotationsFor(AnnotationOverlayImpl.java:241)
	at org.jboss.jandex.AnnotationOverlayImpl.annotations(AnnotationOverlayImpl.java:211)
	at io.quarkus.arc.processor.AnnotationStore.getAnnotations(AnnotationStore.java:42)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1116)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:291)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:153)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:439)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```
(for the full stacktrace see: https://github.com/DSkoufis/quarkus-annotation-transformer-error-reproducer/blob/main/README.md)

### How to Reproduce?

I've prepared a reproducer project here: https://github.com/DSkoufis/quarkus-annotation-transformer-error-reproducer

There's a build step that registers some annotations (using the new class):

```java
new AnnotationsTransformerBuildItem(AnnotationTransformation.forMethods()
        .whenMethod(m -> m.name().equals(HANDLER_METHOD_NAME))
        .whenMethod(m -> m.declaringClass().interfaceNames().stream().anyMatch(HANDLERS::contains))
        .transform(t -> {
          t.add(CustomAnnotation.class);
          t.add(ActivateRequestContext.class);
        }));
```

But when I try to create a test in that extension it's failing:

```java
@RegisterExtension
static final QuarkusUnitTest config = new QuarkusUnitTest()
    .withApplicationRoot(jar -> jar.addClass(TestRequestHandler.class));
```

I've added the previous version that still works just fine and we were using: https://github.com/DSkoufis/quarkus-annotation-transformer-error-reproducer/blob/main/deployment/src/main/java/org/acme/greeting/extension/deployment/GreetingExtensionProcessor.java#L56

### Output of `java -version`

17.0.12

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.9.8

**Comment by Ladicek** [comment]
Thanks for the reproducer! This will be first fixed in Jandex (see https://github.com/smallrye/jandex/pull/414) and then in Quarkus by upgrading to Jandex 3.2.1.
