### ISSUE TITLE
Failure running a test using Junit on Eclipse or Maven

### ISSUE THREAD

**Issue by cvgaviao** [quarkusio/quarkus#42194]
### Describe the bug

I have started the my app (using 3.12.3) using a git bash terminal.

Then, I tried to run a specific test using the Junit Eclipse tool (Version: 2024-06 (4.32.0) Build id: 20240606-1231). 

### Expected behavior

The test to run without any issue.

### Actual behavior

I got the error bellow:
```
jul. 29, 2024 7:46:33 DA MANHÃ io.smallrye.beanbag.sisu.BeanLoadingTaskRunner waitForCompletion
ERROR: The following errors where caught while loading beans:
jul. 29, 2024 7:46:33 DA MANHÃ io.smallrye.beanbag.sisu.BeanLoadingTaskRunner waitForCompletion
ERROR: 1) No valid constructor found on class org.eclipse.aether.internal.transport.wagon.PlexusWagonConfigurator
java.lang.RuntimeException: No valid constructor found on class org.eclipse.aether.internal.transport.wagon.PlexusWagonConfigurator
	at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
	at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
	at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
	at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
	at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
	at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

jul. 29, 2024 7:46:33 DA MANHÃ io.smallrye.beanbag.sisu.BeanLoadingTaskRunner waitForCompletion
ERROR: 2) No valid constructor found on class org.sonatype.plexus.components.sec.dispatcher.DefaultSecDispatcher
java.lang.RuntimeException: No valid constructor found on class org.sonatype.plexus.components.sec.dispatcher.DefaultSecDispatcher
	at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
	at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
	at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
	at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
	at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
	at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

jul. 29, 2024 7:46:33 DA MANHÃ io.smallrye.beanbag.sisu.BeanLoadingTaskRunner waitForCompletion
ERROR: 3) No valid constructor found on class org.apache.maven.DefaultArtifactFilterManager
java.lang.RuntimeException: No valid constructor found on class org.apache.maven.DefaultArtifactFilterManager
	at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
	at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
	at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
	at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
	at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
	at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

jul. 29, 2024 7:46:33 DA MANHÃ io.smallrye.beanbag.sisu.BeanLoadingTaskRunner waitForCompletion
ERROR: 4) No valid constructor found on class org.apache.maven.settings.building.DefaultSettingsBuilder
java.lang.RuntimeException: No valid constructor found on class org.apache.maven.settings.building.DefaultSettingsBuilder
	at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
	at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
	at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
	at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
	at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
	at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

jul. 29, 2024 7:46:33 DA MANHÃ io.smallrye.beanbag.sisu.BeanLoadingTaskRunner waitForCompletion
ERROR: 5) No valid constructor found on class org.apache.maven.cli.internal.BootstrapCoreExtensionManager
java.lang.RuntimeException: No valid constructor found on class org.apache.maven.cli.internal.BootstrapCoreExtensionManager
	at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
	at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
	at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
	at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
	at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
	at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

jul. 29, 2024 7:46:33 DA MANHÃ io.smallrye.beanbag.sisu.BeanLoadingTaskRunner waitForCompletion
ERROR: 6) No valid constructor found on class org.apache.maven.model.validation.DefaultModelValidator
java.lang.RuntimeException: No valid constructor found on class org.apache.maven.model.validation.DefaultModelValidator
	at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
	at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
	at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
	at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
	at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
	at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

jul. 29, 2024 7:46:33 DA MANHÃ io.smallrye.beanbag.sisu.BeanLoadingTaskRunner waitForCompletion
ERROR: 7) No valid constructor found on class org.eclipse.aether.internal.impl.checksum.SparseDirectoryTrustedChecksumsSource
java.lang.RuntimeException: No valid constructor found on class org.eclipse.aether.internal.impl.checksum.SparseDirectoryTrustedChecksumsSource
	at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
	at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
	at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
	at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
	at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
	at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

jul. 29, 2024 7:46:33 DA MANHÃ io.smallrye.beanbag.sisu.BeanLoadingTaskRunner waitForCompletion
ERROR: 8) No valid constructor found on class org.sonatype.plexus.components.sec.dispatcher.DefaultSecDispatcher
java.lang.RuntimeException: No valid constructor found on class org.sonatype.plexus.components.sec.dispatcher.DefaultSecDispatcher
	at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
	at io.smallrye.beanbag.sisu.Sisu.addBeanFromXml(Sisu.java:470)
	at io.smallrye.beanbag.sisu.Sisu.addPlexusComponents(Sisu.java:142)
	at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$1(Sisu.java:85)
	at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
	at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

jul. 29, 2024 7:46:33 DA MANHÃ org.jboss.logmanager.JBossLoggerFinder getLogger
ERROR: The LogManager accessed before the "java.util.logging.manager" system property was set to "org.jboss.logmanager.LogManager". Results may be unexpected.

```

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19045 LP479425 3.4.10-87d57229.x86_64 2024-02-14 20:17 UTC x86_6

### Output of `java -version`

openjdk version "21" 2023-09-19 OpenJDK Runtime Environment (build 21+35-2513) OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.7 (8b094c9513efc1b9ce2d952b3b9c8eaedaf8cbf0)

**Comment by geoand** [comment]
cc @dmlloyd

**Comment by mkouba** [comment]
I'm an Eclipse user too and running a `@QuarkusTest` directly from the IDE never worked reliably. Sometimes it helps if you disable `Project > Build Automatically` but very often a strange class loading issue occurs. I would recommend to use the [Continuous Testing](https://quarkus.io/guides/continuous-testing) feature instead. Or run the tests from the command line/integrated terminal.

**Comment by cvgaviao** [comment]
@mkouba , I'm using Continuous Testing from a terminal outside of Eclipse.

But using the IDE is always easier and intuitive than setup an include pattern on the terminal when you need to run a specific test class or test method, and also when you need to debug the code associated to that test.

Perhaps one future improvement would be to allow us to start a specific test on the dev UI

**Comment by mkouba** [comment]
> But using the IDE is always easier and intuitive than setup an include pattern on the terminal when you need to run a specific test class or test method, and also when you need to debug the code associated to that test.

Yes, I usually use `mvn clean test -Dtest=Foo#bar -Dmaven.surefire.debug` + remote debugging. 

> Perhaps one future improvement would be to allow us to start a specific test on the dev UI

Feel free to file a new issue for this feature.

**Comment by cvgaviao** [comment]
> Yes, I usually use `mvn clean test -Dtest=Foo#bar -Dmaven.surefire.debug` + remote debugging.

@mkouba, I tried today to use maven to run our tests and it failed too. Tried with Surefire plugin versions 3.3.1 and 2.2.5:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.mycompany.api.app_mngt.endpoints.UserResourceTest
2024-08-09 22:33:33,652 ERROR [io.sma.bea.sis.BeanLoadingTaskRunner] (main) The following errors where caught while loading beans:
2024-08-09 22:33:33,662 ERROR [io.sma.bea.sis.BeanLoadingTaskRunner] (main) 1) No valid constructor found on class org.eclipse.aether.internal.transport.wagon.PlexusWagonConfigurator: java.lang.RuntimeException: No valid constructor found on class org.eclipse.aether.internal.transport.wagon.PlexusWagonConfigurator
        at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
        at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
        at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
        at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
        at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
        at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

2024-08-09 22:33:33,665 ERROR [io.sma.bea.sis.BeanLoadingTaskRunner] (main) 2) No valid constructor found on class org.sonatype.plexus.components.sec.dispatcher.DefaultSecDispatcher: java.lang.RuntimeException: No valid constructor found on class org.sonatype.plexus.components.sec.dispatcher.DefaultSecDispatcher
        at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
        at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
        at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
        at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
        at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
        at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

2024-08-09 22:33:33,666 ERROR [io.sma.bea.sis.BeanLoadingTaskRunner] (main) 3) No valid constructor found on class org.apache.maven.DefaultArtifactFilterManager: java.lang.RuntimeException: No valid constructor found on class org.apache.maven.DefaultArtifactFilterManager
        at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
        at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
        at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
        at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
        at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
        at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

2024-08-09 22:33:33,667 ERROR [io.sma.bea.sis.BeanLoadingTaskRunner] (main) 4) No valid constructor found on class org.apache.maven.settings.building.DefaultSettingsBuilder: java.lang.RuntimeException: No valid constructor found on class org.apache.maven.settings.building.DefaultSettingsBuilder
        at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
        at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
        at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
        at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
        at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
        at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

2024-08-09 22:33:33,667 ERROR [io.sma.bea.sis.BeanLoadingTaskRunner] (main) 5) No valid constructor found on class org.apache.maven.cli.internal.BootstrapCoreExtensionManager: java.lang.RuntimeException: No valid constructor found on class org.apache.maven.cli.internal.BootstrapCoreExtensionManager
        at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
        at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
        at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
        at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
        at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
        at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

2024-08-09 22:33:33,668 ERROR [io.sma.bea.sis.BeanLoadingTaskRunner] (main) 6) No valid constructor found on class org.sonatype.plexus.components.sec.dispatcher.DefaultSecDispatcher: java.lang.RuntimeException: No valid constructor found on class org.sonatype.plexus.components.sec.dispatcher.DefaultSecDispatcher
        at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
        at io.smallrye.beanbag.sisu.Sisu.addBeanFromXml(Sisu.java:470)
        at io.smallrye.beanbag.sisu.Sisu.addPlexusComponents(Sisu.java:142)
        at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$1(Sisu.java:85)
        at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
        at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

2024-08-09 22:33:33,668 ERROR [io.sma.bea.sis.BeanLoadingTaskRunner] (main) 7) No valid constructor found on class org.eclipse.aether.internal.impl.checksum.SparseDirectoryTrustedChecksumsSource: java.lang.RuntimeException: No valid constructor found on class org.eclipse.aether.internal.impl.checksum.SparseDirectoryTrustedChecksumsSource
        at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
        at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
        at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
        at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
        at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
        at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

2024-08-09 22:33:33,668 ERROR [io.sma.bea.sis.BeanLoadingTaskRunner] (main) 8) No valid constructor found on class org.apache.maven.model.validation.DefaultModelValidator: java.lang.RuntimeException: No valid constructor found on class org.apache.maven.model.validation.DefaultModelValidator
        at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:905)
        at io.smallrye.beanbag.sisu.Sisu.addClass(Sisu.java:585)
        at io.smallrye.beanbag.sisu.Sisu.addNamed(Sisu.java:174)
        at io.smallrye.beanbag.sisu.Sisu.lambda$addClassLoader$0(Sisu.java:83)
        at io.smallrye.beanbag.sisu.Sisu.lambda$loadBeans$2(Sisu.java:104)
        at io.smallrye.beanbag.sisu.BeanLoadingTaskRunner.lambda$run$0(BeanLoadingTaskRunner.java:32)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.631 s <<< FAILURE! -- in com.mycompany.api.app_mngt.endpoints.UserResourceTest
[ERROR] com.mycompany.api.app_mngt.endpoints.UserResourceTest -- Time elapsed: 0.631 s <<< ERROR!
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for com.mycompany.api:anq-api-application-management::jar:0.1.0-SNAPSHOTnull
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:634)
```

**Comment by cvgaviao** [comment]
Hello @geoand and @mkouba, seems that were introduced some dependencies conflicts on `quarkus-bootstrap-maven-resolver`. I'm seeing plexus-utils 4.0.0-alpha-5/3.5.1 and org.eclipse.sisu.plexus 0.9.0.M3/0.3.5 and others.

Perhaps it would be good to add this [enforcer rule](https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html) to the project.

I have created a project to reproduce the error I'm getting on our project. just call `mvn test` on it:

[quarkus-maven-test-issues.zip](https://github.com/user-attachments/files/16569160/quarkus-maven-test-issues.zip)

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by cvgaviao** [comment]
Hello. Interesting thing. I needed to clean up my laptop and then I deleted the .m2 directory on it.

Also, moved my current application to 3.16.0.CR1 and then I was able to run the test on both maven and Eclipse :)
