### ISSUE TITLE
ClassNotFound when a REST client is used in a @Scheduled kotlin coroutine scope, Quarkus 3.9.5

### ISSUE THREAD

**Issue by laurentperez** [quarkusio/quarkus#42219]
### Describe the bug

Hello. I believe this may be a continuation of https://github.com/quarkusio/quarkus/issues/40245

Reproducer with pseudocode :

```kotlin
@ApplicationScoped
class JobService {
@Inject
lateinit var service: Service // Service itself is @ApplicationScoped and has a injected @RestClient "MyRestClientAPIService"
@Scheduled
fun foo() {service.call()}
}
```

- when #foo is called is from the DEV UI http://localhost:8080/q/dev-ui/io.quarkus.quarkus-scheduler/scheduled-methods it will throw 

```
Caused by: java.lang.ClassNotFoundException: com.xxx.xxx.autogen.authent.api.MyRestClientAPIService
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:491)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at com.xxx.xxx.autogen.authent.api.MyRestClientAPIServicei_SKU7kPVCfXTrnWDieFY1BwYhem8_Synthetic_Bean.createSynthetic(Unknown Source)
	at com.xxx.xxx.autogen.authent.api.MyRestClientAPIService_SKU7kPVCfXTrnWDieFY1BwYhem8_Synthetic_Bean.doCreate(Unknown Source)
	at com.xxx.xxx.autogen.authent.api.MyRestClientAPIService_SKU7kPVCfXTrnWDieFY1BwYhem8_Synthetic_Bean.create(Unknown Source)
```

- I attempted to swap the TCCL as in https://github.com/quarkusio/quarkus/issues/40245#issuecomment-2074797202 : it works ;) 

```kotlin
  var properTccl: ClassLoader? = null

    fun onStart(@Observes ev: StartupEvent) {
        properTccl = Thread.currentThread().contextClassLoader
    }
    then in @scheduled block : Thread.currentThread().contextClassLoader = properTccl

```

### Expected behavior

REST client Class is found

### Actual behavior

see above

### How to Reproduce?

see above

### Quarkus version or git rev

3.9.5

**Comment by geoand** [comment]
Do this problem still occur with the latest version of Quarkus?
If so, please attach a sample project that demonstrates the issue in action.

Thanks

**Comment by laurentperez** [comment]
this works in 3.12.3, the Class is found

but the behaviour of the deferred coroutine is not consistent between 3.9 (with the TCCL workaround) and 3.12

when using `runBlocking(Dispatchers.Default)` on 3.9 the deferreds are correctly dispatched to different worker threads i.e D`efaultDispatcher-worker-2 #122 DefaultDispatcher-worker-2 #123`, etc.

on 3.12 every deferrred runs on the same vertx worker thread and not in multiple workers from `DefaultDispatcher` as it did before

I'm closing this #42219 and will open a different issue for the deferreds behaviour.

**Comment by laurentperez** [comment]
> this works in 3.12.3, the Class is found

edit : mistaken, it does not work in 3.12.3. I'll amend https://github.com/quarkusio/quarkus/issues/42219
