### ISSUE TITLE
Quarkus 3 + JasperReports  - java.sql.SQLException: Enlisted connection used without active transaction

### ISSUE THREAD

**Issue by SATISHEEEK** [quarkusio/quarkus#42210]
### Describe the bug

Dear Quarkus team,
we're having troubles while upgrading  Quarkus 2 -> Quarkus 3.. JasperReports library started to fail on active transaction issue. 

JasperReports executes subreports/tables in multi threads. Therefore I have a reason to think that my issue could be similiar to: https://stackoverflow.com/questions/68058274/transactional-does-not-work-in-sub-thread-in-quarkus

**DESCRIPTION**
- @ApplicationScoped class is calls JasperReports engine
- the transaction is active until Jasper starts to work in sub-threads
- instead of static JasperFillManager.fillReport() I tried to call non-static alternative, but without any difference
- same code has worked for years with Quarkus 2 :( Error occurres for **Quarkus 3 (exactly: 3.7.4)** 

**MY QUESTIONS**
- do you guys have any experience with combination Quarkus 3 + Jasper ? 
- Is there any resource to this multi-threading issue?
- What shall I do? I am no able to execute any report because all of our reports have at least 1 subreport..

**Thank you for your time and help!**  

Detailed description of my issue: https://stackoverflow.com/questions/78793479/quarkus3-jasperreports-got-java-sql-sqlexception-enlisted-connection-used-wit

ERROR LOG: 
```
2024-07-22T21:24:13.597381608Z executor-thread-1 23 2024-07-22 23:24:13.558  ERROR net.sf.jasperreports.engine.fill.JRFillSubreport Fill 1: exception: net.sf.jasperreports.engine.JRException: Error preparing statement for executing the report query:
2024-07-22T21:24:13.597462370Z 
2024-07-22T21:24:13.597475177Z SELECT
2024-07-22T21:24:13.597486237Z     *
2024-07-22T21:24:13.597502662Z FROM
2024-07-22T21:24:13.597519521Z     MY_TABLE
2024-07-22T21:24:13.597530077Z ORDER BY
2024-07-22T21:24:13.597538483Z     col
2024-07-22T21:24:13.597547363Z 
2024-07-22T21:24:13.597555636Z 
2024-07-22T21:24:13.597574220Z  at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createStatement(JRJdbcQueryExecuter.java:555)
2024-07-22T21:24:13.597810783Z  at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createDatasource(JRJdbcQueryExecuter.java:299)
2024-07-22T21:24:13.598088743Z  at net.sf.jasperreports.engine.fill.JRFillDataset.createQueryDatasource(JRFillDataset.java:1317)
2024-07-22T21:24:13.598244727Z  at net.sf.jasperreports.engine.fill.JRFillDataset.initDatasource(JRFillDataset.java:767)
2024-07-22T21:24:13.598340997Z  at net.sf.jasperreports.engine.fill.BaseReportFiller.setParameters(BaseReportFiller.java:465)
2024-07-22T21:24:13.598391111Z  at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:585)
2024-07-22T21:24:13.598464565Z  at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:416)
2024-07-22T21:24:13.598525214Z  at net.sf.jasperreports.engine.fill.JRFillSubreport.fillSubreport(JRFillSubreport.java:827)
2024-07-22T21:24:13.598583947Z  at net.sf.jasperreports.engine.fill.JRSubreportRunnable.run(JRSubreportRunnable.java:61)
2024-07-22T21:24:13.598621143Z  at net.sf.jasperreports.engine.fill.AbstractThreadSubreportRunner.run(AbstractThreadSubreportRunner.java:221)
2024-07-22T21:24:13.598716311Z  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-07-22T21:24:13.598803387Z  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-07-22T21:24:13.598913843Z  at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-22T21:24:13.599023284Z Caused by: java.sql.SQLException: Enlisted connection used without active transaction
2024-07-22T21:24:13.599110173Z  at io.agroal.pool.ConnectionHandler.verifyEnlistment(ConnectionHandler.java:398)
2024-07-22T21:24:13.599149982Z  at io.agroal.pool.wrapper.ConnectionWrapper.getMetaData(ConnectionWrapper.java:452)
2024-07-22T21:24:13.599212173Z  at net.sf.jasperreports.engine.query.OracleProcedureCallHandler.isOracle(OracleProcedureCallHandler.java:72)
2024-07-22T21:24:13.599341106Z  at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.isProcedureCall(JRJdbcQueryExecuter.java:566)
2024-07-22T21:24:13.599481640Z  at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createStatement(JRJdbcQueryExecuter.java:389)
2024-07-22T21:24:13.599597852Z  ... 12 more
```

**Output of `java -version`**
17
**Quarkus version or git rev**
3.7.4

**Comment by mmusgrov** [comment]
I don't know what your setup is, but by default transactions do not propagate to other threads unless you are using smallrye-context-propagation (https://quarkus.io/guides/context-propagation#setting-it-up). It's odd that it worked before, maybe the defaults have changed, but can include that dependency in your pom and retest.

**Comment by gastaldi** [comment]
Also please give a try with the latest Quarkus (3.13.2 as of now), 3.7.4 is not maintained anymore

**Comment by SATISHEEEK** [comment]
@mmusgrov & @gastaldi  - thank you so much for your input guys, its much appreciated. 

Adding depedency alone didn't help unfortunately, but I'll do some more test and experiments this week and give feedback afterwards.

Meanwhile thank you for your tips! I'll test them asap. 

BR,
Jan

**Comment by gastaldi** [comment]
@SATISHEEEK have you been able to find a workaround? It would be nice if you could provide a small reproducer too

**Comment by SATISHEEEK** [comment]
Hi @gastaldi ,
sorry for late reply. Currently I am sharing this issue with more experienced colleague, if we're not successful I'll provide an reproducer.
Thanks for keeping your eyes on our issue.
Jan

**Comment by geoand** [comment]
@SATISHEEEK any updates on this?

Thanks

**Comment by SATISHEEEK** [comment]
@geoand  Hi guys,
unfortunately we were not able to find any solution. 

So I am currently building a clean project with the same structure so we can share the code sample with you. I'll upload it asap. Thanks!

**Comment by geoand** [comment]
🙏🏽

**Comment by nderwin** [comment]
I had the same issue, and traced it down to the default class used to run subreports - https://github.com/TIBCOSoftware/jasperreports/blob/a8ec0e6cbbf04d36878c8f783f10c2ff88afeff5/core/src/main/java/net/sf/jasperreports/engine/fill/JRThreadSubreportRunner.java#L60

I did find a workaround by using a different runner for the subreports;  adding the property `JRSubreportRunnerFactory.SUBREPORT_RUNNER_FACTORY` to the report context, set to `net.sf.jasperreports.engine.fill.JRContinuationSubreportRunnerFactory`;  then I used the net.sf.jasperreports:jasperreports-javaflow dependency instead of net.sf.jasperreports:jasperreports.

There's not as many versions of that dependency published as the main library, however.

**Comment by geoand** [comment]
Let's close this for now, but if a sample becomes available please add it and we can reopen

**Comment by nderwin** [comment]
Here's a simple example using a database that shows the error, and the 2 changes that I mentioned before that make it work.

Run the app in dev mode (`./mvnw clean compile quarkus:dev`), then `curl localhost:8080/hello/report`.

[jasperreports-with-quarkus.zip](https://github.com/user-attachments/files/17197477/jasperreports-with-quarkus.zip)

**Comment by gastaldi** [comment]
That's an issue for https://github.com/quarkiverse/quarkus-jasperreports, which handles this integration better. May I ask you to file an issue there instead?

**Comment by nderwin** [comment]
@gastaldi I'll leave that to the OP, however, my reproducer isn't using the quarkus-jasperreports extension, just the naked jasperreports dependency.

Maybe this whole issue could be moved there?

**Comment by gastaldi** [comment]
> Maybe this whole issue could be moved there?

I don't think GitHub allows us to move issues between repositories in different organizations, at least the UI doesn't let me do that

**Comment by gastaldi** [comment]
@melloware FYI

**Comment by melloware** [comment]
I just opened this ticket: https://github.com/quarkiverse/quarkus-jasperreports/issues/100

**Comment by melloware** [comment]
I got to the bottom of this and added an Integration Tests in Quarkus JasperReports extension. There is no need to be running a report inside a transaction as reports do not INSERT/UPDATE/DELETE data only select.

# Database Datasource

When utilizing an Agroal Datasource to generate your report, ensure it is not within an active transaction. JasperReports employs threads for sub-reports and various features, and a connection cannot be passed across thread boundaries while in a transaction. Failing to do so will result in the following error: `Enlisted connection used without active transaction`.

```java
Caused by: java.sql.SQLException: Enlisted connection used without active transaction
2024-07-22T21:24:13.599110173Z  at io.agroal.pool.ConnectionHandler.verifyEnlistment(ConnectionHandler.java:398)
2024-07-22T21:24:13.599149982Z  at io.agroal.pool.wrapper.ConnectionWrapper.getMetaData(ConnectionWrapper.java:452)
2024-07-22T21:24:13.599212173Z  at net.sf.jasperreports.engine.query.OracleProcedureCallHandler.isOracle(OracleProcedureCallHandler.java:72)
2024-07-22T21:24:13.599341106Z  at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.isProcedureCall(JRJdbcQueryExecuter.java:566)
2024-07-22T21:24:13.599481640Z  at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createStatement(JRJdbcQueryExecuter.java:389)
```

> [!IMPORTANT]  
>In your service you must use `@Transactional(Transactional.TxType.NEVER)` above the method that is filling your report.

```java
@Inject
DataSource datasource;

@Transactional(Transactional.TxType.NEVER)
public byte[] text() throws JRException, SQLException {
    JasperPrint jasperPrint = null;
     try (final Connection connection = datasource.getConnection()) {
         params.put(JRParameter.REPORT_CONNECTION, connection);

         jasperPrint = JRFiller.fill(DefaultJasperReportsContext.getInstance(), SimpleJasperReportSource.from(mainReport, null, new SimpleRepositoryResourceContext()), params);
     }
    final JRTextExporter exporter = new JRTextExporter();
    exporter.setExporterInput(new SimpleExporterInput(jasperPrint));
    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    exporter.setExporterOutput(new SimpleWriterExporterOutput(outputStream));
    exporter.exportReport();
    return outputStream.toByteArray();
}
```

**Comment by SATISHEEEK** [comment]
Hi @melloware,
Thank you so much for your solution. I really appreciate the time you spent on this. It seems that it solved our jasper issue :)

Unfortunately, we've got another exception while using this `@Transactional(Transactional.TxType.NEVER)`
The exception is not jasper related, it's thrown right when the annotated method should be executed...

Do you have any idea, what could be behind this?

`xecutor-thread-1 21 2024-11-25 01:24:08.662  SEVERE sg.sg2020.xse.reports.domain.service.impl.JasperReportBean ARJUNA016153: Transaction is not allowed for invocation: jakarta.transaction.TransactionalException: ARJUNA016153: Transaction is not allowed for invocation
2024-11-25T00:24:08.665532142Z 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorNever.doIntercept(TransactionalInterceptorNever.java:36)
2024-11-25T00:24:08.665546259Z 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
2024-11-25T00:24:08.665556145Z 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorNever.intercept(TransactionalInterceptorNever.java:30)
2024-11-25T00:24:08.665565563Z 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorNever_Bean.intercept(Unknown Source)
2024-11-25T00:24:08.665574747Z 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
2024-11-25T00:24:08.665583894Z 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
2024-11-25T00:24:08.665607369Z 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
2024-11-25T00:24:08.665618210Z 	at sg.sg2020.xse.reports.domain.service.impl.JasperReportBean_Subclass.fillReportMoved(Unknown Source)
2024-11-25T00:24:08.665627746Z 	at sg.sg2020.xse.reports.domain.service.impl.JasperReportBean.prepareReport(JasperReportBean.java:1063)
2024-11-25T00:24:08.665636865Z 	at sg.sg2020.xse.reports.domain.service.impl.JasperReportBean.executePDF(JasperReportBean.java:833)
2024-11-25T00:24:08.665646094Z 	at sg.sg2020.xse.reports.domain.service.impl.JasperReportBean.generateTestReport(JasperReportBean.java:1337)
2024-11-25T00:24:08.665654999Z 	at sg.sg2020.xse.reports.domain.service.impl.JasperReportBean_ClientProxy.generateTestReport(Unknown Source)
2024-11-25T00:24:08.665663726Z 	at sg.sg2020.ars.reports.app.service.JasperReportApplicationService.generateTestReport(JasperReportApplicationService.java:38)
2024-11-25T00:24:08.665672665Z 	at sg.sg2020.ars.reports.app.service.JasperReportApplicationService_Subclass.generateTestReport$$superforward(Unknown Source)
2024-11-25T00:24:08.665681642Z 	at sg.sg2020.ars.reports.app.service.JasperReportApplicationService_Subclass$$function$$1.apply(Unknown Source)
2024-11-25T00:24:08.665690529Z 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
2024-11-25T00:24:08.665702141Z 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
2024-11-25T00:24:08.665711416Z 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInCallerTx(TransactionalInterceptorBase.java:335)
2024-11-25T00:24:08.665720508Z 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:40)
2024-11-25T00:24:08.665729416Z 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
2024-11-25T00:24:08.665738391Z 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
2024-11-25T00:24:08.665747729Z 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
2024-11-25T00:24:08.665756862Z 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
2024-11-25T00:24:08.665765489Z 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
2024-11-25T00:24:08.665774160Z 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
2024-11-25T00:24:08.665783280Z 	at sg.sg2020.ars.reports.app.service.JasperReportApplicationService_Subclass.generateTestReport(Unknown Source)
2024-11-25T00:24:08.665792633Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-11-25T00:24:08.665801644Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-11-25T00:24:08.665810596Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-11-25T00:24:08.665824108Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-11-25T00:24:08.665833742Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
2024-11-25T00:24:08.665842467Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
2024-11-25T00:24:08.665851401Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
2024-11-25T00:24:08.665860087Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
2024-11-25T00:24:08.665868715Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
2024-11-25T00:24:08.665878061Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
2024-11-25T00:24:08.665887370Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
2024-11-25T00:24:08.665896694Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
2024-11-25T00:24:08.665905972Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
2024-11-25T00:24:08.665933679Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
2024-11-25T00:24:08.665950109Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
2024-11-25T00:24:08.665959924Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
2024-11-25T00:24:08.665969570Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
2024-11-25T00:24:08.665978772Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
2024-11-25T00:24:08.665988022Z 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
2024-11-25T00:24:08.665997164Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
2024-11-25T00:24:08.666006206Z 	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:222)
2024-11-25T00:24:08.666038062Z 	at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.service(ResteasyFilter.java:70)
2024-11-25T00:24:08.666049596Z 	at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.sendError(ResteasyFilter.java:76)
2024-11-25T00:24:08.666058743Z 	at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:172)
2024-11-25T00:24:08.666067388Z 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
2024-11-25T00:24:08.666076163Z 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
2024-11-25T00:24:08.666084814Z 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
2024-11-25T00:24:08.666103699Z 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
2024-11-25T00:24:08.666113439Z 	at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:31)
2024-11-25T00:24:08.666124789Z 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
2024-11-25T00:24:08.666133642Z 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
2024-11-25T00:24:08.666144589Z 	at sg.sg2020.xse.scslog.util.filter.SCSLogWebFilter.doFilter(SCSLogWebFilter.java:78)
2024-11-25T00:24:08.666153855Z 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
2024-11-25T00:24:08.666162720Z 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
2024-11-25T00:24:08.666172092Z 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
2024-11-25T00:24:08.666180983Z 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
2024-11-25T00:24:08.666189912Z 	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
2024-11-25T00:24:08.666198651Z 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
2024-11-25T00:24:08.666208148Z 	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
2024-11-25T00:24:08.666216931Z 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
2024-11-25T00:24:08.666225788Z 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
2024-11-25T00:24:08.666235005Z 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2024-11-25T00:24:08.666244066Z 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
2024-11-25T00:24:08.666253178Z 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
2024-11-25T00:24:08.666266214Z 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
2024-11-25T00:24:08.666279298Z 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
2024-11-25T00:24:08.666288720Z 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
2024-11-25T00:24:08.666297647Z 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
2024-11-25T00:24:08.666306978Z 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2024-11-25T00:24:08.666319921Z 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2024-11-25T00:24:08.667112883Z 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
2024-11-25T00:24:08.667135679Z 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
2024-11-25T00:24:08.667155016Z 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
2024-11-25T00:24:08.667164730Z 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
2024-11-25T00:24:08.667174084Z 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
2024-11-25T00:24:08.667183154Z 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:637)
2024-11-25T00:24:08.667192309Z 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
2024-11-25T00:24:08.667201046Z 	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
2024-11-25T00:24:08.667210134Z 	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:91)
2024-11-25T00:24:08.667219776Z 	at io.undertow.server.handlers.CanonicalPathHandler.handleRequest(CanonicalPathHandler.java:49)
2024-11-25T00:24:08.667229138Z 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:126)
2024-11-25T00:24:08.667238109Z 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)
2024-11-25T00:24:08.667247118Z 	at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
2024-11-25T00:24:08.667262569Z 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$2.run(UndertowDeploymentRecorder.java:445)
2024-11-25T00:24:08.667271857Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-11-25T00:24:08.667280845Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-11-25T00:24:08.667289687Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
2024-11-25T00:24:08.667298407Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
2024-11-25T00:24:08.667307207Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
2024-11-25T00:24:08.667316386Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
2024-11-25T00:24:08.667325196Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
2024-11-25T00:24:08.667333758Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
2024-11-25T00:24:08.667351213Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-11-25T00:24:08.667360925Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-11-25T00:24:08.667374933Z Caused by: jakarta.transaction.InvalidTransactionException
2024-11-25T00:24:08.667385011Z 	... 100 more`

**Comment by melloware** [comment]
OK can you try `@Transactional(Transactional.TxType.NOT_SUPPORTED)`  instead of `NEVER`?

**Comment by SATISHEEEK** [comment]
Hi @melloware,
thank you for your input!!! 

`@Transactional(Transactional.TxType.NOT_SUPPORTED`  was the way. But it had to be used over the whole CLASS. 
Otherwise (I guess) there was the conflict between the class which had a transaction and the method which had not. 
Annotating the class solved our issue and now we're able to execute all reports. 

Thank you so much for your time!

**Comment by melloware** [comment]
Nice!
