### ISSUE TITLE
AWS Lambda exceptions: Broken pipe [Error Occurred After Shutdown] 

### ISSUE THREAD

**Issue by cthiebault** [quarkusio/quarkus#42217]
### Describe the bug

I'm using Quarkus to run some AWS Lambdas handling DynamoDB streams events.
In my logs, I get a lot of exceptions like this one:

```json
{
  "loggerClassName": "io.vertx.core.logging.Logger",
  "loggerName": "io.vertx.core.http.impl.HttpClientRequestImpl",
  "level": "ERROR",
  "message": "NULL [Error Occurred After Shutdown]",
  "threadName": "vert.x-eventloop-thread-0",
  "hostName": "unknown-host.unknown-domain",
  "processName": "AWSLambda",
  "sourceLineNumber": -1,
  [...]
}
```

Stacktrace:
```
io.netty.channel.StacklessClosedChannelException: NULL [Error Occurred After Shutdown]
at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
Caused by: java.io.IOException: Broken pipe
    at java.base/sun.nio.ch.SocketDispatcher.writev0(Native Method)
    at java.base/sun.nio.ch.SocketDispatcher.writev(Unknown Source)
    at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
    at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
    at java.base/sun.nio.ch.SocketChannelImpl.write(Unknown Source)
    at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:430)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:359)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:935)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:197)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.channelReadComplete(Http2ConnectionHandler.java:555)
    at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.channelReadComplete(VertxHttp2ConnectionHandler.java:430)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:486)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:456)
    at io.netty.handler.timeout.IdleStateHandler.channelReadComplete(IdleStateHandler.java:298)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:484)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:456)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1415)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
    at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:171)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Unknown Source)
```

My lambda processing is fine, but it seems something wrong is happening during the Lambda shutdown...

Any ideas on how to fix this?

### Output of `java -version`

21.0.2

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

**Comment by cthiebault** [comment]
It seems to be linked with OpenTelemetry: when I remove OpenTelemetry from my Lambdas, I don't see this error anymore...
