### ISSUE TITLE
Spring Data JPA findFirstBy with Optional throws NullPointerException

### ISSUE THREAD

**Issue by andreiyusupau** [quarkusio/quarkus#42239]
### Describe the bug

When using Spring Data JPA with Quarkus I get `NullPointerException` when using repository method with query keyword `findFirstBy` that returns `Optional`.

### Expected behavior

Method returns Optional.of(value) if it's present or Optional.empty if no value is present.

### Actual behavior

Call to `findFirstByOrderByCreatedAtDesc` throws `NullPointerException`:
``` java
public interface ExampleRepository extends JpaRepository<ExampleEntity, Long> {
    Optional<ExampleEntity> findFirstByOrderByCreatedAtDesc();
}
```
Exception stacktrace:
``` java
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.Optional.of(Optional.java:113)
	at com.andreiyusupau.example.ExampleRepository_68d979ff1b1ad5d6d3707a1ecc50adb481e23c00Impl.findFirstByOrderByCreatedAtDesc(Unknown Source)
	at com.andreiyusupau.example.ExampleRepository_68d979ff1b1ad5d6d3707a1ecc50adb481e23c00Impl_ClientProxy.findFirstByOrderByCreatedAtDesc(Unknown Source)
	at com.andreiyusupau.example.ExampleResource.error(ExampleResource.java:25)
	at com.andreiyusupau.example.ExampleResource$quarkusrestinvoker$error_be3de2a1864936f392922eb2209c8fbbb319fa32.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

https://github.com/andreiyusupau/quarkus-spring-data-bug-reproducer

### Output of `java -version`

Amazon Corretto 21.0.1

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

### Additional information

Getting entity and wrapping it into Optional.ofNullable() works normally (just as workaround):
``` java
public interface ExampleRepository2 extends JpaRepository<ExampleEntity, Long> {
    ExampleEntity findFirstByOrderByCreatedAtDesc();
}
```

**Comment by geoand** [comment]
Thanks for reporting.

#42241 takes care of the problem
