### ISSUE TITLE
NPE in websockets-next

### ISSUE THREAD

**Issue by RobertoUa** [quarkusio/quarkus#42271]
### Describe the bug

Getting NPE
```
java.lang.NullPointerException: Cannot invoke "java.lang.Short.shortValue()" because the return value of "io.vertx.core.http.WebSocketBase.closeStatusCode()" is null
	at io.quarkus.websockets.next.runtime.WebSocketConnectionBase.closeReason(WebSocketConnectionBase.java:134)
	at myapp.core.stream.Streaming_WebSocketServerEndpoint.doOnClose(Unknown Source)
	at io.quarkus.websockets.next.runtime.WebSocketEndpointBase$4.call(WebSocketEndpointBase.java:158)
	at io.quarkus.websockets.next.runtime.WebSocketEndpointBase$4.call(WebSocketEndpointBase.java:152)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

It seems like error is happening here https://github.com/quarkusio/quarkus/blob/450681e17a86d19dcae88621dc8f6922598b1dac/extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/runtime/WebSocketConnectionBase.java#L134

`closeStatusCode` is `Short` and it's null. It throws when it tries to unbox (`Short` -> `short`)

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
Hm, this could only happen if an `@OnClose` callback accepts a `CloseReason` param but when it's called the underlying WebSocket is not closed yet. And that should not normally happen.

@RobertoUa Could you tell me a little bit more about your application/use case?

**Comment by RobertoUa** [comment]
it happens every time the connection is terminated abruptly. Reproduces every time when I connect with `websocat` and then `kill -9` it.
But sometimes it happens with a regular browser, I couldn't figure out how and when it happens.

I also don't think it's a timeout from reverse proxy/load balancer, I do pings and connections could stay alive for hours.

**Comment by mkouba** [comment]
> Reproduces every time when I connect with `websocat` and then `kill -9` it.

Yes, I was able to reproduce the problem locally. There's not much we can do about it though. I've modified the code to use `CloseReason.INTERNAL_SERVER_ERROR` instead.
