### ISSUE TITLE
issue with building with --static

### ISSUE THREAD

**Issue by brenol** [quarkusio/quarkus#4228]
**Describe the bug**
Can't build using the provided docker image with --static additionalArgument.

**Expected behavior**
Build a static binary correctly.

**Actual behavior**
No binary is built, seems to be missing gcc dependencies.

**To Reproduce**
1. Create simple quarkus project
2. Try to build with additionalArguments = --static
3. See it fail

**Configuration**
n/a

**Screenshots**
n/a

**Environment (please complete the following information):**
I'm using **quay.io/quarkus/ubi-quarkus-native-image:19.2.0.1** docker image to build statically.

 - Quarkus version or git rev: 
0.22.0

**Additional context**
(Add any other context about the problem here.)
```
Running command: cc -v -o /project/graalvm-test-static-2.0.0-runner -z noexecstack -Wl,-x -static -Wl,--defsym -Wl,main=IsolateEnterStub__JavaMainWrapper__run__5087f5482cc9a6abc971913ece43acb471d2631b__a61fe6c26e84dd4037e4629852b5488bfcc16e7e -L/tmp/SVM-3237552308636428003 -L/opt/graalvm/jre/lib -L/opt/graalvm/jre/lib/svm/clibraries/linux-amd64 /tmp/SVM-3237552308636428003/graalvm-test-static-2.0.0-runner.o /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a -lm -ldl -lpthread -lz -lrt

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.2.1 20180905 (Red Hat 8.2.1-3) (GCC)
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/8/:/usr/libexec/gcc/x86_64-redhat-linux/8/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/8/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/8/:/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/8/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/project/graalvm-test-static-2.0.0-runner' '-z' 'noexecstack' '-static' '-L/tmp/SVM-3237552308636428003' '-L/opt/graalvm/jre/lib' '-L/opt/graalvm/jre/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/8/collect2 -plugin /usr/libexec/gcc/x86_64-redhat-linux/8/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper -plugin-opt=-fresolution=/tmp/ccZ3AXNp.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lc --build-id --no-add-needed --hash-style=gnu -m elf_x86_64 -static -o /project/graalvm-test-static-2.0.0-runner -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/8/crtbeginT.o -L/tmp/SVM-3237552308636428003 -L/opt/graalvm/jre/lib -L/opt/graalvm/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/8/../../.. -x --defsym main=IsolateEnterStub__JavaMainWrapper__run__5087f5482cc9a6abc971913ece43acb471d2631b__a61fe6c26e84dd4037e4629852b5488bfcc16e7e /tmp/SVM-3237552308636428003/graalvm-test-static-2.0.0-runner.o /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a -lm -ldl -lpthread -lz -lrt --start-group -lgcc -lgcc_eh -lc --end-group /usr/lib/gcc/x86_64-redhat-linux/8/crtend.o /usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crtn.o
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:457)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:308)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:446)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:112)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1
```

**Comment by dmlloyd** [comment]
I expect this is probably happening because the base image doesn't contain static versions of `libm.a`, `libdl.a`, `libpthread.a`, etc.

**Comment by neomatrix369** [comment]
`--static` has limited functionality atm, see [PR for docs on Graal repo](https://github.com/oracle/graal/pull/1602)

**Comment by gsmet** [comment]
I don't think we will support that for now.
