### ISSUE TITLE
Support parallel/concurrent testing with JUnit

### ISSUE THREAD

**Issue by bdemers** [quarkusio/quarkus#42296]
### Description

Ideally, Quarkus integration tests should be able to run concurrently in JUnit 5 by configuring:

```properties
junit.jupiter.execution.parallel.enabled = true
junit.jupiter.execution.parallel.mode.default = concurrent
```

Doing this currently results in some sort race condition.
(in my limited testing this occurs about ~50% of the time, the rest of the time, my tests pass successfully.)

```
java.lang.RuntimeException: java.lang.IllegalStateException: SRCFG00017: Configuration already registered for the given class loader
  at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:373)
  at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:117)
  at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.IllegalStateException: SRCFG00017: Configuration already registered for the given class loader
  at io.smallrye.config.SmallRyeConfigProviderResolver.registerConfig(SmallRyeConfigProviderResolver.java:120)
  at io.quarkus.runtime.configuration.QuarkusConfigFactory.setConfig(QuarkusConfigFactory.java:48)
  at io.quarkus.test.common.LauncherUtil.installAndGetSomeConfig(LauncherUtil.java:42)
  at io.quarkus.test.junit.QuarkusIntegrationTestExtension.lambda$isCallbacksEnabledForIntegrationTests$1(QuarkusIntegrationTestExtension.java:381)
  at java.base/java.util.Optional.or(Optional.java:313)
  at io.quarkus.test.junit.QuarkusIntegrationTestExtension.isCallbacksEnabledForIntegrationTests(QuarkusIntegrationTestExtension.java:381)
  at io.quarkus.test.junit.QuarkusIntegrationTestExtension.doProcessStart(QuarkusIntegrationTestExtension.java:225)
  at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:169)
  at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:130)
  ... 6 more
```

**Comment by bdemers** [comment]
Related to: #24524

**Comment by mkouba** [comment]
I don't think it's supported ATM and I also don't think there's a plan to add this support in the near future.

CC @geoand @holly-cummins

**Comment by holly-cummins** [comment]
On the one hand, my head hurts. On the other hand, I can see that once https://github.com/orgs/quarkusio/projects/30 is done, some things might open up. The implementation for that project is that we prepare all the Quarkus classloaders up front, but stop short of actually starting Quarkus. 

Even with https://github.com/orgs/quarkusio/projects/30, though, there'd be some pretty serious challenges around ports. We would have to move to a model where we use ephemeral ports for Quarkus itself, not just testcontainers instances. That would have some nice side effects, but it would also be hard to implement, and we'd probably be fighting hardcoded edge cases for years.

**Comment by holly-cummins** [comment]
I have a sliver of an idea about how we could run in parallel it within each profile/resource group, as long as there's no nested tests. (Nested tests rely on a stack of TCCLs and making that work in parallel would be challenging.)

**Comment by holly-cummins** [comment]
See also https://github.com/quarkusio/quarkus/issues/49146, a worsening in the not-actually-supported behaviour.
