### ISSUE TITLE
OOM in tests since Quarkus 3.13.0

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#42303]
### Describe the bug

Since Quarkus 3.13.0 we get the following exception in our tests:

```
    java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.steps.ConfigGenerationBuildStep#generateConfigClass threw an exception: java.lang.OutOfMemoryError: Java heap space
        at org.objectweb.asm.MethodWriter.visitFrameEnd(MethodWriter.java:1850)
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1648)
        at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1548)
        at io.quarkus.gizmo.MethodCreatorImpl.write(MethodCreatorImpl.java:140)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:233)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:257)
        at io.quarkus.deployment.configuration.RunTimeConfigurationGenerator$GenerateOperation.run(RunTimeConfigurationGenerator.java:523)
        at io.quarkus.deployment.steps.ConfigGenerationBuildStep.generateConfigClass(ConfigGenerationBuildStep.java:318)
        at java.base/java.lang.invoke.LambdaForm$DMH/0x0000732419437800.invokeVirtual(LambdaForm$DMH)
        at java.base/java.lang.invoke.LambdaForm$MH/0x0000732419492400.invoke(LambdaForm$MH)
        at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:157)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at io.quarkus.builder.BuildContext$$Lambda/0x00007324193e5458.run(Unknown Source)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.runWith(Thread.java:1596)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:634)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:718)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

        Caused by:
        java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.deployment.steps.ConfigGenerationBuildStep#generateConfigClass threw an exception: java.lang.OutOfMemoryError: Java heap space
                at org.objectweb.asm.MethodWriter.visitFrameEnd(MethodWriter.java:1850)
                at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1648)
                at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1548)
                at io.quarkus.gizmo.MethodCreatorImpl.write(MethodCreatorImpl.java:140)
                at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:233)
                at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:257)
                at io.quarkus.deployment.configuration.RunTimeConfigurationGenerator$GenerateOperation.run(RunTimeConfigurationGenerator.java:523)
                at io.quarkus.deployment.steps.ConfigGenerationBuildStep.generateConfigClass(ConfigGenerationBuildStep.java:318)
                at java.base/java.lang.invoke.LambdaForm$DMH/0x0000732419437800.invokeVirtual(LambdaForm$DMH)
                at java.base/java.lang.invoke.LambdaForm$MH/0x0000732419492400.invoke(LambdaForm$MH)
                at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:157)
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
                at java.base/java.lang.reflect.Method.invoke(Method.java:580)
                at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
                at io.quarkus.builder.BuildContext$$Lambda/0x00007324193e5458.run(Unknown Source)
                at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
                at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
                at java.base/java.lang.Thread.runWith(Thread.java:1596)
                at java.base/java.lang.Thread.run(Thread.java:1583)
                at org.jboss.threads.JBossThread.run(JBossThread.java:483)
            at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
            at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:254)
            at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:58)
            at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:219)
            at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:601)
            at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:651)
            ... 1 more

            Caused by:
            io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.deployment.steps.ConfigGenerationBuildStep#generateConfigClass threw an exception: java.lang.OutOfMemoryError: Java heap space
                at org.objectweb.asm.MethodWriter.visitFrameEnd(MethodWriter.java:1850)
                at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1648)
                at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1548)
                at io.quarkus.gizmo.MethodCreatorImpl.write(MethodCreatorImpl.java:140)
                at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:233)
                at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:257)
                at io.quarkus.deployment.configuration.RunTimeConfigurationGenerator$GenerateOperation.run(RunTimeConfigurationGenerator.java:523)
                at io.quarkus.deployment.steps.ConfigGenerationBuildStep.generateConfigClass(ConfigGenerationBuildStep.java:318)
                at java.base/java.lang.invoke.LambdaForm$DMH/0x0000732419437800.invokeVirtual(LambdaForm$DMH)
                at java.base/java.lang.invoke.LambdaForm$MH/0x0000732419492400.invoke(LambdaForm$MH)
                at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:157)
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
                at java.base/java.lang.reflect.Method.invoke(Method.java:580)
                at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
                at io.quarkus.builder.BuildContext$$Lambda/0x00007324193e5458.run(Unknown Source)
                at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
                at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
                at java.base/java.lang.Thread.runWith(Thread.java:1596)
                at java.base/java.lang.Thread.run(Thread.java:1583)
                at org.jboss.threads.JBossThread.run(JBossThread.java:483)
                at io.quarkus.builder.Execution.run(Execution.java:123)
                at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
                at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:159)
                at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
                ... 6 more

                Caused by:
                java.lang.OutOfMemoryError: Java heap space
                    at org.objectweb.asm.MethodWriter.visitFrameEnd(MethodWriter.java:1850)
                    at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1648)
                    at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1548)
                    at io.quarkus.gizmo.MethodCreatorImpl.write(MethodCreatorImpl.java:140)
                    at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:233)
                    at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:257)
                    at io.quarkus.deployment.configuration.RunTimeConfigurationGenerator$GenerateOperation.run(RunTimeConfigurationGenerator.java:523)
                    at io.quarkus.deployment.steps.ConfigGenerationBuildStep.generateConfigClass(ConfigGenerationBuildStep.java:318)
                    at java.base/java.lang.invoke.LambdaForm$DMH/0x0000732419437800.invokeVirtual(LambdaForm$DMH)
                    at java.base/java.lang.invoke.LambdaForm$MH/0x0000732419492400.invoke(LambdaForm$MH)
                    at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
                    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
                    at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
                    at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
                    at io.quarkus.builder.BuildContext$$Lambda/0x00007324193e5458.run(Unknown Source)
                    at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
                    at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
                    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
                    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
                    at java.base/java.lang.Thread.runWith(Thread.java:1596)
                    at java.base/java.lang.Thread.run(Thread.java:1583)
                    at org.jboss.threads.JBossThread.run(JBossThread.java:483)

```

### How to Reproduce?

~~I didn't managed to create a reproducer yet.~~

https://github.com/quarkusio/quarkus/issues/42303#issuecomment-2267564460

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus 3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.9

**Comment by gsmet** [comment]
Could you be affected by https://github.com/quarkusio/quarkus/discussions/42298 ?

If not, I think we will need to have a look at the heap dump. Add `-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/your/path` to the Surefire argLine to get a heap dump.

Might be a good idea to share it with me (don't make it public). You can send me a private link to gsmet at redhat dot com.

**Comment by gsmet** [comment]
@mschorsch might be worth trying https://github.com/quarkusio/quarkus/pull/42304

**Comment by gsmet** [comment]
OK, I don't think https://github.com/quarkusio/quarkus/pull/42304 will make any difference so I think getting heap dumps is in order.

**Comment by gsmet** [comment]
What would really help is if you could somehow identify which test class is running when you get the OOM and add a breakpoint there in 3.12.3 and get a heap dump too so that we could compare both.

**Comment by mschorsch** [comment]
> @mschorsch might be worth trying #42304

I tried it but it didn't seem to fix the issue.

**Comment by mschorsch** [comment]
One more hint: If I run the tests individually or only a subset of all tests then I don't get an OOM.

**Comment by gsmet** [comment]
Yeah, I think we will need a heap dump here. There's something leaking somewhere.

**Comment by mschorsch** [comment]
@gsmet 

> Might be a good idea to share it with me (don't make it public). You can send me a private link to gsmet at redhat dot com.

I am not sure if I am authorized to provide a heap dump. I have to clarify this beforehand. Sorry.

> Could you be affected by https://github.com/quarkusio/quarkus/discussions/42298 ?

But good (or bad :) ) news, yes, this seems the same issue. I've replaced `@QuarkusTestResource(OidcWiremockTestResource::class)` with `@QuarkusTestResource(OidcWiremockTestResource::class, restrictToAnnotatedClass = true)` and with Quarkus 3.12.3 I also get an OOM in exactly the same test as in Quarkus 3.13.0

**Comment by gsmet** [comment]
Ah OK, good. I'm busy on something else this week-end. If you had the time to assemble a small reproducer, that would be very helpful for me to have a look on Monday.

Thanks!

**Comment by gsmet** [comment]
(And yes, totally agree that sharing a heap dump can be sensitive but given the problem looks identified, if you have a small reproducer, I'll be able to track it without a heap dump)

**Comment by mschorsch** [comment]
@gsmet I managed to create a reproducer: 
[oom-reproducer.zip](https://github.com/user-attachments/files/16487889/oom-reproducer.zip)

**Comment by gsmet** [comment]
Thanks for the reproducer.

I end up with an OOM with Gradle but not with Maven, probably because of Gradle parallelizing tests (for now I don't think it's Gradle specific, just that it manifests more easily with Gradle).

From what I can see, the problem is a huge `QuarkusClassLoader` leak. What I don't understand is exactly why it manifests only when starting the test resources per test.

**Comment by mschorsch** [comment]
> I end up with an OOM with Gradle but not with Maven, probably because of Gradle parallelizing tests (for now I don't think it's Gradle specific, just that it manifests more easily with Gradle).

I think so too.

**Comment by mschorsch** [comment]
@gsmet As a temporary workaround for the upcoming Quarkus 3.13.1 you could change `restrictToAnnotatedClass` in `@WithTestResource` back to `false`, this would restore the previous behaviour.

**Comment by geoand** [comment]
That indeed fixes the problem.

I am looking into the root cause of this, but it's likely complex

**Comment by gsmet** [comment]
Except this annotation was solely created to change the default so...

I think maybe we should undeprecate `@QuarkusTestResource` for now.

**Comment by geoand** [comment]
Let's wait until I find the exact cause of this

**Comment by geoand** [comment]
Can you try https://github.com/quarkusio/quarkus/pull/42338 please?

It worked for me.

**Comment by mschorsch** [comment]
@geoand I've build your branch and tested against our application. The OOM ist still there.

**Comment by geoand** [comment]
But it's not in the reproducer, is it?

Because that's what I used.

The reason I am asking is because there might be a different leak and in that case we would need a separate reproducer.

**Comment by mschorsch** [comment]
If the repeoducer is now working then there are more leaks ...

**Comment by geoand** [comment]
Right, which is why we would need a reproducer to surfaces it / them - there is absolutely no way to track down a leak without being able to reproduce it reliably

**Comment by mschorsch** [comment]
@geoand I've created a new issue https://github.com/quarkusio/quarkus/issues/42355 with updated reproducer.

**Comment by geoand** [comment]
Thanks!
