### ISSUE TITLE
Native build/test fails on FIPS with Quarkus 3.13.0

### ISSUE THREAD

**Issue by JiriOndrusek** [quarkusio/quarkus#42333]
### Describe the bug

I executed several tests from camel-quarkus on FIPS enabled machine and all of them failed.
The execution of **quarkus-maven-plugin** fails with ` Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#resolveNativeImageBuildRunner threw an exception: org.apache.commons.lang3.exception.UncheckedException: java.security.NoSuchAlgorithmException: No strong SecureRandom impls available: NativePRNGBlocking:SUN,DRBG:SUN`

The problem was not happening with quarkus3.13.0.CR1. The reason might be an upgrade of commons-lang (https://github.com/quarkusio/quarkus/pull/42038/commits/aa91cc911e8961322108e3d089b85c5a9ba747b6)

### Expected behavior

The native build/test works on FIPS system as before.

### Actual behavior

Here is the failure log:

```
JVM test succeeds
...
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.49 s -- in org.apache.camel.quarkus.component.lumberjack.it.LumberjackTest
2024-08-06 07:12:57,132 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.7.0 (camel-1) is shutting down (timeout:45s)
2024-08-06 07:12:57,139 INFO  [org.apa.cam.com.lum.io.LumberjackServer] (Camel (camel-1) thread #4 - ShutdownTask) Stopping the LUMBERJACK server (host=0.0.0.0, port=45443).
2024-08-06 07:12:57,202 INFO  [org.apa.cam.com.lum.io.LumberjackServer] (Camel (camel-1) thread #4 - ShutdownTask) LUMBERJACK server is stopped (host=0.0.0.0, port=45443).
2024-08-06 07:12:57,203 INFO  [org.apa.cam.com.lum.io.LumberjackServer] (Camel (camel-1) thread #4 - ShutdownTask) Stopping the LUMBERJACK server (host=0.0.0.0, port=38769).
2024-08-06 07:12:57,226 INFO  [org.apa.cam.com.lum.io.LumberjackServer] (Camel (camel-1) thread #4 - ShutdownTask) LUMBERJACK server is stopped (host=0.0.0.0, port=38769).
2024-08-06 07:12:57,231 INFO  [org.apa.cam.com.lum.io.LumberjackServer] (Camel (camel-1) thread #4 - ShutdownTask) Stopping the LUMBERJACK server (host=0.0.0.0, port=44997).
2024-08-06 07:12:57,264 INFO  [org.apa.cam.com.lum.io.LumberjackServer] (Camel (camel-1) thread #4 - ShutdownTask) LUMBERJACK server is stopped (host=0.0.0.0, port=44997).
2024-08-06 07:12:57,271 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes stopped (total:3)
2024-08-06 07:12:57,271 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Stopped route3 (lumberjack-global-ssl://0.0.0.0:45443)
2024-08-06 07:12:57,272 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Stopped route2 (lumberjack://0.0.0.0:38769)
2024-08-06 07:12:57,272 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Stopped route1 (lumberjack://0.0.0.0:44997)
2024-08-06 07:12:57,277 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.7.0 (camel-1) shutdown in 144ms (uptime:8s)
2024-08-06 07:12:57,321 INFO  [io.quarkus] (main) camel-quarkus-integration-test-lumberjack stopped in 0.215s
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:3.3.0:jar (default-jar) @ camel-quarkus-integration-test-lumberjack ---
[INFO] Building jar: /home/hudson/jondruse/projects/camel-quarkus/integration-tests/lumberjack/target/camel-quarkus-integration-test-lumberjack-3.13.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.3.0:test-jar (default) @ camel-quarkus-integration-test-lumberjack ---
[INFO] Building jar: /home/hudson/jondruse/projects/camel-quarkus/integration-tests/lumberjack/target/camel-quarkus-integration-test-lumberjack-3.13.0-SNAPSHOT-tests.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:3.13.0:build (quarkus-build) @ camel-quarkus-integration-test-lumberjack ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.054 s
[INFO] Finished at: 2024-08-06T07:13:00Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.13.0:build (quarkus-build) on project camel-quarkus-integration-test-lumberjack: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#resolveNativeImageBuildRunner threw an exception: org.apache.commons.lang3.exception.UncheckedException: java.security.NoSuchAlgorithmException: No strong SecureRandom impls available: NativePRNGBlocking:SUN,DRBG:SUN
[ERROR] 	at org.apache.commons.lang3.RandomStringUtils.lambda$static$0(RandomStringUtils.java:61)
[ERROR] 	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:357)
[ERROR] 	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:225)
[ERROR] 	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:194)
[ERROR] 	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
[ERROR] 	at org.apache.commons.lang3.RandomStringUtils.random(RandomStringUtils.java:66)
[ERROR] 	at org.apache.commons.lang3.RandomStringUtils.random(RandomStringUtils.java:147)
[ERROR] 	at org.apache.commons.lang3.RandomStringUtils.random(RandomStringUtils.java:107)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner.<init>(NativeImageBuildContainerRunner.java:35)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildLocalContainerRunner.<init>(NativeImageBuildLocalContainerRunner.java:20)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.resolveNativeImageBuildRunner(NativeImageBuildStep.java:352)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
[ERROR] Caused by: java.security.NoSuchAlgorithmException: No strong SecureRandom impls available: NativePRNGBlocking:SUN,DRBG:SUN
[ERROR] 	at java.base/java.security.SecureRandom.getInstanceStrong(SecureRandom.java:979)
[ERROR] 	at org.apache.commons.lang3.RandomStringUtils.lambda$static$0(RandomStringUtils.java:59)
[ERROR] 	... 20 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

### How to Reproduce?

Reproducer:
Run a test module from the camel-quarkus on FIPS system (from the main branch which contains Quarkus 3.13.0)
I.e. run lumberjack test (https://github.com/apache/camel-quarkus/tree/main/integration-tests/lumberjack)
with the command `mvn clean verify -Ddocker -Pnative -f integration-tests/lumberjack`

**Comment by Karm** [comment]
I'm taking a look...  On FIPS RHEL with FIPS Red Hat OpenJDK and Red Hat build of Mandrel that is FIPS enabled, i.e. `registry.access.redhat.com/quarkus/mandrel-for-jdk-21-rhel8`. Although it seems I have to build ~1400 Camel components, so it's gonna be a while...

**Comment by Karm** [comment]
Hello @JiriOndrusek, 

I reproduced the issue and I managed to successfully use a known workaround. I will close this ticket as it's not a Quarkus bug.

The issue is tracked as: https://issues.redhat.com/browse/RHEL-3478

## How to make it work

This is verbatim what I did and it made it work *including* native builds that passes tests:   (JAVA_OPTS one is likely superfluous)

```
$ java --version
openjdk 17.0.12 2024-07-16 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.12.0.7-1) (build 17.0.12+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.12.0.7-1) (build 17.0.12+7-LTS, mixed mode, sharing)

$ sysctl crypto.fips_enabled
crypto.fips_enabled = 1

$ uname -a
Linux rhel9fips 5.14.0-63.el9.x86_64 #1 SMP PREEMPT Thu Feb 17 17:02:42 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

$ ./mvnw install -Dquickly
...

$ export JAVA_OPTS=-Djava.security.properties=/home/karm/camel-quarkus/extra.properties

$ export MAVEN_OPTS=-Djava.security.properties=/home/karm/camel-quarkus/extra.properties

$ mvn clean install verify -Ddocker -Pnative -f integration-tests/lumberjack -Dquarkus.native.builder-image=registry.access.redhat.com/quarkus/mandrel-for-jdk-21-rhel8 -Dquarkus.native.container-runtime=podman
```

The contents of my `/home/karm/camel-quarkus/extra.properties` is  this:
```
securerandom.strongAlgorithms=PKCS11:SunPKCS11-NSS-FIPS
```

Hope it helps
Cheers

**Comment by JiriOndrusek** [comment]
Thank you for the workaround!

**Comment by JiriOndrusek** [comment]
Hi @Karm , workaround works well. I was wondering whether it would be possible to create a `fips` maven profile, which would take care of this configuration. I was trying to use configuration of `quarkus-maven-plugin` ([jvmArgs], (https://quarkus.io/guides/quarkus-maven-plugin#quarkus-maven-plugin-goal-test-jvmargs)), but with no success. Do you think that implementing this workaround to maven profile is possible?
