### ISSUE TITLE
Recursive mapping issue with JSON-B (despite custom serializers)

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#42442]
### Describe the bug

Class structures that contain a recursive reference can't be mapped to JSON, even though when one defines custom JSON-B serializers or type adapters. This doesn't really make sense, since serializing (back) references to, for example, scalar values stops the recursion.

### Expected behavior

Make it possible to serialize recursive references when custom serializers / type adapters are present. 

### How to Reproduce?

Reproducer here: https://github.com/sdaschner/quarkus-playground/releases/tag/jsonb-recursive-mapping

```
mvn quarkus:dev
curl localhost:8080/json-test
```

(or run `JsonIT` in the project)

This will cause Quarkus to throw an exception like:

```
Caused by: jakarta.json.bind.JsonbException: Unable to serialize property 'schedule' from com.sebastian_daschner.coffee.JsonTestResource.Item
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.lambda$serialize$0(ObjectSerializer.java:43)
[...]
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.lambda$serialize$0(ObjectSerializer.java:41)
	... 25 more
Caused by: jakarta.json.bind.JsonbException: Recursive reference has been found in class class com.sebastian_daschner.coffee.JsonTestResource$Schedule.
	at org.eclipse.yasson.internal.serializer.RecursionChecker.serialize(RecursionChecker.java:36)
[...]
```

As you can see in the code (`Schedule` -> `Item`), the back reference `Item#schedule` is annotated with `@JsonbTypeSerializer(ScheduleNameSerializer.class)`. Only if *also* the reference `Schedule#item` is annotated with a similar serializer, it works. Adding `@JsonbTransient` on the back reference also works.

However, the following output would be expected from that test:

```json
{
  "item": {
    "name": "Item",
    "schedule": "Name"
  },
  "name": "Name"
}
```

### Quarkus version or git rev

3.13.0

**Comment by geoand** [comment]
Thanks for reporting. 

This actually looks like a Yasson issue to be honest.

**Comment by sdaschner** [comment]
Is there a way that this can be fixed in Yasson then?

**Comment by geoand** [comment]
I propose opening an issue on the Yasson [repo](https://github.com/eclipse-ee4j/yasson) and taking it up with the folks that develop it.

🙏🏽
