### ISSUE TITLE
Hibernate ORM enhanced field access sometimes (randomly?) returning `null`

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#42479]
One test in the Hibernate ORM extension is failing from time to time and being marked as flaky: `io.quarkus.hibernate.orm.applicationfieldaccess.PublicFieldAccessInheritanceTest.testFieldAccess`

We get this error:

```
java.lang.AssertionError: 

Expecting actual not to be null
	at io.quarkus.hibernate.orm.applicationfieldaccess.PublicFieldAccessInheritanceTest$FieldAccessEnhancedDelegate$1.assertValue(PublicFieldAccessInheritanceTest.java:132)
	at io.quarkus.hibernate.orm.applicationfieldaccess.PublicFieldAccessInheritanceTest.doTestFieldAccess(PublicFieldAccessInheritanceTest.java:91)
	at io.quarkus.hibernate.orm.applicationfieldaccess.PublicFieldAccessInheritanceTest.testFieldAccess(PublicFieldAccessInheritanceTest.java:52)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at io.quarkus.test.QuarkusUnitTest.runExtensionMethod(QuarkusUnitTest.java:499)
```

It seems it's been flaky since at least April 16, see the test history (loading will take a while): https://ge.quarkus.io/scans/tests?search.relativeStartTime=P900D&search.timeZoneId=Europe%2FParis&tests.container=io.quarkus.hibernate.orm.applicationfieldaccess.PublicFieldAccessInheritanceTest&tests.test=testFieldAccess#

The first PR to see this test as flaky  is https://github.com/quarkusio/quarkus/pull/40329 (formerly https://github.com/quarkusio/quarkus/pull/40160), and that PR seems way too related to the test (bytecode enhancement) for this to be a coincidence... @Sanne this may be a bug caused by the changes in that PR?

Originally mentioned here:

              @yrodiere @marko-bekhta the flaky test is a bit concerning here ^

_Originally posted by @gsmet in https://github.com/quarkusio/quarkus/issues/42455#issuecomment-2282659586_

**Comment by yrodiere** [comment]
> The first PR to see this test as flaky is #40329 (formerly #40160), and that PR seems way too related to the test (bytecode enhancement) for this to be a coincidence... @Sanne this may be a bug caused by the changes in that PR?

Actually after that PR was merged, the test wasn't flaky until August 1st...

So I think it's more likely that @Sanne had a problem in his PR that caused flakiness, but fixed it, and then sometime before August 1st another changed happened that caused this flakiness to reappear, probably for a different reason...

What change, you ask? I don't know, but it's got to be something shortly before https://github.com/quarkusio/quarkus/pull/42264

**Comment by Sanne** [comment]
This will be tricky unfortunately.
When working on that patch I remember having to figure out other, often unrelatd, race conditions, as making things faster sometimes highlights latent issues in other areas. I suppose this could be triggered by other optimisations, or potentially other fixes in combination with that one.

I'd not be keen to add "slowness" here and there :) and I doubt the issue is caused by semantic changes in my PR (although that's not entirely to be ruled out either); I'm afraid someone will need dig deep and find the deep reason.

**Comment by yuhaibohotmail** [comment]
Is there any progress on this bug? One of my projects uses Hibernate inheritance. Is it unsafe to upgrade to 3.14?

**Comment by yrodiere** [comment]
There is no progress at the moment. As this has not been investigated yet, I cannot provide guidance.
What's for sure is this only affects applications whose entities contain public fields -- if you're using getters and setters, you will be fine.

**Comment by yuhaibohotmail** [comment]
Thanks a lot!
Unfortunately, the project uses  public fields  with Panache, it seems I still need to wait for your investigation.

**Comment by FroMage** [comment]
> Unfortunately, the project uses public fields with Panache, it seems I still need to wait for your investigation.

Actually, ORM with Panache does not use the ORM public fields system, so you should be safe with Panache. Under the hood, Panache will turn all public fields into protected fields with accessors. It's transparent to you, but this ensures that Hibernate-generated accessors are used (for lazy loading and dirty tracking).

**Comment by yrodiere** [comment]
@FroMage the failure happens in Quarkus, and nothing in Quarkus uses the ORM public fields system.

This bug happens precisely in a test that relies on Panache's own public fields system -- though Panache may not be at fault, there's probably some wrong interaction going on.

**Comment by FroMage** [comment]
> @FroMage the failure happens in Quarkus, and nothing in Quarkus uses the ORM public fields system.

Oh, I was misled by the title mentioning `Hibernate ORM enhanced field access`, sorry.

Damn.

**Comment by gsmet** [comment]
@yuhaibohotmail are you able to reproduce this issue reliably?

**Comment by yrodiere** [comment]
@gsmet I don't think so, they were simply worried about the bug and thus didn't want to upgrade.

As far as I know, this problem was only ever encountered on our CI; nobody else reported anything similar. It's entirely possible it's related to our test setup.

Anyway... I'm currently trying to reproducer the problem with this: https://github.com/quarkusio/quarkus/compare/main...yrodiere:quarkus:i42479-reproducer?expand=1
And I must say, so far I'm failing.

Which is not surprising if you consider that even on CI, [over the last 30 days](https://ge.quarkus.io/scans/tests?search.relativeStartTime=P30D&search.tags=Quarkus%20CI&search.timeZoneId=Europe%2FParis&tests.container=io.quarkus.hibernate.orm.applicationfieldaccess.PublicFieldAccessInheritanceTest&tests.test=testFieldAccess#) it passed 751 times and was flaky just 7 times... This fails less than 1% of the time even in a consistent environment :(

**Comment by yrodiere** [comment]
I managed to reproduce on CI here: https://github.com/yrodiere/quarkus/actions/runs/10847021422/job/30101850422
I need to wait for the job to finish to inspect bytecode, but I already managed to make a diff of logs between a success and a failure.

Here is a link to a diff (no bug on the left, bug on the right): https://www.diffchecker.com/bkbU1EEr/
Here's a gist with more data: https://gist.github.com/yrodiere/ca5a0706d729c410e8cac409c14e3852

Some early facts and hypotheses:

1. Enhancement logs appear in a different order relative to `ClassTransformingBuildStep` logs. Do these happen in parallel? At the very least they happen in undetermined order.
2. In the failing case, logs are missing traces of `EnhancementAsProxyLazinessInterceptor#forceInitialize` executing, as well as corresponding SQL execution, both when that interceptor executes and on flush. I'll wait until I have bytecode to tell for sure, but I suspect the entity classes were not bytecode enhanced at all.

**Comment by yrodiere** [comment]
> Something does not compute, to me. This test is not using Panache's public field -> accessor translator, is it? This appears to be pure ORM, and you said `nothing in Quarkus uses the ORM public fields system`, so I'm very confused.

It's pure ORM, but the ORM extension in Quarkus [depends on Panache Common](https://github.com/quarkusio/quarkus/blob/50b35a13cd970883536a24f83bbde141971bee5a/extensions/hibernate-orm/deployment/pom.xml#L44-L47) to [implement public field access enhancement](https://github.com/quarkusio/quarkus/blob/23d8a1c89cef48aaa6011168e7e480c1e2dbda4a/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java#L614-L618). Yeah I know, it's weird.

Now, I'm not saying the problem is in Panache. It could be in Panache (which performs the public field access enhancement), or it could be in ORM (which performs the lazy loading enhancement), or a combination of the two, or some race condition elsewhere, or...

**Comment by yrodiere** [comment]
Good point... There's something fishy for sure.

FWIW the bytecode is available now, so we can have a look on Monday: https://github.com/yrodiere/quarkus/actions/runs/10847021422/artifacts/1930485022

**Comment by yrodiere** [comment]
> Ok, actually in the failing case these do not happen at all:
> 
> ```
> DEBUG [org.hib.byt.enh.spi.Enhancer] (build-<SOME_ID>) Enhancing [io.quarkus.hibernate.orm.applicationfieldaccess.PublicFieldAccessInheritanceTest$MyAbstractEntity] as Entity
> DEBUG [org.hib.byt.enh.spi.Enhancer] (build-<SOME_ID>) Enhancing [io.quarkus.hibernate.orm.applicationfieldaccess.PublicFieldAccessInheritanceTest$MyMappedSuperclass] as MappedSuperclass
> ```

So this was just plain wrong, apparently I was confused by wildly different order in logs.

The mapped superclass _does_ get enhanced in the failing case, but at a different time.

Stéphane pointed out that judging from the logs, it would seem the relative order of ASM visitors is not the same in both cases. This is suspicious, so I'm going to try reproducing the bug again with more logs related to visitor order.

**Comment by yrodiere** [comment]
Looks like this stopped happening on CI shortly after September 13th: https://ge.quarkus.io/scans/tests?search.relativeStartTime=P90D&search.tags=Quarkus%20CI&search.timeZoneId=Europe%2FParis&tests.container=io.quarkus.hibernate.orm.applicationfieldaccess.PublicFieldAccessInheritanceTest&tests.test=testFieldAccess#

And right now I can't reproduce it anywhere, be it on my laptop or on CI. At this point it's not even a Heisenbug... :/

**Comment by yrodiere** [comment]
> And that's even when building over and over the exact commit that _did_ reproduce the bug at least once on CI

I wonder if a different CI environment is being used. since around September 13th. The performance profile does seem different since around then:

![Image](https://github.com/user-attachments/assets/d6c210ae-eca9-411f-b76e-33702490fabe)

One option would be simply different hardware or resource limits, leading to different likeliness to reproduce race conditions.

Another option, a bit more far-fetched, would be that we moved to another (newer?) micro version of the JDK, and that version has changes impacting this test one way or another.

**Comment by FroMage** [comment]
Well… If we can't reproduce it, even though it still exists, is it really still a bug?

**Comment by yrodiere** [comment]
Is it indeed.

Giving up and closing, let's reopen if someone actually encounters the problem. Their integration tests would likely fail.

In case someone needs to check whether the bug happened again on CI, here's the link for failures in the last 90 days: https://ge.quarkus.io/scans/tests?search.relativeStartTime=P90D&search.tags=Quarkus%20CI&search.timeZoneId=Europe%2FParis&tests.container=io.quarkus.hibernate.orm.applicationfieldaccess.PublicFieldAccessInheritanceTest&tests.test=testFieldAccess#

**Comment by yrodiere** [comment]
It's back, baby: 

https://github.com/quarkusio/quarkus/pull/46728#issuecomment-2725108384

https://ge.quarkus.io/scans/tests?search.timeZoneId=Europe%2FParis&tests.container=io.quarkus.hibernate.orm.applicationfieldaccess.PublicFieldAccessInheritanceTest&tests.test=testFieldAccess#

![Image](https://github.com/user-attachments/assets/a0060d95-a1bd-4edf-b95a-871a0b34a3db)

**Comment by yrodiere** [comment]
Some of the simplifications implemented in https://github.com/hibernate/hibernate-orm/pull/9831 _might_ resolve this by accident, simply by reducing concurrency and/or the number of moving parts... but I'm not holding my breath. Let's see when we next upgrade, as I think it'll get backported to 6.6.

**Comment by gsmet** [comment]
Thanks for your continued efforts on this!

**Comment by Sanne** [comment]
Indeed, awesome! Thanks @yrodiere and @beikov !

**Comment by bechhansen** [comment]
Does anyone have a way to temporary fix this? Currently my only workaround is to make all field private and add getters and setter. That would be a pretty big task.

**Comment by yrodiere** [comment]
> Does anyone have a way to temporary fix this? Currently my only workaround is to make all field private and add getters and setter. That would be a pretty big task.

As far as I know, no. The problem is related to concurrency during the build, which you can't really control unless you rebuild Hibernate ORM or Quarkus.

However tomorrow is Wednesday, and a little bird told me Wednesday is release day, so... you could wait until tomorrow and upgrade to Quarkus 3.20.something/3.21.something?

cc @gsmet, who will know better than I do.

**Comment by yrodiere** [comment]
By the way, the fix (ORM upgrade) was merged on April 2nd, and here's how tests look like now:

![Image](https://github.com/user-attachments/assets/60ce6877-1058-4981-a55c-d0c5bc3c2881)

It's certainly looking good :)
