### ISSUE TITLE
Version parsing fails with master GraalVM built with latest Labs JDK 24 ea

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#42516]
When `native-image --version` contains this:

```
native-image 24-ea 2025-03-18
OpenJDK Runtime Environment Oracle GraalVM 24-dev.ea+10.1 (build 24-ea+10-1076)
OpenJDK 64-Bit Server VM Oracle GraalVM 24-dev.ea+10.1 (build 24-ea+10-1076, mixed mode, sharing)
```

Version parsing fails with:

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.11.0:build (default) on project getting-started-reactive: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to get GraalVM version
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildRunner.getGraalVMVersion(NativeImageBuildRunner.java:40)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:217)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:588)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1575)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
[ERROR] Caused by: java.lang.NumberFormatException: For input string: "null"
[ERROR] 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[ERROR] 	at java.base/java.lang.Integer.parseInt(Integer.java:563)
[ERROR] 	at java.base/java.lang.Integer.parseInt(Integer.java:660)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:232)
[ERROR] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:636)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
[ERROR] 	at java.base/java.util.stream.IntPipeline.toArray(IntPipeline.java:565)
[ERROR] 	at io.quarkus.deployment.pkg.steps.GraalVM$Version.breakdownVersion(GraalVM.java:231)
[ERROR] 	at io.quarkus.deployment.pkg.steps.GraalVM$Version.<init>(GraalVM.java:220)
[ERROR] 	at io.quarkus.deployment.pkg.steps.GraalVM$VersionParseHelper.parse(GraalVM.java:88)
[ERROR] 	at io.quarkus.deployment.pkg.steps.GraalVM$Version.of(GraalVM.java:297)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildRunner.getGraalVMVersion(NativeImageBuildRunner.java:37)
[ERROR] 	... 11 more
```

This can be replicated with this bogus test added to `GraalVMTest`:

```
        assertVersion(new Version("GraalVM 23.0.0", "23.0.0", GRAALVM), MANDREL,
            Version.of(Stream.of(("native-image 24-ea 2025-03-18\n"
                        + "OpenJDK Runtime Environment Oracle GraalVM 24-dev.ea+10.1 (build 24-ea+10-1076)\n"
                        + "OpenJDK 64-Bit Server VM Oracle GraalVM 24-dev.ea+10.1 (build 24-ea+10-1076, mixed mode, sharing)").split("\\n"))));
```

GraalVM is built with `mx build` and the latest Labs JDK which is required by oracle/graal master.

**Comment by jerboaa** [comment]
GraalVM Community dev builds have this version output:

```
$ ./graalvm-community-openjdk-24+9.1/bin/native-image --version
native-image 24 2025-03-18
GraalVM Runtime Environment GraalVM CE 24-dev+9.1 (build 24+9-jvmci-b01)
Substrate VM GraalVM CE 24-dev+9.1 (build 24+9, serial gc)
```

So it looks like your built didn't build the native-image of the native image launcher (bash launcher).

**Comment by galderz** [comment]
Yeah, it's just the bash launcher that you get when you call `mx build` from `substratevm`.
