### ISSUE TITLE
WARNING: Thread locked for more than 60000ms when launching a full build

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#4257]
**Describe the bug**
When launching a full Quarkus build from master, I have this warning
```
2019-09-29 12:39:56,579 WARN  [org.apa.act.art.cor.client] (vert.x-worker-thread-0) AMQ212054: Destination address=test-core is blocked. If the system is configured to block make sure you consume messages on this configuration.
2019-09-29 12:39:58,330 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-worker-thread-0,5,main]=Thread[vert.x-worker-thread-0,5,main] has been blocked for 1302641 ms, time limit is 60000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
	at java.base@11.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	at java.base@11.0.2/java.util.concurrent.Semaphore.tryAcquire(Semaphore.java:592)
	at app//org.apache.activemq.artemis.core.client.impl.ClientProducerCreditsImpl.actualAcquire(ClientProducerCreditsImpl.java:73)
	at app//org.apache.activemq.artemis.core.client.impl.AbstractProducerCreditsImpl.acquireCredits(AbstractProducerCreditsImpl.java:77)
	at app//org.apache.activemq.artemis.core.client.impl.ClientProducerImpl.sendRegularMessage(ClientProducerImpl.java:301)
	at app//org.apache.activemq.artemis.core.client.impl.ClientProducerImpl.doSend(ClientProducerImpl.java:275)
	at app//org.apache.activemq.artemis.core.client.impl.ClientProducerImpl.send(ClientProducerImpl.java:121)
	at app//io.quarkus.it.artemis.ArtemisProducerManager.send(ArtemisProducerManager.java:30)
	at app//io.quarkus.it.artemis.ArtemisProducerManager_ClientProxy.send(ArtemisProducerManager_ClientProxy.zig:129)
	at app//io.quarkus.it.artemis.ArtemisEndpoint.post(ArtemisEndpoint.java:19)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.2/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
	at app//org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
	at app//org.jboss.resteasy.core.MethodInjectorImpl$$Lambda$713/0x00000008006f4840.apply(Unknown Source)
	at java.base@11.0.2/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base@11.0.2/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base@11.0.2/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at java.base@11.0.2/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
	at app//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
	at app//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:594)
	at app//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:468)
	at app//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:421)
	at app//org.jboss.resteasy.core.ResourceMethodInvoker$$Lambda$709/0x00000008006f6840.get(Unknown Source)
	at app//org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at app//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:423)
	at app//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at app//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:365)
	at app//org.jboss.resteasy.core.ResourceMethodInvoker$$Lambda$708/0x00000008006f7440.apply(Unknown Source)
	at java.base@11.0.2/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base@11.0.2/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base@11.0.2/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at app//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
	at app//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
	at app//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at app//org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$704/0x00000008006f2c40.run(Unknown Source)
	at app//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at app//org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$705/0x00000008006f7840.get(Unknown Source)
	at app//org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at app//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at app//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at app//io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:69)
	at app//io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:81)
	at app//io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatchRequestContext(VertxRequestHandler.java:64)
	at app//io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:55)
	at app//io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$$Lambda$701/0x00000008006f1c40.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$703/0x00000008006f2840.run(Unknown Source)
	at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.2/java.lang.Thread.run(Thread.java:834)
```
**Expected behavior**
Thread to not be locked for more than the default limit `1m`
**Actual behavior**
The warning above appears over and over. 

**To Reproduce**
1. `mvn clean install` on the current master

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin xxx 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_6`
 - Output of `java -version`:  
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: `master` - https://github.com/quarkusio/quarkus/commit/c7ea31bba69b707d794923fe3b670e078e19ffc1

**Comment by geoand** [comment]
@machi1990 Thanks for reporting.
Since you are using master, could you please add the sha of the commit? There are various things that are being done that might affect this so it would be great to know the exact version which you used to reproduce the problem

**Comment by machi1990** [comment]
Thanks @geoand , I have updated the issue with the sha of the commit.

**Comment by gsmet** [comment]
@machi1990 do you still reproduce this one?

**Comment by machi1990** [comment]
Let me run a full build to see if the issue is still present. If not, we can close this one. Thanks

**Comment by machi1990** [comment]
Closing, could not reproduce this with latest master 52ee9d0b2322dc509158c8a6f2395f71534968c5
