### ISSUE TITLE
ClassNotFoundException with langchain4j 0.17 and Quarkus 3.13.3 

### ISSUE THREAD

**Issue by jonathanvila** [quarkusio/quarkus#42681]
### Describe the bug

After executing quarkus:dev on a new empty project directly downloaded from code.quarkus.io with langchain4j I receive a ClassNotFoundException

```
2024-08-21 16:27:39,108 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.NoClassDefFoundError: dev/langchain4j/service/output/ServiceOutputParser
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at io.quarkus.deployment.util.ServiceUtil.classesNamedIn(ServiceUtil.java:29)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:160)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:106)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:254)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:58)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:91)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:430)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:57)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.ClassNotFoundException: dev.langchain4j.service.output.ServiceOutputParser
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:561)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:509)
        ... 16 more
```

### Expected behavior

to start the dev mode normally

### Actual behavior

It shows the exception in the output

### How to Reproduce?

1. go to code.quarkus.io
2. generate a project with langchain4j, ollama, rest, camel-langchain4j
3. download and unzip
4. mvn quarkus:dev

### Output of `uname -a` or `ver`

Darwin MAC-L0153 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode)

### Quarkus version or git rev

3.13.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9) Maven home: /Users/jonathan.vila/.sdkman/candidates/maven/current Java version: 21.0.2, vendor: Eclipse Adoptium, runtime: /Users/jonathan.vila/.sdkman/candidates/java/21.0.2-tem Default locale: en_GB, platform encoding: UTF-8 OS name: "mac os x", version: "14.6.1", arch: "aarch64", family: "mac"

### Additional information

Changing it manually to Langchain4j and ollama to 0.16 fixes the issue

**Comment by gsmet** [comment]
Please report it in the Quarkus Langchain4j project here: https://github.com/quarkiverse/quarkus-langchain4j/issues (it's a different org, I can't move the issue).

If it ends up being a Quarkus issue, they will open an issue with more details here.

**Comment by jonathanvila** [comment]
Thank you @gsmet . I've opened the new issue on quarkiverse.

**Comment by jordensy** [comment]
> IIRC, the problem was mismatching versions

Any idea which versions do Match?
