### ISSUE TITLE
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true fails native build of StartStopTS microprofile application

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#42774]
### Describe the bug

As suggested in https://github.com/quarkusio/quarkus/issues/42506#issuecomment-2311076936 I tried to run RSS check with `quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true` added to the sample microprofile application (https://github.com/rsvoboda/quarkus-startstop/tree/reactive-jackson-and-health/app-full-microprofile).

Unfortunately, native image build fails when this property is added. I'm using `mvn -f app-full-microprofile clean package -Dnative -Dquarkus.version=999-SNAPSHOT -Dquarkus.rest.jackson.optimization.enable-reflection-free-serializers=true` command.

Native compilation has issue with https://github.com/rsvoboda/quarkus-startstop/blob/reactive-jackson-and-health/app-full-microprofile/src/main/java/com/example/quarkus/serialization/dto/NestedInterface.java. Native compilation without enable-reflection-free-serializers property works well.

Message from the build:
`Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Discovered unresolved method during parsing: com.example.quarkus.serialization.dto.NestedInterface.getCharacter(). This error is reported at image build time because class com.example.quarkus.serialization.dto.NestedInterface$quarkusjacksonserializer is registered for linking at image build time by command line and command line.`

Detailed stack trace:
```
[2/8] Performing analysis...  [08:41:30,400 WARN  [io.net.res.dns.DnsServerAddressStreamProviders] Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'
*****]                                                                   (11.9s @ 1.00GB)
   12,391 reachable types   (87.2% of   14,208 total)
   17,617 reachable fields  (57.0% of   30,904 total)
   63,763 reachable methods (57.3% of  111,277 total)
    3,907 types,   140 fields, and 3,314 methods registered for reflection
       62 types,    67 fields, and    55 methods registered for JNI access
        5 native libraries: -framework CoreServices, -framework Foundation, dl, pthread, z

Error: Discovered unresolved method during parsing: com.example.quarkus.serialization.dto.NestedInterface.getCharacter(). This error is reported at image build time because class com.example.quarkus.serialization.dto.NestedInterface$quarkusjacksonserializer is registered for linking at image build time by command line and command line.
Error encountered while parsing com.example.quarkus.serialization.dto.NestedInterface$quarkusjacksonserializer.serialize(Unknown Source)
Parsing context:
   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:490)
   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:334)
   at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4799)
   at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4040)
   at io.vertx.core.json.jackson.DatabindCodec.toString(DatabindCodec.java:163)
   at io.vertx.core.json.JsonObject.encode(JsonObject.java:1034)
   at io.vertx.core.json.JsonObject.toString(JsonObject.java:1158)
   at root method.(Unknown Source)

Detailed message:

com.oracle.svm.core.util.UserError$UserException: Discovered unresolved method during parsing: com.example.quarkus.serialization.dto.NestedInterface.getCharacter(). This error is reported at image build time because class com.example.quarkus.serialization.dto.NestedInterface$quarkusjacksonserializer is registered for linking at image build time by command line and command line.
Error encountered while parsing com.example.quarkus.serialization.dto.NestedInterface$quarkusjacksonserializer.serialize(Unknown Source)
Parsing context:
   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:490)
   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:334)
   at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4799)
   at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4040)
   at io.vertx.core.json.jackson.DatabindCodec.toString(DatabindCodec.java:163)
   at io.vertx.core.json.JsonObject.encode(JsonObject.java:1034)
   at io.vertx.core.json.JsonObject.toString(JsonObject.java:1158)
   at root method.(Unknown Source)

Detailed message:

	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:814)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Discovered unresolved method during parsing: com.example.quarkus.serialization.dto.NestedInterface.getCharacter(). This error is reported at image build time because class com.example.quarkus.serialization.dto.NestedInterface$quarkusjacksonserializer is registered for linking at image build time by command line and command line.
Error encountered while parsing com.example.quarkus.serialization.dto.NestedInterface$quarkusjacksonserializer.serialize(Unknown Source)
Parsing context:
   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:490)
   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:334)
   at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4799)
   at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4040)
   at io.vertx.core.json.jackson.DatabindCodec.toString(DatabindCodec.java:163)
   at io.vertx.core.json.JsonObject.encode(JsonObject.java:1034)
   at io.vertx.core.json.JsonObject.toString(JsonObject.java:1158)
   at root method.(Unknown Source)

Detailed message:

	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:809)
	... 6 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.example.quarkus.serialization.dto.NestedInterface.getCharacter(). This error is reported at image build time because class com.example.quarkus.serialization.dto.NestedInterface$quarkusjacksonserializer is registered for linking at image build time by command line and command line.
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:550)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:544)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:471)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:368)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1740)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5439)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3431)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.iterateBytecodesForBlock(SharedGraphBuilderPhase.java:743)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3391)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3233)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1137)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.build(SharedGraphBuilderPhase.java:162)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1029)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:101)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:116)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:434)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:146)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.parseGraph(AnalysisMethod.java:895)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsedHelper(AnalysisMethod.java:860)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:843)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:186)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:621)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:167)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:153)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraphInfo(MethodTypeFlow.java:111)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:114)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:620)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:491)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

### Expected behavior

Native image get properly produced.

### Actual behavior

Native image build fails

### How to Reproduce?

```
sdk use java 21.0.2-graalce
git clone https://github.com/rsvoboda/quarkus-startstop -b reactive-jackson-and-health
mvn -f app-full-microprofile clean package -Dnative -Dquarkus.version=999-SNAPSHOT -Dquarkus.rest.jackson.optimization.enable-reflection-free-serializers=true
```

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 21

### Quarkus version or git rev

Quarkus main

**Comment by geoand** [comment]
Very interesting indeed.

Seems like when we add a fix, we'll need an integration test as well.

**Comment by zakkak** [comment]
FTR

This turned out to be related to an `invokevirtual` bytecode being used on an interface method instead of `invokeinterface`.

The stacktrace leading to the generation of an `UnresolvedJavaMethod` (which then lead to the error reported above) was:

```
<init>:34, UnresolvedJavaMethod (jdk.vm.ci.meta)
lookupMethod:724, HotSpotConstantPool (jdk.vm.ci.hotspot)
invokeInterface:-1, LambdaForm$DMH/0x0000000801abd000 (java.lang.invoke)
invoke:-1, LambdaForm$MH/0x0000000801b21000 (java.lang.invoke)
invokeExact_MT:-1, LambdaForm$MH/0x00000008000d8c00 (java.lang.invoke)
invokeImpl:156, DirectMethodHandleAccessor (jdk.internal.reflect)
invoke:103, DirectMethodHandleAccessor (jdk.internal.reflect)
invoke:580, Method (java.lang.reflect)
lookupMethod:134, WrappedConstantPool (com.oracle.graal.pointsto.infrastructure)
invokeInterface:-1, LambdaForm$DMH/0x0000000801abd000 (java.lang.invoke)
invoke:-1, LambdaForm$MH/0x0000000801b21000 (java.lang.invoke)
invokeExact_MT:-1, LambdaForm$MH/0x00000008000d8c00 (java.lang.invoke)
invokeImpl:156, DirectMethodHandleAccessor (jdk.internal.reflect)
invoke:103, DirectMethodHandleAccessor (jdk.internal.reflect)
invoke:580, Method (java.lang.reflect)
lookupMethodWithCaller:458, GraalServices (org.graalvm.compiler.serviceprovider)
lookupMethodInPool:4333, BytecodeParser (org.graalvm.compiler.java)
lookupMethodInPool:210, SharedGraphBuilderPhase$SharedBytecodeParser (com.oracle.svm.hosted.phases)
lookupMethod:4325, BytecodeParser (org.graalvm.compiler.java)
genInvokeVirtual:1731, BytecodeParser (org.graalvm.compiler.java)
processBytecode:5414, BytecodeParser (org.graalvm.compiler.java)
iterateBytecodesForBlock:3426, BytecodeParser (org.graalvm.compiler.java)
iterateBytecodesForBlock:743, SharedGraphBuilderPhase$SharedBytecodeParser (com.oracle.svm.hosted.phases)
handleBytecodeBlock:3386, BytecodeParser (org.graalvm.compiler.java)
processBlock:3228, BytecodeParser (org.graalvm.compiler.java)
build:1137, BytecodeParser (org.graalvm.compiler.java)
build:162, SharedGraphBuilderPhase$SharedBytecodeParser (com.oracle.svm.hosted.phases)
buildRootMethod:1029, BytecodeParser (org.graalvm.compiler.java)
run:101, GraphBuilderPhase$Instance (org.graalvm.compiler.java)
run:116, SharedGraphBuilderPhase (com.oracle.svm.hosted.phases)
run:49, Phase (org.graalvm.compiler.phases)
apply:434, BasePhase (org.graalvm.compiler.phases)
apply:42, Phase (org.graalvm.compiler.phases)
apply:38, Phase (org.graalvm.compiler.phases)
parseBytecode:146, AnalysisParsedGraph (com.oracle.graal.pointsto.flow)
parseGraph:895, AnalysisMethod (com.oracle.graal.pointsto.meta)
ensureGraphParsedHelper:860, AnalysisMethod (com.oracle.graal.pointsto.meta)
ensureGraphParsed:843, AnalysisMethod (com.oracle.graal.pointsto.meta)
parse:186, MethodTypeFlowBuilder (com.oracle.graal.pointsto.flow)
apply:621, MethodTypeFlowBuilder (com.oracle.graal.pointsto.flow)
createFlowsGraph:167, MethodTypeFlow (com.oracle.graal.pointsto.flow)
ensureFlowsGraphCreated:153, MethodTypeFlow (com.oracle.graal.pointsto.flow)
getOrCreateMethodFlowsGraphInfo:111, MethodTypeFlow (com.oracle.graal.pointsto.flow)
onObservedUpdate:114, DefaultVirtualInvokeTypeFlow (com.oracle.graal.pointsto.typestate)
update:620, TypeFlow (com.oracle.graal.pointsto.flow)
run:491, PointsToAnalysis$1 (com.oracle.graal.pointsto)
executeCommand:187, CompletionExecutor (com.oracle.graal.pointsto.util)
lambda$executeService$0:171, CompletionExecutor (com.oracle.graal.pointsto.util)
run:-1, CompletionExecutor$$Lambda/0x0000000801b488b0 (com.oracle.graal.pointsto.util)
exec:1423, ForkJoinTask$RunnableExecuteAction (java.util.concurrent)
doExec:387, ForkJoinTask (java.util.concurrent)
topLevelExec:1312, ForkJoinPool$WorkQueue (java.util.concurrent)
scan:1843, ForkJoinPool (java.util.concurrent)
runWorker:1808, ForkJoinPool (java.util.concurrent)
run:188, ForkJoinWorkerThread (java.util.concurrent)
```
