### ISSUE TITLE
 io.quarkus.grpc.cli.GrpcCliTest.testCommand fails CI and makes it next to impossible to get green CI

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#42819]
### Description

I am experiencing in this PR https://github.com/quarkusio/quarkus/pull/42749 that after several runs I can't get green CI because of this test. According to the build scan history https://ge.quarkus.io/scans/tests?search.timeZoneId=Europe%2FPrague&tests.container=io.quarkus.grpc.cli.GrpcCliTest&tests.test=testCommand it is not just my PR. For example I found same failure in https://github.com/quarkusio/quarkus/pull/42700 from @gsmet. I believe we need to disable this test with link to this issue so that the issue is not forgotten, but also, other PRs are not blocked.

**Comment by alesj** [comment]
Yeah, this just won't go away ... and the problem is probably not the test, it's something more general ... @gsmet should know more.

**Comment by cescoffier** [comment]
@gsmet @alesj any news about this one?

**Comment by holly-cummins** [comment]
Adding stack traces for ease of future searching. I'm seeing problems with this test while working on https://github.com/orgs/quarkusio/projects/30, so it's possible that #34681 has made it worse, or it could be that my changes (temporarily) exposed the existing issue despite the `@Disabled`. The exception is the same, `IllegalStateException`, so in the absence of more information I'm choosing to believe it was the existing issue. I see it in CI, but not locally. (I've stopped the problem in my branch by checking for `@Disabled` earlier than I had been doing, so we don't attempt to load the class.)

```
 Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: ]: Build step io.quarkus.vertx.http.deployment.VertxHttpProcessor#cors threw an exception: java.lang.IllegalStateException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:281)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.getProxyInstance(BytecodeRecorderImpl.java:421)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl$1.invoke(BytecodeRecorderImpl.java:363)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl$$RecordingProxyProxy24.corsHandler(Unknown Source)
	at io.quarkus.vertx.http.deployment.VertxHttpProcessor.cors(VertxHttpProcessor.java:152)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:499)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.quarkus.deployment.proxy.InjectIntoClassloaderClassOutput.write(InjectIntoClassloaderClassOutput.java:42)
	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:246)
	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:257)
	at io.quarkus.deployment.proxy.ProxyFactory.doDefineClass(ProxyFactory.java:245)
	at io.quarkus.deployment.proxy.ProxyFactory.defineClass(ProxyFactory.java:150)
	at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:260)
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.proxy.InjectIntoClassloaderClassOutput.write(InjectIntoClassloaderClassOutput.java:40)
	... 19 more
Caused by: java.lang.LinkageError: loader constraint violation: loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @f3876ef wants to load interface io.vertx.core.Handler. A different interface with the same name was previously loaded by io.quarkus.bootstrap.classloading.QuarkusClassLoader @38667005. (io.vertx.core.Handler is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @38667005, parent loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:575)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:523)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:889)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.visibleDefineClass(QuarkusClassLoader.java:734)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 21 more
```

**Comment by holly-cummins** [comment]
What I'm seeing (caveat, this in my #34681 branch, but may be useful for future debugging) is that it's loaded first by the augmentation loader, and then by the deployment loader. 

```
2025-02-25T16:20:41.8698994Z HOLLY loading io.vertx.core.Handler with QuarkusClassLoader:Augmentation Class Loader: TEST for JUnitQuarkusTest-no-profile (QuarkusTest)@6b091a92
...
2025-02-25T16:20:42.3161055Z HOLLY loading io.vertx.core.Handler with QuarkusClassLoader:Deployment Class Loader: TEST for JUnitQuarkusTest-no-profile (QuarkusTest)@6697f3d
...
2025-02-25T16:20:42.3463129Z Caused by: java.lang.LinkageError: loader constraint violation: loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6697f3d wants to load interface io.vertx.core.Handler. A different interface with the same name was previously loaded by io.quarkus.bootstrap.classloading.QuarkusClassLoader @6b091a92. (io.vertx.core.Handler is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6b091a92, parent loader 'app')
```

**Comment by cescoffier** [comment]
So, we have a new log category: `HOLLY` :-) 

Handler is an interface. I think there are several places where we pass references to Handler from the build time to the runtime (routes, for example).

**Comment by holly-cummins** [comment]
> So, we have a new log category: `HOLLY` :-)

You'll be reassured to know I'm planning to take all those out before submitting the PR. :) 

On the other hand, I did once leave a `HOLLY` log in the startup sequence of another product and we had to do an emergency respin of the release to fix it, so maybe you shoudn't be all that reassured. :)
