### ISSUE TITLE
Duplicate annotation for class: interface org.jetbrains.annotations.NotNull

### ISSUE THREAD

**Issue by kronst** [quarkusio/quarkus#42828]
### Describe the bug

During upgrade Quarkus version from **3.6.9** to **3.11.3** in my Kotlin application I faced a bug related to generated annotations that appears in runtime. After some investigation I found that Quarkus 3.11.3 generates different transformed classes for my sources.
Looks like after upgrade all parameter annotations moved out from the method signature and became method annotations.
In my case since `@org.jetbrains.annotations.NotNull` annotation is non-repeatable this leads to an exception in runtime during transactional method execution.

```bash
java.lang.annotation.AnnotationFormatError: Duplicate annotation for class: interface org.jetbrains.annotations.NotNull: @org.jetbrains.annotations.NotNull(exception=java.lang.Exception.class, value="")
    at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:126)
    at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
    at java.lang.reflect.Executable.declaredAnnotations(Executable.java:625)
    at java.lang.reflect.Executable.declaredAnnotations(Executable.java:623)
    at java.lang.reflect.Executable.getAnnotation(Executable.java:591)
    at java.lang.reflect.Method.getAnnotation(Method.java:738)
    at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.getTransactionConfiguration(TransactionalInterceptorBase.java:91)
    at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.checkConfiguration(TransactionalInterceptorBase.java:348)
    at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInCallerTx(TransactionalInterceptorBase.java:334)
    at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:40)
    at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
    at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
    at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept
    at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
    at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
    at io.quarkus.arc.impl.InterceptedStaticMethods.aroundInvoke(InterceptedStaticMethods.java:22)
```

### Expected behavior

Parameters' annotations stays in method signature (Quarkus **3.6.9**)

```java
package com.kronst;

import com.kronst.IService.DefaultImpls_InterceptorInitializer;
import jakarta.transaction.Transactional;
import java.time.Instant;
import kotlin.Metadata;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

@Metadata(
   mv = {1, 9, 0},
   k = 3,
   xi = 48
)
public final class IService$DefaultImpls {
   @Transactional
   public static void function1_orig(@NotNull IService $this, long id, @NotNull Status status, @Nullable Instant until) {
      Intrinsics.checkNotNullParameter(status, "status");
   }

   @Transactional
   public static void function2_orig(@NotNull IService $this, long id, @Nullable Instant until) {
   }

   public static void function1(IService var0, long var1, Status var3, Instant var4) {
      DefaultImpls_InterceptorInitializer._3958639534e32dc52daf8ac793f8398ec16e4bcb(var0, var1, var3, var4);
   }

   public static void function2(IService var0, long var1, Instant var3) {
      DefaultImpls_InterceptorInitializer._ece9dbc791adcc6c870168f7c5d71433a069413b(var0, var1, var3);
   }
}
```

### Actual behavior

Parameters' annotations duplicates as method annotations (Quarkus **3.11.3**)
```java
package com.kronst;

import com.kronst.IService.DefaultImpls_InterceptorInitializer;
import jakarta.transaction.Transactional;
import java.time.Instant;
import kotlin.Metadata;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

@Metadata(
   mv = {1, 9, 0},
   k = 3,
   xi = 48
)
public final class IService$DefaultImpls {
   @Transactional
   public static void function1_orig(@NotNull IService $this, long id, @NotNull Status status, @Nullable Instant until) {
      Intrinsics.checkNotNullParameter(status, "status");
   }

   @Transactional
   public static void function2_orig(@NotNull IService $this, long id, @Nullable Instant until) {
   }

   @Transactional
   @NotNull
   @NotNull
   @Nullable
   public static void function1(IService var0, long var1, Status var3, Instant var4) {
      DefaultImpls_InterceptorInitializer._3958639534e32dc52daf8ac793f8398ec16e4bcb(var0, var1, var3, var4);
   }

   @Transactional
   @NotNull
   @Nullable
   public static void function2(IService var0, long var1, Instant var3) {
      DefaultImpls_InterceptorInitializer._ece9dbc791adcc6c870168f7c5d71433a069413b(var0, var1, var3);
   }
}
```

### How to Reproduce?

Use Quarkus **3.11.3**
Use Kotlin **1.9.20**

Gradle dependencies:
```kts
val quarkusPlatformVersion: String by project // 3.11.3

dependencies {
    implementation(enforcedPlatform("io.quarkus.platform:quarkus-bom:${quarkusPlatformVersion}"))

    implementation("io.quarkus:quarkus-kotlin")
    implementation("io.quarkus:quarkus-arc")

    implementation("io.quarkus:quarkus-hibernate-orm")
    implementation("io.quarkus:quarkus-hibernate-orm-panache")
    implementation("io.quarkus:quarkus-hibernate-orm-panache-kotlin")
    implementation("io.quarkus:quarkus-jdbc-postgresql")

    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    testImplementation("io.quarkus:quarkus-junit5")
}
```
Example source code:
```kotlin
package com.kronst

import jakarta.enterprise.context.ApplicationScoped
import jakarta.transaction.Transactional
import java.time.Instant

enum class Status {
    OPEN,
    CLOSED,
}

interface IService {

    @Transactional
    fun function1(id: Long, status: Status, until: Instant?) {
        /* default implementation */
    }

    @Transactional
    fun function2(id: Long, until: Instant?) {
        /* default implementation */
    }
}

@ApplicationScoped
class Service : IService {

    fun function3() {
        println("Hello, World!")
    }
}
```

application.properties
```properties
quarkus.package.jar.decompiler.enabled=true
```
Run gradle build
```bash
./gradlew clean build -x test --no-build-cache
```

Check class in `./build/decompiled/transformed-bytecode/com/kronst/IService$DefaultImpls.java`

### Output of `uname -a` or `ver`

Linux laptop 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.9" 2023-10-17 LTS

### Quarkus version or git rev

3.11.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

**Comment by geoand** [comment]
Can you please attach a sample application that behaves as you mention?

Thanks

**Comment by kronst** [comment]
> Can you please attach a sample application that behaves as you mention?
> 
> Thanks

Sure. Here is a sample project:
[quarkus-upgrade.zip](https://github.com/user-attachments/files/16781360/quarkus-upgrade.zip)

**Comment by geoand** [comment]
Thanks!

**Comment by geoand** [comment]
@mkouba @Ladicek this seems to be caused by [this](https://github.com/quarkusio/quarkus/blob/cc6b08d6818deb440189dc3ee8bfd3752386a71f/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/staticmethods/InterceptedStaticMethodsProcessor.java#L458-L460) code not properly copying over the annotations.

I have prepared a simpler [code-with-quarkus.zip](https://github.com/user-attachments/files/16782475/code-with-quarkus.zip) which you can use which contains only what is necessary to reproduce the problem (and no Kotlin :)).

You'll see that for something like:

```java
public class Example {

    @Dummy
    public static void doSomething(@NotNull String in1, @NotNull String in2) {

    }
}
```

The `InterceptedStaticMethodsProcessor` results in producing:

```java
public class Example {
   @Dummy
   public static void doSomething_orig(@NotNull String in1, @NotNull String in2) {
   }

   @Dummy
   @NotNull
   @NotNull
   @NotNull
   @NotNull
   public static void doSomething(String var0, String var1) {
      Example_InterceptorInitializer._8f4c528947d72f7f32e813c99a3a20797d8b132f(var0, var1);
   }
}
```

**Comment by mkouba** [comment]
> @mkouba @Ladicek this seems to be caused by [this](https://github.com/quarkusio/quarkus/blob/cc6b08d6818deb440189dc3ee8bfd3752386a71f/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/staticmethods/InterceptedStaticMethodsProcessor.java#L458-L460) code not properly copying over the annotations.

Yes, this is wrong. It blindly copies all annotations declared on the method and its parameters.
