### ISSUE TITLE
ContainerRequestFilter checking for annotation fails in native

### ISSUE THREAD

**Issue by krisgerhard** [quarkusio/quarkus#42919]
### Describe the bug

First off - it is very similar to https://github.com/quarkusio/quarkus/issues/42537
Error is the same, workaround is the same, unfortunately solution was not, so my issue still reproduces with 3.14.1.

`resourceInfo.resourceMethod.getAnnotation(...)` fails on native build.

Issue was introduced recently, last Quarkus version where issue **is not** present is `3.12.3` (easily verifyable using reproducer).

Workaround is to add `@RegisterForReflection` on `GreetingResource`

### Expected behavior

No error

### Actual behavior

```
Caused by: java.lang.NoSuchMethodException: org.acme.GreetingResource.hello()
        at java.base@21.0.4/java.lang.Class.checkMethod(DynamicHub.java:1078)
        at java.base@21.0.4/java.lang.Class.getMethod(DynamicHub.java:1063)
        at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getMethod(ResteasyReactiveResourceInfo.java:79)
```

### How to Reproduce?

1. Clone https://github.com/krisgerhard/quarkus_nosuchmethod_reproducer/
2. Run integration tests

**Comment by geoand** [comment]
Thanks, I'll have a look next week

**Comment by krisgerhard** [comment]
The speed of response and resolution is incredible. Thank you @geoand!

**Comment by geoand** [comment]
🙏🏽
