### ISSUE TITLE
Upgrading to 3.13.x+ causes parameterised tests using record argument to fail with LinkageError 'loader constraint violation'

### ISSUE THREAD

**Issue by diversit** [quarkusio/quarkus#42915]
### Describe the bug

JUnit5 parameterised tests having a Java record as argument type for the test method fail when upgrading to Quarkus 3.13.0 or higher.
The issue is caused by some class loading issue when the Java record has a property of a type not provided by Java like a Vavr `Option`. Just using String or Integer property type does not cause the test to fail.

I think this is somehow related to the change made for issue #15892 .

What is the point of cloning a Java record anyway? The object is already immutable.
Can the `NewSerializingDeepClone` introduced to fix #15892 (I think) just **not** clone Java records?

### Expected behavior

Test run run normally as with Quarkus versions <= 3.12.3.

### Actual behavior

The test fails with:
```
java.lang.IllegalStateException: Error calling onstructor on record class class my.package.NotificationQuery

	at org.jboss.marshalling.reflect.JDKSpecific.invokeRecordCanonicalConstructor(JDKSpecific.java:111)
	at org.jboss.marshalling.reflect.SerializableClass.invokeRecordCanonicalConstructor(SerializableClass.java:477)
	at org.jboss.marshalling.cloner.SerializingCloner.clone(SerializingCloner.java:293)
	at org.jboss.marshalling.cloner.SerializingCloner.clone(SerializingCloner.java:132)
	at io.quarkus.test.junit.internal.NewSerializingDeepClone.clone(NewSerializingDeepClone.java:128)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:963)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:903)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestTemplateMethod(QuarkusTestExtension.java:863)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:782)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:291)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:291)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:291)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.IllegalAccessException: no such constructor: my.package.NotificationQuery.<init>(Option,Boolean,Option,Option,Integer,Integer)void/newInvokeSpecial
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:906)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:989)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3762)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2822)
	at org.jboss.marshalling.reflect.JDKSpecific.invokeRecordCanonicalConstructor(JDKSpecific.java:107)
	... 52 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'void my.package.NotificationQuery.<init>(io.vavr.control.Option, java.lang.Boolean, io.vavr.control.Option, io.vavr.control.Option, java.lang.Integer, java.lang.Integer)' the class loader 'app' of the current class, org/jboss/marshalling/reflect/JDKSpecific, and the class loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @25216999 for the method's defining class, my/package/NotificationQuery, have different Class objects for the type io/vavr/control/Option used in the signature (org.jboss.marshalling.reflect.JDKSpecific is in unnamed module of loader 'app'; my.package.NotificationQuery is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @25216999, parent loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @61a1ea2c)
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:957)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:986)
	... 55 more
```

NotificationQuery.java
```java
public record NotificationQuery(
        Option<String> searchTerm,
        Boolean showUnread,
        Option<Notification.Level> level,
        Option<SortOrder> sortOrders,
        Integer limit,
        Integer offset) {}
```

Test
```java
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
@QuarkusTest
@TestTransaction
class NotificationRepositoryTest {
    private final NotificationRepository notificationRepository;

    NotificationRepositoryTest(NotificationRepository notificationRepository) {
        this.notificationRepository = notificationRepository;
    }

    /**
     * Provides arguments for testing the "findNotifications" method with various filter configurations.
     * The queryBuilder method takes three parameters:
     * <ul>
     *     <li>{@code searchTerm}: An optional search term used to filter notifications by id, message, or category.</li>
     *     <li>{@code showUnread}: A required boolean flag indicating whether unread notifications are included too.</li>
     *     <li>{@code level}: An optional filter based on the notification level (e.g., <em>Info, Warning, Error</em>).</li>
     * </ul>
     * Each argument contains a query builder configuration and an expected list of unique messages.
     * The assertion will rely on this list to determine whether the correct Notification has been returned from the repository.
     *
     * @return Stream of Arguments containing query builder configurations and expected notification messages
     */
    static Stream<Arguments> provideArgumentsForFindNotifications() {
        return Stream.of(
                // 1: Match all notifications based on no filters
                arguments(queryBuilder(none(), false, none()),
                        of("message1", "message2", "message3", "message4", "message5", "message6", "message7", "message8", "message9", "message10", "unique messageX")),
                // 2: Match notifications based on searchTerm (message)
                arguments(queryBuilder(some("message1"), false, none()),
                        of("message1", "message10")),
                // 3: Match notifications based on searchTerm (category)
                arguments(queryBuilder(some("ui"), false, none()),
                        of("message2")),
                // 4: Match notifications based on level = ERROR
                arguments(queryBuilder(none(), false, some(Notification.Level.ERROR)),
                        of("message3", "message6", "message9")),
                // 5: Match notifications based on level = WARNING (and above)
                arguments(queryBuilder(none(), false, some(Notification.Level.WARNING)),
                        of("message2", "message3", "message5", "message6", "message8", "message9")),
                // 6: Match notifications based on showUnread = true
                arguments(queryBuilder(none(), true, none()),
                        of("message1", "message3", "message5", "message7", "message9", "unique messageX")),
                // 7: Match notifications based on showUnread = false
                arguments(queryBuilder(none(), false, none()),
                        of("message1", "message2", "message3", "message4", "message5", "message6", "message7", "message8", "message9", "message10", "unique messageX")),
                // 8: Match no notifications due to invalid input
                arguments(queryBuilder(some("invalid"), true, none()),
                        empty()),
                // 9: Match specific notification based on all filter parameters
                arguments(queryBuilder(some("unique"), true, some(Notification.Level.INFO)),
                        of("unique messageX"))
        );
    }

    @ParameterizedTest
    @MethodSource("provideArgumentsForFindNotifications")
    void count_should_return_total_number_of_notifications_based_on_testcase(NotificationQuery query, List<String> messages) {
        insertNotificationsForFindNotifications();

        var foundNotifications = notificationRepository.count(query);

        assertThat(foundNotifications).isEqualTo(messages.size());
    }
}
```

### How to Reproduce?

This issue is reproducible when using a Record class containing a Vavr Option.
When just using a String or Integer as record property, the test does not fail.

```java
package io.dhlparcel.energy.cpo.db;

import io.vavr.control.Option;

import java.io.Serializable;

public record Value(Option<Integer> size) implements Serializable {
}
```

Test
```java
package io.dhlparcel.energy.cpo.db;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static io.vavr.control.Option.none;
import static io.vavr.control.Option.some;
import static org.junit.jupiter.api.Assertions.assertEquals;

@QuarkusTest
public class ReproduceTest {

    private static Stream<Arguments> testCases() {
        return Stream.of(
                Arguments.of(new Value(some(5)), 5),
                Arguments.of(new Value(none()), 0)
        );
    }

    @ParameterizedTest
    @MethodSource("testCases")
    void testThis(Value value, Integer expected) {
        assertEquals(expected, value.size().getOrElse(0));
    }
}
```

Fails with
```

WARNING: A Java agent has been loaded dynamically (/Users/myuser/.m2/repository/net/bytebuddy/byte-buddy-agent/1.14.15/byte-buddy-agent-1.14.15.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release

java.lang.IllegalStateException: Error calling onstructor on record class class my.package.Value

	at org.jboss.marshalling.reflect.JDKSpecific.invokeRecordCanonicalConstructor(JDKSpecific.java:111)
	at org.jboss.marshalling.reflect.SerializableClass.invokeRecordCanonicalConstructor(SerializableClass.java:477)
	at org.jboss.marshalling.cloner.SerializingCloner.clone(SerializingCloner.java:293)
	at org.jboss.marshalling.cloner.SerializingCloner.clone(SerializingCloner.java:132)
	at io.quarkus.test.junit.internal.NewSerializingDeepClone.clone(NewSerializingDeepClone.java:128)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:963)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:903)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestTemplateMethod(QuarkusTestExtension.java:863)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:782)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:291)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:291)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:291)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.IllegalAccessException: no such constructor: my.package.Value.<init>(Option)void/newInvokeSpecial
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:906)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:989)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3762)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2822)
	at org.jboss.marshalling.reflect.JDKSpecific.invokeRecordCanonicalConstructor(JDKSpecific.java:107)
	... 51 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'void my.package.Value.<init>(io.vavr.control.Option)' the class loader 'app' of the current class, org/jboss/marshalling/reflect/JDKSpecific, and the class loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6480a063 for the method's defining class, my/package/Value, have different Class objects for the type io/vavr/control/Option used in the signature (org.jboss.marshalling.reflect.JDKSpecific is in unnamed module of loader 'app'; my.package.Value is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6480a063, parent loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @33d53216)
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:957)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:986)
	... 54 more
```

### Output of `uname -a` or `ver`

Darwin MacBook-Pro-8.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "22" 2024-03-19 OpenJDK Runtime Environment Temurin-22+36 (build 22+36) OpenJDK 64-Bit Server VM Temurin-22+36 (build 22+36, mixed mode)

### Quarkus version or git rev

3.13.0+

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f) Maven home: /Users/myuser/.m2/wrapper/dists/apache-maven-3.9.3-bin/326f10f4/apache-maven-3.9.3 Java version: 22, vendor: Eclipse Adoptium, runtime: /Users/myuser/.sdkman/candidates/java/22-tem Default locale: en_GB, platform encoding: UTF-8 OS name: "mac os x", version: "13.4", arch: "aarch64", family: "mac"

**Comment by gsmet** [comment]
Could you test by overriding the version of JBoss Marshalling to 2.2.0.Final?

```xml
<dependency>
    <groupId>org.jboss.marshalling</groupId>
    <artifactId>jboss-marshalling</artifactId>
    <version>2.2.0.Final</version>
</dependency>
```

Ideally when you give us a reproducer, better attach an archive or link to a GitHub repo of a small Maven project.

**Comment by geoand** [comment]
cc @dmlloyd

**Comment by diversit** [comment]
Tested it with Jboss marshalling 2.2.0.FINAL and that seems to work.
Went back and forth a couple of times with the JBoss marshalling version.
With 2.2.0.FINAL the test was consistently successful.
With 2.1.4.SP1 the test consistently fails.

**Comment by gsmet** [comment]
Thanks for testing, this will be part of 3.14.2!
