### ISSUE TITLE
@Inject Mutiny.Session caused UnsatisfiedResolutionException

### ISSUE THREAD

**Issue by maxlam79** [quarkusio/quarkus#42929]
### Describe the bug

I realised a very weird behaviour on Quarkus 3.14.1. I usually uses hibernate reactive panache. In my previous projects, I have no issues with have Mutiny.Session injected in some of the classes extending PanacheRepositoryBase or other classes. Example:

```
@ApplicationScoped
public class SomeProcess {

    @Inject
    Mutiny.Session em;

    // ...
}
```

I have started a new project recently and found that it threw UnsatisfiedResolutionException when Mutiny.Session was injected:
```
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.hibernate.reactive.mutiny.Mutiny$Session and qualifiers [@Default]
```

I have created a small app to reproduce this issue: [https://github.com/maxlam79/quarkus_UnsatisfiedResolutionException_20240831](https://github.com/maxlam79/quarkus_UnsatisfiedResolutionException_20240831)

Working through PanacheEntity.persist and so on is fine though. Should I be using Mutiny.Session in future?

### Expected behavior

Should have no issues in injecting Mutiny.Session.

### Actual behavior

Here's the error log:
```
2024-08-31 16:49:46,566 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.hibernate.reactive.mutiny.Mutiny$Session and qualifiers [@Default]
        - injection target: my.cloudlegato.InvestigateProcess#em
        - declared on CLASS bean [types=[my.cloudlegato.InvestigateProcess, java.lang.Object], qualifiers=[@Default, @Any], target=my.cloudlegato.InvestigateProcess]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1551)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:338)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:167)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:490)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:854)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.hibernate.reactive.mutiny.Mutiny$Session and qualifiers [@Default]
        - injection target: my.cloudlegato.InvestigateProcess#em
        - declared on CLASS bean [types=[my.cloudlegato.InvestigateProcess, java.lang.Object], qualifiers=[@Default, @Any], target=my.cloudlegato.InvestigateProcess]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:545)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:667)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:323)
        ... 11 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:254)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:58)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:91)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:430)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:57)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.hibernate.reactive.mutiny.Mutiny$Session and qualifiers [@Default]
        - injection target: my.cloudlegato.InvestigateProcess#em
        - declared on CLASS bean [types=[my.cloudlegato.InvestigateProcess, java.lang.Object], qualifiers=[@Default, @Any], target=my.cloudlegato.InvestigateProcess]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1551)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:338)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:167)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:490)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:854)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.hibernate.reactive.mutiny.Mutiny$Session and qualifiers [@Default]
        - injection target: my.cloudlegato.InvestigateProcess#em
        - declared on CLASS bean [types=[my.cloudlegato.InvestigateProcess, java.lang.Object], qualifiers=[@Default, @Any], target=my.cloudlegato.InvestigateProcess]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:545)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:667)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:323)
        ... 11 more

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:159)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        ... 9 more
Caused by: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.hibernate.reactive.mutiny.Mutiny$Session and qualifiers [@Default]
        - injection target: my.cloudlegato.InvestigateProcess#em
        - declared on CLASS bean [types=[my.cloudlegato.InvestigateProcess, java.lang.Object], qualifiers=[@Default, @Any], target=my.cloudlegato.InvestigateProcess]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1551)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:338)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:167)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:490)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:854)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.hibernate.reactive.mutiny.Mutiny$Session and qualifiers [@Default]
        - injection target: my.cloudlegato.InvestigateProcess#em
        - declared on CLASS bean [types=[my.cloudlegato.InvestigateProcess, java.lang.Object], qualifiers=[@Default, @Any], target=my.cloudlegato.InvestigateProcess]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:545)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:667)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:323)
        ... 11 more
```

### How to Reproduce?

A small app is here to reproduce this issue: [https://github.com/maxlam79/quarkus_UnsatisfiedResolutionException_20240831](https://github.com/maxlam79/quarkus_UnsatisfiedResolutionException_20240831)

### Output of `uname -a` or `ver`

Darwin Maxs-MBP-2 21.6.0 Darwin Kernel Version 21.6.0: Mon Jun 24 00:56:10 PDT 2024; root:xnu-8020.240.18.709.2~1/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM Zulu21.28+85-CA

### Quarkus version or git rev

3.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4

**Comment by maxlam79** [comment]
I have found a way to obtain the session via 
```
Panache.getSession()
```

Seems to me that Mutiny.Session can't be injected any more.

Just close this if it is not a bug from version 3 onwards...

**Comment by maxlam79** [comment]
Ok, I think I finally understood what is happening. Seems that much have changed from my last use of Quarkus.

I'd realized that even all external libraries where classes of mine which were annotated with @ApplicationScope if injected will throw the same Exception.

Have to resort to this in the application.properties:
```
quarkus.index-dependency.blah.group-id=com.blah
quarkus.index-dependency.blah.artifact-id=blah-library
```

For this matter, I'll just switch to using Panache.getSession() to move on.
