### ISSUE TITLE
Managed Vertx instance should be closed after all Kafka resources have been closed

### ISSUE THREAD

**Issue by mswiderski** [quarkusio/quarkus#4293]
**Describe the bug**
Applications that uses quarkus-smallrye-reactive-messaging-kafka experiences following stacktrace on shutdown

````
2019-10-01 12:03:18,276 ERROR [org.apa.kaf.cli.pro.KafkaProducer] (vert.x-worker-thread-11) [Producer clientId=producer-2] Interrupted while joining ioThread: java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Thread.join(Thread.java:1313)
	at org.apache.kafka.clients.producer.KafkaProducer.close(KafkaProducer.java:1161)
	at org.apache.kafka.clients.producer.KafkaProducer.close(KafkaProducer.java:1138)
	at org.apache.kafka.clients.producer.KafkaProducer.close(KafkaProducer.java:1117)
	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.lambda$close$12(KafkaWriteStreamImpl.java:238)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
````

**Expected behavior**
graceful shutdown

**Actual behavior**
each outgoing channel configured in the application will cause the above stacktrace to be logged

**To Reproduce**
Use quarkus with reactive messaging Kafka with outgoing channel configured

**Additional context**
root cause to be fixed in VertX-kafka-client - https://github.com/vert-x3/vertx-kafka-client/issues/149

**Comment by vietj** [comment]
The issue should actually be fixed in this project as hinted in https://github.com/vert-x3/vertx-kafka-client/issues/149#issuecomment-537091535

**Comment by vietj** [comment]
Actually this issue should be opened in Smallrye Reactive Messaging. I thought this repo was actually Smallrye's one and not Quarkus, sorry for the noise.

**Comment by mswiderski** [comment]
@vietj thanks a lot for all the details, I renamed it here and will create a new issue is smallrye reactive messaging.

**Comment by vietj** [comment]
@mswiderski sure, it if that's needed assign me the issue

**Comment by mswiderski** [comment]
@vietj since I can't assign issues just linking it here https://github.com/smallrye/smallrye-reactive-messaging/issues/233

**Comment by cescoffier** [comment]
Issue fixed in SmallRye Reactive Messaging. Release in progress.

**Comment by cescoffier** [comment]
It was fixed.
