### ISSUE TITLE
Fatal Error: java.lang.Object.wait0(long) Unsupported in Native Build with aws servicediscovery Dependency

### ISSUE THREAD

**Issue by sarathpetec** [quarkusio/quarkus#43008]
### Describe the bug

I'm encountering a fatal error while attempting to build a Quarkus application natively with **mvn clean package -Pnative**. The build fails when using the **servicediscovery** dependency from the AWS SDK. The error indicates that the method **java.lang.Object.wait0(long)** is unsupported during the native image build process.

https://github.com/sarathpetec/quarkus-with-aws.git

### Expected behavior

The application should successfully build into a native executable without errors.

### Actual behavior

The native build fails with the following error:

```
com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Object.wait0(long) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
```

### How to Reproduce?

**Steps to Reproduce**:
1. Create a Quarkus project with the following dependencies:
   - `quarkus-hibernate-reactive-panache`
   - `quarkus-reactive-pg-client`
   - `software.amazon.awssdk:servicediscovery`
2. Ensure GraalVM is set up and in use (details below).
3. Run the following command to build natively:
   ```bash
   mvn clean package -Pnative
   ```

### Output of `uname -a` or `ver`

java 21.0.3 2024-04-16 LTS ( Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37))

### Output of `java -version`

Java version: 21.0.3 (Oracle GraalVM 21.0.3+7.1)

### Mandrel or GraalVM version (if different from Java)

GraalVM: Oracle GraalVM 21.0.3+7-LTS-jvmci-23.1-b37

### Quarkus version or git rev

Quarkus version: 3.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8 

### Additional information

```
[1/8] Initializing...                                                                                   (10.1s @ 0.30GB)
 Java version: 21.0.3+7-LTS, vendor version: Oracle GraalVM 21.0.3+7.1
 Graal compiler: optimization level: 2, target machine: x86-64-v3, PGO: ML-inferred
 C compiler: cl.exe (microsoft, x64, 19.39.33523)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 7 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.quarkus.caffeine.runtime.graal.CacheConstructorsFeature
 - io.quarkus.hibernate.orm.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
 - org.eclipse.angus.activation.nativeimage.AngusActivationFeature
 - org.hibernate.graalvm.internal.GraalVMStaticFeature: Hibernate ORM's static reflection registrations for GraalVM
------------------------------------------------------------------------------------------------------------------------
 4 experimental option(s) unlocked:
 - '-H:+AllowFoldMethods' (origin(s): command line)
 - '-H:BuildOutputJSONFile' (origin(s): command line)
 - '-H:-UseServiceLoaderFeature' (origin(s): command line)
 - '-H:+GenerateBuildArtifactsFile' (origin(s): command line)
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 23.91GB of memory (75.6% of 31.64GB system memory, determined at start)
 - 20 thread(s) (100.0% of 20 available processor(s), determined at start)
WARNING: A Java agent has been loaded dynamically (D:\personal\workspace\temp\quarkus-with-aws\target\quarkus-with-aws-1.0.0-SNAPSHOT-native-image-source-jar\lib\net.bytebuddy.byte-buddy-agent-1.14.15.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
[2/8] Performing analysis...  []                                                                        (11.2s @ 1.90GB)
   12,600 reachable types   (79.5% of   15,856 total)
   14,654 reachable fields  (48.9% of   29,944 total)
   55,760 reachable methods (51.1% of  109,030 total)
    4,175 types,   133 fields, and 2,918 methods registered for reflection
        4 native libraries: crypt32, ncrypt, psapi, winhttp

Fatal error: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.debug.GraalError: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Object.wait0(long) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:322)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapObjectArray.readElementValue(ImageHeapObjectArray.java:84)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.onObjectReachable(ImageHeapScanner.java:464)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.onObjectReachable(SVMImageHeapScanner.java:156)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$markReachable$5(ImageHeapScanner.java:452)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$14(ImageHeapScanner.java:695)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: org.graalvm.compiler.debug.GraalError: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Object.wait0(long) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:322)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.getOrCreateImageHeapConstant(ImageHeapScanner.java:212)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.getOrCreateImageHeapConstant(SVMImageHeapScanner.java:109)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapConstant(ImageHeapScanner.java:186)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$createImageHeapObjectArray$3(ImageHeapScanner.java:270)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        ... 14 more
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Object.wait0(long) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:268)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:140)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:438)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:417)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:78)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaMethod(UniverseMetaAccess.java:112)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:83)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionFeature.createAccessor(ReflectionFeature.java:187)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionFeature.getOrCreateAccessor(ReflectionFeature.java:141)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.target.ExecutableAccessorComputer.transform(ExecutableAccessorComputer.java:43)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.ComputedValueField.computeValue(ComputedValueField.java:366)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:336)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readHostedFieldValue(AnalysisConstantReflectionProvider.java:235)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.readHostedFieldValue(SVMImageHeapScanner.java:124)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapInstance(ImageHeapScanner.java:287)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapObject(ImageHeapScanner.java:254)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$getOrCreateImageHeapConstant$2(ImageHeapScanner.java:205)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
```

**Comment by sarathpetec** [comment]
I would like to add some more details about the project. This project is fully reactive, using **PostgreSQL** as the database and **gRPC** for APIs. Despite using minimal dependencies, I consistently encounter the following error during native image builds:

```
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Object.wait0(long) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
```

I have attempted various configurations and files in the `native-image` folder to resolve this issue, but none have been successful. Below is the native-image configuration we have tried, placed in the `src/main/resources/META-INF/native-image` folder:

### Reflection Configuration (`reflect-config.json`):
```json
[
 {
    "name": "software.amazon.awssdk.services.servicediscovery.ServiceDiscoveryClient",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true
  }
]
```

### Resource Configuration (`resource-config.json`):
```json
{
  "resources": {
    "includes": [
      { "pattern": ".*\\.properties" },
      { "pattern": ".*\\.xml" },
      { "pattern": ".*\\.json" }
    ]
  }
}
```

Even with these configurations, the error persists. The project runs perfectly in JVM mode using `mvn quarkus:dev -Plocal` but fails during native compilation. You can find the full code for the project in my GitHub repository: [quarkus-with-aws](https://github.com/sarathpetec/quarkus-with-aws.git)

Any guidance or suggestions on resolving this issue would be greatly appreciated.

**Comment by zakkak** [comment]
The issue seems to be triggered by the use of `quarkus-junit5-mockito` which brings in bytebuddy which keeps a list of `Object`'s methods in https://github.com/raphw/byte-buddy/blob/b05c7816334a0db5f499371a79437a369adb2d0a/byte-buddy-dep/src/main/java/net/bytebuddy/description/method/MethodList.java#L138 in this case resulting in GraalVM trying to resolve `wait0` and seeing that it's deleted.

**Comment by gsmet** [comment]
This artifact:
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5-mockito</artifactId>
        </dependency>
```
should be scoped `test`.

**Comment by gsmet** [comment]
Also there is a growing list of AWS services that have extensions there: https://github.com/quarkiverse/quarkus-amazon-services/ .

Probably a good idea to discuss things there if you need support for some others, @scrocquesel is very helpful.

**Comment by sarathpetec** [comment]
```markdown
Thank you for looking into this issue. I've tried several modifications to resolve the problem including completely exclude the Junit and mockito, but I'm still encountering the same error. Here's a summary of the changes I've made:

1. Updated `application.properties`:
```properties
quarkus.native.container-build=true
quarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:22.3-java17
quarkus.native.additional-build-args=\
    --initialize-at-run-time=org.apache.http.conn.ssl.SSLConnectionSocketFactory,org.apache.http.conn.ssl.AllowAllHostnameVerifier \
    --report-unsupported-elements-at-runtime \
    -H:+PrintClassInitialization \
    -H:+ReportExceptionStackTraces \
    -H:+AddAllCharsets \
    -H:Name=quarkus-with-aws-1.0.0-SNAPSHOT-runner
quarkus.package.type=native
quarkus.native.native-image-xmx=4g
```

2. Updated `pom.xml` to include native image plugin configuration and set Java version to 17(even though the application is in Java 21):
```xml
<properties>
    <maven.compiler.release>17</maven.compiler.release>
    <java.version>17</java.version>
</properties>
<build>
    <plugins>
        <plugin>
            <groupId>${quarkus.platform.group-id}</groupId>
            <artifactId>quarkus-maven-plugin</artifactId>
            <version>${quarkus.platform.version}</version>
            <extensions>true</extensions>
            <executions>
                <execution>
                    <goals>
                        <goal>build</goal>
                        <goal>generate-code</goal>
                        <goal>generate-code-tests</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        <!-- Other plugins... -->
    </plugins>
</build>
<profiles>
    <profile>
        <id>native</id>
        <activation>
            <property>
                <name>native</name>
            </property>
        </activation>
        <properties>
            <skipITs>false</skipITs>
            <quarkus.package.type>native</quarkus.package.type>
        </properties>
    </profile>
</profiles>
```

3. Updated `native-image.properties` in `src/main/resources/META-INF/native-image/`:
```properties
Args = --initialize-at-build-time=io.netty \
       --initialize-at-run-time=com.amazonaws \
       --enable-url-protocols=http,https \
       --report-unsupported-elements-at-runtime \
       --no-fallback
```

4. Ensured `reflection-config.json` in `src/main/resources/META-INF/native-image/` is correct:
```json
[
  {
    "name": "org.apache.http.conn.ssl.SSLConnectionSocketFactory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "org.apache.http.conn.ssl.AllowAllHostnameVerifier",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  }
]
```

After making these changes, I've tried the following steps:

1. Cleaned the project: `mvn clean`
2. Updated dependencies: 
   ```
   mvn dependency:purge-local-repository
   mvn dependency:resolve
   ```
3. Built the native image: `mvn package -Pnative -Dquarkus.native.container-build=true` or `mvn clean package -Pnative`

However, I'm still encountering the same error:

```
Error: Unknown argument: quarkus-with-aws-1.0.0-SNAPSHOT-runner
The error message keep on change based on the changes.
```

I've also tried running the build with debug output (`-X` flag), but the error persists. 

Any further guidance or suggestions would be greatly appreciated. Thank you for your time and assistance.
```

**Comment by zakkak** [comment]
> However, I'm still encountering the same error:
>
> ```
> Error: Unknown argument: quarkus-with-aws-1.0.0-SNAPSHOT-runner
> The error message keep on change based on the changes.
> ```

@sarathpetec this is not the same error with the one described in the issue description which implies that the changes you applied resolved the initial issue.

The reason you are getting this error is because of the `quarkus.native.additional-build-args` value. The flags in this property should be comma separated:

> `quarkus.native.additional-build-args`
>
> Comma-separated, additional arguments to pass to the build process. If an argument includes the , symbol, it needs to be escaped, e.g. \\,

see https://quarkus.io/guides/building-native-image#configuration-reference

**Comment by sarathpetec** [comment]
The issue appears to be rooted in the following dependency and based on the resolution provided in [issue #6327](https://github.com/quarkusio/quarkus/issues/6327), I was able to resolve my problem:

```xml
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jdbc-postgresql</artifactId>
</dependency>
```

To resolve the problem, I added the following dependencies:

```xml
<dependency>
    <groupId>jakarta.security.jacc</groupId>
    <artifactId>jakarta.security.jacc-api</artifactId>
</dependency>
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
</dependency>
```

After introducing these dependencies, the issue was resolved, and I was able to proceed. However, I encountered this problem specifically when I introduced the `aws servicediscovery` dependency, which caused the native build to fail after initially working.

Is this approach the correct way to resolve the issue, or is there a more optimal solution that aligns with best practices for Quarkus and native builds?

I would appreciate any feedback on whether adding these dependencies is an appropriate fix or if there's an underlying issue that needs to be addressed differently.

**Comment by zakkak** [comment]
> The issue appears to be rooted in the following dependency 

Which issue are you referring to? It looks like you are referring to a new issue that we have no info about.

Assuming (by the https://github.com/quarkusio/quarkus/issues/6327 reference) that you are referring to a `NoClassDefFoundException`, your approach seems reasonable. We can't really tell if it's optimal without more details. In general the documentation in https://quarkus.io/guides/native-reference#i-get-a-analysiserrorparsingerror-when-building-a-native-executable-due-to-an-unresolvedelementexception-what-can-i-do should cover your case.

I am closing this as the originally reported issue has been addressed.
