### ISSUE TITLE
Problems with SecunetEdDSASecurityProvider in native images 

### ISSUE THREAD

**Issue by mithunmaddur** [quarkusio/quarkus#43012]
### Describe the bug

Getting below while running exe generated .
we are using java 17 and quarkus 3.13.2
```
2024-09-02 14:09:43,608 ERROR [] (main) class configured for Signature (provider: SNED25519) cannot be found.: java.security.NoSuchAlgorithmException: class configured for Signature (provider: SNED25519) cannot be found.
        at java.base@17.0.12/java.security.Provider$Service.getImplClass(Provider.java:1959)
        at java.base@17.0.12/java.security.Provider$Service.getDefaultConstructor(Provider.java:1975)
        at java.base@17.0.12/java.security.Provider$Service.newInstanceOf(Provider.java:1889)
        at java.base@17.0.12/java.security.Provider$Service.newInstanceUtil(Provider.java:1897)
        at java.base@17.0.12/java.security.Provider$Service.newInstance(Provider.java:1872)
        at java.base@17.0.12/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at java.base@17.0.12/sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
        at java.base@17.0.12/java.security.Signature.getInstance(Signature.java:404)
        at java.base@17.0.12/sun.security.x509.X509CertImpl.verify(X509CertImpl.java:437)
        at RootChainOfTrust.(RootChainOfTrust.java:47)
```

Will did RegisterForReflection like below 
```java
RegisterForReflection(ignoreNested = false, targets = {
        ,
       
    * .Ed25519PHEngine.class,
        *.SecunetEdDSASecurityProvider.class,
        java.security.cert.X509Certificate.class
})
public class Reflection {
}
```

### Expected behavior

Generating EXE should work.
but from jar is working fine

**Comment by Karm** [comment]
@mithunmaddur Hello, I'd gladly help you with Windows native build, but you have to provide some small reproducer I can build and take a look at...

**Comment by mithunmaddur** [comment]
@Karm 
InputStream stream = new ByteArrayInputStream(certificateBytes)) 
                    CertificateFactory cf = CertificateFactory.getInstance(X_509);
                X509Certificate    certificate = (X509Certificate) cf.generateCertificate(stream);

**Comment by geoand** [comment]
@mithunmaddur can you please attach a sample application that exhibits the problem as @Karm asked?

Thanks
