### ISSUE TITLE
Compilation error on using Generics for Rest Client: java.lang.RuntimeException: Invalid type for descriptor T 

### ISSUE THREAD

**Issue by ricardoalonso** [quarkusio/quarkus#43011]
### Describe the bug

When creating clients for Rest Service, I was trying to create a generic interface to map the methods from `PanacheEntityResource` class that's used to create services for entities:

```java
@Produces(MediaType.APPLICATION_JSON)
public interface BasicClient<T extends BasicType> {    
    @GET    
    T get();
}
```

```java
@Path("/typea")
@RegisterRestClient(configKey = "typeab-service")
public interface TypeAClient extends BasicClient<TypeA> {
}
```

```java
@Path("/typeb")
@RegisterRestClient(configKey = "typeab-service")
public interface TypeBClient extends BasicClient<TypeB> {
}
```

I have created a simple project ( [code-with-quarkus.zip](https://github.com/user-attachments/files/16869014/code-with-quarkus.zip) ) to show the problem. The regular Java compilation (without tests) runs fine, but when the client is used, the problem appears:

```posh
[ERROR] Errors:
[ERROR]   ServiceTest.testTypeAClient » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors        
[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.reflect.UndeclaredThrowableException        
at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:860)        
at io.quarkus.builder.BuildContext.run(BuildContext.java:256)        
at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)        
at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)        
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)        
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)        
at java.base/java.lang.Thread.run(Thread.java:1583)        
at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Invalid type for descriptor T        
at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)        
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)        
at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:432)        
at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:537)        
at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)        
at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:854)        
... 7 more
Caused by: java.lang.RuntimeException: Invalid type for descriptor T        
at io.quarkus.gizmo.DescriptorUtils.typeToString(DescriptorUtils.java:222)        
at io.quarkus.gizmo.MethodDescriptor.<init>(MethodDescriptor.java:66)        
at io.quarkus.gizmo.MethodDescriptor.of(MethodDescriptor.java:109)        
at io.quarkus.arc.processor.ClientProxyGenerator.generate(ClientProxyGenerator.java:161)        
at io.quarkus.arc.processor.BeanProcessor$4$1.call(BeanProcessor.java:326)        
at io.quarkus.arc.processor.BeanProcessor$4$1.call(BeanProcessor.java:323)        
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)        
... 6 more
```

If I implement without the interface, it works fine.

### Expected behavior

Use a generic super interface to map common methods.

### Actual behavior

See the above stack trace.

### How to Reproduce?

See the attached sample project.

### Output of `uname -a` or `ver`

```
Linux localhost.localdomain 6.9.12-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jul 27 15:56:15 UTC 2024 x86_64 GNU/Linux
```

### Output of `java -version`

```
openjdk version "21.0.4" 2024-07-16 OpenJDK Runtime Environment (Red_Hat-21.0.4.0.7-2) (build 21.0.4+7) OpenJDK 64-Bit Server VM (Red_Hat-21.0.4.0.7-2) (build 21.0.4+7, mixed mode, sharing)
```

### Quarkus version or git rev

3.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: /home/ricardo.alonso/.m2/wrapper/dists/apache-maven-3.9.8-bin/337e6d14/apache-maven-3.9.8
Java version: 21.0.4, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-21-openjdk-21.0.4.0.7-2.fc40.x86_64
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "6.9.12-200.fc40.x86_64", arch: "amd64", family: "unix"
```

**Comment by ricardoalonso** [comment]
Let me understand. Quarkus try to create the Rest Client interface from the child that's annotated and from the father class, which is not annotated?

**Comment by geoand** [comment]
It tries to create them for all the interfaces

**Comment by ricardoalonso** [comment]
The `@IgnoreForRestClient` could be a solution, but could be simpler to just not follow the hierarchy tree? Only generate the client proxy for the explicit annotated class and not for the relatives?

**Comment by geoand** [comment]
Unfortunately that would not work because it's perfectly valid to have non annotated interfaces for the rest client

**Comment by gsmet** [comment]
Is it mandated? Because I can see how it could be impractical in the end. 

Being explicit about when you want a client doesn’t seem too far fetched?

Also in this very case, maybe we should just skip it? It’s not annotated and it’s invalid, looks like something we could skip?

**Comment by geoand** [comment]
> Is it mandated?

Yes, otherwise the programmatic usage won't work

**Comment by gsmet** [comment]
Yeah, I mean if we know we cannot instantiate it, we might as well skip it.

**Comment by geoand** [comment]
Potentially, but there could be corner case

**Comment by rekt-hard** [comment]
We also just stumbled upon this issue. This was working before we updated our dependencies from `quarkus-resteasy*` to `quarkus-rest*`.
