### ISSUE TITLE
In quarkus 3.14.x derbydb is not working anymore

### ISSUE THREAD

**Issue by ThomasStuetz** [quarkusio/quarkus#43103]
### Describe the bug

When creating a simple quarkus app in version 3.14.2 with panache, derbydb and one entity now an error message occurs. The class ProductVersionHolder of derby-drivers is not found.

java.lang.NoClassDefFoundError: org/apache/derby/shared/common/info/ProductVersionHolder

This happens when using an local db-instance and also when using the dev-service for derby.

When using Quarkus 3.8.6 all works fine.

### Expected behavior

The application should start.

❯ quarkus dev --clean
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< at.htl:surfboard-repository >---------------------
[INFO] Building surfboard-repository 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ surfboard-repository ---
[INFO] Deleting /Users/stuetz/work/quarkus-foerdern/surfboard-repository/target
[INFO] 
[INFO] --- quarkus:3.8.6:dev (default-cli) @ surfboard-repository ---
[INFO] Invoking resources:3.3.1:resources (default-resources) @ surfboard-repository
[INFO] Copying 2 resources from src/main/resources to target/classes
[INFO] Invoking quarkus:3.8.6:generate-code (default) @ surfboard-repository
[INFO] Invoking compiler:3.12.1:compile (default-compile) @ surfboard-repository
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 7 source files with javac [debug parameters release 17] to target/classes
[INFO] Annotation processing is enabled because one or more processors were found
  on the class path. A future release of javac may disable annotation processing
  unless at least one processor is specified by name (-processor), or a search
  path is specified (--processor-path, --processor-module-path), or annotation
  processing is enabled explicitly (-proc:only, -proc:full).
  Use -Xlint:-options to suppress this message.
  Use -proc:none to disable annotation processing.
[INFO] Invoking resources:3.3.1:testResources (default-testResources) @ surfboard-repository
[INFO] skip non existing resourceDirectory /Users/stuetz/work/quarkus-foerdern/surfboard-repository/src/test/resources
[INFO] Invoking quarkus:3.8.6:generate-code-tests (default) @ surfboard-repository
[INFO] Invoking compiler:3.12.1:testCompile (default-testCompile) @ surfboard-repository
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 1 source file with javac [debug parameters release 17] to target/test-classes
[INFO] Annotation processing is enabled because one or more processors were found
  on the class path. A future release of javac may disable annotation processing
  unless at least one processor is specified by name (-processor), or a search
  path is specified (--processor-path, --processor-module-path), or annotation
  processing is enabled explicitly (-proc:only, -proc:full).
  Use -Xlint:-options to suppress this message.
  Use -proc:none to disable annotation processing.
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-09-07 07:53:25,182 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.package.jar.type" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

2024-09-07 07:53:25,857 INFO  [io.quarkus] (Quarkus Main Thread) surfboard-repository 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.8.6) started in 1.617s. Listening on: http://localhost:8090
2024-09-07 07:53:25,860 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-09-07 07:53:25,861 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-derby, narayana-jta, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]

--
Tests paused

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.492 s
[INFO] Finished at: 2024-09-07T07:53:30+02:00
[INFO] ------------------------------------------------------------------------

### Actual behavior

❯ quarkus dev --clean
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< at.htl:surfboard-repository >---------------------
[INFO] Building surfboard-repository 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ surfboard-repository ---
[INFO] Deleting /Users/stuetz/work/quarkus-foerdern/surfboard-repository/target
[INFO] 
[INFO] --- quarkus:3.14.2:dev (default-cli) @ surfboard-repository ---
[INFO] Invoking resources:3.3.1:resources (default-resources) @ surfboard-repository
[INFO] Copying 2 resources from src/main/resources to target/classes
[INFO] Invoking quarkus:3.14.2:generate-code (default) @ surfboard-repository
[INFO] Invoking compiler:3.13.0:compile (default-compile) @ surfboard-repository
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 7 source files with javac [debug parameters release 17] to target/classes
[INFO] Invoking resources:3.3.1:testResources (default-testResources) @ surfboard-repository
[INFO] skip non existing resourceDirectory /Users/stuetz/work/quarkus-foerdern/surfboard-repository/src/test/resources
[INFO] Invoking quarkus:3.14.2:generate-code-tests (default) @ surfboard-repository
[INFO] Invoking compiler:3.13.0:testCompile (default-testCompile) @ surfboard-repository
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 1 source file with javac [debug parameters release 17] to target/test-classes
Listening for transport dt_socket at address: 5005
2024-09-07 07:58:22,391 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2024-09-07 07:58:22,549 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Press [e[error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: java.lang.NoClassDefFoundError: org/apache/derby/shared/common/info/ProductVersionHolder
        at org.apache.derby.client.am.Configuration.buildProductVersionHolder(Configuration.java:141)
        at org.apache.derby.client.am.Configuration.loadProductVersionHolder(Configuration.java:130)
        at org.apache.derby.client.am.Configuration.<clinit>(Configuration.java:115)
        at org.apache.derby.client.ClientAutoloadedDriver.registerMe(ClientAutoloadedDriver.java:71)
        at org.apache.derby.client.ClientAutoloadedDriver.<clinit>(ClientAutoloadedDriver.java:65)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:529)
        at java.base/java.lang.Class.forName(Class.java:508)
        at io.quarkus.agroal.deployment.AgroalProcessor.validateBuildTimeConfig(AgroalProcessor.java:177)
        at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:114)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:854)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.lang.ClassNotFoundException: org.apache.derby.shared.common.info.ProductVersionHolder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 19 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:254)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:58)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:91)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:430)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:57)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: java.lang.NoClassDefFoundError: org/apache/derby/shared/common/info/ProductVersionHolder
        at org.apache.derby.client.am.Configuration.buildProductVersionHolder(Configuration.java:141)
        at org.apache.derby.client.am.Configuration.loadProductVersionHolder(Configuration.java:130)
        at org.apache.derby.client.am.Configuration.<clinit>(Configuration.java:115)
        at org.apache.derby.client.ClientAutoloadedDriver.registerMe(ClientAutoloadedDriver.java:71)
        at org.apache.derby.client.ClientAutoloadedDriver.<clinit>(ClientAutoloadedDriver.java:65)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:529)
        at java.base/java.lang.Class.forName(Class.java:508)
        at io.quarkus.agroal.deployment.AgroalProcessor.validateBuildTimeConfig(AgroalProcessor.java:177)
        at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:114)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:854)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.lang.ClassNotFoundException: org.apache.derby.shared.common.info.ProductVersionHolder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 19 more

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:159)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: org/apache/derby/shared/common/info/ProductVersionHolder
        at org.apache.derby.client.am.Configuration.buildProductVersionHolder(Configuration.java:141)
        at org.apache.derby.client.am.Configuration.loadProductVersionHolder(Configuration.java:130)
        at org.apache.derby.client.am.Configuration.<clinit>(Configuration.java:115)
        at org.apache.derby.client.ClientAutoloadedDriver.registerMe(ClientAutoloadedDriver.java:71)
        at org.apache.derby.client.ClientAutoloadedDriver.<clinit>(ClientAutoloadedDriver.java:65)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:529)
        at java.base/java.lang.Class.forName(Class.java:508)
        at io.quarkus.agroal.deployment.AgroalProcessor.validateBuildTimeConfig(AgroalProcessor.java:177)
        at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:114)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:854)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.lang.ClassNotFoundException: org.apache.derby.shared.common.info.ProductVersionHolder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 19 more

--
Press [e] to edit command line args (currently ''), [:] for the terminal, [h] for more options>

### How to Reproduce?

1. Create quarkus project with dependencies: quarkus-jdbc-derby, quarkus-hibernate-orm-panache
3. quarkus dev --clean

### Output of `uname -a` or `ver`

Darwin Toms-MBP-2022.fritz.box 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "22.0.2" 2024-07-16 OpenJDK Runtime Environment Temurin-22.0.2+9 (build 22.0.2+9) OpenJDK 64-Bit Server VM Temurin-22.0.2+9 (build 22.0.2+9, mixed mode)

### Quarkus version or git rev

3.14.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256) Maven home: /Users/stuetz/.m2/wrapper/dists/apache-maven-3.9.8-bin/337e6d14/apache-maven-3.9.8 Java version: 22.0.2, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-22.jdk/Contents/Home Default locale: en_AT, platform encoding: UTF-8 OS name: "mac os x", version: "14.6.1", arch: "aarch64", family: "mac"

### Additional information

H2 is working fine

**Comment by melloware** [comment]
Sounds like this is the issue: https://github.com/quarkusio/quarkus/issues/42247

**Comment by gsmet** [comment]
This is not related to the Hibernate ORM depreciation of Derby dialects as it's Derby classes loading Derby classes.

We missed that they added a new artifact when we updated and it needs to be registered as parent first.

I added `derbynet` but I have another failure now with `java.lang.NoClassDefFoundError: org/apache/derby/iapi/jdbc/JDBCBoot` and that is odd as it should be there and parent first...

**Comment by gsmet** [comment]
I think dev mode got broken by this update: https://github.com/quarkusio/quarkus/pull/41084 .

Their source code is still hosted in Subversion AFAICS and there is no UI available. There is a Git mirror but it seems very outdated.

Frankly, I think we will have to deprecate Derby or to stick to an old version (but it will come with some challenges given the description of the PR above). Except if someone wants to track exactly when the problem was introduced and how to work around the CL issues - but it might not be easy.

Out of curiosity, why are you using Derby?

/cc @yrodiere

**Comment by yrodiere** [comment]
Related: #42247, where we're considering removal of the Derby integration in the short to medium term.

**Comment by ThomasStuetz** [comment]
> 
> Out of curiosity, why are you using Derby?
> 
> /cc @yrodiere

Thank you for your answers.

DerbyDb is used for educational purposes.
I am a teacher at a higher technical college. We are teaching quarkus in our courses.
Unfortunately it is not possible to use docker in our labs, so derby is very useful.

Best regards
Thomas

**Comment by ThomasStuetz** [comment]
@yrodiere 
Thank you for the informations. Yes - maybe we have to change to H2. Hopefully, the H2 support will not be removed, too.

**Comment by yrodiere** [comment]
No problem.

> Hopefully, the H2 support will not be removed, too.

Removing H2 is very, very unlikely. It's too popular.

**Comment by ThomasStuetz** [comment]
Thank you, for your help

**Comment by kiharakarua** [comment]
For anyone still facing this issue **_and happens not to be using panache or hibernate_**, it might help to connect to derby [as an "other" datasource](https://quarkus.io/guides/datasource#other-databases) and not use the quarkus-jdbc-derby extension. Of course this means you lose the auto-configured dev-services. But it'll get rid of the error.
It also works as a workaround for this [issue](https://github.com/quarkusio/quarkus/issues/36652)
