### ISSUE TITLE
Strange behavior in dev mode with quarkus-picocli and quarkus-rest dependencies.

### ISSUE THREAD

**Issue by jcarranzan** [quarkusio/quarkus#43182]
### Describe the bug

I encountered a strange behavior while working with a Quarkus application that includes the following dependencies: `quarkus-picocli and quarkus-rest`.

When I run the application in development mode using:
`mvn quarkus:dev`
and navigate to [http://localhost:8080]() then the console shows numerous error logs related to  ` io.vertx.ext.web...`

### Expected behavior

See the `http://localhost:8080/q/dev-ui` UI with no errors.

### Actual behavior

Part of the error trace:
```
2024-09-10 14:54:32,385 ERROR [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-0) Unhandled exception in router [Error Occurred After Shutdown]: java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.vertx.http.runtime.QuarkusErrorHandler$ContentTypes
	at io.quarkus.vertx.http.runtime.QuarkusErrorHandler.handle(QuarkusErrorHandler.java:123)
	at io.quarkus.vertx.http.runtime.QuarkusErrorHandler.handle(QuarkusErrorHandler.java:31)
	at io.vertx.ext.web.impl.RouteState.handleFailure(RouteState.java:1291)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:174)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$7.handle(ResteasyReactiveRecorder.java:237)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$7.handle(ResteasyReactiveRecorder.java:196)
	at io.vertx.ext.web.impl.RouteState.handleFailure(RouteState.java:1291)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:174)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:204)
	at io.vertx.ext.web.impl.RouterImpl.handleFailure(RouterImpl.java:256)
	at io.vertx.ext.web.impl.RouteState.handleFailure(RouteState.java:1291)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:174)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:557)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:196)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:185)
	at io.vertx.ext.web.impl.RoutingContextImplBase.handleInHandlerRuntimeFailure(RoutingContextImplBase.java:215)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:182)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:358)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:347)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup.handleHotReplacementRequest(VertxHttpHotReplacementSetup.java:144)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$HotReplacementRoutingContextHandler.handle(VertxHttpRecorder.java:1606)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$HotReplacementRoutingContextHandler.handle(VertxHttpRecorder.java:1596)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.impl.RoutingContextImplBase.restart(RoutingContextImplBase.java:130)
	at io.vertx.ext.web.impl.RoutingContextImpl.reroute(RoutingContextImpl.java:439)
	at io.vertx.ext.web.impl.RoutingContextWrapper.reroute(RoutingContextWrapper.java:308)
	at io.vertx.ext.web.RoutingContext.reroute(RoutingContext.java:576)
	at io.quarkus.devui.runtime.VaadinRouterHandler.handle(VaadinRouterHandler.java:31)
	at io.quarkus.devui.runtime.VaadinRouterHandler.handle(VaadinRouterHandler.java:9)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:65)
	at io.quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:15)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:68)
	at io.quarkus.devui.runtime.DevUIBuildTimeStaticHandler.handle(DevUIBuildTimeStaticHandler.java:15)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.devmode.FileSystemStaticHandler.sendStatic(FileSystemStaticHandler.java:140)
	at io.quarkus.vertx.http.runtime.devmode.FileSystemStaticHandler.handle(FileSystemStaticHandler.java:86)
	at io.quarkus.vertx.http.runtime.devmode.FileSystemStaticHandler.handle(FileSystemStaticHandler.java:32)
	at io.quarkus.vertx.http.runtime.webjar.WebJarStaticHandler.handle(WebJarStaticHandler.java:94)
	at io.quarkus.vertx.http.runtime.webjar.WebJarStaticHandler.handle(WebJarStaticHandler.java:18)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:138)
	at io.quarkus.devui.runtime.DevUICORSFilter.handle(DevUICORSFilter.java:50)
	at io.quarkus.devui.runtime.DevUICORSFilter.handle(DevUICORSFilter.java:17)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.devui.runtime.LocalHostOnlyFilter.handle(LocalHostOnlyFilter.java:31)
	at io.quarkus.devui.runtime.LocalHostOnlyFilter.handle(LocalHostOnlyFilter.java:15)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:250)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:62)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:40)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:358)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:347)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.handle(VertxHttpHotReplacementSetup.java:204)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$5.handle(VertxHttpHotReplacementSetup.java:192)
	at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```	

### How to Reproduce?

1.` git clone -b picocli-rest-errors` [https://github.com/jcarranzan/quarkus-reproducer.git]()
2. `mvn quarkus:dev`
3. and go to [http://localhost:8080]()

**Comment by mkouba** [comment]
I think that it's the consequence of the [different lifecyle](https://quarkus.io/guides/command-mode-reference#the-command-mode-lifecycle) for command apps, i.e. the app is started, the command is executed and the app is shut down (even in the dev mode; you can hit `[space]` to restart the app). If you add `Quarkus.waitForExit()` in the `HelloCommand#run()` method then it runs like a normal app.

**Comment by maxandersen** [comment]
Agree that is the cause but why is it resulting in a nockassdeffound ? Should we not be able to detect a mismatch somehow?

**Comment by mkouba** [comment]
> Agree that is the cause but why is it resulting in a nockassdeffound ? Should we not be able to detect a mismatch somehow?

I believe that the HTTP server should not be running at all in this case. I mean, if the app is down it does not make sense to keep the HTTP server (and Dev UI) around. IIRC we do not stop the HTTP server because of the live reload feature. But in this particular case, there's no live reload...

**Comment by ebullient** [comment]
> > Agree that is the cause but why is it resulting in a nockassdeffound ? Should we not be able to detect a mismatch somehow?
> 
> I believe that the HTTP server should not be running at all in this case. I mean, if the app is down it does not make sense to keep the HTTP server (and Dev UI) around. IIRC we do not stop the HTTP server because of the live reload feature. But in this particular case, there's no live reload...

I have a CLI that sometimes runs a background thing (it uses Camel). So if you start it without arguments, it starts up an HTTP server and waits for you to cancel/kill it. Just as you say, I use `Quarkus.waitForExit()` when in this mode, and live reload works just fine.

Timing during teardown is ... challenging. `Quarkus.waitForExit()` or manually/correctly triggering exit with `Quarkus.asyncExit()` are the ways to do this cleanly.

**Comment by mkouba** [comment]
> Timing during teardown is ... challenging. `Quarkus.waitForExit()` or manually/correctly triggering exit with `Quarkus.asyncExit()` are the ways to do this cleanly.

Hm, what exactly do you mean? I don't think that `Quarkus.asyncExit()` could help. The thing is that for a command app the Quarkus app is stopped, the JVM is not stopped and the HTTP server is not stopped either (in fact, it's  the `Vertx` instance that "survives" live reloads).

**Comment by ebullient** [comment]
I was thinking that his CLI might have some other exit condition other than Ctrl-C, where `Quarkus.asyncExit()` would be the correct way for his code to initiate a shutdown (combined with `Quarkus.waitForExit()` to otherwise prevent immediate shutdown).

I haven't worked on Pockets in earnest for awhile, but `quarkus dev` is fine for reloading (if you are using `Quarkus.waitForExit()`), but running tests will be weird. 

Pockets had two modes.. tests were only ever with parameters that kept it in one and done (do a thing and exit). Quarkus dev was useful for live reloading, but not for running tests. A bit of a split-brain feeling.

**Comment by jcarranzan** [comment]
I tested this case in dev mode using Quarkus.asyncExit(), as suggested by @mkouba  about the lifecycle with command Quarkus applications and it worked fine.
I think this information could be added to the guide in some way [picocli#development-mode](https://quarkus.io/guides/picocli#development-mode).
However, for our `quarkus-test-suite `using the Maven Failsafe plugin, I observed that Quarkus.asyncExit() seems unnecessary.
Thanks for your suggestions

**Comment by mkouba** [comment]
> I think this information could be added to the guide in some way [picocli#development-mode](https://quarkus.io/guides/picocli#development-mode).

@jcarranzan :+1: Would you care to send a pull request?

**Comment by jcarranzan** [comment]
> > I think this information could be added to the guide in some way [picocli#development-mode](https://quarkus.io/guides/picocli#development-mode).
> 
> @jcarranzan 👍 Would you care to send a pull request?

Sure, I'll do it.

**Comment by jcarranzan** [comment]
PR --> https://github.com/quarkusio/quarkus/pull/43282
