### ISSUE TITLE
Quarkus Websockets Next connection error

### ISSUE THREAD

**Issue by andreiyusupau** [quarkusio/quarkus#43215]
### Describe the bug

Hi!
I'm running into exception when trying to connect to external endpoint via Quarkus Websockets Next:
```java
io.vertx.core.http.UpgradeRejectedException: WebSocket upgrade failure: 301
	at io.vertx.core.http.impl.WebSocketHandshakeInboundHandler.handshakeComplete(WebSocketHandshakeInboundHandler.java:102)
	at io.vertx.core.http.impl.WebSocketHandshakeInboundHandler.channelRead(WebSocketHandshakeInboundHandler.java:84)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
Jakarta WS works well for this case, examples below.

### Expected behavior

Connection to `wss://example.com/ws` is established successfully.

### How to Reproduce?

Here is my WS Next client:
```java
@WebSocketClient(path = "/ws")
public class WebsocketClientNext {

    @OnOpen
    void onOpen(WebSocketClientConnection connection) {
        System.out.println("Opened");
    }

    @OnTextMessage
    void onMessage(String message, WebSocketClientConnection connection) {
        System.out.println(message);
    }

}
```
And it's wrapper:
```java
@ApplicationScoped
public class WebsocketClientNextWrapper {

    @Inject
    WebSocketConnector<WebsocketClientNext> connector;

    public void openAndSendMessage() {
        var connection = connector.baseUri(URI.create("wss://example.com"))
                .connectAndAwait();
    }
```

Example with Jakarta WS that works fine:
```java
@ClientEndpoint
public class WebsocketClient {

    public WebsocketClient() {
        try {
            var container = ContainerProvider.getWebSocketContainer();
            container.connectToServer(this, URI.create("wss://example.com/ws"));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @OnOpen
    public void open(Session session) {
        System.out.println("Opened");
    }

    @OnMessage
    void message(String msg) {
        System.out.println(msg);
    }

}
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.4037]

### Output of `java -version`

Amazon Corretto 21.0.1

### Quarkus version or git rev

3.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.10

**Comment by mkouba** [comment]
I believe that this was fixed in 3.14.2; here's the PR: https://github.com/quarkusio/quarkus/pull/42826

@andreiyusupau could you pls try your app with Quarkus 3.14.2?
