### ISSUE TITLE
Fails to shutdown when using grpc and kafka-streams extensions

### ISSUE THREAD

**Issue by pcasaes** [quarkusio/quarkus#43228]
### Describe the bug

If we have a project with quarkus-grpc (grpc server) and quarkus-kafka-streams, it will fail and hang when shutting down:

```
ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-0) Uncaught exception received by Vert.x [Error Occurred After Shutdown]: java.util.concurrent.RejectedExecutionException
        at org.jboss.threads.RejectingExecutor.execute(RejectingExecutor.java:20)
        at org.jboss.threads.EnhancedQueueExecutor.rejectShutdown(EnhancedQueueExecutor.java:2119)
        at org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:801)
        at io.vertx.core.impl.TaskQueue.execute(TaskQueue.java:149)
        at io.vertx.core.impl.ContextImpl.internalExecuteBlocking(ContextImpl.java:217)
        at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:189)
        at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:131)
        at io.vertx.core.impl.ContextInternal.executeBlocking(ContextInternal.java:155)
        at io.vertx.core.Context.executeBlocking(Context.java:194)
        at io.vertx.grpc.VertxServer$ActualServer.lambda$stop$7(VertxServer.java:139)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)
        at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        Suppressed: java.util.concurrent.RejectedExecutionException: Executor is being shut down
                at org.jboss.threads.EnhancedQueueExecutor.rejectShutdown(EnhancedQueueExecutor.java:2121)
                ... 19 more

```

This happens when running tests, or a production build. Does not happen in dev mode.

### Expected behavior

Should shutdown graceful

### Actual behavior

Erros is logged and shutdown hangs.

### How to Reproduce?

With this reporoducer
https://github.com/pcasaes/quarkus-grpc-kafka-stream-shutdown-fail-repo

Run tests (requires docker running)

```
./mvnw clean verify
```

### Output of `uname -a` or `ver`

Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "21.0.4" 2024-07-16 LTS OpenJDK Runtime Environment Corretto-21.0.4.7.1 (build 21.0.4+7-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.4.7.1 (build 21.0.4+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.14.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)

**Comment by cescoffier** [comment]
It looks like there is a task using Vert.x that is executed after Vert.x being shutdown. Do you know what is this task?

**Comment by pcasaes** [comment]
I do not. The repropducer was made by using [quarkus get started](https://quarkus.io/get-started/), selecting the grpc and kafka streams extension, and adding the code and configuration from https://quarkus.io/guides/kafka-streams#creating-the-aggregator-maven-project.

If we change `quarkus.grpc.server.use-separate-server` to false (default is true) then the issue does not happen.

**Comment by pcasaes** [comment]
It's vertx trying to enqueue something at shutdown

```
at io.vertx.grpc.VertxServer$ActualServer.lambda$stop$7(VertxServer.java:139)
```

**Comment by cescoffier** [comment]
Thanks! 

I wonder how Kafka streams is impacting the shutdown of gRPC. @ozangunalp /  @alesj any idea?

**Comment by alesj** [comment]
Well, VertxServer::stop (gRPC) does a bunch of Vert.x context magic 

```
    void stop(ContextInternal context, Promise<Void> promise) {
      boolean shutdown = count.decrementAndGet() == 0;
      context.runOnContext(v -> {
        group.removeWorker(context.nettyEventLoop());
        contextLocal.get().remove(context);
        if (shutdown) {
          map.remove(id);
          context.executeBlocking(p -> {
            server.shutdown();
            p.complete();
          }, promise);
        } else {
          promise.complete();
        }
      });
    }
```

... but I don't see how Kafka Streams could mess this up, if used together with gRPC.

>> If we change quarkus.grpc.server.use-separate-server to false (default is true) then the issue does not happen.

This is (probably) expected, as then there is only one HTTP(s) server, aka no VertxServer.

**Comment by alesj** [comment]
@pcasaes does this also happen with older Quarkus versions?

**Comment by pcasaes** [comment]
Testing...

3.13.3 -> issue present
3.12.1 -> issue present
3.11.1 -> issue present
3.10.1 -> issue present
3.9.1 -> issue present
3.8.1 -> issue present

**Comment by cescoffier** [comment]
Great catch! It should NOT try to shutdown the executor. This is managed by Quarkus itself.

**Comment by ozangunalp** [comment]
I thought we didn't allow for shutdown the managed worker executor service but apparently we did. 
I'll send a separate PR for that one.

**Comment by pcasaes** [comment]
thanks!
