### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in Quarkus 3.14.3 (Hibernate related)

### ISSUE THREAD

**Issue by c-schmitz-tsystems** [quarkusio/quarkus#43233]
### Describe the bug

in our junit tests addressing a dedicated entity we receive the following error (look in actual behaviour) in quarkus 3.14.3. 
because i have no time for a reproducer i can show the code snippet in the class where the bug occurs:

The initializers- and the state-Array have different sizes. The access to the state array via index i produces the error

org.hibernate.sql.results.graph.entity.internal.EntityInitializerImpl:

    protected void resolveInstanceSubInitializers(EntityInitializerData data) {
        int subclassId = data.concreteDescriptor.getSubclassId();
        Initializer<?>[] initializers = this.subInitializersForResolveFromInitialized[subclassId];
        EntityEntry entityEntry;
        ImmutableBitSet maybeLazySet;
        if (initializers.length != 0 && ((maybeLazySet = (entityEntry = data.entityHolder.getEntityEntry()).getMaybeLazySet()) == null || !this.lazySets[subclassId].contains(maybeLazySet))) {
            RowProcessingState rowProcessingState = data.getRowProcessingState();

            assert entityEntry == rowProcessingState.getSession().getPersistenceContextInternal().getEntry(data.entityInstanceForNotify);

            Object[] loadedState = entityEntry.getLoadedState();
            Object[] state;
            if (loadedState == null) {
                if (entityEntry.getStatus() != Status.READ_ONLY) {
                    assert entityEntry.getStatus() == Status.LOADING;

                    return;
                }

                state = data.concreteDescriptor.getValues(data.entityInstanceForNotify);
            } else {
                state = loadedState;
            }

            for(int i = 0; i < initializers.length; ++i) {
                Initializer<?> initializer = initializers[i];
                if (initializer != null && (maybeLazySet == null || maybeLazySet.get(i))) {
                    **Object subInstance = state[i];**
                    if (subInstance == LazyPropertyInitializer.UNFETCHED_PROPERTY) {
                        initializer.resolveKey(rowProcessingState);
                    } else {
                        initializer.resolveInstance(subInstance, rowProcessingState);
                    }
                }
            }

        }
    }

### Expected behavior

in earlier versions of quarkus the same code works without any error

### Actual behavior

java.lang.ArrayIndexOutOfBoundsException: Index 19 out of bounds for length 18
	at org.hibernate.sql.results.graph.entity.internal.EntityInitializerImpl.resolveInstanceSubInitializers(EntityInitializerImpl.java:593)
	at org.hibernate.sql.results.graph.entity.internal.EntityInitializerImpl.resolveKey(EntityInitializerImpl.java:534)
	at org.hibernate.sql.results.graph.entity.internal.EntityInitializerImpl.resolveKey(EntityInitializerImpl.java:424)
	at org.hibernate.sql.results.graph.entity.internal.EntityInitializerImpl.resolveKey(EntityInitializerImpl.java:94)
	at org.hibernate.sql.results.internal.StandardRowReader.coordinateInitializers(StandardRowReader.java:235)
	at org.hibernate.sql.results.internal.StandardRowReader.readRow(StandardRowReader.java:141)
	at org.hibernate.sql.results.spi.ListResultsConsumer.read(ListResultsConsumer.java:249)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:201)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:35)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:224)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:102)
	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.executeQuery(JdbcSelectExecutor.java:91)
	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:165)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$1(ConcreteSqmSelectQueryPlan.java:152)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:442)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:362)
	at org.hibernate.query.sqm.internal.SqmSelectionQueryImpl.doList(SqmSelectionQueryImpl.java:299)
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:136)
	at org.hibernate.query.SelectionQuery.getResultList(SelectionQuery.java:124)
	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.list(CommonPanacheQueryImpl.java:303)
	at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.list(PanacheQueryImpl.java:150)

### Output of `java -version`

openjdk version "17.0.10" 2024-01-16 LTS OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS) OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.14.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by yrodiere** [comment]
Hello.

Thanks for reporting, but this definitely doesn't look like something Quarkus has any influence on.

Can you please report this to the Hibernate Jira instead? https://hibernate.atlassian.net/browse/HHH
