### ISSUE TITLE
Could not install quarkus using jbang

### ISSUE THREAD

**Issue by Kwaadpepper** [quarkusio/quarkus#43235]
### Describe the bug

    [jbang] [80:263] Requesting HTTP GET https://bitbucket.org/quarkusio/jbang-catalog/raw/HEAD/jbang-catalog.json
    [jbang] [80:264] Headers {User-Agent=[JBang/0.117.1 (Linux/6.10.8-200.fc40.x86_64/amd64) Java/21.0.4/Eclipse Adoptium]}
    [jbang] [83:387] No catalog found at https://bitbucket.org/quarkusio/jbang-catalog/src/HEAD/jbang-catalog.json

### Expected behavior

It looks like nothing related to quarkus is present on bitbucket.

### Actual behavior

Install fails. I cannot run quarkus.

### How to Reproduce?

    jbang app install --fresh --force --verbose quarkus@quarkusio 
    [jbang] [0:385] jbang version 0.117.1
    [jbang] [0:407] Resolving resource ref: quarkus@quarkusio
    [jbang] [0:416] Reading catalog from classpath:/jbang-catalog.json
    [jbang] [0:463] Reading catalog from classpath:/jbang-catalog.json
    [jbang] [0:593] Requesting HTTP GET https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json
    [jbang] [0:593] Headers {User-Agent=[JBang/0.117.1 (Linux/6.10.8-200.fc40.x86_64/amd64) Java/21.0.4/Eclipse Adoptium]}
    [jbang] [36:735] Unable to read catalog https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json because dev.jbang.cli.ExitException: Could not download https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json
    [jbang] [36:737] Local catalog 'quarkusio' not found, trying implicit catalogs...
    [jbang] [36:754] Requesting HTTP GET https://raw.githubusercontent.com/quarkusio/jbang-catalog/HEAD/jbang-catalog.json
    [jbang] [36:754] Headers {User-Agent=[JBang/0.117.1 (Linux/6.10.8-200.fc40.x86_64/amd64) Java/21.0.4/Eclipse Adoptium]}
    [jbang] [44:183] No catalog found at https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json
    dev.jbang.cli.ExitException: Could not download https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json
	    at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:119)
	    at dev.jbang.source.resolvers.RemoteResourceResolver.resolve(RemoteResourceResolver.java:41)
	    at dev.jbang.source.resolvers.CombinedResourceResolver.lambda$resolve$0(CombinedResourceResolver.java:27)
	    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	    at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1034)
	    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	    at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	    at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	    at dev.jbang.source.resolvers.CombinedResourceResolver.resolve(CombinedResourceResolver.java:29)
	    at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	    at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:131)
	    at dev.jbang.catalog.Catalog.getByRef(Catalog.java:190)
	    at dev.jbang.catalog.ImplicitCatalogRef.tryDownload(ImplicitCatalogRef.java:85)
	    at dev.jbang.catalog.ImplicitCatalogRef.lambda$resolveImplicitCatalogUrl$2(ImplicitCatalogRef.java:76)
	    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	    at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1034)
	    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	    at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	    at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	    at dev.jbang.catalog.ImplicitCatalogRef.resolveImplicitCatalogUrl(ImplicitCatalogRef.java:79)
	    at dev.jbang.catalog.CatalogRef.getRemote(CatalogRef.java:77)
	    at dev.jbang.catalog.CatalogRef.get(CatalogRef.java:40)
	    at dev.jbang.catalog.Catalog.getByName(Catalog.java:143)
	    at dev.jbang.catalog.Alias.fromCatalog(Alias.java:275)
	    at dev.jbang.catalog.Alias.merge(Alias.java:200)
	    at dev.jbang.catalog.Alias.get(Alias.java:165)
	    at dev.jbang.source.resolvers.AliasResourceResolver.resolve(AliasResourceResolver.java:39)
	    at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	    at dev.jbang.source.ProjectBuilder.resolveChecked(ProjectBuilder.java:229)
	    at dev.jbang.source.ProjectBuilder.build(ProjectBuilder.java:218)
	    at dev.jbang.cli.AppInstall.install(App.java:139)
	    at dev.jbang.cli.AppInstall.doCall(App.java:104)
	    at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	    at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	    at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	    at picocli.CommandLine.access$1500(CommandLine.java:148)
	    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	    at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	    at dev.jbang.cli.JBang$3.handle(JBang.java:148)
	    at dev.jbang.cli.JBang$3.handle(JBang.java:143)
	    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	    at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	    at picocli.CommandLine.execute(CommandLine.java:2170)
	    at dev.jbang.Main.main(Main.java:14)
    Caused by: java.net.SocketException: Le réseau n'est pas accessible
	    at java.base/sun.nio.ch.Net.connect0(Native Method)
	    at java.base/sun.nio.ch.Net.connect(Net.java:589)
	    at java.base/sun.nio.ch.Net.connect(Net.java:578)
	    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
	    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	    at java.base/java.net.Socket.connect(Socket.java:751)
	    at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	    at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
	    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	    at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	    at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
	    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
	    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
	    at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
	    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307)
	    at dev.jbang.util.Util.handleRedirects(Util.java:1093)
	    at dev.jbang.util.Util.access$400(Util.java:75)
	    at dev.jbang.util.Util$ResultHandler.lambda$redirects$0(Util.java:896)
	    at dev.jbang.util.Util.connect(Util.java:818)
	    at dev.jbang.util.Util.downloadFileAndCache(Util.java:747)
	    at dev.jbang.util.Util.downloadAndCacheFile(Util.java:698)
	    at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:116)
	    ... 51 more
    [jbang] [44:201] Requesting HTTP GET https://gitlab.com/quarkusio/jbang-catalog/-/raw/HEAD/jbang-catalog.json
    [jbang] [44:202] Headers {User-Agent=[JBang/0.117.1 (Linux/6.10.8-200.fc40.x86_64/amd64) Java/21.0.4/Eclipse Adoptium]}
    [jbang] [80:252] No catalog found at https://gitlab.com/quarkusio/jbang-catalog/-/blob/HEAD/jbang-catalog.json
    dev.jbang.cli.ExitException: Could not download https://gitlab.com/quarkusio/jbang-catalog/-/blob/HEAD/jbang-catalog.json
	    at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:119)
	    at dev.jbang.source.resolvers.RemoteResourceResolver.resolve(RemoteResourceResolver.java:41)
	    at dev.jbang.source.resolvers.CombinedResourceResolver.lambda$resolve$0(CombinedResourceResolver.java:27)
	    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	    at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1034)
	    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	    at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	    at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	    at dev.jbang.source.resolvers.CombinedResourceResolver.resolve(CombinedResourceResolver.java:29)
	    at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	    at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:131)
	    at dev.jbang.catalog.Catalog.getByRef(Catalog.java:190)
	    at dev.jbang.catalog.ImplicitCatalogRef.tryDownload(ImplicitCatalogRef.java:85)
	    at dev.jbang.catalog.ImplicitCatalogRef.lambda$resolveImplicitCatalogUrl$3(ImplicitCatalogRef.java:77)
	    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	    at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1034)
	    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	    at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	    at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	    at dev.jbang.catalog.ImplicitCatalogRef.resolveImplicitCatalogUrl(ImplicitCatalogRef.java:79)
	    at dev.jbang.catalog.CatalogRef.getRemote(CatalogRef.java:77)
	    at dev.jbang.catalog.CatalogRef.get(CatalogRef.java:40)
	    at dev.jbang.catalog.Catalog.getByName(Catalog.java:143)
	    at dev.jbang.catalog.Alias.fromCatalog(Alias.java:275)
	    at dev.jbang.catalog.Alias.merge(Alias.java:200)
	    at dev.jbang.catalog.Alias.get(Alias.java:165)
	    at dev.jbang.source.resolvers.AliasResourceResolver.resolve(AliasResourceResolver.java:39)
	    at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	    at dev.jbang.source.ProjectBuilder.resolveChecked(ProjectBuilder.java:229)
	    at dev.jbang.source.ProjectBuilder.build(ProjectBuilder.java:218)
	    at dev.jbang.cli.AppInstall.install(App.java:139)
	    at dev.jbang.cli.AppInstall.doCall(App.java:104)
	    at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	    at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	    at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	    at picocli.CommandLine.access$1500(CommandLine.java:148)
	    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	    at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	    at dev.jbang.cli.JBang$3.handle(JBang.java:148)
	    at dev.jbang.cli.JBang$3.handle(JBang.java:143)
	    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	    at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	    at picocli.CommandLine.execute(CommandLine.java:2170)
	    at dev.jbang.Main.main(Main.java:14)
    Caused by: java.net.SocketException: Le réseau n'est pas accessible
	    at java.base/sun.nio.ch.Net.connect0(Native Method)
	    at java.base/sun.nio.ch.Net.connect(Net.java:589)
	    at java.base/sun.nio.ch.Net.connect(Net.java:578)
	    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
	    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	    at java.base/java.net.Socket.connect(Socket.java:751)
	    at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	    at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
	    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	    at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	    at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
	    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
	    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
	    at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
	    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307)
	    at dev.jbang.util.Util.handleRedirects(Util.java:1093)
	    at dev.jbang.util.Util.access$400(Util.java:75)
	    at dev.jbang.util.Util$ResultHandler.lambda$redirects$0(Util.java:896)
	    at dev.jbang.util.Util.connect(Util.java:818)
	    at dev.jbang.util.Util.downloadFileAndCache(Util.java:747)
	    at dev.jbang.util.Util.downloadAndCacheFile(Util.java:698)
	    at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:116)
	    ... 51 more
    [jbang] [80:263] Requesting HTTP GET https://bitbucket.org/quarkusio/jbang-catalog/raw/HEAD/jbang-catalog.json
    [jbang] [80:264] Headers {User-Agent=[JBang/0.117.1 (Linux/6.10.8-200.fc40.x86_64/amd64) Java/21.0.4/Eclipse Adoptium]}
    [jbang] [83:387] No catalog found at https://bitbucket.org/quarkusio/jbang-catalog/src/HEAD/jbang-catalog.json
    dev.jbang.cli.ExitException: Could not download https://bitbucket.org/quarkusio/jbang-catalog/src/HEAD/jbang-catalog.json
	    at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:119)
	    at dev.jbang.source.resolvers.RemoteResourceResolver.resolve(RemoteResourceResolver.java:41)
	    at dev.jbang.source.resolvers.CombinedResourceResolver.lambda$resolve$0(CombinedResourceResolver.java:27)
	    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	    at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1034)
	    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	    at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	    at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	    at dev.jbang.source.resolvers.CombinedResourceResolver.resolve(CombinedResourceResolver.java:29)
	    at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	    at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:131)
	    at dev.jbang.catalog.Catalog.getByRef(Catalog.java:190)
	    at dev.jbang.catalog.ImplicitCatalogRef.tryDownload(ImplicitCatalogRef.java:85)
	    at dev.jbang.catalog.ImplicitCatalogRef.lambda$resolveImplicitCatalogUrl$4(ImplicitCatalogRef.java:78)
	    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	    at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1034)
	    at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	    at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	    at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	    at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	    at dev.jbang.catalog.ImplicitCatalogRef.resolveImplicitCatalogUrl(ImplicitCatalogRef.java:79)
	    at dev.jbang.catalog.CatalogRef.getRemote(CatalogRef.java:77)
	    at dev.jbang.catalog.CatalogRef.get(CatalogRef.java:40)
	    at dev.jbang.catalog.Catalog.getByName(Catalog.java:143)
	    at dev.jbang.catalog.Alias.fromCatalog(Alias.java:275)
	    at dev.jbang.catalog.Alias.merge(Alias.java:200)
	    at dev.jbang.catalog.Alias.get(Alias.java:165)
	    at dev.jbang.source.resolvers.AliasResourceResolver.resolve(AliasResourceResolver.java:39)
	    at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	    at dev.jbang.source.ProjectBuilder.resolveChecked(ProjectBuilder.java:229)
	    at dev.jbang.source.ProjectBuilder.build(ProjectBuilder.java:218)
	    at dev.jbang.cli.AppInstall.install(App.java:139)
	    at dev.jbang.cli.AppInstall.doCall(App.java:104)
	    at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	    at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	    at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	    at picocli.CommandLine.access$1500(CommandLine.java:148)
	    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	    at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	    at dev.jbang.cli.JBang$3.handle(JBang.java:148)
	    at dev.jbang.cli.JBang$3.handle(JBang.java:143)
	    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	    at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	    at picocli.CommandLine.execute(CommandLine.java:2170)
	    at dev.jbang.Main.main(Main.java:14)
    Caused by: java.net.SocketException: Le réseau n'est pas accessible
	    at java.base/sun.nio.ch.Net.connect0(Native Method)
	    at java.base/sun.nio.ch.Net.connect(Net.java:589)
	    at java.base/sun.nio.ch.Net.connect(Net.java:578)
	    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
	    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	    at java.base/java.net.Socket.connect(Socket.java:751)
	    at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	    at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
	    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	    at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	    at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
	    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
	    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
	    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
	    at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
	    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307)
	    at dev.jbang.util.Util.handleRedirects(Util.java:1093)
	    at dev.jbang.util.Util.access$400(Util.java:75)
	    at dev.jbang.util.Util$ResultHandler.lambda$redirects$0(Util.java:896)
	    at dev.jbang.util.Util.connect(Util.java:818)
	    at dev.jbang.util.Util.downloadFileAndCache(Util.java:747)
	    at dev.jbang.util.Util.downloadAndCacheFile(Util.java:698)
	    at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:116)
	    ... 51 more
    [jbang] [83:389] [ERROR] Unknown catalog 'quarkusio'
    dev.jbang.cli.ExitException: Unknown catalog 'quarkusio'
	    at dev.jbang.catalog.Catalog.getByName(Catalog.java:147)
	    at dev.jbang.catalog.Alias.fromCatalog(Alias.java:275)
	    at dev.jbang.catalog.Alias.merge(Alias.java:200)
	    at dev.jbang.catalog.Alias.get(Alias.java:165)
	    at dev.jbang.source.resolvers.AliasResourceResolver.resolve(AliasResourceResolver.java:39)
	    at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	    at dev.jbang.source.ProjectBuilder.resolveChecked(ProjectBuilder.java:229)
	    at dev.jbang.source.ProjectBuilder.build(ProjectBuilder.java:218)
	    at dev.jbang.cli.AppInstall.install(App.java:139)
	    at dev.jbang.cli.AppInstall.doCall(App.java:104)
	    at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	    at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	    at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	    at picocli.CommandLine.access$1500(CommandLine.java:148)
	    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	    at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	    at dev.jbang.cli.JBang$3.handle(JBang.java:148)
	    at dev.jbang.cli.JBang$3.handle(JBang.java:143)
	    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	    at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	    at picocli.CommandLine.execute(CommandLine.java:2170)
	    at dev.jbang.Main.main(Main.java:14)
    [jbang] [83:390] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues

### Output of `uname -a` or `ver`

Linux fedora-jeremy 6.10.8-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Sep  4 21:41:11 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.4" 2024-07-16 LTS OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)

**Comment by gsmet** [comment]
Looks like a network error. Do you use a proxy by any chance?

**Comment by Kwaadpepper** [comment]
No at all, I also tried using my cell phone.

**Comment by gsmet** [comment]
From what I can see the first error is:
```
[jbang] [0:593] Requesting HTTP GET https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json
[jbang] [0:593] Headers {User-Agent=[JBang/0.117.1 (Linux/6.10.8-200.fc40.x86_64/amd64) Java/21.0.4/Eclipse Adoptium]}
[jbang] [36:735] Unable to read catalog https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json because dev.jbang.cli.ExitException: Could not download https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json
```

Which is a bit odd as I can access the file without any error.

Are you able to download https://raw.githubusercontent.com/jbanghub/jbang-catalog/main/jbang-catalog.json from the command line?

**Comment by geoand** [comment]
Maybe it was just a transient network issue?

**Comment by Kwaadpepper** [comment]
Well I am at another location today so I could run the command successfully.

The reason why I opened the issue was because it was trying to fetch from a project on bitbucket that does not exist.

Thank you for your answers I will close this issue.

**Comment by maxandersen** [comment]
The reason it mention to bitbucket is that is the last fallback it takes. 

It would have looked at GitHub, gitlab then bitbucket ...

For some reason neither of those were available to you.

Any chance you were behind a firewall blocking off git hosting sites ?

**Comment by Kwaadpepper** [comment]
Non firewall, but the sys admin forces us to have a custom SSL certificate and add it to the system.
Also as of the bitbucket repo m, I could navigate to it but the repo seems to be emptied.
