### ISSUE TITLE
Application hangs when using quarkus.http.ssl.certificate.reload-period less than 30s 

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#43247]
### Describe the bug

After the exception:

```
2024-09-12 11:41:53,953 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-1) Uncaught exception received by Vert.x: java.lang.IllegalArgumentException: Unable to configure TLS reloading - The reload period cannot be less than 30 seconds
	at io.quarkus.vertx.http.runtime.options.TlsCertificateReloader.initCertReloadingAction(TlsCertificateReloader.java:80)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle$3.handle(VertxHttpRecorder.java:1335)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle$3.handle(VertxHttpRecorder.java:1303)
```

The application will hang, rather than terminate.

### Expected behavior

The application terminates.

### Actual behavior

The application hangs.

### How to Reproduce?

Configure TLS with a reload period that is too short:

quarkus.http.insecure-requests=disabled
quarkus.http.ssl.certificate.reload-period=10s
quarkus.http.ssl.certificate.key-store-file=...
quarkus.http.ssl.certificate.key-store-password=...

### Quarkus version or git rev

3.14.2

**Comment by geoand** [comment]
Thanks for reporting!

#43252 takes care of the issue
