### ISSUE TITLE
JVM mode provides more detail for exception than Native mode

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#43274]
### Describe the bug

JVM mode provides more detail for exception than Native mode

In the particular example I receive `Cannot invoke "String.length()" because "foo" is null` in JVM mode, but not in native.

This can be known limitation of native mode because of the AOT compilation, but better to file an issue to have have this tracked.

JVM mode
```
2024-09-13 13:19:47,761 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1)
  HTTP Request to /hello failed, error id: 7ef45749-6e13-433c-b076-f8e152aa673a-1: 
    java.lang.NullPointerException: Cannot invoke "String.length()" because "foo" is null
	at org.acme.GreetingResource.hello(GreetingResource.java:14)
	at org.acme.GreetingResource$quarkusrestinvoker$hello_e747664148511e1e5212d3e0f4b40d45c56ab8a1.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Native mode:
```
2024-09-13 13:23:00,206 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1)
  HTTP Request to /hello failed, error id: 3fd53fcf-65f5-43f8-a53a-aa87eb79e8ca-1:
    java.lang.NullPointerException
	at org.acme.GreetingResource.hello(GreetingResource.java:14)
	at org.acme.GreetingResource$quarkusrestinvoker$hello_e747664148511e1e5212d3e0f4b40d45c56ab8a1.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
```

### Expected behavior

Error message in Native mode provide the same level of details as in JVM mode.

### Actual behavior

JVM mode provides more context in the error message.

### How to Reproduce?

 * Get app from https://code.quarkus.io/
 * Adjust GreetingResource to through NPE, e.g. `String foo = null; return "Hello from Quarkus REST" + foo.length();`
 * Run `sdk use java 23.1.4.r21-mandrel` or equivalent
 * Run `mvn clean package -DskipTests && java -jar target/quarkus-app/quarkus-run.jar`
 * Hit http://localhost:8080/hello
 * Run `mvn clean package -DskipTests -Dnative && target/code-with-quarkus-1.0.0-SNAPSHOT-runner`
 * Hit http://localhost:8080/hello

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 21

### Mandrel or GraalVM version (if different from Java)

23.1.4.r21-mandrel

### Quarkus version or git rev

3.14.3

**Comment by geoand** [comment]
That's really interesting. 

@zakkak is this a known issue with GraalVM?

**Comment by zakkak** [comment]
I was not aware of it. I will report it upstream.

**Comment by zakkak** [comment]
Not sure, it's worth keeping this open. WDYT?

**Comment by geoand** [comment]
Let's close it as you the upstream issue is the real thing to track
