### ISSUE TITLE
Show nicer error when a `@ConfigMapping` class exists in the `deployment` module and set to the `runtime` phase

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#43394]
### Description

While creating (see this PR for more context - https://github.com/quarkusio/quarkus-workshops/pull/600), I noticed that the following error is thrown when the `@ConfigMapping` phase is set to RUN_TIME:

```java
Caused by: java.lang.ClassNotFoundException: io.quarkus.workshop.superheroes.version.deployment.VersionConfig
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:533)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:481)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:533)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:481)
	at io.quarkus.runtime.configuration.AbstractConfigBuilder.withMapping(AbstractConfigBuilder.java:64)
	... 21 more

``` 

The solution was to move the `@ConfigMapping` to the `runtime` module, but the error message is a bit cryptic.

- Zulip thread: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Workshop/near/471292983

### Implementation ideas

It would be nice if we could detect that somehow and display a nicer error message

**Comment by mcruzdev** [comment]
I would like to contribute with this one @gastaldi!

**Comment by radcortez** [comment]
Feel free to look into it.

This also applies to old `@ConfigRoot` class objects.
