### ISSUE TITLE
Blaze Persistence 'Secondary entity view roots' feature doesn't work after upgrade to Quarkus 3.14+

### ISSUE THREAD

**Issue by lujun2** [quarkusio/quarkus#43429]
### Describe the bug

After upgrade to Quarkus 3.14+, [Blaze Persistence Secondary entity view roots](https://persistence.blazebit.com/documentation/1.6/entity-view/manual/en_US/#secondary-entity-view-roots) mapping doesn't work, it report exception as below.

But this feature works in Quarkus 3.13+

```
java.lang.UnsupportedOperationException: Not implemented for org.hibernate.query.sqm.produce.function.StandardFunctionReturnTypeResolvers$3
	at org.hibernate.query.sqm.produce.function.FunctionReturnTypeResolver.resolveFunctionReturnType(FunctionReturnTypeResolver.java:46)
	at com.blazebit.persistence.integration.hibernate.base.function.HibernateSqmFunctionDescriptorAdapter.getReturnType(HibernateSqmFunctionDescriptorAdapter.java:133)
	at com.blazebit.persistence.view.impl.ScalarTargetResolvingExpressionVisitor.resolveToFunctionReturnType(ScalarTargetResolvingExpressionVisitor.java:619)
	at com.blazebit.persistence.view.impl.ScalarTargetResolvingExpressionVisitor.visit(ScalarTargetResolvingExpressionVisitor.java:503)
	at com.blazebit.persistence.parser.expression.FunctionExpression.accept(FunctionExpression.java:96)
	at com.blazebit.persistence.view.impl.metamodel.MetamodelBuildingContextImpl.getPossibleTargetTypes(MetamodelBuildingContextImpl.java:379)
	at com.blazebit.persistence.view.impl.metamodel.AttributeMapping.getPossibleTargetTypes(AttributeMapping.java:374)
	at com.blazebit.persistence.view.impl.metamodel.AttributeMapping.getType(AttributeMapping.java:446)
	at com.blazebit.persistence.view.impl.metamodel.AttributeMapping.getJavaType(AttributeMapping.java:362)
	at com.blazebit.persistence.view.impl.metamodel.AbstractAttribute.<init>(AbstractAttribute.java:158)
	at com.blazebit.persistence.view.impl.metamodel.AbstractMethodAttribute.<init>(AbstractMethodAttribute.java:66)
	at com.blazebit.persistence.view.impl.metamodel.AbstractMethodSingularAttribute.<init>(AbstractMethodSingularAttribute.java:69)
	at com.blazebit.persistence.view.impl.metamodel.attribute.MappingMethodSingularAttribute.<init>(MappingMethodSingularAttribute.java:34)
	at com.blazebit.persistence.view.impl.metamodel.MethodAttributeMapping.getMethodAttribute(MethodAttributeMapping.java:795)
	at com.blazebit.persistence.view.impl.metamodel.ManagedViewTypeImpl.<init>(ManagedViewTypeImpl.java:322)
	at com.blazebit.persistence.view.impl.metamodel.FlatViewTypeImpl.<init>(FlatViewTypeImpl.java:41)
	at com.blazebit.persistence.view.impl.metamodel.ViewMappingImpl.getManagedViewType(ViewMappingImpl.java:892)
	at com.blazebit.persistence.view.impl.metamodel.MetamodelBuildingContextImpl.getManagedViewType(MetamodelBuildingContextImpl.java:234)
	at com.blazebit.persistence.view.impl.metamodel.ViewMetamodelImpl.<init>(ViewMetamodelImpl.java:88)
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.<init>(EntityViewManagerImpl.java:271)
	at com.blazebit.persistence.view.impl.EntityViewConfigurationImpl.createEntityViewManager(EntityViewConfigurationImpl.java:257)
	at com.blazebit.persistence.integration.quarkus.runtime.EntityViewRecorder.lambda$entityViewManagerSupplier$1(EntityViewRecorder.java:97)
	at io.quarkus.arc.runtime.ArcRecorder$4.apply(ArcRecorder.java:130)
	at io.quarkus.arc.runtime.ArcRecorder$4.apply(ArcRecorder.java:127)
```

### How to Reproduce?

Reproducer repo:

https://github.com/lujun2/blaze-reproduce

### Output of `java -version`

21.0.2

### Quarkus version or git rev

3.14.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.9

**Comment by yrodiere** [comment]
Hello.

The Blaze Persistence extension for Quarkus is part of the Blaze Persistence repository: https://github.com/Blazebit/blaze-persistence/tree/634799cf2bc8ac8ab8193fbc972c8538988bb197/integration/quarkus

Also, judging from this stacktrace, the problem seems related to an incompatibility between Blaze Persistence and Hibernate ORM, rather than to Quarkus.

Please [report this to Blaze Persistence](https://github.com/Blazebit/blaze-persistence/issues) instead?

I'm sure @beikov will be interested to hear about it. @beikov , please let me know when I can close this issue on the Quarkus side.

**Comment by gsmet** [comment]
I think we can close this one as it has nothing to do with the Core repository.

I'll let @beikov address it and either handle the issue in an ORM release updated in the core repo or a Blaze release updated in the Platform.
