### ISSUE TITLE
Support to skip TLS verification when image is pushed for private HTTPS registries

### ISSUE THREAD

**Issue by cmoulliard** [quarkusio/quarkus#43486]
## Feature request

The command pushing the image build to a private registry (e.g. localhost:5000, gitea.cnoe.localtest.me:8443, etc) should allow to skip to verify the TLS certificate to avoid to get the following error 

```
[INFO] --- quarkus:3.14.4:image-push (default-cli) @ code-with-quarkus ---
[INFO] [io.quarkus.kubernetes.deployment.PropertyUtil] Kubernetes manifests are generated with 'The container port http' having default value '8080'. The app and manifests will get out of sync if the property 'quarkus.http.port' is changed at runtime.
[INFO] Testcontainers version: 1.20.1
[INFO] Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
[INFO] Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///var/run/docker.sock
[INFO] Docker host IP address is localhost
[INFO] Connected to docker: 
  Server Version: 5.0.3
  API Version: 1.41
  Operating System: fedora
  Total Memory: 5487 MB
[INFO] Image pull policy will be performed by: DefaultPullPolicy()
[INFO] Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
[INFO] Checking the system...
[INFO] ✔︎ Docker server version should be at least 1.6.0
[INFO] [io.quarkus.deployment.util.ExecUtil] Error response from daemon: {"errorDetail":{"message":"trying to reuse blob sha256:dd5e77a90e609b328f2e49aa60e50bd8837e505c157060c337725413ccf449f1 at destination: pinging container registry gitea.cnoe.localtest.me:8443: Get \"https://gitea.cnoe.localtest.me:8443/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority"},"error":"trying to reuse blob sha256:dd5e77a90e609b328f2e49aa60e50bd8837e505c157060c337725413ccf449f1 at destination: pinging container registry gitea.cnoe.localtest.me:8443: Get \"https://gitea.cnoe.localtest.me:8443/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.827 s
[INFO] Finished at: 2024-09-25T08:45:58+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.14.4:image-push (default-cli) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromJar threw an exception: java.lang.RuntimeException: Execution of 'docker push gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT' failed. See docker output for more details
[ERROR]         at io.quarkus.container.image.docker.common.deployment.CommonProcessor.containerRuntimeException(CommonProcessor.java:254)
[ERROR]         at io.quarkus.container.image.docker.common.deployment.CommonProcessor.pushImage(CommonProcessor.java:225)
```

using the following commands
```
podman machine start
export DOCKER_HOST="unix:///var/run/docker.sock"            
./mvnw install -Dquarkus.container-image.build=true \
   -Dquarkus.container-image.push=true \
   -Dquarkus.container-image.insecure=true \
   -Dquarkus.container-image.image=gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT

or

quarkus image push \
  --registry gitea.cnoe.localtest.me:8443 \
  --group giteaadmin \
  --name code-with-quarkus \
  --tag 1.0.0-SNAPSHOT
```

Of course, that works using:
```
podman build -f src/main/docker/Dockerfile.jvm -t gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT .
podman push gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT --tls-verify=0
```

**Remark**: We should also offer a new parameter to the CLI to allow to consume the image URL directky without having to pass registry, group, name and tag arguments
```
quarkus image push gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT
```

**Comment by geoand** [comment]
How would one do that if they were using just plain Docker or Podman? Does `--insecure-registry` work / suffice?

**Comment by cmoulliard** [comment]
> Does `--insecure-registry` work / suffice?

It could if we map such a parameter with the podman parameter which is `--tls-verify=false`

**Comment by cmoulliard** [comment]
> How would one do that if they were using just plain Docker or Podman?

We could if we allow the user to pass additional parameters/args to the command executed under the hood which is `docker or podman build`

**Comment by geoand** [comment]
My point is that I don't know how the invocation of the `docker` or `podman` binary would look. 
If you have example commands of how to push to an insecure registry with a flag one the command line, that would be great

**Comment by cmoulliard** [comment]
> If you have example commands of how to push to an insecure registry with a flag one the command line, that would be great

I provided the example on this ticket ;-) Here is again the example to be used
```
podman build -f src/main/docker/Dockerfile.jvm -t gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT .
podman push gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT --tls-verify=false
```

**Comment by geoand** [comment]
Does `--tls-verify=false` work for `docker` too?

**Comment by cmoulliard** [comment]
> Does `--tls-verify=false` work for `docker` too?

No as this parameter is specific to the podman client

**Comment by geoand** [comment]
@cmoulliard see https://github.com/quarkusio/quarkus/pull/43530

**Comment by cmoulliard** [comment]
I think that we should reopen the ticket or create another one as I did a test and we got an error as the `podman push` command executed is not correct

`threw an exception: java.lang.RuntimeException: Execution of '
podman push gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT push gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT --tls-verify=false' `

Full log
```
he command generated is correct. podman raises an error but we don't get it :-(

[INFO] --- quarkus:999-SNAPSHOT:build (default) @ code-with-quarkus ---
[INFO] [io.quarkus.kubernetes.deployment.PropertyUtil] Kubernetes manifests are generated with 'The container port http' having default value '8080'. The app and manifests will get out of sync if the property 'quarkus.http.port' is changed at runtime.
[INFO] Testcontainers version: 1.20.1
[INFO] Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
[INFO] Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///var/run/docker.sock
[INFO] Docker host IP address is localhost
[INFO] Connected to docker:
  Server Version: 5.0.3
  API Version: 1.41
  Operating System: fedora
  Total Memory: 5487 MB
[INFO] Image pull policy will be performed by: DefaultPullPolicy()
[INFO] Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
[INFO] Checking the system...
[INFO] ✔︎ Docker server version should be at least 1.6.0
[INFO] [io.quarkus.container.image.docker.common.deployment.CommonProcessor] Starting (local) container image build for jar using podman
[INFO] [io.quarkus.container.image.docker.common.deployment.CommonProcessor] Executing the following command to build image: 'podman build -f /Users/cmoullia/code/ch007m/code-with-quarkus/src/main/docker/Dockerfile.jvm -t gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT /Users/cmoullia/code/ch007m/code-with-quarkus'
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 1/11: FROM registry.access.redhat.com/ubi8/openjdk-21:1.20
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 2/11: ENV LANGUAGE='en_US:en'
[INFO] [io.quarkus.deployment.util.ExecUtil] --> Using cache ca2159888a32ae5296ed307e4653b8c159e95a8b0475c1a2184b544cdcd73ce2
[INFO] [io.quarkus.deployment.util.ExecUtil] --> ca2159888a32
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 3/11: COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
[INFO] [io.quarkus.deployment.util.ExecUtil] --> Using cache 2e71961ccf2a408ade98c1fe558ae0409e32c1855a2acf92342e998b97bdcc74
[INFO] [io.quarkus.deployment.util.ExecUtil] --> 2e71961ccf2a
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 4/11: COPY --chown=185 target/quarkus-app/*.jar /deployments/
[INFO] [io.quarkus.deployment.util.ExecUtil] --> 533f661dd20a
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 5/11: COPY --chown=185 target/quarkus-app/app/ /deployments/app/
[INFO] [io.quarkus.deployment.util.ExecUtil] --> b0879e5ed067
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 6/11: COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/
[INFO] [io.quarkus.deployment.util.ExecUtil] --> 2e23ce021d09
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 7/11: EXPOSE 8080
[INFO] [io.quarkus.deployment.util.ExecUtil] --> c17bfcd2d1da
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 8/11: USER 185
[INFO] [io.quarkus.deployment.util.ExecUtil] --> 04e5dcbfb8b9
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 9/11: ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
[INFO] [io.quarkus.deployment.util.ExecUtil] --> 6c9934b876c1
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 10/11: ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
[INFO] [io.quarkus.deployment.util.ExecUtil] --> b45b37d83eae
[INFO] [io.quarkus.deployment.util.ExecUtil] STEP 11/11: ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
[INFO] [io.quarkus.deployment.util.ExecUtil] COMMIT gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT
[INFO] [io.quarkus.deployment.util.ExecUtil] --> d9ed5194507d
[INFO] [io.quarkus.deployment.util.ExecUtil] Successfully tagged gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT
[INFO] [io.quarkus.deployment.util.ExecUtil] d9ed5194507d1a8a88f83b4f6e1a9fe42c1e87b26f8d2bab15be11cf83c5c7fb
[INFO] [io.quarkus.deployment.util.ExecUtil] Error: accepts between 1 and 2 arg(s), received 3
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.923 s
[INFO] Finished at: 2024-09-27T10:19:17+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.container.image.podman.deployment.PodmanProcessor#podmanBuildFromJar threw an exception: java.lang.RuntimeException: Execution of 'podman push gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT push gitea.cnoe.localtest.me:8443/giteaadmin/code-with-quarkus:1.0.0-SNAPSHOT --tls-verify=false' failed. See podman output for more details
[ERROR]         at io.quarkus.container.image.docker.common.deployment.CommonProcessor.containerRuntimeException(CommonProcessor.java:261)
[ERROR]         at io.quarkus.container.image.docker.common.deployment.CommonProcessor.pushImage(CommonProcessor.java:228)
[ERROR]         at io.quarkus.container.image.docker.common.deployment.CommonProcessor.pushImages(CommonProcessor.java:219)
[ERROR]         at io.quarkus.container.image.podman.deployment.PodmanProcessor.createContainerImage(PodmanProcessor.java:124)
[ERROR]         at io.quarkus.container.image.podman.deployment.PodmanProcessor.createContainerImage(PodmanProcessor.java:32)
[ERROR]         at io.quarkus.container.image.docker.common.deployment.CommonProcessor.buildFromJar(CommonProcessor.java:87)
[ERROR]         at io.quarkus.container.image.podman.deployment.PodmanProcessor.podmanBuildFromJar(PodmanProcessor.java:62)
[ERROR]         at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:1583)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:483)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by geoand** [comment]
Let's just create a PR fixing it, no need to go through additional ceremony

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/43558
