### ISSUE TITLE
unclear error message ' is in unnamed module of loader 'app' when missing public modifier

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#43600]
### Describe the bug

when class or at least recrod referenced from restclient are not public classes one get a error message like:

```
java.lang.reflect.UndeclaredThrowableException
        at jdk.proxy2/jdk.proxy2.$Proxy22.getSchedules(Unknown Source)
        at cfpdev2ics.run(cfpdev2ics.java:34)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.restclient.runtime.QuarkusProxyInvocationHandler.invoke(QuarkusProxyInvocationHandler.java:165)
        ... 16 more
Caused by: java.lang.IllegalAccessError: failed to access class cfpdev2ics$ScheduleLinks from class jdk.proxy2.$Proxy19 (cfpdev2ics$ScheduleLinks is in unnamed module of loader 'app'; jdk.proxy2.$Proxy19 is in module jdk.proxy2 of loader 'app')
        at jdk.proxy2/jdk.proxy2.$Proxy19.getSchedules(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 18 more     
```

### Expected behavior

tell user it is missing public or something more clearer than "is in unamed module"

### Actual behavior

code like this:

```
///usr/bin/env jbang "$0" "$@" ; exit $?


//JAVA 17+
// Update the Quarkus version to what you want here or run jbang with
// `-Dquarkus.version=<version>` to override it.
//DEPS io.quarkus:quarkus-bom:${quarkus.version:3.7.2}@pom
//DEPS io.quarkus:quarkus-rest-client
//DEPS io.quarkus:quarkus-rest-client-jackson
//DEPS io.quarkus:quarkus-picocli
//Q:CONFIG quarkus.banner.enabled=false
//Q:CONFIG quarkus.log.level=WARN
//Q:CONFIG quarkus.rest-client.devoxxcfp.url=https://dvbe24.cfp.dev
import java.util.List;

import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;
import org.eclipse.microprofile.rest.client.inject.RestClient;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import picocli.CommandLine;

// https://dvbe24.cfp.dev/swagger-ui/index.html

@CommandLine.Command
public class cfpdev2ics implements Runnable {

    @RestClient
    DevoxxCfp devoxxCfp;    
    
    @Override
    public void run() {

        devoxxCfp.getSchedules().links().forEach(System.out::println);
    }

    @Path("/api")
@RegisterRestClient(configKey = "devoxxcfp")
 public interface DevoxxCfp {

    @GET()
    @Path("/public/schedules")
    ScheduleLinks getSchedules();
}


  static record ScheduleLinks(List<ScheduleLink> links) {}
  static record ScheduleLink(String href, String title) {}

}

```

fails but change that static record to `public static record` it works.

makes sense but the error message is not helping location that is the problem.

**Comment by maxandersen** [comment]
just noticed i was using way too old quarkus. sorry for the noise.
