### ISSUE TITLE
Keycloak container insufficient memory in our -rhel8-jdk17-baremetal-ts-jvm-podman-nightly  jenkin job for HttpAdvancedIT test

### ISSUE THREAD

**Issue by jcarranzan** [quarkusio/quarkus#43630]
### Describe the bug

Some days ago in our jenkins-job CI `quarkus-main-rhel8-jdk17-baremetal-ts-jvm-podman-nightly` we have observed these failures in our jenkins jobs in this specific test https://github.com/quarkus-qe/quarkus-test-suite/blob/main/http/http-advanced/src/test/java/io/quarkus/ts/http/advanced/HttpAdvancedIT.java that use this Keycloak image container:` quay.io/keycloak/keycloak:25.0`
```
03:31:11 [INFO] Running io.quarkus.ts.http.advanced.HttpAdvancedIT
03:31:12 01:31:12,230 INFO  ⭐  PKCS12 keystore and truststore generated successfully!
03:31:12 01:31:12,231 INFO  🔐  Key Store File: /tmp/quarkus-qe-certs11648231087839990117/quarkus-qe-keystore.p12
03:31:12 01:31:12,231 INFO  🔓  Trust Store File: /tmp/quarkus-qe-certs11648231087839990117/quarkus-qe-truststore.p12
03:31:12 01:31:12,271 INFO  [keycloak] Initialize service (quay.io/keycloak/keycloak:25.0)
03:31:12 01:31:12,295 Image pull policy will be performed by: DefaultPullPolicy()
03:31:12 01:31:12,297 Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
03:31:12 01:31:12,309 Testcontainers version: 1.20.1
03:31:12 01:31:12,865 Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///run/user/600/podman/podman.sock
03:31:12 01:31:12,866 Docker host IP address is localhost
03:31:12 01:31:12,911 Connected to docker: 
03:31:12   Server Version: 4.9.4-rhel
03:31:12   API Version: 1.41
03:31:12   Operating System: rhel
03:31:12   Total Memory: 7695 MB
03:31:12 01:31:12,931 Pulling docker image: testcontainers/ryuk:0.8.1. Please be patient; this may take some time but only needs to be done once.
03:31:13 01:31:13,159 Starting to pull image
03:31:13 01:31:13,187 Pulling image layers:  2 pending,  1 downloaded,  0 extracted, (0 bytes/? MB)
03:31:13 01:31:13,228 Pulling image layers:  1 pending,  2 downloaded,  0 extracted, (0 bytes/? MB)
03:31:13 01:31:13,437 Pulling image layers:  0 pending,  3 downloaded,  0 extracted, (0 bytes/0 bytes)
03:31:13 01:31:13,440 Pulling image layers:  0 pending,  4 downloaded,  0 extracted, (0 bytes/0 bytes)
03:31:13 01:31:13,445 Pulling image layers:  0 pending,  4 downloaded,  0 extracted, (0 bytes/0 bytes)
03:31:13 01:31:13,446 Image testcontainers/ryuk:0.8.1 pull took PT0.515026139S
03:31:13 01:31:13,463 Creating container for image: testcontainers/ryuk:0.8.1
03:31:13 01:31:13,511 Container testcontainers/ryuk:0.8.1 is starting: 2ab279a2dd2ec6cebf0769110d2be287ba53258260a0bd2d13770dafa9b26d39
03:31:13 01:31:13,873 Container testcontainers/ryuk:0.8.1 started in PT0.409386568S
03:31:13 01:31:13,875 Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
03:31:13 01:31:13,876 Checking the system...
03:31:13 01:31:13,876 ✔︎ Docker server version should be at least 1.6.0
03:31:13 01:31:13,878 Pulling docker image: quay.io/keycloak/keycloak:25.0. Please be patient; this may take some time but only needs to be done once.
03:31:14 01:31:14,417 Starting to pull image
03:31:14 01:31:14,424 Pulling image layers:  0 pending,  1 downloaded,  0 extracted, (0 bytes/0 bytes)
03:31:14 01:31:14,933 Pulling image layers:  2 pending,  2 downloaded,  0 extracted, (0 bytes/? MB)
03:31:15 01:31:15,947 Pulling image layers:  1 pending,  3 downloaded,  0 extracted, (137 MB/? MB)
03:31:18 01:31:18,591 Pulling image layers:  0 pending,  4 downloaded,  0 extracted, (137 MB/217 MB)
03:31:18 01:31:18,593 Pulling image layers:  0 pending,  5 downloaded,  0 extracted, (137 MB/217 MB)
03:31:18 01:31:18,615 Pulling image layers:  0 pending,  5 downloaded,  0 extracted, (137 MB/217 MB)
03:31:18 01:31:18,615 Pull complete. 5 layers, pulled in 4s (downloaded 137 MB at 34 MB/s)
03:31:18 01:31:18,615 Image quay.io/keycloak/keycloak:25.0 pull took PT4.73656389S
03:31:18 01:31:18,620 Creating container for image: quay.io/keycloak/keycloak:25.0
03:31:18 01:31:18,737 Container quay.io/keycloak/keycloak:25.0 is starting: 89e8405a27e8a395d749c589ffdb970b0a5b66514f78e533853aee49ba7b2eba
03:36:19 01:36:19,075 Could not start container: java.lang.IllegalStateException: Wait strategy failed. Container exited with code 1
03:36:19 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:533)
03:36:19 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:354)
03:36:19 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
03:36:19 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:344)
03:36:19 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
03:36:19 	at io.quarkus.test.services.containers.DockerContainerManagedResource.doStart(DockerContainerManagedResource.java:122)
03:36:19 	at io.quarkus.test.services.containers.DockerContainerManagedResource.start(DockerContainerManagedResource.java:72)
03:36:19 	at io.quarkus.test.bootstrap.BaseService.doStart(BaseService.java:356)
03:36:19 	at io.quarkus.test.bootstrap.BaseService.start(BaseService.java:245)
03:36:19 	at io.quarkus.test.bootstrap.QuarkusScenarioBootstrap.launchService(QuarkusScenarioBootstrap.java:172)
03:36:19 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
03:36:19 	at io.quarkus.test.bootstrap.QuarkusScenarioBootstrap.beforeAll(QuarkusScenarioBootstrap.java:73)
03:36:19 	at io.quarkus.test.bootstrap.QuarkusScenarioBootstrap.beforeAll(QuarkusScenarioBootstrap.java:50)
03:36:19 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:396)
03:36:19 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
03:36:19 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:396)
03:36:19 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:212)
03:36:19 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:85)
03:36:19 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
03:36:19 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
03:36:19 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
03:36:19 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
03:36:19 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
03:36:19 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
03:36:19 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
03:36:19 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
03:36:19 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
03:36:19 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
03:36:19 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
03:36:19 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
03:36:19 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
03:36:19 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
03:36:19 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
03:36:19 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
03:36:19 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
03:36:19 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
03:36:19 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
03:36:19 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
03:36:19 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
03:36:19 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
03:36:19 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
03:36:19 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
03:36:19 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
03:36:19 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
03:36:19 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
03:36:19 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
03:36:19 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
03:36:19 	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
03:36:19 	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
03:36:19 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
03:36:19 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
03:36:19 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
03:36:19 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
03:36:19 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
03:36:19 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
03:36:19 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
03:36:19 Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*started in.*\s'
03:36:19 	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)
03:36:19 	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
03:36:19 	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)
03:36:19 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:500)
03:36:19 	... 55 more
03:36:19 
03:36:19 01:36:19,101 Log output from the failed container:
03:36:19 OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000006af400000, 4034920448, 0) failed; error='Not enough space' (errno=12)
03:36:19 #
03:36:19 # There is insufficient memory for the Java Runtime Environment to continue.
03:36:19 # Native memory allocation (mmap) failed to map 4034920448 bytes. Error detail: committing reserved memory.
03:36:19 # An error report file with more information is saved as:
03:36:19 # /tmp/hs_err_pid84.log
03:36:19 
03:36:20 [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 308.6 s <<< FAILURE! -- in io.quarkus.ts.http.advanced.HttpAdvancedIT
03:36:20 [ERROR] io.quarkus.ts.http.advanced.HttpAdvancedIT -- Time elapsed: 308.6 s <<< ERROR!
```

### Expected behavior

Test pass successfully

### Actual behavior

` Log output from the failed container:
03:36:19 OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000006af400000, 4034920448, 0) failed; error='Not enough space' (errno=12)
03:36:19 #
03:36:19 # There is insufficient memory for the Java Runtime Environment to continue.
03:36:19 # Native memory allocation (mmap) failed to map 4034920448 bytes. Error detail: committing reserved memory.`

### How to Reproduce?

It's related to this other issue:
https://github.com/quarkusio/quarkus/issues/41813

**Comment by mabartos** [comment]
This PR for the test framework should close this issue: https://github.com/quarkus-qe/quarkus-test-framework/pull/1351

cc @jcarranzan

**Comment by geoand** [comment]
Thanks @mabartos.

Closing this as it is not a Quarkus issue

**Comment by michalvavrik** [comment]
> Closing this as it is not a Quarkus issue

I can see Quarkus issue @geoand, though it is most likely not clear from issue description. I am really grateful for the Docker fix @mabartos provided, but https://github.com/quarkusio/quarkus/pull/43601 does not work for Podman. So we have Docker-specific memory fix but I believe Quarkus cares a lot about Podman. Either @jcarranzan is wrong and `withMemory` works on Podman, or there should be Podman specific workaround put in place, like limiting `JAVA_OPTS_KC_HEAP`. @jcarranzan please consider opening dedicated issue that describes what is wrong for Keycloak Dev Services memory management when used with Podman. Thanks

**Comment by mabartos** [comment]
JFYI - more discussion continues here: https://github.com/quarkus-qe/quarkus-test-suite/issues/2106

**Comment by michalvavrik** [comment]
Yeah, I read it, I am very grateful for all your comments @mabartos . I left comment here mostly to suggest @jcarranzan that he should open Quarkus issue for Keycloak Dev Services (if I read situation right, I'll leave it for me to reproduce and decide).
