### ISSUE TITLE
EmbeddedId broken in Hibernate Reactive

### ISSUE THREAD

**Issue by danielbobbert** [quarkusio/quarkus#43651]
### Describe the bug

Wenn using Hibernate Reactive with \@Embeddable and \@EmbeddedId, entities can no longer be loaded because of the new (incubating) "ReactiveInitializer" API.

### Expected behavior

Existing entities should be loaded from database without problems.

### Actual behavior

 java.lang.ClassCastException: class org.hibernate.sql.results.graph.embeddable.internal.EmbeddableInitializerImpl cannot be cast to class org.hibernate.reactive.sql.results.graph.ReactiveInitializer (org.hibernate.sql.results.graph.embeddable.internal.EmbeddableInitializerImpl and org.hibernate.reactive.sql.results.graph.ReactiveInitializer are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader \@10d18696)
                at org.hibernate.reactive.sql.results.graph.entity.internal.ReactiveEntityInitializerImpl.initializeId(ReactiveEntityInitializerImpl.java:748)
                at org.hibernate.reactive.sql.results.graph.entity.internal.ReactiveEntityInitializerImpl.reactiveResolveKey(ReactiveEntityInitializerImpl.java:625)
                at org.hibernate.reactive.sql.results.graph.entity.internal.ReactiveEntityInitializerImpl.reactiveResolveKey(ReactiveEntityInitializerImpl.java:605)
                at org.hibernate.reactive.sql.results.graph.entity.internal.ReactiveEntityInitializerImpl.reactiveResolveKey(ReactiveEntityInitializerImpl.java:56)
                at org.hibernate.reactive.sql.results.internal.ReactiveStandardRowReader.resolveKey(ReactiveStandardRowReader.java:383)

### How to Reproduce?

See attached reproducer project.
The application contains an Entity which uses an embeddable ID.

The test creates two entities (which works fine), but then fails to load those entities with the aforementioned exception.
The root cause seems to be some confusion between "ReactiveInitializer", "EmbeddableInitializerImpl" and "ReactiveEmbeddableInitializerImpl".

The same code works with Quarkus 3.13.1 (just change the version in pom.xml to verify). It is broken since Quarkus 3.14 (and still broken in 3.15.1)

### Output of `java -version`

21

### Quarkus version or git rev

3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

### Additional information

[embedded-id-bug.zip](https://github.com/user-attachments/files/17228581/embedded-id-bug.zip)

**Comment by DavideD** [comment]
This issue should be fixed in Hibernate Reactive 2.4.1.Final that [will be included in Quarkus 2.16](https://github.com/quarkusio/quarkus/pull/43348) and probably 2.15.2.
The original issue for Hibernate Reactive is https://github.com/hibernate/hibernate-reactive/issues/1979

**Comment by danielbobbert** [comment]
Sounds great! Yes please, include that in 3.15.x
We are currently migrating a whole bunch of services from 3.8.6 to 3.15 and this bug is a show stopper for some of our services.
