### ISSUE TITLE
Gradle fails to build native executable

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#43661]
### Describe the bug

Native compilation of apps generated from https://code.quarkus.io fail to compile in native mode

### Expected behavior

Build should succeed

### Actual behavior

Build fails with:

```
Caused by: org.gradle.api.GradleException: Outputting both native and JAR packages is not currently supported
        at io.quarkus.gradle.tasks.QuarkusBuild.nativeAndJar(QuarkusBuild.java:377)
        at io.quarkus.gradle.tasks.QuarkusBuild.getBuildInputFiles(QuarkusBuild.java:170)
        at io.quarkus.gradle.tasks.QuarkusBuild_Decorated.getBuildInputFiles(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.internal.reflect.annotations.impl.DefaultPropertyAnnotationMetadata.getPropertyValue(DefaultPropertyAnnotationMetadata.java:97)
        at org.gradle.internal.properties.annotations.DefaultTypeMetadataStore$DefaultPropertyMetadata.getPropertyValue(DefaultTypeMetadataStore.java:284)
        at org.gradle.internal.properties.bean.DefaultPropertyWalker$1.lambda$visitLeaf$0(DefaultPropertyWalker.java:90)
        at org.gradle.internal.deprecation.DeprecationLogger.whileDisabled(DeprecationLogger.java:259)
        at org.gradle.internal.properties.bean.DefaultPropertyWalker$CachedPropertyValue.lambda$new$0(DefaultPropertyWalker.java:107)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
        at org.gradle.internal.properties.bean.DefaultPropertyWalker$CachedPropertyValue.call(DefaultPropertyWalker.java:149)
        at org.gradle.util.internal.GUtil.uncheckedCall(GUtil.java:437)
        at org.gradle.util.internal.DeferredUtil.unpackNestableDeferred(DeferredUtil.java:83)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:90)
        at org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection.visitChildren(DefaultFileCollectionFactory.java:285)
        at org.gradle.api.internal.file.CompositeFileCollection.visitDependencies(CompositeFileCollection.java:102)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:103)
        at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
        ... 143 more
```

### How to Reproduce?

```
quarkus create app --gradle
./gradlew build -Dquarkus.native.enabled=true --stacktrace
```

### Output of `java -version`

21.0.4+7-LTS

### Quarkus version or git rev

3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.7

**Comment by geoand** [comment]
cc @alou

**Comment by aloubyansky** [comment]
Yeah, I saw that. When native is enabled, the jvm binary (fast jar by default) isn't disabled. So Maven builds both but the Gradle plugin doesn't support that, so `quarkus.package.jar.enabled` should be set to `false`.
It's not a recent issue.

**Comment by aloubyansky** [comment]
Not exactly sure, but possibly since https://github.com/quarkusio/quarkus/commit/095feab7314beef55520d4e5087daf053755260e

**Comment by mschorsch** [comment]
See also https://github.com/quarkusio/quarkus/discussions/40679#discussioncomment-9457734

**Comment by zakkak** [comment]
@gsmet in https://github.com/quarkusio/quarkus/issues/45073#issuecomment-2548105876

> Yeah, we have an issue. Either with the README or with the code. And I think expecting people to use -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false to enable native is a bit too much.
> 
> The problem is due to these lines: https://github.com/quarkusio/quarkus/blob/main/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java#L104-L106 .
> 
> From what I can see, we are not enforcing this in the Maven plugin. I think we had to at some point but maybe we relaxed things there and forgot to do it in the Gradle plugin?
> 
> @dmlloyd AFAICS, you added this check, is it still needed? (we are not setting `quarkus.package.jar.enabled` to false in the Maven projects AFAICS).
> 
> Note that when using the CLI, we are passing `-Dquarkus.package.jar.enabled=false` to the Gradle runner.

@dmlloyd in https://github.com/quarkusio/quarkus/issues/45073#issuecomment-2548429964

> The check is still needed because our Gradle integration only knows how to build one thing at a time. I couldn't figure out any way to tell it to build two things.

**Comment by Karm** [comment]
This is still an ongoing issue with what I downloaded as the latest Quarkus 3.19.2 from code.quarkus.

```
C:\tmp\code-with-quarkus
λ cat README.md

<SNIP>

## Creating a native executable

You can create a native executable using:

```shell script
./gradlew build -Dquarkus.native.enabled=true
```

```
C:\tmp\code-with-quarkus
λ gradlew build -Dquarkus.native.enabled=true

[Incubating] Problems report is available at: file:///C:/tmp/code-with-quarkus/build/reports/problems/problems-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':quarkusBuild'.
> Outputting both native and JAR packages is not currently supported

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.12/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 2s
```

**Comment by holly-cummins** [comment]
Stating the obvious, it would be nice to get this fixed. :)
