### ISSUE TITLE
RequestParam Map<String, String> not supported by quarkus-spring

### ISSUE THREAD

**Issue by zhangjiangqige** [quarkusio/quarkus#43705]
### Description

Spring has this behavior that's not supported by quarkus-spring https://docs.spring.io/spring-framework/docs/5.3.x/reference/html/web.html#mvc-ann-requestparam

> When an @RequestParam annotation is declared as a Map<String, String> or MultiValueMap<String, String>, without a parameter name specified in the annotation, then the map is populated with the request parameter values for each given parameter name.

This behavior is useful because in complex code base it makes it much simpler to add new parameters to the endpoint when the endpoint is defined in an interface and is implemented by different classes in different packages.

Example Spring code like this breaks when built with Quarkus

```
@RestController
@RequestMapping("/unbuildable")
public class UnbuildableController {
    @PostMapping("/hello")
    public String hello(@RequestParam(required = false) Map<String, String> params) {
        return params.toString();
    }
}
```

error during build:

```
Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.15.1:build (default) on project spring-web-quickstart: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Failed to process method 'org.acme.spring.web.UnbuildableController#hello'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:333)
	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:658)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.lang.RuntimeException: Failed to process method 'org.acme.spring.web.UnbuildableController#hello'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:781)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:422)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:300)
	... 10 more
Caused by: java.lang.RuntimeException: Could not create converter for java.util.Map for method java.lang.String hello(java.util.Map<java.lang.String, java.lang.String> params) on class org.acme.spring.web.UnbuildableController of type QUERY
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:474)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:101)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.extractParameterInfo(EndpointIndexer.java:1391)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:599)
	... 12 more
Caused by: java.lang.RuntimeException: Failed to find converter for java.util.Map
	at org.jboss.resteasy.reactive.server.processor.generation.converters.GeneratedConverterIndexerExtension.extractConverterImpl(GeneratedConverterIndexerExtension.java:106)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.extractConverter(ServerEndpointIndexer.java:680)
	at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:470)
	... 15 more
```

**Comment by zhangjiangqige** [comment]
Hi @mcruzdev , sure, the reproducer can be found here https://github.com/zhangjiangqige/quarkus-spring-mapstrstr-repro/tree/main

The dependencies are `spring-web,rest-jackson`. In fact it's created from the guide in https://quarkus.io/guides/spring-web , and I just added one java class to the generated project

**Comment by geoand** [comment]
Hey folks,

I won't be around next week, so if you want to proceed with a draft of a possible solution, feel free to do so, just be aware that it will take me a while until I can review it

**Comment by geoand** [comment]
🙏

**Comment by cescoffier** [comment]
It makes sense to add this behavior for non-spring api too, but we need to carefully describe it.

Typically, what would be included? Path parameters? Form? Query? For headers, the signature is not ideal (it should be a Map<String, List<String>). Even for some type of parameters it might be better to use a multimap.

**Comment by aureamunoz** [comment]
cc @aureamunoz

**Comment by mcruzdev** [comment]
Hi @aureamunoz do you think to solve this one? I would like to solve it :)

**Comment by aureamunoz** [comment]
Yes! Let me look at it next week
<https://www.redhat.com>
