### ISSUE TITLE
Kafka snappy conversion fails on native aarch64 for missing native library

### ISSUE THREAD

**Issue by mocenas** [quarkusio/quarkus#43801]
### Describe the bug

When using quarkus-messaging-kafka, with snappy enabled (`quarkus.kafka.snappy.enabled=true`), it fails to start on native on architecture aarch64, with exception
```
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.RuntimeException: no native library is found for os.name=Linux and os.arch=aarch64
	at io.quarkus.kafka.client.runtime.SnappyRecorder.getLibraryFile(SnappyRecorder.java:45)
	at io.quarkus.kafka.client.runtime.SnappyRecorder.loadSnappy(SnappyRecorder.java:26)
	at io.quarkus.deployment.steps.KafkaProcessor$loadSnappyIfEnabled133026306.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.KafkaProcessor$loadSnappyIfEnabled133026306.deploy(Unknown Source)
```

**Comment by zakkak** [comment]
@cescoffier if I get this right https://github.com/quarkusio/quarkus/pull/40304 is only meant for JVM mode, so restricting it to JVM-mode and applying something like https://github.com/quarkusio/quarkus/pull/43782 in native-mode wouldn't break it, right?

**Comment by cescoffier** [comment]
Yes.

We started receiving more demands to include native libraries for other os/arch (not only the host one). I will start a discussion on Monday as we need to discuss how we can handle that and the consequences on native compilation.
