### ISSUE TITLE
RabbitMQClientImpl [Error Occurred After Shutdown]: java.lang.NullPointerException

### ISSUE THREAD

**Issue by elmodeer** [quarkusio/quarkus#43877]
### Describe the bug

After adding the rabbitmq dependency according to this [guide](https://quarkus.io/guides/rabbitmq-reference).

I started getting this error at the end of the test suite run. It doesn't fail the tests, but I want to understand why is it happening.

```
2024-10-15 09:07:05,861 INFO  [io.ver.rab.imp.RabbitMQClientImpl] (Test worker) Stopping rabbitmq client
2024-10-15 09:07:05,861 INFO  [io.ver.rab.imp.RabbitMQClientImpl] (Test worker) Stopping rabbitmq client
2024-10-15 09:07:05,863 INFO  [io.ver.rab.imp.RabbitMQClientImpl] (pool-72-thread-4) Stopping rabbitmq client
2024-10-15 09:07:05,864 INFO  [io.ver.rab.imp.RabbitMQClientImpl] (vert.x-eventloop-thread-8) Starting rabbitmq client
2024-10-15 09:07:05,871 ERROR [io.ver.rab.imp.RabbitMQClientImpl] (executor-thread-2) Exception whilst running connection stablished callback:  [Error Occurred After Shutdown]: java.lang.NullPointerException: Cannot invoke "io.smallrye.context.SmallRyeContextManager.defaultThreadContext()" because the return value of "io.smallrye.context.SmallRyeContextManagerProvider.getManager()" is null
	at io.smallrye.context.SmallRyeThreadContext.getCurrentThreadContextOrDefaultContexts(SmallRyeThreadContext.java:160)
	at io.smallrye.mutiny.context.DefaultContextPropagationInterceptor.getThreadContext(DefaultContextPropagationInterceptor.java:12)
	at io.smallrye.mutiny.context.BaseContextPropagationInterceptor.decorate(BaseContextPropagationInterceptor.java:24)
	at io.smallrye.mutiny.infrastructure.Infrastructure.decorate(Infrastructure.java:149)
	at io.smallrye.mutiny.groups.UniOnItem.call(UniOnItem.java:97)
	at io.smallrye.mutiny.Uni.call(Uni.java:434)
	at io.smallrye.reactive.messaging.rabbitmq.internals.IncomingRabbitMQChannel.lambda$createConsumer$5(IncomingRabbitMQChannel.java:128)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.connectCallbackHandler(RabbitMQClientImpl.java:867)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.connect(RabbitMQClientImpl.java:852)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$tryConnect$36(RabbitMQClientImpl.java:763)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

2024-10-15 09:07:05,872 INFO  [io.quarkus] (Test worker) insights-central-api stopped in 0.094s
UserServiceTest > testApiClientExceptions() PASSED
Exception whilst running connection stablished callback:  [Error Occurred After Shutdown]
java.lang.NullPointerException: Cannot invoke "io.smallrye.context.SmallRyeContextManager.defaultThreadContext()" because the return value of "io.smallrye.context.SmallRyeContextManagerProvider.getManager()" is null
	at io.smallrye.context.SmallRyeThreadContext.getCurrentThreadContextOrDefaultContexts(SmallRyeThreadContext.java:160)
	at io.smallrye.mutiny.context.DefaultContextPropagationInterceptor.getThreadContext(DefaultContextPropagationInterceptor.java:12)
	at io.smallrye.mutiny.context.BaseContextPropagationInterceptor.decorate(BaseContextPropagationInterceptor.java:24)
	at io.smallrye.mutiny.infrastructure.Infrastructure.decorate(Infrastructure.java:149)
	at io.smallrye.mutiny.groups.UniOnItem.call(UniOnItem.java:97)
	at io.smallrye.mutiny.Uni.call(Uni.java:434)
	at io.smallrye.reactive.messaging.rabbitmq.internals.IncomingRabbitMQChannel.lambda$createConsumer$5(IncomingRabbitMQChannel.java:128)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.connectCallbackHandler(RabbitMQClientImpl.java:867)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.connect(RabbitMQClientImpl.java:852)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$tryConnect$36(RabbitMQClientImpl.java:763)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Expected behavior

no error.

### How to Reproduce?

N/A

### Output of `uname -a` or `ver`

Darwin MacBook-Pro 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 OpenJDK Runtime Environment (build 21.0.1+12-29) OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)

### Quarkus version or git rev

3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.10.2!

**Comment by elmodeer** [comment]
@geoand Could you please have a look at this issue?

**Comment by geoand** [comment]
I have never done in work with RabbitMQ and Quarkus, but this seems harmless to me - that said we should certainly make sure the shutdown sequence doesn't result in this error

**Comment by cescoffier** [comment]
That sounds like a shutdown ordering issue.

@ozangunalp did you know about this one?

**Comment by cescoffier** [comment]
Actually, we may be able to handle it in Mutiny CP SPI (CC @jponge)

**Comment by ozangunalp** [comment]
There is something odd with the shutdown of RabbitMQ channels. It tries to reconnect whereas shutdown hooks have already been executed (so context manager has been released).

**Comment by elmodeer** [comment]
@ozangunalp do you have any updates on this ?

**Comment by ozangunalp** [comment]
Yes, this was due to a bug and a regression upstream. 

On shutdown, RabbitMQ consumers were not properly closed and it did not wait for the client close action to terminate. Because of that after the Context propagation extension disposes of the contextprovider, the consumers still try to reconnect.

This is fixed upstream in https://github.com/smallrye/smallrye-reactive-messaging/pull/2825

**Comment by elmodeer** [comment]
> Yes, this was due to a bug and a regression upstream.
> 
> On shutdown, RabbitMQ consumers were not properly closed and it did not wait for the client close action to terminate. Because of that after the Context propagation extension disposes of the contextprovider, the consumers still try to reconnect.
> 
> This is fixed upstream in [smallrye/smallrye-reactive-messaging#2825](https://github.com/smallrye/smallrye-reactive-messaging/pull/2825)

thank you very much.
