### ISSUE TITLE
NPE in Qute on hot-reload (with generated templates)

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#43944]
### Describe the bug

```
java.lang.NullPointerException: Cannot invoke "io.quarkus.qute.Template.instance()" because the return value of "io.quarkus.qute.i18n.MessageBundles.getTemplate(String)" is null
    at io.quarkiverse.roq.frontmatter.runtime.RoqFrontMatterMessages_Bundle.pageNumber(Unknown Source)
    at io.quarkiverse.roq.frontmatter.runtime.RoqFrontMatterMessages_Bundle$$function$$2.accept(Unknown Source)
    at io.quarkus.qute.CompletedStage.whenComplete(CompletedStage.java:285)
    at io.quarkiverse.roq.frontmatter.runtime.RoqFrontMatterMessages_Bundle.RoqFrontMatterMessages_Bundle_resolve_0(Unknown Source)
    at io.quarkiverse.roq.frontmatter.runtime.RoqFrontMatterMessages_Bundle.resolve(Unknown Source)
    at io.quarkus.qute.i18n.MessageBundles$1.resolve(MessageBundles.java:103)
    at io.quarkus.qute.EvaluatorImpl.evaluate(EvaluatorImpl.java:77)
    at io.quarkus.qute.ResolutionContextImpl$ChildResolutionContext.evaluate(ResolutionContextImpl.java:92)
    at io.quarkus.qute.ExpressionNode.resolve(ExpressionNode.java:36)
    at io.quarkus.qute.Results.resolveWith(Results.java:107)
    at io.quarkus.qute.Results.resolveAndProcess(Results.java:57)
    at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:238)
    at io.quarkus.qute.IfSectionHelper$SingletonContext.lambda$resolve$0(IfSectionHelper.java:68)
    at io.quarkus.qute.CompletedStage.thenCompose(CompletedStage.java:249)
    at io.quarkus.qute.IfSectionHelper$SingletonContext.resolve(IfSectionHelper.java:64)
    at io.quarkus.qute.IfSectionHelper.resolve(IfSectionHelper.java:45)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
    at io.quarkus.qute.Results.resolveWith(Results.java:110)
    at io.quarkus.qute.Results.resolveAndProcess(Results.java:57)
    at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:238)
    at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:66)
    at io.quarkus.qute.Parser$1.resolve(Parser.java:1331)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.IncludeSectionHelper.resolve(IncludeSectionHelper.java:50)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
    at io.quarkus.qute.Results.resolveWith(Results.java:110)
    at io.quarkus.qute.Results.resolveAndProcess(Results.java:57)
    at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:238)
    at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:66)
    at io.quarkus.qute.Parser$1.resolve(Parser.java:1331)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.IncludeSectionHelper.resolve(IncludeSectionHelper.java:50)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
    at io.quarkus.qute.Results.resolveWith(Results.java:110)
    at io.quarkus.qute.Results.resolveAndProcess(Results.java:57)
    at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:238)
    at io.quarkus.qute.InsertSectionHelper.resolve(InsertSectionHelper.java:28)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
    at io.quarkus.qute.Results.resolveWith(Results.java:110)
    at io.quarkus.qute.Results.resolveAndProcess(Results.java:57)
    at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:238)
    at io.quarkus.qute.InsertSectionHelper.resolve(InsertSectionHelper.java:28)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
    at io.quarkus.qute.Results.resolveWith(Results.java:110)
    at io.quarkus.qute.Results.resolveAndProcess(Results.java:57)
    at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:238)
    at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:66)
    at io.quarkus.qute.Parser$1.resolve(Parser.java:1331)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.IncludeSectionHelper.resolve(IncludeSectionHelper.java:50)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
    at io.quarkus.qute.Results.resolveWith(Results.java:110)
    at io.quarkus.qute.Results.resolveAndProcess(Results.java:50)
    at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:238)
    at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:66)
    at io.quarkus.qute.Parser$1.resolve(Parser.java:1331)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.IncludeSectionHelper.resolve(IncludeSectionHelper.java:50)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:58)
    at io.quarkus.qute.Results.resolveWith(Results.java:110)
    at io.quarkus.qute.Results.resolveAndProcess(Results.java:50)
    at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:238)
    at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:66)
    at io.quarkus.qute.Parser$1.resolve(Parser.java:1331)
    at io.quarkus.qute.SectionNode.resolve(SectionNode.java:53)
    at io.quarkus.qute.IncludeSectionHelper.resolve(IncludeSectionHelper.java:
```

**Comment by ia3andy** [comment]
You can reproduce it on the Roq blog dir
start dev, edit the web-bundler js
and then open the index again

**Comment by mkouba** [comment]
It's the problem connected to `io.quarkus.qute.runtime.devmode.QuteSetup`. In order to support [`quarkus.qute.dev-mode.no-restart-templates`](https://quarkus.io/guides/qute-reference#quarkus-qute_quarkus-qute-dev-mode-no-restart-templates) we attempt to reload all templates when a no-restart change is detected. However, message bundles are not reflected in this logic.

I don't think we could reliably identify the set of templates that need to bo reloaded (because of `{#include}` etc.).

The correct solution is probably to introduce a dedicated `TemplateLocator` for message bundles... so that the messages can be reloaded automatically.
