### ISSUE TITLE
Swagger UI can't load large YAML file.

### ISSUE THREAD

**Issue by dhoffer** [quarkusio/quarkus#43969]
### Describe the bug

We are porting a large JAX-RS application to Quarkus 999-SNAPSHOT

We are using this for the OpenAPI generation.

`<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
 </dependency>`

And have configured with

`  smallrye-openapi:
    path: /q/swagger-openapi
    info-version: ${project.version}
    store-schema-directory: target/generated-openapi/
  swagger-ui:
    always-include: true
    path: /q/swagger-ui
    urls-primary-name: http
    urls:
      default: /q/swagger-openapi
      local: /q/swagger-openapi
      http: /q/swagger-openapi`

We I run the app and point the browser to http://localhost:8080/q/swagger-ui/#/ I get the following in the app's console log.

`Caused by: com.fasterxml.jackson.dataformat.yaml.JacksonYAMLParseException: The incoming YAML document exceeds the limit: 3145728 code points.
 at [Source: (InputStreamReader); line: 87426, column: 100]
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:456)
        at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:1151)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:539)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:100)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:25)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4959)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3270)
        at io.smallrye.openapi.runtime.io.JacksonJsonIO.fromReader(JacksonJsonIO.java:293)
        ... 76 more
Caused by: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:317)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowMappingKey.produce(ParserImpl.java:889)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162)
        at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:172)
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.getEvent(YAMLParser.java:590)
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:450)
        ... 84 more
`

How can I configure Snakeyaml to accept a larger file size?  I know in code it can be done like this

`LoaderOptions loadingConfig = new LoaderOptions();
            loadingConfig.setCodePointLimit(maxYamlCodePointSize);
            Yaml yaml = new Yaml(loadingConfig);`

Where maxYamlCodePointSize can be any size.  How do I configure this in Quarkus?  I don't see a property for this, is there a way for me to provide my own LoaderOptions?  If not, can a way be added to configure this?  We can't move to Quarkus 3 with quarkus-smallrye-openapi w/o an approach for this.

### Expected behavior

Swagger UI will load with any size YAML.  Expected to be able to configure max YAML size.

### Actual behavior

 org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.

### Output of `java -version`

Java version: 21.0.4, vendor: Oracle Corporation, runtime: C:\Programs\Java\jdk-21.0.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by MikeEdgar** [comment]
@dhoffer you can use `mp.openapi.extensions.smallrye.maximumStaticFileSize` for this.

**Comment by MikeEdgar** [comment]
You can either append `.json` to the OpenAPI request, or add query parameter `format=JSON`.

**Comment by dhoffer** [comment]
That is perfect, thanks!
