### ISSUE TITLE
Quarkus Native with quarkus-jdbc-oracle error

### ISSUE THREAD

**Issue by fdoyledafm** [quarkusio/quarkus#43999]
### Describe the bug

Similar to this issue https://github.com/quarkusio/quarkus/issues/23341 (Which is was getting with Quarkus 3.12), with 3.14 and 3.15 I'm getting the below error when Quarkus in Native mode is deployed to a container. Not using Native mode, the application works fine.

`
2024-09-25 16:08:54,195 WARN [io.agr.pool] (agroal-11) Datasource '<default>': Failed to create connection due to ArrayIndexOutOfBoundsException
2024-09-25 16:08:54,196 WARN [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
at oracle.jdbc.driver.T4CTTIoauthenticate.setSessionFields(T4CTTIoauthenticate.java:2658)
at oracle.jdbc.driver.T4CTTIoauthenticate.<init>(T4CTTIoauthenticate.java:452)
at oracle.jdbc.driver.T4CConnection.authenticateUserForLogon(T4CConnection.java:1980)
at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:1090)
at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1206)
at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:105)
at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:886)
at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:693)
at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:225)
at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:580)
at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:561)
at java.base@21.0.4/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
at java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596)
at java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
2024-09-25 16:08:54,201 WARN [io.qua.hib.orm.run.ser.QuarkusRuntimeInitDialectFactory] (JPA Startup Thread) Persistence unit <default>: Could not retrieve the database version to check it is at least 19.0.0
2024-09-25 16:08:54,256 INFO [io.quarkus] (main) appname 1.0.0-SNAPSHOT native (powered by Quarkus 3.14.4) started in 0.220s. Listening on: http://0.0.0.0:8080
2024-09-25 16:08:54,256 INFO [io.quarkus] (main) Profile prod activated.
2024-09-25 16:08:54,256 INFO [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-oracle, narayana-jta, rest, rest-jackson, smallrye-context-propagation, smallrye-health, vertx]
`

### Expected behavior

I expect this extension to work properly the same way as in JVM mode.

### Actual behavior

Quarkus crashes during DB connection initialization while running in Native mode.

### Output of `java -version`

java version "22.0.2" 2024-07-16

### Quarkus version or git rev

3.14 or 3.15

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8

**Comment by melloware** [comment]
Hmm I use it native mode without issue. Can you create a small reproducible example?

**Comment by fdoyledafm** [comment]
Reproducer here: https://github.com/fdoyledafm/quarkus-reproducible-43999

Just a fresh project with relevant extensions installed throws the error when in native mode

**Comment by yrodiere** [comment]
@fdoyledafm that project builds and starts just fine for me:

```
❯ ./target/reproduce-1.0.0-SNAPSHOT-runner
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-10-23 12:27:55,972 INFO  [io.quarkus] (main) reproduce 1.0.0-SNAPSHOT native (powered by Quarkus 3.15.1) started in 0.017s. Listening on: http://0.0.0.0:8080
2024-10-23 12:27:55,972 INFO  [io.quarkus] (main) Profile prod activated. 
2024-10-23 12:27:55,972 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-oracle, narayana-jta, rest, smallrye-context-propagation, smallrye-health, vertx]
```

That being said, Hibernate ORM is disabled since there are no entities in the project.

Maybe you forgot to push a few commits... ?

**Comment by fdoyledafm** [comment]
For me I didn't need any entities to reproduce the problem. When the container is started health checks will trigger the error:

```cmd
2024-10-23 10:55:50,237 INFO [io.quarkus] (main) reproduce 1.0.0-SNAPSHOT native (powered by Quarkus 3.15.1) started in 0.047s. Listening on: http://0.0.0.0:8080
2024-10-23 10:55:50,237 INFO [io.quarkus] (main) Profile prod activated.
2024-10-23 10:55:50,237 INFO [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-oracle, narayana-jta, rest, smallrye-context-propagation, smallrye-health, vertx]
2024-10-23 10:57:27,542 WARN [io.agr.pool] (agroal-11) Datasource '<default>': Failed to create connection due to ArrayIndexOutOfBoundsException
2024-10-23 10:57:27,543 ERROR [io.sma.health] (executor-thread-1) SRHCK01000: Error processing Health Checks: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
at oracle.jdbc.driver.T4CTTIoauthenticate.setSessionFields(T4CTTIoauthenticate.java:2658)
at oracle.jdbc.driver.T4CTTIoauthenticate.<init>(T4CTTIoauthenticate.java:452)
at oracle.jdbc.driver.T4CConnection.authenticateUserForLogon(T4CConnection.java:1980)
at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:1090)
at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1206)
at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:105)
at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:886)
at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:693)
at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:225)
at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:580)
at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:561)
at java.base@21.0.4/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
at java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596)
at java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
```

**Comment by yrodiere** [comment]
JVM or native, the connection works in my case, using your reproduceer, with JDBC URL `jdbc:oracle:thin:@localhost:1521/FREEPDB1`, and `docker.io/gvenzl/oracle-free:23` running in a container locally as the database.

```
$ curl localhost:8080/q/health
{
    "status": "UP",
    "checks": [
        {
            "name": "Database connections health check",
            "status": "UP",
            "data": {
                "<default>": "UP"
            }
        }
    ]
}
```

I followed these steps:

```sh
docker build -f src/main/docker/Dockerfile.native -t quarkus/reproduce .
docker run -it --rm -p 8080:8080 -e quarkus.datasource.jdbc.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1 -e quarkus.datasource.username=hibernate_orm_test -e quarkus.datasource.password=hibernate_orm_test --network=host quarkus/reproduce
curl localhost:8080/q/health
```

That being said, that dockerfile doesn't define health checks -- that's why I used curl to trigger a health check. So I suspect you're doing something different...

Can you provide the precise steps needed to reproduce the problem? A list of commands, including how you build your container, how your start your Oracle DB, how you run your container (with the JDBC URL), ....

Also, general environment information (OS? Oracle version? Docker or podman?) might help.

**Comment by Bzaid94** [comment]
@yrodiere  
It sounds like you're encountering an issue similar to one I faced while working with Quarkus 3.15.1, GraalVM 17, and the Oracle JDBC driver, specifically during the native image build. Here's how I approached and resolved it:
My Setup:
    OS: Windows or Linux
    ORCLE: 11.2.0
    GraalVM 17 for Java 17 native image compilation.
    Quarkus 3.15.1

The Issue:

When building the native image using:

`./mvnw clean package -Pnative --define quarkus.native.container-build=true -DskipTests
docker build -f src/main/docker/Dockerfile.native -t ${MICROSERVICE_NAME}:latest .
docker run -i --name gen --network bla -p 9010:9010 -p 8080:8080 ${MICROSERVICE_NAME}:latest
`

the POM

` <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-oracle</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-agroal</artifactId>
        </dependency>`

**Comment by yrodiere** [comment]
Thanks for the additional information @Bzaid94 .

> GraalVM 17 for Java 17 native image compilation.

Quarkus 3.15.1 requires GraalVM for Java 21: https://quarkus.io/guides/building-native-image#configuring-graalvm

Did you see the same problem with the correct version of GraalVM?

@fdoyledafm were you also using an older version of GraalVM? Does upgrading help?

**Comment by Bzaid94** [comment]
@yrodiere 
hanks for the suggestion, but I managed to resolve the issue while still using GraalVM 17 with Quarkus 3.15.1. The problem was related to character set support in the native image build. Adding the following property to my application.properties was the key:

properties

`quarkus.native.add-all-charsets=true`

This ensures that all available charsets are included in the native image, which solved the issue with the database connection (specifically, the "connection was null" error and the ArrayIndexOutOfBoundsException related to Oracle JDBC).

So far, everything works perfectly with GraalVM 17 and Quarkus 3.15.1. I hope this helps anyone facing similar issues!

**Comment by yrodiere** [comment]
Thanks for confirming, and thanks for the helpful details!

Since this does not happen when using the recommended (really, required) version of GraalVM, I will close the issue.
