### ISSUE TITLE
IllegalStateException when using @PermissionsAllowed

### ISSUE THREAD

**Issue by mbleichner** [quarkusio/quarkus#44068]
### Describe the bug

The following constellation leads to an `IllegalStateException: The current thread cannot be blocked`:

REST resource with...
- `@PermissionsAllowed` on class-level
- Accessing an injected service via a `public` field
- Returning a `Flow<String>`

### Expected behavior

No exception should be thrown.

### Actual behavior

```
java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-1

Stack:
        java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-1
        at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
        at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)
        at io.quarkus.security.identity.SecurityIdentity.checkPermissionBlocking(SecurityIdentity.java:126)
        at io.quarkus.security.runtime.interceptor.check.PermissionSecurityCheck$1.checkPermissions(PermissionSecurityCheck.java:120)
        at io.quarkus.security.runtime.interceptor.check.PermissionSecurityCheck$1.checkPermissions(PermissionSecurityCheck.java:99)
        at io.quarkus.security.runtime.interceptor.check.PermissionSecurityCheck.apply(PermissionSecurityCheck.java:50)
        at io.quarkus.security.runtime.interceptor.SecurityConstrainer.check(SecurityConstrainer.java:83)
        at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:46)
        at io.quarkus.security.runtime.interceptor.PermissionsAllowedInterceptor.intercept(PermissionsAllowedInterceptor.java:26)
        at io.quarkus.security.runtime.interceptor.PermissionsAllowedInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:44)
        at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_PermissionsAllowedInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at org.acme.GreetingResource1_Subclass.getSomeService(Unknown Source)
        at org.acme.GreetingResource1$hello$1.invokeSuspend(GreetingResource.kt:29)
        at org.acme.GreetingResource1$hello$1.invoke(GreetingResource.kt)
        at org.acme.GreetingResource1$hello$1.invoke(GreetingResource.kt)
        at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(Builders.kt:316)
        at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Builders.kt)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:56)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at org.jboss.resteasy.reactive.server.runtime.kotlin.VertxDispatcher.dispatch$lambda$0(ApplicationCoroutineScope.kt:45)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)
        at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

[reproducer.zip](https://github.com/user-attachments/files/17503658/reproducer.zip)

`curl http://localhost:8080/api/hello1` => crashes

(see the source code for other variations that work correcly)

### Output of `java -version`

21.0.4

### Quarkus version or git rev

3.15.1

**Comment by mschorsch** [comment]
cc @sberyozkin

**Comment by sberyozkin** [comment]
Also CC @michalvavrik, Michal, I'm pretty sure you looked at a nearly identical issue with some of AWS services ?

**Comment by michalvavrik** [comment]
> Also CC [@michalvavrik](https://github.com/michalvavrik), Michal, I'm pretty sure you looked at a nearly identical issue with some of AWS services which ended up being not a Quarkus issue ?

Well, I think this is different issue. I think we apply security check on Kotlin `public val some:SomeService` inside constructor. I don't know how this works internally inside Quarkus, but it is definitely something I'll try to fix.

**Comment by michalvavrik** [comment]
BTW I don't believe it is specific for the `@PermissionsAllowed`, I'd expect this will happen for any security annotation? You can confirm if you know, but it's not necessary to spend time on this. Thanks

**Comment by michalvavrik** [comment]
Because if so, I think this issue should be renamed bit so that it says something like _public getters generated for Kotlin constructor parameters are secured with standard security annotations_. That is my preliminary assumptions and I'll need to debug it when I find a time.

**Comment by michalvavrik** [comment]
I forgot, thank you @mbleichner for very nice reproducer.

**Comment by michalvavrik** [comment]
Hey, I ported and adjusted reproducer for our Quarkus ITs https://github.com/michalvavrik/quarkus/pull/new/feature/kotlin-constructor-param-security-checks and I am not sure whether we should fix it, or how. My Kotlin knowledge is very limited, but I checked docs here https://kotlinlang.org/docs/properties.html#getters-and-setters and it says that annotation that parameter annotates setter, like here:

```
var setterWithAnnotation: Any? = null
    @Inject set // annotate the setter with Inject
```
and so, we are simply doing the same and we cannot really stop securing accessors. I think for Kotlin users it would be the most convenient if they could annotation fields as well, like here, they would use `@PermitAll`, but it would be confusing for Java users.

@geoand I'd like to gather opinion from someone who specializes on Kotlin in Quarkus. Is it you or can you ping someone else, please?

**Comment by geoand** [comment]
I'll have a look next week

**Comment by geoand** [comment]
So if I understand correctly, the problem is that when `public val someService: SomeService` is used, then security check comes into play when `someService.test(channel)` called, correct?

If so, to me this is expected

**Comment by michalvavrik** [comment]
> So if I understand correctly, the problem is that when `public val someService: SomeService` is used, then security check comes into play when `someService.test(channel)` called, correct?

yes

> If so, to me this is expected

I think so. At the very least I feel much safer that accesor is also secured. The fact that this happens when security checks are applied to CDI beans is kinda explained here https://quarkus.io/guides/security-proactive-authentication. I can understand that @mbleichner didn't know what was going there, but it is limitation I don't think we can work around. If accessor is blocking, we need to perform blocking security check on IO thread, which is illegal state.

@mbleichner I think you already know your options, but I'll do recap for whoever comes after you. Use one of.

- use private property
- declare non-blocking explicit accessor and use it
- stop applying checks on every public method (like don't use class level security annotation), use method level security annotation

I also though about it and this could be specific for permission checks because they are non-blocking, this cannot be worked around because it comes from API and brings advantages: https://github.com/quarkusio/quarkus-security/blob/main/src/main/java/io/quarkus/security/identity/SecurityIdentity.java#L121

So if you feel strongly about continuing with current approach, other security annotations will be also applied, but probably don't need to block there as identity is already available in your case and these checks are sync.

**Comment by michalvavrik** [comment]
Thanks @geoand for having a look.

**Comment by michalvavrik** [comment]
Closing as won't fix.

**Comment by geoand** [comment]
🙏🏽
