### ISSUE TITLE
Funqy AWS Lambda native build fails related to opentelemetry dependency since 3.16.0

### ISSUE THREAD

**Issue by holomekc** [quarkusio/quarkus#44094]
### Describe the bug

I know it is a bit early for 3.16.0, but we want to report it anyway.
We have a native build for an AWS Lambda using Funqy. Since 3.16.0 it fails with:
```java
Error: Discovered unresolved type during parsing: io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.OpenTelemetryVertxMetricsFactory$OpenTelemetryHttpServerMetrics. This error is reported at image build time because class io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.OpenTelemetryVertxMetricsFactory is registered for linking at image build time by command line and command line.
Error encountered while parsing io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.OpenTelemetryVertxMetricsFactory.metrics(OpenTelemetryVertxMetricsFactory.java:29) 
Parsing context:
   at io.vertx.core.spi.VertxMetricsFactory.init(VertxMetricsFactory.java:50)
   at io.vertx.core.impl.VertxBuilder.initProviders(VertxBuilder.java:284)
   at io.vertx.core.impl.VertxBuilder.init(VertxBuilder.java:275)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:254)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:681)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$11.get(VertxCoreRecorder.java:552)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$11.get(VertxCoreRecorder.java:549)
   at software.amazon.awssdk.core.endpointdiscovery.providers.ProfileEndpointDiscoveryProvider.resolveEndpointDiscovery(ProfileEndpointDiscoveryProvider.java:47)
   at software.amazon.awssdk.core.endpointdiscovery.providers.EndpointDiscoveryProviderChain.resolveEndpointDiscovery(EndpointDiscoveryProviderChain.java:41)
   at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbBaseClientBuilder.finalizeServiceConfiguration(DefaultDynamoDbBaseClientBuilder.java:93)
   at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:167)
   at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.java:228)
   at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbAsyncClientBuilder.buildClient(DefaultDynamoDbAsyncClientBuilder.java:53)
   at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbAsyncClientBuilder.buildClient(DefaultDynamoDbAsyncClientBuilder.java:25)
   at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:164)
   at software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient.create(DynamoDbAsyncClient.java:11745)
   at software.amazon.awssdk.enhanced.dynamodb.internal.client.DefaultDynamoDbEnhancedAsyncClient.<init>(DefaultDynamoDbEnhancedAsyncClient.java:48)
   at software.amazon.awssdk.enhanced.dynamodb.internal.client.DefaultDynamoDbEnhancedAsyncClient$Builder.build(DefaultDynamoDbEnhancedAsyncClient.java:181)
   at io.quarkus.amazon.dynamodb.enhanced.runtime.DynamodbEnhancedClientRecorder$2.apply(DynamodbEnhancedClientRecorder.java:98)
   at io.quarkus.amazon.dynamodb.enhanced.runtime.DynamodbEnhancedClientRecorder$2.apply(DynamodbEnhancedClientRecorder.java:93)
   at io.quarkus.cache.CacheManager_gav3xP1Xa1oNcPy1xyyVtm9vI-c_Synthetic_Bean.createSynthetic(Unknown Source)
   at io.quarkus.cache.CacheManager_gav3xP1Xa1oNcPy1xyyVtm9vI-c_Synthetic_Bean.doCreate(Unknown Source)
   at io.quarkus.cache.CacheManager_gav3xP1Xa1oNcPy1xyyVtm9vI-c_Synthetic_Bean.create(Unknown Source)
   at io.quarkus.cache.CacheManager_gav3xP1Xa1oNcPy1xyyVtm9vI-c_Synthetic_Bean.create(Unknown Source)
   at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
   at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
   at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
   at software.amazon.awssdk.utils.OptionalUtils.firstPresent(OptionalUtils.java:47)
   at software.amazon.awssdk.utils.internal.SystemSettingUtils.resolveSetting(SystemSettingUtils.java:45)
   at software.amazon.awssdk.utils.Platform.isWindows(Platform.java:29)
   at software.amazon.awssdk.auth.credentials.ProcessCredentialsProvider.executableCommand(ProcessCredentialsProvider.java:112)
   at software.amazon.awssdk.auth.credentials.ProcessCredentialsProvider.<init>(ProcessCredentialsProvider.java:89)
   at software.amazon.awssdk.auth.credentials.ProcessCredentialsProvider$Builder.build(ProcessCredentialsProvider.java:361)
   at io.quarkus.amazon.common.runtime.AwsCredentialsProviderType$8.create(AwsCredentialsProviderType.java:99)
   at root method.(Unknown Source)

```

With 3.15.1 it is working fine.

### Expected behavior

Same behavior as in 3.15.1

### Actual behavior

-

### Output of `uname -a` or `ver`

Darwin Kernel Version 23.6.0

### Output of `java -version`

OpenJDK Runtime Environment Corretto-21.0.4.7.1

### Quarkus version or git rev

3.16.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9

**Comment by brunobat** [comment]
This PR might fix the issue: https://github.com/quarkusio/quarkus/pull/44072
Can you please doublecheck?

**Comment by holomekc** [comment]
Hi @brunobat ,

sorry for the late response. Yes this seems to help. 3.16.1 looks great

**Comment by brunobat** [comment]
Closing the issue.
