### ISSUE TITLE
3.16.0: `ExtendedQuarkusVertxHttpMetrics` not found in tests

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#44125]
### Describe the bug

Upgrading from 3.15.1 to 3.16.0 results in a `ClassNotFoundException` w.r.t. `ExtendedQuarkusVertxHttpMetrics` while running tests in many modules of my multi module maven project.
All affected modules seem to have in common that they don't have `quarkus-vertx-http` on the classpath.

### Expected behavior

No exception.

### Actual behavior

```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:632)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:716)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:305)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:245)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:599)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:649)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: io/quarkus/vertx/http/runtime/ExtendedQuarkusVertxHttpMetrics
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:531)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:490)
	at io.quarkus.opentelemetry.runtime.tracing.intrumentation.vertx.OpenTelemetryVertxMetricsFactory.metrics(OpenTelemetryVertxMetricsFactory.java:29)
	at io.vertx.core.spi.VertxMetricsFactory.init(VertxMetricsFactory.java:50)
	at io.vertx.core.impl.VertxBuilder.initProviders(VertxBuilder.java:284)
	at io.vertx.core.impl.VertxBuilder.init(VertxBuilder.java:275)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:254)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:681)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:660)
	at io.quarkus.opentelemetry.runtime.OpenTelemetryRecorder.storeVertxOnContextStorage(OpenTelemetryRecorder.java:48)
	at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry193862828.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry193862828.deploy(Unknown Source)
	... 8 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.vertx.http.runtime.ExtendedQuarkusVertxHttpMetrics
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:542)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:490)
	... 22 more
```

### Quarkus version or git rev

3.16.0

### Additional information

I've I had to guess I'd say it's caused by https://github.com/quarkusio/quarkus/pull/43919/files#diff-961d9cea05a0737ae8c64bb818127d66f4e8d2e70a3b1b3a59a78ce623667fb7

**Comment by gsmet** [comment]
Hey @famod ! Can you try with https://github.com/quarkusio/quarkus/pull/44072?

**Comment by famod** [comment]
Hi @gsmet! Fix confirmed, thanks for the pointer.

**Comment by gsmet** [comment]
Thanks for opening this. I think I will build a 3.16.1 before the official release.
