### ISSUE TITLE
GraalVM native image build fails for ubi-quarkus-graalvmce-s2i:jdk-17 when running on OpenShift

### ISSUE THREAD

**Issue by gtroitsk** [quarkusio/quarkus#44142]
### Describe the bug

[OpenShiftS2iQuickstartUsingDefaultsIT](https://github.com/quarkus-qe/quarkus-test-framework/blob/eb127f0492c8bb424ca59c3fea1e1aa77ddd767a/examples/external-applications/src/test/java/io/quarkus/qe/OpenShiftS2iQuickstartUsingDefaultsIT.java) from Quarkus QE FW fails when running on OpenShift and Native using `quay.io/quarkus/ubi-quarkus-graalvmce-s2i:jdk-17`. JDK 21 version works as expected.

### Expected behavior

Native image builds successfully

### Actual behavior

```
10:45:12,355 INFO  oc: [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GRAALVM 23.0 JDK 17.0.8+7-jvmci-23.0-b15
10:45:12,355 INFO  oc: [WARNING] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] You are using an older version of GraalVM or Mandrel : 23.0. Quarkus currently supports 23.1.0. Please upgrade to this version.
10:45:12,355 INFO  oc: [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /opt/graalvm/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Duser.language=en -J-Duser.country=US -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -H:IncludeLocales=en-US -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-exports=java.security.jgss/sun.security.jgss=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:BuildOutputJSONFile=getting-started-1.0.0-SNAPSHOT-runner-build-output-stats.json -H:+GenerateBuildArtifactsFile -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http -H:NativeLinkerOption=-no-pie --enable-monitoring=heapdump -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json getting-started-1.0.0-SNAPSHOT-runner -jar getting-started-1.0.0-SNAPSHOT-runner.jar
10:45:16,352 INFO  oc: ========================================================================================================================
10:45:16,352 INFO  oc: GraalVM Native Image: Generating 'getting-started-1.0.0-SNAPSHOT-runner' (executable)...
10:45:16,352 INFO  oc: ========================================================================================================================
10:45:16,353 INFO  oc: For detailed information and explanations on the build output, visit:
10:45:16,353 INFO  oc: https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
10:45:16,353 INFO  oc: ------------------------------------------------------------------------------------------------------------------------
10:45:18,294 INFO  oc: Warning: Method io.quarkus.runtime.configuration.CharsetConverter.provider() not found.
10:45:18,294 INFO  oc: Warning: Method io.quarkus.runtime.configuration.MemorySizeConverter.provider() not found.
10:45:18,294 INFO  oc: Warning: Method io.quarkus.runtime.configuration.InetSocketAddressConverter.provider() not found.
10:45:18,295 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.TrustedProxyCheckPartConverter.provider() not found.
10:45:18,295 INFO  oc: Warning: Method io.quarkus.runtime.configuration.CidrAddressConverter.provider() not found.
10:45:18,295 INFO  oc: Warning: Method io.quarkus.runtime.configuration.InetAddressConverter.provider() not found.
10:45:18,295 INFO  oc: Warning: Method io.quarkus.runtime.configuration.RegexConverter.provider() not found.
10:45:18,295 INFO  oc: Warning: Method io.quarkus.runtime.configuration.PathConverter.provider() not found.
10:45:18,295 INFO  oc: Warning: Method io.quarkus.runtime.configuration.DurationConverter.provider() not found.
10:45:18,295 INFO  oc: Warning: Method io.quarkus.runtime.configuration.LocaleConverter.provider() not found.
10:45:18,295 INFO  oc: Warning: Method io.quarkus.runtime.configuration.ZoneIdConverter.provider() not found.
10:45:18,295 INFO  oc: Warning: Method io.quarkus.runtime.logging.LevelConverter.provider() not found.
10:45:18,295 INFO  oc: Warning: Method sun.security.provider.NativePRNG.<init>(SecureRandomParameters) not found.
10:45:18,295 INFO  oc: Warning: Could not resolve class java.lang.Thread$Builder$OfVirtual for reflection configuration. Reason: java.lang.ClassNotFoundException: java.lang.Thread$Builder$OfVirtual.
10:45:18,295 INFO  oc: Warning: Could not resolve class java.lang.Thread$Builder for reflection configuration. Reason: java.lang.ClassNotFoundException: java.lang.Thread$Builder.
10:45:18,296 INFO  oc: Warning: Method io.quarkus.bootstrap.logging.InitialConfigurator.provider() not found.
10:45:18,296 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.RemoteIPAttribute$Builder.provider() not found.
10:45:18,296 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.LocalIPAttribute$Builder.provider() not found.
10:45:18,296 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.RequestProtocolAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.LocalPortAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.IdentUsernameAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.RequestMethodAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.QueryStringAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.RequestLineAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.BytesSentAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.DateTimeAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.RemoteUserAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.RequestURLAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.ThreadNameAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.LocalServerNameAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.RequestHeaderAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.ResponseHeaderAttribute$Builder.provider() not found.
10:45:18,500 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.CookieAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.ResponseCodeAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.QueryParameterAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.SslClientCertAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.SslCipherAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.SslSessionIdAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.ResponseTimeAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.TransportProtocolAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.RequestSchemeAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.SecureExchangeAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.RemoteHostAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.RequestPathAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.NullAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.AllRequestHeadersAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.ExchangeDataAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.quarkus.vertx.http.runtime.attribute.VertxMDCDataAttribute$Builder.provider() not found.
10:45:18,501 INFO  oc: Warning: Method io.smallrye.config.SmallRyeConfigProviderResolver.provider() not found.
10:45:18,501 INFO  oc: Warning: Method org.jboss.resteasy.reactive.common.jaxrs.RuntimeDelegateImpl.provider() not found.
10:45:19,215 INFO  oc: [1/8] Initializing...                                                                                    (5.9s @ 0.26GB)
10:45:19,215 INFO  oc:  Java version: 17.0.8+7, vendor version: GraalVM CE 17.0.8+7.1
10:45:19,215 INFO  oc:  Graal compiler: optimization level: 2, target machine: x86-64-v3
10:45:19,215 INFO  oc:  C compiler: gcc (redhat, x86_64, 8.5.0)
10:45:19,215 INFO  oc:  Garbage collector: Serial GC (max heap size: 80% of RAM)
10:45:19,215 INFO  oc:  2 user-specific feature(s)
10:45:19,215 INFO  oc:  - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
10:45:19,215 INFO  oc:  - io.quarkus.runtime.graal.DisableLoggingFeature: Adapts logging during the analysis phase
10:45:19,419 INFO  oc: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "version" is null
10:45:19,420 INFO  oc: 	at io.quarkus.runtime.graal.GraalVM$Version.breakdownVersion(GraalVM.java:120)
10:45:19,420 INFO  oc: 	at io.quarkus.runtime.graal.GraalVM$Version.<init>(GraalVM.java:114)
10:45:19,420 INFO  oc: 	at io.quarkus.runtime.graal.GraalVM$Version.<init>(GraalVM.java:109)
10:45:19,420 INFO  oc: 	at io.quarkus.runtime.graal.GraalVM$Version.<init>(GraalVM.java:105)
10:45:19,420 INFO  oc: 	at io.quarkus.runtime.graal.GraalVM$VersionParseHelper.parse(GraalVM.java:52)
10:45:19,420 INFO  oc: 	at io.quarkus.runtime.graal.GraalVM$Version.getCurrent(GraalVM.java:183)
10:45:19,420 INFO  oc: 	at io.quarkus.runner.Feature.beforeAnalysis(Unknown Source)
10:45:19,420 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:757)
10:45:19,420 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:86)
10:45:19,420 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:757)
10:45:19,420 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
10:45:19,420 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
10:45:19,420 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
10:45:19,420 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
10:45:19,420 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
10:45:19,421 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
10:45:29,558 INFO  oc: Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
10:45:29,558 INFO  oc: Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
10:45:29,558 INFO  oc: Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
10:45:29,558 INFO  oc: Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
10:45:29,558 INFO  oc: Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
10:45:29,558 INFO  oc: Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of org.jboss.threads.EnhancedQueueExecutor$RuntimeFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
10:45:40,514 INFO  oc: [2/8] Performing analysis...  [*]                                                                       (21.0s @ 1.63GB)
10:45:40,514 INFO  oc:   10,549 (86.34%) of 12,218 types reachable
10:45:40,514 INFO  oc:   15,681 (56.41%) of 27,796 fields reachable
10:45:40,531 INFO  oc:   53,801 (56.39%) of 95,414 methods reachable
10:45:40,531 INFO  oc:    3,439 types,   118 fields, and 3,105 methods registered for reflection
10:45:40,535 INFO  oc: 
10:45:40,537 INFO  oc: ------------------------------------------------------------------------------------------------------------------------
10:45:40,538 INFO  oc: Error: Classes that should be initialized at run time got initialized during image building:
10:45:40,538 INFO  oc:  io.netty.buffer.UnpooledDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledDirectByteBuf
10:45:40,538 INFO  oc: io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf
10:45:40,638 INFO  oc: io.netty.buffer.UnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeHeapByteBuf
10:45:40,638 INFO  oc: io.netty.buffer.UnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledHeapByteBuf
10:45:40,638 INFO  oc: io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf
10:45:40,638 INFO  oc: io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf
10:45:40,638 INFO  oc: io.netty.buffer.UnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeDirectByteBuf
10:45:40,638 INFO  oc: io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///tmp/src/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.111.Final.jar' with 'io.netty.buffer.ByteBufUtil'). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
10:45:40,639 INFO  oc: io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///tmp/src/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.111.Final.jar' with 'io.netty.buffer.PooledByteBufAllocator'). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
10:45:40,639 INFO  oc: io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///tmp/src/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.111.Final.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf
10:45:40,639 INFO  oc: To see how the classes got initialized, use --trace-class-initialization=io.netty.buffer.UnpooledDirectByteBuf,io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf,io.netty.buffer.UnpooledUnsafeHeapByteBuf,io.netty.buffer.UnpooledHeapByteBuf,io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf,io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf,io.netty.buffer.UnpooledUnsafeDirectByteBuf,io.netty.buffer.ByteBufUtil,io.netty.buffer.PooledByteBufAllocator,io.netty.buffer.AbstractReferenceCountedByteBuf
10:45:40,639 INFO  oc: com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
10:45:40,639 INFO  oc:  io.netty.buffer.UnpooledDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledDirectByteBuf
10:45:40,639 INFO  oc: io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf
10:45:40,639 INFO  oc: io.netty.buffer.UnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeHeapByteBuf
10:45:40,639 INFO  oc: io.netty.buffer.UnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledHeapByteBuf
10:45:40,639 INFO  oc: io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf
10:45:40,639 INFO  oc: io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf
10:45:40,639 INFO  oc: io.netty.buffer.UnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeDirectByteBuf
10:45:40,639 INFO  oc: io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///tmp/src/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.111.Final.jar' with 'io.netty.buffer.ByteBufUtil'). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
10:45:40,639 INFO  oc: io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///tmp/src/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.111.Final.jar' with 'io.netty.buffer.PooledByteBufAllocator'). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
10:45:40,639 INFO  oc: io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///tmp/src/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.111.Final.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf
10:45:40,651 INFO  oc: To see how the classes got initialized, use --trace-class-initialization=io.netty.buffer.UnpooledDirectByteBuf,io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf,io.netty.buffer.UnpooledUnsafeHeapByteBuf,io.netty.buffer.UnpooledHeapByteBuf,io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf,io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf,io.netty.buffer.UnpooledUnsafeDirectByteBuf,io.netty.buffer.ByteBufUtil,io.netty.buffer.PooledByteBufAllocator,io.netty.buffer.AbstractReferenceCountedByteBuf
10:45:40,651 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
10:45:40,651 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.checkDelayedInitialization(ProvenSafeClassInitializationSupport.java:277)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:164)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:770)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:86)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:770)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:179)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:767)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
10:45:40,652 INFO  oc: 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
10:45:40,652 INFO  oc:                         2.7s (9.7% of total time) in 26 GCs | Peak RSS: 3.97GB | CPU load: 8.92
10:45:40,652 INFO  oc: ------------------------------------------------------------------------------------------------------------------------
10:45:40,652 INFO  oc: Produced artifacts:
10:45:40,652 INFO  oc:  /tmp/src/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/build-artifacts.json (build_info)
10:45:40,652 INFO  oc:  /tmp/src/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/getting-started-1.0.0-SNAPSHOT-runner-build-output-stats.json (build_info)
10:45:40,652 INFO  oc: ========================================================================================================================
10:45:40,652 INFO  oc: Finished generating 'getting-started-1.0.0-SNAPSHOT-runner' in 27.3s.
10:45:41,094 INFO  oc: [INFO] ------------------------------------------------------------------------
10:45:41,094 INFO  oc: [INFO] BUILD FAILURE
10:45:41,094 INFO  oc: [INFO] ------------------------------------------------------------------------

```

### How to Reproduce?

1. `git clone git@github.com:quarkus-qe/quarkus-test-framework.git`
2. `cd  quarkus-test-framework`
3. `mvn clean install -Dquarkus.platform.version=999-SNAPSHOT -Dquarkus.platform.group-id=io.quarkus -DskipDocs -DskipTests -DskipITs -DskipExtensionValidation -Dskip.gradle.tests -Dcheckstyle.skip`
4. Login to OpenShift
5. cd examples/external-applications
6. `mvn clean verify -Dopenshift -Dnative -Dquarkus.platform.version=999-SNAPSHOT -Dquarkus.platform.group-id=io.quarkus -Dit.test=OpenShiftS2iQuickstartUsingDefaultsIT -Dts.container.registry-url=<...> -Dts.global.s2i.maven.remote.repository=<...>`

### Output of `uname -a` or `ver`

Linux Fedora 6.2.9-200.fc37.x86_64

### Output of `java -version`

Temurin-17.0.9

### Mandrel or GraalVM version (if different from Java)

GRAALVM 23.0 JDK 17.0.8+7-jvmci-23.0-b15

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

### Additional information

Please reach me on Slack to get more information about affected Jenkins job and environment if needed.

**Comment by Karm** [comment]
Hello @gtroitsk, as stated in your log: 
```
 You are using an older version of GraalVM or Mandrel : 23.0. Quarkus currently supports 23.1.0. Please upgrade to this version.
```
you are attempting to use an old image, a dated version of the native-image unsuitable for your Quarkus version.
