### ISSUE TITLE
Narayana JTA XA transactions doesn't work after mariadb-java-client bump to 3.5.0 as opening datasource connection results in SQLNonTransientConnectionException

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#44160]
### Describe the bug

When https://github.com/quarkusio/quarkus/pull/44111 got merged, my app with Narayana JTA that uses XA transactions stopped to work because connection cannot be opened for DS that has enabled XA.

### Expected behavior

MariaDB works with Narayana JTA XA transactions.

### Actual behavior

Connection is closed, communication with DB doesn't work when XA is enabled:

```
2024-10-29 13:02:37,966 WARN  [io.agr.pool] (executor-thread-1) Datasource '<default>': (conn=13) Connection is closed
2024-10-29 13:02:37,970 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: 2249c270-ed13-45b4-954d-f4fa6e6f0f84-1: java.sql.SQLException: Exception in association of connection to existing transaction
	at io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:130)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:292)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.agroal.api.AgroalDataSource_sqqLi56D50iCdXmOjyjPSAxbLu0_Synthetic_ClientProxy.getConnection(Unknown Source)
	at org.acme.GreetingResource.openConnection(GreetingResource.java:31)
	at org.acme.GreetingResource.hello(GreetingResource.java:26)
	at org.acme.GreetingResource_Subclass.hello$$superforward(Unknown Source)
	at org.acme.GreetingResource_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at org.acme.GreetingResource_Subclass.hello(Unknown Source)
	at org.acme.GreetingResource$quarkusrestinvoker$hello_e747664148511e1e5212d3e0f4b40d45c56ab8a1.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:627)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Unable to enlist connection to existing transaction
	at io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:121)
	... 32 more

```

### How to Reproduce?

- `git clone git@github.com:michalvavrik/mariadb-narayna-jta-xa-repro.git`
- `cd mariadb-narayna-jta-xa-repro`

PASS: `mvn clean test`
FAIL: `mvn clean test -Dquarkus.platform.version=999-SNAPSHOT -Dquarkus.platform.group-id=io.quarkus`

### Output of `java -version`

Temurin 21

### Quarkus version or git rev

999-SNAPSHOT

**Comment by michalvavrik** [comment]
cc @gsmet

**Comment by michalvavrik** [comment]
also cc @mmusgrov

**Comment by michalvavrik** [comment]
also cc @yrodiere

**Comment by yrodiere** [comment]
Just... every single connection is failing, even the ones for Hibernate's schema initialization, which I don't think run in transactions.

TestContainers' `SELECT 1` queries appear to succeed, but then I guess TC is not using XA.

This will definitely need investigation; if we're in a rush I'd recommend reverting #44111, but I think that's in 3.17 only, and the release is still a few weeks away.

On a related note @gsmet , I think we talked about the risk/effort balance of not having dedicated tests for XA, especially considering they would require their own module to not interfere in the case of native compilation... looks like the time has come to add them?

**Comment by marcosgopen** [comment]
Thank you @michalvavrik for opening this issue. I wonder if there is a document with Quarkus and DBs supported versions, is there one.
BTW it appears that the new version of mariadb-java-client is affecting the agroal connection. @barreiro have you already tested agroal against mariadb-java-client 3.5.0 version?

**Comment by barreiro** [comment]
@marcosgopen no, we don't test Agroal with specific drivers.

From a quick glance at the [driver changes from 3.4.1 to 3.5.0](https://github.com/mariadb-corporation/mariadb-connector-j/compare/3.4.1...3.5.0) the changes that are most likely to cause issues are the [updates on truststore](https://jira.mariadb.org/browse/CONJ-1183). @michalvavrik can you please verify the TLS settings used ??

**Comment by rsvoboda** [comment]
Reproducer from https://github.com/michalvavrik/mariadb-narayna-jta-xa-repro is using mysql database started trough devservice, there is no customization and no trust store edits.

The app is simple, just getting connection for the datasource - https://github.com/michalvavrik/mariadb-narayna-jta-xa-repro/blob/master/src/main/java/org/acme/GreetingResource.java#L17

@barreiro pls look into the reproducer app and comment added by Yoann https://github.com/quarkusio/quarkus/issues/44160#issuecomment-2447086400

**Comment by rsvoboda** [comment]
https://github.com/mariadb-corporation/mariadb-connector-j/commit/1ce598284e293a79a082e4a06291ec3184e8dffb is the commit introducing the change in MariaDB driver

Discovered through bisecting https://github.com/mariadb-corporation/mariadb-connector-j/compare/3.4.1...3.5.0 and running the sample app

**Comment by marcosgopen** [comment]
@barreiro I think instead that the actual change that caused this issue is[ XA Pool datasource ensuring close when using XAConnection.close() ](https://github.com/mariadb-corporation/mariadb-connector-j/commit/1ce598284e293a79a082e4a06291ec3184e8dffb). They also needed to update the test for it (https://github.com/mariadb-corporation/mariadb-connector-j/commit/a81f0e3822a8232108a976dce9edb73a1948c990#diff-072b4c89a5cf666e9ec822fcb4dcab96035b832ff50c5f7ff59f8e6a0c4958faL199)
Do you think that it might be the reason for this?

**Comment by gsmet** [comment]
> On a related note @gsmet , I think we talked about the risk/effort balance of not having dedicated tests for XA, especially considering they would require their own module to not interfere with non-XA tests in the case of native compilation... looks like the time has come to add these modules?

Yes, I suppose so.

@barreiro don't hesitate to ping the Narayana team if some help from them is needed.

**Comment by gsmet** [comment]
Let's revert for now until someone complains about us using an old version: https://github.com/quarkusio/quarkus/pull/45034 .

But I think we need to isolate the issue and either find a solution on our side in Agroal or Narayana or open a proper issue for the MariaDB JDBC driver.

**Comment by yrodiere** [comment]
FWIW we're discussing this with Luis and the Hibernate team: https://hibernate.zulipchat.com/#narrow/channel/132094-hibernate-orm-dev/topic/MariaDB.20XAConnection.20and.20Connection.23close

So far it seems the solution will be opening an issue for the MariaDB JDBC Driver.

**Comment by yrodiere** [comment]
FTR CONJ-1218 was apparently fixed in the MariaDB JDBC Driver version 3.5.2 -- but that version hasn't been released yet.
