### ISSUE TITLE
Hot-reload brokes Vertx JsonObject serialization (dev mode)

### ISSUE THREAD

**Issue by luca-bassoricci** [quarkusio/quarkus#44231]
### Describe the bug

Scenario: 
- custom dto with a custom jackson `StdSerializer` registered via `ObjectMapperCustomizer`
- serialization of a `io.vertx.core.json.JsonObject` where a property is an instance of custom dto
- serialization of a `io.vertx.core.json.JsonArray` where one or more elements are instances of custom dto

During first run all works correcty, but after the application is hot-reloaded due to some project modifications, serialization stop to works with this error

(partial stacktrace)

```
io.vertx.core.json.EncodeException: Failed to encode as JSON: No serializer found for class org.acme.StringAndInt and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0])
	at io.quarkus.vertx.runtime.jackson.QuarkusJacksonJsonCodec.toString(QuarkusJacksonJsonCodec.java:147)
	at io.vertx.core.json.JsonArray.encode(JsonArray.java:557)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.vertx.VertxJsonArrayMessageBodyWriter.writeResponse(VertxJsonArrayMessageBodyWriter.java:26)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.vertx.VertxJsonArrayMessageBodyWriter.writeResponse(VertxJsonArrayMessageBodyWriter.java:15)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:218)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:186)
	at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriterArray.write(FixedEntityWriterArray.java:31)
	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:34)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:147)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
```

### Expected behavior

Serialization should works correctly after an hot-reload

### Actual behavior

Serialization stops to work after an hot-reload

### How to Reproduce?

https://github.com/luca-bassoricci/vertxjson-serialization-hotreload-issue

No tests are present due to nature of problem.
To reproduce 
1. start application with quarkus:dev
2. do a `GET http://localhost:8080/test/array`, all should works fine
3. reload using 's' console command
4. do a `GET http://localhost:8080/test/array`: error

### Output of `uname -a` or `ver`

windows

### Output of `java -version`

jdk17

### Quarkus version or git rev

3.16.1

**Comment by luca-bassoricci** [comment]
After some digging I have more info to share:
the problem is in `com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer#L108`
```
Class<?> cc = elem.getClass();
JsonSerializer<Object> serializer = serializers.serializerFor(cc);
```
because `cc#classLoader` always change between reload (as expected) instead class stored in `serializers` `(com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap$Single#_type)` is cached between reload and associated CL is always the original CL so Jackson doesn't recognized custom serializer for `cc` and fallback to generic `BeanSerializer`.

**Comment by geoand** [comment]
Thanks for investigating!

I'll try and take a look soon
