### ISSUE TITLE
Failed to get GraalVM version when using quarkus.native.container-build flag

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#44314]
### Describe the bug

I am trying to create a native executable of the simple Hello World generated by code.quarkus.io.

I create the project and I run the following command ` ./mvnw clean package -DskipTests -Dnative -Dquarkus.native.container-build=true`

### Expected behavior

Have a native executable to bundle into a container

### Actual behavior

An exception is thrown:

```
[INFO] --- quarkus:3.16.1:build (default) @ quarkus-demo ---
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /Users/asotobu/Downloads/quarkus-demo/target/quarkus-demo-1.0.0-SNAPSHOT-native-image-source-jar/quarkus-demo-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /Users/asotobu/Downloads/quarkus-demo/target/quarkus-demo-1.0.0-SNAPSHOT-native-image-source-jar/quarkus-demo-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Using podman to run the native image builder
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Pulling builder image 'quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21'
Trying to pull quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21...
Getting image source signatures
Copying blob sha256:9c4339188d20eb1ee9a3af6fcbe6c80d0c44d236c5ad27ac3752b753413a5b0c
Copying blob sha256:ccc2996f86ebd3e4d7977d4c94de45fb72077e08155b2112f39b24ed1981b365
Copying blob sha256:6a5a799843e8ea43bdb601cba21a575ba757cda19bf0411e85e4b3badc986678
Copying blob sha256:52eb8ad51fd48aaed5b349201c18cca41667b19f579af54859ed204afa3f3c0d
Copying blob sha256:6f207f43bb4e3bb6ed573dc5a65c07f8abfcfecca5c79befe2232996a89761c6
Copying blob sha256:246026f7ba8529af6ea2d580bdb99d1e94de8fd7210c4dab07ef5036e6c16c80
Copying blob sha256:023206fd480620443c8e5dd6d118973b4f2ef8f42dd6050a05291d391adc038e
Copying blob sha256:4b6cf535404844b1bca04b1b190f2abf3870ac9d3e95b5909d9fe7fa9c6413d6
Copying blob sha256:cbfcfe1104fbf6f3df11c74de3e649b0a219a80c220427ec23da242383d656bf
Copying blob sha256:0d2cc8b24da5ebe9e792ce8dff2ac02f043477e2c1e62d0eb83ce23bed6278ec
Copying blob sha256:dc454c7fe584cce7a177df5f08a6d48f84a8c41647a1f49f40c7e40c69b68ccd
Copying blob sha256:bde42b15c9c788d64d7c5127b6ca8bfc40dbd8b29827f2b471bee88cce23dde2
Copying blob sha256:7dbbffe8d0d3f4bd81490adc1fe25299dcb5661a7ca9cbcd9aa8d37659471c0b
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying config sha256:7b2500f31c71e1df1da8eba6ef9831314174369fda44228982d4334872447fd0
Writing manifest to image destination
7b2500f31c71e1df1da8eba6ef9831314174369fda44228982d4334872447fd0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.735 s
[INFO] Finished at: 2024-11-05T09:58:36+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.16.1:build (default) on project quarkus-demo: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to get GraalVM version
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildRunner.getGraalVMVersion(NativeImageBuildRunner.java:41)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:236)
[ERROR] 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1575)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:499)
[ERROR] Caused by: java.lang.IllegalArgumentException: Cannot parse version from output:
[ERROR] Error: unmarshalling into &define.InspectContainerData{ID:"c90ea29ea79f5080ce46ba52270e3275b9dc2962cbe102bf207d03408b906cbd", Created:time.Date(2024, time.November, 5, 9, 58, 36, 682575153, time.Local), Path:"native-image", Args:[]string{"--version"}, State:(*define.InspectContainerState)(0xc0004ce280), Image:"7b2500f31c71e1df1da8eba6ef9831314174369fda44228982d4334872447fd0", ImageDigest:"sha256:55f56e732184f91974cf384a32859d678bf87a7306450a2b67f90a971d95abc0", ImageName:"quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21", Rootfs:"", Pod:"", ResolvConfPath:"", HostnamePath:"", HostsPath:"", StaticDir:"/var/lib/containers/storage/overlay-containers/c90ea29ea79f5080ce46ba52270e3275b9dc2962cbe102bf207d03408b906cbd/userdata", OCIConfigPath:"", OCIRuntime:"crun", ConmonPidFile:"/run/containers/storage/overlay-containers/c90ea29ea79f5080ce46ba52270e3275b9dc2962cbe102bf207d03408b906cbd/userdata/conmon.pid", PidFile:"/run/containers/storage/overlay-containers/c90ea29ea79f5080ce46ba52270e3275b9dc2962cbe102bf207d03408b906cbd/userdata/pidfile", Name:"stupefied_hawking", RestartCount:0, Driver:"overlay", MountLabel:"system_u:object_r:container_file_t:s0:c31,c1005", ProcessLabel:"system_u:system_r:container_t:s0:c31,c1005", AppArmorProfile:"", EffectiveCaps:[]string(nil), BoundingCaps:[]string{"CAP_CHOWN", "CAP_DAC_OVERRIDE", "CAP_FOWNER", "CAP_FSETID", "CAP_KILL", "CAP_NET_BIND_SERVICE", "CAP_SETFCAP", "CAP_SETGID", "CAP_SETPCAP", "CAP_SETUID", "CAP_SYS_CHROOT"}, ExecIDs:[]string{}, GraphDriver:(*define.DriverData)(0xc000010f30), SizeRw:(*int64)(nil), SizeRootFs:0, Mounts:[]define.InspectMount{}, Dependencies:[]string{}, NetworkSettings:(*define.InspectNetworkSettings)(0xc0003d37a0), Namespace:"", IsInfra:false, IsService:false, KubeExitCodePropagation:"invalid", LockNumber:0x0, Config:(*define.InspectContainerConfig)(0xc0001b4780), HostConfig:(*define.InspectContainerHostConfig)(0xc0001e9008)}, data "{\"Id\":\"c90ea29ea79f5080ce46ba52270e3275b9dc2962cbe102bf207d03408b906cbd\",\"Created\":\"2024-11-05T09:58:36.682575153+01:00\",\"Path\":\"native-image\",\"Args\":[\"--version\"],\"State\":{\"OciVersion\":\"1.2.0\",\"Status\":\"created\",\"Running\":false,\"Paused\":false,\"Restarting\":false,\"OOMKilled\":false,\"Dead\":false,\"Pid\":0,\"ExitCode\":0,\"Error\":\"\",\"StartedAt\":\"0001-01-01T00:00:00Z\",\"FinishedAt\":\"0001-01-01T00:00:00Z\",\"CheckpointedAt\":\"0001-01-01T00:00:00Z\",\"RestoredAt\":\"0001-01-01T00:00:00Z\"},\"Image\":\"7b2500f31c71e1df1da8eba6ef9831314174369fda44228982d4334872447fd0\",\"ImageDigest\":\"sha256:55f56e732184f91974cf384a32859d678bf87a7306450a2b67f90a971d95abc0\",\"ImageName\":\"quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21\",\"Rootfs\":\"\",\"Pod\":\"\",\"ResolvConfPath\":\"\",\"HostnamePath\":\"\",\"HostsPath\":\"\",\"StaticDir\":\"/var/lib/containers/storage/overlay-containers/c90ea29ea79f5080ce46ba52270e3275b9dc2962cbe102bf207d03408b906cbd/userdata\",\"OCIRuntime\":\"crun\",\"ConmonPidFile\":\"/run/containers/storage/overlay-containers/c90ea29ea79f5080ce46ba52270e3275b9dc2962cbe102bf207d03408b906cbd/userdata/conmon.pid\",\"PidFile\":\"/run/containers/storage/overlay-containers/c90ea29ea79f5080ce46ba52270e3275b9dc2962cbe102bf207d03408b906cbd/userdata/pidfile\",\"Name\":\"stupefied_hawking\",\"RestartCount\":0,\"Driver\":\"overlay\",\"MountLabel\":\"system_u:object_r:container_file_t:s0:c31,c1005\",\"ProcessLabel\":\"system_u:system_r:container_t:s0:c31,c1005\",\"AppArmorProfile\":\"\",\"EffectiveCaps\":null,\"BoundingCaps\":[\"CAP_CHOWN\",\"CAP_DAC_OVERRIDE\",\"CAP_FOWNER\",\"CAP_FSETID\",\"CAP_KILL\",\"CAP_NET_BIND_SERVICE\",\"CAP_SETFCAP\",\"CAP_SETGID\",\"CAP_SETPCAP\",\"CAP_SETUID\",\"CAP_SYS_CHROOT\"],\"ExecIDs\":[],\"GraphDriver\":{\"Name\":\"overlay\",\"Data\":{\"LowerDir\":\"/var/lib/containers/storage/overlay/5dff5d9b84f5cdc01fad01390e7ce0fb6b2d79bbe90ef8268d4415af0dd80036/diff:/var/lib/containers/storage/overlay/d1af8b3297395eced18d28ccc5632e68c62501d74ab6ab3b4644213076c1fb8d/diff:/var/lib/containers/storage/overlay/1b64658d08a36497e07ffd77855e68d13b98560cd7dd460f9f22f423e8e3f260/diff:/var/lib/containers/storage/overlay/c1c0a997df2e95dfd1dc121e7be62a541ed313a16898a7415721c17a6cb71e79/diff:/var/lib/containers/storage/overlay/4f0d1465334d802487d58cbfe1de2cc17a5e8895e1b1cd4d3735933aed572eed/diff:/var/lib/containers/storage/overlay/2f00aebaa51479c488d6f3bcde9c40034876f181141e53093e6fae55878b9585/diff:/var/lib/containers/storage/overlay/188ec29114bc26b161a0127849234c918b1175d6e2e63e672b191b8c0ecd5b83/diff:/var/lib/containers/storage/overlay/5b3f8cf89e17614b6b74f55e8e4b19ba5ba9ff6b020a4352c94d5e5759042702/diff:/var/lib/containers/storage/overlay/52dcf7cead613f0e46fa7dfba2fbc49dde8e220243f3c2303da755458c92be43/diff:/var/lib/containers/storage/overlay/27c5c0ce45ee9e84146eb6ff6312f2c30b8488e59b0cf317ac14ba308466b9db/diff:/var/lib/containers/storage/overlay/51efe96f9cb05b78634605bb4d2937abbb93b96a83a34714eb224ddcd7e220ae/diff:/var/lib/containers/storage/overlay/80fa62b2a000248513ce3dccb4e456bace4f3cfa586a2c77336443adbaab56ce/diff:/var/lib/containers/storage/overlay/332fd8fb1cacc804a38fbf63b57071fc8c507656f5611372ca46d5d27556abe2/diff:/var/lib/containers/storage/overlay/d0be04bf95588cf0ab03307cce24e7487c2edf5f4b7d2209c7301106608c7054/diff:/var/lib/containers/storage/overlay/7e02eaad2ba11307f6193f6228b257e658eac9cb5e3461a03734744f2b601171/diff\",\"UpperDir\":\"/var/lib/containers/storage/overlay/a3c1fa87fec315f504d5b1684c76d0cc4e4698db4893b72e2c6fd2ca86ef817b/diff\",\"WorkDir\":\"/var/lib/containers/storage/overlay/a3c1fa87fec315f504d5b1684c76d0cc4e4698db4893b72e2c6fd2ca86ef817b/work\"}},\"Mounts\":[],\"Dependencies\":[],\"NetworkSettings\":{\"EndpointID\":\"\",\"Gateway\":\"\",\"IPAddress\":\"\",\"IPPrefixLen\":0,\"IPv6Gateway\":\"\",\"GlobalIPv6Address\":\"\",\"GlobalIPv6PrefixLen\":0,\"MacAddress\":\"\",\"Bridge\":\"\",\"SandboxID\":\"\",\"HairpinMode\":false,\"LinkLocalIPv6Address\":\"\",\"LinkLocalIPv6PrefixLen\":0,\"Ports\":{},\"SandboxKey\":\"\",\"Networks\":{\"podman\":{\"EndpointID\":\"\",\"Gateway\":\"\",\"IPAddress\":\"\",\"IPPrefixLen\":0,\"IPv6Gateway\":\"\",\"GlobalIPv6Address\":\"\",\"GlobalIPv6PrefixLen\":0,\"MacAddress\":\"\",\"NetworkID\":\"podman\",\"DriverOpts\":null,\"IPAMConfig\":null,\"Links\":null,\"Aliases\":[\"c90ea29ea79f\"]}}},\"Namespace\":\"\",\"IsInfra\":false,\"IsService\":false,\"KubeExitCodePropagation\":\"invalid\",\"lockNumber\":0,\"Config\":{\"Hostname\":\"c90ea29ea79f\",\"Domainname\":\"\",\"User\":\"501:20\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"LANG=C\",\"JAVA_HOME=/opt/mandrel\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/mandrel/bin\",\"UPX_VERSION=3.96\",\"LC_ALL=en_US.UTF-8\",\"APP_HOME=/home/quarkus\",\"LANGUAGE=en_US:en\",\"container=oci\",\"GRAALVM_HOME=/opt/mandrel\"],\"Cmd\":[\"--version\"],\"Image\":\"quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21\",\"Volumes\":null,\"WorkingDir\":\"/project\",\"Entrypoint\":[\"native-image\"],\"OnBuild\":null,\"Labels\":{\"architecture\":\"x86_64\",\"build-date\":\"2024-09-17T13:42:02\",\"com.redhat.component\":\"ubi8-minimal-container\",\"com.redhat.license_terms\":\"https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI\",\"description\":\"The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.\",\"distribution-scope\":\"public\",\"io.buildah.version\":\"1.29.0\",\"io.k8s.description\":\"Quarkus.io executable image providing the `native-image` executable.\",\"io.k8s.display-name\":\"Quarkus.io executable (GraalVM Native, Mandrel distribution)\",\"io.openshift.expose-services\":\"\",\"io.openshift.tags\":\"executable,java,quarkus,mandrel,native\",\"maintainer\":\"Quarkus Team \\u003cquarkus-dev@googlegroups.com\\u003e\",\"name\":\"ubi8-minimal\",\"release\":\"1086\",\"summary\":\"Provides the latest release of the minimal Red Hat Universal Base Image 8.\",\"url\":\"https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8-minimal/images/8.10-1086\",\"vcs-ref\":\"4f8da2b64a13f2a264bd802d8909bf803211fb20\",\"vcs-type\":\"git\",\"vendor\":\"Red Hat, Inc.\",\"version\":\"8.10\"},\"Annotations\":{\"io.podman.annotations.autoremove\":\"TRUE\"},\"StopSignal\":\"SIGTERM\",\"HealthcheckOnFailureAction\":\"none\",\"CreateCommand\":[\"podman\",\"run\",\"--env\",\"LANG=C\",\"--rm\",\"--user\",\"501:20\",\"--rm\",\"quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21\",\"--version\"],\"Umask\":\"0022\",\"Timeout\":0,\"StopTimeout\":10,\"Passwd\":true,\"sdNotifyMode\":\"container\"},\"HostConfig\":{\"Binds\":[],\"CgroupManager\":\"systemd\",\"CgroupMode\":\"private\",\"ContainerIDFile\":\"\",\"LogConfig\":{\"Type\":\"journald\",\"Config\":null,\"Path\":\"\",\"Tag\":\"\",\"Size\":\"0B\"},\"NetworkMode\":\"bridge\",\"PortBindings\":{},\"RestartPolicy\":{\"Name\":\"\",\"MaximumRetryCount\":0},\"AutoRemove\":true,\"VolumeDriver\":\"\",\"VolumesFrom\":null,\"CapAdd\":[],\"CapDrop\":[],\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":[],\"GroupAdd\":[],\"IpcMode\":\"shareable\",\"Cgroup\":\"\",\"Cgroups\":\"default\",\"Links\":null,\"OomScoreAdj\":0,\"PidMode\":\"private\",\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"SecurityOpt\":[],\"Tmpfs\":{},\"UTSMode\":\"private\",\"UsernsMode\":\"\",\"ShmSize\":65536000,\"Runtime\":\"oci\",\"ConsoleSize\":[0,0],\"Isolation\":\"\",\"CpuShares\":0,\"Memory\":0,\"NanoCpus\":0,\"CgroupParent\":\"\",\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteIOps\":null,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"KernelMemory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":0,\"OomKillDisable\":false,\"PidsLimit\":2048,\"Ulimits\":[{\"Name\":\"RLIMIT_NPROC\",\"Soft\":4194304,\"Hard\":4194304}],\"CpuCount\":0,\"CpuPercent\":0,\"IOMaximumIOps\":0,\"IOMaximumBandwidth\":0,\"CgroupConf\":null}}\n": json: cannot unmarshal array into Go struct field InspectContainerConfig.Config.Entrypoint of type string
[ERROR] 	at io.quarkus.deployment.pkg.steps.GraalVM$Version.of(GraalVM.java:309)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildRunner.getGraalVMVersion(NativeImageBuildRunner.java:38)
[ERROR] 	... 11 more
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
❯ podman images
REPOSITORY                                         TAG             IMAGE ID      CREATED        SIZE
quay.io/quarkus/ubi-quarkus-mandrel-builder-image  jdk-21          7b2500f31c71  2 days ago     1.15 GB
```

**Comment by zakkak** [comment]
Hi @lordofthejars , this doesn't look like a Quarkus issue.

Can you please try running:

```
podman run --rm quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 --version
```

and report the output?

If it's not something like the following:

```
native-image 21.0.5 2024-10-15
OpenJDK Runtime Environment Mandrel-23.1.5.0-Final (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Mandrel-23.1.5.0-Final (build 21.0.5+11-LTS, mixed mode)
```

then there is some issue with the podman installation/configuration on your machine.

**Comment by zakkak** [comment]
The issue might be https://github.com/containers/podman/discussions/22531

What `podman` version are you using?

**Comment by lordofthejars** [comment]
It fauls too, so yes probably is a podman issue. Problem is that I cannot update podman version. Well, thanks for the info.
