### ISSUE TITLE
elytron-jdbc-security tests are unstable

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#4433]
**Describe the bug**
Fails in this [build](https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=9286&view=logs): 
```
[ERROR] Tests run: 14, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 1.018 s <<< FAILURE! - in io.quarkus.elytron.security.jdbc.MultipleDataSourcesTest
[ERROR] testJaxrsGetRoleSuccess  Time elapsed: 0.078 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```
No further clues are available in the rest of the trace.

@danielpetisme @stuartwdouglas can you please check if you have few secs ?
On my Fedora laptop it passes:
```
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.494 s - in io.quarkus.elytron.security.jdbc.MultipleDataSourcesTest
```

**Comment by sberyozkin** [comment]
Let me rebase again and see if it helps

**Comment by sberyozkin** [comment]
No, they are still failing on Windows, different test this time:
```
[ERROR] Tests run: 14, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 7.79 s <<< FAILURE! - in io.quarkus.elytron.security.jdbc.BcryptPasswordMapperTest
[ERROR] testJaxrsGetDenyAllWithAuth  Time elapsed: 0.094 s  <<< FAILURE!
```
`MultipleDataSourcesTest` which was failing earlier is passing

**Comment by sberyozkin** [comment]
Looks like it was failing for my PR only, the tests are green now, sorry about the noise

**Comment by gastaldi** [comment]
I still see them failing in my Windows box, I'll investigate

**Comment by gsmet** [comment]
Marked as invalid for now. Feel free to reopen and remove the label if needed.

**Comment by gsmet** [comment]
I'm reopening it: the Windows tests on CI are red because of this extension.

Please let's get a fix quickly as we need to fix that for tomorrow's release.

/cc @stuartwdouglas

**Comment by gastaldi** [comment]
I'm seeing the following errors while debugging the `BcryptPasswordMapperTest` in my Windows machine (not sure if it's related): 

```java
Caused by: org.h2.jdbc.JdbcSQLException: Table "TEST_USER" already exists; SQL statement:
CREATE TABLE test_user (
  id INT,
  username VARCHAR(255),
  password_hash VARCHAR(255),
  salt VARCHAR(255),
  iteration_count INT,
  role VARCHAR(255)
) [42101-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:86)
	at org.h2.command.dml.RunScriptCommand.execute(RunScriptCommand.java:79)
	at org.h2.command.dml.RunScriptCommand.update(RunScriptCommand.java:58)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.engine.Engine.openSession(Engine.java:227)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:200)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:370)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:352)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gastaldi** [comment]
Yes, that was the problem, I'll provide a PR shortly

**Comment by danielpetisme** [comment]
Do the test are properly isolated on Windows ? (Normally the datasource connection string defines different schemas...).
The quick and dirty solution would be to add `drop table` statements before creating tables.

**Comment by gastaldi** [comment]
@danielpetisme yes, the solution is to perform a `DROP TABLE IF EXISTS`. I have created a PR in 
https://github.com/quarkusio/quarkus/pull/4449

**Comment by danielpetisme** [comment]
What I don't understand is why it fails only on Windows?
There is a deeper problem because the tests isolated. Normally each suite has its own schema...
