### ISSUE TITLE
gRPC Bearer Token Authentication

### ISSUE THREAD

**Issue by jonsnowseven** [quarkusio/quarkus#44414]
Hello 👋 

I have a GrpcService and I am trying to implement authentication using a bearer token.

```java
@Authenticated
@GrpcService
public class ...
```

and

```java
@ApplicationScoped
public class GrpcAuthNValidator implements GrpcSecurityMechanism {
  private static final Metadata.Key<String> AUTHORIZATION =
      Metadata.Key.of("Authorization", Metadata.ASCII_STRING_MARSHALLER);

  private static final String bearerTokenPrefix = "Bearer";

  @Override
  public AuthenticationRequest createAuthenticationRequest(Metadata metadata) {
    String authString = metadata.get(AUTHORIZATION);
    if (authString != null && authString.startsWith(bearerTokenPrefix)) {
      String token = authString.substring((bearerTokenPrefix + " ").length());
      return new TokenAuthenticationRequest(new TokenCredential(token, bearerTokenPrefix));
    } else {
      throw new UnauthorizedException("Token not found");
    }
  } 
}
```

Although, when I run this Quarkus application I get the this following error:

```
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at mypackage.Main.main(Main.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.vertx.http.runtime.CurrentVertxRequest, id=0_6n6EmChCiiDdd8HelptG_A0AE]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:70)
	at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:30)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.getOtherHttpContextObject(Unknown Source)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusCurrentRequest.get(QuarkusCurrentRequest.java:21)
	at org.jboss.resteasy.reactive.server.core.CurrentRequestManager.get(CurrentRequestManager.java:8)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:39)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_AuthenticatedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at mypackage.MyClass_Subclass.bindService(Unknown Source)
	at io.quarkus.grpc.runtime.GrpcServerRecorder.collectServiceDefinitions(GrpcServerRecorder.java:383)
	at io.quarkus.grpc.runtime.GrpcServerRecorder.buildGrpcServer(GrpcServerRecorder.java:158)
	at io.quarkus.grpc.runtime.GrpcServerRecorder.initializeGrpcServer(GrpcServerRecorder.java:138)
	at io.quarkus.deployment.steps.GrpcServerProcessor$initializeServer760746362.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.GrpcServerProcessor$initializeServer760746362.deploy(Unknown Source)
	... 12 more
","errorType":"java.lang.RuntimeException","errorMessage":"Failed to start quarkus","logContext":"stdout","millis":1731325997337,"exception":"java.lang.RuntimeException: Failed to start quarkus
```

If I remove the `@Authenticated` annotation, the application executes successfully.

My questions are:

* Do I need the `@Authenticated` annotation in order for `GrpcSecurityMechanism` to work?
* If so, how can I resolve the `ContextNotActiveException`?

Thank you in advance!

**Comment by michalvavrik** [comment]
Regarding thrown exception and the stacktrace: It seems to be like security check is invoked when it shouldn't. I suppose this can be fixed in Quarkus REST by checking for CDI request context. @jonsnowseven context you provided is too little because I'll have to do bit of guessing. Would it be too difficult to provide a reproducer? if so, please share at least full grpc service class and also Quarkus extensions you use, like Quarkus REST etc. Thanks

> [@michalvavrik](https://github.com/michalvavrik) Hi Michal, I recall you were adding a test to confirm it was working, correct ?

@jonsnowseven is using his own `GrpcSecurityMechanism` so we cannot have test that some custom mechanism is working. What you can do is to use supported way of doing that: https://quarkus.io/guides/grpc-service-implementation#add-the-quarkus-security-extension and for that we have test: 

https://github.com/quarkusio/quarkus/blob/7a6b0eea9b844576ccfeca163aeff00e3d15c4c5/integration-tests/oidc-wiremock/src/test/java/io/quarkus/it/keycloak/BearerTokenAuthorizationTest.java#L666

**Comment by michalvavrik** [comment]
I just realized the "jon snow" nickname, yeah winter is coming, I am sitting here in parka and cap :-)

**Comment by sberyozkin** [comment]
@michalvavrik Thanks, my understanding is that @jonsnowseven is using a custom GrpcSecurityMechanism to allow bearer tokens but if it works out pf the box already with `quarkus-security` then it should not be necessary, @jonsnowseven, can you please check the link from @michalvavrik ? (The issue if any with custom GRPC mechanisms causing the exception should be fixed but hopefully the specific usecase is already supported)

**Comment by michalvavrik** [comment]
So regarding questions:

>  Do I need the @Authenticated annotation in order for GrpcSecurityMechanism to work?

You need `@Authenticated` to enforce authentication.

> If so, how can I resolve the ContextNotActiveException?

I don't think you need to. It seems to be a bug when grpc is used with Quarkus REST. I only added test for grpc and resteasy, so I think it needs trivial tweak on our side.

> @michalvavrik Thanks, my understanding is that @jonsnowseven is using a custom GrpcSecurityMechanism to allow bearer tokens but if it works out of the box already with quarkus-security then it should not be necessary, 

exactly; though I don't say his way is wrong, just not something we test for the bearer token auth

> @jonsnowseven, can you please check the link from @michalvavrik ? (The issue if any with custom GRPC mechanisms causing the exception should be fixed but hopefully the specific usecase is already supported)

I think the issue is in `io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor` and I probably even know how to fix it. But it would be really better if I got a reproducer or more info because it will save me time on creating a reproducer. Hope I am not wrong :-)

**Comment by michalvavrik** [comment]
So, it seems like `io.quarkus.grpc.deployment.GrpcPostProcessing#BIND_METHOD` is secured as well and for that reason, we only support security annotations on method level.

Hello @cescoffier , I think right now, you can only use standard security annotations on grpc service methods and not the class itself (because when `bindService` is invoked, there will be no security identity. We can:

1.  exclude `bindService` (and possibly others? I don't know if there are other methods that should be ignored)
2. validate and fail build with explanative exception that `@RolesAllowed` etc. should be placed on methods

Generally, I don't like adding exceptions like `bindService` and I'd prefer to add `2.`, but if you think `1.` should be implemented, I can have a look into it. It will require some new build items in Quarkus Security or maybe just annotation transformer.

**Comment by jonsnowseven** [comment]
Thank you for the quick replies!

@michalvavrik and @sberyozkin , sorry I did not notice that `quarkus-security` already supported Bearer Token validation. If that is the case, I don't need a `GrpcSecurityMechanism` implementation. Hence, I don't get the `ContextNotActiveException` anymore.

My following question would be, which parameters do I need to configure to correctly validate the token against the issuer? I just need `quarkus.oidc.auth-server-url`, right?

**Comment by michalvavrik** [comment]
> Thank you for the quick replies!

Thanks for bringing this out.

> [@michalvavrik](https://github.com/michalvavrik) and [@sberyozkin](https://github.com/sberyozkin) , sorry I did not notice that `quarkus-security` already supported Bearer Token validation. If that is the case, I don't need a `GrpcSecurityMechanism` implementation. Hence, I don't get the `ContextNotActiveException` anymore.

You can move `@Authenticated` from the class level to the method that you actually want to secure and it will work even with `GrpcSecurityMechanism`.

> My following question would be, which parameters do I need to configure to correctly validate the token against the issuer? I just need `quarkus.oidc.auth-server-url`, right?

You will need to follow guide and figure it out:

-  https://quarkus.io/guides/security-oidc-bearer-token-authentication-tutorial 
- https://quarkus.io/guides/security-oidc-bearer-token-authentication

**Comment by jonsnowseven** [comment]
Everything is working now 👌 
Thanks for all the help @michalvavrik and @sberyozkin!

**Comment by jonsnowseven** [comment]
Everything is working now 👌 
Thanks for all the help @michalvavrik and @sberyozkin!

**Comment by jonsnowseven** [comment]
@michalvavrik, sorry, one additional question.

Is there a way to do conditional annotations? I am asking so that we can easily disable the `@Autenticated` annotation in gRPC service

**Comment by michalvavrik** [comment]
> [@michalvavrik](https://github.com/michalvavrik), sorry, one additional question.
> 
> Is there a way to do conditional annotations? I am asking so that we can easily disable the `@Authenticated` annotation in gRPC service

You can disable authorization in DEV mode `quarkus.security.auth.enabled-in-dev-mode` or in tests https://quarkus.io/guides/security-testing#testing-security but in a production environment, it must not be possible. I suggest to look into https://quarkus.io/guides/security-authorize-web-endpoints-reference#authorization-using-configuration. You can only authorize certain paths if you use same gRPC server.

This is not a right platform for questions though, please refer to the https://quarkus.io/support/, I cannot help here.

**Comment by michalvavrik** [comment]
We need to improve user experience. Please keep this open, I'll close it myself when I address it.

**Comment by jonsnowseven** [comment]
So I can't use `quarkus.security.auth.enabled-in-dev-mode=false` in one environment (e.g., QA) and `quarkus.security.auth.enabled-in-dev-mode=true` in another (e.g., PROD)?

**Comment by jonsnowseven** [comment]
Or is there a simple workaround, @michalvavrik?

**Comment by michalvavrik** [comment]
> Or is there a simple workaround, [@michalvavrik](https://github.com/michalvavrik)?

I'd prefer if you ask in one of suggested channels https://quarkus.io/support/ so that others can profit from the topic as well. Noone will find it here. Nevertheless:

> So I can't use quarkus.security.auth.enabled-in-dev-mode=false in one environment (e.g., QA) and quarkus.security.auth.enabled-in-dev-mode=true in another (e.g., PROD)?

If what you want is entirely disable authorization, follow this docs section https://quarkus.io/guides/security-customization#disabling-authorization.

**Comment by cescoffier** [comment]
@michalvavrik Did you work on this one?

**Comment by michalvavrik** [comment]
> [@michalvavrik](https://github.com/michalvavrik) Did you work on this one?

It's among hundred of links I plan to pay attention eventually :-). I'll put this on top and address it in 7 days. Thanks for the reminder.
