### ISSUE TITLE
Quarkus-rest-jaxb deserializing XML content will result in deserialisation ambiguity

### ISSUE THREAD

**Issue by mmiccoli** [quarkusio/quarkus#44611]
### Describe the bug

I'm trying to migrate the Quarkus resteasy dependencies to rest (reactive).
My app needs accept SOAP server calls and perform SOAP client calls.

I'm currently facing an XML deserialization issue 

Now I have the following dependencies:
` 
<dependencies>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
            <version>3.15.1</version>
        </dependency>
       
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-jackson</artifactId>
            <version>3.15.1</version>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-jaxb</artifactId>
            <version>3.15.1</version>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-jaxb</artifactId>
            <version>3.15.1</version>
        </dependency>

        <dependency>
            <groupId>io.quarkiverse.cxf</groupId>
            <artifactId>quarkus-cxf</artifactId>
            <version>3.15.2</version>
        </dependency>

        <dependency>
            <groupId>io.quarkiverse.cxf</groupId>
            <artifactId>quarkus-cxf-rt-ws-security</artifactId>
            <version>3.15.2</version>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client</artifactId>
            <version>3.15.1</version>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-jackson</artifactId>
            <version>3.15.1</version>
        </dependency>
...
</dependencies>
`

### Expected behavior

The incoming SOAP messages should be deserialized.

### Actual behavior

At runtime when the app tries to deserialize an XML content it will throw those exceptions:

`
The element name {http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd}Expires has more than one mapping.
	this problem is related to the following location:
		at public jakarta.xml.bind.JAXBElement org.apache.wss4j.binding.wsu10.ObjectFactory.createExpires(org.apache.wss4j.binding.wsu10.AttributedDateTime)
		at org.apache.wss4j.binding.wsu10.ObjectFactory
	this problem is related to the following location:
		at public jakarta.xml.bind.JAXBElement org.apache.cxf.ws.security.sts.provider.model.utility.ObjectFactory.createExpires(org.apache.cxf.ws.security.sts.provider.model.utility.AttributedDateTime)
		at org.apache.cxf.ws.security.sts.provider.model.utility.ObjectFactory
		at protected java.util.List org.apache.cxf.ws.security.sts.provider.model.utility.TimestampType.any
		at org.apache.cxf.ws.security.sts.provider.model.utility.TimestampType
Two classes have the same XML type name "{http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd}AttributedURI". Use @XmlType.name and @XmlType.namespace to assign different names to them.
	this problem is related to the following location:
		at org.apache.cxf.ws.security.sts.provider.model.utility.AttributedURI
		at public org.apache.cxf.ws.security.sts.provider.model.utility.AttributedURI org.apache.cxf.ws.security.sts.provider.model.utility.ObjectFactory.createAttributedURI()
		at org.apache.cxf.ws.security.sts.provider.model.utility.ObjectFactory
		at protected java.util.List org.apache.cxf.ws.security.sts.provider.model.utility.TimestampType.any
		at org.apache.cxf.ws.security.sts.provider.model.utility.TimestampType
	this problem is related to the following location:
		at org.apache.wss4j.binding.wsu10.AttributedURI
		at public org.apache.wss4j.binding.wsu10.AttributedURI org.apache.wss4j.binding.wsu10.ObjectFactory.createAttributedURI()
		at org.apache.wss4j.binding.wsu10.ObjectFactory

Two classes have the same XML type name "{http://www.w3.org/2005/08/addressing}EndpointReferenceType". Use @XmlType.name and @XmlType.namespace to assign different names to them.
	this problem is related to the following location:
		at org.apache.cxf.ws.addressing.EndpointReferenceType
		at public jakarta.xml.bind.JAXBElement org.apache.cxf.ws.security.sts.provider.model.ObjectFactory.createIssuer(org.apache.cxf.ws.addressing.EndpointReferenceType)
		at org.apache.cxf.ws.security.sts.provider.model.ObjectFactory
		at protected java.util.List org.apache.cxf.ws.security.sts.provider.model.RequestSecurityTokenResponseType.any
		at org.apache.cxf.ws.security.sts.provider.model.RequestSecurityTokenResponseType
	this problem is related to the following location:
		at jakarta.xml.ws.wsaddressing.W3CEndpointReference

	at org.glassfish.jaxb.runtime.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:83)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:421)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:255)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1115)
	at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:144)
	at org.glassfish.jaxb.runtime.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:44)
	at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:373)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:605)
	at io.quarkus.jaxb.runtime.JaxbContextProducer.createJAXBContext(JaxbContextProducer.java:80)
	... 25 more
`

### How to Reproduce?

Reproducer:

- Add the dependencies described above to your Quarkus application.
- Build a SOAP endpoint
- Call this SOAP ![Image](https://github.com/user-attachments/assets/d0410f86-5a4f-4e80-91c2-d9724461cad1)
endpoint

### Output of `java -version`

21

### Quarkus version or git rev

3.15

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.9.2 (Maven)

**Comment by geoand** [comment]
I wonder if @ppalaga has any insights on this one

**Comment by ppalaga** [comment]
@mmiccoli thanks for the detailed report. This is a known problem in case you use Quarkus CXF in combination with `quarkus-rest-jaxb` and you inject the default `JAXBContext` somewhere in your app. There is some additional info in https://github.com/quarkusio/quarkus/issues/31646

To mitigate the issue you may need one or more of the following:

* Decide whether you need the default `JAXBContext` that suffers from this issue because it automatically includes all classes with JAXB annotations. A custom `JAXBContext` with small well defined set of classes included would perhaps work better for you?
* Exclude one or both (if you do not need them) classes of the conflicting pair from the default `JAXBContext` using `quarkus.jaxb.exclude-classes` - see https://quarkus.io/guides/rest#xml-serialisation
* If you are absolutely sure that you won't serialize/deserialize any of the conflicting classes in your `JAXBContext`, you may disable the validation altogether though `quarkus.jaxb.validate-jaxb-context=false`. This might be risky and I would not recommend this option.

**Comment by geoand** [comment]
Closing as per comments above
