### ISSUE TITLE
All but first test in a class fail if class is annotated @WithFunction

### ISSUE THREAD

**Issue by devopsix** [quarkusio/quarkus#44661]
### Describe the bug

Given a project which contains an implementation of a Google Cloud Run Function (`CloudEventsFunction` variant) which was created as shown in the [Google Cloud Functions (Serverless) guide](https://quarkus.io/guides/gcp-functions#creating-the-maven-deployment-project),

Add a test class to this project as shown in the [Testing your function section](https://quarkus.io/guides/gcp-functions#the-cloudeventsfunction-4) and add a second identical test is added to this test class,

When running tests, the second test in this class cannot be instantiated.

### Expected behavior

Both tests pass.

### Actual behavior

The first test passes, the second test fails.

```
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
        at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:773)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:739)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8081
        at io.quarkus.google.cloud.functions.test.CloudFunctionTestResource.inject(CloudFunctionTestResource.java:40)
        at io.quarkus.test.common.TestResourceManager.inject(TestResourceManager.java:201)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.test.junit.QuarkusTestExtension.createActualTestInstance(QuarkusTestExtension.java:784)
        at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:767)
        ... 4 more
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8081
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:324)
        at com.google.cloud.functions.invoker.runner.Invoker.startTestServer(Invoker.java:276)
        at io.quarkus.google.cloud.functions.test.CloudFunctionsInvoker.start(CloudFunctionsInvoker.java:26)
        at io.quarkus.google.cloud.functions.test.CloudFunctionTestResource.inject(CloudFunctionTestResource.java:38)
        ... 8 more
Caused by: java.net.BindException: Address already in use: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:565)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
        ... 18 more
```

### How to Reproduce?

https://github.com/devopsix/quarkus-google-cloud-functions-issue

### Output of `uname -a` or `ver`

n/a

### Output of `java -version`

openjdk version "21.0.5" 2024-10-15 LTS OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.16.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

### Additional information

Suspected cause: In [`CloudFunctionTestResource.inject(TestInjector)`](https://github.com/quarkusio/quarkus/blob/8df922d7f8a07ef97a73ba066f2496486140eb67/test-framework/google-cloud-functions/src/main/java/io/quarkus/google/cloud/functions/test/CloudFunctionTestResource.java#L32) a new invoker is started for each test without stopping an invoker created previously.

Potential remedy: Invokers should either be reused between tests or stopped after each test.

**Comment by geoand** [comment]
cc @patriot1burke
