### ISSUE TITLE
Cannot work with resources having spaces (apart from creating)

### ISSUE THREAD

**Issue by agustin-munoz** [quarkusio/quarkus#44769]
### Describe the bug

While working with resources having a space in its name it's not possible to manage them, except its creation.

When trying to access such resource an exception like this is thrown

```
2024-11-27 11:28:20,554 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:116)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:129)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:122)
	at io.fabric8.kubernetes.client.http.StandardHttpRequest$Builder.url(StandardHttpRequest.java:229)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleDelete(OperationSupport.java:318)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.deleteAll(BaseOperation.java:535)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.delete(BaseOperation.java:500)
	at com.example.Example.start(Example.java:22)
	at com.example.Example_Observer_start_mwmXcoYVWkrpQMQGCjbJb5-4UAU.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:156)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:107)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 11 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 130: https://api.example.com:6443/apis/policy/v1/namespaces/default/poddisruptionbudgets/hello world
	at java.base/java.net.URI$Parser.fail(URI.java:2995)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3166)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3248)
	at java.base/java.net.URI$Parser.parse(URI.java:3196)
	at java.base/java.net.URI.<init>(URI.java:645)
	at java.base/java.net.URL.toURI(URL.java:1220)
	at io.fabric8.kubernetes.client.http.StandardHttpRequest$Builder.url(StandardHttpRequest.java:227)
	... 23 more

2024-11-27 11:28:20,564 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (Quarkus Terminal Reader) Failed to start quarkus: io.quarkus.dev.appstate.ApplicationStartException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:63)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:142)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:204)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:185)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:555)
	at io.quarkus.deployment.console.ConsoleStateManager.forceRestart(ConsoleStateManager.java:175)
	at io.quarkus.deployment.console.ConsoleStateManager.lambda$installBuiltins$0(ConsoleStateManager.java:112)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:77)
	at io.quarkus.deployment.console.ConsoleStateManager$1.accept(ConsoleStateManager.java:49)
	at io.quarkus.dev.console.BasicConsole$2.run(BasicConsole.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:116)
	... 1 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:129)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:122)
	at io.fabric8.kubernetes.client.http.StandardHttpRequest$Builder.url(StandardHttpRequest.java:229)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleDelete(OperationSupport.java:318)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.deleteAll(BaseOperation.java:535)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.delete(BaseOperation.java:500)
	at com.example.Example.start(Example.java:22)
	at com.example.Example_Observer_start_mwmXcoYVWkrpQMQGCjbJb5-4UAU.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:156)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:107)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 11 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 130: https://api.example.com:6443/apis/policy/v1/namespaces/default/poddisruptionbudgets/hello world
	at java.base/java.net.URI$Parser.fail(URI.java:2995)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3166)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3248)
	at java.base/java.net.URI$Parser.parse(URI.java:3196)
	at java.base/java.net.URI.<init>(URI.java:645)
	at java.base/java.net.URL.toURI(URL.java:1220)
	at io.fabric8.kubernetes.client.http.StandardHttpRequest$Builder.url(StandardHttpRequest.java:227)
	... 23 more
```

Seems like in the code it is not trying to encode URL leading to this problem.

### Expected behavior

Being able to get, delete and update a resource with spaces in the name.

### How to Reproduce?

Use this code in a project with kubernetes-client

```java
package com.example;

import io.fabric8.kubernetes.api.model.ConfigMapBuilder;
import io.fabric8.kubernetes.api.model.policy.v1.PodDisruptionBudgetBuilder;
import io.fabric8.kubernetes.client.KubernetesClient;
import io.quarkus.runtime.StartupEvent;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;
import jakarta.inject.Inject;

import java.util.Map;

@ApplicationScoped
public class Example {

    @Inject
    KubernetesClient k;

    public void start(@Observes StartupEvent event) {
        System.out.println("Hello, Quarkus!");
        var pdb = new PodDisruptionBudgetBuilder().withNewMetadata().withName("hello world").endMetadata().build();
        k.resource(pdb).inNamespace("default").create();
        pdb = k.resource(pdb).inNamespace("default").get();
        System.out.println(pdb.getMetadata().getName());
        pdb.getMetadata().setLabels(Map.of("foo", "bar"));
        k.resource(pdb).inNamespace("default").update();
    }

}
```

### Quarkus version or git rev

3.15.2

**Comment by agustin-munoz** [comment]
And I agree, just found out our controller was not able to work, because it can not update 2 resources created by customers with spaces.

As example:

```
$ kubectl get pdb -n default "hello world" --loglevel 6
I1127 16:06:20.310303  264065 loader.go:373] Config loaded from file:  ~/.kube/config
I1127 16:06:20.344892  264065 round_trippers.go:553] GET https://api.example.com:6443/api?timeout=32s 200 OK in 30 milliseconds
I1127 16:06:20.351183  264065 round_trippers.go:553] GET https://api.example.com:6443/apis?timeout=32s 200 OK in 5 milliseconds
I1127 16:06:20.385570  264065 cached_discovery.go:88] skipped caching discovery info, no resources found
I1127 16:06:20.389209  264065 cached_discovery.go:88] skipped caching discovery info, no resources found
I1127 16:06:20.392513  264065 cached_discovery.go:88] skipped caching discovery info, no resources found
I1127 16:06:20.399114  264065 round_trippers.go:553] GET https://api.example.com:6443/apis/policy/v1/namespaces/default/poddisruptionbudgets/hello%20world 200 OK in 4 milliseconds
NAME          MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
hello world   N/A             N/A               0                     5h45m
```

Kubectl is able to get the resource by using "hello%20world" in the url, that was also unexpected on my side, a strange corner case.

**Comment by manusa** [comment]
I'd understand that kubectl url-encodes the names, however, I wouldn't advise to allow this.

What's surprising for me is not that kubectl  can retrieve the resource, but that the cluster allows for its creation. I'd expect kubernetes to return a client error when trying to POST (create) a resource with this name. Was this resource created in a real cluster?

**Comment by agustin-munoz** [comment]
Yes, that resource was created on a real cluster (Openshift 4.14.37 with Kubernetes v1.27.16).

With many Kinds, trying to create the resource with a name having a space simply does not work, and an error like this is shown to user:

> Error "Invalid value: "example pod": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')" for field "metadata.name"

But for example it is allowing it for PodDisruptionBudget, also some other known (to me) examples:
* Identity in user.openshift.io
* Group in user.openshift.io (just reviewing I found a Group with fancy names like **a | b**, **a @ äöéà?^ b** (I guess some test from any of my colleagues)

So looks like this is an exception, not sure if happening only in Openshift, or also on Kubernetes cluster.

**Comment by manusa** [comment]
> and an error like this is shown to user:

This is what I'd expect

> But for example it is allowing it for PodDisruptionBudget, also some other known (to me) examples:

For the last couple of weeks I've been refactoring the Fabric8 Kubernetes Client model generation and found many inconsistencies in upstream projects that had been there for years which led me to open multiple PRs. In the end, I found so many issues that I had to implement some workarounds in the generator itself.

I understand that the explanation for this might be in the `PodDisruptionBudget` controller and not performing any sort of basic input validation.

For example, this snippet validates that a `Pod` is correct:

https://github.com/kubernetes/kubernetes/blob/95d71c464a6a5f81ae36bddc86972b3b2a1c40a5/pkg/apis/core/validation/validation.go#L4061-L4066

However, this snippet to validate a `PodDisruptionBudget` is clearly missing validation for `ObjectMeta`, which (unless I missed something) I guess is what explains the situation and probably allows for any kind of crazy stuff in the resource's metadata:

https://github.com/kubernetes/kubernetes/blob/95d71c464a6a5f81ae36bddc86972b3b2a1c40a5/pkg/apis/policy/validation/validation.go#L43-L46

I'd suggest to open an upstream issue with your reproducer.

**Comment by agustin-munoz** [comment]
Thanks for pointing it out.

That was interesting to see how for example [Deployment|https://github.com/kubernetes/kubernetes/blob/95d71c464a6a5f81ae36bddc86972b3b2a1c40a5/pkg/apis/apps/validation/validation.go#L651-L655] calls apivalidation.ValidateObjectMeta or [NetworkPolicy|https://github.com/kubernetes/kubernetes/blob/95d71c464a6a5f81ae36bddc86972b3b2a1c40a5/pkg/apis/networking/validation/validation.go#L186C1-L190C1].

I guess we will need to setup a simple ValidatingWebhook for PodDisruptionBudget to check correctness of its metadata.name

**Comment by atiratree** [comment]
> However, this snippet to validate a PodDisruptionBudget is clearly missing validation for ObjectMeta, which (unless I missed something) I guess is what explains the situation and probably allows for any kind of crazy stuff in the resource's metadata:

There is a fallback validation, so the metadata is still validated. The name validation is relaxed and valid path segment is expected: https://github.com/kubernetes/kubernetes/blob/810e9e212ec5372d16b655f57b9231d8654a2179/staging/src/k8s.io/apiserver/pkg/registry/rest/create.go#L126-L131 

It is unlikely that the k8s upstream will accept strengthening the validation.

I am not familiar with the use case, but do you manage these PDBs? Can you add additional validation on the client side?

> I guess we will need to setup a simple ValidatingWebhook for PodDisruptionBudget to check correctness of its metadata.name

I would try to avoid such a solution. And if necessary, I would only target the PDBs you manage - so as not to break existing PDBs and other actors in the cluster.

**Comment by agustin-munoz** [comment]
Hello @atiratree 

Actually we have a mutating webhook as we provide for our users a feature to declare a timeframe, so in that timeframe we can take ownership of PDB to allow some disruption.

Currently we are working on reporting to users having those invalid names and lately add a validation, so PDBs with such names cannot be declared.
