### ISSUE TITLE
Redis JsonCodec use ObjectMapper without jsr310

### ISSUE THREAD

**Issue by RoMiRoSSaN** [quarkusio/quarkus#44934]
### Describe the bug

JsonCodec use ObjectMapper from DatabindCodec.mapper(). Received mapper contains only io.vertx.core.json.jackson.VertxModule.
https://github.com/quarkusio/quarkus/blob/main/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/datasource/codecs/Codecs.java#L64

As a result, if a list of objects is cached that contains a date/time, when trying to deserialize it, an exception is thrown that there is no jsr310 module.

ObjectMapper in Arc contains next modules by default
- VertxTypes
- jackson-datatype-jsr310
- com.fasterxml.jackson.datatype.jdk8.Jdk8Module
- jackson-module-parameter-names

How it can be fixed:
1. Call findAndRegisterModules
`this.mapper = DatabindCodec.mapper().findAndRegisterModules()`
In this case, `findAndRegisterModules` will be called every time. The `VertxTypes` module will be missing.

2. Get ObjectMapper from Arc
`this.mapper = Arc.container().instance(ObjectMapper.class).orElse(DatabindCodec.mapper())`
In this case, the `io.vertx.core.json.jackson.VertxModule` module will be missing.

I think the first option is more correct, since there may be places where the ObjectMapper from `DatabindCodec` is used. And enriching it with the jsr310 module will not be superfluous. And put it in a static field so as not to call `findAndRegisterModules` every time.
But here you know better.

### Expected behavior

Can cached list of objects this date/time

### Actual behavior

Thrown exception
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 19] (through reference chain: java.util.ArrayList[0]->org.example.Item["localDateTime"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1888)
	at com.fasterxml.jackson.databind.deser.impl.UnsupportedTypeDeserializer.deserialize(UnsupportedTypeDeserializer.java:48)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:246)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4917)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3938)
	at io.quarkus.redis.datasource.codecs.Codecs$JsonCodec.decode(Codecs.java:83)
	... 25 more
```

### How to Reproduce?

[redis-demo.zip](https://github.com/user-attachments/files/18021561/redis-demo.zip)

### Quarkus version or git rev

3.17.3

**Comment by Ladicek** [comment]
I'm honestly surprised we don't use the `ObjectMapper` from CDI by default. There might be a need for customization, but we should default to the Quarkus global instance IMHO.

**Comment by geoand** [comment]
I'll take care of this
