### ISSUE TITLE
[JDK 24] Quarkus native integration tests fail with latest GraalVM CE (ea), JDK 24+27

### ISSUE THREAD

**Issue by jerboaa** [quarkusio/quarkus#45062]
In Mandrel CI we see all Quarkus native CI tests fail due to this issue:

```
========================================================================================================================
GraalVM Native Image: Generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------

[1/8] Initializing...                                                                                    (0.0s @ 0.25GB)
Error: Could not find target method: public static com.oracle.svm.core.foreign.Target_jdk_internal_foreign_abi_NativeEntryPoint com.oracle.svm.core.foreign.Target_jdk_internal_foreign_abi_NativeEntryPoint.make(jdk.internal.foreign.abi.ABIDescriptor,jdk.internal.foreign.abi.VMStorage[],jdk.internal.foreign.abi.VMStorage[],java.lang.invoke.MethodType,boolean,int,boolean)
Internal exception: com.oracle.svm.core.util.UserError$UserException: Could not find target method: public static com.oracle.svm.core.foreign.Target_jdk_internal_foreign_abi_NativeEntryPoint com.oracle.svm.core.foreign.Target_jdk_internal_foreign_abi_NativeEntryPoint.make(jdk.internal.foreign.abi.ABIDescriptor,jdk.internal.foreign.abi.VMStorage[],jdk.internal.foreign.abi.VMStorage[],java.lang.invoke.MethodType,boolean,int,boolean)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:872)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAnnotatedMethodInSubstitutionClass(AnnotationSubstitutionProcessor.java:753)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleSubstitutionClass(AnnotationSubstitutionProcessor.java:700)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:359)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:315)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:1131)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:976)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:565)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:533)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:545)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:731)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:151)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:99)
```

I think it's because quarkus native turns on `-H:+ForeignAPISupport`. It seems specific to the latest `24+27` JDK.

**Comment by jerboaa** [comment]
See: https://github.com/graalvm/mandrel/actions/runs/12267304372/job/34228196960#step:12:424

**Comment by Karm** [comment]
`-H:+ForeignAPISupport`
On as of https://github.com/quarkusio/quarkus/pull/44092

**Comment by zakkak** [comment]
This is caused by https://github.com/oracle/graal/issues/10304

**Comment by jerboaa** [comment]
> This is caused by https://github.com/oracle/graal/issues/10304

master branch is fixed (JDK 25 ea). I think we'll see it fail again on JDK 24 ea (which now runs weekly) as I don't see it backported to JDK 24 yet.

**Comment by zakkak** [comment]
> > This is caused by [oracle/graal#10304](https://github.com/oracle/graal/issues/10304)
> 
> master branch is fixed (JDK 25 ea). I think we'll see it fail again on JDK 24 ea (which now runs weekly) as I don't see it backported to JDK 24 yet.

The fix is now backported to the 24.2 branch and the issue no longer manifests.
