### ISSUE TITLE
Enabling system properties in test as in -Dprop=value prevents QuarkusTestComponent initialization

### ISSUE THREAD

**Issue by laurentperez** [quarkusio/quarkus#45089]
### Describe the bug

Hi

Context : I want to read system properties in a ./gradlew test. I set them as `-Dprop=value.`

In my `build.gradle.kts` I set in addition to Jboss logger the whole properties map, otherwise, the map of properties would not contain my prop when run under a test : 

```
tasks.withType<Test> {
     systemProperty("java.util.logging.manager", "org.jboss.logmanager.LogManager")
     systemProperties(System.getProperties().mapKeys { it.key.toString() })
     systemProperty("java.util.logging.manager", "org.jboss.logmanager.LogManager")
}
```

Setting the second line, the one with the map, makes every test annotated with `@QuarkusComponentTest` fail and throw (1)

Removing the line, the @QuarkusComponentTest tests pass, but then my -Dprop=value is not set.

It works If I use a case-by-case definition of properties : 

```
tasks.withType<Test> {
     systemProperty("java.util.logging.manager", "org.jboss.logmanager.LogManager")
systemProperty("prop", System.getProperty("prop"))
}
```

(1)

```
java.util.ServiceConfigurationError: io.quarkus.arc.ComponentsProvider: Error accessing configuration file
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1180)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1213)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:127)
	at io.quarkus.arc.Arc.initialize(Arc.java:38)
	at io.quarkus.arc.Arc.initialize(Arc.java:22)
	at io.quarkus.test.component.QuarkusComponentTestExtension.startContainer(QuarkusComponentTestExtension.java:418)
	at io.quarkus.test.component.QuarkusComponentTestExtension.beforeEach(QuarkusComponentTestExtension.java:236)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.lang.NullPointerException: Cannot invoke "io.quarkus.arc.ArcContainer.requestContext()" because the return value of "io.quarkus.arc.Arc.container()" is null
		at io.quarkus.test.component.QuarkusComponentTestExtension.afterEach(QuarkusComponentTestExtension.java:246)
		... 2 more
Caused by: java.io.FileNotFoundException: /home/lperez/Bureau/work/cap1pact/build/generated-arc-sources/com/xxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxx/ComponentsProvider (Aucun fichier ou dossier de ce nom)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:84)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:180)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1172)
	... 12 more
```

### Output of `java -version`

21

### Quarkus version or git rev

3.16.4 or 3.17.4

**Comment by geoand** [comment]
cc @mkouba @radcortez

**Comment by mkouba** [comment]
@laurentperez Could you add a breakpoint in `QuarkusComponentTestExtension#startContainer()`  and verify that the service provider file `/home/lperez/Bureau/work/cap1pact/build/generated-arc-sources/com/xxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxx/ComponentsProvider` actually exists?

**Comment by geoand** [comment]
Closing for lack of feedback
