### ISSUE TITLE
Unwanted AWT stack traces in native AWT packaging tests

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus#45107]
In `main` CI, the `awt-packaging` project is spitting out stack traces. The build is green, so they're somewhat harmless, but they're not ideal in two ways:
- Is there actually something wrong with our AWT support that these stack traces are a symptom of?
- Even if not, they make it harder to diagnose problems in the `awt-packaging` project, by adding noise

This is the error:

```
2024-12-12T19:45:47.6903648Z 2024-12-12 19:45:47,637 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /graphics?entrypoint=IIORegistry failed, error id: e407bdc7-362e-4a69-a444-c068d028e803-1: org.jboss.resteasy.spi.UnhandledException: java.lang.UnsupportedOperationException: Add AWT Quarkus extension to enable Java2D/ImageIO. Additional system libraries such as `freetype' and `fontconfig' might be needed.
2024-12-12T19:45:47.6907890Z 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:107)
2024-12-12T19:45:47.6966054Z 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:344)
2024-12-12T19:45:47.6967455Z 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:205)
2024-12-12T19:45:47.6968670Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:452)
2024-12-12T19:45:47.6969991Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invokePropagateNotFound$6(SynchronousDispatcher.java:275)
2024-12-12T19:45:47.6971387Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
2024-12-12T19:45:47.6973022Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
2024-12-12T19:45:47.6974515Z 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
2024-12-12T19:45:47.6975925Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invokePropagateNotFound(SynchronousDispatcher.java:260)
2024-12-12T19:45:47.6977276Z 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:86)
2024-12-12T19:45:47.6978639Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
2024-12-12T19:45:47.6979961Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:97)
2024-12-12T19:45:47.6981230Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:637)
2024-12-12T19:45:47.6982410Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
2024-12-12T19:45:47.6983582Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
2024-12-12T19:45:47.6985109Z 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
2024-12-12T19:45:47.6986599Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
2024-12-12T19:45:47.6987665Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
2024-12-12T19:45:47.6988808Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
2024-12-12T19:45:47.6990009Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-12-12T19:45:47.6991079Z 	at java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596)
2024-12-12T19:45:47.6991955Z 	at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)
2024-12-12T19:45:47.6993104Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
2024-12-12T19:45:47.6994666Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
2024-12-12T19:45:47.6996508Z Caused by: java.lang.UnsupportedOperationException: Add AWT Quarkus extension to enable Java2D/ImageIO. Additional system libraries such as `freetype' and `fontconfig' might be needed.
2024-12-12T19:45:47.6998150Z 	at java.desktop@21.0.5/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:74)
2024-12-12T19:45:47.6999166Z 	at io.quarkus.awt.it.GraphicsResource.graphics(GraphicsResource.java:37)
2024-12-12T19:45:47.7000004Z 	at java.base@21.0.5/java.lang.reflect.Method.invoke(Method.java:580)
2024-12-12T19:45:47.7000898Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
2024-12-12T19:45:47.7001897Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
2024-12-12T19:45:47.7003418Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
2024-12-12T19:45:47.7004896Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
2024-12-12T19:45:47.7006218Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
2024-12-12T19:45:47.7007702Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
2024-12-12T19:45:47.7009444Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
2024-12-12T19:45:47.7010616Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
2024-12-12T19:45:47.7011708Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
2024-12-12T19:45:47.7012786Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
2024-12-12T19:45:47.7013825Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
2024-12-12T19:45:47.7014535Z 	... 20 more
2024-12-12T19:45:47.7014709Z 
2024-12-12T19:45:47.7901921Z HTTP/1.1 500 Internal Server Error
2024-12-12T19:45:47.7902499Z content-type: application/json; charset=utf-8
2024-12-12T19:45:47.7902992Z content-length: 72
2024-12-12T19:45:47.7903200Z 
2024-12-12T19:45:47.7903325Z {
2024-12-12T19:45:47.7903722Z     "details": "Error id e407bdc7-362e-4a69-a444-c068d028e803-1",
2024-12-12T19:45:47.7904247Z     "stack": ""
2024-12-12T19:45:47.7904554Z }
```

Here's an example [run](https://github.com/quarkusio/quarkus/actions/runs/12301973708/job/34336811586) and [log](https://productionresultssa12.blob.core.windows.net/actions-results/a16c33e4-4140-4649-b469-17079030a254/workflow-job-run-7d0019ba-641e-5b68-88f9-b1a442eb20f3/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-12-13T04%3A25%3A07Z&sig=MMuDNYOLF%2FRHLh9pu%2FOKoADHEx880USJw725dUqipbo%3D&ske=2024-12-13T14%3A57%3A30Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-12-13T02%3A57%3A30Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-11-04&sp=r&spr=https&sr=b&st=2024-12-13T04%3A15%3A02Z&sv=2024-11-04) showing the issue. I think it's pretty reproducible.

In the same log, there are also other stack traces relating to image support. 

```
2024-12-12T19:40:03.5369169Z 2024-12-12 19:40:03,498 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /topng/weird_1000.jpg failed, error id: 5320ce64-57c1-4de4-b69d-4af67b5d018f-1: org.jboss.resteasy.spi.UnhandledException: javax.imageio.IIOException: Bogus Huffman table definition
...
2024-12-12T19:40:03.5429465Z Caused by: javax.imageio.IIOException: Bogus Huffman table definition
2024-12-12T19:40:03.5431048Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
2024-12-12T19:40:03.5432922Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:907)
2024-12-12T19:40:03.5434898Z 	at java.desktop@21.0.5/com.sun.imageio.plugins.jpeg.JPEGImageReader.readImage(Native Method)
2024-12-12T19:40:03.5436348Z 	at java.desktop@21.0.5/com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1378)
2024-12-12T19:40:03.5437979Z 	at java.desktop@21.0.5/com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1162)
2024-12-12T19:40:03.5439212Z 	at java.desktop@21.0.5/javax.imageio.ImageReader.readAll(ImageReader.java:1065)
```

```
2024-12-12T19:40:04.6515436Z 2024-12-12 19:40:04,556 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /topng/test_gray_to_k.jpg failed, error id: 5320ce64-57c1-4de4-b69d-4af67b5d018f-2: org.jboss.resteasy.spi.UnhandledException: java.awt.color.CMMException: LCMS error 13: LUT is not suitable to be saved as LutBToA
...
2024-12-12T19:40:04.6547527Z Caused by: java.awt.color.CMMException: LCMS error 13: LUT is not suitable to be saved as LutBToA
2024-12-12T19:40:04.6548880Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
2024-12-12T19:40:04.6550338Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:907)
2024-12-12T19:40:04.6551347Z 	at java.desktop@21.0.5/sun.java2d.cmm.lcms.LCMS.getProfileDataNative(Native Method)
2024-12-12T19:40:04.6552555Z 	at java.desktop@21.0.5/sun.java2d.cmm.lcms.LCMSProfile.getProfileData(LCMSProfile.java:52)
2024-12-12T19:40:04.6553382Z 	at java.desktop@21.0.5/sun.java2d.cmm.lcms.LCMS.getProfileData(LCMS.java:80)
```

```
2024-12-12T19:40:05.1388944Z 2024-12-12 19:40:05,069 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /topng/weird_230.bmp failed, error id: 5320ce64-57c1-4de4-b69d-4af67b5d018f-4: org.jboss.resteasy.spi.UnhandledException: javax.imageio.IIOException: New BMP version not implemented yet.
2024-12-12T19:40:05.1390485Z 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:107)
...
2024-12-12T19:40:05.1407316Z Caused by: javax.imageio.IIOException: New BMP version not implemented yet.
2024-12-12T19:40:05.1408137Z 	at java.desktop@21.0.5/com.sun.imageio.plugins.bmp.BMPImageReader.readHeader(BMPImageReader.java:582)
2024-12-12T19:40:05.1408776Z 	at java.desktop@21.0.5/com.sun.imageio.plugins.bmp.BMPImageReader.read(BMPImageReader.java:838)
2024-12-12T19:40:05.1409328Z 	at java.desktop@21.0.5/javax.imageio.ImageReader.readAll(ImageReader.java:1065)
2024-12-12T19:40:05.1409788Z 	at io.quarkus.awt.it.ImageResource.image(ImageResource.java:92)
```

**Comment by Karm** [comment]
```
 java.lang.UnsupportedOperationException: 
Add AWT Quarkus extension to enable Java2D/ImageIO. 
Additional system libraries such as `freetype' and `fontconfig' might be needed.
```

This means that the native-built project uses Java2D/Graphics without depending on AWT extension and that is a user config failure.

awt-packaging *depends* on AWT and does not show this error when executed in isolation:

```
$ ./mvnw verify -f integration-tests/pom.xml -pl awt-packaging -Dnative 2>&1 | tee log.log
```
in Quarkus 3.15.1.

I'll try to reproduce what Holly is seeing on the HEAD.

**Comment by Karm** [comment]
I iterated back to the issue and I am indeed getting a failure now when trying to a **container**:

```
$ ./mvnw verify --batch-mode -f integration-tests/pom.xml -fn -Dnative -Dquarkus.native.native-image-xmx=8g 
-Dquarkus.native.container-build=true
-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-17
-Dmaven.test.failure.ignore=true
-Dno-format
-Dtest-containers
-Dstart-containers
-Ddocker
-pl awt-packaging
```

Log:
```
[5/8] Inlining methods...     [***]                                                                      (2.0s @ 2.86GB)
[6/8] Compiling methods...    [*****]                                                                   (27.4s @ 2.54GB)
[7/8] Layouting methods...    [**]                                                                       (4.8s @ 2.58GB)

[8/8] Creating image...       [***]                                                                      (0.0s @ 1.92GB)
Fatal error: jdk.vm.ci.common.JVMCIError: java.nio.file.AccessDeniedException: /project/svm_err_b_20250122T133545.302_pid69.md
	at jdk.internal.vm.ci/jdk.vm.ci.common.JVMCIError.shouldNotReachHere(JVMCIError.java:52)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.reportImpl(ReportUtils.java:159)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:140)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.printEpilog(ProgressReporter.java:632)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.reportEpilog(NativeImageGeneratorRunner.java:474)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:466)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
Caused by: java.nio.file.AccessDeniedException: /project/svm_err_b_20250122T133545.302_pid69.md
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.createFile(Files.java:658)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.reportImpl(ReportUtils.java:149)
	... 7 more
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] podman cp 889bcb0bf0240bcc5b8128afd17de53b70d1a3ec916630e54ca11c490f0c8bf1:/project/quarkus-integration-test-awt-packaging-3.15.2-runner /home/karm/workspaceRH/quarkus_3.15.2/integration-tests/awt-packaging/target/quarkus-integration-test-awt-packaging-3.15.2-native-image-source-jar
[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] Failed to copy native image from container volume back to the host. Output: Error: "/project/quarkus-integration-test-awt-packaging-3.15.2-runner" could not be found on container 889bcb0bf0240bcc5b8128afd17de53b70d1a3ec916630e54ca11c490f0c8bf1: no such file or directory
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] podman cp 889bcb0bf0240bcc5b8128afd17de53b70d1a3ec916630e54ca11c490f0c8bf1:/project/build-artifacts.json /home/karm/workspaceRH/quarkus_3.15.2/integration-tests/awt-packaging/target/quarkus-integration-test-awt-packaging-3.15.2-native-image-source-jar
```

**Comment by Karm** [comment]
Normal container build works, it's the remote container build that's hitting issues:

```
+++ b/integration-tests/awt-packaging/src/main/resources/application.properties
@@ -1,2 +1,2 @@
 quarkus.lambda.handler=test
-quarkus.native.remote-container-build=true
+quarkus.native.remote-container-build=false
```

**Comment by Karm** [comment]
It's because the NativeImageBuildRemoteContainerRunner did not receive the same amount of love as NativeImageBuildLocalContainerRunner did when it comes to constructing `--user` permissions when creating volumes. That is problematic for rootless podman. Gonna try to enhance it...

**Comment by gastaldi** [comment]
Is this still happening?

**Comment by holly-cummins** [comment]
It's hard to check one way or another, because we often skip the `awt-packaging` tests as a gib optimisation. I checked the four most complete-looking recent runs, and the native AWT jobs were always about 7m. None of them showed the stack trace, but my reading of the logs is that all of them also skipped the affected tests. The original linked jobs have expired so I can't compare.

**Comment by Karm** [comment]
I cycled to this issue to find out the test is giving false negatives. 
First, it silently runs with a builder image and .so files are not in test's ./target and second, even if you force local native-image, the libs are in `quarkus/integration-tests/awt-packaging/target/quarkus-integration-test-awt-packaging-999-SNAPSHOT-native-image-source-jar` instead of `quarkus/integration-tests/awt-packaging/target` where the test expects those. 
The tests gives false negative because it's missing an assert for an empty set; i.e. empty set of libs equals empty set of libs and all is roses.

```
+        assertFalse(localLibs.isEmpty(), "We built an AWT enabled app, there must be some libs next to our executable.");
```

Fixing it...

**Comment by Karm** [comment]
It was not like that back in the day, so it's something about the test infrastructure that has been changing a lot since...

**Comment by Karm** [comment]
I commented the use of the test here and added the check for false negatives:
https://github.com/quarkusio/quarkus/pull/50603/files#diff-6e9d107f10d4f3a9608790ae0d630a631e9de6d481b15f963ddab99e9ed6937d

There are no error messages for AWT packaging test.   The no-awt logs errors though , which is to test that these meaningful errors are indeed emitted, advising users to ass awt.
