### ISSUE TITLE
Mail sending (Gmail) doesn't work

### ISSUE THREAD

**Issue by dodalovic** [quarkusio/quarkus#4510]
I was following [official guide](https://quarkus.io/guides/sending-emails#sending-simple-emails)
[app.zip](https://github.com/quarkusio/quarkus/files/3713499/mailer.zip)

**Comment by dodalovic** [comment]
```shell-script
curl --request POST \
  --url http://localhost:8181/mails \
  --header 'accept: text/plain' \
  --header 'content-type: application/json' \
  --data '{
	"recipient": "WHATEVER@gmail.com",
	"text": "mail body"
}'
```

**Comment by dodalovic** [comment]
I’m wondering if someone came across the same issue as I did 😞 ?

**Comment by jaikiran** [comment]
I haven't checked the app, but do you see any errors or exceptions when you invoke that endpoint? Any logs?

**Comment by dodalovic** [comment]
@jaikiran Absolutely nothing :)

**Comment by dodalovic** [comment]
Saw that `MockMailboxImpl` is being executed while sending, not sure if mock should be executed in runtime 😕

**Comment by dodalovic** [comment]
@jaikiran 
![image](https://user-images.githubusercontent.com/6358061/66703362-1dffac00-ed12-11e9-9b82-a5ae89174247.png)

**Comment by dodalovic** [comment]
When I set `quarkus.mailer.mock=false` in my `application.properties`, I get the following (I'm sure I'm using proper credentials) : 

```
2019-10-12 17:16:48,000 ERROR [io.und.req.io] (executor-thread-1) Exception handling request d3b5505f-227e-421f-ab69-d90374c12ab7-1 to /visits/email/patient/1: org.jboss.resteasy.spi.UnhandledException: java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: AUTH XOAUTH2 failed 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials m18sm20578699wrg.97 - gsmtp
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
        at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.sendError(ResteasyFilter.java:64)
        at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:172)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:28)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:270)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:59)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:116)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:113)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$8$1$1.call(UndertowDeploymentRecorder.java:433)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:250)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:59)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:82)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:669)
        at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:224)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: AUTH XOAUTH2 failed 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials m18sm20578699wrg.97 - gsmtp
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.vertx.axle.AsyncResultCompletionStage.lambda$toCompletionStage$0(AsyncResultCompletionStage.java:20)
        at io.vertx.ext.mail.impl.MailClientImpl.lambda$returnResult$5(MailClientImpl.java:155)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.vertx.core.impl.NoStackTraceThrowable: AUTH XOAUTH2 failed 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials m18sm20578699wrg.97 - gsmtp
```

**Comment by cescoffier** [comment]
The issue is gmail does not accept username and password anymore:
AUTH XOAUTH2 failed 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials m18sm20578699wrg.97

**Comment by dodalovic** [comment]
Seems they are, considering this sample project: [mail-sending-example.zip](https://github.com/quarkusio/quarkus/files/3723935/mail-sending-example.zip)

**Comment by dodalovic** [comment]
Bug still present in `0.25.0`

**Comment by dodalovic** [comment]
@jaikiran @cescoffier Is there someone available for support? Or to point me out if I can provide any? As stated above, I suspect `vertx-mail-client` has some issues

**Comment by jaikiran** [comment]
@dodalovic Sorry, I haven't been able to find some time to look into this. I will see if I can find some time later this week, if no one else get to it before that.

**Comment by kenfinnigan** [comment]
I encountered something similar last week in setting up some home networking.

It was simply not possible for me to send an email to the GMail SMTP server with a simple email/password combination of the account.

You need to create an application passcode that can be used with the email address. See https://support.google.com/accounts/answer/185833?hl=en

**Comment by t-shaguy** [comment]
Same here!

**Comment by Sanne** [comment]
ok that gmail requires an "app password". But why is there no error, and why was it necessary to set `quarkus.mailer.mock=false` ? Doesn't seem right; is someone looking to get to the bottom of that?

**Comment by jaikiran** [comment]
@Sanne I haven't had time to get to this and given that this involves having to use a gmail id, I probably won't be able to get to this any soon.

**Comment by Sanne** [comment]
thanks @jaikiran , and sure didn't mean to rush anyone :)  Just checking that we agree there's something to be done here, anyone could look to improve this.

Adding the "good first issue" as I think it might not be too hard. I hope I'm not wrong :)

**Comment by akochnev** [comment]
I ran into this same issue with quarkus 1.0.0.CR1
FWIW, the solution specified in https://github.com/vert-x3/vertx-mail-client/issues/118 does work and allow the injected mailer approach to be used in quarkus, e.g. : 

.. (in application.properties) ...
# note - XOAUTH2 is removed from the list
quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
....

... in quarkus app ... 
@ApplicationScoped
public class QuarkusMailSender implements MailSender {
    
    @ConfigProperty(name = "mailer.recipient") 
    String recipient;
    @Inject
    Mailer mailer;
    
    @Override
    public void send(SolReq req) {
        mailer.send(Mail.withText(recipient,String.format("sol req from %s",req.email),req.message));
    }
    
}
...
I still have to dig a bit deeper to sort out on how to make it work with an oauth token (which should be possible), but at least this restores the quarkus setup into a working state.

**Comment by gsmet** [comment]
The documentation has been updated.
