### ISSUE TITLE
Exception about missing maven classes when opening the dev-ui (gradle based project)

### ISSUE THREAD

**Issue by jmini** [quarkusio/quarkus#45112]
### Describe the bug

When you generate the most simple quarkus app using Gradle:
https://code.quarkus.io/?b=GRADLE

Start it in dev mode with `./gradlew quarkusDev`

Open the dev ui http://localhost:8080/q/dev-ui/

### Expected behavior

No Exception, everything is working

### Actual behavior

I got different errors about missing Maven classes:

```
2024-12-13 10:05:26,851 ERROR [io.qua.dev.run.jso.JsonRpcCodec] (ForkJoinPool.commonPool-worker-9) Error in JsonRPC Call: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/apache/maven/settings/building/SettingsBuildingException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/settings/building/SettingsBuildingException
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:90)
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver$Builder.build(MavenArtifactResolver.java:74)
        at io.quarkus.devtools.project.buildfile.MavenProjectBuildFile.getMavenResolver(MavenProjectBuildFile.java:151)
        at io.quarkus.devtools.project.buildfile.MavenProjectBuildFile.getProject(MavenProjectBuildFile.java:54)
        at io.quarkus.devtools.project.QuarkusProjectHelper.getCachedProject(QuarkusProjectHelper.java:59)
        at io.quarkus.devui.deployment.menu.ExtensionsProcessor.getQuarkusProject(ExtensionsProcessor.java:202)
        at io.quarkus.devui.deployment.menu.ExtensionsProcessor.lambda$getInstalledNamespaces$4(ExtensionsProcessor.java:124)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.settings.building.SettingsBuildingException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 14 more
```

Or:

```
2024-12-13 09:18:42,853 ERROR [io.qua.dev.run.jso.JsonRpcCodec] (ForkJoinPool.commonPool-worker-15) Error in JsonRPC Call: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/apache/maven/model/profile/activation/ProfileActivator
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/model/profile/activation/ProfileActivator
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:90)
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver$Builder.build(MavenArtifactResolver.java:74)
        at io.quarkus.devtools.project.buildfile.MavenProjectBuildFile.getMavenResolver(MavenProjectBuildFile.java:151)
        at io.quarkus.devtools.project.buildfile.MavenProjectBuildFile.getProject(MavenProjectBuildFile.java:54)
        at io.quarkus.devtools.project.QuarkusProjectHelper.getCachedProject(QuarkusProjectHelper.java:59)
        at io.quarkus.devui.deployment.menu.ExtensionsProcessor.getQuarkusProject(ExtensionsProcessor.java:202)
        at io.quarkus.devui.deployment.menu.ExtensionsProcessor.lambda$getInstalledNamespaces$4(ExtensionsProcessor.java:124)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.model.profile.activation.ProfileActivator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 14 more
```

Screenshot of the dev ui:

<img width="1098" alt="Image" src="https://github.com/user-attachments/assets/581771b6-cdb6-499c-bfc7-b788b7b464cd" />

### Quarkus version or git rev

3.17.4

**Comment by jmini** [comment]
@aloubyansky I am not sure if this is really a gradle issue, for me it is more something in the dev-ui that assumes it can access some maven classes that are obviously not present.

**Comment by aloubyansky** [comment]
AFAIU, the issue is not observed in Maven projects? It seemed like a Gradle project classpath configuration issue.

**Comment by jmini** [comment]
I did not debug it (yet), but I would say something is wrong here:

https://github.com/quarkusio/quarkus/blob/805c3f3576ca3c8055554a548989aafd20914d2d/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/QuarkusProjectHelper.java#L53-L63

I am obviously not in a maven project 😉

**Comment by phillip-kruger** [comment]
That is something I added. I'll have a look

**Comment by jmini** [comment]
I don't even know how I can debug `detectExistingBuildTool(..)`.

Is this a runtime thing or something that needs to be debugged at compile-time. Right now I don't see it in the dependencies of my quarkus project.

**Comment by phillip-kruger** [comment]
@aloubyansky please can you have a look.

**Comment by gsmet** [comment]
This is problematic, we need it fixed before next LTS.

**Comment by aloubyansky** [comment]
We should disable Dev UI project configuration management features for Gradle projects for now. The classpath issue is just the one on the surface and will be the easiest one to fix.

**Comment by kdubb** [comment]
@aloubyansky What's the state of this? I'm on 3.18 and wondering if an upgrade solves this.

**Comment by joshuadavis** [comment]
Just ran into this today when porting an existing application to Quarkus 3.19.2.     It's definitely not ideal, but I'm not experiencing any lack of functionality yet.   Just scary looking error messages. :)

**Comment by joshuadavis** [comment]
Upgrading to 3.19.3 fixed it, thanks!
