### ISSUE TITLE
BootstrapException running unit test. java.lang.ClassNotFoundException org.codehaus.plexus.util.interpolation.ValueSource

### ISSUE THREAD

**Issue by tomosnam** [quarkusio/quarkus#45137]
### Describe the bug

I am encountering errors when executing any the test. It seems based on the error output  that some of the dependencies listed int the pom.xml files are looking for a reference that no longer exists in the current versions of plexus-utils but in plexus-interpolation. Here is the official documentation for you reference [plexus-utils](https://codehaus-plexus.github.io/plexus-interpolation/)

### Expected behavior

The unit test is expected to execute successfully without any errors. The assertion in the test should validate that the returned value matches the expected output.

### Actual behavior

When test are run the process encounters errors  related to org.codehaus.plexus.util.interpolation.ValueSource when @QuarkusTest is in the context, resulting in a java.lang.ClassNotFoundException. Consequently, the test fails to run, and the expected output is not validated.

```
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for market:account::jar:2024.5.0-SNAPSHOTnull

	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:642)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:726)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for market:account::jar:2024.5.0-SNAPSHOTnull
	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:308)
	at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:133)
	at io.quarkus.test.junit.AbstractJvmQuarkusTestExtension.createAugmentor(AbstractJvmQuarkusTestExtension.java:190)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:218)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:609)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:659)
	... 1 more
Caused by: java.lang.RuntimeException: Failed to create application model resolver for C:\Users\OTMANSO\Documents\Code\unit-test-version-2\account
	at io.quarkus.bootstrap.BootstrapAppModelFactory.getAppModelResolver(BootstrapAppModelFactory.java:165)
	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:293)
	... 6 more
Caused by: java.lang.RuntimeException: Cannot get declared constructors from class org.apache.maven.profiles.activation.FileProfileActivator
	at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:874)
	at io.smallrye.beanbag.sisu.Sisu.addBeanFromXml(Sisu.java:453)
	at io.smallrye.beanbag.sisu.Sisu.addClassLoader(Sisu.java:124)
	at io.smallrye.beanbag.maven.MavenFactory.<init>(MavenFactory.java:71)
	at io.smallrye.beanbag.maven.MavenFactory.create(MavenFactory.java:96)
	at io.smallrye.beanbag.maven.MavenFactory.create(MavenFactory.java:111)
	at io.smallrye.beanbag.maven.MavenFactory.create(MavenFactory.java:124)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.configureMavenFactory(BootstrapMavenContext.java:889)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.initRepoSystemAndManager(BootstrapMavenContext.java:876)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getRepositorySystem(BootstrapMavenContext.java:292)
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:114)
	at io.quarkus.bootstrap.BootstrapAppModelFactory.getAppModelResolver(BootstrapAppModelFactory.java:161)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/util/interpolation/ValueSource
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2727)
	at io.smallrye.beanbag.sisu.Sisu.findConstructor(Sisu.java:872)
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.util.interpolation.ValueSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 22 more
```

### How to Reproduce?

The Minimal Reproducible Example can be found at this [GitHub link](https://github.com/tomosnam/quarkus-test-code-base/tree/main) To reproduce the issue, download the repository open the backend pom file as a project and run AccountResourceTest.

### Output of `java -version`

openjdk 21

### Quarkus version or git rev

3.11.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven version 3.9.9

### Additional information

I aapreciate any advice or suggestions in advance. Tank you!

**Comment by geoand** [comment]
cc @aloubyansky

**Comment by tomosnam** [comment]
The latest version of the plugin, copy-rename-maven-plugin, dates back to 2014, and among its dependencies is the version 1.5.8 of pluxus-utils. However, during the build process, the version of plexus-utils that gets downloaded is not 1.5.8, but rather 3.5.1. The discrepancy in the version of plexus-utils being used can be attributed to Maven's dependency resolution. When multiple versions are present, Maven tends to choose the most recent one, which could result in the use of a newer version of plexus-utils.

The error regarding the class org.codehaus.plexus.util.interpolation.ValueSource not being found is due to the fact that  plexus-utils in more recents versions  has separated  [plexus-interpolation](https://codehaus-plexus.github.io/plexus-interpolation/)  and plexus-utils into two distinct libraries. Previously, org.codehaus.plexus.util.interpolation was included within plexus-utils.

In conclusion, the solution was to replace the copy-rename-maven-plugin with a more up-to-date library that served the same purpose, such as the maven-antrun-plugin.

backend pom.xml before: 
```
 <dependencies>
        <dependency>
            <groupId>com.coderplus.maven.plugins</groupId>
            <artifactId>copy-rename-maven-plugin</artifactId>
            <version>1.0.1</version>
        </dependency>
    </dependencies>
 <profiles>
        <profile>
            <id>deployment</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.coderplus.maven.plugins</groupId>
                        <artifactId>copy-rename-maven-plugin</artifactId>
                        <version>1.0.1</version>
                        <executions>
                            <execution>
                                <id>copy-file</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>copy</goal>
                                </goals>
                                <configuration>
                                    <sourceFile>pom.xml</sourceFile>
                                    <destinationFile>target/${project.artifactId}-${project.version}.pom
                                    </destinationFile>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```

backend pom.xml after: 
```
<dependencies>
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-antrun-plugin</artifactId>
            <version>3.1.0</version>
       </dependency>
 </dependencies>
<profiles>
        <profile>
            <id>deployment</id>
            <build>
                <plugins> 
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <id>copy-and-rename-pom</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <copy file="${basedir}/pom.xml"
                                              tofile="target/${project.artifactId}-${project.version}.pom"/>
                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```

**Comment by geoand** [comment]
Thanks a lot for the update!
