### ISSUE TITLE
Gradle Kotlin project with no code cannot be started in Dev mode

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#45169]
### Describe the bug

```
$ quarkus create app org.acme:no-code-kotlin --extension quarkus-rest,kotlin --gradle-kotlin-dsl --no-code
```

```
$ quarkus dev
> Task :quarkusDev FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusDev'.
> The `src/main/java` directory is required, please create it.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3s
9 actionable tasks: 1 executed, 8 up-to-date
```

Maven works, so this is only issue with Gradle.

### How to Reproduce?

See the description.

### Quarkus version or git rev

3.17.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

$ ./gradlew --version  ------------------------------------------------------------ Gradle 8.9 ------------------------------------------------------------  Build time:    2024-07-11 14:37:41 UTC Revision:      d536ef36a19186ccc596d8817123e5445f30fef8  Kotlin:        1.9.23 Groovy:        3.0.21 Ant:           Apache Ant(TM) version 1.10.13 compiled on January 4 2023 Launcher JVM:  21.0.5 (Eclipse Adoptium 21.0.5+11-LTS) Daemon JVM:    /home/mstefank/.sdkman/candidates/java/21.0.5-tem (no JDK specified, using current Java home) OS:            Linux 6.11.10-300.fc41.x86_64 amd64

**Comment by gsmet** [comment]
Ideally, when you report an issue, it would be nice if you could go the extra mile and provide a full stack trace in the description.

Granted, I can reproduce it but it's a lot better for search engines and it also helps the maintainers trying to get an understanding of the issue and prioritize properly.

In this case, `quarkus dev -e` gives you:

```
Caused by: org.gradle.api.GradleException: The `src/main/java` directory is required, please create it.
        at io.quarkus.gradle.tasks.QuarkusDev.startDev(QuarkusDev.java:334)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
```

(for Quarkus 3.17.5)

**Comment by gsmet** [comment]
This is a can of worms - not completely surprised.

It's easy to lift the early restrictions but you then get NPEs further in the build process so I think I will just improve the log message for now.

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/pull/45291 for now as an easy win.

I'm not sure if things can be improved further but I will let it to someone interested in contributing to the Gradle plugin.

**Comment by xstefank** [comment]
thanks @gsmet
