### ISSUE TITLE
Can't GET /metrics/application in JSON

### ISSUE THREAD

**Issue by nicolasduminil** [quarkusio/quarkus#45179]
### Describe the bug

I'm running the following GET request against a Quarkus 3.17 application using Metrics:

    curl -H "Accept: application/json" localhost:8080/q/metrics/application
    {"details":"Error id 1bcf1b9f-786b-47a6-b279-b8437a852965-5","stack":""}

### Expected behavior

I expect that it works as documented [here](https://quarkus.io/guides/smallrye-metrics).

### Actual behavior

The one below works as expected:

    $ curl http://localhost:8080/q/metrics/application
    application... ...Timer_seconds_count 27.0
    application... ...Timer_seconds_sum 5.731539728
    application... ...Timer_seconds{quantile="0.5"} 0.122515098
    application... ...Timer_seconds{quantile="0.75"} 0.137004009
    ...

### How to Reproduce?

N/A

### Output of `uname -a` or `ver`

Linux nicolas-XPS-15-9570 6.8.0-50-generic #51-Ubuntu SMP PREEMPT_DYNAMIC Sat Nov  9 17:58:29 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Quarkus version or git rev

3.17

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546) Maven home: /opt/apache-maven-3.9.5 Java version: 21.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-21-oracle-x64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.8.0-50-generic", arch: "amd64", family: "unix"

### Additional information

N/A

**Comment by gsmet** [comment]
Could you share the stacktrace you probably get on the server side?

**Comment by jmartisk** [comment]
Looks like you're using SmallRye Metrics, this extension has been discontinued for a while. Instead of putting significant effort into fixing this, I would suggest switching to Micrometer.

**Comment by gsmet** [comment]
I think we still need to understand what's going on as, if not working, we need to adjust the doc.

**Comment by nicolasduminil** [comment]
@gsmet: Sure, sorry about that.

    2024-12-17 17:54:25,682 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-7) HTTP Request to /q/metrics/application failed, error id: 1bcf1b9f-786b-47a6-b279-b8437a852965-5: java.lang.IllegalArgumentException: wrong number of arguments: 0 expected: 1
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkArgumentCount(DirectMethodHandleAccessor.java:329)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:101)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.smallrye.metrics.interceptors.GaugeRegistrationInterceptor.invokeMethod(GaugeRegistrationInterceptor.java:88)
        at io.smallrye.metrics.interceptors.GaugeRegistrationInterceptor.access$100(GaugeRegistrationInterceptor.java:46)
        at io.smallrye.metrics.interceptors.GaugeRegistrationInterceptor$ForwardingGauge.getValue(GaugeRegistrationInterceptor.java:108)
        at io.smallrye.metrics.interceptors.GaugeRegistrationInterceptor$ForwardingGauge.getValue(GaugeRegistrationInterceptor.java:94)
     ...

**Comment by gsmet** [comment]
This is the full thing? Ideally share the whole thing and redact your company name if you have confidential info in it.

I'm especially interested in checking if it's Quarkus or SmallRye Metrics that needs a fix.

I wouldn't be surprised if it's related to some specific metrics so if you can get me a simple reproducer, that would be ideal.

**Comment by nicolasduminil** [comment]
@gsmet Since the "full thing" is very long, I'm attaching a file containing it.[log.txt](https://github.com/user-attachments/files/18181419/log.txt)

**Comment by jmartisk** [comment]
I think this means that you have a `@Gauge` annotation on a method that takes arguments. A gauge method should take no arguments.

**Comment by nicolasduminil** [comment]
@jmartisk This was it, thanks. Strangely enough, without the `application/json` header on the `curl` command, there is no exception but the output wasn't accurate. Closing now.
