### ISSUE TITLE
Spring-di's @Scope#session throws ContextNotActiveException

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#45191]
### Describe the bug

After the merge of https://github.com/quarkusio/quarkus/pull/45170 the `@Scope(scopeName = "session")` stopped working and throwing the `jakarta.enterprise.context.ContextNotActiveException: SessionScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=io.quarkus.ts.spring.data.primitivetypes.configuration.AppConfiguration, id=9767shscEaYLEayHF-_VBq-X1Aw]`

Other scopes seems working fine. So maybe with recent change the [SpringDIProcessor](https://github.com/quarkusio/quarkus/blob/main/extensions/spring-di/deployment/src/main/java/io/quarkus/spring/di/deployment/SpringDIProcessor.java) needs to updated.

### Expected behavior

Not getting `ContextNotActiveException` when using `@Scope(scopeName = "session")`

### Actual behavior

```
jakarta.enterprise.context.ContextNotActiveException: SessionScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean [class=io.quarkus.ts.spring.data.primitivetypes.configuration.AppConfiguration, id=9767shscEaYLEayHF-_VBq-X1Aw]
        at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:70)
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:58)
        at io.quarkus.ts.spring.data.primitivetypes.configuration.AppConfiguration_ProducerMethod_sessionIdBean_3pCqCWZn6or_axTX0l-b0tdJ7hs_ClientProxy.arc$delegate(Unknown Source)
        at io.quarkus.ts.spring.data.primitivetypes.configuration.AppConfiguration_ProducerMethod_sessionIdBean_3pCqCWZn6or_axTX0l-b0tdJ7hs_ClientProxy.getSessionId(Unknown Source)
        at io.quarkus.ts.spring.data.rest.MagazineResource.test(MagazineResource.java:38)
        at io.quarkus.ts.spring.data.rest.MagazineResource$quarkusrestinvoker$test_056288de5192b9be1916ebef3bf0275a7088b428.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:637)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

```

### How to Reproduce?

1. `git clone -b spring-session-scoped git@github.com:jedla97/quarkus-reproducers.git`
2. `cd quarkus-reproducers`
3. `quarkus dev`
4. Visit http://127.0.0.1:8080/magazine-resource or http://127.0.0.1:8080/magazine-resource/1

We mainly propagated it to headers when running test. For simplification I add it as response value on `MagazineResource#test` endpoint (`magazine-resource`).

### Quarkus version or git rev

main

### Additional information

If you want to try it on our TS see https://github.com/quarkus-qe/quarkus-test-suite/tree/main/spring/spring-data

You can run run it by `mvn -fae -V -B clean verify -Dreruns=0 -Pspring-modules -pl spring/spring-data`

**Comment by jedla97** [comment]
cc @mkouba as creator of #45170

**Comment by mkouba** [comment]
AFAIK the session scope was never supported. @geoand do you happen to know how `quarkus-spring-di` handles the session scope?

**Comment by geoand** [comment]
It never did. If it worked, it was an accident

**Comment by aureamunoz** [comment]
From the [doc](https://es.quarkus.io/guides/spring-di#conversion-table): 
_Doesn’t have a one-to-one mapping to a CDI annotation. Depending on the value of @Scope, one of the @Singleton, @ApplicationScoped, @SessionScoped, @RequestScoped, @Dependent could be used_

**Comment by manovotn** [comment]
> From the [doc](https://es.quarkus.io/guides/spring-di#conversion-table): _Doesn’t have a one-to-one mapping to a CDI annotation. Depending on the value of [@scope](https://github.com/scope), one of the [@singleton](https://github.com/singleton), @ApplicationScoped, @SessionScoped, @RequestScoped, [@dependent](https://github.com/dependent) could be used_

Right but what Martin means is that ArC never had an actual session scope impl so we must have ignored it or transformed it into another one whereas now it seems to use the newly added context (which is for tests).

**Comment by mkouba** [comment]
I believe that the scope was previously simply ignored. The `SpringDIProcessor` turns `@Scope(scopeName = "session")` into `@jakarta.enterprise.context.SessionScoped` but since it was not a bean defining annotation the scope was ignored and `@Dependent` was used for a producer method.

`SpringDIProcessor` should probably fail the deployment unless the `quarkus-undertow` (or any other extension that adds the support for session context) is present.

**Comment by manovotn** [comment]
I was looking into the Spring processor as well and came to the same conclusion.

> SpringDIProcessor should probably fail the deployment unless the quarkus-undertow (or any other extension that adds the support for session context) is present.

While this is the right solution, it might break existing apps - an alternative would be to re-implement the fallback to `@Dependent` while logging a warning as such behavior is probably unintentional at best.

**Comment by mkouba** [comment]
> While this is the right solution, it might break existing apps - an alternative would be to re-implement the fallback to `@Dependent` while logging a warning as such behavior is probably unintentional at best.

Good point. Although the fallback should not be used by default because this functionality was unintenional and erroneous. Maybe we should add a config knob, fail by default but enable the fallback if really needed.

**Comment by geoand** [comment]
> Maybe we should add a config knob, fail by default but enable the fallback if really needed.

+1

**Comment by rsvoboda** [comment]
The fail message could mention the fallback configuration option.

**Comment by Ladicek** [comment]
> > While this is the right solution, it might break existing apps - an alternative would be to re-implement the fallback to `@Dependent` while logging a warning as such behavior is probably unintentional at best.
> 
> Good point. Although the fallback should not be used by default because this functionality was unintenional and erroneous. Maybe we should add a config knob, fail by default but enable the fallback if really needed.

I honestly don't agree with this. If it worked, it was a bug, plain and simple. I'm not sure if `@SessionScoped` being a BDA is the right thing to do, but if yes, then the exception being thrown here is the right thing to do.

The only thing we might want to add is a bit of text to the exception message.

**Comment by Ladicek** [comment]
I"m also thinking we should probably add `@ConversationScoped` as a BDA as well, to also throw instead of silently treating the possible beans as `@Dependent`.

**Comment by mkouba** [comment]
> I'm not sure if @SessionScoped being a BDA is the right thing to do, but if yes, then the exception being thrown here is the right thing to do.

Actually, I don't think it's a matter of making the `@SessionScoped` a BDA but the fact that `@SessionScoped` is considered a built-in scope now.

> The only thing we might want to add is a bit of text to the exception message.

Hm, I would say that it's the very least we should do given the fact that it's a bug in a core extension ;-).

> I"m also thinking we should probably add @ConversationScoped as a BDA as well, to also throw instead of silently treating the possible beans as @Dependent.

That's a good point. However, it seems that Spring DI does not care (because spring does not have an equivalent). So the only problematic use case would be a `@ConversationScoped` CDI producer.

**Comment by Ladicek** [comment]
> > I"m also thinking we should probably add @ConversationScoped as a BDA as well, to also throw instead of silently treating the possible beans as [@dependent](https://github.com/dependent).
> 
> That's a good point. However, it seems that Spring DI does not care (because spring does not have an equivalent). So the only problematic use case would be a `@ConversationScoped` CDI producer.

A bit of a stretch, but not unrealistic: you could have a class-based bean annotated with a stereotype (that doesn't define a scope, but is a BDA) and `@ConversationScoped`, which would also be silently considered `@Dependent`.

**Comment by manovotn** [comment]
I tried looking for a fix on ArC level but we cannot really tell if a bean with session scope annotation is an error or not (due to the scope/context now being always present).

So we'll need to restrict this to the spring processor where we should be able to validate this by checking if we know of any custom session scope implementations.

**Comment by manovotn** [comment]
I tried to implement a detection for spring processor but ultimately I don't think that's correct either because it can still be false positive. You can have tests that use session scope and leverage ArC's built-in session context - in such case any detection fails as we can never know if the presence of session scope annotation (without any custom context impl) is a mistake or deliberate action.

So short of just adjusting ArC's exception for `ContextNotActive` in combination with session scoped, I am not sure how to handle this.
@mkouba, @Ladicek if either of you has an idea, fell free to take over. Otherwise, I'll try and get back to it some time next week.

**Comment by Ladicek** [comment]
I think the only correct thing to do here is to adjust the `ContextNotActiveException` message in case of session scope (or conversation scope) to explicitly mention that session scope is not supported unless an extension is used that provides the context implementation (and conversation scope is not supported at all).

**Comment by mkouba** [comment]
> I think the only correct thing to do here is to adjust the `ContextNotActiveException` message in case of session scope (or conversation scope) to explicitly mention that session scope is not supported unless an extension is used that provides the context implementation (and conversation scope is not supported at all).

👍 I agree.
