### ISSUE TITLE
Handling browser close while streaming response

### ISSUE THREAD

**Issue by JarekW** [quarkusio/quarkus#45249]
### Describe the bug

Hi I have a problem with quarkus exceptions after what i think is browser closing data stream. Code below is a proxy, based on documentation on [quarkus s3 client - downloading asynchronously](https://docs.quarkiverse.io/quarkus-amazon-services/dev/amazon-s3.html#_going_asynchronous) . It's streaming video file from s3 to browser. There is also example with local filesystem. Streaming itself is working fine. What is the problem is exceptions in logs about closed channel/pipe.

This is what I think is happening:
When user seek video to other position then browser is closing previous stream and opening another with different range header. If browser close stream there will be cases with some bytes that was received from S3 but not yet send to client. When items in multi are delayed error rate is reduced, at 20 millis they almost don't occur anymore.

Streaming method:
```
//this comes from aws-sdk
CompletableFuture<CompletedDownload<ResponsePublisher<GetObjectResponse>>> downloadComplFuture;

return RestMulti.fromUniResponse(  
	Uni.createFrom().completionStage(downloadComplFuture),  
	(response) -> {  
		ResponsePublisher<GetObjectResponse> publisher1 = response.result();  

		return Multi.createFrom().safePublisher(AdaptersToFlow.publisher(publisher1))  
			.map(BufferUtil::toBuffer)

//delaying items reduces exception rate
/*
			.onItem().call(buffer -> {  
				return Uni.createFrom().nullItem().onItem().delayIt().by(Duration.ofMillis(20));  
			})  
*/
			;  
	},  
	(response) -> {  
		var headers = new HashMap<>(Map.of(  
			"Accept-Ranges", List.of("bytes"),  
			"Content-Length", List.of(response.result().response().contentLength().toString()),  
			"Content-Type", List.of(response.result().response().contentType())  
		));  

		String contentRange = response.result().response().contentRange();  
		if (contentRange != null) {  
			headers.put("Content-Range", List.of(contentRange));  
		}  

		return headers;  
	},  
	(response) -> {  
		String contentRange = response.result().response().contentRange();  
		if (contentRange != null) {  
			return Response.Status.PARTIAL_CONTENT.getStatusCode();  
		}  
		return Response.Status.OK.getStatusCode();  
	}  
);
}
```

When serving file from local filesystem the first and second exception also accurs.

```
return RestMulti.fromUniResponse(  
	vertx.fileSystem().open(filePath, new OpenOptions()),  
	(response) -> {  
		response.setReadPos(rangeFrom);  
		return response.toMulti().map(buffer -> {  
			return Buffer.buffer(buffer.getBytes());  
		})
//delaying items reduces exception rate
/*
			.onItem().call(buffer -> {  
				return Uni.createFrom().nullItem().onItem().delayIt().by(Duration.ofMillis(20));  
			})  
*/
                ;  
	},  
	(response) -> {  
		Long size = response.sizeBlocking();  
		Map<String, List<String>> headers = new HashMap<>(Map.of(  
			"Accept-Ranges", List.of("bytes"),  
			"Content-Length", List.of(String.valueOf(size)),  
			"Content-Type", List.of("video/mp4")  
		));  
		if (range != null) {  
			headers.put("Content-Range", List.of(String.format("bytes %s-%s/%s", rangeFrom, size - 1, size)));  
		}  

		return headers;  
	},  
	(response) -> {  
		if (range != null) {  
			return Response.Status.PARTIAL_CONTENT.getStatusCode();  
		}  
		return Response.Status.OK.getStatusCode();  
	}  
);
```

Exceptions:
```
ERROR [org.jbo.res.rea.ser.han.PublisherResponseHandler] (vert.x-eventloop-thread-3) Exception in SSE server handling, impossible to send it to client: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
```

```
ERROR [org.jbo.res.rea.ser.han.PublisherResponseHandler] (vert.x-eventloop-thread-2) Exception in SSE server handling, impossible to send it to client: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
```

```
ERROR [org.jbo.res.rea.ser.han.PublisherResponseHandler] (vert.x-eventloop-thread-2) Exception in SSE server handling, impossible to send it to client: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:66)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:217)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:153)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:563)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:929)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:366)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:782)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Also error staters that this is for SSE, which is not. It's because handling of that error is in parent `AbstractMultiSubscriber`

It might be related to  #26253 [this comment](https://github.com/quarkusio/quarkus/issues/26253#issuecomment-1494859223), I don't have knowledge to tell if the multi is terminated or not.

### Expected behavior

handling browser close without exceptions

### Actual behavior

exception on browser stream close

### How to Reproduce?

1. stream video file to browser
2. seek video position

### Output of `uname -a` or `ver`

Darwin wa 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

java version "17.0.7" 2023-04-18 LTS  GraalVM

### Quarkus version or git rev

3.17.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8

**Comment by cescoffier** [comment]
Can you provide a standalone reproducer? 

it should _cancel_ the stream (now, whether the stream source handles cancellation is a different question)

**Comment by JarekW** [comment]
I've made a repository with above code: [quarkus-45249](https://github.com/JarekW/quarkus-45249)
There need to be mp4 file in resources folder, [can be this](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4)

**Comment by cescoffier** [comment]
I looked at the reproducer. With _main_, when the request is cancelled, the multi gets the cancellation and the data extractor gets the cancellation signal too (not emitting anything anymore).

In your code, a `.onTermination().call(response::close)` is missing after the delay to close the resource.

**Comment by JarekW** [comment]
Thanks for checking that. I tried adding `response.close` to stream, but these errors still occur. 
Now I'm not sure if you have those errors in logs where reproducing? Is it means it works as expected, and they are supposed to appear in the logs because of broken communication?

I've added commit with debug log lines before/after `response.close()` and errors almost always are between them:
```
13:53:04,575 INFO  [org.acm.StreamResource] (vert.x-eventloop-thread-0) before close on termination
13:53:04,576 ERROR [org.jbo.res.rea.ser.han.PublisherResponseHandler] (vert.x-eventloop-thread-0) Exception in SSE server handling, impossible to send it to client: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.SocketDispatcher.writev0(Native Method)
	...
13:53:04,578 INFO  [org.acm.StreamResource] (vert.x-eventloop-thread-0) after close on termination
```



.
One time had broken pipe error but with longer stack strace, adding that just in case:
<details>
<summary>ERROR [org.jbo.res.rea.ser.han.PublisherResponseHandler] (vert.x-eventloop-thread-1) Exception in SSE server handling, impossible to send it to client: java.io.IOException: Broken pipe</summary>
```
13:45:37,800 ERROR [org.jbo.res.rea.ser.han.PublisherResponseHandler] (vert.x-eventloop-thread-1) Exception in SSE server handling, impossible to send it to client: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.SocketDispatcher.writev0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:66)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:227)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:158)
	at java.base/sun.nio.ch.SocketChannelImpl.implWrite(SocketChannelImpl.java:597)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:631)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:929)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:359)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:893)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1319)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:935)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:937)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:957)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:982)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:950)
	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:181)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:233)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:218)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:214)
	at io.vertx.core.http.impl.Http1xServerResponse.write(Http1xServerResponse.java:788)
	at io.vertx.core.http.impl.Http1xServerResponse.write(Http1xServerResponse.java:333)
	at io.vertx.core.http.impl.Http1xServerResponse.write(Http1xServerResponse.java:69)
	at io.quarkus.vertx.http.runtime.filters.AbstractResponseWrapper.write(AbstractResponseWrapper.java:39)
	at io.quarkus.vertx.http.runtime.filters.AbstractResponseWrapper.write(AbstractResponseWrapper.java:18)
	at io.quarkus.vertx.http.runtime.filters.AbstractResponseWrapper.write(AbstractResponseWrapper.java:39)
	at io.quarkus.vertx.http.runtime.filters.AbstractResponseWrapper.write(AbstractResponseWrapper.java:18)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.write(VertxResteasyReactiveRequestContext.java:442)
	at org.jboss.resteasy.reactive.server.core.StreamingUtil.send(StreamingUtil.java:57)
	at org.jboss.resteasy.reactive.server.handlers.PublisherResponseHandler$StreamingMultiSubscriber.onNext(PublisherResponseHandler.java:108)
	at io.smallrye.mutiny.subscription.MultiSubscriberAdapter.onItem(MultiSubscriberAdapter.java:27)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at org.jboss.resteasy.reactive.RestMulti$AsyncRestMulti$FlatMapPublisherSubscriber.onNext(RestMulti.java:248)
	at io.smallrye.mutiny.subscription.MultiSubscriberAdapter.onItem(MultiSubscriberAdapter.java:27)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:100)
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.vertx.MultiReadStream.lambda$subscribe$2(MultiReadStream.java:76)
	at io.vertx.core.file.impl.AsyncFileImpl.handleBuffer(AsyncFileImpl.java:431)
	at io.vertx.core.file.impl.AsyncFileImpl.lambda$new$0(AsyncFileImpl.java:114)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:279)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:157)
	at io.vertx.core.file.impl.AsyncFileImpl.lambda$doRead$5(AsyncFileImpl.java:413)
	at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```
</details>

**Comment by cescoffier** [comment]
Yes, broken pipe or reset by peer exception may happen on write if the stream has been cut by the client but not yet handled by the stream.
