### ISSUE TITLE
Upcoming Kotlin 2.1.x version looks to be breaking on compiler CLI API

### ISSUE THREAD

**Issue by apatrida** [quarkusio/quarkus#45286]
### Describe the bug

This is a warning of future break that is incoming:

If you update to Kotlin 2.1.x dev builds, then Quarkus dev mode rebuild will die due to a `NoSuchMethodError` indicating that there is a breaking API change coming soon.

```
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.cli.common.ExitCode org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.exec(org.jetbrains.kotlin.cli.common.messages.MessageCollector, org.jetbrains.kotlin.config.Services, org.jetbrains.kotlin.cli.common.arguments.CommonToolArguments)'
	at io.quarkus.kotlin.deployment.KotlinCompilationProvider.compile(KotlinCompilationProvider.java:93)
	at io.quarkus.deployment.dev.QuarkusCompiler.compile(QuarkusCompiler.java:232)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:778)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:475)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:455)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:161)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$6.call(VertxHttpHotReplacementSetup.java:148)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$4(ContextImpl.java:192)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextImpl$1.execute(ContextImpl.java:221)
	at io.vertx.core.impl.WorkerTask.run(WorkerTask.java:56)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

### How to Reproduce?

1. add Jetbrains nightly repo `maven(url = "https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev")`
2. update Kotlin version to `2.1.20-dev-7931`
3. enforce Kotlin BOM `implementation(enforcedPlatform(libs.kotlin.bom))`
4. run app
5. go to results of a page or rest response
6. change code 
7. refresh page, see breaking message as indicated in description

**Comment by geoand** [comment]
Thanks for the heads up!

IIRC @gsmet was already looking into the upgrade

**Comment by gsmet** [comment]
Thanks for the heads up. I'm going to close this one as it's about possible future breakage but it's very nice to have it in mind.

For now, we are actually waiting for a Gradle version that supports Kotlin 2.1.x. Until then, we are kinda stuck.

Our current efforts are there: https://github.com/quarkusio/quarkus/pull/45228 .
