### ISSUE TITLE
IfBuildProfile does not work on scheduler classes

### ISSUE THREAD

**Issue by gbourant** [quarkusio/quarkus#45308]
I have the following class

```java
@IfBuildProfile(anyOf = {"dev", "prod", "RateLimitSchedulerProfile"})
public class RateLimitScheduler {

    @Scheduled(every = "1s")
    public void schedule() {
        System.out.println("hello " + System.currentTimeMillis());
    }
}
```

And the following test

```java
public class RateLimitSchedulerProfile implements QuarkusTestProfile {
    @Override
    public String getConfigProfile() {
        return "test,RateLimitSchedulerProfile";
    }
}

@QuarkusTest
@TestProfile(RateLimitSchedulerProfile.class)
class RateLimitSchedulerTest {

    @Inject
    RateLimitScheduler rateLimitScheduler;

    @Test
    void test() {
        System.out.println("RateLimitSchedulerTest:");
        rateLimitScheduler.schedule();
    }

}
```

This test fails with 

```text
[ERROR] Errors: 
[ERROR]   HelloResourceTest.testHelloEndpoint » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type gr.RateLimitScheduler and qualifiers [@Default]
	- injection target: gr.RateLimitSchedulerTest#rateLimitScheduler
	- declared on CLASS bean [types=[gr.RateLimitSchedulerTest, java.lang.Object], qualifiers=[@Default, @Any], target=gr.RateLimitSchedulerTest]
	The following classes match by type, but have been skipped during discovery:
	- gr.RateLimitScheduler was annotated with @Vetoed


	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1576)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:338)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:178)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:492)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:499)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type gr.RateLimitScheduler and qualifiers [@Default]
	- injection target: gr.RateLimitSchedulerTest#rateLimitScheduler
	- declared on CLASS bean [types=[gr.RateLimitSchedulerTest, java.lang.Object], qualifiers=[@Default, @Any], target=gr.RateLimitSchedulerTest]
	The following classes match by type, but have been skipped during discovery:
	- gr.RateLimitScheduler was annotated with @Vetoed


	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:547)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:697)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:323)
	... 12 more
```

In order to "fix" it i would have to use the `%test.quarkus.scheduler.enabled=false` and delete the `@IfBuildProfile` from RateLimitSchedulerProfile class.

Note: The test which fails is not the RateLimitSchedulerTest but the HelloResourceTest. If i disable the HelloResourceTest it works.

[Reproducer](https://github.com/gbourant/quarkus-scheduler-bug)

**Comment by manovotn** [comment]
IIUIC, you are mixing **build** profiles and **test** profiles.

Build profiles will be either `dev`, `test` or `prod`.
You can have beans existing in any combination of those three and you'd use the `IfBuildProfile`/`UnlessBuildProfile` annotations for it.

Test profiles can be multiple and customized and they typically override some config options of your application.
If you want a bean to be only present for certain test profile, you need to declare that bean within your custom implementation of `QuarkusTestProfile`. Here's the bit from its javadoc:

> If an implementation of this interface declares CDI beans, via producer methods/ fields and nested static classes, then those beans are only taken into account if this test profile is used. In other words, the beans are ignored for any other test profile.

**Comment by mkouba** [comment]
> Note: The test which fails is not the RateLimitSchedulerTest but the HelloResourceTest. If i disable the HelloResourceTest it works.

That's a very important piece of information! This means that `@IfBuildProfile` works as expected but for some reason the `RateLimitSchedulerTest` is also considered a CDI bean when `HelloResourceTest` is executed. This should not be the case. At least that's what I thought. But apparently `@QuarkusTest` is [registered as a bean defining annotation](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/TestsAsBeansProcessor.java#L29-L34) since 1.4.0.CR1 🤔 .

**Comment by mkouba** [comment]
A workaround is to use programmatic lookup in the `RateLimitSchedulerTest`, i.e. replace `@Inject RateLimitScheduler rateLimitScheduler` with `@Inject Instance<RateLimitScheduler> rateLimitScheduler` (`Instance` as in `jakarta.enterprise.inject.Instance`) and then obtain the bean instance with `rateLimitScheduler.get()`. This way there's no direct dependency on `RateLimitScheduler`,  the build does not fail and all tests pass.
