### ISSUE TITLE
Issue with Oracle Object Storage Upload

### ISSUE THREAD

**Issue by OutOfBoundCats** [quarkusio/quarkus#45303]
I have installed below dependencies 

```gradle
    implementation("com.oracle.oci.sdk:oci-java-sdk-objectstorage:2.27.0")
    implementation("com.oracle.oci.sdk:oci-java-sdk-common:2.27.0")
    // https://mvnrepository.com/artifact/com.oracle.oci.sdk/oci-java-sdk-common-httpclient-jersey
    implementation 'com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey:3.55.1'
    // // https://mvnrepository.com/artifact/com.oracle.oci.sdk/oci-java-sdk-addons-resteasy-client-configurator
    // implementation 'com.oracle.oci.sdk:oci-java-sdk-addons-resteasy-client-configurator:3.55.1'

    implementation 'io.quarkus:quarkus-jackson:3.17.5'
    implementation('io.quarkus:quarkus-rest-jsonb:3.17.5')
    implementation('io.quarkus:quarkus-rest-jaxb:3.17.5')`
```

note the commented section in dependency
and below is the code i am using to do upload

```java
@ApplicationScoped
public class ObjectService {
    Logger log = LoggerFactory.getLogger(ObjectService.class);
    @Inject
    AppConfig appConfig;


    public String uploadFile(EnumBucketType bucketName, String objectName, FileUpload file) throws InternalError {
        try {
            String ociConfigPath = appConfig.ociConfig();
            String ociProfile = appConfig.ociProfile();
            ConfigFileAuthenticationDetailsProvider provider =
                    new ConfigFileAuthenticationDetailsProvider(ociConfigPath, ociProfile);

            ClientConfigurator configurator = new com.oracle.bmc.http.DefaultConfigurator();
            // Create an Object Storage client using the builder
            ObjectStorageClient client = ObjectStorageClient.builder()
            .clientConfigurator(configurator).build(provider);

            FileInputStream inputStream = new FileInputStream(new File(file.fileName()));
            String namespaceName = provider.getTenantId();

            PutObjectRequest putObjectRequest = PutObjectRequest.builder()
                    .namespaceName(namespaceName)
                    .bucketName(bucketName.getBucketName())
                    .objectName(objectName)
                    .putObjectBody(inputStream)
                    .contentLength(new File(file.fileName()).length())
                    .build();

            PutObjectResponse putObjectResponse = client.putObject(putObjectRequest);
            String etag=putObjectResponse.getETag();
            System.out.println("File uploaded successfully with ETag: " + etag);
            inputStream.close();
            client.close();
            return etag;
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            log.error("FileNotFoundException:- Error while uploading file", e);
            throw new InternalError();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            log.error("IOException:- Error while uploading file", e);
            throw new InternalError();
        }
    }


}
````

but i get exception

````posh
2024-12-28 09:23:56,274 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (quarkus-virtual-thread-2) HTTP Request to /process_create_profile_form?lang=mr failed, error id: d79d77b9-15d3-4bcb-8020-be9bddaf62d4-2: java.lang.NoClassDefFoundError: Could not initialize class com.oracle.bmc.Region
        at com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider.getRegionFromConfigFile(ConfigFileAuthenticationDetailsProvider.java:102)
        at com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider.<init>(ConfigFileAuthenticationDetailsProvider.java:83)
        at com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider.<init>(ConfigFileAuthenticationDetailsProvider.java:66)
        at services.ObjectService.uploadFile(ObjectService.java:40)
        at services.ObjectService_ClientProxy.uploadFile(Unknown Source)
        at services.ProfileService.saveProfile(ProfileService.java:151)
        at services.ProfileService_ClientProxy.saveProfile(Unknown Source)
        at controller.ProfileController.createProfileFormSubmission(ProfileController.java:75)
        at controller.ProfileController_Subclass.createProfileFormSubmission$$superforward(Unknown Source)
        at controller.ProfileController_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at controller.ProfileController_Subclass.createProfileFormSubmission(Unknown Source)
        at controller.ProfileController_ClientProxy.createProfileFormSubmission(Unknown Source)
        at controller.ProfileController$quarkusrestinvoker$createProfileFormSubmission_e3c9ba066c9877f323c275aa1f0fe9120a9c64da.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: javax/ws/rs/core/Configurable [in thread "ForkJoinPool-1-worker-1"]
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:558)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
        at com.oracle.bmc.Region.<clinit>(Region.java:67)
        ... 30 more

09:23:56.274 [quarkus-virtual-thread-2] ERROR i.q.v.h.runtime.QuarkusErrorHandler - HTTP Request to /process_create_profile_form?lang=mr failed, error id: d79d77b9-15d3-4bcb-8020-be9bddaf62d4-2
java.lang.NoClassDefFoundError: Could not initialize class com.oracle.bmc.Region
        at com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider.getRegionFromConfigFile(ConfigFileAuthenticationDetailsProvider.java:102)
        at com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider.<init>(ConfigFileAuthenticationDetailsProvider.java:83)
        at com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider.<init>(ConfigFileAuthenticationDetailsProvider.java:66)
        at services.ObjectService.uploadFile(ObjectService.java:40)
        at services.ObjectService_ClientProxy.uploadFile(Unknown Source)
        at services.ProfileService.saveProfile(ProfileService.java:151)
        at services.ProfileService_ClientProxy.saveProfile(Unknown Source)
        at controller.ProfileController.createProfileFormSubmission(ProfileController.java:75)
        at controller.ProfileController_Subclass.createProfileFormSubmission$$superforward(Unknown Source)
        at controller.ProfileController_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at controller.ProfileController_Subclass.createProfileFormSubmission(Unknown Source)
        at controller.ProfileController_ClientProxy.createProfileFormSubmission(Unknown Source)
        at controller.ProfileController$quarkusrestinvoker$createProfileFormSubmission_e3c9ba066c9877f323c275aa1f0fe9120a9c64da.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: javax/ws/rs/core/Configurable [in thread "ForkJoinPool-1-worker-1"]
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:558)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
        at com.oracle.bmc.Region.<clinit>(Region.java:67)
        ... 30 common frames omitted
```

Can someone point me in right direction please?

**Comment by yrodiere** [comment]
> ```
> Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: javax/ws/rs/core/Configurable > [in thread "ForkJoinPool-1-worker-1"]
>         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
>         at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
>         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:558)
>         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
>         at com.oracle.bmc.Region.<clinit>(Region.java:67)
> ```


`com.oracle.bmc.Region` is relying on `javax.ws`, which is Java EE technology and technically obsolete as far as Quarkus is concerned. Quarkus 3 is supposed to work with Jakarta EE instead.

You should either upgrade your dependencies to a version where `com.oracle.bmc.Region` relies on Jakarta EE instead, or hope that it isn't used, and just add `javax.ws` to your dependencies (though I wonder why it would be missing).
I doubt things will work fine if your dependencies actually use `javax.ws`, but you can try.

**Comment by OutOfBoundCats** [comment]
@yrodiere  thank you for taking time to answer this query. I was usign old versions of the libraries and i think using newer version will resolve it so closign this issue
