### ISSUE TITLE
RestClientTestCase fails with latest code of master branch

### ISSUE THREAD

**Issue by rashmi-ibm** [quarkusio/quarkus#4597]
**Describe the bug**
Error:
Caused by: java.util.NoSuchElementException: Property test.url not found
at io.smallrye.config.SmallRyeConfig.propertyNotFound(SmallRyeConfig.java:221)
at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:112)
at io.quarkus.runtime.configuration.ConfigExpander.accept(ConfigExpander.java:55)
at io.quarkus.runtime.configuration.ConfigExpander.accept(ConfigExpander.java:15)
at org.wildfly.common.expression.ExpressionNode.emit(ExpressionNode.java:42)
at org.wildfly.common.expression.Expression.evaluateException(Expression.java:75)
at org.wildfly.common.expression.Expression.evaluate(Expression.java:89)
at io.quarkus.runtime.configuration.ExpandingConfigSource.expandValue(ExpandingConfigSource.java:76)
at io.quarkus.runtime.configuration.ExpandingConfigSource.expand(ExpandingConfigSource.java:48)
at io.quarkus.runtime.configuration.ExpandingConfigSource.getValue(ExpandingConfigSource.java:44)
at io.quarkus.runtime.configuration.DeploymentProfileConfigSource.getValue(DeploymentProfileConfigSource.java:57)
at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:136)
at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:131)
at io.quarkus.restclient.runtime.RestClientBase.getBaseUrl(RestClientBase.java:55)
at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:32)
at io.quarkus.it.rest.RestClientBaseUriConfigKeyInterface_caffaa3bd97f1b9d0c34e49d33d7971db9ee59b8_Synthetic_Bean.create(RestClientBaseUriConfigKeyInterface_caffaa3bd97f1b9d0c34e49d33d7971db9ee59b8_Synthetic_Bean.zig:192)
at io.quarkus.it.rest.RestClientBaseUriConfigKeyInterface_caffaa3bd97f1b9d0c34e49d33d7971db9ee59b8_Synthetic_Bean.get(RestClientBaseUriConfigKeyInterface_caffaa3bd97f1b9d0c34e49d33d7971db9ee59b8_Synthetic_Bean.zig:86)
at io.quarkus.it.rest.RestClientBaseUriConfigKeyInterface_caffaa3bd97f1b9d0c34e49d33d7971db9ee59b8_Synthetic_Bean.get(RestClientBaseUriConfigKeyInterface_caffaa3bd97f1b9d0c34e49d33d7971db9ee59b8_Synthetic_Bean.zig:71)
at io.quarkus.arc.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:51)
at io.quarkus.it.rest.ClientResource_Bean.create(ClientResource_Bean.zig:409)
... 76 more
> [ERROR] Errors: [ERROR] RestClientTestCase.testMicroprofileClientComplex:70 ? JsonPath Failed to parse... [ERROR] RestClientTestCase.testMicroprofileClientComplexCdi:79 ? JsonPath Failed to pa... [ERROR] RestClientTestCase.testMicroprofileClientData:48 ? JsonPath Failed to parse th... [ERROR] RestClientTestCase.testMicroprofileClientDataCdi:55 ? JsonPath Failed to parse... [INFO] [ERROR] Tests run: 117, Failures: 8, Errors: 4, Skipped: 1

**Expected behavior**
(Describe the expected behavior clearly and concisely.)

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**
1.  Build quarkus using ./mvnw clean install
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Rhel 7.6 ppc64le
 - Output of `java -version`: jdk1.8
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: latest code

**Additional context**
If I build using release 0.24.0 on ppc64le vm it is successful issue is only with the latest code.

**Comment by gsmet** [comment]
Do you still have the issue with our latest releases?

**Comment by stuartwdouglas** [comment]
Closing as out of date.
