### ISSUE TITLE
RuntimeException: Failed to start quarkus

### ISSUE THREAD

**Issue by genehi** [quarkusio/quarkus#4621]
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:185)
        at io.quarkus.runtime.Application.start(Application.java:93)
        at io.quarkus.runtime.Application.run(Application.java:213)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
Caused by: java.lang.IllegalAccessError: tried to access class io.smallrye.config.Converters from class io.quarkus.runtime.configuration.ConverterSupport
        at io.quarkus.runtime.configuration.ConverterSupport.converterToItem(ConverterSupport.java:86)
        at io.quarkus.runtime.configuration.ConverterSupport.getConverters(ConverterSupport.java:102)
        at io.quarkus.runtime.configuration.ConverterSupport.<clinit>(ConverterSupport.java:32)
        at io.quarkus.runtime.generated.RunTimeConfig.getRunTimeConfiguration(RunTimeConfig.zig:32153)
        at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:49)

I looked at Converters and the Converters.getConverterType method and they are both public.
Cannot determine the actual cause of the error

**Comment by genehi** [comment]
Nevermind, I resolved that the issue is that the Converters class is not public in smallrye config 1.3.4 version, but it is correct in 1.3.9 version.  Now I just have to figure out WHY plugin bundled an older version into the boostrap lib
