### ISSUE TITLE
Custom Configuration Converter failing at start up time

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#4656]
**Describe the bug**

I have created a custom converter that transforms a String representing a percentage to a double but at the bootup time I got: 

```
Caused by: java.lang.NumberFormatException: For input string: "21%"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at java.base/java.lang.Double.valueOf(Double.java:506)
	at io.smallrye.config.Converters.lambda$static$496cfed0$1(Converters.java:55)
	at io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:133)
	at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:98)
	at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:35)
```

**Expected behavior**

The application should start normally.

**Actual behavior**

The exception is thrown. The workaround of creating a custom type instead of using Double fails as well as it interprets the property as number instead of string.

**To Reproduce**

```
@Priority(300)
public class PercentageConverter implements Converter<Double> { // <2>

    @Override
    public Double convert(String value) {
        if (value.endsWith("%")) { // <3>
            String numeric = value.substring(value.length() - 1);
            return Double.parseDouble(numeric) / 100;
        }

        return Double.parseDouble(value); // <4>
    }

}
```

```
greeting.vat = "21%"
```

Using Quarkus 0.25.0

**Comment by lordofthejars** [comment]
Wait wait.
