### ISSUE TITLE
Unclear stacktrace on server startup

### ISSUE THREAD

**Issue by viniciusfcf** [quarkusio/quarkus#4664]
**Describe the bug**
After update my project from 0.23.2 to 0.25.0 and all keycloak configurations, the server did not started. My keycloak was up, however without my realm.

**Expected behavior**
StackTrace with a clear message, like `please make sure the 'quarkus.oidc.auth-server-url' is correct`

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

```2019-10-16 19:06:46,165 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1912ms
java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: Not Found
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044)
        at io.quarkus.oidc.VertxKeycloakRecorder.setup(VertxKeycloakRecorder.java:59)
        at io.quarkus.deployment.steps.VertxKeycloakBuildStep$setup44.deploy_0(VertxKeycloakBuildStep$setup44.zig:73)
        at io.quarkus.deployment.steps.VertxKeycloakBuildStep$setup44.deploy(VertxKeycloakBuildStep$setup44.zig:92)
        at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:169)
        at io.quarkus.runtime.Application.start(Application.java:94)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:135)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:94)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: io.vertx.core.impl.NoStackTraceThrowable: Not Found
2019-10-16 19:06:48,149 ERROR [io.qua.dev.DevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:225)
        at io.quarkus.runtime.Application.start(Application.java:94)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:135)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:94)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: Not Found
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044)
        at io.quarkus.oidc.VertxKeycloakRecorder.setup(VertxKeycloakRecorder.java:59)
        at io.quarkus.deployment.steps.VertxKeycloakBuildStep$setup44.deploy_0(VertxKeycloakBuildStep$setup44.zig:73)
        at io.quarkus.deployment.steps.VertxKeycloakBuildStep$setup44.deploy(VertxKeycloakBuildStep$setup44.zig:92)
        at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:169)
        ... 5 more
Caused by: io.vertx.core.impl.NoStackTraceThrowable: Not Found

2019-10-```

**Comment by mvniekerk** [comment]
Same:
Upgraded from 0.23.1 -> 0.25
The `quarkus.oidc.auth-server-url` and `quarkus.keycloak.auth-server-url` are different, in that the `/realms/<my_realm>` must be appended on 0.25

_0.25_
quarkus.oidc.auth-server-url=http://localhost:8080/auth/realms/quarkus
quarkus.oidc.client-id=backend-service

vs

_0.23_
quarkus.keycloak.realm=quarkus
quarkus.keycloak.auth-server-url=http://localhost:8080/auth
quarkus.keycloak.resource=backend-service
quarkus.keycloak.bearer-only=true
quarkus.keycloak.credentials.secret=secret

**Comment by emmanuelbernard** [comment]
@sberyozkin if you have time or you can delegate to someone. That would be a good to have.

**Comment by sberyozkin** [comment]
@emmanuelbernard sure, I can have a look

**Comment by sberyozkin** [comment]
I have the PR coming with the following:
```
java.util.concurrent.CompletionException: io.quarkus.oidc.OIDCException: OIDC server is not available at the 'quarkus.oidc.auth-server-url' URL. Please make sure it is correct. Note it has to end with a realm value if you work with Keycloak.
.....
the rest of the stack trace
---
Caused by: io.vertx.core.impl.NoStackTraceThrowable: Not Found: {"error":"Realm does not exist"}
```

**Comment by emmanuelbernard** [comment]
@sberyozkin you could provide a quick URL example for Keycloak but not a biggie

**Comment by sberyozkin** [comment]
@emmanuelbernard good idea, as the KC URL has a specific structure, so now it will read:
```
java.util.concurrent.CompletionException: io.quarkus.oidc.OIDCException: OIDC server is not available at the 'quarkus.oidc.auth-server-url' URL. Please make sure it is correct. Note it has to end with a realm value if you work with Keycloak, for example: 'https://localhost:8180/auth/realms/quarkus'
```
