### ISSUE TITLE
OIDC Extension throws ClassNotFoundException when using quarkus-resteasy-jackson

### ISSUE THREAD

**Issue by xfh** [quarkusio/quarkus#4672]
**Describe the bug**
I am migration a project with the Keycloak extension (Quarkus 0.22.0) to the new OIDC extension (Quarkus 0.25.0). I am using the `quarkus-resteasy-jackson` extension instead of jsonb. Unfortunately, these extensions are no longer interchangeable: the access token cannot be parsed, because org.eclipse.microprofile.jwt.Claims specifies JsonObject types, e.g. for the address.
See [stacktrace_JsonObject_notFound.txt](https://github.com/quarkusio/quarkus/files/3744710/stacktrace_JsonObject_notFound.txt)

**Expected behavior**
The app does not crash. Required dependencies are provided.

**Actual behavior**
ClassNotFoundException

**To Reproduce**
1. In the `using-openid-connect` starter pom, change the dependency `quarkus-resteasy-jsonb` to `quarkus-resteasy-jackson` 
2. access UserResource as described in the [guide](https://quarkus.io/guides/oidc-guide.html).

**Comment by gsmet** [comment]
For the record, here is the stracktrace:
```
java.lang.NoClassDefFoundError: javax/json/JsonObject
        at org.eclipse.microprofile.jwt.Claims.<clinit>(Claims.java:71)
        at io.smallrye.jwt.auth.principal.DefaultJWTCallerPrincipal.getRawToken(DefaultJWTCallerPrincipal.java:68)
        at io.smallrye.jwt.auth.principal.DefaultJWTCallerPrincipal.<init>(DefaultJWTCallerPrincipal.java:60)
        at io.smallrye.jwt.auth.principal.DefaultJWTCallerPrincipal.<init>(DefaultJWTCallerPrincipal.java:64)
        at io.quarkus.oidc.VertxJwtCallerPrincipal.<init>(VertxJwtCallerPrincipal.java:15)
        at io.quarkus.oidc.VertxOAuth2IdentityProvider$1.handle(VertxOAuth2IdentityProvider.java:62)
        at io.quarkus.oidc.VertxOAuth2IdentityProvider$1.handle(VertxOAuth2IdentityProvider.java:46)
        at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.lambda$decodeToken$3(OAuth2AuthProviderImpl.java:271)
        at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.authenticate(OAuth2AuthProviderImpl.java:238)
        at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.decodeToken(OAuth2AuthProviderImpl.java:269)
        at io.quarkus.oidc.VertxOAuth2IdentityProvider.authenticate(VertxOAuth2IdentityProvider.java:46)
        at io.quarkus.oidc.VertxOAuth2IdentityProvider.authenticate(VertxOAuth2IdentityProvider.java:23)
        at io.quarkus.oidc.VertxOAuth2IdentityProvider_ClientProxy.authenticate(VertxOAuth2IdentityProvider_ClientProxy.zig:152)
        at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl.handleProvider(QuarkusIdentityProviderManagerImpl.java:104)
        at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl.authenticate(QuarkusIdentityProviderManagerImpl.java:72)
        at io.quarkus.security.runtime.IdentityProviderManagerCreator_ProducerMethod_ipm_91f102be1b2a781216db8a81e6ab4b9b1a84f03c_ClientProxy.authenticate(IdentityProviderManagerCreator_ProducerMethod_ipm_91f102be1b2a781216db8a81e6ab4b9b1a84f03c_ClientProxy.zig:105)
        at io.quarkus.oidc.VertxOAuth2AuthenticationMechanism.authenticate(VertxOAuth2AuthenticationMechanism.java:78)
        at io.quarkus.oidc.VertxOAuth2AuthenticationMechanism_ClientProxy.authenticate(VertxOAuth2AuthenticationMechanism_ClientProxy.zig:41)
        at io.quarkus.vertx.http.runtime.security.HttpAuthenticator.attemptAuthentication(HttpAuthenticator.java:69)
        at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.attemptAuthentication(HttpAuthenticator_ClientProxy.zig:150)
        at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1.handle(HttpSecurityRecorder.java:34)
        at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1.handle(HttpSecurityRecorder.java:23)
        at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:276)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:124)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
        at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:79)
        at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:65)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: javax.json.JsonObject
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 37 more
```

**Comment by gsmet** [comment]
@sberyozkin could you have someone take a look at this Monday. It looks like a missing dependency.

**Comment by sberyozkin** [comment]
@gsmet thanks, I'll be working tomorrow so will have a look

**Comment by xfh** [comment]
I could fix it by adding the dependency
```
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-json-binding-provider</artifactId>
</dependency>
```

**Comment by sberyozkin** [comment]
@xfh thanks, that might be one option, otherwise I was thinking to make `quarkus-jsonb` provided and make the transformation into `JsonWebToken` optional

**Comment by xfh** [comment]
As long as there is still a way to get all the properties from the access token I am happy :-)

With JsonWebToken I can cast the SecurityIdentity Principal to JWTCallerPrincipal and get for example the clientId through `((JWTCallerPrincipal) securityIdentity.getPrincipal()).getClaim("clientId")`

I wouldn't mind a solution that does not require casting tough.

**Comment by sberyozkin** [comment]
@xfh it is even easier, you can have `@Inject JsonWebToken jwt` :-)

**Comment by xfh** [comment]
@sberyozkin great, thanks!

**Comment by xfh** [comment]
@sberyozkin FYI: just adding the `resteasy-json-binding-provider` dependency is apparently not enough. It works when running quarkus in dev mode, but fails after building a JVM based Docker Image with the following ClassNotFoundException: org.apache.commons.io.input.ProxyInputStream

```
RESTEASY002145: NoClassDefFoundError: Unable to load builtin provider org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider from jar:file:/deployments/lib/org.jboss.resteasy.resteasy-json-binding-provider-4.3.1.Final.jar!/META-INF/services/javax.ws.rs.ext.Providers: java.lang.NoClassDefFoundError: org/apache/commons/io/input/ProxyInputStream
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructors(Class.java:1651)
        at org.jboss.resteasy.spi.util.PickConstructor.pickSingletonConstructor(PickConstructor.java:30)
```

I got that fixed by adding
```
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
</dependency>
```

**Comment by xfh** [comment]
Thanks @sberyozkin  & @gsmet, I love how quickly you are moving and where you are going with this project!
