### ISSUE TITLE
QuarkusDev NoSuchMethodError failed startup

### ISSUE THREAD

**Issue by tsfullman** [quarkusio/quarkus#4773]
**Describe the bug**
I pulled in 0.26.0 and built non-natively successfully. However, when trying to do a ./gradlew quarkusDev the app fails to start and gets the following stacktrace (I cut out the beginning):

```
17:06:59,398 INFO  [io.qua.resteasy] Resteasy running without servlet container.
17:06:59,398 INFO  [io.qua.resteasy] - Add quarkus-undertow to run Resteasy within a servlet container
17:07:00,110 INFO  [io.qua.dep.QuarkusAugmentor] Quarkus augmentation completed in 2155ms
17:07:00,540 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:142)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:94)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:437)
        ... 9 more
Caused by: java.lang.NoSuchMethodError: org.eclipse.microprofile.metrics.MetadataBuilder.reusable(Z)Lorg/eclipse/microprofile/metrics/MetadataBuilder;
        at io.smallrye.metrics.setup.MetricsMetadata.getMetadata(MetricsMetadata.java:79)
        at io.smallrye.metrics.setup.MetricsMetadata.registerMetrics(MetricsMetadata.java:45)
        at io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsRecorder.registerMetrics(SmallRyeMetricsRecorder.java:130)
        at io.quarkus.deployment.steps.SmallRyeMetricsProcessor$registerMetricsFromAnnotatedMethods25.deploy_0(SmallRyeMetricsProcessor$registerMetricsFromAnnotatedMethods25.zig:383)
        at io.quarkus.deployment.steps.SmallRyeMetricsProcessor$registerMetricsFromAnnotatedMethods25.deploy(SmallRyeMetricsProcessor$registerMetricsFromAnnotatedMethods25.zig:743)
        at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:415)
        ... 9 more

17:07:00,541 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus, attempting to start hot replacement endpoint to recover
```

**Expected behavior**
The app to start correctly

**Actual behavior**
breaks doing a quarkusDev

**To Reproduce**
1. Use quarkus 0.26.0
2. ./gradlew quarkusDev

**Environment (please complete the following information):**
 - Output of `java -version`: jdk 11.0.2
 - Quarkus version or git rev: 0.26.0
- Gradle version: 5.6.2
- Build.gradle includes following extensions:
```
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-smallrye-metrics'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-smallrye-jwt'
    implementation 'io.quarkus:quarkus-rest-client'
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'io.quarkus:quarkus-resteasy-jsonb'
    implementation 'io.quarkus:quarkus-vertx'
```

**Comment by geoand** [comment]
@tsfullman can you show your entire `build.gradle` file please?

**Comment by jmartisk** [comment]
I don't know how exactly this could happen, but I have an explanation particularly for the `java.lang.NoSuchMethodError` - this will happen if there's MP Metrics 2.0 present, because that method was added in 2.1. Quarkus 0.26 uses Metrics 2.1 though, so we might need to find out how the 2.0 API got into this.

**Comment by tsfullman** [comment]
Your comment about the version helped. I realized I was pulling in another dependency that was enforcing 'org.eclipse.microprofile:microprofile:3.0' which uses metrics 2.0. Closing this bug as it was a code issue on my end. Thank you for your help.

**Comment by geoand** [comment]
Thanks for reporting back @tsfullman
