### ISSUE TITLE
Gradle doesn't work if using JDK 11

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#4823]
**Describe the bug**

When calling `./gradlew build` having `JDK11`, you get that:
```
com.oracle.svm.core.util.UserError$UserException: Class initialization of io.quarkus.runner.ApplicationImpl6 failed. Use the option --initialize-at-run-time=io.quarkus.runner.ApplicationImpl6 to explicitly request delayed initialization of this class.
Detailed message:

        at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:223)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:737)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Class initialization of io.quarkus.runner.ApplicationImpl6 failed. Use the option --initialize-at-run-time=io.quarkus.runner.ApplicationImpl6 to explicitly request delayed initialization of this class.
Detailed message:

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:688)
        ... 7 more
Caused by: java.lang.ExceptionInInitializerError
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:153)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:557)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:116)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:144)
        at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:190)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:262)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:203)
        at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:155)
        at org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4080)
        at org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4330)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5128)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3267)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3074)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:976)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:870)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:510)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        ... 4 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl6.<clinit>(ApplicationImpl6.zig:136)
        ... 34 more
Caused by: java.lang.UnsupportedClassVersionError: org/andy/ExampleResource has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.andy.ExampleResource_Bean.<init>(ExampleResource_Bean.zig:59)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:171)
        at io.quarkus.arc.ArcContainerImpl.<init>(ArcContainerImpl.java:87)
        at io.quarkus.arc.Arc.initialize(Arc.java:18)
        at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:33)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources133.deploy_0(ArcProcessor$generateResources133.zig:53)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources133.deploy(ArcProcessor$generateResources133.zig:297)
        at io.quarkus.runner.ApplicationImpl6.<clinit>(ApplicationImpl6.zig:106)
        ... 34 more
```

We fixed it using (but it needs further tests with Kotlin and Scala):
```
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
```

**Comment by geoand** [comment]
@ia3andy IIRC you had a PR for this?

**Comment by gsmet** [comment]
So the default build also builds the native image?

**Comment by geoand** [comment]
Yes. It's documented in the guide how to exclude the native stuff.
It was done this way since it's more idiomatic to Gradle but we can change if people think this isn't what we should be doing.

**Comment by ia3andy** [comment]
@geoand I won't have time to fix that today, we absolutely need it for next release. @gsmet when is the next?

**Comment by geoand** [comment]
I agree we need it ASAP. @ia3andy if you won't be able to get to this tomorrow, let me know and I'll take care of it.

**Comment by ia3andy** [comment]
@geoand  I think I'll be able to make it tomoz. In case I don't, I'll ping u ;-) thanks mate!

**Comment by geoand** [comment]
Cool!

**Comment by ia3andy** [comment]
@geoand I didn't see the time pass today 😬I totally forgot about that one lol let's do it on monday 😅 Anyway I think the release will not be on monday.

**Comment by geoand** [comment]
@ia3andy yeah, it won't be so we have time. However if you don't get a chance Monday, ping me around noon so I can take care of this one :)
