### ISSUE TITLE
vault-app tests fail to build native image

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#4836]
integration-tests/vault-app fails to build native image

```
uname -a
Darwin RS 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

mvn -version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: /Users/rsvoboda/.sdkman/candidates/maven/current
Java version: 1.8.0_222, vendor: Oracle Corporation, runtime: /Users/rsvoboda/.sdkman/candidates/java/19.2.0.1-grl/jre
Default locale: en_CZ, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```
```
vault-app$ mvn clean package -Dnative -DskipTests -DskipITs
...
...
[INFO] --- quarkus-maven-plugin:0.23.0:native-image (native-image) @ quarkus-integration-test-vault-app ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.build.skip" provided
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Final
[INFO] [org.hibernate.jpa.boot.internal.PersistenceXmlParser] HHH000318: Could not find any META-INF/persistence.xml file in the classpath
[INFO] [org.hibernate.Version] HHH000412: Hibernate Core {5.4.7.Final}
[INFO] [io.quarkus.resteasy] Resteasy running without servlet container.
[INFO] [io.quarkus.resteasy] - Add quarkus-undertow to run Resteasy within a servlet container
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1650ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: /Users/rsvoboda/git/quarkus/integration-tests/vault-app/target/quarkus-integration-test-vault-app-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit GraalVM CE 19.2.0.1
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /Users/rsvoboda/.sdkman/candidates/java/19.2.0.1-grl/bin/native-image -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dio.netty.leakDetection.level=DISABLED -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dio.netty.allocator.maxOrder=1 -J-Dvertx.disableDnsResolver=true --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-integration-test-vault-app-999-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=https --enable-all-security-services -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[quarkus-integration-test-vault-app-999-SNAPSHOT-runner:29862]    classlist:   8,998.73 ms
[quarkus-integration-test-vault-app-999-SNAPSHOT-runner:29862]        (cap):   1,594.04 ms
[quarkus-integration-test-vault-app-999-SNAPSHOT-runner:29862]        setup:   3,043.62 ms
12:12:19,388 INFO  [org.hib.Version] HHH000412: Hibernate Core {5.4.7.Final}
12:12:19,405 INFO  [org.hib.ann.com.Version] HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
12:12:19,446 INFO  [org.hib.dia.Dialect] HHH000400: Using dialect: io.quarkus.hibernate.orm.runtime.dialect.QuarkusPostgreSQL95Dialect
[quarkus-integration-test-vault-app-999-SNAPSHOT-runner:29862]     analysis:  15,662.91 ms
Printing call tree to /Users/rsvoboda/git/quarkus/integration-tests/vault-app/target/reports/call_tree_quarkus-integration-test-vault-app-999-SNAPSHOT-runner_20191024_121236.txt
Printing list of used classes to /Users/rsvoboda/git/quarkus/integration-tests/vault-app/target/reports/used_classes_quarkus-integration-test-vault-app-999-SNAPSHOT-runner_20191024_121237.txt
Printing list of used packages to /Users/rsvoboda/git/quarkus/integration-tests/vault-app/target/reports/used_packages_quarkus-integration-test-vault-app-999-SNAPSHOT-runner_20191024_121237.txt
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.runtime.Timing.printStartupTime(java.lang.String, java.lang.String, java.lang.String, boolean). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:258)
Call path from entry point to io.quarkus.runner.ApplicationImpl1.doStart(String[]):
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:30)
	at io.quarkus.runtime.Application.start(Application.java:94)
	at io.quarkus.runtime.Application.run(Application.java:218)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.runCore(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i


com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.runtime.Timing.printStartupTime(java.lang.String, java.lang.String, java.lang.String, boolean). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:258)
Call path from entry point to io.quarkus.runner.ApplicationImpl1.doStart(String[]):
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:30)
	at io.quarkus.runtime.Application.start(Application.java:94)
	at io.quarkus.runtime.Application.run(Application.java:218)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.runCore(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i


	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:223)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:737)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.runtime.Timing.printStartupTime(java.lang.String, java.lang.String, java.lang.String, boolean). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:258)
Call path from entry point to io.quarkus.runner.ApplicationImpl1.doStart(String[]):
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:30)
	at io.quarkus.runtime.Application.start(Application.java:94)
	at io.quarkus.runtime.Application.run(Application.java:218)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:34)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runner.ApplicationImpl1.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.doStart(java.lang.String[]):v
	io.quarkus.runtime.Application.start(java.lang.String[]):v
	io.quarkus.runtime.Application.run(java.lang.String[]):v
	io.quarkus.runner.GeneratedMain.main(java.lang.String[]):v
	com.oracle.svm.core.JavaMainWrapper.runCore(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.JavaMainWrapper.run(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i
	com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(int, org.graalvm.nativeimage.c.type.CCharPointerPointer):i


	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:688)
	... 7 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.runtime.Timing.printStartupTime(java.lang.String, java.lang.String, java.lang.String, boolean). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:238)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:228)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:182)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1571)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1546)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5125)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3267)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3074)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:976)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:870)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:191)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:343)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:385)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:510)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	... 4 more
Error: Image build request failed with exit status 1
```

**Comment by sberyozkin** [comment]
@vsevel Hi Vincent - can you please check when you get few secs ?

**Comment by gsmet** [comment]
Hmm, this is very weird `com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.runtime.Timing.printStartupTime(java.lang.String, java.lang.String, java.lang.String, boolean)`

**Comment by jaikiran** [comment]
Hello @rsvoboda, is this against upstream master? The same command works fine for me locally. Plus, this output in your log seems odd:
```
[INFO] --- quarkus-maven-plugin:0.23.0:native-image (native-image) @ quarkus-integration-test-vault-app ---
```
Not sure how/why `0.23.0` of Quarkus Maven plugin in coming in here. It should be:
```
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (native-image) @ quarkus-integration-test-vault-app ---
```

**Comment by jaikiran** [comment]
```
mvn -version
Apache Maven 3.6.2
```
Okay, so looks like something changed in plugin dependency resolution in this version. I was on `3.6.1` and things were building fine with the above command. I decided to try this `3.6.2` based on your report and it indeed fails with similar errors. It infact uses `0.23.2` of quarkus-maven-plugin:
```
[INFO] --- quarkus-maven-plugin:0.23.2:native-image (native-image) @ quarkus-integration-test-vault-app ---
```
To be fair, it does log a big warning message before it continues with the build. The WARN says:
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.quarkus:quarkus-integration-test-vault-app:jar:999-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for ${project.groupId}:quarkus-maven-plugin is missing. @ line 156, column 29
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```
Coming up with a PR to fix that and pin the version of this plugin

**Comment by jaikiran** [comment]
I've issued https://github.com/quarkusio/quarkus/pull/4843 to fix this.

**Comment by vsevel** [comment]
@jaikiran hello,
I did miss that big warning. It was on the first `quarkus-maven-plugin` (with the build goal), but not on the second one (for the native). and it just worked.
interestingly, I copied the vault-app module from the [jpa-postgresql](https://github.com/quarkusio/quarkus/blob/master/integration-tests/jpa-postgresql/pom.xml#L63) integration test, which happens to have no version on any of the plugins.
I am doing a quick scan, and I found hibernate-validator, infinispan-client, main (ie: the IT), kafka, jpa, ...
Are these all wrong? or are there situations where we have to put the version, and sometimes not.
and in the pluginManagement of the IT parent module we do have:
```
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>io.quarkus</groupId>
                    <artifactId>quarkus-maven-plugin</artifactId>
                    <version>${project.version}</version>
                    <configuration>
                        <noDeps>true</noDeps>
                        <skip>${quarkus.build.skip}</skip>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
```
Should not that set the version appropriately?

**Comment by jaikiran** [comment]
Hello @vsevel,

> I am doing a quick scan, and I found hibernate-validator, infinispan-client, main (ie: the IT), kafka, jpa, ...

You are right, many of them were missing this version. Maven highly recommends pinning them to a specific version, for avoiding issues like these. So I've updated that PR to include these too.

> and in the pluginManagement of the IT parent module we do have:
> 
>         <pluginManagement>
>             <plugins>
>                 <plugin>
>                     <groupId>io.quarkus</groupId>
>                     <artifactId>quarkus-maven-plugin</artifactId>
>                     <version>${project.version}</version>
>                     <configuration>
>                         <noDeps>true</noDeps>
>                         <skip>${quarkus.build.skip}</skip>
>                     </configuration>
>                 </plugin>
>             </plugins>
>         </pluginManagement>
> 
> Should not that set the version appropriately?

That section is actually under the "build" which seems to be applicable only for the default profiles and that's correctly working for the default profiles of these child projects. However, it seems ineffective for `profile`s in the child project poms like the `native` profile. Like you I was hoping there was a easier way to manage this for the `native` profile from the parent pom.xml but I haven't found any conclusive documentation which states that it works nor could I get it working in my local tests. So I've asked Alexey, in the PR, for his inputs on this subject.

**Comment by gsmet** [comment]
Good catch @rsvoboda !
