### ISSUE TITLE
quarkus-integration-test-vault-app is requiring Docker to build

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#4925]
**Describe the bug**
The module `quarkus-integration-test-vault-app` is expecting the docker daemon to be running; not having it has the whole Quarkus build fail.

Other modules have a conditional dependency controlled by a flag to enable any integration tests requiring docker.

This is particularly annoying for people building Quarkus without docker (possibly because working on an unrelated set of modules), or using `podman` instead of docker.

**Comment by gsmet** [comment]
@Sanne are you sure? AFAICS, the tests should only be run if you have `-Dtest-vault`. At least, that's how it's supposed to work.

**Comment by Sanne** [comment]
I wasn't setting that flag, but I had `-Dnative`; this will produce:

```
Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$3(DockerClientProviderStrategy.java:156)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:148)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:111)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:175)
	at org.testcontainers.containers.JdbcDatabaseContainer.<init>(JdbcDatabaseContainer.java:36)
	at org.testcontainers.containers.PostgreSQLContainer.<init>(PostgreSQLContainer.java:32)
	at org.testcontainers.containers.PostgreSQLContainer.<init>(PostgreSQLContainer.java:28)
	at io.quarkus.vault.test.VaultTestExtension.start(VaultTestExtension.java:120)
	at io.quarkus.vault.test.VaultTestLifecycleManager.start(VaultTestLifecycleManager.java:32)
	at io.quarkus.test.common.TestResourceManager.start(TestResourceManager.java:43)
```

**Comment by Sanne** [comment]
I guess the native tests should be skipped as well when `test-vault` is not set.

Also, no tests requiring docker should be started unless `-Ddocker` is set.

**Comment by gsmet** [comment]
Ah, OK, now that I have a look, it's not consistent with how we do things elsewhere.

Will fix soon as it's in the way.

**Comment by gsmet** [comment]
Yup, it's an oversight, will fix.

**Comment by Sanne** [comment]
hey you don't have to fix it :) leave something for the newcomers!

(but as you wish)

**Comment by gsmet** [comment]
Yeah, it can be a build problem in real life and I prefer to get it fixed
soon.

I just finished this Jakarta work (hopefully!) so a small PR is a nice
change of air :).
