### ISSUE TITLE
Use QuarkusJsonPlatformDescriptorResolver leads to exceptions

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#4938]
**Describe the bug**
I am using `QuarkusJsonPlatformDescriptorResolver` as described in `JsonDescriptorResolverDemo`.

```
       QuarkusJsonPlatformDescriptorResolver.newInstance()
                .setMessageWriter(log)
                .setMavenArtifactResolver()
                .setPlatformJsonArtifactId("quarkus-bom-descriptor-json")
                .resolve()
```

But I get an exception at bootstrap:
```
[ERROR] testWithAllParams  Time elapsed: 0.008 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [io.quarkus.code.CodeQuarkusResourceTest]: Failed to create the boostrap class loader
Caused by: java.lang.IllegalStateException: Failed to create the boostrap class loader
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the deployment classloader for io.launcher:code.quarkus.io::jar:1.0.0
Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to resolve dependencies for io.launcher:code.quarkus.io:jar:1.0.0
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact io.quarkus:quarkus-platform-descriptor-legacy:jar: in central (https://repo.maven.apache.org/maven2)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact io.quarkus:quarkus-platform-descriptor-legacy:jar: in central (https://repo.maven.apache.org/maven2)
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.quarkus:quarkus-platform-descriptor-legacy:jar: in central (https://repo.maven.apache.org/maven2)
```

**Comment by ia3andy** [comment]
To reproduce use this code outside in a main outside of quarkus.

**Comment by ia3andy** [comment]
[resolver.zip](https://github.com/quarkusio/quarkus/files/3779907/resolver.zip)

`./mvnw compile quarkus:dev` and hit `http://0.0.0.0:8080/hello`

you get:
```
java.lang.IllegalStateException: Failed to locate 'groupId' in {
  "group-id": "io.quarkus",
  "artifact-id": "quarkus-bom",
  "version": "999-SNAPSHOT"
}
	at io.quarkus.platform.descriptor.resolver.json.QuarkusJsonPlatformDescriptorResolver.resolveRequired(QuarkusJsonPlatformDescriptorResolver.java:266)
	at io.quarkus.platform.descriptor.resolver.json.QuarkusJsonPlatformDescriptorResolver.resolve(QuarkusJsonPlatformDescriptorResolver.java:151)
	at org.acme.ExampleResource.hello(ExampleResource.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:594)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:468)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:421)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:423)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:365)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:69)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:104)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatchRequestContext(VertxRequestHandler.java:83)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:70)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Resulted in: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalStateException: Failed to locate 'groupId' in {
  "group-id": "io.quarkus",
  "artifact-id": "quarkus-bom",
  "version": "999-SNAPSHOT"
}
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
	... 14 more
```

run `mvn test` and you get the exception in the issue

**Comment by ia3andy** [comment]
I had a wrong (renamed) dependency in my cache making things fail
