### ISSUE TITLE
infinispan-embedded fails on macOS

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#4945]
integration-tests/infinispan-embedded fails on macOS (using OpenJDK 64-Bit GraalVM CE 19.2.0.1 (build 25.222-b08-jvmci-19.2-b02, mixed mode))

I thought it's related to multicast on macOS so I tried to apply steps from https://github.com/belaban/JGroups/wiki/Multicast-routing-on-Mac-OS. Adding route for localhost didn't help. 
Running infinispan-embedded on Windows machine works well, no failure.

```
[INFO] Running io.quarkus.it.infinispan.embedded.InfinispanEmbeddedFunctionalityTest
2019-10-28 20:27:40,611 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-10-28 20:27:42,028 INFO  [io.qua.resteasy] (build-8) Resteasy running without servlet container.
2019-10-28 20:27:42,028 INFO  [io.qua.resteasy] (build-8) - Add quarkus-undertow to run Resteasy within a servlet container
2019-10-28 20:27:42,066 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1455ms
2019-10-28 20:27:42,652 WARN  [org.inf.com.uti.StringPropertyReplacer] (main) ISPN000901: Property jgroups.dns.query could not be replaced as intended!
2019-10-28 20:27:42,655 WARN  [org.inf.com.uti.StringPropertyReplacer] (main) ISPN000901: Property jgroups.s3.region_name could not be replaced as intended!
2019-10-28 20:27:42,656 WARN  [org.inf.com.uti.StringPropertyReplacer] (main) ISPN000901: Property jgroups.s3.bucket_name could not be replaced as intended!
2019-10-28 20:27:42,659 WARN  [org.inf.com.uti.StringPropertyReplacer] (main) ISPN000901: Property jgroups.google.bucket_name could not be replaced as intended!
2019-10-28 20:27:42,664 WARN  [org.inf.com.uti.StringPropertyReplacer] (main) ISPN000901: Property jboss.jgroups.azure_ping.storage_account_name could not be replaced as intended!
2019-10-28 20:27:42,665 WARN  [org.inf.com.uti.StringPropertyReplacer] (main) ISPN000901: Property jboss.jgroups.azure_ping.storage_access_key could not be replaced as intended!
2019-10-28 20:27:42,803 INFO  [org.inf.con.par.Parser] (main) ISPN000293: Ignoring XML attribute aliases at [107,161], please remove from configuration file
2019-10-28 20:27:42,807 INFO  [org.inf.con.par.Parser] (main) ISPN000293: Ignoring XML attribute jndi-name at [107,161], please remove from configuration file
2019-10-28 20:27:42,807 INFO  [org.inf.con.par.Parser] (main) ISPN000293: Ignoring XML attribute module at [107,161], please remove from configuration file
2019-10-28 20:27:42,867 INFO  [org.inf.con.par.Parser] (main) ISPN000293: Ignoring XML attribute module at [141,75], please remove from configuration file
2019-10-28 20:27:42,891 WARN  [org.inf.con.par.Parser] (main) ISPN000551: The custom interceptors configuration has been deprecated and will be ignored in the future
2019-10-28 20:27:42,901 INFO  [org.inf.con.par.Parser] (main) ISPN000293: Ignoring XML attribute module at [322,98], please remove from configuration file
2019-10-28 20:27:42,935 WARN  [org.inf.con.cac.AbstractStoreConfigurationBuilder] (main) ISPN000149: Fetch persistent state and purge on startup are both disabled, cache may contain stale entries on startup
2019-10-28 20:27:42,935 INFO  [org.inf.con.cac.MemoryConfigurationBuilder] (main) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
2019-10-28 20:27:42,946 WARN  [org.inf.con.cac.AbstractStoreConfigurationBuilder] (main) ISPN000437: Unable to validate CustomStoreConfiguration with the implementing store as the @ConfigurationFor annotation is missing
2019-10-28 20:27:42,947 WARN  [org.inf.con.cac.AbstractStoreConfigurationBuilder] (main) ISPN000149: Fetch persistent state and purge on startup are both disabled, cache may contain stale entries on startup
2019-10-28 20:27:42,947 INFO  [org.inf.con.cac.MemoryConfigurationBuilder] (main) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
2019-10-28 20:27:42,948 WARN  [org.inf.con.cac.AbstractStoreConfigurationBuilder] (main) ISPN000149: Fetch persistent state and purge on startup are both disabled, cache may contain stale entries on startup
2019-10-28 20:27:42,950 WARN  [org.inf.con.cac.AbstractStoreConfigurationBuilder] (main) ISPN000149: Fetch persistent state and purge on startup are both disabled, cache may contain stale entries on startup
2019-10-28 20:27:42,950 INFO  [org.inf.con.cac.MemoryConfigurationBuilder] (main) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
2019-10-28 20:27:42,951 WARN  [org.inf.con.cac.AbstractStoreConfigurationBuilder] (main) ISPN000149: Fetch persistent state and purge on startup are both disabled, cache may contain stale entries on startup
2019-10-28 20:27:42,952 WARN  [org.inf.con.cac.AbstractStoreConfigurationBuilder] (main) ISPN000149: Fetch persistent state and purge on startup are both disabled, cache may contain stale entries on startup
2019-10-28 20:27:42,953 INFO  [org.inf.con.cac.MemoryConfigurationBuilder] (main) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
2019-10-28 20:27:42,953 WARN  [org.inf.con.cac.AbstractStoreConfigurationBuilder] (main) ISPN000149: Fetch persistent state and purge on startup are both disabled, cache may contain stale entries on startup
2019-10-28 20:27:42,953 INFO  [org.inf.con.cac.MemoryConfigurationBuilder] (main) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
2019-10-28 20:27:43,221 INFO  [org.inf.fac.GlobalComponentRegistry] (main) ISPN000128: Infinispan version: Infinispan 'N/A' 10.0.0.CR1
2019-10-28 20:27:43,225 INFO  [org.inf.mar.per.imp.PersistenceMarshallerImpl] (main) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.JavaSerializationMarshaller'
2019-10-28 20:27:43,380 INFO  [org.inf.rem.tra.jgr.JGroupsTransport] (main) ISPN000078: Starting JGroups channel maximal-cluster
2019-10-28 20:27:48,469 INFO  [org.jgr.pro.pbc.GMS] (main) a-node-51652(site-id=c, rack-id=b, machine-id=a): no members discovered after 5005 ms: creating cluster as first member
2019-10-28 20:27:48,487 INFO  [org.inf.CLUSTER] (main) ISPN000094: Received new cluster view for channel maximal-cluster: [a-node-51652(site-id=c, rack-id=b, machine-id=a)|0] (1) [a-node-51652(site-id=c, rack-id=b, machine-id=a)]
2019-10-28 20:27:48,568 INFO  [org.inf.rem.tra.jgr.JGroupsTransport] (main) ISPN000079: Channel maximal-cluster local address is a-node-51652(site-id=c, rack-id=b, machine-id=a), physical addresses are [10.20.30.106:7800]
2019-10-28 20:27:48,584 INFO  [org.inf.glo.imp.GlobalStateManagerImpl] (main) ISPN000390: Persisted state, version=10.0.0.CR1 timestamp=2019-10-28T19:27:48.575Z
2019-10-28 20:27:49,010 INFO  [io.qua.it.inf.emb.TestServlet] (main) The application is starting...
2019-10-28 20:27:49,011 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 6.914s. Listening on: http://0.0.0.0:8081
2019-10-28 20:27:49,011 INFO  [io.quarkus] (main) Profile test activated.
2019-10-28 20:27:49,011 INFO  [io.quarkus] (main) Installed features: [cdi, infinispan-embedded, narayana-jta, resteasy]
Running cache test for simple-cache
Running cache test for quarkus-transaction
Running cache test for local
Running cache test for off-heap-memory
Running cluster test
[ERROR] Tests run: 5, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 10.462 s <<< FAILURE! - in io.quarkus.it.infinispan.embedded.InfinispanEmbeddedFunctionalityTest
[ERROR] testPutWithoutTransactionNotRolledBack  Time elapsed: 0.765 s  <<< FAILURE!
java.lang.AssertionError:
1 expectation failed.
Response body doesn't match expectation.
Expected: is "null"
  Actual:

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:493)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:671)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:98)
	at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:238)
	at io.restassured.internal.ValidatableResponseImpl.super$2$body(ValidatableResponseImpl.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
	at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy:293)
	at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
	at io.quarkus.it.infinispan.embedded.InfinispanEmbeddedFunctionalityTest.testPutWithoutTransactionNotRolledBack(InfinispanEmbeddedFunctionalityTest.java:43)
...
```

**Comment by gastaldi** [comment]
Closing as the extension was removed from the Quarkus Core and the integration tests no longer exist
