### ISSUE TITLE
quarkus-amazon-dynamodb and quarkus-smallrye-fault-tolerance combination causes CNFE

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#5115]
quarkus-amazon-dynamodb and quarkus-smallrye-fault-tolerance combination causes CNFE
java.lang.ClassNotFoundException: software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$Builder

url-connection-client is marked as optional - https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-dynamodb/runtime/pom.xml#L45

Steps to reproduce:
use microprofile-fault-tolerance-quickstart https://github.com/quarkusio/quarkus-quickstarts/tree/development/microprofile-fault-tolerance-quickstart
```
cd microprofile-fault-tolerance-quickstart
mvn quarkus:add-extension -Dextensions="quarkus-amazon-dynamodb"
mvn clean verify
```

```
[INFO] Running org.acme.faulttolerance.CoffeeResourceTest
2019-11-01 13:40:34,689 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-11-01 13:40:35,969 INFO  [io.qua.resteasy] (build-22) Resteasy running without servlet container.
2019-11-01 13:40:35,969 INFO  [io.qua.resteasy] (build-22) - Add quarkus-undertow to run Resteasy within a servlet container
2019-11-01 13:40:36,007 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1318ms
java.lang.NoClassDefFoundError: software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient$Builder
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2310)
	at io.quarkus.smallrye.faulttolerance.runtime.SmallryeFaultToleranceRecorder.getMethodsForValidation(SmallryeFaultToleranceRecorder.java:93)
	at io.quarkus.smallrye.faulttolerance.runtime.SmallryeFaultToleranceRecorder.validate(SmallryeFaultToleranceRecorder.java:52)
	at io.quarkus.deployment.steps.SmallRyeFaultToleranceProcessor$validateFaultToleranceAnnotations20.deploy_0(SmallRyeFaultToleranceProcessor$validateFaultToleranceAnnotations20.zig:206)
	at io.quarkus.deployment.steps.SmallRyeFaultToleranceProcessor$validateFaultToleranceAnnotations20.deploy(SmallRyeFaultToleranceProcessor$validateFaultToleranceAnnotations20.zig:36)
	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:121)
	at io.quarkus.runtime.Application.start(Application.java:94)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:143)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:248)
	at io.quarkus.test.junit.QuarkusTestExtension.createTestInstance(QuarkusTestExtension.java:393)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:285)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:275)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:77)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:258)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:252)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:251)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:29)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:106)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:105)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$Builder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 62 more
```

**Comment by gsmet** [comment]
@marcinczeczko could you have a look to this one?

I wonder if it's just not having added the additional jar but the error should really be more user-friendly if it's the case (and be only triggered if some config properties have been set).

**Comment by rsvoboda** [comment]
Adding the dependency to app's pom.xml is workaround for this issue
```
        <dependency>  <!-- workaround for https://github.com/quarkusio/quarkus/issues/5115 -->
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>url-connection-client</artifactId>
        </dependency>
```

+1 for better message

**Comment by marcinczeczko** [comment]
In general the exception should be thrown if you're not using any dybamodb client, so looks like there is some issue in there. I'll take a look this weekend

**Comment by marcinczeczko** [comment]
I found that if extension is just added to the project, during the validation phase the https://github.com/quarkusio/quarkus/blob/fc510298c26703115d0482a1b2a4cb1a1f1e48bf/extensions/smallrye-fault-tolerance/deployment/src/main/java/io/quarkus/smallrye/faulttolerance/deployment/SmallRyeFaultToleranceProcessor.java#L179 method gets beans from validationPhase build item. Among all the beans there is DynamodbClientProducer bean that fails the validation.

@gsmet is there something that can prevent doing that ? Maybe it's a bug in the fault tollerance processor that doesn't filter out beans that shouldn't be validated..

**Comment by marcinczeczko** [comment]
Looks like the `SmallRyeFaultToleranceProcessor` in the runtime causes all other extensions to run recorders even if extension is not used.
E.g. if `quarkus-oidc` extension added I see
```
[INFO] Running org.acme.faulttolerance.CoffeeResourceTest
2019-11-07 12:52:02,486 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-11-07 12:52:03,731 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1245ms
java.lang.RuntimeException: java.net.MalformedURLException: no protocol: /.well-known/openid-configuration
        at io.vertx.ext.auth.oauth2.impl.OAuth2API.makeRequest(OAuth2API.java:112)
        at io.vertx.ext.auth.oauth2.providers.OpenIDConnectAuth.discover(OpenIDConnectAuth.java:42)
        at io.vertx.ext.auth.oauth2.providers.KeycloakAuth.discover(KeycloakAuth.java:120)
```
I'm not sure, but maybe it's an expected behaviour....

**Comment by marcinczeczko** [comment]
Ignore my previous thinking :) Actually it helped me to find out what's wrong. See the PR#5280
