### ISSUE TITLE
Regression in 0.27.0. Gradle's `quarkusDev` reports classes not registered for Reflection.

### ISSUE THREAD

**Issue by soberich** [quarkusio/quarkus#5128]
Gradle's `quarkusDev` reports classes not registered for Reflection in `0.27.0` while in `0.26.1` no such reporting occur.
I did not investigate are they really stopped being registered. The project is a playground and doesn't play well with Quarkus basically.

**To Reproduce**
Steps to reproduce the behaviour:

```console
git clone git@github.com:soberich/marvel.git marvel && cd $_ && ./gradlew quarkusDev
```
with `0.26.1`
it starts up fine logging:
```console
2019-11-02 13:25:43,358 INFO  [io.quarkus] (main) Quarkus 0.26.1 started in 4.321s. Listening on: http://0.0.0.0:8080
2019-11-02 13:25:43,358 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2019-11-02 13:25:43,358 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, kotlin, narayana-jta, rest-client, resteasy, resteasy-jackson, servlet, smallrye-context-propagation, smallrye-reactive-streams-operators, spring-data-jpa, spring-di, spring-web, vertx]
```

if change `0.26.1` to `0.27.0` in https://github.com/soberich/marvel/blob/4a2ce34dba65690e062d08390dc0b53e20f1459c/buildSrc/src/main/kotlin/versioning/Platforms.kt#L11 it fails with:
```console
> Task :time-service:app:classes
Listening for transport dt_socket at address: 5005
12:49:46,331 INFO  [io.qua.dep.QuarkusAugmentor] Beginning quarkus augmentation
12:49:46,756 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
12:49:46,991 INFO  [org.hib.jpa.boo.int.PersistenceXmlParser] HHH000318: Could not find any META-INF/persistence.xml file in the classpath
12:49:47,116 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- com.example.marvel.api.EmployeeCommand$EmployeeCreateCommand
	- com.example.marvel.api.EmployeeCommand$EmployeeUpdateCommand
	- com.example.marvel.api.EmployeeDetailedView
	- com.example.marvel.api.EmployeeView
	- com.example.marvel.api.RecordCollectionCommand$RecordCollectionCreateCommand
	- com.example.marvel.api.RecordCollectionCommand$RecordCollectionUpdateCommand
	- com.example.marvel.api.RecordCollectionDetailedView
	- com.example.marvel.api.RecordDetailedView
	- com.example.marvel.api.RecordType
	- com.example.marvel.api.RecordView
	- io.reactivex.Flowable
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
12:49:47,143 INFO  [org.hib.Version] HHH000412: Hibernate Core {5.4.8.Final}
12:49:47,441 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus, attempting to start hot replacement endpoint to recover
```

trying to resolve **uncomment**:
1. https://github.com/soberich/marvel/blob/4a2ce34dba65690e062d08390dc0b53e20f1459c/time-service/app/build.gradle.kts#L42 (unfortunately Quarkus can't see `runtime` dependencies, this also limits Gradle users to specify all dependencies in `implementation`, even some webjars won't be seen in `runtimeOnly` in Quarkus Development mode. 

2. https://github.com/soberich/marvel/blob/4a2ce34dba65690e062d08390dc0b53e20f1459c/time-service/app/src/main/resources/application.properties#L12-L15
3. https://github.com/soberich/marvel/blob/4a2ce34dba65690e062d08390dc0b53e20f1459c/build.gradle.kts#L45-L64 this one to copy `beans.xml` primarily (though it was working without this coping before).

**Configuration**
```properties
# suppress inspection "UnusedProperty" for whole file
quarkus.log.category."org.hibernate.SQL".level                 = TRACE
quarkus.log.category."org.hibernate.type".level                = TRACE
quarkus.log.category."org.hibernate.type.descriptor.sql".level = TRACE

quarkus.datasource.driver=org.h2.Driver
##quarkus.datasource.url      = jdbc:h2:retry:./build/h2db/db/marvel;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
quarkus.datasource.url      = jdbc:h2:mem:marvel;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
quarkus.datasource.username = sa
quarkus.datasource.password = ""

#quarkus.index-dependency.marvel-api.group-id=io.arrow-kt
#quarkus.index-dependency.marvel-api.artifact-id=arrow-core-data
#quarkus.index-dependency.marvel-spi.group-id=io.reactivex.rxjava2
#quarkus.index-dependency.marvel-spi.artifact-id=rxjava

```

Happy to see better support for Gradle.
https://github.com/quarkusio/quarkus/issues/5101
Now I would say the main trouble is that every Quarkus version changes the behaviour of Gradle integration quite significantly.

**Environment (please complete the following information):**
Darwin MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0:
Java 1.8.0_222

**Comment by gsmet** [comment]
@soberich yeah, things are a bit in flux regarding Gradle at the moment. We are making significant progress though so it should stabilize soon.

I'll let @geoand or @gastaldi answer to you about this.

**Comment by geoand** [comment]
@soberich Thanks for reporting! Indeed Gradle support is in flux. 
I'll hopefully have a look soon although my time is a little limited this week.
@gastaldi feel free to take a look as well if you want to

**Comment by gastaldi** [comment]
Sure, will have a look Monday morning

**Comment by geoand** [comment]
This doesn't really look like a regression in the gradle support. Version `0.27.0` did indeed hide the exception in dev mode so you couldn't really figure out what was going on (but that has been fixed in #5061).
When using the latest `master`  of Quarkus the exception is visible and looks like:

```
01:12:28,307 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.servlet.http.HttpServletRequest and qualifiers [@Default]
        - java member: com.example.marvel.domain.employee.EmployeeOrchestrationResource#setRequest()
        - declared on CLASS bean [types=[com.example.marvel.domain.employee.EmployeeOrchestrationResource], qualifiers=[@Default, @Any], target=com.example.marvel.domain.employee.EmployeeOrchestrationResource]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:850)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:220)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:106)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:251)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.servlet.http.HttpServletRequest and qualifiers [@Default]
        - java member: com.example.marvel.domain.employee.EmployeeOrchestrationResource#setRequest()
        - declared on CLASS bean [types=[com.example.marvel.domain.employee.EmployeeOrchestrationResource], qualifiers=[@Default, @Any], target=com.example.marvel.domain.employee.EmployeeOrchestrationResource]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:404)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
        ... 14 more
```

So I am assuming you need to add `quarkus-undertow`. My guess is that one of the dependencies you have used to depend on undertow in `0.26.1` but that dependency was removed in `0.27.0`.

**Comment by soberich** [comment]
Yeah, well. Really Gradle integration in a dark corner. Thanks @geoand

**Comment by geoand** [comment]
You are welcome!

**Comment by Postremus** [comment]
soberich <notifications@github.com> schrieb am Sa., 2. Nov. 2019, 13:49:
