### ISSUE TITLE
Still seeing channel closed on Firefox and 0.27

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5136]
Swagger UI enabled and with DB but not sure that matters.

```
2019-11-03 13:59:07,266 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-2) HTTP Request to /swagger-ui/favicon-16x16.png failed, error id: 750293f4-dcbb-47b3-b034-f6e67f37dddd-1: java.nio.channels.ClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:958)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:866)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.write(WebSocketServerExtensionHandler.java:139)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
        at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:119)
        at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:161)
        at io.vertx.core.http.impl.Http1xServerConnection.writeToChannel(Http1xServerConnection.java:267)
        at io.vertx.core.net.impl.ConnectionBase.sendFileRegion(ConnectionBase.java:381)
        at io.vertx.core.net.impl.ConnectionBase.sendFile(ConnectionBase.java:408)
        at io.vertx.core.http.impl.Http1xServerConnection.sendFile(Http1xServerConnection.java:456)
        at io.vertx.core.http.impl.HttpServerResponseImpl.doSendFile(HttpServerResponseImpl.java:514)
        at io.vertx.core.http.impl.HttpServerResponseImpl.sendFile(HttpServerResponseImpl.java:433)
        at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:365)
        at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:351)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendFile$11(StaticHandlerImpl.java:457)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.wrapInTCCLSwitch(StaticHandlerImpl.java:266)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.sendFile(StaticHandlerImpl.java:392)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$null$0(StaticHandlerImpl.java:231)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.getFileProps(StaticHandlerImpl.java:299)
        at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:208)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

Consider possible fix for 0.28

**Comment by gsmet** [comment]
We need far more information than that.

**Comment by gsmet** [comment]
I tried to reproduce it with the quickstart in dev mode and couldn't.

**Comment by emmanuelbernard** [comment]
it was Java 8 and based off an alpine container

**Comment by emmanuelbernard** [comment]
image with the jdk is `quay.io/rhdevelopers/tutorial-tools:0.0.3`

Comamnd I ran for info to start the image

```
docker run -ti -p 8090:8080 -v `pwd`/work:/work -v `mvn help:evaluate -Dexpression=settings.localRepository | grep -v '\[INFO\]'`:/opt/developer/.m2/repository --link mariadb:mariadb --rm quay.io/rhdevelopers/tutorial-tools:0.0.3 bash
```

Then I was in `./mvnw compile quarkus:dev`  and hitting http://localhost:8080/swagger-ui with Firefox.

**Comment by gsmet** [comment]
I wasn't able to reproduce it with the quickstart but with this app Emmanuel sent me:

https://www.dropbox.com/s/9e9elhc83g92e7v/fruits-app.zip?dl=0

Starting a MariaDB server:
```
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 --name quarkus_test_mariadb -e MYSQL_USER=demo -e MYSQL_PASSWORD=password -e MYSQL_DATABASE=demodb -e MYSQL_RANDOM_ROOT_PASSWORD=true -p 3306:3306 mariadb:10.4
```

Then:
```
mvn clean compile quarkus:dev
```

Then refreshing http://localhost:8080/swagger-ui/ with Firefox ~20 times quickly, I was able to reproduce it.

**Comment by stuartwdouglas** [comment]
If you are refreshing repeatedly firefox can just drop the connection. We should not be logging these errors at ERROR level, but at DEBUG. Remote clients drop connections all the time, and it is normal.

**Comment by stuartwdouglas** [comment]
@emmanuelbernard what are you doing to get the exception? Does it affect the functionality of the app?

**Comment by emmanuelbernard** [comment]
I don't know if it was breaking the functionality. I have to admit I forgot to check if the favicon was showing up
