### ISSUE TITLE
NoSuchFileException in logs and improper caching in devmode after removing a html file

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#5163]
If there is a static html file in `src/main/resources/META-INF/resources/`, the user starts dev mode, accesses that file over a HTTP request, and then deletes the file and tries the same URL again, this exception will start to appear repeatedly in the log:

```
2019-11-04 10:17:20,409 ERROR [io.qua.dev] (vert.x-worker-thread-4) Failed to copy resources: java.nio.file.NoSuchFileException: /home/jmartisk/Workspace/reproducers/devmode-html-file/my-quarkus-project/target/classes/META-INF/resources/index.html
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForFileChange(RuntimeUpdatesProcessor.java:338)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:122)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:51)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:43)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Moreover, if this file is removed BEFORE there is a HTTP request to it, the contents of that file are cached somewhere and it will still be possible to request it even though the file does not exist anymore.

**Comment by jmartisk** [comment]
https://github.com/quarkusio/quarkus/pull/5165 should fix the log part, haven't yet looked much into the caching thing but that seems to be somewhere on Vert.x level?!

**Comment by machi1990** [comment]
Yeap, I planned to look at this a bit later. Thanks for fixing the logging part.

**Comment by machi1990** [comment]
> #5165 should fix the log part, haven't yet looked much into the caching thing but that seems to be somewhere on Vert.x level?! @machi1990 I see you self-assigned this so perhaps you could find out :)

@jmartisk I pushed a possible fix for this. It also includes your fix for the log. I could not update your PR, so let's open another one that includes the two fixes.
