### ISSUE TITLE
Incorrect error page in dev mode when quarkus-kubernetes is in the classpath

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#5174]
Create a project with `quarkus-kubernetes` as extension.

Then start in dev mode.

Then create a new java file and forget to add a mandatory import (e.g. `List getAll()` without importing `java.util;.List`). You then get the following nasty error

The web page shows

```
java.lang.RuntimeException: Compilation failed[warning: No SupportedSourceVersion annotation found on io.sundr.transform.internal.VelocityTransformationProcessor, returning RELEASE_6., warning: Supported source version 'RELEASE_6' from annotation processor 'io.sundr.transform.internal.VelocityTransformationProcessor' less than -source '1.8', warning: No SupportedSourceVersion annotation found on io.sundr.resourcecify.internal.processor.ResourcecifyProcessor, returning RELEASE_6., warning: Supported source version 'RELEASE_6' from annotation processor 'io.sundr.resourcecify.internal.processor.ResourcecifyProcessor' less than -source '1.8', warning: No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.BuildableProcessor, returning RELEASE_6., warning: Supported source version 'RELEASE_6' from annotation processor 'io.sundr.builder.internal.processor.BuildableProcessor' less than -source '1.8', warning: No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.ExternalBuildableProcessor, returning RELEASE_6., warning: Supported source version 'RELEASE_6' from annotation processor 'io.sundr.builder.internal.processor.ExternalBuildableProcessor' less than -source '1.8', /work/fruits-app/src/main/java/com/example/FruitResource.java:36: error: cannot find symbol

The stacktrace below has been reversed to show the root cause first. Click Here to see the original stacktrace

java.lang.RuntimeException: Compilation failed[warning: No SupportedSourceVersion annotation found on io.sundr.transform.internal.VelocityTransformationProcessor, returning RELEASE_6., warning: Supported source version 'RELEASE_6' from annotation processor 'io.sundr.transform.internal.VelocityTransformationProcessor' less than -source '1.8', warning: No SupportedSourceVersion annotation found on io.sundr.resourcecify.internal.processor.ResourcecifyProcessor, returning RELEASE_6., warning: Supported source version 'RELEASE_6' from annotation processor 'io.sundr.resourcecify.internal.processor.ResourcecifyProcessor' less than -source '1.8', warning: No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.BuildableProcessor, returning RELEASE_6., warning: Supported source version 'RELEASE_6' from annotation processor 'io.sundr.builder.internal.processor.BuildableProcessor' less than -source '1.8', warning: No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.ExternalBuildableProcessor, returning RELEASE_6., warning: Supported source version 'RELEASE_6' from annotation processor 'io.sundr.builder.internal.processor.ExternalBuildableProcessor' less than -source '1.8', /work/fruits-app/src/main/java/com/example/FruitResource.java:36: error: cannot find symbol
    public List<FruityVice> getAll() {
           ^
  symbol:   class List
  location: class com.example.FruitResource]
	at io.quarkus.dev.JavaCompilationProvider.compile(JavaCompilationProvider.java:59)
	at io.quarkus.dev.ClassLoaderCompiler.compile(ClassLoaderCompiler.java:181)
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:186)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:121)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:51)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:43)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

Does annotation processors leaks somehow. CC @geoand

**Comment by geoand** [comment]
@iocanel we stumbled upon this one. Is perhaps one of the jar dependencies adding annotation processing stuff by mistake?

**Comment by iocanel** [comment]
Can you assign the issue to me?

**Comment by iocanel** [comment]
VelocityTransformationProcessor is a dekorate transitive.
It should be marked as compile and optional to avoid issues like this.
Apparently, stopped being the case possibly when we added support for Openshift.

**Comment by geoand** [comment]
I can't seem to assign it to you, but consider it your

**Comment by iocanel** [comment]
I created a pull request that should fix the issue for now.
And also verified that I don't get this issue following the steps @emmanuelbernard described.
