### ISSUE TITLE
Apple keychain store not working with Java 11

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#5337]
Apple security keychain store not working with Java 11

```
Error: Unsupported method apple.security.KeychainStore._getEncodedKeyData(long, char[]) is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Call path from entry point to apple.security.KeychainStore._getEncodedKeyData(long, char[]):
	at apple.security.KeychainStore._getEncodedKeyData(KeychainStore.java)
	at java.base@11.0.4/apple.security.KeychainStore.engineGetKey(KeychainStore.java:180)
	at java.base@11.0.4/java.security.KeyStore.getKey(KeyStore.java:1057)
	at io.vertx.core.net.impl.KeyStoreHelper.<init>(KeyStoreHelper.java:164)
	at io.vertx.core.net.impl.KeyStoreHelper.create(KeyStoreHelper.java:84)
	at io.vertx.core.net.KeyCertOptions.getKeyManagerFactory(KeyCertOptions.java:53)
	at io.vertx.core.net.impl.SSLHelper.getKeyMgrFactory(SSLHelper.java:308)
	at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:261)
	at io.vertx.core.net.impl.SSLHelper.lambda$getContext$2(SSLHelper.java:493)
	at io.vertx.core.net.impl.SSLHelper$$Lambda$998/0x00000007c11a1440.apply(Unknown Source)
	at java.base@11.0.4/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base@11.0.4/java.util.stream.SpinedBuffer.forEach(SpinedBuffer.java:246)
	at java.base@11.0.4/java.util.stream.SpinedBuffer.toString(SpinedBuffer.java:269)
	at java.base@11.0.4/java.lang.String.valueOf(String.java:2951)
	at java.base@11.0.4/java.io.PrintStream.print(PrintStream.java:745)
	at app//com.oracle.svm.core.thread.JavaThreads.dispatchUncaughtException(JavaThreads.java:556)
	at app//com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:157)
	at app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
```

**Comment by galderz** [comment]
`NettyProcessor` checks the existence of a certain class and enables JNI depending on that. A similar thing might work, but we'd only want to happen with Java 11.

**Comment by rsvoboda** [comment]
This is native only issue ?

**Comment by galderz** [comment]
I believe it was @rsvoboda. I'll try to replicate again.

**Comment by galderz** [comment]
Unable to replicate it any more with more recent graal master checkouts.
