### ISSUE TITLE
java.lang.LinkageError from quarkus:dev but not from java -jar 

### ISSUE THREAD

**Issue by brunoabdon** [quarkusio/quarkus#5354]
**Describe the bug**
Quarkus startup fails with `java.lang.LinkageError` from a specific seemingly unharmful combination of facts:

* The app has a JAX `@Path` resource that extends a super from "_dependency-b_"
* This JAX resource overrides a method from its super that returns a `ReturnType` from "_dependency-a_"
* "_dependency-a_" has a class annotated with [`@MappedSuperClass`](https://javaee.github.io/javaee-spec/javadocs/javax/persistence/MappedSuperclass.html) (that is never used).

**Expected behavior**
Startup with `mvn quarkus:dev` should not fail with `java.lang.LinkageError`

**Actual behavior**
Quarkust fails to start, complaining about `java.lang.LinkageError`.

**To Reproduce**
1. Clone this showcase
`git clone git@github.com:brunoabdon/quarkus-issue.git`
2. Build dependency-a
`cd quarkus-issue/dependency-a/`
`mvn package install`
3. Build dependency-b
`cd ../dependency-b/`
`mvn package install`
4. Build and run the quarkus-app 
`cd ../quarkus-app/`
`mvn quarkus:dev`

**Configuration**
It's already at `git@github.com:brunoabdon/quarkus-issue.git`

**Screenshots**
<pre>
22:10:21,454 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:142)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:177)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:95)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:326)
	... 9 more
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "com/github/brunoabdon/quarkus/ReturnType"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.jboss.resteasy.spi.metadata.ResourceBuilder.processDeclaredSetters(ResourceBuilder.java:1129)
	at org.jboss.resteasy.spi.metadata.ResourceBuilder.processSetters(ResourceBuilder.java:1078)
	at org.jboss.resteasy.spi.metadata.ResourceBuilder.fromAnnotations(ResourceBuilder.java:918)
	at org.jboss.resteasy.spi.metadata.ResourceBuilder.getRootResourceFromAnnotations(ResourceBuilder.java:878)
	at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.<init>(POJOResourceFactory.java:40)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:88)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.registration(ResteasyDeploymentImpl.java:474)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:289)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:90)
	at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.staticInit(ResteasyStandaloneRecorder.java:85)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit27.deploy_0(ResteasyStandaloneBuildStep$staticInit27.zig:826)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit27.deploy(ResteasyStandaloneBuildStep$staticInit27.zig:845)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:312)
</pre>
**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
`Linux vasti 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
<pre>
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
</pre>
 - GraalVM version (if different from Java):
None
 - Quarkus version or git rev: 
`1.0.0.CR1`
**Additional context**
(Add any other context about the problem here.)

**Comment by brunoabdon** [comment]
Important to notice that, while starting the app with `mvn quarkus:dev`causes the `java.lang.LinkageError`, this doesn't happens when running the same build with `java -jar target/java -jar target/quarkus-app-0.0.1-SNAPSHOT.jar`

**Comment by gsmet** [comment]
@stuartwdouglas could you have a look to that one?

**Comment by stuartwdouglas** [comment]
I think https://github.com/quarkusio/quarkus/pull/5106 will fix this
