### ISSUE TITLE
Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers

### ISSUE THREAD

**Issue by 4ntoine** [quarkusio/quarkus#5521]
**Describe the bug**
Quarkus does not inject `EntityManager` given `application.properties` is created and 2 module dependencies are added in `pom.xml`

**Expected behavior**
`EntityManager` is injected into controller to the field marked with `@Inject`

**Actual behavior**
`./mvnw compile quarkus:dev` result in error:
```
...
[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]
...
```

**To Reproduce**
1. git clone git@github.com:4ntoine/NotesServerApp.git
2. git checkout issue-5-quarkus-maven
3. ./gradlew publishToMavenLocal
4. cd app-quarkus
5. ./mvnw compile quarkus:dev

**Configuration**
```properties
quarkus.datasource.url = jdbc:h2:mem:notes
quarkus.datasource.driver = org.h2.Driver

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=drop-and-create
```

**Screenshots**
<img width="1410" alt="Снимок экрана 2019-11-15 в 22 29 20" src="https://user-images.githubusercontent.com/846671/68962880-6b7ea580-07f7-11ea-99cd-455dd72d6e14.png">

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
> Darwin MBP-Anton.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: `1.0.0.CR1`

**Additional context**
I've also tried to make it running with Gradle (https://github.com/quarkusio/quarkus/issues/5488).

**Also i've tried to generate a project with code.quarkus.io and modify it to inject `EntityManager` and i have the same issue** (attaching zip file with modified project files).
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/3852573/code-with-quarkus.zip)

So it makes me think smth is wrong and i'm not sure if it's me who configured it incorrectly or it's indeed some bug in Quarkus. Let me know if i can help with anything or please point on how to configure it the right way.

PS. I can see in the log:

> 22:37:57,565 INFO  [org.hib.jpa.boo.int.PersistenceXmlParser] HHH000318: Could not find any META-INF/persistence.xml file in the classpath

But i guess it's ok (as we intentionally follow the way without it).

Also i'd like to note that there are no db entities (marked with `@Entity` classes) in the source code, but i think it should not prevent `EntityManager` from being instantiated and injected, but just no entities tracked by EntityManager.

Here is run log for code-with-quarkus app:
```
~/Downloads/code-with-quarkus asmirnov$./mvnw compile quarkus:dev
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ code-with-quarkus ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- kotlin-maven-plugin:1.3.21:compile (compile) @ code-with-quarkus ---
[INFO] Applied plugin: 'all-open'
[INFO] 
[INFO] --- quarkus-maven-plugin:1.0.0.CR1:dev (default-cli) @ code-with-quarkus ---
Listening for transport dt_socket at address: 5005
22:37:56,774 INFO  [io.qua.dep.QuarkusAugmentor] Beginning quarkus augmentation
22:37:57,281 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
22:37:57,565 INFO  [org.hib.jpa.boo.int.PersistenceXmlParser] HHH000318: Could not find any META-INF/persistence.xml file in the classpath
22:37:57,736 INFO  [org.hib.Version] HHH000412: Hibernate Core {5.4.8.Final}
22:37:57,935 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]
	- java member: org.acme.ExampleResource#entityManager
	- declared on CLASS bean [types=[org.acme.ExampleResource], qualifiers=[@Default, @Any], target=org.acme.ExampleResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:850)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:220)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:106)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]
	- java member: org.acme.ExampleResource#entityManager
	- declared on CLASS bean [types=[org.acme.ExampleResource], qualifiers=[@Default, @Any], target=org.acme.ExampleResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:404)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
	... 14 more

	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:157)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:177)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:95)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]
	- java member: org.acme.ExampleResource#entityManager
	- declared on CLASS bean [types=[org.acme.ExampleResource], qualifiers=[@Default, @Any], target=org.acme.ExampleResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:850)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:220)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:106)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]
	- java member: org.acme.ExampleResource#entityManager
	- declared on CLASS bean [types=[org.acme.ExampleResource], qualifiers=[@Default, @Any], target=org.acme.ExampleResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:404)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
	... 14 more

	at io.quarkus.builder.Execution.run(Execution.java:108)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:121)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:130)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:111)
	... 3 more
Caused by: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]
	- java member: org.acme.ExampleResource#entityManager
	- declared on CLASS bean [types=[org.acme.ExampleResource], qualifiers=[@Default, @Any], target=org.acme.ExampleResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:850)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:220)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:106)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.persistence.EntityManager and qualifiers [@Default]
	- java member: org.acme.ExampleResource#entityManager
	- declared on CLASS bean [types=[org.acme.ExampleResource], qualifiers=[@Default, @Any], target=org.acme.ExampleResource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:404)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:212)
	... 14 more

22:37:57,937 INFO  [io.qua.dev.DevModeMain] Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
```

**Comment by gsmet** [comment]
It might be a stupid question but do you have at least one entity and are they properly detected?

They need to be indexed in Jandex.

**Comment by 4ntoine** [comment]
@gsmet Hi, thanks for the reply. I've noted it:
> Also i'd like to note that there are no db entities (marked with @Entity classes) in the source code, but i think it should not prevent EntityManager from being instantiated and injected, but just no entities tracked by EntityManager.

I guess "missing dependency" and "misconfigured EM" are different things

**Comment by gsmet** [comment]
Ah sorry, I read too fast.

We decided to not create the EM if we don't have any entity so that's why you have this issue.

It's a conscious decision, I don't think we will change that.

/cc @Sanne

**Comment by 4ntoine** [comment]
Ok, but again i think it makes sense to output the reason for better understanding. 
I will add 1 entity and retry to double check.
Thanks for the explanation.

However in updated generated there are no db entities, but in my project there is a [dependency](https://github.com/4ntoine/NotesServerApp/blob/issue-5-quarkus-maven/app-quarkus/pom.xml#L39) to `db` module and there is an [entity](https://github.com/4ntoine/NotesServerApp/blob/issue-5-quarkus-maven/infra-gateway-jpa/src/main/kotlin/name/antonsmirnov/notes/db/Note.kt#L7).

So i guess Quarkus did not find entities in transitive jar or it's smth else wrong.

**Comment by 4ntoine** [comment]
Yup, i've modified the file in generated project to be the following (added 1 db entity):
```
package org.acme

import javax.ws.rs.GET
import javax.ws.rs.Path
import javax.ws.rs.Produces
import javax.ws.rs.core.MediaType
import javax.persistence.EntityManager
import javax.inject.Inject
import javax.persistence.*

@Entity
class DbEntity {
    @Id
    var id: Int = 0

    @Column
    var title: String = ""
}

@Path("/hello")
class ExampleResource {

    @Inject
    lateinit var entityManager: EntityManager

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    fun hello() = "hello from " + entityManager.toString()
}
```

Now i can compile and run and the output is good:
> hello from io.quarkus.hibernate.orm.runtime.JPAResourceReferenceProvider$1@5dfb7367

So i guess the problem is in transitive jar which is not reached by Quarkus. Any thoughts on it?

**Comment by Sanne** [comment]
Regarding the last issue, you might be hitting this extra requirement?
 - https://quarkus.io/guides/hibernate-orm#defining-entities-in-external-projects-or-jars

Regarding the NPE on missing entities, I agree we should provide for a better error message. Could you choose between re-purposing the description/title of this issue or open a new one?

**Comment by 4ntoine** [comment]
@Sanne Thanks for the link, i will try.

> Could you choose between re-purposing the description/title of this issue or open a new one?
Well, this was a combination of 2 issues. I guess transitive jar is the major one. Please do what you feel is better here.

**Comment by 4ntoine** [comment]
> .. by adding an empty META-INF/beans.xml file..

I [did it](https://github.com/4ntoine/NotesServerApp/blob/issue-5-quarkus-maven/app-quarkus/src/main/resources/META-INF/beans.xml) but it did not help, still having the same issue.

**Comment by Sanne** [comment]
hi @4ntoine 

the `META-INF/beans.xml` resource shuld not be added to your main application but to each jar that you want Quarkus to "scan" for any additional components.

So in this case you need to add it to `infra-gateway-jpa/src/main/resources/META-INF/beans.xml`

I tested it locally, and works as expected so I'll close this :)

**Comment by Sanne** [comment]
I've created #5525 as follow up.

**Comment by 4ntoine** [comment]
@Sanne awesome, thanks!

However i doubt it's good approach as it requires modification of existing modules - it prevents reusage of existing modules. It can be highly undesired to ask people to recompile the jars  because of 2 reasons:
1) "cost": recompilation takes time and can be pretty "expensive"
2) conceptual: it means you suggest to add some knowledge about the framework into that transitive modules and it can be undesired to add this coupling.

So i'd suggest to have at least an alternative solution - probably having some xml right in end app (app-quarkus) that uses the jars. Any existing alternative solution i'm not aware of or you can suggest instead?

**Comment by Sanne** [comment]
@4ntoine yes it's actuaully not required to modify existing modules, you can also use a configuration property `quarkus.index-dependency to register a jar for indexing without modifying it.

It's mentioned in the CDI guide:
 - https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index

**Comment by 4ntoine** [comment]
@Sanne Thanks for linking. It's very unclear what should be indexed and why. I want to say that nobody wants to cause you troubles explicitly and such tickets are created as it's very unclear how to do it properly.

This is very unclear default behaviour - to index only what is presented in **exactly this one module**. So i'd prefer to have this index to be included by default for all the transitive deps or it to be clearly documented like follows (list of use cases - jpa entities, any usage of cdi) or annotations (if some class annotated with the following annotations included in transitive jars).

BTW is it correct that the only reason  NOT to scan for all the transitive deps is just performance (compilation time)?

**Comment by ahmedabbas11** [comment]
i got this issue while using bdd and dbunit, so i started with the test code and tried to use dbunit. when application failed to get datasource, i didn't think i would need at least an entity to make quarkus create entity manager bean.
so when i created the entity class, it worked but it will be confusing for every one using either TDD or BDD
