### ISSUE TITLE
Interface with RegisterRestClient doesn't inherit Rest API definitions correctly.

### ISSUE THREAD

**Issue by zerocode** [quarkusio/quarkus#5527]
**Describe the bug**
When using an interface to describe a rest API, interfaces that inherit that API and are annotated with RegisterRestClient, don't appear to inherit the API's definition. When adding a Path annotation to the client interface, the test passes instead of throwing 404.

**Expected behavior**
It should be possible to inherit API definitions and for the injected client to respect them, so they are only defined in one place. For example, this is the code I expect to behave correctly:

```
@Path("/api")
interface GreetingAPI {
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("/hello")
    fun hello(): String
}

@RegisterRestClient
interface GreetingClient : GreetingAPI
```
With the following test:

```
@QuarkusTest
open class GreetingEndpointTest {

    @Inject
    @field: RestClient
    lateinit var client: GreetingClient

    @Test
    fun testHelloEndpoint() {
        val response = client.hello()
        assert(response == "hello")
    }
}
```

In order to get this example to work, I have to apply the Path annotation to the client interface like so. Without the Path annotation it throws a 404.

```
@Path("/api")
@RegisterRestClient
interface GreetingClient : GreetingAPI
```

**Environment (please complete the following information):**
Linux tbox-kubuntu 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu219.04)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu219.04, mixed mode, sharing)

**Comment by geoand** [comment]
cc @kenfinnigan @michalszynkiewicz

**Comment by kenfinnigan** [comment]
@zerocode which version of Quarkus are you using?

**Comment by zerocode** [comment]
@kenfinnigan 1.0.0.CR1

**Comment by kenfinnigan** [comment]
The TCK has a test for this situation: https://github.com/eclipse/microprofile-rest-client/blob/master/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/interfaces/ssl/ClientWithKeystoreFromClasspathAndTruststore.java

Maybe it's a problem with Kotlin, as that looks like what you're using?

Can you verify if there's a problem without Kotlin?

**Comment by yuhaibohotmail** [comment]
@kenfinnigan  I had same problem in java.
```java
@Path("rest/students")
@Produces("application/json")
@Consumes("application/json")
@RegisterRestClient
public interface StudentResource {
    @GET
    @Path("{name}/{testcode}")
    public Student getSingle(@PathParam("name") String name, @PathParam("testcode") String testcode) ;

    @GET
    @Path("{id}")
    public Student find(@PathParam("id") Long id) ;;

}
```
```java
@RegisterRestClient
public interface RemoteStudentResource  extends   StudentResource {
}
```
```
WARN: CDI container is not available - interceptor bindings declared on RemoteStudentResource will be ignored
Exception in thread "main" javax.ws.rs.WebApplicationException: Unknown error, status code 404
	at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:31)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:53)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:166)
	at com.sun.proxy.$Proxy20.getSingle(Unknown Source)
	at StudentClient.main(StudentClient.java:11)
```

when  I changed interface as blow,  it worked!
```java
@Path("rest/students")
@RegisterRestClient
public interface RemoteStudentResource  extends   StudentResource {
}
```

**Comment by kenfinnigan** [comment]
In the TCK test it doesn't appear to have `@Path` on either interface and it works.

An issue could be that the spec currently doesn't define whether interfaces should be inherited or not

**Comment by yuhaibohotmail** [comment]
If inheritance is supported, many things will be easier in my client side.

**Comment by zerocode** [comment]
It would be good to fix this. It's a useful pattern to be able to separate API from server and client implementations, and share a common definition across both.

**Comment by geoand** [comment]
I agree that this sort of pattern seems useful

**Comment by zerocode** [comment]
Did this ever get looked at? It's still causing pain and would be great if it could be revisited.

**Comment by ambition-consulting** [comment]
Agreed. Why use interface definitions for REST servers and then not make them usable for REST clients?

**Comment by islombektoshev** [comment]
Is there any changes about this issue?

**Comment by michalszynkiewicz** [comment]
@islombektoshev can you check with rest client reactive?

**Comment by doppelrittberger** [comment]
Hi.
Experiencing the same problem. We generate interface from openapi spec and would be really happy if we could use these interfaces for server AND client but for adding @RegisterRestClient you need to extend the interface or is there another way?
Best regards
Markus

**Comment by primozh** [comment]
I'm facing the same issue. We need to extend the generated interface to add @RegisterRestClient and @OidcClientFilter on top. Is there a way to overcome this?

> Hi. Experiencing the same problem. We generate interface from openapi spec and would be really happy if we could use these interfaces for server AND client but for adding @RegisterRestClient you need to extend the interface or is there another way? Best regards Markus

**Comment by doppelrittberger** [comment]
Hi
We solved the problem by creating producer classes which use the RestClientBuilder manually. This way we have more control about the created proxies and can use any interface without modification.
Best regards
Markus Ritter

**Comment by primozh** [comment]
Thanks for the response! I was thinking of something similar so I'll give it a try. If it just complicates things too much, I'll probably leave it as-is (extending the interface).

**Comment by ToniChaz** [comment]
I have the same problem and I have solved it as [doppelrittberger](https://github.com/doppelrittberger) says using the RestClientBuilder:

```
@RequestScoped
public class RestService {

  @Inject
  GeneratedApi api;

  public void save(User user) {
      api.create(user);   
  }
}

@ApplicationScoped
public class ApiProducer {

  @ConfigProperty(name = "quarkus.rest-client.my-api.url")
  String myApiUrl;

  @Produces
  public Api produceApi() {
    try {
      return RestClientBuilder.newBuilder()
          .baseUrl(new URL(myApiUrl))
          .register(AuthorizationHeaderFactory.class)
          .build(Api.class);
    } catch (MalformedURLException e) {
      throw new RuntimeException(e);
    }
  }
}

@Provider
public class AuthorizationHeaderFactory implements ClientRequestFilter {

  @Inject
  JsonWebToken jwt;

  @Override
  public void filter(ClientRequestContext requestContext) {
    requestContext.getHeaders().add("Authorization", "Bearer " + jwt.getRawToken());
  }
}
```

In my case I need pass the jwt token from the original request.

**Comment by nicolasduminil** [comment]
Is there any progress on this issue ? I'm experiencing the same with Quarkus 3.15.1.

**Comment by rupert-jung-mw** [comment]
Just a heads-up: The inheritance of `@Path` still does not work. I have to repeat the `@Path` annotation each time and can't just use the one of the inherited interface (generated by OpenAPI).
