### ISSUE TITLE
Build native : kafka + avro

### ISSUE THREAD

**Issue by MossabTN** [quarkusio/quarkus#5633]
Hi, i trying to use kafka with schema registry and i got this error on native build

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.apache.avro.Schema.addProp(java.lang.String, org.codehaus.jackson.JsonNode). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:165)
Call path from entry point to io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(boolean, String, Boolean, byte[], Schema): 
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:113)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:104)
        at io.confluent.kafka.serializers.KafkaAvroDeserializer.deserialize(KafkaAvroDeserializer.java:62)
        at com.oracle.svm.reflect.KafkaAvroDeserializer_deserialize_d8de9219340df9696ef590cef6fb021b0251c8dd_1627.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:163)
        at com.sun.proxy.$Proxy367.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:557)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getFieldNameByID(JNIReflectionDictionary.java:260)
        at com.oracle.svm.jni.functions.JNIFunctions.ToReflectedField(JNIFunctions.java:848)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ToReflectedField_80d8233579d5215df0227b770e5c01228a0de9b9(generated:0)
```
application.properties
```
#kafka
mp.messaging.outgoing.notification.connector=smallrye-kafka
mp.messaging.outgoing.notification.topic=notification
mp.messaging.outgoing.notification.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
mp.messaging.outgoing.notification.schema.registry.url=http://localhost:8081
mp.messaging.outgoing.notification.bootstrap.servers=http://localhost:9092

mp.messaging.incoming.input.connector=smallrye-kafka
mp.messaging.incoming.input.topic=notification
mp.messaging.incoming.input.value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
mp.messaging.incoming.input.schema.registry.url=http://localhost:8081
mp.messaging.incoming.input.bootstrap.servers=http://localhost:9092
```
pom.xml
```
<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.avro</groupId>
      <artifactId>avro</artifactId>
      <version>1.9.1</version>
    </dependency>
    <dependency>
      <groupId>io.confluent</groupId>
      <artifactId>kafka-avro-serializer</artifactId>
      <version>5.1.0</version>
    </dependency>
    <dependency>
      <groupId>org.codehaus.jackson</groupId>
      <artifactId>jackson-mapper-asl</artifactId>
      <version>1.9.13</version>
    </dependency>
```
please check this project example that contains the same problem: https://github.com/MossabTN/quarkus-kafka-avro

**Comment by leosilvadev** [comment]
Hi, what about this issue? I see it was closed but how should someone make that work? Or it just doesn't work yet?

**Comment by davevano** [comment]
Hi, This issue was closed because it's works until kafka-avro-serializer 5.3.1 and avro 1.9.1.
But with the latest version **kafka-avro-serializer 5.5.1 and avro 1.10.0.**.  I doesn't work.
I have tried to use quarkus-avro extension but it doesn't solve the problem..
Is it possible to reopen or update this issue?
Thanks.

**Comment by stewsters** [comment]
I too have this issue on the newest versions.

**Comment by cescoffier** [comment]
Reopening - it has never been completely fixed.

**Comment by leosilvadev** [comment]
Thanks @cescoffier !!!!
Which version should contain the fix?
Thank you again!

**Comment by cescoffier** [comment]
@leosilvadev Quarkus 1.10 should contain the fix. 

We can try to convince @gsmet to backport it in a future Quarkus 1.9.1 maybe.

**Comment by leosilvadev** [comment]
@cescoffier having it in 1.10 would be fine for me
Thanks a lot
