### ISSUE TITLE
Failed to read files that reference in application.properties after upgrade from 0.23.2  to 1.0.0.CR2

### ISSUE THREAD

**Issue by jdang67** [quarkusio/quarkus#5659]
**Describe the bug**

We are working on an application using quarkus 0.23.2 for months without any problem.
Today, we upgrade our app to 1.0.0.CR2 and it fails to load files that reference in application.properties 
```
kafka-streams.ssl.keystore.location=./keystore.jks
kafka-streams.ssl.truststore.location=./truststore.jks
```
**Expected behavior**

The application should work just like version 0.23.2.

**Actual behavior**

The application throw exception 
``` java
java.nio.file.NoSuchFileException: .\keystore.jks
```
**To Reproduce**
1. 

- add this key in application.properties kafka-streams.ssl.keystore.location=./keystore.jks
- add the keystore.jks in the same the same folder ( resources)

2.   Using version 0.23.2, the application works 
3.   Using version 1.0.0.CR2, the application  throw exception
``` java
java.nio.file.NoSuchFileException: .\keystore.jks
```

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
@gunnarmorling can you have a look?

I think it's a bit weird to pass a path like that but I don't know nothing about how Kafka Streams loads the resources.

**Comment by gunnarmorling** [comment]
Are you using a different Java version by any chance, too? I'd kinda suppose that those references are resolved by the JDKs SSL implementation.

**Comment by jdang67** [comment]
> Are you using a different Java version by any chance, too? I'd kinda suppose that those references are resolved by the JDKs SSL implementation.

No,  everything the same. Actually, switching from 0.23.2 to  0.24.0 already throw an exception.

**Comment by jaikiran** [comment]
Hello @jdang67, can you please paste the complete exception stacktrace that you see in `1.0.0.CR1` of Quarkus?

**Comment by jdang67** [comment]
> Hello @jdang67, can you please paste the complete exception stacktrace that you see in `1.0.0.CR2` of Quarkus?

07:15:01 ERROR [or.ap.ka.co.se.ss.SslFactory] (main) Modification time of key store could not be obtained: ./keystore.jks: java.nio.file.NoSuchFileException: .\keystore.jks
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.Files.getLastModifiedTime(Files.java:2266)
        at org.apache.kafka.common.security.ssl.SslFactory$SecurityStore.lastModifiedMs(SslFactory.java:363)
        at org.apache.kafka.common.security.ssl.SslFactory$SecurityStore.<init>(SslFactory.java:340)
        at org.apache.kafka.common.security.ssl.SslFactory.createKeystore(SslFactory.java:312)
        at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:132)
        at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:71)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:67)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:99)
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:361)
        at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:65)
        at org.apache.kafka.streams.processor.internals.DefaultKafkaClientSupplier.getAdminClient(DefaultKafkaClientSupplier.java:34)
        at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:713)
        at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:634)
        at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:544)
        at io.quarkus.kafka.streams.runtime.KafkaStreamsTopologyManager.onStart(KafkaStreamsTopologyManager.java:107)
        at io.quarkus.kafka.streams.runtime.KafkaStreamsTopologyManager_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(KafkaStreamsTopologyManager_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:51)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent29.deploy_0(LifecycleEventsBuildStep$startupEvent29.zig:77)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent29.deploy(LifecycleEventsBuildStep$startupEvent29.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:161)
        at io.quarkus.runtime.Application.start(Application.java:94)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:143)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:177)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:95)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)

**Comment by geoand** [comment]
I am going to close this as it is way out of date
