### ISSUE TITLE
MP Rest Client TCK test InvokeWithJsonPProviderTest failing

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#5715]
**Describe the bug**
After #5387, `InvokeWithJsonPProviderTest` and `InvokeWithJsonBProviderTest` have stopped passing.  The JSON-B test was trivially fixable by adding a config setup step (the config is read before Quarkus has a chance to establish it).  However the JSON-P test, even with a similar fix, fails with an unusual injection error:

```
Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.microprofile.rest.client.tck.interfaces.JsonPClient field org.eclipse.microprofile.rest.client.tck.InvokeWithJsonPProviderTest.cdiJsonPClient to com.sun.proxy.$Proxy59
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
    at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
    at java.lang.reflect.Field.set(Field.java:764)
    at io.quarkus.arc.impl.Reflections.writeField(Reflections.java:84)
```

This test has been disabled in #5387 until the problem can be found and fixed.

**Comment by mkouba** [comment]
I believe we can close this one. Feel free to reopen if neeeded.
