### ISSUE TITLE
Versions of transitive dependencies of extensions quarkus-resteasy and quarkus-jackson do not match

### ISSUE THREAD

**Issue by hartimcwildfly** [quarkusio/quarkus#5720]
The extensions io.quarkus:quarkus-resteasy and io.quarkus.quarkus-jackson
have the following transitive dependencies:

io.quarkus:quarkus-resteasy-jackson:jar:1.0.0.CR2
    +- org.jboss.resteasy:resteasy-jackson2-provider:jar:3.0.24.Final

io.quarkus:quarkus-resteasy:jar:1.0.0.CR2
    +- org.jboss.resteasy:resteasy-core:jar:4.4.1.Final

As a result of this. I get an exception when calling a rest endpoint:
`2019-11-23 21:41:04,728 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-worker-thread-0) HTTP Request to /abc/123/ failed, error id: b7f21f58-1eab-4b9f-b13d-e10d35bf9ee0-1: java.lang.NoClassDefFoundError: org/jboss/resteasy/util/FindAnnotation
	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.isWriteable(ResteasyJackson2Provider.java:61)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.resolveMessageBodyWriter(ResteasyProviderFactoryImpl.java:1309)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.getMessageBodyWriter(ResteasyProviderFactoryImpl.java:1280)
	at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$2(ServerResponseWriter.java:112)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:232)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:97)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:70)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:578)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:508)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:118)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:74)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.jboss.resteasy.util.FindAnnotation
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 23 more
`

When I override the version of org.jboss.resteasy:resteasy-jackson2-provider to 4.4.1.Final,
everything works as expected.

**Comment by hartimcwildfly** [comment]
My fault, I used a pom in which resteasy-jackson2-provider was already defined.
