### ISSUE TITLE
quarkus-oidc throws an OIDCException when a token does not contain the `role-claim-path``

### ISSUE THREAD

**Issue by looorent** [quarkusio/quarkus#5750]
**Describe the bug**
In `application.properties`, we specify a custom `role-claim-path`: `quarkus.oidc.roles.role-claim-path=resource_access/your-client-id/roles`. 

When testing a token using this path (but with the wrong role), everything works as expected.
When testing tokens that do not have this path, it throws an `OIDCException: No claim exists at the path resource_access/your-client-id/roles at the path segment your-client-id`.

By "testing", I mean calling a JAX-RS endpoint (with the appropriate bearer token) that requires a role contained in this claim path.

```
[io.quarkus.vertx.http.runtime.QuarkusErrorHandler] HTTP Request to /access-rights failed, error id: 38f42768-bd07-4e7e-bcde-3d4bd3dc8e2d-1: io.quarkus.oidc.OIDCException: No claim exists at the path resource_access/your-client-id/roles at the path segment /your-client-id
    at io.quarkus.oidc.runtime.OidcUtils.findClaimValue(OidcUtils.java:60)
    at io.quarkus.oidc.runtime.OidcUtils.findClaimValue(OidcUtils.java:66)
    at io.quarkus.oidc.runtime.OidcUtils.findClaimWithRoles(OidcUtils.java:44)
    at io.quarkus.oidc.runtime.OidcUtils.findRoles(OidcUtils.java:21)
    at io.quarkus.oidc.runtime.OidcIdentityProvider$1.handle(OidcIdentityProvider.java:73)
    at io.quarkus.oidc.runtime.OidcIdentityProvider$1.handle(OidcIdentityProvider.java:53)
    at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.lambda$decodeToken$3(OAuth2AuthProviderImpl.java:271)
    at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.authenticate(OAuth2AuthProviderImpl.java:238)
    at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.decodeToken(OAuth2AuthProviderImpl.java:269)
    at io.quarkus.oidc.runtime.OidcIdentityProvider.authenticate(OidcIdentityProvider.java:53)
    at io.quarkus.oidc.runtime.OidcIdentityProvider.authenticate(OidcIdentityProvider.java:23)
    at io.quarkus.oidc.runtime.OidcIdentityProvider_ClientProxy.authenticate(OidcIdentityProvider_ClientProxy.zig:349)
    at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl.handleProvider(QuarkusIdentityProviderManagerImpl.java:121)
    at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl.authenticate(QuarkusIdentityProviderManagerImpl.java:89)
    at io.quarkus.security.runtime.IdentityProviderManagerCreator_ProducerMethod_ipm_91f102be1b2a781216db8a81e6ab4b9b1a84f03c_ClientProxy.authenticate(IdentityProviderManagerCreator_ProducerMethod_ipm_91f102be1b2a781216db8a81e6ab4b9b1a84f03c_ClientProxy.zig:105)
    at io.quarkus.oidc.runtime.AbstractOidcAuthenticationMechanism.authenticate(AbstractOidcAuthenticationMechanism.java:27)
    at io.quarkus.oidc.runtime.BearerAuthenticationMechanism.authenticate(BearerAuthenticationMechanism.java:26)
    at io.quarkus.oidc.runtime.BearerAuthenticationMechanism_ClientProxy.authenticate(BearerAuthenticationMechanism_ClientProxy.zig:201)
    at io.quarkus.vertx.http.runtime.security.HttpAuthenticator.attemptAuthentication(HttpAuthenticator.java:66)
    at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.attemptAuthentication(HttpAuthenticator_ClientProxy.zig:150)
    at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1.handle(HttpSecurityRecorder.java:35)
    at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1.handle(HttpSecurityRecorder.java:24)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
    at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:75)
    at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:64)
    at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
    at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
    at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:830)
```

**Expected behavior**
The endpoint should:
* return a 403
* and/or give the possibility to a `@Provider` (`ExceptionMapper`) to catch and handle this exception.

**Configuration**
```properties
quarkus.oidc.roles.role-claim-path=resource_access/your-client-id/roles
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`
 - Output of `java -version`: `OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)`
 - Quarkus version or git rev: `1.0.0.Final`

**Comment by sberyozkin** [comment]
I agree about 403 in this case.
