### ISSUE TITLE
AWS Lambda handler unable to use JPA repository

### ISSUE THREAD

**Issue by otcyury** [quarkusio/quarkus#5811]
Hi, does Quarkus support JPA in its AWS Lambda handler class / method? I am getting below exception using CrudRepository.

I use repository inside of Lambda handler method and I guess, at this stage, the framework is not ready to go through the request. I followed the pattern of using repository inside Rest controller, where it worked without additional measures.

ERROR [io.qu.am.la.ru.AmazonLambdaRecorder]] (Lambda Thread) Failed to run lambda: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.arc$delegate(RequestScopedEntityManagerHolder_ClientProxy.zig:83)
at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.getOrCreateEntityManager(RequestScopedEntityManagerHolder_ClientProxy.zig:191)
at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:78)
at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.find(TransactionScopedEntityManager.java:142)
at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.find(ForwardingEntityManager.java:42)
at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.findById(JpaOperations.java:196)
at com.antwerkz.quarkus.lambda.BlueskyComplianceRepositoryImpl.findById(BlueskyComplianceRepositoryImpl.zig:246)
at com.antwerkz.quarkus.lambda.BlueskyComplianceRepositoryImpl.findById(BlueskyComplianceRepositoryImpl.zig:182)
at com.antwerkz.quarkus.lambda.BlueskyComplianceRepositoryImpl_ClientProxy.findById(BlueskyComplianceRepositoryImpl_ClientProxy.zig:374)
at com.antwerkz.quarkus.lambda.HelloGreeter.greet(HelloGreeter.java:24)
at com.antwerkz.quarkus.lambda.HelloGreeter_ClientProxy.greet(HelloGreeter_ClientProxy.zig:195)
at com.antwerkz.quarkus.lambda.HelloLambda.handleRequest(HelloLambda.java:15)
at com.antwerkz.quarkus.lambda.HelloLambda.handleRequest(HelloLambda.java:9)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$2.run(AmazonLambdaRecorder.java:96)
at java.lang.Thread.run(Thread.java:748)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

**Comment by famartinrh** [comment]
I had a similar error playing with panache too. @otcyury try put `@Transactional` in your class, it should fix it. However I'm not sure if that's a good solution or a workaround for a bug, @Sanne may be able to clarify that.

**Comment by Sanne** [comment]
Right, adding `@Transactional` explicitly is a reasonable solution.

For Panache usage in a webcontext the decision was to automatically assume a transactional context, should an ORM operation be triggered withing an http request.

One could argue that we should be consistent and do the same with an AWS lambda, but to be honest I don't know enough about these and I'm not sure if it's _definitely_ a good idea.

TBH it's also a bit questionable in the web scope, as having an error might be a good reminder to developers that it's better to be explicit about the transaction scope, but the team fealt that usability and speed of prototyping was more important.

I think this is for @patriot1burke to decide what is the most reasonable approach in the scope of amazon lambdas; likely need some help and feedback from you all, and @evanchooly and @FroMage too.

**Comment by FroMage** [comment]
> For Panache usage in a webcontext the decision was to automatically assume a transactional context, should an ORM operation be triggered withing an http request (and no explicit transaction defined).

I don't recall any such discussion, and I'm pretty sure we do not automatically add transactions when Panache is used. I'm sure it's exactly the same constraints/requirements than plain Hibernate ORM.

AFAIR, we allow transaction-less reads, and then ORM has throwing methods in its `EntityManager` facade that check for any modification-API and throws if there's no transaction.

Note that this error seems to be about a lack of request scope, not the lack of a transaction. I don't know why adding `@Transactional` gives you a request scope that would fix this. I thought it would give you a transaction scope, which is different.

**Comment by patriot1burke** [comment]
I don't like the idea of lambdas getting things the user might not want.

**Comment by Sanne** [comment]
Such as? Could you elaborate a bit?

**Comment by otcyury** [comment]
Adding `@Transactional` worked for me.

I think, in Spring JPA use of Repository implicitly opens up read only transaction not requiring use of `@Transactional,` unless one needs to persist data.

Thanks

**Comment by devendra-kumar1** [comment]
@otcyury : Where you kept @Transactional annoation. on entity class or on interface where you extended CrudRepository.
I am facing exactly same issue while extending org.springframework.data.jpa.repository.JpaRepository

**Comment by devendra-kumar1** [comment]
@otcyury It worked for me after putting @ Transactional annotation on LambdaHandler
