### ISSUE TITLE
ENV Variables doesn't work anymore with Quarkus 1.0.1.Final

### ISSUE THREAD

**Issue by paolodedo** [quarkusio/quarkus#5939]
As of https://github.com/quarkusio/quarkus/issues/3516,

this bug has come back to annoy at **Quarkus version 1.0.1.Final**.

Here's my application.properties:
`quarkus.http.port=${SERVER_PORT:8080}`

Here is the log at startup:

    11:10:17,372 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: 
    java.lang.NumberFormatException: For input string: "${SERVER_PORT:8080}"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:638)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at io.smallrye.config.Converters.lambda$static$60db1e39$1(Converters.java:83)
	at io.smallrye.config.Converters$BuiltInConverter.convert(Converters.java:477)
	at io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:198)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:99)
	at io.quarkus.runtime.configuration.ConfigUtils.getValue(ConfigUtils.java:71)
	at io.quarkus.deployment.configuration.IntConfigType.acceptConfigurationValueIntoGroup(IntConfigType.java:60)
	at io.quarkus.deployment.configuration.GroupConfigType.acceptConfigurationValueIntoLeaf(GroupConfigType.java:238)
	at io.quarkus.deployment.configuration.IntConfigType.acceptConfigurationValue(IntConfigType.java:42)
	at io.quarkus.deployment.configuration.ConfigDefinition.loadConfiguration(ConfigDefinition.java:497)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:229)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:144)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:88)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:111)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:177)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:95)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)

**Comment by gsmet** [comment]
I has never been gone :). It should be fixed for the upcoming 1.1.0 as stated in the issue. Could you try current master and report back?

Thanks!

**Comment by paolodedo** [comment]
Ok thank you very much!

**Comment by gsmet** [comment]
A CR is planned on next Monday. And the Final on December 16th.

But please, test master to be sure the issue is resolved!

**Comment by paolodedo** [comment]
How can I? 

I mean running a clean install on master fails... how to import this version to my project

**Comment by gsmet** [comment]
It shouldn't. What's the issue you have?

**Comment by gsmet** [comment]
In any case, you can just do `mvn clean install -DskipTests -DskipITs`. After that, the idea is to import the quarkus-bom in version 999-SNAPSHOT. You might have to change your pom a bit to point to quarkus-bom instead of the universe one.

**Comment by paolodedo** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) on project quarkus-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
