### ISSUE TITLE
Flyway is not executed before Hiberrnate inside a docker container

### ISSUE THREAD

**Issue by uaihebert** [quarkusio/quarkus#5942]
**Describe the bug**
hello, I noticed a strange behavior with Flyway.

when I run the project inside a docker container sometimes Flyway is not invoked.

What I do is:
1) set Flyway to run on every start-up
2) use hibernate to validate the schema

basically, these are my configs:
```
%test.quarkus.datasource.url=jdbc:h2:mem:testDB
%test.quarkus.datasource.driver=org.h2.Driver
%test.quarkus.datasource.username=username-default
%test.quarkus.datasource.password=
```

for hibernate:
`quarkus.hibernate-orm.database.generation=validate`
At the logs I have this output:

2019-12-03 17:41:47,332 INFO  [io.qua.fly.FlywayProcessor] (build-11) Adding application migrations in path '/Users/hebertcoelhodeoliveira/dev/workspace/small-issues/target/classes/db/migration' using protocol 'file'
And an exception flys from hibernate:
`
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [a]
`
Flyway was able to find the path for it but, for some reason, did not execute the migration and create the table.

To simulate the problem there is this project:
https://github.com/uaihebert/quarkus-small-issues

The problem does not happen all the time, but I had some deploys failing because of it. 

If it fails, update the ExampleResourceTest class and run again until it happens. After I ran 3 times the exception appeared.

Any idea of what could it be?

The full stack is:
```
[INFO] Running org.acme.ExampleResourceTest
2019-12-03 17:28:27,648 INFO  [io.qua.fly.FlywayProcessor] (build-7) Adding application migrations in path '/deployments/target/classes/db/migration' using protocol 'file'
javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
    at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:113)
    at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:67)
    at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:54)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
    at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:109)
    at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:57)
    at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:82)
    at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits25.deploy_0(HibernateOrmProcessor$startPersistenceUnits25.zig:70)
    at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits25.deploy(HibernateOrmProcessor$startPersistenceUnits25.zig:36)
    at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:134)
    at io.quarkus.runtime.Application.start(Application.java:94)
    at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:143)
    at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:248)
    at io.quarkus.test.junit.QuarkusTestExtension.createTestInstance(QuarkusTestExtension.java:393)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:285)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:275)
    at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:77)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:258)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:252)
    at java.base/java.util.Optional.orElseGet(Optional.java:369)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:251)
    at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:29)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:106)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:105)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:69)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:107)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
    at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
    at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
    at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
    at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
    at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
    at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
    at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [a]
    at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:121)
    at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:42)
    at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:89)
    at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:68)
    at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:192)
    at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
    at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:320)
    at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
    at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:65)
    ... 63 more
```

**Expected behavior**
Flyway executes before hibernate and validation passes.

**Actual behavior**
For some reason, Flyway migration is not being executed.

**To Reproduce**
1. `docker build -f Dockerfile -t small_issues .` sometimes you need to run more than 2 or 3 times to see it

**Comment by jaikiran** [comment]
Hello @uaihebert, can you please enabled `DEBUG` log for `io.quarkus.flyway` package and get us the logs? Details and examples on how to enable logging is explained here https://quarkus.io/guides/logging#examples

**Comment by gsmet** [comment]
We had a few issues similar to this on CI.

I wouldn't be surprised if we have some sort of timing issues and that we would need a build item to mark the datasources as migrated and inject it in all the steps manipulating the datasources (in ORM and the Quartz scheduler typically).

**Comment by uaihebert** [comment]
hello, @jaikiran that is the frustrating part. I tried with log in debug, the only difference is that it adds one line:
```
[INFO] Running org.acme.ExampleResourceTest
2019-12-04 15:57:25,346 INFO  [io.qua.fly.FlywayProcessor] (build-41) Adding application migrations in path '/deployments/target/classes/db/migration' using protocol 'file'
2019-12-04 15:57:25,411 DEBUG [io.qua.fly.FlywayProcessor] (build-41) Discovered: db/migration/V0001__create_cookies_table.sql
javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
```
it points out that it found the migration file. 

let me know if there is anything else that I can provide.

**Comment by jaikiran** [comment]
This does indeed look like an issue. I will see if I can reproduce this and see what's causing this, sometime over the weekend.

**Comment by uaihebert** [comment]
hello @jaikiran thank you for the help

If you need any other input just let me know. I do not have yet this deep knowledge in the framework to find this problem.

this is a big pain for us now because if we have a new migration I need to run locally pointing to staging or production because the deploy fails when the project runs inside a docker container.

**Comment by jaikiran** [comment]
Hello @uaihebert, I was able to reproduce this (even without docker) and I've opened https://github.com/quarkusio/quarkus/pull/6003 with a potential fix.

**Comment by uaihebert** [comment]
@jaikiran thank you very much! that is good news!

**Comment by jaikiran** [comment]
A new PR containing a fix has been opened https://github.com/quarkusio/quarkus/pull/6301. This PR follows the suggestions made in the previous PR as well as a the discussion on the mailing list.
