### ISSUE TITLE
NPE if security-properties is enabled and a user has no roles prop

### ISSUE THREAD

**Issue by Teg79** [quarkusio/quarkus#5951]
**Describe the bug**
Activating the module elytron-security-properties-file and configuring it in embedded mode, if a user has not the roles property, Quarkus fails to boot

**Expected behavior**
Run Quarkus with base security from file and a user without roles

**Actual behavior**
```./mvnw compile quarkus:dev
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ code-with-quarkus ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/Teg79/Downloads/code-with-quarkus/target/classes
[INFO] 
[INFO] --- quarkus-maven-plugin:1.0.1.Final:dev (default-cli) @ code-with-quarkus ---
Listening for transport dt_socket at address: 5005
2019-12-04 20:16:43,647 INFO  [io.qua.ely.sec.pro.dep.ElytronPropertiesProcessor] (build-13) Configuring from MPRealmConfig
java.lang.NullPointerException
	at io.quarkus.elytron.security.runtime.ElytronPropertiesFileRecorder$2.run(ElytronPropertiesFileRecorder.java:142)
	at io.quarkus.elytron.security.runtime.ElytronRecorder.runLoadTask(ElytronRecorder.java:31)
	at io.quarkus.deployment.steps.ElytronDeploymentProcessor$loadRealm16.deploy_0(ElytronDeploymentProcessor$loadRealm16.zig:70)
	at io.quarkus.deployment.steps.ElytronDeploymentProcessor$loadRealm16.deploy(ElytronDeploymentProcessor$loadRealm16.zig:36)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:105)
	at io.quarkus.runtime.Application.start(Application.java:94)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:143)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:177)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:95)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
2019-12-04 20:16:44,765 ERROR [io.qua.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:185)
	at io.quarkus.runtime.Application.start(Application.java:94)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:143)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:177)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:95)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: java.lang.NullPointerException
	at io.quarkus.elytron.security.runtime.ElytronPropertiesFileRecorder$2.run(ElytronPropertiesFileRecorder.java:142)
	at io.quarkus.elytron.security.runtime.ElytronRecorder.runLoadTask(ElytronRecorder.java:31)
	at io.quarkus.deployment.steps.ElytronDeploymentProcessor$loadRealm16.deploy_0(ElytronDeploymentProcessor$loadRealm16.zig:70)
	at io.quarkus.deployment.steps.ElytronDeploymentProcessor$loadRealm16.deploy(ElytronDeploymentProcessor$loadRealm16.zig:36)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:105)
	... 5 more

2019-12-04 20:16:44,766 INFO  [io.qua.dev.DevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
```

**To Reproduce**
1. Create a Quarkus Application from the Star Coding site
2. Add the extension elytron-security-properties-file
3. Unpack the Application
4. Edit the application.properties and add these rows:
```
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.admin=admin
quarkus.security.users.embedded.users.user=user1
quarkus.security.users.embedded.roles.admin=admin_role
```
5. Start Quarkus `./mvnw compile quarkus:dev`

**Configuration**
```properties
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.admin=admin
quarkus.security.users.embedded.users.user=user1
quarkus.security.users.embedded.roles.admin=admin_role
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```Darwin PC153-2 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64```
 - Output of `java -version`: 
```
openjdk version "11.0.5" 2019-10-15 LTS
OpenJDK Runtime Environment Corretto-11.0.5.10.1 (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.5.10.1 (build 11.0.5+10-LTS, mixed mode)
```
 - GraalVM version (if different from Java): NA
 - Quarkus version or git rev: 1.0.1.Final

**Comment by gaetancollaud** [comment]
I had the same issue because I didn't specify any roles for my user. This is strange because in your example you specify a role...

Example **not working**:
```
  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        users:
          ttn: ttn
```

Example that works:
```
  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        users:
          ttn: ttn
        roles:
          ttn: READER
```

**Comment by sberyozkin** [comment]
I'm nearly 100% sure this one was fixed, I recall having to deal with this NPE
