### ISSUE TITLE
Use java.util.Locale in Quarkus (i18n)

### ISSUE THREAD

**Issue by JuMp3** [quarkusio/quarkus#5976]
Is it possible to use the Locale (java.util.Locale) object in a controller with Quarkus, for the management of the i18n? If yes, how?

I'm having the following error, if I use the local object as a parameter of the method:

`public ResponseEntity<Prefixes> prefixes(Locale locale) {`

```
ERROR [org.jbo.res.res.i18n] (vert.x-worker-thread-1) RESTEASY002010: Failed to execute: javax.ws.rs.NotSupportedException: RESTEASY003200: Could not find message body reader for type: class java.util.Locale of content type: */*
        at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.throwReaderNotFound(ServerReaderInterceptorContext.java:56)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.getReader(AbstractReaderInterceptorContext.java:134)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:76)
        at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:212)
        at org.jboss.resteasy.core.MethodInjectorImpl.lambda$injectArguments$1(MethodInjectorImpl.java:96)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
        at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:96)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:121)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:594)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:468)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:421)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:423)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:365)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:118)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:74)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by gsmet** [comment]
So basically you would want to inject the Locale as resolved per the `Accept-Language` header in a JAX-RS method?

I don't know if it's supported. If it were, you would have to add a `@Context Locale locale` but can't say if it will work.

@asoldano any idea?

**Comment by JuMp3** [comment]
> 
> 
> So basically you would want to inject the Locale as resolved per the `Accept-Language` header in a JAX-RS method?
> 
> I don't know if it's supported. If it were, you would have to add a `@Context Locale locale` but can't say if it will work.
> 
> @asoldano any idea?

Thanks guy; I tried and if set Content-Type in header as json i've not runtime error, but the locale is null :D so I think there will be some other way to do it.
Thanks a lot anyway for the timely reply ;)

**Comment by mdemerat** [comment]
I'm using this: 

```
	@Context
	HttpServerRequest request;


       String lang = request.getHeader("Accept-language")
```

**Comment by JuMp3** [comment]
> 
> 
> I'm using this:
> 
> ```
> 	@Context
> 	HttpServerRequest request;
> 
> 
>        String lang = request.getHeader("Accept-language")
> ```

ok, but if you don't set that header ("Accept-language"), you have not the Locale; I would like to find a solution equivalent to the Spring Boot Locale that automatically inject it in the controller

**Comment by geoand** [comment]
> I would like to find a solution equivalent to the Spring Boot Locale that automatically inject it in the controller

Which exact feature are you referring to?

**Comment by Eng-Fouad** [comment]
> > I'm using this:
> > ```
> > 	@Context
> > 	HttpServerRequest request;
> > 
> > 
> >        String lang = request.getHeader("Accept-language")
> > ```
> 
> ok, but if you don't set that header ("Accept-language"), you have not the Locale; I would like to find a solution equivalent to the Spring Boot Locale that automatically inject it in the controller

```
@Context
ContainerRequestContext requestContext;

List<Locale> acceptableLocales = requestContext.getAcceptableLanguages();
```

**Comment by geoand** [comment]
Closing for lack of feedback
