### ISSUE TITLE
Support Loggers looked up from methods

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#601]
This simple change in Hibernate ORM broke the Logger/Protean integration: https://github.com/hibernate/hibernate-orm/commit/15ea965d202c23e1ad8477668f32518c1d2371f0 

My guess is that only Loggers initialized into a static field are initialized today?

This is the exact error:

```
Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.hibernate.internal.CoreMessageLogger (implementation not found in java.lang.ClassLoader@3b20208)
	at org.jboss.logging.Logger$1.run(Logger.java:2681)
	at java.security.AccessController.doPrivileged(AccessController.java:62)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2654)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2641)
	at org.hibernate.internal.CoreLogging.messageLogger(CoreLogging.java:28)
	at org.hibernate.internal.CoreLogging.messageLogger(CoreLogging.java:24)
	at org.hibernate.hql.internal.QueryTranslatorFactoryInitiator.initiateService(QueryTranslatorFactoryInitiator.java:43)
```

**Comment by dmlloyd** [comment]
Is this still a problem?  If so, we may need to auto-register log message class constructors for reflection.

**Comment by Sanne** [comment]
Yes it's still a problem;
this is what I had done to move on:
https://github.com/quarkusio/quarkus/blob/8fd4337ee1160ace2aec3c1f4f61377a3db96213/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmReflections.java#L111-L114

**Comment by dmlloyd** [comment]
I would advise that all loggers should be static, in any case.

**Comment by Sanne** [comment]
Sure I agree as a "general recommendation", but we should allow for exceptional different usage?

Or do you think we should always expect people to register those for reflection explicitly?

If that's the case I guess we can close this; I did assume thought that we wanted to be able to claim that any usage of JBoss Logger would work fine in native mode.

**Comment by dmlloyd** [comment]
I don't like making people explicitly register for reflection, but I don't see any good alternative.  I think it's the only practical solution.

**Comment by Sanne** [comment]
Ok, agreed. Closing then!
