### ISSUE TITLE
mvn quarkus:dev freezes in a project with bidirectional JPA relationships

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#6091]
**Describe the bug**
Having the following entities in a Quarkus app makes `mvn compile quarkus:dev` freeze: 

```java
@Entity
@Table(name = "owners")
public class Owner {

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "owner")
    private Set<Pet> pets;

    public Set<Pet> getPets() {
        return pets;
    }

    public void setPets(Set<Pet> pets) {
        this.pets = pets;
    }
}
```

And 
```java
@Entity
@Table(name = "pets")
public class Pet {

    @ManyToOne
    @JoinColumn(name = "owner_id")
    private Owner owner;

    public Owner getOwner() {
        return owner;
    }

    public void setOwner(Owner owner) {
        this.owner = owner;
    }
}

```

**Expected behavior**
Application should run 

**Actual behavior**
Application is frozen. This is the output of jstack: 
```java
"main" #1 prio=5 os_prio=0 tid=0x00007f65d400d800 nid=0x24228 waiting on condition [0x00007f65db60a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000726b33bc0> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at io.quarkus.runner.RuntimeClassLoader.findClass(RuntimeClassLoader.java:214)
	at io.quarkus.runner.RuntimeClassLoader.loadClass(RuntimeClassLoader.java:179)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:935)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1200)
	at org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm.Frame.merge(Frame.java:1197)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1607)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1543)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2431)
	at org.objectweb.asm.ClassReader.readThis is causeMethod(ClassReader.java:1283)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at io.quarkus.hibernate.orm.deployment.HibernateEntityEnhancer$HibernateEnhancingClassVisitor.visitEnd(HibernateEntityEnhancer.java:67)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:692)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at io.quarkus.runner.RuntimeClassLoader.handleTransform(RuntimeClassLoader.java:430)
	at io.quarkus.runner.RuntimeClassLoader.findClass(RuntimeClassLoader.java:225)
	at io.quarkus.runner.RuntimeClassLoader.loadClass(RuntimeClassLoader.java:179)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.quarkus.hibernate.orm.runtime.service.FlatClassLoaderService.classForName(FlatClassLoaderService.java:36)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.<init>(AnnotationMetadataSourceProcessorImpl.java:109)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.<init>(MetadataBuildingProcess.java:155)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:149)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:342)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:111)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:84)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:47)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$4.created(HibernateOrmRecorder.java:75)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:101)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources25.deploy_0(ArcProcessor$generateResources25.zig:406)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources25.deploy(ArcProcessor$generateResources25.zig:36)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:378)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:152)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
	- locked <0x00000005d3e2ea78> (a io.quarkus.dev.DevModeMain)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
```

**To Reproduce**
1. Unzip the project in [jpa-example.zip](https://github.com/quarkusio/quarkus/files/3948053/jpa-example.zip)
2. run `mvn compile quarkus:dev`
3. Output should freeze after the following output is displayed: 
```
[INFO] Launching JVM with command line: /home/ggastald/.sdkman/candidates/java/8.0.232-open/jre/bin/java -XX:TieredStopAtLevel=1 -Xverify:none -Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /tmp/jpa-example/target/jpa-example-dev.jar
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux ggastald-laptop 5.3.14-300.fc31.x86_64 #1 SMP Mon Dec 2 15:41:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

```
 - GraalVM version (if different from Java):  Not used
 - Quarkus version or git rev: 1.1.0.CR1

**Additional context**
Look at the jstack output to find where the problem is. HINT: recursion in RuntimeClassloader

**Comment by gastaldi** [comment]
The application works if run with `java -jar`

**Comment by murphye** [comment]
For what it's worth: This is a blocker for me on a blog post that I am writing. Thanks.

**Comment by murphye** [comment]
I downgraded to 1.0.1.Final and the reproducer started up.

This appears to be a regression, maybe due to a change in Hibernate version?:
5.4.8 (1.0.1.Final)
5.4.10 (1.1.0.CR1)

**Comment by geoand** [comment]
cc @stuartwdouglas @Sanne

**Comment by murphye** [comment]
I just now tried the jpa-example.zip with 999-SNAPSHOT and it's still hanging. I also see the same behavior in my PetClinic application (where the code originated).

@gsmet Can you check again if it works?

**Comment by gsmet** [comment]
@murphye have you tried with a locally compiled master? Because it looks like our snapshots are not pushed anymore for whatever reason. The last snapshot published is from Dec 6th.

With the original project and with latest master, I get an error when I launch `quarkus:dev`:
```
21:56:05,762 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:152)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:497)
	... 6 more
Caused by: org.hibernate.AnnotationException: No identifier specified for entity: org.acme.quickstart.Owner
	at org.hibernate.cfg.InheritanceState.determineDefaultAccessType(InheritanceState.java:266)
	at org.hibernate.cfg.InheritanceState.getElementsToProcess(InheritanceState.java:211)
	at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:781)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:254)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:230)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:273)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:342)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:111)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:84)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:47)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$4.created(HibernateOrmRecorder.java:75)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:101)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources25.deploy_0(ArcProcessor$generateResources25.zig:436)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources25.deploy(ArcProcessor$generateResources25.zig:36)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:459)
	... 6 more
```
which looks like a valid one to me.

**Comment by murphye** [comment]
I believe this was the problem... not having latest snapshot. I will report back if the next release has the issue. Thanks.
