### ISSUE TITLE
Neo4j doesn't work in native mode anymore

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#6115]
Apparently, CI didn't run the Neo4j tests and we missed that the Neo4j extension doesn't work in native mode anymore:

```
2019-12-10T17:22:12.8145240Z 2019-12-10 17:22:12,810 INFO  [io.quarkus] (main) Installed features: [cdi, neo4j, resteasy, resteasy-jsonb, smallrye-health]
2019-12-10T17:22:13.9081262Z 2019-12-10 17:22:13,905 WARN  [ChannelErrorHandler] (Neo4jDriverIO-3-2) [0xf593c5b0][localhost:60513][] Fatal error occurred in the pipeline: org.neo4j.driver.internal.shaded.io.netty.handler.codec.DecoderException: Failed to read inbound message:
2019-12-10T17:22:13.9088669Z 70a2867365727665728b4e656f346a2f332e352e368d636f6e6e656374696f6e5f696486626f6c742d31
2019-12-10T17:22:13.9089433Z 
2019-12-10T17:22:13.9103746Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:87)
2019-12-10T17:22:13.9104472Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
2019-12-10T17:22:13.9111392Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
2019-12-10T17:22:13.9111960Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:13.9119813Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:13.9120438Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:13.9128790Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
2019-12-10T17:22:13.9129424Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
2019-12-10T17:22:13.9140355Z 	at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47)
2019-12-10T17:22:13.9140947Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:13.9157190Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:13.9157750Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:13.9158378Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
2019-12-10T17:22:13.9173772Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
2019-12-10T17:22:13.9186792Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:13.9187349Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:13.9204041Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:13.9208743Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
2019-12-10T17:22:13.9218554Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:13.9233431Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:13.9234237Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
2019-12-10T17:22:13.9234799Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
2019-12-10T17:22:13.9269801Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
2019-12-10T17:22:13.9270658Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
2019-12-10T17:22:13.9279508Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
2019-12-10T17:22:13.9280089Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
2019-12-10T17:22:13.9280494Z 	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
2019-12-10T17:22:13.9293756Z 	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2019-12-10T17:22:13.9298865Z 	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2019-12-10T17:22:13.9323346Z 	at java.lang.Thread.run(Thread.java:748)
2019-12-10T17:22:13.9324027Z 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
2019-12-10T17:22:13.9324520Z 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
2019-12-10T17:22:13.9341405Z Caused by: org.neo4j.driver.internal.packstream.PackStream$Unexpected: Expected a struct, but got: ffffffb1
2019-12-10T17:22:13.9342101Z 	at org.neo4j.driver.internal.packstream.PackStream$Unpacker.unpackStructHeader(PackStream.java:421)
2019-12-10T17:22:13.9343188Z 	at org.neo4j.driver.internal.messaging.v1.ValueUnpackerV1.unpackStructHeader(ValueUnpackerV1.java:62)
2019-12-10T17:22:13.9355222Z 	at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.read(MessageReaderV1.java:51)
2019-12-10T17:22:13.9361078Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
2019-12-10T17:22:13.9361607Z 	... 31 more
2019-12-10T17:22:13.9362006Z 
2019-12-10T17:22:14.1436845Z 2019-12-10 17:22:14,141 WARN  [ChannelErrorHandler] (Neo4jDriverIO-3-1) [0x212a77c8][localhost:60513][] Fatal error occurred in the pipeline: org.neo4j.driver.internal.shaded.io.netty.handler.codec.DecoderException: Failed to read inbound message:
2019-12-10T17:22:14.1444730Z 70a2867365727665728b4e656f346a2f332e352e368d636f6e6e656374696f6e5f696486626f6c742d32
2019-12-10T17:22:14.1445390Z 
2019-12-10T17:22:14.1445910Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:87)
2019-12-10T17:22:14.1446538Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
2019-12-10T17:22:14.1447087Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
2019-12-10T17:22:14.1449022Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:14.1449524Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:14.1455020Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:14.1455692Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
2019-12-10T17:22:14.1470379Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
2019-12-10T17:22:14.1477951Z 	at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47)
2019-12-10T17:22:14.1481279Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:14.1485567Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:14.1486256Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:14.1488240Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
2019-12-10T17:22:14.1489965Z 	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
2019-12-10T17:22:14.1504501Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:14.1513378Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:14.1515236Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
2019-12-10T17:22:14.1517998Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
2019-12-10T17:22:14.1520715Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
2019-12-10T17:22:14.1529101Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
2019-12-10T17:22:14.1532042Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
2019-12-10T17:22:14.1533846Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
2019-12-10T17:22:14.1572936Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
2019-12-10T17:22:14.1573654Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
2019-12-10T17:22:14.1574185Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
2019-12-10T17:22:14.1574888Z 	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
2019-12-10T17:22:14.1575450Z 	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
2019-12-10T17:22:14.1576085Z 	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2019-12-10T17:22:14.1583176Z 	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2019-12-10T17:22:14.1583874Z 	at java.lang.Thread.run(Thread.java:748)
2019-12-10T17:22:14.1584352Z 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
2019-12-10T17:22:14.1620425Z 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
2019-12-10T17:22:14.1621016Z Caused by: org.neo4j.driver.internal.packstream.PackStream$Unexpected: Expected a struct, but got: ffffffb1
2019-12-10T17:22:14.1631143Z 	at org.neo4j.driver.internal.packstream.PackStream$Unpacker.unpackStructHeader(PackStream.java:421)
2019-12-10T17:22:14.1660811Z 	at org.neo4j.driver.internal.messaging.v1.ValueUnpackerV1.unpackStructHeader(ValueUnpackerV1.java:62)
2019-12-10T17:22:14.1661615Z 	at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.read(MessageReaderV1.java:51)
2019-12-10T17:22:14.1662851Z 	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
2019-12-10T17:22:14.1667963Z 	... 31 more
```

**Comment by gsmet** [comment]
Superseded by https://github.com/quarkusio/quarkus/pull/6117 .

**Comment by michael-simons** [comment]
I'm investigating as well. 
So far:
* Pre 1.0.0 with our 4.0.0-alpha is fine
* Pre 1.0.0 with our 4.0.0-beta03 without any additional things in Quarkus is fine
* 1.0.1 works fine with 4.0.0-beta03 and 4.0.0 final (with some changes to the test)

After that, things get's messy somewhere.

**Comment by michael-simons** [comment]
Update: it seems not to be SSL related, but there’s somewhere a class either from us or the shaded netty that gets initialized at buildtime and causes our message handlers to mess up. Cc @zhenlineo

**Comment by michael-simons** [comment]
Here's a plain reproducer. It's not Quarkus related, but GraalVM:

https://github.com/michael-simons/neo4j-java-driver-native-example

Something changed between 19.2 and 19.3.

Maybe @shelajev can ask if someone from the Graal team might have a look here.

**Comment by michael-simons** [comment]
Well it turns out that I cannot even compile anything natively anymore with GraalVM 19.3 on macOS 10.15 (I think that is this https://github.com/oracle/graal/issues/1920)

```
Running command: cc -v -o /Users/msimons/Projects/misc/driver-native/target/org.neo4j.examples.drivernative.drivernativeapplication -Wl,-no_compact_unwind -Wl,-exported_symbols_list -Wl,/var/folders/kc/xrh6jvq57nn8xnj36nzk4klc0000gn/T/SVM-4445666172385118323/exported_symbols.list -Wl,-x -arch x86_64 -L/var/folders/kc/xrh6jvq57nn8xnj36nzk4klc0000gn/T/SVM-4445666172385118323 -L/Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib -L/Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 /var/folders/kc/xrh6jvq57nn8xnj36nzk4klc0000gn/T/SVM-4445666172385118323/org.neo4j.examples.drivernative.drivernativeapplication.o /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/libnet.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/libjava.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/libzip.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/libnio.a -lm -lpthread -Wl,-framework,CoreFoundation -lpthread -ldl -lz

Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -arch x86_64 -macosx_version_min 10.15.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -o /Users/msimons/Projects/misc/driver-native/target/org.neo4j.examples.drivernative.drivernativeapplication -L/var/folders/kc/xrh6jvq57nn8xnj36nzk4klc0000gn/T/SVM-4445666172385118323 -L/Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib -L/Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 -no_compact_unwind -exported_symbols_list /var/folders/kc/xrh6jvq57nn8xnj36nzk4klc0000gn/T/SVM-4445666172385118323/exported_symbols.list -x /var/folders/kc/xrh6jvq57nn8xnj36nzk4klc0000gn/T/SVM-4445666172385118323/org.neo4j.examples.drivernative.drivernativeapplication.o /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/libnet.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/libjava.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/libzip.a /Library/Java/JavaVirtualMachines/graalvm-ce-java8-19.3.0/Contents/Home/jre/lib/libnio.a -lm -lpthread -framework CoreFoundation -lpthread -ldl -lz -L/usr/local/lib -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_Java_sun_misc_Unsafe_staticFieldBase", referenced from:
      ___svm_cglobaldata_base in org.neo4j.examples.drivernative.drivernativeapplication.o
  "_Java_sun_misc_Unsafe_staticFieldOffset", referenced from:
      ___svm_cglobaldata_base in org.neo4j.examples.drivernative.drivernativeapplication.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:382)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:652)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

**Comment by michael-simons** [comment]
This is an issue on Graals optimizer. I'm gonna create an issue over there.

**Comment by gsmet** [comment]
Please ask for it to be backported to 19.3.1.

Could you post the issue here when you have created it?

Thanks!

**Comment by michael-simons** [comment]
Done. Let's see if it a) was the right place to file the issue and b) someone looks at it.
