### ISSUE TITLE
Mongo  panache dont read database name in application.properties when profil is used

### ISSUE THREAD

**Issue by zakhdar** [quarkusio/quarkus#6166]
**Describe the bug**

When using mongo panache  (in native or in java mode tested with two) , when you define the  property   "quarkus.mongodb.database" in a profile like : "%myprofile.quarkus.mongodb.database" 
when you launch your application you get  "java.util.NoSuchElementException: Property quarkus.mongodb.database not found"  even when you use -Dquarkus.profile=myprofil

but if you define it in %dev or %prod  or as global param everything works fine

```java

org.jboss.resteasy.spi.UnhandledException: java.util.NoSuchElementException: Property quarkus.mongodb.database not found
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:503)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:118)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:74)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: Property quarkus.mongodb.database not found
        at io.smallrye.config.SmallRyeConfig.propertyNotFound(SmallRyeConfig.java:221)
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:112)
        at io.quarkus.mongodb.panache.runtime.MongoOperations.mongoDatabase(MongoOperations.java:273)
        at io.quarkus.mongodb.panache.runtime.MongoOperations.mongoDatabase(MongoOperations.java:186)
        at net.afco.vehicle.models.Vehicle.mongoDatabase(Vehicle.java)
        at net.afco.vehicle.api.VehicleAPI.init(VehicleAPI.java:66)
        at net.afco.vehicle.api.VehicleAPI_Bean.create(VehicleAPI_Bean.zig:307)
        at net.afco.vehicle.api.VehicleAPI_Bean.create(VehicleAPI_Bean.zig:116)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at net.afco.vehicle.api.VehicleAPI_Bean.get(VehicleAPI_Bean.zig:61)
        at net.afco.vehicle.api.VehicleAPI_Bean.get(VehicleAPI_Bean.zig:89)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:355)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:367)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:222)
        at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:219)
        at io.quarkus.arc.runtime.ArcRecorder$2$1.create(ArcRecorder.java:79)
        at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:56)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:69)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
        ... 13 more
```

**Expected behavior**
Panache can find property quarkus.mongodb.database when used in specific profile

**Actual behavior**
Panche can only find the property quarkus.mongodb.database when defined in %dev , %prod profiles or as global params

**To Reproduce**
1. create a quarkus project (quarkus version 1.0.1.Final)  
2. Create a POJO with Mongo Panache
2. Set your database name and url in specific profil (inside application.properties)

**Environment (please complete the following information):**
Quarkus version 1.0.1.Final
jdk:8

**Comment by gsmet** [comment]
@dmlloyd does it ring a bell?

**Comment by dmlloyd** [comment]
Not precisely but I'd bet it's fixed upstream already.  @zakhdar maybe try with a build from master?

**Comment by geoand** [comment]
Or even `1.1.0.CR1`?

**Comment by dmlloyd** [comment]
1.1.0.CR1 might not contain all of the necessary fixes.

**Comment by loicmathieu** [comment]
@zakhdar can you try with a recent version of Quakrus, 1.4.1.Final for example, and see if you still have the issue ?

**Comment by Mefffiu** [comment]
I am don't using profiles but for me, it is still not working for: `1.4.1.Final`

**Comment by loicmathieu** [comment]
@Mefffiu this isssue is about using profile and `quarkus.mongodb.database` property, you said that you are not using profile and you code is still not working ?
Maybe I don't understand but you seem to have a different issue ? If this is the case please open an other issue on Github.

**Comment by loicmathieu** [comment]
Closing this one as we haven't heared from the reporter and #11058 rework the retrieval of mongodb database name.
