### ISSUE TITLE
Integration Tests - Maven tooling FAILURE 

### ISSUE THREAD

**Issue by dufoli** [quarkusio/quarkus#6172]
when I run 
mvn clean install  on quarkus source
it failed on quarkus-integration-test-maven

windows environment

Here is the log:
```
 - in io.quarkus.maven.it.RemoteDevMojoIT
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   DevMojoIT.testThatClassAppCanRun:45->MojoTestBase.assertThatOutputWorksCorrectly:263
Expecting:
 <false>
to be equal to:
 <true>
but was not.
[ERROR]   JarRunnerIT.testThatJarRunnerConsoleOutputWorksCorrectly:57->MojoTestBase.assertThatOutputWorksCorrectly:263
Expecting:
 <false>
to be equal to:
 <true>
but was not.
[ERROR]   NativeImageIT.testJavaLibraryPathAtRuntime:45
Expecting:
 <"[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< org.acme:acme >----------------------------
[INFO] Building acme 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ acme ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\src\quarkus\integration-tests\maven\target\test-classes\projects\native-image-app-output\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ acme ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to D:\src\quarkus\integration-tests\maven\target\test-classes\projects\native-image-app-output\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ acme ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\src\quarkus\integration-tests\maven\target\test-classes\projects\native-image-app-output\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ acme ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ acme ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ acme ---
[INFO] Building jar: D:\src\quarkus\integration-tests\maven\target\test-classes\projects\native-image-app-output\target\acme-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ acme ---
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: D:\src\quarkus\integration-tests\maven\target\test-classes\projects\native-image-app-output\target\acme-1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1782ms
[INFO]
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (default) @ acme ---
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: D:\src\quarkus\integration-tests\maven\target\test-classes\projects\native-image-app-output\target\acme-1.0-SNAPSHOT-native-image-source-jar\acme-1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from D:\src\quarkus\integration-tests\maven\target\test-classes\projects\native-image-app-output\target\acme-1.0-SNAPSHOT-native-image-source-jar\acme-1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version dev
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] C:\Program Files\graalvm-ce-19.2.0.1\bin\native-image.cmd -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar acme-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:+JNI -H:-UseServiceLoaderFeature -H:+StackTrace acme-1.0-SNAPSHOT-runner
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.002 s
[INFO] Finished at: 2019-12-14T11:32:03+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:native-image (default) on project acme: Failed to generate a native image: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:323)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
[ERROR]         at java.lang.Thread.run(Thread.java:748)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: -1073741819
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:312)
[ERROR]         ... 12 more
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
">
to contain:
 <"BUILD SUCCESS">
 (ignoring case)
[INFO]
[ERROR] Tests run: 46, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by dufoli** [comment]
I have that on each branch I worked on. So I always push to PR to have test on azure ;-(

**Comment by gwenneg** [comment]
I'm not sure of what's causing the failure, but you should use GraalVM `19.3.0 `instead of `19.2.0.1` if you're doing this from `master`.

**Comment by geoand** [comment]
Another thing you need to make of when running the tests, is to not have any application already running on the ports used by the test applications

**Comment by geoand** [comment]
Does this still occur @dufoli ? CI on Windows seems to be passing without issues

**Comment by dufoli** [comment]
yes still occure with graalvm 19.3.0. I have check service and port and it is not the reason.
I find another issue #4841 hich is maybe the same.

**Comment by dufoli** [comment]
I think I have found the issue I used git bash instead of cygwin terminal to run under windows. BTW there is nothing on documentation about windows native support.
I install cygwin-devel  (replace glibc)+ gcc-core +  zlib-devel + libstdc
Hope it will worked. If it worked, I will add this solution to adoc to help other window guys.
Else I will use a linux docker.

**Comment by geoand** [comment]
Closing as this seems unrelated to Quarkus
