### ISSUE TITLE
Keycloak/OIDC NullPointerException

### ISSUE THREAD

**Issue by TheGeekPharaoh** [quarkusio/quarkus#6200]
**Describe the bug**

After configuring a simple Quarkus project with JAX-RS services I see the following exception when trying to access the service:

```
20:55:29 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] HTTP Request to /api/v1/mymethod failed, error id: 666dd651-6a8b-4004-9c11-3c5bee54503f-5: java.lang.NullPointerException
    at io.quarkus.keycloak.pep.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:44)
    at io.quarkus.keycloak.pep.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:28)
    at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$1$1.run(HttpAuthorizer.java:65)
    at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:224)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at java.base/java.lang.Thread.run(Thread.java:830)
    at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Expected behavior**

For service endpoints without authorization checks (@RolesAllowed, etc.) I would expect the call to go through with no issue.  For calls with authorization checks I would expect the check to be performed and access granted/denied as appropriate.

**Actual behavior**

The exception above occurs whether the service endpoint has authorization applied (@RolesAllowed, entries in application.properties, etc.) or not.  It occurs whether I have authenticated and include an Access Token or not.

**To Reproduce**
1. Create a simple Quarkus REST project, including OIDC support
2. Create a JAX-RS endpoint with no authorization/authentication requirements
3. Attempt to hit the service endpoint using curl or similar

**Configuration**
```properties

quarkus.oidc.auth-server-url=http://localhost:8880/auth/realms/myrealm
quarkus.oidc.client-id=myreal-default
quarkus.oidc.credentials.secret=<SECRET UUID>
quarkus.oidc.authentication.scopes=oidc
quarkus.oidc.application-type=service
```

**Environment (please complete the following information):**
 - Quarkus 1.0.1
- Keycloak 8.0.1

**Comment by sberyozkin** [comment]
@sdnakhla So you have `quarkus-keycloak-authorization` dependency but don't intend to use it ? Can you please try `Quarkus 1.1.0.CR1` ? CC @pedroigor

**Comment by sdnakhla** [comment]
@sberyozkin that's the thing.  I have not listed quarkus-keycloak-authorization as a dependency.  Not sure why I'm seeing exceptions related to KeycloakPolicyEnforcerAuthorizer.  Is it a chained dependency when using OIDC or Undertow?  I'll give v1.1.0.CR1 a shot and see if that corrects things.

**Comment by sdnakhla** [comment]
@sberyozkin what do I need to do to include v1.1.0.CR1 in my pom.xml?  I'm guessing there's a separate repo for snapshots but I don't see that documented anywhere?

**Comment by gsmet** [comment]
You just need to use the quarkus-bom instead of the quarkus-universe-bom.

**Comment by TheGeekPharaoh** [comment]
Just tested with 1.1.0.CR1.  Same issue...

```
18:59:35 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] HTTP Request to /api/v1/echo/test failed, error id: eaec2a38-fea9-4ff4-be83-ad8e250422b6-2: java.lang.NullPointerException
	at io.quarkus.keycloak.pep.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:44)
	at io.quarkus.keycloak.pep.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:28)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$1$1.run(HttpAuthorizer.java:65)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:224)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:830)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

```

**Comment by TheGeekPharaoh** [comment]
Looks like this was the result of a build including more dependencies than it should.  Clearing out my Maven cache and doing a clean/rebuild a couple times seems to have resolved it.  It was including keycloak-authorization when it shouldn't have been.  After the cleanup it was no longer being included and is working properly.

**Comment by sberyozkin** [comment]
@TheGeekPharaoh thanks, I've also confirmed as well as that just adding this dependency to `integration-tests/oidc' test does not cause any issues
