### ISSUE TITLE
UnsupportedOperationException when trying to run dev mode on a multi-module project.

### ISSUE THREAD

**Issue by spolti** [quarkusio/quarkus#6275]
**Describe the bug**
When trying to run quarkus:dev on a multi-module project this issue happens:

```
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.lang.UnsupportedOperationException
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:70)
Caused by: java.lang.UnsupportedOperationException
        at java.base/java.util.AbstractCollection.add(AbstractCollection.java:267)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at io.quarkus.dev.DevModeContext$ModuleInfo.addSourcePaths(DevModeContext.java:165)
        at io.quarkus.dev.DevModeMain.lambda$setupRuntimeCompilation$0(DevModeMain.java:232)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at io.quarkus.dev.DevModeMain.setupRuntimeCompilation(DevModeMain.java:232)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:88)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)

```

**To Reproduce**
1. create a multi module project
2. navitage to the "runnable" module
3. run mvn clean compile quarkus:dev

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 

> openjdk version "11.0.5" 2019-10-15
> OpenJDK Runtime Environment 18.9 (build 11.0.5+10)
> OpenJDK 64-Bit Server VM 18.9 (build 11.0.5+10, mixed mode, sharing)

 - GraalVM version (if different from Java): Not used in this case
 - Quarkus version or git rev: tested with 1.0.1.Final and 1.1.0.Final

**Additional context**
(Add any other context about the problem here.)

**Comment by jaikiran** [comment]
I haven't been able to reproduce this issue. However, looking at the code, this looks like a genuine issue which needs a fix. So I've opened https://github.com/quarkusio/quarkus/pull/6278 which contains a fix.
