### ISSUE TITLE
Configuring application using application.yaml should accept directives separator

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#6297]
## Description

Support with YAML arrived with version `1.1.0.Final`. That's great! Now improving on this, I think it would be great to be able to parse/understand directives separator so we can isolate the profiles in such way, if possible (and applicable).

I understand this separation is already done and we can look at the profiles by their name, but still, I think they are more clear if this is supported...again, if makes sense.

An example file would be like this:

```yaml
#
# https://quarkus.io/guides/all-config
# https://quarkus.io/guides/config#overriding-properties-at-runtime
---
quarkus:
  datasource:
    driver: org.postgresql.Driver
  flyway:
    migrate-at-start: true
  health:
    extensions:
      enabled: true
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
  http:
    port: 8080
  log: # ALL > FINEST > FINER > FINE > CONFIG > INFO > WARNING > SEVERE > OFF
    console:
      async: true
      color: true
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} |- %-5p in %c:%L{3.} [%t] - %s%e%n"
    level: WARNING
  resteasy:
    path: /api
  smallrye-openapi:
    path: /open-api
  swagger-ui:
    always-include: true
    path: /swagger-ui
---
"%dev":
  quarkus:
    datasource:
      password: postgres
      url: jdbc:postgresql://localhost:5432/quarkus_web
      username: postgres
    flyway:
      clean-at-start: true
    hibernate-orm:
      log:
        sql: true
      statistics: true
    log:
      category:
        "io.quarkus.arc.processor":
          level: OFF
        "io.quarkus":
          level: INFO
        "org.acme":
          level: CONFIG
---
"%prod":
  quarkus:
    datasource:
      password: postgres
      url: jdbc:postgresql://localhost:5432/quarkus_web
      username: postgres
    flyway:
      clean-at-start: false
    hibernate-orm:
      database:
        generation: none
      sql-load-script: no-file
---
"%test":
  quarkus:
    datasource:
      password: postgres
      url: jdbc:postgresql://localhost:5432/quarkus_web
      username: postgres
    flyway:
      clean-at-start: true
    log:
      category:
        "io.quarkus":
          level: WARNING
        "org.acme":
          level: WARNING
```

If used in such way, this error pops up:

```shell
14:47:30,257 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: expected a single document in the stream
 in 'reader', line 5, column 1:
    quarkus:
    ^
but found another document
 in 'reader', line 31, column 1:
    ---
    ^

	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:114)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:519)
	at io.smallrye.config.source.yaml.YamlConfigSource.streamToMap(YamlConfigSource.java:48)
	at io.smallrye.config.source.yaml.YamlConfigSource.<init>(YamlConfigSource.java:33)
	at io.quarkus.config.yaml.runtime.ApplicationYamlProvider.getConfigSources(ApplicationYamlProvider.java:36)
	at io.smallrye.config.SmallRyeConfigBuilder.lambda$discoverSources$0(SmallRyeConfigBuilder.java:78)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:78)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:169)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:190)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:133)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:88)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:113)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:177)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:95)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
```

> Another thing could be to move the profile name into its own key within the `quarkus` "namespace".

**Comment by dmlloyd** [comment]
I'm pretty sure this is doable just by reading all the docs in sequence. It's not exactly the same as separating by profile but it could be used for that.

**Comment by famod** [comment]
This is possible in Spring Boot btw and would come in handy for Quarkus as well:
https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-multi-profile-yaml
