### ISSUE TITLE
Mysql-reactive client is not working on native mode

### ISSUE THREAD

**Issue by iabughosh** [quarkusio/quarkus#6321]
I am trying to run mysql-reactive client in native mode and it is not working while it works fine in JVM mode.

I am receiving the below exception when I try to connect to it :
```
java.util.concurrent.CompletionException: java.security.NoSuchAlgorithmException: RSA KeyFactory not available
bookrx_1  | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:164)
bookrx_1  | 	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:110)
bookrx_1  | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:594)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:468)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:421)
bookrx_1  | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:423)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:365)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
bookrx_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
bookrx_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
bookrx_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
bookrx_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
bookrx_1  | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
bookrx_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
bookrx_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
bookrx_1  | 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
bookrx_1  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:120)
bookrx_1  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
bookrx_1  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:85)
bookrx_1  | 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
bookrx_1  | 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
bookrx_1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
bookrx_1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
bookrx_1  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
bookrx_1  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
bookrx_1  | 	at java.lang.Thread.run(Thread.java:748)
bookrx_1  | 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
bookrx_1  | 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
bookrx_1  | 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
bookrx_1  | Caused by: java.util.concurrent.CompletionException: java.security.NoSuchAlgorithmException: RSA KeyFactory not available
bookrx_1  | 	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
bookrx_1  | 	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
bookrx_1  | 	at org.ibra.ebs.service.BookService.init(BookService.java:38)
bookrx_1  | 	at org.ibra.ebs.service.BookService_Bean.create(BookService_Bean.zig:149)
bookrx_1  | 	at org.ibra.ebs.service.BookService_Bean.create(BookService_Bean.zig:343)
bookrx_1  | 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
bookrx_1  | 	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
bookrx_1  | 	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
bookrx_1  | 	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
bookrx_1  | 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
bookrx_1  | 	at org.ibra.ebs.service.BookService_ClientProxy.arc$delegate(BookService_ClientProxy.zig:99)
bookrx_1  | 	at org.ibra.ebs.service.BookService_ClientProxy.getLastestRecords(BookService_ClientProxy.zig:248)
bookrx_1  | 	at org.ibra.ebs.resource.BookResource.get(BookResource.java:47)
bookrx_1  | 	at org.ibra.ebs.resource.BookResource_ClientProxy.get(BookResource_ClientProxy.zig:252)
bookrx_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
bookrx_1  | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
bookrx_1  | 	... 37 more
bookrx_1  | Caused by: java.security.NoSuchAlgorithmException: RSA KeyFactory not available
bookrx_1  | 	at java.security.KeyFactory.<init>(KeyFactory.java:138)
bookrx_1  | 	at java.security.KeyFactory.getInstance(KeyFactory.java:172)
bookrx_1  | 	at io.vertx.mysqlclient.impl.util.RsaPublicKeyEncryptor.generateRsaPublicKey(RsaPublicKeyEncryptor.java:34)
bookrx_1  | 	at io.vertx.mysqlclient.impl.util.RsaPublicKeyEncryptor.encrypt(RsaPublicKeyEncryptor.java:21)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.AuthenticationCommandBaseCodec.sendEncryptedPasswordWithServerRsaPublicKey(AuthenticationCommandBaseCodec.java:76)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.AuthenticationCommandBaseCodec.handleAuthMoreData(AuthenticationCommandBaseCodec.java:35)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.InitialHandshakeCommandCodec.handleAuthentication(InitialHandshakeCommandCodec.java:188)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.InitialHandshakeCommandCodec.decodePayload(InitialHandshakeCommandCodec.java:60)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePayload(MySQLDecoder.java:62)
bookrx_1  | 	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decode(MySQLDecoder.java:51)
bookrx_1  | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
bookrx_1  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
bookrx_1  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
bookrx_1  | 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
bookrx_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
bookrx_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
bookrx_1  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
bookrx_1  | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
bookrx_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
bookrx_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
bookrx_1  | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
bookrx_1  | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
bookrx_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
bookrx_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
bookrx_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
bookrx_1  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
bookrx_1  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
bookrx_1  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
bookrx_1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
bookrx_1  | 	at java.lang.Thread.run(Thread.java:748)
bookrx_1  | 	... 2 more
```

**Configuration**
```properties
quarkus.datasource.url = vertx-reactive:mysql://myhost:3306/ebs_book
quarkus.datasource.username = xxx
quarkus.datasource.password = xxx
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "1.8.0_202"
OpenJDK Runtime Environment Corretto-8.202.08.2 (build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)
 - GraalVM version (if different from Java): 
graalvm-ce-19.0.2
 - Quarkus version or git rev: 
1.1.0.Final

Also tried this [enabling SSL for my image](https://quarkus.io/guides/native-and-ssl#working-with-containers) and it didn't work.

**Comment by galderz** [comment]
You can probably workaround this if you add `--enable-all-security-services` to the `native-image` call that quarkus makes so that all security algorithms are added. By default this is false, since each Quarkus service adds only what it needs. I've not looked at the Quarkus code in detail, but chances are that the Quarkus/Vert.x integration should add RSA as one of the security algorithms it should make available.

**Comment by iabughosh** [comment]
Do you mean by adding "--enable-all-security-services" to docker file image before building or as a run argument ?

**Comment by galderz** [comment]
@iabughosh To the image building process, it's parameter of `native-image` which builds native images :)

**Comment by galderz** [comment]
Btw, the quarkus Maven plugin, for the `native-image` goal, has a parameter called `enableAllSecurityServices` that you should be to enable to achieve the same thing.

**Comment by cescoffier** [comment]
@tsegismont can you have a look?

**Comment by tsegismont** [comment]
@iabughosh it seems similar issues have been filed for other modules, I'm trying to determine if it can be fixed the same way. In the meantime, could you please post a minimal reproducer? Thank you

**Comment by tsegismont** [comment]
@iabughosh can you also try to add `SunRsaSign` provider in the app config file:

```properties
quarkus.security.security-providers=SunRsaSign,SunJCE
```

See https://quarkus.io/guides/security#registering-security-providers

**Comment by cescoffier** [comment]
Any update on this?

**Comment by tsegismont** [comment]
Not yet. I have been able to setup a local db for testing. But no PR yet

Le ven. 15 mai 2020 à 10:27, Clement Escoffier <notifications@github.com> a
écrit :

**Comment by gsmet** [comment]
Wouldn't producing a `ExtensionSslNativeSupportBuildItem` be enough to solve the issue?

**Comment by tsegismont** [comment]
Guillaume, I don't know yet what an `ExtensionSslNativeSupportBuildItem`
is, but I'll look into this.

My plan was to add JksOption, PemCertOption and the likes to the reactive
postgres db config (we have such options on the eventbus config already).

Le ven. 15 mai 2020 à 10:31, Guillaume Smet <notifications@github.com> a
écrit :
