### ISSUE TITLE
[native] JsonbException: No default constructor found.

### ISSUE THREAD

**Issue by TomasHofman** [quarkusio/quarkus#6329]
**Describe the bug**

When running native executable, calling `JsonbBuilder.fromJson(...)` leads to exception: "JsonbException: Can't create instance of a class: class ..., No default constructor found.":

```JsonbBuilder.create().fromJson(body, DataObject.class);```

even though the class has a default constructor:

```
public class DataObject {
    public String field;
    public DataObject() {
    }
}
```

**Expected behavior**
Object is deserialized successfully.

**Actual behavior**
```2019-12-23 16:53:43,752 SEVERE [org.ecl.yas.int.Unmarshaller] (vert.x-eventloop-thread-0) Can't create instance of a class: class org.jboss.set.dependencyalignment.domain.DataObject, No default constructor found.
2019-12-23 16:53:43,752 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /test failed, error id: 165afe5f-8202-4baa-a6e6-feb5766f5436-1: javax.json.bind.JsonbException: Can't create instance of a class: class org.jboss.set.dependencyalignment.domain.DataObject, No default constructor found.
	at org.eclipse.yasson.internal.serializer.ObjectDeserializer.getInstance(ObjectDeserializer.java:95)
	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:61)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:68)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:54)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:53)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:60)
	at org.jboss.set.dependencyalignment.PullRequestLoggerRoutes.test(PullRequestLoggerRoutes.java:80)
	at org.jboss.set.dependencyalignment.PullRequestLoggerRoutes_ClientProxy.test(PullRequestLoggerRoutes_ClientProxy.zig:130)
	at org.jboss.set.dependencyalignment.PullRequestLoggerRoutes_RouteHandler_test_095392cced92ba3989cd0f619dfc45e9c0132af0.handle(PullRequestLoggerRoutes_RouteHandler_test_095392cced92ba3989cd0f619dfc45e9c0132af0.zig:47)
	at io.quarkus.vertx.http.runtime.ResumeHandler.handle(ResumeHandler.java:19)
	at io.quarkus.vertx.http.runtime.ResumeHandler.handle(ResumeHandler.java:6)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
```

**To Reproduce**
1. Create custom data object and an app scoped bean with Vertx route:
```
public class DataObject {
    public String field;
    public DataObject() {
    }
}
```
```
@ApplicationScoped
public class PullRequestLoggerRoutes {
    @Route(path = "/test", methods = HttpMethod.GET, consumes = "application/json")
    public void test(RoutingContext rc) {
        JsonbBuilder.create().fromJson(rc.getBodyAsString(), DataObject.class);
        rc.response().end();
    }
}
```
2. Build native executable.
3. Run the executable and run `curl -X GET -H "Content-Type: application/json" -d '{"field":"str"}' http://localhost:8080/test`

**Configuration**
Installed features: [cdi, reactive-pg-client, resteasy-jsonb, vertx, vertx-web]

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
  ```Linux rama.usersys.redhat.com 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```
 - Output of `java -version`: 
   openjdk version "11" 2018-09-25
   OpenJDK Runtime Environment 18.9 (build 11+28)
   OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
 - GraalVM version (if different from Java): graalvm-ce-19.2.1
 - Quarkus version or git rev: 1.0.1.Final

**Additional context**
Issue only occurs with native executable, running on JVM the application works fine.

**Comment by machi1990** [comment]
Hi @TomasHofman, the `DataObject` class  needs to be registered for reflection  through the `@RegisterForReflection` annotation as explained in this guide https://quarkus.io/guides/writing-native-applications-tips#using-the-registerforreflection-annotation.

**Comment by TomasHofman** [comment]
Yesss, I forgot about this. Thank you @machi1990!

**Comment by machi1990** [comment]
You are welcome. @TomasHofman
