### ISSUE TITLE
Gradle build fails with error Root cannot inherit parent name because it has no parent at class io.quarkus.runtime.TopLevelRootConfig

### ISSUE THREAD

**Issue by debae** [quarkusio/quarkus#6344]
**Describe the bug**
When upgrading an existing project ( Gradle 5.4.1 & Quarkus 1.0.1.Final ) to the new version 1.1.0.Final and thus also using Gradle 6.0.1 I can no longer run ./gradlew build.
It is unclear to me what is going wrong, the error message I get is **Root cannot inherit parent name because it has no parent at class io.quarkus.runtime.TopLevelRootConfig**

The following extensions are active for this project : 

```
    implementation enforcedPlatform("io.quarkus:quarkus-bom:${quarkusVersion}")
    implementation 'io.quarkus:quarkus-amazon-lambda'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-hibernate-validator'
    implementation "io.quarkus:quarkus-amazon-lambda-deployment:${quarkusVersion}"
```

**Expected behavior**
Project is build correctly

**Actual behavior**

```
2019-12-26T15:57:08.425+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
2019-12-26T15:57:08.425+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2019-12-26T15:57:08.425+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2019-12-26T15:57:08.425+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':quarkusBuild'.
2019-12-26T15:57:08.426+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to build a runnable JAR
2019-12-26T15:57:08.426+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2019-12-26T15:57:08.426+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2019-12-26T15:57:08.426+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
2019-12-26T15:57:08.426+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2019-12-26T15:57:08.426+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
2019-12-26T15:57:08.426+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':quarkusBuild'
2019-12-26T15:57:08.429+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.GradleException: Failed to build a runnable JAR
2019-12-26T15:57:08.429+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.gradle.tasks.QuarkusBuild.buildQuarkus(QuarkusBuild.java:171)
...
2019-12-26T15:57:08.435+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
2019-12-26T15:57:08.435+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
2019-12-26T15:57:08.435+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:174)
2019-12-26T15:57:08.435+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 30 more
2019-12-26T15:57:08.436+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: io.quarkus.creator.AppCreatorException: Failed to augment application classes
2019-12-26T15:57:08.436+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.creator.phase.augment.AugmentTask.run(AugmentTask.java:190)
2019-12-26T15:57:08.436+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.creator.phase.augment.AugmentTask.run(AugmentTask.java:48)
2019-12-26T15:57:08.436+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.creator.CuratedApplicationCreator.runTask(CuratedApplicationCreator.java:139)
2019-12-26T15:57:08.436+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.gradle.tasks.QuarkusBuild.buildQuarkus(QuarkusBuild.java:168)
2019-12-26T15:57:08.436+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 92 more
2019-12-26T15:57:08.436+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.IllegalArgumentException: Root cannot inherit parent name because it has no parent at class io.quarkus.runtime.TopLevelRootConfig
2019-12-26T15:57:08.436+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.deployment.configuration.ConfigDefinition.reportError(ConfigDefinition.java:448)
2019-12-26T15:57:08.436+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.deployment.configuration.ConfigDefinition.registerConfigRoot(ConfigDefinition.java:199)
2019-12-26T15:57:08.436+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:187)
2019-12-26T15:57:08.437+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:85)
2019-12-26T15:57:08.437+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.creator.phase.augment.AugmentTask.run(AugmentTask.java:181)
2019-12-26T15:57:08.437+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 95 more
```

**To Reproduce**
1. Change quarkusVersion from 1.0.1.Final to 1.1.0.Final
2. Execute `./gradlew build`

**Configuration**
```properties
quarkus.log.level=TRACE

quarkus.lambda.handler=ExampleLambda

quarkus.log.console.enable=true
quarkus.log.console.format={"timestamp": "%d{yyyy-MM-dd'T'HH:mm:ss.SSS}", "type":"LogMessage", "level": "%p", "loggerName": "%C", "message": "%s", "appName":"doc-gen", "componentName":"russianlabel-reporting-lambda", "stackTrace":"%e" }%n
quarkus.log.console.level=INFO

quarkus.ssl.native=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin APRXJGH6D5D5F9 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.1.0.Final

**Comment by gsmet** [comment]
@debae I don't see a reproducer? Are you still working on it?

**Comment by debae** [comment]
> @debae I don't see a reproducer? Are you still working on it?

Yes, I need to remove some code and dependencies from my client.

**Comment by debae** [comment]
I've created this reproducer project : https://github.com/debae/quarkus-issue-6344
Just git clone and execute `./gradlew build`should be sufficient.

**Comment by amcirillo** [comment]
I also have a project I upgraded to 1.1.0.Final from 1.0.1.Final and I get the same problem described above. Maybe this is a problem in the way I tried upgrading the properties in my pom? I updated two properties,  quarkus.platform.artifact-id and quarkus.platform.version, this is the relevant properties section in my pom:

`<properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>1.0.1.Final</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>1.1.0.Final</quarkus.platform.version>
    <surefire-plugin.version>2.22.1</surefire-plugin.version>
  </properties>`

I  changed the artifact-id from quarkus-universe-bom to quarkus-bom because I no longer saw quarkus-universe-bom in the maven repos. I also left the quarkus plugin version at 1.0.1.Final because I didn't see a newer version in the repos.

If this is not the intended way to upgrade to a newer version of the framework is there any documentation anywhere that points out how to do this? I tried looking and didn't see anything that looked relevant.

Thanks

**Comment by amcirillo** [comment]
I think I figured out my initial problem. When I first tried to upgrade to version 1.1.0.Final there was not yet a new version of the quarkus-maven-plugin. I now see in maven central that version 1.1.0.Final of the plugin has been released. After adjusting my properties to include this new version of the plugin my build gets past the initial problem mentioned above, but now I am running into other issues generating a native image. Maybe the correct course of action is to wait until there is documentation about how to upgrade to newer versions of the framework, or perhaps use the project generator if that has been upgraded to 1.1.0.Final, generate a new project and see if there are any other noticeable differences in the pom.

**Comment by gsmet** [comment]
@amcirillo  The Maven plugin is published exactly at the same time as the rest of the artifacts Quarkus artifacts. This is not the case of the universe bom that came significantly later this time as we had to wait for another release of Camel Quarkus. 

We haven’t changed anything that could break in a Maven project so please open a separate issue with whatever you experience. It’s something entirely different than the issue at hand. 

Thanks!

**Comment by geoand** [comment]
@debae I was able to make `./gradlew clean build` work on your reproducer for Quarkus `1.1.0.Final`.

Basically all I did was follow the [migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.1#gradle-plugin) and apply version `1.1.0.Final` to all necessary properties.

For reference, here is the `git diff` of the changes I made:

```
diff --git a/build.gradle b/build.gradle
index f1ff923..68542b9 100644
--- a/build.gradle
+++ b/build.gradle
@@ -1,17 +1,6 @@
 import static org.gradle.api.JavaVersion.VERSION_1_8
 
 
-buildscript {
-    repositories {
-        mavenLocal()
-        mavenCentral()
-    }
-    dependencies {
-        classpath "io.quarkus:quarkus-gradle-plugin:${quarkusPluginVersion}"
-    }
-}
-
-
 plugins {
     id 'java'
     id 'io.quarkus' version "${quarkusPluginVersion}"
diff --git a/gradle.properties b/gradle.properties
index 9dc0beb..61934a9 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -1,3 +1,3 @@
 version=1.0.0
 quarkusVersion = 1.1.0.Final
-quarkusPluginVersion = 1.0.1.Final
+quarkusPluginVersion = 1.1.0.Final
diff --git a/settings.gradle b/settings.gradle
index 5e2a88f..1db4c98 100644
--- a/settings.gradle
+++ b/settings.gradle
@@ -8,5 +8,4 @@ pluginManagement {
         id 'io.quarkus' version "${quarkusPluginVersion}"
     }
 }
-
 rootProject.name='russianlabel-reporting-lambda'
\ No newline at end of file
```

**Comment by gsmet** [comment]
@debae can you confirm it's all good for you?

**Comment by debae** [comment]
@gsmet With the changes proposed by @geoand it's working fine. I totally overlooked the fact that i mixed the versions of the plugin and quarkus itself.

**Comment by geoand** [comment]
Glad to hear it worked!
