### ISSUE TITLE
native image build fails on graal-ce-java11-19.3.0.2

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#6379]
**Describe the bug**
Native image build fails with the following exception using graal ce 19.3.0.2
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.3.0.2 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /opt/graalvm-ce-java11-19.3.0.2/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar getting-started-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace getting-started-1.0-SNAPSHOT-runner
[getting-started-1.0-SNAPSHOT-runner:123376]    classlist:   5,030.74 ms
[getting-started-1.0-SNAPSHOT-runner:123376]        setup:     498.97 ms
Error: Already registered: jdk.internal.loader.BootLoader.findResourceAsStream(String, String)
com.oracle.svm.core.util.UserError$UserException: Already registered: jdk.internal.loader.BootLoader.findResourceAsStream(String, String)
    at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
    at com.oracle.svm.core.util.UserError.guarantee(UserError.java:86)
    at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.register(AnnotationSubstitutionProcessor.java:708)
    at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:334)
    at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:298)
    at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
    at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
    at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:876)
    at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:825)
    at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
    at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
    at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
```

**Comment by gsmet** [comment]
@johnaohara I added a commit here: https://github.com/quarkusio/quarkus/pull/6364

**Comment by johnaohara** [comment]
The native image builds successfully after removing the Bootloader substitutions ( https://github.com/machi1990/quarkus/commit/c64acd61ccfa13e363418a895e989a7a64608050)

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.3.0.2 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /opt/graalvm-ce-java11-19.3.0.2/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar getting-started-1.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace getting-started-1.0-SNAPSHOT-runner
[getting-started-1.0-SNAPSHOT-runner:132079]    classlist:   5,670.51 ms
[getting-started-1.0-SNAPSHOT-runner:132079]        (cap):     916.42 ms
[getting-started-1.0-SNAPSHOT-runner:132079]        setup:   2,909.50 ms
13:13:27,612 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
[getting-started-1.0-SNAPSHOT-runner:132079]   (typeflow):  27,452.29 ms
[getting-started-1.0-SNAPSHOT-runner:132079]    (objects):  16,463.74 ms
[getting-started-1.0-SNAPSHOT-runner:132079]   (features):     674.18 ms
[getting-started-1.0-SNAPSHOT-runner:132079]     analysis:  46,131.73 ms
[getting-started-1.0-SNAPSHOT-runner:132079]     (clinit):     652.32 ms
[getting-started-1.0-SNAPSHOT-runner:132079]     universe:   1,988.41 ms
[getting-started-1.0-SNAPSHOT-runner:132079]      (parse):   3,993.01 ms
[getting-started-1.0-SNAPSHOT-runner:132079]     (inline):   7,320.09 ms
[getting-started-1.0-SNAPSHOT-runner:132079]    (compile):  40,938.11 ms
[getting-started-1.0-SNAPSHOT-runner:132079]      compile:  54,006.12 ms
[getting-started-1.0-SNAPSHOT-runner:132079]        image:   3,500.81 ms
[getting-started-1.0-SNAPSHOT-runner:132079]        write:     770.17 ms
[getting-started-1.0-SNAPSHOT-runner:132079]      [total]: 115,380.65 ms
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 118019ms

```

**Comment by geoand** [comment]
I made the fools errand of trying to remove them one by one and of course they are all needed :)
