### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by halber** [quarkusio/quarkus#6400]
**Describe the bug**
I get an java.lang.ExceptionInInitializerError when I try to run the docker container created from the Dockerfile.jvm file.

I'm on a macOS Catalina Version 10.15.2

```
$ docker run -i --rm -p 8080:8080 quarkus/getting-started-jvm
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -javaagent:/opt/agent-bond/agent-bond.jar=jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:27)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:334)
	... 1 more
Caused by: java.lang.RuntimeException: Failed to initialize Arc
	at io.quarkus.arc.Arc.initialize(Arc.java:26)
	at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:34)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources18.deploy_0(ArcProcessor$generateResources18.zig:53)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources18.deploy(ArcProcessor$generateResources18.zig:327)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:304)
	... 1 more
Caused by: java.lang.ClassNotFoundException: java.lang.constant.ConstantDesc
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.<init>(ConfigProducer_ProducerMethod_produceStringConfigProperty_75511873be6a3e578c4555b07b03c7231f99c7bc_Bean.zig:308)
	at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans1(Default_ComponentsProvider.zig:135)
	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:38)
	at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:102)
	at io.quarkus.arc.Arc.initialize(Arc.java:20)
	... 5 more
```

**To Reproduce**
```
mvn io.quarkus:quarkus-maven-plugin:1.1.0.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
cd getting-started
./mvnw quarkus:add-extension -Dextensions="io.quarkus:quarkus-smallrye-health"

mvn package
docker build -f src/main/docker/Dockerfile.jvm -t quarkus/getting-started-jvm .
docker run -i --rm -p 8080:8080 quarkus/getting-started-jvm
```

**Environment (please complete the following information):**
 - Output of `java -version`:  
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.1+9, mixed mode, sharing)
 - Quarkus version or git rev: 1.1.0.Final

**Comment by halber** [comment]
Ok, finally I saw my failure. Im compiling this on java 13 and the docker image uses java 1.8
