### ISSUE TITLE
adding a openapi extension to existing project starts giving NoSuchMethodError error for org.yaml.snakeyaml.events.MappingStartEvent

### ISSUE THREAD

**Issue by pawan2014** [quarkusio/quarkus#6420]
Using latest version of quarks. project is compiling fine until quarkus-smallrye-openapi is added to maven. Not sure if this is a error or some missing configuration.

Stacktrace
```
Listening for transport dt_socket at address: 5005
10:10:19,382 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
10:10:19,725 INFO  [org.hib.jpa.boo.int.PersistenceXmlParser] HHH000318: Could not find any META-INF/persistence.xml file in the classpath
10:10:19,838 INFO  [org.hib.Version] HHH000412: Hibernate Core {5.4.10.Final}
10:10:20,325 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor#build threw an exception: java.lang.NoSuchMethodError: org.yaml.snakeyaml.events.MappingStartEvent.<init>(Ljava/lang/String;Ljava/lang/String;ZLorg/yaml/snakeyaml/error/Mark;Lorg/yaml/snakeyaml/error/Mark;Ljava/lang/Boolean;)V
	at com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.writeStartObject(YAMLGenerator.java:543)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeStartObject(GeneratorBase.java:286)
	at com.fasterxml.jackson.databind.node.ObjectNode.serialize(ObjectNode.java:295)
	at com.fasterxml.jackson.databind.ser.std.SerializableSerializer.serialize(SerializableSerializer.java:39)
	at com.fasterxml.jackson.databind.ser.std.SerializableSerializer.serialize(SerializableSerializer.java:20)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:993)
	at io.smallrye.openapi.runtime.io.OpenApiSerializer.serialize(OpenApiSerializer.java:113)
	at io.quarkus.smallrye.openapi.deployment.SmallRyeOpenApiProcessor.build(SmallRyeOpenApiProcessor.java:259)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:180)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
```

Other dependencies
```
      <artifactId>quarkus-resteasy</artifactId>
      <artifactId>quarkus-junit5</artifactId>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <artifactId>quarkus-jsonb</artifactId>
      <artifactId>quarkus-hibernate-orm-panache</artifactId>
      <artifactId>quarkus-jdbc-postgresql</artifactId>
      <artifactId>quarkus-resteasy-jsonb</artifactId>
      <groupId>com.github.javafaker</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
      <artifactId>quarkus-smallrye-opentracing</artifactId>
      <artifactId>quarkus-smallrye-metrics</artifactId>
      <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
      <artifactId>quarkus-logging-gelf</artifactId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
```

**Comment by gsmet** [comment]
Looks like there is a mismatch between the SnakeYaml version and the Jackson one.

Are you using our BOM?

**Comment by pawan2014** [comment]
I think so. the entry in POM i see this <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>

Just for reference the sample project POM  https://github.com/pawan2014/microrofile-quarkus/blob/master/projectservice/pom.xml

**Comment by gsmet** [comment]
This isn't a Quarkus issue. You have a dependency convergence issue on SnakeYaml with 2 different artifacts of differents versions being there:
```
[INFO] +- com.github.javafaker:javafaker:jar:0.15:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.9:compile
[INFO] |  +- org.yaml:snakeyaml:jar:android:1.20:compile
```
and
```
[INFO] +- io.quarkus:quarkus-smallrye-openapi:jar:1.1.0.Final:compile
[INFO] |  +- io.smallrye:smallrye-open-api:jar:1.1.20:compile
[INFO] |  |  +- org.eclipse.microprofile.openapi:microprofile-openapi-api:jar:1.1.2:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.10:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.10.1:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.10:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.10:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.25:compile
```

**Comment by bodiam** [comment]
For those looking for a solution to this, we've forked java-faker here: https://github.com/datafaker-net/datafaker, which has this issue resolved.
