### ISSUE TITLE
empty configuration property behavior change

### ISSUE THREAD

**Issue by jordanglassman** [quarkusio/quarkus#6431]
**Describe the bug**
Up through 1.0.0.RC2, an optional configuration property that is left blank in `application.properties` would have its default set.  Upon upgrading to 1.1.0.Final, these properties now throw with `Caused by: java.util.NoSuchElementException: Required property some.boolean.prop not found`.

**Expected behavior**
Expected a property with a blank entry to use the default entry.

**Actual behavior**
Exception thrown:

```
[INFO] --- quarkus-maven-plugin:1.1.0.Final:dev (default-cli) @ my-artifactId ---
Listening for transport dt_socket at address: 5005
16:01:44,523 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
16:01:45,392 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:152)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:398)
	... 6 more
Caused by: java.lang.RuntimeException: Error injecting boolean org.my.group.MyApplication.someProp
	at org.my.group.MyApplication_Bean.create(MyApplication_Bean.zig:331)
	at org.my.group.MyApplication_Bean.create(MyApplication_Bean.zig:32)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at org.my.group.MyApplication_ClientProxy.arc$delegate(MyApplication_ClientProxy.zig:81)
	at org.my.group.MyApplication_ClientProxy.arc_contextualInstance(MyApplication_ClientProxy.zig:204)
	at io.quarkus.arc.runtime.ClientProxyUnwrapper.apply(ClientProxyUnwrapper.java:11)
	at io.quarkus.resteasy.common.runtime.ResteasyInjectorFactoryRecorder$1.apply(ResteasyInjectorFactoryRecorder.java:22)
	at io.quarkus.resteasy.common.runtime.QuarkusInjectorFactory$UnwrappingPropertyInjector.inject(QuarkusInjectorFactory.java:65)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.createApplication(ResteasyDeploymentImpl.java:373)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:284)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:90)
	at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.staticInit(ResteasyStandaloneRecorder.java:86)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit30.deploy_0(ResteasyStandaloneBuildStep$staticInit30.zig:880)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit30.deploy(ResteasyStandaloneBuildStep$staticInit30.zig:36)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:384)
	... 6 more
Caused by: java.util.NoSuchElementException: Required property some.boolean.prop not found
	at io.smallrye.config.inject.ConfigProducerUtil.propertyNotFound(ConfigProducerUtil.java:63)
	at io.smallrye.config.inject.ConfigProducerUtil.getValue(ConfigProducerUtil.java:57)
	at io.smallrye.config.inject.ConfigProducer.produceBooleanConfigProperty(ConfigProducer.java:86)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.create(ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.zig:101)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.get(ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.zig:364)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.get(ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.zig:44)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:53)
	at org.my.group.MyApplication_Bean.create(MyApplication_Bean.zig:312)
	... 24 more

16:01:45,393 INFO  [io.qua.dev.DevModeMain] Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
^C^[[A
[my-artifactId (master)]$ mvn clean compile quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< my-groupId:my-artifactId >----------------------
[INFO] Building my-artifactId my-version
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ my-artifactId ---
[INFO] Deleting /Users/jglassman/iiworkspace/my-artifactId/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ my-artifactId ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ my-artifactId ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/jglassman/iiworkspace/my-artifactId/target/classes
[INFO]
[INFO] --- quarkus-maven-plugin:1.1.0.Final:dev (default-cli) @ my-artifactId ---
Listening for transport dt_socket at address: 5005
16:04:32,312 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
16:04:33,232 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:152)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:398)
	... 6 more
Caused by: java.lang.RuntimeException: Error injecting boolean org.my.group.MyApplication.someProp
	at org.my.group.MyApplication_Bean.create(MyApplication_Bean.zig:331)
	at org.my.group.MyApplication_Bean.create(MyApplication_Bean.zig:32)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at org.my.group.MyApplication_ClientProxy.arc$delegate(MyApplication_ClientProxy.zig:81)
	at org.my.group.MyApplication_ClientProxy.arc_contextualInstance(MyApplication_ClientProxy.zig:204)
	at io.quarkus.arc.runtime.ClientProxyUnwrapper.apply(ClientProxyUnwrapper.java:11)
	at io.quarkus.resteasy.common.runtime.ResteasyInjectorFactoryRecorder$1.apply(ResteasyInjectorFactoryRecorder.java:22)
	at io.quarkus.resteasy.common.runtime.QuarkusInjectorFactory$UnwrappingPropertyInjector.inject(QuarkusInjectorFactory.java:65)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.createApplication(ResteasyDeploymentImpl.java:373)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:284)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:90)
	at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.staticInit(ResteasyStandaloneRecorder.java:86)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit30.deploy_0(ResteasyStandaloneBuildStep$staticInit30.zig:880)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit30.deploy(ResteasyStandaloneBuildStep$staticInit30.zig:36)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:384)
	... 6 more
Caused by: java.util.NoSuchElementException: Required property some.boolean.prop not found
	at io.smallrye.config.inject.ConfigProducerUtil.propertyNotFound(ConfigProducerUtil.java:63)
	at io.smallrye.config.inject.ConfigProducerUtil.getValue(ConfigProducerUtil.java:57)
	at io.smallrye.config.inject.ConfigProducer.produceBooleanConfigProperty(ConfigProducer.java:86)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.create(ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.zig:101)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.get(ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.zig:364)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.get(ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.zig:44)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:53)
	at org.my.group.MyApplication_Bean.create(MyApplication_Bean.zig:312)
	... 24 more
```

**To Reproduce**

trivial app:

```
package org.my.group;

import io.quarkus.runtime.StartupEvent;
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@ApplicationScoped
@ApplicationPath("/app")
public class MyApplication extends Application {
    private static final Logger LOGGER = LoggerFactory.getLogger(MyApplication.class);

    @Inject
    @ConfigProperty(name = "some.boolean.prop", defaultValue = "false")
    boolean someProp;

    void onStart(@Observes StartupEvent ev) {
        LOGGER.error("on startup ...");
    }
}
```

application.properties:
```
quarkus.log.console.level=DEBUG
# up through 1.0.0.C2, quarkus/smallrye would just use the defaultValue for this
some.boolean.prop=
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
$ uname -a
Darwin ip-192-168-1-137.ec2.internal 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```
 - Output of `java -version`: 
```
$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.0.0.C2, 1.1.0.Final

**Additional context**
Might be expected behavior following https://github.com/smallrye/smallrye-config/pull/209

Repro project:  https://github.com/jordanglassman/quarkus-flyway-bug/tree/quarkus-config-prop-bug

**Comment by gsmet** [comment]
I think that is the intended behavior but /cc @dmlloyd to be sure.

**Comment by dmlloyd** [comment]
Yes, this is intended behavior.  Blanking a property explicitly sets it to an empty value, overriding any default or other value set on the property.  There is no mechanism for explicitly specifying a default value other than specifying that value directly.
