### ISSUE TITLE
Caching NONSTRICT_READ_WRITE fails during test

### ISSUE THREAD

**Issue by danielpetisme** [quarkusio/quarkus#6492]
**Describe the bug**
`@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
` on an entity works with `quarkus:dev` but not on tests

**Expected behavior**
When an entity is annoted `@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
` it should have the same behavior when we test or run the application. 

**Actual behavior**
The test fail with a cryptic error

**To Reproduce**
Here you have a complete repo ready to be forked

0. Setup a persistence and define some fake data in `import.sql`
```
INSERT INTO quarkus_user (id, login) VALUES (1, 'john');
```
1. Create an entity with `@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)`
```
@Entity
@Table(name = "quarkus_user")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class User extends PanacheEntity {

    @NotNull
    @Size(min = 1, max = 50)
    @Column(length = 50, unique = true, nullable = false)
    public String login;

}
```
2.  Verify `http://localhost:8080/accounts/{name}` works
```
$ curl -X GET http://0.0.0.0:8080/account/john
{"id":1,"login":"john"}
```
3.  Define a test reproducing the same behavior
```
 @Test
    public void testGetUserByLogin() {
        given()
                .header(HttpHeaders.ACCEPT, MediaType.APPLICATION_JSON)
                .when()
                .get("/account/john")
                .then()
                .statusCode(HttpStatus.SC_OK)
                .body("login", is("john"));
    }
```
4. Run the test `mvn test`
```
[INFO] Running org.acme.AccountResourceTest
Hibernate: 
    
    drop table quarkus_user if exists
Hibernate: 
    
    drop sequence if exists hibernate_sequence
Hibernate: create sequence hibernate_sequence start with 1 increment by 1
Hibernate: 
    
    create table quarkus_user (
       id bigint not null,
        login varchar(50) not null,
        primary key (id)
    )
Hibernate: 
    
    alter table quarkus_user 
       add constraint UK_qbltlo15hka6hj5jxdsrxehdj unique (login)
Hibernate: 
    INSERT INTO quarkus_user (id, login) VALUES (1, 'john')
2020-01-10 11:45:16,563 INFO  [io.quarkus] (main) Quarkus 1.1.1.Final started in 1.323s. Listening on: http://0.0.0.0:8081
2020-01-10 11:45:16,566 INFO  [io.quarkus] (main) Profile test activated. 
2020-01-10 11:45:16,566 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-h2, narayana-jta, resteasy, resteasy-jackson]
Hibernate: 
    select
        user0_.id as id1_0_,
        user0_.login as login2_0_ 
    from
        quarkus_user user0_ 
    where
        user0_.login=? limit ?
2020-01-10 11:45:17,355 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /account/john failed, error id: dc1b68ec-6246-4466-ab5e-6dbe56f4c628-1: org.jboss.resteasy.spi.UnhandledException: java.lang.AssertionError
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:120)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:85)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.AssertionError
        at org.infinispan.quarkus.hibernate.cache.NonStrictDataAccess.putFromLoad(NonStrictDataAccess.java:59)
        at org.infinispan.quarkus.hibernate.cache.AbstractDomainDataAccess.putFromLoad(AbstractDomainDataAccess.java:35)
        at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:280)
        at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:160)
        at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1179)
        at org.hibernate.loader.Loader.processResultSet(Loader.java:1028)
        at org.hibernate.loader.Loader.doQuery(Loader.java:964)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
        at org.hibernate.loader.Loader.doList(Loader.java:2815)
        at org.hibernate.loader.Loader.doList(Loader.java:2797)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2629)
        at org.hibernate.loader.Loader.list(Loader.java:2624)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1396)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1558)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1526)
        at org.hibernate.query.Query.getResultList(Query.java:165)
        at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.firstResult(PanacheQueryImpl.java:150)
        at org.acme.AccountResource.getOne(AccountResource.java:13)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
        at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:594)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:468)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:421)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:423)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:365)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
        ... 17 more

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.422 s <<< FAILURE! - in org.acme.AccountResourceTest
[ERROR] testGetUserWithRolesByLogin  Time elapsed: 0.854 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.

        at org.acme.AccountResourceTest.testGetUserWithRolesByLogin(AccountResourceTest.java:24)

2020-01-10 11:45:17,453 INFO  [io.quarkus] (main) Quarkus stopped in 0.026s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AccountResourceTest.testGetUserWithRolesByLogin:24 1 expectation failed.
Expected status code <200> but was <500>.

[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

5. Comment the `@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)` in the entity and re re-run the test and it should work now.

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script = import.sql
quarkus.datasource.driver = org.h2.Driver
quarkus.hibernate-orm.database.generation=drop-and-create

%dev.quarkus.datasource.url = jdbc:h2:mem:dev
%test.quarkus.datasource.url = jdbc:h2:mem:test

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
`Darwin Daniels-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
`
 - Output of `java -version`: 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
 - GraalVM version (if different from Java): Not applicable only Java mode
 - Quarkus version or git rev: `1.1.1.Final`

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
@danielpetisme could you prepare a reproducer (a simple Maven project woulr be perfect)? Better do that than describing each file. Thanks!

/cc @Sanne

**Comment by danielpetisme** [comment]
My bad I prepared it but forgot to paste it

https://github.com/danielpetisme/quarkus-caching-test-error

The listed files come from this repo

Le lun. 13 janv. 2020 à 11:01, Guillaume Smet <notifications@github.com> a
écrit :

**Comment by Sanne** [comment]
thanks @danielpetisme !

@galderz will you be able to have a look?

**Comment by galderz** [comment]
@Sanne Sure, looking into it.

**Comment by galderz** [comment]
The second-level cache implementation for nonstrict-read-write requires entry versioning. The error you're getting is because entities do not have versioning information.  With nonstrict-read-write caches are allowed to return stale values, so versions are required to figure out which entry is newer. You have two options to solve this:

* Stick to nonstrict-read-write and add versioning to your entities.
* Or switch to read-write.

**Comment by gsmet** [comment]
Shouldn't we throw an error at build time?

**Comment by danielpetisme** [comment]
@galderz could you point me some documentation please ? I'm not familiar with this versioning...
The only versioning info I have is `private static final long serialVersionUID = 1L;` for Serialization

**Comment by Sanne** [comment]
yes we should provide a better error. But also, we don't support caching of writeable entities: there's no way to keep these caches coherent across multiple nodes.

@danielpetisme could you explain why you're trying to change the caching access? I hope you've seen the warnings documented on https://quarkus.io/guides/hibernate-orm#limitations-of-caching

**Comment by danielpetisme** [comment]
To be franck I stupidly migrate a config from jhipster so I didn't
challenged the need right now.
I'm not an expert of caching so tel me know what would be the best
configuration please.

Daniel PETISME
+33 (0) 6 69 29 45 55
daniel.petisme@gmail.com

**Comment by danielpetisme** [comment]
For the record
https://github.com/jhipster/generator-jhipster/issues/9250

**Comment by Sanne** [comment]
Thanks @danielpetisme , I've commented on https://github.com/jhipster/generator-jhipster/issues/9250#issuecomment-574712451 so that people there can see this too.

Regarding the Quarkus/jhipster work, would it be possible to generate these only for immutable entities?

We only (exclusively) support `@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)` ; clearly this could evolve, but that's not planned yet so it could take a while.

**Comment by Sanne** [comment]
@yrodiere thanks yes Infinispan team might help but it's a "joined effort" as this isn't the traditional Infinispan 2LC implementation used e.g. in Wildfly, it's a new project we've adopted in hibernate.org : 
 - https://github.com/hibernate/quarkus-local-cache

**Comment by geoand** [comment]
Is this still an issue?
