### ISSUE TITLE
Error: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by fcracker79** [quarkusio/quarkus#6509]
**Describe the bug**
I managed to create a native AWS lambda with Quarkus, but when I attempt to interact with DynamoDB, I get the error: "the trustAnchors parameter must be non-empty".

I followed the instructions at [Quarkus - Using SSL With Native Executables](https://quarkus.io/guides/native-and-ssl), without any success.
This is the structure of my project:

```
$ unzip -t function.zip 
Archive:  function.zip
    testing: ssl/                     OK
    testing: ssl/libsunec.so          OK
    testing: ssl/cacerts              OK
    testing: bootstrap.bin            OK
    testing: bootstrap                OK
```
`ssl/libsunec.so` comes from the Docker image `quay.io/quarkus/ubi-quarkus-native-image:19.2.1`.
`bootstrap.bin` is the executable.
`ssl/cacerts` comes from my host JRE.
`bootstrap` is the following script:

```bash
#!/bin/sh
./bootstrap.bin -Djava.library.path=${LAMBDA_TASK_ROOT}/ssl -Djavax.net.ssl.trustStore=${LAMBDA_TASK_ROOT}/ssl/cacerts
```

**Expected behavior**
`com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.scan` invocation should work.

**Actual behavior**
```
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1189)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1135)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:3768)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:3737)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeScan(AmazonDynamoDBClient.java:2929)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.scan(AmazonDynamoDBClient.java:2897)
	at io.mirko.aws.DynamoDBFactory_ProducerMethod_createDynamoDB_4262ebacf51e52b8efab5d239ebd7de015aa8062_ClientProxy.scan(DynamoDBFactory_ProducerMethod_createDynamoDB_4262ebacf51e52b8efab5d239ebd7de015aa8062_ClientProxy.zig:828)
```

**To Reproduce**
1. Create a Quarkus lambda project
2. Include code to access DynamoDB in your entry point
3. Trigger the lambda (there are many other tricks, especially with reflection, to implement in order to have the lambda up-and-running) 

**Environment:**
 - Output of `uname -a` or `ver`: `Linux mypc-ThinkPad-T410 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

 - Output of `java -version`: 
```openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing)
```
 - GraalVM version:
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-jvmci-19.3-b05-LTS)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing)
``` 
 - Quarkus version or git rev: `1.1.0-Final`

**Comment by gsmet** [comment]
@fcracker79 hmmm, do you use the Amazon DynamoDB extension?

**Comment by fcracker79** [comment]
@gsmet thanks for your response. No, I do not use DynamoDB extension, I am just using the AWS SDK, as follows:

```
package io.mirko.aws;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;
import javax.inject.Named;

public class DynamoDBFactory {
    @Produces
    @ApplicationScoped
    @Named
    public AmazonDynamoDB createDynamoDB() {
        return AmazonDynamoDBClientBuilder.defaultClient();
    }
}

...

// Somewhere else in other classes
@Inject
AmazonDynamoDB dynamoDB;

```

**Comment by gsmet** [comment]
Could you try using the extension instead?

**Comment by fcracker79** [comment]
I tried the quickstart:

```bash
$ mvn io.quarkus:quarkus-maven-plugin:1.1.1.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=dynamodb-quickstart     -DclassName="org.acme.dynamodb.FruitResource"     -Dpath="/fruits"     -Dextensions="resteasy-jsonb,dynamodb"

$ mvn clean install -Pnative -Dnative-image.docker-build=true -Dquarkus.native.enable-jni=true
```

 and I got:

```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
```
In addition to that, I found out that the plugin uses a completely different API compared to the official AWS SDK, which is really annoying.

Finally, even in case of successful usage of the plugin, I would have the feeling that, whenever I have to interact via SSL that is not DynamoDB, I would get that error again (e.g. access to S3 or a third party HTTPS Url).

My next step is to check if my attempt to set the system properties for SSL did the trick, maybe my attempt to pass them as an argument does not work.

**Comment by fcracker79** [comment]
I have verified at runtime that the SSL system properties are correctly set.

I have also noticed that the error `WARNING: The sunec native library, required by the SunEC provider, could not be loaded` does non appear any more after adding `libsunec.so`.

I have tried setting the system properties `javax.net.ssl.trustAnchors` and `javax.net.ssl.trustStorePassword` in addition to `javax.net.ssl.trustStore` and `java.library.path`. I still have the error `java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`.

Here are my system properties:

```
java.vm.version=GraalVM 19.2.1 CE,
java.vm.vendor=Oracle Corporation,
java.vendor.url=https://www.graalvm.org/,
path.separator=:,
java.vm.name=Substrate VM,
javax.net.ssl.trustAnchors=/var/task/ssl/cacerts,
java.vm.specification.name=Java Virtual Machine Specification,
user.dir=/var/task,
java.endorsed.dirs=,
os.arch=amd64,
java.io.tmpdir=/var/tmp/,
org.graalvm.nativeimage.kind=executable,
line.separator=
,
java.vm.specification.vendor=Oracle Corporation,
java.util.logging.manager=org.jboss.logmanager.LogManager,
os.name=Linux,
sun.jnu.encoding=ANSI_X3.4-1968,
java.library.path=/var/task/ssl,
javax.net.ssl.trustStore=/var/task/ssl/cacerts,
java.specification.name=Java Platform API Specification,
java.class.version=52.0,
java.net.preferIPv4Stack=true,
os.version=4.14.138-99.102.amzn2.x86_64,
user.home=/home/sbx_user1051,
file.encoding=ANSI_X3.4-1968,
java.specification.version=1.8,
user.name=sbx_user1051,
java.class.path=,
java.vm.specification.version=1.8,
java.specification.vendor=Oracle Corporation,
org.graalvm.nativeimage.imagecode=runtime,
java.version=1.8.0_232,
java.ext.dirs=,
java.vendor=Oracle Corporation,
file.separator=/,
javax.net.ssl.trustStorePassword=changeit}
```

**Comment by fcracker79** [comment]
Apologies for the mess, I accidentally included a symlink of `cacerts` in `function.zip`.
