### ISSUE TITLE
Server Sent Events components aren't being resolved

### ISSUE THREAD

**Issue by k0l0ssus** [quarkusio/quarkus#6515]
**The code kit**: [quarkus-getting-started.zip](https://github.com/quarkusio/quarkus/files/4053740/quarkus-getting-started.zip)

**Describe the bug**
None of the componentry necessary for SSE per the JAX-RS standards are being CDI-resolved in a vanilla bootstrapped Quarkus project
**Expected behavior**
I should be able to successfully startup and inject (with `@Context`) `javax.ws.rs.sse.SseBroadcaster`, `javax.ws.rs.sse.Sse` and `javax.ws.rs.sse.SseEventSink`. The application should start up successfully and service requests, given the following resource definition:

```import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.UriInfo;
import javax.ws.rs.sse.Sse;
import javax.ws.rs.sse.SseBroadcaster;

@Path("/hello")
public class GreetingResource {

    Sse sse;
    SseBroadcaster broadcaster;

    public GreetingResource(@Context Sse sse){
        this.sse = sse;
		this.broadcaster = sse.newBroadcaster();
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(@Context UriInfo uriInfo ) {
        return "hello";
    }
}
```

**Actual behavior**
Arc fails to resolve the classes for injection:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.1.1.Final:build (default) on project quarkus-getting-started: Failed to build a runnable JAR: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.ws.rs.sse.Sse and qualifiers [@Default]
[ERROR]         - java member: com.apress.samples.quarkus.GreetingResource#<init>()
[ERROR]         - declared on CLASS bean [types=[com.apress.samples.quarkus.GreetingResource], qualifiers=[@Default, @Any], target=com.apress.samples.quarkus.GreetingResource]
[ERROR]         at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:865)
[ERROR]         at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:223)
[ERROR]         at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:108)
[ERROR]         at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:265)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
[ERROR]         at java.lang.Thread.run(Thread.java:745)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type javax.ws.rs.sse.Sse and qualifiers [@Default]
[ERROR]         - java member: com.apress.samples.quarkus.GreetingResource#<init>()
[ERROR]         - declared on CLASS bean [types=[com.apress.samples.quarkus.GreetingResource], qualifiers=[@Default, @Any], target=com.apress.samples.quarkus.GreetingResource]
[ERROR]         at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
[ERROR]         at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:416)
[ERROR]         at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:215)
[ERROR]         ... 14 more
[ERROR] -> [Help 1]
```

**To Reproduce**
1. Bootstrap a project from any source (I've verified this from the web starter, Intellij and VSCode plugins, and `quarkus:create`
2. Add the injections to the generated resource class
3. Neither standard `mvn` goals nor `quarkus:dev` are able to start the app successfully.

**Environment (please complete the following information):**
 - Output of `java -version`: 

 ```java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

- Quarkus version or git rev: 1.1.1.Final

**Additional context**

POM dependencies:
```
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
```
I tried with standard Glassfish dependencies/BOM (and specifically the `jersey-media-sse` dependency) as a hail Mary but no dice. Other `@Context`-injectable components work (that's why I left the `@UriInfo` injection in there). I'm happy to provide more context if you need any. I'm trying out Quarkus for a book on the framework, for whatever that's worth. Thank you.

**Comment by stuartwdouglas** [comment]
I think this is part of a more general issue we have with @Context injection in constructors. At the moment ArC does not know about @Context as it is a JAX-RS annotation. Does it work if you inject directly into the field or into the JAX-RS method?

**Comment by k0l0ssus** [comment]
@stuartwdouglas thanks for responding. I haven't been able to inject SSE into a field (doesn't break startup, but the variable is null) nor a resource method (breaks startup). I was able to inject most of the other things that `@Context` provides (`UriInfo` and others like I said in the issue body). I can also confirm that `@Context` is being resolved by Arc - removing the annotation or replacing it with `@Inject` results in a bunch of NPEs

**Comment by gpor0** [comment]
+1

It would be useful if we can Inject SSE (SseEventSink) as a bean property and as a method parameter.

**Comment by stuartwdouglas** [comment]
I wrote a test for this and it passed for me locally: https://github.com/quarkusio/quarkus/pull/9037

Can you provide a reproducer?

**Comment by k0l0ssus** [comment]
Absolutely @stuartwdouglas ! Thanks for sorting this out!

**Comment by k0l0ssus** [comment]
@stuartwdouglas just so I understand, v1.5 has your fix? Because I used the reproducer in this issue and bumped Quarkus version up, same result.

**Comment by stuartwdouglas** [comment]
There was no fix, I wrote a test that passed so I could not reproduce the issue.

**Comment by k0l0ssus** [comment]
Oh. There's a reproducer attached to this issue already @stuartwdouglas

**Comment by fercomunello** [comment]
@k0l0ssus It's working normally here using the non-reactive rest-easy (JAX-RS).


```java

import javax.inject.Singleton;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.sse.OutboundSseEvent;
import javax.ws.rs.sse.Sse;
import javax.ws.rs.sse.SseBroadcaster;
import javax.ws.rs.sse.SseEventSink;
import java.util.concurrent.atomic.AtomicInteger;

@Path("/sse")
@Singleton
public class ServerSentEventResource {

    @Context
    private Sse sse;

    private volatile SseBroadcaster sseBroadcaster;

    private AtomicInteger randomNumber = new AtomicInteger();

    @GET
    @Path("/register")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public void registerEvent(@Context SseEventSink sseEventSink) {
        sseEventSink.send(createTestEvent(false));

        if (this.sseBroadcaster == null) {
            this.sseBroadcaster = this.sse.newBroadcaster();
        }

        this.sseBroadcaster.register(sseEventSink);
    }

    @GET
    @Path("/broadcast")
    @Produces(MediaType.TEXT_PLAIN)
    public Response broadcastEvent() {
        if (this.sseBroadcaster != null) {
            this.sseBroadcaster.broadcast(createTestEvent(true));

            return Response.ok().build();
        }

        return Response.status(Response.Status.BAD_REQUEST).build();
    }

    private OutboundSseEvent createTestEvent(boolean generateNumber) {
        if (generateNumber) {
            this.randomNumber = new AtomicInteger((int) (Math.random() * 1000 + 1));
        }

        return this.sse.newEvent("test", this.randomNumber.toString());
    }

}
```

**Comment by stuartwdouglas** [comment]
So the issue here was the Resteasy does not support constructor injection for @Context, you need to use field injection instead. 

Resteasy reactive does support this.
