### ISSUE TITLE
[Native] Can't create instance of a class: class java.util.Properties, No default constructor found.

### ISSUE THREAD

**Issue by fmhwong** [quarkusio/quarkus#6537]
**Describe the bug**
When running the native image, the following code throws `javax.ws.rs.ProcessingException: RESTEASY008200: JSON Binding deserialization error: javax.json.bind.JsonbException: Can't create instance of a class: class java.util.Properties, No default constructor found.`

Code snippet
```
	        try {
	            Response response = builder.get();
	            if (response.getStatus() == Status.OK.getStatusCode()) {
	                return response.readEntity(Properties.class);
	            } else {
	                System.out.println("Response Status is not OK.");
	            }
	        } catch (RuntimeException e) {
	            System.out.println("Runtime exception: " + e.getMessage());
	            e.printStackTrace();
	        } catch (Exception e) {
	            System.out.println("Exception thrown while invoking the request.");
	            e.printStackTrace();
	        }
```

**Expected behavior**
The code run without throwing exception.  It works fine in dev mode and the jar file.

**Actual behavior**
The following exception was logged when running with the native binary.

```
Runtime exception: RESTEASY008200: JSON Binding deserialization error: javax.json.bind.JsonbException: Can't create instance of a class: class java.util.Properties, No default constructor found.
javax.ws.rs.ProcessingException: RESTEASY008200: JSON Binding deserialization error: javax.json.bind.JsonbException: Can't create instance of a class: class java.util.Properties, No default constructor found.
	at org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider.readFrom(JsonBindingProvider.java:78)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:102)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:81)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:226)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:88)
	at org.jboss.resteasy.specimpl.AbstractBuiltResponse.readEntity(AbstractBuiltResponse.java:262)
	at io.openliberty.guides.inventory.client.SystemClient.getPropertiesHelper(SystemClient.java:101)
	at io.openliberty.guides.inventory.client.SystemClient.getProperties(SystemClient.java:53)
	at io.openliberty.guides.inventory.InventoryManager.get(InventoryManager.java:42)
	at io.openliberty.guides.inventory.InventoryManager_ClientProxy.get(InventoryManager_ClientProxy.zig:148)
	at io.openliberty.guides.inventory.InventoryResource.getPropertiesForHost(InventoryResource.java:39)
	at io.openliberty.guides.inventory.InventoryResource_ClientProxy.getPropertiesForHost(InventoryResource_ClientProxy.zig:56)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:110)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:594)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:468)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:421)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:423)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:365)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:120)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:85)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: javax.json.bind.JsonbException: Can't create instance of a class: class java.util.Properties, No default constructor found.
	at org.eclipse.yasson.internal.ReflectionUtils.lambda$getDefaultConstructor$1(ReflectionUtils.java:228)
	at java.security.AccessController.doPrivileged(AccessController.java:69)
	at org.eclipse.yasson.internal.ReflectionUtils.getDefaultConstructor(ReflectionUtils.java:219)
	at org.eclipse.yasson.internal.InstanceCreator.createInstance(InstanceCreator.java:73)
	at org.eclipse.yasson.internal.serializer.MapDeserializer.createInstance(MapDeserializer.java:66)
	at org.eclipse.yasson.internal.serializer.MapDeserializer.<init>(MapDeserializer.java:59)
	at org.eclipse.yasson.internal.serializer.DeserializerBuilder.build(DeserializerBuilder.java:155)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:68)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:54)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:53)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:93)
	at org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider.readFrom(JsonBindingProvider.java:70)
	... 50 more
Caused by: java.lang.NoSuchMethodException: java.util.Properties.<init>
	at java.lang.Class.getConstructor0(DynamicHub.java:3082)
	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
	at org.eclipse.yasson.internal.ReflectionUtils.lambda$getDefaultConstructor$1(ReflectionUtils.java:221)
	... 61 more

```

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin Kernel Version 19.2.0`
 - Output of `java -version`: 
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
 - GraalVM version (if different from Java): `19.2.1`
 - Quarkus version or git rev: `master`

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
This is interesting because we need a way to register classes for reflection whose source can't be changed and therefore the `@RegisterForReflection` annotation cannot be added.
So some kind of configuration via `application.properties` would make sense

@dmlloyd @gsmet @FroMage @stuartwdouglas have we perhaps discussed this one before?

**Comment by nimo23** [comment]
For native mode, you must register the class for reflection. Normally, it can be done by `@RegisterForReflection` on class level. However, in your case it is `java.util.Properties`, which could be added to `reflection-config.json`. However, maybe classes coming from jdk should be registered for reflection by default.

**Comment by geoand** [comment]
> For native mode, you must register the class for reflection. Normally, it can be done by `@RegisterForReflection` on class level. However, in your case it is `java.util.Properties`, which could be added to `reflection-config.json`. However, maybe classes coming from jdk should be registered for reflection by default.

In this case can't know the type anyway because `Response` does not have a generic type.

**Comment by geoand** [comment]
@fmhwong as a workaround you can just return `Properties` instead of `Response`

**Comment by stuartwdouglas** [comment]
You can use io.quarkus.runtime.annotations.RegisterForReflection#targets to register classes you cannot change.

**Comment by geoand** [comment]
Aha! I never saw that one, thanks

**Comment by geoand** [comment]
So I I'll go ahead and close this since we already have a mechanism for dealing with such cases.

**Comment by fmhwong** [comment]
Okay, I have created `reflection-config.json`

```
[
  {
    "name" : "java.util.Properties",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  }
]
```
and the native binary doesn't throw the exception anymore.  Thanks!

**Comment by nimo23** [comment]
>It would be nice if classes from JDK are added automatically for reflection.

That would be nice.

However, maybe these would lead to bigger size for the native executables?


Btw, you only need the constructor for reflection. Maybe this is sufficient?

```
[
  {
    "name" : "java.util.Properties",
    "allDeclaredConstructors" : false,
    "allPublicConstructors" : true, // only this is needed?
    "allDeclaredMethods" : false,
    "allPublicMethods" : false,
    "allDeclaredFields" : false,
    "allPublicFields" : false
  }
]
```

**Comment by geoand** [comment]
That should probably get it working.

And yes, we don't add things automatically for reflection because (among other things), the more you add, the larger the image size

**Comment by nimo23** [comment]
>the more you add, the larger the image size

Would it be possible for quarkus to scan only those classes needed for reflection on compile? For example: If quarkus analyzes/scans the application source code on compile and sees that the constructor for `java.util.Properties` is needed then it could automatically register this class for reflection on compile.

**Comment by stuartwdouglas** [comment]
If you were returning the Properties object directly from the REST endpoint then we could. Unfortunately we can't really do that for programatically build responses.
