### ISSUE TITLE
:remote-dev mode stopped working with 1.1.0.Final

### ISSUE THREAD

**Issue by wzzrd** [quarkusio/quarkus#6550]
**Describe the bug**
Since 1.1.0.Final, :remote-dev seems to have stopped working (unless I'm missing some additional steps that have to be taken with 1.1.0.Final). Connection from the local to the remote side times out with: 
```
Exception in thread "Websocket ping timer" java.lang.NullPointerException
	at io.quarkus.remotedev.AgentRunner$2.run(AgentRunner.java:62)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```
Command on the "local" side:
```
./mvnw  quarkus:remote-dev -Dquarkus.live-reload.url=http://127.0.0.1:8080 -Dquarkus.live-reload.password=somepassword
```
Command on the "remote" side:
```
./mvnw compile quarkus:dev -Dquarkus.live-reload.password=somepassword 
```
(I have some more -D options set, but I left those out for the sake of conciseness.)

When starting with 1.0.1.Final, the console shows the following when starting:
```
Listening for transport dt_socket at address: 5005
2020-01-14 14:47:01,493 INFO  [io.qua.und.web.dep.WebsocketHotReloadSetup] (main) Using websocket based hot deployment
2020-01-14 14:47:01,519 INFO  [io.und.web.jsr] (main) UT026003: Adding annotated server endpoint class io.quarkus.undertow.websockets.deployment.HotReplacementWebsocketEndpoint for path /quarkus/live-reload
2020-01-14 14:47:04,162 INFO  [io.quarkus] (main) Quarkus 1.0.1.Final started in 2.863s. Listening on: http://0.0.0.0:8080
2020-01-14 14:47:04,162 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-01-14 14:47:04,162 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, narayana-jta, resteasy, resteasy-jackson, servlet, undertow-websockets]
```

When starting with 1.1.0.Final, the console shows
```
Listening for transport dt_socket at address: 5005
2020-01-14 14:48:08,959 INFO  [io.quarkus] (main) Quarkus 1.1.0.Final started in 2.980s. Listening on: http://0.0.0.0:8080
2020-01-14 14:48:08,962 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-01-14 14:48:08,962 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, narayana-jta, resteasy, resteasy-jackson, servlet, undertow-websockets]

```

Outside of version numbers, poms are exactly the same. _Notice that the websockets message is missing for version 1.1.0.Final._

**Expected behavior**
"Local" side of development setup shows "Connected to remote server" after a few seconds.

**Actual behavior**
"Local" side of development setup shows 
```
Exception in thread "Websocket ping timer" java.lang.NullPointerException
	at io.quarkus.remotedev.AgentRunner$2.run(AgentRunner.java:62)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```
Connection is never made

**To Reproduce**
1. create pom.xml with Quarkus 1.1.0.Final
2. add undertow-websockets
3. try and use remote-dev

**Configuration**
For completeness sake, but don't think this helps much?
```properties
# Add your application.properties here, if applicable.
# Configuration file

# configure your datasource
quarkus.datasource.url = jdbc:postgresql://localhost:5432/mydatabase
quarkus.datasource.driver = org.postgresql.Driver
quarkus.datasource.username = sarah
quarkus.datasource.password = connor
quarkus.hibernate-orm.database.generation=drop-and-create
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux taishogun.lan 5.4.8-200.fc31.x86_64 #1 SMP Mon Jan 6 16:44:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 1.1.0.Final

**Additional context**
Switching the pom.xml to 1.0.1.Final makes remote-dev work again.

Hope I provided enough info :)

**Comment by geoand** [comment]
Thanks for reporting, I'll check it out

**Comment by geoand** [comment]
Two things so far:

1) I was able to reproduce your problem
2) The problem goes away if you add something like 

```
quarkus.live-reload.password=somepassword
quarkus.live-reload.url=http://localhost:8080/
``` 

Now I will look at why system property doesn't work

to `application.properties`
