### ISSUE TITLE
QuarkusDev does not start with Kotlin subprojects

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#6561]
To see the full disucssion on this subject, please refer to this chat: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20Dev.20not.20working.20with.20Kotlin.20and.20Subprojects

**Describe the bug**
I have a Quarkus gradle project with two modules `project-a` and `project-a-models`. `project-a` is a quarkus project having a dependency on the plain Kotlin `project-a-models` module.
I can compile this configuration (see sample project linked below). However, when I run `gradlew quarkusDev`, it fails searching a Java path. This is error fixed with the PR #6551. However, when I now run `gradlew quarkusDev`, the server never starts up but hangs after starting the debugger port. 

I ran jstack on gradlew: https://gist.github.com/andreas-eberle/28c3d1438292ab636f6c374988f95f22

And jstack on the built and executed project-a-1.0.0-SNAPSHOT-dev.jar: https://gist.github.com/andreas-eberle/7393cf44da1952d622c0d6383ea09a65

The last part of the output of `gradlew quarkusDev --stacktrace --debug` is here: https://gist.github.com/andreas-eberle/6c074e8f10c2a7514b323430b9f504ed

**Expected behavior**
Server starts up without an exception.

**Actual behavior**
Dev server hangs with PR #6551 or crashes with quarkus 1.1.1-Final

**To Reproduce**
1. Download the reproducer project [quarkus-experiments.zip](https://github.com/quarkusio/quarkus/files/4064951/quarkus-experiments.zip)
2. Install quarkus locally from PR https://github.com/quarkusio/quarkus/pull/6551/files
2. run `./gradlew :project-a:quarkusDev --stacktrace --info`
3. the server won't start up

**Platform**
- Windows 10 x64
- Oracle JDK 64bit Version 1.8.0_231

**Comment by andreas-eberle** [comment]
I tried the same setup with a Java gradle Quarkus project and have the same issues. After simply importing another plain Java module into my Java Quarkus project by adding `implementation project(':plain-java-project')` to the Quarkus project's dependencies, I can run `gradlew assemble`, `gradlew :quarkus-project:buildNative` and `gradlew :quarkus-project:quarkusBuild` without an issue.  However, running `gradlew :quarkus-project:quarkusDev` results in the follwing error:

```
gradlew :quarkus-project:quarkusDev
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: C:\development\quarkus-test\plain-java-project\build\classes\java\main
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:71)
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: C:\development\quarkus-test\quarkus-project\build\classes\java\main
        at io.quarkus.dev.RuntimeUpdatesProcessor.checkForClassFilesChangesInModule(RuntimeUpdatesProcessor.java:254)
        at io.quarkus.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:199)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:92)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: java.nio.file.NoSuchFileException: C:\development\quarkus-test\plain-java-project\build\classes\java\main
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72)
        at java.nio.file.Files.walk(Files.java:3574)
        at java.nio.file.Files.walk(Files.java:3625)
        at io.quarkus.dev.RuntimeUpdatesProcessor.checkForClassFilesChangesInModule(RuntimeUpdatesProcessor.java:219)
        ... 3 more
```

I think this is a major problem, since it makes development very unconvenient when you import another module, which is a very common use case.
