### ISSUE TITLE
Sometimes getting an NPE when using Startup event and vertx

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#6612]
**Describe the bug**
Here is the exception I am getting:
```
Andy Damevin:
2020-01-17 15:47:03,534 ERROR [io.sma.rea.mes.ext.MediatorManager] (main) Unable to initialize mediator: demo.gos.hero.Hero#game: java.lang.RuntimeException: Error injecting io.vertx.core.Vertx demo.gos.hero.Hero.vertx
        at demo.gos.hero.Hero_Bean.create(Hero_Bean.zig:380)
        at demo.gos.hero.Hero_Bean.create(Hero_Bean.zig:1228)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at demo.gos.hero.Hero_Bean.get(Hero_Bean.zig:1212)
        at demo.gos.hero.Hero_Bean.get(Hero_Bean.zig:56)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:355)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:367)
        at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:60)
        at io.smallrye.reactive.messaging.extension.MediatorManager.lambda$initializeAndRun$4(MediatorManager.java:143)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:136)
        at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:100)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:51)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent40.deploy_0(LifecycleEventsBuildStep$startupEvent40.zig:58)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent40.deploy(LifecycleEventsBuildStep$startupEvent40.zig:77)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:124)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runtime.Application.run(Application.java:210)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: java.lang.NullPointerException
        at io.quarkus.vertx.core.runtime.VertxCoreProducer.vertx(VertxCoreProducer.java:26)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:258)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:69)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:128)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:84)
        at demo.gos.hero.Hero_Bean.create(Hero_Bean.zig:363)
        ... 27 more
```

@cescoffier has made a reproducer.

**Comment by cescoffier** [comment]
@mkouba I was able to reproduce it with:

```
package io.quarkus.vertx.core.deployment;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.concurrent.atomic.AtomicReference;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;
import javax.inject.Inject;

import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.JavaArchive;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import io.quarkus.arc.Arc;
import io.quarkus.runtime.StartupEvent;
import io.quarkus.test.QuarkusUnitTest;
import io.vertx.core.Vertx;

public class VertxInjectionTest {

    @RegisterExtension
    static final QuarkusUnitTest config = new QuarkusUnitTest()
            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
                    .addClasses(MyBean.class));

    @RepeatedTest(1000)
    public void test() {
        MyBean bean = Arc.container().instance(MyBean.class).get();
        assertThat(bean.get()).isNotNull();
    }

    @ApplicationScoped
    public static class MyBean extends AtomicReference<Vertx> {

        @Inject
        Vertx vertx;

        public void init(@Observes StartupEvent ev) {
            assertThat(vertx).isNotNull();
            set(vertx);
        }
    }
}
```

**Comment by svilenvul** [comment]
I am getting similar exception in version 1.2.0.Final 

The code that I am using is:

```
@ApplicationScoped
public class Application {

	@Inject
	Vertx vertx;
	Router router;

	void init(@Observes Router router) {
		this.router = router;
	}
	
	void onStart(@Observes StartupEvent ev) throws MissedConfigurationException {
		logger.debug("Application {} is starting ...",  SERVICE_NAME);
		...
		
	}

	void onStop(@Observes ShutdownEvent ev) {
		logger.debug("Application {} is stopping ...",  SERVICE_NAME);
	}

}
```

and the stacktrace is:

```
2020-01-24 12:25:52,307 ERROR [io.qua.application] (main) Failed to start application: java.lang.RuntimeException: Error injecting io.vertx.core.Vertx com.example.Application.vertx
        at com.example.Application_Bean.create(Application_Bean.zig:234)
        at com.example.Application_Bean.create(Application_Bean.zig:257)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at com.example.Application_ClientProxy.arc$delegate(Application_ClientProxy.zig:81)
        at com.example.Application_ClientProxy.arc_contextualInstance(Application_ClientProxy.zig:176)
        at com.example.Application_Observer_init_4919b00b6fde9fec4bbb79136e5247a43318336f.notify(Application_Observer_init_4919b00b6fde9fec4bbb79136e5247a43318336f.zig:86)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.finalizeRouter(VertxHttpRecorder.java:194)
        at io.quarkus.deployment.steps.VertxHttpProcessor$finalizeRouter20.deploy_0(VertxHttpProcessor$finalizeRouter20.zig:169)
        at io.quarkus.deployment.steps.VertxHttpProcessor$finalizeRouter20.deploy(VertxHttpProcessor$finalizeRouter20.zig:237)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:140)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:167)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: java.lang.NullPointerException
        at io.quarkus.vertx.core.runtime.VertxCoreProducer.vertx(VertxCoreProducer.java:26)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:258)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:69)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:128)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:84)
        at com.example.Application_Bean.create(Application_Bean.zig:217)
        ... 21 more

2020-01-24 12:25:52,345 ERROR [io.qua.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:194)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:167)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: java.lang.RuntimeException: Error injecting io.vertx.core.Vertx com.example.Application.vertx
        at com.example.Application_Bean.create(Application_Bean.zig:234)
        at com.example.Application_Bean.create(Application_Bean.zig:257)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at com.example.Application_ClientProxy.arc$delegate(Application_ClientProxy.zig:81)
        at com.example.Application_ClientProxy.arc_contextualInstance(Application_ClientProxy.zig:176)
        at com.example.Application_Observer_init_4919b00b6fde9fec4bbb79136e5247a43318336f.notify(Application_Observer_init_4919b00b6fde9fec4bbb79136e5247a43318336f.zig:86)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.finalizeRouter(VertxHttpRecorder.java:194)
        at io.quarkus.deployment.steps.VertxHttpProcessor$finalizeRouter20.deploy_0(VertxHttpProcessor$finalizeRouter20.zig:169)
        at io.quarkus.deployment.steps.VertxHttpProcessor$finalizeRouter20.deploy(VertxHttpProcessor$finalizeRouter20.zig:237)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:140)
        ... 5 more
Caused by: java.lang.NullPointerException
        at io.quarkus.vertx.core.runtime.VertxCoreProducer.vertx(VertxCoreProducer.java:26)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:258)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:69)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:128)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:84)
        at com.example.Application_Bean.create(Application_Bean.zig:217)
        ... 21 more3_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:128)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:84)
        at com.homeix.c8.ms.adminix.app.AdminixApplication_Bean.create(AdminixApplication_Bean.zig:217)
        ... 21 more
```

I have the feeling that there is a race condition between the registration of this bean and the https://github.com/quarkusio/quarkus/blob/47e5552eb7b914bb394ee11b700bc8ee54636660/extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java#L56 since both are with the same scope. 

Or am I doing something wrong?

**Comment by svilenvul** [comment]
@gastaldi , can we reopen this issue or I should create new one?

**Comment by mkouba** [comment]
Pls create a new one. I think that the problem is that `init(@Observes Router router)` is probably called before the `VertxCoreProducer` is initialized.

**Comment by svilenvul** [comment]
okay I will do so
