### ISSUE TITLE
Kotlin Unit Tests Fail with CDI Issues on Second Run in Intellij 

### ISSUE THREAD

**Issue by sherl0cks** [quarkusio/quarkus#6618]
**Describe the bug**
I have some test made with @QuarkusTest and CDI. After Intellij builds the project, these tests work fine on the first run. If I rerun these tests, even without code changes, they fail. Everything works normal during maven builds.

If I run a rebuild in Intellij, the test works again, but only for a single execution.

I have the `all-open` plugin set for `io.quarkus.test.junit.QuarkusTest` per the Kotlin Guide.

**Expected behavior**
Tests can be re run without issues.

**Actual behavior**
See below stack trace

```
Jan 17, 2020 6:41:06 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.0.0.Final



org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [com.sunrun.GreetingResourceTest]: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.sunrun.SiteAssetServiceTestDriver and qualifiers [@Default]
	- java member: com.sunrun.FunctionalTest#siteAssetServiceTestDriver
	- declared on CLASS bean [types=[java.lang.Object, com.sunrun.FunctionalTest], qualifiers=[@Default, @Any], target=com.sunrun.FunctionalTest]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:865)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:223)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:108)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:265)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.sunrun.SiteAssetServiceTestDriver and qualifiers [@Default]
	- java member: com.sunrun.FunctionalTest#siteAssetServiceTestDriver
	- declared on CLASS bean [types=[java.lang.Object, com.sunrun.FunctionalTest], qualifiers=[@Default, @Any], target=com.sunrun.FunctionalTest]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:416)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:215)
	... 14 more


	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:300)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:275)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:77)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:258)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:252)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:251)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:29)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:106)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:105)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.sunrun.SiteAssetServiceTestDriver and qualifiers [@Default]
	- java member: com.sunrun.FunctionalTest#siteAssetServiceTestDriver
	- declared on CLASS bean [types=[java.lang.Object, com.sunrun.FunctionalTest], qualifiers=[@Default, @Any], target=com.sunrun.FunctionalTest]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:865)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:223)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:108)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:265)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.sunrun.SiteAssetServiceTestDriver and qualifiers [@Default]
	- java member: com.sunrun.FunctionalTest#siteAssetServiceTestDriver
	- declared on CLASS bean [types=[java.lang.Object, com.sunrun.FunctionalTest], qualifiers=[@Default, @Any], target=com.sunrun.FunctionalTest]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:416)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:215)
	... 14 more

	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:181)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:249)
	at io.quarkus.test.junit.QuarkusTestExtension.createTestInstance(QuarkusTestExtension.java:394)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:285)
	... 47 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.sunrun.SiteAssetServiceTestDriver and qualifiers [@Default]
	- java member: com.sunrun.FunctionalTest#siteAssetServiceTestDriver
	- declared on CLASS bean [types=[java.lang.Object, com.sunrun.FunctionalTest], qualifiers=[@Default, @Any], target=com.sunrun.FunctionalTest]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:865)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:223)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:108)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:265)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.sunrun.SiteAssetServiceTestDriver and qualifiers [@Default]
	- java member: com.sunrun.FunctionalTest#siteAssetServiceTestDriver
	- declared on CLASS bean [types=[java.lang.Object, com.sunrun.FunctionalTest], qualifiers=[@Default, @Any], target=com.sunrun.FunctionalTest]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:416)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:215)
	... 14 more

	at io.quarkus.builder.Execution.run(Execution.java:108)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:121)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:128)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:114)
	... 50 more
Caused by: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.sunrun.SiteAssetServiceTestDriver and qualifiers [@Default]
	- java member: com.sunrun.FunctionalTest#siteAssetServiceTestDriver
	- declared on CLASS bean [types=[java.lang.Object, com.sunrun.FunctionalTest], qualifiers=[@Default, @Any], target=com.sunrun.FunctionalTest]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:865)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:223)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:108)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:265)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.sunrun.SiteAssetServiceTestDriver and qualifiers [@Default]
	- java member: com.sunrun.FunctionalTest#siteAssetServiceTestDriver
	- declared on CLASS bean [types=[java.lang.Object, com.sunrun.FunctionalTest], qualifiers=[@Default, @Any], target=com.sunrun.FunctionalTest]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:416)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:215)
	... 14 more

```
**To Reproduce**
1. Build Project
2. Run Test
3. Rerun test

**Configuration**
all-open configured and working (IDE validated) for QuarkusTest classes

**Environment (please complete the following information):**
 - Darwin sunrun.lan 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64 
 - Output of `java -version`: Graal 19.2.1
 - GraalVM version (if different from Java): Graal 19.2.1
 - Quarkus version or git rev: 1.1.1

**Comment by stuartwdouglas** [comment]
Any chance you could test with https://github.com/quarkusio/quarkus/pull/6411 and see if this resolves it?

**Comment by sherl0cks** [comment]
Sure, but it’s unclear to me exactly how to do that given the PR is not
merged and that seems like a substantial change. Can you provide a few
simple steps for me to run the test?

**Comment by sherl0cks** [comment]
FYI - moving the CDI config of the bean to `src/main/kotlin` from `src/test/kotlin` has temporarily solved the problem.

**Comment by stuartwdouglas** [comment]
What do you mean by CDI config?

**Comment by sherl0cks** [comment]
I have an `@ApplicationScoped` bean that has a bunch of CDI producers in it, which I am referring to collectively as my CdiConfig.

**Comment by sherl0cks** [comment]
@stuartwdouglas bump. I'm confirmed that this issue remains, and a workaround is to have the test bean with CDI annotations in `src/main` instead `src/text`. What can I do to test the change you have proposed on classloading?

**Comment by stuartwdouglas** [comment]
Change the Quarkus version to 999-SNAPSHOT. If you are using the quarkus-universe-bom you also need to change it to quarkus-bom

**Comment by sherl0cks** [comment]
I had some issues resolving the right libs and could not build. I'm not able to provide an update on this, as I've changed my config and no longer have a reproducer.

**Comment by sherl0cks** [comment]
@stuartwdouglas finally got around to upgrading my quarkus release. We are now on 1.3.2 and this issue appears to be resolved.
