### ISSUE TITLE
Vladmihalcea Hibernate Types not working on Panache Entities

### ISSUE THREAD

**Issue by marceloverdijk** [quarkusio/quarkus#6625]
It seems `com.vladmihalcea:hibernate-types-52` are not working together with Panache entities, e.g.:

```
@Entity
@TypeDefs({
        @TypeDef(name = "list-array", typeClass = ListArrayType.class)
})
public class Project extends PanacheEntityBase {

    @Type(type = "list-array")
    public List<String> previousNames = new ArrayList<>();

    ..
}
```

This gives an error:

```
Caused by: java.lang.ClassNotFoundException: com.demo.Project
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at com.vladmihalcea.hibernate.type.util.ReflectionUtils.getClass(ReflectionUtils.java:433)
        ... 52 more
```

`com.vladmihalcea:hibernate-types-52` is doing a [`Class.forName(String)`](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/util/ReflectionUtils.java#L433) like `Class.forName("com.demo.Project")` which gives the `com.vladmihalcea:hibernate-types-52`.

Could this be related to Quarkus class loader or enhancing of entities?

**Comment by nimo23** [comment]
You must **register** hibernate-types-52 **for reflection**.

Put this into your `application.properties`:

```
quarkus.index-dependency.vladmihalcea.group-id = com.vladmihalcea
quarkus.index-dependency.vladmihalcea.artifact-id = hibernate-types-52
```

**Comment by marceloverdijk** [comment]
I tried that with:

```
diff --git a/src/main/resources/application.properties b/src/main/resources/application.properties
index b2717aa..7edac2c 100644
--- a/src/main/resources/application.properties
+++ b/src/main/resources/application.properties
@@ -32,6 +32,8 @@ 
 quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQL95Dialect
 quarkus.http.cors=true
+quarkus.index-dependency.vladmihalcea.group-id=com.vladmihalcea
+quarkus.index-dependency.vladmihalcea.artifact-id=hibernate-types-52
 quarkus.log.level=INFO
 quarkus.native.additional-build-args=-H:ResourceConfigurationFiles=resources-config.json
```

bit it still gives the `Caused by: java.lang.ClassNotFoundException: com.demo.Project` unfortunately.

If needed I can provide a sample application?

**Comment by nimo23** [comment]
Actually, it is a mess in quarkus to look why or if a typical java library which runs in any other **java ecosystems** also runs in the **quarkus ecosystem**. It is not easy to see if a library (not typically seen as framework) needs a quarkus extension or not. 

Another implicit danger/pitfall of using quarkus with any other library is that errors due to incompability between quarkus and the 3rd party lib/framework can also occur while running - that means, it could be that runtime errors (due to incompabilties) happen at any time in a quarkus app and not only on compile. Am I right?

**Comment by nimo23** [comment]
@gsmet Can it be that a **3rd party lib or framework** which works nice in _java ecosystem_ throws errors in quarkus **while running** (due to incompabilties), for example, when a 3rd party method invokes any method/class which does not complies with the quarkus requirements (not only because it uses internally reflections)? 

**How one should know beforehand if such libs/frameworks are fully supported (for GraalVM and HotSpot) in quarkus without needing an extension?** 

The user of a 3rd party lib normally does not know about its implementation details and if the implementation confirms to the quarkus requirements or not. Maybe something like https://github.com/quarkusio/quarkus/issues/5740 would be help.

**Comment by loicmathieu** [comment]
@marceloverdijk is the error occurs in JVM mode or in a native image ?
 
If it's inside a native image, can you try adding `@RegisterForRegflection` to your `com.demo.Project` class to be sure it is not removed during native image processing.

**Comment by gsmet** [comment]
@marceloverdijk IMHO, there is something suspicious with the type machinery loading your `Project` class via reflection.

Could you add a breakpoint and get the full stacktrace of this call?

**Comment by marceloverdijk** [comment]
It is in JVM mode; haven't tried native mode yet to be honest.
I will create a sample project and also check with a breakpoint this evening. Will update this ticket then.

**Comment by marceloverdijk** [comment]
@gsmet this is the full stacktrace:

```
2020-01-20 18:29:51,358 ERROR [io.qua.application] (main) Failed to start application: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:113)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:67)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:54)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:109)
        at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:57)
        at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:82)
        at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits29.deploy_0(HibernateOrmProcessor$startPersistenceUnits29.zig:51)
        at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits29.deploy(HibernateOrmProcessor$startPersistenceUnits29.zig:70)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:153)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:167)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.array.ListArrayType
        at org.hibernate.type.TypeFactory.type(TypeFactory.java:96)
        at org.hibernate.type.TypeFactory.byClass(TypeFactory.java:66)
        at org.hibernate.type.TypeResolver.heuristicType(TypeResolver.java:126)
        at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:473)
        at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:455)
        at org.hibernate.mapping.Property.isValid(Property.java:227)
        at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:624)
        at org.hibernate.mapping.RootClass.validate(RootClass.java:267)
        at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:343)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:461)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:65)
        ... 14 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassNotFoundException: com.demo.Project
        at com.vladmihalcea.hibernate.type.util.ReflectionUtils.handleException(ReflectionUtils.java:580)
        at com.vladmihalcea.hibernate.type.util.ReflectionUtils.getClass(ReflectionUtils.java:435)
        at com.vladmihalcea.hibernate.type.array.internal.ListArrayTypeDescriptor.setParameterValues(ListArrayTypeDescriptor.java:67)
        at com.vladmihalcea.hibernate.type.array.internal.AbstractArrayType.setParameterValues(AbstractArrayType.java:42)
        at org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:109)
        at org.hibernate.type.TypeFactory.type(TypeFactory.java:92)
        ... 24 more
Caused by: java.lang.ClassNotFoundException: com.demo.Project
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at com.vladmihalcea.hibernate.type.util.ReflectionUtils.getClass(ReflectionUtils.java:433)
        ... 28 more

2020-01-20 18:29:51,372 ERROR [io.qua.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:223)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:167)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:113)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:67)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:54)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:109)
        at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:57)
        at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:82)
        at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits29.deploy_0(HibernateOrmProcessor$startPersistenceUnits29.zig:51)
        at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits29.deploy(HibernateOrmProcessor$startPersistenceUnits29.zig:70)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:153)
        ... 5 more
Caused by: org.hibernate.MappingException: Could not instantiate Type: com.vladmihalcea.hibernate.type.array.ListArrayType
        at org.hibernate.type.TypeFactory.type(TypeFactory.java:96)
        at org.hibernate.type.TypeFactory.byClass(TypeFactory.java:66)
        at org.hibernate.type.TypeResolver.heuristicType(TypeResolver.java:126)
        at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:473)
        at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:455)
        at org.hibernate.mapping.Property.isValid(Property.java:227)
        at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:624)
        at org.hibernate.mapping.RootClass.validate(RootClass.java:267)
        at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:343)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:461)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:65)
        ... 14 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassNotFoundException: com.demo.Project
        at com.vladmihalcea.hibernate.type.util.ReflectionUtils.handleException(ReflectionUtils.java:580)
        at com.vladmihalcea.hibernate.type.util.ReflectionUtils.getClass(ReflectionUtils.java:435)
        at com.vladmihalcea.hibernate.type.array.internal.ListArrayTypeDescriptor.setParameterValues(ListArrayTypeDescriptor.java:67)
        at com.vladmihalcea.hibernate.type.array.internal.AbstractArrayType.setParameterValues(AbstractArrayType.java:42)
        at org.hibernate.type.TypeFactory.injectParameters(TypeFactory.java:109)
        at org.hibernate.type.TypeFactory.type(TypeFactory.java:92)
        ... 24 more
Caused by: java.lang.ClassNotFoundException: com.demo.Project
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at com.vladmihalcea.hibernate.type.util.ReflectionUtils.getClass(ReflectionUtils.java:433)
        ... 28 more

```

**Comment by marceloverdijk** [comment]
@gsmet as it needs PostgreSQL for the array type I cannot make a demo project with H2.
If you prefer a demo project let me know, then I will work something out.

**Comment by marceloverdijk** [comment]
I did some manual `Class.forName(s)` while in debug mode, and it seems all project classes give a `ClassNotFoundException`. Classes from dependencies do work with `Class.forName`. 
Maybe for some reason `quarkusDev` doesn't add them to the classloader?

**Comment by stuartwdouglas** [comment]
Are you using Class.forName("com.demo.Project", false, Thread.currentThread().getContextClassLoader()); ?

The single argument version does not use the context class loader, so will likely not be able to load project dependencies when used by an external jar in dev mode.

**Comment by stuartwdouglas** [comment]
The reason for this is because Quarkus uses a 2 layer class loading structure, to allow the application classes to be dropped on hot reload. This means that using the single argument version of Class.forName will attempt to load classes using the base class loader which cannot see the application classes.

**Comment by marceloverdijk** [comment]
The problem is when a 3th party lib is using `Class.forName(s)` (with the single argument) the application does not run?

**Comment by stuartwdouglas** [comment]
It will not run if it attempts to load an application class, it can load other 3rd party classes. In general things should always use the Thread Context Class Loader, as it will work in almost all environments.

**Comment by marceloverdijk** [comment]
I understand, but it means all 3th party libs using `Class.forName(s)` won't work? And try to see if these libs can change to ` Class.forName(s, false, Thread.currentThread().getContextClassLoader())`? Correct?

**Comment by stuartwdouglas** [comment]
yes, but that is already true of a lot of environments, it only really works properly if you have a flat classspath, or it is inside the same classloader as the classes you are loading. Most libraries will use the 3 argument version, because they need to to work correctly in environments like WildFly or OSGi.

**Comment by marceloverdijk** [comment]
OK, thanks for the explanation. I will make a PR in the `hibernate-types` project.

**Comment by marceloverdijk** [comment]
For anyone interested the following [PR](https://github.com/vladmihalcea/hibernate-types/pull/177) is created within the `hibernate-types` repo.
