### ISSUE TITLE
Java gradle native build fails with submodules

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#6635]
**Describe the bug**
I have a gradle multi-module project setup with Quarkus and Java. One module contains only Java code (called `plain-java`), the other one is a Quarkus project (`quarkus-java`), which imports the `plain-java` project. 

Running `gradlew assemble` , `gradlew :quarkus-java:quarkus-dev` and `gradlew :quarkus-java:quarkusBuild` all work fine. However, the native build `:gradlew :quarkus-java:buildNative` fails with the following exception: 

```
C:\development\testing\quarkus-debugging\quarkus-java-gradle-submodule-reproducer>gradlew  :quarkus-java:buildNative
Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - test.quarkus.java.dto.SomeDto
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.

> Task :quarkus-java:quarkusBuild
building quarkus runner
These dependencies are not recommended:
        - org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.2_spec should be replaced by jakarta.interceptor:jakarta.interceptor-api
You might end up with two different versions of the same classes or with an artifact you shouldn't have in your classpath.
Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - test.quarkus.java.dto.SomeDto
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.

> Task :quarkus-java:buildNative
building native image
These dependencies are not recommended:
        - org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.2_spec should be replaced by jakarta.interceptor:jakarta.interceptor-api
You might end up with two different versions of the same classes or with an artifact you shouldn't have in your classpath.

Error: Class initialization of io.quarkus.runner.ApplicationImpl failed. Use the option --initialize-at-run-time=io.quarkus.runner.ApplicationImpl to explicitly request delayed initialization of this class.
Detailed message:

com.oracle.svm.core.util.UserError$UserException: Class initialization of io.quarkus.runner.ApplicationImpl failed. Use the option --initialize-at-run-time=io.quarkus.runner.ApplicationImpl to explicitly request delayed initialization of this class.
Detailed message:

        at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:223)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:737)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Class initialization of io.quarkus.runner.ApplicationImpl failed. Use the option --initialize-at-run-time=io.quarkus.runner.ApplicationImpl to explicitly request delayed initialization of this class.
Detailed message:

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:688)
        ... 7 more
Caused by: java.lang.ExceptionInInitializerError
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:153)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:557)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:116)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:144)
        at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:190)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:262)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:203)
        at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:155)
        at org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4080)
        at org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4330)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5128)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3267)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3074)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:976)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:870)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:510)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        ... 4 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:342)
        ... 34 more
Caused by: java.lang.NoClassDefFoundError: test/quarkus/java/dto/SomeDto
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetPublicMethods(Class.java:2902)
        at java.lang.Class.getMethods(Class.java:1615)
        at org.jboss.resteasy.spi.metadata.ResourceBuilder.fromAnnotations(ResourceBuilder.java:908)
        at org.jboss.resteasy.spi.metadata.ResourceBuilder.getRootResourceFromAnnotations(ResourceBuilder.java:878)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.<init>(POJOResourceFactory.java:40)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:88)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.registration(ResteasyDeploymentImpl.java:474)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:289)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:90)
        at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.staticInit(ResteasyStandaloneRecorder.java:86)
        at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit140.deploy_0(ResteasyStandaloneBuildStep$staticInit140.zig:850)
        at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit140.deploy(ResteasyStandaloneBuildStep$staticInit140.zig:869)
        at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:328)
        ... 34 more
Caused by: java.lang.ClassNotFoundException: test.quarkus.java.dto.SomeDto
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 49 more
Error: Image build request failed with exit status 1

> Task :quarkus-java:buildNative FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkus-java:buildNative'.
> Failed to generate a native image

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
6 actionable tasks: 2 executed, 4 up-to-date
```

**Expected behavior**
The native build should work.

**Actual behavior**
Native build breaks.

**To Reproduce**
1. Download and unzip reproducer project [quarkus-java-gradle-submodule-reproducer.zip](https://github.com/quarkusio/quarkus/files/4085480/quarkus-java-gradle-submodule-reproducer.zip)
2. Run `./gradlew :quarkus-java:buildNative` in the directory. (I configured it to use docker build, so either have docker running or disable the dockerbuild.)
3. It fails.

**Comment by andreas-eberle** [comment]
This SO question seems to mention the same problem but unfortunately no solution yet: https://stackoverflow.com/questions/56781972/how-to-create-a-jandex-index-in-quarkus-for-classes-in-a-external-module-for-gra

**Comment by mklueh** [comment]
Also running into it now

**Comment by aloubyansky** [comment]
Appears to be working with 1.3.0.Final. Thanks for the report.
