### ISSUE TITLE
Unsupported feature error loadClass(Module, String) with graal master

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#6685]
I'm trying GraalVM master (commit a765907c72e0e7519a7cb85673acf643987cb860) built with `11.0.5+10-jvmci-19.3-b04-LTS` and seeing this failure:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.it.hibernate.validator.HibernateValidatorFunctionalityInGraalITCase
Executing [/Users/g/1/quarkus-jdk11/integration-tests/hibernate-validator/target/quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
2020-01-21 14:38:58,910 INFO  [io.quarkus] (main) quarkus-integration-test-hibernate-validator 999-SNAPSHOT (running on Quarkus 999-SNAPSHOT) started in 0.018s. Listening on: http://0.0.0.0:8081
2020-01-21 14:38:58,910 INFO  [io.quarkus] (main) Profile prod activated.
2020-01-21 14:38:58,910 INFO  [io.quarkus] (main) Installed features: [cdi, hibernate-validator, resteasy, resteasy-jsonb]
[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.929 s <<< FAILURE! - in io.quarkus.it.hibernate.validator.HibernateValidatorFunctionalityInGraalITCase
[ERROR] testManualValidationMessageLocale  Time elapsed: 0.047 s  <<< FAILURE!
java.lang.AssertionError:
1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "Vrijednost ne zadovoljava uzorak"
  Actual: javax.ws.rs.ProcessingException: RESTEASY008200: JSON Binding deserialization error: com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: Target_java_lang_ClassLoader.loadClass(Target_java_lang_Module, String)
```

The call analysis tree can be found [here](https://gist.github.com/galderz/a56443a2117013d8e65e572be635c96b).

I've tried to add another substitution for the same call site, so that `loadClass(Module, String)` returns null instead, but that didn't work:

```
Error: Already registered: java.lang.ClassLoader.loadClass(Module, String)
com.oracle.svm.core.util.UserError$UserException: Already registered: java.lang.ClassLoader.loadClass(Module, String)
```

I've not yet tried with last released Java 11 GraalVM to see if it's also present there.

**Comment by galderz** [comment]
Issue does not happen with graalvm 19.3.1 (java 11), so that's good. I'll still dig further to understand what is causing this: either a fault on my side, or something a change in graalvm master that could affect us in the future.

**Comment by galderz** [comment]
Full stacktrace:

```
2020-01-22 15:21:07,934 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002305: Failed executing POST /hibernate-validator/test/test-manual-validation-message-locale: org.jboss.resteasy.spi.ReaderException: javax.ws.rs.ProcessingException: RESTEASY008200: JSON Binding deserialization error: com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: Target_java_lang_ClassLoader.loadClass(Target_java_lang_Module, String)
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:249)
	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$injectArguments$1(MethodInjectorImpl.java:96)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:96)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:121)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:594)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:468)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:421)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:423)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:365)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:120)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:85)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: javax.ws.rs.ProcessingException: RESTEASY008200: JSON Binding deserialization error: com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: Target_java_lang_ClassLoader.loadClass(Target_java_lang_Module, String)
	at org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider.readFrom(JsonBindingProvider.java:78)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:102)
	at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:64)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:81)
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:212)
	... 37 more
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: Target_java_lang_ClassLoader.loadClass(Target_java_lang_Module, String)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Package.getPackageInfo(Package.java:420)
	at java.lang.Package.getAnnotations(Package.java:467)
	at org.eclipse.yasson.internal.AnnotationIntrospector.collectAnnotations(AnnotationIntrospector.java:757)
	at org.eclipse.yasson.internal.MappingContext.lambda$createParseClassModelFunction$1(MappingContext.java:89)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:80)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:62)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:52)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:59)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:99)
	at org.jboss.resteasy.plugins.providers.jsonb.JsonBindingProvider.readFrom(JsonBindingProvider.java:70)
	... 41 more
```

**Comment by dmlloyd** [comment]
This part right here:

```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: Target_java_lang_ClassLoader.loadClass(Target_java_lang_Module, String)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Package.getPackageInfo(Package.java:420)
	at java.lang.Package.getAnnotations(Package.java:467)
	at org.eclipse.yasson.internal.AnnotationIntrospector.collectAnnotations(AnnotationIntrospector.java:757)
...
```

indicates a SVM bug.  `Package.getAnnotations` should either itself be considered unsupported, or else it should be fixed along the lines of other methods which allow the gathering of annotations.  We need an upstream Graal issue for this (if one hasn't already been opened).

**Comment by galderz** [comment]
@dmlloyd I'll open an issue

**Comment by galderz** [comment]
[graal#2111](https://github.com/oracle/graal/issues/2111)

**Comment by galderz** [comment]
Fixed in graal
