### ISSUE TITLE
Native build fails with "quarkus-logging-gelf" extension (Unsupported method sun.nio.ch.DatagramDispatcher.read0)

### ISSUE THREAD

**Issue by michael-schnell** [quarkusio/quarkus#6697]
**Describe the bug**
Adding the extension "quarkus-logging-gelf" makes the native build fail with " Unsupported method sun.nio.ch.DatagramDispatcher.read0(FileDescriptor, long, int) is reachable: Native method."

**Expected behavior**
Native build should be successful using "quarkus-logging-gelf" extension.

**Actual behavior**
Native build fails if "quarkus-logging-gelf" extension is added to pom.xml.

**To Reproduce**
1. Goto https://code.quarkus.io/
2. Select "Core / Logging GELF" in addition to default extensions
3. Download and extract archive to disk
4. Execute `./mvnw clean package -Pnative`
5. Fails with "Unsupported method sun.nio.ch.DatagramDispatcher.read0(FileDescriptor, long, int) is reachable: Native method"

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux xxxx 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
 - GraalVM version (if different from Java): penJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
 - Quarkus version: 1.1.1.Final

**Additional context**
Stacktrace
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.2.1 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /home/developer/.sdkman/candidates/java/19.2.1-grl/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar code-with-quarkus-1.0.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace code-with-quarkus-1.0.0-SNAPSHOT-runner
[code-with-quarkus-1.0.0-SNAPSHOT-runner:2903]    classlist:   5,666.25 ms
[code-with-quarkus-1.0.0-SNAPSHOT-runner:2903]        (cap):   1,773.20 ms
[code-with-quarkus-1.0.0-SNAPSHOT-runner:2903]        setup:   4,193.55 ms
18:39:16,597 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
[code-with-quarkus-1.0.0-SNAPSHOT-runner:2903]   (typeflow):  32,557.60 ms
[code-with-quarkus-1.0.0-SNAPSHOT-runner:2903]    (objects):  16,607.72 ms
[code-with-quarkus-1.0.0-SNAPSHOT-runner:2903]   (features):     405.14 ms
[code-with-quarkus-1.0.0-SNAPSHOT-runner:2903]     analysis:  51,374.27 ms
[code-with-quarkus-1.0.0-SNAPSHOT-runner:2903]     (clinit):   6,106.36 ms
[code-with-quarkus-1.0.0-SNAPSHOT-runner:2903]     universe:   7,401.01 ms
Error: Unsupported method sun.nio.ch.DatagramDispatcher.read0(FileDescriptor, long, int) is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Call path from entry point to sun.nio.ch.DatagramDispatcher.read0(FileDescriptor, long, int): 
	at sun.nio.ch.DatagramDispatcher.read0(DatagramDispatcher.java)
	at sun.nio.ch.DatagramDispatcher.read(DatagramDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SimpleAsynchronousFileChannelImpl$2.run(SimpleAsynchronousFileChannelImpl.java:320)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported method sun.nio.ch.DatagramDispatcher.read0(FileDescriptor, long, int) is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Call path from entry point to sun.nio.ch.DatagramDispatcher.read0(FileDescriptor, long, int): 
	at sun.nio.ch.DatagramDispatcher.read0(DatagramDispatcher.java)
	at sun.nio.ch.DatagramDispatcher.read(DatagramDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SimpleAsynchronousFileChannelImpl$2.run(SimpleAsynchronousFileChannelImpl.java:320)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:223)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:581)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method sun.nio.ch.DatagramDispatcher.read0(FileDescriptor, long, int) is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Call path from entry point to sun.nio.ch.DatagramDispatcher.read0(FileDescriptor, long, int): 
	at sun.nio.ch.DatagramDispatcher.read0(DatagramDispatcher.java)
	at sun.nio.ch.DatagramDispatcher.read(DatagramDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SimpleAsynchronousFileChannelImpl$2.run(SimpleAsynchronousFileChannelImpl.java:320)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:579)
	... 6 more
Error: Image build request failed with exit status 1

```

**Comment by gsmet** [comment]
Looks like enabling JNI fixes the issue, I'm on it.

**Comment by gsmet** [comment]
You can work around the issue by setting `quarkus.native.enable-jni` to true at the bottom of the generated pom.xml. It should look like:
```xml
      <properties>
        <quarkus.package.type>native</quarkus.package.type>
        <quarkus.native.enable-jni>true</quarkus.native.enable-jni>
      </properties>
```
