### ISSUE TITLE
AmazonLambdaRecorder.chooseHandlerClass needs to support RequestStreamHandler pattern

### ISSUE THREAD

**Issue by stdunbar** [quarkusio/quarkus#6707]
I'm unable to get the out of the box AWS Lambda test to work if my Lambda uses the RequestStreamHandler implementation pattern.  My code:

```
@Named("lambdaHandler")
public class LambdaHandler implements RequestStreamHandler {
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context) {
        context.getLogger().log( "starting " + this.getClass().getName() );
    }
}
```

And my application.properties has `quarkus.lambda.handler=lambdaHandler`.  At times it is easier to read the InputStream and parse what you need out of it rather than creating a POJO.  As it is I get:

```
2020-01-21 14:30:08,111 ERROR [io.qua.application] (main) Failed to start application: java.lang.RuntimeException: Unable to find handler class with name lambdaHandler make sure there is a handler class in the deployment with the correct @Named annotation
    at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.chooseHandlerClass(AmazonLambdaRecorder.java:98)
    at io.quarkus.deployment.steps.AmazonLambdaProcessor$recordHandlerClass32.deploy_0(AmazonLambdaProcessor$recordHandlerClass32.zig:110)
    at io.quarkus.deployment.steps.AmazonLambdaProcessor$recordHandlerClass32.deploy(AmazonLambdaProcessor$recordHandlerClass32.zig:129)
    at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:172)
    at io.quarkus.runtime.Application.start(Application.java:87)
```

Perhaps the `quarkus.lambda.handler` could work like the AWS Lambda environment and accept a full package name with method name, i.e. `com.example.lambda.handler.LambdaHander::myHandler`

**Comment by gsmet** [comment]
@evanchooly could you have a look at that one?

**Comment by jmkgreen** [comment]
I am seeing exactly the same. If it implements RequestHandler it seems to work.

According to https://quarkus.io/guides/amazon-lambda#choose-your-lambda only `RequestHandler` implementations are scanned for, which may be why.

I am building against `RequestHandler` because I want to use Jackson. The documentation for Quarkus mentioning Jackson does not make clear whether the integration is purely for REST API interfaces or for others such as Amazon Lambda too (which would render my work here redundant).

**Comment by PhilAndrew** [comment]
If I follow the application builder to create the AWS Lambda application then ./mvnw compile quarkus:dev I get the following error.

```
Listening for transport dt_socket at address: 5005
2020-02-18 09:37:23,524 ERROR [io.qua.application] (main) Failed to start application: java.lang.RuntimeException: Unable to find handler class, make sure your deployment includes a com.amazonaws.services.lambda.runtime.RequestHandler implementation
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.chooseHandlerClass(AmazonLambdaRecorder.java:110)
	at io.quarkus.deployment.steps.AmazonLambdaProcessor$recordHandlerClass31.deploy_0(AmazonLambdaProcessor$recordHandlerClass31.zig:129)
	at io.quarkus.deployment.steps.AmazonLambdaProcessor$recordHandlerClass31.deploy(AmazonLambdaProcessor$recordHandlerClass31.zig:36)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:172)
	at io.quarkus.runtime.Application.start(Application.java:87)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:167)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)

2020-02-18 09:37:23,546 ERROR [io.qua.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:202)
	at io.quarkus.runtime.Application.start(Application.java:87)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:167)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: java.lang.RuntimeException: Unable to find handler class, make sure your deployment includes a com.amazonaws.services.lambda.runtime.RequestHandler implementation
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.chooseHandlerClass(AmazonLambdaRecorder.java:110)
	at io.quarkus.deployment.steps.AmazonLambdaProcessor$recordHandlerClass31.deploy_0(AmazonLambdaProcessor$recordHandlerClass31.zig:129)
	at io.quarkus.deployment.steps.AmazonLambdaProcessor$recordHandlerClass31.deploy(AmazonLambdaProcessor$recordHandlerClass31.zig:36)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:172)
	... 5 more
```

**Comment by geniusit** [comment]
+1

**Comment by gsmet** [comment]
Can one of you provide a reproducer?

/cc @patriot1burke @evanchooly

**Comment by patriot1burke** [comment]
No need for a producer.  I understand the problem.  WE don't support stream handler.

**Comment by patriot1burke** [comment]
This is a feature request, not a bug.

**Comment by geniusit** [comment]
Unfortunately, the S3Event object doesn't work with native image .
I ve open an issue for it :https://github.com/quarkusio/quarkus/issues/7670
How to retrieve bucket + key informations with the native image ?

**Comment by oztimpower** [comment]
Please close, this was added by #7866
