### ISSUE TITLE
JWT responds with "401 Unauthorized" 

### ISSUE THREAD

**Issue by zeljkot** [quarkusio/quarkus#6740]
**Describe the bug**
After upgrade to 1.2.0.CR1, all requests are responded with 401 Unauthorized.

**Expected behavior**
With the correct JWT token, a request should be processed.

**Actual behavior**
All requests are responded with 401 Unauthorized.

**To Reproduce**
1. Configure Keycloak client to map "User Client Role" to "groups" (was necessary for 1.1)
2. Using Postman, obtain JWT token.
3. Send a request with a token attached.

**Configuration**
```properties
  mp:
    jwt:
      verify:
        publickey:
          location: classpath:META-INF/certificate.json
quarkus:
  ...
  smallrye-jwt:
    enabled: true
  ssl:
    native: true
```
or
```
quarkus.ssl.native=true
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.publickey.location=keycloak:8080/auth/realms/1/protocol/openid-connect/certs
mp.jwt.verify.issuer=keycloak:8080/auth/realms/1
```
**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.19041.21]
 - Output of `java -version`: java version "1.8.0_231"
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: 1.2.0.CR1

**Additional context**

Please document the proper Keycloak configuration.

**Comment by sberyozkin** [comment]
@zeljkot Thanks. Unfortunately the log content was lost as part of [this PR](https://github.com/smallrye/smallrye-jwt/commit/52fb7d4b8f4d85f3b2d7cea5a8e897cfb7f4bc22#diff-5f4020e440d6d2dd7b7ff27fbe83dd25). 
Can you please try to see what is being logged [here](https://github.com/quarkusio/quarkus/blob/1.1.1.Final/extensions/smallrye-jwt/runtime/src/main/java/io/quarkus/smallrye/jwt/runtime/auth/MpJwtValidator.java#L72) ?

**Comment by zeljkot** [comment]
With file.based token `-Dmp.jwt.verify.publickey.location=classpath:META-INF/certificate.json` i get

```
2020-01-23 12:10:37,016 DEBUG [asc.api-service] () [vert.x-eventloop-thread-14] [JWTAuthContextInfoProvider.java:241] - init, mpJwtPublicKey=NONE, mpJwtIssuer=keycloak:8080/auth/realms/1, mpJwtLocation=classpath:META-INF/certificate.json
2020-01-23 12:10:37,017 DEBUG [asc.api-service] () [vert.x-eventloop-thread-14] [AbstractBearerTokenExtractor.java:55] - tokenHeaderName = Authorization
2020-01-23 12:10:37,030 DEBUG [asc.api-service] () [vert.x-eventloop-thread-14] [KeyLocationResolver.java:243] - Trying to create a key from the encoded PEM key...
2020-01-23 12:10:37,032 DEBUG [asc.api-service] () [vert.x-eventloop-thread-14] [KeyLocationResolver.java:247] - Failed to create a key from the encoded PEM key: java.lang.IllegalArgumentException: Illegal base64 character 7b
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at io.smallrye.jwt.KeyUtils.decodePublicKey(KeyUtils.java:169)
	at io.smallrye.jwt.auth.principal.KeyLocationResolver.tryAsPEMPublicKey(KeyLocationResolver.java:245)
	at io.smallrye.jwt.auth.principal.KeyLocationResolver.initializeKeyContent(KeyLocationResolver.java:172)
	at io.smallrye.jwt.auth.principal.KeyLocationResolver.<init>(KeyLocationResolver.java:82)
	at io.smallrye.jwt.auth.principal.DefaultJWTTokenParser.getKeyResolver(DefaultJWTTokenParser.java:227)
	at io.smallrye.jwt.auth.principal.DefaultJWTTokenParser.parse(DefaultJWTTokenParser.java:72)
	at io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator.authenticate(MpJwtValidator.java:55)
	at io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator.authenticate(MpJwtValidator.java:28)
	at io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator_ClientProxy.authenticate(MpJwtValidator_ClientProxy.zig:134)
	at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl.handleProvider(QuarkusIdentityProviderManagerImpl.java:121)
...
```

**Comment by zeljkot** [comment]
With HTTP `mp.jwt.verify.publickey=http://keycloak:8080/auth/realms/1/protocol/openid-connect/certs` I get

```
2020-01-23 12:49:51,738 DEBUG [asc.api-service] () [vert.x-eventloop-thread-21] [JWTAuthContextInfoProvider.java:241] - init, mpJwtPublicKey=http://keycloak:8080/auth/realms/1/protocol/openid-connect/certs, mpJwtIssuer=http://keycloak:8080/auth/realms/1, mpJwtLocation=keycloak:8080/auth/realms/1/protocol/openid-connect/certs
2020-01-23 12:49:51,749 DEBUG [asc.api-service] () [vert.x-eventloop-thread-21] [JWTAuthContextInfoProvider.java:307] - mpJwtPublicKey failed as JWK(S), Illegal base64 character 3a
2020-01-23 12:49:51,750 ERROR [asc.api-service] () [vert.x-eventloop-thread-21] [QuarkusErrorHandler.java:60] - HTTP Request to /atries-rx/1/asc/api-service/v1/shifts?importFrom=2019-08-11T00:00:00Z&importTo=2019-08-12T23:59:59Z failed, error id: 43f76a3e-0d07-47e6-ae8c-7756de829aba-1: javax.enterprise.inject.spi.DeploymentException: java.lang.IllegalArgumentException: Illegal base64 character 3a
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider.decodeMpJwtPublicKey(JWTAuthContextInfoProvider.java:313)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider.getOptionalContextInfo(JWTAuthContextInfoProvider.java:258)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider.getContextInfo(JWTAuthContextInfoProvider.java:390)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.create(JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.zig:154)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.create(JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.zig:206)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_ClientProxy.arc$delegate(JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_ClientProxy.zig:1057)
	at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_ClientProxy.getTokenHeader(JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_ClientProxy.zig:474)
	at io.smallrye.jwt.auth.AbstractBearerTokenExtractor.getBearerToken(AbstractBearerTokenExtractor.java:54)
	at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMechanism.authenticate(JWTAuthMechanism.java:47)
```

**Comment by sberyozkin** [comment]
Hi @zeljkot thanks, what is `certificate.json`, is it a 'base64-encoded' JWK key ? The only thing that have changed in `KeyLocationResolver` related to it is that an extra Base64-URL decoding try is added which was not even there in 2.0,10.
https://github.com/smallrye/smallrye-jwt/blob/2.0.12/implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java

Can you please post this certificate.json - it is a public key so should be OK and I can try locally; or if you could put a breakpoint in `KeyLocationResolver` then it would also help

**Comment by sberyozkin** [comment]
@zeljkot Also, FYI, `publickey` can not point to a URL based location, it should be a PEM or JWK or JWK set, try `publickey.location`

**Comment by sberyozkin** [comment]
@zeljkot Another question, have you changed to a different a Keycloak version recently ?

**Comment by zeljkot** [comment]
In the first example with file, I used publickey.location: 
`mp.jwt.verify.publickey.location=classpath:META-INF/certificate.json`

In the second example, with URL, I used just the publickey:
`mp.jwt.verify.publickey=http://keycloak:8080/auth/realms/1/protocol/openid-connect/certs`

Keycloak version is baked-in in docker-compose; not the latest one, but the one required by the customer: 
```
keycloak:
  image: jboss/keycloak:6.0.1
```

In any case, the file worked with 1.1 and now it does not. The only changed thing is Quarkus version.

**Comment by sberyozkin** [comment]
@zeljkot sure, so somehow we need to identify the problem. The smallrye-jwt tests in Quarkus (extension specific) and MP JWT TCK tests are passing.
As I said, either paste a public certificate here if it is not a sensitive info  and I will check it or otherwise please put a breakpoint in that resolver code and check locally what exactly is happening.

**Comment by zeljkot** [comment]
In the end, it was misconfiguration from my side and confusing error messages from MP JWT side. Even now when I make everything work I get 
```
2020-01-23 15:33:29,991 DEBUG [asc.api-service] () [vert.x-eventloop-thread-0] [KeyLocationResolver.java:253] - Trying to create a key from the encoded PEM certificate...
2020-01-23 15:33:29,991 DEBUG [asc.api-service] () [vert.x-eventloop-thread-0] [KeyLocationResolver.java:257] - Failed to to create a key from the encoded PEM certificate: java.lang.IllegalArgumentException: Illegal base64 character 7b

```

I could not find it without a debugger. I understand that security frameworks are intentionally silent about problems, I just wish there is an easier way to find the issue.

What puzzles me most is that everything worked when I reverted to 1.1.

On the bright side, the problem with Windows and HTTP certificates is gone. Thank you for yout support!

**Comment by sberyozkin** [comment]
Hi @zeljkot thanks a million, yeah, it was a bit tricky :-). It just logs there the options it tries, but it needs to be made less confusing, will open an issue in smallrye-jwt

**Comment by sberyozkin** [comment]
@zeljkot FYI, https://github.com/smallrye/smallrye-jwt/issues/173

**Comment by zeljkot** [comment]
I subscribed immediately :)
