### ISSUE TITLE
Injected Vertx may be null if the bean also declares @Observes Router

### ISSUE THREAD

**Issue by svilenvul** [quarkusio/quarkus#6764]
**Describe the bug**

We are trying to use the Vert.x extension and inject a Vert.x instance into our app.
Sometimes during application initialization we get a NPE, causing Quarkus start to fail. 

**Expected behavior**
Quarkus starts every single time.

**Actual behavior**
Stacktrace:

```
2020-01-24 12:25:52,307 ERROR [io.qua.application] (main) Failed to start application: java.lang.RuntimeException: Error injecting io.vertx.core.Vertx com.example.Application.vertx
        at com.example.Application_Bean.create(Application_Bean.zig:234)
        at com.example.Application_Bean.create(Application_Bean.zig:257)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at com.example.Application_ClientProxy.arc$delegate(Application_ClientProxy.zig:81)
        at com.example.Application_ClientProxy.arc_contextualInstance(Application_ClientProxy.zig:176)
        at com.example.Application_Observer_init_4919b00b6fde9fec4bbb79136e5247a43318336f.notify(Application_Observer_init_4919b00b6fde9fec4bbb79136e5247a43318336f.zig:86)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.finalizeRouter(VertxHttpRecorder.java:194)
        at io.quarkus.deployment.steps.VertxHttpProcessor$finalizeRouter20.deploy_0(VertxHttpProcessor$finalizeRouter20.zig:169)
        at io.quarkus.deployment.steps.VertxHttpProcessor$finalizeRouter20.deploy(VertxHttpProcessor$finalizeRouter20.zig:237)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:140)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:167)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: java.lang.NullPointerException
        at io.quarkus.vertx.core.runtime.VertxCoreProducer.vertx(VertxCoreProducer.java:26)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:258)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:69)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:128)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:84)
        at com.example.Application_Bean.create(Application_Bean.zig:217)
        ... 21 more

2020-01-24 12:25:52,345 ERROR [io.qua.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:194)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:167)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
Caused by: java.lang.RuntimeException: Error injecting io.vertx.core.Vertx com.example.Application.vertx
        at com.example.Application_Bean.create(Application_Bean.zig:234)
        at com.example.Application_Bean.create(Application_Bean.zig:257)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at com.example.Application_ClientProxy.arc$delegate(Application_ClientProxy.zig:81)
        at com.example.Application_ClientProxy.arc_contextualInstance(Application_ClientProxy.zig:176)
        at com.example.Application_Observer_init_4919b00b6fde9fec4bbb79136e5247a43318336f.notify(Application_Observer_init_4919b00b6fde9fec4bbb79136e5247a43318336f.zig:86)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.finalizeRouter(VertxHttpRecorder.java:194)
        at io.quarkus.deployment.steps.VertxHttpProcessor$finalizeRouter20.deploy_0(VertxHttpProcessor$finalizeRouter20.zig:169)
        at io.quarkus.deployment.steps.VertxHttpProcessor$finalizeRouter20.deploy(VertxHttpProcessor$finalizeRouter20.zig:237)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:140)
        ... 5 more
Caused by: java.lang.NullPointerException
        at io.quarkus.vertx.core.runtime.VertxCoreProducer.vertx(VertxCoreProducer.java:26)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:258)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.create(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:69)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:128)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:84)
        at com.example.Application_Bean.create(Application_Bean.zig:217)
        ... 21 more3_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:128)
        at io.quarkus.vertx.core.runtime.VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.get(VertxCoreProducer_ProducerMethod_vertx_c3372c086117ae1666bc66dfa7ac379ab76c5253_Bean.zig:84)
        ... 21 more
```

**To Reproduce**

Run this example several times.

```
@ApplicationScoped
public class Application {

	@Inject
	Vertx vertx;
	Router router;

	void init(@Observes Router router) {
		this.router = router;
	}
	
	void onStart(@Observes StartupEvent ev) throws MissedConfigurationException {
		logger.debug("Application {} is starting ...",  SERVICE_NAME);
		...
		
	}

	void onStop(@Observes ShutdownEvent ev) {
		logger.debug("Application {} is stopping ...",  SERVICE_NAME);
	}

}
```

**Environment (please complete the following information):**
 - Quarkus 1.2.0.Final

**Additional context**
Possibly a race condition see -  https://github.com/quarkusio/quarkus/issues/6612#issuecomment-578083123

**Comment by mkouba** [comment]
That's probably another regression related to the problem of "two `Vertx` instances".

`io.quarkus.vertx.http.deployment.VertxHttpProcessor.finalizeRouter()` should be run after the `VertxCoreProducer` is initialized. However, currently it only depends on `InternalWebVertxBuildItem` and not the `CoreVertxBuildItem`. TBH I'm quite confused and it is not clear to me whether it should depend on `CoreVertxBuildItem` instead. `InternalWebVertxBuildItem` is deprecated but there is no more info...

@FroMage @stuartwdouglas @cescoffier ^ ideas?

**Comment by FroMage** [comment]
It's possible. We'd have to try it after #5593 is fixed.

**Comment by cescoffier** [comment]
Didn't I fix this last Monday in #6698 ?

**Comment by mkouba** [comment]
@cescoffier that PR is just a bunch of tests ;-)

**Comment by marziman** [comment]
@cescoffier hope you re fine! Could you please help us. This NPE blocks currently some of our services to run. Maybe you can double check, why your fix got lost. Many thanks.

**Comment by stuartwdouglas** [comment]
I think this line should have fixed it in master: https://github.com/quarkusio/quarkus/pull/6686/files#diff-5e1b09692896da198409c72e771d5760R118

**Comment by cescoffier** [comment]
@mkouba I was referring to this commit: https://github.com/quarkusio/quarkus/pull/6686/commits/2ffdb28d6ebe4c24dc7eb139ecfd055b32ec8659

**Comment by mkouba** [comment]
@stuartwdouglas and @cescoffier are right, this should be fixed in master (quarkus 1.3). @gsmet [this commit](https://github.com/quarkusio/quarkus/pull/6686/commits/2ffdb28d6ebe4c24dc7eb139ecfd055b32ec8659) should be probably backported to 1.2.

**Comment by svilenvul** [comment]
Is it possible to have a 1.2.1 release including this fix? 
This is really blocking us now to use Quarkus in our project.

**Comment by cescoffier** [comment]
@gsmet FYI ^ I don't know what are the release plans
