### ISSUE TITLE
Azure Functions - BaseFunction.java triggers a ClassCastException on Azure JavaWorker

### ISSUE THREAD

**Issue by carlitorendon** [quarkusio/quarkus#6940]
**Describe the bug**
Say you deploy a Quarkus app to Azure Functions (using mvn azure-functions:deploy or mvn azure-functions:run). Later you want to interact with any of your endpoints. You get a ClassCastException (see Actual Behavior section)

**Expected behavior**
Being able to interact with the REST endpoint

**Actual behavior**
`[2/2/2020 5:34:45 AM] Executed 'Functions.quarkus' (Failed, Id=5b062e90-b8e1-463c-bd7b-d7fa412acddd)
[2/2/2020 5:34:45 AM] System.Private.CoreLib: Exception while executing function: Functions.quarkus. System.Private.CoreLib: Result: Failure
Exception: ClassCastException: Cannot convert com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource@4f5c16a2to type com.microsoft.azure.functions.HttpRequestMessage<java.util.Optional<byte[]>>
Stack: java.lang.ClassCastException: Cannot convert com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource@4f5c16a2to type com.microsoft.azure.functions.HttpRequestMessage<java.util.Optional<byte[]>>
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.DataOperations.generalAssignment(DataOperations.java:191)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.DataOperations.apply(DataOperations.java:120)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.DataSource.computeByType(DataSource.java:56)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByType(RpcHttpRequestDataSource.java:20)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.DataSource.computeByName(DataSource.java:42)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.RpcHttpRequestDataSource.computeByName(RpcHttpRequestDataSource.java:20)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.binding.BindingDataStore.getDataByName(BindingDataStore.java:55)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:59)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.broker.ParameterResolver.resolve(ParameterResolver.java:42)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:52) [2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:53)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2/2/2020 5:34:45 AM]   at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2/2/2020 5:34:45 AM]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2/2/2020 5:34:45 AM]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2/2/2020 5:34:45 AM]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2/2/2020 5:34:45 AM]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2/2/2020 5:34:45 AM]   at java.lang.Thread.run(Thread.java:748)
[2/2/2020 5:34:45 AM] .`

**To Reproduce**
1. Build a hello world quarkus app 
2. Run locally: `mvn azure-functions:run`
3. Exercise your REST endpoint

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/14046845/73603760-dc0ea600-454c-11ea-99d2-01a4b12f0fba.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Microsoft Windows [Version 10.0.18363.628]`
 - Output of `java -version`: 
openjdk version "1.8.0_222"
`OpenJDK Runtime Environment (Zulu 8.40.0.25-CA-win64) (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-win64) (build 25.222-b10, mixed mode)`
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.1.1.Final
- Azure functions version: 1.3.0

**Additional context**
(Add any other context about the problem here.)

**Comment by carlitorendon** [comment]
Our current solution is to override the following parts of BaseFunction.java in our project code:

`
// Notice the Optional is of String instead of byte[]
protected HttpResponseMessage dispatch(HttpRequestMessage<Optional<String>> request) {
        VirtualClientConnection connection = VirtualClientConnection.connect(VertxHttpRecorder.VIRTUAL_HTTP);
        try {
            return nettyDispatch(connection, request);
        } catch (Exception e) {
            e.printStackTrace();
            return request
                    .createResponseBuilder(HttpStatus.valueOf(500)).build();
        } finally {
            connection.close();
        }
    }

// Notice the Optional is of String instead of byte[]
protected HttpResponseMessage nettyDispatch(VirtualClientConnection connection,
                                                HttpRequestMessage<Optional<String>> request)
            throws Exception {
        String path = request.getUri().getRawPath();
        String query = request.getUri().getRawQuery();
        if (query != null)
            path = path + '?' + query;
        String host = request.getUri().getHost();
        if (request.getUri().getPort() != -1) {
            host = host + ':' + request.getUri().getPort();
        }
        DefaultHttpRequest nettyRequest = new DefaultHttpRequest(HttpVersion.HTTP_1_1,
                HttpMethod.valueOf(request.getHttpMethod().name()), path);
        nettyRequest.headers().set("Host", host);
        for (Map.Entry<String, String> header : request.getHeaders().entrySet()) {
            nettyRequest.headers().add(header.getKey(), header.getValue());
        }

        HttpContent requestContent = LastHttpContent.EMPTY_LAST_CONTENT;
        if (request.getBody().isPresent()) {
            // Notice we get the bytes from the String instead of assuming the optional is an array of bytes.
            ByteBuf body = Unpooled.wrappedBuffer(request.getBody().get().getBytes());
            requestContent = new DefaultLastHttpContent(body);
        }

        connection.sendMessage(nettyRequest);
        connection.sendMessage(requestContent);
        HttpResponseMessage.Builder responseBuilder = null;
        ByteArrayOutputStream baos = null;
        for (;;) {
            // todo should we timeout? have a timeout config?
            //log.info("waiting for message");
            Object msg = connection.queue().poll(100, TimeUnit.MILLISECONDS);
            try {
                if (msg == null)
                    continue;
                //log.info("Got message: " + msg.getClass().getName());

                if (msg instanceof HttpResponse) {
                    HttpResponse res = (HttpResponse) msg;
                    responseBuilder = request.createResponseBuilder(HttpStatus.valueOf(res.status().code()));
                    for (Map.Entry<String, String> entry : res.headers()) {
                        responseBuilder.header(entry.getKey(), entry.getValue());
                    }
                }
                if (msg instanceof HttpContent) {
                    HttpContent content = (HttpContent) msg;
                    if (baos == null) {
                        // todo what is right size?
                        baos = new ByteArrayOutputStream(500);
                    }
                    int readable = content.content().readableBytes();
                    for (int i = 0; i < readable; i++) {
                        baos.write(content.content().readByte());
                    }
                }
                if (msg instanceof LastHttpContent) {
                    responseBuilder.body(baos.toByteArray());
                    return responseBuilder.build();
                }
            } finally {
                if (msg != null)
                    ReferenceCountUtil.release(msg);
            }
        }
    }

`

**Comment by tehMalone** [comment]
@carlitorendon's solution worked for me too!

**Comment by stuartwdouglas** [comment]
@patriot1burke do you know if this is still an issue?

**Comment by patriot1burke** [comment]
I'll take a look, I never tried azure-functions:run.  I just did azure-functiosn:deploy and hit azure with a client.

**Comment by patriot1burke** [comment]
@clarlitorendon @tehMalone 

Guys, maybe you have a custom function.json?  The dataType must be "binary"

`{
  "scriptFile" : "../${project.build.finalName}-runner.jar",
  "entryPoint" : "io.quarkus.azure.functions.resteasy.runtime.Function.run",
  "bindings" : [ {
    "type" : "httpTrigger",
    "direction" : "in",
    "name" : "req",
    "route" : "{*path}",
    "methods" : [ "GET", "POST", "HEAD", "PUT", "OPTIONS", "DELETE" ],
    "dataType" : "binary",
    "authLevel" : "ANONYMOUS"
  }, {
    "type" : "http",
    "direction" : "out",
    "name" : "$return"
  } ]
}`

**Comment by moewes** [comment]
I have the same issue with the latest quarkus 1.10.5.Final version. GET works fine, but no POST with an application/json payload. It gives the same ClassCastException as mentioned above. function.json is not custom. it is the generated one like in the above comment from @patriot1burke (i.e. "dataType" : "binary").

The workaround proposed from @carlitorendon also worked for me in my szenario.

**Comment by patriot1burke** [comment]
I'm pretty sure this is configuration related, but I need to review Azure Functions as I haven't done them in a long time.
