### ISSUE TITLE
Qute Error with for

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#6957]
**Describe the bug**

Hi I have got the next POJO:

```
@TemplateData // <1>
public class Movie {


    public String name;
    public int year;
    public String genre;
    public String director;
    public List<String> mainCharacters = new ArrayList<>();
    public float ratings;


    public int getStars() { // <2>
        return Math.round(ratings);
    }
}
```
Then I am trying to print all the mainCharacters list to an html file template:

```
<dt>Main Characters:</dt>
{#for character in movie.mainCharacters} <!--5-->
{character} <!--6-->
{#if hasNext} <!--7-->
 -
{/if}
{/for}
```

If I remove the previous part the Quarkus app works correctly and the other attributes of Movie are printed but if I add the for then I got the next exception:

```
13:27:19,254 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
 [error]: Build step io.quarkus.qute.deployment.QuteProcessor#validateExpressions threw an exception: java.lang.IllegalArgumentException: Not a parameterized type!
 at org.jboss.jandex.Type.asParameterizedType(Type.java:228)
 at io.quarkus.qute.deployment.QuteProcessor.resolveType(QuteProcessor.java:701)
 at io.quarkus.qute.deployment.QuteProcessor.validateExpressions(QuteProcessor.java:267)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
 at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
 at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
 at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
 at java.base/java.lang.Thread.run(Thread.java:834)
 at org.jboss.threads.JBossThread.run(JBossThread.java:479)
 at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:181)
 at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
 at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
 at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
```

**Expected behavior**

For logic is executed.

**Actual behavior**

An exception is thrown.

**Environment (please complete the following information):**
 - Quarkus 1.2.0

**Additional context**

If it is not a bug and it is something that I have done wrong, I think that the error message should be improved so any user can fix the problem on his own.

**Comment by mkouba** [comment]
Hi @lordofthejars, do you use [parameter declarations](https://quarkus.io/guides/qute-reference#parameter-declarations) in your template?

**Comment by lordofthejars** [comment]
Yes

```
{@org.acme.quickstart.Movie movie} <!--1-->
<!DOCTYPE html>
<html>
```

**Comment by lordofthejars** [comment]
In fact, it works with all parameters except the one defined as a list.
