### ISSUE TITLE
Coverage with jacoco provoques not intialize configuration

### ISSUE THREAD

**Issue by rosell** [quarkusio/quarkus#6992]
**Describe the bug**
If you have a class with a **@ConfigProperties** when run the integration test fails because on the configuration not are defined the synthetic fields added by jacoco.

**Expected behavior**
To run the integration test without problems.

**Actual behavior**
The integration tests fails because try to verify the synthetic values inserted by jacoco , and they are not defined on the configuration.

**Posible solution**
Ignore the synthetic fields when refactoring on Configuraiton load. As you can see at [gradle-jacoco-tasks-add-synthetic-fields-when-spring-app-running-leading-fail](https://stackoverflow.com/questions/52855176/gradle-jacoco-tasks-add-synthetic-fields-when-spring-app-running-leading-fail)

**To Reproduce**
1.  git clone https://github.com/rosell/quarkus-test-coverage-error.git
2.  cd quarkus-test-coverage-error
3.  mvn verify

**Configuration**
```properties
# Add your application.properties here, if applicable.
greetings.version=1.0.0
```

**Screenshots**
`$ mvn verify
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< org.acme:tests-with-coverage-quickstart >---------------
[INFO] Building tests-with-coverage-quickstart 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tests-with-coverage-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ tests-with-coverage-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/rosell/git/quarkus-test-coverage-error/target/classes
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.4:instrument (instrument-ut) @ tests-with-coverage-quickstart ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ tests-with-coverage-quickstart ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/rosell/git/quarkus-test-coverage-error/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ tests-with-coverage-quickstart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/rosell/git/quarkus-test-coverage-error/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ tests-with-coverage-quickstart ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.quickstart.GreetingsConfigurationTest
15:10:41,237 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.096 s <<< FAILURE! - in org.acme.quickstart.GreetingsConfigurationTest
[ERROR] shouldLoadConfiguration  Time elapsed: 0.011 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: 
TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.quickstart.GreetingsConfigurationTest]: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep#setup threw an exception: java.lang.IllegalArgumentException: Configuration properties class org.acme.quickstart.GreetingsConfiguration does not have a setter for field boolean[] org.acme.quickstart.GreetingsConfiguration.$jacocoData nor is the field a public non-final field
	at io.quarkus.arc.deployment.configproperties.ClassConfigPropertiesUtil.populateConfigObject(ClassConfigPropertiesUtil.java:221)
	at io.quarkus.arc.deployment.configproperties.ClassConfigPropertiesUtil.addProducerMethodForClassConfigProperties(ClassConfigPropertiesUtil.java:172)
	at io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep.setup(ConfigPropertiesBuildStep.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

Caused by: java.lang.RuntimeException: 
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep#setup threw an exception: java.lang.IllegalArgumentException: Configuration properties class org.acme.quickstart.GreetingsConfiguration does not have a setter for field boolean[] org.acme.quickstart.GreetingsConfiguration.$jacocoData nor is the field a public non-final field
	at io.quarkus.arc.deployment.configproperties.ClassConfigPropertiesUtil.populateConfigObject(ClassConfigPropertiesUtil.java:221)
	at io.quarkus.arc.deployment.configproperties.ClassConfigPropertiesUtil.addProducerMethodForClassConfigProperties(ClassConfigPropertiesUtil.java:172)
	at io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep.setup(ConfigPropertiesBuildStep.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

Caused by: io.quarkus.builder.BuildException: 
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep#setup threw an exception: java.lang.IllegalArgumentException: Configuration properties class org.acme.quickstart.GreetingsConfiguration does not have a setter for field boolean[] org.acme.quickstart.GreetingsConfiguration.$jacocoData nor is the field a public non-final field
	at io.quarkus.arc.deployment.configproperties.ClassConfigPropertiesUtil.populateConfigObject(ClassConfigPropertiesUtil.java:221)
	at io.quarkus.arc.deployment.configproperties.ClassConfigPropertiesUtil.addProducerMethodForClassConfigProperties(ClassConfigPropertiesUtil.java:172)
	at io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep.setup(ConfigPropertiesBuildStep.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

Caused by: java.lang.IllegalArgumentException: Configuration properties class org.acme.quickstart.GreetingsConfiguration does not have a setter for field boolean[] org.acme.quickstart.GreetingsConfiguration.$jacocoData nor is the field a public non-final field

[ERROR] shouldHaveVersion  Time elapsed: 0.012 s  <<< ERROR!
java.lang.NullPointerException
	at org.acme.quickstart.GreetingsConfigurationTest.shouldHaveVersion(GreetingsConfigurationTest.java:39)

[INFO] Running org.acme.quickstart.GreetingServiceTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.acme.quickstart.GreetingServiceTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   GreetingsConfigurationTest.shouldHaveVersion:39 NullPointer
[ERROR]   GreetingsConfigurationTest.shouldLoadConfiguration » TestInstantiation TestIns...
[INFO] 
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.421 s
[INFO] Finished at: 2020-02-04T15:10:41+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project tests-with-coverage-quickstart: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/rosell/git/quarkus-test-coverage-error/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Darwin dhcp10-149 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.2.0.Final

**Additional context**

I created a derivated project from the [MEASURING THE COVERAGE OF YOUR TESTS](https://quarkus.io/guides/tests-with-coveragel) to show the error at [github](https://github.com/rosell/quarkus-test-coverage-error)

**Comment by emersonl91** [comment]
+1

**Comment by emersonl91** [comment]
It also occurs in 1.3.0.Final

**Comment by geoand** [comment]
Is this still an issue in the latest Quarkus versions?
