### ISSUE TITLE
OIDC code flow tests failing in native on CI

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#7044]
The OIDC code flow tests are now consistently failing on CI with something like:

```
Caused by: org.opentest4j.AssertionFailedError: expected: </index.html> but was: <null>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at io.quarkus.it.keycloak.CodeFlowTest.testAccessTokenInjection(CodeFlowTest.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:360)
	... 62 more

2020-02-06 17:27:14,690 INFO  [io.quarkus] (main) Quarkus stopped in 0.069s

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   CodeFlowTest.testAccessAndRefreshTokenInjection » Runtime org.opentest4j.Asser...
[ERROR]   CodeFlowTest.testAccessAndRefreshTokenInjectionWithoutIndexHtml » Runtime org....
[ERROR]   CodeFlowTest.testAccessTokenInjection » Runtime org.opentest4j.AssertionFailed...
[ERROR]   CodeFlowTest.testCodeFlowNoConsent » Runtime org.opentest4j.AssertionFailedErr...
[ERROR]   CodeFlowTest.testIdTokenInjection » Runtime org.opentest4j.AssertionFailedErro...
[ERROR]   CodeFlowTest.testIdTokenInjectionWithoutRestoredPath » Runtime org.opentest4j....
[ERROR]   CodeFlowTest.testTokenTimeoutLogout » Runtime org.opentest4j.AssertionFailedEr...
```

/cc @sberyozkin @pedroigor

**Comment by sberyozkin** [comment]
@gsmet FYI, I've rebased the latest OIDC PR which I merged in the morning and it was totally green.

**Comment by gsmet** [comment]
Not saying you did anything wrong but we had 2 builds failing in a row with the exact same errors. Looks suspicious.

**Comment by sberyozkin** [comment]
@gsmet Hi Guillaume, I'm always open to realizing I've broken a build :-), but so far I can't reproduce:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.it.keycloak.CodeFlowInGraalITCase
Executing [/home/sberyozkin/work/rh/quarkusio/quarkus/integration-tests/oidc-code-flow/target/quarkus-integration-test-oidc-code-flow-999-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
2020-02-06 18:09:39,799 INFO  [io.quarkus] (main) quarkus-integration-test-oidc-code-flow 999-SNAPSHOT (running on Quarkus 999-SNAPSHOT) started in 0.035s. Listening on: http://0.0.0.0:8081
2020-02-06 18:09:39,799 INFO  [io.quarkus] (main) Profile prod activated. 
2020-02-06 18:09:39,799 INFO  [io.quarkus] (main) Installed features: [cdi, oidc, resteasy, resteasy-jackson, security]
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.822 s - in io.quarkus.it.keycloak.CodeFlowInGraalITCase
``

**Comment by sberyozkin** [comment]
Have rebuilt the master, rerun the tests, still no luck...

**Comment by sberyozkin** [comment]
I'd like to disable one test that depends on a multi-tenancy feature and see if it makes a difference

**Comment by geoand** [comment]
I saw this failure in some PRs as well FWIW

**Comment by sberyozkin** [comment]
If #7045 passes then I'd rewrite that test a bit to avoid setting a custom cookie, my best bet that it has not been cleared in the JVM mode (despite the disabled test actually asking HtmlUnit WebClient to clear it and as such it then affects the tests in the native mode)

**Comment by sberyozkin** [comment]
Hi, #7045 has passed so I'm hoping it was causing the problem, or rather the cookie which this test was depending upon was not cleaned-up. I'll follow up with a simpler solution as the tenant id is not really needed in that test after a redirect, will try tomorrow to let other PRs go in without being affected :-)
