### ISSUE TITLE
Gradle native build mask error

### ISSUE THREAD

**Issue by sciack** [quarkusio/quarkus#7055]
**Describe the bug**
When a gradle native build goes in error, it's really difficult to understand the problem, the exception will just tell that something is failing.

**Expected behavior**
I'm expecting a meaningful error like maven:
`Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: com.ibm.icu.text.Normalizer. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.`

**Actual behavior**
Just the exception telling that ImageGenerationFailed:
```
Caused by: java.lang.RuntimeException: Failed to build native image
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:319)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
```

**To Reproduce**
1. clone project https://github.com/sciack/test-native-compilation
2. run ./gradlew buildNative -i --stacktrace
3. compare result with mvn package -Pnative

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin Mirkos-MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.2.0.final

**Additional context**
(Add any other context about the problem here.)

**Comment by lfmunoz** [comment]
Similar to https://github.com/quarkusio/quarkus/issues/7549

**Comment by bluemonk3y** [comment]
Throwing error '-1' tells us the child process fails but little else. Looking at the code it could  return the command instead of dropping it - hence making everyones lives easier 👍 

`    private RuntimeException imageGenerationFailed(int exitValue, List<String> command) {
        if (exitValue == 137) {
            return command.contains("docker") && !IS_LINUX ? new RuntimeException("Image generation failed. Exit code was " + exitValue + " which indicates an out of memory error. The most likely cause is Docker not being given enough memory. Also consider increasing the Xmx value for native image generation by setting the \"" + "quarkus.native.native-image-xmx" + "\" property") : new RuntimeException("Image generation failed. Exit code was " + exitValue + " which indicates an out of memory error. Consider increasing the Xmx value for native image generation by setting the \"" + "quarkus.native.native-image-xmx" + "\" property");
        } else {
            return new RuntimeException("Image generation failed. Exit code: " + exitValue);
        }
    }`

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
