### ISSUE TITLE
Provider for SchemaFactory cannot be created (1.3.0.Alpha1)

### ISSUE THREAD

**Issue by JohT** [quarkusio/quarkus#7096]
**Describe the bug**
QuarkusTests fail with the following exception when started with Quarkus 1.3.0.Alpha1:

Caused by: javax.xml.validation.SchemaFactoryConfigurationError: Provider for class javax.xml.validation.SchemaFactory cannot be crea
ted
Caused by: java.util.ServiceConfigurationError: javax.xml.validation.SchemaFactory: org.apache.xerces.jaxp.validation.XMLSchemaFactor
y Unable to get public no-arg constructor
Caused by: java.lang.LinkageError: loader constraint violation for class org.apache.xerces.jaxp.validation.XMLSchemaFactory: when sel
ecting overriding method org.apache.xerces.jaxp.validation.XMLSchemaFactory.setErrorHandler(Lorg/xml/sax/ErrorHandler;)V the class lo
ader io.quarkus.bootstrap.classloading.QuarkusClassLoader @57565143 (instance of io.quarkus.bootstrap.classloading.QuarkusClassLoader
, child of 'bootstrap') of the selected method's type org.apache.xerces.jaxp.validation.XMLSchemaFactory, and the class loader 'boots
trap' for its super type javax.xml.validation.SchemaFactory have different Class objects for the type org.xml.sax.ErrorHandler used i
n the signature

**To Reproduce**
1. Clone ```https://github.com/JohT/showcase-quarkus-eventsourcing```
2. Change Quarkus version to 1.3.0.Alpha1 (instead of 1.2.0.Final)
3. Run ```mvn clean package```

**Environment (please complete the following information):**
 - Output of `java -version`: 8
 - GraalVM version (if different from Java): 19.2.1
 - Quarkus version or git rev: 1.3.0.Alpha1

**Stacktrace**
```
[ERROR] io.github.joht.showcase.quarkuseventsourcing.service.account.AccountResourceIntegrationTest  Time elapsed: 2.684 s
 <<< ERROR!
java.lang.RuntimeException:
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build threw an exception: javax.xml.validation.
SchemaFactoryConfigurationError: Provider for class javax.xml.validation.SchemaFactory cannot be created
        at java.xml/javax.xml.validation.SchemaFactoryFinder.findServiceProvider(SchemaFactoryFinder.java:350)
        at java.xml/javax.xml.validation.SchemaFactoryFinder._newFactory(SchemaFactoryFinder.java:217)
        at java.xml/javax.xml.validation.SchemaFactoryFinder.newFactory(SchemaFactoryFinder.java:144)
        at java.xml/javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:245)
        at org.hibernate.boot.xsd.LocalXsdResolver.resolveLocalXsdSchema(LocalXsdResolver.java:95)
        at org.hibernate.boot.xsd.LocalXsdResolver.buildXsdDescriptor(LocalXsdResolver.java:116)
        at org.hibernate.boot.xsd.ConfigXsdSupport.getJPA21(ConfigXsdSupport.java:110)
        at org.hibernate.boot.xsd.ConfigXsdSupport.jpaXsd(ConfigXsdSupport.java:46)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.validate(PersistenceXmlParser.java:467)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.loadUrl(PersistenceXmlParser.java:439)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.parsePersistenceXml(PersistenceXmlParser.java:242)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.parsePersistenceXml(PersistenceXmlParser.java:235)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.doResolve(PersistenceXmlParser.java:229)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.locatePersistenceUnits(PersistenceXmlParser.java:67)
        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.loadOriginalXMLParsedDescriptors(HibernateOrmProcessor.java:743)

        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.build(HibernateOrmProcessor.java:158)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.util.ServiceConfigurationError: javax.xml.validation.SchemaFactory: org.apache.xerces.jaxp.validation.XMLSchemaFactor
y Unable to get public no-arg constructor
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:672)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1232)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
        at java.xml/javax.xml.validation.SchemaFactoryFinder$2.run(SchemaFactoryFinder.java:339)
        at java.xml/javax.xml.validation.SchemaFactoryFinder$2.run(SchemaFactoryFinder.java:335)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.xml/javax.xml.validation.SchemaFactoryFinder.findServiceProvider(SchemaFactoryFinder.java:335)
        ... 27 more
Caused by: java.lang.LinkageError: loader constraint violation for class org.apache.xerces.jaxp.validation.XMLSchemaFactory: when sel
ecting overriding method org.apache.xerces.jaxp.validation.XMLSchemaFactory.setErrorHandler(Lorg/xml/sax/ErrorHandler;)V the class lo
ader io.quarkus.bootstrap.classloading.QuarkusClassLoader @57565143 (instance of io.quarkus.bootstrap.classloading.QuarkusClassLoader
, child of 'bootstrap') of the selected method's type org.apache.xerces.jaxp.validation.XMLSchemaFactory, and the class loader 'boots
trap' for its super type javax.xml.validation.SchemaFactory have different Class objects for the type org.xml.sax.ErrorHandler used i
n the signature
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
        at java.base/java.lang.Class.getConstructor0(Class.java:3343)
        at java.base/java.lang.Class.getConstructor(Class.java:2152)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:656)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:667)
        ... 35 more

Caused by: java.lang.RuntimeException:
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build threw an exception: javax.xml.validation.
SchemaFactoryConfigurationError: Provider for class javax.xml.validation.SchemaFactory cannot be created
        at java.xml/javax.xml.validation.SchemaFactoryFinder.findServiceProvider(SchemaFactoryFinder.java:350)
        at java.xml/javax.xml.validation.SchemaFactoryFinder._newFactory(SchemaFactoryFinder.java:217)
        at java.xml/javax.xml.validation.SchemaFactoryFinder.newFactory(SchemaFactoryFinder.java:144)
        at java.xml/javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:245)
        at org.hibernate.boot.xsd.LocalXsdResolver.resolveLocalXsdSchema(LocalXsdResolver.java:95)
        at org.hibernate.boot.xsd.LocalXsdResolver.buildXsdDescriptor(LocalXsdResolver.java:116)
        at org.hibernate.boot.xsd.ConfigXsdSupport.getJPA21(ConfigXsdSupport.java:110)
        at org.hibernate.boot.xsd.ConfigXsdSupport.jpaXsd(ConfigXsdSupport.java:46)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.validate(PersistenceXmlParser.java:467)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.loadUrl(PersistenceXmlParser.java:439)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.parsePersistenceXml(PersistenceXmlParser.java:242)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.parsePersistenceXml(PersistenceXmlParser.java:235)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.doResolve(PersistenceXmlParser.java:229)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.locatePersistenceUnits(PersistenceXmlParser.java:67)
        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.loadOriginalXMLParsedDescriptors(HibernateOrmProcessor.java:743)

        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.build(HibernateOrmProcessor.java:158)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.util.ServiceConfigurationError: javax.xml.validation.SchemaFactory: org.apache.xerces.jaxp.validation.XMLSchemaFactor
y Unable to get public no-arg constructor
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:672)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1232)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
        at java.xml/javax.xml.validation.SchemaFactoryFinder$2.run(SchemaFactoryFinder.java:339)
        at java.xml/javax.xml.validation.SchemaFactoryFinder$2.run(SchemaFactoryFinder.java:335)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.xml/javax.xml.validation.SchemaFactoryFinder.findServiceProvider(SchemaFactoryFinder.java:335)
        ... 27 more
Caused by: java.lang.LinkageError: loader constraint violation for class org.apache.xerces.jaxp.validation.XMLSchemaFactory: when sel
ecting overriding method org.apache.xerces.jaxp.validation.XMLSchemaFactory.setErrorHandler(Lorg/xml/sax/ErrorHandler;)V the class lo
ader io.quarkus.bootstrap.classloading.QuarkusClassLoader @57565143 (instance of io.quarkus.bootstrap.classloading.QuarkusClassLoader
, child of 'bootstrap') of the selected method's type org.apache.xerces.jaxp.validation.XMLSchemaFactory, and the class loader 'boots
trap' for its super type javax.xml.validation.SchemaFactory have different Class objects for the type org.xml.sax.ErrorHandler used i
n the signature
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
        at java.base/java.lang.Class.getConstructor0(Class.java:3343)
        at java.base/java.lang.Class.getConstructor(Class.java:2152)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:656)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:667)
        ... 35 more

Caused by: io.quarkus.builder.BuildException:
Build failure: Build failed due to errors
        [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build threw an exception: javax.xml.validation.
SchemaFactoryConfigurationError: Provider for class javax.xml.validation.SchemaFactory cannot be created
        at java.xml/javax.xml.validation.SchemaFactoryFinder.findServiceProvider(SchemaFactoryFinder.java:350)
        at java.xml/javax.xml.validation.SchemaFactoryFinder._newFactory(SchemaFactoryFinder.java:217)
        at java.xml/javax.xml.validation.SchemaFactoryFinder.newFactory(SchemaFactoryFinder.java:144)
        at java.xml/javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:245)
        at org.hibernate.boot.xsd.LocalXsdResolver.resolveLocalXsdSchema(LocalXsdResolver.java:95)
        at org.hibernate.boot.xsd.LocalXsdResolver.buildXsdDescriptor(LocalXsdResolver.java:116)
        at org.hibernate.boot.xsd.ConfigXsdSupport.getJPA21(ConfigXsdSupport.java:110)
        at org.hibernate.boot.xsd.ConfigXsdSupport.jpaXsd(ConfigXsdSupport.java:46)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.validate(PersistenceXmlParser.java:467)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.loadUrl(PersistenceXmlParser.java:439)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.parsePersistenceXml(PersistenceXmlParser.java:242)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.parsePersistenceXml(PersistenceXmlParser.java:235)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.doResolve(PersistenceXmlParser.java:229)
        at org.hibernate.jpa.boot.internal.PersistenceXmlParser.locatePersistenceUnits(PersistenceXmlParser.java:67)
        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.loadOriginalXMLParsedDescriptors(HibernateOrmProcessor.java:743)

        at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.build(HibernateOrmProcessor.java:158)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.util.ServiceConfigurationError: javax.xml.validation.SchemaFactory: org.apache.xerces.jaxp.validation.XMLSchemaFactor
y Unable to get public no-arg constructor
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:672)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1232)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
        at java.xml/javax.xml.validation.SchemaFactoryFinder$2.run(SchemaFactoryFinder.java:339)
        at java.xml/javax.xml.validation.SchemaFactoryFinder$2.run(SchemaFactoryFinder.java:335)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.xml/javax.xml.validation.SchemaFactoryFinder.findServiceProvider(SchemaFactoryFinder.java:335)
        ... 27 more
Caused by: java.lang.LinkageError: loader constraint violation for class org.apache.xerces.jaxp.validation.XMLSchemaFactory: when sel
ecting overriding method org.apache.xerces.jaxp.validation.XMLSchemaFactory.setErrorHandler(Lorg/xml/sax/ErrorHandler;)V the class lo
ader io.quarkus.bootstrap.classloading.QuarkusClassLoader @57565143 (instance of io.quarkus.bootstrap.classloading.QuarkusClassLoader
, child of 'bootstrap') of the selected method's type org.apache.xerces.jaxp.validation.XMLSchemaFactory, and the class loader 'boots
trap' for its super type javax.xml.validation.SchemaFactory have different Class objects for the type org.xml.sax.ErrorHandler used i
n the signature
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
        at java.base/java.lang.Class.getConstructor0(Class.java:3343)
        at java.base/java.lang.Class.getConstructor(Class.java:2152)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:656)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:667)
        ... 35 more

Caused by: javax.xml.validation.SchemaFactoryConfigurationError: Provider for class javax.xml.validation.SchemaFactory cannot be crea
ted
Caused by: java.util.ServiceConfigurationError: javax.xml.validation.SchemaFactory: org.apache.xerces.jaxp.validation.XMLSchemaFactor
y Unable to get public no-arg constructor
Caused by: java.lang.LinkageError: loader constraint violation for class org.apache.xerces.jaxp.validation.XMLSchemaFactory: when sel
ecting overriding method org.apache.xerces.jaxp.validation.XMLSchemaFactory.setErrorHandler(Lorg/xml/sax/ErrorHandler;)V the class lo
ader io.quarkus.bootstrap.classloading.QuarkusClassLoader @57565143 (instance of io.quarkus.bootstrap.classloading.QuarkusClassLoader
, child of 'bootstrap') of the selected method's type org.apache.xerces.jaxp.validation.XMLSchemaFactory, and the class loader 'boots
trap' for its super type javax.xml.validation.SchemaFactory have different Class objects for the type org.xml.sax.ErrorHandler used i
n the signature
```

**Comment by gwenneg** [comment]
Thanks for reporting this @JohT!

@stuartwdouglas Could this be related to the big classloader change?

**Comment by stuartwdouglas** [comment]
Yes, this is related to the class loading change.

Generally it happens when you have some artifacts that provide javax.xml classes, but not all of them.

**Comment by stuartwdouglas** [comment]
If you build with https://github.com/quarkusio/quarkus/pull/7106 and exclude the xml-apis dependency from dom4j then the tests pass. I am leaving this open though, as we need a better solution for XML, I will post to the mailing list shortly.

**Comment by gastaldi** [comment]
Closing as outdated. Please reopen if it's still relevant in 3.14.0
