### ISSUE TITLE
New ExtensionProcessor APT fails in Eclipse

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#713]
I'm getting a lot of these errors:

```
Caused by: java.lang.UnsupportedOperationException: Instantiating a Nested type Config of Reference of type JaxrsScanningProcessor as a class
	at org.jboss.jdeparser.AbstractJType._new(AbstractJType.java:79)
	at org.jboss.shamrock.annotation.processor.ExtensionAnnotationProcessor.generateAccessor(ExtensionAnnotationProcessor.java:437)
	at org.jboss.shamrock.annotation.processor.ExtensionAnnotationProcessor.processConfigGroup(ExtensionAnnotationProcessor.java:377)
	at org.jboss.shamrock.annotation.processor.ExtensionAnnotationProcessor.doProcess(ExtensionAnnotationProcessor.java:133)
	at org.jboss.shamrock.annotation.processor.ExtensionAnnotationProcessor.process(ExtensionAnnotationProcessor.java:114)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	... 24 more
```

**Comment by gsmet** [comment]
I'm closing this one. It's so low priority that we will never come to it.
