### ISSUE TITLE
Apache POI not working in native build

### ISSUE THREAD

**Issue by wfrank2509** [quarkusio/quarkus#7171]
**Describe the bug**
I created a server that parses a simple table in an Excel Sheet with Apache POI.
Running the code on the JVM works like expected but in the nativeBuild version I get a runtime exception when the XSSFWorkbook is created.

**Expected behavior**
Should work like in JVM build.

**Actual behavior**
```
 docker run -i --rm -p 8080:8080 wfrank/product-info                                            ✔  502  20:55:21
2020-02-12 19:55:31,206 INFO  [io.quarkus] (main) productinfo 1.0.0-SNAPSHOT (running on Quarkus 1.2.0.Final) started in 0.014s. Listening on: http://0.0.0.0:8080
2020-02-12 19:55:31,206 INFO  [io.quarkus] (main) Profile prod activated. 
2020-02-12 19:55:31,206 INFO  [io.quarkus] (main) Installed features: [cdi, kotlin, resteasy, resteasy-jsonb]
Exception in thread "DefaultDispatcher-worker-1" org.apache.poi.ooxml.POIXMLException: org.apache.poi.xssf.usermodel.XSSFSheet.<init>org.apache.poi.openxml4j.opc.PackagePart
        at org.apache.poi.ooxml.POIXMLFactory.createDocumentPart(POIXMLFactory.java:66)
        at org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:657)
        at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:180)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:282)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:303)
...
...
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.NoSuchMethodException: org.apache.poi.xssf.usermodel.XSSFSheet.<init>org.apache.poi.openxml4j.opc.PackagePart
        at java.lang.Class.getConstructor0(DynamicHub.java:3082)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
        at org.apache.poi.xssf.usermodel.XSSFFactory.createDocumentPart(XSSFFactory.java:55)
        at org.apache.poi.ooxml.POIXMLFactory.createDocumentPart(POIXMLFactory.java:63)
        ... 26 more
```

**To Reproduce**
1. Add POI to project (Gradle: implementation "org.apache.poi:poi-ooxml:4.1.1")
2. Create workbook (e.g. val workbook = XSSFWorkbook(inputStream))
3. ./gradlew buildNative --docker-build=true
5. docker build -f src/main/docker/Dockerfile.native -t wfrank/product-info .
6. docker run -i --rm -p 8080:8080 wfrank/product-info   

**Configuration**
```properties
# Add your application.properties here, if applicable.
Nothing fancy
```

**Environment (please complete the following information):**
```
java -version                                                                        SIGINT(2) ↵  503  21:03:58
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
```

 - Quarkus version or git rev: 1.2.0-Final

**Additional context**
It looks like similar issues exist in the quarkus-tika extension (https://github.com/quarkusio/quarkus/issues/6549).

**Comment by sberyozkin** [comment]
@wfrank2509 thanks, but Quarkus does not have a poi extension so it is not a Quarkus bug :-).
What do you think about giving a tika extension a go ? In which case #6549 would be the issue to discuss

**Comment by gsmet** [comment]
I don't think it has anything to do with Tika. It's about generating a document with Apache POI.

There's a good chance you will need an extension for that to work flawlessly. But you could start by experimenting with a reflection config file: https://quarkus.io/guides/writing-native-applications-tips#using-a-configuration-file . And then we could build an extension from there.

**Comment by geoand** [comment]
I'm changing the label, since this is not a bug (for the simple reason that we don't have an Apache POI extension).

**Comment by sberyozkin** [comment]
@gsmet 
> I don't think it has anything to do with Tika. It's about generating a document with Apache POI.

Per the issue description: `I created a server that parses a simple table in an Excel Sheet with Apache POI.` It is not the generation.

So it is has everything to do with the Tika extension as it uses Apache POI to cover OOXML formats.

**Comment by sberyozkin** [comment]
Even though I'm likely biased, IMHO it does not make sense to create an extension per every familtyy of parsers around and then keep them all maintaining; instead, keeping improving the tika extension is a better strategy IMHO

**Comment by gsmet** [comment]
Ah sorry my bad. That being said, I don't think you can be as fine grained as with the Apache POI API when using Tika. Typically, can you extract a particular cell? Can you get a formula value?

Also keep in mind that Apache POI is widely used to generate Excel files so it has an interest outside of Tika.

So while I agree it makes no sense to have an extension for every parser. A POI one could have value.

**Comment by sberyozkin** [comment]
@gsmet, thanks, no problems, the description also says the exception is thrown when ` XSSFWorkbook is created`, so yeah, could've been either process :-)

Sounds good, re accessing some individual cells, true, Tika can't help. It depends what the requirement is, for the data analytics the fine grained access is typically not needed; for generating things Tika is of no help either (I've proposed to have a neutral Tika `write` API, same as for `read`) but so far there is a concern it would be too difficult to realize :-)

**Comment by wfrank2509** [comment]
I had already added a `reflection-config` and tried to provide all dependencies that way to see if that helps. Unfortunately no difference. I would be up to writing an extension for POI but right now I don't have any idea for this issue where to start (the general way to create an extension project is clear :)).

**Comment by geoand** [comment]
If this is still an issue, it should be reported at https://github.com/quarkiverse/quarkus-poi

**Comment by wfrank2509** [comment]
Hi ... this issue is not really relevant anymore for me.
