### ISSUE TITLE
Cannot configure Vertx Max Frame Size

### ISSUE THREAD

**Issue by nonconceptual** [quarkusio/quarkus#7172]
**Describe the bug**
I am encountering an issue when sending a large set of data to the Quarkus java server. It appears that I am hitting the max allowed frame size for vertx, and I cannot find any way to configure it for Quarkus. From the digging I have done thus far, I _think_ the culprit is io.vertx.core.http.HttpServerOptions#maxWebsocketFrameSize, which seems to be using the [default value.](https://vertx.io/docs/apidocs/io/vertx/core/http/HttpServerOptions.html#DEFAULT_MAX_WEBSOCKET_FRAME_SIZE)

Here is the stack trace I'm seeing:
`2020-02-12 00:15:40,918 WARN  [io.net.cha.DefaultChannelPipeline] (vert.x-eventloop-thread-0) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:426)
        at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:286)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)`

**Expected behavior**
Ability to configure Quarkus to support a larger max frame size, and transmit data without encountering any errors.

**Actual behavior**
Unable to transmit data larger than 65536 bytes. Error occurs during transmission, and the server never receives the data.

**To Reproduce**
1. Publish a string message over websocket larger than 65536 bytes.

**Configuration**
I have tried changing the http limits max-body-size and max-header-size, no luck.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux my-server 3.10.0-957.12.1.el7.x86_64 #1 SMP Wed Mar 20 11:34:37 UTC 2019 x86_64 Linux
 - Output of `java -version`: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
 - Quarkus version or git rev: 1.1.1.Final

**Additional context**
Server is running on a docker container deployed through kubernetes. The websocket endpoint is created using javax.websocket annotations.

**Comment by gsmet** [comment]
@nonconceptual that might be a nice thing to contribute if you want to try!

**Comment by gsmet** [comment]
@fmhwong would you be interested in driving this one home?

**Comment by nonconceptual** [comment]
> @nonconceptual that might be a nice thing to contribute if you want to try!
I don't have the immediate bandwidth but I do have another clue! Setting the `HttpServerOptions` in `VertxHttpRecorder` didn't fix the issue. Instead, increasing the frame size passed to `WebSocketFrameDecoder` in `Hanshake` worked for me.

**Comment by fmhwong** [comment]
Yes, I can take a look.

**Comment by fmhwong** [comment]
Found the place where the max frame size is hardcoded. 
https://github.com/quarkusio/quarkus-http/blob/c91488fa169ed3665d3166c55b98609aa43b43cc/websockets-jsr/src/main/java/io/undertow/websockets/jsr/handshake/Handshake.java#L121

**Comment by fmhwong** [comment]
@gsmet What will be a good way to pass a Quarkus configuration value to the `Handshake` class?

**Comment by nonconceptual** [comment]
@fmhwong This may not be what you're looking for, but it appears that all of the config params start in [HttpConfiguration](https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/HttpConfiguration.java)

**Comment by fmhwong** [comment]
@nonconceptual I can add a new config param in `HttpConfiguration` but it isn't trivial how to pass the value to `Handshake` class.

**Comment by gsmet** [comment]
@stuartwdouglas could you guide @fmhwong . See his question here: https://github.com/quarkusio/quarkus/issues/7172#issuecomment-590393234 .

**Comment by stuartwdouglas** [comment]
Quarkus HTTP changes needed are here: https://github.com/quarkusio/quarkus-http/pull/18

**Comment by fmhwong** [comment]
@stuartwdouglas  Thank you!  Do you know when will quarkus-http cut a new release with this changes?

**Comment by nonconceptual** [comment]
All, I looked at the pull request and it wasn't clear to me how the max frame size would be configured by a user? It appears to me that we still need to add a new config param?

**Comment by stuartwdouglas** [comment]
It does add a configuration parameter: https://github.com/stuartwdouglas/quarkus/commit/3da8342cea593cab2df130ed33c414f568fc9f21#diff-6f1cae14e352fc29f6a6ee30d87a2b5bR16

**Comment by incube8r** [comment]
> 
> 
> It does add a configuration parameter: [stuartwdouglas@3da8342#diff-6f1cae14e352fc29f6a6ee30d87a2b5bR16](https://github.com/stuartwdouglas/quarkus/commit/3da8342cea593cab2df130ed33c414f568fc9f21#diff-6f1cae14e352fc29f6a6ee30d87a2b5bR16)

I've experience this issue with https://quarkus.io/guides/websockets

What would be the value to add in the Quarkus `application.properties` file to change the max frame size? 

Also is this version covered by the fix? 

```
mvn io.quarkus:quarkus-maven-plugin:1.3.2.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=websockets-quickstart \
    -Dextensions="undertow-websockets"
cd websockets-quickstart
```

**Comment by incube8r** [comment]
...I've tried adding in the `application.properties`

```
quarkus.http.port=8081
quarkus.websocket.max-frame-size=1048576
```

Orignally the port I use for my app is 8080, so I changed it to 8081 to see if the `application.properties` is getting picked up, in fact it did changed port, but the max frame size is still throwing the server:

```
 io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.
```

What can I be missing?

**Comment by incube8r** [comment]
Just to add, I did some more testing.

In my code I added this to check for the real max frame size set:

```
    @ConfigProperty(name = "quarkus.websocket.max-frame-size"")
    Integer maxFrameSize;
```

Then simply log it:

```
    @OnMessage
    public void onMessage(ByteBuffer message, @PathParam("username") String username) {
        System.out.println("Max frame size: " + maxFrameSize);
        broadcast(message, username);
    }
```

Here's the output:

```
Max frame size: 1048576
2020-04-16 15:29:23,901 WARN  [io.net.cha.DefaultChannelPipeline] (vert.x-eventloop-thread-1) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did no
t handle the exception.: io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.
```

It seems like even the parameter is set the actual handler is still using the default one `65536`

**Comment by cescoffier** [comment]
`quarkus.websocket.max-frame-size` is a build time property (so setting it at runtime won't change the value).
