### ISSUE TITLE
Cannot build native image with Quarkus on Win10

### ISSUE THREAD

**Issue by tdevilleduc** [quarkusio/quarkus#7173]
- GraalVM: 19.3.1 
 - Java: 11.0.5
 - OS: Win10 pro 
 - Quarkus: 1.2.0.Final
 - repo: https://github.com/tdevilleduc/code-with-quarkus.git

I'm working currently on Quarkus, and i've manage to build a native image with -Dquarkus.native.container-runtime=docker parameter
I want now to make the same without this parameter

I started back from [generating my application][1] and i'm following [building native image tutorial][2]
Problem : I get this error message

    [INFO] --- quarkus-maven-plugin:1.2.0.Final:build (default) @ code-with-quarkus ---
    [INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Final
    [INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: c:\Users\devil\Documents\repository\code-with-quarkus\target\code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar\code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
    [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from c:\Users\devil\Documents\repository\code-with-quarkus\target\code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar\code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
    [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version dev
    [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] C:\Program Files\Tools\graalvm\graalvm-ce-java11-19.3.1\bin\native-image.cmd -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar code-with-quarkus-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:+JNI -H:-UseServiceLoaderFeature -H:+StackTrace code-with-quarkus-1.0.0-SNAPSHOT-runner
    Warning: the '=' character in program arguments is not fully supported.
    Make sure that command line arguments using it are wrapped in double quotes.
    Example:
    "--vm.Dfoo=bar"
    
    Error: Unknown arguments: org.jboss.logmanager.LogManager, io.quarkus.vertx.core.runtime.VertxLogDelegateFactory, true, DISABLED, 1, com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime, 0, http, code-with-quarkus-1.0.0-SNAPSHOT-runner
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  11.930 s
    [INFO] Finished at: 2020-02-12T21:51:49+01:00
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.2.0.Final:build (default) on project code-with-quarkus: Failed to build a runnable JAR: Failed to augment application classes: Build failure: Build failed due to errors
    [ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image

I've try to add all theses args in quarkus.native.additional-build-args in application.properties but it didn't change at all

  [1]: https://code.quarkus.io/
  [2]: https://quarkus.io/guides/building-native-image

**Comment by famod** [comment]
Did you have a look at #5675?

**Comment by tdevilleduc** [comment]
> Did you have a look at #5675?

Oops! That's indeed quite the same problem
As I understand: 
> Just to be clear: we don't support 19.3 yet. The work is in progress.
19.3 is not support yet :)

> packaging the default app from https://code.quarkus.io on Windows with 19.2.1 fails with the same error from native-image.cmd returning non-zero:
5675 is still tracking the issue with 19.2
But it's a Graalvm issue and it seems like it hasn't been reported yet in graal repo

I've tried with 19.2.1 and it does failed silently

**Comment by famod** [comment]
GraalVM 19.3.1 is supported since Quarkus 1.2.0: https://quarkus.io/blog/quarkus-1-2-0-final-released/

You could check whether this applies also to your case: https://github.com/quarkusio/quarkus/issues/5675#issuecomment-578878630
If yes then we have more proof that Quarkus should add extra quotes (`"`).

Beware that if running the command manually (like I did in #5675) you might run in to https://github.com/oracle/graal/issues/1675 and ultimatively https://github.com/oracle/graal/issues/1160

**Comment by tdevilleduc** [comment]
> You could check whether this applies also to your case: #5675 (comment)
I tried this and I think I have the same result as you are

```
$ C:\tools\graalvm\graalvm-ce-java11-windows-amd64-19.3.1\graalvm-ce-java11-19.3.1\bin\native-image.cmd "-J-Dsun.nio.ch.maxUpdateArraySize=100" "-J-Djava.util.logging.manager=org.jboss.logmanager.LogManager" "-J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory" "-J-Dvertx.disableDnsResolver=true" "-J-Dio.netty.leakDetection.level=DISABLED" "-J-Dio.netty.allocator.maxOrder=1" "--initialize-at-build-time=" "-H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime" -jar code-with-quarkus-1.0.0-SNAPSHOT-runner.jar "-H:FallbackThreshold=0" -H:+ReportExceptionStackTraces -H:-AddAllCharsets "-H:EnableURLProtocols=http" -H:+JNI -H:-UseServiceLoaderFeature -H:+StackTrace code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
Warning: the '=' character in program arguments is not fully supported.
Make sure that command line arguments using it are wrapped in double quotes.
Example:
"--vm.Dfoo=bar"

[code-with-quarkus-1.0.0-SNAPSHOT-runner.jar:15256]    classlist:   4,091.53 ms
[code-with-quarkus-1.0.0-SNAPSHOT-runner.jar:15256]        (cap):     365.70 ms
[code-with-quarkus-1.0.0-SNAPSHOT-runner.jar:15256]        setup:     671.59 ms
Error: Unable to compile C-ABI query code. Make sure native software development toolchain is installed on your system.
com.oracle.svm.core.util.UserError$UserException: Unable to compile C-ABI query code. Make sure native software development toolchain is installed on your system.
        at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.compileAndParseError(CCompilerInvoker.java:93)
        at com.oracle.svm.hosted.c.CAnnotationProcessor.compileQueryCode(CAnnotationProcessor.java:131)
        at com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:84)
        at com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:377)
        at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1517)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:835)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.io.IOException: Cannot run program "CL" (in directory "C:\Users\xkhs241\AppData\Local\Temp\SVM-8284886135592304503"): CreateProcess error=2, Le fichier spécifié est introuvable
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.startCommand(CCompilerInvoker.java:146)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.startCompiler(CCompilerInvoker.java:128)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.compileAndParseError(CCompilerInvoker.java:69)
        ... 14 more
Caused by: java.io.IOException: CreateProcess error=2, Le fichier spécifié est introuvable
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 18 more
Error: Image build request failed with exit status 1
```

Apparently I need to install windows-sdk-7.1
This is all new to me. I will try to read stuff before jumping into that

> If yes then we have more proof that Quarkus should add extra quotes (").
Yes I think so too.

Anyway, I can close this one because it's tracked by #5675
