### ISSUE TITLE
The native runner with Mariadb extension fails to run

### ISSUE THREAD

**Issue by kameshsampath** [quarkusio/quarkus#7221]
**Describe the bug**
Building a Hibernate panache application using Mariadb backend is not able to run in native mode and it fails with the following error.

**Expected behavior**
The application should start successfully.

**Actual behavior**
```java.lang.NoSuchFieldException: user
        at java.lang.Class.getField(DynamicHub.java:992)
        at org.mariadb.jdbc.util.DefaultOptions.parse(DefaultOptions.java:869)
        at org.mariadb.jdbc.util.DefaultOptions.parse(DefaultOptions.java:853)
        at org.mariadb.jdbc.UrlParser.defineUrlParserParameters(UrlParser.java:259)
        at org.mariadb.jdbc.UrlParser.parseInternal(UrlParser.java:219)
        at org.mariadb.jdbc.UrlParser.parse(UrlParser.java:174)
        at org.mariadb.jdbc.MariaDbDataSource.initialize(MariaDbDataSource.java:496)
        at org.mariadb.jdbc.MariaDbDataSource.getConnection(MariaDbDataSource.java:272)
        at org.mariadb.jdbc.MariaDbDataSource.getXAConnection(MariaDbDataSource.java:453)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:206)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:390)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:372)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)```

**To Reproduce**
Steps to reproduce the behavior:
1.  The project related to issue is here https://github.com/kameshsampath/issue-7221
2.  Start a mariadb database 
3.  Update the application properties for mariadb config
4.  mvn -Pnative clean package 
5.  Run the native binary

**Comment by gsmet** [comment]
Which version of Quarkus? There's no link to the project.

**Comment by kameshsampath** [comment]
@gsmet  - just updated, its v1.2.0.Final

**Comment by kameshsampath** [comment]
@Sanne  ^^

**Comment by gsmet** [comment]
Can you try 1.3.0.Alpha1? I think it's probably fixed by https://github.com/quarkusio/quarkus/pull/6815 .

**Comment by kameshsampath** [comment]
let me quickly and update

**Comment by kameshsampath** [comment]
@gsmet - I can confirm that #6815  has fixed this issue with bumping quarkus-jdbc-mariadb to `1.3.0.Alpha1`

**Comment by gsmet** [comment]
Thanks.

**Comment by Sanne** [comment]
nice. thanks all!
