### ISSUE TITLE
1.3.0.Alpha2: Kubernetes Client: Could not initialize class KubernetesDeserializer in dev mode

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#7276]
**Describe the bug**
My previously working code, which is getting the currently running deployments via the Quarkus Kubernetes Client, throws the exception below when run in dev mode (`./gradlew quarkusDev`). This happens with Quarkus 1.3.0.Alpha2 and worked with 1.2 and 1.2.1 (it does not compile with 1.3.0.Alpha1 due to unresolved artifacts). I attached a minimized reproducer project below.

Exception:

```
2020-02-19 10:55:06,901 SEVERE [com.tes.qua.DoKubernetesRequestOnStartService] (ForkJoinPool.commonPool-worker-19) Failed to checkForImageUpdates(): java.util.ServiceConfigurationError: io.fabric8.kubernetes.api.KubernetesResourceMappingProvider: io.fabric8.kubernetes.internal.InternalResourceMappingProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1236)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.<clinit>(KubernetesDeserializer.java:66)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.fasterxml.jackson.databind.util.ClassUtil.createInstance(ClassUtil.java:560)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.deserializerInstance(DefaultDeserializationContext.java:229)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findDeserializerFromAnnotation(DeserializerCache.java:427)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:326)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:466)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:443)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:183)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:650)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:484)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:466)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4389)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4198)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfigFromString(KubeConfigUtils.java:45)
	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:509)
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:495)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:230)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:214)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:225)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer.config(KubernetesClientProducer.java:22)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_config_769359a66d09d91814aa0b2d43da90c837fd305c_Bean.create(KubernetesClientProducer_ProducerMethod_config_769359a66d09d91814aa0b2d43da90c837fd305c_Bean.zig:76)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_config_769359a66d09d91814aa0b2d43da90c837fd305c_Bean.create(KubernetesClientProducer_ProducerMethod_config_769359a66d09d91814aa0b2d43da90c837fd305c_Bean.zig:236)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_config_769359a66d09d91814aa0b2d43da90c837fd305c_Bean.get(KubernetesClientProducer_ProducerMethod_config_769359a66d09d91814aa0b2d43da90c837fd305c_Bean.zig:135)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_config_769359a66d09d91814aa0b2d43da90c837fd305c_Bean.get(KubernetesClientProducer_ProducerMethod_config_769359a66d09d91814aa0b2d43da90c837fd305c_Bean.zig:91)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_a22f7caa17bd98380e4f38d941de1bca98b44f84_Bean.create(KubernetesClientProducer_ProducerMethod_kubernetesClient_a22f7caa17bd98380e4f38d941de1bca98b44f84_Bean.zig:204)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_a22f7caa17bd98380e4f38d941de1bca98b44f84_Bean.create(KubernetesClientProducer_ProducerMethod_kubernetesClient_a22f7caa17bd98380e4f38d941de1bca98b44f84_Bean.zig:255)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_a22f7caa17bd98380e4f38d941de1bca98b44f84_Bean.get(KubernetesClientProducer_ProducerMethod_kubernetesClient_a22f7caa17bd98380e4f38d941de1bca98b44f84_Bean.zig:299)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_a22f7caa17bd98380e4f38d941de1bca98b44f84_Bean.get(KubernetesClientProducer_ProducerMethod_kubernetesClient_a22f7caa17bd98380e4f38d941de1bca98b44f84_Bean.zig:327)
	at com.test.quarkus.KubernetesHelpersService_Bean.create(KubernetesHelpersService_Bean.zig:55)
	at com.test.quarkus.KubernetesHelpersService_Bean.create(KubernetesHelpersService_Bean.zig:187)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at com.test.quarkus.KubernetesHelpersService_ClientProxy.arc$delegate(KubernetesHelpersService_ClientProxy.zig:125)
	at com.test.quarkus.KubernetesHelpersService_ClientProxy.getDeployments(KubernetesHelpersService_ClientProxy.zig:170)
	at com.test.quarkus.DoKubernetesRequestOnStartService.checkForImageUpdates(DoKubernetesRequestOnStartService.java:49)
	at com.test.quarkus.DoKubernetesRequestOnStartService.lambda$onStart$0(DoKubernetesRequestOnStartService.java:33)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Expected behavior**
My code should work. 

**Actual behavior**
The code crashes when it tries to retrieve the currently running deployments. This happens in a method called by observing the `StartupEvent` as well as in the health check. I was able to find two workarounds, both shown in the reproducer in the class `DoKubernetesRequestOnStartService` and marked with comments starting with `FIX 1` and `FIX 2`. See the reproduction steps below.

**To Reproduce**
1. Download the reproducer project 
[quarkus-kubernetes-client-deserializer-missing.zip](https://github.com/quarkusio/quarkus/files/4224324/quarkus-kubernetes-client-deserializer-missing.zip)
 and unpack it.
2. In the project directory, execute `./gradlew quarkusDev`
3. When the server is started, the log will display the exception shown above.
4. The same happens if you, call the health endpoint by querying GET `http://localhost:8080/health`.

5. Workaround 1: When you comment in line DoKubernetesRequestOnStartService:24 (marked with comment `FIX 1: ...`), the number of deployments will be retrieved on start. Also the health check will work.
6. Woraround 2: When you instead comment in the lines DoKubernetesRequestOnStartService:41-45 (marked with comment `FIX 2: ...`) and start the server, the initial retrieval of the deployments is delayed by 5 seconds. If you call the health endpoint during this time frame, it will all work fine. If you do not call the health endpoint in these 5 seconds, the same exception will be thrown as before and the health check will also not work afterwards.

**Configuration**
None

**Environment (please complete the following information):**
 - Windows 10
 - Same for Oracle JDK 1.8.0_231 and Oracle JDK 11.0.4
 - Default of Quarkus 1.3.0.Alpha2
 - Quarkus version or git rev: Quarkus 1.3.0.Alpha2. Works with 1.2.0 and 1.2.1
 - Kubernetes on Docker for Windows (simply activated in the UI)

**Comment by stuartwdouglas** [comment]
So the issue here is the use of CompletableFuture.runAsync. This uses the fork join pool which does not provide any way to set the context class loader, so if you attempt to load a service it will use the wrong CL.

I am still trying to figure out a way to resolve this, but I can't really see any except for nasty hacks that may stop working in future versions of Java.

You can work around this by calling Thread.currentThread().setContextClassLoader(DoKubernetesRequestOnStartService.class.getClassLoader()); at the start of the async task.

**Comment by andreas-eberle** [comment]
Thanks for the super fast feedback and workaround. I also found that creating a new Thread (instead of calling CompleteableFuture.runAsync) works as well. Still, I wonder why the same code works with quarkus 1.2 then. Shouldn't it not work their as well?

**Comment by stuartwdouglas** [comment]
It was not an isolated class loader, so even though the TCCL was wrong the effects of a wrong TCCL were not as bad. 

I have an idea for how to fix the TCCL, I am just testing it now.

**Comment by andreas-eberle** [comment]
Cool! Thanks a lot!
