### ISSUE TITLE
Windows build failing with file being used by other process in dev mode

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#7308]
```
[ERROR] shouldNotDisplayDeletedFileIn404ErrorPage  Time elapsed: 4.158 s  <<< ERROR!
9030
java.io.UncheckedIOException: 
9031
java.nio.file.FileSystemException: D:\a\quarkus\quarkus\extensions\resteasy\deployment\target\quarkus-dev-mode-test2251373101877500547\src\main\resources\META-INF\resources\test.html: The process cannot access the file because it is being used by another process.
9032

9033
	at io.quarkus.test.QuarkusDevModeTest.deleteResourceFile(QuarkusDevModeTest.java:443)
9034
	at io.quarkus.resteasy.test.NotFoundExceptionMapperTestCase.shouldNotDisplayDeletedFileIn404ErrorPage(NotFoundExceptionMapperTestCase.java:86)
9035
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
9036
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
9037
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
9038
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by geoand** [comment]
Saw that one as well unfortunately...

**Comment by geoand** [comment]
I have not seen in this in ages, so let's close for now
