### ISSUE TITLE
Infinispan cache JPA tests still failing from time to time

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#731]
Just had this one on CI:

```
2019-02-02T13:15:58.0732707Z   Actual: Oops, shit happened, No boot for you! java.lang.RuntimeException: [org.jboss.shamrock.example.infinispancachejpa.Country] expected Counts{puts=1, hits=0, misses=1, numElements=1} second level cache count, instead got: Counts{puts=1, hits=0, misses=1, numElements=2}
2019-02-02T13:15:58.0733096Z 	java.lang.RuntimeException: [org.jboss.shamrock.example.infinispancachejpa.Country] expected Counts{puts=1, hits=0, misses=1, numElements=1} second level cache count, instead got: Counts{puts=1, hits=0, misses=1, numElements=2}
2019-02-02T13:15:58.0733475Z 	at org.jboss.shamrock.example.infinispancachejpa.InfinispanCacheJPAFunctionalityTestEndpoint.assertCountEquals(InfinispanCacheJPAFunctionalityTestEndpoint.java:735)
2019-02-02T13:15:58.0734341Z 	at org.jboss.shamrock.example.infinispancachejpa.InfinispanCacheJPAFunctionalityTestEndpoint.assertRegionStats(InfinispanCacheJPAFunctionalityTestEndpoint.java:718)
2019-02-02T13:15:58.0737039Z 	at org.jboss.shamrock.example.infinispancachejpa.InfinispanCacheJPAFunctionalityTestEndpoint.verifyFindCountryByNaturalId(InfinispanCacheJPAFunctionalityTestEndpoint.java:157)
2019-02-02T13:15:58.0737421Z 	at org.jboss.shamrock.example.infinispancachejpa.InfinispanCacheJPAFunctionalityTestEndpoint.testMaxIdle(InfinispanCacheJPAFunctionalityTestEndpoint.java:115)
2019-02-02T13:15:58.0737778Z 	at org.jboss.shamrock.example.infinispancachejpa.InfinispanCacheJPAFunctionalityTestEndpoint.doStuffWithHibernate(InfinispanCacheJPAFunctionalityTestEndpoint.java:72)
2019-02-02T13:15:58.0738111Z 	at org.jboss.shamrock.example.infinispancachejpa.InfinispanCacheJPAFunctionalityTestEndpoint.doGet(InfinispanCacheJPAFunctionalityTestEndpoint.java:47)
```

**Comment by gsmet** [comment]
This one has been fixed.
