### ISSUE TITLE
CodeFlowTest failing from time to time on CI

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#7340]
I just had the following issue on a CI build:
```
[INFO] Running io.quarkus.it.keycloak.CodeFlowTest
1247
2020-02-21 16:37:37,356 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 2.445s. Listening on: http://0.0.0.0:8081
1248
2020-02-21 16:37:37,358 INFO  [io.quarkus] (main) Profile test activated. 
1249
2020-02-21 16:37:37,358 INFO  [io.quarkus] (main) Installed features: [cdi, oidc, resteasy, resteasy-jackson, security]
1250
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 27.069 s <<< FAILURE! - in io.quarkus.it.keycloak.CodeFlowTest
1251
[ERROR] testAccessAndRefreshTokenInjection  Time elapsed: 1.064 s  <<< ERROR!
1252
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: Too much redirect for http://localhost:8081/web-app?state=b6bf7d1d-c735-4080-bdf9-0c0d69ba188b&session_state=a0f0d74f-7745-4260-880a-e12d2a84eb31&code=564b2012-fcff-4346-a811-0858b7180bd3.a0f0d74f-7745-4260-880a-e12d2a84eb31.0867fd4e-8b55-4575-81d0-6e150b36fbc2
1253
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1450)
1254
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1465)
1255
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1465)
1256
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1465)
1257
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1465)
1258
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1465)
1259
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1465)
1260
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1465)
1261
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1465)
```

**Comment by sberyozkin** [comment]
Hi @gsmet So far I can only confirm that it might happen in CI with this test. @pedroigor was looking into it, I believe there might be few extra options for optimizing HtmlUnit. The other thing is that this issue, #6802, is what the above stacktrace demonstrates. So I'll try to tackle #6802, and so when the problem occurs then there will be more logging info available.
Thanks

**Comment by geoand** [comment]
I don't know if anything had changed, but I haven't seen this error in the last PRs I've looked at

**Comment by sberyozkin** [comment]
After looking into it yesterday I can confirm this `Too much redirect` issue can happen if `quarkus-oidc` does not detect a `state` cookie when the user (html unit) is returned back from Keycloak. I don't see right now any technical possibility of this happening due to the `quarkus-oidc` fault - it always adds a `state` cookie without any conditions (the only variation is the content of that cookie) and this cookie lifetime is 30 mins which more than enough for a given test.
I do think it is the html unit issue, and particularly of its cookie manager which occasionally loses a cookie in CI and fails to return it to Quarkus.

**Comment by sberyozkin** [comment]
This test will not be failing with 401 when the cookie is not found

**Comment by galderz** [comment]
@sberyozkin An earlier test run of the issue at hand failed with a 401: https://github.com/quarkusio/quarkus/pull/8696#issuecomment-618250862

**Comment by galderz** [comment]
Shall I create a new issue for this flaky test? Or reopen this one?
