### ISSUE TITLE
Quarkus : JPA-Mysql Sequence Generation Error

### ISSUE THREAD

**Issue by jd268** [quarkusio/quarkus#7360]
I am creating simple hibernate mysql application with quarkus. Below  is my database conf -

**# datasource configuration**
quarkus.datasource.url=jdbc:mysql://localhost:3306/quarkus_test
quarkus.datasource.driver=com.mysql.cj.jdbc.Driver
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQL8Dialect
quarkus.datasource.username=demo
quarkus.datasource.password=demo
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.statistics=true
quarkus.hibernate-orm.log.sql=true

**I am using import.sql in resources folder with below content -**
INSERT INTO order_table(id, itemName, orderBy, orderDate) VALUES (nextval('hibernate_sequence'), 'TV','01-Jan-2019');

My Entity class is extending PanacheEntity and whole class has only two annotations - @Entity & @Table and constructors for attributes. That's it.

I am running application from eclipse as maven install, it tries to execute test case which fails with below error -

**Below is the error I am facing -**

Caused by: **java.sql.SQLSyntaxErrorException: FUNCTION quarkus_test.nextval does not exist**
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:232)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
	... 73 more

Hibernate: 
    INSERT INTO order_table(id, itemName, orderBy, orderDate) VALUES (nextval('hibernate_sequence'), 'Cricket Bat','17-Nov-2019')
2020-02-22 11:57:14,314 WARN  [org.hib.too.sch.int.ExceptionHandlerLoggedImpl] (main) GenerationTarget encountered exception accepting command : Error executing DDL "INSERT INTO order_table(id, itemName, orderBy, orderDate) VALUES (nextval('hibernate_sequence'), 'Cricket Bat','17-Nov-2019')" via JDBC Statement: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "INSERT INTO order_table(id, itemName, orderBy, orderDate) VALUES (nextval('hibernate_sequence'), 'Cricket Bat','17-Nov-2019')" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applySqlString(SchemaCreatorImpl.java:439)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applyImportSources(SchemaCreatorImpl.java:492)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:180)

**Comment by batashi** [comment]
Hi @jd268 , 
The same issue still persists for 1.10.5. and I couldn't enter ID manually because it will not reserver the ID in 'hibernate_sequence' table.

**Comment by Kino1994** [comment]
¿Any news about this @gsmet ?

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
