### ISSUE TITLE
quarkus-amazon-lambda-http fails in native mode with java.net.UnknownHostException: null

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#7362]
quarkus-amazon-lambda-http fails in native mode with` java.net.UnknownHostException: null`

https://github.com/quarkusio/quarkus/issues/3352 tracked and solved this for dev mode and jvm mode.

Native mode needs additional work. @evanchooly fyi

```
[INFO] Running io.quarkus.qe.NativeMyResourceIT
Executing [/Users/rsvoboda/Downloads/fooBar/target/fooBar-1.0.0-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
2020-02-23 09:26:39,875 INFO  [io.quarkus] (main) fooBar 1.0.0-SNAPSHOT (running on Quarkus 999-SNAPSHOT) started in 0.015s.
2020-02-23 09:26:39,876 INFO  [io.quarkus] (main) Profile prod activated.
2020-02-23 09:26:39,876 INFO  [io.quarkus] (main) Installed features: [amazon-lambda, cdi, resteasy]
2020-02-23 09:26:39,879 ERROR [io.qua.ama.lam.run.AmazonLambdaRecorder] (Lambda Thread) Failed to run lambda: java.net.UnknownHostException: null
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
```

Reproducer:
```
rm -rf fooBar
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=io.quarkus.qe \
    -DprojectArtifactId=fooBar \
    -DprojectVersion=1.0.0-SNAPSHOT \
    -DplatformArtifactId=quarkus-bom \
    -DclassName="io.quarkus.qe.MyResource" \
    -Dextensions="quarkus-amazon-lambda-http"
mvn -f fooBar/pom.xml clean verify -Dnative
```

**Comment by Karm** [comment]
@gsmet @mkouba 




At first it seemed to me that the test native image just misses the ```quarkus-internal.aws-lambda.test-api```
env prop, i.e. ```requestConnection``` in [AmazonLambdaRecorder.java](https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-lambda/runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaRecorder.java#L145) is ```http://null/2018-06-01/runtime/invocation/next``` while debugging the Native image test run. It is supposed to be  ```http://localhost:5387/2018-06-01/runtime/invocation/next```, as in [LambdaResourceManager.java](https://github.com/quarkusio/quarkus/blob/master/test-framework/amazon-lambda/src/main/java/io/quarkus/amazon/lambda/test/LambdaResourceManager.java#L115).


When I tried to hardcode the env prop to give it a try in [NativeImageLauncher.java#L8](https://github.com/quarkusio/quarkus/blob/master/test-framework/common/src/main/java/io/quarkus/test/common/NativeImageLauncher.java#L80) it failed too, because not only env prop is missing, but the whole Undertow server is not started as it should in [LambdaResourceManager](https://github.com/quarkusio/quarkus/blob/master/test-framework/amazon-lambda/src/main/java/io/quarkus/amazon/lambda/test/LambdaResourceManager.java#L110)

```
ERROR [io.qua.ama.lam.run.AmazonLambdaRecorder] (Lambda Thread) KARM: Failed to run lambda: java.net.ConnectException: Connection refused (Connection refused)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_ConnectException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
```

[LambdaResourceManager.java](https://github.com/quarkusio/quarkus/blob/master/test-framework/amazon-lambda/src/main/java/io/quarkus/amazon/lambda/test/LambdaResourceManager.java) is not found in 
[getTestResources in TestResourceManager.java](https://github.com/quarkusio/quarkus/blob/master/test-framework/common/src/main/java/io/quarkus/test/common/TestResourceManager.java#L95); although it is picked up from [META-INF/services](https://github.com/quarkusio/quarkus/blob/master/test-framework/amazon-lambda/src/main/resources/META-INF/services/io.quarkus.test.common.QuarkusTestResourceLifecycleManager) in JVM mode.

## Question

What would be an idiomatic way of adding LambdaResourceManager so as in 

```
TestResourceManager testResourceManager = new TestResourceManager(extensionContext.getRequiredTestClass());
```

```testResourceManager.testResources``` isn't always an empty collection in native test? See [NativeTestExtension.java#L54](https://github.com/quarkusio/quarkus/blob/master/test-framework/junit5/src/main/java/io/quarkus/test/junit/NativeTestExtension.java#L54).

**Comment by patriot1burke** [comment]
What exactly is failing here?  It fails when deploying to AWS as per the documentation?  Native build cannot be run outside of AWS Lambda environment.

**Comment by Karm** [comment]
@patriot1burke Test is failing.  The test native image should have the fake server from [LambdaResourceManager.java](https://github.com/quarkusio/quarkus/blob/master/test-framework/amazon-lambda/src/main/java/io/quarkus/amazon/lambda/test/LambdaResourceManager.java#L113) baked in it so as the test runs in native mode.

Perhaps I could do it via some annotation in my 
```
@NativeImageTest
public class NativeMyResourceIT extends MyResourceTest {
    // Execute the same tests but in native mode.
}
```
???

**Comment by stuartwdouglas** [comment]
Have you actually added a dependency on quarkus-test-amazon-lambda ?

**Comment by rsvoboda** [comment]
You mean adding
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-test-amazon-lambda</artifactId>
      <version>${quarkus.platform.version}</version>
      <scope>test</scope>
    </dependency>
```
?

I get
```
2020-03-12 10:01:11,029 ERROR [io.qua.ama.lam.run.AmazonLambdaRecorder] (Lambda Thread) Failed to run lambda: java.net.SocketException: Connection reset

WARN: Failed to register an accepted channel: [id: 0xa4275fde, L:0.0.0.0/0.0.0.0:5387]

2020-03-12 10:01:11,069 ERROR [io.qua.ama.lam.run.AmazonLambdaRecorder] (Lambda Thread) Error running lambda: java.net.ConnectException: Connection refused (Connection refused)
```

I tried `quarkus/integration-tests/amazon-lambda-http` in native mode and tests are passing, there are some errors in console
```
[INFO] Running io.quarkus.it.amazon.lambda.AmazonLambdaSimpleIT
Executing [/Users/rsvoboda/git/quarkus/integration-tests/amazon-lambda-http/target/quarkus-integration-test-amazon-lambda-http-999-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log, -Dquarkus-internal.aws-lambda.test-api=localhost:5387]

           ██████╗ ██╗   ██╗ █████╗ ██████╗ ██╗  ██╗██╗   ██╗███████╗    ██╗
██╗██╗    ��█╔═══██╗██║   ██║██╔══██╗██╔══██╗██║ ██╔╝██║   ██║██╔════╝    ╚██╗
╚═╝╚═╝    ██║   ██║██║   ██║███████║██████╔╝███���█╔╝ ██║   ██║███████╗     ╚██╗
██╗██╗    ██║▄▄ ██║██║   ██║██╔══██║██╔══██╗██╔═██╗ ██║   ██║╚════██║     ██╔╝
╚═╝╚═╝    ��██████╔╝╚██████╔╝██║  ██║██║  ██║██��  ██╗╚██████╔╝███████║    ██╔╝
           ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝    ╚═╝
2020-03-12 10:51:13,479 INFO  [io.quarkus] (main) quarkus-integration-test-amazon-lambda-http 999-SNAPSHOT (powered by Quarkus 999-SNAPSHOT) started in 0.013s.
2020-03-12 10:51:13,479 INFO  [io.quarkus] (main) Profile prod activated.
2020-03-12 10:51:13,479 INFO  [io.quarkus] (main) Installed features: [amazon-lambda, cdi, mutiny, resteasy, servlet, vertx, vertx-web]
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.437 s - in io.quarkus.it.amazon.lambda.AmazonLambdaSimpleIT
2020-03-12 10:51:13,965 ERROR [io.qua.ama.lam.run.AmazonLambdaRecorder] (Lambda Thread) Failed to run lambda: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:863)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1610)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3094)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$2.run(AmazonLambdaRecorder.java:159)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

2020-03-12 10:51:13,965 ERROR [io.qua.ama.lam.run.AmazonLambdaRecorder] (Lambda Thread) Error running lambda: java.net.ConnectException: Connection refused (Connection refused)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_ConnectException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.net.Socket.connect(Socket.java:609)
	at java.net.Socket.connect(Socket.java:558)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1362)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1337)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.postResponse(AmazonLambdaRecorder.java:228)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.access$600(AmazonLambdaRecorder.java:38)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$2.run(AmazonLambdaRecorder.java:175)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

2020-03-12 10:51:13,967 INFO  [io.quarkus] (Lambda Thread) quarkus-integration-test-amazon-lambda-http stopped in 0.002s
```

**Comment by mbecca** [comment]
Hi,

I have similar issue when run ./mvnw clean verify -Pnative

 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-05-05 22:55:05,782 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.http.ssl-port" was provided; it will be ignored
2020-05-05 22:55:05,782 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.http.port" was provided; it will be ignored
2020-05-05 22:55:05,786 INFO  [io.quarkus] (main) quarkus-aws-maven-starter 1.0-SNAPSHOT (powered by Quarkus 1.4.2.Final) started in 0.016s.
2020-05-05 22:55:05,786 INFO  [io.quarkus] (main) Profile prod activated.
2020-05-05 22:55:05,786 INFO  [io.quarkus] (main) Installed features: [amazon-lambda, cdi]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.559 s - in com.zinbig.quarkus.aws.starter.test.natives.HelloByNameLambdaIT
2020-05-05 22:55:08,809 ERROR [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread) Failed to run lambda: java.net.SocketException: Unexpected end of file from server
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:863)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1610)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3094)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:50)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

May 05, 2020 10:55:08 PM io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor forceClose
WARN: Failed to register an accepted channel: [id: 0x12d295ed, L:0.0.0.0/0.0.0.0:5387]
java.lang.IllegalStateException
        at io.vertx.core.net.impl.VertxEventLoopGroup.next(VertxEventLoopGroup.java:37)
        at io.vertx.core.net.impl.VertxEventLoopGroup.register(VertxEventLoopGroup.java:53)
        at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:209)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:484)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

**This error is random or no deterministic, but generally happen.**

pom.xml:

<properties>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<surefire-plugin.version>2.22.1</surefire-plugin.version>
		<maven.compiler.parameters>true</maven.compiler.parameters>
		<quarkus.version>1.4.2.Final</quarkus.version>
		<compiler-plugin.version>3.8.1</compiler-plugin.version>
		<maven.compiler.source>11</maven.compiler.source>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.target>11</maven.compiler.target>
	</properties>

Regards,

M.

**Comment by oztimpower** [comment]
Replicated the test per initial comment from @rsvoboda 23/2, and had the same outcome.

I updated the test with versions that are seen in the amazon-lambda-http (and amazon-lambda-http-resteasy) integration tests and got the same output as @rsvoboda 12/3.  Yet these exceptions for JVM and Native are upon shutdown, the tests do actually run.  The run loop in AmazonLambdaRecorder where the native version executes from traps the close and reports the above trace. The JVM flow is slightly different yet still has an exception on LambdaResourceManager.stop().

It would be worth updating the Maven archetype with a version of the test similar to the integration tests, like what was done for the Amazon Lambda Maven archetype. Stack traces on close could be better to suppress this. The Amazon Lambda extension used to have similar stack traces yet they've now gone.

**Comment by oztimpower** [comment]
Submitted PR #9697 to address this.

The Tests must use the AwsProxy (per the integration tests) to work with Quarkus Native Tests.
