### ISSUE TITLE
Submodule not in classpath when running :app:quarkusBuild in a multi-module Gradle project

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#7365]
**Describe the bug**

Running **:app:quarkusBuild** in a multi-module project with a shared module and an application module leads to

` java.lang.NoClassDefFoundError: com/demo/common/model/SharedModel
        at com.demo.application.Application.schedule(Application.java:19)
        at com.demo.application.Application_Subclass.schedule$$superaccessor8(Application_Subclass.zig:21)
        at com.demo.application.Application_Subclass$$function$$8.apply(Application_Subclass$$function$$8.zig:29)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:119)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:92)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:168)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at com.demo.application.Application_Subclass.schedule(Application_Subclass.zig:86)
        at com.demo.application.Application_ClientProxy.schedule(Application_ClientProxy.zig:51)
        at com.demo.application.Application_ScheduledInvoker_schedule_dce0524c3f1de653f83719900424446459b7c471.invokeBean(Application_ScheduledInvoker_schedule_dce0524c3f1de653f83719900424446459b7c471.zig:45)
        at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
        at io.quarkus.scheduler.runtime.SimpleScheduler$2.run(SimpleScheduler.java:123)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
` 

**Expected behavior**

Library classes added to the classpath as well

**Actual behavior**

Classes of the library are **not getting added to the classpath**

**To Reproduce**

Demo Project with the issue and workaround by pre-building the library manually before the application

https://github.com/mklueh/quarkus-multi-module-submodule-classpath-issue

**Comment by geoand** [comment]
cc @gastaldi @aloubyansky

**Comment by mklueh** [comment]
Could s.b. please add the **area/gradle** label to this issue as well?

**Comment by aloubyansky** [comment]
If you try it with Quarkus master, you are going to get the classes of the `common` module copied into the `application` runner jar. However it won't start.
```
2020-02-24 19:18:28,361 INFO  [io.quarkus] (main) application unspecified (running on Quarkus 999-SNAPSHOT) started in 0.497s. 
2020-02-24 19:18:28,389 INFO  [io.quarkus] (main) Profile prod activated. 
2020-02-24 19:18:28,389 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-h2, narayana-jta, scheduler]
2020-02-24 19:18:29,197 ERROR [io.qua.sch.run.SimpleScheduler] (executor-thread-1) Error occured while executing task for trigger IntervalTrigger [id=0_com.demo.application.Application_ScheduledInvoker_schedule_dce0524c3f1de653f83719900424446459b7c471, interval=20000]: javax.persistence.PersistenceException: No EntityManager found. Do you have any JPA entities defined?
        at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.getEntityManager(JpaOperations.java:77)
        at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.persist(JpaOperations.java:28)
        at io.quarkus.hibernate.orm.panache.PanacheEntityBase.persist(PanacheEntityBase.java:43)
        at com.demo.application.Application.schedule(Application.java:24)
	at com.demo.application.Application_Subclass.schedule$$superaccessor1(Application_Subclass.zig:114)
	at com.demo.application.Application_Subclass$$function$$1.apply(Application_Subclass$$function$$1.zig:29)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:119)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:92)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:168)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.demo.application.Application_Subclass.schedule(Application_Subclass.zig:72)
	at com.demo.application.Application_ClientProxy.schedule(Application_ClientProxy.zig:51)
	at com.demo.application.Application_ScheduledInvoker_schedule_dce0524c3f1de653f83719900424446459b7c471.invokeBean(Application_ScheduledInvoker_schedule_dce0524c3f1de653f83719900424446459b7c471.zig:45)
	at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
	at io.quarkus.scheduler.runtime.SimpleScheduler$2.run(SimpleScheduler.java:126)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1411)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

Besides that, what is your expectation @mklueh exactly? Do you expect the `common` classes be copied into the runner jar (like we now do) or build the common jar and add it to the lib?
Thanks.

**Comment by mklueh** [comment]
@aloubyansky thanks for the fast response.

Could you reproduce the issue with Quarkus 1.2.1 that I´m using in the demo project? My expectation was that I won´t have to build the library module separately in order to get a functional archive out of the build.

> Do you expect the common classes be copied into the runner jar (like we now do) or build the common jar and add it to the lib?

I´d have expected it to be part of the runner, but I personally don´t care if it´s a separate library. In the case of the demo project it´s neither part of the runner, nor loaded as a separate .jar, only if I build the library manually beforehand.


> javax.persistence.PersistenceException: No EntityManager found. Do you have any JPA entities defined?

I had that issue once when there was no entity available in the **application module** but only in the library module, the entity manager could not be loaded. Could you please test it again with an additional entity in the application module?

**Comment by aloubyansky** [comment]
Yes, I was able to reproduce your issue with 1.2.1.Final and thanks a lot for making the reproducer available!
There are two way to fix this issue from the application assembly perspective. One would be to copy the classes from the `common` module into the runner JAR. The other way would be to build the `common` module as a JAR and copy it to the `application`'s `lib`dir. My question about your expectation was about which one of those you preferred. Correct me if I'm wrong, as I understood, you don't have a preference.
Note, that if you build the whole project with `buildQuarkus` you will get `common` JAR in the `lib`. My question is about the scenario when you build the app in your script that's failing.
About the entity not being recognized, that looks like an indexing issue that I'm going to look into next.

**Comment by mklueh** [comment]
@aloubyansky good to hear. I don´t have a preference, but I´d probably argue in favour of the .jar variant if it has any impact on build speed in case shared module jars could be cached


> Note, that if you build the whole project with buildQuarkus you will get common JAR in the lib.

Do I understand that correctly that building the application, and building the whole project have two different outcomes? 
Would I have the commons in my jar as well as the commons jar in my libs when I would build the whole project, and afterwards just the application and wouldn´t that lead to duplicate class exceptions?

**Comment by aloubyansky** [comment]
> Do I understand that correctly that building the application, and building the whole project have two different outcomes?

This is currently the case. If you don't build `common` explicitly, `application`'s runner JAR will contain its classes. However, if you build the whole project or `common` explicitly, `application` will use its classes from the JAR.
Just to make it clear, I am not arguing this is how it should be. I'm just saying there are two ways to make it work and this is how it is working, atm. That wasn't a design decision, it was consequence of implementing another feature.
I will probably look into properly configuring task deps to always build `common` JAR. It's just given the number of tasks to work on, I need to make up the priorities.

**Comment by aloubyansky** [comment]
Looking more into this, I think wrote some rubbish up there. #7441 should fix this kind of issue. It certainly fixed the project you shared. Thanks a lot for providing it as a reproducer. This really helps a lot.

**Comment by mklueh** [comment]
@aloubyansky No problem, thanks for helping that quickly. I'm looking forward to the next release :)
