### ISSUE TITLE
reactive-messaging-amqp extension doesn't reconnect to host

### ISSUE THREAD

**Issue by Markus-Schwer** [quarkusio/quarkus#7404]
**Describe the bug**
I use the `quarkus-smallrye-reactive-messaging-amqp` extension and expect the extension to be able to reconnect to my ActiveMQ Artemis broker, if the connection is lost or Atemis restarts. As the extension (or rather the smallrye dependency) provides the properties `amqp-reconnect-attempts` and `amqp-reconnect-interval` i expect them to be responsible for the behaviour I want. Am i missing something?
But, if I stop Artemis while my quarkus application is still connected, it doesn't even try to reconnect.

**Expected behavior**
When stopping the AMQP message broker and starting it again shortly after, i expect quarkus to reconnect automatically.

**Actual behavior**
Two proton events are fired (see screenshot) and nothing happens.

**To Reproduce**
1.  Clone the [amqp-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/master/amqp-quickstart) directory and edit the `application.properties` according to the configuration shown below.
2. Start artemis with the docker-compose file
3. Start the quarkus application
4. Stop and restart the artemis container

**Configuration**
```properties
quarkus.log.level=FINEST

# Configures the AMQP broker credentials.
amqp-username=quarkus
amqp-password=quarkus
amqp-reconnect-attempts=100
amqp-reconnect-interval=1000

# Configure the AMQP connector to write to the `prices`  address
mp.messaging.outgoing.generated-price.connector=smallrye-amqp
mp.messaging.outgoing.generated-price.address=prices
mp.messaging.outgoing.generated-price.durable=true

# Configure the AMQP connector to read from the `prices` queue
mp.messaging.incoming.prices.connector=smallrye-amqp
mp.messaging.incoming.prices.durable=true
```

**Screenshots**
![grafik](https://user-images.githubusercontent.com/22277361/75222896-92a92380-57a5-11ea-94b8-88a4247ab72b.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux nbell02976 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: `openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode)`
 - GraalVM version (if different from Java): -
 - Quarkus version or git rev: `1.2.1.Final`

**Additional context**
This also happens if there is a network error, not only when artemis is restarted.

**Comment by mvlach** [comment]
I have the same issue. 

```
2020-02-25 10:25:47,383 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /prices failed, error id: 09c154b9-584c-4011-a22e-39a1b5e0aea9-5: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalStateException: Stream has been terminated
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:120)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:85)
        at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:224)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Comment by geoand** [comment]
cc @cescoffier

**Comment by Markus-Schwer** [comment]
Any updates on this?

**Comment by cescoffier** [comment]
Unfortunately, the reconnect options are about TCP reconnection, not the broker reconnection. There is some ongoing work about that upstream (CC @gemmellr )

**Comment by gemmellr** [comment]
To be clear, the underlying options ultimately exposed here come straight from the Vert.x NetClient [1], and those are not really about *re*-connection as such at all, they influence behaviour between the initial connect call and what happens before it indicates success or failure to connect. After that, vertx-proton indicates when the AMQP connection is closed and/or NetClient indicates the TCP connection drops, but it doesnt do reconnect itself. Things built on top of it such as vertx-amqp-client, and in turn reactive-messaging-amqp, need to use those indicators themselves.

[1] https://github.com/eclipse-vertx/vert.x/blob/3.9.0/src/main/java/io/vertx/core/net/NetClientOptions.java#L288-L315

**Comment by BobClaerhout** [comment]
Can we have a work around for this? Maybe it's an option to build and inject the AmqpConnection yourself and listen for the disconnect event and reconnect yourself?

**Comment by cescoffier** [comment]
Fixed by https://github.com/smallrye/smallrye-reactive-messaging/pull/549.
