### ISSUE TITLE
Unsupported type MethodAccessorGenerator reachable error

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#7422]
quarkus master (bbb2329ae) w/ graal master (https://github.com/oracle/graal/commit/ee232b09e21e) failing with Java 11 in `integration-tests/optaplanner-jackson`:

```
$ mvn clean install -Dnative -pl integration-tests/optaplanner-jackson
...
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor):
	at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1516)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:81)
	at sun.security.pkcs11.SunPKCS11.initToken(SunPKCS11.java:1028)
	at sun.security.pkcs11.SunPKCS11$TokenPoller.run(SunPKCS11.java:852)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

Console output can be found [here](https://gist.github.com/galderz/b57a0d7f8214348649c2541fa488c8f2).

**Comment by galderz** [comment]
I suspect that this is caused by https://github.com/oracle/graal/commit/eab7e93b585febf7c2c68948af70157732767963

**Comment by galderz** [comment]
The call path does not appear to be under Quarkus control, so I've opened a bug in https://github.com/oracle/graal/issues/2192

**Comment by galderz** [comment]
Btw, I added `--report-unsupported-elements-at-runtime` during image building time but then it didn't fail at runtime.

**Comment by galderz** [comment]
I've tried to do a basic substitution:

```java
@TargetClass(java.io.ObjectStreamClass.class)
final class Target_java_io_ObjectStreamClass {

    @Alias private Long suid;

    @Substitute
    public long getSerialVersionUID() {
        if (suid != null) {
            return suid;
        }

        return 1L;
    }
}
```

But that's not enough, it would then fail with:

```

Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor):
	at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1516)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:81)
	at jdk.internal.module.IllegalAccessLogger.codeSource(IllegalAccessLogger.java:325)
	at jdk.internal.module.IllegalAccessLogger.lambda$log$1(IllegalAccessLogger.java:262)
	at jdk.internal.module.IllegalAccessLogger$$Lambda$898/0x00000007c1b68840.get(Unknown Source)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:340)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
```

**Comment by galderz** [comment]
Actually, the above substitution was this potential case:

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor):
	at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1516)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:81)
	at java.io.ObjectStreamClass.getSerialVersionUID(ObjectStreamClass.java:262)
	at java.io.ObjectStreamClass.toString(ObjectStreamClass.java:322)
	at java.lang.String.valueOf(String.java:2951)
	at java.io.PrintStream.print(PrintStream.java:745)
	at java.io.PrintStream.println(PrintStream.java:882)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
```

Clearly there are different ways in which we can arrive at `ObjectStreamClass.getSerializableConstructor` so the above substitution is definitely not the answer.

**Comment by galderz** [comment]
Trying to a substitution to get `ReflectionFactory.generateConstructor()` to return null.

**Comment by galderz** [comment]
The eagerness of points to analysis means that every possible `PriviledgedAction.run()` calls are inspected and that's leading to some paths that do not seem to happen at runtime. Graal team is looking to avoid this. This [PR](https://github.com/oracle/graal/pull/2194) contains a fix I considered but even though it's not the correct fix, the Quarkus native testsuite passes. So, if you need a temporary workaround you could try that.

**Comment by galderz** [comment]
To be clear, what svm is trying to block now is that serialization is not used to create new classes at runtime (see [longer explanation](https://github.com/oracle/graal/commit/eab7e93b585febf7c2c68948af70157732767963)). So, serialization per-se is not being banned, but serialization that can lead to creating classes that are not pre-defined.

**Comment by galderz** [comment]
In case people miss it, there's been a PR open for this for over a month: #7903
