### ISSUE TITLE
Constructor Injection in secured JAX-RS resources leads to exception

### ISSUE THREAD

**Issue by CrystalMethod** [quarkusio/quarkus#7495]
**Describe the bug**
Constructor Injection in secured (`@Authenticated`) JAX-RS resources leads to exception.

**Expected behavior**
Constructor Injection should also work for secured JAX-RS Resources. 

**Actual behavior**
```
java.lang.RuntimeException: RESTEASY003190: Could not find constructor for class: bar.foo.AuthorizedMyResource
```

**To Reproduce**

```java
@Authenticated
@Path("/secured")
public class AuthorizedMyResource {

  private final MyService service;

  @Inject
  public AuthorizedMyResource(MyService service) {
    this.service = service;
  }
}
```

```
java.lang.RuntimeException: RESTEASY003190: Could not find constructor for class: de.volkswagen.trackandtrace.scanning.web.rest.AuthorizedScanningResource
        at org.jboss.resteasy.spi.metadata.ResourceBuilder.getConstructor(ResourceBuilder.java:852)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.registered(POJOResourceFactory.java:58)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:247)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:228)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:209)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:193)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:176)
        at org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:88)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.registration(ResteasyDeploymentImpl.java:474)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:289)
        at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:90)
        at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.staticInit(ResteasyStandaloneRecorder.java:86)
        at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit271.deploy_0(ResteasyStandaloneBuildStep$staticInit271.zig:1042)
        at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit271.deploy(ResteasyStandaloneBuildStep$staticInit271.zig:1061)
        at io.quarkus.runner.ApplicationImpl.&lt;clinit&gt;(ApplicationImpl.zig:448)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:153)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:178)
        at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:208)
        at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:137)
        at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:51)
        at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:43)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

But Field Injection works as expected for secured resources:

```java
@Authenticated
@Path("/secured")
public class AuthorizedMyResource {

  @Inject
  myService service;
}
```

**And Constructor Injection even works as expected for unsecured resources:**

```java
@Path("/unsecured")
public class MyResource {

    private final MyService service;

    @Inject
    public MyResource(MyService service) {
      this.service = service;
    }
```

**Environment:**
- Quarkus Framework 1.2.1.Final
- GraalVM CE 19.3.1

**Comment by CrystalMethod** [comment]
relating to #6722?

**Comment by geoand** [comment]
Thanks for reporting!

This is not related to  #6722, it's different. I'll take a look.
