### ISSUE TITLE
NPE on OidcAuthenticationMechanism.isWebApp with elytron-security,keycloak-authorization extensions

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#7561]
Getting `NullPointerException` from io.quarkus.oidc.runtime.OidcAuthenticationMechanism. isWebApp [OidcAuthenticationMechanism.java:36](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcAuthenticationMechanism.java#L36) when running the tests for generated app with elytron-security,keycloak-authorization extensions.

I think there are required parameters to be set - for sure `quarkus.oidc.auth-server-url`

Throwing NPE is a problem.
Quarkus should be a good citizen and inform users about mandatory configuration.

An example of good behavior can be quarkus.oauth2.client-id/client-secret/introspection-url
https://github.com/quarkusio/quarkus/blob/master/extensions/elytron-security-oauth2/runtime/src/main/java/io/quarkus/elytron/security/oauth2/runtime/OAuth2Recorder.java#L36

Reproducer:
```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=io.quarkus.qe \
  -DprojectArtifactId=fooBar_0_13 -DprojectVersion=1.0.0-SNAPSHOT \
  -DplatformArtifactId=quarkus-bom -DclassName="io.quarkus.qe.MyResource" \
  -Dextensions="elytron-security,keycloak-authorization,"

mvn verify -f fooBar_0_13/pom.xml
```

Part of stacktrace:
```
[INFO] Running io.quarkus.qe.MyResourceTest
2020-03-04 13:04:02,234 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 2.288s. Listening on: http://0.0.0.0:8081
2020-03-04 13:04:02,240 INFO  [io.quarkus] (main) Profile test activated.
2020-03-04 13:04:02,241 INFO  [io.quarkus] (main) Installed features: [cdi, keycloak-authorization, oidc, resteasy, security]
2020-03-04 13:04:03,477 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /hello failed, error id: 8c2ed78a-1c48-452f-bcab-ab46689e74f3-1: java.lang.NullPointerException
	at io.quarkus.oidc.runtime.OidcAuthenticationMechanism.isWebApp(OidcAuthenticationMechanism.java:36)
	at io.quarkus.oidc.runtime.OidcAuthenticationMechanism.authenticate(OidcAuthenticationMechanism.java:25)
	at io.quarkus.oidc.runtime.OidcAuthenticationMechanism_ClientProxy.authenticate(OidcAuthenticationMechanism_ClientProxy.zig:226)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator.attemptAuthentication(HttpAuthenticator.java:66)
	at io.quarkus.vertx.http.runtime.security.HttpAuthenticator_ClientProxy.attemptAuthentication(HttpAuthenticator_ClientProxy.zig:150)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1.handle(HttpSecurityRecorder.java:36)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1.handle(HttpSecurityRecorder.java:25)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
```

@sberyozkin something for you ?

**Comment by sberyozkin** [comment]
@rsvoboda The problem is that at the moment we simply return a null `oidcTenantConfig` if the `auth-server-url` is null, that was done to distinguish between available or unavailable tenant configurations, which causes the side-effects. I think we need to introduce a per-tenant specifc 'enabled' property, need to think about it

**Comment by pedroigor** [comment]
Or maybe just add some validations?
