### ISSUE TITLE
Cannot override "quarkus.swagger-ui.always-include" property

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#7594]
**Describe the bug**
Havving quarkus.swagger-ui.always-include=false will not load swagger-ui, if you try to override the property at runtime, the swagger-ui address replies with HTTP 500 at:
http://localhost:8080/swagger-ui/index.html#/

>(executor-thread-1) There was a problem with the request. ErrorPayload(code=404, message=RESTEASY003210: Could not find resource for full path: http://localhost:8080/swagger-ui/index.html, description=RESTEASY003210: Could not find resource for full path: http://localhost:8080/swagger-ui/index.html, fields=null): javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://localhost:8080/swagger-ui/index.html
        at org.jboss.resteasy.core.registry.ClassNode.match(ClassNode.java:70)
        at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:47)
        at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:482)
        at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:323)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:244)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:120)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:85)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1395)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

`

**Expected behavior**
 java -Dquarkus.swagger-ui.always-include=true  -jar target/wfm-timeseries-1.1-SNAPSHOT-runner.jar
Must make swagger ui available at http://localhost:8080/swagger-ui/index.html#/

**Actual behavior**
HTTP 500 error. See stack trace above.

**To Reproduce**
1. Set quarkus.swagger-ui.always-include=false at the application.properties
2. Sstart the server with `java -Dquarkus.swagger-ui.always-include=true  -jar target/wfm-timeseries-1.1-SNAPSHOT-runner.jar`
3. Go to http://localhost:8080/swagger-ui/index.html#/

**Configuration**
```properties
quarkus.swagger-ui.always-include=false
 <quarkus.version>1.2.0.Final</quarkus.version>

```

**Comment by machi1990** [comment]
The swagger ui configuration is build time only and it is not runtime overridable. 
You can enable or disable swagger ui on profile basis as shown here https://quarkus.io/guides/config#configuration-profiles

**Comment by brunobat** [comment]
Thanks @machi1990 but it's not what the documentation says:
![image](https://user-images.githubusercontent.com/2318030/76200304-4b7d5280-61e9-11ea-9957-1a0191635bd9.png)
Either the code or the documentation are wrong.

**Comment by machi1990** [comment]
@brunobat thanks for the feedback. 

The documentation just means that if you want to activate the swagger ui in prod you have to always include it by setting the appropriate property to `true`.

 
Since the swagger-ui configurations are not overridable in runtime i.e (the configs are only used during application build time), you can still activate them via build system props during app packaging as shown below:

If you have in your `application.properties` something like:
```
....
quarkus.swagger-ui.always-include=false 
``` 

```
mvn clean install -Dquarkus.swagger-ui.always-include=true 
java -jar <your-app-runner.jar>
```

**Comment by brunobat** [comment]
Nice! thanks @machi1990 That makes more sense.
Now I think that should probably be clearer in the documentation.
