### ISSUE TITLE
Getting Build Failure with following error while running quarkus project

### ISSUE THREAD

**Issue by vikas326** [quarkusio/quarkus#7635]
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.2.0.Final:build (default) on project helloworld: Failed to build a runnable JAR: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep#setup threw an exception: java.lang.NullPointerException
[ERROR] 	at io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep.setup(ConfigPropertiesBuildStep.java:71)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
[ERROR] 	at io.quarkus.builder.BuildContext$$Lambda$132.000000001307ACD0.run(Unknown Source)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
[ERROR] 	at java.lang.Thread.run(Thread.java:813)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:1.2.0.Final:build (default) on project helloworld: Failed to build a runnable JAR
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to build a runnable JAR
	at io.quarkus.maven.BuildMojo.execute(BuildMojo.java:194)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: io.quarkus.creator.AppCreatorException: Failed to augment application classes
	at io.quarkus.creator.phase.augment.AugmentTask.run(AugmentTask.java:188)
	at io.quarkus.creator.phase.augment.AugmentTask.run(AugmentTask.java:53)
	at io.quarkus.creator.CuratedApplicationCreator.runTask(CuratedApplicationCreator.java:139)
	at io.quarkus.maven.BuildMojo.execute(BuildMojo.java:178)
	... 22 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep#setup threw an exception: java.lang.NullPointerException
	at io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep.setup(ConfigPropertiesBuildStep.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
	at io.quarkus.builder.BuildContext$$Lambda$132.000000001307ACD0.run(Unknown Source)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:813)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

	at io.quarkus.builder.Execution.run(Execution.java:108)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:128)
	at io.quarkus.creator.phase.augment.AugmentTask.run(AugmentTask.java:179)
	... 25 more
Caused by: java.lang.NullPointerException
	at io.quarkus.arc.deployment.configproperties.ConfigPropertiesBuildStep.setup(ConfigPropertiesBuildStep.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
	at io.quarkus.builder.BuildContext$$Lambda$132.000000001307ACD0.run(Unknown Source)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:813)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

**Comment by vikas326** [comment]
I am trying to convert a jhipster generated project to quarkus. The above error is coming while running the command "mvn clean install -X". The same NullPointerException also comes when I try to run the project with command "mvn compile quarkus:dev".

**Comment by SR-Lut3t1um** [comment]
Sounds like you hav a config issue, whats inside your application.propperties?

**Comment by gsmet** [comment]
Are you using the exact same version for the Quarkus Maven plugin and the Quarkus BOM?

It looks like the type of error you have when the 2 versions don't match.

**Comment by vikas326** [comment]
I am also getting the warning message with the above error.


[WARNING] [1m[[0;36mio.quarkus.creator.curator.Curator[0;1m][m These dependencies are not recommended:
	- javax.activation:javax.activation-api should be replaced by jakarta.activation:jakarta.activation-api
	- javax.annotation:javax.annotation-api should be replaced by jakarta.annotation:jakarta.annotation-api
	- javax.persistence:javax.persistence-api should be replaced by jakarta.persistence:jakarta.persistence-api
	- javax.transaction:javax.transaction-api should be replaced by jakarta.transaction:jakarta.transaction-api
	- javax.validation:validation-api should be replaced by jakarta.validation:jakarta.validation-api
	- javax.xml.bind:jaxb-api should be replaced by org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec
	- org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec should be replaced by jakarta.servlet:jakarta.servlet-api
	- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec should be replaced by jakarta.transaction:jakarta.transaction-api
You might end up with two different versions of the same classes or with an artifact you shouldn't have in your classpath.

**Comment by vikas326** [comment]
> Are you using the exact same version for the Quarkus Maven plugin and the Quarkus BOM?
> 
> It looks like the type of error you have when the 2 versions don't match.

@gsmet They both have same version. Then also it is showing this error

**Comment by vikas326** [comment]
@SR-Lut3t1um 
I have added yaml support in the pom.xml file of the project. And affter that I made a application.yaml file and copy pasted the data to it from the application-dev.yaml file(i.e. used by jhipster ). Apart from that I have also added the quarkus properties in that file in the yaml file format. Then also it is showing the same error. After that I removed the application.properties file from the resources folder and then also it is showing the same error.
I will paste the content of application.yaml file after some time.

**Comment by vikas326** [comment]
@SR-Lut3t1um 
application.yaml file

#Quarkus properties
"%dev":
  quarkus:
    datasource:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/helloworld
      username: postgres
      password: postgres
    application:
      name: helloworld


quarkus:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/helloworld
    username: postgres
    password: postgres
  application:
    name: helloworld



spring:
  jpa:
    properties:
      hibernate.format_sql: true




# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    com.demo.jhipster: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/helloworld
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: io.github.jhipster.domain.util.FixedPostgreSQL10Dialect
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 8080

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  security:
    remember-me:
      # security key (this key should be unique for your application, and kept secret)
      key: 6715375b2b33c99548b622955216a66e395c859fdaa60f9c5d8ca2b2aa71cf8f929b616c6ce25edd9fb73e576276ee84f345
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:8080
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  audit-events:
    retention-period: 30 # Number of days before audit events are deleted.

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

**Comment by vikas326** [comment]
@SR-Lut3t1um 
Here is the content of my application.yaml file. I have uploaded it as .txt format because yaml file doesn't supported here.


[application.txt](https://github.com/quarkusio/quarkus/files/4342986/application.txt)

**Comment by SR-Lut3t1um** [comment]
What version of quarkus are you using? @vikas326

**Comment by vikas326** [comment]
1.2.0.Final    @SR-Lut3t1um

**Comment by danielpetisme** [comment]
Hello,

It's impossible to figure out the problem with the information you gave so far...

Could you share a reproducer or at least link your repo to get context.
