### ISSUE TITLE
Transient dev mode error on Windows

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#7643]
We often have this error on Windows:
```
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.488 s <<< FAILURE! - in io.quarkus.resteasy.test.NotFoundExceptionMapperTestCase
[ERROR] shouldNotDisplayDeletedFileIn404ErrorPage  Time elapsed: 2.532 s  <<< ERROR!
java.io.UncheckedIOException: 
java.nio.file.FileSystemException: D:\a\quarkus\quarkus\extensions\resteasy\deployment\target\quarkus-dev-mode-test7761304085196119552\src\main\resources\META-INF\resources\test.html: The process cannot access the file because it is being used by another process.

	at io.quarkus.test.QuarkusDevModeTest.deleteResourceFile(QuarkusDevModeTest.java:409)
	at io.quarkus.resteasy.test.NotFoundExceptionMapperTestCase.shouldNotDisplayDeletedFileIn404ErrorPage(NotFoundExceptionMapperTestCase.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
```

**Comment by gsmet** [comment]
@stuartwdouglas does it ring a bell. I remember having seen this type of error a long time ago but I thought you had fixed them.

**Comment by gsmet** [comment]
@jaikiran might be an interesting puzzle for you too :).

**Comment by jaikiran** [comment]
> @jaikiran might be an interesting puzzle for you too :).

Yeah, I just noticed this one during my PR run and was planning to take a look :) I'll find a Windows system and see what's going on.

**Comment by stuartwdouglas** [comment]
I think this is due to a potential race between the client receiving the response and the server actually closing the file. This is because the data is sent before the file is closed.
