### ISSUE TITLE
Quarkus hangs when clients disconnect after sending incomplete POST requests

### ISSUE THREAD

**Issue by cristianokbc** [quarkusio/quarkus#7646]
**Describe the bug**

When a client disconnects after sending an incomplete POST request, Quarkus keepks trying to read the input, blocking the thread indefinitely. Eventually, when all threads become blocked, Quarkus is unable to handle any requests.

It looks that VertxInputStream.VertxBlockingInput should add an exception handler to the request.

**Expected behavior**
Quarkus should throw an exception while reading an InputStream when the client disconnects.

**Actual behavior**
Quarkus keeps trying to read a closed InputStream indefinitely, leading to thread starvation.

**To Reproduce**

Create a simple resource like that:

```java
@POST
@Produces(MediaType.TEXT_PLAIN)
@Path("hello")
public String hello(byte[] b) {
    return "Ok";
}
```

Call it with a Content-Length different than zero and then disconnect:
```
echo "POST /hello HTTP/1.1\r\nContent-Length: 1\r\n" | nc localhost 8080
```

Do that several times.

Debug the application and look for threads with names similar to "executor-thread-x". You will see they are stuck:

```
"executor-thread-1" #47 daemon prio=5 os_prio=0 tid=0x00007fcccc11f000 nid=0x247c in Object.wait() [0x00007fcd1dfad000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000d6e3d988> (a io.vertx.core.http.impl.Http1xServerConnection)
	at java.lang.Object.wait(Object.java:502)
	at io.quarkus.vertx.http.runtime.VertxInputStream$VertxBlockingInput.readBlocking(VertxInputStream.java:188)
	- locked <0x00000000d6e3d988> (a io.vertx.core.http.impl.Http1xServerConnection)
	at io.quarkus.vertx.http.runtime.VertxInputStream.readIntoBuffer(VertxInputStream.java:98)
	at io.quarkus.vertx.http.runtime.VertxInputStream.read(VertxInputStream.java:60)
	at io.quarkus.vertx.http.runtime.VertxInputStream.read(VertxInputStream.java:52)
	at org.jboss.resteasy.util.ReadFromStream.readFromStream(ReadFromStream.java:30)
	at org.jboss.resteasy.plugins.providers.ByteArrayProvider.readFrom(ByteArrayProvider.java:39)
	at org.jboss.resteasy.plugins.providers.ByteArrayProvider.readFrom(ByteArrayProvider.java:25)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:102)
	at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:64)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:81)
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:212)
	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$injectArguments$1(MethodInjectorImpl.java:96)
	at org.jboss.resteasy.core.MethodInjectorImpl$$Lambda$321/1027217515.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:96)
	...
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: openjdk version "1.8.0_242"
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.2.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven 3.6.3

**Additional context**
(Add any other context about the problem here.)

**Comment by emmanuelbernard** [comment]
I am not sure who is best to work on this?
@stuartwdouglas @FroMage or @cescoffier ?

For info @gastaldi reproduced on master

**Comment by gastaldi** [comment]
FYI trying to kill the application with SIGINT (Ctrl + C) won't work after performing the first request with 

`echo "POST /hello HTTP/1.1\r\nContent-Length: 1\r\n" | nc localhost 8080`

**Comment by geoand** [comment]
Interestingly enough I wasn't able to reproduce on master

**Comment by mejlholm** [comment]
Just wanted to give a big thanks for finding/resolving this one!

We've been trying to find that issue for a while now.
