### ISSUE TITLE
[Quarkus 1.3.0.CR1 regression] Building native image fails

### ISSUE THREAD

**Issue by SchulteMarkus** [quarkusio/quarkus#7684]
Quarkus 1.3.0.CR1 was being released. I have given it a try. Using Quarkus 1.3.0.CR1, building the native image via docker fails. There is not an issue when using Quarkus 1.2.1.Final.

```bash
$ ./gradlew clean buildNative --docker-build=true \
  -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11 --info
...
Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1

# Executing the "reported" docker command directly:
$ docker run -v /home/markus/git-repos/some-service/build/some-service-1.0.0-SNAPSHOT-native-image-source-jar:/project:z \
	--user 1004:1005 --rm quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11 \
	-J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false \
	-J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory \
	-J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 \
	-H:ResourceConfigurationFiles=resources-config.json --initialize-at-build-time= \
	-H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI \
	-jar some-service-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+AddAllCharsets \
	-H:+IncludeAllTimeZones -H:EnableURLProtocols=https --enable-all-security-services -H:-SpawnIsolates --no-server \
	-H:-UseServiceLoaderFeature -H:+StackTrace some-service-1.0.0-SNAPSHOT-runner
[some-service-1.0.0-SNAPSHOT-runner:24]    classlist:  13,655.75 ms
[some-service-1.0.0-SNAPSHOT-runner:24]        setup:     350.93 ms
Error: policy com.oracle.svm.core.genscavenge.CollectionPolicy cannot be instantiated.
com.oracle.svm.core.util.UserError$UserException: policy com.oracle.svm.core.genscavenge.CollectionPolicy cannot be instantiated.
        at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
        at com.oracle.svm.core.genscavenge.HeapPolicy.instantiatePolicy(HeapPolicy.java:87)
        at com.oracle.svm.core.genscavenge.CollectionPolicy.getInitialPolicy(CollectionPolicy.java:59)
        at com.oracle.svm.core.genscavenge.GCImpl.<init>(GCImpl.java:148)
        at com.oracle.svm.core.genscavenge.HeapImpl.<init>(HeapImpl.java:106)
        at com.oracle.svm.core.genscavenge.graal.HeapFeature.afterRegistration(HeapFeature.java:65)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$11(NativeImageGenerator.java:812)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:812)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
```

**Environment**
$ uname -a
Linux markus-Aspire-VN7-592G 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode)

Quarkus version: 1.3.0.CR1

$ ./gradlew --version
Gradle 6.2.1

**Comment by SR-Lut3t1um** [comment]
It's likely linked to this [issue](https://github.com/quarkusio/quarkus/issues/7632)

**Comment by SR-Lut3t1um** [comment]
Mind trying it with JDK8 or building quarkus from source?

**Comment by SchulteMarkus** [comment]
I can test JDK8 tomorrow (CET).

**Comment by gsmet** [comment]
I don't know. It could also be some sort of escaping issue with `com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime` but I don't think we have changed something related to that.

**Comment by gwenneg** [comment]
This looks like a duplicate of #2414.

**Comment by SR-Lut3t1um** [comment]
You might also try CR2

**Comment by SchulteMarkus** [comment]
Issue resolved using CR2.
