### ISSUE TITLE
NoSuchMethodError 'void <init>()' when Testing an injected Kotlin class with Provider Injection using the QuarkusTestExtension

### ISSUE THREAD

**Issue by ChFlick** [quarkusio/quarkus#7710]
I've got a simple test to test a class in a Quarkus application (using Kotlin and Gradle), which fails when directly injecting the class being tested, but succeeds when instantiating it.

The weird thing is that it only happens in the CI, or when debugging it in the IDE (Intellij) - not when executing it via ./gradlew check, nor when running it without debugging in the IDE.

As I'm quite new to Kotlin, I'm not entirely sure it's an Quarkus bug, so feel free to close the issue if irrelevant.

**Expected behavior**
Both tests should pass.

**Actual behavior**
Fails:
```
@QuarkusTest
class InfluxVehicleRepositoryTest
@Inject constructor(private val influxVehicleRepository: InfluxVehicleRepository) {
    @Test
    fun findByMinutesFromNow() {
        val result = influxVehicleRepository.findByMinutesFromNow(5)

        assertThat(result).isEmpty()
    }
}
```

Succeeds:
```
@QuarkusTest
@QuarkusTestResource(InfluxDBResource::class)
class InfluxVehicleRepositoryTest
@Inject constructor(private val influxDBProvider: InfluxDBProvider) {
    @Test
    fun findByMinutesFromNow() {
        val influxVehicleRepository = InfluxVehicleRepository(influxDBProvider)
        val result = influxVehicleRepository.findByMinutesFromNow(5)

        assertThat(result).isEmpty()
    }
}
```

The class being tested as well as its direct dependency look like that:
```
@ApplicationScoped
class InfluxVehicleRepository
private constructor(private val influxDB: InfluxDB) : VehicleRepository {
    @Inject
    constructor (influxDBProvider: InfluxDBProvider) : this(influxDBProvider.get())
    ...
}

...

@ApplicationScoped
class InfluxDBProvider : Provider<InfluxDB> {
    @ConfigProperty(name = "traffic.influx.username", defaultValue = "admin")
    lateinit var username: String
    ...

    override fun get(): InfluxDB {
        ...
        return influxDb
    }
}
```

Here is the log of the gradle execution:
```
Testing started at 13:11 ...
> Task :cleanTest
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :compileTestKotlin UP-TO-DATE
> Task :quarkusTestConfig
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/chris/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.8/2f1e8ea55e625fe51e85ef35eb067f1d9c61772d/groovy-2.5.8.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Mar 06, 2020 1:11:02 PM org.testcontainers.dockerclient.DockerClientProviderStrategy lambda$getFirstValidStrategy$1
INFO: Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
Mar 06, 2020 1:11:03 PM org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy test
INFO: Found docker client settings from environment
Mar 06, 2020 1:11:03 PM org.testcontainers.dockerclient.DockerClientProviderStrategy lambda$getFirstValidStrategy$2
INFO: Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///var/run/docker.sock
Mar 06, 2020 1:11:03 PM org.testcontainers.DockerClientFactory client
INFO: Docker host IP address is localhost
Mar 06, 2020 1:11:03 PM org.testcontainers.DockerClientFactory client
INFO: Connected to docker: 
  Server Version: 19.03.6-ce
  API Version: 1.40
  Operating System: Manjaro Linux
  Total Memory: 11908 MB
Mar 06, 2020 1:11:04 PM org.testcontainers.DockerClientFactory client
INFO: Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
Mar 06, 2020 1:11:04 PM org.testcontainers.containers.GenericContainer tryStart
INFO: Creating container for image: influxdb:1.4.3
Mar 06, 2020 1:11:04 PM org.testcontainers.containers.GenericContainer tryStart
INFO: Starting container with ID: 9b84011b121fd153d81299d6b25ad4c9cf000524fb37cd8e591fcf233123bb39
Mar 06, 2020 1:11:04 PM org.testcontainers.containers.GenericContainer tryStart
INFO: Container influxdb:1.4.3 is starting: 9b84011b121fd153d81299d6b25ad4c9cf000524fb37cd8e591fcf233123bb39
Mar 06, 2020 1:11:04 PM org.testcontainers.containers.wait.strategy.HttpWaitStrategy waitUntilReady
INFO: /sharp_dirac: Waiting for 30 seconds for URL: http://localhost:32830/ping
Mar 06, 2020 1:11:08 PM org.testcontainers.containers.GenericContainer tryStart
INFO: Container influxdb:1.4.3 started in PT5.352938S
Mar 06, 2020 1:11:08 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.0.0.Final
[0K[1mde.flick.traffic.vehicles.InfluxVehicleRepositoryTest[m
[0K[1m  Test [22mfindByMinutesFromNow()[31m FAILED[31m
  org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [de.flick.traffic.vehicles.InfluxVehicleRepositoryTest]
  Caused by: java.lang.ExceptionInInitializerError
  Caused by: java.lang.RuntimeException: Failed to start quarkus
  Caused by: java.lang.RuntimeException: Failed to initialize Arc
  Caused by: java.lang.NoSuchMethodError: de.flick.traffic.vehicles.InfluxVehicleRepository: method 'void <init>()' not found
[m

TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [de.flick.traffic.vehicles.InfluxVehicleRepositoryTest]
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [de.flick.traffic.vehicles.InfluxVehicleRepositoryTest]
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:300)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:275)
    at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:77)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:258)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:252)
    at java.base/java.util.Optional.orElseGet(Optional.java:362)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:251)
    at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:29)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:106)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:105)
    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:69)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:107)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
    at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
    at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
    at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
    at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
    at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
    at com.sun.proxy.$Proxy2.stop(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
    at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
    at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.ExceptionInInitializerError
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:416)
    at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:153)
    at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:249)
    at io.quarkus.test.junit.QuarkusTestExtension.createTestInstance(QuarkusTestExtension.java:394)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstanceFactory(ClassBasedTestDescriptor.java:285)
    ... 72 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
    at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:406)
    ... 78 more
Caused by: java.lang.RuntimeException: Failed to initialize Arc
    at io.quarkus.arc.Arc.initialize(Arc.java:26)
    at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:34)
    at io.quarkus.deployment.steps.ArcProcessor$generateResources26.deploy_0(ArcProcessor$generateResources26.zig:72)
    at io.quarkus.deployment.steps.ArcProcessor$generateResources26.deploy(ArcProcessor$generateResources26.zig:36)
    at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:360)
    ... 78 more
Caused by: java.lang.NoSuchMethodError: de.flick.traffic.vehicles.InfluxVehicleRepository: method 'void <init>()' not found
    at de.flick.traffic.vehicles.InfluxVehicleRepository_ClientProxy.<init>(InfluxVehicleRepository_ClientProxy.zig:129)
    at de.flick.traffic.vehicles.InfluxVehicleRepository_Bean.<init>(InfluxVehicleRepository_Bean.zig:218)
    at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans1(Default_ComponentsProvider.zig:1074)
    at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:38)
    at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:103)
    at io.quarkus.arc.Arc.initialize(Arc.java:20)
    ... 82 more

[0K[1;31mFAILURE: [39mExecuted 1 tests in 8.7s (1 failed)[m
1 test completed, 1 failed
> Task :test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/chris/dev/ConnectedVehicle/project/cvs/manage-vehicle-data/build/reports/tests/test/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 9s
6 actionable tasks: 3 executed, 3 up-to-date
```

**Configuration**
build.gradle
```groovy
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.41'
    id 'org.jetbrains.kotlin.plugin.allopen' version '1.3.41'
    id 'io.quarkus'
    id 'com.adarshr.test-logger' version '2.0.0'
}

repositories {
     mavenLocal()
     mavenCentral()
}

dependencies {
    implementation 'io.github.microutils:kotlin-logging:1.7.8'
    implementation 'org.influxdb:influxdb-java:2.15'
    implementation 'io.quarkus:quarkus-smallrye-metrics'
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-kotlin'
    implementation 'io.quarkus:quarkus-smallrye-fault-tolerance'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-resteasy-jsonb'
    implementation 'io.quarkus:quarkus-vertx'
    implementation 'io.quarkus:quarkus-smallrye-opentracing'
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:influxdb:1.12.5'
    testImplementation 'org.assertj:assertj-core:3.15.0'
}

configurations.all {
    exclude group: 'javax.enterprise', module: 'cdi-api'
}

group 'de.flick'
version '1.0.0-SNAPSHOT'

quarkus {
    setOutputDirectory("$projectDir/build/classes/kotlin/main")
}

quarkusDev {
    setSourceDir("$projectDir/src/main/kotlin")
}

allOpen {
    annotation("javax.ws.rs.Path")
    annotation("javax.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

compileKotlin {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_1_8
    kotlinOptions.javaParameters = true
}

compileTestKotlin {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_1_8
}
```

**Environment (please complete the following information):**
- Gradle: 6.0.1
- Quarkus: 1.2.1.Final
- JDK: openjdk version "13.0.2" 2020-01-14
- OS: Linux 5.5.7-1-MANJARO amd64

**Additional context**
I'm unable to reproduce the error with a new repository from scratch, so I cannot provide a good, reproducable example.

**Comment by geoand** [comment]
Hi,

Am I correct to assume that doing:

```
@QuarkusTest
class InfluxVehicleRepositoryTest
   
   @Inject 
   lateinit var influxVehicleRepository: InfluxVehicleRepository
    
   @Test
    fun findByMinutesFromNow() {
        val result = influxVehicleRepository.findByMinutesFromNow(5)

        assertThat(result).isEmpty()
    }
}
``` 

works?

**Comment by ChFlick** [comment]
Hi @geoand,
thanks for your response.

The behavior with your snippet is the same as with my test, it works "sometimes".
I just executed it and now even a different test fails that is not even related to the `InfluxVehicleRepository`.

```
@QuarkusTest
class OpenApiTest {

    @Test
    fun shouldPingOpenAPI() {
        given()
            .header(ACCEPT, APPLICATION_JSON)
            .`when`().get("/openapi")
            .then()
            .statusCode(OK.statusCode)
    }

    @Test
    fun shouldPingSwaggerUI() {
        given()
            .`when`().get("/swagger-ui")
            .then()
            .statusCode(OK.statusCode)
    }
}
``` 

Here are two tests executions, the first worked fine (even though with an error), on the second one the NoSuchMethodError occured:
```
manage-vehicle-data [test/inject]× » ./gradlew check                                                                                                                                                                                       ~/d/C/p/c/manage-vehicle-data
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :compileTestKotlin UP-TO-DATE
> Task :quarkusTestConfig
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/chris/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.8/2f1e8ea55e625fe51e85ef35eb067f1d9c61772d/groovy-2.5.8.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

de.flick.traffic.vehicles.InfluxVehicleRepositoryTest

  Test findByMinutesFromNow() PASSED

de.flick.traffic.TrafficControllerTest

  Test getVehicles() PASSED

de.flick.OpenApiTest

  Test shouldPingSwaggerUI() FAILED

  java.lang.AssertionError: 1 expectation failed.
  Expected status code <200> but was <404>.
      at de.flick.OpenApiTest.shouldPingSwaggerUI(OpenApiTest.kt:28)

  Test shouldPingOpenAPI() PASSED

FAILURE: Executed 4 tests in 9.9s (1 failed)


4 tests completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/chris/dev/ConnectedVehicle/project/cvs/manage-vehicle-data/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
5 actionable tasks: 2 executed, 3 up-to-date





manage-vehicle-data [test/inject]× » ./gradlew check                                                                                                                                                                                     ~/d/C/p/c/manage-vehicle-data 1
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :compileTestKotlin UP-TO-DATE
> Task :quarkusTestConfig
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/chris/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.8/2f1e8ea55e625fe51e85ef35eb067f1d9c61772d/groovy-2.5.8.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

de.flick.OpenApiTest

  Test shouldPingSwaggerUI() FAILED

  org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [de.flick.OpenApiTest]

  Caused by: java.lang.ExceptionInInitializerError

  Caused by: java.lang.RuntimeException: Failed to start quarkus

  Caused by: java.lang.RuntimeException: Failed to initialize Arc

  Caused by: java.lang.NoSuchMethodError: de.flick.traffic.vehicles.InfluxVehicleRepository: method 'void <init>()' not found


  Test shouldPingOpenAPI() FAILED

  java.net.ConnectException: Connection refused
      at de.flick.OpenApiTest.shouldPingOpenAPI(OpenApiTest.kt:18)


de.flick.traffic.TrafficControllerTest

  Test getVehicles() SKIPPED

de.flick.traffic.vehicles.InfluxVehicleRepositoryTest

  Test findByMinutesFromNow() SKIPPED

FAILURE: Executed 4 tests in 8.7s (2 failed, 2 skipped)


4 tests completed, 2 failed, 2 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/chris/dev/ConnectedVehicle/project/cvs/manage-vehicle-data/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
5 actionable tasks: 2 executed, 3 up-to-date

```

**Comment by geoand** [comment]
Thanks @ChFlick. Would it be possible to provide a reproducer project for this problem?

**Comment by mkouba** [comment]
@ChFlick could you pls try to test your app with quarkus 1.3.0.CR2? There is a good chance that this is a class loading issue similar to #7541.

**Comment by ChFlick** [comment]
@geoand
I'm not really able to create a reproducer project for this problem. [This is the project](https://github.com/ChFlick/connected-vehicle-microservice/tree/master/manage-vehicle-data) where the error occurs for me.

@mkouba 
I'm quite sure this resolves the issue. At least, the `@lateinit` version works now. My initial version with constructor injection now throws a different bug which I think is related to #7140 
```
No ParameterResolver registered for parameter [de.flick.traffic.vehicles.InfluxVehicleRepository arg0] in constructor [public de.flick.traffic.vehicles.InfluxVehicleRepositoryTest(de.flick.traffic.vehicles.InfluxVehicleRepository)].
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [de.flick.traffic.vehicles.InfluxVehicleRepository arg0] in constructor [public de.flick.traffic.vehicles.InfluxVehicleRepositoryTest(de.flick.traffic.vehicles.InfluxVehicleRepository)].
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:200)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:183)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:74)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:333)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:280)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:77)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:262)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:256)
```

Thank you very much for your help
