### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types

### ISSUE THREAD

**Issue by zulq** [quarkusio/quarkus#7765]
I have a base model in kotlin similar to the following:
```
@MappedSuperclass
abstract class BaseModel : Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null
    var deleted: Boolean = false
}
```

And another `entity` inheriting from the base model similar to:
```
@Entity
data class Person(
        var firstName: String = "",
        var lastName: String = "",
        @get:Email
        var email: String = ""
) : BaseModel()
```
Stack trace:
```
 ERROR [io.qua.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:80)
	at io.quarkus.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:60)
	at io.quarkus.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:236)
	at io.quarkus.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:39)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:131)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:104)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:46)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:482)
	... 10 more
Caused by: java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:154)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
Caused by: java.lang.RuntimeException: Failed to start quarkus

	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
Caused by: java.lang.IllegalArgumentException: Could not create type

	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
	at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.load(ByteBuddyState.java:175)
	at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.loadProxy(ByteBuddyState.java:99)
	at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyProxyHelper.buildProxy(ByteBuddyProxyHelper.java:54)
	at io.quarkus.hibernate.orm.runtime.proxies.ProxyDefinitions.generateProxyClass(ProxyDefinitions.java:85)
	at io.quarkus.hibernate.orm.runtime.proxies.ProxyDefinitions.createFromMetadata(ProxyDefinitions.java:47)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:338)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:111)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:84)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:47)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$4.created(HibernateOrmRecorder.java:75)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:102)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources28.deploy_0(ArcProcessor$generateResources28.zig:454)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources28.deploy(ArcProcessor$generateResources28.zig:36)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:444)
	... 10 more
Caused by: java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types: class ...
	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:406)
Caused by: java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types: class ...

	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:299)
	at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyProxyHelper.lambda$buildProxy$0(ByteBuddyProxyHelper.java:57)
	at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.lambda$load$0(ByteBuddyState.java:178)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	... 27 more
```

Failing versions: 1.3.0.CR1 and CR2
Prev working versions: 1.2.0 and 1.2.1

**Comment by geoand** [comment]
Thank you for reporting.

Can you please format the classes and also provide the full stacktrace?

@mkouba IIRC you made some kind of fix in Arc to around subclassing, am I right?

**Comment by geoand** [comment]
Actually looking at the stacktrace it looks more like a Hibernate issue, so let's see if @Sanne has any ideas :)

**Comment by Sanne** [comment]
I think this is caused by the upgrade of ByteBuddy. The `Person` entity is a final class, and the new version of ByteBuddy is strictly checking against this.

I would need to check if something is possible in ByteBuddy to be more lenient.

**Comment by geoand** [comment]
@zulq can you check if making your entity `open` gets you passed the issue?

**Comment by zulq** [comment]
`data` classes are incompatible with open unfortunately.

**Comment by geoand** [comment]
Ah yes... I forgot about that...

**Comment by geoand** [comment]
How about if you apply the `jpa-support` Kotlin compiler plugin (details at:  https://kotlinlang.org/docs/reference/compiler-plugins.html#jpa-support)?

**Comment by zulq** [comment]
Still the same, added plugin, gradle clean then quarkusDev.

**Comment by geoand** [comment]
Thanks for checking

**Comment by zulq** [comment]
This really looks like a bytebuddy issue, see here: [Mockito similar issue](https://github.com/mockito/mockito/issues/1606)

**Comment by zulq** [comment]
Is it easy to get all the libraries using bytebuddy? Just trying to see if can try excluding and use an explicit version.

**Comment by zulq** [comment]
Any ideas/workarounds, because this is a blocker for me.

**Comment by Sanne** [comment]
hi zulq, no worries I'm working on a fix: sending a PR soon.

**Comment by zulq** [comment]
Thanks a lot @Sanne, will keep an eye.

**Comment by Sanne** [comment]
I've sent a PR, feel free to test it on your application as as well :)

**Comment by zulq** [comment]
> 
> 
> I've sent a PR, feel free to test it on your application as as well :)

Do I have to use the snapshots or wait for 1.3.0 to be able to test?

**Comment by geoand** [comment]
You can build Quarkus from the https://github.com/quarkusio/quarkus/pull/7780 and use version `999-SNAPSHOT` in order to test yourself

**Comment by arsen-papoyan** [comment]
Hello everyone.
Sorry if my problem is not related to your conversation.
I am striving hard to find a solution but to no avail.
When using DevTools, I get an exception in the case of using RemoteWebDriver.
> java.lang.ExceptionInInitializerError Caused by: java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types: class com.sun.proxy.$Proxy12 at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:486) at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:459) at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:356) at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:179)

I have added this after initializing:
```
WebDriver driver = new Augmenter().augment(getWebDriver());
DevTools devTools = ((HasDevTools) driver).getDevTools();
```
Added bytebuddy maven dependency to pom.xml.
Environment: Selenium Grid v4.

**Comment by Sanne** [comment]
@arsen-papoyan I wonder if you're overriding the bytebuddy version by adding it to the pom - try to ensure you're using the versions recommended by the Quarkus BOM.

If that doesn't help, please open a new issue with a reproducer so that we can look at it in more detail.
