### ISSUE TITLE
Cannot send Kafka message with key in 1.3.0.CRx

### ISSUE THREAD

**Issue by zeljkot** [quarkusio/quarkus#7811]
**Describe the bug**
Previously it was possible to send Kafka message with a key using
```java
    @Inject
    @Channel("status-out")
    Emitter<KafkaMessage<Long, ProcessingStatus>> emitter;

    emitter.send(KafkaMessage.of(fileEntity.getId(), status));
```
If this code is changed to new MP reactive API:
```
    @Inject
    @Channel("status-out")
    Emitter<KafkaRecord<Long, ProcessingStatus>> emitter;

    emitter.send(KafkaRecord.of(fileEntity.getId(), status));
```
It throws the exception because it tries to serialize whole OutgoingKafkaRecord as a value rather than just the ProcessingStatus.

**Expected behavior**
The message key is serialized with key serializer and value is serialized with value serializer.

**Actual behavior**
Whole message is serialized with value serializer.

**To Reproduce**
1. Configure outgoing topic
2. Configure emitter that sends KafkaRecord<key, value>
3. emitter.send(KafkaRecord.of(fileEntity.getId(), status));

**Configuration**
```properties
    outgoing:
      status-out:
        connector: smallrye-kafka
        key:
          serializer: org.apache.kafka.common.serialization.LongSerializer
        value:
          serializer: hr.company.project.dto.messaging.processing.v1.serde.ProcessingStatusSerializer
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
Output of uname -a or ver: Microsoft Windows [Version 10.0.19041.113]
Output of java -version: java version "1.8.0_231"
GraalVM version (if different from Java):
Quarkus version or git rev: 1.3.0.CR1 or later
Build tool (ie. output of mvnw --version or gradlew --version): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**

Stack trace:
```
2020-03-12 11:10:29,439 ERROR [asc.api-service] () [vert.x-worker-thread-9] [KafkaSink.java:88] - Unable to dispatch message to Kafka: java.util.concurrent.CompletionException: org.apache.kafka.common.errors.SerializationException: Can't convert value of class io.smallrye.reactive.messaging.kafka.OutgoingKafkaRecord to class hr.company.project.dto.messaging.processing.v1.serde.ProcessingStatusSerializer specified in value.serializer
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.smallrye.reactive.messaging.kafka.impl.KafkaSink.lambda$null$1(KafkaSink.java:72)
	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.lambda$write$5(KafkaWriteStreamImpl.java:143)
	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.lambda$send$4(KafkaWriteStreamImpl.java:131)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: Can't convert value of class io.smallrye.reactive.messaging.kafka.OutgoingKafkaRecord to class hr.company.project.dto.messaging.processing.v1.serde.ProcessingStatusSerializer specified in value.serializer
Caused by: java.lang.ClassCastException: io.smallrye.reactive.messaging.kafka.OutgoingKafkaRecord cannot be cast to hr.company.project.dto.messaging.processing.v1.ProcessingStatus
	at hr.company.project.dto.messaging.processing.v1.serde.ProcessingStatusSerializer.serialize(ProcessingStatusSerializer.java:12)
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:903)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:865)
	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.lambda$send$4(KafkaWriteStreamImpl.java:93)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cescoffier** [comment]
@zeljkot This is because the Emiutter is now part of the spec and is slightly different. You need:

```
    @Inject
    @Channel("status-out")
    Emitter<ProcessingStatus> emitter;

    emitter.send(KafkaRecord.of(fileEntity.getId(), status));
```

This is documented in the migration guide.

**Comment by zeljkot** [comment]
It works, thanks! From the migration guide, it was not obvious to me that I can send types different than what I defined in the Emitter declaration.

So now there are two possibilities:
* send(type)
* send(KafkaRecord.of(key, type)

There is one drawback of this solution, though: **the key is not typesafe.**

**Comment by zeljkot** [comment]
Another thing that is confusing is that `@Incoming` and `@Outgoing` still need and accept KafkaRecord (bonus: key type could be defined). This change makes API inconsistent and less typesafe. IMHO it would be better if you left Emitter<Message>.

**Comment by gsmet** [comment]
@cescoffier

**Comment by cescoffier** [comment]
I understand the drawback. Unfortunately, it would require to change the spec.

**Comment by zeljkot** [comment]
@cescoffier It is not very old anyway :) and it introduced a change incompatible to original SmallRye implementation.

**Comment by zeljkot** [comment]
On second thought, if key concept is not used on other platforms then it does not make sense to put it into a generic interface. Maybe you can do the same as with KafkaRecord: provide KafkaEmmiter or KeyPayloadEmmiter.

BTW KafkaRecord is a kind of message, so I did not like change from KafkaMessage, too :)
