### ISSUE TITLE
Error in image generation: com.sun.xml.internal.bind.v2.ContextFactory not found

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#7914]
Image generation in [`quarkus-platform`](https://github.com/quarkusio/quarkus-platform) tests with graal master fails with:

```
[quarkus-universe-integration-tests-camel-aws-999-SNAPSHOT-runner:26932]     analysis:  35,247.12 ms,  3.25 GB
Fatal error:com.oracle.svm.core.util.VMError$HostedError: class com.sun.xml.internal.bind.v2.ContextFactory not found
	at com.oracle.svm.core.util.VMError.guarantee(VMError.java:85)
	at com.oracle.svm.core.jdk.JNIRegistrationUtil.clazz(JNIRegistrationUtil.java:78)
	at com.oracle.svm.hosted.config.JAXBClassAndResourcesLoaderFeature.registerReflectionClasses(JAXBClassAndResourcesLoaderFeature.java:70)
	at com.oracle.svm.hosted.config.JAXBClassAndResourcesLoaderFeature.registerJavaxXmlConfigs(JAXBClassAndResourcesLoaderFeature.java:62)
	at com.oracle.svm.hosted.ReachabilityHandlerFeature.duringAnalysis(ReachabilityHandlerFeature.java:114)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:722)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:722)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

Longer output [here](https://gist.github.com/galderz/4f51db8456aa833469e96dccca5679c3).

It appears this might already have been reported (see https://github.com/oracle/graal/issues/2169).

**Comment by dufoli** [comment]
I face some issue related to jaxb on cxf patch and it is fixed on my branch. 
take a look to : https://github.com/dufoli/quarkus/blob/4005_cxf/extensions/cxf/deployment/src/main/java/io/quarkus/cxf/deployment/CxfProcessor.java

**Comment by galderz** [comment]
Thanks @dufoli, I'll check and see if camel needs it too.

**Comment by galderz** [comment]
Testing with latest on 30.3.2020 (last Friday) showed this error instead:

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.xml.bind.JAXBContext. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing org.apache.camel.reifier.rest.RestBindingReifier.setupJaxb(RestBindingReifier.java:166)
Call path from entry point to org.apache.camel.reifier.rest.RestBindingReifier.setupJaxb(RestConfiguration, String, String, DataFormat, DataFormat):
	at org.apache.camel.reifier.rest.RestBindingReifier.setupJaxb(RestBindingReifier.java:160)
	at org.apache.camel.reifier.rest.RestBindingReifier.createRestBindingAdvice(RestBindingReifier.java:124)
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:396)
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:112)
	at org.apache.camel.quarkus.core.FastModel.start(FastModel.java:57)
	at org.apache.camel.quarkus.core.BaseModel.startRoute(BaseModel.java:327)
	at org.apache.camel.quarkus.core.BaseModel.startRouteDefinitions(BaseModel.java:320)
	at org.apache.camel.quarkus.core.BaseModel.startRouteDefinitions(BaseModel.java:299)
	at org.apache.camel.quarkus.core.FastCamelContext.startRouteDefinitions(FastCamelContext.java:515)
	at com.oracle.svm.reflect.AbstractCamelContext_startRouteDefinitions_d9d0e38b2319b6d7686c4d0b97300500cfc8b56c_1398.invoke(Unknown Source)
```

Maybe just adding jaxb as dependency is enough.

**Comment by galderz** [comment]
Cloned to https://github.com/apache/camel-quarkus/issues/996

**Comment by galderz** [comment]
PR with fix sent to https://github.com/apache/camel-quarkus/pull/997

**Comment by galderz** [comment]
PR has been integrated, closing this now.
