### ISSUE TITLE
Keycloak and vertx-web leading to "IllegalStateException: Request has already been read"

### ISSUE THREAD

**Issue by marc-christian-schulze** [quarkusio/quarkus#8126]
**Describe the bug**
Using Keycloak in combination with vertx-web 
```
@Path("/")
@ApplicationScoped
open class Controller {

    @GET
    @Path("/working")
    open fun working(): String = "It's working"

    @Route(path = "/broken", methods = [HttpMethod.GET])
    open fun broken(routingContext: RoutingContext) = routingContext.response().end("It's broken!")
}
```
causes the following exception:
```
2020-03-24 22:46:08,671 INFO  [io.quarkus] (main) quarkus-keycloak-reproducer 1.0.0-SNAPSHOT (powered by Quarkus 1.3.0.Final) started in 1.854s. Listening on: http://0.0.0.0:8083
2020-03-24 22:46:08,678 INFO  [io.quarkus] (main) Profile prod activated. 
2020-03-24 22:46:08,679 INFO  [io.quarkus] (main) Installed features: [cdi, keycloak-authorization, kotlin, mutiny, oidc, resteasy, resteasy-jackson, security, vertx, vertx-web]
2020-03-24 22:46:46,210 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /broken failed, error id: 9d0933d8-7c48-485c-91d2-a7af43662104-1: java.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:600)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handler(HttpServerRequestImpl.java:307)
	at io.quarkus.vertx.http.runtime.ResumingRequestWrapper.handler(ResumingRequestWrapper.java:18)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:78)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:86)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:42)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$12.handle(VertxHttpRecorder.java:866)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$12.handle(VertxHttpRecorder.java:862)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:120)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.checkPermission(HttpAuthorizer.java:93)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:87)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:79)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1$1.apply(HttpSecurityRecorder.java:70)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$1$1.apply(HttpSecurityRecorder.java:36)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2144)
	at io.quarkus.security.runtime.QuarkusIdentityProviderManagerImpl$1$1.run(QuarkusIdentityProviderManagerImpl.java:55)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:835)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Expected behavior**
Endpoint `/working` returns HTTP 200 with content.
Endpoint `/broken` returns HTTP 200 with content.

**Actual behavior**
Endpoint `/working` returns HTTP 200 with content.
Endpoint `/broken`  returns HTTP 500 Internal Server Error

**To Reproduce**
1. Create Keycloak realm "example"
2. Create Keycloak client "example-client"
3. Set access type to "Confidential"
4. Set "Authorization Enabled"
5. Copy client secret into application.properties
6. Create user test with pass test
7. Create token 
```
token=$(curl -X POST http://localhost:8081/auth/realms/example/protocol/openid-connect/token --user 'example-client:4277c122-3002-4379-93bb-60ab86e11c1f' -H 'content-type: application/x-www-form-urlencoded' -d 'username=test&password=test&grant_type=password' | jq -r '.access_token')
```
8. Access /broken endpoint 
```
curl -v -X GET http://localhost:8080/broken -H "Authorization: Bearer $token"
```

**Reproducer:**
https://github.com/marc-christian-schulze/quarkus-reproducer-8126

**Environment:**
Quarkus 1.3.0.Final
```
$ uname -a
Linux christian-GA-990FXA-UD3 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+9-Ubuntu-119.04)
OpenJDK 64-Bit Server VM (build 12.0.2+9-Ubuntu-119.04, mixed mode)
$ ./gradlew --version

------------------------------------------------------------
Gradle 6.2
------------------------------------------------------------

Build time:   2020-02-17 08:32:01 UTC
Revision:     61d3320259a1a0d31519bf208eb13741679a742f

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          12.0.2 (Private Build 12.0.2+9-Ubuntu-119.04)
OS:           Linux 5.0.0-38-generic amd64
```

**Comment by marc-christian-schulze** [comment]
I've seen a similar issue reported at stackoverflow:
https://stackoverflow.com/questions/52969528/keycloak-vert-x-java-lang-illegalstateexception-request-has-already-been-read

**Comment by stuartwdouglas** [comment]
This may have been fixed by. https://github.com/quarkusio/quarkus/pull/7951, I will test

**Comment by marc-christian-schulze** [comment]
I've re-tested with Quarkus 1.3.1.Final and the issue is resolved. The very same reproducer given above is providing the expected results with the new Quarkus version.
