### ISSUE TITLE
Unsupported type MethodAccessorGenerator in camel native tests

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#8201]
Testing latest graalvm w/ latest quarkus today is showing a failure in camel native testing (quarkus-platform):

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing java.base@11.0.8-internal/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor):
	at java.base@11.0.8-internal/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at java.base@11.0.8-internal/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.base@11.0.8-internal/java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1516)
	at java.base@11.0.8-internal/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.base@11.0.8-internal/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at app//com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:81)
	at platform/jdk.crypto.cryptoki@11.0.8-internal/sun.security.pkcs11.SunPKCS11.initToken(SunPKCS11.java:1028)
	at platform/jdk.crypto.cryptoki@11.0.8-internal/sun.security.pkcs11.SunPKCS11$TokenPoller.run(SunPKCS11.java:852)
	at java.base@11.0.8-internal/java.lang.Thread.run(Thread.java:834)
	at app//com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:515)
	at app//com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

Longer output [here](https://gist.github.com/galderz/327c9af4eeb9d660c3d58fa1df9a1aeb).

This is very similar to the optaplanner issue (#7422) found a few weeks back.

**Comment by galderz** [comment]
Fixed more globally in https://github.com/quarkusio/quarkus/pull/9686.
