### ISSUE TITLE
Support java 14 records in quarkus:dev

### ISSUE THREAD

**Issue by arvidvillen** [quarkusio/quarkus#8277]
**Description**
Support the usage of Java 14 records (preview feature) in quarkus:dev.

I’m trying to get java 14 records to work in Quakrus and I’m (quite easily) able to get the tests to pass and the final jar to run but DevMode fails with the following error:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:117)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:54)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:134)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:113)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL
	at io.quarkus.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:259)
	at io.quarkus.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:39)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:131)
	... 3 more
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL
	at org.objectweb.asm.ClassVisitor.visitRecordComponentExperimental(ClassVisitor.java:304)
	at org.objectweb.asm.ClassReader.readRecordComponent(ClassReader.java:929)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:704)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at io.quarkus.dev.JavaCompilationProvider.getSourcePath(JavaCompilationProvider.java:78)
	at io.quarkus.dev.ClassLoaderCompiler.findSourcePath(ClassLoaderCompiler.java:183)
	at io.quarkus.dev.RuntimeUpdatesProcessor.retrieveSourceFilePathForClassFile(RuntimeUpdatesProcessor.java:273)
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForClassFilesChangesInModule(RuntimeUpdatesProcessor.java:235)
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:205)
	at io.quarkus.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:234)
	... 5 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.999 s
[INFO] Finished at: 2020-03-30T18:34:33+02:00
[INFO] ------------------------------------------------------------------------
```

[Reproducer](https://github.com/arvidvillen/quarkus-records)
Run `./mvnw quarkus:dev` to replicate the error.

Run `./mvnw package` and `java  --enable-preview -jar target/java-records-1.0.0-SNAPSHOT-runner.jar` to start the application successfully.

**Implementation ideas**
I think that upgrading ASM to the newly released [8.0 version](https://mvnrepository.com/artifact/org.ow2.asm/asm/8.0) in _quarkus-maven-plugin_ would do the trick.

**Comment by gsmet** [comment]
We would also need to update the version of bytecode we use to ASM8 and I don't know if it's still the case but ByteBuddy has a flag for enabling experimental features.

**Comment by geoand** [comment]
In ASM8  you don't need to use the experimental features, just the regular ASM8 flag to get around the issue.

Like @gsmet said, once all dependencies are in place, we'll update Quarkus and things will work as expected.

**Comment by arvidvillen** [comment]
Tested against master and it now works.
