### ISSUE TITLE
Regression: Strange @ClassCastException when running tests

### ISSUE THREAD

**Issue by fredmtyro** [quarkusio/quarkus#8286]
**Describe the bug**
A `@QuarkusTest` that worked properly with 1.2.1 fails with 1.3.1 with an odd `ClassCastException` where a class can't be cast to its own type, but this failure only occurs during a mvn clean install when a second unrelated unit test is run. When any of the test classes are run in isolation, they pass.

**Expected behavior**
All tests pass as under 1.2.1.

**Actual behavior**
I am having trouble making a reproducer for this one, so it would be good to get some guidance about producing suitable debug information.

I have a project with source that I cannot share.

It builds without error on 1.2.1 but with 1.3.1 I get an error of the form below when running `mvn clean install`:

```
[INFO] Running com.tyro.integration.xTest
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 5.17 s <<< FAILURE! - in com.tyro.integration.xTest
[ERROR] shouldYYY  Time elapsed: 0.017 s  <<< ERROR!
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to initialize Arc
Caused by: java.lang.ClassCastException: com.tyro.service.AService cannot be cast to com.tyro.service.AService
```

There are many other test classes but there is one specific unrelated unit test class (ie one that does not use `@QuarkusTest`) that instantiates one of the service objects from the application with a Mockito mock collaborator and if I disable that test, the problem test above will pass. If I run the tests in isolation they pass. There are no obvious interactions between the two.

Is there any additional debugging I can turn on to provide useful feedback?

**To Reproduce**
_TBC_
1. 
2. 
3. 

**Configuration**
Not applicable as far as I can see.

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin xxxx 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 
```
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 1.8.0_172, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

**Additional context**
(Add any other context about the problem here.)

**Comment by fredmtyro** [comment]
This is similar to the structure I have in my problem project:

[code-with-quarkus 2.zip](https://github.com/quarkusio/quarkus/files/4406164/code-with-quarkus.2.zip)

ExampleResourceTest is like the `@QuarkusTest` that fails above, ExampleResource2Test is like the test I need to comment out to get a successful build.

**Comment by geoand** [comment]
@fredmtyro Thanks for reporting.

It would be a tremendous help if you could come up with a reproducer that fails and shows the problem.

**Comment by fredmtyro** [comment]
@geoand I agree, but no luck so far :(
 
While I experiment with that, is there anything else I can do that will provide some insights about the problem?

**Comment by geoand** [comment]
Short of debugging quarkus source code, not that I can think of :)

**Comment by derKrischan** [comment]
Perhaps this is a suitable reproducer for the described problem: https://github.com/derKrischan/quarkus-reproducer-8286
I'm unable to get Mockito working right now and I don't like the Quarkus way to mock via mock implementations as it makes the tests less readable imho.

**Comment by geoand** [comment]
@derKrischan your issue is: https://github.com/quarkusio/quarkus/issues/7199

**Comment by derKrischan** [comment]
@geoand Thanks. You're right.

**Comment by stuartwdouglas** [comment]
Is this still an issue?

**Comment by fredmtyro** [comment]
Yes this is still an issue with 1.6.0.Final though the error message is more detailed:

`
2020-07-08 15:50:06,105 ERROR [io.qua.sch.run.SimpleScheduler] (executor-thread-1) Error occured while executing task for trigger IntervalTrigger [id=1_com.tyro.integration.AService_ScheduledInvoker_cleanup_876dc04f8610241fa6f344e3d6fa75a663b05f35, interval=3600000]: java.lang.ClassCastException: class com.tyro.service.AService cannot be cast to class com.tyro.service.AService (com.tyro.service.AService is in unnamed module of loader 'app'; com.tyro.service.AService is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @8961e55)
        at com.tyro.integration.MockAService.<init>(AServiceFactory.kt:15)
        at com.tyro.integration.MockAService_ClientProxy.<init>(MockAService_ClientProxy.zig:28)
        at com.tyro.integration.MockAService_Bean.proxy(MockAService_Bean.zig:40)
        at com.tyro.integration.MockAService_Bean.get(MockAService_Bean.zig:204)
        at com.tyro.integration.MockAService_Bean.get(MockAService_Bean.zig:220)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:408)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:421)
        at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:258)
        at com.tyro.integration.MockAService_ScheduledInvoker_cleanup_876dc04f8610241fa6f344e3d6fa75a663b05f35.invokeBean(MockAService_ScheduledInvoker_cleanup_876dc04f8610241fa6f344e3d6fa75a663b05f35.zig:40)
        at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
        at io.quarkus.scheduler.runtime.SimpleScheduler$2.run(SimpleScheduler.java:130)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
 `

We have worked around the problem by running our integration tests (those run with @QuarkusTest) as separate maven-surefire-plugin executions from our unit tests which use Mockito.

**Comment by stuartwdouglas** [comment]
Maybe something weird is happening in the TCCL of the scheduler? The definitely looks scheduler + ClassLoader related. It would be good to capture what the TCCL is at that point.

**Comment by fredmtyro** [comment]
I'm happy to add some more debug output to the project - any tips on exactly what would be helpful to know?

**Comment by stuartwdouglas** [comment]
Basically what the Thread Context ClassLoader is at as many relevant points as possible (e.g. the start of each test, expected failure point, start of scheduled task execution, anywhere else that seems relevant).

**Comment by geoand** [comment]
Is this still an issue with the latest Quarkus versions?

**Comment by fredmtyro** [comment]
Thanks for following up, everything works correctly in Quarkus 2 as far as I can see.

**Comment by famod** [comment]
Thanks for letting us know!
