### ISSUE TITLE
Using @ConfigProperty with Optional<List<String>> throw an exception

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#8294]
**Describe the bug**
Using:
```
    @ConfigProperty(name = "items3")
    Optional<List<String>> getItems3();
```

**Expected behavior**
Return an empty list when unset

**Actual behavior**
Throws an exception:
```
java.lang.IllegalArgumentException: No Converter registered for interface java.util.List

	at io.smallrye.config.SmallRyeConfig.lambda$getConverter$1(SmallRyeConfig.java:202)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.smallrye.config.SmallRyeConfig.getConverter(SmallRyeConfig.java:199)
```

**To Reproduce**
Reproducer:
https://github.com/ia3andy/check-list-config-empty

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.3.1.Final

**Comment by ia3andy** [comment]
@geoand 😇

**Comment by geoand** [comment]
I'll take a look
