### ISSUE TITLE
FaultToleranceDefinitionException: Member applyOn on annotation class com.sun.proxy.$Proxy34 doesn't exist or is not accessible

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#8329]
**Describe the bug**
Small Fault tolerance example code throws ```FaultToleranceDefinitionException: Member applyOn on annotation class com.sun.proxy.$Proxy34 doesn't exist or is not accessible``` with Quarkus 1.3.0.Final and 1.3.1.Final.  It works fine with Quarkus 1.2.1.Final.

**Expected behavior**
Reproducer returns text: "Fallback answer due to timeout"

**Actual behavior**
```
[INFO] --- quarkus-maven-plugin:1.3.1.Final:dev (default-cli) @ demo ---
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-04-01 14:58:42,301 INFO  [io.quarkus] (main) demo 1.0-SNAPSHOT (powered by Quarkus 1.3.1.Final) started in 3.591s. Listening on: http://0.0.0.0:8080
2020-04-01 14:58:42,304 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-04-01 14:58:42,304 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health]
2020-04-01 14:59:24,386 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /data/resilience failed, error id: bbb51b24-5bdb-4a7c-908e-8ea3b42386f2-1: org.jboss.resteasy.spi.UnhandledException: org.eclipse.microprofile.faulttolerance.exceptions.FaultToleranceDefinitionException: Member applyOn on annotation class com.sun.proxy.$Proxy34 doesn't exist or is not accessible
    at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
    at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
    at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:515)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
    at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$589.0000000000000000.run(Unknown Source)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
    at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$590.0000000000000000.get(Unknown Source)
    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
    at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
    at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:122)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:87)
    at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at java.base/java.lang.Thread.run(Thread.java:831)
    at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: org.eclipse.microprofile.faulttolerance.exceptions.FaultToleranceDefinitionException: Member applyOn on annotation class com.sun.proxy.$Proxy34 doesn't exist or is not accessible
    at io.smallrye.faulttolerance.config.GenericConfig.getConfigFromAnnotation(GenericConfig.java:130)
    at io.smallrye.faulttolerance.config.GenericConfig.lambda$lookup$2(GenericConfig.java:118)
    at io.smallrye.faulttolerance.config.GenericConfig$$Lambda$395.00000000A20EEA20.get(Unknown Source)
    at java.base/java.util.Optional.orElseGet(Optional.java:369)
    at io.smallrye.faulttolerance.config.GenericConfig.lookup(GenericConfig.java:118)
    at io.smallrye.faulttolerance.config.GenericConfig.lambda$get$0(GenericConfig.java:78)
    at io.smallrye.faulttolerance.config.GenericConfig$$Lambda$371.0000000000000000.apply(Unknown Source)
    at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
    at io.smallrye.faulttolerance.config.GenericConfig.get(GenericConfig.java:78)
    at io.smallrye.faulttolerance.FaultToleranceInterceptor.toListOfThrowables(FaultToleranceInterceptor.java:503)
    at io.smallrye.faulttolerance.FaultToleranceInterceptor.getSetOfThrowables(FaultToleranceInterceptor.java:498)
    at io.smallrye.faulttolerance.FaultToleranceInterceptor.prepareSyncStrategy(FaultToleranceInterceptor.java:342)
    at io.smallrye.faulttolerance.FaultToleranceInterceptor.lambda$syncFlow$4(FaultToleranceInterceptor.java:195)
    at io.smallrye.faulttolerance.FaultToleranceInterceptor$$Lambda$494.00000000E41056C0.apply(Unknown Source)
    at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
    at io.smallrye.faulttolerance.internal.StrategyCache.getStrategy(StrategyCache.java:23)
    at io.smallrye.faulttolerance.FaultToleranceInterceptor.syncFlow(FaultToleranceInterceptor.java:194)
    at io.smallrye.faulttolerance.FaultToleranceInterceptor.interceptCommand(FaultToleranceInterceptor.java:152)
    at io.smallrye.faulttolerance.FaultToleranceInterceptor_Bean.intercept(FaultToleranceInterceptor_Bean.zig:471)
    at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
    at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
    at com.example.demo.resilient.ResilienceController_Subclass.checkTimeout(ResilienceController_Subclass.zig:72)
    at com.example.demo.resilient.ResilienceController_ClientProxy.checkTimeout(ResilienceController_ClientProxy.zig:80)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
    at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
    at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
    at org.jboss.resteasy.core.ResourceMethodInvoker$$Lambda$594.0000000000000000.get(Unknown Source)
    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
    ... 22 more
```

**To Reproduce**
1. ```curl -O -J 'https://start.microprofile.io/api/project?supportedServer=QUARKUS&selectedSpecs=HEALTH_CHECKS&selectedSpecs=FAULT_TOLERANCE'```
2. ```unzip demo.zip; cd demo```
3. optionally adjust pom.xml to use Quarkus 1.3.1.Final 
4. ```mvn clean compile quarkus:dev```
5. go to http://localhost:8080/data/resilience

If you adjust pom.xml to use Quarkus 1.2.1.Final, you will get a page saying: "Fallback answer due to timeout".

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux local 4.13.16-100 x86_64 GNU/Linux
 - Output of `java -version`: 
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Linux amd64-64-Bit 20191016_322 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)
```
 - GraalVM version (if different from Java):  GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
 - Quarkus version or git rev: 1.3.0.Final, 1.3.1.Final, 1.2.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by jmartisk** [comment]
Seems that's happening because the reproducer's `pom.xml` application declares a dependency on MicroProfile 3.2 while current Quarkus is at 3.3, so the application is somehow using `microprofile-fault-tolerance-api` 2.0 in instead of 2.1. If I change the MP dependency in the pom to 3.3, it works.

**Comment by Karm** [comment]
@jmartisk Dependency on MP 3.2 is intentional here.

**Comment by Karm** [comment]
@jmartisk Unless we want to star building a spreadsheet with what MP version is dropped with which Quarkus version, people expect it to work...

**Comment by jmartisk** [comment]
I agree this should probably work OOTB. The problem is if the application pom imports an older version of a dependency and Quarkus does not know how to work with that older version.
My opinion is that the correct behavior would be that devmode uses the version from Quarkus and doesn't let the application's pom to override that version (?!). In all other running modes, Quarkus seems to pick the version from Quarkus. That sounds inconsistent.

**Comment by mkouba** [comment]
> Dependency on MP 3.2 is intentional here.
> Unless we want to start building a spreadsheet with what MP version is dropped with which Quarkus version, people expect it to work...

I don't think that we can support multiple MP versions given the fact that new versions may break compatibility. In other words, it's more like "best effort". @kenfinnigan and @jclingan know more about our strategy ;-).

**Comment by Karm** [comment]
@mkouba That is a topic to be clearly communicated here: https://wiki.eclipse.org/MicroProfile/Implementation

With my Eclipse MicroProfile hat on, I kinda frown on what you say here.

Users read https://quarkus.io/blog/quarkus-eclipse-microprofile-3-3/ and learn nothing about having to drop MP 3.2.

I believe this thread needs @cealsair and @kenfinnigan to chip in. I would also love to hear from @Ladicek to get some "Thorntail does it this/that way..." point of view.

BTW: The fact that Dev mode is the only one broken makes it all even more fuzzy.

**Comment by jmartisk** [comment]
It's not a problem of MicroProfile 3.3 breaking compatibility for applications written for 3.2, it's a problem of Quarkus being at 3.3 and not expecting that someone will put MP 3.2 on its classpath (which is something else than Quarkus was compiled with), in which case Quarkus would have to detect this and not try to access any constructs which are not present in 3.2. 
Possible, but it would be a big mess.

**Comment by Ladicek** [comment]
I haven't look into this, but I guess it's a classloading issue. I'm pretty sure the `applyOn` attribute (of whatever annotation) is new in MP Fault Tolerance 2.1 (which is in MP 3.3). SmallRye Fault Tolerance 4.1+ (which is currently in Quarkus) implements MP Fault Tolerance 2.1, so it naturally looks for that attribute. But if we have MP Fault Tolerance 2.0 version of the annotation class on classpath, we obviously fail.

I guess the real question here is: why does Quarkus load the user's version of MP Fault Tolerance classes? It should load whatever comes as a dependency of the `quarkus-smallrye-fault-tolerance` extension. Looking at the generated `pom.xml`, it might be because the dependency on `org.eclipse.microprofile:microprofile:3.2` comes sooner than the dependency on `io.quarkus:quarkus-smallrye-fault-tolerance`. On the other hand, `io.quarkus:quarkus-bom` is imported... but only in a profile? Can someone try importing it at the very beginning of the POM?

(Aside: https://ge0ffrey.github.io/maven-dependency-puzzlers/ should be considered mandatory reading for everyone!)

**Comment by Ladicek** [comment]
Ah, one other thing: I see the `org.eclipse.microprofile:microprofile:3.2` dependency is `<scope>provided</scope>`. That's correct. But why does Quarkus load classes from there? That's the right question to ask.

This is not a problem in compatibility with older MicroProfile version, like, at all.

**Comment by jmartisk** [comment]
IMO it's an issue in Quarkus' Maven resolution, in `prod` mode we get the dependency versions which are taken from Quarkus directly, in `dev` and (i think) `test` mode we get the versions which are declared in pom. That's inconsistent and should be unified (I don't know whether to the Quarkus versions or to the pom.xml versions)

**Comment by kenfinnigan** [comment]
1) We will not be supporting multiple MP versions within a single Quarkus release. Thorntail never did that either.

2) I agree that the error is entirely related to having MP 3.2 as a dependency, though provided, on the project. I think it's a two-headed problem, one is that having an entire spec as "provided" might have been the way applications were written with App Servers it's not really the "right way" for microservices, etc. The spec APIs should be exposed by the runtime for use in the compilation. The other issue is the classloading problem others have mentioned.

I think the best approach is to modify the dependency resolution to not favor "provided" dependencies ahead of anything defined through Quarkus dependencies

**Comment by Ladicek** [comment]
I don't think this should be _won't fix_. The classloading issue is real (well, I hope, I didn't try it :-) ). We should get an issue open with minimal reproducer.

(For the record, I think that `<scope>provided</scope>` is something we need to support properly. It's a standard Maven feature that can be used for a myriad of reasons; one particularly common is the lack of compile-only scope.)
