### ISSUE TITLE
Create container within travis

### ISSUE THREAD

**Issue by anthonydenecheau** [quarkusio/quarkus#8346]
Try to create container within travis.
Run this command :
`./mvnw clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=docker
`
I expect to build an image docker and push it to DockerHub.
But mvnw command raise an exception

```
Fatal error: java.lang.NullPointerException
    at sun.reflect.annotation.TypeAnnotationParser.mapTypeAnnotations(TypeAnnotationParser.java:356)
    at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl.<init>(AnnotatedTypeFactory.java:139)
    at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedParameterizedTypeImpl.<init>(AnnotatedTypeFactory.java:240)
    at sun.reflect.annotation.AnnotatedTypeFactory.buildAnnotatedType(AnnotatedTypeFactory.java:77)
    at sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedTypes(TypeAnnotationParser.java:137)
    at java.lang.reflect.Executable.getAnnotatedParameterTypes(Executable.java:688)
    at com.oracle.svm.reflect.target.Target_java_lang_reflect_Executable$AnnotatedParameterTypesComputer.compute(Target_java_lang_reflect_Executable.java:154)
    at com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:264)
    at com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:35)
    at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:100)
    at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:75)
    at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:175)
    at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:344)
    at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:62)
    at com.oracle.graal.pointsto.ObjectScanner$3$1.run(ObjectScanner.java:414)
    at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Environment (please complete the following information):**
 - OS name: "linux", version: "4.4.0-101-generic", arch: "amd64", family: "unix"
 -  java version "1.8.0_151"
 - Quarkus version 1.2.1.Final
 - apache-maven-3.6.1

**Comment by geoand** [comment]
Can you please try with `1.3.1.Final`?

**Comment by anthonydenecheau** [comment]
@geoand : thanks for your support

The update to 1.3.1.Final produced this error
It's much less verbose

Can I send you pom.xml or someting else ?

```
Error: Image build request failed with exit status 137
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:30 min
[INFO] Finished at: 2020-04-02T11:32:55Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.3.1.Final:native-image (default) on project pedigree-service: Failed to generate native image: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:353)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:938)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:273)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
[ERROR] 	at java.lang.Thread.run(Thread.java:748)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:369)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:339)
[ERROR] 	... 12 more
```

**Comment by geoand** [comment]
@anthonydahanne perhaps if you add the `-e` flag to the maven command execution you will find more data in the output?

**Comment by anthonydenecheau** [comment]
I got these warnings

```
[**WARNING**] [io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor] Directly injecting a @ConfigProperty into a JAX-RS provider may lead to unexpected results. To ensure proper results, please change the type of the field to javax.enterprise.inject.Instance<int>. Offending field is '[_MyProperty_]' of class '[_MyClass_]'
```
I notice this : 
```
Status: Downloaded newer image for quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.3.1 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /home/travis/build/[secure]/pedigree-service/target/pedigree-service-1.0-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 2000:2000 --rm quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar pedigree-service-1.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:-IncludeAllTimeZones -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace pedigree-service-1.0-SNAPSHOT-runner
```
Wouldn't there be a version problem with this environment ?

**Comment by anthonydenecheau** [comment]
Then I try to add this to my pom.xml (because it's too slowly)

`<additionalBuildArgs>-J-Xmx6G</additionalBuildArgs>
`
But no way :(
`Exception in thread "ForkJoinPool-2-worker-1" java.lang.OutOfMemoryError: Java heap space`

**Comment by geoand** [comment]
> Wouldn't there be a version problem with this environment ?

Why do you say that?

**Comment by anthonydenecheau** [comment]
See ubi-quarkus  image with tag _java11_ or GraalVM Version 19.3.1 ...

**Comment by geoand** [comment]
I don't see the problem - can you elaborate?

**Comment by anthonydenecheau** [comment]
I will try to avoid thinking by asking questions in writing
I'm Apologize for that

**Comment by geoand** [comment]
No worries!

In any case:

```
Error: Image build request failed with exit status 137
```

is an OutOfMemory expection.

You can experiment with `quarkus.native.native-image.xmx` and whatever settings Travis has for controlling the memory of the executor.

So I am closing this since it's not a Quarkus issue.
If you feel that is should be reopened, feel free to do so after and add your thoughts.
