### ISSUE TITLE
Missing Liquibase properties in native image

### ISSUE THREAD

**Issue by Rupert-RR** [quarkusio/quarkus#8357]
**Describe the bug**
When using Quarkus with a Postgre database (but this may apply to other database types also) and Liquibase, if an (as yet unapplied) database migration uses the `autoIncrement` property on a column the application fails to start with an exception ` java.lang.IllegalStateException: liquibase.exception.UnexpectedLiquibaseException: Property [autoIncrement] was not found for object type [liquibase.datatype.core.IntType]`.

**Expected behavior**
The application should apply the migration and startup without error.

**Actual behavior**
The application crashes while trying to apply the migration.

**To Reproduce**
1. Create and download a new application from the [Start coding](https://code.quarkus.io) page of the Quarkus web site, including the JDBC Driver - PostgreSQL and the Liquibase extensions;
2. Configure the given `application.properties` with the a Postgre datasource and Liquibase migration applied at startup;
3. Add the simple migration given as an [example](https://quarkus.io/guides/liquibase), adding the `autoIncrement="true"` attribute on the `ID` column to `resources/db/changeLog.xml`;
4. Run the application using `./mvnw compile quarkus:dev` and notice that it launches correctly, applying the migration;
5. Stop the application and delete all the tables it created from your Postgre instance;
6. Build the application as a native image using `./mvnw package -Pnative`;
7. Run the native image application by `cd ./target` and ` ./code-with-quarkus-1.0.0-SNAPSHOT-runner`;
8. Notice that the application crashes with the error messages given below.

**Configuration**
```properties
quarkus.datasource.url=jdbc:postgresql://localhost:5432/mypad
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=[your username]
quarkus.datasource.password=[your password]
quarkus.liquibase.change-log=db/changeLog.xml
quarkus.liquibase.migrate-at-start=true
```

**Screenshots**
```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-04-02 15:27:12,596 INFO  [liq.exe.jvm.JdbcExecutor] (main) SELECT COUNT(*) FROM biz.databasechangelog
2020-04-02 15:27:12,597 ERROR [io.qua.application] (main) Failed to start application: java.lang.IllegalStateException: liquibase.exception.UnexpectedLiquibaseException: Property [autoIncrement] was not found for object type [liquibase.datatype.core.IntType]
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:75)
        at io.quarkus.deployment.steps.LiquibaseProcessor$configureRuntimeProperties26.deploy_0(LiquibaseProcessor$configureRuntimeProperties26.zig:98)
        at io.quarkus.deployment.steps.LiquibaseProcessor$configureRuntimeProperties26.deploy(LiquibaseProcessor$configureRuntimeProperties26.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:170)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.Application.run(Application.java:228)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: liquibase.exception.UnexpectedLiquibaseException: Property [autoIncrement] was not found for object type [liquibase.datatype.core.IntType]
        at liquibase.util.ObjectUtil.setProperty(ObjectUtil.java:110)
        at liquibase.datatype.DataTypeFactory.fromDescription(DataTypeFactory.java:251)
        at liquibase.change.core.CreateTableChange.generateStatements(CreateTableChange.java:70)
        at liquibase.change.AbstractChange.generateStatementsVolatile(AbstractChange.java:287)
        at liquibase.change.AbstractChange.warn(AbstractChange.java:358)
        at liquibase.changelog.visitor.ValidatingVisitor.visit(ValidatingVisitor.java:110)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:281)
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:264)
        at liquibase.Liquibase.validate(Liquibase.java:1560)
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.validate(LiquibaseRecorder.java:117)
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:59)
        ... 6 more

Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:256)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.Application.run(Application.java:228)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: java.lang.IllegalStateException: liquibase.exception.UnexpectedLiquibaseException: Property [autoIncrement] was not found for object type [liquibase.datatype.core.IntType]
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:75)
        at io.quarkus.deployment.steps.LiquibaseProcessor$configureRuntimeProperties26.deploy_0(LiquibaseProcessor$configureRuntimeProperties26.zig:98)
        at io.quarkus.deployment.steps.LiquibaseProcessor$configureRuntimeProperties26.deploy(LiquibaseProcessor$configureRuntimeProperties26.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:170)
        ... 3 more
Caused by: liquibase.exception.UnexpectedLiquibaseException: Property [autoIncrement] was not found for object type [liquibase.datatype.core.IntType]
        at liquibase.util.ObjectUtil.setProperty(ObjectUtil.java:110)
        at liquibase.datatype.DataTypeFactory.fromDescription(DataTypeFactory.java:251)
        at liquibase.change.core.CreateTableChange.generateStatements(CreateTableChange.java:70)
        at liquibase.change.AbstractChange.generateStatementsVolatile(AbstractChange.java:287)
        at liquibase.change.AbstractChange.warn(AbstractChange.java:358)
        at liquibase.changelog.visitor.ValidatingVisitor.visit(ValidatingVisitor.java:110)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:281)
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:264)
        at liquibase.Liquibase.validate(Liquibase.java:1560)
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.validate(LiquibaseRecorder.java:117)
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:59)
        ... 6 more
```

**Environment (please complete the following information):**

 - Output of `uname -a` or `ver`: 

```
Darwin machine.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

 - Output of `java -version` (not the version used for building): 
```
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

 - GraalVM version (if different from Java): 

```
graalvm-ce-java11-20.0.0
```

 - Quarkus version or git rev: 

`1.3.1.Final`

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

```
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.0.0/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```

**Comment by Rupert-RR** [comment]
It should be noted that the `addAutoIncrement` change type works fine, so we can create columns without the autoincrement initially then add the autoincrement in a separate changeset.

**Comment by gsmet** [comment]
@andrejpetras could you have a look at that one?

Thanks!

**Comment by andrejpetras** [comment]
@gsmet Yeah sure, I'll have a look later today

**Comment by andrejpetras** [comment]
@Rupert-RR Yes, I can reproduce the bug. There are missing register methods for native image.

@gsmet we need to register more methods of Liquibase classes for native image

**Comment by Rupert-RR** [comment]
@andrejpetras Thanks for having a look.

**Comment by machi1990** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/8368
