### ISSUE TITLE
ArC - Tests fails on eCryptfs directories

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#8385]
**Describe the bug**
Running `./mvnw install -DskipITs -DskipDocs` from an [eCryptfs](https://www.ecryptfs.org/) directory results in `ARC - Tests` failure. eCryptfs developers [suggest](https://unix.stackexchange.com/a/32834/14050) using filenames that are less than 140 characters long. However, `ARC - Tests` generates a class file named `ProducerOnClassWithoutBeanDefiningAnnotationTest_StringProducerMethod_ProducerMethod_observeString_feacd4958fb4a4ba9d99488a42ca265cf027b6b1_Bean.class` which is 151 characters long resulting in a failure.

**Expected behavior**
Test should succeed.

**Actual behavior**
Test fails with
```
...
[INFO] Running io.quarkus.arc.test.producer.discovery.ProducerOnClassWithoutBeanDefiningAnnotationTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.005 s <<< FAILURE! - in io.quarkus.arc.test.producer.discovery.ProducerOnClassWithoutBeanDefiningAnnotationTest
[ERROR] testObserver  Time elapsed: 0.004 s  <<< ERROR!
java.lang.IllegalStateException: Error generating resources
	at io.quarkus.arc.test.ArcTestContainer.init(ArcTestContainer.java:384)
	at io.quarkus.arc.test.ArcTestContainer.beforeEach(ArcTestContainer.java:252)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:161)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:197)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:160)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.nio.file.FileSystemException: /home/zakkak/code/quarkus/independent-projects/arc/tests/target/test-classes/io/quarkus/arc/test/producer/discovery/ProducerOnClassWithoutBeanDefiningAnnotationTest_StringProducerMethod_ProducerMethod_observeString_feacd4958fb4a4ba9d99488a42ca265cf027b6b1_Bean.class: File name too long
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
	at java.base/java.nio.file.Files.write(Files.java:3424)
	at io.quarkus.arc.processor.ResourceImpl.writeTo(ResourceImpl.java:57)
	at io.quarkus.arc.test.ArcTestContainer$1.writeResource(ArcTestContainer.java:356)
	at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:229)
	at io.quarkus.arc.processor.BeanProcessor.process(BeanProcessor.java:252)
	at io.quarkus.arc.test.ArcTestContainer.init(ArcTestContainer.java:382)
	... 48 more

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AlternativePriorityAnnotationTest.testAnnotationWorks » IllegalState Error gen...
[ERROR]   ProducerOnClassWithoutBeanDefiningAnnotationTest.testObserver » IllegalState E...
[INFO] 
[ERROR] Tests run: 164, Failures: 0, Errors: 2, Skipped: 0
```

**To Reproduce**
1. Create an encrypted directory using eCryptfs `sudo mount -t ecryptfs /tmp/encrypted /tmp/encrypted`. Accept the defaults except for filename encryption (enable it).
2. Clone quarkus in the directory
3. `cd /tmp/encrypted/quarkus/independent-projects/arc/` 
3. Run `mvn install -DskipITs -DskipDocs` 

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux slimbee 5.4.27-1-MANJARO #1 SMP PREEMPT Sat Mar 21 16:33:27 UTC 2020 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10)
OpenJDK 64-Bit Server VM (build 11.0.6+10, mixed mode)
```
 - Quarkus version or git rev: 
```
2ca4b60ca6fb9ea4b9c2533de42b8db6a82c4943
```
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
```

**Comment by zakkak** [comment]
As a workaround I am currently using only the first 20 digits of the SHA1 hash.

```diff
diff --git a/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Hashes.java b/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Hashes.java
index f1f97f4b9..fbe096c5b 100644
--- a/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Hashes.java
+++ b/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/Hashes.java
@@ -10,8 +10,8 @@ final class Hashes {
         try {
             MessageDigest md = MessageDigest.getInstance("SHA-1");
             byte[] digest = md.digest(value.getBytes(StandardCharsets.UTF_8));
-            StringBuilder sb = new StringBuilder(40);
-            for (int i = 0; i < digest.length; ++i) {
+            StringBuilder sb = new StringBuilder(20);
+            for (int i = 0; i < 10; ++i) {
                 sb.append(Integer.toHexString((digest[i] & 0xFF) | 0x100).substring(1, 3));
             }
             return sb.toString()
```

**Comment by stuartwdouglas** [comment]
I don't think we are going to support filesystems that are so limited, especially not for building Quarkus itself. 

The actual build of an application assembles files in memory, so this should not be a problem.
