### ISSUE TITLE
kotlin changes to code cause hot-reload fail with error: Intercepted bean must not be final

### ISSUE THREAD

**Issue by xmlking** [quarkusio/quarkus#8404]
How to reproduce:
git clone https://github.com/xmlking/micro-apps.git
gradle :apps:greeting-service:quarkusDev

now change code in  `GreetingResource.kt` and reload page `http://localhost:8080/api/v1/greeting` 

Error when reloading page:
**Intercepted bean must not be final: CLASS bean [types=[micro.apps.greeting.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=micro.apps.greeting.GreetingResource]**

I already open these classes  with `allopen` plugin

https://github.com/xmlking/micro-apps/blob/develop/apps/greeting-quarkus/build.gradle.kts#L2

```
The stacktrace below has been reversed to show the root cause first. Click Here to see the original stacktrace

javax.enterprise.inject.spi.DefinitionException: Intercepted bean must not be final: CLASS bean [types=[micro.apps.greeting.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=micro.apps.greeting.GreetingResource]
	at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:364)
	at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:962)
	at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:319)
	at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:134)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:297)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:938)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:273)
	at io.quarkus.builder.BuildContext$$Lambda$163/0000000000000000.run(Unknown Source)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Resulted in: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.spi.DefinitionException: Intercepted bean must not be final: CLASS bean [types=[micro.apps.greeting.GreetingResource, java.lang.Object], qualifiers=[@Default, @Any], target=micro.apps.greeting.GreetingResource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:910)
	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:138)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:321)
	... 13 more
```

**Comment by geoand** [comment]
I am pretty sure that this has already been fixed in `master`. Would you be willing to give it a try?

**Comment by xmlking** [comment]
sure I need to try other issues also which is fixed in master.
could you please guide my how to get master SNAPSHOT dependencies? or should I have to build myself ?
Thanks

**Comment by geoand** [comment]
You can build quarkus from `master` using `./mvnw clean install -DskipTests -DskipITs -DskipDocs`.

and then use `quarkus-bom` instead of `quarkus-universe-bom`.

**Comment by xmlking** [comment]
built local quarkus and using `999-SNAPSHOT` now. 

**Result: hot-reload is completely disabled...**

I have to restart server to get new changes applied :(.

```
10:17:58 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 1.873s. Listening on: http://0.0.0.0:8080
```

```
gradle :apps:greeting-quarkus:quarkusDev

> Configure project :
Version: 1.6.1-SNAPSHOT,  Branch: develop, isCI: false
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
10:17:57 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.container-image.build" was provided; it will be ignored
10:17:57 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.kubernetes.part-of" was provided; it will be ignored
10:17:57 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.kubernetes.version" was provided; it will be ignored
10:17:57 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.container-image.group" was provided; it will be ignored
10:17:57 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.kubernetes.labels.foo" was provided; it will be ignored
10:17:57 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.kubernetes.name" was provided; it will be ignored
10:17:58 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 1.873s. Listening on: http://0.0.0.0:8080
10:17:58 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
10:17:58 INFO  [io.quarkus] (main) Installed features: [cdi, kotlin, resteasy, resteasy-jsonb, smallrye-health, smallrye-metrics, smallrye-openapi, swagger-ui]
```

**Comment by geoand** [comment]
OK, thanks for checking

**Comment by geoand** [comment]
Is this still an issue with `1.4.0.CR1`?

**Comment by xmlking** [comment]
will test and let you know.

**Comment by evanchooly** [comment]
related #9856

**Comment by evanchooly** [comment]
It would appear this is fixed in the latest release.  @xmlking if you can confirm this for me, i can close this one out.

**Comment by xmlking** [comment]
will test and conform ASAP

**Comment by xmlking** [comment]
yes it works now. Thanks a lot.
