### ISSUE TITLE
SmallRyeFaultToleranceProcessor#hasFTAnnotations(line 222) - crashes on java.lang.Object Beans -> no Super Class

### ISSUE THREAD

**Issue by banovp** [quarkusio/quarkus#8436]
**Describe the bug**
Version 1.3.1. In case a cdi bean does not have a super class -> java.lang.Object, we are getting:
```
java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.faulttolerance.deployment.SmallRyeFaultToleranceProcessor#validateFaultToleranceAnnotations threw an exception: java.lang.IllegalArgumentException: Cannot lookup class, provided DotName was null.
	at io.quarkus.arc.processor.IndexClassLookupUtils.getClassByName(IndexClassLookupUtils.java:41)
	at io.quarkus.arc.processor.BeanArchives$IndexWrapper.getClassByName(BeanArchives.java:103)
	at io.quarkus.smallrye.faulttolerance.deployment.SmallRyeFaultToleranceProcessor.hasFTAnnotations(SmallRyeFaultToleranceProcessor.java:224)
	at io.quarkus.smallrye.faulttolerance.deployment.SmallRyeFaultToleranceProcessor.validateFaultToleranceAnnotations(SmallRyeFaultToleranceProcessor.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
 
suggestion would be to add at line 222 in SmallRyeFaultToleranceProcessor:
```
if(parentClassName == null) return false;
```
for instance the method hasFTAnnotaions would look like that:

```
private boolean hasFTAnnotations(IndexView index, AnnotationStore annotationStore, ClassInfo info) {
        // first check annotations on type
        if (annotationStore.hasAnyAnnotation(info, FT_ANNOTATIONS)) {
            return true;
        }

        // then check on the methods
        for (MethodInfo method : info.methods()) {
            if (annotationStore.hasAnyAnnotation(method, FT_ANNOTATIONS)) {
                return true;
            }
        }

        // then check on the parent
        DotName parentClassName = info.superName();
        if(parentClassName == null){
            return false;
        }

        ClassInfo parentClassInfo = index.getClassByName(parentClassName);
        if (parentClassName.equals(DotNames.OBJECT) || parentClassInfo == null) {
            return false; //no more parents
        }

        return hasFTAnnotations(index, annotationStore, parentClassInfo);
    }
```

**Expected behavior**
no exception

**To Reproduce**
1.  Use myfaces 2.3-next-M2 (download from github and build it) with quarkus 1.3.1.Final.
2. Not able to run QuakrusTests or start the quarkus server

https://github.com/apache/myfaces
e.g. add those dependencies

```
       <dependency>
            <groupId>org.apache.myfaces.core.extensions.quarkus</groupId>
            <artifactId>myfaces-quarkus-deployment</artifactId>
            <version>2.3-next-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.apache.myfaces.core.extensions.quarkus</groupId>
            <artifactId>myfaces-quarkus-runtime</artifactId>
            <version>2.3-next-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.apache.myfaces.core</groupId>
            <artifactId>myfaces-api</artifactId>
            <version>2.3-next-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.apache.myfaces.core</groupId>
            <artifactId>myfaces-impl</artifactId>
            <version>2.3-next-SNAPSHOT</version>
        </dependency>
```

**Comment by gsmet** [comment]
@Ladicek @jmartisk any chance you could have a look at that one today?

**Comment by jmartisk** [comment]
I've submitted a PR
