### ISSUE TITLE
Kafka WeavingException: Unable to connect stream `events`

### ISSUE THREAD

**Issue by Meemaw** [quarkusio/quarkus#8494]
**Describe the bug**
(Describe the problem clearly and concisely.)
**Expected behavior**
I'm trying to integrate Kafka into Quarkus and write some tests for it. I'm using `quarkus-smallrye-reactive-messaging-kafka` extension and it seems to work fine in `quarkusDev`. However, when I run tests I receive an error:

```java
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
...
Caused by: javax.enterprise.inject.spi.DeploymentException: io.smallrye.reactive.messaging.WeavingException: Unable to connect stream `events` (com.meemaw.session.ws.v1.SessionResource#process) - several publishers are available (2), use the @Merge annotation to indicate the merge strategy.
	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:214)
	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:100)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
	... 78 more
Caused by: io.smallrye.reactive.messaging.WeavingException: Unable to connect stream `events` (com.meemaw.session.ws.v1.SessionResource#process) - several publishers are available (2), use the @Merge annotation to indicate the merge strategy.
	at io.smallrye.reactive.messaging.extension.MediatorManager.getAggregatedSource(MediatorManager.java:375)
	at io.smallrye.reactive.messaging.extension.MediatorManager.lambda$weaving$4(MediatorManager.java:234)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at io.smallrye.reactive.messaging.extension.MediatorManager.weaving(MediatorManager.java:228)
	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:212)
	... 80 more
```

Note that this only happens when running tests. I can however "quiet" the warning if I add the `@Merge` annotation.

**To Reproduce**
1. git clone -b no-blueprintjs git@github.com:Meemaw/Insight.git repro
2. cd repro/backend
3. ./gradlew session-service:test

**Configuration**
```properties
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000,http://localhost:3002
quarkus.smallrye-openapi.path=/openapi
quarkus.http.port=8081
%dev.quarkus.log.console.json=false
%test.quarkus.log.console.json=false
%test.quarkus.http.host=localhost

# tag::adocKafka[]
## Kafka configuration
mp.messaging.incoming.events.connector=smallrye-kafka
mp.messaging.incoming.events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
# end::adocKafka[]
```

**Environment (please complete the following information):**
 - Output of `java -version`: openjdk version "13" 2019-09-17
 - Quarkus version or git rev: 1.3.0 Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.3.0

**Comment by jeremyrdavis** [comment]
@Meemaw did you find a solution that did not involve adding the @Merge annotation?
