### ISSUE TITLE
Only specifying named datasources (no default) fails with "cannot guess the dialect"

### ISSUE THREAD

**Issue by michael-schnell** [quarkusio/quarkus#8547]
**Describe the bug**
Only specifying named datasources and no default datasource fails with the following exception:

```
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build threw an exception: io.quarkus.deployment.configuration.ConfigurationError: Hibernate extension cannot guess the dialect as no database kind is specified by 'quarkus.datasource.db-kind'
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.guessDialect(HibernateOrmProcessor.java:870)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.handleHibernateORMWithNoPersistenceXml(HibernateOrmProcessor.java:689)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.build(HibernateOrmProcessor.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:931)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

Example for a failing config:

```
# DATABASE Tenant 'base' Configuration
quarkus.datasource.base.db-kind=postgresql
quarkus.datasource.base.username=quarkus_test
quarkus.datasource.base.password=quarkus_test
quarkus.datasource.base.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_test
quarkus.datasource.base.jdbc.max-size=8
quarkus.datasource.base.jdbc.min-size=2

# DATABASE Tenant 'mycompany' Configuration
quarkus.datasource.mycompany.db-kind=postgresql
quarkus.datasource.mycompany.username=mycompany
quarkus.datasource.mycompany.password=mycompany
quarkus.datasource.mycompany.jdbc.url=jdbc:postgresql://localhost:5433/mycompany
quarkus.datasource.mycompany.jdbc.max-size=8
quarkus.datasource.mycompany.jdbc.min-size=2
```

Same with an additional default datasource works fine:

```
# Default Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus_test
quarkus.datasource.password=quarkus_test
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_test
quarkus.datasource.jdbc.max-size=8
quarkus.datasource.jdbc.min-size=2

# DATABASE Tenant 'base' Configuration
quarkus.datasource.base.db-kind=postgresql
quarkus.datasource.base.username=quarkus_test
quarkus.datasource.base.password=quarkus_test
quarkus.datasource.base.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_test
quarkus.datasource.base.jdbc.max-size=8
quarkus.datasource.base.jdbc.min-size=2

# DATABASE Tenant 'mycompany' Configuration
quarkus.datasource.mycompany.db-kind=postgresql
quarkus.datasource.mycompany.username=mycompany
quarkus.datasource.mycompany.password=mycompany
quarkus.datasource.mycompany.jdbc.url=jdbc:postgresql://localhost:5433/mycompany
quarkus.datasource.mycompany.jdbc.max-size=8
quarkus.datasource.mycompany.jdbc.min-size=2
```

**Expected behavior**
A default datasource should not be required in case only named ones are wanted.

**Actual behavior**
Build fails without a default datasource.

**Comment by wolfomat** [comment]
having a reactive datasource as default with a named datasource results in this:

2021-03-26 10:18:00,200 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.datasource.init-update.jdbc.url" was provided; it will be ignored; verify that the dependency extension for this configuration is set or you did not make a typo

application.properties:

```
# mariadb-reactive-configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=partner_usr
quarkus.datasource.password=acme10
quarkus.datasource.reactive.url=vertx-reactive:mysql://localhost:3310/partnerdb
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
#quarkus.hibernate-orm.packages=de.acme.model

quarkus.datasource.init-update.db-kind=mysql
quarkus.datasource.init-update.username=partner_usr
quarkus.datasource.init-update.password=acme10
quarkus.datasource.init-update.jdbc.url=jdbc:mysql://localhost:3310/partnerdb

quarkus.hibernate-orm.init-update.log.sql=true
quarkus.hibernate-orm.init-update.packages=de.acme.model
quarkus.hibernate-orm.init-update.database.generation=drop-and-create

```

**Comment by geoand** [comment]
Closing for lack of feedback
