### ISSUE TITLE
Native mode fails with "Type `org.flywaydb.core.Flyway` can not be instantiated reflectively"

### ISSUE THREAD

**Issue by michael-schnell** [quarkusio/quarkus#8548]
**Describe the bug**
Flyway migration works fine at runtime, but fails in native mode with error "Type `org.flywaydb.core.Flyway` can not be instantiated reflectively":

```
2020-04-13 12:06:19,955 ERROR [io.qua.application] (main) Failed to start application: java.lang.RuntimeException: java.lang.InstantiationException: Type `org.flywaydb.core.Flyway` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at io.quarkus.arc.runtime.ArcRecorder$DefaultInstanceFactory.create(ArcRecorder.java:159)
	at io.quarkus.arc.runtime.BeanContainer.instance(BeanContainer.java:19)
	at io.quarkus.flyway.runtime.FlywayRecorder.migrate(FlywayRecorder.java:57)
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:47)
	at io.quarkus.deployment.steps.FlywayProcessor$configureRuntimeProperties68.deploy_0(FlywayProcessor$configureRuntimeProperties68.zig:98)
	at io.quarkus.deployment.steps.FlywayProcessor$configureRuntimeProperties68.deploy(FlywayProcessor$configureRuntimeProperties68.zig:36)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:211)
	at io.quarkus.runtime.Application.start(Application.java:88)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.lang.InstantiationException: Type `org.flywaydb.core.Flyway` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:820)
	at io.quarkus.arc.runtime.ArcRecorder$DefaultInstanceFactory.create(ArcRecorder.java:151)
	... 12 more
```
**Expected behavior**
Same configuration should work at runtime **and** in native mode.

**Actual behavior**
Native mode works not correctly.

**To Reproduce**
1. Checkout fork with new [Hibernate ORM Multitenancy](https://github.com/michael-schnell/quarkus) feature 
2. Run `./mvnw install -DskipTests -DskipITs -DskipDocs`
3. Checkout fork with new [Hibernate ORM Multitenancy Quickstart](https://github.com/michael-schnell/quarkus-quickstarts/tree/master/hibernate-orm-quickstart-multi-tenancy)
4. Run `./mvnw clean verify -Pnative` just for that project
5. Run `./mvnw quarkus:dev -Dquarkus.profile=database` (Works fine)
6. Run `./target/hibernate-orm-quickstart-multi-tenancy-1.0-SNAPSHOT-runner -Dquarkus.profile=database` (Fails with above exception)

**Configuration**
See [application.properties](https://github.com/michael-schnell/quarkus-quickstarts/blob/master/hibernate-orm-quickstart-multi-tenancy/src/main/resources/application.properties)

**Environment (please complete the following information):**
 - Linux quarkus-vm 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - openjdk version "1.8.0_242"
 - OpenJDK Runtime Environment (build 1.8.0_242-b06)
 - OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 25.242-b06-jvmci-20.0-b02, mixed mode)
 - Quarkus version: 999-SNAPSHOT

**Comment by michael-schnell** [comment]
Works fine now. The issue was to use the profile switch at compilation time:

`
./mvnw package -Pnative -Dquarkus.profile=database
`
