### ISSUE TITLE
Vertx OAuth2 runs the blocking quarkus-oidc calls in the event loop 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#8559]
**Describe the bug**
Pedro @pedroigor has found out that when `quarkus-oidc` runs a blocking operation such as a refresh token grant request, it will be executed by Vertx OAuth2 in the event loop as opposed to by the executor thread.

CC @pedroigor @stuartwdouglas

**Comment by sberyozkin** [comment]
@stuartwdouglas Hi, this is probably not related to this issue, but I've been wondering, would it be possible somehow to get the context switching going on demand. For example, right now, we have to make the decision quite early whether to run the request on the IO thread or as blocking. 
With `TenantContextResolver` we can optimize, but if a refreshing token is supported then we do it too early, and with the Vertx Auth JWK refresh strategy we will have an event which will give us an option to fetch JWKs remotely, but this even will be on the IO thread I believe, etc...

**Comment by stuartwdouglas** [comment]
If you are on the IO thread you can switch at any point, as long as you have designed your API's to allow it.

**Comment by sberyozkin** [comment]
Hi Stuart @stuartwdouglas and also Clement @cescoffier, here is my [initial attempt](https://github.com/quarkusio/quarkus/compare/master...sberyozkin:oidc_blocking_call_just_in_time?expand=1) at trying to do the blocking calls just in time.

FYI, there are few cases where we expect the blocking calls in the OIDC code flow, this PR only focuses for now on:
1. If the token has expired and `refresh-expired` is enabled then we will try to refresh using the remote Vertx OAuth2 call.

Here is the summary of what is happening without this PR:
1. OIDC `CodeAuthenticationMechanism` is asked to authenticate, it prepares the tokens and then `OidcIdentityProvider` is invoked to validate the tokens and return `SecurityIdentity`
2. `OidcIdentityProvider` will fail if the ID token has expired.
3.  `CodeAuthenticationMechanism` will try to recover by refreshing the tokens.
4. The problem: because refreshing the token requires a blocking call, all the calls will be run in the blocking mode even if the tokens will not be expired and no refreshing the tokens will be needed, and also due to the fact that the blocking call option is only available at the top of the `OidcIdentityProvider` call chain.

So this PR:
1. Saves `AuthenticationRequestContext` as a `RoutingContext` attribute
2. Does not require running all the `OidcIdentityProvider` calls if the `refresh-expired` is enabled
3. Tries to run the blocking call just in time in the Uri recovery handler

However postponing doing the call in a blocking way does not work, the error to do with the blocked thread is reported:
```
2020-08-31 13:00:13,454 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-8,5,main]=Thread[vert.x-eventloop-thread-8,5,main] has been blocked for 1170463 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at io.smallrye.mutiny.operators.UniBlockingAwait.await(UniBlockingAwait.java:55)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:42)
	at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$2.apply(CodeAuthenticationMechanism.java:136)
	at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$2.apply(CodeAuthenticationMechanism.java:110)
	at io.smallrye.mutiny.groups.UniOnFailure.lambda$recoverWithItem$6(UniOnFailure.java:152)
	at io.smallrye.mutiny.groups.UniOnFailure$$Lambda$914/1887491982.apply(Unknown Source)
	at io.smallrye.mutiny.operators.UniOnItemTransformToUni.invokeAndSubstitute(UniOnItemTransformToUni.java:31)
	at io.smallrye.mutiny.operators.UniOnFailureFlatMap$1.onFailure(UniOnFailureFlatMap.java:47)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onFailure(UniSerializedSubscriber.java:85)
	at io.smallrye.mutiny.operators.UniDelegatingSubscriber.onFailure(UniDelegatingSubscriber.java:29)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onFailure(UniSerializedSubscriber.java:85)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onFailure(UniSerializedSubscriber.java:85)
	at io.smallrye.mutiny.operators.DefaultUniEmitter.fail(DefaultUniEmitter.java:52)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$2$1.handle(OidcIdentityProvider.java:96)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$2$1.handle(OidcIdentityProvider.java:92)
	at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.lambda$decodeToken$6(OAuth2AuthProviderImpl.java:342)
	at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl$$Lambda$912/1853026050.handle(Unknown Source)
	at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.authenticate(OAuth2AuthProviderImpl.java:305)
	at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.decodeToken(OAuth2AuthProviderImpl.java:338)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$2.accept(OidcIdentityProvider.java:91)
	at io.quarkus.oidc.runtime.OidcIdentityProvider$2.accept(OidcIdentityProvider.java:87)
	at io.smallrye.mutiny.operators.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at io.smallrye.mutiny.operators.UniCreateFromDeferredSupplier.subscribing(UniCreateFromDeferredSupplier.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at io.smallrye.mutiny.operators.UniOnItemTransform.subscribing(UniOnItemTransform.java:19)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at io.smallrye.mutiny.operators.UniOnFailureFlatMap.subscribing(UniOnFailureFlatMap.java:29)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at io.smallrye.mutiny.operators.UniCache.lambda$subscribing$0(UniCache.java:37)
	at io.smallrye.mutiny.operators.UniCache$$Lambda$858/1094929566.run(Unknown Source)
	at io.smallrye.mutiny.operators.UniCache.subscribing(UniCache.java:65)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:100)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:1)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:80)
	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:1)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:54)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:36)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:392)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$9.handle(VertxHttpRecorder.java:1)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:133)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:1)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
	at io.vertx.core.net.impl.VertxHandler$$Lambda$766/1695860511.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

note

```
	at io.quarkus.oidc.runtime.CodeAuthenticationMechanism$2.apply(CodeAuthenticationMechanism.java:136)
```

This is part of the new PR, at the point where a response from the blocking call is awaited.

Can you can spot some problem with this PR or explain how to avoid blocking the thread ?
thanks
