### ISSUE TITLE
YAML Config does not allow child values 

### ISSUE THREAD

**Issue by codeninja55** [quarkusio/quarkus#8568]
**Describe the bug**
When using YAML Config (`quarkus-config-yaml`), you cannot achieve some of the configurations that are both values and a branch. 

**Expected behavior**
Doing something like this in an `application.properties`:

```
quarkus.log.console.json=true
quarkus.log.console.json.date-format=default
```

One would try to achieve this perhaps with: 

```
quarkus:
  log:
    console:
      json: true 
        date-format: "default" 
```

Should be able to be achieved as part of a YAML config extension.

**Actual behavior**
Doing the above causes the error:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: mapping values are not allowed here
 in 'reader', line 70, column 22:
              date-format: "default"
                         ^

	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:117)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:54)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: mapping values are not allowed here
 in 'reader', line 70, column 22:
              date-format: "default"
                         ^
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: mapping values are not allowed here
```

**Comment by famod** [comment]
"Child values" in general do work for me in 1.3.1.Final. Which version are you using?

**Comment by dmlloyd** [comment]
This is a YAML syntax error.  The correct way to represent this in YAML would be:

```yaml
quarkus:
  log:
    console:
      json:
        ~: true
        date-format: "default"
```

Basically, a YAML key cannot contain both a simple value and subkeys.

**Comment by geoand** [comment]
Closing as the supplied configuration is not valid.

Please reopen if you continue to have issues with the proper syntax
