### ISSUE TITLE
OpenTracing quickstart native build failing

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#8578]
The OpenTracing quickstart native build is failing with current Quarkus master + quickstart development branch:

https://github.com/quarkusio/quarkus-quickstarts/runs/586602480?check_suite_focus=true
```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.jaeger.runtime.QuarkusJaegerMetricsFactory.<init>(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
	at parsing io.quarkus.jaeger.runtime.QuarkusJaegerTracer.tracer(QuarkusJaegerTracer.java:45)
Call path from entry point to io.quarkus.jaeger.runtime.QuarkusJaegerTracer.tracer(): 
	at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.tracer(QuarkusJaegerTracer.java:42)
	at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.toString(QuarkusJaegerTracer.java:31)
	at java.lang.String.valueOf(String.java:2994)
	at java.nio.charset.IllegalCharsetNameException.<init>(IllegalCharsetNameException.java:55)
	at java.nio.charset.Charset.checkName(Charset.java:315)
	at com.oracle.svm.core.jdk.Target_java_nio_charset_Charset.lookup(CharsetSubstitutions.java:78)
	at java.nio.charset.Charset.isSupported(Charset.java:505)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_nio_charset_Charset_2_0002eisSupported_00028Ljava_lang_String_2_00029Z(generated:0)
```

**Comment by gsmet** [comment]
@Ladicek could it be related to your latest adjustments?

**Comment by geoand** [comment]
I am seeing this fail in our Jenkins as well.

**Comment by Ladicek** [comment]
Indeed this looks like it's connected to the change that is supposed to selectively enable/disable OpenTracing metrics. I'll take a look.
