### ISSUE TITLE
Evaluate ImageIO compatibility with GraalVM Native Image

### ISSUE THREAD

**Issue by murphye** [quarkusio/quarkus#8605]
**Describe the bug**
ImageIO is now enabled in Quarkus 1.4.0. 
https://github.com/quarkusio/quarkus/pull/8453

However, not all is good, as ImageIO has a plugin architecture and not all plugins work that are normally installed in the JRE, such as `com.sun.imageio.plugins.jpeg.JPEGImageReader`

According to the comment in this thread, PNGImageReader is working, however:
https://stackoverflow.com/questions/60527663/is-javax-imageio-supported-by-graalvm-native-image

**Expected behavior**
All ImageIO plugins work.

**Actual behavior**
Unknown how many plugins work by default with Native Image, or if the GraalVM is tracking.

**To Reproduce**
1. Try using ImageIO.read on a JPEG
2. Observe java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 11
 - GraalVM version (if different from Java): 20.0.0
 - Quarkus version or git rev: 1.4.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**

This is a GraalVM issue, but filing at the request of George Gastaldi.

**Comment by murphye** [comment]
Advise reaching out to GraalVM team and find out of they are tracking ImageIO compatibility.

**Comment by murphye** [comment]
https://github.com/oracle/graal/issues/2620

**Comment by Rohit-nagbhidkar** [comment]
Still having error while calling ImageIO.read on jpeg files
using quarkus native image 20.3.1
Exception in thread "Lambda Thread" java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader()J [symbol: Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader or Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader__]
--
at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
at com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader(JPEGImageReader.java)
at com.sun.imageio.plugins.jpeg.JPEGImageReader.<init>(JPEGImageReader.java:232)
at com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:532)
at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:516)
at javax.imageio.ImageIO.read(ImageIO.java:1463)
at javax.imageio.ImageIO.read(ImageIO.java:1363)

**Comment by zakkak** [comment]
This issue should be fixed by https://github.com/oracle/graal/pull/3032 in GraalVM CE 21.0.

Upgrading to 21.0 is work in progress (see https://github.com/quarkusio/quarkus/pull/14512) but you should be able to test if it solves the issue with:
`-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:20.3-java11`

**Comment by Rohit-nagbhidkar** [comment]
> This issue should be fixed by [oracle/graal#3032](https://github.com/oracle/graal/pull/3032) in GraalVM CE 21.0.
> 
> Upgrading to 21.0 is work in progress (see #14512) but you should be able to test if it solves the issue with:
> `-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:21.0-java11`

getting `Error: Runtime exited with error: signal: segmentation fault (core dumped) Runtime.ExitError` after using ubi-quarkus-native-image:21.0-java11

**Comment by zakkak** [comment]
@Rohit-nagbhidkar thanks for testing. 

Could you please share a reproducer and let us know whether you tried with the latest `master` or with `1.11.0.Final`?

**Comment by Rohit-nagbhidkar** [comment]
> @Rohit-nagbhidkar thanks for testing.
> 
> Could you please share a reproducer and let us know whether you tried with the latest `master` or with `1.11.0.Final`?

i have tested with 1.11.0.Final
