### ISSUE TITLE
Exceptions thrown in bootstrap recorders prevent logging

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#8624]

**Comment by rsvoboda** [comment]
@geoand how can be this issue reproduced (with older Quarkus version)?

**Comment by geoand** [comment]
@rsvoboda the easiest way I can think of to reproduce this issue, is to take the integration test: https://github.com/quarkusio/quarkus/tree/1.3.2.Final/integration-tests/spring-cloud-config-client

and change https://github.com/quarkusio/quarkus/blob/1.3.2.Final/integration-tests/spring-cloud-config-client/src/main/resources/__files/a-bootiful-client-prod.json to some invalid JSON.

The native test will fail of course, but with the current code you would see something like

```
 Unable to obtain configuration from Spring Cloud Config Server ...
``` 

in the logs. With the 1.3.2.Final code, the application logs will be completely empty.

**Comment by rsvoboda** [comment]
Thanks!

**Comment by rsvoboda** [comment]
@geoand I'm wondering why is this problem with invalid json file visible just in native mode. Can you give me some hints?

**Comment by rsvoboda** [comment]
ah, for surefire run it uses message from application.properties

**Comment by geoand** [comment]
Exactly, it's just about how this particular test is setup

**Comment by rsvoboda** [comment]
I did some standalone experiments but didn't notice any missing logs so I went back to spring-cloud-config-client test on 1.3.2.Final tag

Did the following change and executed `mvn clean verify -Dnative`:
```diff
--- a/integration-tests/spring-cloud-config-client/src/main/resources/__files/a-bootiful-client-prod.json
+++ b/integration-tests/spring-cloud-config-client/src/main/resources/__files/a-bootiful-client-prod.json
@@ -10,7 +10,7 @@
     {
       "name": "https://github.com/spring-cloud-samples/config-repo/testapp-prod.yml",
       "source": {
-        "bar": "spam",
+        "bar" "spam",
         "foo": "from foo development",
         "greeting.message": "hello from spring cloud config server"
       }
```

I think I see all the logs, @geoand what should be missing?

What I see is this:
```
[INFO] Running io.quarkus.spring.cloud.config.client.runtime.GreetingResourceIT
Executing [/Users/rsvoboda/git/quarkus/integration-tests/spring-cloud-config-client/target/quarkus-integration-test-spring-cloud-config-client-1.3.2.Final-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
[INFO] RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-05-20 15:35:13,172 ERROR [io.qua.spr.clo.con.cli.run.SpringCloudConfigServerClientConfigSourceProvider] (main) Unable to obtain configuration from Spring Cloud Config Server at http://localhost:8089: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('"' (code 34)): was expecting a colon to separate field name and value
 at [Source: (String)"{
  "name": "a-bootiful-client",
  "profiles": [
    "prod"
  ],
  "label": "master",
  "version": "bb51f4173258ae3481c61b95b503c13862ccfba7",
  "state": null,
  "propertySources": [
    {
      "name": "https://github.com/spring-cloud-samples/config-repo/testapp-prod.yml",
      "source": {
        "bar" "spam",
        "foo": "from foo development",
        "greeting.message": "hello from spring cloud config server"
      }
    },
    {
      "name": "https://github.com/spring-cloud-samples/co"[truncated 124 chars]; line: 13, column: 9] (through reference chain: io.quarkus.spring.cloud.config.client.runtime.Response["propertySources"]->java.util.ArrayList[0]->io.quarkus.spring.cloud.config.client.runtime.Response$PropertySource["source"])
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at io.quarkus.spring.cloud.config.client.runtime.DefaultSpringCloudConfigClientGateway.exchange(DefaultSpringCloudConfigClientGateway.java:74)
	at io.quarkus.spring.cloud.config.client.runtime.SpringCloudConfigServerClientConfigSourceProvider.getConfigSources(SpringCloudConfigServerClientConfigSourceProvider.java:37)
	at io.quarkus.runtime.configuration.ConfigUtils.addSourceProvider(ConfigUtils.java:106)
	at io.quarkus.runtime.configuration.ConfigUtils.addSourceProviders(ConfigUtils.java:120)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:15971)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:56)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:106)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.Application.run(Application.java:228)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting a colon to separate field name and value
 at [Source: (String)"{
  "name": "a-bootiful-client",
  "profiles": [
    "prod"
  ],
  "label": "master",
  "version": "bb51f4173258ae3481c61b95b503c13862ccfba7",
  "state": null,
  "propertySources": [
    {
      "name": "https://github.com/spring-cloud-samples/config-repo/testapp-prod.yml",
      "source": {
        "bar" "spam",
        "foo": "from foo development",
        "greeting.message": "hello from spring cloud config server"
      }
    },
    {
      "name": "https://github.com/spring-cloud-samples/co"[truncated 124 chars]; line: 13, column: 16]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipColon2(ReaderBasedJsonParser.java:2221)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipColon(ReaderBasedJsonParser.java:2200)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:936)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:500)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	... 26 more

2020-05-20 15:35:13,185 INFO  [io.quarkus] (main) a-bootiful-client 1.3.2.Final (powered by Quarkus 1.3.2.Final) started in 0.241s. Listening on: http://0.0.0.0:8081
2020-05-20 15:35:13,185 INFO  [io.quarkus] (main) Profile prod activated.
2020-05-20 15:35:13,185 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, spring-cloud-config-client]
```

**Comment by geoand** [comment]
Can you try setting `quarkus.spring-cloud-config.fail-fast=true`? It should prevent the application from starting and suppress the output entirely in `1.3.2`

**Comment by rsvoboda** [comment]
That gives:
```
[INFO] Running io.quarkus.spring.cloud.config.client.runtime.GreetingResourceIT
Executing [/Users/rsvoboda/git/quarkus/integration-tests/spring-cloud-config-client/target/quarkus-integration-test-spring-cloud-config-client-1.3.2.Final-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
[INFO] RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:264)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.Application.run(Application.java:228)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: java.lang.RuntimeException: Unable to obtain configuration from Spring Cloud Config Server at http://localhost:8089
	at io.quarkus.spring.cloud.config.client.runtime.SpringCloudConfigServerClientConfigSourceProvider.getConfigSources(SpringCloudConfigServerClientConfigSourceProvider.java:52)
	at io.quarkus.runtime.configuration.ConfigUtils.addSourceProvider(ConfigUtils.java:106)
	at io.quarkus.runtime.configuration.ConfigUtils.addSourceProviders(ConfigUtils.java:120)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:15971)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:56)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:106)
	... 3 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('"' (code 34)): was expecting a colon to separate field name and value
 at [Source: (String)"{
  "name": "a-bootiful-client",
  "profiles": [
    "prod"
  ],
  "label": "master",
  "version": "bb51f4173258ae3481c61b95b503c13862ccfba7",
  "state": null,
  "propertySources": [
    {
      "name": "https://github.com/spring-cloud-samples/config-repo/testapp-prod.yml",
      "source": {
        "bar" "spam",
        "foo": "from foo development",
        "greeting.message": "hello from spring cloud config server"
      }
    },
    {
      "name": "https://github.com/spring-cloud-samples/co"[truncated 124 chars]; line: 13, column: 9] (through reference chain: io.quarkus.spring.cloud.config.client.runtime.Response["propertySources"]->java.util.ArrayList[0]->io.quarkus.spring.cloud.config.client.runtime.Response$PropertySource["source"])
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at io.quarkus.spring.cloud.config.client.runtime.DefaultSpringCloudConfigClientGateway.exchange(DefaultSpringCloudConfigClientGateway.java:74)
	at io.quarkus.spring.cloud.config.client.runtime.SpringCloudConfigServerClientConfigSourceProvider.getConfigSources(SpringCloudConfigServerClientConfigSourceProvider.java:37)
	... 8 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting a colon to separate field name and value
 at [Source: (String)"{
  "name": "a-bootiful-client",
  "profiles": [
    "prod"
  ],
  "label": "master",
  "version": "bb51f4173258ae3481c61b95b503c13862ccfba7",
  "state": null,
  "propertySources": [
    {
      "name": "https://github.com/spring-cloud-samples/config-repo/testapp-prod.yml",
      "source": {
        "bar" "spam",
        "foo": "from foo development",
        "greeting.message": "hello from spring cloud config server"
      }
    },
    {
      "name": "https://github.com/spring-cloud-samples/co"[truncated 124 chars]; line: 13, column: 16]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipColon2(ReaderBasedJsonParser.java:2221)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipColon(ReaderBasedJsonParser.java:2200)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:936)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:500)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	... 26 more
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.943 s <<< FAILURE! - in io.quarkus.spring.cloud.config.client.runtime.GreetingResourceIT
```
Quarkus doesn't start, but I still see the reason why

**Comment by geoand** [comment]
Damn it... 
How about if you don't start wiremock at all for failsafe?

**Comment by rsvoboda** [comment]
```
Executing [/Users/rsvoboda/git/quarkus/integration-tests/spring-cloud-config-client/target/quarkus-integration-test-spring-cloud-config-client-1.3.2.Final-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:264)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.Application.run(Application.java:228)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: java.lang.RuntimeException: Unable to obtain configuration from Spring Cloud Config Server at http://localhost:8089
	at io.quarkus.spring.cloud.config.client.runtime.SpringCloudConfigServerClientConfigSourceProvider.getConfigSources(SpringCloudConfigServerClientConfigSourceProvider.java:52)
	at io.quarkus.runtime.configuration.ConfigUtils.addSourceProvider(ConfigUtils.java:106)
	at io.quarkus.runtime.configuration.ConfigUtils.addSourceProviders(ConfigUtils.java:120)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:15971)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:56)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:106)
	... 3 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8089 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
```

**Comment by geoand** [comment]
Then I honestly don't know what to tell you because when I fixed the issue it was on the at the time current `master` (which was already way ahead of `1.3.x`).

**Comment by rsvoboda** [comment]
Yeah, it's a bit frustrating not to be able to reproduce it :) Thanks for your ideas.

**Comment by geoand** [comment]
Sorry I couldn't help more :(

**Comment by rsvoboda** [comment]
Looking at generated ApplicationImpl

1.3.2 based has this decompiled code inside protected final void doStart(String[] var1) { method:
```java
        } catch (Throwable var5) {
            LOG.error("Failed to start application", var5);
            var2.close();
            throw (Throwable)(new RuntimeException("Failed to start quarkus", var5));
        }
```
Quarkus master has:
```java
        } catch (Throwable var8) {
            LOG.error("Failed to start application", var8);
            DelayedHandler var7 = InitialConfigurator.DELAYED_HANDLER;
            if (!var7.isActivated()) {
                Handler[] var5 = new Handler[1];
                ConsoleHandler var6 = new ConsoleHandler();
                var5[0] = (Handler)var6;
                var7.setHandlers(var5);
            }

            var2.close();
            throw (Throwable)(new RuntimeException("Failed to start quarkus", var8));
        }
```

So the code is ensuring DELAYED_HANDLER is activated and if not console handler is set.
 - Shouldn't it be before `LOG.error` call?
 - any idea on different scenario which would end up with exception during the boot + not available log?

**Comment by geoand** [comment]
The code is correct, because when `setHandlers` is called, all logging up to that point is flushed to the handler (the console handler in this case).

The trick is to throw an exception before logging has been setup properly... I can't think of anything other than the bootstrap configuration that definitively comes before logging.
