### ISSUE TITLE
Kotlin live reload dev mode not working when Tika extension is present

### ISSUE THREAD

**Issue by timounet** [quarkusio/quarkus#8708]
**Description**
Live reload raises a RuntimeException: Unable to invoke Kotlin compiler after a code change in dev mode. `mvnw quarkus:dev`
````
java.lang.RuntimeException: Unable to invoke Kotlin compiler
	at io.quarkus.kotlin.deployment.KotlinCompilationProvider.compile(KotlinCompilationProvider.java:78)
	at io.quarkus.dev.ClassLoaderCompiler.compile(ClassLoaderCompiler.java:174)
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:194)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:125)
	at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:50)
	at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:42)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
````

**To Reproduce**
1. create a new Quarkus project with Quarkus Maven plugin
````
mvn io.quarkus:quarkus-maven-plugin:1.3.2.Final:create /
    -DprojectGroupId=com.acme /
    -DprojectArtifactId=rest-test /
    -DclassName="com.acme.test.MyResource" /
    -Dpath="api/test" /
    -Dextensions="tika,kotlin,resteasy-jsonb,openapi,health,metrics,container-image-jib"
````
2. run `mvnw quarkus:dev` open [http://localhost:8080/api/test](http://localhost:8080/api/test) > hello is correctly displayed
3. Change in code main/kotlin/com/acme/test/MyResource "hello" message by "hello world" and go back to [http://localhost:8080/api/test](http://localhost:8080/api/test). RunTimeExceptions occurs in the browser

**Environment:**
 - Output of `java -version`: openjdk version "11.0.6" 2020-01-14 OpenJDK Runtime Environment GraalVM CE 20.0.0
 - GraalVM version (if different from Java): 
 - Quarkus version: 1.3.2 final

**Comment by gsmet** [comment]
@geoand should we display the errors here: https://github.com/quarkusio/quarkus/blob/master/extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinCompilationProvider.java#L78 ?

**Comment by geoand** [comment]
Yeah, I was about to say that.

I'll fix it later unless someone beats me to it

**Comment by geoand** [comment]
I can reproduce the reported problem.

**Comment by geoand** [comment]
The problem seems to in the Kotlin version, if you update to `1.3.71` or `1.3.72` the problem goes away.

**Comment by timounet** [comment]
1. I have updated kotlin version `<kotlin.version>1.3.72</kotlin.version>` in pom project>properties.
2. run `mvnw quarkus:dev` open http://localhost:8080/api/test > "hello world" is correctly displayed
3. Change back in code main/kotlin/com/acme/test/MyResource "hello world" message by "hello" and go back to http://localhost:8080/api/test. RunTimeExceptions still occurs in the browser. Same message.

Have I missed something? - Thank you

**Comment by geoand** [comment]
Actually there seems to be some incompatibility between the Kotlin compiler and Tika. If you removed the tika extension things should work.

**Comment by timounet** [comment]
correct
