### ISSUE TITLE
Vault ITs unstable

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#8836]
**Describe the bug**
Vault IT test is highly unstable and I have seen it failing for some PR one of them being https://github.com/quarkusio/quarkus/pull/8833 

**Expected behavior**

The test to pass.

**Actual behavior**
```
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:317)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 43 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"driver failed programming external connectivity on endpoint focused_mayer (1936f0278456d8fcc931b7b9e48e9d902a8e84fb5b5a0aad4440e0cc70e0b4e3): Bind for 0.0.0.0:6543 failed: port is already allocated"}

```

**Comment by machi1990** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/8880 we can safely close this one for now.
