### ISSUE TITLE
SmallRyeConfig picks up application.properties from src/main/resources during testing instead of src/test/resources

### ISSUE THREAD

**Issue by marc-christian-schulze** [quarkusio/quarkus#8845]
**Describe the bug**
Quarkus is picking up the `application.properties` file from `src/main/resources` during testing instead of `src/test/resources`.

**Expected behavior**
`./gradlew build --info` passes

**Actual behavior**
`./gradlew build --info` fails with:
```
...
java.util.NoSuchElementException: Property MY_PROD_ENV_VAR not found
  at io.smallrye.config.SmallRyeConfig.propertyNotFound(SmallRyeConfig.java:209)
  at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:96)
  at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:80)
  at io.quarkus.runtime.configuration.ConfigExpander.accept(ConfigExpander.java:55)
  at io.quarkus.runtime.configuration.ConfigExpander.accept(ConfigExpander.java:15)
  at org.wildfly.common.expression.ExpressionNode.emit(ExpressionNode.java:42)
  at org.wildfly.common.expression.Expression.evaluateException(Expression.java:75)
  ...
```

**To Reproduce**
`./gradlew build --info`

[Reproducer available here.](https://github.com/marc-christian-schulze/quarkus-reproducer-8845)

**Additional context**
This is a regression introduced with Quarkus 1.4.0.Final. Testing the very same example with Quarkus 1.4.0.CR1 works.

**Comment by wllianwd** [comment]
Is this broken again?
