### ISSUE TITLE
Improve error reporting of missing default config values

### ISSUE THREAD

**Issue by starksm64** [quarkusio/quarkus#891]
I'm working on the test extension and trying to flesh out all supported types, and during initial testing of a config group like the following:

```java
@ConfigGroup()
public class AllValuesConfig {
    /** a long primitive */
    @ConfigItem
    long longPrimitive;
    /** a long value */
    @ConfigItem
    Long longValue;
    /** an optional long value */
    @ConfigItem
    OptionalLong optLongValue;
}
```
I'm seeing the following exception even before the configuration is loaded:
```
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:601)
	at java.lang.Long.valueOf(Long.java:803)
	at io.smallrye.config.Converters.lambda$static$c244dc85$1(Converters.java:61)
	at io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:133)
	at org.jboss.shamrock.deployment.configuration.ObjectConfigType.getDefaultValueIntoEnclosingGroup(ObjectConfigType.java:30)
	at org.jboss.shamrock.deployment.configuration.GroupConfigType.create(GroupConfigType.java:126)
	at org.jboss.shamrock.deployment.configuration.GroupConfigType.getDefaultValueIntoEnclosingGroup(GroupConfigType.java:231)
	at org.jboss.shamrock.deployment.configuration.GroupConfigType.create(GroupConfigType.java:126)
	at org.jboss.shamrock.deployment.configuration.GroupConfigType.getOrCreate(GroupConfigType.java:180)
	at org.jboss.shamrock.deployment.configuration.ConfigDefinition.initialize(ConfigDefinition.java:127)
	at org.jboss.shamrock.deployment.configuration.ConfigDefinition.loadConfiguration(ConfigDefinition.java:283)
	at org.jboss.shamrock.deployment.steps.ConfigurationSetup.initializeConfiguration(ConfigurationSetup.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.shamrock.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:383)
	at org.jboss.builder.BuildContext.run(BuildContext.java:402)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1416)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

This is happening on the longValue field. I would not think that a Long type would require a default, but if it does we should be reporting what field is the problem.

**Comment by gsmet** [comment]
We need to check first if it's still an issue and see if we still have to improve the error message to include the field name.

**Comment by gsmet** [comment]
@dmlloyd I don't know if it's still a problem. I will refrain from launching a new contributor on it as you probably have a ton of changes in your config patch.

**Comment by dmlloyd** [comment]
This is fixed for run time configuration in the upcoming patch.  It is not fixed for build time configuration which will still just produce an exception for the first problem found, but it may be fixable by a new contributor with some small amount of guidance once that patch is in.
