### ISSUE TITLE
Vert.x MessageCodec not being called when it is used to switch data types

### ISSUE THREAD

**Issue by aaron-rogers82** [quarkusio/quarkus#8916]
**Describe the bug**
When trying to use a MessageCodec to convert from two different types, the message codec does not appear to be called.
I created a repo that will reproduce this issue: https://github.com/aaron-rogers82/QuarkusTest
In there I am trying to convert from a String to a Custom POJO inside of the Codec. When Quarkus starts up, it registers the Codec, but then I get the following exception before the @ConsumeEvent method is even called.

> (RECIPIENT_FAILURE,8185) java.lang.ClassCastException: class java.lang.String cannot be cast to class org.acme.RestEndpoints$MyName (java.lang.String is in module java.base of loader 'bootstrap'; org.acme.RestEndpoints$MyName is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6f27a732)
	at io.vertx.core.eventbus.impl.MessageImpl.fail(MessageImpl.java:113)
	at io.quarkus.vertx.runtime.VertxRecorder$3.handle(VertxRecorder.java:86)
	at io.quarkus.vertx.runtime.VertxRecorder$3.handle(VertxRecorder.java:80)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:271)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:249)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:573)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:532)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Expected behavior**
The transform method on the Custom MessageCodec would be called and the @ConsumeEvent method would have the custom POJO object passed to it.

**Actual behavior**
No methods on the Custom MessageCodec are called and the above exception is thrown.

**To Reproduce**
1. Clone project at https://github.com/aaron-rogers82/QuarkusTest
2. mvn clean test
3. See exception message in console

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  
19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"

**Additional context**
I see the same behavior when converting between any two types. It works fine if you the same type on both end of the MessageCodec (MessageCodec<Class1, Class1>).

**Comment by cescoffier** [comment]
When using a codec explicitly, it must be set on both side:

```
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("{name}")
    public Uni<String> greeting(@PathParam String name) {
        return bus.<String>request("greeting", name, 
            new DeliveryOptions().setCodecName(MyNameCodec.class.getName()))
            .onItem().apply(Message::body);
    }

    @ConsumeEvent(value = "greeting", codec = MyNameCodec.class)
    Uni<String> greeting(MyName name) {
        return Uni.createFrom().item(() -> "Hello "+name.getName());
    }
```

Another solution would be to use the default codec provided by Quarkus:

```
   @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("{name}")
    public Uni<String> greeting(@PathParam String name) {    
        return bus.<String>request("greeting", new MyName(name))
            .onItem().apply(Message::body);
    }

    @ConsumeEvent(value = "greeting")
    Uni<String> greeting(MyName name) {
        return Uni.createFrom().item(() -> "Hello "+name.getName());
    }
```

**Comment by cescoffier** [comment]
Not a bug - it's how the Vert.x event bus works.
