### ISSUE TITLE
SSLProtocolException in RestClient invocation when migrating from version 1.2.1.Final to 1.3.0.Final using Proxy

### ISSUE THREAD

**Issue by bbcjunior** [quarkusio/quarkus#8969]
I have a simple RestClient interface (CDI) called from my resource class that connects to an HTTPS endpoint and it was working fine using proxy connection on quarkus version 1.2.1.Final.

Migrating my app from 1.2.1.Final to 1.3.0.Final (or 1.3.1, 1.3.2 and 1.4), running in Dev mode behind a proxy (working office), starting quarkus locally using:

 -> mvn compile quarkus:dev -Dhttps.proxyHost=myproxy -Dhttps.proxyPort=80

 I got the following exception when I called the RestClient service:

```java
java.lang.RuntimeException: javax.net.ssl.SSLProtocolException: Connection reset
        at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.executeRequest(URLConnectionEngine.java:220)
        at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.invoke(URLConnectionEngine.java:58)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:488)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy87.brasilsegEnviarImagem(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.microprofile.client.InvocationContextImpl.interceptorChainCompleted(InvocationContextImpl.java:62)
        at org.jboss.resteasy.microprofile.client.InvocationContextImpl.proceed(InvocationContextImpl.java:91)
        at io.opentracing.contrib.interceptors.OpenTracingInterceptor.wrap(OpenTracingInterceptor.java:36)
        at io.opentracing.contrib.interceptors.OpenTracingInterceptor_Bean.intercept(OpenTracingInterceptor_Bean.zig:393)
        at org.jboss.resteasy.microprofile.client.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:154)
        at org.jboss.resteasy.microprofile.client.InvocationContextImpl.invokeNext(InvocationContextImpl.java:53)
        at org.jboss.resteasy.microprofile.client.InvocationContextImpl.proceed(InvocationContextImpl.java:89)
        at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
        at com.sun.proxy.$Proxy91.brasilsegEnviarImagem(Unknown Source)
        at br.com.bb.als.resource.Op4681599v1EnviarImagemSinistroResource.executar(Op4681599v1EnviarImagemSinistroResource.java:89)
        at br.com.bb.als.resource.Op4681599v1EnviarImagemSinistroResource_Subclass.executar$$superaccessor11(Op4681599v1EnviarImagemSinistroResource_Subclass.zig:1293)
        at br.com.bb.als.resource.Op4681599v1EnviarImagemSinistroResource_Subclass$$function$$11.apply(Op4681599v1EnviarImagemSinistroResource_Subclass$$function$$11.zig:51)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
...

Caused by: javax.net.ssl.SSLProtocolException: Connection reset
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:137)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1356)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1331)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:241)
        at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.executeRequest(URLConnectionEngine.java:213)
        ... 69 more
Caused by: java.net.SocketException: Connection reset
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        ... 78 more`

```
Runnig the same app at home, with no Proxy, just using 'mvn compile quarkus:dev' for all versions of quarkus (1.2.1 to 1.4) the connection works fine. 
Using version 1.2.1 in the office, with proxy, it works fine too.
Any idea or suggestions or configuration I have to do to migrate version using proxy connection?
I did not see any relevant instruction related to proxy configuration on the migration guides..
ps.: I updated the maven to the newest version, Maven 3.6.3.
ps2.: Until now, I didn't need to put any server certificate on java trusted certification storage.

**Comment by jaikiran** [comment]
Hello @bbcjunior, can you pass along the JVM system property `javax.net.debug` and set it to `all`[1] and get the generated verbose logs? That might help us understand what's going on.
[1] https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/ReadDebug.html

**Comment by bbcjunior** [comment]
Hello @jaikiran , nice to meet you! My first time contributing here and using Quarkus a lot at the company I work.
Well, I think starting the java net tracing won´t help in this case because actually the proxy settings are being ignored by these quarkus versions (1.3.1 to 1.4.1).
Let me describe better, giving you 2 Scenarios:

**To Reproduce Scenario 1: Using quarkus 1.2.0.Final**
1. Clone the project quarkus-quickstarts;
2. Go to project folder rest-client-quickstart;
3. Change the pom.xml to quarkus version 1.2.0.Final;
4. Comment everything related to the quarkus-resteasy-mutiny dependency (mutiny feature belongs to versions above 1.2.0.Final)
5. Start Quarkus (with proxy) using the command:
   mvnw compile quarkus:dev -Dhttps.proxyHost=mycompanyproxy.com -Dhttps.proxyPort=80 (You can put any proxy host here)
6. In your browser, call the endpoint http://localhost:8080/country/name/brazil

**Scenario 1: EXPECTED and ACTUAL behavior**
Considering that my computer does not use proxy to go to internet, I got the expected Exception:
```java
 org.jboss.resteasy.spi.UnhandledException: javax.ws.rs.ProcessingExcep
tion: RESTEASY004655: Unable to invoke request: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 400
 Bad Request"
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
...
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: java.io.IOException: Unable to tunnel thro
ugh proxy. Proxy returns "HTTP/1.1 400 Bad Request"
        at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.invoke(URLConnectionEngine.java:58)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:488)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149)
...
```

**To Reproduce Scenario 2: Using quarkus last version 1.4.1.Final**
1. Clone the project quarkus-quickstarts;
2. Go to project folder rest-client-quickstart;
3. Start quarkus (with proxy) using the command:
   mvnw compile quarkus:dev -Dhttps.proxyHost=mycompanyproxy.com -Dhttps.proxyPort=80 (You can put any proxy host here)
4. In your browser, call the endpoint http://localhost:8080/country/name/brazil

**Scenario 2: EXPECTED behavior**
Some exception complaining about the unknown proxy, like Scenario 1.

**Scenario 2: ACTUAL behavior**
It connects to the external endpoint, like there wasn´t any proxy settings to check first. The proxy was ignored.

Can you help me with that please? Tks!

**Comment by jaikiran** [comment]
Seeing that you are using an http endpoint (http://localhost:8080/country/name/brazil) your proxy settings should set the `http` equivalent system properties (in your example you are setting the `https` system properties) as follows:
```
-Dhttp.proxyHost=mycompanyproxy.com -Dhttp.proxyPort=80
```
Can you give this a try? As to why it was "working" in previous 1.2.x version, maybe there was a bug which got fixed to use the right system properties for the proxies.

**Comment by jaikiran** [comment]
I gave this a quick try by setting the `http` system properties with 1.4.1.Final of Quarkus and got the expected exception:

```
mvn -o quarkus:dev -Dhttp.proxyHost=mycompanyproxy.com -Dhttp.proxyPort=80
```
then
```
curl localhost:8080/country/name/brazil
```
got:
```
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: java.net.UnknownHostException: mycompanyproxy.com
	at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.invoke(URLConnectionEngine.java:63)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:488)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy45.getByName(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:149)
	at com.sun.proxy.$Proxy48.getByName(Unknown Source)
	at org.acme.restclient.CountriesResource.name(CountriesResource.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	... 20 more
Caused by: java.net.UnknownHostException: mycompanyproxy.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:515)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:513)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:512)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:553)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.invoke(URLConnectionEngine.java:60)
	... 47 more
```

**Comment by bbcjunior** [comment]
Hello @jaikiran!! The rest client endpoint that the quickstart example connects is https://restcountries.eu/rest/name/{name} 
It is on connecting to the endpoint above that the proxy was supposed to be used, does it make sense? I didn´t even try using -Dhttp.proxyHost because my application and the quickstart's endpoint are ```https```.
The other endpoint you mentioned (http://localhost:8080/country/name/brazil) is the resource endpoint, used only as a way of testing the rest client.

Buuuut, using the parameter -Dhttp.proxyhost to connects to both kind of rest client endpoints (http and https), using version 1.4.1.Final, that works fine!! Although I think it was not a good decision generalizing both http and https all into one parameter proxy, it is ok!! I imagine that could be Resteasy's project decision..
I suggest put that change on the documentation of quarkus so that others don´t have the same difficulty. Some big companies use proxies so that would be a good help.

Thank you very much for the attention and support. Now I can upgrade it. Can I close the issue?



I haven't tried using -Dhttp.prozuhost
