### ISSUE TITLE
Resteasy and Kotlinx Serialization

### ISSUE THREAD

**Issue by akoufa** [quarkusio/quarkus#9003]
**Description**

Hello to all. If I am not mistaken, currently the only way to automatically serialise and deserialise objects that we receive/send in the Resteasy HTTP endpoints is using either JsonB or Jackson. I would therefore kindly ask if the default Kotlin serialisation way of using [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) is planned to be supported by Quarkus as a RestEasy extension. As me and I think lot of the current and future Quarkus users, like being able to use Kotlin in Quarkus projects, we would be grateful if kotlinx.serialization and coroutines will be considered as important targets for Quarkus near term future as they are the finishing touches on the decent support of Kotlin in Quarkus.

Thank you so much for your effort.

**Comment by geoand** [comment]
cc @evanchooly

**Comment by n1hility** [comment]
@evanchooly Any updates here, or should this be moved to 1.9?

**Comment by evanchooly** [comment]
Definitely move it

**Comment by xiaoyunwu** [comment]
And update on this? I am getting the following "Class initialization of kotlinx.serialization.internal.IntSerializer failed." error when try to build native image.

**Comment by xiaoyunwu** [comment]
@n1hility is there anything pointer on how this should be done? So that others can take a crack at it?

**Comment by geoand** [comment]
@evanchooly is looking into this (and I'll be helping if necessary).
The plan is to introduce support into RESTEasy Reactive

**Comment by vladimirfx** [comment]
Let me describe the use case:
Our team develops many microservices and integrations mainly on Kotlin. About 50% of it is Quarkus based. Almost all need some kind of serialization and the default (most used) option is Jackson. With Jackson, we constantly fight with issues related to Kotlin-Jackson-Native Image compatibility. 
Simplest example:
```kotlin
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy::class)
data class ServerRequest(
    val lastName: String,
    val firstName: String,
    val documentNumber: String,
    val typeOfDocument: String,
    val mobilePhone: String?,
    val dateOfBirth: String?,
)
```

Do not work even on JVM because Jackson does not use the constructor (why???). Ok, fix this by adding to build:

```kotlin
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
```

Quarkus do a good job and do register needed Jackson module. Works fine on JVM! 
This module is nanoservice (c) and 'pay' 200Mb+ RAM for running it is crazy. Let's build Native Image!

Not so fast - https://github.com/quarkusio/quarkus/issues/8479 

So, the fight is proceed. Hours of debugging and we _remove_ `jackson-module-kotlin` module and build workaround:

```kotlin
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy::class)
data class ServerRequest @JsonCreator constructor(
    val lastName: String,
    val firstName: String,
    val documentNumber: String,
    val typeOfDocument: String,
    val mobilePhone: String?,
    val dateOfBirth: String?,
)
```
It is just one example of an annoying experience this came from Jackson for Kotlin developer. For simple cases, we migrated to JSON-B.

How to fix it? Kotlinx Serialization - it just works in our experience - Ktor (handmade native build), Spring Native. It builds serializers at compile time and this is a gamechanger in the native world. As a bonus, you actually **know** what you get serialized instead of **hoping** (and praying) for a good result.

Please support us - your Kotlin fans...

**Comment by geoand** [comment]
The is work in progress on this. You can track it [here](https://github.com/quarkusio/quarkus/pull/21318)

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/21318 has been merged (and some subsequent fixed been applied), so we can close this.

The first release that will contain this support is `2.7`.
Note that Kotlin Serialization support is only provided for RESTEasy Reactive

**Comment by vladimirfx** [comment]
Tryed 2.7.0.CR1 on one-method microservice:

```kotlin
@ApplicationScoped
@Path("horoscope")
class Horoscopes{
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("daily")
    suspend fun daily(): List<Horoscope> {
       // impl here
    }
}

@Serializable
data class Horoscope(val id: Long, val text: String)

```

Error on JVM and Native:

```log

2022-01-20 12:53:28,534 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /horoscope/daily failed, error id: 3b5d1d0c-c940-4b56-b087-bcf0a189e13c-1: kotlinx.serialization.SerializationException: Serializer for class 'Any' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
	at kotlinx.serialization.SerializersKt__SerializersJvmKt.serializer(SerializersJvm.kt:59)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
	at kotlinx.serialization.SerializersKt__SerializersJvmKt.serializer(SerializersJvm.kt:30)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
	at io.quarkus.kotlin.serialization.KotlinSerializationMessageBodyWriter.writeResponse(KotlinSerializationMessageBodyWriter.kt:42)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:207)
	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:178)
	at org.jboss.resteasy.reactive.server.core.serialization.DynamicEntityWriter.write(DynamicEntityWriter.java:90)
	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:32)
	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:15)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:85)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext$1$1.handle(VertxResteasyReactiveRequestContext.java:82)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

That is because `ServerResourceMethod.returnType` of hander method is detected as `java.lang.Object`. Should I file a separate bug or it is normal for `suspend` method?

**Comment by geoand** [comment]
It's definitely a bug. I'll take care of it
