### ISSUE TITLE
@Produces fails for classes without default constructor

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#9050]
**Describe the bug**
I want to create a bean of a class that has no default constructor and requires some properties to be injected into it. However, since it isn't prepared for CDI, I create a producer class and method to create it with the appropriate values for the properties.

With Quarkus dev, this works just fine. However, when I build the code with `gradlew build` and let it run in a docker container for testing, it fails with `java.lang.NoSuchMethodError: ... method 'void <init>()' not found`. It seems the producer class/method is ignored and ARC tries to instantiate the object itself.

I suspect that this also happens with beans having a default constructor. But then it might not be easy to detect that your producer was ignored. However, I haven't tested that.

This happens with Quarkus 1.4.1.Final and the current master. With Quarkus 1.3.2.Final I get the following error when running quarkus dev or compiling the project: 

```
Caused by: javax.enterprise.inject.spi.DefinitionException: Return type of a producer method for normal scoped beans must declare a non-private constructor with no parameters: PRODUCER METHOD bean [types=[java.lang.Object, com.akamai.netstorage.NetStorage], qualifiers=[@Default, @Any], target=com.akamai.netstorage.NetStorage produceNetStorage(), declaringBean=org.acme.MyProducer]
``` 

Which makes no sense to me. Why would the result of a producer method need to have a default constructor? I'm constructing it for Quarkus, it should not call the default constructor itself.

**Expected behavior**
The producer is used.

**Actual behavior**
The producer is ignored.

**To Reproduce**
1. Download reproducer project and unzip it.
[produces-for-non-default-constructor.zip](https://github.com/quarkusio/quarkus/files/4575185/produces-for-non-default-constructor.zip)
2. In the directory run `./gradlew clean quarkusDev` and open localhost:8080/hello in your browser. You should see something like `hello com.akamai.netstorage.NetStorage@26819cc`
3. Compile the project with `./gradlew build` and run the resulting jar. Open the url localhost:8080/hello again. Now you see the following error in the log
```
2020-05-04 14:21:18,306 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: 7ed965f0-4c84-4be5-9e87-818f67f360c8-1: java.lang.NoSuchMethodError: com.akamai.netstorage.NetStorage: method 'void <init>()' not found
        at org.acme.MyProducer_ProducerMethod_produceNetStorage_fa2b9b6d18193aaccf98f59e0885e6a21da609e4_ClientProxy.<init>(MyProducer_ProducerMethod_produceNetStorage_fa2b9b6d18193aaccf98f59e0885e6a21da609e4_ClientProxy.zig:414)
        at org.acme.MyProducer_ProducerMethod_produceNetStorage_fa2b9b6d18193aaccf98f59e0885e6a21da609e4_Bean.proxy(MyProducer_ProducerMethod_produceNetStorage_fa2b9b6d18193aaccf98f59e0885e6a21da609e4_Bean.zig:94)
        at org.acme.MyProducer_ProducerMethod_produceNetStorage_fa2b9b6d18193aaccf98f59e0885e6a21da609e4_Bean.get(MyProducer_ProducerMethod_produceNetStorage_fa2b9b6d18193aaccf98f59e0885e6a21da609e4_Bean.zig:115)
        at org.acme.MyProducer_ProducerMethod_produceNetStorage_fa2b9b6d18193aaccf98f59e0885e6a21da609e4_Bean.get(MyProducer_ProducerMethod_produceNetStorage_fa2b9b6d18193aaccf98f59e0885e6a21da609e4_Bean.zig:41)
        at org.acme.Example2Resource_Bean.create(Example2Resource_Bean.zig:109)
        at org.acme.Example2Resource_Bean.create(Example2Resource_Bean.zig:312)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:79)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at org.acme.Example2Resource_ClientProxy.arc$delegate(Example2Resource_ClientProxy.zig:181)
        at org.acme.Example2Resource_ClientProxy.arc_contextualInstance(Example2Resource_ClientProxy.zig:228)
        at io.quarkus.arc.runtime.ClientProxyUnwrapper.apply(ClientProxyUnwrapper.java:11)
        at io.quarkus.resteasy.common.runtime.ResteasyInjectorFactoryRecorder$1.apply(ResteasyInjectorFactoryRecorder.java:22)
        at io.quarkus.resteasy.common.runtime.QuarkusInjectorFactory$UnwrappingPropertyInjector.inject(QuarkusInjectorFactory.java:71)
        at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:79)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:368)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:123)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:87)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Configuration**
See reproducer. 

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Windows 10
- Java 11
- Quarkus 
  - 1.3.2.Final (throws error on build) 
  - 1.4.1.Final and master (fail during runtime after build but work in quarkusDev)

**Comment by andreas-eberle** [comment]
@gsmet: Maybe you know who is the right one for this.

**Comment by gsmet** [comment]
@mkouba could you have a first look at that one and see if it's an issue in Quarkus or something we don't support? Thanks!

**Comment by andreas-eberle** [comment]
Thanks!

**Comment by mkouba** [comment]
So after some investigation and discussion with @stuartwdouglas the problem is identified - transformations are only supported in application archives, i.e. indexed artifacts.

You could see the following message when running the build with quarkus master:

> Cannot transform com.akamai.netstorage.NetStorage as it's containing application archive could not be found.

### Workaround - index third-party dependency

Just add the following two lines to the `application.properties` file:
```
quarkus.index-dependency.akamai.group-id=com.akamai
quarkus.index-dependency.akamai.artifact-id=NetStorageKit
```
As described here: https://stackoverflow.com/a/55513723/2654154

**Comment by andreas-eberle** [comment]
So first of all, thanks for your answer and the workaround! I still have some question, maybe you can shed some light on them.

Why is the indexing required for a bean which I produce in my artefact with a producer method? Quarkus should never ever need to call the init method in this case. I create the bean with another constructor. I'm now actually worried that Quarkus is creating the bean with the default constructor, which will definetively cause trouble. Shouldn't it be sufficient for Quarkus that the producer method is in my application?

**Comment by mkouba** [comment]
> Why is the indexing required for a bean which I produce in my artefact with a producer method? 

So your producer is `@ApplicationScoped` which means that quarkus needs to create a _client proxy_ for the returned type (as defined by the CDI spec). Normally, a CDI container would fail with an error - because of the absence of a no-args constructor (which is a requirement for any normal scoped bean). In Quarkus, we do try to add a "synthetic" no-args constructor instead.

You could also annotate your producer with `@Singleton`. In this case, a client proxy is not required. But there are some drawbacks. For example you wouldn't be able to use the [new mocking functionality](https://quarkus.io/blog/mocking/).

**Comment by andreas-eberle** [comment]
OK, I see. Would it make sense/be possible for Quarkus to "auto-detect" the artefacts it needs to index in such a case? I mean during build time it should be possible to determine that this class is required for indexing and therefore this artifact needs to be indexed?

**Comment by mkouba** [comment]
Stuart is already working on a fix - https://github.com/quarkusio/quarkus/pull/9105.

**Comment by andreas-eberle** [comment]
Ah, thanks a lot!
