### ISSUE TITLE
access etcd with grpc client and quarkus 1.4.1

### ISSUE THREAD

**Issue by smatijasevic** [quarkusio/quarkus#9053]
**Describe the bug**
I am trying to build etcd client with Quarkus 1,4,1. Currently, the client can read KeyValue items from etcd via grpc but only in JVM mode. When I try to build in the native app (using GraalVM graalvm-ce-java-11-20.0.0) I get some exceptions.
Do you have some advice about how to compile it to native?

Part of the stack trace:
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.netty.internal.tcnative.SSL. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing io.netty.handler.ssl.OpenSsl.version(OpenSsl.java:455)
Call path from entry point to io.netty.handler.ssl.OpenSsl.version(): 
        at io.netty.handler.ssl.OpenSsl.version(OpenSsl.java:455)
        at io.netty.handler.ssl.OpenSsl.isAlpnSupported(OpenSsl.java:440)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:194)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:406)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:507)
        at io.quarkus.grpc.client.runtime.AbstractChannelProducer.createChannel(AbstractChannelProducer.java:27)
        at io.quarkus.grpc.client.runtime.ChannelProducer.createNamedChannel_fc166eb81361ff31179cd3c83da3bfe088b851d3(ChannelProducer.zig:31)
        at io.quarkus.grpc.client.runtime.ChannelProducer_ProducerMethod_createNamedChannel_fc166eb81361ff31179cd3c83da3bfe088b851d3_b8ac3e4011c2697cecfe38ed596e2a75edd19489_Bean.create(ChannelProducer_ProducerMethod_createNamedChannel_fc166eb81361ff31179cd3c83da3bfe088b851d3_b8ac3e4011c2697cecfe38ed596e2a75edd19489_Bean.zig:51)
        at io.quarkus.grpc.client.runtime.ChannelProducer_ProducerMethod_createNamedChannel_fc166eb81361ff31179cd3c83da3bfe088b851d3_b8ac3e4011c2697cecfe38ed596e2a75edd19489_Bean.create(ChannelProducer_ProducerMethod_createNamedChannel_fc166eb81361ff31179cd3c83da3bfe088b851d3_b8ac3e4011c2697cecfe38ed596e2a75edd19489_Bean.zig:188)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:79)
        at io.quarkus.arc.impl.AbstractSharedContext$$Lambda$575/0x00000007c14cd040.apply(Unknown Source)
        at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:340)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:738)
        ... 8 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.netty.internal.tcnative.SSL. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:249)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedType(SharedGraphBuilderPhase.java:204)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:230)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:193)

**Expected behavior**
(Describe the expected behavior clearly and concisely.)

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  ubuntu 18.04
 - Output of `java -version`: openjdk 11.0.7 2020-04-14
 - GraalVM version (if different from Java): graalvm-ce-java-11-20.0.0
 - Quarkus version or git rev: 1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): apache-maven-3.6.3

**Additional context**
(Add any other context about the problem here.)

**Comment by cescoffier** [comment]
Can you post your application properties? I don't understand why it tries to load `tcnative`, it should use the ALPN support provided by Java.

**Comment by cescoffier** [comment]
If you could provide a reproducer it would be awesome! 

I just check the Netty code, and it seems  to be able to load `io.netty.internal.tcnative.SSL` while it shouldn't...

**Comment by smatijasevic** [comment]
example app is in attachment.
Also, application can't be run in dev mode with: mvn clean compile quarkus:dev .I must build runnable jar and then it works.
This is error if I try to run it from dev mode
`
2020-05-05 13:08:32,208 ERROR [io.qua.dep.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.NoSuchMethodError: 'void io.quarkus.builder.BuildChainBuilder.setClassLoader(java.lang.ClassLoader)'
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:92)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:245)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:130)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:52)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:61)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:265)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:40)
        at
`
Application need etcd on localhost:2379 and need /someKey with value in etcd.

[etcd-client.zip](https://github.com/quarkusio/quarkus/files/4580336/etcd-client.zip)

**Comment by cescoffier** [comment]
Your application is using https://github.com/hpehl/quarkus-grpc-client-extension and not quarkus-grpc.

**Comment by smatijasevic** [comment]
OK, I remove  that lib and replace it with quarkus-grpc. In jvm it works but still can't build native image
This is the error:
`[etcd-client-1.0.0-SNAPSHOT-runner:23361]    classlist:   7,042.36 ms,  1.00 GB
[etcd-client-1.0.0-SNAPSHOT-runner:23361]        setup:     341.79 ms,  1.00 GB
Error: substitution target for io.quarkus.grpc.runtime.graal.Target_com_google_protobuf_GeneratedMessageV3_FieldAccessorTable_RepeatedFieldAccessor_ReflectionInvoker is invalid as inner class ReflectionInvoker in com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$RepeatedFieldAccessor can not be found. Make sure that the inner class is present.
com.oracle.svm.core.util.UserError$UserException: substitution target for io.quarkus.grpc.runtime.graal.Target_com_google_protobuf_GeneratedMessageV3_FieldAccessorTable_RepeatedFieldAccessor_ReflectionInvoker is invalid as inner class ReflectionInvoker in com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$RepeatedFieldAccessor can not be found. Make sure that the inner class is present.
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:838)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.interceptParameterType(AnnotationSubstitutionProcessor.java:859)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.interceptParameterTypes(AnnotationSubstitutionProcessor.java:876)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:619)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:326)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:298)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
        at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:893)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:830)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
`
[etcd-client.zip](https://github.com/quarkusio/quarkus/files/4585861/etcd-client.zip)

**Comment by cescoffier** [comment]
I got it working with:

```
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>de.atron.atries.rx</groupId>
  <artifactId>etcd-client</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>999-SNAPSHOT</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>999-SNAPSHOT</quarkus.platform.version>
    <surefire-plugin.version>2.22.1</surefire-plugin.version>

    <quarkus-grpc.version>999-SNAPSHOT</quarkus-grpc.version>
    <grpc.version>1.25.0</grpc.version>
    <protoc.version>3.5.1</protoc.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-grpc</artifactId>
      <version>999-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>


  </dependencies>


  <build>
    <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.6.2</version>
      </extension>
    </extensions>
    <plugins>

      <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.5.1</version>
                <configuration>
                    <protocArtifact>com.google.protobuf:protoc:${protoc.version}:exe:${os.detected.classifier}</protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
                    <protocPlugins>
                        <protocPlugin>
                            <id>quarkus-grpc-protoc-plugin</id>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-grpc-protoc-plugin</artifactId>
                            <version>${quarkus-grpc.version}</version>
                            <mainClass>io.quarkus.grpc.protoc.plugin.MutinyGrpcGenerator</mainClass>
                        </protocPlugin>
                    </protocPlugins>
                </configuration>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemProperties>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
          </systemProperties>
        </configuration>
      </plugin>
    </plugins>
  </build>
  ... 
</project>
```

**Comment by michalszynkiewicz** [comment]
I'm closing the issue because @cescoffier pasted a config that works for him and we haven't heard from @smatijasevic that it does not work for him.
