### ISSUE TITLE
Bean with generated no-args constructor fails to be found during native image build

### ISSUE THREAD

**Issue by aguibert** [quarkusio/quarkus#9132]
**Describe the bug**
I am working on the HiberanteRX extension for Quarkus, and as a part of that I have a bean that produces the type [`Mutiny.Session`](https://github.com/aguibert/hibernate-rx/blob/mutiny-publish-2/hibernate-rx-api/src/main/java/org/hibernate/rx/mutiny/Mutiny.java#L12) which is a concrete class with a 1-arg constructor:

```java
public class Mutiny {
	public static class Session {
		private RxSession session;
		public Session(RxSession session) {
			this.session = session;
		}
                // ...
        }
}
```

The producer bean can be seen here: https://github.com/aguibert/quarkus/blob/hibernate-rx-missing-ctor-issue/extensions/hibernate-rx/runtime/src/main/java/io/quarkus/hibernate/rx/runtime/RxSessionProducer.java#L30

**Expected behavior**
The bean should produce objects like it does in JVM mode.

**Actual behavior**
Native image build fails with the following exception:

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.hibernate.rx.mutiny.Mutiny$Session.<init>(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_ClientProxy.<init>(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_ClientProxy.zig:240)
Call path from entry point to io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_ClientProxy.<init>(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean):
	at io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_ClientProxy.<init>(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_ClientProxy.zig:238)
	at io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.proxy(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.zig:356)
	at io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.get(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.zig:131)
	at io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.get(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.zig:44)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:380)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:393)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:244)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:1)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:188)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:141)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:342)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.hibernate.rx.mutiny.Mutiny$Session.<init>(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_ClientProxy.<init>(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_ClientProxy.zig:240)
Call path from entry point to io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_ClientProxy.<init>(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean):
	at io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_ClientProxy.<init>(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_ClientProxy.zig:238)
	at io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.proxy(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.zig:356)
	at io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.get(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.zig:131)
	at io.quarkus.hibernate.rx.runtime.RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.get(RxSessionProducer_ProducerMethod_mutinySession_5489b4c6464fe51fee98af22f54d8c1e0f37700c_Bean.zig:44)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:380)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:393)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:244)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:1)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:188)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:141)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:342)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:221)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**To Reproduce**
1. Clone and checkout this branch of hibernate-rx: https://github.com/aguibert/hibernate-rx/tree/mutiny-publish-2
2. Build that project with `./gradlew publishToMavenLocal`
3. Checkout my quarkus branch: https://github.com/aguibert/quarkus/tree/hibernate-rx-missing-ctor-issue
4. Do full rebuild of quarkus repo
5. Start postgresql container: `docker run -p 5431:5432 -e POSTGRES_USER=hibernate_orm_test -e POSTGRES_PASSWORD=hibernate_orm_test -e POSTGRES_DB=hibernate_orm_test postgres:10.5`
5. Run the hibernate-rx integration tests with: `cd integration-tests/hibernate-rx/ && mvn verify -Dtest-postgresql -Dnative`

**Configuration**
Included in reproducer

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin aguibert-mbp 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 
```
java version "1.8.0_221"
Java(TM) 2 Runtime Environment, Standard Edition (IBM build 1.8.0_221-b11 06_Aug_2019_07_06 Mac OS X x64(SR5 FP40))
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
IBM Java ORB build orb80-20190708.00
XML build XL TXE Java 1.0.61
XML build IBM JAXP 1.6.1
XML build XML4J 4.5.31
```
 - GraalVM version (if different from Java): 
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit GraalVM CE 19.3.1 (build 25.242-b06-jvmci-19.3-b07, mixed mode)
```
 - Quarkus version or git rev: See steps to reproduce for reproducer branch
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.8.0_221, vendor: Oracle Corporation, runtime: /Users/aguibert/dev/java/ibm_jdk-8.0.5.40/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
```

**Additional context**
N/A

**Comment by aguibert** [comment]
CC @mkouba

**Comment by geoand** [comment]
If push comes to shove, you could always generate the missing constructor in the Quarkus extension.

**Comment by mkouba** [comment]
Hm, I think that this could be related to https://github.com/quarkusio/quarkus/issues/9050 which should be fixed in master. @aguibert Could pls test your reproducer with the current master?

**Comment by geoand** [comment]
@aguibert is this still an issue?

**Comment by aguibert** [comment]
I believe I worked around the issue and haven't ran into it again since. Since nobody else has +1'd this issue in the past month or so we can close it
