### ISSUE TITLE
Configure quarkus-oidc to use any other vert.x oauth2 providers other than KeycloakAuth

### ISSUE THREAD

**Issue by henrique-mmartins** [quarkusio/quarkus#9155]
**Description**
Configure quarkus-oidc to use any other vert.x oauth2 providers other than KeycloakAuth

**Implementation ideas**
Right now quarkus-oidc only supports KeycloakAuth is there a possibility to add the other providers from vert.x oauth2 in the OidcRecorder?

**Comment by sberyozkin** [comment]
@henrique-mmartins It is called `KeycloakAuth` but all it does it uses a standard OIDC discovery protocol.
What issue are you seeing ?

**Comment by henrique-mmartins** [comment]
Hey sberyozkin, 

Please take a look at the code and the stack trace, maybe I'm doing something wrong.

- application.properties (I removed the tenant-id and client-id)
```
quarkus.oidc.auth-server-url=https://login.microsoftonline.com/{tenant-id}/.well-known/openid-configuration
quarkus.oidc.client-id={client-id}
quarkus.oidc.credentials.secret=https://login.microsoftonline.com/common/discovery/keys
```

- The class with a secure endpoint

```
import javax.annotation.security.RolesAllowed;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/v1")
public class ExampleResource {
    
    @GET
    @Path("/secure")
    @Produces(MediaType.TEXT_PLAIN)
    @RolesAllowed("user")
    public String hello() {
        return "secured";
    }
}
```
The application doesn't startup and gives the following error

```
ERROR: Failed to start application
io.quarkus.oidc.OIDCException: OIDC server is not available at the 'quarkus.oidc.auth-server-url' URL. Please make sure it is correct. Note it has to end with a realm value if you work with Keycloak, for example: 'https://localhost:8180/auth/realms/quarkus'
	at io.quarkus.oidc.runtime.OidcRecorder.toOidcException(OidcRecorder.java:211)
	at io.quarkus.oidc.runtime.OidcRecorder$2.handle(OidcRecorder.java:161)
	at io.quarkus.oidc.runtime.OidcRecorder$2.handle(OidcRecorder.java:157)
	at io.vertx.ext.auth.oauth2.providers.KeycloakAuth.lambda$discover$0(KeycloakAuth.java:125)
	at io.vertx.ext.auth.oauth2.providers.OpenIDConnectAuth.lambda$discover$1(OpenIDConnectAuth.java:44)
	at io.vertx.ext.auth.oauth2.impl.OAuth2API.lambda$null$1(OAuth2API.java:124)
	at io.vertx.core.http.impl.HttpClientResponseImpl$BodyHandler.notifyHandler(HttpClientResponseImpl.java:292)
	at io.vertx.core.http.impl.HttpClientResponseImpl.lambda$bodyHandler$0(HttpClientResponseImpl.java:193)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:248)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$beginResponse$0(Http1xClientConnection.java:480)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.endResponse(Http1xClientConnection.java:499)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.access$000(Http1xClientConnection.java:237)
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:634)
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:584)
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:566)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1470)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.vertx.core.impl.NoStackTraceThrowable: Not Found
```

**Comment by sberyozkin** [comment]
Hi @henrique-mmartins 
It should most likely be 
`quarkus.oidc.auth-server-url=https://login.microsoftonline.com/{tenant-id}`
try it please

**Comment by sberyozkin** [comment]
`quarkus.oidc.credentials.secret` should have a secret that will quarkus-oidc will use to authenticate to `https://login.microsoftonline.com/` when getting the tokens, etc. The JWK set for the local verification will be fetched as part of the discovery process

**Comment by sberyozkin** [comment]
@henrique-mmartins Have you made it work ? thanks

**Comment by henrique-mmartins** [comment]
@sberyozkin sorry for the late response

I tested everything on the azure side to make sure it wasn't a mistake on the configuration of the AAD. The correct URL given the [Microsoft documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows) goes at follows:  https://{b2cDomainHost}/{tenantId}/{policyName}/v2.0/.well-known/openid-configuration/
That should give me a configuration like this:

That url should be added to quarkus.oidc.auth-server-url
````
quarkus.oidc.auth-server-url=https://{b2cDomainHost}/{tenantId}/{policyName}/v2.0/.well-known/openid-configuration/
quarkus.oidc.client-id={clientId}
quarkus.oidc.credentials.secret={secretKey}
````
I used the same configuration on the [node.js example](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi) from microsoft and the flow ran without issues, which leads me to believe that the issue is on the quarkus-oidc side. 

Could you shed some light on this issue? I don't know what is happening

**Comment by henrique-mmartins** [comment]
Hello @sberyozkin 

I made it work!

```
quarkus.oidc.auth-server-url=https://{b2cDomainHost}/{tenantnamme}/{policyName}/v2.0
quarkus.oidc.client-id={clientId}
quarkus.oidc.credentials.secret={secretKey}
quarkus.oidc.token.issuer=https://{tenantId}.b2clogin.com/{tenantId}/v2.0/
```
And if I may, there is something that I would like to suggest: Please inform that the code appends the `/.well-known/openid-configuration/` to the end of the auth-server-url since it's not visible in the exception or the documentation

**Comment by sberyozkin** [comment]
@henrique-mmartins Thanks, I'll update the docs before resolving this issue.
In general `quarkus-oidc` should be capable of connecting to any OIDC server, it was a design decision that we made when moving from a Keycloak cebtric extensioin. 
Cheers
