### ISSUE TITLE
HealthCheckResponse builder does not create matching health response

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#9282]
I'm trying to make my own health report entry, but am running into an issue where the builder does not seem to be actually building a health entry with the data I use to set it up:

*Code:*
```
@Readiness
@ApplicationScoped
public class DefaultKeysHealthCheck implements HealthCheck {
    private static final String CHECK_NAME = "Not using packaged keys.";

    @Inject
    DefaultKeysChecker defaultKeysChecker;

    @Override
    public HealthCheckResponse call() {
        if(this.defaultKeysChecker.usingPackagedKeys()){
            return HealthCheckResponse.builder()
                    .down()
                    .name(CHECK_NAME)
                    .withData("reason", "One or more of the keys used were identified to be the ones packaged with the original project.")
                    .build();
        }
        return HealthCheckResponse.up(CHECK_NAME);
    }
}
```

*Resulting entry for DOWN in the /health endpoint:*
```
{
  "name": "com.gjs.taskTimekeeper.webServer.server.health.DefaultKeysHealthCheck_ClientProxy",
  "status": "DOWN",
  "data": {
  }
}
```

**Comment by jmartisk** [comment]
I guess I'd need the whole project source, because when trying to reproduce it, I can see the expected data.

There must be something else fishy with your project, because as I noticed, the health check's name is shown as `com.gjs.taskTimekeeper.webServer.server.health.DefaultKeysHealthCheck_ClientProxy` while it should correctly be `Not using packaged keys.`, as per the code example. That did not happen to me either when attempting to reproduce.

**Comment by GregJohnStewart** [comment]
Sure, the repository is here: https://github.com/GregJohnStewart/task-timekeeper

On Quarkus `1.4.2.Final`

The latest for the quarkus work is under the "webserver-work" branch

Running the project: `./gradlew :Webserver:Server:quarkusdev`

**Comment by jmartisk** [comment]
It seems to be because your health check is throwing an exception:
```
 2020-05-15 09:56:58,866 ERROR [io.sma.hea.SmallRyeHealthReporter] (vert.x-worker-thread-1) Error processing Health Checks: java.lang.NullPointerException
        at com.gjs.taskTimekeeper.webServer.server.health.DefaultKeysHealthCheck.call(DefaultKeysHealthCheck.java:31)
        at com.gjs.taskTimekeeper.webServer.server.health.DefaultKeysHealthCheck_ClientProxy.call(DefaultKeysHealthCheck_ClientProxy.zig:97)
        at io.smallrye.health.SmallRyeHealthReporter.jsonObject(SmallRyeHealthReporter.java:187)
        at io.smallrye.health.SmallRyeHealthReporter.fillCheck(SmallRyeHealthReporter.java:174)
        at io.smallrye.health.SmallRyeHealthReporter.processChecks(SmallRyeHealthReporter.java:162)
        at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:140)
        at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:99)
        at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getHealth(SmallRyeHealthReporter_ClientProxy.zig:428)
        at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.handle(SmallRyeHealthHandler.java:26)
        at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.handle(SmallRyeHealthHandler.java:18)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

In that case the health reporter does not know what data to put in, or even what the name of the health check is. 
We could think whether the reported status should look differently, maybe it could automatically contain at least part of the exception stack trace. 
But generally I guess you should handle that on the application level and if an exception is thrown, catch it and build a proper `DOWN` response.

**Comment by jmartisk** [comment]
So it turns out that the health reporter by default includes the message of the root cause. In your case, `NullPointerException` has no message, so the data is empty.

**Comment by GregJohnStewart** [comment]
Gah, a little embarrassed I didn't pick up on that. I have noticed lately that some beans aren't properly injected with `@Inject`, don't know how I missed this particular one.

Also unsure why the usage of `@Inject` seems rather flaky, wiring works fine if the injected object/ bean is made part of the constructor.

At any rate, thanks for the tip.
