### ISSUE TITLE
Rest client: path param _ has not been provided by the parameter map

### ISSUE THREAD

**Issue by Meemaw** [quarkusio/quarkus#9289]
**Describe the bug**

`@RestClient` doesn't seem to pass path params correctly. It crashes with the following error: `java.lang.IllegalArgumentException: RESTEASY003720: path param SessionID has not been provided by the parameter map`

This is how it is being registered: https://github.com/Meemaw/Insight/blob/re-enable-beacon-tracking-e2e-test/backend/session/session-api-contracts/src/main/java/com/meemaw/session/resource/v1/SessionResource.java#L24

This is how it is being Injected: https://github.com/Meemaw/Insight/blob/re-enable-beacon-tracking-e2e-test/backend/beacon/api/src/main/java/com/meemaw/rec/beacon/service/BeaconService.java#L35

Usage: https://github.com/Meemaw/Insight/blob/re-enable-beacon-tracking-e2e-test/backend/beacon/api/src/main/java/com/meemaw/rec/beacon/service/BeaconService.java#L48

Interestingly, this seems to works when I run unit tests, but fails when application is built into a JAR.

**To Reproduce**
1. `git clone -b re-enable-beacon-tracking-e2e-test https://github.com/Meemaw/insight quarkus-rest-client-bug`
2. `cd backend/local-test-services`
3. `docker-compose up beacon-api`
4. Open a new terminal and execute the following curl command:

```sh
curl --location --request POST 'http://localhost:8081/v1/beacon/beat?OrgID=test-1&SessionID=b06af0c7-8262-4feb-a0ac-d1303fbbc876&UserID=864096b7-695c-4815-9036-05f4c3647941&PageID=a24eaffa-f035-450c-8a2b-116d146b9823' \
--header 'Content-Type: application/json' \
--data-raw '{
    "e": [
        {
            "t": 28,
            "e": 3,
            "a": [
                "http://localhost:8082/v1/sessions",
                "resource",
                77.09500007331371,
                21.44500007852912
            ]
        },
        {
            "t": 84,
            "e": 5,
            "a": [
                61,
                60,
                "<BUTTON",
                ":data-testid",
                "first-button"
            ]
        },
        {
            "t": 92,
            "e": 6,
            "a": [
                61,
                60
            ]
        },
        {
            "t": 92,
            "e": 7,
            "a": [
                61,
                60
            ]
        },
        {
            "t": 93,
            "e": 5,
            "a": [
                61,
                60,
                "<BUTTON",
                ":data-testid",
                "first-button"
            ]
        }
    ],
    "s": 1
}'
```

**Environment (please complete the following information):**
 - Output of `java -version`: openjdk version "14" 2020-03-17
 - Quarkus version or git rev: 1.4.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.4.0

**Aditional context**
Full error (JSON logging):

```json
{
	"timestamp": "2020-05-14T05:27:33.223Z",
	"sequence": 2056,
	"loggerClassName": "org.jboss.resteasy.resteasy_jaxrs.i18n.LogMessages_$logger",
	"loggerName": "org.jboss.resteasy.resteasy_jaxrs.i18n",
	"level": "ERROR",
	"message": "RESTEASY002020: Unhandled asynchronous exception, sending back 500",
	"threadName": "executor-thread-1",
	"threadId": 15,
	"mdc": {
		"uid": "864096b7-695c-4815-9036-05f4c3647941",
		"sessionID": "b06af0c7-8262-4feb-a0ac-d1303fbbc876",
		"beacon.sequence": "1",
		"beacon.timestamp": "0",
		"pageID": "a24eaffa-f035-450c-8a2b-116d146b9823",
		"X-Request-Id": "531b8c82-850c-4e79-aaaf-ce29fe579ddf",
		"orgID": "test-1"
	},
	"ndc": "",
	"hostName": "fbe1f0d7029f",
	"processName": "service-runner.jar",
	"processId": 1,
	"exception": {
		"refId": 1,
		"exceptionType": "org.jboss.resteasy.spi.ApplicationException",
		"message": "java.lang.IllegalArgumentException: RESTEASY003720: path param SessionID has not been provided by the parameter map",
		"frames": [{
			"class": "org.jboss.resteasy.core.MethodInjectorImpl",
			"method": "invoke",
			"line": 180
		}, {
			"class": "org.jboss.resteasy.core.MethodInjectorImpl",
			"method": "invoke",
			"line": 130
		}, {
			"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
			"method": "internalInvokeOnTarget",
			"line": 621
		}, {
			"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
			"method": "invokeOnTargetAfterFilter",
			"line": 487
		}, {
			"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
			"method": "lambda$invokeOnTarget$2",
			"line": 437
		}, {
			"class": "org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext",
			"method": "filter",
			"line": 362
		}, {
			"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
			"method": "invokeOnTarget",
			"line": 439
		}, {
			"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
			"method": "invoke",
			"line": 400
		}, {
			"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
			"method": "invoke",
			"line": 374
		}, {
			"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
			"method": "invoke",
			"line": 67
		}, {
			"class": "org.jboss.resteasy.core.SynchronousDispatcher",
			"method": "invoke",
			"line": 488
		}, {
			"class": "org.jboss.resteasy.core.SynchronousDispatcher",
			"method": "lambda$invoke$4",
			"line": 259
		}, {
			"class": "org.jboss.resteasy.core.SynchronousDispatcher",
			"method": "lambda$preprocess$0",
			"line": 160
		}, {
			"class": "org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext",
			"method": "filter",
			"line": 362
		}, {
			"class": "org.jboss.resteasy.core.SynchronousDispatcher",
			"method": "preprocess",
			"line": 163
		}, {
			"class": "org.jboss.resteasy.core.SynchronousDispatcher",
			"method": "invoke",
			"line": 245
		}, {
			"class": "io.quarkus.resteasy.runtime.standalone.RequestDispatcher",
			"method": "service",
			"line": 73
		}, {
			"class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
			"method": "dispatch",
			"line": 123
		}, {
			"class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
			"method": "access$000",
			"line": 36
		}, {
			"class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1",
			"method": "run",
			"line": 87
		}, {
			"class": "org.jboss.threads.ContextClassLoaderSavingRunnable",
			"method": "run",
			"line": 35
		}, {
			"class": "org.jboss.threads.EnhancedQueueExecutor",
			"method": "safeRun",
			"line": 2046
		}, {
			"class": "org.jboss.threads.EnhancedQueueExecutor$ThreadBody",
			"method": "doRunTask",
			"line": 1578
		}, {
			"class": "org.jboss.threads.EnhancedQueueExecutor$ThreadBody",
			"method": "run",
			"line": 1452
		}, {
			"class": "org.jboss.threads.DelegatingRunnable",
			"method": "run",
			"line": 29
		}, {
			"class": "org.jboss.threads.ThreadLocalResettingRunnable",
			"method": "run",
			"line": 29
		}, {
			"class": "java.lang.Thread",
			"method": "run"
		}, {
			"class": "org.jboss.threads.JBossThread",
			"method": "run",
			"line": 479
		}],
		"causedBy": {
			"exception": {
				"refId": 2,
				"exceptionType": "java.lang.IllegalArgumentException",
				"message": "RESTEASY003720: path param SessionID has not been provided by the parameter map",
				"frames": [{
					"class": "org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl",
					"method": "replaceParameter",
					"line": 637
				}, {
					"class": "org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl",
					"method": "buildCharSequence",
					"line": 560
				}, {
					"class": "org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl",
					"method": "buildString",
					"line": 529
				}, {
					"class": "org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl",
					"method": "buildFromValues",
					"line": 759
				}, {
					"class": "org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl",
					"method": "build",
					"line": 751
				}, {
					"class": "org.jboss.resteasy.client.jaxrs.internal.ClientWebTarget",
					"method": "request",
					"line": 361
				}, {
					"class": "org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker",
					"method": "createRequest",
					"line": 166
				}, {
					"class": "org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker",
					"method": "invokeAsync",
					"line": 117
				}, {
					"class": "org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker",
					"method": "invoke",
					"line": 112
				}, {
					"class": "org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy",
					"method": "invoke",
					"line": 76
				}, {
					"class": "com.sun.proxy.$Proxy50",
					"method": "get"
				}, {
					"class": "jdk.internal.reflect.NativeMethodAccessorImpl",
					"method": "invoke0"
				}, {
					"class": "jdk.internal.reflect.NativeMethodAccessorImpl",
					"method": "invoke"
				}, {
					"class": "jdk.internal.reflect.DelegatingMethodAccessorImpl",
					"method": "invoke"
				}, {
					"class": "java.lang.reflect.Method",
					"method": "invoke"
				}, {
					"class": "org.jboss.resteasy.microprofile.client.ProxyInvocationHandler",
					"method": "invoke",
					"line": 149
				}, {
					"class": "com.sun.proxy.$Proxy53",
					"method": "get"
				}, {
					"class": "com.meemaw.rec.beacon.service.BeaconService",
					"method": "pageExists",
					"line": 49
				}, {
					"class": "com.meemaw.rec.beacon.service.BeaconService",
					"method": "process",
					"line": 98
				}, {
					"class": "com.meemaw.rec.beacon.service.BeaconService_ClientProxy",
					"method": "process",
					"line": 182
				}, {
					"class": "com.meemaw.rec.beacon.resource.v1.BeaconResourceImpl",
					"method": "beacon",
					"line": 55
				}, {
					"class": "com.meemaw.rec.beacon.resource.v1.BeaconResourceImpl",
					"method": "textBeacon",
					"line": 49
				}, {
					"class": "com.meemaw.rec.beacon.resource.v1.BeaconResourceImpl_Subclass",
					"method": "textBeacon$$superaccessor1",
					"line": 30
				}, {
					"class": "com.meemaw.rec.beacon.resource.v1.BeaconResourceImpl_Subclass$$function$$1",
					"method": "apply",
					"line": 77
				}, {
					"class": "io.quarkus.arc.impl.AroundInvokeInvocationContext",
					"method": "proceed",
					"line": 54
				}, {
					"class": "io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor",
					"method": "validateMethodInvocation",
					"line": 69
				}, {
					"class": "io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor",
					"method": "validateMethodInvocation",
					"line": 17
				}, {
					"class": "io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean",
					"method": "intercept",
					"line": 177
				}, {
					"class": "io.quarkus.arc.impl.InterceptorInvocation",
					"method": "invoke",
					"line": 41
				}, {
					"class": "io.quarkus.arc.impl.AroundInvokeInvocationContext",
					"method": "perform",
					"line": 41
				}, {
					"class": "io.quarkus.arc.impl.InvocationContexts",
					"method": "performAroundInvoke",
					"line": 32
				}, {
					"class": "com.meemaw.rec.beacon.resource.v1.BeaconResourceImpl_Subclass",
					"method": "textBeacon",
					"line": 219
				}, {
					"class": "jdk.internal.reflect.NativeMethodAccessorImpl",
					"method": "invoke0"
				}, {
					"class": "jdk.internal.reflect.NativeMethodAccessorImpl",
					"method": "invoke"
				}, {
					"class": "jdk.internal.reflect.DelegatingMethodAccessorImpl",
					"method": "invoke"
				}, {
					"class": "java.lang.reflect.Method",
					"method": "invoke"
				}, {
					"class": "org.jboss.resteasy.core.MethodInjectorImpl",
					"method": "invoke",
					"line": 167
				}, {
					"class": "org.jboss.resteasy.core.MethodInjectorImpl",
					"method": "invoke",
					"line": 130
				}, {
					"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
					"method": "internalInvokeOnTarget",
					"line": 621
				}, {
					"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
					"method": "invokeOnTargetAfterFilter",
					"line": 487
				}, {
					"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
					"method": "lambda$invokeOnTarget$2",
					"line": 437
				}, {
					"class": "org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext",
					"method": "filter",
					"line": 362
				}, {
					"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
					"method": "invokeOnTarget",
					"line": 439
				}, {
					"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
					"method": "invoke",
					"line": 400
				}, {
					"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
					"method": "invoke",
					"line": 374
				}, {
					"class": "org.jboss.resteasy.core.ResourceMethodInvoker",
					"method": "invoke",
					"line": 67
				}, {
					"class": "org.jboss.resteasy.core.SynchronousDispatcher",
					"method": "invoke",
					"line": 488
				}, {
					"class": "org.jboss.resteasy.core.SynchronousDispatcher",
					"method": "lambda$invoke$4",
					"line": 259
				}, {
					"class": "org.jboss.resteasy.core.SynchronousDispatcher",
					"method": "lambda$preprocess$0",
					"line": 160
				}, {
					"class": "org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext",
					"method": "filter",
					"line": 362
				}, {
					"class": "org.jboss.resteasy.core.SynchronousDispatcher",
					"method": "preprocess",
					"line": 163
				}, {
					"class": "org.jboss.resteasy.core.SynchronousDispatcher",
					"method": "invoke",
					"line": 245
				}, {
					"class": "io.quarkus.resteasy.runtime.standalone.RequestDispatcher",
					"method": "service",
					"line": 73
				}, {
					"class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
					"method": "dispatch",
					"line": 123
				}, {
					"class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
					"method": "access$000",
					"line": 36
				}, {
					"class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1",
					"method": "run",
					"line": 87
				}, {
					"class": "org.jboss.threads.ContextClassLoaderSavingRunnable",
					"method": "run",
					"line": 35
				}, {
					"class": "org.jboss.threads.EnhancedQueueExecutor",
					"method": "safeRun",
					"line": 2046
				}, {
					"class": "org.jboss.threads.EnhancedQueueExecutor$ThreadBody",
					"method": "doRunTask",
					"line": 1578
				}, {
					"class": "org.jboss.threads.EnhancedQueueExecutor$ThreadBody",
					"method": "run",
					"line": 1452
				}, {
					"class": "org.jboss.threads.DelegatingRunnable",
					"method": "run",
					"line": 29
				}, {
					"class": "org.jboss.threads.ThreadLocalResettingRunnable",
					"method": "run",
					"line": 29
				}, {
					"class": "java.lang.Thread",
					"method": "run"
				}, {
					"class": "org.jboss.threads.JBossThread",
					"method": "run",
					"line": 479
				}]
			}
		}
	}
}
```

**Comment by geoand** [comment]
cc @kenfinnigan @michalszynkiewicz

**Comment by Ladicek** [comment]
I don't see anything obviously wrong. Given that RestClient is now part of RESTEasy, CC @asoldano

**Comment by michalszynkiewicz** [comment]
@Meemaw thank you for your report, could you create a smaller reproducer of the problem?

**Comment by Meemaw** [comment]
@michalszynkiewicz for some reason I have problem creating a smaller reproducer due to the problems with CDI.

I keep getting this error:
```java
2020-05-14 16:22:43,205 ERROR [io.qua.dep.dev.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.my.group.SessionResource and qualifiers [@RestClient]
	- java member: org.my.group.BeaconService#sessionResource
	- declared on CLASS bean [types=[org.my.group.BeaconService, java.lang.Object], qualifiers=[@Default, @Any], target=org.my.group.BeaconService]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:973)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:240)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:135)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:358)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:931)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

SessionResource.java
```java
@Path(SessionResource.PATH)
@Consumes(MediaType.TEXT_PLAIN)
@Produces(MediaType.TEXT_PLAIN)
@RegisterRestClient
public interface SessionResource {

  String PATH = "/v1/sessions";

  @GET
  @Path("{SessionID}/pages/{PageID}")
  CompletionStage<Response> get(
      @PathParam("SessionID") UUID sessionID,
      @PathParam("PageID") UUID pageID,
      @QueryParam("orgID") String orgID);
}
```

SessionResourceImpl.java
```java
public class SessionResourceImpl implements SessionResource {

  @Override
  public CompletionStage<Response> get(UUID sessionID, UUID pageID, String orgID) {
    return CompletableFuture.completedStage(Response.ok("Hello").build());
  }
}
```

BeaconService.java
```java
@ApplicationScoped
public class BeaconService {

  @Inject @RestClient SessionResource sessionResource;

  public CompletionStage<Response> hello() {
    return sessionResource.get(UUID.randomUUID(), UUID.randomUUID(), "org123");
  }
}
```

**Comment by Meemaw** [comment]
I've identified the root cause for the problem. It was wrong BASE_URL: `http:session-api` while it should have been `http://session-api`.

I think we can close this as this is not a bug in Quarkus, but I still think that the error message should be better in this case and the BASE_URL like this somehow validated?
