### ISSUE TITLE
add codeready-containers (crc) extension

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#9317]
**Description**
as discussed on [list](https://groups.google.com/d/msg/quarkus-dev/fwbKpeRZp7M/1uotF_dSAQAJ) an openshift/CRC extension would be nice to handle the defaults to have container-image / deploy settings just working out of box.

from list:
```
Ok thanks for your help Max and I also got help from Red Hat DevEx team, I got it working, need to be careful with the repo for the push and the ServiceAccount chosen You could do policy changes too, but if you just match up the names, for dev trialing, it's easier not to have to mess with policy. Here's what finally yielded a working solution:

./mvnw clean package -Dquarkus.container-image.build=true -Dquarkus.container-image.registry=default-route-openshift-image-registry.apps-crc.testing -Dquarkus.container-image.group=default

There should always be a "default" NameSpace in CodeReadyContainers.

A deploy yaml like the above in this thread should work but with
 - image: image-registry.openshift-image-registry.svc:5000/default/operator-example:1.0-SNAPSHOT

I tried to fully document the process and provide working example for this simplest possible operator deploy to CRC in the Readme of this repo here:

https://github.com/bentito/operator-example

If someone wants to try it with a fresh CRC install and has any comments I'd be happy to fix up. I freshened my CRC install and ran through all the steps outlined in that section of the Readme, so I am pretty sure it's correct and sufficient.

It's very cool to be able to run the whole thing locally from the Quarkus tooling all the way to working pod.
```

**Comment by geoand** [comment]
Question: Is `default-route-openshift-image-registry.apps-crc.testing` always present for CRC?

As for the `default` namespace, is that also always needed?

cc @bentito

**Comment by bentito** [comment]
There will always a default namespace. So as an example this is good to use, as should work out of the box. Should also be able to use your own namespace but I have not tested that path.

**Comment by geoand** [comment]
@bentito you could try and see if it works with a custom namespace? I would like to know because if we can use a custom namespace, then I would prefer to use it as it would make the experience more consistent with what we already have

**Comment by bentito** [comment]
yep, will try to make it work tonight (USA, Eastern)

Brett Tofel
Sr. Software Engineer
Red Hat (OpenShift Metering)

**Comment by bentito** [comment]
Sorry about delay, it failed and here's the report. Looks like a missing auth item for non-default NS deploy:
built & run with the following:
```bash
./mvnw clean package -Pnative -Dquarkus.native.container-build=true -Dnative-image.xmx=5g -Dquarkus.container-image.build=true -Dquarkus.container-image.registry=default-route-openshift-image-registry.apps-crc.testing -Dquarkus.container-image.group=btofel

export DEPLOY_NAMESPACE=btofel

docker login -u kubeadmin -p $(oc whoami -t) default-route-openshift-image-registry.apps-crc.testing

docker push default-route-openshift-image-registry.apps-crc.testing/btofel/operator-example:1.0-SNAPSHOT

make apply
make deploy
```
I get this in the operator logs:
```bash
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-05-27 19:07:19,036 ERROR [io.qua.application] (main) Failed to start application: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/btofel/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:serviceaccount:btofel:operator-example" cannot list resource "pods" in API group "" in the namespace "btofel".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:505)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:151)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:621)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
	at com.coreos.operator.example.PodLister.onStartup(PodLister.java:18)
	at com.coreos.operator.example.PodLister_Observer_onStartup_8d7b338c7415a5b0bcaaf3b82fd300311baae948.notify(PodLister_Observer_onStartup_8d7b338c7415a5b0bcaaf3b82fd300311baae948.zig:99)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:113)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent31.deploy_0(LifecycleEventsBuildStep$startupEvent31.zig:58)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent31.deploy(LifecycleEventsBuildStep$startupEvent31.zig:77)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:198)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)

2020-05-27 19:07:19,048 ERROR [io.qua.run.Application] (main) Error running Quarkus application: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:275)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/btofel/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:serviceaccount:btofel:operator-example" cannot list resource "pods" in API group "" in the namespace "btofel".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:505)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:151)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:621)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
	at com.coreos.operator.example.PodLister.onStartup(PodLister.java:18)
	at com.coreos.operator.example.PodLister_Observer_onStartup_8d7b338c7415a5b0bcaaf3b82fd300311baae948.notify(PodLister_Observer_onStartup_8d7b338c7415a5b0bcaaf3b82fd300311baae948.zig:99)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:113)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent31.deploy_0(LifecycleEventsBuildStep$startupEvent31.zig:58)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent31.deploy(LifecycleEventsBuildStep$startupEvent31.zig:77)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:198)
	... 6 more
```

**Comment by geoand** [comment]
Thanks for that!

It indeed seems like using `default` namespace would be easiest

**Comment by bentito** [comment]
Also for ref in this issue thread, the reference repo is:
github.com:bentito/operator-example

**Comment by geoand** [comment]
I don't really know how I am going to do this because I am on Ubuntu where CRC isn't really supported... 
If someone has a link or instructions on how to setup CRC for Ubuntu, I would be greatful.

**Comment by bentito** [comment]
Let me know if I can help at all in recreating or documentation. I have
latest CRC running on my Mac.

Brett Tofel
Sr. Software Engineer
Red Hat (OpenShift Metering)

**Comment by geoand** [comment]
The problem is that the only thing I can do is develop the extension blindly and then give to someone as yourself to test it. I have no way of getting immediate feedback which is very very inefficient...
