### ISSUE TITLE
GraalVM SDK required in for OpenJDK runs

### ISSUE THREAD

**Issue by jpechane** [quarkusio/quarkus#9320]
**Describe the bug**
When Quarkus app is executed on OpenShift then GraalVM SKD should be an optional dependency. Now it requires the presence of `ImgaeInfo` class duiring app lifecycle and logging configuration.

**Expected behavior**
GraalVM SDK should not not be mandatory when app runs on OpenJDK.

**Actual behavior**
An exception is thorow during startup when removed

{noformat}
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.jboss.logmanager.LogContext
	at org.jboss.logmanager.LogManager.getLogger(LogManager.java:110)
	at org.jboss.logmanager.LogManager.getLogger(LogManager.java:27)
	at java.logging/java.util.logging.LogManager.demandLogger(LogManager.java:519)
	at java.logging/java.util.logging.LogManager.demandLogger(LogManager.java:515)
	at java.logging/java.util.logging.Logger.demandLogger(Logger.java:654)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:717)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:701)
	at org.jboss.logging.JDKLogger.<init>(JDKLogger.java:33)
	at org.jboss.logging.JDKLoggerProvider.getLogger(JDKLoggerProvider.java:24)
	at org.jboss.logging.LoggerProviders.logProvider(LoggerProviders.java:156)
	at org.jboss.logging.LoggerProviders.tryJDK(LoggerProviders.java:112)
	at org.jboss.logging.LoggerProviders.findProvider(LoggerProviders.java:107)
	at org.jboss.logging.LoggerProviders.find(LoggerProviders.java:34)
	at org.jboss.logging.LoggerProviders.<clinit>(LoggerProviders.java:31)
	at org.jboss.logging.Logger.getLogger(Logger.java:2465)
	at io.quarkus.runtime.configuration.ConfigUtils.<clinit>(ConfigUtils.java:39)
	at io.quarkus.runtime.generated.Config.<clinit>(Config.zig:16544)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:303)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.debezium.server.Main.main(Main.java:15)
{noformat}

**Comment by gunnarmorling** [comment]
s/OpenShift/OpenJDK/ :)

Motivation here is to avoid having to redistribute the Graal SDK when shipping a Quarkus-based JVM application.
