### ISSUE TITLE
mvn quarkus:dev NoSuchFileException for the provided jks

### ISSUE THREAD

**Issue by ozkanpakdil** [quarkusio/quarkus#9371]
**Describe the bug**
While writing https://stackoverflow.com/a/61834360/175554 I needed to test SSL with quarkus. normal command run with `java -jar pathofthejar` works but when I try to run `mvn quarkus:dev` I got this exception `Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:275)
        at io.quarkus.runtime.Application.start(Application.java:89)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:99)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.nio.file.NoSuchFileException: .\keystore.jks
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:160)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.getFileContent(VertxHttpRecorder.java:565)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.createSslOptions(VertxHttpRecorder.java:495)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:355)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:188)
        at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket35.deploy_0(VertxHttpProcessor$openSocket35.zig:100)
        at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket35.deploy(VertxHttpProcessor$openSocket35.zig:119)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:206)
`

**Expected behavior**
mvn quarkus:dev should run with ssl configuration

**Actual behavior**
throws exception and start fails.

**To Reproduce**
1. Clone https://github.com/ozkanpakdil/quarkus-examples/tree/master/local-ssl-usage
2. open any shell
3. run `mvn quarkus:dev`

**Configuration**
```properties
quarkus.http.ssl.certificate.key-store-file-type=JKS
quarkus.http.ssl.certificate.key-store-file=./keystore.jks
quarkus.http.ssl.certificate.key-store-password=changeme

quarkus.http.insecure-requests=redirect
```
Also can see it here https://github.com/ozkanpakdil/quarkus-examples/blob/master/local-ssl-usage/src/main/resources/application.properties

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18362.592] 
 - Output of `java -version`:  openjdk version "14.0.1" 2020-04-14
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev:  1.4.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by jaikiran** [comment]
Hello @ozkanpakdil, I am not really sure how relative paths (the `./keystore.jks` in this case) are supposed to work in dev mode. When Quarkus dev mode is launched, it's working directory (i.e. the value of `user.dir` system property) is the `target/` directory of Maven. Clearly the `keystore.jks` won't reside in that directory (instead it will be in `target/classes/` directory). I don't know if relative paths are recommended as values for cases like these. Maybe @stuartwdouglas or @gsmet will know.

**Comment by jaikiran** [comment]
> quarkus.http.ssl.certificate.key-store-file=./keystore.jks

Does changing that value to:
```
quarkus.http.ssl.certificate.key-store-file=keystore.jks
```
work?

**Comment by ozkanpakdil** [comment]
no it does not. here is the new exception
`Caused by: java.nio.file.NoSuchFileException: keystore.jks
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)`

**Comment by stuartwdouglas** [comment]
The working directory is /target, so can you try:

%dev.quarkus.http.ssl.certificate.key-store-file=../keystore.jks

**Comment by ozkanpakdil** [comment]
`quarkus.http.ssl.certificate.key-store-file=../keystore.jks`
worked thanks. I think we can close this now.
