### ISSUE TITLE
quarkus-ide-launcher breaks mvn dependency:analyze

### ISSUE THREAD

**Issue by rquinio** [quarkusio/quarkus#9506]
**Describe the bug**

When using https://maven.apache.org/plugins/maven-dependency-plugin/analyze-only-mojo.html there are some issues due to the new quarkus-ide-launcher introduced in 1.4 that is shading a lot of classes from other dependencies:

```
[INFO] --- maven-dependency-plugin:3.1.2:analyze-only (default)
[WARNING] Used undeclared dependencies found:
[WARNING]    io.quarkus:quarkus-ide-launcher:jar:1.4.1.Final:runtime
[WARNING] Unused declared dependencies found:
[WARNING]    org.slf4j:slf4j-api:jar:1.7.30:compile
```

It's possible to exclude the dependencies shaded by quarkus-ide-launcher from the analysis but the more you exclude the less interesting the plugin...

A workaround with Quarkus 1.4 was to exclude quarkus-core --> quarkus-ide-launcher transitive dependency, thinking IDE-related stuff shouldn't matter too much:

```
<dependencyManagement>
  <dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-core</artifactId>
    <exclusions>
      <exclusion>
        <artifactId>quarkus-ide-launcher</artifactId>
        <groupId>io.quarkus</groupId>
      </exclusion>
    </exclusions>
  </dependency>
<dependencyManagement>
```

But with Quarkus 1.5.0.CR1 this is no longer possible, as it now causes a NoClassDefFoundError during `@QuarkusTest` bootstrap (including via Maven CLI outside IDE):

```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/eclipse/sisu/inject/Weak

	at io.quarkus.test.junit.QuarkusTestExtension.beforeEach(QuarkusTestExtension.java:273)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:161)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:197)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:160)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/sisu/inject/Weak
	at org.codehaus.plexus.component.configurator.converters.lookup.DefaultConverterLookup.<init>(DefaultConverterLookup.java:77)
	at io.quarkus.bootstrap.resolver.maven.BootstrapWagonConfigurator.<init>(BootstrapWagonConfigurator.java:18)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.newRepositorySystem(BootstrapMavenContext.java:567)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getRepositorySystem(BootstrapMavenContext.java:192)
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:123)
	at io.quarkus.bootstrap.BootstrapAppModelFactory.getAppModelResolver(BootstrapAppModelFactory.java:180)
	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:286)
	at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:137)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:131)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:287)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:310)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	... 29 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.sisu.inject.Weak
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 46 more
```

**Expected behavior**

I'm not sure what quarkus-ide-launcher is actually doing ^_^, but based on its name it should not be required outside the IDE ? 

**To Reproduce**
1. mvn maven-dependency-plugin:3.1.2:analyze-only -DfailOnWarning=true

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: MINGW64_NT-10.0 x86_64 Msys
 - Output of `java -version`: java version "11.0.5" 2019-10-15 LTS
 - Quarkus version or git rev: 1.5.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  Apache Maven 3.6.3

**Comment by geoand** [comment]
@aloubyansky seems related to what some folks were reporting about running from tests the IDE, no?

**Comment by aloubyansky** [comment]
Oh, sure, https://github.com/quarkusio/quarkus/blob/master/test-framework/junit5/pom.xml#L22

**Comment by aloubyansky** [comment]
The main issue is about the ide launcher though :) @stuartwdouglas as you mentioned we should at least shade the packaged API. Do you agree?

**Comment by stuartwdouglas** [comment]
Yes, we should shade it. There is not much else we can do, short of writing our own minimal resolver to just resolve the IDE launcher. This would be super error prone though, as it would be hard to make it respect all the relevant maven settings.

**Comment by gsmet** [comment]
Hmmmm, the IDE launcher jar is 10 MB. Do we really want this as a runtime
dependency of the core?

**Comment by geoand** [comment]
It's not added in the prod mode jar IIRC

**Comment by gsmet** [comment]
What do you mean by that? We filter it out of the dependencies?

Because it's there: https://github.com/quarkusio/quarkus/blob/master/core/runtime/pom.xml#L30 .

**Comment by geoand** [comment]
> What do you mean by that? We filter it out of the dependencies?

Exactly: https://github.com/quarkusio/quarkus/blob/b98972432ede88f556c9fcfcf194367742f459cd/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/model/AppModel.java#L197

**Comment by vietk** [comment]
Can't quarkus-core set the dependency as optional for quarkus-ide-launcher ? 
So that's it's not polluting user classpath but you still get it declared as needed by quarkus core?

**Comment by stuartwdouglas** [comment]
It is needed to launch from your IDE. 

Basically we have two competing requirements:
- Be able to launch Quarkus main methods from your IDE
- Not have anything from the processing side on the runtime class path

The way we deal with this is via the ide-launcher dependency. It has the bootstrap code shaded into it, so can be used to initiate the launch of the application, but is then removed from the final application model so it does not end up in the final app.
