### ISSUE TITLE
1.5.0.CR1 ClassCastException in multi-module maven project

### ISSUE THREAD

**Issue by sean-scott-lr** [quarkusio/quarkus#9515]
**Describe the bug**
1.5.0.CR1 introduces a new regression that was not present in 1.4.2.Final.

An invalid ClassCastException occurs within code that was generated by the quarkus-infinispan client during the execution of unit tests.

**Expected behavior**
The Generated code functions without error.

**Actual behavior**
This exception is raised during unit testing:

```

[ERROR] persist_GivenIdentifierWithId_UsesExistingId  Time elapsed: 0.019 s  <<< ERROR!
java.lang.RuntimeException:
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.infinispan.client.deployment.InfinispanClientProcessor#setup threw an exception: java.lang.ClassCastException: class com.lr.core.caching.initializers.IdentifierContextInitializerImpl cannot be cast to class org.infinispan.protostream.SerializationContextInitializer (com.lr.core.caching.initializers.IdentifierContextInitializerImpl is in unnamed module of loader 'app'; org.infinispan.protostream.SerializationContextInitializer is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @58cda03f)
                at io.quarkus.infinispan.client.deployment.InfinispanClientProcessor.setup(InfinispanClientProcessor.java:158)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
                at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
                at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
                at java.base/java.lang.Thread.run(Thread.java:834)
                at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```
 

**To Reproduce**
1. Create a multi-module maven project
2. In module A

- Define a class you wish to use with an infinispan cache. Annotate the class with the appropriate `@ProtoField` annotations. In our case the class is called `Identifier`
- Define the interface required to generate the proto. for example:
```
@AutoProtoSchemaBuilder(
    includeClasses = {Identifier.class},
    schemaPackageName = "com.lr.core.v1.initializer")
public interface IdentifierContextInitializer extends SerializationContextInitializer {}
```

3. in module B ( which depends on module A )
- Define a class which utilizes the classes defined in module A and define the interface required to generate its proto. for example:
```
@AutoProtoSchemaBuilder(
    dependsOn = IdentifierContextInitializer.class,
    includeClasses = DependentClass.class)
public interface DependentClassContextInitializer extends SerializationContextInitializer {}
```

4. Run a test in module B and you will see this exception:
```
[ERROR] persist_GivenIdentifierWithId_UsesExistingId  Time elapsed: 0.019 s  <<< ERROR!
java.lang.RuntimeException:
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.infinispan.client.deployment.InfinispanClientProcessor#setup threw an exception: java.lang.ClassCastException: class com.logrhythm.core.caching.initializers.IdentifierContextInitializerImpl cannot be cast to class org.infinispan.protostream.SerializationContextInitializer (com.lr.core.caching.initializers.IdentifierContextInitializerImpl is in unnamed module of loader 'app'; org.infinispan.protostream.SerializationContextInitializer is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @58cda03f)
	at io.quarkus.infinispan.client.deployment.InfinispanClientProcessor.setup(InfinispanClientProcessor.java:158)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin USMACEA090SSCOT 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

 - Output of `java -version`: 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
1.5.0.CR1

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment]
Thanks a lot of reporting!

Would it be possible for you to provide minimal project that exhibits this behavior?

**Comment by sean-scott-lr** [comment]
@geoand I wish I had the time to do this, as I appreciate the work that the quarkus community does. But I am really overbooked with work at moment.

**Comment by geoand** [comment]
I completely understand. 
Just keep in mind however that a reproducer is the most surefire way for us to act on issues as quickly as possible and fix them before the next release.

**Comment by sean-scott-lr** [comment]
> I completely understand.
> Just keep in mind however that a reproducer is the most surefire way for us to act on issues as quickly as possible and fix them before the next release.

Makes sense.  I will try to get some support on my end to make it easier for us to create bug reproducer projects, as I do see the value in providing this information.

**Comment by geoand** [comment]
Thanks a ton!

**Comment by sean-scott-lr** [comment]
Ok, got some help creating a reproducer. Not though, I wasn't able to reproduce the same error ( during the "build step" as in the exception above.  However, I got a similar exception with the same classes at runtime.

Here is the reproducer:  [https://github.com/sean-scott-lr/quarkus-bug-reproducer](url)

**Comment by geoand** [comment]
Thanks a lot

**Comment by geoand** [comment]
It seems like the failure occurs in tests but not when the jar is used. 

@stuartwdouglas @wburns any idea what we can do to overcome this problem?

The exception I am seeing is:

```
2020-05-22 18:00:43,130 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: e95cb131-409d-4737-9f1a-cc37c4a2efec-1: java.lang.LinkageError: loader constraint violation: loader 'app' wants to load interface org.infinispan.protostream.SerializationContext. A different interface with the same name was previously loaded by io.quarkus.bootstrap.classloading.QuarkusClassLoader @716185fe. (org.infinispan.protostream.SerializationContext is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @716185fe, parent loader 'platform')
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at com.lr.core.model.IdentifierContextInitializerImpl.registerSchema(IdentifierContextInitializerImpl.java:53)
        at com.lr.svc.a.model.SvcAModelContextInitializerImpl.registerSchema(SvcAModelContextInitializerImpl.java:57)
        at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.lambda$handleProtoStreamMarshaller$10(InfinispanClientProducer.java:203)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.handleProtoStreamMarshaller(InfinispanClientProducer.java:202)
        at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.builderFromProperties(InfinispanClientProducer.java:160)
        at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.initialize(InfinispanClientProducer.java:64)
        at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.remoteCacheManager(InfinispanClientProducer.java:281)
        at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.create(InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.zig:202)
        at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.get(InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.zig:232)
        at io.quarkus.infinispan.client.runtime.InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.get(InfinispanClientProducer_ProducerMethod_remoteCacheManager_b4943dc6282b3982ac4ff16d7d4370041f920ead_Bean.zig:267)

```

My hunch is that the annotation processor being used by Infinispan is causing issues for the Quarkus tests.
One reason why I think this is a happening is because if I remove the dependency in Quarkus that brings in the Infinispan annotation processor (`org.infinispan.protostream:protostream-processor`) and simple replace it with with the `protostream` dependnecy, the application gets passed the exception (although it obviously doesn't work because there is no marshaller generated).

**Comment by stuartwdouglas** [comment]
This is due to https://github.com/quarkusio/quarkus/commit/ae19472cc5c166d49a4a105597780de4366d89c0#diff-5c4067844056bb7ffd25622e4fa17116R36

Basically for safety we added in some additional checks for directory elements in the QuarkusClassLoader. Because of the way this project is laid out with parents and children next to each other the discovery generated paths with '../' in them, that interfere with the directory escape protection code.
