### ISSUE TITLE
Hot reload breaks worker thread with a database context when handling a AMQP reactive mesage

### ISSUE THREAD

**Issue by Adelrisk** [quarkusio/quarkus#9613]
**Describe the bug**

My best attempt at persisting database changes while handling a message from AMQP/SmallRye Reactive Messaging will fail the first time, but will succeed for later incoming messages.

EDIT: I've improved my solution, it now only breaks after a hot reload. See https://github.com/quarkusio/quarkus/issues/9613#issuecomment-634486928

**Expected behavior**

Upon receiving an AMQP message, I expect to be able to update the database while handling the message.

**Actual behavior**

I'd like to demonstrate two approaches.

*Approach 1* (fails as expected)

If I make the database changes in the method annotated with `@Incoming`, then it fails:

```java
@Incoming("amqp_channel")
CompletionStage<Void> consumePublishedTenants(Message<JsonObject> message) {

	Publication converted = message.getPayload().mapTo(Publication.class);

	applyChanges(converted);
```

> java.lang.IllegalStateException: You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.
>         at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.checkBlocking(TransactionScopedEntityManager.java:83)

This is obviously self-explanatory and the expected behaviour.

*Approach 2* (fails only once)

Based on the error and hints in the guides, I determined that I should use the Vertx event bus to offload my work into a worker thread, using the `blocking` flag.

```java
@Incoming("amqp_channel")
CompletionStage<Void> consumePublishedTenants(Message<JsonObject> message) {

	Publication converted = message.getPayload().mapTo(Publication.class);
	return this.bus.<Void>request("workaround_channel", converted)
			.subscribeAsCompletionStage()
			.thenCompose((v) -> message.ack());
}

@ConsumeEvent(value = "workaround_channel", blocking = true)
Uni<Void> handlePublication(Publication payload) {
	applyChanges(payload);

	return Uni.createFrom().voidItem();
}
```

This will also fail, however, only the first time!

The same code will successfully persist changes to the databaseFurther events will be processed, the database changes will be applied and the following error will not be given:

> java.lang.IllegalStateException: You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.
>        at io.vertx.core.eventbus.impl.MessageImpl.fail(MessageImpl.java:113)                                                                                                      

**To Reproduce**
This is unfortunately simple to describe, but a hassle to reproduce, because it uses a database and AMQP. However, the main code is above.

1.  Emit AMQP messages
2.  Consume those AMQP messages
   a. Send a message to a Vertx worker thread
   b. Call a `@Transactional` method and access some Panache method

**Configuration**
```properties
amqp-username=${JMS_USERNAME:quarkus}
amqp-password=${JMS_PASSWORD:quarkus}

mp.messaging.incoming.tenant.connector=smallrye-amqp
mp.messaging.incoming.tenant.host=${JMS_HOST_NAME:localhost}
mp.messaging.incoming.tenant.port=${JMS_AMQP_PORT:17501}
```

**Environment (please complete the following information):**
 - Quarkus version or git rev: `1.4.2.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
  > Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
  > Maven home: /home/neil/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
  > Java version: 12.0.2, vendor: Debian, runtime: /usr/lib/jvm/java-12-openjdk-amd64
  > Default locale: en_GB, platform encoding: UTF-8
  > OS name: "linux", version: "5.6.0-2-amd64", arch: "amd64", family: "unix"

**Additional context**

When I add logging to the above code, it produces the following statements for failure:

```
2020-05-26 17:12:00,168 DEBUG [ff.ser.pas.inf.eve.con.TenantConsumer] (vert.x-eventloop-thread-2) Incoming message of tenant update for tenant 0c4033c9-60cb-43e6-b17e-90a867fc20d9                                                                                
2020-05-26 17:12:00,174 DEBUG [ff.ser.pas.inf.eve.con.TenantConsumer] (vert.x-worker-thread-6) Received tenant 0c4033c9-60cb-43e6-b17e-90a867fc20d9                                                                             
2020-05-26 17:12:00,342 DEBUG [ff.ser.pas.app.TenantService] (vert.x-worker-thread-6) Updating 0c4033c9-60cb-43e6-b17e-90a867fc20d9                                                                                                                             
2020-05-26 17:12:00,352 ERROR [ff.ser.pas.app.TenantService] (vert.x-worker-thread-6) Could not update tenant with id 0c4033c9-60cb-43e6-b17e-90a867fc20d9: (RECIPIENT_FAILURE,8185) java.lang.IllegalStateException: You have attempted to perform a blocking operat
ion on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.
        at io.vertx.core.eventbus.impl.MessageImpl.fail(MessageImpl.java:113)                                                     
        at io.quarkus.vertx.runtime.VertxRecorder$3.handle(VertxRecorder.java:86)                                                 
        at io.quarkus.vertx.runtime.VertxRecorder$3.handle(VertxRecorder.java:80)                                                 
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:271)                                                                                                                                                                     
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:249)                                                                                                                                                                      
        at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:573)                                                                                                                                                               
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:532)                                                                                                                                                                 
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)                                                       
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)                                                                                                                                                                       
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)                                                                                                                                                                
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)                                                                                                                                                        
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)                                                           
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)                                                                                                                                                              
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)                                                                                                                                                                                 
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                                                                                                     
        at java.base/java.lang.Thread.run(Thread.java:835)                                                                        

2020-05-26 17:12:00,381 DEBUG [ff.ser.pas.inf.eve.con.TenantConsumer] (vert.x-eventloop-thread-2) Message acknowledged for tenant update for tenant 0c4033c9-60cb-43e6-b17e-90a867fc20d9
```

The next message is processed as follows:
```
2020-05-26 17:13:00,080 DEBUG [ff.ser.pas.inf.eve.con.TenantConsumer] (vert.x-eventloop-thread-2) Incoming message of tenant update for tenant 0c4033c9-60cb-43e6-b17e-90a867fc20d9
2020-05-26 17:13:00,081 DEBUG [ff.ser.pas.inf.eve.con.TenantConsumer] (vert.x-worker-thread-15) Received tenant 0c4033c9-60cb-43e6-b17e-90a867fc20d9
2020-05-26 17:13:00,082 DEBUG [ff.ser.pas.app.TenantService] (vert.x-worker-thread-15) Updating 0c4033c9-60cb-43e6-b17e-90a867fc20d9
2020-05-26 17:13:00,082 DEBUG [ff.ser.pas.app.TenantService] (vert.x-worker-thread-15) Completed 0c4033c9-60cb-43e6-b17e-90a867fc20d9
2020-05-26 17:13:00,083 DEBUG [ff.ser.pas.inf.eve.con.TenantConsumer] (vert.x-eventloop-thread-2) Message acknowledged for tenant update for tenant 0c4033c9-60cb-43e6-b17e-90a867fc20d9
```
That demonstrates (to me) that everything is correctly initiated. This means the bug is either:

- the first call that fails because of the missing worker thread context, or
- every other call that succeeds because the handler is database-oriented

**Comment by Adelrisk** [comment]
I don't know anything any more. Here's code that works* (see when-it-breaks below):

```java
	@ConsumeEvent(value = CALL_SELF, blocking = true)
	Uni<Void> handlePublication(Publication payload) {
		try {
			applyChanges(payload);
			return Uni.createFrom().voidItem();
		} catch(Throwable t) {
			log.error("It broke", t);
			return Uni.createFrom().failure(t);
		}
	}
```

It turns out that my code will never work if `handlePublication` is a void method AND it throws an exception. I have code like this in another service:

```java
	@ConsumeEvent(value = CALL_SELF, blocking = true)
	Uni<Void> handlePublication(Publication payload) {
		applyChanges(payload);
		return Uni.createFrom().voidItem();
	}
```

*The code does not work after a hot-module-replacement. Immediately after HMR, the first message will fail:

> 2020-05-27 09:38:14,870 ERROR [ff.ser.pas.inf.eve.con.TenantConsumer] (vert.x-worker-thread-1) It broke: (RECIPIENT_FAILURE,8185) java.lang.IllegalStateException: You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.

**Comment by Adelrisk** [comment]
As a side note, I'm missing some failure-handing semantics in my message consumer. I can't handle this failure elegantly. I don't want to drop the message by acknowledging it, but if I fail, then the whole subscription will fail and I stop receiving messages until the service/quarkus application is restarted.

**Comment by Adelrisk** [comment]
Quick question: does anyone have an idea how to disable hot reload in dev mode?

**Comment by tlvlp** [comment]
> I don't know anything any more. Here's code that works* (see when-it-breaks below):
> 
> ```java
> 	@ConsumeEvent(value = CALL_SELF, blocking = true)
> 	Uni<Void> handlePublication(Publication payload) {
> 		try {
> 			applyChanges(payload);
> 			return Uni.createFrom().voidItem();
> 		} catch(Throwable t) {
> 			log.error("It broke", t);
> 			return Uni.createFrom().failure(t);
> 		}
> 	}
> ```
> 
> It turns out that my code will never work if `handlePublication` is a void method AND it throws an exception. I have working code like this in another service:
> 
> ```java
> 	@ConsumeEvent(value = CALL_SELF, blocking = true)
> 	Uni<Void> handlePublication(Publication payload) {
> 		applyChanges(payload);
> 		return Uni.createFrom().voidItem();
> 	}
> ```
> 
> *The code does not work after a hot-module-replacement. Immediately after HMR, the first message will fail:
> 
> > 2020-05-27 09:38:14,870 ERROR [ff.ser.pas.inf.eve.con.TenantConsumer] (vert.x-worker-thread-1) It broke: (RECIPIENT_FAILURE,8185) java.lang.IllegalStateException: You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.

Thank you for sharing the details. Your solution for the original issue has worked nicely for me too.. I've been digging around the documentation of both Quarkus and Verx and asked for help as well on the dev discussion board.

Related  #12925

**Comment by Adelrisk** [comment]
> Thank you for sharing the details. Your solution for the original issue has worked nicely for me too.. I've been digging around the documentation of both Quarkus and Verx and asked for help as well on the dev discussion board.

Glad I could help. Not wanting to be picky, I feel that 'solution' is a strong word, I myself view this as a workaround.

As I said, just adding the blocking attribute to the annotation [is not enough](https://github.com/quarkusio/quarkus/issues/9613#issue-625026295):

> Based on the error and hints in the guides, I determined that I should use the Vertx event bus to offload my work into a worker thread, using the blocking flag. [...] This will also fail, however, only the first time!

**Comment by tlvlp** [comment]
Following the logic that solved the EventBus problem with offloading blocking calls to a worker thread I looked for something similar in the SmallRye messaging API and found [this doc on the @Blocking annotation](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/advanced/blocking.html) that might solve your problem without using the EventBus-workaround.

**Comment by Adelrisk** [comment]
That was one of the solutions I iterated over that I never got to work. I can't remember what the exception/reason was, but it didn't work for the described combination of technologies. But thanks anyway :smiley:

**Comment by cescoffier** [comment]
That was fixed already.
See https://github.com/quarkusio/quarkus-quickstarts/blob/master/kafka-panache-quickstart/src/main/java/org/acme/panache/PriceStorage.java as an example.
