### ISSUE TITLE
Unsupported type MethodAccessorGenerator on Kafka

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#9633]
Replicated locally (first seen in https://github.com/quarkusio/quarkus/pull/9486):

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing java.base@11.0.9-internal/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor):
	at java.base@11.0.9-internal/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at java.base@11.0.9-internal/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.base@11.0.9-internal/java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1531)
	at java.base@11.0.9-internal/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.base@11.0.9-internal/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at app//com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:101)
	at java.base@11.0.9-internal/sun.security.ssl.TransportContext$NotifyHandshake.run(TransportContext.java:657)
	at java.base@11.0.9-internal/java.lang.Thread.run(Thread.java:834)
	at app//com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at app//com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

**Comment by galderz** [comment]
[Longer output of failure](https://gist.github.com/galderz/798e6fa9067c89d1ad23f51422aed381).

The key for these issues is figuring out why `ObjectStreamClass` is being brought to the pointsto analysis. The reason `ObjectStreamClass` access is forbidden is because it's the result of serialization that results in new classes being created on the fly.

So. to see what the source really is, we forbid ObjectStreamClass usage with:

```
@TargetClass(java.io.ObjectStreamClass.class)
@SuppressWarnings({"unused"})
final class Target_java_io_ObjectStreamClass {

    @Delete("Object serialization is currently not supported")
    private static native ObjectStreamClass lookup(Class<?> cl, boolean all);

    @Delete("Object serialization is currently not supported")
    private Target_java_io_ObjectStreamClass(final Class<?> cl) {
    }

    @Delete("Object serialization is currently not supported")
    private Target_java_io_ObjectStreamClass() {
    }
}
```

That results in:
```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported constructor java.io.ObjectStreamClass.<init>() is reachable: Object serialization is currently not supported
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace:
	at parsing java.base@11.0.9-internal/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1926)
Call path from entry point to java.io.ObjectInputStream.readNonProxyDesc(boolean):
	at java.base@11.0.9-internal/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1922)
	at java.base@11.0.9-internal/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1829)
	at java.base@11.0.9-internal/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.base@11.0.9-internal/java.io.ObjectInputStream$GetFieldImpl.readFields(ObjectInputStream.java:2591)
	at java.base@11.0.9-internal/java.io.ObjectInputStream.readFields(ObjectInputStream.java:644)
	at java.base@11.0.9-internal/javax.security.auth.Subject.readObject(Subject.java:963)
	at com.oracle.svm.reflect.Subject_readObject_59d6db48bb6a4b2f99935bb5de87f42e62d92681_919.invoke(Unknown Source)
	at java.base@11.0.9-internal/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
	at com.sun.proxy.$Proxy234.hashCode(Unknown Source)
	at java.base@11.0.9-internal/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.base@11.0.9-internal/java.util.Properties.getProperty(Properties.java:1125)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:144)
	at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:345)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
```

[Longer output of above](https://gist.github.com/galderz/5e5c12e479179fc8c39f60322405e023).

**Comment by galderz** [comment]
Created a draft PR: https://github.com/quarkusio/quarkus/pull/9651.

**Comment by galderz** [comment]
New [PR](https://github.com/quarkusio/quarkus/pull/9686) for wider scope.

**Comment by galderz** [comment]
Issue should be fixed with fix in Quarkus.
