### ISSUE TITLE
Accessing database in an custom ConstraintValidator

### ISSUE THREAD

**Issue by halilbahar** [quarkusio/quarkus#9639]
**Describe the bug**
When accessing the database with Hibernate Panache active record pattern or repository pattern in a custom ConstraintValidator and persisting the valid entity afterwards gets stuck in a recursion.

Here is the stacktrace:
```
        at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:116)
        at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:80)
        at org.hibernate.action.internal.EntityInsertAction.preInsert(EntityInsertAction.java:227)
        at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:100)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
        at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348)
        at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:57)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102)
        at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1317)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1397)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1565)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533)
        at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1581)
        at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.count(JpaOperations.java:392)
        at org.acme.entity.PersonPanache.count(PersonPanache.java)
        at org.acme.validation.UniqueValidatorPanache.isValid(UniqueValidatorPanache.java:11)
        at org.acme.validation.UniqueValidatorPanache.isValid(UniqueValidatorPanache.java:8)
        at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:180)
        at org.hibernate.validator.internal.engine.constraintvalidation.SimpleConstraintTree.validateConstraints(SimpleConstraintTree.java:62)
        at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:75)
        at org.hibernate.validator.internal.metadata.core.MetaConstraint.doValidateConstraint(MetaConstraint.java:130)
        at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:123)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:555)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForSingleDefaultGroupElement(ValidatorImpl.java:518)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:488)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:450)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:400)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:172)
        at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:116)
        at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:80)
```
This keeps on until a StackOverflowError is thrown.

**Expected behavior**
The entity should be persisted.

**Actual behavior**
The persist function tries to validate the constraints of the entity thus the custom ConstraintValidator with the database access gets called. The database access function executes (in my example ```PanacheEntity.count()```) and after some internal calls a function  ```org.hibernate.action.internal.EntityInsertAction.executeActions()``` executes a ```org.hibernate.action.internal.EntityInsertAction.preInsert()``` function. This function calls ```at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate()``` and the validate function leads to executing the ```isValid()``` from the Constraint. After that everything starts over again until a StackOverflowError occurs.

**To Reproduce**
1. Add the following extension: ```quarkus-hibernate-orm-panache quarkus-hibernate-validator quarkus-jdbc-postgresql```
2. Create a postgres database: 
```
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 \
           --name postgres-quarkus-hibernate -e POSTGRES_USER=hibernate \
           -e POSTGRES_PASSWORD=hibernate -e POSTGRES_DB=hibernate_db \
           -p 5432:5432 postgres:10.5
```
3. Create an annotation with a custom ConstraintValidator which accesses the database
4. Validate and persist it afterwards when it is valid

I have recreated this issue in this repo: https://github.com/halilbahar/quarkus-validator-panache-bug

**Configuration**
```properties
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = hibernate
quarkus.datasource.password = hibernate
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/hibernate_db
quarkus.hibernate-orm.database.generation = drop-and-create
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
```
Linux halil-MS-7849 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
```
 - GraalVM version (if different from Java):
 - Quarkus version or git rev: 1.4.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/halil/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-31-generic", arch: "amd64", family: "unix"
```

**Comment by gsmet** [comment]
Yeah, I don't think that's Quarkus specific. The validation can't access to the persistence layer as it's integrated with it. You would need to do the checks in your service layer.

**Comment by famod** [comment]
Since non-tivial queries are auto-flushing in Hibernate, you need to switch `FlushMode` before the query:
```
entityManager.setFlushMode(FlushModeType.COMMIT);
```
and in `finally` set it back to what it was before.

This is how we did it in a pretty old project based on JBoss EAP 6.4 (Hibernate 4.2) and IIRC also in a more recent project based on Wildfly Swarm. So I suppose this also works with Quarkus.

**Comment by famod** [comment]
> So I suppose this also works with Quarkus.

It does, we are using this in our current project.

I'll close this accordingly.
