### ISSUE TITLE
Quarkus 1.4.2 Jib package issue while behind a corporate proxy

### ISSUE THREAD

**Issue by gallotor** [quarkusio/quarkus#9682]
**Quarkus container-image-jib failed to download fabric8/java-alpine-openjdk11-jre base image through a http proxy**
I've being testing Quarkus jib and it doesn't seem to work behoind a proxy. My maven settings include the http_proxy config, but for some reasson the quarkus extension is not aware of it and it fails to download the fabric8 base image. 

**Expected behavior**
mvn package task should be able to make use of the user maven settings 

**Actual behavior**
`mvn quarkus:add-extension -Dextensions="container-image-docker"`
`mvn clean package -Dquarkus.container-image.build=true`
```
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Starting container image build
[WARNING] [io.quarkus.container.image.jib.deployment.JibProcessor] Base image 'fabric8/java-alpine-openjdk11-jre' does not use a specific image digest - build may not be reproducible
[ERROR] [io.quarkus.container.image.jib.deployment.JibProcessor] I/O error for image [registry-1.docker.io/fabric8/java-alpine-openjdk11-jre]:
[ERROR] [io.quarkus.container.image.jib.deployment.JibProcessor]     org.apache.http.conn.ConnectTimeoutException
[ERROR] [io.quarkus.container.image.jib.deployment.JibProcessor]     Connect to registry-1.docker.io:443 [registry-1.docker.io/18.213.137.78, registry-1.docker.io/52.4.20.24, registry-1.docker.io/52.5.11.128, registry-1.docker.io/52.54.232.21, registry-1.docker.io/54.236.131.166, registry-1.docker.io/52.72.232.213, registry-1.docker.io/54.85.107.53, registry-1.docker.io/107.23.149.57] failed: connect timed out
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
The package process works just fine in my same enviroment when I don't use my corporate proxy. The extension documentation doesn't seem to have any http proxy config parameter:

> https://quarkus.io/guides/container-image#jib-options

**Configuration**
My settings file. 
```
  <proxies>
    <proxy>
      <id>http</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>10.113.55.36</host>
      <port>8080</port>
    </proxy>

    <proxy>
      <id>https</id>
      <active>true</active>
      <protocol>https</protocol>
      <host>10.113.55.36</host>
      <port>8080</port>
    </proxy>
  </proxies>
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
`1.4.2 final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
`Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)`

**Comment by geoand** [comment]
Thanks for reporting.

The jib extension doesn't currently look into your maven settings to fetch such properties. So as a workaround you can set the necessary settings using something like 

```
mvn clean package -Dquarkus.container-image.build=true -Dhttp.proxyHost=10.113.55.36 ....
```

@aloubyansky I assume bootstrap already handles Maven Settings files correctly. Can I from an extension pull out that information? Would it make sense to make it available as a build item?

**Comment by geoand** [comment]
I agree, I'm just trying to collect all options here.

Thanks for the info @aloubyansky

**Comment by geoand** [comment]
Changing to enhancement because this isn't an actual bug.

It would be nice to have a general way of handling such cases, but given how dynamic Gradle can be, I don't think we can solve anything other than the Maven case.
Furthermore, there might also be other extensions that need to make network calls that would benefit from this same type of thing.

I wonder if it makes sense to have some kind of way of setting proxy fields before a build step is executed and restoring the old values when it's done. This could be driven by a flag perhaps. Or maybe these settings should be applied for the whole build, in which case we would just set them before the build starts.
But again we need a way to know these proxy settings. Maybe we could have a Quarkus build time Config object that we populate only for the case of Maven (for Gradle we could tell users to use `gradle.properties` for example).

WDYT @aloubyansky?

**Comment by aloubyansky** [comment]
I'd probably prefer providing this kind of info on demand instead of looking it up and populating some config objects just in case some one needs them.
I think we could have some kind of Build[System]Context that would be a facade for providing various build-related settings that could be discovered and provided lazily on demand. It could be set on QuarkusBootstrap.Builder that our Maven mojos and Gradle tasks call to initiate the build. It's as straightforward for the devmode though, since it's kind of isolated in a different process.

**Comment by geoand** [comment]
Even in devmode though, we could pass that info to the devmodecontext, righ?

**Comment by aloubyansky** [comment]
If you want to do it now and if we want to support gradle, we'd have to serialize the info to pass to the dev process.
Eventually we are going to introduce custom models in our gradle plugin that will provide app deps and could probably provide this kind of info too. That should be discoverable in dev mode, IDEs, etc.

**Comment by geoand** [comment]
Given that this is the only such case we have so far and that currently container-image only works for the prod-mode, I don't think we need to complicate dev-mode (until we actually have a use case).

**Comment by gallotor** [comment]
Just a quick update, the workarround of setting up the https proxy config from the command line works fine:

`mvn package -Dquarkus.container-image.build=true -Dhttps.proxyHost=10.113.55.36 -Dhttps.proxyPort=8080`

```
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Using base image with digest: sha256:f59f2dfb8dc75e6fbdb3b5661ab88a3a9de960ca8e13ec478f796a6feb62e990
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Container entrypoint set to [java, -Dquarkus.http.host=0.0.0.0, -Djava.util.logging.manager=org.jboss.logmanager.LogManager, -cp, /app/resources:/app/classes:/app/libs/*, io.quarkus.runner.GeneratedMain] 
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Created container image quarkus:0.0.1-SNAPSHOT (sha256:91b248ba31afac2b3e91c12c22f020f21957bfb76181ce31e5f108318d9a1169)

[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 20605ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.369 s
[INFO] Finished at: 2020-06-01T08:45:37+02:00
[INFO] ------------------------------------------------------------------------
```
Thanks for the feedback!

**Comment by geoand** [comment]
Given that 

1) adding `new BootstrapMavenContext().getEffectiveSettings();` into a build step would be rather unclean
2) the workaround is rather simple

I propose we leave this open for now and act on it if lots of folks report it being an issue.

Another thing I thought of is that we could set system properties for the proxy that apply throughout the build based on what is in `proxy`. But again, that's probably something we only want to look into if this becomes an issue.

**Comment by aloubyansky** [comment]
We can surely set the properties. It seems like in Gradle this is how it's done anyway. And in Maven we can simply set them in Mojos by reading the settings.

**Comment by geoand** [comment]
Exactly, that's what gradle does when user set `systemProps.http.proxyHost=something`.

@aloubyansky do you think setting the properties in the mojos is something we should do now or something we should wait for user demand?

It seems like a reasonable and innocent thing to do :)

**Comment by aloubyansky** [comment]
I wouldn't do it just because we can. I thought JibProcessor or something was missing this info. If it's not the case then I'd wait for a request.

**Comment by aloubyansky** [comment]
My idea was simple: we could provide some NetworkingConfigBuildItem that would expose methods to get proxy settings. But it would resolve them when those methods are actually invoked. In Gradle it would be based on properties. In Maven it would be based on properties + settings. But I would still do that on request.

**Comment by geoand** [comment]
OK yeah. Jib could use this, but since it currently seems to be just an edge case, let's wait and see if more users will request it.

**Comment by vaishnav-piyush** [comment]
I am facing similar issue with gradle. I am using the gradle quarkus plugin and jib to build and publish my image. 

`./gradlew assemble -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.image=<image> -Dquarkus.container-image.username=<image-repo-user> -Dquarkus.container-image.password=<image-repo-password>  -Dhttp.proxyHost=<http-proxy-host> -Dhttp.proxyPort=<port> -Dhttps.proxyHost=<https-proxy-host> -Dhttps.proxyPort=<port>`

The image repository is only accessible via a corporate proxy. 

The issue stated when I first upgraded to Quarkus 3. I have tried with different versions of Quarkus. 


Quarkus  | Result
--------  | ------ | 
3.2.0.Final |✖
3.1.2.Final | ✖
3.1.1.Final | ✖
3.0.2.Final | ✖

I am using Java 11.0.6 and Gradle 8.2.

**Comment by geoand** [comment]
> The issue stated when I first upgraded to Quarkus 3

So it worked with Quarkus 2.16?

**Comment by vaishnav-piyush** [comment]
> 

I have it working in another app which is on Quarkus 2.14.1.Final

**Comment by dprinz** [comment]
Any updates on this. I still have this problem with Quarkus 3.6.6 and Gradle 8.5

**Comment by dprinz** [comment]
Can this be classified as a bug? With Quarkus 3 and Gradle, the jib seems to be unusable behind a proxy.

**Comment by geoand** [comment]
> My idea was simple: we could provide some NetworkingConfigBuildItem that would expose methods to get proxy settings. But it would resolve them when those methods are actually invoked. In Gradle it would be based on properties. In Maven it would be based on properties + settings. But I would still do that on request.

@aloubyansky I wonder if it's time for this :)

**Comment by dprinz** [comment]
Not sure if this is the same bug, but it's also impossible to pass a custom truststore to jib.
Setting  -Djavax.net.ssl.trustStore=cacerts is completely ignored as is -Dhttps.proxyHost=

**Comment by Inithron** [comment]
Hi,
Is there any updated on this issue?

I am using Quarkus 3.17.6 and Gradle 8.12.
I have tried to set the proxy with the 4 possibilities:
1. As JVM arguments: -Dhttps.proxyHost=myProxy
2. In the gradle.properties with systemProp.https.proxyHost=myProxy
3. In the application.properties with quarkus.jib.jvm-arguments=-Dhttps.proxyHost=myProxy
4. In the application.properties with quarkus.jib.jvm-additional-arguments=-Dhttps.proxyHost=myProxy

In all 4 cases I set the proxyHost for http and https. But i get always the following error:
```
> Task :quarkusBuildAppModel
Base image 'registry.access.redhat.com/ubi8/openjdk-17-runtime:1.20' does not use a specific image digest - build may not be reproducible
I/O error for image [registry.access.redhat.com/ubi8/openjdk-17-runtime]:
    java.net.UnknownHostException
    Der angegebene Host ist unbekannt (registry.access.redhat.com)
I/O error for image [localhost:5000/reproducer-for-45472/reproducer-for-45472]:
    java.net.SocketException
    Socket is closed
> Task :quarkusAppPartsBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        	[error]: Build step io.quarkus.container.image.jib.deployment.JibProcessor#buildFromJar threw an exception: java.lang.RuntimeException: Unable to create container image
        	at io.quarkus.container.image.jib.deployment.JibProcessor.containerize(JibProcessor.java:261)
        	at io.quarkus.container.image.jib.deployment.JibProcessor.buildFromJar(JibProcessor.java:188)
        	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        	at java.base/java.lang.Thread.run(Thread.java:833)
        	at org.jboss.threads.JBossThread.run(JBossThread.java:499)
        Caused by: java.util.concurrent.ExecutionException: java.net.UnknownHostException: Der angegebene Host ist unbekannt (registry.access.redhat.com)
        	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:596)
        	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:575)
        	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
        	at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$obtainBaseImagesLayers$6(StepsRunner.java:316)
        	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
        	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        	at java.base/java.lang.Thread.run(Thread.java:833)
        Caused by: java.net.UnknownHostException: Der angegebene Host ist unbekannt (registry.access.redhat.com)
        	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
        	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
        	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
        	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        	at com.google.api.client.http.apache.v2.ApacheHttpRequest.execute(ApacheHttpRequest.java:73)
        	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
        	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:349)
        	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:266)
        	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:138)
        	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:114)
        	at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:623)
        	at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:434)
        	at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:439)
        	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImages(PullBaseImageStep.java:293)
        	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:158)
        	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:70)
        	... 6 more
```
Another strange thing is that parts of the error message and the stack trace is in German even I have set
```
quarkus.default-locale=en_US
quarkus.locales=en_US
```

**Comment by geoand** [comment]
As far as I can tell from the Jib code, the standard JVM system properties should work. 

If this doesn't work, I suggest debugging `com.google.api.client.http.apache.v2.ApacheHttpTransport` and specifically the `newDefaultHttpClientBuilder` method.

In any case, it doesn't look like there is much we can on the Quarkus side, so I am going to close this

**Comment by CoderYellow** [comment]
for gradle the root cause is , Jib runs inside the Quarkus build worker, which does NOT inherit http_proxy from the shell (Java wants -Dhttps.proxyHost, and the Gradle plugin forwards only quarkus.* properties to that worker).
can we fix this

**Comment by geoand** [comment]
That's interesting!

Would you like to propose changes?
