### ISSUE TITLE
IllegalArgumentException for unknown path in resteasy / undertow

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#9683]
**Describe the bug**
I have an application with both RESTEasy and Undertow, when I hit a non-existing endpoint, instead of having a 404 I have a 500 error with an `IllegalArgumentException`.

This is happening in production mode.

**Expected behavior**
404 status code with a correct message.

**Actual behavior**
```
org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: Illegal character in hostname at index 15: http://Optional[localhost:8080]/hello2
    at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
    at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:256)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
    at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
    at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.sendError(ResteasyFilter.java:65)
    at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:172)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
    at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:28)
    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
```

**To Reproduce**
I discover this while working on this PR #9267 not sure it is reproductible out of it.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 11.0.7
 - Quarkus version or git rev: master

**Comment by loicmathieu** [comment]
No idea but as it's very old let's close it for now.

**Comment by geoand** [comment]
👍🏼
