### ISSUE TITLE
Failing to find default configuration converters when running from IDE

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#9776]
**Describe the bug**
While attempting to debug an issue from IDEA, I couldn't start my `@QuarkusTest` annotated integration test as I'd get:

```
Caused by: java.lang.IllegalArgumentException: No Converter registered for class io.quarkus.runtime.configuration.MemorySize
	at io.smallrye.config.SmallRyeConfig.lambda$getConverter$1(SmallRyeConfig.java:202)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
	at io.smallrye.config.SmallRyeConfig.getConverter(SmallRyeConfig.java:199)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getConverter(BuildTimeConfigurationReader.java:682)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.readConfigValue(BuildTimeConfigurationReader.java:625)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.readConfigGroup(BuildTimeConfigurationReader.java:571)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.readConfigGroup(BuildTimeConfigurationReader.java:612)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:285)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:241)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:203)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:135)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:104)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:247)
```

A quick look in `io.smallrye.config.SmallRyeConfig#getConverter` with the debugger reveals that there's a classloader mismatch, so we fail to lookup the right converter from the `converters` map.

The class it's trying to find a converter for was loaded by `QuarkusClassLoader:Augmentation Class Loader`, while the same-named class which is available in the map was loaded by `QuarkusClassLoader:Deployment Class Loader`.

**To Reproduce**
I'm afraid not easy. I don't seem able to reproduce it reliably, it seems to occasionally fail with the tests I'm working with.
I happen to work on integration tests for Hibernate Reactive, but I don't think it matters. We're also not setting any configuration property which would need this specific converter.

**Comment by stuartwdouglas** [comment]
Is this still an issue? I run tests from the IDE all the time and have not seen this.

**Comment by Sanne** [comment]
Let's close, I can no longer reproduce it. Thanks!
