### ISSUE TITLE
@GraphQLApi without @ActivateRequestContext gives a ContextNotActiveException

### ISSUE THREAD

**Issue by marceloverdijk** [quarkusio/quarkus#9786]
As discussed [here](https://groups.google.com/forum/#!topic/quarkus-dev/AGem0DpyE8A) the Quarkus GraphQL integration with `@GraphQLApi` itself gives a `ContextNotActiveException` when using Panache.

```
@GraphQLApi
public class MyGraphQLApi {

    private final ContinentTypeMapper continentTypeMapper;

    public MyGraphQLApi(ContinentTypeMapper continentTypeMapper) {
        this.continentTypeMapper = continentTypeMapper;
    }

    @Query("continents")
    @Description("Get a list of continents")
    public List<ContinentType> getContinents() {
        return continentTypeMapper.toContinentTypes(Continent.findAll(Continent.DEFAULT_SORT).list());
    }
}
```

leads to:

```
Data Fetching Error: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
        at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.arc$delegate(RequestScopedEntityManagerHolder_ClientProxy.zig:68)
        at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.getOrCreateEntityManager(RequestScopedEntityManagerHolder_ClientProxy.zig:220)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:77)
        at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.createQuery(TransactionScopedEntityManager.java:316)
        at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.createQuery(ForwardingEntityManager.java:142)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createBaseQuery(CommonPanacheQueryImpl.java:360)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.createQuery(CommonPanacheQueryImpl.java:315)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.list(CommonPanacheQueryImpl.java:266)
        at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.list(PanacheQueryImpl.java:149)

```

When changing it to:

```
@GraphQLApi
@ApplicationScoped
@ActivateRequestContext
public class MyGraphQLApi {

    ..
}
```

it works.

It would be nice if the `@ActivateRequestContext` is activated automatically.

**Comment by jmartisk** [comment]
I think we should be automatically activating the request context for GraphQL API methods, similar as we do for JAX-RS methods. I'll take a look
