### ISSUE TITLE
NPE Building with fast-jar

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#9788]
A project which builds fine without this option throws a NPE when using it:

--- quarkus-maven-plugin:1.5.0.Final:build (default) @ jg-ukheshe-deployable ---
[org.jboss.threads] JBoss Threads version 3.1.1.Final
[org.hibernate.Version] HHH000412: Hibernate ORM core version 5.4.16.Final
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time:  6.826 s
Finished at: 2020-06-04T15:03:40+02:00
------------------------------------------------------------------------
Failed to execute goal io.quarkus:quarkus-maven-plugin:1.5.0.Final:build (default) on project jg-ukheshe-deployable: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.NullPointerException
	at java.base/java.nio.file.Files.provider(Files.java:100)
	at java.base/java.nio.file.Files.createDirectory(Files.java:689)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
	at java.base/java.nio.file.Files.createDirectories(Files.java:742)
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:388)
	at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

Not sure if its obvious as to wheat is going wrong or if more details are required

**Comment by geoand** [comment]
Do you have a small reproducer project reproducing this problem?

**Comment by bcluap** [comment]
I don't as its on a full project build right now - hoped it would be able to be diagnosed by seeing where the NPE is coming from. Will try and put one together

**Comment by geoand** [comment]
A couple of questions:

* where in the file system are you running the build?
* which quarkus extensions are you using?

**Comment by geoand** [comment]
Do you perhaps have any classes in your library that aren't in any java package?

**Comment by bcluap** [comment]
![image](https://user-images.githubusercontent.com/26746221/83772529-c5579780-a683-11ea-8a48-a0bd72be8201.png)

**Comment by geoand** [comment]
Yeah, the `default` package is the problem. I'll open a PR to fix it

**Comment by geoand** [comment]
Thanks for the great info :wink:
