### ISSUE TITLE
NPE Under high load in io.undertow.vertx.VertxHttpExchange.getSourceAddress

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#9807]
**Describe the bug**
Under high load (+5000 tps) and concurrency we intermittently see an NPE in the logs when a servlet filter tried to read the callers IP address. This must be a race condition of sorts. I cant create a reproducer due to the intermittency it happens at but maybe Stewart or someone familiar with this code can work out how this race can occur.

If you need more details of the call flow let me know.

**Expected behavior**
No NPE should occur

**Actual behavior**
NPE happens intermittently (maybe once in a million requests)

**To Reproduce**
I can't reliably reproduce :-(

**Configuration**
```properties
NA

```

**Screenshots**
NA
**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux pcb 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
1.5.0.Final (Also on 1.4.2.Final)
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
NA
**Additional context**

```
: null: java.lang.NullPointerException
	at io.undertow.vertx.VertxHttpExchange.getSourceAddress(VertxHttpExchange.java:381)
	at io.undertow.server.HttpServerExchange.getSourceAddress(HttpServerExchange.java:750)
	at io.undertow.servlet.spec.HttpServletRequestImpl.getRemoteAddr(HttpServletRequestImpl.java:877)
	at javax.servlet.ServletRequestWrapper.getRemoteAddr(ServletRequestWrapper.java:222)
	at guru.jini.arch.impl.other.BaseHttpImpl.getRemoteAddr(BaseHttpImpl.java:332)
	at guru.jini.arch.impl.other.AhcHttpImpl_ClientProxy.getRemoteAddr(AhcHttpImpl_ClientProxy.zig:406)
	at guru.jini.arch.impl.aaa.BasicUserData.enrichWith(BasicUserData.java:57)
	at guru.jini.arch.impl.aaa.BasicUserData.<init>(BasicUserData.java:50)
	at guru.jini.arch.impl.aaa.AbstractUserDataProvider.getSystemUser(AbstractUserDataProvider.java:41)
	at guru.jini.arch.impl.aaa.UssdAwareUserServiceUserDataProvider_ClientProxy.getSystemUser(UssdAwareUserServiceUserDataProvider_ClientProxy.zig:448)
	at guru.jini.arch.conductor.aaa.impl.JwtAuthenticationProvider.authenticate(JwtAuthenticationProvider.java:141)
	at guru.jini.arch.conductor.aaa.impl.IpAwareJwtAuthenticationProvider.authenticate(IpAwareJwtAuthenticationProvider.java:34)
	at guru.jini.arch.conductor.aaa.impl.UssdAwareJwtAuthenticationProvider.authenticate(UssdAwareJwtAuthenticationProvider.java:34)
	at guru.jini.arch.conductor.aaa.impl.WhatsappAndUssdAwareJwtAuthenticationProvider.authenticate(WhatsappAndUssdAwareJwtAuthenticationProvider.java:36)
	at guru.jini.arch.conductor.aaa.impl.WhatsappAndUssdAwareJwtAuthenticationProvider_ClientProxy.authenticate(WhatsappAndUssdAwareJwtAuthenticationProvider_ClientProxy.zig:159)
	at guru.jini.arch.conductor.aaa.ConductorAaa.doIncomingAaa(ConductorAaa.java:42)
	at guru.jini.arch.conductor.ConductorFilter.doFilter(ConductorFilter.java:230)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$10$1$1.call(UndertowDeploymentRecorder.java:563)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:113)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
	at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$6$1.run(UndertowDeploymentRecorder.java:396)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

```

**Comment by jaikiran** [comment]
This change https://github.com/quarkusio/quarkus-http/pull/36 should prevent that NPE. I'm however unsure why this should show up (only) in high load case and whether or not after fixing this NPE, it will show up as some other issue. We'll probably have to wait and see after that NPE fix is applied.

**Comment by stuartwdouglas** [comment]
This should be fixed now.
