### ISSUE TITLE
Dev tools - CLI Native Tool, Native Test Suite, unresolvable reflection configuration

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus#9825]
**Describe the bug**
It seem that Native Image test suite fails in Devtools module, consistently on several re-runs ```./mvnw verify -Pnative-image -rf :quarkus-cli```
See:
```
Error: Error parsing reflection configuration in /home/karm/workspaceRH/Mandrel/quarkus/devtools/aesh/reflectconfigs/quarkuscli.json:
Field io.quarkus.cli.commands.QuarkusCommand.help not found. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
```

**Expected behavior**
It passes.

**Actual behavior**
```
[quarkus-cli-999-SNAPSHOT:31623]    classlist:   2,473.37 ms,  0.93 GB
[quarkus-cli-999-SNAPSHOT:31623]        (cap):     378.42 ms,  0.93 GB
[quarkus-cli-999-SNAPSHOT:31623]        setup:     533.85 ms,  0.93 GB
Error: Error parsing reflection configuration in /home/karm/workspaceRH/Mandrel/quarkus/devtools/aesh/reflectconfigs/quarkuscli.json:
Field io.quarkus.cli.commands.QuarkusCommand.help not found. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationFiles.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1722)
```
Full log: https://gist.github.com/Karm/417149af6c772510c7d52095bc5ac494

**To Reproduce**
1. ./mvnw verify -Pnative-image

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux x86_64
 - Output of `java -version`: OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)

 - GraalVM version (if different from Java):  The same
 - Quarkus version or git rev:  Master, e99fded
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  ./mvnw

**Comment by geoand** [comment]
@Karm is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feedback
