### ISSUE TITLE
Cannot override quarkus.datasource.* attributes with environment variables if the property is not present in application.properties

### ISSUE THREAD

**Issue by tqvarnst** [quarkusio/quarkus#988]
Problem:
Cannot override shamrock.datasource.* attributes with environment variables

Why: 
It's a common pattern in containers to use environment variables for certain configs like datasource url.

Reproduce:
1.  create a JPA project and set microprofile-config.properties:
```
shamrock.datasource.url=jdbc:postgresql://localhost:5432/catalog_db
shamrock.datasource.driver=org.postgresql.Driver
shamrock.datasource.username=catalog
shamrock.datasource.password=secret


shamrock.datasource.max-size=8
shamrock.datasource.min-size=2
shamrock.hibernate.schema-generation.database.action=create-drop
shamrock.hibernate.show_sql=true
```

2. Build a native image `mvn clean package -Pnative`
3. Start a postgressql
```
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 --name postgres-protean-hibernate -e POSTGRES_USER=catalog -e POSTGRES_PASSWORD=secret123 -e POSTGRES_DB=catalog_db -p 5432:5432 postgres:10.5
```
4. Set environment variable and run the application
```
export SHAMROCK_DATASOURCE_PASSWORD=sercret123 && ./target/<name>-runner
```

Expected result:
Successully started application connected to the database

Actual results:
```
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "catalog"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:514)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:454)
        at org.postgresql.Driver.connect(Driver.java:256)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:195)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:323)
        ... 8 more
```

**Comment by gsmet** [comment]
@dmlloyd is it supposed to work, now?

**Comment by dmlloyd** [comment]
No; have a look at https://github.com/quarkusio/quarkus/issues/1887#issuecomment-480978983 for details.

**Comment by dmlloyd** [comment]
Which is to say, giving an env value only works if there's an existing `application.properties` (or other config source) property to override.

**Comment by emmanuelbernard** [comment]
Would be good to document this limitation in the config guide. It will ease the pain until we try and find a better approach. That's acceptable to me.

**Comment by gsmet** [comment]
@dmlloyd I was wondering if this one had been fixed by your big config PR?

**Comment by dmlloyd** [comment]
Yes, it should be.

**Comment by ahofmeister** [comment]
@dmlloyd Than you should close this ticket? :)

**Comment by dmlloyd** [comment]
I suppose so. :-)
