### ISSUE TITLE
Unable to run debezium quarkus integration tests

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#9880]
Not sure where to report this. Probably something for https://github.com/quarkusio/quarkus-platform but no issue tracker there?

Unable to run native tests for debezium:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:native-image (native-image) on project quarkus-universe-integration-tests-debezium-outbox: Failed to generate native image: Failed to resolve artifact io.debezbium:debezium-quarkus-outbox-integration-tests:jar:1.2.0.Beta2: Could not find artifact io.debezbium:debezium-quarkus-outbox-integration-tests:jar:1.2.0.Beta2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :quarkus-universe-integration-tests-debezium-outbox
java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
        at OperatingSystem.exec(qollider.java:1459)
        at MavenTest$Maven.doTest(qollider.java:948)
        at MavenTest$Maven.test(qollider.java:940)
        at MavenTest$RunTest.apply(qollider.java:928)
        at MavenTest$RunTest.apply(qollider.java:914)
        at MavenTest.call(qollider.java:911)
        at MavenTest.call(qollider.java:849)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at Cli.execute(qollider.java:150)
        at qollider.main(qollider.java:112)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
        at OperatingSystem.exec(qollider.java:1453)
        ... 15 more
12:46:58.362 [main] ERROR qollider - Failed executing: ExecResult[exitCode=1, subResult=null]
```

[Longer output](https://gist.github.com/galderz/e6c0223df9f27d414bff65d2edcb55a3)

**Comment by geoand** [comment]
Is this still an issue?

**Comment by galderz** [comment]
Yeah I think so. I can't remember the resolution, but I think it was just a temporary sync issue between quarkus and quarkus-platform.
