### ISSUE TITLE
NPE in QuarkusTestException instead of reporting real boot exception

### ISSUE THREAD

**Issue by rmzzz** [quarkusio/quarkus#9971]
**Describe the bug**
NullPointerException is thrown in QuarkusTestException.runExtensionMethod (line 498 in 1.5.1.Final) because runningQuarkusApplication is null, whereby exception that caused boot to fail is swallowed.

**Expected behavior**
Real cause of failure should be reported.

**Actual behavior**
```
java.lang.NullPointerException
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:498)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeAllMethod(QuarkusTestExtension.java:365)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:68)

```

**To Reproduce**
Looking into the code: QuarkusTestExtension.interceptBeforeAllMethod (see exception stack trace above)
1. ensureStarted is called
2. doJavaStart is called
3. let assume exception is thrown before runningQuarkusApplication is initialized, e.g. in hibernate drop-and-create routine, i.e. runningQuarkusApplication is null
4. exception (or error) is caught in ensureStarted and saved as firstException field and failedBoot=true
5. returned from ensureStarted
6. runExtensionMethod is called
7. attempt to access runningQuarkusApplication results in NPE. (q.e.d.)

**Comment by jaikiran** [comment]
I've opened https://github.com/quarkusio/quarkus/pull/9982 which should prevent the NPE and throw the actual cause of boot failure.
