### ISSUE TITLE
Proxy Https doesnt trap the url Https://domain.com

### ISSUE THREAD

**Issue by jokergit** [quarkusio/quarkus#9981]
**Describe the bug**
Starting a POD Container the following exec of microservices has been implemented:

exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dhttps.proxyHost=proxytmg.gss.rete.poste -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=notify-psd2a-notify .......

During the execution :

200612 21:13:15,681 ERROR [io.qu.ve.ht.ru.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /psd2attiva/v1/accounts failed, error id: 68a56eed-800f-4d84-8434-d081c27f8417-1: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: java.net.UnknownHostException: api.tink.se

**Expected behavior**

Using the : 
https.proxyHost=proxytmg.gss.rete.poste and https.proxyPort=8080.

**Actual behavior**
Not possible to drive correctly the application through the proxy configuration.

**To Reproduce**

launch a Java application with the Proxy Parameter:
Dhttps.proxyHost=proxytmg.gss.rete.poste -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=notify-psd2a-notify 

and try to call a service through the proxy with the protocol begin: https://domain.com

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
sh-4.4$ uname -a
Linux be-psd2a-api-587fbb74fb-428wk 3.10.0-1062.13.1.el7.x86_64 #1 SMP Mon Dec 30 07:54:12 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
sh-4.4$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
1.4.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Macven 3.6.3

**Additional context**
(Add any other context about the problem here.)
Version
OpenShift Master:
v3.11.153
Kubernetes Master:
v1.11.0+d4cacc0
OpenShift Web Console:
v3.11.153

**Comment by jaikiran** [comment]
Hello @jokergit, can you please post the complete exception stacktrace?

**Comment by jokergit** [comment]
Hi @jaikiran ,

as you request:

200613 14:22:38,674 INFO  [it.po.ps.fi.TinkFilter] (executor-thread-1) ---TINK REQUEST:
200613 14:22:38,675 INFO  [it.po.ps.fi.TinkFilter] (executor-thread-1) https://api.tink.se/api/v1/oauth/token 
200613 14:22:38,769 DEBUG [it.po.ps.fi.TinkFilter] (executor-thread-1) grant_type=client_credentials&client_secret=bc2c15b53a4c4ba797b4c0d54f64f6db&scope=user%3Acreate%2Cauthorization%3Agrant%2C+link-session%3Awrite&client_id=6ef096c61c654f31a820ca15e8b7ddae

200613 14:22:38,877 ERROR [io.qu.ve.ht.ru.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /psd2attiva/v1/accounts failed, error id: f689ac19-a6cb-40bc-a7bc-2b5200b42275-1: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: java.net.UnknownHostException: api.tink.se
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:515)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:123)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:87)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.RuntimeException: java.net.UnknownHostException: api.tink.se
	at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.executeRequest(URLConnectionEngine.java:220)
	at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.invoke(URLConnectionEngine.java:58)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:488)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy67.createOAuth2AuthenticationToken(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.interceptorChainCompleted(InvocationContextImpl.java:62)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.proceed(InvocationContextImpl.java:91)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.lambda$syncFlow$5(FaultToleranceInterceptor.java:197)
	at io.smallrye.faulttolerance.core.InvocationContext.call(InvocationContext.java:20)
	at io.smallrye.faulttolerance.core.Invocation.apply(Invocation.java:24)
	at io.smallrye.faulttolerance.core.timeout.Timeout.apply(Timeout.java:39)
	at io.smallrye.faulttolerance.core.retry.Retry.apply(Retry.java:50)
	at io.smallrye.faulttolerance.core.GeneralMetricsRecorder.apply(GeneralMetricsRecorder.java:17)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.syncFlow(FaultToleranceInterceptor.java:199)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.interceptCommand(FaultToleranceInterceptor.java:152)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor_Bean.intercept(FaultToleranceInterceptor_Bean.zig:471)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:154)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.invokeNext(InvocationContextImpl.java:53)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.proceed(InvocationContextImpl.java:89)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
	at com.sun.proxy.$Proxy68.createOAuth2AuthenticationToken(Unknown Source)
	at it.poste.psd2attiva.services.PSD2TokenService.getClientAccessToken(PSD2TokenService.java:59)
	at it.poste.psd2attiva.services.PSD2TokenService.getUserAccessToken(PSD2TokenService.java:82)
	at it.poste.psd2attiva.services.PSD2TokenService_ClientProxy.getUserAccessToken(PSD2TokenService_ClientProxy.zig:281)
	at it.poste.psd2attiva.services.PSD2Service.getAccounts(PSD2Service.java:188)
	at it.poste.psd2attiva.services.PSD2Service_Subclass.getAccounts$$superaccessor9(PSD2Service_Subclass.zig:1866)
	at it.poste.psd2attiva.services.PSD2Service_Subclass$$function$$9.apply(PSD2Service_Subclass$$function$$9.zig:69)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.opentracing.contrib.interceptors.OpenTracingInterceptor.wrap(OpenTracingInterceptor.java:92)
	at io.opentracing.contrib.interceptors.OpenTracingInterceptor_Bean.intercept(OpenTracingInterceptor_Bean.zig:393)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at it.poste.psd2attiva.services.PSD2Service_Subclass.getAccounts(PSD2Service_Subclass.zig:2857)
	at it.poste.psd2attiva.services.PSD2Service_ClientProxy.getAccounts(PSD2Service_ClientProxy.zig:405)
	at it.poste.psd2attiva.resources.PSD2Resource.getAccounts(PSD2Resource.java:279)
	at it.poste.psd2attiva.resources.PSD2Resource_Subclass.getAccounts$$superaccessor35(PSD2Resource_Subclass.zig:1753)
	at it.poste.psd2attiva.resources.PSD2Resource_Subclass$$function$$35.apply(PSD2Resource_Subclass$$function$$35.zig:59)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:69)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor.validateMethodInvocation(JaxrsEndPointValidationInterceptor.java:32)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor_Bean.intercept(JaxrsEndPointValidationInterceptor_Bean.zig:57)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at it.poste.psd2attiva.resources.PSD2Resource_Subclass.getAccounts(PSD2Resource_Subclass.zig:1974)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	... 17 more
Caused by: java.net.UnknownHostException: api.tink.se
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:681)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
	at org.jboss.resteasy.client.jaxrs.engines.URLConnectionEngine.executeRequest(URLConnectionEngine.java:213)
	... 83 more

Thanks you so much,

PS: With Quarkus ver 1.3.2 no issue, for https proxy.

**Comment by jokergit** [comment]
Hi Jaikirian, 
  any news? Btw Quarkus ver 1.1.1 no issue for NoProxyHost Parameter. Actually, i have downgraded the Quarkus release to 1.1.1, to have the Production Test for PosteItaliane.it.

Thanks a lot

**Comment by jaikiran** [comment]
@jokergit, I have been away for a bit and haven't had a chance to look more into this. Any chance you can share a reproducer app (preferably as a github repo with any instructions)? That will make it easier/quicker for some of us to see what's going on.

**Comment by jaikiran** [comment]
@jokergit Can you try this with `1.6.0.CR1` please? There was a similar issue that was reported which has been marked as fixed (due a recent RestEasy project version upgrade) in 1.6.0.CR1.

**Comment by geoand** [comment]
Please give `1.6.1.Final` a try so we can close this if it has been fixed

**Comment by geoand** [comment]
Closing for lack of feeback
